### PR TITLE
opt: fix building of aggregates with outer columns

### LINKED ISSUE #12703: sql: postgres supports aggregate expressions in a subquery referring to the outer query
from section 4.2.8 of https://www.postgresql.org/docs/9.4/static/sql-expressions.html:
"""
When an aggregate expression appears in a subquery (see Section 4.2.11 and Section 9.22), the aggregate is normally evaluated over the rows of the subquery. But an exception occurs if the aggregate's arguments (and filter_clause if any) contain only outer-level variables: the aggregate then belongs to the nearest such outer level, and is evaluated over the rows of that query. The aggregate expression as a whole is then an outer reference for the subquery it appears in, and acts as a constant over any one evaluation of that subquery. The restriction about appearing only in the result list or HAVING clause applies with respect to the query level that the aggregate belongs to.
"""

Haven't thought too much about what this means, but we don't support it.

cc @knz

### PR DESCRIPTION
**Pull request by rytaft**
This commit fixes a bug in which aggregates containing
outer columns were associated with the wrong scope.

For example, consider this query:
```
  SELECT (SELECT max(a.x) FROM b) FROM a;
```
Previously, the inner (subquery) scope was selected as the grouping scope
for `max(a.x)`. However, this was incorrect. The outer scope should
have been selected instead.

In order to fix this issue, this commit makes significant changes
to the way queries are built by the `optbuilder`. It is difficult
to determine whether a particular select clause needs aggregation without
first building the arguments to the aggregates to see whether there are outer
columns. Therefore, this commit makes the following change: before any
expressions in the `SELECT` list are built, all aggregates in the `SELECT`,
`DISTINCT ON`, `ORDER BY`, and `HAVING` clauses are replaced with an `aggregateInfo`.
The `aggregateInfo` contains the function definition, fully built arguments, and
output column of the aggregate.

In order to avoid traversing the expression tree multiple times, the entire
semantic analysis and type checking phase is completed before
building any non-aggregates for these clauses.

This commit avoids allocating slices for analyzed expressions by
instead creating them as columns directly in the scope which will
use them. It later makes another pass through the columns to build them.
    
This and various other performance improvements make the fix for
correlated aggregates perform at parity with the master branch.

Master branch:
```
name                       time/op
Phases/kv-read/OptBuild    18.8µs ± 4%
Phases/planning1/OptBuild  8.06µs ± 3%
Phases/planning2/OptBuild  20.3µs ± 5%
Phases/planning3/OptBuild  22.0µs ± 3%
Phases/planning4/OptBuild  24.1µs ± 4%
Phases/planning5/OptBuild  22.2µs ± 8%
Phases/planning6/OptBuild  36.8µs ± 2%
```
Correlated aggs:
```
name                       time/op
Phases/kv-read/OptBuild    18.4µs ± 3%
Phases/planning1/OptBuild  7.92µs ± 1%
Phases/planning2/OptBuild  20.6µs ± 4%
Phases/planning3/OptBuild  22.2µs ± 4%
Phases/planning4/OptBuild  24.1µs ± 3%
Phases/planning5/OptBuild  21.4µs ± 1%
Phases/planning6/OptBuild  36.3µs ± 2%
```

Fixes #12703

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
I added some initial comments; there's a lot here to digest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-:-LKSpFzw-6wPGZJMQSun:bi5kia)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/typing, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKRva6sB2k9UWg3MHu_:-LKRva6sB2k9UWg3MHua:b-ay68x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/memo/testdata/typing#L385)):*
> ```
>  ├── columns: x:1(int!null) x:3(string) y:2(int)
>  ├── select
>  │    ├── columns: a.x:1(int!null) y:2(int) column6:6(string!null)
> ```

How come these column labels changed? It seems like they were more descriptive as-is.
___
*[pkg/sql/opt/memo/testdata/logprops/groupby, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKRwHNRBu7-bNT-DjiQ:-LKRwHNRBu7-bNT-DjiR:bg78eg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/memo/testdata/logprops/groupby#L208)):*
> ```
> SELECT * FROM xyzs WHERE (SELECT sum(x) FROM (SELECT y, u FROM kuv) GROUP BY u) > 100
> ----
> error (42803): subquery uses ungrouped column "y" from outer query
> ```

A couple things here:
1. Postgres gives a different error for this query: `aggregate functions are not allowed in WHERE`
2. This test cases needs to be updated, since its purpose was not to test `optbuilder` errors. I'd move the `GROUP BY` subquery to be a column in the  `xyzs``SELECT` list instead, where it should be legal.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKS7jrn-SeVJnOjsgKe:-LKS7jrn-SeVJnOjsgKf:bby3mmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/groupby.go#L435)):*
> ```Go
> 		}
> 
> 		cols.UnionWith(b.factory.Memo().GroupProperties(info.args[i]).OuterCols())
> ```

This violates the principle that we should not rely on what we're building to perform semantic analysis. If there's no other clean way to do this, then I think it's OK. However, it seems like we have plenty of info in `aggInfo`, `groupby`, `scopeColumn`, etc., as well as multiple places we could detect an outer column reference (`finishBuildScalarRef`? `buildScalarHelper`?). I'd think there's a good way to do this without resorting to memo group inspection.

You want to define and use a single set of well-defined abstractions to make your code as clean as possible. If you're finding the need to reach outside to other abstractions, it's a probable indication that the ones you've got need to be modified/upgraded.
___
*[pkg/sql/opt/optbuilder/project.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKSHnW50qws3ov0Hg8x:-LKSHnW50qws3ov0Hg8y:b4yn263) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/project.go#L75)):*
> ```Go
> // As a side-effect, the appropriate scopes are updated with aggregations
> // (scope.groupby.aggs)
> func (b *Builder) analyzeProjectionList(
> ```

I suspect this approach is going to lead to measurable performance regression (but you should verify with our micro-benchmark). Allocating slices even when there are no aggregates is not ideal. Think about how to make a "fast path" for case where there are no aggs.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 576 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKSohjg6_vbfArx28Mu:-LKSohjg6_vbfArx28Mv:bksy7j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/scalar.go#L576)):*
> ```Go
> // that reference inScope are either aggregate or grouping columns in inScope.
> func (b *Builder) checkSubqueryOuterCols(subqueryGroup memo.GroupID, inScope *scope) {
> 	subqueryOuterCols := b.factory.Memo().GroupProperties(subqueryGroup).OuterCols()
> ```

More violation of the abstractions that I'd like to avoid if possible. It feels like something needs fixing in the `optbuilder` abstractions instead...
___
*[pkg/sql/opt/optbuilder/scope.go, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKS5U6A8HmrKkS1TC6f:-LKS5U6A8HmrKkS1TC6g:b52h17p) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/scope.go#L489)):*
> ```Go
> 
> 	for curr := s; curr != nil; curr = curr.parent {
> 		if cols.Len() == 0 || cols.Intersects(curr.colSet()) {
> ```

What about case where `cols` contains columns from multiple scopes? Shouldn't there be some kind of error if `cols` is not a subset of whatever scope it intersects?

**Review by rytaft — COMMENTED** [review]
I believe I've made all the changes now. I was able to get the first commit to have performance parity with the master branch:

Master branch:
```
name                       time/op
Phases/kv-read/OptBuild    18.8µs ± 4%
Phases/planning1/OptBuild  8.06µs ± 3%
Phases/planning2/OptBuild  20.3µs ± 5%
Phases/planning3/OptBuild  22.0µs ± 3%
Phases/planning4/OptBuild  24.1µs ± 4%
Phases/planning5/OptBuild  22.2µs ± 8%
Phases/planning6/OptBuild  36.8µs ± 2%
```
Correlated aggs:
```
name                       time/op
Phases/kv-read/OptBuild    18.4µs ± 3%
Phases/planning1/OptBuild  7.92µs ± 1%
Phases/planning2/OptBuild  20.6µs ± 4%
Phases/planning3/OptBuild  22.2µs ± 4%
Phases/planning4/OptBuild  24.1µs ± 3%
Phases/planning5/OptBuild  21.4µs ± 1%
Phases/planning6/OptBuild  36.3µs ± 2%
```

After the latest change to keep track of referenced columns, it's a bit slower. Any ideas about how to improve the latest commit are especially welcome. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-:-LKwr4KDAbP5_QGOvJ-b:bunz646)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/groupby, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKRwHNRBu7-bNT-DjiQ:-LKvfyui5wo202h4NJzm:b-lo71lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/memo/testdata/logprops/groupby#L208)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

A couple things here:
1. Postgres gives a different error for this query: `aggregate functions are not allowed in WHERE`
2. This test cases needs to be updated, since its purpose was not to test `optbuilder` errors. I'd move the `GROUP BY` subquery to be a column in the  `xyzs``SELECT` list instead, where it should be legal.
</blockquote></details>

Done. I think the `aggregate functions are not allowed in WHERE` error is a separate issue from this PR. Filed #29114 to keep track of it.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKS7jrn-SeVJnOjsgKe:-LKwpbwr3-Ooep4Ysftt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/groupby.go#L435)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This violates the principle that we should not rely on what we're building to perform semantic analysis. If there's no other clean way to do this, then I think it's OK. However, it seems like we have plenty of info in `aggInfo`, `groupby`, `scopeColumn`, etc., as well as multiple places we could detect an outer column reference (`finishBuildScalarRef`? `buildScalarHelper`?). I'd think there's a good way to do this without resorting to memo group inspection.

You want to define and use a single set of well-defined abstractions to make your code as clean as possible. If you're finding the need to reach outside to other abstractions, it's a probable indication that the ones you've got need to be modified/upgraded.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/project.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKSHnW50qws3ov0Hg8x:-LKwpg323tz497eL0VBR:b-8ntu0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/project.go#L75)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I suspect this approach is going to lead to measurable performance regression (but you should verify with our micro-benchmark). Allocating slices even when there are no aggregates is not ideal. Think about how to make a "fast path" for case where there are no aggs.
</blockquote></details>

Without the `colRefs` change, this PR is now at parity with master in terms of performance. The `colRefs` change slows it down slightly.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 576 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKSohjg6_vbfArx28Mu:-LKwpwwPEk-Ch8wa8FtD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/scalar.go#L576)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

More violation of the abstractions that I'd like to avoid if possible. It feels like something needs fixing in the `optbuilder` abstractions instead...
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKS5U6A8HmrKkS1TC6f:-LKwpzG2--Io696BHqtK:b-dkvnun) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/scope.go#L489)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What about case where `cols` contains columns from multiple scopes? Shouldn't there be some kind of error if `cols` is not a subset of whatever scope it intersects?
</blockquote></details>

I think it's correct as-is, since it's possible to have an aggregate with columns from multiple scopes. For example:

`SELECT (SELECT max(t.a + u.x), max(t.a) FROM u) FROM t`

The first aggregate `max(t.a + u.x)` contains columns from both the inner and outer scopes, so it is aggregated in the inner scope (subquery). The second aggregate `max(t.a)` only contains columns from the outer scope, so it is aggregated at the outer query. 

Whether we can actually decorrelate this kind of query is another question....
___
*[pkg/sql/opt/memo/testdata/typing, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKRva6sB2k9UWg3MHu_:-LKve6997_kJhAKwWk_K:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/memo/testdata/typing#L385)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come these column labels changed? It seems like they were more descriptive as-is.
</blockquote></details>

Fixed.

**Comment by rytaft** [comment]
Actually... hold off on reviewing the last commit. I'm going to try something else.

**Comment by rytaft** [comment]
Ok, I think I'm happier with this new change. PTAL.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/project.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKSHnW50qws3ov0Hg8x:-LL0Gbrz3tN_111DTHLj:b-bkkuzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/project.go#L75)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Without the `colRefs` change, this PR is now at parity with master in terms of performance. The `colRefs` change slows it down slightly.
</blockquote></details>

I've fixed the colRefs change so it has no noticeable impact on performance. I think the full PR is pretty close to master now, performance-wise.

**Review by andy-kimball — APPROVED** [review]
:lgtm:, while there are still things that I think could be improved, this is a step forward in correctness, and I think we should move forward. I suspect we'll have future ideas on how to further simplify the design, and we can pursue those at that point. Congrats on finding ways to preserve our performance in important simple cases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-:-LL17jfN9byCb47MbS11:b-fyh0eu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0qbmXAIYOKA-f6d55:-LL0qbmXAIYOKA-f6d56:b-p2fbn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/groupby.go#L174)):*
> ```Go
> // buildAggregation builds the pre-projection and the aggregation operators.
> // Returns the output scope for the aggregation operation.
> func (b *Builder) buildAggregation(
> ```

I'm not loving this function, with no less than 5 scopes passed to it...not sure how to improve, though.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 266 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0r6ds2wCshYKvGjLi:-LL0r6ds2wCshYKvGjLj:b-fhxup8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/groupby.go#L266)):*
> ```Go
> 			// Update the subquery with any outer columns from the aggregate
> 			// arguments.
> 			b.subquery.outerCols.UnionWith(agg.colRefs.Difference(fromCols))
> ```

How come  `finishBuildScalarRef` wouldn't add these outer columns? I hate to see special cases like this, since it suggests problems with the abstractions...
___
*[pkg/sql/opt/optbuilder/scalar.go, line 114 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0ttRpBTeMJmnY3kYU:-LL0ttRpBTeMJmnY3kYV:b-6h9ssw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/scalar.go#L114)):*
> ```Go
> // values.
> func (b *Builder) buildScalar(
> 	scalar tree.TypedExpr, inScope, outScope *scope, outCol *scopeColumn, colRefs *opt.ColSet,
> ```

Should `colRefs` be an `outerCols` field in `inScope`? The meaning would be, "the set of columns referenced by expressions built with respect to this scope, which are not part of this scope".
___
*[pkg/sql/opt/optbuilder/scalar.go, line 122 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0rjar4jt7j0S-Kv7v:-LL0rjar4jt7j0S-Kv7w:b-3quggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/scalar.go#L122)):*
> ```Go
> 	// grouping expressions are built as part of the same projection.
> 	inGroupingContext := inScope.inGroupingContext() && !inScope.groupby.inAgg &&
> 		!inScope.groupby.inGroupings
> ```

Confusing naming here: `inGroupingContext` vs. `inGroupings`. Maybe `buildingGroupingCols` instead?
___
*[pkg/sql/opt/optbuilder/scope.go, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LKS5U6A8HmrKkS1TC6f:-LL0lew-7V5owJ2mngcm:brz70st) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f37aec66f4bb02576264b75e89313194947d3a/pkg/sql/opt/optbuilder/scope.go#L489)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think it's correct as-is, since it's possible to have an aggregate with columns from multiple scopes. For example:

`SELECT (SELECT max(t.a + u.x), max(t.a) FROM u) FROM t`

The first aggregate `max(t.a + u.x)` contains columns from both the inner and outer scopes, so it is aggregated in the inner scope (subquery). The second aggregate `max(t.a)` only contains columns from the outer scope, so it is aggregated at the outer query. 

Whether we can actually decorrelate this kind of query is another question....
</blockquote></details>

I see, I didn't realize that was allowed by SQL.
___
*[pkg/sql/opt/optbuilder/util.go, line 179 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0nxvE94QjSX_nho7J:-LL0nxvE94QjSX_nho7K:b-hdns1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/util.go#L179)):*
> ```Go
> }
> 
> // buildSynthesizedColumn is similar to synthesizeColumn, but it fills in the
> ```

How about `populateSynthesizedColumn` instead, then?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 174 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0qbmXAIYOKA-f6d55:-LL1BO7tAOaidSi2p7ON:b-rxb3dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/groupby.go#L174)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm not loving this function, with no less than 5 scopes passed to it...not sure how to improve, though.
</blockquote></details>

I think one way to do it would be to split this up into two or three functions. These three lines are the same as when there are no aggregations, and they are the only lines that require `orderByScope` and `distinctOnScope`: 
```
b.buildProjectionList(fromScope, projectionsScope)
b.buildOrderBy(fromScope, projectionsScope, orderByScope)
b.buildDistinctOnArgs(fromScope, projectionsScope, distinctOnScope)
```
I'd rather save that change for another PR, though.... created #29215 to track it.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 266 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0r6ds2wCshYKvGjLi:-LL1EO6T5dZHVc2XR6vw:b-sejkan) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/groupby.go#L266)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come  `finishBuildScalarRef` wouldn't add these outer columns? I hate to see special cases like this, since it suggests problems with the abstractions...
</blockquote></details>

`buildAggregateFunction` ensures that `finishBuildScalarRef` doesn't add the outer columns by temporarily setting `b.subquery` to `nil`. It does this since we don't yet know which is the appropriate scope to add them to.  I fleshed out the comment a bit.

I think this is a reasonable special case, since this is the one case where we don't know the correct scope at build time.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 114 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0ttRpBTeMJmnY3kYU:-LL1G2_B6P-u6wp2H6l2:b-fysjhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/scalar.go#L114)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should `colRefs` be an `outerCols` field in `inScope`? The meaning would be, "the set of columns referenced by expressions built with respect to this scope, which are not part of this scope".
</blockquote></details>

I considered a few different options, including adding a field to `inScope` and/or `outScope`. I think this way is better since we only pass `colRefs` when we actually need it (for building aggregation columns), and therefore we don't waste time updating the `ColSet` in other cases (when `colRefs` is `nil`). 

Also, we need the set of columns at the individual expression level, not the scope level, since there may be multiple aggregate functions in a single `SELECT` statement that belong to different scopes.

I agree it's not ideal to add another parameter, but it seemed like the least-bad option.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 122 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0rjar4jt7j0S-Kv7v:-LL1Ido0ENi7r6aHax6c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/scalar.go#L122)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Confusing naming here: `inGroupingContext` vs. `inGroupings`. Maybe `buildingGroupingCols` instead?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/util.go, line 179 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-LL0nxvE94QjSX_nho7J:-LL1Is8Y6Dhi3FD7Xc0Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5aa6f0ae77f0fb941311d240af9f4f36d20463/pkg/sql/opt/optbuilder/util.go#L179)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How about `populateSynthesizedColumn` instead, then?
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
TFTR! Going to merge this now, and can add any follow ups in another PR.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28774#-:-LL1VZ9g4SfMbGmusmfw:b-tre189)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by rytaft** [comment]
Thanks! Regarding documentation, I think the info you found in #12703 is a good place to start. Happy to help give more details or examples.

**Comment by jseldess** [comment]
Create a docs issue for this: https://github.com/cockroachdb/docs/issues/3679. 

@rytaft, for future reference, it's best to add a `Release note` text for such work. It's the main way I catch user-facing changes that need to be documented.

**Pull request merged**
