### PR TITLE
sql: implement SHOW [ALL] CLUSTER SETTINGS FOR TENANT

### PR DESCRIPTION
**Pull request by knz**
All commits but the last 2 from #77740.
(Reviewers: only the last 2 commits belong to this PR.)

Informs #77471

Release justification: low risk, high benefit changes to existing functionality

### CODE REVIEW

**Comment by knz** [comment]
Note to self: need to introduce a decode function to decode the `value` column in the COALESCE clause.

**Comment by knz** [comment]
Updated to reflect #77935.

**Comment by knz** [comment]
RFAL

**Review by rafiss — CHANGES_REQUESTED** [review]
just had small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-:-MyzR4UeBaIrY2-T40lR:b-wkey1b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[-- commits, line 22 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzMq7HEUpXT2IVeJMY):*
does this need a release note?
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 69 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzMvUq8Om8G0YLflu7:-MyzMvUq8Om8G0YLflu8:b-3ecvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L69)):*
> ```Go
> 	if !d.evalCtx.Codec.ForSystemTenant() {
> 		return nil, pgerror.Newf(pgcode.InsufficientPrivilege,
> 			"SHOW CLUSTER SETTINGS FOR TENANT can only be called by system operators")
> ```

nit: is the term "on the system tenant" more familiar than "by system operatosr"
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzO6KI7aIL_k33HMUr:-MyzO6KJ1IsEsD7yI-pV:b9kfrpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L84)):*
> ```Go
>   isvalid AS (
>     SELECT
>       IF(tenant_id=0,
> ```

i think this would be more readable with:
```
CASE
  WHEN tenant_id=0 THEN ...
  WHEN tenant_id=1 THEN ...
  WHEN st.id IS NULL THEN ...
  ELSE 0
END
```
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 85 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzNGVn0Q_nuP-wUNvH:-MyzNGVn0Q_nuP-wUNvI:b1nyxad) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L85)):*
> ```Go
>     SELECT
>       IF(tenant_id=0,
>          crdb_internal.force_error('22023', 'tenant ID must be non-zero'),
> ```

why do this validation / error creation in SQL rather than go code? 
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 98 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzOpfL0zWi3y2RNQLB:-MyzOpfL0zWi3y2RNQLC:bxqmss1) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L98)):*
> ```Go
>   crdb_internal.decode_cluster_setting(allsettings.variable,
>      -- NB: careful not to coalesce with allsettings.value directly!
>      -- This is the value fo the system tenant and is not relevant to other tenants.
> ```

nit: "fo"
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 107 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzP7kF7fbo-rGcFOPH:-MyzP7kF7fbo-rGcFOPI:bwp3s6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L107)):*
> ```Go
>   allsettings.type,
>   ` + publicCol + `
>   IF(tenantspecific.value IS NOT NULL, 'per-tenant-override',
> ```

i think `CASE` would be more readable here too
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 112 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzQ2l_-ft88GwQ-Iwo:-MyzQ2la-TX5B7RHRJfW:b-xvgob1) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L112)):*
> ```Go
>   allsettings.description
> FROM
>   (SELECT * FROM system.crdb_internal.cluster_settings ` + publicFilter + `) AS allsettings
> ```

since there already are CTEs in this query, i wonder if this would be more understandable if CTEs were used for `allsettings` and `tenantspecific` instead of subqueries?
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 113 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzQOeJAGXHo-ER7q28:-MyzQOeJAGXHo-ER7q29:b-wxlm9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L113)):*
> ```Go
> FROM
>   (SELECT * FROM system.crdb_internal.cluster_settings ` + publicFilter + `) AS allsettings
>   LEFT JOIN (SELECT * FROM system.tenant_settings t, tenant_id WHERE t.tenant_id = tenant_id.tenant_id) AS tenantspecific ON
> ```

here and the above lines, would be a bit safer and easier to read this if the columns were named explicitly instead of using `*`
___
*[pkg/sql/sem/builtins/builtins.go, line 4632 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLcJhDE-8ptk_bbUU:-MyzLcJm9hTVV3BcD9fu:b-bk7p9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4632)):*
> ```Go
> 				setting, ok := rawSetting.(settings.NonMaskedSetting)
> 				if !ok {
> 					return nil, errors.AssertionFailedf("setting '%s' is masked", name)
> ```

should this be a user-friendly error?
___
*[pkg/sql/sem/builtins/builtins.go, line 4664 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLlQU6RRoWo9zwb4i:-MyzLlQU6RRoWo9zwb4j:b-jx817a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4664)):*
> ```Go
> 				)
> 				if !ok {
> 					return nil, errors.Newf("unknown cluster setting '%s'", name)
> ```

could this have a `pgcode`?
___
*[pkg/sql/sem/builtins/builtins.go, line 4668 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLoyfC4hvFCXtLyc3:-MyzLoyfC4hvFCXtLyc4:b-bk7p9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4668)):*
> ```Go
> 				setting, ok := rawSetting.(settings.NonMaskedSetting)
> 				if !ok {
> 					return nil, errors.AssertionFailedf("setting '%s' is masked", name)
> ```

should this be a user-friendly error?
___
*[pkg/sql/sem/builtins/builtins.go, line 4676 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLwC2CAxlTmIQ6IhO:-MyzLwC2CAxlTmIQ6IhP:b-nk59s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4676)):*
> ```Go
> 				return tree.NewDString(repr), nil
> 			},
> 			Info:       "Returns the encoded default value of the given cluster setting.",
> ```

remove "default" and change "encoded" to "decoded" (or reword as you like)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rafiss)

___
*[-- commits, line 22 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzMq7HEUpXT2IVeJMY):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this need a release note?
</blockquote></details>

I don't believe so, since the tenant config stuff is not visible to end-users? 
Let me know what you think.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 69 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzMvUq8Om8G0YLflu7:-MzpRSkB0ciQAyK8K0TN:brl5jno) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L69)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: is the term "on the system tenant" more familiar than "by system operatosr"
</blockquote></details>

I reused the same words as was originally implemented by adam in sql/tenant_settings.go for consistency.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzO6KI7aIL_k33HMUr:-MzpRXO3-tjob5F14K-E:b-o4ly33) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L84)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this would be more readable with:
```
CASE
  WHEN tenant_id=0 THEN ...
  WHEN tenant_id=1 THEN ...
  WHEN st.id IS NULL THEN ...
  ELSE 0
END
```
</blockquote></details>

Good call! Done.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 85 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzNGVn0Q_nuP-wUNvH:-MzpRl3g2Fqmi1uDDHPY:b-8lxdjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L85)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do this validation / error creation in SQL rather than go code? 
</blockquote></details>

Added a comment to explain.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 107 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzP7kF7fbo-rGcFOPH:-MzpSFh7-p1zqM8mlSq9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L107)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think `CASE` would be more readable here too
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 112 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzQ2l_-ft88GwQ-Iwo:-MzpTyxE7-u5EUmBTo5O:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L112)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since there already are CTEs in this query, i wonder if this would be more understandable if CTEs were used for `allsettings` and `tenantspecific` instead of subqueries?
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 113 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzQOeJAGXHo-ER7q28:-MzpU-HH-FXyrWsEIsAp:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L113)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

here and the above lines, would be a bit safer and easier to read this if the columns were named explicitly instead of using `*`
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 4632 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLcJhDE-8ptk_bbUU:-MzpU13JA419BPi8a23s:beapc40) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4632)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be a user-friendly error?
</blockquote></details>

The user-friendly error is just above: "unknown cluster setting". Masked settings should already been invisible to the Lookup function. If we get here and we still have a masked setting, this means that Lookup did not do its job properly, so that's an assertion failure.
___
*[pkg/sql/sem/builtins/builtins.go, line 4664 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLlQU6RRoWo9zwb4i:-MzpUVuq7vVe8w77XjpY:bb061qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4664)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could this have a `pgcode`?
</blockquote></details>

I'm not opposed, but then I'd like to use a separate PR for this: the base case in `sql/set_cluster_setting.go` doesn't use a pgcode yet either, and we'd want both to be consistent.
___
*[pkg/sql/sem/builtins/builtins.go, line 4668 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLoyfC4hvFCXtLyc3:-MzpUUsgAeQlouTaXLq1:bfr6s04) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4668)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be a user-friendly error?
</blockquote></details>

see comment above.
___
*[pkg/sql/sem/builtins/builtins.go, line 4676 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLwC2CAxlTmIQ6IhO:-MzpUtIv3YKeepYZbRF8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4676)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

remove "default" and change "encoded" to "decoded" (or reword as you like)
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-:-MzvPDQs3UMuyXp6HYFQ:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[-- commits, line 22 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzMq7HEUpXT2IVeJMY):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't believe so, since the tenant config stuff is not visible to end-users? 
Let me know what you think.
</blockquote></details>

sgtm!
___
*[pkg/sql/delegate/show_all_cluster_settings.go, line 85 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzNGVn0Q_nuP-wUNvH:-MzvOQ8d-toBQcG7ihfC:b-k73z76) ([raw file](https://github.com/cockroachdb/cockroach/blob/39da85405e4f36c95ef2db7ab1b2969cbbe622be/pkg/sql/delegate/show_all_cluster_settings.go#L85)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Added a comment to explain.
</blockquote></details>

thanks
___
*[pkg/sql/sem/builtins/builtins.go, line 4632 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/77742#-MyzLcJhDE-8ptk_bbUU:-MzvP41e0ZbNk8f7ySHd:btndgms) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8f5c5b037ad6d6f090084f62eb4e49f6b8979b/pkg/sql/sem/builtins/builtins.go#L4632)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The user-friendly error is just above: "unknown cluster setting". Masked settings should already been invisible to the Lookup function. If we get here and we still have a masked setting, this means that Lookup did not do its job properly, so that's an assertion failure.
</blockquote></details>

i see, thanks

**Comment by knz** [comment]
thanks!

bors r=rafiss

**Pull request merged**
