### PR TITLE
logical: test that LDR behavior with foreign keys is as expected

### LINKED ISSUE #129932: crosscluster/logical: test that LDR with kv row processor only works when FKs are unvalidated
This should also test that `mode=validated` allows replication of a table with FKs.

Jira issue: CRDB-41780

Epic CRDB-41465

### PR DESCRIPTION
**Pull request by navsetlur**
When a replication stream is started with immediate mode (i.e. KV row processor), the foreign keys must be not valid for the stream to succeed. If valid foreign keys are needed, the mode must be 'validated'

Release note: none
Fixes: #129932

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Nice!

**Comment by navsetlur** [comment]
bors r=msbutler

**Comment by celiala** [comment]
> Build failed:
> - [examples_orms](https://github.com/cockroachdb/cockroach/actions/runs/10738068147/job/29780881536)

[examples_orms passed](https://github.com/cockroachdb/cockroach/actions/runs/10738068147) on re-try.

bors r+

**Pull request merged**
