### PR TITLE
opt: simplify merge and lookup join filters

### PR DESCRIPTION
**Pull request by RaduBerinde**
Merge and lookup joins implicitly test equality on a set of columns.
The corresponding equalities can be removed from the ON condition.
This should make execution faster, since we are no longer evaluating
the redundant conditions (at the cost of a bit of planning overhead).

Benchmarks results for the tpcc lookup join query:
```
name                               old time/op  new time/op  delta
Phases/tpcc-stock-level/Parse      2.07ns ± 0%  2.07ns ± 1%    ~     (p=0.794 n=4+5)
Phases/tpcc-stock-level/OptBuild   49.7µs ± 1%  49.9µs ± 2%    ~     (p=0.548 n=5+5)
Phases/tpcc-stock-level/Normalize  50.2µs ± 1%  50.5µs ± 1%    ~     (p=0.151 n=5+5)
Phases/tpcc-stock-level/Explore     148µs ± 1%   154µs ± 1%  +4.19%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/ExecBuild   157µs ± 1%   162µs ± 2%  +3.26%  (p=0.008 n=5+5)
Exec/tpcc-stock-level/ExecPlan      457µs ± 2%   447µs ± 2%  -2.11%  (p=0.032 n=5+5)
Exec/tpcc-stock-level/ExecOpt       437µs ± 1%   420µs ± 2%  -3.80%  (p=0.008 n=5+5)
```

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

One possible issue: Are we concerned that the filter FDs no longer have the equality columns? I think it's probably ok since MergeJoins and LookupJoins only appear during exploration, but the filter pushdown rules rely on filter FDs containing equality columns.

> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30417#-:-LMndCv07xa21X9_9CLj:b-t4c7w3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
Yeah, the filter pushdown rules don't apply to MergeJoin and LookupJoin (these only exist during exploration). If anything needs to use filter FDs, the filter FDs need to be augmented with the op-specific equalities (this is what the logical props/stat code does, via `joinPropsHelper`).

**Review by rytaft — APPROVED** [review]
:thumbsup: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30417#-:-LMrIfDW35GsPo5gv2Zv:b4c9lyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30417#-LMrIEaKA9RMamw7qJ2J:-LMrIEaKA9RMamw7qJ2K:b-kl8g4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/298b940e9b1ef78fc2aa56dd3f3df516dfe860cb/pkg/sql/opt/memo/statistics_builder.go#L1373)):*
> ```Go
> 	filter ExprView, ev ExprView, relProps *props.Relational,
> ) (numUnappliedConstraints int, constrainedCols opt.ColSet) {
> 	if filter.Operator() == opt.TrueOp {
> ```

good catch!

**Pull request merged**
