### PR TITLE
sql,keys: disregard checks in *ZoneConfig*Batch

### LINKED ISSUE #108253: Two `ALTER` commands on a single line fail
**Describe the problem**

Having two `ALTER` commands on the same line produces the error message:

```
ERROR: unexpected value: raw_bytes:"z\311\346;\003\020\200\200\200@\030\200\200\200\200\002\"\004\010\220\277\005(\003P\000X\000x\001" timestamp:<>
```

**To Reproduce**

```
root@localhost:26257/defaultdb> ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000; ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000;                                                                                             
CONFIGURE ZONE 1
ERROR: unexpected value: raw_bytes:"z\311\346;\003\020\200\200\200@\030\200\200\200\200\002\"\004\010\220\277\005(\003P\000X\000x\001" timestamp:<>
```

However, both `ALTER` commands do take effect despite the error message.  For example, running this will show both 70000 and 60000:

```
ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 70000; SHOW ZONE CONFIGURATIONS; ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 60000; SHOW ZONE CONFIGURATIONS;
```

**Expected behavior**
I would expect both `ALTERS` to return two `CONFIGURE ZONE 1` messages.

**Environment:**
 - CockroachDB version: All 23.1.x
 
**Additional context**
Low impact, just the ominous error message.

Jira issue: CRDB-30386

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by annrpom**
Previously, a bug occured where a transactional schema change,
 `ALTER RANGE default CONFIGURE ZONE...`, statement would
produce a CPut failure, even though both statements do take effect.
This was due to a guard in the code that blocked us from adding the
first zone config to the uncommitted cache, causing the expValues
being updated to the KV batch to be the same for both statements.
This patch addresses the issue by removing the check and allowing
for `default` and psuedotables (like system ranges) to be added to
the uncommitted cache.

Epic: none
Release note (bug fix): two `ALTER RANGE default CONFIGURE ZONE` 
statements on the same line no longer displays an error. 
Fixes: #108253

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @nvanbenschoten)

___
*[`pkg/sql/catalog/descs/collection.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109774#-NdE4p6d1AQOfXkwp-bh:-NdE4p6d1AQOfXkwp-bi:ba6f8h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d2acdbc0788b4bf7ceb1e34612489606f3214/pkg/sql/catalog/descs/collection.go#L558)):*
> ```Go
> 	}
> 
> 	if descID != keys.RootNamespaceID && !keys.IsPseudoTableID(uint32(descID)) {
> ```

i'm guessing if we do this change, we may want to remove this check too. but i'd like to understand this better.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @nvanbenschoten)

___
*[`pkg/sql/catalog/descs/collection.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109774#-NdE4p6d1AQOfXkwp-bh:-NdE5-WF1vZ9ldTcFrG8:b5cxhcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d2acdbc0788b4bf7ceb1e34612489606f3214/pkg/sql/catalog/descs/collection.go#L558)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm guessing if we do this change, we may want to remove this check too. but i'd like to understand this better.
</blockquote></details>

The commit where this was added is ae5c0f6e9fa68f6f5b7c39c317707883e1e34f7e.

It may be related to the fact the RootNamespace and pseudo-tables both don't have descriptors... but i'm not sure

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/catalog/descs/collection.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109774#-NdE4p6d1AQOfXkwp-bh:-Nd_wNqM2WKnEQgUqG8r:b1o6lo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d2acdbc0788b4bf7ceb1e34612489606f3214/pkg/sql/catalog/descs/collection.go#L558)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

The commit where this was added is ae5c0f6e9fa68f6f5b7c39c317707883e1e34f7e.

It may be related to the fact the RootNamespace and pseudo-tables both don't have descriptors... but i'm not sure
</blockquote></details>

+1: also, not sure if I need to keep the check for IsPseudoTableID either - system ranges belong to this category & altering a system range's zone config was (edit: and still is) supported at the time of the commit linked

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/catalog/descs/collection.go` line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109774#-NdE4p6d1AQOfXkwp-bh:-NdajB3A-C9W35Q6DVdK:b1r5tmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1d2acdbc0788b4bf7ceb1e34612489606f3214/pkg/sql/catalog/descs/collection.go#L558)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

+1: also, not sure if I need to keep the check for IsPseudoTableID either - system ranges belong to this category & altering a system range's zone config was supported at the time of the commit linked
</blockquote></details>

update: the descID != keys.RootNamespaceID check makes sense in `DeleteZoneConfigInBatch`, but I also noticed that the following would throw an error before we get to this check: https://github.com/cockroachdb/cockroach/blob/4825e29bc8a92fcd2e771c14837d6981379898bf/pkg/sql/set_zone_config.go#L539-L541

**Review by annrpom — COMMENTED** [review]
@rafiss : [some for posterity] - after discussing with @Xiang-Gu, I aimed to fix this bug in the same nature Xiang detailed in # #88844 (heavy emphasis on the last paragraph in this commit); however, Chengxiong pointed out a good case for not solving it this way: this bug only happens in the case where `descID == keys.RootNamespaceID || keys.IsPseudoTableID(uint32(descID))`

in addition, no one can recall a proper reason as to why this check exists

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109774#-:-Ndk-5JZE1R5dnmSPdqi:bwjrwxf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

**Review by rafiss — APPROVED** [review]
thanks for your research into the history of this code! i think this solution is good

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r=rafiss

**Pull request merged**
