### PR TITLE
server: refactor StartTenant() to pkg/server/tenant.go

### PR DESCRIPTION
**Pull request by Azhng**
Previously, StartTenant() function resided in pkg/server/testserver.go.
However, since this function is not solely used for testing purposes,
it is moved to its own file.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks! Pure movement, right?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62497#-:-MWZsITYEeKjHHFK29eW:b-uluwgv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by Azhng** [comment]
Yes it's just pure movement. But I'm not sure why the Bazel CI failed. Is this something concerning or I can ignore the Bazel CI for now?

**Comment by tbg** [comment]
image

Since that couldn't be caused by code movement, I think it's safe to ignore.

**Comment by Azhng** [comment]
Sounds good! 

bors r=tbg

**Pull request merged**
