### PR TITLE
[prototype] sql: add `system.span_configurations` for kv span configs

### LINKED ISSUE #66390: sql: introduce `system.span_configurations` for KV's span configs
See #66348. We want to introduce a system table on the host tenant to capture the cluster's entire set of span configurations. We'll want to introduce it as part of a start-up migration. Given we intend to establish rangefeeds over this table to disseminate span configs, we'll have to make sure to enable it regardless of the `kv.rangefeed.enabled` setting.

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #66390. It's not wired up to anything yet; we'll later use this
system-tenant only table to store KV span configs.

Release note (sql change): We've added a `system.span_configurations`
table. This will later be used to store authoritative zone configs that
KV has decided to apply.

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: 

@ajwerner did you have concerns about merging this to master or do we feel comfortable enough to do so after todays pod meeting?

> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66402#-:-Mcpjc_mEoXQ1OtsNMod:bjk0r8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
Wait, are we clear on the protocol yet? I feel like there's definitely details we want ironed out. I really don't want to see a table without the code that exercises it.

I'd much much prefer the interfaces for the layers merging first with an in-memory map that can be hooked into an in-memory cluster before the new SQL tables. I have a distinct fear of prototypes which are developed and hooked up to communicate through durable state in SQL tables. We should be hiding that all underneath some storage abstraction for the KV layer. 

I'd also love more clarity on what the protobufs are going to look like that live in this table.

**Comment by ajwerner** [comment]
Let me catch up on the RFC. I still think it'd be better to lead off this project by merging interfaces which can be used for testing the reconciliation layer and for testing the server side. What interface will `kvserver` hold on to? What interface on top of the `Connector` will the reconciliation job use? 

Mostly though, I don't see much value in adding the tables without code to exercise them.

**Comment by irfansharif** [comment]
@ajwerner and I discussed internally around wanting to first spell out the interfaces and then back them up by these concrete implementations that actually write state, vs. coming up with these concrete implementations first and then finding out the abstract interfaces to wrap around them. 

I think in the short term Arul and I are likely going to work on a short-lived branch to figure out what these interfaces are and how they, and then start slowly merging the earlier revisions in this branch back to master. So we'll mark these PRs with the [prototype] prefix, have them land against the [`multi-tenant-zcfgs`](https://github.com/cockroachdb/cockroach/tree/multi-tenant-zcfgs) branch in this repo. It'll give us CI, give us a way to collect all the reviews in one place, etc. Once the interfaces are clearer, we'll send out equivalent PRs to master and just continue working there.

**Pull request merged**
