### PR TITLE
storage: Close replicaConsistencyQueue from the stopper's closer

### PR DESCRIPTION
**Pull request by kkaneda**
Close `replicaConsistencyQueue` as we do for other queues.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5226)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
LGTM

**Comment by tamird** [comment]
typo in commit message s/clsoe/close/

**Comment by kkaneda** [comment]
:( Fixed..

**Comment by tamird** [comment]
:shipit:

**Pull request merged**
