### PR TITLE
pgwire: create a framework for pre-serve connection logic

### PR DESCRIPTION
**Pull request by knz**
Parent PRs:
- [x] https://github.com/cockroachdb/cockroach/pull/84608
- [x] https://github.com/cockroachdb/cockroach/pull/91739
- [x] https://github.com/cockroachdb/cockroach/pull/91744
- [x] https://github.com/cockroachdb/cockroach/pull/92574

Epic: CRDB-14537

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz5x13-WfJtUEn-1_a):*
just a question: why is it named `sql.pre_serve...` and not `sql.pre_auth...`? i feel that from a client's perspective, the connection is already being "served" once it reaches the business logic inside of CRDB. they shouldn't need to care about the various `server` objects we have in our code.

also, will this make it harder for serverless users to see where their credits are being used in the case of high authentication load? or do these `pre_serve` bytes no longer count against them? (if so, that would be worth making explicit in the release notes)
___
*[`pkg/sql/pgwire/pre_serve.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz82_fEqz8DWZpeH6y:-NHz82_fEqz8DWZpeH6z:bxo42kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/pre_serve.go#L55)):*
> ```Go
> type PreServeConnHandler struct {
> 	errWriter errWriter
> 	cfg       struct {
> ```

why do we need this empty `cfg`? explain with a comment? (and maybe don't put the `}` on a new line)
___
*[`pkg/sql/pgwire/pre_serve.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHzDnUn9dX_YcFvdGhz:-NHzDnUo79HlDxeAdruk:bmn398a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/pre_serve.go#L106)):*
> ```Go
> ) (err error) {
> 	defer func() {
> 		if err != nil {
> ```

when would `err` ever be non-nil?
___
*[`pkg/sql/pgwire/server.go` line 1402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz9Moh1vpqHumyc1aK:-NHz9Moh1vpqHumyc1aL:b1fccim) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/server.go#L1402)):*
> ```Go
> // sequence. Later error sends during/after authentication are handled
> // in conn.go.
> func (s *Server) sendErr(ctx context.Context, conn net.Conn, err error) error {
> ```

perhaps the function's job would be more clear if it was renamed `sendPreAuthErr` or `sendPreServeErr`?

**Comment by knz** [comment]
> why is it named sql.pre_serve... and not sql.pre_auth...?

- why not pre_auth: because there is more remaining tenant-specific logic pre-authentication. The split we're designing is *not* about pre-auth vs post-auth; it's pre-tenant-assignment vs post-tenant-assignment, with some remaining pre-auth work to do after tenant assignment.

- why pre_serve: because i'm extracting the work done *before `ServeConn` is called*.   (it's pre-ServeConn really, hence `PreServeConnHandler`)

**Comment by knz** [comment]
> will this make it harder for serverless users to see where their credits are being used in the case of high authentication load? 

I don't see it - as you'll see in the PR chain, the amount of pre-serve work is minimal.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/pgwire/pre_serve.go` line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NI4Butt5esXoOo-bWzt:-NI4ButuAl6U-KQv4nIv:b-e0wgxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec14b680df2a35884627994c3fa001cf82b398b0/pkg/sql/pgwire/pre_serve.go#L75)):*
> ```Go
> // tenantIndependentMetrics is the set of metrics for the
> // pre-serve part of connection handling, before the connection
> // is routed to a specific tenant.
> ```

nit: until tsdb supports tenant cardinality (or maybe I missed it... has this been implemented?) can we specify the semantics of "tenant independent metrics"? Are they stored with tenant-level cardinality, or just available in _status/vars / in-memory?



_Code quote:_
```Go
// tenantIndependentMetrics is the set of metrics for the
// pre-serve part of connection handling, before the connection
// is routed to a specific tenant.
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92575)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @knz, and @rafiss)

___
*[`-- commits` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz5x13-WfJtUEn-1_a):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just a question: why is it named `sql.pre_serve...` and not `sql.pre_auth...`? i feel that from a client's perspective, the connection is already being "served" once it reaches the business logic inside of CRDB. they shouldn't need to care about the various `server` objects we have in our code.

also, will this make it harder for serverless users to see where their credits are being used in the case of high authentication load? or do these `pre_serve` bytes no longer count against them? (if so, that would be worth making explicit in the release notes)
</blockquote></details>

-  why not pre_auth: because there is more remaining tenant-specific logic pre-authentication. The split we're designing is not about pre-auth vs post-auth; it's pre-tenant-assignment vs post-tenant-assignment, with some remaining pre-auth work to do after tenant assignment.

- why pre_serve: because i'm extracting the work done before ServeConn is called. (it's pre-ServeConn really, hence PreServeConnHandler)
___
*[`pkg/sql/pgwire/pre_serve.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz82_fEqz8DWZpeH6y:-NIYrvft-oBfUGCP-KLj:bf9cvk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/pre_serve.go#L55)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do we need this empty `cfg`? explain with a comment? (and maybe don't put the `}` on a new line)
</blockquote></details>

We don't need it. it was dead code. removed.
___
*[`pkg/sql/pgwire/pre_serve.go` line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHzDnUn9dX_YcFvdGhz:-NIYtvNe3NtkjY6l0vmz:brk153u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/pre_serve.go#L106)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

when would `err` ever be non-nil?
</blockquote></details>

This is just a skeleton for the PreServe function that gets populated further in #92577. At that point, err can become non-nil.
___
*[`pkg/sql/pgwire/pre_serve.go` line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NI4Butt5esXoOo-bWzt:-NIYuR1MBYar9SdR6MLQ:b-l8k02l) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ecd713f529f296a2ef2b4e852ed346e9c283ba/pkg/sql/pgwire/pre_serve.go#L75)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: until tsdb supports tenant cardinality (or maybe I missed it... has this been implemented?) can we specify the semantics of "tenant independent metrics"? Are they stored with tenant-level cardinality, or just available in _status/vars / in-memory?
</blockquote></details>

They are tenant-independent so by definition they are not tenant-level. They are just regular metrics and stored alongside the others. What type of specification do you have in mind?
___
*[`pkg/sql/pgwire/server.go` line 1402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/92575#-NHz9Moh1vpqHumyc1aK:-NIYufQbEZEsFFNR7b6i:bxsm13o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8c22818928c6ff86e03db7ce2a549549b737a85/pkg/sql/pgwire/server.go#L1402)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

perhaps the function's job would be more clear if it was renamed `sendPreAuthErr` or `sendPreServeErr`?
</blockquote></details>

I guess that's reasonable. Done.

**Review by rafiss — APPROVED** [review]

**Pull request merged**
