### PR TITLE
release-21.1: roachpb: remove deprecated range from admin scatter response

### PR DESCRIPTION
**Pull request by adityamaru**
Backport 1/1 commits from #62366.

/cc @cockroachdb/release

Backport motivation: Deletion of legacy code. Prior to 20.2 the AdminScatterResponse would return only the Span of the range being scattered. The response was expanded to encapsulate more information in https://github.com/cockroachdb/cockroach/pull/51607. To maintain compatibility with 20.1 nodes this response field and related code were kept around. Now that we will not see <20.2 nodes alongside our 21.1 nodes we can stop populating, sending, and receiving this deprecated response. This backport does not change any behavior.

---

This change removes the DeprecatedRanges field from the admin scatter
response proto and deletes relevant code.  This was kept around for
compatibility with 20.1, and hence it is safe to remove this in 21.1.

Release note: None

### CODE REVIEW

**Review by pbardea — APPROVED** [review]

**Comment by adityamaru** [comment]
@dt can i get a stamp on this too, thanks

**Comment by dt** [comment]
can you expand backport motivation?

**Comment by adityamaru** [comment]
Added it to the PR description, let me know if that is not the right spot.

**Comment by dt** [comment]
Thanks. I'm not quite sure I see the need to backport though -- sometimes we backport pure code cleanup refactors if we think it'll make future bug fix / behavior backports cherrypick more cleanly, but that seems unlikely here?

**Comment by adityamaru** [comment]
Yeah unlikely, that makes sense. I'll close this out.

**Pull request closed without merging**
