### PR TITLE
sql: implement SET LOCAL

### PR DESCRIPTION
**Pull request by otan**
Resolves: #32562
Release justification: high priority bug fix

First 3 commits from #69394

### CODE REVIEW

**Comment by otan** [comment]
Couple of things to assess before this can actually get in:
* param status updates must be tracked and reverted on commit/rollback.
* the sessiondatastack should probably be some pointer.
* we should look at how good that "copy" of session data is. i suspect stuff like search_path won't be so nice.
* tests tests tests

**Comment by otan** [comment]
urgh, according to https://github.com/cockroachdb/cockroach/issues/32562#issuecomment-896752531 there is also a txn state on the connexecutor we need to keep a track of!

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! it's actually less messy than i thought it would be..

what's your concern with search_path? is it special in some way?

(btw, we should make sure this also works with `SET LOCAL ROLE` -- looks like it should, but thats another thing to test)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-:-MhoIyK_3xEazKExhJVy:bksp3j9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/conn_executor_exec.go, line 820 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoIcDGAU-J3MrwI3zF:-MhoIcDGAU-J3MrwI3zG:b-p09uwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/487e14b3fb4169f5ad4092ef2f63de5be43d9ea8/pkg/sql/conn_executor_exec.go#L820)):*
> ```Go
> 	ex.phaseTimes.SetSessionPhaseTime(sessionphase.SessionEndTransactionCommit, timeutil.Now())
> 	if !ex.implicitTxn() {
> 		ex.sessionDataStack = ex.sessionDataStack.Pop()
> ```

so i guess for the param status stuff, we'd need a check (maybe inside of `Pop` that will send out param status messages for all the variables that need it.
___
*[pkg/sql/conn_executor_exec.go, line 1248 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoHEYy57JBgksSP1k0:-MhoHEYy57JBgksSP1k1:bf30zfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/487e14b3fb4169f5ad4092ef2f63de5be43d9ea8/pkg/sql/conn_executor_exec.go#L1248)):*
> ```Go
> ) (_ fsm.Event, payload fsm.EventPayload) {
> 	switch s := ast.(type) {
> 	case *tree.BeginTransaction:
> ```

i think we also need something similar when starting a new SAVEPOINT. (that's the only way to get a nested txn. if you do BEGIN inside an explicit txn, it's an error.)
___
*[pkg/sql/exec_util.go, line 2395 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoFfNPCb4p2AQucSzK:-MhoFfNQ2kphKiRMbeBR:bw8denb) ([raw file](https://github.com/cockroachdb/cockroach/blob/67e068c8c0a3b56e29a06a46b7daad7bd6e26cef/pkg/sql/exec_util.go#L2395)):*
> ```Go
> func (noopParamStatusUpdater) BufferParamStatusUpdate(string, string) {}
> 
> // sessionDataMutatorFactory creates sessionMutators.
> ```

the comment could include why it's needed and also how it interacts with the session data stack
___
*[pkg/sql/planner.go, line 347 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoG5mG0KOlT7mVPZYu:-MhoG5mG0KOlT7mVPZYv:bqhzbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/67e068c8c0a3b56e29a06a46b7daad7bd6e26cef/pkg/sql/planner.go#L347)):*
> ```Go
> 
> 	p.extendedEvalCtx = internalExtendedEvalCtx(
> 		ctx, sd, &sessionDataMutator{
> ```

nit: seemed a bit easier to read when it wasn't inlined
___
*[pkg/sql/set_var.go, line 145 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoHwcxAHEWI0teWMQY:-MhoHwcxAHEWI0teWMQZ:b-tbzxbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/487e14b3fb4169f5ad4092ef2f63de5be43d9ea8/pkg/sql/set_var.go#L145)):*
> ```Go
> 	}
> 	if n.local {
> 		if params.p.EvalContext().TxnImplicit {
> ```

let's match the Postgres warning: "SET LOCAL can only be used in transaction blocks"

weirdly, postgres shows that warning, but then still lets the SET LOCAL go ahead as if it were a normal SET.
___
*[pkg/sql/parser/sql.y, line 4432 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoHXcxAUPv3SFq6zQ9:-MhoHXcxAUPv3SFq6zQA:b-lj7su5) ([raw file](https://github.com/cockroachdb/cockroach/blob/487e14b3fb4169f5ad4092ef2f63de5be43d9ea8/pkg/sql/parser/sql.y#L4432)):*
> ```Yacc
> | set_exprs_internal   { /* SKIP DOC */ }
> | SET CONSTRAINTS error { return unimplemented(sqllex, "set constraints") }
> | SET LOCAL set_rest
> ```

hm i think this works better with a new rule so that we can have the right help text

```
// %Help: SET LOCAL - change a session variable scoped to the current transaction
// %Category: Cfg
// %Text:
// SET LOCAL <var> { TO | = } <values...>
// SET LOCAL TIME ZONE <tz>
//
// %SeeAlso: SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET SESSION,
// WEBDOCS/set-vars.html
set_local_stmt:
  SET LOCAL set_rest
  {
    // ...
  }
```

also, what happens if we put this under `preparable_set_stmt`?
___
*[pkg/sql/sem/tree/eval.go, line 3458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhnsMZu2l32eHc_6boR:-MhnsMZu2l32eHc_6boS:bzh93ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8262aee7f2169bf08e446c025a34f46e3410222/pkg/sql/sem/tree/eval.go#L3458)):*
> ```Go
> type EvalContext struct {
> 	// Session variables. This is a read-only copy of the values owned by the
> 	// Session. A new element is added to the stack for each explicit transaction.
> ```

what is "for each explicit transaction" referring to? i believe it's when a SAVEPOINT is created right?
___
*[pkg/sql/sessiondata/session_data.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mhnrkj_7sc0nb5KDXzp:-Mhnrkj_7sc0nb5KDXzq:b3mymmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a60cd356e3ffffa06b945b75bdcb2d95d25eb7fe/pkg/sql/sessiondata/session_data.go#L183)):*
> ```Go
> }
> 
> // SessionDataStack represents a stack of SessionData objects.
> ```

it would be helpful for the comment to say why we need it -- to support SET LOCAL and txn-scoped session vars
___
*[pkg/sql/sessiondata/session_data.go, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhnrZXmCm-tj5LfRg_V:-MhnrZXmCm-tj5LfRg_W:by6nwd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b9f572cdd16a8dd29e4588c126a48068b97439/pkg/sql/sessiondata/session_data.go#L195)):*
> ```Go
> 
> // NewSessionDataStack creates a new SessionDataStack.
> func NewSessionDataStack(sds ...*git difSessionData) SessionDataStack {
> ```

typo on `git diff`

**Comment by otan** [comment]
> what's your concern with search_path? is it special in some way?

we need a deep copy of it, basically. otherwise it re-uses the same slice

i'll work on fixing this up if we decide to proceed with SET LOCAL.

**Comment by rafiss** [comment]
yeah let's go ahead and try to finish this. @ajstorm and @vy-ton also feel like this would be a good item to complete for 21.2

**Review by ajwerner — COMMENTED** [review]
Drive-by commentary because I was curious. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-:-MhvHVOW24l3b5oB1GJ3:blf4urc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/exec_util.go, line 2488 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhvGcPBCLmXilxxmYke:-MhvGcPBCLmXilxxmYkf:bnlful) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3d7c936a0f3d6712356aa70b793baf674d8d4f/pkg/sql/exec_util.go#L2488)):*
> ```Go
> }
> 
> // sessionDataMutator is the interface used by sessionVars to change the session
> ```

nit: this isn't an interface
___
*[pkg/sql/sessiondata/session_data.go, line 196 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhvGsWeBrUnhVmDbky9:-MhvGsWeBrUnhVmDbkyA:b4ljgph) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3d7c936a0f3d6712356aa70b793baf674d8d4f/pkg/sql/sessiondata/session_data.go#L196)):*
> ```
> 
> 	// Use an internal variable to prevent abstraction leakage.
> 	stack []*SessionData
> ```
Why not a linked list? How do you feel about:

```go
type Stack struct {
    cur   SessionData // could see making this a pointer
    next *Stack
}
```

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @rafiss)

___
*[pkg/sql/exec_util.go, line 2395 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoFfNPCb4p2AQucSzK:-MhvJYGr54IZspmhQGON:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67e068c8c0a3b56e29a06a46b7daad7bd6e26cef/pkg/sql/exec_util.go#L2395)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the comment could include why it's needed and also how it interacts with the session data stack
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhnrZXmCm-tj5LfRg_V:-MhvJWEc3t-z9bye5VVI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b9f572cdd16a8dd29e4588c126a48068b97439/pkg/sql/sessiondata/session_data.go#L195)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

typo on `git diff`
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 196 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhvGsWeBrUnhVmDbky9:-MhvJLEYAd6dVhsvmlY0:b-ws80x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3d7c936a0f3d6712356aa70b793baf674d8d4f/pkg/sql/sessiondata/session_data.go#L196)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 	// Use an internal variable to prevent abstraction leakage.
> 	stack []*SessionData
> ```
Why not a linked list? How do you feel about:

```go
type Stack struct {
    cur   SessionData // could see making this a pointer
    next *Stack
}
```

</blockquote></details>

was thinking it'd re-use the same slice space and because there are certain PopN/fetching all items in the stack as a slice operations i'd like slicing for.

**Review by rafiss — CHANGES_REQUESTED** [review]
release note nit: the release note should describe how it works with savepoints (SET LOCAL isn't rolled back after releasing a savepoint)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-:-Mi0F7NTBtUI9L8DD8ni:b-wuuik6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, @pbardea, and @rafiss)

___
*[pkg/sql/conn_executor_savepoints.go, line 140 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0Dnx6Brroi0MjjEA6:-Mi0Dnx6Brroi0MjjEA7:b-og0oo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/32bc99ffc5eb291888b44ad3754bd64ab73bba3a/pkg/sql/conn_executor_savepoints.go#L140)):*
> ```Go
> 	// We will restore the currSessionData on it, as the SET LOCAL parameters
> 	// are still kept.
> 	// We do not have to report param status updates as the SessionData
> ```

wait why don't we report them? based on the tests below it looked like the timezone was changing even after doing a RELEASE 
___
*[pkg/sql/set_var.go, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi07AuC3hEydGZ2roHl:-Mi07AuC3hEydGZ2roHm:bog98kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a246484e40bf0209c41be158f42c2ba3b66267/pkg/sql/set_var.go#L32)):*
> ```Go
> )
> 
> // setVarNode represents a SET SESSION statement.
> ```

nit: represents a `SET { LOCAL | SESSION } statement`
___
*[pkg/sql/set_var.go, line 139 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0C33dCtcDEJeNrxD7:-Mi0C33dCtcDEJeNrxD8:b1nyrgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f6c309e70bf498808a04f122369961b02323236/pkg/sql/set_var.go#L139)):*
> ```Go
> 	}
> 
> 	if n.v.RuntimeSet != nil {
> ```

could you add a comment saying why RuntimeSet and SetWithPlanner don't work with applyOnSessionDataMutators?
___
*[pkg/sql/logictest/testdata/logic_test/set_local, line 38 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi082wL1ZFxG_nEH7gb:-Mi082wM8C_g6jBJTA_V:b-symaih) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a246484e40bf0209c41be158f42c2ba3b66267/pkg/sql/logictest/testdata/logic_test/set_local#L38)):*
> ```
> 2020-08-25 08:16:17.123456 -0700 PDT  P1DT15H16M17.123456S
> 
> # Rollback and ensure the values are correct.
> ```

i think this comment also deserves a link to https://github.com/cockroachdb/cockroach/issues/69396 mentioning that CRDB diverges from postgres
___
*[pkg/sql/parser/testdata/set, line 520 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi06Gn16n9X-eoWlOIk:-Mi06Gn16n9X-eoWlOIl:bx897gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3befe4bd23d40b475b431fb2404e4f872452245e/pkg/sql/parser/testdata/set#L520)):*
> ```
> 
> parse
> SET LOCAL TIME ZONE +3
> ```

can we test `SET LOCAL ROLE bob` as well?
___
*[pkg/sql/sessiondata/session_data.go, line 56 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi08axLDqBBArM-80zU:-Mi08axLDqBBArM-80zV:b1fzrpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a246484e40bf0209c41be158f42c2ba3b66267/pkg/sql/sessiondata/session_data.go#L56)):*
> ```Go
> func (s *SessionData) Clone() *SessionData {
> 	// Currently clone does a shallow copy of everything - we can get away with it
> 	// as all the slices/maps does a copy if it mutates OR are idempotent
> ```

nit: i don't think idempotent is the right word. maybe it could just say "operations that affect the whole SessionDataStack"
___
*[pkg/sql/sessiondata/session_data.go, line 58 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi08WXG6EG0tOkeDMd_:-Mi08WXG6EG0tOkeDMda:bsmsina) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a246484e40bf0209c41be158f42c2ba3b66267/pkg/sql/sessiondata/session_data.go#L58)):*
> ```Go
> 	// as all the slices/maps does a copy if it mutates OR are idempotent
> 	// operations (e.g. setting SequenceState should be the setting the
> 	// same value across all copied sessions).
> ```

nit: "across all copied SessionData"

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @rafiss)

___
*[pkg/sql/conn_executor_savepoints.go, line 140 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0Dnx6Brroi0MjjEA6:-Mi0sx-nBGgqZ76zI3MJ:b22c34u) ([raw file](https://github.com/cockroachdb/cockroach/blob/32bc99ffc5eb291888b44ad3754bd64ab73bba3a/pkg/sql/conn_executor_savepoints.go#L140)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

wait why don't we report them? based on the tests below it looked like the timezone was changing even after doing a RELEASE 
</blockquote></details>

whereabouts? it's because RELEASE doesn't actually commit or rollback a transaction; they just scrub previous savepoints. 
___
*[pkg/sql/set_var.go, line 139 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0C33dCtcDEJeNrxD7:-Mi0ul1P9hymTqjO2sqp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f6c309e70bf498808a04f122369961b02323236/pkg/sql/set_var.go#L139)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a comment saying why RuntimeSet and SetWithPlanner don't work with applyOnSessionDataMutators?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/set_local, line 38 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi082wL1ZFxG_nEH7gb:-Mi0tzGD5BzBS4Cz0XpH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00a246484e40bf0209c41be158f42c2ba3b66267/pkg/sql/logictest/testdata/logic_test/set_local#L38)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this comment also deserves a link to https://github.com/cockroachdb/cockroach/issues/69396 mentioning that CRDB diverges from postgres
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 4432 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhoHXcxAUPv3SFq6zQ9:-MhvNgAH8vMoDGfUZz-w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/487e14b3fb4169f5ad4092ef2f63de5be43d9ea8/pkg/sql/parser/sql.y#L4432)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm i think this works better with a new rule so that we can have the right help text

```
// %Help: SET LOCAL - change a session variable scoped to the current transaction
// %Category: Cfg
// %Text:
// SET LOCAL <var> { TO | = } <values...>
// SET LOCAL TIME ZONE <tz>
//
// %SeeAlso: SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET SESSION,
// WEBDOCS/set-vars.html
set_local_stmt:
  SET LOCAL set_rest
  {
    // ...
  }
```

also, what happens if we put this under `preparable_set_stmt`?
</blockquote></details>

Done.
___
*[pkg/sql/parser/testdata/set, line 520 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi06Gn16n9X-eoWlOIk:-Mi0uoU32KC4XOpYFWsK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3befe4bd23d40b475b431fb2404e4f872452245e/pkg/sql/parser/testdata/set#L520)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can we test `SET LOCAL ROLE bob` as well?
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/session_data.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mhnrkj_7sc0nb5KDXzp:-MhvNj1G2F3qdbSA9_wU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a60cd356e3ffffa06b945b75bdcb2d95d25eb7fe/pkg/sql/sessiondata/session_data.go#L183)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it would be helpful for the comment to say why we need it -- to support SET LOCAL and txn-scoped session vars
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval.go, line 3458 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-MhnsMZu2l32eHc_6boR:-MhvNhxM0z56ZJzVIKiz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8262aee7f2169bf08e446c025a34f46e3410222/pkg/sql/sem/tree/eval.go#L3458)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is "for each explicit transaction" referring to? i believe it's when a SAVEPOINT is created right?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
this lgtm! i left one naming comment you could decide about

and also could you update the release note before merging:
- the release note should describe how it works with savepoints (SET LOCAL isn't rolled back after releasing a savepoint)
- mention that SET LOCAL outside of an explicit txn is a no-op

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-:-Mi4SESR-IocmoeqgKrt:b-x9jzvt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/sql/conn_executor_savepoints.go, line 140 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0Dnx6Brroi0MjjEA6:-Mi4QZbgDRAOo1YbTGzx:b-wfoqhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/32bc99ffc5eb291888b44ad3754bd64ab73bba3a/pkg/sql/conn_executor_savepoints.go#L140)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

whereabouts? it's because RELEASE doesn't actually commit or rollback a transaction; they just scrub previous savepoints. 
</blockquote></details>

ah i understand. i think i was confusing it with the ROLLBACK TO SAVEPOINT test
___
*[pkg/sql/exec_util.go, line 2562 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi4R80jB_ajoGi2pNa7:-Mi4R80k1u-X4PmSjozm:bxi0k5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffd9430b206a456544232c43bfe636e257a2206c/pkg/sql/exec_util.go#L2562)):*
> ```Go
> // in the stack and applies the given function to them.
> // It is the equivalent of SET SESSION x = y.
> func (it *sessionDataMutatorIterator) forEachMutator(applyFunc func(m *sessionDataMutator)) {
> ```

for naming consistency do you think it makes sense to use the names
```
forTopMutator()
forEachMutator()
forEachMutatorError()
```
or maybe
```
applyToTopMutator()
applyToEachMutator()
applyToEachMutatorError()
```
___
*[pkg/sql/planner.go, line 518 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi4RR77EBw-l__S0FSQ:-Mi4RR77EBw-l__S0FSR:bmaeen1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffd9430b206a456544232c43bfe636e257a2206c/pkg/sql/planner.go#L518)):*
> ```Go
> }
> 
> func (p *planner) forEachMutatorError(applyFunc func(m *sessionDataMutator) error) error {
> ```

ditto on name comment if you change it in the other file

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

___
*[pkg/sql/conn_executor_savepoints.go, line 140 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi0Dnx6Brroi0MjjEA6:-Mi4Zc3pDcPdLjMH4-WT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32bc99ffc5eb291888b44ad3754bd64ab73bba3a/pkg/sql/conn_executor_savepoints.go#L140)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i understand. i think i was confusing it with the ROLLBACK TO SAVEPOINT test
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 2562 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi4R80jB_ajoGi2pNa7:-Mi4ZdEH9TKWKAjxrk91:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffd9430b206a456544232c43bfe636e257a2206c/pkg/sql/exec_util.go#L2562)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for naming consistency do you think it makes sense to use the names
```
forTopMutator()
forEachMutator()
forEachMutatorError()
```
or maybe
```
applyToTopMutator()
applyToEachMutator()
applyToEachMutatorError()
```
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 518 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/69224#-Mi4RR77EBw-l__S0FSQ:-Mi4ZdTM1hDs-y2LRlA1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffd9430b206a456544232c43bfe636e257a2206c/pkg/sql/planner.go#L518)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto on name comment if you change it in the other file
</blockquote></details>

Done.

**Pull request merged**
