### PR TITLE
sql: Support SELECT FOR UPDATE SQL syntax

### PR DESCRIPTION
**Pull request by rytaft**
Update the parser to recognize the `SELECT ... FOR UPDATE` SQL
syntax.  Update the SQL layer so scan nodes in the query plan
are flagged as lockForUpdate if the `SELECT ... FOR UPDATE` syntax
is used.  If a scan node with lockForUpdate is encountered during
plan execution, return an error so the user knows that 
`SELECT ... FOR UPDATE` is not yet fully supported.

This is the first of several commits/PRs needed to support
`SELECT ... FOR UPDATE`.  Future commits will implement the
changes required at the KV layer, connect the two layers with
changes to the KV api, and eliminate the temporary error message
introduced in this commit.

See PR #19577 for the RFC, and Issue #6583.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/processors.proto, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-Kxipjcccgzk1AAb2anc:-Kxipjcccgzk1AAb2and:bhmuuw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb69040da2ac8f7304c1548c660f5ebe0aa95ee/pkg/sql/distsqlrun/processors.proto#L173)):*
> ```protobuf
>   // (that value will be used for sizing batches instead).
>   optional int64 limit_hint = 5 [(gogoproto.nullable) = false];
>   optional bool lockForUpdate = 6 [(gogoproto.nullable) = false];
> ```

Unfortunately, distsql doesn't currently support write operations - this is because the KV TxnCoordSender assumes all writes happen on the same node. I am not quite sure if this will apply to the new KV operations, but I suspect it will (CC @andreimatei - see RFC #19577).

I would not add any support in distsql at this time and disallow such queries from using distsql (see `DistSQLPlanner.checkSupportForNode`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650)*

**Comment by rytaft** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/processors.proto, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-Kxipjcccgzk1AAb2anc:-Kxj8QU2eQ5MJhdd8BX4:btufykf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccb69040da2ac8f7304c1548c660f5ebe0aa95ee/pkg/sql/distsqlrun/processors.proto#L173)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Unfortunately, distsql doesn't currently support write operations - this is because the KV TxnCoordSender assumes all writes happen on the same node. I am not quite sure if this will apply to the new KV operations, but I suspect it will (CC @andreimatei - see RFC #19577).

I would not add any support in distsql at this time and disallow such queries from using distsql (see `DistSQLPlanner.checkSupportForNode`).
</blockquote></details>

Got it.  I've removed support from distsql and added a check in `DistSQLPlanner.checkSupportForNode`. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 21 of 26 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-:-KxjAYQ1lPD0Nx6VGBVG:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm: - but have you considered adding the `lockForUpdate` bit to some of the structures that already get passed around in most of the method signatures you're modifying though? I think ideally we could avoid having to plumb this extra bool through everything, especially since undoubtedly as time goes on we will want to add more and more feature flags like this one.

Concretely, I think adding the bool to the `SelectClause` and `planDataSource` structs would probably eliminate most of the method signature changes.

Forgive me if you've already thought this through and decided that it's infeasible!

---

Reviewed 21 of 26 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/check.go, line 156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjGYEcGLw0SpdC6Wgl:-KxjGYEcGLw0SpdC6Wgm:bkg4j28) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/check.go#L156)):*
> ```Go
> 	// would be marginal compared to the work of the actual query, so the added
> 	// complexity seems unjustified.
> 	rows, err := p.SelectClause(ctx, sel, nil /* orderBy */, lim, false, /* lockForUpdate */
> ```

Did you consider adding the `lockForUpdate` bit to the `SelectClause` AST node?

---

*[pkg/sql/data_source.go, line 265 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjGxa0Byflbgy6_K_j:-KxjGxa0Byflbgy6_K_k:b-pnil6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/data_source.go#L265)):*
> ```Go
> 			return planDataSource{}, err
> 		}
> 		right, err := p.getSources(ctx, sources[1:], scanVisibility, lockForUpdate)
> ```

Would it make sense to add the `lockForUpdate` bit to the `planDataSource` itself? That would eliminate this argument plumbing.

---

*[pkg/sql/plan.go, line 398 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjHEqsOlbfoBtrWwGx:-KxjHEqsOlbfoBtrWwGy:bkydqx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/plan.go#L398)):*
> ```Go
> 		return p.Select(ctx, n, desiredTypes)
> 	case *parser.SelectClause:
> 		return p.SelectClause(ctx, n, nil /* orderBy */, nil /* limit */, false, /* lockForUpdate */
> ```

Adding the bit to the SelectClause expression would eliminate this threading

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-:-KxjHQEBsAkyOvvH7XIS:b-skoqo8)*

**Comment by jordanlewis** [comment]
Whoops looks like I was a bit late on the uptake here!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-:-KxjIfj07p0RjiQw0GOX:blpgoe7)*

**Comment by rytaft** [comment]
Thanks for the comments!  Unfortunately I don't think it's easy to eliminate the extra argument.  As described below in my responses to the inline comments, the `FOR UPDATE` clause is logically grouped with the `ORDER BY` and `LIMIT` clauses in the Postgres parser, and changing that would likely change the grammar.  I don't think adding `lockForUpdate` to `planDataSource` works either, since it is needed by the `scanNode` during plan execution.  Let me know if you think I'm missing something... thanks!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/check.go, line 156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjGYEcGLw0SpdC6Wgl:-KxjKJGuHdM_bohpaglN:b-14unas) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/check.go#L156)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Did you consider adding the `lockForUpdate` bit to the `SelectClause` AST node?
</blockquote></details>

I added it to the `Select` rather than `SelectClause` in order to match the [Postgres yacc file](https://github.com/postgres/postgres/blob/86182b18957b8f9e8045d55b137aeef7c9af9916/src/backend/parser/gram.y#L10834) (`ORDER BY`, `LIMIT`, and `FOR UPDATE` are all handled similarly).  I think it would be difficult to add `lockForUpdate` to the `SelectClause` without changing the grammar...

---

*[pkg/sql/data_source.go, line 265 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjGxa0Byflbgy6_K_j:-KxjpIpSBPIsGECevBbk:bqcv71d) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/data_source.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Would it make sense to add the `lockForUpdate` bit to the `planDataSource` itself? That would eliminate this argument plumbing.
</blockquote></details>

I don't think this would work because the `lockForUpdate` value is needed by the `scanNode` at plan execution.  The `scanNode` won't be able to access the `planDataSource`, since that is higher up in the plan tree.

---

*[pkg/sql/plan.go, line 398 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-KxjHEqsOlbfoBtrWwGx:-KxjrIhtom-SG4D--Rh4:b-i640og) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbeb9e76f9488073966f7ef4d00167aa20997b/pkg/sql/plan.go#L398)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Adding the bit to the SelectClause expression would eliminate this threading
</blockquote></details>

Same comment as above - the `SelectClause` struct is populated in a different section of `sql.y`.  Changing this would depart from the grammar used by Postgres.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-:-KxjrmAbsGuTqUp9Co6P:b-yn8899)*

**Comment by jordanlewis** [comment]
I was suggesting augmenting the `SelectClause` struct outside of the parser just as a way of passing the `lockForUpdate` bit without changing method signatures - but now that I actually survey the code it seems like we're not really doing that anywhere else so it'd be a bit of a break in style.

Thanks for the explanation!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19650#-:-KxkECgFi9Gmx-AXIEcX:btrvpn6)*

**Pull request merged**
