### PR TITLE
*: report panics in context; more context plumbing

### PR DESCRIPTION
**Pull request by knz**
This patch extends log.ReportPanic() to use a context.Context.
Because of this, the stopper interface (RunTask, RunWorker etc) must
be extended to also accept a context parameter.

Forked off #15063.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 71 of 168 files at r1.
Review status: 71 of 168 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/stop/stopper.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki5atF25Pm1IUuT7dcQ:-Ki5atF25Pm1IUuT7dcR:bb8drj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a509b3ec94cc87981107fc29008ccc4f4cf5e182/pkg/util/stop/stopper.go#L205)):*
> ```Go
> // RunWorker runs the supplied function as a "worker" to be stopped
> // by the stopper. The function <f> is run in a goroutine.
> func (s *Stopper) RunWorker(ctx context.Context, f func()) {
> ```

it may be a good idea, in a follow-up, to pass this context (or a derivative of it) into `f`. This is already done in `RunAsyncTask`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-:-Ki5cHrfjtQ7AECOwqUJ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Adding a context to `Stop()` makes things so tedious, and it's just to pass that context to `Recover` which doesn't make too much logical sense to me. If we get a panic, the relevant context logically is that of the server, not whatever context happens to call/defer `Stop`.

IMO we should just store a context in the `Stopper`. If the counter-argument is "we should not store contexts", note that we are already effectively storing one whenever we do `defer stopper.Stop(ctx)`.

**Comment by tamird** [comment]
Tedium seems fine to me in this case.

**Comment by RaduBerinde** [comment]
Review status: 71 of 168 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/stop/stopper.go, line 208 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki5heyC_6Yfip_-419-:-Ki5heyDwy3D3-y9IfGF:bf0btk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a509b3ec94cc87981107fc29008ccc4f4cf5e182/pkg/util/stop/stopper.go#L208)):*
> ```Go
> 	s.stop.Add(1)
> 	go func() {
> 		defer s.Recover(ctx)
> ```

I agree with Andrei, the caller can easily pass a context with a span which is not safe in general. If we are confident that we never use spans in here, we should assert that. Or we can `ForkCtxSpan` like `RunAsyncTask` and (as Tamir suggests) pass that to the worker as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153)*

**Comment by knz** [comment]
So what I was writing to tamir offline is that I observed we are rather consistent at not passing a context with a span to a worker function via `RunWorker`. My understanding from past discussions with andrei is that we've been disciplined about not creating very long-lived spans, because trace collectors don't like that. Because of this our existing calls to `RunWorker` happen to not use context with spans.

Now Tamir is suggesting I enforce this in the code, but I am still a bit uneducated and am having a hard time figuring out how. His suggestion is to call `opentracing.ContextWithSpan(ctx, nil)`, is this sufficient?

**Comment by RaduBerinde** [comment]
We are not passing a context via `RunWorker` at all right now. We use contexts inside the worker function on a case-by-case basis, but in many cases the function doesn't use a context at all, so in those cases whatever we are now passing into `RunWorker` is new.

Yes, using `opentracing.ContextWithSpan(ctx, nil)` instead of `ctx` would be sufficient.

**Comment by knz** [comment]
I have added an additional commit to do what Tamir suggested. PTAL

**Comment by knz** [comment]
Review status: 53 of 168 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/stop/stopper.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki5atF25Pm1IUuT7dcQ:-Ki5xAQQJqj7zWcS3AbL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a509b3ec94cc87981107fc29008ccc4f4cf5e182/pkg/util/stop/stopper.go#L205)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it may be a good idea, in a follow-up, to pass this context (or a derivative of it) into `f`. This is already done in `RunAsyncTask`.
</blockquote></details>

Done.

---

*[pkg/util/stop/stopper.go, line 208 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki5heyC_6Yfip_-419-:-Ki5xCDmvqis26EHyoEe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a509b3ec94cc87981107fc29008ccc4f4cf5e182/pkg/util/stop/stopper.go#L208)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I agree with Andrei, the caller can easily pass a context with a span which is not safe in general. If we are confident that we never use spans in here, we should assert that. Or we can `ForkCtxSpan` like `RunAsyncTask` and (as Tamir suggests) pass that to the worker as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153)*

**Comment by tamird** [comment]
Reviewed 1 of 35 files at r2.
Review status: 54 of 168 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/util/stop/stopper.go, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki6n4UqdkMvoVzqUVRF:-Ki6n4UqdkMvoVzqUVRG:bo6f2h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a5b544cd3f802fd19b3450885c1af70458ccd6/pkg/util/stop/stopper.go#L243)):*
> ```Go
> 	}
> 
> 	ctx, span := tracing.ForkCtxSpan(ctx, key.String())
> ```

there is absolutely no reason to fork this one.

---

*[pkg/util/stop/stopper.go, line 271 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki6n8ekFoMLjCZvnssX:-Ki6n8ekFoMLjCZvnssY:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a5b544cd3f802fd19b3450885c1af70458ccd6/pkg/util/stop/stopper.go#L271)):*
> ```Go
> 	}
> 
> 	ctx, span := tracing.ForkCtxSpan(ctx, key.String())
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153)*

**Comment by knz** [comment]
Review status: 54 of 168 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/util/stop/stopper.go, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki6n4UqdkMvoVzqUVRF:-Ki6pRraCzHQDTDV6XsY:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a5b544cd3f802fd19b3450885c1af70458ccd6/pkg/util/stop/stopper.go#L243)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there is absolutely no reason to fork this one.
</blockquote></details>

Fixed.

---

*[pkg/util/stop/stopper.go, line 271 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-Ki6n8ekFoMLjCZvnssX:-Ki6pSk6hawlPh1zRERK:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9a5b544cd3f802fd19b3450885c1af70458ccd6/pkg/util/stop/stopper.go#L271)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153)*

**Comment by tamird** [comment]
Only reviewed the stopper, assuming the rest is mechanical.

---

Reviewed 1 of 35 files at r4.
Review status: 52 of 168 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15153#-:-Ki6sAlnBWb4mmAf7PMz:b-jwatn)*

**Comment by knz** [comment]
Yes, it was. TFYR!

**Pull request merged**
