### PR TITLE
colexecbase: deflake TestRandomizedCast

### LINKED ISSUE #73849: sql/colexec/colexecbase: TestRandomizedCast failed
sql/colexec/colexecbase.TestRandomizedCast [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3916285&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3916285&tab=artifacts#/) on master @ [d1c137d279e03f7190f228e78db5c1a74b93df17](https://github.com/cockroachdb/cockroach/commits/d1c137d279e03f7190f228e78db5c1a74b93df17):

```
Slow failing tests:
TestRandomizedCast - 0.00s

Slow passing tests:
<none>
```
<details><summary>Help</summary>
<p>
See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)Parameters in this failure:

- GOFLAGS=-race -parallel=4
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomizedCast.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #73849.

Release note: None

### CODE REVIEW

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Thanks for the quick fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-:-MrU74_E62_MSYdwnUAN:b-e69qx5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6DPt6vU17Ny4sQdH:-MrU6DPt6vU17Ny4sQdI:b54gu1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L48)):*
> ```Go
> 		for {
> 			from, to = randgen.RandType(rng), randgen.RandType(rng)
> 			if from.String() == "void" && to.String() == "char" {
> ```

Is `void` -> `char` the only conversion that would cause this issue, or do we need to consider `void` -> `*` or `*` -> `void`?
___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6Y5F2g_4CRKJPMQ6:-MrU6Y5F2g_4CRKJPMQ7:bp8ojvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L49)):*
> ```Go
> 			from, to = randgen.RandType(rng), randgen.RandType(rng)
> 			if from.String() == "void" && to.String() == "char" {
> 				// Skip the cast from void to char because of the TODO below the
> ```

nit: I assume you mean the TODO on line ~85? Could you add a comment below at the start of that section with "// Datum generation." so it's easier to follow up if/when this gets fixed?

nit: s/of the/the

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rharding6373)

___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6DPt6vU17Ny4sQdH:-MrU7Sxr910tYU2u5uCT:b-an45bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L48)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is `void` -> `char` the only conversion that would cause this issue, or do we need to consider `void` -> `*` or `*` -> `void`?
</blockquote></details>

I think it's the only possible scenario. My understanding is that if we're casting from `void`, then `fromDatum` is always `DVoidDatum`, and it casts to an empty string. This is exactly what the TODO below is about.
___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6Y5F2g_4CRKJPMQ6:-MrU8zuW7r53of4sXVSp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L49)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: I assume you mean the TODO on line ~85? Could you add a comment below at the start of that section with "// Datum generation." so it's easier to follow up if/when this gets fixed?

nit: s/of the/the
</blockquote></details>

Done.

**Review by rharding6373 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-:-MrU9o92CXreINb-rnWY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6DPt6vU17Ny4sQdH:-MrU9q50EH1c6ol69m2A:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L48)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think it's the only possible scenario. My understanding is that if we're casting from `void`, then `fromDatum` is always `DVoidDatum`, and it casts to an empty string. This is exactly what the TODO below is about.
</blockquote></details>

Thanks!

**Comment by otan** [comment]
___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6DPt6vU17Ny4sQdH:-MrUCY-t0n1AfNRJvw38:b5a5rfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L48)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

would prefer comparing `from.Oid()` / `to.Oid()`, otherwise LGTM.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-:-MrUDkUe3jpQ3A3Ti09Z:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

___
*[pkg/sql/colexec/colexecbase/cast_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74178#-MrU6DPt6vU17Ny4sQdH:-MrUDi2E2Fec7LPasQmW:bmzjanc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a61cbd3510d23b71ba76e71ec5c6c75f69129a0/pkg/sql/colexec/colexecbase/cast_test.go#L48)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

would prefer comparing `from.Oid()` / `to.Oid()`, otherwise LGTM.
</blockquote></details>

Switched to oids.

**Pull request merged**
