### PR TITLE
exec: add projections of AndExpr

### PR DESCRIPTION
**Pull request by jordanlewis**
This adds support for TPCH q19, which sees a 3x speedup with vectorized.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40471#-:-LnxM3ZwB-movLH21D0E:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 902 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40471#-LnxvywW4p31QEpJgE7M:-LnxvywW4p31QEpJgE7N:b68hmif) ([raw file](https://github.com/cockroachdb/cockroach/blob/35bd3db6c2c8ec30dfb69b6b410cc3cdd32874bd/pkg/sql/distsqlrun/column_exec_setup.go#L902)):*
> ```Go
> 		}
> 		// Add a new boolean column that ands the two output columns.
> 		resultIdx := len(ct)
> ```

`resultIdx` is already defined in this scope -- it seems like other branches of this code would name this variable `outputIdx` to avoid the collision.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 902 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40471#-LnxvywW4p31QEpJgE7M:-LnxwFydE3qLVVVvVgjL:b-nlpir2) ([raw file](https://github.com/cockroachdb/cockroach/blob/35bd3db6c2c8ec30dfb69b6b410cc3cdd32874bd/pkg/sql/distsqlrun/column_exec_setup.go#L902)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`resultIdx` is already defined in this scope -- it seems like other branches of this code would name this variable `outputIdx` to avoid the collision.
</blockquote></details>

or i guess some reuse `resultIdx` with the `=` operator instead of `:=`

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40471)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @solongordon, and @yuzefovich)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
