### PR TITLE
storage: reduce the cache size from 128MiB to 8MiB for in-mem temp engine

### PR DESCRIPTION
**Pull request by ajwerner**
The change was motivated by a desire to remove the cache altogether. Jackson
pointed out that it's useful to avoid decompression. Comments indicate that a
non-zero cache is required.  Nevertheless, a smaller cache was widely
supported.

Release note: None

### CODE REVIEW

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jbowens)

___
*[pkg/storage/temp_engine.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-MllSelvAgmUnvbsSf0Q:-MllSelvAgmUnvbsSf0R:ba8g6qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1645c8f088444fa2c6ed709e4f8349f5f825e52a/pkg/storage/temp_engine.go#L74)):*
> ```Go
> 
> 	p, err := Open(ctx, loc,
> 		CacheSize(cacheSize),
> ```

Not sure if this comment is still relevant: https://github.com/cockroachdb/cockroach/blob/161c2f30a06f1a4a01b68fe780c90d6c7e50daa7/pkg/storage/engine/temp_engine.go#L105-L106

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl and @jbowens)

___
*[pkg/storage/temp_engine.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-MllSelvAgmUnvbsSf0Q:-MllXnmk0trr4pvkFCSm:bxmfgjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1645c8f088444fa2c6ed709e4f8349f5f825e52a/pkg/storage/temp_engine.go#L74)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Not sure if this comment is still relevant: https://github.com/cockroachdb/cockroach/blob/161c2f30a06f1a4a01b68fe780c90d6c7e50daa7/pkg/storage/engine/temp_engine.go#L105-L106
</blockquote></details>

It certainly seems relevant

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jaylim-crl, and @jbowens)

___
*[pkg/storage/temp_engine.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-MllSelvAgmUnvbsSf0Q:-Mlm2IOT9m19bg7u5mG3:bpu2ir4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1645c8f088444fa2c6ed709e4f8349f5f825e52a/pkg/storage/temp_engine.go#L74)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It certainly seems relevant 
</blockquote></details>

Let's use 8MB for the in-memory case, which also happens to be the value of `cacheDefaultSize` in pebble (when a cache isn't supplied and it creates one).

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jaylim-crl, and @sumeerbhola)

___
*[pkg/storage/temp_engine.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-MllSelvAgmUnvbsSf0Q:-MlouVZg3S7cHZd84pbt:bqpblvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1645c8f088444fa2c6ed709e4f8349f5f825e52a/pkg/storage/temp_engine.go#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Let's use 8MB for the in-memory case, which also happens to be the value of `cacheDefaultSize` in pebble (when a cache isn't supplied and it creates one).
</blockquote></details>

+1 to smaller non-zero block cache. A block cache on an in-memory store does prevent decompressing blocks when there's a hit.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl and @sumeerbhola)

___
*[pkg/storage/temp_engine.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-MllSelvAgmUnvbsSf0Q:-MlqeSVn07RqB7a7uQZZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1645c8f088444fa2c6ed709e4f8349f5f825e52a/pkg/storage/temp_engine.go#L74)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

+1 to smaller non-zero block cache. A block cache on an in-memory store does prevent decompressing blocks when there's a hit.
</blockquote></details>

Done.

**Review by jbowens — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71416#-:-MlzgSA6-xcBfUZQNHtt:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jaylim-crl and @sumeerbhola)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
