### PR TITLE
sql: address minor typos in recent overflow fix

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes minor typos introduced in #88199.

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88969#-:-ND9z26EExhD-9VD3Ssq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88969#-:-ND9zYpT9yK7rX9ndHtK:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
blathers backport 22.2.0

**Pull request merged**
