### PR TITLE
config: disallow 2 replica configurations

### LINKED ISSUE #5809: Disallow even number of replicas in a zone configuration
Currently, you can specify an even number of replicas in a zone configuration. For example:

```
$ ./cockroach zone set .default  'replicas:
- attrs: [us-east-1a]
- attrs: [us-east-1b]
- attrs: [us-west-1a]
- attrs: [us-west-1b]'
```

@petermattis mentioned that this can lead to situations where both sides of a network partition can form a quorum. 

We should therefore require that zones always list an odd number of replicas.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #5809.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5830)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/config.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830#-KESVxX60VWQa0IdypHz:-KESVxX7eW8Rh9jxdys4:192918479) ([raw file](https://github.com/cockroachdb/cockroach/blob/718421bc6c01fc5f00df9f1b4d683464ece08a9f/config/config.go#L123)):*
@bdarnell Any suggestions for better error text? I'm not satisfied with the above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/config.go, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830#-KESWDNRpUYnSIkqY02W:-KESWDNRpUYnSIkqY02X:1165345580) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c72c0dff63b40f7dd4dcd2c670cfd4375741a88/config/config.go#L120)):*
Switch to `fmt.Errorf` because these are user facing errors that occur when someone specifies an invalid zone config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/config.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830#-KESVxX60VWQa0IdypHz:-KESWgqLiqqPBSuC89Qa:1126657127) ([raw file](https://github.com/cockroachdb/cockroach/blob/718421bc6c01fc5f00df9f1b4d683464ece08a9f/config/config.go#L123)):*
"at least 3 replicas are required for multi-replica configurations"? Maybe link to the docs instead of trying to explain why here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830#-:-KESXMBC9QnRBIdPrHmr:676834233)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[config/config.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830#-KESVxX60VWQa0IdypHz:-KETiq052ky0oPoZ8n5G:125510347) ([raw file](https://github.com/cockroachdb/cockroach/blob/718421bc6c01fc5f00df9f1b4d683464ece08a9f/config/config.go#L123)):*
Yeah, I like that better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5830)*

**Pull request merged**
