### PR TITLE
coldata: clean up the vectorized templates and nulls

### PR DESCRIPTION
**Pull request by yuzefovich**
**coldata: clean up the templates**

This commit makes several tweaks to the templates:
- in vec_tmpl:
    - remove slicing in _COPY_WITH_SEL. I think it was neither accomplishing
      its goal of bounds check elimination nor was actually correct.
    - add a type information to a slice of Vec.
- rename the generator file.
- remove SWAP placeholder since it's not used anymore.
- rename SwapNulls to swap so that is unexported, but it is not removed just
  case we need it later since it contains non-trivial logic.

**coldata: combine two Nulls.Extend variations into one method**

This commit combines Extend and ExtendWithSel into one method
'duplicate' which is now unexported and is called as part of
Vec.Copy and Vec.Append methods.

**coldata: extract out "core" slice args from AppendArgs and CopyArgs**

Both AppendArgs and CopyArgs had the same "core" which is now extracted
as SliceArgs. CopySliceArgs is now an extension of SliceArgs. This allows
for unifying the interfaces a little bit. Also, Nulls.duplicate is
renamed to Nulls.set.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/col/coldata/vec.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUQbDE9zJaxAHGt01O:-LnUQbDE9zJaxAHGt01P:byt84rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/vec.go#L25)):*
> ```Go
> // VecArgs represents the arguments passed in to Append and Copy methods of
> // Vec.
> type VecArgs struct {
> ```

This name does not seem very good. How about SliceArgs or something?

Also, isn't it messy to collapse into one? `SelOnDest` for example does not get used in one of the branches. Or should we perhaps we panic in the cases where an argument set but is not used?

I dunno, I don't think I like this approach very much because each of the methods takes a different set of these arguments. We're adding (small) overhead everywhere to remove a small amount of code duplication - it doesn't seem worth it to me.

What about the idea of having a "core" struct that has all of the arguments everyone uses, and embed that into other structs to specialize for each of the different functions?
___
*[pkg/col/coldata/vec.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUTedxDtY3Ik0MCEJT:-LnUTedy23mSqcjhDyF6:b-kv5t41) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/vec.go#L94)):*
> ```Go
> 	// Vec.
> 	// Refer to the VecArgs comment for specifics and TestAppend for examples.
> 	Append(*VecArgs)
> ```

These shouldn't take pointers I don't think - it's too likely we'll mess up and cause allocations. The structs are small enough to pass around - it's the same as what we had when passing arguments.

**Review by jordanlewis — COMMENTED** [review]
I like the idea of adding the simplified method of setting nulls.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-:-LnUUHMk91HMMfVW-v9-:b-r7pk5q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-LnUUFiD-W53toAjy8VW:bv4o0l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
> ```Go
> // extended; otherwise, any overlapping old values are overwritten, and this
> // nulls is also extended if necessary.
> func (n *Nulls) duplicate(args *VecArgs) {
> ```

Maybe this should be called copy instead?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-LnUVCYd9WouB05KfnKK:bmw6d28) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Maybe this should be called copy instead?
</blockquote></details>

I was trying to find a word which doesn't match to builtins `copy` and `append` in order not to cause the additional confusion. I guess since it's unexported now, `copy` could work.
___
*[pkg/col/coldata/vec.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUQbDE9zJaxAHGt01O:-LnUW5smCdPt9jnHwcRX:bxuxse5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/vec.go#L25)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This name does not seem very good. How about SliceArgs or something?

Also, isn't it messy to collapse into one? `SelOnDest` for example does not get used in one of the branches. Or should we perhaps we panic in the cases where an argument set but is not used?

I dunno, I don't think I like this approach very much because each of the methods takes a different set of these arguments. We're adding (small) overhead everywhere to remove a small amount of code duplication - it doesn't seem worth it to me.

What about the idea of having a "core" struct that has all of the arguments everyone uses, and embed that into other structs to specialize for each of the different functions?
</blockquote></details>

I like your suggestion about "core" struct, I'll refactor the code.
___
*[pkg/col/coldata/vec.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUTedxDtY3Ik0MCEJT:-LnUWQKwCOHnpRIdRedo:b-h7wcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/vec.go#L94)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These shouldn't take pointers I don't think - it's too likely we'll mess up and cause allocations. The structs are small enough to pass around - it's the same as what we had when passing arguments.
</blockquote></details>

Okay, I'll revert this back to value.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-LnUqD5m9zc8xkTU0TKz:bh71ent) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I was trying to find a word which doesn't match to builtins `copy` and `append` in order not to cause the additional confusion. I guess since it's unexported now, `copy` could work.
</blockquote></details>

I kept `duplicate` to be called by both `copy` and `append`. Any ideas on a better name are welcome (I personally don't like the previous version "extend").
___
*[pkg/col/coldata/vec.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUQbDE9zJaxAHGt01O:-LnUqTUe--O92W5dfJHf:b-ckjcco) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/vec.go#L25)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I like your suggestion about "core" struct, I'll refactor the code.
</blockquote></details>

I started refactoring code for "core" struct, but it seemed like too much friction (structs are not interfaces where you can just "go one layer down"), so I decided to revert the changes I was making.

**Comment by jordanlewis** [comment]
> I started refactoring code for "core" struct, but it seemed like too much friction (structs are not interfaces where you can just "go one layer down"), so I decided to revert the changes I was making.

I'm not sure I follow the one layer down suggestion?

My idea is:

```
type argsBase struct {
    source
    dest
    ...
}

type appendArgs struct {
    argsBase
    extraThingHere
}
```

Maybe that's already what you tried but I don't see what was too annoying about it?

**Review by yuzefovich — COMMENTED** [review]
Yeah, that's what I tried, but for some reason I couldn't do something like `appendArgs.source` - the compiler wanted `appendArgs.argsBase.source`. Probably I messed it up somehow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-:-LnUtLy88z7DOaKEPYxD:b33ym44)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-LnYTwdrEQzPP-_2WGVz:b-dqvbss) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I kept `duplicate` to be called by both `copy` and `append`. Any ideas on a better name are welcome (I personally don't like the previous version "extend").
</blockquote></details>

i do think the names `copy` and `append` are a bit confusing. reading it here is a bit difficult since reviewable highlights those identifiers which makes it seem even more like they are the builtin functions. maybe `copyNulls` and `appendNulls`, as long as you don't think that's too redundant? also, i am unclear what the difference is between `append` and `copy` now?

**Review by yuzefovich — COMMENTED** [review]
I've refactored the code to extract the "core" args. Please let me know what you guys think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-:-LnYsuAG9ARyx_4GjqP3:b-4wv95b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-LnYsm6A3WNwN2QFV-Wd:b-robd03) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i do think the names `copy` and `append` are a bit confusing. reading it here is a bit difficult since reviewable highlights those identifiers which makes it seem even more like they are the builtin functions. maybe `copyNulls` and `appendNulls`, as long as you don't think that's too redundant? also, i am unclear what the difference is between `append` and `copy` now?
</blockquote></details>

The only difference was the type of `args` that are passed in.

**Comment by yuzefovich** [comment]
PTAL at this PR.

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-Lo1UgWH2DcjvwJSSaFV:btfxzpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The only difference was the type of `args` that are passed in.
</blockquote></details>

What about `Set`? Inspiration from `apd.Decimal.Set(other apd.decimal)`.
___
*[pkg/col/coldata/vec.go, line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-Lo1XGTP853B-bejx02Y:-Lo1XGTP853B-bejx02Z:b-r63gq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/486763959af281ccf017b47e2059075bef3172aa/pkg/col/coldata/vec.go#L46)):*
> ```Go
> // ExtendedSliceArgs represents the extension of SliceArgs that is passed in to
> // Vec.Copy.
> type ExtendedSliceArgs struct {
> ```

What about CopySliceArgs then?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/col/coldata/nulls.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-LnUUFiC3gj_4pxeFdqw:-Lo1dZFO0KrqHFPYggSK:b97mnyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4e8e30c34d58ab95b5769641593e4972a536869/pkg/col/coldata/nulls.go#L233)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about `Set`? Inspiration from `apd.Decimal.Set(other apd.decimal)`.
</blockquote></details>

I think it's not ideal, but I like it more than `duplicate`, thanks.
___
*[pkg/col/coldata/vec.go, line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40255#-Lo1XGTP853B-bejx02Y:-Lo1eKiA9Gjgu3sdO6j6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/486763959af281ccf017b47e2059075bef3172aa/pkg/col/coldata/vec.go#L46)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about CopySliceArgs then?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
