### PR TITLE
roachtest: fix ports in ruby-pg helper

### LINKED ISSUE #118499: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13747378?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13747378?buildTab=artifacts#/ruby-pg) on master @ [1d2534b831775dd84edcf7372d38e35ed4903278](https://github.com/cockroachdb/cockroach/commits/1d2534b831775dd84edcf7372d38e35ed4903278):

```
(test_runner.go:1130).runTest: test timed out (1h0m0s)
test artifacts and logs in: /artifacts/ruby-pg/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13747378/ruby-pg/1706640154035/1706643896388)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35761

### PR DESCRIPTION
**Pull request by rafiss**
The test suite needs this logic so that certain tests work correctly.

fixes https://github.com/cockroachdb/cockroach/issues/118499
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
Testing here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13758177?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118501)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/ruby_pg_helpers.rb` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118501#-NpV-qRA96ubzSch0ovh:-NpV-qRA96ubzSch0ovi:br38grc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49cf8fc9c09e7cdb78f6efcc6dc61416a31dc1b/pkg/cmd/roachtest/tests/ruby_pg_helpers.rb#L34)):*
> ```Ruby
> 				@conn = $pg_server.connect
> 
> 				# Find a local port that is not in use
> ```

the changes come from copying this file from upstream: https://github.com/ged/ruby-pg/blob/v1.4.6/spec/helpers.rb

**Review by annrpom — APPROVED** [review]
ok! lgtm

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
