### PR TITLE
cli: Add halt-cluster command

### PR DESCRIPTION
**Pull request by tbg**
This new command hooks up the ClusterFreeze command, which for the
time being implements our active migration model (stop-the-world
updates).

I'm open to naming this differently (as long as concrete suggestions are
given). I have also considered `--stop-the-world` but finding that not very
concrete.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6675)

### CODE REVIEW

**Comment by tamird** [comment]
Can you make this a grpc-gateway style command? We already have an issue to convert `node` and `quit` - let's not add more work to that.

**Comment by tschottdorf** [comment]
Sure. Care to point out a precedent I can copy from?

On Fri, May 13, 2016, 20:20 Tamir Duberstein <notifications@github.com>
wrote:

> Can you make this a grpc-gateway style command? We already have an issue
> to convert node and quit - let's not add more work to that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6675#issuecomment-219188118>
>
-- 

-- Tobias

**Comment by tamird** [comment]
Yep take a look at admin.proto and follow the breadcrumbs from there - the
compiler should help out once you add the service definitions.

On Fri, May 13, 2016 at 8:29 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
This is already in `admin.proto` (`ClusterFreeze`). This PR only adds a `cli` command that queries that endpoint. What should I be doing instead?

**Comment by tamird** [comment]
Oh, my mistake. You'll have to shave a new yak - the command will need to construct an RPC context and open a connection, then construct an admin client (the `server.NewAdminClient` kind, not `client.NewAdminClient`), and should be clear from there.

No precedent for this exists currently that I could find.

**Comment by tschottdorf** [comment]
The yak is now butt naked. PTAL.


On Fri, May 13, 2016 at 10:12 PM Tamir Duberstein <notifications@github.com>
wrote:

> Oh, my mistake. You'll have to shave a new yak - the command will need to
> construct an RPC context and open a connection, then construct an admin
> client (the server.NewAdminClient kind, not client.NewAdminClient), and
> should be clear from there.
>
> No precedent for this exists currently that I could find.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/6675#issuecomment-219195180>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> The yak is now butt naked. PTAL.
> 
> I'll give 'quit' the same treatment (and also hook up `Drain`). But probably different PR.
> 
> </details>


---

Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6675#-:-KHrT-rvuA1SdpSthnvH:1417088721)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6675#-:-KHrVcswUFtMr2q_YaD7:1417088721)*

**Comment by jseldess** [comment]
I don't think `halt` is distinct enough from `quit`. Can we just go with `cockroach freeze`? `freeze` isn't as final and implies that it'll come back to life.

**Comment by tschottdorf** [comment]
@bdarnell what do you think about `freeze` vs `halt`?

**Comment by tschottdorf** [comment]
I pushed some more work updating the `quit` command. @jseldess, can you take a look as well?
PTAL

**Comment by bdarnell** [comment]
Calling it "freeze" instead of "halt" is fine with me (maybe introduce a `cluster` subcommand, for `cockroach cluster freeze`?). I don't like the additions to `quit` - `quit --resume` is just weird. Do we really need to be able to drain a node without killing it (and having done so, do we need to be able to undrain it in place instead of just restarting)? If we do need this I'd rather introduce it as `cockroach node drain` and `cockroach node drain --undo`, leaving `cockroach quit` as drain-then-kill. 

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I pushed some more work updating the `quit` command. @jseldess, can you take a look as well?
> 
> PTAL</details>


---

Reviewed 1 of 5 files at r7.
Review status: 1 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6675#-:-KHu2RSp-N02iYLVMmWE:-1876144272)*

**Comment by tschottdorf** [comment]
> maybe introduce a cluster subcommand, for cockroach cluster freeze?

I thought about that, but it's a bit silly to have a subcommand that has only one item. Maybe other items fit in, but that's a yak I don't want to start shaving right now.

I retracted the post-LGTM changes (mod the halt-freeze rename). I think drain and undrain are useful, but since it's clearly controversial, I don't want to discuss it now.

**Pull request merged**
