### PR TITLE
sql: keep track of statement error code and error message in crdb_internal.execution_insights

### PR DESCRIPTION
**Pull request by gtr**
Part of: #87785, #94381.

Previously, the insights subsystem did not keep track of error code and error messages for failed executions and only contained a `FailedExecution` value for the `problem` field. This commit adds the `error_code` and `error_msg` columns to the `crdb_internal.cluster_execution_insights` virtual table. The next PR will focus on displaying these values in the UI.

Example:
image

Release note (sql change): Added `error_code` and `error_msg` columns to the `crdb_internal.cluster_execution_insights` virtual table which contain the error code and error message for a failed statement execution, respectively.

### CODE REVIEW

**Review by xinhaoz — COMMENTED** [review]
Looking good! Can we add some tests? Also just a small question on naming - do we need the prefix `Last` here? I feel like it's appropriate here in just shortening them to `error` and `errorCode`.

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95856#-:-NN7UkP-0acmDEUw9p0p:b68y33g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/sql/sqlstats/insights/registry.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95856#-NN7TdpH1_QACb1ijiUX:-NN7TdpH1_QACb1ijiUY:bgn50he) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd55b4fb019145fb36e38f5938471bd331cf6ecb/pkg/sql/sqlstats/insights/registry.go#L129)):*
> ```Go
> 			}
> 			insight.Transaction.Problems = addProblem(insight.Transaction.Problems, s.Problem)
> 			// TODO(gerardo): bubble up stmt failed execution error codes
> ```

Is this  TODO going to be addressed in this PR? If not maybe we can file a ticket for it and remove this TODO, as there's no additions here you need to come back and change.

**Review by gtr — COMMENTED** [review]
Thanks! Working on adding tests now. Also, good suggestion on simplifying the names.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95856#-:-NN7yNc12t-vh0ct_VPW:bbyscr5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/sqlstats/insights/registry.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95856#-NN7TdpH1_QACb1ijiUX:-NN7yCFpB7t9pN1YTOZl:b-hv85fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd55b4fb019145fb36e38f5938471bd331cf6ecb/pkg/sql/sqlstats/insights/registry.go#L129)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Is this  TODO going to be addressed in this PR? If not maybe we can file a ticket for it and remove this TODO, as there's no additions here you need to come back and change.
</blockquote></details>

I don't think it'll be addressed in this PR, so I'll go ahead and remove it and file a ticket.

**Comment by maryliag** [comment]
As discussed offline, focus one PR on adding the information to statement and transaction statistics, then another PR on adding the information to insights, then another focusing on capturing all failed executions. This way is more clear, easy for you to develop and easier to review.

**Comment by gtr** [comment]
> As discussed offline, focus one PR on adding the information to statement and transaction statistics, then another PR on adding the information to insights, then another focusing on capturing all failed executions. This way is more clear, easy for you to develop and easier to review.

Added the information to the statement statistics table on [this](https://github.com/cockroachdb/cockroach/pull/96436) PR. Closing this one and saving these changes for later. Thanks!

**Pull request closed without merging**
