### PR TITLE
workload,ttl: add TTL workload for benchmarking time to finish

### LINKED ISSUE #88172: sql: performance test TTL for GA
Implement a workload that measures the performance of the TTL job. The workload should allow us to test at the terabyte scale.

Epic CRDB-14592

Jira issue: CRDB-19716

### PR DESCRIPTION
**Pull request by ecwall**
fixes https://github.com/cockroachdb/cockroach/issues/88172

Measures time row-level TTL job takes to run on a table:
1) Drop TTL table IF EXISTS.
2) Create a table without TTL.
3) Insert initialRowCount number of rows.
4) Gets number of rows that should expire.
5) Wait for table ranges to stabilize after scattering.
6) Enable TTL on table.
7) Poll table until TTL job is complete.
Note: Ops is a no-op and no histograms are used.
Benchmarking is done inside Hooks and details are logged.

Adds useDistSQL field to TTL job progress protobuf for
visibility into which version was run during cluster
upgrades.

Release justification: Added TTL workload.

Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBQ7vZt7UMr1m18Y44s):*
Could we please add some more context to the commit message? E.g., what's the motivation for this PR? how and where is this workload planned to be used? what is exactly is "TTL job" (it's no immediately obvious without reading the bench code)?

**Review by rafiss — CHANGES_REQUESTED** [review]
small nits and a question: so this means that the latency is not actually available from the histogram right? it's only available by looking at the logs?

i think that would be worth mentioning in the description of the job.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-:-NBYl9K9597WGWoWrm98:b2dveum)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @herkolategan, @renatolabs, and @srosenberg)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBQ7vZt7UMr1m18Y44s):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Could we please add some more context to the commit message? E.g., what's the motivation for this PR? how and where is this workload planned to be used? what is exactly is "TTL job" (it's no immediately obvious without reading the bench code)?
</blockquote></details>

in addition to the commit message, let's add that to the `workload.Meta.Description` field.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBYk9K68kxzNNVRxjkJ:-NBYk9K68kxzNNVRxjkK:bnjes0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c62a476a0c3e8ea28060b3a21ec5f78d7a6db0/pkg/workload/ttlbench/ttlbench.go#L72)):*
> ```Go
> 	var count int
> 	row := db.QueryRow(fmt.Sprintf("SELECT count(1) FROM %s WHERE expire_at < '%s'", ttlTableName, now.Format(time.RFC3339)))
> 	if err := row.Err(); err != nil {
> ```

the check for `row.Err()` is not needed, since `row.Scan` already checks for that
___
*[`pkg/workload/ttlbench/ttlbench.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBYkrbn8Fo754Vk_FJx:-NBYkrbpAZFo09WkLEw4:bt7yjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c62a476a0c3e8ea28060b3a21ec5f78d7a6db0/pkg/workload/ttlbench/ttlbench.go#L83)):*
> ```Go
> func (t *ttlBench) Hooks() workload.Hooks {
> 	return workload.Hooks{
> 		// clear the table in case a previous run left records
> ```

nit: for all the comments, we should use capitalization and complete sentences with punctuation.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, @renatolabs, and @srosenberg)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBQ7vZt7UMr1m18Y44s):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in addition to the commit message, let's add that to the `workload.Meta.Description` field.
</blockquote></details>

Added some details to commit message and `Description.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBYk9K68kxzNNVRxjkJ:-NCzvkfQ7jP_6VKW_hd9:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c62a476a0c3e8ea28060b3a21ec5f78d7a6db0/pkg/workload/ttlbench/ttlbench.go#L72)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the check for `row.Err()` is not needed, since `row.Scan` already checks for that
</blockquote></details>

Fixed.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NBYkrbn8Fo754Vk_FJx:-NCzvlz16RHJQHDG_77Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c62a476a0c3e8ea28060b3a21ec5f78d7a6db0/pkg/workload/ttlbench/ttlbench.go#L83)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: for all the comments, we should use capitalization and complete sentences with punctuation.
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! i just had some small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-:-NDU0xnHET2cyWXMukaj:bgs3kbd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @herkolategan, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 255 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTrpvC5lGZf6BJT83t:-NDTrpvC5lGZf6BJT83u:b-swm2no) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/sql/ttl/ttljob/ttljob.go#L255)):*
> ```Go
> 		useDistSQL := execCfg.Settings.Version.IsActive(ctx, clusterversion.TTLDistSQL)
> 		jobRegistry := execCfg.JobRegistry
> 		if err := jobRegistry.UpdateJobWithTxn(
> ```

does this UpdateJobWithTxn fix a bug that's also in release-22.2?
___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 263 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTrzMv5adK-OGcX7E1:-NDTrzMv5adK-OGcX7E2:b-jhfbt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/sql/ttl/ttljob/ttljob.go#L263)):*
> ```Go
> 				progress := md.Progress
> 				rowLevelTTL := progress.Details.(*jobspb.Progress_RowLevelTTL).RowLevelTTL
> 				rowLevelTTL.UseDistSQL = useDistSQL
> ```

i don't see why why we need the `rowLevelTTL` variable. it's not referenced anyehere else i see
___
*[`pkg/workload/ttlbench/ttlbench.go` line 106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTzcET0efIgozyxkJ3:-NDTzcEWBhfLo3iYi6S4:bsh6qet) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L106)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

the `rows` need to be closed too. let's add something like this:
```
	defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()
```
and also make the return value named `retErr`. we use this pattern in other places, for example: https://github.com/cockroachdb/cockroach/blob/b5e54ff82c685229896f9354dcee4186293cf00c/pkg/workload/tpcc/checks.go#L103
___
*[`pkg/workload/ttlbench/ttlbench.go` line 126 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU-PK_3WsAkno0lrY2:-NDU-PK_3WsAkno0lrY3:b-bsjfgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L126)):*
> ```Go
> 			id, status, started, finished, proto.MarshalTextString(&rowLevelTTLProgress),
> 		)
> 	}
> ```

after the for loop, we also need a check for `rows.Err()` (it's only needed when querying multiple rows; if only one row is queried with `QueryRow` it's not needed)

e.g.:
```
if err := rows.Err(); err != nil {
  return err
}
```

take a look at: http://go-database-sql.org/errors.html
___
*[`pkg/workload/ttlbench/ttlbench.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU041xBzjDTpBWWKcu:-NDU041xBzjDTpBWWKcv:bo3jk4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L177)):*
> ```Go
> 		if err != nil {
> 			return err
> 		}
> ```

we'd want something similar to `defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()`

however, since this inside an outer `for` loop, the defer won't work well. one thing you can do to address it is to define a function inline, like:
```
pollFn := func() bool { ... }

for {
  if !pollFn() {
    break
  }
}
```
___
*[`pkg/workload/ttlbench/ttlbench.go` line 184 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU0m_pAm8eYWMBNcIm:-NDU0m_pAm8eYWMBNcIn:bscv64m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L184)):*
> ```Go
> 			}
> 			leaseholderToRangeIDs[leaseholder] = append(leaseholderToRangeIDs[leaseholder], rangeID)
> 		}
> ```

after this loop, we need a check for `rows.Err()`

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 255 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTrpvC5lGZf6BJT83t:-NDU39Mj-l41eFJ-hruB:b-i0y1wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/sql/ttl/ttljob/ttljob.go#L255)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this UpdateJobWithTxn fix a bug that's also in release-22.2?
</blockquote></details>

It is just to set `rowLevelTTL.UseDistSQL = useDistSQL` which I added for visibility into which type of TTL job runs. 

I think it should be in 22.2, but it doesn't fix a bug.
___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 263 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTrzMv5adK-OGcX7E1:-NDU3Ya-0EhLHNUIqqGS:b-7yrb3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/sql/ttl/ttljob/ttljob.go#L263)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't see why why we need the `rowLevelTTL` variable. it's not referenced anyehere else i see
</blockquote></details>

I'll combine these 2 rows then.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTzcET0efIgozyxkJ3:-NDU8Af3-MzQ-HZbVOfH:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L106)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the `rows` need to be closed too. let's add something like this:
```
	defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()
```
and also make the return value named `retErr`. we use this pattern in other places, for example: https://github.com/cockroachdb/cockroach/blob/b5e54ff82c685229896f9354dcee4186293cf00c/pkg/workload/tpcc/checks.go#L103
</blockquote></details>

Added.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 126 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU-PK_3WsAkno0lrY2:-NDU8P8tDIeYOisxoPtq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L126)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

after the for loop, we also need a check for `rows.Err()` (it's only needed when querying multiple rows; if only one row is queried with `QueryRow` it's not needed)

e.g.:
```
if err := rows.Err(); err != nil {
  return err
}
```

take a look at: http://go-database-sql.org/errors.html
</blockquote></details>

Done.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU041xBzjDTpBWWKcu:-NDUH1Xx2G-mZLgMvGpC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L177)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we'd want something similar to `defer func() { retErr = errors.CombineErrors(retErr, rows.Close()) }()`

however, since this inside an outer `for` loop, the defer won't work well. one thing you can do to address it is to define a function inline, like:
```
pollFn := func() bool { ... }

for {
  if !pollFn() {
    break
  }
}
```
</blockquote></details>

Done.
___
*[`pkg/workload/ttlbench/ttlbench.go` line 184 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDU0m_pAm8eYWMBNcIm:-NDUHJtM45SeZx8VMRye:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/workload/ttlbench/ttlbench.go#L184)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

after this loop, we need a check for `rows.Err()`
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-:-NDYXYBn2Iagd9vyfZrs:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @herkolategan, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/ttl/ttljob/ttljob.go` line 255 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-NDTrpvC5lGZf6BJT83t:-NDYVtfeDG9olvUux3gH:bjav49s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9b3aafbd62aefd0e6556265f937d5e614907e1/pkg/sql/ttl/ttljob/ttljob.go#L255)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

It is just to set `rowLevelTTL.UseDistSQL = useDistSQL` which I added for visibility into which type of TTL job runs. 

I think it should be in 22.2, but it doesn't fix a bug.
</blockquote></details>

ah ok got it, then we'll backport, but it's fine to do it for v22.2.1

**Comment by renatolabs** [comment]
This commit also changes the behavior of the `ttl` job and even changes a protobuf definition to make the workload possible. Would be nice to update the commit message to indicate that it includes these changes as well (if I was reading it, I'd think the changes are limited to the `workload` package).

I'm curious about one of Stan's questions that I didn't see answered:

> how and where is this workload planned to be used?

Is this meant to be run manually as a release qualification process, or are there plans to use the workload in an automated context (e.g., roachtest)?

**Review by ecwall — COMMENTED** [review]
I'll add a comment about the `ttl` job/protobuf change. 

> how and where is this workload planned to be used?
The only use case I had for the workload was to run it manually to answer customer questions about performance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87449#-:-NDYi8ZREWE4pOCjb3DX:b-9to8s7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @herkolategan, @rafiss, @renatolabs, and @srosenberg)

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
