### PR TITLE
sql: better checks on table version changes

### PR DESCRIPTION
**Pull request by vivekmenezes**
A big thank you to MutableTableDescriptor!

Release note: None

### CODE REVIEW

**Review by eriktrinh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32717)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/table.go, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKU2E5Hri3448XbAp:-LSVKU2F67NJ3nvZEiPE:bt9900q) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L506)):*
> ```Go
> 	if desc.Version != desc.ClusterVersion.Version + 1 {
> 		return errors.Errorf(
> 			"descriptor version incompatibility: %d vs %d", desc.Version, desc.ClusterVersion.Version)
> ```

error message could be more descriptive, maybe something like "descriptor version %d not incremented from cluster version %d"
___
*[pkg/sql/table.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKtpl4NSMtwSs4znd:-LSVKtpl4NSMtwSs4zne:b-qr9mtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L525)):*
> ```Go
> // returns all the idVersion pairs that have undergone a schema change.
> // Returns nil for no schema changes. The version returned for each
> // schema change is Version - 1, because that's the one that will be
> ```

This comment should still be `Version-2`, or maybe make it clear the difference between the cluster version and the incremented one.

**Review by vivekmenezes — COMMENTED** [review]
This commit has changed a bit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-:-LSVOL0k6PhOC0cgaNiI:b-tkknps)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/table.go, line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKU2E5Hri3448XbAp:-LSVOAD87C_idAU01b-3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L506)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

error message could be more descriptive, maybe something like "descriptor version %d not incremented from cluster version %d"
</blockquote></details>

Done.
___
*[pkg/sql/table.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKtpl4NSMtwSs4znd:-LSVOB2UBElOjrr2Xcb2:buacr9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L525)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

This comment should still be `Version-2`, or maybe make it clear the difference between the cluster version and the incremented one.
</blockquote></details>

I've pushed a new change which consolidates three calls under the same concept of using the previous descriptor version

**Review by eriktrinh — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-:-LSVRKvB5UPA6H53ZKKh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/table.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKtpl4NSMtwSs4znd:-LSVQy7hAyin6C6SIPKv:bgd8nel) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L525)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I've pushed a new change which consolidates three calls under the same concept of using the previous descriptor version
</blockquote></details>

Right, the returned version is `ClusterVersion-1` or `Version-2`.

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32717)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/table.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32717#-LSVKtpl4NSMtwSs4znd:-LSW0gG8CzNoRpv24SFo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96f158a4eb9ef8564e218f07dbb563e875bb13f1/pkg/sql/table.go#L525)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Right, the returned version is `ClusterVersion-1` or `Version-2`.
</blockquote></details>

Done.

**Pull request merged**
