### PR TITLE
cli: zip --redact to redact descriptors

### LINKED ISSUE #86309: `debug zip`: provide redacted form of `system.descriptor` when --redact flag used
**Is your feature request related to a problem? Please describe.**
https://github.com/cockroachdb/cockroach/pull/86180 introduced the --redact flag for the debug zip command. As a first iteration, it provides an immediate but coarse-grained level of compliance for debug zip bundles, where all sensitive data is omitted or redacted from the bundle (except for keys, which have been deemed necessary to support CockroachDB).

One area affected by this is the dumps of `crdb_internal.*` and `system.*` tables, where via an audit of all the dumped tables and their columns, we've implemented a mechanism where sensitive columns are simply omitted from the dumped tables when the --redact flag is provided.

However, this of course poses issues for our support team as some of these table dumps (and more specifically, certain columns) are crucial to their workflows.

One example of this is the `system.descriptor` table. The `descriptor` column in this table can contain sensitive information (for example, unredacted default values for columns contained within a `CREATE TABLE` statement). Therefore, in the first iteration of making debug zip compliant, this column has been omitted from `system.descriptor.txt` when the `--redact` flag is passed to `debug zip`.

We should provide a way to provide these descriptors in a redacted form, as opposed to omitting the descriptors entirely. This information has been identified by both KV and support staff alike as crucial in investigating support escalations, so omitting the data entirely is not a sustainable solution.

**Describe the solution you'd like**
Redaction of the descriptor is not immediately possible via a SQL query against `system.descriptor`. Is there an analogous gRPC/http endpoint that can be utilized until we find a more robust redaction solution at the SQL level? 

If so, we can utilize such an endpoint and its available redaction facilities to provide descriptors where only sensitive information is redacted. The `catalog.Descriptor` interface & its implementations provide a lot of data that's not sensitive, so we should provide as much as possible to avoid scenarios where people needing to analyze descriptors aren't left "blind".

Jira issue: CRDB-18688

Epic CRDB-12732

### PR DESCRIPTION
**Pull request by postamar**
Previously, `zip --redact` would collect a debug zip with the
descriptor and hex_descriptor column omitted in system.descriptor.txt.

This commit includes them after mapping the values to the new
crdb_internal.redact_descriptor builtin function.

This commit also fixes the broken behavior of `debug doctor ... zipdir`
when invoked on a redacted zip dir.

Fixes #86309.

Release note: None

-----

This PR includes @ajwerner 's commit in https://github.com/cockroachdb/cockroach/pull/87839 rebased and slightly modified.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 13 of 32 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/cli/doctor.go` line 432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90349#-NEr0-sj8Ufq3RN7h1vK:-NEr0-sj8Ufq3RN7h1vL:b-pep1a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6624aa58620ac1bdeef93f0f3cd19ac79483a6b7/pkg/cli/doctor.go#L432)):*
> ```Go
> 			// TODO(postamar): remove this check once payload redaction is improved
> 			if fields[last-1] == "NULL" {
> 				return nil
> ```

Is not returning an error better than telling the user the zip is redacted and they are going to have a bad time?



_Code quote:_
```Go
			// TODO(postamar): remove this check once payload redaction is improved
			if fields[last-1] == "NULL" {
				return nil
			}
```

**Comment by postamar** [comment]
> Is not returning an error better than telling the user the zip is redacted and they are going to have a bad time?

If we return an error, then we can't `doctor examine`, which is undesirable.

**Comment by ajwerner** [comment]
Should we log a warning at the end or something?

**Review by ajwerner — APPROVED** [review]

**Comment by postamar** [comment]
Thanks for the review! I thought about this a bit and reached the conclusion that it was best to wait until jobs payloads are properly redacted.

bors r+

**Pull request merged**
