### PR TITLE
sql: avoid a panic with multi-valued SRFs

### LINKED ISSUE #19149: sql: panic: SELECT pg_get_keywords()
``` panic while executing "SELECT pg_get_keywords() ": invalid var index 1 (columns: 1)```

Found with RSG.

### PR DESCRIPTION
**Pull request by knz**
This ensures that a multi-valued SRF in render position, e.g.
`SELECT pg_get_keywords()`, is rendered as a tuple, as in Postgres,
instead of crashing the server.

Fixes #19149.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5Z_yGqSOfWIEuVXW6:-Kw5Z_yGqSOfWIEuVXW7:b-x9idzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/data_source.go#L335)):*
> ```Go
> // getDataSourceAsOneColumn builds a planDataSource from a data source
> // clause and ensures that it returns one column. If the plan would
> // return zero or more than one column, the columns are grouped into
> ```

Could you add a test for the zero column case?

---

*[pkg/sql/render.go, line 372 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5_mir1F2ojkgFZ4t-:-Kw5_misqwL1vYlMzolM:b-yav0et) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/render.go#L372)):*
> ```Go
> 	r.ivarHelper = parser.MakeIndexedVarHelper(r, len(r.sourceInfo[0].sourceColumns))
> 	if err := r.initTargets(ctx,
> 		parser.SelectExprs{parser.SelectExpr{Expr: parser.UnqualifiedStar{}}}, nil); err != nil {
> ```

nit: we should create a single instance of `parser.UnqualifiedStar{}` and use that everywhere.

---

*[pkg/sql/logictest/testdata/logic_test/generators, line 265 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5Zt_eKTjzfk0JEISl:-Kw5Zt_eKTjzfk0JEISm:bbrnkaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/logictest/testdata/logic_test/generators#L265)):*
> ```
> # Beware of multi-valued SRFs in render position (#19149)
> query TTT colnames
> SELECT 'a', pg_get_keywords(), 'b' LIMIT 4
> ```

Add an SRF columns with an alias.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 335 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5Z_yGqSOfWIEuVXW6:-Kw5nEHSb_hLAYDcbV6m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/data_source.go#L335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a test for the zero column case?
</blockquote></details>

Done.

---

*[pkg/sql/render.go, line 372 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5_mir1F2ojkgFZ4t-:-Kw5fnRM8Fyk7RiAwQiI:blwh43c) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/render.go#L372)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we should create a single instance of `parser.UnqualifiedStar{}` and use that everywhere.
</blockquote></details>

We have many more lines doing a type switch on that than lines that create a value. I'm not sure that this would be a net win, unless you'd want to export both the type and the instance?

---

*[pkg/sql/logictest/testdata/logic_test/generators, line 265 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5Zt_eKTjzfk0JEISl:-Kw5fQszkoPPRHqT3hZX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/logictest/testdata/logic_test/generators#L265)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add an SRF columns with an alias.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/render.go, line 372 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5_mir1F2ojkgFZ4t-:-Kw5vHiRIJnSmj47K6SS:b-kuajwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/render.go#L372)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We have many more lines doing a type switch on that than lines that create a value. I'm not sure that this would be a net win, unless you'd want to export both the type and the instance?
</blockquote></details>

Yeah exporting both the type and the instance seems fine to me. I wasn't suggesting we un-export the type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-:-Kw5veWq_hFUu_TmsrP6:bnfp4nl)*

**Comment by knz** [comment]
TFYR

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/render.go, line 372 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-Kw5_mir1F2ojkgFZ4t-:-Kw5ymNpQKlj84P1nL1e:b-7p49gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/90676d26f63a76c36038306daa88ac3563124b16/pkg/sql/render.go#L372)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah exporting both the type and the instance seems fine to me. I wasn't suggesting we un-export the type.
</blockquote></details>

Ok I'll do a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19150#-:-Kw5yo4MQtYy9PvAojcf:bb73zww)*

**Pull request merged**
