### PR TITLE
release: move release qualification buckets

### PR DESCRIPTION
**Pull request by rail**
This PR moves the release qualification bucket to a new project.

Part of: RE-163
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]

**Comment by rail** [comment]
bors r=celiala

**Comment by rail** [comment]
bors retry

**Comment by rail** [comment]
bors retry

**Comment by rail** [comment]
blathers backport release-23.1.20-rc

**Comment by rail** [comment]
blathers backport release-23.2.5-rc

**Pull request merged**
