### PR TITLE
rpc: install custom proto codec

### LINKED ISSUE #60531: vendor: can't upgrade to grpc-go v1.34
**Describe the problem**

Cockroach built with grpc-go v1.34 panics shortly after start with the following error when running `./cockroach demo`:

```
panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer [recovered]
        panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer [recovered]
        panic: field cockroach.rpc.PingRequest.ping has invalid type: got string, want pointer

goroutine 6034 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000b5e540, 0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0x126
panic(0x7c5cf40, 0xc000e7e9d0)
        /usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000b5e540, 0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0x126
panic(0x7c5cf40, 0xc000e7e9d0)
        /usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:969 +0x1b9
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x932f640, 0xc0021eae00, 0x7b876a7, 0x4, 0x0, 0x0, 0x932f760, 0x7c5cf40, 0x7b876ad, 0x2c, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go:228 +0x7d7
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc002152000, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc002544150, 0xc002544180, 0xc0025441b0, 0xc0025441e0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:67 +0x97d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc002152000, 0x932f760, 0x829db40, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc002544150, 0xc002544180, 0xc0025441b0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:36 +0x65
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc002152000)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:90 +0x192
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).ProtoMethods(0xc000e7e6d0, 0xc002095218)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go:150 +0x53
google.golang.org/protobuf/proto.protoMethods(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0x93222e0, 0xc000e7e6d0, 0xc000e7e6d0, 0x93222e0, 0xc000e7e6d0, 0x827bf40, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/encode.go:143 +0x49
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x8000001, 0x0, 0x0, 0x0, 0x9143a00, 0xc000e7e6d0, 0x0, 0x14f790d8, 0x8, 0x7ca0d20, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/protobuf/proto/encode.go:125 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x14f790d8, 0xc001b04e40, 0x4054000, 0xc001030ba8, 0x0, 0x0, 0xc001030ba8, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/wire.go:40 +0xc7
github.com/golang/protobuf/proto.Marshal(...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/protobuf/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal(0x827bf40, 0xc001b04e40, 0xc001030ba8, 0xc002095468, 0xc002095468, 0x486316b, 0x7ca0d20)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto/proto.go:39 +0x5f
google.golang.org/grpc.encode(0x14b9cf40, 0xc000ac60d0, 0x827bf40, 0xc001b04e40, 0xc001380a60, 0xc0020956c8, 0xc000100000, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:592 +0x52
google.golang.org/grpc.prepareMsg(0x827bf40, 0xc001b04e40, 0x14b9cf40, 0xc000ac60d0, 0x0, 0x0, 0x91b6d20, 0xb4fa868, 0x2, 0xc0021bced0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:1559 +0x107
google.golang.org/grpc.(*clientStream).SendMsg(0xc002735e60, 0x827bf40, 0xc001b04e40, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:740 +0x165
google.golang.org/grpc.invoke(0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0xc002279180, 0xc0027fc1c0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:70 +0xe4
github.com/cockroachdb/cockroach/pkg/util/tracing.ClientInterceptor.func2(0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0xc002279180, 0x8b4ed88, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/grpc_interceptor.go:257 +0x158
google.golang.org/grpc.(*ClientConn).Invoke(0xc002279180, 0x91db9e0, 0xc001b04f60, 0x84bd3b3, 0x1d, 0x827bf40, 0xc001b04e40, 0x827c060, 0xc0027fc640, 0x0, ...)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:35 +0x109
github.com/cockroachdb/cockroach/pkg/rpc.(*heartbeatClient).Ping(0xc0003de498, 0x91db9e0, 0xc001b04f60, 0xc001b04e40, 0x0, 0x0, 0x0, 0x91db960, 0xc0003ca9c0, 0xc001c0c3a1ccb1d8)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:199 +0xcf
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func3.2(0x91db9e0, 0xc001b04f60, 0x165a0bc00, 0x91db9e0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1161 +0xb8
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x91db9e0, 0xc001b04f60, 0x847a1e0, 0xd, 0x165a0bc00, 0xc000c5ac30, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:140 +0x9e
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func3(0x91db960, 0xc0003ca9c0, 0x40d5669, 0xc000c5ae28)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1166 +0x332
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc000b5e540, 0x91db960, 0xc0003ca9c0, 0x847a1e0, 0xd, 0xc000c5ad78, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:331 +0xb2
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc00013afc0, 0xc0029119f0, 0xc00189ce10, 0xf, 0xc000ce08a0, 0x0, 0x0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1134 +0x42b
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1.1(0x91db960, 0xc0003ca9c0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1054 +0x79
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000b5e540, 0x91db960, 0xc0003ca9c0, 0x0, 0xc002911ae0)
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:352 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /Users/ssd/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0xfc
```

I believe the likely cause is https://github.com/grpc/grpc-go/pull/3958.

It isn't immediately necessary to upgrade this dependency, so there is no impact at the moment.

### PR DESCRIPTION
**Pull request by stevendanna**
This change enables future upgrades of google.golang.org/grpc.

Recent changes to google.golang.org/grpc have changed the default
proto codec such that it is incompatible with gogoproto:

https://github.com/grpc/grpc-go/pull/3958

While `proto.Marshal` does do a check for the Marshal/Unmarshal it
appears to do this through reflection methods that will panic on
fields using gogoproto.nullable.

To avoid this, we install a proto codec that does an interface check
before dispatching to proto.Marshal/proto.Unmarshal.

Note that I haven't replicated the protobuffer caching that previously
existed in google.golang.org/grpc. The referenced change claims
removing the caching may be a small performance win; however, they
also removed the typecheck that we need to do, so it is unclear.

Fixes #60531

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
I've left out a release justification as I imagine this can wait until we've cut the release branch.

**Comment by stevendanna** [comment]
@pbardea I believe you also need something like this. Perhaps now that master is reopen we can merge the codec separately from the dep updates so that those can be considered in isolation.

I believe @knz and @tbg said the codec changes looked good in #60709; however, I had to make a couple changes to account for some cases that our tests didn't seem to hit.

**Review by pbardea — APPROVED** [review]
LGTM with nits given the comments in 60709

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-:-MVvZuQS2S8AKzzUTO0B:b-cslv9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/rpc/codec.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-MVvUAiB7KV3oj9d0dw4:-MVvUAiB7KV3oj9d0dw5:b-yovwrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e74440a3435bf86933e9c839ccfdd2e293093f5/pkg/rpc/codec.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Should this be 2021? (And the test)
___
*[pkg/rpc/codec_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-MVvW1EE9l6aNL0XiVDu:-MVvW1EE9l6aNL0XiVDv:b-a4351u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e74440a3435bf86933e9c839ccfdd2e293093f5/pkg/rpc/codec_test.go#L37)):*
> ```Go
> 		{"roachpb.GetRequest", func() interface{} { return &roachpb.GetRequest{} }},
> 	} {
> 		t.Run(fmt.Sprintf("can call marshal and unmarhsal on %s", test.name), func(t *testing.T) {
> ```

nit: typo in `unmarhsal`, i also have a slight preference for test names without spaces to avoid needing to manually convert when debugging. Maybe something like `marshal-unmarshal-%s` or `TestCodedMarshalUnmarshal` and just `test.name` here? Don't feel strongly here, take it or leave it :)
___
*[pkg/testutils/lint/lint_test.go, line 1654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-MVvWixn74I7eSepx5ab:-MVvWixn74I7eSepx5ac:b-sd3nun) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e74440a3435bf86933e9c839ccfdd2e293093f5/pkg/testutils/lint/lint_test.go#L1654)):*
> ```Go
> 				// Using deprecated WireLength call.
> 				stream.GrepNot(`pkg/rpc/stats_handler.go:.*v.WireLength is deprecated: This field is never set.*`),
> 				// rpc/codec.go imports the same proto package that grpc-go imports (as of crdb@dd87d1145 and grpc-go@7b167fd6)
> ```

super-nit: `.` at end of line

**Comment by knz** [comment]
@erikgrinaker can you review this too please?

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-:-MW4u4HL3rsMCZ2w6UFx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/rpc/codec_test.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61333#-MW4tfFk08NdU8PL4J1h:-MW4tfFk08NdU8PL4J1i:bcavxun) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99f9395d3fb0f8c04f36a792a21bf9330fbcdd/pkg/rpc/codec_test.go#L40)):*
> ```
> err = testCodec.Unmarshal(marshaled, test.msgBuilder())
> 			require.NoError(t, err, "unmarshal failed")
> ```

Maybe we should check that the unmarshaled message equals the marshaled one (using `proto.Equal`) and put some contents in the messages too?

**Comment by stevendanna** [comment]
> Maybe we should check that the unmarshaled message equals the marshaled one (using proto.Equal) and put some contents in the messages too?

I've added a basic version of this but didn't add too many populated fields.  Unfortunately, most methods of comparing the Go representation of the proto are broken for cases where you might be passing in different types of protos.  For now, I've done some ugly things with reflect to make DeepEqual work for the proto's used in this test.

**Comment by erikgrinaker** [comment]
Yeah, comparing the Go structs using e.g. `DeepEqual` is a hassle because there's lots of Protobuf internals. You can just use `proto.Equal()` to compare the fields we care about and ignore the internals.

**Comment by stevendanna** [comment]
```
You can just use proto.Equal() to compare the fields we care about and ignore the internals.
```

Unfortunately, I don't think we can. Google's `proto.Equal()` does not work correctly for gogoproto generated types and Gogoproto's proto.Equal doesn't work correctly because of some bugs.

**Comment by erikgrinaker** [comment]
Groan, you're right. Thanks for going the extra mile here!

**Comment by stevendanna** [comment]
bors r=[erikgrinaker,pbardea]

**Pull request merged**
