### PR TITLE
server: dynamically increase compaction concurrency during downloads

### PR DESCRIPTION
**Pull request by dt**
Early in an online restore, a workload may not be able to utilize
all CPU due to the high latency of accessing still-remote data meaning
that many or most queries spend most of their time waiting rather than
executing. During this phase, increasing the compaciton concurrency can
expedite getting data downloaded, to reduce that latency and improve the
workload performance.

However later in the download phase, when more of the most accessed data
has been downloaded, the workload itself may be able to execute fast enough
that it requires the majority of available CPU. At this point, excessive
CPU usage by download compactions will actually negatively impact the workload
performance.

Thus it is desirable to maximize compaction concurrency when CPU is available
but reduce it when becomes scarce.

This change introduces an additional goroutine to the download call that
monitors CPU usage and adjusts compaction concurrency up and down based on
the CPU usage being below 70% or above 80% respectively.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
The API doesn't work well with `SetCompactionConcurrency`, it can error out and/or restore the incorrect value.

Should we maybe make this specific to download compactions? Like the compaction limit would be X concurrent non-download compactions + Y concurrent download compactions, and this API would just adjust Y.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116633#-:-NluB_YK9kxQaO9HLbyc:b-8a91uh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @jbowens, and @msbutler)

**Comment by dt** [comment]
>  it can error out and/or restore the incorrect value.

I thought about this a bit which is why I also added the CAS loop checking that it isn't setting it <1. 

I think I'm OK with the sorta meh interaction though, at least until pebble exposes a separate download compaction limit and then we switch this to control that. It can't reduce to below 1 -- it'll fail and log if it were to attempt that, e.g. if you'd manually reduced compaction concurrency by more than it had upped it. And if you manually upped it to some bigger number, well this will reduce that big number by the amount it had automatically upped it before. Presumably when you upped it you picked a number including the fact it was temporarily doing extra (download) compactions?🤷

Also, I think there's already an implicit assumption that `crdb_internal.set_compaction_concurrency` has external coordination around mutual exclusion, since it's undo behavior isn't CAS'ed, so it already restores to "incorrect" values.

**Comment by dt** [comment]
My inclination is to file something to separate the limits as you suggest so we come back to this later, but not let potential interactions with an _internal_ undocumented built-in hold up iterating on online restore, especially since the interactions aren't _that_ worrying?

**Comment by RaduBerinde** [comment]
Sure. One thing I would do here is to cap the number to 1 instead of causing an error to the download (e.g. is something else sets the compaction limit lower)

**Comment by dt** [comment]
> cap the number to 1 instead of causing an error to the download

done.

**Review by msbutler — APPROVED** [review]
Ideally, we could unit test the loop that adjusts compaction concurrency, but since this is a prototype, I'm ok delaying the unit test until we develop a more principled method for adjusting concurrency.

**Comment by itsbilal** [comment]
I'm good with this as a stopgap for now. However I think one better longer-term solution would be to have a separate download compactions concurrency in Pebble (it could be defined as "additional download compaction concurrency"), which can then be used by downloads only and not by other compactions. Pebble already has a `Download()` method so theoretically this change doesn't need to be in Cockroach at all.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Please file an issue to keep track of this, ideally we would have a bucket for Online Restore issues related to making the feature as robust as possible.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116633#-:-Nlx_ph1CJD_vlCdSMDu:b-hrhp6z)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @jbowens)

___
*[`pkg/storage/pebble.go` line 933 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/116633#-Nlx_llrEpoAo9-zJoAc:-Nlx_llrEpoAo9-zJoAd:b-mjr5st) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ebebaf57dfa20165b5fd9c6bf38c385db2dbfd/pkg/storage/pebble.go#L933)):*
> ```Go
> }
> 
> // AdjustCompactionConcurrency adjusts the compaction concurrency up or down by
> ```

[nit] move/copy this comment to the interface (the comment there is not very useful)

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/issues/116679

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
