### PR TITLE
build: upgrade the version check error message

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
Could we avoid this error with a little factoring like:

```
version_major_required=1
version_minor_required=11

...

if (( version_major != version_major_required )) || (( version_minor < version_minor_required )); then
  echo "go$version_major_required.$version_minor_required+ required (detected go$version)" >&2
  exit 1
fi
```

**Review by benesch — APPROVED** [review]
Whoops! Thanks.

**Comment by knz** [comment]
@couchand be my guest after this merges

**Pull request merged**
