### PR TITLE
opt: some stats code refactoring, cleanup, fixes

### PR DESCRIPTION
**Pull request by RaduBerinde**
First commit is #28737.

#### opt: misc stats code cleanup

 - embed `*opt.Metadata` in `statisticsBuilder` to avoid having to
   pass `ev.Metadata()` around;

 - rename `colStatMetadata` to `colStatLeaf`; the "metadata" part is
   confusing, as the function itself has no relation to where the
   given Statistic is coming from;

 - change `ColSet.Len() == 0` checks with `Empty()` which is more
   efficient.

Release note: None

#### opt: clean up colStat path for scans

Currently we pass the parent's relProps to colStatFromChild which is
strange to begin with, and it is only used in the case of the scan,
for `relProps.FuncDeps`. This is not really correct - we are using the
scan's FDs (which reflect constraints/limit) to calculate a stat which
gets stored in the table statistics.

This change fixes this issue by using the table FDs and cleans up the
code somewhat. colStatScan now doesn't rely on colStatFromChild but on
a separate colStatTable function.

A subsequent commit will further clean up colStatFromChild.

Release note: None

#### opt: clean up colStatFromChild

Splitting up colStatsFromChild into two variants with very different
semantics:
 - `colStatsFromChild` is used when we want the stats from a specific
   child. This version no longer needs to implement a fake child for
   scans.

 - `colStatsFromInput` is used when we want stats for selectivity
   estimation. This is only used with a few operators (Scan, Select,
   Join), and it is handled on an operator-by-operator basis. This
   will allow clean handling of LookupJoin, where the right "input" is
   the table itself and not a child of the expression (similar to the
   Scan "input").

Also simplifying `copyColStatsFromChild` to receive the `Statistics`
directly instead of `relProps`.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm_strong:, nice improvements

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-:-LK9PTECA2fzP0IAtBZ8:bvnvyvz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm: thanks for making these changes!

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-:-LKDHpIDEqZA13q2rd-t:b8b7fgx)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 417 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-LKDE2r8EtDHqdbasrpO:-LKDE2r9E36Pek5nT_vR:boc5su1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9293f49cd5cf8cfd36fc9c2a56fbcc67e712a135/pkg/sql/opt/memo/statistics_builder.go#L417)):*
> ```Go
> }
> 
> func (sb *statisticsBuilder) colStatTable(
> ```

[nit] it would be good to give this function it's own section in the file, maybe combined with `makeTableStatistics` under a "Table Statistics" header.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 212 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-LKDGIJP4gGwdv2m__Ru:-LKDGIJQ6ackhgOEi3n0:b6ahzj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7a53b7972841a57be4c1509e6e4906cbf77a188/pkg/sql/opt/memo/statistics_builder.go#L212)):*
> ```Go
> 	default:
> 		if ev.IsJoin() {
> 			// TODO(radu): what if both sides have columns in colSet?
> ```

Do you think it's worth adding a check for this case with a panic?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-:-LKEB2yX86PGDIGcPDmb:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 417 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-LKDE2r8EtDHqdbasrpO:-LKEAd0m40Ubh60XeSIq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9293f49cd5cf8cfd36fc9c2a56fbcc67e712a135/pkg/sql/opt/memo/statistics_builder.go#L417)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] it would be good to give this function it's own section in the file, maybe combined with `makeTableStatistics` under a "Table Statistics" header.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 212 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28766#-LKDGIJP4gGwdv2m__Ru:-LKEADbp4v4EGslVuj5S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7a53b7972841a57be4c1509e6e4906cbf77a188/pkg/sql/opt/memo/statistics_builder.go#L212)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you think it's worth adding a check for this case with a panic?
</blockquote></details>

Done.

**Pull request merged**
