### PR TITLE
go.mod: bump Pebble to 975fbcb07b92

### PR DESCRIPTION
**Pull request by bananabrick**
975fbcb0 *,sstable: upgrade zstd to v1.5.6
b77606f7 db: Zero out bounds for key type not present in ScanInternal
73b9c4d8 ci: add build for OpenBSD
0a26a7f4 vfs: Add support for OpenBSD
ea9e7b8a metamorphic: Batch close operation to `g.BatchClose`
876b2e76 ingest: Call Extend{Point,Range}KeyBounds in excise
d900c432 compaction: Call logUnlock on errored compactions
06034ff0 lint: add linter for raw atomic operations
c2164213 db: use atomic.Pointer for keySpanFrags
a0e702e7 objstorage: support custom object names
db69f4e6 vfs: update DiskSlowInfo Stringer implementation
f583cc14 db: use atomic.Pointer for commit queue
87b36355 db: use atomic wrappers in tests
5f909161 vfs: use atomic wrappers
b69a460a replay: use atomic wrappers
9e74e573 record: use atomic wrappers
f4efcacd randvar: use atomic.Uint64 for Uniform.max
84bb5f33 pacertoy: use atomic wrappers
bc1fc1fe manifest: use atomic.Int32 for Version.refs
c4daad91 manifest: use atomic.Int32 for leafNode.ref
6f17c1c6 errorfs: use atomic.Int32 for InjectIndex.index
e10a6b91 cache: use atomic wrappers
8460a25e arenaskl: use atomic wrappers
0ad5a7ab ackseq: use atomic.Uint64 for next
e7bbdd56 cmd/pebble: use atomic.Uint64 for ycsb.numOps
32b9c781 db: use atomic.Uint32 for keySpanCache count
613c832b db: use atomic.Int32 for readState.refcnt
71775aab db: use atomic.Int32 for flushableEntry.readerRefs
5e3de5ec db: Add IngestShared test to exercise shared ingestion
6746f411 db: support concurrency in TestIngestValidation
1a7fe39c sstable: propagate error if decompression fails
88775ba7 db: don't require holding d.mu to read format major version

Release note: None
Epic: none

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by bananabrick** [comment]
These keep failing, I'll figure it out.

**Comment by bananabrick** [comment]
Failing to build zstd:

```
[3,085 / 3,509] GoCompilePkg external/com_github_datadog_zstd/zstd.a [for tool]; 27s processwrapper-sandbox ... (15 actions, 14 running)
  ERROR: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/external/com_github_datadog_zstd/BUILD.bazel:3:11: GoCompilePkg external/com_github_datadog_zstd/zstd.a [for tool] failed: (Exit 1): builder failed: error executing command (from target @com_github_datadog_zstd//:zstd) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src ... (remaining 217 arguments skipped)
  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  /tmp/rules_go_work-2258605746/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X1_usingDTable_internal: error: undefined reference to 'HUF_decompress4X1_usingDTable_internal_fast_asm_loop'
  /tmp/rules_go_work-2258605746/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X2_usingDTable_internal: error: undefined reference to 'HUF_decompress4X2_usingDTable_internal_fast_asm_loop'
  collect2: error: ld returned 1 exit status
  compilepkg: error running subcommand /usr/bin/gcc: exit status 1
  Target //pkg/gen:code failed to build
  Use --verbose_failures to see the command lines of failed build steps.
  INFO: Elapsed time: 127.168s, Critical Path: 35.84s
  INFO: 3151 processes: 495 internal, 2656 processwrapper-sandbox.
  FAILED: Build did NOT complete successfully
  ERROR: Build failed. Not running target
  Process exited with code 1
  ```

I'm going to try and build cockroach locally to see if this is fixed.

**Comment by bananabrick** [comment]
`dev generate` is failing with the same error locally

**Comment by bananabrick** [comment]
Closing this, as we merged another vendor bump which includes the changes here, and we've reverted the zstd dependency.

**Pull request closed without merging**
