### PR TITLE
cli: add `debug compact`

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7553)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/engine.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-KLWccd_vf6o-OrVH8Fq:-KLWccd_vf6o-OrVH8Fr:701148634) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c02ceb5d06a13653da7fa75d94c379333dc335/storage/engine/engine.go#L169)):*
> ```Go
> 	// Capacity returns capacity details for the engine's available storage.
> 	Capacity() (roachpb.StoreCapacity, error)
> 	// Compact compacts all of the sstables.
> ```

I think I'd prefer to omit this from the interface - it's pretty specific to the implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-:-KLWcuaT9-NN_6kkEL8H:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/engine.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-KLWccd_vf6o-OrVH8Fq:-KLWdxBlR21fu_a9SkE9:886311716) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c02ceb5d06a13653da7fa75d94c379333dc335/storage/engine/engine.go#L169)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think I'd prefer to omit this from the interface - it's pretty specific to the implementation.
</details>
And type assert that the engine is a `*RocksDB`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/engine.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-KLWccd_vf6o-OrVH8Fq:-KLWgwqwjWsLbba9Rmbm:160394143) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c02ceb5d06a13653da7fa75d94c379333dc335/storage/engine/engine.go#L169)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> And type assert that the engine is a `*RocksDB`?
</details>
Yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/engine/engine.go, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-KLWccd_vf6o-OrVH8Fq:-KLWio4uxIR8xZ_cwGEu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c02ceb5d06a13653da7fa75d94c379333dc335/storage/engine/engine.go#L169)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yep
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553)*

**Comment by petermattis** [comment]
Uh, what's with the `license/cla` check not completing?

**Comment by tamird** [comment]
I pinged it for you.

**Comment by petermattis** [comment]
Thanks, @tamird. How did you do that?

**Comment by tamird** [comment]
Here's an illustrated guide:

step1

then scroll down a bit...

step2

**Comment by petermattis** [comment]
Nifty graphics. Thanks.

**Comment by tschottdorf** [comment]
Wow, such graphics. Wow.

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7553#-:-KLXEMBDeZ-65IIikq3h:-1084798345)*

**Pull request merged**
