### PR TITLE
roachprod: never start cockroach processes concurrently

### LINKED ISSUE #113384: roachtestutil/mixedversion: inconsistent node IDs
The test in #113222, using the `mixedversion` framework, has inconsistent node IDs. This is confusing to debug, and also breaks assertions that rely on the `node` attribute matching the node ID (typically used for zone configs).

In the cluster I'm currently looking at, nodes are running with these command line arguments:

```
erik     26259 13.4  0.6 2471300 454604 pts/0  Sl   09:06   3:28 /home/erik/local/3/v22.2.13/cockroach start --certs-dir /home/erik/local/3/certs --log file-defaults: {dir: '/home/erik/local/3/logs', exit-on-error: false} --listen-addr=:29000 --http-addr=:29001 --join=127.0.0.1:29004 --store path=/home/erik/local/3/data,attrs=store1:node3:node3store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/3/logs/cockroach.pid
erik     26260 11.7  0.6 1971700 415572 pts/0  Sl   09:06   3:02 /home/erik/local/1/v22.2.13/cockroach start --certs-dir /home/erik/local/1/certs --log file-defaults: {dir: '/home/erik/local/1/logs', exit-on-error: false} --listen-addr=:29004 --http-addr=:29005 --join=127.0.0.1:29004 --store path=/home/erik/local/1/data,attrs=store1:node1:node1store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/1/logs/cockroach.pid
erik     26276 11.3  0.6 2592180 448480 pts/0  Sl   09:06   2:55 /home/erik/local/4/v22.2.13/cockroach start --certs-dir /home/erik/local/4/certs --log file-defaults: {dir: '/home/erik/local/4/logs', exit-on-error: false} --listen-addr=:29006 --http-addr=:29007 --join=127.0.0.1:29004 --store path=/home/erik/local/4/data,attrs=store1:node4:node4store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/4/logs/cockroach.pid
erik     27056 10.3  0.7 1954836 488868 pts/0  Sl   09:07   2:38 /home/erik/local/2/v23.1.1/cockroach start --certs-dir /home/erik/local/2/certs --log file-defaults: {dir: '/home/erik/local/2/logs', exit-on-error: false} --listen-addr=:29002 --http-addr=:29003 --join=127.0.0.1:29004 --store path=/home/erik/local/2/data,attrs=store1:node2:node2store1 --cache=25% --locality=cloud=local,region=local,zone=local --max-sql-memory=25% --pid-file /home/erik/local/2/logs/cockroach.pid
```

From the DB console, I can map port numbers to node IDs:

* n1: port 29004
* n2: port 29000
* n3: port 29002
* n4: port 29006

Cross-referencing with the command-line args, we find two issues:

1. Node attributes and `~/local/<nodeid>` directories do not correspond with the actual node IDs -- e.g. the real n3 is located in `~/local/2` and has node attribute `node2`.

2. All nodes have attribute `store1`, even though the actual store IDs correspond with the real node ID.

I think this happens because the framework explicitly sets `Sequential: false`, which means all nodes will join the cluster concurrently and race for node ID allocation. The `store1` attribute may be a separate bug.

https://github.com/cockroachdb/cockroach/blob/df141ea4b984effa91f39b115443ec74ddc1aa3a/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L715

Jira issue: CRDB-32918

### PR DESCRIPTION
**Pull request by renatolabs**
This changes startup logic to always start cockroach processes sequentially: this ensures that node IDs match hostnames. Previously, we were starting nodes concurrently for upgrade tests because initialization tasks performed by roachprod required quorum.

Fixes: #113384.

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
I verified that node IDs now consistently match hostnames with this patch, including in upgrade tests. Also ran upgrade tests on this branch to validate that they pass, since those were the main tests that explicitly set `RoachprodOpts.Sequential = false` before:

https://teamcity.cockroachdb.com/viewLog.html?buildId=12494442&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

Ready for review.

@erikgrinaker could also do a sanity check that this fixes what you reported in #113384?

**Comment by erikgrinaker** [comment]
>@erikgrinaker could you sanity check that this fixes what you reported in https://github.com/cockroachdb/cockroach/issues/113384?

Sure, will do some runs after dinner. Thanks!

**Comment by erikgrinaker** [comment]
Confirming that #113222 passed 20/20 runs with this change.

I did see nodes occasionally fail to initialize after restarting, but the error was swallowed after 20 retries. I did not investigate this, since the clusters were nuked. For example:

```
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:11 runner.go:382: ---------- STARTING (6): restart node 2 with binary version v22.2.6 ----------
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:11 runner.go:396: binary versions: [1: 22.1, 2: 22.1, 3: 22.1, 4: 22.1]
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:11 runner.go:397: cluster versions: [1: 22.1, 2: 22.1, 3: 22.1, 4: 22.1]
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:11 clusterupgrade.go:254: restarting node 2 into version v22.2.6
19:56:11 cluster.go:674: test status: stopping nodes :2
local: stopping and waiting
19:56:14 cluster.go:674: test status: stopping nodes :2
local: stopping
19:56:14 cluster.go:2205: running cmd `test -e v22.2.6/cockroach |...` on nodes [:2]; details in run_195614.787626829_n2_test-e-v2226cockroac.log
19:56:14 cluster.go:674: test status: staging binary
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:14 staging.go:358: Resolved release url for cockroach version v22.2.6: https://storage.googleapis.com/cockroach-release-artifacts-prod/cockroach-v22.2.6.linux-amd64.tgz
19:56:15 monitor.go:177: Monitor event: n2: cockroach process for system interface died (exit code unknown): expected
19:56:18 cluster.go:674: test status: 
19:56:18 cluster.go:674: test status: starting nodes :2
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:19 cockroach.go:380: local: starting nodes
local: executing sql
local: executing sql
19:56:20 monitor.go:177: Monitor event: n2: cockroach process for system interface is running (PID: 22341)
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:52 cockroach.go:1078: not creating default admin user due to error: COMMAND_PROBLEM: exit status 127
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:52 cockroach.go:1093: local: setting cluster settings
[mixed-version-test/6_restart-node-2-with-binary-version-v22.2.6] 19:56:56 runner.go:382: ---------- FINISHED [44.467561885s] (6): restart node 2 with binary version v22.2.6 ----------
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:56:56 runner.go:382: ---------- STARTING (7): restart node 4 with binary version v22.2.6 ----------
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:56:56 runner.go:396: binary versions: [1: 22.1, 2: 22.2, 3: 22.1, 4: 22.1]
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:56:56 runner.go:397: cluster versions: [1: 22.1, 2: 22.1, 3: 22.1, 4: 22.1]
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:56:56 clusterupgrade.go:254: restarting node 4 into version v22.2.6
19:56:56 cluster.go:674: test status: stopping nodes :4
local: stopping and waiting
19:57:01 monitor.go:177: Monitor event: n4: cockroach process for system interface died (exit code unknown): expected
19:57:01 cluster.go:674: test status: stopping nodes :4
local: stopping
19:57:01 cluster.go:2205: running cmd `test -e v22.2.6/cockroach |...` on nodes [:4]; details in run_195701.303442393_n4_test-e-v2226cockroac.log
19:57:01 cluster.go:674: test status: staging binary
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:57:01 staging.go:358: Resolved release url for cockroach version v22.2.6: https://storage.googleapis.com/cockroach-release-artifacts-prod/cockroach-v22.2.6.linux-amd64.tgz
19:57:05 cluster.go:674: test status: 
19:57:05 cluster.go:674: test status: starting nodes :4
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:57:05 cockroach.go:380: local: starting nodes
local: executing sql
local: executing sql
local: executing sql
19:57:07 monitor.go:177: Monitor event: n4: cockroach process for system interface is running (PID: 23314)
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
local: executing sql
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:57:37 cockroach.go:1078: not creating default admin user due to error: COMMAND_PROBLEM: exit status 127
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:57:37 cockroach.go:1093: local: setting cluster settings
[mixed-version-test/7_restart-node-4-with-binary-version-v22.2.6] 19:57:41 runner.go:382: ---------- FINISHED [45.83830969s] (7): restart node 4 with binary version v22.2.6 ----------
```

**Comment by renatolabs** [comment]
Thanks for checking!

> I did see nodes occasionally fail to initialize after restarting, but the error was swallowed after 20 retries

Good catch; this happens when the ordering of events is such that n1 (init node) does not have the binary being used to start another node. The issue was not introduced in this PR, but I added a commit here to skip initialization when restarting nodes.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113718#-:-NiesGzMDrxqt6iOFwCc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by renatolabs** [comment]
TFTR!

bors r=RaduBerinde

**Pull request merged**
