### PR TITLE
storage: debug page for RocksDB tickers/histograms

### PR DESCRIPTION
**Pull request by ajkr**
Set up a debug page at "/_status/enginestats/<node_id>" that contains
values of all RocksDB ticker stats and histograms. It is also included
in debug zip.

A portion of the debug page (including both tickers and histograms)
looks like this:

tickershistograms

The debug zip file contains a JSON file named "debug/nodes/<node_id>/enginestats" with all the tickers/histograms, and looks like this:

```
{
  "stats": [
    {
      "storeId": 1,
      "tickersAndHistograms": {
        "tickers": {
          "rocksdb.blobdb.blob.file.bytes.read": "0",
...
          "rocksdb.write.wal": "296"
        },
        "histograms": {
          "rocksdb.blobdb.blob.file.read.micros": {
            "mean": 0,
            "p50": 0,
            "p95": 0,
            "p99": 0,
            "max": 0,
            "count": "0",
            "sum": "0"
          },
...
          "rocksdb.write.raw.block.micros": {
            "mean": 1.8235294117647058,
            "p50": 0.6071428571428571,
            "p95": 10.749999999999993,
            "p99": 12,
            "max": 12,
            "count": "17",
            "sum": "31"
          }
        }
      }
    }
  ]
}
```

Release Note: None

### CODE REVIEW

**Comment by tbg** [comment]
Hmm, 170 lines is hefty. You mention that we're collecting them already anyways (see snippets below), so what do we win by printing them in the logs? Just easier debuggability in situations in which we can't look at the time series? It seems hard to make good use of them since they're all counters and so you end up manually diffing them. For perf work I doubt we're ever going to want to just look at the time series, which also give you 10s granularity while here we have 60s only.
I'm sorry I'm only bringing all this up now. I somehow assumed (for no good reason) that the stats dump would somehow be more compact and less metrics-y.

https://github.com/cockroachdb/cockroach/blob/d8eb94c82e0f9446ef43e2bd4f8e72055fbdefe2/pkg/storage/metrics.go#L1418-L1432

What are examples of some situations in which this dump would be useful? Can we make the timeseries useful instead? For example, which of the stats should we add to the snippet above? How should we expose the timeseries? For example, we have `cockroach debug dumpts` that dumps the time series contained in a cluster. That command is too bare bones right now to use it, for example here's the output

https://gist.github.com/tbg/006a2cfde07ddbfc9c96f10e5b3d4f33

(I think this means that the snippet is `cr.store.totalbytes` from `store 1` and it contains three datapoints 10s apart over a 30s interval)

but it's already more pleasant than trying to piece together multiple stats dumps from the logs. Do you think that can work instead? We need to include that info in the debug zip (not all of the ts, that's too much, but some recent interval).

**Comment by ajkr** [comment]
> You mention that we're collecting them already anyways (see snippets below), so what do we win by printing them in the logs? Just easier debuggability in situations in which we can't look at the time series?

Sorry "we're collecting" was the wrong word choice. What I meant is RocksDB is collecting them internally. Besides the handful of stats in the snippet you showed, the stats RocksDB is collecting don't appear to be exposed in Cockroach in any form.

> It seems hard to make good use of them since they're all counters and so you end up manually diffing them. For perf work I doubt we're ever going to want to just look at the time series, which also give you 10s granularity while here we have 60s only.

I don't know. I find non-granular stats useful sometimes. For example you can compare `rocksdb.bloom.filter.prefix.checked` and `rocksdb.bloom.filter.prefix.useful` to answer whether your prefix bloom filters are effective. Or compare `rocksdb.number.iter.skip` and `rocksdb.number.db.next.found` to answer whether iterators are hitting lots of tombstones. Or compare `rocksdb.block.cache.miss` and `rocksdb.block.cache.hit` to answer whether the memory we're allocating to block cache is worthwhile.

> What are examples of some situations in which this dump would be useful? Can we make the timeseries useful instead? For example, which of the stats should we add to the snippet above?

It is useful for cases where we didn't predict a stat would be useful so don't have it in the timeseries. Or maybe we upgrade RocksDB and don't notice a new stat. If we can think of a way to include everything in timeseries, that'd be preferable to me.

> How should we expose the timeseries? For example, we have cockroach debug dumpts that dumps the time series contained in a cluster.

This is fine for me. I think the only question I have is whether you agree with preemptively exposing all stats as timeseries, or prefer to cherry-pick the ones we think are relevant?

**Comment by tbg** [comment]
> For example you can compare rocksdb.bloom.filter.prefix.checked and rocksdb.bloom.filter.prefix.useful to answer whether your prefix bloom filters are effective. Or compare rocksdb.number.iter.skip and rocksdb.number.db.next.found to answer whether iterators are hitting lots of tombstones. Or compare rocksdb.block.cache.miss and rocksdb.block.cache.hit to answer whether the memory we're allocating to block cache is worthwhile.

That's a good point.

I talked to @bdarnell and we agreed that we can't add them wholesale to either timeseries or the logs, it's just too much (we have <600 time series in total right now, so we don't want to add 170 at once).
My preference would thus be cherry-picking the timeseries you think are most relevant. We can expose the whole list via a debug page on top of that to give access to everything when desired. It won't be available historically, but we can at least include it in a debug zip. How many of the stats do you think are "relevant" enough for timeseries?

Regarding missing a newly added metric, if you worry about that the thing to do - I think - is a unit test that basically extracts all the stats names from your dump string and fails whenever the list changes. I'll let you decide whether that is worth doing, I suspect not.

**Comment by ajkr** [comment]
> We can expose the whole list via a debug page on top of that to give access to everything when desired. It won't be available historically, but we can at least include it in a debug zip.

This is actually the main thing I'm interested in. Adding a few stats to timeseries is nice too but only works if we know in advance what we're looking for. For example, when I found the data synthesized by our workload tool is uncompressible that was due to noticing the stat "rocksdb.bytes.compressed" is always zero. It's not a very good example, but maybe we'd notice interesting engine-related issues in production too if we examine stats that we don't decide months in advance that we need.

**Comment by ajkr** [comment]
The *.pb.go files show huge changes on GitHub but do not show any changes on my local machine. I am not sure what causes this.

**Review by tbg — COMMENTED** [review]
Looks good, thanks for banging this out so quickly! Only a few minor comments and you should write a test that calls the stats endpoint. I think an analogue of https://github.com/cockroachdb/cockroach/blob/0750a437039399ae87086b9fe6cded0dc5d7c5ce/pkg/server/status_test.go#L133-L156 is enough, so it shouldn't be much work.

For what's exposed as time series, do you know of any that should be added? It is helpful to have historical information for some key metrics and I'm curious what you think about the ones we have so far.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-:-Lb2UBTADzQP-2XjbMiw:b-u790tb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr)

___
*[c-deps/libroach/engine.cc, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-Lb2R5M_E4nUxuYW9NTl:-Lb2R5M_E4nUxuYW9NTm:bbeo6k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d266d6fab00fd322ee6b2f4ceaa6b09d7e1d5ded/c-deps/libroach/engine.cc#L224)):*
> ```cpp
> // `GetTickersAndHistograms` retrieves maps of all RocksDB tickers and histograms.
> // It differs from `GetStats` by getting _every_ ticker and histogram, and by not
> // getting anything else (DB properties, for example).
> ```

Mention that the caller needs to free `stats.{tickers,histograms}`.
___
*[pkg/server/serverpb/status.proto, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-Lb2RXgB0m3bQzq4WtWF:-Lb2RXgB0m3bQzq4WtWG:b-uiryyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d266d6fab00fd322ee6b2f4ceaa6b09d7e1d5ded/pkg/server/serverpb/status.proto#L231)):*
> ```protobuf
> }
> 
> message EngineStatsResponse {
> ```

This should also contain the `StoreID`, otherwise with multiple stores you won't know which stats belong to which store.
___
*[pkg/storage/engine/rocksdb.go, line 1195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-Lb2S8mZ7jUSXpyNP2mx:-Lb2S8mZ7jUSXpyNP2my:b-gz3brp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d266d6fab00fd322ee6b2f4ceaa6b09d7e1d5ded/pkg/storage/engine/rocksdb.go#L1195)):*
> ```Go
> 	}
> 
> 	tickers := (*[1 << 20]C.TickerInfo)(
> ```

For consistency, use the same constant value instead of `1 << 20` from here

https://github.com/cockroachdb/cockroach/blob/2558dccbcda09c0eae28f816a05adb8620155175/pkg/storage/engine/slice.go#L34

(I know we don't ever expect to see `1 << 20 < tickers_len`, but still.
___
*[pkg/storage/engine/rocksdb.go, line 1206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-Lb2T0hF458TcBdUI2Uw:-Lb2T0hF458TcBdUI2Ux:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d266d6fab00fd322ee6b2f4ceaa6b09d7e1d5ded/pkg/storage/engine/rocksdb.go#L1206)):*
> ```Go
> 
> 	res.Histograms = make(map[string]*enginepb.HistogramData)
> 	histograms := (*[1 << 20]C.HistogramInfo)(
> ```

ditto
___
*[pkg/storage/engine/rocksdb.go, line 1219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-Lb2TB-h9NogzXM7MEyL:-Lb2TB-h9NogzXM7MEyM:bh5z5ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/d266d6fab00fd322ee6b2f4ceaa6b09d7e1d5ded/pkg/storage/engine/rocksdb.go#L1219)):*
> ```Go
> 			Sum: uint64(histogram.sum),
> 		}
> 		res.Histograms[name] = value
> ```

My preference would be to have Histograms a `map[string]HistogramData` and not `map[string]*HistogramData`. You should be able to make this happen in the `.proto` file by using the option as here:

https://github.com/cockroachdb/cockroach/blob/2bc10e743f9fbbc4c280f2a0d112bb9394c9a68f/pkg/server/diagnosticspb/diagnostics.proto#L32

**Review by tbg — COMMENTED** [review]
PS I don't know about the diffs. You've definitely done the right thing (i.e. the files needed to change) and they're also supposed to be checked in. Locally `git` suppresses these diffs (treats it as  binary files, we've set things up that way), so maybe you just didn't notice them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-:-Lb2XpOd6fEwap5AeOy1:b-hoy9m1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr)

**Comment by ajkr** [comment]
Hm the tests use `engine.InMem`, while this is only supported for `engine.RocksDB`.

**Comment by tbg** [comment]
I think you just need to feed it a config that has a `StoreSpec` with a real dir in it:

https://github.com/cockroachdb/cockroach/blob/352bdf4630d5e16b6200237acaaaca22f7470511/pkg/base/test_server_args.go#L66

You can get a dir with `testutils.TempDir()`

**Comment by tbg** [comment]
Here's an example

https://github.com/cockroachdb/cockroach/blob/8938dcb76bc601204b59fadf49b1206df5ed1596/pkg/server/server_test.go#L540-L548

**Comment by ajkr** [comment]
That was fast, thanks!

**Comment by ajkr** [comment]
Thanks a lot for the fast and detailed review. Addressed all your comments, I believe.

> For what's exposed as time series, do you know of any that should be added? It is helpful to have historical information for some key metrics and I'm curious what you think about the ones we have so far.

OK, I went through them and picked a few that might be worth adding. Will do that in a separate PR, somewhat later.

- "rocksdb.number.superversion_acquires", "rocksdb.number.superversion_releases", and "rocksdb.number.superversion_cleanups" - can be useful for debugging high memory/space usage. superversions pin memtables and ssts so holding them too long can cause problems.
- "rocksdb.num.iterator.created" and "rocksdb.num.iterator.deleted" - after identifying old superversions are a problem, these can be useful to check whether those superversions are pinned by old iterators.
- "rocksdb.number.iter.skip", "rocksdb.number.db.seek.found", "rocksdb.number.db.next.found", and "rocksdb.number.db.prev.found" - can be useful for debugging slow reads. Skips will be relatively high when there are lots of tombstones.
- "rocksdb.no.file.opens" and "rocksdb.no.file.closes" - can be useful for debugging slow reads. Opening files in the read path is slower than getting them from table cache.
- "rocksdb.stall.micros"

**Review by tbg — APPROVED** [review]
:lgtm: and thanks!

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36196#-:-LbOvlgtDcBKTMu2oOzf:bc6pnq8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

**Comment by tbg** [comment]
CI failed on https://github.com/cockroachdb/cockroach/issues/36369

bors r+

**Comment by ajkr** [comment]
@tbg What do you think about backporting this to 19.1? Having the RocksDB stats in debug zip might be useful.

**Comment by tbg** [comment]
Absolutely, please backport this.

**Pull request merged**
