### PR TITLE
client: remove Txn.retrying

### LINKED ISSUE #5531: kv: Txn.retrying can get out of phase because of SQL-level retries
Hey Jingguo, I think there's a problem with the retrying tracking you've introduced in #5396.
We unconditionally set `retrying = false` here:
https://github.com/cockroachdb/cockroach/blob/62ed93d/client/txn.go#L499

But the transaction does not necessarily stop retrying when this `Exec()` function returns. Notice that we break out of the `RetryLoop` if `opt.AutoRetry` is not set. That is because SQL wants to control the retries for its transactions (see `sql/executor.go`). So if SQL decides to retry, I think this `txn.retrying` field will have the wrong value (`false`) the next time `Exec()` is called.
Does this sound right?

This is the kind of reason why I was thinking that all retry-related state should be kept at the sql level (`txnState`). I should have properly reviewed the code in your PR, sorry about that.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #5531.

Also snuck in some refactoring, since this code was quite hard to read.

Closes #5618.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7446)

### CODE REVIEW

**Comment by andreimatei** [comment]
What I was suggesting in https://github.com/cockroachdb/cockroach/pull/5618 was getting rid of `txn.retrying` entirely and keeping all txn state in sql.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-:-KKzPbSbZIG0lvFLwXPN:2047662164)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/txn.go, line 566 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-KKzRZCCWQ4M6sT4JtGk:-KKzRZCCWQ4M6sT4JtGl:-1576743729) ([raw file](https://github.com/cockroachdb/cockroach/blob/a982deda09b06b909ced43efbd8b0d5387692bf4/client/txn.go#L566)):*
> ```Go
> 
> 		if !opt.AutoRetry {
> 			break
> ```

if `err` is retryable, SQL might still retry (or it might also not, as far as this code is concerned. Although right now it always will).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446)*

**Comment by tamird** [comment]
Understood, but why is that better? AFAICT the only use of `retrying` is to prohibit modifying the transaction while it's in flight.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/txn.go, line 566 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-KKzRZCCWQ4M6sT4JtGk:-KKz_brl4j_6QsoISR_s:-12775084) ([raw file](https://github.com/cockroachdb/cockroach/blob/a982deda09b06b909ced43efbd8b0d5387692bf4/client/txn.go#L566)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> if `err` is retryable, SQL might still retry (or it might also not, as far as this code is concerned. Although right now it always will).
</details>
Not sure what you're saying here - can you help me understand the consequences?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-:-KKz_nOVUaJF-E-4VAVi:1442505086)*

**Comment by tamird** [comment]
@andreimatei PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-:-KKzhvVkA2fggYKH25PI:-1652012919)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/session.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-KL2SWJwc88oOfsxh8bw:-KL2SWJwc88oOfsxh8bx:735644428) ([raw file](https://github.com/cockroachdb/cockroach/blob/14f217a33023d16d11314cecbe0f2b01583a53e4/sql/session.go#L125)):*
> ```Go
> 
> 	// false at first, true since the moment when a transaction is retried.
> 	// TODO(andrei): this duplicates the retrying field in client.Txn, but the
> ```

remove the TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-:-KL2Uk2NtLDwbAjuO2om:1417088721)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/session.go, line 125 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-KL2SWJwc88oOfsxh8bw:-KLH8ga_06fqfNLhg7MM:927315454) ([raw file](https://github.com/cockroachdb/cockroach/blob/14f217a33023d16d11314cecbe0f2b01583a53e4/sql/session.go#L125)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> remove the TODO
</details>
Updated this and some other comments; could you take another look?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7446#-:-KLHGVpLd09rfywZnUDr:1417088721)*

**Pull request merged**
