### PR TITLE
opt: add basic testcatalog support for expression-based indexes

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:LGTM:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-:-MJcNf34EU4tnmUV2pqJ:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJcK6NnDb6T2XrcaoeX:-MJcK6NnDb6T2XrcaoeY:bavye0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/81b503c20317916970aa7c1b6dcaf647c691caf2/pkg/sql/opt/testutils/testcat/create_table.go#L675)):*
> ```Go
> func (ti *Index) addColumn(tt *Table, elem tree.IndexElem, colType colType) *cat.Column {
> 	if elem.Expr != nil {
> 		if ti.Inverted && len(ti.Columns) == 0 {
> ```

The `len(ti.Columns) == 0` check is in anticipation of supporting multi-col inverted indexes with expressions for the non-inverted indexed columns?

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-:-MJgIU5LAWqnjgGyhS5z:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/testutils/testcat/table_expr.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJgHCcJ-nJ0NZgdRn4D:-MJgHCcJ-nJ0NZgdRn4E:bcr62ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/81b503c20317916970aa7c1b6dcaf647c691caf2/pkg/sql/opt/testutils/testcat/table_expr.go#L24)):*
> ```Go
> // typeCheckTableExpr takes an expression that refers to table columns by name
> // and returns its resulting type.
> func typeCheckTableExpr(e tree.Expr, cols []cat.Column) *types.T {
> ```

[nit] This code is pretty simple and contained, but it feels like something we've done over and over. Is there no way to reuse the `ScalarBuilder` or something like that? (Not sure if that's better, just wondering if you considered it)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJcK6NnDb6T2XrcaoeX:-MJh8PqhA0fLMIVb6tui:b-4k8uiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/81b503c20317916970aa7c1b6dcaf647c691caf2/pkg/sql/opt/testutils/testcat/create_table.go#L675)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The `len(ti.Columns) == 0` check is in anticipation of supporting multi-col inverted indexes with expressions for the non-inverted indexed columns?
</blockquote></details>

It's just replicating the existing `if`. I think both would need to be updated (they assume the inverted column is first).
___
*[pkg/sql/opt/testutils/testcat/table_expr.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJgHCcJ-nJ0NZgdRn4D:-MJh8adP48hMH4BOsI7U:br1re8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/81b503c20317916970aa7c1b6dcaf647c691caf2/pkg/sql/opt/testutils/testcat/table_expr.go#L24)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] This code is pretty simple and contained, but it feels like something we've done over and over. Is there no way to reuse the `ScalarBuilder` or something like that? (Not sure if that's better, just wondering if you considered it)
</blockquote></details>

It does feel silly to go through all this dance. I don't think I can use the ScalarBuilder from the test catalog. I couldn't find something I could easily reuse. I think what we are really missing is that we should be able to TypeCheck the original expression directly by setting up a column resolver in the SemaContext, instead of having to rewrite it.

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/testutils/testcat/table_expr.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJgHCcJ-nJ0NZgdRn4D:-MJhPoUT4Wnx-XOqyyDM:b-mdpej) ([raw file](https://github.com/cockroachdb/cockroach/blob/81b503c20317916970aa7c1b6dcaf647c691caf2/pkg/sql/opt/testutils/testcat/table_expr.go#L24)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It does feel silly to go through all this dance. I don't think I can use the ScalarBuilder from the test catalog. I couldn't find something I could easily reuse. I think what we are really missing is that we should be able to TypeCheck the original expression directly by setting up a column resolver in the SemaContext, instead of having to rewrite it.
</blockquote></details>

Yea, I guess we can keep in mind for the future if there's a way to build something more reusable like that

**Review by RaduBerinde — COMMENTED** [review]
TFTRs! Rebased and resolved conflicts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-:-MJjHUbc4L8APmy5NXqa:b-nx8igh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-:-MJmUh-R2fDhES7P8pgz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmU_xQ-gns9Zo7JYw2:-MJmU_xQ-gns9Zo7JYw3:ba8guhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/47044feed11ec0c0390989bf8f44e777ec3eb00d/pkg/sql/opt/testutils/testcat/create_table.go#L512)):*
> ```Go
> 			}
> 
> 			idx.invertedOrd = i
> ```

Looks like the tests are failing because this has been removed.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmTGLx79LiExhMo6bT:-MJmTGLx79LiExhMo6bU:bd7x1mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce0e247b47aa05b1f5430c9977d3dfa1bfa9a316/pkg/sql/opt/testutils/testcat/create_table.go#L760)):*
> ```Go
> 	if colType == keyCol || colType == strictKeyCol {
> 		typ := col.DatumType()
> 		if col.Kind() != cat.VirtualInverted {
> ```

[nit] it might be clearer to put the positive case in the first branch of the `if`, `if col.Kind() == cat.VirtualInverted`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmU_xQ-gns9Zo7JYw2:-MJmZ_wb21k8eaF4u8NI:bnoqk7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/47044feed11ec0c0390989bf8f44e777ec3eb00d/pkg/sql/opt/testutils/testcat/create_table.go#L512)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks like the tests are failing because this has been removed.
</blockquote></details>

Fixed, thanks!!
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmTGLx79LiExhMo6bT:-MJmZB0QC6QJPSCgAgrF:bpqkiam) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce0e247b47aa05b1f5430c9977d3dfa1bfa9a316/pkg/sql/opt/testutils/testcat/create_table.go#L760)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] it might be clearer to put the positive case in the first branch of the `if`, `if col.Kind() == cat.VirtualInverted`.
</blockquote></details>

Done (though there's something to be said for putting the common case first).

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmTGLx79LiExhMo6bT:-MJmdgvm4iOvnatgOCiJ:b-cxxpe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce0e247b47aa05b1f5430c9977d3dfa1bfa9a316/pkg/sql/opt/testutils/testcat/create_table.go#L760)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done (though there's something to be said for putting the common case first).
</blockquote></details>

Good point. I'm totally fine with you switching it back!

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-:-MJmfSbz4QyalHZxqNNT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 696 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmf9Mg2q1uImxbtLW0:-MJmf9Mh19uN2W3aQy2j:b-at385t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ebd8de7e7239c90af441c570199996c60017e7/pkg/sql/opt/testutils/testcat/create_table.go#L696)):*
> ```Go
> 	ordinal := tt.FindOrdinal(string(elem.Column))
> 	if ti.Inverted && isLastIndexCol {
> 		// First column of an inverted index is special: the index key does not
> ```

[nit] First -> Last

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 696 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55553#-MJmf9Mg2q1uImxbtLW0:-MJmfoLc8QfzjSfWZruo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1ebd8de7e7239c90af441c570199996c60017e7/pkg/sql/opt/testutils/testcat/create_table.go#L696)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] First -> Last
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55553)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde)

**Pull request merged**
