### PR TITLE
tests: reduce block cache size for kv0/enc=false/nodes=1/size=64kb/co…

### LINKED ISSUE #130223: roachtest: kv0/enc=false/nodes=1/size=64kb/conc=4096 failed
roachtest.kv0/enc=false/nodes=1/size=64kb/conc=4096 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16774846?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16774846?buildTab=artifacts#/kv0/enc=false/nodes=1/size=64kb/conc=4096) on release-24.2 @ [5a2c21418d19689abdb621a5b05d1b1a548ab714](https://github.com/cockroachdb/cockroach/commits/5a2c21418d19689abdb621a5b05d1b1a548ab714):

```
(cluster.go:2413).Run: context canceled
(monitor.go:154).Wait: monitor failure: monitor user task failed: t.Fatal() was called
unexpected node event: n1: cockroach process for system interface died (exit code 15)
test artifacts and logs in: /artifacts/kv0/enc=false/nodes=1/size=64kb/conc=4096/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=8</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv0/enc=false/nodes=1/size=64kb/conc=4096.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

### PR DESCRIPTION
**Pull request by sumeerbhola**
…nc=4096

This is done since the jemalloc faster release setting was insufficient in one case to prevent an OOM.

Fixes #130223

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
This change reduces the Pebble block cache from 7.5GB to 6GB, when run on roachprod.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133491#-:-OA4UtOb-RDo8LkQOWs_:b7xiub)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @itsbilal, and @vidit-bhat)

**Review by itsbilal — APPROVED** [review]
LGTM, nice catch!

**Comment by sumeerbhola** [comment]
> LGTM, nice catch!

It was your catch in https://github.com/cockroachdb/cockroach/issues/130223#issuecomment-2378007213 :)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=itsbilal

**Pull request merged**
