### PR TITLE
Process schema changes through mutations

### PR DESCRIPTION
**Pull request by vivekmenezes**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3136)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Just curious, what's the benefit of opening a PR when the cuffs isn't ready
for review yet?

**Comment by vivekmenezes** [comment]
i like to see the pr on the web. if i could do that privately id appreciate
it.

Vivek

**Comment by vivekmenezes** [comment]
This PR is ready for review. The first commit is part of another PR and can be ignored.

**Comment by tschottdorf** [comment]
Especially with nontrivial changes like this, descriptive commit messages are really helpful. Just beginning to review the code I'm finding myself struggling to even figure out what your end goal is. Consider explaining briefly what the purpose of the changes is.

**Comment by vivekmenezes** [comment]
That's a very good point. I've added a comment to the commit explaining the change.

**Comment by tamird** [comment]
Needs a rebase.

**Comment by vivekmenezes** [comment]
Rebase done. There is another refactoring PR that it is rebased against.

---

Review status: 0 of 15 files reviewed at latest revision, 20 unresolved discussions, some commit checks pending.

---

_[sql/alter_table.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MKk9c8tm0drWOGrRT:-K3Q5hD4UFJ-k9M7hXj4:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L28)):_
done

---

_[sql/alter_table.go, line 82 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MK7YpfevCpxZ3fT1d:-K3Q5uzolCipILIq2ZfG:-1235638271) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L82)):_
Didn't quite follow your question.

---

_[sql/alter_table.go, line 134 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MKS5QKOh8lygO7S0x:-K3Qwe-hh1FmrXVmWm2v:-1019697337) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L134)):_
changed to a switch

---

_[sql/alter_table.go, line 152 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MKOU8PBvWrB_0jdQJ:-K3Q6abFXKYBsLnQzIE8:-517267220) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L152)):_
changed to a switch to make it more readable

---

_[sql/alter_table.go, line 163 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MKtGysSkc_XwGwbg_:-K3Q6l2RVYggrCS_5i1C:-93282591) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L163)):_
ALTER TABLE DROP b, DROP c 
drops two columns which might already be in the process of being dropped.

I've added a comment about why this is needed only for the unittests.

---

_[sql/alter_table.go, line 175 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MK_NY-epKNw6gQIDE:-K3Q8kmbBts9cpG4edp8:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L175)):_
done

---

_[sql/create.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MOQ3De04KH_ef-eJR:-K3Q8xJE4uEzBX27i6Y7:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/create.go#L91)):_
done

---

_[sql/delete.go, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MBe74xoBkWF3SzApL:-K3QAQbxx5m0EClq43jF:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/delete.go#L77)):_
done

---

_[sql/descriptor_mutation_test.go, line 329 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MGEMYNkLBguM-LeCN:-K3QBItYc1hZH7h6MSQZ:-311991675) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L329)):_
It's irrelevant and so we pick a random one. The idea here is to ensure that it stays irrelevant. I could test each case but that's just going to duplicate everything for unclear benefit. If it is going to break it is likely to break with this randomization.

---

_[sql/descriptor_mutation_test.go, line 453 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MJ97uAuKQuUxUZU7o:-K3QBoukSu6NrR77TW2j:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L453)):_
done

---

_[sql/descriptor_mutation_test.go, line 465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MJNGMqPiIbYVm9pRR:-K3QBwgRuWAI9HGpliv1:-443330129) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L465)):_
Yes. That direction should never be used.

---

_[sql/descriptor_mutation_test.go, line 114 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MOnbnBf_m7vDsZXLL:-K3QAX_Ix1QOW6h6ZWgu:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L114)):_
done

---

_[sql/descriptor_mutation_test.go, line 471 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MP17mHzBTcamw6jKX:-K3QC8J1zyrYgZLeRB4W:1262006739) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L471)):_
I've taken this code out in a refactoring. Yes mutations can be nil or empty.

---

_[sql/descriptor_mutation_test.go, line 495 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MP9efOio6AUPERwXL:-K3QCLwXvh06YeWHU154:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L495)):_
done

---

_[sql/descriptor_mutation_test.go, line 537 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MPKNocBGbZSW-7pyg:-K3QDp2DWIGsSZZ8u-zl:-302245178) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L537)):_
All done

---

_[sql/descriptor_mutation_test.go, line 577 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MPWI4kwE50BdLG318:-K3QDuI4603oldxabnoI:1535558354) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L577)):_
I've not being using punctuation for single word comments and occasionally for short phrases. I definitely agree that we should use them for sentences, but is there value in adding them for cases like this?

---

_[sql/drop.go, line 152 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MPxdsUak9TsplcVef:-K3QEH-7XlngLTbnI_lU:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/drop.go#L152)):_
done

---

_[sql/rename.go, line 242 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MQHcznPi2YIzrrMKs:-K3QENJB9IzO973sKhjv:-809037443) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/rename.go#L242)):_
Yeah, they've only been removed for the commands that are considered schema changes, and moved to applyMutations(). The code here is being changed to adjust to the new signature for FindIndexByName()

---

_[sql/rename.go, line 328 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MQYn_I2Z3TRzrtE15:-K3R0XAnwgqYIBIJE4Lw:1941204629) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/rename.go#L328)):_
I've changed the implementation here

---

_[sql/rename.go, line 333 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MR2_nf2ivL7pnsSNb:-K3QFQ1ntVERRMsikeiF:-1388111021) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/rename.go#L333)):_
allIndexes doesn't include indexes that are being dropped. In the future we might want to allow inflight changing of the direction from drop to add, and a column name should be reflected under those circumstances

I've renamed all{Columns|Indexes} to allNoneDrop{Column|Indexes} ?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-:-K3R0bjIRBVTKWHzJRl1:-433208907)_

**Comment by tschottdorf** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[sql/alter_table.go, line 82 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MK7YpfevCpxZ3fT1d:-K3R1KeLNN1zUYtHzl-_:-1699264341) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L82)):_
is `tableDesc` shared from some cache? Asking since the previous code seems to operate on a copy and this one just mutates the "original".

---

_[sql/descriptor_mutation_test.go, line 329 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MGEMYNkLBguM-LeCN:-K3R22w9G1jP9LQtvf17:-1396849410) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L329)):_
but in that case you wouldn't even know because neither do you log this, nor is this moving part documented anywhere. I see your point, but consider at least adding a log line somewhere.

---

_[sql/descriptor_mutation_test.go, line 465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MJNGMqPiIbYVm9pRR:-K3R2B93SORjp9y8JLxm:-1089930075) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L465)):_
so should the other one, but your test only tests that at least one of them is forbidden.

---

_[sql/descriptor_mutation_test.go, line 577 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MPWI4kwE50BdLG318:-K3R2cwx_OlQCqUqoOiZ:324423291) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L577)):_
I'm just blindly OCD'ing over the style guide. Obviously those are not substantial comments.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136)_

**Comment by vivekmenezes** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

_[sql/alter_table.go, line 82 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MK7YpfevCpxZ3fT1d:-K3STysKYpOT4K5mdnqr:955183915) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/alter_table.go#L82)):_
These operations read the tableDesc from the database. The original code applied the operations on a copy because a subsequent call to a backfill method needed to see both the old and new descriptor. In the new code, the mutations are added to tableDesc and written to the DB and then passed to applyMutations that goes forth and develops the actual change over a copy of the table descriptor and calls backfill.

---

_[sql/descriptor_mutation_test.go, line 329 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MGEMYNkLBguM-LeCN:-K3SVPiqCcYumoxf6LaD:-794870655) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L329)):_
Added a comment above writeMutation()

---

_[sql/descriptor_mutation_test.go, line 465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MJNGMqPiIbYVm9pRR:-K3SXDoUN_7yjyoU5CsQ:-292811676) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ac1fdb6be843b99e442035a758f4aaa5d2b71fb/sql/descriptor_mutation_test.go#L465)):_
Good point. Added those tests.

---

_[sql/descriptor_mutation_test.go, line 577 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3MPWI4kwE50BdLG318:-K3SXGyrduKZRNnxGKl9:5173697) ([raw file](https://github.com/cockroachdb/cockroach/blob/96c3cd615a132dd4277d979ac88c9a11ada53642/sql/descriptor_mutation_test.go#L577)):_
Ok

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136)_

**Comment by vivekmenezes** [comment]
Any comments on this PR? I'd like to merge it in. I've added a few more unittests to cover more ground and I think it's better from that perspective.

**Comment by petermattis** [comment]
I'm taking a look.

**Comment by petermattis** [comment]
Review status: 6 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

_[sql/alter_table.go, line 79 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_Engvp6lATUWyNhfh:-K3_Engw9m1w_2VVg2sm:904885036) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L79)):_
Why is this an error? I would expect the following to work: `ALTER TABLE foo DROP bar; ALTER TABLE foo ADD bar;`. Since we have a queue of mutations, I don't see the problem with queueing up the addition. I think the error we do want to catch is two additions of the same column: `ALTER TABLE foo ADD bar; ALTER TABLE foo ADD bar;`.

---

_[sql/alter_table.go, line 102 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_FLhYcpGdYil07GwD:-K3_FLhYcpGdYil07GwE:1513609813) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L102)):_
Similar comment as for add column. Why is this an error?

---

_[sql/alter_table.go, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_FSJcGtHRxlH1VvwE:-K3_FSJcGtHRxlH1VvwF:-1398888223) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L121)):_
Perhaps `switch status` with a default case?

---

_[sql/structured.go, line 165 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_Hzr0A6ePOBMhzV2o:-K3_Hzr0A6ePOBMhzV2p:239379938) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L165)):_
I think that should be `1+len(desc.Indexes)...` to account for the primary index.

---

_[sql/structured.go, line 525 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_IRoj5BxAuBCQQ4N8:-K3_IRoj5BxAuBCQQ4N9:-768151094) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L525)):_
Can you expand the comment explaining why there is nothing to be done? I believe this is because the column/index has already been removed, but that's not obvious from looking at this method in isolation.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136)_

**Comment by vivekmenezes** [comment]
thanks

---

Review status: 6 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

_[sql/alter_table.go, line 79 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_Engvp6lATUWyNhfh:-K3_OynVvEP70RP3RUKX:-865931022) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L79)):_
Well I'd like to eventually reverse the operation inflight because I see that being useful when you apply a schema change by mistake and want to quickly reverse what you've done. Adding a new mutation on the queue is not a good long term solution. See https://github.com/cockroachdb/cockroach/issues/3142

---

_[sql/alter_table.go, line 121 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_FSJcGtHRxlH1VvwE:-K3_QVZf3wRmWevX1hjK:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L121)):_
done

---

_[sql/structured.go, line 165 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_Hzr0A6ePOBMhzV2o:-K3_Qcd7Oz-97iQQdd2g:-467991002) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L165)):_
Good point. Done

---

_[sql/structured.go, line 525 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_IRoj5BxAuBCQQ4N8:-K3_RBtoTeiJvY1vdHSY:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L525)):_
done

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-:-K3_RXHjEK7a5yrTd7RB:-1221266418)_

**Comment by petermattis** [comment]
LGTM

---

Review status: 6 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

_[sql/alter_table.go, line 79 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_Engvp6lATUWyNhfh:-K3_WeV_XkUQhyAEF5qt:368856586) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/alter_table.go#L79)):_
Ok, as long as this isn't the long term plan it is fine for now.

---

_[sql/structured.go, line 525 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_IRoj5BxAuBCQQ4N8:-K3_WmlXTqNHF1j7Z9RJ:-1726259077) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L525)):_
Where was this work done?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-:-K3_WvrT00ysYgKhh0x7:676834233)_

**Comment by tamird** [comment]
Reviewed 2 of 13 files at r2, 3 of 10 files at r3, 1 of 3 files at r4.
Review status: 10 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

_[sql/structured.go, line 457 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_g1H_5ZyDEuiu3yy1:-K3_g1H_5ZyDEuiu3yy2:334354438) ([raw file](https://github.com/cockroachdb/cockroach/blob/543662aa7de44ce8c7dc5ed4fb0efca8d6d32257/sql/structured.go#L457)):_
since you're using this enum, why bother with the error? this function looks very awkward now.

---

_[sql/structured.go, line 461 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_gHc1UDGoO7DOyyJQ:-K3_gHc1UDGoO7DOyyJR:1488949171) ([raw file](https://github.com/cockroachdb/cockroach/blob/543662aa7de44ce8c7dc5ed4fb0efca8d6d32257/sql/structured.go#L461)):_
this duplicates logic from the other "find by name function". perhaps avoid that?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136)_

**Comment by vivekmenezes** [comment]
Review status: 10 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

_[sql/structured.go, line 525 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_IRoj5BxAuBCQQ4N8:-K3am2gwR_1EDtCvEjTC:-1972581360) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c0fffc177f2d13842c1f62af66cd52a3c4a8309/sql/structured.go#L525)):_
changed to:

The column/index was already
    // removed from the set of column/index descriptors
    // at mutation creation time.

---

_[sql/structured.go, line 457 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_g1H_5ZyDEuiu3yy1:-K3bY4QvxrkTexBktgHa:475597383) ([raw file](https://github.com/cockroachdb/cockroach/blob/543662aa7de44ce8c7dc5ed4fb0efca8d6d32257/sql/structured.go#L457)):_
I tried getting rid of the error but it makes the code even worse. I tried using 
type DescriptorStatus error
and return three different DescriptorStatus. Unfortunately  a variable error is created fmt.Errorf("column %q does not exist", name) which can only be detected on the caller using status != DescriptorActive && status != DescriptorIncomplete.

If one uses just the enum, then the Absent case on the caller end needs to generate the variable error, which amounts to code duplication.

---

_[sql/structured.go, line 461 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136#-K3_gHc1UDGoO7DOyyJQ:-K3bZTV7EEEpVXzFeZBT:1836533139) ([raw file](https://github.com/cockroachdb/cockroach/blob/543662aa7de44ce8c7dc5ed4fb0efca8d6d32257/sql/structured.go#L461)):_
I don't think there is much duplicate code here.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3136)_

**Comment by vivekmenezes** [comment]
anything else you want me to do here?

**Comment by vivekmenezes** [comment]
I plan to merge this in. Any more comments are more than welcome.

**Pull request merged**
