### PR TITLE
roachtest: perturbation testing improvements

### PR DESCRIPTION
**Pull request by andrewbaptist**
A set of small commits that do the following:
1) Add a "single score" to each time window
2) Make the workload a parameter (although still only have the KV workload)
3) Increase the dead time to match the perturbation time - to prevent replicas moving during the test
4) enable the Full tests for nightly tests (with validated numbers)

### CODE REVIEW

**Comment by andrewbaptist** [comment]
@kvoli - This set of changes enables the tests (both metamorphic and full) and passes on mainline today. See https://docs.google.com/spreadsheets/d/1d1FRq3-2FaiEL7pJBl_bg8JiWnhNDPwAub5GJuuATqw/edit?gid=0#gid=0

The only major remaining task is to start charting the values from the full test to roachperf. Having this merged will give us some confidence in the "passing" tests today (add and decommission) and will allow us to measure the improvement on the prototype branch.

**Review by kvoli — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @renatolabs)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3ckb8d5jvTR_GTyfWS):*
Specify the test name in the commit headline or body.
___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3ck_hw2zLXgdNAkskH):*
Which tests? Specify the test names in the commit headline or body.
___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3clXZv8_Kd0iZfImD3):*
Which test?
___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cm9MADXlOCBWgb2dS):*
Which test?
___
*[`-- commits` line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cmEOTAlrrTVOlDZZM):*
Add the test name.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3clMYz2By4TWhhX8Dh:-O3clMYz2By4TWhhX8Di:b-hr69dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd2c648343ee13731f08dd79aa686fd5c2e5490/pkg/cmd/roachtest/tests/admission_control_latency.go#L760)):*
> ```Go
> 	for _, name := range keys {
> 		hist := sMap[name]
> 		outputStr.WriteString(fmt.Sprintf("%s: %s / %s, ", name, hist.p99, hist.score))
> ```

Consider including `p99` in the short message, otherwise it requires reading the code to know which percentile these log messages correspond to.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 796 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cm04cARcjNwDmR_-3:-O3cm04cARcjNwDmR_-4:bb896fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/76358e5815a1762877bad46f4ac0fa957becbe46/pkg/cmd/roachtest/tests/admission_control_latency.go#L796)):*
> ```Go
> type workloadType interface {
> 	operations() []string
> 	initWorkload(ctx context.Context, v variations) error
> ```

Why is variations a param here? It isn't used below.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 264 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cmU4K8rtQfyuo7BRM:-O3cmU4K8rtQfyuo7BRN:b-undao2) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca7b5d4d0e859b72b95bfff8ba5c74e00e9500a/pkg/cmd/roachtest/tests/admission_control_latency.go#L264)):*
> ```Go
> 		CompatibleClouds: registry.OnlyGCE,
> 		Suites:           registry.Suites(registry.Nightly),
> 		Owner:            registry.OwnerAdmissionControl,
> ```

Should this be KV? Are AC going to triage failures that come in or KV? We should ensure the AC team are in agreement on ownership.

**Review by andrewbaptist — COMMENTED** [review]
TFTR! I added a regex which covers the names of the tetss impacted to each commit, but I could also add the full list of impacted tests if you think its useful for searching. 

Also I update the function for computing the score to match what the document describes (it didn't include vCPUs before). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-:-O3d4RPJ-1O75BKEk2qV:b3p381r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, and @renatolabs)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3ckb8d5jvTR_GTyfWS):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Specify the test name in the commit headline or body.
</blockquote></details>

Added
___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3ck_hw2zLXgdNAkskH):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Which tests? Specify the test names in the commit headline or body.
</blockquote></details>

Added
___
*[`-- commits` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3clXZv8_Kd0iZfImD3):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Which test?
</blockquote></details>

Added
___
*[`-- commits` line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cm9MADXlOCBWgb2dS):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Which test?
</blockquote></details>

Added
___
*[`-- commits` line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cmEOTAlrrTVOlDZZM):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Add the test name.
</blockquote></details>

Added
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3clMYz2By4TWhhX8Dh:-O3d06VI3xLS6DQpo_lS:bxwxb6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd2c648343ee13731f08dd79aa686fd5c2e5490/pkg/cmd/roachtest/tests/admission_control_latency.go#L760)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Consider including `p99` in the short message, otherwise it requires reading the code to know which percentile these log messages correspond to.
</blockquote></details>

The line is already a little long (e.g.

```
2024/08/05 18:12:08 admission_control_latency.go:748: follower-read: 96.468991ms / 5.960888ms, read: 117.440511ms / 6.775727ms, write: 142.606335ms / 6.560857ms, op/s: 5228
```
I added a TODO to clean up this formatting longer term. 
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 796 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cm04cARcjNwDmR_-3:-O3d-jbW2zI0taMJ2R-W:bfe9cvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/76358e5815a1762877bad46f4ac0fa957becbe46/pkg/cmd/roachtest/tests/admission_control_latency.go#L796)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why is variations a param here? It isn't used below.
</blockquote></details>

Its required in the init method for determining how many splits and how to connect to the node.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 264 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cmU4K8rtQfyuo7BRM:-O3d-cVA-Q6Y5KqaIWnA:b-xe98yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/aca7b5d4d0e859b72b95bfff8ba5c74e00e9500a/pkg/cmd/roachtest/tests/admission_control_latency.go#L264)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this be KV? Are AC going to triage failures that come in or KV? We should ensure the AC team are in agreement on ownership.
</blockquote></details>

Agreed - i moved to KV. I'm not exactly sure how this will all look longer term, but its easier to have us triage them.

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @renatolabs)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3dYlfZ6taYQBwPHQpe):*
nit: capitalize the first letter.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 760 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3clMYz2By4TWhhX8Dh:-O3dZ9Vm3KoPlP3ntu8Y:b-tiy56) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd2c648343ee13731f08dd79aa686fd5c2e5490/pkg/cmd/roachtest/tests/admission_control_latency.go#L760)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

The line is already a little long (e.g.

```
2024/08/05 18:12:08 admission_control_latency.go:748: follower-read: 96.468991ms / 5.960888ms, read: 117.440511ms / 6.775727ms, write: 142.606335ms / 6.560857ms, op/s: 5228
```
I added a TODO to clean up this formatting longer term.
</blockquote></details>

Consider adding it at the start of the output str and truncate to one or two decimal places e.g.

```
[...] [p99] follower-read: 96.47ms(5.96ms), read: 117.44ms(6.78ms), write: 142.61ms(6.56ms), op/s: 5228
```
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 796 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-O3cm04cARcjNwDmR_-3:-O3dZx_B2yKBEKfzVJhH:br8c1al) ([raw file](https://github.com/cockroachdb/cockroach/blob/76358e5815a1762877bad46f4ac0fa957becbe46/pkg/cmd/roachtest/tests/admission_control_latency.go#L796)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Its required in the init method for determining how many splits and how to connect to the node.
</blockquote></details>

Ack, thanks for explaining.

**Review by kvoli — APPROVED** [review]
:lgtm: - see the suggestion for formatting, having latency numbers be rounded to 2 decimals or using humanizeutil to do it for you would make the output easier to read:

```
[...] [p99] follower-read: 96.47ms(5.96ms), read: 117.44ms(6.78ms), write: 142.61ms(6.56ms), op/s: 5228
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128181#-:-O3ivSE43g3CkUYB2yKD:bjzz1j6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @renatolabs)

**Comment by andrewbaptist** [comment]
TFTR! 

bors r=kvoli

**Pull request merged**
