### PR TITLE
Consolidates the node graph pages and brings over tooltips from the old UI

### LINKED ISSUE #7101: ui: Reduce repeated code between "nodes" and "node" graph pages
The "Nodes" and "Node" graph pages are nearly identical at this point; they display exactly the same set of graphs, with only the sources queried differing.  

We should identify anything that can be moved to a common component between these two pages and do so.

### PR DESCRIPTION
**Pull request by maxlang**
Fixes #7101
Old tooltips are from #7087

cc @mberhault

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7845)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/components/linegraph.tsx, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnWsM9Fd0BeoLF07F:-KMgnWsM9Fd0BeoLF07G:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/components/linegraph.tsx#L25)):*
> ```XML
>   legend?: boolean;
>   xAxis?: boolean;
>   tooltip?: React.ReactNode;
> ```

ditto

---

*[ui/app/components/visualization.tsx, line 8 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnUifMwl2Y_Grai5I:-KMgnUifMwl2Y_Grai5J:-847068922) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/components/visualization.tsx#L8)):*
> ```XML
>   title: string;
>   subtitle?: string;
>   tooltip?: React.ReactNode;
> ```

does it need to stay optional?

---

*[ui/app/containers/clusterOverview.tsx, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnktZKMvGql0VJZ8C:-KMgnktZKMvGql0VJZ8D:1210757762) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L119)):*
> ```XML
> 
>           <LineGraph title="SQL Traffic"
>                      tooltip="The average amount of SQL client network traffic in bytes per second.">
> ```

throughout: average over all nodes?

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KMgnNl5nLi4716hllYq:1579930090) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
> ```XML
>             </LineGraph>
> 
>             <LineGraph title="GC Pause Time" sources={sources} tooltip={`The average amount of processor time used by Go’s garbage collector per second ${specifier}. During garbage collection, application code execution is paused.`}>
> ```

did you intend to move this?

---

*[ui/app/containers/nodeGraphs.tsx, line 194 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnL3EFpOvQ43wBHiV:-KMgnL3FmbIgSdiopx-v:231141538) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/ui/app/containers/nodeGraphs.tsx#L194)):*
> ```XML
>             </LineGraph>
> 
>             <LineGraph title="Clock Offset" sources={sources}>
> ```

was this removal intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-:-KMjxLkql6YhZfA2KLs8:1417088721)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/components/visualization.tsx, line 8 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnUifMwl2Y_Grai5I:-KMoMFw4loSsdmsjMYpD:716230991) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/components/visualization.tsx#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does it need to stay optional?
</details>
Not all graphs have tooltips. Some of the more 

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KMoND8ID07YpxrWydyH:-35398225) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> did you intend to move this?
</details>
I'm trying to keep the graphs with no tooltips in the "Advanced" section, which could perhaps be called "Advanced Internals" and move the other graphs into the other relevant sections. "GC Pause Time" could be considered a sibling of the "Memory in Use" graph so it's not out of place in the "Resources" section.

---

*[ui/app/containers/nodeGraphs.tsx, line 194 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnL3EFpOvQ43wBHiV:-KMoMM__W9te5cma0_SY:892220070) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/ui/app/containers/nodeGraphs.tsx#L194)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> was this removal intentional?
</details>
Clock offset appears to be broken and may have been for a while. I'll make an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KMoRlCow7mtcB_228Hy:1342147049) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm trying to keep the graphs with no tooltips in the "Advanced" section, which could perhaps be called "Advanced Internals" and move the other graphs into the other relevant sections. "GC Pause Time" could be considered a sibling of the "Memory in Use" graph so it's not out of place in the "Resources" section.
</details>
GC pause shouldn't be in "resources"; it should be in whatever contains latencies IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 194 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnL3EFpOvQ43wBHiV:-KMoS9MQfoeQBMb-WOpV:-595454110) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/ui/app/containers/nodeGraphs.tsx#L194)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Clock offset appears to be broken and may have been for a while. I'll make an issue.
</details>
https://github.com/cockroachdb/cockroach/issues/5728

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by jseldess** [comment]
LGTM. Thanks, Max.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/clusterOverview.tsx, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnktZKMvGql0VJZ8C:-KMw1gAczvPlnIs6NcGy:-1875822601) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L119)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: average over all nodes?
</details>
I'd add "across all nodes" to the end here for the sake of consistency.

---

*[ui/app/containers/clusterOverview.tsx, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw1t0izV6A7dM4aSer:-KMw1t0izV6A7dM4aSes:1951640630) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L126)):*
> ```XML
>           </LineGraph>
> 
>           <LineGraph title="Reads Per Second"
> ```

We had simplified this to just `Reads`.

---

*[ui/app/containers/clusterOverview.tsx, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw1vp343dBezaRrO_y:-KMw1vp343dBezaRrO_z:-608507241) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L133)):*
> ```XML
>           </LineGraph>
> 
>           <LineGraph title="Writes Per Second"
> ```

We had simplified this to just `Writes`.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KMw23w0cS1zofXVm4Ug:-2079264801) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
> ```XML
>             <dt>Go Allocated</dt><dd>Memory allocated by the Go layer</dd>
>             <dt>Go Total</dt><dd>Total memory managed by the Go layer</dd>
>             <dt>C Allocated</dt><dd>Memory allocated by the C layer</dd>
> ```

`C Allocated` should be `Cgo Allocated`.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KMw26wzhVOETwnxAWoU:1894968217) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
> ```XML
>             <dt>Go Total</dt><dd>Total memory managed by the Go layer</dd>
>             <dt>C Allocated</dt><dd>Memory allocated by the C layer</dd>
>             <dt>C Total</dt><dd>Total memory managed by the C layer</dd>
> ```

`C Total` should be `Cgo Total`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-:-KMw2_SJOZ-Goqi5bFBL:-305089102)*

**Comment by jseldess** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by maxlang** [comment]
Review status: 3 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/clusterOverview.tsx, line 119 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnktZKMvGql0VJZ8C:-KMzJv0nFg0iR2pq7K77:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L119)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I'd add "across all nodes" to the end here for the sake of consistency.
</details>
Done.

---

*[ui/app/containers/clusterOverview.tsx, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw1t0izV6A7dM4aSer:-KMzJwOTpaRmqR_L1qQc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L126)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> We had simplified this to just `Reads`.
</details>
Done.

---

*[ui/app/containers/clusterOverview.tsx, line 133 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw1vp343dBezaRrO_y:-KMzJxRk25Bobrtixn-1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/clusterOverview.tsx#L133)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> We had simplified this to just `Writes`.
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KMzK1V6FJBZb-YwQOPJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> `C Allocated` should be `Cgo Allocated`.
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KMzK2Jo_uwwkNL9sHWE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> `C Total` should be `Cgo Total`.
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KMzK6kHQFmNMiK3lqst:1295138970) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> GC pause shouldn't be in "resources"; it should be in whatever contains latencies IMO
</details>
That would be "Activity." I can move it up there or move it back to "Advanced Internals."

---

*[ui/app/containers/nodeGraphs.tsx, line 194 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnL3EFpOvQ43wBHiV:-KMzKEEHYvboEa4tRBgq:1475373443) ([raw file](https://github.com/cockroachdb/cockroach/blob/59322b0bc4ef0b0b907210b5dc7a1e6edc865ddf/ui/app/containers/nodeGraphs.tsx#L194)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> https://github.com/cockroachdb/cockroach/issues/5728
</details>
Created https://github.com/cockroachdb/cockroach/issues/7887 to focus on this specific issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by maxlang** [comment]
screen shot 2016-07-18 at 4 02 20 pm
screen shot 2016-07-18 at 4 02 03 pm

**Comment by maxlang** [comment]
@tamird @jseldess let me know if everything looks good

**Comment by jseldess** [comment]
:lgtm: 

Only one nit to take or leave: move RSS to the top of the metrics list when hovering over the graph. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-:-KMzp3AwL9kual7VjBzx:-1685682014)*

**Comment by tamird** [comment]
Reviewed 4 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-eC6p31-SlP_bRnsi:1145885326) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
Not sure this is right. `Cgo` isn't allocating memory per se. This is a count of memory which is not allocated by Go code.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN-eIz2bF-nrUtwXqGd:-1516241242) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
Not sure this is right. `Cgo` isn't allocating memory per se. This is a count of memory which is not managed by Go code.

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KN-e_dcIxCb8ISkpyD3:-153776961) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> That would be "Activity." I can move it up there or move it back to "Advanced Internals."
</details>
I'm fine with either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-hMkutKfxfLABiq2O:-2133297734) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not sure this is right. `Cgo` isn't allocating memory per se. This is a count of memory which is not allocated by Go code.
</details>
@tmarid, the text Max has here is close to what was approved in PR #7230. If we said something like, "Memory not allocated by the Go layer", wouldn't it be strange to not mention C at all?

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN-hTxmYprWYtBsomD3:39368625) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Not sure this is right. `Cgo` isn't allocating memory per se. This is a count of memory which is not managed by Go code.
</details>
@tamird, same as above. The text Max has here is close to what was approved in PR #7230. If we said something like, "Total memory not managed by the Go layer", wouldn't it be strange to not mention C at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-k-_Sv4E_7CzlX-Nz:-1299490934) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> @tmarid, the text Max has here is close to what was approved in PR #7230. If we said something like, "Memory not allocated by the Go layer", wouldn't it be strange to not mention C at all?
</details>
The text is fine, but this still says `Cgo`. There is an important distinction to be made here between `Cgo` and `C`.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN-ju9cH26hq2UTKZv7:-1299490934) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> @tamird, same as above. The text Max has here is close to what was approved in PR #7230. If we said something like, "Total memory not managed by the Go layer", wouldn't it be strange to not mention C at all?
</details>
The text is fine, but this still says `Cgo`. There is an important distinction to be made here between `Cgo` and `C`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-ndAaamcdoT28m2TU:1592609337) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The text is fine, but this still says `Cgo`. There is an important distinction to be made here between `Cgo` and `C`.
</details>
I don't understand this well enough to suggest a text that more accurately gets at that distinction. Can you please suggest something? 

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN-odAP25I3q_g12dBS:1777810298) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The text is fine, but this still says `Cgo`. There is an important distinction to be made here between `Cgo` and `C`.
</details>
Same as above. Can you please suggest the right text here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-pIDwyi66I9l72q18:-1503975792) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> I don't understand this well enough to suggest a text that more accurately gets at that distinction. Can you please suggest something? 
</details>
I think s/Cgo/C/ would do fine here and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by jseldess** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN-vMlsZGHhWnEqagFy:89160028) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think s/Cgo/C/ would do fine here and below.
</details>
Ah, I see. So @maxlang, let's change this to: `Memory allocated by the Cgo layer`

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN-vcLsXxU04lEtVHNQ:-1574094303) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Same as above. Can you please suggest the right text here?
</details>
@maxlang, let's change this to: `Total memory managed by the Cgo layer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by maxlang** [comment]
Done.

---

Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN31p_XEFhG0MzCxp8V:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> Ah, I see. So @maxlang, let's change this to: `Memory allocated by the Cgo layer`
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN31qUH7YdgSJeDVW78:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, jseldess wrote…</i></summary>
> @maxlang, let's change this to: `Total memory managed by the Cgo layer`
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMgnNl5nLi4716hllYp:-KN31lt_HF2PWir49eTv:-1171358186) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm fine with either.
</details>
Moved to "Activity". Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-:-KMzq4ub_0cphDG66VNx:-499146009)*

**Comment by tamird** [comment]
Eh, s/Cgo/C/ means replace Cgo with C, not the other way around.

**Comment by maxlang** [comment]
@tamird Which `Cgo` did you want replaced where? Replace them all with C? I'm going largely by the last PR.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN5Dnw6puIkTQDzs-0Y:2025040937) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
`<dt>C Allocated</dt><dd>Memory allocated by the C layer</dd>`

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN5DrsjTmAxe1z6snlN:-1397843598) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Done.
</details>
`<dt>C Total</dt><dd>Total memory managed by the C layer</dd>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Comment by maxlang** [comment]
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/app/containers/nodeGraphs.tsx, line 120 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw23w0cS1zofXVm4Uf:-KN8wgdkNpIQmJ0G_pYb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `<dt>C Allocated</dt><dd>Memory allocated by the C layer</dd>`
</details>
Done.

---

*[ui/app/containers/nodeGraphs.tsx, line 121 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845#-KMw26wzhVOETwnxAWoT:-KN8whxxVddrQMYNTdhy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5eca41e7d916e03b953241958f1cee3742486efe/ui/app/containers/nodeGraphs.tsx#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `<dt>C Total</dt><dd>Total memory managed by the C layer</dd>`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7845)*

**Pull request merged**
