### PR TITLE
colexecagg: move the aggregate functions into a separate package

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit does the following:
- moves all aggregate functions into the newly created `colexecagg`
package
- moves previously private struct `colexec.overloadHelper` into
`execgen` package and exports the struct and all of its fields
- moves `colexec.Closer` into `colexecbase`
- moves `colexec.GetDatumToPhysical` to `colconv` package and renames
the file where that function lives from `utils` to `datum_to_vec`.

This is done as the first step at reducing the size of `colexec`
package.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexecbase/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-MKFZdIy3nCWSwoge060:-MKFZdIy3nCWSwoge061:bnbabyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d2f674140ce75a55ca29e248a0d834939c4dcf/pkg/sql/colexecbase/utils.go#L23)):*
> ```Go
> // it correctly, a local variable named `_overloadHelper` of this type must be declared
> // before the inlined overloaded code.
> type OverloadHelper struct {
> ```

What's your reasoning behind moving this to `colexecbase`? It seems too specific to make public. Is there any template-related code in `colexecbase`? Maybe it might make more sense in a template-related package (theoretically, practically it might not make sense due to import cycles).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexecbase/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-MKFZdIy3nCWSwoge060:-MKFpsFd8qhEluNfpZVl:b-80rth6) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d2f674140ce75a55ca29e248a0d834939c4dcf/pkg/sql/colexecbase/utils.go#L23)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What's your reasoning behind moving this to `colexecbase`? It seems too specific to make public. Is there any template-related code in `colexecbase`? Maybe it might make more sense in a template-related package (theoretically, practically it might not make sense due to import cycles).
</blockquote></details>

This helper is now used in two packages `colexec` and `colexecagg` (and I think we might be extracting `colexecproj` for projection operators that uses it as well), so unless we make other changes to the code, we need to export it. `colexecbase` is currently the package that can be used by other `colexec*` packages.

In `colexecagg` we only use `TmpDec1` field when computing some aggregations, so we could refactor that to only provide a single temporary decimal.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

Since we check in generated files, this refactor should be pretty clean when switching branches, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-:-MKG5kqx9gaSxL-sKX_x:bl45526)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexecbase/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-MKFZdIy3nCWSwoge060:-MKG5JCq0T2o6yzjiVtT:b-gz34g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d2f674140ce75a55ca29e248a0d834939c4dcf/pkg/sql/colexecbase/utils.go#L23)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This helper is now used in two packages `colexec` and `colexecagg` (and I think we might be extracting `colexecproj` for projection operators that uses it as well), so unless we make other changes to the code, we need to export it. `colexecbase` is currently the package that can be used by other `colexec*` packages.

In `colexecagg` we only use `TmpDec1` field when computing some aggregations, so we could refactor that to only provide a single temporary decimal.
</blockquote></details>

:+1: can you mention it's specifically a struct to help with templating (i.e. `OverloadHelper is a utility struct used for templates...`? The current mention seems too "quiet" since that's it's primary purpose

**Review by yuzefovich — COMMENTED** [review]
Yes, because of the files being checked there are no problems with switching between branches.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-:-MKH2vpr58yM8QnTW8OR:b-fk7rws)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexecbase/utils.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55796#-MKFZdIy3nCWSwoge060:-MKH2Wz8CA0ge3lvUI5G:bce0k24) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d2f674140ce75a55ca29e248a0d834939c4dcf/pkg/sql/colexecbase/utils.go#L23)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:+1: can you mention it's specifically a struct to help with templating (i.e. `OverloadHelper is a utility struct used for templates...`? The current mention seems too "quiet" since that's it's primary purpose
</blockquote></details>

Updated the comment and moved this file into `colexec/execgen` folder following your earlier suggestion (I think `execgen` is a better place than `colexecbase` since it is more explicit about being "template-only").

**Pull request merged**
