### PR TITLE
xform: use ordering from LIMIT as a hint for streaming group-by

### LINKED ISSUE #93410: Suboptimal query plan on grouped aggregation with LIMIT and ORDER BY
**Describe the problem**
In support issue https://github.com/cockroachlabs/support/issues/1949, a hash group-by + TopK plan is chosen over a streaming group-by when there is a LIMIT on the query because of unique constraints on certain columns, causing the number of grouping columns to be reduced by the optimizer. When one of the unique indexes is dropped, the fast query plan is picked.  

**To Reproduce**
Use the statement bundles in the support issue.

Jira issue: CRDB-22320

### PR DESCRIPTION
**Pull request by msirek**
Fixes #93410

A query with a grouped aggregation, a LIMIT and an ORDER BY may not always explore the best-cost query plan.

Due to the existence of unique constraints on a table, the set of grouping columns may be reduced during normalization via rule ReduceGroupingCols such that it no longer includes columns present in the ORDER BY clause. This eliminates possibly cheap plans from consideration, for example, if the input to the aggregation is a lookup join, it may be cheaper to sort the input to the lookup join on the ORDER BY columns if they overlap with the grouping columns, so that a streaming group-by with no TopK operator can be used, and a full scan of the inputs to the join is avoided.

This fix adds a new exploration rule which ensures that a grouped aggregation with a LIMIT and ORDER BY clause considers using streaming group-by with no TopK when possible.

Release note (bug fix): This patch fixes join queries involving tables with unique constraints using LIMIT, GROUP BY and ORDER BY clauses to ensure the optimizer considers streaming group-by with no TopK operation, when possible. This is often the most efficient query plan.

### CODE REVIEW

**Comment by msirek** [comment]
This fix is causing a plan change in TPC-H Q18.  The old plan takes appr. 4.1s (varies between 4.0s and 4.2s). The new plan with the fix takes appr. 2.5s (usually below this value).

Q18:
```sql
SELECT
            c_name,
            c_custkey,
            o_orderkey,
            o_orderdate,
            o_totalprice,
            sum(l_quantity)
        FROM
            customer,
            orders,
            lineitem
        WHERE
            o_orderkey IN (
                SELECT
                    l_orderkey
                FROM
                    lineitem
                GROUP BY
                    l_orderkey HAVING
                        sum(l_quantity) > 300
            )
            AND c_custkey = o_custkey
            AND o_orderkey = l_orderkey
        GROUP BY
            c_name,
            c_custkey,
            o_orderkey,
            o_orderdate,
            o_totalprice
        ORDER BY
            o_totalprice DESC,
            o_orderdate
        LIMIT 100;
```
old plan:
```sql
  distribution: local
  vectorized: true

  • top-k
  │ estimated row count: 100
  │ order: -any_not_null,+any_not_null
  │ k: 100
  │
  └── • group (hash)
      │ estimated row count: 499,392
      │ group by: o_orderkey
      │
      └── • hash join
          │ estimated row count: 2,016,361
          │ equality: (o_custkey) = (c_custkey)
          │ right cols are key
          │
          ├── • merge join
          │   │ estimated row count: 2,000,405
          │   │ equality: (l_orderkey) = (o_orderkey)
          │   │ right cols are key
          │   │
          │   ├── • scan
          │   │     estimated row count: 6,001,215 (100% of the table; stats collected 8 minutes ago)
          │   │     table: lineitem@primary
          │   │     spans: FULL SCAN
          │   │
          │   └── • merge join (semi)
          │       │ estimated row count: 509,090
          │       │ equality: (o_orderkey) = (l_orderkey)
          │       │ left cols are key
          │       │ right cols are key
          │       │
          │       ├── • scan
          │       │     estimated row count: 1,500,000 (100% of the table; stats collected 8 minutes ago)
          │       │     table: orders@primary
          │       │     spans: FULL SCAN
          │       │
          │       └── • filter
          │           │ estimated row count: 509,090
          │           │ filter: sum > 300.0
          │           │
          │           └── • group (streaming)
          │               │ estimated row count: 1,527,270
          │               │ group by: l_orderkey
          │               │ ordered: +l_orderkey
          │               │
          │               └── • scan
          │                     estimated row count: 6,001,215 (100% of the table; stats collected 8 minutes ago)
          │                     table: lineitem@primary
          │                     spans: FULL SCAN
          │
          └── • scan
                estimated row count: 150,000 (100% of the table; stats collected 9 minutes ago)
                table: customer@primary
                spans: FULL SCAN
```
new plan:
```sql
  distribution: local
  vectorized: true

  • limit
  │ count: 100
  │
  └── • group (partial streaming)
      │ estimated row count: 499,392
      │ group by: o_orderkey, o_totalprice, o_orderdate
      │ ordered: -o_totalprice,+o_orderdate
      │
      └── • lookup join
          │ estimated row count: 2,016,361
          │ table: lineitem@primary
          │ equality: (o_orderkey) = (l_orderkey)
          │
          └── • lookup join
              │ estimated row count: 513,151
              │ table: customer@primary
              │ equality: (o_custkey) = (c_custkey)
              │ equality cols are key
              │
              └── • sort
                  │ estimated row count: 509,090
                  │ order: -o_totalprice,+o_orderdate
                  │
                  └── • merge join (semi)
                      │ estimated row count: 509,090
                      │ equality: (o_orderkey) = (l_orderkey)
                      │ left cols are key
                      │ right cols are key
                      │
                      ├── • scan
                      │     estimated row count: 1,500,000 (100% of the table; stats collected 1 minute ago)
                      │     table: orders@primary
                      │     spans: FULL SCAN
                      │
                      └── • filter
                          │ estimated row count: 509,090
                          │ filter: sum > 300.0
                          │
                          └── • group (streaming)
                              │ estimated row count: 1,527,270
                              │ group by: l_orderkey
                              │ ordered: +l_orderkey
                              │
                              └── • scan
                                    estimated row count: 6,001,215 (100% of the table; stats collected 56 seconds ago)
                                    table: lineitem@primary
                                    spans: FULL SCAN
```

**Review by DrewKimball — COMMENTED** [review]
Nice fix! That new plan looks really nice, almost no blocking operators. That being said, are you sure we can't do this with a little less work by improving the ordering propagation in `ordering/group_by.go`? I haven't thought it through too deeply yet, but maybe in `groupByCanProvideOrdering` the `CanProjectCols` check should use the closure of the grouping columns instead of just the grouping columns themselves - this would include any grouping columns that got removed. And of course there would have to be changes to `groupByBuildChildReqOrdering` and `groupByBuildProvided` as well.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJbUsj5DAU6oGZo6-o4:bx3lm4x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by msirek — COMMENTED** [review]
Interesting idea. I looked into it a bit.  It looks like `groupByBuildChildReqOrdering` only supports finding a required ordering which intersects with the internal ordering of the `GroupByExpr`:
https://github.com/cockroachdb/cockroach/blob/3916aa674df72e4be8a233da273c0fdacb41ecdb/pkg/sql/opt/ordering/group_by.go#L49

These orderings are generated in `GenerateStreamingGroupBy` which calls `DeriveInterestingOrderings`, which looks at indexes or other operations which result in an ordering. The purpose seems to be to reuse an ordering which is already there and just happens to be beneficial instead of looking at the exact ordering required by the parent. So, even if `groupByBuildChildReqOrdering` is taught to find more orderings compatible with a given grouping, we'd still rely on `DeriveInterestingOrderings` to build the `groupBy.Ordering` that we want.  The current fix is using a direct hint from the required ordering in place of `DeriveInterestingOrderings`, so may introduce a sort operation instead of relying on indexes.

Maybe your idea works differently. Perhaps you could say some more about it in case I didn't get the gist of it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJcCsxr8QKPUcNrxKOR:bz0ms6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by DrewKimball — COMMENTED** [review]
For the case when no internal ordering is specified (which I think is the one we care about), I think the original/canonical groupby should have an empty ordering. And every ordering intersects with the empty ordering, so that check will always succeed for the canonical groupby with no internal ordering. Once the ordering gets propagated to the input, I'd expect `DeriveInterestingOrderings` to pick it up and generate the streaming groupby.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJcRHVxDwUgNIZFYB89:b-5p33e6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by msirek — COMMENTED** [review]
I see.  `o.shouldExplore` only triggers exploration when the required ordering is empty. I made a quick change to `groupByBuildChildReqOrdering` but did not see a new ordering when `GenerateStreamingGroupBy` is called. Anyway, these are some good ideas. Maybe you could dump them in an issue. For now the limited scope of this rewrite rule is more targeted, which should make it safer than more general changes, which would get exercised by many more queries, even if it means the fix requires more lines of code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJdD8sSDzrFYxDu2-Vp:brsmwt7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

**Review by DrewKimball — APPROVED** [review]
Hm, yeah, it's not as simple to make it work as I thought. Had a couple nits but this :lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJg-TU81-4DyxBXa0xJ:bixt3sn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rharding6373)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJfvFwN8IISkvMiEeXS:-NJfvFwN8IISkvMiEeXT:bjze8sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L201)):*
> ```Go
> 	}
> 	limitExpr, ok := limitRel.(*memo.LimitExpr)
> 	if !ok {
> ```

[nit] These three conditions are all guaranteed by the optgen code right? I think it's ok to remove them. Also, it should be possible to change the type of limitRel to `*memo.LimitExpr` to avoid the assertion.
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJfxWZhDjK_w1ruNclA:-NJfxWZhDjK_w1ruNclB:bape7vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L220)):*
> ```Go
> 		return
> 	}
> 	groupingCols = groupingCols.Union(orderingColsInClosure)
> ```

[nit] I think all of the above logic could be pulled out into the optgen match pattern, which we generally prefer over custom logic (though `ComputeClosure` needs to be added to `CustomFuncs`)
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJg06U161wMGVQyFyZS:-NJg06U161wMGVQyFyZT:b7a4qfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L247)):*
> ```Go
> 	// construction. We are just adding back in any ordering columns which overlap
> 	// with grouping columns in order to generate a better plan.
> 	disabledRules.Add(int(opt.ReduceGroupingCols))
> ```

Instead of doing this, maybe it would be better to just construct the groupby without going through the factory, like you're doing with the limit below? Since, it seems like we just want a copy of the matched expression with a couple grouping columns added.

**Review by rharding6373 — APPROVED** [review]
Impressive! :lgtm: once Drew's comments are addressed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJgKh7BCi-j0rXE6Vym:bkuhwpz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @msirek)

**Review by msirek — COMMENTED** [review]
Thanks. I found out any added grouping columns have to be removed from the `Aggregations` because execbuilder logic expects a given column to be in the grouping columns or the aggregations, but not both. I won't merge for a day or so in case you have any more comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJi-HEw4SH9gXp4a6Dq:b9oqnpb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJfvFwN8IISkvMiEeXS:-NJhoesB0454tT-GHKQJ:b-jib4l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L201)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] These three conditions are all guaranteed by the optgen code right? I think it's ok to remove them. Also, it should be possible to change the type of limitRel to `*memo.LimitExpr` to avoid the assertion.
</blockquote></details>

Made the changes, except it's not guaranteed that there is an ordering in the limit expression, so I left that check in.
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJfxWZhDjK_w1ruNclA:-NJi-3JS4pFC8NOc9BAU:b6x3txm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L220)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I think all of the above logic could be pulled out into the optgen match pattern, which we generally prefer over custom logic (though `ComputeClosure` needs to be added to `CustomFuncs`)
</blockquote></details>

Added function `GroupingColsClosureOverlappingOrdering`, called from the match pattern.
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJg06U161wMGVQyFyZS:-NJhqa5q5g7sR2spG5WJ:bsyyojs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L247)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Instead of doing this, maybe it would be better to just construct the groupby without going through the factory, like you're doing with the limit below? Since, it seems like we just want a copy of the matched expression with a couple grouping columns added.
</blockquote></details>

I discovered previously this won't work. The input to `LimitExpr` is already marked as `fullyOptimized`, so adding a new `GroupByExpr` to that memo group has no effect because we just end up picking the previously found best-cost expression instead of the new expression. I think this is the reason why we always see the pattern of constructing everything below the top-level expression, and only that top expression is added to a memo group because that group is actively being explored.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJif5myAtjvw25zTBdQ:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJg06U161wMGVQyFyZS:-NJievPz9Q--RCvOAtP5:b-p4lzas) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2875b35fb8da84edc6c17fb7c281988c26b047a/pkg/sql/opt/xform/groupby_funcs.go#L247)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I discovered previously this won't work. The input to `LimitExpr` is already marked as `fullyOptimized`, so adding a new `GroupByExpr` to that memo group has no effect because we just end up picking the previously found best-cost expression instead of the new expression. I think this is the reason why we always see the pattern of constructing everything below the top-level expression, and only that top expression is added to a memo group because that group is actively being explored.
</blockquote></details>

I see, that makes sense. Thanks for explaining.

**Review by msirek — COMMENTED** [review]
TFTRs!
bors r=DrewKimball,rharding6373

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJkl3_6ABSOfHcbMY9Q:b-owskum)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Review by mgartner — COMMENTED** [review]
Very cool! Sorry for the late drive-by - I left a few optional nits.

> Reviewed 1 of 7 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-:-NJlNf1jE6zfkfH0PRUf:bgroumg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 221 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlNMRU7ZWZ42DqXF8u:-NJlNMRU7ZWZ42DqXF8v:b-3b1kcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/groupby_funcs.go#L221)):*
> ```Go
> // `GroupingColsClosureOverlappingOrdering`, which also produces the
> // `newOrdering`. Argument `private` is expected to be a canonical group-by.
> func (c *CustomFuncs) GenerateStreamingGroupByLimitOrderingHint(
> ```

nit: "hint" may be confusing because hints usually mean explicity query hints - what is the intentional meaning here?
___
*[`pkg/sql/opt/xform/groupby_funcs.go` line 281 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlIWBvCzJRsBQygF-z:-NJlIWBvCzJRsBQygF0-:b-k3pqg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/groupby_funcs.go#L281)):*
> ```Go
> 			).(memo.RelExpr)
> 	}
> 	var disabledRules intsets.Fast
> ```

nit: FYI, you can create this set in one line with `intsets.MakeFast(int(opt.ReduceGroupingCols))`
___
*[`pkg/sql/opt/xform/rules/limit.opt` line 190 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlJBhh7IBQJDVfji_O:-NJlJBhh7IBQJDVfji_P:bukv0lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/rules/limit.opt#L190)):*
> ```
> # GenerateStreamingGroupByLimitOrderingHint generates streaming group-by and
> # distinct-on aggregations with an ordering matching the ordering specified in
> # the Limit Op. The goal is to eliminate the need for a TopK operation.
> ```

nit: an example here might be helpful, for example a diagram showing a before and after subtree. It's also not obvious to me why eliminating the TopK is a good thing - it's for cases when a plan with a TopK is actually more expensive than a Sort, is that correct?
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2582 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlJ_Yc0o48VobiLMFZ:-NJlJ_Yc0o48VobiLMF_:b-kfufcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/testdata/rules/limit#L2582)):*
> ```
>            └── a:1
> 
> # Regression Test for #93410
> ```

nit: I'd label and organize this as we do for test of other rules, since it's not really a regression - it's a new feature. Like:

```
# --------------------------------------------------
# GenerateStreamingGroupByLimitOrderingHint
# --------------------------------------------------

```
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2607 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlLMQ464ZTtn_ANavr:-NJlLMQ464ZTtn_ANavs:b-12mar7) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/testdata/rules/limit#L2607)):*
> ```
>         INDEX t93410_col1_col2_col13_col15_idx (col1 ASC, col2 ASC, col13 ASC, col15 ASC),
>         UNIQUE INDEX t93410_col1_col2_col5_col9_key (col1 ASC, col2 ASC, col5 ASC, col9 ASC),
>         UNIQUE INDEX t93410_col1_col2_col5_key (col1 ASC, col2 ASC, col5 ASC)
> ```

It's a lot of work to simplify these test cases that were derived from TPC benchmarks, but we might be thankful for that later when we come along and update the rule. One strategy that can be effective is to write minimal "unit-y" tests in xform tests that exercise all the code paths of the rule, and then a "regression" test as an execbuilder test to ensure that the specific case you're trying to fix is covered. I know I'm being nitpicky here, so up to you if you want to do that or not.
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 3046 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93858#-NJlMvll8D3W678Web6Q:-NJlMvll8D3W678Web6R:b9o2qwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/04eb457f7d78589f66c1552409ea58fb227e0ba5/pkg/sql/opt/xform/testdata/rules/limit#L3046)):*
> ```
>       └── 20
> 
> # End Regression Test for #93410
> ```

Is it possible to add tests to test the other non-matching cases of the rule, like a negative LIMIT, or when the new aggregate output columns don't match the LIMIT's order by columns?

**Comment by msirek** [comment]
bors retry

**Comment by msirek** [comment]
If this PR is backported, be sure to backport #94112 as well.

**Comment by ikawalec** [comment]
@msirek in which version this fix will be available?

**Comment by mgartner** [comment]
@ikawalec This improvement will be included in v23.1.0 which is scheduled to be release in May.

**Comment by msirek** [comment]
@ikawalec The soonest this fix will be available is towards the end of January in version 22.2.3.
[CRDB Releases](https://www.cockroachlabs.com/docs/releases/index.html)
Note, the fix will ship disabled, so to enable it, the following session setting can be turned on:
```
SET optimizer_use_limit_ordering_for_streaming_group_by = true;
```
The setting may also be enabled for all users in a given ROLE via [ALTER ROLE](https://www.cockroachlabs.com/docs/stable/alter-role.html)

**Comment by ikawalec** [comment]
> @ikawalec The soonest this fix will be available is towards the end of January in version 22.2.3. [CRDB Releases](https://www.cockroachlabs.com/docs/releases/index.html) Note, the fix will ship disabled, so to enable it, the following session setting can be turned on:
> 
> ```
> SET optimizer_use_limit_ordering_for_streaming_group_by = true;
> ```
> 
> The setting may also be enabled for all users in a given ROLE via [ALTER ROLE](https://www.cockroachlabs.com/docs/stable/alter-role.html)

Thanks for the update @msirek 

We will give it a try, once it's released.

**Pull request merged**
