### PR TITLE
server,sql,ui: disable system.eventlog by default, remove event box

### LINKED ISSUE #69772: backupccl: consider including the event log in cluster backup
Today the eventlog is not included in cluster backups. Perhaps they should be.

If we think they should be the change would probably look something like https://github.com/pbardea/cockroach/commit/c0b04c2fe60304334c9837b709db359161c62203.

Jira issue: CRDB-9780

### LINKED ISSUE #72325: logs: generated docs are not accurate when referencing which events go to system.eventlog table
**Describe the problem**

First identified by @fabiog1901: our [docs](https://www.cockroachlabs.com/docs/stable/eventlog.html) mention that `SESSIONS` events will go to the `system.eventlog` table. 

However, that is not accurate. There are inaccuracies in our generated docs around what events go to `system.eventlog`. 

This issue tracks the follow up work to audit / check doc strings with the implementation as suggested by @knz 

Jira issue: CRDB-11096

### PR DESCRIPTION
**Pull request by knz**
Fixes #69772.
Fixes #72325.
Informs #73308.

We're going to remove the population of system.eventlog for structured
events:

- it adds a 5-way write to many small "maintainance" transactions.
- it forces a global roundtrip in multi-region schema changes.
- it does not significantly help when something goes wrong, as when
  something goes wrong there may not be a way to access the system
  table any more.
- it is not sufficiently tamper-proof, and thus unsuitable for
  audit logging.

The deprecation had been announced as of 21.1. It's time to move
forward with the removal: we're making the feature opt-in instead of
opt-out for one release cycle, then remove it in the next cycle.

Release justification: stop released code from relying on deprecated features

Release note (backward-incompatible change): The storage of
operational events in `system.eventlog` had been deprecated since
v21.1. It is now disabled by default. Deployments should now
transition to structured logging events, stored outside of
CockroachDB. It is still possible to manually re-enable the feature
via the cluster setting `server.eventlog.enabled`, but the feature
will be removed altogether in an upcoming version of CockroachDB.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
should we do something to the events box in the right pane of the Metrics pane?


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84983#-:-N80LO7fATR40or0IBjM:b-t1o3hx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
> should we do something to the events box in the right pane of the Metrics pane?

**Comment by knz** [comment]
> should we do something to the events box in the right pane of the Metrics pane?

Do we like it still?

**Comment by andreimatei** [comment]
I kinda like it because it's one of the few things in the console that gives a user the impression that the console has any clue about stuff that's happening to a cluster. It doesn't seem very important to me, but between having it and not having it I'd vote for having it. Not at the cost of inter-region writes for schema changes, though. So if that motivation is burning, I'm not against getting rid of it (but then I think it's up to this PR to do something to the UI). If it's not burning, I would leave it alone until 23.1, when hopefully the Obs Service should be deployed and ready to serve it.

**Comment by andreimatei** [comment]
I think I'd rather remove the functionality th \

**Comment by knz** [comment]
Done. RFAL

(I'd like this to merge for 22.2)

**Comment by dhartunian** [comment]
@knz can we stop writing schema change events to the table as a compromise for this release? Then we can point people to information about where they can find that info if they're looking for it. I think people rely on that box for the node events. It provides helpful reassurance in a running cluster.

**Comment by knz** [comment]
Yes we can do what you suggest as a compromise.

However:
> I think people rely on that box for the node events. It provides helpful reassurance in a running cluster.

Are you sure of this? Do we have proof?

**Comment by knz** [comment]
Okay it looks like we've collected proof through discussion.
https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1660559141523049

I'll make the recommended change.

**Comment by knz** [comment]
Let's go for the following PR instead:  #86174

If folk like it, I'll close this one and also the other issues i've created around it.

**Comment by knz** [comment]
Subsumed by #86174.

**Pull request closed without merging**
