### PR TITLE
workload: add SQLRunner, use it in KV

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### workload: add SQLRunner

A common facility for issuing SQL queries. It supports multiple
issuing methods, specified by the `--method` flag:
 - prepare: each statement is prepared once per session and then
   reused.
 - noprepare: each statement is executed directly (which internally
   is equivalent to preparing and executing each statement
   separately).
 - simple: parameters are formatted as text and replaced in the query
   before it is issued.

Release note: None

#### workload: switch KV to use SQLRunner

The default `prepare` method should be equivalent to the old code.

Ran a performance benchmark (on gceworker, 10 interleaved runs each). 
Ops/s:
 - before: 14890 avg (717 stddev)
 - prepare: 14942 avg (513 stddev)
 - noprepare: 13692 avg (376 stddev)
 - simple: 14685 avg (382 stddev)

Release note: None

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Review by nvb — APPROVED** [review]
:lgtm_strong: this is awesome!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31159#-:-LORPi0V4ubpStE8aLGl:bnekrlx)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/sql_runner.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31159#-LORP-CG3Id9sGpuKYbC:-LORP-CG3Id9sGpuKYbD:bjklp4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f044212d6cd999789e3c4ff751242d0e34d86131/pkg/workload/sql_runner.go#L126)):*
> ```Go
> 	sr.method, ok = stringToMethod[strings.ToLower(flags.Method)]
> 	if !ok {
> 		return fmt.Errorf("unknown method %s", flags.Method)
> ```

nit: let's be consistent about using the `errors` package or not.

**Review by danhhz — APPROVED** [review]
Great stuff!

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31159#-:-LOTZxQE5lvyEQ4Cw8sx:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
I hit some (more) issues with `sql.Database` with TPCC.. I'm going to try rewriting SQLRunner to use `pgx` and see how it goes. It'll be good to have some perf numbers with both versions.

**Comment by RaduBerinde** [comment]
I rewrote SQLRunner to use `pgx` and I see similar performance [numbers](https://docs.google.com/spreadsheets/d/1I028xgdHM9nqydMG3KblfzvZlXGfLRBXrC3xeqiilG8/edit#gid=1667043882) for kv. I will need to make an upstream change to allow proper support for multiple db hosts within a `pgx.ConnPool`.

**Comment by RaduBerinde** [comment]
This is the pgx change I'm proposing: https://github.com/jackc/pgx/pull/466

**Comment by nvanbenschoten** [comment]
Those latest `lib/pq` vs. `pgx` numbers look good. Thanks for running that comparison. 

The change to `pgx` also checks out, but we'll see what they say. If they don't like it, an alternative might be to create a layer above a set of connection pools that round-robins access to them. Are there any obvious downsides to that?

**Comment by RaduBerinde** [comment]
That would work fine.. I had thought that we'd need to replicate the ConnPool code to keep a map of prepared statements, but that shouldn't be necessary if the collection of pools is static (we can issue each Prepare to all of them). Maybe I'll try that and retract the pgx change..

**Comment by RaduBerinde** [comment]
I opened a new PR #31358 with the pgx version. Closing this.

**Pull request closed without merging**
