### PR TITLE
exec: remove Nils from Copy; improve hashjoiner; fix noescape regression

### PR DESCRIPTION
**Pull request by jordanlewis**
Started doing a rabbithole of removing `Nils` from `Copy`, since I needed to extend `Copy` for `case`, and ended up finding a bunch of cleanups and performance improvements.

I'm not sure when `noescape` stopped working, but fixing it 3x'd the speed of the hash joiner. We should probably re-run our TPCH benchmarks.

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rafiss)

___
*[pkg/sql/exec/hash.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmofRed7kN5AWU1Vbd4:-LmofRed7kN5AWU1Vbd5:bh5fb35) ([raw file](https://github.com/cockroachdb/cockroach/blob/0147e78fdb848f79207694f812e8c1ab10807727/pkg/sql/exec/hash.go#L62)):*
> ```Go
> }
> 
> //go:nosplit
> ```

not sure i entirely follow. from my reading it seems like nosplit instructs the compiler to not insert a check to see if the stack size needs to grow. how does that affect escaping to the heap? also, i don't understand the function implementation. maybe some comments could help
___
*[pkg/sql/exec/hash.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmofqBnBuGMkyI4yqmX:-LmofqBnBuGMkyI4yqmY:bmp5l0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1fcb37e1cf7667b4c0cf8d05c3aab571e6da29/pkg/sql/exec/hash.go#L62)):*
> ```Go
> }
> 
> //go:linkname noescape runtime.noescape
> ```

curious how the `//go:linkname noescape runtime.noescape` differs from just `//go:noescape`
___
*[pkg/sql/exec/hash.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmoewhdEZTEAXjgS8D1:-LmoewheErCIpW5nC1fj:b-4aenab) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f1fcb37e1cf7667b4c0cf8d05c3aab571e6da29/pkg/sql/exec/hash.go#L63)):*
> ```Go
> 
> //go:linkname noescape runtime.noescape
> func noescape(p unsafe.Pointer) unsafe.Pointer
> ```

i saw this earlier.. where was this function implemented before?
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmogeeWE_Y3pWXTsK7O:-LmogeeWE_Y3pWXTsK7P:bukscew) ([raw file](https://github.com/cockroachdb/cockroach/blob/90efb758bcde198e2eca10449f633d487b0ae3de/pkg/sql/exec/hashjoiner_tmpl.go#L258)):*
> ```Go
> 	// {{define "collectNoOuter"}}
> 	// Early bounds checks.
> 	_ = prober.ht.headID[batchSize-1]
> ```

that's cool, i didn't realize you could force t he bounds check to just happen once outside the loop. is it guaranteed to work all the time?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rafiss)

___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmogeeWE_Y3pWXTsK7O:-Lmokw5r6ulluhlX4nS1:b4mhb40) ([raw file](https://github.com/cockroachdb/cockroach/blob/90efb758bcde198e2eca10449f633d487b0ae3de/pkg/sql/exec/hashjoiner_tmpl.go#L258)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that's cool, i didn't realize you could force t he bounds check to just happen once outside the loop. is it guaranteed to work all the time?
</blockquote></details>

to elaborate - i was wondering if a linting rule could be added to detect this

**Review by asubiotto — CHANGES_REQUESTED** [review]
Amazing stuff, thank you for doing this. I'm slightly concerned about the `noescape` regression. I'm wondering if there's a way to assert that no allocations happen? I wrote a small test to see if we can do this:
```
func TestAllocations(t *testing.T) {
	defer leaktest.AfterTest(t)

	s := &runtime.MemStats{}
	runtime.ReadMemStats(s)
	numAlloc := s.TotalAlloc
	runtime.ReadMemStats(s)
	require.Equal(t, numAlloc, s.TotalAlloc)
}
```
Stressed that for 5 minutes and it seems stable. We could maybe put in a hash operation between the two and assert a constant increase in the number of allocated objects? It's a bit brittle, but I think better than not having any checks.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-:-LmoonAQ47kWv6lUax3H:b-igsnpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/hash.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmofRed7kN5AWU1Vbd4:-Lmoslcw4-r_rX_L1cUR:bxr215q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0147e78fdb848f79207694f812e8c1ab10807727/pkg/sql/exec/hash.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not sure i entirely follow. from my reading it seems like nosplit instructs the compiler to not insert a check to see if the stack size needs to grow. how does that affect escaping to the heap? also, i don't understand the function implementation. maybe some comments could help
</blockquote></details>

According to this article https://dave.cheney.net/2018/01/08/gos-hidden-pragmas, noescape is only allowed on forward declarations. I'm not sure why nosplit is necessary but I guess it's just to make sure that this really is a noop. The original `noescape` is defined in the runtime package. BTW, @jordanlewis, is this not giving you linter errors? I think I had to add linkname because the function body was making the linter unhappy.
___
*[pkg/sql/exec/hashjoiner.go, line 970 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-Lmoq1011Bzulud6eMws:-Lmoq10E6N4mQD7ZjhTK:b-u0o8f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ce5489763ef90f9856e4aa7ca29a2f65ea720d/pkg/sql/exec/hashjoiner.go#L970)):*
> ```Go
> 			// Add in the nulls we needed to set for the outer join.
> 			nulls := outCol.Nulls()
> 			for i, isNull := range prober.probeRowUnmatched {
> ```

Does this pass tests? I remember that I tried this approach but there was some garbage in a selection vector which caused a panic, is that fixed by the `currentID` change?
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-Lmoqk7QEMYjTAOYElZm:-Lmoqk7QEMYjTAOYElZn:b-6r7svv) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ce5489763ef90f9856e4aa7ca29a2f65ea720d/pkg/sql/exec/hashjoiner_tmpl.go#L274)):*
> ```Go
> 		rowUnmatched := id == 0
> 		prober.probeRowUnmatched[i] = rowUnmatched
> 		if !rowUnmatched {
> ```

nit: double negative is a bit confusing, is it true that a row is matched if `id != 0`? If so maybe change `rowUnmatched` to `rowMatched` and negate the current checks

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/hash.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmofRed7kN5AWU1Vbd4:-LmovNvK-oHA9q7nv_1-:beqc9kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0147e78fdb848f79207694f812e8c1ab10807727/pkg/sql/exec/hash.go#L62)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

According to this article https://dave.cheney.net/2018/01/08/gos-hidden-pragmas, noescape is only allowed on forward declarations. I'm not sure why nosplit is necessary but I guess it's just to make sure that this really is a noop. The original `noescape` is defined in the runtime package. BTW, @jordanlewis, is this not giving you linter errors? I think I had to add linkname because the function body was making the linter unhappy.
</blockquote></details>

ah i see, i guess basically everything in here is from the runtime package (and that's already noted above), so perhaps further commenting isn't necessary

**Review by jordanlewis — COMMENTED** [review]
I wrote a little test for this, thanks for the suggestion. RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-:-LmpzhA52bXT-IOM8w7F:bsv427)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rafiss)

___
*[pkg/sql/exec/hash.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmofRed7kN5AWU1Vbd4:-Lmpy3-x9de_pCFWeUvS:b7kbjpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0147e78fdb848f79207694f812e8c1ab10807727/pkg/sql/exec/hash.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see, i guess basically everything in here is from the runtime package (and that's already noted above), so perhaps further commenting isn't necessary
</blockquote></details>

Copied in the comment from the runtime package for good measure.
___
*[pkg/sql/exec/hashjoiner.go, line 970 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-Lmoq1011Bzulud6eMws:-LmptHgR4bEmlzjHcP4e:b-jsmm1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ce5489763ef90f9856e4aa7ca29a2f65ea720d/pkg/sql/exec/hashjoiner.go#L970)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this pass tests? I remember that I tried this approach but there was some garbage in a selection vector which caused a panic, is that fixed by the `currentID` change?
</blockquote></details>

Yeah, I fixed all of the cases that could produce garbage (caused by setting the result to 0-1, which overflows).
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-Lmoqk7QEMYjTAOYElZm:-LmpwOPx9t4SveJBsPdG:b-jy7hao) ([raw file](https://github.com/cockroachdb/cockroach/blob/28ce5489763ef90f9856e4aa7ca29a2f65ea720d/pkg/sql/exec/hashjoiner_tmpl.go#L274)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: double negative is a bit confusing, is it true that a row is matched if `id != 0`? If so maybe change `rowUnmatched` to `rowMatched` and negate the current checks
</blockquote></details>

I find this more confusing - you get a double negative anyway where you say 

```
rowMatched := id != 0
prober.probeRowUnmatched[i] = !rowMatched
```

The language now matches `probeRowUnmatched`.
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-LmogeeWE_Y3pWXTsK7O:-Lmpw5LY7ooaFY7-mQ78:bj9r9fo) ([raw file](https://github.com/cockroachdb/cockroach/blob/90efb758bcde198e2eca10449f633d487b0ae3de/pkg/sql/exec/hashjoiner_tmpl.go#L258)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to elaborate - i was wondering if a linting rule could be added to detect this
</blockquote></details>

Yeah I'd love that. I'm definitely not going to do it as part of this PR, but having such infrastructure in place would be extremely helpful.

**Comment by jordanlewis** [comment]
Dang it, the new test failed under stress:

```
[19:54:01]636 runs so far, 0 failures, over 5s
[19:54:06]1269 runs so far, 0 failures, over 10s
[19:54:11]1909 runs so far, 0 failures, over 15s
[19:54:16]2544 runs so far, 0 failures, over 20s
[19:54:21]3179 runs so far, 0 failures, over 25s
[19:54:26]3813 runs so far, 0 failures, over 30s
[19:54:31]4441 runs so far, 0 failures, over 35s
[19:54:36]5083 runs so far, 0 failures, over 40s
[19:54:41]5720 runs so far, 0 failures, over 45s
[19:54:46]6357 runs so far, 0 failures, over 50s
[19:54:51]6988 runs so far, 0 failures, over 55s
[19:54:56]7629 runs so far, 0 failures, over 1m0s
[19:55:01]8263 runs so far, 0 failures, over 1m5s
[19:55:06]8898 runs so far, 0 failures, over 1m10s
[19:55:11]9541 runs so far, 0 failures, over 1m15s
[19:55:16]10186 runs so far, 0 failures, over 1m20s
[19:55:21]10819 runs so far, 0 failures, over 1m25s
[19:55:26]11438 runs so far, 0 failures, over 1m30s
[19:55:31]12062 runs so far, 0 failures, over 1m35s
[19:55:36]12692 runs so far, 0 failures, over 1m40s
[19:55:41]13325 runs so far, 0 failures, over 1m45s
[19:55:46]13962 runs so far, 0 failures, over 1m50s
[19:55:51]14596 runs so far, 0 failures, over 1m55s
[19:55:56]15228 runs so far, 0 failures, over 2m0s
[19:55:58]
[19:55:58]I190821 23:55:58.260026 1 rand.go:83  Random seed: -1004038225829400819
[19:55:58]=== RUN   TestHashingDoesNotAllocate
[19:55:58]--- FAIL: TestHashingDoesNotAllocate (0.00s)
[19:55:58]    require.go:157: 
[19:55:58]        	Error Trace:	hashjoiner_test.go:845
[19:55:58]        	Error:      	Not equal: 
[19:55:58]        	            	expected: 0x5d2688
[19:55:58]        	            	actual  : 0x5d2e08
[19:55:58]        	Test:       	TestHashingDoesNotAllocate
```

**Comment by jordanlewis** [comment]
I deflaked the test.

**Comment by jordanlewis** [comment]
PTAL!

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39792#-:-Lmz_LISCwj9GhDjadZ7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rafiss)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
