### PR TITLE
colexec: reduce number of comparisons in ordered synchronizer

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, to find out what is the current minimum row among all inputs
in the ordered synchronizer we would do a linear scan which would
perform O(n) number of row comparisons where n is the number of inputs.
Now we will maintain a minimum heap between all inputs so that finding
a minimum and consequent update of the heap is done in O(log n).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
As a sanity check, I ran `BenchmarkOrderedSynchronizer` with 32 inputs against master, and here the comparison:
```
name                    old time/op    new time/op    delta
OrderedSynchronizer-16     656µs ± 3%     148µs ± 5%   -77.40%  (p=0.000 n=9+9)

name                    old speed      new speed      delta
OrderedSynchronizer-16   400MB/s ± 3%  1770MB/s ± 4%  +342.54%  (p=0.000 n=9+9)
```

This performance improvement will probably not matter that much when `OrderedSynchronizer` is used as an input synchronizer, but it'll be very beneficial for external sort that I'm working on in #43786.

**Review by solongordon — APPROVED** [review]
:lgtm: I tried this back when I first wrote the ordered synchronizer and saw surprisingly little improvement. But I think that was for much fewer than 32 inputs. If you haven't already, I'd recommend checking out the benchmark for a small number of inputs to make sure it's not significantly worse than the linear scan.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43817#-:-Ly5N_wH-rvdjpHUzTYm:b2eekef)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by yuzefovich** [comment]
Good point.

On 2 inputs:
```
name                    old time/op    new time/op    delta
OrderedSynchronizer-16     119µs ± 1%     123µs ± 1%  +3.14%  (p=0.000 n=10+9)

name                    old speed      new speed      delta
OrderedSynchronizer-16   137MB/s ± 1%   133MB/s ± 1%  -3.05%  (p=0.000 n=10+9)
```

On 3 inputs:
```
name                    old time/op    new time/op    delta
OrderedSynchronizer-16     136µs ± 1%     139µs ± 1%  +2.33%  (p=0.000 n=9+10)

name                    old speed      new speed      delta
OrderedSynchronizer-16   181MB/s ± 1%   177MB/s ± 1%  -2.27%  (p=0.000 n=9+10)
```
So the hit is very minor in those cases.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
