### PR TITLE
sql: handle udf invoking other udfs edge cases

### LINKED ISSUE #120366: sql: disallow renames of a UDF if it has UDF dependents
Presently when functions are invoked inside UDF bodies the references are all by name, if any of the referenced UDF's gets renamed the parent UDF ends up breaking. To address this, we will block UDF rename operations in this scenario:
i.e:

```
CREATE PROCEDURE p_rewrite() AS $$
  SELECT nested_func();
  SELECT * FROM nested_func();
$$ LANGUAGE SQL

-- This will break today
ALTER FUNCTION nested_func rename nested_func_diff
```

The long term fix is: #120351

Epic [CRDB-19398](https://cockroachlabs.atlassian.net/browse/CRDB-19398)

Jira issue: CRDB-36648

Epic CRDB-19398

### PR DESCRIPTION
**Pull request by fqazi**
This patch addresses the following issues:

1. Previously it was possible for a UDF invoking another UDF to be broken by the referenced UDF getting re-named. This patch prevents allowing renames of UDFs which are invoked by other UDFs.
2. When restoring a UDF invoking another UDF, we did not properly remap the forward references making such backups impossible to restore. To address this, we add rewrite logic for DependsOnFunctions field.

Fixes: #120366
Epic:  CRDB-19398

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-:-NtI-vSx9EkMQoI-W9w8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @msbutler and @yuzefovich)

**Comment by mgartner** [comment]
Thanks for the fixes!

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-:-NtItGtG-gtbflKCUwUE:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @fqazi and @msbutler)

___
*[`pkg/sql/alter_function.go` line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-NtIsMu-AAROT-tyCqo0:-NtIsMu-AAROT-tyCqo1:bgrtijg) ([raw file](https://github.com/cockroachdb/cockroach/blob/510201fa580d6191314445371643b09368264651/pkg/sql/alter_function.go#L225)):*
> ```Go
> 	}
> 	if len(dependentFuncs) > 0 {
> 		return pgerror.Newf(
> ```

nit: this sounds like a - hopefully - temporary limitation, so should we have a public issue with docs-todo label, and then use unimplemented error referencing that issue here?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @msbutler, and @yuzefovich)

___
*[`pkg/sql/alter_function.go` line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-NtIsMu-AAROT-tyCqo0:-NtJb2Wg2y7blS8AWXkG:b-izoei2) ([raw file](https://github.com/cockroachdb/cockroach/blob/510201fa580d6191314445371643b09368264651/pkg/sql/alter_function.go#L225)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this sounds like a - hopefully - temporary limitation, so should we have a public issue with docs-todo label, and then use unimplemented error referencing that issue here?
</blockquote></details>

I referenced the issue that we are using to track this

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi, @mgartner, @msbutler, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_calling_udf` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-NtJgKGY0DcX7LsTyO_s:-NtJgKGY0DcX7LsTyO_t:b-43l79s) ([raw file](https://github.com/cockroachdb/cockroach/blob/beaf23be05a38ef0d07db64cba7a59489cc308be/pkg/sql/logictest/testdata/logic_test/udf_calling_udf#L24)):*
> ```
> # Validate that function renaming is blocked.
> statement error pgcode 0A000 cannot rename function \"lower_hello\" because other functions \(\[test.public.upper_hello, test.public.concat_hello\]\) still depend on it
> ALTER FUNCTION lower_hello rename to lower_hello_new
> ```

is this blocked in declarative schema changer also?

**Review by rafiss — APPROVED** [review]

**Review by rafiss — COMMENTED** [review]
> Dismissed @rafiss from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi, @mgartner, @msbutler, and @yuzefovich)

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120433)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @msbutler, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_calling_udf` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120433#-NtJgKGY0DcX7LsTyO_s:-NtM3DfO6w0Fqbs3IQav:bo968eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/beaf23be05a38ef0d07db64cba7a59489cc308be/pkg/sql/logictest/testdata/logic_test/udf_calling_udf#L24)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this test seems like it's missing something. should it say `ALTER FUNCTION lower_hello TO lower_hello_new`?
</blockquote></details>

Alter function isn't implemented there yet, so its doesn't need to be yet.

**Comment by fqazi** [comment]
@rafiss @yuzefovich @mgartner TFTR!

bors r+

**Pull request merged**
