### PR TITLE
sql: grant/revoke privileges for udfs

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
There are 4 commits:
(1) add syntax support for grant/revoke privileges of function.
(2) implement grant/revoke privilege for functions (mostly just reading correct descriptors)
(3) fix a minor issue when hydrating a mutable function which use table implicit type (mutable table implicit type cannot be fetched)
(4) populate `information_schema.role_routine_grants`, and we can test privileges on that.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I'd like to ask you to try out my suggestion in 3. Otherwise, :lgtm: 

> Reviewed 9 of 9 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-:-N99xyap082ugMl9dg0c:b-js4czt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/information_schema.go` line 1594 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xmPHB5Ahqvk4rUd2:-N99xmPHB5Ahqvk4rUd3:bpnytaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d4251f404153be02e19be725f956a96000ff2cd/pkg/sql/information_schema.go#L1594)):*
> ```Go
> var informationSchemaRoleRoutineGrantsTable = virtualSchemaTable{
> 	// TODO(chengxiong): add builtin function privileges as well.
> 	comment: "privileges granted on functions (incomplete; only contains privileges of user-defined functions)",
> ```

Should we file an issue to list privileges for the builtins? 
___
*[`pkg/sql/catalog/descs/hydrate.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xNAQBtnphsnLTIH4:-N99xNAQBtnphsnLTIH5:bghvhp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/833e6bc9516190d59610de636a1f88e9b6470f27/pkg/sql/catalog/descs/hydrate.go#L268)):*
> ```Go
> 	return func(ctx context.Context, id descpb.ID) (tree.TypeName, catalog.TypeDescriptor, error) {
> 		var typDesc catalog.TypeDescriptor
> 		typDesc, err := tc.GetMutableTypeVersionByID(ctx, txn, id)
> ```

What would happen if we always got an immutable type here with `AvoidLeased`? I have a feeling that the choice to get a `Mutable` type here is vestigial. I'd be curious to learn if anything breaks. I think always resolving an immutable here would be strictly better if it doesn't cause any problems.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85874)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/information_schema.go` line 1594 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xmPHB5Ahqvk4rUd2:-N9CD50155zCkozB5ZYf:b7tvodc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d4251f404153be02e19be725f956a96000ff2cd/pkg/sql/information_schema.go#L1594)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Should we file an issue to list privileges for the builtins? 
</blockquote></details>

Yes, I'll file one.
___
*[`pkg/sql/catalog/descs/hydrate.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xNAQBtnphsnLTIH4:-N9CDG5d4so0eKv2vhYS:b-rozr7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/833e6bc9516190d59610de636a1f88e9b6470f27/pkg/sql/catalog/descs/hydrate.go#L268)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What would happen if we always got an immutable type here with `AvoidLeased`? I have a feeling that the choice to get a `Mutable` type here is vestigial. I'd be curious to learn if anything breaks. I think always resolving an immutable here would be strictly better if it doesn't cause any problems.
</blockquote></details>

yes, I believe getting an immutable with `AvoidLeased` will work here since we just want the fresh metadata and not really mutate anything. I'll make the change.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85874)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[`pkg/sql/information_schema.go` line 1594 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xmPHB5Ahqvk4rUd2:-N9CRh4nAOgkZBF__4_n:b-zb9tby) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d4251f404153be02e19be725f956a96000ff2cd/pkg/sql/information_schema.go#L1594)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Yes, I'll file one.
</blockquote></details>

oh, I don't need to file one, I'll reuse the existing issue: https://github.com/cockroachdb/cockroach/issues/84297
___
*[`pkg/sql/catalog/descs/hydrate.go` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-N99xNAQBtnphsnLTIH4:-N9CRoa-4ty1Y4c5HSPi:bmcqek7) ([raw file](https://github.com/cockroachdb/cockroach/blob/833e6bc9516190d59610de636a1f88e9b6470f27/pkg/sql/catalog/descs/hydrate.go#L268)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yes, I believe getting an immutable with `AvoidLeased` will work here since we just want the fresh metadata and not really mutate anything. I'll make the change.
</blockquote></details>

changed it to always get a fresh immutable, also changed to get immutbale db and schema.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85874#-:-N9CVptk2z9sqOa0S9Lh:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r=ajwerner

**Comment by chengxiong-ruan** [comment]
🙏 
bors r+

**Pull request merged**
