### PR TITLE
cli: pass fake StoreSpec in mt start-sql

### LINKED ISSUE #69920: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3411578&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3411578&tab=artifacts#/multitenant-upgrade) on master @ [642e44afbe6098f25022618be76c6f7b6b97df45](https://github.com/cockroachdb/cockroach/commits/642e44afbe6098f25022618be76c6f7b6b97df45):

```
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1991
		  | main.(*clusterImpl).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1970
		  | main.(*clusterImpl).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1891
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:84
		  | runtime.gopanic
		  | 	/usr/local/go/src/runtime/panic.go:965
		  | main.(*testImpl).fatalfInner
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:284
		  | main.(*testImpl).Fatal
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:259
		  | main.(*clusterImpl).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1893
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:84
		  | runtime.gopanic
		  | 	/usr/local/go/src/runtime/panic.go:965
		  | main.(*testImpl).fatalfInner
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:284
		  | main.(*testImpl).Fatal
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:259
		  | main.(*clusterImpl).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1893
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tenantNode).stop
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:84
		  | runtime.gopanic
		  | 	/usr/local/go/src/runtime/panic.go:965
		  | main.(*testImpl).fatalfInner
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:284
		  | main.(*testImpl).Fatalf
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_impl.go:264
		  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:59
		  | github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41
		  | github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).CheckQueryResultsRetry
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:222
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runMultiTenantUpgrade
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:323
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerMultiTenantUpgrade.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/multitenant_upgrade.go:39
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (4) cluster.RunL
		Wraps: (5) context canceled
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *errors.errorString
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by tbg**
In #71040 we added disk spilling which in particular added the following
call to the `mt start-sql` code path:

https://github.com/cockroachdb/cockroach/blob/af5a5a5065ce80c5e6568b4b422bf5c3a179e173/pkg/cli/mt_start_sql.go#L90-L89

The tenant doesn't support the `--store` flag, and so this will always
be the default of `cockroach-data`.

This has the unfortunate effect of trying to clean up the temp dirs for
that directory, even if `--temp-dir` is supplied:

https://github.com/cockroachdb/cockroach/blob/6999e5fded43f59eb5839dc8b943fd1e2a33a3fd/pkg/cli/start.go#L223-L227

In the `multitenant-upgrade` roachtest, as it happens there was actually
a cockroach host instance running under `cockroach-data`, and so the
tenant would fail to try to remove its (locked) temp dirs.

This commit fixes that issue by making start-sql use an in-memory store
spec. This fixes the test flake, but I wonder if the temp storage
feature for tenants is working properly. I worry about this because
the concept of a "temp engine" always seems to require a store:

https://github.com/cockroachdb/cockroach/blob/6999e5fded43f59eb5839dc8b943fd1e2a33a3fd/pkg/cli/start.go#L274-L280

and I am not sure how deep this goes. Frankly I don't understand why
if you are providing a Path you also need to provide a StoreSpec. I
will leave untangling this to @knz and @jaylim-crl, who know this
code better than I do.

Fixes #69920.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@jaylim-crl mind reviewing this since @knz is out until Oct 18th?

**Review by jaylim-crl — COMMENTED** [review]
> The tenant doesn't support the --store flag, and so this will always
be the default of cockroach-data.

How come the tenant doesn't support the --store flag? I remember testing this once, and it seems to work as intended :thinking: https://github.com/cockroachdb/cockroach/pull/71040#pullrequestreview-769547039. I believe I was using the default path though. 

We want to configure SQL to spill to ephemeral disk, and if we change it to an in-memory temp storage, then we can't use the disk.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71591#-:-Mm-jKCCBvJl3dqsUumK:bj5axi9)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jaylim-crl — COMMENTED** [review]
The PR you linked above added the `--store` flag support to `mt start-sql`. If we want an in-memory store, we can start the tenant with `--store=type=mem,size=640MiB`. I'll look into this again to verify.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71591#-:-Mm-ltJK2whtfFyT93Zu:bdt65pr)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jaylim-crl — COMMENTED** [review]
`--store` works for me:

```
/cockroach/cockroach mt start-sql --log-config-file ... --certs-dir ... --kv-addrs ... --tenant-id .. --sql-addr ... --store path=/cockroach/foobarbaz,size=2GB --max-sql-memory 30%
```

In the tenant pod:

```
[root@...-default-776fc68c8d-kcvsx cockroach]# ls
cockroach  ...  foobarbaz  goroutine_dump  heap_profiler  inflight_trace_dump	...
[root@...-default-776fc68c8d-kcvsx cockroach]# cd foobarbaz
[root@...-default-776fc68c8d-kcvsx foobarbaz]# ls
cockroach-temp041936600  temp-dirs-record.txt
[root@...-default-776fc68c8d-kcvsx foobarbaz]# pwd
/cockroach/foobarbaz
[root@...-default-776fc68c8d-kcvsx foobarbaz]# cd cockroach-temp041936600/
[root@...-default-776fc68c8d-kcvsx cockroach-temp041936600]# ls
000002.log  CURRENT  LOCK  MANIFEST-000001  OPTIONS-000003  TEMP_DIR.LOCK  auxiliary
```

Could we update the tests to supply an explicit `--store` instead?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71591#-:-Mm0wGqbCzmLyZ29rdRx:b-c2en0b)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request closed without merging**
