### PR TITLE
geogfn: implement ST_Azimuth and correct angle normalization

### PR DESCRIPTION
**Pull request by otan**
* Implement ST_Azimuth
* Correct angle normalization of lat/lng - these were previously
  incorrect as they clipped the wrong ends.

Release note (sql change): Implement the ST_Azimuth functionality for
the geography operator.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50708)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/math.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-IML0km6COcRrmQn:-MAy-IML0km6COcRrmQo:bf3l22x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L15)):*
> ```Go
> import "math"
> 
> // NormalizeLatitudeDegrees normalizes latitudes to the range [-90, 90].
> ```

What is the meaning of a latitude value of say 150 and 200? For longitude I understand one continues to wrap around. It seems it is the same for latitude but I want to confirm. A function comment with a couple of examples would also help.
___
*[pkg/geo/math.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy12R86IGijvaxHVCA:-MAy12R86IGijvaxHVCB:b-2eg8hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L17)):*
> ```Go
> // NormalizeLatitudeDegrees normalizes latitudes to the range [-90, 90].
> func NormalizeLatitudeDegrees(lat float64) float64 {
> 	lat = math.Remainder(lat, 360)
> ```

can you add a comment that this call to  math.Remainder returns a value in the interval [-180, 180]. It wasn't obvious from reading the documentation for Remainder -- I had to try it out.
___
*[pkg/geo/math.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-aa00T-lFT9YTNBa:-MAy-aa00T-lFT9YTNBb:b-7skvi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L27)):*
> ```Go
> }
> 
> // NormalizeLongitudeDegrees normalizes lnggitude to the range [-180, 180].
> ```

s/lnggitude/longitude/
___
*[pkg/geo/geogfn/azimuth.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzunb59sNcnoInruAG:-MAzunb59sNcnoInruAH:bb9dher) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geogfn/azimuth.go#L61)):*
> ```Go
> 	}
> 
> 	_, ret, _ := s.Inverse(
> ```

Can you do s/ret/azimuth/ or az1 to make it clear that this return value is an azimuth.
I'm not sure about the comment in `geographiclib.go` that says ` az1 (azimuth to point 1) `. IIUC, `az1` is the azimuth at point 1 which means it is the azimuth to go to point 2 as observed at point 1. The notion of azimuth is still confusing to me, including the fact that it seems to change as you traverse along the line.
___
*[pkg/geo/geogfn/azimuth_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzvm1V0Js-zCLgHCfU:-MAzvm1WEQ7TE0wfgXTF:b-67r663) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geogfn/azimuth_test.go#L22)):*
> ```Go
> 
> func TestAzimuth(t *testing.T) {
> 	testCases := []struct {
> ```

Can you label these cases as north-east, east, south-east, north. And can you add a couple of real cases, like the airport example here https://gis.stackexchange.com/questions/292558/how-is-st-azimuth-in-postgis-calculated
___
*[pkg/geo/geomfn/azimuth.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzx8491TDGWo_Vy55f:-MAzx8491TDGWo_Vy55g:b-soju27) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L21)):*
> ```Go
> )
> 
> // Azimuth returns the azimuth in radians of the segment defined by the given point geometries.
> ```

Could you make this a longer comment, such as

Azimuth returns the azimuth in radians of the segment defined by the given point geometries, where point a is the reference point. The reference direction from which the azimuth is calculated is north, and is positive clockwise.
North = 0; ...
See https://en.wikipedia.org/wiki/Polar_coordinate_system
___
*[pkg/geo/geomfn/azimuth.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzzpjm0deYqF7pwLVP:-MAzzpjm0deYqF7pwLVQ:by9v0e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L55)):*
> ```Go
> 	}
> 
> 	atan := math.Atan2(bPoint.Y()-aPoint.Y(), bPoint.X()-aPoint.X())
> ```

This could use a longer comment, and I'm not sure I understand the direction adjustment.
- 2 * Pi is just a full rotation, to make it positive, so that makes sense
- If y > 0 and x = 0, atan is Pi/2, I think. So north is Pi/2 while we want it to be 0. Doesn't that mean we should add 3*Pi/2. Or is there a CCW to CW compensation I am missing?
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB-0Xoq9Z38avitfJa7:-MB-0Xoq9Z38avitfJa8:b6mv6fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
> ```
> 	degrees(ST_Azimuth(ST_Point(75, 100)::geography, ST_Point(25, 45)::geography)) AS degB_A
> ----
> NaN  NaN
> ```

These are different points so why are these NaNs?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50708)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/math.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-IML0km6COcRrmQn:-MB-WSpL0EGci939z6F7:bk73etu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L15)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What is the meaning of a latitude value of say 150 and 200? For longitude I understand one continues to wrap around. It seems it is the same for latitude but I want to confirm. A function comment with a couple of examples would also help.
</blockquote></details>

Latitude wraps at 90 degrees, but in a different way, i.e. 89, 90, 89, 88, .... 0 .... -89, -90, -89, ... 0 ...
This is because of the way we cut the sphere into a triangle, in which the top ends up "on the other side" of ethe earth.
___
*[pkg/geo/math.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy12R86IGijvaxHVCA:-MB-X-AxEIq93OdYzg68:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L17)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment that this call to  math.Remainder returns a value in the interval [-180, 180]. It wasn't obvious from reading the documentation for Remainder -- I had to try it out.
</blockquote></details>

Done.
___
*[pkg/geo/math.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-aa00T-lFT9YTNBa:-MB-X-PX3grXSLVLvMTB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L27)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/lnggitude/longitude/
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/azimuth.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzunb59sNcnoInruAG:-MB-XTZRDd6hidIpR8e_:b-dw4c3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geogfn/azimuth.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you do s/ret/azimuth/ or az1 to make it clear that this return value is an azimuth.
I'm not sure about the comment in `geographiclib.go` that says ` az1 (azimuth to point 1) `. IIUC, `az1` is the azimuth at point 1 which means it is the azimuth to go to point 2 as observed at point 1. The notion of azimuth is still confusing to me, including the fact that it seems to change as you traverse along the line.

</blockquote></details>

fixed the comment in geographiclib.go to be the same as geod_inverse.
___
*[pkg/geo/geogfn/azimuth_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzvm1V0Js-zCLgHCfU:-MB-XnHIEEPvSigVxlNe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geogfn/azimuth_test.go#L22)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you label these cases as north-east, east, south-east, north. And can you add a couple of real cases, like the airport example here https://gis.stackexchange.com/questions/292558/how-is-st-azimuth-in-postgis-calculated
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/azimuth.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzx8491TDGWo_Vy55f:-MB-XxsnCwJ9NO4jdJ0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you make this a longer comment, such as

Azimuth returns the azimuth in radians of the segment defined by the given point geometries, where point a is the reference point. The reference direction from which the azimuth is calculated is north, and is positive clockwise.
North = 0; ...
See https://en.wikipedia.org/wiki/Polar_coordinate_system

</blockquote></details>

Done.
___
*[pkg/geo/geomfn/azimuth.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzzpjm0deYqF7pwLVP:-MB-YYS25LLjTNd5j3gf:b-mfhx16) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This could use a longer comment, and I'm not sure I understand the direction adjustment.
- 2 * Pi is just a full rotation, to make it positive, so that makes sense
- If y > 0 and x = 0, atan is Pi/2, I think. So north is Pi/2 while we want it to be 0. Doesn't that mean we should add 3*Pi/2. Or is there a CCW to CW compensation I am missing?
</blockquote></details>

i think the 3*pi/2 method is the opposite direction to what you want.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB-0Xoq9Z38avitfJa7:-MB-YceX9yul2mZ9POdX:bqqowip) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

These are different points so why are these NaNs?
</blockquote></details>

because 100 degrees latitude doesn't make sense. this will be fixed by #50219

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB-0Xoq9Z38avitfJa7:-MB-Yw6o1sJEmR0lHOnb:b-6fa2kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

because 100 degrees latitude doesn't make sense. this will be fixed by #50219
</blockquote></details>

(updated the numbers)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50708)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geogfn/azimuth_test.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB0lKKT2capoK-4x3-B:-MB0lKKT2capoK-4x3-C:b-gzfrkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/da922fc85c766830d6c55a17d8f901ef39711691/pkg/geo/geogfn/azimuth_test.go#L41)):*
> ```Go
> 		},
> 		{
> 			"south west",
> ```

south east?
___
*[pkg/geo/geomfn/azimuth.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzzpjm0deYqF7pwLVP:-MB0mK4y56r0kIIqphaH:bv8j4fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L55)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think the 3*pi/2 method is the opposite direction to what you want.
</blockquote></details>

I didn't notice that it was subtracting `atan` -- it is indeed the CCW to CW transformation. The atan computation gives us
E = 0, N = π/2, W = π, S = 3π/2. which is going CCW. By subtracting from 2.5 π, we get
E = 2.5π, N = 2π, W = 1.5π , S = π, which after the mod is what we want.

A longer code comment which includes the above would be helpful for future readers.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB0nfb22-o4DIjNQAnd:-MB0nfb22-o4DIjNQAne:b-r6tfzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da922fc85c766830d6c55a17d8f901ef39711691/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
> ```
> 	degrees(ST_Azimuth(ST_Point(75, 90)::geography, ST_Point(25, 45)::geography)) AS degB_A
> ----
> 0  -130
> ```

these points have a different longitude, so why is one of the azimuths 0? Wouldn't it be 0 only if one point was north of the other?
___
*[pkg/geo/math.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-IML0km6COcRrmQn:-MB0kMqU1xPZHVXRCzw6:b-b31oi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L15)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Latitude wraps at 90 degrees, but in a different way, i.e. 89, 90, 89, 88, .... 0 .... -89, -90, -89, ... 0 ...
This is because of the way we cut the sphere into a triangle, in which the top ends up "on the other side" of ethe earth.
</blockquote></details>

Are we cutting the sphere? Isn't `NormalizeLatitudeDegrees(120) = 60` so we are just wrapping around the poles, just like longitude wraps around the prime meridian. Am I missing something?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50708)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geogfn/azimuth_test.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB0lKKT2capoK-4x3-B:-MB0qFTYBa0HXQnUD5nH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da922fc85c766830d6c55a17d8f901ef39711691/pkg/geo/geogfn/azimuth_test.go#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

south east?
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/azimuth.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAzzpjm0deYqF7pwLVP:-MB0rPOG1LDT51fj78G0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/geomfn/azimuth.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't notice that it was subtracting `atan` -- it is indeed the CCW to CW transformation. The atan computation gives us
E = 0, N = π/2, W = π, S = 3π/2. which is going CCW. By subtracting from 2.5 π, we get
E = 2.5π, N = 2π, W = 1.5π , S = π, which after the mod is what we want.

A longer code comment which includes the above would be helpful for future readers.

</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB0nfb22-o4DIjNQAnd:-MB0r1bs8AJzC9zDJZ4l:btj7v9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/da922fc85c766830d6c55a17d8f901ef39711691/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

these points have a different longitude, so why is one of the azimuths 0? Wouldn't it be 0 only if one point was north of the other?
</blockquote></details>

We're at the north pole at latitude 90 :) everything is north!
___
*[pkg/geo/math.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MAy-IML0km6COcRrmQn:-MB0pR4g711JHe3M4hXt:b-j3tv8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a6789345956d63560210b3522eec2fed75fbc3/pkg/geo/math.go#L15)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are we cutting the sphere? Isn't `NormalizeLatitudeDegrees(120) = 60` so we are just wrapping around the poles, just like longitude wraps around the prime meridian. Am I missing something?
</blockquote></details>

Longitude doesn't really wrap the same way though. Longitude wraps as 178, 179, 180, -179, -178.... compared to Latitude which is 88, 89, 90, 99, 98 as you traverse the poles.

In a sense, I get what you mean - we are "cutting" the sphere by making it walk back from 120 -> 60, but this is what PostGIS does:
```
otan=# select st_astext(st_point(100, 100)::geography);
NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY
   st_astext
---------------
 POINT(100 80)
(1 row)
```

`100, 100` probably makes more sense as `80, -100` when "normalized" together, but that's not what PostGIS does.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-:-MB10FgP96yKEjXtyZq5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 2535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50708#-MB0nfb22-o4DIjNQAnd:-MB109kZ6-m2DUvm2aoq:bheya57) ([raw file](https://github.com/cockroachdb/cockroach/blob/da922fc85c766830d6c55a17d8f901ef39711691/pkg/sql/logictest/testdata/logic_test/geospatial#L2535)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

We're at the north pole at latitude 90 :) everything is north!
</blockquote></details>

ah yes.

**Comment by otan** [comment]
tftr!

bors r=sumeerbhola

**Pull request merged**
