### PR TITLE
sql: add max_prepared_transactions variable

### PR DESCRIPTION
**Pull request by nvb**
Informs #22329.

This commit adds the `max_prepared_transactions` session variable, returning a value of math.MaxInt32 to indicate that there is no limit on the number of prepared transactions that can be created.

This change has the effect of unblocking the pgjdbc `XADataSourceTest` test suite, which was previously failing during initialization. Is also includes a small patch to work around #31632 (unsupported deferrable qualifier) so that each test in the XA test suite actually runs (and fails, for the most part).

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I manually confirmed that this still passes the `pgjdbc` roachtest after the rebase.

**Review by rafiss — APPROVED** [review]
very nice to get more free testing; nice find

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129295#-:-ODte_qEEkqfFovgHfeK:b-fkrc0v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=rafiss

**Comment by nvanbenschoten** [comment]
bors retry

**Comment by nvanbenschoten** [comment]
EngFlow issues this morning.

bors retry

**Pull request merged**
