### PR TITLE
changefeedccl: update aws kafka package to fix aws-sdk-go-v2 issue

### LINKED ISSUE #131068: roachtest: cdc/kafka-auth-msk failed
roachtest.cdc/kafka-auth-msk [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16965666?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/16965666?buildTab=artifacts#/cdc/kafka-auth-msk) on master @ [c6122f6e6f0d35249a5eef8cab22db49dc43a626](https://github.com/cockroachdb/cockroach/commits/c6122f6e6f0d35249a5eef8cab22db49dc43a626):

```
(cdc.go:3697).MakeCluster: failed to create msk serverless cluster: not found, ResolveEndpointV2
test artifacts and logs in: /artifacts/cdc/kafka-auth-msk/cpu_arch=arm64/run_1
```

Parameters:
 - <code>ROACHTEST_arch=arm64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_runtimeAssertionsBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-auth-msk.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-42352

### PR DESCRIPTION
**Pull request by asg0451**
There's a version mismatch between the
aws-sdk-go-v2 core and kafka packages that's
affecting the msk roachtest.

Fixes: #131068

Release note: none

### CODE REVIEW

**Review by wenyihu6 — APPROVED** [review]
What's our preferred ways for upgrades? Do we want to check commits inbetween?

**Comment by asg0451** [comment]
> What's our preferred ways for upgrades? Do we want to check commits inbetween?

maybe we can do changelog diffs, yeah. however in this case it's fine since this is used only in roachtests, and was just introduced at that.

**Comment by asg0451** [comment]
bors r=wenyihu6

**Comment by asg0451** [comment]
bors r=wenyihu6

**Pull request merged**
