### PR TITLE
ui: some jobs page fixes

### PR DESCRIPTION
**Pull request by benesch**
/cc @mrtracy @couchand

### CODE REVIEW

**Comment by benesch** [comment]
Sigh, embedded.go. /cc @mrtracy @couchand

**Comment by couchand** [comment]
Seems like pausing jobs will aggravate the potential estimate inaccuracy concern I raised on the other PR, but it's probably fine I guess.

:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/styl/pages/jobs.styl, line 4 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17559#-KrByv8c6oYl9suJz3TH:-KrByv8c6oYl9suJz3TI:bf5tseq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a60d1f9009640004d216d0e60e0276d76a18afb/pkg/ui/styl/pages/jobs.styl#L4)):*
> ```Stylus
>   &__row
>     &--paused .rc-progress-line-path
>       stroke $tooltip-color
> ```

This seems just a little odd here.  Perhaps an alias should be added for this purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17559#-:-KrBzE5ZJt0RCii8CtyM:betisqz)*

**Comment by benesch** [comment]
Yup, agreed. We may want to keep track of `paused_duration` in the future.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/styl/pages/jobs.styl, line 4 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17559#-KrByv8c6oYl9suJz3TH:-KrC0r-U6cJ-Vpg4Af2-:by0tkxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a60d1f9009640004d216d0e60e0276d76a18afb/pkg/ui/styl/pages/jobs.styl#L4)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

This seems just a little odd here.  Perhaps an alias should be added for this purpose?
</blockquote></details>

Yeah, I agree, but @mrtracy was worried about color proliferation in the last PR. Are aliases kosher?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17559#-:-KrC0kceLAhjSjqoLNdI:b82d450)*

**Comment by benesch** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/17576 to track the aliases issue; going to merge while this is green to avoid the massive headache of embedded.go.

**Pull request merged**
