### PR TITLE
opt: Add support for views

### PR DESCRIPTION
**Pull request by andy-kimball**
Allow views to be used as a data source in addition to tables. Generalize
Catalog interface to resolve data sources rather than just tables. Separate
out privilege checking so that it can be better controlled by optbuilder.
If selecting from a view, we want to check SELECT privilege on the view,
and not on the underlying table(s).

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: 

Very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-:-LJitNz3AIj_YkkI4eQF:b-5u1ooj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/catalog.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJd80J_CO_tDiOwBt4p:-LJd80JaENwvo0hQg24F:bq6v3p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f6973ea332ca1ffc74f0e4ef5e29524207eae7a/pkg/sql/opt/catalog.go#L118)):*
> ```Go
> 
> 	// ColumnNameCount returns the number of column names specified in the view.
> 	// Note that this can be zero, even if the view itself returns multiple
> ```

[nit] This was a bit confusing, when I first read it it seemed to allow cases where some of the columns are aliased. I would mention that the number matches the columns returned by the view, or it is 0 if the columns are not aliased.
___
*[pkg/sql/opt/optbuilder/select.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJisKSI5GC53u5qo93v:-LJisKSI5GC53u5qo93w:b-999ioh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f6973ea332ca1ffc74f0e4ef5e29524207eae7a/pkg/sql/opt/optbuilder/select.go#L118)):*
> ```Go
> // buildView parses the view query text and builds it as a Select expression.
> func (b *Builder) buildView(view opt.View, inScope *scope) (outScope *scope) {
> 	// Cache parsed text so that multiple references won't need to reparse.
> ```

[nit] Cache the AST

**Review by rytaft — DISMISSED** [review]
:lgtm: great stuff!

> Reviewed 23 of 28 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-:-LJnpEyJ4tMS1pbqur1t:b-nihnxt)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt_catalog.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnflBkEbowi0HxLdW4:-LJnflBkEbowi0HxLdW5:bcil938) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L83)):*
> ```Go
> 	}
> 
> 	if err := filterTableState(desc); err != nil {
> ```

Should this call be moved to `newDataSource` so it gets checked for all data sources?
___
*[pkg/sql/opt_catalog.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJngLsE6lbTjxnZiZuy:-LJngLsE6lbTjxnZiZuz:b-pvwmac) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L118)):*
> ```Go
> 	} else {
> 		if !desc.IsSequence() {
> 			panic(fmt.Sprintf("unexpected table descriptor: %+v", desc))
> ```

[nit] I think this might be a little more idiomatic if you change it to the following:

```
if desc.IsTable() {
  ds = newOptTable(oc, desc, name, oc.statsCache)
} else if desc.IsView() {
  ds = newOptView(oc, desc, name)
} else if desc.IsSequence() {
  ds = newOptSequence(oc, desc, name)
} else {
  panic(fmt.Sprintf("unexpected table descriptor: %+v", desc))
}
		
```
___
*[pkg/sql/opt_catalog.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnhqDpD8DPFowBVIQo:-LJnhqDpD8DPFowBVIQp:bxjyu17) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L138)):*
> ```Go
> }
> 
> var _ opt.View = &optView{}
> ```

Should you also add `var _ opt.DataSource = &optView{}`?
___
*[pkg/sql/opt_catalog.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJni9Js2qU0giLlVBCa:-LJni9Js2qU0giLlVBCb:b-r14p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L176)):*
> ```Go
> 
> // optSequence is a wrapper around sqlbase.TableDescriptor that implements the
> // opt.DataSource interface.
> ```

does it also implement `opt.Sequence`? (You reference that below... maybe at least add a TODO since opt.Sequence doesn't exist yet)
___
*[pkg/sql/opt_catalog.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnpRu9Av_Zq7xQ8SEv:-LJnpRu9Av_Zq7xQ8SEw:b-oj60ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L238)):*
> ```Go
> }
> 
> var _ opt.Table = &optTable{}
> ```

Should you also add `var _ opt.DataSource = &optTable{}`?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28464)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnflBkEbowi0HxLdW4:-LJo84YR4KooQL9e1sN5:b-mt3h36) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L83)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this call be moved to `newDataSource` so it gets checked for all data sources?
</blockquote></details>

My understanding was that only in the `ById` case are these errors possible. In the regular name lookup case, we'd just get back a `relation "a" does not exist` sort of error if the table was being dropped (see `drop_table` logic test for example).
___
*[pkg/sql/opt_catalog.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJngLsE6lbTjxnZiZuy:-LJo6w3573XeeEOhYY4v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L118)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think this might be a little more idiomatic if you change it to the following:

```
if desc.IsTable() {
  ds = newOptTable(oc, desc, name, oc.statsCache)
} else if desc.IsView() {
  ds = newOptView(oc, desc, name)
} else if desc.IsSequence() {
  ds = newOptSequence(oc, desc, name)
} else {
  panic(fmt.Sprintf("unexpected table descriptor: %+v", desc))
}
		
```
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnhqDpD8DPFowBVIQo:-LJo71up7ZKOq94o1nFW:b-5funy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L138)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should you also add `var _ opt.DataSource = &optView{}`?
</blockquote></details>

`View` already includes `DataSource`, so we should already get error if we don't implement everything:
```
type View interface {
	DataSource
```
___
*[pkg/sql/opt_catalog.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJni9Js2qU0giLlVBCa:-LJo7VO1BLS5PXyo6mJl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L176)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

does it also implement `opt.Sequence`? (You reference that below... maybe at least add a TODO since opt.Sequence doesn't exist yet)
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28464#-LJnpRu9Av_Zq7xQ8SEv:-LJo7WUiEVsOPPddFDaa:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab26d016a4424e685f65afeda61f34b6469c514/pkg/sql/opt_catalog.go#L238)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should you also add `var _ opt.DataSource = &optTable{}`?
</blockquote></details>

See above.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28464)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
