### PR TITLE
kvserver: fix race in rangefeed processor setup

### LINKED ISSUE #53183: kv/kvnemesis: TestApplier failed
[(kv/kvnemesis).TestApplier failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2206464&tab=buildLog) on [master@991a05367d38ca32c1f6584e56143ac65270afc8](https://github.com/cockroachdb/cockroach/commits/991a05367d38ca32c1f6584e56143ac65270afc8):

```
  github.com/cockroachdb/cockroach/pkg/server.(*Node).RangeFeed()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:986 +0x78
  github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.RangeFeed.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:595 +0xf8

Previous write at 0x00c0015341d0 by goroutine 235:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).RangeFeed.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_rangefeed.go:214 +0x207
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).maybeRunCatchupScan()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:286 +0xa1
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).outputLoop()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:235 +0x53
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).runOutputLoop()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:271 +0x122
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).run.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:240 +0x7e
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x162

Goroutine 295 (running) created at:
  github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.RangeFeed()
      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:593 +0x134
  github.com/cockroachdb/cockroach/pkg/rpc.(*internalClientAdapter).RangeFeed()
      <autogenerated>:1 +0xd9
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).singleRangeFeed()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:257 +0x5b1
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).partialRangeFeed()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:150 +0x3d6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeed.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:69 +0x7c
  github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x4e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x71

Goroutine 235 (finished) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:342 +0x14a
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).run()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:246 +0x15f6
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).Start.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:177 +0x67
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:347 +0x162
==================
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestApplier657779867
--- FAIL: TestApplier (1.15s)
    test_log_scope.go:154: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestApplier657779867
    test_log_scope.go:63: use -show-logs to present logs inline
    testing.go:853: race detected during execution of test

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=2

```
make stressrace TESTS=TestApplier PKG=./pkg/kv/kvnemesis TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestApplier.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #53183

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Actually this doesn't totally work.

**Comment by ajwerner** [comment]
Okay, this is RFAL

**Review by nvb — COMMENTED** [review]
Isn't this changing the semantics of the cleanup function? Before, the semaphore would be released when the iterator was closed. Now, it's released when the registration is canceled. Maybe we could use a `sync.Once` with the existing `iteratorWithCloser` structure to avoid needing to pass a new variable through the registration?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-:-MFTWJAED72MnudNlFd6:bdphdih)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-MFTVo3j23fzdu44Egh1:-MFTVo3k-QYH2WaAN5gH:b-hy5v94) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f64083c2191d748ff091d8a450fec548ae8ed06/pkg/kv/kvserver/replica_rangefeed.go#L204)):*
> ```
> maybeDisconnectEmptyRangefeed
> ```

Want to remove the `p == nil` handling from this function now?
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-MFTVwmJ654VHZiOBMlr:-MFTVwmKD-sujhOVEeEz:bc3ewev) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f64083c2191d748ff091d8a450fec548ae8ed06/pkg/kv/kvserver/replica_rangefeed.go#L295)):*
> ```Go
> 	p := r.rangefeedMu.proc
> 	if p != nil {
> 		reg, filter := p.Register(span, startTS, catchupIter, nil, withDiff, stream, errC)
> ```

Shouldn't we be passing `cleanup` here? And down below?
___
*[pkg/kv/kvserver/rangefeed/processor.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-MFTW3HS6anCC4fSD1rV:-MFTW3HS6anCC4fSD1rW:b-4oeag9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f64083c2191d748ff091d8a450fec548ae8ed06/pkg/kv/kvserver/rangefeed/processor.go#L361)):*
> ```Go
> // provided an error when the registration closes.
> //
> // If the rangefeed is successfully registered (true is returned), the
> ```

Both of these new sentences need a bit of love. This one is missing punctuation and the other is truncated.

**Comment by ajwerner** [comment]
Yeah, the thought crossed my mind to just use a sync.Once. It's cleaner and simpler. RFAL

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-MFVrvkZ7BrFBcPPaUeq:-MFVrvkZ7BrFBcPPaUer:b-a0t28a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba37cce7ce6eb6fd37fcaca861a21b89ec78e29/pkg/kv/kvserver/replica_rangefeed.go#L176)):*
> ```Go
> 		// Finish the iterator limit if we exit before the iterator finishes.
> 		// The release function will be hooked into the Close method on the
> 		// iterator below. The sync.Once prevents any races.
> ```

Mind spelling out which races?
Also in the commit message pls give a hint that the race was on the `iterSemRelease` variable.
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-MFVtXJK0QZKHDVx-rhr:-MFVtXJK0QZKHDVx-rhs:b-idoypj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba37cce7ce6eb6fd37fcaca861a21b89ec78e29/pkg/kv/kvserver/replica_rangefeed.go#L177)):*
> ```Go
> 		// The release function will be hooked into the Close method on the
> 		// iterator below. The sync.Once prevents any races.
> 		var iterSemReleaseOnce sync.Once
> ```

I see that we have gotten to this `sync.Once` after something else has been tried so you can shut me up, but it seems to me that the control flow is simple enough that a `sync.Once` big hammer shouldn't be necessary; I think ownership of that rate semaphore token is clear. I'm thinking of turning `catchUpIterFunc` into a proper struct with a `Close()` that needs to be called by `Processor.Register` or delegated to the `iteratorWithCloser`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53295#-:-MFVvyXV6_fMqh0agobg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Comment by ajwerner** [comment]
> Mind spelling out which races?
Also in the commit message pls give a hint that the race was on the iterSemRelease variable.

Added more commentary around the call site and to the commit title. 

> I see that we have gotten to this sync.Once after something else has been tried so you can shut me up, but it seems to me that the control flow is simple enough that a sync.Once big hammer shouldn't be necessary; I think ownership of that rate semaphore token is clear. I'm thinking of turning catchUpIterFunc into a proper struct with a Close() that needs to be called by Processor.Register or delegated to the iteratorWithCloser.

@andreimatei be my guest but I'm going to merge this to unflake the tests. 

bors r=nvanbenschoten

**Pull request merged**
