### PR TITLE
descmetadata: do not use experimental setting

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: low-risk cleanup.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I don't quite understand why this was introduced in #83592 - am I missing something? The CI seems happy.

**Comment by fqazi** [comment]
The concern was if ExperimentalDistSQLPlanningAlways was somehow set inside the session, anything inheriting the session run with that. That could cause internal inserts from the metadata updater, etc.. to fail. This used to be a problem on logictest at one point

**Comment by yuzefovich** [comment]
I see. This would only be applicable to a couple of logic test files (that explicitly do `SET experimental_distsql_planning = always`), so I think it's not good that we create a copy of the session data in all cases, production including. I briefly stressed the relevant files with this PR and didn't see any flakes, so I think we should proceed with this change. If the flakes do happen, then we probably will need to add `RESET experimental_distsql_planning` to the end of those files.

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87288)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Review by fqazi — APPROVED** [review]
I'm okay with that approach, the onus should be on the tests themselves. We used to have a logictest mode that forced it in other cases I think

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87288#-:-NAuZqVQDQMZJ36HtgvC:boganqc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by yuzefovich** [comment]
We did have `-spec-planning` configs (which were removed like a month ago), but they were using `On` and not `Always` for this experimental setting.

**Pull request merged**
