### PR TITLE
sql: prevent REGIONAL BY ROW and ADD/DROP REGION concurrent transitions

### LINKED ISSUE #63368: sql: block ADD/DROP REGION during a REGIONAL BY ROW transition and vice versa
If we attempt to add or drop a region whilst a REGIONAL BY ROW is happening, the partitioning will be corrupted. A basic racy test shows the following:

```
--- FAIL: TestRegionChangeDuringAlterTableRegionalByRow (6.73s)
    --- FAIL: TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_GLOBAL_to_ALTER_TABLE_t.test_SET_LOCALITY_REGIONAL_BY_ROW_with_racing_ALTER_DATABASE_t_ADD_REGION_"us-east3" (1.91s)
        regional_by_row_test.go:248:
            	Error Trace:	regional_by_row_test.go:248
            	Error:      	Received unexpected error:
            	            	pq: internal error: relation "test" (55): invalid locality config: missing partition us-east3 on PRIMARY INDEX of table test
            	Test:       	TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_GLOBAL_to_ALTER_TABLE_t.test_SET_LOCALITY_REGIONAL_BY_ROW_with_racing_ALTER_DATABASE_t_ADD_REGION_"us-east3"
    --- FAIL: TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_GLOBAL_to_ALTER_TABLE_t.test_SET_LOCALITY_REGIONAL_BY_ROW_with_racing_ALTER_DATABASE_t_DROP_REGION_"us-east2" (1.79s)
        regional_by_row_test.go:248:
            	Error Trace:	regional_by_row_test.go:248
            	Error:      	Received unexpected error:
            	            	pq: internal error: verify-idx-count: while decoding partition tuple: decoding: could not find [128] in enum "public.crdb_internal_region" representation PhysicalReps: [[64]]; LogicalReps: [us-east1]
            	Test:       	TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_GLOBAL_to_ALTER_TABLE_t.test_SET_LOCALITY_REGIONAL_BY_ROW_with_racing_ALTER_DATABASE_t_DROP_REGION_"us-east2"
    --- FAIL: TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_REGIONAL_BY_ROW_to_ALTER_TABLE_t.test_SET_LOCALITY_GLOBAL_with_racing_ALTER_DATABASE_t_ADD_REGION_"us-east3" (1.60s)
        regional_by_row_test.go:249:
            	Error Trace:	regional_by_row_test.go:249
            	Error:      	Received unexpected error:
            	            	pq: superfluous data in encoded value
            	Test:       	TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_REGIONAL_BY_ROW_to_ALTER_TABLE_t.test_SET_LOCALITY_GLOBAL_with_racing_ALTER_DATABASE_t_ADD_REGION_"us-east3"
    --- FAIL: TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_REGIONAL_BY_ROW_to_ALTER_TABLE_t.test_SET_LOCALITY_GLOBAL_with_racing_ALTER_DATABASE_t_DROP_REGION_"us-east2" (1.43s)
        regional_by_row_test.go:249:
            	Error Trace:	regional_by_row_test.go:249
            	Error:      	Received unexpected error:
            	            	pq: superfluous data in encoded value
            	Test:       	TestRegionChangeDuringAlterTableRegionalByRow/from_CREATE_TABLE_t.test_(k_INT_NOT_NULL,_v_INT)_LOCALITY_REGIONAL_BY_ROW_to_ALTER_TABLE_t.test_SET_LOCALITY_GLOBAL_with_racing_ALTER_DATABASE_t_DROP_REGION_"us-east2"
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl	7.908s
```

We probably need to block ADD/DROP REGION during a REGIONAL BY ROW transition and vice versa. I *think* there is / will be a similar problem with SURVIVE changes.

Marking as GA-blocker as I imagine this is an easy state to get into.

### LINKED ISSUE #63462: sql: concurrent ADD REGION, DROP REGION, (CREATE|ALTER) REGIONAL BY ROW combinations do not mix
Assume that a DROP REGION job fails. If we do not include regions that are being dropped in the SynthesizeRegionConfig during this state, a number of issues arise on REGIONAL BY ROW tables in their given callsites, such as:
* New REGIONAL BY ROW tables created will be missing the dropped region partition.
* alter to/from REGIONAL BY ROW will be missing partitions
* an active CREATE INDEX job on RBR tables may miss the dropped partition
* an active ALTER PRIMARY KEY job on may miss the dropped partition
* an active CREATE UNIQUE CONSTRAINT job will miss the dropped partition
* Partitioning validation is broken during a concurrent ADD/DROP REGION, as per discovery in #63459. This is because an add will repartition every table, but will discard the dropped region.

I've tried taking the tack of including DROPPING regions for these operations [here in the latter two commits](https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:synthesize_fix?expand=1), but unfortunately we hit the error that the enum is not PUBLIC on the repartition case.

We should probably block any REGIONAL BY ROW creating / altering behaviour if there is an ADD/DROP REGION underway (i.e. creating an index, unique constraint, create table ... regional by row, some already handled by #63368) and vice versa - this is the quickest and easiest way to unblock the release. Furthermore, it is probably worth prohibiting concurrent ADD/DROP regions as well - again to unblock the release.

### LINKED ISSUE #63974: sql: DROP INDEX failure with a sandwiched DROP REGION results in irrecoverable state
Consider this test, where:
* DROP INDEX starts
* DROP REGION intercepts and completes. All RBR partitions get repartitioned.
* DROP INDEX fails. no re-partitioning is done.

```go
// TestDropIndexFailureDuringAddOrDropRegion a DROP INDEX failing during
// ADD/DROP REGION, in which case the dropped index should still contain
// the new indexes.
func TestDropIndexFailureDuringAddOrDropRegion(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	defer sqltestutils.SetTestJobsAdoptInterval()()

	for _, tc := range []struct {
		regionChangeSQL    string
		expectedPartitions []string
	}{
		{
			regionChangeSQL:    `ALTER DATABASE db DROP REGION "us-east2"`,
			expectedPartitions: []string{"us-east1"},
		},
		{
			regionChangeSQL:    `ALTER DATABASE db ADD REGION "us-east3"`,
			expectedPartitions: []string{"us-east1", "us-east2", "us-east3"},
		},
	} {
		t.Run(tc.regionChangeSQL, func(t *testing.T) {
			block := false
			typeChangeFinished := make(chan struct{})
			knobs := base.TestingKnobs{
				SQLSchemaChanger: &sql.SchemaChangerTestingKnobs{
					RunBeforeBackfill: func() error {
						if block {
							block = false
							<-typeChangeFinished
							return errors.New("crikey!")
						}
						return nil
					},
				},
			}

			_, sqlDB, cleanup := multiregionccltestutils.TestingCreateMultiRegionCluster(
				t, 3 /* numServers */, knobs, nil, /* baseDir */
			)
			defer cleanup()

			_, err := sqlDB.Exec(`
DROP DATABASE IF EXISTS db;
CREATE DATABASE db WITH PRIMARY REGION "us-east1" REGIONS "us-east2";
CREATE TABLE db.rbr(k INT PRIMARY KEY, v INT NOT NULL, INDEX v_idx(v)) LOCALITY REGIONAL BY ROW;
`)
			require.NoError(t, err)

			block = true
			var wg sync.WaitGroup
			go func() {
				defer wg.Done()

				_, err := sqlDB.Exec(`DROP INDEX db.rbr@v_idx`)
				if err != nil {
					if !strings.Contains(err.Error(), "crikey!") {
						t.Errorf("failed to run drop index for unknown reason: %+v", err)
					}
				} else {
					t.Errorf("expected error during DROP INDEX")
				}
			}()
			wg.Add(1)

			_, err = sqlDB.Exec(tc.regionChangeSQL)
			close(typeChangeFinished)
			require.NoError(t, err)

			// Wait for DROP INDEX to complete.
			wg.Wait()

			require.NoError(
				t,
				validateIndexAndPartitions(
					sqlDB,
					"db.rbr",
					[]string{"rbr@primary", "rbr@v_idx"},
					tc.expectedPartitions,
				),
			)
		})
	}
}

func validateIndexAndPartitions(
	sqlDB *gosql.DB, tableName string, expectedIndexes []string, expectedPartitions []string,
) error {
	rows, err := sqlDB.Query(fmt.Sprintf(
		"SELECT index_name, partition_name FROM [SHOW PARTITIONS FROM TABLE %s] ORDER BY partition_name",
		tableName,
	))
	if err != nil {
		return err
	}
	defer rows.Close()

	indexPartitions := make(map[string][]string)
	for rows.Next() {
		var indexName string
		var partitionName string
		if err := rows.Scan(&indexName, &partitionName); err != nil {
			return err
		}

		indexPartitions[indexName] = append(indexPartitions[indexName], partitionName)
	}

	for _, expectedIndex := range expectedIndexes {
		partitions, found := indexPartitions[expectedIndex]
		if !found {
			return errors.AssertionFailedf("did not find index %s", expectedIndex)
		}

		if len(partitions) != len(expectedPartitions) {
			return errors.AssertionFailedf(
				"unexpected number of partitions; expected %d, found %d",
				len(partitions),
				len(expectedPartitions),
			)
		}
		for i, expectedPartition := range expectedPartitions {
			if expectedPartition != partitions[i] {
				return errors.AssertionFailedf(
					"unexpected partitions; expected %v, found %v",
					expectedPartitions,
					partitions,
				)
			}
		}
	}
	return nil

}
```

In this case, we have bad state - the index does not match the regions.

Originally I tried patching this in #63968, but it's broken in the case that if we transition from RBR to Global instead of drop index, the DROP REGION would also "accidentally" partition the global indexes -- then again, we already do that today and i think that's a bug that will fall our when arul tests it.

My suggested solution would be to repartition again during CREATE INDEX/DROP INDEX when the operation is complete. This is probably similar to arul's proposed work. Can take a stab at this tomorrow. Warrants a GA-blocker.

### LINKED ISSUE #64011: sql: ALTER TABLE ... SET (to/from) LOCALITY REGIONAL BY ROW is bound to fail when running concurrent REGION ADD/DROP operation
**Describe the problem**

Consider the following scenario:

```
setup:
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3"
CREATE TABLE db.t() SET LOCALITY REGIONAL;

steps:
Client 1: ALTER TABLE db.t SET LOCALITY REGIONAL BY ROW; <- block in the schema changer. 
Client 2: ALTER DATABASE db ADD "us-east4"; <- let type schema change finalize
Client 1:  Unblock ALTER TABLE schema change; // Bound to fail.
```

The issue arises from the fact that when we alter to a REGIONAL BY ROW table, we construct the partitioning in the user transaction. As such, the partitioning for the table `t` will not contain an entry for "us-east4". As this isn't refreshed in the schema changer, when we try to write the updated table descriptor back, it will fail validation which ensures that every RBR table has a partition for every (PUBLIC) region in the database. 

This means that an `ALTER TABLE ... SET LOCALITY TO REGIONAL BY ROW` is bound to fail if a REGION is added after the schema change is queued up but before it completes. As altering to a REGIONAL BY ROW table involves backfilling indexes, this window is non-trivial. 

The problem also exists if we replace the ADD REGION operation with a DROP REGION operation albeit for different reasons. This fails in the schema changer when we try to apply zone configurations on the new index -- as the region has been dropped, the enum value used in the partitioning is no longer present, which results in an error. Normally, partitioning would be negotiated when the REGION DROP is finalized. However, because the table's locality is set to REGIONAL BY ROW only _after_ the schema change completes, this doesn't happen. 

** Describe another problem **
```
setup:
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-east2", "us-east3"
CREATE TABLE db.t() SET LOCALITY REGIONAL BY ROW;

steps:
Client 1: ALTER TABLE db.t SET GLOBAL <- block in the schema changer. 
Client 2: ALTER DATABASE db ADD "us-east4"; <- let type schema change finalize
Client 1:  Unblock ALTER TABLE schema change;
```

in this case, the new primary index will have the partitions in db.t will have partitions "us-east1" through 4.

This is because we use `NonDropIndexes` when finalising. We can just use active indexes if we follow through with #63976

**Expected behavior**
The schema change should succeed. 

**Describe the solution you'd like**
We shouldn't be creating the partitioning in the user transaction. Instead, we should create it in the schema changer, right before we apply the zone configuration to the index. Currently, we apply the zone configuration before backfilling and after the schema change completes as well. We probably want to do the same with the index partitioning, as the list of active regions on the database can change between these two phases/might change when rolling back a failed ALTER from a REGIONAL BY ROW table.

**Additional context**
Related to #63462

### PR DESCRIPTION
**Pull request by otan**
see individual commits for details

resolves #63368
resolves #63462 
resolves #64011
resolves #63974

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZ9G8Az86oPORLP9rjZ:-MZ9G8Az86oPORLP9rj_:b-o7cklq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6329066894bdae25fcdfb32f44b9cc3bdd40c9dc/pkg/ccl/multiregionccl/region_test.go#L255)):*
> ```Go
> 		expectedIndexes []string
> 	}{
> 		{
> ```

Looks like this is only testing a CREATE REGIONAL BY ROW table now, so we can probably simplify this test a bit?
___
*[pkg/sql/region_util.go, line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZ9CUON-w4K7TtAadI5:-MZ9CUON-w4K7TtAadI6:bar701v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6841daafa997aa57812cf21997473eb3a6028c13/pkg/sql/region_util.go#L1697)):*
> ```Go
> 	// forEachTableDesc touches all the table keys, which prevents a race
> 	// with ADD/REGION committing at the same time as the user transaction.
> 	return forEachTableDesc(
> ```

`forEachTableDesc` is no good here, as it filters out descriptors the user doesn't have privileges on. You probably want `forEachMutableTableInDatabase` here instead.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/ccl/multiregionccl/region_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZ9G8Az86oPORLP9rjZ:-MZ9jJYL6vlYLM35HZyr:b-fi0grx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6329066894bdae25fcdfb32f44b9cc3bdd40c9dc/pkg/ccl/multiregionccl/region_test.go#L255)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Looks like this is only testing a CREATE REGIONAL BY ROW table now, so we can probably simplify this test a bit?
</blockquote></details>

i'd rather keep it, since it's easier to add cases if we find out we need them at a later point.
also, don't think the simplification makes it that much easier to read :P 
___
*[pkg/sql/region_util.go, line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZ9CUON-w4K7TtAadI5:-MZ9pUoPAVUQnkXZz84n:b-172con) ([raw file](https://github.com/cockroachdb/cockroach/blob/6841daafa997aa57812cf21997473eb3a6028c13/pkg/sql/region_util.go#L1697)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

`forEachTableDesc` is no good here, as it filters out descriptors the user doesn't have privileges on. You probably want `forEachMutableTableInDatabase` here instead.
</blockquote></details>

nice cathc, done

**Review by arulajmani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64117)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZ9G8Az86oPORLP9rjZ:-MZDYY8U3-gtUm7AX7oj:b1z7cr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6329066894bdae25fcdfb32f44b9cc3bdd40c9dc/pkg/ccl/multiregionccl/region_test.go#L255)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i'd rather keep it, since it's easier to add cases if we find out we need them at a later point.
also, don't think the simplification makes it that much easier to read :P 
</blockquote></details>

You have hope we'll need this at a later point after last week? haha, I'm fine keeping the structure as is, just update the comment above the test which explains why there's only one op so that readers aren't confused?
___
*[pkg/sql/region_util.go, line 1757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZDYJ9NC8uhufy5tv46:-MZDYJ9NC8uhufy5tv47:bwed7vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/15896ab82b11e967be9933ff181f88eda8e6fbde/pkg/sql/region_util.go#L1757)):*
> ```Go
> // database are currently being modified.
> func (p *planner) checkNoRegionChangeUnderway(
> 	ctx context.Context, dbID descpb.ID, op string,
> ```

nit: consider wrap the error at the call-site instead of passing in this op string?

**Review by ajstorm — APPROVED** [review]
:lgtm: minus the nits.  :tada: 

> Reviewed 12 of 12 files at r3, 4 of 4 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-:-MZEBD4J4saUWr0kvlyl:bkpyclg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 708 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZE7wYG8CB74btMOmS_:-MZE7wYH1nDJ0m2p5kAS:b-y6ty6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/ccl/multiregionccl/regional_by_row_test.go#L708)):*
> ```Go
> 	regionalByRowChanges := []struct {
> 		setup                          string
> 		alterCmd                       string
> ```

Nit: We might want to generalize the name of this, since some of the below operations aren't "ALTER"s.
___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 778 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZE8zWG7bUJwmXDpawK:-MZE8zWG7bUJwmXDpawL:b-deslcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/ccl/multiregionccl/regional_by_row_test.go#L778)):*
> ```Go
> 	for _, rbrChange := range regionalByRowChanges {
> 		for _, regionChange := range regionChanges {
> 			t.Run(fmt.Sprintf("from %s to %s with racing %s", rbrChange.setup, rbrChange.alterCmd, regionChange.cmd), func(t *testing.T) {
> ```

Nit: Should this be "statement %s with concurrent %s, racing with %s"?
___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 804 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZE9CrRDLY7j2GYeeb1:-MZE9CrRDLY7j2GYeeb2:ba5mbai) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/ccl/multiregionccl/regional_by_row_test.go#L804)):*
> ```Go
> 				setupDB(sqlDB, rbrChange.setup)
> 
> 				// Perform the alter table command asynchronously; this will be interrupted.
> ```

Nit: generalize alter table command?
___
*[pkg/sql/region_util.go, line 1710 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZEA74BBdR2XmzGqvAk:-MZEA74BBdR2XmzGqvAl:b5uxs4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/sql/region_util.go#L1710)):*
> ```Go
> 						detailSuffix,
> 					),
> 					"cancel the existing job or try again when the change is complete",
> ```

Nit: Any chance we can pull the job id for easier reference?
___
*[pkg/sql/region_util.go, line 1735 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZEAg2g1mRm7AwhrJ_k:-MZEAg2g1mRm7AwhrJ_l:ba1g5eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/sql/region_util.go#L1735)):*
> ```Go
> 			}
> 			// Disallow index changes for REGIONAL BY ROW tables.
> 			// We do this on the second loop, as index changes may be a precede to the actual PRIMARY KEY swap.
> ```

Nit: I think we can drop "be a" and "to".  What do you mean by "precede" here?  Might be good to provide a bit more context in this comment.

**Comment by ajstorm** [comment]
@otan just a heads-up that this is one of the last GA blockers needed for the RC that they're hoping to cut Tuesday (EDT).  Any chance we can get this in sometime before then?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64117)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/region_util.go, line 1710 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZEA74BBdR2XmzGqvAk:-MZElD_sCxagXptROJ8H:b-v8b0zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/758c98cf8421e302aa4855f86fde3be0de691fa7/pkg/sql/region_util.go#L1710)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Any chance we can pull the job id for easier reference?
</blockquote></details>

that is not straightforward, so i'm not doing that.
there's a bunch of TODOs all over the place to do this for other things.
___
*[pkg/sql/region_util.go, line 1757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64117#-MZDYJ9NC8uhufy5tv46:-MZEl0KV3R3bZMDM1CqH:b1g1w4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/15896ab82b11e967be9933ff181f88eda8e6fbde/pkg/sql/region_util.go#L1757)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: consider wrap the error at the call-site instead of passing in this op string? 
</blockquote></details>

i'd rather not, because that pushes a lot of lines of code and setup up at the call sites.

**Comment by otan** [comment]
bors r=ajstorm,arulajmani

**Pull request merged**
