### PR TITLE
authors: add <DarrylWong> to authors

### PR DESCRIPTION
**Pull request by DarrylWong**
Release note: None

### CODE REVIEW

**Review by jlinder — APPROVED** [review]
:lgtm:

To merge this, ask Craig (our Bors bot) to merge by writing a comment with a line containing `bors r+`.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74432#-:-Msei_7U3oE-Ki-tkIZl:bhn3hqt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong)

**Comment by DarrylWong** [comment]
bors retry

**Pull request merged**
