### PR TITLE
release-21.2: stats: fix autostats panic with minStaleRows == 0

### LINKED ISSUE #89323: sql: v21.2.7: rand panic in auto stats collection with minStaleRows == 0
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3644903299/?referrer=webhooks_plugin

Panic message:

>panic.go:965: panic: ×
--
*errutil.leafError: panic: × (1)
panic.go:965: *withstack.withStack (top exception)
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

/usr/local/go/src/runtime/panic.go#L964-L966 in runtime.gopanic
/usr/local/go/src/math/rand/rand.go#L110-L112 in math/rand.(*Rand).Int63n
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/sql/stats/automatic_stats.go#L575-L577 in pkg/sql/stats.autoStatsRand.randInt
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/sql/stats/automatic_stats.go#L448-L450 in pkg/sql/stats.(*Refresher).maybeRefreshStats
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/sql/stats/automatic_stats.go#L287-L289 in pkg/sql/stats.(*Refresher).Start.func1.1
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/util/stop/stopper.go#L441-L443 in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
/usr/local/go/src/runtime/asm_amd64.s#L1370-L1372 in runtime.goexit
</details>

```
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 965
/usr/local/go/src/math/rand/rand.go in math/rand.(*Rand).Int63n at line 111
pkg/sql/stats/automatic_stats.go in pkg/sql/stats.autoStatsRand.randInt at line 576
pkg/sql/stats/automatic_stats.go in pkg/sql/stats.(*Refresher).maybeRefreshStats at line 449
pkg/sql/stats/automatic_stats.go in pkg/sql/stats.(*Refresher).Start.func1.1 at line 288
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 442
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1371
```

| Tag | Value |
|---|---|
| Cockroach Release | `v21.2.7` |
| Cockroach SHA: | 37dee546a7c52870a8dc58826f0cffe2afa8d47a |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v21.2.7 |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-20204

### PR DESCRIPTION
**Pull request by msirek**
Fixes #89323

This fixes a panic in autostats code when cluster setting 
`sql.stats.automatic_collection.min_stale_rows` is 0.

Release note (bug fix): This patch fixes errors that may
occur in autostats collection when cluster setting
sql.stats.automatic_collection.min_stale_rows is set to 0.

Release justification: high-severity bug in existing functionality;
autostats collection should never panic.

### CODE REVIEW

**Comment by msirek** [comment]
This is backporting some code from #78110.

**Comment by cucaroach** [comment]
Does is make sense to allow setting minStaleRows to zero?  What does that mean? Recreate stats on any update/insert/delete? Wouldn't 1 be the same? Maybe it should be an error to set it to 0?  Or maybe it should mean never recreate stats (ie turn off auto stats)?  

Where's the PR for this to be fixed on master?  Did I miss it or does this bug not exist on master?

The release justification is just a restatement of the description, it should be something like one of the 4 categories here: https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/168656965/Guidelines+for+Release+Stability+Period

**Review by msirek — COMMENTED** [review]
I hadn't questioned the valid range of `min_stale_rows ` before.  It's had a min value of zero for a couple years.  The description says:
> Target minimum number of stale rows per table that will trigger a statistics refresh

And there's an example in docs:
> Suppose the clusters settings sql.stats.automatic_collection.fraction_stale_rows and sql.stats.automatic_collection.min_stale_rows have the default values .2 and 500 as shown in the preceding table.

>If a table has 100 rows and 20 became stale, a re-collection would not be triggered because, even though 20% of the rows are stale, they do not meet the 500 row minimum.

So, I think a `min_stale_rows` setting of zero would mean basically the thing as a setting of 1.  The number of mutations must be greater than or equal to this value to trigger auto stats. In the case that `rowCount` starts off low, like a value of 1, a `min_stale_rows` setting of zero would trigger stats refresh on the next mutation (if `fraction_stale_rows` is less than 1).  This seems like OK behavior.  Once the `rowCount` start growing, `rowCount` * `fraction_stale_rows` would be above zero and we'd start randomly triggering autostats (instead of on every mutation).

> Where's the PR for this to be fixed on master? Did I miss it or does this bug not exist on master?

This code was part of #78110, which I'm backporting to fix this issue.

I've updated the release justification to category 3.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89706#-:-NE6iIvO3CQkVAGsLiNj:bw5wf6b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

**Review by msirek — COMMENTED** [review]
I suppose users could get creative and set both `fraction_stale_rows` and `min_stale_rows` to zero to force autostats collection on every mutation. That could be by design, but I'm not sure.  Copying @rytaft 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89706#-:-NE6odQ3EXLBe3ItNfEc:b-8t687p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89706#-:-NE6zA7G2i_t38wGFIJR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by msirek — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89706#-:-NE7Vvkq1hropE5x73CB:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Pull request merged**
