### PR TITLE
movr: Add stats collection to movr workload run

### PR DESCRIPTION
**Pull request by rohany**
This PR adds tracking stats for each kind of query in the movr workload
so that output is displayed from cockroach workload run. Additionally,
this refactors the movr workload to define the work as functions on a
worker struct. This hopefully will avoid a common gotcha of having
different workers sharing the same not threadsafe histograms object.

Release justification: low risk nice to have feature

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
cc @jseldess , no need to open an issue

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @rohany)

___
*[pkg/workload/movr/movr.go, line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjF4XX3PF1UcRMesvk:-LpjF4XX3PF1UcRMesvl:bvd2e4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L553)):*
> ```Go
> 		err := work()
> 		elapsed := timeutil.Since(start)
> 		hists.Get(key).Record(elapsed)
> ```

we definitely only want to update when err is nil. we've had issues in the past with it being misleading to mix successful and failing queries in the same histogram

if you'd like to measure the errors as well, i'd make them separate buckets (either one big errors bucket or something like key + "-error", though probably the former to limit histogram explosion)
___
*[pkg/workload/movr/movr.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGAJTANhJ-QZSNDQO:-LpjGAJTANhJ-QZSNDQP:buiul6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L626)):*
> ```Go
> 	}
> 
> 	hists := reg.GetHandle()
> ```

the handle returned by this is not threadsafe, you need one per worker. I _think_ this happens to work now since there appears to be one worker, but let's avoid leaving this gotcha around in case someone goes to add more workers later
___
*[pkg/workload/movr/movr.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGfYQ9vPFGQBIypNk:-LpjGfYQ9vPFGQBIypNl:b-9yagbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L666)):*
> ```Go
> 			return err
> 		} else if rng.Float64() < 0.1 {
> 			// Apply a promo code to an account.
> ```

aren't these more useful to track at the level of a logical "movr api call"? so there'd be one for "apply promo code" instead of breaking it down for each db call in it. see how tpcc works for what i'm suggestion

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/movr/movr.go, line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjF4XX3PF1UcRMesvk:-LpjHl5eEGkPakkrsp4s:b-1tf30h) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L553)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we definitely only want to update when err is nil. we've had issues in the past with it being misleading to mix successful and failing queries in the same histogram

if you'd like to measure the errors as well, i'd make them separate buckets (either one big errors bucket or something like key + "-error", though probably the former to limit histogram explosion)
</blockquote></details>

Ok, that makes sense.
___
*[pkg/workload/movr/movr.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGAJTANhJ-QZSNDQO:-LpjHmny-peo1-uec_NC:b-yheg6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L626)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the handle returned by this is not threadsafe, you need one per worker. I _think_ this happens to work now since there appears to be one worker, but let's avoid leaving this gotcha around in case someone goes to add more workers later
</blockquote></details>

Yeah, i saw that. There is only one worker right now, so this is OK. However, I'm not sure how to change this to avoid a gotcha? Does leaving a comment denoting that this is the case the correct thing to do?
___
*[pkg/workload/movr/movr.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGfYQ9vPFGQBIypNk:-LpjHxlG5em2EuPjPff5:b-d8q6cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L666)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

aren't these more useful to track at the level of a logical "movr api call"? so there'd be one for "apply promo code" instead of breaking it down for each db call in it. see how tpcc works for what i'm suggestion
</blockquote></details>

I can condense some of these queries into one timed execution, but I wanted to separate the getRandom* from the other queries, because these are not part of the original movr application. They were added as a utility for me to easily generate random values, while the movr app we have kind of makes a local in-memory copy of the db and samples from it. So i didn't want to include those queries as part of the timing of a particular API call in order to avoid having times that differ a decent amount from the published movr app.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/workload/movr/movr.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGAJTANhJ-QZSNDQO:-LpjJuDX291mzQZJ5unE:bvl4vmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L626)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah, i saw that. There is only one worker right now, so this is OK. However, I'm not sure how to change this to avoid a gotcha? Does leaving a comment denoting that this is the case the correct thing to do?
</blockquote></details>

I think we need to bite the bullet on a small refactor of this code. Like I said on slack, this should all probably move to be closer to what tpcc is doing. I'm wary of making this code more complex and brittle and then calling it "low risk"
___
*[pkg/workload/movr/movr.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGfYQ9vPFGQBIypNk:-LpjJpQ-5LgadiurTQ2r:bs1iac4) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L666)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I can condense some of these queries into one timed execution, but I wanted to separate the getRandom* from the other queries, because these are not part of the original movr application. They were added as a utility for me to easily generate random values, while the movr app we have kind of makes a local in-memory copy of the db and samples from it. So i didn't want to include those queries as part of the timing of a particular API call in order to avoid having times that differ a decent amount from the published movr app.
</blockquote></details>

Hmm, i'm not particularly concerned about this matching the published movr app. Should I be? I'd rather optimize for this making sense to people kicking the tires on cockroachdb, which is likely to be the majority use of `workload run movr`

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/movr/movr.go, line 626 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGAJTANhJ-QZSNDQO:-LpjdDun9skyLwY-E8F5:b-jtbxvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L626)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think we need to bite the bullet on a small refactor of this code. Like I said on slack, this should all probably move to be closer to what tpcc is doing. I'm wary of making this code more complex and brittle and then calling it "low risk"
</blockquote></details>

Ok, i did the refactor. it does feel better now
___
*[pkg/workload/movr/movr.go, line 666 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpjGfYQ9vPFGQBIypNk:-LpjdIYbCQN5MedoAe-E:b-ggw8rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/12236db6e32d260286714b12cfa8bc79c8d6b29d/pkg/workload/movr/movr.go#L666)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Hmm, i'm not particularly concerned about this matching the published movr app. Should I be? I'd rather optimize for this making sense to people kicking the tires on cockroachdb, which is likely to be the majority use of `workload run movr`
</blockquote></details>

I thought about it more and I agree -- if you want to see the exact same thing as the movr app, just run the docker image yourself. Otherwise, cockroach workload run movr doesn't need to be exact.

**Review by danhhz — COMMENTED** [review]
:lgtm: one last plea for not leaving this as a gotcha, but feel free to merge even if you don't

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-:-LpnHmPf3YXp4x8spw-Y:b3b686c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @rohany)

___
*[pkg/workload/movr/movr.go, line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-LpnG4k36DmnufZ-tUkN:-LpnG4k36DmnufZ-tUkO:bq7u5m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/682765c2988e55006d6c6db60be06b99acc73485/pkg/workload/movr/movr.go#L758)):*
> ```Go
> 	}
> 
> 	// Hists is not threadsafe! If this workload expands to returning multiple workers,
> ```

i think doing this is trivial now. if you make a new `type struct worker` that has a `db *gosql.DB` and a `hists *histograms.Histograms`, you can move all the work fns and `movrQuerySimulation` to be methods on that struct

if you really don't feel like doing this now, then lets move this comment to be above the `ql.WorkerFns = append(ql.WorkerFns, movrQuerySimulation)` line, which is much more likely to be seen by someone making the change you mention than it would up here

**Review by rohany — COMMENTED** [review]
Thanks for your persistence -- it feels alot better now.  Can you take another quick look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-:-Lq1b30G7tbG3vlSTDwh:b-rhrooj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @rohany)

**Review by danhhz — COMMENTED** [review]
:lgtm_strong: \o/

Thanks for you patience on this, I feel good that we picked the cleanup off now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41138#-:-Lq1bkOx9eTJCZHCWC4q:b-h6gh3j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @rohany)

**Comment by rohany** [comment]
bors r=danhhz

**Pull request merged**
