### PR TITLE
mixedversion: unify signature of user and framework functions

### PR DESCRIPTION
**Pull request by renatolabs**
Previously, the signature of functions (hooks) provided by the user
was defined by the `userFunc` type, and the implementation of
framework steps was defined by the `Run` function of the `singleStep`
interface. These functions were slightly different even though there
was no need for the distinction.

This commit unifies the signature of both types of functions and
renames `userFunc` to `stepFunc` to reflect the generality. With this
change, functions implemented by the framework now also have an RNG
instance passed to them automatically. This will become especially
useful when we have mutator steps, where some randomization will often
take place.

Epic: none

Release note: None

**mixedversion: simplify steps by removing crdbNodes requirement**
Some steps implemented by the framework needed to be instantiated with
`crdbNodes`, a list of nodes where cockroachdb is running. This was
both repetitive and unnecessary. All steps have access to the helper
struct, which should given access, via private fields, to the list of
crdb nodes.

### CODE REVIEW

**Comment by renatolabs** [comment]
This PR simplifies internal step implementations and unify the functions they need to implement with user provided functions. This is to make the implementation of mutator steps more seamless, as the functions they will need to be implement will feel just like a regular `mixedversion` callback passed to `InMixedVersion`, for example.

### Context: mixedversion test mutators

This PR is part of a larger effort to introduce the concept of plan _mutators_ to the mixedversion framework. For initial discussion, see [internal thread](https://cockroachlabs.slack.com/archives/C01UDP33CCS/p1700252725103829).

In short, mutators are components that modify (i.e., mutate) the original test plan generated by the mixedversion planner. These changes are supposed to introduce new test scenarios in ways that do not interfere with the vast majority of tests. Tests will have the ability to individually enable or disable specific mutators as necessary; by default, all mutators will apply under some probability.

There is a working implementation of the entire idea in the [rc/mixedversion-plan-mutators](https://github.com/renatolabs/cockroach/tree/rc/mixedversion-plan-mutators) branch, in case it is helpful to see parts of the entire picture. That branch includes the proposed mutator API and an implementation of a mutator that, when merged, will close #111595.

#### History

* #115118: where we introduced the `upgradePlan` data structure and allows the upgrade to isolate the steps associated with each upgrade performed during the test.
* #117498: where we removed the `ID()` function from `singleStepProtocol`, allowing IDs to be assigned to steps later in 
the process, after the entire plan has been generated (and, now, mutations have been applied).
* #117993 is one of the pillars of this work, defining the interface to be implemented by mutators, as well as how the mutations they produce are applied to the original test plan.
* #118441 starts paving the way for the first mutators, with an API to disable them (in case a particular mutator is incompatible with a test), and by renaming the `finalize` step, foreshadowing the first (yet to be introduced) mutator implementation.

**Comment by renatolabs** [comment]
The context passed to `Run()` is the context that user-functions should use and pass to any functions they call that expect a context. While the runner does have the same `ctx` currently 1) it's a private field, so tests don't have access to it, and 2) it exists mostly as a convenience so that helper functions (e.g., `h.Exec()`) can be called by the test without a context.

Does that answer your question or did I miss something?

**Review by DarrylWong — COMMENTED** [review]
One more clarification question and two (tiny) nits but besides that this LGTM.

nit: https://github.com/cockroachdb/cockroach/blob/dde8ace559fdcbd2c72643f5ddd9908847fc07ea/pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go#L28-L29

This comment is no longer true right? Seems like both user and framework run functions take advantage of helper.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-:-Nq9azYI2MUmaZ5yBN3-:bxugwlt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-Nq9bvso5B0MVZPZLe_s:-Nq9bvso5B0MVZPZLe_t:b3pc37y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed83b311b1d95724855db896dc3d4d30e078ba47/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L898)):*
> ```Go
> }
> 
> func (s waitStep) Run(ctx context.Context, l *logger.Logger, _ *rand.Rand, h *Helper) error {
> ```

nit: if we're going to make `Rand` unamed we could also make the various unused `context` and `logger` parameters unamed as well. Doesn't bother me either way though.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-Nq9bA0z-nWpMxExejtD:-Nq9bA0z-nWpMxExejtE:b6mxvlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed83b311b1d95724855db896dc3d4d30e078ba47/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L395)):*
> ```Go
> 			possibleWaitDurations := []time.Duration{1 * time.Minute, 5 * time.Minute, 10 * time.Minute}
> 			steps = append(steps, p.newSingleStep(waitStep{
> 				dur: pickRandomDelay(p.newRNG(), p.isLocal, possibleWaitDurations),
> ```

It looks like the new pattern is to generate a new RNG for each step. I'm curious what benefit we gain from this? I don't think it would be wrong, but wondering if the prior method of reusing the same `p.prng` had some limitation/bug.

**Review by renatolabs — COMMENTED** [review]
Well, I wouldn't say it's not true; it continues to be the case that the helper struct is passed to user functions. But I'm trying to make "user-provided" and "framework-implemented" more uniform. So, in that sense, the helper is passed to both.

I rephrased this comment a bit in hopes of making it clearer, let me know if it helps.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-:-NqEqM17E2NKh8uopFf7:bu0o3f8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-Nq9bvso5B0MVZPZLe_s:-NqElY8v1uSC6CDcdBBY:bdgqxf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed83b311b1d95724855db896dc3d4d30e078ba47/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L898)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: if we're going to make `Rand` unamed we could also make the various unused `context` and `logger` parameters unamed as well. Doesn't bother me either way though.
</blockquote></details>

I guess my point keeping the rand instance unnamed was to indicate that there was nothing random in that function. Most other step implementations do use the context* and logger directly; the few that don't, use it through the `helper`.

That said, I don't feel strongly either way.

* On that note, I noticed that the `waitStep` you are commenting on here shouldn't ignore the context, so I pushed a commit to fix that. Thanks!
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-Nq9bA0z-nWpMxExejtD:-NqEpfNo7-PcOCCPGd7D:b41pc3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed83b311b1d95724855db896dc3d4d30e078ba47/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L395)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

It looks like the new pattern is to generate a new RNG for each step. I'm curious what benefit we gain from this? I don't think it would be wrong, but wondering if the prior method of reusing the same `p.prng` had some limitation/bug.
</blockquote></details>

So, the main change in this PR for step functions (user provided or implemented by the framework) to rely on the rng passed as argument, to make this more uniform. So, in that sense, the main change is to remove the rng field from structs that implement upgrade steps.

What didn't make sense (and I believe that's what you're pointing out) was to switch from `p.prng` to `p.newRNG` in many other unrelated places. While harmless, this change doesn't really mean anything, so I reverted the call sites that didn't need to be updated.

I actually had the same question when I was cherry picking this commit; I'm not sure what I was thinking when I first wrote this code in the `mixedversion-plan-mutators` branch.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118666)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go` line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118666#-Nq9bA0z-nWpMxExejtD:-NqErXT-BEFnuq_xjZIh:buc9wz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed83b311b1d95724855db896dc3d4d30e078ba47/pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go#L395)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

So, the main change in this PR for step functions (user provided or implemented by the framework) to rely on the rng passed as argument, to make this more uniform. So, in that sense, the main change is to remove the rng field from structs that implement upgrade steps.

What didn't make sense (and I believe that's what you're pointing out) was to switch from `p.prng` to `p.newRNG` in many other unrelated places. While harmless, this change doesn't really mean anything, so I reverted the call sites that didn't need to be updated.

I actually had the same question when I was cherry picking this commit; I'm not sure what I was thinking when I first wrote this code in the `mixedversion-plan-mutators` branch.
</blockquote></details>

Another note: while also not necessary for correctness, another change this PR made was to have the RNG be passed as parameter o the `testHooks.*Steps()` functions, instead of those functions referencing RNG fields directly.

The main motivation for this was to have the planner be the single component responsible for managing RNGs. The fact that the RNG was previously passed by the `Test` struct was a bit subtle IMO.

**Review by DarrylWong — APPROVED** [review]
>to indicate that there was nothing random in that function

Got it, I just wasn't aware of that reasoning, but it makes senses. I think it's fine as is.

All other comments SGTM. Thanks for clarifying it for me 😄

**Comment by renatolabs** [comment]
Mixed-version tests [continue to pass](https://teamcity.cockroachdb.com/viewLog.html?buildId=13965911&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=buildResultsDiv) on this branch.

TFTR!

bors r=DarrylWong

**Pull request merged**
