### PR TITLE
distsql: populate EvalCtx.Txn early in remote flows

### PR DESCRIPTION
**Pull request by andreimatei**
This patch fixes a crash when a built-in function was trying to use the
transaction on a remote node (i.e. not the gateway). This bug was
introduced in one of the 19.2 betas when we fiddled with how
transactions are set for flows. It used to be that the EvalCtx to be
used by the flow was initialized early. We changed it because, on the
gateway, the transaction to be used by the flow is only know after the
flow is setup (only then can we decide root vs leaf). We started setting
EvalCtx.Txn later. Unfortunately, a different change some time back
started making deep copies of the EvalCtx eagerly during the process of
setting up processors and operators. Those copies thus capture whatever
is set at that time. In the DistSQL world, most things use the
transaction from the shared FlowCtx, except expression evaluation (i.e.
built-in functions), which unfortunately takes the transaction
implicitly through the EvalCtx. Builtin functions that need the txn
include cluster_logical_timestamp() and a bunch of pg_ ones.

This patch fixes the problem by observing that, on remote nodes, the
transaction is known in advance of setting up the flow - it's a leaf.
And so in this case we start populating the EvalCtx early again.

On gateways things worked, and continue to work, becase the EvalCtx is
coming already populated from the executor. Things are funky because the
flow might end up using a leaf while all the processors capture the
root, but hopefully that doesn't have too bad consequences.

Release note (bug fix): A bug causing rare crashes when using built-in
functions was fixed. The bug had been introduced in the 20191014 beta of
version 19.2

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @bobvawter

**Review by yuzefovich — APPROVED** [review]
I can't say I fully understand this part of the codebase, but the change :lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-:-LsJXOYm1nu7elKWK3G-:b-87jyfk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

**Comment by mjibson** [comment]
Can you add `Fixes #41959` to the commit message?

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsql/server.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-LsLvIy8BbpJP_ynEJys:-LsLvIy8BbpJP_ynEJyt:b-u4ma92) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe656a283de7dad788bcf5b1cbd8d43abea5db5/pkg/sql/distsql/server.go#L391)):*
> ```Go
> 	// set above so it's fine. If we're using a LeafTxn on the gateway, though,
> 	// then the processors have erroneously captured the Root. Hopefully this is
> 	// inconsequential.
> ```

As per your explanation from two weeks ago, if a processor encounters a retry error, its root txncoordsender will do the error processing which is not expected.
Are you sure about the "inconsequential"? I'd like to hear @nvanbenschoten's opinion on this.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql/server.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-LsLvIy8BbpJP_ynEJys:-LsMvga8Ekje-CXQ8M3p:bmxirl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe656a283de7dad788bcf5b1cbd8d43abea5db5/pkg/sql/distsql/server.go#L391)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

As per your explanation from two weeks ago, if a processor encounters a retry error, its root txncoordsender will do the error processing which is not expected.
Are you sure about the "inconsequential"? I'd like to hear @nvanbenschoten's opinion on this.
</blockquote></details>

That's why I said "hopefully" :P.
I was just trying to de-emphasize the importance of the `EvalCtx.Txn`. But you're right, the comment was bad. I've filed https://github.com/cockroachdb/cockroach/issues/41992 and referenced it instead.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql/server.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-LsLvIy8BbpJP_ynEJys:-LsNJYvw0MBf9t-YBXl4:bs56z7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe656a283de7dad788bcf5b1cbd8d43abea5db5/pkg/sql/distsql/server.go#L391)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

That's why I said "hopefully" :P.
I was just trying to de-emphasize the importance of the `EvalCtx.Txn`. But you're right, the comment was bad. I've filed https://github.com/cockroachdb/cockroach/issues/41992 and referenced it instead.
</blockquote></details>

Thanks for this.
A question remains however: what confidence do we have this change fixes the likely problems that are going to be encountered in 19.2?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql/server.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-LsLvIy8BbpJP_ynEJys:-LsO49io4hMnpkV9WmyI:b-e5t3l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe656a283de7dad788bcf5b1cbd8d43abea5db5/pkg/sql/distsql/server.go#L391)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thanks for this.
A question remains however: what confidence do we have this change fixes the likely problems that are going to be encountered in 19.2?
</blockquote></details>

Well I'm pretty sure it fixes the NPE crashes due to the missing txn in the `EvalCtx` captured by processors in remote flows. I've tested it by hand and add a test.

**Review by RaduBerinde — COMMENTED** [review]
> Things are funky because the
> flow might end up using a leaf while all the processors capture the
> root, but hopefully that doesn't have too bad consequences

This sounds a bit scary.. the processors would initialize using the root txn and then later we would change the txn with a leaf txn? So the processors would keep using the root txn? Won't that cause issues? (there is a reason why we changed it to use a leaf txn)

I realize that is a problem already and this PR is a net improvement, so :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-:-LsO8LfUB54GYxmFvBa8:bewgxyx)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

**Review by andreimatei — COMMENTED** [review]
Yeah, it's not great :)
I had filed https://github.com/cockroachdb/cockroach/issues/41992 for it. I'm gonna craft an email to the sql execution peeps about it and a couple of related ones. The way expression evaluation in DistSQL has a couple of problems.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41970#-:-LsOANqnAaMxVt8t0rt-:b5ej9xm)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @nvanbenschoten, and @yuzefovich)

**Comment by andreimatei** [comment]
> So the processors would keep using the root txn?

Oh but what I hope has not gotten lost in translation is that only expression evaluation (i.e. builtin function) erroneously uses the Root. The processors themselves use the correct txn.

bors r+

**Pull request merged**
