### PR TITLE
distsqlrun: future-proof the consumer->producer communication

### PR DESCRIPTION
**Pull request by andreimatei**
This patch enhances the consumer->producer (gRPC server->client)
communication by adding a series of unidirectional "handshake" messages.
These are sent by the consumer node as soon as the producer connects to
inform it about the status of the consumer flow: has it already been
scheduled or not. The first message is sent immediately upon producer
connection with the current status. If the consumer flow was not
scheduled already, then a 2nd message is sent later once the consumer
flow is scheduled (if that happens within the scheduling deadline).

The idea here is to give some information to producers about what's
going on with the data they're sending: is it being consumed or not?
This should be helpful if we ever want to devise fallback schemes for
producers: if the consumer is never scheduled where it was supposed to
be scheduled, we might want the producer to send its data somewhere
else. This kind of schemes need a buffering component in the producer
which needs to not drop data it's streaming before knowing that it is in
fact being consumed - so it also needs to know when it's being consumed
so it stops buffering. If such schemes are to be introduced in say 1.2,
then 1.1 likely needs to start sending these messages.

Besides the more speculative uses of these signals, the patch
incidentally also has some more immediate benefits:
- the consumer status messages make it to the producer's trace spans,
which sounds like a good thing when you're trying to figure out the
timings of streaming events.
- the outbox code has been fixed to not consider any signal a drain
signal. This is a biggie because the current code was narrow minded and
didn't let any signals other that drain signals to be sent. This changed
is why this patch requires a DistSQL version bump and this is a good
time to do it since we've already bumped it lots since 1.0.
- related to the point above, other consumer->producer signals can now
be received by the producer after a drain signal, which sounds like a
sane thing.

### CODE REVIEW

**Comment by andreimatei** [comment]
For your consideration.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/api.proto, line 79 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767#-Ks4MzHnCTcv60W8__9I:-Ks4MzHnCTcv60W8__9J:b-w8m4d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee524373186b449fe3067fc818edca8b4deee3e/pkg/sql/distsqlrun/api.proto#L79)):*
> ```protobuf
> }
> 
> // ConsumerHandshake are the first one or two message sent in the
> ```

[nit] is the first (and sometimes second) message sent

---

*[pkg/sql/distsqlrun/api.proto, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767#-Ks4k5fEjfu_VtfXextC:-Ks4k5fEjfu_VtfXextD:b8qkrhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee524373186b449fe3067fc818edca8b4deee3e/pkg/sql/distsqlrun/api.proto#L97)):*
> ```protobuf
>   // dealine, this stream will be disconnected by the server-side.
>   // Expressed in nanos since epoch.
>   optional int64 consumer_schedule_deadline = 2;
> ```

This should be a `google.protobuf.Timestamp` or `util.hlc.Timestamp`. Can also be `(gogoproto.nullable) = false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767#-:-Ks4kWLxb0xOnCdA0j4U:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/api.proto, line 79 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767#-Ks4MzHnCTcv60W8__9I:-Ks4nJOcOkw6cl5O5mq5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee524373186b449fe3067fc818edca8b4deee3e/pkg/sql/distsqlrun/api.proto#L79)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] is the first (and sometimes second) message sent
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/api.proto, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767#-Ks4k5fEjfu_VtfXextC:-Ks5_H5BMciZRw_9TtYE:b-wabb9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ee524373186b449fe3067fc818edca8b4deee3e/pkg/sql/distsqlrun/api.proto#L97)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be a `google.protobuf.Timestamp` or `util.hlc.Timestamp`. Can also be `(gogoproto.nullable) = false`.
</blockquote></details>

switched to `google.protobuf.Timestamp` (which wasn't easy, required some protobuf build fixes haha). Left it nullable though - it's only set if `consumer_scheduled=false`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17767)*

**Comment by RaduBerinde** [comment]
Hey @andreimatei, I just noticed that `version_history.txt` describes version 6 but the code kept versions 5/4 in the code. Can you take a look? Do we need to bump them to 6 (in 1.1)? Also there is a typo in the description (Version not Verion). BTW this is probably better kept as a comment near the version rather than a separate file.

**Comment by andreimatei** [comment]
Yup, I screwed up. Thanks for catching this. #18522

**Pull request merged**
