### PR TITLE
release-22.2: debug: option to omit goroutine stacks by default from debug zip

### PR DESCRIPTION
**Pull request by abarganier**
Backport:
  * 1/1 commits from "debug: option to omit goroutine stacks by default from debug zip" (#110177)

Please see individual PRs for details.

/cc @cockroachdb/release

----

Release justification: low-risk (CLI) change to debug zip to enable reduction of performance impact for clusters with large numbers of goroutines.

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
What are the line diffs that are different from the original PR, is it just testdata?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110258#-:-NdpP-qZ7xaDBV8DKpRF:b-2ig6b6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by abarganier — COMMENTED** [review]
> What are the line diffs that are different from the original PR, is it just testdata?

I usually pull up the diff of the original PR side-by-side with the diff from the backport PR to determine this.

In this instance, there were some package differences and flags present on v22.2 that aren't present anymore on master, so the code had to be tweaked to fit how things are on 22.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110258#-:-NdpQ8ew2kl8iMYtTcoi:b-96xm63)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by Santamaura — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110258)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by abarganier** [comment]
TFTR!

**Pull request merged**
