### PR TITLE
colexec: make vectorized stats concurrency safe

### LINKED ISSUE #61899: sql/rowexec: TestUncertaintyErrorIsReturned failed
[(sql/rowexec).TestUncertaintyErrorIsReturned failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2770515&tab=buildLog) on [master@4b98115dfda02a9498f566958bd915c45ec7e449](https://github.com/cockroachdb/cockroach/commits/4b98115dfda02a9498f566958bd915c45ec7e449):

```
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:78 +0xab
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:86 +0x91
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedStatsCollectorImpl).Next()
      <autogenerated>:1 +0x5b
  github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash.(*HashTable).FullBuild()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:362 +0x1ac
  github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin.(*hashJoiner).build()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin/hashjoiner.go:319 +0xcf
  github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin.(*hashJoiner).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin/hashjoiner.go:281 +0x1b9
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:201 +0x96
  github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x72
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:199 +0xef
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*InvariantsChecker).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:78 +0xab
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:86 +0x91
  github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedStatsCollectorImpl).Next()
      <autogenerated>:1 +0x5b
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:195 +0x6e
  github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91 +0x72
  github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func2()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:229 +0x8e4

Goroutine 637 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:553 +0x1fd
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:285 +0x832
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:152 +0x304
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:658 +0xeb7
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).startServeSQL.func1.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:2074 +0x16c
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:156 +0x11d
==================
    testing.go:1038: race detected during execution of test
        --- FAIL: TestUncertaintyErrorIsReturned/vectorize=true/SELECT_*_FROM_t_AS_t1_JOIN_t_AS_t2_ON_t1.x_=_t2.x (0.14s)
=== RUN   TestUncertaintyErrorIsReturned/vectorize=true
=== CONT  TestUncertaintyErrorIsReturned/vectorize=true
    testing.go:1038: race detected during execution of test
    --- FAIL: TestUncertaintyErrorIsReturned/vectorize=true (0.55s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-race -parallel=4

```
make stressrace TESTS=TestUncertaintyErrorIsReturned PKG=./pkg/sql/rowexec TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestUncertaintyErrorIsReturned.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colflow: clean up vectorized stats for rowexec processors**

Previously, the wrapped row-execution KV reading processors were
implementing `execinfra.KVReader` interface, but they were never used as
such, only the ColBatchScans would get used to retrieve the KV stats.
This is the case because the row-execution processors report their
execution stats themselves, and we don't want to duplicate that info.
This commit moves `KVReader` interface into `colexecop` package and now
only the ColBatchScans implement it. This allowed for some cleanup
around the vectorized stats code, but the main reason for performing
this change is that the contract of the interface will be modified by
the follow-up commit to mention the safety under concurrent usage, and
I didn't want to change the row-execution processors for that since the
relevant methods never get called anyway.

Additionally, this commit begins emitting of rows-read and bytes-read by
the zigzagJoiners and invertedJoiners to complete the metrics picture.

Release note: None

**colexec: make vectorized stats concurrency safe**

Previously, the collection of vectorized stats was not synchronized with
the operators themselves. Namely, it was possible to call methods like
`GetBytesRead` on the ColBatchScans and Inboxes from a different
goroutine (the root materializer or the outbox) than from the main
goroutine of the operator. This is now fixed by putting mutexes in place
and updating `colexecop.KVReader` interface to require concurrency-safe
implementations.

Fixes: #61899.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> I didn't want to change the row-execution processors for that since the
> relevant methods never get called anyway.

Do they not? Was it just dead code? I'm probably missing something.

How did you track down all places that needed to be changed?

> Reviewed 14 of 14 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-:-MVptxFJBxybTnv9ICvc:bvd2rfa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexecop/operator.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpumL50xeBw6ubKWSf:-MVpumL6A2cs7eERVYTq:b-mwqhhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colexecop/operator.go#L71)):*
> ```Go
> type KVReader interface {
> 	// GetBytesRead returns the number of bytes read from KV by this operator.
> 	// It must be safe for concurrent use.
> ```

Maybe put a TODO. I think long-term it'll be better if we adopt a single-goroutine approach to this similar to DrainMeta.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpvMfO6E8cvrf3t8Lv:-MVpvMfO6E8cvrf3t8Lw:byoek6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colfetcher/colbatch_scan.go#L96)):*
> ```Go
> // Next is part of the Operator interface.
> func (s *ColBatchScan) Next(ctx context.Context) coldata.Batch {
> 	s.mu.Lock()
> ```

Why not `defer` the Unlock?
___
*[pkg/sql/colflow/colrpc/inbox.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpvlhHCbuvxI9t1WGz:-MVpvlhHCbuvxI9t1WH-:b7rjlwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colflow/colrpc/inbox.go#L111)):*
> ```Go
> 	// than Next().
> 	statsMu struct {
> 		syncutil.Mutex
> ```

nit: you could use atomics here maybe. Might be less verbose

**Review by yuzefovich — COMMENTED** [review]
Those methods are still used, but not via `KVReader` interface - they are called explicitly in the corresponding `execStatsForTrace`. Tracking things down was easy - we had 1 operator and 4 processors implement the interface.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-:-MVqnDBl1VpngIbm4dim:b-9ocbe3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexecop/operator.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpumL50xeBw6ubKWSf:-MVqqYdz-0WvwSqI-5F0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colexecop/operator.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe put a TODO. I think long-term it'll be better if we adopt a single-goroutine approach to this similar to DrainMeta.
</blockquote></details>

Done.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpvMfO6E8cvrf3t8Lv:-MVqnofW-uR3AMiD7BtX:b5gy4h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colfetcher/colbatch_scan.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not `defer` the Unlock?
</blockquote></details>

That seems unnecessary - `NextBatch` might take a while (e.g. when we had a range cache miss and had to do a remote read at dist sender level), so I thought this custom locking makes sense since it doesn't look too complicated. Feel free to push back on this though.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-MVpvlhHCbuvxI9t1WGz:-MVqq80M47pHwn7_03a4:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/9807fa3b4d44fc14afbb6422ed1e468a313e7a8a/pkg/sql/colflow/colrpc/inbox.go#L111)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: you could use atomics here maybe. Might be less verbose
</blockquote></details>

Nice, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61937#-:-MVr-VmLB3xxXuH3MdNw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by asubiotto** [comment]
Agreed that I don't think it's worth it to backport to 20.2. Stopwatch sounds fine but also not necessary.

**Comment by yuzefovich** [comment]
Cool, let's not backport the stopwatch fix either then.

**Pull request merged**
