### PR TITLE
build/roachtest: upload stats after upload binaries

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
When openmetrics are enabled in roachtest, we use a different service account in `upload_stats` to upload to a bucket in `cockroach-testeng-infra` rather than `cockroach-ephemeral`.
```
+ gsutil cp bin/roachprod gs://cockroach-nightly/binaries/master/linux/amd64/roachprod.b6bfe7ba6e74af63bbb7a774fe6e3f96a13eca80
04:22:20   AccessDeniedException: 403 teamcity@cockroach-testeng-infra.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
```
Currently since `upload_binaries` run afterwards, it fails since the nightly bucket in present in `cockroach-ephemeral`. 

One simple solution is to swap the order of execution so that the binaries are uploaded before stats since the order doesn't really matter. 
Epic: none

Release note: None

### CODE REVIEW

**Comment by sambhav-jain-16** [comment]
Test runs:

Json: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17949832?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

Openmetrics:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Roachtest_Openmetrics_Gce/17949741?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Comment by sambhav-jain-16** [comment]
> Test runs:
> 
> Json: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17949832?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true
> 
> Openmetrics: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Roachtest_Openmetrics_Gce/17951008?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

Both tests passed

**Review by nameisbhaskar — APPROVED** [review]
LGTM!

**Comment by sambhav-jain-16** [comment]
TFTR! 

bors r=@nameisbhaskar

**Pull request merged**
