### PR TITLE
use a temporary fork of grpc

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13840)

### CODE REVIEW

**Comment by tamird** [comment]
Also it seems that you accidentally removed a vendored proto.

**Comment by dt** [comment]
Looking at the diff in vendor, i think you might need to `go get -u github.com/Masterminds/glide` to pick up the submodule fix (the proto in lightstep)

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[glide.yaml, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4OEHW0nsF983GYE1N:-Ke4OEHW0nsF983GYE1O:b-v2s3om) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb1d6df875839bf24639d73c5a0e3e1ad5c8787/glide.yaml#L47)):*
> ```YAML
> - package: google.golang.org/grpc
>   version: d3f1ab4a4dca70781cf6dc850a79ed38632660a6
>   repo: git@github.com:petermattis/grpc-go.git
> ```

nit: can we use the https version of the remote url (to allow anon access)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-:-Ke4OXArUmk4WXe1K3dl:b8e8noa)*

**Comment by petermattis** [comment]
Extended the commit message and added a comment to `glide.yaml`. Fixed the removed vendored proto.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[glide.yaml, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4OEHW0nsF983GYE1N:-Ke4Ri2fLKAIu7WHFutC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb1d6df875839bf24639d73c5a0e3e1ad5c8787/glide.yaml#L47)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: can we use the https version of the remote url (to allow anon access)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-:-Ke4Rqc0JpLqKd3-DlSZ:b-xw88jt)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-:-Ke4XOqZptr9l_qWergV:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[glide.yaml, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4YTc97aQj8NECAmZG:-Ke4YTc97aQj8NECAmZH:barpdav) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf2dffde6c1f103e53cfbf55b3b5542f0476578/glide.yaml#L48)):*
> ```YAML
> # sizes. The defaults are too low for high latency links and do not
> # adjust dynamically. Remove when upstream addresses the issue, either
> # making the window sizes configurable or dynamically adjust them.
> ```

There's an issue upstream, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[glide.yaml, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4YTc97aQj8NECAmZG:-Ke4kexr4TufYdQrucfL:b-wlbxsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf2dffde6c1f103e53cfbf55b3b5542f0476578/glide.yaml#L48)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

There's an issue upstream, right?
</blockquote></details>

Yes, 2 actually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[glide.yaml, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4YTc97aQj8NECAmZG:-Ke4pIrE9AUbOKOXu1FK:bra0a3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf2dffde6c1f103e53cfbf55b3b5542f0476578/glide.yaml#L48)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, 2 actually.
</blockquote></details>

Apologies for not being more clear: I was suggesting that we link to those issues here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-:-Ke4pOJl4gse_6nDMDFP:bnfp4nl)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[glide.yaml, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4YTc97aQj8NECAmZG:-Ke4pgXC9hvX0hITRxGV:b-4nxge9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf2dffde6c1f103e53cfbf55b3b5542f0476578/glide.yaml#L48)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Apologies for not being more clear: I was suggesting that we link to those issues here.
</blockquote></details>

oh, this is super-nitty (sorry), but if you do opt to eat another CI cycle to add that link: 

when there's an upstream issue forcing a pin to a specific revision, the suggested convention was to put that pin in the section at the top of this file -- this bottom section was intended to be just stability pins (which could still be commented out en-masse when tamir wants to bump everything to latest).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Comment by petermattis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[glide.yaml, line 48 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840#-Ke4YTc97aQj8NECAmZG:-Ke4t3X_OqKOPYnm0hV9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf2dffde6c1f103e53cfbf55b3b5542f0476578/glide.yaml#L48)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

oh, this is super-nitty (sorry), but if you do opt to eat another CI cycle to add that link: 

when there's an upstream issue forcing a pin to a specific revision, the suggested convention was to put that pin in the section at the top of this file -- this bottom section was intended to be just stability pins (which could still be commented out en-masse when tamir wants to bump everything to latest).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13840)*

**Pull request merged**
