### PR TITLE
sql: fix conversion of interval to float

### LINKED ISSUE #22891: sql: conversion of internal to float is broken
```go
    case *DInterval:
      micros := v.Nanos / 1000
      return NewDFloat(DFloat(float64(micros) / 1e-6)), nil
```

should be `/ 1e6` or `* 1e-6`, but the current formula is incorrect.

### PR DESCRIPTION
**Pull request by knz**
Converting an interval to float must give a number of seconds. The
previous code would give a number of picoseconds (!).

Release note (bug fix): the conversion from `INTERVAL` to `FLOAT` now
properly returns the number of seconds in the interval.

Fixes #22891.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:D :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22892#-:-L5tZFPhf6x7H_ueeTsn:b7w035v)*

**Comment by justinj** [comment]
Where is the "correct" behaviour here defined? I get this in Postgres:
```
# select '3h3us'::interval::float;
ERROR:  cannot cast type interval to double precision
LINE 1: select '3h3us'::interval::float;
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22892#-:-L5tYsAQz1JgqJvxO53X:b62lou0)*

**Comment by knz** [comment]
It's a crdb extension.

**Comment by knz** [comment]
The behavior for float must be consistent with the conversion to int or decimal, which return seconds.

**Comment by justinj** [comment]
:lgtm: Ah I see, matching decimal and int makes sense!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22892#-:-L5t_10VbhUDHgAii90E:b-16fhd8)*

**Pull request merged**
