### PR TITLE
roachprod: GetInternalIp now returns the cached vm.PrivateIp

### LINKED ISSUE #99277: roachprod: `GetInternalIP` is unreliable
The current implementation of `GetInternalIP` calls `hostname --all-ip-addresses`, and returns the stdout of that command as the internal IP of the VM.

This has the implicit assumption that the VM has a single private IP, which may not be the case depending on what's running in the VM. When there are multiple IPs, it will return a string like `10.0.1.23 10.0.2.39`.

This is especially tricky to debug in cases where it's used in larger scripts; as a recent example, this made the scripts run by the `SetupSSH` logic [1] wrong in a way that is hard to debug.

[1] https://github.com/cockroachdb/cockroach/blob/1e2ea17a3dbb4b4c8a2942105abc6712d90b477e/pkg/roachprod/install/cluster_synced.go#L1149-L1164

Jira issue: CRDB-25802

### PR DESCRIPTION
**Pull request by smg260**
This PR replaces all parallel calls to `hostname` on each node, with the `vm.PrivateIp` which is resolved when syncing remote vm metadata. As a result, it will also not be susceptible to (also) returning the internal IP created by a docker eth interface

Epic: none
Fixes: #99277

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
Nice! I didn't realize we already had `vm.PrivateIP`. I was trying to see why `GetInternalIP` (previously known as `getInernalIP`) was even added in the first place. It appears that this change predates the availability of `vm.PrivateIP`. I went back as far as this commit [1], in the original repo.

[1] https://github.com/cockroachdb/roachprod/tree/947f786dac39004d69ba7f9e71c7eed3bdaf6a86

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104237#-:-NWxhFDKChe4pMKbhMLa:b2t0xgr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan)

**Review by herkolategan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104237)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260)

**Comment by smg260** [comment]
TeamCity
- [GCE](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10356291?buildTab=overview&showRootCauses=true&expandBuildTestsSection=true&expandBuildProblemsSection=true#%2Fknex%2Frun_1%2Fartifacts.zip)
- [AWS](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel?mode=builds)

**Comment by smg260** [comment]
bors r=srosenberg,herkolategan

TFTR

**Pull request merged**
