### PR TITLE
timeutil: sort timezones

### PR DESCRIPTION
**Pull request by mneverov**
Previously, timezones in the generated file were not sorted. That led to
the file being changed greatly when Go version was updated, or even
within the same Go version when /usr/local/go/lib/time/zoneinfo.zip was
regenerated from different time zone releases:
https://data.iana.org/time-zones/releases
This patch sorts timezones before writing them down so the changes in
the file are minimal and only reflect the actual change in the
timezones.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
thanks!
bors r+

**Comment by mneverov** [comment]
Hi @otan, thanks for the review.
I have a second thought about this. I did not only add sort, but regenerated the file with the newest timezone release (which is https://data.iana.org/time-zones/releases/  tzdb-2021a.tar.lz). 
I think after this change all the CRDB contributors will have `lowercase_timezones.go` changed every time they use `make generate` until they update the Go zoneinfo.zip manually, or update to the newest go version. That was a mistake to do the sorting now, I think it is better to do that together with the Go version update.
Sorry about this!

**Comment by otan** [comment]
Hmm, it seems as if it still passes CI so maybe there are no new timezones in go 1.16?

**Comment by otan** [comment]
CI will automatically check that the generated file in go 1.15 is up to date, so it looks like it is?

**Review by mneverov — COMMENTED** [review]
I see one new release from 2021-01-24. I'll compare the timezones

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60704#-:-MTniGIA15MDU1-GPI4s:b-k6lwyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by mneverov — COMMENTED** [review]
I compared timezones in go 1.15 (2020a) and go 1.16 (2021a). 
Release notes for the changes can be found here https://mm.icann.org/pipermail/tz-announce/. 
You're right, no new timezones added, generated `lowercase_timezones` is the same except the order. Sorry about the confusion :facepalm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60704#-:-MTnwL4C82oIsNXXtQQS:byfzpy9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
no woz!

Let's go again

bors r+

**Pull request merged**
