### PR TITLE
githubpost: tag stress issues with stress

### LINKED ISSUE #83509: bazel: running under stress in bazel is not apparent in autofiled test failure issues
We got this issue recently, from a failure in the nightlies:
https://github.com/cockroachdb/cockroach/issues/83398
Looking at the artifacts, it's apparent that this test failed while running under stress, but this is not reflected in the issue description.

Jira issue: CRDB-17113
Epic CRDB-8349

### PR DESCRIPTION
**Pull request by healthy-pod**
Release note: None
closes #83509

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
We don't use the `stress` tag for anything in the build. What is the advantage of setting it here?

**Review by rickystewart — CHANGES_REQUESTED** [review]
.

**Comment by healthy-pod** [comment]
> We don't use the stress tag for anything in the build. What is the advantage of setting it here?

No advantage. Should I set it [here](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/stress_impl.sh#L7)?

**Review by rickystewart — CHANGES_REQUESTED** [review]
The thing is that setting build tags will thrash the cache, i.e., *everything* in the cache will be thrown away as we rebuild *everything* (the stdlib, all Go code, etc.)

To do this for no reason (when it won't even make a difference in the compiled code) makes no sense.

With regard to #83509, the request is to make the `stress` "tag" evident in the *filed issue*. Note that this can be done without affecting how the build is done at all.

**Comment by healthy-pod** [comment]
Thanks for explaining, ready for another look.

**Review by rickystewart — CHANGES_REQUESTED** [review]
Where is `COCKROACH_STRESS` set?

**Comment by healthy-pod** [comment]
Changed it to `COCKROACH_NIGHTLY_STRESS` which is set in https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/stress_impl.sh#L31

**Review by rickystewart — CHANGES_REQUESTED** [review]
> Changed it to `COCKROACH_NIGHTLY_STRESS` which is set in [`master`/build/teamcity/cockroach/nightlies/stress_impl.sh#L31](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/stress_impl.sh?rgh-link-date=2023-05-17T20%3A15%3A27Z#L31)

This sets the environment variable *inside the test runners*. Outside of the test runners, which is where `githubpost` executes, there is no such variable. So another update to put this variable inside the environment would be necessary.

**Comment by healthy-pod** [comment]
> This sets the environment variable inside the test runners. Outside of the test runners, which is where githubpost executes, there is no such variable. So another update to put this variable inside the environment would be necessary.

Would the latest change work?

**Review by rickystewart — APPROVED** [review]

**Comment by healthy-pod** [comment]
\o/ yaaay

bors r=rickystewart

**Pull request merged**
