### PR TITLE
githooks: update submodule after checkout out new refs

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11765)

### CODE REVIEW

**Comment by tamird** [comment]
Why does make .bootstrap not do the right thing?

**Comment by dt** [comment]
AFAIK, the test below is exiting before then -- I assumed intentionally to
avoid rebuilding tools?

**Comment by tamird** [comment]
Rebuilding tools is cheap, though?

**Comment by RaduBerinde** [comment]
LGTM. I definitely saw cases where checking out a different commit in master didn't update the submodule until I ran `make` or `make .bootstrap`.

**Comment by dt** [comment]
@tamird rebuilding e.g. protoc is anything but cheap.

In general, the tools only really need to be rebuilt before they're invoked (via `make`), so I'm fine not rebuilding them on every branch change but rather only when `make` is run.

**Comment by dt** [comment]
Potentially we could/should remove `make .bootstrap` from all the scm hooks and just rebuild tools at `make` time, and potentially even go further and split `.bootstrap` up to only build applicable tools -- eg. linters for `make check` and protoc for `make protobuf`, etc.

**Pull request closed without merging**
