### PR TITLE
sql: remove 19.1->19.2 foreign key migration references

### LINKED ISSUE #42753: sql: remove the easily removable 19.1 foreign key-related cruft
As one step in finishing the foreign key refactoring described in #37255, we need to stop pinning foreign key constraints to individual indexes in 20.1, which was a measure taken in 19.2 to preserve compatibility with 19.1 during the version upgrade (among other reasons). The first steps are to remove the 19.2 version gate and some of the low-hanging fruit of unused protobuf fields.

The 19.2 version gate has an associated cluster version `VersionTopLevelForeignKeys`, and we should remove all the usages of it and preserve only the 19.2 code paths. (Note that the same cluster version is also used for gating some largely-unrelated schema change functionality, but that shouldn't pose any problems when removing the version gates.) This should be straightforward.

We should also remove `TableDescriptor.MaybeDowngradeForeignKeyRepresentation()`, which transforms 19.2-style descriptors to 19.1-style ones so they could be written to disk, and the `legacy_upgraded_from_{origin,referenced}_reference`, which only existed for verifying consistency.

----

In due time, we should also remove the `legacy_{origin,referenced}_index` fields, which indicate "the" indexes used for a foreign key, and indexes should instead be determined on the fly whenever these fields are read to determine "the" index associated with a foreign key.

Unlike the above steps, this is not straightforward. The places that need to read this field are during (a) the runtime foreign key checks (which will likely go away in 20.1 eventually), and (b) schema changes that drop indexes, since we need to enforce that at least one usable index exists on each side of the foreign key relationship. Part (a) could probably be worked around in the short term by creating a method to arbitrarily pick an index out of the indexes that can be used validly, and dropping that in everywhere, though it would be throwaway code. Part (b) requires some care to determine which indexes can actually be validly removed. I'm mentioning this now because it's related to the above, but it'll probably have to be a separate later step.

### PR DESCRIPTION
**Pull request by otan**
Resolves #42753

This removes some of the now defunct protobuf fields and downgrades for
foreign keys when migrating from 19.1 to 19.2.

Changes roughly include:
* Removing any gate relying on "VersionTopLevelForeignKeys".
* Removing references for MaybeDowngradeForeignKeyRepresentation.
* Removing references for the unused protobuf fields of
`legacy_upgraded_from_{origin,referenced}_reference`.

No release note as this should not result in any defined behaviour on
20.1.

Release note: None

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
We should also get rid of the `legacy_upgraded_from_{origin,referenced}_reference` fields from structured.proto (and `reserve` them).

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-:-Lv7Nm-q7-R_TtPuy2rC:bp2kdzr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @otan)

___
*[pkg/sql/alter_table.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-Lv7NB8e4b12RjcwOOEK:-Lv7NB8e4b12RjcwOOEL:b-8i3w3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd9140e19592f540b7365792d7c8bb789072d5/pkg/sql/alter_table.go#L907)):*
> ```Go
> 		col.Nullable = true
> 
> 		// In 19.2 and above, add a check constraint equivalent to the non-null
> ```

The "In 19.2 and above" part can be removed.
___
*[pkg/sql/sqlbase/structured.go, line 2547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-Lv7N1rRAjtZqrbewU3u:-Lv7N1rRAjtZqrbewU3v:b66cfea) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd9140e19592f540b7365792d7c8bb789072d5/pkg/sql/sqlbase/structured.go#L2547)):*
> ```Go
> 				// We also drop the constraint immediately instead of queuing a mutation
> 				// unless the cluster is fully upgraded to 19.2, for backward
> 				// compatibility.
> ```

This part of the comment can be removed.

**Review by otan — COMMENTED** [review]
I was debating the comments usefulness. I have removed them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-:-Lv7OemABuJM9JKLDRHW:b-1zlj76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @lucy-zhang)

___
*[pkg/sql/alter_table.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-Lv7NB8e4b12RjcwOOEK:-Lv7OiYqDmeF5xwOl8hG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd9140e19592f540b7365792d7c8bb789072d5/pkg/sql/alter_table.go#L907)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

The "In 19.2 and above" part can be removed.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-Lv7N1rRAjtZqrbewU3u:-Lv7OpkKAXgC2-LSM7wH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd9140e19592f540b7365792d7c8bb789072d5/pkg/sql/sqlbase/structured.go#L2547)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This part of the comment can be removed.
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_table.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42889#-Lv7NB8e4b12RjcwOOEK:-Lv7QWJv-OLyWetcdDbM:b-3i8wtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd9140e19592f540b7365792d7c8bb789072d5/pkg/sql/alter_table.go#L907)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we keep `Add a check constraint equivalent to the non-null constraint and drop it in the schema changer.`?

**Pull request merged**
