### PR TITLE
cli/start: factor some of the process shutdown logic

### PR DESCRIPTION
**Pull request by knz**
Currently working on fixing #89974. This PR is a prerequisite to that.

See the individual commits for details.

Informs #88837. 

cc @andreimatei

### CODE REVIEW

**Comment by knz** [comment]
@aliher1911 could you help with reviewing this?

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-:-NEgSJuM66xYEuoXWKzR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/start.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfs1ua4blKnw8EsOFE:-NEfs1ua4blKnw8EsOFF:b-f35v9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L637)):*
> ```Go
> 			// Server started, notify the shutdown monitor running concurrently.
> 			if shutdownInProgress := serverStatusMu.setStarted(); shutdownInProgress {
> 				// The shutdown code is taking a shortcut. Help it along.
> ```

xIt'd be good to say more specific things than "help it along". And also "the shutdown code is taking a shortcut" won't make sense to any readers (it took a while for it to make sense to me).

How about if we make `serverStatusMu.startShutdown()` return either the `Stopper` or `nil` depending on whether it's up to the caller to stop the stopper or not, and extract the code of the goroutine for `waitForShutdown()` into a separate function that receives its stopper through `serverStatusMu.startShutdown()`, and make `setStarted()` take the stopper as an argument? Then I think the responsibility of stopping the stopper would be more apparent - at first the server startup code owns it, and then it passes it to the server shutdown code through this `serverStatusMu`.
___
*[`pkg/cli/start.go` line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfpgFV1F3c0ctWrI3R:-NEfpgFV1F3c0ctWrI3S:b-ez1iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L688)):*
> ```Go
> // server (in waitForShutdown).
> //
> // This is needed because it isn't safe to try to
> ```

bad wrap
___
*[`pkg/cli/start.go` line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfplDW8hOe4jMPQSYj:-NEfplDW8hOe4jMPQSYk:b-2rglg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L688)):*
> ```Go
> // server (in waitForShutdown).
> //
> // This is needed because it isn't safe to try to
> ```

what is "this"? Consider putting more words.
___
*[`pkg/cli/start.go` line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEft6J69qd42RSCyqcg:-NEft6J69qd42RSCyqch:b-wukeao) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L703)):*
> ```Go
> // setStarted marks the server as started. It returns whether
> // shutdown has been requested already. In that case, we know that
> // the shutdown goroutine did not use the stopper, so the
> ```

what happened to your wrapping setup? :P`
___
*[`pkg/cli/start.go` line 809 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfrQX7BcJTKQSpeQbh:-NEfrQX7BcJTKQSpeQbi:b-34kjx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L809)):*
> ```Go
> 		// runs concurrently with the timeout check below.
> 		go func() {
> 			useSoftDrain := serverStatusMu.startShutdown()
> ```

I think a comment here spelling out that we can't drain a server that wasn't started would help.
___
*[`pkg/cli/start.go` line 908 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgP1Yz5eWHXpe0HZ07:-NEgP1Yz5eWHXpe0HZ08:b-5fpn5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a2544daa5aca1a0384ea4dcfa47ca1e035d4a96/pkg/cli/start.go#L908)):*
> ```Go
> 	serverStatusMu *serverStatus,
> 	stopWithoutDrain chan struct{},
> 	gracefulDrain bool,
> ```

I think it'd be nice for `gracefulDrain` to have a comment, perhaps hinting at when you don't want to set it.
And consider calling it simply `drain`.
___
*[`pkg/cli/start.go` line 772 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgPNv46b47-Yi7uDDB:-NEgPNv46b47-Yi7uDDC:bh9jtm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf14d16ba7b5aa7acc1e6a965b1a1524455710d/pkg/cli/start.go#L772)):*
> ```Go
> 
> 	case <-stopper.ShouldQuiesce():
> 		// Receiving a signal on ShouldQuiesce means some internal system
> ```

This comment makes it sound like it's actually a thing for other subsystems to stop to stopper, but currently it is not; the only one that does it is the drain server (at least that's what I saw, but please check that that's true), which is quite a special guy. I would change the wording of this comment to not suggest that anybody can do it, and even point to the drain server.
I will be sure to change the wording, though, if we start using the stopper as a shutdown signaling mechanism in the sqlliveness patch.
___
*[`pkg/cli/start.go` line 783 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgQVBcAN1QqjO8a9ul:-NEgQVBcAN1QqjO8a9um:b-3ku8je) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf14d16ba7b5aa7acc1e6a965b1a1524455710d/pkg/cli/start.go#L783)):*
> ```Go
> 		log.StartAlwaysFlush()
> 		// Let the final steps of the shutdown below as usual.
> 		break
> ```

`break` not needed
___
*[`pkg/cli/start.go` line 743 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgS296DydXtkTeQosM:-NEgS296DydXtkTeQosN:b-a8istb) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L743)):*
> ```Go
> 	getS func() serverShutdownInterface,
> 	stopper *stop.Stopper,
> 	errChan chan error,
> ```

So you want to rename this to something more specific, like `serverStartupErrC` ?
We can change it it again later if the use of the channel expands; we'll have to adjust the comment about "we do not expect any application load, etc." anyway.
___
*[`pkg/cli/start.go` line 768 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgR2NU9KvzBipk6l-P:-NEgR2NV7CGtpp8PBz2p:bvq2c2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L768)):*
> ```Go
> 		// An error in errChat signals that the early server startup failed.
> 		returnErr = err
> 		// At this point, we do not expect any application load, etc., and
> ```

it will be unclear to reader what this comment translates to; add a reference to `gracefulDrain false`.
___
*[`pkg/cli/start.go` line 771 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgRbgX53TW7RRxerlW:-NEgRbgX53TW7RRxerlX:bu9gud5) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L771)):*
> ```Go
> 		// therefore we are OK with an expedited shutdown.
> 		startShutdownAsync(getS, stopper, serverStatusMu, stopWithoutDrain, false /* gracefulDrain */)
> 		// Don't return: we're shutting down gracefully.
> ```

this comment is confusing because none of the arms "returns". I don't think any comment is needed.
___
*[`pkg/cli/start.go` line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgQqrO3OCcSB7Bfwt0:-NEgQqrO3OCcSB7Bfwt1:b-8g3dzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L772)):*
> ```Go
> 		startShutdownAsync(getS, stopper, serverStatusMu, stopWithoutDrain, false /* gracefulDrain */)
> 		// Don't return: we're shutting down gracefully.
> 		break
> ```

break not needed

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90143)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/cli/start.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfs1ua4blKnw8EsOFE:-NEk9k3T7t9xD5uNvJ3W:b-l7s6fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L637)):*
> It'd be good to say more specific things than "help it along"

Good idea. Done.

>  Then I think the responsibility of stopping the stopper would be more apparent 

This is a pretty good idea. I like it. However, I want to make a honest attempt at making it readable, and I don't have the mental bandwidth right now (currently focusing on #89966). I filed this issue to follow up on your suggestion: #90233 and will look at it in a few days.
___
*[`pkg/cli/start.go` line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfpgFV1F3c0ctWrI3R:-NEkAlHm1akei6gPcHsa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L688)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

bad wrap
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfplDW8hOe4jMPQSYj:-NEkAxZqEwtU-0zg12YK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L688)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what is "this"? Consider putting more words.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEft6J69qd42RSCyqcg:-NEkAyRM9wP69loHyYCE:bqbk2o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L703)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what happened to your wrapping setup? :P`
</blockquote></details>

yeah I removed words after the first wrap and didn't rewrap. Fixed.
___
*[`pkg/cli/start.go` line 809 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEfrQX7BcJTKQSpeQbh:-NEkBhUIElruh3Uhr6Id:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f626ec459e763640958e246c63efde48e14c8b7/pkg/cli/start.go#L809)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think a comment here spelling out that we can't drain a server that wasn't started would help.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 908 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgP1Yz5eWHXpe0HZ07:-NEkCgxz-GOytwIjwh79:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a2544daa5aca1a0384ea4dcfa47ca1e035d4a96/pkg/cli/start.go#L908)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it'd be nice for `gracefulDrain` to have a comment, perhaps hinting at when you don't want to set it.
And consider calling it simply `drain`.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 772 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgPNv46b47-Yi7uDDB:-NEkEDl55wbKcElwtcKE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf14d16ba7b5aa7acc1e6a965b1a1524455710d/pkg/cli/start.go#L772)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment makes it sound like it's actually a thing for other subsystems to stop to stopper, but currently it is not; the only one that does it is the drain server (at least that's what I saw, but please check that that's true), which is quite a special guy. I would change the wording of this comment to not suggest that anybody can do it, and even point to the drain server.
I will be sure to change the wording, though, if we start using the stopper as a shutdown signaling mechanism in the sqlliveness patch.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 783 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgQVBcAN1QqjO8a9ul:-NEkDJZHEiyveMbX3BwG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf14d16ba7b5aa7acc1e6a965b1a1524455710d/pkg/cli/start.go#L783)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`break` not needed
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 743 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgS296DydXtkTeQosM:-NEkDMNx75x1eMPFU683:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L743)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So you want to rename this to something more specific, like `serverStartupErrC` ?
We can change it it again later if the use of the channel expands; we'll have to adjust the comment about "we do not expect any application load, etc." anyway.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 768 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgR2NU9KvzBipk6l-P:-NEkDhb7DdTfzhvVQMxO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L768)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it will be unclear to reader what this comment translates to; add a reference to `gracefulDrain false`.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 771 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgRbgX53TW7RRxerlW:-NEkDH7U-d0hRSh-t4hP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L771)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment is confusing because none of the arms "returns". I don't think any comment is needed.
</blockquote></details>

Done.
___
*[`pkg/cli/start.go` line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/90143#-NEgQqrO3OCcSB7Bfwt0:-NEkDBv90Aas5YYrg4gR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edad9711ff14260aa6b3d60fd3624a27608b5c6d/pkg/cli/start.go#L772)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

break not needed
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR

bors r=andreimatei

**Pull request merged**
