### PR TITLE
server: fix tenant auth on statements http endpoint

### LINKED ISSUE #85404: server: tenant auth causes a panic on Statements HTTP endpoint
When attempting to load the tenant HTTP endpoints for statement stats, I see a panic due to a failed authorization:

```
demo@127.0.0.1:26257/defaultdb> *
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:838
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:220
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:818
*   | github.com/cockroachdb/cockroach/pkg/server.(*adminPrivilegeChecker).requireViewActivityOrViewActivityRedactedPermission
*   | 	github.com/cockroachdb/cockroach/pkg/server/admin.go:3494
*   | github.com/cockroachdb/cockroach/pkg/server.(*tenantStatusServer).CombinedStatementStats
*   | 	github.com/cockroachdb/cockroach/pkg/server/tenant_status.go:493
*   | github.com/cockroachdb/cockroach/pkg/server.(*tenantStatusServer).Statements
*   | 	github.com/cockroachdb/cockroach/pkg/server/tenant_status.go:538
*   | github.com/cockroachdb/cockroach/pkg/server/serverpb._Status_Statements_Handler.func1
*   | 	github.com/cockroachdb/cockroach/pkg/server/serverpb/bazel-out/darwin_arm64-fastbuild/bin/pkg/server/serverpb/serverpb_go_proto_/github.com/cockroachdb/cockroach/pkg/server/serverpb/status.pb.go:8665
*   | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
 ```

I think the recently added authorization code in https://github.com/cockroachdb/cockroach/pull/84198 neglected to populate the `adminPrivilegeChecker` on the tenant with the proper fields (https://github.com/cockroachdb/cockroach/blob/e169a160e82af8f93cb44049cc31edaf1b566ce4/pkg/server/tenant.go#L213). There is a testing gap here.

Jira issue: CRDB-18233

### PR DESCRIPTION
**Pull request by Santamaura**
This patch resolves a panic due to failed authorization
by adding in the missing fields cluster.Settings and
makePlanner function to the privilegechecker in tenant.go.

Resolves #85404 

Release note (bug fix): fixes a panic when loading tenant http
endpoints for statement stats

After changes on multi-tenant:
Without system privileges:
Screen Shot 2022-08-01 at 5 28 02 PM

With `VIEWACTIVITY`:
Screen Shot 2022-08-01 at 5 28 33 PM

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
Thanks for picking this up. Can you see if you could add a test in `tenant_status_test.go` as well? I'm not sure why nothing failed in there with your change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8OzYd6BqWyUCx396AT:be47js7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @Santamaura)

___
*[`pkg/server/tenant.go` line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8OxKej2O-GQSI331aj:-N8OxKej2O-GQSI331ak:bplt3g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9dd0903dc11c4b401bcd2749899e6d2f7d3b37/pkg/server/tenant.go#L230)):*
> ```Go
> 		makePlanner: func(opName string) (interface{}, func()) {
> 			// This is a hack to get around a Go package dependency cycle. See comment
> 			// in sql/jobs/registry.go on planHookMaker.
> ```

this comment is inaccurate. there is no `sql/jobs/registry.go` file anymore. the new file is in `pkg/scheduledjobs/env.go` I think that you're referring to here.

that said, you should have a comment on the `adminPrivilegeChecker.makePlanner` field that explains the usage. You can refer *there* to the `planHookMaker` as inspiration for avoiding import cycles but otherwise it's too messy to route people to unrelated code. When I'm initializing `adminPrivilegeChecker` the comment on the `makePlanner` field should explain what I should return as the `interface{}` to be cast to because it's **not** the same type as in the jobs version.
___
*[`pkg/server/tenant.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8OyqHuBeHg8ufl1KJE:-N8OyqHuBeHg8ufl1KJF:b-1iabnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9dd0903dc11c4b401bcd2749899e6d2f7d3b37/pkg/server/tenant.go#L282)):*
> ```Go
> 
> 	debugServer := debug.NewServer(baseCfg.AmbientCtx, args.Settings, s.pgServer.HBADebugFn(), s.execCfg.SQLStatusServer)
> 	adminAuthzCheck := tenantStatusServer.privilegeChecker
> ```

you should assign the privilege checker to `adminAuthzCheck` above and then use it in both places instead pulling it out of `tenantStatusServer` here. this gives the impression that you need the `tenantStatusServer` in order to use the checker but that's not quite true.

**Review by Santamaura — COMMENTED** [review]
I spent some time looking at this test file trying to see if there was a straightforward way of just testing auth but wasn't able to find one. Perhaps someone has some ideas on how we can test it here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8PU5D3B0RLvJoGUSup:b-19ove0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/tenant.go` line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8OxKej2O-GQSI331aj:-N8PWd0GAt3SQ6Lm-69F:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9dd0903dc11c4b401bcd2749899e6d2f7d3b37/pkg/server/tenant.go#L230)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this comment is inaccurate. there is no `sql/jobs/registry.go` file anymore. the new file is in `pkg/scheduledjobs/env.go` I think that you're referring to here.

that said, you should have a comment on the `adminPrivilegeChecker.makePlanner` field that explains the usage. You can refer *there* to the `planHookMaker` as inspiration for avoiding import cycles but otherwise it's too messy to route people to unrelated code. When I'm initializing `adminPrivilegeChecker` the comment on the `makePlanner` field should explain what I should return as the `interface{}` to be cast to because it's **not** the same type as in the jobs version.
</blockquote></details>

Done
___
*[`pkg/server/tenant.go` line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8OyqHuBeHg8ufl1KJE:-N8PWiaL6X_Nr8s45Wox:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/da9dd0903dc11c4b401bcd2749899e6d2f7d3b37/pkg/server/tenant.go#L282)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

you should assign the privilege checker to `adminAuthzCheck` above and then use it in both places instead pulling it out of `tenantStatusServer` here. this gives the impression that you need the `tenantStatusServer` in order to use the checker but that's not quite true.
</blockquote></details>

Done

**Review by dhartunian — COMMENTED** [review]
@santamaura can you at least test via `./cockroach demo --multitenant=true`. You can connect at port 8080 for the tenant. the default console demo drops you into is on the tenant and you can create a user in there to try in the browser.

as for `tenant_status_test.go`, the calls to `serverutils.GetJSONProto` automatically inject an admin user. you can use some of the other methods in there to login as a non-admin and perhaps use sql to set the roles you need and then making the HTTP request afterwards.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8PlUm-CN4Y6Ze9-swM:btrfdli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by Santamaura — COMMENTED** [review]
> @Santamaura can you at least test via ./cockroach demo --multitenant=true. You can connect at port 8080 for the tenant. the default console demo drops you into is on the tenant and you can create a user in there to try in the browser.

Done, it seems to be ok now

> as for tenant_status_test.go, the calls to serverutils.GetJSONProto automatically inject an admin user. you can use some of the other methods in there to login as a non-admin and perhaps use sql to set the roles you need and then making the HTTP request afterwards.

:thumbsup: Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8QJSfF1WZlnmepVebC:b-jhfqe0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @Santamaura)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8TnK4pCSmKbqyq257F:-N8TnK4pCSmKbqyq257G:bb92hi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c19dbd64254d21c80006e50ca836785cc9ccad6/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1194)):*
> ```Go
> 	// privileges.
> 	require.Error(t, err)
> 	if helper.hostCluster.Server(0).ClusterSettings().Version.IsActive(ctx, clusterversion.SystemPrivilegesTable) {
> ```

I don't follow this test logic because I'm unfamiliar with how this works...when is this expression true? Are we granting the privileges somewhere?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8TnK4pCSmKbqyq257F:-N8TpM3z63U6RgnGSxt6:bk02xya) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c19dbd64254d21c80006e50ca836785cc9ccad6/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1194)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I don't follow this test logic because I'm unfamiliar with how this works...when is this expression true? Are we granting the privileges somewhere?
</blockquote></details>

It's true when the version that introduced the `system.privileges` table is active, otherwise the `GRANT` statement below won't work

**Review by dhartunian — COMMENTED** [review]
xzdfsdfsdf

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8Up5Y5-LtedIFXmc5j:bjx4aeh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8TnK4pCSmKbqyq257F:-N8Z4jmeAHfy3nyXHXCm:bgt8qa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c19dbd64254d21c80006e50ca836785cc9ccad6/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1194)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

It's true when the version that introduced the `system.privileges` table is active, otherwise the `GRANT` statement below won't work
</blockquote></details>

I understand that. I'm just confused because this is always active on `master` right, so why do we need to check for it?

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @zachlite)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8TnK4pCSmKbqyq257F:-N8Z5nGh7kF5xpXSgOAT:bgcbms4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c19dbd64254d21c80006e50ca836785cc9ccad6/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1194)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I understand that. I'm just confused because this is always active on `master` right, so why do we need to check for it?
</blockquote></details>

Yeah, I guess I added it so that it's more defensible if changes for whatever reason get back-ported, @dhartunian did you want me to remove the check?

**Review by dhartunian — CHANGES_REQUESTED** [review]
(lol apologies for posting gibberish above)

Can you also explain why this usage doesn't have a definition for `makePlanner`? https://github.com/cockroachdb/cockroach/blob/be41f0a13e036f452e51f51be93f64da30df3d92/pkg/server/server.go#L719

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8dEBsA6JBM5sS0KlQK:b-un3oly)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 1194 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-N8TnK4pCSmKbqyq257F:-N8dE3ao-rDe-SKv5V53:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c19dbd64254d21c80006e50ca836785cc9ccad6/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L1194)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Yeah, I guess I added it so that it's more defensible if changes for whatever reason get back-ported, @dhartunian did you want me to remove the check?
</blockquote></details>

Thanks.

**Review by Santamaura — COMMENTED** [review]
It gets added further down when we have an `execCfg` I added `makePlanner` and set it as `nil` there to make it more clear that it has that field.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8dURNICiwsOUUhayTM:ba8h6g4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

**Comment by Santamaura** [comment]
Friendly bump on this @dhartunian it needs to be in for 22.2

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85407#-:-N8xmxC-29zehNxIA7gb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, @Santamaura, and @zachlite)

**Comment by Santamaura** [comment]
TFTR!

**Pull request merged**
