### PR TITLE
builtins: add builtin to signal complete to stream ingestion job

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a builtin to signal to a running stream ingestion job
to complete its ingestion. It does this by setting a bool on the jobs
progress that will be polled periodically by the stream ingestion job.

The builtin does not wait until the job has performed the necessary cleanup
to get the ingested cluster to a consistent state. It returns the job ID
of the job that has been signalled and can be used in conjunction with
SHOW JOBS WHEN COMPLETE.

Note, this change does not hookup the builtin with the stream ingestion
job. That will be done in a follow up PR.

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
WIP to get some comments while I write up tests!

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/sql/sem/builtins/builtins.go, line 4822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTBGYXzBm1Dw9rMw29R:-MTBGYXzBm1Dw9rMw29S:b9jf9m4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e87f83a5092e67656a6607650e7ccd5ff8dfd3db/pkg/sql/sem/builtins/builtins.go#L4822)):*
> ```Go
> 			}
> 
> 			// Poll the job until we observe that it has finished.
> ```

As discussed in person, let's not wait for this job to finish.  Instead, return job id and using existing show job when complete to ait.

Also, I think this is complex enough -- we ought to move implementation to streamingbase.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/ccl/streamingccl/streamingutils/utils.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCad-w1anGBQQtb04x:-MTCad-w1anGBQQtb04y:b-gogrm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils.go#L28)):*
> ```Go
> func doCompleteIngestion(evalCtx *tree.EvalContext, txn *kv.Txn, jobID int) error {
> 	// Get the job payload for job_id.
> 	const jobsQuery = `SELECT progress FROM system.jobs WHERE id=$1`
> ```

do you want to add `FOR UPDATE` clause?
___
*[pkg/ccl/streamingccl/streamingutils/utils_test.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCcn1q6j02vEwKWZDt:-MTCcn1q6j02vEwKWZDu:b-mxxewf) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils_test.go#L64)):*
> ```Go
> 
> 	group := ctxgroup.WithContext(ctx)
> 	group.GoCtx(func(ctx context.Context) error {
> ```

Why do we need to run this in a go routine?  
___
*[pkg/ccl/streamingccl/streamingutils/utils_test.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCcRBtEQzRYuZhx7fE:-MTCcRBtEQzRYuZhx7fF:bj89hy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils_test.go#L89)):*
> ```Go
> 	// Give a chance for the above group to schedule in order to test that SHOW
> 	// JOBS WHEN COMPLETE does block until the job is canceled.
> 	time.Sleep(2 * time.Millisecond)
> ```

Why do we need to sleep? (oh noo!: if you absolutely need to, just create a `chan struct{}` and close that channel inside go routine.
and read from the channel here.

Also, why do we need to cancel job?
___
*[pkg/sql/sem/builtins/builtins.go, line 4786 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCdBEuAWOKySLdh2cF:-MTCdBEuAWOKySLdh2cG:b5m8kai) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/sql/sem/builtins/builtins.go#L4786)):*
> ```Go
> 				"This function does not wait for the job to reach that terminal state, " +
> 				"but instead returns the job id as soon as it has signaled the job to complete." +
> 				"and can be used in conjunction with SHOW JOBS WHEN COMPLETE.",
> ```

love it.

**Comment by miretskiy** [comment]
You probably need to update PR description.

**Review by pbardea — COMMENTED** [review]
I like the way this is looking!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-:-MTCx-3-1kfUnXeHQxmV:b-1p1tsx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[docs/generated/sql/functions.md, line 2271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCvgx64rMkN5JveM8Y:-MTCvgx64rMkN5JveM8Z:bo7vsh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/docs/generated/sql/functions.md#L2271)):*
> ```Markdown
> <thead><tr><th>Function &rarr; Returns</th><th>Description</th></tr></thead>
> <tbody>
> <tr><td><a name="crdb_internal.complete_stream_ingestion_job"></a><code>crdb_internal.complete_stream_ingestion_job(job_id: <a href="int.html">int</a>) &rarr; <a href="int.html">int</a></code></td><td><span class="funcdesc"><p>This function can be used to signal a running stream ingestion job to complete. The job will eventually stop ingesting, revert to the latest resolved timestamp and leave the cluster in a consistent state. This function does not wait for the job to reach that terminal state, but instead returns the job id as soon as it has signaled the job to complete.and can be used in conjunction with SHOW JOBS WHEN COMPLETE.</p>
> ```

Looks like there's a bit of a formatting snafu on the last line (`... to complete.and can...`).
___
*[pkg/ccl/streamingccl/streamingutils/utils.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCvv_X4r0f4umYBKYA:-MTCvv_X4r0f4umYBKYB:bo4d497) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils.go#L47)):*
> ```Go
> 	var ok bool
> 	if sp, ok = progress.GetDetails().(*jobspb.Progress_StreamIngest); !ok {
> 		return errors.Newf("job %d: not of expected type StreamIngest")
> ```

Missed passing in the job ID in this formatted string.
___
*[pkg/ccl/streamingccl/streamingutils/utils_test.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCcn1q6j02vEwKWZDt:-MTCwXKNCzXqHOYZQ1rC:btw0kpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils_test.go#L64)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Why do we need to run this in a go routine?  
</blockquote></details>

+1 I think that it's enough to test that when we load the job again, the sentinel is set.

If we're leaking some resources, maybe we can defer a cancel job command?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @pbardea)

___
*[docs/generated/sql/functions.md, line 2271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCvgx64rMkN5JveM8Y:-MTDQ0Or6NzWvJkYbxln:b-d4cwro) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/docs/generated/sql/functions.md#L2271)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Looks like there's a bit of a formatting snafu on the last line (`... to complete.and can...`).
</blockquote></details>

fixed in builtins.go
___
*[pkg/ccl/streamingccl/streamingutils/utils.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCad-w1anGBQQtb04x:-MTDPI4PE4tw7S_JAszS:bl7tnra) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils.go#L28)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you want to add `FOR UPDATE` clause?
</blockquote></details>

good point, done.
___
*[pkg/ccl/streamingccl/streamingutils/utils.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCvv_X4r0f4umYBKYA:-MTDPJjK-LKHqhQOvWCi:b4g0byo) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils.go#L47)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Missed passing in the job ID in this formatted string.
</blockquote></details>

oops, done.
___
*[pkg/ccl/streamingccl/streamingutils/utils_test.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCcn1q6j02vEwKWZDt:-MTDQ9gtDjb8t0Wok7aX:b-115kn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils_test.go#L64)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

+1 I think that it's enough to test that when we load the job again, the sentinel is set.

If we're leaking some resources, maybe we can defer a cancel job command?
</blockquote></details>

i got carried away and threw in a SHOW JOBS WHEN COMPLETE in the test too...unnecessarily. Removed it now :)
___
*[pkg/ccl/streamingccl/streamingutils/utils_test.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTCcRBtEQzRYuZhx7fE:-MTD_feDBD5QDNZ1CJcU:b-q6m5j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/58bd8226364c3e3a40c3a273ceab64b0aa9230ed/pkg/ccl/streamingccl/streamingutils/utils_test.go#L89)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Why do we need to sleep? (oh noo!: if you absolutely need to, just create a `chan struct{}` and close that channel inside go routine.
and read from the channel here.

Also, why do we need to cancel job?
</blockquote></details>

yup, removed all the cruft. Test is much simpler now!
___
*[pkg/sql/sem/builtins/builtins.go, line 4822 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60291#-MTBGYXzBm1Dw9rMw29R:-MTDP_Qw-mWlQMSs9TW5:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e87f83a5092e67656a6607650e7ccd5ff8dfd3db/pkg/sql/sem/builtins/builtins.go#L4822)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

As discussed in person, let's not wait for this job to finish.  Instead, return job id and using existing show job when complete to ait.

Also, I think this is complex enough -- we ought to move implementation to streamingbase.
</blockquote></details>

done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 2 of 11 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60291)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @miretskiy, and @pbardea)

**Review by miretskiy — APPROVED** [review]

**Review by pbardea — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=miretskiy,pbardea

**Pull request merged**
