### PR TITLE
vendor: update readline dep, use our fork

### PR DESCRIPTION
**Pull request by jordanlewis**
This fixes a bug with long sql histories getting rewritten incorrectly.

### CODE REVIEW

**Comment by knz** [comment]
I see what you did there, but is this the right approach? Why not changing the `cli` dep to our fork directly?

**Comment by dt** [comment]
@knz We don't usually rewrite the import paths to point to our fork, at least if we have any intention of tracking upstream, going back if changes merge or even just merging upstream patches, since any internal imports in the lib need to be rewritten too.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16714#-:-Kn_fdedhOSpB1q16AU-:bv72m2h)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16714#-:-Kn_gJGUW273Wc_90TmZ:bnfp4nl)*

**Comment by knz** [comment]
ack, that makes sense, thanks.

**Pull request merged**
