### PR TITLE
sql/schemachanger: turn on COMMENT ON in declarative schema changer

### LINKED ISSUE #77327: schemachanger: implement COMMENT ON ... statements
This could be a good learning experience for getting acquainted with the declarative schema changer. Doing this will give exposure to all layers:
1. the COMMENT ON statements need to have hooks in `scbuildstmt`,
2. the `scbuildstmt` dependencies need to have some kind of interface or interface method for retrieving existing comments,
3. the internal executor needs to be plumbed into the `scbuild` dependencies to implement that,
4. the test dependencies therefore also need to mock the above
5. we can get rid of the placeholder string constant `__placeholder_comment__`
6. the `toPublic` paths for the comment elements need to be defined in `opgen`
7. new ops for setting comments need to be defined in `scop`
8. they need to be implemented in `scmutationexec`
9. which might in turn require some plumbing in the `mutationVisitorState` in `scexec`
10. there'll be a bunch of data-driven tests in `schemachanger/...` that need updating as a result of all this.

Epic: CRDB-13602

Jira issue: CRDB-13529

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Resolves #77327
Turn the fully supported flags on. There're a few differences on
error or logging output which should be legit.

Release note: None.

### CODE REVIEW

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81563)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/logictest/testdata/logic_test/event_log` line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2U5ogr5pPVsIXSBIQc:-N2U5ogr5pPVsIXSBIQd:b8aqq5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/event_log#L1004)):*
> ```
> WHERE "eventType" = 'comment_on_table'
> ----
> 1  {"Comment": "This is a table.", "EventType": "comment_on_table", "Statement": "COMMENT ON TABLE a IS 'This is a table.'", "TableName": "defaultdb.public.a", "Tag": "COMMENT ON TABLE", "User": "root"}
> ```

the statements in the new event log are actually closer to the original statements.
___
*[`pkg/sql/logictest/testdata/logic_test/privileges_comments` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2U5ye4EMOL2yHacdeM:-N2U5ye4EMOL2yHacdeN:b-90bhvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/privileges_comments#L26)):*
> ```
> COMMENT ON DATABASE d45707 IS 'd45707'
> 
> onlyif config local-legacy-schema-changer
> ```

these changes are basically because privilege checks are now at declarative schema changer with different error messages.

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/logictest/testdata/logic_test/event_log` line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2U5ogr5pPVsIXSBIQc:-N2WyO4y2gjsLiUzlF6w:b7dtl0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/event_log#L1004)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

the statements in the new event log are actually closer to the original statements.
</blockquote></details>

This looks wrong, don't we always want the fully resolved name? This looks fishy, we normally explicitly resolve them so that the exact object is known
___
*[`pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2WyqFNDKGha3njI1Nd:-N2WyqFNDKGha3njI1Ne:b-20f9mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags#L295)):*
> ```
> 
> # Test COMMENT ON COLUMN.
> skipif config local-legacy-schema-changer
> ```

This looks like a regression. We need to enable the ability to disable the feature.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2WyqFNDKGha3njI1Nd:-N2X8D-Y-hju2JNb7IK2:b-2qzv7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags#L295)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This looks like a regression. We need to enable the ability to disable the feature.
</blockquote></details>

This is actually not a regression, it's just how we get "feature name" from a statement. Previously we just put in a constant string like `COMMENT ON TABLE`. In declarative schema changer it seems wrong that we're only using the first two keywords from a statement as the feature name : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/schema_feature_name.go#L25-L25
This is not sufficient for something like `CREATE OR REPLACE FUNCTION` lol.

For now I just put a switch in this logic test to distinguish here :)
___
*[`pkg/sql/logictest/testdata/logic_test/event_log` line 1004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2U5ogr5pPVsIXSBIQc:-N2X81Pr8xr2M-lOmV8K:b-qocolt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/event_log#L1004)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This looks wrong, don't we always want the fully resolved name? This looks fishy, we normally explicitly resolve them so that the exact object is known
</blockquote></details>

good call. added logic to annotated table name and prefixes

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2WyqFNDKGha3njI1Nd:-N2X9QUiD60Uxw2KnL_E:b-o6ukg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags#L295)):*
>  put in a constant string like COMMENT ON TABLE. In declarative schema changer it seems wrong that we're only using the fir
probably a bad suggestion, but we may put something here to the info: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L49-L49
an extra field called `featureName`, if it's empty string then we get the first 1/2 keywords, otherwise we use the customized feature name.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2WyqFNDKGha3njI1Nd:-N2X9t8D1YiDiX39AWAV:bm773c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags#L295)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

>  put in a constant string like COMMENT ON TABLE. In declarative schema changer it seems wrong that we're only using the fir
probably a bad suggestion, but we may put something here to the info: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L49-L49
an extra field called `featureName`, if it's empty string then we get the first 1/2 keywords, otherwise we use the customized feature name.
</blockquote></details>

ha... I'm bad at formatting things, reposting my previous comment:

probably a bad suggestion, but we may put something here to the info: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L49-L49
an extra field called featureName, if it's empty string then we get the first 1/2 keywords, otherwise we use the customized feature name.

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2WyqFNDKGha3njI1Nd:-N2XGdGgDXBZbb0D1lYT:b64er8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9af08e5f832f280dc71ee2ea10377bed0b2ceda4/pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags#L295)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

ha... I'm bad at formatting things, reposting my previous comment:

probably a bad suggestion, but we may put something here to the info: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L49-L49
an extra field called featureName, if it's empty string then we get the first 1/2 keywords, otherwise we use the customized feature name.
</blockquote></details>

I think we should just modify: GetSchemaFeatureNameFromStmt to use the entire string outside of AlterTable. Trying to get away from hard-coding these and having a more centralized thing for them.

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/sem/tree/schema_feature_name.go` line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81563#-N2X_o2-3t7YNTSJcqn2:-N2X_o2-3t7YNTSJcqn3:bzg09ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e85c15c4360dc46713d125efaffcc1ba8416f1/pkg/sql/sem/tree/schema_feature_name.go#L28)):*
> ```Go
> 	case *CommentOnDatabase, *CommentOnSchema, *CommentOnTable,
> 		*CommentOnColumn, *CommentOnIndex, *CommentOnConstraint:
> 		return SchemaFeatureName(strings.Join(statementInfo[:3], " "))
> ```

Nit: Could just do statementTag here I think.

**Comment by chengxiong-ruan** [comment]
TFTR! @fqazi 
bors r+

**Pull request merged**
