### PR TITLE
ui: update redux-related typings

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7787)

### CODE REVIEW

**Comment by mrtracy** [comment]
LGTM, still not perfect but this kills a lot of `any` usage.

---

Reviewed 1 of 1 files at r1, 30 of 30 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-:-KMVuoqfDCggCZYY9cc-:1583719371)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVzIxWN1FY-WikuTEt:-KMVz7MEIO5xm-dS_hTT:1524226825) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L156)):*
> ```XML
> interface DatabaseSpecified {
>   params: { database_name: string; };
> }
> ```

Should this be replaced with `IInjectedProps`?

---

*[ui/app/containers/databases/databaseDetails.tsx, line 256 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVyTc3JOMDQc4TGuPj:-KMVyTc3JOMDQc4TGuPk:1039016513) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L256)):*
> ```XML
> // Base selectors to extract data from redux state.
> let tables = (state: AdminUIState, props: any): string[] => getDatabaseDetails(state, props) ? getDatabaseDetails(state, props).table_names : [];
> let grants = (state: AdminUIState, props: any): Grant[] => getDatabaseDetails(state, props) ? getDatabaseDetails(state, props).grants : [];
> ```

`getDatabaseDetails` specifies that props should be `DatabaseMainProps`, but really requires something of type `IInjectedProps`. Would it make sense to specify that here as well, instead of `any`?

---

*[ui/app/containers/databases/tableDetails.tsx, line 392 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMW-xFOypByPQE87eV4:-KMW-xFOypByPQE87eV5:-1724886985) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/tableDetails.tsx#L392)):*
> ```XML
> let columns = (state: AdminUIState, props: any): Column[] => getTableDetails(state, props) ? getTableDetails(state, props).getColumns() : [];
> let indexes = (state: AdminUIState, props: any): Index[] => getTableDetails(state, props) ? getTableDetails(state, props).getIndexes() : [];
> let grants = (state: AdminUIState, props: any): Grant[] => getTableDetails(state, props) ? getTableDetails(state, props).getGrants() : [];
> ```

Might also make sense to get rid of these `any`s if easy, while you're at it.

---

*[ui/app/redux/apiReducers.ts, line 58 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMW0FTkBwfzxo9TuoX7:-KMW0FTli866IBz4V9Ck:-1309229964) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/redux/apiReducers.ts#L58)):*
> ```XML
>   nodes: typeof nodesReducerState;
>   raft: typeof raftReducerState;
>   version: typeof versionReducerState;
> ```

Shame these can't be specified with constants :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787)*

**Comment by maxlang** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-:-KMW0SeWVfCf_EGh8L9P:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVzIxWN1FY-WikuTEt:-KMW11hY12zzEC0XlpaV:1951402556) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L156)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Should this be replaced with `IInjectedProps`?
</details>
Maybe?

---

*[ui/app/containers/databases/databaseDetails.tsx, line 256 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVyTc3JOMDQc4TGuPj:-KMW0ob4XPJYwltRanUB:2014171443) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L256)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> `getDatabaseDetails` specifies that props should be `DatabaseMainProps`, but really requires something of type `IInjectedProps`. Would it make sense to specify that here as well, instead of `any`?
</details>
I'm not following, but I'd be happy to review a follow-up

---

*[ui/app/containers/databases/tableDetails.tsx, line 392 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMW-xFOypByPQE87eV4:-KMW0wHTz1XLHasvpoav:-1279816132) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/tableDetails.tsx#L392)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Might also make sense to get rid of these `any`s if easy, while you're at it.
</details>
As above, not sure what the type is but happy to review a followup.

---

*[ui/app/redux/apiReducers.ts, line 58 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMW0FTkBwfzxo9TuoX7:-KMW0xx4PQn0VVRMsbBJ:677251183) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/redux/apiReducers.ts#L58)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Shame these can't be specified with constants :/
</details>
Yep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787)*

**Comment by tamird** [comment]
Review status: 0 of 30 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVzIxWN1FY-WikuTEt:-KMWCk7dvLIky3Co9dfh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L156)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Maybe?
</details>
Done.

---

*[ui/app/containers/databases/databaseDetails.tsx, line 256 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMVyTc3JOMDQc4TGuPj:-KMWCjfghvLAiuM4mpj8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/databaseDetails.tsx#L256)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not following, but I'd be happy to review a follow-up
</details>
Done.

---

*[ui/app/containers/databases/tableDetails.tsx, line 392 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787#-KMW-xFOypByPQE87eV4:-KMWCjADNVg6aqdgFK-m:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f5db292d85146418db22fd39c5c80ceb4650a/ui/app/containers/databases/tableDetails.tsx#L392)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> As above, not sure what the type is but happy to review a followup.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7787)*

**Pull request merged**
