### PR TITLE
sql: Log event for TRUNCATE TABLE

### LINKED ISSUE #25867: sql: log event for TRUNCATE
@a-robinson, @jseldess and I just spend a merry 30 minutes trying to figure out what was going on on cobalt, one of our production clusters.

The outcome was that someone must have `TRUNCATE`d a large table which left lots of empty ranges, which led to an imbalance of live bytes. We needed to look at raw range boundaries to figure this out.

There should be an event log for `TRUNCATE` similar to the one you get when a table gets created:

image

cc @jordanlewis for triage (and apologies for what is probably the wrong A-sql-* category)

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #25867

Release note (sql change): TRUNCATE TABLE commands are now logged in the
event log.

### CODE REVIEW

**Comment by a-robinson** [comment]
screen shot 2018-05-23 at 1 57 15 pm

**Review by vilterp — APPROVED** [review]
Thanks!

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/event_log.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDOau62YKk5q69aIlT:-LDDOau62YKk5q69aIlU:b3nm90s) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/sql/event_log.go#L43)):*
> ```Go
> 	// EventLogDropTable is recorded when a table is dropped.
> 	EventLogDropTable EventLogType = "drop_table"
> 	// EventLogTruncateTable is recorded when a table is dropped.
> ```

truncated not dropped

---

*[pkg/ui/src/util/eventTypes.ts, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP-Y6DT8wQFGti0kx:-LDDP-Y6DT8wQFGti0ky:bcdvrvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L9)):*
> ```XML
> type Event = protos.cockroach.server.serverpb.EventsResponse.Event;
> 
> // Recorded when a database is created.
> ```

might be nice to alphabetize this

---

*[pkg/ui/src/util/eventTypes.ts, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP1I_9oKJ_tAk-H5c:-LDDP1I_9oKJ_tAk-H5d:b-2zxdn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L63)):*
> ```XML
> export const databaseEvents = [CREATE_DATABASE, DROP_DATABASE];
> export const tableEvents = [
>   CREATE_TABLE, DROP_TABLE, TRUNCATE_TABLE, ALTER_TABLE, CREATE_INDEX,
> ```

And to alphabetize this as well

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-:-LDDP4KQ0-9Li-vFQWVY:bnfp4nl)*

**Comment by a-robinson** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/event_log.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDOau62YKk5q69aIlT:-LDDPfIN46KlkG6qdRqq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/sql/event_log.go#L43)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

truncated not dropped
</blockquote></details>

Done.

---

*[pkg/ui/src/util/eventTypes.ts, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP-Y6DT8wQFGti0kx:-LDDPlJ9-qxiKFrqi6OE:bub31wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L9)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

might be nice to alphabetize this
</blockquote></details>

Right now it's grouped logically by the object being acted on, which seems kind of nice to me. Mind if I leave it as is?

---

*[pkg/ui/src/util/eventTypes.ts, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP1I_9oKJ_tAk-H5c:-LDDPtYU3IME--G_q_yR:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L63)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

And to alphabetize this as well
</blockquote></details>

Same as above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-:-LDDPxdiDyFpHVTPLVqY:bz5mair)*

**Comment by vilterp** [comment]
I'm ok with the logical grouping.

**Comment by BramGruneir** [comment]
One last suggestion, but feel free to leave as is.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ui/src/util/eventTypes.ts, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP-Y6DT8wQFGti0kx:-LDDZTWQCUfnViqFpvIR:bazzwyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L9)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Right now it's grouped logically by the object being acted on, which seems kind of nice to me. Mind if I leave it as is?
</blockquote></details>

I like the logical, but perhaps call that out and alphabetize within those groupings?  The logical grouping wasn't clear to me while reviewing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-:-LDDZq3ME58XhL6-PzjI:b4oie7c)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/util/eventTypes.ts, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25868#-LDDP-Y6DT8wQFGti0kx:-LDDalmA5S6B0RmGtxUA:byqewhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/00e1666bda356816d02e3a2ce622390cb4373fff/pkg/ui/src/util/eventTypes.ts#L9)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I like the logical, but perhaps call that out and alphabetize within those groupings?  The logical grouping wasn't clear to me while reviewing.
</blockquote></details>

I'm not gonna burn another CI cycle on this, but doing it next time would be good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25868)*

**Pull request merged**
