### PR TITLE
sql: various COPY improvements

### PR DESCRIPTION
**Pull request by otan**
Refs: #41608

See individual commits for details.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myqs39o9BbKodFoyPMj):*
Can we add some testing here to validate that the options show up as unimplemented?
___
*[pkg/util/encoding/csv/reader_test.go, line 396 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr1z0n4DJpZQJl6VAq:-Myr1z0n4DJpZQJl6VAr:bw3mbpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L396)):*
> ```Go
> 		Escape: 'x',
> 		Input:  `"x"",",","xxx"",x,"xxxx,"` + "\n",
> 		Output: [][]string{{`"`, `,`, `x"`, `x`, `xx,`}},
> ```

I'm not following the 4th case.  If we just provide an escape character, shouldn't this show nothing or a parse error?
___
*[pkg/util/encoding/csv/reader_test.go, line 402 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr2o0b9wk35gwtFhvj:-Myr2o0b9wk35gwtFhvk:bmf3g39) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L402)):*
> ```Go
> 		Comma:  'x',
> 		Input:  `"x""x,x"xxx""x"xx"x"xxxx,"` + "\n",
> 		Output: [][]string{{`"`, `,`, `x"`, `x`, `xx,`}},
> ```

I think I'm missing something.  I would have thought that this would yield:

`'"',',"x"','"x','"xx'`
___
*[pkg/util/encoding/csv/writer_test.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MyrN9TT77AOUFUxqD6W:-MyrN9TT77AOUFUxqD6X:b-l8nzpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/writer_test.go#L54)):*
> ```Go
> 	{Input: [][]string{{"a", "a", "a"}}, Output: "a,a,a\n"},
> 	{Input: [][]string{{`\.`}}, Output: "\"\\.\"\n"},
> 	{Input: [][]string{{`"`, `,`, `x"`, `x`, `xx,`}}, Escape: 'x', Output: `"x"",",","xxx"",x,"xxxx,"` + "\n"},
> ```

More confusion on my part- why is a single x being interpreted as x instead of as the escape, and thus a parse error?

**Comment by awoods187** [comment]
Exciting stuff--can we list explicitly what will remain unimplemented for Copy from the linked issue?

**Comment by ajstorm** [comment]
It's everything in https://github.com/cockroachdb/cockroach/issues/41608
except for the ESCAPE option.

**Comment by awoods187** [comment]
Awesome news!

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myqs39o9BbKodFoyPMj):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we add some testing here to validate that the options show up as unimplemented?
</blockquote></details>

the new tests in TestUnimplementedSyntax in `parse_test.go` already does this
___
*[pkg/util/encoding/csv/reader_test.go, line 396 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr1z0n4DJpZQJl6VAq:-MysQ9wY9XRG0Bl7634h:br5u1ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L396)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm not following the 4th case.  If we just provide an escape character, shouldn't this show nothing or a parse error?
</blockquote></details>

"x"",",","xxx"",x,"xxxx,"` shouldn't.
breaking it down:

`"x"",`: `"x""` - the  wrapping `"` indicates to use escapes, `x` escapes `"`, so it is `"`.
`",",`: the `","` is just `,`
`"xxx"",`: the x escapes x, then x escapes ", so it is `x"`
`x,`: no quotes, so we don't have to escape anything. so it is `x` (see below comment)
`"xxxx,"`, x escapes x twice, then a comma, so `xx,`



_Code quote:_
```Go
"x"",",","xxx"",x,"xxxx,"` + "\n"
```
___
*[pkg/util/encoding/csv/reader_test.go, line 402 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr2o0b9wk35gwtFhvj:-MysQi5eA_XhbdRLRnTm:bymlh1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L402)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I think I'm missing something.  I would have thought that this would yield:

`'"',',"x"','"x','"xx'`
</blockquote></details>

`"x""x`, yields `"`, then a delimiter
`,x` yields `,` then a delimiter
`"xxx""x` yields `"x", then a delimiter
`"xx"x": point of contention. begin quote, then x escapes x, so it becomes just `x`, then a delimiter
`"xxxx,"`: quote, two escapes x's, then a comma, so `xx,`

fwiw all these outputs are from PG
___
*[pkg/util/encoding/csv/writer_test.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MyrN9TT77AOUFUxqD6W:-MysRPGU9xmNj43EP2K2:b20syfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/writer_test.go#L54)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

More confusion on my part- why is a single x being interpreted as x instead of as the escape, and thus a parse error?
</blockquote></details>

because things that are not in quotes are their accepted "raw value".

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/pgwire/testdata/pgtest/copy, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MysY3L65XwciWJby8mT:-MysY3L87rk9wGBfy79m:b-p72ei6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e151af5d60a67ea215a4f16db740d395f42121e7/pkg/sql/pgwire/testdata/pgtest/copy#L297)):*
> ```
> {"Type":"DataRow","Values":[{"text":"1"},{"text":"x\",x"}]}
> {"Type":"CommandComplete","CommandTag":"SELECT 2"}
> {"Type":"ReadyForQuery","TxStatus":"I"}
> ```

just to double-check, these new ones also passed against PG?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/util/encoding/csv/reader.go, line 133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MysYetv243IRsps5wOA:-MysYetv243IRsps5wOB:bbmvl80) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader.go#L133)):*
> ```Go
> 
> 	// Escape, if not 0, is the character used to escape `"` characters and
> 	// itself.
> ```

maybe mention that if it's unset, it defaults to the same as QUOTE. (which will only be more important once we support the QUOTE option)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @rafiss)

___
*[pkg/util/encoding/csv/reader.go, line 133 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MysYetv243IRsps5wOA:-Mysim2YBJj5DBh5nZyx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader.go#L133)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe mention that if it's unset, it defaults to the same as QUOTE. (which will only be more important once we support the QUOTE option)
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
looks good from my end

**Review by ajstorm — APPROVED** [review]
LGTM too.  Thanks for clearing up my confusion about the unquoted characters.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-:-Myt95fuAinHHaDl2ugN:bp90kem)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @rafiss)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myqs39o9BbKodFoyPMj):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the new tests in TestUnimplementedSyntax in `parse_test.go` already does this
</blockquote></details>

Thanks.  I see them now.
___
*[pkg/util/encoding/csv/reader_test.go, line 396 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr1z0n4DJpZQJl6VAq:-Myt8xetDT11eCEANV0V:b6maidw) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L396)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

"x"",",","xxx"",x,"xxxx,"` shouldn't.
breaking it down:

`"x"",`: `"x""` - the  wrapping `"` indicates to use escapes, `x` escapes `"`, so it is `"`.
`",",`: the `","` is just `,`
`"xxx"",`: the x escapes x, then x escapes ", so it is `x"`
`x,`: no quotes, so we don't have to escape anything. so it is `x` (see below comment)
`"xxxx,"`, x escapes x twice, then a comma, so `xx,`
</blockquote></details>

Yeah, makes sense.  It was step 4 that I was missing.
___
*[pkg/util/encoding/csv/reader_test.go, line 402 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-Myr2o0b9wk35gwtFhvj:-Myt91MJ3ViM_PrxygPG:b-s24020) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/reader_test.go#L402)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

`"x""x`, yields `"`, then a delimiter
`,x` yields `,` then a delimiter
`"xxx""x` yields `"x", then a delimiter
`"xx"x": point of contention. begin quote, then x escapes x, so it becomes just `x`, then a delimiter
`"xxxx,"`: quote, two escapes x's, then a comma, so `xx,`

fwiw all these outputs are from PG
</blockquote></details>

All good.  Thanks.
___
*[pkg/util/encoding/csv/writer_test.go, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78303#-MyrN9TT77AOUFUxqD6W:-Myt8WwG-OqPoJT_zFjR:b-n5nvpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/167a9d5b4a99a0d7c501d57c14fcb447e98d5f84/pkg/util/encoding/csv/writer_test.go#L54)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

because things that are not in quotes are their accepted "raw value".
</blockquote></details>

Ahh, interesting.  That explains all of my confusion.  Thx.

**Comment by otan** [comment]
thanks 

bors r=rafiss,ajstorm

**Comment by otan** [comment]
blathers backport 22.1

**Comment by otan** [comment]
blathers backport 21.1 21.2

**Comment by otan** [comment]
blathers backport 21.2

**Pull request merged**
