### PR TITLE
ci: add scripts to build patched versions of Go runtime

### PR DESCRIPTION
**Pull request by rickystewart**
The script simply uses our existing cross toolchains and applies a patch
to the Go sources for the fine-grained CPU attribution work. We make a
custom `go` executable for all supported platforms except FreeBSD, for
which we have no cross-compilers, and M1/M2 Macs, for which we don't
have a code-signing pipeline set up yet.

Also update `build/README.MD` to capture the new process of building
dependencies.

Part of https://github.com/cockroachdb/cockroach/issues/82625.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Only the second commit needs to be reviewed here, the first is #84590.

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @livlobo, @rail, @rhu713, and @rickystewart)

___
*[`build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84867#-N7bThzB-KpZA1fgYSLx:-N7bThzB-KpZA1fgYSLy:b-yqyqam) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da42a3a791af673c32e02e3614f8646684dc4c9/build/teamcity/internal/release/build-and-publish-patched-go/impl.sh#L65)):*
> ```Shell
> rm golang.tar.gz
> cd /tmp/go$GOVERS/go
> git apply /bootstrap/diff.patch
> ```

Could we please provide some context on the origin of this patch. Only having seen it before, I recognize it as this PR [1], but it's far from obvious to anyone reading this.

[1] https://github.com/golang/go/pull/51347

**Review by irfansharif — APPROVED** [review]
> Reviewed 1 of 82 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @livlobo, @rail, @rhu713, and @srosenberg)

___
*[`build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84867#-N7bThzB-KpZA1fgYSLx:-N7bdKw8CtR-uBrMimdS:b-1xy8h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da42a3a791af673c32e02e3614f8646684dc4c9/build/teamcity/internal/release/build-and-publish-patched-go/impl.sh#L65)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Could we please provide some context on the origin of this patch. Only having seen it before, I recognize it as this PR [1], but it's far from obvious to anyone reading this.

[1] https://github.com/golang/go/pull/51347
</blockquote></details>

The commit message refers to #82625, which links out to an RFC (#82356) but perhaps you meant code comments here?

**Review by irfansharif — COMMENTED** [review]
This is very exciting! Thanks a ton for doing it, including the go1.18 bump.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84867#-:-N7bfUaz0RcNL_OltBgI:b-cv7scn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @livlobo, @rail, @rhu713, and @srosenberg)

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @livlobo, @rail, and @rhu713)

___
*[`build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84867#-N7bThzB-KpZA1fgYSLx:-N7bp0UsChmQVyirPSHK:b-mn7ztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da42a3a791af673c32e02e3614f8646684dc4c9/build/teamcity/internal/release/build-and-publish-patched-go/impl.sh#L65)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

The commit message refers to #82625, which links out to an RFC (#82356) but perhaps you meant code comments here?
</blockquote></details>

Yep, it would be nice to embed a comment with a link here describing the patch. This way the reader doesn't need to jump through the `git blame` hoop to understand what's being patched and why.

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Comment by rickystewart** [comment]
Can't merge yet, there are a couple problems:

* The `crosslinux` build is failing in CI on `stringer` for some reason. Haven't been able to reproduce locally.
* The `linux-arm64` Go binary produced by our script isn't actually ARM64 for some reason:
```
roach@baabef8c0616:/cockroach$ file /home/roach/.cache/bazel/_bazel_roach/cc377fc379544923cc7508dd261e4a48/external/go_sdk/bin/go
/home/roach/.cache/bazel/_bazel_roach/cc377fc379544923cc7508dd261e4a48/external/go_sdk/bin/go: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=jhRQbfhMWmwVHYgmGjrb/fPM7zbq08gwDRsSisq1u/Zu0wog_HeK1QIxwbFhVv/DO_1-OUdGdWg86Ng7olV, not stripped
```

Definitely something needs to be tweaked in the script to build the patched `go`s but I'm not sure what it is yet.

**Comment by rickystewart** [comment]
The latest version seems to be working (just had to do a light refactor of `pkg/base` to keep `stringer` working).

bors r=irfansharif,rail

**Comment by rickystewart** [comment]
bors r-

have to generate code again.

**Comment by rickystewart** [comment]
Hmm, still have a failing test. :(

```
/home/roach/.cache/bazel/_bazel_roach/cc377fc379544923cc7508dd261e4a48/sandbox/processwrapper-sandbox/1233/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture_test_/loopvarcapture_test.runfiles/go_sdk/src/runtime/cgo/cgo.go:34:8: could not import C (no metadata for C)
/home/roach/.cache/bazel/_bazel_roach/cc377fc379544923cc7508dd261e4a48/sandbox/processwrapper-sandbox/1233/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture_test_/loopvarcapture_test.runfiles/go_sdk/src/net/cgo_linux.go:12:8: could not import C (no metadata for C)
--- FAIL: TestAnalyzer (0.39s)
    analysistest.go:298: error analyzing loopvarcapture@p: analysis skipped due to errors in package
```

**Comment by irfansharif** [comment]
I don't entirely understand what's happening and what I'm doing is likely unsound, but this patch fixed the test:

```patch
diff --git i/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture.go w/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture.go
index 402c8c3fcb..cf919d0bb2 100644
--- i/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture.go
+++ w/pkg/testutils/lint/passes/loopvarcapture/loopvarcapture.go
@@ -51,10 +51,11 @@ var (
 	// Analyzer implements this linter, looking for loop variables
 	// captured by reference in closures called in Go routines
 	Analyzer = &analysis.Analyzer{
-		Name:     name,
-		Doc:      doc,
-		Requires: []*analysis.Analyzer{inspect.Analyzer},
-		Run:      run,
+		Name:             name,
+		Doc:              doc,
+		Requires:         []*analysis.Analyzer{inspect.Analyzer},
+		Run:              run,
+		RunDespiteErrors: true,
 	}
 
 	// GoRoutineFunctions is a collection of functions that are known to
```

Reproduced using:
```sh
$ ./dev builder
$ ./dev test pkg/testutils/lint/passes/loopvarcapture
```

From what I understand, it's something to do with https://github.com/golang/go/issues/36547, some funkiness in packages.Load expecting metadata for the pseudo C package. By specifying `RunDespiteErrors: true`, we're defeating this [analysis/internal/checker](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.12:go/analysis/internal/checker/checker.go;l=728-729) check.

**Comment by rickystewart** [comment]
I updated the test in question to use a version of the analyzer with `RunDespiteErrors = true` instead of updating the actual analyzer in-place. If this passes CI I'll `bors` today.

**Comment by rickystewart** [comment]
bors r=irfansharif,rail

**Comment by rickystewart** [comment]
image


bors r=irfansharif,rail

**Pull request merged**
