### PR TITLE
ui: move jobs pages to cluster-ui

### PR DESCRIPTION
**Pull request by ericharmeling**
This PR moves the Jobs page and the Jobs Details page to the `cluster-ui` package.

Related to https://github.com/cockroachdb/cockroach/issues/71324.

Release note: None

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
Can you add a loom/video showing that is working normally on db console (you can show running locally)

> Reviewed 25 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-:-N4hLASUCGEeu55STUka:bxlubik)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @maryliag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hKy_H4HzSVJXYHhF6):*
We use the issue number from github, not jira here, so it gets properly connected, so you can add:

Related to #71324
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hMgBR3U1H-lXYHowN:-N4hMgBR3U1H-lXYHowO:b-wf99gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L23)):*
> ```XML
> import { SummaryCard } from "src/summaryCard";
> import { TimestampToMoment } from "src/util";
> import { DATE_FORMAT } from "src/util/format";
> ```

can you confirm the timestamp used here? We're trying to use 24h UTC for all pages, so it will be good to use `DATE_FORMAT_24_UTC`, but make sure it's indeed in UTC
same thing for all usages of this format on this PR
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hLvMC3ufJjoyZ-CX-:-N4hLvMC3ufJjoyZ-CX0:bbfem4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L30)):*
> ```XML
> 
> import { commonStyles } from "src/common";
> import summaryCardstyles from "src/summaryCard/summaryCard.module.scss";
> ```

nit: summaryCardStyles
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hQ5yJ2SK1YQPmkrcK:-N4hQ5yJ2SK1YQPmkrcL:b-hn0895) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss#L59)):*
> ```SCSS
>   &__duration {
>     font-family: SourceSansPro-Regular;
>     font-size: 12px;
> ```

for fonts use the typography constants:
font-family: $font-family--base
font-size: $font-size--small

(for all cases below too)
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/util/duration.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hObaEDd-5AcReoNP-:-N4hObaEDd-5AcReoNP0:b-5sf1b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/util/duration.tsx#L19)):*
> ```XML
> type Job = cockroach.server.serverpb.IJobResponse;
> 
> export const formatDuration = (d: moment.Duration) =>
> ```

I can see you copied this function to here, was it deleted from the original location?
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/util/progressBar.tsx` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hP4wu3BCl9LzLof_A:-N4hP4wu3BCl9LzLof_B:b606dsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/util/progressBar.tsx#L52)):*
> ```XML
>           strokeWidth={this.props.lineWidth}
>           trailWidth={this.props.lineWidth}
>           strokeColor="#0055ff"
> ```

can we keep using the value from design-token here?
___
*[`pkg/ui/workspaces/cluster-ui/src/test-utils/tooltip.ts` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hR7SL10Dq0f7ad8tb:-N4hR7SL10Dq0f7ad8tc:b-1e9dsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/test-utils/tooltip.ts#L13)):*
> ```XML
> import { expect } from "chai";
> 
> export const expectPopperTooltipActivated = () =>
> ```

seems like this function is not being used anywhere, so the file itself can be deleted
___
*[`pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hNFht2QkJPonWDjvV:-N4hNFht2QkJPonWDjvW:b5e8ul4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1634866e44a08d195491cefb4ff16ad9696c6e21/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx#L289)):*
> ```XML
>               href={jobTable}
>               target="_blank"
>               onClick={this.redirectToLearnMore}
> ```

doesn't seem like the redirectToLearnMore is being used anywhere on this file anymore, so you can delete the function itself

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82909)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hKy_H4HzSVJXYHhF6):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We use the issue number from github, not jira here, so it gets properly connected, so you can add:

Related to #71324



</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hMgBR3U1H-lXYHowN:-N55jLDj6gXK1pQEn-iD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L23)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you confirm the timestamp used here? We're trying to use 24h UTC for all pages, so it will be good to use `DATE_FORMAT_24_UTC`, but make sure it's indeed in UTC
same thing for all usages of this format on this PR
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hLvMC3ufJjoyZ-CX-:-N55jWr0C88jq84ZLGfK:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L30)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: summaryCardStyles
</blockquote></details>

Fixed.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hQ5yJ2SK1YQPmkrcK:-N55m6H28tmCsTnwUaWW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss#L59)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

for fonts use the typography constants:
font-family: $font-family--base
font-size: $font-size--small

(for all cases below too)
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/util/duration.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hObaEDd-5AcReoNP-:-N55oTXM5hB97X7MmiCG:bc9y830) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/util/duration.tsx#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I can see you copied this function to here, was it deleted from the original location?
</blockquote></details>

Yes. It was [originally defined in and exported from `index.tsx` (which I've renamed to `jobsPage.tsx`)](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/jobs/index.tsx#L96), but never called in that file. I think it makes more sense to have it defined in `duration.tsx`, where it is actually used.
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/util/progressBar.tsx` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hP4wu3BCl9LzLof_A:-N55k0j91sQTfmNj6yiF:b-yyykqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/util/progressBar.tsx#L52)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can we keep using the value from design-token here?
</blockquote></details>

I was having trouble getting this component to build with the design-token import, but after rebasing... it looks like it works now! :man_shrugging: 
___
*[`pkg/ui/workspaces/cluster-ui/src/test-utils/tooltip.ts` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hR7SL10Dq0f7ad8tb:-N55mAB21LMLP8DgAW17:b-bazrpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/test-utils/tooltip.ts#L13)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

seems like this function is not being used anywhere, so the file itself can be deleted
</blockquote></details>

Done.

FWIW, this function/file was introduced in https://github.com/cockroachdb/cockroach/pull/72291 in order to [test a tooltip pop-up message for retrying jobs](https://github.com/cockroachdb/cockroach/pull/72291/files#diff-320efe14688f047c82a1d563abc72295efdab33dd0883ae1a6845c6192433eaaR90). I was having trouble getting that test to pass in my cluster-ui build of the jobs page with the `expectPopperTooltipActivated` call, and I honestly wasn't sure what calling `expectPopperTooltipActivated` before `userEvent.hover` was even doing for the test, so I simplified the test by removing `expectPopperTooltipActivated` from the test altogether (https://github.com/cockroachdb/cockroach/pull/82909/files#diff-e270da42dd3934f5fca2b6f42d02e9bbd3404471f75e5385f39cdffd9999d9dcR115), and it seems to be passing just fine now and testing on the same condition.
___
*[`pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-N4hNFht2QkJPonWDjvV:-N55jg5f9lejXW4t39SH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1634866e44a08d195491cefb4ff16ad9696c6e21/pkg/ui/workspaces/db-console/src/views/jobs/jobTable.tsx#L289)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

doesn't seem like the redirectToLearnMore is being used anywhere on this file anymore, so you can delete the function itself
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
Awesome!! :lgtm: 

> Reviewed 2 of 31 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82909#-:-N567cLV4XK7A_o8Uvjh:b-dllya6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/cockroach/blob/e5e72d0c918d95b336b9c13ad045a1c4d113ae86/pkg/ui/workspaces/cluster-ui/src/jobs/util/progressBar.tsx#L52

>>can we keep using the value from design-token here?

> I was having trouble getting this component to build with the design-token import, but after rebasing... it looks like it works now! 🤷‍♂️

I was wrong about the design-tokens import causing a build failure. It's causing a test failure. It looks like there is a syntax compatibility with the `design-tokens`

```
Summary of all failing tests
FAIL src/jobs/jobsPage/jobsPage.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /private/var/tmp/_bazel_ericharmeling/9a048edd47028dfa357cd8c58b62045b/sandbox/darwin-sandbox/7373/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/ui/workspaces/cluster-ui/jest.sh.runfiles/com_github_cockroachdb_cockroach/pkg/ui/workspaces/cluster-ui/node_modules/@cockroachlabs/design-tokens/dist/web/tokens.js:6
    export const ColorBackgroundBase = "#ffffff";
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       9 | // licenses/APL.txt.
      10 | import { cockroach } from "@cockroachlabs/crdb-protobuf-client";
    > 11 | import { Line } from "rc-progress";
         |                         ^
      12 | import React from "react";
      13 | import { Badge } from "src/badge";
      14 |

      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/jobs/util/progressBar.tsx:11:25)

FAIL src/jobs/jobsPage/jobTable.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /private/var/tmp/_bazel_ericharmeling/9a048edd47028dfa357cd8c58b62045b/sandbox/darwin-sandbox/7373/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/ui/workspaces/cluster-ui/jest.sh.runfiles/com_github_cockroachdb_cockroach/pkg/ui/workspaces/cluster-ui/node_modules/@cockroachlabs/design-tokens/dist/web/tokens.js:6
    export const ColorBackgroundBase = "#ffffff";
    ^^^^^^

    SyntaxError: Unexpected token 'export'

       9 | // licenses/APL.txt.
      10 | import { cockroach } from "@cockroachlabs/crdb-protobuf-client";
    > 11 | import { Line } from "rc-progress";
         |                         ^
      12 | import React from "react";
      13 | import { Badge } from "src/badge";
      14 |

      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/jobs/util/progressBar.tsx:11:25)


Test Suites: 2 failed, 31 passed, 33 total
Tests:       146 passed, 146 total
Snapshots:   0 total
Time:        268.749 s
Ran all test suites.
```

I'm going to just hardcode the color for now, since this is the only `.tsx` file in `cluster-ui` that uses `design-tokens`.

**Pull request merged**
