### PR TITLE
util/log: fix double close of a channel in some cases

### LINKED ISSUE #84422: util/log: close of closed channel in bufferedSinkCloser
**Describe the problem**

In [failure of `TestTenantLogic/3node-tenant/create_as`](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5747055?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&logFilter=debug#%2Ftest%2FlogTestTenantLogic1903228515) on a branch 1 commit head of 8a910b594199c8c4e290827564531104dc68df1f we see ([here](https://teamcityartifacts.crdb.io/presignedTokenAuth/dcff43a3-7d81-4cbe-8e9d-38af3f55f41e/repository/download/Cockroach_UnitTests/5747055:id/test/failures.txt))

```
ERROR: a panic has occurred!
Details cannot be printed yet because we are still unwinding.
Hopefully the test harness prints the panic below, otherwise check the test logs.

test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestTenantLogic4273976346
    panic.go:1038: close of closed channel
        goroutine 4387100 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/util/leaktest.AfterTest.func1()
        	/go/src/github.com/cockroachdb/cockroach/pkg/util/leaktest/leaktest.go:110 +0x166
        panic({0x496bf00, 0x6708ac0})
        	/usr/local/go/src/runtime/panic.go:1038 +0x215
        github.com/cockroachdb/cockroach/pkg/util/log.(*bufferedSinkCloser).Close(0xc01830f860, 0xc00fe6a030)
        	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/buffered_sink_closer.go:105 +0x5e
        github.com/cockroachdb/cockroach/pkg/util/log.ApplyConfig.func2()
        	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/flags.go:112 +0xf3
        github.com/cockroachdb/cockroach/pkg/util/log.(*TestLogScope).Close(0xc008aae300, {0x68a1e08, 0xc0046b2340})
        	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/test_log_scope.go:413 +0x12d
        github.com/cockroachdb/cockroach/pkg/sql/logictest.RunLogicTestWithDefaultConfig(0xc0046b2340, {0x55f100, 0xa8, 0x3e}, {0x509c883, 0x55f133}, {0x50d9c18, 0x6aad77a}, 0x1, {0xc004b503a0, ...})
        	/go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/logic.go:4532 +0x7a2
        github.com/cockroachdb/cockroach/pkg/ccl/logictestccl.TestTenantLogic(0x10af9c0)
        	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/logictestccl/logic_test.go:53 +0x218
        testing.tRunner(0xc0046b2340, 0x537b1e0)
        	/usr/local/go/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1306 +0x35a
```
 

Jira issue: CRDB-17648

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, it was possible for logic tests to panic because a channel
would be closed twice. This would occur since the cleanup function of
`TestLogScope` would be called twice which happens when the test is
already failed when the scope is created (in a `defer` in
`newLogScope`). This commit fixes that problem by making sure that we
close the scope in its constructor only if the initialization of the log
scope fails (which was probably the original intention anyway).

Fixes: #84422.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This was only applicable to `TestTenantLogic` which invokes `logictest.RunLogicTestWithDefaultConfig` twice on a different set of files, and if the first invocation fails the test, the second invocation would result in this "double close" panic. This means that one way for fixing that particular crash would be to break up two invocation into two top-level tests, still I think the proposed fix is more bullet-proof.

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for the fix

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7QmoZ4CmicAHGXlErq:b-a28mft)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by andreimatei — COMMENTED** [review]
> This would occur since the cleanup function of
> TestLogScope would be called twice which happens when the test is
> already failed when the scope is created (in a defer in
> newLogScope).

Are there other consequences of `log.Scope()` returning an already-closed scope in your scenario? It looks to me like the `defer` you mention was only intended to run if `newLogScope()` called `t.Fatal()` - in which case the caller will not get to run.
So instead of the `Close()` fix, or perhaps in addition to it, should `newLogScope` prohibit being called in a failed test by calling `t.Fatal()` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7Qz2XE4pKibissGxvH:b-l21qff)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by andreimatei — COMMENTED** [review]
Or, rather, I now think that we should permit the creation of a `log.Scope` in a failed test (i.e. after `t.Error()`), if that's what `TestTenantLogic` wants (I don't understand how that tests organizes its subtests). So I'm thinking that that blunt `defer` that closes the new scope for no good reason is a bad idea.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7R1qIa1JsNIIJiZVdf:balylfa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by yuzefovich — COMMENTED** [review]
> Are there other consequences of `log.Scope()` returning an already-closed scope in your scenario?

I'm not sure.

> I'm thinking that that blunt `defer` that closes the new scope for no good reason is a bad idea.

This was my original idea for the fix too. I don't have strong opinions here, so I made the corresponding change.

----

BTW, here is a "regression test" if anyone wants to play around with it:
```
func TestLogScopeOnFailedTest(t *testing.T) {
	// Simulate running a test that fails.
	t.Run("failing subtest", func(t *testing.T) {
		defer Scope(t).Close(t)
		t.Fatal("fail")
	})
	// Simulate running another test in the same higher-level test.
	require.NotPanics(t, func() {
		defer Scope(t).Close(t)
		t.Log("success after having failed")
	})
}
```
I'm not sure whether we can check this in because this test is always considered "failed", and I don't see a way to mark it as "fail expected", is there?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7R6Z5x6yv4T9h9YVUf:b-lxq6tc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @dhartunian)

**Review by yuzefovich — COMMENTED** [review]
>> I'm thinking that that blunt defer that closes the new scope for no good reason is a bad idea.
 
> This was original idea for the fix too. I don't have strong opinions here, so I made the corresponding change.

I guess in the future this could still lead to "close of closed channel" panic if the error does occur in `newLogScope` after `defer` in `ApplyConfig` _and_ `ApplyConfig` returns non-nil cleanup function and non-nil `err` (it currently doesn't though).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7R9mwN-3UkUAz7AVMR:bcc94fl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @dhartunian)

**Review by andreimatei — COMMENTED** [review]
> I'm not sure whether we can check this in because this test is always considered "failed", and I don't see a way to mark it as "fail expected", is there?

Have you tried creating a `*testing.T` by hand?
Alternatively, `log.Scope` is already programmed against an interface. You can create our own T impl.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7RLpIWA7AVWCkfLqgA:b-55mo2v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @yuzefovich)

___
*[`pkg/util/log/test_log_scope.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-N7RMS3wCPkddVpfDoR8:-N7RMS3wCPkddVpfDoR9:bhz12j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/faf90db7e02b6eb62b77e5a43da199f3d52904c6/pkg/util/log/test_log_scope.go#L148)):*
> ```Go
> 		// We use the scope's Close() method as general-purpose finalizer,
> 		// to avoid writing a complex defer function here.
> 		if t.Failed() && !alreadyFailed {
> ```

we want this `sc.Close()` call if `ApplyConfig` or `TempDir` fail below, regardless of `alreadyFail`.
Let's refactor everything that follows in a function that returns an error, and not use `t.Failed()` here.

**Review by yuzefovich — COMMENTED** [review]
> Have you tried creating a `*testing.T` by hand?

Interesting idea, I tried `&testing.T{}`, but that has some fields uninitialized. Is there a way to do that?

> Alternatively, `log.Scope` is already programmed against an interface. You can create our own T impl.

I tried going down this route a bit too but didn't succeed.

----

I don't think it's mandatory to have a regression test here, so I feel like spending more time on this is not really worth it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7RTRITDZFrJjiQDdlb:bf1j2vk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @dhartunian)

___
*[`pkg/util/log/test_log_scope.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-N7RMS3wCPkddVpfDoR8:-N7RTMytAWllIfmoUICR:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/faf90db7e02b6eb62b77e5a43da199f3d52904c6/pkg/util/log/test_log_scope.go#L148)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we want this `sc.Close()` call if `ApplyConfig` or `TempDir` fail below, regardless of `alreadyFail`.
Let's refactor everything that follows in a function that returns an error, and not use `t.Failed()` here.
</blockquote></details>

Good point, fixed.

**Review by andreimatei — COMMENTED** [review]
:lgtm: but I think the commit msg rotted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84688#-:-N7Rdm_H9r2CFEJ0VL5r:b-l0yvo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @dhartunian)

**Comment by yuzefovich** [comment]
Adjusted the commit message.

TFTRs!

bors r+

**Pull request merged**
