### PR TITLE
ui: Pull in ccl protos for encryption view

### LINKED ISSUE #81367: ui: CCL protos not pulled in by webpack
Since the move to yarn workspaces in #68412, protobufs that are only present in the CCL-licensed side are not present in the final `bundle.js` produced by webpack. As a result, the "Encryption status" view on the debug page is broken, with the error `Error decoding protobuf: TypeError: undefined is not an object (evaluating 'F.ccl.storageccl')` being displayed in the UI. As far as I know, only storage / encryption-at-rest stuff is affected by this bug.

### PR DESCRIPTION
**Pull request by itsbilal**
With the move to yarn workspaces, we unintentionally stopped
importing CCL-licensed protobufs into the javascirpt bundle. This
led to a runtime JavaScript error when going to the store
details page if encryption-at-rest was enabled, preventing
observability into encryption-at-rest key statuses.

Fixes #81367.

Release note (bug fix, ui change): Fixes issue where the 'Encryption
status' field on the store details debug page on the DB console would
display an error instead of displaying encryption details when
encryption-at-rest is enabled.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Thanks @itsbilal! :lgtm: (non-binding).

And to confirm, this will backport to 22.1.x and 21.2.x. Mind adding the labels for our friend Blathers?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81373#-:-N2Hq4RPAqldRPZQNZEQ:b3lm9dx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nathanstilwell and @Santamaura)

**Comment by itsbilal** [comment]
TFTR @nicktrav ! I made this PR more minimal, turns out turning the ccl protos folder into a package with a package.json is not necessary to pull it into the bundle. We just need the right webpack indirection. 

Added backport tags as well, thanks for that reminder!

**Review by nicktrav — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81373)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nathanstilwell and @Santamaura)

**Comment by itsbilal** [comment]
Huh, the build fails on CI with this error, but works for me with bazel on my laptop:

> Module not found: Error: Can't resolve 'ccl/src/js/protos' in '/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6703/execroot/com_github_cockroachdb_cockroach/pkg/ui/workspaces/db-console/ccl/src/views/reports/containers/stores'

**Pull request merged**
