### PR TITLE
release-23.2: mint 23.2 version

### PR DESCRIPTION
**Pull request by RaduBerinde**
Set the final 23.2 cluster version.

Release justification: necessary versioning step for every release.
Epic: none
Release note: None

### CODE REVIEW

**Comment by celiala** [comment]
I'll circle back to reviewing this after this PR lands (as this will need a rebase):

https://github.com/cockroachdb/cockroach/pull/112452

**Comment by RaduBerinde** [comment]
Rebased.

Not sure when this is supposed to merge.. I assume it is right before we release `.0`? I could also imagine doing it before `rc1` but we wouldn't be able to add any gates if we find some issue.

**Comment by celiala** [comment]
> Not sure when this is supposed to merge.. 

Let's tentatively plan to merge this right before selecting the final RC candidate.

The guidance for when to merge this is:
- This should not be merged until we are _completely sure_ that we no longer need to backport additional 23.2 version gates.
- One way to think of this as the FINAL-ish GA-blocker backport, where this _must_ be included in the final RC (at the latest).

**Review by celiala — APPROVED** [review]
LGTM!

Since we're on track to prep an rc, we can merge this one now!

Thanks for all the rebases to keep this PR at-the-ready! ❤️

**Pull request merged**
