### PR TITLE
acceptance:Plumb contexts for acceptance

### LINKED ISSUE #10510: acceptance: plumb contexts and improve stopper discipline
Our acceptance tests are currently a disaster with respect to contexts, cancellation, and timeouts. In many cases, we do odd things like create RPC clients in a loop, each time creating and destroying a stopper.

We should clean this up, primarily by plumbing contexts through everything so that we can have sane timeouts for things, and secondarily by associating a stopper with each test (or with the entire suite, in place of the `stopper chan struct{}` that we currently have).

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10510

cc @tamird.

Please help me review if I have done it right. Thanks a lot.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10865)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 5 of 32 files at r1.
Review status: 5 of 32 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/admin_test.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29Oq7R57RBW5FdnxM:-KX29Oq7R57RBW5FdnxN:b34sq68) ([raw file](https://github.com/cockroachdb/cockroach/blob/659691be63feaa72a5694718bb77d4090bb1576f/pkg/acceptance/admin_test.go#L59)):*
> ```Go
> 	// Leave only the first node alive.
> 	for i := 1; i < c.NumNodes(); i++ {
> 		if err := c.Kill(i); err != nil {
> ```

Kill() uses `context.Background()` internally - shouldn't it have a context passed to it? the same goes for other methods in docker.go.

---

*[pkg/acceptance/cluster/docker.go, line 483 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX2QokkzUFj2IXGQAHG:-KX2QokkzUFj2IXGQAHH:bbbxcev) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L483)):*
> ```Go
> ) (io.ReadCloser, error) {
> 	// Image pulling is potentially slow. Make sure the timeout is sufficient.
> 	timeout := cli.timeout
> ```

this is another worrying change in behaviour - the old behaviour had a short timeout and would retry when the timeout expired. the new behaviour plumbs down the entire test's timeout so will fail if any of the docker operations time out.

---

*[pkg/acceptance/terrafarm/farmer.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29432HiRMQANO_pZb:-KX29432HiRMQANO_pZc:b-uj8zjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/terrafarm/farmer.go#L215)):*
> ```Go
> func (f *Farmer) NewClient(t *testing.T, i int) (*client.DB, *stop.Stopper) {
> 	stopper := stop.NewStopper()
> 	rpcContext := rpc.NewContext(log.AmbientContext{}, &base.Config{
> ```

this is a worrying change in behaviour; each call to NewClient will now start an RPC context which will never be closed (until the end of the test). Perhaps the `Farmer` should hold an RPC context rather than or in addition to a stopper?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865)*

**Comment by a6802739** [comment]
Review status: 4 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/admin_test.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29Oq7R57RBW5FdnxM:-KX5bvQ_Bo2NkH8klslk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659691be63feaa72a5694718bb77d4090bb1576f/pkg/acceptance/admin_test.go#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Kill() uses `context.Background()` internally - shouldn't it have a context passed to it? the same goes for other methods in docker.go.
</details>
Done.

---

*[pkg/acceptance/cluster/docker.go, line 483 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX2QokkzUFj2IXGQAHG:-KX5c-7-mlXtn9CIXinI:b1cjkgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L483)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is another worrying change in behaviour - the old behaviour had a short timeout and would retry when the timeout expired. the new behaviour plumbs down the entire test's timeout so will fail if any of the docker operations time out.
</details>
So, Now I change it back.

---

*[pkg/acceptance/terrafarm/farmer.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29432HiRMQANO_pZb:-KX5c3ibwhMUWq_HOfX9:bvif80d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/terrafarm/farmer.go#L215)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is a worrying change in behaviour; each call to NewClient will now start an RPC context which will never be closed (until the end of the test). Perhaps the `Farmer` should hold an RPC context rather than or in addition to a stopper?
</details>
hmm, sorry, I could quit understand what you say here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865)*

**Comment by a6802739** [comment]
Review status: 4 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/acceptance/terrafarm/farmer.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29432HiRMQANO_pZb:-KX5o0dOGXmbdTjRyWxM:bm49gjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/terrafarm/farmer.go#L215)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> hmm, sorry, I could quit understand what you say here.
</details>
hmm, sorry, I couldn't quite understand what you say here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865)*

**Comment by tamird** [comment]
Reviewed 2 of 32 files at r1, 2 of 3 files at r2.
Review status: 8 of 32 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/acceptance/admin_test.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29Oq7R57RBW5FdnxM:-KX6Zp_eFyRUvWwGcXOk:b-j231rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/659691be63feaa72a5694718bb77d4090bb1576f/pkg/acceptance/admin_test.go#L59)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> Done.
</details>
Don't you need to pass a context here?

---

*[pkg/acceptance/cluster/docker.go, line 407 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX6_5xWqmF-_fEOJtsR:-KX6_5xWqmF-_fEOJtsS:b-h79y0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L407)):*
> ```Go
> 		return err
> 	}
> 	return fmt.Errorf("%s: exceeded %d tries with a %s timeout", name, attempts, timeout)
> ```

change this back too?

---

*[pkg/acceptance/cluster/localcluster.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX6_yoqxqyHeQTvF3YM:-KX6_yorr5DMAQVgACPb:b7m3i6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b334a827951268431d3dcbb6b4af3ae56443178/pkg/acceptance/cluster/localcluster.go#L139)):*
> ```Go
> // persistent volumes used for certs and node data and N cockroach nodes.
> type LocalCluster struct {
> 	timeoutCtx           context.Context
> ```

can you avoid putting this context on the structure? In general, I think it's a pattern we'd like to avoid.

---

*[pkg/acceptance/terrafarm/farmer.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29432HiRMQANO_pZb:-KX6Z_9sm1w9EmB5RDcb:bu3yob5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/terrafarm/farmer.go#L215)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> hmm, sorry, I couldn't quite understand what you say here.
</details>
Whenever an RPC context is created, there is a run loop that heartbeats on any RPC connection opened using that RPC context. For this reason, we want to have only one RPC context (so that connections can be shared and so that there aren't random run loops running in the process).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865)*

**Comment by a6802739** [comment]
@tamird, thanks for you review.

---

Review status: 0 of 32 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/admin_test.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29Oq7R57RBW5FdnxM:-KXBMBs1S8hrIzDzk5So:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659691be63feaa72a5694718bb77d4090bb1576f/pkg/acceptance/admin_test.go#L59)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Don't you need to pass a context here?
</details>
Done.

---

*[pkg/acceptance/cluster/docker.go, line 407 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX6_5xWqmF-_fEOJtsR:-KXBMIqKVChFaNPSKR8e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L407)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> change this back too?
</details>
Done.

---

*[pkg/acceptance/cluster/localcluster.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX6_yoqxqyHeQTvF3YM:-KXBMHqjCgVor-FXril4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b334a827951268431d3dcbb6b4af3ae56443178/pkg/acceptance/cluster/localcluster.go#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you avoid putting this context on the structure? In general, I think it's a pattern we'd like to avoid.
</details>
Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KX29432HiRMQANO_pZb:-KXBMLA-4cRJGtS6UD-M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/terrafarm/farmer.go#L215)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Whenever an RPC context is created, there is a run loop that heartbeats on any RPC connection opened using that RPC context. For this reason, we want to have only one RPC context (so that connections can be shared and so that there aren't random run loops running in the process).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXBMN5gfTqQxzz_d52M:b-6cpjf3)*

**Comment by tamird** [comment]
This is looking good.

How come all the tests now have a global timeout? I don't believe that was the previous behaviour.

---

Reviewed 11 of 32 files at r1, 20 of 21 files at r3.
Review status: 31 of 32 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/continuous_load_test.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBwLevyefahOEAnm6K:-KXBwLevyefahOEAnm6L:bwuyqae) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/continuous_load_test.go#L129)):*
> ```Go
> 			t.Fatalf("test.timeout must be greater than create/destroy interval %s", setupTeardownDuration)
> 		} else {
> 			var cancel context.CancelFunc
> ```

what happened here? I believe we still need all this logic, don't we?

---

*[pkg/acceptance/dynamic_client.go, line 38 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBweanwHDcGOPHMFGE:-KXBweanwHDcGOPHMFGF:b-9s3ncw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba42923bd0909b166c2cf7a4ed0469c8ec6350e8/pkg/acceptance/dynamic_client.go#L38)):*
> ```Go
> 	cluster cluster.Cluster
> 	stopper *stop.Stopper
> 	ctx     context.Context
> ```

can you avoid this?

---

*[pkg/acceptance/cluster/docker.go, line 482 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBnq_DpCg8mHs8HoXu:-KXBnq_DpCg8mHs8HoXv:b-nwtyks) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L482)):*
> ```Go
> 	ctx context.Context, ref string, options types.ImagePullOptions,
> ) (io.ReadCloser, error) {
> 	// Image pulling is potentially slow. Make sure the timeout is sufficient.
> ```

restore this comment

---

*[pkg/acceptance/cluster/docker.go, line 491 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBntKYz_OOPUaCbvM5:-KXBntKYz_OOPUaCbvM6:b-dgr1ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L491)):*
> ```Go
> 		func(timeoutCtx context.Context) error {
> 			var err error
> 			ret, err = cli.resilientDockerClient.ImagePull(timeoutCtx, ref, options)
> ```

this is using the wrong context now

---

*[pkg/acceptance/terrafarm/farmer.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBw9KgKYXRY3UpjSWV:-KXBw9KgKYXRY3UpjSWW:bcbxlob) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba42923bd0909b166c2cf7a4ed0469c8ec6350e8/pkg/acceptance/terrafarm/farmer.go#L67)):*
> ```Go
> 	nodes       []string
> 	RPCContext  *rpc.Context
> 	Stopper     *stop.Stopper
> ```

does the stopper still need to be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXBwWhWObNR3EjLS_ZX:brp2ysi)*

**Comment by a6802739** [comment]
@tamird,  Thanks for your review.

do you mean we should use different timeout to set `ctx` for each single test case, right? It seems we don't have accurate `timeout` parameter for each test case before.

---

Review status: 25 of 32 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/continuous_load_test.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBwLevyefahOEAnm6K:-KXFClx3TGf9ga2IwJ8k:b-3u8tpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/continuous_load_test.go#L129)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what happened here? I believe we still need all this logic, don't we?
</details>
I change it back now, But it seems it doesn't matter if we delete this logic? 

---

*[pkg/acceptance/dynamic_client.go, line 38 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBweanwHDcGOPHMFGE:-KXFD1rYqBU6PjvInONa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba42923bd0909b166c2cf7a4ed0469c8ec6350e8/pkg/acceptance/dynamic_client.go#L38)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you avoid this?
</details>
Done.

---

*[pkg/acceptance/dynamic_client.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXFD4pKvsFbKK8zfjhy:-KXFD4pKvsFbKK8zfjhz:b-7l07qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a942bf3c697e0e0fde66bd7896c8d84a3998d9/pkg/acceptance/dynamic_client.go#L64)):*
> ```Go
> 	defer dc.mu.Unlock()
> 	for i, client := range dc.mu.clients {
> 		log.Infof(context.Background(), "closing connection to %s", dc.cluster.Addr(context.Background(), i, base.DefaultPort))
> ```

I don't know if I done it right in this place?

---

*[pkg/acceptance/cluster/docker.go, line 482 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBnq_DpCg8mHs8HoXu:-KXFDFqv8lecEu2go4cS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L482)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> restore this comment
</details>
Done.

---

*[pkg/acceptance/cluster/docker.go, line 491 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBntKYz_OOPUaCbvM5:-KXFDGngmulFawfnRk9w:bc6fhe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/cluster/docker.go#L491)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this is using the wrong context now
</details>
my mistake. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXFBeqQPqdY2cEJRpwV:b-yeo1us)*

**Comment by tamird** [comment]
No, I just mean that those timeouts you added for each test are not needed, are they?

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/continuous_load_test.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBwLevyefahOEAnm6K:-KXFyy84t_OFStpBH1dW:b-3uiy2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/continuous_load_test.go#L129)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> I change it back now, But it seems it doesn't matter if we delete this logic? 
</details>
What do you mean, it doesn't matter? this logic is for cleaning up AWS/GCE resources when tests are run with a package-level timeout.

---

*[pkg/acceptance/continuous_load_test.go, line 115 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXG-Zlx3y9ArftHv-fF:-KXG-Zlx3y9ArftHv-fG:bzczchf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd99d9d9fef2de3f89c3e3847f0011f3f7de6cd/pkg/acceptance/continuous_load_test.go#L115)):*
> ```Go
> func (cl continuousLoadTest) Run(ctx context.Context, t *testing.T) {
> 	f := farmer(t, cl.Prefix+cl.shortTestTimeout(), stopper)
> 	timeoutCtx := context.Background()
> ```

this shouldn't be necessary - the context below should have a timeout derived from the passed-in `ctx` (see my other comment about removing the new top-level timeouts).

---

*[pkg/acceptance/dynamic_client.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXFD4pKvsFbKK8zfjhy:-KXFzhAsQvZO2RbiBTnu:bze22w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd99d9d9fef2de3f89c3e3847f0011f3f7de6cd/pkg/acceptance/dynamic_client.go#L64)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> I don't know if I done it right in this place?
</details>
Isn't it possible to pass a context to Close?

---

*[pkg/acceptance/repair_test.go, line 36 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXG-06pVW98VBwDKXpm:-KXG-06pVW98VBwDKXpn:b6yujob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd99d9d9fef2de3f89c3e3847f0011f3f7de6cd/pkg/acceptance/repair_test.go#L36)):*
> ```Go
> func testRepairInner(ctx context.Context, t *testing.T, c cluster.Cluster, cfg cluster.TestConfig) {
> 	dc := newDynamicClient(c, stopper)
> 	stopper.AddCloser(dc)
> ```

if you change dc.Close to take a context, you'll need to make this:
```
stopper.AddCloser(stop.CloserFn(func() {
  dc.Close(ctx)
}))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXG-OIWD91-lB0FYSiD:bws3ag)*

**Comment by a6802739** [comment]
@tamird, yes you're right.we don't need the timeout parameter.

---

Review status: 16 of 32 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/continuous_load_test.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBwLevyefahOEAnm6K:-KXGMcdr_HJ5RNV3ThIS:b-4uaxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea18eebd2e77adbc71cea917b1171027f2dbdae/pkg/acceptance/continuous_load_test.go#L129)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What do you mean, it doesn't matter? this logic is for cleaning up AWS/GCE resources when tests are run with a package-level timeout.
</details>
ah, I mean if we have the original timeout parameter, it seems we don't need this.

But, you are right. I have change it now.

---

*[pkg/acceptance/continuous_load_test.go, line 115 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXG-Zlx3y9ArftHv-fF:-KXGMbnl2C8a0YRAZgAV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd99d9d9fef2de3f89c3e3847f0011f3f7de6cd/pkg/acceptance/continuous_load_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this shouldn't be necessary - the context below should have a timeout derived from the passed-in `ctx` (see my other comment about removing the new top-level timeouts).
</details>
Done.

---

*[pkg/acceptance/dynamic_client.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXFD4pKvsFbKK8zfjhy:-KXGMwlqDgcDbZm8-P8l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd99d9d9fef2de3f89c3e3847f0011f3f7de6cd/pkg/acceptance/dynamic_client.go#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Isn't it possible to pass a context to Close?
</details>
Done.

---

*[pkg/acceptance/terrafarm/farmer.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXBw9KgKYXRY3UpjSWV:-KXGN12PjVcKIfl_fdOl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba42923bd0909b166c2cf7a4ed0469c8ec6350e8/pkg/acceptance/terrafarm/farmer.go#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does the stopper still need to be here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXGAFu95naH_loCxPj3:bmaob2n)*

**Comment by tamird** [comment]
:lgtm:

@cuongdo can you give this a look?

---

Reviewed 16 of 16 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXGUh0FAqfoCl8d53JD:bpp1vpr)*

**Comment by cuongdo** [comment]
LGTM except for the comments I made

Generally, we shouldn't add `Context` parameters for methods that have no use for them. The methods I pointed out don't log, perform long-running operations, or use `Context`-scoped values.

---

Reviewed 13 of 21 files at r3, 2 of 7 files at r4, 16 of 16 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/cluster/cluster.go, line 38 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhAiuvKe3304oUETf:-KXGhAiuvKe3304oUETg:bi2xenm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L38)):*
> ```Go
> 	NewClient(context.Context, *testing.T, int) *client.DB
> 	// PGUrl returns a URL string for the given node postgres server.
> 	PGUrl(context.Context, int) string
> ```

Why does `PGUrl` need a context? I can't see needing to cancel such a short operation, and `PGUrl` doesn't need to log anything.

---

*[pkg/acceptance/cluster/cluster.go, line 40 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhU_bykgvW5Cp4hFh:-KXGhU_bykgvW5Cp4hFi:bm11kbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L40)):*
> ```Go
> 	PGUrl(context.Context, int) string
> 	// InternalIP returns the address used for inter-node communication.
> 	InternalIP(ctx context.Context, i int) net.IP
> ```

(same as above) Why does this need a context?

---

*[pkg/acceptance/cluster/cluster.go, line 58 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhiP-10edH6OFRMwJ:-KXGhiP-10edH6OFRMwK:bm11kbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L58)):*
> ```Go
> 	Restart(context.Context, int) error
> 	// URL returns the HTTP(s) endpoint.
> 	URL(context.Context, int) string
> ```

(same as above) Why does this need a context?

---

*[pkg/acceptance/cluster/cluster.go, line 60 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhkRzhqny7ITSOcTj:-KXGhkRzhqny7ITSOcTk:bm11kbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L60)):*
> ```Go
> 	URL(context.Context, int) string
> 	// Addr returns the host and port from the node in the format HOST:PORT.
> 	Addr(ctx context.Context, i int, port string) string
> ```

(same as above) Why does this need a context?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXGjbJP5BAiq6SM_72g:bl922p4)*

**Comment by a6802739** [comment]
@cuongdo, For example,  the function`PGUrl` in `cluster/localcluster.go`, it invoked `Container.Addr()` which will invoke `Container.Inspect()`.

**Comment by a6802739** [comment]
@cuongdo, could you please have a review on it again?

**Comment by tamird** [comment]
@a6802739 FYI most of the team is away for thanksgiving, so @cuongdo might not get to this until Monday.

**Comment by a6802739** [comment]
@tamird, oh, got it. Happy thanksgiving Day!

**Comment by cuongdo** [comment]
@a6802739 I still don't see why the methods I mentioned need `Context`s. You haven't made any changes to those methods (e.g. `PGUrl`), so the passed in `Context` doesn't seem to be used for anything. 

---

Reviewed 1 of 7 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-:-KXgMGCXoXinP2SMNlWj:b-2wdjmk)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/cluster/cluster.go, line 38 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhAiuvKe3304oUETf:-KXgemnXu836CUAEGXzY:b-jiegks) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L38)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Why does `PGUrl` need a context? I can't see needing to cancel such a short operation, and `PGUrl` doesn't need to log anything.
</blockquote></details>

(at least one of) the implementations calls `(*Container).Addr`, which calls `(*Container).Inspect`, which calls a method on the docker API client (`ContainerInspect`) which needs a context.

---

*[pkg/acceptance/cluster/cluster.go, line 40 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhU_bykgvW5Cp4hFh:-KXgezUEnsMsCHQo1cuL:bdvg919) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L40)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

(same as above) Why does this need a context?
</blockquote></details>

(at least one of) the implementations calls `(*Container).Inspect`, which calls a method on the docker API client (`ContainerInspect`) which needs a context.

---

*[pkg/acceptance/cluster/cluster.go, line 58 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhiP-10edH6OFRMwJ:-KXgfM7LWqxZY9ddpQBe:b-jiegks) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L58)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

(same as above) Why does this need a context?
</blockquote></details>

(at least one of) the implementations calls `(*Container).Addr`, which calls `(*Container).Inspect`, which calls a method on the docker API client (`ContainerInspect`) which needs a context.

---

*[pkg/acceptance/cluster/cluster.go, line 60 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865#-KXGhkRzhqny7ITSOcTj:-KXgfMkrQiN_CkaacHya:bdvg919) ([raw file](https://github.com/cockroachdb/cockroach/blob/7adb71af2257dd0ad1b66692c9a7067326c9e6c1/pkg/acceptance/cluster/cluster.go#L60)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

(same as above) Why does this need a context?
</blockquote></details>

(at least one of) the implementations calls `(*Container).Inspect`, which calls a method on the docker API client (`ContainerInspect`) which needs a context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10865)*

**Comment by a6802739** [comment]
@tamird, thank you for pointing these out. @cuongdo, what do you think now?

**Comment by cuongdo** [comment]
LGTM

**Comment by tamird** [comment]
@a6802739 could you rebase?

**Comment by a6802739** [comment]
@tamird, yes, I could do that.

**Comment by a6802739** [comment]
@tamird, could I merge this now?

**Comment by tamird** [comment]
Yep!

**Pull request merged**
