### PR TITLE
build: add optimizer tests to nightly testrace tests

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds nightly tests for running the testrace logic tests with
two different flags which create alternate query plans:

 `-optimizer-cost-perturbation=p`

    This flag randomly perturbs the cost of each expression in the
    optimizer by at most p. In other words, if the cost of an expression
    is c, the perturbed cost will be in the range [c - p * c, c + p * c).
    This flag allows us to test that alternate plans created by exploration
    rules are logically equivalent to the lowest cost plan.

 `-disable-opt-rule-probability=p`

    This flag randomly disables each transformation rule in the optimizer
    with probability p. This flag allows us to test that alternate plans
    created by disabling certain rules are logically equivalent to the
    plan that would be created with all rules enabled.

Fixes #31969

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
A couple of things I'm not sure about:
1. Will this make the nightly tests too long? This would add 2 extra runs of `bigtest`...
2. Should I make an exception for any files in the `testrace` run? I guess `subquery_correlated` should be skipped for the runs with `-disable-opt-rule-probability`. Any others? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31980#-:-LQ0CAGX0qeW5KQoXe4R:bk1nvcz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
I wouldn't run the bigtests nightly with these options, it's just too slow (which also makes it hard to verify the chosen parameters aren't flaky). We could run them with our logictests though.

**Comment by rytaft** [comment]
Ok, makes sense. I've already added tests for the logictests with `make testrace`. That's the new code in `teamcity-testlogicrace.sh`. Do you think I should add these same tests with `make test` also?

**Comment by RaduBerinde** [comment]
Oh, I see, doing them in testrace should be sufficient. That one also runs nightly right?

I would use `stress` to run it for a few hours to make sure it's not flaky.

**Review by rytaft — COMMENTED** [review]
Ok, I've removed the bigtest runs and excluded files that would cause flakiness. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31980#-:-LQ58PyM26XzfTs-FMeM:bbegupr)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31980#-:-LQ5D_yPAP9DXz7V_Cz0:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31980#-:-LQ5KyNP7CU1imOYb8PD:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
