### PR TITLE
Cleanup Gossip TODO.

### PR DESCRIPTION
**Pull request by spencerkimball**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4638)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[gossip/storage_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBNlIBze6IdrBvMnlhL:-KBNlIBze6IdrBvMnlhM:-1265847203) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b9fa21f73e06df9c0eead920ac337643b4ff08/gossip/storage_test.go#L115)):*
`s/errors.New(fmt.Sprintf(/fmt.Errorf(/g`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-:-KBNlTnCcrzoq8sKtT3Q:676834233)*

**Comment by tamird** [comment]
Can you please amend the commit message to include a description of the TODO being addressed? It is incredibly painful to encounter commits of this form (and I encountered plenty during e.g. the grpc porting work, so this is not a theoretical concern).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip.go, line 210 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBNxKkYQbA4DZstBpA3:-KBNxKkYQbA4DZstBpA4:1910074825) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7eea69eaa77436698c19f8def347913222e48a/gossip/gossip.go#L210)):*
has this been addressed?

---

*[gossip/storage_test.go, line 115 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBNlIBze6IdrBvMnlhL:-KBNx4zdSr2GnhD9k4Hy:2046150656) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b9fa21f73e06df9c0eead920ac337643b4ff08/gossip/storage_test.go#L115)):*
prefer `util.Errorf` since the `util.SucceedsWithin` failure won't report the correct source location.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-:-KBNwgIZqoEpfJnVJCEH:-1723255626)*

**Comment by spencerkimball** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/gossip.go, line 210 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBNxKkYQbA4DZstBpA3:-KBhkVnnANttnE0Uo7a6:1758359711) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e7eea69eaa77436698c19f8def347913222e48a/gossip/gossip.go#L210)):*
Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender_test.go, line 288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBhvGEwGaAnFeIsNZt5:-KBhvGEwGaAnFeIsNZt6:1139522604) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a7f81813ee6218161cbe5d81caa0c7f3eed473/kv/dist_sender_test.go#L288)):*
does this port number matter? if it doesn't, make it explicit by not using 26257. if it does, use `base.DefaultPort`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-:-KBhz6KD5skOnt6mulao:676834233)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender_test.go, line 288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBhvGEwGaAnFeIsNZt5:-KBi3g-oDto30_6cq6y_:-1393520460) ([raw file](https://github.com/cockroachdb/cockroach/blob/50a7f81813ee6218161cbe5d81caa0c7f3eed473/kv/dist_sender_test.go#L288)):*
It doesn't. I'll just make it "1".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638)*

**Comment by tamird** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/raft_transport_test.go, line 257 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638#-KBi9BeyW2QkM6iua0Er:-KBi9BeyW2QkM6iua0Es:67427279) ([raw file](https://github.com/cockroachdb/cockroach/blob/0866ceb022505621bb5a673a25de217b5cb0473c/storage/raft_transport_test.go#L257)):*
s/Inof/Info/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4638)*

**Pull request merged**
