### PR TITLE
exec: support more decimal, bytes, bool ops

### PR DESCRIPTION
**Pull request by jordanlewis**
Add support for non-infix comparisons and binary operators in
projection, selection and distinct ops.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
LGTM. With the change to distinct, are decimals now supported? Would be good to call out in the commit message.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-:-LQElXLmDXnfu2aigt-0:bvq2b6k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEcya9Ep24UK_EIeEd:-LQEcya9Ep24UK_EIeEe:b74jxvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/distinct_tmpl.go#L179)):*
> ```Go
> 			// Note that not inlining this unique var actually makes a non-trivial
> 			// performance difference.
> 			unique := false
> ```

Any reason this changed?
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEiZGA3Lgk3tfb_4Pq:-LQEiZGA3Lgk3tfb_4Pr:bt3ifmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L67)):*
> ```Go
> 	// Only one of CmpOp and BinOp will be set, depending on whether the overload
> 	// is a binary operator or a comparison operator.
> 	CmpOp tree.ComparisonOperator
> ```

These both implement the `tree.Operator` interface so you could have just one variable, but it might be easier to keep it this way.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEjlP3DX5Vamh6RJxd:-LQEjlP3DX5Vamh6RJxe:bhxrvb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L180)):*
> ```Go
> 
> // binOpTypeCustomizer is a type customizer that changes how the templater
> // produces binary operator output for a particular type.
> ```

`s/binary/comparison`?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32071)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEcya9Ep24UK_EIeEd:-LQF4R7fEvEbMXEqs1Kv:br9fkwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/distinct_tmpl.go#L179)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any reason this changed?
</blockquote></details>

Reverted, was an experiment.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEiZGA3Lgk3tfb_4Pq:-LQF3rlsAo2mfuCxYBGf:b6e5qot) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L67)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

These both implement the `tree.Operator` interface so you could have just one variable, but it might be easier to keep it this way.
</blockquote></details>

Oh I forgot about that. I do think it's easier to keep it this way though. Maybe we can change later.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEjlP3DX5Vamh6RJxd:-LQF41T51FTe4I6La43R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L180)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/binary/comparison`?
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32071)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEcya9Ep24UK_EIeEd:-LQFCUu9AKXq17SVSPzw:bmr22sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/distinct_tmpl.go#L179)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Reverted, was an experiment.
</blockquote></details>

Not sure it's been actually changed back in this revision.

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-:-LQFK7u_EyVDClK-lhiT:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/distinct_tmpl.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32071#-LQEcya9Ep24UK_EIeEd:-LQFK5y-BYq5X9JAeH40:bj4d6ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7b9bfa81b5527031c89fb9f46d8f0eb32234b56/pkg/sql/exec/distinct_tmpl.go#L179)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure it's been actually changed back in this revision.
</blockquote></details>

Actually fixed now.

**Pull request merged**
