### PR TITLE
kvserver,roachpb: introduce max io overload score

### PR DESCRIPTION
**Pull request by kvoli**
The allocator uses the IO threshold score to determine replicas to
filter for rebalancing and lease transfers. Previously, this score would
be the last instantaneous value gossiped. As part of https://github.com/cockroachdb/cockroach/issues/118866, leases
will be shed upon encountering overload, in addition to the existing
behavior of blocking lease transfers. To avoid leases shedding quickly
from one node to another, consider the maximum IO threshold score
instead.

Note that the use of the maximum IO overload score is gated behind a
cluster version gate. Without the version gate it would be possible for
an upgraded node to continually shed all of its leases based off of the
maximum IO overload score, whilst prior version nodes transfer the lease
back based off the instantaneous.

---

This commit introduces `IOThresholdMax` as a field on `StoreCapacity`.
IOThresholdMax holds the store's maximum IO threshold over the last 5
minutes.

Part of: https://github.com/cockroachdb/cockroach/issues/118866
Epic: none
Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Previously, this score would be the last instantaneous value gossiped ... To avoid leases shedding quickly  from one node to another, consider the maximum IO threshold score instead.

slightly confused. If a single instantaneous score in a 5 min interval is high, wouldn't that be the max and therefore result in even more quick shedding. Was the idea to use min instead of max? Should it be a smoothed value which gives higher weight to more recent sample(s)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119433#-:-Nso0sLp0VEk8P56V1X3:bi0ryk5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Review by kvoli — COMMENTED** [review]
> If a single instantaneous score in a 5 min interval is high, wouldn't that be the max and therefore result in even more quick shedding. Was the idea to use min instead of max?

The leases would shed either way on the tick it exceeds the threshold, I suppose what I mean is that the leases wouldn't then come back to the previously shed node quickly, they'd need to wait out a 5 minute timer e.g.

without a smoothed max:

```
t.       : s1 io > shed_threshold (0.4) , sheds leases
t+20s    : s1 io < block_threshold (0.3), leases transfer back to s1
... 
```

> Should it be a smoothed value which gives higher weight to more recent sample(s)?

This might also be fine if we took a decaying avg or something similar, the max was simpler to reason about.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119433#-:-Nso8quj8gFJrBxFRIoz:b1lrigk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Review by sumeerbhola — COMMENTED** [review]
> I suppose what I mean is that the leases wouldn't then come back to the previously shed node quickly, they'd need to wait out a 5 minute timer

makes sense

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119433#-:-NsoFtvN6piaGQ_FzBDS:b-albqrb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

This change looks good. Thank you for moving the computation to the server side as it will ensure we have good backwards compatibility strategies.

I am a little concerned about the CPU cost of computing these scores, and specifically some of the averages. I'm not sure if we have any "allocator perf tests", and its not required as part of this PR, but it would be good with PRs like this to have a "before and after" measurement of the cost of running a replica through the allocator queue, especially with a higher RF (like 7) to make sure we aren't adding too much extra cost and to help reduce cost where we can. No need to change this PR, but consider adding this testing as part of stability.

> Reviewed 3 of 3 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119433#-:-Nt1DMTt-I2aNLaL-hC1:b-lum01x)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Review by kvoli — COMMENTED** [review]
Good idea, I'd be surprised if it changed that much here, iirc simulator profiles showed most low hanging fruit with logging.

Filed https://github.com/cockroachdb/cockroach/issues/120548.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119433#-:-Nt1_AEH90dICSK6Y9Dy:b-6kwgwb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
TYFTR

bors r=andrewbaptist

**Pull request merged**
