### PR TITLE
kv: don't update timestamp cache for unevaluated Get requests

### PR DESCRIPTION
**Pull request by nvb**
This commit adds logic to avoid accounting for Get requests which were not evaluated due to a batch-level byte or key limit. This parallels existing logic that does the same for Scan and ReverseScan requests. This was likely missed in the past because we only recently began using Get requests in more places.

The effect of this change is that limited batches of point reads will conflict less with writes, reducing read/write contention. Batches of this form could be issued by statements that look like: `SELECT * FROM t WHERE id IN (1, 3, 5) LIMIT 2`.

### CODE REVIEW

**Comment by tbg** [comment]
Just a drive-by, curious if this showed up somewhere.

**Comment by nvanbenschoten** [comment]
No, it did not directly show up anywhere. I noticed the omission in the code while exploring ways to improve transaction contention during jobs scheduling (ref: https://github.com/cockroachdb/cockroach/issues/78465 and its related support issue).

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78584#-:-MzLnSy-A4SYKBSYtsw5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
