### PR TITLE
storage: disallow nil settings in StorageConfig

### PR DESCRIPTION
**Pull request by RaduBerinde**
Tolerating nil settings is tedious and error-prone. We don't want these settings to be unset in production paths. This change makes it non-optional.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95243#-:-NMB02vU1Oe9uaBiTKWI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/storage/open.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95243#-NMB-inrD_I3Ke-6EbOX:-NMB-inrD_I3Ke-6EbOY:bl55ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/f227bd44117826f77f62a81a7f18468b40bbb4e7/pkg/storage/open.go#L252)):*
> ```Go
> 	if cfg.Settings == nil {
> 		// TODO(radu): this seems error-prone; should we require the use of
> 		// Settings() in all cases?
> ```

if we do, my preference would be to lift the settings into a required parameter,  and keep the `ConfigOption`s as optional only

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95243)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @michae2)

___
*[`pkg/storage/open.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95243#-NMB-inrD_I3Ke-6EbOX:-NMB5Ui-8t29ykMq8Dpz:b-kouhp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f227bd44117826f77f62a81a7f18468b40bbb4e7/pkg/storage/open.go#L252)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

if we do, my preference would be to lift the settings into a required parameter,  and keep the `ConfigOption`s as optional only
</blockquote></details>

I like it!! Done.

**Review by michae2 — APPROVED** [review]
SQL bits :lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 40 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95243#-:-NMBPurS8h3t_iMaVSrw:b-dtknjl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Comment by yuzefovich** [comment]
This missed at least one spot in the benchmarks (which are included in `Bazel Extended CI`):
```
17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test] --- BENCH: BenchmarkRowContainerAt-16
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/2464ce3205778481c7831decfd0edcdf/logBenchmarkRowContainerAt3373164158
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     test_log_scope.go:79: use -show-logs to present logs inline
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     datum_row_container_test.go:196: -- test log scope end --
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test] --- FAIL: BenchmarkNumberedContainerIteratorCaching
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/2464ce3205778481c7831decfd0edcdf/logBenchmarkNumberedContainerIteratorCaching2728477791
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     test_log_scope.go:79: use -show-logs to present logs inline
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     numbered_row_container_test.go:570: NewPebble requires cfg.Settings to be set
[17:50:12][Bench //pkg/sql/rowcontainer:rowcontainer_test]     panic.go:522: -- test log scope end --
```

**Comment by RaduBerinde** [comment]
Thanks @yuzefovich, I'll take care of it.

**Comment by yuzefovich** [comment]
I just opened up #95711 for a few things I found on a quick look.

**Pull request merged**
