### PR TITLE
sql: ensure that the COUNT builtins have an eval fn attached.

### PR DESCRIPTION
**Pull request by knz**
Fixes https://github.com/cockroachlabs/registration/issues/23.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7033)

### CODE REVIEW

**Comment by tamird** [comment]
yay. LGTM

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 1090 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033#-KJMFWSP5XRRTAqM-QmD:-KJMFWSP5XRRTAqM-QmE:1904532874) ([raw file](https://github.com/cockroachdb/cockroach/blob/8698523a851665795a7631cc89a7cb5f80e8ad99/sql/parser/builtins.go#L1090)):*
> ```Go
> 			Types:      ArgTypes{t},
> 			ReturnType: TypeInt,
> 			fn:         identityFn,
> ```

Aggregates aren't supposed to need an fn IIRC.

---

*[sql/testdata/aggregate, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033#-KJMF5INuwm0kHc9wJjH:-KJMF5INuwm0kHc9wJjI:1083431242) ([raw file](https://github.com/cockroachdb/cockroach/blob/8698523a851665795a7631cc89a7cb5f80e8ad99/sql/testdata/aggregate#L68)):*
> ```
> # Rendering the group column should work.
> query II rowsort
> SELECT v, COUNT(DISTINCT w) FROM kv GROUP BY v, COUNT(DISTINCT w)
> ```

I don't think this is valid -- you cannot have an aggregate expression in the GROUP BY.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033)*

**Comment by dt** [comment]
I think this is the wrong fix -- we should be rejecting the query because of the invalid group by, not trying to make a raw (unreplaced agg func)  be eval'ed.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> yay. LGTM
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033#-:-KJMGYleDWqFdcvnlSsM:1250954840)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/testdata/aggregate, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033#-KJMF5INuwm0kHc9wJjH:-KJMGe1YspU5uDMrQV6n:-1347925245) ([raw file](https://github.com/cockroachdb/cockroach/blob/8698523a851665795a7631cc89a7cb5f80e8ad99/sql/testdata/aggregate#L68)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I don't think this is valid -- you cannot have an aggregate expression in the GROUP BY.
</details>
I think you're right. pg produces:
```
test=# SELECT v, COUNT(DISTINCT w) FROM kv GROUP BY v, COUNT(DISTINCT w);
ERROR:  aggregate functions are not allowed in GROUP BY
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7033)*

**Comment by knz** [comment]
@dt agreed, I'm filing #7034 to look at this. Someone will have to fix the registration server's query however.

**Comment by dt** [comment]
what? why was this merged?

**Comment by tamird** [comment]
Yeah, this is no bueno. Let's revert this and fix it propery.

**Comment by knz** [comment]
I want to follow this up using a separate PR. This fixes the panic; the "good fix" will require fixing the reg server code!

**Comment by dt** [comment]
disagree -- imo returning an error on > crashing > appearing to work but silently returning incorrect results.

**Pull request merged**
