### PR TITLE
sql: allow user priority to be set via SQL

### LINKED ISSUE #2555: sql: allow user priority to be set via SQL
Cockroach internally allows a user priority to be set on all operations. This is particularly relevant to the operation of transactions, where the user priority is used to generate a random priority for the transaction as a whole. Transactions which conflict use the priorities to determine which can be pushed or aborted as necessary.

* Do some research into the SQL 92 ANSI standard and see if there's any equivalent or near-equivalent mechanism for supporting priorities.
* Make determination whether to use existing prioritization scheme or to introduce our own (probably something similar to the way we currently set the database syntax via `SET SYNTAX = modern`).
* Thread the user priority through to the underlying KV commands.

### PR DESCRIPTION
**Pull request by yaojingguo**
Fixes #2555

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3912)

### CODE REVIEW

**Comment by yaojingguo** [comment]
A new squashed commit after changing `%f` to `%g` in `return fmt.Sprintf("%g", float64(up))`

**Comment by petermattis** [comment]
Generally looks pretty good. Thanks for tackling this.

---

Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8LFfk8fQbz2GOvj1oU:39897740) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
Is this type being used?

---

*[roachpb/api.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LD8QE-niVPVd4DyX-:-K8LD8QE-niVPVd4DyX0:557557546) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L34)):*
Perhaps add a constant for `unspecifiedUserPriority = 0`.

---

*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8LF4nhWgPfVnbaChtk:1915367393) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
See my other comment about needing a comma separator here and about adding a test case to `TestParse`.

---

*[sql/parser/sql.y, line 1464 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8KTyN2_sMI5GdQi82D:-K8KTyN2_sMI5GdQi82E:-1159176929) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe345989c4b9d588c9494d61f0867afd11dcd87c/sql/parser/sql.y#L1464)):*
You've got some spurious white space at the end of this line.

---

*[sql/parser/sql.y, line 907 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LDad071otUooi6Ev9:-K8LDad071otUooi6EvA:-1463327626) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/sql.y#L907)):*
Looks like you're using tabs while this file is using spaces. Let's stick with spaces for consistency.

---

*[sql/parser/txn.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LEFX3y5utAmmsbonr:-K8LEFX3y5utAmmsbons:-1185741326) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/txn.go#L84)):*
I think you need a comma if `node.Isolation != UnspecifiedIsolation`. Something like:

```
var sep string
if node.Isolation != UnspecifedIsolation {
  fmt.Fprintf(...)
  sep = ","
}
if node.UserPriority != UnspecifedUserPriority {
  fmt.Fprintf(&buf, "%s PRIORITY %s", sep, node.UserPriority)
}
```

You should also add a test case to `TestParse` which verifies the "round-tripping" of parsing back to SQL. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K8LFl1GYKtEXddOsXzX:554520044)*

**Comment by yaojingguo** [comment]
Thanks for the helpful code review.

---

Review status: 0 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8NoVnsnLJgbTdX4nap:-876328392) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
This type is only used to provide the `UserPriority.String` function.  `UserPriority.String` is used by `v.rows = append(v.rows, []parser.Datum{parser.DString((roachpb.UserPriority(p.txn.UserPriority)).String())})
` in `sql/planner.Show`. I have tried to use type `UserPriority` in `roachpb/api.proto` with the following code:

```
	optional double user_priority = 4 [(gogoproto.nullable) = false,
	   (gogoproto.customname) = "UserPriority", (gogoproto.casttype) = "UserPriority"];
```

But when I ran `make build`, I got the following error:

```
roachpb/api.pb.go:3091: cannot use m.UserPriority (type UserPriority) as type float64 in argument to math.Float64bits
```

It seems that `gogoproto.casttype` does not support `double`. So `UserPriority` is used in the current way. Any suggestion on this?

---

*[roachpb/api.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LD8QE-niVPVd4DyX-:-K8NmLLYc9ufhXKoUUZR:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L34)):*
Done

---

*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8NlP8mdAJzWuY65_sS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
Done.

---

*[sql/parser/sql.y, line 1464 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8KTyN2_sMI5GdQi82D:-K8NPRXRvY8kFFecz0AS:-9142296) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe345989c4b9d588c9494d61f0867afd11dcd87c/sql/parser/sql.y#L1464)):*
Yes, my careless mistake.

---

*[sql/parser/sql.y, line 907 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LDad071otUooi6Ev9:-K8NmcRx-buTquCdmQMn:407185734) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/sql.y#L907)):*
Yes. My careless mistake.

---

*[sql/parser/txn.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LEFX3y5utAmmsbonr:-K8NQ64uUCT2rX1-TVlh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/txn.go#L84)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K8NoFAFuueVsrFsj_Rk:-979389921)*

**Comment by tamird** [comment]
Reviewed 10 of 15 files at r1.
Review status: 10 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8Oe289bEyM6mtrxF0o:-835809131) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
FYI https://github.com/gogo/protobuf/pull/139/files

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by yaojingguo** [comment]
Review status: 10 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8P2cCUXPDrd2g9Guy3:883131483) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
Thanks for letting me know.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by petermattis** [comment]
Review status: 10 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8PqPKxEvOIc4cwnC4O:-2001037409) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
I'm not seeing the changes. Did you forget to push the new commit?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by yaojingguo** [comment]
*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8RckZzb28JumTO7Kfk:-1882677044) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
Sorry for that. I have just pushed the new commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by petermattis** [comment]
Review status: 9 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8_lq_mPegQy3kJj_Lx:1971670982) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
The comma should only be printed if `node.Isolation != UnspecifiedIsolation`. Otherwise you'll get output that looks like: `SET TRANSACTION, PRIORITY LOW`.

---

*[sql/parser/txn.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LEFX3y5utAmmsbonr:-K8_m2qxz1sB3ANlb0vf:-608896183) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/txn.go#L84)):*
See my other comment about when the comma should be output. That's why I suggested using a `sep` (separator) variable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by yaojingguo** [comment]
Review status: 9 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/set.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LF4nhWgPfVnbaChtj:-K8ay88HCLnX-abu1M8g:373832916) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/set.go#L56)):*
I see. Done in another new commit.

---

*[sql/parser/txn.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LEFX3y5utAmmsbonr:-K8ayD0c-VzHvpPz2sxV:-992229288) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/sql/parser/txn.go#L84)):*
Done in another new commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r4.
Review status: 10 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8tUG1lTqiVVmso3V9D:426885881) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
@yaojingguo that issue has been fixed in gogo/protobuf. Can you update this PR to make use of that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by petermattis** [comment]
LGTM

You should squash the commits and rebase before merging.

---

Review status: 10 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K8tU5loLlMUHSEusCM7:890874184)*

**Comment by yaojingguo** [comment]
A new squashed commit:

1. @tamird Please help me review the usage of gogoproto.casttype for user_priority.
2. @petermattis Since MaxUserPriority has been updated to 1000 and MinUserPriority has been updated to 0.001, I have updated HighUserPriority to 10 and  LowUserPriority to 0.1. The reason is that I think that a 10 times probability to win over NormalUserPriority (1) and a 1/10 times probability to win over NormalUserPriority are more usable. 100 is too large and 0.001 is too small. How you think?

---

Review status: 0 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/api.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8LFfk7K0DyErPdwbwQ:-K8yomrRgA_SzzmoN1kp:269098182) ([raw file](https://github.com/cockroachdb/cockroach/blob/997a4e33e8b60718eb031eaefe13450517306a45/roachpb/api.go#L27)):*
Done in the new squashed commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K8yoteiTnAT_HjjUtL_:1614231510)*

**Comment by tamird** [comment]
Reviewed 1 of 15 files at r1, 28 of 28 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/txn.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yvmoKYpgYqwyQhfcj:-K8yvmoKYpgYqwyQhfck:-988572297) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/client/txn.go#L137)):*
consider removing this. if the transaction is in-flight, this should return an error regardless of whether the new value is the same as the existing value.

---

*[roachpb/api.proto, line 594 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yu8ouRBrNF0EUfAsj:-K8yu8ouRBrNF0EUfAsk:-1245234652) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/roachpb/api.proto#L594)):*
no need for the custom name

---

*[sql/session.proto, line 34 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yuE6SVraZ_PGrOHxl:-K8yuE6SVraZ_PGrOHxm:-1245234652) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/sql/session.proto#L34)):*
no need for the custom name

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[roachpb/api.go, line 32 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8zDSr03qi-LDCbuxUf:-K8zDSr03qi-LDCbuxUg:-1822101901) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/roachpb/api.go#L32)):*
`0.1` cannot be represented exactly as a `float64`, so there will always be some round-off error here. It should usually be OK since we're just passing the same value around without doing any math on it, but using floating-point equality here doesn't feel right. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K8zF37uZd8dPvoHX0MX:676834233)*

**Comment by yaojingguo** [comment]
Review status: 26 of 29 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/txn.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yvmoKYpgYqwyQhfcj:-K92vJi8vhu2_PvyNIsT:-217117390) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/client/txn.go#L137)):*
`SetIsolation` does nothing if the given `isolation` is the same as the existing isolation level of an in-flight transaction. And some test cases in `./kv` have already depended on this behavior. `SetUserPriority` is following `SetIsolation`'s approach. If we want to remove `txn.UserPriority != userPriority` for `SetUserPriority`, we should also remove `txn.Proto.Isolation != isolation` for `SetIsolation` to keep them in consistency. Do you want me to do that?

---

*[roachpb/api.go, line 32 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8zDSr03qi-LDCbuxUf:-K91KOlN5CVYCUWyAIpz:1256677149) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/roachpb/api.go#L32)):*
I can think of the following three choices to address this problem: 

1. Keep the current implementation. Although `0.1` can not be represented exactly as `float64`, `0.1 == 0.1` return `true` since these two values are the same thing. Since `float64(float32(0.1)) == float64(0.1)` return `false`, there will be some surprising results if we are not careful.
2. Make the range of `UserPriority` to `[1, 1000000]` instead of `[0.001, 1000]`. Then the floating-point equality can be eliminated. But a user priority `up` in the range`[1, 1000000]` does not mean any more that it has times `up` probability to win over user priority `1`.
3. Use something like `math.Abs(userPriority - LowUserPriority) < EPSILON` to do the equality check.

I think that choice 1 is better compared to choice 2 and choice 3.

---

*[roachpb/api.proto, line 594 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yu8ouRBrNF0EUfAsj:-K903wrYYa740SKHOnIj:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/roachpb/api.proto#L594)):*
Done.

---

*[sql/session.proto, line 34 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yuE6SVraZ_PGrOHxl:-K904-vBaKHcOW2_E_ac:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/sql/session.proto#L34)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by bdarnell** [comment]
Review status: 26 of 29 files reviewed at latest revision, 5 unresolved discussions.

---

*[roachpb/api.go, line 32 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8zDSr03qi-LDCbuxUf:-K93FxXvVz3LQrfOVyEq:-1506675235) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/roachpb/api.go#L32)):*
Fine with me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yvmoKYpgYqwyQhfcj:-K93O7CITDn19N4xDP9v:-1376562666) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/client/txn.go#L137)):*
I'd like to see that, yes, but it can go in a different PR if you prefer not to tackle it here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912)*

**Comment by yaojingguo** [comment]
@petermattis Are you satisfied with the follow change?

> Since MaxUserPriority has been updated to 1000 and MinUserPriority has been updated to 0.001, I have updated HighUserPriority to 10 and LowUserPriority to 0.1. The reason is that I think that a 10 times probability to win over NormalUserPriority (1) and a 1/10 times probability to win over NormalUserPriority are more usable. 100 is too large and 0.001 is too small. How you think?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-K8yvmoKYpgYqwyQhfcj:-K95fPNFv-NdJ1xMgG1G:-2055588591) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe3ce1f1f01937a1397267b2569230e77523faae/client/txn.go#L137)):*
I will do it in https://github.com/cockroachdb/cockroach/issues/4003.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K95dnCU5drcfT7kbMqk:-942140960)*

**Comment by petermattis** [comment]
@yaojingguo Seems reasonable to me. We'll have time to adjust these constants if the current settings prove problematic.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3912#-:-K98UIRwdhILVEJ_2S6r:1127671197)*

**Pull request merged**
