### PR TITLE
sql/logictest: add edge case + overflow logic tests

### PR DESCRIPTION
**Pull request by madelynnblue**
This may help the upcoming vectorized engine to find some bugs before
turning on by default.

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
:lgtm:

Unfortunately as it stands I think the vectorized engine will execute very few (if any) of these due to things like mixed types (e.g. due to type promotion), casts, and the `ROWS FROM` clause. But it's still a good set of test cases which we can tweak once we start adding overflow handling.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38921#-:-Lk-KDNv7YXsqjSLcZfl:bbqfa8x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Comment by mjibson** [comment]
Added floats, simplified some of the SQL so that (one day) maybe vectorized will execute it. Added a fix for sum_int. PTAL.

**Review by solongordon — APPROVED** [review]
Good stuff!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38921#-:-Lk59nqk-Qd8EMjB3Bjj:beuyiaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rafiss)

**Pull request merged**
