### PR TITLE
release-21.1: tree: make string concat do a normal cast

### PR DESCRIPTION
**Pull request by rafiss**
Backport 2/2 commits from #65019.

/cc @cockroachdb/release

---

This also includes one additional commit to prevent date->string cast
in postgres computed columns.

Both issues were identified by the ComposeCompare tests. https://github.com/cockroachdb/cockroach/issues/56845

Release note (bug fix): Previously concatenating a non-string with a
string would not use the normal string representation of the non-string
value. Now it does, so `true || 'string'` returns `truestring` instead
of `tstring`.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
how strongly do you feel this should be in v21.1.1? seems like it doesn't strictly meet the criteria as it is a behaviour change from a previous version of CockroachDB :\

**Comment by rafiss** [comment]
this casting behavior was introduced in v21.1.0 and the `non-string || string` concat was added for compatbility, so i think we should include this bugfix.

**Comment by rafiss** [comment]
that is, 21.1.0 is the first release that includes https://github.com/cockroachdb/cockroach/pull/55611

**Review by otan — APPROVED** [review]
aha! sgtm

**Pull request merged**
