### PR TITLE
Updated docs/codelab1 

### PR DESCRIPTION
**Pull request by ZhouXing19**
- Added clarifying text. 
- Fixed nit in coding.
- The original testing method is replaced by `drivenbydata` testing.

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
Good stuff, thanks for updating this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-:-MeW0s1Q3i2YxmDe5QLo:b37nnn1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[.idea/workspace.xml, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW-ZJN6VNSg2GHFrG0:-MeW-ZJN6VNSg2GHFrG1:b8aqz1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/.idea/workspace.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

This file shouldn't be checked in.
You should add .idea to your .gitignore or global gitignore.
___
*[docs/codelabs/01-sql-statement.md, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW-qd57jbcAYcDHvN3:-MeW-qd57jbcAYcDHvN4:b-faw048) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L104)):*
> ```Markdown
> | FROBNICATE ALL { return unimplemented(sqllex, "frobnicate all") }
> ```
> For now we'll eave it unimplemented, but we'll come back and take care of that later.
> ```

typo: leave
___
*[docs/codelabs/01-sql-statement.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW00tX2W-gwi16_ymL:-MeW00tX2W-gwi16_ymM:b-w7nxag) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L151)):*
> ```Markdown
> ```
> 
> Also open `pkg/sql/parser/gen/sql-gen.y`, search for `frobnicate` and see if the grammar is added.
> ```

Checking `sql.go` is enough, I don't think we need this line.
___
*[docs/codelabs/01-sql-statement.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW061h1LKlFA8-_Cp2:-MeW061h1LKlFA8-_Cp3:b-gzwoyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L161)):*
> ```Markdown
> ```
> 
> Finally, let’s run a single-node Cockroach instance. Make sure you are at `~/go/src/github.com/cockroachdb/cockroach` and
> ```

I would say run from your `cockroachdb/cockroach` directory. It's possible that people have other paths.
___
*[docs/codelabs/01-sql-statement.md, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0D9l45PfrOcUCdG4:-MeW0D9l45PfrOcUCdG5:bxtxhi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L173)):*
> ```Markdown
> statement:
> 
> ```go
> ```

I think text was fine here.
___
*[docs/codelabs/01-sql-statement.md, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0HnN2tX-GX8PoFpB:-MeW0HnN2tX-GX8PoFpC:b-sowyac) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L266)):*
> ```Markdown
> ```
> 
> Then, go to the bottom of this file, and add
> ```

Note that this should also be added in alphabetical order.
___
*[docs/codelabs/01-sql-statement.md, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0ZAB3RDJ95P_1mZE:-MeW0ZAB3RDJ95P_1mZF:b-cxvxtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L494)):*
> ```Markdown
> 
> Back to the terminal, make sure you are at `~/go/src/github.com/cockroachdb/cockroach`,
> and run `make test PKG=./pkg/sql/parser TESTS=TestParseDatadriven TESTFLAGS="-rewrite" FILES=grant_revoke`
> ```

I would add a comment here saying that `TESTFLAGS="-rewrite"` will automatically rewrite the datadriven test with the output it received. 

When doing this, carefully verify that the output is expected.

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[docs/codelabs/01-sql-statement.md, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW-qd57jbcAYcDHvN3:-MeW3pVyBersXLUj0a-c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L104)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

typo: leave
</blockquote></details>

Done.
___
*[docs/codelabs/01-sql-statement.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW00tX2W-gwi16_ymL:-MeW3urCEso9YO2Kh1Tu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L151)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Checking `sql.go` is enough, I don't think we need this line.
</blockquote></details>

Done.
___
*[docs/codelabs/01-sql-statement.md, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW061h1LKlFA8-_Cp2:-MeW3vh6-Vv9W0fIhJi-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L161)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I would say run from your `cockroachdb/cockroach` directory. It's possible that people have other paths.
</blockquote></details>

Done.
___
*[docs/codelabs/01-sql-statement.md, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0D9l45PfrOcUCdG4:-MeW3wri1woogUKx6IY3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L173)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think text was fine here.
</blockquote></details>

Done.
___
*[docs/codelabs/01-sql-statement.md, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0HnN2tX-GX8PoFpB:-MeW3yKk9RfJk_3AqhBk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L266)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Note that this should also be added in alphabetical order.
</blockquote></details>

Done.
___
*[docs/codelabs/01-sql-statement.md, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW0ZAB3RDJ95P_1mZE:-MeW4-uE1wKosFub266K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/docs/codelabs/01-sql-statement.md#L494)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I would add a comment here saying that `TESTFLAGS="-rewrite"` will automatically rewrite the datadriven test with the output it received. 

When doing this, carefully verify that the output is expected.
</blockquote></details>

Done.
___
*[.idea/workspace.xml, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW-ZJN6VNSg2GHFrG0:-MeW41dq3h3IZxM1UYSc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d471ba5802ca63864e6f5eea1a8e719881514f79/.idea/workspace.xml#L1)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This file shouldn't be checked in.
You should add .idea to your .gitignore or global gitignore.
</blockquote></details>

Done.

**Review by RichardJCai — APPROVED** [review]
LGTM mod nit about the comment spacing

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-:-MeW8VoJ0njdKU30jJfT:b-wj098s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @ZhouXing19)

___
*[docs/codelabs/01-sql-statement.md, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67541#-MeW8BMt1OqkYar-D8hQ:-MeW8BMt1OqkYar-D8hR:b-x44yff) ([raw file](https://github.com/cockroachdb/cockroach/blob/effa3771e384fdbd21b56a5578669509116c013f/docs/codelabs/01-sql-statement.md#L91)):*
> ```Markdown
> stmt:
> ...
> | frobnicate_stmt           // EXTEND WITH HELP: FROBNICATE
> ```

nit: Don't need to add the spacing between the stmt and comment here.
(Only in the code)

**Pull request merged**
