### PR TITLE
add zero padding, insert order, and time stamp in text

### LINKED ISSUE #50545: workload/ycsb: add timestamp in the field[0-9] as well as random string
**Is your feature request related to a problem? Please describe.**

random strings are populated in YCSB `fields[0-9]`.  having context to when the field was updated can be helpful for demos.  For example, backup, restore and CDC showing the context of what was changed is useful.

**Describe the solution you'd like**
prepend time in UTC format that matches CRDB's time printing format.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by robert-s-lee**
`--insert-hash=true` creates `user1`, `user2` for `ycsb_key`
`--zero-padding=2` creates `user01`, `user02` for `ycsb_key`
`--time-string=true` creates `field[0-9]` with

```
2020-06-23 13:23:58.529711+00:00DwYFKxzTOKqgYwdHZNmbzdkRfINphVojmwiDbhaFsEnFHRpxSJQdSRnXOrQbjJhjYzko
```
instead of
```
rmArXhKIjbpTAPwyjDNsmkGTLXWNQHQCLAyKwWFOrlopXliOKqQANpakAxsmqfPzYSvAhgYYVQQDhUEuXCVuvsEdJrrguNSaXDbx
```

Closes #50545 and #50544

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@robert-s-lee could you describe the motivation here? It looks like some, but not all, of these flags are coming from the official YCSB. Is the idea to make this version more feature-complete?

**Comment by robert-s-lee** [comment]
We use YCSB for demos of the locality and these fill the gap.

**Review by nvb — APPROVED** [review]
:lgtm: but you'll need to rebase first. Thanks for doing this.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50546#-:-MAfum_a0-sxqIcnV2-r:b-2n1s0s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @robert-s-lee)

___
*[pkg/workload/ycsb/ycsb.go, line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50546#-MAftq7n7pEVgq2g5Ncv:-MAftq7n7pEVgq2g5Ncw:b-f83s7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/227af803ea3408d7eefe26b0619d10da28e1898b/pkg/workload/ycsb/ycsb.go#L616)):*
> ```Go
> 	strStart := 0
> 	if yw.config.timeString {
> 		loc, _ := time.LoadLocation(timeZoneDefault)
> ```

You can replace these two lines with `curTime := time.Now().UTC()`
___
*[pkg/workload/ycsb/ycsb.go, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50546#-MAfu1Xq0ZN8SUnC4QNI:-MAfu1Xq0ZN8SUnC4QNJ:b-2az8ua) ([raw file](https://github.com/cockroachdb/cockroach/blob/227af803ea3408d7eefe26b0619d10da28e1898b/pkg/workload/ycsb/ycsb.go#L618)):*
> ```Go
> 		loc, _ := time.LoadLocation(timeZoneDefault)
> 		currentTime := time.Now().In(loc)
> 		copy(str, currentTime.Format(timeFormatTemplate))
> ```

We can avoid the intermediate allocation and the `timeFormatLen` const with:
```
str = curTime.AppendFormat(str[:0], timeFormatTemplate)
strStart = len(str)
str = str[:length]
```

**Comment by knz** [comment]
Something went amiss with the rebase.

**Pull request merged**
