### PR TITLE
goroutinedumper: Gzip files

### LINKED ISSUE #36846: goroutinedumper: Compress files
Goroutine dumps are large, but compress well. With default settings, the goroutine dumper will fire when there are 1000 goroutines, which produces a file of about 9MB that gzips down to 500KB. We should compress the files we write here (and probably reduce the `total_dump_size_limit` - spending half a gig on this is kind of silly when we only budget 100MB for logs in `util/log`). 

I'm noticing this because #35986 produces 400MB of goroutine dumps per run (twice the size of its log files), so stressing it keeps filling up my local disk.

### PR DESCRIPTION
**Pull request by giorgosp**
Fixes #36846

Release note: None

### CODE REVIEW

**Review by giorgosp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36922)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/zip.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-LcgrDeQBa1GQ0ThCwdD:-LcgrDeQBa1GQ0ThCwdE:bcr0uex) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62203c235032158913d32644172109be08dd5b9/pkg/cli/zip.go#L401)):*
> ```Go
> 				}
> 				for _, file := range goroutinesResp.Files {
> 					name := prefix + "/goroutines/" + file.Name + ".txt"
> ```

@tbg Actually I removed the file extension from the zip command since the files are already written with the extension. What do you think?

**Review by tbg — APPROVED** [review]
:lgtm:, thanks a lot!

There's more where this came from if you're interested -- take a look at https://github.com/cockroachdb/cockroach/issues/25333#issuecomment-448215722 if you'd like!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-:-LcgvOCV441DviLkP4PZ:b-2pe99x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @giorgosp)

___
*[pkg/cli/zip.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-LcgrDeQBa1GQ0ThCwdD:-Lcgv1uLBBRZWvp8YmuC:bc3fa7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62203c235032158913d32644172109be08dd5b9/pkg/cli/zip.go#L401)):*
Yep, good call! Since you're eating another CI cycle anyway, add a comment such as

> // NB: the files have a `.txt.gz` suffix already.
___
*[pkg/server/goroutinedumper/goroutinedumper.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-LcgyRtUCwSmOkzFEODQ:-LcgyRtUCwSmOkzFEODR:b-myb8o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b646ed0c3ec882b7dffabdbbfe944ba921e4c62/pkg/server/goroutinedumper/goroutinedumper.go#L187)):*
> ```Go
> 	defer f.Close()
> 	w := gzip.NewWriter(f)
> 	defer w.Close()
> ```

This returns an error, so remove this defer, add `_ = w.Close()` in the `err != nil` branch below, and change the `return nil` to return `w.Close()`.

This is also why CI is red - some linter caught it.

**Review by giorgosp — COMMENTED** [review]
Thanks, I'll do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-:-LcmvV82AkJxe8L6Ftnz:ba5qmeu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/cli/zip.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-LcgrDeQBa1GQ0ThCwdD:-LcmuKx8B6s_oIM4IEa8:b-hn29xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e62203c235032158913d32644172109be08dd5b9/pkg/cli/zip.go#L401)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yep, good call! Since you're eating another CI cycle anyway, add a comment such as

> // NB: the files have a `.txt.gz` suffix already.
</blockquote></details>

Added above
___
*[pkg/server/goroutinedumper/goroutinedumper.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-LcgyRtUCwSmOkzFEODQ:-LcmvAE1A1P4ulmRP99m:b-53axwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b646ed0c3ec882b7dffabdbbfe944ba921e4c62/pkg/server/goroutinedumper/goroutinedumper.go#L187)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This returns an error, so remove this defer, add `_ = w.Close()` in the `err != nil` branch below, and change the `return nil` to return `w.Close()`.

This is also why CI is red - some linter caught it.
</blockquote></details>

The gzip writer Close() doesn't close the underlying file so I fixed it a bit differently, inspired by https://www.joeshaw.org/dont-defer-close-on-writable-files/ as well. What do you think?

**Review by tbg — APPROVED** [review]
bors r=tbg

Thanks again! Github should've sent you an invite as a contributor to the repo, so you'll be able to merge your own changes (when they're approved) in the future.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36922#-:-LcoCfVXAFAZjOO3NHdr:b-kb4kfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

**Pull request merged**
