### PR TITLE
sql: miscellaneous grant option fixes

### PR DESCRIPTION
**Pull request by rafiss**
Recommended to review this commit-by-commit so the changes are easier to digest.

### sql: return error when missing grant options

Previously, a case was missed in the grant options check. If a user had
zero grant options at all, we were actually allowing them to grant any
privilege.

This also adds a check so we do not check for the old GRANT privilege if
the cluster has been upgraded to v22.1.

### descpb: don't give public role CONNECT grant option

The previous behavior was an oversight. This change matches the Postgres
behavior.

No release note since this is new in v22.1.

###  sql: grant options now inherit from parent roles

Release note: None

### CODE REVIEW

**Review by jackcwu — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/catalog/descpb/privilege.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrNc3y-A3prIHnPXTdq:-MrNc3y-A3prIHnPXTdr:bynmtgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54315dfd64173c7f38acd916d7208691a9c8804/pkg/sql/catalog/descpb/privilege.go#L190)):*
> ```Go
> 	if !exists {
> 		return pgerror.Newf(code,
> 			"missing WITH GRANT OPTION privilege on %s", privList.String(),
> ```

Good catch! I actually caught this same error on Friday but handled it slightly differently (the privilege I output in the error message was `privList[0].String()` to be more consistent with how when the user does exist, it terminates on the first privilege missing grant options).

I do think your solution is more elegant since we do have the foresight in this case that the user will not be able to grant any of the privileges in the list. However, should we consider being consistent with the other cases?



_Code quote:_
```Go
			"missing WITH GRANT OPTION privilege on %s", privList.String(),
```
___
*[pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option, line 365 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrNjGAu2VJsoWgkIBkx:-MrNjGAu2VJsoWgkIBky:bmhg7f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6979b5f50276cee43c5abf293957bb9615fc80/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L365)):*
> ```
> # Make sure that non-admin roles do not have CONNECT grant option inherited
> # from the public role.
> statement error user testuser2 missing WITH GRANT OPTION privilege on CONNEC
> ```

Should this be `CONNECT` at the end?



_Code quote:_
```
statement error user testuser2 missing WITH GRANT OPTION privilege on CONNEC
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu)

___
*[pkg/sql/catalog/descpb/privilege.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrNc3y-A3prIHnPXTdq:-MrO5XCz56fos70dxXJv:bx8ir8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c54315dfd64173c7f38acd916d7208691a9c8804/pkg/sql/catalog/descpb/privilege.go#L190)):*
<details><summary><i>Previously, jackcwu wrote…</i></summary><blockquote>

Good catch! I actually caught this same error on Friday but handled it slightly differently (the privilege I output in the error message was `privList[0].String()` to be more consistent with how when the user does exist, it terminates on the first privilege missing grant options).

I do think your solution is more elegant since we do have the foresight in this case that the user will not be able to grant any of the privileges in the list. However, should we consider being consistent with the other cases?
</blockquote></details>

in a later commit, i made the language more similar, and the error is returned from sql/authorization.go so it's always consistent
___
*[pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option, line 365 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrNjGAu2VJsoWgkIBkx:-MrO64im46yghQ0BGfdb:b-6fw2eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a6979b5f50276cee43c5abf293957bb9615fc80/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L365)):*
<details><summary><i>Previously, jackcwu wrote…</i></summary><blockquote>

Should this be `CONNECT` at the end?
</blockquote></details>

yup nice catch! it works out since the error checking works with a substring match, but i'll fix

**Review by jackcwu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu and @rafiss)

___
*[pkg/sql/authorization.go, line 190 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrOJEi6CXyX4KTIVTDA:-MrOJEi6CXyX4KTIVTDB:b-wfvgrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9f7cda80a34597d2b13f9117264f107e6fdee9/pkg/sql/authorization.go#L190)):*
> ```Go
> 	code := pgcode.WarningPrivilegeNotGranted
> 	if !isGrant {
> 		code = pgcode.WarningPrivilegeNotRevoked
> ```

I think there might be an edge case here in regards to the output. Let's say `testuser` (non-owner) holds `SELECT` and `INSERT` on table `t`, along with grant options for `SELECT`. 

`testuser` tries to grant `SELECT` and `INSERT` on table t to another user called `target`. `hasPriv` will return false since `privs.CheckGrantOptions()` will catch that `testuser` does not hold grant options on `INSERT` and return false.

The error message will say that `testuser` is missing grant options for every privilege it tried to grant in that query (`SELECT`, `INSERT`) when in reality it is only missing grant options for `INSERT`.



_Code quote:_
```Go
	privs := descriptor.GetPrivileges()
	hasPriv, err := p.checkRolePredicate(ctx, user, func(role security.SQLUsername) bool {
		return IsOwner(descriptor, role) || privs.CheckGrantOptions(role, privList)
	})
	if err != nil {
		return err
	}
	if hasPriv {
		return nil
	}

	code := pgcode.WarningPrivilegeNotGranted
	if !isGrant {
		code = pgcode.WarningPrivilegeNotRevoked
	}
	return pgerror.Newf(code,
		"user %s missing WITH GRANT OPTION privilege on %s", user, privList.String(),
	)
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu)

___
*[pkg/sql/authorization.go, line 190 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrOJEi6CXyX4KTIVTDA:-MrOLwHaDdwm0HFWfheA:bv8l7yf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9f7cda80a34597d2b13f9117264f107e6fdee9/pkg/sql/authorization.go#L190)):*
<details><summary><i>Previously, jackcwu wrote…</i></summary><blockquote>

I think there might be an edge case here in regards to the output. Let's say `testuser` (non-owner) holds `SELECT` and `INSERT` on table `t`, along with grant options for `SELECT`. 

`testuser` tries to grant `SELECT` and `INSERT` on table t to another user called `target`. `hasPriv` will return false since `privs.CheckGrantOptions()` will catch that `testuser` does not hold grant options on `INSERT` and return false.

The error message will say that `testuser` is missing grant options for every privilege it tried to grant in that query (`SELECT`, `INSERT`) when in reality it is only missing grant options for `INSERT`.
</blockquote></details>

hm yeah, that's an accurate point. i think i'd prefer to address this by changing the error message to "user %s missing WITH GRANT OPTION privilege on one or more of %s"

the reason is that this way, the user can just run one command to get all the grant options they need (and it's not a big deal if some of the grant option changes are a no-op).

alternatives:
* i don't want change this code to check each grant option one-by-one and then error on the first one. that could be frustrating, since then the user might have to get the grant option and try again, only to find that they still need another grant option.
* i don't want to add logic that checks each one-by-one and then exhaustively computes the diff of what's present and what's missing. that seems a bit overly complicated for what's needed for a helpful error message.

**Review by jackcwu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jackcwu and @rafiss)

___
*[pkg/sql/authorization.go, line 190 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/74000#-MrOJEi6CXyX4KTIVTDA:-MrOi9kgELDpfGSQc1a6:bog5o63) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9f7cda80a34597d2b13f9117264f107e6fdee9/pkg/sql/authorization.go#L190)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm yeah, that's an accurate point. i think i'd prefer to address this by changing the error message to "user %s missing WITH GRANT OPTION privilege on one or more of %s"

the reason is that this way, the user can just run one command to get all the grant options they need (and it's not a big deal if some of the grant option changes are a no-op).

alternatives:
* i don't want change this code to check each grant option one-by-one and then error on the first one. that could be frustrating, since then the user might have to get the grant option and try again, only to find that they still need another grant option.
* i don't want to add logic that checks each one-by-one and then exhaustively computes the diff of what's present and what's missing. that seems a bit overly complicated for what's needed for a helpful error message.
</blockquote></details>

Yep, that seems logical. Not a huge fan of how Postgres does it (I believe if there is at least one valid privilege in the statement they apply what's valid and give a warning saying "not all changes were applied", which doesn't really tell the user anything)

**Review by jackcwu — APPROVED** [review]
LGTM!

**Comment by rafiss** [comment]
tftr!

bors r=jackcwu

**Pull request merged**
