### PR TITLE
gossip: Reduce thrashing caused by process restarts

### LINKED ISSUE #9819: stability: long-lasting gossip connection thrashing
From #9749. We should figure out what was happening there and make sure we find out if it's happening again. See also #9817.
## 

Btw, gossip forwarding is somewhat unhappy. A 100 node cluster should reach a steady state where connections aren't thrashed as much, but they are. I don't think it interferes with operations much, but it's awkward.

```
104.197.7.85: I161006 21:40:32.818083 1505518 gossip/server.go:254  [n29] node 29: refusing gossip from node 40 (max 4 conns); forwarding to 72 ({tcp cockroach-omega-072:26257})
104.197.7.85: I161006 21:40:32.822056 1505518 gossip/server.go:254  [n29] node 29: refusing gossip from node 40 (max 4 conns); forwarding to 93 ({tcp cockroach-omega-093:26257})
104.197.7.85: I161006 21:40:32.822703 1505518 gossip/server.go:254  [n29] node 29: refusing gossip from node 40 (max 4 conns); forwarding to 72 ({tcp cockroach-omega-072:26257})
104.197.140.88: I161006 21:40:32.885913 1743625 gossip/server.go:254  [n12] node 12: refusing gossip from node 40 (max 4 conns); forwarding to 42 ({tcp cockroach-omega-042:26257})
104.197.140.88: I161006 21:40:32.903174 1743625 gossip/server.go:254  [n12] node 12: refusing gossip from node 40 (max 4 conns); forwarding to 7 ({tcp cockroach-omega-007:26257})
104.198.242.162: I161006 21:40:32.970412 1022050 gossip/server.go:254  [n5] node 5: refusing gossip from node 40 (max 4 conns); forwarding to 24 ({tcp cockroach-omega-024:26257})
104.198.242.162: I161006 21:40:32.973392 1022050 gossip/server.go:254  [n5] node 5: refusing gossip from node 40 (max 4 conns); forwarding to 24 ({tcp cockroach-omega-024:26257})
104.198.242.162: I161006 21:40:32.974201 1022050 gossip/server.go:254  [n5] node 5: refusing gossip from node 40 (max 4 conns); forwarding to 24 ({tcp cockroach-omega-024:26257})
130.211.189.253: I161006 21:40:32.977045 1474501 gossip/server.go:254  [n24] node 24: refusing gossip from node 40 (max 4 conns); forwarding to 51 ({tcp cockroach-omega-051:26257})
130.211.189.253: I161006 21:40:32.979703 1474501 gossip/server.go:254  [n24] node 24: refusing gossip from node 40 (max 4 conns); forwarding to 34 ({tcp cockroach-omega-034:26257})
130.211.189.253: I161006 21:40:32.981100 1474501 gossip/server.go:254  [n24] node 24: refusing gossip from node 40 (max 4 conns); forwarding to 33 ({tcp cockroach-omega-033:26257})
104.155.137.78: I161006 21:40:33.861200 1894980 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 65 ({tcp cockroach-omega-065:26257})
104.155.137.78: I161006 21:40:33.868766 1894980 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 12 ({tcp cockroach-omega-012:26257})
104.198.223.39: I161006 21:40:34.595144 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 85 ({tcp cockroach-omega-085:26257})
104.198.223.39: I161006 21:40:34.599871 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 22 ({tcp cockroach-omega-022:26257})
104.198.223.39: I161006 21:40:34.631990 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 89 ({tcp cockroach-omega-089:26257})
104.198.223.39: I161006 21:40:34.633451 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 89 ({tcp cockroach-omega-089:26257})
104.198.223.39: I161006 21:40:34.643484 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 89 ({tcp cockroach-omega-089:26257})
104.155.137.78: I161006 21:40:34.653518 1895834 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 37 ({tcp cockroach-omega-037:26257})
104.198.223.39: I161006 21:40:34.656862 1645601 gossip/server.go:254  [n23] node 23: refusing gossip from node 69 (max 4 conns); forwarding to 89 ({tcp cockroach-omega-089:26257})
104.155.137.78: I161006 21:40:34.664758 1895834 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 12 ({tcp cockroach-omega-012:26257})
104.155.137.78: I161006 21:40:34.667654 1895834 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 12 ({tcp cockroach-omega-012:26257})
104.155.137.78: I161006 21:40:34.722797 1895834 gossip/server.go:254  [n15] node 15: refusing gossip from node 69 (max 4 conns); forwarding to 65 ({tcp cockroach-omega-065:26257})
104.198.255.99: I161006 21:40:34.912909 1384896 gossip/server.go:254  [n26] node 26: refusing gossip from node 69 (max 4 conns); forwarding to 79 ({tcp cockroach-omega-079:26257})
104.198.33.57: I161006 21:40:34.986429 1378355 gossip/server.go:254  [n9] node 9: refusing gossip from node 69 (max 4 conns); forwarding to 66 ({tcp cockroach-omega-066:26257})
104.198.33.57: I161006 21:40:35.001922 1378355 gossip/server.go:254  [n9] node 9: refusing gossip from node 69 (max 4 conns); forwarding to 66 ({tcp cockroach-omega-066:26257})
104.198.33.57: I161006 21:40:35.010396 1378355 gossip/server.go:254  [n9] node 9: refusing gossip from node 69 (max 4 conns); forwarding to 61 ({tcp cockroach-omega-061:26257})
104.198.40.234: I161006 21:40:35.174897 1202176 gossip/server.go:254  [n30] node 30: refusing gossip from node 69 (max 4 conns); forwarding to 61 ({tcp cockroach-omega-061:26257})
104.198.40.234: I161006 21:40:35.184023 1202176 gossip/server.go:254  [n30] node 30: refusing gossip from node 69 (max 4 conns); forwarding to 88 ({tcp cockroach-omega-088:26257})
104.197.143.153: I161006 21:40:36.075797 2002615 gossip/server.go:254  [n11] node 11: refusing gossip from node 75 (max 4 conns); forwarding to 3 ({tcp cockroach-omega-003:26257})
104.198.241.226: I161006 21:40:36.131057 1318331 gossip/server.go:254  [n4] node 4: refusing gossip from node 75 (max 4 conns); forwarding to 10 ({tcp cockroach-omega-010:26257})
104.198.242.162: I161006 21:40:36.149840 1024407 gossip/server.go:254  [n5] node 5: refusing gossip from node 75 (max 4 conns); forwarding to 24 ({tcp cockroach-omega-024:26257})
130.211.189.253: I161006 21:40:36.182970 1478389 gossip/server.go:254  [n24] node 24: refusing gossip from node 75 (max 4 conns); forwarding to 51 ({tcp cockroach-omega-051:26257})
104.197.143.153: I161006 21:40:36.191283 2002615 gossip/server.go:254  [n11] node 11: refusing gossip from node 75 (max 4 conns); forwarding to 44 ({tcp cockroach-omega-044:26257})
104.197.143.153: I161006 21:40:36.200922 2002615 gossip/server.go:254  [n11] node 11: refusing gossip from node 75 (max 4 conns); forwarding to 52 ({tcp cockroach-omega-052:26257})
104.154.87.20: I161006 21:40:36.268781 1458432 gossip/server.go:254  [n14] node 14: refusing gossip from node 75 (max 4 conns); forwarding to 99 ({tcp cockroach-omega-099:26257})
104.198.57.154: I161006 21:40:36.306849 1662653 gossip/server.go:254  [n2] node 2: refusing gossip from node 75 (max 4 conns); forwarding to 36 ({tcp cockroach-omega-036:26257})
104.198.63.222: I161006 21:40:36.318390 1798429 gossip/server.go:254  [n3] node 3: refusing gossip from node 75 (max 4 conns); forwarding to 63 ({tcp cockro
```

### PR DESCRIPTION
**Pull request by a-robinson**
**storage: Add extra logging in maybeGossipSystemConfig**

**gossip: Reduce thrashing by only using NodeID keys in mostDistant**

NodeID infos are reliably re-gossiped periodically and on restart,
making it much less likely that process restarts can lead to large
Hops values, which has shown itself to be a problem for the system
config info.

Fixes #9819

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

As an alternative (or complementary) suggestion: we could set inbound Infos' Hops to 0 when their node ID matches ours, and also iterate over our Infos whenever we connect to a new node and set Hops to 0 for all Infos with the new peer's node ID. Unfortunately, that's not great either, because it is likely to produce the opposite problem of unrealistically _low_ Hops in the presence of thrashing where nodes are always reconnecting to each other, ending up with all Infos having Hops == 0. It would probably work out OK because we only ever care about the highest Hops value, and once that value got high enough, nodes would connect to the originator, resetting Hops to zero. It can definitely still produce thrashing, as you point out in https://github.com/cockroachdb/cockroach/issues/9819#issuecomment-298268202, but it won't be pathological like it is today.

Relying on the node ID keys alone is worrisome because of https://github.com/cockroachdb/cockroach/issues/15163#issuecomment-298253492, where blue 7 (still) does not have a gossip node ID key at all. Though perhaps something much worse is going on there.

If we don't do any of the above, we should consider moving Hops to a narrower type than Info - otherwise it's a bit of a trap, I think.

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/gossip/infostore.go, line 387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0bW-gqYCyFsVxOFjv:-Kj0bW-gqYCyFsVxOFjw:b-easf5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/infostore.go#L387)):*
> ```Go
> 	if err := is.visitInfos(func(key string, i *Info) error {
> 		// Only consider NodeID keys here because they're re-gossiped every time a
> 		// node restarts and periodically after that, so their hops values are more
> ```

s/hops/Hops/ - "Hops" is a proper noun in this case.

---

*[pkg/gossip/infostore.go, line 388 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0bjUsGGBfT2kIFKjC:-Kj0bjUsGGBfT2kIFKjD:b-k6946f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/infostore.go#L388)):*
> that could have been around for a long

This phrasing is a bit vague, which can sometimes do more harm than good. How about "...than keys which are rarely re-gossiped, which can acquire unreliably high Hops values in some pathological cases such as those described in #9819." (i'd also not mention system config by name, but I feel less strongly about that).

---

*[pkg/gossip/keys.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0ag9NbjkU1hCZf2q2:-Kj0ag9OY6-rBV7JHL27:bgin4vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/keys.go#L99)):*
> ```Go
> }
> 
> // IsNodeIDKey returns true iff the provided key is a valid NodeIDKey.
> ```

nit: s/valid NodeIDKey/node ID key/ (NodeIDKey is not a type, or otherwise a proper noun, is it?)

---

*[pkg/storage/replica.go, line 4505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0a72eFtfhkD1qpQw0:-Kj0a72fByWWASrlJNGV:b13glqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/212ab1bb791a0007b3ab35098e7f3fd01843c8b8/pkg/storage/replica.go#L4505)):*
> ```Go
> func (r *Replica) maybeGossipSystemConfig(ctx context.Context) error {
> 	if r.store.Gossip() == nil || !r.IsInitialized() {
> 		log.VEventf(ctx, 2, "not gossiping system config due to uninitialized gossip or replica")
> ```

At the cost of a few extra lines of code we can log the exact reason here, which seems worth it to me. What do you think? Ditto below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-:-Kj0cYT5hwNE4U3EcuTq:b-r2hux4)*

**Comment by a-robinson** [comment]
> we could set inbound Infos' Hops to 0 when their node ID matches ours

We could, but now we don't rely on the Hops values of any infos other than the node descriptors, and we should never overwrite our locally generated info (with Hops=0) with an info passed to us from another node (that would imply that other nodes are either forging node descriptors or bumping timestamps, neither of which should be happening).

> and also iterate over our Infos whenever we connect to a new node and set Hops to 0 for all Infos with the new peer's node ID

Yeah, I don't know if that's really any better. Unrealistically low values make for fewer network tightening attempts, but they also could make for legitimately long gossip chains that don't get corrected.

> where blue 7 (still) does not have a gossip node ID key at all. Though perhaps something much worse is going on there.

Something worse (or at least different) has to be going on there. If a node's descriptor isn't in gossip, more bad things happen than incorrect  `mostDistant` calculations. If the descriptor isn't there, we won't even know what it's address is to try to connect to it.

> If we don't do any of the above, we should consider moving Hops to a narrower type than Info - otherwise it's a bit of a trap, I think.

I agree that the `Hops` logic is currently a trap. I don't think we should do much (if anything) more than this for 1.0, though.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/gossip/infostore.go, line 387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0bW-gqYCyFsVxOFjv:-Kj0kAqHOtNHWYzoF4GF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/infostore.go#L387)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/hops/Hops/ - "Hops" is a proper noun in this case.
</blockquote></details>

Done.

---

*[pkg/gossip/infostore.go, line 388 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0bjUsGGBfT2kIFKjC:-Kj0kJ7oNsqNnivgkB4a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/infostore.go#L388)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> that could have been around for a long

This phrasing is a bit vague, which can sometimes do more harm than good. How about "...than keys which are rarely re-gossiped, which can acquire unreliably high Hops values in some pathological cases such as those described in #9819." (i'd also not mention system config by name, but I feel less strongly about that).
</blockquote></details>

Done.

---

*[pkg/gossip/keys.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0ag9NbjkU1hCZf2q2:-Kj0koCWugSf6ULNJQGx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2065b4391bb2aaf51b9ae629634857c1fb69003c/pkg/gossip/keys.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: s/valid NodeIDKey/node ID key/ (NodeIDKey is not a type, or otherwise a proper noun, is it?)
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 4505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0a72eFtfhkD1qpQw0:-Kj0kyAATcmceBunjDtK:b-h987pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/212ab1bb791a0007b3ab35098e7f3fd01843c8b8/pkg/storage/replica.go#L4505)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

At the cost of a few extra lines of code we can log the exact reason here, which seems worth it to me. What do you think? Ditto below.
</blockquote></details>

Yeah, I agree. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-:-Kj0mVBlRCeYQOAgemvf:bktergr)*

**Comment by tamird** [comment]
> I agree that the Hops logic is currently a trap. I don't think we should do much (if anything) more than this for 1.0, though.

Agreed, though I don't think changes in this area would be destabilizing, only more work than we want to do in the 1.0 timeframe. Perhaps this would make for a good new contributor cleanup task.

---

Reviewed 6 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica.go, line 4518 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-Kj0o_75HdliqfcsIU7J:-Kj0o_76zvWahOZW5usT:bgqybsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/457a9993f8454b9b0cfbb81cbb55cfc19b32aa08/pkg/storage/replica.go#L4518)):*
> ```Go
> 	}
> 	if !r.shouldGossip() {
> 		log.VEventf(ctx, 2, "not gossiping system config because the replica doesn't hold the lease")
> ```

Heh, might be better to remove or rename `shouldGossip` given this its name is not descriptive enough to log here. Not asking you to change it, just observing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15533#-:-Kj0pZ5iXT-C5znW8BkD:bu9o2js)*

**Review by spencerkimball — APPROVED** [review]
Let's create an issue to replace `info.Hops` with `info.Nodes []roachpb.NodeID`, to exactly capture the string of nodes over which an info arrived at a destination. On new receipt of an info, a node would clean up the `info.Nodes` slice to remove cycles.

**Comment by a-robinson** [comment]
Opened #15539 to track further improvements.

**Pull request merged**
