### PR TITLE
sql: clean up hash joiner spec and processor implementations

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: remove deprecated field from hash joiner spec**

Long time ago, the hash joiner spec was created with the "number of
merged columns". The code since has been refactored to not use that
information, but the field was kept for backwards compatibility. Several
years have passed, and we can now safely remove that field and all the
corresponding code. Note that I don't think that we need to bump the
distsql version because it has been bumped multiple times for other
reasons since the time the field was used last.

Release note: None

**sql: clean up processor implementations**

This commit removes several unnecessary method overrides from the
processors (these embed `ProcessorBase`, so we leave the methods not
spelled out explicitly, the "inherited" version will be used which is
exactly what previous methods were doing). Additionally, it removes
redundant call to `GetTraceData` from the zigzag joiner because that
method will be called by the processor base as well (when transitioning
to draining). Also, it removes redundant call to `GetLeafTxnFinalState`
from the inverted filterer (the processor itself doesn't read data from
disk, so it doesn't have to report that txn state).

Release note: None

**rowexec: fix metadata propagation in zigzag joiner**

This commit refactors the zigzag joiner slightly to be more similar to
other processors. Most notable change is the removal of `producerMeta`
method and switching to returning an error and moving to draining
instead. In fact, previous behavior of metadata propagation was
incorrect in some cases when two or more metadata records needed to be
returned, and this is now fixed.

This commit also fixes an issue of zigzag joiner not propagating a leaf
txn final state metadata which could lead to a write skew. Additionally,
this commit adds low-level tests that verify that all reader-processors
output the leaf txn final state meta as well as trace meta.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping.

**Comment by yuzefovich** [comment]
Copying Andrei's guidance for testing the zigzag joiner fix here:
```
For tests, I guess a low-level one would assert that the zigzagjoiner produces this metadata when running in a leaf and a high-level one would actually check that a refresh fails:

set up some ranges such that laseholders are remote
start a txn
run a distributed join
in another txn, modify one of the rows that was read by the join
force the original txn to refresh:
in another txn, read some key
in the original txn attempt to write that key. This should "push" the txn
attempt to commit and expect a retriable error
```
I should extract the fix into a separate commit, add the tests, and backport them.

**Comment by yuzefovich** [comment]
This is RFAL. Note that the first commit is exactly the same as in #54808.

**Comment by yuzefovich** [comment]
I think I won't add a high level test that exposes a write skew due to zigzag joiner not propagating leaf txn final state metadata - in order for such scenario to occur - since the zigzag joins are not distributed - we need another processor to read the data as well (let's say a table reader), but also we'd need to make sure that the not all of the keys read by the zigzag joiner are read by the table reader because the latter does propagate leaf txn final state meta. Anyway, I don't think it's worth spending the time trying to come up with a particular reproduction, and the lower level tests should be sufficient.

That said, I'm not sure whether we want to backport the last commit from this PR - I believe it does fix a possible txn anomaly that has been present for a couple of years, but that anomaly can occur only in an edge case.

**Review by asubiotto — CHANGES_REQUESTED** [review]
I think a unit test for leaf txn metadata is sufficient if it's too difficult to add an integration test.

> Reviewed 10 of 10 files at r1, 10 of 10 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-:-MJWLl8HBhCqCmz596Dg:b-186p56)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/colbatch_scan_test.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWJ6rw9UKdbGSDVfgv:-MJWJ6rw9UKdbGSDVfgw:be9yn5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/colflow/colbatch_scan_test.go#L38)):*
> ```Go
> )
> 
> func TestColBatchScanMeta(t *testing.T) {
> ```

Could you add a short description of what this test does?
___
*[pkg/sql/rowexec/processors_test.go, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWKWnU3e0Bosy4TJ1G:-MJWKWnU3e0Bosy4TJ1H:b-92u03k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/processors_test.go#L1011)):*
> ```Go
> 				t.Fatalf("row was pushed unexpectedly")
> 			}
> 			if meta == nil {
> ```

It might be good to make this test stricter by expecting a certain number of metadata messages
___
*[pkg/sql/rowexec/tablereader_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWLfNh7cWCu4MzQCI7:-MJWLfNh7cWCu4MzQCI8:b2fanub) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/tablereader_test.go#L305)):*
> ```Go
> }
> 
> func TestTableReaderDrain(t *testing.T) {
> ```

Maybe also add `TestJoinReaderDrain`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/colbatch_scan_test.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWJ6rw9UKdbGSDVfgv:-MJYVi_44D0W3z7P-iY_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/colflow/colbatch_scan_test.go#L38)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you add a short description of what this test does?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_test.go, line 858 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJYY40c8t6PTGSCXhwq:-MJYY40c8t6PTGSCXhwr:bn8cvmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/joinreader_test.go#L858)):*
> ```Go
> 	// metadata coming from the producer is still read when ConsumerDone is
> 	// called on the consumer.
> 	t.Run("ConsumerDone", func(t *testing.T) {
> ```

Note that this test is somewhat redundant with the one in `testReaderProcessorDrain`, but here we push an error metadata. I thought we might as well keep both of them, WDYT?
___
*[pkg/sql/rowexec/processors_test.go, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWKWnU3e0Bosy4TJ1G:-MJYVnMy4vMdIFWijd3o:b9vyhia) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/processors_test.go#L1011)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might be good to make this test stricter by expecting a certain number of metadata messages
</blockquote></details>

I think that might be a bit too much - some processors might propagate more metadata than others (for example, about misplanned ranges).
___
*[pkg/sql/rowexec/tablereader_test.go, line 305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWLfNh7cWCu4MzQCI7:-MJYXtBB6DHUzR1J2L0g:b-lo79b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/tablereader_test.go#L305)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe also add `TestJoinReaderDrain`?
</blockquote></details>

There already exists `TestJoinReaderDrain` - I actually based all other tests on that one.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r4, 10 of 10 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/processors_test.go, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWKWnU3e0Bosy4TJ1G:-MJbAze86CiUei64cIL-:b-bbmb8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/processors_test.go#L1011)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think that might be a bit too much - some processors might propagate more metadata than others (for example, about misplanned ranges).
</blockquote></details>

How about an "expect at least x" check? I think it's easy for this test to silently pass if we don't return any metadata, right?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/processors_test.go, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWKWnU3e0Bosy4TJ1G:-MJbYcfqCcWT1fkUc6q1:bqsj563) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/processors_test.go#L1011)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How about an "expect at least x" check? I think it's easy for this test to silently pass if we don't return any metadata, right?
</blockquote></details>

This test will fail if no metadata is returned - we expect that trace meta and leaf txn final state meta are returned, or are you thinking about something else?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-:-MJbdusjEpSdHxDwzKpX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/processors_test.go, line 1011 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54377#-MJWKWnU3e0Bosy4TJ1G:-MJbdtHB7M8RdCL3b2Ow:b29eoub) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13eed96d68e9b19c42e85801005b1ae051a8d9b/pkg/sql/rowexec/processors_test.go#L1011)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This test will fail if no metadata is returned - we expect that trace meta and leaf txn final state meta are returned, or are you thinking about something else?
</blockquote></details>

I misread the code.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
