### PR TITLE
colexec: fix LIKE operators when patterns have escape characters

### LINKED ISSUE #68040: sql: vectorized escapes `LIKE '%\\%'` incorrectly
**Describe the problem**

`LIKE '%\\%'`

**To Reproduce**

This is a problem since v21.1, guessing since vectorize was on by default.

Setup:
```
 CREATE TABLE public.lookup_article (
      id SERIAL PRIMARY KEY,
      headline VARCHAR(100) NOT NULL,
      pub_date TIMESTAMPTZ NOT NULL,
      author_id INT8 NULL,
      slug VARCHAR(50) NULL
  );
  INSERT INTO "lookup_article" ("headline", "pub_date", "author_id", "slug") VALUES ('Article with \ backslash', '2005-11-22T00:00:00-06:00'::timestamptz, NULL, NULL) RETURNING "lookup_article"."id";
```

Now observe the difference in results when vectorized is off vs on:
```

demo@127.0.0.1:26257/defaultdb> set vectorize=off;
SET


Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT "lookup_article"."id", "lookup_article"."headline", "lookup_article"."pub_date", "lookup_article"."author_id", "lookup_article"."slug" FROM "lookup_article" WHERE "lookup_article"."headline" LIKE '%\\%';
          id         |         headline         |        pub_date        | author_id | slug
---------------------+--------------------------+------------------------+-----------+-------
  678626193848238081 | Article with \ backslash | 2005-11-22 06:00:00+00 |      NULL | NULL
(1 row)


Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> set vectorize=on;
SET


Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT "lookup_article"."id", "lookup_article"."headline", "lookup_article"."pub_date", "lookup_article"."author_id", "lookup_article"."slug" FROM "lookup_article" WHERE "lookup_article"."headline" LIKE '%\\%';
  id | headline | pub_date | author_id | slug
-----+----------+----------+-----------+-------
(0 rows)
```

The vectorize=off result is the expected result.

Found by https://github.com/cockroachdb/cockroach/issues/67974

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix LIKE operators when patterns have escape characters**

Fixes: #68040.

Release note (bug fix): Previously, CockroachDB could incorrectly
evaluate LIKE expressions when the pattern contained the escape
characters `\` if the expressions were executed via the vectorized
engine.

**colbuilder: force planning of optimized projection operators**

Whenever we're planning a projection expression, we have 3 cases: the
left is constant, the right is constants, and neither are constants. For
the second case we have some optimized operators. Previously, those
operators weren't exercised via the TestEval/vectorized because in the
eval tests the left side is constant. This commit switches the planning
to force planning of those optimized operators. This shouldn't really
have an effect on planning of actual queries.

This was prompted by the bug in LIKE operators that is fixed in the
previous commit. Had we forced the planning for our eval tests, we would
have caught it earlier.

This also revealed an incompatibility for our IN operator implementation when
the right side is an empty tuple which this commit also fixes. However,
I don't think this scenario can be hit in production because the
optimizer folds such an expression into correct `false`. Thus, there is
no release note.

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Nice! Good idea to fix up`TestEval/vectorized`. :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68289#-:-Mg7Wr0G1TNzFZnbGS6c:b-fxymrq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68289)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Comment by mgartner** [comment]
Should this be backported to 20.2 and 21.1?

**Comment by yuzefovich** [comment]
Yeah, I think we should backport to 20.2 and 21.1 but only the first commit (that's why I didn't put labels on the PR and will do the backport manually).

TFTR!

bors r+

**Comment by mgartner** [comment]
I wanted to point out that there are other unsolved problems with the `LIKE` operator. See #44123.

**Comment by yuzefovich** [comment]
#44123 is a different beast - there, the problem seems to be during constraint generation in the optimizer.

Seems like an unrelated flake.

bors r+

**Pull request merged**
