### PR TITLE
partialidx: fix implication logic for contradictions

### LINKED ISSUE #54649: roachtest: sqlsmith/setup=rand-tables/setting=no-mutations failed
[(roachtest).sqlsmith/setup=rand-tables/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2287957&tab=buildLog) on [master@75ccf016099aa089b0dfee9932398862e6bf7d5c](https://github.com/cockroachdb/cockroach/commits/75ccf016099aa089b0dfee9932398862e6bf7d5c):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	sqlsmith.go:172,sqlsmith.go:202,test_runner.go:755: error: pq: internal error: runtime error: index out of range [-1]
		stmt:
		SELECT
			tab_13211.col1_2 AS col_28184
		FROM
			defaultdb.public.table1@[0] AS tab_13211
		WHERE
			((NULL OR tab_13211.col1_1) OR tab_13211.col1_1)
		LIMIT
			12:::INT8;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=rand-tables/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2287957&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Drand-tables%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: build contridiction constraint for false

This commit builds a tight, contradiction constraint for a `FalseExpr`.
As a result, `SelectExpr` cardinality can be determined to be zero if
one of the filter constraints is a contradiction. This makes the
`DetectSelectContradiction` normalization rule obsolete, so it has been
removed. All of the cases it covered are now covered by
`SimplifyZeroCardinalityGroup`.

Note that `DetectSelectContradiction` was originally removed in #30312,
and re-added in #31173. It was re-added presumably by accident during
the large refactoring in the later PR.

Release note: None

#### partialidx: fix implication logic for contradictions

This commit fixes a panic when trying to prove implication of atoms that
are contradictions, like `false` and `NULL`. By adding logic to
specifically handle contradictions and return early, an out-of-bounds
exception is avoided later when trying to fetch the first constraint of
the contradiction, which does not exist.

A contradiction atom represents an empty set of rows. Because all sets
contain the empty set, a contradiction atom implies any other atom.
Likewise, because the empty set is the only set contained by the empty
set, a contradiction atom is only implied by another contradiction.

Fixes #54649 

Release justification: This is a critical bug fix for a new feature,
partial indexes.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
For the backport, I'll likely only include the second commit to minimize the changes to the release branch. I can add a special case in the Implicator to handle the `FalseExpr` correctly, because a contradiction won't be built for a `FalseExpr` without the first commit.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54718#-:-MHxV2BV8NHWDyCNFMnQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/partialidx/testdata/implicator/false-negative, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54718#-MHxUtkm51I10jcxQe89:-MHxUtkm51I10jcxQe8A:b-qoxgq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a18eac88ef0f989038a2df38b2812cc9d0e46e60/pkg/sql/opt/partialidx/testdata/implicator/false-negative#L55)):*
> ```
> # A true predicate means that the partial index indexes all rows. Therefore any
> # query filter implies a true predicate. There's no need to fix these false
> # negatives because scans over these "psuedo-partial indexes" are generated by
> ```

`pseudo` (saving you a look at TeamCity, this is the only failure)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54718)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/partialidx/testdata/implicator/false-negative, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54718#-MHxUtkm51I10jcxQe89:-MHxVm9xDR56pupyRAuV:blietsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a18eac88ef0f989038a2df38b2812cc9d0e46e60/pkg/sql/opt/partialidx/testdata/implicator/false-negative#L55)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`pseudo` (saving you a look at TeamCity, this is the only failure)
</blockquote></details>

Thank you :pray:  I can't count how many of my builds have failed for failing to spell this word correctly...

**Comment by mgartner** [comment]
bors r=RaduBerinde

**Pull request merged**
