### PR TITLE
cli: Add support for new gossip types to `debug gossip-values`

### PR DESCRIPTION
**Pull request by a-robinson**
Release note: None

Example output from a local 4 node cluster:

```
~/cockroach 0 $ ./cockroach debug gossip-values --insecure
"cluster-id": 986f14be-e7c0-4877-8198-9cc0ccbb054b
"distsql-draining:1": {Draining:false}
"distsql-draining:2": {Draining:false}
"distsql-draining:3": {Draining:false}
"distsql-draining:4": {Draining:false}
"distsql-version:1": {Version:21 MinAcceptedVersion:21}
"distsql-version:2": {Version:21 MinAcceptedVersion:21}
"distsql-version:3": {Version:21 MinAcceptedVersion:21}
"distsql-version:4": {Version:21 MinAcceptedVersion:21}
"first-range": r1:/{Min-System/} [(n1,s1):1, (n3,s4):2, (n4,s3):3, next=4, gen=0]
"gossip-clients:1": 3
"gossip-clients:2": 3,1,4
"gossip-clients:3": 4
"gossip-clients:4": 1
"liveness:1": {NodeID:1 Epoch:2 Expiration:1537554433.373651000,0 Draining:false Decommissioning:false}
"liveness:2": {NodeID:2 Epoch:2 Expiration:1537554433.373692000,0 Draining:false Decommissioning:false}
"liveness:3": {NodeID:3 Epoch:3 Expiration:1537554433.414544000,0 Draining:false Decommissioning:false}
"liveness:4": {NodeID:4 Epoch:2 Expiration:1537554433.374841000,0 Draining:false Decommissioning:false}
"node:1": {NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:26257} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554431161415000 LocalityAddress:[]}
"node:2": {NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:26261} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401350850000 LocalityAddress:[]}
"node:3": {NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:26259} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401350058000 LocalityAddress:[]}
"node:4": {NodeID:4 Address:{NetworkField:tcp AddressField:127.0.0.1:26263} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401356346000 LocalityAddress:[]}
"store:1": {StoreID:1 Attrs: Node:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:26257} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554431161415000 LocalityAddress:[]} Capacity:disk (capacity=234 GiB, available=48 GiB, used=191 KiB, logicalBytes=626 KiB), ranges=17, leases=3, queries=0.00, writes=0.00, bytesPerReplica={p10=0.00 p25=0.00 p50=35.00 p75=8410.00 p90=75775.00 pMax=477212.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00 pMax=0.00}}
"store:2": {StoreID:2 Attrs: Node:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:26261} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401350850000 LocalityAddress:[]} Capacity:disk (capacity=234 GiB, available=48 GiB, used=1.2 MiB, logicalBytes=449 KiB), ranges=15, leases=4, queries=1.28, writes=361.85, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=75654.00 pMax=383964.00}, writesPerReplica={p10=0.18 p25=0.18 p50=0.18 p75=0.18 p90=0.90 pMax=358.60}}
"store:3": {StoreID:3 Attrs: Node:{NodeID:4 Address:{NetworkField:tcp AddressField:127.0.0.1:26263} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401356346000 LocalityAddress:[]} Capacity:disk (capacity=234 GiB, available=48 GiB, used=704 KiB, logicalBytes=369 KiB), ranges=17, leases=5, queries=1.47, writes=220.83, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=5297.00 p90=60968.00 pMax=290716.00}, writesPerReplica={p10=0.20 p25=0.20 p50=0.20 p75=0.30 p90=14.48 pMax=198.47}}
"store:4": {StoreID:4 Attrs: Node:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:26259} Attrs: Locality:region=local,zone=local ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554401350058000 LocalityAddress:[]} Capacity:disk (capacity=234 GiB, available=48 GiB, used=349 KiB, logicalBytes=159 KiB), ranges=17, leases=2, queries=0.00, writes=0.00, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=5297.00 p90=60968.00 pMax=75604.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00 pMax=0.00}}
"system-db": omitted
```

Or a local 1 node cluster (to get a health alert):

```
"cluster-id": 81b45289-bf3e-43fa-aab3-c9af362c8c49
"distsql-draining:1": {Draining:false}
"distsql-version:1": {Version:21 MinAcceptedVersion:21}
"first-range": r1:/{Min-System/} [(n1,s1):1, next=2, gen=1]
"gossip-clients:1":
"health-alert:1": {Alerts:[{StoreID:1 Category:METRICS Description:queue.replicate.process.failure Value:46} {StoreID:1 Category:METRICS Description:ranges.underreplicated Value:34}]}
"liveness:1": {NodeID:1 Epoch:2 Expiration:1537554292.561462000,0 Draining:false Decommissioning:false}
"node:1": {NodeID:1 Address:{NetworkField:tcp AddressField:alex-laptop.local:26257} Attrs: Locality: ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554268008071000 LocalityAddress:[]}
"sentinel": 81b45289-bf3e-43fa-aab3-c9af362c8c49
"store:1": {StoreID:1 Attrs: Node:{NodeID:1 Address:{NetworkField:tcp AddressField:alex-laptop.local:26257} Attrs: Locality: ServerVersion:2.0-13 BuildTag:v2.2.0-alpha.00000000-996-g7d7edcad0a-dirty StartedAt:1537554268008071000 LocalityAddress:[]} Capacity:disk (capacity=234 GiB, available=48 GiB, used=1.6 MiB, logicalBytes=1.7 MiB), ranges=34, leases=18, queries=5.60, writes=56.03, bytesPerReplica={p10=0.00 p25=0.00 p50=3148.00 p75=137214.00 p90=138834.00 pMax=189573.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.20 p90=0.50 pMax=50.44}}
"system-db": omitted
```

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Perhaps we should add a unit test so that we can more easily discover when new gossip keys are added that are not covered by this code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-:-LMxit4ZEk7udroGzp7C:b-27r1dq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by a-robinson** [comment]
Added a test. Mind taking a quick look?

**Review by petermattis — APPROVED** [review]
Thanks for adding the test.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-:-LNGnWnmCUmWJ-bh_wcH:b-hx7j1l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/debug_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-LNGnHiE8xTfw3hQ0WL1:-LNGnHiE8xTfw3hQ0WL2:b4ih04v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2475db9ae008cb6d898695264e54511f60177114/pkg/cli/debug_test.go#L275)):*
> ```Go
> 	}
> 	debugLines := strings.Split(debugOutput, "\n")
> 	if len(debugLines) != len(gossipInfo.Infos) {
> ```

Couldn't this check pass even when the keys in `debugLines` differ from the keys in `gossipInfo.Infos`? Seems more robust to construct `gossipInfoKeys` first and to compare using `reflect.DeepEqual`.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30516)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/debug_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-LNGnHiE8xTfw3hQ0WL1:-LNGoKFF5mOURjuKNUsl:bedfrrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2475db9ae008cb6d898695264e54511f60177114/pkg/cli/debug_test.go#L275)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Couldn't this check pass even when the keys in `debugLines` differ from the keys in `gossipInfo.Infos`? Seems more robust to construct `gossipInfoKeys` first and to compare using `reflect.DeepEqual`.
</blockquote></details>

I suppose, although it'd take quite a behavior change for `parseGossipValues` to start creating new keys out of thin air. And it requires some pretty ugly parsing to get the keys out of `debugLines` in order to compare them against `gossipInfoKeys`, especially since you can't just split on ":" given that many gossip keys legitimately contain ":".

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30516)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/debug_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-LNGnHiE8xTfw3hQ0WL1:-LNGqZ0e9xnN1BH2hbJv:b-8oe4si) ([raw file](https://github.com/cockroachdb/cockroach/blob/2475db9ae008cb6d898695264e54511f60177114/pkg/cli/debug_test.go#L275)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I suppose, although it'd take quite a behavior change for `parseGossipValues` to start creating new keys out of thin air. And it requires some pretty ugly parsing to get the keys out of `debugLines` in order to compare them against `gossipInfoKeys`, especially since you can't just split on ":" given that many gossip keys legitimately contain ":".
</blockquote></details>

Hmm, I didn't see that difficulty. I suppose you can loop over `gossipInfo.Infos` and check to see if each key is a prefix of `debugLines`. That seems more hassle than its worth. Carry on.

**Review by a-robinson — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-:-LNGrNcj7bT9UlZ4jf6o:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/debug_test.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30516#-LNGnHiE8xTfw3hQ0WL1:-LNGrC8oApEdY5moiFwF:b-hgwyg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2475db9ae008cb6d898695264e54511f60177114/pkg/cli/debug_test.go#L275)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Hmm, I didn't see that difficulty. I suppose you can loop over `gossipInfo.Infos` and check to see if each key is a prefix of `debugLines`. That seems more hassle than its worth. Carry on.
</blockquote></details>

It could certainly be done, e.g. by refactoring `parseGossipValues` to return something more structured, but I think this pretty safely accomplishes the goal of not leaving out newly added gossip types.

**Pull request merged**
