### PR TITLE
sql: remove allowAdding resolver option

### PR DESCRIPTION
**Pull request by vivekmenezes**
allowAdding is always set to the same value
as skipCache. If such a policy is needed to
be enforced it can be enforced at a higher level.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Thanks for this cleanup. I find the code much more readable as a result.

I think the first commit is not correct without the 2nd one. Have you tried to run the test suite on each individual commit in the PR? If not, I would recommend squashing the first and 2nd commit together.

Meanwhile I am not 100% sure about the 3rd commit. Does this mean the virtual tables now show descriptors in the process of being added but not yet public? We want this behavior for `crdb_internal.tables`, for sure (SHOW CREATE depends on it), but I am not convinced this is desirable for the `pg_catalog` tables. I would like to check with @jordanlewis whether we'd be happy with the new behavior.

---

Reviewed 22 of 22 files at r1, 6 of 7 files at r2, 3 of 3 files at r3.
Review status: 30 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-:-LCKBKKD-jfEcjR1H_7N:bq5et3g)*

**Comment by vivekmenezes** [comment]
Thanks for taking a look. My next step after this is merged is to split the API into two and eliminate the need for the last resolver flag: avoidCached. And once that's done, I'll create a new type for the cached table descriptor and its API.

Regarding commit and 1 and 2, they stand on their own but I can squash them if you'd like.

Regarding 3, the ADD state for a descriptor only applies to DML statements preventing them from using the
descriptor; all DDL statements can access and modify a descriptor in the ADD state. If there are some additional requirements I'm happy to add a test to reflect them. Thanks!

---

Review status: 30 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-:-LCKc9Xd3rn7scAB-P0R:b466a3h)*

**Comment by knz** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCKePDmBLhWSiNG_NiI:b-xl9at7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
> ```Go
> 	fn func(*sqlbase.DatabaseDescriptor, string, *sqlbase.TableDescriptor, tableLookupFn) error,
> ) error {
> 	return forEachTableDescWithTableLookupInternal(ctx, p, prefix, virtualOpts, false /* allowAdding */, fn)
> ```

By removing the `allowAdding` parameter here, you have effectively changed the (logical) value of the parameter from `false` to `true`.

This implies that now every virtual table generator that uses `forEachTableDescWithTableLookup` (a bunch in `information_schema` plus a couple in `pg_catalog`), now the virtual table will show non-public tables in the adding state, whereas previously they would be hidden.

Was this intentional?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCKfl7KEJTD0EduEn2t:b11stre) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

By removing the `allowAdding` parameter here, you have effectively changed the (logical) value of the parameter from `false` to `true`.

This implies that now every virtual table generator that uses `forEachTableDescWithTableLookup` (a bunch in `information_schema` plus a couple in `pg_catalog`), now the virtual table will show non-public tables in the adding state, whereas previously they would be hidden.

Was this intentional?


</blockquote></details>

Yes that's intentional. I wouldn't claim that I fully understand the requirements for the information_schema and pg_catalog but I suppose given what the ADD state means (affects only DML statements) I wonder if we care? Certainly doesn't see like we do.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCKh89R5GbspZaO7vLn:b-2bd42e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Yes that's intentional. I wouldn't claim that I fully understand the requirements for the information_schema and pg_catalog but I suppose given what the ADD state means (affects only DML statements) I wonder if we care? Certainly doesn't see like we do.
</blockquote></details>

Our test suite does not fully explore this area but I know for sure that ORM clients do care about this. That's why I'd like @jordanlewis or @nvanbenschoten to chime in and state what they think about this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by knz** [comment]
(Disclaimer: I admit that I myself do not fully understand the consequences. When I say "ORMs do care" I mean that they are the main consumers of the data in `pg_catalog` and `information_schema`. But I do not know yet to which extent they will be inconvenienced by making non-public tables visible.)

**Comment by knz** [comment]
Oh also I think this change means that `SHOW TABLES` now show non-public tables too. That's new and thus needs to be called out in the release notes.

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCZFvgR3ymWWBIETDy3:by6cw17) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Our test suite does not fully explore this area but I know for sure that ORM clients do care about this. That's why I'd like @jordanlewis or @nvanbenschoten to chime in and state what they think about this.
</blockquote></details>

@knz you introduced the "false" flag to not include ADD descriptors in this PR: https://github.com/cockroachdb/cockroach/pull/16938

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCZIOCk96yMk2SKG8qW:b-y8sbn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

@knz you introduced the "false" flag to not include ADD descriptors in this PR: https://github.com/cockroachdb/cockroach/pull/16938
</blockquote></details>

That PR changed the various SHOW statement so that they would not any more manually read the descriptors (using an API which avoided ADD descriptors automatically) and instead do their work by a delegated SQL query virtual tables (ensuring that the vtables would avoid ADD descriptors too). 

So the set of visible tables didn't change on that PR, unless I am mistaken?

Whereas it does on this PR (I think).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCdylOy8mRTjhYAENxi:bnwp8dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That PR changed the various SHOW statement so that they would not any more manually read the descriptors (using an API which avoided ADD descriptors automatically) and instead do their work by a delegated SQL query virtual tables (ensuring that the vtables would avoid ADD descriptors too). 

So the set of visible tables didn't change on that PR, unless I am mistaken?

Whereas it does on this PR (I think).
</blockquote></details>

At the very least, this change makes `forEachTableDesc` and `forEachTableDescAll` identical, so that needs to be cleaned up.

More than that, I don't think this is going in the right direction. `forEachTableDescAll` is only used by `crdb_internal`, while `forEachTableDesc` is used by `information_schema` and `pg_catalog`. Why are we changing `information_schema` and `pg_catalog` to show tables in the ADD state?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LChZzdVC3F3SB67EgU1:bj37r2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
> Why are we changing information_schema and pg_catalog to show tables in the ADD state?

So this is the very question I was asking initially. I don't think this PR initially *intended* to do this change, however please consider this: what this effectively does is making the tables visible to introspection.

There are two places where they would become visible, one which I am comfortable with:

1. within the same transaction where a table is created. In that case, arguably the new situation is better. What do you think?

2. within non-related other transactions, where "tables in the process of being added but still unusable" would become visible. This makes me iffy. Nathan do you envision situation where client code could become confused as a result?

I would be much more comfortable if we had a way to only show tables in the ADD state if they were added in the same transaction. @vivekmenezes what do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/information_schema.go, line 1150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25425#-LCKePDmBLhWSiNG_NiH:-LCiyI8F-JHUNJKjp26-:b-mzxztm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d76680f7d2814a8354966b7384d75d10fc968b65/pkg/sql/information_schema.go#L1150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> Why are we changing information_schema and pg_catalog to show tables in the ADD state?

So this is the very question I was asking initially. I don't think this PR initially *intended* to do this change, however please consider this: what this effectively does is making the tables visible to introspection.

There are two places where they would become visible, one which I am comfortable with:

1. within the same transaction where a table is created. In that case, arguably the new situation is better. What do you think?

2. within non-related other transactions, where "tables in the process of being added but still unusable" would become visible. This makes me iffy. Nathan do you envision situation where client code could become confused as a result?

I would be much more comfortable if we had a way to only show tables in the ADD state if they were added in the same transaction. @vivekmenezes what do you think?
</blockquote></details>

I'm realizing that I don't fully understand what it even means for a table descriptor to be in the ADD state. For the two cases you mentioned though, I can share my opinion:
1. A table should only be visible in the transaction that created it iff it's fully usable. It should be writable and readable.
2. A table should absolutely not be visible in these introspection schemas from other transactions if it's not yet usable.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25425)*

**Comment by vivekmenezes** [comment]
Removed last commit. PTAL

**Pull request merged**
