### PR TITLE
build: hook up Pebble nightly benchmark data pipeline

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@jbowens No need to review this yet, I need to perform some manual runs on TeamCity to make sure everything is working.

**Review by petermattis — COMMENTED** [review]
This is ready for a look. I did a run which successfully uploaded the raw data. Unfortunately, it didn't update `data.js` because of the symlink structure. That should be fixed by https://github.com/cockroachdb/pebble/pull/804.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51070#-:-MBfkets3_SN2taax13u:buwsr68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[build/teamcity-nightly-pebble.sh, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51070#-MBflg0GBK7CGA6sLBCM:-MBflg0GBK7CGA6sLBCN:bnrj7y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/09e7b27df89166b9fa860ccd20930e501b834534/build/teamcity-nightly-pebble.sh#L66)):*
> ```Shell
> # mkbench expects the benchmark data to be stored in data/YYYYMMDD.
> mkdir data
> ln -sf $PWD/artifacts data/$(date +"%Y%m%d")
> ```

I could move the artifacts directory rather than symlinking, but my understanding is that doing so prohibits it from being picked up by TeamCity. Not sure if that is important or not.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51070#-:-MBivHwK0A9A5H7Ac3wv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by petermattis** [comment]
TFTR!

bors r+

**Pull request merged**
