### PR TITLE
sql: allow point lookups on secondary indexes with 0 stored columns

### LINKED ISSUE #72735: sql: GetRequest not used when querying secondary index without stored columns
In https://github.com/cockroachdb/cockroach/pull/61583, @jordanlewis landed a major improvement to perform point KV `GetRequests` over ranged KV `ScanRequests` in some cases. This came with a number of benefits, which were listed in the PR description.

While looking at TPC-E, I've seen traces that indicate that this optimization has had a very positive impact. However, I've also noticed a few cases where point lookups should be used when querying secondary indexes, but aren't being used. In these cases, we're resorting to `Scan` requests instead of `Get` requests.

I believe I've narrowed this down to some logic in `span.Builder.CanSplitSpanIntoFamilySpans`, which may be too restrictive:
https://github.com/cockroachdb/cockroach/blob/13669f9c9bd92a4c3b0378a558d7735f122c4e72/pkg/sql/span/span_builder.go#L269-L290

Specifically, I think there's something off with this `NumSecondaryStoredColumns` check. I don't understand why it's needed, and it seems to break cases where a unique secondary index that does not store any columns is being queried to retrieve the primary key column(s).

Here's a reproduction:
```sql
./cockroach demo --empty

CREATE TABLE kv (
	k INT PRIMARY KEY,
	v INT NOT NULL,
	v2 INT NOT NULL,
	UNIQUE INDEX idx1 (v),
	UNIQUE INDEX idx2 (v) STORING (v2)
);

SET tracing = on; SELECT k FROM kv@idx1 WHERE v = 10; SET tracing = off; SHOW kv TRACE FOR session;

            timestamp           |       age       |                message                 |                             tag                             |                location                 |    operation     | span
--------------------------------+-----------------+----------------------------------------+-------------------------------------------------------------+-----------------------------------------+------------------+-------
  2021-11-14 21:52:15.674302+00 | 00:00:00.004366 | Scan /Table/52/2/1{0-1}                | [n=1,client=127.0.0.1:49475,hostssl,user=demo]              | sql/row/kv_batch_fetcher.go:441         | colbatchscan     |    7
  2021-11-14 21:52:15.6774+00   | 00:00:00.007464 | querying next range at /Table/52/2/10  | [n=1,client=127.0.0.1:49475,hostssl,user=demo,txn=ac105482] | kv/kvclient/kvcoord/range_iter.go:175   | dist sender send |    9
  2021-11-14 21:52:15.678542+00 | 00:00:00.008606 | r44: sending batch 1 Scan to (n1,s1):1 | [n=1,client=127.0.0.1:49475,hostssl,user=demo,txn=ac105482] | kv/kvclient/kvcoord/dist_sender.go:1938 | dist sender send |    9
  2021-11-14 21:52:15.683729+00 | 00:00:00.013793 | rows affected: 0                       | [n=1,client=127.0.0.1:49475,hostssl,user=demo]              | sql/conn_executor_exec.go:709           | exec stmt        |    3

SET tracing = on; SELECT k FROM kv@idx2 WHERE v = 10; SET tracing = off; SHOW kv TRACE FOR session;

            timestamp           |       age       |                 message                 |                             tag                             |                location                 |    operation     | span
--------------------------------+-----------------+-----------------------------------------+-------------------------------------------------------------+-----------------------------------------+------------------+-------
  2021-11-14 21:52:16.857978+00 | 00:00:00.004353 | Scan /Table/52/3/10/0                   | [n=1,client=127.0.0.1:49475,hostssl,user=demo]              | sql/row/kv_batch_fetcher.go:441         | colbatchscan     |    7
  2021-11-14 21:52:16.858828+00 | 00:00:00.005203 | querying next range at /Table/52/3/10/0 | [n=1,client=127.0.0.1:49475,hostssl,user=demo,txn=cab3dead] | kv/kvclient/kvcoord/range_iter.go:175   | dist sender send |    9
  2021-11-14 21:52:16.859335+00 | 00:00:00.00571  | r44: sending batch 1 Get to (n1,s1):1   | [n=1,client=127.0.0.1:49475,hostssl,user=demo,txn=cab3dead] | kv/kvclient/kvcoord/dist_sender.go:1938 | dist sender send |    9
  2021-11-14 21:52:16.866307+00 | 00:00:00.012682 | rows affected: 0                        | [n=1,client=127.0.0.1:49475,hostssl,user=demo]              | sql/conn_executor_exec.go:709           | exec stmt        |    3
```

### PR DESCRIPTION
**Pull request by cucaroach**
Remove an unnecessary check that was preventing point lookups in some
TPCE queries.

Fixes #72735

Release note: None

### CODE REVIEW

**Comment by cucaroach** [comment]
This is lightly tested, any good roachtests or nightly tests that might be good to run?

**Comment by jordanlewis** [comment]
I think we need to write some more execbuilder and accompanying logic tests for this that exercise more types of secondary indexes with more variety, to make sure that we're not missing any reasons why this was avoided in the first place.

**Comment by cucaroach** [comment]
Here's a list of call hierachies leading into CanSplitCanIntoFamilySpans in case this jogs anyone's brains on where dragons might be lurking with 0-stored column indexes.   I really don't understand how having stored columns would affect this so I'm having trouble imaging where the dragons could be hiding.

```
- Builder.CanSplitSpanIntoFamilySpans in github.com/cockroachdb/cockroach/pkg/sql/span/span_builder.go
   - Builder.MaybeSplitSpanIntoSeparateFamilies in github.com/cockroachdb/cockroach/pkg/sql/span/span_builder.go
    - multiSpanGenerator.generateSpans in github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader_span_generator.go
      - localityOptimizedSpanGenerator.generateSpans in github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader_span_generator.go
      - localityOptimizedSpanGenerator.generateRemoteSpans in github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader_span_generator.go
      - defaultSpanGenerator.generateSpans (2 usages) in github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader_span_generator.go
 - FKCheckSpan in github.com/cockroachdb/cockroach/pkg/sql/row/fk_spans.go
   - Builder.appendSpansFromConstraintSpan in github.com/cockroachdb/cockroach/pkg/sql/span/span_builder.go
     - Builder.SpansFromConstraint (2 usages) in github.com/cockroachdb/cockroach/pkg/sql/span/span_builder.go
        - Builder.UnconstrainedSpans in github.com/cockroachdb/cockroach/pkg/sql/span/span_builder.go
          - DistSQLPlanner.createStatsPlan in github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go
          - physicalCheckOperation.Start in github.com/cockroachdb/cockroach/pkg/sql/scrub_physical.go
        - execFactory.ConstructDeleteRange in github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go
        - distSQLSpecExecFactory.ConstructScan in github.com/cockroachdb/cockroach/pkg/sql/distsql_spec_exec_factory.go
        - generateScanSpans in github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go
          - execFactory.ConstructScan in github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go
          - func(cat.Table, cat.Index, exec.ScanParams) string in github.com/cockroachdb/cockroach/pkg/sql/explain_plan.go
```

**Comment by jordanlewis** [comment]
On the insert side, here is the mirror logic:

https://github.com/cockroachdb/cockroach/blob/55bb02f999679f200ed962b05c934e7974d2d4f4/pkg/sql/rowenc/index_encoding.go#L1096-L1101

It means that, if there's a secondary index with column families, and a particular column family contains no columns that are stored, we don't write a key.

This means that if someone is expecting to be able to look up row existence using a particular secondary index, they are not allowed to use that column family at all, since an entry won't exist.

In general, we still have to be careful - if someone asks the general `CanSplitSpanIntoFamilySpans` method whether it is allowed to split up a secondary index span like this, we need to know a decent amount about the context in which it's called.

The `SplitRowKeyIntoFamilySpans` method is what actually takes in the listed column families and produces output spans. It would be illegal if, for some reason, someone called that method on a secondary index span with a needed column family that contained 0 stored columns - we'd unexpectedly have a span that would never return any data, despite the fact that the larger span could return data sometimes.

I think one way to move forward here would be to try to understand which needed column families are passed to `SplitRowKeyIntoFamilySpans` in the case of secondary index lookups, and whether it's possible to get one of these situations.

Another way to move forward would be to send more information to `CanSplitSpanIntoFamilySpans` - instead of just sending the number of needed column families, we could send the full set of needed column families. Then, inside of the check, we could make sure that in the case where it's a secondary index, all of the needed column families actually do have stored columns inside, just as we do on the insert side.

**Comment by cucaroach** [comment]
> Another way to move forward would be to send more information to CanSplitSpanIntoFamilySpans - instead of just sending the number of needed column families, we could send the full set of needed column families. Then, inside of the check, we could make sure that in the case where it's a secondary index, all of the needed column families actually do have stored columns inside, just as we do on the insert side.

This seems attractive and the columns families needed is generally available but I don't understand exactly what we would be checking.    The column families is produced by generating the minimum families needed to cover the columns needed (which should be a subset of the columns in the index).   Are we just talking about double checking that math and making sure that every column in the index is indeed covered by one of the families in needed families?   The only way the Builder.neededFamilies gets set is via SetNeededColumns which does this:


```
	s.neededFamilies = rowenc.NeededColumnFamilyIDs(neededCols, s.table, s.index)
```

So unless neededCols somehow includes columns not in the index I don't see how we could get into trouble but I feel like I must be missing something.

**Review by yuzefovich — COMMENTED** [review]
I think it is safe to remove `s.index.NumSecondaryStoredColumns() == 0` check for the secondary indexes without adding any extra checking. My reasoning is that if a secondary index supports column families and does not store any columns, then it will only have a single key-value pair, so it'll be safe to use the GetRequests to fetch from such index.

I agree with Rohan that it seems like this condition was added with a particular use case in mind (can we take an arbitrary key-span and then split it into _multiple_ column-family-specific key-spans?), and for that use case for secondary indexes with no stored columns we would get a _single_ key-span.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-:-Mp7ritP1punPuSzeUFK:b-vkt60a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @jordanlewis)

___
*[pkg/sql/span_builder_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-Mp7u6FF5olB7BkY-Z_v:-Mp7u6FF5olB7BkY-Z_w:b-v6d36w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87f03de796f4cf3bc48bac2c3d2b8b0aec26754/pkg/sql/span_builder_test.go#L41)):*
> ```Go
> 	execCfg := s.ExecutorConfig().(ExecutorConfig)
> 	evalCtx := tree.NewTestingEvalContext(s.ClusterSettings())
> 	tcs := []struct {
> ```

Probably worth adding a couple of test cases for secondary unique indexes with/without stored columns and different `containsNull` argument.

**Review by cucaroach — COMMENTED** [review]
Yeah, my confusion cleared up a bit when I discovered this in the docs: "Secondary indexes respect the column family definitions applied to tables. When you define a secondary index, CockroachDB breaks the secondary index key-value pairs into column families, according to the family and stored column configurations."   I didn't realize column families were applied to secondary indexes like that.   

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-:-Mp8MT_7-kzaT2tEcdtd:b-fb1zl5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/span_builder_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-Mp7u6FF5olB7BkY-Z_v:-Mp8MzsoCsF_WC0llWjl:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87f03de796f4cf3bc48bac2c3d2b8b0aec26754/pkg/sql/span_builder_test.go#L41)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Probably worth adding a couple of test cases for secondary unique indexes with/without stored columns and different `containsNull` argument.
</blockquote></details>

:+1:

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @jordanlewis)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-Mp8poUb5HU4zzO0dsAr):*
nit: I think this commit "fixes" that issue.
___
*[pkg/sql/span/span_builder.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-Mp8q2wz2Gn2KsABhCzN:-Mp8q2wz2Gn2KsABhCzO:bt3t9sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/29e513eb85ed39d29a42c93ece28735b4158a1ae/pkg/sql/span/span_builder.go#L217)):*
> ```Go
> // needed families can be safely split into 1 or more family specific spans.
> func (s *Builder) CanSplitSpanIntoFamilySpans(
> 	neededFamilies []descpb.FamilyID, prefixLen int, containsNull bool,
> ```

Since we're not doing any additional checks with `neededFamilies`, I'd restore the original `numNeededFamilies` here.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

nit: don't forget to update the PR description.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72794#-:-Mp9K6MJ2ZF7vKHa9Ru_:bv4r28q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by cucaroach** [comment]
blathers backport release-21.2

**Comment by yuzefovich** [comment]
Tommy, what's your thinking for backporting this? It seems like a performance optimization only, and we tend to not backport such things (unlike #73272 which fixes a bug present on 21.2 branch).

**Comment by cucaroach** [comment]
I was thinking the TPCE audit would be done on a released 21.2 branch and that we needed to backport for that?  @nvanbenschoten  should I backport this to 21.2?   I also have a slack out to @jordanlewis asking for his thoughts.

**Comment by yuzefovich** [comment]
The TPCE audit will run using the master branch at the time of the audit.

**Comment by cucaroach** [comment]
Okay removing backport label

**Pull request merged**
