### PR TITLE
sql: replace `walkPlan` with `Input` and `InputCount`

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: remove planDataSource field in renderNode

The `planDataSource` field of `renderNode` had a `columns` sub-field
that was only set some of the time, causing confusion with the
`renderNode`'s `columns` field. `planDataSource` has been replaced with
`planNode` to avoid confusion and misuse.

Release note: None

#### sql: remove planDataSource field in applyJoinNode

The `planDataSource` field of `applyJoinNode` had a `columns` sub-field
that was redundant with the `applyJoinNode`'s `columns` field.
`planDataSource` has been replaced with `planNode` to avoid confusion
and misuse.

Release note: None

#### sql: remove planDataSource field in filterNode

The `planDataSource` field of `filterNode` has been replaced by a
`planNode` and `columns` field.

Release note: None

#### sql: replace planDataSource fields in joinNode

The `planDataSource` fields of `joinNode` have been replaced by
`planNode` fields.

Release note: None

#### sql: remove planDataSource

The `planDataSource` struct is no longer needed. It has been removed.

Release note: None

#### sql: add Input and InputCount to planNode interface

Two methods have been added to the `planNode` interface that can be used
for traversing a `planNode` tree: `Input` and `InputCount`. The
`zeroInputPlanNode` and `singleInputPlanNode` structs are provided to
avoid boilerplate code for the two most common types of plan nodes.

The `Input` and `InputCount` methods allow for more flexibility in
traversing the tree than the `planVisitor` pattern. With the visitor
pattern general information can only be passed back to callsites by
capturing local variables in visitor closures, which can incur
incidental heap allocations. With `Input` and `InputCount`, callers can
define custom recursive functions that pass information back to
callsites by returning them.

These methods are not yet used, but will be in future commits.

Release note: None

#### sql: new traversal method of planNodes in wrapPlan

`wrapPlan` now traverses the `planNode` tree with a recursive function
that uses the `Input` and `InputCount` methods instead of the
`planVisitor`. This reduces the overhead of traversal.

Below are some benchmarks that show the improvement.

```
name                                        old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple-16        213µs ± 1%     205µs ± 1%  -4.02%  (p=0.000 n=20+20)
EndToEnd/kv-read/vectorize=off/Simple-16       207µs ± 1%     199µs ± 1%  -3.85%  (p=0.000 n=19+20)
EndToEnd/kv-read/vectorize=on/Prepared-16      146µs ± 1%     141µs ± 1%  -2.98%  (p=0.000 n=19+19)
EndToEnd/kv-read/vectorize=off/Prepared-16     140µs ± 1%     136µs ± 1%  -2.94%  (p=0.000 n=20+18)

name                                        old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Prepared-16     20.7kB ± 0%    20.6kB ± 0%  -0.23%  (p=0.000 n=19+19)
EndToEnd/kv-read/vectorize=on/Simple-16       33.4kB ± 0%    33.4kB ± 0%    ~     (p=0.670 n=19+19)
EndToEnd/kv-read/vectorize=off/Simple-16      33.8kB ± 0%    33.7kB ± 0%    ~     (p=0.760 n=18+18)
EndToEnd/kv-read/vectorize=off/Prepared-16    21.9kB ± 0%    21.9kB ± 0%    ~     (p=0.365 n=18+20)

name                                        old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple-16          283 ± 0%       282 ± 0%    ~     (p=0.105 n=20+20)
EndToEnd/kv-read/vectorize=on/Prepared-16        190 ± 0%       189 ± 0%    ~     (p=0.150 n=19+20)
EndToEnd/kv-read/vectorize=off/Simple-16         270 ± 0%       270 ± 0%    ~     (all equal)
EndToEnd/kv-read/vectorize=off/Prepared-16       182 ± 0%       182 ± 0%    ~     (p=0.447 n=18+20)
```

Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Nice improvement! The approach makes sense to me, so I'm in favor of polishing it up.

One suggestion for implementation I have is to define a couple of helper structs that will implement the new methods and will be embedded into `planNode` implementations (`zeroInputPlanNodeHelper`, `oneInputPlanNodeHelper`, etc). This will require a bit of unification how `planNode`'s inputs are called (`input` or `source` or something else), but unification is always nice :)

**Comment by mgartner** [comment]
> This will require a bit of unification how planNode's inputs are called (input or source or something else)

Ha... You're really gonna make me work for this one. ;) But I do agree, that's a good idea.

**Comment by mgartner** [comment]
The reduction in allocations I originally measured was some sort of fluke. I no longer measure that same reduction on the original prototype nor this polished-up version. However, I do measure a consistent speedup in EndToEnd benchmarks. I got a similar result across three separate 20-count runs:

```
name                                        old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple-16        213µs ± 1%     205µs ± 1%  -4.02%  (p=0.000 n=20+20)
EndToEnd/kv-read/vectorize=off/Simple-16       207µs ± 1%     199µs ± 1%  -3.85%  (p=0.000 n=19+20)
EndToEnd/kv-read/vectorize=on/Prepared-16      146µs ± 1%     141µs ± 1%  -2.98%  (p=0.000 n=19+19)
EndToEnd/kv-read/vectorize=off/Prepared-16     140µs ± 1%     136µs ± 1%  -2.94%  (p=0.000 n=20+18)

name                                        old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Prepared-16     20.7kB ± 0%    20.6kB ± 0%  -0.23%  (p=0.000 n=19+19)
EndToEnd/kv-read/vectorize=on/Simple-16       33.4kB ± 0%    33.4kB ± 0%    ~     (p=0.670 n=19+19)
EndToEnd/kv-read/vectorize=off/Simple-16      33.8kB ± 0%    33.7kB ± 0%    ~     (p=0.760 n=18+18)
EndToEnd/kv-read/vectorize=off/Prepared-16    21.9kB ± 0%    21.9kB ± 0%    ~     (p=0.365 n=18+20)

name                                        old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple-16          283 ± 0%       282 ± 0%    ~     (p=0.105 n=20+20)
EndToEnd/kv-read/vectorize=on/Prepared-16        190 ± 0%       189 ± 0%    ~     (p=0.150 n=19+20)
EndToEnd/kv-read/vectorize=off/Simple-16         270 ± 0%       270 ± 0%    ~     (all equal)
EndToEnd/kv-read/vectorize=off/Prepared-16       182 ± 0%       182 ± 0%    ~     (p=0.447 n=18+20)
```

I think this is likely due to eliminating some of the overhead of the visitor.

**Review by yuzefovich — APPROVED** [review]
Nice improvement! :lgtm:

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, 4 of 4 files at r4, 3 of 3 files at r5, 136 of 136 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-:-OERS26m0YHuGchGKJ9Z:bhrr95v)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERS7LaAMIRBmBFSjwJ:-OERS7LaAMIRBmBFSjwK:b-ktpzl4):*
nit: consider updating the last commit title / message with the recent benchmark findings.
___
*[`pkg/sql/schema_change_plan_node.go` line 216 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERQnzr9zqUUzYGn5G4:-OERQnzr9zqUUzYGn5G5:biigsp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84c1127556d1683ec590415a0fbd2d49f667fe0/pkg/sql/schema_change_plan_node.go#L216)):*
> ```Go
> 	// the nodes that existed preceding the current statement with the output of
> 	// the built current statement. There maybe cases like CTE's, where we will
> 	// need to re-input if the lastState and the plannedState do not match, since
> ```

nit: "re-plan" makes more sense :smiley: 
___
*[`pkg/sql/distsql_physical_planner.go` line 4171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERRYh00LPHNjQElzBx:-OERRYh00LPHNjQElzBy:b-9p7514) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84c1127556d1683ec590415a0fbd2d49f667fe0/pkg/sql/distsql_physical_planner.go#L4171)):*
> ```Go
> 			}
> 			var err error
> 			// Continue walking until we find a node that has a DistSQL
> ```

nit: I'd preserve this comment, seems useful for context.

**Review by mgartner — COMMENTED** [review]
The linting failure should be resolved once #137739 is merged.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-:-OES559gDPEIn2TuZ5AA:b-g50qfh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`-- commits` line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERS7LaAMIRBmBFSjwJ:-OES6gSn1MqVRMj4SLdA:b-896fix):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: consider updating the last commit title / message with the recent benchmark findings.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_physical_planner.go` line 4171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERRYh00LPHNjQElzBx:-OES5pGE8NG24b2V7q4i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84c1127556d1683ec590415a0fbd2d49f667fe0/pkg/sql/distsql_physical_planner.go#L4171)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd preserve this comment, seems useful for context.
</blockquote></details>

Done.
___
*[`pkg/sql/schema_change_plan_node.go` line 216 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OERQnzr9zqUUzYGn5G4:-OES6cwb8UB128SVGnsx:bw10jn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d84c1127556d1683ec590415a0fbd2d49f667fe0/pkg/sql/schema_change_plan_node.go#L216)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: "re-plan" makes more sense :smiley:
</blockquote></details>

Oops, done.
___
*[`pkg/sql/distsql_physical_planner.go` line 4178 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OES5FppApHBbeGk8jRO:-OES5FppApHBbeGk8jRP:b-r1m7vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3e42811e17d6080261388d2af98c280d4b423e/pkg/sql/distsql_physical_planner.go#L4178)):*
> ```Go
> 			return planFirstDistSQLNode(input)
> 		default:
> 			// Can't wrap plans with more than 1 input.
> ```

@yuzefovich is this true? Or are there cases where we might wrap one side of a join or set op but not the other? I'm not sure I understand exactly how the `nParents` check works today.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 2 of 3 files at r9, 134 of 136 files at r10, 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137620)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/distsql_physical_planner.go` line 4178 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OES5FppApHBbeGk8jRO:-OESG6zi6dHFQP57KWdW:b8yypq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3e42811e17d6080261388d2af98c280d4b423e/pkg/sql/distsql_physical_planner.go#L4178)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@yuzefovich is this true? Or are there cases where we might wrap one side of a join or set op but not the other? I'm not sure I understand exactly how the `nParents` check works today.
</blockquote></details>

It is true in a sense that the current infrastructure assumes either 0 or 1 inputs to the `planNode`-being-wrapped (see `rowexec.NewProcessor` for `LocalPlanNode` core).

I think it is confusingly named `nParents` - I'd say `nChildren` or `nInputs` would be more clear. (Consider renaming it while we're here.)

What we have before starting our walk when `wrapPlan` is called is the first `planNode` that we don't have a corresponding DistSQL processor for. We then traverse this `planNode`'s descendants / inputs to find the first "stage" of `planNode`s that have the DistSQL equivalent. Almost all `planNode` implementations have 0 or 1 inputs. I think the main exceptions are `joinNode` and `unionNode` for which we do have equivalent DistSQL processors, so we would never be wrapping them. (There is also some discussion about this on the PR #28509 that introduced this logic.)

(Looks like we have another `planNode` that might have multiple inputs - `hookFnNode` since it has the notion of `subplans`. This was added in 1e722398e6b1388e7eaa74735ef250ae48906159, and on a quick look it seems like we actually don't have any hooks that use `subplans` functionality.)

**Comment by mgartner** [comment]
*[`pkg/sql/distsql_physical_planner.go` line 4178 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/137620#-OES5FppApHBbeGk8jRO:-OE_Dw-I7BpF5iCyAAXl:br0c1t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3e42811e17d6080261388d2af98c280d4b423e/pkg/sql/distsql_physical_planner.go#L4178)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It is true in a sense that the current infrastructure assumes either 0 or 1 inputs to the `planNode`-being-wrapped (see `rowexec.NewProcessor` for `LocalPlanNode` core).

I think it is confusingly named `nParents` - I'd say `nChildren` or `nInputs` would be more clear. (Consider renaming it while we're here.)

What we have before starting our walk when `wrapPlan` is called is the first `planNode` that we don't have a corresponding DistSQL processor for. We then traverse this `planNode`'s descendants / inputs to find the first "stage" of `planNode`s that have the DistSQL equivalent. Almost all `planNode` implementations have 0 or 1 inputs. I think the main exceptions are `joinNode` and `unionNode` for which we do have equivalent DistSQL processors, so we would never be wrapping them. (There is also some discussion about this on the PR #28509 that introduced this logic.)

(Looks like we have another `planNode` that might have multiple inputs - `hookFnNode` since it has the notion of `subplans`. This was added in 1e722398e6b1388e7eaa74735ef250ae48906159, and on a quick look it seems like we actually don't have any hooks that use `subplans` functionality.)
</blockquote></details>

:+1:  `nParents` has already been removed. I'll see if I can clean up `hookFnNode` in a separate PR.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
