### PR TITLE
sql/opt: Support regtype in foldOIDFamilyCast 

### PR DESCRIPTION
**Pull request by e-mbrown**
Informs: #91022

Type cast to regtype can now use the index on pgtype(oid).

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
looking good! just hada  refactor suggestion

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-:-NHBWlDb55EIbtsMt625:b-xmzutm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-NHBQPdc7uyWfku8NNrY:-NHBQPddCTVOs5r6CnoQ:bkgh0bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3973eb80822d66ebf163fbdd91c3e2e18d069adf/pkg/sql/opt/norm/fold_constants_funcs.go#L384)):*
> ```Go
> 
> 			// Check for array being cast to regtype
> 			if arrRef, ok := typRef.(*tree.ArrayTypeReference); ok {
> ```

nit: i'd find it a bit more readable with another switch here. example:

```
var resolvedTyp *types.T
switch t := typRef.(type) {
case *tree.ArrayTypeReference:
  resolvedTyp, err = c.f.catalog.ResolveType(..., t.ElementType.(*tree.UnresolvedObjectName))
  // err check
case *tree.UnresolvedObjectName:
  resolvedTyp, err = c.f.catalog.ResolveType(..., t)
  // err check
case *types.T:
  return resolvedTyp = t
default:
  return nil, false, nil
}

dOid = tree.NewDOidWithTypeAndName(resolvedTyp.Oid(), types.Regtype, resolvedTyp.SQLStandardName())
```

we'd also remove the `oidForUserOrPredefinedTypes` function
___
*[`pkg/sql/opt/exec/execbuilder/testdata/scalar` line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-NHBWSn39fXzx4FbBp25:-NHBWSn39fXzx4FbBp26:bpd1g7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3973eb80822d66ebf163fbdd91c3e2e18d069adf/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1074)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) SELECT * FROM pg_type WHERE oid = 'bool'::regtype
> ```

could you add a test for `oid = 'bool[]'::regtype` too?

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92068)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/scalar` line 1074 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-NHBWSn39fXzx4FbBp25:-NHQm_Lh7TStynODh6Cl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3973eb80822d66ebf163fbdd91c3e2e18d069adf/pkg/sql/opt/exec/execbuilder/testdata/scalar#L1074)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a test for `oid = 'bool[]'::regtype` too?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm, feel free to merge if you address the nit!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-:-NHR4moq7UYxZ9bwT4nV:b-hdmncv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/opt/norm/fold_constants_funcs.go` line 383 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92068#-NHR4cxdDOxqxc8IvFLd:-NHR4cxdDOxqxc8IvFLe:b-rxk2ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/baee6c7f4df24708b8e8faddee0cf6ea98a0fbc5/pkg/sql/opt/norm/fold_constants_funcs.go#L383)):*
> ```Go
> 			}
> 
> 			// Check for array being cast to regtype
> ```

this comment seems misplaced. should it be inside the `ArrayTypeReference` case?

**Comment by e-mbrown** [comment]
bors r=rafiss

**Pull request merged**
