### PR TITLE
release-2.1: adjust gossip timings to minimize gossip partitions

### PR DESCRIPTION
**Pull request by petermattis**
Backport:
  * 1/1 commits from "gossip: replace tickers with timers" (#29051)
  * 6/6 commits from "gossip: maintain a gossip connectivity map" (#28963)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by petermattis** [comment]
bors r=tschottdorf

**Comment by petermattis** [comment]
`TestNetworkReachesEquilibrium` failure. I'm not too fond of that test given how flaky it is under stress (it is skipped for nightly stress). I'll file an issue to fix or remove it.

bors r=tschottdorf

**Comment by petermattis** [comment]
`Example-ORMs` is currently broken. Temporarily disabled until someone more knowledgable can diagnose.

bors r=tschottdorf

**Comment by petermattis** [comment]
Known test failure with `TestSplitAt`. See https://github.com/cockroachdb/cockroach/issues/29169.

bors r=tschottdorf

**Pull request merged**
