### PR TITLE
changefeedccl: Emit span resolved event when end time reached 

### LINKED ISSUE #108464: cdc: Lagging span checkpoint with end_time option might be broken
Lagging span checkpointing supposed to address a case when
changefeed executes rangefeeds against large table, and some of
the spans might be lagging behind the rest of the spans (due
to catchup scan throttling, or any other reasons).
In those cases, changefeed suppose to produce span based checkpoint
that is meant to ensure that catchup scan completes.

Consider the case where changefeed executes against large table, but
has both cursor and end_time options specified, with end_time in the past
(something like: I want to re-emit all events for the past hour, and then exit).
In this case, changefeed will start the catchup scan from cursor position, and
is supposed to terminate at end_time.

It appears (but needs to be verified) that in those cases, as soon. as the event
for the end_time is reached, all subsequent events are skipped -- which is fine.
What's not fine is that in this case we will never emit range based checkpoint, and that
will render lagging span checkpointing ineffective.

(Granted, this is a bit of a corner case, and was discovered via #108157).

Jira issue: CRDB-30482

### PR DESCRIPTION
**Pull request by miretskiy**
Changefeed supports a mode where the user wants to emit
all events that occurred since some time in the past (`cursor`),
and end the changefeed (`end_time) at the time in the near future.

In this mode, the rangefeed catchup scan starting from `cursor`
position could take some time -- maybe even a lot of time --
and in this case, the very first checkpoint kvfeed will observe
will be after `end_time`.  All of the events, including
checkpoints after `end_time` are skipped, as they should.

However, this meant that no changefeed checkpoint
records could be produced until entire changefeed completes.
This PR ensures that once the `end_time` is reached, we will
emit 1 "resolved event" for that span, so that changefeed
can produce span based checkpoint if needed.

Fixes https://github.com/cockroachdb/cockroach/issues/108464

Release note: None

### CODE REVIEW

**Comment by miretskiy** [comment]
@jayshrivastava -- ignore first commit; it's being reviewed at https://github.com/cockroachdb/cockroach/pull/109346

**Review by jayshrivastava — APPROVED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-:-Ncco0UaD1oVJ8MTAmZB:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @miretskiy)

___
*[`-- commits` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccbjiVCvJBfM4aSI-_):*
typo: improve
___
*[`pkg/ccl/changefeedccl/kvevent/event.go` line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NcceAj_AnmZvcdY3DM3:-NcceAj_AnmZvcdY3DM4:bkcnq8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/event.go#L100)):*
> ```Go
> 
> 	// number of event types.
> 	numEventTypes = 3
> ```

I think we should do `TypeResolved + 1`
___
*[`pkg/ccl/changefeedccl/kvevent/event.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-Nccf4P3B68asVeFwLKr:-Nccf4P3B68asVeFwLKs:bt1tgpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/event.go#L131)):*
> ```Go
> 		return int(TypeKV)
> 	default:
> 		return int(TypeResolved)
> ```

Do you think we could add a case for Unknown? The blocking buf should never see an event of type unknown bc the kvfeed will check before adding, but maybe someone in the future will call this without doing the check first.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 6873 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccnTBM2stenbWTKJfS:-NccnTBM2stenbWTKJfT:b-j77rpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5094cf9d0223cf191da56de19cb8a8470c9a46bb/pkg/ccl/changefeedccl/changefeed_test.go#L6873)):*
> ```Go
> 
> 		// Don't care much about the values emitted (tested elsewhere) -- all
> 		// we want to make sure is that the feed terminates.
> ```

We should check if we get resolved timestamps at the boundary when end_time is reached. Can use the filter span with mutation knob.
___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go` line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccdipmEFUTgxcz_f3q:-NccdipmEFUTgxcz_f3r:blsn3ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L180)):*
> ```Go
> 	require.NoError(t, buf.CloseWithReason(context.Background(), context.Canceled))
> 
> 	require.EqualValues(t, 0, metrics.AllocatedMem.Value())
> ```

I think we should assert that the numKV, numResolved, numFlush metrics are reset too. You probably need to store in flight counters to do so.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/kvevent/event.go` line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NcceAj_AnmZvcdY3DM3:-NccprPP2BAcFBoG3ouv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/event.go#L100)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I think we should do `TypeResolved + 1`
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/kvevent/event.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-Nccf4P3B68asVeFwLKr:-NccqWf5CSl9bWu-QcIo:brf3kvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/event.go#L131)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Do you think we could add a case for Unknown? The blocking buf should never see an event of type unknown bc the kvfeed will check before adding, but maybe someone in the future will call this without doing the check first.
</blockquote></details>

made it more explicit + log.warning in case of unknown event.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 6873 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccnTBM2stenbWTKJfS:-Ncd3yjw29rIopCLRRiV:b6g8bp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5094cf9d0223cf191da56de19cb8a8470c9a46bb/pkg/ccl/changefeedccl/changefeed_test.go#L6873)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

We should check if we get resolved timestamps at the boundary when end_time is reached. Can use the filter span with mutation knob.
</blockquote></details>

Good idea -- done.
___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go` line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccdipmEFUTgxcz_f3q:-Ncd41PyDXfJpWwgbDY_:b-vyy8jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L180)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I think we should assert that the numKV, numResolved, numFlush metrics are reset too. You probably need to store in flight counters to do so.
</blockquote></details>

i'll pass for now. I tried that.  First, numKV/flush/resolved are counters, not gauges.
And even those things that are counters (like Acquired/Released counters) are updated only when
release is called.  I realized that release sometimes is not called -- for example when buffer is closed w/out releasing all buffered events.
Plus, there is fair bit of variability in these flush events being generated.

Point is -- this test was becoming more and more elaborate; and it's not clear if trying to get all metrics correctly reset was proving to be more trouble than worth.
Instead, I focused on the allocated memory -- that one is correct to be reset because whether or not
I release events, the memory is returned when closing quota.

I suspect we'll have to revisit this issue since I'm not 100% convinced that we're not generating excessive number of flush requests.

**Review by jayshrivastava — APPROVED** [review]
LGTM. Ty for working on this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-:-NcxPxk_2zMZiSPowPGp:bzhgh61)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 6920 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NcxP6dy6olefSEhCvnC:-NcxP6dy6olefSEhCvnD:b90d6te) ([raw file](https://github.com/cockroachdb/cockroach/blob/120286996ca31bb6a5fe4db661f566af859c7f35/pkg/ccl/changefeedccl/changefeed_test.go#L6920)):*
> ```Go
> 		// After changefeed completes, verify we have seen all ranges emit resolved
> 		// event with end_time timestamp.  That is: verify frontier.Frontier() is at end_time.
> 		expectedFrontier := endTime.Prev()
> ```

For my own understanding, can you explain why it's `Prev()`?
___
*[`pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go` line 180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NccdipmEFUTgxcz_f3q:-NcxPvDpEpcmbsfhjHvP:bb6sh25) ([raw file](https://github.com/cockroachdb/cockroach/blob/5408b7169db02c6cbf73994679cacd0ab2d9c2a9/pkg/ccl/changefeedccl/kvevent/blocking_buffer_test.go#L180)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i'll pass for now. I tried that.  First, numKV/flush/resolved are counters, not gauges.
And even those things that are counters (like Acquired/Released counters) are updated only when
release is called.  I realized that release sometimes is not called -- for example when buffer is closed w/out releasing all buffered events.
Plus, there is fair bit of variability in these flush events being generated.

Point is -- this test was becoming more and more elaborate; and it's not clear if trying to get all metrics correctly reset was proving to be more trouble than worth.
Instead, I focused on the allocated memory -- that one is correct to be reset because whether or not
I release events, the memory is returned when closing quota.

I suspect we'll have to revisit this issue since I'm not 100% convinced that we're not generating excessive number of flush requests.
</blockquote></details>

Ack!

**Comment by miretskiy** [comment]
> For my own understanding, can you explain why it's `Prev()`?

We always treated end_time exclusive.  So, when end time boundary reached, we emit "EXIT" span boundary at boundary.Prev.

**Review by erikgrinaker — COMMENTED** [review]
Not too familiar with the CDC parts, so only skimmed this, but overall LGTM.

> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, 4 of 5 files at r3, 7 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-:-Ndj149WEYxS4U5xjJ3C:b-3uwiz8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NdiyxDQ4CDzhTzqcUc5:-NdiyxDQ4CDzhTzqcUc6:bhgqbzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/120286996ca31bb6a5fe4db661f566af859c7f35/pkg/cmd/roachtest/tests/cdc_bench.go#L201)):*
> ```Go
> 	// (and release allocations), resulting in significant drop in completed ranges throughput.
> 	settings.ClusterSettings["kv.rangefeed.closed_timestamp_refresh_interval"] = "5s"
> 	settings.ClusterSettings["changefeed.memory.per_changefeed_limit"] = "4G"
> ```

Shouldn't we benchmark out-of-the-box performance, since that's what users will typically experience? If the defaults are bad, then we should fix the defaults, not fudge the benchmark.

If we really need this, I'd argue it should be a separate variant, so that we benchmark both default performance and tuned performance -- it's important that we have a realistic view of what the real-world performance is.
___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-NdizO-aDw7pCfZG-dAI:-NdizO-aDw7pCfZG-dAJ:bor162q) ([raw file](https://github.com/cockroachdb/cockroach/blob/120286996ca31bb6a5fe4db661f566af859c7f35/pkg/cmd/roachtest/tests/cdc_bench.go#L215)):*
> ```Go
> 	// due to elevated goroutine scheduling latency.
> 	// Default is 2s; make it 3x.
> 	settings.Env = append(settings.Env, "COCKROACH_NETWORK_TIMEOUT=6s")
> ```

Fixed on master, see #109578.

**Comment by miretskiy** [comment]
> Shouldn't we benchmark out-of-the-box performance, since that's what users will typically experience? If the defaults are bad, then we should fix the defaults, not fudge the benchmark.
> 
> If we really need this, I'd argue it should be a separate variant, so that we benchmark both default performance and tuned performance -- it's important that we have a realistic view of what the real-world performance is.
> 

Good points, @erikgrinaker .  I will test to see if this benchmark passes with the new closed timestamp
(3s vs 200ms before).  I will however, keep the other setting.  I think the argument here is that this is a 
large scale changefeed; so, the fan in is just pretty crazy, which is why you may want to bump up your defaults,
and some of the clients do that.  

> > ```go
> > 	// due to elevated goroutine scheduling latency.
> > 	// Default is 2s; make it 3x.
> > 	settings.Env = append(settings.Env, "COCKROACH_NETWORK_TIMEOUT=6s")
> > ```
> 
> Fixed on master, see #109578.

Nice to know; I'm going to try to see if 4s is sufficient.

**Comment by miretskiy** [comment]
@erikgrinaker  -- verified benchmark still passes once I removed some of the settings you pointed out (timeout of 4 sec is fine, and 3s closed ts is also fine)

**Review by erikgrinaker — COMMENTED** [review]
The typical user isn't going to change any of these settings unless we tell them to. I think we should focus on the default case, and make the default case better if necessary. We can have separate tuned benchmark variants if we want to look at their effect. Your call though, these are CDC's benchmarks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109439#-:-NdoF-6T5ftZ7h-A1qGn:brx8xa8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

**Pull request merged**
