### PR TITLE
 sql,settings: make SET CLUSTER SETTING wait for value to update, disallow in txn

### PR DESCRIPTION
**Pull request by dt**
SET CLUSTER SETTING does a transactional write to the system table. However
settings values are _read_ from an in-memory cache which is not updated until
the system table write is gossiped and that gossip update is processed by the
settings worker.

Release note (sql change): SET CLUSTER SETTING cannot be used inside a
transaction.

Settings values are cached in memory and that cache is updated via gossip after
a SET commits. That delay -- for the update to arrive via gosssip and be
processed and the cache updated -- can mean that a statement executed
immediately following a SET CLUSTER SETTING may execute before the new setting
takes effect, and knowing when it is safe to execute a statement that uses the
new setting is tricky.

Instead, we can make SET CLUSTER SETTING _wait_ until it sees the value it set
returned when reading the settings cache (or return an error if it does not
appear after a timeout of 30s). This should make it easier to set a setting and
then use that value in subsequent statements.

Release note (sql change): SET CLUSTER SETTING attempts to wait until change has
been gossiped.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
:lgtm_strong: so glad to have you taking this off my plate!

One last nitlet to solve, though: it appears that the way we run `SET CLUSTER SETTING` in migrations at server startup interacts badly with waiting to read the gossip update. I guess maybe gossip isn't up and running when migrations execute?

> Reviewed 1 of 1 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29063#-:-LKmKbcx3tGuuPVuyTH_:b-rh5x9g)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by dt** [comment]
Looks like that was a bug in my `Encoded` impl for statemachinesetting -- it needed to return the bytes, not the `%+v` rendered value that `String` does. Fixed (i think? TC isn't picking it up for some reason yet...)

**Review by benesch — COMMENTED** [review]
woohoo, TC is extremely happy!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29063#-:-LKnDyYO6VwNBwpi5LF5:b-j8oauh)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by dt** [comment]
just to assuage my fears:
```
$ make stressrace PKG=./pkg/server TESTS=SetAndShow
756 runs so far, 0 failures, over 7m25s
```

**Comment by knz** [comment]
:+1: on disallowing the thing inside a txn. :microscope: :dog: on the rest. Thanks!

**Comment by dt** [comment]
Bors r+

**Comment by benesch** [comment]
Backporting this in #29082.

**Pull request merged**
