### PR TITLE
sql,csv: distinguish empty columns from quoted empty strings

### LINKED ISSUE #19743: IMPORT: support null as non-quoted string in import csv
Postgres `copy with csv` format differentiates a nullable text field that is null or an empty string by using `""` as the empty string and an unquoted empty string (i.e., nothing) as null. This is round-trippable by default with the postgres copy. We should support this syntax. 

See https://forum.cockroachlabs.com/t/import-from-csv-fails-on-null-data-for-int-types/1067/1

Epic: CRDB-14049

Jira issue: CRDB-17420

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/19743

The first commit is meant to backport. The second one maybe should not be backported.

Release note (bug fix): Previously, an empty column in the input to
COPY ... FROM CSV would be treated as an empty string. Now, this is
treated as NULL. The quoted empty string can still be used to input an
empty string, Similarly, if a different NULL token is specified in
the command options, it can be quoted in order to be treated as the
equivalent string value.

Release note (backward-incompatible change): If no `nullif` option is specified
while using IMPORT CSV, then a zero-length string in the input is now treated as
NULL. The quoted empty string in the input is treated as an empty string. Similarly,
if `nullif` is specified, then an unquoted value is treated as NULL, and a
quoted value is treated as that string. These changes were made to make IMPORT CSV
behave more similarly to COPY CSV.

If the previous behavior (i.e. treating either quoted or unquoted values
that match the `nullif` setting as NULL) is desired, then use the new
`allow_quoted_null` option in the IMPORT statement.

### CODE REVIEW

**Review by otan — APPROVED** [review]
i think we should definitely backport the first commit, i could see it either way with the second commit (but leaning towards committing it anyway)

**Comment by rafiss** [comment]
This is currently blocked on answering the questions in https://github.com/cockroachdb/cockroach/issues/19743#issuecomment-1187610679

**Review by dt — APPROVED** [review]
Second seems like it should be called out as breaking change, since -- absent an explicit null-if -- an empty cell in a csv that was successfully, quietly importing as an empty string will now import as NULL instead, importing as a different value but still doing so quietly and successfully, right? That seems like a breaking change? which would also rule out a backport?

**Comment by rafiss** [comment]
Yes, it is a breaking change, which is why this is blocked until we decide how exactly we want to break things (this thread https://github.com/cockroachdb/cockroach/issues/19743#issuecomment-1187610679). Or if we introduce another option to enable the new behavior (my 2c there is that the mental overhead of having more options may not be worth it, but the Product team should weigh in).

**Comment by rafiss** [comment]
bors r=otan,dt

**Pull request merged**
