### PR TITLE
sqlccl: retry failed splits on AmbiguousResultErrors

### PR DESCRIPTION
**Pull request by benesch**
`RESTORE` presplits sometimes fail due to ambiguous result errors, which
then fails the entire restore. Here's an example of such an error that
reproduced readily on a 2TB `RESTORE` into a cluster with existing data:

    Error: pq: presplitting 16384 ranges: storage/replica_command.go:2712: split at key /Table/53/1/6893975069665253839/"59ebe116-939c-4a40-83ae-b53652393a8b"/9561153 failed: result is ambiguous (error=TransactionRetryError: retry txn "split" id=0355ab32 key=/Local/Range/"\xbd\x89\xfd_\xa8H\x99]\xcb\u07b7\x12bc82cd3b-3091-4ced-a307-fa2f939e3da3\x00\x01\xf8\x04\xc0E"/RangeDescriptor rw=true pri=0.01067854 iso=SERIALIZABLE stat=PENDING epo=0 ts=1495044332.741237574,2 orig=1495044249.173005863,0 max=1495044249.173005863,0 wto=false rop=false seq=2, pending RPCs=1)

This patch, which retries failed splits up to three times, made the
problem completely vanish for me.

### CODE REVIEW

**Comment by bdarnell** [comment]
AdminSplit has an [internal retry loop](https://github.com/cockroachdb/cockroach/blob/dbd54977889302942c2e98ae9195aa61cc032678/pkg/storage/replica_command.go#L2539) that only looks for ConditionFailedError. Would expanding that to include AmbiguousResultErrors also solve your problem, or do you need the higher-level retry loop?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16149#-:-Kl5WZoslPxZvHCDQbGm:bm7d3iu)*

**Comment by benesch** [comment]
Oh, good question. Retrying `AmbiguousResultError`s in the existing loop would definitely solve the problem at hand, though adding this higher-level retry loop might still be useful as future-proofing against new types of transient errors. @danhhz, thoughts?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16149#-:-KlEjWUSpuzTGeFBO2zA:b-xqv53p)*

**Comment by danhhz** [comment]
Expanding the existing loop seems reasonable to me. I prefer to keep retries targeted when we can

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16149#-:-KlUC_bnR_4XRPGGYo-l:brf4b92)*

**Comment by benesch** [comment]
Updated to adjust the existing retry loop inside `AdminSplit` instead of adding a new one in `RESTORE`. PTAL!

(Any way to test this?)

**Comment by tamird** [comment]
I think you can use `TestingEvalFilter` or `TestingApplyFilter`?

I think the commit message needs an update, too.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16149#-:-KlUZbKQI4Tu4Lf_2mJz:b-u8vk1j)*

**Comment by benesch** [comment]
It does? I thought I updated it to this: ```This patch, which extends AdminSplit's internal retry loop to retry
AmbiguousResult errors, made the problem completely vanish for me.```

**Comment by tamird** [comment]
Ah, I only looked at the subject line, which looks a bit overly specific.

**Comment by benesch** [comment]
ah, fair point

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16149#-:-KlVIJ0n_ZuxEM7H-BNW:bnfp4nl)*

**Pull request merged**
