### PR TITLE
storageccl: retry AmbiguousResultErrors from WriteBatch in Import

### LINKED ISSUE #14784: restore: NotLeaseHolderError when restoring TPC-H scale factor 10 data
Build: 725ea82
Config: 6-node Azure cluster (Standard_D3)

While trying to RESTORE a backup of data for TPC-H scale factor 10 (~23 GB), I've run this issue:

>root@:26257/> RESTORE tpch.* FROM 'azure://...../scalefactor-10';
>pq: importing 813 ranges: writebatch [/Table/58/9/54613/79612/233862530031812609/0,/Table/58/9/54658/604645/233862242939731969/0/NULL): result is ambiguous (Raft re-proposal failed: [NotLeaseHolderError] range 52: replica {2 2 2} not lease holder; current lease is repl={4 4 4} start=1491875884.347312985,0 epo=2 pro=1491875884.347317085,0)

In the node 2 logs, I see the only messages that pertain to this key range:

>W170411 01:54:18.978691 63316 kv/dist_sender.go:1174  [s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000,n2] have been waiting 1m0s sending RPC to r52 for batch: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

> W170411 01:55:33.184925 64033 storage/replica.go:2292  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] have been waiting 1m0s for proposing command WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

>W170411 01:59:29.528451 64033 storage/replica.go:1709  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] context canceled before command queue: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

This has happened twice so far (out of 3 attempted RESTOREs).

Logs from all nodes:
[logs.zip](https://github.com/cockroachdb/cockroach/files/913279/logs.zip)

### PR DESCRIPTION
**Pull request by danhhz**
In general, ambiguous results happen occasionally and a larger operation
like RESTORE is more likely to hit them. WriteBatch is idempotent, so
it's safe to retry any WriteBatches that fail.

Closes #14784.

### CODE REVIEW

**Comment by danhhz** [comment]
@bdarnell Any suggestions on how to test this? CommandFilter that returns an error or is there something better?

I'm also testing this on the 2tb restore. It's made it further than it did before this change

**Comment by bdarnell** [comment]
LGTM. Yeah, a TestingEvalFilter is the best way to test that I can think of.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-:-Ki6gKfvTN4O9He5Rra_:b-x4tehl)*

**Comment by andreimatei** [comment]
Do you happen to have the message of an AmbiguousResultError that you saw (in the hope that the message will tell us which of the many places where it come from out of the many place that it could have come from - I forgot if we made the messages good like that or not)?
In the past these AmbiguousResultErrors, when happening on clusters without chaos, were worth looking into.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-:-Ki6h-f_nWN840JpjSTq:b-bu4fqz)*

**Comment by danhhz** [comment]
@andreimatei There's two in the linked issue. Both have an underlying NotLeaseHolderError.

**Comment by andreimatei** [comment]
From that issue it seems to me that we need to repropose for an unclear reason, and the reproposal fails because, since the original proposal, the replica executing the request is no longer the LeaseHolder. This is probably related to the "have been waiting 1m0s for proposing command WriteBatch" messages - I think we may be slamming a replica too hard and the leases move away somehow. This seems scary to me... Who knows what other consequences the appearance of these messages has on the server as a whole. I remember a long time ago we discussed that there'd be rate-limiting somewhere in the restore stack; is that still the plan?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-:-Ki6lv1VUcKq_Ud0pjiM:bx68i2c)*

**Comment by danhhz** [comment]
@bdarnell expanded the Import test if you want to take a quick look

@andreimatei Backup and restore both rate limit quite heavily on the client side (this happened since that issue was filed), so those messages only show up very sporadically now. There's an issue to look back into the rate limiting to see if we can do something more principled (https://github.com/cockroachdb/cockroach/issues/14798).

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/storageccl/import_test.go, line 201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-Ki6qQmWvywTB4pN26rn:-Ki6qQmWvywTB4pN26ro:b48v4qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f63bc59e308732445c311ebb265f1d4652502e6/pkg/ccl/storageccl/import_test.go#L201)):*
> ```Go
> 	for i := 0; i <= len(files); i++ {
> 		t.Run(strconv.Itoa(i), func(t *testing.T) {
> 			atomic.StoreInt64(&remainingAmbiguousWriteBatches, initialAmbiguousWriteBatches)
> ```

Assert that after the test, `remainingAmbiguousWriteBatches` is zero (to make sure that your filter is in fact getting called)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-:-Ki6qW11Bt8Z8b83mDzx:bnfp4nl)*

**Comment by danhhz** [comment]
TFTR!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/storageccl/import_test.go, line 201 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-Ki6qQmWvywTB4pN26rn:-Ki6sIOV_INLGFpKS75_:b-60uxjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f63bc59e308732445c311ebb265f1d4652502e6/pkg/ccl/storageccl/import_test.go#L201)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Assert that after the test, `remainingAmbiguousWriteBatches` is zero (to make sure that your filter is in fact getting called)
</blockquote></details>

good idea, done. (though it's just expected to be < 0 since I'm blindly adding -1 every time the filter gets a WriteBatch)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15175#-:-Ki6sUgnk8JIH7smB8r4:b-814g8k)*

**Pull request merged**
