### PR TITLE
release-20.2: coldata: fix updating offsets of bytes in Batch.SetLength

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/2 commits from #59028.

/cc @cockroachdb/release

---

In `SetLength` method we are maintaining the invariant of `Bytes`
vectors that the offsets are non-decreasing sequences. Previously, this
was done incorrectly when a selection vector is present on the batch
which could lead to out of bounds errors (caught by our panic-catcher)
some time later. This is now fixed by correctly paying attention to the
selection vector.

I neither can easily come up with an example query that would trigger
this condition nor can I prove that it won't occur, but I think we have
seen a single sentry report that could be explained by this bug, so I
think it's worth backporting.

Fixes: #57297.

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when executing queries with BYTES or STRING types via the
vectorized engine in rare circumstances, and now this is fixed.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU62M9C7BMIqUmM8qd:-MRU62M9C7BMIqUmM8qe:b-ouvqo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L252)):*
> ```Go
> 		// by the batch.
> 		maxIdx := length - 1
> 		if m.useSel && m.sel[length-1] > maxIdx {
> ```

Can we be extra-safe here and also check `m.sel != nil && len(m.sel) >= length` before indexing?
___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRU6_s1BvprNlY3HM8L:b-nawj6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
> ```Go
> 			//
> 			// This assumption is only enforced by the invariantsChecker
> 			// starting from 21.1 branches, so we have a "safe" conditional to
> ```

Could you point me to it?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU62M9C7BMIqUmM8qd:-MRVZXcx6R8vswjJo2Qh:bpk94l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L252)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we be extra-safe here and also check `m.sel != nil && len(m.sel) >= length` before indexing?
</blockquote></details>

I think that would be an overkill. If `m.useSel` is `true`, then the batch must have a selection vector with length of at least `length`, since otherwise this batch is broken anyway, so it doesn't matter whether we crash when setting the length on it or some time later when reading from it.
___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRV_2jR8D1V2fMjDSOu:b-kk07rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you point me to it?
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/7df5918551f948d7484a80bf9fd46eb6c2a3dfa0/pkg/sql/colexec/invariants_checker.go#L55-L64

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRVeRetE_UVq6bvauho:b-20plle) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/7df5918551f948d7484a80bf9fd46eb6c2a3dfa0/pkg/sql/colexec/invariants_checker.go#L49-L54
</blockquote></details>

Oops, wrong selected lines. Correct ones: https://github.com/cockroachdb/cockroach/blob/7df5918551f948d7484a80bf9fd46eb6c2a3dfa0/pkg/sql/colexec/invariants_checker.go#L55-L64

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRZMI_x6wwJX0HCslqX:buasx8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Oops, wrong selected lines. Correct ones: https://github.com/cockroachdb/cockroach/blob/7df5918551f948d7484a80bf9fd46eb6c2a3dfa0/pkg/sql/colexec/invariants_checker.go#L55-L64
</blockquote></details>

Sorry, I meant the "safe conditional" you mention in this branch. I guess I'm just worried that this invariant is not checked in this branch. What about a check to ensure that if:
```
if maxIdx < length {
    maxIdx = length
}
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRa0LAp9azrG4WRTgS7:bsmnp3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry, I meant the "safe conditional" you mention in this branch. I guess I'm just worried that this invariant is not checked in this branch. What about a check to ensure that if:
```
if maxIdx < length {
    maxIdx = length
}
```
</blockquote></details>

Yeah, I share your concern, that's why I added `m.sel[length-1] > maxIdx` part above (which is - I think - exactly what you're suggesting, albeit in an "inverse" form).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-:-MRa0s-I31HKunO3iZG5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59151#-MRU6_s1BvprNlY3HM8K:-MRa0tcw8AdLTKmjB303:b-2dar6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dd1f70103eced9e86037d2240a401ceb846f04/pkg/col/coldata/batch.go#L257)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I share your concern, that's why I added `m.sel[length-1] > maxIdx` part above (which is - I think - exactly what you're suggesting, albeit in an "inverse" form).
</blockquote></details>

Carry on :joy:

**Pull request merged**
