### PR TITLE
kvserver: scan only intents during rts scan

### LINKED ISSUE #69697: kvserver/rangefeed: only scan separated intents span to bootstrap resolved timestamp
**Is your feature request related to a problem? Please describe.**
Today we initialize the resolved timestamp by iterating all of the intents in the range. We do this by iterating the entire range and only looking at the intents. We set up the iterator here: https://github.com/cockroachdb/cockroach/blob/c4de73f72136e774ec887f3cbc0dda6c37d60dab/pkg/kv/kvserver/replica_rangefeed.go#L387  and we skip over the values here: https://github.com/cockroachdb/cockroach/blob/c4de73f72136e774ec887f3cbc0dda6c37d60dab/pkg/kv/kvserver/rangefeed/task.go#L84

If we were to restrict this scan to only the separated intents on ranges which have been fully migrated to only use separated intents, we could avoid a full data scan during rangefeed startup. This is a big win!

**Describe the solution you'd like**

We should set up the RTS iterator to only look at the separated intents when appropriate.

**Additional context**

There's been talk in the past of storing the resolved timestamp start. I don't think we need to do this with the separated intents.

### PR DESCRIPTION
**Pull request by stevendanna**
In 21.2, seperated intents are the default. Once migrated, we can then
use this to iterate over substantially less data to find all intents
for a given keyspan. The hope is that this will make rangefeed
start-up substantially cheaper.

Informs #70920
Fixes #69697 

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Exciting! Just left some drive-by comments. I'd be interested to hear what kind of impact you are seeing this have on changefeed restart latency.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-:-MlTSPPj48V-esNZLz9u:b-jntty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTQjEI8w5VvQzlXg9x:-MlTQjEI8w5VvQzlXg9y:blfrzqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/replica_rangefeed.go#L380)):*
> ```Go
> 	p = rangefeed.NewProcessor(cfg)
> 
> 	onlySeperatedIntents := r.store.cfg.Settings.Version.ActiveVersionOrEmpty(ctx).IsActive(clusterversion.PostSeparatedIntentsMigration)
> ```

I don't think you need the `ActiveVersionOrEmpty(ctx)` part.
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTQyBF5tTomQU4W7Mo:-MlTQyBG8j49GN4VpsAS:b-1zvqe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/replica_rangefeed.go#L385)):*
> ```Go
> 	if onlySeperatedIntents {
> 		rtsIter = func() rangefeed.IntentScanner {
> 			lowerBound := keys.LockTableSingleKeyStart
> ```

If we're providing a lower bound (which itself shouldn't be necessary), shouldn't it be `keys.LockTableSingleKey(desc.Key.AsRawKey(), nil)`?
___
*[pkg/kv/kvserver/rangefeed/task.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTT291Cb2_ha7X9eME:-MlTT291Cb2_ha7X9eMF:bexzgzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/rangefeed/task.go#L104)):*
> ```Go
> 	ltStart, _ := keys.LockTableSingleKey(startKey, nil)
> 	var meta enginepb.MVCCMetadata
> 	for valid, err := s.iter.SeekEngineKeyGE(storage.EngineKey{Key: ltStart}); ; valid, err = s.iter.NextEngineKey() {
> ```

This is relying on the iterator's upper bound to terminate the iteration. That's not necessarily a problem, but we should make that clear both here and in the `SeperatedIntentScanner` contract.
___
*[pkg/kv/kvserver/rangefeed/task.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTRwBXB94wwbeOwMmO:-MlTRwBXB94wwbeOwMmP:bio8r02) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/rangefeed/task.go#L113)):*
> ```Go
> 		engineKey, err := s.iter.EngineKey()
> 		if err != nil {
> 			// TODO(ssd): should this return or continue?
> ```

I assume you're asking the question because of the corresponding logic in `computeMinIntentTimestamp`. That logic looks wrong. We were continuing on all error cases at one point during the review process, and we switched it over, but must have missed that case. Do you mind fixing that over there as well?
___
*[pkg/kv/kvserver/rangefeed/task.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTSWgeAguWSztaisp-:-MlTSWgeAguWSztaisp0:b-7o5l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/rangefeed/task.go#L125)):*
> ```Go
> 		}
> 
> 		if meta.Txn != nil {
> ```

`meta.Txn == nil` is an error case, so we should treat it as such.

**Review by stevendanna — COMMENTED** [review]
> I'd be interested to hear what kind of impact you are seeing this have on changefeed restart latency.

Me too! Haven't been able to test this well yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-:-MlW-igs3wiwbhIFRVn9:bmpy7kc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @stevendanna)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTQjEI8w5VvQzlXg9x:-MlW-sUE98u6TOEsgMgj:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/replica_rangefeed.go#L380)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't think you need the `ActiveVersionOrEmpty(ctx)` part.
</blockquote></details>

Done. Thanks!
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTQyBF5tTomQU4W7Mo:-MlW-zdU99SW5C75JJHe:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/replica_rangefeed.go#L385)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're providing a lower bound (which itself shouldn't be necessary), shouldn't it be `keys.LockTableSingleKey(desc.Key.AsRawKey(), nil)`?
</blockquote></details>

Done. Thanks!
___
*[pkg/kv/kvserver/rangefeed/task.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTRwBXB94wwbeOwMmO:-MlUP6Lm622XSFstnkMR:b-4lx31t) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/rangefeed/task.go#L113)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I assume you're asking the question because of the corresponding logic in `computeMinIntentTimestamp`. That logic looks wrong. We were continuing on all error cases at one point during the review process, and we switched it over, but must have missed that case. Do you mind fixing that over there as well?
</blockquote></details>

Done -- your are exactly right about why I was asking, thanks for confirming! 
___
*[pkg/kv/kvserver/rangefeed/task.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlTSWgeAguWSztaisp-:-MlW0DcxEb6GGnaz-mL4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72d45cef975275f60f01063680eadb0321bd3913/pkg/kv/kvserver/rangefeed/task.go#L125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`meta.Txn == nil` is an error case, so we should treat it as such.
</blockquote></details>

Done.

**Comment by stevendanna** [comment]
I definitely like the idea of an intent iterator.  I didn't reach for the
utility function just because I wasn't sure if accumulating the intents
would be OK.  But, I imagine it's probably fine.

**Comment by stevendanna** [comment]
That error was a result of me accidentally misusing the scratch buffer provided by keys.LockSingleKey. Should be resolved now, let's see what CI says.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @nvanbenschoten, and @stevendanna)

___
*[pkg/kv/kvserver/rangefeed/task.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MljV9mb2G7bhDC8NEMU:-MljV9mb2G7bhDC8NEMV:b61wh6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e920ace8394fb7299b4b7e73ab0d4ca9dac37d5/pkg/kv/kvserver/rangefeed/task.go#L90)):*
> ```Go
> // separated intents are in use.
> //
> // EngineIterator Contract:
> ```

Any way to enforce this contract?

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-:-MlzV06I3lGH5S-xutvt:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 380 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlzV8w0AbHiX7blSz1Y:-MlzV8w0AbHiX7blSz1Z:b-pxfuwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e920ace8394fb7299b4b7e73ab0d4ca9dac37d5/pkg/kv/kvserver/replica_rangefeed.go#L380)):*
> ```Go
> 	p = rangefeed.NewProcessor(cfg)
> 
> 	onlySeparatedIntents := r.store.cfg.Settings.Version.IsActive(ctx, clusterversion.PostSeparatedIntentsMigration)
> ```

nit: any reason not to push this into the `rtsIter` closure?
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlzJP2e3Ax3Y4ie1Ms9:-MlzJP2e3Ax3Y4ie1MsA:b-fgxie6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e920ace8394fb7299b4b7e73ab0d4ca9dac37d5/pkg/kv/kvserver/replica_rangefeed.go#L402)):*
> ```Go
> 		iter := r.Engine().NewMVCCIterator(storage.MVCCKeyAndIntentsIterKind, storage.IterOptions{
> 			UpperBound: desc.EndKey.AsRawKey(),
> 			// TODO(nvanbenschoten): To facilitate fast restarts of rangefeed
> ```

I think we can get rid of this TODO now :partying_face: 
___
*[pkg/kv/kvserver/rangefeed/task.go, line 43 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlzU5tu8KCyG8FLWipI:-MlzU5tu8KCyG8FLWipJ:bwg9e76) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e920ace8394fb7299b4b7e73ab0d4ca9dac37d5/pkg/kv/kvserver/rangefeed/task.go#L43)):*
> ```Go
> type initResolvedTSScan struct {
> 	p              *Processor
> 	intentConsumer IntentScanner
> ```

nit: the naming here is a little off. We have a type named `IntentScanner` and we call it `c` in some contexts and `intentConsumer` in others. And we also have a type named `eventConsumer`. Can I suggest using `is` in all contexts?
___
*[pkg/kv/kvserver/rangefeed/task.go, line 114 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71295#-MlzUkOD4FyuYSh_0d9-:-MlzUkOD4FyuYSh_0d90:bya1t89) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e920ace8394fb7299b4b7e73ab0d4ca9dac37d5/pkg/kv/kvserver/rangefeed/task.go#L114)):*
> ```Go
> 			return err
> 		} else if !valid {
> 			// We assume the iterator has an UpperBound
> ```

s/assume the iterator has/depend on the iterator having/

**Comment by stevendanna** [comment]
bors r=nvanbenschoten

**Pull request merged**
