### PR TITLE
 scripts: enhance the release notes

### LINKED ISSUE #25180: docs/scripts: make the RN extraction recognize which changes were backported
Discussed with @jseldess: it would be useful when producing release notes for a branch to mark which changes are also duplicated on other release branches (or master). 

For example when looking at 2.0.x changes mark a RN as "back-ported from ..."
Or when looking at 2.1-alpha  changes mark a RN as "also back-ported to ..."

Preferably the annotation should be simple and easy to parse, so that a script  can further automatically recognize/process it.

### PR DESCRIPTION
**Pull request by knz**
Fixes #25180.

With this the amount of release notes for the first 2.2 alpha in https://github.com/cockroachdb/docs/pull/4051 is reduced to just under two pages.

Also this PR makes it easier to monitor progress during the execution of the script.

### CODE REVIEW

**Comment by knz** [comment]
The relevant command:

```

python3.6 scripts/release-notes.py \
    --from v2.2.0-alpha.00000000 --until <Candidate 2.2 SHA> \
    --exclude-from v2.2.0-alpha.00000000 --exclude-until v2.1.0
```

**Review by jseldess — APPROVED** [review]
Just tested and it seems to work perfectly. Thank you, @knz, for saving me an immense amount of time. 

LGREATTM, but you might want to have another dev review the code.

**Review by jseldess — APPROVED** [review]
Just have two small requests. 

One is inline (adding copy to clipboard for the docker image code block). 

The second I don't know exactly where to pinpoint in the code. It'd be great if you could remove the line breaks from individual bullets. I know the line width you use is friendlier on the eyes, but I end up removing them anyway in the release notes file because we don't use that convention and because the script I use to auto-generate docs issues from release notes currently expects a single line per bullet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-:-LRRvaoy8BHM8GbGKiC4:b-gvauyv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[scripts/release-notes.py, line 754 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRRvGtGCcX-ig2aEy6H:-LRRvGtGCcX-ig2aEy6I:b-eyrsay) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a04a9ab58af297f3febfdde994c0b4a391a2d6/scripts/release-notes.py#L754)):*
> ```Python
>     print("""### Docker image
> 
> ~~~shell
> ```

It'd be wonderful if you'd put this on the line preceding `~~~shell`:

```
{% include copy-clipboard.html %}
```

**Comment by knz** [comment]
yes this seems reasonable. let me have a look

**Comment by knz** [comment]
I have added a new option `--one-line` which does what you request. Please try it.

**Comment by jseldess** [comment]
Works great! Thanks again, @knz!

**Comment by knz** [comment]
I will take payment in the form of you spending some time with me to resume the conversation around #29810!

**Comment by jseldess** [comment]
Haha. Yes, sorry for dropping the ball on that. I need to edit the release notes today, but I'll reserve time early next week to get back to that with you.

**Comment by knz** [comment]
I'll even happily wait until next week, or the week after so we can avoid the stress of Thanksgiving.

**Review by jseldess — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32416)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[scripts/release-notes.py, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi0T4I8BPU1WYrDNvG:-LRi0T4I8BPU1WYrDNvH:b-q3ovsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L132)):*
> ```Python
> # Section titles for release notes.
> relnotetitles = {
>     'cli change': "Command line changes",
> ```

Please change `Command line changes` to `Command-line changes`.
___
*[scripts/release-notes.py, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi0BoL8M6ebrc8KVWr:-LRi0BoL8M6ebrc8KVWs:b-dixmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L725)):*
> ```Python
>     print("---")
>     print("title: What&#39;s New in", current_version)
>     print("toc: false")
> ```

Since this is still open, would you please change `toc: false` to `toc: true`. 
___
*[scripts/release-notes.py, line 764 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi-vAj5YHH8rNeHCjK:-LRi-vAk6g5pYSR7qsni:b-afa1sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L764)):*
> ```Python
> {% include copy-clipboard.html %}
> ~~~shell
> docker pull cockroachdb/cockroach:""" + current_version + """
> ```

Since this is still open, would you mind adding `$` to the start of the command as well?

```
$ docker pull cockroachdb/cockroach:""" + current_version + """
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32416)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[scripts/release-notes.py, line 754 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRRvGtGCcX-ig2aEy6H:-LRmM2P76F64l5Y-NsHk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92a04a9ab58af297f3febfdde994c0b4a391a2d6/scripts/release-notes.py#L754)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

It'd be wonderful if you'd put this on the line preceding `~~~shell`:

```
{% include copy-clipboard.html %}
```
</blockquote></details>

Done.
___
*[scripts/release-notes.py, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi0T4I8BPU1WYrDNvG:-LRmM-nS6BwvuSlmiqJ7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L132)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Please change `Command line changes` to `Command-line changes`.
</blockquote></details>

Done.
___
*[scripts/release-notes.py, line 725 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi0BoL8M6ebrc8KVWr:-LRmM1MdBzPl35dkS6Xi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L725)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Since this is still open, would you please change `toc: false` to `toc: true`. 
</blockquote></details>

Done.
___
*[scripts/release-notes.py, line 764 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32416#-LRi-vAj5YHH8rNeHCjK:-LRmM5HPE2yRVnfZkoiS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26d1d9d9062bbcd7d781bb62b462a6f6cc60d655/scripts/release-notes.py#L764)):*
<details><summary><i>Previously, jseldess (Jesse Seldess) wrote…</i></summary><blockquote>

Since this is still open, would you mind adding `$` to the start of the command as well?

```
$ docker pull cockroachdb/cockroach:""" + current_version + """
```
</blockquote></details>

Done.

**Pull request merged**
