### PR TITLE
storage/engine: add encryption stats for Pebble. The stats are

### PR DESCRIPTION
**Pull request by sumeerbhola**
currently incomplete (there are TODOs).
Also added a minimal test that exercises encrypted Pebble.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgTXKA_VmErWMmHIL:-LvGgTXKA_VmErWMmHIM:b-1sl2iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L205)):*
> ```Go
> }
> 
> type encryptionStatsHandler struct {
> ```

Rather than a separate struct, I would have just hung the methods needed by `EncryptionStatsHandler` off of `encryptedFS`. Then `newEncryptedEnv` would `return dataFS, dataFS, nil`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgsRJ-EFN0cnWRJsy:-LvGgsRJ-EFN0cnWRJsz:bi2wagi) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L222)):*
> ```Go
> 		s.ActiveDataKey = k.Info
> 	}
> 	return []byte(s.String()), nil
> ```

All of these `[]byte` casts make me suspect that these methods should be returning `string` instead of `[]byte`. Am I missing some motivation for returning `[]byte`?
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGjqqfAcRLtY4FMIKD:-LvGjqqfAcRLtY4FMIKE:b-9g5tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L224)):*
> ```Go
> 	r, err := db.GetEncryptionRegistries()
> 	require.NoError(t, err)
> 	fmt.Printf("FileRegistry:\n%s\n\n", r.FileRegistry)
> ```

Perhaps change to `t.Logf` if you want to leave in.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGk_-kAB-vm6PzZg11:-LvGk_-lBB2C0yEjAOD1:b-6x0byk) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L225)):*
> ```Go
> 	require.NoError(t, err)
> 	fmt.Printf("FileRegistry:\n%s\n\n", r.FileRegistry)
> 	fmt.Printf("KeyRegistry:\n%s\n\n", r.KeyRegistry)
> ```

Can we scan the `KeyRegistry` to make sure that `keyFile128` is not present? I'm thinking of something like `bytes.Contains(r.KeyRegistry, keyFile128)`. You could verify this catches a bug by changing `getScrubbedRegistry` to not clear the key.
___
*[pkg/storage/engine/pebble.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGhGxP3OwD90qdJNne:-LvGhGxP3OwD90qdJNnf:b-nxwhyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L273)):*
> ```Go
> // EncryptionStatsHandler provides encryption related stats.
> type EncryptionStatsHandler interface {
> 	// Returns a serialized enginepbccl::EncryptionStatus
> ```

Nit: `s/enginepbccl::/enginepbccl./g`. Also, I think we have a linter that will complain about the lack of trailing punctuation.
___
*[pkg/storage/engine/pebble.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGfxJF3PDlpz7SBdJJ:-LvGfxJF3PDlpz7SBdJK:bw8wdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L281)):*
> ```Go
> 	// Returns the enum value of the encryption type.
> 	GetActiveStoreKeyType() int32
> 	// Returns the KeyId embedded in the serialized EncryptionSettings.
> ```

Nit: `s/KeyId/KeyID/g`
___
*[pkg/storage/engine/pebble.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGhnyJ0y94TVvAMHN_:-LvGhnyJ0y94TVvAMHNa:bf36n2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L665)):*
> ```Go
> func (p *Pebble) GetEnvStats() (*EnvStats, error) {
> 	// TODO(sumeer): make the stats complete. There are no bytes stats. The TotalFiles is missing
> 	// files that are not in the registry (from before encryption was enabled).
> ```

I think you can get the byte and file stats via `pebble.DB.Metrics()`, though I see that's not the approach taken with the C++ code. The one downside to using `pebble.DB.Metrics()` is that it only accounts for live sstables, not ones which are not used by the current version but haven't been deleted due to being pinned by an iterator. https://github.com/cockroachdb/pebble/issues/49#issuecomment-561148090 discusses fixing that limitation. My preference is to use whatever `pebble.DB.Metrics()` provides, fixing or extending those metrics as necessary to be usable here. (This doesn't have to be part of this PR).

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42943)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgTXKA_VmErWMmHIL:-LvLtlUFEBD-hYFvv-Os:b-lubodg) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L205)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than a separate struct, I would have just hung the methods needed by `EncryptionStatsHandler` off of `encryptedFS`. Then `newEncryptedEnv` would `return dataFS, dataFS, nil`.
</blockquote></details>

The `dataFS` returned does not have direct access to the `DataKeyManager` -- it would need to peer inside its `FileCipherStreamCreator` (though that seems normal in Go), and more importantly getting to the `StoreKeyManager` is even more involved `dataFS.streamCreator.keyManager.fs.streamCreator.keyManager` and requires casting the `vfs.FS` inside the first key manager to an `encryptedFS`.  
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgsRJ-EFN0cnWRJsy:-LvLvElTAEsi0o6VIIqe:b1a96ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L222)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

All of these `[]byte` casts make me suspect that these methods should be returning `string` instead of `[]byte`. Am I missing some motivation for returning `[]byte`?
</blockquote></details>

I went back and forth and am looking for the idiomatic way -- `[]byte` allows me to return `nil` while `string` makes me return the empty string. Former seemed cleaner. But the nil case is the one with an error so no one should look at the empty string in that case. Thoughts?
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGjqqfAcRLtY4FMIKD:-LvLwk3z1jeo9qKMJUO9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L224)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps change to `t.Logf` if you want to leave in.
</blockquote></details>

Done.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGk_-kAB-vm6PzZg11:-LvLyLcMAh3dipeApVv2:biismrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L225)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can we scan the `KeyRegistry` to make sure that `keyFile128` is not present? I'm thinking of something like `bytes.Contains(r.KeyRegistry, keyFile128)`. You could verify this catches a bug by changing `getScrubbedRegistry` to not clear the key.
</blockquote></details>

Good idea. But this is just the scrubbed `DataKeysRegistry` proto which never contains the store keys (those stay in the user supplied files). I can enhance the test later (as part of the TODO) to actually grab the full `DataKeysRegistry` and see if any of the data keys have accidentally made it to this string. I tried to just use the "key:" string, but the proto map type uses that too.
___
*[pkg/storage/engine/pebble.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGhGxP3OwD90qdJNne:-LvLw3yvBqnd70jUl7iv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L273)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/enginepbccl::/enginepbccl./g`. Also, I think we have a linter that will complain about the lack of trailing punctuation.
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGfxJF3PDlpz7SBdJJ:-LvLw6Cx8DYdr_pM1DIb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L281)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `s/KeyId/KeyID/g`
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGhnyJ0y94TVvAMHN_:-LvMACs-3OZstW6T0h65:b-8wt99m) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L665)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you can get the byte and file stats via `pebble.DB.Metrics()`, though I see that's not the approach taken with the C++ code. The one downside to using `pebble.DB.Metrics()` is that it only accounts for live sstables, not ones which are not used by the current version but haven't been deleted due to being pinned by an iterator. https://github.com/cockroachdb/pebble/issues/49#issuecomment-561148090 discusses fixing that limitation. My preference is to use whatever `pebble.DB.Metrics()` provides, fixing or extending those metrics as necessary to be usable here. (This doesn't have to be part of this PR).
</blockquote></details>

Ack. One question is how these `EnvStats` are used and whether one needs consistency (for example) between `TotalFiles` and `ActiveKeyFiles` which would mean one should not derive them from different sources. `FileStats::GetFiles()` goes to the extent of disabling file deletions, so the RocksDB code is aiming for consistency.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-:-LvMHR0r2vKEdnVK0Nb_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgTXKA_VmErWMmHIL:-LvMGafR0AXeHlfSefq6:b4o4t18) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L205)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The `dataFS` returned does not have direct access to the `DataKeyManager` -- it would need to peer inside its `FileCipherStreamCreator` (though that seems normal in Go), and more importantly getting to the `StoreKeyManager` is even more involved `dataFS.streamCreator.keyManager.fs.streamCreator.keyManager` and requires casting the `vfs.FS` inside the first key manager to an `encryptedFS`.  
</blockquote></details>

Ack. Ok.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgsRJ-EFN0cnWRJsy:-LvMGby6AtMrmTVS4tsj:b294npc) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L222)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I went back and forth and am looking for the idiomatic way -- `[]byte` allows me to return `nil` while `string` makes me return the empty string. Former seemed cleaner. But the nil case is the one with an error so no one should look at the empty string in that case. Thoughts?
</blockquote></details>

Guess this is a border case. I'd go with returning `string`.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGk_-kAB-vm6PzZg11:-LvMHDpQ01s7xTQtkC2N:byqzgw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L225)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Good idea. But this is just the scrubbed `DataKeysRegistry` proto which never contains the store keys (those stay in the user supplied files). I can enhance the test later (as part of the TODO) to actually grab the full `DataKeysRegistry` and see if any of the data keys have accidentally made it to this string. I tried to just use the "key:" string, but the proto map type uses that too.
</blockquote></details>

Ack on this being the scrubbed data right now. I was suggesting you temporarily change `KeyRegistry` to return the unscrubbed data, add the check and verify it catches the bug, and then revert to the scrubbed data.
___
*[pkg/storage/engine/pebble.go, line 665 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGhnyJ0y94TVvAMHN_:-LvMGqsrAd_oaN-N02L_:b-tvbl71) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/storage/engine/pebble.go#L665)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ack. One question is how these `EnvStats` are used and whether one needs consistency (for example) between `TotalFiles` and `ActiveKeyFiles` which would mean one should not derive them from different sources. `FileStats::GetFiles()` goes to the extent of disabling file deletions, so the RocksDB code is aiming for consistency.
</blockquote></details>

I find the disabling of file deletions in the C++ version a bit of a wart. It also tickled a bug in RocksDB. I believe these stats are only used for observability purposes.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42943)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/encrypted_fs.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGgsRJ-EFN0cnWRJsy:-LvayK269PNXraUKV5UB:b-vloehf) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L222)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Guess this is a border case. I'd go with returning `string`.
</blockquote></details>

I've changed `GetActiveDataKeyID()` and `GetKeyIDFromSettings()` to return string. The other two I left as `[]byte` since they eventually need to be converted to `[]byte` anyway because of the context they are used in.
___
*[pkg/ccl/storageccl/engineccl/encrypted_fs_test.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42943#-LvGk_-kAB-vm6PzZg11:-LvazMyW7v9g_eHbQ_3F:b287uky) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e8302790e3b40eaf8902e6ae4bbbffc8d6de38/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L225)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack on this being the scrubbed data right now. I was suggesting you temporarily change `KeyRegistry` to return the unscrubbed data, add the check and verify it catches the bug, and then revert to the scrubbed data.
</blockquote></details>

Ah, I made a confusing statement. I understood what you were suggesting, but the issue is that the `GetEncryptionRegisteries()` method works with a `DataKeysRegistry` proto which never contains the store keys (even unscrubbed). So the unscrubbed version only contains the random data keys -- I thought I could manage with looking for the "key:" string, but it occurs in 2 ways, one for the actual key and the other in the proto map type, so that doesn't work either. I've updated the TODO to add a proper test for this too.

**Pull request merged**
