### PR TITLE
release: bump version to v24.2.0-alpha.1

### PR DESCRIPTION
**Pull request by rail**
Epic: none
Release note: None

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]

**Comment by rail** [comment]
bors r=andyyang890

**Review by rickystewart — APPROVED** [review]

**Comment by rail** [comment]
bors retry

**Comment by rail** [comment]
bors r=andyyang890

**Comment by rail** [comment]
bors retry

**Comment by srosenberg** [comment]
FYI, we seem to be missing doc links for 24.2: https://github.com/cockroachdb/cockroach/issues/126237

**Comment by rail** [comment]
I am guessing the docs will be up when we publish alpha.1

**Pull request merged**
