### PR TITLE
logictest: introduce a separate matcher for floats

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds another type annotation `F` intended to be used for
floating point numbers which have a separate matcher that allows for
some deviation in the precision. Namely, the matcher checks that the
expected and the actual numbers match in 15 significant decimal
digits. Note that I think the matching algorithm introduces some
rounding errors, so it might not work perfectly in all scenarios, yet it
should be good enough in rare test cases when we need it.

Informs: #55268.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbCQbgANoJGeqOT5zy:-MJbCQbgANoJGeqOT5zz:b-vfcehd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L167)):*
> ```Go
> //        to string (arrays, timestamps, etc.).
> //      - I for integer
> //      - F for floating point (matches 15 significant decimal digits)
> ```

Add a link to the postgres docs here.
___
*[pkg/sql/logictest/logic.go, line 2513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbMdIEDKTjCpmHPGKP:-MJbMdIEDKTjCpmHPGKQ:b2a82ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2513)):*
> ```Go
> 							if *flexTypes && (valT == reflect.Int64) {
> 								t.signalIgnoredError(
> 									fmt.Errorf("result type mismatch: expected R, got %T", val), query.pos, query.sql,
> ```

nit: update
___
*[pkg/sql/logictest/logic.go, line 2630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbNWF09gsrw8qcz5d_:-MJbNWF09gsrw8qcz5da:bnx600y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2630)):*
> ```Go
> 
> 	if query.checkResults {
> 		resultsMatch := reflect.DeepEqual(query.expectedResults, actualResults)
> ```

It feels wrong to do a full equality check and then check for float columns if it fails. If we're just checking strings, why do we need to do a `DeepEqual`? I would iterate over the results in order and change the equality check based on the type.
___
*[pkg/sql/logictest/logic.go, line 2656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbNPJI0FGV31pGZTCa:-MJbNPJI0FGV31pGZTCb:b-28k63) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2656)):*
> ```Go
> 			resultsMatch = true
> 			for i, colT := range query.colTypes {
> 				expected, actual := query.expectedResults[i], actualResults[i]
> ```

I would extract this logic into a separate function which you might be able to unit test (why not?). This'll also make this main body of code easier to read.
___
*[pkg/sql/logictest/logic.go, line 2685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbO4wr76_ZU6iVsUGS:-MJbO4wr76_ZU6iVsUGT:b9yxqjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2685)):*
> ```Go
> 						}
> 						expFloat = normalize(expFloat)
> 						actFloat = normalize(actFloat)
> ```

Won't this return that `123.45` and `12.345` are equal since they'll both be normalized to `1.2345`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/logic.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbCQbgANoJGeqOT5zy:-MJbqI2b2qjm16W363l4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L167)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a link to the postgres docs here.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 2630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbNWF09gsrw8qcz5d_:-MJbzTiiANlaocFW5HPc:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2630)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels wrong to do a full equality check and then check for float columns if it fails. If we're just checking strings, why do we need to do a `DeepEqual`? I would iterate over the results in order and change the equality check based on the type.
</blockquote></details>

Good idea, done.
___
*[pkg/sql/logictest/logic.go, line 2656 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbNPJI0FGV31pGZTCa:-MJbzWmD16XlstxCze9k:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2656)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would extract this logic into a separate function which you might be able to unit test (why not?). This'll also make this main body of code easier to read.
</blockquote></details>

Good idea, done.
___
*[pkg/sql/logictest/logic.go, line 2685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJbO4wr76_ZU6iVsUGS:-MJbvl2NA8-oe1KPegz3:bmysml1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa818d7062f3e44fcb4a0c8d35e1f3a42ed61614/pkg/sql/logictest/logic.go#L2685)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Won't this return that `123.45` and `12.345` are equal since they'll both be normalized to `1.2345`?
</blockquote></details>

Yes, you're right, good catch.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 2705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJg7H8B9xHxGfTZ7kAb:-MJg7H8CBlbBbbG-vT0W:bv2xksr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d2c054fd3e9e8c6a7d73f4e464ebd32ee82b8a2/pkg/sql/logictest/logic.go#L2705)):*
> ```Go
> 	}
> 	if expected == 0 || actual == 0 {
> 		return expected == actual, nil
> ```

Is this correct? What about if expected is `0` and actual is `0.0000000000000000000000001`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55530)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/logic.go, line 2705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJg7H8B9xHxGfTZ7kAb:-MJglSJa3HD5gpfjLWXX:b1vu78h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d2c054fd3e9e8c6a7d73f4e464ebd32ee82b8a2/pkg/sql/logictest/logic.go#L2705)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this correct? What about if expected is `0` and actual is `0.0000000000000000000000001`?
</blockquote></details>

I believe these should be treated as different. The question is what Postgres refers to as `15 decimal digits precision` - I believe it means 15 *significant decimal digits* are correct, and in your example we have only 1 significant digit in the right number if I'm not mistaken.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-:-MJgoC5b3-D4POZu8TWV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 2705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55530#-MJg7H8B9xHxGfTZ7kAb:-MJgo8TK7BNjrSEZHZUx:b-j2fohf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d2c054fd3e9e8c6a7d73f4e464ebd32ee82b8a2/pkg/sql/logictest/logic.go#L2705)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I believe these should be treated as different. The question is what Postgres refers to as `15 decimal digits precision` - I believe it means 15 *significant decimal digits* are correct, and in your example we have only 1 significant digit in the right number if I'm not mistaken.
</blockquote></details>

I think you're right.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
