### PR TITLE
contextutil: preserve contextutil.TimeoutError details across the network

### PR DESCRIPTION
**Pull request by knz**
Found missing by @tbg here:
https://github.com/cockroachdb/cockroach/issues/66354#issuecomment-859586223

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thank you for jumping on this! This can probably use some backports, too.

**Comment by knz** [comment]
bors r=tbg

**Comment by knz** [comment]
does this need a backport to 20.1 too?

**Comment by tbg** [comment]
I think so

**Pull request merged**
