### PR TITLE
tree: fix panic when using UDTs for GENERATED ... IDENTITY columns

### LINKED ISSUE #72804: sql: interface conversion error with GENERATED ALWAYS AS IDENTITY
By following the official website, I found out that we have added support for GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY (seq_option) syntax under CREATE TABLE in v21.2.0-beta.1
I accidentally use a type that doesn't exist, when use this new feature.

Environment:
 - CockroachDB version [v21.2.0-rc.3]
 - Server OS: [centos/linux]
 - Client app [ `cockroach sql`]

Partial Error Messages：

```
root@localhost:26257/defaultdb> create table if not exists tb1 (id myType GENERATED ALWAYS AS IDENTITY,name string);
* interface conversion: tree.ResolvableTypeReference is *tree.UnresolvedObjectName, not *types.T
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:658
*   | [...repeated from below...]
* Wraps: (2) while executing: SHOW SYNTAX '_'
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:658
*   | runtime.gopanic
*   |     /usr/local/go/src/runtime/panic.go:1038
*   | runtime.panicdottypeE
*   |     /usr/local/go/src/runtime/iface.go:261
*   | runtime.panicdottypeI
*   |     /usr/local/go/src/runtime/iface.go:271
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewColumnTableDef
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/create.go:557
*   | github.com/cockroachdb/cockroach/pkg/sql/parser.(*sqlParserImpl).Parse
*   |     sql-gen.y:6711
*   | github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parse
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:195
*   | github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).parseWithDepth
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:175
*   | github.com/cockroachdb/cockroach/pkg/sql/parser.Parse
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:247
*   | github.com/cockroachdb/cockroach/pkg/sql/parser.RunShowSyntax
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/show_syntax.go:55
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runShowSyntax
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1636
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).runObserverStatement
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1616
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1692
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1694
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1616
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:660
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
*   |     /home/mosquito/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:648
*   | runtime.goexit
*   |     /usr/local/go/src/runtime/asm_amd64.s:1581
* Wraps: (4) interface conversion: tree.ResolvableTypeReference is *tree.UnresolvedObjectName, not *types.T
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) *runtime.TypeAssertionError
*

```

### PR DESCRIPTION
**Pull request by otan**
Release note (bug fix): Fix a bug where GENERATED ... IDENTITY would
panic when using a non-int value during table creation.

Resolves #72804

### CODE REVIEW

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/sem/tree/create.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72966#-MoqX8-k0B0rTHZJdXI3:-MoqX8-k0B0rTHZJdXI4:btw8tag) ([raw file](https://github.com/cockroachdb/cockroach/blob/56dc210a32de4a0b4ad391283bff2fda4efd0b02/pkg/sql/sem/tree/create.go#L555)):*
> ```Go
> 				return nil, pgerror.Newf(
> 					pgcode.InvalidParameterValue,
> 					"identity column type must be INT, INT2, or INT4",
> ```

My bad, the type can also be `INT8`. Could you change it to `"identity column type must be INT, INT2, INT4 or INT8"`?

**Review by ZhouXing19 — APPROVED** [review]
LGTM, thanks!

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

**Review by rafiss — APPROVED** [review]

**Comment by otan** [comment]
bors r=ZhouXing19

**Pull request merged**
