### PR TITLE
rpc: log RPC heartbeat errors at error level

### PR DESCRIPTION
**Pull request by erikgrinaker**
Currently heartbeat failures are logged at level INFO. This makes it hard to identify them as anomalies when scanning the log files. This commit changes the level to ERROR to make them stand out during troubleshooting.

Epic: none
Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
RPC heartbeat failures due to e.g. network latencies can cause clusters to completely fall apart. Currently, there is no clear indication of this happening at all in the default `cockroach.log`. These shouldn't be hidden away in the health log at info level.

**Comment by knz** [comment]
I am not objecting to your change, but the PR description as-is is factually incorrect. Try this:

"Currently heartbeat failures are logged at level INFO. This makes it hard to identify them as anomalies when scanning the log files. This commit changes the level to ERROR to make them stand out during troubleshooting."

**Comment by erikgrinaker** [comment]
I see, I'll reword the message.

**Comment by knz** [comment]
You can move your commit message under "Release note (cli change):" since we document changes to non-DEV logging output.

**Review by knz — APPROVED** [review]

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
