### PR TITLE
sql: fix panic in insert on conflict do update

### LINKED ISSUE #32834: sentry: conn_executor.go:639: panic while executing 1 statements: UPSERT INTO _(_, _) VALUES ($1, $2), (__more4000__): caused by <redacted>
https://sentry.io/cockroach-labs/cockroachdb/issues/793275147/?referrer=webhooks_plugin

conn_executor.go:639: panic while executing 1 statements: UPSERT INTO _(_, _) VALUES ($1, $2), (__more4000__): caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 309, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1169, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 746, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 253, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'in_app': True, u'lineno': 602, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'in_app': True, u'lineno': 730, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'Start', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'in_app': True, u'lineno': 139, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go'}, {u'function': u'startExec', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'in_app': True, u'lineno': 645, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'walkPlan', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'in_app': True, u'lineno': 65, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'visit', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor)', u'in_app': True, u'lineno': 101, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'visitInternal', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor)', u'in_app': True, u'lineno': 543, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal', u'in_app': True, u'lineno': 134, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.startExec', u'in_app': True, u'lineno': 640, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'startExec', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode)', u'in_app': True, u'lineno': 173, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go'}, {u'function': u'BatchedNext', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*upsertNode)', u'in_app': True, u'lineno': 331, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/upsert.go'}, {u'function': u'atBatchEnd', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter)', u'in_app': True, u'lineno': 417, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go'}, {u'function': u'panicslice', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 35, u'filename': u'runtime/panic.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:639: panic while executing 1 statements: UPSERT INTO _(_, _) VALUES ($1, $2), (__more4000__): caused by <redacted>

### PR DESCRIPTION
**Pull request by BramGruneir**
There was an assumption that the row inserter and row updater had the same
columns in the same order and if that wasn't the case row inserter's columns
would be larger.

This assumption is incorrect, so to fix it, when storing the existing rows
(which are used to see if they conflicts with other rows further on in the
statement) instead of storing the row used for inputs, convert the rows
directly to those required by the row updater.

Fixes #32834.

Release note (bug fix): Fixed an issue in which if a nullable column wasn't
supplied in an INSERT ON CONFLICT DO UPDATE statement, it may cause a panic.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Very well done! Thank you. Just a nit about memory allocations.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-:-LU5OO1l-cRNhEpZ8hOK:b-y7kmqu)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 692 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU5O-kU2tRzSkSP6jRG:-LU5O-kV3VAGkdMtasNo:b-z99d9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7444fcda275eabe9cf437d8ac9ef652f8f5d94a2/pkg/sql/tablewriter_upsert.go#L692)):*
> ```Go
> 	// We need to convert the new row to match the fetch columns required for
> 	// checking if there is a conflict.
> 	cleanedRow := make(tree.Datums, len(tu.fetchColIDtoRowIndex))
> ```

pre-allocate the `cleanedRow` slice in the tableUpserter.
___
*[pkg/sql/tablewriter_upsert.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU5OEvW2qmv4KZCwWRF:-LU5OEvW2qmv4KZCwWRG:bwyqc2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7444fcda275eabe9cf437d8ac9ef652f8f5d94a2/pkg/sql/tablewriter_upsert.go#L701)):*
> ```Go
> 		}
> 	}
> 	return append(existingRows, cleanedRow)
> ```

you can double check that the passed `existingRows` has sufficient capacity and is reusedin the caller? Perhaps pre-allocate with sufficient capacity.

**Review by BramGruneir — COMMENTED** [review]
TRTR and PTAL!

I added a second commit here that converts existingRows to a rowContainer.  It's a cleaner design on top of actually having some form of memory accounting.

I added it as a second commit just in case backporting this larger change is difficult.  I'd rather get a panic fix in at least if this one can't be backported easily.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-:-LU73xwu4i1MRGGrgpsw:b-svdaj4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 692 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU5O-kU2tRzSkSP6jRG:-LU6p-uM6WQHmNiL1Db3:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7444fcda275eabe9cf437d8ac9ef652f8f5d94a2/pkg/sql/tablewriter_upsert.go#L692)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

pre-allocate the `cleanedRow` slice in the tableUpserter.
</blockquote></details>

done
___
*[pkg/sql/tablewriter_upsert.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU5OEvW2qmv4KZCwWRF:-LU73ukP-bgcK-1pwTSD:b-eb1ukz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7444fcda275eabe9cf437d8ac9ef652f8f5d94a2/pkg/sql/tablewriter_upsert.go#L701)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can double check that the passed `existingRows` has sufficient capacity and is reusedin the caller? Perhaps pre-allocate with sufficient capacity.
</blockquote></details>

I went one better.  Turned it into a rowContainer.

**Review by knz — COMMENTED** [review]
:+1: on cleanedRows. I think you can reuse the rowcontainer across batches instead of creating a new one.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-:-LU75VPn3o7OIKCcFBDT:b1rclc7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 340 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU75Ps39YUmfIiXAg7s:-LU75Ps39YUmfIiXAg7t:b-yt3ji6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7ea69287d19db1887b74e7f21578b4334b01f/pkg/sql/tablewriter_upsert.go#L340)):*
> ```Go
> 		return err
> 	}
> 	existingRows := sqlbase.NewRowContainer(
> ```

you can reuse the row container too! with its .Clear() method.

**Review by BramGruneir — COMMENTED** [review]
Reused the rowContainer too now!  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-:-LU7S15X419UO30Q1uBv:bxurndi)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 340 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LU75Ps39YUmfIiXAg7s:-LU7RufjCIVEDpAS8tgB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e7ea69287d19db1887b74e7f21578b4334b01f/pkg/sql/tablewriter_upsert.go#L340)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can reuse the row container too! with its .Clear() method.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LUBI-VE4kUmn0Y7gPf6:-LUBI-VE4kUmn0Y7gPf7:bnm6ljb) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b28838716dfd513d95abf58000cc1f0f532e89/pkg/sql/tablewriter_upsert.go#L917)):*
> ```Go
> 
> 		pkToRowIdx[string(rowPrimaryKey)] = tu.existingRows.Len()
> 		tu.existingRows.AddRow(ctx, row)
> ```

need to return the error here

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33245)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_upsert.go, line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33245#-LUBI-VE4kUmn0Y7gPf6:-LUBOSnb3GycaeNWqE46:bkj8hqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b28838716dfd513d95abf58000cc1f0f532e89/pkg/sql/tablewriter_upsert.go#L917)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

need to return the error here
</blockquote></details>

nice catch.  Done.

**Pull request merged**
