### PR TITLE
vendor: update pprof

### PR DESCRIPTION
**Pull request by nvb**
Picks up:
- https://github.com/google/pprof/pull/412
- https://github.com/google/pprof/pull/414

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

looks like you also bumped readline, is that just fallout from the pprof bump?

**Comment by nvanbenschoten** [comment]
> looks like you also bumped readline, is that just fallout from the pprof bump?

Yes, exactly. I was also confused about that.

**Comment by benesch** [comment]
Ugh, you'll need to regenerate your Gopkg.toml here with the new revision of #28831. Dep has decided that there are a bunch of new fields that belong in Gopkg.lock now.

**Comment by nvanbenschoten** [comment]
Updated to include https://github.com/google/pprof/pull/414 as well. PTAL!

**Comment by benesch** [comment]
LGTM, but gosh it's sad that we have two readline implementations now.

**Comment by nvanbenschoten** [comment]
https://github.com/google/pprof/blob/d723c7237b64c7871a69e4c411acb04245bcd23d/pprof.go#L36-L40

> // This is contained in pprof.go to avoid adding the readline
// dependency in the vendored copy of pprof in the Go distribution,
// which does not use this file.

Welp... that didn't help.

I wonder if there's some incatation of `dep` magic that will allow us to avoid importing that entire package. We don't use it. Time to learn dep.

**Comment by nvanbenschoten** [comment]
> We don't use it. Time to learn dep.

Or we can just stop requiring it: 

https://github.com/cockroachdb/cockroach/blob/33092de7061eacb60e45a56c1a5ad7829c839e0b/Gopkg.toml#L7

**Comment by benesch** [comment]
Oh, yeah, we only depend on github.com/google/pprof/driver and github.com/google/pprof/profile, right? Then I think just dropping that line from Gopkg.toml will do the right thing and only bring in those two packages!

**Comment by nvanbenschoten** [comment]
Ah ok, we require it because we compile pprof into a utility binary.

https://github.com/cockroachdb/cockroach/blob/33092de7061eacb60e45a56c1a5ad7829c839e0b/Makefile#L291

I'm not sure there's much we can do then @benesch.

**Comment by benesch** [comment]
I think we should maybe nuke that; I imagine most folks are just using the
web UI these days. But feel free not to spend any more time on this. I feel
much better knowing that chyzer/readline isn't actually getting linked into
the cockroach binary.

**Comment by nvanbenschoten** [comment]
> I think we should maybe nuke that

Done!

**Comment by benesch** [comment]
LGTM! Thank you!!

**Pull request merged**
