### PR TITLE
cli: make all client commands recognize `--url`

### LINKED ISSUE #4984: cli/conn+config: all client commands should accept `--url`
Currently CLI commands that use the SQL driver under the hood (sql, zone, user) accept a `--url` parameter, but those that use the KV (or other) API (range, node, kv, exterminate, quit) do not. Commands in the latter group should accept a URL too and parse the necessary fields from it so that users don't have to know about these implementation details. (see discussion in #4957)

### LINKED ISSUE #29567: cli: `cockroach demo` writes to `cockroach-data` (logs)
`cockroach demo` was meant, I thought, to be diskless. Except that it writes to the cockroach-data directory in the current directory for logs.

Not sure that's a feature or a bug -- @jordanlewis, thoughts?

However something needs to be done because it clobbers the source tree during tests (in the `Example_demo` I recently added). I'll look into the test case.

### PR DESCRIPTION
**Pull request by knz**
Fixes #4984.
Fixes #29567.

Prior to this patch, the client commands using a SQL connection under
the hood would accept `--url` in addition to discrete
parameters (`--host`, `--port`, etc); however, non-SQL client commands
did not recognize `--url`.

This was causing UX pain/fatigue because users had to remember which
commands accept a URL and which commands do not. It also made
automation more difficult.

(For context, it was not reasonable to propose to users to _never_ use
`--url` and always stick to discrete flags, because some parameters
can only be specified via `--url`, for example the application name.)

This patch resolves the UX problem by ensuring that all client
commands accept `--url`, in addition to the discrete flags. This
effectively makes all CockroachDB commands (*) homogeneous/consistent
wrt their connection flags.

The value provided via `--url` and via the other discrete flags mesh
as follows:

```
//            flags parser
//                /    \
//         .-----'      `-------.
//         |                    |
//       --url               --host, --port, etc
//         |                    |
//   urlParser.Set()            |
//         |                    |
//         `-------.    .-------'
//                  \  /
//          sqlCtx/cliCtx/baseCtx
//                   |
//                  / \
//         .-------'   `--------.
//         |                    |
//         |                    |
//      non-SQL           makeClientConnURL()
//     commands                 |
//    (quit, init, etc)         |
//                          SQL commands
//                        (user, zone, etc)
```

(*) except for `cockroach workload`, which still has the status an
adopted appendage with its separate argument handling.

Release note (cli change): All `cockroach` client sub-commands (except
for `cockroach workload`) now support the `--url` flag.

### CODE REVIEW

**Review by a-robinson — CHANGES_REQUESTED** [review]
Very nice change! Just a few minor questions/comments.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-:-LL_eB_Q9ugi6TQU2Gnv:btvd7rz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/client_url.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_UgLK0nXCiRJuB91U:-LL_UgLL-ZGH48bVM3x9:b-8ry941) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L96)):*
> ```Go
> 	// registered/supported by lib/pq. Internally, lib/pq supports
> 	// both.
> 	if parsedURL.Scheme != "postgresql" && parsedURL.Scheme != "postgres" {
> ```

Maybe I'm misremembering, but hadn't we started accepting (or wanted to start accepting) URLs without the postgres prefix, such that just `host[:port]` was enough to connect so you could easily copy an address from the UI and use it as a URL?
___
*[pkg/cli/client_url.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_aLC48iuB-3-906iF:-LL_aLC48iuB-3-906iG:b-1heawr) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L110)):*
> ```
> 	// If a client command does not use makeClientConnURL() it also
> 	// will not accept --user and so any attempt to set either user
> 	// or password here will produce an error.
> ```

I'm curious if there's a particular reason to return an error here rather than just ignoring the provided username?
___
*[pkg/cli/client_url.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_b6Az2MyG5iOfyNDa:-LL_b6Az2MyG5iOfyNDb:b-m3u8mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L145)):*
> ```Go
> 		f := u.cmd.Flags().Lookup(cliflags.Database.Name)
> 		if f == nil {
> 			return fmt.Errorf("command %q does not accept a database name", u.cmd.Name())
> ```

Do you think this error (or the similar one above for user/password details) will be clear to everyone? I can imagine scenarios where someone just copies/pastes a URL they saw in a different command and uses it in a command that doesn't support the same parameters, not necessarily realizing what we're talking about when we say that database names aren't accepted.
___
*[pkg/cli/client_url.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_bwMH01w5RJiEMqDo:-LL_bwMH01w5RJiEMqDp:by75au) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L170)):*
> ```Go
> 		case "disable":
> 			if !hasInsecure {
> 				return fmt.Errorf("command %q does not support insecure connections", u.cmd.Name())
> ```

Which client commands support a URL but not insecure connections?
___
*[pkg/cli/client_url.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_ciltDd9sUstBBFkj:-LL_ciltDd9sUstBBFkk:bmf0s22) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L203)):*
> ```Go
> 				// certificate directory. It also checks that the file names are those
> 				// expected by the certificate manager.
> 				tryCertsDir := func(optName, expectedFilename string) error {
> ```

Why is this code being added in this PR? What problem is it solving?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/client_url.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_UgLK0nXCiRJuB91U:-LLa3vMRE4_iC0X1Okst:b-t5j9dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L96)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Maybe I'm misremembering, but hadn't we started accepting (or wanted to start accepting) URLs without the postgres prefix, such that just `host[:port]` was enough to connect so you could easily copy an address from the UI and use it as a URL?
</blockquote></details>

we support this but via the `--host` argument (e.g. `--host=foo:123`) not `--url`. 
___
*[pkg/cli/client_url.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_aLC48iuB-3-906iF:-LLa43199Qv6q4XHJf9H:b-ucd378) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L110)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> ```
> 	// If a client command does not use makeClientConnURL() it also
> 	// will not accept --user and so any attempt to set either user
> 	// or password here will produce an error.
> ```

I'm curious if there's a particular reason to return an error here rather than just ignoring the provided username?
</blockquote></details>

The general rule that I applied here is that we should not accept information that the user may intend to be meaningful and then ignore it silently.

(The rule is one grown from past experience with software evolution: if/when we want to give meaning to these bits in the future, we would have a problem doing so if users also in the meantime learned to put random garbage in these bits and expecting us to ignore the garbage).

I could be convinced to turn this into a stern warning instead of an error. What do you think?
___
*[pkg/cli/client_url.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_b6Az2MyG5iOfyNDa:-LLa4vc842e9gR2CIuH_:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L145)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Do you think this error (or the similar one above for user/password details) will be clear to everyone? I can imagine scenarios where someone just copies/pastes a URL they saw in a different command and uses it in a command that doesn't support the same parameters, not necessarily realizing what we're talking about when we say that database names aren't accepted.
</blockquote></details>

ditto above
___
*[pkg/cli/client_url.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_bwMH01w5RJiEMqDo:-LLa4xFi9pRpjejbUEwY:b-y18u89) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L170)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Which client commands support a URL but not insecure connections?
</blockquote></details>

yeah I was confused. Removed.
___
*[pkg/cli/client_url.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_ciltDd9sUstBBFkj:-LLa5FUs0jhNAaWV3ak9:bnolf9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L203)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why is this code being added in this PR? What problem is it solving?
</blockquote></details>

I added an explanatory comment. What do you think?

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-:-LLaI5YVEGEaL3OV153z:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/client_url.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_UgLK0nXCiRJuB91U:-LLaF-ty3M-zkt3VywW6:b-8kqorz) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L96)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

we support this but via the `--host` argument (e.g. `--host=foo:123`) not `--url`. 
</blockquote></details>

That's it, thanks!
___
*[pkg/cli/client_url.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_aLC48iuB-3-906iF:-LLaGXao5qDtO1-HuH_-:bykwqfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L110)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The general rule that I applied here is that we should not accept information that the user may intend to be meaningful and then ignore it silently.

(The rule is one grown from past experience with software evolution: if/when we want to give meaning to these bits in the future, we would have a problem doing so if users also in the meantime learned to put random garbage in these bits and expecting us to ignore the garbage).

I could be convinced to turn this into a stern warning instead of an error. What do you think?

</blockquote></details>

Seems reasonable. I'm curious if @mberhault has thoughts on it, but it sounds good to me.
___
*[pkg/cli/client_url.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_b6Az2MyG5iOfyNDa:-LLaGiJN4CfrxS8LEZuM:b-9jhq7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L145)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto above
</blockquote></details>

I don't think "ditto above" addresses my point.

Consider someone who copies a URL from some doc somewhere and runs:

```
cockroach zone set -f zone.yaml --url postgres://localhost/bank
```

And then gets the error `command "zone set" does not accept a database name`. Where's the database name?

Saying `command %q does not accept a database name; %q was specified` should clarify things.
___
*[pkg/cli/client_url.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_ciltDd9sUstBBFkj:-LLaHps55_vQRRQgRzqs:b-jmdw91) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L203)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I added an explanatory comment. What do you think?
</blockquote></details>

Makes sense, thanks. The comment would be a little better if it specified why we're using the certificate manager instead of the certificate handler in lib/pq, but otherwise it's great.

@mberhault might catch something important that I didn't in this code, but I don't see any issues with it.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/client_url.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_aLC48iuB-3-906iF:-LLbOUql9ym8sf4WsNos:b-s0xvfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L110)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Seems reasonable. I'm curious if @mberhault has thoughts on it, but it sounds good to me.
</blockquote></details>

All right, turned this into a warning.
___
*[pkg/cli/client_url.go, line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_b6Az2MyG5iOfyNDa:-LLbOXOe5_1q0ud56nrh:b-yja3iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L145)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't think "ditto above" addresses my point.

Consider someone who copies a URL from some doc somewhere and runs:

```
cockroach zone set -f zone.yaml --url postgres://localhost/bank
```

And then gets the error `command "zone set" does not accept a database name`. Where's the database name?

Saying `command %q does not accept a database name; %q was specified` should clarify things.
</blockquote></details>

Done, also turned into a warning as per the discussion above.
___
*[pkg/cli/client_url.go, line 203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LL_ciltDd9sUstBBFkj:-LLbOt-z63bJUyYrhFhd:b-rtkc55) ([raw file](https://github.com/cockroachdb/cockroach/blob/98c451e69f4a69010280ff21a0992b9cb15460d2/pkg/cli/client_url.go#L203)):*
> why we're using the certificate manager instead of the certificate handler in lib/pq

There is no good reason for client commands really; the code in lib/pq is less than 50 lines long and could be reused easily. But it would be a large refactoring. I don't know that I can write anything meaningful about this in this comment.

**Comment by knz** [comment]
I think this is more or less done. I'll let it sleep for a day should @mberhault want to raise concerns. Hoping to merge before Friday.

**Review by mberhault — COMMENTED** [review]
I still disagree with the entire idea, but fine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-:-LLdp7mD76HWHkbP7pP7:bbap21i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/base/config.go, line 177 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LLdnTer0XKyKRnZQP1c:-LLdnTer0XKyKRnZQP1d:b53n6x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/577f1402b1b5276da7c35b8485cd32e897dd3bd6/pkg/base/config.go#L177)):*
> ```Go
> 	cfg.SSLCertsDir = DefaultCertsDirectory
> 	cfg.certificateManager = lazyCertificateManager{}
> 	cfg.httpClient = lazyHTTPClient{}
> ```

The HTTP Client is only used in test code. No need to have it here.
___
*[pkg/base/config.go, line 229 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LLdo8oRATHLqeBHYwpU:-LLdo8oRATHLqeBHYwpV:bt5s82k) ([raw file](https://github.com/cockroachdb/cockroach/blob/577f1402b1b5276da7c35b8485cd32e897dd3bd6/pkg/base/config.go#L229)):*
> ```Go
> 		}
> 
> 		if options.Get("sslrootcert") == "" {
> ```

This looks like it breaks the use of `sslmode=require` when using sql commands. When specified, `sslrootcert` is ignored and does not need to be specified.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29467)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/base/config.go, line 177 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LLdnTer0XKyKRnZQP1c:-LLfX1fpDtlnQMK4PXwp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/577f1402b1b5276da7c35b8485cd32e897dd3bd6/pkg/base/config.go#L177)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

The HTTP Client is only used in test code. No need to have it here.
</blockquote></details>

Done.
___
*[pkg/base/config.go, line 229 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/29467#-LLdo8oRATHLqeBHYwpU:-LLfYiY_1eeb2DsDS-E_:b-xqf7bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/577f1402b1b5276da7c35b8485cd32e897dd3bd6/pkg/base/config.go#L229)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

This looks like it breaks the use of `sslmode=require` when using sql commands. When specified, `sslrootcert` is ignored and does not need to be specified.
</blockquote></details>

Good call. Fixed.

**Comment by knz** [comment]
I'll move ahead and merge this -- will pick up the fallout if any.

bors r+

**Comment by knz** [comment]
flaked on #27253, retrying

bors r+

**Pull request merged**
