### PR TITLE
cli/sql: assorted CLI shell and autocompletion bug fixes

### PR DESCRIPTION
**Pull request by knz**
See the individual commits for details.

Epic: CRDB-28893

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
:lgtm_strong: !! Thanks for the fix! I just left nit comments.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-:-NNcE4394qXtebOcSoqR:b-s5oj71)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/comprules/rules.go` line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcB2-SAm8Rg-z0HXhg:-NNcB2-SAm8Rg-z0HXhh:bufslea) ([raw file](https://github.com/cockroachdb/cockroach/blob/5382a573618c7d681c429676bdce27c2b3f85277/pkg/sql/comprules/rules.go#L248)):*
> ```Go
> 	var start, end int
> 	switch {
> 	case c.CursorInToken() && atWord:
> ```

nit: It took me sometime to understand that the `atWord` is the key issue. Could you add a comment for the `compengine.Context.AtWord()` method that `if the cursor is on the whitespace past an ident or a keyword, it will still return true`?  or maybe we can rename the method to `AtOrAtSpaceAfterWord`? 
___
*[`pkg/sql/comprules/rules.go` line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcDohV1kFStYaD9eIy:-NNcDohV1kFStYaD9eIz:bbaumiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d503cee7a5f47045c20d44df7a9a49b78124f01/pkg/sql/comprules/rules.go#L230)):*
> ```Go
> 	atWord := c.AtWord()
> 	sketch := c.Sketch()
> 	isQualified := false
> ```

nit: add a comment for this value or rename it to `isSchemaQualified`?
___
*[`pkg/sql/comprules/rules.go` line 262 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcCZLODWRGK8N6YZM6:-NNcCZLODWRGK8N6YZM7:b-yuwvyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d503cee7a5f47045c20d44df7a9a49b78124f01/pkg/sql/comprules/rules.go#L262)):*
> ```Go
> 
> 	c.Trace("completing for %q (%d,%d), schema: %s", prefix, start, end, schema)
> 	// We only include pg_catalog relations in the following cases:
> ```

nit: does it make sense if we add a notice in the interface saying "note: pg_catalog relations are not included in the following results. To get auto-completion for pg_catalog relations, please type `pg_` and press `tab`. "  ?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96562)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @ZhouXing19)

___
*[`pkg/sql/comprules/rules.go` line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcB2-SAm8Rg-z0HXhg:-NNcPIgn2q3-iZEy6NpK:b5h48az) ([raw file](https://github.com/cockroachdb/cockroach/blob/5382a573618c7d681c429676bdce27c2b3f85277/pkg/sql/comprules/rules.go#L248)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: It took me sometime to understand that the `atWord` is the key issue. Could you add a comment for the `compengine.Context.AtWord()` method that `if the cursor is on the whitespace past an ident or a keyword, it will still return true`?  or maybe we can rename the method to `AtOrAtSpaceAfterWord`? 
</blockquote></details>

Good call. Done, and renamed to `AtWordOrInSpaceFollowingWord()`.
___
*[`pkg/sql/comprules/rules.go` line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcDohV1kFStYaD9eIy:-NNcPDrb-qWjsFJf2ssP:b-h4hobd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d503cee7a5f47045c20d44df7a9a49b78124f01/pkg/sql/comprules/rules.go#L230)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: add a comment for this value or rename it to `isSchemaQualified`?
</blockquote></details>

Done - `hasSchemaPrefix`.
___
*[`pkg/sql/comprules/rules.go` line 262 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96562#-NNcCZLODWRGK8N6YZM6:-NNcRbVF-2FUBdSyeMUX:bswftec) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d503cee7a5f47045c20d44df7a9a49b78124f01/pkg/sql/comprules/rules.go#L262)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: does it make sense if we add a notice in the interface saying "note: pg_catalog relations are not included in the following results. To get auto-completion for pg_catalog relations, please type `pg_` and press `tab`. "  ?
</blockquote></details>

Good idea! But this would need some extra infrastructure, beyond the scope of a bug fix PR. I've filed this issue to track:  #96680.

**Comment by knz** [comment]
TFYR!

bors r=ZhouXing19

**Comment by knz** [comment]
bors r=ZhouXing19

**Pull request merged**
