### PR TITLE
sql: copy extendedEvalContext from ExecCfg consistently

### LINKED ISSUE #73498: create table t as select * from [SHOW CLUSTER QUERIES]  caused  panic
**Describe the problem**

```sql
create table t as select * from [SHOW CLUSTER QUERIES];
```

```sh
* ERROR: [n1,job=716637457811013633,scExec,id=57] a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038
*   | runtime.panicmem
*   | 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:221
*   | runtime.sigpanic
*   | 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/signal_unix.go:735
*   | github.com/cockroachdb/cockroach/pkg/sql.glob..func29
*   | 	/Users/leoric/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1662
*   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
*   | 	/Users/leoric/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:533
*   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
*   | 	/Users/leoric/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:120
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	/Users/leoric/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:491
*   | runtime.goexit
*   | 	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/asm_amd64.s:1581
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*

```

When I restart, it will crash after a while, even if I do nothing

### PR DESCRIPTION
**Pull request by otan**
Previously, ExecCfg was initialized differently from execCfg in two
different places. This PR unifies that.

Resolves #73498

Release note (bug fix): Fix certain bugs where CREATE TABLE AS or CREATE
MATERIALIZED VIEW may panic if the SELECT query is an internal table
requiring internal database state.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice!

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73577)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/sql/conn_executor.go, line 2459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73577#-MqMubWA7iJsIyBfqCAX:-MqMubWA7iJsIyBfqCAY:bnf900y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28fe7e49a0f2b69d920550f52d6118a7dd0d376/pkg/sql/conn_executor.go#L2459)):*
> ```Go
> // statement, to reinitialize other fields.
> func (ex *connExecutor) initEvalCtx(ctx context.Context, evalCtx *extendedEvalContext, p *planner) {
> 	*evalCtx = extendedEvalContext{
> ```

seems like a lotta stack copies of one of the biggest structs around. thoughts on making your new method a pointer method?

**Comment by rafiss** [comment]
will this fix https://github.com/cockroachdb/cockroach/issues/71414 too? actually idk how to even repro that issue

**Review by otan — COMMENTED** [review]
not sure, repro instructions not good enough for me

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73577#-:-MqNJVkJEUnMGZvG444b:boqzzsz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/conn_executor.go, line 2459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73577#-MqMubWA7iJsIyBfqCAX:-MqNJXwq5nrqoGDfISn5:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28fe7e49a0f2b69d920550f52d6118a7dd0d376/pkg/sql/conn_executor.go#L2459)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

seems like a lotta stack copies of one of the biggest structs around. thoughts on making your new method a pointer method? 
</blockquote></details>

done

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
