### PR TITLE
sql/driver: send time zone on the wire

### PR DESCRIPTION
**Pull request by tamird**
Not sure this is the way we want to go, but it's worth discussing. I had done this work a while ago.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/2840)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
I think there is little value to passing the time zone on the wire. If we do want to have access to the time zone on the driver side, I think it would be better to create a method on the driver that allows the driver user to set the time zone for the driver. That's a driver feature which you've already implemented through the URL settings.

**Comment by bdarnell** [comment]
I think that for our current needs, it's better to expose a time zone at the session level instead of on each value. If we want to introduce value-scoped time zones (like the postgres "timestamp with time zone" type), then this might be a good option but we'd need to think more about how times with time zones interact with times without time zones (can we use `Datum_Timestamp` for both  or are they two separate types?)


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[sql/driver/wire.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0bIbJvXXYi6rDEVuSJ)** ([raw file](https://github.com/cockroachdb/cockroach/blob/2538aaccd9360561d05b58dfb9b98ad362bf6f28/sql/driver/wire.go#L126)):</sup>
Currently, the input location never matters because we convert to either the session timezone or UTC before doing anything with the value. Is this in anticipation of introducing a "timestamp with time zone" type where time zones may be able to carry a time zone with them?


---

<sup>**[sql/executor.go, line 257 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0bJHXtLgu9Diup70a3)** ([raw file](https://github.com/cockroachdb/cockroach/blob/2538aaccd9360561d05b58dfb9b98ad362bf6f28/sql/executor.go#L257)):</sup>
Storing the session time zone in every output timestamp value seems needlessly expensive.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840)

**Comment by petermattis** [comment]
Testing reviewable.io. Ignore.


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840)

**Comment by tamird** [comment]
I think that supporting "timestamp without time zone" is a mistake. The intention here is to remove that entirely. Our timestamps are already "timestamp with time zone"; the time zone just happens to always be [UTC on the wire, Session on the server].


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[sql/driver/wire.go, line 126 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0bIbJvXXYi6rDEVuSJ)** ([raw file](https://github.com/cockroachdb/cockroach/blob/2538aaccd9360561d05b58dfb9b98ad362bf6f28/sql/driver/wire.go#L126)):</sup>
I don't understand your comment. This change is what causes the test changes in this commit.


---

<sup>**[sql/executor.go, line 257 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0bJHXtLgu9Diup70a3)** ([raw file](https://github.com/cockroachdb/cockroach/blob/2538aaccd9360561d05b58dfb9b98ad362bf6f28/sql/executor.go#L257)):</sup>
Maybe, but I'd rather we focus in this PR on whether or not we want this behaviour, and tackle optimization separately (at least in separate discussion if not a separate PR).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840)

**Comment by vivekmenezes** [comment]
Our timestamps are not timestamps with timezone. Timezone is only used for
1. parsing from string
2. converting from timestamp to date

time zone itself is not part of the data stored in the database.

We would like to additionally, 3. use timezone for presentation (in the
UI?, on the client side, etc), but that is very application specific and is
a convenience.

**Comment by petermattis** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[sql/driver/wire.proto, line 41 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0fmFH64CnfTyglk-SY)** ([raw file](https://github.com/cockroachdb/cockroach/blob/15923e8cea9925a94e17b8f3198d953ded478b5a/sql/driver/wire.proto#L41)):</sup>
Won't every timestamp in a response have the same location? I would have thought that we'd return the location at the `Response` level, not the `Datum` level.  And don't we need this to be:

```proto
oneof timezone {
  string location;
  int64 offset;
}
```


---

<sup>**[sql/executor.go, line 349 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840#-K0fmqksevd1ej7oA8zG)** ([raw file](https://github.com/cockroachdb/cockroach/blob/15923e8cea9925a94e17b8f3198d953ded478b5a/sql/executor.go#L349)):</sup>
Aren't we always storing timestamps as UTC? If yes, why are we passing the location information for individual timestamps to the server?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/2840)

**Comment by bdarnell** [comment]
> I think that supporting "timestamp without time zone" is a mistake.

I disagree. I think that we *might* want to support "timestamp with time zone" as an option, but we should definitely not remove support "timestamp without time zone" (and I'm not convinced yet that even adding a "with TZ" option is a good idea).

* All SQL databases that I looked at offer a "without TZ" timestamp type. For MySQL, this is the only option. PostgreSQL and Oracle offer "with TZ" options that can store an offset or a location name. SQL Server has a version that can only store a zone offset (which seems to me to have very limited use: in most cases where time zones matter you care about the location name and not just the offset at one instant. Europe/Paris and Africa/Johannesburg are both +2:00 in June, but only one of them will be +1:00 in December)

* If timestamp values have time zones, when is the session time zone used? I think you only want a time zone in one place, so if we get rid of "without TZ" timestamps then the session time zone becomes useless (although I claim that a session TZ is a better fit for most requirements than a value TZ)

* Time zones and DST rules change. If you store dates in the future as unix offset + location name, the interpretation of that data may change when you read them back later. (If I schedule an event for 10am on Nov 1 2016, I want that event to stay at 10am even if congress decides to move the daylight savings boundary between now and then). I think this implies that to properly support time zones at the value level we need to store timestamps as strings (or at least something with distinguished fields) instead of an offset from an epoch, and re-parse them on demand.

The last point is the one that makes me think that adding a "with TZ" type at this point when we have only a vague notion of the requirements would be a mistake.

**Comment by tamird** [comment]
@bdarnell I'm 99% sure that DST changes are never retroactive, so I'm not sure what the problem is with sending back the time zone by name. The client should be able to figure out the DST rules in effect at the instant in time that it receives.

**Comment by bdarnell** [comment]
DST changes are not retroactive, but not all timestamps are in the past. A change to DST rules could affect the interpretation of timestamps representing a time in the future.

**Comment by tamird** [comment]
Ah, that's a valid point. Ok, I'm going to abandon this for now.

**Pull request closed without merging**
