### PR TITLE
workload/schemachange: "fix" workload

### PR DESCRIPTION
**Pull request by ajwerner**
This is a variety of commits which fixes bugs in the schemachange workload. It also disables a number of features.

### CODE REVIEW

**Comment by ajwerner** [comment]
I spun this up under stress on 256 cores: `7290 runs so far, 0 failures, over 20m0s`. I feel reasonably good about it given some of the things it turned up extremely quickly when they existed. There's more features to turn back on but this is a good start.

**Review by fqazi — COMMENTED** [review]
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59635)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @postamar)

**Review by arulajmani — APPROVED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59635)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/workload/schemachange/operation_generator.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqohZj7pEq4aslJXbK:-MVqohZj7pEq4aslJXbL:bc3p9ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L207)):*
> ```Go
> 	setColumnNotNull:        1,
> 	setColumnType:           1,
> 	insertRow:               0,
> ```

Disallowing inserts will inhibit our ability to test `ALTER TYPE ... DROP VALUE` right? Ideally we'd want to seed tables that use user defined types with some data. 

Is the complication here mostly around computed columns overflowing (like you mention in a comment somewhere below)? If so, would it make sense to block inserts if the table contains computed columns further down instead? I'm not sure if this is even feasible, as I couldn't find with what probability we generate computed columns, and maybe thats crippling in itself. 
___
*[pkg/workload/schemachange/operation_generator.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqh1n62yct83qDpKjp:-MVqh1n62yct83qDpKjq:b-4e83i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L796)):*
> ```Go
> 
> 			// Filter out the generated virtual columns.
> 			// TODO(ajwerner): Remove this after #61768 is fixed.
> ```

Looks like the issue linked is closed, so you could get rid of this thing. 
___
*[pkg/workload/schemachange/operation_generator.go, line 1733 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqrjPT8ImFr7zq5Aa8:-MVqrjPT8ImFr7zq5Aa9:b-lfxb9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L1733)):*
> ```Go
> 	rows := [][]string{}
> 	for _, col := range cols {
> 		if col.generated {
> ```

nit: you could get rid of this as this is always false here.

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-:-MVv6MEs4bMG1UfTh1d5:be4m769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @fqazi, and @postamar)

___
*[pkg/workload/schemachange/operation_generator.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqohZj7pEq4aslJXbK:-MVtMPeoDAjdyeWVYoh4:bdq1nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L207)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Disallowing inserts will inhibit our ability to test `ALTER TYPE ... DROP VALUE` right? Ideally we'd want to seed tables that use user defined types with some data. 

Is the complication here mostly around computed columns overflowing (like you mention in a comment somewhere below)? If so, would it make sense to block inserts if the table contains computed columns further down instead? I'm not sure if this is even feasible, as I couldn't find with what probability we generate computed columns, and maybe thats crippling in itself. 
</blockquote></details>

We'll need to fix this. IIRC there were a few different issues. I wanted to stabilize this test before going back to features as this PR wasn't tiny as it is.  The computed column overflow was the first one I was hitting. 


Insert row also has the problem that there are combinations of schema changes which can fail permanently, generally involving drop column. I think we'll need to add a rule that says that we don't do drop column in a transaction that has schema changes which might fail. D
___
*[pkg/workload/schemachange/operation_generator.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqh1n62yct83qDpKjp:-MVtMw9D4RLSQyE9agA1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L796)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Looks like the issue linked is closed, so you could get rid of this thing. 
</blockquote></details>

Done.
___
*[pkg/workload/schemachange/operation_generator.go, line 1733 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59635#-MVqrjPT8ImFr7zq5Aa8:-MVtNvug9iXLOqQ3cjjF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5ec65d8144eb17fa83f205092d8581ad72b982/pkg/workload/schemachange/operation_generator.go#L1733)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: you could get rid of this as this is always false here. 
</blockquote></details>

Done.

**Pull request merged**
