### PR TITLE
Revert "roachpb: change `Lease.String()`/`SafeFormat()` to support re…

### PR DESCRIPTION
**Pull request by yuzefovich**
…fs."

This reverts commit 33fe9d15b2660cc40d255a3d448d88bb35c2c39d.

See #74559 for rationale.

### CODE REVIEW

**Comment by knz** [comment]
I'd like this to be discussed at a team meeting

**Comment by knz** [comment]
ok so we [discussed this internally](https://cockroachlabs.slack.com/archives/G01G8LK77DK/p1641563611023400), with the summary spelled out in [this comment[(https://github.com/cockroachdb/cockroach/issues/72814#issuecomment-1007480109).

In summary, it's probably ok to revert this.

@kvoli are you cool with it?

**Comment by kvoli** [comment]
> ok so we [discussed this internally](https://cockroachlabs.slack.com/archives/G01G8LK77DK/p1641563611023400), with the summary spelled out in [this comment](https://github.com/cockroachdb/cockroach/issues/72814#issuecomment-1007480109).
> 
> In summary, it's probably ok to revert this.
> 
> @kvoli are you cool with it?

All good from me. This makes sense.

**Review by kvoli — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74560#-:-Mt8cYNL1NKcMmC397LH:bg7igk9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by yuzefovich — COMMENTED** [review]
Fixed the merge conflict.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74560#-:-Mt92SHjBelIEhCiSyR9:b-alxcp3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

**Pull request merged**
