### PR TITLE
sql: add more tests to TestRaceWithBackfill

### PR DESCRIPTION
**Pull request by vivekmenezes**
This PR strengthens our testing for the upcoming change that chunks the backfill process.
It also reenables the test.
#6124

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6137)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/schema_changer_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KFfZbGWk7t2tdDmxMjb:-KFfZbGWk7t2tdDmxMjc:356832449) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8710f11fd5fb32af1a69a2f55a95014a7c8d3c/sql/schema_changer_test.go#L572)):*
should this be a separate test? There's no race being tested for this `DROP COL`, is there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137)*

**Comment by vivekmenezes** [comment]
Ready for another look.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/schema_changer_test.go, line 572 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KFfZbGWk7t2tdDmxMjb:-KFg9aQfe6bA0FwM_vbn:-1103516702) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b8710f11fd5fb32af1a69a2f55a95014a7c8d3c/sql/schema_changer_test.go#L572)):*
I've added another column (pi) and index (vidx) to the table. The schema change transaction now drops pi and vidx and adds a new column and index. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-:-KFg9rIrVzNj-3pYByBc:252301049)*

**Comment by vivekmenezes** [comment]
Hmmm, I don't think this fixes the bug. Let me figure this out and get back
to you.

**Comment by vivekmenezes** [comment]
Okay finally ready for another look.

**Comment by vivekmenezes** [comment]
@andreimatei this is ready for review. I'd really like to check this in so that all future changes test against these tests. Thanks

**Comment by andreimatei** [comment]
LGTM if you don't want to rewrite the "backfill holding a lock" test

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/schema_changer_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDBXme1izYFmLN5nk8:-KGDBXmf9hcOwsA1Quyw:-1534537418) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L446)):*
nit; you do a similar wait in this PR using a `notify` channel. Maybe unify?

---

*[sql/schema_changer_test.go, line 459 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDBqR9K6K-WzwEgoZn:-KGDBqR9K6K-WzwEgoZo:-1466065326) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L459)):*
can you use the new `SyncSchemaChangersFilter` instead of this busy loop?

---

*[sql/schema_changer_test.go, line 570 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDA0eOlPpigy5dDZ40:-KGDA0eOlPpigy5dDZ41:-317064846) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L570)):*
you can use `getKeysForTableDescriptor()`

---

*[sql/schema_changer_test.go, line 673 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDCeBPtRC27Mw5ehWX:-KGDCeBPtRC27Mw5ehWY:-1285853304) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L673)):*
nit: rename `notify` to `backfillDone` so it's clearer what the select below tests.

---

*[sql/schema_changer_test.go, line 684 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDCWSGTWFkUd4eA0WM:-KGDCWSGTWFkUd4eA0WN:-542709995) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L684)):*
can you use `SyncSchemaChangersFilter`?

---

*[sql/schema_changer_test.go, line 696 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDD_xGC4_ebq_ZwJYE:-KGDD_xGC4_ebq_ZwJYF:1897785202) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L696)):*
I think the way we test that the backfill finishes first is pretty inconclusive.
How about adding a test asserting that all the schema changes take the schema change lock (through a new simple testing hook in the lease acquisition) and release it at the expected time (e.g. for backfills, release it when the backfill is done), and separately testing that you can't acquire that lease when someone else has it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-:-KGDEFlD_1-i78t5OA-D:1845150480)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/schema_changer_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDBXme1izYFmLN5nk8:-KGDK8X4Qa3dDrwrrWq0:-1420075845) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L446)):*
I've taken out that other test. It was not really doing anything valuable. We now test that once the schema change is progressing, the lease cannot be acquired.

---

*[sql/schema_changer_test.go, line 459 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDBqR9K6K-WzwEgoZn:-KGDPla6sA4jLN2AZAl7:1381235695) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L459)):*
I much prefer this approach. It's easy to ready without needing to read all that filtering stuff.

---

*[sql/schema_changer_test.go, line 570 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDA0eOlPpigy5dDZ40:-KGDNUnrW-iQ4xHlT3fa:590895329) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L570)):*
I don't a use for it here. However, this piece of code is being copied around in a number of tests, so it does make sense for us to ditch it for a function. I'll send you another PR shortly

---

*[sql/schema_changer_test.go, line 673 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDCeBPtRC27Mw5ehWX:-KGDPz8klquTpN6o9O1F:1443782795) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L673)):*
completely removed

---

*[sql/schema_changer_test.go, line 684 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDCWSGTWFkUd4eA0WM:-KGDQ04kUkfMmrkaZ3T1:-1054325829) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L684)):*
removed

---

*[sql/schema_changer_test.go, line 696 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137#-KGDD_xGC4_ebq_ZwJYE:-KGDJgsGBEzTBUErVe-y:1822735507) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae7dca9785f0828ddf34166a45e3eadb02b43254/sql/schema_changer_test.go#L696)):*
I've taken out this entire test and added the lease acquisition failure test. Good call!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6137)*

**Pull request merged**
