### PR TITLE
jobs: add resume_errors and cleanup_errors to job payload

### PR DESCRIPTION
**Pull request by thoszhang**
The current job `Payload` proto has only a string field `error` for the error
associated with a failed job. This PR adds fields `resume_errors` and
`cleanup_errors` for encoded errors resulting from the job `Resume` and
`OnFailOrCancel` hooks, respectively, and starts writing to `resume_errors`
everywhere `error` is currently set. The errors are stored as
`errorspb.EncodedError`.

The immediate point of this is to be able to recover error codes for schema
change jobs that are queued to run after a transaction. Eventually we'll
populate these fields with an error for each retry attempt for the job hooks.

Release note: None

### CODE REVIEW

**Review by dt — COMMENTED** [review]
Spas and I were talking recently about errors during Resume vs errors during Cleanup and what happens when we have both, as well as tracking failures/retries. As long as we’re going though the work of switching to a new field, should we take a couple minutes to sketch out where that work is headed in case it overlaps with this?

**Comment by lucy-zhang** [comment]
We discussed offline. The plan is to store all the errors from all retry attempts of the job resumer and OnFailOrCancel hook:
```
  repeated errorspb.EncodedError resume_errors = 17;
  repeated errorspb.EncodedError cleanup_errors = 18;
```
We also discussed putting the errors in a separate column in `system.jobs` but decided against it for now. The migration would be difficult because changing the table schema requires writing to `system.jobs`.

This is ready for another look.

**Review by dt — APPROVED** [review]

**Comment by lucy-zhang** [comment]
Flaky test, #44397

bors r+

**Pull request merged**
