### PR TITLE
base,server,testutils: clarify the multi-tenant test situations

### PR DESCRIPTION
**Pull request by knz**
Informs #76378 .
Informs #106772.
Epic: CRDB-18499

Prior to this patch, a test could choose only between the following
options:

- `TestTenantProbabilisticOnly` and `TestTenantProbabilistic`:
  whether or not the load goes to a secondary tenant is randomly
  selected for each test.

- `TestTenantEnabled`: always use a secondary tenant.

- `TestTenantDisabled`: always disable the secondary tenant.

In particular the last option was problematic, as we ended up using it
both in the case "the test doesn't work with secondary tenants and
*we don't know why*" and the case "it doesn't work, we know why
*and it's OK to keep it that way*".

We actually want to distinguish these cases, because the former
case requires further investigation, and we want the test code
to refer to this follow-up work more clearly.

To address this, this commit defines the following options:

```go
// (UNCHANGED)
TestTenantProbabilisticOnly
// (UNCHANGED)
TestTenantProbabilistic

// RENAMED: was previously "TestTenantEnabled"
//
// TestTenantAlwaysEnabled will always start the default test tenant. This is useful
// for quickly verifying that a test works with tenants enabled.
//
// Note: this value should not be used for checked in test code
// unless there is a good reason to do so. We want the common case
// to use TestTenantProbabilistic or TestTenantProbabilisticOnly.
TestTenantAlwaysEnabled

// RENAMED: was previously "TestTenantDisabled"
//
// TODOTestTenantDisabled should not be used anymore. Use the
// other values instead.
// TODO(https://github.com/cockroachdb/cockroach/issues/76378): Review existing tests and use the proper value instead.
TODOTestTenantDisabled = DefaultTestTenantOptions{testBehavior: ttDisabled}

// (NEW) TestIsSpecificToStorageLayerAndNeedsASystemTenant is used when
// the test needs to be given access to a SQL conn to a tenant with
// sufficient capabilities to access all the storage layer.
// (Initially that'd be "the" system tenant.)
TestIsSpecificToStorageLayerAndNeedsASystemTenant

// (NEW) TestControlsTenantsExplicitly is used when the test wants to
// manage its own secondary tenants and tenant servers.
TestControlsTenantsExplicitly

// (NEW) TestNeedsTightIntegrationBetweenAPIsAndTestingKnobs is used when
// a test wants to use a single set of testing knobs for both the
// storage layer and the SQL layer and for simplicity of the test
// code we want to give that test a simplified environment.
//
// Note: it is debatable whether the gain in test code simplicity is
// worth the cost of never running that test with the virtualization
// layer active.
TestNeedsTightIntegrationBetweenAPIsAndTestingKnobs

// (NEW) TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet can be used
// to disable virtualization because the test doesn't appear to be compatible
// with it, and we don't understand it yet.
// It should link to a github issue with label C-test-failure.
TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet(issueNumber int)

// (NEW) TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet can be
// used to disable virtualization because the test exercises a feature
// known not to work with virtualization enabled yet but we wish it
// to work eventually.
//
// It should link to a github issue with label C-bug
// and the issue should be linked to an epic under INI-213 or INI-214.
TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet(issueNumber int)
```

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 14 of 115 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @knz, @Santamaura, @srosenberg, and @stevendanna)

___
*[`pkg/sql/logictest/logic.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FW5hV2_6M3jT9tjhE:-N_FW5hV2_6M3jT9tjhF:b-i1kndw) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1392)):*
> ```Go
> 		// the implicit creation of the default test tenant.
> 		//
> 		// TODO(#76378): This conditional is naive - what does it expect to do
> ```

`DefaultTestTenantOptions` here comes from the logic test config, and we currently only have a binary choice "use tenant or not", so we don't ever enable the probabilistic option. Do you foresee that changing? I can see us randomly deciding to use shared-process multi-tenant instead of single tenant, but enabling separate-process multi-tenant and using it by default for non-tenant logic test configs will probably require some elbow grease to make the existing tests non-flaky (one concrete example is that in the tenant world DistSQL physical planner is not deterministic, so EXPLAIN tests might become non-deterministic in multi-node setup).
___
*[`pkg/sql/logictest/logic.go` line 1501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FWujh05fhnbg0Kzr0:-N_FTz-86bWyqSv17uXk:b3xulhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1501)):*
> ```Go
> 	connsForClusterSettingChanges := []*gosql.DB{t.cluster.ServerConn(0)}
> 	if cfg.DefaultTestTenant.TestTenantAlwaysEnabled() {
> 		// TODO(#76378): What's going here? It looks like this code is
> ```

Indeed, in the logic test framework we currently don't use `serverutils.StartServer` and control ourselves whether we start the tenant or not.
___
*[`pkg/sql/logictest/logic.go` line 2993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FX3c9EML6xpipZQJa:-N_FX3c9EML6xpipZQJb:bsvi9mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L2993)):*
> ```Go
> 			//
> 			// TODO(#76378): It seems the conditional should include `||
> 			// t.cluster.StartedDefaultTestTenant()` here.
> ```

Currently, that will always return `false`.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @knz, @Santamaura, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/sqlinstance/instancestorage/instancecache_test.go` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FbCqH9y-KEfKPuDm7:-N_FbCqH9y-KEfKPuDm8:b-pflra) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf54dacd91358726a6d41f688c45b3164a7c508/pkg/sql/sqlinstance/instancestorage/instancecache_test.go#L73)):*
> ```Go
> 
> 	ctx := context.Background()
> 	host, _, _ := serverutils.StartServer(t, base.TestServerArgs{DefaultTestTenant: base.TODOTestTenantDisabled})
> ```

This test like a few others here are outside of `ccl` and does not enable a license for testing purposes. I tested locally and the flag has no influence here due to a license check opting out of tenants altogether: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/testserver.go#L548. I suspect we'll address this in another PR, or will it also be part of this one?

**Review by yuzefovich — APPROVED** [review]
Overall, I like this, so :lgtm: We can discuss each of the TODOs on a case by case basis (like what to do in the logic test framework, etc).

nit: update the PR description with the latest version of the enum.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-:-N_FlMhzEse1Vb2DPWVP:bksowqr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava, @knz, @Santamaura, @srosenberg, and @stevendanna)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @Santamaura, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FW5hV2_6M3jT9tjhE:-N_G26rc4uMvPq4EEoJr:bx5kwu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1392)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`DefaultTestTenantOptions` here comes from the logic test config, and we currently only have a binary choice "use tenant or not", so we don't ever enable the probabilistic option. Do you foresee that changing? I can see us randomly deciding to use shared-process multi-tenant instead of single tenant, but enabling separate-process multi-tenant and using it by default for non-tenant logic test configs will probably require some elbow grease to make the existing tests non-flaky (one concrete example is that in the tenant world DistSQL physical planner is not deterministic, so EXPLAIN tests might become non-deterministic in multi-node setup).
</blockquote></details>

I am starting to understand. At a very high level, the logic test framework neither cares nor has to care about the randomization logic we have in testutils, **because we have decided that we already want to run logic tests in all configs, all the time** (i.e. cross product).

So at the core, the problem to solve here is how to:
1) opt out of the randomization in testutils.
2) at the same time, ensure the logic test profiles that do want secondary tenants, to get the same "server config" as a regular unit test.

I think one way i'd like to move forward on this (not this PR) is to change `logictestbase.TestClusterConfig` to use a different go type than `base.DefaultTestTenantOptions` to control the use of secondary tenants. Maybe just `UseSecondaryTenant bool`. So logic test profiles have just a boolean. And then we can propagate it to the TestServer config with a conditional that chooses between `TestTenantAlwaysEnabled` and `TestIsSpecificToStorageLayerAndNeedsASystemTenant`.
___
*[`pkg/sql/logictest/logic.go` line 1501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FWujh05fhnbg0Kzr0:-N_G3At71QkLhuBNqBww:b-5qjj76) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1501)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Indeed, in the logic test framework we currently don't use `serverutils.StartServer` and control ourselves whether we start the tenant or not.
</blockquote></details>

See my comment above: we should not use `DefaultTestTenantOptions` in the TestClusterConfig.
___
*[`pkg/sql/logictest/logic.go` line 2993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FX3c9EML6xpipZQJa:-N_G3JQ27lbyCQdSQ3bn:b-i0c0r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L2993)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Currently, that will always return `false`.
</blockquote></details>

Indeed, I now understand why. We can remove my comment when we do the simplification.
___
*[`pkg/sql/sqlinstance/instancestorage/instancecache_test.go` line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FbCqH9y-KEfKPuDm7:-N_G3fKX8KX4sOWhYseD:bwj6mn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf54dacd91358726a6d41f688c45b3164a7c508/pkg/sql/sqlinstance/instancestorage/instancecache_test.go#L73)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

This test like a few others here are outside of `ccl` and does not enable a license for testing purposes. I tested locally and the flag has no influence here due to a license check opting out of tenants altogether: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/testserver.go#L548. I suspect we'll address this in another PR, or will it also be part of this one?
</blockquote></details>

For some tests like these we could try to make them import the CCL packages. We've discussed that before: it's ok for _test code_ in the non-CCL packages to import CCL code.

When it's not possible, we need to make all these tests at least use the non-networked tenant connector that doesn't need CCL.
See my comment on #106772:

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @knz, @Santamaura, @srosenberg, and @stevendanna)

___
*[`pkg/sql/logictest/logic.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FW5hV2_6M3jT9tjhE:-N_GAs-j2rOIjiIuXzGC:bq85zpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1392)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I am starting to understand. At a very high level, the logic test framework neither cares nor has to care about the randomization logic we have in testutils, **because we have decided that we already want to run logic tests in all configs, all the time** (i.e. cross product).

So at the core, the problem to solve here is how to:
1) opt out of the randomization in testutils.
2) at the same time, ensure the logic test profiles that do want secondary tenants, to get the same "server config" as a regular unit test.

I think one way i'd like to move forward on this (not this PR) is to change `logictestbase.TestClusterConfig` to use a different go type than `base.DefaultTestTenantOptions` to control the use of secondary tenants. Maybe just `UseSecondaryTenant bool`. So logic test profiles have just a boolean. And then we can propagate it to the TestServer config with a conditional that chooses between `TestTenantAlwaysEnabled` and `TestIsSpecificToStorageLayerAndNeedsASystemTenant`.

</blockquote></details>

Makes sense and SGTM. FWIW we used to have a boolean in there initially too.

**Review by knz — COMMENTED** [review]
Yahor, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-:-N_GL3N74cyil5ABdzZc:b-rqn9xv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @jayshrivastava, @Santamaura, @srosenberg, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FW5hV2_6M3jT9tjhE:-N_GIGSd6zrih9icZd4P:bbqcq5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1392)):*
> `DefaultTestTenantOptions` here comes from the logic test config, and we currently only have a binary choice "use tenant or not", so we don't ever enable the probabilistic option

I have re-read the original code and I believe this is incorrect in general.
What you say is true in the specific case where a config would specify either `TestTenantEnable` or `TestTenantDisabled` explicitly.
But when it does not, the zero value of the field is `TestTenantProbabilisticOnly`.
Then, in the conditional here `defaultTestTenant` remains what is originally set (because the value is `!= TestTenantEnabled`).

So eventually a tenant server is created randomly by testutils.

This is incidentally why below in this file we have a condition like `if cfg.DefaultTestTenant == TestTenantEnabled || t.cluster.StartedDefaultTestTenant()`. The second part of the condition is for the case the config didn't specify anything and a secondary tenant was started randomly.

I have added an extra commit in the PR. Do you like it?

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 15 of 116 files at r4, 14 of 115 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-:-N_GPYD4Dhm2FRwcFWTc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @knz, @Santamaura, @srosenberg, and @stevendanna)

___
*[`pkg/sql/logictest/logic.go` line 1392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106768#-N_FW5hV2_6M3jT9tjhE:-N_GO0Z96ziDpLtV1JYY:bvldcqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a3914f3135baed36d80f4d48812c3eb629f96a/pkg/sql/logictest/logic.go#L1392)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> `DefaultTestTenantOptions` here comes from the logic test config, and we currently only have a binary choice "use tenant or not", so we don't ever enable the probabilistic option

I have re-read the original code and I believe this is incorrect in general.
What you say is true in the specific case where a config would specify either `TestTenantEnable` or `TestTenantDisabled` explicitly.
But when it does not, the zero value of the field is `TestTenantProbabilisticOnly`.
Then, in the conditional here `defaultTestTenant` remains what is originally set (because the value is `!= TestTenantEnabled`).

So eventually a tenant server is created randomly by testutils.

This is incidentally why below in this file we have a condition like `if cfg.DefaultTestTenant == TestTenantEnabled || t.cluster.StartedDefaultTestTenant()`. The second part of the condition is for the case the config didn't specify anything and a secondary tenant was started randomly.

I have added an extra commit in the PR. Do you like it?

</blockquote></details>

Yeah, you're right, I missed that. I like that change, thanks.

**Comment by knz** [comment]
TFYR!

bors r=yuzefovich

**Comment by knz** [comment]
bors r=yuzefovich

**Pull request merged**
