### PR TITLE
sql: added fetch leaseholder builtin

### PR DESCRIPTION
**Pull request by changangela**
Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
Looks good - the logic test failures are caused by adding a new virtual table - unfortunately a bunch of test cases assert exactly the number of virtual tables present at startup and all of their names. You could go through and fix all of them, or use the `-rewrite-results-in-testfiles`  option in `make testlogic` to just rewrite the tests based on what comes out of the actual test run :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30601#-:-LNCRoafAERZ_MSdyx0K:b-ocrjkz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/builtins.go, line 2876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30601#-LNCHiMT8A88glHUzaT3:-LNCHiMT8A88glHUzaT4:bw20gt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4ff9fa053bea960a1114b2bf0f23f97ece5a/pkg/sql/sem/builtins/builtins.go#L2876)):*
> ```Go
> 				if err := ctx.Txn.Run(ctx.Context, b); err != nil {
> 					return nil, pgerror.NewError(
> 						pgerror.CodeInvalidParameterValueError, "error getting lease information")
> ```

You should include the error details in this message as well - use `pgerror.NewErrorf(code, "message: %s", err)`.
___
*[pkg/sql/sem/builtins/builtins.go, line 2882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30601#-LNCIiCj4X_w3EAaxcry:-LNCIiCj4X_w3EAaxcrz:b-aqg6nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4ff9fa053bea960a1114b2bf0f23f97ece5a/pkg/sql/sem/builtins/builtins.go#L2882)):*
> ```Go
> 				return tree.NewDInt(tree.DInt(resp.Lease.Replica.StoreID)), nil
> 			},
> 			Info: "This function is used to fetch the leases corresponding to a request key",
> ```

I would probably change this to say "leaseholder" instead of "leases".

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30601)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/builtins.go, line 2876 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30601#-LNCHiMT8A88glHUzaT3:-LNGBpdN0WLXpwD-haib:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4ff9fa053bea960a1114b2bf0f23f97ece5a/pkg/sql/sem/builtins/builtins.go#L2876)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should include the error details in this message as well - use `pgerror.NewErrorf(code, "message: %s", err)`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30601#-LNCIiCj4X_w3EAaxcry:-LNGBqJ89Mj2ZxxIDXwb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4ff9fa053bea960a1114b2bf0f23f97ece5a/pkg/sql/sem/builtins/builtins.go#L2882)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would probably change this to say "leaseholder" instead of "leases".
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
LGTM

**Review by asubiotto — APPROVED** [review]
LGTM. Make sure to add a high-level description of this change in the commit message.

**Comment by changangela** [comment]
bors+

**Pull request merged**
