### PR TITLE
storage: send ReplicaState in streaming snapshots

### LINKED ISSUE #10783: storage: avoid indexing batches in Replica.applySnapshot
Most (all?) excessive `raftMu` lock hold times stem from replica deletion and applying a snapshot to a replica. Instrumenting `Replica.applySnapshot` shows the following breakdown of times when applying a 56 MB snapshot:

| | |
| --- | --- |
| clear old range data | 0 ms |
| apply batches | 274 ms |
| write raft log entries | 0 ms |
| commit | 366 ms |
| other | 1 ms |
| total | 641 ms|

Another instance when applying a 54 MB snapshot showed:

| | |
| --- | --- |
| clear old range data | 0 ms |
| apply batches | 646 ms |
| write raft log entries | 0 ms |
| commit | 222 ms |
| other | 4 ms |
| total | 872 ms |

Notice that `apply batches` is taking a significant amount of time in both these snapshot applications. This is interesting because this operation is primarily sending a batch repr from Go to C++. Unfortunately, in addition to moving the data from Go to C++ that operation is indexing the batch on the C++ side so that we can later perform a read to retrieve the replica state (via a call to `loadState`). 

So we index all of the batch data in memory in order to retrieve a handful of keys. It seems feasible to send the replica state explicitly in the snapshot in order to eliminate this read. If we can avoid reading from the C++ batch we could add additional mechanism to avoid indexing the batches cutting a significant chunk of time from `applySnapshot`.

### PR DESCRIPTION
**Pull request by petermattis**
This removes the need to read ReplicaState from the batch when applying
a snapshot, allowing the use of a write-only RocksDB batch. The
write-only RocksDB batch does not index keys on insertion/deletion which
is only necessary if those keys are read.

Fixes #10783

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10931)

### CODE REVIEW

**Comment by petermattis** [comment]
Needs more commenting and some additional performance testing. In my informal testing this speeds up `applySnapshot` by about 50%.

**Comment by bdarnell** [comment]
Nice!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/raft.proto, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KX9pHI11llDQirE_tSO:-KX9pHI11llDQirE_tSP:b2cy4s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fc36d38ea32feda54abe28126b404b9023df1a/pkg/storage/raft.proto#L132)):*
> ```protobuf
> 
>   // The replica state at the time the snapshot was generated.
>   optional storagebase.ReplicaState state = 5;
> ```

`ReplicaState` contains a `RangeDescriptor`, which we're already sending in the header. Should we move this into the header and remove the range descriptor field there?

---

*[pkg/storage/replica_raftstorage.go, line 639 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KX9pV2X9AJAAtj_tGzh:-KX9pV2X9AJAAtj_tGzi:b-78pgyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fc36d38ea32feda54abe28126b404b9023df1a/pkg/storage/replica_raftstorage.go#L639)):*
> ```Go
> 		batch = r.store.Engine().NewWriteOnlyBatch()
> 	} else {
> 		// TODO(peter): This can only happen if the sender is running code before
> ```

The next beta is going to require a stop-the-world upgrade anyway, so if this goes in in time I don't think we need this backwards-compatibility mode at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KX9pjq03R_3wJCUha1S:b-83sjoh)*

**Comment by petermattis** [comment]
Added a benchmark and a basic test of write-only batches. I think this is good to go now. PTAL.

---

Review status: 3 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/raft.proto, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KX9pHI11llDQirE_tSO:-KXBr8lasKUFr5Rk7zCN:b-ihinqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/38fc36d38ea32feda54abe28126b404b9023df1a/pkg/storage/raft.proto#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `ReplicaState` contains a `RangeDescriptor`, which we're already sending in the header. Should we move this into the header and remove the range descriptor field there?
</details>
`Header.RangeDescriptor` is the "updated" range descriptor after we've added the new replica. This `state` field is the current state of the replica on the source at the time of the snapshot which is different. That's a subtle difference which I'd prefer not to touch in this PR. But I can move this field to the `Header` which makes 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXC3QuHKVVTVdNwSNGv:b2hzig4)*

**Comment by petermattis** [comment]
@tamird Can you take a look at the teamcity test failures? The new benchmarks are failing but they are following the same pattern as existing benchmarks.

**Comment by tamird** [comment]
I think you might need to rebase to pick up #10923, #10927, and #10933.

---

Review status: 3 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXCLH7SugbcY0UEyvYG:b-b76a3w)*

**Comment by tamird** [comment]
I haven't looked in detail, but looks like a hardcoded file name so multiple runs of the benchmark under stress are conflicting with one another.

---

Review status: 3 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXCVgho96I5hYIug8kb:b-auqc8n)*

**Comment by petermattis** [comment]
Why are we trying to run benchmarks under stress?

**Comment by tamird** [comment]
Perhaps we shouldn't, but sadly our benchmarks frequently rot, so I
included them in the first cut of the runner.

**Comment by petermattis** [comment]
Ok. Fixed these benchmarks to use an in-mem RocksDB as they aren't actually writing anything to disk.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft.proto, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXF1WasIhTUP1Xj-kiB:-KXF1WatyWRg9-wx48ky:b-eop4kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e3c7f7a54553814d1b357c3c73d1a41d7c37f/pkg/storage/raft.proto#L113)):*
> ```protobuf
>     // field which holds the updated descriptor after the new replica
>     // has been added while ReplicaState.Desc holds the descriptor
>     // before the new replica has been added.
> ```

Ah, that's subtle. It also seems incorrect to me - we shouldn't leak out the post-add range descriptor until after the transaction is committed. I looked at all the places where Header.RangeDescriptor is used and it looks like we only use the start/end key and range ID; nothing ever looks at the replica set there. So it should be safe to just drop the range_descriptor field and use the one in the state instead. (we could do this in a separate PR, but I'd be inclined to group them together just to minimize the number of separate incompatible changes here)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXF2gu2xuXLaKWc5xv4:bnfp4nl)*

**Comment by bdarnell** [comment]
LG again, although I'm realizing that we could use some better documentation about write-only and distinct batches. Should write-only imply distinct?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXGWDdfBbVfJdz1V_Uj:b-r6f4sw)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft.proto, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXF1WasIhTUP1Xj-kiB:-KXGWr4ar0-nRpimYjIW:b-6wvm0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e3c7f7a54553814d1b357c3c73d1a41d7c37f/pkg/storage/raft.proto#L113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Ah, that's subtle. It also seems incorrect to me - we shouldn't leak out the post-add range descriptor until after the transaction is committed. I looked at all the places where Header.RangeDescriptor is used and it looks like we only use the start/end key and range ID; nothing ever looks at the replica set there. So it should be safe to just drop the range_descriptor field and use the one in the state instead. (we could do this in a separate PR, but I'd be inclined to group them together just to minimize the number of separate incompatible changes here)
</details>
We call `Replica.setDescWithProcessUpdate` at the end of `Replica.applySnapshot` using `Header.RangeDescriptor`. Is it correct to change this code to use `ReplicaState.Desc`? Doing so will mean the replica's RangeDescriptor won't contain itself for a brief period of time. Is that ok with the replica GC queue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by bdarnell** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft.proto, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXF1WasIhTUP1Xj-kiB:-KXGYTJ5n2MrWjCRBHy1:b-3irzlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e3c7f7a54553814d1b357c3c73d1a41d7c37f/pkg/storage/raft.proto#L113)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> We call `Replica.setDescWithProcessUpdate` at the end of `Replica.applySnapshot` using `Header.RangeDescriptor`. Is it correct to change this code to use `ReplicaState.Desc`? Doing so will mean the replica's RangeDescriptor won't contain itself for a brief period of time. Is that ok with the replica GC queue?
</details>
Oh, I didn't pull on that thread far enough. It's incorrect to use Header.RangeDescriptor there and it should be changed to use the one from the state.  Leaking the updated range descriptor before it is committed could have some interesting consequences (since raft on the new replica will start using that configuration immediately), although I don't see anything disastrous (yet). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by petermattis** [comment]
Review status: 7 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/raft.proto, line 113 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXF1WasIhTUP1Xj-kiB:-KXfcXh0pITzF9Bx46rs:baq9h7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e3c7f7a54553814d1b357c3c73d1a41d7c37f/pkg/storage/raft.proto#L113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Oh, I didn't pull on that thread far enough. It's incorrect to use Header.RangeDescriptor there and it should be changed to use the one from the state.  Leaking the updated range descriptor before it is committed could have some interesting consequences (since raft on the new replica will start using that configuration immediately), although I don't see anything disastrous (yet). 
</blockquote></details>

Ok, I've removed `Header.RangeDescriptor` and made sure we populate `Header.State` properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 5 of 10 files at r2, 1 of 3 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfiZaLPTP5aS4tp0vo:b-t3us08) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
> ```Go
> 	// The Raft log entries for this snapshot.
> 	LogEntries [][]byte
> 	State      *storagebase.ReplicaState
> ```

is there any reason this is a pointer? looks like it made sense in an earlier version when the proto field was nullable.

---

*[pkg/storage/replica_raftstorage.go, line 581 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiUOOPIXizLBylNWy:-KXfiUOOPIXizLBylNWz:b-3aocsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L581)):*
> ```Go
> 	s := *inSnap.State
> 	if s.Desc.RangeID != r.RangeID {
> 		log.Fatalf(ctx, "unexpected range ID %d", s.Desc.RangeID)
> ```

should this include the expected one?

---

*[pkg/storage/engine/bench_test.go, line 548 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiIZrhNmWxZSjTM9U:-KXfiIZrhNmWxZSjTM9V:bpjtwhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/bench_test.go#L548)):*
> ```Go
> 			ts := makeTS(timeutil.Now().UnixNano(), 0)
> 			if err := MVCCPut(context.Background(), batch, nil, key, ts, value, nil); err != nil {
> 				b.Fatalf("failed put: %s", err)
> ```

merp this can just be `.Fatal(err)`. just sayin'

---

*[pkg/storage/engine/engine.go, line 177 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfhwonLrxy6SP52Z_V:-KXfhwonLrxy6SP52Z_W:b-or11xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/engine.go#L177)):*
> ```Go
> 	// this engine. A write-only batch accumulates all mutations and applies them
> 	// atomically on a call to Commit(). Read operations return an error.
> 	NewWriteOnlyBatch() Batch
> ```

is it possible to have a new, narrower interface for this thing, rather than a bunch of runtime panics?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXfinFxnqRj6k4-Bzll:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfo0a7m3HGyUx0SS3P:b-44vuwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is there any reason this is a pointer? looks like it made sense in an earlier version when the proto field was nullable.
</blockquote></details>

No, there is no strong reason for it to be a pointer. There is also no strong reason for it not to be a pointer.

---

*[pkg/storage/replica_raftstorage.go, line 581 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiUOOPIXizLBylNWy:-KXfoBg7TCzvr08n-wUi:b-34340v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L581)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this include the expected one?
</blockquote></details>

The expected range ID is in the context.

---

*[pkg/storage/engine/bench_test.go, line 548 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiIZrhNmWxZSjTM9U:-KXfoPMvU_bz3DpR2nan:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/bench_test.go#L548)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

merp this can just be `.Fatal(err)`. just sayin'
</blockquote></details>

Done.

---

*[pkg/storage/engine/engine.go, line 177 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfhwonLrxy6SP52Z_V:-KXfp7eedObq4mB2XyLk:bbpc7ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/engine.go#L177)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it possible to have a new, narrower interface for this thing, rather than a bunch of runtime panics?
</blockquote></details>

Not easily. I just explored that and it requires a whole bunch of untangling. In particular, even defining a `WriteBatch` interface is irritating due to the `Close` method currently being defined on `Reader`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfqYkpJS_8AC4nLXZM:bd2r4iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No, there is no strong reason for it to be a pointer. There is also no strong reason for it not to be a pointer.
</blockquote></details>

In this case, I think there is - a pointer creates ambiguity because it is possible for it to be nil, and this field should never be nil.

---

*[pkg/storage/engine/engine.go, line 177 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfhwonLrxy6SP52Z_V:-KXfqJPxDw2IYYx24QwS:bwwiopw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/engine.go#L177)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not easily. I just explored that and it requires a whole bunch of untangling. In particular, even defining a `WriteBatch` interface is irritating due to the `Close` method currently being defined on `Reader`. 
</blockquote></details>

About what I expected. It'd be good to file an issue, given the number of external contributors we've been enjoying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfr3tNEhFz3_X8IVEI:b-omah8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

In this case, I think there is - a pointer creates ambiguity because it is possible for it to be nil, and this field should never be nil.
</blockquote></details>

Using a value requires copying which is cheap, but not free. It also consumes stack space in this instance. I think we need a better justification than documenting non-nilness.

---

*[pkg/storage/engine/engine.go, line 177 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfhwonLrxy6SP52Z_V:-KXfrwAeP_p7AgqV-vUq:bbuqczb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/engine/engine.go#L177)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

About what I expected. It'd be good to file an issue, given the number of external contributors we've been enjoying.
</blockquote></details>

This is low-priority but invasive and possibly destabilizing. Not a good combination. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfuCyia9eMLLjWXVsX:b5xod9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Using a value requires copying which is cheap, but not free. It also consumes stack space in this instance. I think we need a better justification than documenting non-nilness.
</blockquote></details>

Isn't this exactly the opposite of the usual wisdom? Do the thing that is clearest to human readers unless benchmarks justify doing otherwise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by petermattis** [comment]
Review status: 14 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXfiZaLPTP5aS4tp0vn:-KXfumcoMSQOfVY7XmUe:b41wqw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dc93bfb88f6693442e57e42e426a2ebe5df2987/pkg/storage/replica_raftstorage.go#L394)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Isn't this exactly the opposite of the usual wisdom? Do the thing that is clearest to human readers unless benchmarks justify doing otherwise?
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/11616 was needed because benchmarks did show that growing the stack was problematic. And the reason our stacks are so large is our pervasive use of values instead of pointers: creating values and passing them on the stack even when a pointer was readily available. This is exactly an instance of that. The caller has a pointer readily available, we should pass it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
I'm not saying that growing the stack is never problematic, but without
demonstrating that it is problematic in this instance, that argument does
not hold water.

This thread is unlikely to change your mind, so please don't hold off on
proceeding with this change on account of it.

**Comment by petermattis** [comment]
> I'm not saying that growing the stack is never problematic, but without demonstrating that it is problematic in this instance, that argument does not hold water.

Justifying every use of pointer vs value via a benchmark will ensure that we'll almost always use values.

**Comment by tamird** [comment]
...that's not an argument - either we make evidence-based decisions, or we
do not.

**Comment by petermattis** [comment]
> either we make evidence-based decisions, or we do not.

I don't think decision making is as black and white as that. We use evidence to make some decisions and then fold that evidence and those decisions into an internal model and heuristics that we use to make other decisions. We certainly don't base all of our decisions on evidence. I'm curious what evidence you would use to justify changing `IncomingSnapshot.State` from a pointer to a value.

**Comment by tamird** [comment]
On Mon, Nov 28, 2016 at 1:06 PM, Peter Mattis <notifications@github.com>
wrote:

> I'm curious what evidence you would use to justify changing
> IncomingSnapshot.State from a pointer to a value.
>
>
My argument is based on the assumption that the "default" is a to use a
value. At least, it is my recollection that this is the best practice
documented in some document authored by the Go maintainers. It's a wise
default because it more strongly encodes programmer intent than does a
never-nil pointer.

If we agree on the above, then we need justification to deviate from that
default, and if we do not, then we need to adjust that default. The problem
with making decisions based on internal models and heuristics is that they
create FUD - someone will come along at some point and wonder why that
thing is a pointer, and for them to discover that it was because of this
stack growth problem (or worse yet, suspicion thereof) will be completely
impossible.

**Comment by petermattis** [comment]
> My argument is based on the assumption that the "default" is a to use a value. At least, it is my recollection that this is the best practice documented in some document authored by the Go maintainers. It's a wise default because it more strongly encodes programmer intent than does a never-nil pointer.

You're probably thinking of https://github.com/golang/go/wiki/CodeReviewComments#pass-values:

> Don't pass pointers as function arguments just to save a few bytes. If a function refers to its argument x only as *x throughout, then the argument shouldn't be a pointer. Common instances of this include passing a pointer to a string (*string) or a pointer to an interface value (*io.Reader). In both cases the value itself is a fixed size and can be passed directly. This advice does not apply to large structs, or even small structs that might grow.

I'd be interested if there is other wisdom from the Go maintainers you're thinking of. Notice that last sentence. It is an important caveat.

**Comment by tamird** [comment]
Yeah, I re-read this thing when we were discussing pointer-vs-value in
Bram's recent PR. I recall another document that specifically mentioned
using a value for clarity, but I couldn't find it the other day.

In any case, if you choose to leave this as-is, the contract (never nil)
and the intent (saving stack space) should be clearly documented.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft.proto, line 107 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXpO1Sa6CAwPLRGXSQh:-KXpO1Sa6CAwPLRGXSQi:b-5ps83h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3677812a24258ad976e217d18bc36c71373a21/pkg/storage/raft.proto#L107)):*
> ```protobuf
> message SnapshotRequest {
>   message Header {
>     reserved 1; // range_descriptor
> ```

Nit: we don't generally leave comments about what reserved tags were formerly used for. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-:-KXpOQPdSK2V4pXa2_iK:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 11 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/raft.proto, line 107 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXpO1Sa6CAwPLRGXSQh:-KXpRF_BaBTeqNEaydJK:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3677812a24258ad976e217d18bc36c71373a21/pkg/storage/raft.proto#L107)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Nit: we don't generally leave comments about what reserved tags were formerly used for. 
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 394 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931#-KXpRdwqVV38AOAAQoPV:-KXpRdwqVV38AOAAQoPW:bukgv3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/520b7ed7becf1bc1d00d9db71b6c01b9dbf44fe7/pkg/storage/replica_raftstorage.go#L394)):*
> In any case, if you choose to leave this as-is, the contract (never nil) and the intent (saving stack space) should be clearly documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10931)*

**Pull request merged**
