### PR TITLE
coldata: fix behavior of Vec.Append in some cases when NULLs are present

### LINKED ISSUE #42774: sql/colexec: TestMergeJoiner failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/78f8482fd864376a26f32dd983afeb679d1c5977

Parameters:
```
TAGS=
GOFLAGS=-parallel=4
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestMergeJoiner PKG=github.com/cockroachdb/cockroach/pkg/sql/colexec TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1611682&tab=buildLog

```

panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 3527 [running]:
testing.tRunner.func1(0xc000598200)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1eef680, 0x3b989a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/col/coldata.(*Bytes).Get(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:96
github.com/cockroachdb/cockroach/pkg/col/coldata.(*memColumn).Append(0xc000d2db40, 0x1, 0x271c080, 0xc000d2d980, 0xc000436800, 0x400, 0x400, 0x0, 0x1, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/col/coldata/vec.eg.go:56 +0x2230
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Allocator).Append.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:118 +0xa6
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Allocator).performOperation(0xc00040da40, 0xc000977600, 0x1, 0x1, 0xc000977610)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:96 +0xfd
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Allocator).Append(0xc00040da40, 0x271c080, 0xc000d2db40, 0x1, 0x271c080, 0xc000d2d980, 0xc000436800, 0x400, 0x400, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:118 +0xfe
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*mergeJoinBase).appendToBufferedGroup(0xc000e3c000, 0xc000e3c028, 0x2706540, 0xc000d2d8c0, 0xc000436800, 0x400, 0x400, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/mergejoiner.go:421 +0x231
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*mergeJoinFullOuterOp).probeBodyLSeltrueRSeltrue(0xc000e3c000, 0x26d5b00, 0xc000052108)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/mergejoiner_fullouter.eg.go:7985 +0x1a9c5
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*mergeJoinFullOuterOp).probe(0xc000e3c000, 0x26d5b00, 0xc000052108)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/mergejoiner_fullouter.eg.go:38833 +0x1aa
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*mergeJoinFullOuterOp).Next(0xc000e3c000, 0x26d5b00, 0xc000052108, 0x207c420, 0xc000d18101)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/mergejoiner_fullouter.eg.go:39025 +0x2f4
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*opTestOutput).next(0xc000d2d700, 0x26d5b00, 0xc000052108, 0xc000834000, 0xc000d181b0, 0x2706540)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:765 +0xbb
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*opTestOutput).VerifyAnyOrder(0xc000d2d700, 0x1000, 0x1000)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:802 +0x78
github.com/cockroachdb/cockroach/pkg/sql/colexec.TestMergeJoiner.func1(0xc000d2d700, 0xc000d2d700, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/mergejoiner_test.go:1634 +0xcd
github.com/cockroachdb/cockroach/pkg/sql/colexec.runTestsWithoutAllNullsInjection.func1(0xc000598200, 0xc00040da20, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:211 +0x174
github.com/cockroachdb/cockroach/pkg/sql/colexec.runTestsWithFn.func1(0xc000598200)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/utils_test.go:347 +0x298
testing.tRunner(0xc000598200, 0xc0004c6d20)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001f2a00, 0x2156ebc, 0xf, 0x220ae70, 0x4c4701)
	/usr/local/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0005aa300)
	/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0005aa300, 0xc0006a5dc8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc0002ed020, 0x3bba220, 0x5f, 0x5f, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0004cd400, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x162
github.com/cockroachdb/cockroach/pkg/sql/colexec.TestMain.func1(0xc0004cd400, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/main_test.go:46 +0x1b4
github.com/cockroachdb/cockroach/pkg/sql/colexec.TestMain(0xc0004cd400)
```

### PR DESCRIPTION
**Pull request by yuzefovich**
We would always Get and then Set a value while Append'ing without paying
attention to whether the value is actually NULL. This can lead to
problems in case of flat bytes if the necessary invariant is
unmaintained. Now this is fixed by explicitly enforcing the invariant.
Additionally, this commit ensures that the destination slice has the
desired capacity before appending one value at a time (in case of
a present selection vector).

I tried approach with paying attention to whether the value is NULL
before appending it and saw a significant performance hit, so I think
this approach is the least evil.

Fixes: #42774.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/vec_test.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43720#-LyV89Eg30C0hKVN3AfT:-LyV89Eh2ZKce1RLEn5y:b-kxq82n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e79ada623914bc7b0ae00b2023ab25e8d96e51a8/pkg/col/coldata/vec_test.go#L245)):*
> ```Go
> 			dest.Append(sliceArgs)
> 		})
> 	}
> ```

We might want to consider adding an equality check at the end.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_test.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43720#-LyV89Eg30C0hKVN3AfT:-LyVuDSQ1-HyQ-02GxpN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e79ada623914bc7b0ae00b2023ab25e8d96e51a8/pkg/col/coldata/vec_test.go#L245)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We might want to consider adding an equality check at the end.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43720#-:-Lydo4pk6vTwYM5goR1G:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
