### PR TITLE
opt: Add Filters operator and support list construction in replace patterns

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains two related commits. The first adds support for constructing lists in Optgen replace patterns. The second makes use of that to add support for a new Filters operator.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 24 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7GxNVB87IUsRsVW_4N:-L7GxNVB87IUsRsVW_4O:b-n5ctzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/bool.opt#L55)):*
> ```
> #   - Flattens nested And operands by merging their conditions into parent And
> # This rule is especially important when we build a simplified filter.
> [SimplifyAnd, Normalize]
> ```

Do we want a similar rule for `Filters`? It might be useful during pushdown (e.g. pushing down a `False` `ON` condition)

---

*[pkg/sql/opt/xform/rules/join.opt, line 43 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7Gwdot15gHvL3i66y5:-L7Gwdot15gHvL3i66y6:bokad6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/join.opt#L43)):*
> ```
>     $left:*
>     $right:*
>     $filter:^(Filters | And | True | False)
> ```

Why is this different than the Select version? (The other one also disallows `Null`)

I think we should let `Null` go under `Filters` and then have a rule that normalizes `(Filters Null)` to `False` (or do that as part of a SimplifyFilters rule). That way we won't need two versions of the Null -> False rule.

I would also consider putting all the filter-related rules under a `filters.opt`, it would be more useful to see all the rules in one place.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702)*

**Comment by andy-kimball** [comment]
Review status: 0 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7GxNVB87IUsRsVW_4N:-L7H7ERD1YZPwFZ2NCQL:b-sxbzdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/bool.opt#L55)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we want a similar rule for `Filters`? It might be useful during pushdown (e.g. pushing down a `False` `ON` condition)
</blockquote></details>

I originally had this rule handle `Filters` as well. But then I couldn't come up with a single test case that would actually hit that path, since the `And` rules end up handling everything before the `And` becomes a `Filter`. Can you explain the pushdown case you're thinking of in more detail? Can you think of a test case that would actually trigger this rule if it applied to `Filters`?

---

*[pkg/sql/opt/xform/rules/join.opt, line 43 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7Gwdot15gHvL3i66y5:-L7HA1FaCxGTEW88wRDk:bj40noo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/join.opt#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is this different than the Select version? (The other one also disallows `Null`)

I think we should let `Null` go under `Filters` and then have a rule that normalizes `(Filters Null)` to `False` (or do that as part of a SimplifyFilters rule). That way we won't need two versions of the Null -> False rule.

I would also consider putting all the filter-related rules under a `filters.opt`, it would be more useful to see all the rules in one place.
</blockquote></details>

The omission of `Null` was inadvertent.

I agree regarding handling `Null` differently in `Filters` than `And`/`Or`. I've made that change. PTAL.

I thought about a separate `filters.opt` file. My thinking was that I'd always locate rules in files according to their top-level match name, so they're easy to find. But there's definitely an argument to be made to organize them according to what they're trying to do (constant-folding, null-handling, needed cols, filter pushdown, etc). I think both ways will be annoying in some ways and convenient in others. For example, there's a ton of overlap between `Filters` and `And`, so much so that I use both choices in several patterns. Extracting those to another file would be awkward. It's worth more discussion.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7GxNVB87IUsRsVW_4N:-L7HQp727EeTpKwx65kQ:b-xv72u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/bool.opt#L55)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I originally had this rule handle `Filters` as well. But then I couldn't come up with a single test case that would actually hit that path, since the `And` rules end up handling everything before the `And` becomes a `Filter`. Can you explain the pushdown case you're thinking of in more detail? Can you think of a test case that would actually trigger this rule if it applied to `Filters`?
</blockquote></details>

Since I'm working on #23664:
```
build
SELECT * FROM (SELECT x FROM onecolumn WHERE x > 1) RIGHT JOIN twocolumn ON false
----
project
 ├── columns: x:1(int) x:3(int) y:4(int)
 ├── right-join
 │    ├── columns: onecolumn.x:1(int) twocolumn.x:3(int) twocolumn.y:4(int) twocolumn.rowid:5(int!null)
 │    ├── project
 │    │    ├── columns: onecolumn.x:1(int)
 │    │    ├── select
 │    │    │    ├── columns: onecolumn.x:1(int) onecolumn.rowid:2(int!null)
 │    │    │    ├── scan
 │    │    │    │    └── columns: onecolumn.x:1(int) onecolumn.rowid:2(int!null)
 │    │    │    └── gt [type=bool, outer=(1)]
 │    │    │         ├── variable: onecolumn.x [type=int, outer=(1)]
 │    │    │         └── const: 1 [type=int]
 │    │    └── projections [outer=(1)]
 │    │         └── variable: onecolumn.x [type=int, outer=(1)]
 │    ├── scan
 │    │    └── columns: twocolumn.x:3(int) twocolumn.y:4(int) twocolumn.rowid:5(int!null)
 │    └── false [type=bool]
 └── projections [outer=(1,3,4)]
      ├── variable: onecolumn.x [type=int, outer=(1)]
      ├── variable: twocolumn.x [type=int, outer=(3)]
      └── variable: twocolumn.y [type=int, outer=(4)]
```

The `false` will get pushed down and when it reaches the select node, I assume there would be a rule that adds it to the `filters` under `select`. So we would effectively have both `x > 1` AND `false` there.

I know it's a contrived example, but the `false` could be there from folding a more complicated expression (potentially containing a placeholder). At some point we will probably want to have a rule that transforms a `false` filter into a "zeroop" that produces no rows.

---

*[pkg/sql/opt/xform/rules/join.opt, line 43 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7Gwdot15gHvL3i66y5:-L7HSF9F0OkKtbni0iIN:b-y7edy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/join.opt#L43)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The omission of `Null` was inadvertent.

I agree regarding handling `Null` differently in `Filters` than `And`/`Or`. I've made that change. PTAL.

I thought about a separate `filters.opt` file. My thinking was that I'd always locate rules in files according to their top-level match name, so they're easy to find. But there's definitely an argument to be made to organize them according to what they're trying to do (constant-folding, null-handling, needed cols, filter pushdown, etc). I think both ways will be annoying in some ways and convenient in others. For example, there's a ton of overlap between `Filters` and `And`, so much so that I use both choices in several patterns. Extracting those to another file would be awkward. It's worth more discussion.
</blockquote></details>

I see, that organization makes sense too.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/xform/rules/bool.opt, line 83 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23702#-L7HZGHri1HzULsYRPy9:-L7HZGHsdlEhufsdSpCN:b91f3dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad8ab5b9b43675c5498e7f2b9819fc8b30559d60/pkg/sql/opt/xform/rules/bool.opt#L83)):*
> ```
> (Null (BoolType))
> 
> # FoldNullFilters replaces a Filters operator with False if all of its operands
> ```

Why if all of its operands? If any one of them is NULL, the filter is never true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23702)*

**Comment by andy-kimball** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7GxNVB87IUsRsVW_4N:-L7IFH8z1ZXZ9wrkK0tY:bim6r1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c3bacfc3e8fc4ef224822dd7162f563e92530/pkg/sql/opt/xform/rules/bool.opt#L55)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Since I'm working on #23664:
```
build
SELECT * FROM (SELECT x FROM onecolumn WHERE x > 1) RIGHT JOIN twocolumn ON false
----
project
 ├── columns: x:1(int) x:3(int) y:4(int)
 ├── right-join
 │    ├── columns: onecolumn.x:1(int) twocolumn.x:3(int) twocolumn.y:4(int) twocolumn.rowid:5(int!null)
 │    ├── project
 │    │    ├── columns: onecolumn.x:1(int)
 │    │    ├── select
 │    │    │    ├── columns: onecolumn.x:1(int) onecolumn.rowid:2(int!null)
 │    │    │    ├── scan
 │    │    │    │    └── columns: onecolumn.x:1(int) onecolumn.rowid:2(int!null)
 │    │    │    └── gt [type=bool, outer=(1)]
 │    │    │         ├── variable: onecolumn.x [type=int, outer=(1)]
 │    │    │         └── const: 1 [type=int]
 │    │    └── projections [outer=(1)]
 │    │         └── variable: onecolumn.x [type=int, outer=(1)]
 │    ├── scan
 │    │    └── columns: twocolumn.x:3(int) twocolumn.y:4(int) twocolumn.rowid:5(int!null)
 │    └── false [type=bool]
 └── projections [outer=(1,3,4)]
      ├── variable: onecolumn.x [type=int, outer=(1)]
      ├── variable: twocolumn.x [type=int, outer=(3)]
      └── variable: twocolumn.y [type=int, outer=(4)]
```

The `false` will get pushed down and when it reaches the select node, I assume there would be a rule that adds it to the `filters` under `select`. So we would effectively have both `x > 1` AND `false` there.

I know it's a contrived example, but the `false` could be there from folding a more complicated expression (potentially containing a placeholder). At some point we will probably want to have a rule that transforms a `false` filter into a "zeroop" that produces no rows.
</blockquote></details>

I added a `SimplifyFilters` rule.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 83 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-L7HZGHri1HzULsYRPy9:-L7Hc2vB6djkPijskH2b:be5lgbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad8ab5b9b43675c5498e7f2b9819fc8b30559d60/pkg/sql/opt/xform/rules/bool.opt#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why if all of its operands? If any one of them is NULL, the filter is never true.
</blockquote></details>

I pulled that out from `FoldNullAndOr`. But you're right, in this special-case the rule can be stricter. Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23702#-:-L7KRQZt9cLR1Qyl4Vyh:bnfp4nl)*

**Pull request merged**
