### PR TITLE
sql: Move remaining handling of DatabaseDescriptors into DatabaseAccessor

### PR DESCRIPTION
**Pull request by nvb**
This change add the following methods to the `DatabaseAccessor` interface:
- `createDatabase`
- `renameDatabase`

The change is needed because #7965 necessitates mocking out certain `DatabaseDescriptor` accesses. Moving all of these accesses into the `DatabaseAccessor` interface allows the changes needed for #7965 to be much more localized.

A good sign that this is the correct boundary of abstraction is that `databaseKey` is now only used within the `DatabaseAccessor` implementation.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8037)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/database.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcEth-NhA0_K25M3uF:-KNcEth-NhA0_K25M3uG:-1176024164) ([raw file](https://github.com/cockroachdb/cockroach/blob/290e046b52950e3d75b7a3b83034aaccbe333c90/sql/database.go#L207)):*
> ```Go
> func (p *planner) createDatabase(desc *sqlbase.DatabaseDescriptor, ifNotExists bool) (bool, error) {
> 	if desc.Name == "" {
> 		panic("DatabaseDescriptor must include a non-empty database name")
> ```

seems like you could return an error.

actually, why have this check at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-:-KNcFFBhn2GyrGjVZCYe:1417088721)*

**Comment by nvanbenschoten** [comment]
TFTR

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/database.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcEth-NhA0_K25M3uF:-KNcGYMDm4oGQ4_mvmou:-2050800068) ([raw file](https://github.com/cockroachdb/cockroach/blob/290e046b52950e3d75b7a3b83034aaccbe333c90/sql/database.go#L207)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems like you could return an error.
> 
> actually, why have this check at all?
</details>
Yeah this is asserted one layer up so no need for an error. I just like having preconditions like these since this is technically an interface impl that could be called from other places. Also, I'm guessing `databaseKey{""}` would cause issues.

I'll remove it if you think it should be though. If not, I'll document the assertion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-:-KNcI2ssbd69RY20ZVz0:677071605)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/database.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcEth-NhA0_K25M3uF:-KNcIqAYY3dJDttc5uA1:-1191610727) ([raw file](https://github.com/cockroachdb/cockroach/blob/290e046b52950e3d75b7a3b83034aaccbe333c90/sql/database.go#L207)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Yeah this is asserted one layer up so no need for an error. I just like having preconditions like these since this is technically an interface impl that could be called from other places. Also, I'm guessing `databaseKey{""}` would cause issues.
> 
> I'll remove it if you think it should be though. If not, I'll document the assertion.
</details>
I'd remove it. I'm not really sure `databaseKey{""}` would cause problems, either. Nothing special about the empty string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/database.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcEth-NhA0_K25M3uF:-KNcJdTpUutLDlkjKV6l:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/290e046b52950e3d75b7a3b83034aaccbe333c90/sql/database.go#L207)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'd remove it. I'm not really sure `databaseKey{""}` would cause problems, either. Nothing special about the empty string.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3, 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/database.go, line 121 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcs_wBwzoZi7a_SpX-:-KNcs_wBwzoZi7a_SpX0:762517310) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f8832ea3c0fed18592fa63574a7f819ce85b/sql/database.go#L121)):*
> ```Go
> 
> 	// renameDatabase attempts to rename the database with the provided DatabaseDescriptor
> 	// to a new name. The method will mutate the provided DatabaseDescriptor, updating it's
> ```

s/it's/its/

---

*[sql/database.go, line 218 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNctHKFwoWD2tckxNjN:-KNctHKFwoWD2tckxNjO:1727438673) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f8832ea3c0fed18592fa63574a7f819ce85b/sql/database.go#L218)):*
> ```Go
> // renameDatabase implements the DatabaseAccessor interface.
> func (p *planner) renameDatabase(oldDesc *sqlbase.DatabaseDescriptor, newName string) error {
> 	descKey := sqlbase.MakeDescMetadataKey(oldDesc.GetID())
> ```

nit: move this next to the declaration of descDesc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-:-KNctVkfzWfCWM9J8hvj:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/database.go, line 121 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNcs_wBwzoZi7a_SpX-:-KNd8cJ1dB9XT6kEHsjZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f8832ea3c0fed18592fa63574a7f819ce85b/sql/database.go#L121)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> s/it's/its/
</details>
Done.

---

*[sql/database.go, line 218 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037#-KNctHKFwoWD2tckxNjN:-KNd8csbSkZ_vF7iPhdx:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f8832ea3c0fed18592fa63574a7f819ce85b/sql/database.go#L218)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: move this next to the declaration of descDesc
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8037)*

**Pull request merged**
