### PR TITLE
opt: add xform rules to push join through index join

### PR DESCRIPTION
**Pull request by RaduBerinde**
When there is a join on top of an index join and the ON condition only
refers to columns that are available before the index join, we can do
the join first and then join with the primary index.

The main goal is to be able to do lookup joins that use non-covering
indexes; this requires the lookup join to happen before ("under") the
index join. The new rules in conjunction with the existing lookup join
rules achieve this.

Release note: None

As is the PR is light on tests; I am working on reenabling the relevant lookup join tests.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/rules/join.opt, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIHv2pBBQSOEWjDBkIo:-LIHv2pBBQSOEWjDBkIp:bgm71ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L71)):*
> ```
> 
> # PushJoinThroughIndexJoin takes an expression which does an index join followed
> # by a join with an expression which first does the join and then joins with the
> ```

I think there's a word or two missing here - `and produces an expression which first...`?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/rules/join.opt, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIHv2pBBQSOEWjDBkIo:-LII0nzn7UAn2XCDFvlB:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L71)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think there's a word or two missing here - `and produces an expression which first...`?
</blockquote></details>

Fixed.

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-:-LII4u_B82bUN9B5vnZN:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII3FLQ1vk4gP9WvdZi:-LII3FLQ1vk4gP9WvdZj:btoxfkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/custom_funcs.go#L645)):*
> ```Go
> 	//
> 	// The lookup columns are the lookup columns in the original index join,
> 	// without any columns that are already available in its input. Note that the
> ```

This is a bit ambiguous, making it difficult to parse-- what does "its" refer to here?
___
*[pkg/sql/opt/xform/rules/join.opt, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII1b-s-tCEmIGAlNC4:-LII1b-tBybM1KpduW5y:bfptmvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L74)):*
> ```
> # index. This can be advantageous when the join has fewer results than the
> # right input; in particular, the new join can be converted to a lookup join by
> # other rules.
> ```

Why can't it be converted to a lookup join when it's above the index join?
___
*[pkg/sql/opt/xform/rules/join.opt, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII1TLDC8JN5vomZXfG:-LII1TLDC8JN5vomZXfH:b-87ufj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L77)):*
> ```
> #
> # The IndexJoin needs to change into a more general LookupJoin because the
> # other's side columns need to be "plumbed" through.
> ```

I don't really understand this sentence - can you elaborate a bit?
___
*[pkg/sql/opt/xform/rules/join.opt, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII54oODxO3-lhPX7rC:-LII54oODxO3-lhPX7rD:b-c3cbfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf81e66c01e960b756276ca1ca0eac2733dd354/pkg/sql/opt/xform/rules/join.opt#L84)):*
> ```
> #  Left  IndexJoin                      /   \
> #           |                          /     \
> #         Right                      Left  Right
> ```

Nice ascii art! :art:

**Review by andy-kimball — APPROVED** [review]
:lgtm: with some comments, cool stuff!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-:-LIIvc0Z9QWk0xpUfoFo:b-2o5wl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIshJb9BTtnFFP0D9v:-LIIshJb9BTtnFFP0D9w:b-b0vyxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/custom_funcs.go#L629)):*
> ```Go
> func (c *CustomFuncs) PushJoinThroughIndexJoin(
> 	newJoin memo.GroupID,
> 	joinType opt.Operator,
> ```

Can't you get `joinType` from `newJoin`, rather than having to pass it separately?
___
*[pkg/sql/opt/xform/rules/join.opt, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIrMHa7jsUG_EwXQur:-LIIrMHa7jsUG_EwXQus:b-wchbtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/rules/join.opt#L95)):*
> ```
> )
> =>
> (PushJoinThroughIndexJoin
> ```

Maybe you already tried and rejected, but what about this instead:
```
(LookupJoin
  $newJoin:((OpName) $left $right $on)
  (True)
  (HoistIndexJoinDef $indexJoinDef $newJoin)
)
```
Where `HoistIndexJoinDef` creates the `LookupJoinDef` that results from hoisting the `IndexJoin` up above some pushed-down operator. If we pushed other operators down through lookup join, maybe such a method could be reused? I also like showing the structure of the resulting `LookupJoin` in the replace pattern.
___
*[pkg/sql/opt/xform/rules/join.opt, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIqwNGBecUUHuD1rv2:-LIIqwNGBecUUHuD1rv3:bnflnob) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/rules/join.opt#L130)):*
> ```
>     (OpName)
>     $indexJoinDef
>     (Filters (ExtractUnboundConditions $onList $newJoin))
> ```

Fancy use of the new ability to bind expressions in the replace pattern. : )
___
*[pkg/sql/opt/xfunc/custom_funcs.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIqsB_2Tz37qlXq0yw:-LIIqsB_2Tz37qlXq0yx:b-916y30) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xfunc/custom_funcs.go#L170)):*
> ```Go
> }
> 
> func (c *CustomFuncs) ExtractBoundConditions2(
> ```

Need comment.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/custom_funcs.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIshJb9BTtnFFP0D9v:-LIJXl6-Ab-n-fc-dcQE:b11aksb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/custom_funcs.go#L629)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can't you get `joinType` from `newJoin`, rather than having to pass it separately?
</blockquote></details>

Using `memo.MakeNormExprView`? Is that guaranteed to work as intended? In principle, couldn't the `newJoin` expression already exist in a group that has a different normalized expression (which maybe is not even a join)? Hm, I guess not because the explore xforms don't add new fingerprints? Either way, passing it explicitly seems a small price to pay to not have to go through this reasoning :)
___
*[pkg/sql/opt/xform/rules/join.opt, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIrMHa7jsUG_EwXQur:-LIJWiL0Bt5v3iB9K6Op:b-n5edl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/rules/join.opt#L95)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe you already tried and rejected, but what about this instead:
```
(LookupJoin
  $newJoin:((OpName) $left $right $on)
  (True)
  (HoistIndexJoinDef $indexJoinDef $newJoin)
)
```
Where `HoistIndexJoinDef` creates the `LookupJoinDef` that results from hoisting the `IndexJoin` up above some pushed-down operator. If we pushed other operators down through lookup join, maybe such a method could be reused? I also like showing the structure of the resulting `LookupJoin` in the replace pattern.
</blockquote></details>

Hm, good idea. It should work, I'll give it a shot. I started out with more complicated code that added some projections to rename column IDs before I realized I can just make sure the lookup join doesn't have the same column ID on both sides.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII3FLQ1vk4gP9WvdZi:-LIM7Xma0vnGTiQ_bKht:b8hvb0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/custom_funcs.go#L645)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a bit ambiguous, making it difficult to parse-- what does "its" refer to here?
</blockquote></details>

Extended.
___
*[pkg/sql/opt/xform/rules/join.opt, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII1b-s-tCEmIGAlNC4:-LIM7caRDjwrPxMAihe2:b2e2oi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why can't it be converted to a lookup join when it's above the index join?
</blockquote></details>

Lookup join needs a scan on the lookup side (it needs an index to look up from).
___
*[pkg/sql/opt/xform/rules/join.opt, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII1TLDC8JN5vomZXfG:-LIM8GD62o4VjrKHAM81:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L77)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't really understand this sentence - can you elaborate a bit?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIrMHa7jsUG_EwXQur:-LIMDc_n1LYwXqqnYBxa:b-zk56z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/rules/join.opt#L95)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, good idea. It should work, I'll give it a shot. I started out with more complicated code that added some projections to rename column IDs before I realized I can just make sure the lookup join doesn't have the same column ID on both sides.
</blockquote></details>

Done. Much cleaner, thanks.
___
*[pkg/sql/opt/xfunc/custom_funcs.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIqsB_2Tz37qlXq0yw:-LIM8iOq0ZRe7kfQCt1n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xfunc/custom_funcs.go#L170)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Need comment.
</blockquote></details>

Done.

**Review by andy-kimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 629 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIIshJb9BTtnFFP0D9v:-LIMPAYa8fMZh8KPwh7_:b-u7iia6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23a740d1dc788e977432dee974fb1ac7cd43502/pkg/sql/opt/xform/custom_funcs.go#L629)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Using `memo.MakeNormExprView`? Is that guaranteed to work as intended? In principle, couldn't the `newJoin` expression already exist in a group that has a different normalized expression (which maybe is not even a join)? Hm, I guess not because the explore xforms don't add new fingerprints? Either way, passing it explicitly seems a small price to pay to not have to go through this reasoning :)
</blockquote></details>

Ah, right, I forgot this was exploration rule.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 650 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIMge018xyJHlUmc-Gt:-LIMge027DqusQY0G4Dj:b9j5y6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1990739ab29f3f70b479dfb77d2c01f8634966db/pkg/sql/opt/xform/custom_funcs.go#L650)):*
> ```Go
> 	//  SELECT * FROM abc JOIN xyz ON a=y
> 	//
> 	// We want to first join abc with the index on y (which provides columns y, z)
> ```

should be "provides columns y, x"
___
*[pkg/sql/opt/xform/rules/join.opt, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LII1b-s-tCEmIGAlNC4:-LIMh7V40o6SSIFU-cfJ:b-jbbyiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6085a5af30b2cb90fc86d38dc65d15b19e40d216/pkg/sql/opt/xform/rules/join.opt#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Lookup join needs a scan on the lookup side (it needs an index to look up from).
</blockquote></details>

Ah got it - thanks!
___
*[pkg/sql/opt/xform/rules/join.opt, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIMh-k9A8YqjF9lzGB4:-LIMh-k9A8YqjF9lzGB5:bey7se8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1990739ab29f3f70b479dfb77d2c01f8634966db/pkg/sql/opt/xform/rules/join.opt#L83)):*
> ```
> #         Right                      Left  Right
> #
> # Noe that the IndexJoin becomes a more general LookupJoin because an IndexJoin
> ```

Noe -> Note

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 650 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIMge018xyJHlUmc-Gt:-LIMmGyJAhDPHXhcqUgi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1990739ab29f3f70b479dfb77d2c01f8634966db/pkg/sql/opt/xform/custom_funcs.go#L650)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should be "provides columns y, x"
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIMh-k9A8YqjF9lzGB4:-LIMmMKQ7jTpCEo3Ie0C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1990739ab29f3f70b479dfb77d2c01f8634966db/pkg/sql/opt/xform/rules/join.opt#L83)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Noe -> Note
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by RaduBerinde** [comment]
While working on more tests, I found some problems in the execution:
 - the join reader processor has a bug related to NULLs (reopened #27032, should be easy to fix)
 - the tenporary local execution path of lookupJoin is to convert to a hash join and requires that all the equality columns are output by the two sides; this is no longer the case with the index-join that becomes lookup-join. The fix for this isn't trivial.

**Comment by RaduBerinde** [comment]
Ok, this change is ready. The distsql execution issue was fixed, and I have fixed the (temporary) local lookup join path.

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 5 of 7 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-:-LIh8iEGCZzGkQVAc9Bt:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/lookup_join.go, line 107 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIh6Sab3Ry20qeIrOJf:-LIh6Sab3Ry20qeIrOJg:b-rmtaix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2bbbe04154eb2b4c00dfb014f536e79a0e1392c/pkg/sql/lookup_join.go#L107)):*
> ```Go
> 			n.filterVars = tree.MakeIndexedVarHelper(n, len(n.cols))
> 			// startExec was already called for the node, run it again.
> 			n.startExec(params)
> ```

What if there are multiple columns that need to be added? Wouldn't it be better to add all of those columns first and then call this once?
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIh7Him3KQUzRszGPJi:-LIh7Him3KQUzRszGPJj:b-2eovha) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2bbbe04154eb2b4c00dfb014f536e79a0e1392c/pkg/sql/logictest/testdata/logic_test/lookup_join#L279)):*
> ```
> 
> #query TTTTT
> #EXPLAIN (VERBOSE) SELECT small.a, large.d FROM small JOIN large ON small.a = large.b
> ```

Should this be removed?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/lookup_join.go, line 107 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIh6Sab3Ry20qeIrOJf:-LIhFeWrDNCVZxspLj2O:b-nbfvdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2bbbe04154eb2b4c00dfb014f536e79a0e1392c/pkg/sql/lookup_join.go#L107)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if there are multiple columns that need to be added? Wouldn't it be better to add all of those columns first and then call this once?
</blockquote></details>

You're right, but I went with the simplest code since this entire code path is already a temporary hack.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 279 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/27923#-LIh7Him3KQUzRszGPJi:-LIhF_sF3bV-MMXrW-7R:bm8t8i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2bbbe04154eb2b4c00dfb014f536e79a0e1392c/pkg/sql/logictest/testdata/logic_test/lookup_join#L279)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Ah yes, good catch. Will remove, I used it to debug

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27923)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
