### PR TITLE
rac2: specify lock ordering, and add ReplicaSet

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #128308

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm: - see nit on using `roachpb.ReplicaSet`, I don't feel strongly enough to block on it but it'd be worthwhile writing down why we don't use it.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128706#-:-O46ZqKW-3bL4Otv5tEo:bcim97o)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128706#-O46Z6lu3xWsKgVXP1vw:-O46Z6lu3xWsKgVXP1vx:b-5w9hf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/79413343de667fa8537d8c906f2212bd24d5850a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L47)):*
> ```Go
> 	//
> 	// Requires replica.raftMu to be held.
> 	SetReplicasRaftMuLocked(ctx context.Context, replicas ReplicaSet) error
> ```

nit: do we need to use a new replica set type, instead of using the existing `roachpb.ReplicaSet`? It makes sense to use it internally, within the datastructure if we want map accesses but as an argument it might be nicer to use `roachpb.ReplicaSet`, which is a wrapped slice and used in many other parts of KV for similar purposes.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128706)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128706#-O46Z6lu3xWsKgVXP1vw:-O46s5Wn6qbkqIBk5lih:b-45eryo) ([raw file](https://github.com/cockroachdb/cockroach/blob/79413343de667fa8537d8c906f2212bd24d5850a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L47)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: do we need to use a new replica set type, instead of using the existing `roachpb.ReplicaSet`? It makes sense to use it internally, within the datastructure if we want map accesses but as an argument it might be nicer to use `roachpb.ReplicaSet`, which is a wrapped slice and used in many other parts of KV for similar purposes.
</blockquote></details>

The `replicaRACv2Integration` uses a map for lookups by `ReplicaID`. There is also one case of such lookups in `RangeControllerImpl`. These sets are only replaced with a new map (never updated), so it is convenient to share.

And it reduces unnecessary code: in `replicaRACv2Integration` it would need to produce a map for its internal use and produce a `roachpb.ReplicaSet` for `RangeController`, which would then proceed to convert the `roachpb.ReplicaSet` to a map.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

I tweaked the commentary about `ReplicaSet` and `SetReplicasRaftMuLocked`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128706#-:-O46uXTkEz8MY5j7weL7:b-3h2t12)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128706#-:-O46uovrERCzfCCosyg6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
