### PR TITLE
geo/geomfn: implement ST_Buffer

### LINKED ISSUE #48802: geo: implement ST_Buffer({text,float8,text}) -> geometry
Implement `ST_Buffer` on arguments {text,float8,text}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48441 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-17T19:29:14Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48803: geo: implement ST_Buffer({text,float8}) -> geometry
Implement `ST_Buffer` on arguments {text,float8}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48441 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-17T19:29:14Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48804: geo: implement ST_Buffer({text,float8,int4}) -> geometry
Implement `ST_Buffer` on arguments {text,float8,int4}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48441 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-17T19:29:14Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48890: geo/geomfn: implement ST_Buffer({geometry,float8,int4})
Implement `ST_Buffer` on arguments {geometry,float8,int4}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-20T02:07:31Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48891: geo/geomfn: implement ST_Buffer({geometry,float8,text})
Implement `ST_Buffer` on arguments {geometry,float8,text}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-20T02:07:31Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Implemented ST_Buffer. Had to write our own parsing logic to make it
compatible with C.

Also ran clang-format and fixed up a few bad infos.

Resolves #48890
Resolves #48891
Resolves #48802
Resolves #48803
Resolves #48804

Release note (sql change): Implement ST_Buffer for geometry and string
variants.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-:-M8ln5OS90ulyCgkE8vL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geomfn/buffer.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lkUC96UTsJWNua0Xp:-M8lkUC96UTsJWNua0Xq:bnasc3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/geo/geomfn/buffer.go#L50)):*
> ```Go
> // the BufferParams form.
> // The string must be of the same format as specified by https://postgis.net/docs/ST_Buffer.html.
> // Returns the BufferParams, as well as the modified distance.
> ```

does PostGIS support all these parameters for geography too?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lllzYAP4i-6SVopoA:-M8lllzZ2E1xxzV5k464:bu7dinz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L327)):*
> ```Go
> 
> var stBufferWithParamsInfoBuilder = infoBuilder{
> 	info: `Returns a Geometry that represents all points whose distance is less than or equal to the given distance.
> ```

... to the given distance from the given geometry.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lm2uqEUa_veMyD9Gy:-M8lm2uqEUa_veMyD9Gz:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L339)):*
> ```Go
> 
> var stBufferWithQuadSegInfoBuilder = infoBuilder{
> 	info: `Returns a Geometry that represents all points whose distance is less than or equal to the given distance.
> ```

ditto
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lmg8i-4JbKEh3ZUeA:-M8lmg8i-4JbKEh3ZUeB:bl4x6gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L2015)):*
> ```Go
> 				{"geometry_str", types.String},
> 				// This should be float, but for this to work equivalently to the psql type system,
> 				// we have to make a decimal definition.
> ```

is this the first time in CRDB that we are having to do this `types.{Float,Decimal}` dance? And are there any thoughts on how we could get rid of this duplication in the future?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49722)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geomfn/buffer.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lkUC96UTsJWNua0Xp:-M8mex3W7fEWGydgAGfh:bpdlf7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/geo/geomfn/buffer.go#L50)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does PostGIS support all these parameters for geography too?
</blockquote></details>

Yep! But it has a hack to do it...coming soon!
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lllzYAP4i-6SVopoA:-M8mfE7kBk_Ds-yoLEMe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L327)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... to the given distance from the given geometry.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lm2uqEUa_veMyD9Gy:-M8mfEeI9UKaCD_8x8jX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 2015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49722#-M8lmg8i-4JbKEh3ZUeA:-M8mfF3BBrgbXXxrW3sH:b4ndt04) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cd25d6080a7fb5b65956ecc5edb6d9ba9a10f6c/pkg/sql/sem/builtins/geo_builtins.go#L2015)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this the first time in CRDB that we are having to do this `types.{Float,Decimal}` dance? And are there any thoughts on how we could get rid of this duplication in the future?
</blockquote></details>

there's been others. the work on implicit casts will resolve this, but that is kinda "off the table"for now...

**Comment by otan** [comment]
bors r=summerbhola

**Comment by otan** [comment]
bors r=summerbhola

**Pull request merged**
