### PR TITLE
[DNM] storage: add a drop deadline to zone config, process via gc queue

### PR DESCRIPTION
**Pull request by spencerkimball**
Added an internal section to the GC Policy which contains a deadline
for dropping key ranges controlled by the zone config. This section
has a "-" yaml tag so it cannot be set via the CLI.

The gc queue now takes the drop deadline into consideration when
determining whether to queue, and takes a separate path for GC
to invoke `ClearRange` and also compact the affected key range in
RocksDB.

Added a `CompactRange` method to the RocksDB engine.

### CODE REVIEW

**Comment by spencerkimball** [comment]
See #19329 for background. This is meant to be used in conjunction with the work in https://github.com/tschottdorf/cockroach/tree/experiment/fastdrops

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-hft3YiYWHWJnHuw8i:blz9jyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
> ```protobuf
>     // after which the GC queue will invoke ClearRange on the data.
>     // The GC queue is activated if this value is non-zero.
>     optional util.hlc.Timestamp drop_deadline = 1 [(gogoproto.nullable) = false];
> ```

I'm anxious about using zone configs for this. I think it would be more natural for this deadline to be placed on the dropped descriptor and to have the schema change machinery take care of issuing the drops. This also gives us the opportunity in the future to "undrop" a table that hasn't been deleted and to immediately drop a table that has been schedule for dropping in the future. 

Another concern with placing this on the zone config is that it potentially requires creating a zone config for the dropped table where none previously existed. And then that zone config needs to stick around until the table is dropped. I believe currently a zone config associated with a table is deleted when the table is deleted. So you'd be mucking with the zone config lifetime which seems fraught.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by bdarnell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.cc, line 1769 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-i02GysoUstaeeWDyr:-L-i02GysoUstaeeWDys:b-qes8vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/c-deps/libroach/db.cc#L1769)):*
> ```cpp
> DBStatus DBCompactRange(DBEngine* db, DBKey start, DBKey end) {
>   rocksdb::CompactRangeOptions options;
>   options.bottommost_level_compaction = rocksdb::BottommostLevelCompaction::kForce;
> ```

Could this make it *more* expensive to drop a tiny table, if it has to rewrite a full bottommost-level sstable regardless of the table size? We may want some sort of minimum size for the table before dropping it triggers this behavior.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-i0jI5pGDJgvQTbr4v:b-z7zw8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm anxious about using zone configs for this. I think it would be more natural for this deadline to be placed on the dropped descriptor and to have the schema change machinery take care of issuing the drops. This also gives us the opportunity in the future to "undrop" a table that hasn't been deleted and to immediately drop a table that has been schedule for dropping in the future. 

Another concern with placing this on the zone config is that it potentially requires creating a zone config for the dropped table where none previously existed. And then that zone config needs to stick around until the table is dropped. I believe currently a zone config associated with a table is deleted when the table is deleted. So you'd be mucking with the zone config lifetime which seems fraught.
</blockquote></details>

I agree. I also think that adding this to the `gc_queue` is overloading it too much and I'd rather handle this separately. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by spencerkimball** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/db.cc, line 1769 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-i02GysoUstaeeWDyr:-L-i2lVY-Dip1TEk3896:b-epquhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/c-deps/libroach/db.cc#L1769)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Could this make it *more* expensive to drop a tiny table, if it has to rewrite a full bottommost-level sstable regardless of the table size? We may want some sort of minimum size for the table before dropping it triggers this behavior.
</blockquote></details>

Probably. I don't understand the parameters here...this was a first pass.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-i0Sc7D9JAMZ7KZYTf:b-peco1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I agree. I also think that adding this to the `gc_queue` is overloading it too much and I'd rather handle this separately. 
</blockquote></details>

This mechanism also allows us to undrop, and also change the deadline for dropping.

Creating a new zone config is a real problem and we'd need a way to clean it up after the table is fully cleaned up.

I don't see how we could be cleaning up zone configs already though...? We issue the `DeleteRange` requests after the `DROP` or `TRUNCATE` invocations, but we can't delete the zone at that point because that data still lives on until getting eventually GC'ed. So we're already leaking zone configs (?), and need some mechanism that probably will need to be tied to the GC queue to clean them up. Once that's in place, I think the concern about creating a new one is manageable.

@bdarnell: while this is clearly adding complexity to the `gc_queue`, the reason we decided to explore this approach is what the alternatives look like. Specifically, we need to figure out how to schedule the deletion of the data via calls to the KV API's `ClearRange` method. That future scheduling has no current mechanism. We'd need to build a cron-like-something, probably in SQL land. That seemed like a bigger wrinkle than just using the GC queue, which provides the scheduling and appropriate rate-limiting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-iZ22N9bR638F02mdG:br3ihdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

This mechanism also allows us to undrop, and also change the deadline for dropping.

Creating a new zone config is a real problem and we'd need a way to clean it up after the table is fully cleaned up.

I don't see how we could be cleaning up zone configs already though...? We issue the `DeleteRange` requests after the `DROP` or `TRUNCATE` invocations, but we can't delete the zone at that point because that data still lives on until getting eventually GC'ed. So we're already leaking zone configs (?), and need some mechanism that probably will need to be tied to the GC queue to clean them up. Once that's in place, I think the concern about creating a new one is manageable.

@bdarnell: while this is clearly adding complexity to the `gc_queue`, the reason we decided to explore this approach is what the alternatives look like. Specifically, we need to figure out how to schedule the deletion of the data via calls to the KV API's `ClearRange` method. That future scheduling has no current mechanism. We'd need to build a cron-like-something, probably in SQL land. That seemed like a bigger wrinkle than just using the GC queue, which provides the scheduling and appropriate rate-limiting.
</blockquote></details>

Heh, it's possible that there is currently a bug where we delete the zone config before the data is deleted. Regardless, I think it is easier to to the "drop" timestamp to the table descriptor than the zone config. Yeah, we'd need something to pick up the deletion in the future, but I think that can work into the schema changer. 

Thinking about this some more today, unless we add the ability to "undrop" in 2.0, it might be less surprising if `DROP TABLE` simply invoked `ClearRange` immediately. Allowing a user to drop a table but then be unable to easily recover the data for the GC TTL duration is surprising.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-id4Tm1YRyN5px1aZA:b-gsranl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, it's possible that there is currently a bug where we delete the zone config before the data is deleted. Regardless, I think it is easier to to the "drop" timestamp to the table descriptor than the zone config. Yeah, we'd need something to pick up the deletion in the future, but I think that can work into the schema changer. 

Thinking about this some more today, unless we add the ability to "undrop" in 2.0, it might be less surprising if `DROP TABLE` simply invoked `ClearRange` immediately. Allowing a user to drop a table but then be unable to easily recover the data for the GC TTL duration is surprising.
</blockquote></details>

@petermattis I have no personal stake in this decision, but isn't it a pretty drastic change from current behavior if `DROP` semantics changed like that? We've talked about avoiding fat finger mistakes but this seems like it'd incentivize them. I wouldn't put our convenience over what seems to me like a pretty drastic UX change (deterioration?). We have told folks in the past that they could `AS OF SYSTEM TIME` their way back into accidentally deleted data (when they needed it). It doesn't seem harder to make `DROP` schedule the `ClearRange` change after `ttl` seconds (that was straightforward, right?) which preserves the current UX, and have `DROP IMMEDIATE` (:bike: :house_with_garden:) override to `ttl=0` (btw, `ClearRange` will update `GCThreshold`). If you're concerned about folks running `DROP` and then not seeing their space reclaimed immediately, we could provide `crdb_internal.force_drop_immediate` which takes a TableID until we have a better interface (the implication being that it's an experimental API that will go away).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-if0i1QgjSwZDsjAhF:bf98z7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

@petermattis I have no personal stake in this decision, but isn't it a pretty drastic change from current behavior if `DROP` semantics changed like that? We've talked about avoiding fat finger mistakes but this seems like it'd incentivize them. I wouldn't put our convenience over what seems to me like a pretty drastic UX change (deterioration?). We have told folks in the past that they could `AS OF SYSTEM TIME` their way back into accidentally deleted data (when they needed it). It doesn't seem harder to make `DROP` schedule the `ClearRange` change after `ttl` seconds (that was straightforward, right?) which preserves the current UX, and have `DROP IMMEDIATE` (:bike: :house_with_garden:) override to `ttl=0` (btw, `ClearRange` will update `GCThreshold`). If you're concerned about folks running `DROP` and then not seeing their space reclaimed immediately, we could provide `crdb_internal.force_drop_immediate` which takes a TableID until we have a better interface (the implication being that it's an experimental API that will go away).
</blockquote></details>

@tschottdorf Those are good points regarding the UX change, yet our behavior already differs from Postgres and many other databases. I'd rather avoid something like `crdb_internal.force_drop_immediate` and provide a first class feature. Renaming the table into a `trash` database is not difficult. 

Another thought is that we don't add additional syntax, but add a `drop_table_ttl` session variable which defaults to the zone GC ttl.

All this discussion makes me think that we're trying to design too much UX in this issue. It is super useful that we've identified that we can perform drops a lot faster. I think we need to open up the UX discussion to a larger audience. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-ihjLlblLqJOLYsRVD:b93e05q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
> All this discussion makes me think that we're trying to design too much UX in this issue.

I agree, but my point is that you're the one designing UX into it by wanting to make changes to existing behavior, which is bound to be problematic and incurring a lengthier process. I think we ought to keep things working as they are but provide a hatch that can make it into the next release to buy us time to see what's ultimately useful. That is what I was trying to conjure up in my last comment.

Regarding longer-term UX discussions, if we changed the default TTL to, say, 20 minutes, it could work. Most time travel will work, and data would get freed within what users expect. Nightly incremental backups wouldn't work without a change, though I think that is OK as these are advanced enterprise customers who have a better understanding. (I almost regret writing this, as I didn't want to debate UX. Let's table this for some down-the-line UX discussion).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-inDpDo3DlYQ78xgUr:bhkuqka) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> All this discussion makes me think that we're trying to design too much UX in this issue.

I agree, but my point is that you're the one designing UX into it by wanting to make changes to existing behavior, which is bound to be problematic and incurring a lengthier process. I think we ought to keep things working as they are but provide a hatch that can make it into the next release to buy us time to see what's ultimately useful. That is what I was trying to conjure up in my last comment.

Regarding longer-term UX discussions, if we changed the default TTL to, say, 20 minutes, it could work. Most time travel will work, and data would get freed within what users expect. Nightly incremental backups wouldn't work without a change, though I think that is OK as these are advanced enterprise customers who have a better understanding. (I almost regret writing this, as I didn't want to debate UX. Let's table this for some down-the-line UX discussion).
</blockquote></details>

We're both suggesting new UX: I'm suggesting a change in behavior, you're proposing new behavior (via `DROP IMMEDIATE`). One additional concern with new syntax such as `DROP IMMEDIATE` is that we'd have to support it "forever". The least problematic path forward in the short term would be to not add new syntax and to keep the existing TTL behavior but to change the mechanism to use `ClearRange`. Even my suggestion for `drop_table_ttl` is fraught. Perhaps `crdb_internal.drop_table_ttl` could be removed in the future without worrying about backward incompatibility.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Comment by tschottdorf** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone.proto, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518#-L-hft3YiYWHWJnHuw8h:-L-ioZWR-Pts9nKjHU2n:bk1wl85) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8b6752f1374eb6c90db8c014831de08d491b00/pkg/config/zone.proto#L42)):*
Yeah, I did suggest `DROP IMMEDIATE` but I'm not actually attached to that and shouldn't have advocated for it.

> The least problematic path forward in the short term would be to not add new syntax and to keep the existing TTL behavior but to change the mechanism to use ClearRange.

100% agree. I would still consider the temporary escape hatch (say someone can't wait for 24 hours) but that seems straightforward enough (?) to be added in a patch release when necessary, so my interest doesn't go beyond finding out whether it could be worked out if desperately needed (`crdb_internal.force_drop_immediate()`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20518)*

**Pull request closed without merging**
