### PR TITLE
metrics: refactor histogram bucket generation and testing

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit refactors histogram bucketing for legibility and composibility. It also introduces a data-driven test for histogram bucket generation.

This refactor should make it easier to add additional metric categories, distributions, and bucket types.

Part of #97144.

Release note: None

### CODE REVIEW

**Review by jmcarp — COMMENTED** [review]
This makes sense to me! I have a non-blocking question about how to integrate this with #104302. If we want to implement a rule like "optionally enable native histograms for all histograms following an exponential distribution" or "optionally enable native histograms for all histograms that represent a size", would we want to make distribution or histogram type public? We might also want to pass a StaticBucketConfig to NewHistogram rather than a []float64 of buckets. Or should those details not be exposed elsewhere?

**Comment by ericharmeling** [comment]
> If we want to implement a rule like "optionally enable native histograms for all histograms following an exponential distribution" or "optionally enable native histograms for all histograms that represent a size", would we want to make distribution or histogram type public?

I like those rules! We'd be defining said rules within the metrics package, right? In general, I don't think we want to export types outside their package until we have a reason to do so. So I've just made these types "private" for now - is that what you were suggesting?

> We might also want to pass a StaticBucketConfig to NewHistogram rather than a []float64 of buckets. Or should those details not be exposed elsewhere?

I like the idea of keeping bucket generation in its own file (`histogram_buckets.go`), and then just using the `[]float64` bucket vars exported from that file when calling `NewHistogram`. But again, we can do that without exporting `StaticBucketConfig`. 

I imagine the configs (distribution, min, max, count) for these histograms will continue to be per-category of metric (e.g., IO Latency metrics). And the fit of that category will be tested by (forthcoming) integration tests, which ideally will be able to suggest a better fit, or a new category. Does that sound sensible?

**Comment by jmcarp** [comment]
> I like the idea of keeping bucket generation in its own file (histogram_buckets.go), and then just using the []float64 bucket vars exported from that file when calling NewHistogram.

What I'm wondering is: how should we tell `NewHistogram` whether or not to expose native histograms alongside conventional histograms? If we want to use a rule like "expose native histograms if distribution is exponential", then `NewHistogram` needs to know the distribution type of the buckets, not just the []float of bucket bounds. In that case I could imagine passing a `StaticBucketConfig` to `HistogramOptions` instead of a []float.

Or we could do something more explicit, like adding `SupportsNativeHistogram` to `HistogramOptions` and setting to true as appropriate.

Yet another option: we could expose native histograms for many or even all histograms, then decide whether we want to use conventional or native buckets on the prometheus side.

What's your preference? I also don't want to hold up this PR, so we can also discuss in #104302.

**Comment by ericharmeling** [comment]
> If we want to use a rule like "expose native histograms if distribution is exponential", then NewHistogram needs to know the distribution type of the buckets, not just the []float of bucket bounds. In that case I could imagine passing a StaticBucketConfig to HistogramOptions instead of a []float.

That makes sense. The only issue I can see is that we might want to pass non-generated, static buckets (for tests mainly) to `HistogramOptions`. But I suppose we can have both `Buckets []float` and `BucketConfig StaticBucketConfig` in there? And just use the generator when `Buckets` is nil and we have a non-zero `StaticBucketConfig`. Does that make sense? I've pushed a commit with that refactor.

**Comment by ericharmeling** [comment]
> Or we could do something more explicit, like adding SupportsNativeHistogram to HistogramOptions and setting to true as appropriate.

I don't _really_ have a preference on where the `SupportsNativeHistogram` is set/evaluated, but here looks good to me: https://github.com/cockroachdb/cockroach/pull/104302/files#diff-7d9143ffc52f8bb21b9a9f1dfdcef120129a14453e54e126e9ba6e3da4b54941R298. With the distribution exposed via `HistogramOptions.BucketConfig`, it'd be nice to just have the `nativeHistogramsEnabled` env var check + the distribution check.

> Yet another option: we could expose native histograms for many or even all histograms, then decide whether we want to use conventional or native buckets on the prometheus side.

This wouldn't be a terrible idea since native histograms are so space-efficient... We'd just want the bucket sizes to be big enough to make up for any precision lost for the metrics that don't follow exponential distributions. Any other cons to using this approach?

**Review by abarganier — COMMENTED** [review]
Re: the above discussion, agreed that we should just pass the bucket configs themselves to `NewHistogram` (seems like that's already been done - nice!). It'll buy us flexibility as things evolve in the future.

@ericharmeling I have some code nits, but the overall approach lgtm. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-:-NaNfBzT4OiQSWZGf47P:b-7o2yhq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NaNdjTjAlpimWk3Fpk9:b-dfm4d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
> ```Go
> 			Metadata:     metaConnMigrationAttemptedCount,
> 			Duration:     base.DefaultHistogramWindowInterval(),
> 			BucketConfig: metric.StaticBucketConfigs["IOLatencyBuckets"],
> ```

nit: For all these `BucketConfig` assingments, don't we have these static buckets already assigned to public vars in the `metric` package? Do we need to be using the map? 
___
*[`pkg/util/metric/histogram_buckets.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNYgrB5ASiQBApAr4c:-NaNYgrB5ASiQBApAr4d:b-hcsqe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L26)):*
> ```Go
> }
> 
> type distribution int
> ```

nit: comments for this and other newly types created in this file.
___
*[`pkg/util/metric/histogram_buckets.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNXZ0T4AKaDpuUWQkI:-NaNXZ0T4AKaDpuUWQkJ:b4lrtkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L32)):*
> ```Go
> 	Uniform distribution = iota
> 	Exponential
> 	// Normal
> ```

nit: if we're gonna leave these commented out, maybe add a bit more explanation about what we plan to do with these in the future.
___
*[`pkg/util/metric/histogram_buckets.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZJ1k5-wJvf3JeZVr:-NaNZJ1k5-wJvf3JeZVs:bbn5ob7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L44)):*
> ```Go
> )
> 
> // precisionTestEnabledEnv enables precision testing buckets for histograms.
> ```

nit: a bit more explanation about what that means/its affects would be helpful.
___
*[`pkg/util/metric/histogram_buckets.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZYTT7gjsj33APM7k:-NaNZYTT7gjsj33APM7l:b-ira66e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L50)):*
> ```Go
> var staticBucketConfigs = map[string]staticBucketConfig{
> 	"IOLatencyBuckets": {
> 		min:          10e3,
> ```

nit: for these and the other bucket configs, some comments converting these min/max values into units more.easily parsed (E.g. `ms`, `s`, `kb`, etc.) would be helpful for inspection/readability later on.
___
*[`pkg/util/metric/histogram_buckets.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNbWMXA-mSIuaFO7rG:-NaNbWMXA-mSIuaFO7rH:b40j63m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L116)):*
> ```Go
> func getBuckets(config staticBucketConfig) []float64 {
> 	var buckets []float64
> 	if envutil.EnvOrDefaultBool(precisionTestEnabledEnv, false) {
> ```

nit: I think generally the pattern we take is assigning the results of this call to a package-level variable at initialization. Do we need it to be called each time `getBuckets` is called? It could lead to some inconsistent state if the env var value is changed while the bucket vars are still being initialized. 
___
*[`pkg/util/metric/histogram_buckets.go` line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNe9EO-j9jINhVNhJw:-NaNe9EO-j9jINhVNhJx:b-omsxnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/util/metric/histogram_buckets.go#L114)):*
> ```Go
> }
> 
> func GetBucketsFromBucketConfig(config staticBucketConfig) []float64 {
> ```

nit: can this function be defined on the `staticBucketConfig` type itself? Then we could call `config.GetBuckets()`?

**Review by ericharmeling — COMMENTED** [review]
TFTR @abarganier!

I think I got to all your comments. Reworked the `StaticBucketConfigs` map. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-:-NaSedI-0rFNmlFI_6_y:b-f25itd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NaS8wPk32IQccRDrkLa:bvlaean) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
>  don't we have these static buckets already assigned to public vars in the `metric` package?

On master, we have exported vars for the static buckets (of type `[]float64`), to pass to `NewHistogram` here. But we are now passing bucket configs to `NewHistogram`.

If the concern is with the performance of map lookups, we can use ints instead of strings as the keys for O(1) lookups? I went ahead and made that change, but happy to rethink that.
___
*[`pkg/util/metric/histogram_buckets.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNYgrB5ASiQBApAr4c:-NaSaYWu8_w8qTDfCSW-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L26)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: comments for this and other newly types created in this file.
</blockquote></details>

Done.
___
*[`pkg/util/metric/histogram_buckets.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNXZ0T4AKaDpuUWQkI:-NaSaZGF10mSx-KU7Uv9:b-kn60l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L32)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: if we're gonna leave these commented out, maybe add a bit more explanation about what we plan to do with these in the future.
</blockquote></details>

I removed them, and instead added a to-do.
___
*[`pkg/util/metric/histogram_buckets.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZJ1k5-wJvf3JeZVr:-NaSdPcwDJGt5bLR7qNk:b-csywqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L44)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: a bit more explanation about what that means/its affects would be helpful.
</blockquote></details>

I actually think we might as well just take this precision testing stuff out and save it for the actual roachtest PR (especially if that work takes longer than expected to get merged).
___
*[`pkg/util/metric/histogram_buckets.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZYTT7gjsj33APM7k:-NaS_IEJDyWEKXveG72I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L50)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: for these and the other bucket configs, some comments converting these min/max values into units more.easily parsed (E.g. `ms`, `s`, `kb`, etc.) would be helpful for inspection/readability later on.
</blockquote></details>

Done.
___
*[`pkg/util/metric/histogram_buckets.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNbWMXA-mSIuaFO7rG:-NaSc3S33-tB9GRn5dJM:boq58ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L116)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: I think generally the pattern we take is assigning the results of this call to a package-level variable at initialization. Do we need it to be called each time `getBuckets` is called? It could lead to some inconsistent state if the env var value is changed while the bucket vars are still being initialized. 
</blockquote></details>

I actually think we might as well just take this precision testing stuff out and save it for the actual roachtest PR (especially if that work takes longer than expected to get merged).

But I'll follow the recommended pattern in that forthcoming PR.
___
*[`pkg/util/metric/histogram_buckets.go` line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNe9EO-j9jINhVNhJw:-NaSB9jEEVDxCbxD0BIN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/util/metric/histogram_buckets.go#L114)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can this function be defined on the `staticBucketConfig` type itself? Then we could call `config.GetBuckets()`? 
</blockquote></details>

Done.

**Review by abarganier — COMMENTED** [review]
Thanks for addressing the comments! Just one last thing re: the map usage, lmk what you think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-:-NbFprUHA6ytI43loE7x:bl5ufn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jmcarp, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NbFoDNBEUDT9I1DJkZG:b-yin5xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

>  don't we have these static buckets already assigned to public vars in the `metric` package?

On master, we have exported vars for the static buckets (of type `[]float64`), to pass to `NewHistogram` here. But we are now passing bucket configs to `NewHistogram`.

If the concern is with the performance of map lookups, we can use ints instead of strings as the keys for O(1) lookups? I went ahead and made that change, but happy to rethink that.
</blockquote></details>

It wasn't so much about about the performance of the map lookups, but more the convenience/intuitiveness the API. Maybe I'm missing something, but what purpose does the map serve if its elements are essentially vars defined at initialization anyway? 

Could we not just, for example, have `BucketConfig: metric.IOLatencyBuckets` instead of `BucketConfig: metric.StaticBucketConfigs[metric.IOLatencyBuckets]` here and elsewhere, removing the need for all these diffs? 

I guess I'm not seeing the `histType` type as necessary. Could each type not just be an exported package-level variable instead? 
___
*[`pkg/util/metric/histogram_buckets.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZJ1k5-wJvf3JeZVr:-NbFpi-kE9Z9e8o_Xu-C:b-81nlyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L44)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I actually think we might as well just take this precision testing stuff out and save it for the actual roachtest PR (especially if that work takes longer than expected to get merged).
</blockquote></details>

SGTM!
___
*[`pkg/util/metric/histogram_buckets.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNZYTT7gjsj33APM7k:-NbFpkbF8r-S4gqLwUa9:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L50)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`pkg/util/metric/histogram_buckets.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNbWMXA-mSIuaFO7rG:-NbFppYvBUjWoFfDpkcW:b-k6rpab) ([raw file](https://github.com/cockroachdb/cockroach/blob/f920b0c8804579ffdd90679fa4a910a844bdcd9b/pkg/util/metric/histogram_buckets.go#L116)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I actually think we might as well just take this precision testing stuff out and save it for the actual roachtest PR (especially if that work takes longer than expected to get merged).

But I'll follow the recommended pattern in that forthcoming PR.
</blockquote></details>

Sounds good, thanks.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jmcarp, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NbFqcAD53SUWz-YnJjE:blxvo9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

It wasn't so much about about the performance of the map lookups, but more the convenience/intuitiveness the API. Maybe I'm missing something, but what purpose does the map serve if its elements are essentially vars defined at initialization anyway? 

Could we not just, for example, have `BucketConfig: metric.IOLatencyBuckets` instead of `BucketConfig: metric.StaticBucketConfigs[metric.IOLatencyBuckets]` here and elsewhere, removing the need for all these diffs? 

I guess I'm not seeing the `histType` type as necessary. Could each type not just be an exported package-level variable instead? 


</blockquote></details>

Also, we could leave the `Buckets` member of `metric.HistogramOptions` as the same name, instead of changing it to `BucketConfig`, and completely remove the need for any of these diffs altogether. The type of `Buckets` in the options should be enough to convey to the user that they are configs and not `[]float64`

**Review by ericharmeling — COMMENTED** [review]
TFTR! I've updated the PR following your latest feedback. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-:-NbPtg1PCbSiEtF7Q79O:brb550d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @jmcarp, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NbGcqidB4jWBrogD37G:b-ju02x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
> It wasn't so much about about the performance of the map lookups, but more the convenience/intuitiveness the API. Maybe I'm missing something, but what purpose does the map serve if its elements are essentially vars defined at initialization anyway?

Ah okay. I think my main motivation for using a map for `StaticBucketConfigs` here is to simplify the addition of new bucket types. When we introduce a new bucket type, we'd just add it to the map, and then it will automatically be part of the test loop in `pkg/util/metric/histogram_buckets_test.go`. Declaring an explicit var for each would require us to declare an exported var for each, and then append each one individually to a slice that replaces the `StaticBucketConfigs` map for the test loop. If you forget to append the exported var to the slice, then its generation could go untested.

On reflection though, this motivation is a bit weak, and I'm pretty ambivalent about it. I've updated the PR as suggested. See the latest commit.

> I guess I'm not seeing the `histType` type as necessary. Could each type not just be an exported package-level variable instead?

Removed the type and exported each as a package-level var as suggested, in the latest commit.

> Also, we could leave the `Buckets` member of `metric.HistogramOptions` as the same name, instead of changing it to `BucketConfig`, and completely remove the need for any of these diffs altogether. The type of `Buckets` in the options should be enough to convey to the user that they are configs and not `[]float64`

This PR doesn't remove the original `Buckets []float64` from `metric.HistogramOptions`, since we have some tests that use a custom (non-config-generated) bucket (see https://github.com/cockroachdb/cockroach/pull/107388#issuecomment-1652287323).

**Review by abarganier — APPROVED** [review]
:lgtm: nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-:-NbUiyXMARRmUI9og5IK:b-kbynj8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling, @jmcarp, @msirek, @rhu713, and @samiskin)

___
*[`pkg/ccl/sqlproxyccl/metrics.go` line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107388#-NaNdjTjAlpimWk3Fpk8:-NbUitCQ-t8J0yBZ1lrz:bq1lxm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/203ec16f439263df23a65f96ff4fbf0f2e60738a/pkg/ccl/sqlproxyccl/metrics.go#L240)):*
> This PR doesn't remove the original `Buckets []float64` from `metric.HistogramOptions`, since we have some tests that use a custom (non-config-generated) bucket (see [#107388 (comment)](https://github.com/cockroachdb/cockroach/pull/107388#issuecomment-1652287323)).

Ack, nevermind on that one then.

**Pull request merged**
