### PR TITLE
sql: add cluster setting to determine if owner has implicit GRANT OPTION

### LINKED ISSUE #126686: sql: add cluster setting to control if object owner has GRANT OPTION
The creator of a SQL object is the owner, and implicitly has all privileges on that object, including the GRANT OPTION for each privilege. This allows the owner to grant any privilege to others. This behavior is not always desirable for customers looking to exercise strict control over how privileges are able to be conferred. We should add a cluster setting to prevent this behavior.

This is similar to https://github.com/cockroachdb/cockroach/issues/124376, which added a cluster setting to control the inheritance of GRANT OPTION.

Epic CRDB-37763
Request: TREQ-232
Jira issue: CRDB-40066

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/126686

Release note (sql change): Added the sql.auth.grant_option_for_owner.enabled cluster setting. The default value is true, which results in behavior that matches the existing behavior of CockroachDB. When set to false, then the GRANT OPTION is not implcitly given to the owner of an object. The object owner still implicitly has all privileges on the object, just not the ability to grant them to other users.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a test suggestion.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-:-O1Rj2oN2_LZGAKQStjG:b-4a9fhv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option` line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-O1Rhx4k6iSOk3-plzxd:-O1Rhx4l-wpPgjYctfif:bwuf20p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ab82c6c7eec934c7881c770c2f0a00d708e4d/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L783)):*
> ```
> 
> statement ok
> REVOKE SELECT ON TABLE tbl_owned_by_root FROM other
> ```

Was this necessary for the new subtest to work? It doesn't seem like it uses this table.
___
*[`pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-O1RiTIADGTNMyzII2TN:-O1RiTIB5DFgmhXmliBI:b-nufevn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ab82c6c7eec934c7881c770c2f0a00d708e4d/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L810)):*
> ```
> # Verify that child also is not able to grant SELECT on tbl_owned_by_parent.
> statement error user child missing WITH GRANT OPTION privilege on SELECT
> GRANT SELECT ON TABLE tbl_owned_by_parent TO other
> ```

Should we have a positive case? For instance, `sql.auth.grant_option_for_owner.enabled` is false, but we have grant privileges. We should be allowed to grant still.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126860)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option` line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-O1Rhx4k6iSOk3-plzxd:-O1SV3ya2VG_urVIHP-l:ba2pkoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ab82c6c7eec934c7881c770c2f0a00d708e4d/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L783)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Was this necessary for the new subtest to work? It doesn't seem like it uses this table.
</blockquote></details>

That's true. I initially added it just to reset the privileges to the initial state before i wrote the new tests, and then later realized I didn't need to use this table.
___
*[`pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option` line 810 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-O1RiTIADGTNMyzII2TN:-O1SVIXF4CiW3Lq5VJyK:b-e1a4jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a7ab82c6c7eec934c7881c770c2f0a00d708e4d/pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option#L810)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we have a positive case? For instance, `sql.auth.grant_option_for_owner.enabled` is false, but we have grant privileges. We should be allowed to grant still.
</blockquote></details>

Good idea; done

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126860#-:-O1TCgeK4amChkatY-56:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
