### PR TITLE
roachtest: add cdcbench variant with a kafka sink

### PR DESCRIPTION
**Pull request by asg0451**
Add a cdcbench variant that uses a kafka sink to
more realistically represent real-world use cases.

Epic: CRDB-38892

Release note: none

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451, @DarrylWong, @renatolabs, and @wenyihu6)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15DC5e1VEoUhezmlUr):*
nit: s/changefeedccl/roachtest
___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15CvvK7JpEtD0rArub:-O15CvvK7JpEtD0rAruc:bp6dmu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64574b5cf8cd28bb7ac967ec2ea685abc59ef92/pkg/cmd/roachtest/tests/cdc_bench.go#L157)):*
> ```Go
> 					Owner:            registry.OwnerCDC,
> 					Benchmark:        true,
> 					Cluster:          r.MakeClusterSpec(nodes+3, spec.CPU(cpus)), // 5 + coordinator + workload + kafka
> ```

nit: s/5/nodes
___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15CQm-4ZnKhP6olOnp:-O15CQm00d-tHJmwrLZq:bghf5fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64574b5cf8cd28bb7ac967ec2ea685abc59ef92/pkg/cmd/roachtest/tests/cdc_bench.go#L378)):*
> ```Go
> 	server cdcBenchServer,
> 	format string,
> 	withKafka bool,
> ```

nit: maybe this should be an enum (e.g. `cdcBenchSinkType` and `cdcBenchNullSink = iota`) and the if statement below could be a switch?

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, @renatolabs, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15CQm-4ZnKhP6olOnp:-O1I2sxR3FNFbpzPaG8s:b-3ewfeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64574b5cf8cd28bb7ac967ec2ea685abc59ef92/pkg/cmd/roachtest/tests/cdc_bench.go#L378)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe this should be an enum (e.g. `cdcBenchSinkType` and `cdcBenchNullSink = iota`) and the if statement below could be a switch?
</blockquote></details>

i had a similar thought but didnt want to generalize too early. if we want to add other sinks to this we can go that route, but if only kafka is supported that might be confusing.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451, @DarrylWong, @renatolabs, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15CQm-4ZnKhP6olOnp:-O1OPWI90siL0GmPzWmE:b8eb4h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64574b5cf8cd28bb7ac967ec2ea685abc59ef92/pkg/cmd/roachtest/tests/cdc_bench.go#L378)):*
<details><summary><i>Previously, asg0451 (Miles Frankel) wrote…</i></summary><blockquote>

i had a similar thought but didnt want to generalize too early. if we want to add other sinks to this we can go that route, but if only kafka is supported that might be confusing.
</blockquote></details>

Our internal go coding guidelines (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Try-to-avoid-bool-parameters) discourages `bool` parameters. You could maybe just make it a `bool` enum for now.

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @asg0451, @DarrylWong, @renatolabs, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O15CQm-4ZnKhP6olOnp:-O1STF5Z9YPaLYNM_KVt:b4t9n4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64574b5cf8cd28bb7ac967ec2ea685abc59ef92/pkg/cmd/roachtest/tests/cdc_bench.go#L378)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Our internal go coding guidelines (https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Try-to-avoid-bool-parameters) discourages `bool` parameters. You could maybe just make it a `bool` enum for now.
</blockquote></details>

I agree with Andy that we should use a sink type enum instead of a bool here even though we only support 2 sink types in this test right now. In fact, we already have `sinkType` in the tests package so it should be easy to use here https://github.com/cockroachdb/cockroach/blob/4497058d5c7aa09729bea5d47320111da876cbbc/pkg/cmd/roachtest/tests/cdc.go#L80
___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O1SSgB-31JSAkC7y3WF:-O1SSgB-31JSAkC7y3WG:b1eaw8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc61f331c326f36982ac2d1787d55d6decbefb9/pkg/cmd/roachtest/tests/cdc_bench.go#L128)):*
> ```Go
> 				Timeout:          time.Hour,
> 				Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 					runCDCBenchWorkload(ctx, t, c, ranges, readPercent, "", "", false)
> ```

nit: s/`false`/`false /* withKafka */`
Here and at other callsites (if still relevant after resolving other review comment)

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-:-O1ZHiXaAO5JjDXXpVSn:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @asg0451, @DarrylWong, @renatolabs, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O1ZHLFn0_DmgNzm2aYR:-O1ZHLFn0_DmgNzm2aYS:b-629vwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa31f1cb4363adb039c5a5e1ff3c46285db8d057/pkg/cmd/roachtest/tests/cdc_bench.go#L404)):*
> ```Go
> 		defer cleanup()
> 		sinkURI = kafka.sinkURL(ctx)
> 	case nullSink, "":
> ```

optional super minor nit: I'd assign the null sinkURI here and use an empty string at initialization.

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, @renatolabs, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc_bench.go` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-O1ZHLFn0_DmgNzm2aYR:-O1bSon349xGlBdASGl9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa31f1cb4363adb039c5a5e1ff3c46285db8d057/pkg/cmd/roachtest/tests/cdc_bench.go#L404)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional super minor nit: I'd assign the null sinkURI here and use an empty string at initialization.
</blockquote></details>

Done.

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126577#-:-O1cLG0C1GDOH29JI5gF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @renatolabs, @rharding6373, and @wenyihu6)

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Pull request merged**
