### PR TITLE
go mod attempt

### PR DESCRIPTION
**Pull request by otan**

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This is fantastic progress!

The manual vendoring of `go-libedit` is really unfortunate, though I'm sympathetic with doing so as an interim step. I'd like to put some elbow grease into figuring out how to get rid of that. 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-:-M7INYywEjwUPVc1_Q46:bvc3ixp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[Makefile, line 353 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IMhVr6q6CEtrUziuz:-M7IMhVr6q6CEtrUziv-:bjkag6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L353)):*
> ```Makefile
> # Update the git hooks and install commands from dependencies whenever they
> # change.
> bin/.bootstrap: $(GITHOOKS) Gopkg.lock | bin/.submodules-initialized
> ```

Shouldn't `Gopkg.lock` and `Gopkg.toml` be deleted? Should this reference to `Gopkg.lock` be replaced with `go.sum`?
___
*[Makefile, line 1189 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IN42g3y9ae1KoFwpk:-M7IN42h8upKKVUAncD4:beaasq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L1189)):*
> ```Makefile
> CPP_PROTO_CCL_ROOT := $(LIBROACH_SRC_DIR)/protosccl
> 
> GOGO_PROTOBUF_PATH := ./vendorproto/gogoproto
> ```

Can you elaborate on why `vendorproto` is needed? The `vendor` directory still exists, right? I suppose that will go away once we move away from `go mod vendor`, but for right now it is still there.
___
*[pkg/blobs/blobspb/doc.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7INQP_Aybm5OymIpJY:-M7INQP_Aybm5OymIpJZ:bcfqd1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/pkg/blobs/blobspb/doc.go#L1)):*
> ```Go
> package blobspb
> ```

Can you explain why these empty `doc.go` files are necessary? Perhaps I missed it in `GOMODLOG.md`.

**Review by jordanlewis — COMMENTED** [review]
We also have to manually vendor the protos which is very sad.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-:-M7I_G9h1cW2RrPyTa3H:bi840up)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[Makefile, line 353 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IMhVr6q6CEtrUziuz:-M7I_FLX-OcoF7vkx3zT:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L353)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't `Gopkg.lock` and `Gopkg.toml` be deleted? Should this reference to `Gopkg.lock` be replaced with `go.sum`?
</blockquote></details>

Yes.
___
*[Makefile, line 1189 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IN42g3y9ae1KoFwpk:-M7I_9uX7cHYbttclRy0:b-sgaca3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L1189)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on why `vendorproto` is needed? The `vendor` directory still exists, right? I suppose that will go away once we move away from `go mod vendor`, but for right now it is still there.
</blockquote></details>

Go vendoring doesn't include non-Go files. (Or maybe it's packages with only non-Go files).
___
*[pkg/blobs/blobspb/doc.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7INQP_Aybm5OymIpJY:-M7I_4g-1ELQvuyz3WKC:b4d7q3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/pkg/blobs/blobspb/doc.go#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you explain why these empty `doc.go` files are necessary? Perhaps I missed it in `GOMODLOG.md`.
</blockquote></details>

If you try to run `go mod vendor` without this, you run into trouble because there's no Go files in these pb-only dirs.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @petermattis)

___
*[Makefile, line 1189 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IN42g3y9ae1KoFwpk:-M7IcUG_CbeSSyAuUyq9:b-uydrjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L1189)):*
I found https://github.com/golang/go/issues/26366#issuecomment-405683150 which suggests:

> If anyone wants to build a tool that adds to the vendor directory after go mod -vendor, you could do that by reading the modules.txt file and using commands like go list -f '{{.Dir}}' to find out where each package was copied from.

There might be a tool which does this already (I haven't looked). If you do something like `go list -f "{{.Dir}}" github.com/cockroachdb/errors` we'll find the directory in the module cache as something like `/Users/pmattis/Development/go/pkg/mod/github.com/cockroachdb/errors@v1.2.4`. That directory does contain the protos, which we could copy over to the vendor directory.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @petermattis)

___
*[Makefile, line 1189 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/48853#-M7IN42g3y9ae1KoFwpk:-M7IdAes83OP7jCMCmUv:bgp10xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4af29140872bef59d722e738a2f76847be99c986/Makefile#L1189)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I found https://github.com/golang/go/issues/26366#issuecomment-405683150 which suggests:

> If anyone wants to build a tool that adds to the vendor directory after go mod -vendor, you could do that by reading the modules.txt file and using commands like go list -f '{{.Dir}}' to find out where each package was copied from.

There might be a tool which does this already (I haven't looked). If you do something like `go list -f "{{.Dir}}" github.com/cockroachdb/errors` we'll find the directory in the module cache as something like `/Users/pmattis/Development/go/pkg/mod/github.com/cockroachdb/errors@v1.2.4`. That directory does contain the protos, which we could copy over to the vendor directory. 
</blockquote></details>

https://github.com/goware/modvendor might be just such a tool.

**Comment by otan** [comment]
obsoleted by https://github.com/cockroachdb/cockroach/pull/49447

**Pull request closed without merging**
