### PR TITLE
workload: add a new tpccMultiDB workload

### PR DESCRIPTION
**Pull request by fqazi**
Previously, if we wanted to duplicate the TPCC database multiple times we would need to spawn multiple instances of the workload. For large schema testing we need an easier way of replicating this schema multiple times and execute the original workload across them. To address this, this patch will add a new workload called tpccMultiDB. This workload works by sharing code with tpcc, but using hooks to inject DB selection before queries execute and have the capability to execute queries from a file (i.e. this can be used for injecting ORM queries in large schema benchmarking).

Informs: #123757
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
I was curious about this change, so I had a quick look and left a few questions.

> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-:-O-gbmSg8julwz-a6MOO:b791ab9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @renatolabs, and @srosenberg)

___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-gb4em-9nfC1jr20CN:-O-gaSXwDJfxeivrTqut:bidggso) ([raw file](https://github.com/cockroachdb/cockroach/blob/564785a35e110748ec6d3a1917c8c5f20e6cfa1d/pkg/workload/tpcc/tpcc_multi_db.go#L57)):*
> ```Go
> 		g.flags.Meta["txn-preamble-file"] = workload.FlagMeta{RuntimeOnly: true}
> 		// Support executing a query file before each transaction.
> 		g.flags.StringVar(&g.txnPreambleFile, "txn-preamble-file", "", "queries that will be injected before each txn")
> ```

Could this option be added to the parent workload (tpcc) instead? It seems like we had to update the parent to support this anyway, so it's partially implemented already.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-g_XUr7Bkfce0PVyZT:-O-g_XUr7Bkfce0PVyZU:b-p49i24) ([raw file](https://github.com/cockroachdb/cockroach/blob/564785a35e110748ec6d3a1917c8c5f20e6cfa1d/pkg/workload/tpcc/tpcc_multi_db.go#L153)):*
> ```Go
> 		// Run the usual TPCC precreate logic after.
> 		if oldPrecreate != nil {
> 			return oldPrecreate(db)
> ```

Should this be run against each database in the list?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125630)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @spilchen, and @srosenberg)

___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-gb4em-9nfC1jr20CN:-O-l8BA6CxTfnudTqyrJ:b-hv0h9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/564785a35e110748ec6d3a1917c8c5f20e6cfa1d/pkg/workload/tpcc/tpcc_multi_db.go#L57)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Could this option be added to the parent workload (tpcc) instead? It seems like we had to update the parent to support this anyway, so it's partially implemented already.
</blockquote></details>

Good point, and I moved into the parent workload.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-g_XUr7Bkfce0PVyZT:-O-l8WPY0a9zCr8bLGUz:bjcjlbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/564785a35e110748ec6d3a1917c8c5f20e6cfa1d/pkg/workload/tpcc/tpcc_multi_db.go#L153)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should this be run against each database in the list?
</blockquote></details>

Good point and its needed for multi-region support

**Review by spilchen — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125630)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @renatolabs, and @srosenberg)

___
*[`pkg/workload/tpcc/tpcc.go` line 842 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-lZkdb0VG42hWwe7Bt:-O-lZkdb0VG42hWwe7Bu:b-pa4bey) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a5c5922dcca52b276133f21677f0363adc32948/pkg/workload/tpcc/tpcc.go#L842)):*
> ```Go
> 		w.txnPreambleStatements = txnPreambleStatements
> 
> 		w.txnPreambleTime = reg.GetHandle().Get("txnPream&ble")
> ```

Was the ampersand intentional? :smile: 



_Suggestion:_
```Go
txnPreamble
```
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-la6kO1wlrJaV-uyMX:-O-la6kO1wlrJaV-uyMY:b-pr527e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a5c5922dcca52b276133f21677f0363adc32948/pkg/workload/tpcc/tpcc_multi_db.go#L146)):*
> ```Go
> 			// Run the usual TPCC pre-create logic after.
> 			if oldPrecreate == nil {
> 				return nil
> ```

Doesn't this cause us to skip the creation of other databases?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125630)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @spilchen, and @srosenberg)

___
*[`pkg/workload/tpcc/tpcc.go` line 842 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-lZkdb0VG42hWwe7Bt:-O-lcpvL6asqc0xcA5gK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a5c5922dcca52b276133f21677f0363adc32948/pkg/workload/tpcc/tpcc.go#L842)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Was the ampersand intentional? :smile:
</blockquote></details>

Done.
___
*[`pkg/workload/tpcc/tpcc_multi_db.go` line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-O-la6kO1wlrJaV-uyMX:-O-lcqpY1XgVeD7TWXNT:b-ona35y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a5c5922dcca52b276133f21677f0363adc32948/pkg/workload/tpcc/tpcc_multi_db.go#L146)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Doesn't this cause us to skip the creation of other databases?
</blockquote></details>

Should be continue.

Done.

**Review by spilchen — APPROVED** [review]
lgtm

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125630#-:-O-litFh9mzJCbg5y4e7:bb7k0qh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Pull request merged**
