### PR TITLE
cmd/roachprod/vm/aws: add README for terraform stuff

### PR DESCRIPTION
**Pull request by ajwerner**
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I get these errors from `terraform apply`:
```
Error: Error refreshing state: 15 errors occurred:
	* module.aws_roachprod-ap-southeast-2.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ap-southeast-2.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-ap-southeast-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ap-southeast-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-eu-west-3.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-eu-west-3.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-us-west-2.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-us-west-2.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-us-east-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-us-east-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-eu-west-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-eu-west-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-eu-west-2.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-eu-west-2.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-ap-northeast-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ap-northeast-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-eu-central-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-eu-central-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-us-west-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-us-west-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-ap-northeast-2.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ap-northeast-2.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-ap-south-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ap-south-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-ca-central-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-ca-central-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-sa-east-1.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-sa-east-1.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


	* module.aws_roachprod-us-east-2.data.aws_ami.node_ami: 1 error occurred:
	* module.aws_roachprod-us-east-2.data.aws_ami.node_ami: data.aws_ami.node_ami: Your query returned no results. Please change your search criteria and try again.


```

Any ideas?

**Comment by ajwerner** [comment]
Weird, I just ran it and it worked. This is a completely fresh machine so I don't think it's due to any residual state.

**Comment by RaduBerinde** [comment]
My mistake, I had a different image_name set which was the problem. Very useful, thank you!! LGTM

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64432#-:-MZUgJOmALGff4sefzlN:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
