### PR TITLE
opt: rework With bindings

### LINKED ISSUE #51648: opt: foreign key check performs unexpected hash join
Running: https://github.com/cockroachdb/cockroach/commit/438589dcee6bedadca43e8848d9e7a58d77d0569

Statement budle: [stmt-bundle-hash-join-fk.zip](https://github.com/cockroachdb/cockroach/files/4955159/stmt-bundle-hash-join-fk.zip)

Query Plan:
```
update watch_item
 ├── columns: <none>
 ├── fetch columns: wi_wl_id:3 wi_s_symb:4
 ├── update-mapping:
 │    └── wi_s_symb_new:7 => wi_s_symb:2
 ├── input binding: &1
 ├── cardinality: [0 - 0]
 ├── volatile, mutations
 ├── stats: [rows=0]
 ├── cost: 472097.271
 ├── project
 │    ├── columns: wi_s_symb_new:7!null wi_wl_id:3!null wi_s_symb:4!null wl_id:5!null wl_c_id:6!null
 │    ├── stats: [rows=1.02660232]
 │    ├── cost: 7.43080311
 │    ├── key: (5)
 │    ├── fd: ()-->(4,6,7), (3)==(5), (5)==(3)
 │    ├── prune: (3-7)
 │    ├── inner-join (lookup watch_item)
 │    │    ├── columns: wi_wl_id:3!null wi_s_symb:4!null wl_id:5!null wl_c_id:6!null
 │    │    ├── key columns: [5 26] = [3 4]
 │    │    ├── lookup columns are key
 │    │    ├── stats: [rows=1.02660232, distinct(3)=1.02645848, null(3)=0, distinct(5)=1.02645848, null(5)=0]
 │    │    ├── cost: 7.40027106
 │    │    ├── key: (5)
 │    │    ├── fd: ()-->(4,6), (3)==(5), (5)==(3)
 │    │    ├── project
 │    │    │    ├── columns: "project_const_col_@4":26!null wl_id:5!null wl_c_id:6!null
 │    │    │    ├── stats: [rows=1.02645848]
 │    │    │    ├── cost: 1.14910433
 │    │    │    ├── key: (5)
 │    │    │    ├── fd: ()-->(6,26)
 │    │    │    ├── scan watch_list@watch_list_auto_index_fk_wl_c_id_ref_customer
 │    │    │    │    ├── columns: wl_id:5!null wl_c_id:6!null
 │    │    │    │    ├── constraint: /6/5: [/4300155449 - /4300155449]
 │    │    │    │    ├── stats: [rows=1.02645848, distinct(5)=1.02645848, null(5)=0, distinct(6)=1, null(6)=0]
 │    │    │    │    │   histogram(6)=  0    1.0265
 │    │    │    │    │                <--- 4300155449
 │    │    │    │    ├── cost: 1.11857516
 │    │    │    │    ├── key: (5)
 │    │    │    │    ├── fd: ()-->(6)
 │    │    │    │    ├── prune: (5)
 │    │    │    │    └── interesting orderings: (+5) (+6,+5)
 │    │    │    └── projections
 │    │    │         └── 'ZONSPRC-ae' [as="project_const_col_@4":26]
 │    │    └── filters (true)
 │    └── projections
 │         └── 'ZONSPRC-af' [as=wi_s_symb_new:7]
 └── f-k-checks
      └── f-k-checks-item: watch_item(wi_s_symb) -> security(s_symb)
           └── anti-join (hash)
                ├── columns: wi_s_symb_new:8
                ├── stats: [rows=2106083.21]
                ├── cost: 472089.83
                ├── fd: ()-->(8)
                ├── cte-uses
                │    └── &1: count=1 used-columns=(7)
                ├── with-scan &1
                │    ├── columns: wi_s_symb_new:8
                │    ├── mapping:
                │    │    └──  wi_s_symb_new:7 => wi_s_symb_new:8
                │    ├── stats: [rows=5531083.21, distinct(8)=553108.321, null(8)=55310.8321]
                │    ├── cost: 0.01
                │    ├── fd: ()-->(8)
                │    └── cte-uses
                │         └── &1: count=1 used-columns=(7)
                ├── scan security@security_auto_index_fk_s_st_id_ref_status_type
                │    ├── columns: s_symb:9!null
                │    ├── stats: [rows=342500, distinct(9)=342500, null(9)=0]
                │    │   histogram(9)=  0    34    1678    34     1678      34       1678     34     1678     34     1678      34      1678     34      1678     34      1678     34     1678     34     1678     34     1678      34       1678      34       1678       34       1678      34       1678     34     1678     34      1678       34       1678      34       1678     34      1678    34     1678    34     1678     34      1678    34    1678     34      1678       34       1678    34     1678    34    1678     34      1678    34     1678      34       1678     34      1678      34       1678    34     1678      34       1678     34     1678     34     1678      34       1678      34       1678    34     1678    34     1678     34     1678     34     1678     34      1678    34     1678      34       1678      34       1678    34     1678       34       1678     34     1678      34       1678     34     1678     34      1678     34     1678     34      1678     34      1678     34     1678    34     1678       34       1678    34     1678      34       1678       34       1678     34      1678     34     1678     34      1678     34     1678       34       1678     34      1678     34     1678     34     1678     34      1678     34     1678     34     1678     34      1678     34     1678     34      1678     34      1678     34     1678    34     1678      34       1678      34      1678      34       1678       34       1678    34     1678    34     1678       34       1678    34     1678     34     1678     34     1678     34     1678     34     1678     34      1678    34     1678     34     1678     34     1678    34     1678     34     1678      34       1678     34     1678     34      1678     34      1678      34       1678     34     1678       34       1678     34      1678     34     1678      34       1678      34       1678     34     1678     34     1678     34      1678    34     1678      34       1678     34     1678    34     1678     34     1678     34     1678     34     1678     34      1678     34      1678      34      1678       34       1678       34       1678     34     1678     34     1678     34      1678     34     1678     34     1678     34      1678       34       1678     34     1678     34     1678     34     1678      34       1678    34    1678     34      1678      34       1678       34       1678    34     1678      34       1678      34      1678     34     1678     34     1678      34       1678     34     1678     34     1678     34     1678     34      1678     34      1678    34     1678    34     1712     34      1712     34     1712      34      1712      34      1712       34       1712      34       1712     34      1712     34      1712     34      1712     34      1712     34      1712     34     1712     34      1712    34     1712     34      1712     34     1712     34     1712      34       1712     34     1712      34       1712       34       1712     34      1712       34       1712      34      1712    34     1712      34       1712   34    1712      34      1712     34      1712     34     1712     34     1712     34     1712     34     1712    34    1712     34     1712     34     1712     34     1712    34     1712     34     1712      34       1712     34      1712     34     1712     34      1712     34     1712     34     1712      34      1712     34      1712      34       1712    34
                │    │                <--- 'A-ah' ------ 'ABY-j' ------ 'ADAMPRB-s' ------ 'ADVP-g' ------ 'AGIL-u' ------ 'AKPRA-aa' ------ 'ALGI-as' ------ 'AMBK-aq' ------ 'AMPD-z' ------ 'ANIK-q' ------ 'APAT-h' ------ 'APTMPRC-z' ------ 'ARTWPRD-s' ------ 'ASPXPRA-ar' ------ 'ATRPRB-ab' ------ 'AVCI-p' ------ 'AXYS-af' ------ 'BBQZPRC-aj' ------ 'BDCOPRA-a' ------ 'BFUNPRA' ------ 'BKF-h' ------ 'BMC-i' ------ 'BONT-ae' ------ 'BR-q' ------ 'BSET-aj' ------ 'BVRSPRA-ap' ------ 'CAL-i' ------ 'CB-p' ------ 'CCBL-ak' ------ 'CCU-v' ------ 'CDSYPRA-i' ------ 'CERO-ar' ------ 'CHBPRD-ar' ------ 'CHS-j' ------ 'CKRPRC-ar' ------ 'CLS-af' ------ 'CMNT-q' ------ 'CNFLPRA-e' ------ 'COBZPRA-o' ------ 'CPB-j' ------ 'CRE-h' ------ 'CRXL-k' ------ 'CSPI-w' ------ 'CTLMPRA' ------ 'CVS-t' ------ 'CYCLPRB-r' ------ 'DCNPRA-aq' ------ 'DF-ad' ------ 'DJCOPRA-am' ------ 'DORL-e' ------ 'DRYRPRA-a' ------ 'DTEC-t' ------ 'EBIX-ae' ------ 'EFTD-z' ------ 'ELNK-ah' ------ 'ENDO-ap' ------ 'EOG-au' ------ 'EPN-o' ------ 'ESBFPRB-av' ------ 'ETR-m' ------ 'EXJFPRB-h' ------ 'FASHPRA-ab' ------ 'FCTR-af' ------ 'FFED-i' ------ 'FILE-aq' ------ 'FLXS-k' ------ 'FMXIPRB-ar' ------ 'FRIZ-at' ------ 'FTFC-i' ------ 'GBCB-g' ------ 'GEOI-at' ------ 'GIL-aw' ------ 'GLUX-y' ------ 'GNTA-aj' ------ 'GPS-ah' ------ 'GSIC-ae' ------ 'GUPB-ae' ------ 'HAT-as' ------ 'HDL-i' ------ 'HHSPRA-ap' ------ 'HMCPRA-v' ------ 'HORCPRC-s' ------ 'HRZBPRD-aa' ------ 'HVT-p' ------ 'IBM-r' ------ 'IDPHPRA-at' ------ 'IIS-y' ------ 'IMOS-w' ------ 'INMT-r' ------ 'IPLY-s' ------ 'ISKO-c' ------ 'ITXC-aa' ------ 'JBX-p' ------ 'JLMC-t' ------ 'JUNO-h' ------ 'KIM-o' ------ 'KPC-ai' ------ 'KWDPRB-ae' ------ 'LBI-at' ------ 'LEON-ab' ------ 'LION-as' ------ 'LNCPRB-an' ------ 'LRY-am' ------ 'LUMEPRA-an' ------ 'LYTS-ao' ------ 'MAJR-d' ------ 'MAXEPRA-p' ------ 'MCCPRA-ah' ------ 'MCTR-n' ------ 'MDWV-s' ------ 'MFCO-ao' ------ 'MHP-x' ------ 'MKTGPRC-h' ------ 'MMS-at' ------ 'MPV-s' ------ 'MRXX-q' ------ 'MTLK-l' ------ 'MVSN-i' ------ 'NASB-aa' ------ 'NCEM-ao' ------ 'NEVPRB-d' ------ 'NIAGPRA-aq' ------ 'NOIZPRC-am' ------ 'NSAT-i' ------ 'NTES-o' ------ 'NUFO-ao' ------ 'NXL-ae' ------ 'OCA-ab' ------ 'OGSI-ap' ------ 'OMTLPRA-al' ------ 'OPHM-o' ------ 'OSG-as' ------ 'PAAS-g' ------ 'PCAFPRB-e' ------ 'PDFS' ------ 'PERF-al' ------ 'PFSBPRA-j' ------ 'PHFCPRA-as' ------ 'PKS-g' ------ 'PMRPPRA-n' ------ 'POIPRC-q' ------ 'PRBZ-u' ------ 'PRSF-g' ------ 'PSITPRA-v' ------ 'PVA-ah' ------ 'PZZA-j' ------ 'QRAY-s' ------ 'RBNF-aq' ------ 'REFR-ag' ------ 'REY-f' ------ 'RHI-q' ------ 'RMTI-am' ------ 'RSAS-y' ------ 'RYAAY-aw' ------ 'SALNC-ar' ------ 'SBGAPRB-ah' ------ 'SCIOPRB-r' ------ 'SDAY-ar' ------ 'SFNC-aw' ------ 'SHOO-ar' ------ 'SIPX-ao' ------ 'SKYW-al' ------ 'SMPX-y' ------ 'SNAP-ah' ------ 'SNV-j' ------ 'SPEC-aj' ------ 'SQST-j' ------ 'SSTR-d' ------ 'STLDPRA-m' ------ 'SUP-al' ------ 'SYBRPRD-m' ------ 'TASRPRA-ad' ------ 'TCNO-af' ------ 'TEAMPRA-al' ------ 'TFONY-as' ------ 'TIE-t' ------ 'TKTXPRA-x' ------ 'TNB' ------ 'TRBPRB-y' ------ 'TRKN-ar' ------ 'TSBK-g' ------ 'TUC-ag' ------ 'TXN-ac' ------ 'UBPPRD' ------ 'UL-n' ------ 'UNTD-t' ------ 'USPH-c' ------ 'VCBI-g' ------ 'VHI-j' ------ 'VLY-am' ------ 'VRLKPRB-x' ------ 'VWPTPRD' ------ 'WEBK-s' ------ 'WGRD-ac' ------ 'WMC-ak' ------ 'WSBA-a' ------ 'WXHPRA-o' ------ 'XTRM-ap' ------ 'ZGENPRB-z' ------ 'ZYI-u'
                │    ├── cost: 363050.02
                │    ├── key: (9)
                │    ├── prune: (9)
                │    └── unfiltered-cols: (9-24)
                └── filters
                     └── wi_s_symb_new:8 = s_symb:9 [outer=(8,9), constraints=(/8: (/NULL - ]; /9: (/NULL - ]), fd=(8)==(9), (9)==(8)]
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: rework error generated for apply join under With

We currently don't support the correlated side of an apply join to
refer to any outer CTEs. This change reworks #45227 to
detect this condition earlier, rather than relying on things breaking
in a particular place.

Release note: None

#### opt: rework With bindings

The `WithScan` operator refers to the results of a "bound" expression.
We need the properties and statistics of the bound expressions to
calculate the properties of `WithScan`. Because expressions can get
copied between memos (to implement caching), `WithScan` can't directly
refer to the bound expression.

The current solution is to just refer to the bound expression's
Relational properties. Since the properties are immutable, it's ok if
the properties were originally part of a different memo.

This solution has a big problem when prepared statements are used.
Even after assigning placeholders, WithScan refers to the relational
properties of the original built expression (when placeholders didn't
have values). Unfortunately, without placeholders the statistics in
the original expression can be very poor (we currently have no
incentive to handle placeholders in any reasonable way, as they always
get replaced before optimization). I believe #51648 is an instance of
this (I verified in an opt test that if we build the expression with
the placeholders, the row counts are high).

Another problem of this solution is that we can't calculate new column
statistics from the bound expression (because it would mean modifying
the bound properties).

This change addresses both problems by storing the bound expression in
the metadata. To make this work, we need to add special code in
`CopyAndReplace` to set this information. We achieve this by using a
new `WithBinding` tag and the convention that any operator with this
tag implements a `WithBindingID()` method.

Fixes #51648.

Release note (bug fix): Fix instances of slow plans for prepared
queries involving CTEs or foreign key checks.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: very nice!

> Reviewed 5 of 5 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-:-MCxD3r00SJ7aoKpXhCG:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/ops/README.md, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MCx7J0O2-2V5JsEDvk5:-MCx7J0P3kH6huY9DpKM:b-h9l2l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3a7add5c4e1d62a93612f003646fe065ec57b4/pkg/sql/opt/ops/README.md#L72)):*
> ```Markdown
>    conjunction with the `Mutation` tag.
>  - `WithBinding`: used for operators which associate a WithID with the
>    expression in the first children. Such expressions must implement a
> ```

[nit] children -> child
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MCxCjGy-nAMzMQKOdoA:-MCxCjGy-nAMzMQKOdoB:brxdrd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3a7add5c4e1d62a93612f003646fe065ec57b4/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L337)):*
> ```Go
> 		if define.Tags.Contains("Relational") || len(childFields) != 0 {
> 			if len(childFields) != 0 {
> 				if define.Tags.Contains("WithBinding") {
> ```

would be good to add this to one of the optgen tests

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51788)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/ops/README.md, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MCx7J0O2-2V5JsEDvk5:-MCxfE0b6LsufyK9XZjQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3a7add5c4e1d62a93612f003646fe065ec57b4/pkg/sql/opt/ops/README.md#L72)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] children -> child
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MCxCjGy-nAMzMQKOdoA:-MCxfEP8E8YZy6NdITq-:b-fznoh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3a7add5c4e1d62a93612f003646fe065ec57b4/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L337)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to add this to one of the optgen tests
</blockquote></details>

Good idea, done!

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-:-MD-qALUDa6Fb6rzpGG0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/optgen/cmd/optgen/testdata/factory, line 606 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MD-pFmo7VTvXi-WYtUI:-MD-pFmo7VTvXi-WYtUJ:b-xx7a7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/eca1666524e5146d83d0d780be15a32ccbdaea9a/pkg/sql/opt/optgen/cmd/optgen/testdata/factory#L606)):*
> ```
> // callback by recursively calling Replace. It can also return a replacement
> // expression; if it does, then Replace will rebuild the operator and its
> // ancestors via a calls to the corresponding factory Construct methods. Here
> ```

[nit] not your change, but while you're making changes to optgen....

a calls -> calls

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51788)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/optgen/cmd/optgen/testdata/factory, line 606 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-MD-pFmo7VTvXi-WYtUI:-MD0aNE--91Y3FWVUITA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eca1666524e5146d83d0d780be15a32ccbdaea9a/pkg/sql/opt/optgen/cmd/optgen/testdata/factory#L606)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] not your change, but while you're making changes to optgen....

a calls -> calls
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51788#-:-MD0aPJw4XS814Fxcf2l:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

**Pull request merged**
