### PR TITLE
colexec: add vectorized cross joiner

### LINKED ISSUE #46205: colexec: implement specialized cross join operator
In the row-by-row engine hash join processor performs the cross join. However, in the vectorized engine, the hash join operators (both in-memory and external) have a built-in assumption of non-empty equality columns. We should create a specialized disk-backed cross join operator to support such case in `colexec`. See #46204.

### PR DESCRIPTION
**Pull request by yuzefovich**
**descpb: add helper method for computing output types of joins**

Release note: None

**colexec: shorten merge joiner benchmark**

This commit adjust the merge joiner benchmark to run faster (from 145s
to 54s on my laptop) by removing the smallest row options and reducing
the number of options from 5 to 4.

Release note: None

**colexec: extract cross joiner base from the merge joiner**

This commit extracts the logic of building from the buffered groups in
the merge joiner into a cross joiner base struct which will allow us to
reuse it for implementing the disk-backed vectorized cross joiner. The
logical changes were kept to minimum.

Release note: None

**colexec: add vectorized cross joiner**

This commit adds the vectorized cross joiner with the core building
logic being reused from the base struct extracted from the merge joiner.
The new operator simply needs to consume the inputs to set up the base
struct while also paying attention to possibly unmatched tuples (this
was never the case for the buffered group in the merge joiner). It also
optimizes the behavior in how the inputs are consumed depending on the
join type.

Fixes: #46205

Release note: None

**colexec: optimize cross joiner for some join types**

This commit optimizes the cross joiner a bit by taking advantage that
for some join types we need to repeat left tuples only once. It
additionally cleans up the logic around exiting from the build methods
so that we don't run into a situation where `toAppend` is 0 (which is
pointless).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks of the cross joiner base extraction are [here](https://gist.github.com/yuzefovich/b2fc2924206553202bcc687fe57813a1) and of the cross joiner optimization are [here](https://gist.github.com/yuzefovich/1b5e1e239567d59e0868f3f6f7556e95).

**Review by asubiotto — COMMENTED** [review]
Will take a look at this once the spilling queue PR merges.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-:-MQSLtgt-le9AwqaEjXC:bimn0rr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Rebased on top of the spilling queue fix, RFAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 21 of 21 files at r3, 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/catalog/descpb/join_type.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvOuMpA9qL4dRE-Xxi:-MQvOuMpA9qL4dRE-Xxj:b-5u37yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bfceb3a16dfaa3704cf169249e4a010b1e873c8/pkg/sql/catalog/descpb/join_type.go#L123)):*
> ```Go
> 	outputTypes := make([]*types.T, 0, numOutputTypes)
> 	if j.ShouldIncludeLeftColsInOutput() {
> 		outputTypes = append(outputTypes, left...)
> ```

nit: why not put these lines into the conditionals above to avoid having to check both conditions twice? You can give `outputTypes` a `len(left)+len(right)` capacity.
___
*[pkg/sql/colexec/crossjoiner.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvQ0Wy7KsKfKQe9oAU:-MQvQ0Wz8jji_yRxwe4l:b-rtm5ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa40fbee19b6ff944b631ad359318232dd01764/pkg/sql/colexec/crossjoiner.go#L29)):*
> ```Go
> 
> // TODO(yuzefovich): use two separate unlimited allocators and give each
> // spillingQueue a half of the memory limit.
> ```

IIUC, I think we should do this in this PR to limit up to the work mem. It shouldn't be too hard, right?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 898 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvSkMa8XQJUHSw_BrS:-MQvSkMa8XQJUHSw_BrT:b-vzuedh) ([raw file](https://github.com/cockroachdb/cockroach/blob/450962abd16c6c6f0bf42997e99a4b54378554e9/pkg/sql/colexec/colbuilder/execplan.go#L898)):*
> ```Go
> 			copy(rightTypes, spec.Input[1].ColumnTypes)
> 
> 			if len(core.HashJoiner.LeftEqColumns) == 0 {
> ```

Is it unnecessary to check RightEqColumns?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/catalog/descpb/join_type.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvOuMpA9qL4dRE-Xxi:-MQz3t8EAJdpeVc1MfFt:b9nbsdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bfceb3a16dfaa3704cf169249e4a010b1e873c8/pkg/sql/catalog/descpb/join_type.go#L123)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: why not put these lines into the conditionals above to avoid having to check both conditions twice? You can give `outputTypes` a `len(left)+len(right)` capacity.
</blockquote></details>

I agree that this looks a bit ugly, but I'm guessing this approach should be more performant overall due to not having wasteful allocations. I also checked that the `ShouldInclude*` methods get inlined, so I'd prefer to keep as is, but let me know if you feel strongly otherwise.
___
*[pkg/sql/colexec/crossjoiner.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvQ0Wy7KsKfKQe9oAU:-MQz648vBbBamGzBVglY:b-cr2wov) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa40fbee19b6ff944b631ad359318232dd01764/pkg/sql/colexec/crossjoiner.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

IIUC, I think we should do this in this PR to limit up to the work mem. It shouldn't be too hard, right?
</blockquote></details>

Note that the workmem limit will be respected, but the current behavior is somewhat unfortunate in some cases - it is possible that the spilling queue for the left side will use up all of the memory, and then the right spilling queue will have to spill to disk right away. But the optimal behavior is probably giving larger limit to the right queue since it might be read multiple times.

Anyway, I think it is ok to keep it as a TODO since changing the merge joiner to have two separate unlimited allocators seems a bit invasive.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 898 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-MQvSkMa8XQJUHSw_BrS:-MQz7cBgAiaefMhMsNZy:b-qy86h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/450962abd16c6c6f0bf42997e99a4b54378554e9/pkg/sql/colexec/colbuilder/execplan.go#L898)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it unnecessary to check RightEqColumns?
</blockquote></details>

We must have the same number of equality columns on both sides, so it is not necessary. If somehow we have no left eq columns but have some right eq columns, that indicates that something really bad happened during the physical planning, but I don't think it's worth adding an assertion for it.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 29 of 29 files at r5, 1 of 1 files at r6, 21 of 21 files at r7, 9 of 9 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58280#-:-MR-eSC5DJk5rXfvRYa4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
