### PR TITLE
kv: push abort txns after heartbeat failure instead of EndTxn

### LINKED ISSUE #18901: tpcc loadgen produces foreign key violation
@jordanlewis this happened to me once. Does it look like a server problem or a client problem?

```
[andrei:~/work/src/github.com/cockroachdb/loadgen/tpcc] master 49s 1 ± ./tpcc -concurrency=128
_time______opName__ops/s(inst)__ops/s(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   1s        tpmC         30.0        29.8    637.5    973.1   1006.6   1006.6
   2s        tpmC         34.0        31.9   1208.0   1744.8   1879.0   1879.0
2017/09/28 16:46:22 error in tpmC: pq: foreign key violation: value [0 6 3162] not found in order@primary [o_w_id o_d_id o_id]
```

### PR DESCRIPTION
**Pull request by spencerkimball**
Previously when a transaction heartbeat failed, the txn coordinator
would abort the transaction by asynchronously issuing an
`EndTransactionRequest` with `Commit=false`. Unfortunately, this
would cleanup the intents without leaving any abort span record,
resulting in the potential for incorrect results to be returned
for concurrently inflight commands.

This change moves to instead issue a `PushTxnRequest` with
`PushType=PUSH_ABORT` to abort the transaction record without
cleaning up the intents. Any intents forcibly cleaned up by other
actors will then leave abort span entries, eliminating any
confusion for concurrent commands.

Fixes #18901

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
I don't like this change... I liked the cleanup... And I think we should take the opportunity to make the heartbeat more like a "lease" that you check for validity on the results return path.

#23055 has some commits that plug some leaked txns. I think you might need them here, as the `EndTransaction` the heartbeat loop was sending might have been the only one they were getting.

If the PR stays, please add a test checking that we can send an `EndTransaction` after `tryAsyncAbort` has run - checking that the TCS state still allows us to send that request (but doesn't let us send anything but that?). Unless that test already exists.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 992 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24048#-L839g5-YFa-shGcqR-8:-L839g5-YFa-shGcqR-9:bdrd7xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e84843115a36fdebe8ed60c54e079566da442fd/pkg/kv/txn_coord_sender.go#L992)):*
> ```Go
> // intents (which it then clears from meta), and asynchronously tries
> // to abort the transaction.
> func (tc *TxnCoordSender) tryAsyncAbort(ctx context.Context) {
> ```

method name is obsolete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24048#-:-L83AS4NOL-Eg78-elz4:bt0r3rk)*

**Comment by spencerkimball** [comment]
What do you mean "I liked the cleanup"?

#23055 appears irrelevant to this effort. Doing a push txn which aborts the txn is effectively the same thing as calling `EndTransaction`. This introduces no "leaks" of transactions.

Why would we send an `EndTransaction` after `tryAsyncAbort`? The TCS will prevent that via the `maybeRejectClientLocked` method.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/txn_coord_sender.go, line 992 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24048#-L839g5-YFa-shGcqR-8:-L83FmJYeJ1h72ru-ukA:bgli38w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e84843115a36fdebe8ed60c54e079566da442fd/pkg/kv/txn_coord_sender.go#L992)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

method name is obsolete
</blockquote></details>

Why? This still tries to do an asynchronous abort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24048#-:-L83EgvVcra8a_GJAUze:b10hg4s)*

**Comment by andreimatei** [comment]
> What do you mean "I liked the cleanup"?

The commit message says: 
> This change moves to instead issue a `PushTxnRequest` with
> `PushType=PUSH_ABORT` to abort the transaction record without
> cleaning up the intents

I liked the cleaning of intents. Who's gonna clean up the intents? Particularly if `maybeRejectClientLocked` prevents anyone from sending an `EndTransaction` afterwards?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24048#-:-L83HKN5Xt9pMhSimKNb:b-155d7q)*

**Comment by bdarnell** [comment]
Yeah, I think I'd rather add a `poison` flag to `EndTransactionRequest` than switch to `PushTxn` since that lets us clean up the intents faster (or we could push and separately hand our intents to our intent resolver)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83HsvZ69ADNcHOYDOl:bjy3hqn)*

**Comment by spencerkimball** [comment]
I agree cleaning up intents is nice, but heartbeats failing should be relatively rare, so I think the complexity of the change should be balanced against the cost. I can separately send the PR to add a `poison` flag to `EndTransactionRequest` – it's more complicated.

**Comment by andreimatei** [comment]
I don't think the "poison" flag is required or the right thing either.
I think all that's needed is a few lines of code in `TCS.Send()` that check the success and the timing of the last heartbeat.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83JF5zDif3SkMuj0sQ:b-5nb4ww)*

**Comment by spencerkimball** [comment]
It would be different than the heartbeat. We'd need to check the actual state of the TCS – whether or not it's been `aborted`. I'm not saying that wouldn't fix it. But what I'm not comfortable with is cleaning up KV state in such a way that undermines the machinery at that level meant to prevent inconsistencies. Calling `EndTransaction` out of band does just that. Doing so and then relying on the TCS to always be the oracle for preventing inconsistencies is fragile.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83NsC10G_WJwDn9a76:buelsl)*

**Comment by andreimatei** [comment]
> But what I'm not comfortable with is cleaning up KV state in such a way that undermines the machinery at that level meant to prevent inconsistencies.

Here's  how I see it : the "inconsistencies" in question are strictly about a transaction missing its own writes. Since it is about your own writes, and since you already have to perform heartbeats to maintain this guarantee, and since I believe you have to check the state of the heartbeat before returning any results ("you" being the `client.Txn` object) I don't understand why we'd do anything else but just that - check the state of the heartbeat whenever it needs to be checked.
I see no reason for the poison...
In fact, I'd rather get rid of the "async" `EndTransaction/PushTxn{Abort}` request all together (but still add another check about the last successful heartbat to the result return path, and make sure that an `EndTransaction` can still be sent by the user of the `client.Txn`), than do any of the poisoning. And btw, no matter what we do, I think we need to make sure that an `EndTransaction` being sent after this "async abort" does not result in an error.
My 2c.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83bzD83r_DWYE09eoW:brcwcqm)*

**Comment by tschottdorf** [comment]
Like @andreimatei, I want to get rid of this async abort in the first place, but it seems a little ambitious for the 2.0 time frame. And I agree with @spencerkimball that changing from `EndTransaction` to `PushTxn` is a step in the right direction and that every out-of-band use of `EndTransaction` is something to worry about. If we have to stick to cleaning up the intents (unclear to me that we have to, but I guess the burden of proof is on the change), then we could add an `Intents` field to `PushTxn` that can only be populated during `PUSH_ABORT` and preserves that side effect.

And @andreimatei, I'm with you in spirit on rejecting the clients. But is it really just a few lines of code? If a request is in progress, then we fire of the async request, do we error out the in-flight request even if it succeeds? That's another source of ambiguous errors. Or were you planning to slap a mutex on "currently sending" and synchronize the async abort with that? Either way, I'd still switch to a Push, so what you're suggesting is orthogonal.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83r-pNEdgR_PXhX0AJ:bxwe1d)*

**Comment by tschottdorf** [comment]
(Just realized I mixed up your suggestions, please take that into account as you try to decipher them)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L83tS2c1UzTG4HvhbXH:b-g23dnf)*

**Comment by andreimatei** [comment]
>  If a request is in progress, then we fire of the async request, do we error out the in-flight request even if it succeeds? That's another source of ambiguous errors. 

Yes, we'd error out even if it succeeds. But I don't think anything is ambiguous - if the request was not an `EndTransaction` then there's no ambiguity - we'd return whatever error `maybeRejectClient()` currently returns. If it was, it cannot race with the async heartbeat stuff. Right?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L840vXK8zgahbKFFKQ6:b-44of2y)*

**Comment by spencerkimball** [comment]
Come on guys, this see sawing is getting ridiculous. I'm going with the cleanup and `EndTransactionRequest` in #24074. Neither approach is perfect and arguments can be made for both, but, "shit or get off the pot", and I'm going with the approach that cleans up the intents.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24048#-:-L851ieF1tOLJqhy0V32:bthlcq0)*

**Comment by andreimatei** [comment]
> Neither approach is perfect and arguments can be made for both, but, "shit or get off the pot", and I'm going with the approach that cleans up the intents.

There are 4 suggestions, not 2: 
1) `EndTransaction` + poison
2) `PushTxn{Abort}`
3) `EndTransaction` (no poison) + check the heartbeat at the end of `TCS.Send()`
4) no async abort of any kind + check the heartbeat timing at the end of `TCS.Send()`

3 and 4 are both perfect as far as I can see - my feeling is that I prefer 3 and Tobi prefers 4. I see that you don't like them, but I don't understand why. And I think they'd be simpler than what you're doing. All you said is "relying on the TCS to always be the oracle for preventing inconsistencies is fragile" to which I think I've responded how it's not fragile at all; it'd very much in both the spirit and the practice of the TCS - all requests already go through it for reasons including precisely the need to check on the heartbeats. You've ignored that :) An extension to the `EndTransaction` that looks to me to be unnecessary really seems unattractive (to me).
If you keep the pot open a bit longer, I'll try to shit something tomorrow.

**Comment by spencerkimball** [comment]
3) creates incorrect conditions in the event that future usage escapes the confines of the TCS. That’s what I mean by fragile. You’re certain all usage is restricted to the TCS and always will be. I’m much less certain. Even if we always check the top level TCS before we ever return any data in a dist sql flow, option 3 would still allow leaf TCS flows to read inconsistent state, which despite not introducing any incorrectness as long as we strictly check the root TCS heartbeat, is a significant departure from the current model, which either returns an error from the KV layer or returns a consistent result. This is not the elegant solution you present it as because it tears a hole in the side of the KV model which you are simply papering over at a higher level.

4) does not clean up intents, which is what ultimately convinced me not to go with option 2. In my testing of large transactions, I realized that continually leaving many intents in the system causes crippling performance degradation. We do a bad job of dealing with this scenario as each intent, despite being on the same range even, causes a txn push, despite only the first actually being relevant.

By all means, add a check in the TCS for state when `Send()` exits. You will also need to expose a state check for the dist sql leaf flows. But the `EndTransactionRequest.Poison` approach is appropriate regardless.

**Comment by bdarnell** [comment]
There's also a fifth option: No async abort of any kind and don't check heartbeat status at the end of TCS.Send. Checking the heartbeat status  is only necessary when failed heartbeats result in a non-poisoning EndTransaction. Failing a heartbeat leaves a window open for someone else to abort your transaction but it doesn't automatically end it; you can continue with a gap in your heartbeat sequence if no other transaction objects. 

I think the entire reason `tryAsyncAbort` was introduced was to clean up the intents. If we are going to leave the intents for some future transaction to stumble across, we might as well leave the transaction open too, so I don't think option 2 (push/abort) makes much sense. I think the best options are 1 (end+poison) or 5 (completely ignore heartbeat failures).

**Comment by spencerkimball** [comment]
I think until we do a better job with on-the-fly resolution of many intents, the cleanup is a good idea and I've become increasingly convinced over the course of this discussion that the last thing we should do is land a change, that we backport to 2.0, which stops doing intent cleanup.

**Pull request closed without merging**
