### PR TITLE
sql: pool some of the processor allocations

### PR DESCRIPTION
**Pull request by yuzefovich**
**execinfra: fix temporary memory leak of expressions**

This commit fixes the way we reuse the ProcOutputHelpers. Previously, we
would not perform the deep reset of the render expressions which could
lead to those expressions being live for longer than needed (namely till
the helper is reused the next time). This matters when the ProcessorBase
is reused which currently only happens when TableReaders are used from
the sync.Pool. This probably was a pretty bad issue before the
vectorized engine, but nowadays its impact seems minor. Still, it's good
to fix it, especially given the following commit which will introduce
more pooling of processors.

Release note: None

**execinfra: reuse output row allocation in the helper**

This commit makes it so that we reuse the output row in the
ProcOutputHelper if possible. Additionally, it removes a row alloc
object since it is not helpful and only leeds to wasteful allocations.
It also removes a redundant integer for the number of "internal
columns".

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Impact of all three commits:
```
name                                                           old time/op    new time/op    delta
SQL/Cockroach/UpdateWithAssignmentCast/count=1-24                 991µs ± 4%     994µs ± 4%    ~     (p=1.000 n=10+9)
SQL/Cockroach/UpdateWithAssignmentCast/count=10-24               1.28ms ± 4%    1.29ms ± 3%    ~     (p=0.218 n=10+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=100-24              3.32ms ± 5%    3.39ms ± 5%    ~     (p=0.143 n=10+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=1000-24             24.0ms ± 4%    23.3ms ± 6%    ~     (p=0.052 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1-24       1.64ms ± 5%    1.61ms ± 5%    ~     (p=0.353 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=10-24      1.98ms ± 5%    1.88ms ± 9%  -4.65%  (p=0.035 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=100-24     4.02ms ± 7%    4.05ms ± 8%    ~     (p=0.684 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1000-24    24.2ms ± 4%    23.0ms ± 4%  -5.32%  (p=0.001 n=8+9)

name                                                           old alloc/op   new alloc/op   delta
SQL/Cockroach/UpdateWithAssignmentCast/count=1-24                 102kB ± 5%      94kB ± 6%  -8.27%  (p=0.000 n=10+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=10-24                154kB ±13%     145kB ±11%    ~     (p=0.105 n=10+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=100-24               609kB ±12%     607kB ±13%    ~     (p=0.842 n=9+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=1000-24             3.70MB ± 9%    3.72MB ±17%    ~     (p=0.888 n=8+9)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1-24        158kB ± 9%     146kB ± 9%  -7.72%  (p=0.021 n=9+8)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=10-24       244kB ±51%     231kB ±33%    ~     (p=0.353 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=100-24     1.00MB ±47%    1.00MB ±57%    ~     (p=0.912 n=10+10)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1000-24    7.31MB ±20%    7.32MB ±17%    ~     (p=0.863 n=9+9)

name                                                           old allocs/op  new allocs/op  delta
SQL/Cockroach/UpdateWithAssignmentCast/count=1-24                   864 ± 2%       852 ± 1%  -1.35%  (p=0.010 n=9+9)
SQL/Cockroach/UpdateWithAssignmentCast/count=10-24                1.18k ± 8%     1.15k ± 1%    ~     (p=0.138 n=10+9)
SQL/Cockroach/UpdateWithAssignmentCast/count=100-24               3.34k ± 6%     3.35k ± 5%    ~     (p=0.324 n=10+10)
SQL/Cockroach/UpdateWithAssignmentCast/count=1000-24              14.3k ± 6%     14.4k ± 7%    ~     (p=0.489 n=9+9)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1-24        1.43k ± 3%     1.41k ± 4%  -1.70%  (p=0.044 n=9+8)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=10-24       1.83k ± 1%     1.81k ± 2%    ~     (p=0.062 n=9+9)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=100-24      5.32k ±30%     4.95k ± 1%    ~     (p=0.649 n=10+8)
SQL/MultinodeCockroach/UpdateWithAssignmentCast/count=1000-24     19.8k ± 1%     19.7k ± 3%    ~     (p=0.387 n=9+9)
```

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 10 of 10 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88608#-:-ND-dvJX3K4_FlE6ZNW7:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colexec/columnarizer.go` line 168 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/88608#-ND-ReQk4wP2JUp3Vqt0:-ND-ReQl79QgeEfoC69O:b-7c7nc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d016fd2af32ad733278929aa7a22394f05ce3bcc/pkg/sql/colexec/columnarizer.go#L168)):*
> ```Go
> 		execinfra.ProcStateOpts{
> 			// We append input to inputs to drain below in order to reuse the same
> 			// underlying slice from the pooled noopProcessor.
> ```

[nit] noopProcessor -> columnarizer

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88608#-:-ND-nXeu1vtYxSk7MS-3:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/colexec/columnarizer.go` line 168 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/88608#-ND-ReQk4wP2JUp3Vqt0:-ND-nZ6I1j_ejrYypbSR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d016fd2af32ad733278929aa7a22394f05ce3bcc/pkg/sql/colexec/columnarizer.go#L168)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] noopProcessor -> columnarizer
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Alright, these bors failures were legitimate, need to make some tweaks.

**Comment by yuzefovich** [comment]
I'm still working through some things, so please hold off on reviewing - I'll ping once it's ready for a look.

**Comment by yuzefovich** [comment]
It's not as easy of a fix, so I removed the last commit that exposed a pre-existing bug (will file an issue soon) and will merge just the first two simple commits.

bors r+

**Pull request merged**
