### PR TITLE
add table key_column_usage for information_schema

### PR DESCRIPTION
**Pull request by a6802739**
please look at #8675. @nvanbenschoten, please help me have a review, thanks a lot.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9114)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Hi @a6802739, thanks for the help with this! The general approach looks good, but I do have a few comments.

---

Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1OwKEosKs8HGMLA0v:-KR1OwKFGrXuAFrBJI8j:b-40k3gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L34)):*
> ```Go
> 		informationSchemaTableConstraintTable,
> 		informationSchemaTablesTable,
> 		informationSchemaKeyColumnUsage,
> ```

This is being kept in alphabetical order.

---

*[sql/information_schema.go, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1P702qcz3xqEb0WUr:-KR1P702qcz3xqEb0WUs:b-vvl9r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L266)):*
> ```Go
> }
> 
> var informationSchemaKeyColumnUsage = virtualSchemaTable{
> ```

Same here, lets move this up to the correct position.

---

*[sql/information_schema.go, line 271 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1PI0XfTs2Y2kMFXRd:-KR1PI0XfTs2Y2kMFXRe:b-uc38sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L271)):*
> ```Go
>   CONSTRAINT_CATALOG STRING NOT NULL DEFAULT '',
>   CONSTRAINT_SCHEMA STRING NOT NULL DEFAULT '',
>   CONSTRAINT_NAME STRING NOT NULL DEFAULT '',
> ```

This can be null, right?

---

*[sql/information_schema.go, line 277 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1SqvJlKzXltzJ28aB:-KR1SqvKe-U7Zoyf-Ra7:b-2ie0os) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L277)):*
> ```Go
>   COLUMN_NAME STRING NOT NULL DEFAULT '',
>   ORDINAL_POSITION INT NOT NULL DEFAULT 0,
>   POSITION_IN_UNIQUE_CONSTRAINT INT NOT NULL DEFAULT 0
> ```

So can this, right?

---

*[sql/information_schema.go, line 282 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1PXiNIvocvERP_nJ7:-KR1PXiNIvocvERP_nJ8:brg4ev6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L282)):*
> ```Go
> 		return forEachTableDesc(p,
> 			func(db *sqlbase.DatabaseDescriptor, table *sqlbase.TableDescriptor) {
> 				type constraint struct {
> ```

Is `constaint` the right name here? Seems like `keyColumn` might be more appropriate.

---

*[sql/information_schema.go, line 292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1PvVz0nGGMbOBZvCf:-KR1PvVz0nGGMbOBZvCg:b-nywsna) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L292)):*
> ```Go
> 				if table.HasPrimaryKey() {
> 					var columnNames []string
> 					columnNames = append(columnNames, table.PrimaryIndex.ColumnNames...)
> ```

Do we need to copy this string slice? We cant just assign it directly to `constraint.columns`?

---

*[sql/information_schema.go, line 301 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1PqNuRCrXipLpU5N_:-KR1PqNuRCrXipLpU5Na:b-n4w04m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L301)):*
> ```Go
> 				for _, index := range table.Indexes {
> 					var columnNames []string
> 					columnNames = append(columnNames, index.ColumnNames...)
> ```

Same question as above.

---

*[sql/information_schema.go, line 318 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1RW9LBgA7aDXexROv:-KR1RW9MMC8SVE1SCUV_:bdcomh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L318)):*
> ```Go
> 					for pos, column := range c.columns {
> 						var uniquePosition int
> 						if c.unique && c.foreignKey {
> ```

Is this possible? We never set both of these flags. Also, this should be null by default.

I'd suggest the following to address this and the next comment:

```
ordinalPos := parser.NewDInt(parser.DInt(pos+1)) // 1-indexed
uniquePos := parser.DNull
if c.unique && c.foreignKey { // or whatever this check should be
  uniquePos = ordinalPos
}
```

---

*[sql/information_schema.go, line 330 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1RIMUTYDjsuAo9PUc:-KR1RIMUTYDjsuAo9PUd:b1cic4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/information_schema.go#L330)):*
> ```Go
> 							parser.NewDString(column),                   // column_name
> 							parser.NewDInt(parser.DInt(pos)),            // ordinal_position, 1-indexed
> 							parser.NewDInt(parser.DInt(uniquePosition)), // position_in_unique_constraint
> ```

Both of these lines should be 1-indexed, right? It doesnt look like we're doing that here.

---

*[sql/testdata/information_schema, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1Rm0D6AeoYcj5SOuf:-KR1Rm0D6AeoYcj5SOug:b-dhlxu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/testdata/information_schema#L459)):*
> ```
> #statement ok
> #DROP DATABASE constraint_db
> ```

Lets add `## information_schema.key_column_usage` like we have throughout. Also, these groups of tests have been ordered in alphabetical order where possible. Lets move this group up.

---

*[sql/testdata/information_schema, line 461 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR1RfAqG0auF-ZxSoaD:-KR1RfAqG0auF-ZxSoaE:b-mvd46n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2950be79c4e6d11de081231ef2c0695a54afa37/sql/testdata/information_schema#L461)):*
> ```
> 
> statement ok
> CREATE DATABASE constraint_column
> ```

We should drop the database after this series of statements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-:-KR1SKCMonyKjKtOR9r5:b-d10hyp)*

**Comment by a6802739** [comment]
got it. thanks a lot. @nvanbenschoten

**Comment by a6802739** [comment]
@nvanbenschoten ，I can't write `DROP DATABASE constraint_column`, so for now I have to write it in the end of file `information_schema`

**Comment by nvanbenschoten** [comment]
Nice! Just a few more comments then I think it's good to ship.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/information_schema.go, line 154 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR6cq7Sl9XHIL7zsdeS:-KR6cq7THkGqEFzCFleX:b-kpmzbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/55977c8acbeef974903d165fa45acbdaf38a1d7e/sql/information_schema.go#L154)):*
> ```Go
>   CONSTRAINT_CATALOG STRING NOT NULL DEFAULT '',
>   CONSTRAINT_SCHEMA STRING NOT NULL DEFAULT '',
>   CONSTRAINT_NAME STRING NOT NULL DEFAULT '',
> ```

Here and `POSITION_IN_UNIQUE_CONSTRAINT` should remove the `NOT NULL` constraint, since it's possible for us to return null below.

---

*[sql/information_schema.go, line 198 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR6crS6wLCgcrywFRie:-KR6crS6wLCgcrywFRif:biibh1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/55977c8acbeef974903d165fa45acbdaf38a1d7e/sql/information_schema.go#L198)):*
> ```Go
> 						ordinalPos := parser.NewDInt(parser.DInt(pos + 1))
> 						uniquePos := parser.DNull
> 						if c.unique && c.foreignKey {
> ```

I still don't see how entering this block is possible. Are you sure it should be `if c.unique && c.foreignKey` instead of just `if c.foreignKey`?

Also, I think we need a test which exercises the case, ideally with a foreign key that looks something like `CONSTRAINT fk FOREIGN KEY (b, a) REFERENCES t1(a, b)` (multiple columns). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-:-KR6grtahMFsWSWX0lJV:b9ycvdg)*

**Comment by a6802739** [comment]
@nvanbenschoten , got it. from [PostgreSQL doc](https://www.postgresql.org/docs/9.5/static/infoschema-key-column-usage.html), I still think it should be `if c.unique && c.foreignKey {`

**Comment by nvanbenschoten** [comment]
Sure, but that's not possible with this code because you're only entering one branch in the switch-case above, so only one of the two flags will ever be set at a time.

**Comment by a6802739** [comment]
@nvanbenschoten , now I change it to `if c.unique || c.foreignKey {`

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 192 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KRa4BDKkUtS_NC3F822:-KRa4BDKkUtS_NC3F823:b-hv77rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/51f019f6366419a8c8135be382c97ae38e07ab75/sql/information_schema.go#L192)):*
> ```Go
> 						col.foreignKey = true
> 						columns = append(columns, col)
> 					}
> ```

When I compare the output here to Postgres or MySQL it looks like we still handle `POSITION_IN_UNIQUE_CONSTRAINT` incorrectly. Try replacing this block with:

```
col := keyColumn{
    name:        index.Name,
    columnNames: index.ColumnNames,
    unique: index.Unique,
    foreignKey: index.ForeignKey.IsSet(),
}
if col.unique || col.foreignKey {
    columns = append(columns, col)
}
```

and below change to `if c.foreignKey { ...`. This will give us the desired behavior.

---

*[sql/testdata/information_schema, line 484 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114#-KR_JM4VvC98l_-LM9gH:-KR_JM4VvC98l_-LM9gI:b-hudbhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/51f019f6366419a8c8135be382c97ae38e07ab75/sql/testdata/information_schema#L484)):*
> ```
> CREATE TABLE constraint_column.t3 (
>     a INT,
> 	b INT,
> ```

strange spacing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9114)*

**Comment by a6802739** [comment]
@nvanbenschoten , so we don't need to handle `primary key`?

**Comment by nvanbenschoten** [comment]
We still do, and your handling of primary key here is fine. There's no need to touch anything other than the loop over `table.Indexes` and the `if` statement surrounding `uniquePos = ordinalPos`.

**Comment by nvanbenschoten** [comment]
This looks good now, thanks @a6802739! The only remaining step is to rebase onto the HEAD of develop, which may involve cleaning up a few merge conflicts. Then we can merge this.

**Comment by a6802739** [comment]
@nvanbenschoten, `The only remaining step is to rebase onto the HEAD of develop`, how could I do this?

**Comment by nvanbenschoten** [comment]
See https://git-scm.com/book/en/v2/Git-Branching-Rebasing. My easy one-liner for this is `git pull --rebase origin develop`, but there's probably a shorter way. You're then going to need to resolve some merge conflicts, presumably from #9104 and #9327. If you'd rather I take care of this messy merge, its not a problem, just follow https://github.com/blog/2247-improving-collaboration-with-forks and I'll make the necessary changes and get it merged.

**Comment by a6802739** [comment]
@nvanbenschoten , I have `Allow edits from maintainers`. If you could help me merge this PR, I would appreciate it very much.

**Comment by nvanbenschoten** [comment]
@a6802739 I've pulled down your branch and made the needed rebase, but it doesnt seem like I have permission to push to your branch. Could you double check that `Allow edits from maintainers` is checked. If it is, maybe we can try adding me as a collaborator to your fork temporarily so that I can push the rebased commit (you'll still be the author of the commit).

**Comment by a6802739** [comment]
@nvanbenschoten, I have `Allow edits from maintainers` and add a collaborator of my fork.

**Comment by nvanbenschoten** [comment]
Thanks again for all the help @a6802739!

**Pull request merged**
