### PR TITLE
sqlccl: fix merge skew

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by arjunravinarayan** [comment]
:lgtm:
Thank you!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16991#-:-Komtmldux_4NaSvBcLg:b44p7rl)*

**Comment by tschottdorf** [comment]
BTW bumped this in the queue, which I just found out is something one can do.

**Comment by tamird** [comment]
Neat! Should add that to the relevant wiki article.

**Pull request merged**
