### PR TITLE
sql: add role_id, member_id columns to system.role_members

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: add role_id, member_id columns to system.role_members

Release note: None

Release justification: Adding is to system.role_members in same way
as system.users, last users table migration for this version.
We don't use the IDs to delete or lookup users yet.

Last system.users related table migration for 22.2

### CODE REVIEW

**Comment by RichardJCai** [comment]
Bump @ajwerner @rafiss, thoughts on merging this? Given that it's the same as the `system.users and system.role_options` ones, I figure it's fine. Also it's somewhat strange to have the other two with id columns and not this.

**Review by ajwerner — COMMENTED** [review]
Given nothing uses this, do we get benefit from having migrated all the tables? Is it correct that nothing uses it? 

> Reviewed 6 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85928#-:-NA75xnL05EiKca0YA9V:b-qz29r0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rhu713)

**Comment by RichardJCai** [comment]
> Given nothing uses this, do we get benefit from having migrated all the tables? Is it correct that nothing uses it?
> 
> > Reviewed 6 of 24 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85928#-:-NA75xnL05EiKca0YA9V:b-qz29r0)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rhu713)

Yeah we don't use it for reads right now.

**Comment by andyyang890** [comment]
Superseded by #91517

**Pull request closed without merging**
