### PR TITLE
sqlproxyccl: track which side broke the connection

### PR DESCRIPTION
**Pull request by jeffswenson**
Previously, the sqlproxy considered an error when copying from the
client->server as a client error and an error when copying from the
server->client as a server error. This logic is incorrect as either side
could be the source of the broken connection.

Now, a wrapper is applied to the connection, and the errors returned by
the wrapper are used to properly account for which side broke the
connection.

Release note: None

### CODE REVIEW

**Comment by JeffSwenson** [comment]
This change resolves https://cockroachlabs.atlassian.net/browse/CC-5299.

**Review by jaylim-crl — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85031#-:-N7vKf0P8IJmvyAy5lVd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @JeffSwenson)

___
*[`pkg/ccl/sqlproxyccl/error_source.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85031#-N7vJsjs6juokH4LPN2k:-N7vJsjs6juokH4LPN2l:b-d1dz4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cefb0bc206d6cf37f8655c5c306091c34ff91c59/pkg/ccl/sqlproxyccl/error_source.go#L35)):*
> ```Go
> // errServerWrite indicates the error occured when attempting to write to the
> // sql server.
> var errServerWrite = errors.New("server connection error")
> ```

super nit: s/connection/write?
___
*[`pkg/ccl/sqlproxyccl/proxy_handler.go` line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85031#-N7vKXSA8bc_k76bS0M_:-N7vKXSA8bc_k76bS0Ma:bfvfnuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cefb0bc206d6cf37f8655c5c306091c34ff91c59/pkg/ccl/sqlproxyccl/proxy_handler.go#L420)):*
> ```Go
> 	// The TLS connection attempts to cast errors to a net.Err and will behave
> 	// incorrectly if handed a marked error.
> 	clientConn := &errorSourceConn{
> ```

Have we considered wrapping this before the call to open the tenant conn? That way, we could detect this issue during the auth phase as well.

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85031)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jaylim-crl)

___
*[`pkg/ccl/sqlproxyccl/proxy_handler.go` line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85031#-N7vKXSA8bc_k76bS0M_:-N89Q0mqD-eOLRYbLhT7:b7vmkec) ([raw file](https://github.com/cockroachdb/cockroach/blob/cefb0bc206d6cf37f8655c5c306091c34ff91c59/pkg/ccl/sqlproxyccl/proxy_handler.go#L420)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Have we considered wrapping this before the call to open the tenant conn? That way, we could detect this issue during the auth phase as well.
</blockquote></details>

We chatted about this off line. The auth method already correctly annotates which side of the connection broke. I do think the way error handling in the sqlproxy works is kind of funky and would eventually like to clean it up so things are more consistent.

**Pull request merged**
