### PR TITLE
utilccl: add enterprise licence checking

### PR DESCRIPTION
**Pull request by dt**
This adds a new `enterprise.licence` setting to manage a CCL cluster's license.

Attempts to use Enterprise features will return a license error if the cluster
does not have a currently valid license.

A license can be obtained from Cockroach Labs (means TBD) and contains some
identifying information, notably the cluster(s) to which it applies and an
expiration, encoded as a string.

Currently a license is applied via `SET CLUSTER SETTING`, which, via the standard validated setting patter, will validate that the supplied value is well-formed (i.e. that it actually is an encoded license). It will not however verify that it is currently valid for that particular cluster though. A future change that adds `SET LICENSE` and `SHOW LICENSE` sugar on top of the setting could provide this validation and hide the setting.

There's no attempt made to sign, encrypt or really even obfuscate how these
strings are encoded: given that the code is open for all to see, a user
intending to circumvent our license check has easier technical means to do so
already, so there's little point in making things harder here.

For now, the stopgap boolean setting is also still respected but it will be
removed after a transition period.

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Comment by danhhz** [comment]
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/ccl/utilccl/license.proto, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3XJ_WI9cGtDR-3Vj:-Kmh3XJ_WI9cGtDR-3Vk:by1ddfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license.proto#L19)):*
> ```protobuf
>         (gogoproto.customname) = "ClusterID",
>         (gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID"];
>     int64 valid_until_unix_sec = 2;
> ```

isn't there some fancy gogo annotation for this?

---

*[pkg/ccl/utilccl/license_check.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh23LC2bCv1Cxvasez:-Kmh23LC2bCv1Cxvasf-:b2gyaw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L28)):*
> ```Go
> 
> // LicensePrefix is a prefix on license strings to make them easily recognized.
> const LicensePrefix = "cl-0-"
> ```

the most nitty nit you've probably ever gotten: s/cl/crl/

---

*[pkg/ccl/utilccl/license_check.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh1rEACAFlN_YqSA3t:-Kmh1rEACAFlN_YqSA3u:bpot66b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L38)):*
> ```Go
> 
> var currentLicense = func() *atomic.Value {
> 	setting := settings.RegisterValidatedStringSetting(
> ```

this should be hidden from day 1. (I don't consider the `SET LICENSE` sugar optional)

---

*[pkg/ccl/utilccl/license_check.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2L5Z4UNBQDQStpbt:-Kmh2L5Z4UNBQDQStpbu:b-merk42) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L62)):*
> ```Go
> 	}
> 	if !strings.HasPrefix(s, LicensePrefix) {
> 		return nil, errors.New("invalid license string")
> ```

do we want to include the license string in these errors?

---

*[pkg/ccl/utilccl/license_check.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2llGxkY2IJamtqlu:-Kmh2llGxkY2IJamtqlv:b-xy37co) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L80)):*
> ```Go
> // enable it.
> func CheckEnterpriseEnabled(cluster uuid.UUID, feature string) error {
> 	// TODO(dt): delete this after a transition period.
> ```

define "after a transition period" more precisely please

---

*[pkg/ccl/utilccl/license_check.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh36u2zo0NiF17DkYR:-Kmh36u2zo0NiF17DkYS:b7tyje6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L103)):*
> ```Go
> 	return errors.Errorf(
> 		"use of %s requires an enterprise license. "+
> 			"see %s%s for details on how to enable enterprise features",
> ```

does this work?

---

*[pkg/ccl/utilccl/license_check_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3s3hO30cx70CxIpw:-Kmh3s3hO30cx70CxIpx:b-anzafk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L54)):*
> ```Go
> 		{License_Enterprise, clusterA, after, clusterA, wayAfter, "expired"},
> 
> 		{licType: -1, err: "requires an enterprise license"},
> ```

duplicate test case, here an below. intentional?

---

*[pkg/ccl/utilccl/license_check_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh6_B12GJPqD4yhHUx:-Kmh6_B12GJPqD4yhHUy:b-xc92y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L66)):*
> ```Go
> 				[]uuid.UUID{tc.grantedTo},
> 				tc.expiration.Unix(),
> 				License_Evaluation,
> ```

should be `licType` (and this fixes your test case above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Comment by dt** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/utilccl/license.proto, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3XJ_WI9cGtDR-3Vj:-KmhRZniiPmI39qIAXub:bbq9sp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license.proto#L19)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

isn't there some fancy gogo annotation for this?
</blockquote></details>

Don't think so: There's a google.protobuf.timestamp type, but its a whole struct with multiple ints for subsecond precision and IIRC has some issues has some tricky edge cases. This seemed simpler.

---

*[pkg/ccl/utilccl/license_check.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh23LC2bCv1Cxvasez:-Kmh6uBlw9a-Mf-XldjT:b-8flle3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L28)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the most nitty nit you've probably ever gotten: s/cl/crl/
</blockquote></details>

heh, I was actually going for "Cockroach License", not "CockRoach Labs" there... but /shrug.

---

*[pkg/ccl/utilccl/license_check.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh1rEACAFlN_YqSA3t:-KmhQeXl0kyT7dCQcFSy:bk05bdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L38)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this should be hidden from day 1. (I don't consider the `SET LICENSE` sugar optional)
</blockquote></details>

hm, I'm not entirely sure I agree about hiding it, from a general dislike of magic/non-obvious behavior, but will do if you feel strongly. 

---

*[pkg/ccl/utilccl/license_check.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2L5Z4UNBQDQStpbt:-Kmh79s1xrZJ_gtMf-hm:b-607oh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L62)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

do we want to include the license string in these errors?
</blockquote></details>

hm, do we? I'm not so sure we do.

---

*[pkg/ccl/utilccl/license_check.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2llGxkY2IJamtqlu:-KmhPj7OeFpsasAUt95A:b-ad9rwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L80)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

define "after a transition period" more precisely please
</blockquote></details>

Done: added "by 1.1".

My expectation is probably sooner, but I want to see it in practice on test clusters before I pin it down beyond that.

---

*[pkg/ccl/utilccl/license_check.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh36u2zo0NiF17DkYR:-KmhTC2rK8rx2-hZlp5V:bvmjebq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L103)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

The page doesn't do anything with it yet, but when we build something there, it will be able to, without asking them to go back to their cluster and find the ID (which you can't even do via SQL right now).

---

*[pkg/ccl/utilccl/license_check_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3s3hO30cx70CxIpw:-Kmh7MNVKzT9aD1mzqPv:bnm5v3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L54)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

duplicate test case, here an below. intentional?
</blockquote></details>

Yeah, I wanted to go back to unlicensed inbetween, but you could remove these without losing any coverage.

---

*[pkg/ccl/utilccl/license_check_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh6_B12GJPqD4yhHUx:-KmhQagIoGWccTb6Ck8K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L66)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should be `licType` (and this fixes your test case above)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Comment by danhhz** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/utilccl/license_check.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh23LC2bCv1Cxvasez:-KmhZy9ETO0I_y9EO-cx:b-88qaya) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L28)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

heh, I was actually going for "Cockroach License", not "CockRoach Labs" there... but /shrug.
</blockquote></details>

I realized what you were going for, I just like "crl" better. Someone *might* recognize "crdb" or "crl" with no context. They'd never recognize "cl"

---

*[pkg/ccl/utilccl/license_check.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh1rEACAFlN_YqSA3t:-KmhYyoHekz1NfXwkJ9F:b93l07f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L38)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

hm, I'm not entirely sure I agree about hiding it, from a general dislike of magic/non-obvious behavior, but will do if you feel strongly. 
</blockquote></details>

What magic/non-obvious behavior are you referring to?

---

*[pkg/ccl/utilccl/license_check.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2L5Z4UNBQDQStpbt:-KmhZ2-BHF-xZNL7id_r:bfvpe6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L62)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

hm, do we? I'm not so sure we do.
</blockquote></details>

I was thinking if something gets in a weird state and starts failing validations, it might be nice to know what string is failing the validation. Logging is probably more appropriate than erroring, tho

---

*[pkg/ccl/utilccl/license_check.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2llGxkY2IJamtqlu:-KmhZL3q72ddqR0V4459:b26u4gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L80)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done: added "by 1.1".

My expectation is probably sooner, but I want to see it in practice on test clusters before I pin it down beyond that.
</blockquote></details>

i'm totally happy with "before 1.1"

---

*[pkg/ccl/utilccl/license_check.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh36u2zo0NiF17DkYR:-KmhZhHJcS6wjqzsuQwe:b-wrdr24) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L103)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

The page doesn't do anything with it yet, but when we build something there, it will be able to, without asking them to go back to their cluster and find the ID (which you can't even do via SQL right now).
</blockquote></details>

I was referring to the "%s" that disappeared in the latest revision

---

*[pkg/ccl/utilccl/license_check_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3s3hO30cx70CxIpw:-KmhZnkMVi9XjCofRj4u:b-annmqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L54)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, I wanted to go back to unlicensed inbetween, but you could remove these without losing any coverage.
</blockquote></details>

seems reasonable. comment plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Comment by dt** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/utilccl/license_check.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh23LC2bCv1Cxvasez:-KmhcQFELdstT5IsmoNk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L28)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I realized what you were going for, I just like "crl" better. Someone *might* recognize "crdb" or "crl" with no context. They'd never recognize "cl"
</blockquote></details>

Done.

---

*[pkg/ccl/utilccl/license_check.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh1rEACAFlN_YqSA3t:-Kmh_YobSfRhqF7_MH46:bh7pqym) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L38)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

What magic/non-obvious behavior are you referring to?
</blockquote></details>

Since there's a setting that affects behavior, generally I'd rather it be visible, e.g. if I compared the output of `show settings`, it would be clear why it works in one place but not another. 

---

*[pkg/ccl/utilccl/license_check.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh2L5Z4UNBQDQStpbt:-Kmhbntn-H-lnU2kYvyc:b-59e946) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L62)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was thinking if something gets in a weird state and starts failing validations, it might be nice to know what string is failing the validation. Logging is probably more appropriate than erroring, tho
</blockquote></details>

that's probably true in general -- if a setting shows up via gossip that is invalid, it's probably interesting. added to the gossip reader.

---

*[pkg/ccl/utilccl/license_check_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh3s3hO30cx70CxIpw:-KmhaYmVRG4doauEq_MY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check_test.go#L54)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

seems reasonable. comment plz
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/utilccl/license_check.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-Kmh1rEACAFlN_YqSA3t:-Kmhcv8N7kTJ2F1xPoEP:bihbk6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a66c184a586ba73f2bc4942b6d17210b0b2c58c9/pkg/ccl/utilccl/license_check.go#L38)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Since there's a setting that affects behavior, generally I'd rather it be visible, e.g. if I compared the output of `show settings`, it would be clear why it works in one place but not another. 
</blockquote></details>

Just feels like having a setting is inviting people to try setting it directly, which we don't want here (plus the fact that it's a setting is an implementation detail, it just as easily could be a new system table). Anyway, if you feel strongly go ahead and merge as-is

---

*[pkg/server/settingsworker.go, line 102 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-KmhdIZdUlCrhdOeGUik:-KmhdIZeNF2r3VFlciuf:b5387eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6c25b10be81731e41863ad6900cdd37e567e81c/pkg/server/settingsworker.go#L102)):*
> ```Go
> 
> 		if err := u.Set(k, v, t); err != nil {
> 			log.Warningf(ctx, "setting %q to %q failed: %#v", k, v, err)
> ```

don't you want %+v for the err? https://godoc.org/github.com/pkg/errors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532#-:-KmhdpgvJeepO2DxA77f:bnfp4nl)*

**Comment by dt** [comment]
I went ahead and Hid it. RFAL.

**Comment by danhhz** [comment]
Reviewed 4 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16532)*

**Pull request merged**
