### PR TITLE
tenantcapabilitieswatcher: make the watcher react faster

### PR DESCRIPTION
**Pull request by knz**
Needed for #111637. 
Epic: CRDB-26691.

Prior to this patch, the tenant info watcher would only react to
changes to `system.tenants` upon rangefeed cache flushes, which could
be (in default config) up to 3 seconds after the change is committed.

This commit accelerates the behavior by processing updates as soon as
the change is observed in the rangefeed.

This new behavior is similar to the way that cluster settings changes
are effected immediately in the settings watcher (pkg/settingswatcher).

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
I need to double-check, but I believe that the semantics of the translateEvent callback is that you are subject to the redelivery of duplicates.  So I think we need to store the event's timestamp in our cache and skip updates from any older events to prevent regressing the state of a given tenant.

**Comment by knz** [comment]
good point. let me pick that up.

**Review by stevendanna — COMMENTED** [review]
Overall this looks good to me.  One consequence of doing this is that changefeed restarts will cause >1 update for those watching for updates such as the server orchestrator.  But as we discussed, those systems should be able to deal with many such updates per second.

A potential follow-up is that we added some code that restarts the capability watcher to avoid waiting out the 3 seconds (see TestingRestart in this file).  With this change, I think that should largely be unnecessary.

> Reviewed 1 of 1 files at r1, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112094#-:-NgPafcx7BHJQ5_K-zTc:b-3ehh8t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/rangefeed_errors` line 106 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/112094#-NgPbioE-ayncGlfhUGP:-NgPbioE-ayncGlfhUGQ:by0a0uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/76b193036c5be0a011b0a5cbfd1ad0bfa70655ad/pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/rangefeed_errors#L106)):*
> ```
> get-capabilities ten=10
> ----
> ten=10 name=foo state=add service=shared cap={can_admin_unsplit:true}
> ```

Is this test telling us that we won't subsequently update our cache on the tenant deletion event if it happens during an error restart? Is that something we need to handle?

**Comment by stevendanna** [comment]
Merged as part of https://github.com/cockroachdb/cockroach/pull/114719

**Pull request closed without merging**
