### PR TITLE
opt: modify PushAggDistinctIntoScalarGroupBy to handle GroupBy

### PR DESCRIPTION
**Pull request by DrewKimball**
This patch modifies the PushAggDistinctIntoScalarGroupBy rule to
match GroupBy operators.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, can you also add before/after TPCH numbers for this change to make sure we didn't regress.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50379#-:-MA8-Dwh-iUENG9PVIDS:b-duycq9)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by DrewKimball** [comment]
TPC-H Q16:
Master Avg (ms) | Rule Avg (ms) | Percent Change | Delta (ms) | Master Stdev  (ms) | Rule Stdev (ms)
-- | -- | -- | -- | -- | --
533.6612 | 553.0442 | 3.632079679 | 19.383 | 6.1881074 | 6.075159315


Looks like we did regress a bit.  That said, the change isn't large, and we improve on a somewhat similar query (with no index to take advantage of):
```
CREATE TABLE xyz (x INT PRIMARY KEY, y INT, z INT);
INSERT INTO xyz (SELECT t, t%10, t%13 FROM generate_series(1,100000) f(t));
SELECT count(DISTINCT y) FROM xyz GROUP BY z;
```


Master Avg (ms) | Rule Avg (ms) | Percent Change | Delta (ms) | Master Stdev (ms) | Rule Stdev (ms) 
-- | -- | -- | -- | -- | --
64.5692 | 55.0806 | -14.69524169 | -9.4886 | 1.253866699 | 1.323333216

I thought the difference between these first two cases might be because the TPC-H query is grouping on multiple columns, but this example seems to point to that not being the case:
```
CREATE TABLE xyz (x INT PRIMARY KEY, y INT, z1 INT, z2 INT, z3 INT, z4 INT);
INSERT INTO xyz (SELECT t, t%10, t%13, t%11, t%3, t%2 FROM generate_series(1, 100000) f(t));
SELECT count(DISTINCT y) FROM xyz GROUP BY z1, z2, z3, z4;
```

Master Avg (ms) | Rule Avg (ms) | Percent Change | Delta (ms) | Master Stdev (ms) | Rule Stdev (ms) 
-- | -- | -- | -- | -- | --
92.6734 | 54.025 | -41.70387619 | -38.6484 | 0.9841599464 | 2.918832301

I'd appreciate any ideas on why the TPC-H query gets slower but the other two don't.
All averages were taken over five consecutive runs.

**Review by RaduBerinde — APPROVED** [review]
We could check the `EXPLAIN (VEC)` (and maybe `EXPLAIN ANALYZE`) for the query before and after. There is probably some kind of vectorized planning difference between the two plans.

Transformation and code :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50379#-:-MADCI2wEyKE_JdF1Nx5:bzgpwmf)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm: 

Here's a gist you can use to update the stats quality test that changed: https://gist.github.com/rytaft/89913987c53688d53455b9da98eb90d3

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50379#-:-MASfgpYAaNWyH4es3MX:b2di2k2)* status: :shipit: complete! 3 of 0 LGTMs obtained

**Comment by DrewKimball** [comment]
> We could check the `EXPLAIN (VEC)` (and maybe `EXPLAIN ANALYZE`) for the query before and after. There is probably some kind of vectorized planning difference between the two plans.

It looks like the only difference is the change the rule made. I guess (at least in this case) it's slightly slower without having some index to take advantage of. Do you think this is ok?

**Review by RaduBerinde — APPROVED** [review]
Yeah, it's a pretty small difference.

I guess the difference is that instead of maintaining a single count per key, we maintain entire rows and only after that we count them. So for one, more memory is used.

Can't really explain why those other examples are so much improved though. I tried your first example in a `cockroach demo` with and without the PR and didn't see a difference (saw 78-80ms with the PR, ~72ms without).

**Comment by DrewKimball** [comment]
>I tried your first example in a cockroach demo with and without the PR and didn't see a difference (saw 78-80ms with the PR, ~72ms without).

Huh, maybe that was just some vectorized shenanigans then.

**Comment by yuzefovich** [comment]
> Huh, maybe that was just some vectorized shenanigans then.

Vectorized engine is used only if we estimate that we will scan at least `vectorize_row_count_threshold` number of rows (1000 by default) from at least one table, and if that threshold is not met or if the statistics on the tables in question are not present (meaning that we don't have an estimate), then the vectorized engine is not used.

I'm guessing if you quickly fire up a demo shell, create a table, and then run the query, the stats might not be there yet, so we will use row engine. In order to check which engine is used, run "vanilla" `EXPLAIN` (plan). `EXPLAIN (VEC)`, however, gives you the tree of vectorized operators as if the vectorized engine is used (which might not be the case).

**Pull request merged**
