### PR TITLE
roachtest: delete synctest

### LINKED ISSUE #48603: roachtest: synctest failed on Pebble
Seen while running roachtests on #48145 

```
./nemesis on: Restricting random IO restricted to specific syscalls and 1% error probability
F200508 19:38:32.692326 5518 vendor/github.com/cockroachdb/pebble/version_set.go:413  MANIFEST flush failed: write /mnt/data1/cockroach/faulty/0/MANIFEST-000001: no message of desired type
goroutine 5518 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7756e01, 0xed647ac38, 0x0, 0x855980)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x7753800, 0xc000000004, 0x6c9f77b, 0x33, 0x19d, 0xc00004b730, 0x66)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:212 +0xbcd
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4d274c0, 0xc000ab05a0, 0x4, 0x3, 0x44487ba, 0x19, 0xc000267cf0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4d274c0, 0xc000ab05a0, 0x2, 0xc000000004, 0x44487ba, 0x19, 0xc000267cf0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:166
github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:372
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*versionSet).logAndApply.func1(0xc0001c4a88, 0xc0007f6aa0, 0xc00092a2a0, 0xc000d75b78, 0xc000d75b58, 0x0, 0xe49, 0xe4d, 0x156c, 0x4d65180, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/version_set.go:413 +0x387
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*versionSet).logAndApply(0xc0001c4a88, 0x156c, 0xc0007f6aa0, 0xc0008065d0, 0x4d65180, 0xc000010488, 0xc000d75d60, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/version_set.go:436 +0x1ba
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).flush1(0xc0001c4900, 0x77a5d50, 0x77a5d50)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:986 +0x698
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).flush.func1(0x4d274c0, 0xc000806570)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:896 +0x88
runtime/pprof.Do(0x4d274c0, 0xc000806570, 0xc000289880, 0x1, 0x1, 0xc0006effb8)
        /usr/local/go/src/runtime/pprof/runtime.go:37 +0xf8
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).flush(0xc0001c4900)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:893 +0x89
created by github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble.(*DB).maybeScheduleFlush
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/compaction.go:889 +0x177
```

The `no message of desired type` is a strange error message. 

Given the error injection that `synctest` performs, a crash here does not seem unexpected. Hmm, this is not running `cockroach` normally, but running `cockroach debug synctest`. Perhaps that isn't compatible with Pebble. I'm not seeing any facility to catch log fatals. 

Jira issue: CRDB-4311

### PR DESCRIPTION
**Pull request by sumeerbhola**
This test has been skipped since May 2020, because Pebble code is written to crash on an error when writing to the MANIFEST and the WAL, since it is not viable to continue. Additionally, there were problems with hangs due to charybdefs returning EAGAIN (which have since been fixed).

We are deleting this now since:
- The purpose of this test is to test that Pebble does not lose data due to filesystem errors. It does so in a cruder manner than Pebble's strict MemFS based testing (which came later). Given the existence of the latter, there is no good reason to retain this test.

- Working around charybdefs flakiness (see #102492), and Pebble's failstop-on-error behavior is not worth the initial and ongoing maintenance effort.

Epic: none

Fixes: #48603

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106917#-:-N_ZyRFhCZ4nGadl2-R7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @renatolabs, and @smg260)

**Review by itsbilal — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106917#-:-N__axRQ47pj0a4GWiaP:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @renatolabs, and @smg260)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
flaky tests

**Comment by sumeerbhola** [comment]
bors r=RaduBerinde,itsbilal

**Pull request merged**
