### PR TITLE
opt: Fix Projections inlining bug

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR fixes a bug, and adds some helper structs to make it easier to construct the needed lists and Projections operators.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/norm/inline.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChto2Q9VWhXX4Ouatb:-LChto2R398saYNykXAP:b-jwhurv) ([raw file](https://github.com/cockroachdb/cockroach/blob/99201a81e196bfaf6c9c6a8c9af67f156d50efbf/pkg/sql/opt/norm/inline.go#L34)):*
> ```Go
> 	// When a column reference is found, add it to the refs set. If the set
> 	// already contains a reference to that column, then there is a duplicate.
> 	var countRefs func(group memo.GroupID) bool
> ```

[nit] add a description of what the function returns (since the name isn't great, its not actually counting)

---

*[pkg/sql/opt/norm/inline.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChu1ejBIcL5jFB6agC:-LChu1ejBIcL5jFB6agD:b-dff232) ([raw file](https://github.com/cockroachdb/cockroach/blob/99201a81e196bfaf6c9c6a8c9af67f156d50efbf/pkg/sql/opt/norm/inline.go#L40)):*
> ```Go
> 			// Don't try to count references within correlated subqueries.
> 			// Uncorrelated subqueries never have references.
> 			return !f.outerCols(group).Empty()
> ```

We are returning true if the subquery has any outer columns (not necessarily intersecting `refs`), can you explain this more in the comment? The description of the outer function might need to be relaxed (to add an "or has correlated subqueries")?

---

*[pkg/sql/opt/norm/list_builder.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChp2rR5cJ5P1QU3p82:-LChp2rR5cJ5P1QU3p83:b-8iylai) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L33)):*
> ```Go
> // to recurse on factory construction methods without danger of trying to reuse
> // a scratch slice that's already in use further up the stack.
> type listBuilder struct {
> ```

Should be exported? Maybe`optbuilder` should be able to use it too.

If we change the Factory to take well-typed arguments instead of IDs, would we still pass `ListID`s, or maybe we would pass a `listBuilder`?

---

*[pkg/sql/opt/norm/list_builder.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChq_Cb-SY4Xxja6GMT:-LChq_Cb-SY4Xxja6GMU:b-6xnwky) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L61)):*
> ```Go
> 	listID := b.f.InternList(b.items)
> 
> 	// Restore the factory scratch list.
> ```

[nit] We're not necessarily "restoring", the scratchItems could have been taken by a higher-level `listBuilder`, and this is setting it to a new slice (until that higher-level `listBuilder` calls this function).

---

*[pkg/sql/opt/norm/list_builder.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChqB2K8j18i_2FNu9a:-LChqB2K8j18i_2FNu9b:bx80w7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L62)):*
> ```Go
> 
> 	// Restore the factory scratch list.
> 	b.f.scratchItems = b.items
> ```

This seems fragile - if a function bails on creating the list (e.g. hits some error), we will lose the scratch slice. Maybe this is an argument for not exporting `listBuilder` since the norm code doesn't error out. On the other hand, if we hit an error, we likely don't care about the factory anymore so maybe it doesn't matter.

---

*[pkg/sql/opt/norm/projections_builder.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChr6dd2tJoD7O3LAqO:-LChr6dd2tJoD7O3LAqP:bwcgcw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L25)):*
> ```Go
> // Projections operators. It:
> //
> //  1. Allows the Projections operator to be built incrementally
> ```

[supernit] period at the end

---

*[pkg/sql/opt/norm/projections_builder.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChsAVT8dcHuXGWzheu:-LChsAVT8dcHuXGWzhev:bxwa0kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L56)):*
> ```Go
> 	// synthesized is the list of projections that are synthesized from input
> 	// columns or constant values, rather than being passed through unchanged.
> 	synthesized []memo.GroupID
> ```

this could be a `listBuilder`, we would be modifying `scratchItems` in one place

---

*[pkg/sql/opt/norm/projections_builder.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChsyHt4FtlQ7imxAQs:-LChsyHt4FtlQ7imxAQt:b-esu76y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L90)):*
> ```Go
> 	for _, synthID := range b.synthesizedCols {
> 		if synthID == colID {
> 			return
> ```

Should we assert that `elem` is the same group? It seems wrong if we try to add two different synthesized columns with the same ID

---

*[pkg/sql/opt/norm/projections_builder.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChrpyaEklqGHXQtgk_:-LChrpyaEklqGHXQtgka:b7mo7l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L151)):*
> ```Go
> }
> 
> func (b *projectionsBuilder) ensurePassthrough() {
> ```

This ensures something different than `ensureSlices`, maybe rename to `mutablePassthrough`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-:-LChvoPy-bcsv2OBk6NN:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 6 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/projections_builder.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LCjO6pd9ySlqaapi1TW:-LCjO6pd9ySlqaapi1TX:b7tx1ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L46)):*
> ```Go
> 	f *Factory
> 
> 	// passthrough is the set of columns that are passed through unchanged from
> ```

passthrough -> passthroughCols

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-:-LCjTOhFB1Nqv987lkg6:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/inline.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChto2Q9VWhXX4Ouatb:-LCjcv_o8lOrRmd2Ww1U:bs7wun9) ([raw file](https://github.com/cockroachdb/cockroach/blob/99201a81e196bfaf6c9c6a8c9af67f156d50efbf/pkg/sql/opt/norm/inline.go#L34)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a description of what the function returns (since the name isn't great, its not actually counting)
</blockquote></details>

Done.,

---

*[pkg/sql/opt/norm/inline.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChu1ejBIcL5jFB6agC:-LCjdS7p84TAX8vpj3Eg:b-4bijjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/99201a81e196bfaf6c9c6a8c9af67f156d50efbf/pkg/sql/opt/norm/inline.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are returning true if the subquery has any outer columns (not necessarily intersecting `refs`), can you explain this more in the comment? The description of the outer function might need to be relaxed (to add an "or has correlated subqueries")?
</blockquote></details>

I added comment to outer function.

---

*[pkg/sql/opt/norm/list_builder.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChp2rR5cJ5P1QU3p82:-LCjdYJh2PcIQDAQU5vu:b-db3aj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should be exported? Maybe`optbuilder` should be able to use it too.

If we change the Factory to take well-typed arguments instead of IDs, would we still pass `ListID`s, or maybe we would pass a `listBuilder`?
</blockquote></details>

If we find it useful outside the package, we can definitely export. That seems like a separate change, though. I think we do need to do a performance pass on optbuilder, and this might be useful once we do that.

Good question regarding the factory changes. I hadn't considered that aspect. I think we'd probably need a `list() []memo.GroupID` method, and then a separate `close()` method to return the scratch slice. Maybe we use a `defer` pattern?

---

*[pkg/sql/opt/norm/list_builder.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChq_Cb-SY4Xxja6GMT:-LCjexAREeMThWrbo2Bv:b-58crlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L61)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We're not necessarily "restoring", the scratchItems could have been taken by a higher-level `listBuilder`, and this is setting it to a new slice (until that higher-level `listBuilder` calls this function).
</blockquote></details>

Yeah, I was just using common-case terminology. I changed the comment.

---

*[pkg/sql/opt/norm/list_builder.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChqB2K8j18i_2FNu9a:-LCjfCiK41uSvDPHbtK-:bg0shaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems fragile - if a function bails on creating the list (e.g. hits some error), we will lose the scratch slice. Maybe this is an argument for not exporting `listBuilder` since the norm code doesn't error out. On the other hand, if we hit an error, we likely don't care about the factory anymore so maybe it doesn't matter.
</blockquote></details>

This just needs to be best-effort, not guaranteed. If the slice isn't returned, we just allocate a new one, which is not a big deal, as long as we handle the common cases.

---

*[pkg/sql/opt/norm/projections_builder.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChr6dd2tJoD7O3LAqO:-LCjfUfW9Pra3tn_4z2-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[supernit] period at the end
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/projections_builder.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LCjO6pd9ySlqaapi1TW:-LCjfXkc-fpsvf6hGCaW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L46)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

passthrough -> passthroughCols
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/projections_builder.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChsAVT8dcHuXGWzheu:-LCjghOgE-lNjEY_Ok3B:b-k6byex) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this could be a `listBuilder`, we would be modifying `scratchItems` in one place
</blockquote></details>

I did consider that. The trouble is that it makes the initialization case awkward, because I have to initialize the `f` field in that nested list builder. If I try to do that lazily in `ensureSlices`, then it won't get initialized in the empty list case, and then I've got to handle that special case in `buildProjections`. In the end, there's just as much code, and it's harder to understand.

---

*[pkg/sql/opt/norm/projections_builder.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChsyHt4FtlQ7imxAQs:-LCjhF8i97_BV-Q7qzWS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should we assert that `elem` is the same group? It seems wrong if we try to add two different synthesized columns with the same ID
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/projections_builder.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChrpyaEklqGHXQtgk_:-LCjhGDj7FjK42ebT0YK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bd95363053ebb41dddd99f32e46c7671db81ec3/pkg/sql/opt/norm/projections_builder.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This ensures something different than `ensureSlices`, maybe rename to `mutablePassthrough`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25602)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/norm/list_builder.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-LChp2rR5cJ5P1QU3p82:-LCjkgt_8DZu0oQWObzu:b-4d96k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b1d11c1636c22c71f45741b50a37965fcc6ca3b/pkg/sql/opt/norm/list_builder.go#L33)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If we find it useful outside the package, we can definitely export. That seems like a separate change, though. I think we do need to do a performance pass on optbuilder, and this might be useful once we do that.

Good question regarding the factory changes. I hadn't considered that aspect. I think we'd probably need a `list() []memo.GroupID` method, and then a separate `close()` method to return the scratch slice. Maybe we use a `defer` pattern?
</blockquote></details>

Yeah, I thought about `defer`, but I think it's slow enough to where it's not worth saving a list allocation (https://github.com/golang/go/issues/14939).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25602#-:-LCjm2DbA5b-exW4HzCf:bnfp4nl)*

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25602)*

**Pull request merged**
