### PR TITLE
storeliveness: add proto definitions and service

### LINKED ISSUE #125059: storeliveness: add service and state protobufs
Create a single message to handle both heartbeats and heartbeat responses, as well as a batched version of it. Add proto definitions for all persisted data (`RequesterMeta`, `SupporterMeta`, `SupportState`). 

Add the streaming `StoreLiveness` GRPC service:
```
service StoreLiveness {
  rpc Stream (stream MessageBatch) returns (Empty) {}
}
```

Jira issue: CRDB-39247

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by miraradeva**
This commit adds the proto definitions for the Store Liveness messages and streaming RPC service, as well as the proto definitions for all metadata that needs to be persisted for the correctness of Store Liveness across restarts.

Fixes: #125059

Release note: None

### CODE REVIEW

**Comment by miraradeva** [comment]
Created https://github.com/cockroachdb/cockroach/issues/126198 to track the more general documentation.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126194)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KGXgg5pjp7Nav6cW3:-O0KGXgg5pjp7Nav6cW4:b-sgvr07) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L40)):*
> ```proto
> message Message {
>   MessageType type = 1;
>   // from is the identity of the store providing support.
> ```

nit: To match how we usually handle protobufs, these comments should be capitalized and camel case so they match the resulting Go code. When the proto code gen is run, the fields will all be exported.
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KGo8z3Tc_nLTcaQcQ:-O0KGo8z3Tc_nLTcaQcR:btsh77h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L48)):*
> ```proto
>   // expiration is the timestamp of the requested/provided support for the
>   // given epoch; it is drawn from the support requester's clock.
>   util.hlc.Timestamp expiration = 5 [(gogoproto.nullable) = false];
> ```

I'm a little surprised that we got rid of `ack`, but don't have strong feelings. The explicitness of an `ack` field was nice and afforded useful terminology, but also left room for inconsistent message states.

Do we need to say more on `epoch` and `expiration` without the explicit `ack` field?
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KHTxR0Hns_arYfFCC:-O0KHTxR0Hns_arYfFCD:b71smva) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L76)):*
> By incrementing its epoch a store promises to stop using support for the previous epoch.

Is this part correct? I thought a store could increment its epoch in response to a nack from a remote store, but keep heartbeating at an earlier epoch for other stores.
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KIzzuB9Ph_ntNACNu:-O0KIzzuB9Ph_ntNACNv:b-mfgw2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L78)):*
> ```proto
>   // a store promises to stop using support for the previous epoch. To
>   // successfully keep this promise across restarts, the store's current epoch
>   // needs to be persisted.
> ```

Do we want to say something about how a store will not request support for an epoch until that epoch is reflected durably in `current_epoch`?

In some ways, that parallels the `max_requested` timestamp, which could motivate renaming this to `max_epoch`. I don't have a strong preference. Maybe just go with what feels like a more natural name once we resolve the previous comment thread ("I thought a store ...").
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KI-ve2pQ_SOSod4KE:-O0KI-ve2pQ_SOSod4KF:b-5dxnkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L80)):*
> another store is persisted

Is this sentence missing a word?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126194)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KGo8z3Tc_nLTcaQcQ:-O0KrLSz-4OxywsJybP4:b-r9zc66) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little surprised that we got rid of `ack`, but don't have strong feelings. The explicitness of an `ack` field was nice and afforded useful terminology, but also left room for inconsistent message states.

Do we need to say more on `epoch` and `expiration` without the explicit `ack` field?
</blockquote></details>

I looked through the code and I think it's possible to set it up so that `ack = true if and only if expiration != 0`. Both in terms of generating `ack` as part of `handleHeartbeat` and processing `ack` in `handleHeartbeatResp`. Also, we already do this expiration timestamp comparison in `SupportFor` and `SupportFrom`. Maybe we can extract a simple function that does this comparison. So I figured `ack` itself is not all that useful. 

But I was planning to run the TLA+ spec to confirm. We can also add it in later when implementing the algorithm if it looks useful.
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KHTxR0Hns_arYfFCC:-O0Kt2Q_8WSk0Z2SAwG3:b4gikq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> By incrementing its epoch a store promises to stop using support for the previous epoch.

Is this part correct? I thought a store could increment its epoch in response to a nack from a remote store, but keep heartbeating at an earlier epoch for other stores.
</blockquote></details>

No, this is not correct. I meant to say this for a fixed supporter-supportee pair, not in general for a supportee. I rephrased it but I'm still not super happy with the wording. 
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0KIzzuB9Ph_ntNACNu:-O0KtNzI8EsVOYaXCv2U:b7h6gvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5a243dfe5113aa131c7388c939f7040d05f7b3/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to say something about how a store will not request support for an epoch until that epoch is reflected durably in `current_epoch`?

In some ways, that parallels the `max_requested` timestamp, which could motivate renaming this to `max_epoch`. I don't have a strong preference. Maybe just go with what feels like a more natural name once we resolve the previous comment thread ("I thought a store ...").
</blockquote></details>

I like max_epoch.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-:-O0LeyZ_BEYaFnKZWYEu:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 5 of 5 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-:-O0MCsoTEQVtKms_mJ8q:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.go` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0M9D7W2z0MMGYS0w7V:-O0M9D7W2z0MMGYS0w7W:b25vf2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/35242bd046ac506a2aae33224e130002ed8079c2/pkg/kv/kvserver/storeliveness/storelivenesspb/service.go#L14)):*
> ```Go
> 
> // Epoch is an epoch in the Store Liveness fabric, referencing an uninterrupted
> // period of support from one store to another.
> ```

nit: consider adding a sentence which says that stores can unilaterally increment epochs.
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0M8iAI1ifBU8mseF_3:-O0M8iAI1ifBU8mseF_4:bmerw18) ([raw file](https://github.com/cockroachdb/cockroach/blob/35242bd046ac506a2aae33224e130002ed8079c2/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L48)):*
> ```proto
>   // Expiration is the timestamp of the requested/provided support for the
>   // given epoch; it is drawn from the support requester's clock.
>   // An empty Expiration implies that support for the epoch is not provided.
> ```

nit: here, and elsewhere, could we add a new line between paragraphs?
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0M8njp8hu5XMVn1CfM:-O0M8njp8hu5XMVn1CfN:b-yxo6e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/35242bd046ac506a2aae33224e130002ed8079c2/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L85)):*
> ```proto
>   // MaxRequested is the maximum timestamp at which support was requested by
>   // another store. It is persisted to achieve two goals:
>   // 1. Ensures that the store's disk is not stalled before requesting support.
> ```

nit: could we add a new line about this as well
___
*[`pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto` line 108 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126194#-O0M9m_9DkE5WwLNPbk_:-O0M9m_9DkE5WwLNPbka:bhsve0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/35242bd046ac506a2aae33224e130002ed8079c2/pkg/kv/kvserver/storeliveness/storelivenesspb/service.proto#L108)):*
> ```proto
>   // usually assumed to be monotonically increasing even across restarts but
>   // Store Liveness remains correct without this assumption.
>   // Upon restart, a store forwards its clock to MaxWithdrawn.
> ```

nit: "a store must"

**Comment by miraradeva** [comment]
bors r=nvanbenschoten,arulajmani

**Pull request merged**
