### PR TITLE
roachpb: use a slice for Transaction.ObservedTimestamps

### LINKED ISSUE #13442: roachpb: reduce memory allocations for Transaction.ObservedTimestamps
`Transaction.ObservedTimestamps` is a map from node ID to the highest observed timestamp for that node and is used to avoid uncertainty related restarts. This map is copied whenever we clone a transaction, which is unfortunately several times during the lifetime of a request. And those copies involve 3 allocations for the map and the values (I'm not quite sure why the map internals result in 3 allocations, but the profiler doesn't lie). The allocations for the `Transaction.ObservedTimestamps` map account for 4% of the total allocations in Cockroach under a write-only workload I profiled.

It looks straightforward to transform the type from `map[NodeID]hlc.Timestamp` to `[]struct{NodeID,hlc.Timestamp}` and to keep the slice sorted for quick lookup. 

A more radical change would be to replace `ObservedTimestamp` with a 1 element entry which is the observed timestamp of the node we're sending the request to. `Transaction.GetObservedTimestamp` is only called from the store executing a request and from `TxnCoordSender`. The latter could maintain a full map of node to observed timestamp while the store only needs to know the observed timestamp for the node it is running on.

### PR DESCRIPTION
**Pull request by petermattis**
Change the type of Transaction.ObservedTimestamps from
map[nodeID]Timestamp to []ObservedTimestamp. Per
https://developers.google.com/protocol-buffers/docs/proto3#maps, this is
a backwards compatible change, though TestBelowRaftProtos needed
adjustment because the output of Transaction.NewPopulatedTransaction
changed (the generated populate function creates maps that [0,10]
elements in size and slices that are [0,5] elements).

Using a slice of observed timestamps instead of a map reduces the map
allocations and assignments in a write-only workload from 8.64% of total
allocations to 4.02%.

Fixes #13442

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13649)

### CODE REVIEW

**Comment by petermattis** [comment]
Btw, I investigated adding `roachpb.BatchRequest.observed_timestamp` and while that would have feasible, we also return the observed timestamp at the executing node in `Transaction.observed_timestamps`. Reworking all of this in a backward compatible way looked difficult to impossible. This change gets us nearly all of the benefit with much less pain.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/roachpb/data.go, line 939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-KdDcx6S_zhOr8dOjWMt:-KdDcx6TXGVTfS9LQkvC:buazm8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda0a5e0ebc6e57d81fb59609df16522e6b9a98/pkg/roachpb/data.go#L939)):*
> ```Go
> // can be lowered to the returned timestamp when reading from nodeID.
> func (t Transaction) GetObservedTimestamp(nodeID NodeID) (hlc.Timestamp, bool) {
> 	s := (observedTimestampSlice)(t.ObservedTimestamps)
> ```

Remove the first set of parens (unless I'm misreading this).

---

*[pkg/roachpb/data.proto, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-KdDdGdRQP224fAtlMAV:-KdDdGdSEDCHy9nqnpFQ:bguyboy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda0a5e0ebc6e57d81fb59609df16522e6b9a98/pkg/roachpb/data.proto#L278)):*
> ```protobuf
>   // avoiding) uncertainty restarts.
>   //
>   // The list of observed timestamps is kept sorted by NodeID. Use
> ```

Existing transactions won't be in sorted order, so this needs a stop-the-world upgrade (should be fine as it'll ship with the same release as spencer's change which is also stop-the-world)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-:-KdDdV0H2deyqoW7qsaZ:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/roachpb/data.go, line 939 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-KdDcx6S_zhOr8dOjWMt:-KdDixEj_Io3UnJT2wO9:b-ifjhkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda0a5e0ebc6e57d81fb59609df16522e6b9a98/pkg/roachpb/data.go#L939)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove the first set of parens (unless I'm misreading this).
</blockquote></details>

Done. I've been looking at too much C++ lately

---

*[pkg/roachpb/data.proto, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-KdDdGdRQP224fAtlMAV:-KdDjB2EW3ga7q-19lmq:b-3geecj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda0a5e0ebc6e57d81fb59609df16522e6b9a98/pkg/roachpb/data.proto#L278)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Existing transactions won't be in sorted order, so this needs a stop-the-world upgrade (should be fine as it'll ship with the same release as spencer's change which is also stop-the-world)
</blockquote></details>

Protobuf maps are marshalled with their keys in sorted order. Not sure if this is a `gogoproto` thing. Here is a snippet from the old `Transaction.MarshalTo`:

```
		keysForObservedTimestamps := make([]int32, 0, len(m.ObservedTimestamps))
		for k := range m.ObservedTimestamps {
			keysForObservedTimestamps = append(keysForObservedTimestamps, int32(k))
		}
		github_com_gogo_protobuf_sortkeys.Int32s(keysForObservedTimestamps)
		for _, k := range keysForObservedTimestamps {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649)*

**Comment by petermattis** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/roachpb/data.proto, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649#-KdDdGdRQP224fAtlMAV:-KdDjhpuzjy9UH06ToZ3:bs9dg5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda0a5e0ebc6e57d81fb59609df16522e6b9a98/pkg/roachpb/data.proto#L278)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Protobuf maps are marshalled with their keys in sorted order. Not sure if this is a `gogoproto` thing. Here is a snippet from the old `Transaction.MarshalTo`:

```
		keysForObservedTimestamps := make([]int32, 0, len(m.ObservedTimestamps))
		for k := range m.ObservedTimestamps {
			keysForObservedTimestamps = append(keysForObservedTimestamps, int32(k))
		}
		github_com_gogo_protobuf_sortkeys.Int32s(keysForObservedTimestamps)
		for _, k := range keysForObservedTimestamps {
```
</blockquote></details>

This is also why `TestRaftBelowProtos` is deterministic. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13649)*

**Pull request merged**
