### PR TITLE
storage/engine: add timeseries merge read benchmark

### PR DESCRIPTION
**Pull request by ajkr**
Added it for both RocksDB and Pebble.

Release note: None

### CODE REVIEW

**Comment by ajkr** [comment]
Here are some results running on RocksDB. I'll share the Pebble comparison after optimizing it.

```
name                                                            time/op
MVCCGetMergedTimeSeries_RocksDB/numKeys=1/mergesPerKey=1-6      1.38µs ±10%
MVCCGetMergedTimeSeries_RocksDB/numKeys=1/mergesPerKey=16-6     12.9µs ±16%
MVCCGetMergedTimeSeries_RocksDB/numKeys=1/mergesPerKey=256-6    1.70ms ± 6%
MVCCGetMergedTimeSeries_RocksDB/numKeys=16/mergesPerKey=1-6     1.46µs ± 3%
MVCCGetMergedTimeSeries_RocksDB/numKeys=16/mergesPerKey=16-6    12.9µs ± 3%
MVCCGetMergedTimeSeries_RocksDB/numKeys=16/mergesPerKey=256-6   1.79ms ± 1%
MVCCGetMergedTimeSeries_RocksDB/numKeys=256/mergesPerKey=1-6    1.54µs ± 4%
MVCCGetMergedTimeSeries_RocksDB/numKeys=256/mergesPerKey=16-6   13.0µs ± 6%
MVCCGetMergedTimeSeries_RocksDB/numKeys=256/mergesPerKey=256-6  1.66ms ± 2%
```

**Review by petermattis — APPROVED** [review]
:lgtm: though I'm eager to see the Pebble numbers even in advance of optimizing. I'd like to see how bad this initial implementation is and how much the optimization helps.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41838#-:-LrqAQtt8mHzk7tbmMyt:buetu42)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/engine/bench_test.go, line 608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41838#-Lrq9wIq2DhnSlSGUEHT:-Lrq9wIq2DhnSlSGUEHU:b5kaikz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d644da7b5f182419481570fa5ac0e29d192b7180/pkg/storage/engine/bench_test.go#L608)):*
> ```Go
> 	b.ResetTimer()
> 	// Use parallelism if specified when test is run.
> 	b.RunParallel(func(pb *testing.PB) {
> ```

For what this test is measuring, I'd leave out the parallelism and just do `for i := 0; i < b.N; i++ {`. We're mainly looking to see the performance of the merge operator. While there is some interesting bit of how it works concurrently, I think the parallelism here will only obscure the single-threaded performance.

**Review by ajkr — COMMENTED** [review]
Old is RocksDB, new is Pebble.

```
name                                                    old time/op  new time/op  delta
MVCCGetMergedTimeSeries/numKeys=1/mergesPerKey=1-6      1.38µs ±10%  3.93µs ±50%  +184.80%  (p=0.000 n=10+10)
MVCCGetMergedTimeSeries/numKeys=1/mergesPerKey=16-6     12.9µs ±16%  21.8µs ± 2%   +69.01%  (p=0.000 n=9+10)
MVCCGetMergedTimeSeries/numKeys=1/mergesPerKey=256-6    1.70ms ± 6%  2.57ms ± 2%   +51.17%  (p=0.000 n=10+10)
MVCCGetMergedTimeSeries/numKeys=16/mergesPerKey=1-6     1.46µs ± 3%  4.64µs ± 3%  +218.26%  (p=0.000 n=10+8)
MVCCGetMergedTimeSeries/numKeys=16/mergesPerKey=16-6    12.9µs ± 3%  49.0µs ± 4%  +280.35%  (p=0.000 n=7+9)
MVCCGetMergedTimeSeries/numKeys=16/mergesPerKey=256-6   1.79ms ± 1%  5.00ms ± 3%  +180.00%  (p=0.000 n=10+10)
MVCCGetMergedTimeSeries/numKeys=256/mergesPerKey=1-6    1.54µs ± 4%  4.93µs ± 9%  +220.34%  (p=0.000 n=9+10)
MVCCGetMergedTimeSeries/numKeys=256/mergesPerKey=16-6   13.0µs ± 6%  45.5µs ±11%  +250.19%  (p=0.000 n=9+10)
MVCCGetMergedTimeSeries/numKeys=256/mergesPerKey=256-6  1.66ms ± 2%  5.34ms ± 0%      ~     (p=0.182 n=10+1)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41838#-:-LrqBBKa6VA3xoCISOMX:bl32jf4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

**Review by ajkr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41838)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/engine/bench_test.go, line 608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41838#-Lrq9wIq2DhnSlSGUEHT:-LrqCGcr8leSKOrWf8Es:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d644da7b5f182419481570fa5ac0e29d192b7180/pkg/storage/engine/bench_test.go#L608)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

For what this test is measuring, I'd leave out the parallelism and just do `for i := 0; i < b.N; i++ {`. We're mainly looking to see the performance of the merge operator. While there is some interesting bit of how it works concurrently, I think the parallelism here will only obscure the single-threaded performance. 
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
Not surprising. Could have been worse. FYI, `--benchmem` will compute allocations per iteration. I'm pretty sure that most of the overhead is excessive allocations leading to GC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41838#-:-LrqDWb91SJPP5bywiwO:bnriw1t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
