### PR TITLE
opt: inverted-index accelerate filters of the form j->0 @> '{"b": "c"}

### LINKED ISSUE #94667: opt: inverted-index accelerate filters of the form j->0 @> '{"b": "c"}
An inverted index can be used to accelerate queries with filters in the form `j->0 @> '{"b": "c"}'` where `j` is a `JSON` column. This is similar to #94666, but the containment (`@>`) operator is used instead of equality (`=`).

Note that we already index accelerate queries with filters where the RHS of the fetch-value (`->`) operator is a string.

We should also try to handle filters that have the contained-by (`<@`) operator, like `j->0 <@ '{"b": "c"}'`.

Jira issue: CRDB-23073

### PR DESCRIPTION
**Pull request by Shivs11**
Previously, the optimizer did not plan inverted index scans for filters
having an integer as the index for the fetch value in a filter alongside
the "contains" or the "contained by" operator.

To address this, we now build JSON arrays from fetch value expressions
with integer indexes. From these JSON arrays, inverted spans are built
for constraining scans over inverted indexes. With these changes chains
of both integer and string fetch value operators are now supported
alongside the "contains" and the "contained by" operators.
(e.g., j->0 @> '{"b": "c"}' and j->0 <@ '{"b": "c"}').

Epic: [CRDB-3301](https://cockroachlabs.atlassian.net/browse/CRDB-3301)
Fixes: https://github.com/cockroachdb/cockroach/issues/94667

Release note (performance improvement): The optimizer now plans
inverted index scans for queries that filter by JSON fetch value
operators (->) with integer indices alongside the "contains" or
the "contained by" operators, e.g, json_col->0 @> '{"b": "c"}'
or json_col->0 <@ '{"b": "c"}'

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
That was quick! :slightly_smiling_face: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-:-NN30Rg4EjIXiTwjpgWF:bx2vdar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2yqxV4k3EtuPjtDnG):*
nit: also mention <@ (You've added support for both "contains" and "contained by")
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2zO8W2Toc3iVBKEL9:-NN2zO8W2Toc3iVBKELA:b-84ms5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/logictest/testdata/logic_test/inverted_index#L846)):*
> ```
> SELECT j FROM f@i WHERE j->0->1 @> '{"a": {"b": []}}'
> ----
> [[{"a": {"b": []}}]]
> ```

This doesn't look right, since there is no element at `j->0->1`. Maybe you need to mark this expression as not tight?
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2928 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-NnH46qZltOg1R8S:-NN3-NnH46qZltOg1R8T:b3f7x1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/opt/xform/testdata/rules/select#L2928)):*
> ```
> 
> # Generate an inverted scan when the index of the fetch val operator
> # is an integer and there is a containment operator with a JSON object
> ```

nit: end comment with period (here and below)
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2972 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-nCx0eqzNcV0Zk2A:-NN3-nCx0eqzNcV0Zk2B:b-7npwt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/sql/opt/xform/testdata/rules/select#L2972)):*
> ```
> # Generate an inverted scan when right side of the equality is an array.
> opt expect=GenerateInvertedIndexScans
> SELECT k FROM b WHERE j->'a' = '["b"]'
> ```

Did you mean to get rid of this test case and the one below?

**Review by Shivs11 — COMMENTED** [review]
Thanks for the quick review as well!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-:-NN3H6mJDb3oKjiJid81:b-ccg01q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2zO8W2Toc3iVBKEL9:-NN3H8s_3qR2syxvksXQ:bqb581t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/logictest/testdata/logic_test/inverted_index#L846)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This doesn't look right, since there is no element at `j->0->1`. Maybe you need to mark this expression as not tight?
</blockquote></details>

Had a quick question about this - what does it mean by having no element at `j->0->1` ? In my understanding, the answer given by the query, `[[{"a": {"b": []}}]]`, satisfies the filter of `j->0->1 @> '{"a": {"b": []}}'` right?
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2972 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-nCx0eqzNcV0Zk2A:-NN3Hlze2aNkd91cOK3o:b-beptt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/sql/opt/xform/testdata/rules/select#L2972)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you mean to get rid of this test case and the one below?
</blockquote></details>

I thought these test cases would be testing filters of the form: j->0 @> '"a"' right?

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2972 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-nCx0eqzNcV0Zk2A:-NN3JgjM7ppZ23ok4-FF:b895mai) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/sql/opt/xform/testdata/rules/select#L2972)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

I thought these test cases would be testing filters of the form: j->0 @> '"a"' right?
</blockquote></details>

Ah, I seem to have misunderstood your question. I noticed that it has been removed, due to some reason.
Shall add them back since I think they are pretty important cases to consider. Thank you for the catch!

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2zO8W2Toc3iVBKEL9:-NN3JTdL0wYs25Av7wly:bnjfi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/logictest/testdata/logic_test/inverted_index#L846)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Had a quick question about this - what does it mean by having no element at `j->0->1` ? In my understanding, the answer given by the query, `[[{"a": {"b": []}}]]`, satisfies the filter of `j->0->1 @> '{"a": {"b": []}}'` right?
</blockquote></details>

I think it satisfies `j->0->0 @> '{"a": {"b": []}}'`
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2972 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-nCx0eqzNcV0Zk2A:-NN3Jix63OaZEVdMV_RQ:b-60ulqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/sql/opt/xform/testdata/rules/select#L2972)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

I thought these test cases would be testing filters of the form: j->0 @> '"a"' right?
</blockquote></details>

The new cases you added are good, but you removed some old ones (this one was `j->'a' = '["b"]'`)

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2zO8W2Toc3iVBKEL9:-NN3Km6z9wdFG4RBzo6I:b-btqgzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/logictest/testdata/logic_test/inverted_index#L846)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it satisfies `j->0->0 @> '{"a": {"b": []}}'`
</blockquote></details>

Oh yeah, my apologies it is indeed `j->0->0` and not `j->0->1`. So in an ideal setting, the output of this query should be no rows right? The fact that this outputs an invalid row is concerning....
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2928 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-NnH46qZltOg1R8S:-NN3KdeJ0pps0Tbqyk_W:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/opt/xform/testdata/rules/select#L2928)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: end comment with period (here and below)
</blockquote></details>

Done!
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2972 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3-nCx0eqzNcV0Zk2A:-NN3KTxUAbZxZVezkbtv:b-cb1p8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ef5d9d7a646831799faa0f0611834fe032b93b/pkg/sql/opt/xform/testdata/rules/select#L2972)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The new cases you added are good, but you removed some old ones (this one was `j->'a' = '["b"]'`)
</blockquote></details>

Yep, I see the issue now. I have added them back and shall be pushing them right now. Thank you and sorry!

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2yqxV4k3EtuPjtDnG):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: also mention <@ (You've added support for both "contains" and "contained by")
</blockquote></details>

Done!

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3XQm87qTt2kYJBNHC:-NN3XQm87qTt2kYJBNHD:b1avwcs) (no related file):*
I just realized that I have forgotten to add code which shall set the generated `inverted_expr` to tight if keys are of the form of `DInt`. Thank you @rytaft for giving me that hint when a test case failed in one of my earlier submissions. Shall be adding code to now account for that!

___

**Review by rytaft — APPROVED** [review]
:lgtm: just one minor nit below. Nice work!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-:-NN3sAQrDR-swGG_G_45:bcpuzi7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @Shivs11)

___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN2zO8W2Toc3iVBKEL9:-NN3qpAEB8LcNaHZCGaS:bqf7qy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e0323607b16247d50c87b23b37b9fa6af2ff79/pkg/sql/logictest/testdata/logic_test/inverted_index#L846)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Oh yeah, my apologies it is indeed `j->0->0` and not `j->0->1`. So in an ideal setting, the output of this query should be no rows right? The fact that this outputs an invalid row is concerning....
</blockquote></details>

Looks correct now
___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 603 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3rqyY-TKOM85qu522:-NN3rqyY-TKOM85qu523:bodsj3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ce0bca60f685c44c702f51b1616c736ff37750d/pkg/sql/opt/invertedidx/json_array_test.go#L603)):*
> ```Go
> 			tight:            false,
> 			unique:           true,
> 			remainingFilters: `j->0 @> '[1,2]'`,
> ```

This is a duplicate test case

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 603 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN3rqyY-TKOM85qu522:-NN7OXE79Eeote-E2-wo:b-okwzn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ce0bca60f685c44c702f51b1616c736ff37750d/pkg/sql/opt/invertedidx/json_array_test.go#L603)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is a duplicate test case
</blockquote></details>

Removed it in the latest push! Thank you!

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Great work! :lgtm: 

> Reviewed 1 of 4 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-:-NN7RVjn6spyRmHt-CVn:b47l1fw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Shivs11)

___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96202#-NN7RKUN0YJBdejdrpg2:-NN7RKUN0YJBdejdrpg3:b-cvae97) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a3c3e339799a27ddafbef19ed9a1bbd82cb4149/pkg/sql/opt/invertedidx/json_array_test.go#L566)):*
> ```Go
> 		},
> 		{
> 			filters:          "j->0 @> '[1,2]'",
> ```

nit: A single element array might be a good test, like `j->0 @> '[1]'.

**Comment by renatolabs** [comment]
bors r-

See failures in Essential CI.

**Pull request merged**
