### PR TITLE
rac2: add kvflowsimulator equivalent simulation test

### LINKED ISSUE #130186: kvflowcontrol: add simulation unit test equivalent to kvflowsimulator
Add a unit test which has similar coverage as `kvflowsimulator` for `rac2`:

https://github.com/cockroachdb/cockroach/blob/d3e15d723ea8a7bd0c7e9c9600ff25df08525287/pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/simulation_test.go#L43-L47

Jira issue: CRDB-41914

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
Add a new simulation test, `TestUsingSimulation`. This test mirrors
`kvflowsimulator.TestUsingSimulation` and its existing datadriven tests
cases.

When comparing the output from each, no behavioral differences show up,
only intentionally different metric names.

Note that like the `kvflowsimulator.TestUsingSimulation`, the simulation
test needs to be deterministic and therefore only uses a single
goroutine, to avoid goroutine scheduling causing non-determinism. As
such, helper methods have been added to facilitate waiting for available
tokens directly on a stream's token counter and on a range in a
non-blocking manner (`testingNonBlockingAdmit`). These added methods
are simplified versions of `WaitForEval`, which always wait for all
connected streams to have available tokens before admission.

Resolves: https://github.com/cockroachdb/cockroach/issues/130186
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Diffed test outputs between `kvflowsimulator.TestUsingSimulation` and `rac2.TestUsingSimulation:

```bash
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_overview
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_shared_stream pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_shared_stream
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_single_slow_stream
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_connection pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_connection
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_admitting_waiting_choppy pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_admitting_waiting_choppy
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_over_admission pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_over_admission
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_overview pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_overview
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_regular_elastic_prioritization pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_regular_elastic_prioritization
```


<details><summary>handle_overview vs range_controller_overview</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_overview pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_overview
56,58c56,58
< kvadmission.flow_controller.regular_stream_count               unit=streams
< kvadmission.flow_controller.regular_tokens_available           unit=MiB
< kvadmission.flow_controller.regular_tokens_{deducted,returned} unit=MiB/s rate=true
---
> kvflowcontrol.streams.eval.regular.total_count        unit=streams
> kvflowcontrol.tokens.eval.regular.available           unit=MiB
> kvflowcontrol.tokens.eval.regular.{deducted,returned} unit=MiB/s rate=true
62c62
<            regular_stream_count (streams)
---
>       streams.eval.regular.total_count (streams)
81c81
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
100c100
<       rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
114,115c114,115
< kvadmission.flow_controller.regular_tokens_available           unit=MiB
< kvadmission.flow_controller.regular_tokens_{deducted,returned} unit=MiB/s rate=true
---
> kvflowcontrol.tokens.eval.regular.available           unit=MiB
> kvflowcontrol.tokens.eval.regular.{deducted,returned} unit=MiB/s rate=true
134c134
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
153c153
<        rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>        rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
```

</details>


<details><summary>handle_shared_stream vs range_controller_shared_stream</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_shared_stream pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_shared_stream
27,30c27,31
< kvadmission.flow_controller.regular_{,blocked_}stream_count     unit=streams
< kvadmission.flow_controller.regular_tokens_available            unit=MiB
< kvadmission.flow_controller.regular_tokens_{deducted,returned}  unit=MiB/s rate=true
< kvadmission.flow_handle.regular_requests_{admitted,waiting}     unit=reqs/s rate=true
---
> 
> kvflowcontrol.streams.eval.regular.{blocked,total}_count    unit=streams
> kvflowcontrol.tokens.eval.regular.available                 unit=MiB
> kvflowcontrol.tokens.eval.regular.{deducted,returned}       unit=MiB/s rate=true
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
33c34
<  1.0 ┼──────────────────────────────────────╭
---
>  1.0 ┼───────────────────────────────────────
49c50
<       regular_{,blocked_}stream_count (streams)
---
>       streams.eval.regular.{blocked,total}_count (streams)
68c69
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
87c88
<       rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
106c107
<        rate(flow_handle.regular_requests_{admitted,waiting}) (reqs/s)
---
>        rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)

```

</details>


<details><summary>handle_single_slow_stream vs range_controller_single_slow_stream</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_single_slow_stream pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_single_slow_stream
41,44c41,45
< kvadmission.flow_controller.regular_tokens_available           unit=MiB
< kvadmission.flow_controller.regular_tokens_{deducted,returned} unit=MiB/s rate=true
< kvadmission.flow_controller.regular_blocked_stream_count       unit=streams
< kvadmission.flow_handle.regular_requests_{admitted,waiting}    unit=reqs/s rate=true
---
> 
> kvflowcontrol.tokens.eval.regular.available                 unit=MiB
> kvflowcontrol.tokens.eval.regular.{deducted,returned}       unit=MiB/s rate=true
> kvflowcontrol.streams.eval.regular.blocked_count            unit=streams
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
63c64
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
82c83
<       rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
101c102
<        regular_blocked_stream_count (streams)
---
>       streams.eval.regular.blocked_count (streams)
120c121
<        rate(flow_handle.regular_requests_{admitted,waiting}) (reqs/s)
---
>        rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
```

</details>


<details><summary>handle_stream_connection vs range_controller_stream_connection</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_connection pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_connection
29,31c29,32
< kvadmission.flow_controller.regular_stream_count               unit=streams
< kvadmission.flow_controller.regular_tokens_available           unit=MiB
< kvadmission.flow_controller.regular_tokens_{deducted,returned} unit=MiB/s rate=true
---
> 
> kvflowcontrol.streams.eval.regular.total_count        unit=streams
> kvflowcontrol.tokens.eval.regular.available           unit=MiB
> kvflowcontrol.tokens.eval.regular.{deducted,returned} unit=MiB/s rate=true
50c51
<            regular_stream_count (streams)
---
>       streams.eval.regular.total_count (streams)
69c70
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
88c89
<       rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
```

</details>


<details><summary>handle_stream_disconnection vs range_controller_stream_disconnection</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/handle_stream_disconnection pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/range_controller_stream_disconnection
46,49c46,49
< kvadmission.flow_controller.regular_blocked_stream_count    unit=streams
< kvadmission.flow_controller.regular_tokens_available        unit=MiB
< kvadmission.flow_controller.regular_requests_bypassed       unit=reqs/s rate=true
< kvadmission.flow_handle.regular_requests_{admitted,waiting} unit=reqs/s rate=true
---
> kvflowcontrol.streams.eval.regular.blocked_count            unit=streams
> kvflowcontrol.tokens.eval.regular.available                 unit=MiB
> kvflowcontrol.eval_wait.elastic.requests.bypassed           unit=reqs/s rate=true
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
68c68
<        regular_blocked_stream_count (streams)
---
>       streams.eval.regular.blocked_count (streams)
87c87
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
90,106c90,91
<  16.0 ┤                    ╭──╮
<  14.9 ┤                    │  │
<  13.9 ┤                    │  │
<  12.8 ┤                   ╭╯  │
<  11.7 ┤                   │   │
<  10.7 ┤                   │   │
<   9.6 ┤                   │   │
<   8.5 ┤                   │   │
<   7.5 ┤                   │   │
<   6.4 ┤                   │   │
<   5.3 ┤                   │   │
<   4.3 ┤                   │   │
<   3.2 ┤                   │   │
<   2.1 ┤                   │   │
<   1.1 ┤                   │   ╰╮
<   0.0 ┼───────────────────╯    ╰──────────────
<        rate(regular_requests_bypassed) (reqs/s)
---
>  0.0 ┼───────────────────────────────────────
>       rate(eval_wait.elastic.requests.bypassed) (reqs/s)
125c110
<         rate(flow_handle.regular_requests_{admitted,waiting}) (reqs/s)
---
>         rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
```

</details>


<details><summary>flow_controller_admitting_waiting_choppy vs streams_admitting_waiting_choppy</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_admitting_waiting_choppy pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_admitting_waiting_choppy
37,39c37,40
< kvadmission.flow_controller.regular_tokens_{deducted,returned}  unit=MiB/s rate=true
< kvadmission.flow_controller.regular_tokens_{deducted,returned}  unit=MiB
< kvadmission.flow_controller.regular_tokens_available            unit=MiB
---
> 
> kvflowcontrol.tokens.eval.regular.{deducted,returned}  unit=MiB/s rate=true
> kvflowcontrol.tokens.eval.regular.{deducted,returned}  unit=MiB
> kvflowcontrol.tokens.eval.regular.available            unit=MiB
58c59
<       rate(regular_tokens_{deducted,returned}) (MiB/s)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
77c78
<        regular_tokens_{deducted,returned} (MiB)
---
>        tokens.eval.regular.{deducted,returned} (MiB)
96c97
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
106c107
< kvadmission.flow_controller.regular_tokens_available            unit=MiB
---
> kvflowcontrol.tokens.eval.regular.available unit=MiB
124c125
<             regular_tokens_available (MiB)
---
>          tokens.eval.regular.available (MiB)
130c131
< kvadmission.flow_controller.regular_tokens_{deducted,returned}  unit=MiB rate=true
---
> kvflowcontrol.tokens.eval.regular.{deducted,returned}  unit=MiB/s rate=true
148c149
<       rate(regular_tokens_{deducted,returned}) (MiB)
---
>       rate(tokens.eval.regular.{deducted,returned}) (MiB/s)
155,156c156,157
< kvadmission.flow_controller.regular_requests_{admitted,waiting} unit=reqs/s rate=true
< kvadmission.flow_controller.regular_requests_waiting unit=reqs
---
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
> kvflowcontrol.eval_wait.regular.requests.waiting            unit=reqs
175c176
<        rate(regular_requests_{admitted,waiting}) (reqs/s)
---
>        rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
194c195
<           regular_requests_waiting (reqs)
---
>       eval_wait.regular.requests.waiting (reqs)
```

</details>


<details><summary>flow_controller_over_admission vs streams_over_admission</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_over_admission pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_over_admission
30c30
< # TODO(irfansharif): Introduce a "tentative deducted counter" on a per-stream
---
> # TODO(kvoli,sumeerbhola): Introduce a "tentative deducted counter" on a per-stream
34,36c34,36
< kvadmission.flow_controller.regular_tokens_available  unit=MiB
< kvadmission.flow_controller.regular_requests_admitted unit=reqs/s rate=true
< kvadmission.flow_controller.regular_requests_waiting  unit=reqs
---
> kvflowcontrol.tokens.eval.regular.available unit=MiB
> kvflowcontrol.eval_wait.regular.requests.admitted unit=reqs/s rate=true
> kvflowcontrol.eval_wait.regular.requests.waiting  unit=reqs/s
55c55
<              regular_tokens_available (MiB)
---
>           tokens.eval.regular.available (MiB)
74c74
<         rate(regular_requests_admitted) (reqs/s)
---
>         rate(eval_wait.regular.requests.admitted) (reqs/s)
93c93
<             regular_requests_waiting (reqs)
---
>         eval_wait.regular.requests.waiting (reqs/s)
```

</details>

<details><summary>flow_controller_overview vs streams_overview</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_overview pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_overview
31,32c31,32
< kvadmission.flow_controller.{regular,elastic}_tokens_available unit=MiB
< kvadmission.flow_controller.{regular,elastic}_tokens_deducted  unit=MiB/s rate=true
---
> kvflowcontrol.tokens.eval.{regular,elastic}.available unit=MiB
> kvflowcontrol.tokens.eval.{regular,elastic}.deducted  unit=MiB/s rate=true
51c51
<         {regular,elastic}_tokens_available (MiB)
---
>         tokens.eval.{regular,elastic}.available (MiB)
70c70
<       rate({regular,elastic}_tokens_deducted) (MiB/s)
---
>       rate(tokens.eval.{regular,elastic}.deducted) (MiB/s)
80,81c80,81
< kvadmission.flow_controller.regular_requests_{admitted,waiting} unit=reqs/s rate=true
< kvadmission.flow_controller.{regular,elastic}_requests_errored  unit=reqs/s rate=true
---
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
> kvflowcontrol.eval_wait.{regular,elastic}.requests.errored  unit=reqs/s rate=true
100c100
<       rate(regular_requests_{admitted,waiting}) (reqs/s)
---
>       rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
104c104
<       rate({regular,elastic}_requests_errored) (reqs/s)
---
>       rate(eval_wait.{regular,elastic}.requests.errored) (reqs/s)
111,112c111,112
< kvadmission.flow_controller.regular_stream_count                   unit=streams
< kvadmission.flow_controller.{regular,elastic}_blocked_stream_count unit=streams
---
> kvflowcontrol.streams.eval.regular.total_count             unit=streams
> kvflowcontrol.streams.eval.{regular,elastic}.blocked_count unit=streams
116c116
<            regular_stream_count (streams)
---
>       streams.eval.regular.total_count (streams)
135c135
<       {regular,elastic}_blocked_stream_count (streams)
---
>       streams.eval.{regular,elastic}.blocked_count (streams)
144,145c144,145
< kvadmission.flow_controller.regular_requests_{admitted,waiting} unit=reqs/s rate=true
< kvadmission.flow_controller.{regular,elastic}_tokens_available unit=MiB
---
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
> kvflowcontrol.tokens.eval.{regular,elastic}.available       unit=MiB
165c165
<        rate(regular_requests_{admitted,waiting}) (reqs/s)
---
>        rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
184c184
<         {regular,elastic}_tokens_available (MiB)
---
>         tokens.eval.{regular,elastic}.available (MiB)
```

</details>

<details><summary>flow_controller_regular_elastic_prioritization vs streams_regular_elastic_prioritization</summary>

```diff
$ diff pkg/kv/kvserver/kvflowcontrol/kvflowsimulator/testdata/flow_controller_regular_elastic_prioritization pkg/kv/kvserver/kvflowcontrol/rac2/testdata/simulation/streams_regular_elastic_prioritization
24c24
< kvadmission.flow_controller.{regular,elastic}_tokens_available  unit=MiB
---
> kvflowcontrol.tokens.eval.{regular,elastic}.available unit=MiB
42c42
<         {regular,elastic}_tokens_available (MiB)
---
>         tokens.eval.{regular,elastic}.available (MiB)
52,53c52,53
< kvadmission.flow_controller.regular_requests_{admitted,waiting} unit=reqs/s rate=true
< kvadmission.flow_controller.elastic_requests_{admitted,waiting} unit=reqs/s rate=true
---
> kvflowcontrol.eval_wait.regular.requests.{admitted,waiting} unit=reqs/s rate=true
> kvflowcontrol.eval_wait.elastic.requests.{admitted,waiting} unit=reqs/s rate=true
72c72
<         rate(regular_requests_{admitted,waiting}) (reqs/s)
---
>         rate(eval_wait.regular.requests.{admitted,waiting}) (reqs/s)
91c91
<         rate(elastic_requests_{admitted,waiting}) (reqs/s)
---
>         rate(eval_wait.elastic.requests.{admitted,waiting}) (reqs/s)
99c99
< kvadmission.flow_controller.elastic_tokens_deducted  unit=MiB rate=true
---
> kvflowcontrol.tokens.eval.elastic.deducted  unit=MiB/s rate=true
117c117
<         rate(elastic_tokens_deducted) (MiB)
---
>       rate(tokens.eval.elastic.deducted) (MiB/s)
```

</details>


Note there is a non-naming diff for `handle_stream_disconnection vs range_controller_stream_disconnection` due to the new test doing stream disconnection differently. If it is worthwhile, I'll try to massage the newer test to conform.

**Comment by sumeerbhola** [comment]
> Note there is a non-naming diff for handle_stream_disconnection vs range_controller_stream_disconnection due to the new test doing stream disconnection differently. If it is worthwhile, I'll try to massage the newer test to conform.

I don't think we need to conform to existing behavior at all. Just curious: is this because we don't consider these as bypassed as we will see the `refreshCh` being signaled, pop back up, and then wait again on s1 and s2?

**Comment by kvoli** [comment]
> I don't think we need to conform to existing behavior at all

Ack, I think getting these to a point where they produced identical output was useful. I'll consider changing some parts to arrive at a more representative non-blocking `WaitForEval` implementation.

For times sake though, it may be worthwhile merging as is, move to #130187, then the send queue implementation and then come back to this test and re-shape it exercise the send queue impl.

> Just curious: is this because we don't consider these as bypassed as we will see the `refreshCh` being signaled, pop back up, and then wait again on s1 and s2?

The mocked WaitForEval function is doing all of this logic and doesn't check the voter sets again.

See these two functions [(1)](https://github.com/kvoli/cockroach/blob/879b38d22285329e09021a0b8fb4d0289be97a1b/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L1044-L1044) [(2)](https://github.com/kvoli/cockroach/blob/879b38d22285329e09021a0b8fb4d0289be97a1b/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L1003-L1003).

**Review by sumeerbhola — APPROVED** [review]
Really nice to have this done!
I only glanced at at a couple of testdata files since the output is the same as RACv1.

:lgtm_strong: 

> Reviewed 3 of 14 files at r4, 2 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-:-O6mV8I14D9F6uJR1Xeu:b-wbwz5x)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l30bMAFXPBuaUQA1p:-O6l30bMAFXPBuaUQA1q:bkgg33h) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L58)):*
> ```Go
> //   - eval_wait metrics are handled via testing functions, rather than updated
> //     via WaitForEval.
> //   - Tokens can be deducted/returned to a stream indepdenently of the
> ```

nit: independently
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l4Mty9KeCWcoey5T6:-O6l4Mty9KeCWcoey5T7:b-t3mnb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L95)):*
> ```Go
> //     granularity of token adjustment, i.e. if adjust=+100bytes/s and
> //     rate=5/s, then each return adjusts by +100/5 = +20bytes. If flow
> //     tokens are being deducted (-ve 'adjust'), they go through Admit()
> ```

Did this mean to say `Admit()` and `DeductTokens()` or something else? Those are `kvflowcontrol.Controller` methods that we don't use.
Same question for `ReturnTokens()`.

Maybe testingDeductTokens, testingReturnTokens?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5-PP7Szx8fRIbeGn:-O6l5-PP7Szx8fRIbeGo:bio5yrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L101)):*
> ```Go
> //     granted admission and it deducting the corresponding flow tokens.
> //
> //     B. Similar to A except using a given handle instead, which internally
> ```

I guess this is stale since "handle", "connected stream" is v1 terminology.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 104 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5HIZ3FOYwyKX7LkF:-O6l5HIZ3FOYwyKX7LkG:bepf1lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L104)):*
> ```Go
> //     deducts tokens from all connected streams or if returning tokens, does so
> //     for the named stream. Token deductions from a range's RangeController
> //     are tied to monotonically increasing raft log positions starting from
> ```

nit: from the position
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5TKA9TlEyZWWLCo9:-O6l5TKA9TlEyZWWLCoA:b-ej5tem) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L110)):*
> ```Go
> //     positions).
> //
> //     C. Connects the handle's RangeController to the specific stream,
> ```

So this is ensuring the replicaSendStream exists?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 119 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5Zn41jxHPdWZtEkr:-O6l5Zn41jxHPdWZtEks:b-emic56) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L119)):*
> ```Go
> //     don't deduct from/return to the stream.
> //
> //     E. Close or snapshot the named handle. When closing a RangeController,
> ```

Should this say "Close or snapshot the named RangeController"?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 535 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6mQ0i71Oc8vy0YFbxm:-O6mQ0i71Oc8vy0YFbxn:bal2em3) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L535)):*
> ```Go
> 
> 	// Forms B-E, using the RangeController instead.
> 	require.NotNil(s.state.t, tl.handle)
> ```

nit: consider renaming handle and handleOp to rc and rcOp.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 593 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6mQotE9lvQ-S-wbh3c:-O6mQotE9lvQ-S-wbh3d:b93rxbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L593)):*
> ```Go
> 		s.ticker[i].reset()
> 		if s.ticker[i].end().After(tend) {
> 			tend = s.ticker[i].end()
> ```

I realize this is inherited from the previous simulator, but I am curious why `tend` gets adjusted, i.e., we simulate beyond what was specified in `simulate`.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-:-O6vAqTx2f3cWvsGLz74:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l30bMAFXPBuaUQA1p:-O6v8B8L61F45sr0DV5s:b-fdtigt) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: independently
</blockquote></details>

Fixed spelling.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l4Mty9KeCWcoey5T6:-O6v8PT_9NFepUEuYxpY:blfttof) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Did this mean to say `Admit()` and `DeductTokens()` or something else? Those are `kvflowcontrol.Controller` methods that we don't use.
Same question for `ReturnTokens()`.

Maybe testingDeductTokens, testingReturnTokens?
</blockquote></details>

Updated to `testingNonBlockingAdmit()` `testingDeductTokens()` and `testingReturnTokens()`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5-PP7Szx8fRIbeGn:-O6v8a4cDRQ8cLjWloAX:bvtbjs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I guess this is stale since "handle", "connected stream" is v1 terminology.
</blockquote></details>

Extended the sentence to mention handles map to a range's RangeController.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 104 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5HIZ3FOYwyKX7LkF:-O6v8mJk5IIXE5NypmYu:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L104)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: from the position
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 110 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5TKA9TlEyZWWLCo9:-O6v8ncN7Jv0tscpoS1Z:bfn6k9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L110)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So this is ensuring the replicaSendStream exists?
</blockquote></details>

Yes. Added another sentence explaining this.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 119 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6l5Zn41jxHPdWZtEkr:-O6v9A-s-_gD7T0Ol3MW:by630eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L119)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should this say "Close or snapshot the named RangeController"?
</blockquote></details>

I'm trying to weave in the handle terminology as a named RangeController, updated this sentence to `Disconnects the specific stream from the named handle's RangeController.`
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 535 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6mQ0i71Oc8vy0YFbxm:-O6v9LgE1cmjkZis7Bmc:bdx30fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L535)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: consider renaming handle and handleOp to rc and rcOp.
</blockquote></details>

Updated to `rcOp` but left `handle` as is, because it is used in the test syntax. Mentioned above, a handle is presented in these tests as a named RangeController.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go` line 593 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130446#-O6mQotE9lvQ-S-wbh3c:-O6v9jRT9zya6Lr1G5S_:b-wco59b) ([raw file](https://github.com/cockroachdb/cockroach/blob/65bc31ec3faa267511ce3c7c7d74d1e22e91aa66/pkg/kv/kvserver/kvflowcontrol/rac2/simulation_test.go#L593)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I realize this is inherited from the previous simulator, but I am curious why `tend` gets adjusted, i.e., we simulate beyond what was specified in `simulate`.
</blockquote></details>

It is for when `simulate` doesn't specify an end time, the passed in time will be the default constructed time.Time, so its just for convince.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
