### PR TITLE
roachtest: add ruby-pg test to ignorelist

### LINKED ISSUE #111508: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11980180?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11980180?buildTab=artifacts#/ruby-pg) on release-23.1 @ [830d39ee42c3165b67e4ba257aad9ea9323fa083](https://github.com/cockroachdb/cockroach/commits/830d39ee42c3165b67e4ba257aad9ea9323fa083):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.1.11-dev-830d39ee42c3165b67e4ba257aad9ea9323fa083
Tests run against ruby-pg v1.3.5
834 Total Tests Run
646 tests passed
188 tests failed
0 tests skipped
0 tests ignored
1 test passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
1 test expected failed but not run
---
For a full summary look at the ruby-pg artifacts
An updated blocklist (rubyPGBlocklist) is available in the artifacts' ruby-pg log
test artifacts and logs in: /artifacts/ruby-pg/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-11980180/ruby-pg/1696002472125/1696003158616)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31947

### LINKED ISSUE #111522: roachtest: ruby-pg failed
roachtest.ruby-pg [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11980154?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11980154?buildTab=artifacts#/ruby-pg) on master @ [27e7c166b5591b0e05bb2fd23780309b490d7af9](https://github.com/cockroachdb/cockroach/commits/27e7c166b5591b0e05bb2fd23780309b490d7af9):

```
(orm_helpers.go:213).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.2-dev-27e7c166b5591b0e05bb2fd23780309b490d7af9
Tests run against ruby-pg v1.3.5
834 Total Tests Run
648 tests passed
186 tests failed
0 tests skipped
0 tests ignored
1 test passed unexpectedly
0 tests failed unexpectedly
0 tests expected failed but skipped
1 test expected failed but not run
---
For a full summary look at the ruby-pg artifacts 
An updated blocklist (rubyPGBlocklist) is available in the artifacts' ruby-pg log
test artifacts and logs in: /artifacts/ruby-pg/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-11980154/ruby-pg/1696009169634/1696009858589)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #111508 roachtest: ruby-pg failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1 release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*ruby-pg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31945

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/111522
fixes https://github.com/cockroachdb/cockroach/issues/111508

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
Hmm I added this test to the blocklist last week https://github.com/cockroachdb/cockroach/pull/111325 since it seemed flaky. Do we maybe want to instead create an ignorelist and put this test on that?

I'm also kind of confused why it started showing up as both `passed unexpectedly` and `expected failed but not run` after it was added to the blocklist too, do you know why that's happening?

**Comment by rafiss** [comment]
> Do we maybe want to instead create an ignorelist and put this test on that?

Yeah this is a better approach.

Flaky tests cannot be in the in the `blocklist` since those are tests that are expected to fail on every run

> I'm also kind of confused why it started showing up as both passed unexpectedly and expected failed but not run after it was added to the blocklist too, do you know why that's happening?

Looks like there's a bug in the way the test counts unexpected fails. I think this case is wrong: https://github.com/cockroachdb/cockroach/blob/b0e01822a905eb4a0f732503773abe39ac77d5c9/pkg/cmd/roachtest/tests/ruby_pg.go#L210-L216

**Comment by rafiss** [comment]
>> I'm also kind of confused why it started showing up as both passed unexpectedly and expected failed but not run after it was added to the blocklist too, do you know why that's happening?
>
> Looks like there's a bug in the way the test counts unexpected fails. I think this case is wrong: 

Actually that case is fine. The reason is because the ruby-pg tests only log the test name if the test fails. So we can't actually tell which ones are "not run" versus "passed"

**Review by andyyang890 — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
