### PR TITLE
storage: stop writing SST table properties

### PR DESCRIPTION
**Pull request by erikgrinaker**
**util/hlc: add `Timestamp.WallNext()`**

Release note: None

**storage: stop writing SST table properties**

Previously, SSTables were written with the table properties
`crdb.ts.min` and `crdb.ts.max` tracking the minimum and maximum
timestamps in the SSTable. This was used to filter SSTables via the
`MVCCIterator` options `MinTimestampHint` and `MaxTimestampHint`,
aka time-bound iterators.

In 22.1, we additionally began writing the block property
`MVCCTimeInterval` containing the minimum and maximum timestamps for
each SSTable block, aggregated up to the SSTable. Time-bound iterators
filter on this block property in addition to the table properties.

In 22.2, we will be introducing Pebble range keys. Table properties do
not support range keys, so we must migrate entirely to block properties.

This patch therefore stops writing table properties entirely. This
ensures that SSTables containing range keys (introduced in 22.2) will
not have table properties -- conversely, SSTables that do have table
properties can only contain point keys. By doing so, we avoid
erroneously filtering out SSTables with range keys that satisfy the time
predicate but were not taken into account by table properties. A later
patch will add block property collectors for range keys.

We still respect table properties while filtering, to maintain
compatibility with SSTables written by 21.2 nodes and earlier. We must
retain this backwards compatibility as long as it is possible for a
cluster to have SSTables written by older nodes, which can happen e.g.
if a cluster is upgraded from 21.2 to 22.2 in rapid succession.

The change from table to block properties slightly changes the filtering
semantics, as block properties discard the logical timestamp component.
This should not be an issue, since timestamp hints are inclusive, and
TBIs are allowed to emit false positives.

This patch also removes the `IteratorStats.TimeBoundNumSSTs` field, as
block property filters do not update it.

Touches #82596.

Release note: None
  
**storage: remove `pebbleDeleteRangeCollector`**

This was a noop property collector no longer in use.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
> This patch therefore stops writing table properties entirely. This
> ensures that SSTables containing range keys (introduced in 22.2) will
> not have table properties -- conversely, SSTables that do have table
> properties can only contain point keys. By doing so, we avoid
> erroneously filtering out SSTables with range keys that satisfy the time
> predicate but were not taken into account by table properties. A later
> patch will add block property collectors for range keys.

I checked the code, and Pebble will ignore the `TableFilter` for range-key iterators. So this change is unnecessary from a correctness perspective, but I think it's worthwhile [and we should stop populating `TableFilter` in 23.1].

:lgtm:

Thanks for doing this!

> Reviewed 2 of 2 files at r1, 6 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-:-N483fQO76OObHDX0pdS:b-nduuq1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-N487rKb8_zr4gKHt-oF:-N487rKb8_zr4gKHt-oG:bmmh3sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3706c07f7332098d3eb0fcb6ae3b682a385b1306/pkg/storage/engine.go#L181)):*
> ```Go
> // IteratorStats is returned from {MVCCIterator,EngineIterator}.Stats.
> type IteratorStats struct {
> 	TimeBoundNumSSTs int
> ```

so this stat was just unused?
___
*[`pkg/storage/pebble.go` line 412 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-N486LZ7CSkuU33oH_rr:-N486LZ7CSkuU33oH_rs:b-5ldik4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3706c07f7332098d3eb0fcb6ae3b682a385b1306/pkg/storage/pebble.go#L412)):*
> ```Go
> func (t *pebbleTimeBoundPropCollector) Name() string {
> 	// This constant needs to match the one used by the RocksDB version of this
> 	// table property collector. DO NOT CHANGE.
> ```

@sumeerbhola do you know of any incompatibility from the absence of this prop collector?

This comment gave me pause, but afaict, it never really mattered if this constant changed—it's recorded in the `rocksdb.property.collectors` sstable property, but I don't believe that's used programmatically anywhere. It seems like only the `crdb.ts.min` and `crdb.ts.max` properties actually required stability. Just want to make sure I'm not missing something.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82658)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @jbowens, and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-N487rKb8_zr4gKHt-oF:-N48A-rJDzM4mdqPySjH:b-4j2bxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3706c07f7332098d3eb0fcb6ae3b682a385b1306/pkg/storage/engine.go#L181)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

so this stat was just unused?
</blockquote></details>

Yeah, it was just used in a couple of tests.

**Review by sumeerbhola — COMMENTED** [review]
Doing this sounds very reasonable -- since @jbowens has done a detailed review, I'll skip doing so. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-:-N48JZRp204aWKVV_G_M:b-dhathx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @jbowens)

___
*[`pkg/storage/pebble.go` line 412 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82658#-N486LZ7CSkuU33oH_rr:-N48IoyQ9oDGJ9qVn9GV:birgvl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3706c07f7332098d3eb0fcb6ae3b682a385b1306/pkg/storage/pebble.go#L412)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@sumeerbhola do you know of any incompatibility from the absence of this prop collector?

This comment gave me pause, but afaict, it never really mattered if this constant changed—it's recorded in the `rocksdb.property.collectors` sstable property, but I don't believe that's used programmatically anywhere. It seems like only the `crdb.ts.min` and `crdb.ts.max` properties actually required stability. Just want to make sure I'm not missing something.
</blockquote></details>

Sounds right.

**Comment by erikgrinaker** [comment]
TFTRs!

bors r=jbowens

**Pull request merged**
