### PR TITLE
kvserver: move lease logic from replicate queue to lease queue

### LINKED ISSUE #106102: kvserver: underreplicated ranges block lease transfers
See the lease preference setup in https://github.com/cockroachdb/cockroach/issues/106100#issue-1787514672, where we have 5 nodes with RF=5 across 3 racks, with lease preferences set to rack=0 (2 nodes). When we kill a node, leases are randomly scattered across all surviving replicas. The replicate queue will ([slowly](https://github.com/cockroachdb/cockroach/issues/106101)) begin to move leases back to the preferred region.

However, as soon as the killed node is marked as dead, the replicate queue stops moving leases to the preferred region. It's erroring out on upreplication, since there are no stores that can take the replica, but this appears to also short-circuit the lease transfers, so the leases are now permanently stuck in a non-preferred region.

```
I230704 09:57:11.628687 181045 13@kv/kvserver/replicate_queue.go:753 ⋮ [T1,n2,replicate,s2,r595/4:‹/Table/106/1/9{18651…-20494…}›] 41934  error processing replica: ‹0 of 4 live stores are able to take a new replica for the range (4 already have a voter, 0 already have a non-voter); replicas must match constraints [{+rack=0:2} {+rack=1:2} {+rack=2:1}]; voting replicas must match voter_constraints []›
```

### LINKED ISSUE #118966: kvserver: move lease rebalance logic from replicate queue into lease queue
Move relevant lease rebalance decision and execution logic out of the replicate queue and into the dedicated lease queue.

Jira issue: CRDB-35978

### PR DESCRIPTION
**Pull request by kvoli**
Only the last 2 commits are relevant.

Depends on #119410.

This commit moves the lease responsibilities from the replicate queue
into the newly added lease queue. There is now increased concurrency
for lease and replication changes to occur. The allocator simulator is
also updated to reflect the new queue. Note this resulted in most
datadriven tests which plotted values related to replicas/leases to
change slightly, which is expected with higher concurrency.

Resolves: https://github.com/cockroachdb/cockroach/issues/118966
Part of: https://github.com/cockroachdb/cockroach/issues/118866

### CODE REVIEW

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
> Reviewed 2 of 35 files at r4, 46 of 46 files at r5, 14 of 14 files at r6, 36 of 36 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119155)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/lease_queue.go` line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU3P_06dc-FahcOyrE:-NsU3P_06dc-FahcOyrF:birigof) ([raw file](https://github.com/cockroachdb/cockroach/blob/80272e69eb7536c24db87fec6d85a82fb9ce463d/pkg/kv/kvserver/lease_queue.go#L33)):*
> ```Go
> )
> 
> type LeaseQueueMetrics struct{}
> ```

nit: You introduce the metrics and add the metadata for them in the first commit and then add them in the next one. 

Consider moving some of this to the next commit or alternatively just squashing them together. 

It would probably be best to introduce all the metrics in this commit even though they would always be zero.
___
*[`pkg/kv/kvserver/lease_queue.go` line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU4x2O9zNm0CjACyV6:-NsU4x2P8NYUxz_vnCdr:b-8mu28s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L44)):*
> ```Go
> // replica to be removed from a range or moving from a non-preferrred
> // leaseholder to a preferred leaseholder.
> var MinLeaseTransferInterval = settings.RegisterDurationSetting(
> ```

I don't love that this setting is in terms of absolute time, but I don't necessarily have a good alternative. Also 1s seems long to me, but I don't know what the right value is (100ms?) Consider adding language that says it can be set to 0 to disable waiting between lease transfers. I'd be curious to look at the implications for different values of this for a large cluster. However this is just keeping the old behavior, so feel free to disregard (or just leave a TODO).
___
*[`pkg/kv/kvserver/lease_queue.go` line 135 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU5A5_DH7Z3NicRgjv:-NsU5A5_DH7Z3NicRgjw:bfkex6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L135)):*
> ```Go
> 			return false, errors.Wrapf(err, "%s: unable to transfer lease to s%d", repl, transferOp.Target)
> 		}
> 		lq.lastLeaseTransfer.Store(timeutil.Now())
> ```

consider moving this up. I think we should count it as a lease transfer from a pacing perspective even if this transfer fails. That will help us from busy looping if the lease can't be transferred due to some other reason that is outside of the queues control. I think this can be set on the first line even before we attempt to acquire the token.
___
*[`pkg/kv/kvserver/lease_queue.go` line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU69amDN1poKVkr4WD:-NsU69amDN1poKVkr4WE:b-mt44dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L169)):*
> ```Go
> 	if !repl.OwnsValidLease(ctx, lq.store.cfg.Clock.NowAsClockTimestamp()) {
> 		// This replica is not the leaseholder, so it can't transfer the lease.
> 		return false
> ```

This should be rare that this line is hit. We already specified in the `queueConfig` that this queue requires a lease, so this check is redundant. I think it can be safely removed and might be simpler to follow in case the lease does transfer just at the wrong time since we it will be more clear in the logging that attempts to move the lease.
___
*[`pkg/kv/kvserver/replica_command.go` line 4046 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU79LhAIkPO5aiBu_Y:-NsU79LhAIkPO5aiBu_Z:b-28ctrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_command.go#L4046)):*
> ```Go
> 			if targetStoreID != r.store.StoreID() {
> 				log.VEventf(ctx, 2, "randomly transferring lease to s%d", targetStoreID)
> 				if err := r.AdminTransferLease(ctx, targetStoreID, false /* bypassSafetyChecks */); err != nil {
> ```

Should this go through the lease queue (with skipShoudQueue)? Otherwise we aren't checking against the allocator token. 
___
*[`pkg/kv/kvserver/replica_init.go` line 186 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU7qZx3U0jP2Th6N7q:-NsU7qZx3U0jP2Th6N7r:b-kb6yao) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_init.go#L186)):*
> ```Go
> 		)
> 	}
> 	r.allocatorToken = &plan.AllocatorToken{}
> ```

This is now initialized twice.

nit: I think it would be best to just put this into the construction of the Replica above rather than setting it down here. but I don't really mind either way. 
___
*[`pkg/kv/kvserver/replica_proposal.go` line 557 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU8O51-AjwOF98is5h:-NsU8O51-AjwOF98is5i:b-e94rdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_proposal.go#L557)):*
> ```Go
> 			r.store.nodeDesc.Attrs, r.store.nodeDesc.Locality, r.mu.conf.LeasePreferences)
> 		switch preferenceStatus {
> 		case LeasePreferencesOK, LeasePreferencesLessPreferred:
> ```

I know there was a discussion about also queueing up less preferred priorities. Don't add to this PR, but maybe we add them with a lower priority to the queue in a follow-up?
___
*[`pkg/kv/kvserver/allocator/plan/lease.go` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVBk582vgohxJKbi8T:-NsVBk582vgohxJKbi8U:b-lde3nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/allocator/plan/lease.go#L69)):*
> ```Go
> 		return true, 0
> 	}
> 	if leaseStatus.OwnedBy(repl.StoreID()) && !repl.HasCorrectLeaseType(leaseStatus.Lease) {
> ```

Can you check with @erikgrinaker if this is still required. It might not be since `shouldRequestLeaseRLocked` is called as part of the `tick` loop, but maybe we still need it for quiesced epoch leases. That said, I guess its OK to leave it here regardless. Maybe add a comment that this is only necessary when they change the lease time from epoch to expiration and this could be deleted in the future if we don't support epoch leases anymore.
___
*[`pkg/kv/kvserver/allocator/plan/lease.go` line 149 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVDiIO3M4Fof-QS048:-NsVDiIO3M4Fof-QS049:b-uzrm4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/allocator/plan/lease.go#L149)):*
> ```Go
> 		false, /* forceDecisionWithoutStats */
> 		allocator.TransferLeaseOptions{
> 			Goal:                   allocator.FollowTheWorkload,
> ```

This might just be a movement of existing code, but I don't really understand when we are using `FollowTheWorkload` vs `LeaseCountConvergence`. This might be easier to discuss quickly on Monday morning.
___
*[`pkg/kv/kvserver/replicate_queue_test.go` line 2516 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVFrUl2uluCSDVg6i2:-NsVFrUl2uluCSDVg6i3:b-l7ivmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replicate_queue_test.go#L2516)):*
> ```Go
> 
> 	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{
> 		ReplicationMode: base.ReplicationManual,
> ```

nit: add `DisableSQLServer` to make this test slightly faster.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119155)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/allocator/plan/lease.go` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVBk582vgohxJKbi8T:-Nsi_TVE1I7DWUP7TgWU:b-anatfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/allocator/plan/lease.go#L69)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Can you check with @erikgrinaker if this is still required. It might not be since `shouldRequestLeaseRLocked` is called as part of the `tick` loop, but maybe we still need it for quiesced epoch leases. That said, I guess its OK to leave it here regardless. Maybe add a comment that this is only necessary when they change the lease time from epoch to expiration and this could be deleted in the future if we don't support epoch leases anymore.
</blockquote></details>

Yes, it's still required -- otherwise quiesced ranges won't switch to expiration leases when the `kv.expiration_leases_only.enabled` setting changes (at least not until the ranges unquiesce for some reason).

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-:-NsioBNF63w7Mz3oy-1b:bx5oinu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/lease_queue.go` line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU3P_06dc-FahcOyrE:-NsihEbF5t8osZ5GTCJt:b-robrsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/80272e69eb7536c24db87fec6d85a82fb9ce463d/pkg/kv/kvserver/lease_queue.go#L33)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: You introduce the metrics and add the metadata for them in the first commit and then add them in the next one. 

Consider moving some of this to the next commit or alternatively just squashing them together. 

It would probably be best to introduce all the metrics in this commit even though they would always be zero.
</blockquote></details>

This metrics struct wasn't being used. All the metrics are introduced in the first commit and would be updated to zero.
___
*[`pkg/kv/kvserver/lease_queue.go` line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU4x2O9zNm0CjACyV6:-Nsign3ZCRbwRDWpMkqG:b-iuenjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L44)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I don't love that this setting is in terms of absolute time, but I don't necessarily have a good alternative. Also 1s seems long to me, but I don't know what the right value is (100ms?) Consider adding language that says it can be set to 0 to disable waiting between lease transfers. I'd be curious to look at the implications for different values of this for a large cluster. However this is just keeping the old behavior, so feel free to disregard (or just leave a TODO).
</blockquote></details>

There is already an issue which references this problem https://github.com/cockroachdb/cockroach/issues/115614. I added a TODO which references the issue.
___
*[`pkg/kv/kvserver/lease_queue.go` line 135 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU5A5_DH7Z3NicRgjv:-NsihPzo2gZP5BRd_0RJ:bif7ajz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L135)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

consider moving this up. I think we should count it as a lease transfer from a pacing perspective even if this transfer fails. That will help us from busy looping if the lease can't be transferred due to some other reason that is outside of the queues control. I think this can be set on the first line even before we attempt to acquire the token.
</blockquote></details>

This is consistent with the existing behavior -- good idea on moving it up. Moved it up above the transfer attempt.
___
*[`pkg/kv/kvserver/lease_queue.go` line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU69amDN1poKVkr4WD:-NsihzGl5ZpwO5dL89TE:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L169)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This should be rare that this line is hit. We already specified in the `queueConfig` that this queue requires a lease, so this check is redundant. I think it can be safely removed and might be simpler to follow in case the lease does transfer just at the wrong time since we it will be more clear in the logging that attempts to move the lease.
</blockquote></details>

Removed.
___
*[`pkg/kv/kvserver/replica_command.go` line 4046 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU79LhAIkPO5aiBu_Y:-Nsij_OB3sxQy7vOzjqO:bb34ioe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_command.go#L4046)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Should this go through the lease queue (with skipShoudQueue)? Otherwise we aren't checking against the allocator token.
</blockquote></details>

Good point, although the scatter doesn't go through the traditional method to select a lease target, it just randomly selects a lease target here from the list of valid targets. I've updated this code to acquire a token.
___
*[`pkg/kv/kvserver/replica_init.go` line 186 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU7qZx3U0jP2Th6N7q:-Nsik4_61PlXoMapbUFO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_init.go#L186)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This is now initialized twice.

nit: I think it would be best to just put this into the construction of the Replica above rather than setting it down here. but I don't really mind either way.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_proposal.go` line 557 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU8O51-AjwOF98is5h:-Nsik5jO1tZcB1ONFGVH:bbl13lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replica_proposal.go#L557)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I know there was a discussion about also queueing up less preferred priorities. Don't add to this PR, but maybe we add them with a lower priority to the queue in a follow-up?
</blockquote></details>

Yeah sounds good, I'll follow up with enqueueing less preferred priorities in a later PR after all this goes in https://github.com/cockroachdb/cockroach/issues/116081.
___
*[`pkg/kv/kvserver/allocator/plan/lease.go` line 69 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVBk582vgohxJKbi8T:-NsikEl3ARvmMhuo7FPf:b-r6wlm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/allocator/plan/lease.go#L69)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yes, it's still required -- otherwise quiesced ranges won't switch to expiration leases when the `kv.expiration_leases_only.enabled` setting changes (at least not until the ranges unquiesce for some reason).
</blockquote></details>

Ack. Added a comment about why this is necessary here.
___
*[`pkg/kv/kvserver/allocator/plan/lease.go` line 149 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVDiIO3M4Fof-QS048:-Nsikk6w5ovYWx-kUYiR:b6abxe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/allocator/plan/lease.go#L149)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This might just be a movement of existing code, but I don't really understand when we are using `FollowTheWorkload` vs `LeaseCountConvergence`. This might be easier to discuss quickly on Monday morning.
</blockquote></details>

We always use FollowTheWorkload unless we are shedding the lease. I'm not sure on the original context as to why we separated the two, but it would make sense that for bulk transfers (like when shedding for a drain), we'd care less about locality. Note follow the workload also accounts for lease counts via weighting them by latency + QPS from the locality.
___
*[`pkg/kv/kvserver/replicate_queue_test.go` line 2516 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsVFrUl2uluCSDVg6i2:-NsilB8oD4u4CxXMh3Sv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/replicate_queue_test.go#L2516)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: add `DisableSQLServer` to make this test slightly faster.
</blockquote></details>

Done.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

> Reviewed 4 of 38 files at r8, 3 of 34 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-:-NsjQirJ10yUQwoBohwK:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/lease_queue.go` line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU4x2O9zNm0CjACyV6:-NsjGZR1APy4DrOV3RVQ:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L44)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

There is already an issue which references this problem https://github.com/cockroachdb/cockroach/issues/115614. I added a TODO which references the issue.
</blockquote></details>

Thanks
___
*[`pkg/kv/kvserver/lease_queue.go` line 135 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU5A5_DH7Z3NicRgjv:-NsjGbjtANouVghG1J8o:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L135)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This is consistent with the existing behavior -- good idea on moving it up. Moved it up above the transfer attempt.
</blockquote></details>

Thanks
___
*[`pkg/kv/kvserver/lease_queue.go` line 169 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119155#-NsU69amDN1poKVkr4WD:-NsjGeNl154BiLT8ESPc:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c81e4cdc73bab3ed89c17eaf175ace212fde49/pkg/kv/kvserver/lease_queue.go#L169)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Thanks

**Comment by kvoli** [comment]
TYFTR

bors r=andrewbaptist

**Pull request merged**
