### PR TITLE
rocksdb: bump ref to pickup MockEnv fix

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

Does this fix any open issues?

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45584#-:-M1R6xVaDBlidvwNsl92:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by sumeerbhola — COMMENTED** [review]
> Does this fix any open issues?

Thanks for reminding. Added to the commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45584#-:-M1RWz3t6MglccR_DZ5F:b-e2a0a4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
