### PR TITLE
storageccl: address comments about key_rewriter

### PR DESCRIPTION
**Pull request by madelynnblue**
This is renames, refactors, and comment improvements that would
have gone into the listed PR, but didn't due to the 1.0 cutoff
timeframe. There should be no user-facing changes in this PR.

See #15564

### CODE REVIEW

**Comment by danhhz** [comment]
LGTM though merging this should wait until after we branch 1.0

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15665#-KjEqEJvU3ITuf_Z677H:-KjEqEJvU3ITuf_Z677I:b46itgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63878f64aa7a785747eac56b82bc44a6b0b74e2/pkg/ccl/storageccl/key_rewriter.go#L167)):*
> ```Go
> 	}
> 	colIDs, _ := idx.FullColumnIDs()
> 	// TODO(mjibson): We should be able to use
> ```

Now that there's no time crunch, let's actually figure this out instead of TODOing it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15665#-:-KjEq60ERKsd0vND5Ndh:bcjurwq)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/storageccl/key_rewriter.go, line 167 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15665#-KjEqEJvU3ITuf_Z677H:-KjdDpUURsb-06oxbKyL:bxe6qad) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63878f64aa7a785747eac56b82bc44a6b0b74e2/pkg/ccl/storageccl/key_rewriter.go#L167)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Now that there's no time crunch, let's actually figure this out instead of TODOing it
</blockquote></details>

This was working correctly, I was doing something wrong. RFAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15665)*

**Comment by mjibson** [comment]
Ping @danhhz

**Comment by danhhz** [comment]
LGTM

**Pull request merged**
