### PR TITLE
catalog: remove errors from Descriptor methods

### LINKED ISSUE #91924: sql/catalog: stop returning errors from lookup functions
**Is your feature request related to a problem? Please describe.**

There are a bunch of functions like `FindColumnByName` which return an error. These errors are not cheap to construct. We should return booleans rather than errors and then make a family of functions which turn false into the same error. We've seen performance problems where code just nil checks errors and it causes problems.

### PR DESCRIPTION
**Pull request by postamar**
Each of these is typically replaced by a couple of functions in the catalog package, one which returns an error and another which doesn't. Error creation is expensive and should be avoided in the hot path.

Fixes #91924.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This refactor is ready for review. See issue description for rationale.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 12 of 12 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 7 of 7 files at r4, 51 of 51 files at r5, 15 of 15 files at r6, 9 of 9 files at r7, 81 of 81 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95069#-:-NM2KWagCF2q6yb-Jewe:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/catalog/table_elements.go` line 1161 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/95069#-NM2JDRY1ULyXDiZ-CZR:-NM2JDRY1ULyXDiZ-CZS:brhz4jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b81300d016c124b792755df199a6b5561c3d2b3/pkg/sql/catalog/table_elements.go#L1161)):*
> ```Go
> 		return f, nil
> 	}
> 	return nil, fmt.Errorf("family-id \"%d\" does not exist", id)
> ```

The contract regarding which errors are allowed to make it to the end user and which are not is not very well defined. In previous functions you refactored, the errors had pgcodes, this one doesn't. I know you're not changing anything here, just food for thought.

**Comment by postamar** [comment]
Thanks for the review!
bors r+

**Pull request merged**
