### PR TITLE
Update rocksdb to 5.9

### PR DESCRIPTION
**Pull request by mberhault**
There are still a few SSE patches to apply (see https://github.com/cockroachdb/rocksdb/commits/nvanbenschoten/fixArm)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19824#-:-KyGsahFHgrNViVJbfBX:bnfp4nl)*

**Comment by benesch** [comment]
@mberhault want me to cherry-pick the ARM fixes since I'm planning to upstream them anyway?

**Comment by mberhault** [comment]
That would be nice. I took a quick peek, and it looks like they're going to conflict.

**Comment by nvanbenschoten** [comment]
@benesch which ARM fixes are you planning on upstreaming? The upstream [`crc32c.cc`](https://github.com/facebook/rocksdb/blob/master/util/crc32c.cc) is pretty different than the old revision we were working on, and I think https://github.com/facebook/rocksdb/commit/5449c0990b32ac0fcc69faeed9bada5ff1fa4a8a already addressed the same issue that #19795 did. There might not be anything to do on our end.

**Comment by benesch** [comment]
Yeah, they added fast-CRC32 on PPC support upstream. which is why the file looks so different. The underlying problem I was trying to solve is still there, though. If you compile across the board with `-msse4.2`, like RocksDB does when you say `USE_SSE42=1`, GCC will toss some SSE4.2 instructions in other files which aren't guarded by a runtime `cpuid` check. So it's a complete waste to guard the CRC32 instructions behind a `IsFastCrc32Supported` check, because the binary will crash in other SSE4.2-using functions on older CPUs. `target("sse4.2")` solves that, but it broke the ARM build until you fixed it.

**Comment by benesch** [comment]
Ok, here's a patch for 5.9: https://github.com/benesch/rocksdb/tree/5.9-sse

@nvanbenschoten could you verify that works on ARM?

**Comment by nvanbenschoten** [comment]
@benesch yeah, I'll check it out tonight. Thanks for putting that together!

**Comment by nvanbenschoten** [comment]
Report back from ARM-land: compilations succeed with this change as-is and with @benesch's patch!

**Review by a-robinson — APPROVED** [review]

**Comment by mberhault** [comment]
Should we merge this and separately patch `cockrochdb/rocksdb`, or would you prefer I wait until the patch is in?

**Comment by benesch** [comment]
@mberhault I just pushed my patch to the crl-release-5.9.0 branch, so you should be able to update this PR to point at the new tip of that branch.

**Comment by mberhault** [comment]
Thanks. Updated to tip. I'll wait for a green build.

**Comment by mberhault** [comment]
Build's green. PTAL.

**Pull request merged**
