### PR TITLE
opt: Add additional decorrelation rules

### PR DESCRIPTION
**Pull request by andy-kimball**
Add more decorrelation rules needed for the Hibernate test suite:

- TryDecorrelateSemiJoin maps a SemiJoin to an equivalent GroupBy/
    InnerJoin complex in hopes of triggering further rules that will
    ultimately decorrelate the query.

- TryDecorrelateProjectInnerJoin tries to decorrelate by hoisting the
    filter of an InnerJoin operator that sits below a LeftJoin/Project
    operator combo.

Also fix a couple bugs with existing decorrelation rules.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-:-LI6fp5o0eXZUPiiKRaM:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI6efygEQGBw7yjxMYc:-LI6efyhDIBCJq79lC67:b-rm8nz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa9cd1be9651eebeb947034b0fea65c676720375/pkg/sql/opt/norm/rules/decorrelate.opt#L170)):*
> ```
> =>
> (Project
>     ((OpName)
> ```

[nit] `LeftJoinApply`

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r3, 8 of 8 files at r5, 2 of 2 files at r6, 6 of 6 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-:-LI75T1zDthn80OtRpD3:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 300 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI73LKF7xZpzS0BZrsb:-LI73LKF7xZpzS0BZrsc:b-4dvn6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/decorrelate.go#L300)):*
> ```Go
> //   (Aggregations
> //     [(Sum (Variable 4)) (AnyNotNull (Variable 2)) (AnyNotNull (Variable 3))]
> //     [2,3]
> ```

shouldn't this list contain one more element?
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 122 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI7-GnBDjFV3jO-B8ib:-LI7-GnBDjFV3jO-B8ic:b-pr8iex) ([raw file](https://github.com/cockroachdb/cockroach/blob/10bff08ddcc296c48cc112fe5adee808e9b8ee7d/pkg/sql/opt/norm/rules/decorrelate.opt#L122)):*
> ```
> # DetectCycle and HighPriority tags are in use.
> [TryDecorrelateProjectSelect, Normalize, DetectCycle, HighPriority]
> (LeftJoinApply
> ```

Why did you remove LeftJoin? (Ditto below)
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 365 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI74eai7pesfcySrCyR:-LI74eai7pesfcySrCyS:b-et6bpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/rules/decorrelate.opt#L365)):*
> ```
>     $right:* &
>         (HasOuterCols $right) &
>         ^(HasOneOrMoreRows $right) & # Let EliminateExistsGroupBy match instead.
> ```

[nit] This is a bit confusing since it looks like $right must have zero rows

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 300 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI73LKF7xZpzS0BZrsb:-LI7FVs-9ATLSjm2yBnA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/decorrelate.go#L300)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't this list contain one more element?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 122 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI7-GnBDjFV3jO-B8ib:-LI7FY2nEIZYE2CnBIol:b-4wiwsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/10bff08ddcc296c48cc112fe5adee808e9b8ee7d/pkg/sql/opt/norm/rules/decorrelate.opt#L122)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you remove LeftJoin? (Ditto below)
</blockquote></details>

Because this rule is really only useful in the case where the `Select` outer columns refer to the $left columns. And that's never true in the `LeftJoin` case. And therefore, because I couldn't come up with a test case where `LeftJoin` mattered, I decided to exclude it.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 365 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI74eai7pesfcySrCyR:-LI7GF9I3mMWNNjgpPaS:b-qsere) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/rules/decorrelate.opt#L365)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] This is a bit confusing since it looks like $right must have zero rows
</blockquote></details>

I changed the name to `CanHaveZeroRows` (and inverted usages), so it makes more sense in this context.

**Review by andy-kimball — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-:-LI7Itg5Am1AJLsnR39X:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 300 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI73LKF7xZpzS0BZrsb:-LI7Yxi96iS90q_D7vD4:btmy3wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/decorrelate.go#L300)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This shouldn't block this PR, but aren't these supposed to be the output columns of the Aggregations? So (Sum (Variable 4)) would have an output column id that's not 4.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 300 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI73LKF7xZpzS0BZrsb:-LI7_LKyCjR5rQruEQKi:brdl6qf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/decorrelate.go#L300)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This shouldn't block this PR, but aren't these supposed to be the output columns of the Aggregations? So (Sum (Variable 4)) would have an output column id that's not 4.
</blockquote></details>

Ah, true, should be 5, or something. I can throw in fix in my next PR.

**Review by rytaft — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 300 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27830#-LI73LKF7xZpzS0BZrsb:-LI7_gNy89oDzKBZ46zn:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d105d4440e06602c794577046f4659d75ceea22/pkg/sql/opt/norm/decorrelate.go#L300)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ah, true, should be 5, or something. I can throw in fix in my next PR.
</blockquote></details>

:thumbsup:

**Pull request merged**
