### PR TITLE
cli,server: fix --sql-advertise-addr when --sql-addr is not specified

### LINKED ISSUE #87040: --sql-advertise-addr has no effect if you don't also set --sql-addr alongside it
**Describe the problem**

I tried setting `--sql-advertise-addr` on a cluster purely in order to improve the output of `cockroach node status` and related debug endpoints so that they would include a useful identifying hostname that makes reading their output easier (the cluster is using IP addresses for its normal listen/advertise addr for reasons that are unimportant here). But found that it had zero effect, not even in the initial "CockroachDB node starting at ..." message that gets printed out when a node starts up. The non-sql `--advertise-addr` was instead used as the advertised SQL address.

And you can't cheekily work around it by setting `--sql-addr` to the same thing as `--listen-addr`, because cockroach reasonably assumes that you want it to bind to the two addresses separately, so it fails to bind both during startup.

I previously mentioned this in https://github.com/cockroachdb/cockroach/issues/52266#issuecomment-985679803, but haven't personally take the time to fix it myself, so I'm creating a separate issue in case it's helpful given that it isn't really the same issue as #52266 and it bothered me again recently.

**To Reproduce**

```
cockroach start-single-node --insecure --listen-addr 127.0.0.1 --advertise-sql-addr localhost
```

**Expected behavior**
I'd expect the various places that the SQL address is printed such as the `cockroach start` output and `cockroach node status` to use `localhost` in the SQL address, but both use `127.0.0.1`. 

**Additional data / screenshots**

```
$ cockroach start-single-node --insecure --listen-addr 127.0.0.1 --advertise-sql-addr localhost
[...]
CockroachDB node starting at 2022-08-29 15:44:58.872696991 +0000 UTC (took 0.8s)
build:               CCL v22.1.6 @ 2022/08/23 17:05:04 (go1.17.11)
webui:               http://127.0.0.1:8080
sql:                 postgresql://root@127.0.0.1:26257/defaultdb?sslmode=disable
sql (JDBC):          jdbc:postgresql://127.0.0.1:26257/defaultdb?sslmode=disable&user=root
RPC client flags:    cockroach <client cmd> --host=127.0.0.1:26257 --insecure
[...]
```

```
$ cockroach node status --insecure
  id |     address     |   sql_address   |  build  |        started_at         |         updated_at         | locality | is_available | is_live
-----+-----------------+-----------------+---------+---------------------------+----------------------------+----------+--------------+----------
   1 | 127.0.0.1:26257 | 127.0.0.1:26257 | v22.1.6 | 2022-08-29 15:44:58.67473 | 2022-08-29 15:51:12.196074 |          | true         | true
(1 row)
```

**Environment:**
 - CockroachDB version: v22.1.6
 - Server OS: Linux

Jira issue: CRDB-19116

### PR DESCRIPTION
**Pull request by knz**
Fixes #87040.
Informs #52266.

cc @a-robinson 

Release justification: bug fix

Release note (bug fix): The flag `--sql-advertise-addr` now properly
works even when the SQL and RPC ports are shared (because `--sql-addr`
was not specified). Note that this port sharing is a deprecated
feature in v22.2.

### CODE REVIEW

**Comment by knz** [comment]
sorry about the garbage PR title, correct.

**Review by a-robinson — APPROVED** [review]
Thanks @knz !

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by knz** [comment]
TFYRs!

bors r=a-robinson,ajwerner

**Pull request merged**
