### PR TITLE
build: use gsutil to upload the artfacts from nightly tests

### PR DESCRIPTION
**Pull request by danhhz**
While I'm in here, clean up the scripts a bit.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

Let's file an issue to remove `roachprod upload` (or just remove it).

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/nightly-workload.sh, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263#-L4Cqq48FGS3l0NG7LLo:-L4Cqq48FGS3l0NG7LLp:b-1sxncy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0857076dcffd25507d0109d2734eff08340bfb4e/build/nightly-workload.sh#L15)):*
> ```Shell
> # curl -L https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.LATEST -o cockroach-linux-2.6.32-gnu-amd64
> # chmod +x cockroach-linux-2.6.32-gnu-amd64
> cp cockroach-linux-2.6.32-gnu-amd64 cockroach
> ```

Any reason you're using `cp` here instead of `mv`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263#-:-L4CrJOgFFvEB4oQphsM:b-9xbn59)*

**Comment by danhhz** [comment]
https://github.com/cockroachdb/roachprod/issues/40

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/nightly-workload.sh, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263#-L4Cqq48FGS3l0NG7LLo:-L4CxRWdHWQkKbwJyAI7:b-4s3vhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0857076dcffd25507d0109d2734eff08340bfb4e/build/nightly-workload.sh#L15)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Any reason you're using `cp` here instead of `mv`?
</blockquote></details>

no particular reason

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263#-:-L4CxPyojYNncl9g0OnU:bz508yp)*

**Comment by danhhz** [comment]
TFTR! I can switch the `cp` to a `mv` in a followup if you like

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/nightly-workload.sh, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263#-L4Cqq48FGS3l0NG7LLo:-L4Dv4Cjgt9cACnOs6Ka:bvse5za) ([raw file](https://github.com/cockroachdb/cockroach/blob/0857076dcffd25507d0109d2734eff08340bfb4e/build/nightly-workload.sh#L15)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

no particular reason
</blockquote></details>

Seems unnecessary. On the other hand, Tobias and I were thinking that the nightly tests should have a flag specifying the binary so this will probably get fixed in another way soon. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22263)*

**Pull request merged**
