### PR TITLE
[CRDB-8488] ui: add alert banner on overview list page for staggered node versions

### PR DESCRIPTION
**Pull request by Santamaura**
Users wish to see more info related to how the progress of a cluster upgrade
is going. Since we do not have a cluster upgrade status to use we are
instead showing an alert banner on the overview page when there are more
than one node versions detected. This alert banner lists the node versions
detected and how many nodes are on each version. This is a non-critical
alert and can be dismissed.

Release note (ui change): add alert banner on overview list page for
staggered node versions

Related issue: https://github.com/cockroachdb/cockroach/issues/67330

Release justification: Low risk ui changes with improved QoL results

Screen Shot 2022-02-23 at 2 16 34 PM

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx05Wt56va1SZyE0D4c:-Mx05Wt56va1SZyE0D4d:b-xf60h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L159)):*
> ```XML
>       should be investigated if this is unexpected.`,
>       dismiss: (dispatch: AppDispatch) => {
>         dispatch(staggeredVersionDismissedSetting.set(true));
> ```

I'm a bit confused about the two warning selectors. does dismissing one dismiss both? should we just make both alerts show the same message?
___
*[pkg/ui/workspaces/db-console/src/redux/nodes.ts, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx04AtLEh_pbrrZV-F7:-Mx04AtLEh_pbrrZV-F8:b-y4o6nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/nodes.ts#L496)):*
> ```XML
>   nodes => {
>     if (!nodes) {
>       return undefined;
> ```

why not return an empty map?
___
*[pkg/ui/workspaces/db-console/src/redux/nodes.ts, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx04et9493szL93-7Ys:-Mx04et9493szL93-7Yt:bvh7qcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/nodes.ts#L500)):*
> ```XML
>     const versionsMap = new Map();
>     nodes.forEach(node => {
>       if (!node?.build_info?.tag) {
> ```

if you want, you can use `_.countBy` as a shortcut

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @koorosh, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx05Wt56va1SZyE0D4c:-Mx0eNAX0N7bSwMXcAOm:b-cdlntt) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L159)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm a bit confused about the two warning selectors. does dismissing one dismiss both? should we just make both alerts show the same message?
</blockquote></details>

Yeah since the warning banners information is about similar things I thought it made sense when a user dismisses one of them to also dismiss the other. @thtruo @annebirzin What are your thoughts on if we should make both of them show the same message?
___
*[pkg/ui/workspaces/db-console/src/redux/nodes.ts, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx04AtLEh_pbrrZV-F7:-Mx0ekcY5BUtHF6Invph:b-hk1ers) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/nodes.ts#L496)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why not return an empty map?
</blockquote></details>

Agree, it makes more sense to return empty map.
___
*[pkg/ui/workspaces/db-console/src/redux/nodes.ts, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx04et9493szL93-7Ys:-Mx0er9y1nKIU0K1YqYU:bivm7dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e48bf84999ef633caf6fcacd5983b65cd65eed/pkg/ui/workspaces/db-console/src/redux/nodes.ts#L500)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

if you want, you can use `_.countBy` as a shortcut
</blockquote></details>

Well TIL, very useful. Thanks!

**Comment by Annebirzin** [comment]
@Santamaura Good call, I think that does make sense to apply the same message to the warning on the metrics page. fyi @thtruo

**Review by koorosh — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @Santamaura, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx, line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx8lw_G1dzicRmVSl-l:-Mx8lw_G1dzicRmVSl-m:bp1sa86) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx#L315)):*
> ```XML
>         <Helmet title="Cluster Overview" />
>         <EmailSubscription />
>         <OverviewListAlerts />
> ```

@santamaura , should it  be inline warning message or as floating alert banner (top-right corner)? 
See `pkg/ui/workspaces/db-console/src/views/app/containers/alertBanner/index.tsx` component

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @koorosh, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx, line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx8lw_G1dzicRmVSl-l:-MxABC7zD7ncdKQwyutq:b28sx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx#L315)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@santamaura , should it  be inline warning message or as floating alert banner (top-right corner)? 
See `pkg/ui/workspaces/db-console/src/views/app/containers/alertBanner/index.tsx` component
</blockquote></details>

Based on the selectors used with that component I believe it is used for more critical level alerts.

**Review by koorosh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @Santamaura, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-MxZIZvL3B1fMloQoRii:-MxZIZvL3B1fMloQoRij:bycjubd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L139)):*
> ```XML
>  * This excludes decommissioned nodes.
>  */
> export const staggeredVersionWarningCountSelector = createSelector(
> ```

What is the reason of renaming this function to staggeredVersionWarning**Count**Selector? It doesn't return number of staggered versions as I understand.
___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-MxZJaPGDcNjXeu1pnv6:-MxZJaPGDcNjXeu1pnv7:bh00hww) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L152)):*
> ```XML
> 
>     let versionsText = "";
>     versionsMap.forEach((value, key) => {
> ```

This `forEach` construction can be simplified in more functional and readable way:
``` typescript
let versionsText = Array.from(versionsMap)
      .map(([k, v]) => `${v} nodes are running on ${k}`)
      .join(" and ")
      .concat(". ");
```
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx, line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx8lw_G1dzicRmVSl-l:-MxZMxoX1iULF_EvCMzZ:bzo2bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx#L315)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Based on the selectors used with that component I believe it is used for more critical level alerts.
</blockquote></details>

I meant to incorporate your new alerts with existing `panelAlertsSelector` to display non-critical alerts:
``` typescript
/**
 * Selector which returns an array of all active alerts which should be
 * displayed in the alerts panel, which is embedded within the cluster overview
 * page; currently, this includes all non-critical alerts.
 */
export const panelAlertsSelector = createSelector(
...
```

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @koorosh, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-MxZIZvL3B1fMloQoRii:-Mxe2NWO2mx_zf6vQq5k:b-52b8r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L139)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

What is the reason of renaming this function to staggeredVersionWarning**Count**Selector? It doesn't return number of staggered versions as I understand.
</blockquote></details>

I guess I was thinking, it's a selector for showing the versions by node count so added count. I reverted to the old name (I think that one should be ok).
___
*[pkg/ui/workspaces/db-console/src/redux/alerts.ts, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-MxZJaPGDcNjXeu1pnv6:-Mxe2ZNq0MPT2NPclpwh:b-515vg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L152)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

This `forEach` construction can be simplified in more functional and readable way:
``` typescript
let versionsText = Array.from(versionsMap)
      .map(([k, v]) => `${v} nodes are running on ${k}`)
      .join(" and ")
      .concat(". ");
```
</blockquote></details>

Thanks for the optimization :smile: 
___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx, line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx8lw_G1dzicRmVSl-l:-Mxe2bkfEQpykBg50gR2:b-4afpdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx#L315)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I meant to incorporate your new alerts with existing `panelAlertsSelector` to display non-critical alerts:
``` typescript
/**
 * Selector which returns an array of all active alerts which should be
 * displayed in the alerts panel, which is embedded within the cluster overview
 * page; currently, this includes all non-critical alerts.
 */
export const panelAlertsSelector = createSelector(
...
``` 


</blockquote></details>

So if we use this selector we might have a scenario where the new version banner shows up which I don't think we want in that area of the overview list page.

**Review by koorosh — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76932)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @dhartunian, @thtruo, and @zachlite)

___
*[pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx, line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76932#-Mx8lw_G1dzicRmVSl-l:-MxoDd86BPtLeGX9XYNQ:b-xavg35) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ef59dd79f1c7d28fc2d62d66e85e0b52b27e47/pkg/ui/workspaces/db-console/src/views/cluster/containers/clusterOverview/index.tsx#L315)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

So if we use this selector we might have a scenario where the new version banner shows up which I don't think we want in that area of the overview list page.
</blockquote></details>

I thought these banners can stack up... in this case you're right!

**Comment by jocrl** [comment]
Hello! I'd like to reuse this to address https://github.com/cockroachdb/cockroach/issues/77535, but noticed that this only adds the banner to DB Console, and not CC Console.

Does this issue not apply to CC Console/is there a separate PR for that? It seems like customers would want cluster upgrade information in CC Console as well.

@Santamaura

**Comment by Annebirzin** [comment]
@jocrl Just for context, on ticket #77535 we decided to go with a more generic message for the SQL Activity tab since in CC console users don't have much context about specific nodes and their versions. (Dedicated has a very simple node list but does not list out versions, Serverless does not show anything about nodes). The users of CC console wouldn't be able to do much with the specific knowledge of nodes/versions unless they went to DB console.

**Pull request merged**
