### PR TITLE
debug: add plan generator for statement-bundle

### PR DESCRIPTION
**Pull request by jordanlewis**
debug: add plan generator for statement-bundle

```
This commit adds a way to generate alternate optimal plans for a
statement bundle, by replacing each placeholder in the bundle's
statement with all of the different histogram values for the
placeholder's column, and doing this for all combinations with all of
the placeholders.

If the statement in the bundle uses only equality constraints on
columns, all optimal plans will be generated. If the statement uses
inequality constraints, or other constraints that aren't simple equality
constraints between a placeholder and an indexed column, it's not
guaranteed that all optimal plans will be generated.

Each optimal plan is run in the demo cluster via explain, and
deduplicated, so that the result is all unique plans for all of the
combinations above.

To use this, you must pass in the mapping from placeholder number to
fully-qualified column name that is available in the statistics files of
the statement bundle.

Here is an example of the usage:

./cockroach debug statement-bundle recreate bundledir --placeholder='1=public.a.a' --placeholder='2=public.a.b'

This usage will replace each usage of the placeholders 1 and 2 with all
combinations of the values in the histograms for the columns public.a.a
and public.a.b respectively.

Each of the optimal plans is printed to standard out, and the user is
dropped into the demo environment.

The EXPLAIN style used to produce the final output can be customized
with the `--explain-cmd` flag.

Release note: None
```

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Amazing work putting this together so quickly! This is going to be incredibly useful.

> Reviewed 6 of 6 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-:-MfYPzwI4UGtNDHkzBUb:br37lc6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/cli/statement_bundle.go, line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYI-skDdSHSXoCgUcY:-MfYI-sl192ekMYO24cR:byvuhxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L201)):*
> ```Go
> 		pair := strings.Split(placeholderPairStr, "=")
> 		if len(pair) != 2 {
> 			return errors.New("use --placeholder='1=schema.table.col 2=schema.table.col...'")
> ```

Isn't this the wrong format? don't you want just one arg per `--placeholder`?
___
*[pkg/cli/statement_bundle.go, line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYIpTMCCNp__64jz1b:-MfYIpTNB_GTqGe9nyLq:bwiz5oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L216)):*
> ```Go
> 	var stmtPlaceholders []int
> 	for _, line := range strings.Split(placeholders, "\n") {
> 		if matches := placeholderRe.FindStringSubmatch(line); len(matches) == 3 {
> ```

Would help to add a comment to explain why `len(matches)` should be 3.
___
*[pkg/cli/statement_bundle.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYLPbd9wE6kxvcg_4C:-MfYLPbi3x2Fb88uq_sv:bn4gx3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L268)):*
> ```Go
> 					NumEq:         int64(bucket["num_eq"].(float64)),
> 					NumRange:      int64(bucket["num_range"].(float64)),
> 					DistinctRange: bucket["distinct_range"].(float64),
> ```

Why are you casting NumEq and NumRange to int64 but not DistinctRange? I forget what we do when generating histograms -- have you checked that NumEq and NumRange are always integers?
___
*[pkg/cli/statement_bundle.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYO75H5ZYDCGoWvd3n:-MfYO75I5cHrIrdwdZul:b-i5vclr) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L274)):*
> ```Go
> 			upperBounds := make([]string, 0, len(bucketMap))
> 			for _, upperBound := range bucketMap {
> 				upperBounds = append(upperBounds, upperBound)
> ```

This may only cover half the plans. If `NumRange` for this bucket is greater than 0, you could consider using the known upper bound type (from `stat["histo_col_type"]`) to cast this to a datum and then call `Datum.Prev()` to get the previous value. 

In case it's useful, here's where we extract the upper bound as a datum for the test catalog: https://github.com/cockroachdb/cockroach/blob/314261f7963287676391ca586e5d9f7328a5dbe9/pkg/sql/opt/testutils/testcat/test_catalog.go#L1002
___
*[pkg/sql/opt/exec/explain/flags.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYNjRcALCdlwCfWXrw:-MfYNjRd6zoj_AT3QJxM:b-6syzii) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/sql/opt/exec/explain/flags.go#L31)):*
> ```Go
> 	// This is used for EXPLAIN(SHAPE), which is used for the statement-bundle
> 	// debug tool.
> 	OnlyShape bool
> ```

could this also be used for the plan hash work that @cucaroach is working on?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/cli/statement_bundle.go, line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYI-skDdSHSXoCgUcY:-MfYT2OGCVO4iZKNpmmA:bpafm56) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Isn't this the wrong format? don't you want just one arg per `--placeholder`?
</blockquote></details>

Either format works (Cobra parses these in the same way), but you're right we should just stick with the one in the commit msg. Fixed the error.
___
*[pkg/cli/statement_bundle.go, line 216 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYIpTMCCNp__64jz1b:-MfYTNs9AOsA0FnGF0bR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L216)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would help to add a comment to explain why `len(matches)` should be 3.
</blockquote></details>

Done.
___
*[pkg/cli/statement_bundle.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYLPbd9wE6kxvcg_4C:-MfYV_A63vwNut-L7KmN:b-ybf5fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L268)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why are you casting NumEq and NumRange to int64 but not DistinctRange? I forget what we do when generating histograms -- have you checked that NumEq and NumRange are always integers?
</blockquote></details>

They seem to always be integers, yes, but I'm not sure why I casted these in the first place, I removed it.
___
*[pkg/cli/statement_bundle.go, line 274 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYO75H5ZYDCGoWvd3n:-MfYg9xd-sqfnn2L1hQn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/cli/statement_bundle.go#L274)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This may only cover half the plans. If `NumRange` for this bucket is greater than 0, you could consider using the known upper bound type (from `stat["histo_col_type"]`) to cast this to a datum and then call `Datum.Prev()` to get the previous value. 

In case it's useful, here's where we extract the upper bound as a datum for the test catalog: https://github.com/cockroachdb/cockroach/blob/314261f7963287676391ca586e5d9f7328a5dbe9/pkg/sql/opt/testutils/testcat/test_catalog.go#L1002
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/explain/flags.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYNjRcALCdlwCfWXrw:-MfYW6RD6Hkd0rguPTdm:bf8t8md) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/sql/opt/exec/explain/flags.go#L31)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

could this also be used for the plan hash work that @cucaroach is working on?
</blockquote></details>

I'm not sure, I didn't think of that. Very possibly!

**Review by rytaft — APPROVED** [review]
:lgtm:

Not sure how this would work, but it would be great to add a test for this new debug command if possible (not sure how other similar changes are currently tested...).

This seems like something we should backport.

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-:-MfZHeQEEe9kYaJaWXkj:bqx1owr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @jordanlewis)

___
*[pkg/sql/sem/tree/explain.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfZHOeh6H65hW8G-bza:-MfZHOeh6H65hW8G-bzb:bvqlh7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/48acb839427d46b8b3d5b6d1e0ba888e43a6d537/pkg/sql/sem/tree/explain.go#L128)):*
> ```Go
> 	ExplainFlagDeps:    "DEPS",
> 	ExplainFlagMemo:    "MEMO",
> 	ExplainFlagShape:   "SHAPE",
> ```

Can you add a test for `EXPLAIN (SHAPE)`?

**Review by cucaroach — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/opt/exec/explain/flags.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfYNjRcALCdlwCfWXrw:-Mf_n8tx2zFXUWQzCMUS:boe9gku) ([raw file](https://github.com/cockroachdb/cockroach/blob/60916767c6d263bd502e1086e67d7b3f0e7ce5cf/pkg/sql/opt/exec/explain/flags.go#L31)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm not sure, I didn't think of that. Very possibly!
</blockquote></details>

The plan hash stuff as I'm currently imagining it will be very lightweight compared to the full explain machinery but I do plan on checking this out and there may be some overlap to think about when I get a little further along.

**Review by jordanlewis — COMMENTED** [review]
Added a sample bundle to test against. I wish I could get one with some weird stats easily, but I don't have a quick way to produce an artificial one that would have more than one plan... any ideas?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-:-Mfe0F488Lu3FBTCnpF0:bvtpp9k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @jordanlewis, and @rytaft)

___
*[pkg/sql/sem/tree/explain.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfZHOeh6H65hW8G-bza:-Mfe0Ebw5WNmuVEHlBkq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48acb839427d46b8b3d5b6d1e0ba888e43a6d537/pkg/sql/sem/tree/explain.go#L128)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a test for `EXPLAIN (SHAPE)`?
</blockquote></details>

Done.

**Comment by mgartner** [comment]
I think we should make it clear in the naming of the tool, its description, the commit message, etc. that it won't actually generate _all_ plans. A certain plan may only be generated with a placeholder value that is not in the the histogram range.

**Comment by jordanlewis** [comment]
> A certain plan may only be generated with a placeholder value that is not in the the histogram range.

@mgartner can you elaborate? Shouldn't it be possible to generate truly all plans? I was under the (mistaken?) assumption that all plans could be generated by taking a value from every histogram bucket. Do I also need to sample from before the first histogram bucket and after the last histogram bucket? Are there more things that would need to be done here?

**Review by rytaft — COMMENTED** [review]
> I don't have a quick way to produce an artificial one that would have more than one plan... any ideas?

You can reuse the stats from my recent PR: https://github.com/cockroachdb/cockroach/blob/f702cf57c5cf9bf35ec9552eed6f23f9c01e79c7/pkg/sql/opt/memo/testdata/stats/select#L3040
I think if you change the schema and query to look like the following, you should produce multiple plans:
```
CREATE TABLE ab (
  a INT,
  b INT,
  c INT,
  INDEX (a),
  INDEX (b)
);

SELECT * FROM ab WHERE a=$1 AND b=$1;
```

> Do I also need to sample from before the first histogram bucket and after the last histogram bucket?

That's a good point -- you should probably take a sample from before the first bucket (after the last bucket seems unnecessary to me)

> Reviewed 5 of 7 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-:-MfinT7UBjjsYcFpEa2q:biny4m2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/cli/statement_bundle.go, line 350 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfimFnE5G63lRmbrtrc:-MfimFnF2Q6eI2cWg0OZ:b-op5b0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f501b40109bd20a6732f82ef4fc5c48dac18ca10/pkg/cli/statement_bundle.go#L350)):*
> ```Go
> 	}
> 
> 	fmt.Println(statsMap)
> ```

Did you intend to include this? Or was this for debugging?

**Comment by mgartner** [comment]
> @mgartner can you elaborate? Shouldn't it be possible to generate truly all plans? I was under the (mistaken?) assumption that all plans could be generated by taking a value from every histogram bucket.

Using histogram values won't generate all plans for two reasons:

1. The set of all plans is a function of the set of all placeholder values. The set of all placeholder values is much larger than the set of all histogram bucket values. For example, the `a INT` might only have values `[0, 100]` in a table, but a user can query `WHERE a > 200`. Also, in theory there could be a plan that is only chosen with a value in a histogram's range (not an exact upper bound value). I doubt this would come up often, if at all, in practice, though.
2. Stats are _always_ stale, unless writes stop completely. So it's common for there to be values in the table that are not contained by any histogram buckets. So the user might be searching for a value that _is_ in the table, but _is not_ in the histogram. This comes up often in customer issues. See #64570.

> Do I also need to sample from before the first histogram bucket and after the last histogram bucket? Are there more things that would need to be done here?

I think you'd cover a lot of plans if you pick some values outside the range of the histogram. Using the same `a INT` in `[0, 100]` example, it would be nice to pick some placeholders some delta away from the min and max bucket. This might be easy for some types, like integers, but harder for others. 

For now, I think you can merge as-is as long as it's clear that _all_ plans won't necessarily be generated.

**Comment by jordanlewis** [comment]
I'm still confused though - I agree that there are a lot of values (infinite for some datatypes!) outside of the range of the histograms. But I thought based on conversations with @rytaft that a particular value in a particular bucket (or, in this case, in no bucket at all) would be treated by the optimizer as the same value as any other value in that bucket. Is that false?

Like in your example, where there's a table with `[0, 100]`, there will be a bunch of histogram buckets. I thought the idea, though, was that if I picked `200` to set the placeholder to, that would guarantee that the optimizer would generate the same plan as if I picked `300`, or any value greater than `100`, which is the maximum value in the histogram. (Of course the spans would be different! But when I say "all plans" here I mean all plans that have the same shape, spans nonwithstanding.)

**Comment by rytaft** [comment]
If all placeholders are used in equality conditions (e.g., `x = $1`) then I think your solution will produce all possible plans (assuming you make the change to add at least one value that is outside the range of the histogram). But @mgartner makes a good point about range predicates. If any placeholder is part of a range predicate (e.g., `x > $1`) then all bets are off. In this case, we'll probably want to be deliberate about choosing a few values to cover the whole range of the histogram.

But I'm also fine with leaving that enhancement for later...

**Comment by jordanlewis** [comment]
Oh, I see. Sorry, I somehow skimmed over the range predicate in your example, @mgartner. Yeah... woof. Okay, I'll postpone that for later and change this PR to talk about equality predicates only.

**Comment by mgartner** [comment]
> If all placeholders are used in equality conditions (e.g., x = $1) then I think your solution will produce all possible plans **(assuming you make the change to add at least one value that is outside the range of the histogram)**.

This change still needs to be made too, correct?

> But @mgartner makes a good point about range predicates. If any placeholder is part of a range predicate (e.g., x > $1) then all bets are off.

> Oh, I see. Sorry, I somehow skimmed over the range predicate in your example, @mgartner.

Heh, that wasn't a specific point I was trying to make, but I'm glad my example helped get more clarity.

**Comment by jordanlewis** [comment]
> I think if you change the schema and query to look like the following, you should produce multiple plans:

I was unable to produce multiple plans using this schema, stats and query. All combinations of placeholders seemed to produce the same plan (confirmed in my SQL shell as well as the tool):

```
demo@127.0.0.1:26257/defaultdb> explain SELECT * FROM ab WHERE a = 1 and b = 10000;
                                          info
----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ estimated row count: 1
  │ filter: b = 10000
  │
  └── • index join
      │ estimated row count: 1
      │ table: ab@primary
      │
      └── • scan
            estimated row count: 1 (100% of the table; stats collected 36 seconds ago)
            table: ab@ab_a_idx
            spans: [/1 - /1]
(15 rows)
```

**Comment by jordanlewis** [comment]
I added a single extra sample per column to the right of the maximum histogram bucket, so hopefully that will be enough to get all of the equality plans. And, the commit message has been adjusted.

**Comment by mgartner** [comment]
> I was unable to produce multiple plans using this schema, stats and query. All combinations of placeholders seemed to produce the same plan (confirmed in my SQL shell as well as the tool):

This might be obvious, but I want to also make clear: a tool like this will never produce **all query plans** that the optimizer searches, but rather **all optimal plans for any given placeholders**.

For example:

```
CREATE TABLE t (k INT PRIMARY KEY)

SELECT * FROM t WHERE k = $1
```

One of the plans considered is a full table scan with a filter on top, but there is no placeholder value for which such a plan will be chosen by the optimizer.

For the purposes of this tool, I don't think this matters, just want to make sure that is understood.

**Comment by jordanlewis** [comment]
Yes, understood. I've adjusted some wording to make this clearer.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68023)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/cli/statement_bundle.go, line 350 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68023#-MfimFnE5G63lRmbrtrc:-Mg6Z57y0WLkbZRM8N0l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f501b40109bd20a6732f82ef4fc5c48dac18ca10/pkg/cli/statement_bundle.go#L350)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you intend to include this? Or was this for debugging?
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
Alright I'm just gonna merge this, please try it out and we can improve as necessary.

bors r+

**Comment by mgartner** [comment]
🎉 ❤️

**Comment by jordanlewis** [comment]
bors r+

flake on kvevent package

**Pull request merged**
