### PR TITLE
opt,tree: fix bugs with Next(), Prev(), and histogram calculation for DTimeTZ

### LINKED ISSUE #74667: opt: filtering a timetz histogram can produce negative values
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4090697&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4090697&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on release-21.2 @ [f6e5974d563c2700dc68c2f71d4fc05ee1adea6b](https://github.com/cockroachdb/cockroach/commits/f6e5974d563c2700dc68c2f71d4fc05ee1adea6b):

```
The test failed on branch=release-21.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	sqlsmith.go:223,sqlsmith.go:256,test_runner.go:777: error: pq: internal error: estimated row count must be non-zero
		stmt:
		WITH
			with_74008 (col_406695)
				AS (
					SELECT
						*
					FROM
						(VALUES ('1981-12-17':::DATE), ((8592524857603341749:::INT8::INT8 + '1983-09-29':::DATE::DATE)::DATE))
							AS tab_181357 (col_406695)
				),
			with_74009 (col_406696) AS (SELECT tab_181358.col2_5 AS col_406696 FROM defaultdb.public.table2@[0] AS tab_181358)
		SELECT
			count(*) AS col_406697
		FROM
			defaultdb.public.table2@table2_expr_col2_7_col2_1_col2_2_expr1_col2_0_col2_6_key AS tab_181359
		WHERE
			(tab_181359.col2_7 < '03:33:05.598931+07:11:00':::TIMETZ)
		GROUP BY
			tab_181359.col2_7
		HAVING
			bool_or(false::BOOL)::BOOL
		ORDER BY
			tab_181359.col2_7 ASC, tab_181359.col2_7 ASC, tab_181359.col2_7 ASC
		LIMIT
			67:::INT8;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74912: sql: selecting from TimeTZ index may miss values in other time zones
Consider the following example. We have two tables with identical data in a timetz column. The only difference is that one table has the timetz column as the primary key (and therefore the column is indexed).
```
CREATE TABLE tab (t TIMETZ);
INSERT INTO tab VALUES 
  ('05:00:00.000001'),
  ('07:00:00.000001+02:00:00'),
  ('09:00:00.000001+04:00:00'),
  ('20:59:00.000001+15:59:00');
SELECT count(*) FROM tab WHERE t > '05:00:00';
  count
---------
      4

SELECT count(*) FROM tab WHERE t < '05:00:00.000001';
  count
---------
      3


CREATE TABLE tab2 (t TIMETZ PRIMARY KEY);
INSERT INTO tab2 VALUES 
  ('05:00:00.000001'),
  ('07:00:00.000001+02:00:00'),
  ('09:00:00.000001+04:00:00'),
  ('20:59:00.000001+15:59:00');
SELECT count(*) FROM tab2 WHERE t > '05:00:00';
  count
---------
      1

SELECT count(*) FROM tab2 WHERE t < '05:00:00.000001';
  count
---------
      0
```
The queries should return the same results on the two different tables, but they are different. This is because the queries over `tab2` are performing a constrained scan of the primary index using an incorrect constraint that misses some values. The reason the constraint is incorrect is because the index constraint code in the optimizer may call `datum.Next()` or `datum.Prev()` to create an inclusive constraint, and the `DTimeTZ` implementations of `Next()` and `Prev()` are incorrect. These functions return a value that is not the next (or previous) possible value according to the ordering of the key encoded values of TimeTZ.

This bug has existed since the timetz datatype was first added in 20.1.

### PR DESCRIPTION
**Pull request by rytaft**
**sql/sem/tree: fix Next() and Prev() for DTimeTZ**

Prior to this commit, the `DTimeTZ` functions `Next()` and `Prev()`
could skip over valid values according to the ordering of `DTimeTZ`
values in an index (which matches the ordering defined by the
`TimeTZ` functions `After()` and `Before()`).

This commit fixes these functions so that `Next()` now returns the smallest
valid `DTimeTZ` that is greater than the receiver, and `Prev()` returns
the largest valid `DTimeTZ` that is less than the receiver. This is
an important invariant that the optimizer relies on when building index
constraints.

Fixes #74912

Release note (bug fix): Fixed a bug that could occur when a `TIMETZ`
column was indexed, and a query predicate constrained that column using
a `<` or `>` operator with a `timetz` constant. If the column contained values
with time zones that did not match the time zone of the `timetz` constant,
it was possible that not all matching values could be returned by the
query. Specifically, the results may not have included values within one
microsecond of the predicate's absolute time. This bug was introduced
when the timetz datatype was first added in 20.1. It exists on all
versions of 20.1, 20.2, 21.1, and 21.2 prior to this patch.

**opt: fix bug in histogram calculation for TimeTZ**

This commit fixes a bug in the histogram estimation code for `TimeTZ`
that made the faulty assumption that `TimeTZ` values are ordered by
`TimeOfDay`. This is incorrect since it does not take the `OffsetSecs`
into account. As a result, it was possible to estimate that the size
of a histogram bucket was negative, which caused problems in the
statistics estimation code. This commit fixes the problem by taking
into account both `TimeOfDay` and `OffsetSecs` when estimating the size of
a bucket in a `TimeTZ` histogram.

Fixes #74667

Release note (bug fix): Fixed an internal error, "estimated row count must
be non-zero", that could occur during planning for queries over a table
with a `TimeTZ` column. This error was due to a faulty assumption in the
statistics estimation code about ordering of `TimeTZ` values, which has now
been fixed. The error could occur when `TimeTZ` values used in the query had
a different time zone offset than the `TimeTZ` values stored in the table.

### CODE REVIEW

**Comment by otan** [comment]
ah a big oopsie :\ looks good to me!

**Review by otan — APPROVED** [review]

**Review by mgartner — APPROVED** [review]
Nice find! :lgtm: 

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74914#-:-Mthaewz2B4TooTDbSWs:bli3xsu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/timetz, line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74914#-Mth_cVw-ETTVFb6yHU1:-Mth_cVx-dILhtV4n-UM:bl0vmtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/211ebab94d0bb5acf859c533b0418eeea39088ee/pkg/sql/logictest/testdata/logic_test/timetz#L697)):*
> ```
> 
> query I
> SELECT count(*) FROM regression_74912 WHERE t2 > '05:00:00';
> ```

nit: you could force the index here and below to ensure the test will always test what it's supposed to

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74914#-:-Mti1Ow35QuQOKfdgECR:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/timetz, line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74914#-Mth_cVw-ETTVFb6yHU1:-MthyX7GDizYPQK_S__n:b-hw8gxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/211ebab94d0bb5acf859c533b0418eeea39088ee/pkg/sql/logictest/testdata/logic_test/timetz#L697)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could force the index here and below to ensure the test will always test what it's supposed to
</blockquote></details>

There's only one index (the primary index), although I guess maybe I could force using a constrained scan -- Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74914)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74914#-:-Mtjzzps3NyWarYx8vj5:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

**Comment by rytaft** [comment]
Another flake

bors r+

**Pull request merged**
