### PR TITLE
changefeedccl: fix panics when min_checkpoint_frequency is 0

### LINKED ISSUE #125312: cdc: panics in nextFlushWithJitter when min_checkpoint_frequency is zero
**Describe the problem**

In 24.1, we introduced changefeed.aggregator.flush_jitter in https://github.com/cockroachdb/cockroach/pull/114161. Having zero min_checkpoint_frequency could cause panics [here](https://github.com/wenyihu6/cockroach/blob/81e0abb17b37ef4c26f2f872694a5dcd29a8f817/pkg/ccl/changefeedccl/changefeed_processors.go#L645). 

More details in https://github.com/cockroachlabs/support/issues/2984. 

Jira issue: CRDB-39380

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, we introduced the cluster setting changefeed.aggregator.flush_jitter
to apply some jitter to the aggregator flush frequency. This was done to reduce
the load on the coordinator by spreading out aggregator flush times. However,
that PR did not account for the case where min_checkpoint_frequency is set to
zero, which could cause panics due to rand.Int63(0). This patch fixes the issue
by adding a check for when the frequency is zero, ensuring that jitter is not
applied in such cases.

Fixes: https://github.com/cockroachdb/cockroach/issues/125312

Release note (bug fix): Fixed a bug in v24.1, v23.2, and v23.1 where using
changefeed.aggregator.flush_jitter with min_checkpoint_frequency set to zero
could cause panics.

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-NznkqM827v8hy6vdSLf:b-hta36i) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
> ```Go
> func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) time.Time {
> 	if j < 0 || d < 0 {
> 		log.Fatalf(context.Background(), "invalid jitter value: %f, duration: %s", j, d)
> ```

Should this be at the level of a `log.Fatalf`? Would a `log.Warningf` be sufficient?

**Comment by wenyihu6** [comment]
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-Nzno6fc7Vhqvt_Og8LE:b-mbkvae) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Should this be at the level of a `log.Fatalf`? Would a `log.Warningf` be sufficient?
</blockquote></details>

I'm okay with either. Changed to Warningf.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-Nzo9H711O03tmz8JG2f:b-7c7mj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I'm okay with either. Changed to Warningf.
</blockquote></details>

On second thought, since this is for catching developer error, I think you probably want to return an error instead, i.e. a `errors.AssertionFailedf`. The user isn't going to be able to do very much with a log message.

**Review by rharding6373 — COMMENTED** [review]
Thanks for the quick fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-:-NzoEBs-AxJ0aRzWXe4d:b-e69qx5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-Nznqs69-YebGcLNwhFJ:bl4b5g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

On second thought, since this is for catching developer error, I think you probably want to return an error instead, i.e. a `errors.AssertionFailedf`. The user isn't going to be able to do very much with a log message.
</blockquote></details>

This seems like it's going to be very noisy, since this is based on cluster settings/options that aren't going to change often. But also the way we currently use this function this should never happen.

I'm with Andy, this should surface as an unexpected error.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 7056 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NzoDkNC-F-4Ueva8yQX:-NzoDkNC-F-4Ueva8yQY:bp7wzr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7344a22c218e6694c0e1cd0dc7f35c825a566ca2/pkg/ccl/changefeedccl/changefeed_test.go#L7056)):*
> ```Go
> 		100 * time.Millisecond,
> 	} {
> 		t.Run(fmt.Sprintf("Disabled_FlushFrequency=%s", flushFrequency), func(t *testing.T) {
> ```

optional super minor nit: most tests in this file use lower case test names

**Review by wenyihu6 — COMMENTED** [review]
nvm

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rharding6373)

___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 7056 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NzoDkNC-F-4Ueva8yQX:-O-14JPnBAUiXL6KcjwH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7344a22c218e6694c0e1cd0dc7f35c825a566ca2/pkg/ccl/changefeedccl/changefeed_test.go#L7056)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional super minor nit: most tests in this file use lower case test names
</blockquote></details>

Done.

**Review by rharding6373 — COMMENTED** [review]
Seems like it's really close!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-:-O-2_NutD44wtg5ZJZ7n:b-z26ury)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-O-2XMIF7yexicjuxV3S:b-jvbmf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Hm it is a bit hard to return as an error since the function call is wrapped in a defer function. Do you see an easier way to do this?
</blockquote></details>

You could do it with a named return value for the error in the parent function and `errors.CombineErrors`. Here's one such example in the code base: https://github.com/cockroachdb/cockroach/blob/4392d13569db46d8ceeacdf47108c4dd3280e293/pkg/workload/rand/rand.go#L182

So this would look something like:
```
func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) (time.Time, error) { ... }
...
func (ca *changeAggregator) noteResolvedSpan(resolved jobspb.ResolvedSpan) (err error) {
...
defer func() { 
  t, retErr := nextFlushWithJitter(...)
  err = errors.CombineErrors(err, retErr) }()
...
```

Please try to add test coverage for this new code path (though it definitely seems like we should never hit it given current guardrails on the inputs).
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 832 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-O-14M7dB6zK5zrfB4fa:-O-2Z6P88tBN-3QkSGYr:b-by9q0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ad7a8364457e3853f132020242a71915589fdb4/pkg/ccl/changefeedccl/changefeed_processors.go#L832)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I'm not sure if this is a common way to deal with changing errors in a defer statement. Is there a cleaner way to handle this?
</blockquote></details>

See other comment.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 7056 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NzoDkNC-F-4Ueva8yQX:-O-2_IdU7o7WN5gRiMfS:bb70w76) ([raw file](https://github.com/cockroachdb/cockroach/blob/7344a22c218e6694c0e1cd0dc7f35c825a566ca2/pkg/ccl/changefeedccl/changefeed_test.go#L7056)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-O-2bB8GDu-NGJHd0YD6:b-g1qura) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

You could do it with a named return value for the error in the parent function and `errors.CombineErrors`. Here's one such example in the code base: https://github.com/cockroachdb/cockroach/blob/4392d13569db46d8ceeacdf47108c4dd3280e293/pkg/workload/rand/rand.go#L182

So this would look something like:
```
func nextFlushWithJitter(s timeutil.TimeSource, d time.Duration, j float64) (time.Time, error) { ... }
...
func (ca *changeAggregator) noteResolvedSpan(resolved jobspb.ResolvedSpan) (err error) {
...
defer func() { 
  t, retErr := nextFlushWithJitter(...)
  err = errors.CombineErrors(err, retErr) }()
...
```

Please try to add test coverage for this new code path (though it definitely seems like we should never hit it given current guardrails on the inputs).
</blockquote></details>

Done. I added a few more test cases for error. Are there any other test cases you would want me to add? On a side note, is this how we typically handle developer errors? I have a slight preference for using log.Fatal since we should never reach this state, and error handling here makes the code less clean. But I also understand that this is not a serious issue and we may want to be more defensive.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-:-O-2w5nS2aTN9QcXuGco:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-NznkqM827v8hy6vdSLe:-O-2qJkpD6m5Amdf4xDX:b50ujap) ([raw file](https://github.com/cockroachdb/cockroach/blob/386b66a869a1efe017171c97a016b61259f4a7f9/pkg/ccl/changefeedccl/changefeed_processors.go#L644)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Done. I added a few more test cases for error. Are there any other test cases you would want me to add? On a side note, is this how we typically handle developer errors? I have a slight preference for using log.Fatal since we should never reach this state, and error handling here makes the code less clean. But I also understand that this is not a serious issue and we may want to be more defensive.
</blockquote></details>

Ideally when the user provides a bad input, we provide immediate feedback that their operation failed and why. I think we already do that for the user-provided input that is ultimately used in all production calls to this code.

We should generally try to handle errors gracefully and not with panics. The exception is that if you like you can add a test-only runtime assertion here, following a pattern like those described here: https://github.com/cockroachdb/cockroach/issues/94986
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 7138 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125317#-O-2sFj-0jbm2Bhcheh2:-O-2sFj-0jbm2Bhcheh3:b-s4fyq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf2b4b5d4df45af1ae77cdf38a6e462d73f415cb/pkg/ccl/changefeedccl/changefeed_test.go#L7138)):*
> ```Go
> 				if tc.expectedErr {
> 					require.Error(t, err)
> 				}
> ```

`else { require.NoError }`

**Comment by wenyihu6** [comment]
Thanks for the quick review! 

bors r=rharding6373

**Pull request merged**
