### PR TITLE
go.mod: revert comparer change and bump Pebble to 0f785fec58c0

### PR DESCRIPTION
**Pull request by RaduBerinde**
The comparer changes effectively revert #128043, which can cause
replica inconsistency during/after upgrades.

Changes:

 * [`0f785fec`](https://github.com/cockroachdb/pebble/commit/0f785fec) metamorphic: abridge failure output
 * [`be56747f`](https://github.com/cockroachdb/pebble/commit/be56747f) db: fix overlap check for flushable ingest excises
 * [`2569414a`](https://github.com/cockroachdb/pebble/commit/2569414a) db: remove race in TestCrashOpenCrashAfterWALCreation
 * [`575f7a04`](https://github.com/cockroachdb/pebble/commit/575f7a04) sstable: support columnar blocks in Layout.Describe
 * [`c88c7471`](https://github.com/cockroachdb/pebble/commit/c88c7471) github: fix code cover publish workflow
 * [`c0fa4a9c`](https://github.com/cockroachdb/pebble/commit/c0fa4a9c) sstable: populate CompareSuffixes on test4bSuffixComparer
 * [`3a76074f`](https://github.com/cockroachdb/pebble/commit/3a76074f) sstable: set IndexPartitions property in columnar sstable writer
 * [`0595c1fb`](https://github.com/cockroachdb/pebble/commit/0595c1fb) colblk: define behavior of KeyWriter.ComparePrev with no previous
 * [`01dcf575`](https://github.com/cockroachdb/pebble/commit/01dcf575) base: make comparer tolerate empty keys
 * [`d73ab80f`](https://github.com/cockroachdb/pebble/commit/d73ab80f) db: allow excises to unconditionally be flushable ingests
 * [`b34a3937`](https://github.com/cockroachdb/pebble/commit/b34a3937) base: allow CompareSuffixes to be stricter than Compare
 * [`90356021`](https://github.com/cockroachdb/pebble/commit/90356021) db: refactor replayWAL to use flushes to make versionEdits

Informs: #130533

Release note: none.
Epic: none.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131366#-:-O7en2BoCbSnxdmef3NB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by itsbilal** [comment]
Might be worth holding off on this for at least a day so we can get the fix for cockroachdb/pebble#3963

**Comment by RaduBerinde** [comment]
Yes, agreed.

**Comment by RaduBerinde** [comment]
Updated to the current Pebble master.

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by RaduBerinde** [comment]
I'm getting this test error:
```
=== RUN   TestStoreMetrics
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestStoreMetrics1690765082
    test_log_scope.go:81: use -show-logs to present logs inline
    client_metrics_test.go:389: counter rocksdb.block.cache.hits = 0 < min 10
    client_metrics_test.go:389: counter rocksdb.block.cache.hits = 0 < min 10
    client_metrics_test.go:393: -- test log scope end --
```

Any ideas why this changed?

**Comment by jbowens** [comment]
I don't like that test. I've run afoul of it before, because it ends up asserting on details of the storage engine mechanics. I've got no idea why we'd be getting zero block cache hits though.

**Comment by itsbilal** [comment]
This should deflake this test:

[deflake.patch](https://github.com/user-attachments/files/17168365/deflake.patch)


```
diff --git a/pkg/kv/kvserver/client_metrics_test.go b/pkg/kv/kvserver/client_metrics_test.go
index 232f9c9cfbf..eb6413c6ce9 100644
--- a/pkg/kv/kvserver/client_metrics_test.go
+++ b/pkg/kv/kvserver/client_metrics_test.go
@@ -262,7 +262,7 @@ func TestStoreMetrics(t *testing.T) {
                        },
                }
                stickyServerArgs[i] = base.TestServerArgs{
-                       CacheSize:  1 << 20, /* 1 MiB */
+                       CacheSize:  2 << 20, /* 2 MiB */
                        StoreSpecs: []base.StoreSpec{spec},
                        Knobs: base.TestingKnobs{
                                Server: &server.TestingKnobs{
```

**Comment by RaduBerinde** [comment]
Thank you!! What's the explanation why a  1MB cache leads to no hits?

**Comment by itsbilal** [comment]
> Thank you!! What's the explanation why a 1MB cache leads to no hits?

I actually don't know either, but I also wasn't able to really understand what the test was doing so....

**Pull request merged**
