### PR TITLE
server/debug: fix lsm-viz endpoint

### PR DESCRIPTION
**Pull request by dt**
Switch to calling cmd.RunE instead of now nil cmd.Run, and switch to using pebble.Peek instead of manually reading the no longer maintained CURRENT file.

Release note: none.

### CODE REVIEW

**Review by joshimhoff — APPROVED** [review]
Yay! I'm gonna add start & end keys in a follow up PR. After that, I'll put up a backport, if we are all game.

**Review by nicktrav — APPROVED** [review]
Thank you for fixing! :lgtm: 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81986#-:-N363XTt9reLRKDflUWw:b-jurrpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by nicktrav** [comment]
Thoughts on backport labels?

**Comment by joshimhoff** [comment]
I vote 21.2 also. We're gonna live with that baby for a while, and having this in admin UI is pretty great in cloud, where devs can easily be given admin UI but not persistent disk access.

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
