### PR TITLE
gossip: Don't check if the network should be tightened so often

### PR DESCRIPTION
**Pull request by a-robinson**
Touches #51838. See the thread there for more detail, but the gist is that tightenNetwork gets called hundreds of times per second (taking a full mutex lock each time) on large clusters, even when nothing needs tightening.

Release note (performance improvement): Avoid wasteful contention on the gossip mutex caused by checking if the network needs tightening hundreds of times per second.

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
LGTM! Thanks for submitting the fix and investigating the issue @a-robinson.

The release note isn't needed for this change because it doesn't require documentation changes.

Running a 96 node (gcp n1 16vcpu) cluster with 20k ranges, showed some improvement.

The CPU utilization difference isn't very noticeable, both pre/post change are within 0.8-1.5% normalized range across the cluster (12.8-24%). 

Profiling showed 7% (37% -> 30%) reduction in time attributable to gossip, which makes sense since in the cluster running master there was about 8% of on `tightenNetwork`.

Before:
image

After:
image

I couldn't reproduce the issue with processing gossip entries, either quiescent or with 500k QPS running on the cluster.

>  [...] Specifically I'd see a small number of nodes occasionally reporting a large fraction of other nodes in the cluster as unlive (going by their liveness_livenodes metric) and all of their replicas as unavailable (going by their ranges_unavailable metric). At this time no nodes were actually failing liveness heartbeats or having liveness epochs incremented, so it appeared relatively clear that a delay in processing gossip entries was at fault.

**Review by nvb — COMMENTED** [review]
:wave: thanks for the PR @a-robinson.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-:-NCaPj6A5kzkZx6SWXWi:b9mnivj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @a-robinson and @nvanbenschoten)

___
*[`pkg/gossip/server.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-NCaPawE9w-K2An31XNS:-NCaPawE9w-K2An31XNT:b3jg0na) ([raw file](https://github.com/cockroachdb/cockroach/blob/db529902d404579650d3d3a0ef0135810c424bcf/pkg/gossip/server.go#L351)):*
> ```Go
> func (s *server) maybeTightenLocked() {
> 	now := timeutil.Now()
> 	if now.Before(s.mu.lastTighten.Add(gossipTightenInterval)) {
> ```

Are we setting `s.mu.lastTighten` anywhere? Do we want to right after this branch?

**Review by a-robinson — COMMENTED** [review]
Thanks for checking out the profile, @kvoli ! Yeah I do think that the other ideas I mentioned in https://github.com/cockroachdb/cockroach/issues/51838#issuecomment-1255159719 and https://github.com/cockroachdb/cockroach/issues/51838#issuecomment-1255366296 would do much more to reduce CPU usage, but this was the easiest of the wins and should help with mutex contention (e.g. as it relates/related to #84943) even if it isn't a huge CPU reduction.

> I couldn't reproduce the issue with processing gossip entries, either quiescent or with 500k QPS running on the cluster.

My cluster may have been particularly poorly off due to the large number of previously decommissioned nodes on it (slowing down `visitInfos` and/or due to using shared CPUs. Either way I can assure you I saw it happening far more often than I'd like.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-:-NCaTw_2BHNnK4q-ak8-:b-5014ls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/gossip/server.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-NCaPawE9w-K2An31XNS:-NCaTU7508_NQ0B75fEP:b-48pvag) ([raw file](https://github.com/cockroachdb/cockroach/blob/db529902d404579650d3d3a0ef0135810c424bcf/pkg/gossip/server.go#L351)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we setting `s.mu.lastTighten` anywhere? Do we want to right after this branch?
</blockquote></details>

This function isn't necessarily actually checking if the network needs tightening. It's just (maybe) sending a signal on the `s.tighten` channel that will trigger a different goroutine to actually try tightening.

I debated updating `s.mu.lastTighten` below if the channel send succeeds, but it seemed to make the most sense to only update it in `tightenNetwork` in gossip.go where we actually do the tightening/checking.

**Comment by a-robinson** [comment]
> The release note isn't needed for this change because it doesn't require documentation changes.

Does that mean you'd like me to remove it from the commit?

**Review by nvb — COMMENTED** [review]
:lgtm:

bors r=kvoli,nvanbenschoten

> Does that mean you'd like me to remove it from the commit?

I think the release note is fine to keep. Release notes don't necessarily need to imply documentation changes.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-:-NCbJ9bD4uA8Ql960fjp:b5bb28o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @a-robinson and @nvanbenschoten)

___
*[`pkg/gossip/server.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88472#-NCaPawE9w-K2An31XNS:-NCbI_wr9iWBcgzMmdju:bjqv6uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/db529902d404579650d3d3a0ef0135810c424bcf/pkg/gossip/server.go#L351)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This function isn't necessarily actually checking if the network needs tightening. It's just (maybe) sending a signal on the `s.tighten` channel that will trigger a different goroutine to actually try tightening.

I debated updating `s.mu.lastTighten` below if the channel send succeeds, but it seemed to make the most sense to only update it in `tightenNetwork` in gossip.go where we actually do the tightening/checking.
</blockquote></details>

Oh I see, the embedding was tripping me up. `Gossip` embeds a `sever`, so `g.mu.lastTighten` is `s.mu.lastTighten`.

**Pull request merged**
