### PR TITLE
obsservice: create stmt insights table

### PR DESCRIPTION
**Pull request by maryliag**
Creation of Statement Insights table for Obs Service. 
This commit also adds tests that check if all migrations created have the required columns for an event.

Fixes CC-26213

Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Niceee! Just a couple questions about the schema

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-:-NjrtEkLCSIBvv9GdKVf:bd35p2c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrB57BvFtAGjfr2xw:-NjrrB57BvFtAGjfr2xx:bgnjsp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L4)):*
> ```TSQL
> CREATE TABLE statement_execution_insights (
>    timestamp                  TIMESTAMP NOT NULL,
>    org_id                     BYTES NOT NULL,
> ```

nit: Since we don't have org IDs in the payload yet, should we make this nullable for the time being? Or I suppose we can just hardcode it in the prototype processor in the meantime :shrug: 
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrWNk3V1pGHEaMktB:-NjrrWNk3V1pGHEaMktC:b-dkxfcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L6)):*
> ```TSQL
>    org_id                     BYTES NOT NULL,
>    cluster_id                 BYTES NOT NULL,
>    instance_id                INT NOT NULL,
> ```

Just curious, what does `instance_id` represent? Where does it come from? I didn't see it in the insights proto. 
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrqPPX1gGKoJAo7BxR:-NjrqPPX1gGKoJAo7BxS:bro5qh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L7)):*
> ```TSQL
>    cluster_id                 BYTES NOT NULL,
>    instance_id                INT NOT NULL,
>    event_id                   BYTES NOT NULL DEFAULT uuid_v4(),
> ```

This is the `StatementInsightsStatistics.ID`, right? Just curious
___
*[`pkg/obsservice/obslib/migrations/migrations_test.go` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-Njrq91c5M2HAoorSeGJ:-Njrq91dBVg-g2nsovgZ:bslj8i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/migrations_test.go#L25)):*
> ```Go
> // TestMigrationHaveColumns test that all migrations created for
> // events have the required columns.
> func TestMigrationHaveRequiredColumns(t *testing.T) {
> ```

Thank you for adding this!

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrB57BvFtAGjfr2xw:-NjrvE50CJQrvBXLijWQ:bee2x8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L4)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Since we don't have org IDs in the payload yet, should we make this nullable for the time being? Or I suppose we can just hardcode it in the prototype processor in the meantime :shrug:
</blockquote></details>

I would prefer hard code (and adding a TODO), so when we start playing with filter with have something to test on. I will make the changes
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrWNk3V1pGHEaMktB:-NjrvOCr23fAfvRl3KN3:bgwmgpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L6)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just curious, what does `instance_id` represent? Where does it come from? I didn't see it in the insights proto.
</blockquote></details>

I saw that on the cluster_events schema, so assumed it was the tenant_id, so part of the "required columns". I can change the name to tenant in both cases
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrqPPX1gGKoJAo7BxR:-NjrveWAAgVtbP6UesrL:bstj728) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L7)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

This is the `StatementInsightsStatistics.ID`, right? Just curious
</blockquote></details>

Correct, I used the generic name so all table events can have it (added as a required column)
___
*[`pkg/obsservice/obslib/migrations/migrations_test.go` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-Njrq91c5M2HAoorSeGJ:-NjrvlHG-JMAOKoo2sbm:bggq5m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/migrations_test.go#L25)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Thank you for adding this!
</blockquote></details>

You welcome! :smile:

**Review by abarganier — APPROVED** [review]
:lgtm: :rocket: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-:-NjsC_xIDwEq5KLSF3CM:byykejp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrB57BvFtAGjfr2xw:-NjsCQi17ekCQzFAPs8j:bwsi4ek) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L4)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I would prefer hard code (and adding a TODO), so when we start playing with filter with have something to test on. I will make the changes
</blockquote></details>

SGTM! Feel free to handle that in the processor if you'd prefer. 
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrrWNk3V1pGHEaMktB:-NjsC7LP1qo-1gI_cena:b-pxyw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L6)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I saw that on the cluster_events schema, so assumed it was the tenant_id, so part of the "required columns". I can change the name to tenant in both cases
</blockquote></details>

For now, I think we can omit it. The cluster_events schema is pretty outdated, I don't think it should influence how we define tables moving forward. Hopefully, we'll soon delete the cluster_events migration file altogether :smile: 
___
*[`pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114877#-NjrqPPX1gGKoJAo7BxR:-NjsCMyuCY2w3fZCi7Cn:bgsc9xa) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ec262fd2ac2c6ae5d681e0fee51b76806d1a8f/pkg/obsservice/obslib/migrations/sqlmigrations/0002_stmt_insights.sql#L7)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Correct, I used the generic name so all table events can have it (added as a required column)
</blockquote></details>

Ack - makes sense! Thanks.

**Comment by maryliag** [comment]
TFTR!

bors r+

**Pull request merged**
