### PR TITLE
sql: support CREATE DATABASE IF NOT EXISTS ... WITH OWNER

### LINKED ISSUE #97938: sql: cannot set owner with CREATE DATABASE IF NOT EXISTS
The owner clause cannot be set in the `CREATE DATABASE IF NOT EXISTS` variant of `CREATE DATABASE`:
https://github.com/cockroachdb/cockroach/blob/5bae6a000a018f22e85c4d11e71d0c534be3a814/pkg/sql/parser/sql.y#L11442

Investigate if it is as simple as updating the syntax or if something else is preventing them from being combined.

This issue was reported in community slack https://cockroachdb.slack.com/archives/CP4D9LD5F/p1677583350807699

Jira issue: CRDB-24976

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #97938

Previously we supported `CREATE DATABASE IF NOT EXISTS` and `CREATE DATABASE ... WITH OWNER` separately, but not `CREATE DATABASE IF NOT EXISTS ... WITH OWNER`.

It looks like this may have been an oversight when adding `CREATE DATABASE ... WITH OWNER` as it works properly when `sql.y` is updated with the missing syntax.

This change adds the missing syntax and a logic test.

Release note (sql change): Support syntax `CREATE DATABASE IF NOT EXISTS ... WITH OWNER`.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks for the fix!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97951#-:-NPZhfdlBtQk68c82gjQ:bp9cthg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by ecwall** [comment]
bors r=rafiss

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
