### PR TITLE
RFC: Add onto leaseholder locality PR based on post-merge feedback

### PR DESCRIPTION
**Pull request by a-robinson**
https://github.com/cockroachdb/cockroach/pull/13233#issuecomment-277779372

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13493)

Jira issue: CRDB-14789

Jira issue: CRDB-14790

### CODE REVIEW

**Comment by a-robinson** [comment]
ping

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13493#-:-KcxljJ3RQPpXXe3Ah67:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm: thanks

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13493#-Kcxl7Qmtr_1ZxnXqiqm:-Kcxl7Qmtr_1ZxnXqiqn:bqwje11) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d3f0dbf40cca7cbdb66f406042dd9461b65e24/docs/RFCS/leaseholder_locality.md#L304)):*
> ```Markdown
>   causing performance dips.
> 
> * There could be situations in which the locality that's generating most of the
> ```

well you put this as a future direction, but to me this "replica placement" work would be the most interesting thing. Relying on people to think about geo-partitioning, add the right keys for that and set the right zone configs seems like a big burden. If all of Amazon's orders for Smores Inc are accessed from the US, we should be able to locate that data in the US by ourselves.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13493#-:-Kcxkwzg0UeAsavPewcV:b-v6ynew)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/RFCS/leaseholder_locality.md, line 304 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13493#-Kcxl7Qmtr_1ZxnXqiqm:-KcxnBMMLuBkuPn96PCn:b-czd4tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0d3f0dbf40cca7cbdb66f406042dd9461b65e24/docs/RFCS/leaseholder_locality.md#L304)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well you put this as a future direction, but to me this "replica placement" work would be the most interesting thing. Relying on people to think about geo-partitioning, add the right keys for that and set the right zone configs seems like a big burden. If all of Amazon's orders for Smores Inc are accessed from the US, we should be able to locate that data in the US by ourselves.
</blockquote></details>

I do agree that moving replicas with the request load would be a huge win, but the motivating use case for this work assumed that reasonable ZoneConfigs would be in place, so I'm going to keep the focus on that for now and work on moving replicas based on load afterwards. It can be worked into the body of this RFC when the time comes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13493)*

**Pull request merged**
