### PR TITLE
Update Store Stats on Replica Removal

### LINKED ISSUE #4625: storage: Update store stats when a Replica is removed
We apparently never properly implemented the statistic changes when a replica is removed from a node by a rebalance event.  We simply need to update the store stats in store.RemoveReplica.

### PR DESCRIPTION
**Pull request by mrtracy**
Previously, store-level stats were not being update when a replica was removed
from the store by a rebalancing operation. This is a relatively simple fix: we
simply subtract the replica's stats from the store when it is removed.

Fixes #4625

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4964)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964#-KCIePaNdLdyxRPPO8aG:-KCIePaNdLdyxRPPO8aH:-26582512) ([raw file](https://github.com/cockroachdb/cockroach/blob/499129abc22243b194f5e3687d5b2ba70defe3af/storage/store.go#L1266)):*
Is there any harm to updating the metrics before `rep.Destroy()` is called? Seems fragile to be doing it afterward (you're relying on an implementation detail of `rep.Destroy()`).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964#-:-KCIf8mafJNf8zBcMNR6:676834233)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964#-KCIePaNdLdyxRPPO8aG:-KCIg2cbPxCh3FEex7c2:1954196220) ([raw file](https://github.com/cockroachdb/cockroach/blob/499129abc22243b194f5e3687d5b2ba70defe3af/storage/store.go#L1266)):*
I'm just delaying it until all error-returning work is done, in case something earlier fails (stats subtraction cannot be undone).  I'm not sure what should be done if Destroy() returns an error, or anything earlier in the chain for that matter; should some of these indicate that the store is corrupt?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964#-KCIePaNdLdyxRPPO8aG:-KCIhb0UMT_zttZx2qcE:1889709342) ([raw file](https://github.com/cockroachdb/cockroach/blob/499129abc22243b194f5e3687d5b2ba70defe3af/storage/store.go#L1266)):*
Then perhaps grab a copy of the stats before calling `rep.Destroy()`. I'm not sure how or why `Destroy()` could return an error. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964)*

**Comment by mrtracy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964#-KCIePaNdLdyxRPPO8aG:-KCJ4UtElLL8epUkjO52:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/499129abc22243b194f5e3687d5b2ba70defe3af/storage/store.go#L1266)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4964)*

**Pull request merged**
