### PR TITLE
sqlccl: fix segfault with RESTORE

### PR DESCRIPTION
**Pull request by benesch**
This fixes a bug I found while working on #15004, and adds a test to prevent regressions.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiW-g1djpbz57uKg_00:-KiW-g1djpbz57uKg_01:b-6vzh15) ([raw file](https://github.com/cockroachdb/cockroach/blob/a27f0b546b844618f8f27e803e91307ccd368dde/pkg/ccl/sqlccl/backup_test.go#L274)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	for _, numAccounts := range []int{0, 1000} {
> ```

this probably warrants its own test: TestBackupRestoreEmpty

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiVwXoNKbwhAApTPc-z:b-l2d105) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
> ```Go
> // test.
> func TempDir(t testing.TB) (string, func()) {
> 	name := strings.Replace(t.Name(), "/", "_", -1)
> ```

there seems to be a larger general problem here. maybe replace anything not alphanumeric with _?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-:-KiW-l3yU1YHXZHAlpo-:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiW0Y7wQTlLM8F78TkL:bnrsmki) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

there seems to be a larger general problem here. maybe replace anything not alphanumeric with _?
</blockquote></details>

What's the general problem? slashes are no bueno because they look like path separators.

I think this code already exists elsewhere, though, so it'd be good to share it or use a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by danhhz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiW2Gk9hLkiQm4A-z7M:brarecd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

What's the general problem? slashes are no bueno because they look like path separators.

I think this code already exists elsewhere, though, so it'd be good to share it or use a comment.
</blockquote></details>

The general problem is that there are a number of characters that are allowable in go test names, but not in filenames

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiW3EIHCqee0_BWxXET:b-b7k4t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

The general problem is that there are a number of characters that are allowable in go test names, but not in filenames
</blockquote></details>

Which characters aren't allowable in filenames?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by danhhz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiW3v4NCzNa9DGQQHBK:b-7donde) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Which characters aren't allowable in filenames?
</blockquote></details>

https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words. If someone has already done the research and written something that does the right thing, I'm fine with that too. Do you have a pointer to the code you referenced in your first comment?

Otherwise, I don't think it's worth Nikhil's time right now to do anything more complicated than escape non-alphanumerics

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiW6RhaPimN0W82EHF5:b938b1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words. If someone has already done the research and written something that does the right thing, I'm fine with that too. Do you have a pointer to the code you referenced in your first comment?

Otherwise, I don't think it's worth Nikhil's time right now to do anything more complicated than escape non-alphanumerics
</blockquote></details>

https://github.com/cockroachdb/cockroach/commit/17512ae691319c6e03fde97c2c30ddb6b5904e25

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by benesch** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiW-g1djpbz57uKg_00:-KiWAjZpf9GBEoCx_1OQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a27f0b546b844618f8f27e803e91307ccd368dde/pkg/ccl/sqlccl/backup_test.go#L274)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this probably warrants its own test: TestBackupRestoreEmpty
</blockquote></details>

Done.

---

*[pkg/testutils/dir.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293#-KiVwXoMfR4ulr1LIZZ1:-KiWFT-QmF02IJDNtpxc:b-9vu08z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8239b0c29d471adaae29c5fb030eb2b834dfcec2/pkg/testutils/dir.go#L29)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/commit/17512ae691319c6e03fde97c2c30ddb6b5904e25
</blockquote></details>

I don't think it's any harder to replace the Windows-banned characters than it is to replace non-alphanumeric characters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Comment by tamird** [comment]
Reviewed 4 of 6 files at r3, 1 of 2 files at r4.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15293)*

**Pull request merged**
