### PR TITLE
sql: add jsonb_insert builtin

### PR DESCRIPTION
**Pull request by changangela**
Relates to #20120.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Wow, that was quick! Nice work. I'm going to ask @justinj to take a look at this as he's the most familiar with our JSON implementation. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-:-LM4ca3WCoOTbcU6CqSG:b-ddl59j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by justinj — COMMENTED** [review]
nice! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-:-LM83pNL96R0l3eS5VQk:bbixqh9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-G6-1HtcgAYs6uwb:-LM8-G60EZY_dq_fjpBE:b-zi5pqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/logictest/testdata/logic_test/json_builtins#L860)):*
> ```
> 
> query error pq: jsonb_insert\(\): cannot set path in scalar
> SELECT jsonb_insert('1', '{a}'::STRING[], '10', true);
> ```

:thumbsup: on this test coverage, I think we need one where the array is `NULL` though?
___
*[pkg/sql/sem/builtins/builtins.go, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-SEH-THpavdnrkDI:-LM8-SEH-THpavdnrkDJ:b-7n0pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3223)):*
> ```Go
> 		// jsonb_insert only errors if there is a null at the first position, but not
> 		// at any other positions.
> 		if err := checkHasNullAtPositionOne(ary); err != nil {
> ```

do we have a test verifying these cases?
___
*[pkg/sql/sem/builtins/builtins.go, line 3251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-_nTCnieLS0yXUMJ:-LM8-_nTCnieLS0yXUMK:b-n0mbfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3251)):*
> ```Go
> 		// jsonb_insert only errors if there is a null at the first position, but not
> 		// at any other positions.
> 		if err := checkHasNullAtPositionOne(ary); err != nil {
> ```

I think we could factor out this whole chunk of code between this and `jsonInsertImpl` (the error checks, calling `darrayToStringSlice`, etc, so that the only difference is that one passes through `insert_after` and one makes it `false`).

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-G6-1HtcgAYs6uwb:-LM8Doq03Hg16so-oYHt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/logictest/testdata/logic_test/json_builtins#L860)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

:thumbsup: on this test coverage, I think we need one where the array is `NULL` though?
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-SEH-THpavdnrkDI:-LM8Dyk_8TLjNYIONBIj:b6q70dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3223)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

do we have a test verifying these cases?
</blockquote></details>

I just added two tests verifying this case. The reason I'm only throwing an error when NULL is at the first position, but not when NULL is in any other position is to be consistent with the cockroachdb implementation of jsonb_set. However, in postgresql, it looks like they throw an error when NULL is at any position of the path for both jsonb_insert and jsonb_set. Do you think this is okay?
___
*[pkg/sql/sem/builtins/builtins.go, line 3251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-_nTCnieLS0yXUMJ:-LM8DvDQAd0FbBbix1pi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3251)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think we could factor out this whole chunk of code between this and `jsonInsertImpl` (the error checks, calling `darrayToStringSlice`, etc, so that the only difference is that one passes through `insert_after` and one makes it `false`).
</blockquote></details>

Done.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/builtins.go, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-SEH-THpavdnrkDI:-LM8HGlF-v-GR77-EPUg:b-9mh1rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3223)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

I just added two tests verifying this case. The reason I'm only throwing an error when NULL is at the first position, but not when NULL is in any other position is to be consistent with the cockroachdb implementation of jsonb_set. However, in postgresql, it looks like they throw an error when NULL is at any position of the path for both jsonb_insert and jsonb_set. Do you think this is okay?
</blockquote></details>

Hm, that was my doing, but I guess it was wrong? I'm not sure why I thought that was the behaviour but it seems like you're right, could you leave a TODO(justin) for me to revisit this and fix it (or fix it to match postgres yourself if you care to :D)?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/builtins.go, line 3223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-LM8-SEH-THpavdnrkDI:-LM8OKtM2DzKet0fxC_f:b-zg57ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/c04bd9722832b0e277ca89eb1288fa142b7edaaa/pkg/sql/sem/builtins/builtins.go#L3223)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Hm, that was my doing, but I guess it was wrong? I'm not sure why I thought that was the behaviour but it seems like you're right, could you leave a TODO(justin) for me to revisit this and fix it (or fix it to match postgres yourself if you care to :D)?
</blockquote></details>

Done. I've changed both jsonb_insert and jsonb_set to error when NULL is at any position of the path.

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30037#-:-LM8QBD3A7MAWENwt45i:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
