### PR TITLE
asim: better outputs for data-driven tests

### PR DESCRIPTION
**Pull request by wenyihu6**
**asim: sort before iterating over maps when printing**

Previously, the simulator iterates over an unordered map when formatting and
printing states, stores, and ranges, resulting in non-deterministic output. This
patch addresses the issue by sorting the maps by key before printing and
formatting.

Release note: none
Epic: none

---

**asim: better outputs for data-driven tests**

Previously, the randomized testing framework's output only indicates whether
each iteration passes. This lack of of detail makes checking the randomized
framework and debugging challenging. This patch adds more info to the output,
including the selected configurations, the initial state of each simulation.

Additionally, this patch removes the verbosity flag for printing history plots
as it does not seem to have any practical use cases.

New verbosity flags for eval are now supported.
```
"eval"
[verbose=(<[]("result_only","test_settings","initial_state","config_gen","topology","all")>)]
- verbose(default value is OutputResultOnly): used to set flags on what to
   show in the test output messages. By default, all details are displayed
   upon assertion failure.
   - result_only: only shows whether the test passed or failed, along with
   any failure messages
   - test_settings: displays settings used for the repeated tests
   - initial_state: displays the initial state of each test iteration
   - config_gen: displays the input configurations generated for each test
   iteration
   - topology: displays the topology of cluster configurations
   - all: displays everything above
```

Part Of: https://github.com/cockroachdb/cockroach/issues/106311
Release Note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
First five commits are from https://github.com/cockroachdb/cockroach/pull/107957.

**Comment by wenyihu6** [comment]
Please only review the last two commits. The preceding commits are from https://github.com/cockroachdb/cockroach/pull/107957.

**Review by kvoli — APPROVED** [review]
A couple non-blocking questions.

> Reviewed 2 of 2 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-:-NccsTYV6uaCSuZRJ5oK:b-clwi8g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/asim/gen/generator.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-Nccqet56sGR9pNkI0gy:-Nccqet56sGR9pNkI0gz:bg1y0pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/gen/generator.go#L121)):*
> ```Go
> 
> func (bl BasicLoad) String() string {
> 	return fmt.Sprintf("basic load with rw_ratio=%0.2f, rate=%0.2f, skewed_access=%t, min_block_size=%d, max_block_size=%d, min_key=%d, max_key=%d", bl.RWRatio, bl.Rate, bl.SkewedAccess, bl.MinBlockSize, bl.MaxBlockSize, bl.MinKey, bl.MaxKey)
> ```

nit: truncate to 80 chars
___
*[`pkg/kv/kvserver/asim/state/state.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-Nccr1OBDBJ-F0ehcnW2:-Nccr1OBDBJ-F0ehcnW3:bbm0buw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/state/state.go#L60)):*
> ```Go
> 	// PrettyPrint returns a pretty formatted string representation of the
> 	// state (more concise than String()).
> 	PrettyPrint() string
> ```

nit: perhaps `CompactPrint`?
___
*[`pkg/kv/kvserver/asim/tests/output.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-NccsLit2VD0CPf7Nrw4:-NccsLit2VD0CPf7Nrw5:b-5u515) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/tests/output.go#L27)):*
> ```Go
> 
> const (
> 	// OutputResultOnly only shows whether the test passed or failed, along with
> ```

Was there a compelling reason to use a bitset, instead of a struct?
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-NccrgKb2fzkqlPc3FAa:-NccrgKb2fzkqlPc3FAb:bqgqm2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L136)):*
> ```
> # factor of 1. Assertion failures on some samples are expected due to this
> # factor. When there is only one replica, the removal target in rebalancing is a
> # leaseholder, it is locked into the current replica distribution. The
> ```

Could you clarify "it is locked into the current replica distribution"?
___
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-NccraYl2uCnhI1Nrz6d:-NccraYl2uCnhI1Nrz6e:b-ijefe9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L138)):*
> ```
> # leaseholder, it is locked into the current replica distribution. The
> # rebalancer falls back to adding one replica, hoping the rebalancing would
> # happen next time this range is checked. This can case thrashing where settling
> ```

nit: cause

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/state/state.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-Nccr1OBDBJ-F0ehcnW2:-Ncd-iJ_5Z0E5Rwh1k1b:b-85chv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/state/state.go#L60)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: perhaps `CompactPrint`?
</blockquote></details>

I feel `prettyPrint` aligns better with our repo's naming conventions. I didn't find across any functions named `compactPrint`, but there were quite a few named with `PrettyPrint`.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/output.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-NccsLit2VD0CPf7Nrw4:-NcczEij323-EzM20iXL:b-ycg1rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/tests/output.go#L27)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Was there a compelling reason to use a bitset, instead of a struct?
</blockquote></details>

If we use structs here, we would need to create a boolean field for each flag and explicitly checking each field's boolean value. I think using bitset here achieves the same goal but in a cleaner and more efficient way.

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108059#-NccrgKb2fzkqlPc3FAa:-Ncd1jFL4SqYLglMQ24W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac5e1038f4acaca06abaaae61c4a743979e73638/pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges#L136)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you clarify "it is locked into the current replica distribution"?
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
After the PR approval, I did two smaller changes 1. Renamed `GetCurrTime()` to `Curr() `and `GetState()` to `State()`. (I just learned that it is recommended to avoid naming functions with get as prefix based on Golang's best practice https://google.github.io/styleguide/go/decisions#getters.) 2. Initially, we used a variable to track indexes for map iterating. Now, we use the slice for all map iteration, and we can now use slice's index to track positions. I made the changes to two places where map iterations happen but missed one other. I corrected that overlook.

**Comment by wenyihu6** [comment]
TFTR! 

bors r=kvoli

**Pull request merged**
