### PR TITLE
opt: add join order benchmark to tests

### PR DESCRIPTION
**Pull request by madhavsuresh**
The join order benchmark appeared in "How Good are Query Optimizers, Really?".
https://github.com/gregrahn/join-order-benchmark

Release note: None

### CODE REVIEW

**Review by madhavsuresh — COMMENTED** [review]
TFTR!

Done. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29606#-:-LLfQRjzD2MpBuLXz0Bv:b-ezqy3k)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — COMMENTED** [review]
Oops sorry looks like you already had some info there. Anyway, adding the citation is good too.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29606#-:-LLfQuzQ3oK_i9NFeNtG:b-axru2j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29606#-:-LLfUs2R3JLJsY0DnwEq:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by madhavsuresh** [comment]
That's fair. I will hold off for now and open an issue for this.

**Pull request closed without merging**
