### PR TITLE
cli: add a `cockroach workload` subcommand

### PR DESCRIPTION
**Pull request by danhhz**
Only a selection of the current workloads are included to allow the
others to mature and prove their usefulness to users.

The following cobra command hierarchy is established under `cockroach
workload`:

    check         a running cluster's data for consistency
        [generator]
    csv-server    serves csv table data through an HTTP interface
    init          set up tables for a workload
        [generator]
    run           run a workload's operations against a cluster
        [generator]
    fixtures      tools for quickly synthesizing and loading large datasets
        list          list all fixtures stored on GCS
        make          regenerate and store a fixture on GCS
            [generator]
        load          load a fixture into a running cluster. An enterprise license is required.
            [generator]
        url           generate the GCS URL for a fixture
            [generator]

bin/workload is unchanged and contains the full list of all workloads.

Release note (cli change): A `cockroach workload` subcommand has been
added which provides various generators for data and query loads and
tools for working with them.

### CODE REVIEW

**Comment by danhhz** [comment]
I'm still undecided on whether we should include the `fixtures` stuff, in particular `fixtures make`. Pretty sure we can check some sort of `requester pays` option on our fixtures bucket that will let other people use our fixtures without charging us, but I haven't actually tried it out.

**Comment by danhhz** [comment]
Also needs tests. Making sure that all of bin/workload, cockroach, and cockroachoss all do the right thing is surprisingly subtle.

**Review by benesch — APPROVED** [review]
:lgtm_strong: though agreed that we need to do something about fixtures. Would prefer to either sort out the requester-pays stuff or remove `cockroach workload fixtures` before this goes in so we don't forget.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-:-LKWrmYjEbQFcSS-GStA:b7skiyq)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/cli/cli.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-LKWqYTq93eR92yqF3L-:-LKWqYTq93eR92yqF3L0:b-n5p56q) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa74a4527ccb164f7a76bf6332cbb915aa90063/pkg/workload/cli/cli.go#L34)):*
> ```Go
> 	}
> 	return rootCmd
> }
> ```

nit: kind of odd that this returns a new `cobra.Command` on every call. I think I would have done:

```go
var RootCmd = SetCmdDefaults(&cobra.Command...)

func AddSubCmd(fn func() *cobra.Command) {
    RootCmd.AddCommand(fn)
}
```

If you keep it as is, maybe at least update the docstring to "WorkloadCmd returns a new command that can serve as the root of the workload command tree" or somesuch.
___
*[pkg/workload/cli/cli.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-LKWriD0Bhhvbrb5vZKa:-LKWriD0Bhhvbrb5vZKb:btwisfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa74a4527ccb164f7a76bf6332cbb915aa90063/pkg/workload/cli/cli.go#L39)):*
> ```Go
> 
> // AddSubCmd adds a sub-command closure to the workload cli. This is a closure
> // so we can call `workload.Register` in any init function.
> ```

Hrm. I'm not following why this needs to be a closure.

**Review by danhhz — COMMENTED** [review]
TFTR! Ready for another look

Added support for requestor pays, which also required plumbing export storage. Any thoughts on what to do for the sysutil vs syscall lint failure? The stuff being used here isn't present in sysutil, so dunno if I should be blindly adding it or what

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-:-LKXkh1uCyDW0Fu-O6jX:by59xl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/cli/cli.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-LKWqYTq93eR92yqF3L-:-LKXkc5w2B6Z04QEF4cj:b3rid09) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa74a4527ccb164f7a76bf6332cbb915aa90063/pkg/workload/cli/cli.go#L34)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: kind of odd that this returns a new `cobra.Command` on every call. I think I would have done:

```go
var RootCmd = SetCmdDefaults(&cobra.Command...)

func AddSubCmd(fn func() *cobra.Command) {
    RootCmd.AddCommand(fn)
}
```

If you keep it as is, maybe at least update the docstring to "WorkloadCmd returns a new command that can serve as the root of the workload command tree" or somesuch.
</blockquote></details>

Added some docs about why we have to do this. Make more sense?
___
*[pkg/workload/cli/cli.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-LKWriD0Bhhvbrb5vZKa:-LKXkfAU4criEQia7jt8:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfa74a4527ccb164f7a76bf6332cbb915aa90063/pkg/workload/cli/cli.go#L39)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Hrm. I'm not following why this needs to be a closure.
</blockquote></details>

Ditto

**Review by benesch — APPROVED** [review]
Ah, yeah, pkg/cmd is exempt from the exclusion on `syscall`, but now that this is getting included in the binary itself we need to be more careful.

You should do what we do in pkg/cli/start_{unix,windows}.go. Create a file run_unix.go that has

```go
var exitSignals = []os.Signal{unix.SIGINT, unix.SIGTERM}
```

and `run_windows.go` that has:

```go
var exitSignals = []os.Signal{os.Interrupt}
```

Then use that variable in `runRun` instead of referring to `syscall.FOOSIGNAL` directly.

> Reviewed 10 of 10 files at r2, 4 of 4 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-:-LKXnSo-4yxk3UhQcGz_:bhwez9u)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by danhhz — COMMENTED** [review]
Awesome, that worked perfectly (and would have taken me forever to logic out). Added a couple tests for good measure. Borsing on green

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-:-LKYCXk3C1MS3uFN62XF:b-s1u6xx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by danhhz** [comment]
bors r=benesch

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28390)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/cli/run.go, line 348 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28390#-LKYGfcwCTV664HuWWbY:-LKYGfcx7zJAmnWnI7g5:b9s64zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/13b1795ba5ee58422fd6bca0cbbb36457584eea5/pkg/workload/cli/run.go#L348)):*
> ```Go
> 		go func() {
> 			time.Sleep(*duration + *ramp)
> 			done <- os.Interrupt
> ```

don't even sweat this a little, but idiom here is `sysutil.Signal(0)`

**Pull request merged**
