### PR TITLE
ui: Adding TransactionsPageConnected for Cluster UI 21.2

### PR DESCRIPTION
**Pull request by nathanstilwell**
Added a transactionsPageConnected to cluster-ui for use in the published
package. Also added the associated reducer, sagas, and selectors to
support the connection with a Redux store.

I made a slight adjustment with the prop types of transactionsPage for
clarity and to align with other page components.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66036#-:-MbM65aLAThzdFjxyb-r:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)

**Review by koorosh — COMMENTED** [review]
LGTM in general 👍🏼 , with only one request to change, could you re-export transactions page in `pkg/ui/cluster-ui/src/index.ts` as well? it's necessary to import this components in CC.

**Pull request merged**
