### PR TITLE
opt: extract redundant subclauses in OR expressions

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds two rules to transform OR expressions.

One rule extracts redundant subclauses from the list of OR conditions, and
replaces the OR with an AND of the subclause and the remaining OR expression
(a logically equivalent expression). For example:
  `(A AND B) OR (A AND C)`  =>  `A AND (B OR C)`

The other rule handles the case where extracting a redundant subclause from one
of the OR conditions would result in an empty condition. In this case, the
entire OR expression can be replaced with the subclause itself. For example:
  `A OR (A AND B)`  =>  `A`

These transformations are useful for finding a conjunct that can be pushed
down in the query tree. For example, if the redundant subclause is fully bound
by one side of a join, it can be pushed through the join, even if the other
conjuncts cannot.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:, nice rules, and great that we simplified a TPCH query

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/custom_funcs.go, line 629 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKhK0Q8vnn-0LhlHKN:-LFKhK0Q8vnn-0LhlHKO:b-ahv0h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/custom_funcs.go#L629)):*
> ```Go
> 
> 		default:
> 			// The default case should be fully handled by the ExtractRedundantClause
> ```

This comment is no longer true with the change you made to reduce time complexity.

---

*[pkg/sql/opt/norm/testdata/rules/bool, line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKhrLU0u6OSmdyxW7f:-LFKhrLU0u6OSmdyxW7g:b-juosz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/testdata/rules/bool#L555)):*
> ```
> 
> opt
> SELECT (a AND b) OR (c AND a) FROM c
> ```

Do you have case where a top-level redundant sub-clause is not the first disjunct, like:
`(a AND b) OR a OR (a AND c)`

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 1870 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKiIvOE3t59iH519y-:-LFKiIvOE3t59iH519y0:b-amr5om) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/xform/testdata/external/tpch#L1870)):*
> ```
> # of containers, and a range of sizes.
> #
> # TODO:
> ```

You can remove this comment now that you've done the work!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-:-LFKiBWG8NuwYzXQLFGE:b-rtdcoi)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/bool.opt, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKipeQ-7o2gO3LNvnb:-LFKipeQ-7o2gO3LNvnc:b-lnl8y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/rules/bool.opt#L149)):*
> ```
> # if B AND C cannot.
> [ExtractRedundantSubclause, Normalize]
> (Or $conditions:[ (And [ ... $item:* ... ]) ... ] & (IsRedundantSubclause $conditions $item))
> ```

As we chatted about, the initial `...` can be removed, since if the first item doesn't match `IsRedundantSubclause` then none of the other items will either. And since this rule handle cases where a top-level redundant clause is not the first item in the list, you can get ride of the initial `...` in the rule above as well. These simplifications give a nice time complexity win.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/rules/bool.opt, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKipeQ-7o2gO3LNvnb:-LFKjN814T1y0AbmCQ2n:byz59lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/rules/bool.opt#L149)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

As we chatted about, the initial `...` can be removed, since if the first item doesn't match `IsRedundantSubclause` then none of the other items will either. And since this rule handle cases where a top-level redundant clause is not the first item in the list, you can get ride of the initial `...` in the rule above as well. These simplifications give a nice time complexity win.
</blockquote></details>

I got rid of the `...` in front of the `And`, but I don't think I can get rid of the `...` in front of `$item`since we could have something like `(B AND A AND C) OR (D AND E AND A)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/rules/bool.opt, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKipeQ-7o2gO3LNvnb:-LFLbMj5Bg13GtVE1SoH:b-l1hi05) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/rules/bool.opt#L149)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I got rid of the `...` in front of the `And`, but I don't think I can get rid of the `...` in front of `$item`since we could have something like `(B AND A AND C) OR (D AND E AND A)`
</blockquote></details>

OK, makes sense. But you should be able to get rid of the `...` in front of the `ExtractRedundantClause` rule above, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808)*

**Comment by rytaft** [comment]
Thanks!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/custom_funcs.go, line 629 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKhK0Q8vnn-0LhlHKN:-LFNiXq64lYtDwq_a3YI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/custom_funcs.go#L629)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This comment is no longer true with the change you made to reduce time complexity.
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/rules/bool.opt, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKipeQ-7o2gO3LNvnb:-LFNiZ6SDJnYOn1YUL5-:b32jsqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/rules/bool.opt#L149)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

OK, makes sense. But you should be able to get rid of the `...` in front of the `ExtractRedundantClause` rule above, right?
</blockquote></details>

Ah great point! I thought we needed it for `(A AND B) OR A OR (A AND C)`, but that case is handled by the second rule. Fixed.

---

*[pkg/sql/opt/norm/testdata/rules/bool, line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKhrLU0u6OSmdyxW7f:-LFNimKD8RPSsmuhW66H:b-xnovht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/norm/testdata/rules/bool#L555)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Do you have case where a top-level redundant sub-clause is not the first disjunct, like:
`(a AND b) OR a OR (a AND c)`
</blockquote></details>

Good point - added.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 1870 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-LFKiIvOE3t59iH519y-:-LFNiw9GBcxOH4RIubuP:bmfxgaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98c8f2e6b5138cb19506239f2d3ee1101dbbf22/pkg/sql/opt/xform/testdata/external/tpch#L1870)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You can remove this comment now that you've done the work!
</blockquote></details>

Done :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-:-LFNjwP-EzOnCuvMEp8s:b-ucfknh)*

**Comment by rytaft** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26808#-:-LFNkbxz8D0qos19cUuf:b-ydi9ay)*

**Pull request merged**
