### PR TITLE
Embed AngluarJS.

### PR DESCRIPTION
**Pull request by BramGruneir**
This embeds AngularJS directly (and updates the version to the latest).
Once the fonts are embedded, the ui will not require any external dependancies.  This way, clusters without internet access will be able to use the ui.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Careful with the fonts. If you embed large things, we need to check whether that has unwanted consequences, such as large build times or having `go generate ./...` crash. I'm all for having no external dependencies, but maybe we can just use a default font if that's something that helps us. If we're going to have to embed a lot of binary large things anyways, we'll have to figure out a good way of doing it.

**Comment by tschottdorf** [comment]
since fonts aren't in this PR, LGTM.

**Comment by BramGruneir** [comment]
I agree, and I'm worried about the embedding process as a whole.  Not sure if we're using the best solution.  I plan to investigate other options.

**Comment by bdarnell** [comment]
@tschottdorf You may be surprised at what counts as a large file. angular.min.js is 44KB; the two fonts that we're using are 10.5KB and 11.4KB.

**Comment by tschottdorf** [comment]
Oh well. Yeah @BramGruneir there might be other options, worth looking into eventually.

**Pull request merged**
