### PR TITLE
cli: always reject extra positional arguments

### PR DESCRIPTION
**Pull request by benesch**
`cockroach gen autocomplete`, `cockroach gen man`, and `cockroach start`
didn't reject unrecognized positional arguments. In the case of start in
particular, command line options inadvertently specified as positional
arguments would be silently ignored. This commit adds the missing check
to those three commands, thus fixing #6201.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12901)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM but could use a few simple tests (examples, probably).

**Comment by knz** [comment]
+1 on tamir's suggestion.

Please follow model given by `TestQuit` to write a test that expects an error.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-:-KaMg_0YllfE9Tp-u3Lo:b-8t25cv)*

**Comment by benesch** [comment]
In the course of supporting CLI tests that don't autolaunch a server, I ended up refactoring more than I planned to. Let me know if you'd like a separate PR for the refactor (or for me to drop the refactor entirely).

**Comment by knz** [comment]
Mostly good. Please ensure you understand what the log.TestLogScope does and get that right.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 9 of 10 files at r3, 3 of 3 files at r4.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/cli_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-KaR7DoXwb76sn3B5dh-:-KaR7DoXwb76sn3B5dh0:bzckxzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/794eda95ca92dfed4c87c6d17cce7894a9326513/pkg/cli/cli_test.go#L73)):*
> ```Go
> 	fail := func(err interface{}) {
> 		if c.t != nil {
> 			c.t.Fatal(err)
> ```

Don't forget to call `c.logScope.Close(c.t)` here. This is especially important as if `StartServerRaw` fails the logs would be lost otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-:-KaR87vnso-HJokI67bW:b-y8soej)*

**Comment by benesch** [comment]
Updated with `logScope.Close` and go fmt-approved formatting.

---

Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cli/cli_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-KaR7DoXwb76sn3B5dh-:-KaTPohUPm6lq1Ds2Gnv:bufctbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/794eda95ca92dfed4c87c6d17cce7894a9326513/pkg/cli/cli_test.go#L73)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't forget to call `c.logScope.Close(c.t)` here. This is especially important as if `StartServerRaw` fails the logs would be lost otherwise.
</blockquote></details>

Ahh, thanks for catching that. FWIW, I think the original code got this wrong; `newCLITest` called `logScope.Close` before the test function itself called `t.Fatal`, so the `TestLogScope` saw a successful test and nuked the log directory. I adjusted the refactor to implement what I think is the correct behavior: defer calling `logScope.Close` until after calling `t.Fatal`, so that the log files hang around if `StartServerRaw` fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-:-KaTQUzcHXNhKt_LfW-z:b-lurqjf)*

**Comment by knz** [comment]
LGTM

---

Reviewed 11 of 13 files at r5, 2 of 2 files at r6, 10 of 10 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/cli_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-KaR7DoXwb76sn3B5dh-:-KagOnyIjd4rrqWLBh9w:b-hl4zwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/794eda95ca92dfed4c87c6d17cce7894a9326513/pkg/cli/cli_test.go#L73)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ahh, thanks for catching that. FWIW, I think the original code got this wrong; `newCLITest` called `logScope.Close` before the test function itself called `t.Fatal`, so the `TestLogScope` saw a successful test and nuked the log directory. I adjusted the refactor to implement what I think is the correct behavior: defer calling `logScope.Close` until after calling `t.Fatal`, so that the log files hang around if `StartServerRaw` fails.
</blockquote></details>

Good catch. Yes, this works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12901#-:-KagP_oq4hM1_qoIcaUF:bb6ywmx)*

**Comment by knz** [comment]
This is good work. Thanks for your contribution!

**Pull request merged**
