### PR TITLE
Parse the direction option for CREATE INDEX.

### PR DESCRIPTION
**Pull request by andreimatei**
Actually using this for encoding index entries and for queries is yet to
come.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3377)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 86 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K585Q2q3jIDWblGsLxL:-K585Q2q3jIDWblGsLxM:1924158987) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L86)):*
`make([]T, i, i)` is equivalent to `make([]T, i)`.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K5861Uzf_jIPlhE6MkE:1609521858) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
Should these be glued together instead of collected separately (similar to `IndexElem`)?

---

*[sql/parser/create.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586HiQ5ivtTsyzFWhM:-K586HiRxQxUfj1Vh4rS:1942085584) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L82)):*
`buf.WriteString(node.Name)` should work.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K586_WQWOm5jKx9bNDW:-1937115030) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
the `.String()` isn't necessary here.

---

*[sql/parser/parse_test.go, line 395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586izIr_HSnLDKhZjW:-K586izIr_HSnLDKhZjX:310709111) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fad0b1112201883a0b5f7bc031c6679de939b2/sql/parser/parse_test.go#L395)):*
why is this gone?

---

*[sql/parser/sql.go, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586x2etYugOGgpa57T:-K586x2etYugOGgpa57U:826318923) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fad0b1112201883a0b5f7bc031c6679de939b2/sql/parser/sql.go#L1)):*
Wonder if reviewable has options for omitting diffs like this. I thought GitHub did it.

---

*[sql/parser/sql.y, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587CGo3qgjDpVc_b3W:-K587CGo3qgjDpVc_b3X:-664499526) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L78)):*
trailing tab here

---

*[sql/parser/sql.y, line 1324 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587LY5zeJfmipxZWXN:-K587LY5zeJfmipxZWXO:-743192125) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L1324)):*
doesn't look like others are using tabs in this file.

---

*[sql/parser/sql.y, line 1324 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587_yd4DdSgOboUfek:-K587_yd4DdSgOboUfel:-257692035) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L1324)):*
can this be a value and not a pointer? I noticed that's how you use it above in `index_params`.

---

*[sql/structured.proto, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587gwMvk9XExonIk7A:-K587gwMvk9XExonIk7B:-117031271) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L69)):*
tabs here and below.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Your git settings seem to be messed up? author and commiter are not the same, hence github not showing your portrait on the commit. Can you fix this up and `git commit --amend --reset-author`?

**Comment by andreimatei** [comment]
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[sql/create.go, line 86 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K585Q2q3jIDWblGsLxL:-K58Nj8WAiOBKIEsNrGu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L86)):*
Done.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K58NK-9p9WfT0Q2PS9P:1861971289) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
mmmm I don't know. I've gone with this because we already have a parallel array in this proto. And to be honest it doesn't bother more. 
I'll take suggestions.

---

*[sql/parser/create.go, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586HiQ5ivtTsyzFWhM:-K58NGZT3iIFIP9PYbtm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L82)):*
Done.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K58NG6IKFjDoS3COYp9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
Done.

---

*[sql/parser/parse_test.go, line 395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586izIr_HSnLDKhZjW:-K58GW_iFIH85jOJDIh0:-1901822863) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fad0b1112201883a0b5f7bc031c6679de939b2/sql/parser/parse_test.go#L395)):*
it's not gone, it's moved up to the other test that has the list of commands that generate the same text after parsing as the original. Because we now don't ignore the asc/desc any more.

---

*[sql/parser/sql.y, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587CGo3qgjDpVc_b3W:-K58Gy2TRBOGLOnp9qKa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L78)):*
Done.

---

*[sql/parser/sql.y, line 1324 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587LY5zeJfmipxZWXN:-K58H4jfAkQFgAd0JVQK:726107686) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L1324)):*
yeah I need to set my editor right for all file types

---

*[sql/parser/sql.y, line 1324 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587_yd4DdSgOboUfek:-K58I2HW8SDiAMNvC5Z_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/sql.y#L1324)):*
Done.

---

*[sql/structured.proto, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K587gwMvk9XExonIk7A:-K58KfZI8lYt4sr1QNTD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L69)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by andreimatei** [comment]
@tamird I think I've fixed it, thanks!

---

Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-:-K58PW7JofKa-q2RnImY:-1627984311)*

**Comment by petermattis** [comment]
Review status: 4 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[sql/parser/parse_test.go, line 395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586izIr_HSnLDKhZjW:-K58NRs__RvtkjNOII0s:1822018438) ([raw file](https://github.com/cockroachdb/cockroach/blob/81fad0b1112201883a0b5f7bc031c6679de939b2/sql/parser/parse_test.go#L395)):*
These are test cases which parse but do not format the same output as their input. This case was moved to `TestParse` one now that it does format the same as its input.

---

*[sql/structured.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58PfW03BYpxIOPDtea:-K58PfW03BYpxIOPDteb:-641047305) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L82)):*
I'm guessing it was a lot easier to make a parallel array here rather than a single array combining name and direction. I'm ok with that, but we should put a check in `TableDescriptor.Validate` that `IndexDescriptor.column_{names,directions}` are the same size.

---

*[sql/testdata/create_index, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58O_JAvdxUrkb6HRtR:-K58O_JAvdxUrkb6HRtS:-509823971) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/testdata/create_index#L87)):*
You'll also want to test creation of these indexes inside of the `CREATE TABLE` statement.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Reviewed 4 of 9 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58S9nZjy96OjKI-tnA:-K58S9nZjy96OjKI-tnB:451299626) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/create.go#L89)):*
instead of this, you can just use: `indexDesc.ColumnNames = append(indexDesc.ColumNames, c.Column)`; a similar pattern can be applied to `indexDesc.ColumnDirections`.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K58RPW9xcZZbMCRT0uO:-314237945) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
This is a matter of taste, but you can also:
```go
var colStrs []string
for _, column := range node.Columns {
  colStrs = append(colStrs, column)
}

fmt.Fprintf(&buf, "ON %s (%s)", node.Table, strings.Join(colsStrs, ","))
```

---

*[sql/testdata/create_index, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58O_JAvdxUrkb6HRtR:-K58STOIFguzLBrN8NLa:-55892999) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/testdata/create_index#L87)):*
probably also inside `ALTER TABLE`

---

*[sql/testdata/create_index, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58SamsahnR3VdnCrbu:-K58SamsahnR3VdnCrbv:-456546246) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/testdata/create_index#L71)):*
i dont think you need this; you should already be root here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[sql/parser/create.go, line 67 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58bmgCplVj8nrt7e3l:-K58bmgCplVj8nrt7e3m:-1207515082) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/parser/create.go#L67)):*
for improved performance.

---

*[sql/structured.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58PfW03BYpxIOPDtea:-K58aMjwC3bhAcYv6Lsm:-1737134471) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L82)):*
Given that we already have column name, id and now direction as fields of a column, we might as well create a Elements field that starts of with storing the direction, and you can follow this change with another PR that moves the column name and id into it depending on how hard that is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K59ECzLMYTb_a-xDAYC:650527607) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
If the SQL guys don't mind, neither will I.

---

*[sql/create.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58S9nZjy96OjKI-tnA:-K59DmSzjdVXMsICZY0a:-1310332083) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/create.go#L89)):*
where the difference will be that you may see more allocs (since the slice may have to resize if it starts out `nil`). But you can use `indexDesc.ColumnNames = make(.., len(...), 0)` to initialize it and then it's equivalent to what you have.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K59EM-47QA2KsvxXHs2:-869330422) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
`colStrs := make([]string, len(node.Columns), 0)` for OCD.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K5ALM_o9aBKizVACGHL:1515900659) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
colStrs := make([]string, 0, len(node.Columns)) for more OCD.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58S9nZjy96OjKI-tnA:-K5Ahc0c-4IMDiD7gtaZ:-846471576) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/create.go#L89)):*
I think `indexDesc.ColumnNames = make(.., 0, len(...))` was what Tobias meant. You'd be setting the length of the slice to 0 (which will grow with append), but initializing the capacity to its desired size.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/structured.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58PfW03BYpxIOPDtea:-K5At7hwvC7t1p8LCKwf:186782288) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L82)):*
or even better, first refactor this in another PR to see if it's a lot of work putting it into a new Elements field.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K5BDjlLO4kIp57H5BJT:-21447392) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
It's probably worthwhile to see how difficult it would be to combine `Column{Names,IDs,Directions}` into a single array. But I'd consider that a cleanup PR and would prefer to see it handled separately from this one. I'd suggest filing an issue to perform that investigation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K58TVaPA0IESviJqZZx:-1833414786) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
Yeah, I'd do it in a separate PR. It's beginning to look like you want `struct{ColumnDescriptor,Direction}` as the array member.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K5BYgf2juwvFJ5rafSN:-1030445348) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
I'm not sure if we want the full `ColumnDescriptor` copied into every `IndexDescriptor` that references the column. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K5BZeS9Zxwa_s6rmrLi:-1549347484) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
Oh, right. Ignore that last bit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58S9nZjy96OjKI-tnA:-K5Bc-6vCsoZGcNxmZ4G:-710324071) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/create.go#L89)):*
yeah, I keep mixing this one up.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K5Bc6eeQsolnEt7qIpd:1136944149) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
it's not OCD if the previous thing is just plain wrong. :smile: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by andreimatei** [comment]
There's still something to do -> add the direction to whatever `SHOW INDEX` returns. Maybe `SHOW TABLE` too?

---

Review status: 3 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/create.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5861Uzf_jIPlhE6MkD:-K5BlNXA_zV0IJnD6yPN:629232749) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/create.go#L100)):*
I've filed https://github.com/cockroachdb/cockroach/issues/3387 to track the cleanup.

---

*[sql/create.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58S9nZjy96OjKI-tnA:-K5BjiWx5-AK6XJ6vR9M:1081980174) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/create.go#L89)):*
excellent, thanks

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K5C6DINXHE_U9GbTTq3:81574257) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
ah so Python, I love it. Thanks.

---

*[sql/parser/create.go, line 67 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58bmgCplVj8nrt7e3l:-K5Bl_-0IyTdkNed67JM:376894473) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/parser/create.go#L67)):*
"for improved reading performance" :)

---

*[sql/structured.proto, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58PfW03BYpxIOPDtea:-K5C6PH-62RgfR9i4Pmm:-607831199) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/structured.proto#L82)):*
this was discussed above too. I've filed an issue to track that cleanup later.

I've added a consistency check in `TableDescriptor.Validate` (extra methods on protos? nice)

---

*[sql/testdata/create_index, line 87 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58O_JAvdxUrkb6HRtR:-K5DAVyhbQVEOZY7AbBR:444111690) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/testdata/create_index#L87)):*
Added a CREATE TABLE in testdata/table, and in `parse_test.go`. But @tamird there's no modifying indexes in `ALTER TABLE`.

---

*[sql/testdata/create_index, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K58SamsahnR3VdnCrbu:-K5DAJcW4l6VDReWjAr_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/testdata/create_index#L71)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-:-K5DBFZi6Z9ryOczLb-f:-245890940)*

**Comment by andreimatei** [comment]
Review status: 3 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/parser/create.go, line 94 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K586_WPdMYwZqdYtvTj:-K5DC-Z7jJQenfYTbaiX:-1690113805) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac4ba069df7681f71f5768463bdd01d9ed3ac907/sql/parser/create.go#L94)):*
this moved to a new type, IndexElemList, because it was used for printing in other places too

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by tamird** [comment]
Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/structured.go, line 118 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5EjOD_SxUWnXT5Z6mC:-K5EjOD_SxUWnXT5Z6mD:-1818392855) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5df1e50a9145f947bb0025adf981121799c4756/sql/structured.go#L118)):*
`String()` is not needed here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by petermattis** [comment]
LGTM

We could display columns as `+foo` or `-foo` in `SHOW INDEX`. Or perhaps it would be better to add an additional column to the output. Probably best to file an issue and do that work in a follow-up PR.

---

Review status: 3 of 17 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[sql/testdata/table, line 58 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5GP9A0WlLL2HXWB8L7:-K5GP9A0WlLL2HXWB8L8:-49062908) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5df1e50a9145f947bb0025adf981121799c4756/sql/testdata/table#L58)):*
Looks like some tabs snuck into this file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-:-K5GPNSJvrkM0f2sB1LA:462911531)*

**Comment by andreimatei** [comment]
Review status: 3 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[sql/structured.go, line 118 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5EjOD_SxUWnXT5Z6mC:-K5HdpQeYYEAqBBDIcvX:-2058144840) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5df1e50a9145f947bb0025adf981121799c4756/sql/structured.go#L118)):*
Done. I've spent some time understanding why this is so :)

---

*[sql/testdata/table, line 58 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-K5GP9A0WlLL2HXWB8L7:-K5HS4ex77FrQKbSpStH:-1708596493) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5df1e50a9145f947bb0025adf981121799c4756/sql/testdata/table#L58)):*
Done. <simpsons once and for all meme>

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Comment by andreimatei** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/3414 to track SHOW INDEX

---

Review status: 3 of 17 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377#-:-K5HmNNqgG9hSz6yNkAy:1338501631)*

**Comment by tamird** [comment]
Reviewed 14 of 14 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3377)*

**Pull request merged**
