### PR TITLE
builtins: add memory accounting for ST_MakeLine/ST_Union aggregates

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54871)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54871#-MILNwlN6IFsReoU-gBA:-MILNwlN6IFsReoU-gBB:b-o1ud3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c79450fa1ac85938626528a635bddc3bf5354/pkg/sql/sem/builtins/aggregate_builtins.go#L675)):*
> ```Go
> 	switch g.(type) {
> 	case *geom.Point, *geom.LineString, *geom.MultiPoint:
> 		if err := agg.acc.Grow(ctx, int64(len(g.FlatCoords()))*int64(unsafe.Sizeof(g.FlatCoords()[0]))); err != nil {
> ```

can `g.FlatCoords` have length 0?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54871)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54871#-MILNwlN6IFsReoU-gBA:-MILPP_-0zGSMxUlUwWM:b2f7t4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3c79450fa1ac85938626528a635bddc3bf5354/pkg/sql/sem/builtins/aggregate_builtins.go#L675)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can `g.FlatCoords` have length 0?
</blockquote></details>

yep... fixed.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54871#-:-MIOxIp03x6vKZjW1DiY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
