### PR TITLE
storage: optimize range deletion

### LINKED ISSUE #12712: storage: slow Raft snapshot applies
While experimenting with serializing Raft snapshots on a test cluster, I discovered that applying Raft snapshots is often significantly slower than preemptive snapshots due to the need to clear the previous state. For example:

```
I170105 17:48:40.326807 6038497 storage/replica_raftstorage.go:577  [n3,s3,r1212/2:/Table/51/1/49{49976…-54512…},@c420d1d200] applying Raft snapshot at index 242041 (id=88094c9f, encoded size=67424150, 65 rocksdb batches, 408 log entries)
I170105 17:48:52.141188 6038497 storage/replica_raftstorage.go:585  [n3,s3,r1212/2:/Table/51/1/49{49976…-54512…},@c420d1d200] applied Raft snapshot in 11814ms [clear=9252ms batch=628ms entries=99ms commit=1169ms]
```

The above shows the encoded size of the snapshot is ~64MB (the range was about to be split). Applying the RocksDB batches that are part of the snapshot into the local batch took 628ms. Committing the local batch took 1169ms. But clearing the previous replica state took 9252ms! The RocksDB `DeleteRange` operation will almost certainly help here (see https://github.com/cockroachdb/cockroach/issues/9663), but 9252ms is still surprisingly high for what amounts to iterating over the current replica data and issuing `Batch.Clear` calls. 

Looking on the sender side I see:

```
I170105 17:48:40.326392 190 storage/store.go:3282  [raftsnapshot,n5,s5,r1212/3:/Table/51/1/49{49976…-54512…},@c420d13800] streamed snapshot: kv pairs: 470426, log entries: 408
```

Looking at the code, I don't see anything egregiously wrong with the clearing loop:

```
	iter := NewReplicaDataIterator(s.Desc, r.store.Engine(), false /* !replicatedOnly */)
	defer iter.Close()
	for ; iter.Valid(); iter.Next() {
		if err := distinctBatch.Clear(iter.Key()); err != nil {
			return err
		}
	}
```

But one thing that might be occurring is excessive allocations. Each call to `iter.Key` will copy the key from C++.

### PR DESCRIPTION
**Pull request by petermattis**
Optimize deletion of a range of keys by changing the implementation from
iterating over the keys in Go to doing the work in C++. This avoids a
significant number of allocations and cgo calls, though additional
experimentation shows that it is the reduction in cgo calls (not the
reduction in allocations) the provided the bulk of the speedup.

```
name                  old time/op    new time/op    delta
ClearRange_RocksDB-8     424ms ± 4%     226ms ± 3%   -46.72%  (p=0.000 n=10+10)

name                  old speed      new speed      delta
ClearRange_RocksDB-8   158MB/s ± 4%   297MB/s ± 3%   +87.65%  (p=0.000 n=10+10)

name                  old allocs/op  new allocs/op  delta
ClearRange_RocksDB-8      479k ± 0%        0k ± 0%  -100.00%   (p=0.000 n=6+10)
```

This also paves the way for using the RocksDB DeleteRange operation when
it becomes available.

Fixes #12712

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12745)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: though did not review C++

---

Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/engine/bench_test.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_pVzgemBXlMuKzqJGs:-K_pVzgf5RiEN8WpOZJ3:b9dfvez) ([raw file](https://github.com/cockroachdb/cockroach/blob/467cda1d43440e48cf5ca039c8278594ebcf05e0/pkg/storage/engine/bench_test.go#L601)):*
> ```Go
> 	const rangeBytes = 64 << 20
> 	const valueBytes = 92
> 	const overhead = 48 // Per key/value overhead (empirically determined)
> ```

can you hoist this constant out into package scope? this is the 4th copy. possibly a bunch more boilerplate duplicated here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-:-K_pXH4aIXjM9B1xHQ3o:b-k0ndmp)*

**Comment by petermattis** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/engine/bench_test.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_pVzgemBXlMuKzqJGs:-K_pacdYGBhE1-L25_Vy:belf26l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b4f64ecea6d6cb01d7af845832d5bad973081df/pkg/storage/engine/bench_test.go#L601)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you hoist this constant out into package scope? this is the 4th copy. possibly a bunch more boilerplate duplicated here.
</blockquote></details>

Done. There is a bunch of boilerplate, but I don't think the repetition is harmful. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745)*

**Comment by petermattis** [comment]
I added another commit which uses a write-only batch for the replica data deletion in `Replica.destroyDataRaftMuLocked`.

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 6 of 9 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 714 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_yhMuu_sTGpS_0b89y:-K_yhMuu_sTGpS_0b89z:b-mc05fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6ad6c86cf844040eea0879b5c4243e51c3f75e/pkg/storage/replica.go#L714)):*
> ```Go
> 	defer batch.Close()
> 
> 	for _, keyRange := range makeAllKeyRanges(r.Desc()) {
> ```

Keep the old comment about using `r.Desc()` instead of `consistentDesc`.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1919 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_yjKutbFVIwPm8wLao:-K_yjKutbFVIwPm8wLap:bomo6ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6ad6c86cf844040eea0879b5c4243e51c3f75e/pkg/storage/engine/rocksdb/db.cc#L1919)):*
> ```cpp
>   opts.prefix_same_as_start = prefix;
>   opts.total_order_seek = !prefix;
>   iter->rep.reset(rep->NewIterator(opts));
> ```

This implementation of `NewIter` is safe only if it is the first thing done on the `WriteOnlyBatch`. If something else had been written earlier, the iterator wouldn't see it. Maybe it would be less error-prone if `Engine.ClearRange` took an iterator as an argument to make it explicit when the iterator is coming from a different db view than the batch. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-:-K_yk-e9B9j0S5e1KDL9:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 714 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_yhMuu_sTGpS_0b89y:-Ka-rurMnPJvv36JqDIa:bmmihr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6ad6c86cf844040eea0879b5c4243e51c3f75e/pkg/storage/replica.go#L714)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Keep the old comment about using `r.Desc()` instead of `consistentDesc`.
</blockquote></details>

Oops, didn't mean to remove that. Re-added.

---

*[pkg/storage/engine/rocksdb/db.cc, line 1919 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745#-K_yjKutbFVIwPm8wLao:-Ka-s1rjssW6c6lKZ_-X:b-aqk2qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6ad6c86cf844040eea0879b5c4243e51c3f75e/pkg/storage/engine/rocksdb/db.cc#L1919)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This implementation of `NewIter` is safe only if it is the first thing done on the `WriteOnlyBatch`. If something else had been written earlier, the iterator wouldn't see it. Maybe it would be less error-prone if `Engine.ClearRange` took an iterator as an argument to make it explicit when the iterator is coming from a different db view than the batch. 
</blockquote></details>

Heh, that's the way I originally had it, but removed the iterator to make it compatible with the RocksDB `DeleteRange` operation. I'll add the iterator back for now. It's easy enough to remove when `DeleteRange` arrives.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12745)*

**Pull request merged**
