### PR TITLE
sql: convert all populate vtables into generate vtables

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit modifies all of the explicit users of the populate API into
users of the generate API. The only remaining case are the ones that use
the virtual index machinery. Those will be changed next.

Release note (performance improvement): most virtual tables will use less memory

### CODE REVIEW

**Comment by jordanlewis** [comment]
@rohany, just realizing this redoes some of the work in your other PR - sorry about that.

**Comment by rohany** [comment]
who cares about adding 4 tables in a pr when this one does all 100 of them

**Comment by jordanlewis** [comment]
😂 

Not sure how we're going to review this. To be honest, I didn't really review it myself yet. Let's let tests run - I'm sure something will fail.

**Comment by rohany** [comment]
I was just thinking the same thing... "accepting" this amount of changes doesn't really  mean that i can say all 3000 lines of changes look correct

**Comment by yuzefovich** [comment]
Nice branch name :)

**Comment by rohany** [comment]
Can we close this now?

**Pull request closed without merging**
