### PR TITLE
release-19.2: backport date_trunc and extract fixes

### PR DESCRIPTION
**Pull request by otan**
This is important for the cockroach-django release.

Backport:
  * 1/1 commits from "sql/parser: support string values in EXTRACT arguments" (#41429)
  * 1/1 commits from "sql/sem/builtins: support more time spans for EXTRACT and DATE_TRUNC" (#41784)
  * 1/1 commits from "sql: fix handling of date_trunc with alternate timezones" (#42006)
  * 1/1 commits from "builtins: fix incorrect timezone conversions for `extract` and `date_trunc`" (#42267)
  * 1/1 commits from "builtins: fix remaining incorrect MakeDTimestampTZFromDate usages" (#42324)
  * 1/1 commits from "sql/sem/builtins: make EXTRACT return float" (#42131)
  * 1/1 commits from "builtins: make date_trunc(week, timestamp[tz]) truncate to Monday" (#42622)
  * 1/1 commits from "builtins: fix extract from timestamptz to be ctx time zone aware" (#42632)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
LGTM! for backports, you can just press the green merge button

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42678#-:-LuJe_v90eawuHDI2H1L:b-qahu6i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by jordanlewis** [comment]
I think we have to be careful here, because there are several backward incompatible changes in this PR that change output types.

I'm not so sure whether this can realistically get merged into a patch release. Imagine a customer who needed to upgrade to a new patch release to get around a bug, and then also encountered a data type change that causes them to need to change their app.

I might have been inconsistent about my opinion here, but I don't know if we really should be backporting this.

**Comment by otan** [comment]
Discussed this in 1:1 with @jordanlewis, we should probably not include the time changes at the very least. I'll do this again with that principle.

**Comment by jordanlewis** [comment]
s/the time changes/the type changes/ right? :)

**Comment by otan** [comment]
that's totally what i wrote the whole time! 

but yes :D

**Pull request closed without merging**
