### PR TITLE
backupccl: add telemetry

### LINKED ISSUE #46518: Backup Telemetry: Identify whether a backup was full or incremental
**Is your feature request related to a problem? Please describe.**
With the new Backup UX, we can't use statement stats to identify whether a backup taken was full or incremental

**Describe the solution you'd like**
Tracking to be able to tie a job_id / statement_id to whether it was incremental or full

### LINKED ISSUE #46520: Backup Telemetry: Locality aware backup vs. not
**Describe the solution you'd like**
A way to understand if a `BACKUP` being taken is locality aware or not

**Additional context**
Not sure this is possible today with statement stats. This would give us insight into the usage (and by proxy importance) and relative performance.

### LINKED ISSUE #46521: Backup Telemetry: Ability to measure performance of backups
**Describe the solution you'd like**
As we're thinking about improving backup performance, we want to be able to know whether we've made those improvements or not. The ability to tie together:
* Throughput
* Size of the backup
* Where the backup is sent to
* Elapsed time

**Additional context**
At the end of the day, the goal is to understand the extent of our improvements. This may not be the answer. If there is another better way, let's open another issue and link + close this one.

### PR DESCRIPTION
**Pull request by dt**
This adds counters to usage of various features of BACKUP and RESTORE:
  - if encryption is used
 - if full-cluster is used
 - if incremental is used, either explicitly or automatically
 - total, succeeded and failed counts as well as runtime, size and throughput

These should help us measure how BACKUP and RESTORE are used and are behaving in the wild and where to direct our future efforts.

Fixes #46518 
Fixes #46520 
Fixes #46521

Release note (enterprise change): BACKUP and RESTORE now collect some anonymous telemetry on throughput and feature usage.

Release justification: low-risk, high impact.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @mwang1026)

___
*[pkg/ccl/backupccl/backup_job.go, line 580 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g-wQa0q1HAHK2UvEH:-M3g-wQa0q1HAHK2UvEI:b-y7b17m) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/backup_job.go#L580)):*
> ```Go
> 			telemetry.CountBucketed("backup.size-mb.inc", sizeMb)
> 			telemetry.CountBucketed("backup.speed-mbps.inc.total", mbps)
> 			telemetry.CountBucketed("backup.speed-mbps.full.per-node", mbps/int64(numClusterNodes))
> ```

Should this be `backup.speed-mbps.inc.per-node`? (s/full/inc/)
___
*[pkg/ccl/backupccl/backup_job.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g09yx6f4yOeDQ-kWV:-M3g09yx6f4yOeDQ-kWW:bux23eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/backup_job.go#L608)):*
> ```Go
> func (b *backupResumer) OnFailOrCancel(ctx context.Context, phs interface{}) error {
> 	telemetry.Count("backup.total.failed")
> 	telemetry.CountBucketed("backup.duration-sec.failed",
> ```

Similarly to my previous comment, is it interesting to consider which types of backups are failing/being cancelled. It would also be nice if there was a way to differentiate between failing and cancelling...
___
*[pkg/ccl/backupccl/restore_job.go, line 1125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g-kJyAa1ESFsaqbdJ:-M3g-kJyAa1ESFsaqbdK:bi6gd97) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/restore_job.go#L1125)):*
> ```Go
> // change stuff to delete the keys in the background.
> func (r *restoreResumer) OnFailOrCancel(ctx context.Context, phs interface{}) error {
> 	telemetry.Count("restore.total.failed")
> ```

Would it be useful to track how many of the failed restores were full-cluster vs not? (Since w'ere tracking the percentage of restores that are full cluster restores.)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mwang1026 and @pbardea)

___
*[pkg/ccl/backupccl/backup_job.go, line 580 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g-wQa0q1HAHK2UvEH:-M3gCfPg87Q10vusH9kw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/backup_job.go#L580)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should this be `backup.speed-mbps.inc.per-node`? (s/full/inc/)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_job.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g09yx6f4yOeDQ-kWV:-M3gDO9n4HMQw3aBndn0:b7qp2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/backup_job.go#L608)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Similarly to my previous comment, is it interesting to consider which types of backups are failing/being cancelled. It would also be nice if there was a way to differentiate between failing and cancelling...
</blockquote></details>

Agreed, though I think those would be _in addition_ to the top level count, so I'm inclined to proceed with this for now (in the interest of making 20.1 branch cut) and add that later. 
___
*[pkg/ccl/backupccl/restore_job.go, line 1125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46716#-M3g-kJyAa1ESFsaqbdJ:-M3gDk3O72sObz5zhAyw:b-2atgw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/674c19047151220c4edb98820596a9b129f043b6/pkg/ccl/backupccl/restore_job.go#L1125)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Would it be useful to track how many of the failed restores were full-cluster vs not? (Since w'ere tracking the percentage of restores that are full cluster restores.)
</blockquote></details>

ditto above.

Also, to act on that info, we'd probably need more info about the actual failure too, so we might need to rely on bug reports here for now.

**Review by pbardea — APPROVED** [review]
LGTM

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
