### PR TITLE
ccl/sqlproxyccl: add a test of closing the underlying connection

### PR DESCRIPTION
**Pull request by jbowens**
Release note: none

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: assuming I'm understanding the test correctly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57385#-:-MN_aKvg7XjPB59XMoYB:b7ani2p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @petermattis, and @spaskob)

___
*[pkg/ccl/sqlproxyccl/proxy_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57385#-MN_a2qZ-IDLklgKsGkq:-MN_a2qZ-IDLklgKsGkr:bnwp433) ([raw file](https://github.com/cockroachdb/cockroach/blob/3329dc9965fa447105aa62d66b98cb76cccee47d/pkg/ccl/sqlproxyccl/proxy_test.go#L257)):*
> ```Go
> 
> func TestProxyTLSClose(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> ```

Is this what is actually testing that that the `io.Copy` goroutines are being torn down correctly when `Close()` is called? Might be worth a comment somewhere in this test if that is accurate as I generally think of the `leaktest` checks as being boilerplate, but in this case it is a critical part of the test.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57385)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @spaskob)

___
*[pkg/ccl/sqlproxyccl/proxy_test.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57385#-MN_cptkEfkNXR8qRtf7:-MN_cptkEfkNXR8qRtf8:b-3saqj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3329dc9965fa447105aa62d66b98cb76cccee47d/pkg/ccl/sqlproxyccl/proxy_test.go#L289)):*
> ```Go
> 		incomingConn := proxyIncomingConn.Load().(*Conn)
> 		require.NoError(t, incomingConn.Close())
> 		<-incomingConn.Done() // should immediately proceed
> ```

I think the unused lint hack for `Conn.Done` can be removed.

**Review by spaskob — APPROVED** [review]
thanks for adding the test!

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57385)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/ccl/sqlproxyccl/proxy_test.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57385#-MN_a2qZ-IDLklgKsGkq:-MNeGeSsA-9bYAY7MmMO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3329dc9965fa447105aa62d66b98cb76cccee47d/pkg/ccl/sqlproxyccl/proxy_test.go#L257)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this what is actually testing that that the `io.Copy` goroutines are being torn down correctly when `Close()` is called? Might be worth a comment somewhere in this test if that is accurate as I generally think of the `leaktest` checks as being boilerplate, but in this case it is a critical part of the test.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy_test.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57385#-MN_cptkEfkNXR8qRtf7:-MNeGf2CBLOUicG4zOUp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3329dc9965fa447105aa62d66b98cb76cccee47d/pkg/ccl/sqlproxyccl/proxy_test.go#L289)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think the unused lint hack for `Conn.Done` can be removed.
</blockquote></details>

Done.

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
