### PR TITLE
distsqlrun: use SubtractSpans helper to update ResumeSpans

### PR DESCRIPTION
**Pull request by dt**
This is intended to pave the way for marking multiple resume spans as done at once, but for now it just introduces the helper and converts the existing usage/test to call it.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@dt the test is failing with this PR

**Comment by dt** [comment]
yeah, I'd pushed before running tests to run to a meeting to see what the CI thought of it -- fixed the lint error now and have added a randomized test at @RaduBerinde's suggestion. To make that practical, I had to change the handling of subtracting ranges not actually covered slightly -- it used to panic if you tried to subtract a subspace not covered, whereas it now simply subtracts whatever regions overlap.

**Comment by dt** [comment]
@danhhz and @RaduBerinde the first commit is kinda similar to some tricky span or covering merging/splitting helpers you've written before in case either of you wanted to give that one a look.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, @lucy-zhang, @RaduBerinde, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1eJYH4OD6wT28NADN:-Lc1eJYH4OD6wT28NADO:b7ynqe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L105)):*
> ```Go
> }
> 
> // SubtractSpans subtracts one partial covering from another.
> ```

does "partial covering" means that `todo` and `done` must contain non-overlapping spans? If that's the case, mention it explicitly.
___
*[pkg/roachpb/merge_spans.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1erNr7qkuH0Ans2tR:-Lc1erNr7qkuH0Ans2tS:bkatu1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L124)):*
> ```Go
> 
> 	remaining := make(Spans, 0, len(todo))
> ```

There are many cases inside this code.. Would it make things simpler if we first made an "inverted" copy of `done`, and then intersected that with `todo`? (inverting is easy to do only if `done` has non-overlapping spans)
___
*[pkg/roachpb/merge_spans.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gEFNA-1d9uD72l-b:-Lc1gEFNA-1d9uD72l-c:byei557) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L129)):*
> ```Go
> 	for t < len(todo) && d < len(done) {
> 		// if we've shrunk the todo span to nothing, skip it.
> 		if todo[t].Key.Equal(todo[t].EndKey) {
> ```

[nit] it would be much easier to read if we did `tStart, tEnd := todo[t].Key, todo[t].EndKey` and same for `dStart, dEnd` and used those
___
*[pkg/roachpb/merge_spans.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gnq6CBBvye97pt2h:-Lc1gnq6CBBvye97pt2i:b-rec58g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L149)):*
> ```Go
> 		}
> 
> 		keyCmp := done[d].Key.Compare(todo[t].Key)
> ```

[nit] It's more intuitive if `todo` is always on the left side of these comparisons (at least to me - I think of `todo` as the "left side" of the operation)
___
*[pkg/roachpb/merge_spans.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1h4Id2EuyT0iHGu1y:-Lc1h4Id2EuyT0iHGu1z:b-r7gifk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L150)):*
> ```Go
> 
> 		keyCmp := done[d].Key.Compare(todo[t].Key)
> 		endCmd := done[d].EndKey.Compare(todo[t].EndKey)
> ```

endCmp
___
*[pkg/roachpb/merge_spans.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gfrH5LGEBfbG0bCK:-Lc1gfrH5LGEBfbG0bCL:b-e1848x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L154)):*
> ```Go
> 		// We can't subtract something that isn't in todo, so discard up to todo.
> 		if keyCmp < 0 {
> 			done[d].Key = todo[t].Key
> ```

I'd move this case inside the branch below and make that `if keyCmp <= 0` rather than modifying `keyCmp`
___
*[pkg/roachpb/merge_spans.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1hBuY83hprZ1A4-uV:-Lc1hBuY83hprZ1A4-uW:baovo3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L169)):*
> ```Go
> 			} else if endCmd > 0 {
> 				// Matches all of todo and more: remove todo, update done to remainder.
> 				done[d].Key = todo[t].EndKey
> ```

What does modifying `done` get us? (here and in a few other places)  I'd think that we shouldn't care if the start key is earlier than we need, we could just tolerate that.
___
*[pkg/roachpb/merge_spans.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1hbX237Y9HypWqtJt:-Lc1hbX237Y9HypWqtJu:b-yexics) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L172)):*
> ```Go
> 				t++
> 			} else {
> 				panic("unreachable: does not end before, at or after")
> ```

I don't understand this pattern. Do we really need a panic for this "case"? Why not just convert the last `else if` to `else`. These could also be a `switch`.
___
*[pkg/roachpb/merge_spans.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1jeLJCjojtW0SXitl:-Lc1jeLJCjojtW0SXitm:bsac5jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L206)):*
> ```Go
> 	// Just append anything that's left, but first see if it should merge with the
> 	// last added remainder span.
> 	if t < len(todo) && len(remaining) > 1 && todo[t].Key.Equal(remaining[len(remaining)-1].EndKey) {
> ```

We could add a sentinel interval to `done` that is to the right of the last `todo` interval and have this part handled "for free".
___
*[pkg/roachpb/merge_spans_test.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1kFzBClOOv9RQMZzc:-Lc1kFzBClOOv9RQMZzd:b-797cvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L81)):*
> ```Go
> func makeRandomParitialCovering(r *rand.Rand, maxKey int) Spans {
> 	var ret Spans
> 	for i := randutil.RandIntInRange(r, 0, maxKey); i < maxKey-1; {
> ```

Not sure if this is a good method - first intervals and gaps are big, and they get smaller and smaller, and you can't control the number of intervals.

You could choose a number of intervals, generate 2N random numbers for their endpoints and sort them.
___
*[pkg/roachpb/merge_spans_test.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1kZFZDbNTKeJfFsEI:-Lc1kZFZDbNTKeJfFsEJ:b-42u9me) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L84)):*
> ```Go
> 		var s Span
> 		s.Key = encoding.EncodeVarintAscending(nil, int64(i))
> 		i += randutil.RandIntInRange(r, i, maxKey)
> ```

I think you meant `i =` here and below (!)

**Comment by RaduBerinde** [comment]
___
*[pkg/roachpb/merge_spans.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1nnsD9sSwbw2bnsBD:-Lc1nnsD9sSwbw2bnsBE:bn8uhqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L135)):*
> ```Go
> 		// Done span is after todo span so it doesn't affect it.
> 		if todo[t].EndKey.Compare(done[d].Key) <= 0 {
> 			if len(remaining) > 0 && todo[t].Key.Equal(remaining[len(remaining)-1].EndKey) {
> ```

This append-or-coalesce block is used a couple of times. Could be moved to a function `emit := func()` that we define before the loop.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1osTJ1laCVsrhjJHR:-Lc1osTJ1laCVsrhjJHS:b-iqxe5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L132)):*
> ```Go
> 			for i := 0; i < max; i++ {
> 				k := Key(encoding.EncodeVarintAscending(nil, int64(i)))
> 				if before.ContainsKey(k) {
> ```

[nit] these cases can all be collapsed into:
```
expected := before.ContainsKey(k) && !covered.ContainsKey(k)
if actual := after.ContainsKey(k); actual != expected { t.Errorf() }
```

**Review by dt — COMMENTED** [review]
Thanks for the detailed review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-:-Lc31IAA3UKiFJY1x_RS:bdasg5t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @lucy-zhang, @RaduBerinde, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1eJYH4OD6wT28NADN:-Lc2e7rcC8ScSJtI0AuJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L105)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

does "partial covering" means that `todo` and `done` must contain non-overlapping spans? If that's the case, mention it explicitly.
</blockquote></details>

Done.
___
*[pkg/roachpb/merge_spans.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1erNr7qkuH0Ans2tR:-Lc25pgp7OZQYz87xMSY:b-hjau2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L124)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There are many cases inside this code.. Would it make things simpler if we first made an "inverted" copy of `done`, and then intersected that with `todo`? (inverting is easy to do only if `done` has non-overlapping spans)
</blockquote></details>

I'm not sure if it'd be _that_ much simpler and we'd need to loop over two more times to invert and un-invert.
___
*[pkg/roachpb/merge_spans.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gEFNA-1d9uD72l-b:-Lc261ha8RyaKePkHeOO:b9ua65q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] it would be much easier to read if we did `tStart, tEnd := todo[t].Key, todo[t].EndKey` and same for `dStart, dEnd` and used those
</blockquote></details>

Done.

I'd avoided that when I was mutating spans in the slice more to shrink "done" spans as they were used, but without that, we only need to go back to the slice in a couple places so the loop-local vars clean it up nicely.
___
*[pkg/roachpb/merge_spans.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1nnsD9sSwbw2bnsBD:-Lc2Catq6_uTOxCpFIoO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L135)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This append-or-coalesce block is used a couple of times. Could be moved to a function `emit := func()` that we define before the loop.
</blockquote></details>

Done.
___
*[pkg/roachpb/merge_spans.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gnq6CBBvye97pt2h:-Lc2e9yU5Xbfm78PsZOo:b-b27ogn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It's more intuitive if `todo` is always on the left side of these comparisons (at least to me - I think of `todo` as the "left side" of the operation)
</blockquote></details>

Eh, I actually felt the opposite. I switched the one above so it's consistent. I can invert them all if you feel strongly though.
___
*[pkg/roachpb/merge_spans.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1h4Id2EuyT0iHGu1y:-Lc2I6qv4AHtOlsgaaya:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

endCmp
</blockquote></details>

Done.
___
*[pkg/roachpb/merge_spans.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1gfrH5LGEBfbG0bCK:-Lc2I8AFDO_az5Hs71ag:b-mwmnjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L154)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'd move this case inside the branch below and make that `if keyCmp <= 0` rather than modifying `keyCmp`
</blockquote></details>

Done. In fact, it goes away once we don't care about done covering anything not covered by todo.
___
*[pkg/roachpb/merge_spans.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1hBuY83hprZ1A4-uV:-Lc2IDam5HmWTOeCKiUp:b-lrq8yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L169)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What does modifying `done` get us? (here and in a few other places)  I'd think that we shouldn't care if the start key is earlier than we need, we could just tolerate that.
</blockquote></details>

Ditto above - before the random test, done covering anything not in todo was a panic. I had to relax that to make the random test easier to write, and that actually eliminated a lot of code that kept done spans up to date.
___
*[pkg/roachpb/merge_spans.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1hbX237Y9HypWqtJt:-Lc1oNSp0Di7ZEOJnwcX:bk7v8lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L172)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't understand this pattern. Do we really need a panic for this "case"? Why not just convert the last `else if` to `else`. These could also be a `switch`.
</blockquote></details>

Done. Condensed it quite a bit.
___
*[pkg/roachpb/merge_spans.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1jeLJCjojtW0SXitl:-Lc2IVLf69DGYi0kM_3H:b-kslkt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans.go#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could add a sentinel interval to `done` that is to the right of the last `todo` interval and have this part handled "for free".
</blockquote></details>

I don't think I follow, but  I also just decided I didn't care about this final coalesce so I just removed it.
___
*[pkg/roachpb/merge_spans_test.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1kFzBClOOv9RQMZzc:-Lc30OlA2mhL8a8JggeY:b-t7g6pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L81)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure if this is a good method - first intervals and gaps are big, and they get smaller and smaller, and you can't control the number of intervals.

You could choose a number of intervals, generate 2N random numbers for their endpoints and sort them.
</blockquote></details>

Eh, good point. OTOH, we run this 100 times ever time we run it, so we'll get some small spans some of the time. I'm fine with this and it's simple, so unless you feel really strongly, I'm just going to leave it.
___
*[pkg/roachpb/merge_spans_test.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1kZFZDbNTKeJfFsEI:-Lc30bSRDKY75Ff-_S3g:bnljs03) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L84)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think you meant `i =` here and below (!)
</blockquote></details>

Good catch!

Fortunately with enough iterations I actually was hitting all cases even with this mistaken jumping by leaps and bounds, but yes, I meant `i =`
___
*[pkg/roachpb/merge_spans_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1osTJ1laCVsrhjJHR:-Lc316WUDznd2cl194oZ:bc73v73) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L132)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] these cases can all be collapsed into:
```
expected := before.ContainsKey(k) && !covered.ContainsKey(k)
if actual := after.ContainsKey(k); actual != expected { t.Errorf() }
```
</blockquote></details>

Done.

I'd originally broken them out to make better error messages for each specific case, but on second though, I like the concise version better. Thanks!

**Review by RaduBerinde — COMMENTED** [review]
First commit LGTM, thanks for the updates!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-:-Lc3BHiq0OG9MPmchYei:b-hzjjc8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc39DI41D9mBjT2EH6u:-Lc39DI41D9mBjT2EH6v:bp9m8k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a6960d39c150964ce9d649b46ccd22a18de67d/pkg/roachpb/merge_spans.go#L154)):*
> ```Go
> 			continue
> 		}
> ```

[nit] add a comment
// At this point, we know that the two spans overlap.
___
*[pkg/roachpb/merge_spans.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc39NZ3D8oOJqgBDMC3:-Lc39NZ3D8oOJqgBDMC4:b1mn6j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a6960d39c150964ce9d649b46ccd22a18de67d/pkg/roachpb/merge_spans.go#L175)):*
> ```Go
> 			appendRemaining(Span{Key: tStart, EndKey: dStart})
> 
> 			if endCmp < 0 {
> ```

Isn't this block exactly the same with the one above?
___
*[pkg/roachpb/merge_spans_test.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc1kZFZDbNTKeJfFsEI:-Lc39WZl2dyh84iVheJm:b-2rh0gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6549e0a3286c3834f4f7cb2b16e5b29272b765bc/pkg/roachpb/merge_spans_test.go#L84)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Good catch!

Fortunately with enough iterations I actually was hitting all cases even with this mistaken jumping by leaps and bounds, but yes, I meant `i =`
</blockquote></details>

Heh, it's an interesting calculation for the expected number of intervals. Out of curiosity, I ran the original change and all generated sets had 1 or 2 spans, nothing bigger (which is kind of surprising).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, @lucy-zhang, @RaduBerinde, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc39DI41D9mBjT2EH6u:-Lc3FPmk6pOZtEe_Xsvy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a6960d39c150964ce9d649b46ccd22a18de67d/pkg/roachpb/merge_spans.go#L154)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment
// At this point, we know that the two spans overlap.
</blockquote></details>

Done.
___
*[pkg/roachpb/merge_spans.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc39NZ3D8oOJqgBDMC3:-Lc3BtPTC6aHnBqEE1qZ:bsia090) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a6960d39c150964ce9d649b46ccd22a18de67d/pkg/roachpb/merge_spans.go#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Isn't this block exactly the same with the one above?
</blockquote></details>

it is.

I debated moving it out but opted not to, to keep the branching simpler: first branch by key compare, then, on each side, handle end-compare cases.

**Comment by dt** [comment]
@vivekmenezes or @lucy-zhang the second commit in this is backfiller-specific if either of you want to look at that one.

**Review by vivekmenezes — APPROVED** [review]
Great change!

**Comment by dt** [comment]
TFTRs!

bors r+

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/roachpb/merge_spans.go, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc39NZ3D8oOJqgBDMC3:-Lc3xS9X3oLGHG92qNMX:b4oocu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1a6960d39c150964ce9d649b46ccd22a18de67d/pkg/roachpb/merge_spans.go#L175)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

it is.

I debated moving it out but opted not to, to keep the branching simpler: first branch by key compare, then, on each side, handle end-compare cases.
</blockquote></details>

There should be a very good reason to keep two copies of the same block. The code in this block has nothing to do with the key compare. We can break things up logically into 1) emit any uncovered prefix and 2) advance t and d as needed. The fact that we intermingle these is actually more confusing IMO

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, and @lucy-zhang)

___
*[pkg/roachpb/merge_spans.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36615#-Lc3zSj17GLjCaaOOHc7:-Lc3zSj17GLjCaaOOHc8:bml4u27) ([raw file](https://github.com/cockroachdb/cockroach/blob/397f93438e61f5ec322e0279616117d2f13bed5b/pkg/roachpb/merge_spans.go#L112)):*
> ```Go
> // minuend span [0, 10) and a subspan subtrahend [4,5) yields: [0, 4), [5, 10).
> //
> // Both inputs are mutated during execution and are not safe for reuse after.
> ```

 I don't think this is true anymore for `done`. BTW if it was, the calling function would be broken because it reuses `finished` inside a `Txn` loop.

**Pull request merged**
