### PR TITLE
update client/db_test.go

### PR DESCRIPTION
**Pull request by prideloki**
from: https://github.com/cockroachdb/cockroach/issues/6101 
convert all examples to regular tests

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6666)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[client/db_test.go, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtmG4BWY5_Ovy4mgwe:-KHtmG4BWY5_Ovy4mgwf:318145707) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L49)):*
> ```Go
> 	if !bytes.Equal(expected, result.ValueBytes()) {
> 		t.Errorf("expected aa=\"%s\", got aa=\"%s\"\n", expected, result.ValueBytes())
> 	}
> ```

The above piece of code is repeated quite often. How about creating a function

func checkResult(t *testing.T, expected []byte, result Result)

and use it like:

checkResult(t, "", result)

out here and elsewhere

And for the multiple values case  you could add a function

checkResults(t, map, result)

---

*[client/db_test.go, line 85 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtj7B-Pi_d6h4En10F:-KHtj7B-Pi_d6h4En10G:1244721875) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L85)):*
> ```Go
> 	}
> 	var expected []byte
> 	expected = []byte("2")
> ```

use := and not the declaration above

---

*[client/db_test.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtjC2fPrEfkdlaPBWU:-KHtjC2fPrEfkdlaPBWV:2008874092) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L97)):*
> ```Go
> 		panic(err)
> 	}
> 	expected = []byte("2")
> ```

it's the same expectation as above, so we don't need to reassign it.

---

*[client/db_test.go, line 161 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtkKug4k-i2adQ5o_Q:-KHtkKuhyfUDPn2fCx4u:1893087831) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L161)):*
> ```Go
> 		panic(err)
> 	}
> 	var expected int64 = 100
> ```

expected := 100

---

*[client/db_test.go, line 163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtkU959nNULkSJy26S:-KHtkU959nNULkSJy26T:2045329035) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L163)):*
> ```Go
> 	var expected int64 = 100
> 	if result.ValueInt() != expected {
> 		t.Errorf("expected aa=\"%d\", got aa=\"%d\"\n", result.ValueInt(), expected)
> ```

reverse expected and result

---

*[client/db_test.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtlY6J7x7Lg-QT-AVc:-KHtlY6J7x7Lg-QT-AVd:-1207056070) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L181)):*
> ```Go
> 		"bb": []byte("2"),
> 	}
> 	for _, result := range b.Results {
> ```

This test will pass if the returned result is empty. Wanna add a check that two values are evaluated.

---

*[client/db_test.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtlt13_nQdkznLwk79:-KHtlt13_nQdkznLwk7A:-149221371) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L212)):*
> ```Go
> 		"aa": []byte("1"),
> 		"ab": []byte("2"),
> 	}
> ```

same here

---

*[client/db_test.go, line 244 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtlvqFq75z7S1hRJ25:-KHtlvqFq75z7S1hRJ26:1179194526) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L244)):*
> ```Go
> 		"ab": []byte("2"),
> 	}
> 	for i, row := range rows {
> ```

and here

---

*[client/db_test.go, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtlyCGRDB_b1W6m_QC:-KHtlyCHMBUAQHFDGUj-:1179194526) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L278)):*
> ```Go
> 		"ac": []byte("3"),
> 	}
> 	for i, row := range rows {
> ```

and here

---

*[client/db_test.go, line 314 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtm-rvxhwQ054Dh_1f:-KHtm-rvxhwQ054Dh_1g:678021867) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L314)):*
> ```Go
> 		"ab": []byte("2"),
> 	}
> 	for i, result := range b.Results {
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by prideloki** [comment]
@vivekmenezes 
i created this `func checkResult(t *testing.T, expected, result client.KeyValue)`
and i have a problem when creating the roachpb.Value
```
expected := client.KeyValue{
		Key:   roachpb.Key("aa"),
		Value: &roachpb.Value{RawBytes: []byte("")},
}
```
i also tried `&roachpb.MakeValueFromBytes([]byte(""))`, assign a temp variable for the Value
i get `cannot take the address of ...` or go routine leak
please advise

**Comment by vivekmenezes** [comment]
message KeyValue {
  optional bytes key = 1 [(gogoproto.casttype) = "Key"];
  optional Value value = 2 [(gogoproto.nullable) = false];
}

KeyValue has Value nonnullable which means that you have to assign the value directly and not use a pointer

try:
Value: roachpb.Value{RawBytes: []byte("")},

<details><summary><i>Previously, prideloki (Thanakom sangnetra) wrote…</i></summary>
> @vivekmenezes 
> 
> i created this `func checkResult(t *testing.T, expected, result client.KeyValue)`
> 
> and i have a problem when creating the roachpb.Value
> 
> ```
> 
> expected := client.KeyValue{
> 
> 		Key:   roachpb.Key("aa"),
> 
> 		Value: &roachpb.Value{RawBytes: []byte("")},
> 
> }
> 
> ```
> 
> i also tried `&roachpb.MakeValueFromBytes([]byte(""))`, assign a temp variable for the Value
> 
> i get `cannot take the address of ...` or go routine leak
> 
> please advise</details>


---

Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-:-KHzfDjwxsxFnX03XNtu:521551318)*

**Comment by prideloki** [comment]
the Value in KeyValue in `client` package is different, it use the pointer of roachpb.Value
```
package client
// KeyValue represents a single key/value pair and corresponding
// timestamp. This is similar to roachpb.KeyValue except that the value may be
// nil.
type KeyValue struct {
	Key   roachpb.Key
	Value *roachpb.Value // Timestamp will always be zero
}
```

**Comment by vivekmenezes** [comment]
Can you push your change. I can take a look. Thanks

**Comment by prideloki** [comment]
@vivekmenezes  sure, this one here https://github.com/cockroachdb/cockroach/pull/6666/commits/dbf739b6bef87459de8b0a0e4929d8ceacadd30a
i haven't use `checkResult` to all the tests yet just only one first.

**Comment by vivekmenezes** [comment]
I think you are taking too complex an approach. I'd just pass in two []byte
vars and compare them and log an error. All I want you to do is
extract that code out.

Thanks

Vivek

**Comment by prideloki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[client/db_test.go, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KHtmG4BWY5_Ovy4mgwe:-KIktLjzW7FEgkiR5xpV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a8babb85fa2cb224af9ca0a06f7b87fc9ed5fc/client/db_test.go#L49)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> The above piece of code is repeated quite often. How about creating a function
> 
> func checkResult(t *testing.T, expected []byte, result Result)
> 
> and use it like:
> 
> checkResult(t, "", result)
> 
> out here and elsewhere
> 
> And for the multiple values case  you could add a function
> 
> checkResults(t, map, result)
> 
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[client/db_test.go, line 39 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KIm0FQrStdlpDZnD-v7:-KIm0FQsxPVsCLAHaLDo:1356352041) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bb359da5e63e53726d93dfa47d64b70d473e77/client/db_test.go#L39)):*
> ```Go
> func checkIntResult(t *testing.T, expected, result int64) {
> 	if expected != result {
> 		t.Errorf("expected %d, got %d\n", expected, result)
> ```

throughout: no need to put newlines at the end of these calls to Errorf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by prideloki** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[client/db_test.go, line 39 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KIm0FQrStdlpDZnD-v7:-KImRATPJGTj4bXxzEaA:62092805) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bb359da5e63e53726d93dfa47d64b70d473e77/client/db_test.go#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> throughout: no need to put newlines at the end of these calls to Errorf
</details>
Hi, i don't get it where are those new lines at the end of Errorf. 
i only see the  `}` at the new line after Errorf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[client/db_test.go, line 39 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KIm0FQrStdlpDZnD-v7:-KImTesNnYimD2iZztiu:761259628) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bb359da5e63e53726d93dfa47d64b70d473e77/client/db_test.go#L39)):*
<details><summary><i>Previously, prideloki (Thanakom sangnetra) wrote…</i></summary>
> Hi, i don't get it where are those new lines at the end of Errorf. 
> i only see the  `}` at the new line after Errorf
</details>
"\n" is a newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by prideloki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[client/db_test.go, line 39 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KIm0FQrStdlpDZnD-v7:-KImW-d9GU01IZZyy8Or:1025756513) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bb359da5e63e53726d93dfa47d64b70d473e77/client/db_test.go#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "\n" is a newline
</details>
oh, right. thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by prideloki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[client/db_test.go, line 39 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666#-KIm0FQrStdlpDZnD-v7:-KIqQd_EQ7qTC_yovhsW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/25bb359da5e63e53726d93dfa47d64b70d473e77/client/db_test.go#L39)):*
<details><summary><i>Previously, prideloki (Thanakom sangnetra) wrote…</i></summary>
> oh, right. thank you.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6666)*

**Comment by tamird** [comment]
LGTM

**Pull request merged**
