### PR TITLE
roachtest: add npgsql nightly test

### LINKED ISSUE #92623: sql: update support for npgsql
Npgsql is on major version 6.0, we are only on 4.x. We should update our support and get Npgsql out of beta.
https://www.cockroachlabs.com/docs/stable/third-party-database-tools.html

Jira issue: CRDB-21889

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/92623

Release note: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97253)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOQnj6K-gcnV0vMfBtg:-NOQnj6K-gcnV0vMfBth:b-xe4anr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L78)):*
> ```Go
> 			"install dependencies",
> 			`sudo snap install dotnet-sdk --classic && \
> sudo snap alias dotnet-sdk.dotnet dotnet && \
> ```

Do you mind explaining the purpose of this line?
___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR76pa2JMm-KD5CikN:-NOR76pa2JMm-KD5CikO:b-l9pac1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L112)):*
> ```Go
> 			"modify connection settings",
> 			fmt.Sprintf(`cd /mnt/data1/npgsql && \
> sed -e 's/netcoreapp3.1//g' -i test/Directory.Build.props && \
> ```

Do you mind adding a comment explaining why this is necessary?
___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR85096aF4TzGEn6NS:-NOR85096aF4TzGEn6NT:b-kw6bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L157)):*
> ```Go
> }
> 
> const npgsqlPatch = `diff --git a/test/Npgsql.Tests/TestUtil.cs b/test/Npgsql.Tests/TestUtil.cs
> ```

Could you add a comment above this summarizing the patch?
___
*[`pkg/cmd/roachtest/tests/orm_helpers.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR9MRPDEPcNlwDAd4e:-NOR9MRPDEPcNlwDAd4f:bc4mpa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/orm_helpers.go#L179)):*
> ```Go
> 		fmt.Fprintf(&b, "var %s = blocklist{\n", blocklistName)
> 
> 		lastName := ""
> ```

nit: maybe rename to `prevName` to make it more clear? "last" suggests to me that it's the final name in the list
___
*[`pkg/cmd/roachtest/tests/orm_helpers.go` line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NORBIK51bEsR6_VO-PF:-NOR92nuBfCezMmWUCe0:bk1sg06) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/orm_helpers.go#L181)):*
> ```Go
> 		lastName := ""
> 		for _, testName := range r.currentFailures {
> 			// Avoid putting duplicates in the map.
> ```

nit: also it wasn't immediately clear to me that the list of strings is already sorted so this is enough to eliminate duplicates. maybe edit the comment to say that?

also, why are there duplicate tests with the same name in the first place?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97253)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOQnj6K-gcnV0vMfBtg:-NORBv3d-1R5QKmkbx1d:b-ks92lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L78)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do you mind explaining the purpose of this line?
</blockquote></details>

this is how the `dotnet` SDK is installed, following these docs: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

added a comment
___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR76pa2JMm-KD5CikN:-NORC4oMEWviANPLa3Kx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L112)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do you mind adding a comment explaining why this is necessary?
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/npgsql.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR85096aF4TzGEn6NS:-NORC6BnAvVvjBwHO27B:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/npgsql.go#L157)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could you add a comment above this summarizing the patch?
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/orm_helpers.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NOR9MRPDEPcNlwDAd4e:-NORC7spEZ4o2YA6pwgE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/orm_helpers.go#L179)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe rename to `prevName` to make it more clear? "last" suggests to me that it's the final name in the list
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/orm_helpers.go` line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-NORBIK51bEsR6_VO-PF:-NORC9Rb3e2FjQMOXj_K:bnn61hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aa0051e19396c37ac1eb0e494098b2f036c1b66/pkg/cmd/roachtest/tests/orm_helpers.go#L181)):*
> also, why are there duplicate tests with the same name in the first place?

from what i could tell, it seemed like the npgsql framework runs some tests twice. i couldn't find anything in the test logs that distinguished one run from the other

added a comment

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97253#-:-NORJhw--UcW14MULjs6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by rafiss** [comment]
thanks for the review!

bors r=andyyang890

**Pull request merged**
