### PR TITLE
colexec: further optimize hash aggregator

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: low-risk update to new functionality (it is
low-risk because it does not change anything fundamentally, rather only
improves the way we handle allocations and clear an internal state).

This commit optimizes the hash aggregator relationship with selection
vectors. Previously, we were maintaining a map from hash code (`uint64`)
to a slice of ints, and this would result in creating a new int slice
for every hash code that the hash aggregator ever encounters during its
run. However, we're processing atmost (about) `batchTupleLimit` tuples
at once, so at most we can have the same number of different hash codes.
This observation allows us to have constant number of int slices. To
accommodate this, we introducing a map from hash code to the "slot" in
`[][]int`, and the map is maintained to contain hash codes that we need
to process. Once the hash code has been processed, the entry is deleted.
This way both the map and the number of int slices stays constant
throughout the run of the hash aggregator.

Also this commit refactors `makeAggregateFuncs` to separate out the
creation of output types (this has some impact on performance of hash
aggregator which makes aggregate functions for every group).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Initially, I thought that this change might be too invasive, but now I think it's not that bad and can be allowed to go in during the stabilization period.

**Comment by yuzefovich** [comment]
The full benchmarks are [here](https://gist.github.com/yuzefovich/354ba34c646d5140070c35f540a2ec53), and a snippet is below:
```
Aggregator/MIN/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-24                3.12MB/s ± 3%   3.97MB/s ± 1%   +27.21%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-24                 2.96MB/s ± 4%   3.75MB/s ± 1%   +26.52%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-24                6.38MB/s ± 2%   8.07MB/s ± 1%   +26.47%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-24                 6.10MB/s ± 2%   7.64MB/s ± 1%   +25.36%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-24              88.3MB/s ± 0%  205.2MB/s ± 0%  +132.27%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-24               81.6MB/s ± 0%  172.1MB/s ± 0%  +110.96%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-24             91.9MB/s ± 0%  229.3MB/s ± 0%  +149.54%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-24              83.7MB/s ± 1%  189.4MB/s ± 1%  +126.46%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-24              2.80MB/s ± 1%   3.54MB/s ± 4%   +26.34%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-24               2.62MB/s ± 3%   3.26MB/s ± 2%   +24.52%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-24              5.55MB/s ± 3%   6.92MB/s ± 1%   +24.73%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-24               5.28MB/s ± 4%   6.68MB/s ± 2%   +26.56%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-24            58.3MB/s ± 1%   94.0MB/s ± 1%   +61.18%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-24             57.2MB/s ± 0%   90.6MB/s ± 1%   +58.54%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-24           60.0MB/s ± 0%  100.1MB/s ± 0%   +66.96%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-24            58.9MB/s ± 0%   96.4MB/s ± 1%   +63.76%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=1/hasNulls=false/numInputBatches=64-24                2.98MB/s ± 2%   3.79MB/s ± 1%   +27.16%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=1/hasNulls=true/numInputBatches=64-24                 2.85MB/s ± 2%   3.62MB/s ± 2%   +26.84%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=2/hasNulls=false/numInputBatches=64-24                6.19MB/s ± 1%   7.73MB/s ± 3%   +24.86%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=2/hasNulls=true/numInputBatches=64-24                 5.88MB/s ± 3%   7.36MB/s ± 2%   +25.13%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=512/hasNulls=false/numInputBatches=64-24              79.7MB/s ± 0%  159.1MB/s ± 1%   +99.68%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=512/hasNulls=true/numInputBatches=64-24               73.5MB/s ± 0%  137.6MB/s ± 1%   +87.26%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=1024/hasNulls=false/numInputBatches=64-24             82.3MB/s ± 1%  174.1MB/s ± 2%  +111.47%  (p=0.008 n=5+5)
Aggregator/MIN/hash/Bytes/groupSize=1024/hasNulls=true/numInputBatches=64-24              76.5MB/s ± 1%  149.1MB/s ± 1%   +94.93%  (p=0.008 n=5+5)
```

**Review by asubiotto — CHANGES_REQUESTED** [review]
I agree that the change looks scary at first but is simply a change to resetting logic. However, I think that that is why it's important that the Release justification be fleshed out a bit more with a better explanation (i.e. *why* is this change considered low-risk?), especially for engineers not on this team. Otherwise it defeats the purpose of having one.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-:-M3LIY-8DJ46OV5OYmoD:bvi2gpo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/colexec/aggregator.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LIgVU7xo5WN688yjS:-M3LIgVU7xo5WN688yjT:b-r31hyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/aggregator.go#L216)):*
> ```Go
> 	a.aggregateFuncs, err = makeAggregateFuncs(a.allocator, aggTypes, aggFns)
> 	if err == nil {
> 		a.outputTypes, err = makeAggregateFuncsOutputTypes(aggTypes, aggFns)
> ```

This conditional doesn't make sense to me. I prefer to be more verbose:
```
func, err := make funcs()
if err
   return err
output types, err := make output types()
if err
   return err
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LO0gA51DQYRCclNjB:-M3LO0gA51DQYRCclNjC:b-x9x3xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/hash_aggregator.go#L91)):*
> ```Go
> 		coldata.Batch
> 		// vecs stores "unwrapped" batch.
> 		vecs []coldata.Vec
> ```

Do we get that big a performance boost if we store these unwrapped vectors versus getting them each time in `onlineAgg`?
___
*[pkg/sql/colexec/hash_aggregator.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LNCd3ElS364qZwILV:-M3LNCd4Eu0DenuAz7qb:b-6h876t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/hash_aggregator.go#L106)):*
> ```Go
> 		// batchTupleLimit (plus - possibly - constant excess) different
> 		// hashCodes at once.
> 		sels [][]int
> ```

What's the difference between having `hashCodeToSelsSlot` that does the translation versus keeping the same map but limiting the size to at most `batchTuplelimit` per run? Wouldn't you delete the entries in either case once done with the hashCode?

**Review by yuzefovich — COMMENTED** [review]
Updated release justification.

I guess I'm unclear on the guidance for the release justification - I am under the impression that any PR should "go" through two steps:
1. the author needs to think whether the PR falls into one of the release justification buckets, and if not, the PR is definitely no-go
2. the author and the reviewer(s) need to come to an agreement that it is ok for the PR to go in during stability period, whether the benefits outweigh the risks.

I don't think of "release justification" as the reasoning where any engineers might look at since they will likely be missing the context/importance/significance of the change. So unless we decide that it is worth/necessary typing out verbose justifications that would provide that context, I don't see a benefit in having somewhat verbose release justification other than choosing the category. Maybe I'm wrong though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-:-M3N9MysDcJvWZIxzJOT:b-3b9e6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/aggregator.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LIgVU7xo5WN688yjS:-M3N6OlM82wuRYXzQGf2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/aggregator.go#L216)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This conditional doesn't make sense to me. I prefer to be more verbose:
```
func, err := make funcs()
if err
   return err
output types, err := make output types()
if err
   return err
```
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LO0gA51DQYRCclNjB:-M3N6QqvCigVs9HMyAPy:bre3k1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/hash_aggregator.go#L91)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we get that big a performance boost if we store these unwrapped vectors versus getting them each time in `onlineAgg`?
</blockquote></details>

In the grand scheme of things, this is not an important optimization, but I think it's nice to have since we're instantiating this batch only once and never expose it outside of the hash aggregator. (It addresses #45272.)
___
*[pkg/sql/colexec/hash_aggregator.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-M3LNCd3ElS364qZwILV:-M3N7N5V4j4IxaviupuL:b-nhw8gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c883684648252560dd22a370fd846c495ca81743/pkg/sql/colexec/hash_aggregator.go#L106)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What's the difference between having `hashCodeToSelsSlot` that does the translation versus keeping the same map but limiting the size to at most `batchTuplelimit` per run? Wouldn't you delete the entries in either case once done with the hashCode?
</blockquote></details>

The difference would be that we would need to allocate `[]int` for the selection vector for each hash code. And if we're deleting entries from `map[hashCode]selVector`, then we would never reuse the already allocated int slices. So here is gist of options:
1. (what we have currently on master) we have `map[uint64][]int`, it can contain arbitrarily many keys (because we're never deleting entries), but we do reuse the already allocated int slice for a particular hash code if it is ever repeated
2. (what you're asking about) we have `map[uint64][]int`, we will be deleting entries from the map (so it will never grow above `batchTupleLimit` in size), but we will need to allocate `[]int` every time
3. (what I'm proposing) introduce a translation "layer" to get the best of two options.

We could improve option 2 so that instead of simply allocating `[]int`, we would have `intSliceAlloc` object that would give out them, and the object would be reset after `onlineAgg` has completed. It would be essentially the same as option 3 with slightly different semantics.

**Review by asubiotto — APPROVED** [review]
I don't think there's any guidance, I just know that I find it useful. Without guidance this seems like my personal preference, so I guess you should do what you think is right.

:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46595#-:-M3RY_6R3mm-C3gZ_Kze:b-sg6rv3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by yuzefovich** [comment]
Ok, I'll try to be a little more verbose in release justification other than simply choosing the category.

TFTR!

bors r+

**Pull request merged**
