### PR TITLE
tenantcapabilitiesauthorizer: introduce kill-switch cluster setting 

### LINKED ISSUE #98138: tenantcapabilities: cluster setting gate tenant capability infrastructure
**Describe the problem**

Tenant capabilities are stored in the `TenantInfo` column in `system.tenants`, which was added this release. We establish a rangefeed over `system.tenants` and expect the column to be there -- as such, we should version gate the infrastructure until the migration to add the column has started. Without it, we would end up fataling the node, as capabilities won't be present and we won't be able to decode them. 

Jira issue: CRDB-25100
Epic: CRDB-23559

### PR DESCRIPTION
**Pull request by arulajmani**
Fixes #98138.

This patch introduces a new (non-public) cluster setting called
`tenant_capabilities.authorizer.enabled` which acts as a kill switch
for the Authorizer. It is inteded to be a safety switch to turn off
capability checks performed by the Authorizer, in case we need to turn
off the subsystem. As such, it isn't inteded to be used during normal
cluster operation.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks I like it but please make CI happy before we can merge.

> Reviewed 3 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-:-NQCBf6X3XnYk0ORSovE:beb075t)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ecwall — APPROVED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @knz)

___
*[`pkg/multitenant/tenantcapabilities/capabilities.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-NQCBzKnEbSl-iaKQywA:-NQCBzKnEbSl-iaKQywB:bb9epu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba4dd2bf175dbdc59619df6cc331b83c2b19e7b/pkg/multitenant/tenantcapabilities/capabilities.go#L39)):*
> ```Go
> 	GetCapabilities(id roachpb.TenantID) (_ tenantcapabilitiespb.TenantCapabilities, found bool)
> 	// GetGlobalCapabilityState returns the capability state for all tenants.
> 	GetGlobalCapabilityState() map[roachpb.TenantID]tenantcapabilitiespb.TenantCapabilities
> ```

Calling it State instead of Map is fine with me if you think it is more descriptive
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-NQCCZcbCBZDA8YPs2PF:-NQCCZcc2-VTFwrFhgow:b-9jcbnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba4dd2bf175dbdc59619df6cc331b83c2b19e7b/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L141)):*
> ```Go
> // elideCapabilityChecks returns true if capability checks should be skipped for
> // the supplied tenant.
> func (a *Authorizer) elideCapabilityChecks(ctx context.Context, tenID roachpb.TenantID) bool {
> ```

I would call this `skipCapabilityChecks` to use a simpler word (that's also how the comment describes the method), but it is fine with me either way since it looks like we use "elide" elsewhere in the codebase.

**Review by ecwall — COMMENTED** [review]
Add test case(s) to authorizer_test.go and I think it looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-:-NQCE6KM-4IQ_YdxG1I7:bvw3z8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @knz)

**Comment by knz** [comment]
@arulajmani reminder that merging this PR is needed before the 23.1 branch is cut, which is scheduled for the end of this week.

**Review by arulajmani — COMMENTED** [review]
CI was a unrelated flake. I've rebased this PR and added some tests for the `Authorizer`, as suggested. TFTRs! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-:-NQQtkBZ7aFxRoqHaQvL:b-e4iapq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/multitenant/tenantcapabilities/capabilities.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-NQCBzKnEbSl-iaKQywA:-NQQu2hF6qQapL4dmNIt:byfl37e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba4dd2bf175dbdc59619df6cc331b83c2b19e7b/pkg/multitenant/tenantcapabilities/capabilities.go#L39)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Calling it State instead of Map is fine with me if you think it is more descriptive
</blockquote></details>

A map could be anything -- what we're really returning here is a map with an entry for every tenant that has capabilities associated with it (which is every tenant). Calling it the global capability state is more appropriate. 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98274#-NQCCZcbCBZDA8YPs2PF:-NQQu0H_0yy2nAHglFP8:be7krkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba4dd2bf175dbdc59619df6cc331b83c2b19e7b/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L141)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I would call this `skipCapabilityChecks` to use a simpler word (that's also how the comment describes the method), but it is fine with me either way since it looks like we use "elide" elsewhere in the codebase. 
</blockquote></details>

Ack. I'll leave it as elide then.

**Pull request merged**
