### PR TITLE
lint: fix error msg

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-:-MoK5LeC7IFo3iH0Oa5l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/testutils/lint/lint_test.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-MoK5I8x69PKa63HyUMe:-MoK5I8x69PKa63HyUMf:b6bixqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52043b1ed30a964a58401f1134c03c001854d60/pkg/testutils/lint/lint_test.go#L778)):*
> ```Go
> 		if err := stream.ForEach(filter, func(s string) {
> 			t.Errorf("\n%s <- forbidden; use 'timeutil.Since(t)' instead "+
> 				"because they're more efficient", s)
> ```

nit: `s/they're/it's/`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72691)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/testutils/lint/lint_test.go, line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-MoK5P0mBp1k7DBbhrN3:-MoK5P0mBp1k7DBbhrN4:bpykgzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52043b1ed30a964a58401f1134c03c001854d60/pkg/testutils/lint/lint_test.go#L755)):*
> ```Go
> 	})
> 
> 	// Forbid timeutil.Now().Sub(t) in favor or timeutil.Since(t).
> ```

nit: `s/or/of/`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72691)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/testutils/lint/lint_test.go, line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-MoK5P0mBp1k7DBbhrN3:-MoK62fF6vf8msnfXu7A:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52043b1ed30a964a58401f1134c03c001854d60/pkg/testutils/lint/lint_test.go#L755)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/or/of/`.
</blockquote></details>

done
___
*[pkg/testutils/lint/lint_test.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-MoK5I8x69PKa63HyUMe:-MoK63FZ4NnhSMHTL6RZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52043b1ed30a964a58401f1134c03c001854d60/pkg/testutils/lint/lint_test.go#L778)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/they're/it's/`.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72691#-:-MoKqupo5hRNQrqAHIEo:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Pull request merged**
