### PR TITLE
allocator2: test and fixes for init of rangeAnalyzedConstraints

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs https://github.com/cockroachdb/cockroach/issues/103320

Epic: [CRDB-25222](https://cockroachlabs.atlassian.net/browse/CRDB-25222)

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
first commit from https://github.com/cockroachdb/cockroach/pull/103533 and second commit from https://github.com/cockroachdb/cockroach/pull/103561

**Review by sumeerbhola — COMMENTED** [review]
rebased on master

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103622#-:-NVpQXSq9DJeC8dKEu_j:b-9r6maq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by kvoli — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103622#-:-NW3FfxtANfxYX0d9cci:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
