### PR TITLE
rowexec: fix zigzag joiner with ON expression in some cases

### LINKED ISSUE #71093: SQLSTATE[XX000]: Internal error: 7 ERROR:  internal error: decoding unset EncDatum
**Describe the problem**
I got this error when running query below:

```
SQLSTATE[XX000]: Internal error: 7 ERROR:  internal error: decoding unset EncDatum
DETAIL:  stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:228: EnsureDecoded()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:132: IndexedVarEval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/indexed_vars.go:81: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3944: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3677: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3666: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3666: Eval()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr_filter.go:21: RunFilter()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/expr.go:192: EvalFilter()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinerbase.go:180: render()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/zigzagjoiner.go:738: emitFromContainers()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/zigzagjoiner.go:770: nextRow()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/zigzagjoiner.go:969: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:199: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:86: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/count.go:59: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:86: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:290: next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:315: nextAdapter()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:321: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:171: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:781: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:384: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:367: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1011: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1055: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:917: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:661: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:123: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:210: execPortal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1596: func2()

HINT:  You have encountered an unexpected error.
```

**To Reproduce**
Running this query would give error above
```sql
SELECT count(*) AS AGGREGATE
FROM "tasks"
WHERE "status" = 'queue'
  AND "endpoint_id" = 'ddf4c620-857b-11ea-a414-bbce35ef852a'
  AND "type" = 'upload'
  AND "endpoint_path" = '/mnt/mega/s2/'
```

**Environment:**
 - CockroachDB version: ```CockroachDB CCL v21.1.2 (x86_64-unknown-linux-gnu, built 2021/06/07 18:09:50, go1.15.11)```

Is it info above sufficient ? If not please let me know, I could send data via email.

### PR DESCRIPTION
**Pull request by yuzefovich**
Zigzag joiner needs to tell the row fetcher which columns are needed.
Previously, we forgot to include the columns that are needed by the ON
expression but are not needed in the output, so when evaluating such an
ON expression, we would hit an internal error. This commit fixes the
problem by including all columns referenced by the ON expression into
the set of columns to be fetched.

Fixes: #71093

Release note (bug fix): Previously, CockroachDB could encounter an
internal error when executing a zigzag join in some cases (when there
are multiple filters present and at least one filter refers to the
column that is part of STORING clause of the secondary index that is
used by the zigzag join), and this has been fixed.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice find!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-:-MlLly6m27wwb2U7f-QP:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLktCx2Y9Jb0IJnZiR:-MlLktCy2xwIpC9ONnbl:b-ezw510) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L261)):*
> ```
> 
> query I
> SELECT count(*) FROM t71093 WHERE a = 0 AND b = 1 AND c = 2
> ```

nit: add a similar test to execbuilder to show that we use a zigzag join. Or maybe force a zigzag join here with a hint
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLle1TBB7KUQVu27a9:-MlLle1TBB7KUQVu27aA:buny0sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L263)):*
> ```
> SELECT count(*) FROM t71093 WHERE a = 0 AND b = 1 AND c = 2
> ----
> 1
> ```

how about adding another test where the variable in the ON condition comes from the other side of the zigzag join? And maybe one where the condition has columns from both?
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLl9np71heLde5f9SK:-MlLl9np71heLde5f9SL:b-8sf2v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/rowexec/zigzagjoiner.go#L472)):*
> ```Go
> 	for _, v := range z.onCond.Vars.GetIndexedVars() {
> 		// We only include the columns that come from this side (all such
> 		// columns have the ordinals in [colOffset; maxCol) range).
> ```

nit: did you mean to use a semicolon? Maybe you meant [colOffset, maxCol)?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71226)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLktCx2Y9Jb0IJnZiR:-MlLwFqr9ZcEoZWi9l_6:b-b4h15k) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L261)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add a similar test to execbuilder to show that we use a zigzag join. Or maybe force a zigzag join here with a hint
</blockquote></details>

Added the corresponding opt tests - I think it is a better option since - I believe - the zigzag join hint is unavailable in the old releases.
___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLle1TBB7KUQVu27a9:-MlLwFdH9IQ85EkIhyD9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/logictest/testdata/logic_test/zigzag_join#L263)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

how about adding another test where the variable in the ON condition comes from the other side of the zigzag join? And maybe one where the condition has columns from both?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlLl9np71heLde5f9SK:-MlLw50s2woOBk-6fer3:b-1gqexr) ([raw file](https://github.com/cockroachdb/cockroach/blob/854e1f686f15e684416d65ed6eda418809dda4f8/pkg/sql/rowexec/zigzagjoiner.go#L472)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: did you mean to use a semicolon? Maybe you meant [colOffset, maxCol)?
</blockquote></details>

Yeah, I meant to the use the comma.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-:-MlM2j4Q07Lw8QwbQ3vC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by cucaroach — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-:-MlM81LS7zo1KaXqvYwG:bmxilld)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlM7Y-P3ar9nJVM1g2r:-MlM7Y-P3ar9nJVM1g2s:b-ybe1e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f3fcc57bed60708e81c0c1d594a415c5f05c40/pkg/sql/logictest/testdata/logic_test/zigzag_join#L260)):*
> ```
> INSERT INTO t71093 VALUES (0, 1, 2, 3)
> 
> # ON expr needs the stored column from the left side.
> ```

I'm confused by use of the term ON expression, do we use ON expression and WHERE clause interchangably?   Or is it just that for a zz join the where clause gets put into a variable called "onCond"?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71226)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/logictest/testdata/logic_test/zigzag_join, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71226#-MlM7Y-P3ar9nJVM1g2r:-MlM9i9qB0c3N15nk83h:ba97j76) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f3fcc57bed60708e81c0c1d594a415c5f05c40/pkg/sql/logictest/testdata/logic_test/zigzag_join#L260)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I'm confused by use of the term ON expression, do we use ON expression and WHERE clause interchangably?   Or is it just that for a zz join the where clause gets put into a variable called "onCond"?
</blockquote></details>

Yeah, we use these things somewhat interchangeably.

The way things work is that the query specifies `WHERE` clause which contains multiple predicates, then the optimizer picks out those that are equality checks which are pushed as "equality columns" for the join; if there are any other predicates left, those are put into the `onCond` (or "ON expr"). Then, when performing a join, we use the equality columns to find matches, and if `onCond` is not empty, for each match we check whether it passes the `onCond` filter (and emit the row only if it does). This "ON expr" / "ON expression" / "onCond" business is applicable to all types of joins (hash, merge, lookup, zigzag, inverted), only the index joins don't have it.

**Pull request merged**
