### PR TITLE
allocator2: unit test for meansMemo

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs #103320

Epic: CRDB-25222

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103916#-:-NWOFR330rFXXWZtQOIt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/means_memo` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103916#-NWOEnC36943lfv3Lq94:-NWOEnC36943lfv3Lq95:b-u7tzr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee274cd69c13c2860c9f10b324c2d2bcb688890/pkg/kv/kvserver/allocator/allocator2/testdata/means_memo#L30)):*
> ```
> node-mean cpu (load,cap,util): (225, 750, 0.30)
> 
> # Store summary calls out out computeLoadSummary when the load-seq-num increases.
> ```

nit: double "out"

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103916#-:-NWgly1KDtMkxb3an0AQ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/means_memo` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103916#-NWOEnC36943lfv3Lq94:-NWglwy456quGokRBYwz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee274cd69c13c2860c9f10b324c2d2bcb688890/pkg/kv/kvserver/allocator/allocator2/testdata/means_memo#L30)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: double "out"
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
flake in `TestAddNewStoresToExistingNodes`

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
