### PR TITLE
server: use a shared HTTP listener for all in-memory tenant servers

### LINKED ISSUE #91738: server: explore tenant routing in HTTP interface [CRDB-14537 followup]
We want a single HTTP listener for all in-memory tenant servers, with routing based on a header (maybe cookie).

Epic: CRDB-14537

Jira issue: CRDB-21410

### PR DESCRIPTION
**Pull request by knz**
Parent PRs:
- [x] https://github.com/cockroachdb/cockroach/pull/84608
- [x] https://github.com/cockroachdb/cockroach/pull/91739

Fixes #91738.

This commit introduces a HTTP (de)multiplexer for all in-memory tenant
servers.

By default, HTTP requests are routed to the system tenant server.
This can be overridden with the header `X-Cockroach-Tenant` or the `tenant` cookie.

Epic: CRDB-14487

### CODE REVIEW

**Comment by knz** [comment]
@dhartunian do you want to have a preliminary look to check if the overall direction is satisfactory?

I'm still on the fence about whether to select the tenant via a custom header of a cookie. Maybe we should do both? Let me know what you think.

**Review by dhartunian — COMMENTED** [review]
> I'm still on the fence about whether to select the tenant via a custom header or a cookie. Maybe we should do both? Let me know what you think.

I like supporting multiple methods. Cookie is best for the frontend since it allows all requests to flow reliably to the right place. For instance, requests to JS/CSS/images etc. can't have the header attached because the browser makes them. The only way to ensure they come from the correct tenant is to use a cookie. I know we're not serving different assets at the moment, but it's nice to not worry about it.

> Reviewed 11 of 11 files at r1, 12 of 12 files at r2, 5 of 5 files at r3, 4 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-:-NGscRU7BIbZJ5tI42U5:bnzfb40)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @srosenberg)

___
*[`pkg/server/server_controller.go` line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NGsfcJe-TuDcUGGrOf6:-NGsfcJf9ZSa_hzJiPaM:b-lu97bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1527b4ca8d536a8c5ab579056e6d496b7da48f5/pkg/server/server_controller.go#L174)):*
> ```Go
> // the special HTTP request header.
> // If no tenant is specified, the default tenant is used.
> func (c *serverController) httpMux(w http.ResponseWriter, r *http.Request) {
> ```

love how simple this ends up being!
___
*[`pkg/server/server_controller.go` line 277 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NGsfR_l8MtgE02abynR:-NGsfR_l8MtgE02abynS:be3oq6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1527b4ca8d536a8c5ab579056e6d496b7da48f5/pkg/server/server_controller.go#L277)):*
> ```Go
> 
> func (t *systemServerWrapper) getHTTPHandlerFn() http.HandlerFunc {
> 	return t.s.http.baseHandler
> ```

nit: can we standardize between the `t.s` and `t.server` names here?

**Review by knz — COMMENTED** [review]
> I like supporting multiple methods.

:+1: Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-:-NGw3czd2dr2Y2ef9Em0:b1s2d68)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, and @srosenberg)

___
*[`pkg/server/server_controller.go` line 277 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NGsfR_l8MtgE02abynR:-NGw3h-lAYwlUuqE60Mc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1527b4ca8d536a8c5ab579056e6d496b7da48f5/pkg/server/server_controller.go#L277)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can we standardize between the `t.s` and `t.server` names here?
</blockquote></details>

Done.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 18 files at r5, 18 of 18 files at r9, 12 of 12 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @srosenberg)

___
*[`pkg/server/server_controller.go` line 326 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHUVOvb5qur6L2blB3L:-NHUVOvb5qur6L2blB3M:b-kzy6qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb68fc15af30f476ed82ea43422cb59d3cd81e0c/pkg/server/server_controller.go#L326)):*
> ```Go
> 	// Start a goroutine that watches for shutdown requests issued by
> 	// the server itself.
> 	go func() {
> ```

are we trying to avoid `go` keyword in non-test code?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, and @srosenberg)

___
*[`pkg/server/server_controller.go` line 326 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHUVOvb5qur6L2blB3L:-NHUWMii8nNRbUI0b-_q:b-8shopp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb68fc15af30f476ed82ea43422cb59d3cd81e0c/pkg/server/server_controller.go#L326)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

are we trying to avoid `go` keyword in non-test code?
</blockquote></details>

It's a good question. Alas we can't use stopper.RunAsyncTask here because the call to stopper.Stop inside would then deadlock. Clarified in comment.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

I don't have opinions on cookie vs header that you're discussing. However, what I know how to edit is the URL in the address bar. Could we also take the tenant there, like we do with the node id for proxying HTTP requests between nodes?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-:-NHW00MsCcaxcjirypql:bfkl5nz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @knz, and @srosenberg)

___
*[`pkg/server/config.go` line 214 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVYT_zEYDDr5aYSf7K:-NHVYTa-3XPCf7dGak4b:bxs5bac) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/config.go#L214)):*
> ```Go
> 	StartDiagnosticsReporting bool
> 
> 	// DisableOwnHTTPListener prevents this server from starting a TCP
> ```

nit: wrap
___
*[`pkg/server/config.go` line 216 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVYphu9BO_RHL2dUOU:-NHVYphu9BO_RHL2dUOV:b-yxksx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/config.go#L216)):*
> ```Go
> 	// DisableOwnHTTPListener prevents this server from starting a TCP
> 	// listener for the HTTP service. Instead, it is expected
> 	// that some other service (typically, the server controller)
> ```

s/server controller/serverController
___
*[`pkg/server/config.go` line 218 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVYcD36EpURMR7FF71:-NHVYcD36EpURMR7FF72:b-vedz2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/config.go#L218)):*
> ```Go
> 	// that some other service (typically, the server controller)
> 	// will accept and route requests instead.
> 	DisableOwnHTTPListener bool
> ```

s/DisableOwnHTTPListener/DisableHTTPListener
___
*[`pkg/server/server_controller.go` line 326 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHUVOvb5qur6L2blB3L:-NHVhK5hEvb2dMwvGChl:bhtubhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb68fc15af30f476ed82ea43422cb59d3cd81e0c/pkg/server/server_controller.go#L326)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It's a good question. Alas we can't use stopper.RunAsyncTask here because the call to stopper.Stop inside would then deadlock. Clarified in comment.
</blockquote></details>

but the comment was added in the wrong commit :P
___
*[`pkg/server/server_controller.go` line 188 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVz8ex9L5GKIlJPFIS:-NHVz8ex9L5GKIlJPFIT:b68ph4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L188)):*
> ```Go
> 	}
> 	if tenantName == "" {
> 		// TODO(knz): Make the default tenant route for HTTP configurable.
> ```

Take it or leave it but, in my opinion, TODOs like this serve little purpose other than distracting and making reading the code harder. There's no need for this code to anticipate what might or might not come in the future; the code makes enough sense as it is (TODOs are mostly for when the code makes less than enough sense as it is).
___
*[`pkg/server/server_controller.go` line 194 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_fD1AXIijylipj-j:-NHV_fD1AXIijylipj-k:blcdbjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L194)):*
> ```Go
> 	s, err := c.get(ctx, tenantName)
> 	if err != nil {
> 		log.Warningf(ctx, "unable to find tserver for tenant %q: %v", tenantName, err)
> ```

tserver ?
___
*[`pkg/server/server_controller.go` line 194 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_rAk93WBWyDN6--y:-NHV_rAk93WBWyDN6--z:bh8i2v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L194)):*
> ```Go
> 	s, err := c.get(ctx, tenantName)
> 	if err != nil {
> 		log.Warningf(ctx, "unable to find tserver for tenant %q: %v", tenantName, err)
> ```

s/unable to find/failed to start ?
___
*[`pkg/server/server_controller.go` line 206 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_yz97Z0lOl6zlR6y:-NHV_yz97Z0lOl6zlR6z:b1qghr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L206)):*
> ```Go
> // Used in tests until https://github.com/cockroachdb/cockroach/issues/84585 is resolved.
> func (s *Server) TestingGetSQLAddrForTenant(tenant string) string {
> 	ts, err := s.serverController.get(context.Background(), tenant)
> ```

nit: take in a `ctx`
___
*[`pkg/server/tenant.go` line 330 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVbnnYB5ne0gGLYM6h:-NHVbnnYB5ne0gGLYM6i:b-yxksx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/tenant.go#L330)):*
> ```Go
> 
> 	// If DisableOwnHTTPListener is set, we are relying on the HTTP request
> 	// routing performed by the server controller.
> ```

s/server controller/serverController

**Review by knz — COMMENTED** [review]
>  Could we also take the tenant there

Sure why not. (as convenience)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-:-NH_OhAP4urF_-IYAfBm:b-dbmgfj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @dhartunian, @herkolategan, and @srosenberg)

___
*[`pkg/server/config.go` line 216 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVYphu9BO_RHL2dUOU:-NH_NzhhCQdWyqmw34aG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/config.go#L216)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/server controller/serverController
</blockquote></details>

Done.
___
*[`pkg/server/config.go` line 218 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVYcD36EpURMR7FF71:-NH_O9dn2jBqvwmc5z0j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/config.go#L218)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/DisableOwnHTTPListener/DisableHTTPListener
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 326 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHUVOvb5qur6L2blB3L:-NH_ENwO-Aack1DZxutK:bx60bod) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb68fc15af30f476ed82ea43422cb59d3cd81e0c/pkg/server/server_controller.go#L326)):*
> but the comment was added in the wrong commit :P

dang it you're right. Fixed.
___
*[`pkg/server/server_controller.go` line 188 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVz8ex9L5GKIlJPFIS:-NH_OBIj7u_4-PXEZ0dC:b-a36ikn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Take it or leave it but, in my opinion, TODOs like this serve little purpose other than distracting and making reading the code harder. There's no need for this code to anticipate what might or might not come in the future; the code makes enough sense as it is (TODOs are mostly for when the code makes less than enough sense as it is).
</blockquote></details>

As discussed we're using this to track proress from #91282.
___
*[`pkg/server/server_controller.go` line 194 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_fD1AXIijylipj-j:-NH_OLXU0ZIdx2c9JBpR:bgx0p6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L194)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

tserver ?
</blockquote></details>

Typo. Fixed.
___
*[`pkg/server/server_controller.go` line 194 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_rAk93WBWyDN6--y:-NH_OP9r-OeJtTG0hD5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L194)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/unable to find/failed to start ?
</blockquote></details>

Done.
___
*[`pkg/server/server_controller.go` line 206 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHV_yz97Z0lOl6zlR6y:-NH_O_BHBTRSnvN4aCrZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/server_controller.go#L206)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: take in a `ctx`
</blockquote></details>

Done.
___
*[`pkg/server/tenant.go` line 330 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-NHVbnnYB5ne0gGLYM6h:-NH_Od8-1j8aLHRqkW2_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f88d8cab37ca116583334d327c970e123dac76e2/pkg/server/tenant.go#L330)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/server controller/serverController
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for adding the query param option.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91744#-:-NHzVJ160jXVHHlWm477:bgz7zmn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @herkolategan, and @srosenberg)

**Comment by knz** [comment]
TFYR! 

bors r=andreimatei,dhartunian

**Pull request merged**
