### PR TITLE
sql: tighten dependency span analysis for INSERT ... VALUES

### LINKED ISSUE #14953: sql: reduce planner.Spans size for INSERT with VALUES
The `roachpb.Spans` reported by `insertNode` for queries like `INSERT INTO t VALUES (...)` should be limited to the spans corresponding only to the values themselves, instead of including keys for the entire table. This would allow parallel statements inserting disjoint values into the same table to operate concurrently. For instance:

```
INSERT INTO t VALUES (1, 2) RETURNING NOTHING
INSERT INTO t VALUES (3, 4) RETURNING NOTHING
```

should be considered independent by `spanBasedDependencyAnalyzer` and therefore parallelizable.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #14953.

Previously, the `roachpb.Spans` reported by `collectSpans` for queries like
`INSERT INTO t VALUES (...)` would span the entire table being modified.
This prevented inserts into the same table from being run in parallel.
This change tightens the predicted read and write-sets for `INSERT ... VALUES`
statements. It does so by evaluating the `VALUES` clause ahead of time and
computing the specific index spans that will be touched by each `VALUES` tuple.

The following two statements will now be considered independent by
`spanBasedDependencyAnalyzer`:

```
INSERT INTO t VALUES (1, 2) RETURNING NOTHING
INSERT INTO t VALUES (3, 4) RETURNING NOTHING
```

### CODE REVIEW

**Comment by knz** [comment]
reminder: don't forget to rebase if you plan to continue work on this, and pick up the new RFC sections + naming convention.

**Comment by knz** [comment]
Before I complete my review with this I'd enjoy chatting with you so I can check whether my understanding of this work is correct.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-:-KsPrKcRjCplSI6yO7-0:b-yb4j3u)*

**Comment by knz** [comment]
Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 3 of 3 files at r4.
Review status: 5 of 14 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 1898 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilNAZ1LYADL7E99GP:-KsilNAZ1LYADL7E99GQ:b-flekpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/executor.go#L1898)):*
> ```Go
> 	session.setQueryExecutionMode(stmt.queryID, false /* isDistributed */, true /* isParallel */)
> 
> 	err = session.parallelizeQueue.Add(params, plan, func(plan planNode) error {
> ```

`if err := ...); err != nil {`

---

*[pkg/sql/executor.go, line 1725 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsimtBoZUZDJ5p4jLKU:-KsimtBoZUZDJ5p4jLKV:bv8yt2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1df485d6bad44b856242baf449c2d9bfe46738e/pkg/sql/executor.go#L1725)):*
> ```Go
> // forEachRow calls the provided closure for each successful call to
> // planNode.Next, making sure to properly track memory usage.
> func forEachRow(params runParams, p planNode, f func(planNode) error) error {
> ```

Add a comment to motivate why you chose to give the planNode as argument to the filter function and not the result of `Values()`. 

---

*[pkg/sql/parallel_stmts.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilcrDv73LnbpyWHaa:-KsilcrEj_bdnuQHNKgG:b3cgrqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L229)):*
> ```Go
> type DependencyAnalyzer interface {
> 	// Analyze collects any upfront analysis that is necessary to make future
> 	// independence decisions about the planNode. It should be called before
> ```

s/should/must

---

*[pkg/sql/parallel_stmts.go, line 230 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilaS2e-MIVpDGjZST:-KsilaS2e-MIVpDGjZSU:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L230)):*
> ```Go
> 	// Analyze collects any upfront analysis that is necessary to make future
> 	// independence decisions about the planNode. It should be called before
> 	// calling Independent for each planNode, and the planNode provided should
> ```

ditto

---

*[pkg/sql/parallel_stmts.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilgiTUzi7MKn5X1j_:-KsilgiTUzi7MKn5X1ja:b-7ehflo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L235)):*
> ```Go
> 	Analyze(runParams, planNode) error
> 	// Independent determines if the provided planNodess are independent from
> 	// one another. Either planNode may be running when Independent is called,
> ```

Dangling "Either".

---

*[pkg/sql/plan_spans.go, line 95 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Ksim3eGECnTQAryriUq:-Ksim3eGECnTQAryriUr:b-prepq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b3660f3791aa613641b2fbbd82fbb906f0347e/pkg/sql/plan_spans.go#L95)):*
> ```Go
> 
> 	var writerReads, writerWrites roachpb.Spans
> 	// switch v := r.rows.(type) {
> ```

Stray comment in commit 3.

---

*[pkg/sql/tablewriter.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilCWVlStLH213a_h2:-KsilCWWQfViJL8J6a5N:b-preprs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a608f34e863a96f80a8c3e2c25dbc75508114bb1/pkg/sql/tablewriter.go#L86)):*
> ```Go
> 	// constrain these spans.
> 	spans() (reads, writes roachpb.Spans, err error)
> 	// spansForValues(*valuesNode, runParams) (reads, writes roachpb.Spans, err error)
> ```

Stray comment in commit 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757)*

**Comment by knz** [comment]
Reviewed 7 of 8 files at r5, 1 of 1 files at r6.
Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parallel_stmts.go, line 84 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsirdeTD_KGWCjWjnpg:-KsirdeUis4eUhqszYdM:b-otvrps) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ab64cde03c816518a06d8bc8aa185487619f83/pkg/sql/parallel_stmts.go#L84)):*
> ```Go
> // details.
> func (pq *ParallelizeQueue) Add(params runParams, plan planNode, exec func(planNode) error) error {
> 	prereqs, finishLocked, err := pq.insertInQueue(params, plan)
> ```

I think you can add `defer plan.Close(params.ctx)` here (before the `err` check) insteadof the two occurrences below.

---

*[pkg/sql/subquery.go, line 239 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsirG4D4QnAX9BRccML:-KsirG4D4QnAX9BRccMM:bf48fom) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ab64cde03c816518a06d8bc8aa185487619f83/pkg/sql/subquery.go#L239)):*
> ```Go
> 
> // containsSubqueries checks if the walked plan contains subqueries.
> func containsSubqueries(params runParams, plan planNode) (bool, error) {
> ```

Ugh :(
I'd suggest following the model from 3727237ae57ab5ef79dc242e9b38b52586234e0c instead.
We'll need that bit for other optimization anyways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757)*

**Comment by knz** [comment]
Discussed offline: the current PR is incomplete due to row-dependent default expressions. Looking forward to the update!

---

Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-:-Ksix9NG5Ws0ZXI8vS0D:bg54atq)*

**Comment by nvanbenschoten** [comment]
I've added a pair of commits to address the problem we saw before. As it turns out, DEFAULT expressions were already pushed down to `valuesNodes` in most cases, so row-dependent default expressions wouldn't be an issue for `DefaultVal` expressions. The exception to this was tuples which had fewer elements than the number of columns being inserted into. We now push down the default expressions for these too, so that when we memoize the `valuesNode` results, no row-dependent default expressions are ever evaluated again at a higher level.

---

Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 1898 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilNAZ1LYADL7E99GP:-KsorkZqZgFjXeFCyANy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/executor.go#L1898)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`if err := ...); err != nil {`
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 1725 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsimtBoZUZDJ5p4jLKU:-Ksow1BwI0X3JYi_2vmp:bt4k4p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1df485d6bad44b856242baf449c2d9bfe46738e/pkg/sql/executor.go#L1725)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add a comment to motivate why you chose to give the planNode as argument to the filter function and not the result of `Values()`. 
</blockquote></details>

That's a better interface. Done.

---

*[pkg/sql/parallel_stmts.go, line 229 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilcrDv73LnbpyWHaa:-KsorylL6xF0zTwsKOxF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L229)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/should/must
</blockquote></details>

Done.

---

*[pkg/sql/parallel_stmts.go, line 230 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilaS2e-MIVpDGjZST:-Ksorz5I_rsKN-YhJf5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L230)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/parallel_stmts.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilgiTUzi7MKn5X1j_:-Ksos4lMG2B9xY9HRSa-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb9bb0626b89bae26f790325812e9006438e717/pkg/sql/parallel_stmts.go#L235)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Dangling "Either".
</blockquote></details>

Done.

---

*[pkg/sql/parallel_stmts.go, line 84 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsirdeTD_KGWCjWjnpg:-KsozD2i2fBGvRTGC0uT:b-db6rn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ab64cde03c816518a06d8bc8aa185487619f83/pkg/sql/parallel_stmts.go#L84)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you can add `defer plan.Close(params.ctx)` here (before the `err` check) insteadof the two occurrences below.
</blockquote></details>

One is in the new goroutine though. We only want to close the plan directly in `Add` if we never launch the new goroutine.

---

*[pkg/sql/plan_spans.go, line 95 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Ksim3eGECnTQAryriUq:-KsotRi44LLqZN64NXIn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b3660f3791aa613641b2fbbd82fbb906f0347e/pkg/sql/plan_spans.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Stray comment in commit 3.
</blockquote></details>

Done.

---

*[pkg/sql/subquery.go, line 239 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsirG4D4QnAX9BRccML:-Ksozd-fsFveaeAsZu0Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ab64cde03c816518a06d8bc8aa185487619f83/pkg/sql/subquery.go#L239)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ugh :(
I'd suggest following the model from 3727237ae57ab5ef79dc242e9b38b52586234e0c instead.
We'll need that bit for other optimization anyways.
</blockquote></details>

Done.

---

*[pkg/sql/tablewriter.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsilCWVlStLH213a_h2:-KsorT0bNset81QN7YX4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a608f34e863a96f80a8c3e2c25dbc75508114bb1/pkg/sql/tablewriter.go#L86)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Stray comment in commit 1.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-:-KsqUsiMcQnc0uQp-b5q:b-xuqzrn)*

**Comment by knz** [comment]
Reviewed 1 of 14 files at r7, 2 of 3 files at r8, 3 of 3 files at r9, 3 of 3 files at r10, 4 of 4 files at r11, 3 of 3 files at r12, 9 of 9 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 130 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsryAMMqXSCyS3078pt:-KsryAMNmKJiSRtxAQTY:bnbci8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/insert.go#L130)):*
> ```Go
> 			return nil, err
> 		}
> 		if values != nil {
> ```

if `values == nil`, add a parser.SelectClause under n.Rows which renders the default expressions in addition to the columns produced by the source. This then enables you to remove the extra logic in GenerateInsertRow below.

---

*[pkg/sql/insert.go, line 139 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrzHEwl-TmJt8j13LJ:-KsrzHEy8jNaKbCcrZmb:ba75lgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/insert.go#L139)):*
> ```Go
> 			// tuple, we expect to see extra columns come up from the data source
> 			// planNode. Account for that here.
> 			numInputColumns += addedCols
> ```

What I don't understand is why you need the extra return value in `fillDefaults`. It seems to me that the code in there i guaranteed to always produce a ValuesClause with exactly as many values per rows as there are items in the `cols` argument slice. If that is indeed the case, you can document this in `fillDefaults` contract and set `numInputColumns = len(cols)` here. 

Then, if you combine this with my suggestion above, perhaps you don't need `numInputColumns` at all.

---

*[pkg/sql/insert.go, line 57 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-drNvIjt9PQ_Uf-6:-Kss-drNvIjt9PQ_Uf-7:bp4q4go) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L57)):*
> ```Go
> 	insertColIDtoRowIndex map[sqlbase.ColumnID]int
> 	tw                    tableWriter
> ```

add: `hasSubqueriesInSource bool` here

---

*[pkg/sql/insert.go, line 153 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-oq4BbIASl35ivJ4:-Kss-oq4BbIASl35ivJ5:b-2i84es) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L153)):*
> ```Go
> 	// This performs type checking on source expressions, collecting
> 	// types for placeholders in the process.
> 	rows, err := p.newPlan(ctx, insertRows, desiredTypesFromSelect)
> ```

add:
`defer func(prev bool) { p.hasSubqueries = prev }(p.hasSubqueries)`
before this line

---

*[pkg/sql/insert.go, line 260 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss02KRctcHKETep6lj:-Kss02KSZ6y5UyIXKHyE:b-4tbaj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L260)):*
> ```Go
> 		insertColIDtoRowIndex: ri.InsertColIDtoRowIndex,
> 		isUpsertReturning:     isUpsertReturning,
> 		tw:                    tw,
> ```

Add: 
`hasSubqueriesInSource: p.hasSubqueries`

---

*[pkg/sql/plan_spans.go, line 51 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-95SX8Ex_w259Iml:-Kss-95Ur9S8iE9NlvRb:bh8qg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/plan_spans.go#L51)):*
> ```Go
> 			// subqueries, even within valuesNodes, can be arbitrarily complex,
> 			// so we can't run the valuesNode ahead of time if they are present.
> 			if !params.p.hasSubqueries {
> ```

Not the right condition, should be `if !n.hasSubqueriesInSource {`
See my comments in `insert.go`
(The problem is that there may be subqueries in other places that do not matter.)

---

*[pkg/sql/plan_spans.go, line 99 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrvHywA_fBP4NTT10E:-KsrvHyxygxm0ygWFWgu:b-cmf6qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3460990eae2a222c8d981170a7d60b6b06b86e/pkg/sql/plan_spans.go#L99)):*
> ```Go
> // touched because it performs no predicate analysis. Interestingly, performing
> // this analysis fully with optimal span bounds would reduce to the analysis
> // required for predicate locking.
> ```

Explain / hint what "predicate locking" means.

---

*[pkg/sql/values.go, line 29 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrxM7SHZo7sq9jKCBU:-KsrxM7U1Pw1_2wgcqEh:buwc828) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/values.go#L29)):*
> ```Go
> 
> func newValuesListLenErr(len1, len2 int) error {
> 	return fmt.Errorf("VALUES lists must all be the same length, %d for %d", len1, len2)
> ```

Please take the opportunity to improve the error message. Suggestion: `VALUES lists must all be the same length; expected %d columns, found %d`.

---

*[pkg/sql/values.go, line 122 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss0TdRv7ESsDr8Qr8H:-Kss0TdTEcBXJnAy0iUE:bs61m7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/values.go#L122)):*
> ```Go
> }
> 
> // Start implements the planNode interface. Unlike for most planNode
> ```

I do not believe it is a good idea to use the same type `valuesNode` both for 
- something where the values are evaluated before the plan is started (and therefore, that something *must not* contain subqueries / is guaranteed not to contain subqueries), and where plan evaluation will merely serve precomputed values, which can be done one or more times; and
- something for something where the values are evaluated during plan evaluation, and where plan evaluation must not be done more than once.

The contracts and assertions are different for these two things and having them meshed into the same type makes the code hard to read. (for precedent, this is the kind of reasoning that pushed Justin to split emptyNode into zeroNode/unaryNode)

So I would like to re-propose adding a separate type to hold pre-evaluated values clauses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757)*

**Comment by nvanbenschoten** [comment]
Thanks for your insight here!

---

Review status: 0 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/insert.go, line 130 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsryAMMqXSCyS3078pt:-KswVavp5OlcHKZW8fke:bp8ywga) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/insert.go#L130)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

if `values == nil`, add a parser.SelectClause under n.Rows which renders the default expressions in addition to the columns produced by the source. This then enables you to remove the extra logic in GenerateInsertRow below.
</blockquote></details>

It's not trivial to determine which columns are given and which need to be implicitly added given a `parser.SelectStatement` interface. There are also other consumers of `GenerateInsertRow ` that may rely on the default columns behavior. I like the idea of adding an intermediate `SelectClause` to push down all default handling from `insertNode`, but I'd like to open an issue right now. I don't want to introduce any more refactoring into this already large and fundamentally unrelated change.

---

*[pkg/sql/insert.go, line 139 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrzHEwl-TmJt8j13LJ:-KswgTGNf04szxuuDL6A:b-50by5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/insert.go#L139)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What I don't understand is why you need the extra return value in `fillDefaults`. It seems to me that the code in there i guaranteed to always produce a ValuesClause with exactly as many values per rows as there are items in the `cols` argument slice. If that is indeed the case, you can document this in `fillDefaults` contract and set `numInputColumns = len(cols)` here. 

Then, if you combine this with my suggestion above, perhaps you don't need `numInputColumns` at all.
</blockquote></details>

Things were a little bit more subtle because of how we deal with columns in a migration. I did clean this up quite a bit thanks to your suggestion though.

---

*[pkg/sql/insert.go, line 57 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-drNvIjt9PQ_Uf-6:-KsukwuebqHGx7jk6wSP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add: `hasSubqueriesInSource bool` here
</blockquote></details>

Done.

---

*[pkg/sql/insert.go, line 153 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-oq4BbIASl35ivJ4:-KsulRalhS6FaWDD3GE_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L153)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add:
`defer func(prev bool) { p.hasSubqueries = prev }(p.hasSubqueries)`
before this line
</blockquote></details>

Done.

---

*[pkg/sql/insert.go, line 260 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss02KRctcHKETep6lj:-KsulS1wBl8xjso0GyV1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/insert.go#L260)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add: 
`hasSubqueriesInSource: p.hasSubqueries`
</blockquote></details>

Done.

---

*[pkg/sql/plan_spans.go, line 51 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss-95SX8Ex_w259Iml:-KsulZAVQBEWoYppRlcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/plan_spans.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not the right condition, should be `if !n.hasSubqueriesInSource {`
See my comments in `insert.go`
(The problem is that there may be subqueries in other places that do not matter.)
</blockquote></details>

Done.

---

*[pkg/sql/plan_spans.go, line 99 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrvHywA_fBP4NTT10E:-KswbCYO4gwxQdqDy-Nq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3460990eae2a222c8d981170a7d60b6b06b86e/pkg/sql/plan_spans.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Explain / hint what "predicate locking" means.
</blockquote></details>

Done.

---

*[pkg/sql/values.go, line 29 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-KsrxM7SHZo7sq9jKCBU:-KsumgiQZDC8EVIiZKQ4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e208def09092acd90a677b8691e91fc3c79d61c/pkg/sql/values.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please take the opportunity to improve the error message. Suggestion: `VALUES lists must all be the same length; expected %d columns, found %d`.
</blockquote></details>

Done.

---

*[pkg/sql/values.go, line 122 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss0TdRv7ESsDr8Qr8H:-KswWQbjcgcr_jE-8QEM:b8ex78p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/values.go#L122)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I do not believe it is a good idea to use the same type `valuesNode` both for 
- something where the values are evaluated before the plan is started (and therefore, that something *must not* contain subqueries / is guaranteed not to contain subqueries), and where plan evaluation will merely serve precomputed values, which can be done one or more times; and
- something for something where the values are evaluated during plan evaluation, and where plan evaluation must not be done more than once.

The contracts and assertions are different for these two things and having them meshed into the same type makes the code hard to read. (for precedent, this is the kind of reasoning that pushed Justin to split emptyNode into zeroNode/unaryNode)

So I would like to re-propose adding a separate type to hold pre-evaluated values clauses.
</blockquote></details>

I think you may be underestimating the size and complexity of introducing a `constValuesNode` (or something like it). I started to implement it, and it was neither a small change nor made the code any cleaner. The change resulted in duplicated logic both within the new `planNode` type and outside of it where other code paths now needed to handle both `valuesNode` and `constValuesNode`. Attempting to precompute the values in the `constValuesNode` was also messy because that then required us to change the contract around `planNode.Close` (see TODO).

In fact, I'm not even introducing anything new here (meshing two concepts into the same type). We've already overloaded the contract of `valuesNode` with its use in `newContainerValuesNode`. What I've done now is push the `isConst` state down into `valuesNode`, which unifies some of the logic between `newContainerValuesNode` and Values clauses with no subqueries. This replaces the `hasSubqueries` handling at the `insertNode` layer.

I fully understand the points you made and I think they're valid, but I don't think this is the PR to make such a refactoring. If you'd like, I'd be happy to open an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-:-KswvafTZzlfj4etIChr:bg5lt2d)*

**Comment by knz** [comment]
:lgtm: modulo lint errors

---

Reviewed 2 of 3 files at r17, 2 of 3 files at r18, 2 of 5 files at r19, 2 of 3 files at r20, 9 of 9 files at r21, 1 of 1 files at r22.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/values.go, line 122 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-Kss0TdRv7ESsDr8Qr8H:-KsxRgkqb1PS9p9G1AbH:b8asm2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea225d6eb2f908d1b4dfc60c4af6a17711dac15e/pkg/sql/values.go#L122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you may be underestimating the size and complexity of introducing a `constValuesNode` (or something like it). I started to implement it, and it was neither a small change nor made the code any cleaner. The change resulted in duplicated logic both within the new `planNode` type and outside of it where other code paths now needed to handle both `valuesNode` and `constValuesNode`. Attempting to precompute the values in the `constValuesNode` was also messy because that then required us to change the contract around `planNode.Close` (see TODO).

In fact, I'm not even introducing anything new here (meshing two concepts into the same type). We've already overloaded the contract of `valuesNode` with its use in `newContainerValuesNode`. What I've done now is push the `isConst` state down into `valuesNode`, which unifies some of the logic between `newContainerValuesNode` and Values clauses with no subqueries. This replaces the `hasSubqueries` handling at the `insertNode` layer.

I fully understand the points you made and I think they're valid, but I don't think this is the PR to make such a refactoring. If you'd like, I'd be happy to open an issue.
</blockquote></details>

Ack. The new code with `isConst` is good enough now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17757#-:-KsxS33QypvPUbyNyePT:b7df4fh)*

**Pull request merged**
