### PR TITLE
release-21.1: deps:  google/x/text

### PR DESCRIPTION
**Pull request by knz**
Epic: CREQ-446

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@rickystewart can I request your help with this?  (this is old branch `release-21.1`)

I want to update `DEPS.bzl` but `make bazel-generate` fails with:

```
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/spill/kena/cache/bazel/_bazel_kena/fd4e84c51f365d6a93ea158225b979df/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/spill/kena/cache/bazel/_bazel_kena/fd4e84c51f365d6a93ea158225b979df/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 188, column 30, in download_llvm_preconfigured
                rctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang%2Bllvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz] to /spill/kena/cache/bazel/_bazel_kena/fd4e84c51f365d6a93ea158225b979df/external/llvm_toolchain/temp15552223537400758937/clang%2Bllvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz: Checksum was 6f442c06e452583307a17488370a3ef078830f2238d5705dbd04df4935a01284 but wanted b25f592a0c00686f03e3b7db68ca6dc87418f681f4ead4df4745a01d9be63843

```

**Comment by knz** [comment]
hm nvm, I re-ran the command and the error disappeared. will update DEPS.bzl myself

**Comment by knz** [comment]
@rickystewart is there any way I could mint the update to DEPS.bzl by hand in a text editor?

**Comment by rickystewart** [comment]
@knz Is something busted due to the lack of change to `DEPS.bzl`? Generally we don't need to keep the Bazel stuff up to date on `release-21.2` and `release-21.1` since Bazel isn't used for anything.

**Comment by knz** [comment]
> Generally we don't need to keep the Bazel stuff up to date on release-21.2 and release-21.1 since Bazel isn't used for anything.

Oh, TIL.

**Comment by knz** [comment]
Sadly, this dependency upgrade will be complicated:

1. upgrading `thrift` incurs a build error: 

   ```
   vendor/github.com/openzipkin-contrib/zipkin-go-opentracing/thrift/gen-go/zipkincore/zipkinCore.go:155:37: not enough arguments in call to iprot.ReadStructBegin
   ```

2. if I try to upgrade `github.com/openzipkin-contrib/zipkin-go-opentracing`, I get the following `go mod` error:

```
github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/cliccl imports
        google.golang.org/api/option imports
        google.golang.org/api/internal imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.43.0), but does not contain package google.golang.org/grpc/naming
```

**Comment by knz** [comment]
Let's hold onto this until the appropriate eng team analyzes the impact of the outdated `apache/thrift` version.

**Comment by knz** [comment]
Discussed with @kpatron-cockroachlabs  - we only need to upgrade x/text. This upgrade is clean. Updated the PR; RFAL.

**Review by kpatron-cockroachlabs — APPROVED** [review]

**Comment by knz** [comment]
@rickystewart 
> Is something busted due to the lack of change to DEPS.bzl? Generally we don't need to keep the Bazel stuff up to date on release-21.2 and release-21.1 since Bazel isn't used for anything.

FYI, yes there was a problem: the `lint` CI target was complaining that DEPS.bzl didn't contain the right information. 
Luckily, it also gave me a diff to apply, so I could do just that, but I think I'd prefer if the check wasn't there to start with in those branches.

**Pull request merged**
