### PR TITLE
Add /debug/stopper endpoint

### LINKED ISSUE #5231: server: should expose Stopper.{NumTasks,RunningTasks}
`(*stop.Stopper)` has methods `NumTasks` and `RunningTasks`. The first if self-explanatory and the second prints a map whose keys are `file:line` and the value a count.
Should be helpful for debugging. Maybe `/debug/stopper`?

### PR DESCRIPTION
**Pull request by tbg**
```
0xc8202eb570: 1 tasks
1      server/node.go:700
```

Closes #5231.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5234)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/stop/stopper.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPAHl12pPZnRD2Ve4:-KCqPAHl12pPZnRD2Ve5:130182679) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L30)):*
this doesn't need to be a pointer

---

*[util/stop/stopper.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPOlA0WWoqsCIyDHs:-KCqPJTb_O6swjcfO6d_:569132468) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L111)):*
do these guys get removed anywhere? probably should do that in `Stop`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/stop/stopper.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPAHl12pPZnRD2Ve4:-KCqPiKOahQgEPLjUIZQ:-529581635) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L30)):*
I'm identifying the guys by their address, so I'd like a pointer.

---

*[util/stop/stopper.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPOlA0WWoqsCIyDHs:-KCqPlzcaMBLam9AIjz2:-101807248) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L111)):*
Was trying to dodge this, but I guess I should add it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/stop/stopper.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPAHl12pPZnRD2Ve4:-KCqQ1yxBqP_Ee0RdwDP:-917047670) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L30)):*
note that my comment is on the `trackedStoppers` struct, not the slice of `*Stopper`.

---

*[util/stop/stopper.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPOlA0WWoqsCIyDHs:-KCqQ8lSjKTgyUIHKivH:1300967684) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L111)):*
Yeah, otherwise you're gonna leak all the things in tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/stop/stopper.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPAHl12pPZnRD2Ve4:-KCqS3vffWjceCmT_fbP:722087242) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L30)):*
Ah, gotcha. Done.

---

*[util/stop/stopper.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqPOlA0WWoqsCIyDHs:-KCqRrWVrlUDN7e708WG:-561432819) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be141fee73342c1bf2302fca9781c1abaa6f500/util/stop/stopper.go#L111)):*
Doubt that would actually matter, but should be good now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/stop/stopper.go, line 36 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqS_etbN9YH7xemaww:-KCqS_etbN9YH7xemawx:860240953) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1482564ec2350a39c34a30e1a4792932c47e999/util/stop/stopper.go#L36)):*
haha i think you forgot to call this one. also, maybe use a map now?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[util/stop/stopper.go, line 36 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqS_etbN9YH7xemaww:-KCqT0_9Px6nJPZskex_:1150251804) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1482564ec2350a39c34a30e1a4792932c47e999/util/stop/stopper.go#L36)):*
Haha. Ok, decoy failed. I'm going to call it. Rather not use a map, don't want to have to avoid random ordering stuff in the output (we only have one stopper, but still).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/stop/stopper.go, line 36 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqS_etbN9YH7xemaww:-KCqTMHM4Qn6Hr_NU2fx:527026013) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1482564ec2350a39c34a30e1a4792932c47e999/util/stop/stopper.go#L36)):*
Cool, makes sense.

---

*[util/stop/stopper.go, line 39 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqTTjjWiKz044mqSiX:-KCqTTjjWiKz044mqSiY:619743876) ([raw file](https://github.com/cockroachdb/cockroach/blob/d832f90c65a4b4e9c4b8aed1a5f09fb170ba82bd/util/stop/stopper.go#L39)):*
just noticing this local is not necessary, but whatevs

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-:-KCqTcfqUANlBo8dPwgZ:1417088721)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-:-KCqTcRe_ce6wsKU4VgN:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[util/stop/stopper.go, line 39 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234#-KCqTTjjWiKz044mqSiX:-KCqWiIBuEwZTblA0bH_:910403400) ([raw file](https://github.com/cockroachdb/cockroach/blob/d832f90c65a4b4e9c4b8aed1a5f09fb170ba82bd/util/stop/stopper.go#L39)):*
oh wait, reused below. ignore me

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5234)*

**Pull request merged**
