### PR TITLE
concurrency: enable joint claims on the request scan path

### PR DESCRIPTION
**Pull request by arulajmani**
This patch addresses a TODO that was blocking joint claims on a request's scan path and adds a test to show joint claims work. In particular, previously the lock mode of a queued request was hardcoded to use locking strength `lock.Intent`. We now use the correct lock mode by snapshotting an immutable copy of the request's lock strength on to the queuedGuard when inserting a it into a lock's wait queue.

Informs #102275

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1KRO0nZ5MIczO7zV:-Nah1KRO0nZ5MIczO7zW:b-o2klle) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L926)):*
> ```Go
> }
> 
> // getLockMode returns the lock mode of the queued request. Once a request is
> ```

Instead of re-implementing `lockTableGuardImpl.curLockMode`, should we just store a `lock.Mode` on `queuedGuard` and assign it to `g.curLockMode()` on construction?
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1bcw0KhjihdSC9dF:-Nah1bcw0KhjihdSC9dG:b-w86dw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L2709)):*
> ```Go
> 			qg := &queuedGuard{
> 				guard:  g,
> 				str:    g.curStrength(),
> ```

Should this be `accessStrength`?

Or, if we also address my other comment, should we assign `g.str` in `AddDiscoveredLock`, stop passing in `accessStrength` in here, and call `g.curLockMode`?
___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah2RKz7sd_-avTdVft:-Nah2RKz7sd_-avTdVfu:bicj5ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L106)):*
> ```
> 
> # ------------------------------------------------------------------------------
> # Ensure scanning requests are able to acquire joint claims on the initial
> ```

It feels like this should be built into the test above after `req3`, so that we can demonstrate the possibility of joint claims, but then demonstrate that `req6` still blocks if there are conflicting waiters between it and the claiming reqs. What do you think?

**Review by arulajmani — COMMENTED** [review]
RFAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-:-NarhyEA7kEBdAUsCQ4J:b-828fno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 926 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1KRO0nZ5MIczO7zV:-NarWdu_A-EXcYAm941s:b-8agdrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L926)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of re-implementing `lockTableGuardImpl.curLockMode`, should we just store a `lock.Mode` on `queuedGuard` and assign it to `g.curLockMode()` on construction?
</blockquote></details>

D'oh.
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1bcw0KhjihdSC9dF:-NarhMTAETjt3SyyAfqf:bc8ej16) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L2709)):*
It should; fixed. 

> Or, if we also address my other comment, should we assign `g.str` in `AddDiscoveredLock`, stop passing in `accessStrength` in here, and call `g.curLockMode`?

I ended up opting for something a bit different, because these 3 fields seem to go in tandem:

https://github.com/cockroachdb/cockroach/blob/7a063ff5b40b3e2088e1f8d31ba28b2df499d494/pkg/kv/kvserver/concurrency/lock_table.go#L429-L434

Assigning just one seems error prone; we could assign all 3, but it doesn't seem worth it.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah2RKz7sd_-avTdVft:-Nari7WS49WFTaa-U9uN:b9jtusl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L106)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It feels like this should be built into the test above after `req3`, so that we can demonstrate the possibility of joint claims, but then demonstrate that `req6` still blocks if there are conflicting waiters between it and the claiming reqs. What do you think?
</blockquote></details>

Missed this comment. That does sound reasonable, I'll fix this test case.

**Review by arulajmani — COMMENTED** [review]
RFAL-FR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-:-NarkOsl6t7rgV1_N2Cf:b-59vo2z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah2RKz7sd_-avTdVft:-Nark8Rz11aOMfFJGzml:bcdc2z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks#L106)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Missed this comment. That does sound reasonable, I'll fix this test case.
</blockquote></details>

Done. Sorry for making your job as a reviewer hard with the diff as a result.

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1bcw0KhjihdSC9dF:-Narq-y8DwSabFc20rH_:bohg761) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L2709)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It should; fixed. 

> Or, if we also address my other comment, should we assign `g.str` in `AddDiscoveredLock`, stop passing in `accessStrength` in here, and call `g.curLockMode`?

I ended up opting for something a bit different, because these 3 fields seem to go in tandem:

https://github.com/cockroachdb/cockroach/blob/7a063ff5b40b3e2088e1f8d31ba28b2df499d494/pkg/kv/kvserver/concurrency/lock_table.go#L429-L434

Assigning just one seems error prone; we could assign all 3, but it doesn't seem worth it. 
</blockquote></details>

This still feels like a good amount of code duplication, which is quite unfortunate. Maybe we should add a `lockModeForStrength` method to `lockTableGuardImpl` if we don't want to reach inside and mutate `g.str`?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1bcw0KhjihdSC9dF:-NartIinAnCc7bR7TZZ-:b77cu3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L2709)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This still feels like a good amount of code duplication, which is quite unfortunate. Maybe we should add a `lockModeForStrength` method to `lockTableGuardImpl` if we don't want to reach inside and mutate `g.str`?
</blockquote></details>

How do you feel about a `makeLockMode` function instead? Mostly to avoid any confusion between which fields are coming from the receiver and which ones are being passed in using function arguments.

**Review by nvb — APPROVED** [review]
:lgtm: mod the once nit.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-:-Nas4Iv63vLMS4S_qYe2:b-t3k5uw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 2709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nah1bcw0KhjihdSC9dF:-Nas4FPPAaL3wDltLlgm:b-qx45pc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d5c78fd2224ac7b26e55d060f8253e0a523853d/pkg/kv/kvserver/concurrency/lock_table.go#L2709)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

How do you feel about a `makeLockMode` function instead? Mostly to avoid any confusion between which fields are coming from the receiver and which ones are being passed in using function arguments. 
</blockquote></details>

That SGTM!
___
*[`pkg/kv/kvserver/concurrency/lock_table.go` line 772 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-Nas45kK0ys0Id8kdOPp:-Nas45kK0ys0Id8kdOPq:b-qsvwsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b947d1e8c114d14b0b5ed7aedd1916d173fdc15f/pkg/kv/kvserver/concurrency/lock_table.go#L772)):*
> ```Go
> // makeLockMode constructs and returns a lock mode.
> func makeLockMode(
> 	accessStrength lock.Strength, txn *roachpb.Transaction, ts hlc.Timestamp,
> ```

nit: `str` is probably enough, especially if it avoids the line wrapping.

**Review by arulajmani — COMMENTED** [review]
TFTR! 

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-:-Nas4sE11WbA-xL-0DL6:b-2fjird)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:-FR

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107889#-:-Nas5CRF0OTX7FIodt8V:bks4vns)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
bors r=nvanbenschoten 

(-FR)

**Pull request merged**
