### PR TITLE
builtins: make extract work with TimeTZ

### PR DESCRIPTION
**Pull request by otan**
Refs: #26097

Add extract for TimeTZ, which has a slight extension to that of Time and
a gotcha in epoch.

No release note as this will be combined in a later PR.

Release note: none

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
I messed around a bit with Postgres and it seems like you should not be forcing all values to be positive:
```
solon=# select extract('timezone_hour' from '00:00-01:02'::TIMETZ);
 date_part
-----------
        -1
(1 row)

solon=# select extract('timezone_minute' from '00:00-01:02'::TIMETZ);
 date_part
-----------
        -2
(1 row)

solon=# select extract('timezone' from '00:00-01:02'::TIMETZ);
 date_part
-----------
     -3720
(1 row)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42618#-:-Lu9xYZH9FtLZR8Tw_A-:bd857vw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by otan** [comment]
> I messed around a bit with Postgres and it seems like you should not be forcing all values to be positive:

WEIRD i swear it didn't work

**Comment by otan** [comment]
oh.... i tested timestamptz....

```

otan=# select extract('timezone' from '2001-01-01 11:00+06:00'::timestamptz);
 date_part
-----------
     21600
(1 row)

otan=# select extract('timezone' from '2001-01-01 11:00-06:00'::timestamptz);
 date_part
-----------
     21600
(1 row)

otan=# select extract('timezone' from '2001-01-01 11:00+06:00'::timestamptz);
 date_part
-----------
     21600
(1 row)
```

**Comment by otan** [comment]
oh it's even more subtle than that, for timestamp tz it's always where you are when you `extract`

**Review by solongordon — APPROVED** [review]
:lgtm: modulo one documentation nit.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42618#-:-LuA3e5n2AhgjPH6hzEx:b-cuyw5s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/sem/builtins/builtins.go, line 1835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42618#-LuA3L3N6emgmw1eTHf8:-LuA3L3N6emgmw1eTHf9:b-9l9r49) ([raw file](https://github.com/cockroachdb/cockroach/blob/aefb637d6c1a6a9830d5a97476b32f7298966957/pkg/sql/sem/builtins/builtins.go#L1835)):*
> ```Go
> 			},
> 			Info: "Extracts `element` from `input`.\n\n" +
> 				"Compatible elements: hour, minute, second, millisecond, microsecond, epoch\n" +
> ```

Minor: Missing `,` after `epoch`.

**Pull request merged**
