### PR TITLE
release-22.2: sql,opt: improve SHOW TABLES and virtual tables with many databases

### LINKED ISSUE #90115: sql: DB-scope virtual tables are slow despite a small DB
**Is your feature request related to a problem? Please describe.**

CockroachDB offers per-database metadata schemas `information_schema` and `pg_catalog`. The tables in these schemas are implemented "virtually"; instead of being real tables, we run some code over the internal metadata structures to generate the output. Today, in order to populate the correct set of descriptors, we unconditionally fetch all descriptors. In cases where individual databases are not large, but the total number of descriptors is large, virtual tables are shockingly slow. Importantly, these virtual tables don't need to look at most of these descriptors.

**Describe the solution you'd like**
We can avoid looking at the unwanted descriptors by performing a lookup first against the namespace table and then fetching the descriptors in the database.

**Additional context**
This approach won't help with cases like https://github.com/cockroachdb/cockroach/issues/83626 where individual schemas or databases have large numbers of objects. 

Epic: CRDB-20865

Jira issue: CRDB-20592

### PR DESCRIPTION
**Pull request by ajwerner**
Backport 6/6 commits from #90116.

/cc @cockroachdb/release

---

information_schema and pg_catalog are always scoped to a database. Before this change, we would always look up all descriptors to materialize virtual tables, even if we only care about descriptors in the current database. This PR adds a new cluster setting (so that backports can be made kosher) to enable a new approach: scan the namespace table to find the relevant descriptors and then only resolve those.

On my local machine where I loaded up a few megabytes of descriptors into 6k databases, a simple query like `SELECT * FROM information_schema.sequences` takes 1.2s without the setting enabled and 1ms with it.

Release justification: Fixes an important issue for using many databases.

Fixes #90115

Epic: CRDB-20865
    
Release note (performance improvement): Tables in `pg_catalog` and
`information_schema` (when not explicitly referenced as
`"".information_schema`) may now be much faster if the current database has
a small number of relations relative to the total number in the cluster.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
First commit :lgtm: 

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91054#-:-NFpRIBX2s5j5YhqWMpX:bg60rpc)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
@rafiss can I get a look at this and can you help me decide whether I should default this to off on release-22.2?

**Review by rafiss — APPROVED** [review]
this lgtm, with some minor nits that maybe should be addressed in `master` as well. as far as the default setting value, i feel fine about leaving it as true. one thing i wonder though is how do we envision that someone would know to disable it if they need to? it doesn't seem like something we want to spend time training TSE on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91054#-:-NG2Lq9w1LLTkLaHD3-F:b5plnyq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @rytaft)

___
*[`pkg/sql/crdb_internal.go` line 488 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91054#-NG2KOtPCgD7qm-GfaIG:-NG2KOtPCgD7qm-GfaIH:b-xnrcjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee34eb210064846b741ab19eb0f51fe0218d0a9b/pkg/sql/crdb_internal.go#L488)):*
> ```Go
> 	indexes: []virtualIndex{
> 		{
> 			populate: func(ctx context.Context, unwrappedConstraint tree.Datum, p *planner, _ catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) (matched bool, err error) {
> ```

nit: add a comment to each `populate` to make it clear which index is which
___
*[`pkg/sql/resolver.go` line 988 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91054#-NG2HO3UDS30ycLDb06-:-NG2HO3UDS30ycLDb060:bxs3jvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9d52318cc0af8168af70a792e7d1402347296/pkg/sql/resolver.go#L988)):*
> ```Go
> }
> 
> var metamorphicDeadultUseIndexLookupForDescriptorsInDatabase = util.ConstantWithMetamorphicTestBool(
> ```

nit: typo
___
*[`pkg/sql/delegate/show_tables.go` line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/91054#-NG2JllL3wEo7UvnaHgJ:-NG2JllL3wEo7UvnaHgK:b-njwc0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee34eb210064846b741ab19eb0f51fe0218d0a9b/pkg/sql/delegate/show_tables.go#L113)):*
> ```Go
> 		estimatedRowCount,
> 		estimatedRowCountJoin,
> 		tree.NewDString(name.CatalogName.String()),
> ```

nit: did you test this query with a database named like `"Mixed-Case"`? i believe CatalogName.String() will add those quotes, but for this query we don't want that, so maybe it should just be `string(name.CatalogName)`. also, the `NewDString` is not needed.

**Comment by ajwerner** [comment]
@rafiss TFTR! I added the commits from https://github.com/cockroachdb/cockroach/pull/91292 to this PR to address your feedback.

**Pull request merged**
