### PR TITLE
distsql: add row batching to simple aggregations

### PR DESCRIPTION
**Pull request by asubiotto**
This change does not provide any performance improvements since there are no changes to improve processor efficiency given batches of rows rather than single rows as input. The RowChannel overhead discussed in #20555 was removed in https://github.com/cockroachdb/cockroach/pull/21254 so does not play a factor in this change. The plan is to continue incrementally changing all the processors to send/receive batches of rows and to tackle possible performance improvements within processors later.

I have made some changes to `RowChannel`, `outbox`, and `stream{encoder,decoder}` but will hold off on submitting them until necessary for these changes to be digestible.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
General structure looks good. You might get away by adding a shim processor that is a `RowSource` that unbatches a batch, and then we can use that to hook up a single processor to the rest of the system with just the shim. I think we can do something with less than 500 LoC total that demonstrates the very basics of batching, and quickly use that to iterate.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-:-L3-t5yS6q8DAlnYya4Q:bmtteoc)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 240 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30qAPGw6m_O502Jdrl:-L30qAPGw6m_O502Jdrm:b5mlsz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/aggregator.go#L240)):*
> ```Go
> 		var meta *ProducerMetadata
> 		for {
> 			if batching {
> ```

Placing conditionals like this in our inner-loops is unfortunate for both performance and readability. Rather, I think we should add a wrapper when the processor is created so that if the input does not implement `RowBatchSource`, we wrap the input with a `BatchingRowSource`. Then the code here always knows it has a `RowBatchSource` and the logic is simplified.

---

*[pkg/sql/distsqlrun/base.go, line 51 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pdt06b1aK96O9sXP:-L30pdt1KRMC1GjO7gwp:btjqawo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/base.go#L51)):*
> ```Go
> 
> // RowBatch is a batch of rows. The underlying representation is currently
> // inefficient.
> ```

Can you expand on why this is inefficient? Your future self who has forgotten the reason will thank you.

---

*[pkg/sql/distsqlrun/tablereader.go, line 379 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pDELQndedaSRlaO_:-L30pDELQndedaSRlaOa:b3tvuan) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L379)):*
> ```Go
> // NextBatch is part of the RowBatchSource interface.
> func (tr *tableReader) NextBatch() (RowBatch, *ProducerMetadata) {
> 	batch := make(RowBatch, 0, RowBatchSize)
> ```

This is likely a pessimization. Every call to `NextBatch` will allocate a 10000 element slice, while many times you'll only use a fraction of that data. 

---

*[pkg/sql/distsqlrun/tablereader.go, line 381 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pRq_XnGs31tTlndd:-L30pRq_XnGs31tTlnde:bhgy9zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L381)):*
> ```Go
> 	batch := make(RowBatch, 0, RowBatchSize)
> 	var row sqlbase.EncDatumRow
> 	var meta *ProducerMetadata
> ```

I don't think there is a benefit to declaring these outside the loop.

---

*[pkg/sql/distsqlrun/tablereader.go, line 387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pXEeaeYHjY-X9CLY:-L30pXEeaeYHjY-X9CLZ:b-9bcpta) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L387)):*
> ```Go
> 		// metadata was received.
> 		if tr.pendingMetadata != nil {
> 			meta = tr.pendingMetadata
> ```

`s/meta =/meta :=/g` to scope this `meta` to this block.

---

*[pkg/sql/distsqlrun/tablereader.go, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30qvuG0ZIvnc1oOYoc:-L30qvuG0ZIvnc1oOYod:b-741p15) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L391)):*
> ```Go
> 			return nil, meta
> 		}
> 		if len(batch) == RowBatchSize {
> ```

I know we discussed how often to output batches before, but can't recall the results of that discussion. Can you track that down? I seem to recall that waiting for a batch to become full before outputting was not what we thought was best, but perhaps my memory is failing me. Regardless, we should either link to the discussion here or include some of the rationale in a comment. It isn't obvious to me that this heuristic is good.

---

*[pkg/sql/distsqlrun/tablereader.go, line 394 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30p__D11JuJmxC8V_m:-L30p__D11JuJmxC8V_n:bvuodm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L394)):*
> ```Go
> 			return batch, nil
> 		}
> 		row, meta = tr.Next()
> ```

`s/ = / := /g`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/tablereader.go, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30qvuG0ZIvnc1oOYoc:-L31FZxdV72A__-3c01M:bg0xikq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L391)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I know we discussed how often to output batches before, but can't recall the results of that discussion. Can you track that down? I seem to recall that waiting for a batch to become full before outputting was not what we thought was best, but perhaps my memory is failing me. Regardless, we should either link to the discussion here or include some of the rationale in a comment. It isn't obvious to me that this heuristic is good.
</blockquote></details>

I think we should finish the batch when we have exhausted the KVs we obtained so far (and getting one more row would require another KV request). We will need to plumb some info from the kvfetcher.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489)*

**Comment by asubiotto** [comment]
@arjunravinarayan I don't quite follow what you mean. Since processors still implement `Next` they are still compatible with non-batching processors.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/tablereader.go, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30qvuG0ZIvnc1oOYoc:-L33fIgi8Z958kYwIQpK:bh2jcbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L391)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we should finish the batch when we have exhausted the KVs we obtained so far (and getting one more row would require another KV request). We will need to plumb some info from the kvfetcher.
</blockquote></details>

Here is the comment on the issue: https://github.com/cockroachdb/cockroach/issues/20555#issuecomment-350761628
In this case it would be, as Radu suggests, outputting batches whenever getting another row would result in a kv request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-:-L33g-dEW_2xGvLRUrFh:b-kqf5sh)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/tablereader.go, line 391 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30qvuG0ZIvnc1oOYoc:-L38wLIxdKWdRO9wO9ei:bkntgcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L391)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Here is the comment on the issue: https://github.com/cockroachdb/cockroach/issues/20555#issuecomment-350761628
In this case it would be, as Radu suggests, outputting batches whenever getting another row would result in a kv request.
</blockquote></details>

Thanks for tracking that down. You'll need to extend `MultiRowFetcher` with a call that can determine if the internal buffer is exhausted. That should be relatively straightforward. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489)*

**Comment by arjunravinarayan** [comment]
I don't quite like that design since that puts the burden on a processor to support unrolling their own batch if required. And I don't know what it would mean if someone called `Next` and then followed with a call to `NextBatch`. How about something like adding a couple fields `batchMode` and `unroll` to `processorBase`. If `batchMode` is unset, `NextBatch` should panic. If `batchMode` is set and `Next` is called, then `unroll` gets set, and subsequent calls to `NextBatch` should panic.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-:-L3AGTOgJ5ws3JAG0qXP:bd6ch5l)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/tablereader.go, line 379 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pDELQndedaSRlaO_:-L3AH72GhJc5iWLyeQdD:b-of8xfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L379)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is likely a pessimization. Every call to `NextBatch` will allocate a 10000 element slice, while many times you'll only use a fraction of that data. 
</blockquote></details>

FWIW, I always envisioned the batch size as something like 100, not 10,000.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489)*

**Comment by petermattis** [comment]
> I don't quite like that design since that puts the burden on a processor to support unrolling their own batch if required. And I don't know what it would mean if someone called Next and then followed with a call to NextBatch. How about something like adding a couple fields batchMode and unroll to processorBase. If batchMode is unset, NextBatch should panic. If batchMode is set and Next is called, then unroll gets set, and subsequent calls to NextBatch should panic.

Which design don't you like? 

I'd have to see the details, but adding more fields to `processorBase` doesn't sound good to me. We should be pushing toward more composition of smaller components, not larger components with more special cases.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/tablereader.go, line 379 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-L30pDELQndedaSRlaO_:-L3Af8qKieANqu4ftSPh:b-txluqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f04b500ee8a4d54077f89f6c5a207a2a60312cb/pkg/sql/distsqlrun/tablereader.go#L379)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

FWIW, I always envisioned the batch size as something like 100, not 10,000.
</blockquote></details>

Even if we set `RowBatchSize` to 100 this will be a pessimization. We should let the `batch` slice use the normal growth mechanisms here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21489#-:-L3AeqSiycy_MVSpR3YK:bqq1udx)*

**Comment by asubiotto** [comment]
See https://github.com/cockroachdb/cockroach/issues/20555#issuecomment-362730139

**Pull request closed without merging**
