### PR TITLE
cli/interactive_tests: add tests for --multi-region on demo movr

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Nice!  Just one comment below.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-:-MahpwKl0VZvh4hc8CWW:b-6bn5df)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-Mahn7Jq4DtxH_-0UEYY:-Mahn7Jr5L95j-MCrnVV:bi19d1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b68121ef2598fee2c9b05f88ac336dcbf0a5af/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L22)):*
> ```Tcl
>         # The license server is unreachable. There's not much we can test here.
>         # Simply ignore the test.
>         report "License server could not be reached - skipping with no error"
> ```

Is there any way we could retry here?  My experience has been that license server errors are generally transient.  I'd rather we retry than skip the test.

**Comment by knz** [comment]
> Is there any way we could retry here? My experience has been that license server errors are generally transient. I'd rather we retry than skip the test.

if we retry here, we'll want to retry in the other tests in the same directory that use the same logic.
(perhaps even make a common function to do this)

**Comment by otan** [comment]
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-Mahn7Jq4DtxH_-0UEYY:-MahqFfS5jyJGQeMcB3p:bxrpngc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b68121ef2598fee2c9b05f88ac336dcbf0a5af/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L22)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is there any way we could retry here?  My experience has been that license server errors are generally transient.  I'd rather we retry than skip the test.
</blockquote></details>

I'd count that as an enhancement considering this is just moving a method into a routine and rather do it at a later point.

License server errors also for me last several hours and I'd rather not have CI flake for that long.

**Comment by otan** [comment]
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-Mahn7Jq4DtxH_-0UEYY:-MahqYS25tIssswHrZb-:bw4ezxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b68121ef2598fee2c9b05f88ac336dcbf0a5af/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L22)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'd count that as an enhancement considering this is just moving a method into a routine and rather do it at a later point.

License server errors also for me last several hours and I'd rather not have CI flake for that long. 
</blockquote></details>

(I think this contacts the server which I've seen down for hours at a time but I'm happy to be wrong)

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-Mahn7Jq4DtxH_-0UEYY:-Maht72F9PcW2RNKB-XB:bqm3d9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b68121ef2598fee2c9b05f88ac336dcbf0a5af/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L22)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(I think this contacts the server which I've seen down for hours at a time but I'm happy to be wrong) 
</blockquote></details>

I'm fine hitting retry in a subsequent PR.  Let's just open something to keep track of it.  In my (limited) experience, the license server typically corrects itself within a few seconds (or at worst, a few minutes).

**Comment by otan** [comment]
___
*[pkg/cli/interactive_tests/test_demo_partitioning.tcl, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65767#-Mahn7Jq4DtxH_-0UEYY:-MahtY0M9vsHlDw5CbS9:bnosjk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b68121ef2598fee2c9b05f88ac336dcbf0a5af/pkg/cli/interactive_tests/test_demo_partitioning.tcl#L22)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm fine hitting retry in a subsequent PR.  Let's just open something to keep track of it.  In my (limited) experience, the license server typically corrects itself within a few seconds (or at worst, a few minutes).
</blockquote></details>

There was a time licensing server died and this test broke CI for several hours :)

**Comment by knz** [comment]
oh yeah right, that's another concern. the license server issues are transient but when they occur it's multiple tens of minutes at a time.

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
