### PR TITLE
log: Include raft functions and server uptime in sentry crash reports

### PR DESCRIPTION
**Pull request by a-robinson**
**log: Include raft functions in sentry stacktraces**

Given that raft is a pretty important dependency and that it makes
function calls back into our code, it seems more than worth including
its function call in our sentry stacktraces, which would help with
issues like #14231.

It's kind of a shame that specifying the packages is even needed, but
it looks like it is, judging by the raven-go source code.

**log: Include approximate server uptime in sentry crash reports**

This would be helpful to determine if crashes are happening during
startup or as part of the steady-state operation of a cluster, which
would be useful for crashes such as #16600 and #18085.

### CODE REVIEW

**Comment by a-robinson** [comment]
+ @BramGruneir to make sure this gets looked at by tomorrow

**Comment by BramGruneir** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsvHL-5prttPbsph19v:b-u6qop0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
> ```Go
> }
> 
> func uptimeTag(now time.Time) string {
> ```

Why not just include the String version of the duration?  Why bucket them?  And is you are bucketing them, why stop at 1 day?  (also, isn't 24h 1d?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsvWcZaCX0C8hLiz8pr:b-eezvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not just include the String version of the duration?  Why bucket them?  And is you are bucketing them, why stop at 1 day?  (also, isn't 24h 1d?)
</blockquote></details>

Because by default sentry gives you percentage breakdowns of the value for each tag, and having the values grouped up seems more valuable than having to find the list of tag values for all events with a given stack trace and scan through the dozens or hundreds of individual values to mentally build up a sense of the distribution.

Is it useful when debugging a crash to know whether a server has been running for 1 day or 30 days? Is there any real difference?

I stuck with 24h just because that's how go stringifies durations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsvXp-p39HUefUMNIYY:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Because by default sentry gives you percentage breakdowns of the value for each tag, and having the values grouped up seems more valuable than having to find the list of tag values for all events with a given stack trace and scan through the dozens or hundreds of individual values to mentally build up a sense of the distribution.

Is it useful when debugging a crash to know whether a server has been running for 1 day or 30 days? Is there any real difference?

I stuck with 24h just because that's how go stringifies durations.
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-:-KsvXoBD1SdGRbEZTTYr:bnfp4nl)*

**Comment by dt** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-Ksxe0VjM5J4Fxnk-5hW:b3pceoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

I _do_ think #days is useful in the >24 bucket -- servers crashing after N days is A Thing. We might not get meaningful aggregate percentage there but I think the raw number in an individual report might be useful?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-:-KsxeZbqGeN0J6SmueY4:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsxloPI28gjnSUh8aRH:bz52qf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I _do_ think #days is useful in the >24 bucket -- servers crashing after N days is A Thing. We might not get meaningful aggregate percentage there but I think the raw number in an individual report might be useful?
</blockquote></details>

So you'd prefer to switch to the actual raw number? Or just to include the number of days if it's been more than 24 hours?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsxqVpp9f61tuANTdbU:bj0hj9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

So you'd prefer to switch to the actual raw number? Or just to include the number of days if it's been more than 24 hours?
</blockquote></details>

I was thinking just for >24h case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Comment by a-robinson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-KsxvgSV1h2LOuvchPZT:b-5dcild) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I was thinking just for >24h case.
</blockquote></details>

I can't tell for sure whether you mean you want the raw number if it's >24 hours or just the number of days if it's >24 hours. I've gone with the latter since it makes more sense to me, but let me know if I misinterpreted you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Comment by dt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/log/crash_reporting.go, line 185 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102#-KsvHL-4mGsM5LqbdJNC:-Ksz4F7Spo3V-In3ohdc:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5641daf27faa20faee8e0538f9332e285f613784/pkg/util/log/crash_reporting.go#L185)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I can't tell for sure whether you mean you want the raw number if it's >24 hours or just the number of days if it's >24 hours. I've gone with the latter since it makes more sense to me, but let me know if I misinterpreted you.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18102)*

**Pull request merged**
