### PR TITLE
sql: refactor session phase to its own package

### PR DESCRIPTION
**Pull request by Azhng**
Previously, session phase time tracking code lives in the `sql` package.
Both connExectuor and SQL stats collector depends on the session phase time's
functionaility.
As we move to extracting SQL stats collection to its own package that will be
imported by the `sql` package, we want to avoid having this new package to
depend on `sql` package.

Addresses #65699

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: 

This sort of dependency peeling is a key part f refactoring. Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-:-Mae4kIF2TJMWYyMjb0y:bsoxp08)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sessionphase/session_phase.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-Mae4uUa4tEyM_cGUAvZ:-Mae4uUa4tEyM_cGUAv_:b-e477z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cbf29befd9044c7744108dce6045c2b27e0bea/pkg/sql/sessionphase/session_phase.go#L99)):*
> ```Go
> )
> 
> type PhaseTimes interface {
> ```

total nit: could call this just `Times`, in my head I like to read type names as package.name. 
___
*[pkg/sql/sessionphase/session_phase.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-Mae53Kt50F6hteHVxvU:-Mae53Ku0PXw4bbRxNCF:b60pmiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cbf29befd9044c7744108dce6045c2b27e0bea/pkg/sql/sessionphase/session_phase.go#L99)):*
> ```Go
> )
> 
> type PhaseTimes interface {
> ```

This will need a comment

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65734)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sessionphase/session_phase.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-Mae5OcwCD2ULB9yqH7-:-Mae5OcwCD2ULB9yqH70:b6gmf45) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cbf29befd9044c7744108dce6045c2b27e0bea/pkg/sql/sessionphase/session_phase.go#L99)):*
> ```Go
> )
> 
> type PhaseTimes interface {
> ```

Also a nit: I don't think you need to make everything an interface when you pull it into another package. I don't expect this to ever have another implementation. I think it also would be reasonable to just make `phaseTimes` be implemented as below and then return a pointer to that thing. I have a slight preference for that in this case. 
```
type Times struct {
     times [SessionUmPhases]time.Time
}
```

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65734)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/sessionphase/session_phase.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-Mae53Kt50F6hteHVxvU:-MaeOncg6HHLWUH9PqmS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cbf29befd9044c7744108dce6045c2b27e0bea/pkg/sql/sessionphase/session_phase.go#L99)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This will need a comment
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65734#-:-Maf-zbSDomyUZMHlmjd:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by Azhng** [comment]
TFTR!

bors r=ajwerner

**Pull request merged**
