### PR TITLE
roachprod-microbench: refactor cli to use cobra

### PR DESCRIPTION
**Pull request by herkolategan**
This change introduces cobra to manage cli flags, as the flat structure before struggled to account for the various actions that `roachprod-microbench` can perform. Commands have now been split into run and compare; with the aim to add an additional command for metrics export later on.

The run command continues to do the orchestration and execution of the benchmarks on a cluster. While the compare command is used to analyse the output provided by the run command. 

The CI script is also updated, which will split out the compare step. This makes it easier to view the comparison results on CI separately from the run output.

Epic: CRDB-20903

### CODE REVIEW

**Review by renatolabs — COMMENTED** [review]
Not sure this is mentioned somewhere and I missed it, but is the idea that we'd make the `compare` build in TC dependant on the `run` build (i.e., compare what has just been run)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-:-NVfSb7z2t9dVU9Z7AKC:b-ohfpkz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

___
*[`build/teamcity/cockroach/nightlies/microbenchmark_weekly_compare.sh` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfMoRyEybFETnzzaiu:-NVfMoRyEybFETnzzaiv:bsk2yh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/build/teamcity/cockroach/nightlies/microbenchmark_weekly_compare.sh#L20)):*
> ```Shell
> 
> # Generate sheets
> ./bin/roachprod-microbench compare "$COMPARE_NEW_DIR" "$COMPARE_OLD_DIR" --sheet-desc="$SHEET_DESCRIPTION"
> ```

Where was `roachprod-microbench` compiled?
___
*[`pkg/cmd/roachprod-microbench/compare.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfMwCVBsZ3ipExKs9z:-NVfMwCVBsZ3ipExKsA-:b-3au6fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L42)):*
> ```Go
> }
> 
> func makeCompare(config compareConfig) (*compare, error) {
> ```

Nit: typically constructor functions for structs are called `newStruct` instead of `makeStruct`.
___
*[`pkg/cmd/roachprod-microbench/compare.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfNOBS2fUcxFFNz_nE:-NVfNOBVC_FMM2QEz9Gj:b-ywuats) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L130)):*
> ```Go
> 			sheetName += " " + c.sheetDesc
> 		}
> 		url, err := c.service.CreateSheet(context.Background(), sheetName, tables)
> ```

Nit: it wouldn't hurt to keep a context in `compare` and pass that here, in case we want to have a single context controlling everything `compare` does (same for other structs in this PR).
___
*[`pkg/cmd/roachprod-microbench/main.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfPSEMCp8QXZsT_jO7:-NVfPSEN4h351y_c8r9y:b-2xpf0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/main.go#L88)):*
> ```Go
> 		})
> 
> 		config := executorConfig{
> ```

Nit: maybe a matter of personal preference, but I prefer the `{Type}VarP` class of functions and using that to populate the struct automatically instead of doing it ourselves here. Example

```go
var executorConfig config
cmd.Flags().StringVarP(&config.timeout, flagTimeout, "", "timeout")
```

(like we do in roachprod/roachtest, for example)

We could also make use of cobra's `MarkFlagRequired` instead of implementing the `mustGet` functions for the different types ourselves.
___
*[`pkg/cmd/roachprod-microbench/main.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfRVaeBlE0s6X2Sq9B:-NVfRVaeBlE0s6X2Sq9C:b9nuje) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/main.go#L131)):*
> ```Go
> 	cmd.Flags().String(flagRemoteDir, "/mnt/data1/microbench", "working directory on the target cluster")
> 	cmd.Flags().String(flagTimeout, "20m", "timeout for each benchmark e.g. 10m")
> 	cmd.Flags().String(flagShell, "COCKROACH_RANDOM_SEED=1", "additional shell command to run on node before benchmark execution")
> ```

Is this the actual default command that is run before the benchmarks? Should it be defined in a variable somewhere? Actually, that would apply to a lot of the defaults in this list.
___
*[`pkg/cmd/roachprod-microbench/util.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfSOaG2DdjmnbWxnau:-NVfSOaHE1pxRDXkK-K-:bdnlt91) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/util.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

Nit: 2023.
___
*[`pkg/cmd/roachprod-microbench/executor.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfNseQ-NDhmnhnI_9v:-NVfNseQ-NDhmnhnI_9w:b-agw9nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/executor.go#L94)):*
> ```Go
> 		}
> 		if !strings.HasSuffix(binariesName, ".tar") && !strings.HasSuffix(binariesName, ".tar.gz") {
> 			return nil, fmt.Errorf("the binaries archive %s must have the extention .tar or .tar.gz", binariesName)
> ```

Nit: `extension`

**Review by herkolategan — COMMENTED** [review]
Actually now that you mention it, I think I'll fold it back in to the original script. I wanted split out the steps so it's easier to find the compare results containing links to the google sheets on TC. But maybe it would be better to pipe the produced sheet links to a file in the artifacts folder?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-:-NVff1qrAqB6WgIdrteP:b-xwsjwq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260)

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`build/teamcity/cockroach/nightlies/microbenchmark_weekly_compare.sh` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfMoRyEybFETnzzaiu:-NVfgWrS5wtsQa9H6fU8:b-pt77bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/build/teamcity/cockroach/nightlies/microbenchmark_weekly_compare.sh#L20)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Where was `roachprod-microbench` compiled?
</blockquote></details>

This script is meant to be run after the main execution script which compiles the binaries. But as I mentioned I think I'm going to move this back in to the main microbenchmark script to keep everything together.
___
*[`pkg/cmd/roachprod-microbench/compare.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfMwCVBsZ3ipExKs9z:-NVfghm5-EBb3ol0Stlc:b5j1azg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L42)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: typically constructor functions for structs are called `newStruct` instead of `makeStruct`.
</blockquote></details>

Thanks for the pointer, I'll update.
___
*[`pkg/cmd/roachprod-microbench/compare.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfNOBS2fUcxFFNz_nE:-NVfgqwx8Fpju4vv4scj:b-ovwaw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L130)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: it wouldn't hurt to keep a context in `compare` and pass that here, in case we want to have a single context controlling everything `compare` does (same for other structs in this PR).
</blockquote></details>

Good idea.
___
*[`pkg/cmd/roachprod-microbench/main.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfPSEMCp8QXZsT_jO7:-NVhRpfK1FF8B6a8wGrV:b-9hfa9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/main.go#L88)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: maybe a matter of personal preference, but I prefer the `{Type}VarP` class of functions and using that to populate the struct automatically instead of doing it ourselves here. Example

```go
var executorConfig config
cmd.Flags().StringVarP(&config.timeout, flagTimeout, "", "timeout")
```

(like we do in roachprod/roachtest, for example)

We could also make use of cobra's `MarkFlagRequired` instead of implementing the `mustGet` functions for the different types ourselves.
</blockquote></details>

I followed the `dev` way of doing it, but I think I prefer this way as well. Thanks for pointing it out. Updated.
___
*[`pkg/cmd/roachprod-microbench/main.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfRVaeBlE0s6X2Sq9B:-NVhTPM79lNJgmPQLshM:bbdlhpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/main.go#L131)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is this the actual default command that is run before the benchmarks? Should it be defined in a variable somewhere? Actually, that would apply to a lot of the defaults in this list.
</blockquote></details>

Yes that is the default. But I figure what you mean here is to use the same style used in `roachprod` where the options struct has a default initialiser, and we pass that to cobra via its *Var functions?
___
*[`pkg/cmd/roachprod-microbench/util.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfSOaG2DdjmnbWxnau:-NViPeLmDIozpb0ryaJF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/util.go#L1)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: 2023.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachprod-microbench/executor.go` line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVfNseQ-NDhmnhnI_9v:-NVfgtN60yrqaN-XA5xC:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/executor.go#L94)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: `extension`
</blockquote></details>

done.

**Comment by smg260** [comment]
*[`pkg/cmd/roachprod-microbench/compare.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVjWGKJ8ICgs9txnDoW:-NVjWGKJ8ICgs9txnDoX:b-jyre9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L86)):*
> ```Go
> 					results.old = append(results.old, postfixResultWithPackage(pkg, result))
> 					resultMutex.Unlock()
> 				}); err != nil && !errors.Is(err, os.ErrNotExist) {
> ```

What if the err is `ErrNotExist`? Should we log this, or is it an acceptable state?

**Comment by smg260** [comment]
*[`pkg/cmd/roachprod-microbench/compare.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NVjWGKJ8ICgs9txnDoW:-NVjWprODUD-YjHw-AwT:b-r7m7yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d304d08f0662d5710acf0860d27147aff0aa19ba/pkg/cmd/roachprod-microbench/compare.go#L86)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

What if the err is `ErrNotExist`? Should we log this, or is it an acceptable state?
</blockquote></details>

nvm - I see your comment at the top

**Review by renatolabs — APPROVED** [review]
:lgtm:

Seems like a lot of the functions in `util.go` can be removed now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-:-NWEMkMVCnh9xugRnD26:b-l0oeng)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260)

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWENpQw-MTxRPXuHVHO:-NWENpQxEDAF0MGiWeYz:b-ll0dwo) (no related file):*
If I understand correctly, we'll output the link to the Google sheets in `sheets.txt`, and people will have to go look for that specific artifact to check the results, yes?

Should we post an update in the `#perf` channel? Since this is a weekly job, it should add very little noise, and IMO would help build the habit to check these results.

We have some (unused) code in roachtest's `slack.go` that we might be able to use.

___

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWENpQw-MTxRPXuHVHO:-NWEOfgc3CvOFfIXQOfC:b-k6h7on) (no related file):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

If I understand correctly, we'll output the link to the Google sheets in `sheets.txt`, and people will have to go look for that specific artifact to check the results, yes?

Should we post an update in the `#perf` channel? Since this is a weekly job, it should add very little noise, and IMO would help build the habit to check these results.

We have some (unused) code in roachtest's `slack.go` that we might be able to use.
</blockquote></details>

Not for this PR, of course, this is just an idea that came to mind as I reviewed.

___

**Review by smg260 — COMMENTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWEUXj96q98ZAHPKZGw:-NWEUXj96q98ZAHPKZGx:b-4o95nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/257406d11cef3fe30bc9448db9285839584532ce/pkg/cmd/roachprod-microbench/compare.go#L87)):*
> ```Go
> 					results.old = append(results.old, postfixResultWithPackage(pkg, result))
> 					resultMutex.Unlock()
> 				}); err != nil && !errors.Is(err, os.ErrNotExist) {
> ```

I believe you can use `oserror.IsNotExist(err) ` - In one of my PRs, a linter complained about something that lead me to using this.
___
*[`pkg/cmd/roachprod-microbench/main.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWEVyUxCgaTXTauaB7s:-NWEVyUxCgaTXTauaB7t:b-7sctb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/257406d11cef3fe30bc9448db9285839584532ce/pkg/cmd/roachprod-microbench/main.go#L85)):*
> ```Go
> 	cmd.Flags().StringVar(&config.binaries, "binaries", config.binaries, "portable test binaries archive built with dev test-binaries")
> 	cmd.Flags().StringVar(&config.compareBinaries, "compare-binaries", "", "run additional binaries from this archive and compare the results")
> 	cmd.Flags().StringVar(&config.outputDir, "outputdir", config.outputDir, "output directory for run log and microbenchmark results")
> ```

super nit: we have `compare-binaries` which is hyphen separated, but the `*dir` flags are just onewordified. Might make sense to have them consistent?
___
*[`pkg/cmd/roachprod-microbench/main.go` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWEWGeSBfl9_CYErEni:-NWEWGeSBfl9_CYErEnj:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/257406d11cef3fe30bc9448db9285839584532ce/pkg/cmd/roachprod-microbench/main.go#L126)):*
> ```Go
> 		RunE:  runCmdFunc,
> 	}
> 	cmd.Flags().StringVar(&config.sheetDesc, "sheet-desc", "", "append a description to the sheet title when doing a comparison")
> ```

same as above

**Review by herkolategan — COMMENTED** [review]
good catch, almost forgot to remove those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-:-NWHrjvr1_kydi4Fm0fH:bmbcyt0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWEUXj96q98ZAHPKZGw:-NWHrngo8JKinQsjJ2vU:bbj2icf) ([raw file](https://github.com/cockroachdb/cockroach/blob/257406d11cef3fe30bc9448db9285839584532ce/pkg/cmd/roachprod-microbench/compare.go#L87)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

I believe you can use `oserror.IsNotExist(err) ` - In one of my PRs, a linter complained about something that lead me to using this.
</blockquote></details>

ah good catch, this is a remnant that can be updated from when this use to support gcs as well.
___
*[`pkg/cmd/roachprod-microbench/main.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWEVyUxCgaTXTauaB7s:-NWHrLgp6Fn4z2wTbcXi:b-e9aj05) ([raw file](https://github.com/cockroachdb/cockroach/blob/257406d11cef3fe30bc9448db9285839584532ce/pkg/cmd/roachprod-microbench/main.go#L85)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

super nit: we have `compare-binaries` which is hyphen separated, but the `*dir` flags are just onewordified. Might make sense to have them consistent?
</blockquote></details>

super nit acknowledged, I've been eyeing it too, will update.

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103285)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @smg260)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/103285#-NWENpQw-MTxRPXuHVHO:-NWILYWf9ftU1HnCnjoP:b-pgni4n) (no related file):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not for this PR, of course, this is just an idea that came to mind as I reviewed.
</blockquote></details>

Good idea, I'll add it to my notes.

___

**Comment by herkolategan** [comment]
bors r=renatolabs

**Pull request merged**
