### PR TITLE
gossip: provide online method to clear leaked gossip infos

### LINKED ISSUE #85013: kv: provide online method to clear leaked gossip infos
In a support escalation (https://github.com/cockroachlabs/support/issues/1709) for a v21.1 cluster, we saw that [leaked gossip entries](https://github.com/cockroachdb/cockroach/blob/9e1e2235a05ab0b2a77f917ba7bce303f6b8fe4a/pkg/sql/stats/new_stat.go#L112-L119) could impact foreground latency. The gossip leak itself has [since been fixed](https://github.com/cockroachdb/cockroach/commit/d07b32db3e49e91a438619586534b3ccc9813bcc), but there was no way to clear the leaked gossip values without a simultaneous, cluster-wide restart.

**It would have been valuable to have a way to expire gossip information manually.**

As a strawman, imagine a builtin function like `crdb_internal.expire_gossip_info(key)` that did the following:
```go
info := gossip.get(key)
if info != nil {
    gossip.addInfo(key, info.value, ttl=1m)
}
```
By injecting a 1m expiration, the gossip info would have enough time to propagate across the cluster but would then expire after a minute, clearing out the leaked information.

Jira issue: CRDB-18003

### PR DESCRIPTION
**Pull request by nvb**
Fixes #85013.
Needed (in v21.2.X) for cockroachlabs/support#1709.

This commit introduces a new `crdb_internal.unsafe_clear_gossip_info` builtin
function which allows admin users to manually clear info objects from the
cluster's gossip network. The function does so by re-gossiping an identical
value for the specified key but with a TTL that is long enough to reasonably
ensure full propagation to all nodes in the cluster but short enough to expire
quickly once propagated.

The function is best-effort. It is possible for the info object with the low
TTL to fail to reach full propagation before reaching its TTL. For instance,
this is possible during a transient network partition. The effect of this is
that the existing gossip info object with a higher (or no) TTL would remain
in the gossip network on some nodes and may eventually propagate back out to
other nodes once the partition heals.

@knz: I'm assigning this to you for a review both because you're as good a
person as any to look at gossip-related changes, and because limited SQL
access to the cluster's gossip network is a nuanced subject in the
context of multi-tenancy.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85505)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/gossip/gossip.go` line 1097 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-N8YRO2T4AXdveaCk534:-N8YRO2T4AXdveaCk535:b-yvmzcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f7b3b463dc339df376071b6548c4f525a7c6c/pkg/gossip/gossip.go#L1097)):*
> ```Go
> 	if err != nil {
> 		if errors.HasType(err, KeyNotPresentError{}) {
> 			// Info object does not exist. Nothing to do.
> ```

nit: it may not be present on _this node_, _yet_ but already populated on some other node.

Don't you want to issue the replacement key anyway, as a sort of "poison"?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85505)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/gossip/gossip.go` line 1097 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-N8YRO2T4AXdveaCk534:-N8Z9ymQ0pe0Mgsrzy0I:byvksh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f7b3b463dc339df376071b6548c4f525a7c6c/pkg/gossip/gossip.go#L1097)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: it may not be present on _this node_, _yet_ but already populated on some other node.

Don't you want to issue the replacement key anyway, as a sort of "poison"? 
</blockquote></details>

Yeah, I think that's the more ideal thing to do. However, if the info is not present on this node yet, we don't know what value to associate with it when poisoning. We could give it a nil value, but I have concerns about taking a gossip key that code reasonably expects will always have a value if present (e.g. `"store"` -> `roachpb.StoreDescriptor`), and then giving it no key. If any code is making assumptions about the value, we could cause issues (e.g. crash loops) which would then be hard to work around without a full cluster power cycle.

Gossiping a poison entry with the existing key-value avoids this issue, but then has the problem you mention.

What do you think?

**Review by knz — APPROVED** [review]
:lgtm: with nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-:-N8ZEX666OfQY9Z98i7O:b-xv64lu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/gossip/gossip.go` line 1097 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-N8YRO2T4AXdveaCk534:-N8ZEHbr0Pv5Wu-N8bMe:bu8uelq) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f7b3b463dc339df376071b6548c4f525a7c6c/pkg/gossip/gossip.go#L1097)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I think that's the more ideal thing to do. However, if the info is not present on this node yet, we don't know what value to associate with it when poisoning. We could give it a nil value, but I have concerns about taking a gossip key that code reasonably expects will always have a value if present (e.g. `"store"` -> `roachpb.StoreDescriptor`), and then giving it no key. If any code is making assumptions about the value, we could cause issues (e.g. crash loops) which would then be hard to work around without a full cluster power cycle.

Gossiping a poison entry with the existing key-value avoids this issue, but then has the problem you mention.

What do you think?
</blockquote></details>

yeah I didn't think about the fact that consumers likely make assumption about the format of the value. I guess this is fine.

But then please adjust the comment to "Info object not known on this node. We can't force a deletion preemptively, e.g. with a poison entry, because we do not have a valid value object to populate."

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-:-N8Zi45BEAl8h6qoKVN_:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[`pkg/gossip/gossip.go` line 1097 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85505#-N8YRO2T4AXdveaCk534:-N8Zi5CMA7gNfkZIrv91:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/521f7b3b463dc339df376071b6548c4f525a7c6c/pkg/gossip/gossip.go#L1097)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah I didn't think about the fact that consumers likely make assumption about the format of the value. I guess this is fine.

But then please adjust the comment to "Info object not known on this node. We can't force a deletion preemptively, e.g. with a poison entry, because we do not have a valid value object to populate."
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=knz

**Pull request merged**
