### PR TITLE
util/log: explain why log.Fatal never returns

### PR DESCRIPTION
**Pull request by knz**
Found while working on  #34366.

log.Fatal has an interesting logic to ensure it never returns,
together with a timeout in case something bad happens. This logic is
non-trivial and wasn't documented. This patch adds some doc.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
This will need a backport.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
Thanks!

**Review by petermattis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/util/log/clog.go, line 944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34367#-LXQG42G7ptW-cEHJeEd:-LXQG42G7ptW-cEHJeEe:b-fu7tmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec996de55a69f795d22b5451423665ab0d558518/pkg/util/log/clog.go#L944)):*
> ```Go
> 		l.putBuffer(buf)
> 	}
> 	l.mu.Unlock()
> ```

Looks to me like `flushAndSync` wants to be called with the lock held. 
___
*[pkg/util/log/clog.go, line 950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34367#-LXQGO5m729FkmPnurDi:-LXQGO5m729FkmPnurDj:b-ysykyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec996de55a69f795d22b5451423665ab0d558518/pkg/util/log/clog.go#L950)):*
> ```Go
> 		close(fatalTrigger)
> 		// Wait and prevent the function from returning - the goroutine
> 		// above will ensure the process terminates.
> ```

I'd describe this as blocking rather than waiting. This goroutine will never move past this line of code.

**Comment by knz** [comment]
on second read, I realize my change was bogus. I simply hadn't read the entire function thoroughly. Arguably it was missing some explanation, which I added in comments. But there is no code change needed.

**Review by petermattis — APPROVED** [review]
Heh, I didn't see that either. The new comments LGTM.

**Pull request merged**
