### PR TITLE
kvserver: export lock table metadata via concurrency manager

### LINKED ISSUE #74832: kv: implement cmd to query lock table
Part of #67589.

As part of the work to expose which transactions are currently holding which locks (and blocking other waiting transactions), we will need to implement a new command to query the `lockState` objects in the lock table.  This command will need to iterate through the Concurrency Manager's lock table as well as the wait queues on each lock to collect the information we intend to expose.

### PR DESCRIPTION
**Pull request by AlexTalks**
This change adds support for exporting lock table metadata using the
`LockStateInfo` protobuf structure.  The metadata is exposed via the
Concurrency Manager, such that it can be queried during command
evaluation.  While previously we had support for exposing lock table
metrics, this change adds support for capturing and exposing a snapshot
state of the locks actively held (and waited on) in the lock table.

Resolves #74832.

Release note: None

Release justification: New observability for use in visualizing
contention, without changes to existing functionality.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCa6Vo-oVrptvDVByn:-MxCa6Vo-oVrptvDVByo:b-qg5zgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/concurrency_control.go#L257)):*
> ```Go
> 	// QueryLockTableState gathers detailed metadata on locks tracked in the lock
> 	// table that are part of the provided span (if non-nil) and key scope.
> 	QueryLockTableState(ctx context.Context, span *roachpb.Span, opts QueryLockTableOptions) ([]roachpb.LockStateInfo, QueryLockTableResumeState)
> ```

nit: `roachpb.Span` is typically passed around by value, not reference. Is the idea that a nil span means "scan everything"? If so, the canonical way to represent that is `keys.EverythingSpan`.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCaM2ICszW2eWlb6hg:-MxCaM2ICszW2eWlb6hh:b-7wlt5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/concurrency_manager.go#L146)):*
> ```Go
> 	cfg.initDefaults()
> 	m := new(managerImpl)
> 	lt := newLockTable(cfg.MaxLockTableSize, cfg.RangeDesc.GetRangeID(), timeutil.DefaultTimeSource{})
> ```

nit: `s/GetRangeID()/RangeID/`
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCaPqf8YRQDgtVnzZC:-MxCaPqf8YRQDgtVnzZD:b-n7trvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/concurrency_manager.go#L503)):*
> ```Go
> }
> 
> // QueryLockTableState implements the LockManager interface
> ```

nit: missing punctuation.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2885 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCbx_z2XedMMPU55M7:-MxCbx_z2XedMMPU55M8:b-p3wskl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/lock_table.go#L2885)):*
> ```Go
> 		l := iter.Cur()
> 		if span != nil {
> 			if l.key.Compare(span.Key) < 0 || (len(span.EndKey) > 0 && span.EndKey.Compare(l.key) < 0) {
> ```

We should be able to do something like we do earlier in this file to iterate over the specific key range we want without this logic:
```go
ltRange := &lockState{key: startKey, endKey: span.EndKey}
for iter.FirstOverlap(ltRange); iter.Valid(); iter.NextOverlap(ltRange) {
    ...
}
```
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCd_ZO2ffQWDgTrA_T:-MxCd_ZO2ffQWDgTrA_U:bw4zy8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/lock_table.go#L2893)):*
> ```Go
> 			nextKey = l.key
> 			nextByteSize = int64(lInfo.Size())
> 			lInfo.RangeID = t.rID
> ```

I've gone back and forth, so I don't feel strongly, but did you consider populating RangeID for each of the LockStateInfo values above this level (in `cmd_query_locks.go`) and keeping the lockTable RangeID oblivious?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2896 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCcbrJ5YOoNrOVIZlK:-MxCcbrJ5YOoNrOVIZlL:b-pcopxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/lock_table.go#L2896)):*
> ```Go
> 
> 			// Check if adding the lock would exceed our byte or count limits.
> 			if opts.TargetBytes > 0 && (numBytes+nextByteSize) > opts.TargetBytes {
> ```

You mentioned not wanting to support the allow_empty option. That seems fine, but then I think we need to default to the behavior of `allow_empty = false`, not the behavior of `allow_empty = true`. In other words, we need to ensure that at least one lock is returned, otherwise a client may be starved by a single large lock. That's probably worth a test case.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/query, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCdKFZ4eBZz7RAwzQW:-MxCdKFZ4eBZz7RAwzQX:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/testdata/lock_table/query#L1)):*
> ```
> new-lock-table maxlocks=10000
> ```

Nice test!

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCd_ZO2ffQWDgTrA_T:-MxjUbtC5O1lvpA8nuxL:b-hk5x64) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/lock_table.go#L2893)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I've gone back and forth, so I don't feel strongly, but did you consider populating RangeID for each of the LockStateInfo values above this level (in `cmd_query_locks.go`) and keeping the lockTable RangeID oblivious?
</blockquote></details>

I did, but I think it makes the most sense to add it here where we're populating the rest of the data - I think it makes the logic easier to reason about and understand.  Especially since we don't have to pass in anything new to the concurrency manager to do so.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2896 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCcbrJ5YOoNrOVIZlK:-MxjdHVD12DQ9bCN0EcU:ba83bao) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/lock_table.go#L2896)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You mentioned not wanting to support the allow_empty option. That seems fine, but then I think we need to default to the behavior of `allow_empty = false`, not the behavior of `allow_empty = true`. In other words, we need to ensure that at least one lock is returned, otherwise a client may be starved by a single large lock. That's probably worth a test case.
</blockquote></details>

OK - that seems reasonable.  Added.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/query, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxCdKFZ4eBZz7RAwzQW:-Mxjdth_BcnE88FKE9wH:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86123e3a911bac197db5d0c3cc0bc4a98d40ad5/pkg/kv/kvserver/concurrency/testdata/lock_table/query#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Thanks!

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-:-MxkTHIVETDj9FCPJfCT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 2916 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-MxkT8k5EQfoV2697mAw:-MxkT8k5EQfoV2697mAx:b6ja8f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/13c45af6e9a48059603237762a643d1de8f64efc/pkg/kv/kvserver/concurrency/lock_table.go#L2916)):*
> ```Go
> 		resumeState.ResumeNextBytes = nextByteSize
> 		resumeState.ResumeSpan = &roachpb.Span{Key: nextKey}
> 		if len(span.EndKey) > 0 && !bytes.Equal(span.EndKey, roachpb.KeyMax) {
> ```

Why the `!bytes.Equal(span.EndKey, roachpb.KeyMax)` condition?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76968#-:-MxklBkn-a3mxDILnCgp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks)

**Pull request merged**
