### PR TITLE
sql: refactor window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, ArgIdxStart variable of windowFuncHolder had to meanings:
one to specify the index of the first argument, and another to tell
the windower where to put the output of a window function. Also,
windowers would "consume" columns that were arguments to window
functions computed on a particular stage. This required careful
manipulation with ArgIdxStart's of window functions computed on
different stage. Additionally, this required rendering arguments
for every window function separately (i.e. without reusing the
renders).

Now, windowers will pass through all of its input columns and append
new columns for the results of window functions' computations at a
particular stage. windowFuncHolders now store information about
indices of the columns where the arguments are which allows us to
reuse renders as much as possible.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Now, it is ready for a look. I wasn't sure whom to ask for a review, but you guys, Jordan and Justin, probably have the most context.

**Review by justinj — COMMENTED** [review]
non distsql stuff LGTM, but I wonder if it might be easier to define a different planNode with simpler semantics and avoid changing any of the existing windowNode planning stuff, since hopefully that codepath will be more-or-less dead in 19.2.

> Reviewed 3 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-:-Ld5OnIX3-AQRKqHvAx3:buw3uol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/window.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-Ld5JXRU84L__8Gte4-P:-Ld5JXRU84L__8Gte4-Q:bbr2kc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8810d0fe35bd4c3091e3b60f532c141bf3e37e66/pkg/sql/window.go#L49)):*
> ```Go
> 	// to migrate IndexedVars and aggregate functions below the windowing level.
> 	colAndAggContainer windowNodeColAndAggContainer
> ```

I think the semantics of `windowNode` could do to be a little more clearly defined in the comments here, it's not clear where the decisions for where the various columns go are made (lots of them live elsewhere, in the `windowFuncHolder`, for instance, but that could be made clearer here via some comments).

In particular it's not really clear to me how to specify the passthrough columns here, does it involve setting up the renders in a particular way? The ideal API for me would be to just have a list of column indices which are passed through directly from the input (we don't want to pass through, say, arguments that were not reused from some other projection).
___
*[pkg/sql/window.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-Ld5LAlgBt_pQMg-Uh_C:-Ld5LAlgBt_pQMg-Uh_D:b-84bjp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8810d0fe35bd4c3091e3b60f532c141bf3e37e66/pkg/sql/window.go#L178)):*
> ```Go
> }
> 
> // extractWindowFunctions loops over the render expressions and extracts any
> ```

All the various `windowNode` helper functions are a little :microscope::dog: to me, this looks reasonable (and hopefully this codepath can go away soon, to be replaced with opt).

**Review by yuzefovich — COMMENTED** [review]
Hm, having a different planNode might be a good idea - both you and I are working on window functions at the moment, and it might be easier to get what we need with starting from scratch.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-:-Ld6SMSg09bwxv4mUyVr:b-fmrmu7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

___
*[pkg/sql/window.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-Ld5JXRU84L__8Gte4-P:-Ld6RPoE-cLVP34UxyKk:b-djvn1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8810d0fe35bd4c3091e3b60f532c141bf3e37e66/pkg/sql/window.go#L49)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think the semantics of `windowNode` could do to be a little more clearly defined in the comments here, it's not clear where the decisions for where the various columns go are made (lots of them live elsewhere, in the `windowFuncHolder`, for instance, but that could be made clearer here via some comments).

In particular it's not really clear to me how to specify the passthrough columns here, does it involve setting up the renders in a particular way? The ideal API for me would be to just have a list of column indices which are passed through directly from the input (we don't want to pass through, say, arguments that were not reused from some other projection).
</blockquote></details>

I left a comment describing what happens with the columns, hopefully that will clear up things a bit. I don't want to be extremely verbose since I think this stuff is subject to change very soon, so if something is unclear, just ping me and I'll do my best to explain what's happening.

Also, the PR is already getting too big, so I want to merge this as is and can modify the API (to flesh out pass through columns) later in addition to being able to pass through constant arguments as a single variable instead of rendering a full column for it.
___
*[pkg/sql/window.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-Ld5LAlgBt_pQMg-Uh_C:-Ld6RA637PAutuIIh7FT:bclsezj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8810d0fe35bd4c3091e3b60f532c141bf3e37e66/pkg/sql/window.go#L178)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

All the various `windowNode` helper functions are a little :microscope::dog: to me, this looks reasonable (and hopefully this codepath can go away soon, to be replaced with opt).
</blockquote></details>

Yeah, my hope is the same.

**Review by yuzefovich — COMMENTED** [review]
I've rebased on top of Justin's PR, so this is ready for a look. cc @jordanlewis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-:-LdBOF4AEkrrWn16tLVl:b4c7z12)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @justinj)

**Review by jordanlewis — COMMENTED** [review]
So much deleted code! :lgtm: except for the comment on the distsql version - that must be bumped or else this will break mixed version clusters.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-:-LdBuxvM2Rw7Ws77a_Dy:b-dskf3x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/distsqlpb/processors.proto, line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-LdBuL5ACx-eUpdqyDHz:-LdBuL5ACx-eUpdqyDI-:bf7aiyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfe34c5fd97ad0bbbf8bed65478d9dec65ce9a/pkg/sql/distsqlpb/processors.proto#L997)):*
> ```protobuf
>     // ArgsIdxs contains indices of the columns that are arguments to the
>     // window function.
>     repeated uint32 argsIdxs = 7;
> ```

A change like this means that new nodes will no longer be able to communicate with old nodes, and vice versa. To solve this, DistSQL has a versioning scheme. You will need to update the `MinAcceptedVersion` and `Version` fields in `server.go` to make sure things work ok, and update the `version.txt` file explaining the change.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-:-LdEjbdd43xbUknFCGfS:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

___
*[pkg/sql/distsqlpb/processors.proto, line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36943#-LdBuL5ACx-eUpdqyDHz:-LdEjYEYE9n5vVHDZUm8:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfe34c5fd97ad0bbbf8bed65478d9dec65ce9a/pkg/sql/distsqlpb/processors.proto#L997)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

A change like this means that new nodes will no longer be able to communicate with old nodes, and vice versa. To solve this, DistSQL has a versioning scheme. You will need to update the `MinAcceptedVersion` and `Version` fields in `server.go` to make sure things work ok, and update the `version.txt` file explaining the change.
</blockquote></details>

Done, thanks!

**Pull request merged**
