### PR TITLE
server: fix race in `TestCachedSettingsServerRestart`.

### PR DESCRIPTION
**Pull request by shubhamdhama**
Before this change, we picked the expected value without waiting for all settings to be updated in the cache. This could lead to a race condition in rare cases where the settings watcher had not yet received some of the settings through rangefeed. We would assign those incomplete settings to `expectedSettingsCount`, and just before stopping the server, the settings cache would receive the remaining ones.

Informs: #124419. We haven't seen this issue on the current master yet, likely due to some improvements in rangefeed performance. This fix will be backported.

Epic: CRDB-38882
Release note: None

### CODE REVIEW

**Comment by shubhamdhama** [comment]
Fixing this issue in master doesn't harm but just an fyi this issue only happens in 23.1.x.

**Review by stevendanna — APPROVED** [review]
:lgtm:

Thanks for digging into this!

**Comment by shubhamdhama** [comment]
Thanks for the review!

bors r=stevendanna

**Comment by shubhamdhama** [comment]
blathers backport 23.1

**Pull request merged**
