### PR TITLE
server: fail readiness checks for server.drain.unready_wait

### PR DESCRIPTION
**Pull request by asubiotto**
To interact well with load balancers, we should wait an amount of time
    in an unready state yet still be operational. Otherwise load balancers
    may not pick up draining nodes and may send them client traffic.

    A cluster setting has been added (server.drain.unready_wait) to control
    the length of time spent in this state since it is dependent on load
    balancer settings set by the operator.

    Addresses #22424 (will close manually once it is a confirmed fix)

    Release note (bug fix): Add server.drain.unready_wait cluster setting
    and wait for that length of time in an unready state before draining to
    not get client requests while draining behind a load balancer.

Will be cherrypicked into 1.1 and 2.0

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm: modulo name bike shedding.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/server.go, line 92 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6SxsTtc3MRfW22wrAK:-L6SxsTtc3MRfW22wrAL:b-wmdwrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L92)):*
> ```Go
> 
> 	subsystemDrainMaxWait = settings.RegisterDurationSetting(
> 		"server.drain.subsystem_max_wait",
> ```

The `server.drain_max_wait` setting is new in 2.0, right?

What does "subsystem" mean here? Why should all subsystems wait the same amount of time?

---

*[pkg/server/server.go, line 98 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6SyfqpN4As7kHhC7qP:-L6SyfqpN4As7kHhC7qQ:bbe7cvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L98)):*
> ```Go
> 
> 	drainUnreadyWait = settings.RegisterDurationSetting(
> 		"server.drain.unready_wait",
> ```

I don't love the name `unready_wait`.  I think this period is the real "draining" part of the process, so how about `server.shutdown.drain_wait`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-:-L6Sx6r6NsNljevQ8x2O:b-efe6h)*

**Comment by asubiotto** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/server.go, line 92 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6SxsTtc3MRfW22wrAK:-L6YYwVq4YOvhdAobUhn:b5yqrzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L92)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

To second this, "subsystem" isn't a word that has any particular shared meaning in cockroach. It's not at all clear to me what it means in this context, so it almost certainly won't mean anything to users.
</blockquote></details>

Yeah, this setting is new in 2.0, I wasn't planning on cherrypicking the first commit into 1.1. Subsystem means `pgwire` and `distsql`. This is essentially a grace period given to running queries to finish in (`pgwire` waits for queries using this node as the gateway, `distsql` waits for any queries in which the node is participating). I renamed this setting to `server.shutdown.query_wait` with a (hopefully) better explanation (in practice we could end up waiting 2*`query_wait`). We might want to split this into two settings but I want to limit the change in this PR to clarification of the setting.

---

*[pkg/server/server.go, line 98 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6SyfqpN4As7kHhC7qP:-L6TLQRjecHi9B8qg0v4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L98)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[pkg/server/server.go, line 99 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6TFokawD7S_n5th8y5:-L6TLIzshMALPUMtD4f7:b-lsj974) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L99)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The help text of these two settings isn't enough for me to really understand the difference between them or how they interact with each other. Mind trying to clarify them?
</blockquote></details>

Clarified them, let me know if it still isn't clear.

---

*[pkg/server/server.go, line 1365 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-L6TH-_8qCoAY4q1hfbp:-L6TKu1NDkxn4Nl1THJJ:b-14c599) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7934ed6d58e8a71d83e14ce8ad50f0ed7a94455/pkg/server/server.go#L1365)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It shouldn't be part of this PR, but is it odd that we serialize the different drain modes? Why wouldn't we want to, for example, drain leases at the same time as clients?
</blockquote></details>

Draining clients includes a grace period in which we wait for work to complete (that's what the subsystem thing is all about, I agree it's pretty unclear), we wouldn't want to be transferring leases around while stuff is still executing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233)*

**Comment by asubiotto** [comment]
Updated, also modified some tests that would become slower/fail because of this slowness due to the wait. PTAL.

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-:-L6YjimC60vYldGjRtei:b-1bkkj8)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23233#-:-L6YxQrLfg-pr0_l-hTG:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm: - we should also update the `cockroach gen haproxy` command to use the new readiness endpoint for its health checks, and this is probably worth calling out in docs as well.

---

Reviewed 1 of 3 files at r3, 2 of 7 files at r4.
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23233#-:-L6bOM7aDq-0560NZ6nq:b7rv02x)*

**Pull request merged**
