### PR TITLE
opt,ccl: eliminate Project inside GroupBy, add tests for validation of partial unique indexes

### PR DESCRIPTION
**Pull request by rytaft**
**opt: add a test-only check for `NullsAreDistinct` in `GroupingPrivate`**

This commit adds a check that `NullsAreDistinct` is true iff the grouping
operator is `UpsertDistinctOn` or `EnsureUpsertDistinctOn`.

Release note: None

**opt: add exploration rule to eliminate `Project` inside `GroupBy`**

This commit updates the exploration rule `EliminateIndexJoinInsideGroupBy`
and renames it to `EliminateIndexJoinOrProjectInsideGroupBy`. The rule now
removes either an `IndexJoin` or `Project` operator if it can be proven that
the removal does not affect the output of the parent grouping operator.

Removal of a `Project` is needed in cases where the partial index predicate
constrains some columns to be constant, and therefore provides those
columns as constant projections. If the projected columns are not actually
needed by the `GroupBy`, however, the `Project` is not necessary and interferes
with other rules matching, such as `SplitGroupByScanIntoUnionScans`.

Informs #65473

Release note (performance improvement): Improved the efficiency of validation
for some partial unique indexes in `REGIONAL BY ROW` tables by improving the
query plan to use all streaming operations.

**ccl: add tests for validation of partial unique indexes**

This commit adds tests to ensure that the expected query plan is used
to validate new partial unique indexes in `REGIONAL BY ROW` tables.

Informs #65473

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Hold off on reviewing this -- I need to make a change.

**Comment by rytaft** [comment]
Ok, RFAL

**Review by mgartner — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 2 of 2 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67263#-:-MdxpVld7OCbJQdk0OzZ:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/67263#-Mdxp7IA8yBwZN_DzbwS:-Mdxp7IA8yBwZN_DzbwT:b12oqa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6424f6b49d245b987ab65fff07e891be81937596/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1560)):*
> ```
>                     │ estimated row count: 10
>                     │
>                     ├── • union all
> ```

I think it would be helpful for users if EXPLAIN clearly showed that these union-all's are locality optimized. Definitely not necessary for this PR, but what do you think?

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67263#-:-Mdxrr2QEiF1vN3UoZ-C:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/67263#-Mdxp7IA8yBwZN_DzbwS:-MdxqV9rCfQyJAXkDyxr:blwqjok) ([raw file](https://github.com/cockroachdb/cockroach/blob/6424f6b49d245b987ab65fff07e891be81937596/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1560)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think it would be helpful for users if EXPLAIN clearly showed that these union-all's are locality optimized. Definitely not necessary for this PR, but what do you think?
</blockquote></details>

These UNION ALLs aren't actually locality optimized -- they are streaming due to the ordering on `+b`. https://github.com/cockroachdb/cockroach/issues/66211 is already open to improve EXPLAIN for locality optimized UNION ALLs, but that wouldn't apply here (locality optimized UNION ALL must have a limit).

We could make it clearer that this is a streaming op, I guess -- is that what you had in mind? (In that case, we'd also want to make that change for group by...)

**Comment by mgartner** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/67263#-Mdxp7IA8yBwZN_DzbwS:-MdyE4Sp6WRo6Q6tE7U8:bqrpijv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6424f6b49d245b987ab65fff07e891be81937596/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1560)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These UNION ALLs aren't actually locality optimized -- they are streaming due to the ordering on `+b`. https://github.com/cockroachdb/cockroach/issues/66211 is already open to improve EXPLAIN for locality optimized UNION ALLs, but that wouldn't apply here (locality optimized UNION ALL must have a limit).

We could make it clearer that this is a streaming op, I guess -- is that what you had in mind? (In that case, we'd also want to make that change for group by...)
</blockquote></details>

Heh, ya I was confused, sorry. Thanks for the link to #66211. But yes, I think our `EXPLAIN` and `EXPLAIN (opt)` are too cryptic for streaming set operations. IIRC segmented sorts are also cryptic. Maybe we should expand #66211 to include more EXPLAIN improvements beyond LOS.

cc'ing @vy-ton to help prioritize this.

**Pull request merged**
