### PR TITLE
[WIP] sql: add telemetry for cross-db references for views, sequence ownership, and FKs

### LINKED ISSUE #67807: sql: Add telemetry for different cross-database references
We don't have telemetry for these cross-database references:

- foreign key constraints
- sequence ownership
- views

Data here would be helpful since we plan to remove these cross-database references in a future release.

Epic: CRDB-1519

### PR DESCRIPTION
**Pull request by sajjadrizvi**
Previous, we were not recording telemetry for cross-database views,
sequences, and foreign-key constraints. This commit adds the
functionality to record these cross-database references (a) during a
long-running migration, and (b) when they are created.

Release justification: low-risk changes to existing functionality

Release note: None

Fixes: #67807

### CODE REVIEW

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sajjadrizvi)

___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69774#-MibRqZv2AfWTpmhyVVl:-MibRqZw8wNKCkOlnwIt:b9xzw5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fc90d02a24c9e9f1bdc6eda8862136a8709a93d/pkg/migration/migrations/fix_descriptor_migration.go#L136)):*
> ```
> 	var ids []descpb.ID
> 	var descs []descpb.Descriptor
> 	var timestamps []hlc.Timestamp
> ```

We can combine these in a structure!
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69774#-MibRCeP8M4ZlADnH4Q7:-MibRCeP8M4ZlADnH4Q8:b8j2kb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fc90d02a24c9e9f1bdc6eda8862136a8709a93d/pkg/migration/migrations/fix_descriptor_migration.go#L139)):*
> ```Go
> 	var descs []descpb.Descriptor
> 	var timestamps []hlc.Timestamp
> 	var allDescs []descpb.Descriptor
> ```

I am not that happy to add `allDescs` as it can defeat the purpose of batching here. What was the motivation for batching? Is memory usage a concern?
___
*[pkg/migration/migrations/fix_descriptor_migration.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69774#-MibRPcb8dhyM-sTzN5m:-MibRPcb8dhyM-sTzN5n:b-2x3hc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fc90d02a24c9e9f1bdc6eda8862136a8709a93d/pkg/migration/migrations/fix_descriptor_migration.go#L210)):*
> ```Go
> 	}
> 
> 	dg := catalog.MakeMapDescGetter()
> ```

I have created a mapped descGetter as we have access to all descriptors. Should I be using another mechanism to get a table from its ID?

**Comment by sajjadrizvi** [comment]
This PR can now be reviewed.

**Comment by postamar** [comment]
Before reviewing this in more detail I'd like to know if you shouldn't also be adding telemetry when restoring a backup? This would count as a form of creation, I'd think.

**Comment by ajwerner** [comment]
Consider also `IMPORT`.

**Review by sajjadrizvi — COMMENTED** [review]
Yes, I am missing some places. I should add telemetry in `ALTER` as well, in addition to `IMPRT` and `RESTORE`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69774#-:-Mj5kgRA3-vY_q8zmU7H:b-k7kqgz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sajjadrizvi)

**Pull request closed without merging**
