### PR TITLE
sql: fix random syntax tests + refactor

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9048)

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/rsg_test.go, line 170 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgPaYORRvYJwjuxqo:-KQdgPaZtRyyh5kvDJY1:b-fk7bl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L170)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	// Broadcast channel for all workers.
> ```

You could have a `var err error` here

---

*[sql/rsg_test.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgSIWhF7hAOQdZEIH:-KQdgSIWhF7hAOQdZEII:b-tyus0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L181)):*
> ```Go
> 			default:
> 			}
> 			f(db, r)
> ```

`err = f(db, r); if err != nil { return }`

---

*[sql/rsg_test.go, line 191 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgTcwxcmepAa0La_R:-KQdgTcwxcmepAa0La_S:b-eritfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L191)):*
> ```Go
> 	close(done)
> 	wg.Wait()
> }
> ```

then after the `Wait`, `if err != nil { t.Fatalf("%v", err) }`, so you can remove the `panic()` calls throughout.

---

*[sql/rsg_test.go, line 55 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdh4CBPriYsnoTGvzb:-KQdh4CBPriYsnoTGvzc:brxgg83) ([raw file](https://github.com/cockroachdb/cockroach/blob/67d7d2d29fa3afadd9377b7ad9347ca51efb8d35/sql/rsg_test.go#L55)):*
> ```Go
> 			return false
> 		}
> 		_, _ = db.Exec(`ROLLBACK`)
> ```

I think I'd like to test the `err` for each of these `Exec`'s and return the `err` instead of `bool`.

---

*[sql/split_at_test.go, line 141 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdhNmN2tQsJJNo6cES:-KQdhNmODIVeLPCgWEuH:bzhiruc) ([raw file](https://github.com/cockroachdb/cockroach/blob/67d7d2d29fa3afadd9377b7ad9347ca51efb8d35/sql/split_at_test.go#L141)):*
> ```Go
> 		} else {
> 			// Successful split, verify it happened.
> 			rng, err := s.DistSender().LookupRange(key)
> ```

It looks like this change belongs to a separate commit/PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/rsg_test.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgSIWhF7hAOQdZEIH:-KQkzdicHNvJdHUuUIM-:b-oi5doc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L181)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> `err = f(db, r); if err != nil { return }`
</details>
I tried this and it makes a bad design. There are only a few times where panic is called, and otherwise errors are fine. So the `f` func here would have to have a return signature of `(bool, error)` because we can't just return the errors from a db.Exec since they can be != nil and that's fine.  And I'd honestly prefer to have a panic because then I get a stack trace of where that happened instead of hiding it in an error message.

---

*[sql/rsg_test.go, line 55 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdh4CBPriYsnoTGvzb:-KQkx5ScU42J_I-tVJv_:b-9t8usa) ([raw file](https://github.com/cockroachdb/cockroach/blob/67d7d2d29fa3afadd9377b7ad9347ca51efb8d35/sql/rsg_test.go#L55)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think I'd like to test the `err` for each of these `Exec`'s and return the `err` instead of `bool`.
</details>
It's not an error for the ROLLBACK to fail. It's there just in case the random statement started a transaction. The CREATE should always succeed, though.

---

*[sql/split_at_test.go, line 141 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdhNmN2tQsJJNo6cES:-KQl11pNSzMCuV5z0BG9:b-834n6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/67d7d2d29fa3afadd9377b7ad9347ca51efb8d35/sql/split_at_test.go#L141)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> It looks like this change belongs to a separate commit/PR.
</details>
Oops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/rsg_test.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgSIWhF7hAOQdZEIH:-KQlR3chtG1neIlNbS8a:bf0b6ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L181)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I tried this and it makes a bad design. There are only a few times where panic is called, and otherwise errors are fine. So the `f` func here would have to have a return signature of `(bool, error)` because we can't just return the errors from a db.Exec since they can be != nil and that's fine.  And I'd honestly prefer to have a panic because then I get a stack trace of where that happened instead of hiding it in an error message.
</details>
fwiw `errors.Errorf` or `errors.New` capture stack traces which can be seen if printed with `%+v`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/rsg_test.go, line 181 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQdgSIWhF7hAOQdZEIH:-KQmDFCd0rAVp6PHgwFE:bhorre3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ec8d579d9bea91431c4d169e65c116325c93ed5/sql/rsg_test.go#L181)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> fwiw `errors.Errorf` or `errors.New` capture stack traces which can be seen if printed with `%+v`.
</details>
Your call, just make sure that errors don't disappear :)

---

*[sql/rsg_test.go, line 52 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-KQmDUhV_gVsqpCI1CBP:-KQmDUhV_gVsqpCI1CBQ:bu8w8os) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a1779e85ddeb3f1f7216999488664e1cf7c35b/sql/rsg_test.go#L52)):*
> ```Go
> 	testRandomSyntax(t, nil, func(db *gosql.DB, r *rsg.RSG) bool {
> 		s := r.Generate(rootStmt, 20)
> 		// TODO(mjibson): figure out why these run slowly. May be a bug.
> ```

Perhaps this would be better filed as an issue rather than a TODO. (just a suggestion)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048#-:-KQmDQyiW4ORxbYJDkEn:bnfp4nl)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9048)*

**Pull request merged**
