### PR TITLE
cli: improve tsdump datadog upload

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, tsdump datadog upload was time consuming. This was due to synchronous upload requests to datadog. Along with this, we were decoding raw data to TimeSeriesData. Then again converting it to DatadogSeries. This change addresse both challenges. We are now decoding timeseries data to DatadogSeries. We have decoupled deocding & uploading data so that we will perform both operations concurrently.

Epic: CC-27740
Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
In the future it would be helpful to move the code in a separate commit because it's difficult to review what's changed.

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-:-O7V_xwHEjeBGUxGqhu1:blehaez)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @arjunmahishi)

___
*[`pkg/cli/tsdump_upload.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VcoeC82wNAK25rgFG:-O7VcoeC82wNAK25rgFH:b9xujhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L206)):*
> ```Go
> 		Type:   DatadogSeriesTypeUnknown,
> 		Points: make([]DatadogPoint, len(data.Datapoints)),
> 	}*/
> ```

nit: can you remove this if it's unneeded.
___
*[`pkg/cli/tsdump_upload.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7UTjDD80gGdAv0F0D3:-O7UTjDE2PdnYYN4DXuS:b-t32yq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L320)):*
> ```Go
> 	}
> 
> 	ch := make(chan tup, 8192*1000)
> ```

Can you explain why you select this channel size in a comment? It seems quite large. Do we expect to make 8 million HTTP requests to Datadog?
___
*[`pkg/cli/tsdump_upload.go` line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VfchV3MA92rCEUESz:-O7VfchV3MA92rCEUET-:b-w6eu0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L337)):*
> ```Go
> 
> 	for {
> 		data, err := recvDatadogSeries()
> ```

If all you're doing is immediately consuming all the messages on `ch` in this infinite loop, there's no need for the channel at all. You can replace this with a call to `decodeOne()`.

I think what you might want to do instead is to fire off N concurrent workers in a loop and then have each of those consume concurrently from the channel. Use a waitGroup to wait for all items on the channel to be processed.

I'm surprised we don't get rate limited using the current approach.
___
*[`pkg/cli/tsdump_upload.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VcaLuCWHRc374YHuG:-O7VcaLuCWHRc374YHuH:b-oli3y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L351)):*
> ```Go
> 		go func() {
> 			// requestChannel is closed when the process exits, so closing channel here is
> 			// more for extra protection.
> ```

nit: this comment doesn't make sense here.
___
*[`pkg/cli/tsdump_upload.go` line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VccfbAaSWxL2Q0jW-:-O7VccfbAaSWxL2Q0jW0:bnliy9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L354)):*
> ```Go
> 			err := d.emitDataDogMetrics(data)
> 			if err != nil {
> 				fmt.Printf("rertries exhausted for datadog upload containing series: %s", data[0].Metric)
> ```

nit: "retries". Also the error should be encoded in the message so we can debug.

**Review by arjunmahishi — COMMENTED** [review]
I think we've discussed most of the below points offline also. Just leaving the comments here for reference. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-:-O7YEm4u6dwbD-j-koyY:br27zkp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @dhartunian)

___
*[`pkg/cli/tsdump_upload.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7UTjDD80gGdAv0F0D3:-O7YD_d9-np0lHG8m72n:b-626m04) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L320)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you explain why you select this channel size in a comment? It seems quite large. Do we expect to make 8 million HTTP requests to Datadog?
</blockquote></details>

The channel size can be a small multiple of `no_of_consumers`.
Like `no_of_consumers * 4` will make sure that there is enough work for each consumer to dequeue 4 times before the producer is blocked. 
___
*[`pkg/cli/tsdump_upload.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y6DYP018NWnDN0tfY:-O7Y6DYP018NWnDN0tfZ:b13w2lh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L324)):*
> ```Go
> 		// ch is closed when the process exits, so closing channel here is
> 		// more for extra protection.
> 		defer close(ch)
> ```

This channel should not be closed by the "producer". It should be closed by the orchestrator spawning this go routine. There is a risk of panic. Also, we need to close the channel only when everything is dequeued (so that we dont miss sending any metric).

In this case (since this is a single run CLI command), we don't actually need to worry about closing the channel. The process will anyway exit soon after the upload is done. 
___
*[`pkg/cli/tsdump_upload.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y89ID5Fk1JQi8poeF:-O7Y89ID5Fk1JQi8poeG:b-23khb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L326)):*
> ```Go
> 		defer close(ch)
> 		for {
> 			data, err := decodeOne()
> ```

The EOF check done below needs to be moved back here. That is the condition that will break this loop. Right now, the loop is running infinitely. That's probably why the `defer close(ch)` has not caused a problem :) 
___
*[`pkg/cli/tsdump_upload.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y7gWS6feZOUZkhtPS:-O7Y7gWS6feZOUZkhtPT:bk77m2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L327)):*
> ```Go
> 		for {
> 			data, err := decodeOne()
> 			ch <- tup{data, err}
> ```

Right now, the decode is happening in a single go routine. If the decode process is concurrency safe, we can consider calling decode concurrently in multiple go-routines.
___
*[`pkg/cli/tsdump_upload.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7YEZ3K2_j18XrfAiQo:-O7YEZ3K2_j18XrfAiQp:b-bwwdr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L339)):*
> ```Go
> 		data, err := recvDatadogSeries()
> 		if err == io.EOF {
> 			if len(data) != 0 {
> ```

Looking at the implementation of decode, it looks like there will either be data or error. Never both.

**Comment by arjunmahishi** [comment]
*[`pkg/cli/tsdump_upload.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y7gWS6feZOUZkhtPS:-O7YFe-R1elv7suiNlLI:b-s6rvgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L327)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Right now, the decode is happening in a single go routine. If the decode process is concurrency safe, we can consider calling decode concurrently in multiple go-routines.
</blockquote></details>

Ignore this. We discussed that the decode is not concurrency safe.

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arjunmahishi and @dhartunian)

___
*[`pkg/cli/tsdump_upload.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VcoeC82wNAK25rgFG:-O7YTon5-2z9ro8fQvQU:bb6tyiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L206)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can you remove this if it's unneeded.
</blockquote></details>

DONE
___
*[`pkg/cli/tsdump_upload.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7UTjDD80gGdAv0F0D3:-O7YU80t--oIxePhnD2w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L320)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

The channel size can be a small multiple of `no_of_consumers`.
Like `no_of_consumers * 4` will make sure that there enough work for each consumer can dequeue 4 times before the producer is blocked.
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump_upload.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y6DYP018NWnDN0tfY:-O7YUAGn2UmETfkd-WDS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L324)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

This channel should not be closed by the "producer". It should be closed by the orchestrator spawning this go routine. There is a risk of panic. Also, we need to close the channel only when everything is dequeued (so that we dont miss sending any metric).

In this case (since this is a single run CLI command), we don't actually need to worry about closing the channel. The process will anyway exit soon after the upload is done.
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump_upload.go` line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7Y89ID5Fk1JQi8poeF:-O7YUCINEO_1MvbBjufD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L326)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

The EOF check done below needs to be moved back here. That is the condition that will break this loop. Right now, the loop is running infinitely. That's probably why the `defer close(ch)` has not caused a problem :)
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump_upload.go` line 337 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VfchV3MA92rCEUESz:-O7YUGZx9Sqsluq6MWd3:b-4qnh2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L337)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

If all you're doing is immediately consuming all the messages on `ch` in this infinite loop, there's no need for the channel at all. You can replace this with a call to `decodeOne()`.

I think what you might want to do instead is to fire off N concurrent workers in a loop and then have each of those consume concurrently from the channel. Use a waitGroup to wait for all items on the channel to be processed.

I'm surprised we don't get rate limited using the current approach.
</blockquote></details>

DONE. It's a public API so I don't think datadog has any rate limit restrictions per source.
___
*[`pkg/cli/tsdump_upload.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7YEZ3K2_j18XrfAiQo:-O7YUXBzE9nmhNs7O-jw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L339)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Looking at the implementation of decode, it looks like there will either be data or error. Never both.
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump_upload.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7VcaLuCWHRc374YHuG:-O7YUZhN1_5QpL0ZvtcB:bn3h27w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L351)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: this comment doesn't make sense here.
</blockquote></details>

My bad! this was carry forwarded from previous implementation.

**Review by arjunmahishi — COMMENTED** [review]
Will take one last look at the full code in the morning. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-:-O7ZbjKu8-k2wcg_AoLL:boy4rl5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @dhartunian)

___
*[`pkg/cli/tsdump_upload.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7YEZ3K2_j18XrfAiQo:-O7ZbRv2-mDxUATV4HbH:bv9ntnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L339)):*
<details><summary><i>Previously, aa-joshi (Akshay Joshi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we should move this check above to avoid adding an empty `data` to the channel and also avoid an extra `wg.Add(1)`.

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arjunmahishi and @dhartunian)

___
*[`pkg/cli/tsdump_upload.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-O7YEZ3K2_j18XrfAiQo:-O7cIY184hxBkSR1_M44:bb6tyiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4612d85f3b8fa2a2267348b0991b6b804cad64de/pkg/cli/tsdump_upload.go#L339)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

I think we should move this check to avoid adding an empty `data` to the channel and also avoid an extra `wg.Add(1)`.
</blockquote></details>

DONE

**Review by arjunmahishi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131177#-:-O7ca7EL8p-yttonOuQf:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi and @dhartunian)

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Pull request merged**
