### PR TITLE
storage: move `Engine.ExportMVCCToSst` to `MVCCExportToSST`

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch moves the interface method `Engine.ExportMVCCToSst()` to a
function `MVCCExportToSST()`, since there was no reason for this to be
implemented on the engine interface.

This is mostly a mechanical reorganization, except minor tweaks to
function parameters and return values, as well as comments.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
Nice

:lgtm: 

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82811#-:-N4TTfEr-mtwbNdpP2Gf:b-293xf2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @nicktrav)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=jbowens

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
