### PR TITLE
sql, json, opt, util: refactor EncodeContainingInvertedIndexSpans to use SpanExpressions

### PR DESCRIPTION
**Pull request by rytaft**
**sql,json: change meaning of return param for `EncodeContainingInvertedIndexSpans`**

This commit subtly changes the meaning of the `unique` return parameter for
`EncodeContainingInvertedIndexSpans`. Previously, `unique` was always false if more
than one span slice was returned (indicating an `INTERSECTION` was required). Now
`unique` is true if every span slice returned is itself unique.

To match this behavior, when `SpanExpressions` are intersected (combined with
`And`), the resulting `SpanExpression` is unique if both its children are unique.
The union of `SpanExpression`s (combined with `Or`) is still not guaranteed to be
unique, however, even if its children are.

These changes are necessary in order to be able to use this infrastructure for
planning zigzag joins in a future commit.

Release note: None

**sql,opt,util: move `invertedexpr.SpanExpression` to `inverted`**

This refactor is necessary to remove the dependency on the `rowenc`
package, so that `rowenc` can use `SpanExpression`. A following commit
will update `rowenc` to use `inverted.SpanExpression`.

**sql,util: use `inverted.Expressions` when getting spans for `@>` expressions**

This commit converts `EncodeContainingInvertedIndexSpans` and functions it
calls to use `inverted.Expression`s instead of the prior set of three return
params (`spans`, `tight`, `unique`). All three of these params are now nicely
encapsulated in `inverted.Expression`, implemented by `inverted.SpanExpression`,
which more clearly documents the set expression nature of the return
parameter. This unifies the code across the optimizer and sql execution to
use the same data structure for representing inverted span expressions. It
also limits the number of conversions required and reduces the total amount
of code (as well as surface area for testing).

In addition to cleaning up the code in `EncodeContainingInvertedIndexSpans`,
this change also has the benefit of keeping track of which leaf-node span
expressions are unique, thus eliminating the need for a special code path for
zigzag joins.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSgazJ0ygKW8a_Zpj1:-MRSgazJ0ygKW8a_Zpj2:b-viqr7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/sql/opt/invertedexpr/expression.go#L365)):*
> ```Go
> 	// Unique is true if the spans are guaranteed not to produce duplicate
> 	// primary keys. Otherwise, Unique is false. Unique may be true for certain
> 	// JSON or Array SpanExpressions, and it holds when SpanExpressions are
> ```

... when unique SpannExpressions ...
___
*[pkg/util/inverted/span_expression.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSk5nnEJKbaRpj7WdZ:-MRSk5nnEJKbaRpj7Wd_:b4dd6hx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6067f265b5968f55f4ed790faf30fb240fa13a1/pkg/util/inverted/span_expression.go#L33)):*
> ```Go
> 
> // SpanExpression forms a set expression tree that represents unions and
> // intersections over spans read from an inverted index.
> ```

I am trying to understand how this relates to `invertedexpr.SpanExpression`. `JSONOrArrayToContainingSpanExpr` used to do the conversion from what was returned by `rowenc.EncodeContainingInvertedIndexSpans` into `invertedexpr.SpanExpression`. But now that what is returned is this `SpanExpression`, which can represent an arbitrary depth expression, things are starting to look similar (and this struct is not limited to two children). Can these be unified?
___
*[pkg/util/json/json.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSipJE0N6JdQUODtv0:-MRSipJE0N6JdQUODtv1:b-a7t65b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/util/json/json.go#L904)):*
> ```Go
> 	// false. We will return tight=false for the second case, which will
> 	// signal the need to filter out false positives.
> 	if !isRoot && j.Len() > 1 && len(spans) > 1 {
> ```

do we need both `j.Len() > 1` and `len(spans) > 1` in this expression -- isn't the latter sufficient?

**Review by rytaft — COMMENTED** [review]
Sorry to change things again... 3rd time's a charm, hopefully? I've added two more commits that unify the two different `SpanExpressions`, so that we use the same span expression for everything. There are some edge cases where this would mislabel a `SpanExpression` as not tight, but that only affects performance, not correctness. I think those cases are rare enough that it's worth it to unify everything. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MRfWT9j6hRJjajsiDWj:b-7oz02q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/expression.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSgazJ0ygKW8a_Zpj1:-MRfQVnn7eEmOb9Fb8Fe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/sql/opt/invertedexpr/expression.go#L365)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... when unique SpannExpressions ...
</blockquote></details>

Done.
___
*[pkg/util/inverted/span_expression.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSk5nnEJKbaRpj7WdZ:-MRfQ_T97zW_uen8LEqK:b7gkluc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6067f265b5968f55f4ed790faf30fb240fa13a1/pkg/util/inverted/span_expression.go#L33)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am trying to understand how this relates to `invertedexpr.SpanExpression`. `JSONOrArrayToContainingSpanExpr` used to do the conversion from what was returned by `rowenc.EncodeContainingInvertedIndexSpans` into `invertedexpr.SpanExpression`. But now that what is returned is this `SpanExpression`, which can represent an arbitrary depth expression, things are starting to look similar (and this struct is not limited to two children). Can these be unified?
</blockquote></details>

Yes, you're right. I thought it wouldn't be possible due to package dependencies and ergonomics of using the `invertedexpr.SpanExpression` in `rowenc.EncodeContainingInvertedIndexSpans` and related code, but I found a way to make it work in the last two commits. 
___
*[pkg/util/json/json.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSipJE0N6JdQUODtv0:-MRfR-mY7Jm81G0fWsVE:bdev6pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/util/json/json.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we need both `j.Len() > 1` and `len(spans) > 1` in this expression -- isn't the latter sufficient?
</blockquote></details>

You're right, we don't need both. But I've left it in now that I've changed to using the original `SpanExpression`, since there's no way to tell if the intersection was passed through from a child. Added a comment to explain.

**Comment by rytaft** [comment]
(If these commits look good, I'll squash them with the previous commits to remove all traces of the alternative `SpanExpression`).

**Review by mgartner — APPROVED** [review]
:lgtm: Very nice. I reviewed the commits wholesale and it all looks great. I appreciate the unification of inverted expressions.

> Reviewed 1 of 8 files at r1, 11 of 11 files at r3, 3 of 16 files at r4, 4 of 10 files at r5, 40 of 52 files at r6, 20 of 20 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MRukiF01-T7d7bF8uAE:b2a2ojv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/xform/select_funcs.go, line 1293 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRueLQLEkUzDDKZeWIm:-MRueLQLEkUzDDKZeWIn:btm1fsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1293)):*
> ```Go
> 		// are guaranteed not to produce duplicate primary keys.
> 		spanExpr, _, _, _, ok := invertedidx.TryFilterInvertedIndex(
> 			c.e.evalCtx, c.e.f, filters, nil /* optionalFilters */, scanPrivate.Table, index,
> ```

Can you add something like : `TODO(mgartner): Once we support multi-column inverted indexes, pass optional filters generated from CHECK constraints and computed column expressions to help constrain non-inverted prefix columns`
___
*[pkg/sql/opt/xform/select_funcs.go, line 1307 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuevtWAHzMxesGvwdN:-MRuevtWAHzMxesGvwdO:b4u2u5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1307)):*
> ```Go
> 				// exploring further.
> 				// TODO(rytaft): use stats here to choose the two most selective
> 				//  constraints instead of the first two.
> ```

[nit] remove extra space after `//`
___
*[pkg/sql/opt/xform/select_funcs.go, line 1310 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRug7i80wB_pURhKtLV:-MRug7i80wB_pURhKtLW:bjostnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1310)):*
> ```Go
> 				return
> 			}
> 			spanExprLocal, ok := invertedExpr.(*inverted.SpanExpression)
> ```

[nit] it wasn't immediately clear to me when `invertedExpr` would _not_ be an `inverted.SpanExpression`. might be worth adding a note about how it can either be `nil` or a `NonInvertedColExpression`. (I think it can be `nil`, but not sure.)
___
*[pkg/sql/opt/xform/select_funcs.go, line 1327 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRugYIg7i-fAHJaQQ8X:-MRugYIg7i-fAHJaQQ8Y:bfgk05n) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1327)):*
> ```Go
> 			// Check that this span expression represents a single-key span that is
> 			// guaranteed not to produce duplicate primary keys.
> 			if spanExpr.Unique && len(spanExprLocal.SpansToRead) == 1 &&
> ```

So if `spanExpr.Unique` is false, we'll never append to vals. Should we add `if !spanExpr.Unique { return }` before defining and calling `getVals` to prevent unnecessarily searching the expression tree?
___
*[pkg/util/inverted/expression.go, line 11 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuiycb7OsIXLhJMD-t:-MRuiycb7OsIXLhJMD-u:b-yx0jfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package inverted
> ```

`pkg/sql/inverted` might be a better home for this package. `pkg/util` seems a bit generic for logic that seems to fit under the SQL umbrella.

**Comment by mgartner** [comment]
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 589 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRumY2d5x1l9mLvLzb4:-MRumY2e1ZsZj5gzE1E7:b-j018ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/rowexec/zigzagjoiner.go#L589)):*
> ```Go
> 
> 	// First encode datums for any non-inverted prefix columns.
> 	keyPrefix, err := rowenc.EncodeInvertedIndexPrefixKeys(
> ```

So in theory, the zigzagjoiner now supports multi-column indexes. I guess there's no way to test this in logictests until the optimizer plans them, though?

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Great to see all this refactoring and cleanup!

I worry about the quality of my reviewing on a PR of this size.
Is it possible to separate the zigzag join change into a followup PR?

> Reviewed 3 of 11 files at r3, 3 of 16 files at r4, 1 of 10 files at r5, 33 of 52 files at r6, 15 of 20 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MRvQHRcAkOepWjM15t5:blu6hps)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 884 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvO6WL28-dEhgUpGlg:-MRvO6WL28-dEhgUpGlh:b-8sq8wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/memo/testdata/stats/select#L884)):*
> ```
>  │    ├── columns: a:1(int!null)
>  │    ├── eq columns: [1] = [1]
>  │    ├── left fixed columns: [6] = ['\x3761000112620001']
> ```

what happened here?
___
*[pkg/util/inverted/expression.go, line 98 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvGiN_48ivli3GJ1M2:-MRvGiN_48ivli3GJ1M3:b-ive3lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L98)):*
> ```Go
> // TODO(sumeer): work out how this will change when we have partitioned
> // inverted indexes, where some columns of the primary key will appear before
> // the inverted column.
> ```

nits:
- this TODO can be removed
- is it possible to get it back to showing the diff from the original file that was moved here, so I can review only the changes?
___
*[pkg/util/inverted/expression.go, line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvK1682_EGr6GCxXsb:-MRvK169Cmkgw5a7ZSgd:b-l5hwi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L739)):*
> ```Go
> 	// Both left and right are non-empty.
> 
> 	// The output spans.
> ```

is the code that used to be in `unique.go` and is gone now, because we were already doing the merging and de-duplication in this file (e.g. `tryPruneChildren`)?

Also, I am unclear on whether we are still requiring callers who generate the initial `SpanExpressions` to put sorted spans in `FactoredUnionSpans` and `SpansToRead`. The code in `geo_expression.go` does that for the geo path, but we've had bugs in that area in the past. I wonder whether we should do some invariant checking here when running tests.
___
*[pkg/util/json/json.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSipJE0N6JdQUODtv0:-MRvIWKC2W9gqk-KXwyH:btr9hrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/util/json/json.go#L904)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You're right, we don't need both. But I've left it in now that I've changed to using the original `SpanExpression`, since there's no way to tell if the intersection was passed through from a child. Added a comment to explain.
</blockquote></details>

And the factoring out into the union spans, performed by And, doesn't add any issues here, yes?

**Review by rytaft — COMMENTED** [review]
TFTRs! I've now rebased and squashed a couple of the commits so that there is no trace of the alternative `SpanExpression` I had created.
- The first commit is unchanged. 
- The second commit now contains the mechanical move of `SpanExpression` to `util/inverted`, with some renames.
- The third commit contains the changes to use `SpanExpression` in `rowenc`.

> Is it possible to separate the zigzag join change into a followup PR?

Done. #59485.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MS3tj7c-8uZhesyotmu:b-g9sk1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 884 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvO6WL28-dEhgUpGlg:-MRzm-5KBNRpYq9OaNfC:b536ond) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/memo/testdata/stats/select#L884)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what happened here?
</blockquote></details>

The column ID now corresponds to the inverted column with type bytes, and the encoded bytes are on the right side. Or was your question about something else?
___
*[pkg/sql/opt/xform/select_funcs.go, line 1293 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRueLQLEkUzDDKZeWIm:-MRzmrUkDR426kdoN4Zq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1293)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add something like : `TODO(mgartner): Once we support multi-column inverted indexes, pass optional filters generated from CHECK constraints and computed column expressions to help constrain non-inverted prefix columns`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1307 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuevtWAHzMxesGvwdN:-MRzmu9pEVmtRX2LhSPI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1307)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] remove extra space after `//`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1310 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRug7i80wB_pURhKtLV:-MRzmyZu6fpNwLYDfaer:boyfipa) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1310)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] it wasn't immediately clear to me when `invertedExpr` would _not_ be an `inverted.SpanExpression`. might be worth adding a note about how it can either be `nil` or a `NonInvertedColExpression`. (I think it can be `nil`, but not sure.)
</blockquote></details>

It shouldn't be nil (unless there's a bug). Added a comment.
___
*[pkg/sql/opt/xform/select_funcs.go, line 1327 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRugYIg7i-fAHJaQQ8X:-MRzpaY0C-GHssYWk-oj:bevxqi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/opt/xform/select_funcs.go#L1327)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So if `spanExpr.Unique` is false, we'll never append to vals. Should we add `if !spanExpr.Unique { return }` before defining and calling `getVals` to prevent unnecessarily searching the expression tree?
</blockquote></details>

Oops it actually should have been `spanExprLocal`. Fixed and added a test where this is relevant.
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 589 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRumY2d5x1l9mLvLzb4:-MRzrc8C3LN8xsoICe5V:b1s13x) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/sql/rowexec/zigzagjoiner.go#L589)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So in theory, the zigzagjoiner now supports multi-column indexes. I guess there's no way to test this in logictests until the optimizer plans them, though?
</blockquote></details>

Yea, let's hold off on those tests until we can plan them.
___
*[pkg/util/inverted/expression.go, line 11 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuiycb7OsIXLhJMD-t:-MRzronTDRvyUUDAn-IB:b88494p) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`pkg/sql/inverted` might be a better home for this package. `pkg/util` seems a bit generic for logic that seems to fit under the SQL umbrella.
</blockquote></details>

I put it here since the JSON stuff is in the `util` package. But I don't feel that strongly, if you think it would be much better in `sql`.
___
*[pkg/util/inverted/expression.go, line 98 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvGiN_48ivli3GJ1M2:-MRzs7zWDQBUBLMipn1V:bmzn3qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L98)):*
> this TODO can be removed

Done.

> is it possible to get it back to showing the diff from the original file that was moved here, so I can review only the changes?

I had to change some of the names because the linter was complaining about "stuttering", but otherwise the second commit should be just the move. The third commit is just changes on top of the moved file with some shortened names.
___
*[pkg/util/inverted/expression.go, line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvK1682_EGr6GCxXsb:-MRztLmi9tZyf-dsx3Vf:br6ovg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L739)):*
> is the code that used to be in unique.go and is gone now, because we were already doing the merging and de-duplication in this file (e.g. tryPruneChildren)?

Yes, that's right

> Also, I am unclear on whether we are still requiring callers who generate the initial SpanExpressions to put sorted spans in FactoredUnionSpans and SpansToRead. The code in geo_expression.go does that for the geo path, but we've had bugs in that area in the past. I wonder whether we should do some invariant checking here when running tests.

All of the code that I added in `index_encoding.go` and `json.go` never adds to `FactoredUnionSpans` and `SpansToRead` directly. It always builds them up using the `And` and `Or` functions combined with `ExprForSpan`.

Either way, invariant checking is a good idea. We could use the `crdb_test` build tag similar to what @mgartner did in #57845.  But I'd rather save that for another PR if you don't mind.
___
*[pkg/util/json/json.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSipJE0N6JdQUODtv0:-MRzwha-CUw238m5HuIo:b-d5vz8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/util/json/json.go#L904)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

And the factoring out into the union spans, performed by And, doesn't add any issues here, yes?
</blockquote></details>

I don't think it should. It would only eliminate the `SetIntersection` if there was a duplicate span, which is what `SortAndUniquifySpanSets` was doing before, and that's the behavior that we want from the `And` function.

There's a chance we'd call `SetNotTight` when it's not strictly necessary, but I haven't found an example where that happens.  I don't think we would ever *not* call it when it *is* strictly necessary.

**Comment by mgartner** [comment]
___
*[pkg/util/inverted/expression.go, line 11 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuiycb7OsIXLhJMD-t:-MS5LRMq0WcEQ1TyAkL9:b397e37) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L11)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I put it here since the JSON stuff is in the `util` package. But I don't feel that strongly, if you think it would be much better in `sql`.
</blockquote></details>

Hmm. I don't know the justification for the `json` package being in `pkg/util` when it's the implementation of our internal, SQL JSON type, not a general JSON library. Something irks me about placing fairly specific code into `pkg/util`. In my mind `util` is for general libraries that can be used throughout the codebase, like logging, metrics, tree printing.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 67 files at r8, 3 of 64 files at r11, 4 of 53 files at r12, 6 of 18 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MS5mfh0EPKoJz6mQU6V:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/util/inverted/expression.go, line 739 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRvK1682_EGr6GCxXsb:-MS5ltq0-KzRJmwIZZWq:ba2r6v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L739)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> is the code that used to be in unique.go and is gone now, because we were already doing the merging and de-duplication in this file (e.g. tryPruneChildren)?

Yes, that's right

> Also, I am unclear on whether we are still requiring callers who generate the initial SpanExpressions to put sorted spans in FactoredUnionSpans and SpansToRead. The code in geo_expression.go does that for the geo path, but we've had bugs in that area in the past. I wonder whether we should do some invariant checking here when running tests.

All of the code that I added in `index_encoding.go` and `json.go` never adds to `FactoredUnionSpans` and `SpansToRead` directly. It always builds them up using the `And` and `Or` functions combined with `ExprForSpan`.

Either way, invariant checking is a good idea. We could use the `crdb_test` build tag similar to what @mgartner did in #57845.  But I'd rather save that for another PR if you don't mind.

</blockquote></details>

Later PR is fine.
___
*[pkg/util/json/json.go, line 904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRSipJE0N6JdQUODtv0:-MS5m_Iz1lgyaSRjDUxV:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be7beadac0838387671d19900309c2c10513277/pkg/util/json/json.go#L904)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think it should. It would only eliminate the `SetIntersection` if there was a duplicate span, which is what `SortAndUniquifySpanSets` was doing before, and that's the behavior that we want from the `And` function.

There's a chance we'd call `SetNotTight` when it's not strictly necessary, but I haven't found an example where that happens.  I don't think we would ever *not* call it when it *is* strictly necessary.
</blockquote></details>

Ack

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-:-MS68vdm8iNO1riyxXpT:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/util/inverted/expression.go, line 11 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59074#-MRuiycb7OsIXLhJMD-t:-MS5gJpk4-RZRQWStcUz:b-7axnf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/de46623c0d656944c70b1fd1df7a4d23c952d7e2/pkg/util/inverted/expression.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm. I don't know the justification for the `json` package being in `pkg/util` when it's the implementation of our internal, SQL JSON type, not a general JSON library. Something irks me about placing fairly specific code into `pkg/util`. In my mind `util` is for general libraries that can be used throughout the codebase, like logging, metrics, tree printing. 
</blockquote></details>

Fair enough -- moved to `sql/inverted`.

**Pull request merged**
