### PR TITLE
sql/schemachanger/rel: rework indexes and values

### PR DESCRIPTION
**Pull request by ajwerner**
This change is a major reworking of the rel library. It does two things:

1) It makes indexes partial leading to much smaller data structures
2) It inlines values to avoid so many cache misses during comparisons

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
This is close but not quite quite ready to go. The benchmark results are satisfying using the benchmark from https://github.com/cockroachdb/cockroach/pull/80275.

**Comment by ajwerner** [comment]
```
name                                                              old time/op    new time/op    delta
DropLargeDatabase/tables=3,columns=2,depth=2,declarative=true-16     211ms ± 3%     140ms ±16%  -33.50%  (p=0.001 n=7+7)
DropLargeDatabase/tables=3,columns=4,depth=2,declarative=true-16     371ms ±19%     189ms ± 6%  -49.11%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=2,depth=3,declarative=true-16     681ms ±35%     276ms ± 3%  -59.49%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=4,depth=3,declarative=true-16     1.03s ± 5%     0.45s ± 3%  -56.77%  (p=0.001 n=7+7)
DropLargeDatabase/tables=3,columns=2,depth=4,declarative=true-16     1.64s ±12%     0.69s ± 2%  -58.23%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=4,depth=4,declarative=true-16     3.34s ± 8%     1.42s ±12%  -57.52%  (p=0.001 n=7+7)
DropLargeDatabase/tables=3,columns=2,depth=5,declarative=true-16     4.79s ± 5%     2.04s ± 4%  -57.42%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=4,depth=5,declarative=true-16     10.0s ± 2%      4.4s ± 1%  -56.51%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=2,depth=2,declarative=true-16     386ms ± 2%     226ms ±16%  -41.57%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=4,depth=2,declarative=true-16     693ms ± 2%     424ms ±24%  -38.89%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=2,depth=3,declarative=true-16     1.41s ± 6%     0.68s ± 5%  -51.78%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=4,depth=3,declarative=true-16     2.83s ± 1%     1.26s ± 5%  -55.54%  (p=0.001 n=6+7)
DropLargeDatabase/tables=4,columns=2,depth=4,declarative=true-16     6.10s ± 2%     2.65s ± 6%  -56.51%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=4,declarative=true-16     12.9s ± 1%      5.5s ± 2%  -57.05%  (p=0.001 n=6+7)
DropLargeDatabase/tables=4,columns=2,depth=5,declarative=true-16     27.9s ± 6%     11.9s ± 3%  -57.53%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=5,declarative=true-16     62.1s ± 6%     26.3s ± 1%  -57.72%  (p=0.001 n=7+6)

name                                                              old alloc/op   new alloc/op   delta
DropLargeDatabase/tables=3,columns=2,depth=2,declarative=true-16    35.6MB ± 1%    33.4MB ± 1%   -6.26%  (p=0.001 n=7+7)
DropLargeDatabase/tables=3,columns=4,depth=2,declarative=true-16    55.9MB ± 1%    52.6MB ± 0%   -5.85%  (p=0.001 n=7+7)
DropLargeDatabase/tables=3,columns=2,depth=3,declarative=true-16    77.1MB ± 0%    72.2MB ± 0%   -6.38%  (p=0.001 n=6+7)
DropLargeDatabase/tables=3,columns=4,depth=3,declarative=true-16     144MB ± 0%     132MB ± 0%   -8.12%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=2,depth=4,declarative=true-16     219MB ± 0%     205MB ± 0%   -6.53%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=4,depth=4,declarative=true-16     541MB ± 0%     408MB ± 0%  -24.58%  (p=0.004 n=5+6)
DropLargeDatabase/tables=3,columns=2,depth=5,declarative=true-16     679MB ± 0%     621MB ± 0%   -8.61%  (p=0.001 n=6+7)
DropLargeDatabase/tables=3,columns=4,depth=5,declarative=true-16    1.68GB ± 0%    1.33GB ± 0%  -20.68%  (p=0.004 n=6+5)
DropLargeDatabase/tables=4,columns=2,depth=2,declarative=true-16    62.0MB ± 1%    58.3MB ± 0%   -5.89%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=4,depth=2,declarative=true-16     108MB ± 0%     103MB ± 1%   -4.98%  (p=0.002 n=6+6)
DropLargeDatabase/tables=4,columns=2,depth=3,declarative=true-16     212MB ± 0%     200MB ± 0%   -5.67%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=4,depth=3,declarative=true-16     387MB ± 0%     369MB ± 0%   -4.74%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=2,depth=4,declarative=true-16     887MB ± 0%     817MB ± 0%   -7.82%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=4,declarative=true-16    2.21GB ± 0%    1.73GB ± 0%  -21.56%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=2,depth=5,declarative=true-16    4.77GB ± 1%    4.60GB ± 0%   -3.52%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=5,declarative=true-16    9.77GB ± 1%    9.38GB ± 2%   -4.05%  (p=0.001 n=7+7)

name                                                              old allocs/op  new allocs/op  delta
DropLargeDatabase/tables=3,columns=2,depth=2,declarative=true-16      277k ± 0%      228k ± 0%  -17.82%  (p=0.002 n=6+6)
DropLargeDatabase/tables=3,columns=4,depth=2,declarative=true-16      441k ± 0%      353k ± 0%  -19.96%  (p=0.003 n=5+7)
DropLargeDatabase/tables=3,columns=2,depth=3,declarative=true-16      637k ± 0%      506k ± 0%  -20.59%  (p=0.004 n=6+5)
DropLargeDatabase/tables=3,columns=4,depth=3,declarative=true-16     1.16M ± 0%     0.89M ± 0%  -23.20%  (p=0.002 n=6+6)
DropLargeDatabase/tables=3,columns=2,depth=4,declarative=true-16     1.70M ± 0%     1.31M ± 0%  -23.08%  (p=0.001 n=7+6)
DropLargeDatabase/tables=3,columns=4,depth=4,declarative=true-16     3.51M ± 0%     2.50M ± 0%  -28.80%  (p=0.002 n=6+6)
DropLargeDatabase/tables=3,columns=2,depth=5,declarative=true-16     4.95M ± 0%     3.70M ± 0%  -25.32%  (p=0.001 n=6+7)
DropLargeDatabase/tables=3,columns=4,depth=5,declarative=true-16     10.2M ± 0%      7.5M ± 0%  -27.20%  (p=0.002 n=6+6)
DropLargeDatabase/tables=4,columns=2,depth=2,declarative=true-16      489k ± 0%      393k ± 0%  -19.66%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=2,declarative=true-16      843k ± 0%      664k ± 0%  -21.27%  (p=0.002 n=6+6)
DropLargeDatabase/tables=4,columns=2,depth=3,declarative=true-16     1.61M ± 0%     1.24M ± 0%  -22.88%  (p=0.001 n=7+6)
DropLargeDatabase/tables=4,columns=4,depth=3,declarative=true-16     3.05M ± 0%     2.36M ± 0%  -22.68%  (p=0.003 n=7+5)
DropLargeDatabase/tables=4,columns=2,depth=4,declarative=true-16     6.13M ± 0%     4.58M ± 0%  -25.28%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=4,declarative=true-16     12.8M ± 0%      9.3M ± 0%  -27.42%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=2,depth=5,declarative=true-16     25.3M ± 0%     19.8M ± 0%  -21.87%  (p=0.001 n=7+7)
DropLargeDatabase/tables=4,columns=4,depth=5,declarative=true-16     50.5M ± 0%     39.4M ± 1%  -21.95%  (p=0.001 n=6+7)
```

On https://github.com/cockroachdb/cockroach/pull/80275

**Review by fqazi — APPROVED** [review]
:LGTM:

Great work! Very minor nitty comments

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-:-N19feTr0j7hHXpEYs9B:b-xjm8zt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/schemachanger/rel/query_data.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19gs7pB-yOzExTAfZu:-N19gs7pB-yOzExTAfZv:b3dvbwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/query_data.go#L48)):*
> ```Go
> 	typ       reflect.Type
> 	value     interface{}
> 	inline    uintptr
> ```

Nit: Might be worth documenting the types of values that will be inlined here.
___
*[`pkg/sql/schemachanger/rel/schema.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19hUTKCvX-8KCP1a3O:-N19hUTKCvX-8KCP1a3P:b4sctgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/schema.go#L301)):*
> ```Go
> 		case f.isStruct():
> 			f.inline = func(u unsafe.Pointer) (uintptr, bool) {
> 				return 0, false
> ```

Combine this with isString and fallthrough?
___
*[`pkg/sql/schemachanger/rel/values.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19j8vtBigfLqhOU83x:-N19j8vtBigfLqhOU83y:bvefc5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/values.go#L21)):*
> ```Go
> // Schemas with entities which have more than this many attributes will need to
> // increase this number.
> const numAttrs = 8
> ```

Any danger of missing runtime errors for this stuff?

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-:-N1EqIaUE6FQG54_0dWU:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/rel/query_data.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19gs7pB-yOzExTAfZu:-N1EqG_N-eTQNFcQFLMz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/query_data.go#L48)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Might be worth documenting the types of values that will be inlined here.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/schema.go` line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19hUTKCvX-8KCP1a3O:-N1A3KQR0bUHg9p51Jkf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/schema.go#L301)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Combine this with isString and fallthrough?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/rel/values.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-N19j8vtBigfLqhOU83x:-N1A4dKb29vIEdIsB6VL:b-1fhzp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/88ed3caec5966fb42d61cb4ce1a113d3e4dc3fd1/pkg/sql/schemachanger/rel/values.go#L21)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Any danger of missing runtime errors for this stuff?
</blockquote></details>

Nice catch. Added a check and a test that we disallow this problem in the schema.

**Review by ajwerner — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80276#-:-N1F89CH4YqCO8VOESV4:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

**Pull request merged**
