### PR TITLE
pkg/obsservice: reintroduce migrations, add `--no-db` flag, flag cleanup

### PR DESCRIPTION
**Pull request by abarganier**
Originally, the obsservice was equipped to run DB migrations
 against the `--sink-pgurl` provided at startup. However, during
 prototyping we temporarily disabled this functionality to reduce the
 number of things we needed to care about while we were getting things up
 and running initially.

 We're now at a point where we're ready to reintroduce the migrations
 framework. This patch reintroduces it, with some extra goodies:

 1. A new CLI flag, `--no-db`, which disables the migrations / DB
    connection at startup. This is for testing purposes where it's many
    times inconvenient to have to connect to a sink DB.
 2. Dockerfile updates, adding env vars for `--sink-pgurl` and `--no-db`
    so that they're configurable at the container level.
 3. Some README updates/cleanup.

 An example `docker run` to get an obsservice container connected to the
 provided `--sink-pgurl` is:
 ```
 docker run \
     --platform=linux/amd64 \
     -v "$(pwd)"/root.crt:/tmp/root.crt \
     -e SINK_PGURL="postgresql://user@host:26257?sslmode=verify-full&sslrootcert=/tmp/root.crt" \
     obsservice:latest
 ```

 Note that we had to mount the root certificate, and point to it in the
 SINK_PGURL with the `sslrootcert` query param.

 With this in place, we are ready to create new migrations.

 Release note: none

Epic: CC-25978

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114834)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/cmd/obsservice/Dockerfile` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-NjnOy3s1N5LZW2cDiYT:-NjnOy3s1N5LZW2cDiYU:b-3t6784) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb38fa08c5a47bf652d0832dadde0c474e86393/pkg/obsservice/cmd/obsservice/Dockerfile#L12)):*
> ```Dockerfile
> ENV OTLP_ADDR=0.0.0.0:4317
> ENV HTTP_ADDR=0.0.0.0:8081
> ENV SINK_PGURL="postgresql://root@0.0.0.0:26257?sslmode=disable"
> ```

is ssl mode disabled only now for testing or will it always be disabled?
___
*[`pkg/obsservice/obslib/migrations/migrations.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-NjnPovsBZf4Hf3U5CqS:-NjnPovsBZf4Hf3U5CqT:btjyge3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb38fa08c5a47bf652d0832dadde0c474e86393/pkg/obsservice/obslib/migrations/migrations.go#L40)):*
> ```Go
> 		return errors.AssertionFailedf("expected database name to be set")
> 	}
> 	log.Info(ctx, "Attempting to open a DB connection")
> ```

was this added just for development or you intend to keep it?
otherwise you might wanna keep consistent and only add an error message for the case where you can't connect

**Review by abarganier — COMMENTED** [review]
TFTR! PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-:-NjrnEEc--cWWNYbB7nM:b-qozhfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/obsservice/cmd/obsservice/Dockerfile` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-NjnOy3s1N5LZW2cDiYT:-NjrkuJX184_foUnuBMg:b-8gt6k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb38fa08c5a47bf652d0832dadde0c474e86393/pkg/obsservice/cmd/obsservice/Dockerfile#L12)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is ssl mode disabled only now for testing or will it always be disabled?
</blockquote></details>

This is just the default value if no sink PGURL is specified. In reality though, we'll be using SSL :slightly_smiling_face: 
___
*[`pkg/obsservice/obslib/migrations/migrations.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-NjnPovsBZf4Hf3U5CqS:-Njrl1GHABnQ5GSHY9hn:bzacf9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fb38fa08c5a47bf652d0832dadde0c474e86393/pkg/obsservice/obslib/migrations/migrations.go#L40)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

was this added just for development or you intend to keep it?
otherwise you might wanna keep consistent and only add an error message for the case where you can't connect
</blockquote></details>

Ah, yes thanks. I added some verbose logging for dev but I can remove since this is working reliably now.

**Review by maryliag — APPROVED** [review]
great!
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114834#-:-Njt5FT60r8PU4hELxtz:boxvjwd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by maryliag** [comment]
I will merge this, to use on my PR :) 

bors r+

**Pull request merged**
