### PR TITLE
storage: limit goroutine creation in gcQueue

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5373)

### CODE REVIEW

**Comment by bdarnell** [comment]
I initially planned to make `gcQueue` use the `intentResolver` for pushing transactions (it already does so for actually resolving intents), but the refactoring that would be necessary to make that possible would be substantial and I don't think it's worthwhile.

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9D_relGGu0ZtgGHrZ:1324907146) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
Is this a bug that you're fixing?

---

*[storage/gc_queue.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9DF7PSHt_V7Kp-BG5:-KD9DF7PSHt_V7Kp-BG6:299758946) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L459)):*
Do we really need to handle RunLimitedAsyncTask returning false?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9KHJuizMTx5_dqAuc:1694209398) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
there was no closure before, and now there is.

---

*[storage/gc_queue.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9DF7PSHt_V7Kp-BG5:-KD9KPfD4ub5HYirLYhG:1786007377) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L459)):*
What's the harm?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-:-KD9KTBXW9732WeGGlqX:1417088721)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9OGQCL8ddrNprDJA7:-735192153) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
that's pretty subtle. I didn't realize that a short variable declaration in a loop creates a new variable for each iteration of the loop

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9SkN8LsoClDyVkfar:-619865629) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
it doesn't create a new variable - it overwrites the same variable. that is why this copy is required

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9TzaXnL69MUxUIzSs:-986334694) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
What I'm saying is that each iteration has its own txnCopy, while txn behaves like it were declared outside of the loop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9WaQ2PDwjbT9qltFE:307628441) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
Yeah, it's subtle and it took me a while to figure out what was going on despite having run into this before (and either `go vet` wasn't catching this or my emacs integration is failing me). It's in the go FAQ: https://golang.org/doc/faq#closures_and_goroutines

---

*[storage/gc_queue.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9DF7PSHt_V7Kp-BG5:-KD9XMnmnQd4moalpIW6:1038764339) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L459)):*
We need to handle it in some way, either by returning from the function or calling `wg.Done`. I thought it would make more sense to bail out early rather than continue to resolve intents while we should be draining, and to avoid any possible assumptions that every transaction that could be pushed had been pushed. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by vivekmenezes** [comment]
LGTM

**Comment by tschottdorf** [comment]
:lgtm:. Sorry for the nasty rebase - I hope you can put the limited tasks in a wrapped `{resolve,push}Func` which is created before the call to `NewGC`. Btw, I'll be looking into making the sequence cache smaller - that's part of why this is exploding so badly.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KD9Zw6sNA5aLTxfF35Z:467317185) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
I've had my run-ins with this as well. Wish there were a lint.

---

*[storage/gc_queue.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9DF7PSHt_V7Kp-BG5:-KD9_WnMyN_pxsvxZisS:717499614) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L459)):*
I agree that this is sane behavior.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-:-KD9_iyms9xIr2dO6d94:-530359239)*

**Comment by bdarnell** [comment]
Reworked from scratch to rebase onto @tschottdorf 's change. Now that more of the work is done in static functions instead of methods, there's no good place to put a stopper so I'm just using a local semaphore channel at each of the two loops. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/gc_queue.go, line 449 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KD9D_relGGu0ZtgGHrY:-KDJMV_bhpj2Sd9Dm6-D:-1700453009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d4c958489537da5ce154cda6ed753a97177150/storage/gc_queue.go#L449)):*
`go vet` does check for this, but for some reason it wasn't showing up in emacs and I'm not in the habit of running `make check` while iterating on a change. (it's working for me now, though)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-:-KDJNEFyqBlMNEA8ECJo:1901512127)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/gc_queue.go, line 250 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDJRY5GFe6xAf-q1YoE:-KDJRY5GFe6xAf-q1YoF:975495265) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec01fbfd45afeea46533964a6850afc9b0e47be8/storage/gc_queue.go#L250)):*
since there's no stopper - remove this?

---

*[storage/gc_queue.go, line 266 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDJS9qi3hIDGd3ulE3i:-KDJS9qi3hIDGd3ulE3j:-389675677) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec01fbfd45afeea46533964a6850afc9b0e47be8/storage/gc_queue.go#L266)):*
if you went the other way and passed `sem` into `pushTxn`, you could avoid allocating a closure here and elsewhere.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-:-KDJSOsAelM860WHK5Tu:1417088721)*

**Comment by tschottdorf** [comment]
:lgtm: mod comments.

---

Reviewed 1 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 266 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDJS9qi3hIDGd3ulE3i:-KDLETntgscOv8Nb04IF:287015475) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec01fbfd45afeea46533964a6850afc9b0e47be8/storage/gc_queue.go#L266)):*
Was also going to suggest putting that in the closure. Could even use the stopper for it.

---

*[storage/gc_queue.go, line 257 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDLDwyh_aBXDCGiHVXy:-KDLDwyixnvlwNdBwV29:1833850756) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de6e7aebb0247163dd5974561de5dddbb2467d3/storage/gc_queue.go#L257)):*
same behaviour, but maybe

```go
go func(txn *roachpb.Transaction) {
  // ...
}(txn)
```

---

*[storage/gc_queue.go, line 331 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDLEtPr5F_hMWCMKcgL:-KDLEtPskngLZ6Ta8PF2:-1020528004) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de6e7aebb0247163dd5974561de5dddbb2467d3/storage/gc_queue.go#L331)):*
what if you used `repl.store.Stopper().RunLimitedTask(...)` here? Looks like you wouldn't need the manual sem.

---

*[storage/gc_queue.go, line 549 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDLG2TX0RCPIeqj7NA8:-KDLG2TYU8WhudC1fhm-:-1677837463) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de6e7aebb0247163dd5974561de5dddbb2467d3/storage/gc_queue.go#L549)):*
ditto.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-:-KDLG89i-VgcrvuI1YWm:-1927687667)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[storage/gc_queue.go, line 266 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDJS9qi3hIDGd3ulE3i:-KDOf1_LC5GSjUmuUhPK:65180555) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec01fbfd45afeea46533964a6850afc9b0e47be8/storage/gc_queue.go#L266)):*
There's no reason for `pushTxn` to know so much about how it's called; the semaphore and WaitGroup are the caller's concern. This could be abstracted away a little bit with a helper function but since it's only done twice I think it's more clear to just inline the logic. 

---

*[storage/gc_queue.go, line 257 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDLDwyh_aBXDCGiHVXy:-KDOeQNJws6IckfSHr0_:-1225516816) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de6e7aebb0247163dd5974561de5dddbb2467d3/storage/gc_queue.go#L257)):*
It's more common in our code to copy variables instead of adding arguments to the closure (because we rarely use bare goroutines and you can't pass arguments into `RunAsyncTask`)

---

*[storage/gc_queue.go, line 331 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373#-KDLEtPr5F_hMWCMKcgL:-KDObt4LGkPqTbpdg3AA:-221768067) ([raw file](https://github.com/cockroachdb/cockroach/blob/1de6e7aebb0247163dd5974561de5dddbb2467d3/storage/gc_queue.go#L331)):*
In the debug command you just added, there are no `Replica` objects. I could add an explicit `Stopper` argument to `RunGC` and associated methods but that seems a little heavy when all we really want is the semaphore, not the "stop" functionality.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5373)*

**Pull request merged**
