### PR TITLE
logictest: support mixed binary version tests with upgrades

### LINKED ISSUE #72451: sql: add directives to logictest for mixed version cluster tests
Currently we have limited support for testing mixed version cluster tests using logictests.

We have a config to support testing version gates via logic tests but not actually functionality.

```
	{
		name:                "local-mixed-21.1-21.2",
		numNodes:            1,
		overrideDistSQLMode: "off",
		overrideAutoStats:   "false",
		bootstrapVersion:    roachpb.Version{Major: 21, Minor: 1},
		binaryVersion:       roachpb.Version{Major: 21, Minor: 2},
		disableUpgrade:      true,
	},
```

Ensuring mixed version functionality actually works is very tedious as we currently have to make a roachtest for example:
https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go
The problem is creating a roachtest is not straightforward and takes a while to run.

Ideally we could support some logic test directives to make writing mixed version tests easier.

For example, we could specify which nodes are on which versions - then execute commands from a specified node.
We could improve on that by adding support for updating / rolling back nodes.

Ideally we could make testing mixed version clusters very easy.

Might be a good hackathon project.

Potentially support commands to upgrade / downgrade

Mentioned in https://github.com/cockroachdb/cockroach/issues/69361
```
new-cluster
should-error-with-version
should-succeed
upgrade-cluster
```

Jira issue: CRDB-11159

Epic CRDB-14557

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/72451

The logictest framework can now use the cockroach-go testserver to test a multi-node cluster in which each node is running a different binary version.

Previously, only mixed logical versions could be tested.

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 1236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5WEHj6f3Of7MLfNxH:-NH5WEHk4383Gjkz6Qwk:b-bnqqww) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L1236)):*
> ```Go
> }
> 
> func (t *logicTest) newTestServerCluster(bootstrapBinaryPath string, upgradeBinaryPath string) {
> ```

nit: maybe add a comment that "upgradeBinaryPath is set according to cfg.CockroachGoUpgradeVersion. If the latter is unset, upgradeBinaryPath is of the same value as  bootstrapBinaryPath"
___
*[`pkg/sql/logictest/logic.go` line 1251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH0_SzA869pGAScAX3U:-NH0_SzA869pGAScAX3V:b-i9ew4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L1251)):*
> ```Go
> 		testserver.StoreOnDiskOpt(),
> 		testserver.CockroachBinaryPathOpt(bootstrapBinaryPath),
> 		testserver.UpgradeCockroachBinaryPathOpt(upgradeBinaryPath),
> ```

This may be a bit random, but just curious if we would ever want a mix of 3 versions in a test?
___
*[`pkg/sql/logictest/logic.go` line 3018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5X3NbEJB0bzJtKrGe:-NH5X3NbEJB0bzJtKrGf:bppq80y) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3018)):*
> ```Go
> 				return errors.Errorf(`could not perform "upgrade", not a cockroach-go/testserver cluster`)
> 			}
> 			nodeNum, err := strconv.Atoi(fields[1])
> ```

nit: `nodeIdx` maybe better?
___
*[`pkg/sql/logictest/logic.go` line 3045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5ly_Y3sgDBTV5wp-U:-NH5ly_Y3sgDBTV5wp-V:b-wqem31) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3045)):*
> ```Go
> 			}
> 
> 			if err := t.testserverCluster.WaitForInitFinishForNode(nodeNum); err != nil {
> ```

Do we still need this WaitForInitFinishForNode? Look like it's doing the same thing as the for loop above.
___
*[`pkg/sql/logictest/logic.go` line 3871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH0c_rtD2zgUAsC1eIS:-NH0c_rtD2zgUAsC1eIT:b6nqt6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3871)):*
> ```Go
> 	// Ensure that all of the created descriptors can round-trip through json.
> 	{
> 		// If `useCockroachGoTestserver` is true and we do an upgrade,
> ```

Not requesting for changes, but wanted to know whether this check for descriptors in necessary for all tests? When using cockroach-go test server, will we want to wait till migrations finish then run this check? 
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5mf052BvZIFL8EIcf:-NH5mf052BvZIFL8EIcg:baesvfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node#L1)):*
> ```
> # LogicTest: cockroach-go-testserver-22.2-master
> ```

nit: Would this name be a bit confusing once the master moves forward to a later version? Would it be better if it's something like `testserver-22.2-single-version`?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/logictest/logic.go` line 1236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5WEHj6f3Of7MLfNxH:-NHQKiVSCxd4JOA1-CgN:bsmfq2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L1236)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: maybe add a comment that "upgradeBinaryPath is set according to cfg.CockroachGoUpgradeVersion. If the latter is unset, upgradeBinaryPath is of the same value as  bootstrapBinaryPath"
</blockquote></details>

done - with a small correction
___
*[`pkg/sql/logictest/logic.go` line 1251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH0_SzA869pGAScAX3U:-NHQh_RfEAKxAX1eveen:b-6dojwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L1251)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

This may be a bit random, but just curious if we would ever want a mix of 3 versions in a test?
</blockquote></details>

no, we shouldn't need that, since CRDB only supports upgrading from one version to the next
___
*[`pkg/sql/logictest/logic.go` line 3018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5X3NbEJB0bzJtKrGe:-NHQhjMv53kUZ7cO9-cY:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3018)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: `nodeIdx` maybe better?
</blockquote></details>

done
___
*[`pkg/sql/logictest/logic.go` line 3045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5ly_Y3sgDBTV5wp-U:-NHQiEgz9xj9OADvGS-D:bgzno6) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3045)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Do we still need this WaitForInitFinishForNode? Look like it's doing the same thing as the for loop above.
</blockquote></details>

yeah, i'll remove this one, nice catch
___
*[`pkg/sql/logictest/logic.go` line 3871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH0c_rtD2zgUAsC1eIS:-NHQiNrDCJvQQ6narZYb:b-qu9z5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/logic.go#L3871)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Not requesting for changes, but wanted to know whether this check for descriptors in necessary for all tests? When using cockroach-go test server, will we want to wait till migrations finish then run this check? 
</blockquote></details>

i don't think it's necessary for all tests - it's kind of like a defensive check, and doesn't seem worth it to make it work during version upgrades
___
*[`pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH5mf052BvZIFL8EIcf:-NHQioj59lEMc4eQMbCb:bepbcl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fcb6c58b1076a8cf36ba55318fed658a91b129/pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node#L1)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

nit: Would this name be a bit confusing once the master moves forward to a later version? Would it be better if it's something like `testserver-22.2-single-version`? 
</blockquote></details>

when master moves forward to a new version, this test should start failing, so then the test configs will be update or removed as needed

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/logic.go` line 3045 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH_e8QJ08XuubcxKHOh:-NH_e8QJ08XuubcxKHOi:bclfwuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/05480d09b1b495cbd02750361d2325029cac3b11/pkg/sql/logictest/logic.go#L3045)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			for i := 0; i < 3; i++ {
> ```

Hmm, so now with the ci green, seems that though we upgrade a single node (by killing the process and restart a new one), we still need to wait till **all** nodes in the cluster are ping-able. :thinking:

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/logictest/logic.go` line 3045 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH_e8QJ08XuubcxKHOh:-NH_jk5SBrLRZALkZnuP:buk55l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/05480d09b1b495cbd02750361d2325029cac3b11/pkg/sql/logictest/logic.go#L3045)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Hmm, so now with the ci green, seems that though we upgrade a single node (by killing the process and restart a new one), we still need to wait till **all** nodes in the cluster are ping-able. :thinking: 
</blockquote></details>

yeah, i wanted to experiment with this to see if that would fix it. i believe this is correct, since the testserver uses `Kill` when upgrading a node, which means that there could be temporary cluster unavailability (for example, if the leaseholder for the system database is killed)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/logictest/logic.go` line 3045 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH_e8QJ08XuubcxKHOh:-NH_kceYDqXiIdQRl11V:b-2tbhjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/05480d09b1b495cbd02750361d2325029cac3b11/pkg/sql/logictest/logic.go#L3045)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah, i wanted to experiment with this to see if that would fix it. i believe this is correct, since the testserver uses `Kill` when upgrading a node, which means that there could be temporary cluster unavailability (for example, if the leaseholder for the system database is killed)
</blockquote></details>

i've also made https://github.com/cockroachdb/cockroach-go/pull/154 so that this logic is part of the testserver

**Comment by ZhouXing19** [comment]
*[`pkg/sql/logictest/logic.go` line 1272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH_q890389J6THnXbfC:-NH_q890389J6THnXbfD:btj3gvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/05480d09b1b495cbd02750361d2325029cac3b11/pkg/sql/logictest/logic.go#L1272)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	testutils.SucceedsSoon(t.rootT, func() error {
> ```

Do we want to replace here with 
```go
for i := 0; i < 3; i ++ {
  if err := ts.WaitForInitFinishForNode(i); err != nil {
    return err
  }
}
```
as well?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[`pkg/sql/logictest/logic.go` line 1272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-NH_q890389J6THnXbfC:-NHa5aQT-w9xHWG9GciN:b-dt7lr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/05480d09b1b495cbd02750361d2325029cac3b11/pkg/sql/logictest/logic.go#L1272)):*
<details><summary><i>Previously, ZhouXing19 (Jane Xing) wrote…</i></summary><blockquote>

Do we want to replace here with 
```go
for i := 0; i < 3; i ++ {
  if err := ts.WaitForInitFinishForNode(i); err != nil {
    return err
  }
}
```
as well?
</blockquote></details>

i think this one is fine as-is, since during the initial startup there is no non-graceful killing

**Review by ZhouXing19 — COMMENTED** [review]
:lgtm_strong: !! Thanks for answering my questions

> Reviewed 5 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91881#-:-NHbnKnsDIaRDwkpBuhx:b-qmxnsa)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by ZhouXing19 — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=ZhouXing19

**Comment by rafiss** [comment]
bors r=ZhouXing19

**Pull request merged**
