### PR TITLE
rpc: reuse gRPC streams across unary BatchRequest RPCs

### LINKED ISSUE #136572: rpc: reuse gRPC streams across unary BatchRequest invocations
There could be a sizeable win here in light of the results in https://github.com/cockroachdb/cockroach/pull/136558.
We should prototype this approach, measure the improvement, and decide whether this is something we can do in production.
Epic: CRDB-42584

### PR DESCRIPTION
**Pull request by nvb**
Closes #136572.

This commit introduces pooling of gRPC streams that are used to send requests and receive corresponding responses in a manner that mimics unary RPC invocation. Pooling these streams allows for reuse of gRPC resources across calls, as opposed to native unary RPCs, which create a new stream and throw it away for each request (see grpc.invoke).

The new pooling mechanism is used for the Internal/Batch RPC method, which is the dominant RPC method used to communicate between the KV client and KV server. A new Internal/BatchStream RPC method is introduced to allow a client to send and receive BatchRequest/BatchResponse pairs over a long-lived, pooled stream. A pool of these streams is then maintained alongside each gRPC connection. The pool grows and shrinks dynamically based on demand.

The change demonstrates a large performance improvement in both microbenchmarks and full system benchmarks, which reveals just how expensive the gRPC stream setup on each unary RPC is.

### Microbenchmarks:
```
name                                            old time/op    new time/op    delta
Sysbench/KV/1node_remote/oltp_point_select-10     45.9µs ± 1%    28.8µs ± 2%  -37.31%  (p=0.000 n=9+8)
Sysbench/KV/1node_remote/oltp_read_only-10         958µs ± 6%     709µs ± 1%  -26.00%  (p=0.000 n=9+9)
Sysbench/SQL/1node_remote/oltp_read_only-10       3.65ms ± 6%    2.81ms ± 8%  -23.06%  (p=0.000 n=8+9)
Sysbench/KV/1node_remote/oltp_read_write-10       1.77ms ± 5%    1.38ms ± 1%  -22.09%  (p=0.000 n=10+8)
Sysbench/KV/1node_remote/oltp_write_only-10        688µs ± 4%     557µs ± 1%  -19.11%  (p=0.000 n=9+9)
Sysbench/SQL/1node_remote/oltp_point_select-10     181µs ± 8%     159µs ± 2%  -12.10%  (p=0.000 n=8+9)
Sysbench/SQL/1node_remote/oltp_write_only-10      2.16ms ± 4%    1.92ms ± 3%  -11.08%  (p=0.000 n=9+9)
Sysbench/SQL/1node_remote/oltp_read_write-10      5.89ms ± 2%    5.36ms ± 1%   -8.89%  (p=0.000 n=9+9)

name                                            old alloc/op   new alloc/op   delta
Sysbench/KV/1node_remote/oltp_point_select-10     16.3kB ± 0%     6.4kB ± 0%  -60.70%  (p=0.000 n=8+10)
Sysbench/KV/1node_remote/oltp_write_only-10        359kB ± 1%     256kB ± 1%  -28.92%  (p=0.000 n=10+10)
Sysbench/SQL/1node_remote/oltp_write_only-10       748kB ± 0%     548kB ± 1%  -26.78%  (p=0.000 n=8+10)
Sysbench/SQL/1node_remote/oltp_point_select-10    40.9kB ± 0%    30.8kB ± 0%  -24.74%  (p=0.000 n=9+10)
Sysbench/KV/1node_remote/oltp_read_write-10       1.11MB ± 1%    0.88MB ± 1%  -21.17%  (p=0.000 n=9+10)
Sysbench/SQL/1node_remote/oltp_read_write-10      2.00MB ± 0%    1.65MB ± 0%  -17.60%  (p=0.000 n=9+10)
Sysbench/KV/1node_remote/oltp_read_only-10         790kB ± 0%     655kB ± 0%  -17.11%  (p=0.000 n=9+9)
Sysbench/SQL/1node_remote/oltp_read_only-10       1.33MB ± 0%    1.19MB ± 0%  -10.97%  (p=0.000 n=10+9)

name                                            old allocs/op  new allocs/op  delta
Sysbench/KV/1node_remote/oltp_point_select-10        210 ± 0%        61 ± 0%  -70.95%  (p=0.000 n=10+10)
Sysbench/KV/1node_remote/oltp_read_only-10         3.98k ± 0%     1.88k ± 0%  -52.68%  (p=0.019 n=6+8)
Sysbench/KV/1node_remote/oltp_read_write-10        7.10k ± 0%     3.47k ± 0%  -51.07%  (p=0.000 n=10+9)
Sysbench/KV/1node_remote/oltp_write_only-10        3.10k ± 0%     1.58k ± 0%  -48.89%  (p=0.000 n=10+9)
Sysbench/SQL/1node_remote/oltp_write_only-10       6.73k ± 0%     3.82k ± 0%  -43.30%  (p=0.000 n=10+10)
Sysbench/SQL/1node_remote/oltp_read_write-10       14.4k ± 0%      9.2k ± 0%  -36.29%  (p=0.000 n=9+10)
Sysbench/SQL/1node_remote/oltp_point_select-10       429 ± 0%       277 ± 0%  -35.46%  (p=0.000 n=9+10)
Sysbench/SQL/1node_remote/oltp_read_only-10        7.52k ± 0%     5.37k ± 0%  -28.60%  (p=0.000 n=10+10)
```

### Roachtests:
```
name                                            old queries/s  new queries/s  delta
sysbench/oltp_read_write/nodes=3/cpu=8/conc=64     17.6k ± 7%     19.2k ± 2%  +9.22%  (p=0.008 n=5+5)

name                                            old avg_ms/op  new avg_ms/op  delta
sysbench/oltp_read_write/nodes=3/cpu=8/conc=64      72.9 ± 7%      66.6 ± 2%  -8.57%  (p=0.008 n=5+5)

name                                            old p95_ms/op  new p95_ms/op  delta
sysbench/oltp_read_write/nodes=3/cpu=8/conc=64       116 ± 8%       106 ± 3%  -9.02%  (p=0.016 n=5+5)
```

### Manual tests:
Running in a similar configuration to `sysbench/oltp_read_write/nodes=3/cpu=8/conc=64`, but with a benchmarking related cluster settings (before and after) to reduce variance.
```
-- Before
Mean: 19771.03
Median: 19714.22
Standard Deviation: 282.96
Coefficient of variance: .0143

-- After
Mean: 21908.23
Median: 21923.03
Standard Deviation: 200.88
Coefficient of variance: .0091
```

----

Release note (performance improvement): gRPC streams are now pooled across unary intra-cluster RPCs, allowing for reuse of gRPC resources to reduce the cost of remote key-value layer access. This pooling can be disabled using the `rpc.batch_stream_pool.enabled` cluster setting.

### CODE REVIEW

**Comment by tbg** [comment]
This looks great, thank you for putting that together so quickly.

**Comment by nvanbenschoten** [comment]
@tbg this should be good for a review, at your convenience. You should also be able to take this and extend it to work with dRPC, though it will need some changes if dRPC does not support multiple streams sharing a single TCP connection.

**Review by tbg — APPROVED** [review]
Looks great. A few small comments but :lgtm_strong:
Are there any roachtests we think might find new unexpected behavior? For example, anything that has to do with DistSQL circuit breaking or failover (`failover/*`?). Looking at the code I don't see what that something might be, so I'm not sure it's worth running them manually, especially since KV owns the `failover` tests anyway.

> Reviewed 1 of 1 files at r4, 22 of 22 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-:-ODeODWv3On7b8sEZUJZ:b2px94y)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @cthumuluru-crdb, @kyle-a-wong, and @nvanbenschoten)

___
*[`pkg/rpc/nodedialer/nodedialer.go` line 342 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeMOCt7nH1MiYqoU0C:-ODeMOCt7nH1MiYqoU0D:b-ckpgqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/nodedialer/nodedialer.go#L342)):*
> ```Go
> 		return client
> 	}
> 	return &BatchStreamPoolClient{InternalClient: client, pool: pool}
> ```

Curious if you think this deserves to be pooled. It's not a large allocation, but it is an allocation; at what point is the hassle of pooling it worth it? I think it should be easy to pool this one.
___
*[`pkg/rpc/stream_pool.go` line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeL0Kw00uBJynCk68o:-ODeL0Kx-HdACFdyrunV:b5qry4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/stream_pool.go#L220)):*
> ```Go
> 
> // Bind sets the gRPC connection and context for the streamPool. This must be
> // called before streamPool.Send.
> ```

// called once before streamPool.Send.



_Code quote:_
```Go
// called before streamPool.Send.
```
___
*[`pkg/rpc/stream_pool_test.go` line 290 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeNiOW7XGUQOwUx7Ck:-ODeNiOW7XGUQOwUx7Cl:bsfn53e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/stream_pool_test.go#L290)):*
> ```Go
> 	require.Nil(t, res.resp)
> 	require.Error(t, res.err)
> 	require.ErrorIs(t, res.err, context.Canceled)
> ```

And the stream should not be back in the pool, right?

**Review by tbg — APPROVED** [review]
One more thing: In the rel note, do you want to mention the cluster setting to turn off this feature?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-:-ODeOuJQDk5ORsXEmH4M:b5oyy1x)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @cthumuluru-crdb, @kyle-a-wong, and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
TFTR!

> Are there any roachtests we think might find new unexpected behavior? For example, anything that has to do with DistSQL circuit breaking or failover (`failover/*`?). Looking at the code I don't see what that something might be, so I'm not sure it's worth running them manually, especially since KV owns the `failover` tests anyway.

This is a good question. I'm not aware of any new failure modes with this, because we were already just laying unary RPCs over long-lived gRPC connections, which are the actual resource that can fail. I'll keep an eye on the `failover` tests over the next few weeks (which I've been doing anyway for leader leases).

> One more thing: In the rel note, do you want to mention the cluster setting to turn off this feature?

Done.

> The "rpc: make batch stream pool general over Conn" commit from [here](https://github.com/cockroachdb/cockroach/pull/136794/commits) might be something you could cherry-pick into your grpc stream pooling PR, btw. Especially if you're going to make any code changes in that PR I'd appreciate that.

(from Slack)

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-:-ODhl-LzCcm5N_xrHg9V:b1vqqck)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @cthumuluru-crdb, @kyle-a-wong, and @tbg)

___
*[`pkg/rpc/stream_pool.go` line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeL0Kw00uBJynCk68o:-ODhkUYI3Czcf9tuOZ3j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/stream_pool.go#L220)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

// called once before streamPool.Send.
</blockquote></details>

Done.
___
*[`pkg/rpc/nodedialer/nodedialer.go` line 342 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeMOCt7nH1MiYqoU0C:-ODhkVdREnUAfgJNNXO1:bxdimgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/nodedialer/nodedialer.go#L342)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Curious if you think this deserves to be pooled. It's not a large allocation, but it is an allocation; at what point is the hassle of pooling it worth it? I think it should be easy to pool this one.
</blockquote></details>

Done in a new commit using a similar approach to what @RaduBerinde suggested in #136941.

I'll let you give that commit a review before merging.
___
*[`pkg/rpc/stream_pool_test.go` line 290 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODeNiOW7XGUQOwUx7Ck:-ODhkaV70IkR9bApViBT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4596eb92a0fa24304e868318b389137d1a835254/pkg/rpc/stream_pool_test.go#L290)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

And the stream should not be back in the pool, right?
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
:lgtm: nice!

> Reviewed 6 of 6 files at r6, 2 of 2 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-:-ODkXjfp-JSgql4nd7EY:b-7yytuz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @cthumuluru-crdb, @kyle-a-wong, and @nvanbenschoten)

___
*[`-- commits` line 118 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136648#-ODkWtZ-ByORul6aGgf6:-ODkWtZ-ByORul6aGgf7:b-pjneff):*
nice that this shows up!

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=tbg

**Pull request merged**
