### PR TITLE
sql: include regions information into the sampled query telemetry

### LINKED ISSUE #85427: sql: collect log-based telemetry on regions visited by each query
**Is your feature request related to a problem? Please describe.**
Currently our log-based telemetry does not include the regions visited by a query. It would be helpful to know how many of our customers' queries are visiting multiple regions.

**Describe the solution you'd like**
The log-based telemetry should include all the regions visited by a query, similar to the region information currently output by `EXPLAIN ANALYZE`. Although the `EXPLAIN ANALYZE` output today doesn't technically include every region touched by the query (e.g., if the KV api fetches data from a remote region this will not be represented), it will give us a pretty good idea. In particular, it will include all the regions where DistSQL processors are planned.

**Describe alternatives you've considered**
It would be helpful to include regions visited by the KV api, but this would be a more invasive change.

Jira issue: CRDB-18243

### PR DESCRIPTION
**Pull request by yuzefovich**
**execstats: remove unused regions field**

This field was never actually populated nor used since it was introduced
in https://github.com/cockroachdb/cockroach/commit/9f716a7723f8ac081005f475f3fc6eee6444b1ae.

Release justification: low-risk cleanup.

Release note: None

**sql: include regions information into the sampled query telemetry**

This commit adds the regions (where SQL processors where planned for the
query) to the sampled query telemetry. This required a couple of minor
changes to derive the regions information stored in the instrumentation
helper earlier (before the logging takes place).

Fixes: #85427.

Release justification: low-risk improvement.

Release note (sql change): The structured payloads used for telemetry
logs now include the new `Regions` field which indicates the regions of
the nodes where SQL processing ran for the query.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Awesome thanks!

> Reviewed 3 of 3 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86829#-:-NAKMU2y0UXd-O5qHQ9-:b-2ak790)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86829)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @srosenberg, and @THardy98)

___
*[`docs/generated/eventlog.md` line 2607 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86829#-NALsZNoDNtbibH-rTX0:-NALsZNoDNtbibH-rTX1:bbw0w90) ([raw file](https://github.com/cockroachdb/cockroach/blob/68a7bf17ed82674aa57f16958de88be55ce32c82/docs/generated/eventlog.md#L2607)):*
> ```Markdown
> | `ZigZagJoinCount` | The number of zig zag joins in the query plan. | no |
> | `ContentionNanos` | The duration of time in nanoseconds that the query experienced contention. | no |
> | `Regions` | The regions of the nodes where SQL processors ran. | no |
> ```

I'm assuming that the regions information is not sensitive, does that sound right? cc @kevin-v-ngo

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by rytaft** [comment]
Can we backport this to 22.1?

**Comment by yuzefovich** [comment]
> Can we backport this to 22.1?

This would require pulling in some of the changes made in #84718 (in particular, we'd need to get the trace recording one more time, before logging the telemetry). Is the backport desirable?

**Comment by rytaft** [comment]
cc @vy-ton @kevin-v-ngo @awoods187 see @yuzefovich's question above. Not sure how important it is to get region telemetry from 22.1. (Otherwise this will just be included in 22.2)

**Comment by vy-ton** [comment]
If possible, I'd like to see this backported to 22.1.

**Pull request merged**
