### PR TITLE
sqlsmith: add bulk IO statements

### PR DESCRIPTION
**Pull request by thoszhang**
This PR is basically the same as #36306, but rebased.

----

3b104d4 sqlsmith: add BACKUP, RESTORE

Add BACKUP and RESTORE statements to sqlsmith. The backups are written to and
read from an in-memory HTTP file server.

Release note: None

----

c87b28f sqlsmith: add IMPORT, EXPORT

Add IMPORT and EXPORT statements to sqlsmith.

Release note: None

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Review by dt — APPROVED** [review]
🎉

**Comment by lucy-zhang** [comment]
Oh, I forgot to fix the linter issues.

bors r-

**Pull request merged**
