### PR TITLE
server, tenant: add tenantHotRanges api

### PR DESCRIPTION
**Pull request by koorosh**
This patch introduces TenantHotRanges API that allows to
request hot ranges for particular tenant.
TenantHotRanges api mostly duplicates initial `HotRanges` api
and is a subject of unification in future.

Release note: None

Depends on: #90097

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-19124

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/server/serverpb/status.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFEUwY923q5oD8DY44O:-NFEUwY923q5oD8DY44P:b-2s5u2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1438e090ba54a625c8275d9ce0f8dd90b9385047/pkg/server/serverpb/status.go#L85)):*
> ```Go
> type TenantStatusServer interface {
> 	TenantRanges(context.Context, *TenantRangesRequest) (*TenantRangesResponse, error)
> 	TenantHotRanges(context.Context, *TenantHotRangesRequest) (*TenantHotRangesResponse, error)
> ```

I'm not confident that it's a common way to access kv layer but it's straightforward.
@dhartunian , can you suggest if it okay to extend this interface or there's another way to access KV layer?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/server/status.go` line 2736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFJMSCS4_nQjefP6etH:-NFJMSCT3pmg8drePyo7:b3nfpzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/363db4297e6ad1e046e04394088c1e3bb1367045/pkg/server/status.go#L2736)):*
> ```Go
> 	var resp serverpb.HotRangesResponse_NodeResponse
> 	err := s.stores.VisitStores(func(store *kvserver.Store) error {
> 		ranges := store.HottestReplicasByTenant(tenantID)
> ```

`HottestReplicasByTenant` is implemented in another PR (#90097)

**Review by dhartunian — COMMENTED** [review]
@koorosh can you explain why you can't use the existing `HotRanges` or `HotRangesV2` APIs? I see there's duplicated code here already and am wondering why. I'd like to avoid tenant-specific endpoints.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-:-NFJo-YBCJAM-sxFpssu:bavooz4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/status.go` line 2736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFJMSCS4_nQjefP6etH:-NFJuZWe5BnQ9gplJWHX:bcl7w84) ([raw file](https://github.com/cockroachdb/cockroach/blob/363db4297e6ad1e046e04394088c1e3bb1367045/pkg/server/status.go#L2736)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`HottestReplicasByTenant` is implemented in another PR (#90097)
</blockquote></details>

Is there no way to unify `HotRanges` and `TenantHotRanges`? There's a lot of duplicated code here.

**Review by koorosh — COMMENTED** [review]
Agree, will extend `HotRangesV2` API to cover "per-tenant" requests as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-:-NFL-s05BYpmq1MJ4X31:b7ov7be)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/status.go` line 2736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFJMSCS4_nQjefP6etH:-NFL8OH91P1tbtQjpDE1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/363db4297e6ad1e046e04394088c1e3bb1367045/pkg/server/status.go#L2736)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is there no way to unify `HotRanges` and `TenantHotRanges`? There's a lot of duplicated code here.
</blockquote></details>

Done

**Review by koorosh — COMMENTED** [review]
Unification APIs added one more requirement to specify `tenantID` in `HotRangesRequest` because information
about tenant ID isn't preserved in context when request is propagated to another remote nodes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-:-NFnYmD343msAL2UCh3j:b-ub6ssn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/tenant_status.go` line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFuUNwF9BhoTDZ0mv9Y:-NFuUNwG-iTeLxfyebpz:bqrcj5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/799952615bccb7c437820cfee05948ac51669b7d/pkg/server/tenant_status.go#L1299)):*
> ```Go
> func (t *tenantStatusServer) HotRangesV2(ctx context.Context, req *serverpb.HotRangesRequest) (*serverpb.HotRangesResponseV2, error) {
> 	ctx = t.AnnotateCtx(propagateGatewayMetadata(ctx))
> 	return t.sqlServer.tenantConnect.HotRangesV2(ctx, req)
> ```

expectation:

`req` does NOT have anything specified because by sending it to this server, we already have CHOSEN a tenant

`t.sqlSever.tenantConnect.HotRangesV2(ctx, &HotRangesRequest{tenantID: myTenantID})`

then `tenant_auth` will check that the tenantID in request matches the server, before letting it through to KV.

**Comment by kvoli** [comment]
I tagged myself as a reviewer here but I think I really wanted to look at #90097.

**Comment by koorosh** [comment]
Adjusted code to latest changes in Status Server implementation. Appreciate any feedback!

**Review by dhartunian — COMMENTED** [review]
Looks good in general, just want to see if we can avoid adding `tenantID` to the API since it can be derived from local context.

> Reviewed 1 of 11 files at r3, 4 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-:-NKz3C2I4uxplOmiR7qH:b-6tpq72)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/status.go` line 2425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz10V-6xANsFUMwQ5k:-NKz10V-6xANsFUMwQ5l:b-umkc0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2425)):*
> ```Go
> 	var tenantID roachpb.TenantID
> 	if len(req.TenantID) > 0 {
> 		tenantID, err = roachpb.TenantIDFromString(req.TenantID)
> ```

I think you can get this from the context via `	tID, ok := roachpb.TenantFromContext(ctx)` like in `TenantRanges`. You just have to make sure it's inserted into the context...which it should be if you go through the connector :thinking: 
___
*[`pkg/server/status.go` line 2603 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz1Xc74WGlMql6eipW:-NKz1Xc74WGlMql6eipX:b-kp23s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2603)):*
> ```Go
> 
> func (s *systemStatusServer) localHotRanges(
> 	ctx context.Context, tenantID *roachpb.TenantID,
> ```

I think you can just take a value instead of a pointer and only check `.IsSet()` instead of the `nil` in the conditional below.
___
*[`pkg/server/serverpb/status.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFEUwY923q5oD8DY44O:-NKz0P_rEnt95xuSC2M9:b-dlc71r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1438e090ba54a625c8275d9ce0f8dd90b9385047/pkg/server/serverpb/status.go#L85)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I'm not confident that it's a common way to access kv layer but it's straightforward.
@dhartunian , can you suggest if it okay to extend this interface or there's another way to access KV layer?
</blockquote></details>

I think this works for accessing KV-level information.
___
*[`pkg/server/serverpb/status.proto` line 1290 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz0gPG-MJvzlESwoYT:-NKz0gPG-MJvzlESwoYU:b-btortk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/serverpb/status.proto#L1290)):*
> ```protobuf
>     (gogoproto.customname) = "TenantID",
>     (gogoproto.nullable) = true
>   ];
> ```

I don't think your request needs to have a tenantID field within. You can get the tenantID from the status server. See my comment there.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/status.go` line 2425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz10V-6xANsFUMwQ5k:-NLLWonBA40vpm0Jw5gi:bx9ugj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2425)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think you can get this from the context via `	tID, ok := roachpb.TenantFromContext(ctx)` like in `TenantRanges`. You just have to make sure it's inserted into the context...which it should be if you go through the connector :thinking: 
</blockquote></details>

I've tried this but it doesn't work when this API is called from UI. For some reason it is directly calls `systemStatusServer.HotRangesV2` and bypasses `connector`'s method that can inject tenant ID in context.
Also I'm not sure how to guarantee that Tenant ID will be propagated through `dialNode` calls when it has to be called on another remote node.
___
*[`pkg/server/status.go` line 2603 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz1Xc74WGlMql6eipW:-NLLWxuj9E_9sP3GnBlH:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2603)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think you can just take a value instead of a pointer and only check `.IsSet()` instead of the `nil` in the conditional below.
</blockquote></details>

Good point. Done.
___
*[`pkg/server/serverpb/status.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NFEUwY923q5oD8DY44O:-NLLX0TB2A9TRj3tPEsW:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1438e090ba54a625c8275d9ce0f8dd90b9385047/pkg/server/serverpb/status.go#L85)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think this works for accessing KV-level information.
</blockquote></details>

Thanks!

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/status.go` line 2425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz10V-6xANsFUMwQ5k:-NLRYjW_7gbs2X9nzHuS:b-7q0wss) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2425)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I've tried this but it doesn't work when this API is called from UI. For some reason it is directly calls `systemStatusServer.HotRangesV2` and bypasses `connector`'s method that can inject tenant ID in context.
Also I'm not sure how to guarantee that Tenant ID will be propagated through `dialNode` calls when it has to be called on another remote node.
</blockquote></details>

Figured out that `systemStatusServer.HotRangesV2` is called directly for system tenant.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/status.go` line 2425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz10V-6xANsFUMwQ5k:-NLWYuBTBcgZCoTJvy_2:b-fw4xji) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2425)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Figured out that `systemStatusServer.HotRangesV2` is called directly for system tenant.
</blockquote></details>

@dhartunian , just ensured that it's not currently possible to pass Tenant ID within context while calling `dialNode` to communicate between KV nodes ((

Instead found that there's already a case when Tenant ID is passed within request payload:
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/kvccl/kvtenantccl/connector.go#L629-L641
Curious to know if it should be treated as an exception or not?

**Comment by koorosh** [comment]
> What Zach and I discussed yesteday is that for hot ranges, we can perhaps insert the tenant prefix at the beginning of the start/end keys for the ranges. Since the functionality already uses start/end keys it would be a natural extension.

Hot ranges are based on `ReplicaRankings` functionality where N replicas with highest QPS accumulated in stack over the time. To track hot ranges per tenant - separate stacks allocated per tenant (https://github.com/cockroachdb/cockroach/pull/90097). 
I'm not sure that start/end keys applicable here as far as we collect hot ranges per store but not per arbitrary range of keys.

**Comment by knz** [comment]
A single range can contain data for at most 1 tenant (we split a tenant boundaries). So there is no need to "split" the stats collected per range.

What is needed here is to filter down the list of ranges being looked at. I believe it's reasonable to use start/end key boundaries to do this filtering.

**Comment by koorosh** [comment]
> So there is no need to "split" the stats collected per range.

It is split by _tenant_ to make sure that one tenant's stats doesn't affect others; and allows to keep ordered by QPS stats without need to filter/sort them on every request;

> What is needed here is to filter down the list of ranges being looked at.

List of hot ranges is limited to fixed length (128 ranges with highest QPS). Having a single list of hot ranges to look up by prefix key will require to reconsider how hot ranges are accumulated. How to guarantee that list of hot ranges doesn't grow without limitations and at the same time track ranges per tenant in isolation.
Current implementation keeps track separate stacks per tenant and it allows instant access by tenant ID but doesn't allow to do the same by start/end keys.

I'm not sure if it requires to reconsider the way hot ranges accumulated to make sure it's possible to query by start/end key?
Sorry if it looks obvious, I'm trying to understand your point and how it can be done.

**Comment by knz** [comment]
Sorry I have to backtrack in my argument. Only now I went to look more closely at #90097 and understand how per-tenant stats are collected.

Based on this new understanding, I agree that having the tenant ID as an additional query parameter is a better approach. 
My apologies for confusing matters.

**Comment by koorosh** [comment]
Appreciate any arguments/suggestions, and thanks for spending time on this!

**Review by dhartunian — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-:-NLaoKfU8P1QZlEmA4n2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/status.go` line 2425 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90618#-NKz10V-6xANsFUMwQ5k:-NLaoD8o9ara15WDJO6G:b-gz85cn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2272f5da5808794055f6ed8f015871b54136e0a/pkg/server/status.go#L2425)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@dhartunian , just ensured that it's not currently possible to pass Tenant ID within context while calling `dialNode` to communicate between KV nodes ((

Instead found that there's already a case when Tenant ID is passed within request payload:
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/kvccl/kvtenantccl/connector.go#L629-L641
Curious to know if it should be treated as an exception or not?
</blockquote></details>

Ok we can keep this exception for now. Thx for looking into it.

**Pull request merged**
