### PR TITLE
sql: make SHOW USERS/SHOW ROLES match psql \du command.

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Make SHOW USERS and SHOW ROLES the same since USERS=ROLES.
Make SHOW USERS and SHOW ROLES match psql \du command. SHOW ROLES displays three columns, username, options, member_of.

Release justification: Low risk change, only changing underlying select command for SHOW ROLES/USERS.

### CODE REVIEW

**Comment by RichardJCai** [comment]
@awoods187 
@knz suggested having SHOW USERS/SHOW ROLES be the same and have it match psql \du

Here's how both SHOW USERS / SHOW ROLES would look - 
image

Is this okay? If not I can go back to having SHOW USERs show those who can login and SHOW ROLES be showing both users/roles.

**Comment by knz** [comment]
I like this a lot 💯

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45827#-:-M2dHaf5EO2rNSFYP9wu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RichardJCai** [comment]
bors r=knz

**Pull request merged**
