### PR TITLE
 geoindex: error indexing NaN coordinates

### LINKED ISSUE #81609: geoindex: panic when trying to insert object with NaN coordinate
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=5223707&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=5223707&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on release-21.2 @ [2bd5952ed0db3dc898c0d75eb50bc65c26feef04](https://github.com/cockroachdb/cockroach/commits/2bd5952ed0db3dc898c0d75eb50bc65c26feef04):

```
						*
					FROM
						(VALUES (NULL), (NULL), (NULL), (7.429673887640251493E+26:::DECIMAL)) AS tab_140445 (col_214839)
				),
			with_44972 (col_214840)
				AS (
					SELECT
						*
					FROM
						(VALUES (NULL), ('\xe29883':::BYTES), ('\x94b4':::BYTES), ('\xf3ff':::BYTES)) AS tab_140446 (col_214840)
				)
		SELECT
			tab_140448.col1_2 AS col_214841,
			'10:24:07.603288':::TIME AS col_214842,
			(-0.3989618420600891):::FLOAT8 AS col_214843,
			st_rotatex('0105000000060000000102000000020000002CF565DB1790F041C2509EC57231F2411C1E119D614AE7C166AFF2D39B030142010200000003000000809745B2972CF84160399714F897E241E0D03302F1C6D6410EFC89BE9FE20042F83C7FD5C4ACD6411854CBFDFF42DE41010200000004000000C4A695BE1FC2FD411CE9BCE66C42D8C142F59F55FD7800424C0D1238165FE041A07574B08DC0D94170D034F5A969EB41D843A641FF49E741B6F0864FF80E0242010200000004000000781D60294113F2412C338441624C02C2100451CE196BED41525C0281389BEEC11430818C69A2EF415C09A4FD752D024200E4B02D00CB9341C047BBFE74DDE44101020000000400000040B0B6B74C96A0C162D23CFAACB8E7C11CD943F294E9E5C187C18248646102C2709F7E29F32AC4C160D1A56EC799FAC1607737DC4662E941ADC9125B944FF6C1010200000004000000F097AF975517F441714AF1717A16F0C15442BA391710F841BEBE416B6780F241E01C9C5F7602B6413CC620A0C9C3E14140E714D68300E2C1A0C4038270B4BAC1':::GEOMETRY::GEOMETRY, tab_140448.col1_3::FLOAT8)::GEOMETRY
				AS col_214844
		FROM
			defaultdb.public.table3@[0] AS tab_140447, defaultdb.public.table1@[0] AS tab_140448
		LIMIT
			94:::INT8;

	cluster.go:1296,context.go:91,cluster.go:1284,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-5223707-1653112301-10-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 2: 12429
		1: dead (exit status 134)
		3: 12310
		4: 11803
		Error: UNCLASSIFIED_PROBLEM: 1: dead (exit status 134)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/roachprod.Monitor
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/roachprod.go:596
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:569
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:123
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1170
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:255
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
		Wraps: (3) 1: dead (exit status 134)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16035

### PR DESCRIPTION
**Pull request by otan**
Resolves #81609

Release note (bug fix): Previously, inserting geometries into a table
with an inverted index involving a NaN coordinate could result in a
panic. This has now errors instead.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106671)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[`pkg/geo/geoindex/s2_geometry_index.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106671#-N_ESrrIBysBLD5kY8bo:-N_ESrrIBysBLD5kY8bp:bh9oub0) ([raw file](https://github.com/cockroachdb/cockroach/blob/280efdfd208c582343547e26cd1c4bf6a297c031/pkg/geo/geoindex/s2_geometry_index.go#L283)):*
> ```Go
> 	if bbox := g.BoundingBoxRef(); bbox != nil && (math.IsNaN(bbox.LoX) || math.IsNaN(bbox.HiX) ||
> 		math.IsNaN(bbox.LoY) || math.IsNaN(bbox.HiY)) {
> 		return nil, true, nil
> ```

How about returning an error here instead? We haven't correctly indexed this shape since we haven't included the clipped shape. We are supposed to index the clipped shape *and* add `exceedsBoundsCellID` as mentioned in https://github.com/cockroachdb/cockroach/blob/bbfe3d08923e0543ac290e0cf025f984ba2ece5c/pkg/geo/geoindex/s2_geometry_index.go#L180-L183

**Comment by otan** [comment]
*[`pkg/geo/geoindex/s2_geometry_index.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106671#-N_ESrrIBysBLD5kY8bo:-N_GTTJU7BSZjowhwUeo:b-lg1385) ([raw file](https://github.com/cockroachdb/cockroach/blob/280efdfd208c582343547e26cd1c4bf6a297c031/pkg/geo/geoindex/s2_geometry_index.go#L283)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about returning an error here instead? We haven't correctly indexed this shape since we haven't included the clipped shape. We are supposed to index the clipped shape *and* add `exceedsBoundsCellID` as mentioned in https://github.com/cockroachdb/cockroach/blob/bbfe3d08923e0543ac290e0cf025f984ba2ece5c/pkg/geo/geoindex/s2_geometry_index.go#L180-L183
</blockquote></details>

good idea! done!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106671#-:-N_Jh45J7h5juz3Gbq_5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106671#-N_Jgq8gCRmaLHD1guYZ):*
nit: This returns an error instead.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks for the fix!

> Reviewed 8 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106671#-:-N_KvUxE4Hmp-qcVZGaE:b-rsz3om)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

**Comment by otan** [comment]
bors r=rytaft,sumeerbhola

**Comment by otan** [comment]
bors r=rytaft,sumeerbhola

**Comment by otan** [comment]
what a bizarre flake...

```
ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeedcache/BUILD.bazel:26:8: GoCompilePkg pkg/kv/kvclient/rangefeed/rangefeedcache/ordering.recompile1109.a failed: (Exit 1): builder failed: error executing command (from target //pkg/kv/kvclient/rangefeed/rangefeedcache:rangefeedcache_test) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/sql/opt/ordering/distribute.go ... (remaining 76 arguments skipped)
  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  compilepkg: panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e89bc]
  goroutine 516 [running]:
  go/types.methodSet.add(0xc17ea0?, {0x0, 0x1, 0xc00057fe50?}, {0x0, 0x0, 0xc0035b3b90?}, 0x58?, 0x5d?)
    GOROOT/src/go/types/methodset.go:214 +0xdc
  go/types.NewMethodSet({0xc17ea0?, 0xc002710bd0?})
    GOROOT/src/go/types/methodset.go:150 +0x869
  golang.org/x/tools/go/types/typeutil.(*MethodSetCache).lookupNamed(0xc001d346e0, 0xc002710bd0)
    golang.org/x/tools/go/types/typeutil/external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:66 +0x99
  golang.org/x/tools/go/types/typeutil.(*MethodSetCache).MethodSet(0xc001d346e0, {0xc17ea0?, 0xc002710bd0?})
    golang.org/x/tools/go/types/typeutil/external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:37 +0xe5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc002710bd0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:191 +0xf5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc003695d70?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc000e377a0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:209 +0x1f7
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc000e470c8?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ec8?, 0xc000e2ac40?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:208 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc000e78468?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ec8?, 0xc000e2b0b0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:208 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc000e78a20?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc000b1f110?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:208 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc000e78a80?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc0002f0f50?}, 0x0, 0xfbaca8?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:209 +0x1f7
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f40?, 0xc000fd0720?}, 0x1, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:255 +0x6b6
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc000298a80?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:248 +0x589
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ec8?, 0xc000fc8cc0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:220 +0x5d1
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc001034c90?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ec8?, 0xc003c5b180?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:208 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ea0?, 0xc000fccf50?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:242 +0x55a
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f18?, 0xc000fc8ec0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:223 +0x37b
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc001035620?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ec8?, 0xc001a7e4e0?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:209 +0x1f7
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17f68?, 0xc001a4d740?}, 0x0, 0xfbaca0?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:260 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001d346c0, {0xc17ef0?, 0xc001a83f80?}, 0x0, 0x503a3e?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:236 +0x314
  golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc001d346c0, {0xc17ef0?, 0xc001a83f80?}, 0x9200000000000180?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:172 +0x7f
  golang.org/x/tools/go/ssa.(*Package).build(0xc000d3ac00)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/builder.go:2501 +0x13f
  sync.(*Once).doSlow(0xc001d346c0?, 0xc0003253b0?)
    GOROOT/src/sync/once.go:74 +0xc2
  sync.(*Once).Do(...)
    GOROOT/src/sync/once.go:65
  golang.org/x/tools/go/ssa.(*Package).Build(...)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/builder.go:2477
  golang.org/x/tools/go/analysis/passes/buildssa.run(0xc00084d950)
    golang.org/x/tools/go/analysis/passes/buildssa/external/org_golang_x_tools/go/analysis/passes/buildssa/buildssa.go:72 +0x1a8
  main.(*action).execOnce(0xc00068a780)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:353 +0x843
  sync.(*Once).doSlow(0x755073492e797469?, 0x100000186ff6572?)
    GOROOT/src/sync/once.go:74 +0xc2
  sync.(*Once).Do(...)
    GOROOT/src/sync/once.go:65
  main.(*action).exec(0x6f697469646e6f43?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:280 +0x3d
  main.execAll.func1(0x33762f6470612f62?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:274 +0x54
  created by main.execAll
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:272 +0x47
  panic: interface conversion: interface {} is nil, not *buildssa.SSA
  goroutine 179 [running]:
  github.com/cockroachdb/cockroach/pkg/testutils/lint/passes/nilness.(*analyzerConfig).run(0xa92400?, 0xc003554000)
    github.com/cockroachdb/cockroach/pkg/testutils/lint/passes/nilness/nilness.go:132 +0xbc
  main.(*action).execOnce(0xc00068bf40)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:353 +0x843
  sync.(*Once).doSlow(0x6f5043470b016270?, 0x1304d2e7963696c?)
    GOROOT/src/sync/once.go:74 +0xc2
  sync.(*Once).Do(...)
    GOROOT/src/sync/once.go:65
  main.(*action).exec(0x3201000001020201?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:280 +0x3d
  main.execAll.func1(0x7361654c12016270?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:274 +0x54
  created by main.execAll
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:272 +0x47
  INFO: Elapsed time: 349.202s, Critical Path: 276.71s
  INFO: 10243 processes: 1716 internal, 108 local, 8419 processwrapper-sandbox.
  FAILED: Build did NOT complete successfully
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xb0c78c]
  goroutine 35 [running]:
  main.(*monitorBuildServer).handleBuildEvent(0xc0000ece40, {0x0?, 0xc000314ad0?}, 0xc00010fc80)
    main/pkg/cmd/bazci/bazci.go:209 +0x32c
  main.(*monitorBuildServer).PublishBuildToolEventStream(0xc000314b10?, {0xdd90d0, 0xc000380260})
    main/pkg/cmd/bazci/bazci.go:155 +0xaa
  google.golang.org/genproto/googleapis/devtools/build/v1._PublishBuildEvent_PublishBuildToolEventStream_Handler({0xc0dce0?, 0xc0000ece40}, {0xdd7888?, 0xc0003c6000})
    google.golang.org/genproto/googleapis/devtools/build/v1/bazel-out/k8-fastbuild/bin/external/go_googleapis/google/devtools/build/v1/build_go_proto_/google.golang.org/genproto/googleapis/devtools/build/v1/publish_build_event.pb.go:816 +0x9f
  google.golang.org/grpc.(*Server).processStreamingRPC(0xc0002325a0, {0xdd9518, 0xc0002d21a0}, 0xc00039a240, 0xc0002b28d0, 0x1299940, 0x0)
    google.golang.org/grpc/external/org_golang_google_grpc/server.go:1620 +0x11e7
  google.golang.org/grpc.(*Server).handleStream(0xc0002325a0, {0xdd9518, 0xc0002d21a0}, 0xc00039a240, 0x0)
    google.golang.org/grpc/external/org_golang_google_grpc/server.go:1708 +0x9ea
  google.golang.org/grpc.(*Server).serveStreams.func1.2()
    google.golang.org/grpc/external/org_golang_google_grpc/server.go:965 +0x98
  created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc/external/org_golang_google_grpc/server.go:963 +0x28a
```

**Pull request merged**
