### PR TITLE
sql: JSON-ify timestamps using RFC3339 format

### LINKED ISSUE #34372: sql: json timestamp stringify doesn't match postgres
cockroach
```
> select json_build_object('foo', now());
               json_build_object
+---------------------------------------------+
  {"foo": "2019-01-29 19:37:52.855198+00:00"}
```

postgres
```
# select json_build_object('foo', now());
              json_build_object
----------------------------------------------
 {"foo" : "2019-01-29T11:50:35.607352-08:00"}
```

Note the "T" between date and time. I think the postgres is something like rfc 3339, but I haven't looked for it in their docs.

Assigning to @justinj for triage

### PR DESCRIPTION
**Pull request by bobvawter**
Currently, when converting a timestamp value to a JSON string, we use
CockroachDB's customary string format, which is RFC3339 without the T separator.
This creates some compatibility problems with JSON consumers which expect to
receive exactly RFC3339-formatted timestamp value.

The output in the logictest has been cross-checked against a PostgreSQL 10
database.

Fixes #34372

Release note (sql change): Formatting of timestamps as JSON strings has been
changed to always use the RFC3339 format instead of Cockroach's customary
format. Users can now expect to see a `T` separator instead of a space between
the date and time components.

### CODE REVIEW

**Comment by rolandcrosby** [comment]
Thanks for the quick fix @bobvawter. Are you hoping to get this out as a bug fix, with the logic being that this was an unintended divergence from the typical Postgres behavior? I don't know how we typically handle this kind of output change, since it could break applications that consume data from CRDB.

**Comment by bobvawter** [comment]
@rolandcrosby Yes, I think this qualifies as a bug-fix, since the existing behavior was a divergence from the PG behavior.  I have amended the commit message with a release note describing the change.

As to the more general question of how do we classify potentially-breaking changes, @knz has been working on a rather comprehensive document outlining the current thinking on when a compatibility mode is justified, etc.

**Review by knz — APPROVED** [review]
LGTM thanks with nit

**Pull request merged**
