### PR TITLE
kvserver: fix bug causing stuck closed timestamps

### PR DESCRIPTION
**Pull request by andreimatei**
r.ensureClosedTimestampStarted() was broken when we made non-leader
replicas refuse to acquire leases. This function was relying on a lease
being acquire if there's no valid lease, and in the case where the
leader was elsewhere it wasn't getting what it wanted. As a result,
rangefeeds (which use this method to "nudge" the range into sending
closed timestamp updates) were stuck because closed timestamp updates
were not generated - timestamps are not closed when there's no lease.
Because they weren't getting closed timestamp updates, rangefeeds were
not generating resolved timestamp updates, and so data (from other
ranges) was being endlessly buffered.

The fix is to force a lease acquisition by performing a read on the
respective range.

Release note (bug fix): A bug causing changefeeds to sometimes get stuck
was fixed.

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @aayushshah15

**Review by miretskiy — APPROVED** [review]
This change :lgtm:, but syou probably should get lg from @nvanbenschoten or @ajwerner  since I"m not a an expert on closedts.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-:-MfEp20tE_hucGXtTQ7g:b-vnnpj1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEniU38LXdslDSI4oJ:-MfEniU38LXdslDSI4oK:b-s76ylk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/keys/constants.go#L148)):*
> ```Go
> 	// They're useful for reading, though, for example as a way to force a lease
> 	// acquisition.
> 	LocalDummyRangeKeySuffix = roachpb.RKey("dumy")
> ```

s/dumy/dummy/
___
*[pkg/keys/keys.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEnsCa7WvcvR6I7aHj:-MfEnsCa7WvcvR6I7aHk:b-alue56) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/keys/keys.go#L403)):*
> ```Go
> 
> // DummyRangeKey returns a range-local key that is never written to.
> func DummyRangeKey(rangeStart roachpb.RKey) roachpb.Key {
> ```

I wonder if we should rename it to a NoopKey (and rename `LocalDummyRangeKeySuffix` to `NoopRangeKeySuffix`)?
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEoqqZAvQ274hCYDz7:-MfEoqqZAvQ274hCYDz8:b-y2app2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1138)):*
> ```Go
> 	// record that's in flight (perhaps the split's txn) races and re-acquires the
> 	// lease we're about to expire.
> 	time.Sleep(time.Second)
> ```

could this sleep make the test flaky?

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @miretskiy, and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEniU38LXdslDSI4oJ:-MfEpbcC4Zd5Ple1Q1en:begs4jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/keys/constants.go#L148)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

s/dumy/dummy/
</blockquote></details>

Or a different term. Is there a justification for the 4-letter thing? 
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEoWb-6m5jJrIv01xH:-MfEoWb09jCJs8QgGHUS:bh6t6xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed.go#L677)):*
> ```Go
> 		fn(ctx, r, lease)
> 	}
> 	// Do a dummy (consistent) read on a range-local key, in order to ensure a
> ```

I think we're trying to not use `dummy` as a term. I think `reserved` to describe the key might serve the purpose here.
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEo1_w7ZuEibaGk16O:-MfEo1_w7ZuEibaGk16P:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed.go#L683)):*
> ```Go
> 	// doesn't work because, if the current lease is invalid and the current
> 	// replica is not a leader, it will not take a lease.
> 	//
> ```

nit: extra line
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEok1j6Zx9o_FK9mV5:-MfEok1j6Zx9o_FK9mV6:b-2wnsfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed.go#L685)):*
> ```Go
> 	//
> 	//
> 	// Note that the dummy key we're reading is never written to, so we don't
> ```

`reserved key`?
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEq6ySBfpnP5YG4bVO:-MfEq6ySBfpnP5YG4bVP:b-n8u7ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1036)):*
> ```Go
> 				DisableReplicaGCQueue:             true,
> 				DisableTimeSeriesMaintenanceQueue: true,
> ```

any interest in observing the actual read request with a `ReplicaRequestFilter`?
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEpWReAdz7kylG9Jl8:-MfEpWRf3p77MLM9XvWi:b-c29p0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1136)):*
> ```Go
> 
> 	// Sleep a little bit to let the range quiesce. Otherwise, GCing of a txn
> 	// record that's in flight (perhaps the split's txn) races and re-acquires the
> ```

what split?

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 692 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFI3a_3oBoiVAaIped:-MfFI3a_3oBoiVAaIpee:b7x7ijz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed.go#L692)):*
> ```Go
> 		err := contextutil.RunWithTimeout(ctx, "read forcing lease acquisition", 5*time.Second,
> 			func(ctx context.Context) error {
> 				_, err := r.store.DB().Get(ctx, reservedKey)
> ```

I understand why we're using this dummy key read, but it all seems a bit hacky and unnecessary to me when we have other solutions available. Did you consider using a request like `RangeStatsRequest`? That avoids hitting the LSM on the other side. I think @ajwerner suggested that on one of the threads.
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFIsSXD14mP0RlNMjl:bnollbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
> ```Go
> // lease, and it does so because of a read performed by
> // r.ensureClosedTimestampStarted().
> func TestRangefeedCheckpointsRecoverFromLeaseExpiration(t *testing.T) {
> ```

This is a nice test. It seems like we should also (not in this PR and not written by you) have a higher-level test up in CDC land as well where we spin up a multi-node testcluster, import N ranges worth of one of our workloads into it, then restart the cluster without adding any load and make sure a newly established changefeed is publishing checkpoints.

cc. @miretskiy what do you think?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFUXUK0MOZG0r2Leui:bqp8vgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a nice test. It seems like we should also (not in this PR and not written by you) have a higher-level test up in CDC land as well where we spin up a multi-node testcluster, import N ranges worth of one of our workloads into it, then restart the cluster without adding any load and make sure a newly established changefeed is publishing checkpoints.

cc. @miretskiy what do you think?
</blockquote></details>

@miretskiy Andrei and I were talking a bit about this and we had a question for you. This whole nudging behavior to ensure that each inactive range has a leaseholder was introduced in https://github.com/cockroachdb/cockroach/pull/36684 in response to behavior seen in https://github.com/cockroachdb/cockroach/issues/35142. Do you have any idea why that roachtest (now called `cdc/tpcc-1000`) missed this regression?

It still certainly seems that we'll want an intermediate multi-node unit test using a testcluster that exercises this behavior, but it's interesting that the high-level test that motivated this did not catch the issue.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @miretskiy, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFa6es2sOV-6pHl3lg:bmxptf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@miretskiy Andrei and I were talking a bit about this and we had a question for you. This whole nudging behavior to ensure that each inactive range has a leaseholder was introduced in https://github.com/cockroachdb/cockroach/pull/36684 in response to behavior seen in https://github.com/cockroachdb/cockroach/issues/35142. Do you have any idea why that roachtest (now called `cdc/tpcc-1000`) missed this regression?

It still certainly seems that we'll want an intermediate multi-node unit test using a testcluster that exercises this behavior, but it's interesting that the high-level test that motivated this did not catch the issue.
</blockquote></details>

Not really, other than the fact that the customer table was pretty big; perhaps tpcc-1000 cdc test is not large enough to trigger this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEoWb-6m5jJrIv01xH:-MfFEBBxBrBtzrwkmXmW:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed.go#L677)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think we're trying to not use `dummy` as a term. I think `reserved` to describe the key might serve the purpose here.
</blockquote></details>

removed
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEok1j6Zx9o_FK9mV5:-MfFED8Q2hUNx_VKuscd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed.go#L685)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`reserved key`?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_rangefeed.go, line 692 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFI3a_3oBoiVAaIped:-MfFaycs1HLHg8s_HS9i:bg0i3ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed.go#L692)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I understand why we're using this dummy key read, but it all seems a bit hacky and unnecessary to me when we have other solutions available. Did you consider using a request like `RangeStatsRequest`? That avoids hitting the LSM on the other side. I think @ajwerner suggested that on one of the threads.
</blockquote></details>

switched to `LeaseInfoRequest`
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEq6ySBfpnP5YG4bVO:-MfFEEn7BEXBDJTdMsTx:b-8166me) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1036)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

any interest in observing the actual read request with a `ReplicaRequestFilter`?
</blockquote></details>

I didn't originally, but in the meantime I've needed a filter anyway to reject random requests and stabilize the test - instead of the sleep below. So now the new knob is gone.
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEpWReAdz7kylG9Jl8:-MfFLfrD6x7qtT6w5H5h:b3y3r8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1136)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what split?
</blockquote></details>

I was thinking of the split creating the scratch range (inside the `TestCluster` creation). But I think it was actually the commit from the up-replication
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEoqqZAvQ274hCYDz7:-MfFbNKn0F-CXrk8w4hj:b-19ifje) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/kv/kvserver/replica_rangefeed_test.go#L1138)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

could this sleep make the test flaky?
</blockquote></details>

the sleep was making the test non-flaky :p
But yeah, I've done something else instead - a filter rejecting unexpected random requests,
___
*[pkg/keys/constants.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEniU38LXdslDSI4oJ:-MfFE6TE9vFmixIvbZGA:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/keys/constants.go#L148)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Or a different term. Is there a justification for the 4-letter thing? 
</blockquote></details>

removed
___
*[pkg/keys/keys.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfEnsCa7WvcvR6I7aHj:-MfFE7iIC1PcqBfnhPJj:b8idazv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e1efa8f92eaf799ab51c928414423f1e9d9e3/pkg/keys/keys.go#L403)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wonder if we should rename it to a NoopKey (and rename `LocalDummyRangeKeySuffix` to `NoopRangeKeySuffix`)?
</blockquote></details>

went with `reserved`

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFcBF08M6aiV4W4C_v:bhzjqu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Not really, other than the fact that the customer table was pretty big; perhaps tpcc-1000 cdc test is not large enough to trigger this?
</blockquote></details>

I think it's definitely worth pulling on this. Even though the problem was relatively low in the stack,  we need a high-level CDC test with enough chaos to catch this, I think.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-:-MfFd_CN91SRbh9flkTd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFdCGMDMHR7aZ0KUCp:bqz5fv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
> to catch this, I think.

This or any other bugs lurking at various levels in the stack which could have a similar effect.

**Comment by aayushshah15** [comment]
>Do you have any idea why that roachtest (now called cdc/tpcc-1000) missed this regression?

Would we expect to have any dormant ranges in a tpc-c workload? My understanding was that we wouldn't, which would explain why we didn't catch this in that roachtest. Do you buy that?

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-:-MfFs-eD9mp8Ec4aYr-5:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1010 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67952#-MfFIsSXD14mP0RlNMjk:-MfFs2IU3ztrNf-Xmd3X:btaw96p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bf2d77028b09c7ceecf93ca22c6f2020f917ec9/pkg/kv/kvserver/replica_rangefeed_test.go#L1010)):*
copying comment to the right place:

> [aayush] Would we expect to have any dormant ranges in a tpc-c workload? My understanding was that we wouldn't, which would explain why we didn't catch this in that roachtest. Do you buy that?

**Pull request merged**
