### PR TITLE
sqlccl: disallow BACKUP and RESTORE on 2.x nodes in 1.x clusters

### PR DESCRIPTION
**Pull request by dt**
older nodes would execute the commands incorrectly, ignoring the new flag.

Release note: none.

### CODE REVIEW

**Comment by mjibson** [comment]
Is there a reason we can't/shouldn't make a new version identifier specifically for this issue? I'm not sure it's best to tag along on that other one.

**Comment by dt** [comment]
1.1.0-4 is well after it merged, so there's no really benefit to adding a 1.1.0-5 and making people bump the setting?

**Comment by mjibson** [comment]
In that case we should be using VersionClearRange because we need this version to be after #20185 since that made backup correctly resume in all cases.

**Comment by dt** [comment]
Good point. Done.

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-L0LnJGyQArIIxJuHaBS:-L0LnJGyQArIIxJuHaBT:bfgvcik) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b77c13d87d12598034eb74b771847fe6e907c3f/pkg/ccl/sqlccl/backup.go#L731)):*
> ```Go
> 		mvccFilter := MVCCFilter_Latest
> 		if _, ok := opts[backupOptRevisionHistory]; ok {
> 			// older nodes don't know about MVCCAll and would incorrectly do latest.
> ```

This code looks correct, but it is in the wrong place. We can't start any backups with an old node in the cluster because of the new BackupDescriptor field, which old nodes won't see. It is possible we should do the same thing for RESTORE (i.e., put the version check at the top and not in any feature-detection block).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721)*

**Comment by mjibson** [comment]
@tschottdorf do you have thoughts on whether or not we should/should not add a specific version marker for this, or is it ok to piggyback off another?

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-L0LnJGyQArIIxJuHaBS:-L0Lpe4E0eD_opvf-oKi:b-d6589y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b77c13d87d12598034eb74b771847fe6e907c3f/pkg/ccl/sqlccl/backup.go#L731)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This code looks correct, but it is in the wrong place. We can't start any backups with an old node in the cluster because of the new BackupDescriptor field, which old nodes won't see. It is possible we should do the same thing for RESTORE (i.e., put the version check at the top and not in any feature-detection block).
</blockquote></details>

Are you just referring to options being lost on resume? Isn't that an issue on 1.x with or without a 2.x node in the mix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-L0LnJGyQArIIxJuHaBS:-L0RC5ebNisKuHn9Bz3v:b-xse54l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b77c13d87d12598034eb74b771847fe6e907c3f/pkg/ccl/sqlccl/backup.go#L731)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Are you just referring to options being lost on resume? Isn't that an issue on 1.x with or without a 2.x node in the mix?
</blockquote></details>

The backupdesc also contains the completeDB field, so if a 1.x node resumes a 2.x backup, it will be forgotten. I'm not aware of any 1.x options that are forgotten during a resume.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721)*

**Comment by dt** [comment]
Per discussion with @mjibson:

Basically there has just been so much churn in the fields and flags and how they're handled that, since we don't have a really strong story as far as mixed version testing, moving the check out to be unconditional just feels like the safest option, covering the unknown-unknowns aspect here. If an operator really does want to run in a mixed cluster, they still have the option of doing so by sending the command to one of the remaining 1.x nodes, so I've withdrawn my objection that it was overly restrictive, and gone ahead and moved it.

**Comment by dt** [comment]
okay, fixed up rebase conflict, and RFAL.

**Comment by mjibson** [comment]
Let's say an operator has a mixed-version cluster, wants to backup, and sends a backup statement to a 1.1 node. If that node goes down and a 2.0 node adopts the job and attempts to resume it, it will fail. I think this is ok, but now the requirements for successfully running a backup/restore on a mixed version cluster are: send it to the old nodes, and make sure those nodes don't go down or else it may fail. I guess that's ok. But this situation is not great. Although maybe we're worrying about something that no users actually care about anyway.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-L2WYJsu8319N6DKSnc8:-L2WYJsu8319N6DKSnc9:b-5gi8zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bad9e6df99ae171d03f80cafaa63023a0f2eb55/pkg/ccl/sqlccl/backup.go#L667)):*
> ```Go
> 		// jobs resume refactorings, though we may still wish to bump this to 2.0
> 		// when that is defined.
> 		if !p.ExecCfg().Settings.Version.IsMinSupported(cluster.VersionClearRange) {
> ```

This block is below the span tracing stuff above, while the other block is above it. We should choose one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-:-L2WYbqW8P4y7QpwCJCN:bapus1t)*

**Comment by dt** [comment]
Yep, indeed. It certainly isn't ideal, the strict bad cuts the most unknown-unknowns as far as how new and old backups/restores will interact. Combined with diana's feedback that running these operations in mixed versions clusters aren't isn't a critical concern for many, I think your initial intuition to just be strict makes sense.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 667 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-L2WYJsu8319N6DKSnc8:-L2X1DsAadpN1kkuI3af:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bad9e6df99ae171d03f80cafaa63023a0f2eb55/pkg/ccl/sqlccl/backup.go#L667)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This block is below the span tracing stuff above, while the other block is above it. We should choose one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20721#-:-L2X1EMgOphp0ZaIboJo:b6y1q99)*

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
