### PR TITLE
kvserver: bring TestRaftPreVote to a leader leases world

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits.

### CODE REVIEW

**Review by iskettaneh — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136177)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by arulajmani** [comment]
bors r=iskettaneh

**Comment by arulajmani** [comment]
Rebased. 

bors r+

**Comment by arulajmani** [comment]
The linter doesn't like `t.Skip`. Fixed it.

bors r+

**Pull request merged**
