### PR TITLE
distsqlrun: start all sources on heap in orderedSynchronizer

### LINKED ISSUE #35304: teamcity: failed test: TestLogic
The following tests appear to have failed on master (test): TestLogic/fakedist: TestLogic/fakedist-metadata, TestLogic, TestLogic/fakedist: TestLogic/fakedist-metadata: TestLogic/fakedist-metadata/fk

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestLogic).

[#1156962](https://teamcity.cockroachdb.com/viewLog.html?buildId=1156962):

```
TestLogic/fakedist: TestLogic/fakedist-metadata
--- FAIL: test/TestLogic: TestLogic/fakedist: TestLogic/fakedist-metadata (0.360s)




TestLogic/fakedist: TestLogic/fakedist-metadata: TestLogic/fakedist-metadata/fk
--- FAIL: test/TestLogic: TestLogic/fakedist: TestLogic/fakedist-metadata: TestLogic/fakedist-metadata/fk (2.540s)

------- Stdout: -------
=== PAUSE TestLogic/fakedist-metadata/fk
            logic.go:2313: 
                 
                testdata/logic_test/fk:318: 
                expected "foreign key violation: \"delivery\" row item='885155001450' has no match in \"products\"", but found "pq: expected 13 metadata senders but found 11; missing ae10e1a7-4615-45ed-beb8-fb4632e27be3, 5436c8c4-3b88-4ed4-ac49-a2e3d2c5b392"
            logic.go:2345: 
                testdata/logic_test/fk:321: error while processing
            logic.go:2346: testdata/logic_test/fk:321: too many errors encountered, skipping the rest of the input



TestLogic
--- FAIL: test/TestLogic (422.610s)

------- Stdout: -------
    test_log_scope.go:81: test logs captured to: /tmp/logTestLogic876114019
    test_log_scope.go:62: use -show-logs to present logs inline




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by asubiotto**
Previously, the orderedSynchronizer heap would start off empty in its
notInitialized state. This state would be at odds with the assumption
made that only sources that had no more rows or metadata to give would
be out of the heap. This led to cases in which the draining code would
not drain sources that had pending metadata, before initHeap was called.

This commit removes initHeap's responsibility to add all unfinished
sources to the sync's heap by initializing the sync with a full heap
(although unordered), which is then ordered and removed of any empty
sources in initHeap.

Fixes #35304

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/input_sync.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35648#-L_nMAMJ4azNdjUye_Y8:-L_nMAMJ4azNdjUye_Y9:b-impx3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/540934125026787d54f97e563cf023a9f99e1612/pkg/sql/distsqlrun/input_sync.go#L144)):*
> ```Go
> 	// consumeErr is the last error encountered while consuming metadata.
> 	var consumeErr error
> ```

Add a comment here about the state of `s.heap` at this point, and what we're about to do. Something like "The heap now contains all of the sources. Go through the sources and remove them if they're already finished".

**Review by asubiotto — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35648#-:-L_sZM7IAndwS-n8ViJZ:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/distsqlrun/input_sync.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35648#-L_nMAMJ4azNdjUye_Y8:-L_sZNTEC1C00kE1It5U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/540934125026787d54f97e563cf023a9f99e1612/pkg/sql/distsqlrun/input_sync.go#L144)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add a comment here about the state of `s.heap` at this point, and what we're about to do. Something like "The heap now contains all of the sources. Go through the sources and remove them if they're already finished".
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
bors r-

Logic tests have discovered a panic

**Comment by asubiotto** [comment]
bors r+

Changed the deletion logic to only truncate the slice after the for loop

**Pull request merged**
