### PR TITLE
go.mod: bump Pebble to 5babbee7ffe8

### PR DESCRIPTION
**Pull request by aadityasondhi**
Changes:

 * [`5babbee7`](https://github.com/cockroachdb/pebble/commit/5babbee7) metamorphic: add a missing simulated excise
 * [`9c2da6d2`](https://github.com/cockroachdb/pebble/commit/9c2da6d2) metamorphic: reenable downloadOp
 * [`090ee67e`](https://github.com/cockroachdb/pebble/commit/090ee67e) db: minor reorganization of downloadSpan code
 * [`8453c9c1`](https://github.com/cockroachdb/pebble/commit/8453c9c1) db: add separate download concurrency count
 * [`a043debc`](https://github.com/cockroachdb/pebble/commit/a043debc) base: minor documentation fixes for Comparer
 * [`86b5f54c`](https://github.com/cockroachdb/pebble/commit/86b5f54c) db: copy synthetic prefix/suffix when excising
 * [`bd8563ec`](https://github.com/cockroachdb/pebble/commit/bd8563ec) objstorageprovider: fix race in `GetExternalObjects`
 * [`83e94440`](https://github.com/cockroachdb/pebble/commit/83e94440) metamorphic: ingestAndExcise key manager fixes
 * [`35d80916`](https://github.com/cockroachdb/pebble/commit/35d80916) db: flushable ingest excise fixes

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by jbowens** [comment]
```
    --- FAIL: TestPebbleRestarts/engine/standard (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1042314]
goroutine 73 [running]:
testing.tRunner.func1.2({0x1871ca0, 0x2afd880})
  GOROOT/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
  GOROOT/src/testing/testing.go:1634 +0x377
panic({0x1871ca0?, 0x2afd880?})
  GOROOT/src/runtime/panic.go:770 +0x132
github.com/cockroachdb/pebble.(*Options).String(0xc0003fcb08)
  github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/options.go:1355 +0x734
github.com/cockroachdb/cockroach/pkg/storage/metamorphic.(*engineConfig).create(0xc000376b70, {0xc00030e8c0?, 0xc0000fb998?}, {0x1e395a0?, 0xc000053700?})
  github.com/cockroachdb/cockroach/pkg/storage/metamorphic/generator.go:52 +0x153
github.com/cockroachdb/cockroach/pkg/storage/metamorphic.(*metaTestRunner).init(0xc000002000)
  github.com/cockroachdb/cockroach/pkg/storage/metamorphic/generator.go:121 +0x1ed
github.com/cockroachdb/cockroach/pkg/storage/metamorphic.runMetaTestForEngines({{0x1e22758, 0x2d58080}, 0xc00014cb60, 0x1, 0xc421b172049efb2, 0x1, {0x0, 0x0}, {0x1e08080, 0xc0000ec3b8}, ...})
  github.com/cockroachdb/cockroach/pkg/storage/metamorphic/meta_test.go:92 +0x3e5
github.com/cockroachdb/cockroach/pkg/storage/metamorphic.runMetaTest.func2(0xc00014cb60)
  github.com/cockroachdb/cockroach/pkg/storage/metamorphic/meta_test.go:163 +0x5c5
testing.tRunner(0xc00014cb60, 0xc0005d8730)
  GOROOT/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 68
  GOROOT/src/testing/testing.go:1742 +0x390
```

CI failure from a nil pointer in `Options.String`

**Review by aadityasondhi — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121147#-:-Nu-ZW9NCrj8uL-IzRb6:b-ydi9ay)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by aadityasondhi** [comment]
I will merge this with https://github.com/cockroachdb/cockroach/pull/121138 instead.

bors r-

**Pull request merged**
