### PR TITLE
util/log: refactor and bug fixes

### LINKED ISSUE #40973: log: the Intercept() mechanism only works for the main log
The log package provides an `Intercept()` function used by the "logspy" debug endpoint.

At this time `Intercept()` only redirects logging to the main logger. Secondary loggers (SQL audit log, statements, RocksDB) are not intercepted.

Presumably we want interception to work across all loggers simultaneously.

cc @tbg

### LINKED ISSUE #40974: log: the log GC does not work for secondary loggers
There's a channel `gcNotify` in each logger object, both main and secondary.

Today when _any_ logger creates a new file it tickles the `gcNotify` of the main logger, which then proceeds to GC just the main logger. 

So the secondary loggers do not get GC'ed.

### LINKED ISSUE #40983: log: the cluster ID is only printed on the main log file
The code was meant to output the cluster ID on every log file, including those generated for secondary loggers, but due to an oddity/bug in the code only the main logger produces it.

cc @tbg

### PR DESCRIPTION
**Pull request by knz**
Fixes #40983.
Fixes #40973.
Fixes #40974.
Fixes #41231.

I might also want to add code to clean up #40972, #40982 and #40990 provided I receive some guidance from @tbg or someone familiar with the log package.

### CODE REVIEW

**Comment by knz** [comment]
Added a commit to use `sync.Pool` as recommended by @petermattis .

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @tbg)

___
*[pkg/util/log/clog.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40993#-LrAVo327U_2qlwXq9Gy:-LrAVo327U_2qlwXq9Gz:byo7bfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/56e5ad2e1b26972e8f80cbf9f246f09752ed1fc2/pkg/util/log/clog.go#L43)):*
> ```Go
> 
> 	// pool for entry formatting buffers.
> 	bufPool sync.Pool
> ```

I would make this a global. All of the loggers should be sharing a single `sync.Pool`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/util/log/clog.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40993#-LrAVo327U_2qlwXq9Gy:-LrK9PYyEChtbzEFDTui:b-6s4qrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/56e5ad2e1b26972e8f80cbf9f246f09752ed1fc2/pkg/util/log/clog.go#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I would make this a global. All of the loggers should be sharing a single `sync.Pool`.
</blockquote></details>

It is global now. The `loggingT` is now used for the common singleton, and there is a separate per-logger `loggerT`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/util/log/clog.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40993#-LrAVo327U_2qlwXq9Gy:-LrKBH276TIyUvUl-tb4:bxhiufc) ([raw file](https://github.com/cockroachdb/cockroach/blob/56e5ad2e1b26972e8f80cbf9f246f09752ed1fc2/pkg/util/log/clog.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It is global now. The `loggingT` is now used for the common singleton, and there is a separate per-logger `loggerT`.
</blockquote></details>

Ah, I missed that. Very good. Carry on.

**Review by tbg — APPROVED** [review]
:lgtm: I did not review the code movement in depth.

> Reviewed 7 of 26 files at r1, 20 of 20 files at r4, 18 of 18 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40993#-:-LrOw65X71yOz0FWMos5:b-hvt1cr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
thank you!

bors r+

**Pull request merged**
