### PR TITLE
sql: refactor unnecessary bookkeeping of every type in tuples when type checking ANY/ALL operations

### PR DESCRIPTION
**Pull request by richardwu**
In #18094, I introduced an intermediary step where we keep track of all the types in a tuple such that we can verify there exists a comparison function between each element and the left expression.

I forgot to remove this unnecessary bookkeeping after introducing a helper method that type checks and requires every element in a tuple be equivalent to the left.

As pointed out by @knz in #18094 (https://reviewable.io/reviews/cockroachdb/cockroach/18094#-Kt3dEQawKw2PgHNgpGq), I should have reverted this back to the original style: https://github.com/cockroachdb/cockroach/pull/18094/files#diff-f5c8f9ab30e6b17710413b03d2169349L1019.

### CODE REVIEW

**Comment by justinj** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/suboperators, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtO-7oF9opmhKFk1LPc:-KtO-7oF9opmhKFk1LPd:b-1gfwle) ([raw file](https://github.com/cockroachdb/cockroach/blob/f945f5fb40d942ace154b76a2ae3ef2db69a541d/pkg/sql/logictest/testdata/logic_test/suboperators#L261)):*
> ```
> SELECT 1 = ALL(ARRAY['foo', 'bar'])
> 
> query error unsupported comparison operator: <int> = ALL <string\[\]>
> ```

how come this change? these errors seemed more helpful before to me.

---

*[pkg/sql/parser/type_check.go, line 1047 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtO0RC6niMqCPJ_KDaa:-KtO0RC6niMqCPJ_KDab:bxq3vu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/12bdae3122a74489513f0c9fedcd51f5b03bf685/pkg/sql/parser/type_check.go#L1047)):*
> ```Go
> 		case TTuple:
> 			if len(rightUnwrapped) == 0 {
> 				// Literal tuple or tuple from subquery contains no elements.
> ```

kind of unfortunate that we can't handle this case :/ (since it has a definite answer as long as there's some overload matching the left side), but I guess there's complications with the typing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271)*

**Comment by richardwu** [comment]
*[pkg/sql/logictest/testdata/logic_test/suboperators, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtO-7oF9opmhKFk1LPc:-KtOKr8P4mFI6ORdH0df:b-de5bp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f945f5fb40d942ace154b76a2ae3ef2db69a541d/pkg/sql/logictest/testdata/logic_test/suboperators#L261)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

how come this change? these errors seemed more helpful before to me.
</blockquote></details>

Good point. I naively followed what the previous codepath did with these error messages, but it only handled arrays before whereas now tuples are also supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271)*

**Comment by richardwu** [comment]
*[pkg/sql/parser/type_check.go, line 1047 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtO0RC6niMqCPJ_KDaa:-KtOMO18vg4lK-dc7YMh:b-uvtc0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/12bdae3122a74489513f0c9fedcd51f5b03bf685/pkg/sql/parser/type_check.go#L1047)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

kind of unfortunate that we can't handle this case :/ (since it has a definite answer as long as there's some overload matching the left side), but I guess there's complications with the typing.
</blockquote></details>

One option is to move checking for empty tuples to `typeCheckAndRequireTupleElems`, but this would be a different behavior than the other type checking methods. This case in fact only covers literal tuples since subqueries are verified for 1 and only 1 column during `analyzeExpr` (analyze.go). I've updated the comment to reflect that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271)*

**Comment by knz** [comment]
LGTM modulo comment request

---

Reviewed 1 of 2 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 1052 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtRIwD6LXzevP-QTx0J:-KtRIwD6LXzevP-QTx0K:b-hxzk6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3a82812ec2752a82680cf4003a951d6c5204d6/pkg/sql/parser/type_check.go#L1052)):*
> ```Go
> 				return nil, nil, CmpOp{}, subOpCompError(cmpTypeLeft, rightReturn, subOp, op)
> 			}
> 			cmpTypeRight = rightUnwrapped[0]
> ```

Add a comment here to remind the reader why rightUnwrapped never contains more than 1 element.
Also, it's perhaps worth extending the condition above so that it also serves as an assertion this is true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-:-KtRJ8VNR26S1AF4imo1:b-ez7edx)*

**Comment by richardwu** [comment]
*[pkg/sql/parser/type_check.go, line 1052 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271#-KtRIwD6LXzevP-QTx0J:-KtRZY92SxU4Bb7MkEWw:b-rk55vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d3a82812ec2752a82680cf4003a951d6c5204d6/pkg/sql/parser/type_check.go#L1052)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add a comment here to remind the reader why rightUnwrapped never contains more than 1 element.
Also, it's perhaps worth extending the condition above so that it also serves as an assertion this is true.
</blockquote></details>

Well rightUnwrapped would contain more than 1 element if it's a literal tuple (but all elements will have been type inferred to equivalent types).

I've added a comment to reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18271)*

**Pull request merged**
