### PR TITLE
[DNM] storage: introduce SST snapshot strategy

### LINKED ISSUE #16954: storage: use IngestExternalFile instead of WriteBatches for applying snapshots
Sending a snapshot of a range currently involves generating a series of 256KB `WriteBatches` which are then applied on the recipient. Per the recent work to use the RocksDB `IngestExternalFile` functionality for restore, it would likely be significantly faster on the recipient to send an sstable instead. Using `IngestExternalFile` for applying snapshots should be straightforward in comparison to the usage within restore as we don't have any of the complexity of Raft involved. The sender can create the sstable locally and then stream it to the recipient. And because we send a header before streaming the snapshot, we can probe whether the recipient supports receiving an sstable snapshot which will make the migration story easier.

There is no particular urgency here as applying snapshots is not currently a bottleneck. 

@danhhz Do you have benchmark numbers readily available showing the performance difference between `IngestExternalFile` and applying the equivalent `WriteBatches`?

### PR DESCRIPTION
**Pull request by nvb**
Fixes #16954.
Related to #25047.

This depends on the following two upstream changes to RockDB:
- facebook/rocksdb#3778
- facebook/rocksdb#3779

The change introduces a new snapshot strategy called "SST". This strategy
stream sst files consisting of all keys in a range from the sender to the
receiver. These sst files are then atomically ingested directly into RocksDB.
An important property of the strategy is that the amount of memory required
for a receiver using the strategy is constant with respect to the size of
a range, instead of linear as it is with the KV_BATCH strategy. This will
be critical for increasing the default range size and potentially for
increasing the number of concurrent snapshots allowed per node. The
strategy also seems to significantly speed up snapshots once ranges are
above a certain size (somewhere in the single digit MBs).

This is a WIP change. Before it can be merged it needs:
- to be cleaned up a bit
- more testing (unit test, testing knobs, maybe some chaos)
- proper version handling
- heuristic tuning
- decisions on questions like compactions after ingestion

### CODE REVIEW

**Comment by bdarnell** [comment]
This generally looks good so far (although some of these methods are getting huge and ought to be split up). It's unfortunate that this is a large amount of new code instead of replacing the old code paths. I assume the reason we can't just use the SST strategy all the time is that the extra I/O from writing multiple SSTs adds up. Would it make sense to postprocess the received SSTs into either a single large SST or a KV batch (if the total size is small enough) so we could phase out the old KV batch paths. 

---

Reviewed 1 of 1 files at r1, 9 of 13 files at r2, 4 of 4 files at r3, 10 of 10 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[c-deps/libroach/include/libroach.h, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNA7-y4ALgFX4j9Xf4:-LBNA7-y4ALgFX4j9Xf5:b-y2pxf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/c-deps/libroach/include/libroach.h#L367)):*
> ```objc
> // if the underlying RocksDB blocks have not been flushed. Close cannot have
> // been called.
> DBStatus DBSstFileWriterTruncate(DBSstFileWriter* fw, DBString* data);
> ```

s/Truncate/Flush/, if I'm understanding this correctly. 

---

*[pkg/storage/replica_command.go, line 1878 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNI-sL5hwlMoPOBVUR:-LBNI-sL5hwlMoPOBVUS:bas7txc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_command.go#L1878)):*
> ```Go
> 	}
> 
> 	// TODO we should introduce a heuristic here for which snapshot strategy
> ```

Add your name to the TODO. 

---

*[pkg/storage/replica_command.go, line 1879 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNR8k01HgXNAVow9B0:-LBNR8k01HgXNAVow9B1:b-l9ahia) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_command.go#L1879)):*
> ```Go
> 
> 	// TODO we should introduce a heuristic here for which snapshot strategy
> 	// to use. An easy heuristic would be to use SST snapshots only when a
> ```

A heuristic like this risks being under-tested - I'm surprised that we have enough large snapshots in the test that this could make a difference. We may need to have some way to run all the tests with each strategy. 

---

*[pkg/storage/replica_raftstorage.go, line 872 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNKvmM-dwIegO9KZ_L:-LBNKvmM-dwIegO9KZ_M:blgjw7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_raftstorage.go#L872)):*
> ```Go
> 		stats.commit = timeutil.Now()
> 	case *sstSnapshotStrategy:
> 		// TODO DURING REVIEW: do we need to worry about RaftTombstoneIncorrectLegacyKey here?
> ```

I hope not since everything should be migrated before this version is introduced, but @tschottdorf should confirm. 

---

*[pkg/storage/replica_raftstorage.go, line 972 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNNo4C-DgbhQhBNH-w:-LBNNo4C-DgbhQhBNH-x:b-e560f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_raftstorage.go#L972)):*
> ```Go
> 		}
> 
> 		// TODO should we force a compaction? Only in the global keyspace? The
> ```

We should probably add a suggestion to the compaction queue. I think forcing a compaction is going to negate a lot of the benefit of the sst ingestion strategy. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-:-LBNQG9Y8jqxKCdvEZnL:b-iwllaa)*

**Comment by nvanbenschoten** [comment]
> I assume the reason we can't just use the SST strategy all the time is that the extra I/O from writing multiple SSTs adds up. 

That and because it would be slower and result in a lot of small SSTs, which doesn't sound like a good idea.

> Would it make sense to postprocess the received SSTs into either a single large SST or a KV batch (if the total size is small enough) so we could phase out the old KV batch paths.

We could use a `RocksDBSstFileReader` to postprocess the received SSTs into a KV batch if the total size is small enough. I don't think that would be a great idea though, because it would still require us to write the SSTs to disk instead of buffering all KVs in memory if the snapshot is below a certain size.

I don't see the two snapshot strategies as a huge issue for a few reasons. The first is that we're still going to need to support the KV batch approach in the short-term because of mixed version clusters. We also know that the KV batch approach is stable, so keeping it doesn't seem like a very big liability. My biggest concern is testing, which as you mention will need to be comprehensive for both approaches. We could have a testing hook that forces senders to use both strategies and asserts that they both result in the same exact resulting range.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[c-deps/libroach/include/libroach.h, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNA7-y4ALgFX4j9Xf4:-LCjwJ3rEUmnsPM7IiY1:bongf34) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/c-deps/libroach/include/libroach.h#L367)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/Truncate/Flush/, if I'm understanding this correctly. 
</blockquote></details>

It actually doesn't flush (since there aren't good hooks into the underlying `BlockBasedTableBuilder`), it only truncates what's already been flushed to the inMem env. This is discussed further in `TestRocksDBSstFileWriterTruncate`.

---

*[pkg/storage/replica_command.go, line 1878 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNI-sL5hwlMoPOBVUR:-LCk89rO8IjNBMbtH6od:b-6avpqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_command.go#L1878)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add your name to the TODO. 
</blockquote></details>

This was a TODO for this PR. I'm going to revisit it when all prerequisite ROcksDB changes have been merged.

---

*[pkg/storage/replica_raftstorage.go, line 872 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNKvmM-dwIegO9KZ_L:-LCjw8q19xgNl0xdhzJO:b7qvhxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_raftstorage.go#L872)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I hope not since everything should be migrated before this version is introduced, but @tschottdorf should confirm. 
</blockquote></details>

That was my understanding as well, but I was hoping for confirmation.

---

*[pkg/storage/replica_raftstorage.go, line 972 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-LBNNo4C-DgbhQhBNH-w:-LCjwDf5CleB0WH6SbmY:bb9zixc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2881a8f91753be0b0722352fdeb05cef2e259044/pkg/storage/replica_raftstorage.go#L972)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should probably add a suggestion to the compaction queue. I think forcing a compaction is going to negate a lot of the benefit of the sst ingestion strategy. 
</blockquote></details>

Adding a suggestion to the compaction queue sounds like the right approach to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-:-LCjx1bV-IsiImIaU5E1:bqb3hr5)*

**Comment by bdarnell** [comment]
> We could use a RocksDBSstFileReader to postprocess the received SSTs into a KV batch if the total size is small enough. I don't think that would be a great idea though, because it would still require us to write the SSTs to disk instead of buffering all KVs in memory if the snapshot is below a certain size.

This is fixable if we want to go in this direction. We could either make a custom `rocksdb::Env` that supports ingesting from in-memory buffer or (perhaps simpler) just decode the sst directly instead of going through all the rocksdb ingestion machinery.

**Comment by nvanbenschoten** [comment]
> This is fixable if we want to go in this direction.

I'm not convinced that we do because I think that direction would add a lot of new logic in an effort to remove stable old logic. Sure, doing this would allow us to remove one of the two strategies on-the-wire (once we no longer need to worry about compatibility), but it would still require two different code paths to apply the snapshot on the receiver's side, which is the part that changes more often and is harder to test. With everything considered and after the migration period finished in 2.2, I think we would just be going through extra hoops to send SSTs over the wire instead of KVs in the cases where we already know we want to write KVs in WriteBatches on the receiver anyway.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25134#-:-LD3QEibDRiatab5UZHn:b-mdix8m)*

**Comment by benesch** [comment]
Are we planning to open source the AddSSTable command or will this be CCL binaries/enterprise licenses only?

**Comment by benesch** [comment]
Oh, never mind. I guess this doesn't actually use AddSSTable.

**Comment by nvanbenschoten** [comment]
https://github.com/cockroachdb/cockroach/pull/32931 just merged, which includes the RocksDB changes necessary for this change. @tbg what do you think we should do with this PR? Do you have any desire to see it adopted in the 2.2 release cycle?

**Pull request closed without merging**
