### PR TITLE
sql: capture timeout settings in explain bundles

### PR DESCRIPTION
**Pull request by rafiss**
Epic: CRDB-38033
Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122721#-:-NvsNUFM8PvS3d3tSpvC:b-ae66e1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
bors r-

oops missed the test

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
