### PR TITLE
 changefeedccl: deflake TestAlterChangefeedAddTargetsDuringBackfill

### LINKED ISSUE #120744: ccl/changefeedccl: TestAlterChangefeedAddTargetsDuringBackfill failed
ccl/changefeedccl.TestAlterChangefeedAddTargetsDuringBackfill [failed](https://tanzanite.cluster.engflow.com/invocations/default/ed4c1d3d-62fb-4e38-9fa4-6341741d7fc0?testReportRun=3&testReportShard=8&testReportAttempt=1#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0) on master @ [f0116ea373a2b87155e7f0264df4f783ce177360](https://github.com/cockroachdb/cockroach/commits/f0116ea373a2b87155e7f0264df4f783ce177360):

```
=== RUN   TestAlterChangefeedAddTargetsDuringBackfill
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestAlterChangefeedAddTargetsDuringBackfill1577098480
    test_log_scope.go:81: use -show-logs to present logs inline
    alter_changefeed_test.go:1449: -- test log scope end --
test logs left over in: outputs.zip/logTestAlterChangefeedAddTargetsDuringBackfill1577098480
--- FAIL: TestAlterChangefeedAddTargetsDuringBackfill (184.01s)
=== RUN   TestAlterChangefeedAddTargetsDuringBackfill/enterprise
    helpers_test.go:867: making server as system tenant
    helpers_test.go:943: making enterprise feed factory
    helpers_test.go:957: pgURL enterprise root
    helpers_test.go:682: waiting for checkpoint
    helpers_test.go:682: waiting for checkpoint
    helpers_test.go:682: waiting for checkpoint
    helpers_test.go:685: read checkpoint spans:<key:"\362\211\366\232\210" end_key:"\362\211\366\333\210" > timestamp:<wall_time:1710925058292374311 > 
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:697: waiting for highwater
    helpers_test.go:704: could not read highwater
    --- FAIL: TestAlterChangefeedAddTargetsDuringBackfill/enterprise (184.00s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=3</code>
 - <code>shard=8</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestAlterChangefeedAddTargetsDuringBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-36850

### PR DESCRIPTION
**Pull request by andyyang890**
This patch deflakes `TestAlterChangefeedAddTargetsDuringBackfill`
by increasing the max batch size used for changefeed initial scans.
Previously, if we were unlucky, the batch sizes could be too small
leading to a timeout while waiting for the initial scan to complete.

Fixes #120744

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120812)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120812#-NtpzAPcCACe53FCXV3-:-NtpzAPcCACe53FCXV30:b7k7sgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/531d82c342cb0f98347e38bf66b87ae080f7413b/pkg/ccl/changefeedccl/alter_changefeed_test.go#L1355)):*
> ```Go
> 			// the initial scan to take too long, leading to the waitForHighwater
> 			// call below to time out.
> 			b.Header.MaxSpanRequestKeys = maxBatchSize/2 + rndMu.rnd.Int63n(maxBatchSize/2)
> ```

How did you decide on this formula?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120812)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120812#-NtpzAPcCACe53FCXV3-:-Ntq-pq_2-2Iw_aWffhc:b-8ex2in) ([raw file](https://github.com/cockroachdb/cockroach/blob/531d82c342cb0f98347e38bf66b87ae080f7413b/pkg/ccl/changefeedccl/alter_changefeed_test.go#L1355)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

How did you decide on this formula?
</blockquote></details>

It's arbitrary but it'll guarantee a much bigger max batch size than before while still preserving the fact that there will be multiple batches.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120812#-:-NtqABzM6eHyoOyYL18B:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120812#-NtpzAPcCACe53FCXV3-:-Ntq9mS52EjgJE3z6MzR:b7ejnw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/531d82c342cb0f98347e38bf66b87ae080f7413b/pkg/ccl/changefeedccl/alter_changefeed_test.go#L1355)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

It's arbitrary but it'll guarantee a much bigger max batch size than before while still preserving the fact that there will be multiple batches.
</blockquote></details>

Can you add brief comments here and where we set `maxBatchSize` with the rationale and what the expected effect will be? Arbitrary is ok, but that should be clear to the next person who may have to tweak this.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120812)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 1355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120812#-NtpzAPcCACe53FCXV3-:-NtrINCu28I2w-8LG8C5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/531d82c342cb0f98347e38bf66b87ae080f7413b/pkg/ccl/changefeedccl/alter_changefeed_test.go#L1355)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can you add brief comments here and where we set `maxBatchSize` with the rationale and what the expected effect will be? Arbitrary is ok, but that should be clear to the next person who may have to tweak this.
</blockquote></details>

Done.

**Comment by andyyang890** [comment]
TFTR!

bors r=rharding6373

**Pull request merged**
