### PR TITLE
storage: Skip TestSystemZoneConfigs when running race detector

### PR DESCRIPTION
**Pull request by a-robinson**
Touches #30483

Release note: None

### CODE REVIEW

**Comment by m-schneider** [comment]
:lgtm:

**Comment by tschottdorf** [comment]
LGTM, but we've gotta fix that data race first... ;-)

**Comment by a-robinson** [comment]
So you'd prefer to wait until the data race is fixed before doing this? My gut would be to go ahead and merge this to stop flakes, similar to skipping a flaky test before a fix is found.

**Comment by tschottdorf** [comment]
Fine by me, if it's on your queue next (once we skip it and never see the flake again, it'll slip).

**Comment by a-robinson** [comment]
Fair, it's not next on my queue. I'll hold off for now.

**Comment by tschottdorf** [comment]
Thanks. You could also merge this as an unconditional skip, but that's only mildly better. I'm happy triaging a few extra test failures if I know in exchange that it'll be taken care of in the near future.

**Comment by a-robinson** [comment]
With https://github.com/cockroachdb/cockroach/pull/31631 now going in as a fix for `TestSystemZoneConfigs`, have we still been seeing timeouts in this test lately @tschottdorf? If not let's just close this.

**Comment by petermattis** [comment]
I haven't seen timeouts on this test in my stressing. I'd be fine with closing this out.

**Comment by tschottdorf** [comment]
👍

**Pull request closed without merging**
