### PR TITLE
changefeedccl: add mvcc_timestamp option

### PR DESCRIPTION
**Pull request by stevendanna**
This revives @HonoreDB's demo of a non_logical_updated option.

Overall, the point of this feature is to allow changefeed consumers to
take action based on row age during an initial backfill. Changefeed
consumers may want to ignore backfill'd rows older some pre-defined
timestamp.

Emitting this extra timestamp allows them to do this filtering at the
expense of sending more data over the wire when not backfilling rows.

In our discussion of this, no one was in love with the name
non_logical_updated. Thus, I've changed this field name to
mvcc_timestamp and added a small test.

* Alternatives

1. Provide an explicit, non-SQL means of limiting what gets emitted
   during backfills. This could be in the form of an option such as
   `backfill_max_age` which would drop any rows older than the provided
   timestamp.  This, however, would not allow the consumer to make
   more complicated decisions about the older data downstream (for
   example, perhaps they want to partially process old data). Further,
   it would add filtering based on mvcc_timestamp as a special case
   that we need to support even if we develop more sophisticated
   predicate filtering.

2. Provide a general way of filtering messages. For example, if the
   user could run:

       CREATE CHANGEFEED FOR foo WHERE crdb_internal_mvcc_timestamp >
       $1 INTO 'kafka://bar'

   This wouldn't allow for more dynamic downstream decisions, but would
   also avoid the special-case nature of alternative 1.

3. Provide a general way of selecting columns for emissions. For
   example, if the user could run something like:

       CREATE CHANGEFEED FOR (SELECT *, crdb_internal_mvcc_timestamp
       FROM foo) INTO 'kafka://bar'

   They could then make decisions based on the rows mvcc timestamp
   without the explicit new option added in this PR.

I think that in the long run we would like something like both 2 and
3. However, providing a means by which the user can get the actual
MVCC timestamp of rows in the near term will allow users to handle the
filtering they need downstream until we have the more sophisticated
features.

Release note (enterprise change): Changefeed's can now be started with
the `mvcc_timestamp` option to emit the mvcc timestamp of each row
being emitted. This option is similar to the `updated` option, but the
`mvcc_timestamp` will always contain the row's mvcc timestamp, even
during the changefeed's initial backfill.

### CODE REVIEW

**Comment by stevendanna** [comment]
@HonoreDB @miretskiy @amruss Revived this for discussion.  I tried to write up some of the alternatives we have considered.  Given the low-overhead of emitting the timestamp, I think it is probably worth doing something like this to help some of the users who need it while we work on the longer-term solutions.  WDYT?

**Review by miretskiy — APPROVED** [review]
I like this new name.  This PR :lgtm: to me.  I'll let @amruss to be the final arbiter.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65661#-:-MbGdNsG5r8q1AA5BqHQ:b-jz08nh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB)

**Review by HonoreDB — APPROVED** [review]
Thanks for the rez! I'm fine with this if Abbey is.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65661#-:-MbflpgyACfmKkMGgkEN:bqxi09x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by stevendanna** [comment]
bors r=[miretskiy,HonoreDB]

**Pull request merged**
