### PR TITLE
cli: add userfile get command

### PR DESCRIPTION
**Pull request by dt**
`userfile get` fetches the file or files that match the supplied path,
path prefix or glob-style path pattern to the current working directory.

Release note (cli change): `userfile get` can be used to fetch files from a cluster.

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/cli/userfile.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHDL67tFkZiOuWpRS:-MTIHDL67tFkZiOuWpRT:b20kqbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L72)):*
> ```Go
> 	Long: `
> Fetch the files stored in the user scoped file storage which match the provided pattern,
> using a SQL connection, to the current directory or 'destination' if provided. If destination
> ```

stray `if destination...`
___
*[pkg/cli/userfile.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHi2O2GctJTvSh_yK:-MTIHi2O2GctJTvSh_yL:b-2lmoxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L407)):*
> ```Go
> 
> 	// os.Create uses a permissive 0666 mode so use OpenFile directly.
> 	localFile, err := os.OpenFile(dst, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0600)
> ```

how would slashes be handled in dst? Could we upload a file from unix like system and the file name may contain `\` and then try downloading it to windows?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/cli/userfile.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHi2O2GctJTvSh_yK:-MTIbOVo2oOUyxRh5gwD:b-6inaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L407)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

how would slashes be handled in dst? Could we upload a file from unix like system and the file name may contain `\` and then try downloading it to windows?
</blockquote></details>

if you look up at where we pick dst, you'll see it is either `filepath.FromSlash(u.Path)` (for multi-file downloads) or `filename := path.Base(u.path)` (for single-file downloads), so there shouldn't be any non-platform matching slashes in it. We don't have a windows CI. also, I thought that windows has been happy to use either separator for a while now?

**Review by stevendanna — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/cli/userfile.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIpTL72v4bwbZAPZnu:-MTIpTL85QmJRdbDEXbG:b-p5g3y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L77)):*
> ```Go
> 	Args:    cobra.MinimumNArgs(1),
> 	RunE:    maybeShoutError(runUserFileGet),
> 	Aliases: []string{"ls"},
> ```

I don't think we want this Alias
___
*[pkg/cli/userfile.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHi2O2GctJTvSh_yK:-MTItS_DDwMTM1-PaCyo:b-fpcj3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L407)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

if you look up at where we pick dst, you'll see it is either `filepath.FromSlash(u.Path)` (for multi-file downloads) or `filename := path.Base(u.path)` (for single-file downloads), so there shouldn't be any non-platform matching slashes in it. We don't have a windows CI. also, I thought that windows has been happy to use either separator for a while now?
</blockquote></details>

I think @miretskiy is pointing at the fact that the only reserved character for unix filenames is `/` while windows filenames have many more reserved characters.  Notably, `\` is a valid character in a filename for unix files but may (I don't know windows well) be interpreted as a path separator in windows, which would then result in this writing the file to different locations depending on which operating system it was running on.

Additionally, since userfile allows other characters that may be a problem on windows:

```
./cockroach userfile list
foo><:"\|
```

I think there are likely to always be some cases where a windows user may need to specify a single-file download to avoid naming issues.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/cli/userfile.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHDL67tFkZiOuWpRS:-MThWRxT9aSPErYwxpkY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L72)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

stray `if destination...`
</blockquote></details>

Done.
___
*[pkg/cli/userfile.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIpTL72v4bwbZAPZnu:-MThWSwS1flDxuufyFJL:b-aiavw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L77)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I don't think we want this Alias
</blockquote></details>

Whoops, nice catch.
___
*[pkg/cli/userfile.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MTIHi2O2GctJTvSh_yK:-MTIcIWoAMZHE3qgg0Bd:bbmo0oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1501f08e13e8ed07898a20fce5b9fbf40f006736/pkg/cli/userfile.go#L407)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think @miretskiy is pointing at the fact that the only reserved character for unix filename's is `/` while windows filesnames have many more reserved characters.  Notably, `\` is a valid character in a filename for unix files but may (I don't know windows well) be interpreted as a path separator in windows, which would then result in this writing the file to different locations depending on which operating system it was running on.

Additionally, since userfile allows other characters that may be a problem on windows:

```
./cockroach userfile list
foo><:"\|
```

I think there are likely to always be some cases where a windows user may need to specify a single-file download to avoid naming issues.
</blockquote></details>

Ah, yeah, I see. Yeah, I think you're right: as long as we're more permissive in our file names than the client's fs, they may need to specify a local file name. I'm... okay with this I think?

**Comment by dt** [comment]
Are we okay with the window filename situation? anything else left to do here?

**Comment by stevendanna** [comment]
> Are we okay with the window filename situation?

I think it is OK. Personally, I would expect a `get` command to write out the content to the exact filename that exists in the database. I then get the file at a location that matches the rules of the filesystem I'm using or an error.  I am less familiar with the expectations of Windows users. 

The only two solutions I've though of are either doing some path normalisation when writing or restricting the allowed filenames on the way in.  Normalisation seems problematic because it (1) may surprise some users, (2) might not be necessary/correct for the given _filesystem_ we are talking to, regardless of platform and (3) is an unending chase (I imagine windows isn't the only problem.  For example, userfile is case sensitive which could also produce some unexpected behaviour on `get` for macOS users).  Input restrictions might be more reasonable, but almost surely would be independent of the `get` command.

**Review by stevendanna — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-:-MU97kzv3ahQQPFtMBzs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @stevendanna)

___
*[pkg/cli/userfile.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MU97R4a7mtyo2SEQ3Xt:-MU97R4a7mtyo2SEQ3Xu:b-hu3e0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f0a1e7e11a0d9077c8e35b3c04e948ef6dec801/pkg/cli/userfile.go#L238)):*
> ```Go
> 			return err
> 		}
> 		fmt.Printf("\rdownloaded %s to %s (%s)\n", file, fileDest, humanizeutil.IBytes(sz))
> ```

Do we ever change output based on whether we are connected to a TTY? If so, I suppose it could be nice to avoid writing the carriage returns if we are writing to a file.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[pkg/cli/userfile.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-MU97R4a7mtyo2SEQ3Xt:-MU9CUSXCQdoSXELMdGR:b-e0k4iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f0a1e7e11a0d9077c8e35b3c04e948ef6dec801/pkg/cli/userfile.go#L238)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we ever change output based on whether we are connected to a TTY? If so, I suppose it could be nice to avoid writing the carriage returns if we are writing to a file.
</blockquote></details>

we use isatty to check stdin but AFAIK not stdout. I think I'm okay with the output including them -- if someone _really_ doesn't want them a quick `sed` would do the trick?

**Review by dt — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60490#-:-MU9sACv2soiPSY9dBVj:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

**Pull request merged**
