### PR TITLE
server: add diagnostics report endpoint

### PR DESCRIPTION
**Pull request by dt**
This admin endpoint returns an anonymous diagnostics report, generated via the same collection
logic as is used during background diagnositcs reporting. This lets users inspect an example report
from their own cluster to see what it contains or potentially even collect and use that information
themselves.

Release note (general change): add a debug endpoint that returns an anonymized diagnostics report.

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM, but please add a release note.

Also, as a follow up, can you add the endpoint to the debug landing page?

**Comment by knz** [comment]
ditto what Bram said about the release note. Also, this could use a test.

**Comment by dt** [comment]
oh, and added a release note (though this doesn't seem particularly note-worthy to me?).

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24813#-:-LAEXazUCPZbWm3Wfs8B:bnfp4nl)*

**Comment by dt** [comment]
added link

**Comment by BramGruneir** [comment]
LGTM

As discussed, if you want to allow it to get info from any node, by passing in the node id as part of the URL, it's easy to do but you'll have to move the proto to `status.proto` instead of `admin.proto` and the code from `admin.go` to `status.go` and call the dialNode function.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24813#-:-LAEsd_sCryKiAy2atQs:b-b4muvc)*

**Pull request merged**
