### PR TITLE
roachtest: don't panic when writing to a closed logger, various logger fixes

### LINKED ISSUE #39706: cmd/roachtest: panic "file already closed" from logger.Printf
From https://teamcity.cockroachdb.com//viewLog.html?buildId=1441311&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildLog&_focus=6090:

```
[12:23:30][Step 2/2] test returned error: import/tpch/nodes=4: test timed out and afterwards failed to respond to cancelation
[12:23:38][Step 2/2] import/tpch/nodes=8 (43s)
[12:23:47][Step 2/2] panic: write /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190816-1441311/import/tpch/nodes=4/run_1/test.log: file already closed
[12:23:47][Step 2/2] 
[12:23:47][Step 2/2] goroutine 10080 [running]:
[12:23:47][Step 2/2] main.(*logger).PrintfCtxDepth(0xc00165c6c0, 0x38c70a0, 0xc000060070, 0x2, 0xc0003aef00, 0x52, 0x0, 0x0, 0x0)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/log.go:254 +0xd7
[12:23:47][Step 2/2] main.(*logger).Printf(...)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/log.go:243
[12:23:47][Step 2/2] main.(*test).printAndFail(0xc0009290e0, 0x2, 0xc0004d9f20, 0x1, 0x1)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:269 +0x140
[12:23:47][Step 2/2] main.(*test).fatalfInner(0xc0009290e0, 0x0, 0x0, 0xc0004d9f20, 0x1, 0x1)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:255 +0xb3
[12:23:47][Step 2/2] main.(*test).Fatal(0xc0009290e0, 0xc0004d9f20, 0x1, 0x1)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:242 +0x51
[12:23:47][Step 2/2] main.(*monitor).Wait(0xc0003b81e0)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2099 +0xcb
[12:23:47][Step 2/2] main.registerImportTPCH.func1(0x38c7060, 0xc0005f9880, 0xc0009290e0, 0xc000020960)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/import.go:187 +0x620
[12:23:47][Step 2/2] main.(*testRunner).runTest.func2(0xc000b041e0, 0xc0009290e0, 0x38c7060, 0xc0005f9880, 0xc000020960)
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:674 +0x7d
[12:23:47][Step 2/2] created by main.(*testRunner).runTest
[12:23:47][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:670 +0x516
```

Looks like there is some badness in handling timeouts. @nvanbenschoten made a stab at fixing this in https://github.com/cockroachdb/cockroach/pull/39645. The above test run was from 720a6605f182c4459c56f055c23e805d48b89344 which includes #39645.

### PR DESCRIPTION
**Pull request by ajwerner**
This PR was motivated by #39706. It comes in 4 commits.

1) refactor similar logic in `printAndFail()` and `printfAndFail()` to share code (drive-by cleanup)
2) don't panic if writing to the logger fails, this is too brittle for relatively untested critical infrastructure like roachtest
3) don't close the test logger until after we're done writing to it. There was a case where we'd close it and proceed to use it.
4) don't call `Fatal()` from a monitor if the test has already failed. 

Fixes #39706.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
LGTM to unblock things, but shouldn't we really just make sure a closer logger doesn't fatal? It seems that with our current handling of test timeouts it'll be difficult to make sure this doesn't occasionally happen. What keeps a test from calling `l.Printf`?

**Review by andreimatei — COMMENTED** [review]
I think indeed we should make printing to a closed logger not panic. Instead it can yell to stdout. Or an alternative is to make the Logger maintain a refcount internally and have two refererences - one in the test runner, one in the test itself - and have `Close()` actually close the file only when both are released.

But also it seems to me that the current code is obviously broken. I think maybe it has gotten such after some refactoring (or maybe I had always screwed up).
We close a test's logger here:
https://github.com/cockroachdb/cockroach/blob/e7df44ec0569e58f76dc660824268b29a616ade9/pkg/cmd/roachtest/test_runner.go#L455
and then we immediately print stuff to its logger here
https://github.com/cockroachdb/cockroach/blob/e7df44ec0569e58f76dc660824268b29a616ade9/pkg/cmd/roachtest/test_runner.go#L460
Was this the call that generated the panic in this case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39707#-:-LmPrjha6hb0Kouq7PyV:brtnuum)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by ajwerner** [comment]
I've reworked this. Now it won't panic if logging fails. Additionally I refactored the printAndFail code to share more code. lastly I moved the closing of the test logger for the case @andreimatei pointed out. The fourth commit detects the case where the test has already failed and doesn't attempt to fail again (I suspect this is the root problem).

> What keeps a test from calling l.Printf?

I didn't fix this. This is about getting the lifetimes right. In the roachtest rewrite there's now a whole bunch of loggers. Each cluster has a logger. Each test has a logger. Each monitor has a logger. Here the monitor is outliving the test but then is attempting to call Fatal on that test. I think the idea was that by giving the monitor it's own logger with its own lifetime we'd avoid the scenario we're in. The problem is that there's a dependency on the test's logger via the test's methods. Now that we don't panic we're going to become less aware of this type of bug. Perhaps we ought to record the stack where we close loggers and then when we detect writes to a closed logger print the current stack and the closed stack to help debug. 

> Was this the call that generated the panic in this case?

No, the issue was that the monitor attempted to call t.Fatal after the test failed:

https://github.com/cockroachdb/cockroach/blob/e7df44ec0569e58f76dc660824268b29a616ade9/pkg/cmd/roachtest/cluster.go#L2099

called here

https://github.com/cockroachdb/cockroach/blob/e7df44ec0569e58f76dc660824268b29a616ade9/pkg/cmd/roachtest/import.go#L47

I added logic to detect cases where the test might have already failed though it feels like there's still a race. Eliminating the panic should help. 

> But also it seems to me that the current code is obviously broken. I think maybe it has gotten such after some refactoring (or maybe I had always screwed up).

Seems to have always been that way. That being said, it's only a problem if the test returned an error but wasn't marked as failed. It's not clear that that happens. The third commit fixes this case.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39707#-:-Lmfj7y83scsqvLB9wjk:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
bors r=andreimatei

**Pull request merged**
