### PR TITLE
Add PutInline to the KV client and use to store node status

### PR DESCRIPTION
**Pull request by spencerkimball**
This prevents counter-productive version explosions on node status
summaries. We are interested in the history of node statuses but that
information is already captured better by our metrics time series.
Writing a new node status every 10s with endlessly repeated build info
was putting pressure on a single range splitting, despite having only
versions for a single key.

See issue #5501

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5595)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/batch.go, line 252 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo7r8emUgQ7xyPNG8_:-KDo7r8emUgQ7xyPNG8a:-945234465) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/batch.go#L252)):*
This seems a little strange but I see why it's needed. Consider moving the inline constructor logic into `roachpb.NewPut` to avoid this (either as another parameter or another function). The reason those functions all return `Request` interfaces is to separate concerns.

---

*[storage/replica_command.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo6zhvipsZyrGYev07:-KDo6zhvipsZyrGYev08:1937273344) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/replica_command.go#L208)):*
It probably has the same effect, but for symmetry with the MVCC layer, I'd change this to `ts := roachpb.ZeroTimestamp`.

---

*[storage/engine/mvcc.go, line 946 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo6-D_ybmSZxwcn2Vf:-KDo6-D_ybmSZxwcn2Vg:-146612932) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc.go#L946)):*
s/with/within/

---

*[storage/engine/mvcc_test.go, line 707 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo657CjdUQUTKM454n:-KDo657DaRL_e5agpa-2:-1844297748) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc_test.go#L707)):*
Consider `if err := ...; err != nil {` throughout.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/batch.go, line 269 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo874eaODvgh_jGW83:-KDo874eaODvgh_jGW84:-1760059381) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/batch.go#L269)):*
double period

---

*[client/client_test.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo8IPUc1zhMNTTxd9R:-KDo8IPUc1zhMNTTxd9S:1947534673) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/client_test.go#L365)):*
mixing %v and %s

---

*[storage/engine/mvcc.go, line 683 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo8eOfND_uGg7k09qs:-KDo8eOfND_uGg7k09qt:-1100595923) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc.go#L683)):*
old version seems more accurate?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595)*

**Comment by tschottdorf** [comment]
:lgtm: mod comments.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[client/batch.go, line 269 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDoec3ow6Bjc4_KQd3U:-KDoec3ow6Bjc4_KQd3V:1648299880) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/batch.go#L269)):*
It also can't be mutated transactionally. In particular, any `DeleteRange` will fail when there's an inline value anywhere. So, basically, warn against using this "just for fun".

---

*[client/db.go, line 242 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDoeyNJgr4Mbc2H-DC6:-KDoeyNJgr4Mbc2H-DC7:-1677837463) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/db.go#L242)):*
ditto.

---

*[client/txn.go, line 242 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDof-IKgQh98im7fGM1:-KDof-IKgQh98im7fGM2:-1553552475) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/txn.go#L242)):*
This method should not even exist.

---

*[storage/engine/mvcc_test.go, line 730 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDofSTZAzJnxwQai4do:-KDofSTZAzJnxwQai4dp:1204592112) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc_test.go#L730)):*
always check the specific error: `testutils.IsError`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-:-KDofd2WujRrFr2hdwmB:-1927687667)*

**Comment by spencerkimball** [comment]
Review status: 5 of 13 files reviewed at latest revision, 11 unresolved discussions.

---

*[client/client_test.go, line 365 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo8IPUc1zhMNTTxd9R:-KDogRSYW_7i2wP8Y0DL:-1116166910) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/client_test.go#L365)):*
Fixed this one and others in this file.

---

*[storage/engine/mvcc.go, line 683 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo8eOfND_uGg7k09qs:-KDoh0Vt6XQcXMdY83a-:-625685580) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc.go#L683)):*
I don't understand the comment.

---

*[client/txn.go, line 242 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDof-IKgQh98im7fGM1:-KDogZbbxQuVzRrQIjp_:1988756434) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/client/txn.go#L242)):*
Oops good point! Removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595)*

**Comment by tschottdorf** [comment]
Review status: 5 of 13 files reviewed at latest revision, 10 unresolved discussions.

---

*[storage/engine/mvcc.go, line 683 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595#-KDo8eOfND_uGg7k09qs:-KDomJ5MgwEsFRn6mJU3:1344340701) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea952d34cd59527f044bbaeab1d9d622c670e9b/storage/engine/mvcc.go#L683)):*
The old comment said the `txn` is also irrelevant. That seems true.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5595)*

**Pull request merged**
