### PR TITLE
ui: remove polling from fingerprints pages, allow new stats requests while one is in flight

### PR DESCRIPTION
**Pull request by xinhaoz**
See individual commits.

The changes here serve as a base for the performance improvements we'll be making.
Since they're not really related to those changes specifically (e.g. adding limit/sort and splitting the api calls), I've put them in their own PR here to make reviewing easier.

Loom verifying behaviour and showing new requests being dispatched while ones are pending
Pages shown:
- stmt fingerprints
- txn fingerprints
- txn fingerprint details
- stmt fingerprint details

https://www.loom.com/share/3448117bfecf404c8d698f4ad1240e8c

CC:
https://www.loom.com/share/bb30b51ebe5144528ab0c6fabdbfb2f1

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ6zT7KBXTMCCzGEn_R):*
nit: experiences
___
*[`-- commits` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ6zc7K3E7dtw6YDhQ3):*
nit: this phrase is confusing
___
*[`-- commits` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ6zzZl5yYltfOa4ZoN):*
nice!
___
*[`pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts` line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ7-22E9kbJGzy7lMaQ:-NQ7-22E9kbJGzy7lMaR:b-hu9zby) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d517dcdb9f864862599f5a01ea0dd2efa4f87c1/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L324)):*
> ```XML
>       this.pendingRequest = request;
> 
>       return request;
> ```

can you add test to confirm the behaviour and/or a loom showing network tab before/after?

**Comment by xinhaoz** [comment]
I have to do some testing on CC still. I'll add that Loom once it is done.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`-- commits` line 6 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVH9ym4Lh_lBhe3ZC5):*
nit: typo `finegerprints`
___
*[`-- commits` line 29 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVHSd15u_W2mspzfWw):*
Should this be labeled SQL Activity pages instead of fingerprint pages? 
___
*[`-- commits` line 31 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVIPeg22o7b1kYSUSx):*
Should a refresh/apply button be added to the page to make it clear that it's not refreshing?
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 212 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVIgsO2EyHRq_jL43a:-NQVIgsO2EyHRq_jL43b:b-e0p792) ([raw file](https://github.com/cockroachdb/cockroach/blob/57eaea1e0b5a8bed7cf4b594fe179e58b216f4df/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L212)):*
> ```XML
> 
>   refreshData = (): void => {
>     console.log("aaaaaaaaaaah");
> ```

nit: I think this might need to be removed..
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 782 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVJA1q03WHaw4XWB49:-NQVJA1q03WHaw4XWB4A:bu407gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/57eaea1e0b5a8bed7cf4b594fe179e58b216f4df/pkg/ui/workspaces/db-console/src/util/api.ts#L782)):*
> ```XML
>   return timeoutFetch(
>     serverpb.StatementsResponse,
>     `${STATUS_PREFIX}/combinedstmts?${queryStr}`,
> ```

Is this a new api?  If so should it be a concern this will likely break during upgrades?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dongniwang, @j82w, and @maryliag)

___
*[`-- commits` line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ6zc7K3E7dtw6YDhQ3):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: this phrase is confusing
</blockquote></details>

Rephrased.
___
*[`-- commits` line 6 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVH9ym4Lh_lBhe3ZC5):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: typo `finegerprints`
</blockquote></details>

Fixed.
___
*[`-- commits` line 29 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVHSd15u_W2mspzfWw):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this be labeled SQL Activity pages instead of fingerprint pages? 
</blockquote></details>

I wanted to distinguish them from insights pages / active exec pages, I can change it SQL Activity if it's more clear though. 
___
*[`-- commits` line 31 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVIPeg22o7b1kYSUSx):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should a refresh/apply button be added to the page to make it clear that it's not refreshing?
</blockquote></details>

Sounds like a good idea -- cc @dongniwang  
___
*[`pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx` line 212 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVIgsO2EyHRq_jL43a:-NQVQEPR5sgXVFBeTfiS:b-xrerli) ([raw file](https://github.com/cockroachdb/cockroach/blob/57eaea1e0b5a8bed7cf4b594fe179e58b216f4df/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L212)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

nit: I think this might need to be removed..
</blockquote></details>

Oops, removed.
___
*[`pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts` line 324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ7-22E9kbJGzy7lMaQ:-NQVQHVTDR6lcH9mySry:b-p5umyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d517dcdb9f864862599f5a01ea0dd2efa4f87c1/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L324)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add test to confirm the behaviour and/or a loom showing network tab before/after?
</blockquote></details>

Loom added.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 782 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVJA1q03WHaw4XWB49:-NQVQIlU1Ugcjnmg6guF:bvjrthr) ([raw file](https://github.com/cockroachdb/cockroach/blob/57eaea1e0b5a8bed7cf4b594fe179e58b216f4df/pkg/ui/workspaces/db-console/src/util/api.ts#L782)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is this a new api?  If so should it be a concern this will likely break during upgrades?
</blockquote></details>

It's not a new api. It existed since the creation of persisted stats from 21.2, we just did not use it and instead opted to have the older api just route to this one using a req param in case we needed to revert anything. We're fully committed to persisted stats now though so I don't see why we shouldn't be using it.

**Review by maryliag — APPROVED** [review]
on this PR you removed the polling on txn details, is the removal on stmt details being done on a separate PR? Just wanna make sure if not forgotten. It can be a separate PR for easy review, since this one is already big.

Besides the typos on the commit message I mentioned previously :lgtm: 

> Reviewed 16 of 16 files at r5, 21 of 21 files at r6, 10 of 14 files at r7, 1 of 2 files at r8, 3 of 8 files at r10, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-:-NQ_gB2g1VDFgZ1tlZJu:b7n4s8h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dongniwang, @j82w, and @xinhaoz)

___
*[`-- commits` line 30 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQRPAHy1KsCwzTDuJ4B):*
nit: action
___
*[`-- commits` line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQRPI_D7L-Eyz3TEXMj):*
nit: In the future, we should remove... (without the `now`)

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dongniwang, @maryliag, and @xinhaoz)

___
*[`-- commits` line 29 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQVHSd15u_W2mspzfWw):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I wanted to distinguish them from insights pages, I can change it SQL Activity if it's more clear though. 
</blockquote></details>

I would prefer to go with the names in the ui to avoid confusion. 
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 650 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ_2uoN1G_jGBjBY8Ci:-NQ_2uoN1G_jGBjBY8Cj:b-ddhwfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b15c3bd22f1a6d627c24606aa2874720858a201/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L650)):*
> ```XML
>           />
>           {this.props.isReqInFlight &&
>             getValidErrorsList(this.props.statementsError) == null &&
> ```

Would it be better to just do `getValidErrorsList(this.props.statementsError) &&` to handle undefined?

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 650 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-NQ_2uoN1G_jGBjBY8Ci:-NQaJUsQ2dVIg5jGq_AA:b1sfhag) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b15c3bd22f1a6d627c24606aa2874720858a201/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L650)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Would it be better to just do `getValidErrorsList(this.props.statementsError) &&` to handle undefined?
</blockquote></details>

`== null` captures both null and undefined.

**Comment by xinhaoz** [comment]
Addressed typos. The refresh data button will be deferred since we're going to be updating the UI with limit and sort soon.

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98331#-:-NQeXXi66e99fRdFd3dg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dongniwang, @maryliag, and @xinhaoz)

**Pull request merged**
