### PR TITLE
catalog/descs: allow caching of system.rangelog

### PR DESCRIPTION
**Pull request by ajwerner**
We write to the rangelog any time we do a replication change or a split
or merge. A replication change will write *4* entries (learner, promote,
demote, gone). We were looking up the descriptor on every single write.

I could see not publishing the release note.

Might be the fix for https://github.com/cockroachdb/cockroach/issues/35293.

Release note (performance improvement): Reduce number of round-trips required
to make low-level replication changes which improves scalability of replication
changes in large, global clusters.

### CODE REVIEW

**Comment by ajwerner** [comment]
cc @aayushshah15

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by ajwerner** [comment]
Oh no, this one has bootstrapping problems :see_no_evil:

**Comment by ajwerner** [comment]
We don't use sql here anymore.

**Pull request closed without merging**
