### PR TITLE
sql: implement SQL-compliant DROP PROCEDURE

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Addresses: #100405.
Epic: CRDB-30611

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that only the last two commits should be reviewed here - all others are #120851.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work tracking down all that complexity!

> Reviewed 21 of 21 files at r1, 19 of 19 files at r2, 8 of 8 files at r3, 38 of 38 files at r4, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120856#-:-Nt_S8JaBKRV7BJaYHJ8:bu2fxzf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r1, 19 of 19 files at r2, 8 of 8 files at r3, 38 of 38 files at r4, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120856#-:-NtaOpfN3kAvK-IPJ_Z4:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
