### PR TITLE
colflow: finish spans created by the outboxes

### PR DESCRIPTION
**Pull request by yuzefovich**
Addresses: #58721

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58741#-:-MQqICZFDX5FJ-kvl0A_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by irfansharif** [comment]
Sorry about that, I just came across it. It's increasingly going to be an anti-pattern to Finish() a span after grabbing the recording. I realize that's not at all what we do today in lots of places, but will be the world we're moving towards. For this PR, I made the relevant changes in https://github.com/cockroachdb/cockroach/pull/58712/files, in a way that follows that pattern. Sorry for the noise, I think we can close this.

**Comment by yuzefovich** [comment]
Oh ok, thanks.

**Pull request closed without merging**
