### PR TITLE
blobs: enforce disabled external-io-dir

### PR DESCRIPTION
**Pull request by dt**
The `nodelocal` cloud storage implementation previously did its own
file IO, and checked for and enforced the ExternalIODirectory, including
checking when it was disabled completely ("").

However after the switch to backing `nodelocal` with the local-or-remote
blob service, this enforcement now needs to be done in that service,
when it actually goes to do local IO,  as it is a per-node decision if
and where to allow IO.

Release note (security update): ensure --external-io-dir=disabled applies to `nodelocal upload` requests as well.

Release justification: Bug fix.

Separately: add a zero-byte write at the end of upload to ensure any errors in the pipe are flushed (otherwise zero-byte files never saw errors).

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM but I'd like to see a test that COPY does the right thing now too.

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45858#-:-M1wPmzy0IHz5OGQQ3Rt:bheoc48)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/blobs/local_storage.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45858#-M1wPaqX5A5meBd1MpsR:-M1wPaqX5A5meBd1MpsS:b7ffhd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0f457139cb14b84b3f501a45171918cd8878e6f/pkg/blobs/local_storage.go#L58)):*
> ```Go
> func (l *LocalStorage) prependExternalIODir(path string) (string, error) {
> 	if l == nil {
> 		return "", errors.Errorf("local file access is disabled")
> ```

might be worth defining the error object as a global var so as to enable `errors.Is()` elsewhere.
___
*[pkg/sql/copy_file_upload.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45858#-M1wPUC16Of2bv6AQZSP:-M1wPUC2-5B65S78SIM4:b-guue8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a4cb8c2a254fbb8afa022f11047ceadc48b4d88/pkg/sql/copy_file_upload.go#L146)):*
> ```Go
> 	}
> 
> 	// Issue a final zero-byte write to ensure we observe any errors in the pipe.
> ```

This feels like it could use a test.

**Review by knz — COMMENTED** [review]
I would also recommend a `Release note (security update): ...` which would outline the overall security rules for nodelocal/COPY. That would ensure it lands in the right place in docs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45858#-:-M1wPtTt202mwihncY2Y:b-hynsu3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45858)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @knz)

___
*[pkg/sql/copy_file_upload.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45858#-M1wPUC16Of2bv6AQZSP:-M1wPzEy9WzqeBu9KvpY:b-m8xnf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a4cb8c2a254fbb8afa022f11047ceadc48b4d88/pkg/sql/copy_file_upload.go#L146)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This feels like it could use a test.
</blockquote></details>

that's what the `empty` file case is above: https://github.com/cockroachdb/cockroach/blob/b0f457139cb14b84b3f501a45171918cd8878e6f/pkg/cli/nodelocal_test.go#L62

**Comment by knz** [comment]
Oh I see I had missed that `nodelocal upload` was implemented using COPY :sweat_smile: 
carry on. LGTM

**Comment by dt** [comment]
bors r=knz

**Pull request merged**
