### PR TITLE
sql/catalog/lease: break lease.go up, adopt nstree for nameCache

### PR DESCRIPTION
**Pull request by ajwerner**
Extracted from a larger change to leasing. Feels self-contained and good.

### CODE REVIEW

**Comment by ajwerner** [comment]
First commit is just code movement.

**Review by fqazi — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/lease/descriptor_state.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66958#-MdHrU1dAQV5IgX_Epz9:-MdHrU1dAQV5IgX_EpzA:b-3ustjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c533be728ea6451aa16b58808cc350c90a66f3a/pkg/sql/catalog/lease/descriptor_state.go#L239)):*
> ```Go
> 		s.mu.refcount--
> 		if log.V(2) {
> 			log.VEventf(context.TODO(), 2, "release: %s", s.stringLocked())
> ```

Shouldn't this be just ctx?
___
*[pkg/sql/catalog/lease/descriptor_version_state.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66958#-MdHroW60cRQJQE7YeuU:-MdHroW60cRQJQE7YeuV:b4tcdeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c533be728ea6451aa16b58808cc350c90a66f3a/pkg/sql/catalog/lease/descriptor_version_state.go#L119)):*
> ```Go
> 	s.mu.Lock()
> 	s.incRefcountLocked()
> 	s.mu.Unlock()
> ```

Nit: Just defer

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/descriptor_state.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66958#-MdHrU1dAQV5IgX_Epz9:-MdIEZYBBkqD1EL6alyf:bmi0b1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c533be728ea6451aa16b58808cc350c90a66f3a/pkg/sql/catalog/lease/descriptor_state.go#L239)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Shouldn't this be just ctx?
</blockquote></details>

Done. Also fixed another TODO().
___
*[pkg/sql/catalog/lease/descriptor_version_state.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66958#-MdHroW60cRQJQE7YeuU:-MdIEcXE-FLArn3Cmk3n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c533be728ea6451aa16b58808cc350c90a66f3a/pkg/sql/catalog/lease/descriptor_version_state.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Just defer
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r=fqazi

**Pull request merged**
