### PR TITLE
pkg/server: Expose LSM visualization on debug pages.

### PR DESCRIPTION
**Pull request by miretskiy**
Expose LSM visualization on AdminUI /debug pages.

### CODE REVIEW

**Comment by miretskiy** [comment]
@petermattis  This PR will not run cleanly since it depends on pebble change I sent in https://github.com/cockroachdb/pebble/pull/646

I just wanted to provide context for pebble change, and give you an idea on the direction I decided to go with when integrating pebble tool w/ the debug admin UI.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @petermattis)

___
*[pkg/server/debug/server.go, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6UpBZk2atWPMZEjuRb:-M6UpBZk2atWPMZEjuRc:bmixfai) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L189)):*
> ```Go
> 	manifestPath := path.Join(dir, string(bytes.TrimSpace(manifestName)))
> 
> 	t := pebbletool.New()
> ```

I think I mentioned this elsewhere, but it is a bit inelegant to call `pebbletool.New()` only to extract the "lsm" tool. Perhaps we should add a `pebbletool.NewLSM()`. Fine to leave this suggestion as a TODO.
___
*[pkg/server/debug/server.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6Uo9J19Du4evbtYX2z:-M6Uo9J23u3Xd6Q2KUlL:bkfjlw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L206)):*
> ```Go
> }
> 
> func (ds *Server) AddLSMVisualizationDebugForEngines(id int, spec base.StoreSpec) {
> ```

`id` isn't the store ID or the node ID or any ID inside CRDB. Instead, it is the index of the store in the store specs passed on the command line. I see why you did it this way, but I think that will make usage of this a bit burdensome. I have a very strong preference for `id` to refer to the actual store ID.

I don't know The Right Way to achieve this, but I'd take a look at `statusServer.EngineStats` or one of the other status endpoints which retrieve info for a particular node ID. I'm not sure if there are any status endpoints that retrieve info for a particular store ID.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/server/debug/server.go, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6UpBZk2atWPMZEjuRb:-M6UqueC9Z56Yq2aD3SA:b34nos9) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L189)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think I mentioned this elsewhere, but it is a bit inelegant to call `pebbletool.New()` only to extract the "lsm" tool. Perhaps we should add a `pebbletool.NewLSM()`. Fine to leave this suggestion as a TODO.
</blockquote></details>

I started off with adding accessor to LSM command directly.
Even with that I had to add a wrapper (like NewLSM) to the tool since lsmT has private methods.
That wrapper took "io.Writer" as a parameter.  At that point, I realized that I don't need to have
any accessors if I have access to the Command itself.

Also, exposing LSM directly, I felt I'd be exposing a lot of internal implementation details.
Accessing command was a low impact change -- an easy to just pass in  a writer instead of stdout

TODO added.
___
*[pkg/server/debug/server.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6Uo9J19Du4evbtYX2z:-M6Wo7VAESJIz30uLvf4:baisfc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`id` isn't the store ID or the node ID or any ID inside CRDB. Instead, it is the index of the store in the store specs passed on the command line. I see why you did it this way, but I think that will make usage of this a bit burdensome. I have a very strong preference for `id` to refer to the actual store ID.

I don't know The Right Way to achieve this, but I'd take a look at `statusServer.EngineStats` or one of the other status endpoints which retrieve info for a particular node ID. I'm not sure if there are any status endpoints that retrieve info for a particular store ID. 
</blockquote></details>

I'm not sure what "The Right Way" is either.  I did find a way to do it, but not 100% on whether it's okay.  Take a look.  Let me know.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/server/debug/server.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6Uo9J19Du4evbtYX2z:-M6X5EcW26aDjh2T8eEI:b8d1hzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L206)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure what "The Right Way" is either.  I did find a way to do it, but not 100% on whether it's okay.  Take a look.  Let me know.
</blockquote></details>

My knowledge of the server startup procedure is out of date. I know @tbg has been mucking in this area recently. Perhaps he can give some guidance on how to hook up a store specific debug endpoint.

**Comment by miretskiy** [comment]
@tbg  do you mind taking a look at this pr?
I'm trying to expose a debug url, and I need to get the store id.  Not sure if what I'm doing right now is "the right way" to go about doing this.

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/server/debug/server.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6Uo9J19Du4evbtYX2z:-M6ZKJtpAjJMMy1LYhi_:bvn3oqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L206)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My knowledge of the server startup procedure is out of date. I know @tbg has been mucking in this area recently. Perhaps he can give some guidance on how to hook up a store specific debug endpoint.
</blockquote></details>

This is fine. It could be made better but that would require some refactoring that I don't want to put on your plate.

**Comment by miretskiy** [comment]
Can I have a stamp from either @petermattis or @tbg ?  I still need to bump pebble version before I will be able to merge this pr.

**Review by petermattis — COMMENTED** [review]
@miretskiy Do you have any thoughts about exposing the presence of this debug page on the `Advanced Debug` page? Keeping it completely hidden is unfortunate. But because the page is keyed by store ID, adding the right links to the `Advanced Debug` page may be a bit difficult to plumb.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-:-M6_Rlsc2MqgF3Hda1hi:b-h3ja65)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @petermattis)

___
*[pkg/server/debug/server.go, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6_Oht4-S_DxFZA3SVB:-M6_Oht4-S_DxFZA3SVC:bwa6cfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2741ad8afb7afc876d06a026ff638244a92f55/pkg/server/debug/server.go#L209)):*
> ```Go
> }
> 
> func (ds *Server) AddLSMVisualizationDebugForEngines(
> ```

Nit: it is mildly repetitive to put `Debug` in the method name given that this is the `debug.Server`. I'd go with a name like `debug.Server.RegisterEngines` as I'd like to see more engine specific debug info exposed in the future.
___
*[pkg/server/debug/server.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6_Poh8AWtX_F9rPZFP:-M6_Poh8AWtX_F9rPZFQ:b-kng2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2741ad8afb7afc876d06a026ff638244a92f55/pkg/server/debug/server.go#L216)):*
> ```Go
> 	}
> 	for i := 0; i < len(specs); i++ {
> 		if specs[i].InMemory {
> ```

Add a TODO here that we could support in-memory engines with a bit more plumbing in the LSM visualization tool. I think a bit more plumbing would allow us to get rid of the `specs` argument as well, because each engine knows its directory, we just don't provide an accessor for it.

**Review by miretskiy — COMMENTED** [review]
I honestly have not looked at it (yet?).  Another venue of improvement might be hooking this via _status server endpoint -- to be able to retrieve visualization for external nodes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-:-M6_n7Ko1TLXKB416GU9:brjub5k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/server/debug/server.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6Uo9J19Du4evbtYX2z:-M6_nHpy-jxk7WZQvrL7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82f338bade1df6dc9e55ee8f6922fdf07d959270/pkg/server/debug/server.go#L206)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is fine. It could be made better but that would require some refactoring that I don't want to put on your plate.
</blockquote></details>

Done.
___
*[pkg/server/debug/server.go, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6_Oht4-S_DxFZA3SVB:-M6_nV1u4M1ULd6kamiv:b-cz0kqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2741ad8afb7afc876d06a026ff638244a92f55/pkg/server/debug/server.go#L209)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: it is mildly repetitive to put `Debug` in the method name given that this is the `debug.Server`. I'd go with a name like `debug.Server.RegisterEngines` as I'd like to see more engine specific debug info exposed in the future.
</blockquote></details>

Good idea and good name.  Done.
___
*[pkg/server/debug/server.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-M6_Poh8AWtX_F9rPZFP:-M6_nu3F1vZtxR1PogVD:b-llrbm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d2741ad8afb7afc876d06a026ff638244a92f55/pkg/server/debug/server.go#L216)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Add a TODO here that we could support in-memory engines with a bit more plumbing in the LSM visualization tool. I think a bit more plumbing would allow us to get rid of the `specs` argument as well, because each engine knows its directory, we just don't provide an accessor for it.
</blockquote></details>

Added 2 todos (1 for in mem + 1 to possibly add Path accessor to storage.Engine implementation.. I  did consider this, btw.  But the tee engine doesn't have a clean definition for path accessor)

**Comment by miretskiy** [comment]
@petermattis  Is it safe to bump pebble to latest version? or is there some process I should follow to do that?  I would like to pick up my change to see if this PR builds cleanly on CI

**Comment by petermattis** [comment]
> @petermattis Is it safe to bump pebble to latest version? or is there some process I should follow to do that? I would like to pick up my change to see if this PR builds cleanly on CI

Yes, it is safe to bump Pebble to the latest version. `bin/dep ensure -update github.com/cockroachdb/pebble` is the process to use. We include the `git log --oneline --no-merges` output of the Pebble commits in the Cockroach commit message. See https://github.com/cockroachdb/cockroach/pull/47788 for an example.

**Comment by miretskiy** [comment]
@petermattis  Sorry, this pr fell through about.  All comments addressed (i believe). CI build is clean.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48295#-:-M7bjtDEEnJMTsVOEvls:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

**Pull request merged**
