### PR TITLE
sqlsmith: Add multiregion syntax to sqlsmith

### LINKED ISSUE #65492: sqlsmith: add support for multi-region syntax to SQL smith
**Is your feature request related to a problem? Please describe.**

We currently have no coverage for multi-region abstractions introduced in 21.1 in SQL Smith. In particular, we don't have a "seed schema" that uses the multi-region abstractions for setup. We also don't have support for performing DDLs (Alters) on tables/databases that use the multi-region syntax. 

I'm not entirely sure how this works with ccl, as the mutliregion stuff requires a CCL binary to work. 

Epic CRDB-8948

### PR DESCRIPTION
**Pull request by RichardJCai**
Add sqlsmith testing for multiregion syntax.
Added support for

ALTER TABLE LOCALITY
ALTER DATABASE PRIMARY REGION
ALTER DATABASE ADD/DROP REGION

Release note: None

Resolves https://github.com/cockroachdb/cockroach/issues/65492

### CODE REVIEW

**Comment by rytaft** [comment]
Exciting to see this!

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqtnSup47U10Rt831N1:-MqtnSup47U10Rt831N2:bpyw9ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/cmd/roachtest/tests/sqlsmith.go#L303)):*
> ```Go
> 	}
> 	setups["seed-vec"] = sqlsmith.Setups["seed-vec"]
> 	setups = map[string]sqlsmith.Setup{
> ```



why redefine `setups` here? won't that wipe out the seed-vec key?
___
*[pkg/internal/sqlsmith/alter.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqtnZ3p5v6GhMeQ0dmS:-MqtnZ3p5v6GhMeQ0dmT:b-nfquh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/internal/sqlsmith/alter.go#L24)):*
> ```Go
> 
> var (
> 	alters               = append(append(append(altersTableExistence, altersExistingTable...), altersTypeExistence...), altersExistingTypes...)
> ```

i think `alterMultiRegion` needs to be added into this slice too maybe?
___
*[pkg/internal/sqlsmith/alter.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-Mqtnlg126OgFP5ZTt2n:-Mqtnlg126OgFP5ZTt2o:b-fmn26x) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/internal/sqlsmith/alter.go#L381)):*
> ```Go
> 	var region, zone string
> 	for rows.Next() {
> 		rows.Scan(&region, &zone)
> ```

maybe check for `err` here? or does sqlsmith just ignore all these errors already?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqtnSup47U10Rt831N1:-Mqttw2W4JL0i2G6LoNV:b-8ytekd) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/cmd/roachtest/tests/sqlsmith.go#L303)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why redefine `setups` here? won't that wipe out the seed-vec key?
</blockquote></details>

Oops shoot I forgot to remove this, was using this for testing, will update
___
*[pkg/internal/sqlsmith/alter.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqtnZ3p5v6GhMeQ0dmS:-Mqttb0J7XdRi6DFZrf0:bpwq9co) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/internal/sqlsmith/alter.go#L24)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think `alterMultiRegion` needs to be added into this slice too maybe?
</blockquote></details>

I left this out of this slice since we don't want the `alterMultiRegions` outside of when the multi-region setting is used so its set separately (only when the `MultiRegionDDLs` opt is set)

```
var MultiRegionDDLs = simpleOption("include multiregion DDLs", func(s *Smither) {
	s.alterWeights = append(s.alterWeights, alterMultiregion...)
})
```
___
*[pkg/internal/sqlsmith/alter.go, line 381 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-Mqtnlg126OgFP5ZTt2n:-Mqttswy5-2cv2KhPaNh:b-vghai0) ([raw file](https://github.com/cockroachdb/cockroach/blob/78097eb9ca8589644f3a55cc42b8b36c0c574132/pkg/internal/sqlsmith/alter.go#L381)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe check for `err` here? or does sqlsmith just ignore all these errors already?
</blockquote></details>

Yeah this needs a check I'll add it

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/internal/sqlsmith/alter.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-Mqv0XzvBgZdvwZewIdX:-Mqv0Xzw-UJmm0YvgLHi:b87qtvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b1ca221306cc6929c33f344f2583b2828845d8/pkg/internal/sqlsmith/alter.go#L381)):*
> ```Go
> 	var region, zone string
> 	for rows.Next() {
> 		rows.Scan(&region, &zone)
> ```

still needs the error check?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJFxm3gdamipP9MY8:-MqvJFxm3gdamipP9MY9:b-w7dfes) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L125)):*
> ```Go
> 			regionsSet := make(map[string]struct{})
> 			var region, zone string
> 			rows, _ := conn.Query("SHOW REGIONS FROM CLUSTER")
> ```

should we check the error instead of using `_`?
___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJCgD6C556pKiqt11:-MqvJCgD6C556pKiqt12:beo9e04) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L127)):*
> ```Go
> 			rows, _ := conn.Query("SHOW REGIONS FROM CLUSTER")
> 			for rows.Next() {
> 				rows.Scan(&region, &zone)
> ```

seems like this also needs an error check; missed this earlier.

**Comment by jordanlewis** [comment]
This is awesome! Could/should we also randomly make tables REGIONAL, REGIONAL BY ROW, and GLOBAL?

**Review by ajstorm — CHANGES_REQUESTED** [review]
I agree, awesome!

> This is awesome! Could/should we also randomly make tables REGIONAL, REGIONAL BY ROW, and GLOBAL?

I _think_ that's what's going on here: https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/internal/sqlsmith/alter.go#L414

Can we also add syntax for `PLACEMENT RESTRICTED`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-:-MqyNSCG9oVNRWsG7YLu:b-j2dxyb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/internal/sqlsmith/alter.go, line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqyNE6N83MfxbWdSiWY:-MqyNE6N83MfxbWdSiWZ:b4wizx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/internal/sqlsmith/alter.go#L415)):*
> ```Go
> 		Locality: &tree.Locality{
> 			LocalityLevel: tree.LocalityLevel(rand.Intn(3)),
> 			TableRegion:   tree.Name(regions[rand.Intn(len(regions))]),
> ```

Should this only be set if we're setting LocalityLevel to LocalityLevelTable?  Not sure if it matters.

**Review by RichardJCai — COMMENTED** [review]
Correct, that is for making the tables randomly REGIONAL, REGIONAL BY ROW, and GLOBAL. Made the code a bit more clear there.

Also added syntax for `ALTER DATABASE PLACEMENT`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-:-Mqyvlpw596r3ry24hqV:byifczt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @rafiss)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJFxm3gdamipP9MY8:-Mqyw-f54uviS5rikxi5:b-p9guej) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L125)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we check the error instead of using `_`?
</blockquote></details>

Fixed, was being lazy when I first wrote this
___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJCgD6C556pKiqt11:-Mqyw7Gb94VaNtdIqLU7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L127)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

seems like this also needs an error check; missed this earlier.
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/alter.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-Mqv0XzvBgZdvwZewIdX:-MqywFyn-zy6l6crBvpc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4b1ca221306cc6929c33f344f2583b2828845d8/pkg/internal/sqlsmith/alter.go#L381)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

still needs the error check?
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/alter.go, line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqyNE6N83MfxbWdSiWY:-Mqyw8XUDpYic9Z4lBiJ:b-1llm3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/internal/sqlsmith/alter.go#L415)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should this only be set if we're setting LocalityLevel to LocalityLevelTable?  Not sure if it matters.
</blockquote></details>

Don't think it matters since TableRegion is ignored if we're not `LocalityLevelTable` but I changed it so it only sets TableRegion if we're on `LocalityLevelTable`

**Review by ajstorm — COMMENTED** [review]
PLACEMENT changes look good.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-:-MqzWqCn1Hw527BI5q7s:b8151sd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/internal/sqlsmith/alter.go, line 415 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqyNE6N83MfxbWdSiWY:-MqzWTbiAk3xwtgCdUQe:bxp4t4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/internal/sqlsmith/alter.go#L415)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Don't think it matters since TableRegion is ignored if we're not `LocalityLevelTable` but I changed it so it only sets TableRegion if we're on `LocalityLevelTable`
</blockquote></details>

Thanks. Looks more intentional this way.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJFxm3gdamipP9MY8:-Mr32jZeE6Bc2PMzYKJB:b5sot8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L125)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Fixed, was being lazy when I first wrote this
</blockquote></details>

looks like this line still needs the error check

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73753)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/sqlsmith.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73753#-MqvJFxm3gdamipP9MY8:-Mr3BRPN97dX6HNqrxTI:bvn1ztv) ([raw file](https://github.com/cockroachdb/cockroach/blob/da608b0af8ce89d61e3ac532f6bc2102561c7c85/pkg/cmd/roachtest/tests/sqlsmith.go#L125)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

looks like this line still needs the error check
</blockquote></details>

🤦 Idk how I keep missing, I also updated two other instances of this

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by RichardJCai** [comment]
TFTR!
bors r=rafiss

**Pull request merged**
