### PR TITLE
opt: fix qualified star expansion after joins

### LINKED ISSUE #66123: sql: join with USING condition does not include all the output columns
**Describe the problem**

There is a rare constelation during which the column defined in a join is missing in the to_jsonb result

**To Reproduce**

```
CREATE TABLE  products (
    product_name TEXT,
    PRIMARY KEY (product_name)
);
CREATE TABLE  offers (
    offer_id TEXT,
    product_name TEXT,
    PRIMARY KEY (offer_id)
);
SELECT to_jsonb(products.*) as product , jsonb_agg(to_jsonb(offers.*)) as offers
FROM products
INNER LOOKUP JOIN offers
USING (product_name)
GROUP BY products.product_name;
```
Result I'm getting from the query:
`|{"product_name": "orange"}|[{"offer_id": "best orange"}]|`

**Expected behavior**
`|{"product_name": "orange"}|[{"offer_id": "best orange", "product_name": "orange"}]|`

**Environment:**
 - CockroachDB version 21.1.1
 - Server OS: Ubuntu 20.04
 - Client app `cockroach sql`

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: introduce "accessible by qualified star" column visibility in optbuilder

This commit extends `cat.Visibility` into a new `columnVisibility`
type and adds a new value for columns which are not visible by default
but are part of qualified star expansions (`<table_name>.*` aka "all
columns selector").

Release note: None

#### opt: fix qualified star expansion after joins

When using JOIN NATURAL/USING, the equality columns are visible in the
result only once. However, the original table columns are still
accessible by qualified star ("<table_name>.*"). These columns are
currently missing from the qualified star expansion.

This commit fixes this problem by making use of the new
`accessibleByQualifiedStar` visibility.

Fixes #66123.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Friendly ping.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-:-McFFuUk4nppONqQv_0X:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1541 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFChru6r-6BPfIcDT5:-McFChru6r-6BPfIcDT6:bhr65jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e227d05766a3170bd1b0286361a596b176214b/pkg/sql/opt/optbuilder/scope.go#L1541)):*
> ```Go
> 	for i := range s.cols {
> 		col := &s.cols[i]
> 		if col.name.MatchesReferenceName(n) && (col.visibility == cat.Visible || (col.visibility == cat.Hidden && allowHidden)) {
> ```

Nice cleanup here. This was a mess!
___
*[pkg/sql/opt/optbuilder/scope.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFCJ8Y9flshxHIcE-I:-McFCJ8Z0ETIIyADL7xj:bse55o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope.go#L1544)):*
> ```Go
> 			if col.visibility == visible {
> 				if col.table.ObjectName == "" {
> 					// Visible, anonymous source.  Only print the first one, since
> ```

do you also need to check if `moreThanOneCandidateFromAnonSource` is true here?
___
*[pkg/sql/opt/optbuilder/scope_column.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFCoSw5upqrUWhbmYJ:-McFCoSw5upqrUWhbmYK:bfozzb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope_column.go#L71)):*
> ```Go
> 
> // columnVisibility is an extension of cat.ColumnVisibility.
> // ColumnVisibility values can be converted directly.
> ```

nit: `ColumnVisibility` -> `cat.ColumnVisibility`?

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-:-McFMtEO1xod3umNm7I5:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope_column.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFI8KA5V-rMFcwmqre:-McFI8KA5V-rMFcwmqrf:b-pry61n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope_column.go#L72)):*
> ```Go
> // columnVisibility is an extension of cat.ColumnVisibility.
> // ColumnVisibility values can be converted directly.
> type columnVisibility int8
> ```

Is there any reason you use an `int8` here when `cat.ColumnVisibility` is a `uint8`? I suppose you could make `accessibleByQualifiedStart = columnVisibility(-1)` to make it impossible that it will equal a potential future 11th `cat.ColumnVisibility` constant. Probably super unlikely though.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/scope.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFCJ8Y9flshxHIcE-I:-McFdzQ5AdAeKyPSgPro:bfyu4c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope.go#L1544)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you also need to check if `moreThanOneCandidateFromAnonSource` is true here?
</blockquote></details>

I guess. This kind of hurts my head. I think that if there is a matching anon source, we must have multiple candidates, or resolution would have been successful. I will work on refactoring the resolution code to clean all this up.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFCJ8Y9flshxHIcE-I:-McGMlns5YuRm9nwu0lY:b-2lkiv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope.go#L1544)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I guess. This kind of hurts my head. I think that if there is a matching anon source, we must have multiple candidates, or resolution would have been successful. I will work on refactoring the resolution code to clean all this up.
</blockquote></details>

Ok, I think it's much better now, PTAL.
___
*[pkg/sql/opt/optbuilder/scope_column.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFI8KA5V-rMFcwmqre:-McGMcSY1lpHLFnfsSHp:b-ijza5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope_column.go#L72)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is there any reason you use an `int8` here when `cat.ColumnVisibility` is a `uint8`? I suppose you could make `accessibleByQualifiedStart = columnVisibility(-1)` to make it impossible that it will equal a potential future 11th `cat.ColumnVisibility` constant. Probably super unlikely though.
</blockquote></details>

No, didn't think about it at all. Changed to uint8.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice cleanup!

> Reviewed 5 of 5 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-:-McHGTy13m0yJ7PLt0Xp:b-d43tfz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHE_qcDwk9s6TGTdjc:-McHE_qd0pbIg4AxiWxO:b-780i8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L765)):*
> ```Go
> 	for ; s != nil; s, allowHidden = s.parent, false {
> 		// Keep track of a candidate for each class. See columnMatchClass.
> 		var candidates [hiddenMatch + 1]candidateColumn
> ```

nit: setting a `const numMatchClasses = hiddenMatch+1` and using it here might make this a bit easier to grok.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1549 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHFwMWDLl2joZ8bs9p:-McHFwMWDLl2joZ8bs9q:b-wbg8qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L1549)):*
> ```Go
> 			continue
> 		}
> 		var match bool
> ```

nit: add a comment here (or above the `for` loop or in the function comment) that explains that we're searching the scope's columns for the column with the given name and match class.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/scope.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHE_qcDwk9s6TGTdjc:-McHjDGx3BbsKRfmdidS:bsuqpic) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L765)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: setting a `const numMatchClasses = hiddenMatch+1` and using it here might make this a bit easier to grok.
</blockquote></details>

I improved this more. I realized that we only need to keep track of the candidate for the "best" class seen so far. PTAL
___
*[pkg/sql/opt/optbuilder/scope.go, line 1549 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHFwMWDLl2joZ8bs9p:-McHk-_V5mxBOaB4Qq4A:bw70df3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L1549)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add a comment here (or above the `for` loop or in the function comment) that explains that we're searching the scope's columns for the column with the given name and match class.
</blockquote></details>

Done. Also moved this method so it's next to the one that calls it.

**Review by rytaft — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 5 files at r3, 1 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-:-McJbMAR2N5nTPNZuEF1:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McFCJ8Y9flshxHIcE-I:-McJaTWd8s5WBeCE5gRg:bfcm5r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a48af4b5741815af31674686365dd0879d5a07aa/pkg/sql/opt/optbuilder/scope.go#L1544)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ok, I think it's much better now, PTAL.
</blockquote></details>

So much better!
___
*[pkg/sql/opt/optbuilder/scope.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHE_qcDwk9s6TGTdjc:-McHiHdk21NaiTfowd-r:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L765)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I improved this more. I realized that we only need to keep track of the candidate for the "best" class seen so far. PTAL
</blockquote></details>

Nice!

**Review by mgartner — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66380)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/scope.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66380#-McHE_qcDwk9s6TGTdjc:-McKSx6D64x5CSFs7K1t:bxztp5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ec3671eaa411100d2b94d657f17e249893098e/pkg/sql/opt/optbuilder/scope.go#L765)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Beautiful!

**Comment by RaduBerinde** [comment]
This cannot be cleanly backported to 20.2, which still uses just a `hidden` flag. Given that the issue existed for a long time and was reported by a 21.1 user, I will not backport until/unless someone needs it on 20.2.

**Pull request merged**
