### PR TITLE
ui: clusterviz qps & cpu sparklines

### PR DESCRIPTION
**Pull request by couchand**
A first pass at a sparkline for QPS.  Needs to be incorporated into the reskinning work @vilterp is doing, and there's some cleanup that could be done to the code (`UnwrapResults` anyone?).

screen shot 2018-02-14 at 10 51 27 am

### CODE REVIEW

**Comment by couchand** [comment]
Review status: 0 of 6 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BrNg2fQjK3FBmjzur:-L5BrNg2fQjK3FBmjzus:bvrs5tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L37)):*
> ```XML
>         usedCapacity={capacityUsed}
>         label={node.desc.address.address_field}
>         nodes={["" + node.desc.node_id]}
> ```

We do this stringify twice, maybe we could DRY it?  Or not, it's just a stringify.  Is this the best way to stringify?  Maybe it would be nicer looking as ````${node.desc.node_id}````.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 15 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BtMnpnoC4TzfVAtVm:-L5BtMnqQUKJ02h2rnc2:b-ngbsdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L15)):*
> ```XML
> 
> function renderSparkline(sel: d3.Selection<{ results: Datapoint[] }>) {
>   const { results } = sel.datum();
> ```

it would be great to unsingletonize this, so that in some beautiful, distant future we could render all the localities with a single bulk update

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BsLYT9gMOWlMUAOnQ:-L5BsLYUNgk5Bx8VLNQz:bjc8st) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L20)):*
> ```XML
>   const xScale = d3.scale.linear()
>     .domain(d3.extent(results, (d: Datapoint) => d.timestamp))
>     .range([1, 92]);
> ```

unmagicify

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BsMyUSBNC2WGRrVLN:-L5BsMyUSBNC2WGRrVLO:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L23)):*
> ```XML
>   const yScale = d3.scale.linear()
>     .domain(d3.extent(results, (d: Datapoint) => d.value))
>     .range([19, 1]);
> ```

ditto

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 25 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BsTIvzYrSFbgkUsVD:-L5BsTIvzYrSFbgkUsVE:bc66zq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L25)):*
> ```XML
>     .range([19, 1]);
> 
>   const drawPath = d3.svg.line<Datapoint>()
> ```

don't recreate on every render

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 30 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5Bt0BYLhMEMwEwR9wY:-L5Bt0BZObFT2GvxEbS9:bnl3cy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L30)):*
> ```XML
> 
>   const bg = sel.selectAll("rect")
>     .data([1]);
> ```

looks like d3 uses `[null]` in cases like this

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 36 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5Bscmf0VJ6iTC3NKqU:-L5Bscmf0VJ6iTC3NKqV:bapbvwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L36)):*
> ```XML
>     .append("rect")
>     .attr("width", 93)
>     .attr("height", 20)
> ```

maybe it would be better to pass these in as config?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 57 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5Btc8BUjbjpyJTGJCq:-L5Btc8BUjbjpyJTGJCr:b-esk187) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L57)):*
> ```XML
> const Sparkline = createChartComponent("g", renderSparkline);
> 
> class UnwrapResults extends React.Component<MetricsDataComponentProps> {
> ```

maybe make this an HOC?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BuWEObH1rK3aAyq9C:-L5BuWEObH1rK3aAyq9D:b-p0d9rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L64)):*
> ```XML
>     }
> 
>     const { datapoints } = data.results[0];
> ```

i think we'll want this to sum over all the `data.results` rows, pivoting by `timestamp`, once we query for the other query types

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BtzMvSEyiMjsA00FU:-L5BtzMvSEyiMjsA00FV:b-jlmmm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L77)):*
> ```XML
> }
> 
> export function QpsSparkline(props: QpsSparklineProps) {
> ```

maybe this should be an HOC? signature`(metricName: string) => React.Component<NodeId[]>`

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BtuVCZXGLUobstdmY:-L5BtuVDldiPXYkikcgo:bcu7hag) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L78)):*
> ```XML
> 
> export function QpsSparkline(props: QpsSparklineProps) {
>   const key = "qps-sparkline.nodes." + props.nodes.join(",");
> ```

there's probably a better key schema than this

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx, line 83 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BuIKbOd1xtIU75AxS:-L5BuIKcBodxGnS58KOP:b-sejn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/qpsSparkline.tsx#L83)):*
> ```XML
>     <MetricsDataProvider id={key}>
>       <UnwrapResults>
>         <Metric name="cr.node.sql.select.count" sources={props.nodes} nonNegativeRate />
> ```

yeah that's not good enough...

---

*[pkg/ui/src/views/shared/util/d3-react.tsx, line 12 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BsCl0dspiWVb83tmH:-L5BsCl0dspiWVb83tmI:bh28q47) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/src/views/shared/util/d3-react.tsx#L12)):*
> ```XML
> export default function createChartComponent<T>(containerTy: string, chart: Chart<T>) {
>   return class WrappedChart extends React.Component<T, {}> {
>     // TODO(couchand): not any
> ```

but what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618)*

**Comment by couchand** [comment]
Reviewed 1 of 2 files at r1, 1 of 5 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618)*

**Comment by couchand** [comment]
@vilterp i think this is ready to go, PTAL

**Comment by vilterp** [comment]
:lgtm: although now is probably a good time to replace the `XX`s next to the sparklines with the actual most recent values in those time series. Can be a separate PR if you want.

---

Reviewed 1 of 2 files at r1, 5 of 5 files at r3, 4 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BrNg2fQjK3FBmjzur:-L5K8XZIavpQFOPdwdkO:b-2mnyug) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L37)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

We do this stringify twice, maybe we could DRY it?  Or not, it's just a stringify.  Is this the best way to stringify?  Maybe it would be nicer looking as ````${node.desc.node_id}````.
</blockquote></details>

`node.desc.node_id.toString()` is what I've used other places — it's a `Long`, right?

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/sparkline.tsx, line 75 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5K9TNVdoT6p31JIXG-:-L5K9TNVdoT6p31JIXG0:b-71eu2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4870ec2bb836d0bbba575518e40b8f987111746f/pkg/ui/ccl/src/views/clusterviz/containers/map/sparkline.tsx#L75)):*
> ```XML
> }
> 
> export class SparklineMetricsDataComponent extends React.Component<MetricsDataComponentProps> {
> ```

this name is a bit weird; doesn't really suggest that it actually renders the sparkline. Then again, as we've discussed, the whole component hierarchy of this is weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-:-L5K9_4uraqVncpc_rRq:b-3pqfwf)*

**Comment by couchand** [comment]
I'll replace those XX after #22671 merges 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5BrNg2fQjK3FBmjzur:-L5KE-wn4TDAS_As-_Yy:b1s3erw) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2c6efb9195d99e59f4a92da1c295b1d63afcff/pkg/ui/ccl/src/views/clusterviz/containers/map/nodeView.tsx#L37)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

`node.desc.node_id.toString()` is what I've used other places — it's a `Long`, right?
</blockquote></details>

Nope, it's just a number.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/sparkline.tsx, line 75 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-L5K9TNVdoT6p31JIXG-:-L5KE4I3G27vW9NFvceC:btps1jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4870ec2bb836d0bbba575518e40b8f987111746f/pkg/ui/ccl/src/views/clusterviz/containers/map/sparkline.tsx#L75)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

this name is a bit weird; doesn't really suggest that it actually renders the sparkline. Then again, as we've discussed, the whole component hierarchy of this is weird.
</blockquote></details>

Yeah, it sucks.  I spent about ten minutes trying to hide this inside something else but was seeing really confusing errors so I decided not to bother.  Yes, this whole usage pattern is super strange.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22618#-:-L5KENbG-Z8W9NvBF1Q4:b860o1m)*

**Pull request merged**
