### PR TITLE
allocatorimpl: return why lease should be transferred

### PR DESCRIPTION
**Pull request by kvoli**
ShouldTransferLease` is used to determine whether a replica should be
enqueued for a later lease transfer. The reason the lease should be
transferred could be due to preferences, IO overload or balance. Include
the reason why the lease should be transferred, or why the lease should
not be transferred.

Part of: #118966
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
> This is great! One possible enhancements is to have a set of "Don't transfer" reasons as well. This will likely help debugging when we decide NOT to transfer:
> 
> ```
> DontTransferLeaseNoStats
> DontTransferLeaseNoValidTargets
> DontTransferLeaseNoDescriptor
> DontTransferLease
> ```
> 
> That would really help debugging especially if a user is expecting it to transfer and it doesn't.

Nice idea. I've updated the PR to include some of these additional don't transfer reasons. Should be good for another look.

**Review by andrewbaptist — COMMENTED** [review]
:lgtm:
Thanks for the changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119016#-:-Nr6N9Oz0wmt8qMLbPyq:b-qnb1r2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/plan/replicate.go` line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119016#-Nr6MobE8uPfH1EODWJ7:-Nr6MobF3VPgezbe2imN:b-nbmwqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c725710d2a78b2395e4594eb800478ade494eedc/pkg/kv/kvserver/allocator/plan/replicate.go#L217)):*
> ```Go
> 			repl.RangeUsageInfo(),
> 		)
> 		if decision.ShouldTransfer() {
> ```

nit: Consider logging outside the `if` check.

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119016#-:-Nr6dBS72SsRCHGkKrzM:bzftgo7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/allocator/plan/replicate.go` line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119016#-Nr6MobE8uPfH1EODWJ7:-Nr6dCyE-UK-nh95YFyP:b-59buxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c725710d2a78b2395e4594eb800478ade494eedc/pkg/kv/kvserver/allocator/plan/replicate.go#L217)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Consider logging outside the `if` check.
</blockquote></details>

I have this logic in a follow up PR which does the separation between the lease queue and replicate queue so i'll defer till then. https://github.com/cockroachdb/cockroach/pull/119155

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Comment by kvoli** [comment]
Looks like its missing a stamp @andrewbaptist, could you re-approve?

**Review by andrewbaptist — APPROVED** [review]

**Comment by andrewbaptist** [comment]
Sorry - must have clicked something wrong. Should be good now.

**Comment by kvoli** [comment]
All good, thanks!


bors r=andrewbaptist

**Pull request merged**
