### PR TITLE
distsql: add stats collection to distinct

### PR DESCRIPTION
**Pull request by asubiotto**
The first commit also adds a `memMonitor` field to `processorBase` which is a private memory monitor for processors used even when not collecting stats.

Addresses #25743

### CODE REVIEW

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/distinct.go, line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFI_Fhf1W6k5c6qQsmB:-LFI_Fhg-vg-AviMH6aD:bla0p03) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f66014359d067123ec7432cd08409daaba3613/pkg/sql/distsqlrun/distinct.go#L345)):*
> ```Go
> // outputStatsToTrace outputs the collected distinct stats to the trace. Will
> // fail silently if the Distinct processor is not collecting stats.
> func (d *Distinct) outputStatsToTrace() {
> ```

Could maybe have a helper function around processorBase that gets these input stats from an input, seems to be a lot of repeated code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26792)*

**Comment by jordanlewis** [comment]
Reviewed 14 of 14 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/distinct.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFI_yz-7-ojf3WgH46F:-LFI_yz-7-ojf3WgH46G:bw4bb49) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f66014359d067123ec7432cd08409daaba3613/pkg/sql/distsqlrun/distinct.go#L331)):*
> ```Go
> 		"distinct.input.rows": fmt.Sprintf("%d", ds.InputStats.NumRows),
> 		"distinct.stalltime":  fmt.Sprintf("%v", ds.InputStats.RoundStallTime()),
> 		"distinct.mem.max":    humanizeutil.IBytes(ds.MaxAllocatedMem),
> ```

Speaking of repeated code, we also do this in every place. Could you find a way to eliminate this duplication? It would also be nice to avoid having to write the suffixes (`input.rows`, `stalltime`) more than once as strings, to prevent typos.

---

*[pkg/sql/distsqlrun/distinct.go, line 345 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFI_Fhf1W6k5c6qQsmB:-LFI_x1b7IWF7wo-RaKA:bpm45gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f66014359d067123ec7432cd08409daaba3613/pkg/sql/distsqlrun/distinct.go#L345)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could maybe have a helper function around processorBase that gets these input stats from an input, seems to be a lot of repeated code.
</blockquote></details>

Yeah agreed.

---

*[pkg/sql/distsqlrun/sorter.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFIZHWM9nXsFHLmf1DH:-LFIZHWM9nXsFHLmf1DI:b24vetq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ce45f82d0b0b4663d48a152332fbc7e0ac2290/pkg/sql/distsqlrun/sorter.go#L285)):*
> ```Go
> 		ctx := s.evalCtx.Ctx()
> 		s.rows.Close(ctx)
> 		s.memMonitor.Stop(ctx)
> ```

Now that this lives in processorBase, should we put it in InternalClose, guarded by an if memMonitor != nil?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26792)*

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/distsqlrun/distinct.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFI_yz-7-ojf3WgH46F:-LFJ0K-C59y1RYh-UrkG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f66014359d067123ec7432cd08409daaba3613/pkg/sql/distsqlrun/distinct.go#L331)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Speaking of repeated code, we also do this in every place. Could you find a way to eliminate this duplication? It would also be nice to avoid having to write the suffixes (`input.rows`, `stalltime`) more than once as strings, to prevent typos.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/sorter.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-LFIZHWM9nXsFHLmf1DH:-LFIaUoG69kaMI_tH4CW:bbysuuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ce45f82d0b0b4663d48a152332fbc7e0ac2290/pkg/sql/distsqlrun/sorter.go#L285)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Now that this lives in processorBase, should we put it in InternalClose, guarded by an if memMonitor != nil?
</blockquote></details>

We can't do that because there are some callers of `internalClose` that go on and close memory accounts associated with the `memMonitor` after doing so, which would result in trying to free memory that's already been freed. We could try to figure out better ownership/closing semantics but I'm fine leaving this as it is for now at least.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26792)*

**Comment by asubiotto** [comment]
Fixed the failing tests PTAL

**Comment by asubiotto** [comment]
There were still some acceptance test failures, those should be resolved now.

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 10 of 18 files at r3, 5 of 5 files at r4, 5 of 5 files at r5.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26792#-:-LFS_BIF1PIw1OsH_7yM:bnfp4nl)*

**Comment by asubiotto** [comment]
TFTR!
bors r+

**Pull request merged**
