### PR TITLE
ts: allow time interval and series to dump to be specified

### PR DESCRIPTION
**Pull request by vrongmeal**
Previously, only *all* of the timeseries could be dumped.
This is a lot of data. With this commit, we can pull any
subset of timeseries restricted to a time interval of
interest.

The plan is to use this from `debug.zip` and in `roachtest`,
for visualization via `./scripts/localmetrics`.

Release note: None

Signed-off-by: Vaibhav <vrongmeal@gmail.com>

### CODE REVIEW

**Comment by vrongmeal** [comment]
@tbg created this as a draft PR for now

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

___
*[pkg/ts/server.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiK1YY31c27fTGz4V4:-MNiK1YY31c27fTGz4V5:b-o7e8xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/server.go#L328)):*
> ```Go
> 		// TODO: Add option to specify different resolutions in DumpRequest.
> 		// Currently it only gets the data for Resolution10s since Dump is defined
> 		// so but we probably want to make it flexible enough to dump all the
> ```

Let's give DumpRequest the resolution, and `debug dumpts` can hard-code Resolution10s.
___
*[pkg/ts/catalog/walk.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiJdf98RMkMw73lh8i:-MNiJdf98RMkMw73lh8j:b-k3p2an) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/catalog/walk.go#L38)):*
> ```Go
> 	Walk(func(chart *IndividualChart) {
> 		for _, metric := range chart.Metrics {
> 			// TODO(lunevalex): these prefixes come from pkg/server/status/recorder.go.
> ```

These TODOs were originally in Alex's name because we were hoping he would have time to work on them, which he didn't in the end. Make them out in my name instead.
___
*[pkg/ts/tspb/timeseries.proto, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiJr9L2TPLInrFkjXa:-MNiJr9L2TPLInrFkjXb:b6lhi2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/tspb/timeseries.proto#L150)):*
> When not provided, defaults to the maximum possible.
___
*[pkg/ts/tspb/timeseries.proto, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiKMg7-IymRMfPJBRt:-MNiKMg7-IymRMfPJBRu:bv8i004) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/tspb/timeseries.proto#L152)):*
> ```protobuf
>   optional int64 end_nanos = 2 [(gogoproto.nullable) = false];
>   // The timeseries to dump. All sources will be queried.
>   repeated string names = 3;
> ```

We could default this to all known names if empty. I think this makes sense, as it will be how it's commonly used.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

___
*[pkg/cli/tsdump.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiK_2lE0YvgVpoFIx8:-MNiK_2lE0YvgVpoFIx9:b-pmtv7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/cli/tsdump.go#L64)):*
> ```Go
> 		tsClient := tspb.NewTimeSeriesClient(conn)
> 		stream, err := tsClient.Dump(context.Background(), &tspb.DumpRequest{
> 			Names: catalog.AllMetricsNames(resp.Catalog...),
> ```

The upshot of defaulting to all names is that the code changes here wouldn't be necessary.

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

**Review by vrongmeal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg and @vrongmeal)

___
*[pkg/ts/server.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiK1YY31c27fTGz4V4:-MNlpLHC4yNovmJDlho-:b5klayy) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/server.go#L328)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Let's give DumpRequest the resolution, and `debug dumpts` can hard-code Resolution10s.
</blockquote></details>

Resolution enum is already created in the package so how should I handle this?

- Create another enum in proto and have a function translate proto enum to the ones that already exist OR
- Use the new enum created in proto instead OR
- Just keep the resolution as `int64`
___
*[pkg/ts/catalog/walk.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiJdf98RMkMw73lh8i:-MNlqLskBNvBlm_h7y1U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/catalog/walk.go#L38)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

These TODOs were originally in Alex's name because we were hoping he would have time to work on them, which he didn't in the end. Make them out in my name instead.
</blockquote></details>

Done.
___
*[pkg/ts/tspb/timeseries.proto, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiJr9L2TPLInrFkjXa:-MNlqOYt9ngpOL6eKgIu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/tspb/timeseries.proto#L150)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> When not provided, defaults to the maximum possible.
</blockquote></details>

Done.
___
*[pkg/ts/tspb/timeseries.proto, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiKMg7-IymRMfPJBRt:-MNloZHB6pbOgtwXQrNJ:b40eogu) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/tspb/timeseries.proto#L152)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We could default this to all known names if empty. I think this makes sense, as it will be how it's commonly used.
</blockquote></details>

This would require the `MetricsRecorder` to get metrics metadata which will generate charts. Basically, I will have to add the recorder field in `ts.Server` and set it as the same recorder as created in `server.NewServer`.

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

___
*[pkg/ts/server.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiK1YY31c27fTGz4V4:-MO0_Dt95Si65IEpyEt7:b-vhleif) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/server.go#L328)):*
<details><summary><i>Previously, vrongmeal (Vaibhav) wrote…</i></summary><blockquote>

Resolution enum is already created in the package so how should I handle this?

- Create another enum in proto and have a function translate proto enum to the ones that already exist OR
- Use the new enum created in proto instead OR
- Just keep the resolution as `int64`
</blockquote></details>

I would go with option one, since that allows us to define only the supported resolutions (10s and 30m). The `const` enum we have right now also has a bunch of testing stuff that I'd rather not leak into the proto.
___
*[pkg/ts/tspb/timeseries.proto, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MNiKMg7-IymRMfPJBRt:-MO0aRy2Cwov73r_QzcS:bcgdr20) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0ad224ff5c00451d9673587e48f2adcc919b8b/pkg/ts/tspb/timeseries.proto#L152)):*
<details><summary><i>Previously, vrongmeal (Vaibhav) wrote…</i></summary><blockquote>

This would require the `MetricsRecorder` to get metrics metadata which will generate charts. Basically, I will have to add the recorder field in `ts.Server` and set it as the same recorder as created in `server.NewServer`.
</blockquote></details>

Ok, I see the problem - I think it goes back to how poorly the metrics metadata and timeseries are coupled together (similar to the `cr.node` prefix problem).

However, I think this is a good opportunity to untie it a little bit. The charts catalog carries the metric metadata (i.e. the thing that is used to actually create the metric instance) and so the `ts` package doesn't know it (because it never gets to see that). So instead we have this `ChartCatalog` request which passes the metrics registry that has all of the metadata into a catalog method `GenerateCatalog` so that the package can link up its descriptions with the meta... this is not great :-)

But you don't need the metadata here! You're just collecting metric names, and they *are* known to the `catalog` package:

```go
// TODO comment
func AllMetricsNames() []string {
	m := map[string]struct{}{}
	for _, section := range charts {
		for _, chart := range section.Charts {
			for _, metric := range chart.Metrics {
				m[metric] = struct{}{}
			}
		}
	}
	// TODO: copy the TODO about the prefix from old impl
	names := make([]string, 0, 2*len(m))
	for name := range m {
		names = append(names, "cr.store."+name, "cr.node."+name)
	}
	sort.Strings(names)
	return names
}

// nb: Walk() is no longer needed
```

That should solve the problem as you can call `catalog.AllMetricsNames()` in `dumpSeriesAllNames` when no names are specified.

**Comment by vrongmeal** [comment]
@tbg I made the requested changes as well as updated the test.

**Review by tbg — COMMENTED** [review]
Looking good! One more round of polish and it will be :shipit: o'clock.

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-:-MOa1h1fB7JmPXufDq8x:b-dskohd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

___
*[pkg/ts/server_test.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa0Z_i5BgoMPz51XPd:-MOa0Z_jAlBLHn7tgjv8:bvkeubp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/server_test.go#L372)):*
punctuation

Also, is this just where you're deciding to start dumping? Might be made a little clearer with

> // We'll dump `[startVal, endVal]` below. To simplify the test, pick them according to a slab boundary.

(or is endVal exclusive?)
___
*[pkg/ts/server_test.go, line 375 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1ACc5eVDjj7X3DQ8:-MOa1ACc5eVDjj7X3DQ9:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/server_test.go#L375)):*
> ```Go
> 	startSlab := 2
> 	startVal := numPointsEachHour * startSlab
> 	// Ending point for endNanos
> ```

.
___
*[pkg/ts/tspb/timeseries.proto, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Zyt0Cnt79k6mH-G:-MOa1Zyt0Cnt79k6mH-H:b-3vpfb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L157)):*
> ```protobuf
> message DumpRequest {
>   // A timestamp in nanoseconds which defines the early bound of the time span
>   // for this query. Will be rounded to nearest resolution boundary.
> ```

And this would be rounded down ideally and the comment could reflect that.
___
*[pkg/ts/tspb/timeseries.proto, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Xe1CwDwmD7eYBC2:-MOa1Xe1CwDwmD7eYBC3:b-pb2wcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L160)):*
> ```protobuf
>   optional int64 start_nanos = 1 [(gogoproto.nullable) = false];
>   // A timestamp in nanoseconds which defines the late bound of the time span
>   // for this query. Must be greater than start_nanos. Will be rounded to nearest
> ```

will it be rounded up or down? I think it should be up. (We want rounding to return more data, not less).
___
*[pkg/ts/tspb/timeseries.proto, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1PmaDUtRi1CWNmDO:-MOa1PmaDUtRi1CWNmDP:b-w957gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L162)):*
> ```protobuf
>   // for this query. Must be greater than start_nanos. Will be rounded to nearest
>   // resolution boundary. When not provided, defaults to the maximum possible.
>   optional int64 end_nanos = 2 [(gogoproto.nullable) = false];
> ```

Might be worth pointing out whether the end is exclusive (which only matters when it falls on a slab boundary, but whatever)

**Review by vrongmeal — COMMENTED** [review]
Left some comments regarding the changes you suggested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-:-MP8lIRYB2IBFHkYOcaK:bqc7sw9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg and @vrongmeal)

___
*[pkg/ts/tspb/timeseries.proto, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Zyt0Cnt79k6mH-G:-MP8jli69mq6fJXFjNtK:bp3kdd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L157)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

And this would be rounded down ideally and the comment could reflect that.
</blockquote></details>

Yes, I'll add the comment.
___
*[pkg/ts/tspb/timeseries.proto, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Xe1CwDwmD7eYBC2:-MP8a7T84GXhHy3SDkGo:bgqmmtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L160)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

will it be rounded up or down? I think it should be up. (We want rounding to return more data, not less).
</blockquote></details>

The end is exclusive. Say, given `startNanos = 0` and `endNanos = 100`, it will fetch data for `[0, 1, 2, ..., 99]` nano-seconds.

One way could be making `endNanos` inclusive. In the range span, I can make this change:

```diff
--- a/pkg/ts/server.go
+++ b/pkg/ts/server.go
@@ -360,7 +360,7 @@ func dumpTimeseriesAllSources(
            seriesName, "" /* source */, diskResolution, startNanos,
        ),
        EndKey: MakeDataKey(
-           seriesName, "" /* source */, diskResolution, endNanos,
+           seriesName, "" /* source */, diskResolution, endNanos+1,
        ),
    }
```
___
*[pkg/ts/tspb/timeseries.proto, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1PmaDUtRi1CWNmDO:-MP8jCm95M55Hj-KaD9M:bu4oiac) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L162)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Might be worth pointing out whether the end is exclusive (which only matters when it falls on a slab boundary, but whatever)
</blockquote></details>

Yeah, I'll mention that. It's exclusive.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg and @vrongmeal)

___
*[pkg/ts/tspb/timeseries.proto, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Xe1CwDwmD7eYBC2:-MPJLfKP-XC7qU1AcObH:b3t5ti1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L160)):*
<details><summary><i>Previously, vrongmeal (Vaibhav) wrote…</i></summary><blockquote>

The end is exclusive. Say, given `startNanos = 0` and `endNanos = 100`, it will fetch data for `[0, 1, 2, ..., 99]` nano-seconds.

One way could be making `endNanos` inclusive. In the range span, I can make this change:

```diff
--- a/pkg/ts/server.go
+++ b/pkg/ts/server.go
@@ -360,7 +360,7 @@ func dumpTimeseriesAllSources(
            seriesName, "" /* source */, diskResolution, startNanos,
        ),
        EndKey: MakeDataKey(
-           seriesName, "" /* source */, diskResolution, endNanos,
+           seriesName, "" /* source */, diskResolution, endNanos+1,
        ),
    }
```
</blockquote></details>

That's not enough because of the slab structure, right? If there is a slab at 56 and another at 10056, and endNanos is, say, 950, then we'd want to round up to 10057. I think we'd need `endNanos + (slabWidth - 1)`. I.e. if `slabWidth =  1000`, and `endKey=1001`, then the end key created by `endNanos+1` is slab 1, and is exclusive, meaning we fetch only slab zero. However, the data for timestamp 1000 (in slab 1) should have been returned but is missed. With `endNanos+(slabWidth-1)`, we'd compute the end key from `1001+999 = 2000`, i.e. we get the extra slab. (if endNanos was 1000 to begin with, because it is exclusive which is ok, we did not have to return timestamp 1000 and so the nanos we use, 1000+999, translates to only slab zero again as it should). I think that makes sense - keep end nanos exclusive but make sure we compute the end slab so that endNanos-1 is definitely included. Make sure to guard against int overflows when computing `endNanos + slabWidth - 1` (returning an error is fine). Btw, I don't think this matters much for the 10s resolution, but in the 30m resolution it would be weird if we run a query and are missing up to 30 minutes on the right end.

I wonder how `(*DB).Query` solves this; as far as I can tell it also rounds the end slab down? That code is a lot more complicated, but I think what it does is actually an unbounded scan, and it simply stops when it sees a timestamp >= the end key:

https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/ts/query.go#L518-L520

I don't think there's much we want to copy into here right now, adjusting the end key seems fine and appears more optimal.

**Review by vrongmeal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg and @vrongmeal)

___
*[pkg/ts/tspb/timeseries.proto, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-MOa1Xe1CwDwmD7eYBC2:-MPVtrXF1qG5p7zwyqJe:bezqggi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dcca86906fcaa86439cd7484ad74c2d3b275078e/pkg/ts/tspb/timeseries.proto#L160)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That's not enough because of the slab structure, right? If there is a slab at 56 and another at 10056, and endNanos is, say, 950, then we'd want to round up to 10057. I think we'd need `endNanos + (slabWidth - 1)`. I.e. if `slabWidth =  1000`, and `endKey=1001`, then the end key created by `endNanos+1` is slab 1, and is exclusive, meaning we fetch only slab zero. However, the data for timestamp 1000 (in slab 1) should have been returned but is missed. With `endNanos+(slabWidth-1)`, we'd compute the end key from `1001+999 = 2000`, i.e. we get the extra slab. (if endNanos was 1000 to begin with, because it is exclusive which is ok, we did not have to return timestamp 1000 and so the nanos we use, 1000+999, translates to only slab zero again as it should). I think that makes sense - keep end nanos exclusive but make sure we compute the end slab so that endNanos-1 is definitely included. Make sure to guard against int overflows when computing `endNanos + slabWidth - 1` (returning an error is fine). Btw, I don't think this matters much for the 10s resolution, but in the 30m resolution it would be weird if we run a query and are missing up to 30 minutes on the right end.

I wonder how `(*DB).Query` solves this; as far as I can tell it also rounds the end slab down? That code is a lot more complicated, but I think what it does is actually an unbounded scan, and it simply stops when it sees a timestamp >= the end key:

https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/ts/query.go#L518-L520

I don't think there's much we want to copy into here right now, adjusting the end key seems fine and appears more optimal.
</blockquote></details>

Sorry, that's my bad. Looking at `MakeDataKey` cleared a lot of things up about how the data is stored.

`endNanos + slabWidth - 1` and keeping `endNanos` exclusive seems like the correct call to make.

**Review by tbg — APPROVED** [review]
Thanks Vaibhav!

bors r+

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57481#-:-MQBdmrPCMqlZRCQ0Q4K:bfi915d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vrongmeal)

**Comment by tbg** [comment]
Unrelated flake - I asked the storage team to take a look

https://teamcity.cockroachdb.com/viewLog.html?buildId=2556525&buildTypeId=Cockroach_UnitTests&tab=artifacts&branch_Cockroach=56735#%2Facceptance%2Facceptance%2FTestDockerPSQL

bors r+

**Pull request merged**
