### PR TITLE
sql: virtual table changes for implicit column definitions

### LINKED ISSUE #58730: sql: hide implicit partitioned columns from SHOW CREATE TABLE and pg_catalog.index[es]

### PR DESCRIPTION
**Pull request by otan**
resolves #58730 

# descpb: hide implicit partitioning columns from SHOW CREATE TABLE

The implicit partitioning columns are now hidden from SHOW CREATE TABLE
statements. This more accurately re-creates the same syntax used for
creating the implicit partitioning columns of each index.

Release note: None

# sql: hide sharded index and implicit columns from pg_index/pg_indexes

To mimic Postgres behavior to ORMs, we should hide any columns we
implicitly add, which in this case is the pg_index and pg_indexes column
names/ids.

Release note (sql change): Columns implicitly added from hash sharded
indexes will no longer display on pg_index and pg_indexes.

# sql: add implicit column for crdb_internal.index_columns

Release note (sql change): Add a new `implicit` column to
crdb_internal.index_columns, which signifies whether the column is
implicitly added onto the index.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/catalog/descpb/index.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58749#-MQrRbyD-P1WfW35Xfvv:-MQrRbyD-P1WfW35Xfvw:b-gofvcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda20e6b1068fc3ab65e2e68fc382cd6471220b9/pkg/sql/catalog/descpb/index.go#L84)):*
> ```Go
> // in this index to the given buffer.
> func (desc *IndexDescriptor) ColNamesFormat(ctx *tree.FmtCtx) {
> 	for start, i := desc.ExplicitColumnStartIdx(), desc.ExplicitColumnStartIdx(); i < len(desc.ColumnNames); i++ {
> ```

Nit: could just be me, but I find the way this is written confusing.  I would have written it with `start` named `firstTime` as a `bool` initialized to `true`, and the if branch below would check if it's set and if so, set it to false.  Then, if we're not the first time through, we can print the `,`.  Of course, you can take or leave this comment.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58749#-MQrcoSJ6VIWpCwDBKCe:-MQrcoSJ6VIWpCwDBKCf:bpfpa40) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa52eeb90d044ba7418d4607dec80f13fec5c3cb/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L76)):*
> ```
> index_name  column_name               implicit
> primary     a                         false
> primary     crdb_internal_a_shard_10  true
> ```

If hash sharded columns are implicit, does it make sense to mark internally generated `rowid` columns as "implicit"?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/catalog/descpb/index.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58749#-MQrRbyD-P1WfW35Xfvv:-MQs1T8o0r-f-8W_4PtE:b-ia7mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda20e6b1068fc3ab65e2e68fc382cd6471220b9/pkg/sql/catalog/descpb/index.go#L84)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: could just be me, but I find the way this is written confusing.  I would have written it with `start` named `firstTime` as a `bool` initialized to `true`, and the if branch below would check if it's set and if so, set it to false.  Then, if we're not the first time through, we can print the `,`.  Of course, you can take or leave this comment.
</blockquote></details>

i've updated this slightly to be more readable.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58749#-MQrcoSJ6VIWpCwDBKCe:-MQs0C0YAs8wQWgEOdO8:b9ybu09) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa52eeb90d044ba7418d4607dec80f13fec5c3cb/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L76)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

If hash sharded columns are implicit, does it make sense to mark internally generated `rowid` columns as "implicit"?
</blockquote></details>

not in terms of the optimiser being able to quickly know to "check every known prefix of the partition". it is implicit in the index sense, which is different i feel.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58749)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/catalog/descpb/index.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58749#-MQrRbyD-P1WfW35Xfvv:-MQs3naB2upJ9kq243Tw:b-5bovjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fda20e6b1068fc3ab65e2e68fc382cd6471220b9/pkg/sql/catalog/descpb/index.go#L84)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i've updated this slightly to be more readable.
</blockquote></details>

Looks better.  Thx!

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
