### PR TITLE
kvserver: declare lock spans for `AddSSTable`

### PR DESCRIPTION
**Pull request by erikgrinaker**
`AddSSTable` did not declare lock spans, even though it can return
`WriteIntentError` when encountering unresolved intents (e.g. when
checking for key collisions with `DisallowShadowing` set). This would
cause the concurrency manager to error with e.g.:

```
cannot handle WriteIntentError ‹conflicting intents on /Table/84/1/99/49714/0›
for request without lockTableGuard; were lock spans declared for this request?
```

This patch makes `AddSSTable` take out lock spans via
`DefaultDeclareIsolatedKeys` if `DisallowShadowing` is set. This will
automatically handle any unresolved intents via the concurrency manager.

Release note (bug fix): `IMPORT INTO` no longer crashes when encountering
unresolved write intents.

### CODE REVIEW

**Review by aayushshah15 — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
@dt I think part of why this was missed was because `AddSSTable` can only return a `WriteIntentError` if its `DisallowShadowing` flag is set. Could you confirm that even without `DisallowShadowing`, we would like `AddSSTable` to block on and attempt to resolve any overlapping intents that the lock table may know about?

If that is the case, then this change LGTM.

**Comment by dt** [comment]
I suppose when disallowshadowing is false, we don't strictly need the current `AddSSTableRequest` to block on and exclude creation of new intents in its span? Since it is already allowed to write under other writes, and with disallowshadowing false, its evaluation isn't conditional on the being able to correctly read the current content of that span either. I think there's still the concern about not letting it write a key that splits an intent from its value, but in backfills, where disallowshadowing is false we already take care to pick timestamps for the sst keys we _know_ there are not and will never be intents at (by scanning that time first). 

I wonder if IMPORT INTO should instead have been scanning the whole table, after it went offline, to create a timestamp at which it knows there are no intents and cannot be any later (thanks to tscache).

**Review by dt — APPROVED** [review]

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71676#-MmO_BhC-IihbvusKEgG:-MmO_BhC-IihbvusKEgH:b22qgco) ([raw file](https://github.com/cockroachdb/cockroach/blob/335c1c6865847025cf5952b1dd793ffb9c29d321/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L44)):*
> ```Go
> 	args := req.(*roachpb.AddSSTableRequest)
> 	// DisallowShadowing may encounter intents while checking for key collisions,
> 	// particularly in the case of IMPORT INTO.
> ```

This comment should speak more towards the intended behavior of `AddSSTable` with and without `DisallowShadowing`. Why is one able to ignore conflicting writes/intents while the other is not? And how do we want an `AddSSTable` that has `DisallowShadowing` set to true to interact with conflicting intents?

Also, the effect of this is that we will now begin waiting in the lock table for any intent that overlaps the AddSSTableRequest's key span, not just that collide with the individual keys in the sstable. Is this ok @dt? Could this lead to starvation where there are always overlapping intents at higher and higher timestamps?

This is leading me to question whether this is the right fix or whether the current interaction between `AddSStableRequest` and conflicting intents makes sense. If we addressed https://github.com/cockroachdb/cockroach/issues/71697, could we then treat intents the same way that we treat other values in `checkForKeyCollisionsGo`, throwing a hard error if they exist at lower timestamps and ignoring them if they exist at higher timestamps?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @erikgrinaker)

___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71676#-MmO_BhC-IihbvusKEgG:-MmTtMWO7lZLK6W5r8V3:b-ibpn4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/335c1c6865847025cf5952b1dd793ffb9c29d321/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L44)):*
Will look into the current AddSSTable semantics and guarantees, and write up a comment summarizing them.

>This is leading me to question whether this is the right fix or whether the current interaction between AddSStableRequest and conflicting intents makes sense. If we addressed #71697, could we then treat intents the same way that we treat other values in checkForKeyCollisionsGo, throwing a hard error if they exist at lower timestamps and ignoring them if they exist at higher timestamps?

That sounds reasonable to me, given the current behavior. We'd still have to resolve the intents at a higher level though, to get the updated write timestamp, right? Which would involve returning a WriteIntentError in any case?

 For MVCC-compliant AddSSTable we'd have to treat the intents as any other 1PC write would. But we'd still support a non-MVCC AddSSTable for e.g. streaming replication.

**Review by nvb — COMMENTED** [review]
The code comment :lgtm:.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71676#-:-MmcJ85EDKaxXKJIAsei:b-law76m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Pull request merged**
