### PR TITLE
opt: add support for reverse scans

### PR DESCRIPTION
**Pull request by madhavsuresh**
The optimizer does not generate plans which include reverse scans.
This PR adds support logical support for reverse scans.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
[nit] fix typo in commit message (support logical support)

Looks good to me, but I'd wait for Radu to comment on that strange DistSQL plan...

---

Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/memo_format.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRwC2w2FFV29f3uddA:-LGRwC2w2FFV29f3uddB:b7spfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/memo_format.go#L280)):*
> ```Go
> 			fmt.Fprintf(f.buf, " %s@%s", tab.TabName(), tab.Index(t.Index).IdxName())
> 		}
> 		fmt.Fprintf(f.buf, ",rev=%t", t.Reverse)
> ```

To avoid cluttering the test files, I'd only include this if `t.Reverse` is true.

---

*[pkg/sql/opt/memo/private_defs.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRu13F73ilD99WCPjz:-LGRu13F73ilD99WCPk-:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L73)):*
> ```Go
> // ScanOpDef defines the value of the Def private field of the Scan operator.
> type ScanOpDef struct {
> ```

[nit] extra line

---

*[pkg/sql/opt/memo/private_defs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRuo5233ksVFm8-FAZ:-LGRuHPu2mBfUpkYeUcb:b-s0x1te) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L114)):*
> ```Go
> 			ordering.AppendCol(colID, !indexCol.Descending)
> 		} else {
> 			ordering.AppendCol(colID, indexCol.Descending)
> ```

You could do something like `ordering.AppendCol(colID, indexCol.Descending != s.Reverse)`

But I think your approach might actually be better since it's very clearly correct. Up to you....

---

*[pkg/sql/opt/memo/private_defs.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRuPbY3HJ0zbOZdK1N:-LGRuPbY3HJ0zbOZdK1O:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L115)):*
> ```Go
> 		} else {
> 			ordering.AppendCol(colID, indexCol.Descending)
> ```

[nit] extra line

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGRsjHJDooYnAwngsQM:b-259fnw)*

**Comment by madhavsuresh** [comment]
TFTR! Fixed the typo, sounds good on waiting to discuss the DistSQL plan. 

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/memo_format.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRwC2w2FFV29f3uddA:-LGS-YBG0BfXr53-OWgI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/memo_format.go#L280)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

To avoid cluttering the test files, I'd only include this if `t.Reverse` is true.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRu13F73ilD99WCPjz:-LGS-Zn7554GMIuYCt6G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L73)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_defs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRuo5233ksVFm8-FAZ:-LGS-c-p2Dp1kXgp5iL8:b-11xfk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L114)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You could do something like `ordering.AppendCol(colID, indexCol.Descending != s.Reverse)`

But I think your approach might actually be better since it's very clearly correct. Up to you....
</blockquote></details>

Yea I see what you're saying. However, at the risk of being too verbose, the current if statement is easier for me to understand. 

---

*[pkg/sql/opt/memo/private_defs.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRuPbY3HJ0zbOZdK1N:-LGS-b1h7MvaIB5rpSSj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L115)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGS03A768RahdciSsjz:b-q5gxjz)*

**Comment by justinj** [comment]
We probably want to cost this as a bit more expensive than a normal scan, I think? I remember hearing anecdotally that they're ~3-5x slower than forward scans in RocksDB. That's definitely a concern that can be pushed down the road though (maybe consult Peter about the relative rate, I remember him talking about it a while back).

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/custom_funcs.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSU53X-q5rOcW085zk:-LGSU53X-q5rOcW085zl:b37r9gp) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L86)):*
> ```Go
> 		// then construct a new Scan operator using that index.
> 		if scanOpDef.Cols.SubsetOf(indexCols) {
> 			newDef := &memo.ScanOpDef{Table: scanOpDef.Table, Index: i, Cols: scanOpDef.Cols, Reverse: false}
> ```

up to you, but since `false` is the zero-value of `bool`, you can omit the `Reverse: false`, which still seems reasonably semantic to me, since non-reverse is the "default".

---

*[pkg/sql/opt/xform/custom_funcs.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSUQUr1Pln94A6eTpk:-LGSUQUr1Pln94A6eTpl:b-2guby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L109)):*
> ```Go
> 				Index:   i,
> 				Cols:    scanCols,
> 				Reverse: false,
> ```

same here

---

*[pkg/sql/opt/xform/testdata/rules/scan, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSSw4b37Y3dbzfmkJw:-LGSSw4b37Y3dbzfmkJx:bawn3xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/testdata/rules/scan#L36)):*
> ```
> # --------------------------------------------------
> 
> # Revscan won't be used here because there is no index with f
> ```

If there was an `f DESC` index, wouldn't that be serviced by a forward scan?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGSQnxwAsbwLo10FzYU:b-uyocox)*

**Comment by petermattis** [comment]
> We probably want to cost this as a bit more expensive than a normal scan, I think? I remember hearing anecdotally that they're ~3-5x slower than forward scans in RocksDB. That's definitely a concern that can be pushed down the road though (maybe consult Peter about the relative rate, I remember him talking about it a while back).

The performance diff depends on the number of historic versions. Assuming 2-3x slower seems reasonable (below, old is forward scan and new is reverse scan).

```
name                                                   old time/op    new time/op    delta
MVCCScan_RocksDB/rows=1000/versions=1/valueSize=8-8       203µs ± 1%     341µs ± 2%   +68.06%  (p=0.000 n=8+10)
MVCCScan_RocksDB/rows=1000/versions=2/valueSize=8-8       264µs ± 2%     742µs ± 4%  +181.42%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=8-8      700µs ± 2%    2346µs ± 2%  +235.15%  (p=0.000 n=10+10)
MVCCScan_RocksDB/rows=1000/versions=100/valueSize=8-8    4.54ms ± 1%    8.82ms ± 3%   +94.32%  (p=0.000 n=9+10)
```

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGSrqeN2cVzsDuUZ23a:b-xhyw9x)*

**Comment by RaduBerinde** [comment]
This looks great! Nice work!

Yeah, I would add a 2x factor for reverse scans (grep for `computeScanCost`). This is a low-hanging improvement over the old planner.

Now that we have revscans, the next thing you can do (in another PR) is to make a rule analogous to `ReplaceMinWithLimit` but for MAX. That would resolve a few TODOs in tests.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/testdata/distsql_numtables, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRsiDP0NotSzPIyDXj:-LGTIwSgBQpeMki59Vdg:b9b8kbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/94524bfb4282f8a7ca01f702a64c00b72217a771/pkg/sql/opt/exec/execbuilder/testdata/distsql_numtables#L146)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

I wasn't entirely sure about this change. It seemed to make sense, but I'm confused by as to why there is no annotation that the scan is a reverse scan. Additionally, I'm confused as to why there's only a scan on one node.  
</blockquote></details>

This looks goo. I checked and there is no annotation for reverse vs non-reverse. It runs on one node because the limit gets pushed into the TableReader and it likely will only need to get results from that one node. Note that the node is correct, it is node 5 which stores the last ranges.

Note that TableReaders can do remote KVs if some rows are not on that node (it was an explicit design decision to not require strict placement for correctness).

BTW you can also check out the "old planner" versions of these tests: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/planner_test/distsql_numtables#L141

---

*[pkg/sql/opt/xform/custom_funcs.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGTLEiGAnH6PRbd0CWR:-LGTLEiGAnH6PRbd0CWS:b7hegl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L127)):*
> ```Go
> 			}
> 
> 			join := memo.MakeIndexJoinExpr(input, c.e.mem.InternIndexJoinDef(&def))
> ```

[nit] maybe call `Intern` just once since it's the same arg

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGTJqFr3yw0GyR1BUMr:b-e9xxg0)*

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/private_defs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGRuo5233ksVFm8-FAZ:-LGV6kxoCjMfEXa76Bcq:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c94e6392ebfdea6f72032048c81ab859aba4a2dd/pkg/sql/opt/memo/private_defs.go#L114)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Yea I see what you're saying. However, at the risk of being too verbose, the current if statement is easier for me to understand. 
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Comment by madhavsuresh** [comment]
TFTR! Added cost for reverse scans. After changing the cost, reverse scans don't seem favorable at all. This makes sense when the sort is in memory, but goes against my intuition for disk sorts. 

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/custom_funcs.go, line 86 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSU53X-q5rOcW085zk:-LGVTt2955GSjFDBHjd3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L86)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

up to you, but since `false` is the zero-value of `bool`, you can omit the `Reverse: false`, which still seems reasonably semantic to me, since non-reverse is the "default".
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSUQUr1Pln94A6eTpk:-LGVTtMA2yu2Q5Qw3WMr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L109)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGTLEiGAnH6PRbd0CWR:-LGVU4Qb-vWpgA1W9urH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/custom_funcs.go#L127)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe call `Intern` just once since it's the same arg
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/rules/scan, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGSSw4b37Y3dbzfmkJw:-LGSrtnm6iJ4ASI_YR_B:b-w5iezr) ([raw file](https://github.com/cockroachdb/cockroach/blob/384f21ba3b3e0bd922ae9defd154bca371249e0d/pkg/sql/opt/xform/testdata/rules/scan#L36)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

If there was an `f DESC` index, wouldn't that be serviced by a forward scan?
</blockquote></details>

You're right, thanks for catching this. Should update it to, there's no index with "f asc, k desc" 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGVYdNODHpi5IuDWR_g:byxbz77)*

**Comment by rytaft** [comment]
Yea, we haven't added costing for disk sorts yet. Maybe when you add the rule with MAX + limit 1, reverse scans will be favorable.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGVheNF8yKti8PtmD9x:b71sm8i)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/coster.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGVjMbF7zOox0PiVh3c:-LGVjMbG1UoxQ9N1Iwxi:b-scraq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7290da488cd93860ebcce725bd0dd5ec1b9b3e/pkg/sql/opt/xform/coster.go#L132)):*
> ```Go
> 	def := candidate.Private(c.mem).(*memo.ScanOpDef)
> 	rowCount := memo.Cost(logical.Relational.Stats.RowCount)
> 	reverseMultiplier := memo.Cost(1)
> ```

Radu should weigh in here, but I don't think the multiplier should be applied to the IO cost, but instead to the CPU cost (i.e. `rowScanCost` portion). Iterating in reverse doesn't change how costly it is to fetch the rows from disk/network into memory, but instead on how costly it is to iterate once in memory.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Comment by RaduBerinde** [comment]
This looks good to me. It looks that it is favored in the important cases - the ones where it allows LIMIT to be pushed into the scan.

Perhaps for large tables (with stats) revscan will be favored over forward scan + sort (because of the `log` factor in the sort cost).

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGVkBcyEpQF0CRPM8g0:bfpjn9f)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/coster.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGVjMbF7zOox0PiVh3c:-LGVl0dH2Anapl16s-sP:b4ej6g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7290da488cd93860ebcce725bd0dd5ec1b9b3e/pkg/sql/opt/xform/coster.go#L132)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Radu should weigh in here, but I don't think the multiplier should be applied to the IO cost, but instead to the CPU cost (i.e. `rowScanCost` portion). Iterating in reverse doesn't change how costly it is to fetch the rows from disk/network into memory, but instead on how costly it is to iterate once in memory.
</blockquote></details>

In practice it is 2-3x more expensive overall, so a 2x factor for everything seems fine to me. I think the IO pattern is less efficient in this case, or we wouldn't see that big of a difference.

Note that a rev scan is not merely a forward scan + a reverse in-memory iteration. You can do a rev scan on a huge table to get just the last few rows and this doesn't read the entire table.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Comment by madhavsuresh** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/coster.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGVjMbF7zOox0PiVh3c:-LGVmVyq92QzN-T7C2Ou:b1tybbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7290da488cd93860ebcce725bd0dd5ec1b9b3e/pkg/sql/opt/xform/coster.go#L132)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In practice it is 2-3x more expensive overall, so a 2x factor for everything seems fine to me. I think the IO pattern is less efficient in this case, or we wouldn't see that big of a difference.

Note that a rev scan is not merely a forward scan + a reverse in-memory iteration. You can do a rev scan on a huge table to get just the last few rows and this doesn't read the entire table.
</blockquote></details>

I based this off the table that Peter provided saying that there's ~2x performance penalty overall.  Similar to what Radu said, the performance hit seemed, on average, a total factor of 2x. There is probably some expression which is a more accurate representation of the reverse scan cost - one that takes into account the CPU cost and the IO pattern independently. That seems challenging to construct given the limited information we have. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Comment by petermattis** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/coster.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGVjMbF7zOox0PiVh3c:-LGW4iPj80Fs4INPQcYc:bl8vsq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7290da488cd93860ebcce725bd0dd5ec1b9b3e/pkg/sql/opt/xform/coster.go#L132)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

I based this off the table that Peter provided saying that there's ~2x performance penalty overall.  Similar to what Radu said, the performance hit seemed, on average, a total factor of 2x. There is probably some expression which is a more accurate representation of the reverse scan cost - one that takes into account the CPU cost and the IO pattern independently. That seems challenging to construct given the limited information we have. 
</blockquote></details>

In the benchmark numbers I posted, the perf diff between a forward and reverse scan is entirely CPU. The amount of IO performed is the same.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Comment by madhavsuresh** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/coster.go, line 132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGVjMbF7zOox0PiVh3c:-LGW6s8u46rsKLnhuS8O:be1k2r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a7290da488cd93860ebcce725bd0dd5ec1b9b3e/pkg/sql/opt/xform/coster.go#L132)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In the benchmark numbers I posted, the perf diff between a forward and reverse scan is entirely CPU. The amount of IO performed is the same.
</blockquote></details>

Got it, thanks for clarifying! In that case, it makes sense to push in the multiplier to the rowScanCost as @andy-kimball mentioned. The updated plans use the reverse scan in more cases. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)*

**Review by madhavsuresh — COMMENTED** [review]
ping @rytaft, @RaduBerinde

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGzXGei6ZmGSAVqpFTV:b1meute)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — DISMISSED** [review]
:lgtm: 

> Reviewed 20 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGz_Tlc4x0LagiaVRkB:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 126 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGzZAqc0yUjTiPQiyQH:-LGzZAqc0yUjTiPQiyQI:b-safwzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b3e2fe6ce6bf25cf24d809a50a4a3943d320d59/pkg/sql/opt/xform/custom_funcs.go#L126)):*
> ```Go
> 			}
> 
> 			memoDef := c.e.mem.InternIndexJoinDef(&def)
> ```

[super nit] I think by convention we've been calling this `private` instead of `memoDef`

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGzbE1U1E7zmpo9i9c5:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 126 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-LGzZAqc0yUjTiPQiyQH:-LGzbCOQ82gLaoE6xJZ1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b3e2fe6ce6bf25cf24d809a50a4a3943d320d59/pkg/sql/opt/xform/custom_funcs.go#L126)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[super nit] I think by convention we've been calling this `private` instead of `memoDef`
</blockquote></details>

Done.

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGzcGB33kKx8MliElLk:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madhavsuresh — COMMENTED** [review]
> Dismissed @justinj from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by madhavsuresh — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27110#-:-LGzg4gIBKKDu_TYePQi:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
