### PR TITLE
sql: declarative schema changer did not detect dropped objects

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer was incorrectly
converting index and database names. This was inadequate because
object looks up would fail due to certain being characters
being converted to be SQL friendly. To address this, this
patch correctly fixes uses the correct string conversion functions.

Release Note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 995 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvpiCZ73O2vTM6Scz7:-MpvpiCZ73O2vTM6Scz8:b-4jzjaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L995)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> CREATE DATABASE "'db1-a'";
> 
> statement ok
> CREATE SCHEMA "'db1-a'".sc1;
> 
> statement ok
> CREATE SCHEMA "'db1-a'".sc2;
> ```
</details>

this `'` seems wrong, no?

**Review by postamar — DISMISSED** [review]
edit: deleted, I reviewed the wrong revision, sorry

**Review by postamar — COMMENTED** [review]
I reviewed the latest revision this time. This mostly looks good, just a couple of minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-:-MpvukMBCPrZMmAv7H3w:b-q60gmh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_util.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-Mpvtah63yskOTkW_RsU:-Mpvtah63yskOTkW_RsV:b-89q8d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_util.go#L103)):*
> ```Go
> 
> // checkIfDescriptorIsDropped determines if a descriptor is being dropped.
> func checkIfDescriptorIsDropped(b BuildCtx, id descpb.ID) bool {
> ```

Can you rename this please? It's not just the descriptor that you're checking.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_util.go, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvtLKt65AIx8mQeBqo:-MpvtLKt65AIx8mQeBqp:b-e1sntc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_util.go#L132)):*
> ```Go
> 				matches = true
> 			case *scpb.Schema:
> 				matches = true
> ```

nit: fyi you can `case  *scpb.Table, *scpb.Sequence, ...` instead
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvtmNQ7W7vE7J0XgSB:-MpvtmNQ7W7vE7J0XgSC:bmphux8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L40)):*
> ```Go
> 			if schema.Dropped() {
> 				return
> 			}
> ```

Shouldn't you be calling your new check-if-dropped function instead?
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_view.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvuU6JCMjCupbDTxFw:-MpvuU6JCMjCupbDTxFx:b-s1ffke) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_view.go#L92)):*
> ```Go
> 			if behavior != tree.DropCascade &&
> 				!checkIfDescriptorIsDropped(b, dep.DependedOnBy) {
> 				name, err := b.CatalogReader().GetQualifiedTableNameByID(b.EvalCtx().Context, int64(view.GetID()), tree.ResolveRequireViewDesc)
> ```

nit: fyi you can replace `b.EvalCtx().Context` with just `b`, because `b` embeds `context.Context`.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 1012 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-Mpvs0ui9dGNNoFCHTOK:-MpwA1FZ735tmnKFWwHC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbe950b3d6ad127790d155c4b4e0fcbe4e6ebd69/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L1012)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you also cover the index name case in the tests please?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 995 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvpiCZ73O2vTM6Scz7:-MpwA0aVCGNElelykPrF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L995)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> CREATE DATABASE "'db1-a'";
> 
> statement ok
> CREATE SCHEMA "'db1-a'".sc1;
> 
> statement ok
> CREATE SCHEMA "'db1-a'".sc2;
> ```
this `'` seems wrong, no?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73367#-MpvtmNQ7W7vE7J0XgSB:-MpwA2oSDXwpdmaJF0kn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8b1481449e1e6cb89a072d86128094cf7f375f8/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go#L40)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't you be calling your new check-if-dropped function instead?
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 14 files at r3, 5 of 15 files at r6, 2 of 2 files at r7, 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @postamar)

**Comment by fqazi** [comment]
@postamar TFTR!

**Pull request merged**
