### PR TITLE
storage: fix race in TestMVCCIncrementalIteratorIntentRewrittenConcur…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…rently

Release justification: Non-production code change.

Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69602)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69602#-:-MiNVl5F8h_TgCij28xW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by sumeerbhola** [comment]
TFTRs!

**Pull request merged**
