### PR TITLE
sql: add interface/wrapper for default privileges access

### PR DESCRIPTION
**Pull request by RichardJCai**
Added to ensure users don't access default privileges and read
from or access the protos directly.

Release note: None

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
Couple suggestions but I like where this is going! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-:-Mgflry78JqkQjYZMz_g:b27uupx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RichardJCai)

___
*[pkg/sql/catalog/descriptor.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfghYMEbqSB9tuF7bM:-MgfghYMEbqSB9tuF7bN:bttscla) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/descriptor.go#L182)):*
> ```Go
> 	GetSchemaID(name string) descpb.ID
> 	GetNonDroppedSchemaName(schemaID descpb.ID) string
> 	GetImmutableDefaultPrivileges() defaultprivilegedesc.ImmutableDefaultPrivileges
> ```

s/GetImmutableDefaultPrivileges/GetDefaultPrivileges and have this return the interface instead of the concrete implementation. 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 421 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-Mgfh3Mz7738gc9eH50H:-Mgfh3Mz7738gc9eH50I:bp972wk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/dbdesc/database_desc.go#L421)):*
> ```Go
> 
> // GetMutableDefaultPrivileges returns a MutableDefaultPrivileges.
> func (desc *Mutable) GetMutableDefaultPrivileges() defaultprivilegedesc.MutableDefaultPrivileges {
> ```

Consider make a `interface MutableDefaultPrivileges` that exposes all the setters on `defaultprivilegedesc.MutableDefaultPrivileges`. Then, we can have `dbdesc.Mutable` implement this interface. To do so, when building a `MutableDatabaseDescriptor`, we can embed a `defaultprivilegedesc.MutableDefaultPrivileges` inside it.  Then all mutable accesses for default privileges would be done directly on the database descriptor. Your call!
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfgTs5APVvEx8eWL64:-MgfgTs5APVvEx8eWL65:bhlnskw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L24)):*
> ```Go
> // DefaultPrivilegeDescriptor protos are not accessed and interacted
> // with directly.
> type defaultPrivileges interface {
> ```

Let's make this interface public and move it to the `catalog` package. Then, all read only accesses can go through this interace. 
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfgIow1lRmul19HVUE:-MgfgIow1lRmul19HVUF:b-qhv5d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L37)):*
> ```Go
> // ImmutableDefaultPrivileges is a wrapper for a DefaultPrivilegeDescriptor
> // that only exposes getters.
> type ImmutableDefaultPrivileges struct {
> ```

Following on from my comment above, let's make this struct private so that all read only accesses are through the interface rather than this implementation?

**Review by RichardJCai — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-:-MggIeOG5RxcQ0Wf_8ql:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pbardea)

___
*[pkg/sql/catalog/descriptor.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfghYMEbqSB9tuF7bM:-MggI3hN9j5ETFOCvkjP:b-piaxpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/descriptor.go#L182)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/GetImmutableDefaultPrivileges/GetDefaultPrivileges and have this return the interface instead of the concrete implementation. 
</blockquote></details>

Done, had to use `GetDefaultPrivilegeDescriptor` since `GetDefaultPrivileges` is already implemented by default cause of the proto definition
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 421 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-Mgfh3Mz7738gc9eH50H:-MggI9okEeNdszntM-uC:b-osf5kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/dbdesc/database_desc.go#L421)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Consider make a `interface MutableDefaultPrivileges` that exposes all the setters on `defaultprivilegedesc.MutableDefaultPrivileges`. Then, we can have `dbdesc.Mutable` implement this interface. To do so, when building a `MutableDatabaseDescriptor`, we can embed a `defaultprivilegedesc.MutableDefaultPrivileges` inside it.  Then all mutable accesses for default privileges would be done directly on the database descriptor. Your call!
</blockquote></details>

Imo it doesn't make sense for dbdesc.Mutable to implement the interface, I'd prefer to keep the interfaces / concepts split
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfgTs5APVvEx8eWL64:-MggIY5U7DszyaXnrn00:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L24)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's make this interface public and move it to the `catalog` package. Then, all read only accesses can go through this interace. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MgfgIow1lRmul19HVUE:-MggIYvO2_HHq7hn1bL1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L37)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Following on from my comment above, let's make this struct private so that all read only accesses are through the interface rather than this implementation? 
</blockquote></details>

Done.

**Review by arulajmani — CHANGES_REQUESTED** [review]
Mostly nits now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-:-MggUYJq2EDgYjOC0Aza:b-6pbnwl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RichardJCai)

___
*[pkg/sql/create_table.go, line 278 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggT5TUAOSdQMBAJ2Rz:-MggT5TUAOSdQMBAJ2S-:bgkq2m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/create_table.go#L278)):*
> ```Go
> 
> 	immutableDefaultPrivileges := n.dbDesc.GetDefaultPrivilegeDescriptor()
> 	privs := immutableDefaultPrivileges.CreatePrivilegesFromDefaultPrivileges(
> ```

nit: can we do this whole thing on a single line? (ditto for a few other instances above)
___
*[pkg/sql/create_type.go, line 349 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggT3I0AJGZmhTz_xeL:-MggT3I0AJGZmhTz_xeM:b-chvdcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/create_type.go#L349)):*
> ```Go
> 
> 	immutableDefaultPrivileges := dbDesc.GetDefaultPrivilegeDescriptor()
> 	privs := immutableDefaultPrivileges.CreatePrivilegesFromDefaultPrivileges(
> ```

nit: can we do this whole thing on a single line? 
___
*[pkg/sql/pg_catalog.go, line 1199 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggPVgDEZyg5BrGxch8:-MggPVgDEZyg5BrGxch9:b-85mlkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/pg_catalog.go#L1199)):*
> ```Go
> 			return nil
> 		}
> 		immutableDefaultPrivileges := dbContext.GetDefaultPrivilegeDescriptor()
> ```

nit: could we do this whole thing on one line?
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 421 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-Mgfh3Mz7738gc9eH50H:-MggTffz9DKNUKcTTPjQ:b-9ozhbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e9f5e3d65d6d8a37d5b09d8e5660bffc83cd378/pkg/sql/catalog/dbdesc/database_desc.go#L421)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Imo it doesn't make sense for dbdesc.Mutable to implement the interface, I'd prefer to keep the interfaces / concepts split
</blockquote></details>

Ack,  that's fair! 
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggTYaX-yrNtpLUZSns:-MggTYaX-yrNtpLUZSnt:bdr5v6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L24)):*
> ```Go
> // immutableDefaultPrivileges is a wrapper for a DefaultPrivilegeDescriptor
> // that only exposes getters.
> type immutableDefaultPrivileges struct {
> ```

nit: s/immutableDefaultPrivileges/immutable 
(the package name is enough to tell us that it's a default privilege descriptor!)
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggOnvY2MJhzuD8-LCW:-MggOnvZ52jn7G44KWk7:b-yv75gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L25)):*
> ```Go
> // that only exposes getters.
> type immutableDefaultPrivileges struct {
> 	catalog.DefaultPrivilegeDescriptor
> ```

Instead of embedding the interface in here, you might want to say: 

```
var _ catalog.DefaultPrivilegeDescriptor = &immutableDefaultPrivileges{}
```

To denote that the interface is implemented by this type. Ditto for `MutableDefaultPrivileges`. 
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggTVio2hYl2ogSbM_4:-MggTVio2hYl2ogSbM_5:b-mk7o3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L31)):*
> ```Go
> // MutableDefaultPrivileges is a wrapper for a DefaultPrivilegeDescriptor
> // that exposes getters and setters.
> type MutableDefaultPrivileges struct {
> ```

nit: s/MutableDefaultPrivileges/Mutable
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggSTngBF-4qxQYFVXn:-MggSTngBF-4qxQYFVXo:b-yywdwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L95)):*
> ```Go
> }
> 
> // CreatePrivilegesFromDefaultPrivileges creates privileges for a
> ```

Here, and below, add something like // CreatePrivilegesFromDefaultPrivileges implements the catalog.DefaultPrivilegeDescriptor interface before the actual comment.
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggTH3G-gtaMtV4KF4W:-MggTH3G-gtaMtV4KF4X:b4ueqrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L188)):*
> ```Go
> // GetDefaultPrivilegesForRole looks for a specific user in the list.
> // Returns (nil, false) if not found, or (ptr, true) if found.
> func (d immutableDefaultPrivileges) GetDefaultPrivilegesForRole(
> ```

Any reason these aren't pointer receivers?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @pbardea, and @RichardJCai)

___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggOnvY2MJhzuD8-LCW:-MgkqOMQ4iMTeOSl5UnT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L25)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of embedding the interface in here, you might want to say: 

```
var _ catalog.DefaultPrivilegeDescriptor = &immutableDefaultPrivileges{}
```

To denote that the interface is implemented by this type. Ditto for `MutableDefaultPrivileges`. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 95 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggSTngBF-4qxQYFVXn:-MgkqP2U5LR6U7uWztlV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L95)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Here, and below, add something like // CreatePrivilegesFromDefaultPrivileges implements the catalog.DefaultPrivilegeDescriptor interface before the actual comment.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MggTH3G-gtaMtV4KF4W:-MgkqPS90Vq14C3h0X0K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bacd34b9029218936f330b29524fc77bed53d8f/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L188)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Any reason these aren't pointer receivers? 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
One suggestion but otherwise :lgtm: 

Thanks for iterating on this, the interfaces around here are much cleaner now! :100: 

> Reviewed 1 of 13 files at r3, 2 of 12 files at r5, 10 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-:-MglNWaLBTrQW6xkXIfJ:b-67mt83)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea and @RichardJCai)

___
*[pkg/sql/create_view.go, line 163 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MglLg9y-FnDlstdJcil:-MglLg9y-FnDlstdJcim:b-j1j3sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bebdfbe819f0e74a3c26301553a4b69d7778f8b/pkg/sql/create_view.go#L163)):*
> ```Go
> 	}
> 
> 	immutableDefaultPrivileges := n.dbDesc.GetDefaultPrivilegeDescriptor()
> ```

nit: same line? :sweat_smile: 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 420 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MglMfH6DbL-Z0Eh4Lzv:-MglMfH6DbL-Z0Eh4Lzw:bhmt26w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bebdfbe819f0e74a3c26301553a4b69d7778f8b/pkg/sql/catalog/dbdesc/database_desc.go#L420)):*
> ```Go
> }
> 
> // GetMutableDefaultPrivilegeDescriptor returns a Mutable.
> ```

nit: s/Mutable/defaultprivilegedesc.Mutable
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 51 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MglNMm-0Oyo4irjFvpm:-MglNMm-0Oyo4irjFvpn:b-29rr3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bebdfbe819f0e74a3c26301553a4b69d7778f8b/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L51)):*
> ```Go
> func MakeMutableDefaultPrivileges(
> 	defaultPrivilegeDescriptor *descpb.DefaultPrivilegeDescriptor,
> ) Mutable {
> ```

Should we have this method be `NewMutableDefaultPrivileges` and have it return a `*Mutable` instead? Here, and further up the chain?

**Review by RichardJCai — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-:-MgmfKEH5C6NizxdXjNO:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @pbardea)

___
*[pkg/sql/create_view.go, line 163 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MglLg9y-FnDlstdJcil:-MgmfFts6WB_hWCAh_XD:bq2laup) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bebdfbe819f0e74a3c26301553a4b69d7778f8b/pkg/sql/create_view.go#L163)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: same line? :sweat_smile: 
</blockquote></details>

Oops missed this one
___
*[pkg/sql/catalog/defaultprivilegedesc/default_privilege.go, line 51 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68558#-MglNMm-0Oyo4irjFvpm:-MgmfIi36dyR38gI9JFH:b-n062c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bebdfbe819f0e74a3c26301553a4b69d7778f8b/pkg/sql/catalog/defaultprivilegedesc/default_privilege.go#L51)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we have this method be `NewMutableDefaultPrivileges` and have it return a `*Mutable` instead? Here, and further up the chain? 
</blockquote></details>

Seems reasonable, done.

**Comment by RichardJCai** [comment]
TFTR!
bors r=arulajmani

**Pull request merged**
