### PR TITLE
storage: require enterprise license for WAL failover

### PR DESCRIPTION
**Pull request by jbowens**
If WAL failover is configured but the user has not provided an enterprise license, WAL failover will refuse to failover and log a warning message every 10 minutes.

Epic: none
Release note: none

### CODE REVIEW

**Comment by jbowens** [comment]
I'm working on some `storage.WALFailover` unit tests in the background

**Review by RaduBerinde — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-:-Ntx_2sfB72i24jEE1Ee:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/open.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-NtxZsw42vnx5x0rFGb7:-NtxZsw42vnx5x0rFGb8:bitwji5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90eb16376d2ff0b5e777eac1da872d06ff23227/pkg/storage/open.go#L417)):*
> ```Go
> 				licenseOK := base.CCLDistributionAndEnterpriseEnabled(settings)
> 				if !licenseOK && cclWALFailoverLogEvery.ShouldLog() {
> 					log.Warningf(context.Background(), "Ignoring WAL failover configuration because it requires an enterprise license.")
> ```

Maybe we should log in the version not ok case too? In case someone doesn't finalize the upgrade accidentally

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-:-NtxkXHs4jQ779aptO30:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/storage/open.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-NtxZsw42vnx5x0rFGb7:-NtxkK1_9wV5rXtylXhm:baw0msg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90eb16376d2ff0b5e777eac1da872d06ff23227/pkg/storage/open.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe we should log in the version not ok case too? In case someone doesn't finalize the upgrade accidentally
</blockquote></details>

do users sometimes intentionally go for days without finalizing?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121165)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/open.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-NtxZsw42vnx5x0rFGb7:-NtxksQV0Nj2ADpSOqdp:b4knhwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90eb16376d2ff0b5e777eac1da872d06ff23227/pkg/storage/open.go#L417)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do users sometimes intentionally go for days without finalizing?
</blockquote></details>

Probably, if it takes a long time to roll over the nodes.. but then they shouldn't be configuring WAL failover.  I definitely heard of cases where they stay in that state unintentionally though.

**Review by jbowens — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-:-NtzuEvN1isXvzc-RTyD:bz5mair)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[`pkg/storage/open.go` line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121165#-NtxZsw42vnx5x0rFGb7:-NtztcWS1qS4RiYTitHa:bbi95c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90eb16376d2ff0b5e777eac1da872d06ff23227/pkg/storage/open.go#L417)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Probably, if it takes a long time to roll over the nodes.. but then they shouldn't be configuring WAL failover.  I definitely heard of cases where they stay in that state unintentionally though.
</blockquote></details>

I know of one customer that intends to set the env var fleet-wide, and they won't upgrade all at once. In their case, I think it's expected for WAL failover to be set but the version not yet finalized.

Maybe we should have a more general warning  (independent of wal failover) logged at a longer period if the version hasn't been finalized.

**Pull request merged**
