### PR TITLE
kvserver: deflake TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected

### LINKED ISSUE #136597: kv/kvserver: TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected failed
kv/kvserver.TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected [failed](https://tanzanite.cluster.engflow.com/invocations/default/19c59fd8-74b2-488c-98d1-c5bf93a4d383?testReportRun=11&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [b3fec61ca90095c664f6432af864f18e9946f8bb](https://github.com/cockroachdb/cockroach/commits/b3fec61ca90095c664f6432af864f18e9946f8bb):

```
=== RUN   TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected
    test_log_scope.go:165: test logs captured to: outputs.zip/logTestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected1542221226
    test_log_scope.go:76: use -show-logs to present logs inline
    client_merge_test.go:3060: condition failed to evaluate within 45s: from client_merge_test.go:3062: lhs not destroyed
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected1542221226
--- FAIL: TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected (52.05s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=11</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)

</sub>

Jira issue: CRDB-45156

### PR DESCRIPTION
**Pull request by arulajmani**
Fixes https://github.com/cockroachdb/cockroach/issues/136597

Release note: None

### CODE REVIEW

**Review by iskettaneh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136605)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks!

bors r+

**Review by tbg — APPROVED** [review]

**Comment by arulajmani** [comment]
Not sure why this didn't merge. Bors says the build succeeded. 

bors r+

**Comment by arulajmani** [comment]
Flaked. 

bors retry

**Pull request merged**
