### PR TITLE
descidgen: use system.descriptor_id_seq for all tenants

### LINKED ISSUE #80294: sql: migrate system tenant to use SQL sequence as DescIDGenerator
See https://github.com/cockroachdb/cockroach/issues/48513.

In https://github.com/cockroachdb/cockroach/pull/48778/commits/027f6e3f6347f2403e9c780607529ceabcfa6fb2, we introduced a new SQL sequence called `descriptor_id_seq` that is used by all non-system tenants to allocate descriptor IDs. This was necessary because the system tenant used a non-SQL global key called `/system/desc-idgen` to allocate descriptor IDs.

As we look to unify the system and secondary tenants, we should switch the system tenant to also use this SQL sequence to allocate descriptor IDs.

The tricky part here will be the migration. It could go something like this:
```
version X-1:
- system tenant reads from and writes to `/system/desc-idgen`

version X:
- (existing clusters, before running) SQL migration creates descriptor_id_seq
- (new clusters) SQL bootstraps with the descriptor_id_seq (see https://github.com/cockroachdb/cockroach/blob/3553a79001c0e362f03eaae514c1d403764bd4c3/pkg/sql/catalog/bootstrap/metadata.go#L267-L269)
- system tenant transactionally reads from `/system/desc-idgen` and `descriptor_id_seq`, returns max
- system tenant transactionally increments `/system/desc-idgen` and `descriptor_id_seq`, picks max, if they differ, repair lagging counter

version X+1:
- (existing clusters, before running) system tenant sets `descriptor_id_seq` to `max(/system/desc-idgen, descriptor_id_seq)`
- system tenant reads from and writes to `descriptor_id_seq`
```

At the end of this migration, we should be able to forget about the `/system/desc-idgen` key.

Jira issue: CRDB-15782

Epic: CRDB-17124

### PR DESCRIPTION
**Pull request by postamar**
Previously, the system tenant used a legacy non-SQL key in the meta range to generate descriptor IDs, while non-system tenants used the system.descriptor_id_seq sequence.

This commit introduces a cluster upgrade step which creates this sequence in the the system tenant's system database and migrates the legacy counter value to it.

While this migration is underway, the descriptor ID generator is not available. This upgrade consists of a relatively brief transaction and descriptor ID generation is a relatively infrequent event, as a result the disruption is deemed tolerable.

Fixes #80294.

Release note (sql change): upgrading a cluster to a major release containing this patch will endow the system tenant's system database with a descriptor_id_seq sequence which will henceforth be used to generate new descriptor IDs, as is already the case for non-system tenants.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 7 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/catalog/descidgen/generate_id.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91205#-NFy88hQ05FLWoQxHdGi:-NFy88hQ05FLWoQxHdGj:b-kbyo64) ([raw file](https://github.com/cockroachdb/cockroach/blob/316a7d4e4e545bf1f1764322c83064826d297ec5/pkg/sql/catalog/descidgen/generate_id.go#L63)):*
> ```Go
> 		// which case descriptor ID generation is made unavailable.
> 		if cv.IsActive(ctx, clusterversion.V23_1DescIDSequenceForSystemTenant-1) {
> 			return catid.InvalidDescID, ErrDescIDSequenceMigrationInProgress
> ```

I sort of think that if you're going to hit this error, we might as well sit and retry until you won't hit it again and then return a serializable restart. That way the system will automatically retry and succeed and the client drivers will know how to handle it. WDYT? Otherwise, I think this is a nice approach.

**Comment by postamar** [comment]
Thanks! I wondered about retries, and indeed what you suggest would have been ideal as far as I'm concerned, I just don't know how to properly do it.

My initial approach was to do what @nvanbenschoten suggested in https://github.com/cockroachdb/cockroach/issues/80294 but I rejected it for two reasons:
- the added complexity of tracking two counters felt more risky than just barfing an error in the user's face,
- making the generator transactional in all places was going to be hard.

**Comment by ajwerner** [comment]
There's a few options. The most complex pattern to follow which is probably the most by-the-book would be to make your error type marked as retriable here:
https://github.com/cockroachdb/cockroach/blob/e2de0809ef9415adefe701b9c3616634ca9d9439/pkg/sql/conn_executor.go#L2594-L2599

Then, in the txnStateApplyWrapper, do the waiting. You can follow the pattern we did for concurrent schema changes here:
https://github.com/cockroachdb/cockroach/blob/e2de0809ef9415adefe701b9c3616634ca9d9439/pkg/sql/conn_executor.go#L2929-L2935

Internally this thing aborts the transaction and then waits for there to be no concurrent changes on the descriptor. In your case we'll want to also abort the transaction but instead poll the currently active version.

**Review by knz — COMMENTED** [review]
The first time Andrew and I talked about this, we had the follownig idea:

- use 3 version markers, not just 1. Let's call them versions A, B, C.
- after version  A is reached, we still use the special ID gen but we start *incrementing by 2* every time.
- we make a migration from A to B, which creates a new sequence generator and initializes it with an offset of 1 from the current value of the special ID generator.
- after version B is reached, the  ID gen code uses the new sequence, and *also increments it by 2* every time. 

At this point, the following properties hold:
- it's still possible that a txn started under version A is still using the previous gen, however
- regardless of which gen is used, the IDs generated from them don't overlap

Then the final transition:

- a migraiton from version B to C, which checks if the old ID gen has a value higher than the (new) sequence, and if so bumps the sequence forward.
- once version C is reached, the new sequence is used and *incremented by 1* every time.

This way, there is never an error because the seq is not available yet, nor a need to retry.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91205#-:-NFyg67J3x4DW1eKe8i4:bmju3k0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Comment by postamar** [comment]
> The first time Andrew and I talked about this, we had the follownig idea

It's neat. I think the reason why I can't convince myself that it works is that I don't know enough about how `kv.DB.Inc()` works or how it interacts with `cluster.Settings.Version` and how that's updated:
- what if an `Inc` which started pre-A takes a really long time for whatever reason and only increments by 1 after version A is active?
- how do we implement the B->C migration when the counters aren't transactional? Is a `GetForUpdate` enough? What if there's a concurrent `kv.DB.Inc` on the special gen which reads the old value before the for-update lock is acquired and actually increments it after the txn commits?

I found my either-or approach to be less sensitive to having overlooked something. Still, I'm genuinely curious about the questions above and just how the database works in general. I assume it has to do with raft logs and whatnot, things I'm painfully ignorant about.

**Comment by ajwerner** [comment]
I think I've come around to preferring this. Very few systems use this generator at high throughput. I doubt anybody will notice this migration, and if they do, it's transient and equivalent to contention we'd have seen from other migrations which rewrite descriptors. I like its simplicity.

**Comment by knz** [comment]
No objection to the simplicity.

Marius, to answer your question, the increment is not in a txn but it is now MVCC aware so the last update has a HLC timestamp associated to it. So it's always possible to certainly order an increment with the txn that's bumping the cluster version.

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by postamar** [comment]
Thanks for the reviews!

bors r+

**Comment by knz** [comment]
thank you :sparkling_heart:

**Pull request merged**
