### PR TITLE
storage: assert that the transaction proto doesn't change

### PR DESCRIPTION
**Pull request by andreimatei**
... through the execution of read-only batches.

CC @RaduBerinde

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 1464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15015#-KhyQf2swh3Qh_T05n8w:-KhyQf2swh3Qh_T05n8x:bd50xh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/67db7a1d3db323c2e5cf0dd289ee65a91433b909/pkg/storage/replica.go#L1464)):*
> ```Go
> 		// txn proto. If this changes, the check can be relaxed or removed, although
> 		// it generally seems like a good idea to keep track of what can change in
> 		// the transaction proto and what can't.
> ```

This introduces multiple allocations into the read-only code path. I don't have a suggestion for how to avoid that, but perhaps this could be made test only.

Was there an actual bug here? Or is this just paranoia?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15015)*

**Comment by bdarnell** [comment]
Just paranoia - distsql is considering allowing transactional reads that don't go through the single TxnCoordSender, and I asked Andrei to make sure that reads never change the Transaction object in ways that matter. We definitely don't want to run this all the time; making it test-only would be best (or maybe race-only, so it doesn't interfere with benchmarks).

**Comment by andreimatei** [comment]
Well how exactly do y'all purpose I make it test only? A TestingKnob (so
default no check)? Or a store config option (default check)? If we want it
on for tests but not benchmarks, then I really don't know how to do that
uniformly with any confidence.

One idea is to introduce IsTest/IsBench globals and set them through env
vars and main_test.go files...

But actually, how about I run some benchmarks and hopefully show that these
allocations don't matter (we already clone transactions a bunch of time,
for example) and if that's the case, keep it to always run?

**Comment by petermattis** [comment]
> One idea is to introduce IsTest/IsBench globals and set them through env vars and main_test.go files...

We have `testutils.Stress`. We wouldn't want to depend on `testutils` in normal code, but that same idea would be appropriate here.

> But actually, how about I run some benchmarks and hopefully show that these allocations don't matter (we already clone transactions a bunch of time, for example) and if that's the case, keep it to always run?

I doubt you'll see this in benchmarks. Our read performance is CPU limited. This is just going to add to that burden via additional GC pressure.

**Comment by bdarnell** [comment]
To make it testrace-only is add two files, one with `//+build race\n\n var isRace = true` and one with `//+build !race var isRace = false`. Race builds, unlike test builds, have a distinct build tag and we never really care about performance in them.

**Comment by andreimatei** [comment]
ok, the race dependency is a reasonable idea. Done. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15015#-:-KjOcecyN3qhN3jRoryN:b-9ya985)*

**Pull request closed without merging**
