### PR TITLE
build: force manual generation of .eg.go files

### PR DESCRIPTION
**Pull request by jordanlewis**
Commit 05cd25953 added all .eg.go files to the repo, but only partially
removed the dependency rules that made them get generated in the first
place. This caused several irritating issues.

This commit removes any automatic Makefile-driven dependency management
for .eg.go files. These files must be generated by hand when _tmpl files
change with `make execgen`. CI will notice if this is not done, because
`make execgen` will be run as a part of `make generate`, and any
differences in the repo cause the build to fail at that point.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50726#-:-MAqYwvd97Io4SyzJJZ7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[Makefile, line 1568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50726#-MAqX1nX-pU9kDIrtyvn:-MAqX1nYEB6XlL605inQ:bfvfiz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06d8b204e6b98144e9dabac697c5eef33ac767/Makefile#L1568)):*
> ```Makefile
> # to know how to invoke `make` or clean up.
> ifneq ($(build-with-dep-files),)
> -include bin/execgen_out.d
> ```

Is this needed anymore? It doesn't seem to be generated.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50726)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[Makefile, line 1568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50726#-MAqX1nX-pU9kDIrtyvn:-MAqZgJK11txI7ICIqU1:bvov1kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06d8b204e6b98144e9dabac697c5eef33ac767/Makefile#L1568)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this needed anymore? It doesn't seem to be generated.
</blockquote></details>

Looks like probably not, thanks for noticing.

**Comment by petermattis** [comment]
Sorry to force another round of CI.

**Comment by jordanlewis** [comment]
Not at all!

**Comment by jordanlewis** [comment]
🤞 
bors r+

**Pull request merged**
