### PR TITLE
[WIP] client: add a new WriteBatch command

### PR DESCRIPTION
**Pull request by danhhz**
I dunno who to assign this to, so cc @petermattis @spencerkimball @bdarnell. There is obviously a lot of cleanup left here, especially with naming, but I wanted to make sure I got @bdarnell's signoff before I go any further (this is Spencer and Peter's idea, so I assume they're in favor). On a local cluster, this gets restore a little over the throughput required by the OKR, so it's possible it'll be enough once optimized a bit.

Reviewers please look especially at:
- The request flags
- What are the unknown unknowns? I haven't worked deeply in this area of the codebase before, so there was a lot of cargo culting. What do I need to consider that I may not have?
- How do I test that the mvcc stats are being updated correctly?
- Anything else I need to do before cleaning this up and sending it out for review?
- Should this be ccl'd code?

For now, feel free to ignore naming, missing godoc, basically everything in rocksdb.go, db.h, db.cc.

This command takes a BatchRepr, which is the serialized form of a RocksDB
WriteBatch, and applies it directly to the underlying Engine. The command cannot
span Ranges, must be the only command in a batch, and must be run on an empty
keyrange.

WriteBatch is added as a performance optimization for restore and bulk ingest,
which it speeds up considerably (4MB/s -> 19MB/s).

BenchmarkKVInsert10000_Native-8                 10     111853535 ns/op    93312874 B/op      272559 allocs/op
BenchmarkKVInsert10000_SQL-8                    10     147756975 ns/op    82018657 B/op      318250 allocs/op
BenchmarkKVInsert10000_WriteBatch-8             50      23938387 ns/op     5350640 B/op       51837 allocs/op

TODO(dan)
- Fill in all the various godocs
- Should this be ccl'd code?
- Improve the naming of the new code in rocksdb.go, db.h
- The benchmark frequently errors with "truncation resulted in empty batch"
- Test the behavior of a WriteBatch req that spans two ranges
- Test the MVCCStats behavior of the WriteBatch impl
- Test w/ and w/o proposer evaluated kv

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10908)

### CODE REVIEW

**Comment by petermattis** [comment]
That speed up is quite nice! This looks like what I was expecting, though I've only skimmed the PR so far. 

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/internal/client/txn.go, line 752 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7HTXC0jkXwr1pJTgl:-KX7HTXC0jkXwr1pJTgm:b8rvz6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/internal/client/txn.go#L752)):*
> ```Go
> 
> // WriteBatch TODO(dan)
> func (txn *Txn) WriteBatch(begin, end interface{}, data []byte) error {
> ```

I don't think this `WriteBatch` operation can be transactional (we're not writing intents), so it should be omitted from `Txn`.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2214 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7H25XKdeQ6IitsozH:-KX7H25XKdeQ6IitsozI:b-qu0png) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/storage/engine/rocksdb/db.cc#L2214)):*
> ```cpp
>   DBBatchInserter inserter(&batch);
>   rocksdb::WriteBatch b(ToString(repr));
>   b.Iterate(&inserter);
> ```

Inserting into a batch so you can iterate over it is unfortunate, though I suppose you know that. Nice reuse of `MVCCComputeStatsInternal` below, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-:-KX7I1-kcVnMosjIu974:b-sdtsc0)*

**Comment by paperstreet** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2214 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7H25XKdeQ6IitsozH:-KX7U9vNkUokxfKSaNOg:bmsd0ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/storage/engine/rocksdb/db.cc#L2214)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Inserting into a batch so you can iterate over it is unfortunate, though I suppose you know that. Nice reuse of `MVCCComputeStatsInternal` below, though.
</details>
Added a TODO. I think we could get away with not doing this if we recompute the mvcc stats from scratch after applying the repr and then blowing the old ones away. Could we make that work somehow?

---

*[pkg/internal/client/txn.go, line 752 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7HTXC0jkXwr1pJTgl:-KX7Ug7wnosPkVsZrAHb:bsq252x) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/internal/client/txn.go#L752)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I don't think this `WriteBatch` operation can be transactional (we're not writing intents), so it should be omitted from `Txn`.
</details>
Correct. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908)*

**Comment by paperstreet** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2214 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7H25XKdeQ6IitsozH:-KX7nLocAhOHd8WGQtPJ:b-10731b) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/storage/engine/rocksdb/db.cc#L2214)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Added a TODO. I think we could get away with not doing this if we recompute the mvcc stats from scratch after applying the repr and then blowing the old ones away. Could we make that work somehow?
</details>
Ah, I see that splitTrigger already does this. Probably worth including in this PR, so I don't need the MVCCComputeStatsInternal refactor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908)*

**Comment by bdarnell** [comment]
Reviewed 12 of 16 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.go, line 635 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9vr74OfNq5tpdOpia:-KX9vr74OfNq5tpdOpib:b-9xvdwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/roachpb/api.go#L635)):*
> ```Go
> 
> // ShallowCopy implements the Request interface.
> func (dvcr *WriteBatchRequest) ShallowCopy() Request {
> ```

s/dvcr/wbr/ (or just `r`, which could be used for all request types)

---

*[pkg/storage/replica_command.go, line 3350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9xe7s9_VC-3ES56l9:-KX9xe7s9_VC-3ES56lA:balds7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/storage/replica_command.go#L3350)):*
> ```Go
> 	// Verify that the key range specified in the request span is empty.
> 	// TODO(dan): Is there a better way to do this? `ms.KeyCount > 0`
> 	// doesn't seem to work.
> ```

The incoming `ms` is a delta to be filled in by this method; it's not usable for input. Seeking to the start and end key looks like the best approach to me. 

---

*[pkg/storage/replica_command.go, line 3358 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9yBfu0vHllns1vNFt:-KX9yBfu0vHllns1vNFu:b-jtydok) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/storage/replica_command.go#L3358)):*
> ```Go
> 	}
> 
> 	// Verify that the keys in the batch are within the range specified by the
> ```

Do this verification first. It would be nice if one day we had better lower-level support for raising errors if you try to seek outside your replica's bounds.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2214 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7H25XKdeQ6IitsozH:-KX9zAE29aBXxkS4fofl:b-qoe7jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/storage/engine/rocksdb/db.cc#L2214)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Ah, I see that splitTrigger already does this. Probably worth including in this PR, so I don't need the MVCCComputeStatsInternal refactor
</details>
The fact that splitTrigger recomputes stats is a headache for propEvalKV. I think it's going to be better to do it this way at least until propEvalKV is settled and we have a better handle on how to handle stat recomputation in that world. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908)*

**Comment by paperstreet** [comment]
Review status: 9 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/roachpb/api.go, line 635 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9vr74OfNq5tpdOpia:-KXBa8SRxXZgeGB-5UBP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/roachpb/api.go#L635)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/dvcr/wbr/ (or just `r`, which could be used for all request types)
</details>
Done.

---

*[pkg/storage/replica_command.go, line 3350 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9xe7s9_VC-3ES56l9:-KXBaA0vUjZ_V9dPVHG2:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/storage/replica_command.go#L3350)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The incoming `ms` is a delta to be filled in by this method; it's not usable for input. Seeking to the start and end key looks like the best approach to me. 
</details>
sgtm

---

*[pkg/storage/replica_command.go, line 3358 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX9yBfu0vHllns1vNFt:-KXBaXf7pXWaJos1dEAl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a49978c76d4f8fce5936480050315c6077bad3bb/pkg/storage/replica_command.go#L3358)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Do this verification first. It would be nice if one day we had better lower-level support for raising errors if you try to seek outside your replica's bounds.
</details>
Done.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2214 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908#-KX7H25XKdeQ6IitsozH:-KXBah3siu90pU2UumpQ:b585xfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/aef7a9fb88ecda5c66330b191e3bdb3ff64f9aa8/pkg/storage/engine/rocksdb/db.cc#L2214)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The fact that splitTrigger recomputes stats is a headache for propEvalKV. I think it's going to be better to do it this way at least until propEvalKV is settled and we have a better handle on how to handle stat recomputation in that world. 
</details>
Makes sense. Updated the TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10908)*

**Comment by paperstreet** [comment]
Decided this should be ccl'd so closing for now

**Pull request closed without merging**
