### PR TITLE
ui: add trace rate option to stmt diagnostics

### LINKED ISSUE #92415: Investigate adding sampling probability to statement bundle collection
This issue breaks down https://github.com/cockroachdb/cockroach/issues/90292 and https://github.com/cockroachdb/cockroach/issues/82896#issuecomment-1163812677 in the context of statement bundles.

This issue tracks the investigation of surfacing the sampling probability introduced in (https://github.com/cockroachdb/cockroach/issues/82896) to statement bundles. This is an improvement to the existing conditional statement bundling experience. Although bundles (tracing) will not always be activated, this improvement will enable users to turn on statement bundles with higher confidence that bundles will not impact _all_ statement fingerprint executions. This will help for known outlier scenarios.

A follow up issues has been created here: https://github.com/cockroachdb/cockroach/issues/92416 to define a retention and expiration policy.

Epic: CRDB-8649

Jira issue: CRDB-21754

### PR DESCRIPTION
**Pull request by maryliag**
Fixes #92415

Add option to select the trace rate for statement
diagnostics collection directly on the Console.

https://www.loom.com/share/beaf1ce16f7d4efc845056e33cb3bee1

Screenshot 2023-04-12 at 4 09 50 PM

Screenshot 2023-04-12 at 4 10 00 PM

Release note (ui change): Add option to select the trace rate for statement diagnostics collection.

### CODE REVIEW

**Review by dongniwang — APPROVED** [review]
LGTM!

**Review by THardy98 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101381#-NTJqpqe-LTjMs7XStD8:-NTJqpqe-LTjMs7XStD9:b-7u46sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8842795957d92c40508f528813b4db803c0cb8fd/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L92)):*
> ```XML
>     args.push(samplingProbability);
>   } else {
>     args.push(0);
> ```

Not sure if we want to allow sampling probability of 0, wouldn't this never sample? 
Or is 0 a special value that means "always sample" until we get the statement diagnostics bundle?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101381#-NTJqpqe-LTjMs7XStD8:-NTK17ZF3oOgLyn5aXGY:b-yyixwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8842795957d92c40508f528813b4db803c0cb8fd/pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts#L92)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Not sure if we want to allow sampling probability of 0, wouldn't this never sample? 
Or is 0 a special value that means "always sample" until we get the statement diagnostics bundle?
</blockquote></details>

the 0 is what the function expects, but when you passed it actually uses NULL. You can see in the loom some cases with NULL. When we have NULL the sampling is actually 100%

**Review by THardy98 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by maryliag** [comment]
TFTR!
bors r+

**Comment by maryliag** [comment]
blathers backport 22.2

**Pull request merged**
