### PR TITLE
distsqlrun: fail gracefully if out of memory during stats creation

### PR DESCRIPTION
**Pull request by rytaft**
This commit ensures that the `sampler` and `sampleAggregator` processors
fail gracefully if they run out of memory. Instead of causing the
entire `CREATE STATISTICS` job to fail in case of an out of memory error,
they will continue to collect statistics for row counts, distinct
counts and null counts, but will disable collection of histograms.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39738#-:-LmevaBmDXTabuccY4t8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlpb/data.proto, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39738#-Lmeuqyy1DGuSgW_By3X:-Lmeuqyy1DGuSgW_By3Y:b-u2sy8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6eb5c622f0b5c8c52d9dc8b01de2db88cbaf99f/pkg/sql/distsqlpb/data.proto#L282)):*
> ```protobuf
>     optional uint64 rows_processed = 1 [(gogoproto.nullable) = false];
>     // Indicates that sample collection for histograms should be disabled,
>     // likely because the sampler processor ran out of memory.
> ```

[nit] a sampler processor

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39738#-:-Lmez-xa-VpLWhcZ7oy6:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/distsqlpb/data.proto, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39738#-Lmeuqyy1DGuSgW_By3X:-LmeyiEe-k3uQYl58YFV:bewsiyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6eb5c622f0b5c8c52d9dc8b01de2db88cbaf99f/pkg/sql/distsqlpb/data.proto#L282)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] a sampler processor
</blockquote></details>

I think "the" sampler processor works here because it corresponds to whichever sampler processor is sending this metadata message (same reason we use "the" sampler processor in the line above for rows_processed).

Although I also don't really feel strongly -- happy to change it if you think it would be clearer with "a".

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39738)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

___
*[pkg/sql/distsqlpb/data.proto, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39738#-Lmeuqyy1DGuSgW_By3X:-Lmf30T5C9WaeG4hS7k7:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6eb5c622f0b5c8c52d9dc8b01de2db88cbaf99f/pkg/sql/distsqlpb/data.proto#L282)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think "the" sampler processor works here because it corresponds to whichever sampler processor is sending this metadata message (same reason we use "the" sampler processor in the line above for rows_processed).

Although I also don't really feel strongly -- happy to change it if you think it would be clearer with "a".
</blockquote></details>

:thumbsup:

**Pull request merged**
