### PR TITLE
kvserver: de-flake+unskip TestResetQuorum

### LINKED ISSUE #58165: kv: TestResetQuorum is timing out (acceptance test)
Updated `TestResetQuorum` test is timing out.

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #58165.

Release note: None

### CODE REVIEW

**Review by TheSamHuang — APPROVED** [review]

**Comment by tbg** [comment]
This deletes a part of the test, why?

**Comment by irfansharif** [comment]
The subtest tests the scenario where there's an older replica still around in the cluster, which trips up the consistency checker.

**Comment by tbg** [comment]
Why does that happen? I thought reset quorum should work in that case. No
raft command from the new range should apply on the old one.

**Comment by irfansharif** [comment]
Hm, good point, I'm not sure. I've started at this subtest all morning but didn't get very far. Filed https://github.com/cockroachdb/cockroach/issues/58376 to track it.

**Pull request merged**
