### PR TITLE
changefeedccl: adopt protected timestamps

### LINKED ISSUE #43772: cdc: updating GC TTL on watched tables does not solve replica GC threshold error
**Describe the problem**

When creating a new changefeed on a table, the initial "catchup" scan can take a long time on tables with large amounts of data. This is possibly related to #43103. For particularly large tables, the initial scan might take longer than the default GC TTL window in the cluster, which results in an error that looks like: 

`batch timestamp <timestamp> must be after replica GC threshold <timestamp>`

@ajwerner hypothesized that we might be able to increase the GC window on the watched tables to get around this issue. I attempted this in the Telemetry cluster by bumping the database's GC TTL to 75 hrs:

```
psingh@telemetry/registration> show zone configuration for table stmtstats;
         target         |                  raw_config_sql                   
+-----------------------+--------------------------------------------------+
  DATABASE registration | ALTER DATABASE registration CONFIGURE ZONE USING  
                        |     range_min_bytes = 16777216,                   
                        |     range_max_bytes = 67108864,                   
                        |     gc.ttlseconds = 270000,                       
                        |     num_replicas = 3,                             
                        |     constraints = '[]',                           
                        |     lease_preferences = '[]'                      
(1 row)
```
However despite this change, we still see the error above after starting the changefeed:

`batch timestamp 1576793173.840962794,0 must be after replica GC threshold 1576870074.490489034,0`

Full response:
```psingh@telemetry/registration> select * from crdb_internal.jobs where job_type='CHANGEFEED';
        job_id       |  job_type  |                                                              description                                                              | statement | user_name | descriptor_ids  | status | running_status |             created              |             started              |             finished             |             modified             | fraction_completed | high_water_timestamp |                                                              error                                                               | coordinator_id  
+--------------------+------------+---------------------------------------------------------------------------------------------------------------------------------------+-----------+-----------+-----------------+--------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+----------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------+
  513549185343979521 | CHANGEFEED | CREATE CHANGEFEED FOR TABLE stmtstats INTO 'experimental-s3://register-cdc/stmtstats/' WITH updated                                   |           | joel      | {94,100}        | failed | NULL           | 2019-12-19 22:06:13.847661+00:00 | 2019-12-19 22:06:13.889793+00:00 | 2019-12-22 01:42:55.230138+00:00 | 2019-12-19 22:06:13.847661+00:00 |                  0 | NULL                 | batch timestamp 1576793173.840962794,0 must be after replica GC threshold 1576870074.490489034,0                                 |              4  
```

@danhhz suspects that the issue is the GC window on an internal/system table:
> 1576870074 is Dec 20th and it started on Dec 19th which is less than 75 hours, so sounds like the gc ttl isn't in effect somewhere. I wonder if this is the system.descriptors table which is also used by changefeeds, do you know what the gc ttl is on that table? (This all needs to be documented once we figure it out.) It sucks that this error doesn't have any info about where in the keyspace it had the gc issue.

I confirmed the system database still had the default value for GC TTL (25 hrs). 

cc @lnhsingh for any docs impact - we will probably want to warn users about this potential issue. This may be obviated by supporting compression on the JSON files sent to cloud storage.

### PR DESCRIPTION
**Pull request by ajwerner**
This commit adopts protected timestamps during cdc backfills.
It sets up a protected timestamp record when the changefeed begins
if the changefeed is going to begin with an initial scan.

It removes protected timestamps when checkpointing a new resolved timestamp
as this indicates we've now moved past a scan. It adds a new protected
timestamp when a scan boundary is reached - indicating the start of a
backfill.

One thing to note is that we don't verify these protected timestamps.
This is intentional. I can't think of why we'd want to. If we hit and error,
we hit an error. In the vast majority of cases, the timestamp we're
protecting is the present.

It seems like a mistake to do the verification in the foreground and to
do it asynchronously is awkward.

One thing that is intentionally not handled is paused jobs.

Fixes #43772.

Release justification: bug fixes and low-risk updates to new functionality

Release note (bug fix): CHANGEFEED jobs which take a long time to perform
backfills will no longer encounter failures due to garbage collection so
long as they begin before the data has expired.

### CODE REVIEW

**Comment by ajwerner** [comment]
The first two commits are #45652

**Review by danhhz — COMMENTED** [review]
A couple of drive by comments. I will be afk through Monday, so don't wait up on me if you get an approval from Nathan

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-:-M1kb6pG4-zOW8czgvNu:biio0bg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 775 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_bWGE0BBNINqRcKq:-M1k_bWGE0BBNINqRcKr:bceq6jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_processors.go#L775)):*
> ```Go
> 		log.Infof(ctx, "creating protected timestamp %v at %v", protectedTimestampID, resolved)
> 	}
> 	spansToProtect := makeSpansToProtect(cf.spec.Feed.Targets)
> ```

can this be cached on cf?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_tqc4BHfOCP891R5:-M1k_tqc4BHfOCP891R6:b2zpp74) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L303)):*
> ```Go
> 				return nil
> 			}
> 			ptr := jobsprotectedts.MakeRecord(*protectedTimestampID, *sj.ID(),
> ```

Why is this all the way out here? It seems more appropriate for the scan bit on each node to protect just the spans it needs, no?

More generally, it seems unfortunate that this is tied to the job. Before this change, a changefeed could theoretically be run independent from the jobs infrastructure but this is tying them more tightly together.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1kagmT87zNEv2cKokn:-M1kagmT87zNEv2cKoko:b-fotse6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/helpers_test.go#L252)):*
> ```Go
> }
> 
> func enterpriseTestWithServerArgs(
> ```

the other tests that need knob control grab it from the instantiated testcluster, let's use that pattern here. I've been intentionally avoiding making enterpriseTest* helpers

```
		knobs := f.Server().(*server.TestServer).Cfg.TestingKnobs.
			DistSQL.(*execinfra.TestingKnobs).
			Changefeed.(*TestingKnobs)
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 775 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_bWGE0BBNINqRcKq:-M1kf1-w1CuY5fnbhM5J:b79agdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_processors.go#L775)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

can this be cached on cf?
</blockquote></details>

Yes though my sense is we're about to go read this many tables, we can probably afford to allocate a single slice with #targets keys given the allocations we're going to do for every row of the table. Feels like premature optimization for a rare event. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_tqc4BHfOCP891R5:-M1kcLuABC7Ll0Ae2h4m:bw7yb65) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L303)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Why is this all the way out here? It seems more appropriate for the scan bit on each node to protect just the spans it needs, no?

More generally, it seems unfortunate that this is tied to the job. Before this change, a changefeed could theoretically be run independent from the jobs infrastructure but this is tying them more tightly together.
</blockquote></details>

I want to push back on this a bit. We already returned before this function for sinkless. It is true that a dependency of this feature is durable job checkpointing. Without durable job checkpointing enabled, we can't have other durable features either. 

For the changefeeds with sinks we want to resume which is a tight coupling to jobs. Any time we make any guarantees about checkpointing progress we're tied to jobs today. Effectively we should be thinking about protected timestamps here as a feature that's tied to the job only because jobs are where we're storing state.

The likely source of this percieved coupling is the jobsprotectedts and the fact that it seems like the protectedts and the job are tightly coupled. The reconciliation mechanism is quite decoupled from jobs. If you look in the jobsprotectedts package, there is very little logic, it's just about marking the bits so that a reconciliation loop will clean up after these things. We could trivially tie protected timestamps to any other state layout. 

Maybe you're saying is that you'd like the change aggregators to be run independently from jobs. I'm not sure exactly what I mean by that. If you're saying you want the whole changefeed to be run independently from jobs - that's fine and I'm super on board.

If you're saying you want to run changefeeds in such a way that the leaves checkpoint there progress indepedently then I have something of a philosphical concern. Checkpointing state of the job at the leaves of distsql flows seems awkward. There's a large footprint for the various leaves to step on eachother w.r.t. serializability. The model of only performing writes from the root is incredibly easier to reason about. If we solve those concerns with some big brain data modeling however, I think protected timestamps would be easy to bolt on at that level - just use the metadata to associate them with the leaf state and then go reconcile over that somehow.

In short, I'm skeptical about writing job state from leaves ever without a big change in infrastructure.

Lastly, I really need to add a step to go verify this protected timestamp. The protected timestamp subsystem would much rather have a smaller number of larger protected timestamps than vice versa. If we had to do the creation and verification from the leaves  it would likely be less efficient. 
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1kagmT87zNEv2cKokn:-M1kfRBw7xZwcG-HN4zN:bftda9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/helpers_test.go#L252)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the other tests that need knob control grab it from the instantiated testcluster, let's use that pattern here. I've been intentionally avoiding making enterpriseTest* helpers

```
		knobs := f.Server().(*server.TestServer).Cfg.TestingKnobs.
			DistSQL.(*execinfra.TestingKnobs).
			Changefeed.(*TestingKnobs)
```
</blockquote></details>

Isn't that racy? Once the server has started, requests can get sent around and we'll check the knobs during the request serving path. I'm worried about the race detector.

**Review by nvb — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @danhhz)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l19Wx1c5x2Ii_hyNu:-M1l19Wx1c5x2Ii_hyNv:bk13q1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed.go#L374)):*
> ```Go
> 
> func makeSpansToProtect(targets jobspb.ChangefeedTargets) []roachpb.Span {
> 	// NB: We add 1 because we're also going to protect system.descriptors.
> ```

Mention why we protect `system.descriptors`.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_tqc4BHfOCP891R5:-M1l5riO4L8sKvE5NDiw:b-2xf8nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L303)):*
It sounds like this discussion needs to come to some resolution. I understand why we're creating a job here and immediately protecting well enough to feel ok with this change, but I'd still like to get Dan on-board as well. I don't personally think this needs to block the PR though, given time constraints.

> and immediately protecting

Actually, maybe I don't understand this. Why do we need to protect timestamps both here and in the changeFrontier? Is there a race with establishing it immediately in the changeFronteir? Is doing so insufficient to protect timestamps in all cases? Could you add a comment somewhere?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 575 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l5fgXCl603CSNfdEo:-M1l5fgYCfWfbsmFPLIb:b3zw8en) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L575)):*
> ```Go
> // OnFailOrCancel is part of the jobs.Resumer interface.
> func (b *changefeedResumer) OnFailOrCancel(ctx context.Context, planHookState interface{}) error {
> 	phs := planHookState.(sql.PlanHookState)
> ```

Add a comment about what this is doing. `// Try to clean up protected timestamp installed by associated job.` or something.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l6iBbDgWQEIw8nsfk:-M1l6iBbDgWQEIw8nsfl:b-v235uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_test.go#L2036)):*
> ```Go
> 		}
> 		done           = make(chan struct{})
> 		blockRequestCh = make(chan chan chan struct{}, 1)
> ```

I think you missed a `chan`.

In all seriousness, give this a comment indicating what each level of the channel hierarchy is used for.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1kagmT87zNEv2cKokn:-M1l9Cr47KJ5eCKTAPln:by6a6sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/helpers_test.go#L252)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Isn't that racy? Once the server has started, requests can get sent around and we'll check the knobs during the request serving path. I'm worried about the race detector. 
</blockquote></details>

Yeah, that does seem like it would be racy. I wonder why we haven't hit any issues yet.
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l3g0X4X2jbdKCKsU7:-M1l3g0Y8N8MgpquyhbR:bfku2il) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L188)):*
> ```Go
> 		// Resolve all of the spans as a boundary if the policy indicates that
> 		// we should do so.
> 		if f.schemaChangePolicy == changefeedbase.OptSchemaChangePolicyStop ||
> ```

Should this just be `f.schemaChangePolicy != changefeedbase.OptSchemaChangePolicyNoBackfill`?
___
*[pkg/jobs/jobspb/jobs.proto, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l2YURCF3amcKzoCYv:-M1l2YUS21itpFFDyo2f:buav66k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/jobs/jobspb/jobs.proto#L252)):*
> ```protobuf
>   // Furthermore, once subsequent backfills begin, record will be created and
>   // released accordingly.
>   bytes protected_timestamp_record = 3 [
> ```

I would encourage you to make this non-nullable and use the zero-value (`uuid.Nil`) to indicate a missing record (if that state exists). This parallels what we do in `TxnMeta`.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1k_tqc4BHfOCP891R5:-M1lA6RGEzFA0rhr8hig:b-o4so0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L303)):*
Maybe I misread this completely. Is it just about where we lay down the protected timestamp for the initial scan? I don't care that strongly about that. It seemed like it was easier to do it when we create the job. I really didn't want to give the sinkless feeds distributed state so this felt like the appropriate place to put it. 

> Why do we need to protect timestamps both here and in the changeFrontier?

Well, in the changefrontier we won't have reached a boundary right when we start. We could do it as an additional step while starting up the change frontier but that seems worse. It seemed totally unimportant whether to do it here or at the top of the `Resume` by detecting the initial scan so I preferred to do it here because 1) it's earlier and 2) it's a pattern I want other jobs which retain their protected timestamp throughout their lifetime to follow. I'll admit that it's not the most elegantly abstracted pattern but improvements in abstractions will help this and won't help logic sitting inside of resume. 
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l6iBbDgWQEIw8nsfk:-M1lBgQzDXxAI5xydD4Q:b-ijpu3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_test.go#L2036)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you missed a `chan`.

In all seriousness, give this a comment indicating what each level of the channel hierarchy is used for.
</blockquote></details>

ha okay I actually looked at it and started to write a series of functions with more descriptive names and then questioned whether it was worth it. I guess it was.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed.go, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l19Wx1c5x2Ii_hyNu:-M1lQbeN3cvb9vBR5YCQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed.go#L374)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mention why we protect `system.descriptors`.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 575 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l5fgXCl603CSNfdEo:-M1lQkwoAyzjZlNSfjAM:b-olhycf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_stmt.go#L575)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment about what this is doing. `// Try to clean up protected timestamp installed by associated job.` or something.
</blockquote></details>

I made a method. 
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 2036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l6iBbDgWQEIw8nsfk:-M1lThqwDs6tMY-t8LQ5:b-eyeldx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/changefeed_test.go#L2036)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

ha okay I actually looked at it and started to write a series of functions with more descriptive names and then questioned whether it was worth it. I guess it was. 
</blockquote></details>

See how you feel about this. I think it reads better. 
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1kagmT87zNEv2cKokn:-M1lTlSk753p9ObxfnJ8:b-sznscg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/helpers_test.go#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, that does seem like it would be racy. I wonder why we haven't hit any issues yet.
</blockquote></details>

Probably because background system work tests not to touch distsql or execinfra testing knobs. Mucking with the store knobs is a whole different ballgame. 
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l3g0X4X2jbdKCKsU7:-M1lU0_H3sLW3tVZmb9j:b-adf7bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L188)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this just be `f.schemaChangePolicy != changefeedbase.OptSchemaChangePolicyNoBackfill`?
</blockquote></details>

It certainly could be. I considered it. That seemed more bug-prone in the case a new policy is added.
___
*[pkg/jobs/jobspb/jobs.proto, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l2YURCF3amcKzoCYv:-M1lU7rj39HLeZ0EQvem:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/jobs/jobspb/jobs.proto#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would encourage you to make this non-nullable and use the zero-value (`uuid.Nil`) to indicate a missing record (if that state exists). This parallels what we do in `TxnMeta`.
</blockquote></details>

Done.

**Review by nvb — COMMENTED** [review]
> Reviewed 11 of 11 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @danhhz, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 758 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1zo6sCDh0ENMhwqdz9:-M1zo6sD6kmKsacXGTbo:betk6c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce1bd35bf991e26353d1c21923fe7da05eedc5e/pkg/ccl/changefeedccl/changefeed_processors.go#L758)):*
> ```Go
> 	txn *client.Txn,
> ) error {
> 	if progress.ProtectedTimestampRecord.Equal(uuid.Nil) {
> ```

nit throughout: `==` works, right?
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l3g0X4X2jbdKCKsU7:-M1zpXjG2e1sty6AuhT2:b-5yshlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L188)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It certainly could be. I considered it. That seemed more bug-prone in the case a new policy is added.
</blockquote></details>

If you're concerned about this then we should have a better way to map from policy variants to the behavior of those policies. I'm picturing either a list of predicate functions near the policy definitions or a `flags`-type structure like we have with `roachpb.Request`.

**Review by ajwerner — COMMENTED** [review]
TFTR! Still waiting on @danhhz to see if there was something I wasn't getting from what he said. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-:-M2045ai-6uuxOQ5eVDL:b-i13cc8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 758 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1zo6sCDh0ENMhwqdz9:-M2042glDa-ez5o5LYPc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bce1bd35bf991e26353d1c21923fe7da05eedc5e/pkg/ccl/changefeedccl/changefeed_processors.go#L758)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit throughout: `==` works, right?
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/kvfeed/kv_feed.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45778#-M1l3g0X4X2jbdKCKsU7:-M2044HZ5cEzZ6bB9524:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc9c61ac73a46d2262dd1c10702c298cfe4866b/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L188)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If you're concerned about this then we should have a better way to map from policy variants to the behavior of those policies. I'm picturing either a list of predicate functions near the policy definitions or a `flags`-type structure like we have with `roachpb.Request`.
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
@danhhz I added a bunch more commentary in the areas we discussed. I'm going to wait until #45821 gets merged by bors, rebase, and then later tonight give this a bors. Feel free to retroactively comment.

**Review by danhhz — APPROVED** [review]
I think I'd still like a bit more of a centralized comment about how all this fits together (I'm still a tiny bit confused about what all goes into boundaries and where all they're used). It's possible that we just need to bite the the bullet and write one for all of changefeeds (a la the one nathan has for the concurrency package or the one I wrote for snapshots).

However, as I mentioned offline, go ahead and merge and we can deal with this during stability period.

https://github.com/cockroachdb/cockroach/blob/5570c01402796edb7cd06eb8ce7f615371f22d42/pkg/kv/kvserver/concurrency/concurrency_control.go#L29-L147

https://github.com/cockroachdb/cockroach/blob/5570c01402796edb7cd06eb8ce7f615371f22d42/pkg/kv/kvserver/replica_command.go#L1672-L1782

**Comment by ajwerner** [comment]
Thanks for coming back to this.

> It's possible that we just need to bite the the bullet and write one for all of changefeeds (a la the one nathan has for the concurrency package or the one I wrote for snapshots).

They would definitely benefit from such a thing. I additionally think they have some room to get better. Just writing down the current structure will probably lead to better structure. I've got it mostly paged in at the moment, I can try to take a stab at starting such a comment.

Here's some thoughts generally on things I'd like to improve:

The memory monitoring isn't sane. I started hacking together a not very good roachtest to demonstrate the OOMs of a cluster with too many changefeeds (though I now realize I didn't need to actually create separate tables). https://github.com/cockroachdb/cockroach/pull/45882. I'm going to take a stab at making the changefeeds share a memory monitor and have some queuing to get memory. 

The buffering between the changeAggregator and sink is probably bad, though I need to lean on the benchmarks to understand that better. 

I'm not sure how I feel about the relationship between the schemafeed and the table lease manager. It's subtle that it works. It feels like just coming out of the schemafeed the machinery to convert kvs to rows should have access to the appropriate table descriptor without any need for schema leases. That's a win we get out of proving the schema. This simplifies the dependencies.

**Comment by ajwerner** [comment]
TFTR!

bors r=danhhz,nvanbenschoten

**Comment by ajwerner** [comment]
bors r=danhhz,nvanbenschoten

**Pull request merged**
