### PR TITLE
opt: fix TestExecBuild/local/limit flake

### LINKED ISSUE #71549: sql/opt/exec/execbuilder: TestExecBuild failed
sql/opt/exec/execbuilder.TestExecBuild [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3580398&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3580398&tab=artifacts#/) on master @ [2f2c517d2f2fd046ee25ad4dfe62c32f7eda6ac5](https://github.com/cockroachdb/cockroach/commits/2f2c517d2f2fd046ee25ad4dfe62c32f7eda6ac5):

```
                      estimated row count: 100 - 1,001 (100% of the table; stats collected <hidden> ago)
                      table: a@a_i_j_idx
                      spans: FULL SCAN
        but found (query options: "") :
            planning time: 10µs
            execution time: 100µs
            distribution: <hidden>
            vectorized: <hidden>
            rows read from KV: 176 (1.4 KiB)
            maximum memory usage: <hidden>
            network usage: <hidden>
            regions: <hidden>
            ·
            • limit
            │ nodes: <hidden>
            │ regions: <hidden>
            │ actual row count: 5
            │ KV time: 0µs
            │ KV contention time: 0µs
            │ KV rows read: 76
            │ KV bytes read: 608 B
            │ count: 5
            │
            └── • lookup join
                │ nodes: <hidden>
                │ regions: <hidden>
                │ actual row count: 5
                │ KV time: 0µs
                │ KV contention time: 0µs
                │ KV rows read: 76
                │ KV bytes read: 608 B
                │ table: b@b_k_s_idx
                │ equality: (j) = (k)
                │
                └── • scan
                      nodes: <hidden>
                      regions: <hidden>
                      actual row count: 100
                      KV time: 0µs
                      KV contention time: 0µs
                      KV rows read: 100
                      KV bytes read: 800 B
                      estimated row count: 100 - 1,001 (100% of the table; stats collected <hidden> ago)
                      table: a@a_i_j_idx
                      spans: FULL SCAN
--- done: testdata/limit with config local: 28 tests, 1 failures
--- done: testdata/distinct_on with config local: 32 tests, 0 failures
        --- FAIL: TestExecBuild/local/limit (10.50s)
=== RUN   TestExecBuild/local
    --- FAIL: TestExecBuild/local (0.00s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestExecBuild PKG=./pkg/sql/opt/exec/execbuilder TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries RaduBerinde
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestExecBuild.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by RaduBerinde**
The stats cache is updated asynchronously. We can fix this flake using
`retry`.

Fixes #71549.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71569#-:-MlzR4sl0vMzseXg_6HM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by Azhng — APPROVED** [review]
Thanks for the fix!

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71569)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
