### PR TITLE
release-21.2: ui: added formatting to statements on the statement & transaction details pages.

### PR DESCRIPTION
**Pull request by THardy98**
Backport 2/2 commits from #73853.

/cc @cockroachdb/release

---

Previously, statements displayed on the statement/transaction details
pages were not formatted.  Formatting was added to allow for better
readability of statements on these detail pages. Requested statements
are now formatted on the server using the existing pretty-printing
logic. Statements returned from the statement handler now include an
additional "formatted_statement" [field.](url)

Before changes:
Screen Shot 2022-01-04 at 9 47 03 AM

After changes:
Screen Shot 2022-01-04 at 9 37 56 AM

These formatting changes can also be seen on the transaction details page, databases page (now includes indentation for table creation statements), and the index details page.

Resolves: #71544

Release note (ui change): added formatting to statemenets on the
statement & transaction details pages.

Release justification: Category 4: Low risk, high benefit changes to existing functionality

### CODE REVIEW

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-Mt90fND59eLkMIsDify:-Mt90fND59eLkMIsDifz:bghnq1r) (no related file):*
Just pushed a small change - updating the bazel file and fixing a linting error.

Might be worth mentioning that CI triggered a lint failure on this PR but not on the original PR. The linting error was unused `LineWidthMode` in `pretty.go` (it should be assigned to the type of the `DefaultLineWidth` and `ConsoleLineWidth` constant variables).

Not sure why this wasn't caught in the CI of the original issue.

---

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-Mt9cA9Y5C6rVnURjMPB:-Mt9cA9Z5SJsXv5WPQfb:b-7npf7i) (no related file):*
Additional push to add changes to the old `appStats.ts` file in `db-console`. New versions do not have this file and import from `cluster-ui`.

---

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-Mt9mm4v6GwKxPc9zsho:-Mt9mm4v6GwKxPc9zshp:b-18yj02) (no related file):*
Made changes to the old `statementsPage.fixture.ts` file in `db-console`, added the new `aggregatedFingerprintID` to the fixture as well as the formatted statements. New versions do not have this file.

---

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-MtDl0hUBgBubiniPFmd:-MtDl0hUBgBubiniPFme:bs4rwv2) (no related file):*
Should be okay for review despite failing Bazel CI

https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1641918312090300

---

**Review by jocrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-MtDl0hUBgBubiniPFmd:-MtKFRAgDHk8K-ghFmKo:b-1gtygz) (no related file):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Should be okay for review despite failing Bazel CI

https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1641918312090300
</blockquote></details>

Frontend lgtm! Backend I'm not sure/don't know enough about why there isn't a change in this backport to `index_usage_stats.go` but otherwise it looks identical.

---

**Review by maryliag — APPROVED** [review]

**Comment by THardy98** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74677)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)
> 
> _[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/74677#-MtDl0hUBgBubiniPFmd:-MtKFRAgDHk8K-ghFmKo:b-1gtygz) (no related file):_
> 
> Previously, THardy98 (Thomas Hardy) wrote…
> Frontend lgtm! Backend I'm not sure/don't know enough about why there isn't a change in this backport to `index_usage_stats.go` but otherwise it looks identical.

The changes made to format index statements in `index_usage_stats.go` were based on Lindsey's changes to the index details page. Her changes weren't backported (and are not intended to be), so the code my changes were based off don't exist on previous versions.

**Pull request merged**
