### PR TITLE
opt: add support for unique constraints in the test catalog

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds support for unique constraints in the test catalog.
This will allow us to begin work on supporting uniqueness checks in
the optimizer.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt_catalog.go, line 1807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuTavsA34izfEoaPhd:-MKuTavsA34izfEoaPhe:b-5ql8kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt_catalog.go#L1807)):*
> ```Go
> // UniqueCount is part of the cat.Table interface.
> func (ot *optVirtualTable) UniqueCount() int {
> 	return 0
> ```

This is technically not a correct implementation of the catalog (even disregarding the new syntax), since we're not including unique indexes. I'd add a TODO to make that clear.
___
*[pkg/sql/opt/cat/table.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuTDxU16Pt_y3p6BFJ:-MKuTDxVA7mbKcOOyODD:b-23qbyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/cat/table.go#L127)):*
> ```Go
> 	InboundForeignKey(i int) ForeignKeyConstraint
> 
> 	// UniqueCount returns the number of unique constraints defined on this table.
> ```

[nit] Let's mention explicitly that here that this includes any unique constraints implied by unique indexes.
___
*[pkg/sql/opt/testutils/testcat/testdata/table, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuU0dD5W6lcfy9Hjl3:-MKuU0dD5W6lcfy9Hjl4:bdb5un0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/testutils/testcat/testdata/table#L94)):*
> ```
>  │    ├── a int
>  │    └── rowid int not null default (unique_rowid()) [hidden] (storing)
>  └── UNIQUE (a)
> ```

We should have a `UNIQUE (rowid)` too no?

**Review by mgartner — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/cat/table.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKvdhx5EWrvdxFSeqRK:-MKvdhx5EWrvdxFSeqRL:b-zemchm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/cat/table.go#L267)):*
> ```Go
> 
> 	// ColumnOrdinal returns the ith column ordinal (see Table.Column) in
> 	// the table on which this constraint is defined.
> ```

Is "returns the column ordinal in the table of the ith column of the unique constraint" more clear? Or  "returns the table column ordinal of the ith column in the unique constraint".

This "ordinal" term seems to create a lot of confusion. Maybe we should come up with some terms that make it clear whether the ordinal is the ordinal in the table or in the constraint/index/etc and use them everywhere for consistency.

Or maybe we should create `int` type aliases like `TableColumnOrdinal`, `IndexColumnOrdinal`, `ConstraintColumnOrdinal` to make things more clear?  Or should the function be named `TableColumnOrdinal`? Or maybe I'm the only one confused by this, in which case, no change is necessary :wink: !
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKvhN876X0tfE1VX4_b:-MKvhN876X0tfE1VX4_c:bnqtpug) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/testutils/testcat/create_table.go#L462)):*
> ```Go
> 	// Don't add duplicate constraints.
> 	for _, c := range tt.uniqueConstraints {
> 		if reflect.DeepEqual(c.columnOrdinals, cols) {
> ```

Why don't we allow duplicate constraints?

What if there is a unique constraint with the same columns but `withoutIndex=false`, and another with `withoutIndex=true`? Ditto for the `validated`?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-:-MKvnpmrDpUEW3V73ihB:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt_catalog.go, line 1807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuTavsA34izfEoaPhd:-MKvbmlL7MMiY3OjO_aV:b-ooe01i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt_catalog.go#L1807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is technically not a correct implementation of the catalog (even disregarding the new syntax), since we're not including unique indexes. I'd add a TODO to make that clear.
</blockquote></details>

Added a comment for `optTable` -- but I don't think `optVirtualTable` will have any unique constraints, will it?
___
*[pkg/sql/opt/cat/table.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuTDxU16Pt_y3p6BFJ:-MKvdJG43NU623YgrRuF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/cat/table.go#L127)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Let's mention explicitly that here that this includes any unique constraints implied by unique indexes.
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/table.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKvdhx5EWrvdxFSeqRK:-MKvl_aSD2lVtWzjCTrQ:bcibi31) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/cat/table.go#L267)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is "returns the column ordinal in the table of the ith column of the unique constraint" more clear? Or  "returns the table column ordinal of the ith column in the unique constraint".

This "ordinal" term seems to create a lot of confusion. Maybe we should come up with some terms that make it clear whether the ordinal is the ordinal in the table or in the constraint/index/etc and use them everywhere for consistency.

Or maybe we should create `int` type aliases like `TableColumnOrdinal`, `IndexColumnOrdinal`, `ConstraintColumnOrdinal` to make things more clear?  Or should the function be named `TableColumnOrdinal`? Or maybe I'm the only one confused by this, in which case, no change is necessary :wink: !
</blockquote></details>

Adding type aliases seems like it might be a good idea, but I think that should be a separate PR. Updated the comment for now.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKvhN876X0tfE1VX4_b:-MKvjGnqDCLSlXs4uY1s:b52ya2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/testutils/testcat/create_table.go#L462)):*
> Why don't we allow duplicate constraints?

It's just unnecessary, and it was cluttering the output for some of the tests with the duplicated indexes pattern.

> What if there is a unique constraint with the same columns but withoutIndex=false, and another with withoutIndex=true? Ditto for the validated?

`validated` is always true in the test catalog (for now). Added a check for `withoutIndex`.
___
*[pkg/sql/opt/testutils/testcat/testdata/table, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuU0dD5W6lcfy9Hjl3:-MKvg0MN84ZeUxWa4nlj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/testutils/testcat/testdata/table#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should have a `UNIQUE (rowid)` too no?
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/cat/table.go, line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKvdhx5EWrvdxFSeqRK:-MLE6sx9Dc8tkFyBraIr:b-j4tqk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt/cat/table.go#L267)):*
> but I think that should be a separate PR

:+1: Totally. Not an urgent thing, just something we can consider doing.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-:-MLEC6fH5h3VCYElCBMl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt_catalog.go, line 1807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-MKuTavsA34izfEoaPhd:-MLEBgkVEgMdO0iY-J9c:b-tnkdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc3d16578a6d6cdfe7c81adbce10a4a8979d6b7c/pkg/sql/opt_catalog.go#L1807)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Added a comment for `optTable` -- but I don't think `optVirtualTable` will have any unique constraints, will it?
</blockquote></details>

Yeah, I put the comment in the wrong place.

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56139#-:-MLKqyUI7mYaWEr4sIK3:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Pull request merged**
