### PR TITLE
gossip: replace stored contexts with AmbientContext

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of #9807.
@tamird @tschottdorf @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9965)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzm8MHpcZN-V626MQh:-KTzm8MIW7Iz462kSQ71:b-fl5iuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L189)):*
> ```Go
> 
> 		if log.V(1) {
> 			ctx := c.AnnotateCtx(context.TODO())
> ```

this can be `stream.Context()`

---

*[pkg/gossip/client.go, line 206 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzmJA_ADOAXVWZ4dcM:-KTzmJA_ADOAXVWZ4dcN:bm174ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L206)):*
> ```Go
> // handleResponse handles errors, remote forwarding, and combines delta
> // gossip infos from the remote server with this node's infostore.
> func (c *client) handleResponse(g *Gossip, reply *Response) error {
> ```

this function's caller has a context. easy refactor if you feel like it.

---

*[pkg/gossip/infostore.go, line 123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznUWRWHDBLRUJ_Hz4:-KTznUWSLxzTbugPDD42:b-tgnekm) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/infostore.go#L123)):*
> ```Go
> 	}); err != nil {
> 		ctx := is.AnnotateCtx(context.TODO())
> 		log.Errorf(ctx, "failed to properly construct string representation of infoStore: %s", err)
> ```

this pattern is absurd; we're running a string, we should just include the error in the returned string.

---

*[pkg/gossip/server.go, line 201 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznzmhQhpO0HgWaR4D:-KTznzmis0h3zyDsO10s:b-qi4pmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/server.go#L201)):*
> ```Go
> 	reply := new(Response)
> 
> 	ctx := s.AnnotateCtx(context.Background())
> ```

subjectively: do this in the caller (because that's closer to the RunWorker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-:-KTzoORam6hdVkzJ3V2z:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client.go, line 217 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzs3pgTciXD79Gf4c8:-KTzs3pgTciXD79Gf4c9:b-w7gqgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L217)):*
> ```Go
> 	c.nodeMetrics.InfosReceived.Inc(infosReceived)
> 
> 	ctx := c.AnnotateCtx(context.TODO())
> ```

how about we detect `context.TODO()` in `AnnotateCtx` and add a `?` tag 8-)

---

*[pkg/util/log/ambient_context.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzrCJGDADotT12GQaI:-KTzrCJH20L4OfScWpjJ:b-4oj364) ([raw file](https://github.com/cockroachdb/cockroach/blob/172366507d80fa100277e4ac302e2b7cbac576f0/pkg/util/log/ambient_context.go#L78)):*
> ```Go
> 
> // SetEventLog sets up an event log. Annotated contexts log into this event log
> // (unless they go to a span).
> ```

"unless there's an open Span"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-:-KTzsw4sll4lRIFFzBSE:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/gossip/client.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzm8MHpcZN-V626MQh:-KU1e2I_GccunRwYgHE2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L189)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this can be `stream.Context()`
</details>
Done.

---

*[pkg/gossip/client.go, line 206 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzmJA_ADOAXVWZ4dcM:-KU1eBAoYVCrrFQ1LgxP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L206)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this function's caller has a context. easy refactor if you feel like it.
</details>
Done.

---

*[pkg/gossip/client.go, line 217 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzs3pgTciXD79Gf4c8:-KU1eBuoNSNX_rmMiEFe:b-nhs22f) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L217)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> how about we detect `context.TODO()` in `AnnotateCtx` and add a `?` tag 8-)
</details>
I think it's a good idea to do temporarily if you're hunting down missing plumbing but it would be distracting otherwise. In many cases, you won't change anything visible in the logs by fixing the TODO properly.

---

*[pkg/gossip/infostore.go, line 123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznUWRWHDBLRUJ_Hz4:-KU1fKtWm6wAqCQVrn5b:bzci83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/infostore.go#L123)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this pattern is absurd; we're running a string, we should just include the error in the returned string.
</details>
Removed this case altogether (it's impossible to get an error above if the func never returns one).

---

*[pkg/util/log/ambient_context.go, line 78 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzrCJGDADotT12GQaI:-KU1fgY8SFCut03OOSF9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/172366507d80fa100277e4ac302e2b7cbac576f0/pkg/util/log/ambient_context.go#L78)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> "unless there's an open Span"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 22 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/gossip/server.go, line 201 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznzmhQhpO0HgWaR4D:-KU1hPbNu1or3Sc0YbuZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/server.go#L201)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> subjectively: do this in the caller (because that's closer to the RunWorker)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by tamird** [comment]
Reviewed 1 of 20 files at r3, 19 of 19 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzm8MHpcZN-V626MQh:-KU1wMuQRslGHP7ICBHD:b9u0wje) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Done.
</details>
Oh it's already annotated? Neat.

---

*[pkg/gossip/infostore.go, line 123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznUWRWHDBLRUJ_Hz4:-KU1wjO78tdYlpNdT-Zd:b-9hemwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/infostore.go#L123)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Removed this case altogether (it's impossible to get an error above if the func never returns one).
</details>
Can you make it a panic? Just to satisfy OCD (and in case of future changes).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by RaduBerinde** [comment]
Review status: 19 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/gossip/client.go, line 189 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTzm8MHpcZN-V626MQh:-KU2MeQwS4mlMXrI_Mjf:bmktmue) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/client.go#L189)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Oh it's already annotated? Neat.
</details>
Oh, wait, I guess not, fixed.

---

*[pkg/gossip/infostore.go, line 123 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KTznUWRWHDBLRUJ_Hz4:-KU2OdZI7On9jF5eO943:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43166d3298dfb6982579cd1714fb913dc0a8f81e/pkg/gossip/infostore.go#L123)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can you make it a panic? Just to satisfy OCD (and in case of future changes).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by tamird** [comment]
Reviewed 1 of 20 files at r5, 19 of 19 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client_test.go, line 58 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KU3F15QZaRug_Ppf49H:-KU3F15QZaRug_Ppf49I:bhj8dyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d86fbba119628e6ed9f7605f493589d43a5dd08a/pkg/gossip/client_test.go#L58)):*
> ```Go
> ) *Gossip {
> 	var ac log.AmbientContext
> 	ac.AddLogTagInt("n", int(nodeID))
> ```

how come this is needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client_test.go, line 58 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KU3F15QZaRug_Ppf49H:-KU3PCQZ1L2OvRJ1bTkV:b-7mykn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d86fbba119628e6ed9f7605f493589d43a5dd08a/pkg/gossip/client_test.go#L58)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come this is needed?
</details>
Because normally the server sets up the `nodeID` tag., and this is for tests so there is no server layer. We have had this conversation a couple of times before and we ended up not doing anything here, even though this helps debug tests. As a result of those discussions, I have #9344 which tracks sharing the `NodeID` between components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/client_test.go, line 58 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-KU3F15QZaRug_Ppf49H:-KU3Qd43bl3nO8T2CeJ6:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d86fbba119628e6ed9f7605f493589d43a5dd08a/pkg/gossip/client_test.go#L58)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Because normally the server sets up the `nodeID` tag., and this is for tests so there is no server layer. We have had this conversation a couple of times before and we ended up not doing anything here, even though this helps debug tests. As a result of those discussions, I have #9344 which tracks sharing the `NodeID` between components.
</details>
Ack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965)*

**Comment by RaduBerinde** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9965#-:-KU3S1xuIYW_lBAKkzP0:bz5mair)*

**Pull request merged**
