### PR TITLE
roachprod: added capability to set OS disk size for AWS, GCP

### PR DESCRIPTION
**Pull request by fabiog1901**
Added capability in `roachprod` to set the OS/root disk volume size in GB for AWS and GCP.

The global flag is `--os-volume-size`. 

At times you might want to install additional software, or run some simple tests that do not require additional disks.

Usage example:

```
bin/roachprod create fabio-test -n=1 -c aws|gce --os-volume-size=100
```

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
This looks great! Thank you very much.

I tested it and it worked as expected for GCE and AWS. \o/

Would you mind adding this change on top of yours to make it work also for Azure: https://gist.githubusercontent.com/rail/6b38e2fa5562db37fa5da8eab2855460/raw
Or I can push this change to this PR.

I have a few small nits as well.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65941#-:-MbctqXv4xfKMJkSUqUy:b-pl01e1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fabiog1901)

___
*[pkg/cmd/roachprod/vm/aws/aws.go, line 865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65941#-Mbcr-AAAdzOY6lheOag:-Mbcr-AAAdzOY6lheOah:b2z3o8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d85fe144974b18e430ddc596dd556358f687c6/pkg/cmd/roachprod/vm/aws/aws.go#L865)):*
> ```Go
> 
> 	osDiskVolume := &ebsVolume{
> 		DeviceName: "/dev/sda1",
> ```

According to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html it can be also `/dev/xvda` in some cases.  Maybe we should also expose this as a CLI parameter and default to `/dev/sda1`?
___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65941#-MbcpScqDAU3qz4ip0c1:-MbcpScqDAU3qz4ip0c2:b7304tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d85fe144974b18e430ddc596dd556358f687c6/pkg/cmd/roachprod/vm/gce/gcloud.go#L280)):*
> ```Go
> 			"use `gcloud compute images list --filter=\"family=ubuntu-2004-lts\"` to list available images")
> 
> 	flags.IntVar(&o.SSDCount, ProviderName+"-local-ssd-count", 0,
> ```

Can you add comments why you changed the default value here please.
___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65941#-Mbcpsdb8K5Z_ke2wfTl:-Mbcpsdb8K5Z_ke2wfTm:b-o6oftm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d85fe144974b18e430ddc596dd556358f687c6/pkg/cmd/roachprod/vm/gce/gcloud.go#L407)):*
> ```Go
> 		// See: https://cloud.google.com/compute/docs/disks/
> 		n2MachineTypes := regexp.MustCompile("^[cn]2-.+-16")
> 		if n2MachineTypes.MatchString(p.opts.MachineType) && p.opts.SSDCount == 1 {
> ```

I'd leave the initial check, because it better suites the comment below ("at least 2"). Who knows what edge cases we can hit and maybe have -3 disks :)

**Comment by fabiog1901** [comment]
Hi @rail , thanks for helping with the review! Here are my comments to yours, happy to chat if they are not clear:

1. Please go ahead and add the equivalent code for Azure (I'm afraid I'm not well versed with Azure, and last time I worked with it it wasn't as easy to configure root disk size)
2. True, root disk can be either `/dev/sda1|xvda1` but from reading the Device Name Consideration on that web doc, it seems AWS takes care of that mismatch when you pass `/dev/sda1` but it should have been `/dev/xvda1`:

> Depending on the block device driver of the kernel, the device could be attached with a different name than you specified. For example, if you specify a device name of /dev/sdh, your device could be renamed /dev/xvdh or /dev/hdh

>HVM AMIs do not support the use of trailing numbers on device names, except for /dev/sda1, which is reserved for the root device 

If you still think we should add an extra flag `--root-mount-point` we can certainly add it but I don't think is needed: it would be very tedious to know for which AMIs I must use one vs the other mount point, so I'd expect AWS to handle that.

3. The reason I updated the default && the check is because I wasn't able to provision a n2-standard-16 **without** local disks. If you check the logic, it forces you to provision it with at least 2 local disks. So the reasoning I went by is: let the user explicitly set how many local disks they want and only force the number of disks to 2 **if** the user choose 1 disks but the minimum is 2 (for that machine type).
4. The check is only applied to some machine types (`"^[cn]2-.+-16"`) and it should only catch the case where the disk is set to 1, which is invalid for that machine type. If the value is set to something negative like -3, that's handled by the for loop that comes right after (`for i := 0; i < p.opts.SSDCount; i++ {`), resulting in no disk being provisioned as the loop exits immediately.

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Pull request merged**
