### PR TITLE
sql: run postqueries with EXPLAIN ANALYZE

### LINKED ISSUE #45099: sql: postqueries not run under EXPLAIN ANALYZE
The explain analyze code doesn't run postqueries. This allows circumventing FK checks, for example:
```
create table p (p int primary key);
create table c (c int primary key, p int references p(p));
explain analyze insert into c select x,x+1 from (values (1),(2)) as v(x);
root@127.49.34.176:42397/movr> select * from c; 
  c | p
----+----
  1 | 2
  2 | 3
(2 rows)
```

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, postqueries didn't run when executing a query with EXPLAIN
ANALYZE. This is incorrect (for example, this allows for circumventing
foreign key checks) and is now fixed.

Fixes: #45099.

Release note: None (the bug is present only with experimental settings).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45155)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/explain_distsql.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-M0LPJ_W6d_lVzndQymh:-M0LPJ_W6d_lVzndQymi:b-em79ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/78206651a3ab74817b3c4ac4cb04c310748a2962/pkg/sql/explain_distsql.go#L105)):*
> ```Go
> 			params.extendedEvalCtx.Tracing,
> 		)
> 		if !distSQLPlanner.PlanAndRunSubqueries(
> ```

There are two other places where `PlanAndRunSubqueries` is called and `PlanAndRunPostqueries` is not:
1. `apply_join` (in `runPlanInsidePlan`)
2. `schema_changer` (in `maybeBackfillCreateTableAs`)

and I'm not sure whether it is ok.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45155)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/explain_distsql.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-M0LPJ_W6d_lVzndQymh:-M0O0zBrCLsQorlBgSjk:bmiyghv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78206651a3ab74817b3c4ac4cb04c310748a2962/pkg/sql/explain_distsql.go#L105)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

There are two other places where `PlanAndRunSubqueries` is called and `PlanAndRunPostqueries` is not:
1. `apply_join` (in `runPlanInsidePlan`)
2. `schema_changer` (in `maybeBackfillCreateTableAs`)

and I'm not sure whether it is ok.
</blockquote></details>

I don't think we can have mutations inside apply join.

I am not sure about the CTAS code, CCing @dt. I at least couldn't reproduce like this:
```
root@127.125.217.76:37749/movr> create table foo as with x as (insert into c values (1,1) returning c) select c from x;
ERROR: insert on table "c" violates foreign key constraint "fk_p_ref_p"
SQLSTATE: 23503
DETAIL: Key (p)=(1) is not present in table "p".
```

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-:-M0O2ML8Au4Va_GugZ5q:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @RaduBerinde)

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-:-M0P6XVqBs968fbE8myQ:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @jordanlewis)

___
*[pkg/sql/explain_distsql.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-M0LPJ_W6d_lVzndQymh:-M0P6SER6FlmzDooJV2q:b-kp8gbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78206651a3ab74817b3c4ac4cb04c310748a2962/pkg/sql/explain_distsql.go#L105)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think we can have mutations inside apply join.

I am not sure about the CTAS code, CCing @dt. I at least couldn't reproduce like this:
```
root@127.125.217.76:37749/movr> create table foo as with x as (insert into c values (1,1) returning c) select c from x;
ERROR: insert on table "c" violates foreign key constraint "fk_p_ref_p"
SQLSTATE: 23503
DETAIL: Key (p)=(1) is not present in table "p".
```
</blockquote></details>

Thanks for verifying!

**Comment by dt** [comment]
I don't know much about the SQL feature semantics for `CREATE TABLE ... AS` or what's allowed there, so I'll defer to the SQL Feature team about what can appear there (bulk-io is just responsible for writing whatever it emits -- regardless it is -- as fast as possible)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45155)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @jordanlewis)

___
*[pkg/sql/explain_distsql.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45155#-M0LPJ_W6d_lVzndQymh:-M0P8SHV8m34Soh3G8Wg:bmjkljf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78206651a3ab74817b3c4ac4cb04c310748a2962/pkg/sql/explain_distsql.go#L105)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Thanks for verifying!
</blockquote></details>

Maybe CTAS didn't reproduce the problem because optimizer-driven FK checks are not being used?

**Comment by yuzefovich** [comment]
Unrelated flakes, one more try.

bors r+

**Pull request merged**
