### PR TITLE
exec: fix possible infinite loops in the benchmark

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
@solongordon I think you were looking at this too?

@yuzefovich it might be easier to always include an element of mintint64 as the 0th element or something?

:lgtm: though.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37106#-:-LdRCPwE4nV0OTvftHK2:bqjmd12)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by solongordon — COMMENTED** [review]
My in-progress PR for null handling makes these benchmarks deterministic. No harm in merging this in the meantime.

It might also be nice to add a bit of logic to `repeatableBatchSource` which panics if `Next` is called some unrealistically high number of times, since I'm sure we'll hit this problem again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37106#-:-Ld_Bp1GAcrEvUMq2peK:b2u8gld)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
I liked Jordan's suggestion on how to simplify the logic a bit by putting a few specific values.

Not sure about the `repeatableBatchSource` - what that unrealistic number would be? I think that Golang itself panics after reaching the certain depth of the stack, right? And our logic would be very similar - we'd check for number of batches returned and panic with a custom message instead of Golang's.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37106#-:-Lde8TRx43iOY_cGsCOG:bogx65c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by solongordon — COMMENTED** [review]
I don't think there's recursion going on so we wouldn't hit a stack depth error. But yeah, don't know off the top of my head what a good number would be. Don't worry about it for this PR, just an idea.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37106#-:-LdeAS3H0rPTMoTQK3wY:bkxzime)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
