### PR TITLE
jwtauthccl: add support for custom CA

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
Added support for custom CA for verifying certificates from the JWT issuer domain. The JWT issuer domain hosts the JWKS configuration which is fetched to verify JWTs.
Added a cluster setting to accept the custom root CA. Updated the constructor of `httputil.Client` to accept functional options.

Epic: CRDB-38682

Release note (security update): Added
`server.jwt_authentication.issuer_custom_ca` cluster setting to support custom root CA for verifying certificates while fetching JWKS from the JWT issuer.

### CODE REVIEW

**Review by souravcrl — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @pritesh-lahoti, and @rafiss)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07iBNT5ghwRhYF0QvE:-O07iBNT5ghwRhYF0QvF:b-ugbmcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/settings.go#L29)):*
> ```Go
> 	JWTAuthClaimSettingName          = baseJWTAuthSettingName + "claim"
> 	JWKSAutoFetchEnabledSettingName  = baseJWTAuthSettingName + "jwks_auto_fetch.enabled"
> 	jWTAuthIssuerCustomCASettingName = baseJWTAuthSettingName + "issuer_custom_ca"
> ```

nit:  jWTAuthIssuerCustomCASettingName -> JWTAuthIssuerCustomCASettingName
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 874 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07vgqa2gsYDxAL5a_q:-O07vgqa2gsYDxAL5a_r:bi0wftf) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L874)):*
> ```Go
> 	}
> 
> 	certPEMBlock, err := securitytest.EmbeddedAssets.ReadFile(
> ```

Other implementations I see use https://github.com/cockroachdb/cockroach/blob/e514e0be2eef580fc3074375645dab6ec0fdeb06/pkg/security/certificate_loader.go#L318-L324
```
securityassets.GetLoader().ReadFile(fullCertPath)
```
Should we considering using `securityassets` here which was set previously?

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07iBNT5ghwRhYF0QvE:-O0AA9kY0roHafZXUqvc:bs4ewcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/settings.go#L29)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

nit:  jWTAuthIssuerCustomCASettingName -> JWTAuthIssuerCustomCASettingName
</blockquote></details>

I didn't see these constants being used outside of the package, hence did not choose to export.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 874 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07vgqa2gsYDxAL5a_q:-O0ABNhq-GtAJvb-zJvR:baepupk) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L874)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Other implementations I see use https://github.com/cockroachdb/cockroach/blob/e514e0be2eef580fc3074375645dab6ec0fdeb06/pkg/security/certificate_loader.go#L318-L324
```
securityassets.GetLoader().ReadFile(fullCertPath)
```
Should we considering using `securityassets` here which was set previously?
</blockquote></details>

Addressed. Thank you!

**Review by souravcrl — CHANGES_REQUESTED** [review]
`settings.html` has not been generated for the cluster setting. the doc referring to this: https://cockroachlabs.atlassian.net/wiki/spaces/ED/pages/1134068095/Generated+Docs+and+External+Dependencies#Cluster-settings

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0D-c0Z63esc6JEdQae:b-90lzwb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @pritesh-lahoti, and @rafiss)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07iBNT5ghwRhYF0QvE:-O0D-oHs3utAp4w6_z3h:bnd6qxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/settings.go#L29)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

I didn't see these constants being used outside of the package, hence did not choose to export.
</blockquote></details>

my bad. I thought this was a typo. Previously if there was an acronym we were doing all small or all block letters for that acronym:
https://github.com/cockroachdb/cockroach/blob/44d7da514c7c0d21411fa31caaa59457b413540a/pkg/ccl/oidcccl/authentication_oidc.go#L42-L60
like `idTokenKey`, `oidcJWTPath`, `oidcJWTPath`. I was thinking if this a private constant we should have it as `jwtAuthIssuerCustomCASettingName` in line with other private constants in the package.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0D2vrDAVR2oJdxbTaV:-O0D2vrE62LPqP-czH3i:bfbeq4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/05bb6da858e6d34e2c273eb7c97e67babff9d99e/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L933)):*
> ```Go
> 		identMap,
> 	)
> 	require.NoError(t, err)
> ```

Missed this earlier, I think we can define a test table(https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Test-Tables)
with a case for when custom CA set in cluster setting does not validate the jwt server key pair

**Review by souravcrl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @pritesh-lahoti, and @rafiss)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0DTpGhBcSqwkBp2xnO:-O0DTpGhBcSqwkBp2xnP:bk5s1am) ([raw file](https://github.com/cockroachdb/cockroach/blob/05bb6da858e6d34e2c273eb7c97e67babff9d99e/pkg/ccl/jwtauthccl/settings.go#L95)):*
> ```Go
> 		"If this is enabled, the server.jwt_authentication.jwks will be ignored.",
> 	false,
> 	settings.WithReportable(true),
> ```

We shouldn't have this as reportable inline with other `customCA` based cluster setting
https://github.com/cockroachdb/cockroach/blob/6330fa439fc783ceb5f0fa1f146f7819a6bc896b/pkg/cloud/cloud_io.go#L44-L49
This uses `settings.WithPublic` as the settings option

**Review by pritesh-lahoti — COMMENTED** [review]
I did run it, but it produced no output. Looks like it is able to generate the docs since the cluster setting visibility has been set to public. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0NF3sg1jTYxSaaRoRD:brqa8jm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O07iBNT5ghwRhYF0QvE:-O0NEDYn94hU6Icpywo6:b-6j90q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4d655731fbfa1a46627fca24aec1b73188bb7/pkg/ccl/jwtauthccl/settings.go#L29)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

my bad. I thought this was a typo. Previously if there was an acronym we were doing all small or all block letters for that acronym:
https://github.com/cockroachdb/cockroach/blob/44d7da514c7c0d21411fa31caaa59457b413540a/pkg/ccl/oidcccl/authentication_oidc.go#L42-L60
like `idTokenKey`, `oidcJWTPath`, `oidcJWTPath`. I was thinking if this a private constant we should have it as `jwtAuthIssuerCustomCASettingName` in line with other private constants in the package.
</blockquote></details>

Oh, right. Renamed to `jwtAuthIssuerCustomCASettingName`. Thank you!
___
*[`pkg/ccl/jwtauthccl/settings.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0DTpGhBcSqwkBp2xnO:-O0NETHv3RPgzX6YDbMN:bvljs2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/05bb6da858e6d34e2c273eb7c97e67babff9d99e/pkg/ccl/jwtauthccl/settings.go#L95)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

We shouldn't have this as reportable inline with other `customCA` based cluster setting
https://github.com/cockroachdb/cockroach/blob/6330fa439fc783ceb5f0fa1f146f7819a6bc896b/pkg/cloud/cloud_io.go#L44-L49
This uses `settings.WithPublic` as the settings option
</blockquote></details>

Addressed.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 933 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0D2vrDAVR2oJdxbTaV:-O0NmYu415ckMQZZu4-F:baepupk) ([raw file](https://github.com/cockroachdb/cockroach/blob/05bb6da858e6d34e2c273eb7c97e67babff9d99e/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L933)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Missed this earlier, I think we can define a test table(https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Test-Tables)
with a case for when custom CA set in cluster setting does not validate the jwt server key pair
</blockquote></details>

Addressed. Thank you!

**Review by rafiss — APPROVED** [review]
the cluster setting looks good to me! however, i don't work much with HTTP clients, so someone from the o11y team may be interested in taking a look. @dhartunian might be able to help find a good reviewer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0VBWC08T-5MK7e2VkS:b-4gs3mw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @souravcrl)

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @pritesh-lahoti, and @souravcrl)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0ij2NR5-Di3vrFLt4a:-O0ij2NS64jVJ25zJSkV:b-uq5yq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8545a89cea0fa288e55689aff3ebe2915bbb124f/pkg/ccl/jwtauthccl/settings.go#L85)):*
> ```Go
> 	"sets the custom root CA for verifying certificates while fetching JWKS from the JWT issuer",
> 	"",
> 	settings.WithPublic,
> ```

is there any sort of validation you can do on the CA to make sure it's parse-able etc?
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 931 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0ikD_x4E7EUfHZLol9:-O0ikD_x4E7EUfHZLolA:b-xwx9fo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8545a89cea0fa288e55689aff3ebe2915bbb124f/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L931)):*
> ```Go
> 		},
> 	} {
> 		if testCase.caCertName != "" {
> ```

nit: it's usually helpful to wrap each test case in a `t.Run` and add a `name string` param to the cases so you can easily distinguish which case failed in CI.

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @dhartunian, and @souravcrl)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0ij2NR5-Di3vrFLt4a:-O0jTvjb-V8Xy6-wbHyt:bank11f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8545a89cea0fa288e55689aff3ebe2915bbb124f/pkg/ccl/jwtauthccl/settings.go#L85)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there any sort of validation you can do on the CA to make sure it's parse-able etc?
</blockquote></details>

Of course. Have added. Thank you!
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 931 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0ikD_x4E7EUfHZLol9:-O0jU8uC08d22zOMUZd6:bvljs2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8545a89cea0fa288e55689aff3ebe2915bbb124f/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L931)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: it's usually helpful to wrap each test case in a `t.Run` and add a `name string` param to the cases so you can easily distinguish which case failed in CI.
</blockquote></details>

Addressed.

**Review by dhartunian — APPROVED** [review]
:lgtm: just a question about a removed comment.

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0pceSf0xhMggzJYMni:b-xuwjyh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar, @pritesh-lahoti, and @souravcrl)

___
*[`pkg/util/httputil/client.go` line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0p_gi69kznI5IL0oIb:-O0p_gi69kznI5IL0oIc:bhex373) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d362070be19565f0252af57296dfe8e8bbb8365/pkg/util/httputil/client.go#L40)):*
> ```Go
> 		Transport: &http.Transport{
> 			// Don't leak a goroutine on OSX (the TCP level timeout is probably
> 			// much higher than on linux).
> ```

do you know what this comment is talking about? is it correct to remove it?

**Review by pritesh-lahoti — COMMENTED** [review]
Thank you for catching. Have retained the original comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0rC9Zf2ZvBVRxhMxgB:b-k2trq9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @souravcrl)

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar, @dhartunian, and @souravcrl)

___
*[`pkg/util/httputil/client.go` line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-O0p_gi69kznI5IL0oIb:-O0rddbxBrrha3RRtSQV:b-f3kjkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d362070be19565f0252af57296dfe8e8bbb8365/pkg/util/httputil/client.go#L40)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

do you know what this comment is talking about? is it correct to remove it?
</blockquote></details>

Have retained the original comment.

**Review by souravcrl — COMMENTED** [review]
LGTM.

> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0rhpIa0-uAyqUgtzds:b-85i63v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @dhartunian)

**Review by souravcrl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126062#-:-O0ri1nG9eNG82QfaAx8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @dhartunian)

**Comment by pritesh-lahoti** [comment]
TFTRs!
bors r=dhartunian,souravcrl,rafiss

**Pull request merged**
