### PR TITLE
opt: make use of streaming group-by

### LINKED ISSUE #29161: opt: Cost-based optimizer doesn't select merge join
from logic_test/aggregate:
```
SELECT * FROM (SELECT x, max(y) FROM group_ord GROUP BY x) JOIN (SELECT z, min(y) FROM group_ord@foo GROUP BY z) ON x = z
```

EXPECTED: I expect the optimizer to use a merge join. Here is the heuristic planner's plan:
```
            tree            |     field      |    description
+---------------------------+----------------+-------------------+
  join                      |                |
   │                        | type           | inner
   │                        | equality       | (x) = (z)
   │                        | mergeJoinOrder | +"(x=z)"
   ├── group                |                |
   │    │                   | aggregate 0    | x
   │    │                   | aggregate 1    | max(y)
   │    │                   | group by       | @1
   │    └── render          |                |
   │         └── scan       |                |
   │                        | table          | group_ord@primary
   │                        | spans          | ALL
   └── group                |                |
        │                   | aggregate 0    | z
        │                   | aggregate 1    | min(y)
        │                   | group by       | @1
        └── render          |                |
             └── index-join |                |
                  ├── scan  |                |
                  │         | table          | group_ord@foo
                  │         | spans          | ALL
                  └── scan  |                |
                            | table          | group_ord@primary
```

ACTUAL: the cost-based optimizer uses a hash join:
```
          tree         |    field    |    description    |     columns      | ordering
+----------------------+-------------+-------------------+------------------+----------+
  join                 |             |                   | (x, max, z, min) |
   │                   | type        | inner             |                  |
   │                   | equality    | (x) = (z)         |                  |
   ├── group           |             |                   | (x, agg0)        |
   │    │              | aggregate 0 | x                 |                  |
   │    │              | aggregate 1 | max(y)            |                  |
   │    │              | group by    | @1                |                  |
   │    └── scan       |             |                   | (x, y)           |
   │                   | table       | group_ord@primary |                  |
   │                   | spans       | ALL               |                  |
   └── group           |             |                   | (z, agg0)        |
        │              | aggregate 0 | z                 |                  |
        │              | aggregate 1 | min(y)            |                  |
        │              | group by    | @2                |                  |
        └── index-join |             |                   | (y, z)           |
             ├── scan  |             |                   | (x, z)           |
             │         | table       | group_ord@foo     |                  |
             │         | spans       | ALL               |                  |
             └── scan  |             |                   | (y, z)           |
                       | table       | group_ord@primary |                  |
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: show ordered groupby columns in EXPLAIN

Release note: None

#### sql: fix bugs in streaming groupby distsql planning

Fixing two distsql planning bugs related to streaming group-by:
 - `orderedGroupCols` contains groupNode input columns, not indexes
   into `groupCols`.
 - props.ordering columns refer to output columns, not input columns.

With the heuristic planner, the grouping cols are always `@1-@x` so
these bugs only showed up with the optimizer.

Release note: None

#### opt: make use of streaming group-by

The execution path supports telling aggregation operations that there
is an ordering on a subset of the grouping columns, which causes the
aggregation to be performed in a "streaming" fashion: we accumulate
data from rows until the set of values on those ordered columns
change, at which point we emit the results and start fresh. This has
two benefits: it uses less memory; and it preserves the ordering on
those grouping columns.

This change implements passing ordering requirements on grouping
columns through `GroupBy`.

Fixes #29161.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm:, for the `opt` related changes

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-:-LLeWntyAph1NveGFYkP:b-str4y8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-LLeVUxpEoks6_aRky8H:-LLeVUxpEoks6_aRky8I:b5ufs8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa643a36045afea9717b368132d5bfa2daa8c2f3/pkg/sql/opt/xform/testdata/physprops/ordering#L349)):*
> ```
>       └── array-agg [type=int[]]
>            └── variable: c [type=int]
> ```

This set of tests feel a bit thin. I don't have enough context to suggest many other tests, but spend a bit of time making sure you've covered the interesting cases. Maybe:

- GROUP BY and ORDER BY columns don't have same order: `a, b` vs. `b, a` kind of thing
- GROUP BY and ORDER BY are interesting supersets/subsets of one another
- Other interesting interactions between required and internal orderings?

**Review by justinj — COMMENTED** [review]
Is it future work to explore to a group by operator which forces the input ordering? Unless I misunderstand, today we won't actively seek out these streaming group-bys unless the appropriate ordering is requested by a parent?

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-:-LLebJ8i-U6j87ujXS5d:b-sr22eu)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/physical_props.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-LLeaxwK3eR6dtCrnrdP:-LLeaxwL-bEJWDg3r9uC:bwp7jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa643a36045afea9717b368132d5bfa2daa8c2f3/pkg/sql/opt/xform/physical_props.go#L189)):*
> ```Go
> 			// to satisfy both orderings.
> 			//
> 			// DistinctOn is executed differently than GroupBy, in a way that retains
> ```

This comment is outdated now I think

**Review by RaduBerinde — COMMENTED** [review]
Correct.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-:-LLemNJF9XrNRCNc5VEA:btqqu5l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/physical_props.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-LLeaxwK3eR6dtCrnrdP:-LLemcT54RU3j3XM9F2e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa643a36045afea9717b368132d5bfa2daa8c2f3/pkg/sql/opt/xform/physical_props.go#L189)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This comment is outdated now I think
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29587)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29587#-LLeVUxpEoks6_aRky8H:-LLexH688-uPj1jlNU7p:b-wsclz) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa643a36045afea9717b368132d5bfa2daa8c2f3/pkg/sql/opt/xform/testdata/physprops/ordering#L349)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This set of tests feel a bit thin. I don't have enough context to suggest many other tests, but spend a bit of time making sure you've covered the interesting cases. Maybe:

- GROUP BY and ORDER BY columns don't have same order: `a, b` vs. `b, a` kind of thing
- GROUP BY and ORDER BY are interesting supersets/subsets of one another
- Other interesting interactions between required and internal orderings?
</blockquote></details>

Added a few more cases. There aren't as many interesting cases as for e.g. DistinctOn, because ORDER BY can only refer to group-by columns (or aggregation results, but in that case it never gets passed through).

**Pull request merged**
