### PR TITLE
 changefeedccl: add experimental support format=avro

### PR DESCRIPTION
**Pull request by danhhz**
Avro is specifically designed to encode data and to enforce backward
and/or forward compatibility of that data as its schema changes.

https://avro.apache.org/docs/current/

This commit adds a method to convert our internal respresention of a
table schema into an avro schema. Avro foundationally includes the
schema with the data, either in the same bytes as the encoded records or
by pointing at unique ID in some instance of the Confluent Schema
Registry. The convention with Kafka is the latter, so when the Avro
format is used, we require the user also provide the url of their schema
registry.

A bunch of column types are still unsupported and this needs some
end-to-end tests to make sure the table descriptor to avro schema
mapping is right, so no release note for now.

Release note: None

### CODE REVIEW

**Review by mrtracy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30379)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/avro.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30379#-LMiCOL68b6grNmry198:-LMiCOL68b6grNmry199:b-56quqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/437f2137aa206bb7957651575df969eb0cc23950/pkg/ccl/changefeedccl/avro.go#L232)):*
> ```Go
> }
> 
> // RowFromTextual decodes the given row data from avro's defined JSON format.
> ```

Are these decoding functions going to be used somewhere else? Right now they seem to be used only for the purpose of testing, which means they likely shouldn't be exported, or should be in the testing package.

I dunno, that seems a little pedantic though; it's likely fine as is.
___
*[pkg/ccl/changefeedccl/encoder.go, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30379#-LMi6PWr1Nkd8tZp-BQp:-LMi6PWr1Nkd8tZp-BQq:b-4dte8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/437f2137aa206bb7957651575df969eb0cc23950/pkg/ccl/changefeedccl/encoder.go#L241)):*
> ```Go
> ) ([]byte, error) {
> 	// TODO(dan): Is unsafe.Pointer as a map key okay?
> 	registered, ok := e.valueCache[unsafe.Pointer(tableDesc)]
> ```

Yikes, is there no other way to address a specific tableDesc?  I wonder how often the tableDesc you get is going to have the same memory address at the last time, even if it represents the same table/version. I don't think Go has a compacting GC, but I doubt the stability of memory addresses is guaranteed at all.

If the address is not guaranteed to match up between subsequent calls, this would lead to unbounded growth problems as the changefeed continues. Even if this is the case now, it's something subtle that could break later.

It's also not safe if a memory address gets re-used, or if the table descriptor gets mutated; highly unlikely, i'm guessing, but still an odd situation.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30379)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/avro.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30379#-LMiCOL68b6grNmry198:-LMiNVRV3NatpGIY7VXz:bf0pgcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/437f2137aa206bb7957651575df969eb0cc23950/pkg/ccl/changefeedccl/avro.go#L232)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Are these decoding functions going to be used somewhere else? Right now they seem to be used only for the purpose of testing, which means they likely shouldn't be exported, or should be in the testing package.

I dunno, that seems a little pedantic though; it's likely fine as is.
</blockquote></details>

they're used for `format=avro-json`
___
*[pkg/ccl/changefeedccl/encoder.go, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30379#-LMi6PWr1Nkd8tZp-BQp:-LMiN_hREmCTB_HkUBf0:b3z98v) ([raw file](https://github.com/cockroachdb/cockroach/blob/437f2137aa206bb7957651575df969eb0cc23950/pkg/ccl/changefeedccl/encoder.go#L241)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Yikes, is there no other way to address a specific tableDesc?  I wonder how often the tableDesc you get is going to have the same memory address at the last time, even if it represents the same table/version. I don't think Go has a compacting GC, but I doubt the stability of memory addresses is guaranteed at all.

If the address is not guaranteed to match up between subsequent calls, this would lead to unbounded growth problems as the changefeed continues. Even if this is the case now, it's something subtle that could break later.

It's also not safe if a memory address gets re-used, or if the table descriptor gets mutated; highly unlikely, i'm guessing, but still an odd situation.
</blockquote></details>

good point, this is relying a bit too much on the way that leasemanager caches these. replaced they key with table id and version

**Comment by danhhz** [comment]
Btw, manually verified this works with confluent platform:
```
$ ./confluent/bin/kafka-avro-console-consumer --topic=foo --from-beginning --bootstrap-server=localhost:9092 --property print.key=true
{"a":1}	{"a":1,"b":{"string":"foo"}}
```

**Review by mrtracy — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30379#-:-LMn5i2Q-wTvIGUaBfHk:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by danhhz** [comment]
TFTR

bors r=mrtracy

**Pull request merged**
