### PR TITLE
Add `SHOW LOGS` SQL grammar

### PR DESCRIPTION
**Pull request by miretskiy**
Add `SHOW LOGS` SQL grammar for a new statement that can
tail cluster logs via regular SQL shell.

This statement is restricted to the admin user.

To stream all logs, possibly restricted to specified nodes, use:
`SHOW ALL LOGS [FROM NODES nodeID,...] [WITH k=v, ...]`

Similarly, you can stream logs restricted to the specified regular
expression pattern.
`SHOW LOGS [FROM NODES nodeID,...] [MATCHING <pattern>] [WITH k=v, ...]`

Both flavors support optional `WITH` options:
 * `vmodule` option that can set `--vmodule` on each node where the
statement runs.
 * `duration` option that restricts the duration of command.

Because the logs are streamed as they arrive on each node, in order for
this statement to be useful, the caller should disable buffering when
invoking this statement (otherwise, 16KB worth of logs will be buffered
before they are emitted):
  `./cockroach sql --format=csv --url postgresql://....?results_buffer_size=64`

Release Notes: Add a new `SHOW LOGS` statement that can tail the logs
across the cluster.

### CODE REVIEW

**Comment by miretskiy** [comment]
Pushing this PR as a draft to get some feedback and to demonstrate the use of new log interceptor API changes
in https://github.com/cockroachdb/cockroach/pull/61378 can be leveraged

**Comment by knz** [comment]
The interceptor logic change is somewhat ok and desirable, 1

however this PR here is not. as I mentioned when we talked, log data is completely insecure and should not make its way through SQL. We must preserve a complete code isolation between the output of logging and the SQL client connections. There's a strong design assumptions at many layers in cockroachdb that the output of logging is never ingested again by the process. If we break this assumption we are going to create confidentiality breaches left, right and center.

**Review by knz — CHANGES_REQUESTED** [review]
supposing, hypothetically, you wanted to move forward with this,
you'd need:

- adequate PM-level discussion about what customer needs this is solving
- a thorough security analysis of the risks created by this work
- a thorough security analysis of *all* the logging calls throughout cockroachdb to ensure that no existing log call would cause sensitive information to leak this way (we never did this before)
- a training for the entire eng team to prevent insecure logging from ever being added in the future and preferably some corresponding linter technology

(cc @aaron-crl for review)

**Comment by knz** [comment]
Also this PR makes no accommodation for logging channels, configurability of redactability and logging format, and the fact that individual log entries can be so large that they will cause RAM usage to spike up in SQL  (and choke up pgwire and the RPCs)

**Comment by miretskiy** [comment]
@knz  Thanks for the feedback.

> Also this PR makes no accommodation for logging channels, configurability of redactability and logging format, and the fact that individual log entries can be so large that they will cause RAM usage to spike up in SQL (and choke up pgwire and the RPCs)

As I mentioned (in the title) -- this is a draft PR.   started off as a fun friday
project to learn a bit about dist flows.  I'm sure I'll get more feedback on it -- and
quite possibly, the right thing to do is to close this PR... I didn't want to add more functionality
w/out knowing that this would actually proceed.

> adequate PM-level discussion about what customer needs this is solving
  That is absolutely true. 
I would say it's more of a debugging/SRE problems this is solving.
Seeing the logs while things are happening, without having to wait (sometimes for a long time) 
to generate debug.zip is a very powerful tool.

> a thorough security analysis of the risks created by this work

 We can (and should) debate if this is better or worse than existing logspy, which, as @dt pointed out,
is a log steal functionality.  Security concerns are real.  I have gated this feature to admin only.
It might not be enough.  Perhaps a server command line flag to enable this feature might be a good idea.
I'm also curious as to the story around tracing.  We do have an internal table you can select from to 
view in flight traces... And, afaik, you can log pretty much anything into those traces -- seems like we already
have a way to examine potentially sensitive data.  Though again, I may be wrong, and I'm certainly not a security expert.

> a thorough security analysis of all the logging calls throughout cockroachdb to ensure that no existing log call would cause sensitive information to leak this way (we never did this before)

I use redacted logs -- I thought that was exactly what this facility accomplishes.

> a training for the entire eng team to prevent insecure logging from ever being added in the future and preferably some corresponding linter technology

Are redacted logs not sufficient?

**Pull request closed without merging**
