### PR TITLE
sql: Add ownership concept for objects

### PR DESCRIPTION
**Pull request by RichardJCai**
Added ownership when creating objects. Owners have ALL privilege on the object.

Currently, ownership cannot be changed, we will need to implement the
ALTER OWNER commands for all objects.

The privileges CREATE/DROP currently exist to alleviate missing privileges
from the lack of ownership, this PR does affect CREATE/DROP privileges.

Also added testuser2 certs to allow using testuser2 in logictests to test
inheritance between multiple roles.

Release note (sql change): Added "ownership" concept objects.
Objects must have an owner, all objects that do not have owners currently
will have admin set as the default owner except system objects.
System objects without owners will have node as their owner.
By default, owners are the creator of the object. Owners have all privileges
to the objects they own. Similarly, any roles that are members of the owner
role also have all privileges on the object.

### CODE REVIEW

**Comment by RichardJCai** [comment]
This is ready for review

**Review by knz — COMMENTED** [review]
Ok this is very good work and a good step forward.

Code-wise this mostly looks good but needs some polish, see below.

There's a major UX problem though: as soon as a user owns some objects they cannot be DROPped until their objects have been dropped to.

We discussed that already: you can either introduce the same mechanism as in pg to re-own an object to a different role/user; or add a CASCADE clause on DROP ROLE to also delete the owned objects. Or both.

> Reviewed 52 of 61 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-:-MDQFBioDFSXW6Ehg6e9:bwla74e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @RichardJCai, and @solongordon)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQBwzb9L7MwsWYAjmH:-MDQBwzd-7ceq4uE1jI8:b-w46zlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/ccl/importccl/read_import_pgdump.go#L246)):*
> ```Go
> 					id,
> 					hlc.Timestamp{WallTime: walltime},
> 					sqlbase.NewDefaultPrivilegeDescriptor(params.SessionData().User),
> ```

in the mysql case, you're checking if `params.SessionData()` is available. 
Why is this not happening here? (Question)
___
*[pkg/security/securitytest/test_certs/client.testuser2.crt, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCQPOCl3Wjyw_lkr9:-MDQCQPP4__ZrPVbnEfY:bqzepnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/security/securitytest/test_certs/client.testuser2.crt#L1)):*
> ```
> -----BEGIN CERTIFICATE-----
> ```

Unless you have a particular reason not to, I would revert all the changes to this directory except for the addition of the `testuser2` credentials and the edit to the readme file. I don't see a reason to replace every other test credential in this PR.
___
*[pkg/sql/authorization.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCyop4mzT4ObLkDEu:-MDQCyop4mzT4ObLkDEv:b-4kutjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L94)):*
> ```Go
> 	// privileges.
> 	// TODO(richardjcai): Add checks for if the user owns the parent of the object.
> 	// Ie, being the owner of a database gives access to all tables in the db.
> ```

Arguably, this TODO belongs as a comment on the `isOwner` function, not here.
___
*[pkg/sql/authorization.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCo08EcxvC5naH0Sf:-MDQCo08EcxvC5naH0Sg:b-42xm6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L95)):*
> ```Go
> 	// TODO(richardjcai): Add checks for if the user owns the parent of the object.
> 	// Ie, being the owner of a database gives access to all tables in the db.
> 	// Issue 51931.
> ```

nit: add the full issue URL, or write `#51931` (when searching for issue references we usually always include the `#` sign or URL prefix)
___
*[pkg/sql/authorization.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDIli0kZp3xf_DBHb:-MDQDIli0kZp3xf_DBHc:bvtbqnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L112)):*
> ```Go
> 
> 	// Expand role memberships.
> 	memberOf, err := p.MemberOfWithAdminOption(ctx, user)
> ```

This call and the loop below seem redundant with the new `HasOwnership` function below. IS there a way to factor them?
___
*[pkg/sql/create_schema.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDVlnBcS3MhiNplq2:-MDQDVlnBcS3MhiNplq3:b-zibs6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_schema.go#L112)):*
> ```Go
> 	}
> 
> 	// Inherit the parent privileges.
> ```

woah, this is quite a major change. 
1) can you explain the rationale in the commit message - what is this and how was it motivated? (It seems this is a fix for consistency with what is done already for tables sequences etc. If you think this is a bug fix, there may be an issue for it already.
2) add a call out in the release notes. If a bug fix, explain since when it was present and an example symptom.
___
*[pkg/sql/create_sequence.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQEBjh7XxSOmDTXZ6D:-MDQEBjh7XxSOmDTXZ6E:b-haz0r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_sequence.go#L93)):*
> ```Go
> 	// Inherit permissions from the database descriptor.
> 	privs := dbDesc.GetPrivileges()
> 	privs.SetOwner(params.SessionData().User)
> ```

Add the same `node `exception here as for tables.

Better yet: factor this code in a single function called from all the places.
___
*[pkg/sql/create_table.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQE-IuAUdMs1p5V3Db:-MDQE-IuAUdMs1p5V3Dc:bbtiskv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_table.go#L272)):*
> ```Go
> 
> 	privs := n.dbDesc.GetPrivileges()
> 	privs.SetOwner(params.SessionData().User)
> ```

I'd move these two new lines in the `else` branch of the `if` below.
___
*[pkg/sql/create_view.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQE4pV2XxK_BND5I2I:-MDQE4pV2XxK_BND5I2J:b-haz0r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_view.go#L119)):*
> ```Go
> 	// Inherit permissions from the database descriptor.
> 	privs := n.dbDesc.GetPrivileges()
> 	privs.SetOwner(params.SessionData().User)
> ```

Add the same `node `exception here as for tables.

Better yet: factor this code in a single function called from all the places.
___
*[pkg/sql/drop_role.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQEhrQ0Bna8IbMLy5J:-MDQEhrQ0Bna8IbMLy5K:b6pcgay) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/drop_role.go#L193)):*
> ```Go
> 			objectsMsg.WriteString(fmt.Sprintf("\nowner of %s %s", obj.ObjectType, obj.ObjectName))
> 		}
> 		return pgerror.Newf(pgcode.Grouping,
> ```

the pgcode here seems incorrect.

(check what pg uses in the same case)
___
*[pkg/sql/sqlbase/validate_test.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQF7Zi8DDK1bMr2fCV:-MDQF7Zi8DDK1bMr2fCW:b-q3tf6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/sqlbase/validate_test.go#L115)):*
> ```Go
> 					"perform validation. Need to know which version the descriptor is " +
> 					"in order to determine if an empty field is valid or not. " +
> 					"TODO(richardjcai): Add this field after implementing 51930."},
> ```

Is this disclaimer still needed?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @solongordon)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQBwzb9L7MwsWYAjmH:-MDRepwr4wyrh_UMJfKx:b-70crr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/ccl/importccl/read_import_pgdump.go#L246)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

in the mysql case, you're checking if `params.SessionData()` is available. 
Why is this not happening here? (Question)
</blockquote></details>

I think this should happen here as well, updated.
___
*[pkg/security/securitytest/test_certs/client.testuser2.crt, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCQPOCl3Wjyw_lkr9:-MDRet5604SULNlomzHs:b-ttqfi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/security/securitytest/test_certs/client.testuser2.crt#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Unless you have a particular reason not to, I would revert all the changes to this directory except for the addition of the `testuser2` credentials and the edit to the readme file. I don't see a reason to replace every other test credential in this PR.
</blockquote></details>

I was lazy and regenerated everything by running regenerate.sh, will revert the other changes.
___
*[pkg/sql/authorization.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCyop4mzT4ObLkDEu:-MDRfMKH17dIBxHiss54:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Arguably, this TODO belongs as a comment on the `isOwner` function, not here.
</blockquote></details>

Updated
___
*[pkg/sql/authorization.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQCo08EcxvC5naH0Sf:-MDRfABd71L4DSqVHfIp:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: add the full issue URL, or write `#51931` (when searching for issue references we usually always include the `#` sign or URL prefix)
</blockquote></details>

Fixed
___
*[pkg/sql/authorization.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDIli0kZp3xf_DBHb:-MDSALyS3gKMc7Cf56XR:bhkx1jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This call and the loop below seem redundant with the new `HasOwnership` function below. IS there a way to factor them?
</blockquote></details>

I agree, I think it does seem a little redundant. I added the HasOwnership function separately since it seems that in some cases, we only want to check for ownership whereas CheckPrivilege checks for a privilege or ownership. 

Example is RenameDatabase, we check for ownership or drop + admin, but checking for a privilege includes checking for ownership.

We can add the HasOwnership call inside the CheckPrivilege call and possibly make HasOwnership take in the roleMembership map to avoid expanding it again, although I'm not sure how much nicer/clearer this is, I don't mind the current duplication that much. What are your thoughts?
___
*[pkg/sql/create_schema.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDVlnBcS3MhiNplq2:-MDRgJNEDUwAyehjpHgg:b-pnlz1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_schema.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

woah, this is quite a major change. 
1) can you explain the rationale in the commit message - what is this and how was it motivated? (It seems this is a fix for consistency with what is done already for tables sequences etc. If you think this is a bug fix, there may be an issue for it already.
2) add a call out in the release notes. If a bug fix, explain since when it was present and an example symptom.
</blockquote></details>

This was already the behaviour, I just moved the call and comment outside of the function below. If you compare to revision 1, the logic is still the same except it sets the owner.
___
*[pkg/sql/create_sequence.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQEBjh7XxSOmDTXZ6D:-MDS8HxU7iZZAZ2ZcsZB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_sequence.go#L93)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add the same `node `exception here as for tables.

Better yet: factor this code in a single function called from all the places.
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQE-IuAUdMs1p5V3Db:-MDS8ljfD10lctCLcZ70:bo6g53t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_table.go#L272)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd move these two new lines in the `else` branch of the `if` below.
</blockquote></details>

Moved this to its own function, I have a return in the if clause and no else clause in the createInheritedPrivilegesFromDBDesc function, let me know what you think
___
*[pkg/sql/create_view.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQE4pV2XxK_BND5I2I:-MDS8w4l0kbXlcemkdCZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/create_view.go#L119)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add the same `node `exception here as for tables.

Better yet: factor this code in a single function called from all the places.
</blockquote></details>

Done.
___
*[pkg/sql/drop_role.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQEhrQ0Bna8IbMLy5J:-MDS8wmv8HYiKvOCGtQ7:b-e0b31v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/drop_role.go#L193)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the pgcode here seems incorrect.

(check what pg uses in the same case)
</blockquote></details>

Fixed, think I read the pgcode wrong in the first pass
___
*[pkg/sql/sqlbase/validate_test.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQF7Zi8DDK1bMr2fCV:-MDS90ncC9zTsdZZkEdZ:b-ms6y6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/sqlbase/validate_test.go#L115)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Is this disclaimer still needed?
</blockquote></details>

I think it is fine to leave until we implement #51930

**Review by knz — COMMENTED** [review]
> Reviewed 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @RichardJCai, and @solongordon)

___
*[pkg/sql/authorization.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDIli0kZp3xf_DBHb:-MDUF1966l_O0YSFhD8M:b-2lnle1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L112)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I agree, I think it does seem a little redundant. I added the HasOwnership function separately since it seems that in some cases, we only want to check for ownership whereas CheckPrivilege checks for a privilege or ownership. 

Example is RenameDatabase, we check for ownership or drop + admin, but checking for a privilege includes checking for ownership.

We can add the HasOwnership call inside the CheckPrivilege call and possibly make HasOwnership take in the roleMembership map to avoid expanding it again, although I'm not sure how much nicer/clearer this is, I don't mind the current duplication that much. What are your thoughts?
</blockquote></details>

Here's my thought:

```go
// FIXME: add the missing ctx args
func (p * planner) checkRolePredicate(user string, predicate func(role string) (bool, error)) (bool, error) {
       if ok, err := predicate(user); ok || err != nil {
         return ok, err
       }
       memberOf, err := p.MemberOfWithAdminOption(user)
	if err != nil {
		return false, err
	}
	for role := range memberOf {
          if ok, err := predicate(user); ok || err != nil {
             return ok, err
          }
	}
       return false, nil
}
```

Then here:

```go
hasPriv, err := p.checkRolePredicate(sessionUser, func(role string) (bool, error) {
      if isOwner(descriptor, role) { return true, nil }
      if privs.CheckPrivilege(role, privilege) { return true, nil }
})
if err != nil {
    return err
}
if !hasPriv {
   return pgerror.Newf(pgcode.InsufficientPRivilege)
}
```

And separately in `HasOwnership` below:

```go
func (p) HasOwnership(...) (bool, error) {
   return p.checkRolePredicate(..., func(...) ... {
       return isOwner(descriptor, role)
   })
}
``` 

:tada: 
___
*[pkg/sql/sqlbase/validate_test.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQF7Zi8DDK1bMr2fCV:-MDUGbI_6neyGx4v7JkP:b-2cov75) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/sqlbase/validate_test.go#L115)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think it is fine to leave until we implement #51930
</blockquote></details>

I don't see where in the code this version is used, hence my question. Can you point me to it?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @solongordon)

___
*[pkg/sql/authorization.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQDIli0kZp3xf_DBHb:-MDVSKlx0fhAPp09Hen6:b39dr2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/authorization.go#L112)):*
> // FIXME: add the missing ctx args
> func (p * planner) checkRolePredicate(user string, predicate func(role string) (bool, error)) (bool, error) {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>        if ok, err := predicate(user); ok || err != nil {
>          return ok, err
>        }
>        memberOf, err := p.MemberOfWithAdminOption(user)
</details>
> 	if err != nil {
> 		return false, err
> 	}
> 	for role := range memberOf {
>           if ok, err := predicate(user); ok || err != nil {
>              return ok, err
>           }
> 	}
>        return false, nil
> }

Good idea, I like this.
___
*[pkg/sql/sqlbase/validate_test.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDQF7Zi8DDK1bMr2fCV:-MDVC2TP53qKfLpsgiiV:be4rso2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b90a46e618b7d64e466e2b655fa5ef52c661b6/pkg/sql/sqlbase/validate_test.go#L115)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't see where in the code this version is used, hence my question. Can you point me to it?
</blockquote></details>

Oh, you're right this should be under PrivilegeDescriptor not TableDescriptor. 
There doesn't seem to be a PrivilegeDescriptor validation case here. I'll look into adding it.

**Review by solongordon — CHANGES_REQUESTED** [review]
:lgtm: with a few minor comments. I'm also going to circle back and take a closer look at your logic tests.

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-:-MDq5srtEpZxD0UjSDzf:bj86fee)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq4B1NEQ2gwNTZWAJ7:-MDq4B1NEQ2gwNTZWAJ8:bks7f28) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/drop_role.go#L182)):*
> ```Go
> 		fnl := tree.NewFmtCtx(tree.FmtSimple)
> 		defer fnl.Close()
> 		for i, name := range names {
> ```

I think it would be preferable to do what Postgres does here and only print out the first user which cannot be dropped along with what objects they own. Otherwise it's confusing as to who owns what.
___
*[pkg/sql/logictest/testdata/logic_test/owner, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq5AFjAR44B4GecBpB:-MDq5AFjAR44B4GecBpC:bwkqr3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/logictest/testdata/logic_test/owner#L28)):*
> ```
> DROP TABLE t
> 
> user testuser
> ```

redundant?
___
*[pkg/sql/sqlbase/privilege.proto, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq5YK73aRnP3LpiipR:-MDq5YK73aRnP3LpiipS:b-qhgqz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/sqlbase/privilege.proto#L30)):*
> ```protobuf
>   option (gogoproto.equal) = true;
>   repeated UserPrivileges users = 1 [(gogoproto.nullable) = false];
>   optional string owner = 41 [(gogoproto.nullable) = false];
> ```

Minor: Might as well this `2` rather than `41`.

**Comment by RichardJCai** [comment]
Changed the unit test from pgwire_test.go into a logic test in bytes. The unit test was really annoying to update, it's now a logic test in bytes under subtest Regression_4312

The original issue was https://github.com/cockroachdb/cockroach/issues/4312

```
{"SELECT descriptor FROM system.descriptor WHERE descriptor != $1 LIMIT 1", []preparedQueryTest{
	baseTest.SetArgs([]byte("abc")).Results([]byte("\x12%\n\x06system\x10\x01\x1a\x15\n\t\n\x05admin\x100\n\b\n\x04root\x100\"\x00(\x01")),
}},
```

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @miretskiy, and @solongordon)

___
*[pkg/sql/drop_role.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq4B1NEQ2gwNTZWAJ7:-MDr0dQdCh9k9N95gIze:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/drop_role.go#L182)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think it would be preferable to do what Postgres does here and only print out the first user which cannot be dropped along with what objects they own. Otherwise it's confusing as to who owns what.
</blockquote></details>

Fixed
___
*[pkg/sql/logictest/testdata/logic_test/owner, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq5AFjAR44B4GecBpB:-MDr0brnCFQKCaxnbH2i:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/logictest/testdata/logic_test/owner#L28)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed
___
*[pkg/sql/sqlbase/privilege.proto, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq5YK73aRnP3LpiipR:-MDr0eQ660TehmAaomzK:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/sqlbase/privilege.proto#L30)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Minor: Might as well this `2` rather than `41`.
</blockquote></details>

Updated.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @miretskiy, and @solongordon)

___
*[pkg/sql/drop_role.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-MDq4B1NEQ2gwNTZWAJ7:-MDr0h4o6fWOQn3NmX0Z:b-vlduk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae63b18fc6e129dbfe68b66ecbebb77e9db536f8/pkg/sql/drop_role.go#L182)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

I think we'll also want to do this for privileges as well and combine the error messages, opened an issue for it.
#52314

**Review by solongordon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51856#-:-MDzVmJh5Gms5qIBl1fe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @miretskiy)

**Comment by RichardJCai** [comment]
Thanks for the review!

**Comment by RichardJCai** [comment]
bors r=solongordon

**Comment by knz** [comment]
The bors run was aborted because of the merge conflict. This needs to be rebased.

**Comment by RichardJCai** [comment]
bors r=solongordon

**Pull request merged**
