### PR TITLE
sql: implement pg_prepared_statements virtual table

### LINKED ISSUE #41778: sql: virtual schema table not implemented: pg_catalog.pg_prepared_statements
The PGJDBC test `testSelectPrepareThreshold0AutoCommitFalseFetchSizeNonZero` uses this catalog table, but it doesn't work.

### PR DESCRIPTION
**Pull request by otan**
* resolves #41778
* add List() to the prepared statements accessor
* implemented pg_prepared_statements, with some fun caveats
   * i think we always use wire format, so from_sql is always false?
   * had to add an extra data type for CreatedAt, not sure how to increment SizeOf here with the location variable set.
   * other caveats are documented as a comment.

Release note (sql change): introduces pg_prepared_statements table for use

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
Left a few minor comments

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-:-LsTKRyZClrDBsOZKP-M:bonxhx6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTJhnK4vIVLn67oKt4:-LsTJhnK4vIVLn67oKt5:btvvnbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/conn_executor.go#L2347)):*
> ```Go
> // List is part of the preparedStatementsAccessor interface.
> func (ps connExPrepStmtsAccessor) List() map[string]*PreparedStatement {
> 	// Return a copy of the data, to prevent modification of the map.
> ```

The map isn't being modified by the function that calls List() . Do we need to make this copy?
___
*[pkg/sql/pg_catalog.go, line 1804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTK3l9--gphJi1ymA8:-LsTK3l9--gphJi1ymA9:by0jtax) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1804)):*
> ```Go
> 			if err := addRow(
> 				tree.NewDString(name),
> 				tree.NewDString("PREPARE "+name+argumentsStr+" AS "+stmt.SQL+";"),
> ```

You could use `fmt.Sprintf` here
___
*[pkg/sql/pg_catalog.go, line 1809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsT7p6RD5TneevZ2zDI:-LsT7p6RD5TneevZ2zDJ:b-b16xu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1809)):*
> ```Go
> 				tree.DBoolFalse, // from_sql
> 			); err != nil {
> 				return err
> ```

You could simplify this by simply returning addRow(...) and removing the `return nil` below

**Review by yuzefovich — COMMENTED** [review]
Nice work getting this done so quickly! A few comments from me.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-:-LsTX8Zl5VXSRlQGVrH7:b-spm8mx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/conn_executor.go, line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTJhnK4vIVLn67oKt4:-LsTUag27niAF-FlQPIW:b7gstzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/conn_executor.go#L2347)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The map isn't being modified by the function that calls List() . Do we need to make this copy?
</blockquote></details>

I think I'd rather be on the safe side and return a copy (unless there is a huge performance burden). This way, in case some other function will modify the map later, the bug will be avoided.
___
*[pkg/sql/pg_catalog.go, line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTSaUTAbZ-pioHZEuw:-LsTSaUTAbZ-pioHZEux:b-281u3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1766)):*
> ```Go
> // The statement field differs in that it uses the parsed version
> // of the PREPARE statement.
> // The from_sql statement will always return false, as we use the wire protocol.
> ```

I don't think this is true - if we're talking to CRDB via CLI we could issue a `PREPARE` statement, and I think `from_sql` would be true in that case. cc @mjibson
___
*[pkg/sql/pg_catalog.go, line 1804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTK3l9--gphJi1ymA8:-LsTVJeTDx5SgMCtHgf2:b-acfdv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1804)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You could use `fmt.Sprintf` here
</blockquote></details>

I agree, that's what we usually do (same goes for `argumentsStr` above).
___
*[pkg/sql/pg_catalog.go, line 1809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsT7p6RD5TneevZ2zDI:-LsTSBZH5T_bobq0CacB:b-1zx4ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1809)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You could simplify this by simply returning addRow(...) and removing the `return nil` below
</blockquote></details>

I don't think so - here we're returning from inside of the loop, but `return nil` is outside of it.
___
*[pkg/sql/prepared_stmt.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTVZny6ZxasTHfjZm_:-LsTVZny6ZxasTHfjZma:b-x5ivlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/prepared_stmt.go#L82)):*
> ```Go
> // of prepared statements.
> type preparedStatementsAccessor interface {
> 	// List returns all prepared statements as a map keyed by name.
> ```

[nit]: I'd call out explicitly that the map is a copy.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTW6Yr3BnG0cFcw2EC:-LsTW6Yr3BnG0cFcw2ED:b-cxfmsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1844)):*
> ```
> 
> statement ok
> CREATE TABLE types(a timestamptz, b integer);
> ```

[super nit]: semicolons are not needed in the logic test queries.
___
*[pkg/sql/sqlbase/prepared_statement.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTWJfA1fu2BYJdfwTt:-LsTWJfA1fu2BYJdfwTu:b-g5y2fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/sqlbase/prepared_statement.go#L44)):*
> ```Go
> 	InferredTypes []oid.Oid
> 
> 	// CreatedAt is the timestamp this prepare statement was made.
> ```

[nit]: I feel like preposition `at` is missing at the end.
___
*[pkg/sql/sqlbase/prepared_statement.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTWVN54_oUwSGSYZ7l:-LsTWVN54_oUwSGSYZ7m:b-ehu11w) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/sqlbase/prepared_statement.go#L67)):*
> ```Go
> 
> 	// This is missing pm.CreatedAt.Location.
> 	// TODO: confirm whether we should add it in.
> ```

I'd add use `unsafe.Sizeof(time.Time{})` as the size of a single `CreatedAt` (which should evaluate to 24 bytes). time.Time has a pointer to `time.Location`, and I feel like that actual `time.Location` struct is cached and is shared among different timestamps. Feel free to dig in and figure that out :)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @yuzefovich)

___
*[pkg/sql/pg_catalog.go, line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTSaUTAbZ-pioHZEuw:-LsTfbbI2u6fhYt1Qwnk:bhio9g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1766)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think this is true - if we're talking to CRDB via CLI we could issue a `PREPARE` statement, and I think `from_sql` would be true in that case. cc @mjibson
</blockquote></details>

Yahor is correct. However, I'm not sure we currently distinguish between the two. If we don't, it's probably best to leave this as is (as false) and mark it with a TODO in the code. We should probably only spend time implementing it correctly if we can demonstrate an ORM that cares.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTJhnK4vIVLn67oKt4:-LsTZdsZ5pSugYEug1Kh:bww5vaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/conn_executor.go#L2347)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I'd rather be on the safe side and return a copy (unless there is a huge performance burden). This way, in case some other function will modify the map later, the bug will be avoided.
</blockquote></details>

I was following the style guide, which tells me to as long as it isn't a perf burden... I don't think this is (for now)
___
*[pkg/sql/pg_catalog.go, line 1766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTSaUTAbZ-pioHZEuw:-LsTiokw2Jmg9lgHbPt_:b4vb7kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1766)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yahor is correct. However, I'm not sure we currently distinguish between the two. If we don't, it's probably best to leave this as is (as false) and mark it with a TODO in the code. We should probably only spend time implementing it correctly if we can demonstrate an ORM that cares.
</blockquote></details>

i think we found a way. so marking this as done.
___
*[pkg/sql/pg_catalog.go, line 1804 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTK3l9--gphJi1ymA8:-LsTjb0o8h7mMq8F0v40:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1804)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I agree, that's what we usually do (same goes for `argumentsStr` above).
</blockquote></details>

Done.
___
*[pkg/sql/pg_catalog.go, line 1809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsT7p6RD5TneevZ2zDI:-LsTjewR0VI40wvBYLQ2:brywaka) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1809)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think so - here we're returning from inside of the loop, but `return nil` is outside of it.
</blockquote></details>

yes, this is in a loop.
___
*[pkg/sql/prepared_stmt.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTVZny6ZxasTHfjZm_:-LsTjtZQALwa4O5WIWDp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/prepared_stmt.go#L82)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd call out explicitly that the map is a copy.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTW6Yr3BnG0cFcw2EC:-LsTk-6G3MQZ755IZ9jZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1844)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: semicolons are not needed in the logic test queries.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/prepared_statement.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTWJfA1fu2BYJdfwTt:-LsTk53v24tJEGouuI64:b-7hjbva) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/sqlbase/prepared_statement.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I feel like preposition `at` is missing at the end.
</blockquote></details>

don't feel strongly but i think both are okay.
___
*[pkg/sql/sqlbase/prepared_statement.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsTWVN54_oUwSGSYZ7l:-LsTkCLl6gD2cjt-ZLKS:b-9spxyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/sqlbase/prepared_statement.go#L67)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd add use `unsafe.Sizeof(time.Time{})` as the size of a single `CreatedAt` (which should evaluate to 24 bytes). time.Time has a pointer to `time.Location`, and I feel like that actual `time.Location` struct is cached and is shared among different timestamps. Feel free to dig in and figure that out :)
</blockquote></details>

I don't think we need to, as res := int64(unsafe.Sizeof(*pm)) should take care of it
see https://play.golang.org/p/ysgmEWFvAwa

trusting you on the cachedness :P

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @yuzefovich)

___
*[pkg/sql/pg_catalog.go, line 1809 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsT7p6RD5TneevZ2zDI:-LsUJmz00OeyurSInt9D:b-q1omgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/00cadd21d24d89cc51bd875e705d2fa5690b9540/pkg/sql/pg_catalog.go#L1809)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yes, this is in a loop.
</blockquote></details>

My bad, I missed the loop.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-:-LsYZrlE8J796Px-6wWk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @mjibson, @otan, and @yuzefovich)

___
*[pkg/sql/prepared_stmt.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsYZJfWEyOub9EjvxYg:-LsYZJfWEyOub9EjvxYh:b8jz6zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f638f1f424ae9247b9cc47469a6d774d13b3313/pkg/sql/prepared_stmt.go#L104)):*
> ```Go
> type preparedStatementsAccessor interface {
> 	// List returns all prepared statements as a map keyed by name.
> 	// The map itself is a copy the prepared statements.
> ```

[nit]: `s/copy/copy of/g`.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1859 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42018#-LsYZlHg3ZQCLwRRewnd:-LsYZlHg3ZQCLwRRewne:b-ye7zkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f638f1f424ae9247b9cc47469a6d774d13b3313/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1859)):*
> ```
> 
> statement ok
> DROP TABLE types;
> ```

[super nit]: last semicolon :)

**Review by arulajmani — APPROVED** [review]

**Pull request merged**
