### PR TITLE
[MINIRFC] Add no-client and passive operation

### PR DESCRIPTION
**Pull request by tbg**
[ci skip]

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6283)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/RFCS/drain_modes.md, line 18 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGD_w-PD7k2csoJoU5W:-KGD_w-Q5QQ2t-ZZgvwa:-446858842) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L18)):*
I'm not thrilled with the `no-client` and `passive` terminology. I kept on having to refer back here to understand what `no-client` and `passive` referred to. How about `drain-clients` and `drain-leaders` or something like that?

Btw, the two drain new modes seem independent. It isn't clear to me why you can't enter `no-client` while simultaneously refusing new leader leases. Why do they have to be distinct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/drain_modes.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDgGBh3MrgXXpouufM:-KGDgGBh3MrgXXpouufN:-784970506) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L11)):*
There's another draining mode: when taking a node out of service permanently, we want the rebalancer to move all ranges away from it. This may or may not be combined with one of the other new modes (we could prevent the node from accepting clients or becoming leader while it's in this state, but it's not necessary)

---

*[docs/RFCS/drain_modes.md, line 18 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGD_w-PD7k2csoJoU5W:-KGDgkAIyiWIthWCHH-6:-2117601592) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L18)):*
If you enter `passive` mode before draining all clients, performance will suffer as the client will need to go through an extra hop to find the leader (if the range has fallen quiescent). I think it's best to go through this progression but not strictly necessary.

I agree with the naming concerns: maybe `drain-clients`, `drain-leadership` and `drain-ranges`? And I'd make them a set instead of a single value so we're not locked in to a certain progression.

---

*[docs/RFCS/drain_modes.md, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDlwZ5fTDC8LGGgQC8:-KGDlwZ5fTDC8LGGgQC9:-542267962) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L72)):*
We should do some research about how widely-supported these error codes are. For example, `pgbouncer` doesn't seem to do anything with them. I'm concerned that in practice the best way to load balance clients may turn out to be a tcp-level tool like `haproxy`, in which case we may have to use cruder techniques (e.g. closing the listening socket, which would also imply re-separating pgport from the unified port).

---

*[docs/RFCS/drain_modes.md, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDnLNjf7iELApWKMUK:-KGDnLNjf7iELApWKMUL:900432460) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L80)):*
We should try to close existing connections while they're idle (i.e. after a command finishes but before we send the `serverMsgReady`). If a command comes in while the server is draining we should execute it and then close afterwards. If no command comes in then we can just close the connection (which will race against the possibility that a client is sending a command at that time, but there's not much we can do about that in the postgresql protocol).

We should also consider this in the context of file descriptor limits (#6230): if we're close to the limit we would like to be able to shed load by draining idle connections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-:-KGDpxO8VNJLKYG_j4NI:676834233)*

**Comment by tschottdorf** [comment]
Updated, PTAL.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/drain_modes.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDgGBh3MrgXXpouufM:-KGDu_DwTihlmMZ_YyWC:-1757800999) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L11)):*
See the motivation section below - I was trying to avoid conflating that circle of ideas with this. There's the draining mode you're mentioning, but also that where you're only moving certain ranges off - I don't think they all need their own modes, they're just going to be commands that switch to drain-clients mode and then do maintenance of one type or another (and I'm sure there will be more operations that we don't anticipate yet). Or is there something I'm missing?

---

*[docs/RFCS/drain_modes.md, line 18 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGD_w-PD7k2csoJoU5W:-KGDvkxqw0AM6ryvtGVP:1583998349) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L18)):*
`drain-client` and `drain-leadership` sound good to me. I commented on `drain-ranges` above (essentially that moving ranges off is one of many maintenance operations we're going to have and that those shouldn't all have their own "operation modes").

I renamed the terms used as suggested above.

Updated as well to reflect independence of the drain modes.

---

*[docs/RFCS/drain_modes.md, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDlwZ5fTDC8LGGgQC8:-KGDyeEWM30IYeLKQHPL:23526862) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L72)):*
added as out of scope and filed #6295.

---

*[docs/RFCS/drain_modes.md, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-KGDnLNjf7iELApWKMUK:-KGDzHm_vDIcDsfC_sYD:1087609733) ([raw file](https://github.com/cockroachdb/cockroach/blob/2416ad476a3653872bb35d210c45fc438376f353/docs/RFCS/drain_modes.md#L80)):*
Added this to the proposal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6283#-:-KGE0KN58_5YmPs18zYX:-1677991115)*

**Comment by tschottdorf** [comment]
Let's continue the discussion on the implementation, https://github.com/cockroachdb/cockroach/pull/6313.

**Comment by JackKrupansky** [comment]
Is there any intent for draining to deal with the RocksDB level issue of flushing memtables to disk so that the entire WAL will not have to be replayed on restart?

Independent of any migration-oriented draining, is there a concept of administratively forcing a Rocks-level flush? Is/Should that be under the umbrella of draining? Is there any automatic/forced flushing or the option to do so on a shutdown? Or to do so periodically or on some schedule (like once a day during off-peak hours)>

Cassandra has separate flush and drain operations.

**Comment by tschottdorf** [comment]
Good point, we should be doing this at shutdown at some point down the road. Also easy enough to add to the UI once requested. For the purpose of this thread, I consider it out of scope.

**Pull request merged**
