### PR TITLE
ui: add event log entries for multi-region operations

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits.

### CODE REVIEW

**Review by otan — APPROVED** [review]
what about ALTER TABLE LOCALITY?
what about DROP ENUM?

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63099#-:-MXYmTWdAOQqsBKvWz3P:belfb6w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — COMMENTED** [review]
ALTER TABLE LOCALITY should be taken care of under umbrella ALTER TABLE event. Tacked on a couple more commits for `ALTER TYPE`, which should serve as an umbrella for DROP VALUE, and `DROP TYPE`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63099#-:-MXYuNPP5IAK9zI1Ynoq:b-bi6nou)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! 

bors r=otan

**Pull request merged**
