### PR TITLE
ui: fix typo in node map onboarding screen

### LINKED ISSUE #25096: ui: typo in node map onboarding screen
image

> Step 3: Refer this configuration guide to configure the Node Map.

Missing 'to'. Should be 
> Refer to [this guide](https://www.cockroachlabs.com/docs/v2.0/enable-node-map.html) to configure the roadmap

### PR DESCRIPTION
**Pull request by vilterp**
Fixes #25096

Before;
image

After:
image

Release note (admin ui change): fix typo in node map onboarding screen

### CODE REVIEW

**Comment by couchand** [comment]
Thanks for knocking this out.  @nstewart suggested alternate wording to avoid the stilted "configuration ... configure" which seems reasonable.  Thoughts on that?

**Comment by couchand** [comment]
Ping @vilterp

**Comment by vilterp** [comment]
Whoops, this fell by the wayside. How's this? 
image

I like it because it's more explicit about what you actually need to do next.

**Comment by couchand** [comment]
LGTM

**Pull request merged**
