### PR TITLE
authors: add <sideny> to authors

### PR DESCRIPTION
**Pull request by sidenyl**
Release note: None

### CODE REVIEW

**Review by jenngeorge — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74429#-:-Msl6Ne0CHzeyjYitzfW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

**Review by jlinder — APPROVED** [review]
:lgtm:

To merge this, ask Craig (our Bors bot) to merge by writing a comment with a line containing `bors r+`.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74429#-:-MslRncS70x9JkMpmpcY:bhn3hqt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sidenyl)

**Pull request merged**
