### PR TITLE
roachtest/cdc: fix cdc/mixed-versions deadlock

### LINKED ISSUE #128173: roachtest: cdc/mixed-versions failed
roachtest.cdc/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298784?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16298784?buildTab=artifacts#/cdc/mixed-versions) on master @ [78fa126dfc749e620c28531c1659e35bf98034ec](https://github.com/cockroachdb/cockroach/commits/78fa126dfc749e620c28531c1659e35bf98034ec):

```
(test_runner.go:1301).runTest: test timed out (2h0m0s)
test artifacts and logs in: /artifacts/cdc/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16298784/cdc-mixed-versions/1722587468232/1722594839604)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #127517 roachtest: cdc/mixed-versions failed [A-cdc C-test-failure O-roachtest O-robot T-cdc branch-release-24.2]
</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40845

### PR DESCRIPTION
**Pull request by wenyihu6**
**roachtest/cdc: fix cdc/mixed-versions deadlock**

Previously, cmvt.timestampsResolved.C could deadlock if it receives more
timestamps after waitAndValidate have received all of resolved timestamps they
are waiting for. This patch changes it to be a buffered channel with a size of
resolvedTimestampsPerState and is now unblocking.

Fixes: https://github.com/cockroachdb/cockroach/issues/128173
Release note: none

----

**roachtest/cdc: add more debugging lines to cdcMixedVersionTester**

This patch adds more debugging lines to cdcMixedVersionTester for
cmvt.timestampsResolved.C.

Epic: none
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
Tested in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16386337?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=16386337_5635_2250.5981.5990.5999&logFilter=debug&logView=flowAware.

**Review by renatolabs — APPROVED** [review]
Thanks for fixing!

**Comment by wenyihu6** [comment]
TFTR! The CI failure on cockroach-microbench-ci looks irrelevant. 

bors r=renatolabs

**Comment by renatolabs** [comment]
blathers backport 24.2 24.1 23.2

**Pull request merged**
