### PR TITLE
Refactor the Java acceptance test.

### PR DESCRIPTION
**Pull request by knz**
This patch pulls out Java code in separate standalone .java files
and generalizes template substitution.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4578)

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KB9qLogHZqpui2d0slh:-1605766289) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
The substitution is pretty ugly; I think we should get rid of it so the tests are plain non-pre-processed java files. The point of `testDockerFail` is to make sure that if the test failed the response code would be passed back correctly, so we just need some way to force an error at runtime (a command-line flag or environment variable)

---

*[acceptance/main.java, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9q3HmndMbM0x703zK:-KB9q3HmndMbM0x703zL:-668329523) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L1)):*
It will get pretty messy to have files in lots of different languages in the `acceptance` directory; can we make a subdirectory `acceptance/java`?

---

*[acceptance/main.java, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9r2bcRpjAbTgAwFyt:-KB9r2bdrm-C-CiDyLS3:548707193) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L6)):*
Use either tabs or spaces for indentation; don't mix them and assume that a tab is equivalent to 8 spaces. I think we've standardized on 2-space indents for non-go code.

---

*[acceptance/main.java, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9pzfgSxvGcBVkc1O_:-KB9pzfhhVikE1NdYZ4E:-864239453) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L20)):*
How does this even work? We're not applying the substitution to main.java

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/main.java, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9q3HmndMbM0x703zK:-KB9sGjz9kd-ZwTjGwS_:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L1)):*
+1

---

*[acceptance/TestStatements.tmpl.java, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9ry2WurBQvr4IJ-V-:-KB9ry2WurBQvr4IJ-V0:439575849) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/TestStatements.tmpl.java#L7)):*
man, this really does not seem worth the interpolation now. Can we just write plain java and have two tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/main.java, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9r2bcRpjAbTgAwFyt:-KB9sjheBa0aA8ZU6jpz:-1069218715) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L6)):*
We didn't standardize on using tabs for tabs just like go does? :(

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by mjibson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KB9tU54DZXF0qYijwyt:-83581432) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
I think the reason it's being done this way is that a future PR is adding a few more java tests, and would like to use the common connection logic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KB9uYS0wixlrbEOMIpk:-1681139804) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
What if we compiled a single JAR that ran all our java tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by knz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KB9tpjRn7pg0CTbjFAT:-1790846521) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
Yes please see how I am using this in https://github.com/knz/cockroach/blob/empty-row-desc/acceptance/java_test.go.

---

*[acceptance/main.java, line 1 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9q3HmndMbM0x703zK:-KB9ttscRDQhCdbqFi6B:180046683) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L1)):*
ok I'll have a look.

---

*[acceptance/main.java, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9r2bcRpjAbTgAwFyt:-KB9ty50r8rGH9nByfEW:1643511451) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L6)):*
Ow :sob:

---

*[acceptance/main.java, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9pzfgSxvGcBVkc1O_:-KB9uCoMtGblLBWwyEv3:1275815243) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L20)):*
Oops wrong file committed.

---

*[acceptance/TestStatements.tmpl.java, line 7 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9ry2WurBQvr4IJ-V-:-KB9uG9JP3WCfuZLsySp:-302089438) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/TestStatements.tmpl.java#L7)):*
Yeah I think that might be best.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by bdarnell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KB9vyolWyTTiqxAH4og:-37846232) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
Preprocessing the source is not the way to go. The tests should be customizable using the command line or environment so the source doesn't have to change. We should generally just have one `testDockerSuccess` call per language which will run all of that language's tests (which should be defined in the language's standard idioms wherever possible - is junit or some equivalent part of the standard library for java these days or would we have to figure out how to handle external java dependencies to be able to use it?)

---

*[acceptance/main.java, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9r2bcRpjAbTgAwFyt:-KB9xNqrSXHZEmVFmNt6:454649669) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L6)):*
I'd be fine with tabs-only as well, but we went with 2-space indents for our `.ts` files.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by knz** [comment]
Ok guys this is not the ultimate Java acceptance refactoring PR. I *really* want to get *something* going in order to move forward with #4548 and #4550 and ultimately #4036. I propose that once *this* PR is merged and I can go on with #4548, we file another issue to make this Java testing even better than it is now post-Beta.

**Comment by knz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/java_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9qLogHZqpui2d0slg:-KBA-GwkN6MUllyNs9X-:-1693559620) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/java_test.go#L30)):*
@bdarnell yes this is possible however there is no preprocessing going on any more in the latest commit. 

---

*[acceptance/main.java, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KB9r2bcRpjAbTgAwFyt:-KBA-Rd3I1k1qOiBOZzz:-1347491299) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c56e1623ac94e677137b440f656dac3a1d4d747/acceptance/main.java#L6)):*
Spaces it is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 8 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[acceptance/java/runjava.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0Ak9j0USQlxjUHaY:-KBA0Ak9j0USQlxjUHaZ:-1406794258) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L1)):*
nit: no space after the shebang, and i think this can be `sh`

---

*[acceptance/java/runjava.sh, line 2 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA067H-fO9939wbkKp:-KBA067H-fO9939wbkKq:1195340916) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L2)):*
probably a good idea to set `-u` as well.

---

*[acceptance/java/runjava.sh, line 11 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0OnNWKj-KGXN94yb:-KBA0OnNWKj-KGXN94yc:347585857) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L11)):*
don't you always want this file compiled? i think you can drop this argument.

---

*[acceptance/java/runjava.sh, line 12 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0bEjm5LauxiScfuz:-KBA0bEjm5LauxiScfv-:264846554) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L12)):*
you should trap EXIT and clean this up, then you can avoid the `-f`

---

*[acceptance/java/TestPlaceholders.java, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA-txwSH77hhE9eRCX:-KBA-txwSH77hhE9eRCY:-1306712674) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/TestPlaceholders.java#L25)):*
let's throw a better exception here, yeah?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-:-KBA0WCqacmeH8xWOR7-:676834233)*

**Comment by knz** [comment]
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[acceptance/java/runjava.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0Ak9j0USQlxjUHaY:-KBA1Te3hDcIpifgWK5j:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L1)):*
Done.

---

*[acceptance/java/runjava.sh, line 2 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA067H-fO9939wbkKp:-KBA1XJwdXuPALBRbuza:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L2)):*
Done.

---

*[acceptance/java/runjava.sh, line 11 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0OnNWKj-KGXN94yb:-KBA1Z4i6lBLKnOpVjkW:988424166) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L11)):*
The test for #4550 will use a different DB URL.

---

*[acceptance/java/runjava.sh, line 12 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0bEjm5LauxiScfuz:-KBA1eAzxTT1bh3U4ICY:1219952483) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L12)):*
Code saved vs code gained, etc.

---

*[acceptance/java/TestPlaceholders.java, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA-txwSH77hhE9eRCX:-KBA1ieiRVKdZeJH9bDn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/TestPlaceholders.java#L25)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by bdarnell** [comment]
LGTM but I still think it would be worthwhile to make the test configurable at runtime instead of swapping out which classes get compiled in. 

---

Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-:-KBAN8qN2vjv1MYvC0Ff:-2129680710)*

**Comment by tamird** [comment]
Reviewed 1 of 10 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[acceptance/java/runjava.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0Ak9j0USQlxjUHaY:-KBAayaAojb1L_gr_iMH:-263007232) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L1)):*
eh, i meant `#!/usr/bin/env sh`

---

*[acceptance/java/runjava.sh, line 2 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA067H-fO9939wbkKp:-KBAb085lGeGGNY6Ujtn:-943908377) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L2)):*
sorry to nit, but we usually keep it alphabetical with `set -eux`

---

*[acceptance/java/runjava.sh, line 12 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0bEjm5LauxiScfuz:-KBAb5PtqYip779qisrF:-1217517366) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L12)):*
it's not about gaining or saving code, it's about not polluting the file system

---

*[acceptance/java/TestPlaceholders.java, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA-txwSH77hhE9eRCX:-KBAbA0bHGo_kY9-kiRK:-1786903999) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/TestPlaceholders.java#L25)):*
Can we include the actual values? how is anyone going to debug this with the current message?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by knz** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[acceptance/java/runjava.sh, line 1 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0Ak9j0USQlxjUHaY:-KBCHb6LVO3CXwD-dhUy:919903488) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L1)):*
That is not necessary. POSIX says 'sh' lives in /bin.

---

*[acceptance/java/runjava.sh, line 12 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA0bEjm5LauxiScfuz:-KBCI5T9sIYPomWRw2lV:434671310) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/runjava.sh#L12)):*
Right  now this doesn't work anyways so I'll refactor.

---

*[acceptance/java/TestPlaceholders.java, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578#-KBA-txwSH77hhE9eRCX:-KBCIUDwqXHFSziI8_oC:648619580) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5295a2f4cd0c93f7ec0678fcfdbb3889a32f59/acceptance/java/TestPlaceholders.java#L25)):*
This is a   refactoring PR not enhancement.  I'll file a separate issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4578)*

**Comment by knz** [comment]
Closing in favor of #4591.

**Pull request closed without merging**
