### PR TITLE
importccl: add throughput telemetry

### LINKED ISSUE #46519: Import Telemetry: Ability to compare import characteristics to performance
**Is your feature request related to a problem? Please describe.**
When considering future improvements to import, it's important to know what types of imports people are running and what their relative performance is. The ability to tie file size, rows, number of files, and throughput can help us identify common patterns to solve for.

**Describe the solution you'd like**
- Job IDs tied to telemetry (or some other unique ID)
- Throughput metrics on input (or whatever else gives us most actionable insight into performance of IMPORT)

**Additional context**
We already have telemetry for file size, # of files, import type, and rows. We just don't have a way to tie those together with performance.

### PR DESCRIPTION
**Pull request by dt**
As we work on optimizing IMPORT performance, collecting some performance information
will make it easier to measure our progress.

Fixes #46519 

Release note (sql change): The IMPORT statement now records some additonal anonymous telemetry about its performance and reliability.

Release justification: low-risk, high impact.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
LGTM, mod one minor question.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46731#-:-M3gJBuHDJ8i8q8FecQv:btevth4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 1151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46731#-M3gIcnc8tQ5E7-wDF2t:-M3gIcnc8tQ5E7-wDF2u:b-dwe0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/78e74d1e371cf73bdcd331d2705d6cf9fa56a744/pkg/ccl/importccl/import_stmt.go#L1151)):*
> ```Go
> 	// Tiny imports may skew throughput numbers due to overhead.
> 	if sizeMb > 10 {
> 		telemetry.CountBucketed("import.speed-mbps.over10mb", mbps)
> ```

Question since I'm not super familiar with telemetry: if we decide to change this threshold in the future, would it be annoying to see all "not small" backups as a single metric? Specifically, I'm thinking if there's an advantage to doing "import.speed-mbps.over.10mb" so then we can look at all of the "import.speed-mpbs.over" metrics to get a sense of the number of "not small" ones if we decide that the threshold should be something like 50mb in the future.

**Review by pbardea — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46731#-:-M3gJfmzDlDC0Hg2-iW6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @pbardea)

**Comment by dt** [comment]
they're just strings keys -- the dots and such mean nothing beyond to us humans, so presumably if we later decided we wanted to sum up all the over buckets (though I'm not sure we would since presumable over10 includes over100?) `over.*` and `over*` are the same.

**Comment by pbardea** [comment]
Ah, good to know -- thanks for the explanation.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
