### PR TITLE
kv/kvnemesis: include support for deleterange operations

### LINKED ISSUE #64815: kvnemesis: add DeleteRange
We should extend kvnemesis to issue DeleteRange requests.

### LINKED ISSUE #67437: kvnemesis: support ReturnKeys option in DeleteRange operations
We should support the ReturnKeys option in DeleteRange requests in kvnemesis.

### PR DESCRIPTION
**Pull request by AlexTalks**
Adds DeleteRange operations to the potential operations
performed by kvnemesis.  This adds additional validation on these
KV operations, which were not previously tested by the tool.

This also includes adding a `returnKeys` parameter to `db.DelRange(..)`
and `txn.DelRange(..)`, returning the keys deleted in the operation 
when true.

Closes #64815, Closes #67437

### CODE REVIEW

**Comment by AlexTalks** [comment]
Depends on https://github.com/cockroachdb/cockroach/pull/67044

**Review by ajwerner — COMMENTED** [review]
The one line in schema_changer.go :lgtm:, removing the @cockroachdb/sql-schema reviewer

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-:-MhQqIzO-2MJyK0Qif4_:b-p3ye44)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/schema_changer.go, line 2200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MhQqDOA8BFhlItBaCy2:-MhQqDOA8BFhlItBaCy3:b-blknwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb6eb078fe6e9ee0357135cd696e0f27b6d9b8e/pkg/sql/schema_changer.go#L2200)):*
> ```Go
> 				}
> 				// Delete the zone config entry for this database.
> 				if _, err := p.ExecCfg().DB.DelRange(ctx, zoneKeyPrefix, zoneKeyPrefix.PrefixEnd(), false); err != nil {
> ```

nit can you comment or const the bool?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 10 files at r6, 23 of 23 files at r9, 20 of 20 files at r10, 10 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/db.go, line 556 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi2zgCN16ig3BDR34vH:-Mi2zgCN16ig3BDR34vI:b-jh195t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319421d43e6dc0659f89f5ed7b6bfe81f6d4571/pkg/kv/db.go#L556)):*
> ```Go
> //
> // The returned []roachpb.Key will contain the keys deleted if the returnKeys
> // parameter is true.
> ```

Mind spelling out what it will contain if `returnKeys` is false?
___
*[pkg/kv/db_test.go, line 456 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi2zw731xcS6NjgURYN:-Mi2zw74CU9BHOFyLRxy:b-bfe7ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319421d43e6dc0659f89f5ed7b6bfe81f6d4571/pkg/kv/db_test.go#L456)):*
> ```Go
> }
> 
> func TestDB_Del(t *testing.T) {
> ```

Do we not have a `TestDB_DelRange`? If not, I think it would be valuable to write one, modeled off `TestDB_Del`. You can then add two subtest variants using `testutils.RunTrueAndFalse`, one that passes `returnKeys` as true and one that passes `returnKeys` as false.
___
*[pkg/kv/txn.go, line 620 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-Mb02ieJz3BtrD2Z:-Mi3-Mb02ieJz3BtrD2_:b6tyxp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdaa69677a6a358e8d26d89d4eb93c3ef46f8f9/pkg/kv/txn.go#L620)):*
> ```Go
> //
> // The returned []roachpb.Key will contain the keys deleted if the returnKeys
> // parameter is true, and Result.Err will indicate success or failure.
> ```

Same point about detailing what the return value will contain is returnKeys is false.
___
*[pkg/kv/kvclient/kvcoord/txn_correctness_test.go, line 168 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-c-PAdEfoaVJjIDm:-Mi3-c-PAdEfoaVJjIDn:b-vp2afo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdaa69677a6a358e8d26d89d4eb93c3ef46f8f9/pkg/kv/kvclient/kvcoord/txn_correctness_test.go#L168)):*
> ```Go
> // deleteRngCmd deletes the range of values from the db from [key, endKey).
> func deleteRngCmd(ctx context.Context, c *cmd, txn *kv.Txn) error {
> 	_, err := txn.DelRange(ctx, c.getKey(), c.getEndKey(), false)
> ```

`false /* returnKeys */`
___
*[pkg/kv/kvnemesis/applier.go, line 144 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-qUv9iLDNMACdaB8:-Mi3-qUv9iLDNMACdaB9:bjadej4) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier.go#L144)):*
> ```Go
> 			o.Txn = savedTxn.TestingCloneTxn()
> 		}
> 	case *DeleteRangeOperation:
> ```

We discussed this in person. The plan is to try to remove this and instead ban non-transactional delete ranges by adjusting the generator and panicking in `applyClientOp` and `applyBatchOp` when appropriate.
___
*[pkg/kv/kvnemesis/applier.go, line 224 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi30GeR3aU1ObxYIXQp:-Mi30GeR3aU1ObxYIXQq:b-6kwk9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier.go#L224)):*
> ```Go
> 		o.Result = resultError(ctx, err)
> 	case *DeleteRangeOperation:
> 		deletedKeys, err := db.DelRange(ctx, o.Key, o.EndKey, true)
> ```

`true /* returnKeys */`
___
*[pkg/kv/kvnemesis/applier.go, line 228 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31_5x89kd-w8vBZW2:-Mi31_5x89kd-w8vBZW3:b-5mh2ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier.go#L228)):*
> ```Go
> 			o.Result = resultError(ctx, err)
> 		} else {
> 			o.Result.Type = ResultType_Values
> ```

Do we want to introduce a new `ResultType_Keys` and `Keys [][]byte` field on the `Result` type?
___
*[pkg/kv/kvnemesis/applier_test.go, line 85 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31pKrA6W3oRiYNLCo:-Mi31pKrA6W3oRiYNLCp:b1kzlat) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier_test.go#L85)):*
> ```Go
> 	check(t, step(put(`d`, `4`)), `db1.Put(ctx, "d", 4) // nil`)
> 
> 	check(t, step(delRange(`b`, `d`)), `db0.DelRange(ctx, "b", "d") // (["c"], nil)`)
> ```

Shouldn't we add new tests, instead of replacing these? We're losing test coverage right now.
___
*[pkg/kv/kvnemesis/generator.go, line 511 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi30XIx-2EI12N-5AEH:-Mi30XIx-2EI12N-5AEI:bj3anfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/generator.go#L511)):*
> ```Go
> 	// We don't write any new keys to `g.keys` on a DeleteRange operation,
> 	// because DelRange(..) only deletes existing keys.
> 	key, endKey := randKey(rng), randKey(rng)
> ```

Should we pull out a `randSpan` helper that we can use here and in `randScan`?
___
*[pkg/kv/kvnemesis/operations.go, line 243 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi30jaX4qkntOkCGtn3:-Mi30jaX4qkntOkCGtn4:bpu7ewz) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/operations.go#L243)):*
> ```Go
> 
> func (op DeleteRangeOperation) format(w *strings.Builder, fctx formatCtx) {
> 	fmt.Fprintf(w, `%s.DelRange(ctx, %s, %s)`, fctx.receiver, roachpb.Key(op.Key), roachpb.Key(op.EndKey))
> ```

This is missing `, true` in the string, right?
___
*[pkg/kv/kvnemesis/operations.proto, line 70 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi311B-Aw3GvxX7ri39:-Mi311B-Aw3GvxX7ri3A:bai7adq) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/operations.proto#L70)):*
> ```protobuf
>   bytes end_key = 2;
>   Result result = 3 [(gogoproto.nullable) = false];
>   roachpb.Transaction txn = 4;
> ```

Do we need this to include the transaction if we ban non-transactional delete range requests?
___
*[pkg/kv/kvnemesis/operations_test.go, line 44 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31BfC6q3maSG8uaYq:-Mi31BfC6q3maSG8uaYr:b-kv04um) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/operations_test.go#L44)):*
> ```Go
> 			step: step(
> 				closureTxn(ClosureTxnType_Commit,
> 					batch(get(`g`), get(`h`), delRange(`i`, `j`)),
> ```

nit: want to add it instead of replacing?
___
*[pkg/kv/kvnemesis/validator.go, line 380 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31ISB4Gz7HF8xIfAA:-Mi31ISB4Gz7HF8xIfAB:b-dm677k) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator.go#L380)):*
> ```Go
> 		} else {
> 			for _, kv := range t.Result.Values {
> 				write := &observedWrite{
> ```

Consider pointing to the comment right above this.
___
*[pkg/kv/kvnemesis/validator.go, line 385 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi32Uu05Ie49MeaLn9V:-Mi32Uu141LnKU0g2kDa:b69wbkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator.go#L385)):*
> ```Go
> 				}
> 				v.observedOpsByTxn[*txnID] = append(v.observedOpsByTxn[*txnID], write)
> 			}
> ```

Discussed in person. We're going to want to also consider this an observed read (an `observedScan` but maybe with a new `keysOnly` flag?). That will allow us to assert that the DelRange decided to delete the exact keys we expected it to.
___
*[pkg/kv/kvnemesis/validator_test.go, line 39 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31OXlDP5vrzq-YoxI:-Mi31OXlDP5vrzq-YoxJ:bb7xhmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator_test.go#L39)):*
> ```Go
> 		0,
> 	)
> 	switch o := op.GetValue().(type) {
> ```

I think this will also go away.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvnemesis/applier.go, line 228 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31_5x89kd-w8vBZW2:-Mi3PW12Aur8f32EMbJ7:b-qliu60) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier.go#L228)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to introduce a new `ResultType_Keys` and `Keys [][]byte` field on the `Result` type?
</blockquote></details>

It seems a bit duplicative in the Result protobuf to have `repeated bytes keys` and `repeated KeyValue values`, but if you think it's helpful in this case?
___
*[pkg/kv/kvnemesis/applier_test.go, line 85 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31pKrA6W3oRiYNLCo:-Mi3QHzC63k3Cekgu5bG:b-hm63iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier_test.go#L85)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't we add new tests, instead of replacing these? We're losing test coverage right now.
</blockquote></details>

OK.- Good point, fixing
___
*[pkg/kv/kvnemesis/applier_test.go, line 85 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3QWnd9hsV5d4yABi9:-Mi3QWnd9hsV5d4yABiA:bnuysyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c36a9dedeeee4387e7834957f7bf302b60b67ad/pkg/kv/kvnemesis/applier_test.go#L85)):*
> ```
> check(t, step(delRange(`b`, `d`)), `db0.DelRange(ctx, "b", "d") // (["c"], nil)`)
> ```
___
*[pkg/kv/kvnemesis/operations.go, line 243 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi30jaX4qkntOkCGtn3:-Mi3tire4IueAewtbQVa:bjuu4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/operations.go#L243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is missing `, true` in the string, right?
</blockquote></details>

Done - Good call, thanks!
___
*[pkg/kv/kvnemesis/operations.proto, line 70 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi311B-Aw3GvxX7ri39:-Mi3sxc3CuwbUqSRYRTk:bq7p2ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/operations.proto#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this to include the transaction if we ban non-transactional delete range requests?
</blockquote></details>

Done: Nope - removed in pending commit!
___
*[pkg/kv/kvnemesis/validator.go, line 380 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31ISB4Gz7HF8xIfAA:-Mi3sRPW1wyKYGolaPuE:b-6pjz8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator.go#L380)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider pointing to the comment right above this.
</blockquote></details>

OK - Added comment.
___
*[pkg/kv/kvnemesis/validator.go, line 385 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi32Uu05Ie49MeaLn9V:-Mi3rJm5AITHwwqvpBBR:bh2ku90) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator.go#L385)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Discussed in person. We're going to want to also consider this an observed read (an `observedScan` but maybe with a new `keysOnly` flag?). That will allow us to assert that the DelRange decided to delete the exact keys we expected it to.
</blockquote></details>

I actually implemented this by adding bounds to the write itself, rather than another new operation - hopefully that makes sense.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/db.go, line 556 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi2zgCN16ig3BDR34vH:-Mi8TQWY-PBmWZh-Z4QZ:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319421d43e6dc0659f89f5ed7b6bfe81f6d4571/pkg/kv/db.go#L556)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind spelling out what it will contain if `returnKeys` is false?
</blockquote></details>

Done!
___
*[pkg/kv/db_test.go, line 456 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi2zw731xcS6NjgURYN:-Mi8TTvB0RlckcaYNe8p:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6319421d43e6dc0659f89f5ed7b6bfe81f6d4571/pkg/kv/db_test.go#L456)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we not have a `TestDB_DelRange`? If not, I think it would be valuable to write one, modeled off `TestDB_Del`. You can then add two subtest variants using `testutils.RunTrueAndFalse`, one that passes `returnKeys` as true and one that passes `returnKeys` as false.
</blockquote></details>

Done!
___
*[pkg/kv/txn.go, line 620 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-Mb02ieJz3BtrD2Z:-Mi8WIT53nYZRdTfUtvt:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdaa69677a6a358e8d26d89d4eb93c3ef46f8f9/pkg/kv/txn.go#L620)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same point about detailing what the return value will contain is returnKeys is false.
</blockquote></details>

Done!
___
*[pkg/kv/kvclient/kvcoord/txn_correctness_test.go, line 168 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi3-c-PAdEfoaVJjIDm:-Mi8WsG2Ekkr0J62Hncp:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdaa69677a6a358e8d26d89d4eb93c3ef46f8f9/pkg/kv/kvclient/kvcoord/txn_correctness_test.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`false /* returnKeys */`
</blockquote></details>

Done!

**Review by nvb — COMMENTED** [review]
This is getting close! The primary remaining discussion is about how we model a `DeleteRange` operation in terms of its set of composite `observedOp`s. It seems like there are a few directions we could go there.

> Reviewed 4 of 21 files at r16, 6 of 6 files at r17, 11 of 11 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-:-MiCl7kxCqbTjdtNP4Ie:b-uypixb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks)

___
*[pkg/kv/kvnemesis/applier.go, line 228 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi31_5x89kd-w8vBZW2:-MiCh5FNDbXfgV1-TlSx:b2py749) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/applier.go#L228)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

It seems a bit duplicative in the Result protobuf to have `repeated bytes keys` and `repeated KeyValue values`, but if you think it's helpful in this case?
</blockquote></details>

I don't feel too strongly, but the empty `Value` in each `KeyValue` is a bit ugly. It seems like we're being quite explicit about the different result types (see `ResultType_Value` vs. `ResultType_Values`), so `ResultType_Keys` feels like a natural extension of that. And I don't think it will be very invasive. But I'll defer to you.
___
*[pkg/kv/kvnemesis/applier_test.go, line 67 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MiCiHbPDdDeWu4f_XKw:-MiCiHbPDdDeWu4f_XKx:b3lkjgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1305b6b7057f148fda3b2504ff229a424ee9d2f/pkg/kv/kvnemesis/applier_test.go#L67)):*
> ```Go
> 	checkPanics := func(t *testing.T, s Step, expectedPanic string) {
> 		t.Helper()
> 		require.EqualError(t, a.Apply(ctx, &s), fmt.Sprintf("panic applying step %s: %v", s, expectedPanic))
> ```

How does this recover from the panic? I thought we would need to use something like `require.Panics` for something like this. I must be missing something.
___
*[pkg/kv/kvnemesis/generator.go, line 229 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MiCj43Z-DFBTG4FFMHi:-MiCj43Z-DFBTG4FFMHj:b-8zb2k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1305b6b7057f148fda3b2504ff229a424ee9d2f/pkg/kv/kvnemesis/generator.go#L229)):*
> ```Go
> func NewDefaultConfig() GeneratorConfig {
> 	config := newAllOperationsConfig()
> 	// TODO(sarkesian): Enable non-transactional DelRange once supported
> ```

Do you mind opening a github issue for this and linking it here?

Also, minor nit, but missing punctuation.
___
*[pkg/kv/kvnemesis/generator.go, line 472 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MiCjFxL3zoDwwYsiD3G:-MiCjFxL3zoDwwYsiD3H:b4epg6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1305b6b7057f148fda3b2504ff229a424ee9d2f/pkg/kv/kvnemesis/generator.go#L472)):*
> ```Go
> }
> 
> func randSpan(rng *rand.Rand) (string, string) {
> ```

nit: move this right below `randMapKey`.
___
*[pkg/kv/kvnemesis/validator.go, line 385 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-Mi32Uu05Ie49MeaLn9V:-MiCjZl50OWCiFgfkUKu:bp91mrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/246570851a1bb7d7c66cba1f56d34439ad4beff6/pkg/kv/kvnemesis/validator.go#L385)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I actually implemented this by adding bounds to the write itself, rather than another new operation - hopefully that makes sense.
</blockquote></details>

Is this asserting everything that we want it to? Right now, we're asserting that none of the keys returned are outside of the del range span, but we're not actually asserting that the del range saw and deleted all of the keys that we would expect it to have seen. For instance, I don't think we will catch a del range over `[a-c)` that deletes and returns "a" but not "b".

Do you mind explaining why you chose to model this by expanding the role of the `observedWrite` `observedOp`?

It seems to me that it would be cleaner to model this as a composition between a single `observedScan` (with a new `keysOnly` option) and a set of `observedWrite`s, but I may be missing a complication that precludes this.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/kv/kvnemesis/applier_test.go, line 67 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MiCiHbPDdDeWu4f_XKw:-MiRkeKcB5hC_gIPe-Sq:bcthnve) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1305b6b7057f148fda3b2504ff229a424ee9d2f/pkg/kv/kvnemesis/applier_test.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this recover from the panic? I thought we would need to use something like `require.Panics` for something like this. I must be missing something.
</blockquote></details>

There's actually a `recover` in the `Apply()` (which I didn't put this there).  So I just figured I could use that and match on the error message.
___
*[pkg/kv/kvnemesis/generator.go, line 229 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MiCj43Z-DFBTG4FFMHi:-MiRkx300RcJORY6Sw5i:b2nhktc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1305b6b7057f148fda3b2504ff229a424ee9d2f/pkg/kv/kvnemesis/generator.go#L229)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind opening a github issue for this and linking it here?

Also, minor nit, but missing punctuation.
</blockquote></details>

OK!

**Review by nvb — APPROVED** [review]
:lgtm: this came out very well!

> Reviewed 3 of 21 files at r19, 1 of 18 files at r22, 6 of 6 files at r23, 9 of 11 files at r24, 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-:-MlOCJ9W9HxhqH2QnZe7:b59b442)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks)

___
*[pkg/kv/kvnemesis/operations.go, line 249 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MlOArve8xbpMdUTYwBH:-MlOArve8xbpMdUTYwBI:b-jz3pdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa3a5e67714f6d5cbd83633d1540b9a3884a4ff8/pkg/kv/kvnemesis/operations.go#L249)):*
> ```Go
> 		fmt.Fprintf(w, ` // (nil, %s)`, err.Error())
> 	case ResultType_Keys:
> 		var keysW strings.Builder
> ```

The `keysW` naming here is intentional, right? Just checking.

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68003)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvnemesis/operations.go, line 249 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/68003#-MlOArve8xbpMdUTYwBH:-MlRE1oG2XwEySMmuCfk:b7i11q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa3a5e67714f6d5cbd83633d1540b9a3884a4ff8/pkg/kv/kvnemesis/operations.go#L249)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The `keysW` naming here is intentional, right? Just checking.
</blockquote></details>

yes - if writer is `w`, I figured it would follow for the writer for the keys to be `keysW`

**Pull request merged**
