### PR TITLE
distsql: add SortAll and SortLimit benchmarks to Sorter

### PR DESCRIPTION
**Pull request by asubiotto**
I think it's a good idea to start tracking the running times of processor implementations so here are some initial benchmarks for the Sorter (only SortAll and Limit for now) that show what this would look like. All processors should have these in the long term.

The other commit introduces a `RowReceiver/RowSource` that is useful for benchmarks because once all its rows are consumed, it starts again from the beginning. It also acts as a sink that throws away any input.

```
$ make bench PKG=./pkg/sql/distsqlrun BENCHES=BenchmarkSort
BenchmarkSortAll/InputSize0-8         	  300000	      4070 ns/op
BenchmarkSortAll/InputSize1-8         	  300000	      5426 ns/op
BenchmarkSortAll/InputSize2-8         	  200000	      5902 ns/op
BenchmarkSortAll/InputSize4-8         	  200000	      6837 ns/op
BenchmarkSortAll/InputSize8-8         	  200000	      8087 ns/op
BenchmarkSortAll/InputSize16-8        	  100000	     12839 ns/op
BenchmarkSortAll/InputSize32-8        	  100000	     22252 ns/op
BenchmarkSortAll/InputSize64-8        	   30000	     43094 ns/op
BenchmarkSortAll/InputSize128-8       	   20000	     88813 ns/op
BenchmarkSortLimit/Limit0-8           	   20000	     87563 ns/op
BenchmarkSortLimit/Limit1-8           	  100000	     12964 ns/op
BenchmarkSortLimit/Limit2-8           	  100000	     13390 ns/op
BenchmarkSortLimit/Limit4-8           	  100000	     15098 ns/op
BenchmarkSortLimit/Limit8-8           	  100000	     19218 ns/op
BenchmarkSortLimit/Limit16-8          	   50000	     26267 ns/op
BenchmarkSortLimit/Limit32-8          	   30000	     43182 ns/op
BenchmarkSortLimit/Limit64-8          	   20000	     63152 ns/op
BenchmarkSortLimit/Limit128-8         	   20000	     70387 ns/op
```

Note some potential weirdness that this has uncovered: sorting a 128-row input with no limit takes `17000 ns` longer than sorting a 128-row input with a limit of 128. I haven't found anything at first glance (nothing should be different in the implementations since we never construct a max-heap in the latter case)

@cuongdo

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for doing this!

Note that for 64, the limit one is 20us slower so this might just be variation?

Instead of running the entire sort `b.N` times, why not have an input of size `b.N`? We could have a source that stores some rows and emits them over and over. Not sure which is better to use for all processors. I do like that we have an idea of how much just setting things up (0 input rows) takes though.

Input sizes should have a wider range, e.g. 0, 4, 16, 256, 4096.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/testutils.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-KmCI84jcEsz0WpOak6p:-KmCI84jcEsz0WpOak6q:b-n9djhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/15529327e1bfabaa12ae40a1f3f301fa17cc59e2/pkg/sql/distsqlrun/testutils.go#L21)):*
> ```Go
> import "github.com/cockroachdb/cockroach/pkg/sql/sqlbase"
> 
> // RepeatableSink is both a RowReceiver and a RowSource used in benchmarks
> ```

Conflating the two is not helpful in this case. A separate "black hole" `RowReceiver` that just ignores rows would be clearer.

---

*[pkg/sql/distsqlrun/testutils.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-KmCIU4O1sEaN12_J7vj:-KmCIU4O1sEaN12_J7vk:b-sjtrdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/15529327e1bfabaa12ae40a1f3f301fa17cc59e2/pkg/sql/distsqlrun/testutils.go#L58)):*
> ```Go
> 	if r.nextRowIdx >= len(r.rows) {
> 		r.nextRowIdx = 0
> 		return nil, ProducerMetadata{}
> ```

From the perspective of the RowSource interface, it is surprising that if `Next` returns nil and we call `Next` again it doesn't return nil. I don't think calling it again is disallowed. I would just add a separate `Reset()` call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-:-KmCHZbP-A0-nkxmZHdL:bxsm65f)*

**Comment by petermattis** [comment]
When running benchmarks, you want to run them multiple times using the `-count` flag. For example, `-count 10` or `-count 20`. Then pass the result through [`benchstat`](https://godoc.org/golang.org/x/perf/cmd/benchstat) which will toss out outliers.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-:-KmCLMf6d_1YbelHMO_g:bjvpojz)*

**Comment by asubiotto** [comment]
I'm not quite sure what you mean by having an input size of `b.N`. If I understand correctly, the sort time of an input size of `b.N` will be divided by `b.N` which won't be representative of time spent sorting the input. I updated the PR to reflect your other comments.
Here are the results from running the benchmarks with `-count 20` (thanks peter). The weirdness is still there.
```
$ benchstat bsort
name                                  time/op
SortAll/InputSize0-8                  2.92µs ± 6%
SortAll/InputSize4-8                  5.17µs ± 2%
SortAll/InputSize16-8                 11.0µs ± 4%
SortAll/InputSize256-8                 179µs ± 4%
SortAll/InputSize4096-8               3.51ms ± 2%
SortAll/InputSize65536-8              70.4ms ± 8%
SortLimit/InputSize65536Limit0-8      70.0ms ± 8%
SortLimit/InputSize65536Limit4-8      2.90ms ± 8%
SortLimit/InputSize65536Limit16-8     2.91ms ± 7%
SortLimit/InputSize65536Limit256-8    4.02ms ± 6%
SortLimit/InputSize65536Limit4096-8   18.5ms ± 4%
SortLimit/InputSize65536Limit65536-8  61.5ms ± 4%
```

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/testutils.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-KmCI84jcEsz0WpOak6p:-Kn3kr00CWr5E3mIUL2H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15529327e1bfabaa12ae40a1f3f301fa17cc59e2/pkg/sql/distsqlrun/testutils.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Conflating the two is not helpful in this case. A separate "black hole" `RowReceiver` that just ignores rows would be clearer.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/testutils.go, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-KmCIU4O1sEaN12_J7vj:-Kn3kwtGqS7ODp4pIKoT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15529327e1bfabaa12ae40a1f3f301fa17cc59e2/pkg/sql/distsqlrun/testutils.go#L58)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

From the perspective of the RowSource interface, it is surprising that if `Next` returns nil and we call `Next` again it doesn't return nil. I don't think calling it again is disallowed. I would just add a separate `Reset()` call.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-:-Kn3tVAEuqow-7r3vk37:b-9jnrua)*

**Comment by RaduBerinde** [comment]
Well we would see the time taken per input row. But this is fine as well. Note that Limit0 is probably unlimited based on the times, probably want limit 1 for the smallest case.

**Comment by asubiotto** [comment]
Ah, got it. You're right, updated the smallest case.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16421#-:-Kn4xnkAT9WEor1xRlyM:bnfp4nl)*

**Pull request merged**
