### PR TITLE
sql: multi node parallel_tests

### LINKED ISSUE #7942: sql: extend parallel_test to use multiple nodes
The parallel test can issue queries in parallel from multiple clients, but it currently sets up a single node. We should extend it to be able to create a test cluster with multiple nodes, and have each node run a set of txns.

Ideally the test should reproduce #7899.

### PR DESCRIPTION
**Pull request by RaduBerinde**
Switching test spec to yaml, adding support for multinode tests. I was hoping the new test would tickle #7899 but it is passing. I can't make the split size smaller, the set up code errors out because it finds more ranges than it expects.

Fixes #7942.

@tschottdorf @knz

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7979)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r1, 8 of 8 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parallel_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHxjlm3WGNw6icR6oA:-KNHxjlm3WGNw6icR6oB:1484219227) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L174)):*
> ```Go
> 		cfg.RangeMaxBytes = int64(spec.RangeSplitSize)
> 		cfg.RangeMinBytes = cfg.RangeMaxBytes / 2
> 		defer config.TestingSetDefaultZoneConfig(cfg)()
> ```

Can this be done without the global hacks? For example, by just changing the zone config programmatically.

---

*[sql/parallel_test.go, line 203 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHy3vh7iD-Adud6ZiY:-KNHy3vh7iD-Adud6ZiZ:-634703765) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L203)):*
> ```Go
> 
> 	if spec.ClusterSize >= 3 {
> 		if err := t.cluster.WaitForFullReplication(); err != nil {
> ```

Why? Not waiting could expose more bugs (besides, I think this line alone causes a ~3s test runtime currently), though we need to make sure it isn't all single-node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by tschottdorf** [comment]
Basically LGTM mod comments, but let @knz take a look.

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parallel_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHxjlm3WGNw6icR6oA:-KNIKnkVxKN9wwOAePoZ:-663158293) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L174)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Can this be done without the global hacks? For example, by just changing the zone config programmatically.
</details>
No idea, I copied this from another test.. Do you have any pointers as to how to change the zone config for a server? Would it need to be plumbed through TestServerArgs?

---

*[sql/parallel_test.go, line 203 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHy3vh7iD-Adud6ZiY:-KNIL6B_d2V7LXT4_298:-1718665800) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L203)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Why? Not waiting could expose more bugs (besides, I think this line alone causes a ~3s test runtime currently), though we need to make sure it isn't all single-node.
</details>
What are you suggesting? (with respect to the "we need to make sure it isn't all single node" part)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parallel_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHxjlm3WGNw6icR6oA:-KNIhN3YDAJqImACebxD:-527139651) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L174)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> No idea, I copied this from another test.. Do you have any pointers as to how to change the zone config for a server? Would it need to be plumbed through TestServerArgs?
</details>
Take a look at `runSetZone` in `cli/zone.go` - I believe it's just a SQL query:
```
			makeQuery(`UPDATE system.zones SET config = $2 WHERE id = $1`, id, buf), cliCtx.prettyFmt)
	} else {
```

---

*[sql/parallel_test.go, line 203 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHy3vh7iD-Adud6ZiY:-KNIgYrPv4wtmrPh-REg:1095044885) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What are you suggesting? (with respect to the "we need to make sure it isn't all single node" part)
</details>
Maybe start running the test right away, but keep it going at least until `WaitForFullReplication` has returned? That might cause a bit of trouble since in tests where you split like crazy, perhaps the replication doesn't get a foot in the door, but then it's good to find out about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/partestdata/subquery_retry_multinode/txn, line 7 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNIi3oGnOat9bUC57Pb:-KNIi3oGnOat9bUC57Pc:-1528232478) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4710a7b4ab6db2f610a356099988cc81770f01/sql/partestdata/subquery_retry_multinode/txn#L7)):*
> ```
> repeat 25
> statement ok
> INSERT INTO T VALUES ((SELECT MAX(k+1) FROM T), 'This is filler text to make the rows use more space and cause range splits quicker. One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What''s happened to me?" he thought. It wasn''t a dream.')
> ```

I dig it, even though it made me go to the SQL shell and convinced myself that `repeat('x', 100)` was a thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parallel_test.go, line 203 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHy3vh7iD-Adud6ZiY:-KNItKVEe33flA-DVyiy:-1579775173) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L203)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Maybe start running the test right away, but keep it going at least until `WaitForFullReplication` has returned? That might cause a bit of trouble since in tests where you split like crazy, perhaps the replication doesn't get a foot in the door, but then it's good to find out about that.
</details>
Hm.. The workload is "fixed" in that it's exactly what is specified in the logic files in the test dir..

---

*[sql/partestdata/subquery_retry_multinode/txn, line 7 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNIi3oGnOat9bUC57Pb:-KNItT1AnmgDrM8nSuad:436626296) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4710a7b4ab6db2f610a356099988cc81770f01/sql/partestdata/subquery_retry_multinode/txn#L7)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I dig it, even though it made me go to the SQL shell and convinced myself that `repeat('x', 100)` was a thing.
</details>
Hah, I didn't know of it, I should use that instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parallel_test.go, line 174 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHxjlm3WGNw6icR6oA:-KNIuUReWNjioU-maWc3:-1248872257) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L174)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Take a look at `runSetZone` in `cli/zone.go` - I believe it's just a SQL query:
> ```
> 			makeQuery(`UPDATE system.zones SET config = $2 WHERE id = $1`, id, buf), cliCtx.prettyFmt)
> 	} else {
> ```
</details>
Oo, nice, thank you!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parallel_test.go, line 203 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979#-KNHy3vh7iD-Adud6ZiY:-KNK4eVcYXNt0HM7ek82:924255872) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d35f3991b648a0530007f64cd066ac36a19e62b/sql/parallel_test.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Hm.. The workload is "fixed" in that it's exactly what is specified in the logic files in the test dir..
</details>
Hmm, yeah. Agree that it doesn't map nicely to the test format. I think they still cover more when not waiting for replication ahead of time, but it's your call - don't want to get too sidetracked here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7979)*

**Comment by RaduBerinde** [comment]
Unfortunately the new test, despite usually taking ~12s sometimes times out. I will submit the change with the test skipped and do some more investigation. I will file an issue after doing some due diligence.

**Pull request merged**
