### PR TITLE
Add status endpoint to report problematic range IDs.

### PR DESCRIPTION
**Pull request by mberhault**
Finding which range is causing a problem can be annoying, we have to
hope it's holding up requests and shows up in /debug/requests.
see #10736

This makes it a bit easier to find such ranges, albeit for a single node
at a time (a wrapper to loop over all nodes might be useful).

It would also be nice to just produce links from this to the
raft?range_ids=<range_id> page.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13626)

### CODE REVIEW

**Comment by mberhault** [comment]
Still need to figure out how to inject those failures in tests.

**Comment by petermattis** [comment]
The `Status` service seems a bit ad-hoc to me. Perhaps we should take the opportunity to clean up the API, at least in regard to ranges. For example, I think there should be a `ListRanges` that can return the range IDs for the local node and @bramgruneir `Range` operation can return the detail for a specific range. 

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-Kd8n64mjlr_XrWhsAxy:-Kd8n64mjlr_XrWhsAxz:bms7x6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/server/serverpb/status.proto#L230)):*
> ```protobuf
>   string node_id = 1;
>   bool want_unavailable = 2;
>   bool want_leader_not_lease_holder = 3;
> ```

I'm not sure leader-not-leaseholder is useful anymore. But under-replicated is. I'm wondering if this interface should instead by `ListRangesRequest` and for it to take an option filter on what ranges to return:

```
enum Filter {
  ALL = 1,
  UNDER_REPLICATED = 2,
  UNAVAILABLE = 3,
}
```

---

*[pkg/storage/store.go, line 4068 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-Kd8oj8DBFPHWaYB5tXC:-Kd8oj8DBFPHWaYB5tXD:b-84znei) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/storage/store.go#L4068)):*
> ```Go
> 
> 	unavailable := []roachpb.RangeID{}
> 	notLeaseHolder := []roachpb.RangeID{}
> ```

Idiomatic way to declare empty slices is: `var unavailable []roachpb.RangeID`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-:-Kd8p4XP8UV3SeEy37HZ:bjj8eje)*

**Comment by bdarnell** [comment]
I don't think we should block a useful inspection interface on a cleanup of the existing Status service. However, I do think we should converge on one RangeDebugInfo output format instead of adding ad-hoc ones for each new request. It's cheap enough to include the "problem" status of a range anytime we query anything about it. Then we can have multiple ways of querying ranges (all ranges, just problems, specific range IDs) that can return the same type of results to the UI.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-Kd8n64mjlr_XrWhsAxy:-KdDQxHOkxT3oxR8NERX:b-rxesmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/server/serverpb/status.proto#L230)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure leader-not-leaseholder is useful anymore. But under-replicated is. I'm wondering if this interface should instead by `ListRangesRequest` and for it to take an option filter on what ranges to return:

```
enum Filter {
  ALL = 1,
  UNDER_REPLICATED = 2,
  UNAVAILABLE = 3,
}
```
</blockquote></details>

Do we even need this in the request? Maybe this request should return all abnormal ranges and then the receiver filters them later. 

Why is leader-not-leaseholder no longer useful? It hasn't been happening as much recently, but I think it's still conceptually valid.

Another category of trouble we should include here is ranges whose raft state is "candidate" (since partitioned nodes tend to get stuck in this state for a long time).

---

*[pkg/server/serverpb/status.proto, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-KdDRhUlghQC2LLIVzod:-KdDRhUlghQC2LLIVzoe:b-wrn0gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/server/serverpb/status.proto#L234)):*
> ```protobuf
> 
> message ProblemRangesResponse {
>   repeated int64 unavailable_range_ids = 1 [(gogoproto.customname) = "UnavailableRangeIDs",
> ```

I'd structure this as

```
message ProblemRange {
    int64 range_id = 1;
    bool unvavailable = 2;
    bool leader_not_lease_holder = 3;
}
repeated ProblemRange problem_ranges = 1
```

It seems more useful to have all the information about a range together. 

---

*[pkg/storage/store.go, line 4048 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-KdDSsAMrwslq16eiCef:-KdDSsANyMlHQ0I2m9lq:b2wjqo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/storage/store.go#L4048)):*
> ```Go
> 
> // ListProblemRanges iterates over all replicas and returns the range IDs of ranges that
> // have requested problems.
> ```

s/have requested/have the requested/ (or remove the options and just return everything)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-:-KdDUAMyL2DhHEcnGl1m:b-3omlwc)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-Kd8n64mjlr_XrWhsAxy:-KdDkGY6hZJeWeuJJOp-:b-9m8hty) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/server/serverpb/status.proto#L230)):*
> Why is leader-not-leaseholder no longer useful?

Because it isn't happening any more. I suppose it isn't harmful to leave in, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626)*

**Comment by mberhault** [comment]
I think there's probably a right middle-ground here. list-problems is incredibly specific, some type of filter on a list-ranges would be more easily expandable. I'll poke at this a bit, it shouldn't be too tricky. I'll be intentionally ignoring the problem of paging results (we'd have to sort first).

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/status.proto, line 230 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-Kd8n64mjlr_XrWhsAxy:-KdDmV-oI-e0VQvrjN2F:b-um0m5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/461d462e3921f3f5c3ff0e404341237753cec50c/pkg/server/serverpb/status.proto#L230)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> Why is leader-not-leaseholder no longer useful?

Because it isn't happening any more. I suppose it isn't harmful to leave in, though.
</blockquote></details>

actually, it's still happening, the alerts for those are in #monitoring-test. indigo and blue (both upgraded with Ben's fix) are still paging, and omega just started.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13626#-:-KdDmLrjJ6zvHFMBWZWz:b-gnp6xz)*

**Comment by BramGruneir** [comment]
Replaced by #15291.

**Pull request closed without merging**
