### PR TITLE
storage: fix nil pointer panic in tryGetOrCreateReplica

### LINKED ISSUE #44332: roachtest: tpccbench/nodes=9/cpu=4/chaos/partition failed
[(roachtest).tpccbench/nodes=9/cpu=4/chaos/partition failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1708438&tab=buildLog) on [master@3c408a47707a15d4b5c92031c4eafcfa643d307c](https://github.com/cockroachdb/cockroach/commits/3c408a47707a15d4b5c92031c4eafcfa643d307c):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200124-1708438/tpccbench/nodes=9/cpu=4/chaos/partition/run_1
	cluster.go:2315,tpcc.go:720,tpcc.go:561,test_runner.go:719: error with attached stack trace:
		    main.(*monitor).WaitE
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2306
		    main.(*monitor).Wait
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2314
		    main.runTPCCBench
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:720
		    main.registerTPCCBenchSpec.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:561
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:719
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - monitor failure:
		  - unexpected node event: 9: dead

```

<details><summary>More</summary><p>

Artifacts: [/tpccbench/nodes=9/cpu=4/chaos/partition](https://teamcity.cockroachdb.com/viewLog.html?buildId=1708438&tab=artifacts#/tpccbench/nodes=9/cpu=4/chaos/partition)
Related:
- #44293 roachtest: tpccbench/nodes=9/cpu=4/chaos/partition failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-2.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-2.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44287 roachtest: tpccbench/nodes=9/cpu=4/chaos/partition failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44259 roachtest: tpccbench/nodes=9/cpu=4/chaos/partition failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202001221958_v2.1.11](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202001221958_v2.1.11) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpccbench%2Fnodes%3D9%2Fcpu%3D4%2Fchaos%2Fpartition.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by ajwerner**
This commit checks the Replica's destroy status in tryGetOrCreateReplica
prior to checking if the fromReplica is too old. The hazard occurs when a
freshly previously created Replica was determined to be older than a tombstone
which was created concurrently (see the second tombstone check in the same
function). In that case it's possible for a destroyed replica to exist in the
store's map with a nil descriptor.

The added test reproduced the panic under stress within 5s.

This PR should be backported to 19.2.

Fixes #44332.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Oof, my brain is melting a bit. Is this spelling out the problematic history:

- g1 creates a replica, calls `addReplicaToRangeMapLocked`, pauses after releasing mutex (replica has nil desc at this point)
- g2 with higher replicaID comes in, calls into `s.removeReplicaRaftMuLocked`, blocks after setting destroy status (but before removing from store map)
- g3 with higher replicaID comes in, retrieves the replica (which still has a nil desc), explodes in `fromReplicaIsTooOld`

LGTM, though if there is any way that you can make what  I wrote above more legible and persist it (perhaps near the .Removed() check) I would appreciate that.
And as always thanks for tracking this nasty one down.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44513#-:-Lzq-Rj26AXnckNFM9rk:b-jmlk6p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
> Oof, my brain is melting a bit. Is this spelling out the problematic history:
> 
>     * g1 creates a replica, calls `addReplicaToRangeMapLocked`, pauses after releasing mutex (replica has nil desc at this point)
> 
>     * g2 with higher replicaID comes in, calls into `s.removeReplicaRaftMuLocked`, blocks after setting destroy status (but before removing from store map)
> 
>     * g3 with higher replicaID comes in, retrieves the replica (which still has a nil desc), explodes in `fromReplicaIsTooOld`
> 
> 
> LGTM, though if there is any way that you can make what I wrote above more legible and persist it (perhaps near the .Removed() check) I would appreciate that.
> And as always thanks for tracking this nasty one down.

Yes, that is a hazardous trace. This ended up finding another NPE. The problem is in the case where the store scanner is examing the range for gossip and checking if it's initialized. I think this change of checking the destroy status up front is a good one but given this second crash, I decided to eliminate the possibility of a replica having a nil descriptor given it's so rare already. PTAL.

**Review by tbg — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44513#-:-Lzr18iGEwA4D5_4TK3L:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=tbg

**Pull request merged**
