### PR TITLE
security: add support for root owned certificates

### PR DESCRIPTION
**Pull request by catj-cockroach**
The certificate loader previously verified that certificate private
keys were only accessible by the owning user. This is adequate for
instances where CockroachDB is run as root, or run in a system where
the certificate private key is manually updated.

Where this breaks down is in Kubernetes, as volume mounts (such as
Secrets) are mounted as owned by the root user. To allow non-root
processes to interact with volumes, they can be given a owning group ID
and have custom permissions set. This means in Kubernetes, when running
CockroachDB as a regular user, we should allow root owned keys,
provided the group is correct and permissions are still restricted.

This change adds an exception to the permission checks that allow the
certificate loader to read a key that is owned by root but has a group
ID that matches the process's group ID (the group ID of the user
running the process) and has updated permissions to match.

Release note (security update): The certificate loader now allows the
loading of root owned private keys, provided the owning group matches
the group of the (non-root) user running CockroachDB.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @catj-cockroach)

___
*[pkg/security/certificate_loader.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfhw8047_lAp3lmHcVM:-Mfhw8047_lAp3lmHcVN:bif6tt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e76979940f12d3c97cfeed35cb203570fe2f1770/pkg/security/certificate_loader.go#L397)):*
> ```Go
> 
> 	if !cl.skipPermissionChecks {
> 		if ok, err := checkFilePermissions(fullKeyPath, info); err != nil || !ok {
> ```

that doesn't sound right - I think there should not be an `ok` return, and the function should clarify a failure using an `error` object.

(In fact looking at the code for `checkFilePermissions` I don't really understand the function of the boolean. What information does it convey other than `err == nil` already?

**Comment by catj-cockroach** [comment]
___
*[pkg/security/certificate_loader.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfhw8047_lAp3lmHcVM:-MfhxW4--8ELDUDzBWOU:b-kpzfdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e76979940f12d3c97cfeed35cb203570fe2f1770/pkg/security/certificate_loader.go#L397)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that doesn't sound right - I think there should not be an `ok` return, and the function should clarify a failure using an `error` object.

(In fact looking at the code for `checkFilePermissions` I don't really understand the function of the boolean. What information does it convey other than `err == nil` already?
</blockquote></details>

The boolean is completely unnecessary! I wasn't certain how comfortable we are using errors for flow control, I'll refactor!

**Review by catj-cockroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

___
*[pkg/security/certificate_loader.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfhw8047_lAp3lmHcVM:-Mfhzv-k6gx3HYplSWCq:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/e76979940f12d3c97cfeed35cb203570fe2f1770/pkg/security/certificate_loader.go#L397)):*
<details><summary><i>Previously, catj-cockroach wrote…</i></summary><blockquote>

The boolean is completely unnecessary! I wasn't certain how comfortable we are using errors for flow control, I'll refactor!
</blockquote></details>

Done!

**Review by knz — COMMENTED** [review]
The change looks good, but you still need to add a unit test. 
See `certificate_loader_test.go` for some examples.

Given that you have a special case for UID 0, and you cannot force UID 0 in  a test, you'll probably need to create a test interface in the new permission checking code that you've created, so that the test can control the special UID value to compare.  Do you have some ideas about how to achieve that?

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-:-Mfi0wnp4-QqGYzxS-4p:b259ltu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @catj-cockroach)

___
*[pkg/security/certificate_loader.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfhw8047_lAp3lmHcVM:-Mfi0XlN1zq2ooldXBsy:b-xjw2ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/e76979940f12d3c97cfeed35cb203570fe2f1770/pkg/security/certificate_loader.go#L397)):*
<details><summary><i>Previously, catj-cockroach wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Sometimes it is in fact necessary to separate them. For example when the boolean "false" case is not an error and there are really 3 different control paths out.
In this case though, not necessary.

**Review by catj-cockroach — COMMENTED** [review]
@knz I was hoping you'd let me skip unit tests because this is so operating system dependent :sweat_smile: I've pushed up a change that adds unit tests (it manually creates the Stat structures that describe the permissions and UID/GID) but I think I have a better way of implementing this that I'm going to take a stab at today!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-:-MfmcRgPBbfSBrUN4jvX:b-23d7dl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @catj-cockroach, and @knz)

**Review by knz — APPROVED** [review]
:lgtm: with a dependency nit

> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-:-Mfs8lmS0rY28pUq6uFH:b60jhwu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @catj-cockroach)

___
*[pkg/util/sysutil/acl_unix_test.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfs8e_OENybFDfUgOUn:-Mfs8e_OENybFDfUgOUo:b4wpf6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0df6ee98d3218d768e5fd2eb6e4d70b6b32882/pkg/util/sysutil/acl_unix_test.go#L27)):*
> ```Go
> 
> func TestGetFileACLInfo(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> ```

the sysutil package does not use leaktest, so you could remove this from the tests in the directory, which will drop a dependency and avoid movement on the BUILD.bzl.

**Comment by catj-cockroach** [comment]
___
*[pkg/util/sysutil/acl_unix_test.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfs8e_OENybFDfUgOUn:-MfsAdEn3m6TK-28-3Y3:b-4kn9yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0df6ee98d3218d768e5fd2eb6e4d70b6b32882/pkg/util/sysutil/acl_unix_test.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

the sysutil package does not use leaktest, so you could remove this from the tests in the directory, which will drop a dependency and avoid movement on the BUILD.bzl.
</blockquote></details>

Oh! I will fix that!

**Review by catj-cockroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68182)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aaron-crl and @knz)

___
*[pkg/util/sysutil/acl_unix_test.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68182#-Mfs8e_OENybFDfUgOUn:-MgCE7n767avPR_o1D-w:b-898mwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c0df6ee98d3218d768e5fd2eb6e4d70b6b32882/pkg/util/sysutil/acl_unix_test.go#L27)):*
<details><summary><i>Previously, catj-cockroach (Cat J) wrote…</i></summary><blockquote>

Oh! I will fix that!
</blockquote></details>

Done! Is there anything else I need to do before calling out to bors?

**Comment by knz** [comment]
I already approved this

**Pull request merged**
