### PR TITLE
opt: Add support for DELETE operator

### PR DESCRIPTION
**Pull request by andy-kimball**
This commit adds support for the DELETE operator to the cost-based
optimizer. The DELETE operator is similar to the UPDATE operator. It
fetches existing values from the deletion table using the clauses
specified in the DELETE statement:

  CREATE TABLE abc (a INT PRIMARY KEY, b INT, c INT)
  DELETE FROM abc WHERE b=10

Then an input expression equivalent to this would be built:

  SELECT a, b, c
  FROM abc
  WHERE b=10

At runtime, the Delete execution operator will iterate over each input
row and use its key to delete each row in turn.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

The (non-interleaved) fast path "just works", right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33524#-:-LV_fVto3C4Il2iQ1JV-:b-n2gx6w)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by justinj — COMMENTED** [review]
:lgtm: too

> Reviewed 11 of 11 files at r1, 16 of 16 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33524#-:-LVd2lck9LoL8bkPOaJd:b4xzfr9)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by rytaft — APPROVED** [review]
:lgtm:

[nit] the commit message and PR description say "similar to, but similar to". I assume you meant "similar to, but different from"...?

> Reviewed 11 of 11 files at r1, 16 of 16 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33524#-:-LVcuKUSCqQKGLFBvnbL:b5v1kbk)* status: :shipit: complete! 3 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
@RaduBerinde, yes, the non-interleaved delete fast path should "just work".

**Pull request merged**
