### PR TITLE
storageccl: test the MVCCStats behavior of the WriteBatch impl

### PR DESCRIPTION
**Pull request by danhhz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13844)

### CODE REVIEW

**Comment by tamird** [comment]
:dog: :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/storageccl/writebatch_test.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-Ke4aJ3WOvADE26jmPNB:-Ke4aJ3WOvADE26jmPNC:bxuvx30) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d76e31a25b3e2174a0d10ceb6e4c8846b1c452/pkg/ccl/storageccl/writebatch_test.go#L90)):*
> ```Go
> 
> 	var batch engine.RocksDBBatchBuilder
> 	key := engine.MVCCKey{Key: []byte("bb"), Timestamp: hlc.Timestamp{WallTime: 1}}
> ```

in light of recent scoping-related mistakes, consider putting this in a scope:
```
{
  key := engine.MVCCKey{Key: []byte("bb"), Timestamp: hlc.Timestamp{WallTime: 1}}
  batch.Put(key, roachpb.MakeValueFromString("1").RawBytes)
}
```


---

*[pkg/ccl/storageccl/writebatch_test.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-Ke4aVtMXoH9k9VxtIVa:-Ke4aVtMXoH9k9VxtIVb:bdxmuag) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d76e31a25b3e2174a0d10ceb6e4c8846b1c452/pkg/ccl/storageccl/writebatch_test.go#L103)):*
> ```Go
> 		Stats: &enginepb.MVCCStats{},
> 	}
> 	var resp roachpb.Response
> ```

hm, what is the point of this? seems like you could just pass nil below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-:-Ke4afbgML9Kj_kmq5p8:bvma1yx)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/storageccl/writebatch_test.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-Ke4aJ3WOvADE26jmPNB:-Ke4cX3nuRjl1nYF5Q5q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d76e31a25b3e2174a0d10ceb6e4c8846b1c452/pkg/ccl/storageccl/writebatch_test.go#L90)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

in light of recent scoping-related mistakes, consider putting this in a scope:
```
{
  key := engine.MVCCKey{Key: []byte("bb"), Timestamp: hlc.Timestamp{WallTime: 1}}
  batch.Put(key, roachpb.MakeValueFromString("1").RawBytes)
}
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/writebatch_test.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-Ke4aVtMXoH9k9VxtIVa:-Ke4cO2tW6Twskv-81gH:b-5fsabn) ([raw file](https://github.com/cockroachdb/cockroach/blob/70d76e31a25b3e2174a0d10ceb6e4c8846b1c452/pkg/ccl/storageccl/writebatch_test.go#L103)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

hm, what is the point of this? seems like you could just pass nil below.
</blockquote></details>

ah, you are correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844)*
<!-- Sent from Reviewable.io -->

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-:-Ke4mKONlqvT1FXYFYUN:bnfp4nl)*

**Comment by danhhz** [comment]
TFTRs!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13844#-:-Ke4o8HdGPyo2iyhmcii:bz5mair)*

**Pull request merged**
