### PR TITLE
opt: check type and composite sensitivity before remapping computed expressions

### LINKED ISSUE #124732: unoptimized-query-oracle: missing intermediate cast in computed column
roachtest.unoptimized-query-oracle/disable-rules=all/rand-tables [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15417862?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/15417862?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/rand-tables) on release-24.1 @ [d194358048c92a697d52fe77f52e01e9e7c670d9](https://github.com/cockroachdb/cockroach/commits/d194358048c92a697d52fe77f52e01e9e7c670d9):

```
(query_comparison_util.go:389).runOneRoundQueryComparison: . 1646 statements run: expected unoptimized and optimized results to be equal
  []string(
- 	{"-"},
+ 	nil,
  )
sql: SELECT
	tab_851."col\\U000EF8951_6" AS col_2807
FROM
	defaultdb.public.table_3 AS tab_850
	JOIN defaultdb.public."tab?le_1" AS tab_851 ON (tab_850."coL3_0") = (tab_851."col\\U000EF8951_6")
GROUP BY
	tab_851."col\\U000EF8951_6"
ORDER BY
	tab_851."col\\U000EF8951_6" ASC NULLS LAST,
	tab_851."col\\U000EF8951_6" NULLS LAST,
	tab_851."col\\U000EF8951_6" NULLS FIRST,
	tab_851."col\\U000EF8951_6" ASC NULLS FIRST,
	tab_851."col\\U000EF8951_6" NULLS LAST,
	tab_851."col\\U000EF8951_6" ASC NULLS LAST,
	tab_851."col\\U000EF8951_6" NULLS LAST
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/rand-tables/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-15417862/unoptimized-query-oracle-disable-rules-all-rand-tables/1716826950289/1716828543393)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #124699 roachtest: unoptimized-query-oracle/disable-rules=all/rand-tables failed [C-test-failure O-roachtest O-robot O-rsg T-sql-queries branch-master release-blocker]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/rand-tables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-39045

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: don't remap non-identical cols when building a lookup join

It is possible in some cases to infer an equality constraint for a
computed column in order to allow a lookup join. This requires remapping
the columns in the computed column expression to columns from the join's
left input. Previously, this logic did not check that the remapped columns
all have identical types. This could result in incorrect results.
This commit fixes the issue by only remapping columns that are identical.

Fixes #124732

Release note (bug fix): Fixed a bug existing since before v23.1 which
could lead to incorrect results in rare cases. The bug requires a join
between two tables, with an equality between columns with equivalent but
not identical types (e.g. OID and REGCLASS). In addition, the join must
lookup into an index that includes a computed column that references one
of the equivalent columns.

#### opt: don't remap composite-sensitive computed cols when building a lookup join

Similar to the prior fix for remapping non-identical columns when
projecting a computed columns expression for a lookup join, this commit
adds a check to ensure that the computed column expression is composite
insensitive. Without this check, differences in a composite-typed column
(e.g. `2.0::DECIMAL` vs `2.0000::DECIMAL`) could cause the lookup join
to produce incorrect results.

Informs #124732

Release note (bug fix): Fixed a bug existing since before v23.1 which
could lead to incorrect results in rare cases. The bug requires a
lookup join into a table with a computed index column, where the
computed column expression is composite sensitive. A composite sensitive
expression can compare differently if supplied non-identical but
equivalent input values (e.g. `2.0::DECIMAL` vs `2.00::DECIMAL`).

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O0QbuwNDtstLagXp21U:b-d5wue7) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
> ```Go
> 		var rightEqIdenticalTypeCols opt.ColSet
> 		for i := range rightEq {
> 			if b.md.ColumnMeta(rightEq[i]).Type.Identical(b.md.ColumnMeta(leftEq[i]).Type) {
> ```

This works, but it seems a little over-restrictive to me. For example, it would be nice to retain the optimization for a case like the following, in which INT2 and INT4 are not identical but no information is lost.

```sql
CREATE TABLE xy (
  x STRING,
  y INT2 NOT NULL,
  PRIMARY KEY (x)
);

CREATE TABLE yz (
  y INT4 NOT NULL,
  z INT8 NOT NULL AS (y + 1) VIRTUAL,
  PRIMARY KEY (z)
);

EXPLAIN (OPT, TYPES) SELECT * FROM xy JOIN yz ON yz.y = xy.y WHERE x = 'foo';
```

Instead of only adding the column if the type is identical, could we check if the type is lossless cast-able to the type of the equality comparison?

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O0Qm_h64uKxShP8516c:b-do70km) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
> Instead of only adding the column if the type is identical, could we check if the type is lossless cast-able to the type of the equality comparison?

Actually, I think this is slightly wrong: I think the condition we're looking for is more like:
* if the type of the equality comparison is identical to the type of the column we'd be replacing

And then we need to add a cast to the type of the equality comparison to the replacement, like @yuzefovich mentioned during the collab session. So the rendered expression for lookup should be `xy.y::INT4::INT8 + 1`.

**Review by mgartner — COMMENTED** [review]
I'm still wrapping my head around this, but it sounds a lot like [composite sensitivity](https://github.com/cockroachdb/cockroach/blob/c137b35c79b8f1917e760cdb3fd74d48d62484e5/pkg/sql/opt/memo/logical_props_builder.go#L2839-L2864).

If we have a scalar expression `f`:

```
f(c1, c2) => c1::STRING = c2::STRING
```

If `f` is composite insensitive then we would expect `f1 = f(0::OID, 0::REGCLASS)` to equal `f2 = f(0::REGCLASS, 0::REGCLASS)` because `0::OID` is logically equivalent to `0::REGCLASS`. But `f1 != f2`, so it is composite sensitive.

However, it's not clear to me that the definition of composite insensitivity should apply when outer columns (`c1` and `c2` in this case) have different types. There's actually an implicit cast happening—even if it's a no-op its still logically occurring. So how does that implicit cast fit into this...?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O0u7op06N1HaNeQb7Jp:b-pft5rz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O0u4Za458cDeO2_8fqW:b4xs1p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
> could we check if the type is lossless cast-able to the type of the equality comparison

That wouldn't prevent the OID/REGCLASS problem this PR is trying to address, would it?
___
*[`pkg/sql/logictest/testdata/logic_test/lookup_join` line 1599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0u18DW9h03y9f4IVCO:-O0u18DW9h03y9f4IVCP:but6tpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/logictest/testdata/logic_test/lookup_join#L1599)):*
> ```
> 
> statement ok
> ALTER TABLE table_3_124732 INJECT STATISTICS e'[{"avg_size": 5, "columns": ["col3_7"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 201038037, "histo_buckets": [{"distinct_range": 0, "num_eq": 700, "num_range": 0, "upper_bound": "\\u0000"}, {"distinct_range": 0, "num_eq": 3066039884274213925, "num_range": 50, "upper_bound": "I6\\u0017="}, {"distinct_range": 40000000000, "num_eq": 2000, "num_range": 40000000000, "upper_bound": "k_Y~y;"}, {"distinct_range": 0, "num_eq": 9000000000, "num_range": 4958652185256911015, "upper_bound": "\\u0008<\\r2]J\\u000e"}, {"distinct_range": 0, "num_eq": 600, "num_range": 100000, "upper_bound": "8R`tYH^"}, {"distinct_range": 1640102296691195600, "num_eq": 80000000000, "num_range": 1640102296691195695, "upper_bound": "\\u000f\\\\[Mm|c\\r"}, {"distinct_range": 242047641220621220, "num_eq": 8503850823594830229, "num_range": 3633976948439898226, "upper_bound": "\\u0018s5iH\'4\\""}, {"distinct_range": 0, "num_eq": 5000000, "num_range": 5380871138879966725, "upper_bound": "Ld\\u0011\\u0006\\u001b\\u000br3"}, {"distinct_range": 6675431471957301000, "num_eq": 300000, "num_range": 6675431471957300813, "upper_bound": "\\u000e4 \\u000b2Yz\\u001ay"}], "histo_col_type": "STRING", "histo_version": 3, "name": "__auto__", "null_count": 0, "row_count": 800000000}]';
> ```

nit: use this reproduction with hints instead of stats injection: https://github.com/cockroachdb/cockroach/issues/124732#issuecomment-2207022348 - query plans will be less likely to change over time with hints.

**Review by DrewKimball — COMMENTED** [review]
I don't think composite-sensitivity is exactly the problem, though it's definitely similar. With composite-sensitivity, you have two equivalent columns, with slightly different values because the equivalence holds even despite those differences (with `1.0 == 1.0000` begin an example).

In the case of this failure, we're replacing a column with another column with a different type from the same type family. In some cases this would be fine, but the computed column expression can have arbitrary logic that's sensitive to the type change - like a STRING cast. So the property is "type-sensitivity", or something

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O0uDiSQ2hur_T6tAcap:b-3kzhxl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O0uFriwE_y-l6HJAYz3:b-kicgvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> could we check if the type is lossless cast-able to the type of the equality comparison

That wouldn't prevent the OID/REGCLASS problem this PR is trying to address, would it?
</blockquote></details>

The issue is, the computed column can be doing arbitrary things with the columns we're remapping. For example, what if it includes the `pg_typeof` builtin function? So we have to make sure the type is identical, and (Marcus just made me realize) we also have to make sure the expression isn't composite-sensitive, either.

**Review by michae2 — APPROVED** [review]
:lgtm: Ok, I'm in favor of this (but maybe wait for @mgartner too).

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O0uegeH-IWOasZbUsbc:b-z4zqzi)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O0uSp4g8-_UdrjyQQmW:bz0gp7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The issue is, the computed column can be doing arbitrary things with the columns we're remapping. For example, what if it includes the `pg_typeof` builtin function? So we have to make sure the type is identical, and (Marcus just made me realize) we also have to make sure the expression isn't composite-sensitive, either.
</blockquote></details>

Could we add a cast to the type of the column we're replacing? (To `OID` in this case.)

e.g. rewrite

```sql
SELECT col1_6 FROM table_3_124732 JOIN table_1_124732 ON col3_0 = col1_6;
```

to

```sql
SELECT col1_6 FROM table_3_124732 JOIN table_1_124732 ON col3_7 = (lower(CAST((col1_6::OID) AS STRING)));
```

This seems like it would work as long as we can prove that `col3_0 = col1_6` is always the same as `col3_0 = col1_6::OID` (though maybe that's not easy to do?).

Oh, wait, I see what you're saying, this will work for `pg_typeof` but as you point out it won't work for a composite-sensitive expression, e.g. it doesn't work for a case like this (ignoring the fact that float::string isn't legal as a virtual computed column expression):

```sql
CREATE TABLE mn (
  m STRING,
  n FLOAT4 NOT NULL,
  PRIMARY KEY (m)
);

CREATE TABLE no (
  n FLOAT8 NOT NULL,
  o STRING NOT NULL AS (n::STRING) VIRTUAL,
  PRIMARY KEY (o)
);

INSERT INTO mn VALUES ('foo', -0);
INSERT INTO no (n) VALUES (+0);

EXPLAIN (OPT, TYPES) SELECT * FROM mn JOIN no ON no.n = mn.n WHERE m = 'foo';
```

This should return one row but if we replace `ON no.n = mn.n` with `ON no.o = mn.n::FLOAT8::STRING` it would return zero rows.

Eh... I'm ok with checking for identical type. The user can always add the cast themselves.

**Review by mgartner — COMMENTED** [review]
Apologies for the hold up! I'm in favor of this too, and we should get this merged. I left a few minor comments to address first.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O5x8q7_95oQ0BkGbmuF:b-ujj69h)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O5x7tmR-wUp3UIk8yJt:-O0u37vz2_ghHVnLJ__j:bgw3aiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L295)):*
> ```Go
> 		// NOTE: we must only consider equivalent columns with identical types,
> 		// since column remapping is otherwise not valid.
> 		var rightEqIdenticalTypeCols opt.ColSet
> ```

nit: we should be able to reuse this set for all iterations, and we can lazily create it if needed.
___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0QbuwNDtstLagXp21T:-O5x7yPjBhZ7UJi3Nfm8:b-oocu2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L297)):*
> Eh... I'm ok with checking for identical type. The user can always add the cast themselves

SGTM too.
___
*[`pkg/sql/logictest/testdata/logic_test/lookup_join` line 1599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0u18DW9h03y9f4IVCO:-O5x831k8Ounhhs5sXvH:b3n05ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/logictest/testdata/logic_test/lookup_join#L1599)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: use this reproduction with hints instead of stats injection: https://github.com/cockroachdb/cockroach/issues/124732#issuecomment-2207022348 - query plans will be less likely to change over time with hints.
</blockquote></details>

friendly reminder on using the simpler reproduction
___
*[`pkg/sql/opt/lookupjoin/testdata/computed` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O5x8ahPDPXjcMVnGA55:-O5x8ahPDPXjcMVnGA56:b-lmgwnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/testdata/computed#L126)):*
> ```
> # Regression test for #124732: Computed columns cannot be remapped unless the
> # column types are identical.
> lookup-constraints left=(a regclass, b int) right=(x oid, v int not null as (x::string) stored) index=(v, x)
> ```

I don't think `v int not null as (x::string) stored` is a valid computed column. Did you mean for `v` to have type `string` instead?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @yuzefovich)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O5x7tmR-wUp3UIk8yJt:-O8Iw1DzBjlCPwNCBgKi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/constraint_builder.go#L295)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: we should be able to reuse this set for all iterations, and we can lazily create it if needed.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/lookup_join` line 1599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O0u18DW9h03y9f4IVCO:-O8IxJPi-ZG_qLIKXcbS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/logictest/testdata/logic_test/lookup_join#L1599)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

friendly reminder on using the simpler reproduction
</blockquote></details>

Done.
___
*[`pkg/sql/opt/lookupjoin/testdata/computed` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O5x8ahPDPXjcMVnGA55:-O8Ixc5064v8y7fKAzJT:b-al6gwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/48f86de56db8eaa945f9a7ae33b7467e77145c9c/pkg/sql/opt/lookupjoin/testdata/computed#L126)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think `v int not null as (x::string) stored` is a valid computed column. Did you mean for `v` to have type `string` instead?
</blockquote></details>

Yes, good catch. Done,

**Review by DrewKimball — COMMENTED** [review]
Sorry for the delay, I think I've addressed everything now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O8J0AeGA8drnYnIkJPv:b-c0zcnh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @yuzefovich)

**Comment by mgartner** [comment]
@michae2  previoulys mentioned the alternative:

> Could we add a cast to the type of the column we're replacing? (To OID in this case.)

@mw5h thought of the same solution when investigating https://github.com/cockroachdb/cockroach/issues/130638#issuecomment-2392147579:

> When synthesizing the equality of computed expressions, add a cast to one side if the columns do not have identical types. Using the example above, instead of incorrectly synthesizing `t.o::STRING = v.r::STRING` from `t.o = v.r`, synthesize `t.o::STRING = t.r::OID::STRING`.

It looks like Michael and Drew discovered [some pitfalls of that approach](https://github.com/cockroachdb/cockroach/pull/126345#pullrequestreview-2157582653).

I think requiring identical types is fine for now, but these breadcrumbs might be helpful if we ever need to loosen that restriction.

**Review by mgartner — APPROVED** [review]
:lgtm: :shipit: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O8J2J6K4VPtoRfNSJEQ:byzm7aw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by mgartner** [comment]
@DrewKimball you previously wrote:

>The issue is, the computed column can be doing arbitrary things with the columns we're remapping. For example, what if it includes the pg_typeof builtin function? So we have to make sure the type is identical, and (Marcus just made me realize) we also have to make sure the expression isn't composite-sensitive, either.

Does this mean we have another bug here because we aren't checking for composite sensitivity? Or are we ok?

**Comment by DrewKimball** [comment]
>Does this mean we have another bug here because we aren't checking for composite sensitivity? Or are we ok?

Yeah that probably is also a bug... I'll add another commit to fix that as well.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 527 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O8JI8B53k0yiQnSsgSt:-O8JI8B53k0yiQnSsgSu:b-yaij76) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f69563c01e0d923068714268c9a006ee3cc46b/pkg/sql/opt/lookupjoin/constraint_builder.go#L527)):*
> ```Go
> 		// computed column expression produces equivalent (but not necessarily
> 		// identical) results if its columns are swapped out with equivalent
> 		// columns.
> ```

I'm not exactly sure why, but this check doesn't appear to be necessary. On v24.2.0:

```sql
CREATE TABLE t (
  i DECIMAL,
  v STRING AS (i::STRING) VIRTUAL,
  PRIMARY KEY (i, v)
);

INSERT INTO t VALUES (1.000);

SELECT * FROM (VALUES (1)) AS v(i)
INNER LOOKUP JOIN t ON v.i = t.i;
-- ERROR: could not produce a query plan conforming to the LOOKUP JOIN hint
```

If you remove it, does the lookup join test you added still succeed?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @yuzefovich)

___
*[`-- commits` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O8JGyA59bXNWA2mrE20):*
This is a link to this very PR... Is that intended?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-O8JGyA59bXNWA2mrE20):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is a link to this very PR... Is that intended?
</blockquote></details>

Nope... Fixed!

**Comment by mgartner** [comment]
@DrewKimball did you see my comment here: https://github.com/cockroachdb/cockroach/pull/126345#issuecomment-2392377355? It looks like something is already preventing the composite-sensitive remapping, without the second commit, unless I'm missing something.

**Comment by DrewKimball** [comment]
>I'm not exactly sure why, but this check doesn't appear to be necessary. On v24.2.0:
>@DrewKimball did you see my comment here: https://github.com/cockroachdb/cockroach/pull/126345#issuecomment-2392377355? It looks like something is already preventing the composite-sensitive remapping, without the second commit, unless I'm missing something.

It looks like we don't plan the lookup join because an integer type is inferred for the `VALUES` in your example. This logic test produces an incorrect result for the table with the virtual column:
```
statement ok
CREATE TABLE t (
  i DECIMAL,
  v STRING AS (i::STRING) VIRTUAL,
  PRIMARY KEY (v, i)
);

statement ok
CREATE TABLE t2 (
  i DECIMAL,
  PRIMARY KEY (i)
);

statement ok
INSERT INTO t VALUES (1.000);
INSERT INTO t2 VALUES (1.000);

query RRT
SELECT * FROM (VALUES (1::DECIMAL)) AS v(i)
INNER LOOKUP JOIN t ON v.i = t.i;
----

query RR
SELECT * FROM (VALUES (1::DECIMAL)) AS v(i)
INNER LOOKUP JOIN t2 ON v.i = t2.i;
----
1  1.000
```

**Comment by DrewKimball** [comment]
>This logic test produces an incorrect result for the table with the virtual column

I've added a version of that test to the last commit.

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126345#-:-O8s21Zt-I_C5B40FaT2:b-msncp4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
