### PR TITLE
storage: eager GC for campaigning replicas

### PR DESCRIPTION
**Pull request by tbg**
Previously, replicas were queued only after a very long time (10d), which
meant that we crucially relied on them being processed eagerly as part of
RemoveReplica. This has proven not to work in practice (and even if it did,
it would be wise to not rely on it); see #7489.

To remedy this, we observe that a replica which has been removed from its
range but wasn't gc'ed is typically stuck in candidate state - nobody talks
to it, and it will continuously campaign.

When a replica is found in that state by the GC queue, and if the replica has
not been processed by the GC queue "recently" (10 days), it is queued for
processing with a higher priority.

In practice, this should remove most left-out replicas quickly, though it
does leave the case in which a replica is erroneously processed (i.e. still
a member of the range at that time), after which it will have a high
last-verified timestamp set and we have to sit out the 10 days. This could
likely be remedied by an event-based eager enqueuing when the replica goes
through a large enough number of unbroken candidacy term changes.

Addresses #7489, though I want to do the field test first before we close it.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7507)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1543 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNDyGkNu-W24pRCiru:-KLNDyGkNu-W24pRCirv:1613412016) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a04b9fe66214336a951beac6eea8dd37a290a2/storage/replica.go#L1543)):*
> ```Go
> 
> //go:generate stringer -type refreshRaftReason
> type refreshRaftReason int32
> ```

nit: any reason for `int32` rather than `int`?

---

*[storage/replica_gc_queue.go, line 126 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNGceEx050D32cDFoP:-KLNGceEx050D32cDFoQ:-1542324587) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L126)):*
> ```Go
> 	}
> 
> 	// Return whether or not lease activity occurred within the inactivity threshold.
> ```

remove this

---

*[storage/replica_gc_queue_test.go, line 43 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNGv-Y2IWW5AKMz20Z:-KLNGv-Y2IWW5AKMz20_:-1046068147) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue_test.go#L43)):*
> ```Go
> 	)
> 
> 	_, _, _, _ = cTS, cTSnext, iTS, iTSnext
> ```

detritus

---

*[storage/replica_test.go, line 5766 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNE4tabsK4sUwZnHcg:-KLNE4tabsK4sUwZnHch:-1326997231) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a04b9fe66214336a951beac6eea8dd37a290a2/storage/replica_test.go#L5766)):*
> ```Go
> 		tc.rng.insertRaftCommandLocked(cmd)
> 		if repropose {
> 			if err := tc.rng.refreshPendingCmdsLocked(reasonTicks /* irrelevant */); err != nil {
> ```

nit: pass `0` if it's irrelevant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLNH779p6lYcJPDTRHU:1417088721)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/replica_gc_queue.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNPm3Cg6QJs3Kg67u7:-KLNPm3DRDZJbsUPaesz:-53762573) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L89)):*
> ```Go
> 		lastActivity.Forward(lease.Expiration)
> 	}
> 	if nextLease != nil {
> ```

why not make this `if nextLease != nil { ... } else if lease != nil { ... }` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLNQU3hVc3K2YdOXjud:1417088721)*

**Comment by tschottdorf** [comment]
Yuck, I've been running this code for an hour and it still hasn't GC'ed the replica. Going to experiment more and update this PR.

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/replica_gc_queue.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNswro5_aBf2BFrRgd:-KLNswro5_aBf2BFrRge:288840703) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L38)):*
> ```Go
> 
> 	// replicaGCQueueTimerDuration is the duration between GCs of queued replicas.
> 	replicaGCQueueTimerDuration = 10 * time.Second
> ```

Any idea why this value is so high? Limiting replica GC to one every 10 seconds doesn't seem right.

---

*[storage/replica_gc_queue.go, line 42 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNtR9gldQzXupr5MoV:-KLNtR9gldQzXupr5MoW:1556040997) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L42)):*
> ```Go
> 	// ReplicaGCQueueInactivityThreshold is the inactivity duration after which
> 	// a range will be considered for garbage collection. Exported for testing.
> 	ReplicaGCQueueInactivityThreshold = 10 * 24 * time.Hour // 10 days
> ```

And why is this so large as well? Checking once every 10 days seems strange.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507)*

**Comment by tschottdorf** [comment]
Just revamped this PR. The latest iteration actually unclogged my cluster. The issue was (presumably) that the cycle which was dispatched eagerly by the replica change went through too early, setting a high last-checked timestamp which let the queue back off a lot. Now when a range is candidate, we always try after 10 seconds.

@petermattis I think the timing is relatively high because processing a replica is a hit to the meta ranges, and the queue runs from each replica. We don't want replicationFactor*numRanges requests hitting those at high frequency. That said, I don't think this code works very well in practice because various other queues will pick it up those defunct ranges which means trouble.

I'd like to try out this change since I think it'll serve us well in the short term, but I'll also file an issue when this merges to revisit this on a more fundamental level.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[storage/queue.go, line 103 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNwd44T2GMiSHyY-RA:-KLNwd44T2GMiSHyY-RB:867457171) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L103)):*
> ```Go
> )
> 
> func isExpectedQueueError(err error) bool {
> ```

oh this is fancy

---

*[storage/queue.go, line 293 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNx2F0VkfNGCGsDZom:-KLNx2F0VkfNGCGsDZon:1801904524) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L293)):*
> ```Go
> 	should, priority := bq.impl.shouldQueue(now, repl, cfg)
> 	if err := bq.addInternal(repl, should, priority); !isExpectedQueueError(err) {
> 		bq.eventLog.Error(errors.Wrapf(err, "unable to add to %s", repl))
> ```

to %s? i think "unable to add %s" was correct.

---

*[storage/queue.go, line 441 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNxOOglp9FQJu48gyO:-KLNxOOglp9FQJu48gyP:-1746001316) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L441)):*
> ```Go
> 		// Create a "fake" get request in order to invoke redirectOnOrAcquireLease.
> 		if err := repl.redirectOnOrAcquireLeaderLease(ctx); err != nil {
> 			if _, harmless := err.GetDetail().(*roachpb.NotLeaderError); !harmless {
> ```

nit: i think this is easier to read as the positive case:
```
if _, harmless := err.GetDetail().(*roachpb.NotLeaderError); harmless {
  bq.eventLog.VInfof(log.V(3), "%s: not holding lease; skipping", repl)
  return nil
}
return errors.Wrap(err.GoError(), "could not obtain lease")
```

also perhaps log the replica:
```
return errors.Wrapf(err.GoError(), "%s: could not obtain lease", repl)
```

---

*[storage/queue.go, line 467 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNxmHx_ltI7iFAWXly:-KLNxmHygRUckKUyTtwO:456538707) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L467)):*
> ```Go
> 	// Check whether the failure is a purgatory error and whether the queue supports it.
> 	if _, ok := err.(purgatoryError); !ok || bq.impl.purgatoryChan() == nil {
> 		bq.eventLog.Error(errors.Wrapf(err, "on %s", repl))
> ```

more words? "not adding to purgatory" or something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[storage/queue.go, line 293 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNx2F0VkfNGCGsDZom:-KLNzehU_2s3oKlobyAR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L293)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> to %s? i think "unable to add %s" was correct.
</details>
Done.

---

*[storage/queue.go, line 441 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNxOOglp9FQJu48gyO:-KLO-8xvx2xpTZV-rnTr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L441)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: i think this is easier to read as the positive case:
> ```
> if _, harmless := err.GetDetail().(*roachpb.NotLeaderError); harmless {
>   bq.eventLog.VInfof(log.V(3), "%s: not holding lease; skipping", repl)
>   return nil
> }
> return errors.Wrap(err.GoError(), "could not obtain lease")
> ```
> 
> also perhaps log the replica:
> ```
> return errors.Wrapf(err.GoError(), "%s: could not obtain lease", repl)
> ```
</details>
Done.

---

*[storage/queue.go, line 467 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNxmHx_ltI7iFAWXly:-KLO-kvmf0j-M-JVGn-9:473624634) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L467)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> more words? "not adding to purgatory" or something
</details>
Not sure what would be helpful here. While I was here, homogenized the purgatory error below.

---

*[storage/replica.go, line 1543 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNDyGkNu-W24pRCiru:-KLO-vPL-EBGUiC-iIKg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a04b9fe66214336a951beac6eea8dd37a290a2/storage/replica.go#L1543)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: any reason for `int32` rather than `int`?
</details>
Done.

---

*[storage/replica_gc_queue.go, line 89 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNPm3Cg6QJs3Kg67u7:-KLNya4fuKLAKqNyn7WK:925964745) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L89)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> why not make this `if nextLease != nil { ... } else if lease != nil { ... }` ?
</details>
That makes an assumption about which lease is further ahead (which would be fine, but is not necessary).

---

*[storage/replica_gc_queue.go, line 126 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNGceEx050D32cDFoP:-KLNykHB3FmP9RsPf6x0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue.go#L126)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove this
</details>
Done.

---

*[storage/replica_gc_queue_test.go, line 43 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNGv-Y2IWW5AKMz20Z:-KLNz2XblVpJ-hXqfDle:34754002) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f7b60b129b2015e75635c27b38e17cb0d60a6c/storage/replica_gc_queue_test.go#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> detritus
</details>
Not in any patch set any more.

---

*[storage/replica_test.go, line 5766 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNE4tabsK4sUwZnHcg:-KLNzYcBaHaQKXQHpi-v:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/35a04b9fe66214336a951beac6eea8dd37a290a2/storage/replica_test.go#L5766)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: pass `0` if it's irrelevant
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r7, 1 of 1 files at r8, 7 of 7 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 467 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLNxmHx_ltI7iFAWXly:-KLO2yjScU6b_zUo-h2d:-1382738388) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e5a2eca510ec1967c3a93cf67ba72efdfc7c1ed/storage/queue.go#L467)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Not sure what would be helpful here. While I was here, homogenized the purgatory error below.
</details>
I mean literally just spell out the implication of the error (which is that this error is not a purgatory error and thus this replica isn't going to get purgatoried).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507)*

**Comment by petermattis** [comment]
I'm curious why the queue is necessary at all in the common case. Can we perform the removal eagerly in `Replica.changeReplicasTrigger`? Does raft not respond when a replica that is not part of the group tries to campaign? Seems like there should be good signals that a replica should be removed.

---

Review status: 2 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLOFW6dm3TvNiLXwFfq:-376505088)*

**Comment by tamird** [comment]
> Does raft not respond when a replica that is not part of the group tries to campaign? Seems like there should be good signals that a replica should be removed.

I believe that's #5789.

:lgtm: again

---

Reviewed 7 of 7 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLOi2Jba9qgk4I2NbrW:-467118511)*

**Comment by petermattis** [comment]
Yep, #5789 looks like it would fix this problem too. And that approach seems like a much better solution than this PR.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLR3eQlMQyv2_uk6f_M:1257229914)*

**Comment by tschottdorf** [comment]
I agree, consider this a holdover until that issue is addressed.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLRT9dSpF7K_4yt2Q4-:1127938818)*

**Comment by tschottdorf** [comment]
screen shot 2016-06-29 at 10 18 24 am

managed to up-replicate from 1x108gb to 5x with this change.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 8 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 442 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLRY5q6DpXGw-Zt729C:-KLRY5q6DpXGw-Zt729D:1969195424) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f134c9eab87193dda6bdbf4f484a5bc4f53e4a/storage/queue.go#L442)):*
> ```Go
> 		if err := repl.redirectOnOrAcquireLeaderLease(ctx); err != nil {
> 			if _, harmless := err.GetDetail().(*roachpb.NotLeaderError); harmless {
> 				bq.eventLog.VInfof(log.V(3), "%s: not holding lease; skipping", repl)
> ```

I wonder if this should be added to the eventlog at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-:-KLRZ4zOpzNMU5dxw9uV:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/queue.go, line 442 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507#-KLRY5q6DpXGw-Zt729C:-KLRroS3HCYuCP8g0frd:428891463) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f134c9eab87193dda6bdbf4f484a5bc4f53e4a/storage/queue.go#L442)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I wonder if this should be added to the eventlog at all.
</details>
Hasn't been spammy so far (in fact never seen it). If it does show up with some regularity, probably means something is up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7507)*

**Pull request merged**
