### PR TITLE
kvcoord: fix rangefeed retries on transport errors

### LINKED ISSUE #66636: changefeedccl: Rangefeeds might fail due to stale range cache
Customer observed changefeeds failing after some of the nodes were
decomissioned

```
ERROR: failed to connect to n4 at 172.31.91.238:26257: initial connection heartbeat failed: rpc error: code = PermissionDenied desc = n4 was permanently removed from the cluster at 2021-05-27 21:08:12.282567682 +0000 U…
```

In addition, error message
```
return args.Timestamp, newSendError(
				fmt.Sprintf("sending to all %d replicas failed", len(replicas)))
```

The hypothesis is that we might not be handling decomissioned nodes correctly.  In particular, perhaps we need to handle `InitialHeartbeatFailed` error in addition to the errors we already handle in `partialRangeFeed` 

1. We need to write tests around decomissioned nodes
2. We need to improve above error message in dist_sender_rangefeed -- we should print all replicas.
3. We need to handle decomissioned nodes

### PR DESCRIPTION
**Pull request by erikgrinaker**
### rangecache: consider FailedPrecondition a retryable error

In #66199, the gRPC error `FailedPrecondition` (returned when contacting
a decommissioned node) was incorrectly considered a permanent error
during range descriptor lookups, via `IsRangeLookupErrorRetryable()`.
These lookups are all trying to reach a meta-range (addressed by key),
so when encountering a decommissioned node they should evict the cache
token and retry the lookup.

This patch reverses that change, making only authentication errors
permanent (i.e. when the local node is decommissioned or otherwise not
part of the cluster).

Release note: None

### kvcoord: fix rangefeed retries on transport errors

`DistSender.RangeFeed()` was meant to retry transport errors after
refreshing the range descriptor (invalidating the cached entry).
However, due to an incorrect error type check (`*sendError` vs
`sendError`), these errors failed the range feed without invalidating
the cached range descriptor.

This was particularly severe in cases where a large number of nodes had
been decommissioned, where some stale range descriptors on some nodes
contained only decommissioned nodes. Since change feeds set up range
feeds across many nodes and ranges in the cluster, they are likely to
encounter these decommissioned nodes and return an error -- and since
the descriptor cache wasn't invalidated they would keep erroring until
the nodes were restarted such that the caches were flushed (often
requiring a full cluster restart).

Resolves #66636, touches #66586.

Release note (bug fix): Change feeds now properly invalidate cached
range descriptors and retry when encountering decommissioned nodes.

/cc @cockroachdb/kv

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

**Review by tbg — APPROVED** [review]
:lgtm: nice, thank you for going the extra mile with mockgen! I know you've struggled with getting this to play ball with bazel, is this going to be the same amount of pain for the next person trying to use mockgen elsewhere? If so, I wonder where a good place would be to document how this works.

> Reviewed 1 of 1 files at r1, 3 of 9 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-:-MdGwD3xE1Yk-2p581QO:b-ff4v8s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/kv/kvclient/kvcoord/BUILD.bazel, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGu6bi3EsGAqhlEX-B:-MdGu6bi3EsGAqhlEX-C:broigbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/kvcoord/BUILD.bazel#L73)):*
> ```Starlark
> )
> 
> # keep
> ```

Missing words? Or some secret bazel stuff I don't know about.
___
*[pkg/kv/kvclient/kvcoord/BUILD.bazel, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuGZMBicPHCv6T3a4:-MdGuGZMBicPHCv6T3a5:b8gki5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/kvcoord/BUILD.bazel#L85)):*
> ```Starlark
> )
> 
> gomock(
> ```

Uh what, why did you need that.
___
*[pkg/kv/kvclient/rangefeed/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuYUoCblRI9JH7uZ4:-MdGuYUoCblRI9JH7uZ5:b-kg0ap6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/BUILD.bazel#L47)):*
> ```Starlark
>     name = "mocks_rangefeed",
>     out = "mocks_generated.go",
>     interfaces = [""],  # required, yet ignored when using source -- bug?
> ```

:(

Did you want to ask Ricky for a review on the bazel-specific parts of this PR?
___
*[pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuzW5EgIDnVdJq9mX:-MdGuzW5EgIDnVdJq9mY:b86qyw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go#L346)):*
> ```Go
> 	// Make sure scan failure gets retried.
> 	db.EXPECT().Scan(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(errors.New("scan failed"))
> 	db.EXPECT().Scan(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
> ```

This (and below) can't be chained into the invocation above, right? `.Return(x).Return(y)`?
___
*[pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go, line 348 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGvA0T5DJRDFGP0QNj:-MdGvA0T5DJRDFGP0QNk:b-7c95sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go#L348)):*
> ```Go
> 	db.EXPECT().Scan(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
> 
> 	// Make sure rangefeed is retried even after 3 failures, then succeed and cancel context.
> ```

(which is the signal for the range feed to shut down gracefully)?
___
*[pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go, line 370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGvFy86zt4HKDcg7c2:-MdGvFy86zt4HKDcg7c3:bmt00eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go#L370)):*
> ```Go
> 	select {
> 	case <-ctx.Done():
> 	case <-time.After(time.Second):
> ```

10s because race builds?

**Review by erikgrinaker — COMMENTED** [review]
> is this going to be the same amount of pain for the next person trying to use mockgen elsewhere?

Hopefully the next person can just grep for `gomock` and follow the same pattern.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-:-MdGx2lKE_mXP1f8OP0d:b-t2qhxm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @rickystewart, and @tbg)

___
*[pkg/kv/kvclient/kvcoord/BUILD.bazel, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGu6bi3EsGAqhlEX-B:-MdGx9Pp7zc-SWSuFHo2:be1zunf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/kvcoord/BUILD.bazel#L73)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Missing words? Or some secret bazel stuff I don't know about.
</blockquote></details>

Secret Bazel stuff. Gazelle, which autogenerates Bazel build files from Go source files, doesn't handle the gomock target libraries properly so it will go ahead and replace all of this stuff with its own targets. `# keep` tells Gazelle to back off. This also means that we can't get Gazelle to manage dependencies for these targets, so they must be updated by hand.
___
*[pkg/kv/kvclient/kvcoord/BUILD.bazel, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuGZMBicPHCv6T3a4:-MdGxea29Cs2d9B0AQoo:bhntsyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/kvcoord/BUILD.bazel#L85)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Uh what, why did you need that.
</blockquote></details>

Bazel doesn't use the `go:generate` comments, it wants to handle all code generation and dependency tracking itself, so we need separate code generation mechanisms for Bazel and the Go build chain.
___
*[pkg/kv/kvclient/rangefeed/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuYUoCblRI9JH7uZ4:-MdGxwbC7CcIPkBqp2cg:b-gty5eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/BUILD.bazel#L47)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

:(

Did you want to ask Ricky for a review on the bazel-specific parts of this PR?
</blockquote></details>

Good idea. @rickystewart mind looking over the Bazel bits here? The purpose is to autogenerate test mock objects from interface definitions.
___
*[pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuzW5EgIDnVdJq9mX:-MdH-2dN00v1Ei46PRsY:b-xk5qsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go#L346)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This (and below) can't be chained into the invocation above, right? `.Return(x).Return(y)`?
</blockquote></details>

This can (updated), but not the one below because of the `Times(3)` thing.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @rickystewart, and @tbg)

___
*[pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go, line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuzW5EgIDnVdJq9mX:-MdH0Y_nEYOhkQzV1sqb:b-qby9pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go#L346)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This can (updated), but not the one below because of the `Times(3)` thing.
</blockquote></details>

Actually no, the chained return replaces the previous definition.

**Review by aliher1911 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-:-MdHZdkI27KbuJ3U7Dvg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rickystewart and @tbg)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 1329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdHYua88xnerlRG9MUh:-MdHYua9CmuZmcCBg-fK:bmx9evd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b396b8ad2039a7ae1f470d628d6d67d6dd2e512e/pkg/kv/kvclient/rangecache/range_cache.go#L1329)):*
> ```Go
> 	// Auth errors are not retryable. These imply that the local node has been
> 	// decommissioned or is otherwise not part of the cluster.
> 	return !grpcutil.IsAuthError(err)
> ```

The original motivation was that since range lookup goes through DistSender.sendToReplicas to get range it would retry FailedPrecondition and evict replicas, but the error code itself would never bubble up. So there would be no need to handle it specifically anywhere above. I'm probably missing invalidation case here.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rickystewart and @tbg)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 1329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdHYua88xnerlRG9MUh:-MdH_HkQ1_612ImVg1Bn:b-h63sin) ([raw file](https://github.com/cockroachdb/cockroach/blob/b396b8ad2039a7ae1f470d628d6d67d6dd2e512e/pkg/kv/kvclient/rangecache/range_cache.go#L1329)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

The original motivation was that since range lookup goes through DistSender.sendToReplicas to get range it would retry FailedPrecondition and evict replicas, but the error code itself would never bubble up. So there would be no need to handle it specifically anywhere above. I'm probably missing invalidation case here.
</blockquote></details>

Sure, that's probably true, but the logic is a bit backwards -- if it ever _did_ see a `FailedPrecondition` it shouldn't consider it permanent, so there's no reason to mark it as permanent.

**Review by irfansharif — COMMENTED** [review]
For the bazel stuff, something looks off. After trying it out a bit locally, I can see why this PR was so cumbersome with Bazel. So the way `go:generate mockgen` stuff is setup here will not play well with Bazel. Here's why:
- To generate `mock_generated.go` in `pkg/kv/kvclient/kvcoord`, we depend on the code already present in `pkg/kv/kvclient/kvcoord`. 
- The test that uses these mocks, `TestDistSenderRangeFeedRetryOnTransportErrors`, is also in`kvcoord`. 
- There's a dependency cycle! `kvcoord` (`TestDistSenderRangeFeedRetryOnTransportErrors`) depends on mocks (generated with package name `kvcoord`) which in turn depends on `kvcoord`. 

The reason `go:generate stuff` was comparatively easier to write is that it'll run the generation script using an on-disk image of the kvcoord package, to generate more stuff in kvcoord, and then the tests in kvcoord can simply assume the on-disk state has been updated to include the mocks in kvcoord. Bazel doesn't like this -- it can't figure out the full set of transitive dependencies needed to compile+run `TestDistSenderRangeFeedRetryOnTransportErrors`. It forces you to break this hidden dependency cycles to be able to correctly cache artifacts + parallelize your test runs. This subtle `go build` behavior, though convenient during development, is difficult to build on-top of to get the kind of CI performance bazel promises.

Breaking this dependency cycle is pretty easy, it would look something like https://github.com/cockroachdb/cockroach/pull/66975. I'd normally tested my changes locally with `bazel build //pkg/kv/kvclient/kvcoord:{kvcoord_test,kvcoord,mocks_transport}`, but it looks like my local bazel builds of the `kvcoord_test` were not working at SHAs even before this PR -- not investigating. In any case, the attempt in that draft PR above doesn't break `bazel build cockroach-short`.

---

As for the the rangefeed bazel work, have you taken a look at https://github.com/cockroachdb/cockroach/pull/65029? Given there we're using source mode generation, our approach there should apply here as well. Happy to work through it with you if it proves to be as annoying. Looking at the upstream libraries, this could all be documented better. Perhaps we could in-code so it's greppable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-:-MdI4bsbA3hcE2VdD3rP:b1rsgke)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rickystewart and @tbg)

___
*[pkg/kv/kvclient/rangefeed/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuYUoCblRI9JH7uZ4:-MdI5Ob5-uCQJZ6jXynj:b9w9wzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/BUILD.bazel#L47)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Good idea. @rickystewart mind looking over the Bazel bits here? The purpose is to autogenerate test mock objects from interface definitions.
</blockquote></details>

Reading through https://github.com/jmhodges/bazel_gomock and https://github.com/golang/mock, and the corresponding `mockgen` invocation in this package:

```
//go:generate mockgen -package=rangefeed -source rangefeed.go -destination=mocks_generated.go .
```

We're using the "source mode", which is "Required if source is not set, and ignored if source is set". I can't speak to whether or not using source mode is what we want, but this is not a bug.

**Review by irfansharif — COMMENTED** [review]
An short-term alternative to all this is to not try and bother with generating these mocks through bazel now, and just listing these mock_generated.go files as regular user-edited files in bazel (so adding them to `srcs` for the `go_{library,test}` targets), and punting off the proper generation of these in a separate issue (that I'd be happy to take on soon, documenting the right gomock patterns as I go). It'd be good to have @rickystewart chime in though, seeing as how they're very close to migrating all instances of `go:generate` to bazel.

**Comment by rickystewart** [comment]
Haven't had a chance to review this in earnest yet, I'll do so ASAP.

> An short-term alternative to all this is to not try and bother with generating these mocks through bazel now, and just listing these mock_generated.go files as regular user-edited files in bazel (so adding them to `srcs` for the `go_{library,test}` targets), and punting off the proper generation of these in a separate issue (that I'd be happy to take on soon, documenting the right gomock patterns as I go). It'd be good to have @rickystewart chime in though, seeing as how they're very close to migrating all instances of `go:generate` to bazel.

The `go:generate` work has actually been done (#57787), so it would be great if we could avoid regressing it.

**Review by rickystewart — APPROVED** [review]
This seems fine to me.

**Review by erikgrinaker — COMMENTED** [review]
Thanks for having a look @irfansharif! I get why Bazel needs things to be set up in this way. For Bazel itself, I don't think it matters much that these are all in the same Go package though -- it strictly just needs to know which source files `gomock` depends on (at least for source mode), then the Go library could depend on those source files and the mocks. But that wouldn't work well with Gazelle, I think. Being disciplined about splitting tests out to a separate package would help -- but I'd like to keep this PR fairly backportable without doing a bunch of restructuring.

I'm going to merge this as-is for now, and we can revisit this setup later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-:-MdLusArE_Jg_HLYc6g8:blvtq7s)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rickystewart and @tbg)

___
*[pkg/kv/kvclient/rangefeed/BUILD.bazel, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66910#-MdGuYUoCblRI9JH7uZ4:-MdLtry59rqK-JSm93mm:b-excln0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8355fc966a5f803d103131a9c304f9ef9dfd9618/pkg/kv/kvclient/rangefeed/BUILD.bazel#L47)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Reading through https://github.com/jmhodges/bazel_gomock and https://github.com/golang/mock, and the corresponding `mockgen` invocation in this package:

```
//go:generate mockgen -package=rangefeed -source rangefeed.go -destination=mocks_generated.go .
```

We're using the "source mode", which is "Required if source is not set, and ignored if source is set". I can't speak to whether or not using source mode is what we want, but this is not a bug.
</blockquote></details>

Why wouldn't this be a bug? `source` and `interfaces` are mutually exclusive, so requiring `interfaces` when `source` is set doesn't make any sense.

**Comment by erikgrinaker** [comment]
bors r=miretskiy,tbg,aliher1911,rickystewart

**Comment by aliher1911** [comment]
When do you plan to backport this? It requires my other backport to land first.

**Comment by erikgrinaker** [comment]
We should get these backported soon. Let's discuss elsewhere.

**Pull request merged**
