### PR TITLE
spanconfig: carve empty ranges for pseudo-table IDs

### PR DESCRIPTION
**Pull request by irfansharif**
This commit is similar in spirit to #73746 in that it gets rid of a
benign difference between the span configs infrastructure and the system
config span. When enabling span configs by default (#73876), we observed
a wide blast radius with respect to test failures. This was in large
part due to assumptions we've baked in regarding the number of splits we
should expect at cluster start, often waiting for the same number of
ranges to form before executing the rest of the test.

The differences between the SystemConfigSpan and the span configs
infrastructure in how they handled (empty) pseudo table keyspaces makes
for an annoying large list of tests to adjust manually. Instead we take
the lazy route and generate empty ranges for pseudo table IDs as we did
before. We can get rid of this special handling once we actually get rid
of the system config span, and adjust all these tests accordingly. Doing
it later is also preferable should we need to revert pieces of #73876
due to unforeseen instability.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msab9hQA-SFY9NDUeIA:-Msab9hQA-SFY9NDUeIB:b-e94ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b9ee18e4e71da186d1e8231cc9daf1647143ba/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L90)):*
> ```Go
> 			}
> 
> 			if (id == keys.SystemDatabaseID || id == keys.RootNamespaceID) && s.codec.ForSystemTenant() {
> ```

Could you add a comment explaining why we need to handle this case when `id == keys.SystemDatabaseID || id == keys.RootNamespaceID`?
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msabhut3LPM6MrvRgQD:-Msabhut3LPM6MrvRgQE:b530zrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b9ee18e4e71da186d1e8231cc9daf1647143ba/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L107)):*
> ```Go
> 				// removed (#70560).
> 				for _, pseudoTableID := range keys.PseudoTableIDs {
> 					zone, err := sql.GetHydratedZoneConfigForDatabase(ctx, txn, s.codec, keys.SystemDatabaseID)
> ```

We're setting the system database's zone config for each pseudo table? Don't we allow custom zone configs to be set on individual pseudo IDs? Is that handled here? My memory of this is hazy, so I might be misremembering something.

Actually, I might be misunderstanding this patch. It's not trying to respect the zone configs configured on the keyspaces referenced by these pseudo IDs — that's already handled by `generateSpanConfigurationsForNamedZone`. This is just trying to add split points in the system database on them. Is that the correct understanding?

If so, would it be possible to unify this code further by having `findDescendantLeafIDs` return the IDs of all psuedo tables when given the `SystemDatabaseID` and then having `generateSpanConfigurations` handle these IDs properly? Would that avoid the `SystemDatabaseID || RootNamespaceID` complication above?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msab9hQA-SFY9NDUeIA:-MsbCf8m8fZub9fjK6Lz:b-lkclqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b9ee18e4e71da186d1e8231cc9daf1647143ba/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a comment explaining why we need to handle this case when `id == keys.SystemDatabaseID || id == keys.RootNamespaceID`?
</blockquote></details>

Did you happen to see the comment right below?  Moved it above the `addedPseudoTableSpans` no-op check to make it clearer.  For your question specifically:

```
// We have special handling for the system database (and RANGE
// DEFAULT, which the system database inherits from). The system
```

Also see comment below.
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msabhut3LPM6MrvRgQD:-MsbD1wB0PsZ7szgPmcy:b-5su1tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b9ee18e4e71da186d1e8231cc9daf1647143ba/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L107)):*
> It's not trying to respect the zone configs configured on the keyspaces referenced by these pseudo IDs — that's already handled by generateSpanConfigurationsForNamedZone. This is just trying to add split points in the system database on them. Is that the correct understanding?

Exactly! Added a footnote to the comment block, hopefully making it clearer.

```
// [1]: Consider the liveness range [/System/NodeLiveness,
//      /System/NodeLivenessMax). It's identified using the
//      pseudo ID 22 (i.e. keys.LivenessRangesID). Because we're
//      using a pseudo ID, what of [/Table/22-/Table/23)? This
//      is a keyspan with no contents, yet one the system config
//      span splits along to create an empty range. It's
//      precisely this "feature" we're looking to emulate. As
//      for what config to apply over said range -- we do as the
//      system config span does, applying the config for the
//      system database.
```
> If so, would it be possible to unify this code further by having findDescendantLeafIDs return the IDs of all psuedo tables when given the SystemDatabaseID and then having generateSpanConfigurations handle these IDs properly?

It's not possible with how the code is currently structured, and I wanted to keep this diff minimal. The problem is that `generateSpanConfigurations` knows to generate "special" spans when passed in a pseudo ID. In our example above, even if we augmented `findDescendantLeafIDs` to include these pseudo IDs when operating off of `DATABASE SYSTEM`/`RANGE DEFAULT`, when a specific pseudo range ID (say, `keys.LivenessRangesID`) is passed into `generateSpanConfigurations`, it would generate what the pseudo ID represents (in our example `[/System/NodeLiveness, /System/NodeLivenessMax)`, instead of  `[/Table/22-/Table/23)`). It's possible to make it work, but I found this to be simpler.

**Review by arulajmani — APPROVED** [review]
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-MseeOIf6DhwcPsJo7V4:-MseeOIf6DhwcPsJo7V5:bo5tsix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L90)):*
> ```Go
> 			}
> 
> 			if (id == keys.SystemDatabaseID || id == keys.RootNamespaceID) && s.codec.ForSystemTenant() {
> ```

nit: consider pulling all this logic to handle empty ranges corresponding to pseudo IDs into its own function. You'll be iterating over IDs twice, but I think it reads clearer. 
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msedhfs3S7396AzAUTB:-Msedhfs3S7396AzAUTC:b-836edm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L104)):*
> ```Go
> 				// removed (#70560).
> 				//
> 				// [2]: Consider the liveness range [/System/NodeLiveness,
> ```

s/[2]/[1]/g? 
___
*[pkg/sql/zone_config.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-MsecfB558F8TY3AaXd-:-MsecfB558F8TY3AaXd0:b-3i67hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/sql/zone_config.go#L364)):*
> ```Go
> 	}
> 	zoneID, zone, _, _, err := getZoneConfig(
> 		codec, id, getKey, false /* getInheritedDefault */, true, /* mayBeTable */
> ```

Should `mayBeTable` be false here?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-MseeOIf6DhwcPsJo7V4:-Msewh1_1OJ7PBi3i0iF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L90)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: consider pulling all this logic to handle empty ranges corresponding to pseudo IDs into its own function. You'll be iterating over IDs twice, but I think it reads clearer. 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-Msedhfs3S7396AzAUTB:-Msewf849xXcnv_9CxB9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L104)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/[2]/[1]/g? 
</blockquote></details>

Done.
___
*[pkg/sql/zone_config.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74171#-MsecfB558F8TY3AaXd-:-MsewgCL3FOp-8oz1wuJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6925ae5581c245da036b0a1c9afc6b8e095cbf0/pkg/sql/zone_config.go#L364)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should `mayBeTable` be false here? 
</blockquote></details>

Done.

**Pull request merged**
