### PR TITLE
sqlliveness: bug fixes and improvements

### PR DESCRIPTION
**Pull request by andreimatei**
Please see individual commits.

Release note: None
Epic: None

### CODE REVIEW

**Comment by andreimatei** [comment]
First two commits are #90777.

**Review by andreimatei — COMMENTED** [review]
#90777 is now merged. All commits in this PR are original.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-:-NFQPauu0eDdXpDVzT_l:b-8is1zh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @ajwerner)

**Review by knz — COMMENTED** [review]
> Reviewed 22 of 22 files at r11, 18 of 18 files at r12, 17 of 17 files at r13, 18 of 18 files at r14, 17 of 17 files at r15, 17 of 17 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @ajwerner, and @andreimatei)

___
*[`-- commits` line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU1qRtCg0AgSfm1hrB):*
I have no objection to the change, but I don't understand the rationale. How come the amount of state protected makes a difference in the choice between regular vs rw?

When I was at school, i was taught that the tradeoff is only a matter of the number of readers vs the number of writers. When we expect more readers, rwmutex is better.

What of the last field that remains under the mutex? Is it truly mostly equally written and read from?
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 19 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2Qp8DLIS3mEY6wAc:-NFU2Qp8DLIS3mEY6wAd:b-s3ipg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L19)):*
> ```Go
> import (
> 	"context"
> 	"errors"
> ```

cockroachdb/errors
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 127 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2Uq-AhwbSQVWfeHX:-NFU2Uq-AhwbSQVWfeHY:b-81zlmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L127)):*
> ```Go
> 	testKnobs     sqlliveness.TestingKnobs
> 	mu            struct {
> 		syncutil.Mutex
> ```

maybe also a q of normal vs rw here.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 292 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2lbK8xVzEiWJSfax:-NFU2lbK8xVzEiWJSfay:b1c3voh) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L292)):*
> ```Go
> 	// Keep track of the fact that this Instance is not usable anymore. Further
> 	// Session() calls will return errors.
> 	l.mu.Lock()
> ```

`defer l.mu.Unlock`
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 93 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU35a33_1znWJoeF45:-NFU35a33_1znWJoeF46:bux12cd) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L93)):*
> ```Go
> 	// and causes further Session() calls to fail.
> 	stopper.Stop(ctx)
> 	testutils.SucceedsSoon(t, func() error {
> ```

How come you need SucceedsSoon here? The heartbeat loop is tied to the stopper via RunAsync, so the goroutine is guaranteed to have completed after Stop returns?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @ajwerner, and @knz)

___
*[`-- commits` line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU1qRtCg0AgSfm1hrB):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I have no objection to the change, but I don't understand the rationale. How come the amount of state protected makes a difference in the choice between regular vs rw?

When I was at school, i was taught that the tradeoff is only a matter of the number of readers vs the number of writers. When we expect more readers, rwmutex is better.

What of the last field that remains under the mutex? Is it truly mostly equally written and read from?
</blockquote></details>

The Go RWMutex is not a scalable implementation - all readers synchronize with each other to enter/exit the critical section, unfortunately (but once a reader is inside, another one can also enter, of course). In fact, the `Mutex` implementation scales *better* for small critical section than `RLock/RUnlock` until 8 cores, where the two become pretty similar. `RWMutex`'s `Lock/Unlock` is both slower absolutely, and scales worse than the other two.
So, it's not about the "amount of state", it's about the duration of reader critical sections. When all critical sections are small (which is the case here, and is also commonly the case), the `RWMutex` is worse. There are special situations where you might want to use `RWMutex` even for fairly small critical sections - which is when one of those sections, even though it's small, is prone to preemption and you don't want that to affect the tail latency of other readers. But these are rare.
More importantly, seeing `RWMutex` sends a message to the reader that there's particular considerations around that code.

In the case we're discussing here, the use of the `RWMutex` never really made sense. The commit message is being polite. It did use to be the case, however, that the mutex was held while running a list of callbacks, so from the perspective of this struct, there was some theoretical justification for it.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 19 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2Qp8DLIS3mEY6wAc:-NFZTew-6f8qQYrdCyCd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L19)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

cockroachdb/errors
</blockquote></details>

done
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 127 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2Uq-AhwbSQVWfeHX:-NFZTjK-5sCVfYASQh54:bpec3qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L127)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

maybe also a q of normal vs rw here.
</blockquote></details>

I don't think it's a good idea, for the same reasons. Switching to `RWMutex` would not be a good idea for the vast majority of mutexes in the codebase. 
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 292 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU2lbK8xVzEiWJSfax:-NFZUNUM5QV1urN3afO_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance.go#L292)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`defer l.mu.Unlock`
</blockquote></details>

done
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 93 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFU35a33_1znWJoeF45:-NFZUuit82UqivHKBznY:b-4zfani) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L93)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

How come you need SucceedsSoon here? The heartbeat loop is tied to the stopper via RunAsync, so the goroutine is guaranteed to have completed after Stop returns?
</blockquote></details>

you're right, done

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 18 files at r12, 1 of 5 files at r17, 2 of 2 files at r19, 5 of 5 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-:-NFidaxmEnXk7cqsNPHa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @andreimatei, and @knz)

___
*[`pkg/server/server_sql.go` line 425 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFiaT_j1qA2frRwuHnq:-NFiaT_j1qA2frRwuHnr:bhjx386) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/server/server_sql.go#L425)):*
> ```Go
> 
> // OnSessionDeleted implements the slinstance.SessionEventListener interface.
> func (s *stopperSessionEventListener) OnSessionDeleted(ctx context.Context) bool {
> ```

nit: name the return param for readability. 
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 20 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFi_oyLAD6X8CRG7etM:-NFi_oyLAD6X8CRG7etN:b-dxvtmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L20)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/cockroachdb/errors"
> ```

I think this needs a gofmt. 
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 186 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidX2T5vO6e7ZEjVBx:-NFidX2T5vO6e7ZEjVBy:bc9i656) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L186)):*
> ```Go
> 	}
> 	// When the session is set, blockCh should not be set.
> 	if l.mu.blockCh != nil {
> ```

nit: panic errors and not strings



_Code quote:_
```Go
		panic("expected session to be set")
	}
	// When the session is set, blockCh should not be set.
	if l.mu.blockCh != nil {
		panic("unexpected blockCh")
	}
```
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 269 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFibJBBD_2KgfEIpeNG:-NFibJBBD_2KgfEIpeNH:b-xkzcqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L269)):*
> ```Go
> 	if err != nil {
> 		if ctx.Err() == nil {
> 			panic(fmt.Sprintf("expected canceled ctx on err: %s", err))
> ```

Can you panic an error rather than a string? I think if you panic a string, it'll get redacted when it goes to sentry. https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/util/log/logcrash/crash_reporting.go#L189
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidGem7WK1ph0GC4hV:-NFidGem7WK1ph0GC4hW:bd2cth2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
> ```Go
> 	err := l.heartbeatLoopInner(ctx)
> 	if err == nil {
> 		panic("expected heartbeat to always terminate with an error")
> ```

Same nit about panicking an error

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @ajwerner, and @knz)

___
*[`pkg/server/server_sql.go` line 425 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFiaT_j1qA2frRwuHnq:-NFikUH2C52-nZ8XlyQU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/95f2dde6fc4e5ab0b82f94d2908a77ced146896e/pkg/server/server_sql.go#L425)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: name the return param for readability. 
</blockquote></details>

done
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 20 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFi_oyLAD6X8CRG7etM:-NFij1-r02Cd1DjsV_Qs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L20)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this needs a gofmt. 
</blockquote></details>

done
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 186 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidX2T5vO6e7ZEjVBx:-NFiiHWj5Y7k4K3oL3Cg:b9yr1j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L186)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: panic errors and not strings
</blockquote></details>

switched to `log.Fatal()`, which hopefully achieves the same
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 269 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFibJBBD_2KgfEIpeNG:-NFiiwG9Elqxxay1tGsL:b-tnv7w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L269)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you panic an error rather than a string? I think if you panic a string, it'll get redacted when it goes to sentry. https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/util/log/logcrash/crash_reporting.go#L189
</blockquote></details>

switched to `log.Fatal()`
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 285 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidGem7WK1ph0GC4hV:-NFiizbr9NiacHli6oGk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L285)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Same nit about panicking an error
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @ajwerner, and @andreimatei)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 186 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidX2T5vO6e7ZEjVBx:-NFimFgA2C0XALwOb6s3:b4o3ibr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L186)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

switched to `log.Fatal()`, which hopefully achieves the same
</blockquote></details>

panic+error is objectively better FYI - it gives us a chance to recover in a test suite.

I don't mind about it _in this case_ (given how unlikely it is), but I've noticed you're biased towards `log.Fatal` in other work so I want to remind you to over-compensate  on this when you can.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 269 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFibJBBD_2KgfEIpeNG:-NFimb7_4zC10lHTX-MF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L269)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

switched to `log.Fatal()`
</blockquote></details>

ditto

**Comment by knz** [comment]
> panic+error is objectively better FYI - it gives us a chance to recover in a test suite.

I mean it gives a chance to the test runner to still run the tests after it.

log.Fatal will stupidly stop the entire test process and doesn't give a chance to the other tests to run.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @ajwerner, and @knz)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 186 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidX2T5vO6e7ZEjVBx:-NFiuBo97Cdae2UsMiz4:b-9e8dlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L186)):*
> I mean it gives a chance to the test runner to still run the tests after it.

> log.Fatal will stupidly stop the entire test process and doesn't give a chance to the other tests to run.

(Rafa, I think you sometimes comment from Github (or email?) and your comments don't make it to the right Reviewable thread)

TIL that the bazel test runner seems to continue running tests after a panic. `go test` doesn't do that.
Anyway, I think `log.Fatal()` is fine for assertion failures. I don't think whether or not tests continue to run is an important consideration; I think ergonomics are more important. I usually prefer `log.Fatal()` cause it uses the log tags, and because it does the string formatting. With panics, you frequently have to combine it `fmt.Sprintf()` (or better with `errors.Newf()`, I guess). I don't think we should discourage people away from `log.Fatal()`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @ajwerner, and @andreimatei)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 186 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/90586#-NFidX2T5vO6e7ZEjVBx:-NFiwsan2GNMz-5sYVUC:b-6apvg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c8090c44ff595bcd9f7045d327fad631ce4741/pkg/sql/sqlliveness/slinstance/slinstance.go#L186)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> I mean it gives a chance to the test runner to still run the tests after it.

> log.Fatal will stupidly stop the entire test process and doesn't give a chance to the other tests to run.

(Rafa, I think you sometimes comment from Github (or email?) and your comments don't make it to the right Reviewable thread)

TIL that the bazel test runner seems to continue running tests after a panic. `go test` doesn't do that.
Anyway, I think `log.Fatal()` is fine for assertion failures. I don't think whether or not tests continue to run is an important consideration; I think ergonomics are more important. I usually prefer `log.Fatal()` cause it uses the log tags, and because it does the string formatting. With panics, you frequently have to combine it `fmt.Sprintf()` (or better with `errors.Newf()`, I guess). I don't think we should discourage people away from `log.Fatal()`.
</blockquote></details>

Yeah I was treating the bias, not suggesting moving away from log.Fatal entirely. We should have better guidance.

**Comment by knz** [comment]
(i don't consider myself to be a stakeholder here - don't wait for my review to merge this)

**Comment by andreimatei** [comment]
TFTRs!

bors r+

**Pull request merged**
