### PR TITLE
opt: build LIMIT/OFFSET

### PR DESCRIPTION
**Pull request by RaduBerinde**
Support for Limit and Offset. We use two operators because we can't
have three children and a private in a single operator; use of offset
should be relatively rare and we should be able to coalesce the
operators at execbuild time.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/operator.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q4AzsYIN7WXbxLw7b:-L7Q4AzsYIN7WXbxLw7c:b-608t22) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/operator.go#L100)):*
> ```Go
> // the desired ordering). Otherwise, the operator skips over the first Offset
> // rows and returns the following Limit rows.
> type LimitOpDef struct {
> ```

I don't see this being used anywhere, since you're directly using `Ordering` in the `Limit` and `Offset` op private field.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q7jkRfWcovpP708Re:-L7Q7jkRfWcovpP708Rf:bsuyjmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L119)):*
> ```Go
> 		// input.
> 		private := ev.Private()
> 		if private == nil {
> ```

In what case could/should this ever be nil? Even if we had a limit without ordering, i'd still expect use to use `&Ordering{}` so that we don't need to sprinkle nil checks around the code.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q8o3rQI9TuFNXXSra:-L7Q8o3rQI9TuFNXXSrb:b4k60t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L176)):*
> ```Go
> 			private := ev.Private()
> 			if private != nil {
> 				childProps.Ordering = *private.(*opt.Ordering)
> ```

This interacts weirdly with the code above. Say that an `Ordering` is required of the `Limit` operator. Then the code above will set `childProps.Ordering = nil` and `changed = true`. But then this code will set `childProps.Ordering` after all, often back to the same value. In that case, `changed` will be true, even though there wasn't really a change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735)*

**Comment by andy-kimball** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q8o3rQI9TuFNXXSra:-L7QEAeCxTmhyEmQVHPg:b-80hrd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L176)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This interacts weirdly with the code above. Say that an `Ordering` is required of the `Limit` operator. Then the code above will set `childProps.Ordering = nil` and `changed = true`. But then this code will set `childProps.Ordering` after all, often back to the same value. In that case, `changed` will be true, even though there wasn't really a change.
</blockquote></details>

After chatting with Radu, I see it's good as-is, because to check whether it really changed would require comparing the orderings by value, which is not worth the trouble in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q7jkRfWcovpP708Re:-L7QK6gEgOgUGYW33xlc:b9fu9v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L119)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In what case could/should this ever be nil? Even if we had a limit without ordering, i'd still expect use to use `&Ordering{}` so that we don't need to sprinkle nil checks around the code.
</blockquote></details>

Changed to `&Ordering{}`

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q8o3rQI9TuFNXXSra:-L7QKAzxM9SRiTV3B3Y8:b6ps1bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L176)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

After chatting with Radu, I see it's good as-is, because to check whether it really changed would require comparing the orderings by value, which is not worth the trouble in this case.
</blockquote></details>

I added `Equals` methods to PhysicalProps/Ordering and removed the `changed` flag, which makes the entire logic simpler, and allows a simple `switch` for everything.

---

*[pkg/sql/opt/operator.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q4AzsYIN7WXbxLw7b:-L7QKbtAvUoFopY8TZTK:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/operator.go#L100)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't see this being used anywhere, since you're directly using `Ordering` in the `Limit` and `Offset` op private field.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/physical_props_factory.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-L7Q8o3rQI9TuFNXXSra:-L7QLYOlV9AnfxtDAlek:bj3yp3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/296642b1b09b169ebf77e703924520a5c466f535/pkg/sql/opt/xform/physical_props_factory.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I added `Equals` methods to PhysicalProps/Ordering and removed the `changed` flag, which makes the entire logic simpler, and allows a simple `switch` for everything.
</blockquote></details>

Yes, definitely better this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23735#-:-L7QPklzygMAzzSjJoBW:bnfp4nl)*

**Pull request merged**
