### PR TITLE
cli: add encode-uri command

### PR DESCRIPTION
**Pull request by stevendanna**
We expect that users may find distributing certs to all of their nodes for use in PCR a burden. To address this, we previously added support for "sslinline" URLs where the certs could be provided directly in the URL. However, such URLs are difficult to create. This command helps users create them more easily for example:

    ./cockroach encode-uri demo:demo20498@127.0.0.1:26257 --inline --ca-cert ~/.cockroach-demo/ca.crt

Epic: none

Release note (cli change): A new encode-uri utility has been added to make generating connection strings for use with physical replication easier.

### CODE REVIEW

**Review by alicia-l2 — COMMENTED** [review]
What is --demo referring to in the command? a demo cluster?

**Comment by dt** [comment]
The "demo:demo20498@127.0.0.1:26257" argument in the example is a connection string, where user `demo` with password `demo20498` is connecting to `127.0.0.1` on port `26257`.

**Review by dt — APPROVED** [review]

**Review by alicia-l2 — APPROVED** [review]

**Comment by stevendanna** [comment]
TFTRs. Going to merge, but let's discuss the defaults here before release.

bors r=dt,alicia-l2

**Comment by stevendanna** [comment]
bors r=dt,alicia-l2

**Pull request merged**
