### PR TITLE
distsqlrun: add countRows processor

### PR DESCRIPTION
**Pull request by jordanlewis**
This is a simple processor that counts the number of rows it receives.
It's about 10x faster than using the generalized aggregator for this
purpose.

Before:
```
BenchmarkCountRows-8         500           4012735 ns/op         199.37 MB/s
```

After:
```
BenchmarkCountRows-8        3000            549780 ns/op        1455.13 MB/s
```

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Wow, this speed-up is depressing. Any idea what's so inefficient in the general aggregator?

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-:-LFNskPT8A-DvB4qdmB4:b-83lbek)*

**Comment by jordanlewis** [comment]
It's a bunch of stuff. It's hard to tell via pprof, though. Seems to be death by ~a thousand~ several cuts. The normal implementation is pretty efficient and shortcuts when there are no columns, but there's still a bunch of work that gets done for no reason, lots of extra indexing into arrays, some copies, some spurious map lookups, that kind of thing.

I don't understand how this adds up to a 10x speedup though.

**Comment by jordanlewis** [comment]
Alfonso had the wise suggestion to make this slightly more general, to handle aggregates with no grouping, which is indeed a more general special case. I think I'll leave that for a separate PR, though - I have a feeling that doing so might erase these gains, and COUNT(*) is a classic special case that might well deserve a specialized implementation. Then again, this doesn't really affect overall query time too much that I can tell, since we're limited by our scan implementation.

**Comment by jordanlewis** [comment]
It seems like the slow stuff in the general aggregator is all of the indirection to aggregateFuncHolders. Maybe the pointer lookups there are what gets us. Perhaps we should be storing a slice of concrete aggregateFuncHolders rather than pointers to them. I can experiment with that also.

**Comment by solongordon** [comment]
😮
:lgtm:
Interested to see what comes out of your experiments. It feels like there must be a general lesson to be learned here.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-:-LFOM0901cBw5zEEuAdX:b14kag5)*

**Comment by jordanlewis** [comment]
Resurrected from the dead.

```
name                old time/op    new time/op    delta
Count/Cockroach-24    33.3ms ± 4%    29.5ms ± 1%  -11.56%  (p=0.000 n=9+10)

name                old alloc/op   new alloc/op   delta
Count/Cockroach-24    3.77MB ± 0%    3.76MB ± 0%   -0.22%  (p=0.000 n=10+9)

name                old allocs/op  new allocs/op  delta
Count/Cockroach-24     1.00k ± 1%     0.97k ± 1%   -2.47%  (p=0.000 n=9+8)
```

**Review by asubiotto — APPROVED** [review]
LGTM, I guess there was no particular reason this died?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-:-LNpxCf34UMD6Zx_yjkJ:bsnqgeh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/aggregator_test.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpwvjQD-rQSXmuwMmB:-LNpwvjQD-rQSXmuwMmC:b-frnnbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/aggregator_test.go#L466)):*
> ```Go
> 	const numCols = 1
> 	const numRows = 100000
> 	input := NewRepeatableRowSource(oneIntCol, makeIntRows(numRows, numCols))
> ```

Do you think you could use `ProcessorTest` here?
___
*[pkg/sql/distsqlrun/countrows.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpwPg37uga17vPSmUX:-LNpwPg4C-7cFBaaTWN0:bdwlse0) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/countrows.go#L52)):*
> ```Go
> 	ag := &countAggregator{}
> 	ag.input = input
> 	memMonitor := NewMonitor(ag.Ctx, flowCtx.EvalCtx.Mon, "aggregator-mem")
> ```

Why the memMonitor? You might be able to just pass nil.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/countrows.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpxo7a-BW6oleihOUc:-LNpxo7a-BW6oleihOUd:b404wdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/countrows.go#L55)):*
> ```Go
> 
> 	if sp := opentracing.SpanFromContext(flowCtx.EvalCtx.Ctx()); sp != nil && tracing.IsRecording(sp) {
> 		ag.input = NewInputStatCollector(input)
> ```

BTW, I think aggregatorBase now does stat collection/outputting for you. The downside is that the struct has a bunch of unnecessary field. Up to you.

**Review by andreimatei — COMMENTED** [review]
Is this PR being made obsolete by the work to use range stats for serving `count(1)` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-:-LNpyXjX59eNF46KeE9I:b-umzvvq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — COMMENTED** [review]
@andreimatei I would say yes and no, this will work in general regardless of things like # of column families and whatnot that won't be able to be served by the range stats work.

No particular reason this died, I just forgot about it / moved on to other things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-:-LNq0fOq6aQFGnOn3JLj:bwqfux7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/countrows.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpwPg37uga17vPSmUX:-LNq0t7W88Gs2Erlb-CT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/countrows.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why the memMonitor? You might be able to just pass nil.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/countrows.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpxo7a-BW6oleihOUc:-LNq0rCg8yBJ0i7ueXgR:b-ujue2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/countrows.go#L55)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

BTW, I think aggregatorBase now does stat collection/outputting for you. The downside is that the struct has a bunch of unnecessary field. Up to you.
</blockquote></details>

Yeah, I wanted to avoid the unnecessary fields.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/aggregator_test.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpwvjQD-rQSXmuwMmB:-LNqR83W7WiXKr7VKtei:bmqq5y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/aggregator_test.go#L466)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you think you could use `ProcessorTest` here?
</blockquote></details>

In a benchmark? Is it appropriate to use in a benchmark?

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/aggregator_test.go, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26828#-LNpwvjQD-rQSXmuwMmB:-LNqn8s9BImw2Ig4rOxz:b-hsfda1) ([raw file](https://github.com/cockroachdb/cockroach/blob/da36c3d4b44d4edab05ac2dca4d9e51eaadbbe03/pkg/sql/distsqlrun/aggregator_test.go#L466)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

In a benchmark? Is it appropriate to use in a benchmark?
</blockquote></details>

Nope, it isn't, sorry. We need to allow the caller to specify the row source they want instantiated and have a reset method of some sort. Might be worth it but not in this PR.

**Pull request merged**
