### PR TITLE
jobs: add username column to system.jobs

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change introduces an upgrade to add the `username` column to
`system.jobs` as a nullable string. This change also adds another
upgrade to backfill it.

With this change, new jobs being inserted into the jobs table by
the jobs registry will populate the `username` column.

To make migrations easier, this change adds a new builtin,
`crdb_internal.job_payload_user`, which can be used to determine
the user from a jobs payload.

Release note: None
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-19709
Informs: https://github.com/cockroachdb/cockroach/issues/92261

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
Would it be easy for you to add a `user_id` column instead of (or less preferably, in addition to) a username column? I'm currently working on writing migrations for every system table that has username cols to also have user_id cols so I'd greatly appreciate it if you were able to use user IDs instead of usernames from the get-go. The user IDs can be found in the `user_id` column in `system.users` and you can query it with something like `SELECT user_id FROM system.users WHERE username = $1`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93797#-:-NJSAzP1BRA1yHOmb8zZ:b-v1rhzv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by Storages235** [comment]
Heres a store that might have something you like :https://latestarticlesstore.creator-spring.com and if you have any ideas contact me at this email: storages235@gmail.com.

**Comment by Storages235** [comment]
Heres a site that has good job connections : https://latestarticles.store/?s=+jobs+

**Comment by jayshrivastava** [comment]
Discarding this PR. It doesn't solve as many problems as it creates.

**Pull request closed without merging**
