### PR TITLE
log,kvserver: hand redacted KV traces to tenants

### PR DESCRIPTION
**Pull request by tbg**
Make traces generally redactable. Before returning to a tenant, redact them.
See individual commits for details.

- log,tracing: make traces redactable
- kvserver: redact tenant-bound trace recordings
- kvtenantccl: test that tenants can't see KV-level trace messages

Touches https://github.com/cockroachdb/cockroach/issues/58610.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@knz could I get a review of the approach? If this is "fine" then I would shoot for polishing this instead of https://github.com/cockroachdb/cockroach/pull/70406.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkClLfg-R5t8cKGJelS):*
I'm curious if this comes with a performance hit. Or, perhaps a perf win? Maybe run `BenchmarkTracing` with a new `ForceVerbose` flag or with verbose tracing turned on in some other way?
___
*[pkg/util/log/trace.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkEeJBE87c6bc5nLN:-MkCkEeJBE87c6bc5nLO:b32x1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L117)):*
> ```Go
> 		buf.Printf("%s:%d ", redact.Safe(entry.file), redact.Safe(entry.line))
> 	} else {
> 		panic("x")
> ```

xx
___
*[pkg/util/log/trace.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkt2-8bUJbXdpBLsh:-MkCkt2-8bUJbXdpBLsi:bs44mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L202)):*
> ```Go
> 		channel.DEV,   /* unused for trace events */
> 		1,             /* depth */
> 		true,          /* redactable */
> ```

would you mind commenting on `makeUnstructuredEntry` what the semantics of `redactable` are? 
I'm confused about how the `true` here jives with the `TODO` you've added above.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkClLfg-R5t8cKGJelS):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm curious if this comes with a performance hit. Or, perhaps a perf win? Maybe run `BenchmarkTracing` with a new `ForceVerbose` flag or with verbose tracing turned on in some other way?
</blockquote></details>

I sympathize with the performance problem aspect, but we're possibly leaking data in Serverless and only after that is fixed would I support someone looking into the performance impact. The perf impact is zero in regular operations since verbose tracing is not enabled.
___
*[pkg/util/log/trace.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkEeJBE87c6bc5nLN:-MkCm_wo4gXKZs9nhsHl:b-4ka12d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L117)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

xx
</blockquote></details>

xoxo

Will remove when I actually continue this PR after Raphael has had his say.
___
*[pkg/util/log/trace.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkt2-8bUJbXdpBLsh:-MkCm80j20ccIpHawUAQ:b2xc6ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L202)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would you mind commenting on `makeUnstructuredEntry` what the semantics of `redactable` are? 
I'm confused about how the `true` here jives with the `TODO` you've added above.
</blockquote></details>

The TODO says we have to prevent stuff like `Event(ctx, userPassword.String())`, because I'm passing `msg` as a `format` string into the machinery. For the `XXXf` methods we have linters that make sure that you only pass const strings as the `format` parameter. We just need to do that here too (or better yet, remove the method).

The `redactable` parameter "just" makes the entry contain a `RedactedString`, which is basically `redact.Sprint(format, args...)`. Here, there are no args and `format := msg`.

**Review by knz — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/server/node.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDApHSBtoitVWJZrH5:-MkDApHSBtoitVWJZrH6:b-vcbcf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node.go#L1101)):*
> ```Go
> 			// Tenants get a redacted recording, i.e. with anything
> 			// sensitive stripped out of the verbose messages. However,
> 			// structured payloads stay untouched.
> ```

We need to explain in the commit message + PR description that we'll want to audit all the structured payloads (and set up a stringent review process for new structured payloads in the future), to ensure they don't include sensitive information.
___
*[pkg/server/node_tenant.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDB4_mBT0gAr39LfU-:-MkDB4_mBT0gAr39LfU0:b-7ys9ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node_tenant.go#L36)):*
> ```Go
> 					// We don't have any of these fields, but let's not take any
> 					// chances (our dependencies might slip them in).
> 					field.Value = string(redact.RedactedMarker())
> ```

You could assign that string just once out of then loop, to prevent a bytearray-to-string conversion on each iteration.
___
*[pkg/server/node_tenant.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDBHwQB0oviGJarXEE:-MkDBHwQB0oviGJarXEF:bxb3zac) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node_tenant.go#L39)):*
> ```Go
> 					continue
> 				}
> 				field.Value = string(redact.RedactableString(field.Value).Redact())
> ```

With the proto change I suggested elsewhere, the cast becomes unnecessary.
___
*[pkg/util/log/trace.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDAIUrEpfTQVIwE4m2:-MkDAIUrEpfTQVIwE4m3:bnxg5jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L108)):*
> ```Go
> // information in them will not be surfaced.
> func eventInternal(sp *tracing.Span, el *ctxEventLog, isErr bool, entry logEntry) {
> 	var buf redact.StringBuilder
> ```

if you were to implement a `SafeFormat` on `logEntry` that emits the verbose trace string using a safeprinter, you could give that logEntry to `sp.Record`, and the `redact.Sprint` call inside that would "do the right thing" and avoid allocating the intermediate StringBuilder here.
___
*[pkg/util/log/trace.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD9o82DwtiePaz87_Q:-MkD9o82DwtiePaz87_R:b-o4zpvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L148)):*
> ```Go
> 
> 	if sp != nil {
> 		sp.Recordf("%s", msg)
> ```

`Record` still works, unless you were extra keen to elide a call.
___
*[pkg/util/tracing/crdbspan.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8aa32f-BGCA-xFJZ:-MkD8aa4EZDuzVnBLuOq:b-tn96e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/crdbspan.go#L308)):*
> ```Go
> 		Time: now,
> 		Fields: []tracingpb.LogRecord_Field{
> 			{Key: tracingpb.LogMessageField, Value: string(msg)},
> ```

1. you could put `(gogoproto.customtype) = "github.com/cockroachdb/redact.RedactableString"` in that proto. We do this elsewhere already.

2. you need a new boolean field in that proto and set it to true here. When receiving a record, and the boolean is false, you know it's coming from a node that doesn't know about redaction markers and you can consider the entire string as unsafe.
___
*[pkg/util/tracing/span_inner.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8pH3Dyi_4yeTpOUt:-MkD8pH3Dyi_4yeTpOUu:b-vbwdkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/span_inner.go#L234)):*
> ```Go
> 	if s.ot.shadowSpan != nil {
> 		// TODO(obs-inf): depending on the situation it may be more appropriate to
> 		// redact the string here.
> ```

Could to mention this TODO in the commit message and the PR description too.

**Comment by tbg** [comment]
Thanks for the review Raphael, but allow me a meta question, any concern about the approach and getting it fixed up & reviewed & merged by the end of next week? I want to avoid spending a bunch of time on this PR since it addresses a Serverless release blocker. If we're unsure, I will have to go with https://github.com/cockroachdb/cockroach/pull/70406, but I'd prefer the approach at hand.

**Comment by knz** [comment]
The approach is fine, but you _really_ need that boolean in the proto to not turn a sensitive string from a previous version node into a safe string inadvertently.

**Review by tbg — COMMENTED** [review]
I'm sure this will find some way to fail CI, but this is RFAL.

> Dismissed @andreimatei and @knz from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-:-MkJLP6CEIJ8C2-4Pmow:b5lvz72)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @tbg)

___
*[pkg/server/node.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDApHSBtoitVWJZrH5:-MkJJ-xEERwK5QYF4rvB:bmr9thq) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node.go#L1101)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We need to explain in the commit message + PR description that we'll want to audit all the structured payloads (and set up a stringent review process for new structured payloads in the future), to ensure they don't include sensitive information.
</blockquote></details>

I will get the ball rolling a bit more proactively than this. I'm about to do an ad-hoc audit of the current payloads and I'll dish out action items to the owners in the form of Github issues.
___
*[pkg/server/node_tenant.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDB4_mBT0gAr39LfU-:-MkJ10sj9s4U2FbOldZ8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node_tenant.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You could assign that string just once out of then loop, to prevent a bytearray-to-string conversion on each iteration.
</blockquote></details>

Done.
___
*[pkg/util/log/trace.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkEeJBE87c6bc5nLN:-MkJ9w_F5HwqC2qkgMQm:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L117)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

xoxo

Will remove when I actually continue this PR after Raphael has had his say.
</blockquote></details>

Removed.
___
*[pkg/util/log/trace.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkCkt2-8bUJbXdpBLsh:-MkJAQUxAss32HD_rH4u:by4iua0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/log/trace.go#L202)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The TODO says we have to prevent stuff like `Event(ctx, userPassword.String())`, because I'm passing `msg` as a `format` string into the machinery. For the `XXXf` methods we have linters that make sure that you only pass const strings as the `format` parameter. We just need to do that here too (or better yet, remove the method).

The `redactable` parameter "just" makes the entry contain a `RedactedString`, which is basically `redact.Sprint(format, args...)`. Here, there are no args and `format := msg`.
</blockquote></details>

I checked the lint and it's already enforced: https://github.com/cockroachdb/cockroach/blob/6d024aef059995f8b127c98c72110c32e19a50fc/pkg/testutils/lint/passes/fmtsafe/functions.go#L48
Added `(*Span).Record{,f}` to the linter as well, so now we're good.
___
*[pkg/util/tracing/crdbspan.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8aa32f-BGCA-xFJZ:-MkJ7ooD5y862kuWQpc9:b-8skru9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/crdbspan.go#L308)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1. you could put `(gogoproto.customtype) = "github.com/cockroachdb/redact.RedactableString"` in that proto. We do this elsewhere already.

2. you need a new boolean field in that proto and set it to true here. When receiving a record, and the boolean is false, you know it's coming from a node that doesn't know about redaction markers and you can consider the entire string as unsafe.
</blockquote></details>

1. thanks, nice simplification.
2. I would like to avoid this if possible and didn't think this was necessary. The status quo is that information got through verbatim. If now in mixed binary scenarios we treat some non-redactable strings as redactable (i.e. call `Redact()` on them), they will be preserved. That's fine too; it was the status quo after all. Or are you worried about causing panics in the redaction code if users somehow slip imbalanced redaction markers into the trace messages? In that case I would still rather wrap the one call to `.Redact()` in a `defer recover` and be done with it. Also, the one user of this is Serverless (since the `Redact()` call requires non-system-tenant) plus we do enable tracing globally in our mixed version tests (https://github.com/cockroachdb/cockroach/blob/fbfcded982530a9b37af3f2c843da2769f927025/pkg/cmd/roachtest/tests/versionupgrade.go#L195) so there aren't any obvious crashes here if this passes as I assume it does. If you're not convinced, I will add the bool. It might annoy Andrei (https://github.com/cockroachdb/cockroach/pull/70502) but he will manage.
___
*[pkg/util/tracing/span_inner.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8pH3Dyi_4yeTpOUt:-MkJ7jkhAacNKJw-hBMW:bs551kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/span_inner.go#L234)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Could to mention this TODO in the commit message and the PR description too.
</blockquote></details>

I elaborated on this in https://github.com/cockroachdb/cockroach/issues/58610#issuecomment-926093901 and left a link to that comment here.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 13 files at r4, 14 of 14 files at r5, 2 of 7 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager_test.go, line 1026 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbGpF4fbm0CRGeMxn:-MkMbGpG3pTHaccld5iS:b-394mhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/kv/kvserver/concurrency/concurrency_manager_test.go#L1026)):*
> ```Go
> 						continue
> 					}
> 					logs = append(logs, logRecord{
> ```

maybe logRecord.value could be a redactable string too.
___
*[pkg/server/node.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDApHSBtoitVWJZrH5:-MkMbK-Y9kX7Mc4DCssL:b-wyqa74) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node.go#L1101)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I will get the ball rolling a bit more proactively than this. I'm about to do an ad-hoc audit of the current payloads and I'll dish out action items to the owners in the form of Github issues.
</blockquote></details>

FWIW, eventpb uses struct field tag annotations to indicate which fields are safe for inclusion in logs. maybe we can repurpose that mechanism.
___
*[pkg/server/status.go, line 669 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbbSu4Zh2Et4GGjTW:-MkMbbSv38RM_eWWMVjQ:bioa87m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/server/status.go#L669)):*
> ```Go
> 			}
> 			if len(entry.Fields) == 1 {
> 				event.Message = entry.Fields[0].Value.StripMarkers()
> ```

Maybe add a TODO in the serverpb proto to indicate we would like to be more clever here.
___
*[pkg/util/log/channels.go, line 56 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbmW47FJpIUj6dAb3:-MkMbmW47FJpIUj6dAb4:b-svkifh) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/channels.go#L56)):*
> ```Go
> 		depth+1, true /* redactable */, format, args...)
> 	if sp, el, ok := getSpanOrEventLog(ctx); ok {
> 		eventInternal(sp, el, sev >= severity.ERROR, &entry)
> ```

could you double check whether the move to the heap happens under the conditional, or at the time the object is defined above?

If the latter, we'll likely want to move most of the logging function to take this by reference, and use a sync.Pool like the log.buffer.
___
*[pkg/util/log/event_log.go, line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbwkO-tVtQVULjXTL:-MkMbwkO-tVtQVULjXTM:b-z3itza) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/event_log.go#L42)):*
> ```Go
> 
> 	if sp, el, ok := getSpanOrEventLog(ctx); ok {
> 		eventInternal(sp, el, (entry.sev >= severity.ERROR), &entry)
> ```

ditto alloc
___
*[pkg/util/log/trace.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMc6on39S1gVu0NDRB:-MkMc6on39S1gVu0NDRC:b-1gn876) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/trace.go#L116)):*
> ```Go
> 		_ = isErr
> 	} else {
> 		el.Lock()
> ```

Not your pr, but this would like a closure an a `defer el.Unlock()`, in case the print code panics. defers are cheap now.
___
*[pkg/util/tracing/crdbspan.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8aa32f-BGCA-xFJZ:-MkMcNdk0KQkCzidqbhX:bq81112) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/crdbspan.go#L308)):*
> Or are you worried about causing panics in the redaction code if users somehow slip imbalanced redaction markers into the trace messages?

It's not about panics. It's about pretty-printed database keys/values that contain an unbalanced redaction marker. You can't catch this with a defer/recover, so you need to redact always in that case.

Also, in a mixed-version cluster, with one node with your patch and one without, there will be unescaped string coming from the previous-version node.

(This is incidentally _exactly_ the reason why we even carry that "redactable" boolean in the output log format, so that we know to _not_ interpret redaction marker in logging output from nodes that don't know about them, in case they are embedded in a message as part of some string value)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/util/tracing/crdbspan.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8aa32f-BGCA-xFJZ:-MkMgtZQ3BS1yoQuhqAs:bykz86a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/crdbspan.go#L308)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> Or are you worried about causing panics in the redaction code if users somehow slip imbalanced redaction markers into the trace messages?

It's not about panics. It's about pretty-printed database keys/values that contain an unbalanced redaction marker. You can't catch this with a defer/recover, so you need to redact always in that case.

Also, in a mixed-version cluster, with one node with your patch and one without, there will be unescaped string coming from the previous-version node.

(This is incidentally _exactly_ the reason why we even carry that "redactable" boolean in the output log format, so that we know to _not_ interpret redaction marker in logging output from nodes that don't know about them, in case they are embedded in a message as part of some string value)
</blockquote></details>

Alternatively you could create _another_ string field. That would be clearer and would clarify what happens cross-version.

**Review by tbg — COMMENTED** [review]
TFTR, updated, PTAL.

> Dismissed @andreimatei and @knz from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-:-MkN3OJyBImXVNL-LUMD:bwto1fd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager_test.go, line 1026 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbGpF4fbm0CRGeMxn:-MkMq-AJ0NMWrJ3Bqh4U:bd6da3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/kv/kvserver/concurrency/concurrency_manager_test.go#L1026)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe logRecord.value could be a redactable string too.
</blockquote></details>

Since this is addressing a release blocker and will need a backport, I will gently push back on making any additional non-essential changes at this point.
___
*[pkg/server/node.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkDApHSBtoitVWJZrH5:-MkMq6eh7LKSy5J3uBpA:b-5yssm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/29342fa59dab7be34c0af80ea5bffedb36925ffc/pkg/server/node.go#L1101)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

FWIW, eventpb uses struct field tag annotations to indicate which fields are safe for inclusion in logs. maybe we can repurpose that mechanism.
</blockquote></details>

There are a few callers that use `types.String`, so it won't be as easy. I will go pester the owners after this PR lands.
___
*[pkg/server/status.go, line 669 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbbSu4Zh2Et4GGjTW:-MkMqJB70MyVp2CyCzOa:b-3hh9my) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/server/status.go#L669)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe add a TODO in the serverpb proto to indicate we would like to be more clever here.
</blockquote></details>

This is consumed by system-level tools (enqueue range, allocator dry run), so redaction isn't useful here. What would be useful is to have a better framework around redactability across RPC boundaries (i.e. one has to opt out of redactability explicitly somehow), but this won't be achieved by a TODO - I filed https://github.com/cockroachdb/cockroach/issues/70679 instead.
___
*[pkg/util/log/channels.go, line 56 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbmW47FJpIUj6dAb3:-MkMsoMu-2PA6P-s3iar:bk90dfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/channels.go#L56)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

could you double check whether the move to the heap happens under the conditional, or at the time the object is defined above?

If the latter, we'll likely want to move most of the logging function to take this by reference, and use a sync.Pool like the log.buffer.
</blockquote></details>

Good call, it does escape. I don't want to get into the weeds to much in this PR, so using the old trick that allocs only when the branch is taken. It works:

```
./scripts/goescape ./pkg/util/log/channels.go
./channels.go:57:3: moved to heap: heapEntry
./channels.go:47:5: ch escapes to heap
./channels.go:70:39: func literal escapes to heap
./channels.go:79:57: sev.String() escapes to heap
./channels.go:80:19: strings.Replace(FormatWithContextTags(ctx, format, args...), "\n", "\n* ", -1) escapes to heap
```
___
*[pkg/util/log/event_log.go, line 42 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMbwkO-tVtQVULjXTL:-MkMtd9BElrX0eTXPeoo:b4t8ku8) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/event_log.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto alloc
</blockquote></details>

Fixed in the same way.
___
*[pkg/util/log/trace.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkMc6on39S1gVu0NDRB:-MkMxVQsBBcKTE2pIVMt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64816fbf04c3877d3760cfcfb446514266c27b68/pkg/util/log/trace.go#L116)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not your pr, but this would like a closure an a `defer el.Unlock()`, in case the print code panics. defers are cheap now.
</blockquote></details>

Done.
___
*[pkg/util/tracing/crdbspan.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70562#-MkD8aa32f-BGCA-xFJZ:-MkN-rfy7N3lml0boWp6:baj97b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4226c574a6eabdd5ee57dfd80d9dd75d5b566955/pkg/util/tracing/crdbspan.go#L308)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Alternatively you could create _another_ string field. That would be clearer and would clarify what happens cross-version.
</blockquote></details>

Thanks for prodding me, I still think this would work fine without the bool (degraded experience is fine, after all fully stripping everything is the most degraded you can make it), but it's better to just play by the book and to know that we are safe from weird interactions.

**Comment by knz** [comment]
Ok this looks good.

Can you help me double check something: are there places where a recording is merged into another one, e.g. during trace repatriation? In that case, we need to be sure that no non-redactable strings are blindly appended to a recording that has the boolean set.

**Comment by tbg** [comment]
No, I don't think recordings are merged. A "Recording" is really a `[]RecordedSpan` so the "merging" is appending to a slice. I verified this via my IDE. The only write to the `Logs` field is here:

https://github.com/cockroachdb/cockroach/blob/b1abec735a6bcf1b0fba0f7b8b1b19021ef14d43/pkg/util/tracing/crdbspan.go#L473-L479

so nobody is doing `s.Logs = append(s.Logs, someOtherStuff...)` anywhere and this also doesn't fit into how we handle recordings.

**Review by knz — APPROVED** [review]

**Comment by tbg** [comment]
bors r=knz

**Comment by tbg** [comment]
blathers backport 21.2

**Pull request merged**
