### PR TITLE
spanconfig: integrate SpanConfigBounds with the Store and KVSubscriber

### LINKED ISSUE #99689: spanconfig: integrate SpanConfigBounds with the KVSubscriber
**Describe the problem**

With https://github.com/cockroachdb/cockroach/pull/96692 landing, we should now be able to `Clamp` span configs before returning them above the `KVSubscriber`/`spanconfig.Store` interfaces. 

Jira issue: CRDB-26025
Epic: CRDB-23559

### PR DESCRIPTION
**Pull request by arulajmani**
This patch integrates `SpanConfigBounds` with the `KVSubscriber` and
`spanconfig.Store`. The `spanconfig.Store` used by the `KVSubscriber`
now has a handle to the global tenant capability state. It uses this to
clamp any secondary tenant span configs that are not in conformance
before returning them.

By default, clamping of secondary tenant span configurations is turned
off. It can be enabled using the `spanconfig.bounds.enabled` cluster
setting. The setting is hidden.

Fixes: https://github.com/cockroachdb/cockroach/issues/99689
Informs #99911
Epic: CRDB-16706

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

The nit can be done later. I do think it's better practice, but I leave it up to you. Nice work!

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 22 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99699#-:-NRcPe1nDHytH-GL-Uaq:b-96yqd8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/spanconfig/spanconfigstore/store.go` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/99699#-NRcP-aE9lcK1sVZ_aCl:-NRcP-aE9lcK1sVZ_aCm:bova3m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd2928cd800b6929e9d03449d10990e5186d9cee/pkg/spanconfig/spanconfigstore/store.go#L92)):*
> ```Go
> 
> 	// capabilitiesReader provides a handle to the global tenant capability state.
> 	capabilitiesReader tenantcapabilities.Reader
> ```

nit: I think life will be better here if you narrow the interface and make an adapter. Like, don't depend directly on `tenantcapabilities.Reader`, but rather extract the logic you added into `getSpanConfigForKeyRLocked` behind another interface defined in this package. It'll make testing the logic here much more direct. The adapter between the two interfaces will be just what you have.

**Review by arulajmani — COMMENTED** [review]
This was a solid improvement, thanks for the suggestion. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99699#-:-NRjBpot6x_qJ-9foX_o:b-pob0gf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99699#-:-NRjDCCYCBw_hXhqNR0E:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
TFTR! 

bors r=ajwerner

**Pull request merged**
