### PR TITLE
sql: use SQL views to implement pg_catalog views

### PR DESCRIPTION
**Pull request by knz**
This aims to support the resolution of  #34776.

First commit from #34857.

Some items in PostgreSQL's `pg_catalog` schema are real tables; others
are actually views. For example, `pg_tables` is a view over
`pg_class`.

Now that CockroachDB supports views in virtual schemas, we should do
the same: it enables better optimizations and join eliminations for
introspection queries.

Unfortunately, this is (still) difficult to do because the content of
vtables is dependent on the database on which they are applied. For
example, `d1.pg_catalog.pg_tables` should only render tables in `d1`,
and `d2.pg_catalog.pg_tables` should only render tables in
d2. Conceptually, We need a different instance of the view in every
database. However, currently the vtable/vview objects are shared
between all databases.

This makes this patch (as-is) not-work. It needs to be extended before
the approach can be generalized.

### CODE REVIEW

**Comment by knz** [comment]
@RaduBerinde do you confirm that exposing `pg_catalog` views as actual views, assuming that the underlying tables (eg `pg_class`) are requipped with suitable index descriptors, will make things better or CBO?

**Comment by RaduBerinde** [comment]
It should, it would give CBO visibility into the entire query and into things like column uniqueness info on the underlying table.

**Comment by knz** [comment]
Excellent.

Now on to the next investigation -- I have created the proper unique index definitions on `pg_class`, but they do not get stored in the descriptors.

**Comment by RaduBerinde** [comment]
Actually, I just realized the indexes part will require a bit of work in the optimizer as well - see `logicalPropsBuilder.buildVirtualScanProps`, it would need the FuncDeps part from `buildScanProps`.

**Comment by knz** [comment]
@jordanlewis  @RaduBerinde I still think this PR is going in a good direction but back when I started it was still a bit too large for me to chew on. Do you think this may be a good starter project?

**Comment by knz** [comment]
@RaduBerinde @jordanlewis  I think this PR has been superseded by recent work, should I close it?

**Comment by jordanlewis** [comment]
Probably! :)

**Comment by knz** [comment]
thanks!

**Pull request closed without merging**
