### PR TITLE
sql/gcjob: deal with a missing system config span

### PR DESCRIPTION
**Pull request by ajwerner**
This can cause panics if not handled. It must be quite rare that the jobs
subsystem gets going before we have a system config, but clearly it's
possible.

The contract on the SystemConfigProvider is that it can return nil. This case has to be
handled. https://github.com/cockroachdb/cockroach/blob/8878715577f4b8669da2cdaa57f6a0070b784998/pkg/config/provider.go#L16-L17

See https://teamcityartifacts.crdb.io/presignedTokenAuth/158ce0ab-b5b6-4cc1-9f1b-672d20d0a56e/repository/download/Cockroach_Ci_Tests_LocalRoachtest/5545173:id/acceptance/version-upgrade/run_1/artifacts.zip!/logs/2.unredacted/cockroach-stderr.05b0f904debc.roach.2022-06-23T14_53_26Z.103197.log

Release note (bug fix): Fixed a bug where a panic could occur during server
startup when restarting a node which is running a GC job.

### CODE REVIEW

**Comment by ajwerner** [comment]
I'm all ears on how to test this.

**Comment by ajwerner** [comment]
Alright, I wrote a test. It was somewhat painful.

**Comment by ajwerner** [comment]
It did, however, reproduce the crash.

**Comment by ajwerner** [comment]
Maybe I could get @arulajmani to give this a review?

**Comment by ajwerner** [comment]
RFAL

**Comment by ajwerner** [comment]
@RichardJCai maybe you have interest? I think this is worse now, or, rather, I've seen the test failing frequently lately and maybe it's because we don't have the gossip value ever.

**Review by arulajmani — APPROVED** [review]
:lgtm:

Sorry for not replying earlier, I looked through this but didn't publish given CI war red. 

> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83280#-:-N5MCn1m6acYqxgFYG4_:b-ll7khi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/gcjob_test/gc_job_test.go` line 610 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83280#-N5_cZTz1yDWaKLIqZuL:-N5_cZTz1yDWaKLIqZuM:bzg4jsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9915139c6aa473fec3bb2c0c4cabf8f68fda9108/pkg/sql/gcjob_test/gc_job_test.go#L610)):*
> ```Go
> 	// once for the job itself.
> 	testutils.SucceedsSoon(t, func() error {
> 		if n := provider.numNotifyees(); n == 0 {
> ```

nit: `n != 1`

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83280#-:-N5_lpAA7WIaeP8cDF-N:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/sql/gcjob_test/gc_job_test.go` line 610 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83280#-N5_cZTz1yDWaKLIqZuL:-N5_lnENCoze4OGWuSsr:bgx00ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/9915139c6aa473fec3bb2c0c4cabf8f68fda9108/pkg/sql/gcjob_test/gc_job_test.go#L610)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: `n != 1`
</blockquote></details>

Doesn't feel worth a CI cycle.

**Pull request merged**
