### PR TITLE
colcontainer: use explicit copy for nulls instead of replacing the bitmap

### PR DESCRIPTION
**Pull request by yuzefovich**
Issue #43964 outlines a possible memory corruption scenario that can
occur if we reset either the data or the nulls in the region to be
deserialized. Originally, to go around that we were creating new vectors
whenever a new region of memory is deserialized from. Later, we removed
the vector resetting logic but kept the null resetting behavior in #47705.
This commit finishes the job by never using the deserialized region
directly and always performing a copy (for nulls). This behavior seems
less error-prone to me (this would have prevented recently discovered
bug).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think I actually like this approach more. Probably it wouldn't be backportable since it is more of an invasive change then the first commit. Benchmarks incoming.

**Comment by yuzefovich** [comment]
The benchmarks look pretty [good](https://gist.github.com/yuzefovich/fd17d35d3dd2461e836c06ddb40d1d09).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62644#-:-MX8lxy567lq6XkPGaH_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
