### PR TITLE
logictest: ensure generated ccl build files have the right tags

### PR DESCRIPTION
**Pull request by healthy-pod**
Release note: None
Epic: none

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]
Thanks for fixing it!

**Comment by healthy-pod** [comment]
bors r=andyyang890

**Comment by knz** [comment]
should this be backported?

**Comment by andyyang890** [comment]
> should this be backported?

I'm gonna guess no since https://github.com/cockroachdb/cockroach/pull/98834 was not backported.

**Pull request merged**
