### PR TITLE
base: decrease store liveness durations

### LINKED ISSUE #133613: storeliveness: tune heartbeat and liveness intervals
Part of https://github.com/cockroachdb/cockroach/issues/133612.

The store liveness heartbeat and liveness intervals are currently set to the same values as they are for expiration-based leases and for node liveness records. This intuitively feels correct, but it's actually a problem, because raft is built on top of store liveness. As a result, raft's leader election and its randomized jitter adds to store liveness's failover time, instead of being hidden by it.

Luckily, store liveness was built to scale, so we likely have room to make these intervals more aggressive and align them with the existing raft configuration (as opposed to the existing lease configuration).

For example, we could set the heartbeat interval to 1s and the liveness interval to 3s. Coupled with https://github.com/cockroachdb/cockroach/issues/133576, we could realistically push failover time down to around 5s.

Jira issue: CRDB-43707

Epic CRDB-42947

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, store liveness used a heartbeat interval and support duration of 3s and 6s, respectively. This matched the lease extension and lease duration, respectively. However, these values were not well aligned with Raft's election timeout (4s) and jitter (up to 2s), so when a follower had to campaign after withdrawing support from the leader, the store liveness durations added up to the Raft timeout and jitter, instead of being subsumed by them.

This commit reduces the store liveness heartbeat interval and support duration to 1s and 3s, respectively.

Fixes: [#133613](https://github.com/cockroachdb/cockroach/issues/133613)

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137608#-:-OEKYu9z2EBZ66BW2XF0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137608#-OEKYJ4FA9wZeA2sdPyS:-OEKYJ4FA9wZeA2sdPyT:b-gx8g4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c81e148a09b7b75a669318b61b60b192ae75c4/pkg/kv/kvserver/storeliveness/requester_state.go#L336)):*
> ```Go
> 
> // updateMaxRequested forwards the current MaxRequested timestamp to now +
> // interval, where now is the node's clock timestamp and support duration is the
> ```

nit: interval is the support duration or, better yet, "now + support duration, where now is the node's clock timestamp".

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 11 files at r1, 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137608#-:-OEQR19H-8c-Lv3Q_Xml:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miraradeva)

___
*[`pkg/base/testdata/raft_config_recovery` line 3 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137608#-OEQQspz5favezUtQh4u:-OEQQspz5favezUtQh4v:b-l5o97z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4244b971c4922bf8ad57fc610cbc97d9436c346/pkg/base/testdata/raft_config_recovery#L3)):*
> ```
> # Any changes in this result should be copied to the comment on
> # defaultRangeLeaseRaftElectionTimeoutMultiplier, and the corresponding
> # reasoning should be adjusted.
> ```

We'll want to update the comment that this is referencing as well.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137608)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten)

___
*[`pkg/base/testdata/raft_config_recovery` line 3 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137608#-OEQQspz5favezUtQh4u:-OEQ_n0U8jg1k8tdges9:bb0mdnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4244b971c4922bf8ad57fc610cbc97d9436c346/pkg/base/testdata/raft_config_recovery#L3)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We'll want to update the comment that this is referencing as well.
</blockquote></details>

Looks like `defaultRangeLeaseRaftElectionTimeoutMultiplier` doesn't exist as of https://github.com/cockroachdb/cockroach/commit/40cb0758f710004b4626e55d22287336e8899d2a, so I updated the comment to point to the right place (which is `defaultRangeLeaseDuration`). I had already updated that one.

**Comment by miraradeva** [comment]
The CI failure (`TestRaftCheckQuorum`) looks suspicious. I'll try to repro.

**Comment by miraradeva** [comment]
The CI extended failure is `TestLogGrowthWhenRefreshingPendingCommands`, which should be fixed on master. Will rebase.

**Comment by miraradeva** [comment]
CI is finally green. TFTRs!

bors r+

**Pull request merged**
