### PR TITLE
storage: Improve a couple log messages and variable names

### PR DESCRIPTION
**Pull request by a-robinson**
Seen while doing some log spelunking earlier this afternoon.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14210)

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm: mod the fatal

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_command.go, line 3312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210#-KfNuVMOZm7yFjEzXq7l:-KfNuVMOZm7yFjEzXq7m:bsyerkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffc1f9731697ae34c9aa15c7583dc8715d55631/pkg/storage/replica_command.go#L3312)):*
> ```Go
> 			return err
> 		}
> 		log.Fatalf(ctx, "change replicas (%v %s): read existing descriptor %+v",
> ```

Fatal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210#-:-KfNudRV8aHeUachfQ7f:brq6aqw)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_command.go, line 3312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210#-KfNuVMOZm7yFjEzXq7l:-KfNuy1m6-9CUygIpDs7:bw8vh9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffc1f9731697ae34c9aa15c7583dc8715d55631/pkg/storage/replica_command.go#L3312)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Fatal?
</blockquote></details>

Hah, thanks for catching that! I had switched it to fatal to trigger it by running the tests to make sure the name formatted properly.

And it does:

```
change replicas (ADD_REPLICA {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"b" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210)*

**Comment by BramGruneir** [comment]
Reviewed 2 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_command.go, line 3312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210#-KfNuVMOZm7yFjEzXq7l:-KfNwKKvT-vIDz-zmxHI:b-82anhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffc1f9731697ae34c9aa15c7583dc8715d55631/pkg/storage/replica_command.go#L3312)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Hah, thanks for catching that! I had switched it to fatal to trigger it by running the tests to make sure the name formatted properly.

And it does:

```
change replicas (ADD_REPLICA {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"b" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2
```
</blockquote></details>

hmm... while your in there, might as well change the oldDesc to %s so it will have the proper formatting.  (I think).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210)*

**Comment by a-robinson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_command.go, line 3312 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210#-KfNuVMOZm7yFjEzXq7l:-KfNy-nLzI6fJe4rWp1h:b-bxd9vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffc1f9731697ae34c9aa15c7583dc8715d55631/pkg/storage/replica_command.go#L3312)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

hmm... while your in there, might as well change the oldDesc to %s so it will have the proper formatting.  (I think).
</blockquote></details>

It prints out the same after the change, but sure:

```
change replicas (ADD_REPLICA {2 2 2}): read existing descriptor range_id:1 start_key:"" end_key:"b" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14210)*

**Pull request merged**
