### PR TITLE
docs/tla-plus: add timestamp refreshes to ParallelCommits spec

### PR DESCRIPTION
**Pull request by nvb**
This commit adds transaction timestamp refreshes to the PlusCal model
for parallel commits. This allows the committing transaction to bump
its timestamp without a required epoch bump.

This completes the parallel commits formal specification.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
You added some inline commentary which is great, but add a nice fat box comment at the top that explains at a high level what you're modeling (and sort of how it corresponds to our code).

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-:-Lf4zwFX6HBCwgjhbQjf:b-28k5iz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf5-s1r8wvypgY8eAFA:-Lf5-s1r8wvypgY8eAFB:bd95igk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L11)):*
> ```TLA
> variables
>   record = [status |-> "pending", epoch |-> 0, ts |-> 0];
>   intent_writes = [k \in KEYS |-> <<0, 0>>];
> ```

This might be a little clearer with a struct instead of a tuple, i.e. `\in [ key: KEYS, ts: 0..MAX_ATTEMPTS ]`
___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf53s-F7U7a3K1tDXAr:-Lf53s-F7U7a3K1tDXAs:b-2bsoe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L222)):*
> ```TLA
>             assert record.epoch = prevent_epoch;
>             assert record.ts    = prevent_ts;
>             
> ```

Weird spaces

**Review by nvb — COMMENTED** [review]
> add a nice fat box comment at the top that explains at a high level what you're modeling (and sort of how it corresponds to our code).

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-:-Lf6Nfv40LOexMcFXhX7:bt1e3lv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf5-s1r8wvypgY8eAFA:-Lf6CMmv7vBGnVe1qR5Z:bpijetz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L11)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This might be a little clearer with a struct instead of a tuple, i.e. `\in [ key: KEYS, ts: 0..MAX_ATTEMPTS ]`
</blockquote></details>

I think those are saying slightly different things. What's written now is saying "set intent writes equal to a map from each key in the domain of KEYS to the epoch-timestamp tuple <<0, 0>>". I think your suggestion says "set intent writes equal to a random element in the set of all combinations of 'key' mapping to a valid key and 'ts' mapping to a valid timestamp".

I moved this from a tuple to a struct to be more explicit about what the fields are.
___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf53s-F7U7a3K1tDXAr:-Lf6F95zEWRcpATMRVBG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L222)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Weird spaces
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
:lgtm: thanks for the box! It's great.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-:-LfGjSny8FboSmmJwTG5:bkx9mxa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf5-s1r8wvypgY8eAFA:-LfGisOS3WxHMCetHyXn:b1ddi8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L11)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think those are saying slightly different things. What's written now is saying "set intent writes equal to a map from each key in the domain of KEYS to the epoch-timestamp tuple <<0, 0>>". I think your suggestion says "set intent writes equal to a random element in the set of all combinations of 'key' mapping to a valid key and 'ts' mapping to a valid timestamp".

I moved this from a tuple to a struct to be more explicit about what the fields are.
</blockquote></details>

No, sorry, I wrote the type of intent_writes (i.e. saying that `intent_writes should always be of type X`). That was confusing, but luckily the end result is that you did what I was trying to ask for.
___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf53s-F7U7a3K1tDXAr:-LfGjCnL2RCN2ZtaLxrW:bpm2tk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L222)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like they're still here and also in other places. Not sure this is worth iterating over but if you wanted to `s/\s+$//g` should fix them all.
___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-LfGipTt7rbvCvnv72PJ:-LfGipTu840d_Q18gNbp:b-j7qk9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3217c9488d7bc5d7bcc22e022b4a20d40a48fead/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L45)):*
> ```TLA
> (* - pkg/storage/batcheval/cmd_recover_txt.go                            *)
> (* - pkg/storage/replica_tscache.go                                      *)
> (*************************************************************************)
> ```

Very nice!

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-:-LfKgqG-7H0xFdkO3hrg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[docs/tla-plus/ParallelCommits/ParallelCommits.tla, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37558#-Lf53s-F7U7a3K1tDXAr:-LfKfA6IEF70Eqg5hb-Q:b-hx3ye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec9d18e8637516e42b4addee89aa533312bccd4f/docs/tla-plus/ParallelCommits/ParallelCommits.tla#L222)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Looks like they're still here and also in other places. Not sure this is worth iterating over but if you wanted to `s/\s+$//g` should fix them all.
</blockquote></details>

Oh, you meant the spacing after the line. I thought you meant the padding so that the equals signs lined up. Done.

**Pull request merged**
