### PR TITLE
distsqlrun: restructure a snippet of gnarly code

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-LRJqEPE-NFCygyn6zVj:-LRJqEPE-NFCygyn6zVk:bf1u6xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bb68fc9691daa16d592324a864b7f07b7403a9/pkg/sql/distsqlrun/processors.go#L683)):*
> ```Go
> 		}
> 		if meta != nil {
> 			if meta.Err != nil {
> ```

What's up with this?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-LRJqEPE-NFCygyn6zVj:-LRJr44OAvyK2tWf4TVI:bwrip6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bb68fc9691daa16d592324a864b7f07b7403a9/pkg/sql/distsqlrun/processors.go#L683)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's up with this?
</blockquote></details>

sorry, that came from the future, a different timeline. Removed.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LRNHju72nRN1xZQFBnq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 683 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-LRJqEPE-NFCygyn6zVj:-LRNHc8BAMLSmQKENBiw:bbinjhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7bb68fc9691daa16d592324a864b7f07b7403a9/pkg/sql/distsqlrun/processors.go#L683)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sorry, that came from the future, a different timeline. Removed.
</blockquote></details>

This is a different object, so linearizability still holds.

**Review by jordanlewis — APPROVED** [review]
Thanks, Andrei. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LRNIATL21nutU4Uefci:bnw57fj)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LROBq0K2qsq8FngSdbO:b-ydi9ay)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LROC3Cz331GYW45_94A:b-ydi9aw)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LROECOL37_67KSEMXQT:b-ydi9ay)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
bors r-

Looks like this needs a `make protobuf` before it can be merged.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32368#-:-LROSffL6nNx92h5_TQg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
