### PR TITLE
sql: Bug fix on LIKE operator

### PR DESCRIPTION
**Pull request by ghost**
Added count for the number of backslashes, `\`, preceding an ending `%` in a
pattern. LIKE operator now works correctly with backslashes.

Fixes: #24828.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/sem/tree/eval.go, line 3783 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaotq8fzh-otEOI31:-LAFaotq8fzh-otEOI32:b64x4uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3783)):*
> ```Go
> 		if !strings.ContainsAny(pattern[1:len(pattern)-1], "_%") {
> 			// Patterns with even number of `\` preceding the ending `%` will have
> 			// anyStart set to true. Otherwise anyStart will be set to false.
> ```

Shouldn't this be `s/anyStart/anyEnd/g`?

---

*[pkg/sql/sem/tree/eval.go, line 3798 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaIjU2F_fbzkE5wRj:-LAFaIjU2F_fbzkE5wRk:bu503hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3798)):*
> ```Go
> 			// singleAnyEnd and anyEnd are mutually exclusive
> 			// (similarly with Start).
> 			singleAnyEnd := pattern[len(pattern)-1] == '_' && pattern[len(pattern)-2] != '\\'
> ```

Is this also broken? Either way, let's add a test for it too.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848)*

**Comment by windchan7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sem/tree/eval.go, line 3783 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaotq8fzh-otEOI31:-LAFvg5G786DXUIGYvwU:bauoll7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3783)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't this be `s/anyStart/anyEnd/g`?
</blockquote></details>

Thanks for the catch.

---

*[pkg/sql/sem/tree/eval.go, line 3798 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaIjU2F_fbzkE5wRj:-LAFvkkEBuz9yvLokZtu:bawa2k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3798)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this also broken? Either way, let's add a test for it too.
</blockquote></details>

Sorry I overlooked it. I added a couple test cases to test both.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/eval.go, line 3798 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaIjU2F_fbzkE5wRj:-LAG1ZRP6-s6vGO1ykj9:bzffgb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3798)):*
<details><summary><i>Previously, windchan7 (Victor Chen) wrote…</i></summary><blockquote>

Sorry I overlooked it. I added a couple test cases to test both.
</blockquote></details>

No need to apologize :smiley: 

---

*[pkg/sql/sem/tree/eval.go, line 3760 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAG-sxr3hnGETBV5hAc:-LAG-sxr3hnGETBV5hAd:b-ss8ptk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf109271a58c05c943591c8656bbac044247e8b0/pkg/sql/sem/tree/eval.go#L3760)):*
> ```Go
> }
> 
> // ending returns true if the ending byte is end and pattern has even number
> ```

Let's make this name more descriptive. How `hasUnescapedSuffix` to draw parallels to [`strings.HasSuffix`](https://golang.org/pkg/strings/#HasSuffix). Also, I'd switch the two param names to mirror that function as well.

Also, I think we'll want to parameterize the `escapeToken` like we do for `unescapePattern`, so let's add a third param. This might force you to restructure this a bit to support multi-byte escape tokens.

Another alternative to all of this is to just throw our hands up in defeat when we see escapePattern as the second to last char in the pattern right behind an `%` or an `_`.  `optimizedLikeFunc` is all best effort so we can always return `nil` and defer to the un-optimized regexp approach.

---

*[pkg/sql/sem/tree/eval_test.go, line 310 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAG1VH7AhTlGYGZFGal:-LAG1VH7AhTlGYGZFGam:bjac5jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf109271a58c05c943591c8656bbac044247e8b0/pkg/sql/sem/tree/eval_test.go#L310)):*
> ```Go
> 		{`'.' LIKE '\.'`, `true`},
> 		{`'\' LIKE '%\\%'`, `true`},
> 		{`'\%' LIKE '\\\%'`, `true`},
> ```

Let's add the exact cases from the bug report as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848)*

**Comment by windchan7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/sem/tree/eval.go, line 3798 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAFaIjU2F_fbzkE5wRj:-LAG6l1fDUkivWxOAMs3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f907bb44cd4425443a1407897b18fd82bb95bb4/pkg/sql/sem/tree/eval.go#L3798)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need to apologize :smiley: 
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval_test.go, line 310 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848#-LAG1VH7AhTlGYGZFGal:-LAG6kSy43SsYR75_5fV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf109271a58c05c943591c8656bbac044247e8b0/pkg/sql/sem/tree/eval_test.go#L310)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's add the exact cases from the bug report as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24848)*

**Pull request merged**
