### PR TITLE
upgrades: use TestingBinaryMinSupportedVersion in tests

### PR DESCRIPTION
**Pull request by rafiss**
As described in #100552, it's important for this API to use TestingBinaryMinSupportedVersion in order to correctly bootstrap on the older version.

informs #100552 
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
Needs some bazel generation. You have my stamp when CI is green. 

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100726#-:-NSHlbN0CDrsUDlfcZp8:b-1m5mjr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @herkolategan, and @srosenberg)

**Review by srosenberg — APPROVED** [review]

**Pull request merged**
