### PR TITLE
ci: add scripts for bazel-based `ui test`, `ui lint` ci jobs

### PR DESCRIPTION
**Pull request by rickystewart**
These scripts just do the same logic that `dev` does for the same
functions.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Working `ui lint` job: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_UiLint/4681158?buildTab=log&focusLine=321&linesState=248.253

**Comment by rickystewart** [comment]
`ui test` is not working yet, I need to install `chrome` on the builder image, give me a second.

**Comment by sjbarag** [comment]
> `ui test` is not working yet, I need to install `chrome` on the builder image, give me a second.

This is because Karma.  One day soonish we'll get rid of that.

**Review by sjbarag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail and @rickystewart)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/78526#-MzGDfQh1xhPtBnoMWdM:-MzGDfQh1xhPtBnoMWdN:b58gh6c) (no related file):*
Forgot to approve this last week, sorry!

---

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Comment by rickystewart** [comment]
UI test build now working: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_UiTest/4720069?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true

**Comment by rickystewart** [comment]
blathers backport 22.1

**Pull request merged**
