### PR TITLE
roachtest: add test for authentication under network partition

### PR DESCRIPTION
**Pull request by knz**
Supersedes #66550

### CODE REVIEW

**Comment by knz** [comment]
@rafiss with your test and my fixes I am able to readily reproduce the customer's issue. I'm now looking into the log files to see if there's anything interesting.

cc @tbg

**Comment by knz** [comment]
Here are the node logs from the repro (1 is the node with all the leases originally, that got shut off):

[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/6702925/logs.tar.gz)

Immediately after blocking traffic with `iptables` at 14:16:07, the test saw:

- 14:16:09: 9.58s connection delay from n3 ending at 14:16:20  
  (too long, but not enough to trigger the error)
- 14:16:20: 0.14s connection delay from n2 ending at 14:16:22
- 14:16:22: 6.51s connection delay from n3 ending at 14:16:31
  (again too long, but not enough to trigger the error)
- 14:16:31: 10.07s connection delay from n2 ending at 14:16:43

that last failure failed with the customer's reported error message
```
ERROR: internal error while retrieving user account
```

then:
- 14:16:43: 3.31s connection delay from n3 ending at 14:16:48

and then after that all further connection attempts were resolved quickly (in less than 0.2s)


As detailed in the timeline above, both n2 and n3 were encountering a >4.5s delay for up to 30 seconds. This strongly confirms the customer's observation.

So the period of interest is from the iptables command at 14:16:07 to when connections became normal again at 14:16:48.

Here are the "interesting" heartbeat failures from n2:

```
cockroach.log:W210623 14:15:53.240839 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 3.606109623s; err=<nil>
cockroach.log:W210623 14:16:16.635103 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500253127s; err=context deadline exceeded
cockroach.log:W210623 14:16:20.604874 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 3.9696735s; err=<nil>
cockroach.log:W210623 14:16:25.635146 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500288899s; err=context deadline exceeded
cockroach.log:W210623 14:16:30.135478 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500233573s; err=‹aborted in DistSender: context deadline exceeded›
cockroach.log:W210623 14:16:30.189462 33594 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r8/3:‹/Table/1{2-3}›] slow heartbeat took 4.549790544s; err=<nil>
cockroach.log:W210623 14:16:30.189555 33604 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r6/3:‹/Table/{SystemCon…-11}›] slow heartbeat took 4.51348012s; err=<nil>
cockroach.log:W210623 14:16:39.135067 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500236273s; err=context deadline exceeded
cockroach.log:W210623 14:16:43.635375 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500234435s; err=‹aborted in DistSender: context deadline exceeded›
cockroach.log:W210623 14:16:48.135586 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500118935s; err=context deadline exceeded
cockroach.log:W210623 14:16:48.561551 45860 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r5/3:‹/{Systemtse-Table/System…}›] slow heartbeat took 9.415041492s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:16:48.562160 46402 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r6/3:‹/Table/{SystemCon…-11}›] slow heartbeat took 8.849017769s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:16:48.562830 50141 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r3/2:‹/System/{NodeLive…-tsd}›] slow heartbeat took 4.653593527s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:16:48.563274 50205 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r4/2:‹/System{/tsd-tse}›] slow heartbeat took 4.514427495s; err=heartbeat failed on epoch increment

-- after this point, the client doesn't experience login delay any more --

cockroach.log:W210623 14:16:57.135077 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500238113s; err=context deadline exceeded
cockroach.log:W210623 14:17:01.635347 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500200418s; err=‹aborted in DistSender: context deadline exceeded›
cockroach.log:W210623 14:17:05.578698 63614 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r6/3:‹/Table/{SystemCon…-11}›] slow heartbeat took 7.007826896s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:17:05.579189 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 3.943750846s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:17:05.579565 68377 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r3/2:‹/System/{NodeLive…-tsd}›] slow heartbeat took 1.671525872s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:17:05.579989 68424 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r4/2:‹/System{/tsd-tse}›] slow heartbeat took 1.528752237s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:17:15.135057 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500228331s; err=context deadline exceeded
cockroach.log:W210623 14:17:19.635231 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 3.802752131s; err=context deadline exceeded
cockroach.log:W210623 14:17:24.135498 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500160088s; err=context deadline exceeded
cockroach.log:W210623 14:17:25.034981 79866 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r6/3:‹/Table/{SystemCon…-11}›] slow heartbeat took 9.206951399s; err=heartbeat failed on epoch increment
cockroach.log:W210623 14:17:33.135094 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500235161s; err=context deadline exceeded
cockroach.log:W210623 14:17:35.237710 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 2.102542378s; err=<nil>
cockroach.log:W210623 14:17:35.237950 96823 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r4/2:‹/System{/tsd-tse}›] slow heartbeat took 1.11815483s; err=<nil>
cockroach.log:W210623 14:17:35.238176 96869 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r3/2:‹/System/{NodeLive…-tsd}›] slow heartbeat took 1.118141729s; err=<nil>
cockroach.log:W210623 14:17:46.635080 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.50018725s; err=context deadline exceeded
cockroach.log:W210623 14:17:55.635182 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500354615s; err=context deadline exceeded
cockroach.log:W210623 14:18:00.135594 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500244238s; err=‹aborted in DistSender: context deadline exceeded›
cockroach.log:W210623 14:18:04.635823 182 kv/kvserver/node_liveness.go:748 ⋮ [n2,liveness-hb] slow heartbeat took 4.500120754s; err=context deadline exceeded
cockroach.log:W210623 14:18:04.980352 116520 kv/kvserver/node_liveness.go:748 ⋮ [n2,s2,r6/3:‹/Table/{SystemCon…-11}›] slow heartbeat took 9.314270655s; err=<nil>
```

The log paste above separates the two phases of slow heartbeats, one "while the client is experiencing delays"  and another "after this point the client seems fine"

What's different between the two?

- both phases see heartbeat failures on r3, r4, r6
- only the first phase (the one with problem) sees hearbeat failures on r5 and r8
- later the second phase (the one without a problem) also sees failures on r12, r20, r33

What are these ranges?

| Range | Keys | Note |
|--|--|--|
| r3 | /System/NodeLivenessMax - /System/tsd | empty range? |
| r4 | /System/tsd - /System/"tse" | timeseries |
| r5 | /System/"tse" - /Table/SystemConfigSpan/Start | empty range? |
| r6 | /Table/SystemConfigSpan/Start - /Table/11 | system config |
| r8 | /Table/12 - /Table/13 | system.eventlog |
| r12 | /Table/16 - /Table/17 | ?? |
| r20 | /Table/20 - /Table/21 | system.table_statistics |
| r33 | /Table/37 - /Table/38 | system.scheduled_jobs |

**Comment by knz** [comment]
I only looked at the hearbeat failures. There are more events in the logs about the circuit breaker, updating node descriptors etc but I haven't investigated those yet.

**Comment by rafiss** [comment]
This is great! 

We should also break this down into two categories of slow heartbeats:
- The ones that take 4.5 seconds make sense to me, since the heartbeat is run with a context timeout of 4.5 seconds. https://github.com/cockroachdb/cockroach/blob/62196e0eefd380146617da673913e61c1764b740/pkg/kv/kvserver/node_liveness.go#L630
- There are also heartbeats that take 8-9 seconds, and those are much more confusing and concerning to me. It indicates we aren't respecting the context timeout somewhere.

**Comment by knz** [comment]
yes you're right

but even the 4.5s timeouts can be a problem if they are cascading. I'm thinking that there's likely a cascading failure with first timeout on meta, then timeout on liveness, then timeout on system.users, which will force a >15s timeout on at least one client conn.

**Comment by rafiss** [comment]
Definitely agree that it would be ideal to improve the 4.5s behavior and fail 

Sharing one snippet from [these gRPC docs](https://pkg.go.dev/google.golang.org/grpc?utm_source=godoc#WaitForReady) that may be relevant:

> WaitForReady configures the action to take when an RPC is attempted on broken connections or unreachable servers. If waitForReady is false, the RPC will fail immediately. Otherwise, the RPC client will block the call until a connection is available (or the call is canceled or times out) and will retry the call if it fails due to a transient error. gRPC will not retry if data was written to the wire unless the server indicates it did not process the data. Please refer to https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md.
>
> By default, RPCs don't "wait for ready". 

So it seems like gRPC is supposed to fail more quickly. Would it be worth investigating this further?

And also possibly related issues https://github.com/grpc/grpc-go/issues/1443 and https://github.com/grpc/grpc-go/issues/2663

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cmd/roachtest/network.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuDVWe8HczWC5sl0Kj:-McuDVWe8HczWC5sl0Kk:b-92fcln) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L128)):*
> ```Go
> 		"--args=--accept-sql-without-tls",
> 		"--env=COCKROACH_SCAN_INTERVAL=200ms",
> 		"--env=COCKROACH_SCAN_MAX_IDLE_TIME=20ms",
> ```

consider commenting why we use these environment variables
___
*[pkg/cmd/roachtest/network.go, line 243 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuCtotAQmTR0ceDeFe:-McuCtovA-yiY-BwxuOl:b3h8ysr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L243)):*
> ```Go
> 
> 				url := fmt.Sprintf("postgres://testuser:password@%s/defaultdb?sslmode=require", serverAddrs[i-1])
> 				b, err := c.RunWithBuffer(ctx, t.l, clientNode, "time", "-p", "./cockroach", "sql",
> ```

ah interesting, so you've changed it to connect from another GCE instance to all the server nodes. any particular reason why? the testing done by the customer was just logging directly onto the server and connecting to localhost
___
*[pkg/cmd/roachtest/network.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuALM5CwDw7CCg32nu:-McuALM5CwDw7CCg32nv:b-ks7l4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L267)):*
> ```Go
> sudo iptables -P OUTPUT ACCEPT;
> 
> # Drop any node-to-node crdb traffic.
> ```

i had set up more aggressive rules in my draft, since i thought we'd want to drop all ICMP traffic as well. i guess it's not necessary to repro though, but maybe still useful to have the more aggressive rule? blocking all traffic (or as much as we can) matches more closely with the kind of testing done by the customer
___
*[pkg/cmd/roachtest/network.go, line 277 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuBHeeBmeqQrIhJETn:-McuBHeeBmeqQrIhJETo:b-iavhkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L277)):*
> ```Go
> 
> 	// (attempt to) restore iptables when test end, so that cluster
> 	// can be investigated afterwards.
> ```

well, we'd still be able to SSH into the node without undoing these rules. or did you mean something else?
___
*[pkg/cmd/roachtest/network.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuDNBKD12O2PDd9T26:-McuDNBKD12O2PDd9T27:b-8geizg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L291)):*
> ```Go
> 	t.l.Printf("waiting for client to do its thing...")
> 
> 	wg.Wait()
> ```

do we still need `wg` if we move the `m.Wait()` call to here?
___
*[pkg/cmd/roachtest/network.go, line 292 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuAwaE8n6xriajHO6P:-McuAwaE8n6xriajHO6Q:ba6qvd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L292)):*
> ```Go
> 
> 	wg.Wait()
> 	if errorCount >= 1 /*c.Spec().NodeCount*/ {
> ```

i had left this commented as a TODO/reminder for myself. i don't really know what the expected number of failures is. should it be 0? (if so, change to `errorCount > 0` and remove the commented code)
___
*[pkg/cmd/roachtest/network.go, line 450 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuAm770_Io2rwsbBVE:-McuAm770_Io2rwsbBVF:b-dkwypb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L450)):*
> ```Go
> 	})
> 	r.Add(testSpec{
> 		Name:    fmt.Sprintf("network/authentication/nodes=%d", numNodes),
> ```

it wasn't entirely clear to me why these tests use 4 nodes and not 3. i suppose it's fine though.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cmd/roachtest/network.go, line 450 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuAm770_Io2rwsbBVE:-McuEO8g6c4RyNmC__rf:b-qyx8i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L450)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it wasn't entirely clear to me why these tests use 4 nodes and not 3. i suppose it's fine though.
</blockquote></details>

retracting this -- i see it's because one of the nodes is only used for trying to connect to the others.

**Comment by nvanbenschoten** [comment]
As a data point, I've been running this with the settings from https://github.com/cockroachdb/cockroach/pull/66550#issuecomment-865404485 to see the full extent of one of these failover delays. I have yet to see any login attempt take longer than 22 seconds on v20.2.

Unfortunately, I am running into trouble in a few areas with trying to get this running with v20.1. @rafiss, have you had any luck with that?

**Comment by nvanbenschoten** [comment]
I upgraded from `v20.2.10` to `release-20.2`'s HEAD and saw this delay drop down to about 9 seconds on each attempt. I believe (but have not confirmed) that this is because of https://github.com/cockroachdb/cockroach/pull/66552. While that change only shaves off 4.5 during the recovery of a single range, it has the potential to compound across the multiple dependent ranges at play here. I'll try to narrow the improvement down to just this commit.

**Comment by rafiss** [comment]
For this issue (https://github.com/cockroachlabs/support/issues/1022) the customer reported the behavior on 20.2.10 as well as 20.1.8; so I've been focusing on 20.2.10 only so far.

I just tried with 20.1.8 now, and did get an error:

```
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *exec.ExitError:
I210623 22:00:23.669764 1 (gostd) cluster_synced.go:1658  [-] 1  command failed
22:00:23 test.go:362: test failure: 	cluster.go:2307,network.go:123,network.go:454,test_runner.go:756: /Users/rafiss/go/src/github.com/cockroachdb/cockroach/bin/roachprod start --secure --args=--locality=node=1 --args=--accept-sql-without-tls --env=COCKROACH_SCAN_INTERVAL=200ms --env=COCKROACH_SCAN_MAX_IDLE_TIME=20ms rafi-1624485452-01-n4cpu4:1 returned: exit status 1
		(1) /Users/rafiss/go/src/github.com/cockroachdb/cockroach/bin/roachprod start --secure --args=--locality=node=1 --args=--accept-sql-without-tls --env=COCKROACH_SCAN_INTERVAL=200ms --env=COCKROACH_SCAN_MAX_IDLE_TIME=20ms rafi-1624485452-01-n4cpu4:1 returned
		  | stderr:
		  | <... some data truncated by circular buffer; go to artifacts for details ...>
		  | ach.go:373
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachprod/install.Cockroach.Start.func1
```
```
$ journalctl -xe

Jun 23 22:00:17 rafi-1624485452-01-n4cpu4-0001 bash[10414]: /home/ubuntu/cockroach-helper.sh: line 20: 10422 Killed                  ${HOME}/cockroach start --certs-dir=${HOME>
Jun 23 22:00:17 rafi-1624485452-01-n4cpu4-0001 bash[10748]: cockroach exited with code 137: Wed Jun 23 22:00:17 UTC 2021
Jun 23 22:00:17 rafi-1624485452-01-n4cpu4-0001 systemd[1]: cockroach.service: Main process exited, code=exited, status=137/n/a
```

**Comment by nvanbenschoten** [comment]
> I just tried with 20.1.8 now, and did get an error:

I found that this error goes away if you use a roachprod binary from the release-20.1 branch. But I then found that the `--accept-sql-without-tls` flag was unsupported on v20.1.

> I'll try to narrow the improvement down to just this commit.

I can confirm. When running https://github.com/cockroachdb/cockroach/pull/66552/commits/0fcebbf820f9a4621adbfe005610102d3b3a4c90, I see a single delay of about 9 to 10 seconds. When running on its parent SHA, I see a single delay that lasts somewhere between 20 and 24 seconds.

**Comment by nvanbenschoten** [comment]
After reverting https://github.com/cockroachdb/cockroach/pull/66550#issuecomment-865404485 and running with https://github.com/cockroachdb/cockroach/commit/0fcebbf820f9a4621adbfe005610102d3b3a4c90, I still do see one login attempt hit the 10s timeout, as expected. However, I then see no subsequent slowdown at all on any other connection attempt.

I'll see how stable the test is when I bump `server.user_login.timeout` from 10s to 15s.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @tbg)

___
*[pkg/cmd/roachtest/network.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuDVWe8HczWC5sl0Kj:-McxALx1A5T7ah9xbVVz:b-d7bhn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L128)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

consider commenting why we use these environment variables
</blockquote></details>

will do
___
*[pkg/cmd/roachtest/network.go, line 243 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuCtotAQmTR0ceDeFe:-Mcx9Ny9-z67b67yg8bE:b-hfoib7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L243)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah interesting, so you've changed it to connect from another GCE instance to all the server nodes. any particular reason why? the testing done by the customer was just logging directly onto the server and connecting to localhost
</blockquote></details>

Yes it's to exclude any variability due to the network distance between my computer where `roachtest` is running and the gce instance.
___
*[pkg/cmd/roachtest/network.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuALM5CwDw7CCg32nu:-Mcx9SrA389CxCznS40s:b-rmu6bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L267)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i had set up more aggressive rules in my draft, since i thought we'd want to drop all ICMP traffic as well. i guess it's not necessary to repro though, but maybe still useful to have the more aggressive rule? blocking all traffic (or as much as we can) matches more closely with the kind of testing done by the customer
</blockquote></details>

We should focus on reducing the scope of the test as much as possible to get to what the customer observes.
Once we have that, we can fix that issue, and then step over to a wider test scope to see if other issues remain.

Also:
- I see your point wrt ICMP but I'm pretty sure crdb does not use ICMP.
- regardless of which rules you use we should be careful to only block the traffic between the server nodes and not the traffic from the roachtest process (otherwise the monitor will bark, and it won't be possible to properly interact with the gce instance from the gce console and roachprod)
___
*[pkg/cmd/roachtest/network.go, line 277 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuBHeeBmeqQrIhJETn:-Mcx9uwd8EttSckvbz-F:bebtlmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L277)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

well, we'd still be able to SSH into the node without undoing these rules. or did you mean something else?
</blockquote></details>

I want the ability to re-start the test using the same GCE instance, to save up on reinitialization costs.
___
*[pkg/cmd/roachtest/network.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuDNBKD12O2PDd9T26:-Mcx9znt4q15F9Lrjbkm:b-7bv9ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L291)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we still need `wg` if we move the `m.Wait()` call to here?
</blockquote></details>

the monitor code is generally unreliable. I wouldn't trust it to organize synchronization between phases of the test code.
___
*[pkg/cmd/roachtest/network.go, line 292 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuAwaE8n6xriajHO6P:-McxAHF6BPMfkSE5sIos:b-y64kdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L292)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i had left this commented as a TODO/reminder for myself. i don't really know what the expected number of failures is. should it be 0? (if so, change to `errorCount > 0` and remove the commented code)
</blockquote></details>

I'll reply to this in a next comment.

**Comment by knz** [comment]
Here are a few things I'd like to see happen:

- do the additional logging inside the crdb code as described inside [this comment](https://github.com/cockroachdb/cockroach/pull/66550#issuecomment-866645671). Also this will come useful in #66777.

- explore how much the test result changes when we remove the env vars during server initialization. Right now I'm using these env vars because they dramatically reduce the time needed to wait for the initial rebalancing and lease migration (from ~1 minute to <5 seconds).

- change the structure of the async client goroutine. Right now, the code does a round-robin connection attempt to all the non-partitioned nodes. This is not what the customer is doing. Instead, I want to have **1 goroutine per server node**, with each goroutine attempting to connect to the same node in a sequence, retrying with no delay if they observe a connection error. I want to see this confirm that:
  1) it can establish connections without delay, OR
  2) if there is a delay/error once, there is no delay afterwards.

- evolve the test to run longer, and try partitioning multiple nodes over time (e.g. perhaps a round-robin partition, one node split from the network at a time), and each time verify the client connection behavior.


The last two points are important to bring this test code into production: 
- we'll want to have it running in nightlies
- in the long term, I believe it's OK for clients to experience a connection delay *once* after a network partition, during the time needed by crdb to heal. The test should thus tolerate at least one failure in the short amount of time after the network partition occurs. Not more than one failure though; that's what the customer doesn't want.

**Comment by knz** [comment]
> I'll see how stable the test is when I bump server.user_login.timeout from 10s to 15s.

@nvanbenschoten did you mean bump it down to 5s? Presumably a longer timeout will tolerate more errors, not less.

**Comment by knz** [comment]
This is ready for review now. RFAL

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66768)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @tbg)

___
*[pkg/cmd/roachtest/network.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-McuDVWe8HczWC5sl0Kj:-MfXA9g210rja4vhQMRa:b-ticrar) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba0fc76845801d255d7323e5ec8e71c737ad108/pkg/cmd/roachtest/network.go#L128)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Removed them.

**Review by rafiss — APPROVED** [review]
this is wonderful. thanks for taking this over and bringing it to a finish and all the cleanup+enhancements in this test. lgtm!

i wonder two things:
- now that i've merged the `AuthInfoCache` PR, would there be value in running this test once with the cache enabled, and once disabled? the setting is `server.authentication_cache.enabled`. i'd be able to add that additional test myself, so we can merge this PR now
- is there still value in adding the logging you mentioned in https://github.com/cockroachdb/cockroach/pull/66550#issuecomment-866645671 ? i'm not familiar enough with that part of the code to say. if the logging is useful, then i think it'd be better to spin that off into its own issue and keep this PR as is

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66768#-:-Mfa2BBR2zOAPSYp3mFn:b-wug8k7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @tbg)

**Comment by rafiss** [comment]
@knz friendly ping -- can this be merged?

the CI failures is
```
pkg/cmd/roachtest/tests/network.go:32:2: a blank import should be only in a main or test package, or have a comment justifying it
```

**Comment by rafiss** [comment]
fixed the lint issue and merging after checking with knz

bors r=rafiss,knz

**Comment by yuzefovich** [comment]
Seems like this needs an update.

bors r-

**Comment by rafiss** [comment]
i don't think it needs an update. Github CI is passing after I retriggered. I'll give it another shot

bors r=rafiss,knz

**Comment by yuzefovich** [comment]
I don't think so - it calls a method that doesn't exist in the interface anymore:
```
db, err := c.ConnSecure(ctx, 1, "root", localCertsDir, 26257)
```

and I couldn't immediately figure out which one to call, so I didn't update the PR myself.

bors r-

**Comment by rafiss** [comment]
I see, thanks for the explanation. Fixed

**Comment by rafiss** [comment]
bors r=rafiss,knz

**Pull request merged**
