### PR TITLE
sql/catalog: add return error to RunPostDeserializationChanges

### PR DESCRIPTION
**Pull request by rafiss**
Release justification: low risk enhancement to existing functionality.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @msbutler, and @rafiss)

___
*[pkg/ccl/backupccl/restore_planning.go, line 872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduV0T0Gmuq38CQF75:-MxduV0T0Gmuq38CQF76:b4hdeck) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/ccl/backupccl/restore_planning.go#L872)):*
> ```Go
> 		}
> 		if err := b.RunPostDeserializationChanges(); err != nil {
> 			return err
> ```

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
___
*[pkg/sql/catalog/descriptor.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-Mxdu1SOAPZRaDo4gXcB:-Mxdu1SOAPZRaDo4gXcC:b-x6q68s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/descriptor.go#L78)):*
> ```Go
> 	// RunPostDeserializationChanges attempts to perform changes to the descriptor
> 	// being built from a deserialized protobuf.
> 	RunPostDeserializationChanges() error
> ```

Please note that any error should be treated an assertion failure and indicates corruption. 
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-Mxdu9IX5cEv_fgF8MBs:-Mxdu9IX5cEv_fgF8MBt:b4hdeck) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/descs/kv_descriptors.go#L247)):*
> ```Go
> 		b := desc.NewBuilder()
> 		if err := b.RunPostDeserializationChanges(); err != nil {
> 			return nil, err
> ```

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
___
*[pkg/sql/catalog/internal/catkv/catalog_query.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduEXt7lhEsT3TKY3k:-MxduEXt7lhEsT3TKY3l:b4hdeck) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/internal/catkv/catalog_query.go#L207)):*
> ```Go
> 	}
> 	if err := b.RunPostDeserializationChanges(); err != nil {
> 		return nil, err
> ```

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
___
*[pkg/sql/catalog/systemschema/system.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduHcD-EpHYS78hus-:-MxduHcD-EpHYS78hus0:bouqwl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/systemschema/system.go#L800)):*
> ```Go
> 	if err := b.RunPostDeserializationChanges(); err != nil {
> 		log.Fatalf(
> 			ctx, "System table %q cannot be registered, error during RunPostDeserializationChanges: %+v",
> ```

nit: message shouldn't be capitalized. 
___
*[pkg/sql/doctor/doctor.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduMui7lyQPQTrb5j6:-MxduMui7lyQPQTrb5j7:bpdvc8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/doctor/doctor.go#L85)):*
> ```Go
> 		if b != nil {
> 			if err := b.RunPostDeserializationChanges(); err != nil {
> 				return nil, err
> ```

can you wrap this?
___
*[pkg/sql/doctor/doctor.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduOJw8EC3fe-Au7TS:-MxduOJw8EC3fe-Au7TT:bpdvc8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/doctor/doctor.go#L98)):*
> ```Go
> 		b := desc.NewBuilder()
> 		if err := b.RunPostDeserializationChanges(); err != nil {
> 			return nil, err
> ```

can you wrap this?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @e-mbrown, and @msbutler)

___
*[pkg/ccl/backupccl/restore_planning.go, line 872 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduV0T0Gmuq38CQF75:-MxeZoDD5X-ipXMCjxjV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/ccl/backupccl/restore_planning.go#L872)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descriptor.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-Mxdu1SOAPZRaDo4gXcB:-Mxe_11wEYj1l4coBEsc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/descriptor.go#L78)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Please note that any error should be treated an assertion failure and indicates corruption. 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descs/kv_descriptors.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-Mxdu9IX5cEv_fgF8MBs:-Mxe_8eR7622imFmFTAt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/descs/kv_descriptors.go#L247)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/internal/catkv/catalog_query.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduEXt7lhEsT3TKY3k:-Mxe_Cy964Y18p3R4IdI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/internal/catkv/catalog_query.go#L207)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you wrap this with an assertion failure and note that it's running PostDeserializationChanges?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/systemschema/system.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduHcD-EpHYS78hus-:-Mxe_E-f5PiN5AAN8HrD:b-n4qswf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/catalog/systemschema/system.go#L800)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: message shouldn't be capitalized. 
</blockquote></details>

fixed this one and the existing one above
___
*[pkg/sql/doctor/doctor.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduMui7lyQPQTrb5j6:-Mxe_WF-2mAKqdfYLzJQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/doctor/doctor.go#L85)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you wrap this?
</blockquote></details>

Done.
___
*[pkg/sql/doctor/doctor.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-MxduOJw8EC3fe-Au7TS:-Mxe_ZtcEdJRztqd48dl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d9d67e9df6e9a77dfe5e09c6e60f2020bd1ab3f/pkg/sql/doctor/doctor.go#L98)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you wrap this?
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77483#-:-MxeddBz1c9hjtj5FzYm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @e-mbrown and @msbutler)

**Comment by rafiss** [comment]
looks like a flake from [Examples-ORMs](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ExampleORMs). i re-ran just that job and it passed

bors r=ajwerner

**Pull request merged**
