### PR TITLE
sql: break delete fast path into its own node

### LINKED ISSUE #31656: sql: fast path delete seems to still scan
Check out the following trace. It looks like there's still a Scan sent by the delete, even before it says it's a fast path delete. What gives - is this expected?

Also, does it make sense to send a `DelRng` when we're only deleting a single key/? Seems like that might incur more overhead than a point delete (or a couple in the case of multiple column families).

```
root@127.0.0.1:52506/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 5.958214ms

root@127.0.0.1:52506/defaultdb> select * from a;
  a
+---+
(0 rows)

Time: 7.832102ms

root@127.0.0.1:52506/defaultdb> delete from a where a=10;
DELETE 0

Time: 2.48128ms

root@127.0.0.1:52506/defaultdb> \set auto_trace=on                                                                                                                                                          root@127.0.0.1:52506/defaultdb> delete from a where a=10 or a=10;
DELETE 0

Time: 2.06686ms

             timestamp             |         age          |                                   message                                    |                        tag                         | location |             operation             | span
+----------------------------------+----------------------+------------------------------------------------------------------------------+----------------------------------------------------+----------+-----------------------------------+------+
  2018-10-19 21:31:28.523999+00:00 | 0s                   | === SPAN START: session recording ===                                        |                                                    |          | session recording                 |    0
  2018-10-19 21:31:28.524039+00:00 | 39\302\265s286ns     | [NoTxn pos:120] executing Sync                                               | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.524238+00:00 | 238\302\265s868ns    | [NoTxn pos:121] executing ExecStmt: DELETE FROM a WHERE (a = 10) OR (a = 10) | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.52425+00:00  | 250\302\265s604ns    | executing: DELETE FROM a WHERE (a = 10) OR (a = 10) in state: NoTxn          | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.524271+00:00 | 271\302\265s879ns    | === SPAN START: sql txn ===                                                  |                                                    |          | sql txn                           |    1
  2018-10-19 21:31:28.524356+00:00 | 356\302\265s915ns    | [Open pos:121] executing ExecStmt: DELETE FROM a WHERE (a = 10) OR (a = 10)  | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.52437+00:00  | 370\302\265s363ns    | executing: DELETE FROM a WHERE (a = 10) OR (a = 10) in state: Open           | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.52441+00:00  | 410\302\265s995ns    | planning starts: DELETE                                                      | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524413+00:00 | 413\302\265s502ns    | generating optimizer plan                                                    | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524438+00:00 | 438\302\265s353ns    | optimizer plan failed: unsupported statement: *tree.Delete                   | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.52444+00:00  | 440\302\265s420ns    | optimizer falls back on heuristic planner                                    | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524442+00:00 | 442\302\265s589ns    | query is correlated: false                                                   | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524444+00:00 | 444\302\265s558ns    | heuristic planner starts                                                     | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524468+00:00 | 468\302\265s302ns    | added table 'defaultdb.public.a' to table collection                         | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524528+00:00 | 528\302\265s307ns    | found table in table collection for table 'defaultdb.public.a'               | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524635+00:00 | 635\302\265s565ns    | heuristic planner optimizes plan                                             | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524756+00:00 | 756\302\265s632ns    | heuristic planner optimizes subqueries                                       | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524759+00:00 | 759\302\265s881ns    | planning ends                                                                | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524761+00:00 | 761\302\265s953ns    | checking distributability                                                    | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524771+00:00 | 771\302\265s889ns    | query not supported for distSQL: unsupported node *sql.rowCountNode          | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524773+00:00 | 773\302\265s466ns    | distributable plan: false                                                    | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524776+00:00 | 776\302\265s588ns    | execution starts: distributed                                                | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524789+00:00 | 789\302\265s869ns    | === SPAN START: consuming rows ===                                           |                                                    |          | consuming rows                    |    2
  2018-10-19 21:31:28.524815+00:00 | 815\302\265s606ns    | creating DistSQL plan with isLocal=true                                      | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524846+00:00 | 846\302\265s797ns    | running DistSQL plan                                                         | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.524864+00:00 | 864\302\265s300ns    | === SPAN START: flow ===                                                     |                                                    |          | flow                              |    3
  2018-10-19 21:31:28.524899+00:00 | 899\302\265s77ns     | starting (1 processors, 0 startables)                                        | [n1,client=127.0.0.1:52508,user=root]              |          | flow                              |    3
  2018-10-19 21:31:28.524958+00:00 | 959\302\265s         | Scan /Table/52/1/10{-/#}                                                     | [n1,client=127.0.0.1:52508,user=root]              |          | flow                              |    3
  2018-10-19 21:31:28.52497+00:00  | 970\302\265s224ns    | === SPAN START: txn coordinator send ===                                     |                                                    |          | txn coordinator send              |    4
  2018-10-19 21:31:28.525008+00:00 | 1ms8\302\265s755ns   | === SPAN START: dist sender send ===                                         |                                                    |          | dist sender send                  |    5
  2018-10-19 21:31:28.525043+00:00 | 1ms43\302\265s109ns  | querying next range at /Table/52/1/10                                        | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    5
  2018-10-19 21:31:28.525091+00:00 | 1ms92\302\265s21ns   | r21: sending batch 1 Scan to (n1,s1):1                                       | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    5
  2018-10-19 21:31:28.525096+00:00 | 1ms96\302\265s509ns  | sending request to local client                                              | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    5
  2018-10-19 21:31:28.525106+00:00 | 1ms106\302\265s343ns | === SPAN START: /cockroach.roachpb.Internal/Batch ===                        |                                                    |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525111+00:00 | 1ms111\302\265s666ns | 1 Scan                                                                       | [n1]                                               |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525123+00:00 | 1ms123\302\265s367ns | executing 1 requests                                                         | [n1,s1]                                            |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525138+00:00 | 1ms138\302\265s609ns | read-only path                                                               | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525148+00:00 | 1ms148\302\265s789ns | read has no clock uncertainty                                                | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525159+00:00 | 1ms160\302\265s22ns  | command queue                                                                | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525176+00:00 | 1ms176\302\265s382ns | waiting for read lock                                                        | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.52535+00:00  | 1ms350\302\265s540ns | read completed                                                               | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    6
  2018-10-19 21:31:28.525447+00:00 | 1ms447\302\265s454ns | fast delete: skipping scan                                                   | [n1,client=127.0.0.1:52508,user=root]              |          | flow                              |    3
  2018-10-19 21:31:28.525462+00:00 | 1ms462\302\265s910ns | === SPAN START: txn coordinator send ===                                     |                                                    |          | txn coordinator send              |    7
  2018-10-19 21:31:28.525507+00:00 | 1ms507\302\265s249ns | === SPAN START: dist sender send ===                                         |                                                    |          | dist sender send                  |    8
  2018-10-19 21:31:28.525538+00:00 | 1ms538\302\265s503ns | querying next range at /Table/52/1/10                                        | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    8
  2018-10-19 21:31:28.525598+00:00 | 1ms598\302\265s661ns | r21: sending batch 1 DelRng, 1 BeginTxn, 1 EndTxn to (n1,s1):1               | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    8
  2018-10-19 21:31:28.52561+00:00  | 1ms610\302\265s474ns | sending request to local client                                              | [n1,client=127.0.0.1:52508,user=root,txn=3768a757] |          | dist sender send                  |    8
  2018-10-19 21:31:28.525618+00:00 | 1ms618\302\265s449ns | === SPAN START: /cockroach.roachpb.Internal/Batch ===                        |                                                    |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525624+00:00 | 1ms624\302\265s478ns | 1 DelRng, 1 BeginTxn, 1 EndTxn                                               | [n1]                                               |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525636+00:00 | 1ms636\302\265s184ns | executing 3 requests                                                         | [n1,s1]                                            |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525655+00:00 | 1ms655\302\265s68ns  | read-write path                                                              | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525691+00:00 | 1ms691\302\265s248ns | command queue                                                                | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525729+00:00 | 1ms729\302\265s506ns | read has no clock uncertainty                                                | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.52576+00:00  | 1ms760\302\265s129ns | applied timestamp cache                                                      | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525902+00:00 | 1ms902\302\265s925ns | evaluated request                                                            | [n1,s1,r21/1:/{Table/52-Max}]                      |          | /cockroach.roachpb.Internal/Batch |    9
  2018-10-19 21:31:28.525959+00:00 | 1ms959\302\265s185ns | fast path completed                                                          | [n1,client=127.0.0.1:52508,user=root]              |          | flow                              |    3
  2018-10-19 21:31:28.525977+00:00 | 1ms977\302\265s862ns | execution ends                                                               | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.52598+00:00  | 1ms980\302\265s516ns | rows affected: 0                                                             | [n1,client=127.0.0.1:52508,user=root]              |          | sql txn                           |    1
  2018-10-19 21:31:28.526018+00:00 | 2ms18\302\265s606ns  | releasing 1 tables                                                           | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.526038+00:00 | 2ms38\302\265s896ns  | [NoTxn pos:122] executing Sync                                               | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.526246+00:00 | 2ms246\302\265s606ns | [NoTxn pos:123] executing ExecStmt: SET TRACING = off                        | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
  2018-10-19 21:31:28.526253+00:00 | 2ms253\302\265s287ns | executing: SET TRACING = off in state: NoTxn                                 | [n1,client=127.0.0.1:52508,user=root]              |          | session recording                 |    0
(62 rows)

Time: 28.874764ms
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, deleteNode had 2 runtime modes: the normal mode, and the
fast path mode. The fast path mode was activated in certain
circumstances where it was possible to send DeleteRange requests instead
of point deletes to kv.

The fast path mode was quite unusual, however, because it reached into
its input nodes at runtime to check their types and retrieve some
attributes. This made things somewhat difficult in other parts of the
code.

Now, deleteNode is replaced by deleteRangeNode at planning time
(expandPlan in the heuristic planner, and execBuild in the CBO) when
possible. deleteRangeNode has no inputs and owns its own spans,
preventing the trickiness mentioned above.

This incidentally also fixes a bug with the fast path deleter, wherein
previously, the beginning part of the scan would always run since the
deleter's input scanNode would get its startExec method called even
though the fast path would run, triggering the scan.

Closes #31656.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Very good work! thank you.
Just two main comments see below.

> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-:-LXEEmnEDanXc0i2E6hW:b-l4fxbq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @jordanlewis)

___
*[pkg/sql/delete_range.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEDXzGBWODe_sbtkO2:-LXEDXzH4nqLjra5cBLa:by976mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L102)):*
> ```Go
> 
> // BatchedNext implements the batchedPlanNode interface.
> func (d *deleteRangeNode) BatchedNext(params runParams) (bool, error) {
> ```

If you're not planning on implemented the batch interface, then why do you even bother defining the methods? the planNode is valid without them.
___
*[pkg/sql/opt_filters.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE4EaDWY5q8bz_wAP:-LXEE4Eb8eZlGwtQNt7T:b-9bde53) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_filters.go#L278)):*
> ```Go
> 			return plan, extraFilter, err
> 		}
> 	case *deleteRangeNode:
> ```

move to the bottom with other no-ops.
___
*[pkg/sql/opt_limits.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEDygtDS7fd7S7cR4M:-LXEDygu0EtxA9RjYucY:b-9bde53) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_limits.go#L160)):*
> ```Go
> 		// the surrounding query only uses parts of its results.
> 		p.setUnlimited(n.source)
> 	case *deleteRangeNode:
> ```

move to the bottom with other no-ops.
___
*[pkg/sql/opt_needed.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE6oiAAtGo7Zlh-uz:-LXEE6oj6DreL3KN3Y8Y:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_needed.go#L218)):*
> ```Go
> 		setNeededColumns(n.source, allColumns(n.source))
> 
> 	case *deleteRangeNode:
> ```

ditto
___
*[pkg/sql/plan_physical_props.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE_or1PqAHldJNv6J:-LXEE_or1PqAHldJNv6K:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/plan_physical_props.go#L50)):*
> ```Go
> 			return planPhysicalProps(n.source)
> 		}
> 	case *deleteRangeNode:
> ```

ditto
___
*[pkg/sql/walk.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEEdjv0RMJxtcHS7iL:-LXEEdjv0RMJxtcHS7iM:ba3jafx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc107419bdcaad839766495b57001965565bd0b/pkg/sql/walk.go#L510)):*
> ```Go
> 				ext = "fast "
> 			}
> 			v.observer.attr(name, "strategy", ext+n.run.td.desc())
> ```

keep the strategy but remove the fast part. Even `update` has a strategy - the idea is that we want the identity of the table writer in any case.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/delete_range.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXF1D9mAcmE9t2D4hqW:-LXF1D9nCiZVBFwejpFQ:bnsib3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L94)):*
> ```Go
> 	}
> 
> 	return &deleteRangeNode{
> ```

What about all the other fields of `scanNode`, such as `hardLimit`, `reverse`, and `maxResults`?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/delete_range.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXF1D9mAcmE9t2D4hqW:-LXF27yn69zXNM_QXXlx:blfefqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L94)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What about all the other fields of `scanNode`, such as `hardLimit`, `reverse`, and `maxResults`?
</blockquote></details>

Looking at this more, I think this is a bug in the current implementation, but by chance it's never triggered because while the heuristic planner pushes down the limit into the `scanNode`, it's not smart enough to remove the `limitNode`. But if that was removed, the bug would manifest. We should be returning false if `hardLimit` is non-zero.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/sql/delete_range.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXF1D9mAcmE9t2D4hqW:-LXHhFmkA8HAeWrW4hri:brzeqg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L94)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Looking at this more, I think this is a bug in the current implementation, but by chance it's never triggered because while the heuristic planner pushes down the limit into the `scanNode`, it's not smart enough to remove the `limitNode`. But if that was removed, the bug would manifest. We should be returning false if `hardLimit` is non-zero.
</blockquote></details>

Good point. Added the condition for `hardLimit`. I don't think `reverse` can ever be generated in this case, and `maxResults` shouldn't matter either - it's deduced from the spans, not vice versa.
___
*[pkg/sql/delete_range.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEDXzGBWODe_sbtkO2:-LXHhOU76bgEQvbftbmw:baxnq04) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L102)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If you're not planning on implemented the batch interface, then why do you even bother defining the methods? the planNode is valid without them.
</blockquote></details>

This is required - all inputs to rowCountNode need to be a batchedPlanNode. This could be fixed with more expandPlan shenanigans i think, but it seems tricky, and I'll leave it for someone else.
___
*[pkg/sql/opt_filters.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE4EaDWY5q8bz_wAP:-LXHhbsW-c9cLYhXW0Jq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_filters.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

move to the bottom with other no-ops.
</blockquote></details>

Done.
___
*[pkg/sql/opt_limits.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEDygtDS7fd7S7cR4M:-LXHhcJ4BRA7ZtPn5ArK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_limits.go#L160)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

move to the bottom with other no-ops.
</blockquote></details>

Done.
___
*[pkg/sql/opt_needed.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE6oiAAtGo7Zlh-uz:-LXHhfRB6x-0yAK9Mfi2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/opt_needed.go#L218)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/plan_physical_props.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEE_or1PqAHldJNv6J:-LXHhiOR4VSADzpDQDSK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/plan_physical_props.go#L50)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEEdjv0RMJxtcHS7iL:-LXHhmLV5rtdz2hGcNoQ:b-p0is9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc107419bdcaad839766495b57001965565bd0b/pkg/sql/walk.go#L510)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

keep the strategy but remove the fast part. Even `update` has a strategy - the idea is that we want the identity of the table writer in any case.
</blockquote></details>

I don't see the point - what is this adding? The explain is merely made larger without new semantic content.

**Review by knz — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @jordanlewis)

___
*[pkg/sql/delete_range.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXF1D9mAcmE9t2D4hqW:-LXItY9kAq7PC-WEm81R:b-ikyfn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L94)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good point. Added the condition for `hardLimit`. I don't think `reverse` can ever be generated in this case, and `maxResults` shouldn't matter either - it's deduced from the spans, not vice versa.
</blockquote></details>

not so fast about `reverse`:
```
root@127.181.123.209:38339/defaultdb> explain(verbose) delete from t where true order by x desc limit 10 ;
           tree          |  field   | description | columns |      ordering
+------------------------+----------+-------------+---------+---------------------+
  count                  |          |             | ()      |
   └── delete            |          |             | ()      |
        │                | from     | t           |         |
        │                | strategy | deleter     |         |
        └── limit        |          |             | (x)     | x!=NULL; key(x); -x
             │           | count    | 10          |         |
             └── revscan |          |             | (x)     | x!=NULL; key(x); -x
                         | table    | t@primary   |         |
                         | spans    | ALL         |         |
                         | limit    | 10          |         |
```

and

```
root@127.181.123.209:38339/defaultdb> explain(verbose) delete from t where true order by x desc ;
        tree        |  field   | description  | columns |      ordering
+-------------------+----------+--------------+---------+---------------------+
  count             |          |              | ()      |
   └── delete       |          |              | ()      |
        │           | from     | t            |         |
        │           | strategy | fast deleter |         |
        └── revscan |          |              | (x)     | x!=NULL; key(x); -x
                    | table    | t@primary    |         |
                    | spans    | ALL          |         |
(7 rows)
```

Semantically, the direction does not matter if there's no consumer for the rows being deleted (eg just a count) and there is no limit.
However by deciding to turn `revscan` into `scan` you're also saying to the user "I'm going to disregard your ORDER BY hint".

I think it's completely fine but it definitely deserves a comment (and a test).
___
*[pkg/sql/delete_range.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEDXzGBWODe_sbtkO2:-LXIuN8g2GnFIww_K9g8:b-dqvunq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L102)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is required - all inputs to rowCountNode need to be a batchedPlanNode. This could be fixed with more expandPlan shenanigans i think, but it seems tricky, and I'll leave it for someone else.
</blockquote></details>

thanks for reminding me.
___
*[pkg/sql/delete_range.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXIuc2q3fBfUpS6x5A3:-LXIuc2q3fBfUpS6x5A4:b737qhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e1c82db6107006a64586ecfcd7f174288c16921/pkg/sql/delete_range.go#L110)):*
> ```Go
> 	if scan.hardLimit != 0 {
> 		if log.V(2) {
> 			log.Infof(ctx, "delete forced to scan: scan has limit %d", scan.hardLimit)
> ```

cool! But this needs a test.
___
*[pkg/sql/walk.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEEdjv0RMJxtcHS7iL:-LXIuWX_3vnsqrUoHjNw:b2rhhrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc107419bdcaad839766495b57001965565bd0b/pkg/sql/walk.go#L510)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't see the point - what is this adding? The explain is merely made larger without new semantic content.
</blockquote></details>

consistency!

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/sql/delete_range.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXF1D9mAcmE9t2D4hqW:-LXLZb70CD7-BUXL6GRU:bufim0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aaeedd819b75fb14cd6e814524eb48b8642b0fa/pkg/sql/delete_range.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

not so fast about `reverse`:
```
root@127.181.123.209:38339/defaultdb> explain(verbose) delete from t where true order by x desc limit 10 ;
           tree          |  field   | description | columns |      ordering
+------------------------+----------+-------------+---------+---------------------+
  count                  |          |             | ()      |
   └── delete            |          |             | ()      |
        │                | from     | t           |         |
        │                | strategy | deleter     |         |
        └── limit        |          |             | (x)     | x!=NULL; key(x); -x
             │           | count    | 10          |         |
             └── revscan |          |             | (x)     | x!=NULL; key(x); -x
                         | table    | t@primary   |         |
                         | spans    | ALL         |         |
                         | limit    | 10          |         |
```

and

```
root@127.181.123.209:38339/defaultdb> explain(verbose) delete from t where true order by x desc ;
        tree        |  field   | description  | columns |      ordering
+-------------------+----------+--------------+---------+---------------------+
  count             |          |              | ()      |
   └── delete       |          |              | ()      |
        │           | from     | t            |         |
        │           | strategy | fast deleter |         |
        └── revscan |          |              | (x)     | x!=NULL; key(x); -x
                    | table    | t@primary    |         |
                    | spans    | ALL          |         |
(7 rows)
```

Semantically, the direction does not matter if there's no consumer for the rows being deleted (eg just a count) and there is no limit.
However by deciding to turn `revscan` into `scan` you're also saying to the user "I'm going to disregard your ORDER BY hint".

I think it's completely fine but it definitely deserves a comment (and a test).
</blockquote></details>

Added tests.
___
*[pkg/sql/delete_range.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXIuc2q3fBfUpS6x5A3:-LXLZbixEoJclIoghfU3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e1c82db6107006a64586ecfcd7f174288c16921/pkg/sql/delete_range.go#L110)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

cool! But this needs a test.
</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-LXEEdjv0RMJxtcHS7iL:-LXLZ_HBB3llwgSIboQK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbc107419bdcaad839766495b57001965565bd0b/pkg/sql/walk.go#L510)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

consistency!
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34275#-:-LXO-2uY4n6Ti5R6YdRg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
Nice work!

**Pull request merged**
