### PR TITLE
kvcoord: add observability for DistSender circuit breakers

### LINKED ISSUE #119916: kvcoord: DistSender circuit breaker observability
The DistSender circuit breakers added in #118943 don't currently have any observability. At the very least, they should have metrics for the number of tracked and tripped replicas, non-spammy logging when replicas (un)trip, and appropriate trace events. We should also consider returning a wrapper error type with additional information.

Jira issue: CRDB-36385

Epic CRDB-25200

### PR DESCRIPTION
**Pull request by erikgrinaker**
**util/circuit: add `error` parameter for `EventHandler.OnReset`**

This allows the `OnReset` handler to determine whether the circuit breaker was tripped when reset. This can happen e.g. if an async probe succeeds before the breaker has been tripped.

**kvcoord: add DistSender circuit breaker metrics**

This patch adds an initial set of DistSender circuit breaker metrics:

* distsender.circuit_breaker.replicas.count
* distsender.circuit_breaker.replicas.tripped
* distsender.circuit_breaker.replicas.tripped_events
* distsender.circuit_breaker.replicas.probes.running
* distsender.circuit_breaker.replicas.probes.success
* distsender.circuit_breaker.replicas.probes.failure
* distsender.circuit_breaker.replicas.requests.cancelled
* distsender.circuit_breaker.replicas.requests.rejected

**kvcoord: annotate DistSender circuit breaker async contexts**

**kvcoord: improve DistSender circuit breaker errors**

**kvcoord: add logging/tracing for DistSender circuit breakers**

By default, only the trip/reset events are logged. vmodule logs yield:

```
I240316 13:07:33.815949 113 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:899  [T1,Vsystem,n1] 243  launching circuit breaker probe for r68/(n3,s3):3 (tripped=false stall=1.318s error=0s)
I240316 13:07:33.816084 4941 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:811  [T1,Vsystem,n1] 244  sending probe to r68/(n3,s3):3: LeaseInfo [/Table/Max]
I240316 13:07:34.816556 4941 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:813  [T1,Vsystem,n1] 249  probe result from r68/(n3,s3):3: br=<nil> err=ba: LeaseInfo [/Table/Max] RPC error: grpc: context deadline exceeded [code 4/DeadlineExceeded]
E240316 13:07:34.816788 4941 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:873  [T1,Vsystem,n1] 250  r68/(n3,s3):3 circuit breaker tripped: probe timed out: context deadline exceede  (stalled for 2.32s, erroring for 0s)
E240316 13:07:38.023324 5287 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:519  [T1,Vsystem,n1] 535  request rejected by tripped circuit breaker for r68/(n3,s3):3: probe timed out: context deadline exceeded
I240316 13:07:38.024899 9324 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:813  [T1,Vsystem,n1] 550  probe result from r68/(n3,s3):3: br=<nil> err=ba: LeaseInfo [/Table/Max] RPC error: grpc: context canceled [code 1/Canceled]
I240316 13:07:38.025341 9324 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:890  [T1,Vsystem,n1] 556  r68/(n3,s3):3 circuit breaker reset
I240316 13:07:38.025374 9324 kv/kvclient/kvcoord/dist_sender_circuit_breaker.go:906  [T1,Vsystem,n1] 557  stopping circuit breaker probe for r68/(n3,s3):3 (tripped=false lastRequest=1.344s)
```

Resolves #119916.
Epic: none
Release note: None

**kvcoord: use duration helpers in DistSender circuit breakers**

**kvcoord: change DistSender circuit breaker string identifier**

Changes e.g. `r68/(n3,s3):3` to `r68/3:(n3,s3)`.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: I left a collection of comments, but they're all nits and aren't blocking. Feel free to adopt the ones that you think make sense.

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-:-NtbL7-k-TkGjHiT28Uq:brqk235)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @erikgrinaker)

___
*[`-- commits` line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbIWqOBU1ZwPtBj9IO):*
"exceeded"?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbGNwm7o2rc9paOsGs:-NtbGNwm7o2rc9paOsGt:b23mqro) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f51e7b7ad61a447d8395f5f1a1e6d1a6f54759e/pkg/kv/kvclient/kvcoord/dist_sender.go#L264)):*
> ```Go
> 	metaDistSenderCircuitBreakerReplicasProbesRunning = metric.Metadata{
> 		Name:        "distsender.circuit_breaker.replicas.probes.running",
> 		Help:        `The number of currently running DistSender replica circuit breaker probes`,
> ```

nit: for consistency with the other metrics, `s/The number of/Number of/`.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbGdkyAim4tw9cj3xM:-NtbGdkyAim4tw9cj3xN:bj0f9kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f51e7b7ad61a447d8395f5f1a1e6d1a6f54759e/pkg/kv/kvclient/kvcoord/dist_sender.go#L285)):*
> ```Go
> 	metaDistSenderCircuitBreakerReplicasRequestsCancelled = metric.Metadata{
> 		Name:        "distsender.circuit_breaker.replicas.requests.cancelled",
> 		Help:        `Number of requests cancelled when DistSender replica circuit breakers trip`,
> ```

Are these last two metrics "Cumulative number ..."?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbGmJH0Pxdp6YKmsaG:-NtbGmJH0Pxdp6YKmsaH:bj61rag) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f51e7b7ad61a447d8395f5f1a1e6d1a6f54759e/pkg/kv/kvclient/kvcoord/dist_sender.go#L289)):*
> ```Go
> 		Unit:        metric.Unit_COUNT,
> 	}
> ```

tiny nit: consider removing new line between each `metaDistSenderCircuitBreaker`, to mirror formatting above.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbHocL0KR8lwUmX-hi:-NtbHocL0KR8lwUmX-hj:b82yzf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f51e7b7ad61a447d8395f5f1a1e6d1a6f54759e/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L851)):*
> ```Go
> }
> 
> // OnTrip implements circuit.EventHandler.
> ```

This EventHandler integration turned out nicely.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbJLP47rQpCjr7FkRb:-NtbJLP47rQpCjr7FkRc:b-jcmpzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf11f4b0ed947f81dacbc19a5db3a6fd64676bf/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L878)):*
> ```Go
> 		errorSince := r.errorDuration(nowNanos).Truncate(time.Millisecond)
> 		log.Errorf(ctx, "%s circuit breaker tripped: %s (stalled for %s, erroring for %s)",
> 			r.id(), cur, stallSince, errorSince)
> ```

Do you think it's worth computing the `r.id()` string once in `newReplicaCircuitBreaker` and storing it in a field instead of on each call to `id`, now that it's used all over?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 926 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbKGl7DANWHBIaFZCl:-NtbKGl7DANWHBIaFZCm:bhv4yy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf11f4b0ed947f81dacbc19a5db3a6fd64676bf/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L926)):*
> ```Go
> }
> 
> // errorDuration returns the error duration relative to nowNanos.
> ```

Think it's worth using these utilities instead of the raw atomic loads and comparisons throughout? For example, `stallDuration` could be used at the end of `probeStallLoop` to clean up the logic a bit. Same thing with `errorDuration` in `done` and `lastRequestDuration` in `launchProbe` and `gcLoop`.

Only do so if you actually think it cleans up the code.
___
*[`pkg/util/circuit/event_handler.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbG2oz5384e3a34wny:-NtbG2p-2OkpzyRoKza5:b-fyub7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f403e24d798c4c369975c0a386daedf4d5eed57/pkg/util/circuit/event_handler.go#L23)):*
> ```Go
> 	OnProbeLaunched(*Breaker)
> 	OnProbeDone(*Breaker)
> 	OnReset(*Breaker, error)
> ```

nit: `OnReset(_ *Breaker, prev error)`

**Review by erikgrinaker — COMMENTED** [review]
TFTR! Also tacked on a commit to change the `id()` string formatting.

> Reviewed 3 of 4 files at r1, 1 of 5 files at r6, 1 of 3 files at r7, 2 of 3 files at r8, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-:-NtbiwIv0GDG25VEKWcQ:bdk65d8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbGdkyAim4tw9cj3xM:-NtbV5xYA1y2gCHnGjY5:bn41fwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f51e7b7ad61a447d8395f5f1a1e6d1a6f54759e/pkg/kv/kvclient/kvcoord/dist_sender.go#L285)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are these last two metrics "Cumulative number ..."?
</blockquote></details>

Yes, reworded.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 878 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbJLP47rQpCjr7FkRb:-Ntbeol_3zRlhOV21uD3:b-k22fqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf11f4b0ed947f81dacbc19a5db3a6fd64676bf/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L878)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it's worth computing the `r.id()` string once in `newReplicaCircuitBreaker` and storing it in a field instead of on each call to `id`, now that it's used all over?
</blockquote></details>

Given that we can have tens of thousands of these circuit breakers, I think we should prioritize reduced memory usage instead.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 926 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-NtbKGl7DANWHBIaFZCl:-Ntbir1O8nRSJRf2wy6C:b-mtig95) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf11f4b0ed947f81dacbc19a5db3a6fd64676bf/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L926)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Think it's worth using these utilities instead of the raw atomic loads and comparisons throughout? For example, `stallDuration` could be used at the end of `probeStallLoop` to clean up the logic a bit. Same thing with `errorDuration` in `done` and `lastRequestDuration` in `launchProbe` and `gcLoop`.

Only do so if you actually think it cleans up the code.
</blockquote></details>

May as well, it did clean things up a fair bit.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, 1 of 3 files at r7, 2 of 3 files at r8, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120596#-:-NtbpDcd9c2M8B1xz4o0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by erikgrinaker** [comment]
TFTR!

bors r+

**Pull request merged**
