### PR TITLE
exec: remove fallback logic and enhance SupportsVectorized check

### LINKED ISSUE #38458: exec: dist_vectorize test flake
I'm getting the following test flake:
```
------- Stdout: -------
=== PAUSE TestLogic/5node-dist-vec/dist_vectorize
=== CONT  TestLogic/5node-dist-vec/dist_vectorize
--- done: testdata/logic_test/dist_vectorize with config 5node-dist-vec: 11 tests, 1 failures
            logic.go:2338: 
                 
                testdata/logic_test/dist_vectorize:53: SELECT url FROM [EXPLAIN ANALYZE SELECT count(*) FROM kv]
                expected:
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJzMlcGLm0AUxu_9K-SdtjBWR002O6ctPeXQpCRZeiiyzOrDSo0jM-Oyy5L_vaiFGmlnBgIbjz7z5fs-fg_fG9Qixw0_ogL2AygQiIBADAQSILCAlEAjRYZKCdn9ZBCs8xdgIYGyblrdjVMCmZAI7A10qSsEBgf-VOEOeY4yCIFAjpqXVW_TyPLI5ev9r2cgsG94rZjnB53xttXM24gagcAT19lPVJ5oddONu3C6barJSGGFmS6fS_3KvPBT2HkpzavK0-URmRcqSE8EBsmfrErzAoHRE3Hv87koJBZcCxkszut82T5sDo-77ff9zcfLcuMLZq0uRW3PHv03-9_IbS1kjhLzs7zpydyOTmjtH74-rjeHm3v6fu3is3bUfdOofdOCyA_iK--apdGIxnJ2uxa504gcaMR-kFyZhqXRiMbt7GjE7jRiBxqJ33_drknD0mhEYzU7Gok7jcSBxsK_MgtLnxGLu9mxsNzzHapG1Aont_Hf_xx2NxPzAocDq0QrM_wmRdbbDI_bXtcPclR6eEuHh3U9vOoCjsXUKI7OxHQqjszOFuvYqE7M4uSS3AujeGl2Xl7ifGsUr8zOq0uc78ysQsuamJds6p2ePvwOAAD__0aN3zM=
                    
                but found (query options: "") :
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJzcVUFr2zAYve9XmO_UgTJbttOmOnXslMOSkaTsMExRrQ_XzJGMJJeWkv8-bA-WmE3y8FhDj_rk5_ce76HvBaQSuOJ7NMC-AQUCMRBIgEAKBOaQEai1ytEYpdtPesBSPAGLCJSybmw7zgjkSiOwF7ClrRAY7Ph9hRvkAnUYAQGBlpdVR1Prcs_18833RyCwrbk0LJiFLfG6sSxYKYlA4J7b_AFNoBpbt-NWnG3qajAyWGFuy8fSPrMg-hC1XMbyqgpsuUcWRAayA4Ee8lOrsbxAYPRAxvv5WBQaC26VDuendj6tb1e7u8366_bi_TTd-IR5Y0sl_drjP2r_JbmRSgvUKE70Zge3OzpIa3v7-W652l3c0P_nLjlxR8c3LfY3LYxnYRJwKQIaKPuA-u97F__L3nncHSVzdXa9i990Mh53Z51MMj6ZZEQy6ax79V7zffY4OkpjcXZppOPTSEekMZ-9chYeP0dZXJ9dFp49v0FTK2lwsDN__-eo3aUoCuwXr1GNzvGLVnlH0x_XHa4bCDS2v6X9YSn7q1bgMZg6wfEJmA7BsZvZQ5040ZducDpF93wK8-UU5isneOFmXkxhvnZnFXlq4i7ZkDs7vPsRAAD__91L5wM=
                    
                
            logic.go:2370: 
                testdata/logic_test/dist_vectorize:58: error while processing
            logic.go:2371: testdata/logic_test/dist_vectorize:58: too many errors encountered, skipping the rest of the input
```
I can reproduce by running `make stress PKG=./pkg/sql/logictest TESTS='TestLogic//dist_vectorize'` on master

### LINKED ISSUE #38651: distsqlrun: `syncFlowConsumer` unset when running internal executor queries
A panic was discovered in the vectorized flow setup code where `Flow.syncFlowConsumer` was nil. #38557 mitigates this by checking if the consumer is `nil` and returning an error which started producing these errors:
```
I190628 15:59:45.676023 3672 sql/distsql_running.go:180 [intExec=adopt-job] error vectorizing remote flow d6d8146f-f896-41d8-8c17-82bae5f1bbd3, restarting with vectorize=off and ID 10d20b4f-490d-48b6-943a-a1bc791f5102: syncFlowConsumer unset, unable to create materializer
```
These seem like bad plans generated by the distsql physical planner when running internal executor queries (`read-setting` is another example of when this happens). Essentially the node running the internal query generates a plan that says that the final receiver of data of that query should be on the remote node, which is not a state a query should ever be in (how do you get data back to the gateway if the final receiver is on a remote node?).

### PR DESCRIPTION
**Pull request by yuzefovich**
First commit removes fallback logic from vectorized to DistSQL.

The fallback logic has been very fragile and causes some hard to
debug and understand issues. This commit removes it entirely so
that if the vectorized flow encounters a runtime execution error,
the error is returned to the client.

Second commit refactors vectorized flow setup

Setup of the vectorized flow has been refactored to decouple
planning and running steps. This allows us to have a noop
runner to check whether the flow is supported through the
vectorized engine which enhances SupportsVectorized check.

Addresses: #38919.
Fixes: #38458.
Fixes: #38651.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
First commit LGTM. Second commit seems pretty hacky and hard to read and extend. If you want to merge this for now to start testing sooner, that's fine. I put a suggestion inline.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-:-LkeouvY6NJ_EjS-2Qey:bozch9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkepMn37psW-iAnbloY:-LkepMn37psW-iAnbloZ:b-5bhfed) ([raw file](https://github.com/cockroachdb/cockroach/blob/dffb58560f268c15e114f9867e5bb216b0ee5d57/pkg/sql/distsqlrun/column_exec_setup.go#L1358)):*
> ```Go
> 			f.processors[0] = proc
> 		}
> 		metadataSourcesQueue, vectorizedStatsCollectorsQueue, err = setupVectorizedOutput(
> ```

Yikes, this is a pretty monster function call. If you want to merge this for now I'm okay with it, but we can't leave things like this forever.

What about the idea of introducing a new interface for the setup stuff, with 2 implementations? One is the no-op implementation that doesn't start anything async. The other is the real implementation.

**Review by yuzefovich — COMMENTED** [review]
I refactored the second commit. It looks a lot better now. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-:-LkjFmD9C25zFEaUKHaA:b-64ev39)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkepMn37psW-iAnbloY:-LkjEsdi0yt_N27k7bJA:b-gs8foq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dffb58560f268c15e114f9867e5bb216b0ee5d57/pkg/sql/distsqlrun/column_exec_setup.go#L1358)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yikes, this is a pretty monster function call. If you want to merge this for now I'm okay with it, but we can't leave things like this forever.

What about the idea of introducing a new interface for the setup stuff, with 2 implementations? One is the no-op implementation that doesn't start anything async. The other is the real implementation.
</blockquote></details>

Yeah, further refactoring this code would have been my next step, but initially I thought we can just postpone it and merge the way it was in revision 1. I was hoping that other PRs would be merged, so I didn't want to hold off the testing. But since the flow cancelation is still work in progress, there is no reason to merge it as it was. Refactored.

**Review by jordanlewis — COMMENTED** [review]
Would like to see a review from @asubiotto as well but :lgtm: except for a couple of comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-:-LkyjqVPD0mRCEQ6bbn1:bfguo7p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 932 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkyj3FiACC_PuICR65o:-Lkyj3FiACC_PuICR65p:b-3hpsa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L932)):*
> ```Go
> // infrastructure asynchronously as well as to perform some sanity checks.
> type vectorizedFlowRunner interface {
> 	addStreamEndpoint(distsqlpb.StreamID, *colrpc.Inbox, *sync.WaitGroup)
> ```

Small comments on these would be very welcome.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkjsVJe0QkVFWRyQvyS:-LkjsVJe0QkVFWRyQvyT:b-1edtov) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L943)):*
> ```Go
> // to run the flow or do the setup needed to check that the flow is supported
> // through the vectorized engine.
> type vectorizedFlowSetuper struct {
> ```

:smiley: how about `creator` instead of `setuper`? Or something else that's more of a word. `initializer`, etc.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkyjMxf9YjRvHRLAOxr:-LkyjMxf9YjRvHRLAOxs:b-9yfhnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L1403)):*
> ```Go
> }
> 
> func (r *actualVectorizedFlowRunner) runOutbox(
> ```

These seem nearly identical, could you combine into one by passing the `.Run` function in closure into the arguments?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 932 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkyj3FiACC_PuICR65o:-Lkz4XSlAMi5eO0zPOeV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L932)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Small comments on these would be very welcome.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkjsVJe0QkVFWRyQvyS:-Lkyx4VM1I9ml4FJsEC4:bc7hecf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L943)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

:smiley: how about `creator` instead of `setuper`? Or something else that's more of a word. `initializer`, etc.
</blockquote></details>

I like `creator`.

I thought that in English you just take a verb and add "er" suffix, and voila, you've got a noun :D  
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkyjMxf9YjRvHRLAOxr:-Lkz4V376sRuO78de08w:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae76a7cb25e8b77541dd88f7788ad7c80f03d64/pkg/sql/distsqlrun/column_exec_setup.go#L1403)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These seem nearly identical, could you combine into one by passing the `.Run` function in closure into the arguments?
</blockquote></details>

Good point, done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-Lkz8F3z4TADqu7midVk:b-g3tgpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
> ```Go
> 	// this once logic of falling back to DistSQL is bullet-proof.
> 	if evalCtx.SessionData.Vectorize != sessiondata.VectorizeOff {
> 		acc := evalCtx.Mon.MakeBoundAccount()
> ```

Why are we passing in an account bound to the mon? I don't think we should do this, or at least pass in an unlimited account in `SupportsVectorized`.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz5Byt2g7cTS9rdJ0j:-Lkz5Byt2g7cTS9rdJ0k:b-9m553u) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsqlrun/column_exec_setup.go#L942)):*
> ```Go
> 	// runComponent adds a component (either a router or an outbox) to be run
> 	// asynchronously.
> 	runComponent(runFn)
> ```

This `runComponent` method makes it seem like the components will actually be run. Maybe `accumulateAsyncComponent` or something like that?
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1386 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz6aDr1efDzdZIftNH:-Lkz6aDr1efDzdZIftNI:bi0791p) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsqlrun/column_exec_setup.go#L1386)):*
> ```Go
> // actualVectorizedFlowRunner is a vectorizedFlowRunner that sets up all the
> // vectorized infrastructure to be actually run.
> type actualVectorizedFlowRunner struct {
> ```

The naming is a bit confusing to me since we're not actually running anything (only `Flow.Run` will). I think that we should rename `vectorizedFlowRunner` to `flowCreatorHelper` and this to `vectorizedFlowCreatorHelper` or something like that. Nothing better comes to mind but I think it's important we don't insinuate that anything will be run at this stage.
___
*[pkg/sql/distsqlrun/flow.go, line 528 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz30hJB0ORkamc1aJm:-Lkz30hK9rLu3jopjHCq:brwn9oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/28bb1e92852177708440f5796e8c2bf21c0429ef/pkg/sql/distsqlrun/flow.go#L528)):*
> ```Go
> 		f.startables = nil
> 
> 		if f.EvalCtx.SessionData.Vectorize == sessiondata.VectorizeAlways {
> ```

~I think this is necessary, to keep around if this were a standalone commit.~ Actually, taking a look at a later commit, it doesn't seem like this check is done anywhere anymore? It's necessary to be able to run `SET` statements while in `experimental_vectorize=always` mode (otherwise you won't ever be able to leave it). This might be wrong though, since I think that a logic test should be failing if that were the case.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz3PyL-dI0EAG5v4ud:-Lkz3PyL-dI0EAG5v4ue:bp7a7ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b2e7ab683dd4e38840d34088c18e6cfac5d45c/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L77)):*
> ```
> 
> statement ok
> RESET experimental_vectorize
> ```

I think we can remove this

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-LkzNiU47Y7HDuIEjLRZ:bi6cx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are we passing in an account bound to the mon? I don't think we should do this, or at least pass in an unlimited account in `SupportsVectorized`.
</blockquote></details>

Hm, we're creating some components that allocate memory which should be accounted for, so I think we should be passing a memory account. Also, if we have an unlimited account in `SupportsVectorized` which - if it were limited - would get OOM, then the check for support succeeds but then actual setup will fail, so I don't like the idea of having different limits on accounts. Why do you think we shouldn't do this?
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 942 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz5Byt2g7cTS9rdJ0j:-LkzP8xFC-aJpsTiqfAW:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsqlrun/column_exec_setup.go#L942)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This `runComponent` method makes it seem like the components will actually be run. Maybe `accumulateAsyncComponent` or something like that?
</blockquote></details>

I agree, done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1386 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz6aDr1efDzdZIftNH:-LkzPtwu25aFjhXUH9kj:b-7h0uw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsqlrun/column_exec_setup.go#L1386)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The naming is a bit confusing to me since we're not actually running anything (only `Flow.Run` will). I think that we should rename `vectorizedFlowRunner` to `flowCreatorHelper` and this to `vectorizedFlowCreatorHelper` or something like that. Nothing better comes to mind but I think it's important we don't insinuate that anything will be run at this stage.
</blockquote></details>

Yeah, I didn't particularly like the naming myself but didn't have better ideas. I like you suggestions, done.
___
*[pkg/sql/distsqlrun/flow.go, line 528 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz30hJB0ORkamc1aJm:-LkzQFW7DpeIds1edwD6:bhsrap2) ([raw file](https://github.com/cockroachdb/cockroach/blob/28bb1e92852177708440f5796e8c2bf21c0429ef/pkg/sql/distsqlrun/flow.go#L528)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

~I think this is necessary, to keep around if this were a standalone commit.~ Actually, taking a look at a later commit, it doesn't seem like this check is done anywhere anymore? It's necessary to be able to run `SET` statements while in `experimental_vectorize=always` mode (otherwise you won't ever be able to leave it). This might be wrong though, since I think that a logic test should be failing if that were the case.
</blockquote></details>

The check is done right after the call to `SupportsVectorized` within `DistSQLPlanner.setupFlows`.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz3PyL-dI0EAG5v4ud:-LkzQclEBQBta2DJ26MG:bk5e6g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b2e7ab683dd4e38840d34088c18e6cfac5d45c/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L77)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we can remove this
</blockquote></details>

This `RESET` is because of `SET experimental_vectorize = always` a few lines above. Are you suggesting that we run everything from this point on with `always`?
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkzSxMv-zsPffFGG2gM:-LkzSxMv-zsPffFGG2gN:bmfqr6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/13de1e85e0276610ab91146688b14b2f9b54b9c5/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L40)):*
> ```
> 
> # Verify data placement.
> query TTTI rowsort
> ```

For some reason, the output of this query has changed:
```
                testdata/logic_test/dist_vectorize:41: SELECT start_key, end_key, replicas, lease_holder from [SHOW EXPERIMENTAL_RANGES FROM TABLE kw]
                expected:
                    start_key  end_key  replicas  lease_holder
                    NULL       /1       {5}       5
                    /1         /2       {1}       1
                    /2         /3       {2}       2
                    /3         /4       {3}       3
                    /4         /5       {4}       4
                    /5         NULL     {5}       5
                    
                but found (query options: "colnames") :
                    start_key  end_key  replicas  lease_holder
                    /1         /2       {1}       1
                    /2         /3       {2}       2
                    /3         /4       {3}       3
                    /4         /5       {4}       4
                    NULL       /1       {5}       5
                    /5         NULL     {5}       5
```
Both of the outputs are correct, so I just added `rowsort` to get deterministic results.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-:-LkzWDY4-w6bKJmrj-6l:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-LkzUmKK25V74QBByp1d:bpgtu6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, we're creating some components that allocate memory which should be accounted for, so I think we should be passing a memory account. Also, if we have an unlimited account in `SupportsVectorized` which - if it were limited - would get OOM, then the check for support succeeds but then actual setup will fail, so I don't like the idea of having different limits on accounts. Why do you think we shouldn't do this?
</blockquote></details>

That makes sense. I guess it's just the idea of having to pass in a memory account to a function that says it just does a check seems weird (i.e. what is this function doing?). Also if we're running a distributed flow, getting or not getting a memory error here doesn't really change the likelihood of getting a memory error later on (since the memory budget is node-dependent).
___
*[pkg/sql/distsqlrun/flow.go, line 528 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz30hJB0ORkamc1aJm:-LkzW-b-4-ir-5nGk5nd:bnyykjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/28bb1e92852177708440f5796e8c2bf21c0429ef/pkg/sql/distsqlrun/flow.go#L528)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The check is done right after the call to `SupportsVectorized` within `DistSQLPlanner.setupFlows`.
</blockquote></details>

You're right, thanks!
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz3PyL-dI0EAG5v4ud:-LkzW8RqCZubNfsKsLXZ:bbr71aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9b2e7ab683dd4e38840d34088c18e6cfac5d45c/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L77)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This `RESET` is because of `SET experimental_vectorize = always` a few lines above. Are you suggesting that we run everything from this point on with `always`?
</blockquote></details>

No, I just missed the `always` line, thanks!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-LkzYqhd44qRPrdUwQsg:biq13d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That makes sense. I guess it's just the idea of having to pass in a memory account to a function that says it just does a check seems weird (i.e. what is this function doing?). Also if we're running a distributed flow, getting or not getting a memory error here doesn't really change the likelihood of getting a memory error later on (since the memory budget is node-dependent).
</blockquote></details>

Oh, I see, I now share your sentiment, so I added an unlimited account when doing the check.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-LkzwYUU3lfipKfhRvvO:bdpjidw) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Oh, I see, I now share your sentiment, so I added an unlimited account when doing the check.
</blockquote></details>

I thought making a memory account via `MakeStandaloneBudget` would be sufficient, but it still needs a memory monitor. Now, we're creating a monitor and an account on every call to `SupportsVectorized`, and I'm not sure whether it is better than creating a memory account bound to `flowCtx.EvalCtx.Mon`. Thoughts?

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-Ll0-8K_4Yu7gcbXdgAT:bnbamip) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I thought making a memory account via `MakeStandaloneBudget` would be sufficient, but it still needs a memory monitor. Now, we're creating a monitor and an account on every call to `SupportsVectorized`, and I'm not sure whether it is better than creating a memory account bound to `flowCtx.EvalCtx.Mon`. Thoughts?
</blockquote></details>

Making a new monitor is quite cheap and causes no allocations - seems fine to make a new one every time. We can always fix this later if necessary.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-LkzSxMv-zsPffFGG2gM:-Ll0-XcLCgRRI7I7rR_T:b76f16w) ([raw file](https://github.com/cockroachdb/cockroach/blob/13de1e85e0276610ab91146688b14b2f9b54b9c5/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L40)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

For some reason, the output of this query has changed:
```
                testdata/logic_test/dist_vectorize:41: SELECT start_key, end_key, replicas, lease_holder from [SHOW EXPERIMENTAL_RANGES FROM TABLE kw]
                expected:
                    start_key  end_key  replicas  lease_holder
                    NULL       /1       {5}       5
                    /1         /2       {1}       1
                    /2         /3       {2}       2
                    /3         /4       {3}       3
                    /4         /5       {4}       4
                    /5         NULL     {5}       5
                    
                but found (query options: "colnames") :
                    start_key  end_key  replicas  lease_holder
                    /1         /2       {1}       1
                    /2         /3       {2}       2
                    /3         /4       {3}       3
                    /4         /5       {4}       4
                    NULL       /1       {5}       5
                    /5         NULL     {5}       5
```
Both of the outputs are correct, so I just added `rowsort` to get deterministic results.
</blockquote></details>

Seems fine.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-:-Ll00DUGCqL4fYEQsGoK:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39089#-Lkz8F3z4TADqu7midVj:-Ll007dz70SZNJituMEO:bkrelnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/489cfd348bf6fd069b3d7fef6d6c7ebbf0882eda/pkg/sql/distsql_running.go#L140)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Making a new monitor is quite cheap and causes no allocations - seems fine to make a new one every time. We can always fix this later if necessary.
</blockquote></details>

Ok, SGTM.

**Pull request closed without merging**
