### PR TITLE
storage: Temporarily disable preemptive snapshots

### LINKED ISSUE #7659: storage: disable preemptive snapshots (at least for this week)
As discussed with @bdarnell @arjunravinarayan @tamird, we are going to take out preemptive snapshots for this week's beta (and leave them out until we have some lower-level Raft concerns around them sorted out).

The change will be minimal enough so that those wishing to play with preemptive snapshots should be able to do this. We will leave all of the machinery in, but simply not send preemptive snapshots during replica changes.

### PR DESCRIPTION
**Pull request by bdarnell**
Fixes #7659
Updates #7600
Updates #7619

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7674)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7674#-:-KM4uTKWKJbUaJKpUjCi:1417088721)*

**Comment by tschottdorf** [comment]
LGTM. Interesting that we used SendAsync (I guess there isn't a good way to do a blocking send) before.

**Comment by bdarnell** [comment]
Yeah, we don't currently have a way to do a synchronous send. My hope for raft transport errors (#5789) was that we would get a return stream that we could use for acknowledging snapshots, but #7534 took a different strategy. We may need to revisit that (for this reason in addition to the goroutine concerns).

**Comment by tamird** [comment]
LGTM ✈️

**Pull request merged**
