### PR TITLE
cli: unskip TestUnavailableZip

### LINKED ISSUE #53306: cli: TestUnavailableZip failed
[(cli).TestUnavailableZip failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2214740&tab=buildLog) on [master@b0ded83998c7b3b71d433dd93ad35a0fed561d3b](https://github.com/cockroachdb/cockroach/commits/b0ded83998c7b3b71d433dd93ad35a0fed561d3b):

```
=== RUN   TestUnavailableZip
[debug --host=127.0.0.1:34299 --insecure=true zip --cpu-profile-duration=0 /dev/null --timeout=.5s]
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestUnavailableZip426276598
--- FAIL: TestUnavailableZip (10.02s)
    test_log_scope.go:154: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestUnavailableZip426276598
    test_log_scope.go:63: use -show-logs to present logs inline
    datadriven.go:194: output didn't match expected:
        @@ -72,11 +72,12 @@
         requesting data for debug/nodes/1/details... writing: debug/nodes/1/details.json
         requesting data for debug/nodes/1/gossip... writing: debug/nodes/1/gossip.json
         requesting data for debug/nodes/1/enginestats... writing: debug/nodes/1/enginestats.json
         requesting stacks for node 1... writing: debug/nodes/1/stacks.txt
         requesting threads for node 1... writing: debug/nodes/1/threads.txt
        -requesting heap profile for node 1... writing: debug/nodes/1/heap.pprof
        +requesting heap profile for node 1... writing: debug/nodes/1/heap.pprof.err.txt
        +  ^- resulted in ...
         requesting heap files for node 1... writing: debug/nodes/1/heapprof.err.txt
           ^- resulted in ...
         requesting goroutine files for node 1... writing: debug/nodes/1/goroutines.err.txt
           ^- resulted in ...
         requesting log file ...

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestUnavailableZip PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestUnavailableZip.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-3878

### PR DESCRIPTION
**Pull request by aadityasondhi**
cli: make debug zip resilient to single failures

This fixes a regression in debug zip where a timeout failure in calls to
the status server would fail the entire collection of debug zip. We
instead want to continue trying all endpoints instead.

----

cli: unskip TestUnavailableZip

Fixes: https://github.com/cockroachdb/cockroach/issues/53306

Release note: None

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
thanks for tackling this but this needs more work.

 The point of `debug zip` is that it should be able to scrape as much data as possible even when (some) ranges are unavailable. For example, if there are 3 nodes, and nodes n1 and n2 are still available (but n3 is not), it should be possible to retrieve the node-specific data in n1 and n2 still.

You can notice this was true in the original reference output for the test, for example:
```
[node 1] retrieving SQL data for crdb_internal.node_metrics... writing output: debug/nodes/1/crdb_internal.node_metrics.txt... done
[node 1] retrieving SQL data for crdb_internal.node_queries... writing output: debug/nodes/1/crdb_internal.node_queries.txt... done
[node 1] retrieving SQL data for crdb_internal.node_runtime_info... writing output: debug/nodes/1/crdb_internal.node_runtime_info.txt... done
[node 1] retrieving SQL data for crdb_internal.node_sessions... writing output: debug/nodes/1/crdb_internal.node_sessions.txt... done
```

**Comment by aadityasondhi** [comment]
@knz Thanks for pointing that out! Made the changes in a previous commit. PTAL

**Review by knz — APPROVED** [review]
:lgtm: modulo moving the error simplifiation logic to a function specific to TestUnavailableZip.

> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100678#-:-NTPJ317Ac-uho8AfaWi:b77ife4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @dhartunian)

___
*[`pkg/cli/zip_test.go` line 332 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/100678#-NTPIy4JCY4pD9GaR_Tg:-NTPIy4JCY4pD9GaR_Th:b-fe0z63) ([raw file](https://github.com/cockroachdb/cockroach/blob/2100aee3dd83d08ae0f65e481c870e90e5a035cb/pkg/cli/zip_test.go#L332)):*
> ```Go
> 	out = re.ReplaceAllString(out, ``)
> 
> 	// The request for debug/settings is non-deterministic in this test, and fails periodically.
> ```

As we discussed offline, you can put this special case into a function specific to TestUnavailableZip.

**Comment by aadityasondhi** [comment]
Required a rebase off master

**Comment by aadityasondhi** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9713090?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

known flake from https://github.com/cockroachdb/cockroach/issues/101519.

bors r+

**Pull request merged**
