### PR TITLE
sqlstats/insights: fix mem leaks on session close

### LINKED ISSUE #128213: insights: ensure per-session statementBufs are cleared on session close
In the insights subsystem, we store statement execs in a per-session statement buf which is cleared when the ingester processes a Transaction event for the session, signalling the end of the transaction. This can lead to a memory leak if the session is closed mid transaction, as the ingester will never clear the statementBuf for the session.

Ensure on session close that the insights system clears up any memory in use by that session, such as the `statementBuf` in the ingester: https://github.com/cockroachdb/cockroach/blob/feddaea233df5084fe023af9af210e63e8142486/pkg/sql/sqlstats/insights/registry.go#L26

Jira issue: CRDB-40866

### PR DESCRIPTION
**Pull request by xinhaoz**
insights: ensure releasing to Insight pool clears slice

Ensure that when we return objects into the Insight pool
that we release the statmeents in the slice. This fixes
an issue in the logic that returned this object to the pool
which did not nil the `Statements` slice, making it possible
for these slices to grow in capacity in the node's lifetime,
holding onto garbage Statement objects.

This is a lead up to https://github.com/cockroachdb/cockroach/issues/128199 which will likely remove
this pool and reuse the existing statmentBuf pool.

Epic: none
Release note: None

insights: add testing knobs

Add insights specific testing knobs. We'll add some
knobs in later commts.

Epic: none
Release note: None

sqlstats/insights: free memory allocated per session on session close

The insights locking registry buffers statement insight objects
by session id until receiving a transaction insight, when the
buffer is emptied. These buffers can leak if the session is closed
midway through a transaction since the registry will never
receive a transaction event for the session. This commit ensures
we clear any memory allocated in insights for a session by
sending an event to clear the container's session entry, if it
exists, on session close.

A testing knob was added, OnCloseSession, which is called
when the locking registry clears a session.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/128213

Release note (bug fix): Fixes a memory leak where statement
insight objects may leak if the session is closed without
the transaction finishing.

insights: move insights testing knobs from sqlstats

Move some insights testing knobs that were on the
sqlstats testing knobs to insights pkg.

Epic: none

Release note: None

### CODE REVIEW

**Comment by xinhaoz** [comment]
I think we might want to add a memory monitor to the insights system but that work seems a bit more involved (gotta inject some contexts into some funcs) so I think I'd rather get this in first for backportability. LMK what y'all think though.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128400)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mILN8CEfZtkckPqQ4):*
This wording is a bit vague regarding impact. Can you provide a bit more clarity on why this pool is safe to remove? Is it possible that an idiosyncratic workload could generate an insights object for every execution? For instance, if a lot of failures accumulate, do we generate an insight for every single one?

There's a prior issue here that led to some memory pooling changes: https://github.com/cockroachdb/cockroach/issues/89918
Can we run the same benchmark and confirm that we're not making this worse?
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mIYIB2-4PeSTWUAw1):*
nit: release note
___
*[`-- commits` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mKzMoC1n02mE3d6TC):*
nit: space
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3rw8ha3sqTou-PhHvy:-O3rw8ha3sqTou-PhHvz:b3tho8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/ingester.go#L148)):*
> ```Go
> 		} else if e.transaction != nil {
> 			i.registry.ObserveTransaction(e.sessionID, e.transaction)
> 		} else if e.sessionID != (clusterunique.ID{}) {
> ```

There should be a comment here clarifying that this is a "synthetic" event generated in `ClearSession`, otherwise it's confusing as to why this clause can be triggered.
___
*[`pkg/sql/sqlstats/insights/provider.go` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3rwT594llV7tdA0Dvu:-O3rwT594llV7tdA0Dvv:bhkro5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/provider.go#L50)):*
> ```Go
> // ActiveSessions returns the IDs of all sessions that are currently being observed.
> // Used for testing.
> func (p *Provider) ActiveSessions() []clusterunique.ID {
> ```

nit: I would rename this to include a `ForTesting` suffix so that it's not misused in the future.
___
*[`pkg/sql/sqlstats/insights/registry.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3ryQc9E6pBzjVNTUoe:-O3ryQc9E6pBzjVNTUof:b-t918u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/registry.go#L31)):*
> ```Go
> 
> 		// statements can be accessed concurrently in testing.
> 		statements map[clusterunique.ID]*statementBuf
> ```

I'm not sure if the test is adequate motivation to introduce a mutex here. One of the features of the `lockingRegistry` seems to be that it's accessed in a single async task and invoked in batches. This change makes that nature confusing.

Is there a way that the tests can be modified to avoid this?

**Comment by xinhaoz** [comment]
*[`pkg/sql/sqlstats/insights/registry.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3ryQc9E6pBzjVNTUoe:-O3sFCqbEZokwm3if8Qp:b-2f95g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/registry.go#L31)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm not sure if the test is adequate motivation to introduce a mutex here. One of the features of the `lockingRegistry` seems to be that it's accessed in a single async task and invoked in batches. This change makes that nature confusing.

Is there a way that the tests can be modified to avoid this?
</blockquote></details>

One alternative I was thinking about is to introduce a testing knob callback that we can call when the clear session event is processed. We can manage the sync structure in the test, then and not in the locking registry directly. WDYT?

**Comment by xinhaoz** [comment]
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mILN8CEfZtkckPqQ4):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This wording is a bit vague regarding impact. Can you provide a bit more clarity on why this pool is safe to remove? Is it possible that an idiosyncratic workload could generate an insights object for every execution? For instance, if a lot of failures accumulate, do we generate an insight for every single one?

There's a prior issue here that led to some memory pooling changes: https://github.com/cockroachdb/cockroach/issues/89918
Can we run the same benchmark and confirm that we're not making this worse?
</blockquote></details>

The fix for that issue was applied when we generated insights objects at the statement level (it wrapped each stmt insight object). Now we generate an insight object per txn. Initial reasoning for deleting this was that we don't pool the allocation for Statement and Transaction objects, which are created more or just as frequently as this object is. The PR addressing the initial memory issue added pooling in some other areas so it could be that this specific one was not as impactful. Maybe it does not hurt to keep it around for the problematic workloads you described? I think we should be pooling the Statement and Transaction objects in the insights package if we are doing it here for this, thoughts?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128400)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kyle-a-wong)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mILN8CEfZtkckPqQ4):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

The fix for that issue was applied when we generated insights objects at the statement level (it wrapped each stmt insight object). Now we generate an insight object per txn. Initial reasoning for deleting this was that we don't pool the allocation for Statement and Transaction objects, which are created more or just as frequently as this object is. The PR addressing the initial memory issue added pooling in some other areas so it could be that this specific one was not as impactful. Maybe it does not hurt to keep it around for the problematic workloads you described? I think we should be pooling the Statement and Transaction objects in the insights package if we are doing it here for this, thoughts?
</blockquote></details>

Thought about a little more and ran some ycsbA to look at the heap. I think we should pursue pooling the insight Statement and Transaction objects. Going to do that in a separate PR and keep this PR ot just clearing the object when we return it to the pool, without adding or removing things :) 
___
*[`pkg/sql/sqlstats/insights/registry.go` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3ryQc9E6pBzjVNTUoe:-O3seK8O1WBCW59hhFPf:b-ar4t7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/registry.go#L31)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

One alternative I was thinking about is to introduce a testing knob callback that we can call when the clear session event is processed. We can manage the sync structure in the test, then and not in the locking registry directly. WDYT?
</blockquote></details>

Going to pursue this.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128400)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kyle-a-wong)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mIYIB2-4PeSTWUAw1):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: release note
</blockquote></details>

Done
___
*[`-- commits` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3mKzMoC1n02mE3d6TC):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: space
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-O3rw8ha3sqTou-PhHvy:-O3stGxDBo6DtHuvzOb4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/179d1cb1850a9d2e26d91632b310ce98c8bcacec/pkg/sql/sqlstats/insights/ingester.go#L148)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

There should be a comment here clarifying that this is a "synthetic" event generated in `ClearSession`, otherwise it's confusing as to why this clause can be triggered.
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
nice work. thanks for the separate commits. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128400#-:-O4S3B3M8uWcHf9Bu7wd:by83n81)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kyle-a-wong)

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
