### PR TITLE
Revert "storage,libroach: update MVCCIncrementalIterator to look at every updated key"

### PR DESCRIPTION
**Pull request by pbardea**
Reverts cockroachdb/cockroach#45163

To stop the errors we're seeing on #45524. Will investigate further once it's off master.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45535)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by pbardea** [comment]
Bors r+

**Comment by pbardea** [comment]
ah, bors was crashing due to license/cla checks. Should be good now.
bors r+

**Pull request merged**
