### PR TITLE
settings/cluster: remove v2.1 and add v19.2

### PR DESCRIPTION
**Pull request by andreimatei**
This PR introduces the cluster version corresponding to the 19.2 release. As a precursor, I've had to remove all the versions below 19.1 - we have logic verifying that there's no versions that are "always active" - as everything included in the 19.1 release would be. See individual commits.

I want to backport to 19.2 everything here other than the "remove dead code after VersionSideloadedStorageNoReplicaID" commit.

### CODE REVIEW

**Comment by andreimatei** [comment]
@petermattis and @dt can you please look the first commit and see if there's more cleanup to do? I don't really know what I was doing.

**Comment by andreimatei** [comment]
@tbg in the 2nd commit I don't know what to do with the tests using VersionUnreplicatedRaftTruncatedState. Any suggestion or patch...

**Comment by andreimatei** [comment]
Nvm about the backport; I've done a minimal version on release-19.2 in https://github.com/cockroachdb/cockroach/pull/41935

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/storage/replica_proposal.go, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3RWFN6-QQUpLiOssf:-Ls3RWFO1K-2n026Mu9b:bwn0m0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/replica_proposal.go#L456)):*
> ```Go
> 	// read these SSTs, so it is safe to use https://github.com/facebook/rocksdb/pull/4172
> 	// to avoid needing the global seq_no edits and the copies they required.
> 	canSkipSeqNo := st.Version.IsActive(cluster.VersionUnreplicatedRaftTruncatedState)
> ```

You are braver than I am. Rather than plumb through the removal of `skipWritingSeqNo`, I'd change this commit to be minimal and replace the line above with:

```
// TODO(peter): Plumb through removal of `skipWritingSeqNo` in `Engine.IngestExternalFiles`.
const canSkipSeqNo = true
```

I'm recommending this even though you already did the plumbing because of the fragile usage of multiple boolean parameter. Get one wrong and boom, bad performance or worse.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @nvanbenschoten, @petermattis, and @tbg)

___
*[c-deps/libroach/db.cc, line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3gB6g-MTJB1il95HJ:-Ls3gB6g-MTJB1il95HK:b6poetn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/c-deps/libroach/db.cc#L856)):*
> ```cpp
>   // will not be used to read these SSTs.
>   //
>   // RocksDB checks the option allow_global_seqno and, if it is false, returns
> ```

pls tell me if anything out of this comment should remain
___
*[pkg/storage/replica_proposal.go, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3RWFN6-QQUpLiOssf:-Ls3fZC7CByPq4xKzH4M:b-1z7x9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/replica_proposal.go#L456)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You are braver than I am. Rather than plumb through the removal of `skipWritingSeqNo`, I'd change this commit to be minimal and replace the line above with:

```
// TODO(peter): Plumb through removal of `skipWritingSeqNo` in `Engine.IngestExternalFiles`.
const canSkipSeqNo = true
```

I'm recommending this even though you already did the plumbing because of the fragile usage of multiple boolean parameter. Get one wrong and boom, bad performance or worse.
</blockquote></details>

I no longer want to backport this PR, so I'd much rather brave ahead. Does this change your mind?
There's only 3 calls to this method...

And yes, two bools - bad idea. Even one bool - bad idea!

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @tbg)

___
*[c-deps/libroach/db.cc, line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3gB6g-MTJB1il95HJ:-Ls3go3C9l6tJkL__dK9:b-cuz3sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/c-deps/libroach/db.cc#L856)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls tell me if anything out of this comment should remain
</blockquote></details>

I think much of the comment should remain to explain why we're setting these values the way they are. Also, `allow_file_modifications` is now unused. Are you sure you don't want the Storage Team to take over this part of the PR? We'll do it up right. I promise.
___
*[pkg/storage/replica_proposal.go, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3RWFN6-QQUpLiOssf:-Ls3h2Yb1s2zXOXjaEDc:b-rchr6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/replica_proposal.go#L456)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I no longer want to backport this PR, so I'd much rather brave ahead. Does this change your mind?
There's only 3 calls to this method...

And yes, two bools - bad idea. Even one bool - bad idea!
</blockquote></details>

Yes, that does change my mind and makes me much more comfortable with making this change. See my other comment, though. I think you can get rid of the `allowFileModifications` parameter too.

**Review by andreimatei — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, @petermattis, and @tbg)

___
*[c-deps/libroach/db.cc, line 856 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3gB6g-MTJB1il95HJ:-Ls3moD9BRuvwR1lpsgK:b6325xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/c-deps/libroach/db.cc#L856)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think much of the comment should remain to explain why we're setting these values the way they are. Also, `allow_file_modifications` is now unused. Are you sure you don't want the Storage Team to take over this part of the PR? We'll do it up right. I promise.
</blockquote></details>

Please see now. Changed the phrasing only so slightly to what I believe makes more sense (if I understand things correctly).
___
*[pkg/storage/replica_proposal.go, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-Ls3RWFN6-QQUpLiOssf:-Ls3nHZz5pVKDJoq2dG1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/replica_proposal.go#L456)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, that does change my mind and makes me much more comfortable with making this change. See my other comment, though. I think you can get rid of the `allowFileModifications` parameter too.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
@ajwerner, the last commit (bumping BinaryMinimumSupportedVersion to 19.2) is breaking `TestUpgradeFromPreemptiveSnapshot`. That test insists on bootstrapping a 19.1 and then upgrading it to the current version, but that's no longer possible. It's unclear to me if I can simply delete the test...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-Ls432Q72YMu_5K62BdR:b-wq57dz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, @petermattis, and @tbg)

**Comment by ajwerner** [comment]
> @ajwerner, the last commit (bumping BinaryMinimumSupportedVersion to 19.2) is breaking `TestUpgradeFromPreemptiveSnapshot`. That test insists on bootstrapping a 19.1 and then upgrading it to the current version, but that's no longer possible. It's unclear to me if I can simply delete the test...


I would quite like to retain the ability to test the upgrade from preemptive snapshots in the 19.2 branch. In the 20.1 branch I agree that it does not make sense.

**Comment by tbg** [comment]
@andreimatei that test should get to set any min supported version it wants. If it can't do that today, let's add an option for that, similar to https://github.com/cockroachdb/cockroach/blob/82d6d3f4b7d7bc34994710d1c811532486dacef6/pkg/storage/client_raft_test.go#L5161-L5164

**Review by tbg — APPROVED** [review]
I didn't review the seqno commit, leaving that to Peter. LGTM is assuming resolution of the open issues and LGTM from respective stakies (stakeholders). Thanks for taking this on, @andreimatei!

> Reviewed 10 of 10 files at r2, 9 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-LsHQ0md8VEJ9A_HZvZw:ba7jd1x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @petermattis)

___
*[pkg/server/version_cluster_test.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHQoC11SdEVqq-_IZv:-LsHQoC11SdEVqq-_IZw:bth8sbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/server/version_cluster_test.go#L191)):*
> ```Go
> }
> 
> // NOTE(andrei): I've commented out this test when removing
> ```

Remove it - it'd be nice to retain some testing for the migration specifically here, 
___
*[pkg/storage/store_bootstrap.go, line 236 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSZDe7rO59SQWFkZq:-LsHSZDe7rO59SQWFkZr:b-a1nf6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/storage/store_bootstrap.go#L236)):*
> ```Go
> 			hlc.Timestamp{}, /* gcThreshold */
> 			bootstrapVersion,
> 			truncStateType,
> ```

This parameter should no longer exist, right? Similarly there should be no way to write such a trunc state any more. It is only ever read in the upgrade path.
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSiS9DwxwjY1ub51Y:-LsHSiS9DwxwjY1ub51Z:bcn7qnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/batcheval/cmd_truncate_log.go#L142)):*
> ```Go
> 
> 	if !useNewUnreplicatedTruncatedStateKey {
> 		return pd, MakeStateLoader(cArgs.EvalCtx).SetLegacyRaftTruncatedState(ctx, batch, cArgs.Stats, tState)
> ```

SetLegacy... should go
___
*[pkg/storage/batcheval/truncate_log_test.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHTOUEC-dRw5hOYLLe:-LsHTOUFCKC538yhXRMF:b-gpy88d) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/storage/batcheval/truncate_log_test.go#L84)):*
> ```Go
> // NOTE(andrei): I've commented out this test when removing
> // VersionUnreplicatedRaftTruncatedState cluster version. I think the test needs
> // to stay for this special migration, but I'm not sure how it needs to evolve.
> ```

This test should be relatively easy to adopt, you just remove the case `hasVersionBumped == false` which should remove any reference to cluster versions. The evaluation will always attempt to unreplicate the trunc state if it finds it replicated (=legacy).

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSiS9DwxwjY1ub51Y:-LsHkLQ57Y7JNekW_ZiF:btfwv15) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/batcheval/cmd_truncate_log.go#L142)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

SetLegacy... should go
</blockquote></details>

Should it? Cause I think it's still used for ranges that haven't undergone the migration, no?

**Review by petermattis — APPROVED** [review]
First commit :lgtm:. I didn't look at the other commits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-LsHlxy08NPFZ-yIcBQw:btb3a48)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @tbg)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSiS9DwxwjY1ub51Y:-LsHo_FYBB_b5oUlHgl5:b-cj4qan) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/batcheval/cmd_truncate_log.go#L142)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Should it? Cause I think it's still used for ranges that haven't undergone the migration, no?
</blockquote></details>

But a range that hasn't undergone the migration will undergo the migration with the next truncation (now that the version is always on), so what would possibly try to *write* an old unreplicated state? I'd expect it to be read only. You can change my mind by finding an offending caller...

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @tbg)

___
*[pkg/server/version_cluster_test.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHQoC11SdEVqq-_IZv:-LsHmq97AjsHqFoOt2gI:b-b5ho2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/server/version_cluster_test.go#L191)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Remove it - it'd be nice to retain some testing for the migration specifically here, 
</blockquote></details>

Did you want to say something more here? :)
Removed it...
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSiS9DwxwjY1ub51Y:-LsHpcqxCBM3eHEvfMsA:bg8kov2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/batcheval/cmd_truncate_log.go#L142)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

But a range that hasn't undergone the migration will undergo the migration with the next truncation (now that the version is always on), so what would possibly try to *write* an old unreplicated state? I'd expect it to be read only. You can change my mind by finding an offending caller...
</blockquote></details>

Here:
https://github.com/cockroachdb/cockroach/blob/0b9e3b4fb1f75ad8792a35981997f6f2e448ccb2/pkg/storage/batcheval/cmd_end_transaction.go#L978
___
*[pkg/storage/batcheval/truncate_log_test.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHTOUEC-dRw5hOYLLe:-LsHmhxY00eT4jHq8gV0:bmwxkt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/storage/batcheval/truncate_log_test.go#L84)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This test should be relatively easy to adopt, you just remove the case `hasVersionBumped == false` which should remove any reference to cluster versions. The evaluation will always attempt to unreplicate the trunc state if it finds it replicated (=legacy).
</blockquote></details>

please see now

**Review by tbg — APPROVED** [review]
> Reviewed 14 of 14 files at r9, 9 of 9 files at r10, 4 of 4 files at r11, 2 of 2 files at r12, 4 of 4 files at r13, 1 of 1 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, @dt, and @nvanbenschoten)

___
*[pkg/server/version_cluster_test.go, line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHQoC11SdEVqq-_IZv:-LsHqSJ1CCMDNUm5-Ms_:btjr3u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/server/version_cluster_test.go#L191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Did you want to say something more here? :)
Removed it...
</blockquote></details>

Oops. I meant to say: but we have tests both for the eval and below-raft portion of this, so I don't think it can really rot.
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSiS9DwxwjY1ub51Y:-LsHqgog4-QpI5D4rw_G:b-udo0vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4291b659adbef46d511cb40bc53a2348a4ac30/pkg/storage/batcheval/cmd_truncate_log.go#L142)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Here:
https://github.com/cockroachdb/cockroach/blob/0b9e3b4fb1f75ad8792a35981997f6f2e448ccb2/pkg/storage/batcheval/cmd_end_transaction.go#L978
</blockquote></details>

Ah! Fair enough.

**Review by andreimatei — COMMENTED** [review]
@lucy-zhang @jordanlewis should I remove the `local-mixed-19.1-19.2` config for logictests?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-LsIAoDd2DRq9vNyMwOv:bl75ujh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @tbg)

**Review by tbg — COMMENTED** [review]
> Reviewed 5 of 5 files at r16, 1 of 1 files at r17, 5 of 5 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, @dt, and @nvanbenschoten)

**Review by bdarnell — COMMENTED** [review]
LGTM, although I don't think it's really necessary to force such aggressive removal of legacy migrations. But if we're going to do it, I suggest that the test be conditioned on a greater-than-zero "unstable" version component. Otherwise it will always need to be skipped for the official release. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-LsIud790MkWh81ooyX9:b-sifu42)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @dt, and @nvanbenschoten)

___
*[pkg/settings/cluster/cockroach_versions.go, line 293 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsItb5-EsybUC48k0Vy:-LsItb5-EsybUC48k0Vz:be7wwyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c98758b9d3c9ecc3bfb3a3dc6754ab9971f14d57/pkg/settings/cluster/cockroach_versions.go#L293)):*
> ```Go
> 	// 	Version: roachpb.Version{Major: 2, Minor: 0, Unstable: 14},
> 	// },
> 	// Removed.
> ```

Leaving these in with comments seems silly. It might have been useful when there were gaps in the sequence but if we're going to remove these we should just remove them. 
___
*[pkg/storage/replica_raft.go, line 1709 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsIu0Hx5XdY8RH55PQA:-LsIu0Hx5XdY8RH55PQB:boxcz34) ([raw file](https://github.com/cockroachdb/cockroach/blob/c98758b9d3c9ecc3bfb3a3dc6754ab9971f14d57/pkg/storage/replica_raft.go#L1709)):*
> ```Go
> 
> 			// NB: before the first log truncation evaluated under the
> 			// cluster version which activates this code (see anchor below) this
> ```

This comment also appears to be obsolete.

**Review by andreimatei — COMMENTED** [review]
> I don't think it's really necessary to force such aggressive removal of legacy migrations. But if we're going to do it, I suggest that the test be conditioned on a greater-than-zero "unstable" version component. Otherwise it will always need to be skipped for the official release.

I'll think about it separately

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-:-LsSQQCg3lM3nMhNOOFf:b-9ls773)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @bdarnell, @dt, @nvanbenschoten, and @tbg)

___
*[pkg/settings/cluster/cockroach_versions.go, line 293 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsItb5-EsybUC48k0Vy:-LsSPhR19Vvyonp-cMrl:b-oo6f9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c98758b9d3c9ecc3bfb3a3dc6754ab9971f14d57/pkg/settings/cluster/cockroach_versions.go#L293)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Leaving these in with comments seems silly. It might have been useful when there were gaps in the sequence but if we're going to remove these we should just remove them. 
</blockquote></details>

ok, I've added a commit that gets rid of all of the dead one except the one about unreplicating the truncation state, which is still referenced in comments elsewhere
___
*[pkg/storage/replica_raft.go, line 1709 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsIu0Hx5XdY8RH55PQA:-LsSQH_aEYEr1cs77qQc:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c98758b9d3c9ecc3bfb3a3dc6754ab9971f14d57/pkg/storage/replica_raft.go#L1709)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This comment also appears to be obsolete. 
</blockquote></details>

removed
___
*[pkg/storage/store_bootstrap.go, line 236 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41931#-LsHSZDe7rO59SQWFkZq:-LsSQJjq0vDFO0paxRc7:b4vmrom) ([raw file](https://github.com/cockroachdb/cockroach/blob/163449d1080be3a9724c2223da87c48828fc7c20/pkg/storage/store_bootstrap.go#L236)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This parameter should no longer exist, right? Similarly there should be no way to write such a trunc state any more. It is only ever read in the upgrade path.
</blockquote></details>

as discussed elsewhere, it's still used

**Comment by andreimatei** [comment]
flaked on #42020

bors r+

**Pull request merged**
