### PR TITLE
 backupccl: refactor backup/restore processors to use ProcessorBase

### PR DESCRIPTION
**Pull request by pbardea**
This PR refactors the remaining processors used in backup/restore to use ProcessorBase.

Informs https://github.com/cockroachdb/cockroach/issues/57293.

See individual commits.

### CODE REVIEW

**Comment by pbardea** [comment]
I'm marking this as draft again. I've been rethinking the general approach for these today and want to try another approach -- please hold off reviewing.

**Comment by pbardea** [comment]
This should be ready for review. Will create another PR for the backfiller processors.

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57128)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by pbardea** [comment]
TFTR!
bors r=adityamaru

**Pull request merged**
