### PR TITLE
roachtest: update orm blacklists to remove some expected failures

### LINKED ISSUE #37596: roachtest: hibernate failed
SHA: https://github.com/cockroachdb/cockroach/commits/58c567a325056033b326cb9c4ed9ba490e8956da

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=hibernate PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1296592&tab=buildLog

```
The test failed on branch=master, cloud=gce:
	hibernate.go:314,hibernate.go:325,test.go:1251: 
		Tests run on Cockroach v19.2.0-alpha.00000000-489-g58c567a
		Tests run against Hibernate 5.4.2
		8455 Total Tests Run
		7980 tests passed
		475 tests failed
		0 tests passed unexpectedly
		164 tests failed unexpectedly
		3 tests expected failed, but not run
		For a full summary look at the hibernate artifacts 
		
		An updated blacklist (hibernateBlackList19_2) is available in the artifacts' hibernate log
	cluster.go:1038,context.go:89,cluster.go:1027,asm_amd64.s:522,panic.go:397,test.go:788,test.go:778,hibernate.go:314,hibernate.go:325,test.go:1251: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1296592-hibernate --oneshot --ignore-empty-nodes: exit status 1 1: dead
		Error:  1: dead

```

### LINKED ISSUE #38179: roachtest: psycopg failed
SHA: https://github.com/cockroachdb/cockroach/commits/db6d4425d65bdb027624972ccb19d7aad0bc57cc

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=psycopg PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1339372&tab=buildLog

```
The test failed on branch=master, cloud=gce:
	psycopg.go:249,psycopg.go:261,test.go:1248: 
		Tests run on Cockroach v19.2.0-alpha.20190606-115-gdb6d442
		Tests run against Pyscopg 2_8_3
		674 Total Tests Run
		385 tests passed
		289 tests failed
		95 tests skipped
		1 test ignored
		1 test passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		For a full summary look at the psycopg artifacts. 
		
		An updated blacklist (psycopgBlackList19_2) is available in the logs

```

### PR DESCRIPTION
**Pull request by jordanlewis**
Upgraded support for int2 and int4 datatypes in #37295 caused us to pass some more tests. This PR updates the blacklists to remove their expected failures.

Closes #37596.
Closes #38179.

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38186)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/cmd/roachtest/psycopg_blacklist.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38186#-Lhab1TI-_uhibP1Apji:-Lhab1TJE10ZerKCS5Em:b-ht6wmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/056afc72397974ed9489bf11f16ac8e2fc281a67/pkg/cmd/roachtest/psycopg_blacklist.go#L287)):*
> ```Go
> 	"tests.test_types_basic.TypesBasicTests.testEmptyArray":                                                  "23299",
> 	"tests.test_types_basic.TypesBasicTests.testEmptyArrayRegression":                                        "36179",
> 	"tests.test_types_basic.TypesBasicTests.testGenericArrayNull":                                            "25123",
> ```

Is this supposed to be in 19.1 or 19.2?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38186)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir)

___
*[pkg/cmd/roachtest/psycopg_blacklist.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38186#-Lhab1TI-_uhibP1Apji:-Lher_1lA76X19kIFHIR:b-r9blc) ([raw file](https://github.com/cockroachdb/cockroach/blob/056afc72397974ed9489bf11f16ac8e2fc281a67/pkg/cmd/roachtest/psycopg_blacklist.go#L287)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is this supposed to be in 19.1 or 19.2?
</blockquote></details>

Oops, good point. Done - made a new 19.2 list.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38186#-:-LhfOG1G14EpnYT5yh91:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Pull request merged**
