### PR TITLE
sql: implement ConstructZigzagJoin in distsql_spec_exec_factory

### PR DESCRIPTION
**Pull request by cucaroach**
Informs #47473

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
nit: link to #47473 in the PR description.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-:-MoFrl6c5mK3QP4RqxKA:b-jpij25)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 708 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFrMf72XRKpalIhAho:-MoFrMf72XRKpalIhAhp:b5cb79b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L708)):*
> ```Go
> ) (exec.Node, error) {
> 
> 	// RFC: guessing it doesn't make sense to distribute zigzag...
> ```

Looks good to me, I'd just leave a comment saying that we currently choose to not distribute zigzag joins.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoFs6-786dcNCA47X0y:bta63ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
> ```Go
> }
> 
> func (e *distSQLSpecExecFactory) constructZigzagJoin(
> ```

Currently there is a lot of duplication between `constructZigzagJoin` and `DistSQLPlanner.createPlanForZigzagJoin`. I'd encourage you to introduce `zigzagPlanningInfo` or something that would encompass all information needed to create a zigzag joiner spec and pass that as an argument to `DistSQLPlanner.planZigzagJoin`. This will allow for two factories to have different instantiation of `zigzagPlanningInfo`, yet most of the code will be in a single place (`planZigzagJoin`).
___
*[pkg/sql/distsql_spec_exec_factory.go, line 833 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFqxX99qrn9kHMYXrN:-MoFqxX99qrn9kHMYXrO:bnxbhzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L833)):*
> ```Go
> 	}}
> 
> 	// RFC: why isn't reqOrdering used?  Should it be used here?
> ```

Yeah, it should be, for the cleanliness purposes, but it would not change the behavior - since we do not distribute the zigzag joins, we have only a single zigzag join processor, so it automatically maintains the req ordering if necessary. (This req ordering is only used when merging multiple streams into one in the input synchronizer.) If you go into `AddNoInputStage` and then into `SetMergeOrdering` you'll see that we use an empty req ordering if there is a single processor in the stage (i.e. that stage is not distributed). Still, it'd be cleaner to use the proper `reqOrdering` here.
___
*[pkg/sql/opt/exec/execbuilder/testdata/zigzag_join, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFsswL4X5Gd6m1YkIE:-MoFsswL4X5Gd6m1YkIF:b-k8brzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/opt/exec/execbuilder/testdata/zigzag_join#L1)):*
> ```
> # LogicTest: local local-spec-planning
> ```

I'd also add a query that uses a zigzag join into `experimental_distsql_planning` file (where we have `always` mode).

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoGDRmt1LqN5aBcmqR0:bduyiq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Currently there is a lot of duplication between `constructZigzagJoin` and `DistSQLPlanner.createPlanForZigzagJoin`. I'd encourage you to introduce `zigzagPlanningInfo` or something that would encompass all information needed to create a zigzag joiner spec and pass that as an argument to `DistSQLPlanner.planZigzagJoin`. This will allow for two factories to have different instantiation of `zigzagPlanningInfo`, yet most of the code will be in a single place (`planZigzagJoin`).
</blockquote></details>

I thought we discussed this and decided copying would be better since we're gonna throw away the old code and we don't want
to introduce bugs into the old code with the refactoring.   That said I agree it would be cleaner and if we make improvements to to the zigzag it would be nice not to have to do it twice.    If we want to do it this way why not just have dist_spec_exec_factory just turn the factory args into a zigzagJoinNode and call createPlanForZigzagJoin?   Seems like that would be the most straight forward way to do it with least amount of risk of breaking old code.   
___
*[pkg/sql/distsql_spec_exec_factory.go, line 833 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFqxX99qrn9kHMYXrN:-MoGFU7z55hdtO4THVO8:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L833)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, it should be, for the cleanliness purposes, but it would not change the behavior - since we do not distribute the zigzag joins, we have only a single zigzag join processor, so it automatically maintains the req ordering if necessary. (This req ordering is only used when merging multiple streams into one in the input synchronizer.) If you go into `AddNoInputStage` and then into `SetMergeOrdering` you'll see that we use an empty req ordering if there is a single processor in the stage (i.e. that stage is not distributed). Still, it'd be cleaner to use the proper `reqOrdering` here.
</blockquote></details>

:+1: 
___
*[pkg/sql/opt/exec/execbuilder/testdata/zigzag_join, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFsswL4X5Gd6m1YkIE:-MoGFYeS8MIGVmXk7He1:b6161zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/opt/exec/execbuilder/testdata/zigzag_join#L1)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'd also add a query that uses a zigzag join into `experimental_distsql_planning` file (where we have `always` mode).
</blockquote></details>

Ha! I did that but removed it because I thought it was overkill.   I confirmed in a debugger the logic test used the new factory but I agree it would be nice to have some tests under always mode.   I guess duplicating tests into the experiment_distsql_planning for now is fine since we'll blow it away eventually.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoGHhGF0oK5CmxoE05f:b-dfgoh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I thought we discussed this and decided copying would be better since we're gonna throw away the old code and we don't want
to introduce bugs into the old code with the refactoring.   That said I agree it would be cleaner and if we make improvements to to the zigzag it would be nice not to have to do it twice.    If we want to do it this way why not just have dist_spec_exec_factory just turn the factory args into a zigzagJoinNode and call createPlanForZigzagJoin?   Seems like that would be the most straight forward way to do it with least amount of risk of breaking old code.   
</blockquote></details>

Going further zigzag join is probably so simple why don't we just do this:

```go
func (e *distSQLSpecExecFactory) ConstructZigzagJoin(...) (exec.Node, error) {
  zigzagNode := constructZigzagNode(...factory args...)
  return e.dsp.createPlanForZigzagJoin(ctx, zigzagNode,...)
}
```

Essentially I'm arguing since zigzag isn't very "disty" it should just use the old code because we aren't gaining anything by doing it differently.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoGJNWp6lA3-hLjO6wZ:brrbo4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Going further zigzag join is probably so simple why don't we just do this:

```go
func (e *distSQLSpecExecFactory) ConstructZigzagJoin(...) (exec.Node, error) {
  zigzagNode := constructZigzagNode(...factory args...)
  return e.dsp.createPlanForZigzagJoin(ctx, zigzagNode,...)
}
```

Essentially I'm arguing since zigzag isn't very "disty" it should just use the old code because we aren't gaining anything by doing it differently.   
</blockquote></details>

Hmm not so sure about that now, the old way used scanNodes and a bunch of other intermediate allocations/structures and the new way eliminates that overhead.    Let me look at it some more.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoGjbdADpyS7C_fZH-q:b-dqrl5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
> I thought we discussed this and decided copying would be better since we're gonna throw away the old code and we don't want to introduce bugs into the old code with the refactoring.

Sorry, I might have been unclear. I think we should aim to not change the behavior (i.e. preserve the current physical planning heuristics as much as possible, which in this case means not distributing the zigzag joins); however, I'm not a fan of the idea of copying a bunch of essentially duplicated code. So what I'm suggesting is to do something similar to d55f5eb675dbb2a374537f0d628bd2e16b36df2c.

Creating `zigzagPlanNode` would defeat the purpose of the spec work - we want to eliminate creation of planNodes during the execbuild. Instead, we could create a "planning info" struct that allows us to populate `ZigzagJoinerSpec` in `DistSQLPlanner.planZigzagJoin`, and then both old and new factories would fill up that "planning info" struct in a different manner, but once that info is set, we have only a single code path in `DistSQLPlanner`.
___
*[pkg/sql/opt/exec/execbuilder/testdata/zigzag_join, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFsswL4X5Gd6m1YkIE:-MoGkit22q764B2K5rdV:b-3v4lqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/opt/exec/execbuilder/testdata/zigzag_join#L1)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Ha! I did that but removed it because I thought it was overkill.   I confirmed in a debugger the logic test used the new factory but I agree it would be nice to have some tests under always mode.   I guess duplicating tests into the experiment_distsql_planning for now is fine since we'll blow it away eventually.
</blockquote></details>

Yeah, that's my thinking too.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2685 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoKrMnJCe2s3JZJVcd6:-MoKrMnK-HLfLxqYJzxn:bccyy2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a16bd94cdabb23947d3b043603a2f4c7d2c1/pkg/sql/distsql_physical_planner.go#L2685)):*
> ```Go
> 	}}
> 
> 	plan.AddNoInputStage(corePlacement, post, pi.outputTypes, execinfrapb.Ordering{})
> ```

Should I use convertOrdering to turn the sql.ReqOrdering into a execinfrapb.Ordering here?
___
*[pkg/sql/distsql_spec_exec_factory.go, line 789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoKrgT271xrOuVZCyDa:-MoKrgT39ZCG70cBfGNf:b-z4xlid) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a16bd94cdabb23947d3b043603a2f4c7d2c1/pkg/sql/distsql_spec_exec_factory.go#L789)):*
> ```Go
> 		return nil, err
> 	}
> 	p.ResultColumns = colinfo.ResultColumnsFromColumns(tabDesc.GetID(), catCols)
> ```

I'm not sure what's going on with ResultColumns, apparently only new spec factory needs it?   I discovered this when trying to run a query which fed a zigzag into a lookup join, so this isn't super well tested (because lookup join isn't implemented).

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/distsql_physical_planner.go, line 2685 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoKrMnJCe2s3JZJVcd6:-MoLMm8d8BH-EW4iE-9c:bep78lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a16bd94cdabb23947d3b043603a2f4c7d2c1/pkg/sql/distsql_physical_planner.go#L2685)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Should I use convertOrdering to turn the sql.ReqOrdering into a execinfrapb.Ordering here?
</blockquote></details>

Yeah, I'd do it in a separate commit though.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 724 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoFs6-6EJHyRF56EJB3:-MoLNPVaArqN3jzvolbf:bobuxlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2eea9a2f7b8919221f8ac7dc8ec39da3e39600/pkg/sql/distsql_spec_exec_factory.go#L724)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> I thought we discussed this and decided copying would be better since we're gonna throw away the old code and we don't want to introduce bugs into the old code with the refactoring.

Sorry, I might have been unclear. I think we should aim to not change the behavior (i.e. preserve the current physical planning heuristics as much as possible, which in this case means not distributing the zigzag joins); however, I'm not a fan of the idea of copying a bunch of essentially duplicated code. So what I'm suggesting is to do something similar to d55f5eb675dbb2a374537f0d628bd2e16b36df2c.

Creating `zigzagPlanNode` would defeat the purpose of the spec work - we want to eliminate creation of planNodes during the execbuild. Instead, we could create a "planning info" struct that allows us to populate `ZigzagJoinerSpec` in `DistSQLPlanner.planZigzagJoin`, and then both old and new factories would fill up that "planning info" struct in a different manner, but once that info is set, we have only a single code path in `DistSQLPlanner`.
</blockquote></details>

I still think there is more code that could be de-duplicated about the physical planning.

In particular, I'm thinking of the physical planning via the old factory path as being performed in two steps:
1. create planNodes so that the `DistSQLPlanner` has enough info to perform the physical planning ("execbuilding"). This is done in the old factory.
2. perform actual physical planning. This is done in `DistSQLPlanner.createPlanForZigzagJoin`. (There is a bit of nuance that `createPlanForZigzagJoin` also contains some logic that performs the adaptation from `planNode`s to specs.)

I think we should not modify the physical planning logic in `distsql_physical_planner` as much as possible while we're performing this transition to the new factory (the goal is to preserve the existing behavior as much as possible). However, both the new and the old paths have different ways of setting up the necessary information for the physical planner. It requires a bit of untangling in `createPlanForZigzagJoin` to split that out.

With the current change the physical planning logic is being introduced into the new factory, and now we have it duplicated. This is not ideal, and apologies for being annoying, but we could de-duplicate things further. If it's unclear what I'm driving at, I prototyped my thinking in https://github.com/yuzefovich/cockroach/commit/97e410fcdef4537ba342b1d43cda78820473ab2d.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoKrgT271xrOuVZCyDa:-MoLN0QLCASyY79Aexzs:bnxp98v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b72a16bd94cdabb23947d3b043603a2f4c7d2c1/pkg/sql/distsql_spec_exec_factory.go#L789)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I'm not sure what's going on with ResultColumns, apparently only new spec factory needs it?   I discovered this when trying to run a query which fed a zigzag into a lookup join, so this isn't super well tested (because lookup join isn't implemented).
</blockquote></details>

In the old factory, these result columns are taken off `zigzagJoinNode` (via `planColumns` method), but in the new factory we set it directly on the physical plan (because we don't have those `planNode`s to propagate this info).
___
*[pkg/sql/distsql_spec_exec_factory.go, line 716 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoLMsfhAoFFwoqCUa-y:-MoLMsfhAoFFwoqCUa-z:b-usb9wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/721c381d6077e1481ea7748ef582f590dce88550/pkg/sql/distsql_spec_exec_factory.go#L716)):*
> ```Go
> 
> 	for s, table := range tables {
> 		// RFC: does casting a cat.Table to an optTable ruin the ability to test this code from opttester?  opt_exec_factory
> ```

I dunno about this.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 762 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MoLMx-RDUqGJt11_Y7i:-MoLMx-RDUqGJt11_Y7j:b-oe3qwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/721c381d6077e1481ea7748ef582f590dce88550/pkg/sql/distsql_spec_exec_factory.go#L762)):*
> ```Go
> 		for c, ok := col.Next(0); ok; c, ok = col.Next(c + 1) {
> 			column := tdesc.PublicColumns()[c]
> 			// RFC: what's going on with visibility?  can't find where its set I think its just
> ```

Yeah, I agree, it does look like Go default is used here.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 738 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-Mo_u0NsC-b7Z02rj8U7:-Mo_u0NsC-b7Z02rj8U8:bvclqdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L738)):*
> ```Go
> ) (exec.Node, error) {
> 	planCtx := e.getPlanCtx(cannotDistribute)
> ```

Should I check onCond and the fixed value expressions against checkExpr or does that not matter because I specified cannotDistribute?

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 694 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MokkV40B5gGexdsnnPP:-MokkV40B5gGexdsnnPQ:b-1kvwk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L694)):*
> ```Go
> ) (zigzagPlanningSide, error) {
> 	desc := table.(*optTable).desc
> 	colCfg := scanColumnsConfig{wantedColumns: make([]tree.ColumnID, 0, wantedCols.Len())}
> ```

Should this be using makeScanColumnsConfig?

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-:-MooCcOPAQJSuQr84qK1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 694 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MokkV40B5gGexdsnnPP:-MooBjsR5TyaYsHdoyAJ:b-u5fve4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L694)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Should this be using makeScanColumnsConfig?
</blockquote></details>

I think no given that the old factory is creating `scanColumnsConfig` directly.

Maybe it's worth extracting a helper method to initialize this struct when it is needed for the zigzag joins, and then use that method in both old and new factories.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 714 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MooCnBi8jQPwCtOdPEG:-MooCnBi8jQPwCtOdPEH:bjtgc63) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L714)):*
> ```Go
> 		return zigzagPlanningSide{}, err
> 	}
> 	return zigzagPlanningSide{
> ```

In the old factory we also are keeping track of the `indexUsageStats`. I think we don't - yet - do that in the new factory, but maybe add a TODO here for that.
___
*[pkg/sql/distsql_spec_exec_factory.go, line 738 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-Mo_u0NsC-b7Z02rj8U7:-MooCIqiDhTGT1GxMdZZ:b-1ejjzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L738)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Should I check onCond and the fixed value expressions against checkExpr or does that not matter because I specified cannotDistribute?
</blockquote></details>

Yeah, I think it doesn't matter because of `cannotDistribute`. Maybe add a quick comment about that.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72653)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 694 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72653#-MokkV40B5gGexdsnnPP:-MooZKE77X4vKDtC7C5N:b-l3s3vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9319e2f1f376f319d044f431cff75c9ec610bf36/pkg/sql/distsql_spec_exec_factory.go#L694)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think no given that the old factory is creating `scanColumnsConfig` directly.

Maybe it's worth extracting a helper method to initialize this struct when it is needed for the zigzag joins, and then use that method in both old and new factories.


</blockquote></details>

I'll leave it like this and extract a helper when i need it..

**Pull request merged**
