### PR TITLE
Flesh out TODO. Add Roadmap section.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM

**Comment by spencerkimball** [comment]
Let's create ROADMAP.md and move all TODO items into issues.

**Comment by bdarnell** [comment]
I'd put the roadmap in the wiki instead of a file in the repo - unlike TODOs, it is unlikely to change in conjunction with the code.

**Comment by petermattis** [comment]
Good idea about the wiki. Done: https://github.com/cockroachdb/cockroach/wiki/Roadmap

Going to submit this with the additional TODOs and then start moving the contents into issues later tonight.

**Pull request merged**
