### PR TITLE
sql: implement SHOW REGIONS FROM ALL DATABASES

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Introduce `SHOW REGIONS FROM ALL DATABASES`,
which shows region metadata for each database in the table.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
Looks great.  Left a comment in slack about circling back on whether or not we need a command which shows which databases are using a given region.  

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57500#-:-MNsrVWcBQg_NX3JQJpZ:bshc5s3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
