### PR TITLE
ui: Add Raft graphs to nodes/graphs.

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds the graphs added in #8257 to the node graphs pages in
the UI.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8382)

### CODE REVIEW

**Comment by bdarnell** [comment]
Can we put all three data points on one graph? (ideally stacked instead of three independent lines)

**Comment by jordanlewis** [comment]
Done.

**Comment by bdarnell** [comment]
LGTM

**Comment by maxlang** [comment]
Could you include a screenshot?

LGTM

**Comment by jordanlewis** [comment]
image
image

**Pull request merged**
