### PR TITLE
sql: fix crdb_internal statment_activity and transaction_activity tables

### PR DESCRIPTION
**Pull request by j82w**
The virtual table is selecting the wrong columns 
from the system table causing it to fail. This fixes 
the column names and adds tests.

Release note: None
Part of #98882
Epic: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102021#-:-NT_Ac3JBoNbIUPdWszC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by maryliag** [comment]
missing a 23.1.0 backport

**Comment by matthewtodd** [comment]
blathers backport 23.1

**Comment by matthewtodd** [comment]
Working through REL-298 (making sure everything on `release-23.1.0` made it to `release-23.1`), it looks like we missed this commit, despite the attempt in #102002.

So I've just sent #103039 to get this commit into `release-23.1`.

**Pull request merged**
