### PR TITLE
Add COPY support to IMPORT PGDUMP

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
ping @dt

**Review by dt — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-:-LGxC8-RDtegAkCNSdWL:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGx0YQS0_Oyt_L78vrE:-LGx0YQS0_Oyt_L78vrF:b-yrbio4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/ccl/importccl/read_import_pgdump.go#L89)):*
> ```Go
> 			// Got whitespace or comments; try again.
> 		case 1:
> 			if cf, ok := stmts[0].(*tree.CopyFrom); ok && cf.Stdin {
> ```

should this have an else block? if not, maybe a comment to explain what's expected.
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGx0HdQ0kykdRGsebs8:-LGx0HdQ0kykdRGsebs9:b-4cyhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/ccl/importccl/read_import_pgdump.go#L107)):*
> ```Go
> 			return stmts[0], nil
> 		default:
> 			return nil, errors.New("unexpected")
> ```

might be nice to do `unexpected number of statements %d` and/or include the text here in case this ever actually happens / is reported.
___
*[pkg/roachpb/io-formats.proto, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGwv_-F66UiWH9ZvrEZ:-LGwv_-GCjvitfM5G4Zl:b-isazwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/roachpb/io-formats.proto#L36)):*
> ```protobuf
>   optional MySQLOutfileOptions mysql_out = 3 [(gogoproto.nullable) = false];
>   optional PgCopyOptions pg_copy = 4 [(gogoproto.nullable) = false];
>   optional PgDumpOptions pg_dump = 6 [(gogoproto.nullable) = false];
> ```

just curious, but any reason we're skipping 5?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27062)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGx0YQS0_Oyt_L78vrE:-LGxbzdo-OYW8GTy-ETH:b-h6a4ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/ccl/importccl/read_import_pgdump.go#L89)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

should this have an else block? if not, maybe a comment to explain what's expected.
</blockquote></details>

No, this sets p.copy for use during the next call to Next. Added a comment.
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGx0HdQ0kykdRGsebs8:-LGxbdA69mzLLJAPlcQZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/ccl/importccl/read_import_pgdump.go#L107)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

might be nice to do `unexpected number of statements %d` and/or include the text here in case this ever actually happens / is reported.
</blockquote></details>

Done.
___
*[pkg/roachpb/io-formats.proto, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27062#-LGwv_-F66UiWH9ZvrEZ:-LGxc7rMAfvPAtTyvag6:b-mxilhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c7794ecc52013034325602275bf0318090fc5a/pkg/roachpb/io-formats.proto#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

just curious, but any reason we're skipping 5?
</blockquote></details>

not skipped: compression below is 5

**Pull request merged**
