### PR TITLE
builtins: implement ST_Extent

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Implement the ST_Extent builtin for geometry
aggregations into box2d.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
LGTM except you need to bump the version and minacceptedversion in  server_config.go (maybe you can also move `rowexec/version_history.txt` in the same dir)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53001#-:-MF2lQWr2PGkpQsLNrYC:b-2res42)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
does the min version need bumping? from history it looks like it does not?

**Comment by RaduBerinde** [comment]
I guess not, I always forget the exact logic (even though I came up with it haha)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53001#-:-MF3t_ho7AMD6BwXy4RR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53001#-:-MF6EiFqEF5l9oa1xGnX:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
