### PR TITLE
c-deps: use rocksdb's MockEnv instead of MemEnv

### LINKED ISSUE #16345: rocksdb: MemEnv doesn't support NewRandomRWFile
The RocksDB in-memory env doesn't support NewRandomRWFile, which is used when a file is ingested while a snapshot is outstanding (it rewrites the sequence number in the ingested file to be greated than the snapshot's sequence number). We currently have to set snapshot_consistency to false in IngestExternalFile as a workaround

### PR DESCRIPTION
**Pull request by danhhz**
MockEnv is considerably more mature than MemEnv and has replaced it
upstream, so we're going to make this switch eventually. Cherry-picking
this now gets us a working NewRandomRWFile, which lets us turn on the
snapshot_consistency consistency option when IngestingExternalFiles
(which was turned off only because the tests use in-memory stores).

Closes #16345.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16732#-:-KneNrzexeqBF6CPlEng:bnfp4nl)*

**Comment by danhhz** [comment]
Embarrassingly, I stressed the wrong test. Updated this to have the current impl of mock_env PTAL

**Comment by petermattis** [comment]
Still :lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16732#-:-KnecO1ZpPO7xSrO9pId:b-2pygyf)*

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
