### PR TITLE
sql: batch datum allocations during decoding

### PR DESCRIPTION
**Pull request by petermattis**
```
name                old time/op    new time/op    delta
KVScan1_SQL-32         189µs ± 3%     186µs ± 2%   -1.65%  (p=0.023 n=10+10)
KVScan10_SQL-32        263µs ± 6%     268µs ± 4%     ~     (p=0.190 n=10+10)
KVScan100_SQL-32       938µs ± 3%     945µs ± 4%     ~     (p=0.739 n=10+10)
KVScan1000_SQL-32     7.63ms ± 9%    7.35ms ± 6%     ~     (p=0.089 n=10+10)
KVScan10000_SQL-32    74.8ms ± 7%    71.0ms ± 5%   -4.99%  (p=0.007 n=10+10)

name                old allocs/op  new allocs/op  delta
KVScan1_SQL-32           213 ± 0%       209 ± 0%   -1.88%  (p=0.000 n=10+10)
KVScan10_SQL-32          356 ± 0%       308 ± 0%  -13.48%  (p=0.000 n=10+10)
KVScan100_SQL-32       1.72k ± 0%     1.24k ± 0%  -28.05%   (p=0.000 n=10+9)
KVScan1000_SQL-32      15.2k ± 0%     10.4k ± 0%  -31.57%   (p=0.000 n=10+9)
KVScan10000_SQL-32      151k ± 0%      102k ± 0%  -31.97%   (p=0.000 n=9+10)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6142)

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

Nice. Should bool, time, interval, and decimal get the same treatment, or does that start to bloat the allocator?

---

Reviewed 36 of 36 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-:-KFigdwGuiuPKz1y6QSK:-558306433)*

**Comment by petermattis** [comment]
Oh, I meant to add batch allocation of time, interval and decimal and just forgot to do this when my kids were bugging me last night. There is no need to batch allocate bool as `parser.MakeDBool` returns 1 of 2 global values.

**Comment by petermattis** [comment]
Anyone else want to take a look at this? The first commit is fairly large, though mostly mechanical. I want to make sure I'm not missing some way to make that change somewhat cleaner.

**Comment by nvanbenschoten** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Awesome change! Thanks for doing this, must have been very tedious. I don't see how the main change could have been smaller.

---

Review status: 37 of 38 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/table.go, line 981 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjipWzelxYJdmSsf9g:-KFjipWzelxYJdmSsf9h:1080591552) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L981)):*
Shouldn't we use `a` here?

---

*[sql/table.go, line 1001 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjiqlJYbx_GJ_BlXld:-KFjiqlJYbx_GJ_BlXle:1179194526) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1001)):*
and here

---

*[sql/table.go, line 1007 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjiuEDPmnktA1Sy4O_:-KFjiuEDPmnktA1Sy4Oa:1179194526) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1007)):*
and here

---

*[sql/table.go, line 1013 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjitKV_lJa4n-NX9fk:-KFjitKV_lJa4n-NX9fl:1179194526) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1013)):*
and here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-:-KFjizzQFAI8RMQVZf10:-299792117)*

**Comment by petermattis** [comment]
The first change was tedious, but the compiler caught everything which was nice.

---

Review status: 37 of 38 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/table.go, line 981 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjipWzelxYJdmSsf9g:-KFjkaRAU8mGkquzDnop:1545930671) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L981)):*
Yes, thanks for catching.

---

*[sql/table.go, line 1001 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjiqlJYbx_GJ_BlXld:-KFjkeAz5fYGZN7JUBb_:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1001)):*
Done.

---

*[sql/table.go, line 1007 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjiuEDPmnktA1Sy4O_:-KFjkeaKS7fgG17KqJ0m:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1007)):*
Done.

---

*[sql/table.go, line 1013 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-KFjitKV_lJa4n-NX9fk:-KFjkfUDyhusF7CPmXd0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5833668eb783814ed1480214e7c8216125e06e63/sql/table.go#L1013)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-:-KFjkhlZ5SxvbdTZtNi8:-1124765501)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 35 of 36 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: 37 of 38 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6142#-:-KFjn_lWAgSZDgubS8YF:1417088721)*

**Pull request merged**
