### PR TITLE
ui: use esbuild-loader in webpack configs

### PR DESCRIPTION
**Pull request by sjbarag**
Transformations via Babel and JS minification via Terser took up a
significant amount of time during UI builds due to the single-threaded
nature of those tools. esbuild's multi-threaded behavior is
significantly faster, but means babel-plugin-import [1] must be applied
to committed files rather than applied at build-time for each build.
esbuild-loader is a webpack plugin that uses esbuild for TypeScript and
JavaScript transformation and minification in place of babel-loader and
TerserWebpackPlugin respectively, with very few changes additional
changes required but dramatic speed improvements. As measured on a
24-core Xeon machine with 32GB RAM via `./dev build`:

    Package       babel-loader + terser   esbuild-loader
    -------       ---------------------   --------------
    cluster-ui    71 s                    29s
    db-console    157 s                   30s

Since building cluster-ui is a strict prerequisite for building
db-console, this implies a time savings of roughly
(157 s + 71 s) - (30 s + 29 s) == 169 seconds per build. Use
esbuild-loader for UI bundling.

To enable esbuild-loader, add an eslint plugin that ensure antd styles
are imported properly.

[1] https://github.com/umijs/babel-plugin-import

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]
🚀

**Comment by sjbarag** [comment]
Bazel build currently blocked by https://github.com/cockroachdb/cockroach/pull/82961

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 12 of 12 files at r1, 67 of 67 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

**Comment by sjbarag** [comment]
No change in diff, just rebased to use the versions of https://github.com/cockroachdb/yarn-vendored/pull/96 from `origin/master`

**Review by laurenbarker — COMMENTED** [review]
I have questions! Mostly about how the antd style imports worked before/work now. One thing I'd be concerned about it the global style overrides in CC Console not being applied to cluster-ui components that are importing the antd styles directly.

> Reviewed 12 of 12 files at r1, 23 of 67 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-:-N56zjSk4kb5mNY02ZWU:b-v8ew2s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @laurenbarker, @nathanstilwell, and @sjbarag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56usQsBmNnFb6Fo6Mn):*
I'm not entirely sure what the state of the app was prior to this change. Was `babel-plugin-import` being used to add the style imports automatically at build-time, and that's no longer an option if we use `esbuild-loader`? Now, in order to ensure the styles are getting added, an eslint rule checks that the style imports are in the files?

Something that I'm not sure about is whether the style imports are programmatically added or whether developers now have to add those imports.
___
*[`-- commits` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56vy9Q2ik3YqwQaLfc):*
Ah, does this mean that the styles are added programmatically as a separate step in the build process?
___
*[`-- commits` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56wBrN00dtEhOOMkqj):*
Incredible!
___
*[`-- commits` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56wI082m0Lhqdk0SHM):*
nit: I'm not sure what the last line, "use esbuild-loader for UI bundling", is adding to the commit message.
___
*[`Makefile` line 1360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56wfK8-tjywpVQFzwX:-N56wfK8-tjywpVQFzwY:b-9qagv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/Makefile#L1360)):*
> ```Makefile
> 
> .PHONY: ui-lint
> ui-lint: pkg/ui/yarn.installed $(ESLINT_PLUGIN_CRDB) $(UI_PROTOS_OSS) $(UI_PROTOS_CCL) $(CLUSTER_UI_JS)
> ```

Hm...so maybe the `antd` styles aren't added programmatically since the custom eslint plugin is included in the lint step?
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xKPl4L4yea1djA_x:-N56xKPl4L4yea1djA_y:b-y9n7d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L14)):*
> ```jsonc
>     "@typescript-eslint/no-namespace": "off",
>     "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
>     "@cockroachlabs/crdb/require-antd-style-import": "error"
> ```

If the rule is included in each packages' eslint config, does the plugin need to be run as part of the lint command? Are they doing different things?
___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xf1z4aYpjl09SF-J:-N56xf1z4aYpjl09SF-K:bi8pun0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/package.json#L169)):*
> ```JSON
>     "**/jest-environment-jsdom": "^27.5.1",
>     "aria-query": "file:../../yarn-vendor/aria-query-5.0.0-no-spaced-files.tgz",
>     "esbuild": "0.14.43"
> ```

Why is the resolution necessary?
___
*[`pkg/ui/workspaces/cluster-ui/tsconfig.json` line 7 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56y2NM4cHlGsS3bNnr:-N56y2NM4cHlGsS3bNns:blvkr7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/tsconfig.json#L7)):*
> ```jsonc
>     "emitDeclarationOnly": true,
>     "esModuleInterop": true,
>     "isolatedModules": true,
> ```

TIL https://www.typescriptlang.org/tsconfig#isolatedModules
___
*[`pkg/ui/workspaces/cluster-ui/webpack.config.js` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56y96DAniOwwSFhw1y:-N56y96DAniOwwSFhw1z:b5v2buw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/webpack.config.js#L96)):*
> ```JavaScript
>               },
>             },
>             {
> ```

Huh, I did not know this was here. Just an FYI in case it gets in your way at some point, the astroturf loader/astroturf as a dep can be removed because I'm pretty sure we aren't using it anywhere.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56ymXU7p4saMP_E3g0:-N56ymXU7p4saMP_E3g1:bqmpo5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L14)):*
> ```XML
> import { Link, RouteComponentProps } from "react-router-dom";
> import { Tooltip } from "antd";
> import "antd/lib/tooltip/style";
> ```

If we have overrides in other places, importing the styles here could cause them not to be applied. Were the tooltips improperly styled before?
___
*[`pkg/ui/workspaces/db-console/package.json` line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56z9RwAfWCWOxV9VwB:-N56z9Rx4bOUYabdUdMq:b-giojdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/db-console/package.json#L142)):*
> ```JSON
>     "karma-sourcemap-loader": "^0.3.7",
>     "karma-webpack": "^2.0.13",
>     "less-loader": "6.2.0",
> ```

Why didn't we need this before?
___
*[`pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56tLNIEgpu5UgjNrvu:-N56tLNIEgpu5UgjNrvv:b-t4xczg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae17145fda80abf2dfccd70681b2b6b64d1062a/pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json#L3)):*
> ```jsonc
> {
>   "compilerOptions": {
>     /* Visit https://aka.ms/tsconfig to read more about this file */
> ```

I don't think keeping all of the commented out complier options in the file is beneficial since there is this very helpful link :)
___
*[`pkg/ui/workspaces/db-console/webpack.config.js` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56zODr4--M4rhYz83j:-N56zODr4--M4rhYz83k:b-7a252f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/db-console/webpack.config.js#L104)):*
> ```JavaScript
>           ]
>         },
>         // Preprocess LESS styles required by external components
> ```

Interesting...how were we using these styles before?

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82862)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @laurenbarker, @nathanstilwell, and @sjbarag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56usQsBmNnFb6Fo6Mn):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

I'm not entirely sure what the state of the app was prior to this change. Was `babel-plugin-import` being used to add the style imports automatically at build-time, and that's no longer an option if we use `esbuild-loader`? Now, in order to ensure the styles are getting added, an eslint rule checks that the style imports are in the files?

Something that I'm not sure about is whether the style imports are programmatically added or whether developers now have to add those imports.
</blockquote></details>

Good point!  I can make that a bit more clear, but the short answer is "you're correct"!  Before this change, style imports were added programmatically at build-time via a babel-plugin.  Since we're not using babel anymore, we naturally can't use that plugin anymore either.  There's no esbuild equivalent, and requests for something like it have generally been shot down by the esbuild maintainer as "it's going to be really slow".  Since we build the DB more often than we add new components, it felt reasonable to perform those style imports statically and commit the results.  The eslint rule is there so people don't forget, and offers to add the correct import for them if their editor supports eslint fixers!
___
*[`-- commits` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56vy9Q2ik3YqwQaLfc):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Ah, does this mean that the styles are added programmatically as a separate step in the build process?
</blockquote></details>

Close!  It means that they were added programmatically at build-time, but are now added directly to the files we commit in git!
___
*[`-- commits` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56wI082m0Lhqdk0SHM):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

nit: I'm not sure what the last line, "use esbuild-loader for UI bundling", is adding to the commit message.
</blockquote></details>

Fair!  It's a habit I picked up from other projects that probably doesn't apply very well to CRDB.  I don't see any preferences for "final sentence" guidelines in https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages :shrug: 

I'll drop it.
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xKPl4L4yea1djA_x:-N57JPsv5uirPRA6EVn6:bnrpse6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L14)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

If the rule is included in each packages' eslint config, does the plugin need to be run as part of the lint command? Are they doing different things?
</blockquote></details>

The plugin doesn't need to be included as part of the lint command, but it does need to be compiled as a prerequisite of the `make ui-lint` task!  It's included here so that it actually gets run by `eslint` :smiley: 
___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xf1z4aYpjl09SF-J:-N57JgXe7t3WcC_8xxY2:b-x7uvyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/package.json#L169)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Why is the resolution necessary?
</blockquote></details>

When I installed the same version of `esbuild-loader` in `db-console` and `cluster-ui` on different days, I got different versions of `esbuild`!  I wanted to be explicit about it, since the `esbuild` binaries in `yarn-vendored` are pretty big.
___
*[`pkg/ui/workspaces/cluster-ui/webpack.config.js` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56y96DAniOwwSFhw1y:-N57KdiC8zS4HA6-iIkG:b-htgp92) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/webpack.config.js#L96)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Huh, I did not know this was here. Just an FYI in case it gets in your way at some point, the astroturf loader/astroturf as a dep can be removed because I'm pretty sure we aren't using it anywhere.
</blockquote></details>

Woah really? I'll file a github issue to remove then — no need to keep it around.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56ymXU7p4saMP_E3g0:-N57KjHi6MuIYuUVArjB:b7nnw8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L14)):*
> Were the tooltips improperly styled before?

Nope!  This is what `babel-plugin-import` would produce for us in `master` today (without this PR), so I've manually applied that transform.
___
*[`pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56tLNIEgpu5UgjNrvu:-N57LHyy9YMpTnwyw6vp:be5mrzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae17145fda80abf2dfccd70681b2b6b64d1062a/pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json#L3)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

I don't think keeping all of the commented out complier options in the file is beneficial since there is this very helpful link :)
</blockquote></details>

Heh I tend to agree!  This is the default output of `tsc --init`.  I can remove the trailing `/* … */` comments if you prefer!
___
*[`pkg/ui/workspaces/db-console/webpack.config.js` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56zODr4--M4rhYz83j:-N57L9-p5EH_ET_iVua7:bc9ck6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/db-console/webpack.config.js#L104)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Interesting...how were we using these styles before?
</blockquote></details>

TBH I don't remember writing this comment or changing this at all, so let me look :thinking:

**Review by laurenbarker — APPROVED** [review]
Thanks for the helpful explanations! I believe the only open question is about why less loader is now required, but otherwise this :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-:-N5AsuYRDMEVg9iLDbiu:bb7gaoq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @laurenbarker, @nathanstilwell, and @sjbarag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56usQsBmNnFb6Fo6Mn):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Good point!  I can make that a bit more clear, but the short answer is "you're correct"!  Before this change, style imports were added programmatically at build-time via a babel-plugin.  Since we're not using babel anymore, we naturally can't use that plugin anymore either.  There's no esbuild equivalent, and requests for something like it have generally been shot down by the esbuild maintainer as "it's going to be really slow".  Since we build the DB more often than we add new components, it felt reasonable to perform those style imports statically and commit the results.  The eslint rule is there so people don't forget, and offers to add the correct import for them if their editor supports eslint fixers!
</blockquote></details>

Ahh, the fact that this the styles are end result is the same as before makes me feel much better about this change! Thanks for the explanation.
___
*[`pkg/ui/workspaces/cluster-ui/.eslintrc.json` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xKPl4L4yea1djA_x:-N5ArTMi00zq7W7UmF6V:bj5pvax) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L14)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

The plugin doesn't need to be included as part of the lint command, but it does need to be compiled as a prerequisite of the `make ui-lint` task!  It's included here so that it actually gets run by `eslint` :smiley: 
</blockquote></details>

Oh, that makes sense. I definitely misinterpreted what `make ui-lint` was doing.
___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xf1z4aYpjl09SF-J:-N5AriIp7HFzh0v4maFc:b-9d7ted) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/package.json#L169)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

When I installed the same version of `esbuild-loader` in `db-console` and `cluster-ui` on different days, I got different versions of `esbuild`!  I wanted to be explicit about it, since the `esbuild` binaries in `yarn-vendored` are pretty big.
</blockquote></details>

lol what. I don't understand how that would happen if you installed the same version... Doesn't hurt to have the resolution though :shrug: 
___
*[`pkg/ui/workspaces/cluster-ui/webpack.config.js` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56y96DAniOwwSFhw1y:-N5ArvnACTNRWqtGhu9E:bvhmfhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/webpack.config.js#L96)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Woah really? I'll file a github issue to remove then — no need to keep it around.
</blockquote></details>

Thanks! https://github.com/cockroachdb/ui/pull/425 is a PR that removes astroturf from one of the UI packages if you want to link an example. It's pretty straight-forward though.
___
*[`pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56ymXU7p4saMP_E3g0:-N5AsRU50ardYO5sP08Q:b-83sjml) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx#L14)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

> Were the tooltips improperly styled before?

Nope!  This is what `babel-plugin-import` would produce for us in `master` today (without this PR), so I've manually applied that transform.
</blockquote></details>

Nicee
___
*[`pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56tLNIEgpu5UgjNrvu:-N5AscDl9A1AUPi-R_e_:bhi7dvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae17145fda80abf2dfccd70681b2b6b64d1062a/pkg/ui/workspaces/eslint-plugin-crdb/tsconfig.json#L3)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Heh I tend to agree!  This is the default output of `tsc --init`.  I can remove the trailing `/* … */` comments if you prefer!
</blockquote></details>

I would prefer if they're removed, but I also don't feel strongly about it. I'll leave it up to you!

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82862)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @laurenbarker, @nathanstilwell, and @sjbarag)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56usQsBmNnFb6Fo6Mn):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Ahh, the fact that this the styles are end result is the same as before makes me feel much better about this change! Thanks for the explanation.
</blockquote></details>

Done.
___
*[`Makefile` line 1360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56wfK8-tjywpVQFzwX:-N5BDJHB9RIKEYNI4HZy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/Makefile#L1360)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Hm...so maybe the `antd` styles aren't added programmatically since the custom eslint plugin is included in the lint step?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56xf1z4aYpjl09SF-J:-N5BDPgP5bq1OTTO9UcD:b-a5g97o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/package.json#L169)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

lol what. I don't understand how that would happen if you installed the same version... Doesn't hurt to have the resolution though :shrug: 
</blockquote></details>

`esbuild-loader` depends on `esbuild` with a caret range, and `esbuild` releases verrrrry often :smile: https://github.com/privatenumber/esbuild-loader/blob/077efbde9ed985a3e60535e6ecd5db8fe2756e1b/package.json#L44
___
*[`pkg/ui/workspaces/cluster-ui/webpack.config.js` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56y96DAniOwwSFhw1y:-N5BD_vRBppk2mgQ9aAG:b-47qh87) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/cluster-ui/webpack.config.js#L96)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Thanks! https://github.com/cockroachdb/ui/pull/425 is a PR that removes astroturf from one of the UI packages if you want to link an example. It's pretty straight-forward though.
</blockquote></details>

Perfect!  Filed https://github.com/cockroachdb/cockroach/issues/83192
___
*[`pkg/ui/workspaces/db-console/webpack.config.js` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82862#-N56zODr4--M4rhYz83j:-N5BGczJ7El9oVWDAYw-:b-612thv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3528115927bc66931ca129bffa6d651ac4a714ed/pkg/ui/workspaces/db-console/webpack.config.js#L104)):*
I definitely changed this!  Without adding `less-loader`, we receive errors from webpack:

```
ERROR in ./node_modules/antd/lib/tabs/style/index.less 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '../../style/themes/index';
| @import '../../style/mixins/index';
| @import './card-style';
 @ ./node_modules/antd/lib/tabs/style/index.js 5:0-23
 @ ./src/views/sqlActivity/sqlActivityPage.tsx
 @ ./src/app.tsx
 @ ./src/index.tsx
 @ multi ./src/index.tsx
```

As it turns out, our usage of `babel-plugin-import` was slightly different between `db-console` and `cluster-ui`.  `cluster-ui` used [style: true](https://github.com/umijs/babel-plugin-import#-libraryname-antd-style-true-) , which loads the `.less` file for compile-time transforms, but `db-console` used [style: css](https://github.com/umijs/babel-plugin-import/tree/c4d691057462bf4329a3126cedb5a7f94969884d#-libraryname-antd-style-css-), which imports pre-compiled CSS.  In a world without babel and `babel-plugin-import`, we've got a few options:

1. Standardize importing `.less` files from `antd` and compile them to CSS in the cluster-ui and db-console builds (that's what this PR does)
2. Standardize importing pre-compiled `.css` files from `antd`. This requires the style imports to be `import "antd/lib/component-name/style/css";`, which we'd update the linter to check for.
3. Don't standardize how we import styles from antd, and make the eslint-plugin configurable to check for `import "antd/lib/component-name/style";` or `…/style/css";`

Since importing less files directly can give us a smaller bundle according to the babel-plugin-import docs, it feels like the right choice?  It's also conveniently what I've done here, but that's not why I'm leaning towards it :stuck_out_tongue:

**Comment by sjbarag** [comment]
bors r=rickystewart,nathanstilwell,laurenbarker

**Comment by sjbarag** [comment]
bors p=1

**Pull request merged**
