### PR TITLE
sql: project out temporary columns used by window functions

### LINKED ISSUE #33340: Panic on aggregate function with window: SELECT SUM(_) OVER (ORDER BY _) FROM _
**Describe the problem**

I'm seeing a panic when aggregate functions (e.g., SUM, AVG) are used with a window. For example, if I set up a table like this:

```
create table test_table3 (a int, b int);
insert into test_table3 values (0, 10), (1, 11);
```
Then the following statement causes a panic: 

```
select sum(b) over (order by a) from test_table3;
```

This was on CockroachDB v2.1.1, and I tried upgrading to v2.1.3 and am seeing the same problem. Here is a dump of the logs:

> E181224 00:38:10.963782 16082 sql/conn_executor.go:636  [n1,client=100.112.0.11:34314,user=root] a SQL panic has occurred while executing "SELECT avg(b) OVER (ORDER BY a) FROM test_table3": runtime error: index out of range
> E181224 00:38:10.963916 16082 util/log/crash_reporting.go:203  [n1,client=100.112.0.11:34314,user=root] a panic has occurred!
> E181224 00:38:10.964418 16082 util/log/crash_reporting.go:477  [n1,client=100.112.0.11:34314,user=root] Reported as error 2dc5897bbbb3498f927858aa9c74565f
> panic: runtime error: index out of range [recovered]
> 	panic: panic while executing 1 statements: SELECT avg(_) OVER (ORDER BY _) FROM _; caused by runtime error: index out of range
> 
> goroutine 16082 [running]:
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42b452000, 0x30326a0, 0xc427cfab80, 0x2770280, 0x4231d70)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:650 +0x36f
> github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42b452000, 0x30326a0, 0xc427cfab80)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
> panic(0x2770280, 0x4231d70)
> 	/usr/local/go/src/runtime/panic.go:502 +0x229
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).bufferRow(0xc420959500, 0x3032760, 0xc428ff7890, 0xc4291db1e0, 0x2, 0x2, 0xc42677c2ea, 0x1, 0x1, 0x424e140, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:892 +0x355
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).AddRow(0xc429266c60, 0x3032760, 0xc428ff7890, 0xc4291db1e0, 0x2, 0x2, 0x4853b80, 0x3048940)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:216 +0x189
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push(0xc42a06a500, 0xc42ad0ae28, 0x2, 0x2, 0x0, 0x2)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:534 +0x8bc
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*accountClearingRowReceiver).Push(0xc429005170, 0xc42ad0ae28, 0x2, 0x2, 0x0, 0x2)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:279 +0x83
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*copyingRowReceiver).Push(0xc42ad0ae00, 0xc428c32fc0, 0x2, 0x2, 0x0, 0xc400000000)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:659 +0x191
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3032760, 0xc429004e70, 0x303cde0, 0xc420931000, 0x300f720, 0xc42ad0ae00)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:173 +0x5c
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc420931000, 0x3032760, 0xc429004e70, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc42740aa80, 0x3032760, 0xc429004e70, 0x2c30f98, 0xc420b54fc0, 0x300f3e0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:607 +0x191
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420b77a00, 0xc428c32f00, 0xc429266750, 0xc42c0748d8, 0xc42a06a500, 0xc42b4524b0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:253 +0x879
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420b77a00, 0x3032760, 0xc428ff7890, 0xc42b4524b0, 0xc428c32f00, 0xc429266750, 0x3025fa0, 0xc428a69d40, 0xc42a06a500)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:758 +0x24c
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc42b452000, 0x3032760, 0xc428ff7890, 0xc42b452418, 0x3, 0x7f9cc47ce1e8, 0xc429266c60, 0xc428ff7401, 0x1, 0x1)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42b452000, 0x30326a0, 0xc427cfab80, 0xc420d300d8, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0x0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1173 +0x1400
> github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4209fe000, 0x30326a0, 0xc427cfab80, 0xc42b452000, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0x0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc4209fe000, 0x30326a0, 0xc427cfab80, 0xc42b452000, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0xc42580da40, 0xc4277ba060)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
> created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c
> 

**Expected behavior**
I expected the query to complete successfully, with a result being a column with values 10 and 21 (as it does in PostgreSQL.)

**Environment:**
 - CockroachDB 2.1.1, 2.1.3
 - Server OS: Debian 8.9 (Docker)
 - Client app: PyCharm JDBC

**Additional context**
The cluster returns to normal operation after the node restarts.

### PR DESCRIPTION
**Pull request by yuzefovich**
windowNode adds rendering for the columns used in PARTITION BY and
ORDER BY clauses of OVER clause. Previously, those columns were kept
which crashed the nodes when invoked via an external driver. Now,
these temporary columns are projected out as a post-processing step
of the last stage of windowers.

Fixes: #33340.

Release note (bug fix): window functions with non-empty PARTITION BY
and ORDER BY clauses are now handled correctly when invoked via an
external driver.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

We should add a check to the end of the distsql receiver that validates that the number columns we're pushing is the same as the number of columns reported by `planColumns`. A strategy like that would have caught this bug. I can look at doing this with you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-:-LVq4CO1BczuP-bcP-Ok:b-uvroy3)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 3406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-LVq3F041yTFDe4luZf8:-LVq3F041yTFDe4luZf9:b-4hdckn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6610de90978e8fb4976d10635ba3b73a72429b1/pkg/sql/distsql_physical_planner.go#L3406)):*
> ```Go
> 		}
> 		plan.AddProjection(columns)
> 		plan.PlanToStreamColMap = identityMap(plan.PlanToStreamColMap, len(plan.ResultTypes))
> ```

This seems duplicated from the equivalent statement a few lines up, before the if - is it necessary? Or perhaps it's modified by `addRenderingIfNecessary` as well. It does seem like we're regenerating a lot of "identity maps" of different lengths for no reason - perhaps it would be better to just do it once, at the end, after we know the exact length we're supposed to be generating?

**Review by yuzefovich — COMMENTED** [review]
It's a great idea, we should definitely do that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-:-LVs8Q-m7PPWux89SErP:b2bfjuh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 3406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-LVq3F041yTFDe4luZf8:-LVs8Hb7DV4bU-d3ffR5:b9d5xob) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6610de90978e8fb4976d10635ba3b73a72429b1/pkg/sql/distsql_physical_planner.go#L3406)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems duplicated from the equivalent statement a few lines up, before the if - is it necessary? Or perhaps it's modified by `addRenderingIfNecessary` as well. It does seem like we're regenerating a lot of "identity maps" of different lengths for no reason - perhaps it would be better to just do it once, at the end, after we know the exact length we're supposed to be generating?
</blockquote></details>

Yes, I agree. Done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 3406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-LVq3F041yTFDe4luZf8:-LVsOPxm96KPjU81OdGb:b-fesasw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6610de90978e8fb4976d10635ba3b73a72429b1/pkg/sql/distsql_physical_planner.go#L3406)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, I agree. Done.
</blockquote></details>

Actually, I take this back: the map needs to be updated before addition of rendering because it is used to compute the rendering expressions. Not sure if we can avoid duplicating the code.

**Review by jordanlewis — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-:-LVt0b6lAatD-y60jE-m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 3406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-LVq3F041yTFDe4luZf8:-LVt0OOH8JAgtemT-Uyo:b8dywkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6610de90978e8fb4976d10635ba3b73a72429b1/pkg/sql/distsql_physical_planner.go#L3406)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually, I take this back: the map needs to be updated before addition of rendering because it is used to compute the rendering expressions. Not sure if we can avoid duplicating the code.
</blockquote></details>

Ah I understand. Ok, seems good.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33591#-:-LVt1ass2A9sKjAMA3V5:bctxt4d)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Can you backport this to 2.1 please @yuzefovich?

**Pull request merged**
