### PR TITLE
kvserver: add BenchmarkNodeLivenessScanStorage to measure liveness scan

### PR DESCRIPTION
**Pull request by sumeerbhola**
Node liveness scans, like the one done in MaybeGossipNodeLivenessRaftMuLocked, while holding raftMu, are performance sensitive, and slowness has caused production issues (https://github.com/cockroachlabs/support/issues/2665, https://github.com/cockroachlabs/support/issues/2107).

This benchmark measures the scan performance both when DELs (due to GC) have not been compacted away, and when they have. It also sets up a varying number of live versions since decommissioned nodes will have a single live version.

Results on M1 macbook on master with dead-keys=false and compacted=true:
```
 NodeLivenessScanStorage/num-live=2/compacted=true-10   26.80µ ± 9%
 NodeLivenessScanStorage/num-live=5/compacted=true-10   30.34µ ± 3%
 NodeLivenessScanStorage/num-live=10/compacted=true-10   38.88µ ± 8%
 NodeLivenessScanStorage/num-live=1000/compacted=true-10 861.5µ ± 3%
```

When compacted=false the scan takes ~10ms, which is > 100x slower, but probably acceptable for this workload.
```
 NodeLivenessScanStorage/num-live=2/compacted=false-10     9.430m ± 5%
 NodeLivenessScanStorage/num-live=5/compacted=false-10     9.534m ± 4%
 NodeLivenessScanStorage/num-live=10/compacted=false-10    9.456m ± 2%
 NodeLivenessScanStorage/num-live=1000/compacted=false-10 10.34m ± 7%
```

dead-keys=true (and compacted=false) defeats the NextPrefix optimization, since the next prefix can have all its keys deleted and the iterator has to step through all of them (it can't be sure that all the keys for that next prefix are deleted). This case should not occur in the liveness range, as we don't remove decommissioned entries, but is included for better understanding.
```
 NodeLivenessScanStorage/num-live=2/dead-keys=true/compacted=false-10 58.33m
```

Compared to v22.2, the results are sometimes > 10x faster, when the pebbleMVCCScanner seek optimization in v22.2 was defeated.

```
                                                         │                    sec/op                    │          sec/op           vs base               │
NodeLivenessScanStorage/num-live=2/compacted=false-10                                     117.280m ± 2%                9.430m ± 5%  -91.96% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=5/compacted=false-10                                     117.298m ± 0%                9.534m ± 4%  -91.87% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=10/compacted=false-10                                     12.009m ± 0%                9.456m ± 2%  -21.26% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=1000/compacted=false-10                                    13.04m ± 0%                10.34m ± 7%  -20.66% (p=0.002 n=6)

                                                         │                block-bytes/op                │      block-bytes/op       vs base               │
NodeLivenessScanStorage/num-live=2/compacted=false-10                                     14.565Mi ± 0%               8.356Mi ± 0%  -42.63% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=5/compacted=false-10                                     14.570Mi ± 0%               8.361Mi ± 0%  -42.61% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=10/compacted=false-10                                    11.094Mi ± 0%               8.368Mi ± 0%  -24.57% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=1000/compacted=false-10                                  12.235Mi ± 0%               8.990Mi ± 0%  -26.53% (p=0.002 n=6)

                                                         │                     B/op                     │           B/op            vs base               │
NodeLivenessScanStorage/num-live=2/compacted=false-10                                      42.83Ki ± 4%               41.87Ki ± 0%   -2.22% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=5/compacted=false-10                                      43.28Ki ± 3%               41.84Ki ± 0%   -3.32% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=10/compacted=false-10                                     37.59Ki ± 0%               41.92Ki ± 0%  +11.51% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=1000/compacted=false-10                                   37.67Ki ± 1%               42.66Ki ± 0%  +13.23% (p=0.002 n=6)

                                                         │                  allocs/op                   │        allocs/op          vs base               │
NodeLivenessScanStorage/num-live=2/compacted=false-10                                       105.00 ± 8%                 85.00 ± 0%  -19.05% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=5/compacted=false-10                                       107.00 ± 5%                 85.00 ± 0%  -20.56% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=10/compacted=false-10                                       74.00 ± 1%                 85.00 ± 0%  +14.86% (p=0.002 n=6)
NodeLivenessScanStorage/num-live=1000/compacted=false-10                                     79.00 ± 1%                 92.00 ± 1%  +16.46% (p=0.002 n=6)
```

Relates to https://github.com/cockroachlabs/support/issues/2665

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I'll gather some numbers for 23.1 and report.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-:-Nhbo-o43OIpCqzF5C1I:bwnal9i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @jbowens)

**Review by sumeerbhola — COMMENTED** [review]
> I'll gather some numbers for 23.1 and report.

As expected 23.1 is similar to master, because both have the `NextPrefix` optimization:
```
NodeLivenessScanStorage/num-live=2/compacted=false-10         	     129	   9235305 ns/op	   8764740 block-bytes/op	   40295 B/op	      60 allocs/op
NodeLivenessScanStorage/num-live=5/compacted=false-10         	     129	   9278107 ns/op	   8769950 block-bytes/op	   40486 B/op	      61 allocs/op
NodeLivenessScanStorage/num-live=10/compacted=false-10        	     128	   9247444 ns/op	   8777481 block-bytes/op	   40367 B/op	      60 allocs/op
NodeLivenessScanStorage/num-live=1000/compacted=false-10      	     120	   9889519 ns/op	   9429277 block-bytes/op	   40859 B/op	      64 allocs/op
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-:-NhbugyV5tb1ZyzfTgQK:belh7bs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @jbowens)

**Comment by andrewbaptist** [comment]
Since we are trying to measure the impact of large disk scans does it make more sense to change this test to run with a "real disk" rather than just in-memory? I'm concerned that the majority of the time will be waiting for the SSD and we may not capture that with an in-memory pebbe.

**Review by sumeerbhola — COMMENTED** [review]
The `block-bytes/op` is meant to capture the "disk" cost in a predictable manner. It won't account for a lower hit rate in one case than another, but note that the numbers here are modest (< 15MB), so the block cache ought to be very effective when we are doing this repeatedly. And this was exactly what was observed in a prior incident (no syscalls for disk reads and just a hot CPU loop inside Pebble iteration code) https://cockroachlabs.slack.com/archives/C04RXNF8THA/p1677786862307449?thread_ts=1677782359.190299&cid=C04RXNF8THA 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-:-Nhc4-4j1jRxV-SdSAFr:b-9w3ec2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @jbowens)

**Comment by jbowens** [comment]
Should we try on 22.2 too to see if there's an observable regression without NextPrefix?

**Comment by sumeerbhola** [comment]
> Should we try on 22.2 too to see if there's an observable regression without NextPrefix?

See the "Compared to v22.2, the results are sometimes > 10x faster, when the pebbleMVCCScanner seek optimization in v22.2 was defeated" in the commit comment.

**Comment by andrewbaptist** [comment]
Not directly related to this, but a good query for reference to track down what the liveness range looks like on a customer (thanks @jbowens):

This only works in 23.2+
```
SELECT crdb_internal.scan_storage_internal_keys(1, 1, start_key, end_key) 
FROM crdb_internal.ranges 
WHERE start_pretty = '/System/NodeLiveness';
```

**Review by jbowens — APPROVED** [review]
> See the "Compared to v22.2, the results are sometimes > 10x faster, when the pebbleMVCCScanner seek optimization in v22.2 was defeated" in the commit comment.

Whoops, thanks :)


:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-:-NhlPFPG-hIbB-ZgvOc-:b-vtx693)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlSSS83h4BVUSWfdOv:-NhlSSS83h4BVUSWfdOw:bnrn54w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1318)):*
> ```Go
> 		// 20 per minute, so 1000 represents 50 min of liveness writes in a level.
> 		// This is unusual, but we can have such accumulation if flushes and
> 		// compactions are rare.
> ```

We might have significantly more accumulation in the lower levels if compactions are prioritizing other parts of the keyspace instead, right?. I'm not sure if we know how many tombstones were encountered in recent escalations.
___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlQ1u_00bvQMNAenNb:-NhlQ1u_00bvQMNAenNc:b-j1vvrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1340)):*
> ```Go
> 					// Always write a version if not at the highest level. If at the
> 					// highest level, only write if v < numLiveVersions. Additionally,
> 					// either haveFullyDeadKeys must be false or this node is one that
> ```

nit: should this say "or this _level_ is one that has live versions"?
___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlRCTg9TkgBu3vtIiJ:-NhlRCTg9TkgBu3vtIiK:b-410zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1401)):*
> decommissioned nodes will only have 1 version,

Ah, that's encouraging. That makes NextPrefix effective where the pebbleMVCCScanner optimization was not, right?

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-:-NhmYB4M2RX_cWt3qyQL:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @jbowens)

___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlSSS83h4BVUSWfdOv:-NhmW9f8BVJPw5gooyoC:b-h8wdbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1318)):*
> We might have significantly more accumulation in the lower levels if compactions are prioritizing other parts of the keyspace instead, right?

Agreed. This was somewhat arbitrarily chosen. Arguably this is also imbalanced since L6 only had 1/7th of the data.
___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlQ1u_00bvQMNAenNb:-NhmWdThEZyzVZoUpM_J:bwnez1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1340)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: should this say "or this _level_ is one that has live versions"?
</blockquote></details>

Meant "node" since when `haveFullyDeadKeys` is true we alternative NodeIDs that have some live versions and NodeIDs that have only dead versions for their liveness. All of this alternating applies only to the highest level.
___
*[`pkg/kv/kvserver/node_liveness_test.go` line 1401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113069#-NhlRCTg9TkgBu3vtIiJ:-NhmX5Ib9aGJi0dtbr3P:b-ut9146) ([raw file](https://github.com/cockroachdb/cockroach/blob/b41c72f10658c3c597d35bd55105dfe1658600ad/pkg/kv/kvserver/node_liveness_test.go#L1401)):*
> That makes NextPrefix effective where the pebbleMVCCScanner optimization was not, right?

Right.

**Comment by sumeerbhola** [comment]
bors r=andrewbaptist,jbowens

**Pull request merged**
