### PR TITLE
distsql: fix columnar operators test harness

### LINKED ISSUE #43945: colexec: TestMergeJoinerAgainstProcessor failed
Saw a reproducible on current master failure:
```
=== RUN   TestMergeJoinerAgainstProcessor
--- join type = FULL_OUTER onExpr = "" filter = "@5 = 'e'N[a\\rNaN\\x10''" seed = 4829897133613591500 run = 2 ---
CREATE TABLE left(a integer, b "char", c "char");
CREATE TABLE right(a integer, b "char", c "char");
INSERT INTO left VALUES
(1103164611, 'y#', e' co\x0f>MT'),
(-1565006090, e'rC3!a\x05\x1e\fi', '(]KH`L'),
(1204663163, e'lN\x1c@~"', '%3`'),
(1468221204, e'j1\x17\x17', e'\x06\x14'),
(886130321, e'\\Nn%', e'\x12U\x03C'),
(NULL, 'W', e'j_,\x10w'),
(1006345766, e'19\x06\x7f\x07\x10y\x1e', e'\x1fgdpO3\x1aa6'),
(1, '/', ' 7'),
(1994356194, e'#x.\x11M[T4', e'\x01%n\x04'),
(-2004744569, e'\x0fl\x10\x19x,l', e'A\x11Clh\x1f');
INSERT INTO right VALUES
(2147483647, e'v\x0eA', e'\x1cU'),
(0, 'l@tf,', NULL),
(738516335, e'h\x04\x12u\\\x02(', 'a'),
(-1498981068, 'HJ', '<C'),
(467334683, e'\x1as]N\x1fC8', '@,bOb(&x'),
(-2147483648, e'\x1aRJ;\x11-`rP', e'\x02'),
(-882647303, e'\t', e'477\x04'),
(-1127096114, NULL, NULL),
(-1456007196, NULL, e'7\t<4\fe'),
(-883064187, NULL, '');
--- FAIL: TestMergeJoinerAgainstProcessor (6.00s)
    columnar_operators_test.go:535: at or near "n": syntax error
```
Not immediately sure where the error is coming from.

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we incorrectly surrounded a randomly generated constant
datum with single quotes if its string representation contained `NaN`
or `Inf`, regardless of the type. However, this surrounding should only
happen when we're working with numeric types.

Fixes: #43945.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql/columnar_utils_test.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-LydvAN-7-7HRgq3-ozH:-LydvAN-7-7HRgq3-ozI:b-sx1hgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L72)):*
> ```Go
> 	proc, err := rowexec.NewProcessor(ctx, flowCtx, 0, &pspec.Core, &pspec.Post, inputsProc, []execinfra.RowReceiver{nil}, nil)
> 	if err != nil {
> 		if strings.Contains(err.Error(), "syntax error") {
> ```

String matching error messages is very brittle, not sure what we want to do here.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-Lydv8VY2saCuaPNYWmE:-Lydv8VZ-QnaC8ifCdex:b-pqsfi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L73)):*
> ```Go
> 	if err != nil {
> 		if strings.Contains(err.Error(), "syntax error") {
> 			// It is possible that we generated an invalid filter expression, and in
> ```

What about the filter expression is invalid?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql/columnar_utils_test.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-LydvAN-7-7HRgq3-ozH:-Lydwlta2z2JybAbaKuQ:bgh5k6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

String matching error messages is very brittle, not sure what we want to do here.
</blockquote></details>

I agree it's not perfect, but the goal of these "against processor" tests (in my mind) is to find differences between row-by-row processors and columnar operators. We take the processor output as the source of the truth, and if for some input a processor cannot be created, I think the test should not fail.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-Lydv8VY2saCuaPNYWmE:-Lydw8Yf0aMbMDXjLH8t:b-1baxsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L73)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What about the filter expression is invalid?
</blockquote></details>

In #43945, the generated filter expression is `@5 = 'e'N[a\\rNaN\\x10''` and creating a processor with such filter expression returns `at or near "n": syntax error`. Seems like an incorrect number of escape symbols or single quotes in it.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql/columnar_utils_test.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-LydvAN-7-7HRgq3-ozH:-LydxvN4ERjyHxKGQVOp:b-f9f4el) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I agree it's not perfect, but the goal of these "against processor" tests (in my mind) is to find differences between row-by-row processors and columnar operators. We take the processor output as the source of the truth, and if for some input a processor cannot be created, I think the test should not fail.
</blockquote></details>

Completely agree. I think this is fine, but we should keep in mind that we should avoid string matching errors whenever possible
___
*[pkg/sql/distsql/columnar_utils_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-Lydv8VY2saCuaPNYWmE:-LydxrOuE_lTvKbFXYrg:bw1hwrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L73)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

In #43945, the generated filter expression is `@5 = 'e'N[a\\rNaN\\x10''` and creating a processor with such filter expression returns `at or near "n": syntax error`. Seems like an incorrect number of escape symbols or single quotes in it.
</blockquote></details>

:+1: is there something to do about our filter generation?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsql/columnar_utils_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-Lydv8VY2saCuaPNYWmE:-LyeQVcS3CwWaRlVnr9b:b-igk6sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08c20f453147177ab9b5c1ee57317dedfeddb7cd/pkg/sql/distsql/columnar_utils_test.go#L73)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:+1: is there something to do about our filter generation?
</blockquote></details>

Thanks for pushing back on this. It forced to me to look at the problem closer, and I realized that expression generation must be the culprit. Fixed.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43988#-:-Lyf8X4n9HaHJBAl2cuX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
