### PR TITLE
roachtest: set min version for sqlsmith test

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Maybe this is not a good idea since sqlsmith found a panic on 2.1 release (https://github.com/cockroachdb/cockroach/issues/42813#issue-529160431).

**Comment by mjibson** [comment]
What exactly does minversion do? Will we need to bump it every release?

**Comment by yuzefovich** [comment]
This `MinVersion` specifies the minimum version of Cockroach to run this roachtest against. Basically, if we pin at `19.2.0`, then the branches for all previous releases will not run it. It doesn't need to be updated every release.

I created this PR because of failures like this:
```
The test failed on branch=release-2.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191128-1616610/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
	sqlsmith.go:102,sqlsmith.go:189,test_runner.go:697: pq: unimplemented at or near ")"
```

I think we could either
1. set the min version like this PR is doing
or
2. modify the setup of the test so that each version uses features that it supports

**Comment by mjibson** [comment]
Ah if it fixes that bug then ship it. LGTM.

**Review by madelynnblue — APPROVED** [review]

**Comment by yuzefovich** [comment]
Yes, I believe it will fix that issue.

TFTR!

bors r+

**Pull request merged**
