### PR TITLE
workload/ycsb: use pgx in ycsb

### PR DESCRIPTION
**Pull request by ajwerner**
The workload tool was saturated because pq is inefficient for scans. It was
spending all of its time copying data under `Rows.Next()`. The pgx driver
avoids this copy and thus is able to actually saturate the underlying database.

Epic: None

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89980#-:-NENIaYxCLWtH8M6zS-B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by jbowens** [comment]
should we add a label to the roachperf graph?

81B882D0-0D3F-4069-9ABD-20FE23F0A15A

**Comment by srosenberg** [comment]
> should we add a label to the roachperf graph?
> 

Good catch, we should! PR: https://github.com/cockroachdb/roachperf/pull/113

**Comment by srosenberg** [comment]
Annotations are now rendered. Curiously, the runs in AWS have remained flat after this and related changes,

ycsb_e_aws

**Comment by ajwerner** [comment]
On AWS we are saturating the network to the client node. One GCP we were not.

**Comment by srosenberg** [comment]
> On AWS we are saturating the network to the client node. On GCP we were not.

In that case, `m6i` would probably perform better (up to 12Gbps vs. up to 10Gbps for `m5`).

**Comment by ajwerner** [comment]
Sure. I don't know enough to know. It's an unfortunate thing generally to change machine types for the other benchmarks because it'll make the history meaningless and confusing. I think it'd be ~fine to change it just for E.

**Pull request merged**
