### PR TITLE
*: ensure cluster-less RPC-related tests validate cluster IDs

### LINKED ISSUE #35412: storage: TestReopenConnection failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/f53d12936efd36ea51eab6f191725d1dca2ceff3

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stress TESTS=TestReopenConnection PKG=github.com/cockroachdb/cockroach/pkg/storage TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1162543&tab=buildLog

```

I190305 07:50:50.638676 111966 rpc/nodedialer/nodedialer.go:95  unable to connect to n2: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:40755: connect: connection refused"
I190305 07:50:50.639085 111966 rpc/nodedialer/nodedialer.go:95  unable to connect to n3: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:40755: connect: connection refused"
panic: locally configured maximum clock offset (1ns) does not match that of node 127.0.0.1:36099 (500ms)

goroutine 112000 [running]:
github.com/cockroachdb/cockroach/pkg/rpc.(*HeartbeatService).Ping(0xc42045eba0, 0x2c74b40, 0xc422578090, 0xc422417620, 0xc42045eba0, 0xc4233d80f0, 0xc4211cc880)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.go:115 +0x517
github.com/cockroachdb/cockroach/pkg/rpc._Heartbeat_Ping_Handler.func1(0x2c74b40, 0xc422578090, 0x25a2ee0, 0xc422417620, 0x25a2ee0, 0xc422417620, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:155 +0x86
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2c74b40, 0xc422578090, 0x25a2ee0, 0xc422417620, 0xc42045f2c0, 0xc42045f2e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:48 +0xa33
github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor.func3(0x2c74b40, 0xc422578090, 0x25a2ee0, 0xc422417620, 0xc42045f2c0, 0xc42045f2e0, 0x2405640, 0x3e2f998, 0x2695cc0, 0xc42022a200)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:227 +0xac
github.com/cockroachdb/cockroach/pkg/rpc._Heartbeat_Ping_Handler(0x23c7760, 0xc42045eba0, 0x2c74b40, 0xc422578090, 0xc421be4e00, 0xc4203d9520, 0x0, 0x0, 0xc42022a200, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/heartbeat.pb.go:157 +0x167
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420353500, 0x2c90f00, 0xc42057c000, 0xc42022a200, 0xc420ad79b0, 0x3b7ad30, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1011 +0x4fc
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420353500, 0x2c90f00, 0xc42057c000, 0xc42022a200, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1249 +0x1318
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42034c6a0, 0xc420353500, 0x2c90f00, 0xc42057c000, 0xc42022a200)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:678 +0xa1

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4201d9590, 0x27003a5, 0x14, 0x282df28, 0x8ba201)
	/usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc4201d92c0)
	/usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc4201d92c0, 0xc420593b90)
	/usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4203140e0, 0x3ba8040, 0x238, 0x238, 0x15b13b8)
	/usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc42022e180, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x171
github.com/cockroachdb/cockroach/pkg/storage_test.TestMain(0xc42022e180)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/main_test.go:57 +0x1e3
main.main()
	_testmain.go:1194 +0x151

goroutine 6 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 10 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
```

### PR DESCRIPTION
**Pull request by knz**
Fixes  #35412.

When a test uses RPCs but does not set up a fully-fledged cluster, its
RPC context operates "without a cluster ID" throughout the test.

This creates potential for a flake if the test creates a server and
subsequently stops the server and expects further RPCs to that server
to fail: it is possible for a concurrent unrelated test to start a
server using the same TCP port as the server in the first test, in
which case the first test will then (unexpectedly, and incorrectly)
succeed in connecting to a server itself did not start. This failure
mode exists because without a valid cluster ID, the RPC context does
not validate what it's talking to.

The likelihood of TCP port reuse on a single server process is
relatively low, but given the frequency and sheer amount of tests that
start and stop servers, the probability we would observe such a flake
“in the wild” was asymptotically approaching 1, and indeed #35412 has
this scenario as likely cause.

This patch attempts to mitigate this situation by revisiting all the
tests that currently spawn a client RPC context without spawning a
cluster, in the cases where the test also checks the
availability/status/liveness of its server(s). On these tests, the
patch sets the cluster ID to be a random non-zero value.

Note that the previous fix to check expected node IDs is also a
partial mitigation, however most tests use node IDs starting from
1 (with most of them using just 1, or 1 and 2), and so the probability
that two unrelated tests running concurrently on the same machine
would run two server instances with the same node ID remains high. A
random cluster ID thus constitutes a more effective, definite mitigation.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
The change looks good, but looks like some tests are failing. I'll hold off on the "real" review, just let me know when it's ready.

**Comment by knz** [comment]
RFAL

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37344#-:-LeIoKn34w0u24nkK_We:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
