### PR TITLE
ui: update to typescript 2.0.0

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8028)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

Has Jade still been renamed to pug?

**Comment by tamird** [comment]
Yep.

**Comment by maxlang** [comment]
@tamird are you getting a bunch of warnings when you ran tests?

**Comment by tamird** [comment]
Yeah. See https://github.com/frankwallis/plugin-typescript/issues/144

**Pull request merged**
