### PR TITLE
Migrate kv/{rest,txn_coord_sender}.go from client.KV to client.DB.

### PR DESCRIPTION
**Pull request by petermattis**
See #997.

### CODE REVIEW

**Comment by tamird** [comment]
LGTM but a comment detailing how the `InternalAddCall` issue might resolved would be nice

**Comment by petermattis** [comment]
@tamird You mean the issue with its usage in `kv/rest.go`? Getting rid of the REST interface would be my preference, but I need to discuss when others are around.

**Comment by tamird** [comment]
Agreed. Carry on.

**Comment by bdarnell** [comment]
+1 to getting rid of the REST API, at least in its current form. The point of the REST API is to be more insulated from our internal protos (i.e. PUT takes a blob instead of a proto.Value), so the return values should be similarly abstracted.

**Pull request merged**
