### PR TITLE
storage: add COCKROACH_REBALANCE_THRESHOLD

### PR DESCRIPTION
**Pull request by petermattis**
Only rebalance from a store when doing so would result in the range
count remaining about the mean*(1+COCKROACH_REBALANCE_THRESHOLD).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9230)

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @cockroachdb/stability 

An alternative to #9216.

**Comment by petermattis** [comment]
Running `zerosum -n 10 -m 3 -c none -verify=false -- --vmodule=replicate_queue=1` for 5 min resulted in 217 rebalances. Those settings create a 10 node cluster that is splitting ranges approximately once per second. 

Using `COCKROACH_GOSSIP_STORES_INTERVAL=1m COCKROACH_REBALANCE_THRESHOLD=0` resulted in 512 rebalances. Those env var settings mimic the heuristics prior to this change.

Lastly, using `COCKROACH_REBALANCE_THRESHOLD=0.1` resulted in 118 rebalances.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREE32J81ETS30W-aMk:-KREE32J81ETS30W-aMl:biz7dbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
> ```Go
> 	// DefaultGossipStoresInterval is the default interval for gossiping storage-
> 	// related info.
> 	DefaultGossipStoresInterval = 5 * time.Second
> ```

is this really intended to be in the same commit?

---

*[storage/balancer.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREERrngJ_QkiuTuTVj:-KREERroTCGTqAClZ9jE:bba65ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L153)):*
> ```Go
> 	store roachpb.StoreDescriptor, sl StoreList,
> ) bool {
> 	// TODO(peter,bram,cuong): The FractionUsed check seems suspicious. When a
> ```

nit: anchor this comment on the `shouldRebalance := ....` line.

---

*[storage/balancer.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREGFs3WG4saiqx6L3-:-KREGFs3WG4saiqx6L30:b-ciawr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L166)):*
> ```Go
> 		// converge on the mean range count. This only affects clusters with a
> 		// small number of ranges.
> 		shouldRebalance =
> ```

nit: instead of mutating shouldRebalance, can you use two different bindings for clarity?

---

*[storage/balancer.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREF0T6nVjVoWsr_u4s:-KREF0T7W5iP-wzdZ27v:b-5z3k0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L167)):*
> ```Go
> 		// small number of ranges.
> 		shouldRebalance =
> 			(math.Abs(float64(store.Capacity.RangeCount-1)-sl.candidateCount.mean) <
> ```

isn't this giant expression equivalent to `float64(store.Capacity.RangeCount)-sl.candidateCount.mean > 0.5`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KREGMPuVS-T-aTVuliS:bnfp4nl)*

**Comment by cuongdo** [comment]
:lgtm: mod comments

I think that a unit test that specifically verifies that thrashing does not occur would be useful and would serve as de-facto documentation as to the thrashing scenarios you're looking to address. Specifically, it should test small replica counts (to ensure a user's first experiences with a small cluster show visible rebalancing) as well as larger replica counts.

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KRECt8zDc4i-GljLg1-:-KRECt8zDc4i-GljLg10:bbklluu) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
> ```Go
> 	// DefaultGossipStoresInterval is the default interval for gossiping storage-
> 	// related info.
> 	DefaultGossipStoresInterval = 5 * time.Second
> ```

This seems really aggressive. What if each gossip contains thousands of `StoreDescriptor`s? This seems wasteful for network bandwidth. Maybe 15 seconds is a good compromise, since it would allow only a couple of rebalances to occur with potentially stale data?/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KREDIHjRTrvUua4jHaG:bqxkaxl)*

**Comment by petermattis** [comment]
I agree that we need tests for these heuristics, though I'm not sure yet what that looks like. Perhaps an expansion of the simulator. Perhaps something else. Let me file an issue. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREE32J81ETS30W-aMk:-KREUu_NJ-AIYIHiWKWz:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this really intended to be in the same commit?
</details>
Yes.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KRECt8zDc4i-GljLg1-:-KREUvCa363Ys4Ukg_Wq:bhwkaw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> This seems really aggressive. What if each gossip contains thousands of `StoreDescriptor`s? This seems wasteful for network bandwidth. Maybe 15 seconds is a good compromise, since it would allow only a couple of rebalances to occur with potentially stale data?/
</details>
How big is `StoreDescriptor`? I'll be pessimistic and say 1K. For our current cluster sizes we're talking about gossiping 10s of kilobytes per second. Let's worry about how this scales to larger clusters once we get our current cluster sizes stable.

---

*[storage/balancer.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREERrngJ_QkiuTuTVj:-KREVYE1KYFA2rhZKjWB:bojld95) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: anchor this comment on the `shouldRebalance := ....` line.
</details>
And yet is obscures the other comment that talks about the rebalancing heuristic. I moved it here intentionally.

---

*[storage/balancer.go, line 166 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREGFs3WG4saiqx6L3-:-KREVmJsr2-rTsTCkoTR:b-kgjuvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: instead of mutating shouldRebalance, can you use two different bindings for clarity?
</details>
I've manually tested the current code (because our allocation heuristics don't have good tests). Any tweak here would require another round of such testing and the benefits seem minor. 

---

*[storage/balancer.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREF0T6nVjVoWsr_u4s:-KREVgFLNHQwQR00elO_:biw4fgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L167)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't this giant expression equivalent to `float64(store.Capacity.RangeCount)-sl.candidateCount.mean > 0.5`?
</details>
This is the previous expression. I want to leave it verbatim and not worry about whether another expression is equivalent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KREW1_RHci0-2fRCs2n:b3dapw9)*

**Comment by petermattis** [comment]
A 10min run with the previous heuristics resulted in 1328 rebalances. A 10min run with `COCKROACH_REBALANCE_THRESHOLD=0.1` resulted in 121 rebalances. Also interesting, here are the per-node replica counts

```
old: 253 256 254 254 264 256 254 258 252 258
new: 271 302 285 264 256 281 266 287 285 290
```

As expected, the old heuristics are "trying too hard" to have every node at the mean. I'm not sure what setting we should try initially. `0.1` reduces the rebalancing to almost zero in my setup. `0.05` feels a bit more conservative.

**Comment by bdarnell** [comment]
In your last comment, which gossip interval was used (in both cases)?

The balancer change :lgtm:; I'd rather not change the gossip interval except to make it configurable. 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KRECt8zDc4i-GljLg1-:-KRE_ladPMHCcOwjvZx5:bwuho4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> How big is `StoreDescriptor`? I'll be pessimistic and say 1K. For our current cluster sizes we're talking about gossiping 10s of kilobytes per second. Let's worry about how this scales to larger clusters once we get our current cluster sizes stable.
</details>
I still think it's a bad idea to set the interval this low. We could make it configurable for experimentation's sake, but if this turns out to be beneficial I'd rather explore other solutions (like exchanging capacity information on reservation/streaming snapshot requests) than just lowering this interval. The goal is to make a rebalancing system that can tolerate some amount of stale data so gossiping more often just masks the root issue. 

---

*[storage/balancer.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREb3IGL2DP4kCq-Pkr:-KREb3IGL2DP4kCq-Pks:b-v4oi6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L159)):*
> ```Go
> 	// The store requires rebalancing if its range count is larger than
> 	// mean*(1+rebalanceThreshold).
> 	target := sl.candidateCount.mean * (1 + rebalanceThreshold)
> ```

I think we need to `math.Ceil` this for small clusters. Make `target` an int instead of casting `RangeCount` to a float. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KREbXAKESR3SgAFPM7b:b-qcpgnw)*

**Comment by petermattis** [comment]
In the last comment, I used `COCKROACH_GOSSIP_STORES_INTERVAL=5s` for `new` and `COCKROACH_GOSSIP_STORES_INTERVAL=1m` for `old`. 

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[gossip/gossip.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KRECt8zDc4i-GljLg1-:-KREh4TWPv3IAmM4_HT3:b6qcr4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/gossip/gossip.go#L118)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I still think it's a bad idea to set the interval this low. We could make it configurable for experimentation's sake, but if this turns out to be beneficial I'd rather explore other solutions (like exchanging capacity information on reservation/streaming snapshot requests) than just lowering this interval. The goal is to make a rebalancing system that can tolerate some amount of stale data so gossiping more often just masks the root issue. 
</details>
Ok, I was off by an order of magnitude. An encoded `StoreDescriptor` is ~70 bytes. The rebalancing system should tolerate some amount of stale data, but why make it work harder than necessary. Setting the store gossip interval to 5s won't cause any significant load for clusters we're going to hit in the near term and doing so removes significant staleness as a concern when reasoning about the heuristics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KREgrd9tdjbTyhIGGsT:b-a2zd5y)*

**Comment by bdarnell** [comment]
You're changing two variables at once. Can you try them each independently so we can see which is contributing more to the result?

**Comment by petermattis** [comment]
Ok, here are the 4 scenarios:

```
gossip-interval=5s  rebalance-threshold=0.0  rebalances=1766
gossip-interval=5s  rebalance-threshold=0.1  rebalances=121
gossip-interval=1m  rebalance-threshold=0.0  rebalances=1328
gossip-interval=1m  rebalance-threshold=0.1  rebalances=432
```

Reducing the gossip interval without adjust rebalance threshold just makes the rebalancing even more aggressive. Tweaking the rebalance threshold by itself seems to leave open periods of asymmetric knowledge. I'm guessing this could be closed if we had both the sending and recipient node for a rebalance exchange range counts (currently the range count only flows from the recipient to the sender).

To be fair, `zerosum` is unrealistic in how fast it is creating ranges which exacerbates the slow gossip interval. Still, I see little harm in setting the default store gossip interval to 5s. We're talking about gossiping a tiny amount of data per store every 5s. In contrast, we currently send thousands of heartbeats to every node every 200ms.

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[storage/balancer.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREb3IGL2DP4kCq-Pkr:-KRFEWkMcyck5_cpnQcN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L159)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think we need to `math.Ceil` this for small clusters. Make `target` an int instead of casting `RangeCount` to a float. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KRFEZcjdLtBORaSm5NZ:bkro6r4)*

**Comment by spencerkimball** [comment]
Nice work.

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KRFXLEenAMTYNK2_t5F:bdtx8rj)*

**Comment by tschottdorf** [comment]
:lgtm:

Can this merge and could you suggest settings that we should use for `gamma` to reduce thrashing there? I don't think the discussion about the gossip store interval is substantial enough in the short term to block this PR (though the disagreement should be resolved asynchronously).

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/balancer.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREF0T6nVjVoWsr_u4s:-KRFYaeWE2MJSA50V_r9:b-n6x0qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L167)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This is the previous expression. I want to leave it verbatim and not worry about whether another expression is equivalent.
</details>
I'm fine either way, but just pointing out that what Tamir says is that it's equivalent to `rangeCount > mean + 0.5` which is an intuitive way of saying that rangeCount will be closer to mean after subtracting one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KRF_0LvooJYLBY5fA29:b4i1665)*

**Comment by petermattis** [comment]
The default settings in the binary (gossip interval of 5s, rebalance threshold of 0.1) seem to be good. I'll file an issue about reexamining the gossip store interval. 

---

Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/balancer.go, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-KREF0T6nVjVoWsr_u4s:-KRFew3TIMaBZOylz3xi:b-t3evgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/886dc53acd02b926c647b06d57929cbac830ace6/storage/balancer.go#L167)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I'm fine either way, but just pointing out that what Tamir says is that it's equivalent to `rangeCount > mean + 0.5` which is an intuitive way of saying that rangeCount will be closer to mean after subtracting one.
</details>
Yes, the existing expression is a bit unintuitive. I agree it could be simplified and yet my point remains that I wanted to leave it verbatim.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9230#-:-KRFfHzffzgBtxqrTDRU:b5z1qwg)*

**Comment by bdarnell** [comment]
I'm satisfied with the numbers showing that the reduced gossip interval makes a substantial contribution to the reduction in rebalancing, and isn't just wasted resources on top of the increased threshold.

**Comment by tamird** [comment]
This has a non-trivial merge conflict with https://github.com/cockroachdb/cockroach/pull/8959.

**Comment by petermattis** [comment]
I'm sure. I can help you take a look at it tomorrow.

**Pull request merged**
