### PR TITLE
sql/lex: keyword generation improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM on the approach -- good to go after you improve the new generator's main.go, see comments below.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVwEDJQ0fWgAVkuEisw:b-pe9vmb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/all-keywords/main.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDFu36tTxM55aMrjl:-LVwDFu36tTxM55aMrjm:b-h8ss1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L1)):*
> ```Go
> // all-keywords generates sql/lex/keywords.go from sql.y.
> ```

Something in the file properties confuses reviewable and makes it reported as a generated file. This is wrong, we definitely want to review this file.

Also it's missing a copyright header.
___
*[pkg/cmd/all-keywords/main.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDRAZ2nXO1kxJ48pr:-LVwDRAZ2nXO1kxJ48ps:b-v47fmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L26)):*
> ```Go
> 
> func main() {
> 	keywordRE := regexp.MustCompile(`^.*_keyword:`)
> ```

Also I do not find this text more readable than the previous awk code. This is currently a strictly worse development. If you want to improve this, you'll need to add the same amount of explanatory comments there are lines of code here.
___
*[pkg/cmd/all-keywords/main.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDugp0nZmWxIGzEK9:-LVwDugp0nZmWxIGzEKA:b-gc3nez) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9aefb6a908071e9a867ddf984795037b9182c81/pkg/cmd/all-keywords/main.go#L97)):*
> ```Go
> // not a keyword.
> func GetKeywordID(k string) int32 {
> 	// Although odd, manually listing out a full switch statement benchmarked faster than a map lookup.
> ```

You should extend this comment to add a link to the evidence. Someone picking this up 6 months down the line will want to understand this.
___
*[pkg/sql/parser/scan_test.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwE8oMCuLHrsHqhdml:-LVwE8oMCuLHrsHqhdmm:b-imbui4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bbd2779077e6afb185a4eaef376624123dd6a1b/pkg/sql/parser/scan_test.go#L162)):*
> ```Go
> 		var lval sqlSymType
> 		s.scan(&lval)
> 		id := lex.GetKeywordID(kwName)
> ```

nit: `if id := ...; id != ... {`

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/all-keywords/main.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDFu36tTxM55aMrjl:-LVyAkyQ3dHQX_2DdjKn:b-31oaoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Something in the file properties confuses reviewable and makes it reported as a generated file. This is wrong, we definitely want to review this file.

Also it's missing a copyright header.
</blockquote></details>

Added copyright header. I think it's flagged because it contains the string "GENERATED FILE DO NOT EDIT" in the template. github correctly shows it.
___
*[pkg/cmd/all-keywords/main.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDRAZ2nXO1kxJ48pr:-LVy9VYbAhqdHqTr_MjO:bngsv8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also I do not find this text more readable than the previous awk code. This is currently a strictly worse development. If you want to improve this, you'll need to add the same amount of explanatory comments there are lines of code here.
</blockquote></details>

I disagree because:

1) We are a Go company. Me reading the awk code took quite a bit more time to figure out what was going on than a read of the current Go code would have. Converting more of our stuff to Go instead of awk is a sufficient enough reason to me to do work).
2) I did about a half dozen experiments where I code-gen'd lots of different kinds of things. Being able to use Go templates instead of awk saved me lots of time and correctness issues. These various experiments are not written down in the final version, but there is already a comment describing that the motivating factor of this Go program was to enable fast prototyping, which it did. Doing the same prototyping in awk would have been slower (for me).
___
*[pkg/cmd/all-keywords/main.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDugp0nZmWxIGzEK9:-LVyATz97QYbcO3syv-8:bt03bd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9aefb6a908071e9a867ddf984795037b9182c81/pkg/cmd/all-keywords/main.go#L97)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You should extend this comment to add a link to the evidence. Someone picking this up 6 months down the line will want to understand this.
</blockquote></details>

I'll add some caveats to the comment but adding

**Review by petermattis — COMMENTED** [review]
I'm surprised at the speedup, but that's why we benchmark. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVyQ9XCDNYBA3Vlc-tX:b-je1djm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1301 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyP7K35Hdgw4-CvZVV:-LVyP7K35Hdgw4-CvZVW:b-c0eslo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff97cd2a4dc44318c7c9beb13ecaa521ff94057/Makefile#L1301)):*
> ```Makefile
> 
> pkg/sql/lex/keywords.go: pkg/sql/parser/sql.y pkg/cmd/all-keywords/main.go
> 	go run pkg/cmd/all-keywords/main.go < $< > $@.tmp || rm $@.tmp
> ```

FYI, there is another way to achieve this rather than using a separate package. You can create an `sql/parser/all_keywords.go` file containing `main` but with a build tag such as `keywords`. And then run that file with `go run -tags keywords pkg/sql/parser/all_keywords.go`. See `pkg/roachpb/gen_batch.go` for an example. I prefer this approach because it keeps the generator near the code which utilizes it.

**Review by madelynnblue — COMMENTED** [review]
Indeed. I guessed wrong about the expected perf improvements almost every time during this work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVyU7_zDxt1XUsyImTn:b-idjr7o)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[Makefile, line 1301 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyP7K35Hdgw4-CvZVV:-LVyU5i-Cfs4wTa5UPJi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff97cd2a4dc44318c7c9beb13ecaa521ff94057/Makefile#L1301)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

FYI, there is another way to achieve this rather than using a separate package. You can create an `sql/parser/all_keywords.go` file containing `main` but with a build tag such as `keywords`. And then run that file with `go run -tags keywords pkg/sql/parser/all_keywords.go`. See `pkg/roachpb/gen_batch.go` for an example. I prefer this approach because it keeps the generator near the code which utilizes it.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 3 of 3 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lex/all_keywords.go, line 46 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyW2qy3K7qPcQOLjTB:-LVyW2qzDvi9oG7S9rlZ:b-pjap85) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L46)):*
> ```Go
> 	pipeRE := regexp.MustCompile(`[A-Z].*`)
> 
> 	keyword := false
> ```

A comment to explain each of the main variables in the algorithm is generally very useful, more than comments inside the algorithm itself.
___
*[pkg/sql/lex/all_keywords.go, line 57 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyWAWcE9s_gOvHTeMc:-LVyWAWcE9s_gOvHTeMd:b-ybu8i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L57)):*
> ```Go
> 	// subsequent non-empty lines, all words are keywords so add them to our
> 	// data list. An empty line indicates the end of the keyword section, so
> 	// stop recording.
> ```

I love this comment!
___
*[pkg/sql/lex/all_keywords.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyWH4ACNnSu9wFSVBq:-LVyWH4ACNnSu9wFSVBr:bri0t50) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L81)):*
> ```Go
> 	}
> 
> 	sort.Slice(data, func(i, j int) bool {
> ```

A comment here will help. Why does the sort matter?
___
*[pkg/sql/lex/all_keywords.go, line 85 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyWJ7y0pIfpgPUEojP:-LVyWJ7y0pIfpgPUEojQ:bdakao9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L85)):*
> ```Go
> 	})
> 
> 	if err := template.Must(template.New("tmpl").Parse(tmpl)).Execute(os.Stdout, data); err != nil {
> ```

The reader will have no idea what template.Must does, or template.Execute.

Also perhaps for legibility it's worth loading the template at the beginning, and refuse to start processing if that gives an error.
___
*[pkg/cmd/all-keywords/main.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDFu36tTxM55aMrjl:-LVyU49X1a75Qx602OgR:beged1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L1)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Added copyright header. I think it's flagged because it contains the string "GENERATED FILE DO NOT EDIT" in the template. github correctly shows it.
</blockquote></details>

I appreciate you were able to pinpoint the cause of problem but it doesn't make it any less important to solve. Many of us are using reviewable over github for reviews, and if the file is hidden it's too easy to forget to review it.

I think you can solve this by moving the template to a separate .tmpl file.
___
*[pkg/cmd/all-keywords/main.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDRAZ2nXO1kxJ48pr:-LVyUMCDCkrXMP-4-XPx:b-87i2w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L26)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I disagree because:

1) We are a Go company. Me reading the awk code took quite a bit more time to figure out what was going on than a read of the current Go code would have. Converting more of our stuff to Go instead of awk is a sufficient enough reason to me to do work).
2) I did about a half dozen experiments where I code-gen'd lots of different kinds of things. Being able to use Go templates instead of awk saved me lots of time and correctness issues. These various experiments are not written down in the final version, but there is already a comment describing that the motivating factor of this Go program was to enable fast prototyping, which it did. Doing the same prototyping in awk would have been slower (for me).
</blockquote></details>

1. I agree with the motivation, yet...
2. ... that's exactly the point that blinds you from the thrust of my comment. You've produced a big blob of go code here and you're fine with this because you are currently intricately familiar with the logic. It's not the case for me. 

   a. You also can appreciate that awk has only one purpose, and is working line-by-line on the input, the overall structure of the program is always the same, so once you know awk just a little you can reverse-engineer a program super-fast. (I appreciate the fact that you personally didn't know this when you went in *this time*, but you can probably satisfy yourself that once you know one awk program you've seen them all.)
   b. Go in contrast can do arbitrary things, and it's not so clear what to expect if you're not the author. It's really harder to read even if you have previous experience.
   
Meanwhile, you've been known for writing big blobs of go code without comments (eg docgen.go, pretty.go). As a friendly nudge of peer feedback, it's not super nice for the maintainers who need to adjust something in there long after you've left.

i'll provide some concrete suggestions below.

Maybe all that I want is some English prose to help a code reader like me who is not as proficient at Go as you are, to help follow along with the logic.
___
*[pkg/cmd/all-keywords/main.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDugp0nZmWxIGzEK9:-LVyW_CW4vNpjPXEBxDS:bhb6so5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9aefb6a908071e9a867ddf984795037b9182c81/pkg/cmd/all-keywords/main.go#L97)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I'll add some caveats to the comment but adding 
</blockquote></details>

Nice comment! Thank you.

**Review by petermattis — COMMENTED** [review]
I'll let @knz finish reviewing the other changes. The build changes :lgtm:.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVyYu5F1UiCScsuCYX1:bc7g0p6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by madelynnblue — COMMENTED** [review]
Ok I've improved some comments and var names in the generator file. Should be pretty readable now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVye0Tj1KobVqHSv-9O:b6khkop)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/lex/all_keywords.go, line 46 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyW2qy3K7qPcQOLjTB:-LVyc3f3C4N3da9s-upZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L46)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

A comment to explain each of the main variables in the algorithm is generally very useful, more than comments inside the algorithm itself.
</blockquote></details>

Done.
___
*[pkg/sql/lex/all_keywords.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVyWH4ACNnSu9wFSVBq:-LVycgbFCx0EZXxhMN8R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b54f536902f2ab74e77187fd681ee617798a309f/pkg/sql/lex/all_keywords.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

A comment here will help. Why does the sort matter?
</blockquote></details>

Done.
___
*[pkg/cmd/all-keywords/main.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVwDFu36tTxM55aMrjl:-LVybbMO585QcVF7CD6L:bvfh380) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d3ea68d4492699059d05190c01b34025de8c7b2/pkg/cmd/all-keywords/main.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I appreciate you were able to pinpoint the cause of problem but it doesn't make it any less important to solve. Many of us are using reviewable over github for reviews, and if the file is hidden it's too easy to forget to review it.

I think you can solve this by moving the template to a separate .tmpl file.
</blockquote></details>

I have solved this problem by removing the line completely. This is consistent with, for example, our .pb.go files, which only have the first line disclaimer.

**Review by knz — COMMENTED** [review]
Thank you! have you perhaps forgotten to commit your changes to all_keywords.go?

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVyf5zs0_acHKqxST15:bh55sab)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by madelynnblue — COMMENTED** [review]
I think it was github being a bit behind. I had to refresh a few times before it showed the current stuff. Should work for you now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LVyhN1w0wQPlcI20gWA:b-t8wpah)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/lex/all_keywords.go, line 49 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVzC_LWASflVPb8BRoX:-LVzC_LWASflVPb8BRoY:bxvze7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0cac7df864196f3526930491a6d0938c0b80f7/pkg/sql/lex/all_keywords.go#L49)):*
> ```Go
> 	keyword := false
> 	category := ""
> 	seen := map[string]bool{}
> ```

Why do you need `seen`? Shouldn't a keyword appear in only one of the lists?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/lex/all_keywords.go, line 49 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-LVzC_LWASflVPb8BRoX:-LW9eitd-fRghkw9_uxa:ba6pb8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/be0cac7df864196f3526930491a6d0938c0b80f7/pkg/sql/lex/all_keywords.go#L49)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why do you need `seen`? Shouldn't a keyword appear in only one of the lists?
</blockquote></details>

Oops, removed. Was added to an earlier version when I was trying to understand the awk.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33658#-:-LWBWdLm3gZLGHfDo_U_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
