### PR TITLE
storage: minor log message tweaks

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 3222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333#-KiaPg3O0lGKLpflh32k:-KiaPg3O0lGKLpflh32l:b-a5jbuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca131dc1c49a24e422cde8e5f67e2fc3cedb4423/pkg/storage/store.go#L3222)):*
> ```Go
> 				declinedMsg = resp.Message
> 			}
> 			return errors.Errorf("n%d,s%d: remote declined snapshot: %s",
> ```

I don't think we use commas elsewhere. Is there any reason not to log the entire replica descriptor (which I think already has a compact representation)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/store.go, line 3222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333#-KiaPg3O0lGKLpflh32k:-KiaQKYcAXjkeNAr-v-1:bc8hn8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca131dc1c49a24e422cde8e5f67e2fc3cedb4423/pkg/storage/store.go#L3222)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't think we use commas elsewhere. Is there any reason not to log the entire replica descriptor (which I think already has a compact representation)?
</blockquote></details>

That's what node IDs and store IDs look like in log tags which is where I see them logged most frequently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 3222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333#-KiaPg3O0lGKLpflh32k:-KiaS71CgG0sTZoxVdUj:bqwxr6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca131dc1c49a24e422cde8e5f67e2fc3cedb4423/pkg/storage/store.go#L3222)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That's what node IDs and store IDs look like in log tags which is where I see them logged most frequently.
</blockquote></details>

roachpb.RangeDescriptor.String includes some of this formatting (of its replicas); it would be nice to extract a roachpb.ReplicaDescriptor.String that would also be used here. I'm guessing you don't want to do that here, so this is fine as-is :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333#-:-KiaSK8maWi6wc8Bio9H:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/store.go, line 3222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333#-KiaPg3O0lGKLpflh32k:-KiaUl-zHnVfW7oKdQ9i:b-4emn26) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca131dc1c49a24e422cde8e5f67e2fc3cedb4423/pkg/storage/store.go#L3222)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

roachpb.RangeDescriptor.String includes some of this formatting (of its replicas); it would be nice to extract a roachpb.ReplicaDescriptor.String that would also be used here. I'm guessing you don't want to do that here, so this is fine as-is :)
</blockquote></details>

Yeah, I'm going to leave as-is for now. Just noticed that `RangeDescriptor.String` uses `r%d` for replica IDs which is no bueno, so I might fix this sooner than later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15333)*

**Pull request merged**
