### PR TITLE
storage: enable load based splitting by default

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Load based splitting looks stable enough to enable by
default. This may break some tests that rely on specific
range counts. For all such tests, LBS should be turned off.

Release note (general change): Load based splitting enabled
by default.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32306)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-LRI2nz3Be5kp6wqx5el:-LRI2nz3Be5kp6wqx5em:b-dgtv59) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5cd567b18f1ad0d82ec1166c762c7b2ebf83b4/pkg/cmd/roachtest/rebalance_load.go#L141)):*
> ```Go
> 		Name:       `rebalance-leases-by-load`,
> 		Nodes:      nodes(4), // the last node is just used to generate load
> 		MinVersion: "2.2.0",
> ```

We shouldn't restrict the scope of this test just because of the cluster setting that was added in 2.2. It should still work properly in 2.1 (without LBS), right?

@a-robinson should this have had `MinVersion: "2.1.0"` instead of no min version?
___
*[pkg/storage/replica.go, line 6881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-LRI37ZsCilMHhVMJaUV:-LRI37ZsCilMHhVMJaUW:bcieb3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5cd567b18f1ad0d82ec1166c762c7b2ebf83b4/pkg/storage/replica.go#L6881)):*
> ```Go
> 	"kv.range_split.load_qps_threshold",
> 	"the QPS over which, the range becomes a candidate for load based splitting.",
> 	250, // 250 req/s
> ```

Let's put this in a separate commit with an explanation about why we did it.

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32306)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-LRI2nz3Be5kp6wqx5el:-LRI4PBx0f_Lowl5tIfN:bolk2vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5cd567b18f1ad0d82ec1166c762c7b2ebf83b4/pkg/cmd/roachtest/rebalance_load.go#L141)):*
> We shouldn't restrict the scope of this test just because of the cluster setting that was added in 2.2.

Agreed.

> It should still work properly in 2.1 (without LBS), right?

Yes.

> @a-robinson should this have had `MinVersion: "2.1.0"` instead of no min version?

Yes.

**Review by ridwanmsharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32306)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-LRI2nz3Be5kp6wqx5el:-LRJ8zQ47H7r8qN9r-ub:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5cd567b18f1ad0d82ec1166c762c7b2ebf83b4/pkg/cmd/roachtest/rebalance_load.go#L141)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> We shouldn't restrict the scope of this test just because of the cluster setting that was added in 2.2.

Agreed.

> It should still work properly in 2.1 (without LBS), right?

Yes.

> @a-robinson should this have had `MinVersion: "2.1.0"` instead of no min version?

Yes.
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 6881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-LRI37ZsCilMHhVMJaUV:-LRJ9-c554SLXJRY6C4l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba5cd567b18f1ad0d82ec1166c762c7b2ebf83b4/pkg/storage/replica.go#L6881)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's put this in a separate commit with an explanation about why we did it.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: nice work. Happy to have this enabled by default. Now we wait for the test flakes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32306#-:-LRJEfWe9cbyEpKkS73B:by6pvnw)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by a-robinson — APPROVED** [review]
LGTM 🎉🎉🎉

**Pull request merged**
