### PR TITLE
ring: make ring.Buffer generic

### PR DESCRIPTION
**Pull request by ajwerner**
Epic: none

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93736)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/util/tracing/crdbspan.go` line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93736#-NJQfcQ05I4xQLpQ6Vmy:-NJQfcQ05I4xQLpQ6Vmz:bvq0o84) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a0fb42b93dcb5075daef0b8711fcb763830a07/pkg/util/tracing/crdbspan.go#L157)):*
> ```Go
> 	// verbose recording because of the span limit) are not part of this buffer;
> 	// they're in finishedChildren.Root.StructuredRecords.
> 	structured sizeLimitedBuffer[*tracingpb.StructuredRecord]
> ```

do these need to be pointers any more or were they only pointer because they had to be boxed in `interface{}` anyway?
___
*[`pkg/util/tracing/tracer.go` line 970 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93736#-NJQfR7OBG-SIxHUHiOi:-NJQfR7P1L23XQen7CFN:b2ni18w) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a0fb42b93dcb5075daef0b8711fcb763830a07/pkg/util/tracing/tracer.go#L970)):*
> ```Go
> 	tagsAlloc             [3]attribute.KeyValue
> 	childrenAlloc         [4]childRef
> 	structuredEventsAlloc [3]*tracingpb.StructuredRecord
> ```

do

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93736)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/util/tracing/crdbspan.go` line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93736#-NJQfcQ05I4xQLpQ6Vmy:-NJQr6-L5iKvny7bPvCM:b-9g6rtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a0fb42b93dcb5075daef0b8711fcb763830a07/pkg/util/tracing/crdbspan.go#L157)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do these need to be pointers any more or were they only pointer because they had to be boxed in `interface{}` anyway?
</blockquote></details>

I think they want to be pointers because the `protoutil.Message` interface is implemented on the pointer and they're constructed as pointers, no? Also, for better or for worse, the `ring.Buffer` doesn't have a mechanism to get a pointer into the buffer itself. If it did you'd have to be careful about lifecycles. I think it's better to leave them as pointers in this PR. 
___
*[`pkg/util/tracing/tracer.go` line 970 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/93736#-NJQfR7OBG-SIxHUHiOi:-NJQrNNH9ONfDSVKN7zy:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a0fb42b93dcb5075daef0b8711fcb763830a07/pkg/util/tracing/tracer.go#L970)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do 
</blockquote></details>

?

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93736#-:-NJf428EC_Sq8rCWxY5M:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
