### PR TITLE
opt/idxconstraint: recognize stored column expressions

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### deps: update datadriven

Release note: None

#### opt/idxconstraint: recognize stored column expressions

This change makes the index constraint generator aware of computed
column expressions so it can substitute them for the computed column
if it is indexed.

Release note (performance improvement): indexes on computed columns
can now be utilized when filters reference the computed expression and
not the computed column directly.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-:-MKGwHsG27d-XR1xNyH6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKGu_6VAEPZx3hmiLyB:-MKGu_6W77xHSek8Jly3:b2ll34a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/idxconstraint/index_constraints.go#L1428)):*
> ```Go
> }
> 
> // isIndexColumn returns true if ev is a variable on the n indexed var that
> ```

I think this comment is a bit stale

**Review by mgartner — APPROVED** [review]
:LGTM:

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-:-MKfALHC4uyq-k_zYWfH:bmxilld)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/xform/testdata/rules/select, line 1646 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKf9f0ODBCZr6Bm-zbW:-MKf9f0ODBCZr6Bm-zbX:b-pkvd3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/xform/testdata/rules/select#L1646)):*
> ```
>  └── scan computed@l_idx
>       ├── columns: k:1!null
>       ├── constraint: /3/1: [/'foo' - /'foo']
> ```

Maybe the formatted constraint should include the column name, like `/l:3/k:1`? The column ID `3` appears no where else in this output, so it's not clear that it is `l`. No need to make this change for this PR, but something we should think about.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKGu_6VAEPZx3hmiLyB:-MKk3HdeDDgpoOGsqZEt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/idxconstraint/index_constraints.go#L1428)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think this comment is a bit stale
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1646 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKf9f0ODBCZr6Bm-zbW:-MKk3IJb8UbRU_PtbU9E:b-jxqgie) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/xform/testdata/rules/select#L1646)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Maybe the formatted constraint should include the column name, like `/l:3/k:1`? The column ID `3` appears no where else in this output, so it's not clear that it is `l`. No need to make this change for this PR, but something we should think about.
</blockquote></details>

Good idea, I'll look at that separately.

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 9 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKGu_6VAEPZx3hmiLyB:-MKk4E3pCJ39ONe2rbqR:b-jwbgdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/idxconstraint/index_constraints.go#L1428)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It still references `ev` which doesn't exist.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55867#-MKGu_6VAEPZx3hmiLyB:-MKk5r9iAaqageGXnWa_:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f774213f3cd37ec9fe6f6b99a7e1eda43649501/pkg/sql/opt/idxconstraint/index_constraints.go#L1428)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It still references `ev` which doesn't exist.
</blockquote></details>

Fixed.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55867)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Pull request merged**
