### PR TITLE
colexec,coldata: check in generated code

### PR DESCRIPTION
**Pull request by jordanlewis**
The Makefile target for the .eg.go targets is a continued source of
pain. Its dependency management is also very imperfect: it rebuilds all
.eg.go files if any dependencies of execgen change. While this is
technically required, since theoretically execgen's behavior could
change if any of its Go dependencies do, in practice it's almost never
necessary and very irritating when changing base packages.

This commit checks in all .eg.go files. `make generate` will regenerate
.eg.go files, so CI will fail if someone checks in a change that changes
.eg.go files without also checking in the .eg.go changes.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
cc @RaduBerinde @petermattis @knz, we're throwing in the towel to avoid too much rebuild pain. Holler if you have objections.

**Comment by knz** [comment]
No objection from me at this point, given that we're expecting much fewer changes these days than when the machinery was first introduced.

**Review by petermattis — COMMENTED** [review]
No objections from me either. Do we have to backport this to the active release branches? If we don't we could run into strangeness when switching back and forth between release branches and master.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50636#-:-MAfNIG_7Nrb8SjyuCgZ:b-mlakow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[Makefile, line 1758 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50636#-MAfNj45BgaMafIrtrWH:-MAfNj45BgaMafIrtrWI:b1rzm4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5286181aadfe30b39f04a37bf993fa93951ff170/Makefile#L1758)):*
> ```Makefile
> bin/workload bin/docgen bin/execgen bin/roachtest $(logictest-bins): $(SQLPARSER_TARGETS) $(PROTOBUF_TARGETS)
> bin/workload bin/docgen bin/roachtest $(logictest-bins): $(LIBPROJ) $(CGO_FLAGS_FILES)
> bin/workload bin/roachtest $(logictest-bins): ./bin/.execgen_targets
> ```

There are more references to `./bin/.execgen_targets` in the Makefile. I suspect all references to `./bin/.execgen_targets` can be removed or replaced with `$(EXECGEN_TARGETS)`.

**Review by RaduBerinde — APPROVED** [review]
Prepare to become `#2` contributor in terms of lines added. @tbg is still king haha

**Comment by jordanlewis** [comment]
@petermattis, we don't have to backport to release branches because we added code to wipe out unknown .eg.go files earlier.

**Comment by jordanlewis** [comment]
bors cancel

**Comment by petermattis** [comment]
> @petermattis, we don't have to backport to release branches because we added code to wipe out unknown .eg.go files earlier.

Such confidence!

**Comment by jordanlewis** [comment]
Bors is ignoring me >:(

**Comment by tbg** [comment]
It's not running this PR. Bors crashed on ya pal

**Comment by jordanlewis** [comment]
Let's try again

bors r+

**Comment by yuzefovich** [comment]
The build is red, so I'm gonna cancel.

bors r-

**Comment by jordanlewis** [comment]
Ok, build is green and rebased:

bors r+

**Comment by yuzefovich** [comment]
Boom! Jordan, you're a monster - +651,149 lines in a single commit :D

**Comment by jordanlewis** [comment]
Haha, I'm sure to be eclipsed by you soon. It'll just take a few rewrites of this code to accumulate massive diff numbers. I was hoping marking the files as `binary` in `.gitattributes` would avoid these large diff outputs, but I guess not.

**Pull request merged**
