### PR TITLE
sql,jobs: stop depending on streamingccl

### PR DESCRIPTION
**Pull request by pbardea**
Before this commit, some of our protobuf definitions (not defined in the
ccl code-base) referenced ccl types. This commit removes the implicit
casting of the protos and therefore the dependency on ccl code.

Release justification: high-impact (non-ccl code should not bring in ccl
code), low risk (type casts).
Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
In addition to the linting failures, I'm also seeing other violators of this. Will include them in this PR and re-ping when updated.

**Comment by pbardea** [comment]
cc @adityamaru friendly ping

**Review by adityamaru — APPROVED** [review]
Forgot to approve it, sorry! I like the singleton change.

**Comment by pbardea** [comment]
TFTR!
bors r=adityamaru

**Comment by pbardea** [comment]
Bors flaked, rebased.
bors r+

**Pull request merged**
