### PR TITLE
sql: fix duplicated schema change job descriptions

### LINKED ISSUE #80889: sql/drop_index: duplicated schema change job description for DROP INDEX
If `DROP INDEX idx` requires us to also drop a column (as in the case of dropping an expression index or dropping a shared index), the schema change job description is slightly off:

```
CREATE TABLE tbl (a string);
CREATE INDEX expr_idx ON tbl(lower(a));
DROP INDEX expr_idx;
SELECT job_id, description FROM [show jobs] ORDER BY created DESC LIMIT 2;
```

gives us 

```
       job_id       |                                   description
---------------------+----------------------------------------------------------------------------------
  758436656643145729 | GC for DROP INDEX defaultdb.public.tbl@idx; DROP INDEX defaultdb.public.tbl@idx
  758436654120108033 | DROP INDEX defaultdb.public.tbl@idx; DROP INDEX defaultdb.public.tbl@idx
```

The root cause is the following:

https://github.com/cockroachdb/cockroach/blob/f4db23063d12529877622502a8f72e9e51bda119/pkg/sql/drop_index.go#L177-L181

in which `finalizeDropColumn` will attempt to create a schema change job that already exists. Then it will update the existing job by appending the job description, resulting in the duplicated description message.

https://github.com/cockroachdb/cockroach/blob/f4db23063d12529877622502a8f72e9e51bda119/pkg/sql/table.go#L219-L220

Jira issue: CRDB-15465

### PR DESCRIPTION
**Pull request by lkyuchukov**
Fixes #80889 
 
Release note(bug fix):
Fixed a bug that caused duplicated schema change job description messages.

### CODE REVIEW

**Review by Xiang-Gu — APPROVED** [review]
Good work and thank you for contributing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81268#-:-N2C_7hb4qziVT9e1ObN:b-g6nq41)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by Xiang-Gu — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81268#-:-N2C_UP3CVADnm9WTkuf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by rafiss — CHANGES_REQUESTED** [review]
before we merge this, please update the release notes in your commit to match our guidelines: https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes

Specifically, please use full sentences, and explain what changed, how it changed, and why it's relevant to users. 

For this change, I think you should use the category "bug fix" and not "sql change"

**Review by rafiss — APPROVED** [review]
thank you for your contribution!

bors r+

**Pull request merged**
