### PR TITLE
opt: execute SubqueryOp and ExistsOp

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding support for subqueries in the exec builder.

The factory interface is changed with a new `Plan` entity which
encapsulates one or more `Node` trees (one for each subquery). This
corresponds to the `sql.planTop` structure.

In this change we support `SubqueryOp` and `ExistsOp`. We don't support
`AnyOp` because in most cases the subquery is correlated, even for
something like `x IN (subquery)`.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/exec/factory.go, line 117 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeVYmxBgGx3ybOe_ZT:-LAeVYmxBgGx3ybOe_ZU:blqj401) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L117)):*
> ```Go
> 	ExprNode *tree.Subquery
> 	// Type
> 	Type SubqueryType
> ```

How come you need this as a data field? Can't you have a helper method like:
```
func (s Subquery) Type() SubqueryType {
  if s.ExprNode.Exists {
    return SubqueryExists
  }
  return SubqueryOneRow
}
```
Or if there's just the two options, it could be a boolean like it is on `tree.Subquery`.

---

*[pkg/sql/opt/exec/factory.go, line 124 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeVR7aBhMp7O3CqUlL:-LAeVR7aBhMp7O3CqUlM:b-u7ss3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L124)):*
> ```Go
> 
> // SubqueryType indicates how the results of the subquery are to be processed.
> type SubqueryType int
> ```

I'd change `SubqueryType` to `SubqueryKind` or `SubqueryMode`, since `Type` is a pretty overloaded term. When I see `SubqueryType`, my mind instantly assumes it's the subquery's data type.

---

*[pkg/sql/opt/exec/execbuilder/builder.go, line 30 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeWV7H3OwCzQjefGt8:-LAeWV7H3OwCzQjefGt9:b98shkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/builder.go#L30)):*
> ```Go
> 	ev      memo.ExprView
> 
> 	subqueries []exec.Subquery
> ```

A comment on how this is used would be helpful.

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 333 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeSPLZCK3A0en5qmj_:-LAeSPLZCK3A0en5qmja:b-x3h3ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L333)):*
> ```Go
> // addSubquery adds an entry to b.subqueries and associates exprNode with
> // that entry.
> func (b *Builder) addSubquery(exprNode *tree.Subquery, typ exec.SubqueryType, root exec.Node) {
> ```

If you go with my suggestion above to get rid of `exprNode`, this function could become something like:
```
func (b *Builder) addSubquery(kind exec.SubqueryKind, root exec.Node, typ types.T) *tree.Subquery {
```
Doing it this way would also let you allocate the `tree.Subquery` struct inline in the `exec.Subquery` struct (assuming the two have the same lifetime).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955)*

**Comment by andy-kimball** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 312 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAfAd7YE7QgFp9F9cEq:-LAfAd7YE7QgFp9F9cEr:b-vv8ztj) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L312)):*
> ```Go
> 
> func (b *Builder) buildSubquery(ctx *buildScalarCtx, ev memo.ExprView) (tree.TypedExpr, error) {
> 	input := ev.Child(0)
> ```

The code isn't handling the 2nd operand of the `Subquery` operator. This is OK for now, since it's currently always just a reference to the column returned by the input. However, I'm working on a PR where I'll be setting that 2nd operand to an arbitrary expression. We should talk more about the semantics of that, and whether we want to support it in the execbuilder.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/exec/factory.go, line 117 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeVYmxBgGx3ybOe_ZT:-LAmoII0ClgCq9VI3RPC:bu5w838) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L117)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come you need this as a data field? Can't you have a helper method like:
```
func (s Subquery) Type() SubqueryType {
  if s.ExprNode.Exists {
    return SubqueryExists
  }
  return SubqueryOneRow
}
```
Or if there's just the two options, it could be a boolean like it is on `tree.Subquery`.
</blockquote></details>

There will be more modes (here are the modes the current planner uses: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/subquery.go#L66) . We'll probably need one for `Any`.

---

*[pkg/sql/opt/exec/factory.go, line 124 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeVR7aBhMp7O3CqUlL:-LAmot0S3QuTbnqJBZ2J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L124)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd change `SubqueryType` to `SubqueryKind` or `SubqueryMode`, since `Type` is a pretty overloaded term. When I see `SubqueryType`, my mind instantly assumes it's the subquery's data type.
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 312 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAfAd7YE7QgFp9F9cEq:-LAmpo0r0TDFt6RLUnsw:b-49bhro) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L312)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The code isn't handling the 2nd operand of the `Subquery` operator. This is OK for now, since it's currently always just a reference to the column returned by the input. However, I'm working on a PR where I'll be setting that 2nd operand to an arbitrary expression. We should talk more about the semantics of that, and whether we want to support it in the execbuilder.
</blockquote></details>

Oh, I missed that. I'll add a TODO for now. Why does the SubqueryOp need a projection (as opposed to having a ProjectOp as its input)?

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 333 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeSPLZCK3A0en5qmj_:-LAmrW9wB572s6a5ueGo:b4udf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L333)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If you go with my suggestion above to get rid of `exprNode`, this function could become something like:
```
func (b *Builder) addSubquery(kind exec.SubqueryKind, root exec.Node, typ types.T) *tree.Subquery {
```
Doing it this way would also let you allocate the `tree.Subquery` struct inline in the `exec.Subquery` struct (assuming the two have the same lifetime).
</blockquote></details>

Done. I didn't allocate the struct inline, it feels strange to do that in conjunction with `append` which can reallocate

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/builder.go, line 30 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAeWV7H3OwCzQjefGt8:-LAmuFH61Xz2VMUitgAV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/builder.go#L30)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

A comment on how this is used would be helpful.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/subquery.go, line 130 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAms1O49GAUaC3pGtgP:-LAmrhPd8a6ZsNk_K4-m:b-cfledm) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/subquery.go#L130)):*
> ```Go
> 		// For EXISTS expressions, all we want to know is if there is at least one
> 		// row.
> 		ok, err := s.plan.Next(params)
> ```

[nit] I feel like `ok` is kind of overloaded. Maybe use `hasRow` like below?

---

*[pkg/sql/opt/exec/factory.go, line 31 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmtQrP9pNt4mBgxmpo:-LAmtQrP9pNt4mBgxmpp:bsi6n5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L31)):*
> ```Go
> 
> // Plan represents the plan for a query (currently maps to sql.planTop).
> // A Plan contains at least a Node tree, but it could contain more if there are
> ```

This is a bit confusing. Could it contain more `Node`s or more `Node` trees?

---

*[pkg/sql/opt/exec/factory.go, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmuGQ-80ylvQ8-AyK4:-LAmuGQ-80ylvQ8-AyK5:b-qjgslw) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L129)):*
> ```Go
> 	// SubqueryExists: the value of the subquery is a boolean: true if the
> 	// subquery returns any rows, false otherwise.
> 	SubqueryExists = iota
> ```

Do you want to declare this as type `SubqueryMode`?

---

*[pkg/sql/opt/exec/test_engine.go, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmuc170u4d4SCCkgWa:-LAmuc18AieaTARGQPf-:b-pd1ztl) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/test_engine.go#L36)):*
> ```Go
> 	Factory() Factory
> 
> 	// Columns returns the column information for the given execution node
> ```

execution node -> plan

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmvMgp6xdaizzzVAYg:-LAmvMgp6xdaizzzVAYh:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a8233fa3c4d3ab06f037014cbd0f37e5cfe64f/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L55)):*
> ```Go
> 		opt.ArrayOp:           (*Builder).buildArray,
> 		opt.UnsupportedExprOp: (*Builder).buildUnsupportedExpr,
> ```

[nit] extra line

---

*[pkg/sql/sem/tree/expr.go, line 856 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmx9fqDR01DML3ek3d:-LAmx9fqDR01DML3ek3e:bqdd4ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a8233fa3c4d3ab06f037014cbd0f37e5cfe64f/pkg/sql/sem/tree/expr.go#L856)):*
> ```Go
> 			// If the subquery is generated by the optimizer, we
> 			// don't have an actual statement.
> 			noTypesCtx.WriteString("<unknown>")
> ```

Does this mean we can't view a printed version of the subquery? Will this be a problem for debugging?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-:-LAmxhBe4EzG3wO4bSqr:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTRs!

---

Review status: 8 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/subquery.go, line 130 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAms1O49GAUaC3pGtgP:-LAngTKD7MOSpbRSK9jh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/subquery.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I feel like `ok` is kind of overloaded. Maybe use `hasRow` like below?
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/factory.go, line 31 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmtQrP9pNt4mBgxmpo:-LAngkLTDZiHDou193pF:bx599mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L31)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a bit confusing. Could it contain more `Node`s or more `Node` trees?
</blockquote></details>

Clarified (trees).

---

*[pkg/sql/opt/exec/factory.go, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmuGQ-80ylvQ8-AyK4:-LAnh5gv-HAxJxws5lVg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/factory.go#L129)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you want to declare this as type `SubqueryMode`?
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/test_engine.go, line 36 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmuc170u4d4SCCkgWa:-LAnhBh8Ab8Dy2sBPmMg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/test_engine.go#L36)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

execution node -> plan
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 312 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAfAd7YE7QgFp9F9cEq:-LAnhMct6SeXeovNJfaa:b-snu58d) ([raw file](https://github.com/cockroachdb/cockroach/blob/24b3b0e758f5fbd659d01e3e48688b49bb84aeb5/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L312)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, I missed that. I'll add a TODO for now. Why does the SubqueryOp need a projection (as opposed to having a ProjectOp as its input)?
</blockquote></details>

Added code to check that the projection is trivial.

---

*[pkg/sql/opt/exec/execbuilder/scalar_builder.go, line 55 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmvMgp6xdaizzzVAYg:-LAnhHVl0b52EOkVAhsz:b-t6szuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a8233fa3c4d3ab06f037014cbd0f37e5cfe64f/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L55)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

I wanted to keep the subquery ones separate.

---

*[pkg/sql/sem/tree/expr.go, line 856 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-LAmx9fqDR01DML3ek3d:-LAnhPmF2TAqZ4JwLvh8:bc2s65n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a8233fa3c4d3ab06f037014cbd0f37e5cfe64f/pkg/sql/sem/tree/expr.go#L856)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this mean we can't view a printed version of the subquery? Will this be a problem for debugging?
</blockquote></details>

I am not sure when/if this can be useful for debugging. The problem is that in general we can't populate this field - a plan is not necessarily something that can be directly expressed in SQL anymore (e.g. it might have a semi-join).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-:-LAnksOp8Uo5euLlV6di:bz5mair)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24955#-:-LAnrn0D3fy-mh0RfvLm:bnfp4nl)*

**Pull request merged**
