### PR TITLE
pkg/sql: export sql.aggregated_livebytes metric for tenants

### PR DESCRIPTION
**Pull request by jaylim-crl**
#### pkg/util/metric: support metrics removal from the metrics registry 

Previously, once a metric has been added to the metrics registry, it will
always be registered forever, and there isn't a mechanism to remove it. For
multi-tenancy, we plan to implement a job that exports global metrics for
tenants (i.e. such metrics should only exist on one SQL node at any point in
time). Given that jobs can be cancelled and resumed on a different SQL node,
the only option to support such a behavior is to remove metrics from the
registry when the job is no longer running, and this commit adds such support
to it.

Epic: none

Release note: None

#### pkg/sql: export sql.aggregated_livebytes metric in application layer 

Previously, in order to obtain livebytes metrics for tenants, one would need
to query such values via the KV servers, and this can be problematic if we
only have access to just the SQL servers. For example, in CockroachDB Cloud,
only metrics from the SQL servers are exported to end-users, and it done so
directly from the cockroachdb process. It is not trivial to export an
additional subset of metrics from the KV servers filtered by tenant ID.

To address that, this commit exposes livebytes for tenants directly via an
aggregated metric on the SQL nodes. The aggregated metric will be updated
every 30 seconds by default, and will be exported via a singleton job. This
ensures that only one SQL node for a given tenant is aggregating such metric
at any point in time. Unlike other job metrics where metrics are registered at
initialization time and stays forever, this aggregated metric is tied to the
lifespan of the job (i.e. it is only exported if the job is running, and
unexported otherwise).

To create such a job, a new `crdb_internal.create_tenant_global_metrics_exporter_job`
built-in has been added. The plan is to backport the changes in this commit
into 23.2, and a follow-up commit will automatically create such a job via
a permanent migration (which won't be backported).

No release note for this commit since the job is opt-in only, and bulitin will
only be used by CockroachDB Cloud while we transition to the permanent upgrade
in 24.1.

Epic: none

Release note: None

#### pkg/upgrades: add permanent upgrade for the tenant global metrics exporter job

This commit adds a new cluster version to represent a permanent upgrade for
the tenant global metrics exporter singleton job. With this upgrade, tenants
will automatically run the global metrics exporter job, which currently only
aggregates and exports the livebytes metric.

Note that this cluster version will not be backported to versions prior to
24.1, and users will have to resort to the crdb_internal built-in that was
added in the previous commit.

Epic: none

Release note (sql change): This change adds a new tenant global metrics
exporter automatic job. The job currently aggregates livebytes from the
storage nodes, and exports them as a new `sql.aggregated_livebytes` metric.
These metrics will only be exported as long as the job is running, and are
updated at an interval defined by the `tenant_global_metrics_exporter_interval`
cluster setting, which defaults to 30 seconds.

### CODE REVIEW

**Comment by jaylim-crl** [comment]
`TestRetriesWithExponentialBackoff` failing seems to be a common flake under stress: https://github.com/cockroachdb/cockroach/issues/115552.

**Comment by dt** [comment]
Can you add epic or issue links?

Based on the commit descriptions it sounds like you’re intending to backport the definition of the new job type; historically this has _not_ been safe, with at least some number of code paths where a node that encountered an unknown job type would crash, so I’m not confident that this new job will be able to backport, at least not without a deep audit of a lot of jobs code.

**Comment by jaylim-crl** [comment]
We had some discussions offline. I’m going to convert this back into a draft for now.

**Comment by jaylim-crl** [comment]
Closing this in favor of #119140. I took a different approach there:
1. We reused the existing MVCC statistics update job instead of adding a new job or permanent uprgade.
2. SpanStats was used to query the aggregated livebytes instead of querying individual ranges.

I like (1) better as there's no additional work needed on our end (e.g. cluster setting, built in, etc). The backport is optional, but can be done so easily if we want to.

**Pull request closed without merging**
