### PR TITLE
storage: remove excessive new range lease logging

### PR DESCRIPTION
**Pull request by spencerkimball**
Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31644)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_proposal.go, line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31644#-LPCiVd866vQJQW657cz:-LPCiVd866vQJQW657d-:bran1rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c22a1e0bba16ef1a49813bdbc7d810680e87b4/pkg/storage/replica_proposal.go#L212)):*
> ```Go
> 		// logging is enabled).
> 		if newLease.Type() == roachpb.LeaseEpoch && leaseChangingHands || log.V(1) {
> 			log.VEventf(ctx, 1, "new range lease %s following %s", newLease, prevLease)
> ```

This has historically been pretty useful in tracking down problems, though. I'd be interested in hearing from @tschottdorf, @bdarnell, @nvanbenschoten, and @a-robinson about whether this has been useful recently.

**Review by a-robinson — COMMENTED** [review]
Are you basing the need for this on the logs you see on v2.1-beta nodes? Because it's already been made more quiet once since v2.0 - https://github.com/cockroachdb/cockroach/pull/29113

**Comment by spencerkimball** [comment]
It's just impractical when you have tens of thousands of ranges, much less 1M, which is what I'm testing right now. The logs are 99.99% range lease messages.

**Comment by spencerkimball** [comment]
Yes, it logs every range at startup.

**Review by bdarnell — APPROVED** [review]
It's been a while since I've found this message useful.

**Pull request merged**
