### PR TITLE
security: update min password length setting docs

### PR DESCRIPTION
**Pull request by rmloveland**
Update docs for the cluster setting `server.user_login.min_password_length` to clarify that the setting only applies when adding new users or altering an existing user's password; it does not affect existing users' passwords.

Fixes DOC-10060

### CODE REVIEW

**Comment by rmloveland** [comment]
@fqazi any objections to merging this docstring update?  happy to revise it as needed!

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122024#-:-NvXwo4H6XwE6hmd_A5u:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rmloveland)

**Pull request merged**
