### PR TITLE
changefeedccl: Merge adjacent spans in the frontier.

### PR DESCRIPTION
**Pull request by miretskiy**
Harden span frontier API against bugs at the call sites by
changing frontier methods to return an error instead of panic-ing.

Implement frontier benchmark to mesure frontier performance.

Rewrite frontier `Forward` implementation to be a single pass
over the tree of spans.  Update all required timestamps in one
pass, while merging adjacent spans that have advanced to the
same timestamp.

The implementation no longer scales sub-linearly, and has much
better per op performance, and much lower per op allocations.

The difference between old and new code is substantial, with the old code
able to perform 10000 operations, each around 6.5 milliseconds

```
BenchmarkFrontier-16               10000           6496607 ns/op         2655966 B/op      20599 allocs/op
```

The new code was able to execute over 1/2 million ops, at around 2.5 microseconds.
```
BenchmarkFrontier-16              544978              2250 ns/op             806 B/op         17 allocs/op
```

Release Notes: None

### CODE REVIEW

**Review by stevendanna — CHANGES_REQUESTED** [review]
That seems like a really nice performance win.  Perhaps include some benchstat output in the commit message?

Perhaps it would be good to add a test or two around our range merging behaviour specifically?

> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-:-Ma3Sl548Eyl7JjYCF5L:bz1g8z2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

___
*[pkg/util/span/frontier.go, line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3Ym0O-B6jB1u39zZg:-Ma3Ym0O-B6jB1u39zZh:bgj5vzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L175)):*
> ```Go
> // ranges all have specified timestamp.
> // Updates provided range with the new starting position.
> // Returns the list of frontier entries covered by the updated range.
> ```

Since this is an internal function, perhaps we could remind the reader here how this is expected to be used.  Namely, that you should remove the returned entries from the tree if you are going to add the input range to the tree.
___
*[pkg/util/span/frontier.go, line 279 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3XocR3kn-xQHIr6sb:-Ma3XocR3kn-xQHIr6sc:b-xcgcrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L279)):*
> ```Go
> 
> 		// If overlap does not start immediately after our mergedSpan,
> 		// then add and reset pending.
> ```

I kinda wonder with `pendingSpan` and `addPending` might be better name just to make it clear that that is our accumulator.
___
*[pkg/util/span/frontier.go, line 323 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3ZCZNBuGb5ib9CTE-:-Ma3ZCZNBuGb5ib9CTE0:b-h5xdi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L323)):*
> ```Go
> 				// We can also attempt to merge more ranges with the same timestamp to the right
> 				// of overlap.
> 				toRemove = append(toRemove, extendRangeToTheRight(f.tree, &mergedSpan, insertTS)...)
> ```

I think my only main stumbling block when reviewing this code was at this point since you have to recall that `extendRangeToRight` modified mergedSpan, that mergedSpan will latter be added to the toAdd list, and that the return value here are the spans that got merged.  There isn't a change to make, but I just wanted to call it out for other reviewers in case it helps.

**Review by miretskiy — COMMENTED** [review]
Testing can always be expanded -- but if you noticed, there were some todo's in the test -- and I addressed those todos by checking for merged spans:

```
	// Forward them all at once (spans don't collapse for now, this is a TODO).
	adv = f.Forward(spAD, hlc.Timestamp{WallTime: 6})
	require.Equal(t, true, adv)
	require.Equal(t, hlc.Timestamp{WallTime: 6}, f.Frontier())
	require.Equal(t, `{a-b}@6 {b-c}@6 {c-d}@6`, f.entriesStr())
```

got changed to 

```
	// Forward them all at once.
	forwardFrontier(spAD, 6).
		expectedAdvanced(true).
		expectFrontier(6).
		expectEntries(`{a-d}@6`)

```

I also just added another test case to disjoint test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-:-Ma9dP8Z876ozyfvedqr:b-yndh2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

___
*[pkg/util/span/frontier.go, line 175 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3Ym0O-B6jB1u39zZg:-Ma9bvnrDaNoR3MrOwFl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L175)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Since this is an internal function, perhaps we could remind the reader here how this is expected to be used.  Namely, that you should remove the returned entries from the tree if you are going to add the input range to the tree.
</blockquote></details>

Done.
___
*[pkg/util/span/frontier.go, line 279 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3XocR3kn-xQHIr6sb:-Ma9bx0HAVN3Ytgu8jJS:b-7w2e73) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L279)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I kinda wonder with `pendingSpan` and `addPending` might be better name just to make it clear that that is our accumulator.
</blockquote></details>

Funny you mentioned this.  I was going back and forth between merged and pending :)
___
*[pkg/util/span/frontier.go, line 323 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3ZCZNBuGb5ib9CTE-:-Ma9d8cK2camhzPTgFy6:b-h7km2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L323)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think my only main stumbling block when reviewing this code was at this point since you have to recall that `extendRangeToRight` modified mergedSpan, that mergedSpan will latter be added to the toAdd list, and that the return value here are the spans that got merged.  There isn't a change to make, but I just wanted to call it out for other reviewers in case it helps.
</blockquote></details>

I hear you.  This code is tricky.  I expanded the comment.  Do you think it's clearer now? Anything else I can improve?

**Review by stevendanna — APPROVED** [review]
Ah, I hadn't quite noticed that actually, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-:-MaA0szP-XI3Xgq1e9W_:b-94d13t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-MaA1FeHDyjBeEDo8kmf:-MaA1FeHDyjBeEDo8kmg:b-yl7rva) (no related file):*
Overall this :lgtm: 

---
___
*[pkg/util/span/frontier.go, line 323 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65354#-Ma3ZCZNBuGb5ib9CTE-:-MaA19cq7Y0fNAFI96Yi:b-q8477h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3393c8da78049877b0b77ec267d965ec08d8e451/pkg/util/span/frontier.go#L323)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I hear you.  This code is tricky.  I expanded the comment.  Do you think it's clearer now? Anything else I can improve?
</blockquote></details>

Definitely helpful!

**Comment by miretskiy** [comment]
tftr
bors r=stevendanna

**Comment by shermanCRL** [comment]
Did we consider a backport here?

**Pull request merged**
