### PR TITLE
client: add unittest to client/txn.go to verify txn don't change keys on restart

### LINKED ISSUE #5492: client: add unittest to client/txn.go to verify txn's don't change keys on restart
...even if the first command in the transaction is a put with a different key than the first time the transaction was started see the code in `client/txn.go`:
```
// If the transaction already has a key (we're in a restart), make
		// sure we set the key in the begin transaction request to the original.
		if txn.Proto.Key != nil {
			bt.Key = txn.Proto.Key
		}
```

### PR DESCRIPTION
**Pull request by yaojingguo**
client: add unittest to client/txn.go to verify txn don't change keys on restart

Fixes #5492

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7544)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[client/txn_test.go, line 438 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVvujmtlICcPTvyElp:-KLVvujmtlICcPTvyElq:-287572609) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L438)):*
> ```Go
> 	firstTry := true
> 	db := NewDB(newTestSender(nil, func(ba roachpb.BatchRequest) (*roachpb.BatchResponse, *roachpb.Error) {
> 		var bt *roachpb.BeginTransactionRequest
> ```

https://godoc.org/github.com/cockroachdb/cockroach/roachpb#BatchRequest.GetArg

---

*[client/txn_test.go, line 452 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVwRkxySijx0_mXVnc:-KLVwRkyK0Vaw_OB5tU8:523225003) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L452)):*
> ```Go
> 
> 		var expectedKey roachpb.Key
> 		if firstTry {
> ```

why does the expected key change? isn't that the opposite of what's supposed to be tested here?

---

*[client/txn_test.go, line 476 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVw4sGzcxS05dMKGmw:-KLVw4sGzcxS05dMKGmx:340752601) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L476)):*
> ```Go
> 		return nil
> 	}); err != nil {
> 		t.Errorf("unexpected error on commit: %s", err)
> ```

need to assert that the transaction was actually retried

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Comment by yaojingguo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[client/txn_test.go, line 438 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVvujmtlICcPTvyElp:-KLZ7c0SgZipFGntd0_8:404540358) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L438)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> https://godoc.org/github.com/cockroachdb/cockroach/roachpb#BatchRequest.GetArg
</details>
Done in the new commit.

---

*[client/txn_test.go, line 452 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVwRkxySijx0_mXVnc:-KLZ7fPp2av0tArBL8Yy:505261377) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L452)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why does the expected key change? isn't that the opposite of what's supposed to be tested here?
</details>
In the first try, the transaction's key should be set to the key of the first write command which is `testKey` by `txn.send`. After the first try is finished, the transaction key is set to `txnKey` by https://github.com/cockroachdb/cockroach/blob/master/internal/client/txn_test.go#L53. `txn.send` honors this transaction key by https://github.com/cockroachdb/cockroach/blob/master/internal/client/txn.go#L647. So in the second try, the transaction's key should be set to `txnKey`.

The test is to verify that after the transaction key is set to `txnKey`, it will not be changed by `txn.send`.

---

*[client/txn_test.go, line 476 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLVw4sGzcxS05dMKGmw:-KL_FcosUuwrQJt8zcJ0:404540358) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3dddfdcc683e9988f8d406150c2743247f37ed/client/txn_test.go#L476)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> need to assert that the transaction was actually retried
</details>
Done in the new commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[internal/client/txn_test.go, line 437 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcXyt5C4Gl4XYWR0Pq:-KLcXyt5C4Gl4XYWR0Pr:1940103965) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L437)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	tries := 0
> 	expectedTries := 2
> ```

i'm not sure you need to test that exactly two tries happened, just more than one.

---

*[internal/client/txn_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcXuN1IU_3ljhmKgtz:-KLcXuN1IU_3ljhmKgu-:-1450858799) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L446)):*
> ```Go
> 		}
> 
> 		// In the frist try, the transaction key is the key of the first write command. Before the
> ```

s/frist/first/

---

*[internal/client/txn_test.go, line 458 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcYKXjd9dJfoP3dWl4:-KLcYKXjd9dJfoP3dWl5:172911027) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L458)):*
> ```Go
> 			t.Fatalf("No. %d try is being made. At most %d tries can be made", tries, expectedTries)
> 		}
> 		if !reflect.DeepEqual(expectedKey, bt.Key) {
> ```

`if !expectedKey.Equal(bt.Key) {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-:-KLcYyc62wF2xbT_wKaG:1417088721)*

**Comment by yaojingguo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[internal/client/txn_test.go, line 437 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcXyt5C4Gl4XYWR0Pq:-KLd7tKBMAHqxZk7d-WQ:713397345) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L437)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i'm not sure you need to test that exactly two tries happened, just more than one.
</details>
Now check that more than one tries are made. Done in a new commit.

---

*[internal/client/txn_test.go, line 446 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcXuN1IU_3ljhmKgtz:-KLd0SjPDNZbJJG3wkpC:-1857981642) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L446)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/frist/first/
</details>
Done in a new commit.

---

*[internal/client/txn_test.go, line 458 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcYKXjd9dJfoP3dWl4:-KLd16QjxoH4UrrIRE_0:236005940) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L458)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `if !expectedKey.Equal(bt.Key) {`
</details>
I prefer to use `!bt.Key.Equal(expectedKey) `. Is it OK for you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[internal/client/txn_test.go, line 458 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLcYKXjd9dJfoP3dWl4:-KLdNLE3ozlgWl_uOpH3:1727517720) ([raw file](https://github.com/cockroachdb/cockroach/blob/a43f44d50a79f8e14b939bf9e1fc1b76a3dea530/internal/client/txn_test.go#L458)):*
<details><summary><i>Previously, yaojingguo (Jingguo Yao) wrote…</i></summary>
> I prefer to use `!bt.Key.Equal(expectedKey) `. Is it OK for you?
</details>
yep, agree that's better.

---

*[internal/client/txn_test.go, line 453 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLdNS1BKTM0pSv_3jtF:-KLdNS1BKTM0pSv_3jtG:468484186) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5ff0e98976e7c083a1590b0c4d5355fcc6031e/internal/client/txn_test.go#L453)):*
> ```Go
> 		case 1:
> 			expectedKey = testKey
> 		case minimumTries:
> ```

how about `default:` here? then you can move `minimumTries` all the way to the bottom assertion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Comment by yaojingguo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[internal/client/txn_test.go, line 453 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544#-KLdNS1BKTM0pSv_3jtF:-KLeM4QW3D1FwzV0fLoe:-68357636) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d5ff0e98976e7c083a1590b0c4d5355fcc6031e/internal/client/txn_test.go#L453)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how about `default:` here? then you can move `minimumTries` all the way to the bottom assertion.
</details>
`minimumTries` is moved to the bottom assertion in the new commit. But `if else` is used instead of `switch`. Is it OK  for you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7544)*

**Pull request merged**
