### PR TITLE
storage: add setting to seed up consistency checks in tests

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, we'd fall back to the 3 second consistency checker EventuallyFileOnlySnapshot (EFOS) wait in roachtests, which was slowing all of
them down when we ran every replica through the consistency checker in post-test assertions. This change speeds up that consistency check in roachtest post-test assertions by flipping a new cluster setting to speed up EFOS waits for consistency checks after a roachtest finishes.

Epic: none
Unblocks #116330.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Does this imply that running `crdb_internal.check_consistency()` is going to be generally slow?

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116892#-:-NmBccf5E90uIpaOTs68:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @DarrylWong, @itsbilal, and @srosenberg)

___
*[`pkg/storage/engine.go` line 638 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116892#-NmBbCQo97lxCVz_pv9p:-NmBbCQpEDWi7XxwTUby:bas7pl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb9b7444571e0bea7b83efe6df2fbabcd448fdf/pkg/storage/engine.go#L638)):*
> ```Go
> 	// argument specifies how long to wait for before attempting a flush to
> 	// force a transition to a file-only snapshot.
> 	WaitForFileOnly(context.Context, time.Duration) error
> ```

[nit] I'd name give the parameter a useful name, maybe `gracePeriodBeforeFlush`. Ideally we'd plumb that through the implementation - `dur` is not useful, and in fact is misleading: a generic duration argument to a method like `Wait` usually means that we'll give up waiting after that duration.

**Review by itsbilal — COMMENTED** [review]
TFTR!

@erikgrinaker that's correct but only if we're running that command with little/no background writes happening. Flushes will result in forward progress on `WaitForFileOnly` without the 3 second wait.

In general when we were making this change, we were under the impression that consistency checks are usually a background operation. If this is an undesirable knock-on effect of this change we can look into ways to speed up consistency checks too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116892#-:-NmCD_zB9cbIbvIMGSzP:bv2msw6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @DarrylWong, and @srosenberg)

___
*[`pkg/storage/engine.go` line 638 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116892#-NmBbCQo97lxCVz_pv9p:-NmCq0YW8pIS9aFNC_X6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb9b7444571e0bea7b83efe6df2fbabcd448fdf/pkg/storage/engine.go#L638)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd name give the parameter a useful name, maybe `gracePeriodBeforeFlush`. Ideally we'd plumb that through the implementation - `dur` is not useful, and in fact is misleading: a generic duration argument to a method like `Wait` usually means that we'll give up waiting after that duration.
</blockquote></details>

Done.

**Comment by itsbilal** [comment]
bors r=RaduBerinde

**Review by erikgrinaker — COMMENTED** [review]
>we were under the impression that consistency checks are usually a background operation. If this is an undesirable knock-on effect of this change we can look into ways to speed up consistency checks too.

That's generally true, except for `crdb_internal.check_consistency()`. I doubt it's used much outside of tests. We could consider disabling EFOS for foreground consistency checks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116892#-:-Nn9RJvlAFC0WmRUMtvf:bc5yog1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
> That's generally true, except for crdb_internal.check_consistency(). I doubt it's used much outside of tests. We could consider disabling EFOS for foreground consistency checks.

We do know at this level whether we're running on behalf of the consistency queue or on behalf of the `crdb_internal.check_consistency()` builtin. The `mode` param will have a value of `ChecksumMode_CHECK_VIA_QUEUE` when from the queue and either `ChecksumMode_CHECK_FULL` or `ChecksumMode_CHECK_STATS` when manually run.

It would probably make sense to disable EFOS for both. If not, we should at least do it for `ChecksumMode_CHECK_STATS`, which doesn't iterate over the range and should be quick.

**Comment by nvanbenschoten** [comment]
I'll make the less contentious change for now. https://github.com/cockroachdb/cockroach/pull/117297.

**Comment by erikgrinaker** [comment]
blathers backport 23.2

**Comment by erikgrinaker** [comment]
Nevermind, I guess we didn't enable this by default for 23.2.

**Pull request merged**
