### PR TITLE
server: kill dead code for snappy-compressed http

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6542)

### CODE REVIEW

**Comment by dt** [comment]
note this doesn't remove the dep from glock since we still transitively pull it in via c-rocksdb.

**Comment by tamird** [comment]
Lgtm. Do we still want to keep gzip?

**Comment by bdarnell** [comment]
LGTM. We should keep gzip unless it's handled automatically for us at lower levels of the stack (and I don't think it is).

**Comment by dt** [comment]
It isn't IIRC, though just about everyone has published their own fancy "middleware" for it.

**Pull request merged**
