### PR TITLE
opt: use paired joins for left semi inverted joins

### PR DESCRIPTION
**Pull request by sumeerbhola**
Semi joins using the inverted index used to be converted
to an inner inverted join followed by an inner lookup join
and a distinct for de-duplication. They are now converted
to paired-joins consisting of an inner inverted join
followed by a left semi lookup join, which is more
efficient.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-:-MKb0Gxo-h9YdqgFoRby:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/opt/xform/join_funcs.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKb-m-G6XrdXs-adPWe:-MKb-m-G6XrdXs-adPWf:b-6d2x8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5863460731a07d763f5800ec04c1a9792b98b02d/pkg/sql/opt/xform/join_funcs.go#L467)):*
> ```Go
> 		continuationCol := opt.ColumnID(0)
> 		invertedJoinType := joinType
> 		// Anti/semi joins are converted to a pair consisting of a left join and
> ```

is there any way we can use an inner join for the first join when the second is a semi join?
___
*[pkg/sql/opt/xform/rules/join.opt, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKb06HB0IQTNCGHgOf0:-MKb06HB0IQTNCGHgOf1:b-piucar) ([raw file](https://github.com/cockroachdb/cockroach/blob/5863460731a07d763f5800ec04c1a9792b98b02d/pkg/sql/opt/xform/rules/join.opt#L151)):*
> ```
> # custom function for more details.
> # TODO(rytaft): Add support for SemiJoin. Currently it is supported by first
> # converting it to InnerJoin using the rule ConvertSemiToInnerJoin.
> ```

remove TODO

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-:-MKbEvBk28botVeGbr9u:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKb-m-G6XrdXs-adPWe:-MKbEOkT4WtLry_sGUtc:b-t2kke1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5863460731a07d763f5800ec04c1a9792b98b02d/pkg/sql/opt/xform/join_funcs.go#L467)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there any way we can use an inner join for the first join when the second is a semi join?
</blockquote></details>

That was silly of me. I thought I'd forgotten to add support for a continuation column for inner joins, but I had actually added that for exactly this reason (and it's even explained in the comment for `InvertedJoinerSpec`).

Done.
___
*[pkg/sql/opt/xform/rules/join.opt, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKb06HB0IQTNCGHgOf0:-MKbEN4I5EU_pTWVo8at:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5863460731a07d763f5800ec04c1a9792b98b02d/pkg/sql/opt/xform/rules/join.opt#L151)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

remove TODO
</blockquote></details>

Done

**Review by rytaft — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-:-MKbFzxS5RvyOAZXh7Ey:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/xform/join_funcs.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKbGDpZ62kfB3jtQlaK:-MKbGDpZ62kfB3jtQlaL:bjrd5vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12a12a6ba921ecf2f297efe18cc07114b489774/pkg/sql/opt/xform/join_funcs.go#L475)):*
> ```Go
> 			// Semi joins are converted to a pair consisting of an inner inverted
> 			// join and semi lookup join.
> 			continuationCol = c.constructContinuationColumnForPairedLeftJoin()
> ```

[nit] maybe rename this function to just be PairedJoin instead of PairedLeftJoin

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-MKbGDpZ62kfB3jtQlaK:-MKbMxis9Fsc-kvqfz70:b46nbdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12a12a6ba921ecf2f297efe18cc07114b489774/pkg/sql/opt/xform/join_funcs.go#L475)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] maybe rename this function to just be PairedJoin instead of PairedLeftJoin
</blockquote></details>

The original intention was for "left join" to refer to the overall join (which is a left semi/anti/outer join). But I see why this can be confusing. I've renamed it as you suggested, and added a sentence to the function comment.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by rytaft** [comment]
Don't forget to update the PR message to change left outer -> inner

**Review by sumeerbhola — COMMENTED** [review]
Thanks for the reminder. Done. I wish it would sync from the commit message for a single commit PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55986#-:-MKe2imo0VAjaWgxpGd_:b-xbuf9r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by rytaft** [comment]
Yea... that would be nice

**Pull request merged**
