### PR TITLE
sql: Add support for SERIAL2, SERIAL4, and SERIAL8 types

### PR DESCRIPTION
**Pull request by hjames9**
Release note (sql change): Added aliases for SERIAL types.

These aliases match types used in PostgreSQL.  They also make it consistent with the integer types (INT2, INT4, INT8).
https://www.postgresql.org/docs/9.5/static/datatype-numeric.html#DATATYPE-SERIAL

Related issue: #20774

### CODE REVIEW

**Comment by knz** [comment]
Thanks @hjames9 for your contribution.
This looks good! Just a minor suggestion.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/coltypes/arith.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-L0dDxxgoubTTZU5jwgl:-L0dDxxhW5CcvO8To8Lc:b-kz8uax) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a11c12d00691eb11125262f9b2131a4f68db52/pkg/sql/coltypes/arith.go#L52)):*
> ```Go
> // incrementing function.
> func (node *TInt) IsSerial() bool {
> 	return node.Name == Serial.Name || node.Name == SmallSerial.Name ||
> ```

Place replace all this code by a single access to a `map[string]bool`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-:-L0dE6QeV-n-EU32AdsW:boghpt1)*

**Comment by hjames9** [comment]
@knz Thanks for the feedback.  But where would be the appropriate place to initialize this static map?  Should it be part of the TInt structure and then each instance would be responsible for creating the map?

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/coltypes/arith.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-L0dDxxgoubTTZU5jwgl:-L0dZE0fq1BGzls_lU6U:b-8uyrg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a11c12d00691eb11125262f9b2131a4f68db52/pkg/sql/coltypes/arith.go#L52)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Place replace all this code by a single access to a `map[string]bool`.
</blockquote></details>

```go
var serialIntTypes map[string]struct{} {
  Serial.Name: {},
  BigSerial.Name: {},
  ...
}

func (node *TInt) IsSerial() bool {
   _, ok := serialIntTypes[node.Name]
   return ok
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776)*

**Comment by hjames9** [comment]
@knz Thanks, I've committed the suggested change and tests passed.

**Comment by knz** [comment]
Excellent! 
Just one bit left, then please squash the two commits together before we can merge this.
Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/coltypes/arith.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-L0dxlY55XXH1dGC2yQd:-L0dxlY6osNWOgcaOYtG:b-ol8f22) ([raw file](https://github.com/cockroachdb/cockroach/blob/141d88b07e23d74f6fc112100807f862c0527157/pkg/sql/coltypes/arith.go#L41)):*
> ```Go
> }
> 
> var serialIntTypes = map[string]struct{}{
> ```

Move the definition of this map to just above or below `IsSerial` above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-:-L0dxpMRndejivBCmc0c:btgz9oi)*

**Comment by hjames9** [comment]
@knz Looks like I got it now.

**Comment by knz** [comment]
Yes! Perfect. Thank you!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20776#-:-L0e_gF6cMwlva2nNGVI:b8uhxkm)*

**Comment by vilterp** [comment]
My fault for being slow on the draw here (distracted by other things), but I'm a little concerned that this could create confusion, since the `SERIAL` type is used to hold values from the `unique_rowid` function, which returns values that actually take up all 64 bytes (since they include a timestamp, node id, and I think maybe a tiebreaker value).

This won't immediately break because the type is still 64 bits, but people might think that they can cram `unique_rowid` values into less than 64 bits in their application code.

What do you think @knz? Also cc @lhirata

**Comment by jordanlewis** [comment]
Yeah this is sketchy indeed - do the new `SERIAL` types validate their input sizes?

Our other alias types do:

```
root@:26257/test> create table ss (a int2);
CREATE TABLE

Time: 6.395ms

root@:26257/test> insert into ss values(10000);
INSERT 1

Time: 3.946ms

root@:26257/test> insert into ss values(1000090000);
pq: integer out of range for type SMALLINT (column "a")
```

**Comment by vilterp** [comment]
Looks like it just accepts values bigger than its input size:

```
root@:26257/test> create table test (id serial2 primary key, foo text);
CREATE TABLE

Time: 7.234ms

root@:26257/test> insert into test (foo) values ('derp');
INSERT 1

Time: 3.47ms

root@:26257/test> select * from test;
+--------------------+------+
|         id         | foo  |
+--------------------+------+
| 306884757024014337 | derp |
+--------------------+------+
(1 row)

Time: 1.707ms

root@:26257/test>
```

**Comment by hjames9** [comment]
I can send another PR to fix the size validation for SERIAL2 and SERIAL4.  Is that the only issue?

**Comment by bdarnell** [comment]
Note that we've already supported `SMALLSERIAL` as an alias for our 64-bit `SERIAL`, even though in postgres `SMALLSERIAL` is `SERIAL2`. Even `SERIAL` itself is different from postgres: in postgres it's 4 bytes, and in cockroach it's 8. 

Simply adding size validation won't help, because the values generated by `unique_rowid()` won't fit in anything less than 64 bits. We'd need to switch to a `SEQUENCE`-backed implementation of `SERIAL`. This would bring us closer to postgres compatibility, but it would be expensive. I'd rather not support SMALLSERIAL/SERIAL2 at all than use them as a reason to make the more common SERIAL more expensive (what's the use case for such a constrained serial type?). OTOH, it *might* be justifiable to make SERIAL a sequence-backed 4-byte int instead of our current 8-byte int. A few libraries have trouble with this discrepancy already.

**Comment by hjames9** [comment]
This is exactly why I made the change this way, because that's how
SMALLSERIAL was already working.  Just wanted to create a simple alias to
match Postgres and not change any of the underlying implementation.

**Comment by knz** [comment]
@bdarnell so we can agree that this PR was worth merging for now, and that we can do sequence-based SERIAL later in a different RFC+PR?

**Comment by bdarnell** [comment]
Yes, I'm fine with this PR for now. Any change to use sequences for SERIAL would be a separate RFC (that I'm sure would attract a lot of controversy).

**Pull request merged**
