### PR TITLE
log: output the goroutine ID in log message headers

### PR DESCRIPTION
**Pull request by petermattis**
Change EntryDecoder to be able to parse headers both with and without a
goroutine ID.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8977)

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @cockroachdb/stability 

This was useful in tracking down what was happening in #8974.

**Comment by a-robinson** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/log/clog.go, line 473 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-KQVoHRae4WiDkyV7O1O:-KQVoHRae4WiDkyV7O1P:bn5jxt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/34603f92a3c13cd289c147f47b3aa74a61d9af52/util/log/clog.go#L473)):*
> ```Go
> // 	dd               The day (zero padded)
> // 	hh:mm:ss.uuuuuu  Time in hours, minutes and fractional seconds
> // 	goid             The goroutine id (if non zero)
> ```

When will it be zero? Optional fields in logs can be somewhat frustrating and surprising to consumers of those logs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977)*

**Comment by petermattis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/log/clog.go, line 473 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-KQVoHRae4WiDkyV7O1O:-KQW5Oft_TUqjq4XoSS5:bysvv30) ([raw file](https://github.com/cockroachdb/cockroach/blob/34603f92a3c13cd289c147f47b3aa74a61d9af52/util/log/clog.go#L473)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> When will it be zero? Optional fields in logs can be somewhat frustrating and surprising to consumers of those logs
</details>
It is only 0 for tests so that we can test reading both the old and new headers with `EntryDecoder`. In practice, moving forward, we will always output the goroutine ID. I'll clarify the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r2, 2 of 9 files at r3.
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-:-KQW9Mi2nYmXQKO71e4g:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-:-KQWFJtWL3SIItpCM7sQ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Nice! :lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[GLOCKFILE, line 91 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-KQWIQGeNdZsgFIpLV_q:-KQWIQGeNdZsgFIpLV_r:b-v5h8r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f432186a312e6fc43b0ff6cfb0e27efa5a04fba/GLOCKFILE#L91)):*
> ```
> github.com/pborman/uuid c55201b036063326c5b1b89ccfe45a184973d073
> github.com/peterbourgon/g2s 5767a0b2078638d14800683fd0fe425604883f63
> github.com/petermattis/goid 208e1c5be6bf38853827abdc6290b5f6a0c404d5
> ```

Should we make a fork of this in `cockroachdb/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-:-KQWIhW6Dem0e9eCYOfE:be8rotp)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[GLOCKFILE, line 91 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977#-KQWIQGeNdZsgFIpLV_q:-KQWJtfNijO8xJW01DsD:b-jdl0b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f432186a312e6fc43b0ff6cfb0e27efa5a04fba/GLOCKFILE#L91)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Should we make a fork of this in `cockroachdb/`?
</details>
Doesn't seem necessary yet. I think we can trust this `petermattis` fellow to be a well-behaved maintainer of that code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8977)*

**Pull request merged**
