### PR TITLE
acceptance: use native go ssh instead of shelling out

### PR DESCRIPTION
**Pull request by tamird**
This paves the way for running processes from the test orchestrator
rather than relying on supervisor on the remote side.

Reviewers: early feedback? I'm going to try to test this, too.

### CODE REVIEW

**Comment by cuongdo** [comment]
Could you add some info to the commit message describing *why* it's desirable to run processes from the orchestrator?

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/terrafarm/ssh.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0icBu1Lbim22veSFo:-Kq0icBu1Lbim22veSFp:buf5stt) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L52)):*
> ```Go
> 		node := &f.nodes[i]
> 		if node.hostname == host {
> 			if c := node.ssh; c != nil {
> ```

does this have an advantage over `if node.ssh != nil`?

---

*[pkg/acceptance/terrafarm/ssh.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0jgDiVnKsjRpiDKYY:-Kq0jgDiVnKsjRpiDKYZ:brofgt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L73)):*
> ```Go
> 	}
> 	conn, err := (&net.Dialer{
> 		KeepAlive: 5 * time.Second,
> ```

I believe that this is a TCP keepalive rather than an SSH keepalive like the `ServerAliveInterval` config variable that's been removed. Is there a way to reinstate the SSH keepalive? This might make a difference with some cloud providers' firewalls.

---

*[pkg/acceptance/terrafarm/ssh.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0ldi0KltD0UQIaZDh:-Kq0ldi0KltD0UQIaZDi:b-6lz19u) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L82)):*
> ```Go
> 		Auth: []ssh.AuthMethod{
> 			ssh.PublicKeys(signer),
> 		},
> ```

It seems like you'll need to set `HostKeyCallback` to `ssh.InsecureIgnoreHostKey()` to disable checks for host keys, or is that not needed here?

---

*[pkg/acceptance/terrafarm/ssh.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0kxxAFoARv8CmFJmp:-Kq0kxxAFoARv8CmFJmq:b-7bcvh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L105)):*
> ```Go
> 	s.Stdout = &stdout
> 	s.Stderr = &stderr
> ```

nit: extra newline

---

*[pkg/acceptance/terrafarm/ssh.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0mcxfyRcNq8euVd24:-Kq0mcxfyRcNq8euVd25:btey3mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L139)):*
> ```Go
> 	dir, file := filepath.Split(dest)
> 
> 	if err := s.Start("/usr/bin/scp -t " + dir); err != nil {
> ```

what does `-t` do? and where can I find the docs for it? I can't find it in the man page for `scp` on `navy-0001`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-:-Kq0lBhpl-4_OfC5ggN1:b2qlox9)*

**Comment by tamird** [comment]
Sure thing, done.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/acceptance/terrafarm/ssh.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0icBu1Lbim22veSFo:-Kq3WD0nYfVJ6Imt0-cJ:b84ig1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L52)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

does this have an advantage over `if node.ssh != nil`?
</blockquote></details>

probably a bit faster since it avoids an extra pointer dereference of `host` on the `return` call?

---

*[pkg/acceptance/terrafarm/ssh.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0jgDiVnKsjRpiDKYY:-Kq3YWuYwKw9WUf6X7qf:b-y3yzfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L73)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I believe that this is a TCP keepalive rather than an SSH keepalive like the `ServerAliveInterval` config variable that's been removed. Is there a way to reinstate the SSH keepalive? This might make a difference with some cloud providers' firewalls.
</blockquote></details>

Yeah; had to do this somewhat manually, but done.

---

*[pkg/acceptance/terrafarm/ssh.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0ldi0KltD0UQIaZDh:-Kq3YmuSsOvjAzTeGwfr:bnf8948) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L82)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

It seems like you'll need to set `HostKeyCallback` to `ssh.InsecureIgnoreHostKey()` to disable checks for host keys, or is that not needed here?
</blockquote></details>

Hm, i'm not sure. I'm going to test this as-is.

---

*[pkg/acceptance/terrafarm/ssh.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0kxxAFoARv8CmFJmp:-Kq3YyqE4efj53kOYOz_:b-vqb7oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L105)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

nit: extra newline
</blockquote></details>

I found this more readable =/

---

*[pkg/acceptance/terrafarm/ssh.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0mcxfyRcNq8euVd24:-Kq3Z1EqVePYhMYHAmg6:b-yxjbt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L139)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

what does `-t` do? and where can I find the docs for it? I can't find it in the man page for `scp` on `navy-0001`
</blockquote></details>

Removed in the next commit that uses sftp instead of scp (and this implementation wouldn't have worked because this function is used to copy from the remote host to the local filesystem).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-:-Kq3ZTMK8E2pgEDkuhzU:b-ik8b4)*

**Comment by tamird** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/terrafarm/ssh.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-Kq0ldi0KltD0UQIaZDh:-KqOEscfezYxlIAN9EEB:b-j83oek) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a2ba056bbf7f6f7c65dec85aca464e6950c9dc/pkg/acceptance/terrafarm/ssh.go#L82)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Hm, i'm not sure. I'm going to test this as-is.
</blockquote></details>

Yeah, turns out we don't need this - we still want to check the host key; the strict host check we were previously suppressing has to do with locally cached remote keys which we don't have here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247)*

**Comment by cuongdo** [comment]
`ssh` and `newSSH` LGTM.

I'm a little concerned about the much longer implementation for `CollectLogs`. The previous implementation using command-line `scp` was much shorter and seemed to work well. Is your intention to add the streaming to `CollectLogs` in another PR?

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-KqPb3Li3-5yo_bxT4m3:-KqPb3Li3-5yo_bxT4m4:b-ds7gov) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397403102effcaa9ef741a0472f03285faaeb8b/pkg/acceptance/terrafarm/farmer.go#L200)):*
> ```Go
> 			return errors.Wrapf(err, "could not lstat %q on %q", src, host)
> 		}
> 		if lstat.Mode()&os.ModeSymlink != 0 {
> ```

nit: add spaces around `&`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-:-KqPd2PZrNj8b7OQy49R:b-cdufhd)*

**Comment by tamird** [comment]
Yeah, that's unfortunately a consequence of the fact that the `logs` directory is a symlink. Note that the new behaviour is slightly different than the old; symlinks are copied as symlinks - `scp` dereferences every symlink.

Using `scp` while using native SSH everywhere else is more likely to produce surprising behaviour changes, and I did test that this implementation of CollectLogs works correctly in manual tests. WDYT?

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-KqPb3Li3-5yo_bxT4m3:-KqPglEPlrd5KK7o6zVR:b9tos7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1397403102effcaa9ef741a0472f03285faaeb8b/pkg/acceptance/terrafarm/farmer.go#L200)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

nit: add spaces around `&`
</blockquote></details>

`gofmt` makes this decision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-:-KqPgnIHPR7Pf08FWPtM:b-hx0uvu)*

**Comment by cuongdo** [comment]
:lgtm: 

I agree that using native SSH everywhere avoids surprising inconsistencies.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17247#-:-KqStRS63vjUkf35IIYw:bilph0j)*

**Pull request merged**
