### PR TITLE
kvserver: disable merge queue until kvsubscriber has updated

### PR DESCRIPTION
**Pull request by irfansharif**
If we don't have any span configs available, enabling range merges would
be extremely dangerous -- we could collapse everything into a single
range. We've observed this happen when the kvsubscriber's initial scan
overflows its bounded buffer, preventing it from ever getting a
snapshot. A future commit will fix the bounded memory issue, but the
side-effect pointed out the need for this important safe guard.

Informs #77687.

Release justification: bug fix
Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Drive-by which you can feel free to disregard, where does the merge queue interact with the span configs? And is that perhaps a place where the API can be extended to indicate that the spans aren't known yet?

**Comment by irfansharif** [comment]
There are two places. When we receive configs over a keyspan, we enqueue the corresponding ranges into merge+split queues in case the config necessitates a split/allows a merge:

https://github.com/cockroachdb/cockroach/blob/0fb2c0c102a51864ede89df954a8d8ade67e0696/pkg/kv/kvserver/store.go#L2445

When the merge queue processes replicas in its own background thread, it checks if the extending a replicas keyspace a key further would necessitate a split:

https://github.com/cockroachdb/cockroach/blob/b3525c95b176f7520173e7a6d3e4a93dca86b198/pkg/kv/kvserver/merge_queue.go#L146

Right above processing individual replicas we check if the merge queue is enabled. Given that, folding this check in where it is felt reasonable/minimally invasive.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78122#-:-Mygx3vU7ow7hUnLywg2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by andreimatei** [comment]
Would it make sense to block for the kvsubscriber connection in the server's join phase?

**Comment by ajwerner** [comment]
I think it might.

**Review by andreimatei — COMMENTED** [review]
Irfan have you considered doing that instead?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78122#-:-Mz0SD611YI1VCP0DZvw:b-vufucd)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
