### PR TITLE
acceptance: make docker more resilient to timeout in ContainerStart

### PR DESCRIPTION
**Pull request by tbg**
Docker likes to never respond to us, and we do not usually have cancellations
on the context (which would not help, after all, that would just fail the test
right there). Instead, try a few times.

The problem looks similar to

https://github.com/golang/go/issues/16060
https://github.com/golang/go/issues/5103

Another possibility mentioned in usergroups is that some file descriptor limit
is hit. Since I've never seen this locally, perhaps that's the case on our
agent machines. Unfortunately, those are hard to SSH into.

This may not be a good idea (after all, perhaps `Start()` succeeded) and we'd
have to do something similar for `ContainerWait`. But, at least it should
give us an additional data point: do the retries also just block? Is the
container actually started when we retry?

### CODE REVIEW

**Comment by tamird** [comment]
Seems worthwhile to me; thanks for doing this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/acceptance/cluster/docker.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-Ks9eeFlDvwV8vpVaTIN:-Ks9eeFlDvwV8vpVaTIO:b3xyoxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe2cbc6487cd3987700ff106838729319136405/pkg/acceptance/cluster/docker.go#L324)):*
> ```Go
> 
> func (cli resilientDockerClient) ContainerStart(clientCtx context.Context, id string, opts types.ContainerStartOptions) error {
> 	ctx, _ := context.WithTimeout(clientCtx, 20*time.Second)
> ```

help me understand this unusual use of context:
- why do you need to bind `clientCtx` separately from this `ctx`?
- why not bind and defer `cancel` here?
- where you compare `err == context.DeadlineExceeded`, why not `if err == ctx.Err()`; isn't that what you really want?

---

after re-reading the code, I think maybe you just want to `ctx, cancel := context.WithTimeout(clientCtx, ...)` inside the `for` loop, so that each ContainerStart call has a timeout? the way the code is written now, I believe retries will be handed a context which is already expired. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-:-Ks9fk-LmQddnOhKQMba:bs0hea2)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/acceptance/cluster/docker.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-Ks9eeFlDvwV8vpVaTIN:-KsCGqGLpmWLSAnppCyK:b2eqm60) ([raw file](https://github.com/cockroachdb/cockroach/blob/efe2cbc6487cd3987700ff106838729319136405/pkg/acceptance/cluster/docker.go#L324)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

help me understand this unusual use of context:
- why do you need to bind `clientCtx` separately from this `ctx`?
- why not bind and defer `cancel` here?
- where you compare `err == context.DeadlineExceeded`, why not `if err == ctx.Err()`; isn't that what you really want?

---

after re-reading the code, I think maybe you just want to `ctx, cancel := context.WithTimeout(clientCtx, ...)` inside the `for` loop, so that each ContainerStart call has a timeout? the way the code is written now, I believe retries will be handed a context which is already expired. What do you think?
</blockquote></details>

As you've pointed out this code was total :poop:, rewritten!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/docker.go, line 332 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-KsDVhPeyvFWEN0D2Pek:-KsDVhPeyvFWEN0D2Pel:b-eu6nkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ffe1b44988f52dc3b953be71e8264e13e3433ab/pkg/acceptance/cluster/docker.go#L332)):*
> ```Go
> 
> 			return cli.APIClient.ContainerStart(ctx, id, opts)
> ```

remove this empty line?

---

*[pkg/acceptance/cluster/docker.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-KsDVn9MNIokm0jZYUbB:-KsDVn9MNIokm0jZYUbC:b-4oty7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ffe1b44988f52dc3b953be71e8264e13e3433ab/pkg/acceptance/cluster/docker.go#L335)):*
> ```Go
> 		}()
> 
> 		if err == nil {
> ```

i think you can remove this clause:
```
		// Keep going if client's context is up for it.
		if err == context.DeadlineExceeded && clientCtx.Err() == nil {
			log.Warningf(clientCtx, "ContainerStart timed out, retrying")
			continue
		}
		return err
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-:-KsDW-gVe9zx02ruitqo:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/cluster/docker.go, line 332 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-KsDVhPeyvFWEN0D2Pek:-KsFAuPe5r1Nnf_If8X4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ffe1b44988f52dc3b953be71e8264e13e3433ab/pkg/acceptance/cluster/docker.go#L332)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this empty line?
</blockquote></details>

Done.

---

*[pkg/acceptance/cluster/docker.go, line 335 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-KsDVn9MNIokm0jZYUbB:-KsFB2uVGchX1AbDgq22:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ffe1b44988f52dc3b953be71e8264e13e3433ab/pkg/acceptance/cluster/docker.go#L335)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i think you can remove this clause:
```
		// Keep going if client's context is up for it.
		if err == context.DeadlineExceeded && clientCtx.Err() == nil {
			log.Warningf(clientCtx, "ContainerStart timed out, retrying")
			continue
		}
		return err
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800#-:-KsFB6kHs-2uyxTFf4C0:b-814g8k)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17800)*

**Pull request merged**
