### PR TITLE
[WIP] sql: partition REGIONAL BY ROW on all indexes during region changes

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

Refs: #63462

### CODE REVIEW

**Comment by otan** [comment]
thought about this more and now i think this is the wrong way to go about it. we should instead repartition after index creation/drop (even during failures). doing this on AllIndexes has a chance of e.g. for RBR->GLOBAL making partitions on the new indexes of the global table.

**Review by ajstorm — COMMENTED** [review]
Added a few comments.  Would like @arulajmani to have a look too though, as I'm still pretty new to these concurrent tests in go.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-:-MYoqD8t3pbN2MHCPMMG:b19elwe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-MYoltCpETdWp5-QVE8D:-MYoltCpETdWp5-QVE8E:b6dqlni) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa2e64becfdb7680d1568dbeb0682110fbe9c62/pkg/ccl/multiregionccl/region_test.go#L355)):*
> ```Go
> }
> 
> // TestDropIndexFailureDuringAddOrDropRegion a DROP INDEX failing during
> ```

Nit: TestDropIndexFailureDuringAddOrDropRegion _tests_ a DROP INDEX...
___
*[pkg/ccl/multiregionccl/region_test.go, line 357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-MYom41N4mq3MuTQkSJE:-MYom41N4mq3MuTQkSJF:b-mbqcex) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa2e64becfdb7680d1568dbeb0682110fbe9c62/pkg/ccl/multiregionccl/region_test.go#L357)):*
> ```Go
> // TestDropIndexFailureDuringAddOrDropRegion a DROP INDEX failing during
> // ADD/DROP REGION, in which case the dropped index should still contain
> // the new indexes.
> ```

Nit: ...should still contain the proper set of regions?
___
*[pkg/ccl/multiregionccl/region_test.go, line 383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-MYop6oB6K-G5qt0tod7:-MYop6oB6K-G5qt0tod8:bkudv0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa2e64becfdb7680d1568dbeb0682110fbe9c62/pkg/ccl/multiregionccl/region_test.go#L383)):*
> ```Go
> 				SQLSchemaChanger: &sql.SchemaChangerTestingKnobs{
> 					RunBeforeBackfill: func() error {
> 						if block {
> ```

Do we need a mutex above this to ensure that we don't get both racers in this block (in which case the test would hang)?
___
*[pkg/ccl/multiregionccl/region_test.go, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-MYon8y88i4Swa0oWWJv:-MYon8y88i4Swa0oWWJw:bndn67l) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa2e64becfdb7680d1568dbeb0682110fbe9c62/pkg/ccl/multiregionccl/region_test.go#L405)):*
> ```Go
> 			require.NoError(t, err)
> 
> 			block = true
> ```

I'm confused as to why we need to set this to `true` down here.  Can't we just initialize it to true above?  Is there any chance that the DROP/CREATE/CREATE sequence above will invoke the schema changer?
___
*[pkg/ccl/multiregionccl/region_test.go, line 421 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63968#-MYopQmf77lUES5WgowL:-MYoop9_EMThoNU_jikK:b7un08j) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa2e64becfdb7680d1568dbeb0682110fbe9c62/pkg/ccl/multiregionccl/region_test.go#L421)):*
> ```Go
> 			wg.Add(1)
> 
> 			_, err = sqlDB.Exec(tc.regionChangeSQL)
> ```

Forgive me if this comment is noise, as I'm still pretty new to writing these types of concurrent go tests, but shouldn't we wait for the above go routine to make it to the type schema changer before we run this?  As written, isn't it possible that the ADD/DROP region statement could make it into the error path before the DROP INDEX statement does?

**Comment by ajstorm** [comment]
Gah!  And now I notice the WIP and closed 🤦

**Comment by otan** [comment]
haha sorry, not sure whether this should go through...

**Pull request closed without merging**
