### PR TITLE
changefeedccl: set groundwork for nemeses replay

### PR DESCRIPTION
**Pull request by stevendanna**
This contains #53771 but with the enumCreate event mix set to 0, effectively
disabling it until we can fix the issue it uncovered.

Further, it sets the groundwork for making ChangefeedNemeses something we
can record and play back by moving various random choices into the event payload.

Subsequent PRs will add the ability to record events and their payload such that they
can be replayed.

See the individual commits for more details.

### CODE REVIEW

**Review by HonoreDB — COMMENTED** [review]
Replay! Great idea!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65325#-:-M_vGZMr8Fm8KPtzU7FC:bnwf32k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 600 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65325#-M_vHisUCNuE46qPGmeO:-M_vHisUCNuE46qPGmeP:bw2d798) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c95d6cd3521eb40abc065e864e38ec1c94ae956/pkg/ccl/changefeedccl/cdctest/nemeses.go#L600)):*
> ```Go
> 		return err
> 	}
> 	ns.enumCount++
> ```

Should this be `--`?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 600 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65325#-M_vHisUCNuE46qPGmeO:-M_yU97f-aOzk_dMCMOv:byqmyaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c95d6cd3521eb40abc065e864e38ec1c94ae956/pkg/ccl/changefeedccl/cdctest/nemeses.go#L600)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Should this be `--`?
</blockquote></details>

I don't think so.  This counts how many enum's have been created, then in nextEvent() we only generate an eventAddColumn with type enum if we have at least one enum.

**Comment by stevendanna** [comment]
@HonoreDB Mind giving this a second look?

**Review by HonoreDB — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by stevendanna** [comment]
bors r=HonoreDB

Thanks!

**Pull request merged**
