### PR TITLE
opt: Refactor Metadata classes

### PR DESCRIPTION
**Pull request by andy-kimball**
Export TableMeta and ColumnMeta structs. Fields in these structs
replace accessor methods on the Metadata type. For example, a
ColumnMeta.Type field replaces a Metadata.ColumnType() method.

The motivation for this change was that the accessor methods are
somewhat clunky, and we need to add even more of them. Better to
create separate abstractions for the table and column metadata.

Also, improve formatting when aliases are present, which is useful
when debugging self-joins and mutations.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: except one comment in the privilege code

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-:-LTtrq7dCICKohvl4t7O:b-3guoj1)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtom9n02OZQootl60Z:-LTtom9n02OZQootl60_:b-jg8ds1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1465613f830e3c2bfc2e49ebb20f1c972b2fd0/pkg/sql/opt/metadata.go#L65)):*
> ```Go
> 	// most once. The map value is the union of all required privileges, where
> 	// each bit is 1 << privilege.Kind so that multiple privileges can be stored.
> 	deps map[DataSource]uint64
> ```

[nit] I would make a `type PrivilegeBitmap uint32` so it's evident what the value is. Btw `privilege.Kind` has a `Mask()` function  and `privilege.List` has a `ToBitField()` function, not sure if they are any use here though.
___
*[pkg/sql/opt/metadata.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtqbF4Ev7M25LZUAZO:-LTtqbF4Ev7M25LZUAZP:b-cpqcmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1465613f830e3c2bfc2e49ebb20f1c972b2fd0/pkg/sql/opt/metadata.go#L133)):*
> ```Go
> 			// Strip off each privilege bit and make call to CheckPrivilege for it.
> 			priv := privilege.Kind(bits.TrailingZeros64(privs))
> 			if priv == 0 {
> ```

I don't get this condition, this is the case if the lowest bit is set..
___
*[pkg/sql/opt/optbuilder/select.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtre4tESAhhWXrtEHt:-LTtre4tESAhhWXrtEHu:b-ifsnwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f61116858ea1119ce8ad9e3a029f7643a9c4166/pkg/sql/opt/optbuilder/select.go#L213)):*
> ```Go
> 		// If input expression is a ScanExpr, then override metadata aliases for
> 		// pretty-printing.
> 		scan, ok := scope.expr.(*memo.ScanExpr)
> ```

[nit] `if scan, ok := ..; ok { .. }`

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33180)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/metadata.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtom9n02OZQootl60Z:-LTwoFd72Mt6mkuOxlCY:bj8uycu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1465613f830e3c2bfc2e49ebb20f1c972b2fd0/pkg/sql/opt/metadata.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I would make a `type PrivilegeBitmap uint32` so it's evident what the value is. Btw `privilege.Kind` has a `Mask()` function  and `privilege.List` has a `ToBitField()` function, not sure if they are any use here though.
</blockquote></details>

Done, except that I didn't export this, since it's just an internal implementation detail.
___
*[pkg/sql/opt/metadata.go, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtqbF4Ev7M25LZUAZO:-LTwoSEa9-USGCfmZML2:b6e0dc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1465613f830e3c2bfc2e49ebb20f1c972b2fd0/pkg/sql/opt/metadata.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't get this condition, this is the case if the lowest bit is set..
</blockquote></details>

When the lowest bit is set, that's `PrivilegeKind._ = 0`, which I don't want to check. Some data sources don't need any privileges checked (e.g. table that's referenced within a view). I changed the code a bit and added a comment. Also, I found a different bug where I shouldn't be shifting below, but instead masking the just-handled bit. It turns out that this code rarely gets executed in the failed privilege case, because any time a catalog object's privileges are changed, it bumps the version, and the stale check fails above rather than here.
___
*[pkg/sql/opt/optbuilder/select.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTtre4tESAhhWXrtEHt:-LTx7jKG-YFCuPlBVUqR:b-cdo9ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f61116858ea1119ce8ad9e3a029f7643a9c4166/pkg/sql/opt/optbuilder/select.go#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `if scan, ok := ..; ok { .. }`
</blockquote></details>

The `ok` was used below. I changed it to `isScan` for clarity.

**Review by justinj — COMMENTED** [review]
I just gave a skim but :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-:-LTyaUjb3lKehfAFOLNt:by2plld)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/testdata/rules/join, line 1537 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/33180#-LTyau8qE0D4qUUH3RzW:-LTyau8r8ELYparrGHD7:blro4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6091b4967be84b6cfc929821d8684f9c8299e4/pkg/sql/opt/norm/testdata/rules/join#L1537)):*
> ```
>  │    └── filters (true)
>  └── filters
>       └── a.f = a.f [type=bool, outer=(3,8), constraints=(/3: (/NULL - ]; /8: (/NULL - ]), fd=(3)==(8), (8)==(3)]
> ```

Huh, I guess this is right, but I'm a little surprised that col 8 is used for this instead of col 13.

**Pull request merged**
