### PR TITLE
kvserver,rac2: do force-flushing when told to

### PR DESCRIPTION
**Pull request by sumeerbhola**
The MsgAppSender interface is used to send the MsgApps.

Informs https://github.com/cockroachdb/cockroach/issues/130433

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit is from https://github.com/cockroachdb/cockroach/pull/131715. @kvoli This lacks tests too, but hopefully unblocks you wrt the pacing based on watching tokens. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-:-O8CPHeq8LmGb84GfMk5:b-l9ykoi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131747#gh-1785032325:-O8DWKEI2KUDNKI7j0pr:bci4twy) ([raw file](https://github.com/cockroachdb/cockroach/blob/67427655c71bfa870b4099c90405d7b98df5d0d8/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2049)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Why are `MsgApp`s constructed with only 1 entry in them?
</blockquote></details>

note the n-1 in:
[event.sendingEntries[0].index, event.sendingEntries[n-1].index+1)

And we don't have any test coverage for this, so there could be bugs.

**Review by kvoli — COMMENTED** [review]
Approach :lgtm:  -- will re-review once the tests are ready.

> Reviewed 5 of 6 files at r4, 7 of 7 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-:-O8DXcPw9fEwHimX7iSc:bk07ouh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/force_flush_choice` line 552 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8DX6oWEM3P4SXCE4Lk:-O8DX6oWEM3P4SXCE4Ll:b2mv3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7f347c261e36614ec40de872fdd8455b8f51e81/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/force_flush_choice#L552)):*
> ```
> ++++
> schedule-controller-event-count: 1
> scheduled-replicas: 4 5
> ```

Should we de-schedule the replicas as well? Not necessary but thought it'd be worth mentioning.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131747#gh-1785032325:-O8D_ymG0LK0ecMjzdMc:b2ezm2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/67427655c71bfa870b4099c90405d7b98df5d0d8/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2049)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

note the n-1 in:
[event.sendingEntries[0].index, event.sendingEntries[n-1].index+1)

And we don't have any test coverage for this, so there could be bugs.
</blockquote></details>

Ah, right. I can't read apparently :)
Thanks.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

Rebased on master. Tests are ready.

> Reviewed 2 of 6 files at r4, 7 of 12 files at r7, 1 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-:-O8EDzAQ-pkgoysPZ8Mr:b-ynizyw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131747#gh-1785032325:-O8EEIA-CK4_ZNjxUkQJ:b-8srrgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/67427655c71bfa870b4099c90405d7b98df5d0d8/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2049)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Ah, right. I can't read apparently :)
Thanks.
</blockquote></details>

We now have test coverage.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/force_flush_choice` line 552 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8DX6oWEM3P4SXCE4Lk:-O8Dnd2x4WO98ftdtvoK:b-vc5mgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7f347c261e36614ec40de872fdd8455b8f51e81/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/force_flush_choice#L552)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should we de-schedule the replicas as well? Not necessary but thought it'd be worth mentioning.
</blockquote></details>

I think it is unnecessary.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1884 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8EFvfZ1Vz8BpcGxMH-:-O8EFvfZ1Vz8BpcGxMH0:b-pfo4hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d821e5d62977fd92f6f24077f16c0deeb87e557a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1884)):*
> ```Go
> 		int64(MaxBytesToSend))
> 	if err != nil {
> 		// Transitioned to StateSnapshot, or some other error that Raft needs to
> ```

There will be no transition to `StateSnapshot` in these calls, they don't mutate the `RawNode` state.

Also, do we need to split `LogSnapshot().LogSlice()` vs `RawNode.SendMsgApp(logSlice)`? There is no "combined" call that does both things, because we need to get `LogSnapshot()` under `Replica.mu`, and then fetch the slice after releasing it.

`LogSlice()` can return an error like `ErrCompacted`, meaning that the first index is already gone.
`SendMsgApp` can return an error if the slice became stale (e.g. the term changed while we were fetching the slice from the snapshot).

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 1884 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8EFvfZ1Vz8BpcGxMH-:-O8EILfI0BXTkbAcBoQY:bkxn6t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d821e5d62977fd92f6f24077f16c0deeb87e557a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L1884)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

There will be no transition to `StateSnapshot` in these calls, they don't mutate the `RawNode` state.

Also, do we need to split `LogSnapshot().LogSlice()` vs `RawNode.SendMsgApp(logSlice)`? There is no "combined" call that does both things, because we need to get `LogSnapshot()` under `Replica.mu`, and then fetch the slice after releasing it.

`LogSlice()` can return an error like `ErrCompacted`, meaning that the first index is already gone.
`SendMsgApp` can return an error if the slice became stale (e.g. the term changed while we were fetching the slice from the snapshot).
</blockquote></details>

`SendMsgApp` will mutate the `RawNode`, but only if the message send is successful. It will register the intent to send this message, and update `Next`.

**Comment by sumeerbhola** [comment]
Yes, we will split this in a later PR, as noted in the comment in `RaftInterface` (which may be slightly stale).
```
	// TODO(sumeer): This is a temporary API. LogSnapshot and LogSlice will
	// replace it, and we will do this in two steps: (a) create a LogSlice while
	// holding raftMu, which will not use RaftInterface, (b) call the following
	// method with the LogSlice, and the callee will make the MsgApp and behave
	// as if it was sent (i.e., update Next). Since we are not holding
	// Replica.mu, the callee will need to acquire Replica.mu.
```

> LogSlice() can return an error like ErrCompacted, meaning that the first index is already gone.

We will close the `replicaSendStream` on any error, under the assumption that if it is `ErrCompacted`, RawNode will notice soon enough and transition to `StateSnapshot`.

> SendMsgApp can return an error if the slice became stale (e.g. the term changed while we were fetching the slice from the snapshot).

Again, we will close the `replicaSendStream`.

Does this sound reasonable?

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 4 of 12 files at r7, 5 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-:-O8ER-cUBCkIoWh1gPCN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 2120 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8EQpRN5CAHYTX5Jcpi:-O8EQpRN5CAHYTX5Jcpj:b-810ihx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d821e5d62977fd92f6f24077f16c0deeb87e557a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L2120)):*
> ```Go
> 	for _, entry := range msg.Entries {
> 		entryState := getEntryFCStateOrFatal(ctx, entry)
> 		if entryState.index != rss.mu.sendQueue.indexToSend {
> ```

nit: up to you, we could assert on `nextRaftIndex` for the tail as well.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/no_send_q_choice` line 68 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/131747#-O8EP_4dCItKl2b-kD_P:-O8EP_4dCItKl2b-kD_Q:b-ra0xjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d821e5d62977fd92f6f24077f16c0deeb87e557a/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/no_send_q_choice#L68)):*
> ```
>   term=1 index=1  tokens=1048576
> ++++
> MsgApps sent in pull mode:
> ```

:partying_face:

**Comment by sumeerbhola** [comment]
> nit: up to you, we could assert on nextRaftIndex for the tail as well.

Done. And fixed the empty panic string.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
