### PR TITLE
kvserver: add no-op safeguard to `TransferLeaseTarget`

### PR DESCRIPTION
**Pull request by aayushshah15**
kvserver: add no-op safeguard to `TransferLeaseTarget`

Release justification: adds no-op safeguard

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 1257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-Mj5c_3O7fQTVoCbvM6w:-Mj5c_3O7fQTVoCbvM6x:bhsibx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a102381d7617ce5caf309c0edc18ba3b03f472d/pkg/kv/kvserver/allocator.go#L1257)):*
> ```Go
> // TransferLeaseTarget returns a suitable replica to transfer the range lease
> // to from the provided list. It excludes the current lease holder replica
> // unless asked to do otherwise by the checkTransferLeaseSource parameter.
> ```

would you mind taking the opportunity to put a comment on`checkTransferLeaseSource`? I can't really tell what the deal with it is.
___
*[pkg/kv/kvserver/allocator.go, line 1454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-Mj5ckOjBQWM6YFbyW8m:-Mj5ckOjBQWM6YFbyW8n:bdaxp96) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a102381d7617ce5caf309c0edc18ba3b03f472d/pkg/kv/kvserver/allocator.go#L1454)):*
> ```Go
> 		currentDelta := getQPSDelta(storeQPSMap, existing)
> 		// NB: If the `bestOption` ends up being the current leaseholder, then the
> 		// check below will fail since we know that `leaseholderReplQPS` must be
> ```

you say the check will fail, but won't it pass?

TBH, I can't really tell what this change is doing (btw, the commit msg says it's comments only, but it's not). So tell me the dealeo, or otherwise perhaps clarify this comment more?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 1257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-Mj5c_3O7fQTVoCbvM6w:-Mj6BENA12sUkr4qSryM:b3wru5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a102381d7617ce5caf309c0edc18ba3b03f472d/pkg/kv/kvserver/allocator.go#L1257)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would you mind taking the opportunity to put a comment on`checkTransferLeaseSource`? I can't really tell what the deal with it is.
</blockquote></details>

done, let me know if its lacking. 
___
*[pkg/kv/kvserver/allocator.go, line 1454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-Mj5ckOjBQWM6YFbyW8m:-Mj6CB847ScCa1qIJ6qO:b-lcg0s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a102381d7617ce5caf309c0edc18ba3b03f472d/pkg/kv/kvserver/allocator.go#L1454)):*
The comment was perhaps in the wrong place. See now. 

> TBH, I can't really tell what this change is doing (btw, the commit msg says it's comments only, but it's not). So tell me the dealeo, or otherwise perhaps clarify this comment more?

See https://github.com/cockroachdb/cockroach/blob/d61f474635f814bc420a61a11e6660b8882e05f0/pkg/kv/kvserver/store_rebalancer.go#L412-L422

**Review by nvb — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-MjAljph3zqGvOPygAHj:-MjAljph3zqGvOPygAHk:bjhj6u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b80e3684b5d4ba518f95ff875b546682da0cb5/pkg/kv/kvserver/allocator.go#L1454)):*
> ```Go
> 		currentDelta := getQPSDelta(storeQPSMap, existing)
> 		bestOption := getCandidateWithMinQPS(storeQPSMap, existing)
> 		if bestOption != (roachpb.ReplicaDescriptor{}) && leaseholderReplQPS > 0 &&
> ```

This looks good, although I'm left wondering why it was preferable to write like this, as opposed to the more direct 
```go
if bestOption != (roachpb.ReplicaDescriptor{}) && bestOption.StoreID != leaseRepl.StoreID()
```

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69931)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-MjAljph3zqGvOPygAHj:-MjB6g9GBm0yr4Ojz-uv:b1qp1p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b80e3684b5d4ba518f95ff875b546682da0cb5/pkg/kv/kvserver/allocator.go#L1454)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This looks good, although I'm left wondering why it was preferable to write like this, as opposed to the more direct 
```go
if bestOption != (roachpb.ReplicaDescriptor{}) && bestOption.StoreID != leaseRepl.StoreID()
```
</blockquote></details>

Yeah you're right, evidently Andrei found this weird as well. Changed.

**Comment by aayushshah15** [comment]
TFTRs

bors r+

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69931#-:-MjBUgzU5ooRIcQw_AAc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

**Pull request merged**
