### PR TITLE
docs/codelabs: update SQL statement codelab

### PR DESCRIPTION
**Pull request by andyyang890**
This patch updates the codelab for adding a new SQL statement to use `./dev`
instead of `make`. It also fixes some of the code snippets in the
instructions so that they will compile with the current state of the repo.

Release note: None

### CODE REVIEW

**Review by ZhouXing19 — APPROVED** [review]
:lgtm_strong: ! Very nice job, thanks for fixing the doc. This will be very helpful!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88203#-:-NCNiM7l7GiGf9D0cUHX:b8wcuz2)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andyyang890** [comment]
TFTR!

bors r=ZhouXing19

**Comment by andyyang890** [comment]
bors r-

need to fix line breaks in PR desc

**Comment by andyyang890** [comment]
bors r=ZhouXing19

**Pull request merged**
