### PR TITLE
colserde: fix null handling in arrowbatchconverter

### PR DESCRIPTION
**Pull request by yuzefovich**
**colserde: fix null handling in arrowbatchconverter**

This commit fixes the null handling in the ArrowBatchConverter.
Previously, we would always marshal/unmarshal values without paying
attention to the nulls bitmaps. Those operations could result in errors
which would stop the execution whereas it shouldn't. Now we are paying
attention to the nulls bitmaps and we enhance the testing harness to
insert garbage values when setting random nulls.

In theory, this bug could occur in production, but it seems unlikely in
practice.

Release note: None

**colexec: override testing mem limit in external operators**

This commit overrides the testing memory limit of 1 byte in the external
operators to the default value of 64MiB. Such behavior is acceptable
because this limit will matter only once the operators spill to disk
(which is the goal of setting such low limit in the first place). This
allows for faster test runs and more realistic benchmarks.

Release note: None

**execinfra: check ForceDiskSpill in GetWorkMemLimit**

This commit cleans up the logic around `ForceDiskSpill` and
`MemoryLimitBytes` testing knobs. Now we require that only one of the
two knobs is used, and we also check the former knob in
`GetWorkMemLimit` utility function since we have already been doing it
in all callsites.

Additionally, several callsites that have `MemoryLimitBytes = 1` are
replaced with more explicit `ForceDiskSpill = true`.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks [here](https://gist.github.com/yuzefovich/ec399d7778edd12077d493af9c16a0e1) show expected improvement in the performance when nulls are present.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfJtC59Z_JZTX6J9VN:-MTfJtC59Z_JZTX6J9VO:b69mtsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6e4663d8f8c273856030c6dc1b62959dcc109a/pkg/col/colserde/arrowbatchconverter.go#L111)):*
> ```Go
> 			for i := range decimals {
> 				if nulls != nil && nulls.NullAt(i) {
> 					c.builders.binaryBuilder.AppendNull()
> ```

Why append any nulls if we're going to overwrite the null bitmap? Should we append a zero value instead to avoid having to reallocate an unnecessary bitmap? Also this `if else` pattern is a bit ugly, maybe just use `if { ... continue }`
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfLU73Av1OcWGgj9ZD:-MTfLU73Av1OcWGgj9ZE:b-mt69dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5971ecb9dd1a25c81cd6012d6be1ff922802eae5/pkg/sql/colexec/external_hash_joiner_test.go#L134)):*
> ```Go
> 			TestingKnobs: execinfra.TestingKnobs{
> 				ForceDiskSpill:   true,
> 				MemoryLimitBytes: 1,
> ```

At some point, it'd be nice to get rid of this in favor of `ForceDiskSpill`. Do you know what currently stands in the way of this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfJtC59Z_JZTX6J9VN:-MTh4D3x1e0_Ntn0NNIS:b-7iyaw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6e4663d8f8c273856030c6dc1b62959dcc109a/pkg/col/colserde/arrowbatchconverter.go#L111)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why append any nulls if we're going to overwrite the null bitmap? Should we append a zero value instead to avoid having to reallocate an unnecessary bitmap? Also this `if else` pattern is a bit ugly, maybe just use `if { ... continue }`
</blockquote></details>

I looked into this, and `arrow` library itself still maintains the null bitmap even when we only use `Append` (essentially it will perform `AppendValue` to the data and `AppendNonNull` to the null bitmap), so we won't save anything if we don't call `AppendNull`, but this way I think the code is easier to read and makes more sense.

As it turns out, this way we also don't need to overwrite the null bitmap in many cases, so I refactored that part a bit too.

I did refactor the indentation.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfLU73Av1OcWGgj9ZD:-MTh4ehS9xRPd4auJ5VY:b-kl6tab) ([raw file](https://github.com/cockroachdb/cockroach/blob/5971ecb9dd1a25c81cd6012d6be1ff922802eae5/pkg/sql/colexec/external_hash_joiner_test.go#L134)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

At some point, it'd be nice to get rid of this in favor of `ForceDiskSpill`. Do you know what currently stands in the way of this?
</blockquote></details>

Do you mean getting rid off `MemoryLimitBytes` entirely? I think there are valid scenarios when we want to have a custom memory limit without forcing the disk spilling (at least not right away).

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r4, 2 of 2 files at r5, 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgo8l9Fb0-jRPMX2W:-MTjgo8l9Fb0-jRPMX2X:b-109gax) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L89)):*
> ```Go
> 	}
> 	n := batch.Length()
> NEXTVEC:
> ```

Is this placed correctly? Shouldn't it be inside the for loop?
___
*[pkg/col/colserde/arrowbatchconverter.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgd5y-TmUijGHGrgO:-MTjgd5y-TmUijGHGrgP:b7gtg3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L182)):*
> ```Go
> 			}
> 			c.scratch.arrowData[vecIdx] = c.builders.binaryBuilder.NewBinaryArray().Data()
> 			continue NEXTVEC
> ```

Maybe it's time to put this switch into another function which will probably make it easier to read. This way we can also get rid of the label. I try to avoid labels like the plague (or covid) unless necessary because it easily leads to spaghetti code.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfLU73Av1OcWGgj9ZD:-MTjhV_j7NKjG9gA8zNy:b-fevw22) ([raw file](https://github.com/cockroachdb/cockroach/blob/5971ecb9dd1a25c81cd6012d6be1ff922802eae5/pkg/sql/colexec/external_hash_joiner_test.go#L134)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do you mean getting rid off `MemoryLimitBytes` entirely? I think there are valid scenarios when we want to have a custom memory limit without forcing the disk spilling (at least not right away).
</blockquote></details>

Yep. Ack.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgo8l9Fb0-jRPMX2W:-MTkbfXF-0R8tum_yoOx:butrxz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L89)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this placed correctly? Shouldn't it be inside the for loop?
</blockquote></details>

Yes, I think it was placed correctly - we mark a for loop with a label by putting the label right before the for loop.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgd5y-TmUijGHGrgO:-MTkbr_40J0uKdMjUqg1:bxktt3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L182)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe it's time to put this switch into another function which will probably make it easier to read. This way we can also get rid of the label. I try to avoid labels like the plague (or covid) unless necessary because it easily leads to spaghetti code.
</blockquote></details>

Refactored to remove the label.

Personally, I'm not against labels at all costs, but I agree that they should be used with care. In this case I think a label was acceptable because within `select` block we simply wanted to go to the next iteration of the outer loop, the label is defined very close to where it is used and the general thinking why we're jumping to the label is pretty clear too.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTfLU73Av1OcWGgj9ZD:-MTkcmZ_7D_h7Rmf9_aR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5971ecb9dd1a25c81cd6012d6be1ff922802eae5/pkg/sql/colexec/external_hash_joiner_test.go#L134)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yep. Ack.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 16 of 16 files at r7, 2 of 2 files at r8, 13 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-:-MToiwed-4EFM8xl6omq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgo8l9Fb0-jRPMX2W:-MToiK1X1TjmQKj-CGuR:b-c4ejtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L89)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes, I think it was placed correctly - we mark a for loop with a label by putting the label right before the for loop.
</blockquote></details>

Oh right, so a label before the for loop resumes the for loop? For some reason I thought it would re-execute the whole loop again.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgd5y-TmUijGHGrgO:-MToiewlAsCmWoMfhGq-:bcx13zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L182)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Refactored to remove the label.

Personally, I'm not against labels at all costs, but I agree that they should be used with care. In this case I think a label was acceptable because within `select` block we simply wanted to go to the next iteration of the outer loop, the label is defined very close to where it is used and the general thinking why we're jumping to the label is pretty clear too.
</blockquote></details>

Could you still put the handling of these special types into a function I do think it would make `BatchToArrow` easier to read.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-:-MTqAuUQ0PnMAPxmaqSl:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/colserde/arrowbatchconverter.go, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgo8l9Fb0-jRPMX2W:-MTpyOiN-al7vy49PBKt:b-2ebs3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L89)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oh right, so a label before the for loop resumes the for loop? For some reason I thought it would re-execute the whole loop again.
</blockquote></details>

Yeah, the label before the for loop allows you to jump to the next iteration of the loop with `continue LABEL` or exit the loop with `break LABEL`.
___
*[pkg/col/colserde/arrowbatchconverter.go, line 182 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60574#-MTjgd5y-TmUijGHGrgO:-MTqApRW-xEfyu7s4kAm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c45e30f7d8fb1a53edb52c230aa94e44fc63d11/pkg/col/colserde/arrowbatchconverter.go#L182)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you still put the handling of these special types into a function I do think it would make `BatchToArrow` easier to read.
</blockquote></details>

Done.

**Pull request merged**
