### PR TITLE
colexec: fix spillingQueue and flow temporary storage bugs

### LINKED ISSUE #46256: roachtest: tpchvec/disk failed
[(roachtest).tpchvec/disk failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1814553&tab=buildLog) on [master@b5f030223fbcf22e806c48a3c46e74a73a54f50f](https://github.com/cockroachdb/cockroach/commits/b5f030223fbcf22e806c48a3c46e74a73a54f50f):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200318-1814553/tpchvec/disk/run_1
	tpchvec.go:579,tpchvec.go:669,test_runner.go:753: error with attached stack trace:
		    main.execCmdWithBuffer
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:426
		    main.(*cluster).RunWithBuffer
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2031
		    main.registerTPCHVec.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:574
		    main.registerTPCHVec.func3
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:669
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:753
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - error with embedded safe details: %s
		    -- arg 1: <string>
		  - /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1814553-1584515366-86-n3cpu4:1 -- ./workload run tpch --concurrency=1 --db=tpch --max-ops=1 --queries=3 --vectorize=on {pgurl:1-3}:
		  - exit status 1

	cluster.go:1410,context.go:135,cluster.go:1399,test_runner.go:825: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1814553-1584515366-86-n3cpu4 --oneshot --ignore-empty-nodes: exit status 1 2: 5968
		1: dead
		3: 5848
		Error:  1: dead

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/disk](https://teamcity.cockroachdb.com/viewLog.html?buildId=1814553&tab=artifacts#/tpchvec/disk)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fdisk.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
Release justification: bug fixes to new functionality.

These commits (look at separate commits for details) fix a nil pointer panic in the spillingQueue when encountering an error when creating a disk queue as well as the underlying error (caused by a bug in flow temporary directory creation).

Fixes #46256

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-:-M3CC-8d4P93m_honRPn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3CAkT-4gaBKXrM4ntO:-M3CAkT-4gaBKXrM4ntP:b-iw5t9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b741c64256834541cd41dd31feb1e2bfcc3309/pkg/sql/colflow/vectorized_flow.go#L109)):*
> ```Go
> 		// path is the path to this flow's temporary storage directory.
> 		path string
> 		// created is a protected boolean that is true when the flow's temporary
> ```

nit: `s/created/createdStateMu/g`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3CBk0zD5iXr728HE7u:-M3CBk0zD5iXr728HE7v:bmdk9b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b741c64256834541cd41dd31feb1e2bfcc3309/pkg/sql/colflow/vectorized_flow.go#L169)):*
> ```Go
> 		Path: f.tempStorage.path,
> 		OnNewDiskQueueCb: func() {
> 			f.tempStorage.createdStateMu.Lock()
> ```

Do we want to add a unit test for such concurrent accesses? I'm not sure whether it'll give us much benefit, but it would be nice to have if it is easy.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46484)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3CBk0zD5iXr728HE7u:-M3CgkRFA2RBthcuu27H:b-dhslem) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b741c64256834541cd41dd31feb1e2bfcc3309/pkg/sql/colflow/vectorized_flow.go#L169)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we want to add a unit test for such concurrent accesses? I'm not sure whether it'll give us much benefit, but it would be nice to have if it is easy.
</blockquote></details>

I added a test, but the in-memory engine seems to create parent directories if they don't exist so it's not much use. Can add it in if you want.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46484)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3CBk0zD5iXr728HE7u:-M3CkxSS07nECtfYxblp:bo0opky) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b741c64256834541cd41dd31feb1e2bfcc3309/pkg/sql/colflow/vectorized_flow.go#L169)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I added a test, but the in-memory engine seems to create parent directories if they don't exist so it's not much use. Can add it in if you want.
</blockquote></details>

Why not use the on-disk engine then? We do use it in the benchmarks.

I don't have a strong opinion here, so I'll leave it up to you to decide whether the test is needed.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46484)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/spilling_queue.go, line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3DdRJ8DsMv6F3LJoyO:-M3DdRJ8DsMv6F3LJoyP:b-rcg1gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/64dc3aa531c86b93a94aa1cdfa21130c750acb46/pkg/sql/colexec/spilling_queue.go#L267)):*
> ```Go
> 
> func (q *spillingQueue) close(ctx context.Context) error {
> 	if q.closed {
> ```

By the way, the problem with this method can be trigger on master when running `BenchmarkHashRouter`:
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkHashRouter/numOutputs=2/numInputBatches=2-16         	panic: testing semaphore too many resources released, releasing 2, have 0

goroutine 72 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror.VectorizedInternalPanic(...)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:190
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*TestingSemaphore).Release(0xc0000fa160, 0x2, 0xc0005c6000)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/testutils.go:200 +0x114
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc0006962d0, 0x69ffa80, 0xc0000fa008, 0x0, 0x0)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:261 +0xb6
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).reset(0xc0006962d0, 0x69ffa80, 0xc0000fa008)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:283 +0x43
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).reset(0xc000604090, 0x69ffa80, 0xc0000fa008)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:346 +0x67
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).reset(0xc000604120, 0x69ffa80, 0xc0000fa008)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:547 +0x117
github.com/cockroachdb/cockroach/pkg/sql/colexec.BenchmarkHashRouter.func1(0xc0003f16c0)
	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers_test.go:946 +0x8e3
...
```
and there is no panic with this fix.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46484)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46484#-M3CBk0zD5iXr728HE7u:-M3GQ_1N11KCkp6vcg00:bonn6f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b741c64256834541cd41dd31feb1e2bfcc3309/pkg/sql/colflow/vectorized_flow.go#L169)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why not use the on-disk engine then? We do use it in the benchmarks.

I don't have a strong opinion here, so I'll leave it up to you to decide whether the test is needed.
</blockquote></details>

Good point, changed test to use on-disk engine. I think I stay away from using on-disk for tests to not make them slower, but in this case we're testing file system interactions rather than writing/reading a lot of data.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
Looks like a build issue with `c-deps`, will try again.

bors r=yuzefovich

**Pull request merged**
