### PR TITLE
sql: add dashboard for distributed query reruns as local

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds a couple of metrics that track the number of times "rerun as local" mechanism for distributed errors kicked in as well as the number of times that resulted in a failure. Accordingly it adjusted one of the existing telemetry counters to be about failures rather than successes (which seems to be somewhat more useful). Additionally, these two metrics are now exposed on the SQL dashboard too.

Epic: None

Release note (ui change): An additional dashboard has been added to SQL metrics page. It tracks the number of times distributed queries that resulted in errors were rerun as local as well as when those reruns failed. This "rerun as local" mechanism is new in 23.2 and is enabled by default but could be disabled by updating the undocumented cluster setting `sql.distsql.distributed_query_rerun_locally.enabled` to `false`.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Currently, here is how the dashboard looks:

Screenshot 2023-09-13 at 7 25 45 PM

I'm not sure whether "non negative rate" is right way to expose it. I tried to expose it as a counter per node (by using `downsampleMax`, similar to what we do for `Full Table/Index Scans` dashboard), but I couldn't figure out whether it's possible to have two metrics be side-by-side on a single dashboard. @cockroachdb/cluster-observability is that possible? Or do I need to introduce two separate dashboards for each metric if I want to show each metric as the counter per node?

**Comment by maryliag** [comment]
> I couldn't figure out whether it's possible to have two metrics be side-by-side on a single dashboard.

What do you mean on side-by-side? If you mean just having the two lines, it's possible and is what you're already doing. Unless they would have different units, in this case I don't think is currently possible.
 [Here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/changefeeds.tsx#L55C1-L78C18) is another example of different metrics by node on the same chart using the `downsampleMax`.

**Comment by yuzefovich** [comment]
Oh, yes, `downsampleMax` is what I want. I did try it before but apparently forgot to recompile the binary 😅 
Screenshot 2023-09-14 at 10 17 20 AM

**Comment by yuzefovich** [comment]
friendly ping @cucaroach @msirek

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110619#-:-NfCfPVaCPLX-eUjdHn8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by yuzefovich** [comment]
@maryliag @j82w could you please help me understand the failure on `pkg/ui/workspaces/db-console/eslint.sh`?

**Comment by maryliag** [comment]
@yuzefovich you have some extra spaces on your sql.tsx file, for example compare your line 613 with the line 593 on the same file. You mostly need to remove the extra tab/spaces on the majority of the lines.
Your [error message](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11779666?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&showLog=11779657_2560_2560&logFilter=debug&logView=flowAware) shows which ones you have the extra tab/spaces

Screenshot 2023-09-25 at 5 50 52 PM

**Comment by yuzefovich** [comment]
Thanks Marylia! CI should be green now.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
