### PR TITLE
cli: update zone set flag

### LINKED ISSUE #7643: cli: yaml-consuming commands should use `-f -` for stdin, `-f myfile.yaml` otherwise
The current state of affairs,

```
./cockroach zone set .default 'some
yaml
over
multiple
lines
```

isn't great.

Instead, you'd want

`cat myfile.yaml | ./cockroach zone set -f - default` or `./cockroach zone set -f myfile.yaml .default`.
Kubernetes' `kubectl create` does something similar (and we might be able to crib some code).

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #7643 

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7953)

### CODE REVIEW

**Comment by knz** [comment]
Which issue is this PR addressing?

Also run "make check" before sending in your commits; you will see some useful information in there.

---

Reviewed 4 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cli/cli_test.go, line 492 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDknZE-ITAWlpeDly:-KNCDkn_Wo8MGlvWgu2_:195595692) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L492)):*
> ```Go
> 	}
> 	zone1Writer := bufio.NewWriter(zone1File)
> 	zone1Writer.WriteString("replicas:\n")
> ```

Use a single WriteString for both lines.

---

*[cli/cli_test.go, line 494 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDue2ZuHzMWDDQtNt:-KNCDue2ZuHzMWDDQtNu:-43876545) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L494)):*
> ```Go
> 	zone1Writer.WriteString("replicas:\n")
> 	zone1Writer.WriteString("- attrs: [us-east-1a,ssd]\n")
> 	zone1Writer.Flush()
> ```

Use Close() here, not Flush().

---

*[cli/cli_test.go, line 508 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDxP-j4NyXmLIFS_d:-KNCDxP-j4NyXmLIFS_e:1117646442) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L508)):*
> ```Go
> 		zone1File.Close()
> 		zone2File.Close()
> 		if err := os.Remove(zone1); err != nil {
> ```

Defer Remove() only, not Close().

---

*[cli/cli_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCE-8J1FRpOPW_javM:-KNCE-8J1FRpOPW_javN:-1231126522) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L509)):*
> ```Go
> 		zone2File.Close()
> 		if err := os.Remove(zone1); err != nil {
> 			log.Fatalf("Could not remove zone config file : %v", err)
> ```

no space before ":" in the error message.

---

*[cli/flags.go, line 74 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCD6eU7rrXv6wCpYhN:-KNCD6eVn2vflAoqEiIg:-1117649099) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/flags.go#L74)):*
> ```Go
> `,
> 
> 	cliflags.ZoneConfigName: wrapText(`Zone Config file to set Zone`),
> ```

"File to read the zone configuration from"

---

*[cli/zone.go, line 466 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDLl20SGQcsFHhJx8:-KNCDLl20SGQcsFHhJx9:-1096743081) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/zone.go#L466)):*
> ```Go
> 	}
> 	// judge whether the specified zone config file exists.
> 	if _, err := os.Stat(zoneConfig); err != nil {
> ```

Try removing this check. I think it is not necessary: if the file does not exist, ReadFile below will also report an error.

---

*[cli/zone.go, line 477 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDSkK1yVvotvaFO94:-KNCDSkL_bOVKTKBCjkg:-4161343) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/zone.go#L477)):*
> ```Go
> 	conf, err := ioutil.ReadFile(zoneConfig)
> 	if err != nil {
> 		return fmt.Errorf("read zoneConfig file error : %s", err)
> ```

"error reading zone config: %s"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-:-KNCCsG4G0OUV3QVp7Tj:1629360023)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by a6802739** [comment]
@knz , thanks. I will fix it.

**Comment by knz** [comment]
Also do not forget to use a special case for `-f -`, which should read from standard input instead. (As described in #7643)

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-:-KNCLbPZpoxU0kqdTo7R:1752644091)*

**Comment by a6802739** [comment]
sorry, @knz . I don't know how did it turn to this situation. should I do something now?

**Comment by knz** [comment]
Hi, I am not sure how you got there but I suggest the following solution:

```
git checkout master # swap to master
git pull  # obtain the latest cockroachdb code
git checkout -b new_cli_zone_set master # create a new branch
git cherry-pick cli_zone_set  # take the 1 commit with the changes to the new branch
make test # ensure that the new branch new_cli_zone_set works like you want
git branch -D cli_zone_set # remove the old tip
git checkout -b cli_zone_set # reset the branch
git push -f # push the new tip
```

**Comment by a6802739** [comment]
@knz, thank you very much. I have done it as you say.

**Comment by knz** [comment]
Reviewed 1 of 4 files at r1, 3 of 102 files at r3, 101 of 101 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cli/cli_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCE-8J1FRpOPW_javM:-KNWyMl89LbI1cVM9RI0:1274553577) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L509)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> no space before ":" in the error message.
</details>
There should be no space before, and one space after.
See https://en.wikipedia.org/wiki/Colon_%28punctuation%29#Spacing

---

*[cli/cli_test.go, line 491 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNWy3xoGf45oUG2HC_X:-KNWy3xqaQ9KLruZTz7Y:172470635) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c4393c45e389eb367bcb5e5bed4b1bfc5d1641/cli/cli_test.go#L491)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile1.WriteString("replicas:"); err != nil {
> ```

Use a single call to WriteString for the entire file contents.

---

*[cli/cli_test.go, line 510 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNWyGILoEwFP-Uc6XJ0:-KNWyGIMf3q3bktapCw9:-631298692) ([raw file](https://github.com/cockroachdb/cockroach/blob/15c4393c45e389eb367bcb5e5bed4b1bfc5d1641/cli/cli_test.go#L510)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile2.WriteString("range_max_bytes: 134217728"); err != nil {
> ```

Use a single call to WriteString.

---

*[cli/zone.go, line 470 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNWza6JgkFIxTlKE1I2:-KNWza6Kl-XCs5bbxInl:2093534589) ([raw file](https://github.com/cockroachdb/cockroach/blob/077f27f8e301b3eb84bf585e3e5c127d9a0ac10a/cli/zone.go#L470)):*
> ```Go
> 	origReplicaAttrs := zone.ReplicaAttrs
> 	zone.ReplicaAttrs = nil
> 	//Read zoneConfig file to conf
> ```

Space between "//" and "Read". End sentence with period.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by a6802739** [comment]
@knz , thanks for your review.

**Comment by knz** [comment]
Thanks for pushing this. Just a few minor details remaining.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[cli/cli_test.go, line 491 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNkpsIK88eX7aTFu4oz:-KNkpsIK88eX7aTFu4p-:1125141352) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f547f11a8ad7345a9eeb0666937d1e70f6eb954/cli/cli_test.go#L491)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile1.WriteString("replicas:\n- attrs: [us-east-1a,ssd]"); err != nil {
> ```

Add also a `\n` at the end of the string.

---

*[cli/cli_test.go, line 501 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNkq-XRLyvz-JpDxBz1:-KNkq-XRLyvz-JpDxBz2:-335283145) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f547f11a8ad7345a9eeb0666937d1e70f6eb954/cli/cli_test.go#L501)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile2.WriteString("range_max_bytes: 134217728"); err != nil {
> ```

Add a `\n` at the end of the string.

---

*[cli/cli_test.go, line 508 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNkq3Sk4oOCbcB_4FXk:-KNkq3Sk4oOCbcB_4FXl:-701543736) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f547f11a8ad7345a9eeb0666937d1e70f6eb954/cli/cli_test.go#L508)):*
> ```Go
> 	defer func() {
> 		if err := os.Remove(zone1); err != nil {
> 			log.Fatalf("Could not remove zone config file:%v", err)
> ```

A space is missing *after* the colon. Like this: `... zone config file: %v"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-:-KNkqEWRMRXOLtZK19xn:-1751584789)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-:-KNlLiLS3Z0uHuHfl1Uu:1417088721)*

**Comment by knz** [comment]
@tschottdorf I think this is good to go, what do you think?

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r1, 1 of 101 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[cli/cli_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCE-8J1FRpOPW_javM:-KNlMbUMNdvwKKUk23er:-678969641) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L509)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> There should be no space before, and one space after.
> See https://en.wikipedia.org/wiki/Colon_%28punctuation%29#Spacing
</details>
downcase

---

*[cli/cli_test.go, line 491 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMUFSl-26pCXl6FMJ:-KNlMUFSl-26pCXl6FMK:-562070097) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L491)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile1.WriteString("replicas:\n- attrs: [us-east-1a,ssd]\n"); err != nil {
> ```

if this fails, the file won't be removed?

---

*[cli/cli_test.go, line 492 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMQcWpFUgSKlJNwvF:-KNlMQcWpFUgSKlJNwvG:-678969641) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L492)):*
> ```Go
> 	}
> 	if _, err := zoneFile1.WriteString("replicas:\n- attrs: [us-east-1a,ssd]\n"); err != nil {
> 		log.Fatalf("Could not write string: %v", err)
> ```

downcase

---

*[cli/cli_test.go, line 501 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMYagyoXI9NNoUqHA:-KNlMYagyoXI9NNoUqHB:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L501)):*
> ```Go
> 		log.Fatalf("Could not create zone config file: %v", err)
> 	}
> 	if _, err := zoneFile2.WriteString("range_max_bytes: 134217728\n"); err != nil {
> ```

ditto

---

*[cli/cli_test.go, line 511 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMd80jFr1iYtLjwXO:-KNlMd80jFr1iYtLjwXP:-678969641) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L511)):*
> ```Go
> 		}
> 		if err := os.Remove(zone2); err != nil {
> 			log.Fatalf("Could not remove zone config file: %v", err)
> ```

downcase

---

*[cli/zone.go, line 477 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCDSkK1yVvotvaFO94:-KNlMFqrdcdggQAZrU0S:-2044596574) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/zone.go#L477)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> "error reading zone config: %s"
</details>
`errors.Wrap(err, "could not read zone config")`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[cli/cli_test.go, line 492 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMQcWpFUgSKlJNwvF:-KNlMxQDB8vu3VMPPL0D:815016437) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L492)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> downcase
</details>
actually, just `log.Fatal(err)` all these errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[cli/cli_test.go, line 497 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlN6orJxRzH_83hEFf:-KNlN6orJxRzH_83hEFg:-1976449758) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L497)):*
> ```Go
> 
> 	zone2 := "zone2.yaml"
> 	zoneFile2, err := os.Create(zone2)
> ```

instead of create + write, can you use https://golang.org/pkg/io/ioutil/#WriteFile ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[cli/flags.go, line 74 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlO1Ig_HB0dWv-BEVw:-KNlO1Ih6TxTTF9KdzFp:2054217587) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/flags.go#L74)):*
> ```Go
> `,
> 
> 	cliflags.ZoneConfigName: wrapText(`File to read the zone configuration from`),
> ```

this should mention the `-` behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[cli/cli_test.go, line 509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNCE-8J1FRpOPW_javM:-KNlO016tH_Y2YAEvAM9:1011671347) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c08557d6dea789389596d5a140ed444c8e12438/cli/cli_test.go#L509)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> downcase
</details>
"Downcase" means write `"could not remove...` instead of `"Could not remove...`

---

*[cli/cli_test.go, line 491 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlMUFSl-26pCXl6FMJ:-KNlNIS70DB2TPK5Vaf8:1276585029) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L491)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> if this fails, the file won't be removed?
</details>
songhao: see the other comment about `WriteFile`. Tamir is right, this will simplify. Also wee my comment below about defer (`WriteFile` does not remove the file automatically, you have to do it yourself.)

---

*[cli/cli_test.go, line 497 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlN6orJxRzH_83hEFf:-KNlNfb5CUYFAraq20nB:-2114088350) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L497)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> instead of create + write, can you use https://golang.org/pkg/io/ioutil/#WriteFile ?
</details>
Good idea to use `WriteFile`. See my comment below about defer.

---

*[cli/cli_test.go, line 506 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlNnZjvPZegJklzRGN:-KNlNnZjvPZegJklzRGO:1826440604) ([raw file](https://github.com/cockroachdb/cockroach/blob/72b15803b7e12d8a65813a49df1a72bb5467022c/cli/cli_test.go#L506)):*
> ```Go
> 	zoneFile2.Close()
> 
> 	defer func() {
> ```

Put the defer at the beginning to ensure the files are removed automatically even if an error occurs during writing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-:-KNlX3h-gfJ2fFA38Iog:1417088721)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[cli/flags.go, line 75 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953#-KNlXD-LCQkxKsEKfeHS:-KNlXD-LCQkxKsEKfeHT:-991463833) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9a451c2da2ac5d3a84776cd4e561fc731f8f06/cli/flags.go#L75)):*
> ```Go
> 
> 	cliflags.ZoneConfigName: wrapText(`
> File to read the zone configuration from. Use "-" to specify read from stdin`),
> ```

`Specify "-" to read from standard input.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7953)*

**Comment by knz** [comment]
Brilliant! Thank you so much.

**Comment by a6802739** [comment]
@knz @tamird  thanks for your review.

**Comment by knz** [comment]
@a6802739 could you rebase your latest commit on top of the latest master branch? This should take care of fixing the remaining CI failure.

**Comment by tamird** [comment]
I'm going to go ahead and merge, no need to rebase.

**Pull request merged**
