### PR TITLE
server: add 3 new range issues to the problem range page

### PR DESCRIPTION
**Pull request by BramGruneir**
- No Raft Leader
- Underreplicated
- Invalid or Missing Lease

Part of #14671.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/problem_ranges.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-Kjivn0_JzWtiK0lW9jd:-Kjivn0aspIAln9jzr7B:b-t8a9jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L132)):*
> ```Go
> 				if info.Problems.NoRaftLeader {
> 					curCount := noRaftLeader[info.State.Desc.RangeID]
> 					noRaftLeader[info.State.Desc.RangeID] = curCount + 1
> ```

You can do `noRaftLeader[info.State.Desc.RangeID]++`: https://play.golang.org/p/OrFFnmpU8_

---

*[pkg/server/problem_ranges.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjiwSyz_zL13F-Ropc6:-KjiwSyz_zL13F-Ropc7:bb6mcd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L154)):*
> ```Go
> 
> 	for rangeID, count := range noRaftLeader {
> 		if count == numNodes {
> ```

Is there a reason for this check? I think it is interesting (and problematic) if any replica in a range thinks the range doesn't have a Raft leader.

---

*[pkg/server/problem_ranges.go, line 347 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixfurqVkVmxIELjjV:-KjixfurqVkVmxIELjjW:b-83wn75) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L347)):*
> ```Go
>         </DIV>
>       </DIV>
>       <H2>Invalid or Missing Lease</H2>
> ```

I'd retitle this as `No Lease`. Whether the lease is not present at all or not currently valid amounts to the same thing.

I'd also move this section above `Underreplicated` as I'd like a generate prioritization to the problems here.

---

*[pkg/server/status.go, line 648 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixHphn6h0SJQluae-:-KjixHphn6h0SJQluae0:b-nozxua) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L648)):*
> ```Go
> 				Unavailable:          metrics.RangeCounter && metrics.Unavailable,
> 				LeaderNotLeaseHolder: metrics.Leader && metrics.LeaseValid && !metrics.Leaseholder,
> 				NoRaftLeader:         !storage.HasRaftLeader(raftStatus) && raftState.State != raftStateDormant,
> ```

I think the `raftState.State != raftStateDormant` check is already captured by `storage.HasRaftLeader()`.

Ah, you're probably doing this to capture the lazy-loading of Raft groups. Not sure how to filter those Ranges, but probably something which checks whether `Replica.mu.internalRaftGroup` is present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/server/problem_ranges.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjiyUlKLHCOPvJcCZec:-KjiyUlKLHCOPvJcCZed:bksalr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L348)):*
> ```Go
>       </DIV>
>       <H2>Invalid or Missing Lease</H2>
>       <DIV CLASS="table">
> ```

There's getting to be a lot of repetition here. It's probably time to factor these rows out. 

---

*[pkg/server/status.go, line 640 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixHrvt6JO-zBadJiL:-KjixHrvt6JO-zBadJiM:b-8foqbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L640)):*
> ```Go
> 				EndKey:   desc.EndKey.String(),
> 			},
> 			RaftState:     raftState,
> ```

Why did you change this to pass in `raftState` from the caller instead of using `rep.RaftStatus` in this function? You're already calling methods on `rep` here (e.g. `rep.State` on the next line), so it's unclear why this is different. 

---

*[pkg/server/status.go, line 650 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixZSQSGic5hnD71jj:-KjixZSQSGic5hnD71jk:bf16123) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L650)):*
> ```Go
> 				NoRaftLeader:         !storage.HasRaftLeader(raftStatus) && raftState.State != raftStateDormant,
> 				Underreplicated:      metrics.Leader && metrics.Underreplicated,
> 				NoLease:              metrics.Leader && !metrics.LeaseValid,
> ```

Won't quiescent ranges with expiration-based leases show up as "NoLease" by this metric? I'm not sure that this is actually a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-:-KjiyaQSF-3GjOtbjVZm:bnfp4nl)*

**Comment by BramGruneir** [comment]
All comment addressed and ready for another pass.

---

Review status: 6 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/server/problem_ranges.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-Kjivn0_JzWtiK0lW9jd:-KjizYeU2R-rN_ST67f6:b-uphb9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L132)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can do `noRaftLeader[info.State.Desc.RangeID]++`: https://play.golang.org/p/OrFFnmpU8_
</blockquote></details>

nice, but now unneeded

---

*[pkg/server/problem_ranges.go, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjiwSyz_zL13F-Ropc6:-KjizbLGFgzvjYY8bqei:b-g8fh6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L154)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason for this check? I think it is interesting (and problematic) if any replica in a range thinks the range doesn't have a Raft leader.
</blockquote></details>

This came out of testing.  But I wasn't exposing the HasRaftLeader function early on.  Removed, but I'm leaving in a map to ensure de-duping of ids. 

---

*[pkg/server/problem_ranges.go, line 347 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixfurqVkVmxIELjjV:-Kjj224DdQpiEPSg44SR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L347)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd retitle this as `No Lease`. Whether the lease is not present at all or not currently valid amounts to the same thing.

I'd also move this section above `Underreplicated` as I'd like a generate prioritization to the problems here.
</blockquote></details>

Done.

---

*[pkg/server/problem_ranges.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjiyUlKLHCOPvJcCZec:-Kjj-f_fcZH5U5JfQgpP:b-32e37w) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/problem_ranges.go#L348)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There's getting to be a lot of repetition here. It's probably time to factor these rows out. 
</blockquote></details>

Yeah, I was thinking the same thing.  Was going to do in a fresh pr, but no time like the present.  Done.

---

*[pkg/server/status.go, line 640 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixHrvt6JO-zBadJiL:-KjjBV6gNb46xt6E6we1:b-4koccz) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L640)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why did you change this to pass in `raftState` from the caller instead of using `rep.RaftStatus` in this function? You're already calling methods on `rep` here (e.g. `rep.State` on the next line), so it's unclear why this is different. 
</blockquote></details>

I was trying to avoid adding new calls internally to the function, but you're right, might as well make the call.  Also moved GetLeaseHistory into the function.

---

*[pkg/server/status.go, line 648 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixHphn6h0SJQluae-:-KjjCOWdwJXS08fy6-KR:bpdb2k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L648)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think the `raftState.State != raftStateDormant` check is already captured by `storage.HasRaftLeader()`.

Ah, you're probably doing this to capture the lazy-loading of Raft groups. Not sure how to filter those Ranges, but probably something which checks whether `Replica.mu.internalRaftGroup` is present.
</blockquote></details>

How about using metrics.Quiescent?  I think it works even better and is what you were thinking of.

---

*[pkg/server/status.go, line 650 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixZSQSGic5hnD71jj:-KjjDcsfoWRB3ySCc7G9:b-elramo) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L650)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Won't quiescent ranges with expiration-based leases show up as "NoLease" by this metric? I'm not sure that this is actually a problem.
</blockquote></details>

Didn't notice that in practice, but I'm just using roachdemo so I don't have that many quiescent ranges.  I added a check for quiescent ranges here too which should filter them out appropriately. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-:-KjjGgFDCJkiFpcxwmNm:b-eyw13j)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/problem_ranges.go, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-Kjmjcc8Z7yn5x4r-xaN:-Kjmjcc8Z7yn5x4r-xaO:bqf8mo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbeac7a89fc2c97fea48562e21b47b8368ff1b2b/pkg/server/problem_ranges.go#L54)):*
> ```Go
> 			debugRangeProblemHeaderNoRaftLeader,
> 			debugRangeProblemHeaderNoLease,
> 			debugRangeProblemHeaderUnderreplicated,
> ```

Can we roughly order these by priority?

1. Unavailable
2. No Raft Leader
3. No Lease
4. Raft Leader but Not Lease Holder
5. Underreplicated

---

*[pkg/server/status.go, line 650 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-KjixZSQSGic5hnD71jj:-KjmkPQshlOfRrZ8WHPA:biymf59) ([raw file](https://github.com/cockroachdb/cockroach/blob/45c19e6e543f8500b6cd2e92d87d888cb3b8d6b4/pkg/server/status.go#L650)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Didn't notice that in practice, but I'm just using roachdemo so I don't have that many quiescent ranges.  I added a check for quiescent ranges here too which should filter them out appropriately. 
</blockquote></details>

Seems fine to me. Let's see how this works in practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-:-KjmkY0WHCtkTHjuR7y6:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/problem_ranges.go, line 54 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820#-Kjmjcc8Z7yn5x4r-xaN:-Kjn9W5I7vyKbsm_6a0X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbeac7a89fc2c97fea48562e21b47b8368ff1b2b/pkg/server/problem_ranges.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can we roughly order these by priority?

1. Unavailable
2. No Raft Leader
3. No Lease
4. Raft Leader but Not Lease Holder
5. Underreplicated
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15820)*

**Pull request merged**
