### PR TITLE
Disallow shadowing `err`

### PR DESCRIPTION
**Pull request by tamird**
Also removes `go-nyet` in favour of `go tool vet`.

### CODE REVIEW

**Comment by MBerhault** [comment]
that seems a little overkill, especially since everyone is used to handling err properly.
I'm especially concerned about the anonymous functions added here and there, they really don't improve readability.

**Comment by petermattis** [comment]
Agreed that this seems like overkill. And premature. @tamird can you give some examples in the cockroach code base of bugs caused by the shadowing of `err`?

**Comment by tamird** [comment]
I'm not sure about existing bugs, but I definitely lost some time to shadowing over in #1729. Before realizing what was up, I had used `:=` on https://github.com/cockroachdb/cockroach/pull/1729/files#diff-a376451ad94c99c035e8e8d13cdac4caR162.

**Comment by petermattis** [comment]
The vet shadow check finds a lot of false positives. They usually have this form:

```
	a, err := foo()
	if ... {
		b, err := foo()
		...
	}
	...
	// err is not used again until being reassigned.
	c, err := foo()
	...
```

This shadowing is perfectly ok. The `err` scoped within the if is not used again until it is reassigned. The vet tool does some basic tracking of variable lifetime. It might be straightforward to extend that analysis so that it didn't warn about the above usage. And even if we can't get such a patch accepted upstream, it would be reasonable to run our own customized version of vet. 

PS I disagree with our setting of the `--shadowstrict` setting. That's just asking for busy work.

**Comment by tamird** [comment]
I agree with your analysis. What exactly does `--shadowstrict` do?

**Comment by petermattis** [comment]
`--shadowstrict` causes `vet` to warn about every instance of variable shadowing. See https://github.com/golang/tools/blob/master/cmd/vet/shadow.go#L93. Without `--shadowstrict`, `vet` tracks variable lifetime and won't report variable shadowing if the shadowed variable is not subsequently used.  For example, the following only reports `err` as shadowed if `--shadowstrict` is set:

```
package main

import "fmt"

func foo() (int, error) {
	return 0, fmt.Errorf("foo!")
}

func main() {
	a, err := foo()
	fmt.Println(a, err)
	if a > 0 {
		b, err := foo()
		fmt.Println(b, err)
	}
}
```

But clearly this shadowing of `err` is not problematic. Add a usage of `err` after the if-statement (e.g. `fmt.Println(err)` and `go tool vet --shadow` will report the `err` as being problematically shadowed.

**Comment by tamird** [comment]
So would removing the `--shadowstrict` flag and the `err` exemption be acceptable?

**Comment by petermattis** [comment]
How many `err` shadow violations remain after removing `--shadowstrict`? Mind whipping up a PR which addresses only those violations.

**Comment by bdarnell** [comment]
There are 141 instances of shadowing `err` with `--shadowstrict`, and 65 without. Of those 65, 43 are in tests and 22 are in regular code.

More important than the quantity, though, is the nature of the fix. I think the function expressions make things much less readable. Even simpler fixes like renaming `err` to `getErr` are risky: the name of the error variable occurs three times in a typical `if err := expr; err != nil { return err }`. It would be easy for someone to type `err` instead of `getErr` out of habit, in which case we'd have another subtle bug.

Since shadowing `err` only rarely leads to genuine problems, and in general those places are already known to be doing something odd (handling `err` at a distance), I think the answer is to simply be more vigilant in those areas instead of disallowing `err` shadowing throughout the codebase.

**Comment by tamird** [comment]
Yeah, the function expression ugliness went away with the removal of `--shadowstrict`. I'll open another PR in a few minutes.

**Comment by tamird** [comment]
Closing in favour of #1735.

**Pull request closed without merging**
