### PR TITLE
cli: add cgo compiler, os and arch info to version output

### PR DESCRIPTION
**Pull request by dt**
also hide the dep versions unless requested with --all since they are usually captured by the tag
thanks to glock, and thus just clutter up submitted issue reports.

```
$ ./cockroach version
Build Tag:   beta-20160331-dirty
Build Time:  2016/03/31 14:42:04
Platform:  darwin amd64
Go Version:  go1.6
C Compiler:  4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5766)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/cli.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KEC8byKUK-I6ewCwvt1:-KEC8byKUK-I6ewCwvt2:1904003013) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/cli.go#L46)):*
Can you add another space before the `%s` so the fields are aligned?

---

*[util/build.go, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KEC97Hw2j6YNasXOfD8:-KEC97HxByEPzv4uHacg:437975111) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.go#L25)):*
This seems to return something less useful for gcc. Try building with `build/builder.sh make build` and then `build/builder.sh ./cockroach version`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cli/flags.go, line 480 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECCFKCv827AQiT2QIQ:-KECCFKCv827AQiT2QIR:1160035010) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/flags.go#L480)):*
put an extra newline above this to separate

---

*[cli/cliflags/names.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBa36uToNpNM_gglx:-KECBa36uToNpNM_ggly:797035683) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/cliflags/names.go#L21)):*
"all" is really ambiguous. How about "deps"?

---

*[util/build.proto, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBxDx9B4lnfBEbKbv:-KECBxDx9B4lnfBEbKbw:277965183) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L25)):*
can you rename this field to go_version and remove the json tag? this is just confusing.

---

*[util/build.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBJVUNK7JE6_mqaCd:-KECBJVUNK7JE6_mqaCe:637691067) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L29)):*
we use snake_case in protos

---

*[util/build.proto, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBOuOPyjU2IAhlPNp:-KECBOuOPyjU2IAhlPNq:1829699321) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L30)):*
why bother with the tag?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[cli/cli.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KEC8byKUK-I6ewCwvt1:-KECJEp6Km9nW5P5UuNt:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/cli.go#L46)):*
Done.

---

*[cli/flags.go, line 480 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECCFKCv827AQiT2QIQ:-KECJKWQq5CCsaUckhoE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/flags.go#L480)):*
Done.

---

*[cli/cliflags/names.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBa36uToNpNM_gglx:-KECJLHuNcZLqqfoOaGI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/cli/cliflags/names.go#L21)):*
Done.

---

*[util/build.go, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KEC97Hw2j6YNasXOfD8:-KECJLqtKrV1HqyowDMh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.go#L25)):*
Done.

---

*[util/build.proto, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBxDx9B4lnfBEbKbv:-KECDRvzXGKfiUkma3bq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L25)):*
Done.

---

*[util/build.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBJVUNK7JE6_mqaCd:-KECDJyXw5GZBaxE18xX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L29)):*
Done.

---

*[util/build.proto, line 30 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECBOuOPyjU2IAhlPNp:-KECDJ_URLp-FjyAZVwJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af9c0939afd18c2dd8bd8c835afd8e9ccbf7e57/util/build.proto#L30)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[util/build.go, line 25 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECU7zTfHg4R0RuU_RM:-KECU7zTfHg4R0RuU_RN:-1187746781) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L25)):*
Technically, I believe the hash mark (`#`) is supposed to appear in the first column. So you should de-indent this to line up with the `const char*`.

---

*[util/build.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECUILk40q1ovJEHq8p:-KECUILk40q1ovJEHq8q:46718428) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L30)):*
`"unknown " __VERSION__`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-:-KECUTn58Ws-GZSIDTSk:1417088721)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cli/flags.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECUavql2IovMXTHxAM:-KECUavql2IovMXTHxAN:-1903764000) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/cli/flags.go#L79)):*
s/all //

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by dt** [comment]
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[util/build.go, line 25 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECU7zTfHg4R0RuU_RM:-KECaZwF8cEdkEbsu1Fx:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L25)):*
Done.

---

*[util/build.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECUILk40q1ovJEHq8p:-KECardRzVNyhewM-g-G:-617733435) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L30)):*
I think if it somehow isn't gcc or clang, we can't actually count on `__VERSION__` being defined (i.e. looks like MS VS doesn't define it). 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by petermattis** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/build.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECUILk40q1ovJEHq8p:-KECcfAsf3s5nvXVYWiV:-100421877) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L30)):*
Ah, good point. Carry on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/build.go, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECUILk40q1ovJEHq8p:-KECiRlHLjM1YJQG7z8R:1892486275) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cb1e88d1c0e393b28e04ca0b50000eea96a881b/util/build.go#L30)):*
Perhaps we should log something better than "unknown"? "unknown: not clang or gcc".

---

*[util/build.proto, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECiaX6ucG9O0hd2grh:-KECiaX6ucG9O0hd2gri:-1490272040) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c216d7c10bd253caa71d5d581f782fd26876076/util/build.proto#L25)):*
did this break the UI? sigh

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[util/build.proto, line 25 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766#-KECiaX6ucG9O0hd2grh:-KECjKhYNWNfrDJXbP1D:-738584484) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c216d7c10bd253caa71d5d581f782fd26876076/util/build.proto#L25)):*
yeah, not sure if the UI _acutally_ uses it, but it certainly made the test unhappy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5766)*

**Pull request merged**
