### PR TITLE
glide.yaml: remove all deriveable specifications

### PR DESCRIPTION
**Pull request by tamird**
Also updates build/teamcity-checkdeps.sh to check commands' dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11797)

### CODE REVIEW

**Comment by tamird** [comment]
@dt it seems that we're not actually running teamcity-checkdeps anywhere. can you take care of that?

**Comment by dt** [comment]
Can you expand a bit on what the benefits of this are and if we actually want to do this? 

Seems like we'll be fighting our tools a bit here, since this isn't the standard/intended usage.

Glide docs/design say `glide.yaml` lists the projects dependencies,  so while it may happen to work now with it pruned to just those where we additionally impose a version constraint, I wound't be surprised if our non-standard usage later violates some assumption they make, and we're the ones left debugging a strange failure that no one else seems to be hitting.

This will also require that any time someone `glide get`s a dependency, they need to evaluate which dependencies it adds should or shouldn't be included, and just seems like more special-cases to document, enforce, etc.

Overall, I'm just not quite sure that the benefits of pruning it justify the potential costs.

**Comment by tamird** [comment]
> Seems like we'll be fighting our tools a bit here, since this isn't the standard/intended usage.

> Glide docs/design say glide.yaml lists the projects dependencies, so while it may happen to work now with it pruned to just those where we additionally impose a version constraint, I wound't be surprised if our non-standard usage later violates some assumption they make, and we're the ones left debugging a strange failure that no one else seems to be hitting.

I don't understand what you're saying here. We *still* end up fighting the tools because the tools do the wrong thing. Ultimately, the burden is on us to validate the content of glide.lock (not glide.yaml), and having less junk in general in these files is a benefit, not a detriment.

> This will also require that any time someone glide gets a dependency, they need to evaluate which dependencies it adds should or shouldn't be included, and just seems like more special-cases to document, enforce, etc.

This is already the case - if anything, this partially removes the need to `glide get` when adding new dependencies. Ultimately, this is what checkdeps is for, and *not* merging this PR does not remove the need for that script.

> Overall, I'm just not quite sure that the benefits of pruning it justify the potential costs.

What costs? The bullets above do not make sense to me as "costs".

**Comment by dt** [comment]
The "costs" are the unexpected bumps that come with trying a non-standard/non-recommended usage -- if/when glide decides to assume `glide.yaml` has all direct deps, we're the odd ones out who get to discover what breaks since we're doing something unusual. It's also more special-usage we need to document and educate.

Obviously those are not deal breakers, so if this had a compelling benefit that outweighed them I'd be all for it, but it isn't clear to me that it does: If you just want to see what's pinned, searching for `version` in there is pretty easy.

I'm just not convinced we gain enough to justify being different.

**Comment by tamird** [comment]
Again, this isn't about finding out what's pinned - it's about preventing rot. Currently we have no documentation explaining what to do when we *remove* a dependency, and this fixes that by including only those things which glide does not properly account for (meaning nothing needs to be done when removing non-cmd deps).

Also, discovery of a change in these semantics will be trivially obvious as glide.lock will change, and checkdeps will flag it (when it's actually hooked up).

What education are you envisioning? In practical terms, we've never had an external contributor add a cmd dependency, which after this change is the only case that would require "non-standard" interaction with glide.yaml.

**Comment by dt** [comment]
Chatted offline:
I'm still not crazy about being the special project with a non-standard usage, but it is easy enough to get out of this situation: we move the minimal `yaml` over, `glide init` and then re-add everything from the minimal one (the tools and overrides).
Given our ability to easily get back to the standard usage if/when it becomes an issue, doing this for now seems fine if it makes our most-frequent-dep-updater happy.

One caveat (also discussed offline): `glide.yaml` should be the source of additional roots for `checkdeps` rather than the glockfile.

**Comment by tamird** [comment]
> One caveat (also discussed offline): glide.yaml should be the source of additional roots for checkdeps rather than the glockfile.

Further discussed offline: the glide.yaml syntax which uses `subpackages` means that a full YAML parser is needed for this.

Also agreed offline that this PR, as-is, is better than the current state, so I'm merging it, with some follow-on work to be done by @dt.

**Pull request merged**
