### PR TITLE
cmd/smithcmp: sql arrays

### PR DESCRIPTION
**Pull request by madelynnblue**
Release justification: Category 1: Non-production code changes

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Second commit LGTM. Not really sure what the first commit is for. Maybe a PR description could help.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40624#-:-LoaGZgJ9pDoauobZC_X:bzfp9i9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @solongordon)

___
*[pkg/cmd/smithcmp/tpch.toml, line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40624#-LoaGHl-3jclTA36F6L7:-LoaGHl-3jclTA36F6L8:bdjjutx) ([raw file](https://github.com/cockroachdb/cockroach/blob/82b3aec84c1ce0608e7aa0e60b33adc968ed1660/pkg/cmd/smithcmp/tpch.toml#L503)):*
> ```TOML
> ]
> 
> # Missing: 9, 13, 15, 16, 17, 21
> ```

Why are these ones missing? Maybe we could add them in but mark them as disabled for now. It's still useful to compare non-vec and postgres even if vec can't do these queries yet.

**Review by madelynnblue — COMMENTED** [review]
The first commit has its description in the commit message: it's useful for TPCH comparison testing. I needed it to convert our TPCH schema into a postgres-compatible one so I could load postgres with identical data.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40624#-:-LoaLOoj6o6-3MSVKEi-:b-c44kvl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/cmd/smithcmp/tpch.toml, line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40624#-LoaGHl-3jclTA36F6L7:-LoaLdKG93Ti3XV5Dwo3:b-odjrl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/82b3aec84c1ce0608e7aa0e60b33adc968ed1660/pkg/cmd/smithcmp/tpch.toml#L503)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why are these ones missing? Maybe we could add them in but mark them as disabled for now. It's still useful to compare non-vec and postgres even if vec can't do these queries yet.
</blockquote></details>

These are missing because there's nothing to parameterize. That is, the constant datums in those are very specific and shouldn't be randomized. If we want to ensure that vec and non-vec are correct with these unchanged queries, then that should be hard coded in some nightly test somewhere. This program is specifically for randomized testing where the result is unknown.

**Comment by mjibson** [comment]
@jordanlewis I've updated the commit messages and comments about the missing queries to include this commentary. PTAL.

**Comment by jordanlewis** [comment]
Okay, I see that the idea is to make Cockroach SQL parsable by Postgres. Is there an example of this?

Also, check your email about "Release justification" - PRs need to have a line that says "Release justification: blah" until the release branch is cut.

**Comment by mjibson** [comment]
Any table dumped with `cockroach dump` will include column families, which aren't supported by postgres. Postgres doesn't support adding indexes directly in the CREATE TABLE statement, they must be added later with a CREATE INDEX statement. Postgres doesn't support primary keys with descending columns. TPCH has all of these things and thus requires rewriting our CREATE TABLE statements to fit its needs.

I'm planning on just waiting for the release period to be over before I merge this stuff.

**Pull request merged**
