### PR TITLE
geo: minor fix ups to ST_Summary

### PR DESCRIPTION
**Pull request by otan**
Minor fixes to ST_Summary to make it more PostGIS like:
* Correct ordering of the symbols.
* Fix bounding boxes not being reported in sub structures.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/summary.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50782#-MB1MATREwWOWup0L-TI:-MB1MATREwWOWup0L-TJ:b-v2rbf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dad44effe915665c8618569c7124a2a00f187c6c/pkg/geo/summary.go#L74)):*
> ```Go
> 		for i := 0; i < numPoints; i++ {
> 			point := t.Point(i)
> 			line, err := summary(point, false, hasSRID, geopb.ShapeType_Point, isGeography, offset+2)
> ```

is this false because the `MultiPoint` may have a bounding box, but the individual points don't?

**Comment by otan** [comment]
___
*[pkg/geo/summary.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50782#-MB1MATREwWOWup0L-TI:-MB1N0oo7ioKSezWj6VN:bnuwd6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dad44effe915665c8618569c7124a2a00f187c6c/pkg/geo/summary.go#L74)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this false because the `MultiPoint` may have a bounding box, but the individual points don't?
</blockquote></details>

Yep. all children do not have one in PostGIS.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50782#-:-MB1PvqlDs-FmEMXnQzt:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
