### PR TITLE
WIP distsql: use column group ordering in JOINs

### PR DESCRIPTION
**Pull request by rjnn**
Commits 1-3 are from #17439 (currently also a WIP), only the 4th commit is for review.

This is a very rough WIP commit, but sending it out to get early feedback to see if there's anything  obviously wrong. I've added some tests, including one that is currently incorrect (marked with a TODO(arjun)). If its not immediately obvious whats wrong, I'll continue to hack at it later. Suggestions on more tests welcome, although I intend to add explicit nested joins to the tests before merging.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for working on this! The direction is good.

My main comment is to compute the ordering once during expandPlan (same place where we currently compute the merge join ordering) and store it in the node. And then `trim` it as necessary in `simplifyOrderings`. As things stand, if we do a merge join, because we advertise the full (untrimmed) ordering, we may be using ordered synchronizers in distsql to maintain that ordering after the join even if we don't care about it.

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/plan_ordering.go, line 49 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqitIKUVQKGBR-YUzg5:-KqitIKUVQKGBR-YUzg6:b-ooezv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L49)):*
> ```Go
> 		// First we compute the ordering that would be retained after a join.
> 		// This ordering is an index into the equality indexes.
> 		equalityColumnOrderingAfterMerge := computeMergeJoinOrdering(
> ```

Any reason we have to recompute this instead of using `n.mergeJoinOrdering`?

---

*[pkg/sql/plan_ordering.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqitc4eR25hDkssqi1x:-Kqitc4eR25hDkssqi1y:bj873ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L64)):*
> ```Go
> 				// at index col.
> 				group := orderingColumnGroup{}
> 				group.cols.Add(uint32(n.pred.leftEqualityIndices[col.ColIdx]))
> ```

the value we add to cols is a column in the `joinNode`'s schema. This needs to be something like `n.pred.numMergedEqualityColuns + n.pred.leftEqualityIndices[..]` for the left side and `n.pred.numMergedEqualityColumns + n.pred.numLeftcols + n.pred.rightEqualityIndices[..]` for the right side. We should probably hide these calculations behind some helper methods.

---

*[pkg/sql/plan_ordering.go, line 65 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqitSCGJkFfsskQ2DxS:-KqitSCGJkFfsskQ2DxT:bydkri1) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L65)):*
> ```Go
> 				group := orderingColumnGroup{}
> 				group.cols.Add(uint32(n.pred.leftEqualityIndices[col.ColIdx]))
> 				group.cols.Add(uint32(n.pred.rightEqualityIndices[col.ColIdx]))
> ```

Also, `if n.pred.numMergedEqualityColumns > i { group.cols.Add(uint32(i)) }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-:-KqiuDQZLQzVp-pA3ulv:b-1ko2fq)*

**Comment by knz** [comment]
Reviewed 5 of 5 files at r4.
Review status: 5 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by arjunravinarayan** [comment]
Done. Thank you for your comments! Ready for another review, PTAL @knz!

FWIW, it is no longer clear to me why we retain `mergeJoinOrdering` separately, since it can just be rolled into `ordering`?

I added a few more test cases, which revealed a flaw: currently merge joins are not propagating their ordering in DistSQL due to not setting the `mergeOrdering` correctly, but we're very close to being able to do so - the orderings are properly propagated in Classic SQL (see test case plan diagrams in `distsql_join`). That would be the last task.

I have rebased this PR on top of #17439, so please ignore all commits except r12. 

---

Review status: 0 of 23 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1627 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzPseKdMfD8c6qlPzS:-KqzPseKdMfD8c6qlPzT:b-kyel16) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/distsql_physical_planner.go#L1627)):*
> ```Go
> 		// A MergeJoiner guarantees an ordering to its outputs, so we ensure
> 		// that ordering is propagated through the output synchronizer.
> 		// TODO(arjun): Not done yet.
> ```

Flagging this TODO for help, cc @knz, @raduberinde.

---

*[pkg/sql/plan_ordering.go, line 49 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqitIKUVQKGBR-YUzg5:-KqxPZRnGFuor6mmPpKh:bjwozba) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Any reason we have to recompute this instead of using `n.mergeJoinOrdering`?
</blockquote></details>

No. Reused.

---

*[pkg/sql/plan_ordering.go, line 64 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqitc4eR25hDkssqi1x:-KqxiSZpUySQwU7DC3QO:bknzrwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

the value we add to cols is a column in the `joinNode`'s schema. This needs to be something like `n.pred.numMergedEqualityColuns + n.pred.leftEqualityIndices[..]` for the left side and `n.pred.numMergedEqualityColumns + n.pred.numLeftcols + n.pred.rightEqualityIndices[..]` for the right side. We should probably hide these calculations behind some helper methods.
</blockquote></details>

Done. Added a helper.

---

*[pkg/sql/plan_ordering.go, line 65 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqitSCGJkFfsskQ2DxS:-Kqxe5R44jxPiAitynmG:byklz4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/68144c290b0a66bb5b40a4642816bad7a3959138/pkg/sql/plan_ordering.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Also, `if n.pred.numMergedEqualityColumns > i { group.cols.Add(uint32(i)) }`
</blockquote></details>

Done, except its not `i`, its `col.colIdx` and we need the rest to be an `else` case. 

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 124 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzQ_oewSP_NnOEG_B6:-KqzQ_oewSP_NnOEG_B7:buf5zq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/logictest/testdata/logic_test/distsql_join#L124)):*
> ```
> 3  ·       spans           ALL                ·                               ·
> 
> # TODO(arjun): this is wrong, the final synchronizer should be ordered.
> ```

cc @knz, @raduberinde this URL is where you can clearly see that the mergejoiner output needs the ordering synchronizer set properly (and in a couple more testcases below).

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 200 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzQhv3NAycZji0w58E:-KqzQhv3NAycZji0w58F:b-fvlspu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/logictest/testdata/logic_test/distsql_join#L200)):*
> ```
> 5  ·       spans           ALL                          ·                                                                                                                                                                                       ·
> 
> ## TODO(arjun): Nested merge joins are not propagating their ordering
> ```

cc @knz, @raduberinde: And this is where you can see that the lack of a synchronizer affects downstream queries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-:-Kqxv0-QoVxwsW02dDib:b-10816t)*

**Comment by RaduBerinde** [comment]
Cool! I have some comments that should help.

---

Review status: 0 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1613 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzccYV-2dFk5cIPiLG:-KqzccYV-2dFk5cIPiLH:b7ttnqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/distsql_physical_planner.go#L1613)):*
> ```Go
> 			MergedColumns:  mergedColumns,
> 		}
> 		outputMergeOrd = orderingTerminated
> ```

This needs to be handled the same for both. We now advertise the ordering in the plan, so both local SQL and dist SQL need to provide it.

---

*[pkg/sql/distsql_physical_planner.go, line 1626 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzcNpwRZkC4PkJdNrQ:-KqzcNpwRZkC4PkJdNrR:bb9b1k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/distsql_physical_planner.go#L1626)):*
> ```Go
> 
> 		// A MergeJoiner guarantees an ordering to its outputs, so we ensure
> 		// that ordering is propagated through the output synchronizer.
> ```

[nit] There is no such thing as an output synchronizer. We want to say "through to the input synchronizer of the next stage, if necessary".

We probably just need to call `SetMergeOrdering`. Since the equality columns are equal, we can choose to put either side in there.

---

*[pkg/sql/join.go, line 572 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzcqCQDgp085dH8ZFQ:-KqzcqCQDgp085dH8ZFR:boyl2hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L572)):*
> ```Go
> 	// TODO(arjun): Support order propagation for other JOIN types.
> 	if n.joinType == joinTypeInner {
> 		for _, col := range n.mergeJoinOrdering {
> ```

Here we should look at the ordering of the source plan and propagate any constant columns (formerly known as "exact match"). Note that if one equality column is constant on one side, all two/three columns in the output would also be constant. This can be a TODO for a later PR.

This would be a reason to still have the separate `mergeJoinOrdering`. Conceptually: `mergeJoinOrdering` is what columns we need to compare when doing the merge join; `n.ordering` contains the physical properties of the output stream.

---

*[pkg/sql/join.go, line 587 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqzea3XTQ-cu4meXqDy:-Kqzea3XTQ-cu4meXqDz:b-v6fvyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L587)):*
> ```Go
> 				// then add all the columns from the left and right inputs that
> 				// have an ordering.
> 				group.cols.Add(n.equalityColIdxInSchema(col.ColIdx, false))
> ```

/* !right */

---

*[pkg/sql/join.go, line 588 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqzeb_S6LDz20t_XQPu:-Kqzeb_S6LDz20t_XQPv:bnva6vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L588)):*
> ```Go
> 				// have an ordering.
> 				group.cols.Add(n.equalityColIdxInSchema(col.ColIdx, false))
> 				group.cols.Add(n.equalityColIdxInSchema(col.ColIdx, true))
> ```

/* right */

---

*[pkg/sql/ordering.go, line 288 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzdsVvAgQrrjSFtJeX:-KqzdsVvAgQrrjSFtJeY:b-17u6os) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/ordering.go#L288)):*
> ```Go
> // columns are left untouched.
> //
> // TODO(arjun): this is my proposal below for how to trim column groups. It
> ```

What's the benefit of this? I don't see the harm in leaving the groups - we can just pick any column from each group if need be.

---

*[pkg/sql/ordering.go, line 319 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzeEnUMqHHLo-WJAbd:-KqzeEnUMqHHLo-WJAbe:bmbpm3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/ordering.go#L319)):*
> ```Go
> 		// previous column groups does - for example, if we have an ordering
> 		// (1/2)+,3+ and the desired ordering is 1+,3+,2+ the 2+ is redundant with
> 		// 1+ and can be removed.
> ```

Well, we're not talking about a redundant column in `ord` (which would be illegal). We are talking about a redundant column in `desired`, and we're not modifying `desired` so I think "ignored" was better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-:-KqzevP31eFVVhWkFu3F:bkhlyyt)*

**Comment by arjunravinarayan** [comment]
Thank you! All tests passing, PTAL.

---

Review status: 0 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 1613 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzccYV-2dFk5cIPiLG:-Kr2BL1ehBphv0xe6lFV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/distsql_physical_planner.go#L1613)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This needs to be handled the same for both. We now advertise the ordering in the plan, so both local SQL and dist SQL need to provide it.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 1626 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzcNpwRZkC4PkJdNrQ:-Kr1QxEqqI64QMCTl_-C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/distsql_physical_planner.go#L1626)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] There is no such thing as an output synchronizer. We want to say "through to the input synchronizer of the next stage, if necessary".

We probably just need to call `SetMergeOrdering`. Since the equality columns are equal, we can choose to put either side in there.
</blockquote></details>

Done.

---

*[pkg/sql/join.go, line 572 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzcqCQDgp085dH8ZFQ:-Kr2Z9fWBi6lz_g8wdlo:b2vtk5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L572)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we should look at the ordering of the source plan and propagate any constant columns (formerly known as "exact match"). Note that if one equality column is constant on one side, all two/three columns in the output would also be constant. This can be a TODO for a later PR.

This would be a reason to still have the separate `mergeJoinOrdering`. Conceptually: `mergeJoinOrdering` is what columns we need to compare when doing the merge join; `n.ordering` contains the physical properties of the output stream.
</blockquote></details>

Done, I think. PTAL.

---

*[pkg/sql/join.go, line 587 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqzea3XTQ-cu4meXqDy:-Kr2An6nuhRtIyUkqhqc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L587)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

/* !right */
</blockquote></details>

Done.

---

*[pkg/sql/join.go, line 588 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kqzeb_S6LDz20t_XQPu:-Kr2AtrDgQ_TU6H5Bz2h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/join.go#L588)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

/* right */
</blockquote></details>

Done.

---

*[pkg/sql/ordering.go, line 288 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzdsVvAgQrrjSFtJeX:-Kr2AusWOcXarXX7HLLP:b-p36tvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/ordering.go#L288)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What's the benefit of this? I don't see the harm in leaving the groups - we can just pick any column from each group if need be.
</blockquote></details>

It was an idea I was playing around with. Removed.

---

*[pkg/sql/ordering.go, line 319 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-KqzeEnUMqHHLo-WJAbd:-Kr2B8d_0UhY3M9zBIZb:bmjr761) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0692a53325e6913c8596556366e25c170993019/pkg/sql/ordering.go#L319)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Well, we're not talking about a redundant column in `ord` (which would be illegal). We are talking about a redundant column in `desired`, and we're not modifying `desired` so I think "ignored" was better.
</blockquote></details>

I agree. Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-:-Kr2_gWmpTQp00mcqgs9:b-pc6e9x)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 23 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/join.go, line 572 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr695awRybkxyHlK4N-:-Kr695awRybkxyHlK4N0:b-4utlcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/join.go#L572)):*
> ```Go
> 	// TODO(arjun): Support order propagation for other JOIN types.
> 	if n.joinType == joinTypeInner {
> 		info.constantCols = n.ordering.constantCols.Copy()
> ```

n.ordering? Isn't that what this function is used to initialize? We need to copy the constant columns from the left and the right side with the correct indices, similar to what we're doing below. This can be a TODO for a follow-up change since it's not critical.

---

*[pkg/sql/join.go, line 585 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr69N5J_iJSveMV1SDm:-Kr69N5J_iJSveMV1SDn:buy5vwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/join.go#L585)):*
> ```Go
> 			if col.ColIdx < n.pred.numMergedEqualityColumns {
> 				group.cols.Add(uint32(col.ColIdx))
> 			} else {
> ```

I don't think this should be `else`. We should always add the left and right columns to the group, even if we have a merged column. A query like this is legal and uses all three columns:  `SELECT x, a.x, b.x FROM a JOIN b USING(x)`

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 201 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6BO6Sh33RbL_PGijl:-Kr6BO6Sh33RbL_PGijm:b-tw5m41) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L201)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) (SELECT * FROM (SELECT a,b from data AS data3 NATURAL JOIN ((SELECT a,b FROM data AS data1) JOIN (SELECT c,d FROM data AS data2 ORDER BY c,d) ON a=c AND b=d)))]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzsmE9r20wQxu_vpwhzeku24F3Jf2Io6NgUmpS0t-KDYm1tg-M1KxkaQr57sR0qpHXm8VSyQeCjbf00s5PVT0_2hVYus3fpk81p_JM0KTKkKCJFMSnq00TR2rupzXPnt5fsgdvsN417ihar9abYfj1RNHXe0viFikWxtDSmH-nj0j7YNLOeFGW2SBfLXZG1Xzyl_jnJ0iIlRfebYnyVaJUYlUQqiWnyqshtirc7lzd8fL6ap_m8erMqOFGUF-nM0li_qlO2-g9NVtozp2vvwAzLupGk7nfni3rJRF-rxFw3XX_8bh_lrZzPrLfZu_WPvvLA0r5aP7Nf3GJVX9_S_ir-f0M_fPKL2bz8eLLN2j9iGpvVoVVWxvDeJQfW_znN58zy_7ZZjqD8insQyjUNGqzpQMN37qNb15d-sPCwUlh3R1Ktt9qupFptTyApUPdsktIXScFpdFtSpjuuaL3Vdl3RansCV4C6Z3OFubgCTqPbroi644rWW23XFa22J3AFqHs2V0QXV8BpdNsVcXdc0Xqr7bqi1fYErgB1z-aK-OIKOI1uuwIcyT3YfO1WuT3qJKS3XZDNZnY_oNxt_NR-8266K7P_eL_jdv_PZTYv9r_29x9uV_uftg0eD2vTiB41oU3chI56PK1ZGpTmYa0b0cMmtIka0Tc8bep0rzLyCtyrw5Fg4kYG1yYupYdN6NrEpfQNT8eCZ1sI155tKT1qQhvw5-bp2rMd0H12mw74PT7g97jmN_mwiYt5GLkY0MDFPI1czNPIxaMmLuZh5GJAAxfzNHIxoIGLb9h9qnv8PtX82xM8noBGOkY48DHAkZARDoys-VcoUDKgkZMRDqQMcGRlgCMtaz4-AC9r_kUK1Apo5FaEA7kCHNkV4DDq8m9TVBzkABR2AY7SLsgRKO4CHDhW80lCD4BkgywhkixPQ8kCHEmWx6FkAY4kK8lRUhpKVpSkpDiUrChLhXiQKkSSDVKFSLI8DSULcCRZHoeS5XEkWSMJVFIaSRbhQLIAR5JFODpUCFJFZccaw0vWBKlCIllAI8kiHEgW4EiyCAeSNZJEJaWRZBEOJAtwJFmAI8maIFZIJGuCVCGRLKCRZBEOJAtwJFmAQ8lKApWUhpIVBSopDiUrClQhHqSKqmRHQLKSI5rwcRGd0YhxJFnRKY0YR5KVJCopDSUrSlRSHEpWlKjCg_MgVrCSnbz-9ycAAP__rsUAIA==
> ```

This should be working no? Maybe the correction I mentioned (adding all three columns to the group) fixes it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 166 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6FZvsdxbN91eqoL1V:-Kr6FZvsdxbN91eqoL1W:b-vep52g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L166)):*
> ```
> # Nested merge joins should be planned on the same ordering
> query ITTTTT
> EXPLAIN (VERBOSE) (SELECT * FROM (SELECT a,b from data AS data3 NATURAL JOIN ((SELECT a,b FROM data AS data1) JOIN (SELECT c,d FROM data AS data2 ORDER BY c,d) ON a=c AND b=d)))
> ```

I don't get this query. Why the outer `SELECT *`? Did you mean to close a paren after the first select:
`(SELECT a,b from data) AS data3 NATURAL JOIN ..`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 23 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/join.go, line 572 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr695awRybkxyHlK4N-:-Kr6zzqEw4FUn-dfAkHW:b-7yd1q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/join.go#L572)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

n.ordering? Isn't that what this function is used to initialize? We need to copy the constant columns from the left and the right side with the correct indices, similar to what we're doing below. This can be a TODO for a follow-up change since it's not critical.
</blockquote></details>

Added a TODO.

---

*[pkg/sql/join.go, line 585 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr69N5J_iJSveMV1SDm:-Kr6yyTzG8rRPRdi5srt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/join.go#L585)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this should be `else`. We should always add the left and right columns to the group, even if we have a merged column. A query like this is legal and uses all three columns:  `SELECT x, a.x, b.x FROM a JOIN b USING(x)`
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 166 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6FZvsdxbN91eqoL1V:-Kr6zLO25yi7c4_8EVpT:bmed5zd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't get this query. Why the outer `SELECT *`? Did you mean to close a paren after the first select:
`(SELECT a,b from data) AS data3 NATURAL JOIN ..`?
</blockquote></details>

Removed. Detritus from when I was trying to construct a 3 way join.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 201 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6BO6Sh33RbL_PGijl:-Kr71DDi9TsfMLJYT7ND:b-tvgvh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be working no? Maybe the correction I mentioned (adding all three columns to the group) fixes it?
</blockquote></details>

No, its still not working. I'm puzzled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 201 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6BO6Sh33RbL_PGijl:-Kr78v6AmIYuMZbmrna6:b-3ugfwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L201)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

No, its still not working. I'm puzzled.
</blockquote></details>

Ok, I think it's a problem with `computeMergeJoinOrdering`, I'm working on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 201 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6BO6Sh33RbL_PGijl:-Kr7FCw4r9AeUgD9irJD:b-i335w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ok, I think it's a problem with `computeMergeJoinOrdering`, I'm working on it.
</blockquote></details>

Can you try rebasing now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_join, line 201 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-Kr6BO6Sh33RbL_PGijl:-Kr7w2akc9zWH4uEdtb-:b-lzqklr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7bdaecb1bef4df2ae5a32a67bc3b01c1def7fba/pkg/sql/logictest/testdata/logic_test/distsql_join#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you try rebasing now?
</blockquote></details>

Looks like you fixed it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454)*

**Comment by RaduBerinde** [comment]
:lgtm: :tada: 

---

Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17454#-:-Kr8aMp59pFOi4-isNrC:by6fmpn)*

**Pull request merged**
