### PR TITLE
cli: add a flag to allow listening on all interfaces

### LINKED ISSUE #1008: cli: add flag for external address for internode-communication
This will be necessary for spanning cloud service infrastructure.

### PR DESCRIPTION
**Pull request by tamird**
This permits users to use the --host and --port flags to control the
node's advertised external address while listening on all interfaces.

Fixes #1008.

cc @mberhault

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6862)

### CODE REVIEW

**Comment by bdarnell** [comment]
See also #5816, which is a request for a way to bind to multiple specific interfaces (but not all of them). I think it may be better to go ahead and implement a list of secondary addresses to bind instead a special case to bind to everything.

**Comment by tamird** [comment]
FYI it's not so simple (https://github.com/golang/go/issues/9334), so the multiple `--host` flags suggested in #5816 won't work.

**Comment by petermattis** [comment]
@tamird Can't you create a new listener for each address you want to listen on? You could probably wrap that up in a `MultiListen` method that does the multiplexing internally.

**Comment by mberhault** [comment]
what does this give us over the use of `--host=0.0.0.0`?

**Comment by petermattis** [comment]
@mberhault You can specify exactly which interfaces you listen on.

**Comment by mberhault** [comment]
sorry, I meant what does this current PR give us that `0.0.0.0` doesn't? we're still only allowing one interface or all.

**Comment by tamird** [comment]
right, but --host currently controls the advertised address as well as the listening address

**Comment by mberhault** [comment]
sure, but that has nothing at all to do with what we listen on. I would prefer to see `--host` control which interface(s) we bind to, and a separate flag overriding our advertised address.

**Comment by tamird** [comment]
Updated, PTAL.

**Pull request closed without merging**
