### PR TITLE
sql: rework @index syntax

### PR DESCRIPTION
**Pull request by RaduBerinde**
The syntax `@` is implemented as an indirection, which makes the parser happy to
accept it for any table or column name. Various statements like
`INSERT INTO table@idx..` silently ignore the index. The recent index hint
additions makes this worse (e.g. `@{FORCE_INDEX=x}` is accepted in statements
like `DROP INDEX`).

In this change we reimplement this syntax:
- for `DROP INDEX` and `ALTER INDEX` we introduce a `TableNameWithIndex`, which
  makes the index mandatory.
- for selecting from a table, we add an optional `IndexHints` field in
  `AliasedTableExpr` which supports the full "index hints" syntax.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5838)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/sql.y, line 2273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838#-KEWnIXKm5jLiakhNleo:-KEWnIXKm5jLiakhNlep:912103211) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec3ddafdf878373eb2ecf99e4a0f5ca4595c88e/sql/parser/sql.y#L2273)):*
I'm not sure if this rule is buying you anything. Why not just use `FORCE_INDEX` where desired? Ditto for `no_index_join_keyword`. I see this is just code movement, I should have noticed this in the last code review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838#-:-KEWo3rKlqFgyqLFBNa6:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/sql.y, line 2273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838#-KEWnIXKm5jLiakhNleo:-KEWpJhhSi3z_mDvxOyv:-654085579) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec3ddafdf878373eb2ecf99e4a0f5ca4595c88e/sql/parser/sql.y#L2273)):*
Without this it doesn't work - we generate the keyword list based on rules that end in _keyword. The _keyword rules themselves need to be used somewhere too, I can't just put both words in a single _keyword and then not use that rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838)*

**Comment by petermattis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.y, line 2273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838#-KEWnIXKm5jLiakhNleo:-KEWqBSN_Om2sY2zJYAc:-167706726) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec3ddafdf878373eb2ecf99e4a0f5ca4595c88e/sql/parser/sql.y#L2273)):*
Ah, subtle. Got it. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.y, line 2273 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838#-KEWnIXKm5jLiakhNleo:-KEWqhJCSNW3h3yXwFfn:-878646848) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ec3ddafdf878373eb2ecf99e4a0f5ca4595c88e/sql/parser/sql.y#L2273)):*
Hm, maybe I should just put them under `unreserved_keyword`. I'll try that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5838)*

**Pull request merged**
