### PR TITLE
security: allow automatic re-hashing from SCRAM to bcrypt

### LINKED ISSUE #96408: sql: add a cluster setting to easily roll back SCRAM
Downgrading from SCRAM currently requires multiple steps:
https://www.cockroachlabs.com/docs/v22.2/error-handling-and-troubleshooting#downgrade-from-scram-authentication

There are valid reasons why a user might want to downgrade:  compatibility with old drivers, unexpected connection latency hits, etc.

Having to alter the password for each user to downgrade them to SCRAM is not scalable if a cluster has many SQL users. We should think about a cluster setting that can effectively fold the three steps currently required to roll back to bcrypt into one.

Jira issue: CRDB-24398

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/96408

Release note (security update): Currently the process to change
passwords from SCRAM hashing to bcrypt hashing is manual and can take a
long time. An operator may wish to do this if their tools do not support
SCRAM or if SCRAM is not desired for another reason.
This change introduces the new cluster setting
`server.user_login.downgrade_scram_stored_passwords_to_bcrypt.enabled`,
which defaults to true. If it is true AND
`server.user_login.password_encryption` is `crdb-bcrypt`, then during
login, the stored hashed password will be converted from SCRAM to bcrypt.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Very nice.

LGTM modulo code organization.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-:-NOzxzv76PAy2a4iobDs:bwei2ky)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzwudw1NaxALDBjeZG):*
I'd recommend explaining the use case (why this is useful, when would a user want to use it etc) before the change.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzws1U1wUOGIQboKSx):*
nit: add quotes around the setting names
___
*[`pkg/security/password/password.go` line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzxMmD2nsVNhnsW40s:-NOzxMmE1j9N1CHDWdqv:bt4rkdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0256b675e981b01370219069def839f3f58d417/pkg/security/password/password.go#L719)):*
> ```Go
> 	// - conversion enabled by cluster setting.
> 	// - the configured default method is scram-sha-256.
> 	if isBcrypt && autoUpgradePasswordHashes && PasswordHashMethod == HashSCRAMSHA256 {
> ```

This function is becoming large and hard to read/maintain. I'd recommend splitting it up. 
___
*[`pkg/security/password/password.go` line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzxavLE9tAhDPQTm8g:-NOzxavMAg9ghDwUN2ss:b-wwzzjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0256b675e981b01370219069def839f3f58d417/pkg/security/password/password.go#L719)):*
> ```Go
> 	// - conversion enabled by cluster setting.
> 	// - the configured default method is scram-sha-256.
> 	if isBcrypt && autoUpgradePasswordHashes && PasswordHashMethod == HashSCRAMSHA256 {
> ```

The isBcrypt/isScram bools can be replaced by a type `switch`.

**Comment by rafiss** [comment]
RFAL. For some reason, I can't reply to your comments inline (nor see them inline). I extracted some of the common logic, and adjusted the release note. I don't feel like a type switch improves readability, since we also need to check those other bools.

**Review by knz — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97429)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzwudw1NaxALDBjeZG):*
I'd recommend explaining the use case (why this is useful, when would a user want to use it etc) before the change.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97429#-NOzws1U1wUOGIQboKSx):*
nit: add quotes around the setting names

**Comment by knz** [comment]
sorry i don't know why my comments were duplicated. please ignore

**Comment by rafiss** [comment]
tftr! flake in Extended CI was https://github.com/cockroachdb/cockroach/issues/96343

bors r=knz

**Pull request merged**
