### PR TITLE
sql: implement ST_AsTWKB

### PR DESCRIPTION
**Pull request by otan**
Refs #48886, #52013

Release note (sql change): Implement a subset of variants for ST_AsTWKB,
which encodes a geometry into a TWKB format. This allows the use of
GeoServer with CRDB if the user selects "PreserveTopology" for their
"Method used to simplify geometries" option on the "Store" page.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-:-MZP1c09-Olo8gjcsAGo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/twkb/twkb.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-MZP-ldk44pGQY0A0zWB:-MZP-ldk44pGQY0A0zWC:b-5lwj3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/21be6ffa77f9d774e3fe533c4a7b1557a8e4136f/pkg/geo/twkb/twkb.go#L12)):*
> ```
> https://github.com/TWKB/Specification/blob/master/twkb.md.
> ```

I only browsed the spec, so I haven't really reviewed whether the following code is accurate compared to the spec.
___
*[pkg/geo/twkb/twkb.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-MZP1Gr1DhAAKeJIGFuN:-MZP1Gr1DhAAKeJIGFuO:b8rd4e3) ([raw file](https://github.com/cockroachdb/cockroach/blob/21be6ffa77f9d774e3fe533c4a7b1557a8e4136f/pkg/geo/twkb/twkb.go#L291)):*
> ```Go
> 
> // putUvarint encodes a uint64 into buf and returns the number of bytes written.
> func (m *marshaller) putUvarint(x uint64) error {
> ```

is there a reason not to use `binary.PutUvarint`?
___
*[pkg/geo/twkb/twkb_test.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-MZOz_FK8fgqf36hMxYr:-MZOz_FK8fgqf36hMxYs:b-5kbks0) ([raw file](https://github.com/cockroachdb/cockroach/blob/21be6ffa77f9d774e3fe533c4a7b1557a8e4136f/pkg/geo/twkb/twkb_test.go#L32)):*
> ```Go
> 			desc:     "empty point",
> 			t:        geom.NewPointEmpty(geom.XY),
> 			expected: mustDecodeHex("0110"),
> ```

I guess eventually we would also have `ST_GeomFromTWKB` and we could test by pairing encode/decode.
Does geoserver not need `ST_GeomFromTWKB`?

Have you been validating this output by using some other tool for decoding?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64250)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/twkb/twkb.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-MZP1Gr1DhAAKeJIGFuN:-MZPDbFJ8IL033Oeom_N:b-7fm98i) ([raw file](https://github.com/cockroachdb/cockroach/blob/21be6ffa77f9d774e3fe533c4a7b1557a8e4136f/pkg/geo/twkb/twkb.go#L291)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a reason not to use `binary.PutUvarint`?
</blockquote></details>

i couldn't find a way of making it works with bytes.Buffer :'(
___
*[pkg/geo/twkb/twkb_test.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64250#-MZOz_FK8fgqf36hMxYr:-MZPDkcn6j1DuH6XC1N0:b-hm9q3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/21be6ffa77f9d774e3fe533c4a7b1557a8e4136f/pkg/geo/twkb/twkb_test.go#L32)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I guess eventually we would also have `ST_GeomFromTWKB` and we could test by pairing encode/decode.
Does geoserver not need `ST_GeomFromTWKB`?

Have you been validating this output by using some other tool for decoding?

</blockquote></details>

yeah, i use PostGIS, but the spec also includes a javascript thingy to validate.
but i assume if it works for postgis and we match output we're ok

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
