### PR TITLE
server: improve the tenant context

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #72638
(Reviewers: only review last commit)

Informs #58938

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72644#-:-MoF-EcnCIsa56d4tiBo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by knz** [comment]
TFYR!

bors r=RaduBerinde

**Comment by knz** [comment]
bors r-

linter failure

**Comment by knz** [comment]
bors r=RaduBerinde

**Pull request merged**
