### PR TITLE
roachpb: provide an explanation for Transaction.refreshed_timestamp

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Spencer, Nathan and I were wondering if this field needs to exist.
Is the suggested comment accurate/complete?

**Comment by andreimatei** [comment]
cc @nvanbenschoten

**Comment by spencerkimball** [comment]
Yes it absolutely needs to exist and the comment is correct.

**Review by nvb — APPROVED** [review]

**Pull request merged**
