### PR TITLE
server: remove this task that likes to deadlock

### PR DESCRIPTION
**Pull request by tamird**
This thing has given me enough grief that it's time for it to die. I can't figure why it's needed, but maybe CircleCI will produce a reason.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4813)

### CODE REVIEW

**Comment by tamird** [comment]
@petermattis do you think perhaps we could remove this custom ServeHTTP entirely and delegate to s.mux directly? I think this compression stuff made sense when we were doing RPC-over-HTTP, but no longer does.

**Comment by petermattis** [comment]
The compression stuff here is for HTTP requests. The RPC-over-HTTP compression always happened at the `rpc/codec` layer. I think HTTP compression is still desirable, though perhaps the stdlib will give it to us for free if we get rid of the snappy support.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBx3oqXG3fc7iXGqjec:86629504) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
I'm pretty sure this was necessary for orderly shut down. If we don't run a task here a server can receive a request and try to process it while it is being shut down.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-:-KBx4T0ocpKbP9WqL6dn:-730848185)*

**Comment by tamird** [comment]
Cool. I'll remove it in a separate PR.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBx6BOrsSf3Fwr1TeeD:605358955) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
Yeah, I think that's OK, though. All the RPC handlers are already stopper-instrumented, so the orderly shutdown happens there, and this is not necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-:-KBx6KsyNQh7JnUbL6W3:-1071731186)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBx73qRheNBtxvWg36l:1411056011) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
What about the HTTP handlers? I'm specifically worried about the JSON admin endpoints.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBx7a7QRG4VTXBcCYLJ:-1737535231) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
What's the worry? Someone shuts down a node with ctrl-c and the UI has a blip? Seems low risk to me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBx8LZ8QxXEIJXhrPss:-1984058638) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
The UI blip is not a concern. The concern is flaky tests. An admin endpoint which uses internal data structures (such as the store) cannot safely use those structures while being stopped. Perhaps we never run into these cases for admin endpoints, but we certainly did for RPC endpoints.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 419 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813#-KBx3oqWieN0xo-AiFDm:-KBxDdZvkv5LrnrZ1AWT:-611211841) ([raw file](https://github.com/cockroachdb/cockroach/blob/597e50c4789dd40e4ff28041a6bd14571e410b34/server/server.go#L419)):*
I've scheduled a bunch of builds of this SHA. Let's see if CircleCI turns anything up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4813)*

**Comment by tamird** [comment]
OK, 10 CI runs and no related failures. Can I merge this?

**Comment by tamird** [comment]
Verbal LGTM received, merging.

**Pull request merged**
