### PR TITLE
ui: refactor info tooltip usages into info tooltip component

### PR DESCRIPTION
**Pull request by oeph**
This change refactors the several usages of info tooltips into a dedicated component and uses this component in these places.

Solves #20921

### CODE REVIEW

**Comment by oeph** [comment]
CC @vilterp

**Comment by oeph** [comment]
I also refactored the usages in the following files as they were pretty similar - but we could alos revert this, if you think this change should not be done.

- pkg/ui/src/views/shared/components/summaryBar/index.tsx
- pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx

**Review by maryliag — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks good, just some minor changes.

Regarding the PR itself, there are some guidelines as the bot mention, so can you squash your commits? We typically have one commit per PR. And add a release note, if there isn't one you can always add `Release note: none`.
Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64555#-:-M_S5p1m7gDbOU795-B8:blvqag7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @oeph)

___
*[pkg/ui/src/components/infoTooltip/infoTooltip.tsx, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64555#-M_S4mm0DYjV6OhN29Dk:-M_S4mm0DYjV6OhN29Dl:b4jj9bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31680b2ef7dd89db6ed56efcbc90451ba8044/pkg/ui/src/components/infoTooltip/infoTooltip.tsx#L21)):*
> ```XML
>   return (
>     <div className="info-tooltip__tooltip">
>       <ToolTipWrapper text={children}>
> ```

We don't want to mix the props `children` and `text` from `ToolTipWrapperProps`. Since the value here is for `text` is better to pass that specifically as a prop, otherwise we might mix up with `children` ( which we might have several or none). So something like:

```export const InfoTooltip = (props: { text: React.ReactNode }) => {
  return (
    <div className="info-tooltip__tooltip">
      <ToolTipWrapper text={props.text}>
      ...
```
___
*[pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64555#-M_S51VCEqKM_JkhcGLF:-M_S51VCEqKM_JkhcGLG:b-d7o493) ([raw file](https://github.com/cockroachdb/cockroach/blob/09c31680b2ef7dd89db6ed56efcbc90451ba8044/pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx#L128)):*
> ```XML
>         <div className="data-distribution__zone-config-sidebar">
>           <h2 className="base-heading">
>             Zone Configs <InfoTooltip>{ZONE_CONFIG_TEXT}</InfoTooltip>
> ```

And with the change from above, this line would change to
`Zone Configs <InfoTooltip text={ZONE_CONFIG_TEXT}/>`

Same changes for all other usages

**Comment by oeph** [comment]
@maryliag thank you for your suggestions - I will change the PR

**Review by maryliag — CHANGES_REQUESTED** [review]
Changes look good. 
The only thing left is updating your commit message to include the package you made the changes. You can do `git commit --amend` and change the `Add InfoTooltip component` message to `ui: add InfoTooltip component` and then I can approve and merge :) 

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64555#-:-M_VwOhI2XvAAmvbJNVi:bmdo4rn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @oeph)

**Comment by oeph** [comment]
@maryliag aah, sure - missed this

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64555#-:-M_W9Mg83u3_t95ls9ey:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @oeph)

**Pull request merged**
