### PR TITLE
storage: introduce LockTableIterator

### LINKED ISSUE #109644: storage: ignore shared and exclusive locks in intentInterleavingIterator
As part of https://github.com/cockroachdb/cockroach/issues/100193, we'll want the `intentInterleavingIterator` to ignore Shared and Exclusive locks.

Jira issue: CRDB-31028

Epic CRDB-26544

### PR DESCRIPTION
**Pull request by nvb**
Informs #100193.
Closes #109644.
Closes #109570.

This PR introduces a new form of iterator, the `LockTableIterator`, which is an `EngineIterator` that iterates over locks in the lock table keyspace. It performs no translation of input or output keys or values, so it is used like a normal `EngineIterator`, with the limitation that it can only be used to iterate over the lock table keyspace.

The benefit of using a `LockTableIterator` is that it performs filtering of the locks in the lock table, only returning locks that match the configured filtering criteria and transparently skipping past locks that do not. The filtering criteria is expressed as a logical disjunction of two configuration parameters, at least one of which must be set:

- **MatchTxnID**: if set, the iterator return locks held by this transaction.

- **MatchMinStr**: if set, the iterator returns locks held by any transaction with this strength or stronger.

Expressed abstractly as a SQL query, the filtering criteria is:

```sql
SELECT * FROM lock_table WHERE (MatchTxnID  != 0 AND txn_id = MatchTxnID)
                            OR (MatchMinStr != 0 AND strength >= MatchMinStr)
```

Pushing this filtering logic into the iterator is a convenience for its users. It also allows the iterator to use its knowledge of the lock table keyspace structure to efficiently skip past locks that do not match the filtering criteria. It does this by seeking past many ignored locks when appropriate to avoid cases of O(ignored_locks) work, instead performing at most O(matching_locks + locked_keys) work.

A common case where this matters is with shared locks. If the iterator is configured to ignore shared locks, a single key with a large number of shared locks can be skipped over with a single seek. Avoiding this unnecessary work is essential to avoiding quadratic behavior during shared lock acquisition and release.

The LockTableIterator will be used by `intentInterleavingIter`, `MVCCCheckLock`, `MVCCAcquireLock`, `mvccPutUsingIter`, `MVCCResolveWriteIntent`, `MVCCResolveWriteIntentRange`, `computeMinIntentTimestamp`, `SeparatedIntentScanner`, and more.

----

The PR introduces the abstraction of a `LockTableIterator`, but doesn't yet implement the logic to avoid O(ignored_locks) work in the iterator. This is left as a TODO which will be addressed in the next few weeks, but doesn't need to block this PR or use of the `LockTableIterator`.

The PR then copies over the 2 commits from #109570, which ignore non-intent locks in `intentInterleavingIter`. This could have been done in a separate PR, but it felt useful to demonstrate how much simpler and cleaner #109644 gets with this new abstraction. I can extract it back out if reviewers would like.

----

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
I didn't look at the tests, but interface and integration with `intentIterleavingIter` looks good.

> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-:-Ne3coez0oecwNWpixU4:b-kf99mo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/storage/lock_table_iterator.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3cDwAD4SLyxzWGX0s:-Ne3cDwAD4SLyxzWGX0t:b-6ctgrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L61)):*
> ```Go
> // and release.
> type LockTableIterator struct {
> 	iter EngineIterator
> ```

There was some commentary in `intentInterleavingIter` about avoiding dynamic dispatch and using `*pebbleIterator`. Consider doing that here.
___
*[`pkg/storage/lock_table_iterator.go` line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3WRWGE3Kx82vO9JzC:-Ne3WRWGE3Kx82vO9JzD:b-nblspa) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L139)):*
> ```Go
> // SeekEngineKeyGE implements the EngineIterator interface.
> func (i *LockTableIterator) SeekEngineKeyGE(key EngineKey) (valid bool, err error) {
> 	if err := checkLockTableKey(key.Key); err != nil {
> ```

Is `checkLockTableKey` cheap enough, or should be hidden behind `invariants.Enabled`?
___
*[`pkg/storage/lock_table_iterator.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3aE-D-d3bLIje9ivq:-Ne3aE-D-d3bLIje9ivr:b-z11v61) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L252)):*
> ```Go
> ) (state pebble.IterValidityState, err error) {
> 	for {
> 		engineKey, err := i.iter.UnsafeEngineKey()
> ```

nit: can this use `i.LockTableKeyVersion()`

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110319)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @sumeerbhola)

___
*[`pkg/storage/lock_table_iterator.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3cDwAD4SLyxzWGX0s:-Ne3jbI73IxdYxOWCqku:b4ehirz) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L61)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

There was some commentary in `intentInterleavingIter` about avoiding dynamic dispatch and using `*pebbleIterator`. Consider doing that here.
</blockquote></details>

I hoped to do that, but unfortunately, this won't always be a `*pebbleIterator`. There will be cases where it's a `spanset.EngineIterator`, when constructed from a `spanset.spanSetReader`. We don't have this problem in `newIntentInterleavingIterator` because iterators are constructed from a `Reader` below `spanset.spanSetReader` in the `Reader.NewMVCCIterator` hierarchy.

Dynamic dispatch on the `intentIter` (as opposed to the mvcc `iter`) doesn't seem to make much of a difference on the benchmarks we care about, though:
```
➜ benchstat full_static.txt full_dynamic.txt
name                                                                old time/op   new time/op   delta
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10   25.8µs ± 3%   26.2µs ± 3%  +1.72%  (p=0.000 n=49+44)

name                                                                old speed     new speed     delta
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10  248MB/s ± 3%  244MB/s ± 3%  -1.76%  (p=0.000 n=49+45)

➜ benchstat full_static.txt static_mvcc_dynamic_intent.txt
name                                                                old time/op   new time/op   delta
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10   25.8µs ± 3%   25.8µs ± 2%   ~     (p=0.163 n=49+45)

name                                                                old speed     new speed     delta
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-10  248MB/s ± 3%  248MB/s ± 2%   ~     (p=0.163 n=49+45)
```
That's because these benchmarks we were concerned about when making this optimization don't even write any intents. However, I also don't see a difference with `IntentInterleavingSeekGEAndIter/separated=true/version=1/intentStride=1/keyLen=10/seekStride=1`, which should exercise the `intentIter` more than any other benchmark we have. So I'll leave this as is.
___
*[`pkg/storage/lock_table_iterator.go` line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3WRWGE3Kx82vO9JzC:-Ne42gMhBrYnFd2sUdUO:br3j0i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L139)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is `checkLockTableKey` cheap enough, or should be hidden behind `invariants.Enabled`?
</blockquote></details>

It's inlined all the way down through the call to `bytes.HasPrefix` and the underlying `bytes.Equal` of two bytes, so it's just a few branches that should play well with a branch predictor.
___
*[`pkg/storage/lock_table_iterator.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne3aE-D-d3bLIje9ivq:-Ne44QckA_1SZBQSCXX6:b-giyf9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L252)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can this use `i.LockTableKeyVersion()`
</blockquote></details>

It can right now, but to address the TODO below, I'll need access to the `EngineKey.Key`. I'll leave this as is to avoid the churn when addressing that TODO.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 9 files at r1, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-:-Ne8wqoY2stY3qgLxmKT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/storage/lock_table_iterator_test.go` line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne8mgiv6kTCd2WLqwKl:-Ne8mgiv6kTCd2WLqwKm:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1565fb06df74084348296ad4afdeed182a78cf78/pkg/storage/lock_table_iterator_test.go#L580)):*
> ```Go
> // TestLockTableIteratorEquivalence is a quickcheck test that verifies that a
> // LockTableIterator is equivalent to a raw engine iterator with non-matching
> // lock keys filtered before writing to the engine.
> ```

nice

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-:-NeAAoGy7vGLU73SaGjR:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/storage/lock_table_iterator.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-NeA8kCU4rTbrJ9_xQR3:-NeA8kCU4rTbrJ9_xQR4:bxbdudr) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L332)):*
> ```Go
> // LockTableKeyVersion returns the strength and txn ID from the version of the
> // current key.
> func (i *LockTableIterator) LockTableKeyVersion() (lock.Strength, uuid.UUID, error) {
> ```

My IDE is telling me this isn't used anywhere -- is that because one of the subsequent commits makes use of this?
___
*[`pkg/storage/lock_table_iterator_test.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne9mMZZ8RY4hx9LyqmS:-Ne9mMZZ8RY4hx9LyqmT:bvc98vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator_test.go#L160)):*
> ```Go
> }
> 
> // TestLockTableIterator is a datadriven test consisting of two commands:
> ```

nit: should we move this test to the top of the file? 
___
*[`pkg/storage/lock_table_iterator_test.go` line 580 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne8mgiv6kTCd2WLqwKl:-NeA5DGj5TvLDriehQkx:b2ngthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1565fb06df74084348296ad4afdeed182a78cf78/pkg/storage/lock_table_iterator_test.go#L580)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice
</blockquote></details>

+1

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r=sumeerbhola,arulajmani

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-:-NeEWMm1ChO4zEZVzJA3:b-uajvkh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @arulajmani and @sumeerbhola)

___
*[`pkg/storage/lock_table_iterator.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-NeA8kCU4rTbrJ9_xQR3:-NeEWTCG3dqWjS5MMkIW:buwqpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator.go#L332)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

My IDE is telling me this isn't used anywhere -- is that because one of the subsequent commits makes use of this?
</blockquote></details>

Yes, a few of the subsequent PRs make use of this. It's not tripping up the linter, so I'll just leave it as is for now.
___
*[`pkg/storage/lock_table_iterator_test.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110319#-Ne9mMZZ8RY4hx9LyqmS:-NeEWaAs478BwH9o613t:bolad6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/94e3c35b5ac5a0f87b83745f7684c6fcd1e25237/pkg/storage/lock_table_iterator_test.go#L160)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: should we move this test to the top of the file?
</blockquote></details>

I was following the example set by `TestIntentInterleavingIter` in `intent_interleaving_iter_test.go`. Since this is the only comment, I'll leave as is to avoid a round of CI.

**Pull request merged**
