### PR TITLE
storage: re-introduce dual buffer for iterator bounds

### PR DESCRIPTION
**Pull request by erikgrinaker**
For the `mvcc-range-tombstones` branch. Undoes a change in #79291 and #79744. Will be squashed into the original commit once merged.

---

**storage: re-introduce dual buffer for iterator bounds**

This is necessary to avoid mutating the bounds in use by
`pebble.Iterator`, which can interfere with seek optimizations.

Release note: None

**storage: simplify `pebbleIterator` options comparisons**

Since we now use dual buffers for bounds encoding, we can fully generate
the new `pebble.IterOptions` during `setOptions()` and compare them
directly with the existing options, which simplifies the code.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
Performance diff when writing to a batch (reusing iterators) is negligible, and within error margins (c.f. benchmarks in #79291):

```
name                                        old time/op    new time/op    delta
MVCCGet_Pebble/versions=1/valueSize=8-24      2.60µs ± 4%    2.61µs ± 1%    ~     (p=0.132 n=19+19)
MVCCGet_Pebble/versions=10/valueSize=8-24     3.82µs ± 1%    3.88µs ± 1%  +1.54%  (p=0.000 n=20+19)
MVCCGet_Pebble/versions=100/valueSize=8-24    9.47µs ± 6%    9.59µs ± 3%    ~     (p=0.123 n=19+19)
```

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jbowens, and @nicktrav)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79993#-N-x7yHw6Yp6lW_IxVQF):*
Can you look into why TestPebbleIterBoundSliceStabilityAndNoop did not fail?
Is it because it was removed since SetBounds is no more? We need a test that would have caught this bug.
___
*[pkg/storage/pebble_iterator.go, line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79993#-N-x9D2vDA9cj5ju46cc:-N-x9D2vDA9cj5ju46cd:b-5kq0r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/492183c85c349a3b9a1a948c44d812954c1f5907/pkg/storage/pebble_iterator.go#L214)):*
> ```Go
> 	// require either Prefix, UpperBound, or LowerBound to be set, so one of these
> 	// won't match the zero value of a new iterator.
> 	optsChanged := opts.Prefix != p.prefix ||
> ```

I didn't spot a new test for this noop optimization. If there isn't one, please add.

From past experience, this is the kind of thing that results in extremely long and painful roachtest failure investigations.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nicktrav, and @sumeerbhola)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79993#-N-x7yHw6Yp6lW_IxVQF):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you look into why TestPebbleIterBoundSliceStabilityAndNoop did not fail?
Is it because it was removed since SetBounds is no more? We need a test that would have caught this bug.
</blockquote></details>

Ah, yes, it was removed. Sloppy of me not to look closer here.
___
*[pkg/storage/pebble_iterator.go, line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79993#-N-x9D2vDA9cj5ju46cc:-N0GQwCPC9Osg6RL6cbP:badhj9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/492183c85c349a3b9a1a948c44d812954c1f5907/pkg/storage/pebble_iterator.go#L214)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't spot a new test for this noop optimization. If there isn't one, please add.

From past experience, this is the kind of thing that results in extremely long and painful roachtest failure investigations.
</blockquote></details>

Let's see where we land on https://github.com/cockroachdb/pebble/pull/1640 first. I think it'd be beneficial to move this into Pebble, since it'd allow for more fine-grained optimization and less coupling.

**Comment by erikgrinaker** [comment]
Superseded by #81242.

**Pull request closed without merging**
