### PR TITLE
sql: add support for drop type, drop schema, drop database in new schema changer

### LINKED ISSUE #64684: sql: implement DROP DATABASE CASCADE in new schema changer
Prereqs:
- [ ] https://github.com/cockroachdb/cockroach/issues/64683
- [ ] https://github.com/cockroachdb/cockroach/issues/64682
- [ ] https://github.com/cockroachdb/cockroach/issues/64681
- [ ] https://github.com/cockroachdb/cockroach/issues/64680
- [ ] https://github.com/cockroachdb/cockroach/issues/64679

### PR DESCRIPTION
**Pull request by fqazi**
Previously drop type, drop schema, drop database were only implemented in the old schema changer using imperative logic. This pull request adds support for all 3 in the schema changer and additionally adds plan-based testing for drop table as well.

Fixes: #64684, #64683, #64682, #64681

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
What would happen if we tried returning the unsupported error for `ADD COLUMN` and then tried running all of the logic tests with this on in the "on" mode (as opposed to "unsafe_always"). I have a feeling that it would point to interesting things. 

It's cool to see this stuff coming together. 

> Reviewed 17 of 17 files at r1, 10 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-:-MbssHPl2QBuWsFS4102:bxis17h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 547 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsrgR-5lLoUPFWmNLF:-MbsrgR-5lLoUPFWmNLG:br17o98) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L547)):*
> ```
> 
> statement ok
> CREATE SEQUENCE db1.public.SQ1
> ```

nit: no need to capitalize
___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsrieg56x14vQHUxZ1:-MbsrfmV8_JYBKln1XQG:br17o98) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L550)):*
> ```
> 
> statement ok
> CREATE SEQUENCE db1.sc1.SQ1
> ```

nit: no need to capitalize
___
*[pkg/sql/schemachanger/scbuild/database.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuC760ZtWiZyN0KEV:-MbsuC760ZtWiZyN0KEW:b-q9qja7) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/database.go#L49)):*
> ```Go
> 		if err != nil {
> 			panic(err)
> 		}
> ```

How does this deal with `public` and the temporary schemas? It'd be good to at least comment. I think it works but I'm not totally clear on how. 
___
*[pkg/sql/schemachanger/scbuild/table.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsqPIa4m4EhBNQG42A:-MbsqPIa4m4EhBNQG42B:b-3fwxt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scbuild/table.go#L162)):*
> ```Go
> 			panic(err)
> 		}
> 		b.addNode(scpb.Target_ADD, &scpb.TypeReference{
> ```

For the type back-references, do you add them even if the table already uses the type? Can you add commentary about that topic? If so, this also gets tricky because you'll need to look at whether there was a different clause to drop a column that might complicate the situation. 
___
*[pkg/sql/schemachanger/scbuild/table.go, line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuUug7X0vuWBhveHV:-MbsuUuhAaUvyN3Gz3oH:b-xk045a) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/table.go#L649)):*
> ```Go
> 		// Setup logic to clean up the default expression,
> 		// only if sequences are depending on it.
> 		if col.NumUsesSequences() > 0 {
> ```

Would it be more consistent if we dropped the default expression always? 

Another, related question is how does this handle types which get used in the default expression. I think that's a thing. 
___
*[pkg/sql/schemachanger/scbuild/type.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsueBl9Urz9-EukPR3:-MbsueBl9Urz9-EukPR4:b-qne6lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/type.go#L126)):*
> ```Go
> 			continue
> 		}
> 		b.dropTypeDesc(ctx, typeDesc, n.DropBehavior, false)
> ```

nit: comment the name of this boolean for readability. 
___
*[pkg/sql/schemachanger/scbuild/testdata/drop_schema, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuvhnDlbd8h768MT8:-MbsuvhnDlbd8h768MT9:bbszt8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/testdata/drop_schema#L32)):*
> ```
> CREATE TYPE sc1.typ AS ENUM('a')
> ----
> ```

It'd be interesting to observe the cascades which cross schemas. 
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsqt7m6ammwJLwpO9m:-Mbsqt7m6ammwJLwpO9n:b-viz046) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L163)):*
> ```Go
> 		return err
> 	}
> 	mutDesc.AddReferencingDescriptorID(op.DescID)
> ```

Do we want to make this idempotent or should it check if there's already a back ref? I feel like an assertion error would be nice.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsvX1034iIMhV0gDl_:-MbsvX1034iIMhV0gDla:b-t3a5ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L231)):*
> ```Go
> }
> 
> func (m *visitor) DrainDescriptorName(ctx context.Context, op scop.DrainDescriptorName) error {
> ```

I wonder if we should make these names also be an element. That might make sense with renames. 
___
*[pkg/sql/schemachanger/scpb/elements.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsr5cf3c2SUzrvsHAG:-Mbsr5cf3c2SUzrvsHAH:bnjck69) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scpb/elements.go#L45)):*
> ```Go
> }
> 
> // ElementDescriptorSet represents all the descriptors touched by an element
> ```

This is unused in this commit, will revisit.
___
*[pkg/sql/schemachanger/scplan/rules.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsrF7o1k-r9Bep6ZML:-MbsrF7o1k-r9Bep6ZMM:b-1bc8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scplan/rules.go#L249)):*
> ```Go
> 	},
> 	(*scpb.Type)(nil): {
> 		deps: nil,
> ```

Are we going to need some deps here? We'll want to test dropping the type in the same transaction that drops its usage and make sure that we don't drop the type until the column is all the way absent (I'd think). This is one of those things that should be in the "uncancelable" part of the job.
___
*[pkg/sql/schemachanger/scplan/rules.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsw8mx0oxltGFwCd_m:-Mbsw8mx0oxltGFwCd_n:b44vvww) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scplan/rules.go#L265)):*
> ```Go
> 					op: func(this *scpb.Database) []scop.Op {
> 						ops := []scop.Op{
> 							&scop.CreateGcJobForDescriptor{
> ```

One thing to be aware of is that the GC job supports dropping multiple tables at a time. We don't have to use that, but we might eventually want to. We should track that somewhere along with the fact that that GC job thing does not support dropping a schema at a time. I think what I'm getting at is that ideally we'd coalesce all of the drops of a transaction into a single GC job. 
___
*[pkg/sql/schemachanger/scplan/testdata/drop_database, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbswMQVCpk8nlbydD91:-MbswMQVCpk8nlbydD92:bgxuznr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63b75e453ea33ef07d229bbfd07a283c0c67f93/pkg/sql/schemachanger/scplan/testdata/drop_database#L155)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>   *scop.CreateGcJobForDescriptor
>     DescID: 53
>   *scop.CreateGcJobForDescriptor
>     DescID: 52
>   *scop.DrainDescriptorName
>     TableID: 53
>   *scop.DrainDescriptorName
>     TableID: 52
> ```
</details>

Having these lag a stage doesn't seem right to me.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/database.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuC760ZtWiZyN0KEV:-Mbw2IYUCeZYI3g8FE8H:blkmvi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/database.go#L49)):*
> t have to use that, but we might eventually want to. We should track that some
Added a comment to clarify:
		// For public and temporary schemas the drop logic
		// will only drop the underlying objects and return
		// if that no drop schema node was added (nodeAdded).
		// The schemaDroppedIDs list will have the list of
		// dependent objects, which that database will add
		// direct dependencies on.
___
*[pkg/sql/schemachanger/scbuild/table.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsqPIa4m4EhBNQG42A:-Mbw57za2QAVVl9OaLNL:b-g6t6jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scbuild/table.go#L162)):*
> at topic? If so, this also gets tricky because you'll need to look at whether th
Good point, I'll change this to check before adding

		// Only add a type reference node only if there isn't
		// any existing reference inside this table. This makes
		// it easier to handle drop columns and other operations,
		// since those can for example only remove nodes.
___
*[pkg/sql/schemachanger/scbuild/table.go, line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuUug7X0vuWBhveHV:-Mbw7814DajIzpezkffU:b-h34sq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/table.go#L649)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would it be more consistent if we dropped the default expression always? 

Another, related question is how does this handle types which get used in the default expression. I think that's a thing. 
</blockquote></details>

I don't see any special handling inside ALTER COLUMN? I'm guessing it's because the column's type would be the same, or am I crazy?  I'll update this to always drop default expressions, it should be harmless in other cases.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsqt7m6ammwJLwpO9m:-MbwCS1b6z82mnFyH_KN:b-yacvfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L163)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do we want to make this idempotent or should it check if there's already a back ref? I feel like an assertion error would be nice.
</blockquote></details>

Done. Added an assertion
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsvX1034iIMhV0gDl_:-MbwSc1D7-I4va9HZZpz:b-u4e2nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if we should make these names also be an element. That might make sense with renames. 
</blockquote></details>

Dependency wise this would get interesting, I guess the drop only kicks in once the object has been dropped?
___
*[pkg/sql/schemachanger/scpb/elements.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsr5cf3c2SUzrvsHAG:-MbwBiL2DTaZTyJi0CpG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7813a91c6df75d04b12815839680f2782e86b135/pkg/sql/schemachanger/scpb/elements.go#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is unused in this commit, will revisit.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scplan/rules.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsw8mx0oxltGFwCd_m:-MbwSM6X1FCC9E2HgfHD:b-k4h875) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scplan/rules.go#L265)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One thing to be aware of is that the GC job supports dropping multiple tables at a time. We don't have to use that, but we might eventually want to. We should track that somewhere along with the fact that that GC job thing does not support dropping a schema at a time. I think what I'm getting at is that ideally we'd coalesce all of the drops of a transaction into a single GC job. 
</blockquote></details>

Done. I think longer-term it would be nice to link back to the original operation / statement, since right now I'm only tagging the job as drops for the set of descriptor ID's.
___
*[pkg/sql/schemachanger/scplan/testdata/drop_database, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbswMQVCpk8nlbydD91:-MbwUSB7CUMNThoFKj6k:bjg4xcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63b75e453ea33ef07d229bbfd07a283c0c67f93/pkg/sql/schemachanger/scplan/testdata/drop_database#L155)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
>   *scop.CreateGcJobForDescriptor
>     DescID: 53
>   *scop.CreateGcJobForDescriptor
>     DescID: 52
>   *scop.DrainDescriptorName
>     TableID: 53
>   *scop.DrainDescriptorName
>     TableID: 52
> ```
Having these lag a stage doesn't seem right to me. 
</blockquote></details>

It's because of operator randomization. If we had an implicit ordering of some sort it would help. But, we have to add one more stage because we can't drop the database/schema before everything else is gone.

So, maybe that is something we need to look into next? The dependency graph is sort of enforcing that right now since require the other objects are absent first.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scbuild/database.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuC760ZtWiZyN0KEV:-McA4fqf2irCaxa51x3g:b-slhgux) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/database.go#L49)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

> t have to use that, but we might eventually want to. We should track that some
Added a comment to clarify:
		// For public and temporary schemas the drop logic
		// will only drop the underlying objects and return
		// if that no drop schema node was added (nodeAdded).
		// The schemaDroppedIDs list will have the list of
		// dependent objects, which that database will add
		// direct dependencies on.
</blockquote></details>

Missing a push?
___
*[pkg/sql/schemachanger/scbuild/table.go, line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuUug7X0vuWBhveHV:-McA3Lxs1wadDsMFYAR3:b-o4uh4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/table.go#L649)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I don't see any special handling inside ALTER COLUMN? I'm guessing it's because the column's type would be the same, or am I crazy?  I'll update this to always drop default expressions, it should be harmless in other cases.
</blockquote></details>

Seems like it happens somewhere:

```
root@localhost:26257/defaultdb> CREATE TYPE typ AS ENUM ('a');
CREATE TYPE

Time: 139ms

root@localhost:26257/defaultdb> CREATE TABLE t (i INT PRIMARY KEY, j STRING AS ('a'::typ::string) STORED);
ERROR: relation "defaultdb.public.t" already exists
SQLSTATE: 42P07
root@localhost:26257/defaultdb> DROP TABLE t;
DROP TABLE

Time: 481ms

root@localhost:26257/defaultdb> CREATE TABLE t (i INT PRIMARY KEY, j STRING AS ('a'::typ::string) STORED);
CREATE TABLE

Time: 523ms

root@localhost:26257/defaultdb> DROP TYPE typ;
ERROR: cannot drop type "typ" because other objects ([defaultdb.public.t]) still depend on it
SQLSTATE: 2BP01

root@localhost:26257/defaultdb> SET sql_safe_updates = false;
SET

Time: 0ms

root@localhost:26257/defaultdb> ALTER TABLE t DROP COLUMN j;
ALTER TABLE

Time: 1.274s

root@localhost:26257/defaultdb> DROP TYPE typ;
DROP TYPE

Time: 693ms

```
___
*[pkg/sql/schemachanger/scplan/rules.go, line 265 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-Mbsw8mx0oxltGFwCd_m:-McA4KnJBTuDuUE0Fdz8:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scplan/rules.go#L265)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done. I think longer-term it would be nice to link back to the original operation / statement, since right now I'm only tagging the job as drops for the set of descriptor ID's.
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/schemachanger/scplan/testdata/drop_database, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbswMQVCpk8nlbydD91:-McA4PVQ4eD4HwdraU_7:b-yqsnd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63b75e453ea33ef07d229bbfd07a283c0c67f93/pkg/sql/schemachanger/scplan/testdata/drop_database#L155)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

It's because of operator randomization. If we had an implicit ordering of some sort it would help. But, we have to add one more stage because we can't drop the database/schema before everything else is gone.

So, maybe that is something we need to look into next? The dependency graph is sort of enforcing that right now since require the other objects are absent first.
</blockquote></details>

I think this warrants an issue to track the work. Can you file one?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/database.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuC760ZtWiZyN0KEV:-McAPUZOAyGIyMGghFAS:bpm8bim) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/database.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Missing a push?
</blockquote></details>

Yes forgot to push.
___
*[pkg/sql/schemachanger/scbuild/testdata/drop_schema, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsuvhnDlbd8h768MT8:-Mc9wljgAiPdjDW4xvDo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scbuild/testdata/drop_schema#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It'd be interesting to observe the cascades which cross schemas. 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scplan/testdata/drop_database, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbswMQVCpk8nlbydD91:-McAPROFEuhX0W6T8dwR:boewcn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63b75e453ea33ef07d229bbfd07a283c0c67f93/pkg/sql/schemachanger/scplan/testdata/drop_database#L155)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this warrants an issue to track the work. Can you file one? 
</blockquote></details>

I'll create a new one

**Review by ajwerner — COMMENTED** [review]
This is looking good to me. CI is a bit unhappy. 

What does the testing coverage look like over the builder? The builder sure is getting complex. We knew that was coming. I don't think there's anything fundamentally wrong with it. Let's keep an eye on patterns which might be coming up and opportunities to modularize pieces of it. I don't have any bright ideas at the moment. For now I think there's value is scrutinizing coverage profiles, making sure we're exercising the code we have, and being assertion-happy to make sure that we aren't adding too many subtle, implicit assumptions.

> Reviewed 6 of 16 files at r6, 5 of 13 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-:-McKCzsO832kQtD0A4lZ:b-2tajqm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/logictest/testdata/logic_test/new_schema_changer, line 538 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McK9Utk3BA7KXmVAWPg:-McK9Utk3BA7KXmVAWPh:bp92i4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L538)):*
> ```
> DROP TYPE typ8
> 
> # DROP TYPE in a singe transaction
> ```

Should we be using `subtest`? 
___
*[pkg/sql/schemachanger/scbuild/database.go, line 66 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKA6cL76lstoO6XHo7:-McKA6cL76lstoO6XHo8:b4jy6yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/database.go#L66)):*
> ```Go
> 		// If no schema exists to depend on, then depend on dropped IDs
> 		if !nodeAdded {
> 			dropIDs = append(dropIDs, schemaDroppedIDs...)
> ```

Is it possible to have duplicates here? Would it be a bug if we did? If so, how would you feel about using `catalog.DescriptorIDSet` and then ensuring that when you union the sets here that the intersection is empty?  Adding `Intersection()` or `Intersects()` to `catalog.DescriptorIDSet` should be trivial. 
___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 59 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKAyVJ2YNZvvf5yYfK:-McKAyVKBWOn3In6ASX0:b-9rn0d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L59)):*
> ```Go
> }
> 
> func (b *buildContext) removeColumnTypeBackRefs(table catalog.TableDescriptor, id descpb.ColumnID) {
> ```

This deserves some commentary. 
___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 68 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKB4kHACnhbUp6SkDy:-McKB4kI9zQUwNMbHgV9:b-okmhm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L68)):*
> ```Go
> 	// Get all available type references and create nodes
> 	// for dropping these type references.
> 	for _, col := range table.AllColumns() {
> ```

What about computed columns? 
___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 68 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKBArI1y52-oYLLl6L:-McKBArI1y52-oYLLl6M:b-r9vz6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L68)):*
> ```Go
> 	// Get all available type references and create nodes
> 	// for dropping these type references.
> 	for _, col := range table.AllColumns() {
> ```

Can you add a TODO to deal with the case where we've added the column in the current statement? I think that's where this stuff starts to come off the rails.

```
CREATE TYPE typ AS ENUM ('a');
CREATE TABLE t (a typ);
ALTER TABLE t DROP COLUMN a, ADD COLUMN b typ;
```
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsvX1034iIMhV0gDl_:-McKCUcB0yI0vYM3VYAG:bhm2tw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L231)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Dependency wise this would get interesting, I guess the drop only kicks in once the object has been dropped?
</blockquote></details>

For the drop that's right but for the rename it's just got to be after the new name is public. 
___
*[pkg/sql/schemachanger/scplan/testdata/drop_database, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbswMQVCpk8nlbydD91:-McKCyxwAH16WQ1aMZ0D:b-l52ode) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63b75e453ea33ef07d229bbfd07a283c0c67f93/pkg/sql/schemachanger/scplan/testdata/drop_database#L155)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I'll create a new one
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/66437

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 59 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKAyVJ2YNZvvf5yYfK:-McLh2dU0gMxDY-oYZpg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This deserves some commentary. 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 68 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKB4kHACnhbUp6SkDy:-McLh3IL-BbZWMCtYoo5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What about computed columns? 
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/relation_common.go, line 68 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-McKBArI1y52-oYLLl6L:-McLh3tw30fp25Fhndt-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17f166db44811107910cd5d3e81e0ccec0f3ce3c/pkg/sql/schemachanger/scbuild/relation_common.go#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you add a TODO to deal with the case where we've added the column in the current statement? I think that's where this stuff starts to come off the rails.

```
CREATE TYPE typ AS ENUM ('a');
CREATE TABLE t (a typ);
ALTER TABLE t DROP COLUMN a, ADD COLUMN b typ;
```
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-MbsvX1034iIMhV0gDl_:-McLh6ncD465nirw49hT:b-ej1fcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/30e75a8e67399ba7e7a7841011be66e672ae766b/pkg/sql/schemachanger/scexec/scmutationexec/scmutationexec.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For the drop that's right but for the rename it's just got to be after the new name is public. 
</blockquote></details>

I'll add this in a future PR with the CREATE stuff

**Review by ajwerner — APPROVED** [review]
Will need a rebase but :lgtm: 

> Reviewed 11 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66099#-:-McUFkY27UzS2hgsGzes:b-sb0jl3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by fqazi** [comment]
bors r=ajwerner

**Comment by fqazi** [comment]
bors r=ajwerner

**Comment by fqazi** [comment]
bors cancel

**Comment by fqazi** [comment]
bors r=ajwerner

**Pull request merged**
