### PR TITLE
oidc: make redirect path after login configurable 

### LINKED ISSUE #111242: oidc: make success redirection configurable
**Is your feature request related to a problem? Please describe.**
Currently, when hosting CRDB HTTP behind a load balancer and using a subpath, it's not possible to get the OIDC login flow to end up at a path of your choice. This can result in odd behavior when a user logs in via OIDC but ends up at a different URL than their DB.

**Describe the solution you'd like**
A cluster setting which allows for configuration of the success redirect path. The default is `/` which is currently hardcoded.

Jira issue: CRDB-31833

### PR DESCRIPTION
**Pull request by dhartunian**
This commit adds a new cluster setting called `server.http.base_path` that's used to redirect a user logging in with OIDC SSO.

Future work will adjust other routing across the DB based on this cluster setting.

Resolves: #111242
Epic: None

Release note (ops change, ui change): A new cluster setting `server.http.base_path` is introduced that currently controls the redirection of the browser after successful login with OIDC SSO. It is expected that most customers should *not* have to adjust this. This is helpful in cases where a customer is running CRDB behind a load- balancer or proxy that serves CRDB under a subpath such as `https:// <hostname>/crdb/ `. In those cases it's necessary for the browser to redirect to `/ crdb` after login instead of `/` which has always been the hardcoded default.

### CODE REVIEW

**Review by Santamaura — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by Santamaura** [comment]
I think you might need a `generate`

**Review by knz — APPROVED** [review]
Nice.

I do recommend linking this issue to an epic. It's significant.

**Review by knz — COMMENTED** [review]
Would you also mind adding a unit test thanks.

**Comment by dhartunian** [comment]
Testing this code directly is a bit tricky because we have no existing tests for the `/callback` endpoint and no ability to reach into the testServer to inspect the oidc config.

I have a WIP commit that reworks the tests to use mocked interfaces for all the OIDC stuff but it touches a lot of the production code. Given that this needs to go into a backport I'm going to merge + backport as-is and see if I can add some tests in the 22.2 version directly (we've seen a lot of churn in the testServer interfaces for multi-tenant so that would need to be changed for the backport anyway). I'll merge a separate test update as part of addressing #111185 which I have in progress.

I'm going to merge this now in order to get a custom build into the customer's hands.

**Comment by knz** [comment]
sounds good!

**Comment by dhartunian** [comment]
bors r=knz,santamaura

**Pull request merged**
