### PR TITLE
ui: use build version for docs links

### LINKED ISSUE #19024: ui: current version in docs links is hardcoded
As of #18986, we're creating links to the docs using the helper `util/docs.ts` to make sure they point to the version of the docs for the version of the cluster.  However, the version number is hardcoded there.  There's already a TODO item there, but since this is something we definitely don't want to get lost, I'm also making an issue to keep track of it.

We should figure out a way to DRY this so it's not hardcoded (we can get it from `pkg/base/docs`).  Until then, for every release we'll need to update the version string in the client.

### PR DESCRIPTION
**Pull request by couchand**
The first commit is reviewed separately here: #25823

#### ui: extract dataFromServer global from login file

Since the dataFromServer will hold more than just login state, move it out to a
new file.

Release note: None

#### ui: use build version for docs links

Previously, the current version was hard-coded into the docs links,
requiring manual effort to keep in sync with the released version
of the binary.  This change interpolates the `build.VersionPrefix()`
instead, so that it's always correct.

Fixes: #19024
Release note: None

### CODE REVIEW

**Review by vilterp — APPROVED** [review]
Nice! Good call to move `DataFromServer` into its own file and give it its own type.

Any reason the update TSLint commit is in here?

**Comment by couchand** [comment]
The tslint update is here because otherwise this doesn't build...  I'm not sure the details, when I was flailing around trying to figure it out I saw a suggestion somewhere on the internet to upgrade tslint, so... 🤷‍♂️

**Comment by couchand** [comment]
seems to have been a flake, filed #25870

bors r+

**Pull request merged**
