### PR TITLE
distsqlrun: pool TableReaders

### PR DESCRIPTION
**Pull request by jordanlewis**
And permit ProcOutputHelper and ProcessorBase to be reset without
throwing away all slice memory.

Extracted from #30556.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
```
name                          old time/op    new time/op    delta
FlowSetup/distribute=true-8     44.2µs ± 3%    44.4µs ± 2%    ~     (p=0.563 n=10+9)
FlowSetup/distribute=false-8    34.5µs ± 5%    32.6µs ± 2%  -5.42%  (p=0.000 n=10+9)

name                          old alloc/op   new alloc/op   delta
FlowSetup/distribute=true-8     38.6kB ± 0%    36.4kB ± 0%  -5.60%  (p=0.000 n=9+9)
FlowSetup/distribute=false-8    30.2kB ± 0%    28.0kB ± 0%  -7.22%  (p=0.000 n=9+9)

name                          old allocs/op  new allocs/op  delta
FlowSetup/distribute=true-8        344 ± 0%       341 ± 0%  -0.84%  (p=0.000 n=10+10)
FlowSetup/distribute=false-8       258 ± 0%       255 ± 0%  -1.16%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
This is kind of weird - I can't reproduce the CI failure locally.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30676)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVHCy54lJFbb0ZEdWn:-LNVHCy54lJFbb0ZEdWo:bo00ktq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L163)):*
> ```Go
> 		}
> 	} else {
> 		h.outputTypes = types
> ```

I think this might be what the crash is about. Here we're using the given `types` directly.

[nit] also add a comment in this block `// No projection or renders.`, it's hard to see the high level logic

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30676)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVIsnn-rGvRCAGI1-1:-LNVIsnn-rGvRCAGI1-2:bxjw3yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L66)):*
> ```Go
> 	renderExprs []exprHelper
> 	// outputCols is set if we have a projection. Only one of renderExprs and
> 	// outputCols can have length > 0.
> ```

[nit] 0-length projections are possible, which would be an empty non-nil `outputCols`. Can you add that information in a comment here? And say `is not nil` instead of `length > 0` in these comments

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30676)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVIsnn-rGvRCAGI1-1:-LNVhnQeEy3hceZ5afQR:bwq7wpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L66)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] 0-length projections are possible, which would be an empty non-nil `outputCols`. Can you add that information in a comment here? And say `is not nil` instead of `length > 0` in these comments
</blockquote></details>

Hmm, I didn't realize that. That makes getting this code right harder. I think we'll need to store a boolean then, because now there's no way to distinguish empty renderExprs caused by the pool trying to retain slice memory, vs empty renderExprs caused by a 0 length projection.
___
*[pkg/sql/distsqlrun/processors.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVHCy54lJFbb0ZEdWn:-LNVjg_1-lHbXJ8evnfL:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L163)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this might be what the crash is about. Here we're using the given `types` directly.

[nit] also add a comment in this block `// No projection or renders.`, it's hard to see the high level logic
</blockquote></details>

done.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30676)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVIsnn-rGvRCAGI1-1:-LNVlkanAnUbPAJpapxD:b-fiqn6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L66)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, I didn't realize that. That makes getting this code right harder. I think we'll need to store a boolean then, because now there's no way to distinguish empty renderExprs caused by the pool trying to retain slice memory, vs empty renderExprs caused by a 0 length projection.
</blockquote></details>

Oh, wait, I see, this only matters for `outputCols`, which we aren't trying to save the memory of.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-:-LNjz1Oo-Yu9SUxvpi8O:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/processors.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30676#-LNVIsnn-rGvRCAGI1-1:-LNjxuar7ce0XYMWRenf:b-mj33dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbf2c86185985da0176685434676c0a3511e224/pkg/sql/distsqlrun/processors.go#L66)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh, wait, I see, this only matters for `outputCols`, which we aren't trying to save the memory of.
</blockquote></details>

Can you explicitly mention that 0-length projections are possible, in which case outputCols has length 0 but is not nil.

**Comment by jordanlewis** [comment]
Done. TFTR!

**Pull request merged**
