### PR TITLE
backupccl,ingesting: support RESTORE WITH preserve_grants_for=<users>

### LINKED ISSUE #45359: backupccl: Add option to RESTORE to preserve grants to specified users
Currently all BACKUPs include the privilege grant information on individual tables and databases, even if those backups do not include the actual users/roles to which those privileges are granted.

During restore, these grants are wiped and replaced with default privileges as if the restore had created new tables, since it isn't obvious that RESTORE can assume that a grant to user "jsmith" on the old cluster should still apply to user "jsmith" on the new cluster -- they may not be the same person, they may have different access, or may not even exist, etc.

However if can operator _is_ restoring into the same cluster or another cluster that does have the same users configured, it would be nice if they could choose to preserve that grant information instead of being forced to re-grant everything from scratch. 

An option like `RESTORE mytable ... WITH preserve_grants_for = 'jsmith,dtaylor,...'` would allow operators to express when a grant to a given pre-backup user should be preserved and apply to a post-restore user. As a shorthand, `preserve_grants_for = '*'` could mean for all users (and error if any table in the backup has a grant to a username that does not exist on the restoring cluster).

Epic CRDB-40762
Jira issue: CRDB-5156

gz#11757

### PR DESCRIPTION
**Pull request by adityamaru**
Co-authored-by: casper@cockroachlabs.com

Fixes: https://github.com/cockroachdb/cockroach/issues/45359

Release note (enterprise change): This change adds an option to database
and table level restores to `preserve_grants_for` user(s) when restoring
the table or database.

A cluster restore is not allowed to specify this option since we already
restore all users as part of the `system.users` table, and therefore the descriptor
privileges are restored exactly how they were backed up.

In the case of table and database level restores, the users specified in
the `preserve_grants_for` option must be present in the restoring cluster.
If they are, then the privileges on the restored database, schema, type and
table descriptors for those users will be restored exactly how they were backed
up. Privileges for users not specified in the `preserve_grants_for` list will
continue to be wiped and the descriptors will be restored with the "default"
privileges as they are today.

### CODE REVIEW

**Comment by adityamaru** [comment]
@RichardJCai sorry to put this on your plate so late into the release cycle but its a work item that slipped in the shuffle and we might want to consider a backport. I'm going to lean on your understanding of the privilege model to make sure what I'm doing here is sane, I've tried to comment my thinking around the major code changes.

**Comment by rafiss** [comment]
What is the plan with this PR?

**Comment by RichardJCai** [comment]
> What is the plan with this PR?

I asked Aditya to hold off on merging this a while back until the on-going privilege work is done. We should be able to get back to this soon

**Comment by livlobo** [comment]
@adityamaru @RichardJCai - can this PR be merged now?

**Comment by data-matt** [comment]
Hi folks, 

Can we provide a wildcard for this?

Something like:
`RESTORE WITH preserve_grants_for=*`

The problem is, it will be an overhead for the customer to loop through and find the users themselves.

Thanks

**Comment by data-matt** [comment]
Hey folks, whats the latest on this? @adityamaru

**Comment by adityamaru** [comment]
This is in our backlog but hasn't been prioritized, when we do pick this up we're probably going to have to start from scratch given how much has changed. cc: @livlobo

**Comment by data-matt** [comment]
@adityamaru , this was closed, what happened? thanks

**Pull request closed without merging**
