### PR TITLE
roachprod: Minor readme updates

### PR DESCRIPTION
**Pull request by bdarnell**
Use new convenience commands and demonstrate running a workload

Release note: None

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-:-LapTVNGEoYCOtqo7eI4:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

___
*[pkg/cmd/roachprod/README.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-LapTCo30AvGY_Uostf1:-LapTCo30AvGY_Uostf2:bn06n04) ([raw file](https://github.com/cockroachdb/cockroach/blob/c159d3a0d0709978b03ffe9c8a175765aa360199/pkg/cmd/roachprod/README.md#L38)):*
> ```Markdown
> # load generator for some tests. Note that the cluster name must always begin
> # with your username.
> export CLUSTER="${USER}-test"
> ```

say something about sourcing the bash completion script in ~/.roachprod (although the  thing doesn't complete cluster names for me for some reason...)
___
*[pkg/cmd/roachprod/README.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-LapTLYACpRqWc_uOsq_:-LapTLYACpRqWc_uOsqa:b-snagws) ([raw file](https://github.com/cockroachdb/cockroach/blob/c159d3a0d0709978b03ffe9c8a175765aa360199/pkg/cmd/roachprod/README.md#L50)):*
> ```Markdown
> # ...or using roachprod directly (e.g., for your locally-built binary).
> build/builder.sh mkrelease
> roachprod put ${CLUSTER} cockroach-linux-2.6.32-gnu-amd64 cockroach
> ```

isn't the binary in `bin.linux-amd64/cockroach-linux-...` or so on Macs?

**Review by andreimatei — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-:-LapT_Uw8p5qgDUeBjhX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @bdarnell)

**Review by bdarnell — COMMENTED** [review]
bors r=andreimatei

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-:-LapUhrNCHJa1hBaDIzr:bx2dzm5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/cmd/roachprod/README.md, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-LapTCo30AvGY_Uostf1:-LapUON2-NNc2_CSQbYM:bbjdox5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c159d3a0d0709978b03ffe9c8a175765aa360199/pkg/cmd/roachprod/README.md#L38)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say something about sourcing the bash completion script in ~/.roachprod (although the  thing doesn't complete cluster names for me for some reason...)
</blockquote></details>

I'll leave that for someone who knows something about it (and who can get it to work as expected); I run stuff from emacs so I don't use custom bash completion anyway. 
___
*[pkg/cmd/roachprod/README.md, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36101#-LapTLYACpRqWc_uOsq_:-LapUVeI-fOEsJwwMApQ:b-uihamv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c159d3a0d0709978b03ffe9c8a175765aa360199/pkg/cmd/roachprod/README.md#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

isn't the binary in `bin.linux-amd64/cockroach-linux-...` or so on Macs?
</blockquote></details>

Not with `builder.sh mkrelease`

**Comment by bdarnell** [comment]
bors r+

Looks like bors missed this before.

**Comment by bobvawter** [comment]
bors ping

**Pull request merged**
