### PR TITLE
colexec: fix merge joiner in some cases

### LINKED ISSUE #46106: colexec: incorrect output on TPCH Q5 with very low memory limit
I decided to run all TPCH queries with `100KiB` as `workmem` memory limit with `vectorize=experimental_on` (to stress disk spilling) and got incorrect results on query 5. This is reproducible on a local 1 node cluster:
```
Yahors-MacBook-Pro:cockroach yuzefovich$ ./bin/workload run tpch --db tpch --concurrency=1 --vectorize=experimental_on --queries=5
Error: TPCH wrong output [q5] 55617258.261000 and 55502041.170000 differ by more than 0.02
wrong result in row 0 in column 1: got "5.561725826130002e+07", expected "5.5502041169699945e+07"
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix merge joiner in some cases**

Release justification: bug fixes and low-risk updates to new
functionality.

The cross product builder in the merge joiner was not correctly reset
when building from the left buffered group. The issue was that we were
correctly resetting `builderState` for the first column but then could
be incorrectly overwriting it to `initialBuilderState` (which hasn't
been properly reset) on the consequent columns. For the problem to
appear we needed to have such buffered group that its built output would
not fit into a single batch and that the "building" would stop somewhere
in the middle.

Fixes: #46106.

Release note: None

**colexec, coldata: miscellaneous cleanups**

Release justification: bug fixes and low-risk updates to new
functionality.

This commit cleans up a few things:
- removes coldata.Batch.PrettyValueAt method since it is no longer used
- fixes the calculation of the partition sizes on the right side in the
external hash joiner
- fixes the calculation of RAM dedicated in the external sort to the
cache of disk queues.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
first commit looks good. not sure about the second one - why is this batched in the same PR?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-:-M39faHp-R_bdLX62fGd:b-vs6wva)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/mergejoiner.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-M39fTZb9ZUyKCzjP0Px:-M39fTZb9ZUyKCzjP0Py:b-cpbl6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d9ff28b767ee49bdca5ebe24969640e237f2c3/pkg/sql/colexec/mergejoiner.go#L414)):*
> ```Go
> 	o.proberState.rBufferedGroup.reset(ctx)
> 	o.proberState.lBufferedGroupNeedToReset = false
> 	o.proberState.rBufferedGroupNeedToReset = false
> ```

these are in the wrong commit i think

**Review by yuzefovich — COMMENTED** [review]
Only because I noticed those things while debugging the issue and didn't feel like creating a separate PR for those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-:-M39fu3f4L5CLW8kpStD:b1xijwg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/mergejoiner.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-M39fTZb9ZUyKCzjP0Px:-M39g3xl2hRz3pZK1Xw3:btse6m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d9ff28b767ee49bdca5ebe24969640e237f2c3/pkg/sql/colexec/mergejoiner.go#L414)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

these are in the wrong commit i think
</blockquote></details>

This is not needed for correctness at all and more like "philosophically correct thing to do" that doesn't actually affect the bug fix in the first PR.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-M3B28hB5Tjap-rkjh2M:-M3B28hCB8rN5vX4MObM:bkfdmxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d9ff28b767ee49bdca5ebe24969640e237f2c3/pkg/sql/colexec/external_hash_joiner.go#L471)):*
> ```Go
> 				// look at the capacities of the vectors, and in our case only
> 				// first len(sel) tuples belong to the "current" batch.
> 				partitionInfo.rightMemSize += getProportionalBatchMemSize(scratchBatch, int64(len(sel)))
> ```

What was wrong with this calculation beforehand, not accounting for bytes properly?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46432)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-M3B28hB5Tjap-rkjh2M:-M3C3ZnU3us8bmalpWgx:b-hmepxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d9ff28b767ee49bdca5ebe24969640e237f2c3/pkg/sql/colexec/external_hash_joiner.go#L471)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What was wrong with this calculation beforehand, not accounting for bytes properly?
</blockquote></details>

We were overestimating the actual footprint. For example, a batch with vectors' capacities of 1024 came in but with the length of 512. If `len(sel) == 256`, we would estimate that `256/512=1/2` of the full batch memory footprint would be added into the right partition, but, in fact, it should `256/1024=1/4`.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46432#-:-M3CdnSn18Zyyp8DR31z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
