### PR TITLE
storage, kv: Delete Compactor and related metrics

### LINKED ISSUE #55839: storage: Delete compactor code, metrics, and settings
All compactor-related code paths and settings are effectively dead after #55509 lands, as they were only enabled when the storage engine was RocksDB. Pebble already took into account range deletions when scoring compactions, so a compactor queue was unnecessary on top of it.

This issue is to clean up all references to the compactor, as well as any related settings and metrics.

### PR DESCRIPTION
**Pull request by itsbilal**
All code around the Compactor and compaction suggestions is now
dead code, as it was only used with RocksDB anyway. This change
deletes it.

Fixes #55839.

Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
I'm less familiar with `pkg/keys` code and any potential issues with migrations, so I didn't delete `StoreSuggestedCompactionKey` and related functions. Is there a canonical way to mark that prefix of keys as deprecated and delete code around it?

**Review by tbg — COMMENTED** [review]
I would delete the code and put something into `(*Store).Start` that manually constructs and then iterates over that span and point deletes any key it finds. That code can be removed one release later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MKKl5uM89lRZsKlui1H:bo9ql57)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @petermattis, and @tbg)

___
*[pkg/ts/catalog/chart_catalog.go, line 2129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-MKKkx6l3t1gnkvPUk0g:-MKKkx6l3t1gnkvPUk0h:b-k79kly) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e88183e084317805a11bcdff68c43d714eaa745/pkg/ts/catalog/chart_catalog.go#L2129)):*
> ```Go
> 			{
> 				Title: "Overview",
> 				Metrics: []string{
> ```

btw, I checked that the corresponding time series will still be deleted over time (see MaintainTimeSeries, not in this diff).

**Review by tbg — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

**Review by jbowens — APPROVED** [review]
You love to see it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MKL9YJj75XhvqLlXuQQ:bvqobyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

**Review by petermattis — COMMENTED** [review]
More code deletion. Lovely!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MKMo6Mj1hG2aaqEr8s-:b-yn3vhn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

**Review by itsbilal — COMMENTED** [review]
TFTRs!

I added a second commit where I deleted all `StoreSuggestedCompactionKey` related code, and added a block in `Store.Start` to clean up any keys from past versions. @tbg / someone from kv mind reviewing the second commit? Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MK_ffQA43Y1FKu_FdDH:b-fgdko5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MKjwFH-6_hORTKbzKwP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/kv/kvserver/store.go, line 1589 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-MKjwBGv2MxDMq8yZJYd:-MKjwBGv2MxDMq8yZJYe:bl6u6nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7032f1588d9307ffe6fc9996607264c863f31fa/pkg/kv/kvserver/store.go#L1589)):*
> ```Go
> 		storage.MVCCKeyIterKind,
> 		func(res storage.MVCCKeyValue) error {
> 			return s.engine.Clear(res.Key)
> ```

This syncs, right? ;-)

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-:-MKjy8cc2mgBSz-rwXFM:bz5m8ji)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/store.go, line 1589 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55893#-MKjwBGv2MxDMq8yZJYd:-MKjxzP9D1VWJnN2I1Qm:b-u9towg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7032f1588d9307ffe6fc9996607264c863f31fa/pkg/kv/kvserver/store.go#L1589)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This syncs, right? ;-)
</blockquote></details>

Haha of course. I actually did think about using a batch here, but given the most common case is where this code won't be invoked at all, it's best to keep that part light.

**Comment by itsbilal** [comment]
bors r=tbg

**Pull request merged**
