### PR TITLE
opt: detect Select contradictions, make CanConstrainScan more selective

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: detect Select contradictions

When a Select filter has a contradiction, replace it with a Values
expression with no rows.

Release note: None

#### opt: make CanConstrainScan more selective

CanConstrainScan now also checks if the filter involves the first
column of the index. This is a quick check to reduce the cases where
the rule matches but we don't generate any new expressions.

Release note: None

These changes seem unrelated, but there were a few cases where we were detecting a contradiction with a filter that would not pass the new check.

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-:-LJdf6xp7HrgZPkONZXd:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-LJdekJPAdtAMCXZsgUF:-LJdekJPAdtAMCXZsgUG:b-towdt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/72eb9520b432f23acd4bd25cac777fc775114e85/pkg/sql/opt/xform/custom_funcs.go#L252)):*
> ```Go
> 	index := md.Table(scanOpDef.Table).Index(scanOpDef.Index)
> 	firstIndexCol := scanOpDef.Table.ColumnID(index.Column(0).Ordinal)
> 	return c.OuterCols(filter).Contains(int(firstIndexCol))
> ```

Should we also be checking the constraints (if present) to see if the first index column has any constraint on it?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28480)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-LJdekJPAdtAMCXZsgUF:-LJjErGx1sDikI8lXjAM:bze0pbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/72eb9520b432f23acd4bd25cac777fc775114e85/pkg/sql/opt/xform/custom_funcs.go#L252)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should we also be checking the constraints (if present) to see if the first index column has any constraint on it?
</blockquote></details>

We don't generate constraints in all cases where we generate index constraints (there are a bunch of TODOs in the general constraints code); a major case is `OR`. I added a check but only if the constraints are tight.

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28480)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-LJo-8-G7hGcOjf8las3:-LJo-8-G7hGcOjf8las4:bgcdaeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/31514a399989132087fed17bf6e0915665f1bbd8/pkg/sql/opt/memo/testdata/logprops/constraints#L335)):*
> ```
>       ├── columns: x:1(int) y:2(int) rowid:3(int!null)
>       ├── constraint: /3: contradiction
>       ├── cardinality: [0 - 1]
> ```

why did this revert back to having max cardinality of 1?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28480)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-LJo-8-G7hGcOjf8las3:-LJofJOS1NtJrZ-gYcUa:b-1mkak9) ([raw file](https://github.com/cockroachdb/cockroach/blob/31514a399989132087fed17bf6e0915665f1bbd8/pkg/sql/opt/memo/testdata/logprops/constraints#L335)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did this revert back to having max cardinality of 1?
</blockquote></details>

It's a different test than before, it's now hard to end up with a scan w/contradiction. In this case we have a filter that is not a contradiction on its own, but it becomes one when combined with the table properties. The logical props we are seeing come from the original `Select` that started the group.

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-:-LJobMovEamRPe3nQ-ww:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28480#-LJo-8-G7hGcOjf8las3:-LJokhGcE3TbdyIRU41R:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/31514a399989132087fed17bf6e0915665f1bbd8/pkg/sql/opt/memo/testdata/logprops/constraints#L335)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a different test than before, it's now hard to end up with a scan w/contradiction. In this case we have a filter that is not a contradiction on its own, but it becomes one when combined with the table properties. The logical props we are seeing come from the original `Select` that started the group.
</blockquote></details>

Got it - thanks!

**Pull request merged**
