### PR TITLE
sql: check for multiple mutations to the same table by triggers

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: refactor some cascade/trigger logic

This commit refactors some of the logic shared between cascades and
AFTER triggers. This will make the following commit easier to understand.

Epic: None

Release note: None

#### sql: check for multiple mutations to the same table by triggers

There are currently some situations where a query that modifies the
same table in multiple locations may cause index corruption (#70731).
To avoid this, we disallow query structures that may lead to a problematic
combination of mutations.

Triggers require special handling to make this check work, because they
can execute arbitrary SQL statements, which can mutate a table directly
or through routines, FK cascades, or other triggers. BEFORE triggers on
the main query "just work" because they are built as UDF invocations as
part of the main query. AFTER triggers and BEFORE triggers fired on
cascades are more difficult, because they are planned lazily only if
the post-query has rows to process.

This commit adds logic to track invalid mutations for both types of
triggers. We now propagate the "ancestor" mutated tables whenever planning
a post-query, so that any triggers planned as part of the post-query
can detect conflicting mutations. See the "After Triggers" section in
`statement_tree.go` for additional explanation.

Informs #70731

Release note (bug fix): Previously, it was possible to cause index
corruption using AFTER-triggers that fire within a routine. In order
for the bug to manifest, both the AFTER-trigger and the statement that
invokes the routine must mutate the same row of a table with a mutation
other than `INSERT`.

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136076)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ3QRwEpjFhvPoTSg5:-OCZ3QRwEpjFhvPoTSg6:b-l1vuwu):*
Does "routine" mean the trigger routine here? Or the routine that performs the cascade? IIUC this can manifest without calling a UDF or SP directly, which is what a user would probably assume by the expression "invokes the routine".
___
*[`pkg/sql/opt/optbuilder/util.go` line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ8-nM4N8sIx8hBPma:-OCZ8-nM4N8sIx8hBPmb:bym0ag5) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dac42228051c4fe0474e73fc29c47c4287b16e/pkg/sql/opt/optbuilder/util.go#L567)):*
> ```Go
> // stmtTreeInitFnForPostQuery returns a function that can be used to initialize
> // the statement tree for a post-query plan.
> func (b *Builder) stmtTreeInitFnForPostQuery() func() statementTree {
> ```

I think this might be better as a method of `statementTree`. Should it be unit tested?
___
*[`pkg/sql/opt/optbuilder/util.go` line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ7svx5nFnjUi9Kril:-OCZ7svx5nFnjUi9Krim:b2maaz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dac42228051c4fe0474e73fc29c47c4287b16e/pkg/sql/opt/optbuilder/util.go#L573)):*
> ```Go
> 	// Save references to the ancestor statementTreeNodes. Modifications to them
> 	// after this point should be reflected in the references, ensuring that all
> 	// ancestor mutations are visible when the post-query is built.
> ```

I'm having trouble understanding cases where using mutable references here is necessary. Do you have an exmaple?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136076)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ3QRwEpjFhvPoTSg5:-OCbh3JD74JlM8lLfvj3:b-ru21fl):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does "routine" mean the trigger routine here? Or the routine that performs the cascade? IIUC this can manifest without calling a UDF or SP directly, which is what a user would probably assume by the expression "invokes the routine".
</blockquote></details>

"routine" here means there must be a UDF/SP, with a body statement that mutates the table in an AFTER trigger (or BEFORE trigger on a cascade). It's a pretty convoluted set of steps. I've modified the release note to try and make it more clear, PTAL.
___
*[`pkg/sql/opt/optbuilder/util.go` line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ8-nM4N8sIx8hBPma:-OCbRxjr1aAg7Z8k2duY:bx4nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dac42228051c4fe0474e73fc29c47c4287b16e/pkg/sql/opt/optbuilder/util.go#L567)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this might be better as a method of `statementTree`. Should it be unit tested?
</blockquote></details>

Done and done.
___
*[`pkg/sql/opt/optbuilder/util.go` line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ7svx5nFnjUi9Kril:-OC_9_TB872bF-WyhRsT:bmywjqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dac42228051c4fe0474e73fc29c47c4287b16e/pkg/sql/opt/optbuilder/util.go#L573)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm having trouble understanding cases where using mutable references here is necessary. Do you have an exmaple?
</blockquote></details>

Good callout. It's possible to encounter some mutations in the "current" scope after some mutations in the "child" scope - e.g. if the first branch of a CTE contains a UDF call with a mutation, and the second branch is an INSERT statement. I'll add to the comment. I'll also add a test and verify that it catches a failure to observe all references.

**Comment by DrewKimball** [comment]
@mgartner friendly ping :)

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-:-ODSUNfSBDB17uzLFO_5:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/opt/optbuilder/util.go` line 573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136076#-OCZ7svx5nFnjUi9Kril:-ODSU1CA6fkld3FIaX6g:b-gw4nhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/79dac42228051c4fe0474e73fc29c47c4287b16e/pkg/sql/opt/optbuilder/util.go#L573)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good callout. It's possible to encounter some mutations in the "current" scope after some mutations in the "child" scope - e.g. if the first branch of a CTE contains a UDF call with a mutation, and the second branch is an INSERT statement. I'll add to the comment. I'll also add a test and verify that it catches a failure to observe all references.
</blockquote></details>

Thanks. It's a bit confusing, but I believe I understand it now. This may be a sign that this data structure is no longer a good fit for this responsibility. We talked IRL about potentially lifting this restriction of multiple mutations altogether by using read-committed locks. It's something we should explore more.

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
