### PR TITLE
sql: allow creating multi-column inverted indexes

### PR DESCRIPTION
**Pull request by mgartner**
This commit allows creating multi-column inverted indexes if the
`experimental_enable_mutlti_column_inverted_indexes` session setting is
set to true. Once these indexes are fully supported,  this session
setting will be removed.

This change is required for writing logic tests to validate the behavior
of mutating and scanning multi-column inverted indexes.

Release note (sql change): Creating multi-column inverted indexes is
allowed by setting the
`experimental_enable_mutlti_column_inverted_indexes` session setting to
true. At this time, these indexes are not fully supported and their
behavior is undefined. Using this feature will likely result in errors.
Do not enable this setting in a production database.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-:-MKb2M_BDhG7xxt1lA1W:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/catalog/descpb/index.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKb1JU-Ag-sIaRwe3GZ:-MKb1JU-Ag-sIaRwe3G_:b-pajbt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ca392139b8a586565579018ddac1efc9e986171/pkg/sql/catalog/descpb/index.go#L182)):*
> ```Go
> // inverted index. This is always the last column in ColumnNames. Panics if the
> // index is not inverted.
> func (desc *IndexDescriptor) InvertableColumnName() string {
> ```

Why not just call it `InvertedColumnName`?
___
*[pkg/sql/catalog/descpb/index.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKb1Zwi0833jptuvNyE:-MKb1Zwj6AQSGMDZyeit:b4z0myr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ca392139b8a586565579018ddac1efc9e986171/pkg/sql/catalog/descpb/index.go#L184)):*
> ```Go
> func (desc *IndexDescriptor) InvertableColumnName() string {
> 	if desc.Type != IndexDescriptor_INVERTED {
> 		panic(errors.AssertionFailedf("index in not inverted"))
> ```

in -> is

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/catalog/descpb/index.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKb1JU-Ag-sIaRwe3GZ:-MKb53Fu6RBJLDsyDJXu:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ca392139b8a586565579018ddac1efc9e986171/pkg/sql/catalog/descpb/index.go#L182)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why not just call it `InvertedColumnName`?
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/catalog/descpb/index.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKb1Zwi0833jptuvNyE:-MKb57Rv1jCwcmsfpvqR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ca392139b8a586565579018ddac1efc9e986171/pkg/sql/catalog/descpb/index.go#L184)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

in -> is
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/explain_bundle.go, line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKg6BnD8abhCgalTbvP:-MKg6BnD8abhCgalTbvQ:bmnu8qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40ca77753e5b0c8a4979865faf80af2230df72a/pkg/sql/explain_bundle.go#L516)):*
> ```Go
> 		{sessionSetting: "optimizer_use_multicol_stats", clusterSetting: optUseMultiColStatsClusterMode},
> 		// TODO(mgartner): remove this once multi-column inverted indexes are fully supported.
> 		{sessionSetting: "experimental_enable_multi_column_inverted_indexes", clusterSetting: experimentalMultiColumnInvertedIndexesMode},
> ```

I don't think this setting can affect planning inside the optimizer, it shouldn't need to be in this list.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/explain_bundle.go, line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-MKg6BnD8abhCgalTbvP:-MKgO-1G3_Trz7Ckej8t:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b40ca77753e5b0c8a4979865faf80af2230df72a/pkg/sql/explain_bundle.go#L516)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this setting can affect planning inside the optimizer, it shouldn't need to be in this list.
</blockquote></details>

Removed.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55993#-:-MKqKvsQAKX7RYn-V59T:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
