### PR TITLE
sql,log: productionize the event logging

### LINKED ISSUE #57629: logging: standardize the event log and bring structured details to external logs
Today we have an `EventLog` mechanism inside the SQL package that writes JSON blobs to `system.eventlog`. These use structured payloads that are undocumented, unstable and irregular/inconsistent.

Then, separately, we also have the logging infrastructure that writes unstructured strings to external files.

We want instead to have structured payloads that are documented, stable and consistent, and have them into external files (or network collector when that is supported - see #57170  ), on a dedicated logging channel (see #57171 ).

Steps:

- [x] finish converting the calls throughout the SQL package #57737
- [x] find some workable approach for the node events #57737 
- [x] fix the generated names for grant/revoke events  #57737 
- [x] add a doc generator  #57737 
- [x] tweak the files in `pkg/ui/src/util` accordingly  #57737 
- [x] add an assertion in `sql.planner` that everything that touches descriptor has at least 1 event logged - NOT DONE, instead filed #57823 for SQL Schema team
- [x] add a "category" field for cluster-level vs sql-level, use that in doc generator   #57737 
- [x] recognize the events in `util/log` and treat them separately   #57737 
- [x] make writes to system.eventlog conditional #57879
- [x] include the sql tenant ID in log file headers alongside cluster ID #57888 #57890
- [x] update PR #57171 to assign cluster events to the OPS channel 
- [x] rework PR #51987 to assign DDL and privilege events to their appropriate channels
- [x] ensure that individual fields inside JSON notable events are redacted (or marked as redactable) separately  #57990 
- [x] add the application name to all structured sql events #58130 
- [x] insert JSON formats #58126 
- [x] treat event types specially and insert their JSON representation inline #58126 
- [x] transform the single-string "Tags" payload of log events into separate JSON fields #58126 
- [x] modify the JSON output to inject the node ID and tenant ID and sql instance ID as separate discrete fields #57890   #58128 
- [x] pgwire: migrate auth/conn logs to notable events #57839
- [x] update the RFC in #51990 
- [x] new RFC to explain notable events #58374 
- [x] sql: ensure event log entries for ALTER/DROP TYPE are fully qualified #58257 
- [x] add placeholder values alongside the SQL statement #59108
- [x] add more structure for the events for accesses to audited tables (SENSITIVE_ACCESS) and SQL query logs #59105  #59110
- [x] server: file operational notable events for TLS cert rotations #57889  #59345
- [x] add a new sort of SQL query logging, for all statements performed by admin users  #58334 #59356

### PR DESCRIPTION
**Pull request by knz**
Informs #57629

CockroachDB needs to report structured events for
"important" (notable) events on the logical structure of a cluster,
including changes to the SQL logical schema, node activity, privilege
changes etc.

Prior to this patch, these events were reported mainly into the
table `system.eventlog`, with a partial copy of the payload into the
debugging external log (`cockroach.log`).

This solution was incomplete and unsatisfactory in many ways:

- the event payloads were not documented.
- the event payloads were not centrally defined, which was preventing
  the generation of automatic documentation.
- the payload types were declared "inline" in the log calls, which
  made it easy for team members to inadvertently change the structure of
  the payload and make them backward-incompatible for users consuming
  this data externally.
- the payload fields were inconsistently named across event types.
- the metadata fields on the payloads were incompletely and
  inconsistently populated:

  - the SQL instance ID was missing in some cases.
  - the descriptor ID of affected descriptor was missing in some
    cases.

- the same event type was mistakenly used for different events (e.g.
  "rename_database" for both RENAME DATABASE and CONVERT TO SCHEMA)
- the same event type was abusingly over-used for multiple separate
  operations, e.g. a single event would be generated for a multi-table,
  multi-user GRANT or REVOKE operation.
- events could be omitted entirely from external logs, e.g.
  if the system.eventlog table was not available during a node
  restart.
- the copy in the external log was not parseable. Generally, the
  logging package was unaware of the internal structure of events
  and would “flatten” them.
- no provision was available to partially redact events. From the
  logging system's perspective, the entire payload is sensitive.

This commit changes the situation as follows:

- it centralizes the payload definitions and standardizes them into a
  new package `eventspb`.
- it groups events into categories and associates logging
  channels to each event category.
- it enables automatic generation of documentation for events.
- it ensures that field names are consistent across event payloads.
- it ensures that event metadata is consistently populted.
- it decomposes complex GRANT/REVOKE operations into individual
  events.
- it automates the generation of a reference documentation for all
  event types.
- it ensures that events are sent to external logs unconditionally.

The following problems continue to exist and need to be resolved
separately:

- privilege changes that occur as a side effect of certain operations
  do not get events logged:

  #57573
  #57576
  #57739
  #57741

- the name fields in certain DDL events is not properly qualified,
  which prevents the determination of the logical schema or database
  where the object was altered:

  #57734
  #57735
  #57738
  #57740

Release note (sql change): The cluster event logging system has been
modernized. In particular, the schema of the entries for the `info`
column in `system.eventlog` has been stabilized.

Release note (cli change): The events that were previously only stored
in `system.eventlog` are now also directed unconditionally to an
external logging channel using a JSON format.  Refer to the
configuration to see how to customize how events are directed to
external sinks. Note that the exact external output format (and thus
how to detect/parse the events from e.g. log files) is not yet
stabilized and remains subject to change.

Release note (doc change): The cluster event logging system has been
standardized. A reference documentation is now
available (auto-generated from source code); changes to non-reserved
payloads will now be announced at least one release version in
advance. The event types are organized into broad categories: SQL
Logical Schema Changes, SQL Privilege Changes, SQL User Management,
CLuster-level events and SQL Miscellaneous operations.

Release note (backward-incompatible change): The payload fields for
certain event types in `system.eventlog` have been changed and/or
renamed. Note that the payloads in `system.eventlog` were an
undocumented, reserved feature so no guarantee was made about
cross-version compatibility to this point. The list of changes
includes (but is not limited to):

- `TargetID` has been renamed to `NodeID` for `node_join`
- `TargetID` has been renamed to `TargetNodeID` for
  `node_decommissioning` / `node_decommissioned` /
  `node_recommissioned`.
- `NewDatabaseName` has been renamed to `NewDatabaseParent` for
  `convert_to_schema`.
- `grant_privilege` and `revoke_privilege` have been removed;
  they are replaced by `change_database_privilege`,
  `change_schema_privilege`, `change_type_privilege` and
  `change_table_privilege`.
  Each event only reports change for one user/role, so the
  `Grantees` field was renamed to `Grantee`.
- Each `drop_role` event now pertains to a single user/role.

Release note (sql change): The `targetID` and `reportingID` columns in
`system.eventlog` are now deprecated. Their values, for relevant event
types, can be found as fields inside the `info` column instead.

### CODE REVIEW

**Comment by knz** [comment]
@itsbilal this is the draft branch we talked about yesterday.
Can you have a look at the overall approach? 

What I am missing here is an approach that works for the 3 odd events, those that are node-level: node restart, join, decommission. How to best factor that code?

**Comment by knz** [comment]
Remaining to do:

- [ ] finish converting the calls throughout the SQL package
- [ ] add an assertion in `sql.planner` that everything that touches descriptor has at least 1 event logged
- [ ] add a doc generator
- [ ] find some workable approach for the node events
- [ ] recognize the events in `util/log` and treat them separately
- [ ] modify #57170 to treat event types specially and insert their JSON representation inline

**Review by itsbilal — COMMENTED** [review]
Looks great to me so far! I like the CommonDetails/CommonSQLDetails etc setup of the protobuf structs. I made one suggestion around handling the node events by having a more specialized method than `InsertEventRecord` that fills in node-specific details. From my code observation so far, that seems to make sense to be, but let me know if it doesn't.

> Reviewed 16 of 16 files at r1, 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-:-MO79kQW5_GnlcIY3t0_:bbxmb3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/event_log.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MO77f2GDPCgGdKVB-sK:-MO77f2GDPCgGdKVB-sL:b64wfha) ([raw file](https://github.com/cockroachdb/cockroach/blob/55e07355ccd15bc6a4b91f1dd96e254d9cd3bf2b/pkg/sql/event_log.go#L233)):*
> ```Go
> // InsertEventRecord inserts a single event into the event log as part of the
> // provided transaction.
> func (ev EventLogger) InsertEventRecord(
> ```

I'm guessing all uses of this method will soon be from just this file. Might be worth unexporting the method and having a separate one, `LogNodeEvent`, that takes in a partially-filled NodeEvent, a node descriptor/ctx/etc, and fills in common details + common node details?

**Review by knz — COMMENTED** [review]
I think this is good for a first round of review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-:-MO95X3G9Lxq8KBIOImv:bauudm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/sql/event_log.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MO77f2GDPCgGdKVB-sK:-MO95V10-1ZoUPTVoPvk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55e07355ccd15bc6a4b91f1dd96e254d9cd3bf2b/pkg/sql/event_log.go#L233)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'm guessing all uses of this method will soon be from just this file. Might be worth unexporting the method and having a separate one, `LogNodeEvent`, that takes in a partially-filled NodeEvent, a node descriptor/ctx/etc, and fills in common details + common node details?
</blockquote></details>

Done.

**Review by itsbilal — APPROVED** [review]
Looks great so far! Just some minor comments. Looking forward to seeing the rest of the changes come in.

> Reviewed 45 of 45 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-:-MOEXlHz-UiRkdhARkzi:bcy0f6w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/event_log.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MOE9-PF9OSna0MFsRA4:-MOE9-PF9OSna0MFsRA5:b7rngva) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4186bc68ab20ecdeb44ab5cf6b95cb4764428b2/pkg/sql/event_log.go#L150)):*
> ```Go
> `
> 	args := []interface{}{
> 		info.CommonDetails().Timestamp,
> ```

Might be a good idea returning an error here if this is unset?
___
*[pkg/util/log/eventpb/events.proto, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MOEUkS7-boFxW_nDKhD:-MOEUkS7-boFxW_nDKhE:b-nc8dlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4186bc68ab20ecdeb44ab5cf6b95cb4764428b2/pkg/util/log/eventpb/events.proto#L21)):*
> ```protobuf
> //
> // Notes:
> // - the fields have jsontag ",..." to override the default
> ```

`,omitempty` intead of ... ? I'm not sure if I understand this comment as-is.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/sql/event_log.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MOE9-PF9OSna0MFsRA4:-MOGAogp5F9YXbUaRW2D:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4186bc68ab20ecdeb44ab5cf6b95cb4764428b2/pkg/sql/event_log.go#L150)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Might be a good idea returning an error here if this is unset?
</blockquote></details>

Good idea. Done.
___
*[pkg/util/log/eventpb/events.proto, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57737#-MOEUkS7-boFxW_nDKhD:-MOGr6U83ZIKF4GFYRt0:b-b8wlxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4186bc68ab20ecdeb44ab5cf6b95cb4764428b2/pkg/util/log/eventpb/events.proto#L21)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`,omitempty` intead of ... ? I'm not sure if I understand this comment as-is.
</blockquote></details>

Explained in comment.

**Comment by knz** [comment]
bors r=itsbilal

**Pull request merged**
