### PR TITLE
Utilize breaker in `RaftTransport.SendSync`

### PR DESCRIPTION
**Pull request by spencerkimball**
This fixes merge skew from #8529

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8652)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-:-KPTemIWVDm3sjbO_0aQ:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTegPVuc-20CvlBubT:b-i8yglm) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
> ```Go
> 		roachpb.ReplicaDescriptor{NodeID: 3, StoreID: 3},
> 		rep.Desc()); !testutils.IsError(err, expErr) {
> 		t.Fatalf("epxected %s; got %s", expErr, err)
> ```

typo: expected. also "got" could be `nil`, so you should use `%v` for it (but not expected).

---

*[storage/raft_transport.go, line 141 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeHavjiWPzktMXxXb:-KPTeHavjiWPzktMXxXc:b8adgok) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L141)):*
> ```Go
> 
> 	if !ok {
> 		return roachpb.NewErrorf("unable to accept Raft message from %+v: no store registered for %+v",
> ```

s/store/handler/

---

*[storage/raft_transport.go, line 397 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeQA4PmECeboLzVzd:-KPTeQA4PmECeboLzVze:b-sd1xkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L397)):*
> ```Go
> func (t *RaftTransport) SendSync(ctx context.Context, req *RaftMessageRequest) error {
> 	// Use the circuit breaker to fail fast if the breaker is open.
> 	// The same underlying conneciton is shared between sync and
> ```

typo: connection

---

*[storage/raft_transport.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeapd9H1Bb12XvDK8:-KPTeapd9H1Bb12XvDK9:b-p5nvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L401)):*
> ```Go
> 	var resp *RaftMessageResponse
> 	nodeID := req.ToReplica.NodeID
> 	breaker := t.GetCircuitBreaker(nodeID)
> ```

fair bit of duplicated code here (all but the RPC itself). extract?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1174 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTephinwiOzncIja-l:-KPTephinwiOzncIja-m:b-hfpv1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L1174)):*
> ```Go
> 		mtc.manualClock.Increment(int64(storage.ReplicaGCQueueInactivityThreshold + 1))
> 		mtc.stores[1].ForceReplicaGCScanAndProcess()
> 		log.Infof(context.TODO(), "waiting to verify GC of replica")
> ```

remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTextCA51YcnYB31-i:b-dpy3mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> typo: expected. also "got" could be `nil`, so you should use `%v` for it (but not expected).
</details>
I always use `%s` for errors.

---

*[storage/raft_transport.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeapd9H1Bb12XvDK8:-KPTf97o50jSRPh_UD-h:b-k7i7ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L401)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> fair bit of duplicated code here (all but the RPC itself). extract?
</details>
This isn't significant enough to warrant another method IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTk9HwP_dLBLCSP0zc:b-5enxrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I always use `%s` for errors.
</details>
That's no bueno. See https://play.golang.org/p/Fb5mUjxTOQ

---

*[storage/raft_transport.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeapd9H1Bb12XvDK8:-KPTkPW5f4lBrJOQx7gA:b-rebw5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L401)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> This isn't significant enough to warrant another method IMO.
</details>
I'm not really concerned about code duplication - to me this is more about potential for divergent behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTm_s_9eQSnC9t_G6J:b-2cnxsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> That's no bueno. See https://play.golang.org/p/Fb5mUjxTOQ
</details>
That playground example isn't very motivating. Probably 90+% of our code uses `%s`.

---

*[storage/raft_transport.go, line 401 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTeapd9H1Bb12XvDK8:-KPTmiiq6n76SNAwuOR_:b8bh0g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/raft_transport.go#L401)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not really concerned about code duplication - to me this is more about potential for divergent behaviour.
</details>
Seems an insignificant risk.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTnSZbXF8i0FhaIhpe:b-izk0tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> That playground example isn't very motivating. Probably 90+% of our code uses `%s`.
</details>
For non-nil errors, the number is more like 25%:

```
$ git grep -A2 -F IsError | grep -F '%s' | grep -vF '%v' | wc -l
      48
$ git grep -F IsError | wc -l
     163
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 2341 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652#-KPTegPVuc-20CvlBubS:-KPTo-oYSC9PBIGU723Q:b2lu878) ([raw file](https://github.com/cockroachdb/cockroach/blob/259e8dfafd65b17ae3537d8f3ac62de3841222d1/storage/client_raft_test.go#L2341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> For non-nil errors, the number is more like 25%:
> 
> ```
> $ git grep -A2 -F IsError | grep -F '%s' | grep -vF '%v' | wc -l
>       48
> $ git grep -F IsError | wc -l
>      163
> ```
</details>
Er, more like 30%

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8652)*

**Comment by spencerkimball** [comment]
```
SPENCERs-MacBook-Pro:cockroach spencerkimball$ git grep -A2 -F %s | grep -F 'err'  | wc -l
    1520
SPENCERs-MacBook-Pro:cockroach spencerkimball$ git grep -A2 -F %v | grep -F 'err'  | wc -l
     441
```

**Comment by tamird** [comment]
That grep is misleading, it is including errors that are known to be non-nil logged as `%s`.

**Comment by spencerkimball** [comment]
The code indicates there's no agreed-upon pattern and the win for the case
of `err=nil` seems inconsequential.

**Pull request merged**
