### PR TITLE
opt/execbuilder: reduce allocations when building group-by expressions

### PR DESCRIPTION
**Pull request by mgartner**
#### opt/bench: add benchmark with many columns and a group-by

Release note: None

#### opt/execbuilder: reduce ColSet allocations when building group-by

Prior to this commit `buildGroupByInput` would create a set of the
aggregate input columns and add it to a copy of the set of grouping
columns. Now, the aggregate input columns are added directly to the
grouping columns copy, eliminating allocations when column IDs exceed
the small set maximum column ID (currently 128).

Release note: None

#### opt/execbuilder: reduce allocations when building aggregates

Aggregate input columns and constants are now allocated in bulk, instead
of one-at-a-time for each aggregate expression in a group-by. This
reduces allocations, espeically for queries with group-by expressions
with many aggregates.

Epic: None

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'll defer to Drew for approval.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-:-O0AqBCNATfDHvFq-Ht-:b-ap6dij)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1631 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0Apnlt6FbOY7p94BIG:-O0Apnlt6FbOY7p94BIH:bkew105) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71ced1e46fa122261135e49613a200269bb6d8a/pkg/sql/opt/exec/execbuilder/relational.go#L1631)):*
> ```Go
> 	aggregations := *groupBy.Child(1).(*memo.AggregationsExpr)
> 	aggInfos := make([]exec.AggInfo, len(aggregations))
> 	// There will roughly one column or constant argument per aggregation.
> ```

nit: `s/roughly one/roughly be one/`.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-:-O0B7vuP50mjPxMmYkov:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0B74986_2p8fdMwzRn):*
[nit] typo in `espeically`
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1633 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0B7j2593G28kxBJ1fP:-O0B7j2593G28kxBJ1fQ:b-9io70z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71ced1e46fa122261135e49613a200269bb6d8a/pkg/sql/opt/exec/execbuilder/relational.go#L1633)):*
> ```Go
> 	// There will roughly one column or constant argument per aggregation.
> 	argCols := make([]exec.NodeColumnOrdinal, 0, len(aggregations))
> 	constArgs := make(tree.Datums, 0, len(aggregations))
> ```

[super nit] will this potentially cause a regression in the common case when there are no constant arguments? Worth making the allocation lazy when we append?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126141)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0B74986_2p8fdMwzRn):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] typo in `espeically`
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1631 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0Apnlt6FbOY7p94BIG:-O0FF1pABWJR-jfUowqA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71ced1e46fa122261135e49613a200269bb6d8a/pkg/sql/opt/exec/execbuilder/relational.go#L1631)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/roughly one/roughly be one/`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1633 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126141#-O0B7j2593G28kxBJ1fP:-O0FEnHi0-GVWLl154uA:b-uapeg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71ced1e46fa122261135e49613a200269bb6d8a/pkg/sql/opt/exec/execbuilder/relational.go#L1633)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[super nit] will this potentially cause a regression in the common case when there are no constant arguments? Worth making the allocation lazy when we append?
</blockquote></details>

Good call. It improved the benchmark a bit:

```
name                                  old time/op    new time/op    delta
ExecBuild/many-columns-and-indexes-a    1.32µs ±10%    1.24µs ± 2%     ~     (p=0.135 n=5+5)
ExecBuild/many-columns-and-indexes-b    1.73µs ± 0%    1.76µs ± 1%   +1.73%  (p=0.008 n=5+5)
ExecBuild/many-columns-and-indexes-c    22.6µs ± 0%    23.7µs ± 3%   +4.98%  (p=0.016 n=4+5)
ExecBuild/many-columns-and-indexes-d    19.5µs ± 0%    18.9µs ± 2%   -3.06%  (p=0.008 n=5+5)

name                                  old alloc/op   new alloc/op   delta
ExecBuild/many-columns-and-indexes-a    1.15kB ± 0%    1.15kB ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-b    1.44kB ± 0%    1.44kB ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-c    23.4kB ± 0%    23.4kB ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-d    12.1kB ± 0%    11.4kB ± 0%   -5.78%  (p=0.008 n=5+5)

name                                  old allocs/op  new allocs/op  delta
ExecBuild/many-columns-and-indexes-a      14.0 ± 0%      14.0 ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-b      18.0 ± 0%      18.0 ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-c       115 ± 0%       115 ± 0%     ~     (all equal)
ExecBuild/many-columns-and-indexes-d       110 ± 0%        60 ± 0%  -45.45%  (p=0.008 n=5+5)
```

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
