### PR TITLE
sql: Add default_int_size to control INT alias

### PR DESCRIPTION
**Pull request by bobvawter**
This is a follow-up from #32831 to support #26925.

The combination of `default_int_size` interacts with
`experimental_serial_normalization`. Sequence types that are ultimately based
on `unique_rowid()` must always be INT8 types in order to hold the returned
values.  Only in the case where `default_int_size=4
experimental_serial_normalization='sql_sequence'` will an INT4 column be
created in response to a SERIAL type.

Release note (sql change): A new session variable `default_int_size` and
cluster setting `sql.defaults.default_int_size` have been added to control how
the INT and SERIAL types are interpreted. The default value, 8, causes the INT
and SERIAL types to be interpreted as aliases for INT8 and SERIAL8, which have
been the historical defaults for CockroachDB.  PostgreSQL clients that expect
INT and SERIAL to be 32-bit values, can set `default_int_size` to 4, which will
cause INT and SERIAL to be aliases for INT4 and SERIAL4.  Please note that due
to issue #32846, `SET default_int_size` does not take effect until the next
statement batch is executed.

### CODE REVIEW

**Comment by knz** [comment]
please ping me when the other PR merges and this is rebased; I'd prefer to avoid the review until the file list becomes smaller.

**Review by bobvawter — COMMENTED** [review]
PTAL: Rebased against master.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-:-LTNdnrn5GtVJv9ILmho:bitn7w3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
Well done. Just a few minor comments (don't forget to update the release note accordingly).

That said I think some proper treatment of SERIAL is missing here.

Also please emphasize in the release note that this is meant for compatibility with PostgreSQL clients.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-:-LTNh53N-WM79PujzXJA:b-7s4etn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNgNqyDLuyMorz09u0:-LTNgNqyDLuyMorz09u1:bw66y2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/exec_util.go#L87)):*
> ```Go
> // TODO(bob): Remove or n-op this in v2.4: https://github.com/cockroachdb/cockroach/issues/32844
> var defaultIntSize = settings.RegisterValidatedIntSetting(
> 	"sql.default_int_size",
> ```

`sql.defaults.xxx_int_size` for consistency with other settings

with a suitable word for `xxx` -- default, base, naked, whatever
___
*[pkg/sql/vars.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNgyKVAI6oWPJZjbs0:-LTNgyKVAI6oWPJZjbs1:biqhsmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/vars.go#L225)):*
> ```Go
> 	// TODO(bob): Remove or no-op this in v2.4: https://github.com/cockroachdb/cockroach/issues/32844
> 	`default_int_size`: {
> 		Get: func(evalCtx *extendedEvalContext) string {
> ```

Turn this session variable into one configurable using SQL integers; you can follow the model of `extra_float_digits`.
___
*[pkg/sql/parser/parse.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNfusS-5_ghZTlV4Dy:-LTNfusS-5_ghZTlV4Dz:br57gtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/parser/parse.go#L107)):*
> ```Go
> 
> // ParseOne parses a sql statement string, ensuring that it contains only a
> // single statement, and returns that Statement.
> ```

Please extend the comment to justify the choice of int8
___
*[pkg/sql/parser/sql.y, line 6603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNfiBN82uxA-D3STR5:-LTNfiBN82uxA-D3STR6:bsxbzsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/parser/sql.y#L6603)):*
> ```Yacc
>   INT
>   {
>     $$.val = sqllex.(*scanner).nakedIntType
> ```

You need to do something about SERIAL too.

**Review by bobvawter — COMMENTED** [review]
PTAL; comments addressed.  I *think* this is doing the right thing w.r.t. expanding a `SERIAL` column to always fit the `unique_rowid()` function.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-:-LTObfmcCCmbTtydqDaV:buf69yr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/vars.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNgyKVAI6oWPJZjbs0:-LTOYbfN6hY2iMgpxLEr:b-uz2xne) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/vars.go#L225)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Turn this session variable into one configurable using SQL integers; you can follow the model of `extra_float_digits`.
</blockquote></details>

Done. Extracted a common `makeIntGetStringValFn()` per the existing TODO.
___
*[pkg/sql/parser/parse.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNfusS-5_ghZTlV4Dy:-LTO_ZPfA5-8rMcEJpIt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/parser/parse.go#L107)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please extend the comment to justify the choice of int8
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 6603 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNfiBN82uxA-D3STR5:-LTOZo0C63hYbjjV39cV:b2dt64u) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/parser/sql.y#L6603)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to do something about SERIAL too.
</blockquote></details>

Done. Extended the test to show that a SERIAL column is expanded to SERIAL8 to accept the result of `unique_row_id()`.

**Review by bobvawter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32848)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-LTNgNqyDLuyMorz09u0:-LTObxgKCsnEVwxQJreU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/deaa7d8a046da4fa8971d6e761b333c86606291c/pkg/sql/exec_util.go#L87)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`sql.defaults.xxx_int_size` for consistency with other settings

with a suitable word for `xxx` -- default, base, naked, whatever
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
The behavior you observe here with `default_int_size = 4` and SERIAL going to INT8 is OK if and only if you also include a test that demonstrates/exercises that `default_int_size = 4` + `experimental_serial_normalization = sql_sequence` makes `SERIAL` go to `INT4`.

You may then want to add a markdown table in the commit message to enumerate exhaustively what SERIAL expands to depending on the values of `default_int_size` and `serial_normalization`.

PR LGTM after that.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32848#-:-LTU6XvzDUIIEDl_FSxB:b-8pr0ws)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
