### PR TITLE
sql: per-statement statistics, step two

### PR DESCRIPTION
**Pull request by knz**
This PR follows up on #14092 towards #13968.

**sql: track per-statement statistics.**

This patch extends/replaces the previously introduced mechanism that
tracks per-application statistics: statistics are now bucketed by
statement/query instead, but each application has its own set of
buckets (so we collect different stats per application).

Only the statement types that do not implement the (new) interface
`parser.HiddenFromStats` are collected. For example SET and SHOW are
excluded.

The collected data is exposed in the new virtual table
`crdb_internal.stmt_stats`, which replaces the previous `app_stats`
virtual table.

These statistics are only enabled if the environment variable
COCKROACH_SQL_STMT_STATS_ENABLE is set and true.

Also, the data is cleared from memory periodically, at the interval
set by COCKROACH_SQL_STMT_STATS_RESET_INTERVAL, by default set to 1
day.

**sql: track per-statement execution details.**

This patch starts tracking the following details per statement:

- total number of executions
- total number of first attempts (to separate implicit retries)
- maximum observed number of retries
- last error encountered
- average and variance for:
  - total number of rows
  - parse latency
  - logical plan latency
  - execution latency
  - overhead latency (total latency - parse - logical - execution)

The statements are also separately bucketed depending on:
- whether the execution failed with an error
- whether the query was distributed.

(This results in potentially 4 buckets per statement.)

cc @petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14181)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/app_stats.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJs7F8goDwHU621yl8:-KfJs7F8goDwHU621yl9:bk87iga) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L149)):*
> ```Go
> 			select {
> 			case <-ticker.C:
> 				s.resetStats()
> ```

I wonder if we should dump these to the log before resetting. 

---

*[pkg/sql/crdb_internal.go, line 264 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJsNAyIm0bwxKa77Je:-KfJsNAzWODvTa5waL3e:b-dqcc7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/crdb_internal.go#L264)):*
> ```Go
> var crdbInternalStmtStatsTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.stmt_stats (
> ```

To abbreviate or not to abbreviate?

---

*[pkg/sql/executor.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJrnl-I3uj-fReRyZK:-KfJrnl-I3uj-fReRyZL:b-32ajfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/executor.go#L362)):*
> ```Go
> 	// Until per-statement statistics are properly recorded and
> 	// scrubbed, we clear them periodically.
> 	e.stopper.RunWorker(e.sqlStats.getResetWorker(e.stopper))
> ```

That's sort of an odd construction. Normally we'd just call something like `e.sqlStats.resetWorkerLoop(e.stopper)` and have that create a worker goroutine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by dt** [comment]
Reviewed 8 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/app_stats.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMNZN8UpVVZ2K0CwG2:-KfMNZN8UpVVZ2K0CwG3:b-tl623r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L35)):*
> ```Go
> 
> // stmtStats holds per-statement statistics.
> type stmtStats struct {
> ```

I'm fine doing in a followup, but I'd like to switch to a wrapped porto-defined struct as early as possible for holding the actual stats, since separating data from behavior in a normal struct later can get trickier than building it that way from the beginning.

---

*[pkg/sql/app_stats.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMM_2aXLCEq1_MNzpK:-KfMM_2aXLCEq1_MNzpL:b-61p2r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L44)):*
> ```Go
> // statistics.
> var StmtStatsEnable = envutil.EnvOrDefaultBool(
> 	"COCKROACH_SQL_STMT_STATS_ENABLE", false,
> ```

out of scope for this PR but...

env var is fine for things we don't trust yet and want to hide, but in general, I'd like to be able to change settings like this at runtime without editing the startup scripts and rebooting the whole cluster. 

Seems like we should have a system.settings table that nodes can cache for ~1m or something.

---

*[pkg/sql/app_stats.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMKmKrRMPRg6R16cx6:-KfMKmKrRMPRg6R16cx7:bk68egi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L123)):*
> ```Go
> 	for _, a := range s.apps {
> 		a.Lock()
> 		a.stmts = make(map[string]*stmtStats)
> ```

we could potentially size this map based on the old one (e.g. `len(a.stmtStats)/2`) to avoid having to re-grow incrementally after a clear.

---

*[pkg/sql/app_stats.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfML6VWlJYV03hxms99:-KfML6VWlJYV03hxms9A:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L128)):*
> ```Go
> 
> 	// Clear everything.
> 	s.apps = make(map[string]*appStats)
> ```

ditto

---

*[pkg/sql/app_stats.go, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMLEgqGNKTPSBPiDSO:-KfMLEgqGNKTPSBPiDSP:boj5xsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L144)):*
> ```Go
> func (s *sqlStats) getResetWorker(stopper *stop.Stopper) func() {
> 	return func() {
> 		ticker := time.NewTicker(StmtStatsResetFrequency)
> ```

I'm find landing this as-is for now, but I'll probably pull periodic triggering of clearing into the server reporting loop, so we don't risk accidentally clearing right before reporting.

---

*[pkg/sql/app_stats.go, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMOG01I-5l3-Gq-E9b:-KfMOG01I-5l3-Gq-E9c:bu7olkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f580754d2fe1488813ef6438ede26084cdf3de66/pkg/sql/app_stats.go#L129)):*
> ```Go
> // numericStat collect the running values until the mean and variance
> // are required.
> type numericStat struct {
> ```

okay, yeah, now I really want to proto this.

---

*[pkg/sql/executor.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJrnl-I3uj-fReRyZK:-KfMLlL8z7f5oqFb0Wap:b-9yzxtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/executor.go#L362)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That's sort of an odd construction. Normally we'd just call something like `e.sqlStats.resetWorkerLoop(e.stopper)` and have that create a worker goroutine.
</blockquote></details>

ditto above -- this goes away and we pul it into existing worker running a 24h loop in server. feel free to `TODO(dt): remove this` here and above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by knz** [comment]
(will process your other comments in a 2nd round of tweaks)

---

Review status: 4 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/app_stats.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMM_2aXLCEq1_MNzpK:-KfOLAQDNK--7e_Gzc8a:b-uy7a9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L44)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

out of scope for this PR but...

env var is fine for things we don't trust yet and want to hide, but in general, I'd like to be able to change settings like this at runtime without editing the startup scripts and rebooting the whole cluster. 

Seems like we should have a system.settings table that nodes can cache for ~1m or something.
</blockquote></details>

That's it -- not trusted yet, not enabled by default. I envision that the feature will always be enabled later. Added a clarifying comment.

---

*[pkg/sql/app_stats.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMKmKrRMPRg6R16cx6:-KfOLTMz5qNavyC_jJu7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L123)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we could potentially size this map based on the old one (e.g. `len(a.stmtStats)/2`) to avoid having to re-grow incrementally after a clear.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfML6VWlJYV03hxms99:-KfOLhfgIJ0yDvImf9Ul:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L128)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-:-KfOPJSuLbKax4iZvGCG:brqxcaa)*

**Comment by knz** [comment]
Review status: 2 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/app_stats.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMNZN8UpVVZ2K0CwG2:-KfOjIrkDCL8HJGy7kE2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L35)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm fine doing in a followup, but I'd like to switch to a wrapped porto-defined struct as early as possible for holding the actual stats, since separating data from behavior in a normal struct later can get trickier than building it that way from the beginning.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMLEgqGNKTPSBPiDSO:-KfO_L-72WbrnsBT4kTC:bjjk3h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L144)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm find landing this as-is for now, but I'll probably pull periodic triggering of clearing into the server reporting loop, so we don't risk accidentally clearing right before reporting.
</blockquote></details>

Let's talk more; I have a feeling we'll be more happy all around if we were to persist this data in a SQL table rather than our ts database. In which case, we'd issue a sql transaction here, at this custom interval. Then the reporting loop (actually the update loop, running once a day) can pick up the data to send from this SQL table.

---

*[pkg/sql/app_stats.go, line 149 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJs7F8goDwHU621yl8:-KfOYAf6IOYZd8GF2Td1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/app_stats.go#L149)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we should dump these to the log before resetting. 
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 129 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfMOG01I-5l3-Gq-E9b:-KfOjJbyKEnV5q6XZ_1B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f580754d2fe1488813ef6438ede26084cdf3de66/pkg/sql/app_stats.go#L129)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

okay, yeah, now I really want to proto this.
</blockquote></details>

Done.

---

*[pkg/sql/crdb_internal.go, line 264 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJsNAyIm0bwxKa77Je:-KfOjL8Rbq4fg2e9lXD1:b-u6u07n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/crdb_internal.go#L264)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

To abbreviate or not to abbreviate?
</blockquote></details>

Not to. Done.

---

*[pkg/sql/executor.go, line 362 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfJrnl-I3uj-fReRyZK:-KfOWUdvMz5jXAOrcNUK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1975ff05559801931ea7d7334957bd1279f9a1c/pkg/sql/executor.go#L362)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto above -- this goes away and we pul it into existing worker running a 24h loop in server. feel free to `TODO(dt): remove this` here and above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by petermattis** [comment]
Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/app_stats.proto, line 42 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOr_jl9OnQYm0XS3R8:-KfOr_jmXINCx0fKtw82:b-vfa1g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L42)):*
> ```protobuf
>   optional int64 MaxRetries = 3  [(gogoproto.nullable) = false];
> 
>   // LastError collects the last error encountered.
> ```

`s/LastError/LastErr/g`

---

*[pkg/sql/app_stats.proto, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOrb_-2oB6zQ0kdKFg:-KfOrb_-2oB6zQ0kdKFh:b-f06ya1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L51)):*
> ```protobuf
>   optional NumericStat ParseLat = 6  [(gogoproto.nullable) = false];
>   optional NumericStat PlanLat	= 7  [(gogoproto.nullable) = false];
>   optional NumericStat RunLat	= 8  [(gogoproto.nullable) = false];
> ```

Tabs on the above lines.

Also, looking at this again, the terms `Run` and `Execute` are too similar. I'm not sure (without looking at the code) what they refer to. I think one needs to be renamed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by dt** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/app_stats.proto, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOqu_VoxsQ9ZrAN6NI:-KfOqu_VoxsQ9ZrAN6NJ:bepj0pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L26)):*
> ```protobuf
>   // Count is the total number of times this statement was executed
>   // since the begin of the reporting period.
>   optional int64 Count = 1  [(gogoproto.nullable) = false];
> ```

These don't need to be capitalized and usually aren't -- the generated Go code will cap them for us.

---

*[pkg/sql/app_stats.proto, line 36 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOr1kLHGd1hv-4DPeC:-KfOr1kLHGd1hv-4DPeD:b-u4xdnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L36)):*
> ```protobuf
>   // The cumulative number of retries can be computed with
>   // count - firstAttemptCount.
>   optional int64 FirstAttemptCount = 2  [(gogoproto.nullable) = false];
> ```

we usually snake_case proto field names -- again, generated Go code will convert to more idiomatic CamelCase identifiers.

---

*[pkg/sql/app_stats.proto, line 50 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOrW76blMe9B-5Eik3:-KfOrW76blMe9B-5Eik4:b-gfq4fo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L50)):*
> ```protobuf
>   // phase latencies.
>   optional NumericStat ParseLat = 6  [(gogoproto.nullable) = false];
>   optional NumericStat PlanLat	= 7  [(gogoproto.nullable) = false];
> ```

is that a tab? spaces in protos.

---

*[pkg/sql/crdb_internal.go, line 264 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOozvt1xzszqJk8vmq:-KfOozvurvacaWM35dlM:b-jx6oy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/crdb_internal.go#L264)):*
> ```Go
> var crdbInternalStmtStatsTable = virtualSchemaTable{
> 	schema: `
> CREATE TABLE crdb_internal.statement_statistics (
> ```

nit: I'm slightly apprehensive of presenting the node-specific, unaggregated stats directly to users via SQL. Getting different answers depending on what node you ask (e.g. behind a load-balancer) seems like a ux-surprise.

I understand that this is a step towards some form of aggregation that can come later, it just seems that surfacing this intermediate step in SQL, a medium where we _usually_ are consistent (thanks to being on top of a common kv) has the potential to be surprising.

my concerns would be mostly assuaged by something as simple as making it obvious what it is, e.g. `node_statement_statistics`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by knz** [comment]
Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/app_stats.proto, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOqu_VoxsQ9ZrAN6NI:-KfSTZ1AluG6WdtHxfyg:b-1rypy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L26)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

These don't need to be capitalized and usually aren't -- the generated Go code will cap them for us.
</blockquote></details>

I had forgotten. Thanks for the reminder.

---

*[pkg/sql/app_stats.proto, line 36 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOr1kLHGd1hv-4DPeC:-KfSTadkGOzE9RBmA_J6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L36)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we usually snake_case proto field names -- again, generated Go code will convert to more idiomatic CamelCase identifiers.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.proto, line 42 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOr_jl9OnQYm0XS3R8:-KfSTb9SFMYFpF6ywQb6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/LastError/LastErr/g`
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.proto, line 50 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOrW76blMe9B-5Eik3:-KfSTb_mhuitd_3cDVxW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L50)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

is that a tab? spaces in protos.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.proto, line 51 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOrb_-2oB6zQ0kdKFg:-KfSTc8ZZxYbMa0YNU2k:b-lpeby7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/app_stats.proto#L51)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Tabs on the above lines.

Also, looking at this again, the terms `Run` and `Execute` are too similar. I'm not sure (without looking at the code) what they refer to. I think one needs to be renamed. 
</blockquote></details>

"exec" senamed to "service latency", added comments too.

---

*[pkg/sql/crdb_internal.go, line 264 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181#-KfOozvt1xzszqJk8vmq:-KfSWf4h6X1wC2ukFnFR:bg5lhpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc7eeb584346a304e5753817715f1c73eb9870a/pkg/sql/crdb_internal.go#L264)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: I'm slightly apprehensive of presenting the node-specific, unaggregated stats directly to users via SQL. Getting different answers depending on what node you ask (e.g. behind a load-balancer) seems like a ux-surprise.

I understand that this is a step towards some form of aggregation that can come later, it just seems that surfacing this intermediate step in SQL, a medium where we _usually_ are consistent (thanks to being on top of a common kv) has the potential to be surprising.

my concerns would be mostly assuaged by something as simple as making it obvious what it is, e.g. `node_statement_statistics`.
</blockquote></details>

Of the other 4 tables in `crdb_internal` currently, 3 are already node-local (all but `tables`). All of them (including `table`) are guaranteed to not need access to the cluster to deliver a respone, and that's a feature. I think there is a case to be made to expose node-specific data via SQL, even if we have to gate it behind a big warning sign.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14181)*

**Comment by knz** [comment]
Please suggest what remains to be done here in light of today's discussion :)

**Comment by dt** [comment]
documenting our discussion this morning:
* we should make it clearer these are node-specific (add node_id col, maybe prefix the tables with node_).
* this PR is about metrics collection, not aggregation or persistence, which are still TBD.
* IMO the value removal here serves to canonicalize queries for the purposes of bucketing, but is not sufficient sanitation to make it safe to upload them to cockroach labs: table and column names could easily be considered sensitive / proprietary info, so we'll want to another sanitizer in the reporting side that cleans those up. There's likely some overlap with the tabledescriptor sanitizer there. This concern doesn't block merging this PR or anything relating to collection at all, just the followup reporting work.

**Comment by knz** [comment]
I have renamed the other crdb_internal tables as suggested.

Note: value removal will occur in a subsequent PR. For now the bucketing includes the values. This is why the feature is currently gated.

**Comment by dt** [comment]
👍

**Comment by knz** [comment]
Thanks!

**Pull request merged**
