### PR TITLE
build: mark some libraries as being `testonly`

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: none
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
Yes!!!!!

**Comment by rickystewart** [comment]
bors r=rail

**Review by mgartner — APPROVED** [review]
Cool! I'm curious to know what the benefit of this is. `pkg/sql/opt/bench`, `pkg/sql/opt/testutils/testcat`, and `pkg/sql/opt/testutils/testexpr` are good candidates as well. I'm happy to add those in another PR, too, whatever you'd prefer.

**Comment by rickystewart** [comment]
> I'm curious to know what the benefit of this is. 

The build system will flat-out refuse to link a `testonly` library like these into a library or binary that is not itself marked as `testonly`. So these libraries CANNOT be linked into `cockroach{,-short,-sql}`, for example, and this invariant is always satisfied without us having to write separate `disallowed_imports_test`s for all of these libraries or similar. Furthermore the build won't even start if you try to introduce a `testonly` dependency from a non-`testonly` library and since it fails immediately, you won't waste any time barking up the wrong tree should you make an error in local development.

> I'm happy to add those in another PR, too, whatever you'd prefer.

Yes, definitely, go ahead. Just keep an eye on CI to make sure nothing breaks because just because something "should" be `testonly` doesn't mean that it is in fact.

**Pull request merged**
