### PR TITLE
kvserver: modernize TestAcceptsUnsplitRanges

### PR DESCRIPTION
**Pull request by andrewbaptist**
This commit changes the if err blocks to require.NoError for most of the checks. The only minor functional change is not unnecessarily looping waiting for the ConfReader to be available as SpanConfigs are disabled for the test store and therefore this never returns an error.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
I'm splitting out some of the "non-concerning" parts of the larger PR to get them into 23.2 since I'm not going to push the bigger one.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111932#-:-Ng5I-b0AkFbU4VD2HtH:b593vm9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Comment by andrewbaptist** [comment]
bors r=kvoli

TFTR!

**Comment by andrewbaptist** [comment]
bors retry

**Pull request merged**
