### PR TITLE
builtins: teach pg_get_userbyid & pg_catalog about the node user

### LINKED ISSUE #98760: sql,cli: \l shows unknown owner of the system database
**Describe the problem**

On master, the `\l` command shows the owner of the `system` database as `unknown`. `SHOW DATABASES` shows the expected output:

```
root@localhost:26257/defaultdb> \l                                                                                                                                                                                                                           
List of databases:
    Name    |          Owner           | Encoding |  Collate   |   Ctype    | Access privileges
------------+--------------------------+----------+------------+------------+--------------------
  defaultdb | root                     | UTF8     | en_US.utf8 | en_US.utf8 |
  postgres  | root                     | UTF8     | en_US.utf8 | en_US.utf8 |
  system    | unknown (OID=3233629770) | UTF8     | en_US.utf8 | en_US.utf8 |
(3 rows)

root@localhost:26257/defaultdb> SHOW DATABASES;                                                                                                                                                                                                              
  database_name | owner | primary_region | secondary_region | regions | survival_goal
----------------+-------+----------------+------------------+---------+----------------
  defaultdb     | root  | NULL           | NULL             | {}      | NULL
  postgres      | root  | NULL           | NULL             | {}      | NULL
  system        | node  | NULL           | NULL             | {}      | NULL
(3 rows)
```

On 22.2, both commands show `node` as the owner.


Jira issue: CRDB-25504

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/98760

The node user is the owner of the system database. For safety reasons,
the node user cannot be used externally, so it doesn't exist in the
system.users table. This was making it impossible to do introspection on
the node user through pg_catalog and pg_builtin functions.

Now the node user will appear in pg_catalog tables like pg_roles, so the
introspection will work.

Release note (bug fix): Fixed a bug where the internal `node` pseudo-role
was not viewable through introspection of pg_catalog tables.

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
LGTM mod the failed tests which seems straight forward to do a rewrite.

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
blathers backport 23.1

**Pull request merged**
