### PR TITLE
settings: introduce system.tenant_settings table

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of implementing the multi-tenant cluster settings RFC #73349. I was planning to post it along with more of the implementation but I'm posting it earlier for visibility, in case we need to make decisions related to system table IDs.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
Thanks for sharing this. I took a look at it and read the RFCs. Would it be unreasonable to ask to not merge this until the first week of February? As it turns out, we'll be actively working on dynamic system table IDs next week. Your table could, in fact, be quite suitable for testing that it works, and this PR is basically ready to go as it is.

**Comment by RaduBerinde** [comment]
Yes, no problem. I can work on all the other pieces without merging this now.

**Comment by postamar** [comment]
Thanks Radu. We'll keep you posted!

**Comment by ajwerner** [comment]
I'm rebasing this and playing with getting it a dynamic ID now.

**Comment by RaduBerinde** [comment]
Closing in favor of #76313.

**Pull request closed without merging**
