### PR TITLE
storage: change the comparer and time bounds collector to handle Engi…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…neKeys

- Rename MVCCComparer to PebbleComparer. PebbleComparer is changed to
  handle EngineKeys.
- Add GetKeyPartFromEngineKey for callers that don't care about the
  version.
- Fix pebbleTimeBoundPropCollector to handle EngineKeys.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-:-MMLYeW86MJLnbGOK9k7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-MMLYQkUAN8cGKegur-C:-MMLYQkUAN8cGKegur-D:b-ed7jmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bbae635dba5b1942d0fdda849918a4ad33c5d5/pkg/storage/pebble.go#L115)):*
> ```Go
> // PebbleComparer is a pebble.Comparer object that implements MVCC-specific
> // comparator settings for use with Pebble.
> var PebbleComparer = &pebble.Comparer{
> ```

How do you feel about naming this just `Comparer`? I don't feel strongly about this suggestion, it just felt a little surprising to see the name `Pebble` showing up everywhere this is used.
___
*[pkg/storage/pebble.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-MMLYGNL6yepbJpu3ir-:-MMLYGNL6yepbJpu3ir0:bif64f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bbae635dba5b1942d0fdda849918a4ad33c5d5/pkg/storage/pebble.go#L190)):*
> ```Go
> 			return len(k)
> 		}
> 		// Pebble and RocksDB require that keys generated via a split be
> ```

Nit: we can remove the RocksDB mention now.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-:-MMS5ikA1urBdVj6Ca4l:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/pebble.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-MMLYQkUAN8cGKegur-C:-MMS5FVt8h7MT0jlCDRm:bplydij) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bbae635dba5b1942d0fdda849918a4ad33c5d5/pkg/storage/pebble.go#L115)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How do you feel about naming this just `Comparer`? I don't feel strongly about this suggestion, it just felt a little surprising to see the name `Pebble` showing up everywhere this is used.
</blockquote></details>

I've renamed it `EngineComparer`, since `Comparer` did not seem specific enough, though one could argue that `storage.Comparer` is specific enough for references outside the package.
___
*[pkg/storage/pebble.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-MMLYGNL6yepbJpu3ir-:-MMS4vT-BBHX7AYTtpms:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bbae635dba5b1942d0fdda849918a4ad33c5d5/pkg/storage/pebble.go#L190)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: we can remove the RocksDB mention now.
</blockquote></details>

Done

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56752)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56752#-MMLYQkUAN8cGKegur-C:-MMS6b_74qgTRUizx7Si:bvtn2si) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bbae635dba5b1942d0fdda849918a4ad33c5d5/pkg/storage/pebble.go#L115)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've renamed it `EngineComparer`, since `Comparer` did not seem specific enough, though one could argue that `storage.Comparer` is specific enough for references outside the package.
</blockquote></details>

Ack. That works for me.

**Pull request merged**
