### PR TITLE
ui: upgrade to prettier 2.x

### PR DESCRIPTION
**Pull request by sjbarag**
Prettier 2.x includes backwards-incompatible formatting changes (namely:
the default values of a few settings changed), but critically adds
support for TypeScript 3.8 language features like 'import type', 'export
type', etc. Type-only imports will be necessary to enable
--isolatedModules during TypeScript compilation, which is a requirement
for building with esbuild (particularly via esbuild-loader). Upgrade
cluster-ui and db-console to prettier 2.6.2, applying the 1.x config
values where possible to minimize the number of changes.

### CODE REVIEW

**Comment by sjbarag** [comment]
> to minimize the number of changes
> +26,522 -3,020

[I found this gif outside, can I keep it?](https://gfycat.com/wetidolizedgrayling)

**Review by fantapop — COMMENTED** [review]
I've never actually used this but always found it to be tantalizing: https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame If the changes are mainly formatting, I'd recommend looking into it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82424#-:-N3fPWwX0RSVKaBMIoYj:b-unjl45)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Comment by sjbarag** [comment]
> I've never actually used this but always found it to be tantalizing: https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame If the changes are mainly formatting, I'd recommend looking into it.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82424#-:-N3fPWwX0RSVKaBMIoYj:b-unjl45)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

Agreed! There's a thread in `#dev-inf` talking about exactly that technique, and setting it up in the `githooks/post-checkout` hook so it's automatic 😄

**Review by fantapop — COMMENTED** [review]
:thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82424#-:-N3fW-uH6Of6l0tLkBUd:b4c9lyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 124 of 124 files at r2, 111 of 111 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82424)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

**Review by lassenordahl — APPROVED** [review]

**Pull request merged**
