### PR TITLE
sql: move interleaved join planning in the optimizer

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: consolidate exec factory scan parameters in a struct

This is a mechanical change that moves the myriad of `ConstructScan`
arguments into an `exec.ScanParams` struct.

Release note: None

#### sql: move interleaved join planning in the optimizer

The distsql planner can convert merge joins to interleave joins. This
logic is fragile (e.g. it prevents some unrelated scanNode cleanup)
and would need to be duplicated by the new factory.

This change moves the logic that decides whether to build an
interleaved join to the execbuilder. Longer term, we will want the
rest of the optimizer to be aware of interleaved joins and cost them
differently.

Unit tests targeting this planning decision have been converted to
execbuilder logictests. We also add a session variable that controls
interleaved joins (with default value controlled by the existing
cluster setting).

Release note (sql change): Interleaved table joins now show up in
EXPLAIN (PLAN).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for working on this! It looks a lot better now. I just have some nits.

> Reviewed 6 of 6 files at r1, 24 of 24 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-:-MCJ7ips2A6PTFoQcGj8:b-cbrqos)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_plan_join_test.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ7bx-8ii4ZmmZt2SO:-MCJ7bx0BlSisSP1YZcs:bw6cb71) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17d51cd1a6ac6d3a3000bf4508fa6757d0b826/pkg/sql/distsql_plan_join_test.go#L329)):*
> ```Go
> 	// doesn't get planned as an interleaved table join, even if the
> 	// non-interleaved column is constant and is given a merge join ordering.
> 	t.Run("MismatchedJoin", func(t *testing.T) {
> ```

Has this test been also translated?
___
*[pkg/sql/distsql_spec_exec_factory.go, line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ2nQg0KnZLB50STu4:-MCJ2nQg0KnZLB50STu5:brjlwil) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/distsql_spec_exec_factory.go#L399)):*
> ```Go
> }
> 
> // TODO(yuzefovich): move the decision whether to use an interleaved join from
> ```

nit: this TODO can now be removed, thanks for addressing it :)
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ3on-EBhmdPUCSKQj:-MCJ3on-EBhmdPUCSKQk:bnu3x9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/execinfrapb/processors_sql.proto#L706)):*
> ```protobuf
>   }
> 
> 	// The tables can be in any order. The processor figures out internally the
> ```

super nit: seems like indentation is with tabs.
___
*[pkg/sql/opt/cat/utils.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ4EGV0cY5xP33h9bD:-MCJ4EGV0cY5xP33h9bE:b11muku) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/opt/cat/utils.go#L366)):*
> ```Go
> 	case aCount > bCount:
> 		a, b = b, a
> 		aCount, bCount = bCount, aCount
> ```

nit: rather than switching `aCount` and `bCount` it might be more clear to have a separate variable for `ancestorIdxID` or something.
___
*[pkg/sql/opt/exec/factory.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ1maMC-wQXOE5SJ-f:-MCJ1maMC-wQXOE5SJ-g:bq3xf16) ([raw file](https://github.com/cockroachdb/cockroach/blob/33c5cc94709db1fcb7da549c7bac511edea05e9e/pkg/sql/opt/exec/factory.go#L581)):*
> ```Go
> 
> 	// If non-zero, the scan may still be required to return up to all its rows
> 	// (or up to the HardLimit if it is set0, but can be optimized under the
> ```

nit: `s/set0/set/`.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1034 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ5Wxe1lgyDg-jh58s:-MCJ5Wxe1lgyDg-jh58t:b-jn1roq) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/opt/exec/execbuilder/relational.go#L1034)):*
> ```Go
> 		}
> 	}
> 	if joinType == sqlbase.LeftSemiJoin || joinType == sqlbase.LeftAntiJoin {
> ```

nit: we have `sqlbase.JoinType.ShouldIncludeRightColsInOutput()` method for this.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-:-MCJMXx_B8E8bwWdQMcF:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsql_plan_join_test.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ7bx-8ii4ZmmZt2SO:-MCJCzIo5PmE5WSfaLYN:b-yyl0ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17d51cd1a6ac6d3a3000bf4508fa6757d0b826/pkg/sql/distsql_plan_join_test.go#L329)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Has this test been also translated?
</blockquote></details>

Good catch, ddin't notice there was another subtest. Added to execbuilder test.
___
*[pkg/sql/execinfrapb/processors_sql.proto, line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ3on-EBhmdPUCSKQj:-MCJGKHq5aHoGB9hTk4Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/execinfrapb/processors_sql.proto#L706)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: seems like indentation is with tabs.
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/utils.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-MCJ4EGV0cY5xP33h9bD:-MCJJYk2E1ZzUgqBFhl7:b-hfhvcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/85667ae5d0c3b459b2a3abc78bbdd2067fa6cfea/pkg/sql/opt/cat/utils.go#L366)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: rather than switching `aCount` and `bCount` it might be more clear to have a separate variable for `ancestorIdxID` or something.
</blockquote></details>

Reworked it and added a comment.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51469#-:-MCJYwB25IyQ10Q8mrtA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Pull request merged**
