### PR TITLE
kvserver/tenantrate: add slow logging and vmodule logging around Acquire

### PR DESCRIPTION
**Pull request by ajwerner**
Note that it will show up in tracing if tracing is enabled. 

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53133#-:-MFBjjot2QosBBKAq9e3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/tenantrate/limiter.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53133#-MFBiyxd4_MU2ZNSq-Mk:-MFBiyxd4_MU2ZNSq-Ml:bc7m1fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c20c4ac45076d814d479fc08918067693cea1b2/pkg/kv/kvserver/tenantrate/limiter.go#L114)):*
> ```Go
> 	) (onAcquire func()) {
> 		return func() {
> 			now := timeutil.Now()
> ```

Why not use `timeutil.Since(start)` as above?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53133)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/kv/kvserver/tenantrate/limiter.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53133#-MFBiyxd4_MU2ZNSq-Mk:-MFBkA1gBioH_k-yGeKI:b-d215un) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c20c4ac45076d814d479fc08918067693cea1b2/pkg/kv/kvserver/tenantrate/limiter.go#L114)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not use `timeutil.Since(start)` as above?
</blockquote></details>

I was just optimizing accesses to the clock given I needed to access it for the log.Every

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53133)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/tenantrate/limiter.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53133#-MFBiyxd4_MU2ZNSq-Mk:-MFBlExLB-BZLtp-NWiv:b-bqlyif) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c20c4ac45076d814d479fc08918067693cea1b2/pkg/kv/kvserver/tenantrate/limiter.go#L114)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was just optimizing accesses to the clock given I needed to access it for the log.Every
</blockquote></details>

Gotcha, missed the use of `now` there

**Comment by ajwerner** [comment]
Closing as stale

**Pull request closed without merging**
