### PR TITLE
sql: table-level CHECK constraints

### PR DESCRIPTION
**Pull request by dt**
All col-level CHECKs are hoisted up to table-level during table creation,
essentially rendering the column qualifier shorthand for a table definition
element, much like the handling of UNIQUE.

This allows a single implementation to handle constraints thereafter,
rather than treating col-level and table-level differently.

This means `SHOW CREATE TABLE` is not a perfect round-trip of the original
`CREATE`stmt, since the `CHECK` doesn't appear with the column, but the
created table is functionally the same.

Also this change _doesn't_ handle existing col-level CHECKs.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6625)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/sqlbase/structured.proto, line 59 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHUtDGI0qwprtHYMAoU:-KHUtDGJXE8JsUpQ6wQ5:-505043033) ([raw file](https://github.com/cockroachdb/cockroach/blob/be280e744c8b0747a36fe0dc938c85f82ed00d9b/sql/sqlbase/structured.proto#L59)):*
> ```protobuf
>   optional string default_expr = 5;
>   optional bool hidden = 6 [(gogoproto.nullable) = false];
>   optional string check_expr = 7;
> ```

this will require a mention in release notes, but I think I'm okay not maintaining a bunch of migration code for something that isn't really functional yet (e.g. not used during UPDATE, renames, etc).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625)*

**Comment by mjibson** [comment]
Reviewed 2 of 10 files at r1.
Review status: 2 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 346 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWVR3KlzOaeVKvk1t7:-KHWVR3KlzOaeVKvk1t8:-1224984483) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L346)):*
> ```Go
> 				qval.datum = rowVals[ri]
> 			} else {
> 				qval.datum = parser.DNull
> ```

I don't understand what this change and the corresponding `d != parser.DNull` below is supposed to do. What's the problem it's solving?

---

*[sql/insert.go, line 512 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWWgtlA13M_j0sOYmw:-KHWWgtlA13M_j0sOYmx:170689705) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L512)):*
> ```Go
> 	checkExprs := make([]parser.Expr, 0, len(checks))
> 	for _, check := range checks {
> 		expr, err := parser.ParseExprTraditional(check)
> ```

Should this use the session syntax mode instead? Maybe for another PR...

---

*[sql/insert.go, line 516 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWWzdRLba5DvEo_iSi:-KHWWzdRLba5DvEo_iSj:864086795) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L516)):*
> ```Go
> 			return nil, err
> 		}
> 		checkExprs = append(checkExprs, expr)
> ```

Why are we using append here when `checkExprs[i]` is faster? The `make` can remove its second argument too. Could be another PR.

---

*[sql/show_test.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHW_u94SFkzxEMOpbMd:-KHW_u94SFkzxEMOpbMe:1977366090) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/show_test.go#L50)):*
> ```Go
> 	v FLOAT NOT NULL,
> 	t TIMESTAMP DEFAULT NOW(),
> 	CHECK (i > 0)
> ```

Could we also test: `CONSTRAINT c CHECK (i > )`
I'm not sure the current code handles a named CHECK constraint correctly.

---

*[sql/parser/create.go, line 349 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWa3gCOoMsTZsXOPlD:-KHWa3gCOoMsTZsXOPlE:312034415) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/parser/create.go#L349)):*
> ```Go
> 		fmt.Fprintf(buf, "CONSTRAINT %s ", node.name)
> 	}
> 	buf.WriteByte('(')
> ```

Do we need the work `CHECK` here?

---

*[sql/sqlbase/structured.proto, line 59 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHUtDGI0qwprtHYMAoU:-KHWXwZKBbbqxkSFcqOy:677042770) ([raw file](https://github.com/cockroachdb/cockroach/blob/be280e744c8b0747a36fe0dc938c85f82ed00d9b/sql/sqlbase/structured.proto#L59)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> this will require a mention in release notes, but I think I'm okay not maintaining a bunch of migration code for something that isn't really functional yet (e.g. not used during UPDATE, renames, etc).</details>
SGTM

---

*[sql/testdata/check_constraints, line 52 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWYjt9SWdpqBAPoUg5:-KHWYjt9SWdpqBAPoUg6:1904551643) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/testdata/check_constraints#L52)):*
> ```
> 
> # Verify we don't accept COUNT(*)
> statement error not allowed in constraint
> ```

This is only part of the error message. Can we include the full message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625)*

**Comment by dt** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/insert.go, line 346 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWVR3KlzOaeVKvk1t7:-KHWcKfrtkfXWtZ3Lv4v:-1360211363) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L346)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I don't understand what this change and the corresponding `d != parser.DNull` below is supposed to do. What's the problem it's solving?</details>
As mentioned in commit, this PR also changes handling of NULL to match other DBs as discussed in #6599,
specifically a CHECK expression must evaluate to `true` *or null* to succeed.

---

*[sql/insert.go, line 512 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWWgtlA13M_j0sOYmw:-KHWcPhI9DGDqOphLzMS:-2119391243) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L512)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Should this use the session syntax mode instead? Maybe for another PR...</details>
Hm, or maybe of the session used to CREATE TABLE? Either way, yeah, punt to stand-alone change. 

---

*[sql/insert.go, line 516 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWWzdRLba5DvEo_iSi:-KHX-XmtHur9XpGeh9QS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L516)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why are we using append here when `checkExprs[i]` is faster? The `make` can remove its second argument too. Could be another PR.</details>
Done.

---

*[sql/show_test.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHW_u94SFkzxEMOpbMd:-KHX-aINpmO4QTmyzxhv:1130124724) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/show_test.go#L50)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Could we also test: `CONSTRAINT c CHECK (i > )`
> I'm not sure the current code handles a named CHECK constraint correctly.</details>
The current code certainly doesnt -- I was initially just wanting to move the existing checks to table level in this PR and add new functionality later, but looking at it, it probably makes sense (since it changes the TableDesc proto) to add it now.

Done.

---

*[sql/parser/create.go, line 349 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWa3gCOoMsTZsXOPlD:-KHX0LFkji5O_fE8443z:50514319) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/parser/create.go#L349)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Do we need the work `CHECK` here?</details>
Huh. Probably. Done. Where is this called anyway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625)*

**Comment by mjibson** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/insert.go, line 512 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWWgtlA13M_j0sOYmw:-KHYsnClY7O9R1oqhShI:-536372050) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/insert.go#L512)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Hm, or maybe of the session used to CREATE TABLE? Either way, yeah, punt to stand-alone change. </details>
I added #6645 to track this.

---

*[sql/parser/create.go, line 349 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWa3gCOoMsTZsXOPlD:-KHYt1oHQgaXb3E7CV2Y:1975670696) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/parser/create.go#L349)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Huh. Probably. Done. Where is this called anyway?</details>
Not sure. Dug around with guru for a bit. It's used in some panic messages and EXPLAINs, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625)*

**Comment by dt** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/check_constraints, line 52 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-KHWYjt9SWdpqBAPoUg5:-KHaBBmAybA9rC5As-5m:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db7e2ab60f7cae52ceb27abbf01f861dac87fc08/sql/testdata/check_constraints#L52)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> This is only part of the error message. Can we include the full message?</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625)*

**Comment by mjibson** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> #### sql: table\-level CHECK constraints
> 
> All col-level CHECKs are hoisted up to table-level during table creation,
> 
> essentially rendering the column qualifier shorthand for a table definition
> 
> element, much like the handling of UNIQUE.
> 
> 
> 
> This allows a single implementation to handle constraints thereafter,
> 
> rather than treating col-level and table-level differently.
> 
> 
> 
> This means `SHOW CREATE TABLE` is not a perfect round-trip of the original
> 
> `CREATE`stmt, since the `CHECK` doesn't appear with the column, but the
> 
> created table is functionally the same.
> 
> 
> 
> Also this change *doesn't* handle existing col-level CHECKs.
> 
> 
> </details>


---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6625#-:-KHaYq7QhdXVCS8L8H2s:1417088721)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/280

**Pull request merged**
