### PR TITLE
stylus lint

### PR DESCRIPTION
**Pull request by maxlang**
Add linting for stylus. I'm open to discussing the config.

### CODE REVIEW

**Comment by maxlang** [comment]
oops brought in nav stuff

**Comment by tamird** [comment]
why close? just rebase that stuff out

**Comment by maxlang** [comment]
I'm waiting for tests to pass to merge the navbar stuff, since this depends on it. Is there a way around that?

**Comment by tamird** [comment]
the trivial solution is also fine: "plz review only the last commit".

**Comment by maxlang** [comment]
ah k

**Pull request closed without merging**
