### PR TITLE
admission: refactor disk bandwidth consumption

### PR DESCRIPTION
**Pull request by CheranMahalingam**
Refactor to reduce complexity of disk bandwidth plumbing and disk monitoring logic.

Epic: None.
Release note: None.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122689)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @CheranMahalingam, @jbowens, and @nkodali)

___
*[`pkg/kv/kvserver/stores.go` line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122689#-NwLdPtpECPil2jxqFhF:-NwLdPtpECPil2jxqFhG:ba2qdik) ([raw file](https://github.com/cockroachdb/cockroach/blob/88da86fd5eff69879231524f1d136493d56ace08/pkg/kv/kvserver/stores.go#L305)):*
> ```Go
> 	return err
> }
> ```

nit: // DiskStatsMonitor abstracts disk.Monitor for testing purposes.
___
*[`pkg/server/node.go` line 1103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122689#-NwLft8y6nxfuPowUcXY:-NwLft8y6nxfuPowUcXZ:bm1z2w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88da86fd5eff69879231524f1d136493d56ace08/pkg/server/node.go#L1103)):*
> ```Go
> }
> 
> func (dsm *diskStatsMap) initDiskStatsMap(
> ```

I was imagining something like the following that would allow us to continue testing `initDiskStatsMap` in `TestDiskStatsMap`.


```
// monitorManagerInterface abstracts disk.MonitorManager for testing.
type monitorManagerInterface interface {
	Monitor(path string) (kvserver.DiskStatsMonitor, error)
}

func (dsm *diskStatsMap) initDiskStatsMap(
	specs []base.StoreSpec, engines []storage.Engine, diskManager monitorManagerInterface) {
...	
}
```

Test code:
```
type testDiskStatsMonitorManager struct {
	monitors map[string]*testDiskStatsMonitor
}

func (mm *testDiskStatsMonitorManager) Monitor(path string) (kvserver.DiskStatsMonitor, error) {
	m, ok := mm.monitors[path]
	if ok {
		return m, nil
	}
	return nil, errors.Errorf("not found ...")
}

```

**Review by CheranMahalingam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122689)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, @nkodali, and @sumeerbhola)

___
*[`pkg/server/node.go` line 1103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122689#-NwLft8y6nxfuPowUcXY:-NwMKpOSBbTh44nv_Czw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88da86fd5eff69879231524f1d136493d56ace08/pkg/server/node.go#L1103)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was imagining something like the following that would allow us to continue testing `initDiskStatsMap` in `TestDiskStatsMap`.


```
// monitorManagerInterface abstracts disk.MonitorManager for testing.
type monitorManagerInterface interface {
	Monitor(path string) (kvserver.DiskStatsMonitor, error)
}

func (dsm *diskStatsMap) initDiskStatsMap(
	specs []base.StoreSpec, engines []storage.Engine, diskManager monitorManagerInterface) {
...	
}
```

Test code:
```
type testDiskStatsMonitorManager struct {
	monitors map[string]*testDiskStatsMonitor
}

func (mm *testDiskStatsMonitorManager) Monitor(path string) (kvserver.DiskStatsMonitor, error) {
	m, ok := mm.monitors[path]
	if ok {
		return m, nil
	}
	return nil, errors.Errorf("not found ...")
}

```
</blockquote></details>

Done.

**Review by CheranMahalingam — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122689#-:-NwMNV5A3bqIKs6nYEd_:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, @nkodali, and @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122689#-:-NwMUnNFCsOf2Db70oOu:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, and @nkodali)

**Comment by CheranMahalingam** [comment]
bors r=sumeerbhola

**Pull request merged**
