### PR TITLE
acceptance/chaos: always unlock via `defer`

### PR DESCRIPTION
**Pull request by tamird**
I don't know what's been up with this test lately, just hoping for the best at this point.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4388)

### CODE REVIEW

**Comment by tschottdorf** [comment]
seems random. Does this happen locally as well? Should be easy enough to `killall -3 acceptance.test` and see where it's stuck. I remember there were numerous issues about clients never becoming healthy (this never giving the lock back).

**Comment by bdarnell** [comment]
Has this been failing since #4356? There are no early returns in the changes here, which means that `defer unlock()` can only help in the presence of a recovered panic, and I don't think there are any `recover()` calls in play here.

**Comment by vivekmenezes** [comment]
I've made substantive changes to this test in https://github.com/cockroachdb/cockroach/pull/4392 out for review. I'm happy to take over this PR and merge it in later after that one is in.

**Comment by tamird** [comment]
Superceded by #4392

**Pull request closed without merging**
