### PR TITLE
row: bugfixes to cfetcher

### LINKED ISSUE #38609: exec: panic when selecting from crdb_internal.zones
When `experimental_vectorize` is enabled at the cluster level, selecting from `crdb_internal.zones` panics.
```
root@127.0.0.1:65524/defaultdb> SET CLUSTER SETTING sql.defaults.experimental_vectorize = on;
SET CLUSTER SETTING

Time: 2.896ms

root@127.0.0.1:65524/defaultdb> SELECT * FROM crdb_internal.zones;
E190702 16:28:07.539314 740 sql/conn_executor.go:713  [n1,client=127.0.0.1:65526,user=root] a SQL panic has occurred while executing "SELECT * FROM crdb_internal.zones": expected *DInt, found tree.dNull
E190702 16:28:07.539387 740 util/log/crash_reporting.go:207  [n1,client=127.0.0.1:65526,user=root] a panic has occurred!
panic: expected *DInt, found tree.dNull [recovered]
	panic: panic while executing 1 statements: SELECT * FROM _._; caused by expected *DInt, found tree.dNull

goroutine 740 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000cca380, 0x75f07e0, 0xc000a11580, 0x6a95f60, 0xc0003b7340)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:727 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000cca380, 0x75f07e0, 0xc000a11580)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:440 +0x61
panic(0x6a95f60, 0xc0003b7340)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.MustBeDInt(0x75f7d60, 0x9707c20, 0x9707c20)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:617 +0xd9
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getAllNames(0xc000cca6d0, 0x75f08a0, 0xc0014fa600, 0x10, 0x400e999, 0xc001692f90)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1835 +0x16f
github.com/cockroachdb/cockroach/pkg/sql.glob..func53(0x75f08a0, 0xc0014fa600, 0xc000cca6d0, 0xc00041ab20, 0xc00175dc20, 0xc00175dbd0, 0xc000630001)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1866 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.getPlanInfo.func1(0x75f08a0, 0xc0014fa600, 0xc000cca6d0, 0x6dd8709, 0x9, 0xc0002da5c0, 0xc00063a0a0, 0xc0007290e0, 0x100)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:272 +0x38e
github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructVirtualScan.func1(0x75f08a0, 0xc0014fa600, 0xc000cca6d0, 0x1, 0xc0014fa5d0, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:135 +0x5e
github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec(0xc001515840, 0x75f08a0, 0xc0014fa600, 0xc001862800, 0xc000cca6d0, 0x1, 0xc0011a5b30)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go:58 +0x57
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x6de271b, 0xd, 0x75f1d60, 0xc001515840, 0xc0000b1bc0, 0xc0011a5b40)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:497 +0x55
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc00179b7a0, 0x6de271b, 0xd, 0x75f1d60, 0xc001515840)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:142 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc00179b7a0, 0x75f1d60, 0xc001515840, 0x6de271b, 0xd)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:624 +0x2a8
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc00179b7a0, 0x75f1d60, 0xc001515840, 0x0, 0x60)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:109 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:73
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x75f08a0, 0xc0014fa600, 0xc001862800, 0xc000cca6d0, 0x75f1d60, 0xc001515840, 0x75abfe0, 0x970a660)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:500 +0x286
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc000634500, 0x75f08a0, 0xc0014fa600, 0x970a660, 0x68ac3a0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:117 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc000634500, 0x75f08a0, 0xc0014fa600)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:792 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc00000cd20, 0x75f08a0, 0xc0014fa600, 0x6f49358, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:654 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0001eafc0, 0xc00179b6e0, 0xc001675710, 0xc0011a68b0, 0xc00092e2c0, 0xc000cca7a8, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:296 +0x35c
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0001eafc0, 0x75f08a0, 0xc0014fa420, 0xc000cca7a8, 0xc00179b6e0, 0xc001675710, 0x75f1d60, 0xc001515840, 0xc00092e2c0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:860 +0x208
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000cca380, 0x75f08a0, 0xc0014fa420, 0xc000cca6d0, 0x3, 0xbb92940, 0xc000443d90, 0xc0011a6b00, 0x0, 0x0, ...)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:902 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000cca380, 0x75f08a0, 0xc0014fa420, 0xc000cca6d0, 0xbb92940, 0xc000443d90, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734 +0x6e5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000cca380, 0x75f08a0, 0xc0014fa420, 0x75f5ca0, 0xc0018610c0, 0xc0008d6170, 0x21, 0x0, 0x1, 0x0, ...)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xb64
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000cca380, 0x75f08a0, 0xc0014fa420, 0x75f5ca0, 0xc0018610c0, 0xc0008d6170, 0x21, 0x0, 0x1, 0x0, ...)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc000cca380, 0x75f07e0, 0xc001515740, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1204 +0x1ab0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000cca380, 0x75f07e0, 0xc000a11580, 0xc000507540, 0x5400, 0x15000, 0xc0005075d8, 0xc0002c98a0, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0001b9b00, 0x75f07e0, 0xc000a11580, 0xc000cca380, 0x5400, 0x15000, 0xc0005075d8, 0xc0002c98a0, 0x0, 0x0)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000347d39, 0xc0003091e0, 0x75f07e0, 0xc000a11580, 0xc0002c98a0, 0xc0001b9b00, 0xc000b9e000, 0x75f4220, 0xc0003091c0, 0xc001020300, ...)
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/Users/solon/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:509 +0x17b
```

### LINKED ISSUE #38611: exec: error when accessing system.users table
For some reason when selecting from `system.users`, `cfetcher` tries to access a column family which doesn't exist.

Reproducing logic test:
```
# LogicTest: local-vec

query T
SELECT "hashedPassword" FROM system.users
----
```

Result:
```
pq: unexpected error from the vectorized runtime: index_key_decoding_error: family-id "4" does not exist
```

### LINKED ISSUE #38755: exec: incorrect results for system.namespace table
The vectorized engine returns incorrectly NULL results for the `system_namespace.id` column.
```
root@127.0.0.1:53699/defaultdb> select * from system.namespace;
  parentID |       name       | id
+----------+------------------+----+
         0 | defaultdb        | 50
         0 | postgres         | 51
         0 | system           |  1
         1 | comments         | 24
         1 | descriptor       |  3
         1 | eventlog         | 12
         1 | jobs             | 15
         1 | lease            | 11
         1 | locations        | 21
         1 | namespace        |  2
         1 | rangelog         | 13
         1 | role_members     | 23
         1 | settings         |  6
         1 | table_statistics | 20
         1 | ui               | 14
         1 | users            |  4
         1 | web_sessions     | 19
         1 | zones            |  5
(18 rows)

Time: 1.079ms

root@127.0.0.1:53699/defaultdb> set experimental_vectorize=on;
SET

Time: 263µs

root@127.0.0.1:53699/defaultdb> select * from system.namespace;
  parentID |       name       |  id
+----------+------------------+------+
         0 | defaultdb        | NULL
         0 | postgres         | NULL
         0 | system           | NULL
         1 | comments         | NULL
         1 | descriptor       | NULL
         1 | eventlog         | NULL
         1 | jobs             | NULL
         1 | lease            | NULL
         1 | locations        | NULL
         1 | namespace        | NULL
         1 | rangelog         | NULL
         1 | role_members     | NULL
         1 | settings         | NULL
         1 | table_statistics | NULL
         1 | ui               | NULL
         1 | users            | NULL
         1 | web_sessions     | NULL
         1 | zones            | NULL
(18 rows)

Time: 964µs
```
I haven't investigated further yet but perhaps related to #38611? Almost certainly it involves column family logic.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #38755.
Fixes #38611.
Fixes #38609.

Two bugfixes to the cfetcher.
- row: teach cfetcher about missing sentinel kvs
System tables are special in that they might be missing their "sentinel
kv": the kv that's marked as column family 0. Previously, cfetcher
assumed that a sentinel kv would always exist. This led to the inability
of decoding system tables correctly.
Now, if the table being read has more than one column family, we always
actively decode the column family id from the first key in a row to make
sure we know what values will be available in the kv.

- row: cfetcher bugfix to unique idxs w/ nulls
Previously, the cfetcher misbehaved when decoding unique secondary
indexes that had null values in one or more of their index columns. This
was because the encoding of the "extra columns" in a unique index (the
columns that are in the primary index but missing from the secondary) is
performed using the key encoding, not the value encoding, and the key
decoding routines in the cfetcher hadn't been taught to keep track of
which needed columns hadn't been seen in the current row yet.
This commit corrects the problem by teaching the key decoding routine to
optionally remove the decoded keys from the set of unseen column values
so far.

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
Nice, thanks for the fix. I added a couple thoughts but looks good in general.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-:-LjR47ubEYsRX2fcx7mL:bhxo1mt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/row/cfetcher.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjR2nzt1i20hzXEwfts:-LjR2nzt1i20hzXEwftt:b-ibfvww) ([raw file](https://github.com/cockroachdb/cockroach/blob/91744f26668a357af625a01f95f80ee63c554a05/pkg/sql/row/cfetcher.go#L676)):*
> ```Go
> 			}
> 
> 			key := kv.Key[len(rf.machine.lastRowPrefix):]
> ```

It still strikes me as a little dicey that `lastRowPrefix` might be nil here. But I guess that is never the case if we're dealing with interleaves, so probably it's ok? Feels somewhat brittle. Should we consider always setting it in `stateDecodeFirstKVOfRow`? We can do so without decoding the key by using `keys.GetRowPrefixLength`.
___
*[pkg/sql/row/cfetcher.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjR1P0IBZhWXLXQSBd3:-LjR1P0IBZhWXLXQSBd4:b-pzpvdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/91744f26668a357af625a01f95f80ee63c554a05/pkg/sql/row/cfetcher.go#L1077)):*
> ```Go
> 		return 0, nil
> 	}
> 	if keyLen-1 < int(columnFamilyIDLength) {
> ```

`keys.go` writes this differently to avoid a potential overflow:
https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/keys/keys.go#L777-L779
(Also maybe there is some potential to share code between the two.)

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/row/cfetcher.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjR2nzt1i20hzXEwfts:-LjR4oKv3cm6sx8U14gV:b-4zhjx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/91744f26668a357af625a01f95f80ee63c554a05/pkg/sql/row/cfetcher.go#L676)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It still strikes me as a little dicey that `lastRowPrefix` might be nil here. But I guess that is never the case if we're dealing with interleaves, so probably it's ok? Feels somewhat brittle. Should we consider always setting it in `stateDecodeFirstKVOfRow`? We can do so without decoding the key by using `keys.GetRowPrefixLength`.
</blockquote></details>

Actually if we did this, I think your new `getCurrentColumnFamilyID` function would be unnecessary. You could just decode the next int to get the column family like the code was doing before.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/row/cfetcher.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjR2nzt1i20hzXEwfts:-LjRfVeV1kaZmduI2UGE:b5neqzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/91744f26668a357af625a01f95f80ee63c554a05/pkg/sql/row/cfetcher.go#L676)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Actually if we did this, I think your new `getCurrentColumnFamilyID` function would be unnecessary. You could just decode the next int to get the column family like the code was doing before.
</blockquote></details>

Good idea, though it does make me sad that we're sacrificing even the tiniest bit of performance in the COUNT(*) case. The thing that I added I think manages to avoid doing work if the max column family is 0. But I think you're right anyway - I'll keep `getCurrentColumnFamilyID` and have it assume that the row prefix is set, return 0 if it can, and otherwise decode.
___
*[pkg/sql/row/cfetcher.go, line 1077 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjR1P0IBZhWXLXQSBd3:-LjRfAk6BHS7rA9uHbjn:b-6zx5un) ([raw file](https://github.com/cockroachdb/cockroach/blob/91744f26668a357af625a01f95f80ee63c554a05/pkg/sql/row/cfetcher.go#L1077)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

`keys.go` writes this differently to avoid a potential overflow:
https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/keys/keys.go#L777-L779
(Also maybe there is some potential to share code between the two.)
</blockquote></details>

Ah, I was looking for this code but couldn't find it. Now we are using the shared method.

**Review by jordanlewis — COMMENTED** [review]
I accidentally amended the fix to the wrong commit, then fixed it and force pushed, hopefully things make sense.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-:-LjS8qd65EoEqXKgwlmC:by3mvhf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Review by solongordon — COMMENTED** [review]
It seems like `DecodeKeyValsToCols` is always invoked with a nil `unseen` argument. Is something weird?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-:-LjXaBK8B-G6F62Y_9sn:b-87f14v)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/row/cfetcher.go, line 842 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjZJ_TyEz0Cgehedcvt:-LjZJ_TyEz0Cgehedcvu:bggh27q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f05450a1c4da319942d8cd7045bf4f036dfa551/pkg/sql/row/cfetcher.go#L842)):*
> ```Go
> 				table.extraTypes,
> 				nil,
> 				&rf.machine.remainingValueColsByIdx,
> ```

This is the sneaky spot where it's getting called with non-nil - reviewable is bad at showing it

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/row/cfetcher.go, line 842 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-LjZJ_TyEz0Cgehedcvt:-LjaX65W2-eiws_kcS7w:b-puatcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f05450a1c4da319942d8cd7045bf4f036dfa551/pkg/sql/row/cfetcher.go#L842)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is the sneaky spot where it's getting called with non-nil - reviewable is bad at showing it
</blockquote></details>

Aha, thanks. Looks good to go then.

**Review by jordanlewis — COMMENTED** [review]
TFTR!

(I uploaded a fix to an unfinished comment in the first commit, hence the final push.)

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38787#-:-LjaeISR84zDdk5zawsM:b-kf3a90)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
