### PR TITLE
opt: only infer self-join equality with a key over the base table

### LINKED ISSUE #106371: roachtest: django failed
roachtest.django [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10813231?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10813231?buildTab=artifacts#/django) on master @ [1137aee0089fc2fe161bab0f1c899d2ddc997c90](https://github.com/cockroachdb/cockroach/commits/1137aee0089fc2fe161bab0f1c899d2ddc997c90):

```
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.2.0-alpha.00000000-dev-1137aee0089fc2fe161bab0f1c899d2ddc997c90
Tests run against django cockroach-4.1.x
9951 Total Tests Run
9949 tests passed
2 tests failed
639 tests skipped
2 tests ignored
0 tests passed unexpectedly
2 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- SKIP: backends.mysql.test_creation.DatabaseCreationTests.test_create_test_db_unexpected_error due to MySQL tests (expected)
--- FAIL: queries.tests.Queries1Tests.test_ticket2306 (unexpected)
--- FAIL: queries.tests.Queries1Tests.test_ticket4464 (unexpected)
For a full summary look at the django artifacts 
An updated blocklist (djangoBlocklist) is available in the artifacts' django log
test artifacts and logs in: /artifacts/django/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*django.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29537

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: only infer self-join equality with a key over the base table

Self-join equality inference was added by #105214, so that the `FuncDeps`
for a self-join would include equalities between *every* pair of columns
at the same ordinal position in the base table if there was an equality
between key columns (also at the same ordinal position). However, the
key column check was performed using the FDs of the join inputs rather
than the base table's FDs. This could lead to incorrectly adding self-join
equality filters. For example, consider the following:
```
CREATE TABLE t106371 (x INT NOT NULL, y INT NOT NULL);
INSERT INTO t106371 VALUES (1, 1), (1, 2);

SELECT * FROM t106371 a JOIN t106371 b ON a.x = b.x;

SELECT * FROM (SELECT * FROM t106371 ORDER BY y DESC LIMIT 1) a
JOIN (SELECT DISTINCT ON (x) * FROM t106371) b ON a.x = b.x;
```
In the first query above, `a.x = b.x` does not consitute joining on
key columns. But in the second query, one input has one row and the
other de-duplicated by the `x` column and so `x` is a key over both
inputs. However, the query as written will select different rows for
each input - `a` will return the `(1, 2)` row, while `b` will return
the `(1, 1)` row. Inferring a `a.y = b.y` filter will incorrectly cause
the join to return no rows.

This patch fixes the problem by requiring the initial self-join
equalities to form a key over the *base* table, not just the inputs
of the join.

Fixes #106371

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
Looks good overall, just need to fix some tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-:-N_ZYDpcAi9frM6_ONtN:bf4s372)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXrBm3ZgfuMR2Yjw2:-N_ZXrBm3ZgfuMR2Yjw3:bdjq5wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/opt/memo/logical_props_builder.go#L2553)):*
> ```Go
> 	}
> 	for leftTable, leftTableOrds := range leftTables {
> 		var baseTabFDs *props.FuncDepSet
> ```

The "resetting" of `baseTabFDs` for every iteration of the outer loop is subtle and might be easy for someone to mess up in the future. Consider adding a comment to highlight this or a test that will fail if it's not reset.
___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXLHH4-0e_Y2AbS7l:-N_ZXLHH4-0e_Y2AbS7m:b-pk818m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/logictest/testdata/logic_test/join#L1210)):*
> ```
> 
> # Regression test for #106371 - only infer self-join equalities if the original
> # equality columns form a key over the *base* table, not just the join inputs.
> ```

Can you simplify this to the example in the commit message, or does it the reproduction require all this?
___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXDOkANKhxhH057nt:-N_ZXDOkANKhxhH057nu:b-vxbi35) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/logictest/testdata/logic_test/join#L1234)):*
> ```
> 
> statement ok
> CREATE TABLE queries_item_tags (                                                                      
> ```

nit: remove trailing spaces

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106485)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXrBm3ZgfuMR2Yjw2:-N__FWoE7HdCOIfim-MM:b-8bljgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/opt/memo/logical_props_builder.go#L2553)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The "resetting" of `baseTabFDs` for every iteration of the outer loop is subtle and might be easy for someone to mess up in the future. Consider adding a comment to highlight this or a test that will fail if it's not reset.
</blockquote></details>

Since `MakeTableFuncDep` caches the FDs anyway, I've just changed it to unconditionally initialize `baseTabFDs` in the outer loop, and leave it untouched in the inner loop.
___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXLHH4-0e_Y2AbS7l:-N__PG6bBlvxtPAc5JUb:b-vubegi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/logictest/testdata/logic_test/join#L1210)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you simplify this to the example in the commit message, or does it the reproduction require all this?
</blockquote></details>

Good point, a modified version of the commit example will work for a logic test. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXDOkANKhxhH057nt:-N__PKeU58kzUGXg75hF:bcpgx4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/logictest/testdata/logic_test/join#L1234)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove trailing spaces
</blockquote></details>

Replaced the test case as mentioned above.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice find!

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-:-N_dHGUIA8ifDOcoBYzN:bcdfsno)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_ZXrBm3ZgfuMR2Yjw2:-N_dFp_lDNI5fYMuV6A1:bu0eg4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ec29b2255ac20467d8dcd26ff5e4fb457788d32/pkg/sql/opt/memo/logical_props_builder.go#L2553)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Since `MakeTableFuncDep` caches the FDs anyway, I've just changed it to unconditionally initialize `baseTabFDs` in the outer loop, and leave it untouched in the inner loop.
</blockquote></details>

Nice solution!
___
*[`pkg/sql/opt/memo/testdata/logprops/join` line 3010 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106485#-N_dH1Oo4AthsIWi5dLY:-N_dH1Oo4AthsIWi5dLZ:b7yrv4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7053d2f3974c493ad81cfdf132f48960559f6faa/pkg/sql/opt/memo/testdata/logprops/join#L3010)):*
> ```
> # from each input.
> norm
> SELECT * FROM xyz INNER JOIN xyz foo ON xyz.x = foo.x AND xyz.y = 1 AND foo.y = 2
> ```

We already had a test for this, but none of us realized the output was invalid... :shrug:

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Comment by DrewKimball** [comment]
bors retry

**Comment by DrewKimball** [comment]
Looks like the bors failure was transient, due to something in the test infra.

**Pull request merged**
