### PR TITLE
sql: add infrastructure for tracing queries on demand

### PR DESCRIPTION
**Pull request by andreimatei**
This patch adds some infrastructure, to be hooked up to the AdminUI in
the future. The system.statement_diagnostics_requests and
system.statement_diagnostics tables are introduced. The idea is that all
nodes poll the former for fingerprints of requests that need information
collected and, when nodes then see a query with such a fingerprint, they
race to write the requested info (initially, a trace) into the latter.

system.statement_bundle_chunks is also introduced, to be used in the
future for gatherig more generic data about a query.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Nice! Thanks for incorporating my stuff too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M-la9Qs4gMWVmJzSpZw:blng2s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lWYHs4Yidm8mc3Quw:-M-lWYHtAnUR8la6glwD:bs5gt0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/conn_executor.go#L748)):*
> ```Go
> ) {
> 	pollingInterval := 10 * time.Second
> 	if knob := s.cfg.TestingKnobs.StmtInfoRequestPollingInterval; knob != 0 {
> ```

10 seconds might be annoyingly slow if the query runs frequently. Could we gossip whenever something is added to the statement info requests? The table stats use that mechanism.
___
*[pkg/sql/statement_info.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lYl109lG2RXYLJRdN:-M-lYl109lG2RXYLJRdO:bwuhvmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L78)):*
> ```Go
> 
> // stmtInfoRequestTypeFromString is the inverse of stmtInfoRequestType().
> func stmtInfoRequestTypeFromString(s string) (bool, stmtInfoRequestType) {
> ```

make it `ok bool` and it it's typically the last return
___
*[pkg/sql/statement_info.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lXYhxEVjo5_lV0NOz:-M-lXYhxEVjo5_lV0NP-:bgnne) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L176)):*
> ```Go
> func (r *stmtInfoRequestRegistry) shouldCollectInfo(
> 	ctx context.Context, ast tree.Statement,
> ) (bool, func(ctx context.Context, trace tracing.Recording)) {
> ```

This callback signature is dubious (it only works for traces). I think the caller should call `insertTrace` and this callback should just do the registry-related stuff.
___
*[pkg/sql/statement_info.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZ1moAEAb7cPpbtro:-M-lZ1moAEAb7cPpbtrp:b-fyvbry) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L185)):*
> ```Go
> 	}
> 
> 	stmt := tree.AsString(ast)
> ```

move this closer to where it's being used, we don't need to do it if there is no matching request
___
*[pkg/sql/statement_info.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lYMhb7Pqa2n1eNekR:-M-lYMhb7Pqa2n1eNekS:b-a1ez7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L246)):*
> ```Go
> 			cnt := int(*row[0].(*tree.DInt))
> 			if cnt == 0 {
> 				// Someone else already marked the request as completed. We've traced for nothing.
> ```

Mention that this will happen at most once per node because we remove the entry from the registry.
___
*[pkg/sql/sqlbase/system.go, line 1330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-l_Scy66V6WteA_Itq:-M-l_Scy66V6WteA_Itr:b-ypryg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/sqlbase/system.go#L1330)):*
> ```Go
> 			{Name: "collected_at", ID: 4, Type: *types.TimestampTZ, Nullable: true},
> 			{Name: "trace", ID: 5, Type: *types.Jsonb, Nullable: true},
> 		},
> ```

Can you add a "bundle_chunks" which is a nullable int array?
___
*[pkg/sql/tests/system_table_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZtkb7eD1xR_njshs:-M-lZtkb7eD1xR_njsht:bso7aa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/tests/system_table_test.go#L123)):*
> ```Go
> 		{keys.ProtectedTimestampsRecordsTableID, sqlbase.ProtectedTimestampsRecordsTableSchema, sqlbase.ProtectedTimestampsRecordsTable},
> 		{keys.StatementBundleChunksTableID, sqlbase.StatementBundleChunksTableSchema, sqlbase.StatementBundleChunksTable},
> 		// !!! other tables here
> ```

fix this
___
*[pkg/util/tracing/recorded_span.proto, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZk_I2L4JWabPd_9h:-M-lZk_I2L4JWabPd_9i:bcc715u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/util/tracing/recorded_span.proto#L20)):*
> ```protobuf
> import "google/protobuf/duration.proto";
> 
> message LogRecord {
> ```

[nit] add a comment, mentioning that it's for traces (in case someone just jumps to the def)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/statement_info.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-luywO9n4QdEzNc8_y:-M-luywP653zJzLLoQdG:b-he20so) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L253)):*
> ```Go
> 		var traceID int
> 		if json, err := traceToJSON(trace); err != nil {
> 			row, err := r.ie.QueryRowEx(ctx, "statement-info-insert-trace", nil, /* txn */
> ```

should this be txn?
___
*[pkg/sql/statement_info.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lv-OWBqsWdw7ioEkD:-M-lv-OWBqsWdw7ioEkE:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L265)):*
> ```Go
> 		} else {
> 			// Insert the trace into system.statement_info.
> 			row, err := r.ie.QueryRowEx(ctx, "statement-info-insert-trace", nil, /* txn */
> ```

ditto
___
*[pkg/sql/statement_info.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lv04LEC8qjKdXbPV1:-M-lv04LEC8qjKdXbPV2:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L278)):*
> ```Go
> 
> 		// Mark the request from system.statement_info_request as completed.
> 		_, err := r.ie.ExecEx(ctx, "statement-info-mark-completed", nil, /* txn */
> ```

ditto

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/statement_info.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvq5ZBDKK9m5QN_dJ:-M-lvq5_7e6FIC7wYdVf:btodl57) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L124)):*
> ```Go
> 		},
> 		"INSERT INTO system.statement_info_requests (type, statement_fingerprint, requested_at) "+
> 			"VALUES ($1, $2, $3) RETURNING ID",
> ```

[nit] `id`
___
*[pkg/sql/statement_info.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvtVGApLHwrLsWa9-:-M-lvtVGApLHwrLsWa90:btodl57) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L257)):*
> ```Go
> 				"INSERT INTO system.statement_info "+
> 					"(statement_fingerprint, statement, collected_at, error) "+
> 					"VALUES ($1, $2, $3, $4) RETURNING ID",
> ```

[nit] `id`
___
*[pkg/sql/statement_info.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvuXL6XXNbhXJQmpq:-M-lvuXL6XXNbhXJQmpr:btodl57) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L269)):*
> ```Go
> 				"INSERT INTO system.statement_info "+
> 					"(statement_fingerprint, statement, collected_at, trace) "+
> 					"VALUES ($1, $2, $3, $4) RETURNING ID",
> ```

[nit] `id`

**Review by andreimatei — COMMENTED** [review]
RFAL

cc @dhartunian @nathanstilwell 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M0PHSlFALLvOYPxlLxQ:b-lazru0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lWYHs4Yidm8mc3Quw:-M0PHFJX1SMZArRVhxpI:blplhjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/conn_executor.go#L748)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

10 seconds might be annoyingly slow if the query runs frequently. Could we gossip whenever something is added to the statement info requests? The table stats use that mechanism.
</blockquote></details>

added gossip
___
*[pkg/sql/sqlbase/system.go, line 1330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-l_Scy66V6WteA_Itq:-M0On_bW4gS43poGpPhL:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/sqlbase/system.go#L1330)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you add a "bundle_chunks" which is a nullable int array?
</blockquote></details>

done
___
*[pkg/sql/tests/system_table_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZtkb7eD1xR_njshs:-M0P8O7KBOZrCMYsA7Sq:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/tests/system_table_test.go#L123)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

fix this
</blockquote></details>

done
___
*[pkg/util/tracing/recorded_span.proto, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZk_I2L4JWabPd_9h:-M0P8Yrq14g4tdwMDquN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/util/tracing/recorded_span.proto#L20)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment, mentioning that it's for traces (in case someone just jumps to the def)
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lYl109lG2RXYLJRdN:-M0OlEFD3LJxcSlgtZjs:bb7gzl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

make it `ok bool` and it it's typically the last return
</blockquote></details>

gone
___
*[pkg/sql/statement_info.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvq5ZBDKK9m5QN_dJ:-M0OlNj2BxT4iL0J9b3S:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L124)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `id`
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lXYhxEVjo5_lV0NOz:-M0PH5mNCj0C42-jchSm:bshf1ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L176)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This callback signature is dubious (it only works for traces). I think the caller should call `insertTrace` and this callback should just do the registry-related stuff.
</blockquote></details>

I left it after all.
___
*[pkg/sql/statement_info.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lZ1moAEAb7cPpbtro:-M0Onx2T7HeJ3GPm2adm:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L185)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

move this closer to where it's being used, we don't need to do it if there is no matching request
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lYMhb7Pqa2n1eNekR:-M0P82OH0EhrVr_bqrDf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention that this will happen at most once per node because we remove the entry from the registry.
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-luywO9n4QdEzNc8_y:-M0P8Gtf-aiWWJD36aLQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L253)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

should this be txn?
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvtVGApLHwrLsWa9-:-M0P8JfdAf62dMsw2Acc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L257)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `id`
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lv-OWBqsWdw7ioEkD:-M0PH8fxDAlms5mbs3-g:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L265)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lvuXL6XXNbhXJQmpq:-M0P8KD7-wn2MIhIFCxX:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L269)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `id`
</blockquote></details>

done
___
*[pkg/sql/statement_info.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lv04LEC8qjKdXbPV1:-M0P8MLc82JeokWNIO9r:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/statement_info.go#L278)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-M-lWYHs4Yidm8mc3Quw:-M0PkI_z4JoB9Td0nDXJ:baq8bnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3351e2a5d7023c78f5198d16a52b83501449a168/pkg/sql/conn_executor.go#L748)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

added gossip
</blockquote></details>

I'm now thinking that I should have gossipped the new request id rather than a node id. I'll change it.

Btw one thing that I've considered using when I was still opposing gossip is changefeeds. But that's CCL only and it comes with other technical imperfections. cc @ajwerner so he can dig up this PR when said imperfections are perfected.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M0y86I46qf-nctKRJ0N:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M16Gj_t7J0PWb6iypZe:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M16Gj_t7J0PWb6iypZe:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44947#-:-M16QwjpE2itFZOVlyfG:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by andreimatei** [comment]
merge skew

bors r+

**Pull request merged**
