### PR TITLE
kv: allow DeleteRangeRequests to be pipelined 

### LINKED ISSUE #64723: kv: pipeline DeleteRange requests where possible
Sorry if this is intended and I've just missed why, but in a bit of testing recently I noticed that while transactional pipelining of INSERTs/UPSERTs works great (i.e. they return almost instantly when run within a transaction), it doesn't appear to work for DELETEs (i.e. they have to wait for a full replication round trip).

I noticed this on a cluster running v20.2.7 with roughly 30ms RTT between localities in the cluster.

@nvanbenschoten is this expected? Sorry if it's a dupe or I'm way off base here, but it's surprising to me that inserts/upserts can be pipelined but not deletes.

# Reproduction

Create a simple table:

```
root@/defaultdb> create table foo (k string primary key, v string);
```

Single inserts, upserts, and deletes all take around 30ms, corresponding with the network latency between localities:
```
root@/defaultdb> insert into foo values ('a', 'a')
INSERT 1

Time: 31ms total (execution 31ms / network 0ms)
```

Within a transaction, inserts and upserts finish basically immediately, as I'd expect due to transactional pipelining:
```
root@/defaultdb> begin;
BEGIN

Time: 0ms total (execution 1ms / network 0ms)

root@/defaultdb  OPEN> insert into foo values ('c', 'a'), ('d', 'a');
INSERT 2

Time: 2ms total (execution 2ms / network 0ms)

root@/defaultdb  OPEN> commit;
COMMIT

Time: 31ms total (execution 31ms / network 0ms)
```

However, delete statements don't appear to benefit from this optimization:
```
root@/defaultdb> begin;
BEGIN

Time: 0ms total (execution 0ms / network 0ms)

root@/defaultdb  OPEN> delete from foo where k = 'c';
DELETE 1

Time: 30ms total (execution 30ms / network 0ms)

root@/defaultdb  OPEN> commit;
COMMIT

Time: 31ms total (execution 31ms / network 0ms)
```

Jira issue: CRDB-7218

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, ranged requests could not be pipelined. However, there is no
good reason to not allow them to be pipeliend -- we just have to take
extra care to correctly update in-flight writes tracking on the response
path. We do so now.

As part of this patch, we introduce two new flags -- canPipeline and
canParallelCommit. We use these flags to determine whether batches can
be pipelined or committed using parallel commits. This is in contrast to
before, where we derived this information from other flags
(isIntentWrite, !isRange). This wasn't strictly necessary for this
change, but helps clean up the concepts.

As a consequence of this change, we now have a distinction between
requests that can be pipelined and requests that can be part of a batch
that can be committed in parallel. Notably, this applies to
DeleteRangeRequests -- they can be pipeliend, but not be committed in
parallel. That's because we need to have the entire write set upfront
when performing a parallel commit, lest we need to perform recovery --
we don't have this for DeleteRange requests.

In the future, we'll extend the concept of canPipeline
(and !canParallelCommit) to other locking ranged requests as well. In
particular, (replicated) locking {,Reverse}ScanRequests who want to
pipeline their lock acquisitions.

Closes https://github.com/cockroachdb/cockroach/issues/64723
Informs https://github.com/cockroachdb/cockroach/issues/117978

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This is looking good! Have you tested it out end-to-end with SQL in an MR cluster to show the latency win? You can use the script from https://github.com/cockroachdb/cockroach/issues/64723.

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-:-NsjKy23Ekkv4aJ93VWo:b72oz2m)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjEM4d4EC9BXTROdqJ:-NsjEM4d4EC9BXTROdqK:b-ksk7ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L139)):*
> ```Go
> 	mu                 sync.Locker
> 	disable1PC         bool
> 	disableElideEndTxn bool
> ```

I don't understand why this part of the change was needed. Maintaining a separate flag instead of deriving this from the `EndTxn` request feels like a step backwards. Doing so means that we need to keep the flag in sync with the rest of the txn, lest we accidentally disable elision too much or too little.

For example, on first reading, it looks like there's a bug here where we should reset this flag to false in `epochBumpedLocked`. That's not actually a bug because we don't want to elide in these cases, but the flag being separate from `lockFootprint` (which documents this) raises these questions.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go` line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjH4zYCCITW9v6bN8_:-NsjH4zYCCITW9v6bN8a:bmv4xlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L370)):*
> ```Go
> 		req := ru.GetInner()
> 		switch {
> 		case kvpb.IsIntentWrite(req):
> ```

Should we use `CanParallelCommit` here?
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjGaEj8KFHFV53nsis:-NsjGaEj8KFHFV53nsit:berpc72) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L462)):*
> ```Go
> 		req := ru.GetInner()
> 
> 		// The current request cannot be pipelined, so it prevents us from
> ```

This comment should either start with "Determine whether ..." (with a few other updates) or should be moved within the `if` block.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 485 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjHiE-5Byrq4AmIIY_:-NsjHiE-5Byrq4AmIIYa:bwb52h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L485)):*
> ```Go
> 		}
> 
> 		switch req.Method() {
> ```

nit: we'll need to move this above the `CanPipeline` check if we listen to the comment I made in `api.go`.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjIBOr0fTGrW57ohQj:-NsjIBOr0fTGrW57ohQk:b-3bmvob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L497)):*
> ```Go
> 			// can disable DeleteRange pipelining entirely for requests that set this
> 			// field to false.
> 			deleteRangeReq.ReturnKeys = true
> ```

We'll need to do this for mixed version clusters, but longer term, should we try to just deprecate this flag and always treat it as set to true? It will be set to true most of the time going forward anyway.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjK58h7JeFwpvdiKYB:-NsjK58h7JeFwpvdiKYC:b7aqgcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L497)):*
> ```Go
> 			// can disable DeleteRange pipelining entirely for requests that set this
> 			// field to false.
> 			deleteRangeReq.ReturnKeys = true
> ```

Should we add a test that demonstrates that this flag is set to true? Or add it to `TestTxnPipelinerDeleteRangeRequests`.
___
*[`pkg/kv/kvpb/api.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjFLtQAv5QEogMgpaq:-NsjFLtQAv5QEogMgpar:bz3bvqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L87)):*
> ```Go
> 	isLocking:         {isTxn},
> 	isIntentWrite:     {isWrite, isLocking},
> 	canParallelCommit: {canPipeline},
> ```

Does `canPipeline` depend on `isIntentWrite`?
___
*[`pkg/kv/kvpb/api.go` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjFZ7qCxKIlmItr2i_:-NsjFZ7qCxKIlmItr2ia:b6h73nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L186)):*
> ```Go
> }
> 
> // CanPipeline returns true iff the BatchRequest can be pipelined.
> ```

`s/BatchRequest/command/`

Here and below.
___
*[`pkg/kv/kvpb/api.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjGQlD3ZHbcJ6GXBFi:-NsjGQlD3ZHbcJ6GXBFj:bxbqaxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L193)):*
> ```Go
> // CanParallelCommit returns true iff the BatchRequest can be part of a batch
> // that is committed in parallel.
> func CanParallelCommit(args Request) bool {
> ```

Can we use this in place of `kvpb.IsIntentWrite(req) && !kvpb.IsRange(req)` (twice) in `maybeStripInFlightWrites`?
___
*[`pkg/kv/kvpb/api.go` line 1669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjFnQC5QdQjldvYUvu:-NsjFnQC5QdQjldvYUvv:b5lvqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L1669)):*
> ```Go
> 	// recovery we need the entire in-flight write set to plop on the txn record,
> 	// and we don't have that on the request path if the batch contains a
> 	// DeleteRange request.
> ```

Should we only return `canPipeline` if `drr.ReturnKeys`?
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsKYLhk1WbfRlzsv3Br:-NsKYLhk1WbfRlzsv3Bs:bmdzf8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/534be2911d0274627d70270073d88e4f58efe358/pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go#L75)):*
> ```Go
> 			require.Len(t, ba.Requests, 2)
> 			require.IsType(t, &kvpb.GetRequest{}, ba.Requests[0].GetInner())
> 			require.IsType(t, &kvpb.PutRequest{}, ba.Requests[1].GetInner())
> ```

`ScanRequest`
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 617 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjJasmAKe1L4BCRpkY:-NsjJasmAKe1L4BCRpkZ:b-5iiida) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L617)):*
> ```Go
> 	require.Equal(t, 3, tp.ifWrites.len())
> 
> 	// Now, test RefreshRangeRequests, which cannot be pipelined.
> ```

`RefreshRangeRequest` will never go through the `txnPipeliner`, so I don't think this is worth testing. If you want to test a ranged request, maybe use a `ScanRequest`?
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjJotYEw_KLE01kV2e:-NsjJotYEw_KLE01kV2f:b-hp9pzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L637)):*
> ```Go
> 	require.Nil(t, pErr)
> 	require.NotNil(t, br)
> 	require.Equal(t, 0, tp.ifWrites.len())
> ```

How do we end up with `0` in-flight writes here? We didn't clear them or issue QueryIntent request for them.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjK0Iv5xcSgle_0Ks6:-NsjK0Iv5xcSgle_0Ks7:bn8b7en) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L972)):*
> ```Go
> }
> 
> // TestTxnPipelinerDeleteRangeRequests ensures the txnPipelineer correctly
> ```

`txnPipeliner`
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjKHoq4wgypqasOdwo:-NsjKHoq4wgypqasOdwp:bbbxn5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L997)):*
> ```Go
> 		br.Txn = ba.Txn
> 		resp := br.Responses[0].GetInner()
> 		resp.(*kvpb.DeleteRangeResponse).Keys = []roachpb.Key{keyB}
> ```

Since this is the only test where we set `DeleteRangeResponse.Keys`, let's add a few to demonstrate that all end up in `ifWrites` and that they all end up with the correct sequence number. See the `qiReq1 := ...` logic above for inspiration.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 1010 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjKkPS7FQE9JcT34zs:-NsjKkPS7FQE9JcT34zt:b-liy6gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L1010)):*
> ```Go
> 	ba = &kvpb.BatchRequest{}
> 	ba.Header = kvpb.Header{Txn: &txn}
> 	ba.Add(&kvpb.DeleteRangeRequest{RequestHeader: kvpb.RequestHeader{Key: keyD, EndKey: keyE}})
> ```

Let's have this overlap with some (but not all) of the in-flight intent writes from the first request. That will lead to an interesting order of `QueryIntentRequest`s.

**Review by arulajmani — COMMENTED** [review]
Still need to look into/fix TestTxnPipelinerRejectAboveBudget, but I addressed all your review comments, beefed up some testing,  and I think I have all other tests passing. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-:-NtrbFuCDGHEmdIDBkEd:bcvl3m7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go` line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjEM4d4EC9BXTROdqJ:-NtrJrTy52kOPSWKcIQM:bbb5gie) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't understand why this part of the change was needed. Maintaining a separate flag instead of deriving this from the `EndTxn` request feels like a step backwards. Doing so means that we need to keep the flag in sync with the rest of the txn, lest we accidentally disable elision too much or too little.

For example, on first reading, it looks like there's a bug here where we should reset this flag to false in `epochBumpedLocked`. That's not actually a bug because we don't want to elide in these cases, but the flag being separate from `lockFootprint` (which documents this) raises these questions.
</blockquote></details>

We discussed this offline. The main motivation here was that `TestCommitMutatingTransaction` was failing without this. But that turned out to be because I hadn't debugged the failure properly, so this change can be reverted.

I beefed up `TestCommitMutatingTransaction` to include cases where the `EndTxnRequest` is part of the same batch as the mutating request as well. The `DeleteRange` variant of that is interesting because it exercises the logic in `attachLocksToEndTxn` that you pointed me to earlier. I also added a new test for no-op `DeleteRange` requests, as those can elide `EndTxn` requests in some cases.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go` line 370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjH4zYCCITW9v6bN8_:-NtqlkSl2Rr2Ci_qWhZ-:b2i832c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L370)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we use `CanParallelCommit` here?
</blockquote></details>

We should be, done. Thanks for catching.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjGaEj8KFHFV53nsis:-NtrNFSiDHhMDepjzIoc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L462)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment should either start with "Determine whether ..." (with a few other updates) or should be moved within the `if` block.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjIBOr0fTGrW57ohQj:-NtrRHPL68Uw90BOMvGm:b-jqe2gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L497)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We'll need to do this for mixed version clusters, but longer term, should we try to just deprecate this flag and always treat it as set to true? It will be set to true most of the time going forward anyway.
</blockquote></details>

That makes sense, I added a TODO.

 TODO(arul): open an issue about deprecating this. Maybe we can even try and get it into this release.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjK58h7JeFwpvdiKYB:-NtrSMnh16NpGUI24ZGX:baeefwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L497)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we add a test that demonstrates that this flag is set to true? Or add it to `TestTxnPipelinerDeleteRangeRequests`.
</blockquote></details>

Added it to `TestTxnPipelinerDeleteRangeRequests`.
___
*[`pkg/kv/kvpb/api.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjFLtQAv5QEogMgpaq:-Ntqg9C8EfzdbZuBG-Ci:b-xk81ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L87)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `canPipeline` depend on `isIntentWrite`?
</blockquote></details>

You're right, it does as of this PR though this will change when we start pipelining replicated lock acquisitions. For now, I've added it here -- later, we'll probably want something like:

```golang
var var flagDependencies = map[flag][]flag{
...
	canPipeline:       {isLocking},
	canParallelCommit: {canPipeline, isIntentWrite},
...
}
```
___
*[`pkg/kv/kvpb/api.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjGQlD3ZHbcJ6GXBFi:-NtqjpR92xYjobxwEbWS:b4v2p3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L193)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use this in place of `kvpb.IsIntentWrite(req) && !kvpb.IsRange(req)` (twice) in `maybeStripInFlightWrites`?
</blockquote></details>

Done. I'm 50-50 on what's more understandable, so let me know if we want to keep this change or not.
___
*[`pkg/kv/kvpb/api.go` line 1669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjFnQC5QdQjldvYUvu:-NtrQZl192__uCcvmfXj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvpb/api.go#L1669)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we only return `canPipeline` if `drr.ReturnKeys`?
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsKYLhk1WbfRlzsv3Br:-NtqlMov3U8v0rZ5yWxc:b-fn8mpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/534be2911d0274627d70270073d88e4f58efe358/pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go#L75)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`ScanRequest`
</blockquote></details>

:facepalm: 
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 617 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjJasmAKe1L4BCRpkY:-Ntqtf_J5pHQdmZon0Gh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L617)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`RefreshRangeRequest` will never go through the `txnPipeliner`, so I don't think this is worth testing. If you want to test a ranged request, maybe use a `ScanRequest`?
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjJotYEw_KLE01kV2e:-NtqtvseBBX0aC6F5Npb:b-sbiay4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L637)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How do we end up with `0` in-flight writes here? We didn't clear them or issue QueryIntent request for them.
</blockquote></details>

Meant to update this to 2; the test was failing earlier.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjKHoq4wgypqasOdwo:-NtrUpHlDJTfjPpU3aW0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L997)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Since this is the only test where we set `DeleteRangeResponse.Keys`, let's add a few to demonstrate that all end up in `ifWrites` and that they all end up with the correct sequence number. See the `qiReq1 := ...` logic above for inspiration.
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 1010 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NsjKkPS7FQE9JcT34zs:-NtrUmlg1cyJtb5ssbaS:baf33ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d8ea254f8ca84cff3e70d12a6d0d118dd7ee027/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L1010)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's have this overlap with some (but not all) of the in-flight intent writes from the first request. That will lead to an interesting order of `QueryIntentRequest`s.
</blockquote></details>

Good call, done.

**Review by nvb — APPROVED** [review]
:lgtm: once CI is green.

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-:-Ntrl7YhBwAGefzFQA70:b-3q4x1l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go` line 2001 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NtrjZ1B5fYG99Ne9KFg:-NtrjZ1B5fYG99Ne9KFh:b93i3p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/63270dd56382bef955a028baed616f11b5ac6964/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2001)):*
> ```Go
> 		}
> 
> 		if _, ok := ba.GetArg(kvpb.DeleteRange); ok {
> ```

nit: consider moving above `if et, ok := ...`, because `DeleteRange` will come earlier in the batch.
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go` line 2112 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-Ntrk5P7-Dd9lEDM1qKY:-Ntrk5P7-Dd9lEDM1qKZ:b-lw0se9) ([raw file](https://github.com/cockroachdb/cockroach/blob/63270dd56382bef955a028baed616f11b5ac6964/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2112)):*
> ```Go
> 			db := kv.NewDB(log.MakeTestingAmbientCtxWithNewTracer(), factory, clock, stopper)
> 			if err := db.Txn(ctx, test.f); err != nil {
> 				t.Fatalf("%d: unexpected error on commit: %s", i, err)
> ```

nit: `require.NoError`, while we're here.
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go` line 2119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-NtrjolsARhDDS1gBrKt:-NtrjolsARhDDS1gBrKu:bgxluuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/63270dd56382bef955a028baed616f11b5ac6964/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2119)):*
> ```Go
> 			}
> 			expectedCalls = append(expectedCalls, kvpb.EndTxn)
> 			if !reflect.DeepEqual(expectedCalls, calls) {
> ```

nit: `require.Equal`
___
*[`pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go` line 2203 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-Ntrk8iV0VJv2OXVHwU_:-Ntrk8iV0VJv2OXVHwUa:bentenb) ([raw file](https://github.com/cockroachdb/cockroach/blob/63270dd56382bef955a028baed616f11b5ac6964/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2203)):*
> ```Go
> 			}
> 			if !reflect.DeepEqual(expectedCalls, calls) {
> 				t.Fatalf("%d: expected %s, got %s", i, expectedCalls, calls)
> ```

Same point about using `require`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-:-NtrxOrBC7dvM5W4Ci0t:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — COMMENTED** [review]
Addressed comments from the last round and fixed `TestTxnPipelinerRejectAboveBudget`. Ended up adding a `ScanRequest` variant and a `DeleteRangeRequest` variant, as we're now handling what we track for ranged locking requests differently for each. 

Separately, I applied a bandaid on `TestIntentResolution` but I think we should just get rid of it. I'll send out a followup to get your thoughts on in a bit.

TFTRs!

bors r=nvanbenschoten 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119975#-:-Ntrx2qM6nhMAW-RcRWl:bs9t59l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Pull request merged**
