### PR TITLE
multi-region: Long-term owners for multi-region tests

### PR DESCRIPTION
**Pull request by ajstorm**
When we were actively doing work on the multi-region syntax, we had a virtual team which was regularly triaging MR test cases. With the v-team disbanded, these tests need long-term owners which can regularly triage any test case failures. I took a stab at the right long-term owners, but may have not gotten it entirely correct. Specifically, we may want schema to own multiregionccl.

Epic: none
Release note: none

### CODE REVIEW

**Comment by rimadeodhar** [comment]
@ajwerner I believe we had spoken about schema owning MR a couple of months back. Can all these tests be marked as owned by schema?

**Review by ajwerner — COMMENTED** [review]
Sure, making these schema makes sense to me.

**Comment by ajstorm** [comment]
Updated.  Could I get a stamp from someone so that I can merge this?

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by ajstorm** [comment]
TFTR

bors r=ajwerner,rimadeodhar

**Pull request merged**
