### PR TITLE
ttljob: add row statistics

### PR DESCRIPTION
**Pull request by otan**
This commit adds the ability for the TTL job to generate statistics on
number of rows and number of expired rows on the table. This is off by
default, controllable by the `ttl_automatic_stats_poll_interval` storage
parameter syntax.

Release justification: low risk high benefit changes to new
functionality

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
small suggestions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-:-MwlMI8E0YglqJviFJMN:b-oy5gjz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/paramparse/paramparse.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-Mwjhp9O8ojDjaX1gBzy:-Mwjhp9O8ojDjaX1gBzz:b-edwhzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/paramparse/paramparse.go#L60)):*
> ```Go
> }
> 
> // DatumAsDuration transforms a tree.TypedExpr containing a Datum into a float.
> ```

nit: into a Duration
___
*[pkg/sql/paramparse/paramparse.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-Mwji8oK-mdK20POkdBi:-Mwji8oL7iwmreqzCdKD:bdj9tcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/paramparse/paramparse.go#L79)):*
> ```Go
> 		d = v.Duration
> 	default:
> 		err = pgerror.Newf(pgcode.InvalidParameterValue,
> ```

should we allow  DInts here? doesn't seem that important, just curious
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwjiMJl-VTywNfnkOBq:-MwjiMJl-VTywNfnkOBr:b9ggl2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L373)):*
> ```Go
> 	)
> 
> 	statsCloseCh := make(chan struct{})
> ```

nit: should the channel have a size of 1?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwjmV1I0Cj7x_7KO-vl:-MwjmV1I0Cj7x_7KO-vm:bhz0k1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L408)):*
> ```Go
> 
> 	if ttlSettings.RowStatsPollInterval != 0 {
> 		g.GoCtx(func(ctx context.Context) error {
> ```

random thought: i'm not familiar with this part of the code, but should this use RunAsyncTask?
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwlLX5x5PteKxuxyzJ8:-MwlLX5x5PteKxuxyzJ9:b-soydp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L566)):*
> ```Go
> 					ctx,
> 					c.opName,
> 					txn,
> ```

nit: seems like it could be simpler to pass in a `nil` txn. then you can get rid of the `DB.Txn` and `SET TRANSACTION` parts, just need to keep:
```
				datums, err := execCfg.InternalExecutor.QueryRow(
					ctx,
					c.opName,
					nil,
					fmt.Sprintf(c.query, details.TableID),
					c.args...,
				)
				if err != nil {
					return err
				}
				c.gauge.Update(int64(*datums[0].(*tree.DInt)))
				return nil
```
and modify `c.query` so it has an AOST clause
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 573 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwlLiD0Ex2EBu3-63ov:-MwlLiD0Ex2EBu3-63ow:b-quu5h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L573)):*
> ```Go
> 					return err
> 				}
> 				c.gauge.Update(int64(*datums[0].(*tree.DInt)))
> ```

nit: use `tree.MustBeDInt`

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/paramparse/paramparse.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-Mwji8oK-mdK20POkdBi:-MwmXmxcBnj3YPQuxnfo:bx7l7qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/paramparse/paramparse.go#L79)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we allow  DInts here? doesn't seem that important, just curious
</blockquote></details>

not imo, would that be s or ms or ns ...
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwjiMJl-VTywNfnkOBq:-MwmXr1j7gM8scHyceeF:bawi8wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L373)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should the channel have a size of 1?
</blockquote></details>

no, it's just closed and not used in any way.
___
*[pkg/sql/ttl/ttljob/ttljob.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-MwjmV1I0Cj7x_7KO-vl:-MwmY4ia2LiGkuAClmR5:b182b8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/714e75f2bdf43d960fbb479b7ced8a081dc30907/pkg/sql/ttl/ttljob/ttljob.go#L408)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

random thought: i'm not familiar with this part of the code, but should this use RunAsyncTask?
</blockquote></details>

runasynctask doesn't have a way to wait(). i'd rather goroutines be accounted for (for now) and block wait at the end

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-Mx6VruyEQnKsow5kzxI:-Mx6VruyEQnKsow5kzxJ:b-atis77) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cf5b12a079abcb3766f93d2eeceb00c4ccbb799/pkg/sql/ttl/ttljob/ttljob.go#L420)):*
> ```Go
> 					return nil
> 				case <-time.After(ttlSettings.RowStatsPollInterval):
> 					fetchStatistics(ctx, p.ExecCfg(), details, metrics, aostDuration)
> ```

hm, obviously this compiled, but a bit confused how since nothing gets returned in this branch.

**Review by otan — COMMENTED** [review]
bors r=rafiss

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-:-Mx7dNLiDzh3tcnGxkkR:bx70i2y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/ttl/ttljob/ttljob.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76837#-Mx6VruyEQnKsow5kzxI:-Mx7dJ3u-EMeFRnWaXtx:b9b5oss) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cf5b12a079abcb3766f93d2eeceb00c4ccbb799/pkg/sql/ttl/ttljob/ttljob.go#L420)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, obviously this compiled, but a bit confused how since nothing gets returned in this branch.
</blockquote></details>

it's in a for loop so continuously executes until stats is closed

**Pull request merged**
