### PR TITLE
logictests: reduce scope of overly broad, brittle tests

### PR DESCRIPTION
**Pull request by dt**
Several logic tests were using SELECT queries that would enumerate the entire set of all system tables, or worse all columns/indexes/constraints of all system tables, or similarly enumerating the set and properties of the set of all intenral tables/views/etc. These tests were all thus extremely brittle to any changes in those sets, causing toil and friction in the form of needing to update them whenever wholly unrelated functionality, that has nothing to do with the ability to inspect catalogs/grants/tables that these tests exist to verify, was being modified and required adding or changing system tables. 

These overly broad tests, that asserted far more than required, would then be unable to run in mixed version configs where there are changes the underlying sets.

Furthermore, they required such frequent updates by unrelated changes as mentioned above that it had become standard practice to simply blindly run `--rewrite` on them but this completely defeats the point of having test in the first place, as doing so, and unconditionally changing the test to just assert any new behavior it observes is the expected behavior, means it can no longer actually catch real, unintended regressions in the behaviors it observes.

This diff updates the vast majority of these tests to choose just few example objects from the system or internal catalog they inspect when testing functionality that enumerates it, so that the asserted enumeration is restricted to this deliberate subset of the larger, potentially more volatile sets of tables or columns and grants. This can allow these tests to continue to check that enumerating tools correctly render the properties a view or a table or a column or grant, without needing to be updated every time these larger sets change, avoiding the problems described above.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136891)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136891#-ODSxCTp-VYWqwlNh6oJ:-ODSxCTp-VYWqwlNh6oK:b-gee8s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad803ccdf1b37e13ecb2c8dcc6fc8d435fe221f/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L286)):*
> ```Go
> 			WHERE target LIKE 'TABLE system.public.%'
> 			    AND raw_config_sql NOT LIKE '%global_reads = true%'
> 					AND target = 'TABLE system.public.locations'
> ```

Nit: This looks like an okay change. Do we want a safety query to also confirm RBR tables  do not appear inside SHOW ALL ZONE CONFIGURATIONS as well

**Comment by dt** [comment]
@fqazi it looked like the special tables were already being checked in the case before this one so this one was just checking the rest, so I picked a specific  one -- locations -- to check instead of enumerating all tables. If there are other specific tables that would be interesting to include here I'm not opposed to including them, as long as it is specifically chosen tables rather than the entire set.

**Comment by fqazi** [comment]
> it looked like the special tables were already being checked in the case before this one so this one was just checking the rest, so I picked a specific one -- locations -- to check instead of enumerating all tables. If there are other specific tables that would be interesting to include here I'm not opposed to including them, as long as it is specifically chosen tables rather than the entire set.

My suggestion was to just confirm the list of intentionally RBR tables as a sanity, which should be a fixed subset as well.

**Pull request merged**
