### PR TITLE
release-21.1: storage: fix read behavior for large key-values

### PR DESCRIPTION
**Pull request by sumeerbhola**
Backport 1/1 commits from #61872.

/cc @cockroachdb/release

---

pebbleMVCCScanner no longer has a 128MB limit on the size
of the key-value pair it can read.

Release justification: Fix for high-severity bug in existing
functionality. The pebbleMVCCScanner change prevents a panic
if a key-value pair larger than 128MB gets written, which
affected a customer cluster.

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62262#-:-MWPAVUM-N1bGpwcSso4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by itsbilal** [comment]
`TestMVCCScanWithLargeKeyValue` seems to have failed to finish in CI.

**Comment by petermattis** [comment]
> TestMVCCScanWithLargeKeyValue seems to have failed to finish in CI.

CI machines have less memory than our laptops. Could that be a factor somehow?

**Comment by sumeerbhola** [comment]
According to https://teamcity.cockroachdb.com/project.html?tab=testDetails&testNameId=-5380595815773845523&projectId=Cockroach_UnitTests&buildTypeId=Cockroach_UnitTests_Testrace&branch_Cockroach_UnitTests=%3Cdefault%3E it always succeeds on master under testrace

**Comment by sumeerbhola** [comment]
This is slow under race due to the flushes and compactions caused by the large values. I am going to `skip.UnderRace` -- it is still unclear to me why master does not exhibit the same behavior.

```
=== RUN   TestMVCCScanWithLargeKeyValue
I210330 18:25:32.816183 71 storage/in_mem.go:64  [-] 1  engine creation is randomly setting oldClusterVersion: false, enabledSeparated: false
I210330 18:25:32.823559 71 3@vendor/github.com/cockroachdb/pebble/version_set.go:156  [pebble] 2  [JOB 1] MANIFEST created 000001
I210330 18:25:32.824001 71 3@vendor/github.com/cockroachdb/pebble/open.go:305  [pebble] 3  [JOB 1] WAL created 000002
I210330 18:25:32.826669 89 3@vendor/github.com/cockroachdb/pebble/table_stats.go:118  [pebble] 4  [JOB 2] all initial table stats loaded
TestMVCCScanWithLargeKeyValue 0: 2021-03-30 14:25:35.067608231 -0400 EDT m=+2.430192667
TestMVCCScanWithLargeKeyValue 1: 2021-03-30 14:25:35.068163508 -0400 EDT m=+2.430747879
I210330 18:26:01.813966 71 3@vendor/github.com/cockroachdb/pebble/db.go:1449  [pebble] 5  [JOB 3] WAL created 000004
TestMVCCScanWithLargeKeyValue 2: 2021-03-30 14:26:01.816081687 -0400 EDT m=+29.178666051
I210330 18:26:01.816468 91 3@vendor/github.com/cockroachdb/pebble/compaction.go:1415  [pebble] 6  [JOB 4] flushing 2 memtables to L0
I210330 18:26:01.816905 91 3@vendor/github.com/cockroachdb/pebble/compaction.go:2034  [pebble] 7  [JOB 4] flushing: sstable created 000005
TestMVCCScanWithLargeKeyValue 3: 2021-03-30 14:26:01.841383355 -0400 EDT m=+29.203967760
I210330 18:26:07.390108 91 3@vendor/github.com/cockroachdb/pebble/compaction.go:1472  [pebble] 8  [JOB 4] flushed 2 memtables to L0 [000005] (7.0 M), in 5.6s, output rate 1.3 M/s
I210330 18:26:07.393606 5 3@vendor/github.com/cockroachdb/pebble/compaction.go:1840  [pebble] 9  [JOB 5] compacting L0 [000005] (7.0 M) + L6 [] (0 B)
I210330 18:26:07.394532 5 3@vendor/github.com/cockroachdb/pebble/compaction.go:1881  [pebble] 10  [JOB 5] compacted L0 [000005] (7.0 M) + L6 [] (0 B) -> L6 [000005] (7.0 M), in 0.0s, output rate 290 G/s
I210330 18:26:35.867578 71 3@vendor/github.com/cockroachdb/pebble/db.go:1449  [pebble] 11  [JOB 6] WAL created 000006 (recycled 000002)
TestMVCCScanWithLargeKeyValue before scan: 2021-03-30 14:26:35.869318489 -0400 EDT m=+63.231902892
I210330 18:26:35.869606 7 3@vendor/github.com/cockroachdb/pebble/compaction.go:1415  [pebble] 12  [JOB 7] flushing 2 memtables to L0
I210330 18:26:35.870045 7 3@vendor/github.com/cockroachdb/pebble/compaction.go:2034  [pebble] 13  [JOB 7] flushing: sstable created 000007


ERROR: signal: killed

1 runs completed, 1 failures, over 1m11s
```

**Pull request merged**
