### PR TITLE
sql/opt: add external YCSB tests

### PR DESCRIPTION
**Pull request by nvb**
This commit adds optimizer tests for the query suite found in YCSB.
These statements are all almost simple enough that these kinds of
tests are unnecessary, but they will be useful to have while building
out support for implicit row-level locking during the initial row-fetch
phase of UPDATE and DELETE statements.

Specifically, right now we see three interesting pieces of information
in these plans:
1. the UPDATE statement's scan does not use a row-level locking mode.
This will change when we switch it to use one implicitly.
2. the UPDATE statement's scan retrieves the primary column family
and the column family of the field its intending to update. In order
to not regress performance by increasing contention, we'll need to
avoid Upgrade locking the primary column family when UPDATEing only
a single field. Hopefully, this will be as easy as marking all other
columns as NOT NULL and making the notion of the "sentinel column
family" a little more flexible.
3. the SELECT statement in the read-modify-write transaction does not
use a FOR UPDATE clause so it does not perform any row-level locking.
At some point, I intend to explore adding a FOR UPDATE clause to the
statement and observing whether it improves performance.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44178#-:-Lz9BXBH2LDf-cdwzpxV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by nvanbenschoten** [comment]
> The UPDATE statement's scan retrieves the primary column family and the column family of the field its intending to update. In order to not regress performance by increasing contention, we'll need to avoid Upgrade locking the primary column family when UPDATEing only a single field. Hopefully, this will be as easy as marking all other columns as NOT NULL and making the notion of the "sentinel column family" a little more flexible.

This logic isn't in the optimizer like I thought it was. It's actually here:

https://github.com/cockroachdb/cockroach/blob/13fe121aaf8936c0ca21aff6f1929a7433f10af6/pkg/sql/sqlbase/index_encoding.go#L247-L249

We should be able to remove this restriction if any of the other column families that are already being fetched are guaranteed to exist due to `NOT NULL` constraints.

**Comment by nvanbenschoten** [comment]
@solongordon actually pointed out this exact optimization in:
https://github.com/cockroachdb/cockroach/blob/13fe121aaf8936c0ca21aff6f1929a7433f10af6/pkg/sql/sqlbase/index_encoding.go#L265-L268

@solongordon do you have any interest in addressing this? It turns out that it's going to be very important for improving YCSB performance when we add implicit row-level locking to UPDATE statements.

**Comment by nvanbenschoten** [comment]
We have access to the full `TableDescriptor` in all callers of `NeededColumnFamilyIDs`, so it doesn't look like addressing this will be too invasive.

**Comment by nvanbenschoten** [comment]
It actually looks very small. I'll see if I can knock it out right now so you don't have to page this stuff back in.

**Comment by solongordon** [comment]
I actually implemented this back in September as part of a bug fix, but we decided it was too risky for the stability period and to just always scan column family 0 instead. I meant to revive it after the branch was cut but didn't get around to it. Happy for you to knock it out now if it's easy. Otherwise I should be able to get to it in the next week. My original PR is here if it's helpful: https://github.com/cockroachdb/cockroach/pull/41136

Note that you also need column family 0 if any of the needed columns have composite encodings.

**Comment by solongordon** [comment]
Also worth checking in with @rohany to make sure we get this logic right for secondary indexes, now that they respect column families too.

**Comment by nvanbenschoten** [comment]
Oh nice, I had forgotten about that PR. I'll leave this to you then since you already have it all written out. Thanks @solongordon!

**Pull request merged**
