### PR TITLE
eval: reduce interface->interface conversions in ComparisonWithSubOperator

### PR DESCRIPTION
**Pull request by mgartner**
#### colexecproj: add benchmark for colexecproj.defaultCmpRConstProjOp

Release note: None

#### eval: reduce interface->interface conversions in ComparisonWithSubOperator

Consider the schema and queries below.

    CREATE TABLE a (a STRING);
    INSERT INTO a SELECT 'abc' || i::STRING FROM generate_series(1, 500) g(i);

    CREATE TABLE b (b STRING);
    INSERT INTO b SELECT 'abc' || i::STRING FROM generate_series(1, 75000) g(i);

    CREATE TABLE c (c STRING);

    SELECT * FROM b
    WHERE b IN (SELECT a FROM a) OR
          b IN (SELECT c FROM c);

A significant portion of time is spent performing `tree.Expr` to
`tree.Datum` conversions when evaluating the `IN` expressions. This
commit eliminates those unnecessary conversions, drastically speeding up
execution of the query.

Release note (performance improvement): Some types of queries with
comparisons with constant values now execute faster.

### CODE REVIEW

**Comment by mgartner** [comment]
I couldn't figure out how to get a micro-benchmark to show the speedup - any help appreciated. Do we ever write end-to-end benchmarks in SQL? Seems like that'd be easier in this case.

When running the slow query in the example above here's the CPU flamegraph before:

image


And here's the flamegraph after:

image

Notice the `runtime.assertI2I` and `runtime.convI2I` are eliminated.

**Review by michae2 — APPROVED** [review]
:lgtm: :fire: very nice!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-:-NCgnvEtDcAiQ3v4kfr8:begacn5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/colexec/colexecproj/default_cmp_op_test.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-NCgn6cg9m8LN_Rdocn0:-NCgn6cg9m8LN_Rdocn1:bonrrvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4baa642744a286675fe1fe531c17f10f2ec0d0b7/pkg/sql/colexec/colexecproj/default_cmp_op_test.go#L148)):*
> ```Go
> 			inputTypes = []*types.T{types.String, types.String}
> 			var sb strings.Builder
> 			sb.WriteString("@1 IN (")
> ```

I think the expression needs to use `IS DISTINCT FROM` with a constant on the right side. E.g.:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE t (s STRING);
CREATE TABLE


Time: 12ms total (execution 11ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> EXPLAIN (VEC, VERBOSE) SELECT s IS DISTINCT FROM 'a' FROM t;
                        info
----------------------------------------------------
  │
  └ Node 1
    └ *colflow.BatchFlowCoordinator
      └ *colexecbase.simpleProjectOp
        └ *colexecprojconst.defaultCmpRConstProjOp
          └ *colexecutils.vectorTypeEnforcer
            └ *colexecutils.CancelChecker
              └ *colfetcher.ColBatchScan
(8 rows)


Time: 10ms total (execution 10ms / network 0ms)
```

**Review by yuzefovich — COMMENTED** [review]
Nice find!

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-:-NCur9A66Xy_T5s1Dkrn:bdkgtm2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/colexec/colexecproj/default_cmp_op_test.go` line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-NCuqAIO8QIhrj0hVsKm:-NCuqAIO8QIhrj0hVsKn:b-vaqszv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d71bc6f1cf08a4bb5d6a90a44a7f6b088b7f1d21/pkg/sql/colexec/colexecproj/default_cmp_op_test.go#L169)):*
> ```Go
> 			projectingExpr := sb.String()
> 			name = fmt.Sprintf("IN/useSel=%t/hasNulls=%t", useSel, hasNulls)
> 			benchmarkProjOp(b, name, func(source *colexecop.RepeatableBatchSource) (colexecop.Operator, error) {
> ```

nit: it might be a bit cleaner to extract the construction of the `projectingExpr`s outside of the `for` loop and then add another outer dimension for another `for` loop to iterate over the two bench cases.
___
*[`pkg/sql/colexec/colexecproj/default_cmp_op_test.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-NCgn6cg9m8LN_Rdocn0:-NCupVDX0m4i5mzYU2Jm:b-i46ej3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4baa642744a286675fe1fe531c17f10f2ec0d0b7/pkg/sql/colexec/colexecproj/default_cmp_op_test.go#L148)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think the expression needs to use `IS DISTINCT FROM` with a constant on the right side. E.g.:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE t (s STRING);
CREATE TABLE


Time: 12ms total (execution 11ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> EXPLAIN (VEC, VERBOSE) SELECT s IS DISTINCT FROM 'a' FROM t;
                        info
----------------------------------------------------
  │
  └ Node 1
    └ *colflow.BatchFlowCoordinator
      └ *colexecbase.simpleProjectOp
        └ *colexecprojconst.defaultCmpRConstProjOp
          └ *colexecutils.vectorTypeEnforcer
            └ *colexecutils.CancelChecker
              └ *colfetcher.ColBatchScan
(8 rows)


Time: 10ms total (execution 10ms / network 0ms)
```
</blockquote></details>

The issue is that `IN` has an optimized version, so the default cmp operator is not planned. We need to use `ANY` instead of `IN` here (i.e. something like `@1 = ANY (`, etc) to get the default cmp op. We have subqueries in the original reproduction, so under the hood it uses `Any` too.

**Review by mgartner — COMMENTED** [review]
The benchmark now shows the speed up:

```
name                                                              old time/op    new time/op    delta
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=false-16     140µs ± 4%     136µs ± 1%    -3.01%  (p=0.016 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=true-16      136µs ± 3%     128µs ± 2%    -5.43%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=false-16      138µs ± 1%     133µs ± 3%    -3.43%  (p=0.032 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=true-16       130µs ± 0%     125µs ± 1%    -3.46%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=false-16        21.1ms ± 2%    10.2ms ± 2%   -51.96%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=true-16         20.5ms ± 1%     9.8ms ± 2%   -52.36%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=false-16         21.2ms ± 2%    10.1ms ± 0%   -52.47%  (p=0.016 n=5+4)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=true-16          20.6ms ± 2%     9.7ms ± 3%   -52.88%  (p=0.008 n=5+5)

name                                                              old speed      new speed      delta
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=false-16   117MB/s ± 4%   121MB/s ± 1%    +3.07%  (p=0.016 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=true-16    121MB/s ± 3%   128MB/s ± 2%    +5.72%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=false-16    119MB/s ± 1%   123MB/s ± 3%    +3.57%  (p=0.032 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=true-16     126MB/s ± 0%   131MB/s ± 1%    +3.59%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=false-16       390kB/s ± 0%   804kB/s ± 2%  +106.15%  (p=0.016 n=4+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=true-16        400kB/s ± 0%   840kB/s ± 2%  +110.00%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=false-16        386kB/s ± 2%   806kB/s ± 3%  +108.81%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=true-16         396kB/s ± 2%   850kB/s ± 0%  +114.65%  (p=0.016 n=5+4)

name                                                              old alloc/op   new alloc/op   delta
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=false-16     108kB ± 0%     107kB ± 0%    -0.99%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=true-16     98.0kB ± 0%    97.6kB ± 0%    -0.39%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=false-16      109kB ± 0%     108kB ± 0%    -1.11%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=true-16      96.0kB ± 0%    97.3kB ± 0%    +1.28%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=false-16        54.6kB ± 0%    53.9kB ± 0%    -1.20%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=true-16         47.7kB ± 0%    49.6kB ± 0%    +4.07%  (p=0.029 n=4+4)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=false-16         54.7kB ± 0%    53.7kB ± 0%    -1.99%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=true-16          47.5kB ± 0%    48.4kB ± 0%    +1.86%  (p=0.008 n=5+5)

name                                                              old allocs/op  new allocs/op  delta
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=false-16     1.98k ± 0%     1.98k ± 0%    +0.15%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=false/hasNulls=true-16      1.80k ± 0%     1.80k ± 0%    -0.11%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=false-16      2.00k ± 0%     1.98k ± 0%    -1.00%  (p=0.008 n=5+5)
DefaultCmpProjOp/IS_DISTINCT_FROM/useSel=true/hasNulls=true-16       1.76k ± 0%     1.78k ± 0%    +1.13%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=false-16         1.00k ± 0%     1.00k ± 0%    +0.50%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=false/hasNulls=true-16            902 ± 0%       910 ± 0%    +0.89%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=false-16            986 ± 0%      1000 ± 0%    +1.42%  (p=0.008 n=5+5)
DefaultCmpProjOp/eq_ANY_const/useSel=true/hasNulls=true-16             887 ± 0%       891 ± 0%    +0.45%  (p=0.008 n=5+5)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-:-NCwIWyD6hV3dJV8gCOX:bkugzb0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/colexec/colexecproj/default_cmp_op_test.go` line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-NCuqAIO8QIhrj0hVsKm:-NCwIVssBpFJXARkrNH3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d71bc6f1cf08a4bb5d6a90a44a7f6b088b7f1d21/pkg/sql/colexec/colexecproj/default_cmp_op_test.go#L169)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it might be a bit cleaner to extract the construction of the `projectingExpr`s outside of the `for` loop and then add another outer dimension for another `for` loop to iterate over the two bench cases.
</blockquote></details>

Done.
___
*[`pkg/sql/colexec/colexecproj/default_cmp_op_test.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-NCgn6cg9m8LN_Rdocn0:-NCwIRVhDX_jd5EQTpve:bjp8qba) ([raw file](https://github.com/cockroachdb/cockroach/blob/4baa642744a286675fe1fe531c17f10f2ec0d0b7/pkg/sql/colexec/colexecproj/default_cmp_op_test.go#L148)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The issue is that `IN` has an optimized version, so the default cmp operator is not planned. We need to use `ANY` instead of `IN` here (i.e. something like `@1 = ANY (`, etc) to get the default cmp op. We have subqueries in the original reproduction, so under the hood it uses `Any` too.
</blockquote></details>

Thank you! That was the missing piece.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

nit: don't forget to update the PR description.

Do you have an intuition for why we're seeing 2x increase in allocations? That seems suspicious.

> Reviewed 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-:-NCwUWka2xm2P728n5Jt:b-4lrapw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by yuzefovich — APPROVED** [review]
Oh, scratch that - it's 2x improvement in speed, lol. Never mind.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88638#-:-NCwUo2LDH09pdAUXXN9:b9g8fb0)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by mgartner** [comment]
TFTRs and the help @michae2 and @yuzefovich!

bors r+

**Comment by mgartner** [comment]
I think it might be nice to get this into 22.2.1.

blathers backport 22.2

**Pull request merged**
