### PR TITLE
docs: propose an RFC to clarify namespaces

### PR DESCRIPTION
**Pull request by knz**
cc @bdarnell @jseldess  @nvanbenschoten

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13319)

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrrUZ7hbxnMLsildCK:-KbrrUZ7hbxnMLsildCL:b5tmwio) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L116)):*
> ```Markdown
>   the physical storage location is "zone".
> 
> - Someone who has learned the word "Database" with MySQL needs to be
> ```

What specifically do these people need to learn? (I'm one of them) My understanding of what you've said so far is that there are some capabilities that MySQL users may not be aware of (renaming tables across databases), but I wouldn't say that teaching MySQL users about this is a major concern of ours (I didn't know that mysql had this limitation)

---

*[docs/RFCS/namespaces.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrsraNY-g9NdyZftEW:-KbrsraNY-g9NdyZftEX:blvba0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L134)):*
> ```Markdown
> When looking at the table above, consider how far we could go by:
> 
> 1. renaming the word "database" to "schema" throughout our documentation
> ```

In general I'd favor adjusting our terminology to match postgres. We started out trying to "simplify" our SQL dialect instead of hewing closely to any particular implementation (which led us to choose mysqlisms because we were most familiar with that database), but now we care more about being compatible with postgres. 

---

*[docs/RFCS/namespaces.md, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrxdWshVsQViXdJvpg:-KbrxdWshVsQViXdJvph:bf55d6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L136)):*
> ```Markdown
> 1. renaming the word "database" to "schema" throughout our documentation
>    and all user-visible SQL interfaces; and
> 2. start using the word "database" for the collection of all schemas
> ```

This would be a significant backwards-compatibility break (`CREATE DATABASE` is all over [our example code](https://github.com/cockroachdb/examples-go/blob/5d6d4c7ee7fcaa86348fd01e9cec952856ecda37/block_writer/main.go#L164). Alternative: treat "database" and "schema" as synonyms and come up with a new name for the scope between cluster and schema. 

---

*[docs/RFCS/namespaces.md, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrtsO0iFwVOxfNAbr-:-KbrtsO0iFwVOxfNAbr0:bxt1syt) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L138)):*
> ```Markdown
> 2. start using the word "database" for the collection of all schemas
>    stored in a cluster; and
> 3. create a default schema when initializing an empty cluster, and use that
> ```

This seems orthogonal to the question of what we call our namespaces. I'm not sure how I feel about it. It would be easier (and creating databases is a significant practical pain point with mysql in things like test frameworks. It's not as bad for us since we let you connect to a database/schema that doesn't exist yet and create it once connected), but it seems to also encourage bad habits. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by arjunravinarayan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuBgcD0JQXTMC-9Stl:-KbuBgcD0JQXTMC-9Stm:b550ao6) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L119)):*
> ```Markdown
>   educated about the nuances available in other products, including
>   CockroachDB.
> ```

This RFC was a wonderful read in its descriptions of the current state of things (i.e. up to this line). Beyond that, I'm not sure I'm on board with the prescriptions you suggest. I think the more cautious thing to do is to follow @bdarnell 's advice, and try and match postgres in a best-effort way, without breaking backward compatibility. Second, I think if we added some careful documentation that states what you have said above, that would be close to sufficient. 

That said, my confidence in my own views is very low as this is quite new to me (so thank you for writing up the description! I learned a lot.), so do take that into account as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by cuongdo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrsraNY-g9NdyZftEW:-KbuExqz65Yk6qzmdY0l:b-yn7x66) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L134)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In general I'd favor adjusting our terminology to match postgres. We started out trying to "simplify" our SQL dialect instead of hewing closely to any particular implementation (which led us to choose mysqlisms because we were most familiar with that database), but now we care more about being compatible with postgres. 
</blockquote></details>

I think it depends on who we see as the earlier adopters of CockroachDB. As having used mostly MySQL myself, I'm much more familiar with "databases" than "schemas".

---

*[docs/RFCS/namespaces.md, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrxdWshVsQViXdJvpg:-KbuFCqJ3j7RN2umqXGL:b-rysfn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L136)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This would be a significant backwards-compatibility break (`CREATE DATABASE` is all over [our example code](https://github.com/cockroachdb/examples-go/blob/5d6d4c7ee7fcaa86348fd01e9cec952856ecda37/block_writer/main.go#L164). Alternative: treat "database" and "schema" as synonyms and come up with a new name for the scope between cluster and schema. 
</blockquote></details>

I very much agree with this. Treating "database" and "schema" as the same, for now, leaves possibilities open for the future and defers the cost and cognitive load of schemas for our users until there's a clear need for a distinct notion of schemas.

---

*[docs/RFCS/namespaces.md, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuGh0N0Q6rkcJQxf22:-KbuGh0OmqZ6jBZorS-c:b-7s55gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L154)):*
> ```Markdown
> - the step "creating a database" can be elided from tutorials: create a cluster, create a table, bam, done. *Easier adoption and onboarding.*
> 
> - online resources available to users of other SQL products is more transparently reusable with CockroachDB. *Easier mindshare.*
> ```

Again, it depends on who we hypothesize would be the first to adopt us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by cuongdo** [comment]
*[docs/RFCS/namespaces.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrsraNY-g9NdyZftEW:-KbuGrRy3Y6FeDLQS9ul:b-yhvbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L134)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I think it depends on who we see as the earlier adopters of CockroachDB. As having used mostly MySQL myself, I'm much more familiar with "databases" than "schemas".
</blockquote></details>

Also, even having used Oracle a long time ago, as an application developer (rather than a DBA), I was exposed more to databases than schemas or whatever the Oracle equivalent is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by dianasaur323** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrsraNY-g9NdyZftEW:-KbuVSwGML29oNKNXfZp:brvgeba) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L134)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Also, even having used Oracle a long time ago, as an application developer (rather than a DBA), I was exposed more to databases than schemas or whatever the Oracle equivalent is.
</blockquote></details>

Raphael - thanks for writing this up. I may not be in the best position to provide feedback on this, but I'll do my best to give my two cents. I see where the confusion could lie in terms of differentiating database vs schema, but this would be a pretty big change as Ben points out later. Perhaps the solution is to clearly document what the word "database" means for us.

---

*[docs/RFCS/namespaces.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuXIg21vadG6qMTutQ:-KbuXIg3mfOaX2bCtCGF:b-33zqx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L161)):*
> ```Markdown
>   could then be simply named "database", keeping the word "cluster"
>   for the surrounding container.
> ```

This is an interesting point. Limited knowledge here, but we could probably still accomplish this by setting permissions on the database (aka schema) level, and then at the cluster (aka database) level right? The terminology is confusing, but it might be too late to make this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrrUZ7hbxnMLsildCK:-Kc4Z2C6XR2KWBmB90qj:b-w4atu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L116)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What specifically do these people need to learn? (I'm one of them) My understanding of what you've said so far is that there are some capabilities that MySQL users may not be aware of (renaming tables across databases), but I wouldn't say that teaching MySQL users about this is a major concern of ours (I didn't know that mysql had this limitation)
</blockquote></details>

I added two points to clarify what I had in mind.

---

*[docs/RFCS/namespaces.md, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrsraNY-g9NdyZftEW:-Kc4_LuJCSJq45cK7_Tp:bbdblde) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L134)):*
<details><summary><i>Previously, dianasaur323 (Diana Hsieh) wrote…</i></summary><blockquote>

Raphael - thanks for writing this up. I may not be in the best position to provide feedback on this, but I'll do my best to give my two cents. I see where the confusion could lie in terms of differentiating database vs schema, but this would be a pretty big change as Ben points out later. Perhaps the solution is to clearly document what the word "database" means for us.
</blockquote></details>

Thanks to all of you. I have reworked the phrasing to make "schema" and "database" synonyms in the product (for backward compatibility) and also promote our recommended understanding in docs, as you suggest Diana.

---

*[docs/RFCS/namespaces.md, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrxdWshVsQViXdJvpg:-Kc4_itYRbwu6uViqwvs:b52i0t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L136)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I very much agree with this. Treating "database" and "schema" as the same, for now, leaves possibilities open for the future and defers the cost and cognitive load of schemas for our users until there's a clear need for a distinct notion of schemas.
</blockquote></details>

Ok let's make them synonyms in the product, that is not a big deal. (We can always promote one more over the other)

---

*[docs/RFCS/namespaces.md, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrtsO0iFwVOxfNAbr-:-Kc4_rZmfE28ILQ0Py1N:bo2n3tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L138)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This seems orthogonal to the question of what we call our namespaces. I'm not sure how I feel about it. It would be easier (and creating databases is a significant practical pain point with mysql in things like test frameworks. It's not as bad for us since we let you connect to a database/schema that doesn't exist yet and create it once connected), but it seems to also encourage bad habits. 
</blockquote></details>

What bad habits are you thinking about?
We already have a predefined schema "system"; and here I am advocating the existence of another called "default" where user-level tables get created. 

A prod database can then disable this default schema by removing privileges to it for all users.

---

*[docs/RFCS/namespaces.md, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuGh0N0Q6rkcJQxf22:-Kc4a6CPlVYLrDaOC44j:blsicfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L154)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

Again, it depends on who we hypothesize would be the first to adopt us.
</blockquote></details>

In terms of how "serious" we want our audience to be, I'd rather get people who know/like pg to adopt cockroachdb than people who like mysql.

---

*[docs/RFCS/namespaces.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuXIg21vadG6qMTutQ:-Kc4aIREVwKFOWEGWJGP:b-nhwk99) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L161)):*
<details><summary><i>Previously, dianasaur323 (Diana Hsieh) wrote…</i></summary><blockquote>

This is an interesting point. Limited knowledge here, but we could probably still accomplish this by setting permissions on the database (aka schema) level, and then at the cluster (aka database) level right? The terminology is confusing, but it might be too late to make this change.
</blockquote></details>

So what you propose is indeed possible.

Meanwhile I certainly think it is not too late to revisit this, anything at this level is fair game before 1.0 and I *very much* would like us to be in a more future-proof place before we commit to backward compatibility.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-Kc4YlBr7BH5VKA-q2I5:-Kc4YlBs6Qc_IkyXIHPY:b-betzgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L74)):*
> ```Markdown
> | Namespace level      | MSSQL    | PostgreSQL | CockroachDB | MySQL    | SQLLite  | Oracle     |
> |----------------------|----------|------------|-------------|----------|----------|------------|
> | Transactional store  | (global) | Database   | (cluster)   | Server   | Database | (global)   |
> ```

nit: This would be a bit easier to think about if these were in the same order as their description in `methodology`

---

*[docs/RFCS/namespaces.md, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-Kc4Z9wTEgLw0CJR6QK2:-Kc4Z9wTEgLw0CJR6QK3:b-3ze2pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L75)):*
> ```Markdown
> |----------------------|----------|------------|-------------|----------|----------|------------|
> | Transactional store  | (global) | Database   | (cluster)   | Server   | Database | (global)   |
> | Privilege container  | Database | Database   | (cluster)   | Database | N/A      | Database   |
> ```

how does cluster compare to global? If they have the same logical meaning (a single deployment), I'd use the same terminology

---

*[docs/RFCS/namespaces.md, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-Kc4_I39_a6tb1wIDQok:-Kc4_I39_a6tb1wIDQol:b-we7h2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L112)):*
> ```Markdown
> - In most SQL products other than CockroachDB, there's a strong
>   semantic binding between the intuition of where data is physically
>   storage and the word "database". In CockroachDB, the word "database"
> ```

`s/is physically storage/is physically stored`

---

*[docs/RFCS/namespaces.md, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-Kc4guqghyK3W2dVIepJ:-Kc4guqghyK3W2dVIepK:bsm63lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d8595c8f179535ccc829e3bb934c7a27b97d98/docs/RFCS/namespaces.md#L72)):*
> ```Markdown
> Using these definitions we can recognize the following conceptual mapping:
> 
> | Namespace level      | MSSQL    | PostgreSQL | CockroachDB | MySQL    | SQLLite  | Oracle     |
> ```

Discussed in person: it might be interesting to note here how a few popular NoSQL databases organize their logical hierarchies as well. I can imagine a large chunk of future-CockroachDB users coming from a strictly NoSQL background, so bridging any conceptual gaps for them will also be important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by dianasaur323** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuXIg21vadG6qMTutQ:-Kc4mI7NoiLgHBPRyxit:b-2vgu2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L161)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So what you propose is indeed possible.

Meanwhile I certainly think it is not too late to revisit this, anything at this level is fair game before 1.0 and I *very much* would like us to be in a more future-proof place before we commit to backward compatibility.
</blockquote></details>

Your suggestion to make database and schema synonyms for now, while introducing the term schema seems to be a first initial approach to address this issue as well as the others discussed above. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/namespaces.md, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrrUZ7hbxnMLsildCK:-Kc5E2jZIg_TxWv2Mznp:b9a5txp) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L116)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I added two points to clarify what I had in mind.
</blockquote></details>

Hmm, all of those things seem true of MySQL as well, as I understand things. MySQL calls its unit of storage organization "tablespaces" and it allows tables to renamed across databases when the storage configuration allows it. It may not be an exact match for the corresponding features in other databases, but the basic concepts are there. Let's drop the sniping at mysql - the reason to shift our terminology towards what postgres is using is not that it's better than the mysql terminology, but that it's what we're doing everywhere else. (and being consistently compatible with one existing system is better than mixing up expressions from different ones)

---

*[docs/RFCS/namespaces.md, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbrtsO0iFwVOxfNAbr-:-Kc5GTTZ0na3eEquWzbh:b-vvav1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L138)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What bad habits are you thinking about?
We already have a predefined schema "system"; and here I am advocating the existence of another called "default" where user-level tables get created. 

A prod database can then disable this default schema by removing privileges to it for all users.
</blockquote></details>

The bad habit I'm thinking about is just that people will just put everything in the default schema rather than disabling it and using schemas when they would be appropriate (the predefined "system" schema doesn't have this risk since you can't put new tables there). But I don't know that this is something worth worrying about - after all, it's analogous to the home/desktop folder that people can clutter up as much as they want and them move to a more organized system when they feel it's appropriate. 

---

*[docs/RFCS/namespaces.md, line 154 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-KbuGh0N0Q6rkcJQxf22:-Kc5ILBSn3oSZuq29Ojm:b91c7w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/168122075361921acfcc87d9fb9871e121ef1608/docs/RFCS/namespaces.md#L154)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

In terms of how "serious" we want our audience to be, I'd rather get people who know/like pg to adopt cockroachdb than people who like mysql.
</blockquote></details>

I want to attract users from both postgres and mysql. In fact, despite our technical and philosophical alignment with postgres, I think there's reason to believe that a large fraction of our early adopters will be coming from a mysql background (mysql's replication support is/was considered to be better than postgresql's, at least until relatively recently). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319)*

**Comment by knz** [comment]
FWIW I just downloaded and installed [DBeaver](http://dbeaver.jkiss.org/) to test #14238 and was surprised at how nice a GUI it is; also it can connect to CockroachDB. However DBeaver also very prominently displays the difference between databases and schemas, and the way we currently present them through our SQL interface makes DBeaver think that CockroachDB tables are actually pg schemas, and is thus unable to inspect the tables.  See screenshot:
schermafdruk_2017-03-17_16-58-06

**Comment by benesch** [comment]
Additional namespacing food for thought re: indices. Index names in CockroachDB are namespaced to their table, so it's possible to have two indices in the same database with the same name:

```sql
CREATE TABLE t1 (a int);
CREATE TABLE t2 (a int);
CREATE INDEX i ON t1 (a);
CREATE INDEX i ON t2 (a);
```

The preferred syntax for altering an index is, correspondingly,

```sql
ALTER INDEX t1@i
```

which disambiguates between the two `i` indices. Most unfortunately, for Postgres compatibility, we support `ALTER INDEX <unqualified_idx_name>`, which assumes that indices live in a global (schema-scoped) namespace and fails when two indices have the same name:

```sql
ALTER INDEX i RENAME TO j;
pq: index name "i" is ambiguous (found in d.t2 and d.t1)
```

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13319#-:-KxiJZIA9r7T4AvxJ2Xt:b-91h3gb)*

**Comment by knz** [comment]
We have successfully introduced logical schemas in 2.0 and the remaining work is captured in #26443.

Closing this.

**Pull request closed without merging**
