### PR TITLE
storage: default COCKROACH_RAFT_LOG_SYNC to false

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13509)

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM

**Review by mberhault — APPROVED** [review]

**Comment by tamird** [comment]
Was there some discussion here? I thought the reason for defaulting to true was that not doing so is a lie.

**Comment by petermattis** [comment]
See #13507.

**Comment by petermattis** [comment]
Also, the TODO comment in the code mentions the reason.

**Comment by tamird** [comment]
OK. It is a shame that neither the commit nor the PR reference that issue.

**Comment by petermattis** [comment]
> OK. It is a shame that neither the commit nor the PR reference that issue.

Yes, and yet the world still turns.

**Comment by petermattis** [comment]
(It's not like we're going to forget about this).

**Comment by tamird** [comment]
Right, but this is the kind of thing that makes it difficult to understand
why things are being done without consuming the fire hose.

**Pull request merged**
