### PR TITLE
util: modify FastIntSet to continue using the small set when large is non-nil

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, once an element outside the range of [0, 63] was inserted
into a FastIntSet, the "small" field was wiped. This patch modifies
FastIntSet so that even once the "large" field is initialized, the
"small" set is still maintained. This speeds up binary set operations
involving one "small" FastIntSet and one "large" FastIntSet.

Once the "large" set is in use, values are stored in both "large" and
"small" sets. The "small" set simply serves as a fast path in this case.

Average planning times for support issue 383 vs master:
Master: 25.9494ms
New: 7.0738ms

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-:-MCmYzRKC2QFXd4jF4MY:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/util/fast_int_set.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmYOZtCA8gJrEtkjvV:-MCmYOZtCA8gJrEtkjvW:b-xcq4vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a166baa7488d9bb965b2b8d87fe7d33172d89d3/pkg/util/fast_int_set.go#L26)):*
> ```Go
> 	// We use a uint64 as long as all elements are between 0 and 63. If we add an
> 	// element outside of this range, we switch to Sparse. We don't just use the
> 	// latter directly because it's larger and can't be passed around by value.
> ```

This comment needs an update.
___
*[pkg/util/fast_int_set.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmYd6T-aIurZi_Rzj7:-MCmYd6T-aIurZi_Rzj8:b-qdude0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a166baa7488d9bb965b2b8d87fe7d33172d89d3/pkg/util/fast_int_set.go#L249)):*
> ```Go
> 		return
> 	}
> ```

could add a case here to just clear `s.large` if `rhs.large == nil`

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51635)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmYOZtCA8gJrEtkjvV:-MCmdIxh1HYfU6xxMhI6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a166baa7488d9bb965b2b8d87fe7d33172d89d3/pkg/util/fast_int_set.go#L26)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment needs an update.
</blockquote></details>

Done.
___
*[pkg/util/fast_int_set.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmYd6T-aIurZi_Rzj7:-MCmdRLE8a5rKc-DJtC_:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a166baa7488d9bb965b2b8d87fe7d33172d89d3/pkg/util/fast_int_set.go#L249)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

could add a case here to just clear `s.large` if `rhs.large == nil`
</blockquote></details>

Good idea. Done.

**Comment by DrewKimball** [comment]
@RaduBerinde I've also added an optimization to ForEach in addition to the changes you suggested.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-:-MCmnrlN2-pAMI82Vbjb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmnapC9Qkh1svu_yBH:-MCmnapD23fAiFIKtTrH:b68xkrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/805cdcdb5bf4c828bb22a08757c08e4aa78cf763/pkg/util/fast_int_set.go#L170)):*
> ```Go
> 	if s.large != nil {
> 		// Start iterating from the element where small left off.
> 		for x := i + 1; x != intsets.MaxInt; x = s.large.LowerBound(x + 1) {
> ```

This should just start at the `smallCutoff`.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51635)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/util/fast_int_set.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmnapC9Qkh1svu_yBH:-MCmrihD0wGQeKgUFPvo:b-6476sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/805cdcdb5bf4c828bb22a08757c08e4aa78cf763/pkg/util/fast_int_set.go#L170)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should just start at the `smallCutoff`.
</blockquote></details>

Actually it's just plain wrong, since negative values are possible. I'll just revert to the old version.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-:-MCmsgER5g-80IzmzYb8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/util/fast_int_set.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51635#-MCmnapC9Qkh1svu_yBH:-MCmscmz60SYiOROzgG5:bdcv6l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/805cdcdb5bf4c828bb22a08757c08e4aa78cf763/pkg/util/fast_int_set.go#L170)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Actually it's just plain wrong, since negative values are possible. I'll just revert to the old version.
</blockquote></details>

Good point.

**Pull request merged**
