### PR TITLE
roachtest: add a mixed-ver follower-reads test

### LINKED ISSUE #59683: kvserver, roachtest: run follower_reads roachtest in mixed-version cluster
In 21.1 we're re-[working](https://github.com/cockroachdb/cockroach/issues/57397) [how](https://github.com/cockroachdb/cockroach/issues/57408) [closed timestamps](https://github.com/cockroachdb/cockroach/issues/57410) are propagated throughout the system. A critical challenge to this is ensuring that follower reads continue to work in a mixed-version cluster, as some nodes will still be using the [existing side-transport mechanism.](https://github.com/cockroachdb/cockroach/blob/293c931cf6c9c55c41c7a7a4ab30dc08fa07b45c/pkg/kv/kvserver/closedts/closedts.go#L11-L10)

We should add a variant of the existing [follower reads roachtest](https://github.com/cockroachdb/cockroach/blob/5e7341ac87ca18b7e9a80dbb71f8e9f3a1f834e4/pkg/cmd/roachtest/follower_reads.go#L40-L39) that exercises its workload on a mixed-version cluster.

### PR DESCRIPTION
**Pull request by andreimatei**
Closes #59683.

It seems good to have a test checking that the closed timestamp
mechanism stays compatible between versions. Particularly since 21.1
changes it completely from 20.2.

This patch also makes the existing closed timestamps more sensitive by
analyzing more timeseries.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
I still want to add something to this test - intervals of reads/writes alternating with intervals of just reads (what we currently have) - to exercise the closed timestamps more. But I wanted to get the PR out before vacay.

The new test needs #64394 on both 20.2 and 21.1 in order to pass.

The first two commits are elsewhere.

**Review by andreimatei — COMMENTED** [review]
This is ready for review.

The new mixed-version test can't be merged until we release 21.1.2 and make that the previous version, as it needs to follower reads fixes we've made (#64394).


Release note: None

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-:-MaUjOX25OqYmqbg92AD:b-auqtms)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
Sorry for letting this sit. This looks like a great addition to the testing story around here.

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-:-MatJs8wDsXXlhSMB42G:bappilj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/cmd/roachtest/follower_reads.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatHVdODoy4zwZxRp2l:-MatHVdODoy4zwZxRp2m:b-4pv92l) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L98)):*
> ```Go
> 	regional     localitySetting = "regional"
> 	global       localitySetting = "global"
> 	singleRegion localitySetting = "single-region"
> ```

This is strange to me. `single-region` is not a table locality setting, which this data type was meant to indicate. Perhaps we should add another boolean field to `topologySpec` that indicates whether the database has multiple regions added to it or not.
___
*[pkg/cmd/roachtest/follower_reads.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatI3EW-nQSmg993GAv:-MatI3EW-nQSmg993GAw:b-yrfssg) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L298)):*
> ```Go
> 	} else {
> 		// The leaseholder and one of the nodes in the non-primary region that has
> 		// two replicas.
> ```

Does this need to be based on the survival goal? With zone survival, the topology will be `{3 voters}, {1 non voter, 1 empty}, {1 non voter}`. For region survival, the topology will be `{2 voters, 1 empty}, {2 voters}, {1 voter}`.

But also, this is dependent on the node count, right ?
___
*[pkg/cmd/roachtest/follower_reads.go, line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatIiOv5-SCFe_kUcTE:-MatIiOv5-SCFe_kUcTF:b-ppfw56) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L309)):*
> ```Go
> 		// We don't do this for singleRegion since, in a single region, there's no
> 		// low latency and high-latency regimes.
> 		verifySQLLatency(ctx, c, t, c.Node(1), start, end, 20*time.Millisecond)
> ```

20ms is still pretty high. Would be interesting at some point to try to drop this down and see what falls out while trying to stabilize the test. But I wouldn't do that unless we're motivated to do the second part.
___
*[pkg/cmd/roachtest/follower_reads.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatJMSO-DN74Pcs1XiT:-MatJMSO-DN74Pcs1XiU:b-ani4he) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L631)):*
> ```
> The first 20 seconds are ignored, as a "ramp-up" period.
> ```
Is this still true?
___
*[pkg/cmd/roachtest/follower_reads.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatJ_PM48KDtaop2mCg:-MatJ_PM48KDtaop2mCh:b-6n4mio) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L744)):*
> ```Go
> }
> 
> func runFollowerReadsMixedVersionSingleRegionTest(
> ```

Could you add a comment to this explaining what the test is doing and why it's useful to look at follower reads even when in a single region? Something about how, even in a single region, a gateway node will try to serve follower reads when possible, so this is still a test of the closed timestamp system.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64443)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/cmd/roachtest/follower_reads.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatHVdODoy4zwZxRp2l:-MblI4DY-dhMU9A5MK_a:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L98)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is strange to me. `single-region` is not a table locality setting, which this data type was meant to indicate. Perhaps we should add another boolean field to `topologySpec` that indicates whether the database has multiple regions added to it or not.
</blockquote></details>

done
___
*[pkg/cmd/roachtest/follower_reads.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatI3EW-nQSmg993GAv:-MblNKiMAESFCU0_vdjv:b-snbv0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L298)):*
> Does this need to be based on the survival goal? With zone survival, the topology will be {3 voters}, {1 non voter, 1 empty}, {1 non voter}. For region survival, the topology will be {2 voters, 1 empty}, {2 voters}, {1 voter}.

All the replicas are supposed to serve follower reads, except the leaseholder. So the only thing that matters is the number of nodes and the replication factor. For the topology used by these tests, the replication factor is 5 in both the zone and the region-survival cases. Improved the comment.


> But also, this is dependent on the node count, right ?

Yes, added comments.
___
*[pkg/cmd/roachtest/follower_reads.go, line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatIiOv5-SCFe_kUcTE:-MblX5MH4OEC2eUhTYKr:b-x7o1zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L309)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

20ms is still pretty high. Would be interesting at some point to try to drop this down and see what falls out while trying to stabilize the test. But I wouldn't do that unless we're motivated to do the second part.
</blockquote></details>

yeah... next time
___
*[pkg/cmd/roachtest/follower_reads.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatJMSO-DN74Pcs1XiT:-MblXSBMBJaBJsGcInFf:bogcyhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L631)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> The first 20 seconds are ignored, as a "ramp-up" period.
> ```
Is this still true?
</blockquote></details>

no, removed
___
*[pkg/cmd/roachtest/follower_reads.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-MatJ_PM48KDtaop2mCg:-MblYF2P3074mKdFYiMp:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d4182935cf76684c1f411310989098bb9b49d/pkg/cmd/roachtest/follower_reads.go#L744)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a comment to this explaining what the test is doing and why it's useful to look at follower reads even when in a single region? Something about how, even in a single region, a gateway node will try to serve follower reads when possible, so this is still a test of the closed timestamp system.
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-:-MbrOpMwB9LFYcWjmqcu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64443#-:-McB_NZi8en7Tn3sZWtD:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Pull request merged**
