### PR TITLE
config: introduce pseudo "tenants" zone

### LINKED ISSUE #48123: sql/kv: remove all uses of keyutils.TestingSQLCodec (previously keys.TODOSQLCodec)
We want to remove uses of `keysutils.TestingSQLCodec` (previously `keys.TODOSQLCodec`) then remove that codec altogether.

Dependencies:

- Feature work:
  - [x] table/db details in admin server HTTP API  #82879
  - [x] `cockroach debug backup export` #82878 
  - [ ] KV replication reports #82881 - use renamed to `FIXMEIDONTKNOWWHICHCODECTOUSE` in #99774

- Test code:
  - [x] backup TestPublicIndexTableSpans, check two keyspaces #82882   
  - [x] tenant streaming TestRandomClientGeneration, plumb proper codec #82883  
  - [x] columnar execution, TestSpanAssembler, check two keyspaces #82884 
  - [x] row / jobs, TestJobBackedSeqChunkProvider, plumb proper codec #82886  
  - [ ] keysutils/pretty_scanner (used by replication reports), plumb proper codec #100004 / #82881  

Jira issue: CRDB-4356
Epic: CRDB-26091

### LINKED ISSUE #49318: sql: ALTER TABLE statement issued by tenant cannot find relation
Modifying the logic test harness to set an explicit tenant ID:
```
diff --git a/pkg/server/testserver.go b/pkg/server/testserver.go
index 67d805b16f..9a7490c1a7 100644
--- a/pkg/server/testserver.go
+++ b/pkg/server/testserver.go
@@ -527,7 +527,14 @@ func testSQLServerArgs(ts *TestServer) sqlServerArgs {
 // StartTenant starts a SQL tenant communicating with this TestServer.
 func (ts *TestServer) StartTenant() (addr string, _ error) {
        ctx := context.Background()
+       if _, err := ts.InternalExecutor().(*sql.InternalExecutor).Exec(
+               ctx, "testserver-create-tenant", nil /* txn */, "SELECT crdb_internal.create_tenant(10)",
+       ); err != nil {
+               return "", err
+       }
+
        args := testSQLServerArgs(ts)
+       args.tenantID = roachpb.MakeTenantID(10)
```

And running the following test:
```
# LogicTest: 3node-tenant

statement ok
CREATE TABLE x (x int)

statement ok
INSERT INTO x VALUES (1)

query I
SELECT * FROM x
----
1

statement error operation is unsupported
ALTER TABLE x CONFIGURE ZONE USING num_replicas = 123
```

Fails on the `ALTER TABLE` statement.
```
        expected:
        operation is unsupported
        got:
        pq: relation "x" does not exist
```

cc @tbg @nvanbenschoten

### LINKED ISSUE #49445: sql: gcjob and opt need ZoneConfig which is not available on tenants
See

https://github.com/cockroachdb/cockroach/blob/c37f28f03d58122392946104ac53bac47e271935/pkg/sql/gcjob/refresh_statuses.go#L95

The way we've designed clearing up after a `DROP TABLE` is fundamentally incompatible with a hard split between KV and SQL, unless we add a way for the SQL layer to figure out the zone config for a given table from the KV backend. The other way to do this is to push the responsibility for cleaning up into KV, which is a bigger change but is "better" in the sense that it doesn't rely on the SQL tenant process running (which often won't be the case after the TTL).

We should be able to hard-code a value here instead for the time being.

Similar in opt:

https://github.com/cockroachdb/cockroach/blob/74741e6794ffedacfc9962b353ed65c8ef2e0321/pkg/sql/opt/xform/coster.go#L754

We have a pretty hard dependency on reasoning about the physical location of data. Here there seems no way around it, we need to be able to resolve table ID to localities, and this becomes a blocker the moment we go geo-distributed.

cc @nvanbenschoten

### PR DESCRIPTION
**Pull request by nvb**
Fixes #49318.
Fixes #49445.
Progress towards #48123.
Informs #48774.

This commit introduces a new pseudo object ID in the system tenant's namespace called "tenants". Like "liveness" and "timeseries" before it, the pseudo object allows zone configurations to be applied to pseudo-objects that do not live directly in the system tenant's SQL keyspace. In this case, the "tenants" zone allows zone configurations to be set by the system tenant and applied to all other tenants in the system. There may come a time when we want secondary tenants to have more control over their zone configurations, but that will require a much larger change to the zone config structure and UX as a whole.

While making this change, we rationalize the rest of zone configuration handling and how it relates to multi-tenancy. Now that secondary tenant ranges have a zone config to call their own, we can make sense of calls from SQL into the zone configuration infrastructure. We gate off calls that don't make sense for secondary tenants and clean up hooks in SQL that handle zone config manipulation.

All of this works towards a good cause - we eliminate the remaining uses of `keys.TODOSQLCodec` from `pkg/sql/...` and `pkg/config/...`, bringing us a big step closer towards being able to remove the placeholder and close #48123.

This work also reveals that in order to address #48774, we need to be able to determine split points from the SystemConfig. This makes it very difficult to split on secondary tenant object (e.g. table) boundaries. However, it makes it straightforward to split on secondary tenant keysapce boundaries. This is already what we were thinking (see #47907), so out both convenience and desire, I expect that we'll follow this up with a PR that splits Ranges only at secondary tenant boundaries - placing the overhead of an otherwise empty tenant at only a single Range and a few KBs of data.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Glad to see this! Do we have an issue to track post phase 2 work for tenant zone configs once #49445 is closed? We should create one if not.

I'll rerun the logic tests to see which blacklists can be removed.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 5 of 5 files at r3, 44 of 44 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-:-M8oGG-_CLW_Xm9xBHd-:b-tcbeqx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @nvanbenschoten, and @tbg)

___
*[pkg/sql/drop_table.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oSj9I3Qn8sctBcCs9:-M8oSj9I3Qn8sctBcCsA:bxxukrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/sql/drop_table.go#L354)):*
> ```Go
> 	// this faster mechanism.
> 	if tableDesc.IsTable() && !tableDesc.IsInterleaved() {
> 		// TODO BEFORE MERGING: confirm that we can delete this.
> ```

I think so. Based on https://github.com/cockroachdb/cockroach/commit/7abac2f025ea32fd596124152652f665685ad713, this code was added as a sanity check. OOC, how would this inability to get a zone config for a dropped tenant table have manifested itself otherwise? Would the default TTL be applied?
___
*[pkg/sql/logictest/testdata/logic_test/tenant_unsupported, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oUW84CkJq2FHl5cOy:-M8oUW84CkJq2FHl5cOz:b-p1vi66) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/sql/logictest/testdata/logic_test/tenant_unsupported#L37)):*
> ```
> # https://github.com/cockroachdb/cockroach/issues/49318 is fixed.
> # statement error operation is unsupported
> # ALTER TABLE kv CONFIGURE ZONE USING num_replicas = 123
> ```

You can probably delete this.

**Review by tbg — APPROVED** [review]
:lgtm_strong: looks good!

> Now that secondary tenant ranges have a zone config to call their own, we can make sense of calls from SQL into the zone configuration infrastructure. We gate off calls that don't make sense for secondary tenants and clean up hooks in SQL that handle zone config manipulation.

This left me slightly confused. Secondary tenants don't really get to do anything with the zone configs, or am I missing something? All they will see is the default zone config (configured at startup). Your description made it sound as if tenants can do... something with the zone config, but I don't think you even let them list the "background" config that applies to them.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 5 of 5 files at r3, 44 of 44 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-:-M8oeVXTBk_pCBWR-1GL:bc86ed9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @nvanbenschoten)

___
*[pkg/config/system.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8obvj89mLCwYe0p8tq:-M8obvj89mLCwYe0p8tr:buvvzf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L207)):*
> ```Go
> 
> 	// No maximum specified; maximum ID is the last entry in the descriptor
> 	// table.
> ```

or the largest pseudo ID, whichever is larger.
___
*[pkg/config/system.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8ocCnXBSQ0kGU4tZTH:-M8ocCnXBSQ0kGU4tZTI:b-sco3i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L221)):*
> ```Go
> 	// Maximum specified: need to search the descriptor table. Binary search
> 	// through all descriptor table values to find the first descriptor with ID
> 	// >= maxID.
> ```

and pick either it or maxPseudoID.
___
*[pkg/config/system.go, line 229 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oc2ll1Bj8HOKNzvzv:-M8oc2ll1Bj8HOKNzvzw:bgov761) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L229)):*
> ```Go
> 		}
> 		var id uint32
> 		id, err = keys.TODOSQLCodec.DecodeDescMetadataID(searchSlice[i].Key)
> ```

This can't be intentional, at least not without a comment.
___
*[pkg/keys/constants.go, line 399 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8odMA50GxBGjm400s7:-M8odMA50GxBGjm400s8:b-7iod8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/keys/constants.go#L399)):*
> ```Go
> // PseudoTableIDs is the list of ids from above that are not real tables (i.e.
> // there's no table descriptor). They're grouped here because the cluster
> // bootstrap process needs to create splits for them; splits for the tables
> ```

Can you revisit the "because the bootstrap process needs to create splits for them"? I think I remember that it does create splits for the tables with these IDs (which don't exist). I think something is fishy here, it's not like this package has any notion of where the split points that correspond to these pseudoIDs are. Probably the comment makes no sense.
___
*[pkg/sql/zone_config.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8obPS63X5NlxffBvhX:-M8obPS63X5NlxffBvhY:bf05x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e0a47635459941d7b21846db4ea663aebf413/pkg/sql/zone_config.go#L159)):*
> ```Go
> func ZoneConfigHook(
> 	cfg *config.SystemConfig, id uint32,
> ) (*zonepb.ZoneConfig, *zonepb.ZoneConfig, bool, error) {
> ```

While you're here, explain the retvals?

**Review by nvb — COMMENTED** [review]
TFTRs!

> Do we have an issue to track post phase 2 work for tenant zone configs once #49445 is closed?

I opened https://github.com/cockroachdb/cockroach/issues/49854 to track this.

> This left me slightly confused.

Reworded.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-:-M8wEojWA9XqUK-673Ar:bcgy60o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @tbg)

___
*[pkg/config/system.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8obvj89mLCwYe0p8tq:-M8w88RH2meXTvDjLh6a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L207)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

or the largest pseudo ID, whichever is larger.
</blockquote></details>

Done.
___
*[pkg/config/system.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8ocCnXBSQ0kGU4tZTH:-M8w8I658OerkeohltPM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L221)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

and pick either it or maxPseudoID.
</blockquote></details>

Done.
___
*[pkg/config/system.go, line 229 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oc2ll1Bj8HOKNzvzv:-M8w8UD2ACIapbuoDDRH:b-w9n16i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b34698d9289eaf20ce8b011bd7319e234d0797a/pkg/config/system.go#L229)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This can't be intentional, at least not without a comment.
</blockquote></details>

This was a drive-by fix. The code was subtly broken before. We could hit an error while decoding and then overwrite it on the next iteration. I added a test that tests a case that would have previously been handled incorrectly.
___
*[pkg/keys/constants.go, line 399 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8odMA50GxBGjm400s7:-M8wFTuV8FCCmJbdTt3O:bpu8ulq) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/keys/constants.go#L399)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you revisit the "because the bootstrap process needs to create splits for them"? I think I remember that it does create splits for the tables with these IDs (which don't exist). I think something is fishy here, it's not like this package has any notion of where the split points that correspond to these pseudoIDs are. Probably the comment makes no sense.
</blockquote></details>

I'm not sure I understand the ask. We do create splits for these tables, even though they don't really exist. Do you take issue with the `keys` package mentioning split points?
___
*[pkg/sql/drop_table.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oSj9I3Qn8sctBcCs9:-M8wHIJY7sX0dt8MnM5z:b64y9rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/sql/drop_table.go#L354)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think so. Based on https://github.com/cockroachdb/cockroach/commit/7abac2f025ea32fd596124152652f665685ad713, this code was added as a sanity check. OOC, how would this inability to get a zone config for a dropped tenant table have manifested itself otherwise? Would the default TTL be applied?
</blockquote></details>

Thanks for confirming. It looks like an inability to get a zone config for a dropped tenant table will now manifest as an error being thrown by `updateStatusForGCElements` from the call to `GetZoneConfigForObject`. I don't think there's ever a case where a table wouldn't have an associated zone config though, and David seemed to think this was pointless, so I'm going to remove it.
___
*[pkg/sql/zone_config.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8obPS63X5NlxffBvhX:-M8w400NANIcCXsJV2xV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f5e0a47635459941d7b21846db4ea663aebf413/pkg/sql/zone_config.go#L159)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

While you're here, explain the retvals?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/tenant_unsupported, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-M8oUW84CkJq2FHl5cOy:-M8wJFSr0KgV9Y8ynXrr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a399d9b8a03eda2f9f51a038128e1b8b4b8816/pkg/sql/logictest/testdata/logic_test/tenant_unsupported#L37)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You can probably delete this.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-:-M8ymRCY81eGj7qRnuBb:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @tbg)

**Review by tbg — COMMENTED** [review]
:lgtm:

> Reviewed 47 of 47 files at r5, 4 of 4 files at r6, 5 of 5 files at r7, 3 of 3 files at r8, 44 of 44 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49784#-:-M8ynvw44iTWCI670CjN:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @dt, and @tbg)

**Pull request merged**
