### PR TITLE
sql: change system.tenant_usage to use a single consumption column

### PR DESCRIPTION
**Pull request by RaduBerinde**
There are ongoing discussions about adding more components to the RU
cost. The prospect of having to change the columns of
`system.tenant_usage` each time is daunting.

This commit modifies the table to use a single `total_consumption`
column which encodes the TenantConsumption proto. We can add fields to
the proto in the future without changing the schema.

The values are still readable via SQL using `pb_to_json`:
```
crdb_internal.pb_to_json('cockroach.roachpb.TenantConsumption', total_consumption)
```

Informs #68479.

Release note: None

Release justification: Necessary change for supporting changes to the
cost model for the upcoming Serverless MVP release. This functionality
is only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
I think this is fine. I do get the drive to avoid the schema changes. The counter-argument to the pain of adding such columns is the relative ease of this change. When we go and do things like this, it does tend to leave me wondering about the experience that our customers have writing sql.

The change itself :lgtm:.

This is going to break the clusters which @darinpp has been prototyping with, no? That's probably fine, just want to call it out. 

> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkcdkmbDzKdA9YuaGxT:b-i9t5il)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @celiala, and @RaduBerinde)

___
*[pkg/migration/migrations/tenant_usage.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcerCLApTiN6oFy4Yg:-MkcerCLApTiN6oFy4Yh:b-9nnp9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/migration/migrations/tenant_usage.go#L61)):*
> ```Go
> 		  DROP COLUMN total_sql_pod_cpu_seconds,
> 		  ADD COLUMN total_consumption BYTES FAMILY "primary"`,
> 		schemaExistsFn: hasColumn,
> ```

A paranoid part of me might make me feel better if there were some way to compose this `hasColumn` check with some form of `notHasColumn` that ensures the other columns are gone. I'm not too worried about it. This framework is a bit brittle for my liking but alas, it's better than nothing. 
___
*[pkg/sql/catalog/systemschema/system.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcdHGCCB2pHcULf9Rb:-MkcdHGD4EAuzyudiZyS:b-rmtijm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/sql/catalog/systemschema/system.go#L591)):*
> ```Go
> 
> 	-- Current shares value for this instance.
>   instance_shares FLOAT,
> ```

nit while you're here: align the indentation of this column and generally within this statement
___
*[pkg/sql/catalog/systemschema/system.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcdRLi26T88dzS_dAJ:-MkcdRLi26T88dzS_dAK:b-hfcar) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/sql/catalog/systemschema/system.go#L591)):*
> ```Go
> 
> 	-- Current shares value for this instance.
>   instance_shares FLOAT,
> ```

would we ever be in the game of protobuf-ing instance state too?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

The migration will reset existing tenant consumption on existing clusters, but shouldn't lead to crashes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkcgOF_BgJstE_iGd_G:b-6xa2uu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, and @celiala)

___
*[pkg/migration/migrations/tenant_usage.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcerCLApTiN6oFy4Yg:-MkciMkADe8wQWlalUqO:bkd5ega) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/migration/migrations/tenant_usage.go#L61)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

A paranoid part of me might make me feel better if there were some way to compose this `hasColumn` check with some form of `notHasColumn` that ensures the other columns are gone. I'm not too worried about it. This framework is a bit brittle for my liking but alas, it's better than nothing. 
</blockquote></details>

Added a TODO
___
*[pkg/sql/catalog/systemschema/system.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcdHGCCB2pHcULf9Rb:-MkchQ552Cx9_c6-p7WO:b-f9n6gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/sql/catalog/systemschema/system.go#L591)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit while you're here: align the indentation of this column and generally within this statement
</blockquote></details>

Fixed. There was a mix of tabs and spaces, changed everything to spaces.
___
*[pkg/sql/catalog/systemschema/system.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkcdRLi26T88dzS_dAJ:-MkchbziD1Bjxj5wj5hV:b-n5fadm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccdabc98f668184c141c9c55cb6af77c77a01061/pkg/sql/catalog/systemschema/system.go#L591)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

would we ever be in the game of protobuf-ing instance state too?
</blockquote></details>

I don't think so..

**Review by RaduBerinde — COMMENTED** [review]
> The counter-argument to the pain of adding such columns is the relative ease of this change

The bigger problem is not the change itself but the versioning - we can't add new versions in patch releases (right?) and that would make it impossible to add an RU component to 21.2.x.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkciW1ZBXbZiTD4IuWm:b-a59mfu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, and @celiala)

**Comment by andy-kimball** [comment]
Should we consider having a strongly-typed "total_ru_usage" column, but a weakly typed protobuf column for the component metrics? Having to crack a protobuf to see how many RUs have been used seems very painful.

**Comment by RaduBerinde** [comment]
Great idea, added a commit:

#### sql: add crdb_internal.tenant_usage_details

This commit adds a virtual view which decodes the tenant consumption
details. Example:
```
root@:26257/defaultdb> select * from crdb_internal.tenant_usage_details;
  tenant_id |     total_ru      | total_read_bytes | total_read_requests | total_write_bytes | total_write_requests | total_sql_pod_seconds
------------+-------------------+------------------+---------------------+-------------------+----------------------+------------------------
        123 | 9618.311247130436 |           751504 |                4660 |             47485 |                 1877 |     4.454030256529996
```

Release note: None

Release justification: Necessary change for supporting changes to the
cost model for the upcoming Serverless MVP release. This functionality
is only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 2 files at r3, 2 of 5 files at r6, 9 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkhIAoRAoFB6yLN4w64:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andy-kimball, @celiala, @dt, and @RaduBerinde)

___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-Mkh9M3H8eebPbjr1ZI9:-Mkh9M3H8eebPbjr1ZIA:b3fp8rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0228b9f62e319f6fe3c8cd2001c680602eda156/pkg/ccl/backupccl/backup_planning_tenant.go#L37)):*
> ```Go
> 	  tenants.id = tenant_usage.tenant_id AND tenant_usage.instance_id = 0`
> 
> func tenantMetadataFromRow(row tree.Datums) (descpb.TenantInfoWithUsage, error) {
> ```

defensive programming thought: want to assert the number of columns here? I'm not really worried about it but an assertion failure would be better than a panic if it were to happen. 
___
*[pkg/sql/crdb_internal.go, line 5326 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkhE91OAzmbdNFsBrU_:-MkhE91OAzmbdNFsBrUa:bhdb64p) ([raw file](https://github.com/cockroachdb/cockroach/blob/76202f736d8ae877e282949140d2305ab5bac7b4/pkg/sql/crdb_internal.go#L5326)):*
<details><summary><i alt="summary">Quoted 18 lines of code…</i></summary>

> ```
> CREATE VIEW crdb_internal.tenant_usage_details AS
> SELECT
>   tenant_id,
>   (j->>'rU')::FLOAT AS total_ru,
> 	(j->>'readBytes')::INT AS total_read_bytes,
> 	(j->>'readRequests')::INT AS total_read_requests,
> 	(j->>'writeBytes')::INT AS total_write_bytes,
> 	(j->>'writeRequests')::INT AS total_write_requests,
> 	(j->>'sqlPodsCpuSeconds')::FLOAT AS total_sql_pod_seconds
> FROM (
>   SELECT
> 	  tenant_id,
> 		crdb_internal.pb_to_json('cockroach.roachpb.TenantConsumption', total_consumption) AS j
> 	FROM
> 	  system.tenant_usage
> 	WHERE
> 	  instance_id = 0
> )`,
> ```
</details>

nit: sqlfmt this again?

```sql
CREATE VIEW crdb_internal.tenant_usage_details AS
  SELECT
    tenant_id,
    (j->>'rU')::FLOAT8 AS total_ru,
    (j->>'readBytes')::INT8 AS total_read_bytes,
    (j->>'readRequests')::INT8 AS total_read_requests,
    (j->>'writeBytes')::INT8 AS total_write_bytes,
    (j->>'writeRequests')::INT8 AS total_write_requests,
    (j->>'sqlPodsCpuSeconds')::FLOAT8 AS total_sql_pod_seconds
  FROM
    (
      SELECT
        tenant_id,
        crdb_internal.pb_to_json(
          'cockroach.roachpb.TenantConsumption',
          total_consumption
        )
          AS j
      FROM
        system.tenant_usage
      WHERE
        instance_id = 0
    );
```

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkhbO0j-2uTZ86cxd5Y:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andy-kimball, @celiala, and @dt)

___
*[pkg/ccl/backupccl/backup_planning_tenant.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-Mkh9M3H8eebPbjr1ZI9:-MkhaQpU1qLpUYTa5aUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0228b9f62e319f6fe3c8cd2001c680602eda156/pkg/ccl/backupccl/backup_planning_tenant.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

defensive programming thought: want to assert the number of columns here? I'm not really worried about it but an assertion failure would be better than a panic if it were to happen. 
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 5326 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-MkhE91OAzmbdNFsBrU_:-Mkhar348lqgC-VrA__p:bqxtbnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/76202f736d8ae877e282949140d2305ab5bac7b4/pkg/sql/crdb_internal.go#L5326)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> CREATE VIEW crdb_internal.tenant_usage_details AS
> SELECT
>   tenant_id,
>   (j->>'rU')::FLOAT AS total_ru,
> 	(j->>'readBytes')::INT AS total_read_bytes,
> 	(j->>'readRequests')::INT AS total_read_requests,
> 	(j->>'writeBytes')::INT AS total_write_bytes,
> 	(j->>'writeRequests')::INT AS total_write_requests,
> 	(j->>'sqlPodsCpuSeconds')::FLOAT AS total_sql_pod_seconds
> FROM (
>   SELECT
> 	  tenant_id,
> 		crdb_internal.pb_to_json('cockroach.roachpb.TenantConsumption', total_consumption) AS j
> 	FROM
> 	  system.tenant_usage
> 	WHERE
> 	  instance_id = 0
> )`,
> ```
nit: sqlfmt this again?

```sql
CREATE VIEW crdb_internal.tenant_usage_details AS
  SELECT
    tenant_id,
    (j->>'rU')::FLOAT8 AS total_ru,
    (j->>'readBytes')::INT8 AS total_read_bytes,
    (j->>'readRequests')::INT8 AS total_read_requests,
    (j->>'writeBytes')::INT8 AS total_write_bytes,
    (j->>'writeRequests')::INT8 AS total_write_requests,
    (j->>'sqlPodsCpuSeconds')::FLOAT8 AS total_sql_pod_seconds
  FROM
    (
      SELECT
        tenant_id,
        crdb_internal.pb_to_json(
          'cockroach.roachpb.TenantConsumption',
          total_consumption
        )
          AS j
      FROM
        system.tenant_usage
      WHERE
        instance_id = 0
    );
```
</blockquote></details>

Done. Again mixing tabs with spaces was the problem.

**Comment by RaduBerinde** [comment]
Unrelated flake (filed #70839).

bors r+

**Comment by yuzefovich** [comment]
Looks like the generated code is not up to date.

bors r-

**Comment by RaduBerinde** [comment]
> Looks like the generated code is not up to date.

How come? The failure looks like a flake in `acceptance/cli/node-status`.

**Comment by yuzefovich** [comment]
I'm looking at the CI build on this PR in isolation: https://teamcity.cockroachdb.com/viewLog.html?buildId=3510938&buildTypeId=Cockroach_UnitTests

**Comment by RaduBerinde** [comment]
> I'm looking at the CI build on this PR in isolation: https://teamcity.cockroachdb.com/viewLog.html?buildId=3510938&buildTypeId=Cockroach_UnitTests

And? There is a flake (TestMultiRegionDataDriven/regional_by_table, tracked by https://github.com/cockroachdb/cockroach/issues/70846) and a timeout..

**Comment by yuzefovich** [comment]
The generated code issue is above:
Screen Shot 2021-09-28 at 3 35 06 PM

**Comment by yuzefovich** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=3510935&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_CheckGeneratedCode

**Comment by RaduBerinde** [comment]
Ah, thanks, I missed that!

**Review by jaylim-crl — COMMENTED** [review]
If I understand correctly, `tenant_usage_details` is going to be available only to the KV cluster, right? I'd imagine we won't leak data if a regular tenant tries to query that internal table?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70778#-:-MkqifDu4mdH6ZGEZ4lN:b-utwoxl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
Correct. The tenant has their own tenant_usage table which should just be empty (and modifying it would be inconsequential). Ideally, these wouldn't exist at all on the tenant but I think we're missing a bit of infrastructure to make that happen.

**Pull request merged**
