### PR TITLE
sqlccl: plumb sstsize to dist csv import

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-:-KuR-FCSa41WP1EKq1Wa:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 892 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAR4HIRAMBZfimnmI:-KuRAR4HIRAMBZfimnmJ:bpxioht) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L892)):*
> ```Go
> }
> 
> // LoadCSV TODO(dan): This entire method is a placeholder to get the distsql
> ```

what's going on with this TODO?

---

*[pkg/sql/distsql_physical_planner.go, line 914 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAFxja1QCJqhcsx6g:-KuRAFxja1QCJqhcsx6h:b-407s9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L914)):*
> ```Go
> 	nullif *string,
> 	walltime int64,
> 	splitSize int64,
> ```

these arguments surely deserve comments :)
also nit: put the unit in the name

---

*[pkg/sql/distsql_physical_planner.go, line 916 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAxoxH4G6cV9SgVN0:-KuRAxoxH4G6cV9SgVN1:b-p5b5ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L916)):*
> ```Go
> 	splitSize int64,
> ) error {
> 	const oversample = 3
> ```

what's this? I think it deserves a comment.

---

*[pkg/sql/distsql_physical_planner.go, line 930 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRB9zcuc0ZuXaaJnPH:-KuRB9zcuc0ZuXaaJnPI:b-6pnae9) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L930)):*
> ```Go
> 		// TODO(mjibson): attempt to intelligently schedule http files to matching cockroach nodes
> 		rcs := distsqlrun.ReadCSVSpec{
> 			SampleSize: int32(sampleSize),
> ```

I tried to track the use of this sampleSize and failed. Somewhere there needs to be more comments about what it does. Also a unit would probably help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609)*

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 892 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAR4HIRAMBZfimnmI:-KuSaxXLVBaeeq6jhs5G:b-pk1vwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L892)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on with this TODO?
</blockquote></details>

Remove. Was old.

---

*[pkg/sql/distsql_physical_planner.go, line 916 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAxoxH4G6cV9SgVN0:-KuSciCYICbtGQxX0jqf:b-nkvvqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L916)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's this? I think it deserves a comment.
</blockquote></details>

I added a big comment describing the algorithm and how the various variables work together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609)*

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 916 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609#-KuRAxoxH4G6cV9SgVN0:-KuUrVqZCAx_Xu3JFgW0:b-k73z76) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e9552bae1e94b1aa1dfdaff9b305fa216103bf/pkg/sql/distsql_physical_planner.go#L916)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I added a big comment describing the algorithm and how the various variables work together.
</blockquote></details>

thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18609)*

**Pull request merged**
