### PR TITLE
testing: rewrite TestInitialPartitioning as SQLTranslator tests

### LINKED ISSUE #49909: ccl/partitionccl: TestInitialPartitioning failed
[(ccl/partitionccl).TestInitialPartitioning failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1991102&tab=buildLog) on [master@b0c3eca4dfdb21186251fa23af60d5d185afda98](https://github.com/cockroachdb/cockroach/commits/b0c3eca4dfdb21186251fa23af60d5d185afda98):

```
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:425 +0x30a
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:255 +0x15f
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:223 +0x65
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:349 +0x196
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:223 +0xc90
  github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.setupPartitioningTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:1159 +0xd48
  github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.TestInitialPartitioning()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:1189 +0x1b5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 369 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0xc3
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:165 +0x149
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaft()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:573 +0xcb
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store.go:1506 +0xc8c
  github.com/cockroachdb/cockroach/pkg/server.(*Node).bootstrapStores()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:564 +0x5f7
  github.com/cockroachdb/cockroach/pkg/server.(*Node).start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:452 +0x1713
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1365 +0x2fda
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/testserver.go:425 +0x30a
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:255 +0x15f
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:223 +0x65
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).doAddServer()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:349 +0x196
  github.com/cockroachdb/cockroach/pkg/testutils/testcluster.StartTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:223 +0xc90
  github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.setupPartitioningTestCluster()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:1159 +0xd48
  github.com/cockroachdb/cockroach/pkg/ccl/partitionccl.TestInitialPartitioning()
      /go/src/github.com/cockroachdb/cockroach/pkg/ccl/partitionccl/partition_test.go:1189 +0x1b5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/partitionccl	793.951s

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestInitialPartitioning PKG=./pkg/ccl/partitionccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestInitialPartitioning.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

Jira issue: CRDB-4173

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #49909

This rewrites TestInitialPartitioning subtests as SQLTranslator tests
so that they can be unskipped.

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6JF4KA7x_q03jzYrD:b2rhdta) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
> ```
> exec-sql
> CREATE DATABASE db;
> ```

i was trying to understand what the old test was checking. it used to say:
```
		{
			name: `inheritance - multi col default`,
			schema: `CREATE TABLE %s (a INT, b INT, PRIMARY KEY (a, b)) PARTITION BY LIST (a, b) (
				PARTITION p34 VALUES IN ((3, 4)),
				PARTITION p3d VALUES IN ((3, DEFAULT)),
				PARTITION p56 VALUES IN ((5, 6)),
				PARTITION p5d VALUES IN ((5, DEFAULT))
			)`,
			configs: []string{`@primary`, `.p3d`, `.p56`},
			generatedSpans: []string{
				`@primary /1-/1/3`,
				`    .p3d /1/3-/1/4`,
				`@primary /1/4-/1/5/6`,
				`    .p56 /1/5/6-/1/5/7`,
				`@primary /1/5/7-/2`,
			},
		},
```

It looks like there were more generated spans in the old test case? is the change in results expected?

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @primary, and @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6TLzO-EuTZ6rXXHSh:bu424a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i was trying to understand what the old test was checking. it used to say:
```
		{
			name: `inheritance - multi col default`,
			schema: `CREATE TABLE %s (a INT, b INT, PRIMARY KEY (a, b)) PARTITION BY LIST (a, b) (
				PARTITION p34 VALUES IN ((3, 4)),
				PARTITION p3d VALUES IN ((3, DEFAULT)),
				PARTITION p56 VALUES IN ((5, 6)),
				PARTITION p5d VALUES IN ((5, DEFAULT))
			)`,
			configs: []string{`@primary`, `.p3d`, `.p56`},
			generatedSpans: []string{
				`@primary /1-/1/3`,
				`    .p3d /1/3-/1/4`,
				`@primary /1/4-/1/5/6`,
				`    .p56 /1/5/6-/1/5/7`,
				`@primary /1/5/7-/2`,
			},
		},
```

It looks like there were more generated spans in the old test case? is the change in results expected?
</blockquote></details>

This test does not have any constraints (the `ALTER INDEX`/`ALTER PARTITION` statements in the other tests) which I think means all of the span configs can resolve to a single range. @arulajmani can you confirm my understanding?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @primary, and @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6_rG8CU6XU2G84C0I:b4jams4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

This test does not have any constraints (the `ALTER INDEX`/`ALTER PARTITION` statements in the other tests) which I think means all of the span configs can resolve to a single range. @arulajmani can you confirm my understanding?
</blockquote></details>

I think the reason we aren't seeing the same spans here is because we aren't applying zone configurations. Partitioning by itself doesn't do anything -- partitioning and applying zone configurations on the partitions does. I think that's what the `configs` portion of the test case is about.

Rafi is right, once w've fully translated the test case, we should expect the generated spans to match.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @primary, and @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6UM4g1sKQGMPOX6CM:b-qogl5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think the reason we aren't seeing the same spans here is because we aren't applying zone configurations. Partitioning by itself doesn't do anything -- partitioning and applying zone configurations on the partitions does. I think that's what the `configs` portion of the test case is about.

Rafi is right, once w've fully translated the test case, we should expect the generated spans to match.
</blockquote></details>

Does "applying zone configurations" mean using `ALTER INDEX ... CONFIGURE ZONE USING`/`ALTER PARTITION ... CONFIGURE ZONE USING`?

AFAICT those are only run if constraints are added here (via a config with a `:`) https://github.com/cockroachdb/cockroach/blob/8b7fb0c389eee9a89f7aff6c6865b6becff6127e/pkg/ccl/partitionccl/partition_test.go#L212
but test cases like this one do not specify constraints in `configs`.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @primary and @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6qtCh8GuKQibGO_HH:b-vuuwvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Does "applying zone configurations" mean using `ALTER INDEX ... CONFIGURE ZONE USING`/`ALTER PARTITION ... CONFIGURE ZONE USING`?

AFAICT those are only run if constraints are added here (via a config with a `:`) https://github.com/cockroachdb/cockroach/blob/8b7fb0c389eee9a89f7aff6c6865b6becff6127e/pkg/ccl/partitionccl/partition_test.go#L212
but test cases like this one do not specify constraints in `configs`.
</blockquote></details>

You're right, I missed that. It seems like this test is doing something a bit more wonky than I initially thought. See around:

https://github.com/cockroachdb/cockroach/blob/6a51bf43a7feabfbe85c4286bee3dd4f11de307e/pkg/ccl/partitionccl/partition_test.go#L189-L203

We're manually constructing this `subzones` list from the test input instead of going through zone configurations. Then, we're calling `sql.GenerateSubzoneSpans` and comparing the output of that function with this `subzones` list.

The SQL Translator tests are at a level higher, so we can't manually construct this `subzones` list (which maps to the `subzones` list on the `ZoneConfig` proto).

----

All of this is to say that my original suggestion should still help here. Setting zone configurations on these indexes/partitions should result in getting the correct output, with spans mapping to `generatedSpans`.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @primary and @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-Nd6JF4KA7x_q03jzYrC:-Nd6tK2t5VltU7zvAuGH:bp7dbbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3fdd4ed50fa5080c1a2832dc58d0a3e2f398cff/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/initialpartition/inheritance_multi_col_default#L2)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You're right, I missed that. It seems like this test is doing something a bit more wonky than I initially thought. See around:

https://github.com/cockroachdb/cockroach/blob/6a51bf43a7feabfbe85c4286bee3dd4f11de307e/pkg/ccl/partitionccl/partition_test.go#L189-L203

We're manually constructing this `subzones` list from the test input instead of going through zone configurations. Then, we're calling `sql.GenerateSubzoneSpans` and comparing the output of that function with this `subzones` list.

The SQL Translator tests are at a level higher, so we can't manually construct this `subzones` list (which maps to the `subzones` list on the `ZoneConfig` proto).

----

All of this is to say that my original suggestion should still help here. Setting zone configurations on these indexes/partitions should result in getting the correct output, with spans mapping to `generatedSpans`.
</blockquote></details>

It looks like these "inheritance" test cases were being skipped here
https://github.com/cockroachdb/cockroach/blob/6a51bf43a7feabfbe85c4286bee3dd4f11de307e/pkg/ccl/partitionccl/partition_test.go#L1222
because they did not specify `scans` and they are similar to other test cases that do specify `scans` so I removed them.

**Review by rafiss — APPROVED** [review]
nice! glad all the testing went smoothly 

> Reviewed 1 of 1 files at r1, 5 of 30 files at r4, 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109693#-:-NdDuR037FsPv1g4ikw0:b-xx46mq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @primary)

**Pull request merged**
