### PR TITLE
kvserver: avoid concurrent range changes with allocator token

### LINKED ISSUE #119406: kvserver: reduce concurrent replication changes/lease tranfers on the same range
**Is your feature request related to a problem? Please describe.**

Currently, the store rebalancer may interfere with the replicate queue and vice versa. The interference can result in longer joint configuration times or failed change replica commands, as both systems propose changes to the range / leaseholder without synchronization.

**Describe the solution you'd like**

Introduce a synchronization mechanism on the leaseholder of the range which limits concurrent allocator activity for a range to 1. 

**Describe alternatives you've considered**

Consolidating the planning, scheduling and execution of changes would be a better alternative to pursue in the future.

**Additional context**

Introducing additional concurrency is planned as part of https://github.com/cockroachdb/cockroach/issues/118866, making this issue more relevant.

Jira issue: CRDB-36191

### PR DESCRIPTION
**Pull request by kvoli**
Previously, the leaseholder store on a node could attempt to apply lease transfers and replica changes to the same range concurrently. This occurred when the replicate queue processed the same range as the store rebalancer concurrently.

Introduce an allocator token, which is acquired per-range on the leaseholder when planning and executing replica/lease changes via the store rebalancer or replicate queue for a range. The allocator token is released upon success/failure of an action. When encountering an already acquired token, the respective actor may register a callback which is called upon release in order. The callback is used to maybe add the replica back into the replicate queue and is not used by the store rebalancer.

Resolves: #119406
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
An alternative to the callback approach described here is to mark the `AllocatorTokenError` as a purgatory error. The purgatory error would then be retried by a queue when encountered. I slightly favor this approach with a callback, because purgatory is typically used for non-processable replicas with allocation issues (not enough nodes etc), whereas the replica is processable, just not immediately.

We could mark the error as a purgatory error and also signal the purgatoryChannel when the token is released. This would increased the amount of work (every purgatory replica is retried) but add some observability with purgatory.

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
The structure here is a little confusing. Basically it is a mix of a "tryAcquire" and an "asyncAcquire". However if there are multiple threads trying to acquire, then they will all be sitting in loops that look like

```
fn acquireAndDoSomething() {
    if (token.Acquire(.. , acquire.DoSomething, ...) { 
        doSomething() 
    }
}
```

Every time one of them gets an acquisition, one goes through and the others all get added to the `onFail` list. So if there are a lot of contending threads, it will be in a race each time, and only one will get through. For the current usage, this is probably OK, but there are a few alternatives.

1) Use the purgatory error as you described
2) Skip replicas that can't be immediately acquired on with the idea that it will come back again soon enough (basically remove the retry optimization)
3) Create seperate Acquire and TryAcquire methods. If TryAcquire fails, then create a new goroutine that will call Acquire and block until it is available.

I slightly prefer the 3rd option, but it does also change the queuing model since now its possible that two process calls are happening concurrently (once the Acquire succeeds). It better deals with the case where we have been asked to skip queueing and process this request, but maybe at a cost of additional complexity to the queues that they don't have now. 

I'm also OK leaving things as you have them. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-:-Ns8qAEL8m7w9dq38NcV:b-7hrlv3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8w8su-K69rSTIUkZr:-Ns8w8su-K69rSTIUkZs:bkv5pbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/replicate_queue.go#L651)):*
> ```Go
> 	ctx context.Context, repl *Replica, confReader spanconfig.StoreReader,
> ) (processed bool, err error) {
> 	if tokenErr := repl.allocatorToken.Acquire(ctx, rq.name, func(ctx context.Context) {
> ```

This isn't necessarily ideal for something that calls `skipQueue`. as the `maybeAdd` goes through the queue checks again. Consider calling `addInternal` instead. 
___
*[`pkg/kv/kvserver/replicate_queue.go` line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8vfPGE2DMLkHE01uW:-Ns8vfPGE2DMLkHE01uX:bzg1nu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/replicate_queue.go#L653)):*
> ```Go
> 	if tokenErr := repl.allocatorToken.Acquire(ctx, rq.name, func(ctx context.Context) {
> 		rq.maybeAdd(ctx, repl, rq.store.Clock().NowAsClockTimestamp())
> 	}); tokenErr != nil {
> ```

nit: Add a log message here. This would allow more context about what happened in the case where we skip processing a replica. 
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8pf2Y9La8Z9Kc4jJ8:-Ns8pf2Y9La8Z9Kc4jJ9:b-enq9rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L39)):*
> ```Go
> }
> 
> // Acquire tries to acquire the token, returning true if successful and false
> ```

nit: It looks like you changed from true/false to nil/Err, I slightly prefer the true/false return, but either way update the comment to match the code.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8pWp6Bl57J2gcf7qY:-Ns8pWp76r4ezKsCEhC6:b-mih1se) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L42)):*
> ```Go
> // otherwise. When acquisition fails, the onFail callback will be registered
> // and called upon release.
> func (at *AllocatorToken) Acquire(
> ```

nit: Rename to TryAcquire to make it more clear what this method does in the case of it already being held.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8xN9x29Rbt9VGttQZ:-Ns8xN9x29Rbt9VGttQ_:b-o8w8rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L53)):*
> ```Go
> 		at.mu.acquired = true
> 		at.mu.acquiredName = name
> 		log.KvDistribution.VEventf(ctx, 1, "acquired allocator token")
> ```

nit: consider making this level 2 or 3. Thi sis going to be very common and not very useful for most debugging. 
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8xT1o5PzQsDxZhVBv:-Ns8xT1o5PzQsDxZhVBw:bnijslf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L96)):*
> ```Go
> 	}
> 	at.mu.acquired = false
> 	log.KvDistribution.VEventf(ctx, 1, "released allocator token")
> ```

nit: similar to above, reduce the verbosity of this message.
___
*[`pkg/kv/kvserver/allocator/plan/token_test.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8u8Gv-2eqPoz2SIpb:-Ns8u8Gv-2eqPoz2SIpc:bj3pfqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token_test.go#L21)):*
> ```Go
> 	"github.com/stretchr/testify/require"
> )
> ```

Consider adding a stress test - with ~100 threads all contending for one token and each having an onRelease callback. The code would look similar to what I had put above. Specifically each of them "re-register" on failure which means that we end up with n^2 contention/retries. This might be OK, but it isn't necessarily the best approach here.

**Review by kvoli — COMMENTED** [review]
TYFTR

I decided to go with option 1 and use purgatory. This greatly simplified the token logic and its probably a safer option -- even if it does skew purgatory meaning slightly.

I wanted to avoid option 2 because this would break the purgatory lease transfer retry when a lease violates preferences.

3 sounded interesting, I played around with it a bit but introducing a new queueing system on-top seemed like it would hcange the queueing model too significantly as you suggested. There's already a lot of subtly around the replica queue internals and I want to avoid heaping further complexity on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-:-Ns9N6_51lOlE4GTU5zU:b-dvgckq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @kvoli)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8w8su-K69rSTIUkZr:-Ns9ECeF-F8GiaKOX9mQ:bf5pfky) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/replicate_queue.go#L651)):*
> This isn't necessarily ideal for something that calls `skipQueue`. as the `maybeAdd` goes through the queue checks again. Consider calling `addInternal` instead.

This is intentional, its possible and likely that the current token holder has transferred the lease away, or moved a replica.
___
*[`pkg/kv/kvserver/replicate_queue.go` line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8vfPGE2DMLkHE01uW:-Ns9HBE01QdsA-C3HW05:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/replicate_queue.go#L653)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Add a log message here. This would allow more context about what happened in the case where we skip processing a replica.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8pf2Y9La8Z9Kc4jJ8:-Ns9DJse184m9SZKZ43E:b4tvxp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L39)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: It looks like you changed from true/false to nil/Err, I slightly prefer the true/false return, but either way update the comment to match the code.
</blockquote></details>

Updated to reflect the code.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8pWp6Bl57J2gcf7qY:-Ns9F-ea9P-JWj5uun64:b-8mwq1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L42)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Rename to TryAcquire to make it more clear what this method does in the case of it already being held.
</blockquote></details>

Good idea, updated to `TryAcquire`.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8xN9x29Rbt9VGttQZ:-Ns9Epbd6r68FET5n5Z7:bt6be0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L53)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: consider making this level 2 or 3. Thi sis going to be very common and not very useful for most debugging.
</blockquote></details>

Update to v=3.
___
*[`pkg/kv/kvserver/allocator/plan/token.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8xT1o5PzQsDxZhVBv:-Ns9Ey4e7G9QbjegSy12:b-ucjqf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token.go#L96)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: similar to above, reduce the verbosity of this message.
</blockquote></details>

Updated to v=3.
___
*[`pkg/kv/kvserver/allocator/plan/token_test.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8u8Gv-2eqPoz2SIpb:-Ns9qDUnEmBQ5lsC_EtB:b-s4icvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/allocator/plan/token_test.go#L21)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Consider adding a stress test - with ~100 threads all contending for one token and each having an onRelease callback. The code would look similar to what I had put above. Specifically each of them "re-register" on failure which means that we end up with n^2 contention/retries. This might be OK, but it isn't necessarily the best approach here.
</blockquote></details>

Updated to use purgatory instead, this makes increasing the concurrency of the test less relevant.

**Review by andrewbaptist — APPROVED** [review]
LGTM!

Thanks for the changes. It is much reason about now.

> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-:-NsU-XFA9sJPZByd4dQH:beifcvp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119410#-Ns8w8su-K69rSTIUkZr:-NsU-l3K8OVAbVRebmEy:btz2ruq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aac8d76d156159aff52b8e96e4346fd7ef7f57c/pkg/kv/kvserver/replicate_queue.go#L651)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> This isn't necessarily ideal for something that calls `skipQueue`. as the `maybeAdd` goes through the queue checks again. Consider calling `addInternal` instead.

This is intentional, its possible and likely that the current token holder has transferred the lease away, or moved a replica.
</blockquote></details>

That makes sense and should be OK. I still have a small concern with requests that don't want to pass through the `shouldQueue` checks, but I think they can manually retry if they hit this lock, so that should be OK.

**Comment by kvoli** [comment]
TYFTR!

bors r=andrewbaptist

**Pull request merged**
