### PR TITLE
kvserver: fix flake in TestReplicaGCQueueDropReplicaDirect

### LINKED ISSUE #51263: kv/kvserver: TestReplicaGCQueueDropReplicaDirect failed
[(kv/kvserver).TestReplicaGCQueueDropReplicaDirect failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2079492&tab=buildLog) on [master@542c83e7db1694208e09c7fea7d350db4993b897](https://github.com/cockroachdb/cockroach/commits/542c83e7db1694208e09c7fea7d350db4993b897):

```
=== RUN   TestReplicaGCQueueDropReplicaDirect
    TestReplicaGCQueueDropReplicaDirect: test_log_scope.go:77: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestReplicaGCQueueDropReplicaDirect808729660
    TestReplicaGCQueueDropReplicaDirect: test_log_scope.go:58: use -show-logs to present logs inline
    TestReplicaGCQueueDropReplicaDirect: client_replica_gc_test.go:96: r35 was not found on s2
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestReplicaGCQueueDropReplicaDirect808729660
--- FAIL: TestReplicaGCQueueDropReplicaDirect (1.92s)

```

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=TestReplicaGCQueueDropReplicaDirect PKG=./pkg/kv/kvserver TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestReplicaGCQueueDropReplicaDirect.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by lunevalex**
Fixes #51263

A previous change that switched this test from multiTestContect to using TestCluster introduced a regression. The test did not properly wait/replicate the scratch range, so it sometimes failed. This change adds deterministic replication for the scrath range, which fixes this issue.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
LGTM. Thanks for tracking this down!

**Comment by lunevalex** [comment]
bors retry

**Pull request merged**
