### PR TITLE
sql: various COPY and pgtest improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
Since the feature cutoff date has hit, the CSV features in #52236 can no longer go in. This PR is that plus #53239 and supersedes both. It is here so that it can be easily backported to the release branch. The COPY CSV support will be added in a future PR later.

**Review by arulajmani — APPROVED** [review]
Changes look good to me as I've reviewed these in different PRs before. I think you'll need to update the third commit message though, which talks about adding COPY CSV support.  

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53359#-:-MFaL5SsBZKm-Ai9hGbe:b3yvncc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @arulajmani)

**Comment by mjibson** [comment]
Good catch. Fixed up the commit message to discuss testing improvements.

**Review by adityamaru — APPROVED** [review]

**Pull request merged**
