### PR TITLE
storage: respect closed timestamp in tryReproposeWithNewLeaseIndex

### LINKED ISSUE #42821: storage: tryReproposeWithNewLeaseIndex may violate closed timestamp
Consider proposing a write and this code path:

https://github.com/cockroachdb/cockroach/blob/4850974add18d34658d538579383cd673a9d6b5a/pkg/storage/replica_write.go#L149-L165

Let's say the `maxLeaseIndex` assigned here is 100 and the timestamp of the command is 1000. The closed timestamp tracker now knows 100 as the MLAI of a command that has an effect at ts=1000.

The proposal now hits this code path

https://github.com/cockroachdb/cockroach/blob/27c3d499b528c91a956b2d8b9d5176d0b632b5bf/pkg/storage/replica_application_result.go#L145-L151

and gets reproposed with a new lease index, let's say 200:

https://github.com/cockroachdb/cockroach/blob/27c3d499b528c91a956b2d8b9d5176d0b632b5bf/pkg/storage/replica_application_result.go#L210-L215

From the perspective of closed timestamps, this is problematic. A CT update might have been sent out stating that "if you've caught up to lease index 100, you've seen all the proposals that will have an effect on timestamp 1000". But it turns out that in this example, such a command will pop out of raft at lease index 200.

It seems that this can cause a violation of the invariant that any closed out MVCC snapshot is immutable.

As for fixing this, the "natural" attempt is to go through the tracker again. However, if we find that the tracker pushes the proposal (i.e. the original timestamp has closed out, as it has in this example), we need someone to reevaluate it.

It's possible that we would be better off removing this one-off below-raft-reproposal path completely and instead opting for having the client reevaluate the command unconditionally. The one-off path was originally introduced to accommodate pipelined writes (where the client returns early and isn't around to reevaluate the command) but this doesn't mean we can't reevaluate the batch, just that we have to create a goroutine to do so. This approach is less performant, but this is a rare case where simplicity is more important than performance.

### PR DESCRIPTION
**Pull request by tbg**
Prior to this commit, tryReproposeWithNewLeaseIndex would not consult
with the closed timestamp tracker. This meant that a proposal may end up
with a new lease index at a timestamp that consumers of closed timestamp
updates had already considered immutable. In other words, this broke
closed timestamp guarantees and would by extension also have the
potential to break CDC's.

This path is fairly rare and it isn't one likely to cause problems
in practice, though it certainly could have.

See https://github.com/cockroachdb/cockroach/issues/42821 for details.

Fixes #42821

Release note (bug fix): fix a bug which could lead to follower reads or
CDC updates that did not reflect the full set of data at the timestamp.
This bug was never observed in practice and should be rare to cause
issues, one of the necessary ingredients being an aggressive closed
timestamp interval.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
The basic idea makes sense. Good find and nice fix. 

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-LvGTWosBGr_gmqVsP-U:b94co1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/roachpb/batch.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGRtFuCGSrt0Xl4YnS:-LvGRtFuCGSrt0Xl4YnT:bqrgw4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/roachpb/batch.go#L62)):*
> ```Go
> 	if txn := ba.Txn; txn != nil {
> 		ts := txn.ReadTimestamp
> 		ts.Forward(txn.DeprecatedOrigTimestamp)
> ```

Can this be removed in 20.2? 
___
*[pkg/storage/replica_application_result.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSpsI1CkFv3SE92Dv:-LvGSpsI1CkFv3SE92Dw:b-gjqi4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed717cbaf741e3a32c76db25b16a59dc2a8221d7/pkg/storage/replica_application_result.go#L214)):*
> ```Go
> 	maxLeaseIndex, pErr := r.propose(ctx, p)
> 	if pErr != nil {
> 		log.Warningf(ctx, "failed to repropose with new lease index: %s", pErr)
> ```

Can you help me understand why you didn't want to log here and you did want to log above?
___
*[pkg/storage/replica_application_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSUAY1aokGndU_RiP:-LvGSUAY1aokGndU_RiQ:b4jqhjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L220)):*
> ```Go
> 		// will go to the client, so send something it can digest.
> 		//
> 		// WIP(tbg): is this the right error?
> ```

This is a bummer. We want an error which will be retried in distsender. Not leaseholder error will do the trick but seems wrong. I think I’d be in favor of adding a new error over this.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/batch.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGRtFuCGSrt0Xl4YnS:-LvGTkFlA9gpXMWqtKLO:b-kecgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/roachpb/batch.go#L62)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can this be removed in 20.2? 
</blockquote></details>

I think so, but let's remove this thing in its own PR.
___
*[pkg/storage/replica_application_result.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSpsI1CkFv3SE92Dv:-LvGW7vIBxmoCsfMVSCX:bie6ub3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed717cbaf741e3a32c76db25b16a59dc2a8221d7/pkg/storage/replica_application_result.go#L214)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you help me understand why you didn't want to log here and you did want to log above?
</blockquote></details>

I removed this and added logging at the caller, to avoid introducing extra `log.Warningf` for the new error return in this method.
___
*[pkg/storage/replica_application_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSUAY1aokGndU_RiP:-LvGTmrI6AnHnIR1fjAq:bmhxv7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L220)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is a bummer. We want an error which will be retried in distsender. Not leaseholder error will do the trick but seems wrong. I think I’d be in favor of adding a new error over this. 
</blockquote></details>

Hmm - this needs a backport, so I don't think we should be adding a new error. The leaseholder error has a "custom message" field, I can use it to disambiguate this error should it pop up somewhere. Agreed that there's not much to love about returning this error. More generally though, there's lots that's not to love about this whole method in general. I chatted with @nvanbenschoten yesterday and we both thought that there's something we should do around handling ErrProposalDropped (https://github.com/cockroachdb/cockroach/issues/21849) and avoiding raft forwarding entirely (https://github.com/cockroachdb/cockroach/issues/37906). The idea being that illegal lease applied index && proposal hasn't applied yet just can't happen if you don't forward proposals. This needs some fleshing out, but I'd very much like to remove all of this reordering, and thus this subtle code, altogether. (The bug count for this code is >5).

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSUAY1aokGndU_RiP:-LvGb09U0ksD0asMUZpO:b-xa5hsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L220)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm - this needs a backport, so I don't think we should be adding a new error. The leaseholder error has a "custom message" field, I can use it to disambiguate this error should it pop up somewhere. Agreed that there's not much to love about returning this error. More generally though, there's lots that's not to love about this whole method in general. I chatted with @nvanbenschoten yesterday and we both thought that there's something we should do around handling ErrProposalDropped (https://github.com/cockroachdb/cockroach/issues/21849) and avoiding raft forwarding entirely (https://github.com/cockroachdb/cockroach/issues/37906). The idea being that illegal lease applied index && proposal hasn't applied yet just can't happen if you don't forward proposals. This needs some fleshing out, but I'd very much like to remove all of this reordering, and thus this subtle code, altogether. (The bug count for this code is >5).
</blockquote></details>

Wrote up the comment: https://github.com/cockroachdb/cockroach/issues/21849#issuecomment-561705730

**Review by ajwerner — COMMENTED** [review]
How do we write tests to detect closed timestamp violations such as this one? Something that might show up had we set the closed timestamp interval to something short and then added some chaos to the raft transport perhaps?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-LvHsEcD20Phb93g2lC2:b3ou2ek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/batch.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGRtFuCGSrt0Xl4YnS:-LvHByO01fFDtMUnRlR0:b-mcn3nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/roachpb/batch.go#L62)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think so, but let's remove this thing in its own PR.
</blockquote></details>

You need this while in 20.1.I think I was mostly just asking for a `TODO` to get rid of this forwarding in 20.2 but I suppose that will just fall out of the removal of that field.  
___
*[pkg/storage/replica_application_result.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSpsI1CkFv3SE92Dv:-LvHCq2m2KvduCvyORXt:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed717cbaf741e3a32c76db25b16a59dc2a8221d7/pkg/storage/replica_application_result.go#L214)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I removed this and added logging at the caller, to avoid introducing extra `log.Warningf` for the new error return in this method.
</blockquote></details>

Ack.
___
*[pkg/storage/replica_application_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvGSUAY1aokGndU_RiP:-LvHD9ZBDHQ1MOOfdOFl:b-2i108r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L220)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Wrote up the comment: https://github.com/cockroachdb/cockroach/issues/21849#issuecomment-561705730
</blockquote></details>

Thanks. Makes sense.

**Review by tbg — COMMENTED** [review]
> How do we write tests to detect closed timestamp violations such as this one? Something that might show up had we set the closed timestamp interval to something short and then added some chaos to the raft transport perhaps?

I think there are two ingredients we need:

1) an invariant that detects CT violations (i.e. something like: query the tracker in .propose to validate that the MLAI is tracked; and/or with each applied Raft command, verify that the MVCC snapshot being changed isn't immutable yet)
2) run through situations in which a violation is more likely.

Honestly to establish confidence that we have fixed this *particular* bug I would rather spend energy on simplifying our architecture so that we just handle things in a simpler way that doesn't even have this problem (i.e. there's only one path into Raft, and it "obviously" goes through the tracker). But even after that having some way to establish confidence that our closed timestamps are in fact properly closed does seem desirable. An always-on assertion to that end could be good, coupled with tests in which we run with an aggressive closed timestamp duration as you suggested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-Lvd-JXjBCodxPLi8nbd:bun4x9l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by ajwerner** [comment]
> Honestly to establish confidence that we have fixed this particular bug I would rather spend energy on simplifying our architecture so that we just handle things in a simpler way that doesn't even have this problem (i.e. there's only one path into Raft, and it "obviously" goes through the tracker).

Fair. Thanks for the thoughts on the testing strategy. I'll keep those in mind as I look towards moving some of the closed timestamp subsystem into the raft transport and work to make closed timestamps something more of a per-range concept than today's store level concept.

**Review by nvb — COMMENTED** [review]
Here's a test that indicates that this works: https://github.com/cockroachdb/cockroach/pull/43121. In general, the assertions in rangefeed are actually pretty good at catching these issues.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-LvrWl-q0O2A9r86YgxS:bws0l8j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/batch.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrVX4f1QK1Oiskqn-8:-LvrVX4f1QK1Oiskqn-9:b8z976d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/roachpb/batch.go#L59)):*
> ```Go
> 
> // GetActiveTimestamp returns the timestamp at which the request will read.
> func (ba *BatchRequest) GetActiveTimestamp() hlc.Timestamp {
> ```

Isn't `ba.Timestamp` set to this timestamp in `SetActiveTimestamp`? Why do we need this accessor?
___
*[pkg/storage/replica_application_result.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrVgXvAOGxU3GJWxmc:-LvrVgXvAOGxU3GJWxmd:b-i7krh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L223)):*
> ```Go
> 		lhErr := roachpb.NewError(newNotLeaseHolderError(
> 			r.mu.state.Lease,
> 			cmd.proposal.command.ProposerReplica.StoreID,
> ```

I think I just removed this. If we're here then don't we know that this was proposed locally?
___
*[pkg/storage/replica_application_result.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrWNqdCs1UFdnpQZGR:-LvrWNqdCs1UFdnpQZGS:b-ldmrcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L238)):*
> ```Go
> 	// NB: The caller already promises that the lease check succeeded, meaning
> 	// the sequence numbers match, implying that the lease epoch hasn't changed
> 	// from what it was under the proposal-time lease.
> ```

This all checks out, but I still think it would look less troubling if we pulled the lease epoch off of `cmd`. Is that possible?

**Review by tbg — COMMENTED** [review]
Neat, thanks for writing that test!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-LvuWca1E5mY-RZnIJzA:b-vy8vyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application_result.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrVgXvAOGxU3GJWxmc:-LvuPflIBuRa0XlWnuQ2:b-bj4s0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L223)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think I just removed this. If we're here then don't we know that this was proposed locally?
</blockquote></details>

Yes, we do. Updated.
___
*[pkg/storage/replica_application_result.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrWNqdCs1UFdnpQZGR:-LvuOuQT5Aq_vXq1NyAo:b-tttjmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L238)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This all checks out, but I still think it would look less troubling if we pulled the lease epoch off of `cmd`. Is that possible?
</blockquote></details>

It's not available there, or are you saying I should stash it on `ProposalData`? I agree that it'd be nice not to have to do mental yoga over the epoch.

**Review by nvb — APPROVED** [review]
> thanks for writing that test!

It wasn't meant to test this. So I should be thanking you for deflaking my test.

:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-:-LvuyPcg5QCuCtaQ3a01:b-n83f30)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_application_result.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42939#-LvrWNqdCs1UFdnpQZGR:-LvvAOkFBAyeRPM4ewA7:b-e3jnsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8ee83ace00448a5e873ded698684e01017f9ef7/pkg/storage/replica_application_result.go#L238)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's not available there, or are you saying I should stash it on `ProposalData`? I agree that it'd be nice not to have to do mental yoga over the epoch.
</blockquote></details>

Oh you need the epoch, not the sequence, never mind.

**Comment by tbg** [comment]
TFTR!

bors r=nvanbenschoten

**Comment by tbg** [comment]
bors r=nvanbenschoten

flake was #38428

**Pull request merged**
