### PR TITLE
roachtest: update django test skips

### LINKED ISSUE #87250: roachtest: django failed
roachtest.django [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=6315055&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=6315055&tab=artifacts#/django) on release-22.1 @ [5e2f4ff465491982e869cfb113fe9d73a087b081](https://github.com/cockroachdb/cockroach/commits/5e2f4ff465491982e869cfb113fe9d73a087b081):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/django/run_1
	orm_helpers.go:193,orm_helpers.go:119,django.go:235,django.go:246,test_runner.go:883: 
		Tests run on Cockroach v22.1.6-112-g5e2f4ff465
		Tests run against django cockroach-4.1.x
		9939 Total Tests Run
		9938 tests passed
		1 test failed
		642 tests skipped
		3 tests ignored
		0 tests passed unexpectedly
		1 test failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: select_for_update.tests.SelectForUpdateTests.test_raw_lock_not_available (unexpected)
		--- SKIP: backends.mysql.test_creation.DatabaseCreationTests.test_create_test_db_unexpected_error due to MySQL tests (expected)
		For a full summary look at the django artifacts 
		
		An updated blocklist (djangoBlocklist22_1) is available in the artifacts' django log
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*django.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19235

### LINKED ISSUE #87368: roachtest: django failed
roachtest.django [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6347309?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6347309?buildTab=artifacts#/django) on master @ [e5917605f751c569ddd90062250a40cafd7ccf30](https://github.com/cockroachdb/cockroach/commits/e5917605f751c569ddd90062250a40cafd7ccf30):

```
test artifacts and logs in: /artifacts/django/run_1
	orm_helpers.go:191,orm_helpers.go:117,django.go:223,django.go:234,test_runner.go:897: 
		Tests run on Cockroach v22.2.0-alpha.1-309-ge5917605f7
		Tests run against django cockroach-4.1.x
		9931 Total Tests Run
		9929 tests passed
		2 tests failed
		642 tests skipped
		3 tests ignored
		0 tests passed unexpectedly
		2 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: migrations.test_operations.OperationTests.test_rename_model_with_db_table_noop (unexpected)
		--- SKIP: backends.mysql.test_creation.DatabaseCreationTests.test_create_test_db_unexpected_error due to MySQL tests (expected)
		--- FAIL: unittest.loader._FailedTest.admin_docs.test_utils (unexpected)
		For a full summary look at the django artifacts 
		
		An updated blocklist (djangoBlocklist22_2) is available in the artifacts' django log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #87250 roachtest: django failed [C-test-failure O-roachtest O-robot branch-release-22.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*django.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19302

### LINKED ISSUE #87576: roachtest: django failed
roachtest.django [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6383281?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6383281?buildTab=artifacts#/django) on release-22.2 @ [f8e04f32b84a9727c9e813d0096bde2de64d5675](https://github.com/cockroachdb/cockroach/commits/f8e04f32b84a9727c9e813d0096bde2de64d5675):

```
test artifacts and logs in: /artifacts/django/run_1
	orm_helpers.go:191,orm_helpers.go:117,django.go:223,django.go:234,test_runner.go:908: 
		Tests run on Cockroach v22.2.0-alpha.2-283-gf8e04f32b8
		Tests run against django cockroach-4.1.x
		9941 Total Tests Run
		9939 tests passed
		2 tests failed
		642 tests skipped
		3 tests ignored
		0 tests passed unexpectedly
		2 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: schema.tests.SchemaTests.test_autofield_to_o2o (unexpected)
		--- FAIL: schema.tests.SchemaTests.test_add_auto_field (unexpected)
		--- SKIP: backends.mysql.test_creation.DatabaseCreationTests.test_create_test_db_unexpected_error due to MySQL tests (expected)
		For a full summary look at the django artifacts 
		
		An updated blocklist (djangoBlocklist22_2) is available in the artifacts' django log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #87368 roachtest: django failed [C-test-failure O-roachtest O-robot branch-master]
- #87250 roachtest: django failed [C-test-failure O-roachtest O-robot branch-release-22.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*django.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-19420

### PR DESCRIPTION
**Pull request by timgraham**
Fixes #87368, fixes #87576, fixes #87250

Release note: None

### CODE REVIEW

**Comment by timgraham** [comment]
I didn't test this (hopefully I haven't made any typos). The test skips correspond to https://github.com/cockroachdb/django-cockroachdb/pull/266.

**Comment by rafiss** [comment]
if the skips are noted there, then i don't think we need to change this test

**Comment by rafiss** [comment]
Ah i see, we'd need a new release of the adapter. Let's merge this - I've just amended it slightly to do a little bit of extra cleanup

**Review by rafiss — APPROVED** [review]

**Pull request merged**
