### PR TITLE
admission: allow range snapshot ignored bytes to be normal writes

### PR DESCRIPTION
**Pull request by sumeerbhola**
This is needed for https://github.com/cockroachdb/cockroach/pull/110943 since we are sometime applying incoming snapshots as normal writes. As a reminder, we do not deduct tokens for data ingested/written to the LSM for range snapshots since this can starve out normal writes. We also compensate for these ignored bytes when fitting the linear model. The change in that compensation logic is what this PR addresses.

Informs #109808

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @bananabrick)

___
*[`pkg/util/admission/store_token_estimation.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111367#-NfMyYxMEYGYlYQt0vzB:-NfMyYxMEYGYlYQt0vzC:b-pw4esp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd44fbec3ce5953ff1d3515a8ca1df0c056a07d/pkg/util/admission/store_token_estimation.go#L187)):*
> ```Go
> 	}
> 	intL0WriteBytes := int64(l0Metrics.BytesFlushed) - int64(e.cumL0WriteBytes)
> 	intL0IgnoredWriteBytes := int64(admissionStats.statsToIgnore.writeBytes) -
> ```

the only real changes are the tiny changes in this file. The rest is just plumbing.

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111367#-:-NfSHIsE5EQXLbPW1teC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=aadityasondhi

**Pull request merged**
