### PR TITLE
rpc: return an error instead of calling log.Fatal and add a test

### PR DESCRIPTION
**Pull request by tamird**
This adds a unit test for the issue reported in #4884. However, it seems that the current implementation works correctly. Perhaps my test here could be more focused with respect to the clock offsets used? Suggestions welcome.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5107)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-:-KCY6-buAuCe4Q9W4p2s:676834233)*

**Comment by tamird** [comment]
OK, I think this is ready to merge. PTAL.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 4 of 4 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 3 of 3 files at r14, 6 of 6 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 2 of 2 files at r19, 4 of 4 files at r20, 3 of 3 files at r21.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[rpc/context_test.go, line 222 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq8mWKh9HiHl6_lvjh:-KCq8mWKh9HiHl6_lvji:369930555) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L222)):*
could this be `maxOffset+1`?

---

*[rpc/context_test.go, line 261 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq92RkE67iOQTfhuPf:-KCq92RkE67iOQTfhuPg:-25469380) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L261)):*
Add comment about why that's necessary.

---

*[rpc/context_test.go, line 281 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq9GG_QlxmFm8GswgE:-KCq9GG_QlxmFm8GswgF:1597820276) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L281)):*
could this become flaky? Would it hurt to have this on up to`15s` of waiting?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-:-KCqAOzYHf2McDcme6sv:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[rpc/context_test.go, line 222 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq8mWKh9HiHl6_lvjh:-KCqBIswpKEGNOCjUjWl:-319590911) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L222)):*
No, but it can be `maxOffset*2 + 1`. Changed and added a comment to explain.

---

*[rpc/context_test.go, line 261 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq92RkE67iOQTfhuPf:-KCqCgpx2cDEW7SZ6JHs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L261)):*
Done.

---

*[rpc/context_test.go, line 281 \[r14\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107#-KCq9GG_QlxmFm8GswgE:-KCqChR4OvNZaEOj07a1:-858623330) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28bec3beb68eb7c4f3bf7db793f546acc81c0b1/rpc/context_test.go#L281)):*
It shouldn't - this wait time should be strictly a function of the monitorInterval, and 5x seems sufficient. In the worst case, we could increase it when/if circle CI gets grumpy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5107)*

**Pull request merged**
