### PR TITLE
rac2: implement handle raft event

### LINKED ISSUE #129668: rac2: implement handle raft ready
Currently, RAC v2 does not support most functionality due to missing `HandleRaftReady` on the leaders `RangeController`. This issue is to implement said functionality necessary to support `WaitForEval`.

Jira issue: CRDB-41655

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
This commit implements `HandleRaftEvent` on the `RangeController`. When `HandleRaftEvent` is called by the `Processor` on the leader, the `RangeController` will perform local replica state management for the range and potentially return tokens if admitted has advanced. Additionally, any entries will subject to admission control will have corresponding tokens deducted and tracked.

Resolves: #129668
Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PKvBZ9vDemQo4HNpk:-O5PKvBZ9vDemQo4HNpl:b-efm411) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L317)):*
> ```Go
> // Requires replica.raftMu to be held.
> func (rc *rangeController) HandleRaftEventRaftMuLocked(ctx context.Context, e RaftEvent) error {
> 	for r, rs := range rc.replicaMap {
> ```

I think we should make `handleReadyState` return whether its `connectedState` changed in a way that affects the value of shouldWait... And accumulate those here. If any replica changed, we need to call `updateVoterSets`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PE1fF9cBKEIG0-g2c:-O5PE1fF9cBKEIG0-g2d:b1tuae) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L451)):*
> ```Go
> 
> 	connectedState connectedState
> 	closed         bool
> ```

The concept of  "closed" on a `replicaState` is odd. We have a `replicaState` for each replica, regardless of its `connectedState`. I think we should introduce the notion of `replicaSendStream` now, even if the state in there is minimal and move the `connectedState` and `tracker` into it.

We should also do the TODO (which we never did in the prototype) to transition from `probeRecentlyReplicate` to closing the `replicaSendStream` after x seconds. The reason we had `probeRecentlyReplicate` is we don't want to admit a flood of elastic work by excluding the slow replica from WaitForEval if it briefly transitioned to probe and back to replicate. Since `RangeController` relies on `Processor` for most of its locking, and because we don't want O(ranges) goroutines, we could just assume that RangeController is provided a timer scheduling interface in its options. Something like:
```
type ProbeToCloseTimerScheduler interface {
   ScheduleReplicaStreamClose()
}
```
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PIEpCB2p-W3aZALna:-O5PIEpCB2p-W3aZALnb:bt6est8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L517)):*
> ```Go
> 		rs.tracker.Track(ctx, state.term, state.index, state.pri, state.tokens)
> 		rs.evalTokenCounter.Deduct(
> 			ctx, WorkClassFromRaftPriority(state.pri), state.tokens)
> ```

should we also deduct from sendTokenCounter just to stay consistent with our model, since we will introduce the send-queue.

**Review by kvoli — COMMENTED** [review]
TYFTR!

I need to extend the `range_controller/handle_raft_event` test to include changing connection states w/ a `wait_for_eval` running. I've adopted the suggestions, it should be good for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-:-O5PrlZcCvSgQyqtximc:b3d2hwh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PKvBZ9vDemQo4HNpk:-O5Prq1P9M_d2Tpnj9dX:b-jdt4k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L317)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we should make `handleReadyState` return whether its `connectedState` changed in a way that affects the value of shouldWait... And accumulate those here. If any replica changed, we need to call `updateVoterSets`.
</blockquote></details>

Ack, updated to add this.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PE1fF9cBKEIG0-g2c:-O5Prry97i0yz11CJvEG:by9oiic) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L451)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The concept of  "closed" on a `replicaState` is odd. We have a `replicaState` for each replica, regardless of its `connectedState`. I think we should introduce the notion of `replicaSendStream` now, even if the state in there is minimal and move the `connectedState` and `tracker` into it.

We should also do the TODO (which we never did in the prototype) to transition from `probeRecentlyReplicate` to closing the `replicaSendStream` after x seconds. The reason we had `probeRecentlyReplicate` is we don't want to admit a flood of elastic work by excluding the slow replica from WaitForEval if it briefly transitioned to probe and back to replicate. Since `RangeController` relies on `Processor` for most of its locking, and because we don't want O(ranges) goroutines, we could just assume that RangeController is provided a timer scheduling interface in its options. Something like:
```
type ProbeToCloseTimerScheduler interface {
   ScheduleReplicaStreamClose()
}
```
</blockquote></details>

Added in `replicaSendStream` and some refactoring.


```
type ProbeToCloseTimerScheduler interface {
   ScheduleReplicaStreamClose()
}
```

I have a TODO here for now, I'll fill in the rest tomorrow.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PIEpCB2p-W3aZALna:-O5PrvzBCiPYgk6NGP_V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L517)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should we also deduct from sendTokenCounter just to stay consistent with our model, since we will introduce the send-queue.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-:-O5TKrY2BRCxqP8mOTII:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PE1fF9cBKEIG0-g2c:-O5TKnPhDiJ_KRFOzGs3:b5bucbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L451)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Added in `replicaSendStream` and some refactoring.


```
type ProbeToCloseTimerScheduler interface {
   ScheduleReplicaStreamClose()
}
```

I have a TODO here for now, I'll fill in the rest tomorrow.
</blockquote></details>

You can also leave this to a future PR.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 507 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TJchC5_5MDjzEKkkI:-O5TJchC5_5MDjzEKkkJ:bfx9zfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L507)):*
> ```Go
> 	if err != nil {
> 		log.Fatalf(ctx, "error getting encoding of entry: %v", err)
> 	}
> ```

This could be a v1 encoding. It happens to work now (though I am not sure the unit test exercises it -- it ought to), because `EncodingOf` will return priority 0, which just happens to be `raftpb.LowPri`. But we should explicitly add code here to set it to `raftpb.LowPri` in case of a v1 encoding. That is better than leaking into `raftlog.EncodingOf` that v1 priority is always considered LowPri.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TIOvm25y_Jh6KOwOr:-O5TIOvm25y_Jh6KOwOs:b-pyqzq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L522)):*
> ```Go
> 	}
> 	for _, entry := range entries {
> 		state := getEntryFCStateOrFatal(ctx, entry)
> ```

Consider adding a TODO that doing this for each replica for each entry could be optimized by lifting the loop and calling `getEntryFCStateOrFatal` into the caller, and doing it once across all replicas.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 572 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5THStRDVWBzl8ksnTW:-O5THStRDVWBzl8ksnTX:b-36psa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L572)):*
> ```Go
> func (rs *replicaState) closeSendStream(ctx context.Context) {
> 	if rs.sendStream.connectedState != snapshot {
> 		rs.sendStream.changeToStateSnapshot(ctx)
> ```

worth adding a comment that `changeToStateSnapshot` releases all tokens, hence being called here.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TKCe257mzZDPMu78w:-O5TKCe257mzZDPMu78x:b5ja16c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L273)):*
> ```Go
> 	ctx context.Context, wc admissionpb.WorkClass, tokens kvflowcontrol.Tokens,
> ) {
> 	log.Infof(ctx, "deducting tokens %v for work class %v", tokens, wc)
> ```

temporary logging?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TKTqSAsIf9abjOk1N:-O5TKTqSAsIf9abjOk1O:b-7si085) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event#L56)):*
> ```
> admit
> range_id=1
>   store_id=1 term=1 to_index=3 pri=NormalPri
> ```

can you change this so that one replica does not admit everything.

**Review by kvoli — COMMENTED** [review]
TYFTR!

I've updated to reflect the comments. It probably deserves another review before merging as there is a 200+ line diff from the prior commit you reviewed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-:-O5Tlvl6BJvZMGj6yMhW:bkvrxwl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5PE1fF9cBKEIG0-g2c:-O5TerEN4TVvm-fkNlot:b-efyvda) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2d089b5471128c4771da80fae963951e7c622a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L451)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

You can also leave this to a future PR.
</blockquote></details>

Sounds good, lets do that.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 507 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TJchC5_5MDjzEKkkI:-O5Tft1b8cSDeYIXI3pY:b2z0hlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L507)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This could be a v1 encoding. It happens to work now (though I am not sure the unit test exercises it -- it ought to), because `EncodingOf` will return priority 0, which just happens to be `raftpb.LowPri`. But we should explicitly add code here to set it to `raftpb.LowPri` in case of a v1 encoding. That is better than leaking into `raftlog.EncodingOf` that v1 priority is always considered LowPri.
</blockquote></details>

Updated to check here explicitly and set the priority to `LowPri` if v1/v1-sideloaded.  Also added a test.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TIOvm25y_Jh6KOwOr:-O5TlWt32df-rl1rIdj_:b-qkhdkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L522)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Consider adding a TODO that doing this for each replica for each entry could be optimized by lifting the loop and calling `getEntryFCStateOrFatal` into the caller, and doing it once across all replicas.
</blockquote></details>

Lifted the loop.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 572 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5THStRDVWBzl8ksnTW:-O5Tlo9Z3nQbGtDcDoSP:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L572)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

worth adding a comment that `changeToStateSnapshot` releases all tokens, hence being called here.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TKCe257mzZDPMu78w:-O5Tls8W907ymAxyTE_l:bcxsc9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L273)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

temporary logging?
</blockquote></details>

Yeah, removed.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5TKTqSAsIf9abjOk1N:-O5TltnE1vaRVfBsWvHh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e183cf7360c3081a9a967262bc108104c5228a82/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/handle_raft_event#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you change this so that one replica does not admit everything.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-:-O5U4DcZ9wBqb3KEDK62:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 488 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5U3ehN95J2fUpfuj5F:-O5U3ehN95J2fUpfuj5G:br60xkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/891e8ced85ade6414fd2ef55da165188ac9231d2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L488)):*
> ```Go
> 
> 	mu struct {
> 		syncutil.Mutex
> ```

just curious: was this mutex added for the future, when `replicaSendStream` will be called from paths that don't hold `raftMu`? Or something more immediate?

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129759)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 488 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129759#-O5U3ehN95J2fUpfuj5F:-O5UCCTZ9OQ5byGRwkrI:bpv27zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/891e8ced85ade6414fd2ef55da165188ac9231d2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L488)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just curious: was this mutex added for the future, when `replicaSendStream` will be called from paths that don't hold `raftMu`? Or something more immediate?
</blockquote></details>

More immediate. `WaitForEval` holds the `RangeController.mu` to update the voter sets in `updateVoterSets` on refresh/init but `updateVoterSets` reads the `connectedState` which can be written without holding the `RangeController.mu` This `mu` synchronizes this access. It could also be an atomic for now but we will need the `mu` later.

**Comment by kvoli** [comment]
TYFTR!

bors r=sumeerbhola

**Comment by sumeerbhola** [comment]
I'm confused. `rangeController` is relying on external synchronization (`raftMu`) for calls to itself (other than the `WaitForEval` path), which is why it doesn't have a mutex for its `replicaMap`. Any change to `connectedState` for a `replicaSendStream` happens in the context of this external synchronization, and AFAIK, all reads of `connectedState` too. That is, we call `updateVoterSets` while holding `raftMu`. Did I miss something? In the prototype there was at least one path that did not hold `raftMu`, specifically `TokenAvailableNotification.Notify`, so `replicaSendStream` did need its own mutex.

**Comment by kvoli** [comment]
> I'm confused. rangeController is relying on external synchronization (raftMu) for calls to itself (other than the WaitForEval path), which is why it doesn't have a mutex for its replicaMap.

My mistake, this was incorrect:

> [...] but `updateVoterSets` reads the `connectedState` which can be written without holding the `RangeController.mu` This `mu` synchronizes this access. It could also be an atomic for now but we will need the `mu` later.

You're right, `updateVoterSets` is only called while holding `raftMu`, the synchronization on the replica send stream here is premature. I was confusing something here.

**Pull request merged**
