### PR TITLE
distsql: flow registry

### PR DESCRIPTION
**Pull request by RaduBerinde**
Implementing a flow registry that will be used to look up flows by ID when
establishing streams. The key feature of the interface is that lookup waits for
the flow (up to a timeout); this is necessary because the flows on each node
get established in parallel.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7690)

### CODE REVIEW

**Comment by knz** [comment]
LGTM, but is the choice of UUID to identify flows wise? How many flows do we expect and how often are they created? UUIDs are large and slow to generate. What about the NodeID concatenated with HLC timestamp as identifier? Something location- and time-based would make troubleshooting easier.

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-:-KMB5lsXBj_ItXgazCkb:1714197287)*

**Comment by RaduBerinde** [comment]
TFTR!

Honestly it's not really set yet. I had talked to @andreimatei about this and we might switch to having a query ID and a flow ID. The flow ID would be meaningful only within the context of a query ID so it's a small integer (in most cases there would be only one flow per host for a given query). The query ID can be a UUID or something more efficient (like what you suggest). It shouldn't make much of a difference as far as the flow registry code in this PR is concerned though.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-:-KMBGEXBmnh5FcHamrvL:1763505968)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/distsql/flow.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBFoF2A12KF9gBhO_J:-KMBFoF3ghrcXRl3Jt0Q:-336058090) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow.go#L38)):*
> ```Go
> // FlowID identifies a flow. It is most importantly used when setting up streams
> // between nodes.
> type FlowID struct {
> ```

can't you just say `type FlowID uuid.UUID`? That only works with primitives?

---

*[sql/distsql/flow_registry.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBGFuKnpyWkxp4n-5s:-KMBGFuKnpyWkxp4n-5t:100152719) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L29)):*
> ```Go
> type flowEntry struct {
> 	waitCh   chan struct{}
> 	refCount int
> ```

can you comment about what the deal with the `refCount` is?

---

*[sql/distsql/flow_registry.go, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBGyymc8-rcQWDIRk9:-KMBGyymc8-rcQWDIRkA:1911854756) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L35)):*
> ```Go
> // flowRegistry allows clients to look up flows by UUID and to wait for flows to
> // be registered.
> type flowRegistry struct {
> ```

comment on how multiple clients can wait concurrently for the same flow

---

*[sql/distsql/flow_registry.go, line 36 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBG3nCzZP-Q9oLno-w:-KMBG3nCzZP-Q9oLno-x:-1804759499) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L36)):*
> ```Go
> // be registered.
> type flowRegistry struct {
> 	mutex sync.Mutex
> ```

nit: I think we use name `mu` everywhere 

---

*[sql/distsql/flow_registry.go, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBHE_eHaqSw-Kr--bP:-KMBHE_eHaqSw-Kr--bQ:-660030609) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L76)):*
> ```Go
> // registerFlow makes a flow accessible to lookupFlow. Any previous calls that
> // are waiting are woken up.
> func (fr *flowRegistry) registerFlow(id FlowID, f *Flow) {
> ```

nit: consider making some of these methods exported so that you hint how clients will use this class

---

*[sql/distsql/flow_registry.go, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBHWcAPxrjEiGBqMnw:-KMBHWcAPxrjEiGBqMnx:-269972489) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L83)):*
> ```Go
> 		panic("flow already registered")
> 	}
> 	entry.refCount++
> ```

maybe add a function-level comment about how `unregisterFlow` needs to be called eventually to kill this reference.

---

*[sql/distsql/flow_registry.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBI2ub6ecHTDAguJ5k:-KMBI2ucwkE1L0gd11O7:565384737) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L91)):*
> ```Go
> }
> 
> // unregisterFlow removes a flow from the registry. Any subsequent lookupFlow
> ```

who's gonna call this?

---

*[sql/distsql/flow_registry_test.go, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBIkBwf2HeHqVZkpxU:-KMBIkBwf2HeHqVZkpxV:296558367) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry_test.go#L45)):*
> ```Go
> 	// -- Register, lookup, unregister, lookup. --
> 
> 	if f := reg.lookupFlow(id1, 0); f != nil {
> ```

*lookup*,  register, lookup, unregister, lookup  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-:-KMBIwhGj_HwaKC3wL1e:1417088721)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/distsql/flow.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBFoF2A12KF9gBhO_J:-KMBJA5OeRMTeYEl1usT:138427735) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow.go#L38)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> can't you just say `type FlowID uuid.UUID`? That only works with primitives?
</details>
You can but you don't automatically get all the functions that were implemented for `uuid.UUID`

---

*[sql/distsql/flow_registry.go, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBHE_eHaqSw-Kr--bP:-KMBJKYSygMlAYXh-UTY:-616606363) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nit: consider making some of these methods exported so that you hint how clients will use this class
</details>
Done - I actually wanted to ask you this the other day, if you think that is a good idea for arbitrary types and not just interfaces. Are there any traps with this general approach though? Won't some `make check` test complain if exported functions e.g. return unexported types? (not the case here but in general)

---

*[sql/distsql/flow_registry.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBI2ub6ecHTDAguJ5k:-KMBJauemNe3Rx4njtux:-1268238491) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L91)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> who's gonna call this?
</details>
the flow code will call it when the flow finishes (or errors out)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-:-KMBJmDX8ve-7kGO9tbR:-485616692)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/distsql/flow.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBFoF2A12KF9gBhO_J:-KMBP49BFtryhTGk0MrD:-1928437857) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow.go#L38)):*
> all the functions
"any of the methods" I should say

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690)*

**Comment by andreimatei** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/distsql/flow.go, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBFoF2A12KF9gBhO_J:-KMB_rKQiErut-0EuPOC:-1814942719) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow.go#L38)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> > all the functions
> "any of the methods" I should say
</details>
I see, interesting.

---

*[sql/distsql/flow_registry.go, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690#-KMBHE_eHaqSw-Kr--bP:-KMBb_qJFdNiuu-4DjG9:-1809976104) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8816cdad734e3f0fa8200f4f8309ae8a8d1f168/sql/distsql/flow_registry.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Done - I actually wanted to ask you this the other day, if you think that is a good idea for arbitrary types and not just interfaces. Are there any traps with this general approach though? Won't some `make check` test complain if exported functions e.g. return unexported types? (not the case here but in general)
</details>
yeah... I don't know about that linter. But otherwise I *think* it's a good idea...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7690)*

**Pull request merged**
