### PR TITLE
sql: run schema changes in TestRaceWithBackfill asynchronously

### LINKED ISSUE #6293: sql: schema change exceeding pq deadline
https://circleci.com/gh/cockroachdb/cockroach/16801?utm_campaign=build-failed&utm_medium=email&utm_source=notification

is failing because a schema change execution is not fast enough. See:
schema_changer_test.go:451: pq: context deadline exceeded

This test can be fixed to always run the schema change through the async path.

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #6293

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6294)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

Does this also fix #6292 and #6148, or are those separate?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/schema_changer_test.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-KGDxVVLiTBhU539thN0:-KGDxVVLiTBhU539thN1:1363549040) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0dd421d067e07418aa1090548831dc93dd69d1/sql/schema_changer_test.go#L459)):*
Assert that `len(table.Mutations) > 0` here to make sure that the backfills didn't complete synchronously. 

---

*[sql/schema_changer_test.go, line 522 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-KGDx4QqkgWUhLGGZUVN:-KGDx4QqkgWUhLGGZUVO:-154542017) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0dd421d067e07418aa1090548831dc93dd69d1/sql/schema_changer_test.go#L522)):*
Remove the parens.

---

*[sql/schema_changer_test.go, line 529 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-KGDwvEZiQ45KFKBusNr:-KGDwvEZiQ45KFKBusNs:-1623395894) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0dd421d067e07418aa1090548831dc93dd69d1/sql/schema_changer_test.go#L529)):*
Why `+3`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-:-KGDwmCx3beqmWN836tq:-1068613995)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/schema_changer_test.go, line 560 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-KGDxLo6ffE4na9-_Ar3:-KGDxLo6ffE4na9-_Ar4:-1926989109) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0dd421d067e07418aa1090548831dc93dd69d1/sql/schema_changer_test.go#L560)):*
I'm still looking at this, but there's no "pg-wire-protocol deadline". I'm actually unsure about what context deadline you're encoutering. I don't think the sql layer sets any deadlines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/schema_changer_test.go, line 472 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294#-KGE27oFibXCOm8183Cm:-KGE27oFibXCOm8183Cn:-1052770524) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf0dd421d067e07418aa1090548831dc93dd69d1/sql/schema_changer_test.go#L472)):*
besides whether or not the current PR is copacetic, I don't know if I should trust the test as currently written to actually test concurrent backfill and changes.
First of all, isn't it possible that we never see `table.Version == version+2` (and instead directly see `version+3`? That `SucceedsSoon` call can test the condition every second. How long does the backfill take?

Also even if we do see `version+2`, isn't it possible that we see it when the backfill is just about done? That's why I was suggesting the `schemaChangeFilter` before - to get control over when backfill starts and when it ends, and then you can assert that the other changes have overlapped with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6294)*

**Comment by vivekmenezes** [comment]
This was not the right fix.

**Pull request closed without merging**
