### PR TITLE
upgrades: reorganize files

### PR DESCRIPTION
**Pull request by RaduBerinde**
This PR is only for the top commit (it is on top of #114306).

#### upgrades: reorganize files

In this commit we rename files implementing permanent upgrades to
start with `permanent_` and files implementing 23.2 upgrades to start
with `v23_2_`. This will make it easier to remove deprecated upgrades
later.

Informs: #112629
Release note: None

### CODE REVIEW

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114308#-:-Nj9fKP03tktdhlz8cxv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala and @JeffSwenson)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Comment by RaduBerinde** [comment]
bors r-

Actually, let me rebase so the branch history doesn't look weird.

**Pull request merged**
