### PR TITLE
release-22.2: xform: constrain index scans on computed columns in more cases

### PR DESCRIPTION
**Pull request by msirek**
Backport 3/3 commits from #100242.

/cc @cockroachdb/release

---

IN list predicates on index columns which are the inputs to computed
column expressions can't currently constrain the scan if the computed                                                        
columns are a prefix of the index key, e.g.      
```sql
CREATE TABLE t1 (
    id VARCHAR(32) NOT NULL,
    b INT2 NOT NULL AS (CAST(substr(id, 2:::INT8, 1:::INT8) AS INT8)) VIRTUAL,
    CONSTRAINT pkey PRIMARY KEY (b ASC, id ASC));

-- This uses a constrained scan.
SELECT * FROM t1 WHERE id IN ('12345');

-- This does not.
SELECT * FROM t1 WHERE id IN ('12345', '6789');
```

Function `computedColFilters` derives filters on computed columns by
calling `findConstantFilterCols` on all required and optional filters to
find the constants in single-column single-span constraints, then
converts them into single-column single-span predicates on computed
columns.

This change introduces a new, similar function `combineComputedColFilters` 
which combines the steps of finding span key values and building up new
predicates based on them within the same nested loops, so if the derived
predicate needs to be AND'ed with the span keys they were derived from
or nested under an OR term, this can be done.

New terms can be generated from spans with a single key based on one or
more columns, though each `FiltersItem` is processed in isolation, so
there are cases `computedColFilters` can handle which
`combineComputedColFilters` can't.

Fixes: #100206
Fixes: #99557
Fixes: #83343

Release note (performance improvement): This adds support for
constrained scans using computed columns which are part of an index
when there is an IN list predicate on the columns that appears
in the computed column expression.

----
opt: track columns in computed column expressions in metadata

This commit adds tracking of columns present in computed column
expressions to table metadata, tracked in `ColsInComputedColsExpressions`.

Function `combineComputedColFilters` is updated to skip checking of
constraints which do not involve columns referenced in any computed column
expression of the table.

Release note: None

----
sql: add optimizer_use_improved_computed_column_filters_derivation

This commit adds the `optimizer_use_improved_computed_column_filters_derivation`
session setting that defaults to `false`. When `true`, the optimizer will
derive filters on computed columns in more cases. Previously, filters
could only be derived when the expression defining the computed column
involved a single column and that column was equated with a single
constant value in a WHERE clause filter.

Release note (sql change): This patch adds session setting
optimizer_use_improved_computed_column_filters_derivation, which
defaults to `false`. When `true`, the optimizer will derive filters on
computed columns in more cases.

Release justification: Fixes missing derivation of filters on computed columns
in the presence of multi-value IN list predicates. New behavior is disabled by default
behind a session setting.

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 9 of 9 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103424)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCT6B3SydezAP5ust:-NVeCT6B3SydezAP5usu:b-cnxslv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/opt/testutils/opttester/opt_tester.go#L295)):*
> ```Go
> 	ot.evalCtx.SessionData().VariableInequalityLookupJoinEnabled = true
> 	ot.evalCtx.SessionData().OptimizerUseImprovedSplitDisjunctionForJoins = true
> 	ot.evalCtx.SessionData().OptimizerUseImprovedComputedColumnFiltersDerivation = true
> ```

I think we should set this to `false` to match the default session setting.
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCarU97LU9o9sipuj:-NVeCarU97LU9o9sipuk:br5tp0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/sessiondatapb/local_only_session_data.proto#L345)):*
> ```protobuf
>   // during optimization. The goal of this setting is to flush out cases where
>   // panics used for error-propagation are uncaught.
>   bool testing_optimizer_inject_panics = 103;
> ```

nit: remove this unrelated change
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2050 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCrdKAn5NgK3Gt6jH:-NVeCrdKAn5NgK3Gt6jI:b-ijx0ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/opt/xform/testdata/rules/select#L2050)):*
> ```
> # This should not derive the value of c when improved filter derivation is
> # disabled.
> opt expect-not=GenerateConstrainedScans set=optimizer_use_improved_computed_column_filters_derivation=false
> ```

When you change the default you can remove the `set` here, and you'll need to add `set=optimizer_use_improved_computed_column_filters_derivation=true` to the tests above.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103424)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCarU97LU9o9sipuj:-NVeOuWI196tm7JP-mrw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/sessiondatapb/local_only_session_data.proto#L345)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove this unrelated change
</blockquote></details>

Done
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2050 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCrdKAn5NgK3Gt6jH:-NVeOwYe6dyNIH_eS_em:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/opt/xform/testdata/rules/select#L2050)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

When you change the default you can remove the `set` here, and you'll need to add `set=optimizer_use_improved_computed_column_filters_derivation=true` to the tests above.
</blockquote></details>

Done
___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-NVeCT6B3SydezAP5ust:-NVeOlja3p1_SRON70qK:bpjk1yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9133c58facf020ab76854cebab2ad82eb4b89a2/pkg/sql/opt/testutils/opttester/opt_tester.go#L295)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we should set this to `false` to match the default session setting.
</blockquote></details>

Removed this line

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-:-NVjzlyz6eyr-7EFQ5EZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Review by msirek — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103424#-:-NVjzyHNBXyWg9-cSf4I:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

**Pull request merged**
