### PR TITLE
distsql: annotate visual query plans with execution stats

### PR DESCRIPTION
**Pull request by asubiotto**
This is done through the EXPLAIN (DISTSQL, ANALYZE) statement. The
provided statement is executed with tracing enabled and the resulting
statistics found in the trace spans are added to the plan.

Addresses #19476

Release note (sql change): Add EXPLAIN (DISTSQL, ANALYZE). This
annotates distsql execution plans with collected execution statistics.

Note that since we only collect the number of rows read from the tableReader for now, there aren't that many stats on the plan yet.

Result:
screen shot 2018-05-23 at 10 06 32 am

### CODE REVIEW

**Comment by asubiotto** [comment]
@RaduBerinde Do you mean from a user experience perspective? I don't have any concerns with EXPLAIN running the query, and it seems postgres does as well.

@solongordon That would be more in line with postgres but it seems to also have some variant with `EXPLAIN (ANALYZE, BUFFERS)`. I would rather just stick to this syntax since other options also follow the same syntax unless you have strong feelings about it.

@petermattis It definitely is interesting to do that but my thinking is that downstream processors will also have input stats eventually so you would be duplicating information there for a single stream. In cases where the stream splits, I plan on adding information to the `hashRouter` like the total number of rows it routed which would achieve the same goal I think.

**Comment by asubiotto** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/explain_distsql, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDCdev--x6xRNGNNUab:-LDIbUnPBt5YG9j1sdXU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6db1a3ec1c15952f2977e93d856d0c707ea9ef5a/pkg/sql/logictest/testdata/logic_test/explain_distsql#L131)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] no need for `;`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849)*

**Comment by andreimatei** [comment]
My vote is to keep `explain` pure by not running the query, and use `analyze` or maybe `trace` for things that need to run it.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-:-LDXywQj7i5Oc8NxSXUQ:b-6irmr0)*

**Comment by asubiotto** [comment]
Oracle, SQL Server and MySQL have some statistics setting that is enabled/disabled around the query. In the case of MySQL, these stats are not actual query execution stats but rather estimates from the optimizer. This is sort of similar to enabling session tracing/running `SHOW TRACE FOR <STMT>`. However, I feel like we should support `EXPLAIN ANALYZE` to be in line with postgres (its own top-level statement), since familiarity to pg users is a good thing to aim for. If there is any surprise in `EXPLAIN` running the query, it will come from non-pg users who will probably have other surprises to deal with as well.

I'll switch the statement to be `EXPLAIN ANALYZE (DISTSQL)` (thanks for the suggestion @solongordon)

**Comment by jordanlewis** [comment]
`EXPLAIN ANALYZE (DISTSQL)` sounds good to me.

**Comment by asubiotto** [comment]
Statement changed and rebased. PTAL

**Comment by asubiotto** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/sql.y, line 2136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDmUXx37_cIXwD9JhMW:-LDmeUMs2ZwgWxwBvGPb:bdmzbnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/parser/sql.y#L2136)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I like that you're implementing this as if it was just another flag; unfortunately we still accept the `EXPLAIN (ANALYZE, DISTSQL)` syntax which could lead to confusion. Maybe we should have a couple of `Explain` constructors which could check for this.
</blockquote></details>

I double-checked and we don't accept that. `ANALYZE` is not accepted by the parser as an explain option since it is a reserved keyword and the requirements for an `explain_option_name` are that it is unreserved. As a side-note, maybe we should properly define what an `explain_option_name` can be.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/parser/sql.y, line 2136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDmUXx37_cIXwD9JhMW:-LDmkFUl74eu346LPZyc:b-1y0b30) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/parser/sql.y#L2136)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I double-checked and we don't accept that. `ANALYZE` is not accepted by the parser as an explain option since it is a reserved keyword and the requirements for an `explain_option_name` are that it is unreserved. As a side-note, maybe we should properly define what an `explain_option_name` can be.
</blockquote></details>

Ah, nice!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/explain_distsql.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDqZvPC7ryTO3qKa2yO:-LDqZvPC7ryTO3qKa2yP:b-bokpey) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L34)):*
> ```Go
> 
> 	// If analyze is set, plan will be executed with tracing enabled and a url
> 	// pointing to a visual query plan with statistics will be returned.
> ```

very minor nit: returned where and by what?

---

*[pkg/sql/explain_distsql.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDqZz_d6GI7PzI_8eD3:-LDqZz_d6GI7PzI_8eD4:boww8e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L37)):*
> ```Go
> 	analyze bool
> 	// stmtType is only used if analyzing a statement. It is needed by the
> 	// distSQLWrapper.
> ```

nit: you've explained when it's used and why it's needed, but what does it correspond to? i would say "stmtType is the originating StatementType for the plan" or something like that.

---

*[pkg/sql/explain_distsql.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDq_wLnC6VeD4ZNZ8Vz:-LDq_wLnC6VeD4ZNZ8W-:bhfxx2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L76)):*
> ```Go
> 	if n.analyze {
> 		if params.extendedEvalCtx.Tracing.Enabled() {
> 			return errTracingAlreadyEnabled
> ```

so you can't EXPLAIN ANALYZE with session tracing on? Is this is a problematic limitation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-:-LDCdhlk2rWOiKM9qnQj:bnfp4nl)*

**Comment by asubiotto** [comment]
Review status: 14 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/explain_distsql.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDqZvPC7ryTO3qKa2yO:-LDqhUW94lx4vvZFAJls:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L34)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

very minor nit: returned where and by what?
</blockquote></details>

Done.

---

*[pkg/sql/explain_distsql.go, line 37 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDqZz_d6GI7PzI_8eD3:-LDqvBpf0RnPdF4BlaSU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L37)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: you've explained when it's used and why it's needed, but what does it correspond to? i would say "stmtType is the originating StatementType for the plan" or something like that.
</blockquote></details>

Done.

---

*[pkg/sql/explain_distsql.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDq_wLnC6VeD4ZNZ8Vz:-LDqhcbJC59C3dzMNldF:b7g5c8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/explain_distsql.go#L76)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

so you can't EXPLAIN ANALYZE with session tracing on? Is this is a problematic limitation?
</blockquote></details>

That's a good point. This mirrors the show trace node but it's less surprising to not be able to run a trace on a statement during session tracing than not be able to run `EXPLAIN ANALYZE`. Changed.

---

*[pkg/sql/parser/sql.y, line 2136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25849#-LDmUXx37_cIXwD9JhMW:-LDquEN02Erwn8y_PlkP:b51lxaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/28db2e4718d8c3ba080afbf14ca4b3bd1b183e87/pkg/sql/parser/sql.y#L2136)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, nice!
</blockquote></details>

On the other hand, we do accept `EXPLAIN ANALYZE (<option list that doesn't necessarily include DISTSQL>)`. Added some logic when parsing explain options.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25849)*

**Pull request merged**
