### PR TITLE
allocator2: constraintMatcher test and fixes

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs https://github.com/cockroachdb/cockroach/issues/103320

Epic: [CRDB-25222](https://cockroachlabs.atlassian.net/browse/CRDB-25222)

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
first commit is from https://github.com/cockroachdb/cockroach/pull/103533

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-:-NVgNUQ7EZRqffrbyZji:bfdxpzz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by kvoli — APPROVED** [review]
:lgtm:

Nice test again, these are intuitive to read.

> Reviewed 1 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-:-NVomhG75kywRYdERfLW:ba7vvot)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-NVok0OJ65t7EjD0VA8o:-NVok0OKBKG6tcyAsGHm:bxzmpi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c84e9356bdf267b7c0c59a9da761923e7ee78a6b/pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go#L131)):*
> ```Go
> 				}
> 			}
> 			if matches {
> ```

Can this ever be hit? Perhaps I'm misreading but it appears all the matches=true cases are followed by a break.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-NVokMLK23z7vlgJBj00:-NVokMLK23z7vlgJBj01:b8ioutd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c84e9356bdf267b7c0c59a9da761923e7ee78a6b/pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go#L156)):*
> ```Go
> 		cm.constraints[c] = ms
> 		for storeID, mc := range cm.stores {
> 			matches := cm.storeMatchesConstraint(mc.descriptor, c)
> ```

nit: why not use `if matches := ...;`?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-:-NVoquAA8ro4CSwrYJvD:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-NVok0OJ65t7EjD0VA8o:-NVoq71GEh6jGKmweAy2:b1fjh6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c84e9356bdf267b7c0c59a9da761923e7ee78a6b/pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go#L131)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Can this ever be hit? Perhaps I'm misreading but it appears all the matches=true cases are followed by a break.
</blockquote></details>

this is to break out of the outer loop
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103561#-NVokMLK23z7vlgJBj00:-NVoqKj-ASN7TPBTE23i:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c84e9356bdf267b7c0c59a9da761923e7ee78a6b/pkg/kv/kvserver/allocator/allocator2/constraint_matcher.go#L156)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: why not use `if matches := ...;`?
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
