### PR TITLE
[WIP] backupccl: persist protected ts between scheduled incremental backups

### PR DESCRIPTION
**Pull request by adityamaru**
TODO

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
@miretskiy this is a very early preview that I wanted to get your opinion on. I haven't taken it for a spin yet but wanted input on a few things, and looking at some code might make it easier:

Context around what we are trying to achieve here can be found in https://github.com/cockroachdb/cockroach/issues/67282.

I'm conflicted about whether this baton passing of protected timestamp records between backups in a chain should be handled by the job (as in the PR), or by the scheduled backup executor. 

I went with the former since we already have a logical concept of "chained backups" where one backup derives some information from a previous backup in the chain. It seemed intuitive that we should use this to cascade forward the protected timestamp information. Should we even consider leaking interaction with the protected ts subsystem outside of the job, my intuition says no.

OTOH, this is a unique semantic that we only expect scheduled incremental backups to use. Maybe the full/incremental jobs should update the incremental schedule with the protected timestamp record that needs to be passed on to the next backup, and we do the relevant cleanup in `NotifyJobTermination`.  One complication that comes to mind is how we synchronize the scheduled incremental after the next full to pick up the record from the new full instead of the last incremental in the previous chain. Backup manifests allow us to do this quite gracefully.

There are still some TODOs I have to figure out to ensure we don't have orphaned records lying around after the schedule has passed it by. Happy to talk about this offline too.

**Comment by miretskiy** [comment]
I'm going to take a look when I get back from vacation

**Comment by adityamaru** [comment]
> I'm going to take a look when I get back from vacation

I didn't realize, sorry! Enjoy your vacation 🙂

**Review by miretskiy — COMMENTED** [review]
I appreciate the simplicity of this approach, and I appreciate the fact that we didn't have to touch schedules in any way.
But I'm not sure that this is the approach would work well (but I may as well be wrong -- so, bear with me).


> I went with the former since we already have a logical concept of "chained backups" where one backup derives some information from a previous backup in the chain

I agree that we have a notion of "chained backup", but up to this point, everything was rather loosely coupled.
The incremental backup doesn't "know" that it's chained -- only that it ought to read "latest" to determine where to place its data.

The schedules themselves are also not "chained" -- they are independent.  And that independence is where I feel some pitfalls might be.  For example, what happens if you run full backup, record the PTS record, and then (just like one of the customers did), decide to delete incremental schedule?  Would we wind up protecting spans until next full backup?  Is that desirable?

What happens if you drop the entire backup schedule (both full + incremental) after few runs?

Another complication is that jobs PTS record reconciler would ignore the backup job record if it has a "protect" bit set.  But
that's also not great: like, what does it mean if you have a PTS record, but the customer changed their mind, and just wiped out entire backup directory?  We no longer have any record of protected timestamp.

So, roughly 3 big issues that I think we need to resolve:
   1. We should try (hard) to not strongly depend on chained logic.  I think this will complicate matters now, and will undoubtedly make it even harder if we decide to add differential backups or some such.
   2. We don't have a good mechanism to handle schedules being dropped or paused.
   3. We lack any visibility into this protected timestamp -- outside of using low level crdb_internal functions to decode
        payloads and/or read build manifests.  This information, even though is related to schedules are not surfaced in any way
       when examining schedules (`show schedule`).

Based on the above (and assuming I'm not entirely wrong), I would advocate that we add "parent_id" field to backup schedule records (incremental will have parent id set, full one will not).
The PTS record would always be associated with the full schedule.  `NotifyJobTermination` would drop & update 
record appropriately.  The actual record ID can be persisted in execution args (kinda sucks that we would need to mutate
full schedule record every time backup runs -- but I don't see it as a big red flag).
I don't think we need to implement anything ala jobs reconciliation wrt to PTS, but we may.
With this rough approach, I think we'll have a story around observability as well as a reasonable way to handle dropping
(and maybe pausing schedules).

WDYT?

> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67633#-:-MevLD8C6DJ3ddK3Y1lP:bop1hdq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67633#-MeuiyLb8QTGdQ4Wy_Bx:-MeuiyLb8QTGdQ4Wy_By:b-lblctm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f96ce3aca0996a454e244488123d1262aa784b92/pkg/ccl/backupccl/create_scheduled_backup.go#L356)):*
> ```Go
> 		//
> 		// This chaining allows us to decouple incremental schedules from the
> 		// configured GC TTL, since we protect what we need as we go.
> ```

It would be useful to also note how failures are handled wrt to PTS records.

**Comment by adityamaru** [comment]
I like this! 

A couple of thoughts that popped in my head while reading your approach:

1. I'm wondering if we can completely decouple these protected ts records from the jobs using them, and associate them with the schedule. i.e. Introduce a new `MetaType` - https://github.com/cockroachdb/cockroach/blob/bb6ebca7513d91769db3e6f689afb31d179fdd0c/pkg/kv/kvserver/protectedts/ptpb/protectedts.pb.go#L127 maybe `PersistedScheduledBackup` and a corresponding `Meta`
```
message {
    schedule_id int. // full schedule id (parent schedule)
    canBeReleased bool
}
```

Then on `NotifyJobTermination` the job running as part of the incremental schedule would look for its parent schedule, mark `canBeReleased = true`, and do a best attempt `release` on the protected record. If the release fails then we won't fail the job/schedule instead we will have new reconciliation logic that marks records as releasable if either:
- schedule_id can no longer be found in the schedules table
- schedule_id can be found, but `canBeReleased = true`

2. Full backups after the first one should not persist/release protected timestamp records associated with the schedule. They should allow incremental backups on either side of the full to do the right thing.

Thinking about the time when we have two jobs (a full and an incremental) running concurrently, as part of the "same" schedule. Assume that the incremental job starts on the previous chain, and while it is running a new full backup starts, and completes. On completion, if the full backup releases the protected record being tracked in the parent schedule, the running incremental which is still relying on it might fail. If the full backup persists a new protected record at its `EndTime` we now have 2 protected records that this schedule needs to keep track of instead of 1. 

To avoid all this complexity maybe we should have something as follows:
- first full protects after `EndTime` and persists record in the parent schedule.
- each incremental on completion protects after its `EndTime` and releases the previous record.

**Comment by adityamaru** [comment]
Discussion continued in #67282 but this PR has served its purpose 🙂.

**Pull request closed without merging**
