### PR TITLE
sql: fix panic with null delimiter in string_agg

### LINKED ISSUE #28836: sql: panic in concatAggregate
```
SELECT subq_0.c3 AS c0, subq_0.c6 AS c1, subq_0.c4 AS c2, CASE WHEN (SELECT start_key FROM crdb_internal.ranges LIMIT 1 OFFSET 6) < CAST(NULLIF(pg_catalog.string_agg(CAST((SELECT start_key FROM crdb_internal.ranges LIMIT 1 OFFSET 7) AS BYTES), CAST((SELECT pg_catalog.xor_agg(tgargs) FROM pg_catalog.pg_trigger) AS BYTES)) OVER (PARTITION BY subq_0.c0 ORDER BY subq_0.c0, subq_0.c5, subq_0.c2), CAST(NULL AS BYTES)) AS BYTES) THEN subq_0.c6 ELSE subq_0.c6 END AS c3, subq_0.c2 AS c4, subq_0.c7 AS c5, CAST(COALESCE(subq_0.c7, subq_0.c7) AS INT8) AS c6 FROM (SELECT ref_0.table_name AS c0, ref_0.table_catalog AS c1, ref_0.table_type AS c2, (SELECT rolcreatedb FROM pg_catalog.pg_roles LIMIT 1 OFFSET 79) AS c3, ref_0.table_name AS c4, ref_0.version AS c5, ref_0.version AS c6, ref_0.version AS c7 FROM information_schema.tables AS ref_0 WHERE (ref_0.version IS NOT NULL) OR (pg_catalog.set_masklen(CAST(CAST(NULL AS INET) AS INET), CAST(ref_0.version AS INT8)) != (SELECT pg_catalog.max(client_addr) FROM pg_catalog.pg_stat_activity)) LIMIT 101) AS subq_0 WHERE subq_0.c7 IS NOT NULL
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #28836.

Release note: None

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
Nice catch!  

Please add a logic test for this.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28837#-:-LKNW3gFEhdKOQhYyZHY:b-slp6lf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28837#-LKNVj0v1tV8eb5yeSz_:-LKNVj0w5ZXrNCMKLdBf:b-pd1sdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e90c021dede89c5dff26484d2b09dfe443bff1e3/pkg/sql/sem/builtins/aggregate_builtins.go#L642)):*
> ```Go
> 	// via the first element in others.
> 	if len(others) == 1 {
> 		if others[0] == tree.DNull {
> ```

This behaviour is incorrect.  In postgres, using a NULL in both a window function or normal aggregate, the result is to treat it as an empty delimiter.

**Comment by jordanlewis** [comment]
I added a logic test containing this massive query that caught the bug. I actually can't figure out how to reproduce with just a simple window function! Maybe we could sit together and look at it?

**Comment by jordanlewis** [comment]
Reduced the test case. PTAL

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28837#-:-LKNk2N02cGhNOBWgDGI:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
