### PR TITLE
storage: Dial remote nodes asynchronously in the raft transport

### LINKED ISSUE #40362: teamcity: failed test: TestStopServer
The following tests appear to have failed on master (test): TestStopServer

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestStopServer).

[#1462371](https://teamcity.cockroachdb.com/viewLog.html?buildId=1462371):

```
TestStopServer
..., 11 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc005f38a50, 0x4fe)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc005f38a40)
	/usr/local/go/src/sync/cond.go:56 +0x9e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc0065d9a80, 0x4136a60, 0xc0064a4090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:192 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4136a60, 0xc0064a4090)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0024fb0f0, 0xc005e81a70, 0xc0024fb0e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

goroutine 5709 [sync.Cond.Wait, 11 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc005f38a50, 0x508)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc005f38a40)
	/usr/local/go/src/sync/cond.go:56 +0x9e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc0065d9a80, 0x4136a60, 0xc0064a40c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:192 +0x7c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4136a60, 0xc0064a40c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:161 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0024fb110, 0xc005e81a70, 0xc0024fb100)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

goroutine 5672 [chan receive, 11 minutes]:
github.com/cockroachdb/cockroach/pkg/server.(*Server).startListenRPCAndSQL.func3(0x4136a60, 0xc00616ee70)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1709 +0xd5
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00022eb40, 0xc005e81a70, 0xc005f38500)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

goroutine 5782 [select, 11 minutes]:
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1(0x4136a60, 0xc0064cced0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:748 +0x15e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc002cf5430, 0xc005e81a70, 0xc0065a47a0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

goroutine 7905 [sync.Cond.Wait, 11 minutes]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc005c52fd0, 0xc)
	/usr/local/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc005c52fc0)
	/usr/local/go/src/sync/cond.go:56 +0x9e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Quiesce(0xc005e81a70, 0x41369e0, 0xc000102018)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:544 +0x1df
github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers.func1(0xc004c32d70, 0xc005e81a70)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:95 +0x83
created by github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).stopServers
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:92 +0xe0




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by ajwerner**
Prior to this PR, calls to RaftTransport.SendAsync() would synchronously
Dial the remote node if there wasn't an existing connection. This is
problematic as those calls to SendAsync() happen while holding the raftMu.
Therefore, if a remote process being dialed were somehow listening on the
TCP process but not accepting or processing new connections we may block
indefinitely. This effectively allowed a single hung process (think ctrl-z
on a cockroach process) to make an entire cluster unavailable.

There's no reason for this Dial to be synchronous.

My sense is that we should merge this for this release but I could be convinced
otherwise.

Fixes #40362.

Release justification: This is a pretty bad bug and pretty minor change that
I'd be in favor of backporting.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@tbg want to review this or pass it to somebody else?

**Comment by tbg** [comment]
Happy to review, but it won't be until tomorrow so if someone beats me to
it that's ok

**Comment by ajwerner** [comment]
>Happy to review, but it won't be until tomorrow so if someone beats me to
it that's ok

Of course, no rush, I wish there was a way to send you async notifications on github. Enjoy your night!

**Comment by tbg** [comment]
It's async, I just happened to peek in :-)

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/raft_transport_test.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41087#-LpgU1vP9K6FtAMUbhIq:-LpgU1vP9K6FtAMUbhIr:bwk26jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d842071c497ac8670fa5e2658b530f8d7345a87/pkg/storage/raft_transport_test.go#L623)):*
> ```Go
> 	// Set up a plain old TCP listener that's not going to accept any connecitons
> 	// which will lead to blocking during dial.
> 	ln, err := net.Listen("tcp", util.TestAddr.String())
> ```

The listener doesn't have to be closed to make leakcheck happy?

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41087#-:-Lphx5pCC8h0FOz5jJea:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/raft_transport_test.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41087#-LpgU1vP9K6FtAMUbhIq:-LphnVkZC5aNhrLMBQeW:b-7ji1av) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d842071c497ac8670fa5e2658b530f8d7345a87/pkg/storage/raft_transport_test.go#L623)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The listener doesn't have to be closed to make leakcheck happy?
</blockquote></details>

Interestingly no, there's no underlying goroutine attached to that listener. I've added a `defer ln.Close()` because it's good practice but it's not required.

**Pull request merged**
