### PR TITLE
util/log: new logging channels SQL_SCHEMA, USER_ADMIN and PRIVILEGES

### PR DESCRIPTION
**Pull request by knz**
Release note (cli change): Notable events that pertain to SQL schema,
user and privilege changes are now sent on the new SQL_SCHEMA,
USER_ADMIN and PRIVILEGES channels. These can now be redirected to
different sinks from the other log entries.

**SQL_SCHEMA**

The SQL_SCHEMA channel is used to report changes to the
SQL logical schema, excluding privilege and ownership changes
(which are reported on the separate channel PRIVILEGES) and
zone config changes (which go to OPS).

This includes:

- database/schema/table/sequence/view/type creation
- adding/removing/changing table columns
- changing sequence parameters

etc., more generally changes to the schema that affect the
functional behavior of client apps using stored objects.

**USER_ADMIN**

The USER_ADMIN channel is the channel used to report changes
in users and roles, including:

- users added/dropped.
- changes to authentication credentials, incl passwords, validity etc.
- role grants/revocations.
- role option grants/revocations.

This is typically configured in "audit" mode, with event
numbering and synchronous writes.

**PRIVILEGES**

The PRIVILEGES channel is the channel used to report data
authorization changes, including:

- privilege grants/revocations on database, objects etc.
- object ownership changes.

This is typically configured in "audit" mode, with event
numbering and synchronous writes.

### CODE REVIEW

**Comment by knz** [comment]
Rebased this today.
There is some interference with #53313 and #53313, which causes some state not to be cleaned up properly after TestRedirectStderrWithSecondaryLoggersActive. Will work on that next.

**Comment by knz** [comment]
fixed the broken log tests. The issue was a missing clearing of the `channels[]` map.

Next step is to fix the TCL logging tests since the file names are changing.

Additioanlly the logging directory for the SQL audit log needs to be configurable.

**Comment by knz** [comment]
I have extracted the individual bits from the original change in this PR to the following new PRs:

- util/log,cli: channel abstraction; new configuration system #57134
-  util/log: new experimental integration with Fluentd #57170 
-  *: new logging channels OPS and HEALTH #57171 

As a result the original PR has been greatly slimmed down, so much it is now just a draft for a follow-up project to bring `system.eventlog` under logging. If/when that project makes progress, I plan to solicit review here again.

**Comment by knz** [comment]
Rebased this on top of `master` which greatly simplifies the review.

@itsbilal RFAL

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51987#-:-MOXsq8V9wecDDr4n1F5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/logpb/log.proto, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51987#-MOXsSdb8cvz6Zkoz2C2:-MOXsSdb8cvz6Zkoz2C3:b-puphkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b3186d591d9d0851df2091517404e100993be4d/pkg/util/log/logpb/log.proto#L98)):*
> ```protobuf
>   // This is typically configured in "audit" mode, with event
>   // numbering and synchronous writes.
>   SENSITIVE_ACCESS = 7;
> ```

The renumbering is unfortunate. I'm assuming this is a non-issue as log messages aren't meant to transcend nodes.

**Comment by knz** [comment]
> The renumbering is unfortunate. I'm assuming this is a non-issue as log messages aren't meant to transcend nodes.

I can revert that. IT's not mandatory. My reasoning is that we have no released versions with these channel numbers embedded in log files yet, so it's ok to do this renaming now (it won't be after the next stable release), for the sake of readability.

WDYT?

**Comment by itsbilal** [comment]
Sure, that sounds good to me. We haven't "released" this so a renumbering is fine.

**Comment by knz** [comment]
thanks!

bors r=itsbilal

**Pull request merged**
