### PR TITLE
sql: change DefaultExprs after ALTER TABLE LOCALITY ... REGIONAL BY ROW

### PR DESCRIPTION
**Pull request by otan**
We previously relied on the `gateway_region` of the schema changer to
dictate what the rows would be populated as. However, in actuality, we
want the region to be the PRIMARY REGION when changing the table to
REGIONAL BY ROW for the first time.

This pattern is unfortunately unsupported by the schema changer right now:
```
BEGIN;
-- Run backfill on all columns to 5.
ALTER TABLE t ADD COLUMN col INT DEFAULT 5.
-- We want any new rows afterwards will default to 10.
-- Unfortunately with the current schema changer world, the data will
all backfill to 10.
ALTER TABLE t ALTER COLUMN col SET DEFAULT 10;
COMMIT
```

Which means we have to introduce an intermediate "hacky" solution to
support backfilling as PRIMARY REGION but then after backfill completion
defaulting to gateway_region().

When we add the crdb_region column, we initially set the default to
PRIMARY REGION. We then modify LocalitySwapConfig on ALTER PRIMARY KEY
to contain information about the column ID and correctly serialized
default expression after the ALTER PRIMARY KEY is complete.

When the schema changer completes, we modify the column on the table
descriptor to use gateway_region().

Release note: None

### CODE REVIEW

**Review by ajstorm — COMMENTED** [review]
>This pattern is unfortunately supported by the schema changer right now:

Don't you wish that it was supported?  I think what you mean here is that "is unfortunately _not_ supported".

Aside from that, this looks reasonable to me, but I yield to @ajwerner on the schema change details.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTBBvvA3kPtngqSIqu0:boydiai)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTBEe167mftRO95Jt68:-MTBEe167mftRO95Jt69:b7mmd8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/427b00c1fde1259fa7f87698f40140bc1bcd0dde/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L453)):*
> ```
> # Check the row was backfilled to the primary region.
> query TI
> SELECT crdb_region, pk FROM created_as_global ORDER BY pk ASC
> ```

Can we add one more test here to insert after backfill and confirm that we get the gateway region?
___
*[pkg/sql/alter_table_locality.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTBCj1h3sHuH0WudCe_:-MTBCj1h3sHuH0WudCea:bbfcerp) ([raw file](https://github.com/cockroachdb/cockroach/blob/427b00c1fde1259fa7f87698f40140bc1bcd0dde/pkg/sql/alter_table_locality.go#L253)):*
> ```Go
> 		}
> 		// No crdb_region column is found so we are implicitly creating it.
> 		// We insert the column definition before altering the primary key.
> ```

This seems like the perfect place to explain the fact that we're backfilling with the primary region, but we'll change that after the backfill is complete to use the `gateway_region()`.
___
*[pkg/sql/alter_table_locality.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTBDcuP1QnoGa72qwc0:-MTBDcuP1QnoGa72qwc1:b76uuwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/427b00c1fde1259fa7f87698f40140bc1bcd0dde/pkg/sql/alter_table_locality.go#L289)):*
> ```Go
> 		}
> 
> 		col := n.tableDesc.GetMutations()[mutationIdx].GetColumn()
> ```

Nit: Above here a comment would also be helpful to explain that this is what we want the final column to look like.

**Review by otan — COMMENTED** [review]
hehe, fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTCrJW57XNZvYCpvKFb:b9l1rvl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @otan)

**Review by ajwerner — APPROVED** [review]
I'm cool with this. This does mean that concurrent writes during the backfills will go to the primary region rather than the gateway region. A more involved but potentially better approach would be to inject the default value of the primary region only for the column backfill. 

> Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTEkmER1IqsoGvvTdOI:b-u3txm0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/create_table.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTEjMBGCRH3Ka_vQyWt:-MTEjMBH5glxymkzkrdu:b40thjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8a843988b4b6210ed16e6abb31309d5071e3af/pkg/sql/create_table.go#L2648)):*
> ```Go
> 	return &tree.CastExpr{
> 		Expr:       tree.NewDString(string(region)),
> 		Type:       &tree.OIDTypeReference{OID: oid},
> ```

Very tangential aside mostly unrelated to this PR:

I'm working with @the-ericwang35 on making sure that when we store sequences references in default exprs, we do it by the ID. The working proposal is that when formatting the table we swap `<integer sequence id>::regclass` with `<fully qualified name>::regclass`. That felt sane to me given postgres's display of regclass values. I'm thinking we need to do something similar with types. For view queries things get a little more tricky.

The long and the short of it is: do you think it'd be reasonable to, at formatting time, replace `OIDTypeReference` values with their fully-qualified counterpart, unconditionally?

**Review by ajwerner — APPROVED** [review]
I guess it doesn't matter too much because the primary index isn't partitioned, so, definitely :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTElHFB9Zvyei1hMysT:boe7tgk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — COMMENTED** [review]
I've had a shot at the other way and https://github.com/cockroachdb/cockroach/pull/60476. Which do you prefer?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTFzwQsAUtmlH1QEjrP:bkj7ra3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/create_table.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTEjMBGCRH3Ka_vQyWt:-MTG--af82XJDtVVIdL5:b3txsz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8a843988b4b6210ed16e6abb31309d5071e3af/pkg/sql/create_table.go#L2648)):*
> I'm working with @the-ericwang35 on making sure that when we store sequences references in default exprs, we do it by the ID

This seems to contradict

> when formatting the table we swap <integer sequence id>::regclass with <fully qualified name>::regclass

do we want to store it by FQ path? does that screw with renames?

> The long and the short of it is: do you think it'd be reasonable to, at formatting time, replace OIDTypeReference values with their fully-qualified counterpart, unconditionally?

should be done at SanitizeVarFreeExpr?

**Review by ajwerner — APPROVED** [review]
I think I prefer this one for the reasons you mentioned. I don't think it's important to populate the region prior to the completion of the schema change. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-:-MTGZ_Fx-gYRyXOLPqli:bwg4u67)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/create_table.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTEjMBGCRH3Ka_vQyWt:-MTGYJvd4qOun-E7BqA9:bt1birt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8a843988b4b6210ed16e6abb31309d5071e3af/pkg/sql/create_table.go#L2648)):*
Let me make this more concrete:

Say user does:

```
CREATE DATABASE db;
USE db;
CREATE SEQUENCE seq; -- assume this has ID 52
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval('seq'));
```
Then we'd store `t` as:

```
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval(52:::regclass)
```

So the DefaultExpr is `52:::regclass`

But then in `SHOW CREATE` and other formatting contexts we'd display it as:

```
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval('db.public.seq':::regclass)
```

> should be done at SanitizeVarFreeExpr?

Maybe, for now we're planning on rewriting these exprs in an updated [maybeAddSequenceDependencies](https://github.com/cockroachdb/cockroach/blob/53b7d3fd72ff3fb2fff60ee7f382e1a18b271d66/pkg/sql/sequence.go#L569). I could see centralizing this re-writing even more. 

Does this make sense?

**Comment by otan** [comment]
___
*[pkg/sql/create_table.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60310#-MTEjMBGCRH3Ka_vQyWt:-MTHaR9m7pcR3-iYArq0:b-tu5ww4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8a843988b4b6210ed16e6abb31309d5071e3af/pkg/sql/create_table.go#L2648)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Let me make this more concrete:

Say user does:

```
CREATE DATABASE db;
USE db;
CREATE SEQUENCE seq; -- assume this has ID 52
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval('seq'));
```
Then we'd store `t` as:

```
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval(52:::regclass)
```

So the DefaultExpr is `52:::regclass`

But then in `SHOW CREATE` and other formatting contexts we'd display it as:

```
CREATE TABLE t (i PRIMARY KEY DEFAULT nextval('db.public.seq':::regclass)
```

> should be done at SanitizeVarFreeExpr?

Maybe, for now we're planning on rewriting these exprs in an updated [maybeAddSequenceDependencies](https://github.com/cockroachdb/cockroach/blob/53b7d3fd72ff3fb2fff60ee7f382e1a18b271d66/pkg/sql/sequence.go#L569). I could see centralizing this re-writing even more. 

Does this make sense? 
</blockquote></details>

Oh yeah I'm on board. I think we replace OIDTypeReference unconditionally already, based on my experience with SHOW CREATE TABLE tests with these.

**Comment by otan** [comment]
bors r=ajwerner

**Pull request merged**
