### PR TITLE
sql: populate information_schema.user_defined_types and attributes

### LINKED ISSUE #109603: Implement INFORMATION_SCHEMA.USER_DEFINED_TYPES and INFORMATION_SCHEMA.ATTRIBUTES
**Is your feature request related to a problem? Please describe.**

I would like to reverse engineer user-defined types from the `INFORMATION_SCHEMA` via the standard views:

- `USER_DEFINED_TYPES`
- `ATTRIBUTES`

**Describe alternatives you've considered**

I can probably work with queries against `pg_type` and `pg_attribute` as I've done before with the lack of `ROUTINES` support (see https://github.com/cockroachdb/cockroach/issues/104083):

```sql
select *
from pg_catalog.pg_type as t
join pg_catalog.pg_attribute as a on a.attrelid = t.typrelid
where t.typname = 't';
```

But for the future support of third party tooling, I still think these `INFORMATION_SCHEMA` views would be useful.

Jira issue: CRDB-31015

### PR DESCRIPTION
**Pull request by annrpom**
commit 1-4:
### sql: add necessary builtins for information_schema.attributes

These patches add the following builtins:
- information_schema._pg_char_octet_length: returns the octet length of a given char/varchar/string
- pg_encoding_max_length: returns the maximum length of a given encoding. Since we only support UTF8, this will return length 4.
- information_schema._pg_datetime_precision: returns the precision of the given datetime-related type
- information_schema._pg_interval_type: displays the interval type duration if it is set

Needed for: #109603
Epic: none

Release note (sql change): The information_schema._pg_char_octet_length, information_schema._pg_datetime_precision, information_schema._pg_interval_type, and pg_encoding_max_length builtin functions are now supported, which improves compatibility with PostgreSQL.

---
last commit:
### sql: populate information_schema.user_defined_types and attributes

This patch populates information_schema.user_defined_types with
information about user defined types and information_schema.attributes
with information about the attributes of composite data types.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/109603

Release note (sql change): This patch populates
information_schema.user_defined_types with information about user
defined types and information_schema.attributes with information about
the attributes of composite data types.

### CODE REVIEW

**Comment by annrpom** [comment]
- [ ] add tests

**Review by rafiss — CHANGES_REQUESTED** [review]
this is great! my comments are all minor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-:-Ni03NiU8w_2EnWCZPQH:bv9fb5r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni0-eKE9Fdo21TZVo_I:-Ni0-eKFA-48RkjuwD3Z:bv0uctq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2186)):*
> ```Go
> 	),
> 
> 	// NOTE: this could be defined as a user-defined function, like
> ```

nit: this comment seems outdated, since that's how the function is defined now. we could just keep the part that links to postgres source
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02Dlc2tzmQ0_VCnfL:-Ni02Dlc2tzmQ0_VCnfM:b-gyjm7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2203)):*
> ```Go
> 	//          ELSE null
> 	// END;
> 	"information_schema._pg_char_octet_length": makeBuiltin(tree.FunctionProperties{Category: builtinconstants.CategorySystemInfo},
> ```

this function could use some basic tests
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni00tUl5ZUYK_gE4NBO:-Ni00tUl5ZUYK_gE4NBP:bcmtivv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2212)):*
> ```Go
> 			Body: `SELECT
> 						 CASE WHEN $1 IN (25, 1042, 1043)
> 			            THEN CASE WHEN $2 = -1
> ```

nit: the comments that are included above would make this more understandable. i mean the ` /* text, char, varchar */` and `/* default typmod */` comments
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02JcY0_VOVH0BfP5J:-Ni02JcY0_VOVH0BfP5K:bupmtsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/sem/builtins/pg_builtins.go#L2273)):*
> ```Go
> 	),
> 
> 	// NOTE: this could be defined as a user-defined function, like
> ```

nit: "could be" is outdated here; this comment just needs a link to the postgres code
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02QSZ8unHi6Cadp27:-Ni02QSZ8unHi6Cadp28:bglw2m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/sem/builtins/pg_builtins.go#L2294)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.String),
> 			Body: `SELECT
> 						 CASE WHEN $1 IN (1186) 
> ```

nit: the `/* interval */` comment could be helpful here
___
*[`pkg/sql/logictest/testdata/logic_test/pg_builtins` line 951 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02a5a5I7RF6lXNB0T:-Ni02a5a5I7RF6lXNB0U:bmryd5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/logictest/testdata/logic_test/pg_builtins#L951)):*
> ```
> ORDER BY a.attname
> ----
> attname  typname   information_schema._pg_interval_type
> ```

nit: could you add some test cases where the result of `_pg_interval_type_ is not null?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111401)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni0-eKE9Fdo21TZVo_I:-Ni2TV0M-ttm_juUzeka:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2186)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this comment seems outdated, since that's how the function is defined now. we could just keep the part that links to postgres source
</blockquote></details>

done
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02Dlc2tzmQ0_VCnfL:-Ni2ZsSj84stLfLoRsdp:b-8vq6jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2203)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this function could use some basic tests
</blockquote></details>

these were added in the commit with pg_encoding_max_length - since pg_encoding_max_length was needed for _pg_char_octet_length

 i added some tests for pg_encoding_max_length and moved the commits next to eachother!
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni00tUl5ZUYK_gE4NBO:-Ni2eSNe6SmEw4tR6UNJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6846d7c282da9f0d3b643d868f05d43187087b5/pkg/sql/sem/builtins/pg_builtins.go#L2212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the comments that are included above would make this more understandable. i mean the ` /* text, char, varchar */` and `/* default typmod */` comments
</blockquote></details>

done
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02JcY0_VOVH0BfP5J:-Ni2f0yA5O-Noilbm8TI:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/sem/builtins/pg_builtins.go#L2273)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: "could be" is outdated here; this comment just needs a link to the postgres code
</blockquote></details>

done
___
*[`pkg/sql/sem/builtins/pg_builtins.go` line 2294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02QSZ8unHi6Cadp27:-Ni2f1e41P33plqh6yDa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/sem/builtins/pg_builtins.go#L2294)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the `/* interval */` comment could be helpful here
</blockquote></details>

done
___
*[`pkg/sql/logictest/testdata/logic_test/pg_builtins` line 951 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-Ni02a5a5I7RF6lXNB0T:-Ni55OGe5uO6aWNe4D6r:blxp516) ([raw file](https://github.com/cockroachdb/cockroach/blob/229a8d377466eaaf8cc7043a08bbda2d96d1b353/pkg/sql/logictest/testdata/logic_test/pg_builtins#L951)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you add some test cases where the result of `_pg_interval_type_ is not null?
</blockquote></details>

hmmm looks like this will return null for now due to how interval types in TypeModifier get handled - let me get a fix up for this. think I need to have another check for if t.InternalType.IntervalDurationField.DurationType != IntervalDurationType_UNSET - not sure yet what I should be returning. maybe postgres source code has something for me

**Comment by annrpom** [comment]
> maybe postgres source code has something for me

This is now looking like a separate issue - as this looks to be a compatibility bug that existed before this PR (see issue above) For now, information_schema._pg_interval_type does not work properly on intervals that have durations on them

**Review by rafiss — APPROVED** [review]
lgtm!! nice work on seeing this through. (feel free to rebase and merge)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111401#-:-Ni__Jm0DTgbq4XomRwc:b-lu81gl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by annrpom** [comment]
TFTR! ('-')7 

bors r=rafiss

**Pull request merged**
