### PR TITLE
sql: support SHOW ALL CLUSTER SETTINGS.

### PR DESCRIPTION
**Pull request by knz**
This statement form will list all known cluster-wide settings.

### CODE REVIEW

**Comment by dt** [comment]
Hm, I'm completely sure I like reusing the single-value syntax and special casing the name "all".

If we used a different syntax (like `SHOW ALL CLUSTER SETTINGS` or something), i'd also suggest we keep the single setting SHOW only returning the value as ideally I'd like to fix it so it returns a matching type, which would mean matching the column type to it as well.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-:-Ki6mlE1n9rliUrYEKm3:b-bm4ce5)*

**Comment by knz** [comment]
Can you rephase your first sentence, I'm not sure I understand it.

I have modified  the code so that the single-value SHOW CLUSTER SETTINGS return their proper Datum type.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-:-Ki6poHxSgAbj8Y56VIY:b-lom542)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/cache.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-Ki6z2STaioBVWdZoXNj:-Ki6z2STaioBVWdZoXNk:b-2ujspz) ([raw file](https://github.com/cockroachdb/cockroach/blob/217acfe7e145065857963c2dacbd2739326627f1/pkg/settings/cache.go#L101)):*
> ```Go
> // GetDatum returns the value of the setting as a Datum, together with
> // its description.
> func GetDatum(key string) (parser.Datum, string) {
> ```

I've been really trying to avoid adding any cockroach dependencies to this package -- those packages, and all the packages they depend on, will become unable to use settings if we do, so I'd rather we do this switch on the type in show.go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179)*

**Comment by knz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/cache.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-Ki6z2STaioBVWdZoXNj:-Ki6zj2daA4N0FZFzB6b:b-8pxomd) ([raw file](https://github.com/cockroachdb/cockroach/blob/217acfe7e145065857963c2dacbd2739326627f1/pkg/settings/cache.go#L101)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I've been really trying to avoid adding any cockroach dependencies to this package -- those packages, and all the packages they depend on, will become unable to use settings if we do, so I'd rather we do this switch on the type in show.go.
</blockquote></details>

Ok, but then we need to export the `getXXX()` accessors, are you ok with that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179)*

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/settings/cache.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-Ki6z2STaioBVWdZoXNj:-Ki70qQkLhhwOjUj0cbt:b-9j0sez) ([raw file](https://github.com/cockroachdb/cockroach/blob/217acfe7e145065857963c2dacbd2739326627f1/pkg/settings/cache.go#L101)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok, but then we need to export the `getXXX()` accessors, are you ok with that?
</blockquote></details>

that's one option -- another would exporting `Value` and basically just returning getVal, or even another would be having this function as-is return interface{} and cast it in show... 

pulling in parser dep here though will make settings unusable in `parser` and all its deps, which I'd really like to avoid, and am willing to have some isolated grossness in `show.go` if that's what it takes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179)*

**Comment by knz** [comment]
Ack; Done. PTAL

**Comment by dt** [comment]
:lgtm:

still slightly -1 on the special `all` name (vs the parser setting a flag or returning a different AST node), but that won't matter until someone tries to make a setting called 'all', so its a theoretical, not practical complaint for now.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-:-KiAL_33TIZzUhDVrbFM:b-murg66)*

**Comment by knz** [comment]
Yes, we can change this later if need be.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15179#-:-KiATF7T4OxMZVL2tevW:b-ocvgb2)*

**Pull request merged**
