### PR TITLE
slstorage: minor cleanups

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
https://github.com/cockroachdb/cockroach/pull/52692

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52723#-:-MEZ3jQ57_eqcd6B74rx:b-qk1q1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

**Review by ajwerner — APPROVED** [review]
I'm cool with this other than the merge skew with dt's change. 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52723#-:-MEZ3yK564Wp13bgIVpD:b-3djpob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @spaskob)

___
*[pkg/sql/sqlliveness/slstorage/slstorage.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52723#-MEZ3nPZ9BLWBA_ZDZmx:-MEZ3nPZ9BLWBA_ZDZmy:b-lgdur5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9696b40d91c50fcd228ead95507666dadc70a12/pkg/sql/sqlliveness/slstorage/slstorage.go#L252)):*
> ```Go
> 	s.metrics.SessionDeletionsRuns.Inc(1)
> 	s.metrics.SessionsDeleted.Inc(n)
> 	if n > 0 {
> ```

this one is already happening  https://github.com/cockroachdb/cockroach/pull/52692

**Comment by andreimatei** [comment]
Resolved the merge skew. Not much is left of the first commit.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52723#-:-MEZ8psx0IXPw4Kf9V-1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @spaskob)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52723#-:-MF6eG5C0fH-E-lmk7Q0:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @spaskob)

**Pull request merged**
