### PR TITLE
sql: implement unnest builtin

### LINKED ISSUE #12785: sql: support unnest() built-in function
https://www.postgresql.org/docs/9.6/static/functions-array.html

This is needed for the second line of the following ActiveRecord query:

```
WITH pk_constraint AS (
  SELECT conrelid, unnest(conkey) AS connum FROM pg_constraint
  WHERE contype = 'p'
    AND conrelid = '"numbers"'::regclass
), cons AS (
  SELECT conrelid, connum, row_number() OVER() AS rownum FROM pk_constraint
)
SELECT attr.attname FROM pg_attribute attr
INNER JOIN cons ON attr.attrelid = cons.conrelid AND attr.attnum = cons.connum
ORDER BY cons.rownum
```

### PR DESCRIPTION
**Pull request by jordanlewis**
unnest is a set-returning function that returns each element of an array
as a single-column row containing that element.

Resolves #12785.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13154)

### CODE REVIEW

**Comment by tamird** [comment]
no occurrences of NamedArgTypes, :shipit:

**Comment by knz** [comment]
Very good work.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/parser/generator_builtins.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPpar0H3yVKY_bUv9O:-KbPpar1hGQAbj2fgSKC:b5ue2jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L117)):*
> ```Go
> 	"unnest": {
> 		makeGeneratorBuiltin(
> 			ArgTypes{{"input", TypeIntArray}},
> ```

I though nathan had done something by which we could say "this builtin works on every array of T and returns T", isn't that a thing we can use here?

cc @nvanbenschoten

---

*[pkg/sql/parser/generator_builtins.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPprDFt8R3K6vO2fXv:-KbPprDFt8R3K6vO2fXw:b-f32wgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L200)):*
> ```Go
> 	arr, ok := args[0].(*DArray)
> 	if !ok {
> 		panic(fmt.Errorf("expected *DArray, found %T", args[0]))
> ```

The type checker guarantees the cast is always valid. Remove `ok` and the check on it.

---

*[pkg/sql/parser/generator_builtins.go, line 216 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq4ysAIzsH5UISWQh:-KbPq4ysAIzsH5UISWQi:bd71ob2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L216)):*
> ```Go
> 
> // Start implements the ValueGenerator interface.
> func (s *arrayValueGenerator) Start() error { return nil }
> ```

`s.nextIndex = -1` here

---

*[pkg/sql/parser/generator_builtins.go, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq82Yhmol0R9H_C4X:-KbPq82ZFaCqipIOzqvc:bb7bh5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L224)):*
> ```Go
> func (s *arrayValueGenerator) Next() (bool, error) {
> 	s.nextIndex++
> 	if s.nextIndex > s.array.Len() {
> ```

`>=`

---

*[pkg/sql/parser/generator_builtins.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPqAQAZzXty98ZRjL9:-KbPqAQAZzXty98ZRjLA:b-aqjv4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L232)):*
> ```Go
> // Values implements the ValueGenerator interface.
> func (s *arrayValueGenerator) Values() DTuple {
> 	if s.nextIndex == 0 {
> ```

I would remove this check. Go does array bound checking for us already -- it would panic anyway.

---

*[pkg/sql/parser/generator_builtins.go, line 236 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq8v3uSMg1b9GJLll:-KbPq8v3uSMg1b9GJLlm:b-acq63a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L236)):*
> ```Go
> 		panic("programming error: called Values() before Next() on arrayValueGenerator")
> 	}
> 	return DTuple{s.array.Array[s.nextIndex-1]}
> ```

`Array[s.nextIndex]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-:-KbPp5ylyXm6GNn8pmFB:b-ovvi4h)*

**Comment by jordanlewis** [comment]
TFTR!

---

Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/parser/generator_builtins.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPpar0H3yVKY_bUv9O:-KbQot9uxSG3QRFLWl9N:b-6cp161) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L117)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I though nathan had done something by which we could say "this builtin works on every array of T and returns T", isn't that a thing we can use here?

cc @nvanbenschoten
</blockquote></details>

I tried that (by making the input argument `TypeAnyArray`, the output `TypeAny`, and then having ColumnTypes do what it does now and return a `TTuple` with inner type whatever's the inner type of the array. I don't think this feature is ready yet. Isn't it part of https://github.com/cockroachdb/cockroach/pull/12644 ?

---

*[pkg/sql/parser/generator_builtins.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPprDFt8R3K6vO2fXv:-KbQoq9NcQQyLdVEer8H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L200)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The type checker guarantees the cast is always valid. Remove `ok` and the check on it.
</blockquote></details>

Done.

---

*[pkg/sql/parser/generator_builtins.go, line 216 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq4ysAIzsH5UISWQh:-KbQoqleXp8M1dX5P4WP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L216)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`s.nextIndex = -1` here
</blockquote></details>

Done.

---

*[pkg/sql/parser/generator_builtins.go, line 224 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq82Yhmol0R9H_C4X:-KbQor73bZyKtX7XZk2_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L224)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`>=`
</blockquote></details>

Done.

---

*[pkg/sql/parser/generator_builtins.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPqAQAZzXty98ZRjL9:-KbQorMcSKbPik-0eOVL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L232)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would remove this check. Go does array bound checking for us already -- it would panic anyway.
</blockquote></details>

Done.

---

*[pkg/sql/parser/generator_builtins.go, line 236 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPq8v3uSMg1b9GJLll:-KbQorcc_7-XIuxueHzo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L236)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`Array[s.nextIndex]`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-:-KbQpXPENiUfaYcLUX0G:b-814g8k)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/generator_builtins.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-KbPpar0H3yVKY_bUv9O:-KbR54D5b5Fs_tf51J1h:baog74f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bb1afcc8314efc4b2cc49ce7f3739ba9809a939/pkg/sql/parser/generator_builtins.go#L117)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I tried that (by making the input argument `TypeAnyArray`, the output `TypeAny`, and then having ColumnTypes do what it does now and return a `TTuple` with inner type whatever's the inner type of the array. I don't think this feature is ready yet. Isn't it part of https://github.com/cockroachdb/cockroach/pull/12644 ?
</blockquote></details>

Yes indeed. Please add a note/TODO on #12644 to properly annotate unnest().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13154#-:-KbR5Dxr4AYw0AjW-y35:bnfp4nl)*

**Pull request merged**
