### PR TITLE
rpc,server: move ownership of ClusterIDContainer to server.Config

### PR DESCRIPTION
**Pull request by knz**
All commits but the last from #73161 and prior PRs.
(Reviewers: focus on the last commit.)

Informs #58938.

Prior to this patch, the `rpc.Context` was the owner of the cluster ID
container. This made it hard to capture a reference to the cluster ID
container prior to the instantiation of the RPC subsystem.

This commit fixes that by transferring the ownership away from RPC,
like was done for the node ID container already in #73160.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
catalog code LGTM

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73252#-:-MpnCpO_5vj3Tc9kKZvi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @rimadeodhar, and @tbg)

___
*[pkg/rpc/context.go, line 413 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73252#-MpnCkNJBv8MSg9ywOHN:-MpnCkNJBv8MSg9ywOHO:bgg7c0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11c4c3629779aa568e690df65b476e03b8ad2a5/pkg/rpc/context.go#L413)):*
> ```Go
> 		// Tests rely on NewContext to generate its own ID container.
> 		var c base.ClusterIDContainer
> 		opts.ClusterID = &c
> ```

[nit] ` = &base.ClusterIDContainer{}`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rimadeodhar and @tbg)

___
*[pkg/rpc/context.go, line 413 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73252#-MpnCkNJBv8MSg9ywOHN:-MqP8NKDDDWRp765unr-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11c4c3629779aa568e690df65b476e03b8ad2a5/pkg/rpc/context.go#L413)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] ` = &base.ClusterIDContainer{}`
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r=ajwerner,RaduBerinde

**Pull request merged**
