### PR TITLE
changefeedccl: enable the RangeFeed version of more tests

### PR DESCRIPTION
**Pull request by danhhz**
Changefeed resolved timestamps rely on RangeFeed checkpoints which rely
on closed timestamps which only work with epoch leases. This means that
any changefeed test that _uses RangeFeed_ and _needs resolved
timestamps_ should first wait until all the relevant ranges have
epoch-leases.

This commit adds that waiting to unblock RangeFeed work, but it takes
~10s, so we should fix it for real at some point. The permanent fix is
being tracked in #32495.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
How odd. Teamcity got a timeout in both test and testrace, so it should be reproducable, but I haven't seen it locally.

**Comment by danhhz** [comment]
Turns out this failure only happens in ./build/builder.sh, but it happens reliability in the builder. Should be straightforward to work out.

**Comment by danhhz** [comment]
Okay @mrtracy I'm pretty sure I've figured out the test failures. This should be ready to go!

**Review by mrtracy — APPROVED** [review]
LGTM

**Comment by danhhz** [comment]
TFTR!

bors r=mrtracy

**Pull request merged**
