### PR TITLE
sql: add `VIEWACTIVITY`/`VIEWACTIVITREDACTED` permission for `ranges_no_leases`

### PR DESCRIPTION
**Pull request by THardy98**
Fixes: #98514

This change adds the `VIEWACTIVITY` and `VIEWACTIVITREDACTED` permissions access to `ranges_no_leases`. This allows users to view range data, necessary to use popular console pages:
- databases page
- database details page
- database table page

Prior to this change, users with `VIEWACTIVITY`/`VIEWACTIVITYREDACTED` would not be able to view these pages (would show error notification).

Release note (bug fix): Allow users with
`VIEWACTIVITY`/`VIEWACTIVITYREDACTED` permissions to access `ranges_no_leases` table, necessary to view important console pages (databases, database details, and database table pages).

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/crdb_internal.go` line 3566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNX2GCSPefzvlWfpQ:-NQRNX2GCSPefzvlWfpR:b-easde1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/crdb_internal.go#L3566)):*
> ```Go
> 		// if the user has no VIEWACTIVITY or ZONECONFIG privilege on any table/schema/database
> 		if !hasPermission {
> 			return nil, nil, pgerror.Newf(pgcode.InsufficientPrivilege, "only users with the VIEWACTIVITY or ZONECONFIG privilege or the admin role can read crdb_internal.ranges_no_leases")
> ```

nit: or VIEWACTIVITYREDACTED
___
*[`pkg/sql/delegate/show_ranges.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNgUjE6kkG1D9RmRY:-NQRNgUjE6kkG1D9RmRZ:bp47s3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/delegate/show_ranges.go#L60)):*
> ```Go
> 	}
> 	if err := d.catalog.CheckPrivilege(d.ctx, table, privilege.ZONECONFIG); err != nil {
> 		return pgerror.Wrapf(err, pgcode.InsufficientPrivilege, "only users with the VIEWACTIVITY or ZONECONFIG privilege or the admin role can use SHOW RANGES on %s", table.Name())
> ```

nit: or `VIEWACTIVITYREDACTED`
___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNkJb7xohQf1J3LWJ:-NQRNkJb7xohQf1J3LWK:b-easde1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L422)):*
> ```
> select * from crdb_internal.node_runtime_info
> 
> query error pq: only users with the VIEWACTIVITY or ZONECONFIG privilege or the admin role can read crdb_internal.ranges_no_leases
> ```

nit: or VIEWACTIVITYREDACTED
___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNoGI50NZ59auJrkv:-NQRNoGI50NZ59auJrkw:b-easde1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/logictest/testdata/logic_test/crdb_internal#L670)):*
> ```
> select * from crdb_internal.node_runtime_info
> 
> query error pq: only users with the VIEWACTIVITY or ZONECONFIG privilege or the admin role can read crdb_internal.ranges_no_leases
> ```

nit: or VIEWACTIVITYREDACTED

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/crdb_internal.go` line 3566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNX2GCSPefzvlWfpQ:-NQRPbOV8tmCG6Y35sTE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/crdb_internal.go#L3566)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: or VIEWACTIVITYREDACTED
</blockquote></details>

Done.
___
*[`pkg/sql/delegate/show_ranges.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNgUjE6kkG1D9RmRY:-NQRPZJ5DHH-QOteq-ZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/delegate/show_ranges.go#L60)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: or `VIEWACTIVITYREDACTED`
</blockquote></details>

Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant` line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNkJb7xohQf1J3LWJ:-NQRP_QzBJgg1ggF5rU5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant#L422)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: or VIEWACTIVITYREDACTED
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRNoGI50NZ59auJrkv:-NQRPaPCEvcBJ8H4Riz3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af520816ac9febc3680d2da734fc88567bcc141/pkg/sql/logictest/testdata/logic_test/crdb_internal#L670)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: or VIEWACTIVITYREDACTED
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm: 
make sure to add the backports label to it

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-:-NQRRU4V1_Xm_SuvPglD:b6s4mds)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/delegate/show_ranges.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRQSPd7gTxKtLAdF4D:-NQRQSPd7gTxKtLAdF4E:b-yme048) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc262675384445d170e0ea80bacc30109b30d10f/pkg/sql/delegate/show_ranges.go#L41)):*
> ```Go
> 		return nil
> 	}
> 	hasView := d.catalog.CheckPrivilege(d.ctx, table, privilege.VIEWACTIVITY) == nil
> ```

it feels like it would be more natural and safer to check these privileges in crdb_internal.go instead. could we move it there?

there's also an issue with swallowing the error. it's not safe to do always. if the error is "insufficient privilege" then it can be swallowed. but any other error should be returned immediately, or you could end up in a weird state.

to check that you can use `pgerror.GetPGCode(err) == pgcode.InsufficientPrivilege`, or if you move the check to crdb_internal, you should be able to use a `HasPrivilege` function that is better about not swallowing errors

**Comment by rafiss** [comment]
i also just noticed that this is being merged into `release-22.2` directly? could you update the commit message to explain why `master` doesn't need this change?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @THardy98)

___
*[`pkg/sql/crdb_internal.go` line 3558 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRlnKd1cuC_roeyCT1:-NQRlnKd1cuC_roeyCT2:b9lkmyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d396aad6ef671f07b3ce4d579daef74203da5/pkg/sql/crdb_internal.go#L3558)):*
> ```Go
> 				return true
> 			}
> 			return p.CheckPrivilege(ctx, desc, privilege.ZONECONFIG) == nil
> ```

this is getting closer. the contract with these `has*` checks is that if it returns an error, then you _must_ propagate it up to the caller. it could be an error that causes the transaction to abort

and we should update the ZONECONFIG check to do the same (this one was a mistake in this code from before your PR. looks like it was fixed in master but not release-22.2)

so:
```
		privCheckerFunc := func(desc catalog.Descriptor) (bool, error) {
			if hasAdmin {
				return true, nil
			}
			hasViewPriv, err := p.HasViewActivityOrViewActivityRedactedRole(ctx)
			if err != nil {
				return false, err
			}
			if hasViewPriv {
				return true, nil
			}
			return p.HasPrivilege(ctx, desc, privilege.ZONECONFIG, p.User())
		}
```
___
*[`pkg/sql/delegate/show_ranges.go` line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-NQRnFC49tl9yjYpJ93g:-NQRnFC49tl9yjYpJ93h:btgn0kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/246d396aad6ef671f07b3ce4d579daef74203da5/pkg/sql/delegate/show_ranges.go#L46)):*
> ```Go
> 		return nil
> 	}
> 	hasViewAct, err := d.catalog.HasRoleOption(d.ctx, roleoption.VIEWACTIVITY)
> ```

since the checks are in crdb_internal now, let's remove the VIEWACTIVITY and ZONECONFIG checks from this function

**Review by THardy98 — COMMENTED** [review]
I've added explicitly added this change as part of:
https://github.com/cockroachdb/cockroach/pull/93209
when I noticed VIEWACTIVITY users couldn't use this table. In hindsight, a separate PR with a backport would be better. I'll close this PR open a separate one and link it here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98518#-:-NQRoAfu3-SIkP0p113m:bs4fhsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

**Comment by THardy98** [comment]
Closed in favour of: https://github.com/cockroachdb/cockroach/pull/98535

**Pull request closed without merging**
