### PR TITLE
sql: assign sequence ownership created when create/alter table

### LINKED ISSUE #69298: sql: related sequence from a `SERIAL` column is not deleted when `DROP TABLE`
**Describe the problem**

The `SERIAL` syntax under `CREATE TABLE` creates an underlying sequence. When we `DROP TABLE`, in PostgreSQL this underlying sequence will be deleted at the same time. But in CRDB, this sequence stays.

**To Reproduce**

I'm using PostgreSQL 13.3 and CockroachDB 21.1.7 on MacOS.

In PostgreSQL:

```
postgres=# \d
Did not find any relations.

postgres=# CREATE TABLE t (x SERIAL);
CREATE TABLE

postgres=# \d
           List of relations
 Schema |  Name   |   Type   |  Owner
--------+---------+----------+----------
 public | t       | table    | postgres
 public | t_x_seq | sequence | postgres
(2 rows)

postgres=# DROP TABLE  t;
DROP TABLE

postgres=# \d
Did not find any relations
```

In CockroachDB (with unrelated lines deleted):

```
demo@127.0.0.1:26257/movr> set serial_normalization=sql_sequence;
SET

demo@127.0.0.1:26257/movr> CREATE TABLE t (x SERIAL);
CREATE TABLE

demo@127.0.0.1:26257/movr> \d
  schema_name |         table_name         |   type   | owner | estimated_row_count | locality
--------------+----------------------------+----------+-------+---------------------+-----------
  public      | t                          | table    | demo  |                   0 | NULL
  public      | t_x_seq                    | sequence | demo  |                   0 | NULL



demo@127.0.0.1:26257/movr> DROP TABLE t;
DROP TABLE


demo@127.0.0.1:26257/movr> \d
  schema_name |         table_name         |   type   | owner | estimated_row_count | locality
--------------+----------------------------+----------+-------+---------------------+-----------
  public      | t_x_seq                    | sequence | demo  |                   0 | NULL
```

**If possible, provide steps to reproduce the behavior:**
I ran cockroachDB with:

cd ~/your/path/to/cockroachdb/cockroach
gmake buildshort
./cockroach demo

**Expected behavior**
In this `DROP TABLE` case, the SERIAL column in CRDB is expected to behave the same as in PostgreSQL.

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #69298

  Release note (bug fix): A sequence is created when a column is
  defined as `SERIAL` type and the `serial_normalization` session
  variable is set to `sql_sequence`. In this case, the sequence is
  owned by the column and the table where the column exists. The
  sequence should be dropped when the owner table/column is dropped,
  which is the postgres behavior. However, cockroach never set
  ownership information correctly but only dependecy relationship.
  So the sequence stays even the owner table/column does not exist
  anymore. This fix assigns correct ownership information to sequence
  descriptor and column descriptor so that cockroach can align with
  postgres behavior.

### CODE REVIEW

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74840)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/add_column.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOEiV_0OklqzpYOvEI:-MtOEiV_0OklqzpYOvEJ:bwkruwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/add_column.go#L170)):*
> ```Go
> 	// If the new column has a DEFAULT or an ON UPDATE expression that uses a
> 	// sequence, add references between its descriptor and this column descriptor.
> 	if err := cdd.ForEachTypedExpr(func(expr tree.TypedExpr) error {
> ```

This block is mostly moved from above.
___
*[pkg/sql/add_column.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOEmkXCGpPDi240VHU:-MtOEmkXCGpPDi240VHV:bie8z4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/add_column.go#L178)):*
> ```Go
> 		}
> 		for _, changedSeqDesc := range changedSeqDescs {
> 			if colOwnedSeqDesc != nil && colOwnedSeqDesc.ID == changedSeqDesc.ID {
> ```

I think in theory `colOwnedSeqDesc` and `changedSeqDesc` should refer to a same instance, we can set ownership outside of this loop by using `colOwnedSeqDesc`. But still want to make sure I'm modifying the right copy here just in case the assumption is not true any more in the future..
___
*[pkg/sql/create_sequence.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOFVwEEdI0GeMpo5Sc:-MtOFVwEEdI0GeMpo5Sd:b-5fuoll) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/create_sequence.go#L177)):*
> ```Go
> }
> 
> func createSequencesForSerialColumns(
> ```

This function is mostly a copy paste extraction from `create_table.go` below. Also narrow down the `params` dependency to a subset of its fields.
___
*[pkg/sql/temporary_schema.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOGZoI8Hyg5_u4W2iG:-MtOGZoI8Hyg5_u4W2iH:bm5f09m) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/temporary_schema.go#L272)):*
> ```Go
> 		databaseIDToTempSchemaID[uint32(desc.GetParentID())] = uint32(desc.GetParentSchemaID())
> 
> 		// If a sequence is owned by a table column, it is dropped when the owner
> ```

this is covered by an existing test
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOG64TE0t0_BUTV8B6:-MtOG64TE0t0_BUTV8B7:b5gaq82) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/catalog/tabledesc/table_desc.go#L176)):*
> ```Go
> // SetSequenceOwner adds sequence id to the sequence id list owned by a column
> // and set ownership values of sequence options.
> func (desc *Mutable) SetSequenceOwner(colName tree.Name, table *Mutable) error {
> ```

I'm always not proud of myself whenever creating a function with side effects... We may not need a function for this at all.

**Review by ajwerner — COMMENTED** [review]
I'm good with this. We should probably backport it, at least the last release. Backporting to 21.1 has gotten somewhat painful. 

> Reviewed 6 of 15 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-:-MuBTdBbBMldtBd8m2j5:b-jgfnqt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @chengxiong-ruan)

___
*[pkg/ccl/importccl/read_import_mysql.go, line 433 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBRQgi77kZMFwsxzhR:-MuBRQgi77kZMFwsxzhS:bl4v5c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e840c4ddf41a5be02c04944d2fa8233fd2e25a/pkg/ccl/importccl/read_import_mysql.go#L433)):*
> ```Go
> 		seqDesc, err = sql.NewSequenceTableDesc(
> 			ctx,
> 			nil,
> ```

nit: comment the nil
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBRfTwCtFXPkaSBjyd:-MuBRfTwCtFXPkaSBjye:bfwt3qx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e840c4ddf41a5be02c04944d2fa8233fd2e25a/pkg/ccl/importccl/read_import_pgdump.go#L319)):*
> ```Go
> 		desc, err := sql.NewSequenceTableDesc(
> 			ctx,
> 			nil,
> ```

nit: comment the nil 
___
*[pkg/sql/add_column.go, line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOEmkXCGpPDi240VHU:-MuBS2zL9GRKPzfwrshp:bh1jnvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/add_column.go#L178)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I think in theory `colOwnedSeqDesc` and `changedSeqDesc` should refer to a same instance, we can set ownership outside of this loop by using `colOwnedSeqDesc`. But still want to make sure I'm modifying the right copy here just in case the assumption is not true any more in the future..
</blockquote></details>

I hear you. The assumption should be true. It used to not be true, but we did work in 2020 to make it such that if you resolve the same descriptor mutably in the same transaction you get the same object. You can rely on that. That being said, this is fine. It'd be better if you added some explanatory commentary. 
___
*[pkg/sql/testutils.go, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBSvF--9Xw3l_2bZnf:-MuBSvF--9Xw3l_2bZng:bl4v5c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e840c4ddf41a5be02c04944d2fa8233fd2e25a/pkg/sql/testutils.go#L77)):*
> ```Go
> 		desc, err := NewSequenceTableDesc(
> 			ctx,
> 			nil,
> ```

nit: comment the nil
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOG64TE0t0_BUTV8B6:-MuBT0J_35FZUsLPGyME:b-2xtyl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/catalog/tabledesc/table_desc.go#L176)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

I'm always not proud of myself whenever creating a function with side effects... We may not need a function for this at all.
</blockquote></details>

How would you feel about having this as a helper function in the `sql` package as opposed to as a method on the descriptor? 
___
*[pkg/sql/logictest/testdata/logic_test/serial, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBTTgz5g-JTQ4BFoS5:-MuBTTgz5g-JTQ4BFoS6:b-4q0qzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb72381cab272a4f03871032cc2195e97c11260a/pkg/sql/logictest/testdata/logic_test/serial#L225)):*
> ```
> ----
> serial  CREATE TABLE public.serial (
>         a INT8 NOT NULL DEFAULT nextval('public.serial_a_seq1'::REGCLASS),
> ```

what in this change caused the naming changes here?
___
*[pkg/ccl/importccl/testutils_test.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBTYI30zSyBiwhUCEg:-MuBTYI30zSyBiwhUCEh:bl4v5c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e840c4ddf41a5be02c04944d2fa8233fd2e25a/pkg/ccl/importccl/testutils_test.go#L63)):*
> ```Go
> 		desc, err := sql.NewSequenceTableDesc(
> 			ctx,
> 			nil,
> ```

nit: comment the nil

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @chengxiong-ruan)

___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MtOG64TE0t0_BUTV8B6:-MuBsgW76d1oGhHFTHHT:bee6ink) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f7769506b047597ad135be5440a79dc0cb1787/pkg/sql/catalog/tabledesc/table_desc.go#L176)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How would you feel about having this as a helper function in the `sql` package as opposed to as a method on the descriptor? 
</blockquote></details>

yeah, I'm happy with that. It's better to have a function acting the side effect than a method on an object.
___
*[pkg/sql/logictest/testdata/logic_test/serial, line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuBTTgz5g-JTQ4BFoS5:-MuBt0WJ4H2OcAv9J3XW:bk8zve1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb72381cab272a4f03871032cc2195e97c11260a/pkg/sql/logictest/testdata/logic_test/serial#L225)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what in this change caused the naming changes here?
</blockquote></details>

there's a test before this line already create sequence with name `public.serial_a_seq`, and we have a logic to find the first available sequence name by appending incremental integers to a default sequence name. so there is a sequence of sequence name like `public.serial_a_seq1`, `public.serial_a_seq2`, `public.serial_a_seq3` if we create more.... with this change since the sequence from previous test is dropped and the names become available when creating this table, these names change :(

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-:-MuXRNfXEOBqaTXcZWw1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @chengxiong-ruan)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 315 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74840#-MuXRUUS1aHb_tQYilwo:-MuXRUUS1aHb_tQYilwp:bwaqkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6afe54eb6879c990ddfb9db55b1c37085f1bbab4/pkg/ccl/importccl/read_import_pgdump.go#L315)):*
> ```Go
> 	for schemaAndTableName, seq := range createSeq {
> 		schema, err := getSchemaByNameFromMap(ctx, schemaAndTableName, schemaNameToDesc, execCfg.Settings.Version)
> 		if err != nil {
> ```

This is a good catch!

**Pull request merged**
