### PR TITLE
kvserver: consolidate RaftTruncatedState handling

### PR DESCRIPTION
**Pull request by pav-kv**
This PR simplifies handling the `RaftTruncatedState` eval result, and adds TODO to remove a zero check after the next below-raft migration.

`RaftExpectedFirstIndex` used to be zero before f9dee66 which started setting this field after a `LooselyCoupledRaftLogTruncation` version gate. Since then, the version gate has been removed, and the field is set unconditionally.

But we still need to have done at least one below-raft migration to safely say that this field can't be zero.

Related to #136109

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
But we can't rule out that there are still raft log entries around that have the zero, right? In contrived scenarios, these could pop up for application after an upgrade to the release that contains this PR. Don't we - at least technically - need a below-raft migration here?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136536#-:-ODAVYjqAfR_qXKtIGfl:b1pvyp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by pav-kv — COMMENTED** [review]
Good point, yeah, I'll remove this part of the PR. Unless we've had any below-raft migrations after Feb 2022. We don't need a fully-fledged migration, just the wait/sync all state machines aspect of it. Any other below-raft migration would give us this for free.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136536#-:-ODB24TW6tWC36HCzHCA:b-db1uex)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by pav-kv** [comment]
The last below-raft migration #75675 was a bit earlier than that change #76215. So yeah, it's slightly unsafe. Will add it to the list of things waiting for the next migration.

**Review by tbg — APPROVED** [review]

**Comment by pav-kv** [comment]
TFTR!

bors r=tbg

**Comment by pav-kv** [comment]
The CI failure in bors is unrelated: #136548.

**Comment by pav-kv** [comment]
bors retry

**Comment by pav-kv** [comment]
bors cancel

**Comment by pav-kv** [comment]
CI should be fixed by #136583. Retrying to enter the queue after it.

**Pull request merged**
