### PR TITLE
admin: Add "Liveness" endpoint to Admin API

### PR DESCRIPTION
**Pull request by mrtracy**
Add /liveness endpoint to admin API, which returns the liveness status of the
cluster as known to the queried node. This information is a copy of the node's
in-memory Liveness collection.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13699)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/serverpb/admin.proto, line 368 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0gbBJDpQEEZhDZ5W:-Kda0gbBJDpQEEZhDZ5X:bdkvsbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/serverpb/admin.proto#L368)):*
> ```protobuf
> // by Node ID.
> message LivenessResponse {
>   map<int32, cockroach.storage.Liveness> liveness_map = 1 [(gogoproto.nullable) = false];
> ```

`Liveness` contains the `NodeID`. Do you need this to be a map? Could it be `repeated cockroach.Storage.Liveness nodes`?

---

*[pkg/storage/node_liveness.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0NWJDF-sMvNESgXs:-Kda0NWJDF-sMvNESgXt:b-hxqwvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness.go#L383)):*
> ```Go
> 
> // GetLivenessMap returns a map from NodeID to a full Liveness status.
> func (nl *NodeLiveness) GetLivenessMap() map[int32]Liveness {
> ```

The comment doesn't match the implementation. You should use `map[roachpb.NodeID]` here even if you have to make another copy of the map for the RPC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/server/admin.go, line 880 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaSqFKGHMSr67WDR4I:-KdaSqFKGHMSr67WDR4J:brvnu9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin.go#L880)):*
> ```Go
> 
> func (s *adminServer) Liveness(
> 	ctx context.Context, req *serverpb.LivenessRequest,
> ```

`func (s *adminServer) Liveness(context.Context, *serverpb.LivenessRequest)` (i.e. both arguments can be unnamed)

---

*[pkg/server/admin_cluster_test.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaT6K9VO4R33R7u3mP:-KdaT6K9VO4R33R7u3mQ:b16w99y) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L37)):*
> ```Go
> 	// adminPrefix is the prefix for RESTful endpoints used to provide an
> 	// administrative interface to the cockroach cluster.
> 	adminPrefix = "/_admin/v1/"
> ```

this constant is used in exactly one place (and we have many places where we simply inline it). I think i'd prefer to inline it here, as well.

---

*[pkg/server/admin_cluster_test.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaU6Y08c7CGB-Ms0n9:-KdaU6Y08c7CGB-Ms0nA:b5hdz8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L158)):*
> ```Go
> 	startTime := tc.Server(0).Clock().PhysicalNow()
> 
> 	// We need to retry because the node ID isn't set until after
> ```

is that why? i thought the reason would be the time it takes for all the nodes to gossip their liveness.

---

*[pkg/server/admin_cluster_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaTTuXeQv5IYq6Ed3r:-KdaTTuYujnOmGfRAT9t:b-9xxr8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L166)):*
> ```Go
> 		}
> 		if a, e := len(resp.LivenessMap), tc.NumServers(); a != e {
> 			return errors.Errorf("found %d liveness records, got %d", a, e)
> ```

this error message is nonsensical

---

*[pkg/server/serverpb/admin.proto, line 368 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0gbBJDpQEEZhDZ5W:-KdaTa-BppIbUGTqM3mR:bvgpr7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/serverpb/admin.proto#L368)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`Liveness` contains the `NodeID`. Do you need this to be a map? Could it be `repeated cockroach.Storage.Liveness nodes`?
</blockquote></details>

if not, the key should be a customtype.

---

*[pkg/storage/node_liveness.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0NWJDF-sMvNESgXs:-KdaTtO7_9tc6Jncq0IL:ba0lojw) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness.go#L383)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The comment doesn't match the implementation. You should use `map[roachpb.NodeID]` here even if you have to make another copy of the map for the RPC.
</blockquote></details>

As stated in another comment, you can use `customtype` to make the proto field the correct type (and avoid int32 entirely).

---

*[pkg/storage/node_liveness_test.go, line 457 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaUVPjM4KJ0dgtKMl1:-KdaUVPjM4KJ0dgtKMl2:b-ybd6j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness_test.go#L457)):*
> ```Go
> 	for nid, l := range lMap {
> 		if int32(l.NodeID) != nid {
> 			t.Errorf("Liveness record node ID %d did not match key in collection %d", l.NodeID, nid)
> ```

i'm sure this is copied from elsewhere, but we don't capitalize error messages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by mrtracy** [comment]
Review status: 1 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/server/admin.go, line 880 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaSqFKGHMSr67WDR4I:-Kdb_S8mTGgamM_-eN4O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin.go#L880)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`func (s *adminServer) Liveness(context.Context, *serverpb.LivenessRequest)` (i.e. both arguments can be unnamed)
</blockquote></details>

Done.

---

*[pkg/server/admin_cluster_test.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaT6K9VO4R33R7u3mP:-Kdb_FrV4DRCPE2v4Xi_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L37)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this constant is used in exactly one place (and we have many places where we simply inline it). I think i'd prefer to inline it here, as well.
</blockquote></details>

Done.

---

*[pkg/server/admin_cluster_test.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaU6Y08c7CGB-Ms0n9:-Kdb_P739hY_4AUfgHSf:b-jixlss) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L158)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is that why? i thought the reason would be the time it takes for all the nodes to gossip their liveness.
</blockquote></details>

I believe you are correct, updated the message.

---

*[pkg/server/admin_cluster_test.go, line 166 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaTTuXeQv5IYq6Ed3r:-KdbZxE0KBP-nUBBrTYN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/admin_cluster_test.go#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this error message is nonsensical
</blockquote></details>

Done.

---

*[pkg/server/serverpb/admin.proto, line 368 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0gbBJDpQEEZhDZ5W:-KdbZd8vqGEzsZhSuKvt:bkd3axg) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/server/serverpb/admin.proto#L368)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

if not, the key should be a customtype.
</blockquote></details>

After consideration, I switched it to a repeated field. The map is more convenient in some cases, but we can reconstruct the map on the caller side using the NodeIDs; there are also some cases where the map would not be helpful, such as searching the collection for Live/Not Live nodes.

---

*[pkg/storage/node_liveness.go, line 383 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kda0NWJDF-sMvNESgXs:-KdbgT3AJ3daLHHKhZ5l:b-tqcsai) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness.go#L383)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

As stated in another comment, you can use `customtype` to make the proto field the correct type (and avoid int32 entirely).
</blockquote></details>

Switched to returning a slice.

---

*[pkg/storage/node_liveness_test.go, line 457 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaUVPjM4KJ0dgtKMl1:-KdbGThA4TisLB7MZDbZ:b3dlqv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness_test.go#L457)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i'm sure this is copied from elsewhere, but we don't capitalize error messages
</blockquote></details>

It's not copied, "Liveness" is an exported class that is being referenced here; in a way, that seems like a proper noun.  I'll go ahead an de-capitalize, because it works either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness.go, line 387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kdbi-veOM3uVQ8gmesx:-Kdbi-veOM3uVQ8gmesy:b9b60f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/876d14c5f44b95e26e07ba312c87102afa51d7d7/pkg/storage/node_liveness.go#L387)):*
> ```Go
> 	nl.mu.Lock()
> 	defer nl.mu.Unlock()
> 	livenesses := make([]Liveness, 0, len(nl.mu.nodes)+1)
> ```

what's going on here? you allocate space for an extra entry, but then only add `nl.mu.self` if that entry is in `ln.mu.nodes`. something doesn't add up.

---

*[pkg/storage/node_liveness_test.go, line 457 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdaUVPjM4KJ0dgtKMl1:-KdbiHKqGT7e2GO_5m_I:b-z5t6qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/100808676721de615d50f8b90fe600c74b1585ca/pkg/storage/node_liveness_test.go#L457)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

It's not copied, "Liveness" is an exported class that is being referenced here; in a way, that seems like a proper noun.  I'll go ahead an de-capitalize, because it works either way.
</blockquote></details>

Ah, I didn't realize you intended to use it as a proper noun because of the context; i.e. "Liveness record" doesn't look like a proper noun. Anyway, looks fine now, thanks for changing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by mrtracy** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/node_liveness.go, line 387 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-Kdbi-veOM3uVQ8gmesx:-KdbnPEecoXS8iV8LZFV:brorhk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/876d14c5f44b95e26e07ba312c87102afa51d7d7/pkg/storage/node_liveness.go#L387)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what's going on here? you allocate space for an extra entry, but then only add `nl.mu.self` if that entry is in `ln.mu.nodes`. something doesn't add up.
</blockquote></details>

Good catch.

I had initially misunderstood the equivalent logic from `GetIsLiveMap()`; I thought that the node's own liveness was stored exclusively in `nl.mu.self`, and that `nl.nodes` only contained information about other nodes. However, it turned out that there is also a liveness record for the current node in `nl.nodes` pulled from gossip callbacks; however, `nl.mu.self` is always more current, so it supercedes the value from `nl.nodes` when building these informational structures.

My initial pass failed tests (3 node cluster, got 4 nodes in this collection); I figured out the problem and went back and modified this method accordingly, but forgot to adjust this line.

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdbpuVoSufvfS7C8gH2:-KdbpuVp5TMkSETT0R99:b-w4ym94) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f0fc39ec74d1a4507081e123b2bb5dd8e83164/pkg/storage/node_liveness.go#L373)):*
> ```Go
> 	now := nl.clock.Now()
> 	maxOffset := nl.clock.MaxOffset()
> 	for nID, l := range nl.mu.nodes {
> ```

can you help me understand why this is not exactly the same as the logic in `GetLivenesses`? This one checks for `nl.mu.self.NodeID != 0`, but it seems like it could do exactly the same check as you do below:

```
for _, l := range nl.mu.nodes {
  if l.NodeID == ln.mu.self.NodeID {
    lMap[l.NodeID] = nl.mu.self.isLive(now, maxOffset)
  } else {
    lMap[l.NodeID] = l.isLive(now, maxOffset)
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by bdarnell** [comment]
:lgtm: 

---

Reviewed 1 of 12 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-:-Kdc9eX1rcx88lvaDPNU:bg7igkv)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-:-KdfA10x1IPxsFk6JoiA:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdbpuVoSufvfS7C8gH2:-KdgG-fgsG5bbsjGh4Gx:bw73t8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f0fc39ec74d1a4507081e123b2bb5dd8e83164/pkg/storage/node_liveness.go#L373)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you help me understand why this is not exactly the same as the logic in `GetLivenesses`? This one checks for `nl.mu.self.NodeID != 0`, but it seems like it could do exactly the same check as you do below:

```
for _, l := range nl.mu.nodes {
  if l.NodeID == ln.mu.self.NodeID {
    lMap[l.NodeID] = nl.mu.self.isLive(now, maxOffset)
  } else {
    lMap[l.NodeID] = l.isLive(now, maxOffset)
  }
}
```
</blockquote></details>

It could, but this also works. The version in GetIsLiveMap() works because it is constructing a map, so the '!= 0' version overwrites the own-node liveness from the loop. That doesn't work in GetLivenesses() because it is returning a slice.

Naively, you might even expect the version in GetIsLiveMap() to be more performant as the number of nodes increases, since you would have far fewer branch statements. However,  I suppose the cost of an additional map lookup might outweigh that depending on implementation.

Either way, this code already works and I did not feel the need to change it; I only used a different version in GetLivenesses() because I was constructing a different data structure, and this method doesn't work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdbpuVoSufvfS7C8gH2:-KdgHqGd58rDMkfxTody:b-9agwfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f0fc39ec74d1a4507081e123b2bb5dd8e83164/pkg/storage/node_liveness.go#L373)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

It could, but this also works. The version in GetIsLiveMap() works because it is constructing a map, so the '!= 0' version overwrites the own-node liveness from the loop. That doesn't work in GetLivenesses() because it is returning a slice.

Naively, you might even expect the version in GetIsLiveMap() to be more performant as the number of nodes increases, since you would have far fewer branch statements. However,  I suppose the cost of an additional map lookup might outweigh that depending on implementation.

Either way, this code already works and I did not feel the need to change it; I only used a different version in GetLivenesses() because I was constructing a different data structure, and this method doesn't work.
</blockquote></details>

This subtle difference is bizarre enough that I would change it for no reason other than to reduce the cognitive overhead of these two functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-:-KdgIBHxsNwaSHVvg4SA:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: 8 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/node_liveness.go, line 373 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699#-KdbpuVoSufvfS7C8gH2:-KdgJ3U1edqD-ofZgQOP:bm5oq4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f0fc39ec74d1a4507081e123b2bb5dd8e83164/pkg/storage/node_liveness.go#L373)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This subtle difference is bizarre enough that I would change it for no reason other than to reduce the cognitive overhead of these two functions.
</blockquote></details>

Needed another round trip anyway, so done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13699)*

**Pull request merged**
