### PR TITLE
sql: various USER statement improvements

### LINKED ISSUE #19011: sql: dropping user doesn't remove user's grants
```
~/src/github.com/cockroachdb/cockroach$ cockroach version
Build Tag:    v1.1-beta.20170928-19-gf5f0d0a45
Build Time:   2017/10/02 13:45:19
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.9
C Compiler:   4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
Build SHA-1:  f5f0d0a45695c9836c84bc3d63fc62ecbe0eaa73
Build Type:   development
```

If you have a user who has privileges on databases/tables, dropping that user removes the user but not the user's privileges. Not sure if this is really a problem, but it seems strange to me.

Example:

```
root@:26257/> create user jseldess;
CREATE USER

Time: 4.743393ms

root@:26257/> GRANT ALL ON test.orders TO jseldess;
GRANT

Time: 12.424305ms

root@:26257/> drop user jseldess;
DROP USER 1

Time: 4.86353ms

root@:26257/> show grants on test.orders;
+--------+----------+------------+
| Table  |   User   | Privileges |
+--------+----------+------------+
| orders | jseldess | ALL        |
| orders | root     | ALL        |
+--------+----------+------------+
(2 rows)

Time: 2.409006ms

root@:26257/> show users;
+----------+
| username |
+----------+
+----------+
(0 rows)

Time: 5.892734ms
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #19011.

As follows:

- DROP USER will error out if there are grants remaining. The error message will spell out where the remaining grants are.
- SHOW GRANTS now works without the `ON` clause, i.e. it will look everywhere for possible grants. So one can use `SHOW GRANTS FOR <user>` to see where the remaining grants are.

Also incidentally this introduces a new statement ALTER USER ... WITH PASSWORD .. to change a user's password from SQL.

cc @jseldess @mberhault @bdarnell

### CODE REVIEW

**Comment by knz** [comment]
cc @benesch for how to use the placeholder magic. see 2nd and 3rd commit.

**Comment by knz** [comment]
?

**Comment by dt** [comment]
Whoops, sorry, missed this. looking now, though you might also want @asubiotto for the password stuff.

---

Reviewed 8 of 8 files at r1, 10 of 10 files at r2, 9 of 9 files at r3, 1 of 1 files at r4.
Review status: 4 of 38 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-KwGdtIdtjjO6Cj0XI_B:b-bpoalv)*

**Comment by asubiotto** [comment]
The `alter user` logic looks good to me. However, why are we supporting the statement `ALTER USER ... IDENTIFIED BY ...` rather than `ALTER USER ... WITH PASSWORD ...`?

---

Review status: 4 of 38 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-Kw_ffo4RC1LuMA6gbMC:bsurdb)*

**Comment by knz** [comment]
I actually didn't know that pg supported this syntax. I have discovered "identified by" from the mysql/oracle docs. Will use the pg one instead.

---

Review status: 4 of 38 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-Kw_gW6FDXkYMK1r-9aY:bl5d64g)*

**Comment by knz** [comment]
Updated to use WITH PASSWORD like pg/

**Comment by asubiotto** [comment]
Nice, just some minor cosmetic stuff.

---

Reviewed 13 of 17 files at r5, 11 of 16 files at r10.
Review status: 11 of 37 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create.go, line 347 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-Kwee72Y1evDtWzNmi_e:-Kwee72Y1evDtWzNmi_f:b-pcwi22) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/create.go#L347)):*
> ```Go
> 
> // alterUserSetPasswordNode represents an ALTER USER ... WITH PASSWORD statement.
> type alterUserSetPasswordNode struct {
> ```

Consider renaming all the `alterUserSetPassword...` instances to `alterUserWithPassword...` to mirror the statement.

---

*[pkg/sql/parser/create.go, line 709 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KweefddaHLuSMLHV-NJ:-KweefddaHLuSMLHV-NK:b-ap6lv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/create.go#L709)):*
> ```Go
> }
> 
> // AlterUserSetPassword represents an ALTER USER WITH PASSWORD statement.
> ```

Minor nit: `ALTER USER WITH PASSWORD` vs `ALTER USER ... WITH PASSWORD` in `pkg/sql/create.go`. Doesn't matter much but consider keeping these consistent across files.

---

*[pkg/sql/parser/sql.y, line 998 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KwedaI8IX5uC6KwLsyE:-KwedaI8IX5uC6KwLsyF:b-9vd9r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/sql.y#L998)):*
> ```Yacc
> // %Category: Priv
> // %Text:
> // ALTER USER [IF EXISTS] <name> IDENTIFY BY <password>
> ```

Change to `WITH PASSWORD`.

---

*[pkg/sql/parser/sql.y, line 3051 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KwedqXvyCSQOee_tCha:-KwedqXvyCSQOee_tChb:b6worzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/sql.y#L3051)):*
> ```Yacc
> 
> // As in MySQL.
> // https://dev.mysql.com/doc/refman/5.7/en/alter-user.html
> ```

Change this to refer to postgres.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-Kweez3QzHe6lY9_XaNa:bhj4f4i)*

**Comment by knz** [comment]
Review status: 11 of 37 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/create.go, line 347 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-Kwee72Y1evDtWzNmi_e:-Kwiwm1wxubXsmJal5mU:bnn7jmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/create.go#L347)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Consider renaming all the `alterUserSetPassword...` instances to `alterUserWithPassword...` to mirror the statement.
</blockquote></details>

I don't really feel comfortable with using "with" here. I like my nodes to use a verb that says what is being done. The word "with" doesn't say what is being done.

---

*[pkg/sql/parser/create.go, line 709 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KweefddaHLuSMLHV-NJ:-Kwiwk9xbedpC_9hvJTE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/create.go#L709)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Minor nit: `ALTER USER WITH PASSWORD` vs `ALTER USER ... WITH PASSWORD` in `pkg/sql/create.go`. Doesn't matter much but consider keeping these consistent across files.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 998 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KwedaI8IX5uC6KwLsyE:-Kwiw_qCn22UTPxQ57Dt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/sql.y#L998)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Change to `WITH PASSWORD`.
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 3051 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-KwedqXvyCSQOee_tCha:-KwiwU63nN6VYIDa2vKs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/parser/sql.y#L3051)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Change this to refer to postgres.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095)*

**Comment by jordanlewis** [comment]
:lgtm: wow what a comprehensive overhaul.

I have a small reservation about `SHOW GRANTS` that I'm happy to debate after this PR merges. Are there permissions implications to letting all users see the names of all databases and tables, as well as the grants of all other users on tables and databases?

---

Reviewed 1 of 8 files at r1, 36 of 36 files at r16, 1 of 10 files at r17, 4 of 9 files at r18, 16 of 16 files at r20, 4 of 4 files at r21.
Review status: 21 of 37 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 347 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-Kwee72Y1evDtWzNmi_e:-KxsmJyObOT0r0Fvwkez:b-s7m6mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ef8e12fbb2479bf04f1b45254a46cb48aa2189/pkg/sql/create.go#L347)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't really feel comfortable with using "with" here. I like my nodes to use a verb that says what is being done. The word "with" doesn't say what is being done.
</blockquote></details>

I agree that it'd be better to have this node be `alterUserWithPasswordNode` because it corresponds directly to the syntax that creates the node, but I hear your objection.

---

*[pkg/sql/create.go, line 401 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-Kxsmp6Hi9vTm0CkVPAJ:-Kxsmp6I5K3WFoMeNMxX:burfvzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8019c4f0d4e21762d1085af6622332a4ad658bb1/pkg/sql/create.go#L401)):*
> ```Go
> 
> 	var hashedPassword []byte
> 	if n.password != nil {
> ```

This code seems suspiciously similar to its analogue in `CREATE USER`. Is there a way it can be shared? I see there are some subtle differences so maybe this is fine, just calling it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-Kxsr9rA2JIXmE1bnxnw:b-44xr63)*

**Comment by knz** [comment]
`SHOW GRANTS` is restricted by permissions in the same way that `information_schema.schema_privileges` is (it uses the same mechanism): root can see everything, a non-root user can only see those tables/databases they have some permissions to.

---

Review status: 21 of 37 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 401 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-Kxsmp6Hi9vTm0CkVPAJ:-Kxy2R0rwypbSBRmY8Uv:b-ebm9au) ([raw file](https://github.com/cockroachdb/cockroach/blob/8019c4f0d4e21762d1085af6622332a4ad658bb1/pkg/sql/create.go#L401)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This code seems suspiciously similar to its analogue in `CREATE USER`. Is there a way it can be shared? I see there are some subtle differences so maybe this is fine, just calling it out.
</blockquote></details>

Done (separate commit).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19095#-:-Kxy3b8R6MDZmO8ilcjL:bgmnw06)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
