### PR TITLE
sql: add times series metrics for disk spilling

### LINKED ISSUE #61363: sql: add time series metrics for disk spilling
We currently lack some metrics for disk spilling. Add the following metrics:

1. A counter that tracks the number of times queries have spilled to disk
2. A counter that tracks the number of bytes written to temporary disk storage as a result of spilling
3. A counter that tracks the number of bytes read from temporary disk storage as a result of spilling

### PR DESCRIPTION
**Pull request by barryhe2000**
Add time series metrics for disk spilling to track
queries spilled to disk, bytes written, and bytes
read.

Fixes: #61363

Release note (ui change): User can see time series metrics
for disk spilling in advanced debug console

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for getting this out! I have one comment that should simplify things a bit.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-:-MWWsYCACMsG8o1vCErf:b7xttgk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @barryhe2000)

___
*[pkg/sql/colcontainer/diskqueue.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWWqGSN2m3cjtLCiKo8:-MWWqGSO68a0k7fWqlEs:b-589zkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1455bd7d01b771ccdf892c5cf72363d430e0ad83/pkg/sql/colcontainer/diskqueue.go#L298)):*
> ```Go
> 
> // DiskSpillingMetrics keeps track of various disk spilling metrics.
> type DiskSpillingMetrics interface {
> ```

I know that I was the one that mentioned having an exported interface in the first place, but now that I look at the code it seems unnecessary. I imagined that we want to have an interface because we would use it for two of our execution engines, but now I think that adding these metrics only in the vectorized engine (which is what this PR does) is sufficient. cc @jordanlewis in case you think otherwise

So assuming that we are satisfied with metrics being updated only for the vectorized engine, I'd remove the exported interface entirely and, instead, would just have a helper struct - I'd rename `diskSpillingMetricImpl` to something like `diskSpillingMetricsHelper` that lives in the `diskQueue` itself. `diskQueueCfg` would have `*execinfra.DistSQLMetrics` that will be used to initialize the helper in `newDiskQueue`.

Note that `BytesWritten` and `BytesRead` methods of the interface then aren't needed since we can just inline them directly in their callsites.

**Review by barryhe2000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWWqGSN2m3cjtLCiKo8:-MW_m3o2AyD_2hPXo9eN:b-za1xhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1455bd7d01b771ccdf892c5cf72363d430e0ad83/pkg/sql/colcontainer/diskqueue.go#L298)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I know that I was the one that mentioned having an exported interface in the first place, but now that I look at the code it seems unnecessary. I imagined that we want to have an interface because we would use it for two of our execution engines, but now I think that adding these metrics only in the vectorized engine (which is what this PR does) is sufficient. cc @jordanlewis in case you think otherwise

So assuming that we are satisfied with metrics being updated only for the vectorized engine, I'd remove the exported interface entirely and, instead, would just have a helper struct - I'd rename `diskSpillingMetricImpl` to something like `diskSpillingMetricsHelper` that lives in the `diskQueue` itself. `diskQueueCfg` would have `*execinfra.DistSQLMetrics` that will be used to initialize the helper in `newDiskQueue`.

Note that `BytesWritten` and `BytesRead` methods of the interface then aren't needed since we can just inline them directly in their callsites.
</blockquote></details>

RFAL! Let me know what you think of the refactoring.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-:-MWb-ymF7B7fA-BsNAh7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @barryhe2000 and @jordanlewis)

___
*[pkg/sql/colcontainer/diskqueue.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWWqGSN2m3cjtLCiKo8:-MWb-FYK6_HHUW7UEEor:b4f5zhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1455bd7d01b771ccdf892c5cf72363d430e0ad83/pkg/sql/colcontainer/diskqueue.go#L298)):*
<details><summary><i>Previously, barryhe2000 (Barry He) wrote…</i></summary><blockquote>

RFAL! Let me know what you think of the refactoring.
</blockquote></details>

Thanks, this looks very good!
___
*[pkg/sql/colcontainer/diskqueue.go, line 379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWazYq508JI4Rxin7cJ:-MWazYq508JI4Rxin7cK:b-g6ijg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6c28ff5da1e981051df84ca312fc3d76496ab/pkg/sql/colcontainer/diskqueue.go#L379)):*
> ```Go
> }
> 
> func (d *diskQueue) querySpilled(cfg DiskQueueCfg) {
> ```

nit: no need to take in `cfg` as an argument since `diskQueue` already stores it.
___
*[pkg/sql/colcontainer/diskqueue.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWb-PPF1PWftzpccPoG:-MWb-PPF1PWftzpccPoH:b-hcnbcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6c28ff5da1e981051df84ca312fc3d76496ab/pkg/sql/colcontainer/diskqueue.go#L410)):*
> ```Go
> 		return nil, err
> 	}
> 	if cfg.DistSQLMetrics != nil {
> ```

super nit: personally, I would have moved `if` check into `querySpilled` method since to me it would read nicer. My reasoning is that unlike in a couple cases below where we use `d.cfg.DistSQLMetrics` directly, here we call a function, and it's not as clear why we're checking one seemingly unrelated object for "non-nil"ness. But feel free to ignore this comment if you prefer the current way.

**Review by barryhe2000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62467)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 379 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWazYq508JI4Rxin7cJ:-MWbFtk-AI1L7lBg7bPp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6c28ff5da1e981051df84ca312fc3d76496ab/pkg/sql/colcontainer/diskqueue.go#L379)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: no need to take in `cfg` as an argument since `diskQueue` already stores it.
</blockquote></details>

Done.
___
*[pkg/sql/colcontainer/diskqueue.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62467#-MWb-PPF1PWftzpccPoG:-MWbFvvDCIb1oEtIKbQX:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6c28ff5da1e981051df84ca312fc3d76496ab/pkg/sql/colcontainer/diskqueue.go#L410)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: personally, I would have moved `if` check into `querySpilled` method since to me it would read nicer. My reasoning is that unlike in a couple cases below where we use `d.cfg.DistSQLMetrics` directly, here we call a function, and it's not as clear why we're checking one seemingly unrelated object for "non-nil"ness. But feel free to ignore this comment if you prefer the current way.
</blockquote></details>

Makes sense, done.

**Comment by barryhe2000** [comment]
TFTR!
bors r+

**Comment by barryhe2000** [comment]
Flake.

bors r+

**Comment by yuzefovich** [comment]
@cockroachdb/sql-observability thoughts about backporting this?

**Comment by jordanlewis** [comment]
blathers backport 21.1

**Pull request merged**
