### PR TITLE
acceptance: disable test_sql_mem_monitor

### PR DESCRIPTION
**Pull request by jordanlewis**
It's causing broken agents due to the large join that causes DistSQL to
spill to disk, which creates files as root because of Docker. Disable
for the time being.

cc @BramGruneir @a-robinson

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/acceptance/cli_test.go, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17793#-Ks5ynaTQ3RQd4CznhGM:-Ks5ynaTQ3RQd4CznhGN:ba5e0du) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8d3e842d6cb0b3c257d4fcfda428190fdc0f8f/pkg/acceptance/cli_test.go#L64)):*
> ```Go
> 		testFile := filepath.Base(p)
> 		testPath := filepath.Join(containerPath, testFile)
> 		if strings.Contains(testPath, "disabled") {
> ```

how about hassuffix instead of contains?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17793#-:-Ks5yz54RBPomWxgxWI8:bnfp4nl)*

**Comment by tschottdorf** [comment]
Can we merge this ASAP please? I think most the agents are bricked.

**Review by tbg — APPROVED** [review]

**Comment by tschottdorf** [comment]
God-merge ahoy. Only one previously flaky race test failed.

**Comment by knz** [comment]
Please create a followup issue to address the problem durably.

- Either the docker run thing should change the UID of the cockroach process (to eliminate the root cause)

- Or the test should be run outside of Docker

**Pull request merged**
