### PR TITLE
colexec: fix binary operators with const datum on the left

### LINKED ISSUE #50261: roachtest: no volatility for cast sqlsmith/setup=tpcc/setting=no-mutations failed
[(roachtest).sqlsmith/setup=tpcc/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2013639&tab=buildLog) on [master@9eea0be192499fa7d29b5eca5ed14173982b25f0](https://github.com/cockroachdb/cockroach/commits/9eea0be192499fa7d29b5eca5ed14173982b25f0):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=tpcc/setting=no-mutations/run_1
	sqlsmith.go:169,sqlsmith.go:199,test_runner.go:753: error: pq: internal error: no volatility for cast unknown::tuple{oid[], int, int, int[]}
		stmt:
		WITH
			with_68 (col_350, col_351)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(
									(ARRAY[3326584685:::OID,80433409:::OID,820018757:::OID], (-938321928942505224):::INT8, (-7580):::INT8, ARRAY[8950:::INT8,18770:::INT8]),
									EXISTS(
										SELECT NULL AS col_343 FROM defaultdb.public.warehouse@[0] AS tab_183 LIMIT 57:::INT8
									)
								),
								(
									(
										SELECT
											NULL AS col_344
										FROM
											defaultdb.public.warehouse@primary AS tab_184
										ORDER BY
											tab_184.w_id ASC, tab_184.w_zip
										LIMIT
											1:::INT8
									),
									not_ilike_escape(jsonb_typeof('false':::JSONB::JSONB)::STRING::STRING, e'?\x1aDKy\r\x16\f':::STRING::STRING, e'1Hc\x13$5Yj':::STRING::STRING)::BOOL
								),
								(
									(ARRAY[2929277516:::OID,1298950565:::OID,3862054642:::OID,4199588206:::OID,0:::OID,921931389:::OID], 2156249725798318035:::INT8, (-22696):::INT8, ARRAY[(-128):::INT8,127:::INT8,(-18278):::INT8,7433:::INT8,(-1):::INT8,(-13908):::INT8,(-22434):::INT8]),
									(false AND (EXISTS (WITH with_66 (col_345) AS (SELECT * FROM (VALUES (NULL), (0.4354933111764593:::FLOAT8), ((-1.4090297597753398):::FLOAT8)) AS tab_185 (col_345)), with_67 (col_346, col_347, col_348) AS (SELECT * FROM (VALUES (e'\x14\x078<=':::STRING, '\xd013479c':::BYTES, 722184144:::OID)) AS tab_186 (col_346, col_347, col_348)) SELECT cte_ref_22.col_348 AS col_349 FROM with_67 AS cte_ref_22 WHERE true) AND true))
								)
						)
							AS tab_187 (col_350, col_351)
				)
		SELECT
			cte_ref_23.col_350 AS col_352, cte_ref_23.col_351 AS col_353
		FROM
			with_68 AS cte_ref_23
		ORDER BY
			cte_ref_23.col_351 DESC,
			cte_ref_23.col_351 ASC,
			cte_ref_23.col_350 DESC,
			cte_ref_23.col_350,
			cte_ref_23.col_351 ASC,
			cte_ref_23.col_350 ASC;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=tpcc/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2013639&tab=artifacts#/sqlsmith/setup=tpcc/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dtpcc%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: clean up output types of binary operations on datum vecs**

Previously, for Plus, Minus, Mult, and Div binary operations we would
register an output type for datum-backed vector and all compatible types
on the right. This results in generating some dead code (for example,
datum-backed vector * boolean). This commit cleans up it by registering
the output types only for "real" type pairs. Note that we don't need to
do update the map of "compatible" type families since that is used to
register type customizers, and not declaring an output type for
a particular family-width pair is sufficient to stop the code generation
on that pair.

Release note: None

**colexec: fix binary operators with const datum on the left**

We have a hard-coded assumption that the left element of a binary or
comparison operation with datum-backed vector on the left is
`*coldataext.Datum`. However, this hasn't been the case previously when
we have a constant datum on the left. This commit fixes the issue by
performing a necessary conversion during the operator's creation time.

Additionally, it changes the way we propagate the eval context to
a binary operation - previously, we would use `datumVec` to do that, now
we use `overloadHelper`. The reason is that there is a scenario in which
there is no datum vector in the scope (namely, when we have a const
datum-backed value on the left and non-constant non-datum vector on the
right).

Fixes: #50261.

Release note: None (no stable release with this bug).

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50608#-:-MAfyQ5A-euXGQG3qTlp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I'll wait for #50636 to go in.

**Comment by jordanlewis** [comment]
You can merge this first if you like, apparently still some kinks in the other PR.

**Comment by yuzefovich** [comment]
Alright.

bors r+

**Pull request merged**
