### PR TITLE
publish-artifacts: build and upload workload binaries

### PR DESCRIPTION
**Pull request by benesch**
As promised!

Binaries will be uploaded to https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST, where LATEST can be replaced with a recent SHA from master.

### CODE REVIEW

**Comment by danhhz** [comment]
Amazing! Does it build a binary for each platform?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24072#-:-L83K4UOoNW4tBS6FQTs:b-ekpeab)*

**Comment by benesch** [comment]
> Does it build a binary for each platform?

Nope, just Linux. Do you need a macOS binary?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24072#-:-L83ObFhjmabkr7BUZf1:b-3omxp7)*

**Comment by danhhz** [comment]
> Nope, just Linux. Do you need a macOS binary?

I think @jseldess did because he wanted to start using this in docs.

**Comment by benesch** [comment]
That'll require some work as the Makefile isn't equipped to cross compile anything but Cockroach. Are you okay with shipping this as-is for now?

**Comment by danhhz** [comment]
Is the the url going to change if/when we do that?

**Comment by benesch** [comment]
Yeah. But `crl-stage-binaries` can abstract that away.

**Comment by danhhz** [comment]
And docs would have to be updated

**Comment by jseldess** [comment]
Yeah, @benesch, @danhhz, I'll probably wait to feature these in docs until we have pre-built binaries for OSX and Windows as well. When do you think that might happen?

**Comment by benesch** [comment]
Hmm, we're not well-equipped to officially support binaries besides
cockroach. I put together this PR to support `crl-stage-binaries` (and
hopefully soon a `roachprod stage`). There's at least another afternoon of
work to make the binary fit for public consumption.

For example, do we want to package workload up into a tarball, like we do
for cockroach? Otherwise users will need to manually run `chmod +x` on what
they download. Do we want actual releases of workload, rather than just
linking to the latest master? Otherwise the docs will get stale quite
quickly.

What is it that we're planning to document? How to use the workload tool to
run load against a Cockroach cluster? I'm starting to think we might want
to just bake workload into cockroach itself. It would sure solve the
distribution problem.

**Comment by jseldess** [comment]
@benesch, we already feature some of our load gens in docs tutorials, so we'd be able to simplify that process (no need for go, etc.). But I think we'd use these more widely in our docs if it were easy for users. We might want to document the behaviors and use cases for each load gen as well. 

I really like the idea of baking them into cockroach itself. But if that's not possible, we could find a way for docs to stay aware of changes to the workload binary.

**Comment by benesch** [comment]
@danhhz, do you have thoughts on bundling workloads into Cockroach?

**Comment by bdarnell** [comment]
I think I'm OK with adding (some of the) load generators to the main cockroach binary for docs/example purposes (it makes at least as much sense as an example database of star trek quotes), although we wouldn't be able to ship this until 2.1. Some of the workloads are more complicated than others, though (tpcc needs to import a large data set - would we provide public hosting for that or just give people instructions to regenerate it?), and the simple ones (like ycsb) aren't necessarily the ones we want to encourage.

**Comment by danhhz** [comment]
Since adding some generators to the cockroach binary will address the docs use case and this solves real problems in the meantime, I think we should merge it. :lgtm: and thanks!

**Comment by benesch** [comment]
Thanks!

**Pull request merged**
