### PR TITLE
sql: set locality to GLOBAL for materialized views

### PR DESCRIPTION
**Pull request by otan**
Only last two commits matter.
See individual commits for details.

Refs: #61382

### CODE REVIEW

**Comment by awoods187** [comment]
Nice speedy work!

**Review by ajstorm — APPROVED** [review]
> Reviewed 13 of 13 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62122)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @otan)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0CFYqB8tWdzEGIBWW:-MW0CFYrDGT_YgX9Wt6N:bxy7rcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe2b8ea5c161606e5fe4a7ed1b8225d8e3cb450/pkg/sql/catalog/tabledesc/validate.go#L1253)):*
> ```Go
> 	// Check non-table items have a correctly set locality.
> 	if desc.IsSequence() {
> 		if !desc.IsLocalityRegionalByTable() {
> ```

Nit: Does it make sense here to create IsDefaultLocalitySequence and tree.DefaultLocalitySequence, so that we only have to change this in one place down the road?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62122)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @otan)

___
*[pkg/sql/create_sequence.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0EJ2MDGTziNxfU2OU:-MW0EJ2MDGTziNxfU2OV:b-i55xwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L91)):*
> ```Go
> func doCreateSequence(
> 	params runParams,
> 	context string,
> ```

mind removing this context? Looks greyed out
___
*[pkg/sql/create_sequence.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0EXMz7sjfsNrle5dn:-MW0EXMz7sjfsNrle5do:b-b63cba) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L98)):*
> ```Go
> 	opts tree.SequenceOptions,
> 	jobDesc string,
> 	isMultiRegion bool,
> ```

nit: you can get rid of this param and construct `isMultiRegion` in this function as opposed to funnelling it through to here. 
___
*[pkg/sql/create_table.go, line 2419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0DBMjAuxwi4Vu7XhO:-MW0DBMjAuxwi4Vu7XhP:bbjadld) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_table.go#L2419)):*
> ```Go
> 	}
> 
> 	_, dbDesc, err := params.p.Descriptors().GetImmutableDatabaseByID(
> ```

Don't you need an `AvoidCached` version here?

**Review by otan — COMMENTED** [review]
suggestions changed on base PR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-:-MW0wFBv0G0EqSohmg4K:b-91h1n2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @miretskiy)

___
*[pkg/sql/create_sequence.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0EJ2MDGTziNxfU2OU:-MW0bfYM7e2d_qtrArLJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L91)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

mind removing this context? Looks greyed out
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 2419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0DBMjAuxwi4Vu7XhO:-MW0bgaa6PPCKzPYHU7r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_table.go#L2419)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Don't you need an `AvoidCached` version here?
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62122#-MW0CFYqB8tWdzEGIBWW:-MW0blVo8iQki3Ln_0GL:b-mb9b24) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe2b8ea5c161606e5fe4a7ed1b8225d8e3cb450/pkg/sql/catalog/tabledesc/validate.go#L1253)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Does it make sense here to create IsDefaultLocalitySequence and tree.DefaultLocalitySequence, so that we only have to change this in one place down the road?
</blockquote></details>

hmm, i don't see the value of it so much right now as i imagine the way we go forwards from here is allowing users to configure it.
depends how strongly you feel. happy to do this in a follow up.

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
