### PR TITLE
sql: make a couple of constants metamorphic

### LINKED ISSUE #75468: sql: DefaultBatchBytesLimit and ParallelScanResultThreshold should be metamorphic constants
If we ran a good chunk of our tests with randomized values for these settings, we would likely have caught #74736.

Jira issue: CRDB-12685

### PR DESCRIPTION
**Pull request by yuzefovich**
**logictest: clean up non-metamorphic tests a bit**

This commit renames a knob to disable metamorphic randomization of some
values since the knob now controls more than the two variables it was
made for initially. Additionally, all logic tests in the `execbuild`
package now run with forced production values, so all corresponding
"nonmetamorphic" files have dropped that suffix or have been merged
into the corresponding files without the suffix. (There is no benefit
to randomizing different values in these execbuild tests.)

Release note: None

**sql: make a couple of constants metamorphic**

This commit makes `execbuilder.ParallelScanResultThreshold` and
`rowinfra.DefaultBatchBytesLimit` constants metamorphic. The former is
randomized in [1, 10000] range and the latter in [1B, 64KiB] range.
The randomization is disabled via a testing knob, and I had to use that
knob in some tests and benchmarks as well as mark some logic tests as
"nonmetamorphic".

I ran several CI runs with both constants hard-coded at 1, and I think
I fleshed out all flakes.

Fixes: #75468.

Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg and @yuzefovich)

___
*[pkg/sql/rowinfra/base.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-MvbD3Ut-sBNHklCoBs_:-MvbD3Ut-sBNHklCoBsa:bpb59ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dd97b00bcb631ca4f5d7ce7d80cbb930067e7eb/pkg/sql/rowinfra/base.go#L48)):*
> ```Go
> 	"default-batch-bytes-limit",
> 	10<<20, /* defaultValue, 10 MB */
> 	1,      /* metamorphicValue */
> ```

I wonder if we should extend `metamorphicValue` to a set of (multiple) values as opposed to a singleton? While it may suffice to try a single value in this case, it seems error-prone in general; e.g., what if there is a possibility of another bug lurking when `DefaultBatchBytesLimit` is `NoBytesLimit` (0) or some other well-defined value? It's probably outside of the scope of this PR, but methinks it might be worthwhile to extend `ConstantWithMetamorphicTestValue` so that it allows fuzzing multiple values for a given param.; also, uniform distribution might be good enough initially, but for some params other distributions might be more fruitful, e.g., exponential; i.e., `ConstantWithMetamorphicTestValue` could be extended to support both a set of values and a distribution.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

___
*[pkg/sql/rowinfra/base.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-MvbD3Ut-sBNHklCoBs_:-MvbLAYA3r7m9JJzDjkn:buabbez) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dd97b00bcb631ca4f5d7ce7d80cbb930067e7eb/pkg/sql/rowinfra/base.go#L48)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I wonder if we should extend `metamorphicValue` to a set of (multiple) values as opposed to a singleton? While it may suffice to try a single value in this case, it seems error-prone in general; e.g., what if there is a possibility of another bug lurking when `DefaultBatchBytesLimit` is `NoBytesLimit` (0) or some other well-defined value? It's probably outside of the scope of this PR, but methinks it might be worthwhile to extend `ConstantWithMetamorphicTestValue` so that it allows fuzzing multiple values for a given param.; also, uniform distribution might be good enough initially, but for some params other distributions might be more fruitful, e.g., exponential; i.e., `ConstantWithMetamorphicTestValue` could be extended to support both a set of values and a distribution.
</blockquote></details>

We do have `ConstantWithMetamorphicTestRange ` that uses a uniform distribution within the specified boundaries, and I intend to use that eventually in this change. For the moment, I was trying to flesh out all cases that would fail with the lowest possible value, so I hard-coded it to be 1.

Your idea of having another `ConstantWithMetamorphic` variant that would take in a set of "interesting pre-defined" values sounds worth pursuing too.

**Comment by yuzefovich** [comment]
First commit is #79922 and should be ignored here.

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 22 files at r3, 16 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @srosenberg, and @yuzefovich)

___
*[pkg/sql/rowinfra/base.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-N-cxeIQDXRBxVz0giQg:-N-cxeIQDXRBxVz0giQh:bwruh1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fc59c98847becaabc624505b08ae575d09de4d5/pkg/sql/rowinfra/base.go#L49)):*
> ```Go
> 	defaultBatchBytesLimitProductionValue, /* defaultValue */
> 	1,                                     /* min */
> 	1<<15,                                 /* max, 64KiB */
> ```

How did you pick this max value?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rharding6373, and @srosenberg)

___
*[pkg/sql/rowinfra/base.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-N-cxeIQDXRBxVz0giQg:-N-dCw5DBgjP4-XsKMgz:b-yieuq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fc59c98847becaabc624505b08ae575d09de4d5/pkg/sql/rowinfra/base.go#L49)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

How did you pick this max value?
</blockquote></details>

It is somewhat arbitrary. The smaller the value is, the more likely for the KV layer to return multiple BatchResponses for a single BatchRequest, and randomizing this value wants to encourage that, so the values should be relatively small. If we were to pick 10MiB as the max, then small values would be extremely rare. 64KiB seems large enough for decent randomization range for variety, but also small enough that small values will be picked often. I know I'm a bit hand-wavy here, but I don't know whether we can be more principled.

**Review by cucaroach — APPROVED** [review]
> Reviewed 17 of 22 files at r3, 18 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rharding6373, and @srosenberg)

**Review by yuzefovich — COMMENTED** [review]
@rharding6373 are you ok with merging this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-:-N02vRF_-kHGoOJk1peh:b6dvm6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rharding6373, and @srosenberg)

**Review by rharding6373 — APPROVED** [review]
:lgtm: :thumbsup: sorry for the delay!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-:-N02w8mI7D01A_ZV2d59:b-wk9h00)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @rharding6373, and @srosenberg)

**Review by yuzefovich — COMMENTED** [review]
No worries, TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75302#-:-N02x_Rh9wAXv6kdyWoQ:bdeystw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @rharding6373, and @srosenberg)

**Pull request merged**
