### PR TITLE
roachtest: update 21.1 version map to 20.2.15

### PR DESCRIPTION
**Pull request by celiala**
This updates the version mapping of the 21.1 branch to point to the
latest version (20.2.15).

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks!

**Comment by erikgrinaker** [comment]
There's a comment there about running acceptance/version-upgrade to generate some test fixtures, will we have to do that as well?

**Comment by celiala** [comment]
Ah: those comments are from April 2020, but the more recent [notes on the Release Process wiki](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures) say that fixtures only need to be regenerated for a new major release. 

I'll update the comments in the code before merging, thanks!

**Comment by erikgrinaker** [comment]
Great, thanks for looking into it!

**Comment by tbg** [comment]
Correct, the fixtures only need to be built "once", when they are first
required, for the same reasons that users can freely switch between
binaries for a patch release.

**Pull request merged**
