### PR TITLE
kvserver: improve the closedts regression message

### PR DESCRIPTION
**Pull request by andreimatei**
This patch improves the respective assertion failure message. For no
good reason we weren't including the request triggering the assertion if
it wasn't an "intent write". Also include the command's Raft term and
index.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
Please see again an extra commit printing the Raft log.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64163#-:-MZ-pGtzBhUwhqh24Q-U:b-sonirt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64163#-:-MZByEJ5-JceF2lg52Km:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64163#-:-MZDni-2CJ7ZuhdL8uP6:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64163#-:-MZFNJDm5PZ9FXX2cuYs:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
