### PR TITLE
roachpb: remove deprecated range from admin scatter response

### PR DESCRIPTION
**Pull request by adityamaru**
This change removes the DeprecatedRanges field from the admin scatter
response proto and deletes relevant code.  This was kept around for
compatibility with 20.1, and hence it is safe to remove this in 21.1.

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
Stumbled on this while working on the protected ts PR.

**Review by pbardea — APPROVED** [review]
Thanks for cleaning this up!

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea

**Comment by rafiss** [comment]
@adityamaru friendly ping on this: does this still need to be backported?

**Comment by adityamaru** [comment]
nope, we decided against backporting this. Thanks for the ping!

**Pull request merged**
