### PR TITLE
server,rpc: validate node IDs in RPC heartbeats

### LINKED ISSUE #34158: rpc: verify node ID in handshake
Outside of gossip, when a cockroach node opens an RPC connection it knows the ID of the node it expects to be talking to. Due to the ephemerality and reuse of hostnames under Kubernetes, the recipient might be a different node. For sanity, and reduction of log spam, we should extend the handshake request `PingRequest` to take an optional node ID. If present the request should fail if the remote node ID differs from the requested ID.

See https://github.com/cockroachdb/cockroach/issues/34120#issuecomment-456207387.

### PR DESCRIPTION
**Pull request by knz**
Fixes #34158.

Prior to this patch, it was possible for a RPC client to dial a node
ID and get a connection to another node instead. This is because the
mapping of node ID -> address may be stale, and a different node could
take the address of the intended node from "under" the dialer.

(See #34155 for a scenario.)

This happened to be "safe" in many cases where it matters because:

- RPC requests for distSQL are OK with being served on a different
  node than intended (with potential performance drop);
- RPC requests to the KV layer are OK with being served on a different
  node than intended (they would route underneath);
- RPC requests to the storage layer are rejected by the
  remote node because the store ID in the request would not match.

However this safety is largely accidental, and we should not work with
the assumption that any RPC request is safe to be mis-routed. (In
fact, we have not audited all the RPC endpoints and cannot establish
this safety exists throughout.)

This patch works to prevent these mis-routings by adding a check of
the intended node ID during RPC heartbeats (including the initial
heartbeat), when the intended node ID is known. A new API
`GRPCDialNode()` is introduced to establish such connections.

Release note (bug fix): CockroachDB now performs fewer attempts to
communicate with the wrong node, when a node is restarted with another
node's address.

### CODE REVIEW

**Comment by tbg** [comment]
> Hence my proposal to revert the condition to args.NodeID != 0 && nodeID != 0 && args.NodeID != nodeID as I had initially.

Before you do that, I would special-case nodeID `-1` to mean "this is the multiTestContext, please let me do bad things".

**Comment by knz** [comment]
> Before you do that, I would special-case nodeID -1 to mean "this is the multiTestContext, please let me do bad things".

Done, with a testing knob instead.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @tbg)

___
*[pkg/rpc/heartbeat.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LX-1uGY-KBrt6HcHqC0:-LX-1uGY-KBrt6HcHqC1:b6o3s3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d999e247ae78081dcba0de44a0ef92b06f021abf/pkg/rpc/heartbeat.go#L85)):*
> ```Go
> // populate separate node IDs for each heartbeat service.
> // The returned callback should be called to cancel the effect.
> func TestingAllowNamedRPCToAnonymousServer() func() {
> ```

This is a dated way of tweaking behavior for tests. Can you put a boolean on `*HeartbeatService` and `Context` (for plumbing from the latter into the former in `NewServerWithInterceptor`)? This is a bit more work, but now it's unclear that we'll really undo this change when an mtc-based test fails. I really want to avoid hacks like this, sorry to make you jump through another hoop. So concretely my suggestion is:

1. add a TestingNoValidateNodeIDs into Context
1. in NewServerWithInterceptor, carry the bool over into HeartbeatService
1. use the bool in Ping

Perhaps there's a more direct way, but we never hold on to the heartbeat service (we just stick it into a grpc server) and doing so wouldn't add clarity (then it would seem that one could replace the heartbeat service, but that wouldn't work).

**Review by tbg — COMMENTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @petermattis)

**Comment by knz** [comment]
> Can you put a boolean on *HeartbeatService and Context (for plumbing from the latter into the former in NewServerWithInterceptor)?

Done, RFAL

(I had no choice but to do that anyway, otherwise the race detector didn't like me during stress runs)

**Comment by knz** [comment]
@petermattis 
> I'm still a bit anxious about this PR (I just realized that 2 RPC connections means we'll be exchanging clock synchronization twice per node

I think that since I'm still doing the thing to share the `*Connection` object between gossip and "named" (specific node ID) dials, there should be just 1 RPC connection between two nodes.

**Review by petermattis — COMMENTED** [review]
> I think that since I'm still doing the thing to share the *Connection object between gossip and "named" (specific node ID) dials, there should be just 1 RPC connection between two nodes.

I think gossip will frequently be the first connection to a remote node. That will prohibit sharing a connection.

> Yes and what's the problem with that?
>
> My understanding is that if the conn object gets closed on the non-zero path, it's going to be marked as unusable (the grpc code marks it as closed) and so further zero-nodeid rpc activity (gossip) will cause a re-dial. Is my understanding wrong?

I'm not sure what problems that will cause. I don't think this scenario is adequately tested to give us any confidence that the right thing occurs. Feel free to point to tests that I'm missing. My anxiety here is relaxing a previous invariant: closing a connection removes the connection from the connection map.

I'm wondering what the aim of this PR should be. Should we be trying to make it impossible to send an RPC to a remote node with the wrong node ID? That's noble (and perhaps the right thing to do), but also risky in the short term. Another approach would be to focus on reducing the log spam (that's the near term impetus for a change). For example, `nodeDialer` could poison the local gossip address cache for a node if it discovers the remote node has an unexpected ID. I think that could be done while leaving the current connection behavior in place.

I apologize for the strictness of this review. I'm happy to take this change over if you'd like. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-:-LX4rtPb4ZIvL4C7QxDK:bfa7wgu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @tbg)

**Comment by knz** [comment]
> Should we be trying to make it impossible to send an RPC to a remote node with the wrong node ID? That's noble (and perhaps the right thing to do),

The evidence (based on my limited testing) is that we do not have a disciplined approach to prevent mis-routed RPCs from being incorrectly served and break invariants. See the commit message at the top of this PR. On its own that's an important goal.

> but also risky in the short term.

Can you clarify why?

> For example, nodeDialer could poison the local gossip address cache for a node if it discovers the remote node has an unexpected ID. 

We can certainly _also_ do this (the current PR, as it stands, does not do this yet). I'm happy to add this.

**Comment by knz** [comment]
(rebased PR - will check what CI fallout we get)

**Comment by tbg** [comment]
Could you update the commit/PR message to indicate what the behavior you're introducing is? I gather that outbound connections to NodeID zero don't validate the peer. From reading the code, I think the situation is as follows:

1. zero given, nothing cached: creates new connection that doesn't validate NodeID.
1. NodeID given, but cached with zero: opens new connection, leaves old connection in place (so dialing to zero later still gives the unvalidated conn back)
1. zero given, cached with nonzero: will use the cached connection.

Please state that (in better words) and give a bit of motivation. It'd also be good to learn who doesn't necessarily supply a NodeID. I think we should consider removing the nodeID-less API completely and force callers to explicitly pass a nodeID (even if it's zero) to make sure we don't regress in silly ways.

The major problem (but it's not a new problem) here seems to be that these unvalidated connections have no reason to ever go away. This is just fallout of the fact that we don't have a mechanism to gracefully tear down connections at all. We don't want to just brutally close the old connection because that gives ugly errors. And yet we know that consumers of a connection can hold on to it for essentially forever (for example Raft transport). Fixing this seems out of scope here and will require all callers to buy into the fact that they'll need to switch over at some point. It'll be a while until that's worth it.

I also looked into @petermattis' concern about clock offsets. We will have multiple connections open but the clock offset measurements key only on the address (i.e. we won't double count the measurements, though we'll measure and verify more frequently). That seems like it *should* be fine, but should also be mentioned in the commit, or even in the code, where appropriate.

I still have to review the code in detail, but it looked pretty solid. @petermattis had a good point that putting a connection in multiple slots in the map (zero and nonzero) might cause new behavior that needs to be tested appropriately.

**Comment by knz** [comment]
> Could you update the commit/PR message to indicate what the behavior you're introducing is? 
> Please state that (in better words) and give a bit of motivation.

Done.

> It'd also be good to learn who doesn't necessarily supply a NodeID.

Done (Gossip + CLI client commands)

> I think we should consider removing the nodeID-less API completely and force callers to explicitly pass a nodeID (even if it's zero) to make sure we don't regress in silly ways.

Agreed! I added a 2nd commit to do exactly that. PTAL!

> The major problem (but it's not a new problem) here seems to be that these unvalidated connections have no reason to ever go away. 

- for gossip it does not matter
- for CLI clients it does not matter
- there are no other users
- so we're fine!

**Review by tbg — APPROVED** [review]
Before you merge this, can you set up a local three node cluster (or just run the tpcc `headroom` roachtest) and watch the logs for annoying errors, especially early as the cluster is brought up? I don't expect there to be much (that isn't already there before this PR) but it's worth a look.

Thanks for pulling through!

> Reviewed 2 of 8 files at r2, 16 of 16 files at r3, 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-:-LcexrJd1u97mTRWDxsQ:bexw7z2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/start.go, line 1137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcewcqKDzdwnBahUovZ:-LcewcqKDzdwnBahUov_:bilklke) ([raw file](https://github.com/cockroachdb/cockroach/blob/25747e57900dfa5ff32bccdb5ed604072a00921c/pkg/cli/start.go#L1137)):*
> ```Go
> 	// We use GRPCGossipDial() here because it does not matter
> 	// to which node we're talking to.
> 	conn, err := rpcContext.GRPCGossipDial(addr).Connect(ctx)
> ```

how about `GRPCUnvalidatedDial`?
___
*[pkg/rpc/heartbeat.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcevmdtE8LpmN743ZZ7:-LcevmduCnz1uAOH8QGP:b-3fnx69) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ba844acc33fe34fe51b12cf88c984f4bc08206/pkg/rpc/heartbeat.go#L60)):*
> ```Go
> 	// currently used by the multiTestContext which does not suitably
> 	// populate separate node IDs for each heartbeat service.
> 	// The returned callback should be called to cancel the effect.
> ```

Remove this line.
___
*[pkg/server/server.go, line 1493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcewDay4_TuvOWAzIzh:-LcewDay4_TuvOWAzIzi:bp13d6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d999e247ae78081dcba0de44a0ef92b06f021abf/pkg/server/server.go#L1493)):*
> ```Go
> 	// Now that we have a node ID, ensure that incoming RPC connections
> 	// are validated against this node ID.
> 	s.rpcContext.NodeID.Set(ctx, s.NodeID())
> ```

Why did you (have to) lower this into `*Node`?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/start.go, line 1137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcewcqKDzdwnBahUovZ:-LckVcWyCt8V0p7nHb7G:b-lyranz) ([raw file](https://github.com/cockroachdb/cockroach/blob/25747e57900dfa5ff32bccdb5ed604072a00921c/pkg/cli/start.go#L1137)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

how about `GRPCUnvalidatedDial`?
</blockquote></details>

I'll trust your judgement.
___
*[pkg/rpc/heartbeat.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LX-1uGY-KBrt6HcHqC0:-LX46IT7C--Lqb4gJJIX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d999e247ae78081dcba0de44a0ef92b06f021abf/pkg/rpc/heartbeat.go#L85)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is a dated way of tweaking behavior for tests. Can you put a boolean on `*HeartbeatService` and `Context` (for plumbing from the latter into the former in `NewServerWithInterceptor`)? This is a bit more work, but now it's unclear that we'll really undo this change when an mtc-based test fails. I really want to avoid hacks like this, sorry to make you jump through another hoop. So concretely my suggestion is:

1. add a TestingNoValidateNodeIDs into Context
1. in NewServerWithInterceptor, carry the bool over into HeartbeatService
1. use the bool in Ping

Perhaps there's a more direct way, but we never hold on to the heartbeat service (we just stick it into a grpc server) and doing so wouldn't add clarity (then it would seem that one could replace the heartbeat service, but that wouldn't work).
</blockquote></details>

Done.
___
*[pkg/rpc/heartbeat.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcevmdtE8LpmN743ZZ7:-LckW9VI3j7qU8334ZSJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68ba844acc33fe34fe51b12cf88c984f4bc08206/pkg/rpc/heartbeat.go#L60)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Remove this line.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-LcewDay4_TuvOWAzIzh:-LckWTbe1EgbTHv2-gwf:bhvd6n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d999e247ae78081dcba0de44a0ef92b06f021abf/pkg/server/server.go#L1493)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why did you (have to) lower this into `*Node`?
</blockquote></details>

I think you're misreading the code and commenting on a rebase diff. I haven't changed anything here.

**Review by knz — COMMENTED** [review]
> Before you merge this, can you set up a local three node cluster [...] and watch the logs for annoying errors, especially early as the cluster is brought up?

I have used my testing script from [earlier](https://github.com/cockroachdb/cockroach/pull/34155#issuecomment-456156335) and I didn't find anything suspicious.

I did find what I was looking for however:

```
I190418 13:02:08.329989 333 rpc/nodedialer/nodedialer.go:143  [n1] unable to connect to n4: failed to connect to n4 at localhost:26004: initial connection heartbeat failed: rpc error: code = Unknown desc = client requested node ID 4 doesn't match server node ID 3
```

(the new check)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-:-LcklS00C3NomdWVRc24:bz30bc4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r5, 17 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34197#-:-LdEBDgjApOfqqCoHnLU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
Thank you

bors r=tbg

**Pull request merged**
