### PR TITLE
kvstorage: speed up scan for range descriptors

### PR DESCRIPTION
**Pull request by RaduBerinde**
On startup we currently scan through all `/Local/Range/` keys in order
to find the range descriptors. In some cases, there can be a lot of
`/Local/Range/Transaction` records so we end up reading through a lot
of data.

This change switches to using `SeekGE`:
 - when we encounter a key that has a suffix before `rdsc` like
   `/Local/Range/foo/prbe`, we seek directly to the corresponding
   descriptor key `/Local/Range/foo/rdsc`;
 - when we encounter a key that has a suffix after `rdsc`, we
   seek beyond all keys for this range, e.g. `/Local/Range/fop/`.

Note that inside Pebble, seeks to a key that is very close to the
current position are optimized to try to iterate through the next few
keys before doing a real seek. So this change should not be very
detrimental even when there aren't a lot of keys to skip.

Fixes: #109740

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxotBSEAdDegMWlmRhf:-NxotBSEAdDegMWlmRhg:b-dzuyir) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L329)):*
> ```Go
> 				return errors.AssertionFailedf("range key has intent with no timestamp")
> 			}
> 			// Seek to the latest value below the intent timestamp.
> ```

This code is well exercised by `loqrecovery.TestRetrieveApplyStatus`, which I have run with `--stress`

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

A few nits, but otherwise changes look good.

I'm not familiar enough with the code and testing in this area, so having a storage review as well would be good. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-:-Nxs4B3e12pUWgzzsub-:bprd1ak)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrvCLd8fzdFQ6TP4P3):*
is -> are
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrwoXr4INlamJ9vRTX:-NxrwoXr4INlamJ9vRTY:b-wnzhvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L281)):*
> ```Go
> 		}
> 
> 		const reportPeriod = 10 * time.Second
> ```

nit: This would be more idiomatic if you used `log.EveryN` and then use call `log.ShouldLog`.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs1Dr-1v-C1UmkUmEQ:-Nxs1Dr-1v-C1UmkUmER:b-iky7g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L316)):*
> ```Go
> 		}
> 
> 		if key.Timestamp.IsEmpty() {
> ```

I'm confused how we get here. Didn't we just check the `suffixCmp` above so we know this is a LocalRangeDescriptorSuffix? Or does this check mean its a "RangeDescriptor intent"? I'm a little unclear why we need to iterate in Inconsistent mode at all here, so maybe just a comment which justifies that would help.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs3sDs-zobS4QESaey:-Nxs3sDs-zobS4QESaez:bl0dz22) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L342)):*
> ```Go
> 			// versions of this key.
> 			tombstoneCount++
> 			iter.NextKey()
> ```

Couldn't we call 
`iter.SeekGE(storage.MVCCKey{Key: nextRangeDescKey})` instead of `NextKey`. 

This probably doesn't normally matter in the scheme of things but might be important if we had a large table delete and had not run an MVCCGC yet.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs31RbEX4b_nBkTAli:-Nxs31RbEX4b_nBkTAlj:b-tsjfik) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L357)):*
> ```Go
> 				key.Key, desc.StartKey)
> 		}
> 		if !desc.IsInitialized() {
> ```

I see this check in the previous commit as well, but what is the rational for failing on an uninitialized replica. I don't fully understand the lifecycle here, but all replicas pass through this state, but maybe the reason is that we neve persiste them to disk? This is more for my understanding of persisted `RangeDescriptors` but consider adding a comment why this is an assertion error or make the message cleaner.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrvqLq0FfnDgKqND_q:-NxrvqLq0FfnDgKqND_r:bl8nyh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L377)):*
> ```Go
> }
> 
> func IterateRangeDescriptorsFromDiskOld(
> ```

It would be cleaner to delete the old code rather than leaving it here.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-:-Nxs9oBs9lx7R6DZxjw0:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @bdarnell, and @jbowens)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrvCLd8fzdFQ6TP4P3):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

is -> are
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrwoXr4INlamJ9vRTX:-Nxs83zA-YOGt_hpD2cA:b-b1n4a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L281)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: This would be more idiomatic if you used `log.EveryN` and then use call `log.ShouldLog`.
</blockquote></details>

With `log.EveryN` we would have an undesirable first message at the very start.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs1Dr-1v-C1UmkUmEQ:-Nxs8GbH50sGMRekwUAF:b-xxv7n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L316)):*
We check above that the key starts with `/Local/Range/start-key/rdsc/`. Normally we would have only one or more MVCC values like `/Local/Range/start-key/rdsc/some-timestamp`. For a transasction that was in progress when the node was shut down, we will have an unresolved intent, which is just the "bare" key `/Local/Range/start-key/rdsc/` without a timestamp.

I don't know all the details around why we do this in inconsistent mode (but note that the handling would be more complicated otherwise). @bdarnell mentioned the following:

> There is one special rule for `rdsc` that makes it a little easier: the transaction record for any modification to a `rdsc` record must be located on that range, and the intent is resolved synchronously with the commit/abort of the transaction.
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs3sDs-zobS4QESaey:-Nxs9L6s5vMEZIFzagfY:b-rado06) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L342)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Couldn't we call 
`iter.SeekGE(storage.MVCCKey{Key: nextRangeDescKey})` instead of `NextKey`. 

This probably doesn't normally matter in the scheme of things but might be important if we had a large table delete and had not run an MVCCGC yet.
</blockquote></details>

We don't have a `nextRangeDescKey` here..
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs31RbEX4b_nBkTAli:-Nxs9Sib11Y8eH44gwym:bplobt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L357)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I see this check in the previous commit as well, but what is the rational for failing on an uninitialized replica. I don't fully understand the lifecycle here, but all replicas pass through this state, but maybe the reason is that we neve persiste them to disk? This is more for my understanding of persisted `RangeDescriptors` but consider adding a comment why this is an assertion error or make the message cleaner.
</blockquote></details>

This is the descriptor we just unmarshalled. We should never be writing out an uninitialized descriptor (hence the assertion error).
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxrvqLq0FfnDgKqND_q:-Nxs9j_BDnlDW15kDh9E:b-4irssn) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L377)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

It would be cleaner to delete the old code rather than leaving it here.
</blockquote></details>

Done, I left it accidentally.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @jbowens, @nvanbenschoten, and @RaduBerinde)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-Nxs1Dr-1v-C1UmkUmEQ:-Nxwjx0tCoDVh7UFtavs:b-fcsbph) ([raw file](https://github.com/cockroachdb/cockroach/blob/58777c35cac6854d97ae04eea874bf0dc191788e/pkg/kv/kvserver/kvstorage/init.go#L316)):*
> but note that the handling would be more complicated otherwise

Not just more complicated, but it would no longer be possible to resolve locally. We'd have to look up the transaction record, which may be on another node, and until then we couldn't be sure whether we should be using the RangeDescriptor value from the intent or the last committed value. And this ambiguity can have cascading effects - if a split or merge was left uncommitted, this need to be resolved before we can use the neighboring range as well. We can't bring a cluster up in the face of this ambiguity (Can't remember whether this is something that is definitely impossible or just something we'd rather not deal with), so we jump through hoops to ensure that intents on range descriptors can be resolved locally and we iterate inconsistently here. 
___
*[`pkg/kv/kvserver/kvstorage/init.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxwgGn_1JhHCMB3m-oq:-NxwgGn_1JhHCMB3m-or:b-z0xw5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a268db8ab3bdfcf52eeae8f341b3893fb79171/pkg/kv/kvserver/kvstorage/init.go#L301)):*
> ```Go
> 				iter.SeekGE(storage.MVCCKey{Key: keys.RangeDescriptorKey(keys.MustAddr(startKey))})
> 			} else {
> 				// This case should be rare in practice: we have a key that isn't
> ```

Can it ever happen? Should we log a warning (or panic?) if we see one?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @bdarnell, @jbowens, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxwgGn_1JhHCMB3m-oq:-NxxDYx31o5X-F8edRqB:b-r0mico) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a268db8ab3bdfcf52eeae8f341b3893fb79171/pkg/kv/kvserver/kvstorage/init.go#L301)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Can it ever happen? Should we log a warning (or panic?) if we see one?
</blockquote></details>

I am not sure exactly how things happen when we move a range to another node. We have to update the descriptor and range-delete these keys, do these operations happen together atomically?

If we think it shouldn't happen, I can add a warning and panic in crdb_test mode.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @jbowens, @nvanbenschoten, and @RaduBerinde)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxwgGn_1JhHCMB3m-oq:-NxxdxZQ1stbQN73hm8r:b2qk1pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a268db8ab3bdfcf52eeae8f341b3893fb79171/pkg/kv/kvserver/kvstorage/init.go#L301)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I am not sure exactly how things happen when we move a range to another node. We have to update the descriptor and range-delete these keys, do these operations happen together atomically?

If we think it shouldn't happen, I can add a warning and panic in crdb_test mode.
</blockquote></details>

I would think it would all be atomic but I can't say for sure. If it's not atomic I don't think there's anything else that would asynchronously clean it up so we'd have some kind of leak. I'd be comfortable with at least putting in something like a panic in debug/test mode.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123959)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @bdarnell, @jbowens, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/kvstorage/init.go` line 301 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123959#-NxwgGn_1JhHCMB3m-oq:-Nxxfc01CAl-wxasXF6p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a268db8ab3bdfcf52eeae8f341b3893fb79171/pkg/kv/kvserver/kvstorage/init.go#L301)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I would think it would all be atomic but I can't say for sure. If it's not atomic I don't think there's anything else that would asynchronously clean it up so we'd have some kind of leak. I'd be comfortable with at least putting in something like a panic in debug/test mode.
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
CI failure is #124197

bors r+

**Comment by RaduBerinde** [comment]
How do folks feel about backporting this to 24.1.x (after it bakes on master for a while)?

**Comment by jbowens** [comment]
> How do folks feel about backporting this to 24.1.x (after it bakes on master for a while)?

Just saw another instance of this on 23.2. I'm supportive of backporting it to 24.1.x.

**Comment by RaduBerinde** [comment]
Note to self: if/when we backport, #125094 needs to be backported along with it.

**Pull request merged**
