### PR TITLE
sql: jitter periodic refresh of leases

### LINKED ISSUE #30206: sql: Large spikes of lease-release batch requests every 3m30s
I had a 30 node cluster for running tpc-c 10k tests. I came back to my desk well after some test runs had finished up, meaning there was no SQL workload at all on the cluster and hadn't been for over an hour. I checked out the "Distributed" dashboard in the admin UI, and saw this:

screen shot 2018-09-12 at 11 54 53 pm

Very large spikes of batch requests every 3 minutes and 30 seconds. I did some digging via logspy during one of these spikes to see what these requests were (`/debug/logspy?count=1000&duration=60s&grep=sending%20batch`). I confirmed that the steady background stream was just the timeseries system doings its thing (helpfully marked with the "ts-poll" log tag), and found that the spikes were all caused by the SQL lease management infrastructure (helpfully marked with the "lease-release" log tag), mostly sending requests to the system config span (r7) in very quick succession:

```
...
I180913 04:51:41.529254 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529279 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529329 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529446 35094900 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3d541eb8,ts=1536814301.528467050,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529796 35094826 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=106ace19,ts=1536814301.528471565,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530116 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530186 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530230 35094900 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3d541eb8,ts=1536814301.528467050,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530255 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530375 35094826 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=106ace19,ts=1536814301.528471565,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530763 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530807 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530824 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
...
```

I also did a logspy specifically to get more details on what the lease-release process was doing, but didn't dig through it too much myself:
[lease-release-logspy.txt](https://github.com/cockroachdb/cockroach/files/2380415/lease-release-logspy.txt)

I will say, though, that it seems kind of silly that in order to delete table leases we run a SQL query that has to acquire table leases.

Again, this was on a cluster that hadn't had any SQL clients connected to it for more than an hour, and here it was spiking up to nearly a thousand batch requests per second (~30 qps per each of the 30 nodes in the cluster) every few minutes.

@vivekmenezes is this expected? Handing off to you to triage.

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change jitters the periodic refresh interval so
the periodic refresh of leases from each node are spread.

fixes #30206

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@a-robinson asking you to review because @dt ain't around

**Review by a-robinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30665)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30665#-LNLixNbBdWdFspfpt9Q:-LNLixNbBdWdFspfpt9R:b-20i8cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/58f337322dbd95937c867e2a56870a92f245298d/pkg/sql/lease.go#L1697)):*
> ```Go
> 		tickDuration := m.leaseDuration / 2
> 		// Jitter tickDuration by a bit.
> 		tickDuration = tickDuration - time.Duration(float64(tickDuration/10)*rand.Float64())
> ```

Is this a standard jitter formula? Could we just reuse `jitteredLeaseDuration`, e.g. `tickDuration := m.jitteredLeaseDuration() / 2`?

Although I also wonder if it'd be better to re-jitter for every tick, rather than jittering once up front and having to just live with it if a bunch of nodes end up with the same ticker timing.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30665)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 1697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30665#-LNLixNbBdWdFspfpt9Q:-LNLlqtA7LzIdTO3cr__:b-h1yg3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/58f337322dbd95937c867e2a56870a92f245298d/pkg/sql/lease.go#L1697)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is this a standard jitter formula? Could we just reuse `jitteredLeaseDuration`, e.g. `tickDuration := m.jitteredLeaseDuration() / 2`?

Although I also wonder if it'd be better to re-jitter for every tick, rather than jittering once up front and having to just live with it if a bunch of nodes end up with the same ticker timing.
</blockquote></details>

I'd definitely re-jitter on every tick. I recently fixed this problem in gossip. See https://github.com/cockroachdb/cockroach/pull/29051

**Comment by vivekmenezes** [comment]
@a-robinson @petermattis I modified the code to rejitter before every refresh. Thanks!

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30665#-:-LNQQF1f4UFdF08tx9Qc:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30665#-:-LNQRIoUDCZpi238dwIn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
