### PR TITLE
builtins: add `tenant_span_stats` generator function

### PR DESCRIPTION
**Pull request by THardy98**
Part of: https://github.com/cockroachdb/cockroach/issues/94332
Part of: https://github.com/cockroachdb/cockroach/issues/94330

Added new builtin function `tenant_span_stats` that retrieves span
statistics for the current tenant. `tenant_span_stats` can be called as:
- `crdb_internal.tenant_span_stats()`: returns table span statistics for all of the tenants tables
- `crdb_internal.tenant_span_stats(database_id)`: returns table span statistics for the tenant's tables belonging to the specified database id
- `crdb_internal.tenant_span_stats(database_id, table_id)`: returns the tenant's table span statistics for the provided table id

Returned rows take the format:
```
demo@127.0.0.1:26257/movr> select * from crdb_internal.tenant_span_stats(104);
  database_id | table_id | range_count | approximate_disk_bytes | live_bytes | total_bytes | live_percentage
--------------+----------+-------------+------------------------+------------+-------------+------------------
          104 |      106 |          27 |                  53866 |      16821 |       16821 |               1
          104 |      107 |          27 |                  45285 |      10932 |       10932 |               1
          104 |      108 |          27 |                 225645 |     528219 |      528219 |               1
          104 |      109 |           3 |                 130978 |     260826 |      260826 |               1
          104 |      110 |           3 |                 393815 |     708387 |      708387 |               1
          104 |      111 |           3 |                  30021 |       1413 |        1413 |               1
```

**Note**: This implementation is naive - it calls `SpanStats` for each table span. Future work will entail expanding the endpoint to be able to fetch span statistics for multiple spans at once.

Release note (sql change): new builtin function `tenants_span_stats`,
retrieves the span statistics for the current tenant.

### CODE REVIEW

**Comment by THardy98** [comment]
Not sure how to add logic tests for this builtin. Is there a way to set deterministic values for `approximate_disk_bytes`, `live_bytes`, `total_bytes`?

**Comment by THardy98** [comment]
> > Not sure how to add logic tests for this builtin. Is there a way to set deterministic values for `approximate_disk_bytes`, `live_bytes`, `total_bytes`?
> 
> My 2-cents - Perhaps it would be sufficient to only test this function up to the boundary with `SpanStats()`. There's already coverage of [`SpanStats`](https://github.com/cockroachdb/cockroach/blob/4fee2a42e5f2c10cf0bb5d422121243928a6f297/pkg/server/span_stats_test.go#L28) and [`tenant isolation`](https://github.com/cockroachdb/cockroach/blob/c177713404e2dd933d5404c034e8c85352206043/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L161) --- and then even lower-level coverage of [`RangeStats`](https://github.com/cockroachdb/cockroach/blob/6848307179c02bbc85183f47ffd74ae1c81118e3/pkg/kv/kvserver/replica_test.go#L11609) and [`ComputeMetrics`](https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/storage/mvcc_test.go#L2145).
> 
> Another test idea would be to make sure that each overloaded function returns the correct column values with respect to database and table.

Yes, considering that SpanStats is already tested there's no need to test the values being returned by SpanStats. Rather, I've added tests ensuring that returned values are scoped correctly (to the correct database, or database + table) and a couple checks to ensure the validity of passed in arguments (no negative values).

**Review by zachlite — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NP4SMBODR2xrbZRHesL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by ecwall — COMMENTED** [review]
Can you partially test the non-deterministic columns with something like `SELECT ... approximate_disk_bytes > 0, live_bytes > 0, etc` to make sure the columns are being populated and aren't just defaulting to a zero value to cover this part of the code
```
		tree.NewDInt(tree.DInt(tssi.currStatsResponse.RangeCount)),
		tree.NewDInt(tree.DInt(tssi.currStatsResponse.ApproximateDiskBytes)),
		tree.NewDInt(tree.DInt(liveBytes)),
		tree.NewDInt(tree.DInt(totalBytes)),
		tree.NewDFloat(tree.DFloat(livePercentage)),
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NPJ9O9R6XmnLf-2UdnV:bn6iq1w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/sql/planner.go` line 857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoFlHCUmCfEMQHPi1:-NPIoFlHCUmCfEMQHPi2:b568cqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L857)):*
> ```Go
> 	ctx context.Context, dbId int, tableId int,
> ) (eval.InternalRows, error) {
> 	query := `SELECT parent_id, table_id from crdb_internal.tables`
> ```

Could you capitalize FROM/WHERE/AND/etc for consistency
___
*[`pkg/sql/planner.go` line 867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoO2h4T0sfIyKDEaE:-NPIoO2h4T0sfIyKDEaF:bthndsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L867)):*
> ```Go
> 		args = append(args, dbId)
> 	} else {
> 		query += ` where parent_id != $1`
> ```

Why is this `parent_id != 0` instead of no WHERE clause?

**Review by THardy98 — COMMENTED** [review]
Added a test to check for non-deterministic columns. Omitted `approximate_disk_bytes`, as we weren't recording any disk bytes until I generated a large series (1mil), which I didn't feel was particularly valuable. I think this its probably sufficient enough to check that our other span stats are being populated, but if there's a simple way to ensure that a table has disk bytes, than I can make the change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NPJdXGS4UBF6a8vHSwc:b3y90hw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall)

___
*[`pkg/sql/planner.go` line 857 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoFlHCUmCfEMQHPi1:-NPJWOhR7_U10P0FR-9e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L857)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Could you capitalize FROM/WHERE/AND/etc for consistency
</blockquote></details>

Done.
___
*[`pkg/sql/planner.go` line 867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoO2h4T0sfIyKDEaE:-NPJWPTz0MBkJV8NIZoC:b-94guuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L867)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Why is this `parent_id != 0` instead of no WHERE clause?
</blockquote></details>

Some tables belonging to `crdb_internal.tables` are not affiliated with a database and have a `parent_id` of 0 (usually crdb_internal or pg catalog tables), which aren't useful to the user.

**Review by ecwall — APPROVED** [review]
Looks good just a couple minor comments before merging
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NPNVHr35YyOX4B_pwul:b-blgj1c)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @THardy98)

___
*[`pkg/sql/planner.go` line 867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoO2h4T0sfIyKDEaE:-NPNVqe1AOCC3L9KyFwh:b-tspk5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L867)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Some tables belonging to `crdb_internal.tables` are not affiliated with a database and have a `parent_id` of 0 (usually crdb_internal or pg catalog tables), which aren't useful to the user.
</blockquote></details>

Can you add this as a brief comment here since it was not obvious to me.
___
*[`pkg/sql/planner.go` line 871 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPNVXElDcskFgiV1s3w:-NPNVXElDcskFgiV1s3x:b-10izyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c83a7ef086ee24259b9291fe99e08dd87db29cf/pkg/sql/planner.go#L871)):*
> ```Go
> 	}
> 
> 	it, err := p.QueryIteratorEx(
> ```

You can just `return p.QueryIteratorEx(...)` instead of doing this assignment.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 2958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPNUlFz7mJRE1i-DBtF:-NPNUlFz7mJRE1i-DBtG:b-z2slcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c83a7ef086ee24259b9291fe99e08dd87db29cf/pkg/sql/sem/builtins/generator_builtins.go#L2958)):*
> ```Go
> 	var next bool
> 	var err error
> 	next, err = tssi.it.Next(ctx)
> ```

Remove the separate declarations and use `next, err :=`.

**Review by THardy98 — COMMENTED** [review]
Addressed the nits, TYFR :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NPNnYtR43A6q35TNRsE:b-qp9fn3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ecwall)

___
*[`pkg/sql/planner.go` line 867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPIoO2h4T0sfIyKDEaE:-NPNn3J2DfrJ3aYkppef:b-n3y33b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc7d252cde89d0315766e9e9707fc84d31637729/pkg/sql/planner.go#L867)):*
>  tables belonging to crdb_internal.tables are not affiliated with a database and have a parent_id of 0 (usually crdb_internal or pg catalog tables), which aren't useful to the user.
Added a comment.
___
*[`pkg/sql/planner.go` line 871 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPNVXElDcskFgiV1s3w:-NPNn4Xf-knfWeE47JhM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c83a7ef086ee24259b9291fe99e08dd87db29cf/pkg/sql/planner.go#L871)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

You can just `return p.QueryIteratorEx(...)` instead of doing this assignment.
</blockquote></details>

Done
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 2958 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPNUlFz7mJRE1i-DBtF:-NPNnBGUA-J10OoZLKcx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c83a7ef086ee24259b9291fe99e08dd87db29cf/pkg/sql/sem/builtins/generator_builtins.go#L2958)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Remove the separate declarations and use `next, err :=`.
</blockquote></details>

Done

**Review by j82w — COMMENTED** [review]
> Reviewed 2 of 7 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ecwall and @THardy98)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPSO8lOAf9z4Uq4zSu7:-NPSO8lOAf9z4Uq4zSu8:b-datq0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f826d8a161f55413dac39af9cbccaebdeaf5ea4/pkg/sql/sem/builtins/generator_builtins.go#L3017)):*
> ```Go
> 		return nil, err
> 	}
> 	if !isAdmin {
> ```

Should this also be allowed for the same roles as `HasViewActivityOrViewActivityRedactedRole` to match the crdb_internal view role check?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ecwall and @j82w)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPSO8lOAf9z4Uq4zSu7:-NPSZsElBddJyDcuV9_g:bmt95rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f826d8a161f55413dac39af9cbccaebdeaf5ea4/pkg/sql/sem/builtins/generator_builtins.go#L3017)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this also be allowed for the same roles as `HasViewActivityOrViewActivityRedactedRole` to match the crdb_internal view role check?
</blockquote></details>

I had kept it to admin as the `SpanStats` endpoint is scoped to admin privileges.

**Comment by j82w** [comment]
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPSO8lOAf9z4Uq4zSu7:-NPSe_175zW_BVKV3kei:bn1o9qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f826d8a161f55413dac39af9cbccaebdeaf5ea4/pkg/sql/sem/builtins/generator_builtins.go#L3017)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

I kept it to admin as the `SpanStats` endpoint is scoped to admin privileges.
</blockquote></details>

Does the database page work with view activity permission? Will the ui using sql-over-http still work if this requires admin?

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-:-NPSrldP8CKmWXGWc5li:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ecwall and @THardy98)

**Comment by THardy98** [comment]
> _[`pkg/sql/sem/builtins/generator_builtins.go` line 3017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPSO8lOAf9z4Uq4zSu7:-NPSe_175zW_BVKV3kei:bn1o9qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f826d8a161f55413dac39af9cbccaebdeaf5ea4/pkg/sql/sem/builtins/generator_builtins.go#L3017)):_
> 
> Previously, THardy98 (Thomas Hardy) wrote…
> Does the database page work with view activity permission? Will the ui using sql-over-http still work if this requires admin?

After some discussion offline, opened up the builtin to anyone with `VIEWACTIVITY` permission.

**Review by j82w — COMMENTED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ecwall and @THardy98)

___
*[`pkg/sql/authorization.go` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPY2Loh4Ax3Hy0uddQE:-NPY2Loh4Ax3Hy0uddQF:bac59pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10fdf9772e68c557132db4f59c2948684d146bca/pkg/sql/authorization.go#L462)):*
> ```Go
> // HasViewActivity implements the AuthorizationAccessor interface.
> // Requires a valid transaction to be open.
> func (p *planner) HasViewActivity(ctx context.Context) (bool, error) {
> ```

Why not use the existing `HasViewActivityOrViewActivityRedactedRole` which the crdb_internal views use?

**Comment by THardy98** [comment]
> > Reviewed 1 of 5 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ecwall and @THardy98)
> 
> _[`pkg/sql/authorization.go` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPY2Loh4Ax3Hy0uddQE:-NPY2Loh4Ax3Hy0uddQF:bac59pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10fdf9772e68c557132db4f59c2948684d146bca/pkg/sql/authorization.go#L462)):_
> 
> > ```go
> > // HasViewActivity implements the AuthorizationAccessor interface.
> > // Requires a valid transaction to be open.
> > func (p *planner) HasViewActivity(ctx context.Context) (bool, error) {
> > ```
> 
> Why not use the existing `HasViewActivityOrViewActivityRedactedRole` which the crdb_internal views use?

Not sure how I missed that, will use it instead.

**Comment by THardy98** [comment]
> > Reviewed 1 of 5 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ecwall and @THardy98)
> 
> _[`pkg/sql/authorization.go` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPY2Loh4Ax3Hy0uddQE:-NPY2Loh4Ax3Hy0uddQF:bac59pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10fdf9772e68c557132db4f59c2948684d146bca/pkg/sql/authorization.go#L462)):_
> 
> > ```go
> > // HasViewActivity implements the AuthorizationAccessor interface.
> > // Requires a valid transaction to be open.
> > func (p *planner) HasViewActivity(ctx context.Context) (bool, error) {
> > ```
> 
> Why not use the existing `HasViewActivityOrViewActivityRedactedRole` which the crdb_internal views use?

Done

**Review by j82w — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ecwall and @THardy98)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3018 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPYVuQ33X00ySisPkxl:-NPYVuQ4CumBbx3o6a_k:bmbr8ci) ([raw file](https://github.com/cockroachdb/cockroach/blob/be984c23964baca67f86c7b8789398b10772632c/pkg/sql/sem/builtins/generator_builtins.go#L3018)):*
> ```Go
> 	}
> 	if !hasViewActivity {
> 		return nil, pgerror.Newf(pgcode.InsufficientPrivilege, "user needs the VIEWACTIVITY or VIEWACTIVITYREDACTED permission to view span statistics")
> ```

Should this include admin?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ecwall and @j82w)

___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 3018 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/97534#-NPYVuQ33X00ySisPkxl:-NPYY9hfBcdPEZtj4VI2:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/be984c23964baca67f86c7b8789398b10772632c/pkg/sql/sem/builtins/generator_builtins.go#L3018)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this include admin?
</blockquote></details>

Added.

**Comment by THardy98** [comment]
TYFR :)

**Pull request merged**
