### PR TITLE
sql: Fix DB-qualified table names in CREATE TABLE AS

### LINKED ISSUE #9307: sql: CREATE TABLE AS doesn't work with a fully-qualified table name
```
root@:26257> CREATE DATABASE foo;
CREATE DATABASE
root@:26257> create table foo.bar as VALUES ('one', 1), ('two', 2);
pq: table "foo.bar" does not exist
```

The same thing happens if you try to populate it from an existing table.

The fix is trivial, I'll send out a PR shortly.

### PR DESCRIPTION
**Pull request by a-robinson**
Also cleaned up variable name in related function to be more consistent.

Fixes #9307

@dt

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9309)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309#-:-KRVGRJ19QsjDbFzk-LL:bnfp4nl)*

**Comment by mjibson** [comment]
Err, I think we need another test first.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/create_as, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309#-KRVJ2rIoLVP9GDzxM7S:-KRVJ2rIoLVP9GDzxM7T:b-i4tf4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d095e622a75c846a9dba4e95fc6d59f528d3d63/sql/testdata/create_as#L67)):*
> ```
> 
> statement ok
> CREATE TABLE IF NOT EXISTS smtng.something AS SELECT * FROM stock
> ```

I'd like a test to verify that the table was indeed created on that database instead of the current database.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309#-:-KRVItStIsd3d69VRQWD:bjxmrtq)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/create_as, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309#-KRVJ2rIoLVP9GDzxM7S:-KRVN5u7GEaSRfq58b0L:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d095e622a75c846a9dba4e95fc6d59f528d3d63/sql/testdata/create_as#L67)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I'd like a test to verify that the table was indeed created on that database instead of the current database.
</details>
Good call, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9309#-:-KRXfAhUj6Y4yQRKb9tn:bnfp4nl)*

**Pull request merged**
