### PR TITLE
opt: Improve FuncDepSet

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains a number of improvements and fixes to the functional
dependency library:

- Normalize constants and equivalencies so there's less redundancy
- Allow MakeOuter dependencies that cross join boundaries
- Make ProjectCols actually remove un-projected columns
- Fix FDs generated for apply joins
- Add Verify method to FuncDepSet

Together, these changes clean up the FD logical props so that they're
more compact and more efficient.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Some minor comments for r1 (posting separately so it's easier to keep track of which commit to update).

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/props/func_dep.go, line 737 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5dmfYATbHTkVMjYyt:-LG5dmfYATbHTkVMjYyu:bkwnn6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5b300ddc93bfd94ef5c040d9394c9da1e28047/pkg/sql/opt/props/func_dep.go#L737)):*
> ```Go
> 		f.deps = deps
> 	} else {
> 		f.deps[0].to = f.deps[0].to.Union(cols)
> ```

I wondered if we should also set `cols` to the union to make the logic below do more. I don't think that does anything because we would have already performed simplifications with existing constant columns, but it's a bit subtle. Not sure if it warrants a comment or not though.

---

*[pkg/sql/opt/props/func_dep.go, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5b9p09E92OwHB9GSW:-LG5b9p09E92OwHB9GSX:b-gytg5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5b300ddc93bfd94ef5c040d9394c9da1e28047/pkg/sql/opt/props/func_dep.go#L748)):*
> ```Go
> 		if !fd.equiv {
> 			if fd.strict {
> 				// Constants in the from side of a strict dependency are no-ops,
> ```

[nit] This is a bit misleading. There are two cases:
 - if the from side includes constant columns and non-constant columns, the constant columns are no-ops and can be removed;
 - if the from side includes only constant columns, the to side is also constant and would now be represented in the first FD; so this FD is redundant. (maybe we could assert that `to` is included in `f.deps[0].to`)

---

*[pkg/sql/opt/props/func_dep_test.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5cNmw7nSk8Wq9mOT0:-LG5cNmx65xz558dS6fM:b1fps9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5b300ddc93bfd94ef5c040d9394c9da1e28047/pkg/sql/opt/props/func_dep_test.go#L472)):*
> ```Go
> 	verifyFD(t, &bcden, "")
> 
> 	// Project single row.
> ```

single column

---

*[pkg/sql/opt/props/func_dep_test.go, line 473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5csxIC5gsaM-CULnt:-LG5csxIC5gsaM-CULnu:bb7c33j) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5b300ddc93bfd94ef5c040d9394c9da1e28047/pkg/sql/opt/props/func_dep_test.go#L473)):*
> ```Go
> 
> 	// Project single row.
> 	//   SELECT d FROM abcde, mnpq WHERE a=m AND 1=1 AND n=2
> ```

a=1?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG5dJI_3FkdEjTG8h0C:b-8bvqc7)*

**Comment by RaduBerinde** [comment]
r2 LGTM

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/props/func_dep.go, line 721 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5p8yZ8i8-_hdjN5pI:-LG5p8yZ8i8-_hdjN5pJ:b-xpvv1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/53d9b700bbdc0f410cb70db3ac60cc697298c5d4/pkg/sql/opt/props/func_dep.go#L721)):*
> ```Go
> 			// All determinant columns are equivalent to one another.
> 			if fd.equiv {
> 				// Ensure that each equivalent columns directly maps to all other
> ```

[nit] columns

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG5paDV5zmArfH9ue7r:bs93zcf)*

**Comment by RaduBerinde** [comment]
r3,r4 LGTM
t5 LGTM (with minor comments)

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/props/func_dep.go, line 986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5rFSgB05xn3vcGGka:-LG5rFSgB05xn3vcGGkb:b-2mv86) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a46b4639e384fc2df4025af4ee8305c884c1ab0/pkg/sql/opt/props/func_dep.go#L986)):*
> ```Go
> 			//   ----------------------
> 			//   1  4  1     NULL  2
> 			//   2  5  NULL  NULL  NULL
> ```

Could you add a `2 4 2 x y` line as an example of when `(a)-->(c)` doesn't hold?

---

*[pkg/sql/opt/props/func_dep_test.go, line 597 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5taTO2jFPVqEQGaC0:-LG5taTO2jFPVqEQGaC1:btcmpjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a46b4639e384fc2df4025af4ee8305c884c1ab0/pkg/sql/opt/props/func_dep_test.go#L597)):*
> ```Go
> 	//   SELECT * FROM abcde RIGHT OUTER JOIN mnpq ON a=m
> 	nullExtendedCols = util.MakeFastIntSet(1, 2, 3, 4, 5)
> 	loj = makeAbcdeFD(t)
> ```

[nit] should be `roj` (same for the two cases above and the one below)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG5qh__2rrs0Ib-A89f:b-ifm5f7)*

**Comment by RaduBerinde** [comment]
question on r6

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/props/func_dep.go, line 810 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5ueUlDY2Yu5aa1q8t:-LG5ueUlDY2Yu5aa1q8u:bnbvx1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/451be85a4db6991fe0d604f05d404e3646dbd919/pkg/sql/opt/props/func_dep.go#L810)):*
> ```Go
> 				fd.to = f.ComputeClosure(fd.to)
> 			}
> 		}
> ```

Can't we also replace any removed columns in `from` with equivalent columns that are not removed (if possible)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG5uyUK0bo8MnusoC3u:b-7dfc7k)*

**Comment by RaduBerinde** [comment]
r7 LGTM
question on r8
r9 LGTM

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 643 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG5zGhp6pIJ4HJjzMoA:-LG5zGhp6pIJ4HJjzMoB:b-sz2jvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27349195fda2806a6f0235bc7c31af64e79d7b7/pkg/sql/opt/norm/testdata/rules/decorrelate#L643)):*
> ```
>  │    │    │    ├── columns: x:6(int!null) y:7(int) v:9(int) notnull:12(bool)
>  │    │    │    ├── outer: (2)
>  │    │    │    ├── fd: (6)-->(7,12), ()~~>(12)
> ```

Why is `notnull` a constant column here? And how come we have a const column in a `to`, I thought we always simplify that now?

---

*[pkg/sql/opt/props/func_dep.go, line 1071 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LG6-Xms28j4211CdXJA:-LG6-Xms28j4211CdXJB:bqupcg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aa6ab5833d7a3fc907c4179e89fe011991e712c/pkg/sql/opt/props/func_dep.go#L1071)):*
> ```Go
> //   7. Closure of key should include all known columns in the FD set.
> //   8. If FD set has no key then key columns should be empty.
> //
> ```

Should we check that there are no const cols in any `from` or `to`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG6-BGRB-s9uLc0hIoU:b-op0pgw)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 36 files at r10, 1 of 3 files at r16, 31 of 31 files at r17, 1 of 3 files at r18, 2 of 2 files at r19.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LG7zpCCCYv7s-exCsM-:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm: Nice changes!

---

Reviewed 36 of 36 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 3 of 3 files at r15, 3 of 3 files at r16, 31 of 31 files at r17, 3 of 3 files at r18, 2 of 2 files at r19.
Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/props/func_dep.go, line 934 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGBynyRDjMmBwNRXRfM:-LGBy7PC21Xay8qRHLSi:b-1qnt46) ([raw file](https://github.com/cockroachdb/cockroach/blob/8af67665a69ba52f54f2eb637d5daf7f952eecac/pkg/sql/opt/props/func_dep.go#L934)):*
> ```Go
> 		fd := &fdset.deps[i]
> 		if fd.from.Empty() {
> 			f.addDependency(fd.from, fd.to, fd.strict, fd.equiv)
> ```

The comment above implies you don't need this call here. Maybe add a comment here or update the comment above.

---

*[pkg/sql/opt/props/func_dep.go, line 986 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGC1Jan8vlefoEqbpOt:-LGC1Jan8vlefoEqbpOu:b7z87rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac2632e89206bb10227b16392450d36d9b00189/pkg/sql/opt/props/func_dep.go#L986)):*
> ```Go
> 			//
> 			//   CREATE TABLE ab (a INT, b INT, PRIMARY KEY(a, b))
> 			//   SELECT * FROM ab LEFT OUTER JOIN cde ON a=c AND b=1
> ```

It's a bit odd that you only included the CREATE TABLE statement for `ab` -- why not `cde`?

---

*[pkg/sql/opt/props/func_dep.go, line 1037 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGC1kHADOWordZg6cIC:-LGC1kHADOWordZg6cID:b-v11j24) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac2632e89206bb10227b16392450d36d9b00189/pkg/sql/opt/props/func_dep.go#L1037)):*
> ```Go
> 				}
> 			} else {
> 				// Rule 2, described above (where determinant is on row-supplying side).
> ```

Isn't this actually rule #1?

---

*[pkg/sql/opt/props/func_dep.go, line 771 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGC5HCC4TbCC3QDWxkW:-LGC5HCC4TbCC3QDWxkX:b3pyveu) ([raw file](https://github.com/cockroachdb/cockroach/blob/689adf452dcbd14b68924d9832d9084bd4877d8f/pkg/sql/opt/props/func_dep.go#L771)):*
> ```Go
> // by replacing any un-projected dependants by their closures, and then removing
> // all FDs containing un-projected columns. While this algorithm may cause some
> // loss of information in edge cases, it does a good job of preserving the most
> ```

Can you give an example of an edge case?

---

*[pkg/sql/opt/props/func_dep.go, line 828 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGC4u_q0pY53hvBS1mU:-LGC4u_r5R-dGpHITkNX:b-m7n7kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/689adf452dcbd14b68924d9832d9084bd4877d8f/pkg/sql/opt/props/func_dep.go#L828)):*
> ```Go
> 	//
> 	if !constCols.Empty() {
> 		f.AddConstants(constCols)
> ```

Why is this necessary? Shouldn't constants have already been removed from all determinants by previous normalization?

---

*[pkg/sql/opt/props/func_dep.go, line 864 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGC5m-U25didzVhe6hQ:-LGC5m-U25didzVhe6hR:b-fyneny) ([raw file](https://github.com/cockroachdb/cockroach/blob/689adf452dcbd14b68924d9832d9084bd4877d8f/pkg/sql/opt/props/func_dep.go#L864)):*
> ```Go
> // While this requires O(N**2) time, it's useful when the two FD sets may
> // overlap one another and substantial simplifications are possible (as with
> // LookupJoin).
> ```

Maybe you mean IndexJoin (since these are different now)?

Also, can you add a comment to explain what the `cols` parameter is?

---

*[pkg/sql/opt/props/func_dep.go, line 1064 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGCDDURBdNbyJFFUJDs:-LGCDDURBdNbyJFFUJDt:b6ze2dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbdbf88f24fff1b45496098edb80c12693f6b8f1/pkg/sql/opt/props/func_dep.go#L1064)):*
> ```Go
> //   3. Lax equivalencies should be reduced to lax dependencies.
> //   4. Equivalence determinant should be exactly one column.
> //   5. The determinants of an equivalence is always its closure.
> ```

determinants -> dependants

---

*[pkg/sql/opt/props/func_dep.go, line 728 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGCE5e72Fi--6m8d_8r:-LGCE5e72Fi--6m8d_8s:b8g0mug) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c1120fd8a2950be738e03c07875d3d9e34c3bd/pkg/sql/opt/props/func_dep.go#L728)):*
> ```Go
> 			}
> 
> 			if fd.to.Intersects(cols) {
> ```

Why not just call `removeToCols` here? This check is redundant.

---

*[pkg/sql/opt/props/func_dep.go, line 827 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-LGCFJg89RAHlE6Rx-Zt:-LGCF8Cv2QQKF2qFiALn:b-jxtcys) ([raw file](https://github.com/cockroachdb/cockroach/blob/32c1120fd8a2950be738e03c07875d3d9e34c3bd/pkg/sql/opt/props/func_dep.go#L827)):*
> ```Go
> 
> 		// Track all columns that have equivalent alternates.
> 		if fd.equiv {
> ```

You could add another check that `fd.to.Intersects(cols)` to ensure that `makeEquivMap` is only called when it will be useful

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27046#-:-LGCIo9G1eX_hNbSMhKQ:b-2hquxa)*

**Pull request merged**
