### PR TITLE
keys,roachpb: add some high-level documentation

### PR DESCRIPTION
**Pull request by benesch**
Add some high-level documentation that explains our keyspace to package
keys's godoc. Also explain what roachpb.RKey probably stands for.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
I hope you emerged from this jungle without major bruises.

:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/keys/doc.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsleYBAWfERwJSn26y:-LAsleYBAWfERwJSn26z:bnxhern) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L62)):*
> ```Go
> // of stores, with no guarantee of collocation. Local data includes store
> // metadata, range metadata, abort cache values, transaction records,
> // range-spanning binary tree node pointers, and message queues.
> ```

There's no range-spanning binary tree. If you find remnants of it, just delete them. Same for message queues.

---

*[pkg/keys/doc.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsloFe2yrepQzSxYnX:-LAsloFe2yrepQzSxYnY:b-rqxvo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L73)):*
> ```Go
> // some local data are stored as MVCC values and are addressable as part of
> // distributed transactions, such as range metadata, range-spanning binary tree
> // node pointers, and message queues.
> ```

ditto.

---

*[pkg/roachpb/data.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAslySFEpmv1IgTpg8R:-LAslySFEpmv1IgTpg8S:b-hjmirx) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/roachpb/data.go#L75)):*
> ```Go
> // A key can be transformed to an RKey by keys.Addr().
> //
> // RKey probably stands for "resolved key," as in a key whose address has been
> ```

It does stand for resolved key.
source: am author

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-:-LAsm8FX4HEoT5ShL3h0:b64qemd)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/keys/constants.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsm-es7-PMLhJ52XGE:-LAsm-es7-PMLhJ52XGF:brn6wbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/constants.go#L23)):*
> ```Go
> )
> 
> // For a high-level overview of how the keyspace, see the package godoc.
> ```

Missing word before the comma. Refer to doc.go, since viewing this through godoc is (i think) less common in practice than looking at the code in an editor. 

---

*[pkg/keys/doc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsnRIZ3SE5e4B8WzOf:-LAsnRIZ3SE5e4B8WzOg:b2xhgaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L33)):*
> ```Go
> //
> // Non-local key types (i.e., meta1, meta2, system, and SQL keys) are
> // collectively referred to as "global" keys.
> ```

Add: The empty key (`/Min`) is a special case. No data is stored there but it is sometimes used as the starting point for a scan or the start key of the first range descriptor, in which case it acts like a global key. 

---

*[pkg/keys/doc.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsnl_6CLDrXO18KQe6:-LAsnl_6CLDrXO18KQe7:b-pe2gj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L38)):*
> ```Go
> //
> // The keyspace is divided into contiguous, non-overlapping chunks called
> // "ranges." A range is defined by its start and end keys. For example, a range
> ```

Add: Range boundaries are always global keys. 

---

*[pkg/keys/doc.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsofes4Y1IZXtyGVbs:-LAsofes4Y1IZXtyGVbt:b-45cvhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L64)):*
> ```Go
> // range-spanning binary tree node pointers, and message queues.
> //
> // The local key prefix was deliberately chosen to sort before the meta key
> ```

I'm not sure what, if anything, this sentence means (I know you're just copying it from the old docs). Local keys would work just as well with the prefix `0xff` as `0x01` (or even with a suffix). 

---

*[pkg/keys/doc.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsq1RT1vfgYxUbtC4z:-LAsq1RT1vfgYxUbtC5-:buqco03) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L68)):*
> ```Go
> // addressing indexes.
> //
> // Some local data is not replicated, such as the store's 'ident' record. Most
> ```

There are four kinds of "local" keys:
- store-local (unreplicated), typical example is the store `ident` record
- range-local unreplicated (would be better called replica-local using newer terminology), such as the raft log and replica tombstones
- unaddressable range-local replicated (often called range-id-local), such as mvcc stats and the abort span
- addressable range-local, such as the range descriptor and transaction records

---

*[pkg/keys/doc.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsrOsi1-WqBEUJEIQ5:-LAsrOsi1-WqBEUJEIQ6:b5ph36h) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L70)):*
> ```Go
> // Some local data is not replicated, such as the store's 'ident' record. Most
> // local data is replicated, such as AbortSpan entries and transaction rows, but
> // is not addressable as normal MVCC values as part of transactions. Finally,
> ```

The MVCC-ness of data is not encoded in the key. Range descriptors are MVCC and transaction records are not, but they're both the same addressable range-local key type. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-:-LAsrw8rCF1VeENW3TCq:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm: :clap: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-:-LAsyxr04Pv0HByVfmE8:bqao6p5)*

**Comment by benesch** [comment]
Thanks for the reviews! Think I've addressed everything. Going to merge, but happy to address any additional feedback in a follow-up PR.

---

Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/keys/constants.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsm-es7-PMLhJ52XGE:-LAxiD7q2AJC9_RhZMVJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/constants.go#L23)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Missing word before the comma. Refer to doc.go, since viewing this through godoc is (i think) less common in practice than looking at the code in an editor. 
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsnRIZ3SE5e4B8WzOf:-LAxiRb97yuBRCJt-3dh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L33)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add: The empty key (`/Min`) is a special case. No data is stored there but it is sometimes used as the starting point for a scan or the start key of the first range descriptor, in which case it acts like a global key. 
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsnl_6CLDrXO18KQe6:-LAxiYYkCRkuzzYVvEAE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L38)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add: Range boundaries are always global keys. 
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsleYBAWfERwJSn26y:-LAxiZia0jrwLChPJrqX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L62)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

There's no range-spanning binary tree. If you find remnants of it, just delete them. Same for message queues.
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsofes4Y1IZXtyGVbs:-LAxihblAs4VHqu_Mf40:b-lkt9zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L64)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure what, if anything, this sentence means (I know you're just copying it from the old docs). Local keys would work just as well with the prefix `0xff` as `0x01` (or even with a suffix). 
</blockquote></details>

I think this is an interesting enough point that I included it in place of this line.

---

*[pkg/keys/doc.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsq1RT1vfgYxUbtC4z:-LB2XeMP0brecQSPUDF9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L68)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There are four kinds of "local" keys:
- store-local (unreplicated), typical example is the store `ident` record
- range-local unreplicated (would be better called replica-local using newer terminology), such as the raft log and replica tombstones
- unaddressable range-local replicated (often called range-id-local), such as mvcc stats and the abort span
- addressable range-local, such as the range descriptor and transaction records
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsrOsi1-WqBEUJEIQ5:-LB2XfhC6iEiXDljP9kV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L70)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The MVCC-ness of data is not encoded in the key. Range descriptors are MVCC and transaction records are not, but they're both the same addressable range-local key type. 
</blockquote></details>

Done.

---

*[pkg/keys/doc.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAsloFe2yrepQzSxYnX:-LB2Xgkq6T4Gp_kqRboW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/keys/doc.go#L73)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.

---

*[pkg/roachpb/data.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-LAslySFEpmv1IgTpg8R:-LB2Xha4BXFgfwzaejuP:b-3cekw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/42143fbca019eb082f064bafa27c0bebe438102f/pkg/roachpb/data.go#L75)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

It does stand for resolved key.
source: am author
</blockquote></details>

Well that sure clears things up. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25032#-:-LB2Xjt9A6HHeWsANvzL:b-l7tv0x)*

**Comment by benesch** [comment]
bors r=tschottdorf,a-robinson,bdarnell

**Comment by benesch** [comment]
bors r=tschottdorf,a-robinson,bdarnell

**Comment by tschottdorf** [comment]
For posterity, the failed build failed on lint because of missing copyright headers.

**Pull request merged**
