### PR TITLE
sql: store offsets in JSON arrays and objects

### PR DESCRIPTION
**Pull request by justinj**
Still to come is the optimizations for seeking in an encoded object, rather than just arrays.

### CODE REVIEW

**Comment by m-schneider** [comment]
Review status: 0 of 88 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/json/encode.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-L0Gu4CLehpqzBGr-HYN:-L0Gu4CLehpqzBGr-HYO:bae97t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bae3bff5cf56d8ed7b3070cc10f63510650bbb6/pkg/util/json/encode.go#L82)):*
> o
This would encode  every other entry as a length? Also how did you choose the length of the stride?

---

*[pkg/util/json/encode_test.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-L0GpoOF1RbA9toJOBh2:-L0GpoOF1RbA9toJOBh3:b-4wyuqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bae3bff5cf56d8ed7b3070cc10f63510650bbb6/pkg/util/json/encode_test.go#L197)):*
> ```Go
> 		assertEncodeRoundTrip(t, j)
> 	}
> ```

nit: blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645)*

**Comment by justinj** [comment]
Review status: 0 of 88 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/json/encode.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-L0Gu4CLehpqzBGr-HYN:-L0KzF8AqBjMSJESmBX-:b-rryexr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bae3bff5cf56d8ed7b3070cc10f63510650bbb6/pkg/util/json/encode.go#L82)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

> o
This would encode  every other entry as a length? Also how did you choose the length of the stride?
</blockquote></details>

Every 32nd one is an offset and all others are a length, yeah. This is the same value Postgres chose, but I think there remains to be some benchmarking/weighing of values to determine if that value is also sensible for us.

---

*[pkg/util/json/encode_test.go, line 197 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-L0GpoOF1RbA9toJOBh2:-L0KzNuCPXxzI6vWrQaF:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bae3bff5cf56d8ed7b3070cc10f63510650bbb6/pkg/util/json/encode_test.go#L197)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

nit: blank line
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645)*

**Comment by m-schneider** [comment]
:lgtm:

---

Review status: 0 of 88 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/json/encode.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-L0Gu4CLehpqzBGr-HYN:-L0M1aINMl_WEQHps4M-:b-69k4kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bae3bff5cf56d8ed7b3070cc10f63510650bbb6/pkg/util/json/encode.go#L82)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Every 32nd one is an offset and all others are a length, yeah. This is the same value Postgres chose, but I think there remains to be some benchmarking/weighing of values to determine if that value is also sensible for us.
</blockquote></details>

Ok cool!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-:-L0M1coRfL8N4QHMb-TK:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm: ship it!

---

Review status: 0 of 88 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20645#-:-L2Y6pg77j65Z00Ui-Y0:b-quxs7z)*

**Comment by justinj** [comment]
TFTRs!

**Pull request merged**
