### PR TITLE
sqlccl: backup/restore progress updating fixes

### PR DESCRIPTION
**Pull request by benesch**
See individual commit messages for details.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14607)

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/progress.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu6QcMK-nDr9-fXPxb:-Kgu6QcMK-nDr9-fXPxc:b347c1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/92d8fd100912cfb512d49250f5293ac3f73c5466/pkg/ccl/sqlccl/progress.go#L53)):*
> ```Go
> 	shouldLogProgress := fraction-jpl.mu.lastReportedFraction > progressFractionThreshold ||
> 		jpl.mu.lastReportedAt.Add(progressTimeThreshold).Before(timeutil.Now())
> 	if shouldLogProgress {
> ```

This is easier for me to reason about with one Unlock and two `if shouldLogProgress`s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-:-Kgu6XSLNfwlhOMYyjcI:bnfp4nl)*

**Comment by danhhz** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/progress.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu6QcMK-nDr9-fXPxb:-Kgu70NoVak6Z5IAXxKw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92d8fd100912cfb512d49250f5293ac3f73c5466/pkg/ccl/sqlccl/progress.go#L53)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This is easier for me to reason about with one Unlock and two `if shouldLogProgress`s
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/progress.go, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu6yKlW6gC7ziREQ9n:-Kgu6yKmQp4M9L1CH9Nz:b-7bxsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/45696c5df55696da7c272ad808d234dc813dd943/pkg/ccl/sqlccl/progress.go#L57)):*
> ```Go
> 		// NOTE: We intentionally hold the lock while updating system.jobs to ensure
> 		// progress updates are written in order.
> 		jpl.mu.lastReportedAt = timeutil.Now()
> ```

is this testable?

---

*[pkg/sql/jobs.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu7LmkG01KYH3TG76z:-Kgu7LmlKQtcc2VINWb_:b-7hghro) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d1782e873e17d888688b1ccb776f7e0f0a0d8d/pkg/sql/jobs.go#L204)):*
> ```Go
> 
> func (jl *JobLogger) updateJobRecord(
> 	ctx context.Context, newStatus JobStatus, updateFn func(payload *JobPayload) (bool, error),
> ```

nit: the name `payload` is not necessary in this signature. Consider extracting this as a type alias so that you can document the bool return.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by benesch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/progress.go, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu6yKlW6gC7ziREQ9n:-Kgu8Imk5jNw9BuTEc64:b-88j6tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/45696c5df55696da7c272ad808d234dc813dd943/pkg/ccl/sqlccl/progress.go#L57)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this testable?
</blockquote></details>

Not without a lot of stubbing/mocking/constant-mutation pain, which @danhhz and I were trying to avoid.

---

*[pkg/sql/jobs.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu7LmkG01KYH3TG76z:-Kgu8IGnTctZgp4m_QyO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d1782e873e17d888688b1ccb776f7e0f0a0d8d/pkg/sql/jobs.go#L204)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: the name `payload` is not necessary in this signature. Consider extracting this as a type alias so that you can document the bool return.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/jobs.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu7LmkG01KYH3TG76z:-Kgu8tFJaVkCitvip1lP:b-nrbgox) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d1782e873e17d888688b1ccb776f7e0f0a0d8d/pkg/sql/jobs.go#L204)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, I meant a comment, but this works too. You can skip the type alias in this case - it was only so that you'd have something to hang the comment on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by benesch** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/jobs.go, line 204 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607#-Kgu7LmkG01KYH3TG76z:-KguA5QNQHR62ylftgV0:b-3j4jod) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d1782e873e17d888688b1ccb776f7e0f0a0d8d/pkg/sql/jobs.go#L204)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Oh, I meant a comment, but this works too. You can skip the type alias in this case - it was only so that you'd have something to hang the comment on.
</blockquote></details>

Gotcha, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14607)*

**Pull request merged**
