### PR TITLE
execinfrapb: print out input types for EXPLAIN (DISTSQL, TYPES)

### PR DESCRIPTION
**Pull request by yuzefovich**
This change adds printing out the column types for InputSyncSpec in the
flow diagram. This could be useful to understand the issue when a type
mismatch occurs.

Release note (sql change): Column types will now be displayed in the box
for the input synchronizer in the flow diagram obtained via EXPLAIN
(DISTSQL, TYPES).

### CODE REVIEW

**Comment by RaduBerinde** [comment]
How often do you think this will be useful? It adds a bit more clutter to already cluttered diagrams, and it makes the URLs longer. If it's just to debug specific cases, we could consider having an `EXPLAIN (DISTSQL, TYPES)` version (we already support the `TYPES` keyword).

**Comment by yuzefovich** [comment]
I don't think it'll be useful very often, and I like your suggestion about `TYPES` keyword (I was thinking about `VERBOSE`, but `TYPES` seems better), so I'll look into it.

**Comment by yuzefovich** [comment]
Updated the PR, RFAL.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43193#-:-LwKtQ8cB_5gb0xKQh36:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
