### PR TITLE
Store the version of key addressing used in each TableDescriptor

### LINKED ISSUE #4994: sql: add data format version number to TableDescriptor
See #4499. The format of the SQL to KV mapping needs to be stored in the `TableDescriptor`. Old software should refuse to read table data that has a version it doesn't support. New software should be able to read old versions and ensure it is writing out the correct format. We don't need any of the mechanism to handle different data formats at this point, just the version number and a check in the code that the value matches the only supported version we have at this point.

### PR DESCRIPTION
**Pull request by danhhz**
Check it when the table is used. For now, just error out when they don't match exactly.

Fixes #4994.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5095)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/structured.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCWqIZVcFW1bCS8geFy:-KCWqIZVcFW1bCS8geFz:-242211586) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad848246c97763619003002a2edae700ba0a18f/sql/structured.go#L486)):*
Reviewers, thoughts on the following?

On one hand, Validate seems like it isn't the right place for this. Checking this right before we do the mapping in select/update/truncate/etc may be more correct.

On the other hand, it works and as far as I can tell is a single point that is in every relevant codepath. More importantly, at the point that we're changing the sql to keyval mapping (aka adding our second version), we'll probably need some logic for backwards compatibility everywhere the mapping is done, and the version check could easily be moved then.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095)*

**Comment by petermattis** [comment]
This looks almost exactly like what I was thinking. I'd just like to find a better name than `KeyAddressingVersion`.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/structured.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCWtI31U0kocf8j7-xc:-KCWtI31U0kocf8j7-xd:1329866607) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad848246c97763619003002a2edae700ba0a18f/sql/structured.go#L48)):*
You can `go:generate stringer` this type. More important once the constants have descriptive names.

---

*[sql/structured.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCWt0XUDrsf7Uh-c1N1:-KCWt0XUDrsf7Uh-c1N2:764757443) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad848246c97763619003002a2edae700ba0a18f/sql/structured.go#L56)):*
I'd prefer to use descriptive names here, such as `BaseVersion`, `ForeignKeysVersion`, `InterleavedTablesVersion`, etc.

---

*[sql/structured.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCWqIZVcFW1bCS8geFy:-KCWruIereqks_wFoesZ:1604990373) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad848246c97763619003002a2edae700ba0a18f/sql/structured.go#L486)):*
I think it is fine to place this here, though I might move this check to the beginning of `Validate`.

---

*[sql/structured.proto, line 251 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCWsHU7xuR9yDnXAdvY:-KCWsHU7xuR9yDnXAdvZ:-532188321) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ad848246c97763619003002a2edae700ba0a18f/sql/structured.proto#L251)):*
I'd like a more general name than this, such as `format_version`. Key addressing is a major thing we have to version, but there are others which we could squeeze in here as well which aren't actually related to the key addressing. For example, "foreign keys" don't require a change to key addressing (AFAIK), but we wouldn't want to manipulate a table which had foreign keys with a server that didn't know about them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-:-KCWstigfAP3hFDBQLWp:-2019894417)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[sql/structured.go, line 49 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Z8rkeqe7cDzsbpf:-KCX1Z8rkeqe7cDzsbpg:413243722) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L49)):*
does this need to be exported?

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Wv5zsh_XuqSQXcW:-KCX1Wv6c-uputBsLKdy:845862576) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
you could use iota here to avoid manually numbering these.

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1aD4X8paI9nouQEp:-KCX1aD4X8paI9nouQEq:-202356401) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
do these variants need to be exported?

---

*[sql/structured.go, line 380 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Uz-7xSvtT2QfNrf:-KCX1Uz-7xSvtT2QfNrg:87404355) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L380)):*
be sure to emit the encoded version and either all the supported versions or the highest supported version (highest supporting version would be fine if we used iota above since versions will be non-sparse by definition).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095)*

**Comment by paperstreet** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 49 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Z8rkeqe7cDzsbpf:-KCX2SAvI4isxaj0QxgE:889785288) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L49)):*
They're used in package sql_test

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Wv5zsh_XuqSQXcW:-KCX5SAVXIRu_9M6BRIu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
Done.

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1aD4X8paI9nouQEp:-KCX5T9vfZgn45-wWjFr:889785288) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
They're used in package sql_test

---

*[sql/structured.go, line 380 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Uz-7xSvtT2QfNrf:-KCX6aZC6G6GoiFGfKi7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L380)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Wv5zsh_XuqSQXcW:-KCXDbrnf6ZvtoR8CJjC:-1972293510) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
publish before push?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095)*

**Comment by paperstreet** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/structured.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095#-KCX1Wv5zsh_XuqSQXcW:-KCXFkiM0_KEZ6M5Zybh:-481359127) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeb2d9f95d1c984ad7c7496a3bc781913a4d9e5b/sql/structured.go#L54)):*
doh! it was sitting around unstaged

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5095)*

**Pull request merged**
