### PR TITLE
kv: Return descriptor hint in RangeKeyMismatchError

### LINKED ISSUE #5880: kv: Investigate not specifying RangeID on post-split requests
The `Stores` struct currently supports the ability to [lookup a replica](https://github.com/cockroachdb/cockroach/blob/master/storage/stores.go#L184) for a given key when a RangeID is [not included](https://github.com/cockroachdb/cockroach/blob/master/storage/stores.go#L132) in a `BatchRequest`. However, this is currently only ever used in tests. 

We should look into if we can take advantage of this behavior when a split is detected. In practice, this would mean that `DistSender` would not specify a RangeID on `BatchRequest` where an initial range miss is inferred as a split. Instead it should send to the same `Node` as the missed `Range` and have the store discover the correct new `Range`, which it will include in the `BatchResponse` so that the `RangeCache` could be corrected. This is possible because a replica will split in-place, so there is a very high likelyhood that when a split is detected, the new range will be on the same store as the old range.

An alternative would be for `Store` to "catch" `RangeKeyMismatchError`s and perform a best-effort RangeLookup before returning the error.

### PR DESCRIPTION
**Pull request by nvb**
Resolves #5880.

This change makes `Replica` perform a best-effort lookup for the correct
range in the case of `RangeKeyMismatchError` and provide this as a hint
to `DistSender` for where to look next.

The change doesn't yet include a "replica creation timestamp" as I wasn't
convinced that was needed (but also wasn't convinced it wouldn't be a
nice indicator to have). I'm hoping to get some input on this.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5911)

### CODE REVIEW

**Comment by tschottdorf** [comment]
@bdarnell is best qualified to comment on my suggestion about the replica creation timestamp. The reason I brought it up was because I was worried that an old range may not be GCed for a while and, repeatedly being returned with this new code here, could confuse DistSender (which at the moment takes hints pretty seriously). Though it's not clear to me whether it could repeatedly be returned (`DistSender` would do an authoritative lookup next, so the situation should rectify itself at that point).

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[kv/dist_sender.go, line 667 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjqU7xRo9dEoeoL3Cu:-KEjqU7y7Wg7iT_N_zoG:1109265949) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L667)):*
`s/Front/First/`? The term "front" has a direction to it which in my mind suggests it's the `c` in `Scan[a,c)` (because a normal scan moves "to the right").

---

*[kv/dist_sender.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjqpE2b_wNIFpBC8tI:-KEjqpE2b_wNIFpBC8tJ:-834595509) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L670)):*
should double-check that `[b,c).ContainsKeyRange(b, a)` doesn't do unexpected things (i.e. that `ContainsKeyRange($1, $2) == false` for all `$1 >= $2`.

---

*[kv/dist_sender.go, line 731 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjrftqG47xTOFEQ2v9:-KEjrLtNHDYjndAx2Jap:-1075104094) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L731)):*
Add comment about likely culprit being a rebalance.

---

*[kv/dist_sender.go, line 750 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjraimia3SFjkozn_y:-KEjraimia3SFjkozn_z:1041819745) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L750)):*
Add a small comment that this would likely happen on a Split.

---

*[kv/dist_sender_test.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjs7P13HmP4NaZpoiv:-KEjs7P13HmP4NaZpoiw:1458277882) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender_test.go#L660)):*
Can this new (and somewhat copy-pasta) test replace the one just above? After all, it's testing the same and more. That would make the changes easier to spot as well.

---

*[kv/range_cache.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjslmC8in9bf43gwbz:-KEjslmDWaRLvvzPd2to:320314351) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/range_cache.go#L232)):*
nit:

> When called without arguments, EvictAndReplace will behave the same as Evict`.

is a bit more correct (there's a `newDescs` slice, but only kind of).

---

*[storage/replica.go, line 791 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjtDOyvzQBFpJpN81s:-KEjtDOyvzQBFpJpN81t:387934974) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/storage/replica.go#L791)):*
`s/rkme/mismatchErr/` (or anything with an `Err` suffix)

This is untested as far as I can tell?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-:-KEjojsl5zQ6ltnzOEDC:538846740)*

**Comment by bdarnell** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[storage/replica.go, line 797 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEl_rbM5pT-SdnOR6Dt:-KEl_rbN82IV9o22w-h1:1950284742) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/storage/replica.go#L797)):*
Per my comment on #5880, we may want to set `SuggestedRange` only when a leader is known. (i.e. `repl.getLease()` is non-nil and `lease.Covers(clock.Now())`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911)*

**Comment by nvanbenschoten** [comment]
Review status: 7 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 667 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjqU7xRo9dEoeoL3Cu:-KEmkyudd1pgJb3syqi3:370332661) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L667)):*
What I was going for here was that during this outer loop we're trying to chop away at the front (in the context of the request direction) of the current key range. First seems to imply left to me, which confuses a reverse search. That said, I completely get where you're coming from. Does "Beginning" work?

---

*[kv/dist_sender.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjqpE2b_wNIFpBC8tI:-KEmmBEuDsKZ6kSa6LhF:-1274197723) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L670)):*
As long as the start and end keys aren't inverted, it seems to make sense.

---

*[kv/dist_sender.go, line 731 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjrftqG47xTOFEQ2v9:-KEmmXpr8Ms1miwYgXzO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L731)):*
Done.

---

*[kv/dist_sender.go, line 750 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjraimia3SFjkozn_y:-KEmntlh8x-dhdRItCgy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender.go#L750)):*
Done.

---

*[kv/dist_sender_test.go, line 660 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjs7P13HmP4NaZpoiv:-KEmpO8PYUxxXAvq3_NH:443778910) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/dist_sender_test.go#L660)):*
I dont think they're quite testing the same thing. The one above is testing that after a `RangeKeyMismatchError` without a suggestion `DistSender` will perform another `LookupRequest`. This one is testing that it wont if the `RangeKeyMismatchError` includes a hint. Seems worthwhile to keep both tests.

---

*[kv/range_cache.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjslmC8in9bf43gwbz:-KEmpsUXzP8P9OBppUvd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/kv/range_cache.go#L232)):*
Done.

---

*[storage/replica.go, line 791 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEjtDOyvzQBFpJpN81s:-KEmy9FT6xxJ29x5szuD:-1463562567) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/storage/replica.go#L791)):*
Done. And added a test for both the `MismatchedRange` and `SuggestedRange` in the `RangeKeyMismatchError`.

---

*[storage/replica.go, line 797 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KEl_rbM5pT-SdnOR6Dt:-KEmyEfH5_eNjqXpHZF1:-1844596946) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5bd491394ecd27d2f6af1753b6d8aee53ab493/storage/replica.go#L797)):*
Perfect, that seems like it should work well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 5 of 7 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[kv/range_cache.go, line 232 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KErfU4AreJ5B_WKDMYf:-KErfU4AreJ5B_WKDMYg:2000231645) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbc930c267a42c9e632fe5f131b0a13cd57dc18/kv/range_cache.go#L232)):*
Get rid of the stray backtick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-:-KErfnkEIW2IaoQMRu5M:676834233)*

**Comment by nvanbenschoten** [comment]
Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[kv/range_cache.go, line 232 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911#-KErfU4AreJ5B_WKDMYf:-KEsvK4gQqa7G-SaBfmS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecbc930c267a42c9e632fe5f131b0a13cd57dc18/kv/range_cache.go#L232)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5911)*

**Pull request merged**
