### PR TITLE
kvserver: introduce blocking vfs.FS; add some tests

### PR DESCRIPTION
**Pull request by tbg**
edit: with the third commit in place, the test in 2) now passes.

----

This introduces a `vfs.FS` implementation that can be toggled to block
on any write activity.

Add two tests:

1. check that even though a durable commit is inflight, we can still
   write non-durably. I.e. at the pebble level there is no immediate
   reason why we couldn't keep *applying* the raft log even though log
   *appends* are stuck.
2. end-to-end test where we set up a three node cluster, send unique
   writes and stall the leaseholder's disk, hoping for the writes to
   keep going through. This fails, as is expected, because raft does
   not even put up entries for application if they haven't been durably
   appended to the leader's log (which they can't be due to the stall
   we're injecting).

If we can get 2) to pass, we can have reason to believe that we can
address #88699 (though we'd need to verify with "real" disk stalls
and higher write volumes/stall durations and would certainly need to
configure pebble to allow much more data to accumulate in memory).

The additional benefit test 2) provides is that it prints who is
blocked. At the time of writing, it's encouraging - we see just
the LogWriter blocked on a call to `Write` (via `flushPending`).

The next step would be to hack in the ability to apply entries
that aren't durable on the leader and to see what we get.

Touches #88699.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
cc @jbowens @nvanbenschoten @erikgrinaker since we talked about #88699.

[(Internal) Slack thread](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1679000081743509)

**Comment by tbg** [comment]
From the above Slack thread:

> I got raft patched to also put up entries for application that are committed via a non-local quorum, and magically things work.. until the ~257th write, then it stalls:

Jackson then had some responses on where the stalls would be.

At this point I'm going to disengage from the prototype, we can pick this back up if we're interested in making progress in earnest. There seems to be reason to believe that with some pebble work we can possibly mask short disk stalls or latency degradations without necessarily exposing them to users. What's unexplored is how "real" disk stalls affect disk _reads_. We need to be doing all pebble reads out of the cache during evaluation and replication or requests get stuck anyway.

**Comment by tbg** [comment]
Closing: the work is tracked in https://github.com/cockroachdb/cockroach/issues/88699.

@jbowens any interest in putting the blocking vfs.VFS anywhere? I'm not sure how disk stalls are being tested right now, I epxected something similar to exist for that use case but it doesn't seem to.

**Comment by jbowens** [comment]
Yeah, maybe we should start a `pebble/vfs/vfstest` package that can be consumed within both Pebble and Cockroach. Our current disk stall unit tests use a completely mocked fs: [vfs/disk_health_test.go](https://github.com/cockroachdb/pebble/blob/5d60d312f3ba441b518051d16c6325aec8ef56a0/vfs/disk_health_test.go#L74)

IIRC, there's also a few tests that use [errorfs](https://github.com/cockroachdb/pebble/blob/master/internal/errorfs/errorfs.go) and a custom [InjectorFunc](https://github.com/cockroachdb/pebble/blob/5d60d312f3ba441b518051d16c6325aec8ef56a0/internal/errorfs/errorfs.go#L138-L140) to induce blocking. We could also move `errorfs` out of the internal package so that it can be used by cockroach.

**Pull request closed without merging**
