### PR TITLE
docs: add MVCC range tombstones tech note

### LINKED ISSUE #83406: docs: add tech note for MVCC range tombstones
See doc comment on `SimpleMVCCIterator` for an early outline.

Jira issue: CRDB-17056

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
[Rendered version](https://github.com/cockroachdb/cockroach/blob/e67e47f72225da1e4b4b895814a4661d3c1a96a3/docs/tech-notes/mvcc-range-tombstones.md)

---

This describes the current state, but the details will likely change as
we iterate on the implementation.

Resolves #83406.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@nicktrav As we discussed in the meeting last week, here's the high-level tech note (MVCC and above) for MVCC range tombstones. Let me know when we have something for Pebble range keys, and I'll link it from here -- I figure including low-level implementation details here is probably not useful to most readers, but let me know if you feel otherwise.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-:-N6DkfOW20LR4EYlSxyb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @erikgrinaker, @itsbilal, @jbowens, and @nicktrav)

___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DaIyp3X28sXUR3mn2:-N6DaIyp3X28sXUR3mn3:b4gaz4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L105)):*
> ```Markdown
> ```
> Time
> 5  a5  b5
> ```

worth clarifying that a5 is the value for a@5 and so on.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DQphy6e57h6LnFBNo:-N6DQphy6e57h6LnFBNp:bzfwpem) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L126)):*
> ```Markdown
> MVCC iteration later.
> 
> In the KV API, however, this distinction doesn't really matter: `Get(c)` would
> ```

worth saying what read timestamp this Get is using.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6D_ega7N9_DFJRrCBk:-N6D_ega7N9_DFJRrCBl:bhd87ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L231)):*
> ```Markdown
> A notable and unfortunate implementation detail is that these KV mutations must
> take out a latch that is slightly wider than the written span (e.g.
> `EndKey.Next()`) in order to look for any surrounding MVCC range keys that might
> ```

how is the start key widened?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dco2w2_pLjb3JBMzN:-N6Dco2w2_pLjb3JBMzO:b-9ezjxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L385)):*
> ```Markdown
> it it has no existing point keys: a get of `bar` would return `bar@4` and
> `bar@2` even though there is no real point key at `bar`, as this might be
> required e.g. for conflict checks. These synthetic tombstones would similarly
> ```

why is an MVCCGet returning multiple versions for the same key?
Also, worth saying what timestamp this get is operating at (and similarly for the MVCCScan description earlier).
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6De9fh-qZJZfkOSymt:-N6De9fh-qZJZfkOSymu:b-xks71l) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L405)):*
> ```Markdown
> 
> * `RangeKeyCount`: The number of MVCC range key fragment stacks, i.e. ignoring
>   historical versions.
> ```

this includes fragmentation caused by historical versions, yes?
That is, if we have [a,z)@10, and [b,c)@5, [d,e)@5, we would have fragmentation into [a,b)@10, [b,c)@10, [c,d)@10, [d,e)@10, [e,z)@10, so it would count as 5? If yes, could you enhance the example below to clarify this.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dep0gAWQRE0o8VEmp:-N6Dep0gAWQRE0o8VEmq:b-gvladc) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L430)):*
> ```Markdown
> 
> * `RangeKeyCount`: 3 (`[a-b)`, `[b-c)`, and `[c-d)`).
> * `RangeKeyBytes`: 48 (3 * 2 * 2 for encoded key bounds `a`, `b`, `b`, `c`,
> ```

where does this last *2 come from. Is it the \x00 sentinel byte?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dgn026jCTrFkcI_nq:-N6Dgn026jCTrFkcI_nr:b-9yw75e) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L510)):*
> ```Markdown
> example, if there is a range tombstone `[b-d)@2`, and iteration stops between
> `c@3` and `c@1`, returning a resume span at `c@1`, then the previous SST will
> contain `[b-c\0)@2` and the next SST will contain `[c-d)@2`. This ensures that
> ```

This is ugly, but I can see why you had to do this.
Were there any alternatives considered?
And I am puzzled by the following comment in the code, regarding "allow this overlap". AddSSTable is adding a single sstable, so the usual non-overlap rule in `DB.Ingest` is trivially satisfied. Were there any Pebble changes made to allow for overlap when ingesting multiple sstables?
```
	// NB: If the result contains MVCC range tombstones, this can cause MVCC range
	// tombstones in two subsequent SSTs to overlap. For example, given the range
	// tombstone [a-f)@5, if we return a resume key at c@3 then the response will
	// contain a truncated MVCC range tombstone [a-c\0)@5 which covers the point
	// keys at c, but resuming from c@3 will contain the MVCC range tombstone
	// [c-f)@5 which overlaps with the MVCC range tombstone in the previous
	// response for the interval [c-c\0)@5. AddSSTable will allow this overlap
	// during ingestion.
	StopMidKey bool
```
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DjQn7CkmkG8luzGim:-N6DjQn8A6DcunfuwsM-:b-wheeix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L538)):*
> ```Markdown
> There will be no corresponding point key events: it is up to the consumer to
> apply these to relevant point keys as appropriate. However, rangefeeds with
> diffs enabled will respect the MVCC range tombstone as the previous (empty)
> ```

The diff semantics are somewhat unclear to me.
When the point key is the latest and the prev is the range key, will the latter show as a synthesized point key?
If the range key is the latest, is the with-diff ignored -- maybe that's what you meant by "no corresponding point key events".
Do we know how customers use changefeeds with-diff and how will they be affected?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DkBjsELtlniBrLT7S:-N6DkBjtBglJTzX7fM4i:b-jy5fi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L554)):*
> ```Markdown
> CDC will not need to take these into account yet, because the two initial
> use-cases (SQL schema GC and import cancellation) take the tables offline and
> prevent CDC changefeeds across them (including later catchup scans). However,
> ```

I suppose this answers my previous question.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DkSAT2YMZKM8I4O_l:-N6DkSAT2YMZKM8I4O_m:b6a3trv) ([raw file](https://github.com/cockroachdb/cockroach/blob/32881180a75ba676064ff55756035eb91f0fda79/docs/tech-notes/mvcc-range-tombstones.md#L468)):*
> ```Markdown
> However, MVCC range tombstones also allow for much more efficient GC using
> Pebble range deletes rather than Pebble point deletes when there is no live data
> above it. This optimization will is not yet implemented, but will be necessary
> ```

something wrong with this sentence: ... will is ...

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @10, @5, @aliher1911, @itsbilal, @jbowens, @nicktrav, and @sumeerbhola)

___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DaIyp3X28sXUR3mn2:-N6DnA6U3zB3IKN0-gQ7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L105)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

worth clarifying that a5 is the value for a@5 and so on.
</blockquote></details>

Done.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DQphy6e57h6LnFBNo:-N6DnMZp69FE4lFC8F7X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L126)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

worth saying what read timestamp this Get is using.
</blockquote></details>

Done.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6D_ega7N9_DFJRrCBk:-N6DnNCjAhwemLyTPbe0:b-ngdrgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L231)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how is the start key widened?
</blockquote></details>

This, unfortunately:

https://github.com/cockroachdb/cockroach/blob/566dff233d94aa18e2f9e53cdf888adf9ee22d53/pkg/roachpb/data.go#L166-L179 
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dco2w2_pLjb3JBMzN:-N6Do03fA9B7rESpYz9E:b-zf7c62) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L385)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is an MVCCGet returning multiple versions for the same key?
Also, worth saying what timestamp this get is operating at (and similarly for the MVCCScan description earlier).
</blockquote></details>

It shouldn't, thanks. I keep thinking of this from the iterator point of view (which surfaces historical versions), rather than the get/scan point of view.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 405 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6De9fh-qZJZfkOSymt:-N6DqbLl6lKIpcoXyR7d:b-9f087b) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L405)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this includes fragmentation caused by historical versions, yes?
That is, if we have [a,z)@10, and [b,c)@5, [d,e)@5, we would have fragmentation into [a,b)@10, [b,c)@10, [c,d)@10, [d,e)@10, [e,z)@10, so it would count as 5? If yes, could you enhance the example below to clarify this.
</blockquote></details>

Yep, done.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dep0gAWQRE0o8VEmp:-N6Dqcr03C95h9c1w9lV:bpabwmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L430)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where does this last *2 come from. Is it the \x00 sentinel byte?
</blockquote></details>

It is, made this explicit.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Dgn026jCTrFkcI_nq:-N6Dqlsk2gjtNnsK26iv:bak7ora) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L510)):*
>Were there any alternatives considered?

We originally discussed this back in https://github.com/cockroachdb/cockroach/pull/76131#pullrequestreview-878949046 and related Slack discussions. We considered e.g. exporting range keys separately from point keys and such, but ended up preferring this approach since we expect there to be 0 range keys in the typical case.

> And I am puzzled by the following comment in the code, regarding "allow this overlap". AddSSTable is adding a single sstable, so the usual non-overlap rule in DB.Ingest is trivially satisfied. Were there any Pebble changes made to allow for overlap when ingesting multiple sstables?

Right, this may turn out not to be an issue. I though we might have to add handling in `CheckSSTConflicts` such that it wouldn't conflict with itself, but this is only relevant when we're backfilling MVCC history (otherwise we're writing at the current timestamp), and in that case we won't even check for conflicts.

Furthermore, for backup specifically, we won't ingest MVCC range tombstones at all; we'll only ingest live data, but we'll have to read the MVCC range tombstones from the SSTs to build the live data view, in which case I believe the Pebble SST iterator will already merge these automatically.

I'll write some tests around this and make sure it works as expected, then update the comment and doc.

>Were there any Pebble changes made to allow for overlap when ingesting multiple sstables?

Not that I'm aware of.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DjQn7CkmkG8luzGim:-N6DwPZb4O-wqfesagrF:bpmd6fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/afee3ecf3fa9b61d9dd22f39053fa8cd54471bdb/docs/tech-notes/mvcc-range-tombstones.md#L538)):*
> When the point key is the latest and the prev is the range key, will the latter show as a synthesized point key?

Yes. The main point is that if we have a real point key at `b@1` covered by `[a- c)@2`, then writing `b@3` will emit an event with a previous value that's empty rather than the value of `b@1`, as one would expect. Update the text with this example.

> Do we know how customers use changefeeds with-diff and how will they be affected?

As you found below, changefeeds won't currently be affected.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 468 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DkSAT2YMZKM8I4O_l:-N6Dqjw24FxApusyLll4:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/32881180a75ba676064ff55756035eb91f0fda79/docs/tech-notes/mvcc-range-tombstones.md#L468)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

something wrong with this sentence: ... will is ... 
</blockquote></details>

Thanks, fixed.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-:-N6Eb7hcDeKJCmWdBbAX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @10, @5, @aliher1911, @erikgrinaker, @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6DzSf_DmPiRLRo05-4:-N6DzSf_DmPiRLRo05-5:b-m7z6yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/32881180a75ba676064ff55756035eb91f0fda79/docs/tech-notes/mvcc-range-tombstones.md#L183)):*
> ```Markdown
> * `PutMVCCRangeKey(MVCCRangeKey, MVCCValue)`:  Writes the given range key
>   with the given value. Replaces any existing range key(s) within the keyspan
>   and timestamp. Errors if the value is not a tombstone.
> ```

nit: maybe "within the keyspan and at an identical timestamp"?[
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6EGrKc7oSCM_Lh94ZE:-N6EGrKc7oSCM_Lh94ZF:btczxae) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L387)):*
> ```Markdown
> 
> Additionally, an `MVCCGet` will emit a synthetic point tombstone for the key
> even it it has no existing point keys: `Get(bar)` at timestamp >= 4 would return
> ```

nit: s/it it/if it/

**Review by nicktrav — APPROVED** [review]
This makes for great reading. Thank you for putting it together! :lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-:-N6GPSLdCmq-g7t1rfel:b-ujy8s3)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @10, @5, @aliher1911, @erikgrinaker, @itsbilal, and @sumeerbhola)

___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6Eg0JJ9_wbJ1L9l2GF:-N6EfTgtDEhvX6tatyH5:beotpzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L259)):*
> ```Markdown
> The properties of point and range keys are accessed via:
> 
> * `HasPointAndRange()`: whether the current position has a point and/or
> ```

nit: can we specify here that this returns a `(bool, bool)` tuple? The reader may assume this is a single `bool`, then be confused to encounter the tuple in the examples.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6EhV2gEW4iVFG7CfTy:-N6EhV2gEW4iVFG7CfTz:b-f5w5di) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L299)):*
> ```Markdown
> last in this example.
> 
> When using `SeekGE` within range key bounds, the iterator may land on the bare
> ```

Might be useful to have a case where there's a point key with _no_ covering range key (i.e. the existing, pre-range key case), and therefore the seek will "move up" to the point key, rather than stopping at the range key lower bound. For example, `SeekGE(e@5)` if there was an `e1` with no covering range key. 

Maybe that's obvious, in which case perhaps just mention it in writing, for completeness?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GHBgr9eDAqojf8Rjb:-N6GHBgr9eDAqojf8Rjc:byq5ayy) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L315)):*
> ```Markdown
> | `c@2`    | `c@2`       | `false`, `true`    |               | `[b-d)@4`, `[b-d)@2` |
> 
> The same is not true for `SeekLT`: when using it within range key bounds, it
> ```

Worth an additional, tabulated example, to underscore the difference in the SeekLT case? Or even just a subset of the above operations that would demonstrate wherein difference lies.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GIjgz6RTmLtZLWjQs:-N6GIjgz6RTmLtZLWjQt:b-amvoyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L349)):*
> ```Markdown
> Additionally, `EngineIterator` has corresponding functionality for processing
> raw Pebble range keys, but these are primarily intended for low-level use,
> e.g. when building Raft snapshots.
> ```

Worth adding a brief, final paragraph with something like "When in doubt, use X iterator implementation with Y settings"?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GKwUvBfmOk07XF36H:-N6GKwUvBfmOk07XF36I:bh2hud4) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L464)):*
> ```Markdown
> ## MVCC Garbage Collection
> 
> This is still under development, but once complete, MVCC range tombstones will
> ```

Curious - are you planning on going back and updating this note once GC is done? Or publishing a new note for GC?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GLn4jE4kzRwyo4Vil:-N6GLn4jE4kzRwyo4Vim:b-u2359o) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L487)):*
> ```Markdown
> `Writer` section above for details.
> 
> However, the old `SSTIterator` does not support range keys, as it is built on a
> ```

Are we tracking the removal of this "old" iterator impl?
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GO6WW4e_mcw5h5CXC:-N6GO6WW4e_mcw5h5CXD:bvlndgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L575)):*
> ```Markdown
> building them in the first place.
> 
> ## Related Reading
> ```

We also have cockroachdb/pebble#1341, which we intend to land as the "official RFC" for Pebble range keys (despite it being finalized after we implemented range keys). Not sure if / how you want to incorporate here. We could also just loop back and add a reference to RFC in its final form once we land it.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @10, @5, @aliher1911, @itsbilal, @nicktrav, and @sumeerbhola)

___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6EhV2gEW4iVFG7CfTy:-N6I45R418mMUTSqGyae:bb5xcir) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L299)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Might be useful to have a case where there's a point key with _no_ covering range key (i.e. the existing, pre-range key case), and therefore the seek will "move up" to the point key, rather than stopping at the range key lower bound. For example, `SeekGE(e@5)` if there was an `e1` with no covering range key. 

Maybe that's obvious, in which case perhaps just mention it in writing, for completeness?
</blockquote></details>

We can cover this with the existing example, with `SeekGE(d@5)`, if I'm understanding you correctly? Added.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GHBgr9eDAqojf8Rjb:-N6I5JDz8Jg-OToiTw3n:bcqy5yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L315)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Worth an additional, tabulated example, to underscore the difference in the SeekLT case? Or even just a subset of the above operations that would demonstrate wherein difference lies.
</blockquote></details>

Sure, may as well.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GIjgz6RTmLtZLWjQs:-N6I5WxA2PoeoGIYWBmL:b-ugo42p) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L349)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Worth adding a brief, final paragraph with something like "When in doubt, use X iterator implementation with Y settings"?
</blockquote></details>

I don't think I want to prescribe any settings, because it's very situation-dependant, but clarified that `EngineIterator` is mostly internal and that almost everyone wants an `MVCCIterator`.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GKwUvBfmOk07XF36H:-N6I5nCu5-vUO8fpJd9E:b-o1r1oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L464)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Curious - are you planning on going back and updating this note once GC is done? Or publishing a new note for GC?
</blockquote></details>

Yes, I'm going to update this note as the implementation matures.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GLn4jE4kzRwyo4Vil:-N6I5tHP2KIAa3F0ROBb:b-77q79b) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L487)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Are we tracking the removal of this "old" iterator impl?
</blockquote></details>

Not explicitly. Bulk IO will have to migrate all of their code, so I guess it falls under the MVCC range tombstone backup/restore work.
___
*[`docs/tech-notes/mvcc-range-tombstones.md` line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83762#-N6GO6WW4e_mcw5h5CXC:-N6I6LUP2synSmw8W7UU:b-g1h5mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fbdf4c06176eaa515252fe3df2a86875bc5128/docs/tech-notes/mvcc-range-tombstones.md#L575)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

We also have cockroachdb/pebble#1341, which we intend to land as the "official RFC" for Pebble range keys (despite it being finalized after we implemented range keys). Not sure if / how you want to incorporate here. We could also just loop back and add a reference to RFC in its final form once we land it.
</blockquote></details>

Sure, thanks, linked it for now and we can update it later.

**Review by nicktrav — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83762)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @10, @5, @aliher1911, @itsbilal, and @sumeerbhola)

**Comment by erikgrinaker** [comment]
bors r-

Forgot about the `AddSSTable` bit that I wanted to test and update.

**Comment by erikgrinaker** [comment]
Added some test and docs updates for the `Export` SST overlap over in #83927, and added a sentence to the tech note.

bors r=sumeerbhola,jbowens,nicktrav

**Pull request merged**
