### PR TITLE
colrpc: do not keep reference to batch in outbox

### PR DESCRIPTION
**Pull request by yuzefovich**
I was just looking at a heap profile in which most of the memory was
allocated in the input to the outbox for batches, and this prompted me
to look into releasing the reference to the batch in the outbox eagerly.
However, we actually don't need to keep the reference to batch at all,
so this commit cleans that up a bit.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I don't think it will have a big impact, but I also don't see a reason to not do this.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-MROxB5lEQFgiWNCq7DJ:-MROxB5lEQFgiWNCq7DK:bqfc8h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22a142b960fdc7eaecd388843cd3a658d63f278/pkg/sql/colflow/colrpc/outbox.go#L254)):*
> ```Go
> 			// We no longer need the batch, so unset it eagerly to allow it to
> 			// be garbage-collected sooner.
> 			o.batch = nil
> ```

Technically this batch is not safe for reuse until the next call to `Next`, right? Intuitively, this line should have no effect because the input should still hold on to a batch to reuse on the next call to `Next`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-MROxB5lEQFgiWNCq7DJ:-MRQhQxX8NAIftk2EnU2:bvlnf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22a142b960fdc7eaecd388843cd3a658d63f278/pkg/sql/colflow/colrpc/outbox.go#L254)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Technically this batch is not safe for reuse until the next call to `Next`, right? Intuitively, this line should have no effect because the input should still hold on to a batch to reuse on the next call to `Next`.
</blockquote></details>

Good points, but I updated the PR to be less controversial (I think).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-:-MRU4j5J5CCPfNy0sZ8h:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-MROxB5lEQFgiWNCq7DJ:-MRU4cfy-haD_Xefl2A8:b-4fyoa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22a142b960fdc7eaecd388843cd3a658d63f278/pkg/sql/colflow/colrpc/outbox.go#L254)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good points, but I updated the PR to be less controversial (I think).
</blockquote></details>

Indeed. I wonder why we kept a reference to this batch?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-:-MRVYxS_6xtG_f-tEBpQ:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59072#-MROxB5lEQFgiWNCq7DJ:-MRVYyfY2lUt-VqTh5SS:btupv1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c22a142b960fdc7eaecd388843cd3a658d63f278/pkg/sql/colflow/colrpc/outbox.go#L254)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Indeed. I wonder why we kept a reference to this batch?
</blockquote></details>

:man_shrugging:

**Comment by yuzefovich** [comment]
Unrelated Flake should be fixed now.

bors r+

**Pull request merged**
