### PR TITLE
Contacts the Cockroach Labs server when saving opt-in data

### PR DESCRIPTION
**Pull request by maxlang**
This wires up registering clusters on the registration server. The only thing remaining is to add the appropriate Cluster ID once https://github.com/cockroachdb/cockroach/pull/5647 is merged.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5656)

### CODE REVIEW

**Comment by cuongdo** [comment]
When I try your branch on my machine (using Chrome), I get the following errors:



---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[ui/ts/models/cockroachlabs.ts, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-F6yucVhFM86PrJRi:-KE-F6yucVhFM86PrJRj:505756706) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L65)):*
Since TS defaults to public visibility, should we by default declare new fields `private`? That's the default thing we do in Go, but I'm not sure if there are other factors that make it difficult in TS.

---

*[ui/ts/models/cockroachlabs.ts, line 70 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-DbPmAxoq5kC7TJzO:-KE-DbPmAxoq5kC7TJzP:1370456029) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L70)):*
You can now get the ClusterID through the new `/_admin/v1/cluster` API. Its usage should be self-explanatory.

---

*[ui/ts/models/cockroachlabs.ts, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-GGBNtMKWYjvf_UiC:-KE-GGBNtMKWYjvf_UiD:-1116900642) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L167)):*
s/or has opted it/or has opted out/

---

*[ui/ts/models/cockroachlabs.ts, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-JjUrjH6z74j4-8_p:-KE-JjUrjH6z74j4-8_q:-1239644888) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L169)):*
Why is `data` an optional parameter? It seems like you're always passing it in.

---

*[ui/ts/models/cockroachlabs.ts, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-Id7Sbcam6xQcRHM1:-KE-Id7Sbcam6xQcRHM2:-1446988699) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L187)):*
What if this has an error? Seems like the error should be logged.

---

*[ui/ts/models/cockroachlabs.ts, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-HpjvjcmjecC2JeUD:-KE-HpjvjcmjecC2JeUE:1074481882) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L212)):*
We really should have a cleaner API for setUIData that does the stringification & `btoa` calls. Not for this PR, but wanted to note that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-:-KE-JU3mSj2ttfhasCzO:767101808)*

**Comment by cuongdo** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656)*

**Comment by maxlang** [comment]
Yeah, this is an issue with the registration server.
I made a PR with fixes here: https://github.com/cockroachlabs/registration/pull/16

---

Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[ui/ts/models/cockroachlabs.ts, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-F6yucVhFM86PrJRi:-KE-MbBIiBOyzJzhhwkF:-1194809292) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L65)):*
We should probably start building up a simple style guide with stuff like this.  I guess I'm not used to the capability to make things private in JS so I typically don't use it, but I should maybe be more aggressive.

In this particular case, we should probably use something like a factory pattern. The issue I'm trying to solve is that the object isn't safe to use until the http requests in the constructor have completed. That feels like you want a ```CockroachLabsFactory``` that returns a ```MithrilPromise<CockroachLabs>```. Then you'd no longer need to expose these properties.

I added a TODO, but I know the whole way we manage these singletons which are essentially services needs to change.

---

*[ui/ts/models/cockroachlabs.ts, line 70 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-DbPmAxoq5kC7TJzO:-KE-NIbih8ezGIt2AxPe:1610000531) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L70)):*
Added.

---

*[ui/ts/models/cockroachlabs.ts, line 167 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-GGBNtMKWYjvf_UiC:-KE-TWbrnzWUQkfLbj_4:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L167)):*
Done

---

*[ui/ts/models/cockroachlabs.ts, line 169 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-JjUrjH6z74j4-8_p:-KE-NSkSymhXirE5d7eZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L169)):*
Done.

---

*[ui/ts/models/cockroachlabs.ts, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-Id7Sbcam6xQcRHM1:-KE-Nqgi5hDJ_KxCSbkb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L187)):*
Done.

---

*[ui/ts/models/cockroachlabs.ts, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-HpjvjcmjecC2JeUD:-KE-OFjjTdgL6jcBeldV:1335831285) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L212)):*
Yeah, I actually started doing that for this change but then decided to back off. It shouldn't really be too complicated, but I hesitated because I wasn't sure if there was a good way to handle all the casting that has to happen after ```JSON.parse```

It can probably just return an object of type any and perform the cast at that point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-:-KE-MKd-o5z87hMRmB5A:-544635220)*

**Comment by cuongdo** [comment]
Looks good so far. I'd really like to test against a fixed registration server before green-lighting this.

---

Reviewed 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/ts/models/cockroachlabs.ts, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-F6yucVhFM86PrJRi:-KE1i1YrQKeL3iGDb1fB:651902063) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L65)):*
Yes, let's look at putting together a style guide after beta and close look at the data framework and web framework we're using.

---

*[ui/ts/models/cockroachlabs.ts, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-HpjvjcmjecC2JeUD:-KE1iopjy7gjq-cBIKe3:1956736309) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L212)):*
Maybe add a TODO so we don't forget?

---

*[ui/ts/models/cockroachlabs.ts, line 90 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE1iVkXmzdwGWOHJOuf:-KE1iVkY3Pqx88eYHbhq:-332399482) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6bb26c3d5e9bfbecffd7ed4e423284eed515b0/ui/ts/models/cockroachlabs.ts#L90)):*
There must be a cleaner way to catch errors than these nested `try`/`catch` blocks. We're running short on time for beta, but let's look at this more generally post-beta. Maybe add a TODO here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-:-KE1isj_tFANs9v-zzKK:1816382585)*

**Comment by cuongdo** [comment]
:lgtm:

Tested against the pending PR on the reg server. I'd suggest getting this in only after the reg server changes go through. I'd like to avoid JS errors on master when possible.

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-:-KE1zElR5bTCoBpZ-2lg:-260788468)*

**Comment by maxlang** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[ui/ts/models/cockroachlabs.ts, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE-HpjvjcmjecC2JeUD:-KE20eBvM2Gp5DCABwWt:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/803d6f6d2801ec3e0c3777de9023054fc5be3996/ui/ts/models/cockroachlabs.ts#L212)):*
Done

---

*[ui/ts/models/cockroachlabs.ts, line 90 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656#-KE1iVkXmzdwGWOHJOuf:-KE20NLTUa4UwP41HmcU:676635175) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6bb26c3d5e9bfbecffd7ed4e423284eed515b0/ui/ts/models/cockroachlabs.ts#L90)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5656)*

**Comment by maxlang** [comment]
cc @spencerkimball @mberhault blocked on https://github.com/cockroachlabs/registration/pull/16

**Comment by maxlang** [comment]
Merging with failure after consulting with @cuongdo 
The UI seems to be fine

**Pull request merged**
