### PR TITLE
cli/sql: improve the display of statement timings

### PR DESCRIPTION
**Pull request by knz**
Requested/recommended by @jordanlewis 

2 changes:
- bug fix: include the parse and planning times too
- aesthetics: make the display clearer and more compact

Example:
```
root@:26257/defaultdb> delete from t where true;
DELETE 12

Time: 0.003s total (exec 40.5% / net 37.5% / other 22.0%)

root@:26257/defaultdb> insert into t select uuid_v4()::uuid from generate_series(1,10000);
INSERT 10000

Time: 0.108s total (exec 99.5% / net 0.3% / other 0.2%)
```

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
LGTM. I quite like the new time rendering format, it's an improvement over what we had before. :100: 

> The recent change to introduce server execution times mistakenly moved
the report about excess formatting latency under the `show_times`
conditional. 

I think this is [inaccurate](https://github.com/arulajmani/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/cli/sql_util.go#L799) though. I would make an argument that we should stick to printing the render delay only if `show_times` is turned on, as it is only interesting when presented along other timings anyway. Also it's slightly confusing if `show_times` doesn't apply to the render delay time. At the least, we should call out the new behaviour in the release notes. 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54605#-:-MHlIeSP4YESOPJCyNly:b-jsska9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by knz — COMMENTED** [review]
> I think this is inaccurate though.

You're right. I made a mistake - your change did not alter the prior behavior, so there was nothing to fix.

I altered the PR accordingly to remove mention of a bug fix here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54605#-:-MHlUvQG5tggXf9iRrSX:b-mibzp9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by knz** [comment]
TFYR

bors r=arulajmani

**Comment by arulajmani** [comment]
Just to clarify, when I said update the release notes, I meant to say that we should explicitly call out the new behavior (which is that render delay is printed regardless of the value of `show_times`). But if you think it's too minor a change and not worth calling out, I'm oaky with that too, I'll leave it up to you!

**Comment by knz** [comment]
> we should explicitly call out the new behavior 

I agree with this! But I reverted that change.

**Pull request merged**
