### PR TITLE
sql: fix several typos

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
:lgtm: except for that code movement in aggregator.go which seems unnecesssary

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28314#-:-LJGFKshAtkXGna5pGFC:bs9y3uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/aggregator.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28314#-LJGFI8v75OiNu87jB4y:-LJGFI8w-OItH1HF5MyE:b-i1r9p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c105230318e30968c80de8f8774ff1c47f2009d1/pkg/sql/distsqlrun/aggregator.go#L884)):*
> ```Go
> 	if err := ag.bucketsAcc.Grow(ag.ctx, sizeOfAggregateFunc*int64(len(ag.funcs))); err != nil {
> 		return nil, err
> 	}
> ```

Not sure what the point of moving this up is?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28314)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/aggregator.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28314#-LJGFI8v75OiNu87jB4y:-LJGHbvT5HkDIJUAJyp7:bqj42cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c105230318e30968c80de8f8774ff1c47f2009d1/pkg/sql/distsqlrun/aggregator.go#L884)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Not sure what the point of moving this up is?
</blockquote></details>

My understanding is that we want to make sure that we have enough memory with call to `Grow` before actually allocating the memory with `make`. I moved the check prior to allocation. I might be missing something though.

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28314)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/aggregator.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28314#-LJGFI8v75OiNu87jB4y:-LJGKOU93-mNbt0FCr7b:bp93p1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c105230318e30968c80de8f8774ff1c47f2009d1/pkg/sql/distsqlrun/aggregator.go#L884)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

My understanding is that we want to make sure that we have enough memory with call to `Grow` before actually allocating the memory with `make`. I moved the check prior to allocation. I might be missing something though.
</blockquote></details>

Oh I see, good point!

**Review by yuzefovich — COMMENTED** [review]
Thanks for quick review!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28314#-:-LJGKn8Y3pFJfUFcVBVl:bappye6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
