### PR TITLE
sql: do not purge range cache when using follower reads

### LINKED ISSUE #61313: execinfra: check whether planned follower reads are mistakenly counted as misplanned ranges
In #61244 Nathan made the following observation:
```
This code is also making me wonder: do we count DistSQL flows that are
intentionally planned on followers to execute follower reads using the
ClosestOracle as "misplanned"?
```
and upon quick code inspection I think that we mistakenly count planned follower reads as misplanned ranges. We should look into this and fix it if that's the case.

Jira issue: CRDB-3040

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when we used the closest replica oracle and happened to pick a follower for a distributed plan, the TableReaders would still produce "misplanned ranges" metadata. This would then lead to purging the range cache of supposedly stale entries on the gateway even though the entries weren't stale. This is now fixed by setting `ignoreMisplannedRanges` flag on the TableReader spec.

One of the approaches to solve this issue mentioned propagating a set of `ClientRangeInfo`s as part of the TableReader spec, but that seems more complicated and much more involved than this one, so the simpler approach was chosen. In particular, for that idea to work we'd need to include all Infos for all ranges intersecting with the spans to read (which can be non-trivial in size) as well as to add code on the TableReader side to compare the gateway's `ClientRangeInfo` with the range cache of the node where the TableReader was placed.

Fixes: #61313.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/execinfra/readerbase.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVVrtpQCuHXJO0keiMs:-NVVrtpQCuHXJO0keiMt:b-d7lta8) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b324498869b48f134c50bdbfdd323c5294c1b2/pkg/sql/execinfra/readerbase.go#L61)):*
> ```Go
> 		}
> 		if rSpan.EndKey == nil {
> 			// GetCachedOverlapping simply ignores spans if EndKey is not set.
> ```

Q for KV folks: should we push the logic in the first commit into `getCachedOverlappingRLocked`?

**Review by michae2 — COMMENTED** [review]
Thank you for fixing this (and sorry I never did!).

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-:-NVku9crBrQzM_skGkJf:bvmfuzo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkm57hB7VYDjHIZfFi:-NVkm57hB7VYDjHIZfFj:btxb1gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L201)):*
> ```Go
> 	// There are no "misplanned" ranges if we know the leaseholder, and we're
> 	// deliberately choosing non-leaseholder.
> 	ignoreMisplannedRanges = leaseholder != nil && leaseholder.NodeID != repl.NodeID
> ```

Maybe this is a bit contrived, but it seems like we should ignore misplanned ranges for _all_ follower reads even if we were wrong about which replica was the leaseholder, because for a workload consisting of _only_ follower reads it should never matter if we know the correct leaseholder or not.

But I can be convinced otherwise (I can see that maybe in general this helps us find out the new leaseholder sooner, even if it didn't matter for this query, and most workloads do not consist of _only_ follower reads).
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkl8tD3bJWrJgvQsEK:-NVkl8tECGb8OxGe1L0H:b-hyptko) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L346)):*
> ```Go
> 	// There are no "misplanned" ranges if we know the leaseholder, and we're
> 	// deliberately choosing non-leaseholder.
> 	ignoreMisplannedRanges = leaseholder != nil && leaseholder.NodeID != repl.NodeID
> ```

Should we be checking within `leaseholders` instead of checking the singular `leaseholder`?

(Also, same comment here, maybe we shouldn't condition this on leaseholder for follower reads.)
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkqzIg7m_SPrtmJ_uJ:-NVkqzIg7m_SPrtmJ_uK:b6xd5h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L864)):*
> ```Go
> 	// Verify that we didn't produce the "misplanned ranges" metadata that would
> 	// purge the non-stale entries from the range cache on n4.
> 	require.False(t, strings.Contains(rec.String(), "clearing entries overlapping"))
> ```

It seems like n4 should have an up-to-date cache anyway because no replicas have moved or changed between n4's cache being updated and now. (Am I missing something? Should there be an `EXPERIMENTAL_RELOCATE` command at the beginning of this new code to cause n4's cache to be stale?)

**Review by yuzefovich — COMMENTED** [review]
No worries, thanks for taking a look! My guess is that it's not that frequent of an issue (at least we never had any user reports about it), so it seems ok to take a while to fix it :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-:-NWnHqRnA0TI668urYh9:beqymay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/execinfra/readerbase.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVVrtpQCuHXJO0keiMs:-NWn9oixATLGP4z6tcKI:b-oi2wyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b324498869b48f134c50bdbfdd323c5294c1b2/pkg/sql/execinfra/readerbase.go#L61)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Q for KV folks: should we push the logic in the first commit into `getCachedOverlappingRLocked`?
</blockquote></details>

@nvanbenschoten any opinion on this?
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkm57hB7VYDjHIZfFi:-NWnBP1E78eCiFWxY6fM:baixru8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L201)):*
My rationale for using this approach is exactly

> I can see that maybe in general this helps us find out the new leaseholder sooner, even if it didn't matter for this query, and most workloads do not consist of _only_ follower reads

I think of this "misplanned ranges" metadata as a nice-to-have: it allows us to piggy-back on incorrect DistSQL physical planning decisions to update the range cache. It seems to be always beneficial to keep the range cache as close to up-to-date as possible, even if a particular workload consists only of follower reads (and the range cache doesn't matter for DistSQL physical planning of that workload), I'm speculating that there might be other internal users of the range cache (outside of SQL) that would benefit from the updated range cache.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkl8tD3bJWrJgvQsEK:-NWnD5Zw9u3_N2UY3yNL:bus9lcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L346)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should we be checking within `leaseholders` instead of checking the singular `leaseholder`?

(Also, same comment here, maybe we shouldn't condition this on leaseholder for follower reads.)
</blockquote></details>

My understanding here is that `leaseholders` is a slice of _leaseholder candidates_ (i.e. potential leaseholders) whereas `leaseholder` is the node we believe to be _the_ leaseholder right now. There can only be one actual leaseholder at any point in time, so checking a single node ID here seems appropriate.

(Also, this oracle is only used in tests right now, so I'm not too concerned about doing something incorrect here - I considered not making any changes here but decided to do it for completeness sake.)
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkqzIg7m_SPrtmJ_uJ:-NWnE1to-Zj9869fEDIC:bpj9dxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L864)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It seems like n4 should have an up-to-date cache anyway because no replicas have moved or changed between n4's cache being updated and now. (Am I missing something? Should there be an `EXPERIMENTAL_RELOCATE` command at the beginning of this new code to cause n4's cache to be stale?)
</blockquote></details>

Indeed, n4 does have an up-to-date range cache (and we do verify its contents above, in the middle of the test); however, that's not what this test and the bug is about.

Here we issue a query against `n4` which chooses to use a follower read on `n3` and places the `TableReader` processor on `n3`. `n4` knows that `n1` is the leaseholder, yet before this patch the `TableReader` (the `ColBatchScan`, to be precise) on `n3` would produce "misplanned ranges" metadata because it would assume that `n3` is the leaseholder for the range, so `n4` would purge its range cache entry even though it was non-stale. After this fix, we expect that the `TableReader` on `n3` doesn't produce the "misplanned ranges" metadata, so we don't see any range cache purging on `n4`.

**Review by michae2 — APPROVED** [review]
I think we probably want to plumb `ignoreMisplannedRanges` through the `spanResolverIterator.queryState.AssignedRanges` map as well, but other than that this :lgtm:

Thanks for answering my questions.

> Reviewed 11 of 11 files at r4, 3 of 3 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-:-NXCV1NW9SQcvcNRTCx9:b-u2cq06)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`pkg/sql/distsql_physical_planner.go` line 1181 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NXCQOKUB3ed6UE2ZNB9:-NXCQOKUB3ed6UE2ZNBA:bpajp3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/814f6d144d42808aadf4e2e28378fb39c31082fd/pkg/sql/distsql_physical_planner.go#L1181)):*
> ```Go
> 	if planCtx.isLocal {
> 		// If we're planning locally, map all spans to the gateway.
> 		return []SpanPartition{{dsp.gatewaySQLInstanceID, spans}}, true /* ignoreMisplannedRanges */, nil
> ```

question: Does this `true` make a difference? I imagine we must already not be going through the usual misplanned-ranges code path for local plans?
___
*[`pkg/sql/physicalplan/span_resolver.go` line 289 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NXCSocmEe4Y2c1i7jHz:-NXCSocmEe4Y2c1i7jI-:b-xgaslb) ([raw file](https://github.com/cockroachdb/cockroach/blob/814f6d144d42808aadf4e2e28378fb39c31082fd/pkg/sql/physicalplan/span_resolver.go#L289)):*
> ```Go
> 	rngID := it.it.Desc().RangeID
> 	if repl, ok := it.queryState.AssignedRanges[rngID]; ok {
> 		return repl, false, nil
> ```

Should we be keeping the value of `ignoreMisplannedRanges` in the `AssignedRanges` map as well?
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkm57hB7VYDjHIZfFi:-NXCMXTx-cowaA87JsEy:b-a65ex6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L201)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My rationale for using this approach is exactly

> I can see that maybe in general this helps us find out the new leaseholder sooner, even if it didn't matter for this query, and most workloads do not consist of _only_ follower reads

I think of this "misplanned ranges" metadata as a nice-to-have: it allows us to piggy-back on incorrect DistSQL physical planning decisions to update the range cache. It seems to be always beneficial to keep the range cache as close to up-to-date as possible, even if a particular workload consists only of follower reads (and the range cache doesn't matter for DistSQL physical planning of that workload), I'm speculating that there might be other internal users of the range cache (outside of SQL) that would benefit from the updated range cache.
</blockquote></details>

Great point.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkl8tD3bJWrJgvQsEK:-NXCNmcD5o3sXi_5vDS6:b-f743ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/sql/physicalplan/replicaoracle/oracle.go#L346)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My understanding here is that `leaseholders` is a slice of _leaseholder candidates_ (i.e. potential leaseholders) whereas `leaseholder` is the node we believe to be _the_ leaseholder right now. There can only be one actual leaseholder at any point in time, so checking a single node ID here seems appropriate.

(Also, this oracle is only used in tests right now, so I'm not too concerned about doing something incorrect here - I considered not making any changes here but decided to do it for completeness sake.)
</blockquote></details>

Ah, that makes sense. Thank you.
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkqzIg7m_SPrtmJ_uJ:-NXCUbW4DQyq5ZDAsUmY:b57peg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L864)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Indeed, n4 does have an up-to-date range cache (and we do verify its contents above, in the middle of the test); however, that's not what this test and the bug is about.

Here we issue a query against `n4` which chooses to use a follower read on `n3` and places the `TableReader` processor on `n3`. `n4` knows that `n1` is the leaseholder, yet before this patch the `TableReader` (the `ColBatchScan`, to be precise) on `n3` would produce "misplanned ranges" metadata because it would assume that `n3` is the leaseholder for the range, so `n4` would purge its range cache entry even though it was non-stale. After this fix, we expect that the `TableReader` on `n3` doesn't produce the "misplanned ranges" metadata, so we don't see any range cache purging on `n4`.
</blockquote></details>

Right, thank you, sorry.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102842)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/distsql_physical_planner.go` line 1181 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NXCQOKUB3ed6UE2ZNB9:-NXCX-NwB4NpKlJFWVEM:b-k88xup) ([raw file](https://github.com/cockroachdb/cockroach/blob/814f6d144d42808aadf4e2e28378fb39c31082fd/pkg/sql/distsql_physical_planner.go#L1181)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

question: Does this `true` make a difference? I imagine we must already not be going through the usual misplanned-ranges code path for local plans?
</blockquote></details>

Good point, no, it doesn't really matter - we always set `ColBatchScan.ignoreMisplannedRanges` to `true` when it's part of local-only plan, but I thought it'd be good to be explicit here. Extended the comment to include this detail.
___
*[`pkg/sql/physicalplan/span_resolver.go` line 289 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NXCSocmEe4Y2c1i7jHz:-NXCdAbDAxAzjnwp7oh5:b-o0g651) ([raw file](https://github.com/cockroachdb/cockroach/blob/814f6d144d42808aadf4e2e28378fb39c31082fd/pkg/sql/physicalplan/span_resolver.go#L289)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should we be keeping the value of `ignoreMisplannedRanges` in the `AssignedRanges` map as well?
</blockquote></details>

Yes, very nice catch, thank you. I adjusted the test to cover this case.
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 864 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102842#-NVkqzIg7m_SPrtmJ_uJ:-NXCZMe83XGw_oRMyP94:bfligsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9cab4a1da9aeeaa819c964f54959f801db62514/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L864)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Right, thank you, sorry.
</blockquote></details>

np! typing things like these out helps in making sure that we are asserting what we want to assert :)

**Comment by yuzefovich** [comment]
Thanks for the careful review!

bors r+

**Pull request merged**
