### PR TITLE
*: migrate some uses of ReplicaDescriptors.Unwrap to All or Voters

### PR DESCRIPTION
**Pull request by danhhz**
Touches #37916

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Feels like this deserves more commentary than I have, but I'm not sure what would be most helpful. Comment next to each usage of All or Voters with a justification feels too spammy. Looking for opinions

**Review by tbg — APPROVED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/cli/debug.go, line 1171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ63BS7y_vaBzDoRfD:-LgZ63BS7y_vaBzDoRfE:b-mtage0) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/cli/debug.go#L1171)):*
> ```Go
> 		hasSelf := false
> 		numDeadPeers := 0
> 		allReplicas := desc.Replicas().All()
> ```

How do you feel about s/All/VotersAndLearners/?
___
*[pkg/server/admin.go, line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ6PrKAKar1TG9MDZW:-LgZ6PrKAKar1TG9MDZX:b-o0i9i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/server/admin.go#L670)):*
> ```Go
> 			return nil, s.serverError(err)
> 		}
> 		for _, repl := range rng.Replicas().Voters() {
> ```

Doesn't this want them all? IIRC this code is concerned with computing the stats accounting for the duplication due to replication. So it wants to include all of the copies, including learners.
___
*[pkg/sql/crdb_internal.go, line 1768 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ6n8V9ZrnSRL0g7np:-LgZ6n8WEzllAZJOH09J:bt7zxcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/sql/crdb_internal.go#L1768)):*
> ```Go
> 
> 			var replicas []int
> 			for _, rd := range desc.Replicas().Voters() {
> ```

This should expose learners, but probably as a separate column. We rely on the replicas column for "fully upreplicated" type computations in all sorts of tests.
___
*[pkg/storage/consistency_queue.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ79b2-n0oO_pwqvA8:-LgZ79b2-n0oO_pwqvA9:b-g8pg0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/storage/consistency_queue.go#L89)):*
> ```Go
> 	// Check if all replicas are live. Some tests run without a NodeLiveness configured.
> 	if repl.store.cfg.NodeLiveness != nil {
> 		for _, rep := range repl.Desc().Replicas().Voters() {
> ```

Deserves a comment. Don't we want all nodes here? I assume we check this because running consistency checks when some replicas are on dead nodes clogs up the queue. By that token we should avoid dead learners too (I assume we'll want to include them in the consistency checks, at least that seems natural to me).
___
*[pkg/storage/replica.go, line 738 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ7NfBEIrakgDV3fxD:-LgZ7NfBEIrakgDV3fxE:bhhvhnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/storage/replica.go#L738)):*
> ```Go
> }
> 
> func maxReplicaID(desc *roachpb.RangeDescriptor) roachpb.ReplicaID {
> ```

The callers know what they're getting now, right? Maybe add a comment to this method. Or maybe this is obvious? Hmm. In `replica.go` it's probably fair to assume that it is.
___
*[pkg/storage/replica.go, line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ7_tXCL3fFCbmTAA8:-LgZ7_tXCL3fFCbmTAA9:b-n25bp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/storage/replica.go#L914)):*
> ```Go
> 	ri.RangeMaxBytes = *r.mu.zone.RangeMaxBytes
> 	if desc := ri.ReplicaState.Desc; desc != nil {
> 		for _, replDesc := range desc.Replicas().Voters() {
> ```

Why not all? They're going to receive ct updates just the same, even though we'll probably end up not serving reads from them for quite a while.
___
*[pkg/storage/replica_command.go, line 1423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38010#-LgZ7sPEBn79HbfCP9_t:-LgZ7sPEBn79HbfCP9_u:b-u48rs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/742926daa31c85b58d2f9920d2b43441fc5bdda9/pkg/storage/replica_command.go#L1423)):*
> ```Go
> 	if args.RandomizeLeases && r.OwnsValidLease(r.store.Clock().Now()) {
> 		desc := r.Desc()
> 		voterReplicas := desc.Replicas().Voters()
> ```

Makes sense, but worth a small comment.

**Comment by danhhz** [comment]
TFTR! I'm a little shy about all this since the decisions feel pretty ad-hoc. Particular evidence for that is that these were the ones that I was expecting to be fairly unambiguous, but we have different expectations for so many of them that it's clear that was an incorrect assumption.

I'm really starting to consider if we should just default to absolutely everything using all replicas unless it absolutely has to care about learners. I wonder what that second list even is. Even some of the current uses of QuorumSize in the allocator seem like care more about what the quorum size _will be_ than what it _currently is_. (Though on this last point, I think we'll need to introduce some new protections in the allocator that care about both.)

My initial guess was that a learner replica was most like a replica getting a preemptive snapshot, but I'm starting to wonder how much it makes sense to think of them as a replica that's really far behind. In that case, I don't know what they'd affect besides ... alert-ing when quorum is lost/waiting for full replication. They shouldn't become leaseholders or raft leaders or serve follower reads, plus some perf optimizations to avoid trying to do those things just to find out you can't. The allocation also wants new code to clean them up if it seems the node that tried to add them is gone. I'm not even sure what else.

**Comment by danhhz** [comment]
Closing in favor of #38149

**Pull request closed without merging**
