### PR TITLE
sql: use 'NONVOTERS' as keyword for 'RELOCATE', not 'NON_VOTERS'

### LINKED ISSUE #63219: sql,kv: SQL syntax for the RELOCATE statement is non-idiomatic
commits af80850da718040acf050a4f1957e89e30f3da4c and af80850da718040acf050a4f1957e89e30f3da4c have added the syntax `RELOCATE VOTERS` and `RELOCATE NON_VOTERS`

The prefix `NON_` in front of a keyword is highly non-idiomatic for SQL: the goal of the SQL syntax it to use only standalone english words, and use adjectives/adverbs/prepositions to indicate inclusion/exclusion.

For this use case, the more idiomatic syntax would be:

- `RELOCATE ONLY VOTERS` / `RELOCATE VOTERS ONLY`

- `RELOCATE EXCLUDING VOTERS` / `RELOCATE VOTERS EXCLUDED`

Found while working on rebasing #60676. 

cc @mwang1026 @aayushshah15 for triage.

### PR DESCRIPTION
**Pull request by knz**
Informs #73315.
Fixes #63219.

The idiom for positional keywords in SQL is to either use words
separated by spaces (e.g. NOT NULL), or to concatenate the words
together (ISERROR, NOLOGIN, LINESTRING).

Release note (sql change): In the experimental RELOCATE syntax
forms, the positional keyword that indicates that the statement
should move non-voter replicas is now spelled `NONVOTERS`, instead
of `NON_VOTERS` previously.

Release note (sql change): The inline help for the ALTER
statements now mentions the RELOCATE syntax.

### CODE REVIEW

**Comment by rafiss** [comment]
thank you, seems like this will resolve https://github.com/cockroachdb/cockroach/issues/63219

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73802#-:-Mqu7bfJ9qjLXQWN4iij:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @lunevalex)

**Review by rafiss — APPROVED** [review]

**Review by otan — COMMENTED** [review]
do we have to worry about backwards compat?

**Comment by rafiss** [comment]
ordinarily yes, but this is both an experimental feature, and also only intended for internal use.

**Review by lunevalex — APPROVED** [review]

**Pull request merged**
