### PR TITLE
importccl: schema and better support for FKs

### PR DESCRIPTION
**Pull request by madelynnblue**
Supersedes #27755

### CODE REVIEW

**Review by dt — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27782#-:-LI7gqWrAqwWOGgFK3of:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27782#-LI7giU7-H_gmzB1hCP4:-LI7giU7-H_gmzB1hCP5:b-pgysth) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b39210b0c9f527db4e9253cb9483b8aa0777852/pkg/ccl/importccl/import_stmt_test.go#L665)):*
> ```Go
>     ADD CONSTRAINT b_pkey PRIMARY KEY (j);
> 
> ALTER TABLE ONLY public.a
> ```

Hard-mode of circular is self-referential... maybe also make a reference a?
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27782#-LI7g7cL2cI6dpy-3EE1:-LI7g7cL2cI6dpy-3EE2:b41u6aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e371e8f3aaa9da1193a16b2cdd46d5e03361f30c/pkg/ccl/importccl/read_import_pgdump.go#L352)):*
> ```Go
> 	}
> 	if sc := tn.Schema(); sc != "" && sc != "public" {
> 		return "", errors.Errorf("non-public schemas unsupported: %s", sc)
> ```

we have an unsupported error helper in pgerror if you felt like it -- would also mean that we got a count of how many times we hit that error.

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
(whoops, didn't mean to use the request changes status)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27782)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt_test.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27782#-LI7giU7-H_gmzB1hCP4:-LI7mwm9Eet2tKe2wTK9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b39210b0c9f527db4e9253cb9483b8aa0777852/pkg/ccl/importccl/import_stmt_test.go#L665)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hard-mode of circular is self-referential... maybe also make a reference a?
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27782#-LI7g7cL2cI6dpy-3EE1:-LI7nVe615EMCsH46bMb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e371e8f3aaa9da1193a16b2cdd46d5e03361f30c/pkg/ccl/importccl/read_import_pgdump.go#L352)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we have an unsupported error helper in pgerror if you felt like it -- would also mean that we got a count of how many times we hit that error.
</blockquote></details>

Done.

**Pull request merged**
