### PR TITLE
Implement basic draining modes

### PR DESCRIPTION
**Pull request by tbg**
Implemented DrainClients and DrainLeadership with simple implementations
according to the mini-RFC #6283.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6313)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 10 of 12 files at r8.
Review status: 10 of 12 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 231 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIfGTTWNxI7apNoa39:-KGIfGTTWNxI7apNoa3A:1864092216) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/cli/start.go#L231)):*
We may want to make this procedure more complicated in the future, e.g. first drain clients, then drain leadership. This signal handler and `/quit` should both call into a single zero-argument method in the server instead of hard-coding the fact that we set multiple drain modes at once.

---

*[server/admin.proto, line 239 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIhdhi3wVhmPhvjNtq:-KGIhdhi3wVhmPhvjNtr:-61765874) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/admin.proto#L239)):*
Put the second half of this comment in a TODO.

---

*[server/admin.proto, line 248 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIdXjgvZrZl8b0U4xs:-KGIdXjh3ReeAZFAkLaW:-1873957688) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/admin.proto#L248)):*
s/a DrainMode/a set of DrainModes/

Specify how the modes in the request interact with drain modes that are already set. Does it overwrite or take the union? I don't like overwriting here because it implies that draining will always be controlled by a single source, but we may want to trigger drains from multiple places (e.g. start draining after a replicaCorruptionError).  But using the union doesn't allow for drain flags to be cleared, so maybe it should take a set to add and a set to remove?

---

*[server/server.go, line 420 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIgV_Rj2Y4RdaWglZe:-KGIgV_SBhukZD_NTxwd:-1620797272) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/server.go#L420)):*
This doesn't work as described in the comment. 

---

*[sql/pgwire_test.go, line 187 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIgwU4ELfk-c0qAEI7:-KGIgwU4ELfk-c0qAEI8:441416010) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/sql/pgwire_test.go#L187)):*
Also clear the drain flag and verify that connections are allowed again

---

*[storage/replica.go, line 538 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIhySU08rsg9v-oC4q:-KGIhySU08rsg9v-oC4r:-1678507005) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/storage/replica.go#L538)):*
We want the client to get a `NotLeaderError` for the proper retry behavior. (If we don't, then it's disruptive to drain clients and leadership at the same time; we'd need to continue requesting leader leases until the clients are gone)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313)*

**Comment by tschottdorf** [comment]
Review status: 10 of 12 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 231 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIfGTTWNxI7apNoa39:-KGIoMRKRNQbeb3BjxBE:417177065) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/cli/start.go#L231)):*
Why not make it more complicated when it gets more complicated? Btw, this already drains clients first, then leadership (order matters and each drain state blocks, at least so far).

I considered adding a method on `*Server`, but there wasn't really a point. If you had something specific in mind, mind writing out some pseudo-Gode?

---

*[server/admin.proto, line 239 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIhdhi3wVhmPhvjNtq:-KGIotxgAdo_A3zqcZ7I:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/admin.proto#L239)):*
Done.

---

*[server/admin.proto, line 248 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIdXjgvZrZl8b0U4xs:-KGIvjJfI9GsfTn3FHe8:-1838485793) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/admin.proto#L248)):*
Yeah, the current API is a bit clunky. I think deltas make sense and one thing I haven't considered in this version is reading the current status. I will rework this to allow for all of that.

---

*[sql/pgwire_test.go, line 187 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIgwU4ELfk-c0qAEI7:-KGIz2j9Bt1WDJFAmvdK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/sql/pgwire_test.go#L187)):*
Done.

---

*[storage/replica.go, line 538 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIhySU08rsg9v-oC4q:-KGIz4r793LotSBYKrYF:135085749) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/storage/replica.go#L538)):*
I agree that we should return `NotLeaderError` here (this is already an issue with the old code), but only so that other nodes which have this leader cached don't catch unexpected errors. This could get some requests trapped in DistSender forever if all replicas of a range are draining, but I guess that's what context deadlines are for.
Changed (and as expected, some annoying deadlock fallout addressed in new early commits).

Btw, we wouldn't drain clients and leadership at the same time, but one after another (and they block), so we wouldn't see this in simple setups. But your comment still applies (applied) in multi-node clusters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313)*

**Comment by tschottdorf** [comment]
Smoothed out the API and added the option to query the current status. PTAL.

---

Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 420 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIgV_Rj2Y4RdaWglZe:-KGJMiQ7pkEM5wqTfNvF:1758359711) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/server/server.go#L420)):*
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-:-KGJO6TjFdEkoquWBuWD:-1544863802)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 6 of 12 files at r14, 6 of 6 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[cli/start.go, line 231 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIfGTTWNxI7apNoa39:-KGJTemsSclI3hx4xl6x:-2126935327) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/cli/start.go#L231)):*
I was mainly thinking of unexporting `GracefulDrainModes` and centralizing this knowledge in one place.

---

*[storage/store.go, line 289 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGNid7C4cDvWrI3XDpC:-KGNid7D2ngZUShjE8Wd:557851666) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b46108b413c50225bb65bd0b3376aab44ea7e/storage/store.go#L289)):*
Why an atomic instead of putting it in `mu`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-:-KGNiyJmB7gQmzDqBm3I:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 12 files at r14.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[cli/start.go, line 231 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGIfGTTWNxI7apNoa39:-KGRzYfLzqih6cnevEza:771868893) ([raw file](https://github.com/cockroachdb/cockroach/blob/641b1c657662271b0deadb2aa3b958497e9346f8/cli/start.go#L231)):*
To my mind, `server.GracefulDrainModes` *is* the knowledge in one place. I'm going to leave as is (mostly because I'm not really sure what else to do - I don't want to have `s.DrainForGracefulShutdown` sitting next to `s.Drain`), but feel free to send a follow-up PR for that.

---

*[storage/store.go, line 289 \[r16\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313#-KGNid7C4cDvWrI3XDpC:-KGRzFmSk3JsdeQUXm6C:-361340528) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3b46108b413c50225bb65bd0b3376aab44ea7e/storage/store.go#L289)):*
Good question, maybe got scared by the lock order comments below. Changed. And changed back because of lock order issues:

`systemGossipUpdate` holds `s.mu` while iterating over `s.mu.replicas` and, still under `s.mu`, calls `r.Desc()` but that needs the replica mu and that may be held by the replica's call out to `r.store.IsDrainingLeadership` (which in turn needs `s.mu`). Maybe this one is easy to fix, but how many more could there be?

I think we should generally make sure that the Replica doesn't acquire the Store lock. Since IsDrainingLeadership is one of the methods exposed specifically to have `Replica` call it, I'm going to stick with the atomic for now (but happy to talk about a more satisfying refactor).

Adding a comment/TODO on the field to capture the above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6313)*

**Pull request merged**
