### PR TITLE
forbid clusters join in same gossip network

### PR DESCRIPTION
**Pull request by Kevin-GuanJian**
Forbid clusters join in same gossip network

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3236)

### CODE REVIEW

**Comment by tschottdorf** [comment]
what's wrong with the existing code in `server/node.go`?

```go
func (n *Node) connectGossip() {
	log.Infof("connecting to gossip network to verify cluster ID...")
	// No timeout or stop condition is needed here. Log statements should be
	// sufficient for diagnosing this type of condition.
	<-n.ctx.Gossip.Connected

	bytes, err := n.ctx.Gossip.GetInfo(gossip.KeyClusterID)
	if err != nil {
		log.Fatalf("unable to ascertain cluster ID from gossip network: %s", err)
	}
	gossipClusterID := string(bytes)

	if n.ClusterID == "" {
		n.ClusterID = gossipClusterID
	} else if n.ClusterID != gossipClusterID {
		log.Fatalf("node %d belongs to cluster %q but is attempting to connect to a gossip network for cluster %q",
			n.Descriptor.NodeID, n.ClusterID, gossipClusterID)
	}
	log.Infof("node connected via gossip and verified as part of cluster %q", gossipClusterID)
}
```

**Comment by Kevin-GuanJian** [comment]
The ```connectGossip``` will forbid started node join to another cluster, but can't cover the inited node
Scenario: 
three node init use same gossip network, each node will gossip its own ```ClusterID``` simply here,:
```
func (r *Replica) maybeGossipFirstRange() error {
...
	// Gossip the cluster ID from all replicas of the first range.
	if log.V(1) {
		log.Infoc(ctx, "gossiping cluster id %s from store %d, range %d", r.store.ClusterID(),
			r.store.StoreID(), r.Desc().RangeID)
	}
	if err := r.store.Gossip().AddInfo(gossip.KeyClusterID, []byte(r.store.ClusterID()), clusterIDGossipTTL); err != nil {
		log.Errorc(ctx, "failed to gossip cluster ID: %s", err)
	}
...
```

**Comment by tschottdorf** [comment]
Ah, I see. Can you add a comment explaining that it's a sanity check? Something like

> // When multiple nodes are initialized with overlapping Gossip addresses, they all
// will attempt to gossip their cluster ID. This is a fairly obvious misconfiguration,
// so we error out below.

In order to prevent a newly inited node to disrupt an existing cluster (after all, there's no
guarantee that the node who will kill itself is the new one - it could mean the old cluster
dying as well) we'll need to be a little smarter, but this should be a good starting point.

**Comment by tamird** [comment]
LGTM. I think this needs a test, though.

**Comment by tschottdorf** [comment]
Generally on board with the idea of testing anything, but this change doesn't actually prevent cluster poisoning (I think - it's too asynchronous). Something that actually would is pinning the clusterID on all Gossip messages (rejecting those which don't match our own, if we have one, printing a fat error instead but leaving the node running).
Since the test here will be pretty involved, I don't think it's worth it at this point. But we should file an issue to get to the bottom of this.

**Comment by tschottdorf** [comment]
filed #3583.

**Pull request merged**
