### PR TITLE
storageccl: delete ImportRequest as it is no longer used by restore

### PR DESCRIPTION
**Pull request by adityamaru**
In 21.1 RESTORE stopped using the KV level ImportRequest for ingesting
data. The logic for restore was pulled into the data ingestion processor
as it did not rely on any KV specific information.

This change deletes all references of ImportRequest, and pulls out
some proto definitions that were previously nested in the ImportRequest.

Release note: None

### CODE REVIEW

**Comment by dt** [comment]
let's sit on this until 21.1.0 actually ships

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=dt

**Comment by adityamaru** [comment]
bors r=dt

**Comment by adityamaru** [comment]
Looks like an unrelated flake `TestRejectedLeaseDoesntDictateClosedTimestamp`.

bors r=dt

**Pull request merged**
