### PR TITLE
sql: correctly convert HLC time to AS OF SYSTEM TIME

### LINKED ISSUE #27229: sql: app schema migration fails with "count-leases: AS OF SYSTEM TIME: cannot specify timestamp in the future" and "value out of range"
**BUG REPORT**

When I drop tables it show following messages:

```
SQLSTATE[XX000]: Internal error: 7 ERROR:  count-leases: AS OF SYSTEM TIME: parsing argument: strconv.ParseInt: parsing "4000000000": value out of range (SQL: DROP TABLE IF EXISTS password_resets CASCADE)
```
or sometime, this:
```
SQLSTATE[XX000]: Internal error: 7 ERROR:  count-leases: AS OF SYSTEM TIME: cannot specify timestamp in the future (SQL: DROP TABLE IF EXISTS audio_streams CASCADE)
```
```
+--------------------------------------------------------------------------+
|                                 version                                  |
+--------------------------------------------------------------------------+
| CockroachDB CCL v2.1.0-alpha.20180702-243-g9521635-dirty                 |
| (x86_64-unknown-linux-gnu, built 2018/07/06 02:39:27, go1.10)            |
+--------------------------------------------------------------------------+
```
2. Please describe the issue you observed:

- What did you do?
Run the SQL above
- What did you expect to see?
Drop the table

### PR DESCRIPTION
**Pull request by vivekmenezes**
fixes #27229

Release note: None

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Comment by knz** [comment]
Could you perhaps consider back-porting this to 2.0?

**Comment by vivekmenezes** [comment]
the problem manifests only on the alpha release. This was introduced by https://github.com/cockroachdb/cockroach/pull/26346 through changing CountLease() to use AS OF SYSTEM TIME .

**Comment by knz** [comment]
Thanks for clarifying.

**Pull request merged**
