### PR TITLE
grpcutil: debounce grpc log spam

### LINKED ISSUE #14564: rpc: log spam about unable to connect to down node
Not sure what can be done here, but when a node in a cluster is down, all of the other nodes log a message once per second about being unable to create a client transport:

```
I170403 16:28:47.254064 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
I170403 16:28:48.141162 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
I170403 16:28:52.003562 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
```

### PR DESCRIPTION
**Pull request by tamird**
Closes #14564.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/grpcutil/log.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWRecPETnF5L5MDoN:-KiaWRecPETnF5L5MDoO:b-ynomag) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L88)):*
> ```Go
> 	if isSpam {
> 		gid := goid.Get()
> 		if t, ok := reconnectingGIDs[gid]; ok {
> ```

This isn't {thread,goroutine}-safe.

---

*[pkg/util/grpcutil/log.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWgzp_U6Foiae5pIG:-KiaWgzp_U6Foiae5pIH:b-xq9feu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L89)):*
> ```Go
> 		gid := goid.Get()
> 		if t, ok := reconnectingGIDs[gid]; ok {
> 			if timeutil.Since(t) < 10*time.Second {
> ```

So instead of logging every second this will log once every 10 seconds. That's an improvement, but do we really want even that spam?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Comment by bdarnell** [comment]
LGTM modulo thread safety.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/grpcutil/log.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWgzp_U6Foiae5pIG:-KiaYIfa37g7NkMsVXae:b-5s5o1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

So instead of logging every second this will log once every 10 seconds. That's an improvement, but do we really want even that spam?
</blockquote></details>

We want to log it at least once, and I think it's probably better to repeat it at some interval (My color for that bikeshed would be once a minute)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-:-KiaYp7DNQ_heMvcM5dK:bankdop)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/grpcutil/log.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWRecPETnF5L5MDoN:-KiaXSJKGXO-Kn7YNfzk:b1kpng0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L88)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This isn't {thread,goroutine}-safe.
</blockquote></details>

Yeah, I'm seeing that (thought maybe it was safe since each key is only accessed by one goroutine). Added a lock.

---

*[pkg/util/grpcutil/log.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWgzp_U6Foiae5pIG:-KiaXaEcAiuJaYlv-d1E:b6ofvmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

So instead of logging every second this will log once every 10 seconds. That's an improvement, but do we really want even that spam?
</blockquote></details>

Yeah, I dunno. I think it's valuable to see, sometimes. Let the bikeshedding begin.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/util/grpcutil/log.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWgzp_U6Foiae5pIG:-KiaaRo3eNTU7zQQp11G:b2zxoc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L89)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yeah, I dunno. I think it's valuable to see, sometimes. Let the bikeshedding begin.
</blockquote></details>

`1m` sounds better than `10s`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/grpcutil/log.go, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KiaWgzp_U6Foiae5pIG:-KiaaZeXyzy5afRZnuH_:bubcpz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbfe59dac393252bea94f94aae4f5adbfbaf6446/pkg/util/grpcutil/log.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`1m` sounds better than `10s`.
</blockquote></details>

Changed to 1m.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-:-Kiaaiq1m-sLPt6qOeA9:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/grpcutil/log.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KibDUTaqOMJQF_Elpy9:-KibDUTaqOMJQF_ElpyA:bpwccyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c5ca4ace14614353443045639d3590c054d1c9b/pkg/util/grpcutil/log.go#L100)):*
> ```Go
> 			if t, ok := spamMu.gids[gid]; ok {
> 				if timeutil.Since(t) < time.Minute {
> 					return
> ```

I just noticed that this logic doesn't seem correct now that you're using the `func(){}()` pattern. This `return` returns from the `func()` but we'll merrily proceed to call `log.InfofDepth`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/util/grpcutil/log.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335#-KibDUTaqOMJQF_Elpy9:-KibDlNR2Bncigqg_rdS:b-vjhy18) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c5ca4ace14614353443045639d3590c054d1c9b/pkg/util/grpcutil/log.go#L100)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I just noticed that this logic doesn't seem correct now that you're using the `func(){}()` pattern. This `return` returns from the `func()` but we'll merrily proceed to call `log.InfofDepth`.
</blockquote></details>

Multiple ways to fix, but it might be better to restructure the logic here so that there is a `shouldLog` function that returns true if a grpc log message is not spam or has not been logged about in the last minute. I think this would eliminate the need for the `func()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15335)*

**Pull request merged**
