### PR TITLE
sql: fix panic using Reset() when using sqlstats iterator

### LINKED ISSUE #68785: sql/tests: panic in sqlstats
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3290922&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3290922&tab=artifacts#/) on master @ [e723a85739a2e1b514f5de3221a2177a3a37d0e6](https://github.com/cockroachdb/cockroach/commits/e723a85739a2e1b514f5de3221a2177a3a37d0e6):

Fatal error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x273d2b9]

```
Stack: 

```
goroutine 1203574 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc009dca280, 0x6864950, 0xc01abe4ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:231 +0x126
panic(0x4a61d60, 0x8bd1680)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlushSingleStmtStats.func1(0x6864950, 0xc01abe4ae0, 0xc00b33c370, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:130 +0x59
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1(0x6864950, 0xc01abe4ae0, 0xc00b33c370, 0xc00c67c240, 0x3ff0000000000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:794 +0x43
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec(0xc00b33c370, 0x6864950, 0xc01abe4ae0, 0xc002b8db68, 0xc00b33c370, 0x11ae1a6a97f)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:878 +0xdc
github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn(0xc009dcaf80, 0x6864950, 0xc01abe4ae0, 0xc002b8dbb8, 0xc002b8dbe8, 0x9674a6)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:793 +0x105
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlushSingleStmtStats(0xc00be7a0f0, 0x6864950, 0xc01abe4ae0, 0x0, 0xed8a6a771, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:128 +0x85
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush.func1.1(0xc00be7a0f0, 0x290c9ed9)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:39 +0x45
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlush(0xc00be7a0f0, 0x6864950, 0xc01abe4ae0, 0xc002b8dd10, 0x5245bbe, 0x24)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:73 +0x10a
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush.func1(0x6864950, 0xc01abe4ae0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:38 +0x9c
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/sslocal.(*SQLStats).IterateStatementStats(0xc01196ec40, 0x6864950, 0xc01abe4ae0, 0xc01fe9f9ca, 0xc002b8de10, 0x35, 0xc00c81ee20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/sslocal/sslocal_provider.go:134 +0x93
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush(0xc00be7a0f0, 0x6864950, 0xc01abe4ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:37 +0x225
github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop.func1(0x6864950, 0xc01abe4ae0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/provider.go:115 +0x24c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2(0xc009dca280, 0x6864950, 0xc01abe4ae0, 0x0, 0x0, 0xc00c6032a8)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:434 +0x22b
```
<details><summary>Log preceding fatal error</summary>
<p>

```
    rsg_test.go:736: 25s of 5m0s: 108046 executions, 68505 successful
    rsg_test.go:736: 30s of 5m0s: 128606 executions, 81523 successful
    rsg_test.go:736: 35s of 5m0s: 150284 executions, 95263 successful
    rsg_test.go:736: 40s of 5m0s: 171647 executions, 108751 successful
    rsg_test.go:736: 45s of 5m0s: 193480 executions, 122622 successful
    rsg_test.go:736: 50s of 5m0s: 214918 executions, 136107 successful
    rsg_test.go:736: 55s of 5m0s: 236312 executions, 149678 successful
    rsg_test.go:736: 1m0s of 5m0s: 257902 executions, 163396 successful
E210812 05:23:58.714504 1847606 sql/distsql/server.go:367  [n1,client=127.0.0.1:33510,hostssl,user=root,intExec=read-roles] 1  error setting up flow: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
    rsg_test.go:736: 1m5s of 5m0s: 279174 executions, 176755 successful
E210812 05:24:01.206197 1872224 sql/distsql/server.go:367  [n1,client=127.0.0.1:35612,hostssl,user=root,intExec=read-roles] 2  error setting up flow: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
E210812 05:24:01.206384 1872188 sql/distsql/server.go:367  [n1,client=127.0.0.1:35586,hostssl,user=root,intExec=read-roles] 3  error setting up flow: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4  a panic has occurred!
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +runtime error: invalid memory address or nil pointer dereference
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +(1) attached stack trace
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  -- stack trace:
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | runtime.gopanic
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/usr/local/go/src/runtime/panic.go:965
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | runtime.panicmem
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/usr/local/go/src/runtime/panic.go:212
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | runtime.sigpanic
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/usr/local/go/src/runtime/signal_unix.go:734
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlushSingleStmtStats.func1
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:130
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:794
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:878
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:793
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlushSingleStmtStats
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:128
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush.func1.1
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:39
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).doFlush
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:73
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush.func1
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:38
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/sslocal.(*SQLStats).IterateStatementStats
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/sslocal/sslocal_provider.go:134
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/flush.go:37
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop.func1
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/provider.go:115
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:442
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | runtime.goexit
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +Wraps: (2) runtime error: invalid memory address or nil pointer dereference
E210812 05:24:01.688734 1203574 1@util/log/logcrash/crash_reporting.go:140  [n1] 4 +Error types: (1) *withstack.withStack (2) runtime.errorString
```
</p>
</details>
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestRandomSyntaxFunctions PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #66514 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot branch-release-21.1]
- #63943 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-experience branch-release-20.2]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-experience rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by Azhng**
Previously, when if SQLStats.Reset() is called while iterating
through an iterator, this will cause panics since the iterator
will then return a nil pointer.

This commit changed the iterator to gracefully handle this situation
and prevents panic.

Resolves #68785

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM but please take a review from another member of your team as well

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-:-MguefOa08HYH-pa2gyu:b-2ztpkg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-Mgue__a7nFdY7cDiusU:-Mgue__a7nFdY7cDiusV:b-t81p3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L77)):*
> ```Go
> 			sqlConn.Exec(t, stmt)
> 		}
> 		require.NoError(t, sqlStats.IterateTransactionStats(ctx, &sqlstats.IteratorOptions{}, func(ctx context.Context, id roachpb.TransactionFingerprintID, statistics *roachpb.CollectedTransactionStatistics) error {
> ```

maybe break the long line into multiple lines
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MguePw3CR1eqNhrurWh:-MguePw3CR1eqNhrurWi:b-cep8kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
> ```Go
> func (s *StmtStatsIterator) Next() bool {
> 	s.idx++
> 	if s.idx < len(s.stmtKeys) {
> ```

would be slightly easier to read to invert the condition and `return false` early, then de-indent the rest
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgueXZY7_l19TXCNsNI:-MgueXZY7_l19TXCNsNJ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L146)):*
> ```Go
> func (t *TxnStatsIterator) Next() bool {
> 	t.idx++
> 	if t.idx < len(t.txnKeys) {
> ```

ditto

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MguZSeo32HLvUqAJ4ZB:-MguZSeo32HLvUqAJ4ZC:bh7a1pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L50)):*
> ```Go
> 	fingerprintIDs := make(map[roachpb.StmtFingerprintID]struct{})
> 
> 	// First we collect all the statement fingerprint ID so that we can test the
> ```

nit: IDs
isn't this comment suppose to be on the line above, where you're collecting the fingerprint IDs (creating the fingerprintIDs variable)?
Or change this comment to explain that here you're initializing stats for each fingerprint ID
___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-Mgu_DGPBRG-irPB88sT:-Mgu_DGPBRG-irPB88sU:byzkyqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L64)):*
> ```Go
> 				func(_ context.Context, statistics *roachpb.CollectedStatementStatistics) error {
> 					require.NotNil(t, statistics)
> 					// If we are running out test case, we reset the SQL Stats. The iterator
> ```

nit: out? (our?)
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgudMLP0e_PTS8H5qdT:-MgudMLP0e_PTS8H5qdU:b-mojn1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
> ```Go
> func (s *StmtStatsIterator) Next() bool {
> 	s.idx++
> 	if s.idx < len(s.stmtKeys) {
> ```

Example:
You have 4 stmt keys: A, B, C, D
You start at A and idx is -1, so you will have
A: idx will be update to 0 -> 0 is < 4 -> return true
B: idx will be update to 1 -> 1 is < 4 -> return true
C: idx will be update to 2 -> 2 is < 4 -> return true
D: idx will be update to 3 -> 3 is < 4 -> return true.   <---- shouldn't this be return false, since there is no next after D?
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgubWZ9-EqoGffIUZBm:-MgubWZ9-EqoGffIUZBn:b-v2penz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L69)):*
> ```Go
> 		// If the key is not found (and we expected to find it), the table must
> 		// have been cleared between now and the time we read all the keys. In
> 		// that case we simply skip this key by keep advancing the iterator.
> ```

nit: .. this key and advance the...

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @maryliag)

___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MguZSeo32HLvUqAJ4ZB:-Mguf_tD4LfzdMy3lQ03:b2ahdgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L50)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: IDs
isn't this comment suppose to be on the line above, where you're collecting the fingerprint IDs (creating the fingerprintIDs variable)?
Or change this comment to explain that here you're initializing stats for each fingerprint ID
</blockquote></details>

Moved it to line above.
___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-Mgu_DGPBRG-irPB88sT:-MgufdqJ08O_mLeyrPP-:b-qa4mu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L64)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: out? (our?)
</blockquote></details>

s/out/our/
___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-Mgue__a7nFdY7cDiusU:-MgufnSr1yLjk-9iQ5H-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L77)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe break the long line into multiple lines
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MguePw3CR1eqNhrurWh:-Mgug3OZDkzpYz5sdl-1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

would be slightly easier to read to invert the condition and `return false` early, then de-indent the rest
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgudMLP0e_PTS8H5qdT:-MgugL1-BMFdbbysLEIa:bc5ndo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Example:
You have 4 stmt keys: A, B, C, D
You start at A and idx is -1, so you will have
A: idx will be update to 0 -> 0 is < 4 -> return true
B: idx will be update to 1 -> 1 is < 4 -> return true
C: idx will be update to 2 -> 2 is < 4 -> return true
D: idx will be update to 3 -> 3 is < 4 -> return true.   <---- shouldn't this be return false, since there is no next after D?
</blockquote></details>

In this case, the last line should return true, because the following `.Cur()` is valid. Concretely, consider: 

``` golang
it := NewIter() // with A, B, C, D, idx = -1

it.Next() // true, idx = 0
it.Cur() // A

it.Next() // true, idx = 1
it.Cur() // B

it.Next() // true, idx = 2
it.Cur() // C

it.Next() // true, idx = 3
it.Cur() // D

it.Next() // false, idx = 4
```
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgueXZY7_l19TXCNsNI:-Mgug8nU01xCytihynUq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L146)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @knz)

___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgudMLP0e_PTS8H5qdT:-Mguj0Qo7Qkr-mDIGHmn:bug9zol) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

In this case, the last line should return true, because the following `.Cur()` is valid. Concretely, consider: 

``` golang
it := NewIter() // with A, B, C, D, idx = -1

it.Next() // true, idx = 0
it.Cur() // A

it.Next() // true, idx = 1
it.Cur() // B

it.Next() // true, idx = 2
it.Cur() // C

it.Next() // true, idx = 3
it.Cur() // D

it.Next() // false, idx = 4
```


</blockquote></details>

From the comment on the function, it looks like this function is only checking if there is a Next, that's why the results gets confusing. 
Update the comment to explain this function is actually updating the current value to the next value, and returning true if that was possible and false otherwise

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @maryliag)

___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MgudMLP0e_PTS8H5qdT:-Mgun7w-1W-9C1wuVUGV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/ssmemstorage/ss_mem_iterator.go#L60)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

From the comment on the function, it looks like this function is only checking if there is a Next, that's why the results gets confusing. 
Update the comment to explain this function is actually updating the current value to the next value, and returning true if that was possible and false otherwise
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
just one small comment left (updating to IDs), and :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-:-Mguua_g2oR8JFa4KLkl:b-rma7nb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/sqlstats/sslocal/iterator_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68796#-MguZSeo32HLvUqAJ4ZB:-MguuKPh8ywQYiJH1_ad:bs7bykz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc1d4146e853a8d646b4c562b8c936edb4317285/pkg/sql/sqlstats/sslocal/iterator_test.go#L50)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Moved it to line above.
</blockquote></details>

You forgot the "IDs" part

**Comment by Azhng** [comment]
TFTR!

bros r=knz,maryliag

**Comment by Azhng** [comment]
bors r=knz,maryliag

**Pull request merged**
