### PR TITLE
sql: fix LIMIT not properly applied in INSERT

### LINKED ISSUE #11617: sql: LIMIT not properly applied in INSERT
What did I do:
```
EXPLAIN INSERT INTO foo SELECT * FROM foo LIMIT 20
```

What did I see:
```
0 insert
1 scan
```

What did I expect:
```
0 insert
1 limit
2 scan
```

Note that `INSERT INTO foo SELECT * FROM (SELECT * FROM foo LIMIT 20)` does work properly.

### LINKED ISSUE #11641: sql: must remove parentheses around select clause of INSERT
Found while investigating #11617.

```sql
INSERT INTO bzz(x, y) (VALUES (1, DEFAULT), (2, 3), (3, 4)); -- should work, inserts 3 rows
```

currently fails with:

```
pq: unhandled type parser.DefaultVal
```

This is because the parentheses around the select clause of INSERT are not removed before the VALUES clause is detected/processed.

### PR DESCRIPTION
**Pull request by yznming**
Fixes #11617.
Fixes #11641.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11632)

### CODE REVIEW

**Comment by knz** [comment]
Note: the text in the PR message must be "Fixes #xxxx"

Not "fix #xxxx" like you initially wrote. "Fixes" is a special word detected by Github.

**Comment by knz** [comment]
Ok so I looked at your patch and it already fixes most of the issues.
However we need to consider also VALUES, which can be subject to a LIMIT clause too!

So ensure the following situations work as expected:

```sql
CREATE TABLE bzz(x INT, y INT DEFAULT 42);

INSERT INTO bzz(x) VALUES(1),(2),(3) LIMIT 2;  -- should work, insert only 2 rows

-- however:
INSERT INTO bzz(x,y) VALUES(1,DEFAULT),(2,3),(3,4) LIMIT 2;
-- should fail with an error
```

**Comment by knz** [comment]
Also there is another related issue #11641.
I think it is a bit different but the solution will be in the same area of the code.

**Comment by yznming** [comment]
OK, I will fix them together.

**Comment by yznming** [comment]
@knz done

**Comment by knz** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-KXftbiUCvVrzpQfvfOu:-KXftbiXK0fJOiQjHDRh:byoty9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9477f13c345455a9092fd92e4f5993ee9791ef31/pkg/sql/insert.go#L430)):*
> ```Go
> 	values, ok := wrapped.(*parser.ValuesClause)
> 	if !ok {
> 		return n.Rows, nil
> ```

1) Perhaps here `&parser.Select{Select: wrapped, OrderBy: orderBy, Limit: limit}`
So that the rest of the code doesn't have to do the simplification two times.
(I'm not sure, please check.)

2) avoid creating a `Select` node if both orderBy and limit are nil.

3) please extract this code in a separate function and call this new function from the planNode constructor just after fillDefaults().

---

*[pkg/sql/insert.go, line 459 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-KXfu4SXAWyt62b64YmK:-KXfu4SYiKjoq2f1vr3j:bujcw91) ([raw file](https://github.com/cockroachdb/cockroach/blob/9477f13c345455a9092fd92e4f5993ee9791ef31/pkg/sql/insert.go#L459)):*
> ```Go
> 	}
> 
> 	return &parser.Select{Select: ret, OrderBy: orderBy, Limit: limit}, nil
> ```

Avoid returning a new Select node if both orderBy and limit are nil.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632)*

**Comment by yznming** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-KXftbiUCvVrzpQfvfOu:-KXkd7o_vaIRNBZSGhUw:bcy4sg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9477f13c345455a9092fd92e4f5993ee9791ef31/pkg/sql/insert.go#L430)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) Perhaps here `&parser.Select{Select: wrapped, OrderBy: orderBy, Limit: limit}`
So that the rest of the code doesn't have to do the simplification two times.
(I'm not sure, please check.)

2) avoid creating a `Select` node if both orderBy and limit are nil.

3) please extract this code in a separate function and call this new function from the planNode constructor just after fillDefaults().
</blockquote></details>

@knz do you mean change it like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-KXftbiUCvVrzpQfvfOu:-KXkzWI_DV2-lCw9IsVh:b-f8ncu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9477f13c345455a9092fd92e4f5993ee9791ef31/pkg/sql/insert.go#L430)):*
<details><summary><i>Previously, yznming (Yan Long) wrote…</i></summary><blockquote>

@knz do you mean change it like this?
</blockquote></details>

See https://github.com/yznming/cockroach/pull/2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632)*

**Comment by yznming** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/insert.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-KXftbiUCvVrzpQfvfOu:-KXoDxasi8I2ds9KK5-Y:b-bxjwka) ([raw file](https://github.com/cockroachdb/cockroach/blob/9477f13c345455a9092fd92e4f5993ee9791ef31/pkg/sql/insert.go#L430)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See https://github.com/yznming/cockroach/pull/2
</blockquote></details>

@knz done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632)*

**Comment by knz** [comment]
:lgtm: Thank you for your contribution!

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11632#-:-KXoI33s68Yjx3PwaVj-:buckrpd)*

**Pull request merged**
