### PR TITLE
cmd/benchmark: stage results in buffers

### PR DESCRIPTION
**Pull request by tamird**
This might prevent failures caused by long running multipart uploads.

I'll be looking to merge this pending the outcome of https://teamcity.cockroachdb.com/viewLog.html?buildId=271327&tab=buildResultsDiv&buildTypeId=Cockroach_BenchmarkTests.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/benchmark/main.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXmLl-XU4fBedNmc_4:-KmXmLl-XU4fBedNmc_5:b68g23g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L137)):*
> ```Go
> 	var files []*os.File
> 	for i := 0; i < numIterations; i++ {
> 		f, err := ioutil.TempFile(dir, fmt.Sprintf("bench%02d.txt", i))
> ```

Does this need to use `TempFile`? Seems like you already have a unique directory. I suppose it doesn't hurt though.

---

*[pkg/cmd/benchmark/main.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXliOVmjVA0HNPDKY_:-KmXliOWraMdsdCUbCMi:bppw96v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L191)):*
> ```Go
> 			if _, err := io.Copy(w, f); err != nil {
> 				return errors.Wrapf(err, "could not copy from temp file %s", f.Name())
> 			}
> ```

Do you want to `w.Close()` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-:-KmXmGnTpHKwM6TVD2pZ:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/benchmark/main.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXliOVmjVA0HNPDKY_:-KmXmpGEGzvCRwFZiYfD:b-1xas6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L191)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do you want to `w.Close()` here?
</blockquote></details>

`w` is an `io.Writer`, so it doesn't have a `Close` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/benchmark/main.go, line 191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXliOVmjVA0HNPDKY_:-KmXnG2oh4BYwa-Kzl3K:b-omwzwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L191)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`w` is an `io.Writer`, so it doesn't have a `Close` method.
</blockquote></details>

Ah, I misunderstood the code. You're keeping around the files and using individual defers to close them. Seems fine. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/benchmark/main.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXmLl-XU4fBedNmc_4:-KmXp2QaAG2ZoarIhBfm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L137)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this need to use `TempFile`? Seems like you already have a unique directory. I suppose it doesn't hurt though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/benchmark/main.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502#-KmXmLl-XU4fBedNmc_4:-Kmfi52gOdSEH4lilXML:b-92zfag) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36e6dec92535162fc7f745117d0feea767e8f4/pkg/cmd/benchmark/main.go#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't notice earlier that you switched to using an in-memory buffer. Mea culpa, though your comment on what you did could have been a bit more descriptive than "Done". Oh well, thus we have #16534.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16502)*

**Pull request merged**
