### PR TITLE
ui: display very large ranges in problematic ranges

### LINKED ISSUE #127843: ui: display very large ranges in the problem ranges page
We've seen in escalations (e.g. https://github.com/cockroachlabs/support/issues/3032) that sometimes a range can grow very large and cause instability across the cluster. While we have various defense mechanisms to limit this, it would be nice to display these large ranges as Problem Ranges in the UI. Maybe we can start with a high threshold like 5 or 10GiB.

Jira issue: CRDB-40637

Epic CRDB-39958

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit adds a column in the DB Console's page problematic ranges that displays the ranges that are too large. The threshold is set to be: 8 * the current range max size.

The two screenshots below show how that looks like. In order to generate that, I had to set the threshold multiplier to be 0.8 (instead of 8).
Screenshot 2024-08-15 at 11 13 28 AM

Screenshot 2024-08-15 at 11 14 15 AM

Fixes: #127843

Epic: None

Release note (ui change): Adding too large ranges to the problematic ranges
page in DB Console. If a range is larger than twice the max range
size, it will show up in the problematic ranges page.

### CODE REVIEW

**Review by miraradeva — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-:-O4R9a5q-jtFW2TvaUsY:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @arulajmani, and @iskettaneh)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4R8wlp8Ih56WvUDvLB:-O4R8wlq43Gh1efOJ0ch:bqmqy35) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L368)):*
> ```Go
> }
> 
> func (r *Replica) splitSizeRLocked() (maxBytes int64) {
> ```

Can you add a comment for this new function?
___
*[`pkg/kv/kvserver/replica_metrics_test.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4R9IAA7d2awFzoIpnO:-O4R9IAA7d2awFzoIpnP:b-dfmf1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics_test.go#L60)):*
> ```Go
> 		ctr, down, under, over, _ := calcRangeCounter(1100, threeVotersAndSingleNonVoter, leaseStatus, livenesspb.NodeVitalityMap{
> 			1000: livenesspb.FakeNodeVitality(true), // by NodeID
> 		}, 3 /* numVoters */, 4 /* numReplicas */, 4 /* clusterNodes */, 0 /*rangeTooLargeThreshold*/, 0 /*rangeSize*/)
> ```

nit: I think usually we put spaces within the comment, like `/* rangeTooLargeThreshold */`.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @iskettaneh, and @miraradeva)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RMIEpBu-LY95vBZmj:-O4RMIEpBu-LY95vBZmk:b-xyvflo) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L174)):*
> ```Go
> 	const (
> 		raftLogTooLargeMultiple = 4
> 		rangeTooLargeMultiple   = 8
> ```

Should this be 2, given we set `backpressureRangeSizeMultiplier` to be 2 by default?
___
*[`pkg/kv/kvserver/replica_metrics.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RNVec7mgCS0XjPoEv:-O4RNVec7mgCS0XjPoEw:btoxx0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L176)):*
> ```Go
> 		rangeTooLargeMultiple   = 8
> 	)
> 	largeRangeThreshold := rangeTooLargeMultiple * d.rangeSplitSize
> ```

See my comment below, but I think we should just simplify this to be d.conf.MaxRangeBytes.
___
*[`pkg/kv/kvserver/replica_metrics.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RMyFm-AeCrQs-t0h1:-O4RMyFm-AeCrQs-t0h2:bydg7zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L370)):*
> ```Go
> func (r *Replica) splitSizeRLocked() (maxBytes int64) {
> 	maxBytes = r.mu.conf.RangeMaxBytes
> 	if r.mu.largestPreviousMaxRangeSizeBytes > maxBytes {
> ```

This calculation is pretty contained to `exceedsSplitSizeRLocked`. IMO, we shouldn't let this bleed in elsewhere -- how do you feel about reverting this change and just using `RangeMaxBytes` in the calculation for whether a range is too large or not?
___
*[`pkg/kv/kvserver/replica_metrics_test.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4R9IAA7d2awFzoIpnO:-O4RMd0mERH0jPBcG9kR:b3mgxhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics_test.go#L60)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

nit: I think usually we put spaces within the comment, like `/* rangeTooLargeThreshold */`.
</blockquote></details>

+1. Elsewhere in this file as well.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @arulajmani, and @miraradeva)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RMIEpBu-LY95vBZmj:-O4aDQ-R5MqPDfWLxN4E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L174)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be 2, given we set `backpressureRangeSizeMultiplier` to be 2 by default?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_metrics.go` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RNVec7mgCS0XjPoEv:-O4aDYWb9hHhEfVpnleY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L176)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

See my comment below, but I think we should just simplify this to be d.conf.MaxRangeBytes.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_metrics.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4R8wlp8Ih56WvUDvLB:-O4aDjC_853dBYuSCW9i:bx7voo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L368)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Can you add a comment for this new function?
</blockquote></details>

Removed the functions based on Arul's comments.
___
*[`pkg/kv/kvserver/replica_metrics.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4RMyFm-AeCrQs-t0h1:-O4aDnyz-AMrB5GmKl-T:b-ba7jcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb0219e85b35ba1dfc16a416eeba71aa402942f4/pkg/kv/kvserver/replica_metrics.go#L370)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This calculation is pretty contained to `exceedsSplitSizeRLocked`. IMO, we shouldn't let this bleed in elsewhere -- how do you feel about reverting this change and just using `RangeMaxBytes` in the calculation for whether a range is too large or not?
</blockquote></details>

Sounds good to me.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @arulajmani, and @iskettaneh)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4eqB2H1al90FSxR6En):*
This probably deserves a release note like `Release note(ui): ...`. See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @arulajmani, and @miraradeva)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4eqB2H1al90FSxR6En):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

This probably deserves a release note like `Release note(ui): ...`. See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes.
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: modulo comment. 

> Reviewed 5 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-:-O4g7Wqk2D21NHkfwsKQ:b46bkwm)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @iskettaneh, and @miraradeva)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4g75Z26diBIROAhczG:-O4g75Z26diBIROAhczH:b-jagv7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa28fdefc80c60a61b0c8077d080999311f578d6/pkg/kv/kvserver/replica_metrics.go#L114)):*
> ```Go
> 		raftLogSizeTrusted:       r.mu.raftLogSizeTrusted,
> 		rangeSize:                r.mu.state.Stats.Total(),
> 		rangeSplitSize:           r.mu.conf.RangeMaxBytes,
> ```

Is there benefit to carrying copying over this into `rangeSplitSize` and then using it below? Or, could we get rid of this field entirely and use `d.conf.MaxRangeBytes` in `calcReplicaMetrics` instead?

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129001)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @angles-n-daemons, @arulajmani, and @miraradeva)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129001#-O4g75Z26diBIROAhczG:-O4gBRn73JHNmSh-By2_:b-tmg0h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa28fdefc80c60a61b0c8077d080999311f578d6/pkg/kv/kvserver/replica_metrics.go#L114)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is there benefit to carrying copying over this into `rangeSplitSize` and then using it below? Or, could we get rid of this field entirely and use `d.conf.MaxRangeBytes` in `calcReplicaMetrics` instead?
</blockquote></details>

My bad, I didn't notice that r.mu.conf is passed already. 

Done!

**Pull request merged**
