### PR TITLE
Fix release builds

### PR DESCRIPTION
**Pull request by benesch**
See individual commits for details.

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27343)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/publish-artifacts/main.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-LH4YVffEdMxYmzNglfK:-LH4YVffEdMxYmzNglfL:b-pyoo4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/637a59b35e29c78ae7bb72e89486431940ae1b51/pkg/cmd/publish-artifacts/main.go#L295)):*
> ```Go
> 
> 	if strings.Contains(o.BuildType, "linux") {
> 		binaryName := "./cockroach" + o.Suffix
> ```

Isn't this changing the name from `cockroach-<suffix>` to `cockroach.<suffix>`? Will that break anything? I'd be mildly surprised if it didn't break something.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27343)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/publish-artifacts/main.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-LH4YVffEdMxYmzNglfK:-LH4aH-V0iaZqSvGar_P:bk3gd1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/637a59b35e29c78ae7bb72e89486431940ae1b51/pkg/cmd/publish-artifacts/main.go#L295)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Isn't this changing the name from `cockroach-<suffix>` to `cockroach.<suffix>`? Will that break anything? I'd be mildly surprised if it didn't break something.
</blockquote></details>

It's actually preserving the old behavior (see the line I flagged below). publish-artifacts has always generated names of the form `cockroach.darwin-10.9-amd64`; it's the Makefile/mkrelease which, when used alone, generate names of the form `cockroach-darwin-10.9-amd64`. FYI the publish-artifacts tests check this naming. I actually remembered to run them this time—and they pass!

The inconsistency is dumb, but I broke enough of our build system with the last change that I'm willing to live with it for now.
___
*[pkg/cmd/publish-artifacts/main.go, line 421 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-LH4aEis8UM15S0532TW:-LH4aEitAeZzEgCAuzGc:b15fdvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/21e8648089d5ae2c081f8d5eff26e59614768be6/pkg/cmd/publish-artifacts/main.go#L421)):*
> ```Go
> 	// Replace cockroach{suffix}-{target suffix} with
> 	// cockroach{suffix}.{target suffix}.
> 	remoteName = strings.Replace(remoteName, "-", ".", 1)
> ```

We used to replace the first `-` with a `.` here.

**Review by knz — COMMENTED** [review]
I reviewed all the changes except `public-artifacts/main.go`, and these LGTM.

The remaining file I do not understand (yet?) so I have not reviewed.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-:-LH50MVP06uxhy7x60Z2:b-rak92b)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-:-LH5KZlM2bWtYEkbWLOL:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/publish-artifacts/main.go, line 295 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27343#-LH4YVffEdMxYmzNglfK:-LH5KLPsCDFtmID1SM-w:b-dzxh8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/637a59b35e29c78ae7bb72e89486431940ae1b51/pkg/cmd/publish-artifacts/main.go#L295)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's actually preserving the old behavior (see the line I flagged below). publish-artifacts has always generated names of the form `cockroach.darwin-10.9-amd64`; it's the Makefile/mkrelease which, when used alone, generate names of the form `cockroach-darwin-10.9-amd64`. FYI the publish-artifacts tests check this naming. I actually remembered to run them this time—and they pass!

The inconsistency is dumb, but I broke enough of our build system with the last change that I'm willing to live with it for now.
</blockquote></details>

Ah, got it. This is confusing, but fine for now.

**Comment by benesch** [comment]
bors r=knz,petermattis

**Pull request merged**
