### PR TITLE
roachtest: better merge testing in clearrange

### PR DESCRIPTION
**Pull request by tbg**
Unfortunately, the method to determine the range count is quite slow since
crdb_internal.ranges internally sends an RPC for each range to determine
the leaseholder.

Anecdotally, I've seen ~25% of the merges completed after less than 15
minutes. I know that it's slowing down over time, but @benesch will fix
that.

Also throws in aggressive consistency checks so that when something goes
out of sync, we find out right there.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
Guess what, folks? We got our repro right away!

```
E180906 16:06:58.941627 103825 storage/replica_consistency.go:94  [merge,n8,s8,r9836/3:/Table/53/1/31{599388-753605}] replica (n9,s9):2 is inconsistent: expected checksum ba45b571796dd4ddd8d54087011abab0e0f91cb0d57052b642f384cc70cc98416c093249ef9edaa0b56d531e66d74480009fa1770bdc71b043d969e00f1a771a, got dd16df53ab4308b10934b5eb78b9073c2c6d20ea37e6682e12d75394c26767177536539f0498aef999b9bd30390b3a86bea12a1c3e9949cf6334758af5da7840
--- leaseholder
+++ follower
+0.000000000,0 /Local/Range/Table/53/1/31627334/Transaction/"5a9a2ffe-5ce0-480d-b83d-eaa8b3479155"
+    ts:<zero>
+    value:"\x12\x04\b\x00\x10\x00\x18\x00 \x00(\x002\x81\x01P\xd0$\xdd\x03\n6\n\x10Z\x9a/\xfe\\\xe0H\r\xb8=ꨳG\x91U\x1a\x10\x01k\x12\xbd\x89xf9\x01\xe2\x98F\x00\x01rdsc*\n\b\xba\xb2\xe3Б\xe7\xf6\xa8\x150\xbb\x99\x1d8\x01\x12\x05merge*\n\b\x95\xd8\xfaБ\xe7\xf6\xa8\x152\n\b\xba\xb2\xe3Б\xe7\xf6\xa8\x15:\n\b\xba\xb2\xe3Б\xe7\xf6\xa8\x15B\x0e\b\x03\x12\n\b\xba\xb2\xe3Б\xe7\xf6\xa8\x15H\x01r\x00z\x00\x80\x01\x01"
+    raw mvcc_key/value: 016b12bd89f901e29846000174786e2d5a9a2ffe5ce0480db83deaa8b347915500 12040800100018002000280032810150d024dd030a360a105a9a2ffe5ce0480db83deaa8b34791551a10016b12bd89f901e298460001726473632a0a08bab2e3d091e7f6a81530bb991d380112056d657267652a0a0895d8fad091e7f6a815320a08bab2e3d091e7f6a8153a0a08bab2e3d091e7f6a815420e0803120a08bab2e3d091e7f6a815480172007a00800101
E180906 16:06:58.941858 103825 util/log/crash_reporting.go:477  [merge,n8,s8,r9836/3:/Table/53/1/31{599388-753605}] Reported as error 875dfcad015e4c82845f68a1293eb893
```

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-:-LLjf0g_CVZc61hLLwTv:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-LLjdFK9ESbh8cvL8IR0:-LLjdFKA4iDkpTxLbsK3:b-tpfu70) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dd2b602958f9db8dcc8ca8277082e00f0269e1/pkg/cmd/roachtest/clearrange.go#L97)):*
> ```Go
> 					}
> 				} else {
> 					startHex = "bd" // extremely likely to be the right thing (b'\275').
> ```

loooool
___
*[pkg/cmd/roachtest/clearrange.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-LLje7ijEsuNGbKmSzEd:-LLje7ik3J-kDsoRDHLa:b-kx853t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dd2b602958f9db8dcc8ca8277082e00f0269e1/pkg/cmd/roachtest/clearrange.go#L110)):*
> ```Go
> 					return n
> 				}
> 			}()
> ```

I don't understand why this needs the outer layer of closuring. Isn't this equivalent?

```
conn := c.Conn(ctx, 1)
defer conn.Close()

var startHex string
// NB: set this to false to save yourself some time during development. Selecting
// from crdb_internal.ranges is very slow because it contacts all of the leaseholders.
// You may actually want to run a version of cockroach that doesn't do that because
// it'll still slow you down every time the method returned below is called.
if true {
	if err := conn.QueryRow(
		`SELECT to_hex(start_key) FROM crdb_internal.ranges WHERE "database" = 'bank' AND "table" = 'bank' ORDER BY start_key ASC LIMIT 1`,
	).Scan(&startHex); err != nil {
		t.Fatal(err)
	}
} else {
	startHex = "bd" // extremely likely to be the right thing (b'\275').
}

numBankRanges := func() int {
	var n int
	if err := conn.QueryRow(
		`SELECT COUNT(*) FROM crdb_internal.ranges WHERE substr(to_hex(start_key), 1, length($1::string)) = $1`, startHex,
	).Scan(&n); err != nil {
		t.Fatal(err)
	}
	return n
}
```

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29646)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-LLje7ijEsuNGbKmSzEd:-LLkVWJI5K8kZioMBKpc:b-mb5tgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dd2b602958f9db8dcc8ca8277082e00f0269e1/pkg/cmd/roachtest/clearrange.go#L110)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I don't understand why this needs the outer layer of closuring. Isn't this equivalent?

```
conn := c.Conn(ctx, 1)
defer conn.Close()

var startHex string
// NB: set this to false to save yourself some time during development. Selecting
// from crdb_internal.ranges is very slow because it contacts all of the leaseholders.
// You may actually want to run a version of cockroach that doesn't do that because
// it'll still slow you down every time the method returned below is called.
if true {
	if err := conn.QueryRow(
		`SELECT to_hex(start_key) FROM crdb_internal.ranges WHERE "database" = 'bank' AND "table" = 'bank' ORDER BY start_key ASC LIMIT 1`,
	).Scan(&startHex); err != nil {
		t.Fatal(err)
	}
} else {
	startHex = "bd" // extremely likely to be the right thing (b'\275').
}

numBankRanges := func() int {
	var n int
	if err := conn.QueryRow(
		`SELECT COUNT(*) FROM crdb_internal.ranges WHERE substr(to_hex(start_key), 1, length($1::string)) = $1`, startHex,
	).Scan(&n); err != nil {
		t.Fatal(err)
	}
	return n
}
```

</blockquote></details>

Sure, that works, but I always find it a bit unsavory. Also, note that we're calling `SET statement_timeout` below, though you get lucky and it's on a different conn. Might just be my preference, but I like having stuff defined locally and not floating around as a quasiglobal. Makes my brain melt less.

**Review by tbg — COMMENTED** [review]
This PR is now @benesch's to probably close and reopen under his name.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-:-LLkW9US6Xi5hjtNu-p6:b-8uvbue)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by benesch — APPROVED** [review]
> This PR is now @benesch's to probably close and reopen under his name.

I'm actually going to merge it basically as-is. The one change I made I noted below; doesn't seem worthy of another review cycle. Merging as soon as I verify this passes with the fix from #29677.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-:-LLkso3VA8EzJP1aLX0j:b-9tyb8v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-LLje7ijEsuNGbKmSzEd:-LLksTQ-Db45eboj7ryP:b6e0zk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2dd2b602958f9db8dcc8ca8277082e00f0269e1/pkg/cmd/roachtest/clearrange.go#L110)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Sure, that works, but I always find it a bit unsavory. Also, note that we're calling `SET statement_timeout` below, though you get lucky and it's on a different conn. Might just be my preference, but I like having stuff defined locally and not floating around as a quasiglobal. Makes my brain melt less.
</blockquote></details>

Ack. Returning a closure from a closure ranks as more confusing than a stray state variable to me, but to each his own. I'm going to leave as is.
___
*[pkg/cmd/roachtest/clearrange.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29646#-LLksj8kC7UFEW59w152:-LLksj8kC7UFEW59w153:b-vbk0j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd99414f8227984728f5ea7a86759ef67bd8ffb/pkg/cmd/roachtest/clearrange.go#L125)):*
> ```Go
> 					return err
> 				}
> ```

Added this to speed up merges.

**Comment by benesch** [comment]
All is well.

image

bors r+

**Comment by benesch** [comment]
And now Bors is stuck. Great.

bors r+

**Pull request merged**
