### PR TITLE
sql: add CREATEDB role option

### LINKED ISSUE #52576: sql: add CREATEDB role option
This is a new role option which allows a non-admin user to create new databases. The user who issues the command is the owner of the new database. As the owner, the user should also be able to rename the database via `ALTER DATABASE ... RENAME`.

### PR DESCRIPTION
**Pull request by solongordon**
Fixes #52576

Release note (sql change): Introduced a new CREATEDB role option. This
grants non-admin roles the ability to create new databases. It can be
conferred via `ALTER ROLE <role> CREATEDB` and revoked via `ALTER ROLE
<role> NOCREATEDB`.

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
There's also a case where we check for CREATEDB privilege when renaming databases, I think there's a todo left there (line 39 of rename_database.go) can you add the check there too?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-:-MEyrOzB6iXBEGRU4zfb:bhh1n9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/database, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MEyqybEDvY2gk4_uDJ-:-MEyqybFCSQOrFSeZ-Z-:b1kzupn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2723aa7803eaab0b1d49dd7775d22d027558b655/pkg/sql/logictest/testdata/logic_test/database#L214)):*
> ```
> 
> statement error user testuser does not have CREATEDB privilege
> CREATE DATABASE privs
> ```

nit: missing endline
___
*[pkg/sql/parser/sql.y, line 6236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MEyrsnDAmyIJGjEoteQ:-MEyrsnE7c8D0yc-_rOp:bpwne99) ([raw file](https://github.com/cockroachdb/cockroach/blob/2723aa7803eaab0b1d49dd7775d22d027558b655/pkg/sql/parser/sql.y#L6236)):*
> ```Yacc
> | NOCREATEDB
> 	{
> 		$$.val = tree.KVOption{Key: tree.Name($1), Value: nil}
> ```

tabs here

**Review by solongordon — COMMENTED** [review]
Good call, I updated the RENAME logic as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-:-MF0yrWQ2e4eAfq0bTZe:b-jsruw5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/parser/sql.y, line 6236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MEyrsnDAmyIJGjEoteQ:-MF0yvwvCFD4r3z0cUWZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2723aa7803eaab0b1d49dd7775d22d027558b655/pkg/sql/parser/sql.y#L6236)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

tabs here
</blockquote></details>

Done.

**Review by RichardJCai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/rename_database, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MFBdvmI8zfjwHjn-ddV:-MFBdvmI8zfjwHjn-ddW:b-s10e9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec4d8149769df0c1629aecd1c04cf254efae867/pkg/sql/logictest/testdata/logic_test/rename_database#L120)):*
> ```
> t
> 
> # Test that owners can rename databases as long as they have the CREATEDB
> ```

nit: And they must own the db

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52831)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/rename_database, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MFBdvmI8zfjwHjn-ddV:-MFBoRVDAGW3vO0JzN-5:b-htl0mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec4d8149769df0c1629aecd1c04cf254efae867/pkg/sql/logictest/testdata/logic_test/rename_database#L120)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: And they must own the db
</blockquote></details>

It says "owners" :)

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52831)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)
> 
> _[pkg/sql/logictest/testdata/logic_test/rename_database, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52831#-MFBdvmI8zfjwHjn-ddV:-MFBoRVDAGW3vO0JzN-5:b-htl0mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ec4d8149769df0c1629aecd1c04cf254efae867/pkg/sql/logictest/testdata/logic_test/rename_database#L120)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> It says "owners" :)

What if the owner doesn't actually own the object :O 
Just kidding I somehow missed that on my pass through. LGTM!

**Pull request merged**
