### PR TITLE
allocsim: Use tc for fine-grained, correct injection of fake latency

### PR DESCRIPTION
**Pull request by a-robinson**
Rip out the outgoing-connection based logic that we couldn't get working
properly. On the good ol' 50ms between nodes setup with all 32 workers
hitting node 2, the code from #13797 does the following on an azworker:

```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:2_______________3:3
    1m0s    493.9    370.1   86.4ms        0      117           39/8/14           39/25/2            39/2/2
    2m0s    486.8    427.3   74.9ms        0      213          71/10/22           71/48/7            71/9/5
    3m0s    470.9    442.5   72.3ms        0      399         133/22/25         133/87/17          133/20/7
    4m0s    471.9    449.4   71.2ms        0      408         136/20/32         136/91/23          136/21/9
    5m0s    461.9    452.5   70.7ms        0      672         224/34/34        224/145/34          224/38/9
    6m0s    465.9    452.5   70.7ms        0      786         262/41/44        262/174/42         262/44/13
```

A more extreme algorithm gets the latency down to the low 50s of
milliseconds per operation.

Also, add a couple additional allocsim workload configs that rely on the new tc mode to work properly.

If you guys are fine with me basically giving up on the previous approach, I'll follow up with a tweak to allow for running the previous uniform latency workloads on MacOS.

@petermattis @bdarnell 

Initial run of the new `uneven-latency` config:

```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:2_______________3:3

    1m0s    736.8    571.2   56.0ms        0      177          59/12/21           59/32/0            59/1/0
    2m0s    610.7    610.6   52.4ms        0      399         133/22/26          133/85/7          133/18/0
    3m0s    599.9    609.8   52.5ms        0      420         140/25/29         140/88/17          140/21/8
    4m0s    633.9    610.8   52.4ms        0      771         257/45/29        257/169/28         257/37/16
    5m0s    605.9    608.3   52.6ms        0      795         265/47/31        265/176/41         265/38/29
```

Initial run of the new `multiple-nodes-per-locality` config:

```
_elapsed__ops/sec__average__latency___errors_replicas_______________1:1_______________2:1_______________3:1_______________4:2_______________5:2_______________6:2_______________7:3_______________8:3_______________9:3
    1m0s    465.9    377.9   84.6ms        0      120           13/3/19            13/4/5            14/4/4            13/5/7            13/5/5            14/7/6            13/4/4            14/2/6            13/5/0
    2m0s    519.8    430.5   74.3ms        0      220           25/4/26           24/4/10            23/5/9          24/15/12          25/14/11          25/16/10            24/5/8           25/5/11            25/5/5
    3m0s    475.9    445.4   71.8ms        0      414           46/8/34           46/9/14           44/7/18          48/29/21          48/30/23          45/28/16          45/10/17           46/8/21            46/7/9
    4m0s    496.9    458.0   69.8ms        0      417           46/7/37           46/8/16           45/8/19          48/31/24          49/32/26          45/30/19           46/8/23           46/7/25            46/8/9
    5m0s    448.9    459.7   69.6ms        0      717          78/15/44          78/16/20          78/16/21          79/47/35          81/46/39          84/49/29          81/14/28          81/15/32          77/17/10
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13902)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/allocsim/main.go, line 437 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ2-AbGQxZDbEams_r:-KeZ2-AbGQxZDbEams_s:bb07qfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/allocsim/main.go#L437)):*
> ```Go
> 			separateAddrs = true
> 			log.Info(context.Background(),
> 				"using a separate IP address for each node -- note that this will break on MacOS")
> ```

Perhaps exit if `runtime.GOOS == "darwin"`.

---

*[pkg/cmd/internal/tc/tc.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ3lGP7HML3bUSpyhE:-KeZ3lGP7HML3bUSpyhF:b-e6b2fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L45)):*
> ```Go
> // NewController creates and returns a controller that will modify the traffic
> // routing for the provided interfaces.
> func NewController(ifces []string) *Controller {
> ```

Might be more convenient to use `...string`.

`ifces` doesn't exactly roll off the tongue. Perhaps `interfaces`.

---

*[pkg/cmd/internal/tc/tc.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ5XjXTJwDY9Eiv0MN:-KeZ5XjYGBfBUOiuubPr:b-8egq1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L63)):*
> ```Go
> 		}
> 		out, err = exec.Command("/bin/sh", "-c", fmt.Sprintf("sudo tc class add dev %s parent %d: classid %d:%d htb rate 100mbit",
> 			ifce, rootHandle, rootHandle, defaultClass)).Output()
> ```

I'm not familiar with `tc`. What is the `100mbit` doing?

---

*[pkg/cmd/internal/tc/tc.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ5qaOk5V0IffT96F8:-KeZ5qaOk5V0IffT96F9:b4y0kxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L102)):*
> ```Go
> 		out, err := exec.Command("/bin/sh", "-c", fmt.Sprintf("sudo tc qdisc del dev %s root", ifce)).Output()
> 		if err != nil {
> 			return errors.Wrapf(err, "failed to remove tc rules for %q -- you may have to remove them manually: %s", ifce, out)
> ```

Instead of returning here, perhaps you should try to cleanup all of the interfaces and return a concatenation of the errors.

---

*[pkg/rpc/context.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ6NYegRTkNYAJuhmn:-KeZ6NYegRTkNYAJuhmo:bbj5dfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/rpc/context.go#L62)):*
> ```Go
> // connections. It should only ever be set by testing code, and is not thread
> // safe (so it must be initialized before the server starts).
> var SourceAddr net.Addr
> ```

If you allowed this to be configured via an env var, could you get rid of the flag parsing ugliness in `allocsim.handleStart`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-:-KeZ6bw72Oc6RsdqgT_-:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

I'm fine with making all of this linux-only; no need to develop a separate mac-only fallback. 

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/internal/localcluster/localcluster.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZgMdUy1MOWTEkR6oC:-KeZgMdUy1MOWTEkR6oD:bbvnj3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/localcluster/localcluster.go#L87)):*
> ```Go
> }
> 
> // New creates a cluster of size nodes.
> ```

Document the `separateAddrs` flag.

---

*[pkg/cmd/internal/localcluster/localcluster.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZg3DZ-XQgduu0GMF6:-KeZg3D__H0e_1wrrWeP:bhgf1kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/localcluster/localcluster.go#L145)):*
> ```Go
> 		return fmt.Sprintf("127.1.1.%d", nodeIdx+1)
> 	}
> 	return "localhost"
> ```

Either name the method `Host` or use `127.0.0.1` instead of `localhost`.

---

*[pkg/cmd/internal/tc/tc.go, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZh0_QDNmHcua3QjRf:-KeZh0_QDNmHcua3QjRg:but6clk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L17)):*
> ```Go
> // Package tc contains utility methods for using the Linux tc (traffic control)
> // command to mess with the network links between cockroach nodes running on
> // the local machine.
> ```

Mention that this requires passwordless sudo to run `tc`. 

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-KeZhDmFx4bMIlpWQ8sJ:bhi0sod) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
> ```Go
> func (c *Controller) Init() error {
> 	for _, ifce := range c.ifces {
> 		_, _ = exec.Command("/bin/sh", "-c", fmt.Sprintf("sudo tc qdisc del dev %s root", ifce)).Output()
> ```

Why do these all use `sh -c`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-:-KeZhc1WxjMAdvJVqq_v:bv8kilk)*

**Comment by a-robinson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/cmd/allocsim/main.go, line 437 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ2-AbGQxZDbEams_r:-KeZ8Qy02GJP0BgjpPYU:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/allocsim/main.go#L437)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps exit if `runtime.GOOS == "darwin"`.
</blockquote></details>

Good call, done.

---

*[pkg/cmd/internal/tc/tc.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ3lGP7HML3bUSpyhE:-KeZ8cR09C1HAbuhxAZe:b-e49cb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might be more convenient to use `...string`.

`ifces` doesn't exactly roll off the tongue. Perhaps `interfaces`.
</blockquote></details>

Done. The naming was stolen from some etcd code which I had previously been depending on to get the default interface, probably originally done because `interface` is a keyword

---

*[pkg/cmd/internal/tc/tc.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ5XjXTJwDY9Eiv0MN:-KeZ8qPUQok7oWcYU2cu:b-amebl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not familiar with `tc`. What is the `100mbit` doing?
</blockquote></details>

You have to specify a bandwidth limit on classes of type `htb` (hierarchy token bucket), and `htb` is the simplest type of class that allows an arbitrary number of children. The 100mbit number is meant to be an arbitrarily high bandwidth limit. I've added a comment.

---

*[pkg/cmd/internal/tc/tc.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ5qaOk5V0IffT96F8:-KeZFSOn36jX_sn9Omhb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/cmd/internal/tc/tc.go#L102)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Instead of returning here, perhaps you should try to cleanup all of the interfaces and return a concatenation of the errors.
</blockquote></details>

Done.

---

*[pkg/rpc/context.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ6NYegRTkNYAJuhmn:-KeZklkip8gVmj8lYhEl:b2hjrau) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/rpc/context.go#L62)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If you allowed this to be configured via an env var, could you get rid of the flag parsing ugliness in `allocsim.handleStart`?
</blockquote></details>

We'll have to do the parsing a little more often, but that'll indeed simplify the code a bit. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by a-robinson** [comment]
TFTRs!

I've also added a third config that simulates the latency of having replicas in us-east-1, us-east-2, and ap-southeast-2 (Sydney)

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/internal/localcluster/localcluster.go, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZgMdUy1MOWTEkR6oC:-KeZpjziKIEWSgaQEFpl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/localcluster/localcluster.go#L87)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Document the `separateAddrs` flag.
</blockquote></details>

Done.

---

*[pkg/cmd/internal/localcluster/localcluster.go, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZg3DZ-XQgduu0GMF6:-KeZplYK9Q30tjt5uRD1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/localcluster/localcluster.go#L145)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Either name the method `Host` or use `127.0.0.1` instead of `localhost`.
</blockquote></details>

Done.

---

*[pkg/cmd/internal/tc/tc.go, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZh0_QDNmHcua3QjRf:-KeZppfxJ1laOcNET4zz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L17)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Mention that this requires passwordless sudo to run `tc`. 
</blockquote></details>

Done.

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-KeZq4b2ndRQuAD9Uu2l:b-gizawm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why do these all use `sh -c`?
</blockquote></details>

No real reason, I just wanted the code to be as similar as possible to my manual testing of the tc commands. Want me to change them to something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-:-KeZsR-7aA_VdzRNNNuQ:b3xzxoc)*

**Comment by bdarnell** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-KeZtW3fwmhU5fnp_Cux:bdx48bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

No real reason, I just wanted the code to be as similar as possible to my manual testing of the tc commands. Want me to change them to something else?
</blockquote></details>

I generally prefer to avoid involving the shell unless shell features are required, although this does require an annoying amount of extra punctuation: `exec.Command("sudo", "tc", "qdisc", "del", "dev", ifce, "root")`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by a-robinson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-Ke_-2P5JCxF4wYCih9s:b-zfqg9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I generally prefer to avoid involving the shell unless shell features are required, although this does require an annoying amount of extra punctuation: `exec.Command("sudo", "tc", "qdisc", "del", "dev", ifce, "root")`
</blockquote></details>

Yeah, it makes for a lot of verbosity on some of these comands, particularly the one below. Would you be fine with me leaving these as is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by bdarnell** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-Ke_0Um6uLgGr6LR0SHa:babik1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yeah, it makes for a lot of verbosity on some of these comands, particularly the one below. Would you be fine with me leaving these as is?
</blockquote></details>

You could also do `exec.Command("sudo", ...strings.Split(fmt.Sprintf("tc qdisc add..."), " ")`, which should prevent any shell injections here while leaving the command in a mostly copy-pasteable format. It doesn't matter too much in this little test, but I'm just paranoid about shell injection, especially in a program that's already assuming it's run by a user with passwordless sudo. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by a-robinson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/cmd/internal/tc/tc.go, line 56 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZhDmFx4bMIlpWQ8sI:-Ke_6tOz4snPs7KBInoV:bl1h72v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea0160407c893e173ec620d348aa376e9e0d0a6/pkg/cmd/internal/tc/tc.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You could also do `exec.Command("sudo", ...strings.Split(fmt.Sprintf("tc qdisc add..."), " ")`, which should prevent any shell injections here while leaving the command in a mostly copy-pasteable format. It doesn't matter too much in this little test, but I'm just paranoid about shell injection, especially in a program that's already assuming it's run by a user with passwordless sudo. 
</blockquote></details>

Ok, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by tamird** [comment]
Reviewed 1 of 7 files at r3.
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/context.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ6NYegRTkNYAJuhmn:-Ke_7nuWB5s81cJY41ug:byp65ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/rpc/context.go#L62)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

We'll have to do the parsing a little more often, but that'll indeed simplify the code a bit. Done.
</blockquote></details>

How about an explicit boolean via `EnvString`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by a-robinson** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/context.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ6NYegRTkNYAJuhmn:-Ke_8aebmtIShSr7aMyw:b-herxl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/rpc/context.go#L62)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

How about an explicit boolean via `EnvString`?
</blockquote></details>

What value does that add over checking whether the environment variable is empty? A source addr set to empty doesn't seem particularly useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Comment by tamird** [comment]
Review status: 1 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/context.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902#-KeZ6NYegRTkNYAJuhmn:-Ke_9e9Nle2z1xBjyTjS:b-krmtqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5036c089cc441a188207d91326328a3e1529b70/pkg/rpc/context.go#L62)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

What value does that add over checking whether the environment variable is empty? A source addr set to empty doesn't seem particularly useful
</blockquote></details>

It's not useful, but it's usually better to report misconfiguration than to silently ignore it. It's harmless here, but there's something to be said for setting precedent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13902)*

**Pull request merged**
