### PR TITLE
roachtest: enable metamorphic expiration leases in most tests

### LINKED ISSUE #103188: roachtest: metamorphically enable expiration-based leases
This will increase test coverage of expiration leases, but we can't do this for roachperf benchmarks.

Jira issue: CRDB-27877

Epic CRDB-25212

### PR DESCRIPTION
**Pull request by erikgrinaker**
**roachprod: add option for initial cluster settings**

This patch adds a roachprod option `ClusterSettingsOption` that can be used to pass arbitrary initial cluster settings during cluster start.

It also no longer sets `server.remote_debugging.mode = 'any'`, since this setting was removed in 21.2.

  
**roachtest: add option for metamorphic expiration leases**

To increase test coverage of expiration-based leases, this patch adds an opt-in test parameter `Leases` that allows tests to enable them either metamorphically or explicitly.

**roachtest: add TPCC benchmarks with expiration leases**

This patch adds TPCC benchmark variants with expiration leases for a few representative configurations.

**roachtest: enable metamorphic expiration leases in most tests**

This patch uses metamorphic expiration leases in most non-benchmark roachtests. There will likely be some fallout from this, in particular for timing/latency-sensitive tests, but we can deal with that as it happens.

Resolves #103188.
Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 98 of 98 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Review by andrewbaptist — APPROVED** [review]
:lgtm: 
Its a little unfortunate that we need to add the new parameter in so many places, but I don't see an easy alternative.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103190#-:-NVF_ttUCkHKvpXOqa2b:bw1mewr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Comment by erikgrinaker** [comment]
The alternative would be to opt-out, but I'd rather we accidentally don't enable metamorphism in some tests than accidentally enable it in tests/benchmarks where they cause flake, confusion, and unnecessary work.

**Comment by erikgrinaker** [comment]
I'm going to merge this to start getting some runtime in the nightlies. If test-eng has comments on the plumbing then leave a review as usual and I'll post a follow-up PR.

bors r+

**Pull request merged**
