### PR TITLE
opt: improve various composite-ness checks

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: improve composite check for PushFilterIntoSetOp

Use `CanBeCompositeSensitive` instead of disallowing any filters
involving composite columns.

Release note: None

#### opt: improve composite check for Project FDs

Release note: None

#### opt: improve composite check for join filter remapping

Use CanBeCompositeSensitive to allow remapping insensitive join
filters.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-:-MIyexX-DpQ_kbfcPMRj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/norm/join_funcs.go, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-MIyead59tReRa0h_S9B:-MIyead59tReRa0h_S9C:b-zhll7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bc1751da12261821b558163f3f8078427588607/pkg/sql/opt/norm/join_funcs.go#L337)):*
> ```Go
> 
> 	allowCompositeEncoding := !memo.CanBeCompositeSensitive(c.mem.Metadata(), src)
> 	// Map each column in src to one column in dst. We choose an arbitrary column
> ```

[nit] add a blank line above this
___
*[pkg/sql/opt/norm/join_funcs.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-MIyeGbJ4O8mGw1NEXh0:-MIyeGbJ4O8mGw1NEXh1:biombh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bc1751da12261821b558163f3f8078427588607/pkg/sql/opt/norm/join_funcs.go#L408)):*
> ```Go
> //
> // TODO(rytaft): In the future, we may want to allow the mapping if the
> // filter involves a comparison operator, such as x < 5.
> ```

you can remove this TODO :) 
(and update the comment)

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-:-MIzHWxT9Hnzj8MEKnNl:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/norm/join_funcs.go, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-MIyead59tReRa0h_S9B:-MIzGOOB2VLDxW5J40Sh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bc1751da12261821b558163f3f8078427588607/pkg/sql/opt/norm/join_funcs.go#L337)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] add a blank line above this
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join_funcs.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55194#-MIyeGbJ4O8mGw1NEXh0:-MIzHVVi-RVC0jpu7U4X:b-xiw2c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bc1751da12261821b558163f3f8078427588607/pkg/sql/opt/norm/join_funcs.go#L408)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you can remove this TODO :) 
(and update the comment)
</blockquote></details>

Nice catch, done!

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55194)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Pull request merged**
