### PR TITLE
sql: use ComponentStats for all exec stats

### PR DESCRIPTION
**Pull request by RaduBerinde**
In this change we use ComponentStats for all execution statistics
passed through spans and remove the other protos. ComponentStats now
includes "input" statistics, used only with the row execution.

We improve the FinishTrace callback in ProcessorBase to a more
specific ExecStatsForTrace, which is only called if we are tracing.
The callback returns the ComponentStats.

In terms of EXPLAIN ANALYZE diagrams, the differences are minor
(ordering of stats, switching from "rows" to "tuples" for
consistency).

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 45 of 48 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56635)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/trace_test.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MM-vxDj3VDk6mZkxAXN:-MM-vxDj3VDk6mZkxAXO:bji621u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ecd756018e11daa912e7c4d9c0fe0d85b60145e/pkg/sql/trace_test.go#L109)):*
> ```Go
> 				rows, err := sqlDB.Query(
> 					"SELECT count(message) FROM crdb_internal.session_trace " +
> 						"WHERE message LIKE '%cockroach.stat.KV.tuples.read: 0%'",
> ```

nit: I'd prefer to keep kv lowercase in the tag key for consistency
___
*[pkg/sql/colflow/vectorized_meta_propagation_test.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMF_9Xw868WP6ReNi1Z:-MMF_9Xw868WP6ReNi1_:b-hv78g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6662df0441cebb55ed2a3466c8985a767cbf61ad/pkg/sql/colflow/vectorized_meta_propagation_test.go#L82)):*
> ```Go
> 		[]execinfrapb.MetadataSource{col},
> 		nil, /* toClose */
> 		nil, /* execStatsToTrace */
> ```

nit: `s/To/For` here and eslewhere
___
*[pkg/sql/execstats/traceanalyzer.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMF__Iw3yBgQrKfVoDV:-MMF__Iw3yBgQrKfVoDW:b-fp8un8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6662df0441cebb55ed2a3466c8985a767cbf61ad/pkg/sql/execstats/traceanalyzer.go#L135)):*
> ```Go
> 		return 0, errors.Errorf("could not get network bytes from %T", dss)
> 	}
> 	return int64(v.NetRx.BytesReceived.Value() + v.NetTx.BytesSent.Value()), nil
> ```

This will be technically equivalent to the code before because at most one of these fields is set, but it makes me uncomfortable to add them both together. Maybe add a comment about this expectation or change the code to be more explicit (checking and returning each field explicitly)? What do you think?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/execstats/traceanalyzer.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMF__Iw3yBgQrKfVoDV:-MMHBWTw4OIsb5vnps8k:bxdcev6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6662df0441cebb55ed2a3466c8985a767cbf61ad/pkg/sql/execstats/traceanalyzer.go#L135)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This will be technically equivalent to the code before because at most one of these fields is set, but it makes me uncomfortable to add them both together. Maybe add a comment about this expectation or change the code to be more explicit (checking and returning each field explicitly)? What do you think?
</blockquote></details>

What should be the behavior here when neither is set? Error or return 0?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56635)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execstats/traceanalyzer.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMF__Iw3yBgQrKfVoDV:-MMHLks01oeBAb3Fs4Vg:b-wlhcqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6662df0441cebb55ed2a3466c8985a767cbf61ad/pkg/sql/execstats/traceanalyzer.go#L135)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What should be the behavior here when neither is set? Error or return 0?
</blockquote></details>

Good question. My initial reaction is to return 0 to make it as friendly as possible, but I think this file goes down the "return an error if stats are not well-structured" route. I think that a component with a stream ID but neither tx nor rx stats set is badly-formed, so I would return an error here.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-:-MMI0hGl9u1shaysfoT3:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/execstats/traceanalyzer.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMF__Iw3yBgQrKfVoDV:-MMI0UNVAaT2nwwZsL-q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6662df0441cebb55ed2a3466c8985a767cbf61ad/pkg/sql/execstats/traceanalyzer.go#L135)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Good question. My initial reaction is to return 0 to make it as friendly as possible, but I think this file goes down the "return an error if stats are not well-structured" route. I think that a component with a stream ID but neither tx nor rx stats set is badly-formed, so I would return an error here.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-:-MMKVoWP1Mq4GIpB0-yK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execstats/traceanalyzer.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMKVZIZAKrkdQYwQAiQ:-MMKVZIZAKrkdQYwQAiR:bxa4w49) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ea589101a0b0dc423a8b84c1ffd0faeb848a69/pkg/sql/execstats/traceanalyzer.go#L135)):*
> ```Go
> 		return 0, errors.Errorf("could not get network bytes from %T", dss)
> 	}
> 	// We expect exactly of BytesReceived and BytesSent to be set.
> ```

nit: `s/exactly of/exactly one of`
___
*[pkg/sql/execstats/execstatspb/component_stats.go, line 25 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56635#-MMKVikbElOmUEmQ096v:-MMKVikbElOmUEmQ096w:bkllmzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/21ea589101a0b0dc423a8b84c1ffd0faeb848a69/pkg/sql/execstats/execstatspb/component_stats.go#L25)):*
> ```Go
> 	result := make(map[string]string, 4)
> 	s.formatStats(func(key string, value interface{}) {
> 		// The key becomes a tracing span tag. Replace spaces with dotes and use
> ```

nit: `s/dotes/dots`

**Pull request merged**
