### PR TITLE
testcluster: avoid infinite hang in WaitForNStores

### PR DESCRIPTION
**Pull request by tbg**
Fail gracefully instead of timing out the test suite.

See https://github.com/cockroachdb/cockroach/pull/80619#issuecomment-1110994494

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Hold off, did something silly here. Will ping.

**Comment by tbg** [comment]
Ping.

**Review by srosenberg — APPROVED** [review]
Thanks for adding the timeout!

**Comment by tbg** [comment]
bors r=srosenberg

**Pull request merged**
