### PR TITLE
ui: update components dep

### LINKED ISSUE #56959: ui: DB Console branding refresh
Update logo:

* Site header
* Login page
* Favicon 

Update primary color Green (#37A806) to Purple (#6933FF) on buttons and other primary states
Note: Success states like alerts and badges should stay green

Resources

[DB Console Brand Updates](https://www.figma.com/file/cxE2QFATR24EStFTeHNdJc/obsrv_console-brand-update?node-id=1%3A10)

[Figma Design System](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System?node-id=6398%3A39)

Since the DB Console uses Stylus for CSS, it may be difficult to use the design tokens from the design system here: https://github.com/cockroachdb/ui/pull/137

It is *not* a requirement to use the design tokens but if there's a straightforward way to import these then please do. Our assumption is that making the modifications directly in the DB Console is fine for now but we don't want to add Stylus support to the UI repository since we're trying to phase it out.

### PR DESCRIPTION
**Pull request by vladlos**
requested version of package in admin-ui-components includes:
 - brand update changes (primary color, new link colors)
 - transactions page followups (default per page value, txn font)

Resolves: #56959, #55131

Release note (ui): Changed defualt per page value on Transactions page to 20, minor style updates

https://github.com/cockroachdb/yarn-vendored/pull/45

### CODE REVIEW

**Comment by dhartunian** [comment]
@elkmaster Please revise the commit and PR description with an explanation of what changes have been made. There are user facing changes here so the release note cannot be "none"

**Comment by elkmaster** [comment]
@dhartunian , done

**Comment by dhartunian** [comment]
@elkmaster can you also link to the `yarn-vendored` PR in the description? then we'll be good to go. thanks!

**Review by dhartunian — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57824#-:-MOJ1cwq1SrCqReFkFs-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
