### PR TITLE
docs: Pass in Jira tickets in the body of product change issues

### PR DESCRIPTION
**Pull request by nickvigilante**
Epic and issue references are now pointing to the associated Jira
tickets.

Fixes DOC-7019

Release note: None

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante)

___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZ5z3EfBEe-moLRJK:-NQeZ5z3EfBEe-moLRJL:b-e5zzs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab9d958309c460ae3e06602a5e3c50346126ed2/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L688)):*
> ```Go
> 	}
> 	err := queryGraphQL(query, queryVariables, token, &search)
> 	if err != nil {
> ```

Does it mean we swallow the error here? What happens in this case?
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 677 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZk_H3NYXXNGSow-x:-NQeZk_H3NYXXNGSow-y:bfzug99) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L677)):*
> ```Go
> // getJiraIssueFromGitHubIssue is specified as a function closure to allow for testing
> // of getJiraIssueFromGitHubIssue* methods.
> var getJiraIssueFromGitHubIssue = func(org, repo string, issue int, token string) string {
> ```

Is there any particular reason to change from the function declaration style to the var one? For a top level function it looks unusual to me.
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQe_tLB-eO8_91rqmnt:-NQe_tLB-eO8_91rqmnu:b-11m6cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L703)):*
> ```Go
> 		jiraIssue = jiraIssuePartRE.FindString(exalateRef)
> 	}
> 	jiraGHIssueCache[key] = jiraIssue
> ```

I see the cache is populated, but it's not used anywhere. Maybe I'm missing something?
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeaNMkDApQjilnX3CU:-NQeaNMkDApQjilnX3CV:b3oin9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L707)):*
> ```Go
> }
> 
> func Split(r rune) bool {
> ```

maybe rename the function to something like `splitBySlashOrHash` so it's not exported (lowercase).

**Review by nickvigilante — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 688 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZ5z3EfBEe-moLRJK:-NQf0stZ2P8RCL4tYurG:b-96np1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab9d958309c460ae3e06602a5e3c50346126ed2/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L688)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Does it mean we swallow the error here? What happens in this case?
</blockquote></details>

I made it here so that we don't swallow the error in the event of a network outage. I didn't want the lack of issue or epic reference to block the creation of a docs issue ticket.
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 677 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZk_H3NYXXNGSow-x:-NQeyVnk7F3uIHYOe3AW:b4pa9zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L677)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Is there any particular reason to change from the function declaration style to the var one? For a top level function it looks unusual to me.
</blockquote></details>

Certain test cases that once did not rely on network resources now rely on network resources. I had a conversation with Celia and David H about this, and the best way that I could make my tests not rely on network resources was to use https://github.com/cockroachdb/cockroach/tree/master/pkg/testutils, and David suggested I change that function to be a variable declaration that I could then defer as part of this test: https://github.com/nickvigilante/cockroach/blob/doc-7019/pkg/cmd/docs-issue-generation/docs_issue_generation_test.go#L227
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQe_tLB-eO8_91rqmnt:-NQezRJeDJS9OdkpNNiv:b9rx1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L703)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I see the cache is populated, but it's not used anywhere. Maybe I'm missing something?
</blockquote></details>

Deleted the artifact.
___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 707 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeaNMkDApQjilnX3CU:-NQezHHI0PdY0KHxbNR8:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L707)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

maybe rename the function to something like `splitBySlashOrHash` so it's not exported (lowercase).
</blockquote></details>

Done!

**Review by rail — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nickvigilante)

___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 677 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZk_H3NYXXNGSow-x:-NQjYAS3-Y_iCRW4aMUR:bqyhtkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L677)):*
<details><summary><i>Previously, nickvigilante (Nick Vigilante) wrote…</i></summary><blockquote>

Certain test cases that once did not rely on network resources now rely on network resources. I had a conversation with Celia and David H about this, and the best way that I could make my tests not rely on network resources was to use https://github.com/cockroachdb/cockroach/tree/master/pkg/testutils, and David suggested I change that function to be a variable declaration that I could then defer as part of this test: https://github.com/nickvigilante/cockroach/blob/doc-7019/pkg/cmd/docs-issue-generation/docs_issue_generation_test.go#L227
</blockquote></details>

You also need to update the test to reflect the function signature change. Otherwise LGTM.
`  panic: reflect.Set: value of type func(string, string, int, string) string is not assignable to type func(string, string, int, string) (string, error)`



_Code quote:_
```Go
getJiraIssueFromGitHubIssue
```

**Review by nickvigilante — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[`pkg/cmd/docs-issue-generation/docs_issue_generation.go` line 677 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-NQeZk_H3NYXXNGSow-x:-NQkoRG9AM85r_rx-gR6:bp3n08l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a504ae95e57bac82d63e32aaab69d94a00dd830b/pkg/cmd/docs-issue-generation/docs_issue_generation.go#L677)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

You also need to update the test to reflect the function signature change. Otherwise LGTM.
`  panic: reflect.Set: value of type func(string, string, int, string) string is not assignable to type func(string, string, int, string) (string, error)`
</blockquote></details>

Done, I think! One more review?

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97789#-:-NQkrtWMBxk_Z0BNlwmS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nickvigilante)

**Pull request merged**
