### PR TITLE
exec,coldata: support timestamp type

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds support for the TIMESTAMP type to the coldata and exec
packages.

Also, add random projection tests for all types.

This test randomly runs binary comparisons against all types with random
data, verifying that the result of Datum.Compare matches the result of
the exec projection.

This found the bug with date infinity matching tracked in #40354, and
immediately found a bug with the timestamp implementation in the
previous commit, so I'm fairly sure it's a useful random test to have
around.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
That was very quick! One of the failed tests indicates that the serialization is missing.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-:-LnJ7RJt1GO_b_R4I8wI:bd4y0hp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnJ74ADDblfi9pkBpiQ:-LnJ74AEATB2p28n_bjG:b18uo0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46e8343b39993b535a7eb319c8d3397e8de7c53/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L24)):*
> ```Go
> 
> import (
> 	"bytes"
> ```

[super nit]: different indentation.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnJ77Tp4AyN5ojd4bvF:-LnJ77Tp4AyN5ojd4bvG:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46e8343b39993b535a7eb319c8d3397e8de7c53/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L24)):*
> ```Go
> 
> import (
> 	"bytes"
> ```

ditto
___
*[pkg/sql/exec/typeconv/typeconv.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnJ7DgG3ifkkPMWlMza:-LnJ7DgG3ifkkPMWlMzb:bfvavc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46e8343b39993b535a7eb319c8d3397e8de7c53/pkg/sql/exec/typeconv/typeconv.go#L175)):*
> ```Go
> 			d, ok := datum.(*tree.DTimestamp)
> 			if !ok {
> 				return nil, errors.Errorf("expected *tree.DDecimal, found %s", reflect.TypeOf(datum))
> ```

[nit]: `s/DDecimal/DTimestamp/`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/typeconv/typeconv.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnJ87PBADt5zWszoHNM:-LnJ87PBADt5zWszoHNN:b-k88ld9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46e8343b39993b535a7eb319c8d3397e8de7c53/pkg/sql/exec/typeconv/typeconv.go#L177)):*
> ```Go
> 				return nil, errors.Errorf("expected *tree.DDecimal, found %s", reflect.TypeOf(datum))
> 			}
> 			return d.Time, nil
> ```

(The blank comment from above):
[nit]: `s/DDecimal/DTimestamp/`.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/col/colserde/arrowbatchconverter_test.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnYD8F6ADnBpXE0dywe:-LnYD8F7CZv6iNLOVc9H:byo08o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b1f970dcfe6c60757a12868b4d7d788e6a0907/pkg/col/colserde/arrowbatchconverter_test.go#L33)):*
> ```Go
> 	availableTyps := make([]coltypes.T, 0, len(coltypes.AllTypes))
> 	for _, typ := range coltypes.AllTypes {
> 		// TODO(asubiotto): We do not support decimal conversion yet.
> ```

nit: update todo
___
*[pkg/col/colserde/record_batch_test.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnYDBuZBaY6pyxVpMTU:-LnYDBuZBaY6pyxVpMTV:b5k8fqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b1f970dcfe6c60757a12868b4d7d788e6a0907/pkg/col/colserde/record_batch_test.go#L197)):*
> ```Go
> 	)
> 
> 	// We do not support decimals yet.
> ```

nit: update comment
___
*[pkg/sql/exec/min_max_agg_tmpl.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnYE6R563B-P6UB08sa:-LnYE6R563B-P6UB08sb:beprybz) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b1f970dcfe6c60757a12868b4d7d788e6a0907/pkg/sql/exec/min_max_agg_tmpl.go#L48)):*
> ```Go
> 
> // Dummy import to pull in "time" package.
> var _ time.Time
> ```

i think it should be pretty easy to add the time type to aggregator_test.go for min/max and any-not-null.

**Review by yuzefovich — COMMENTED** [review]
Looks like Rafi beat me to it with the nits :)

> Reviewed 10 of 10 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-:-LnYHZBEAAmNJkO88vFb:b-2mf7bk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/vec_elem_to_datum.go, line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnYHyYD4F3blm5_46nv:-LnYHyYD4F3blm5_46nw:b8mjxea) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ce6b32814070ca87d87f6be262f148727ba4bdb/pkg/sql/exec/vec_elem_to_datum.go#L65)):*
> ```Go
> 		return da.NewDOid(tree.MakeDOid(tree.DInt(col.Int64()[rowIdx])))
> 	case types.TimestampFamily:
> 		return tree.MakeDTimestamp(col.Timestamp()[rowIdx], time.Microsecond)
> ```

The failed tests indicate that we might need to zero out fields of the timestamp that are smaller than a microsecond.

**Comment by jordanlewis** [comment]
The test failures are quite suspicious. I don't get it yet.

**Comment by jordanlewis** [comment]
Ah, you were right, RandDatum wasn't rounding to microsecond (we do that everywhere else).

**Review by asubiotto — COMMENTED** [review]
> Reviewed 10 of 10 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/col/colserde/arrowbatchconverter_test.go, line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-RNgv-Kp5oz-niJIr:-Lo-RNgv-Kp5oz-niJIs:bvleq58) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b019e3510aea87371bda8c83e5e17b8fab4eab/pkg/col/colserde/arrowbatchconverter_test.go#L120)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	typs := []coltypes.T{coltypes.Decimal, coltypes.Timestamp}
> ```

nit: don't think this is testing anything new, we should probably loop over the types and create a converter for each
___
*[pkg/sql/exec/mem_estimation.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnxKqPH8DkIFn11eZto:-LnxKqPH8DkIFn11eZtp:b51v8ss) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b1f970dcfe6c60757a12868b4d7d788e6a0907/pkg/sql/exec/mem_estimation.go#L65)):*
> ```Go
> 			acc += 50
> 		case coltypes.Timestamp:
> 			// time.Time has 2 int64s and a pointer.
> ```

nit: could we use `unsafe.SizeOf(time.Time{})` to be clearer?
___
*[pkg/sql/exec/projection_ops_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-UAZgE7e90sbnkF4c:-Lo-UAZgE7e90sbnkF4d:b-53mo69) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/projection_ops_test.go#L150)):*
> ```Go
> }
> 
> func TestRandomComparisons(t *testing.T) {
> ```

Cool test! Could you add a small comment about what it does?
___
*[pkg/sql/exec/projection_ops_test.go, line 157 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-Tscr63VdcU5-TFPq:-Lo-Tscr63VdcU5-TFPr:bty3vd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/projection_ops_test.go#L157)):*
> ```Go
> 	var da sqlbase.DatumAlloc
> 	lDatums := make([]tree.Datum, 2048)
> 	rDatums := make([]tree.Datum, 2048)
> ```

nit: extract `2048` into a const
___
*[pkg/sql/exec/vec_elem_to_datum.go, line 29 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-UjcsElIHIlLSJYDO:-Lo-UjcsElIHIlLSJYDP:b-u8b3i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/vec_elem_to_datum.go#L29)):*
> ```Go
> // PhysicalTypeColElemToDatum converts an element in a colvec to a datum of semtype ct.
> func PhysicalTypeColElemToDatum(
> 	col coldata.Vec, rowIdx uint16, da sqlbase.DatumAlloc, ct *types.T,
> ```

Why was the `ct` type changed to a pointer?
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 1076 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-S9N9EZQYXBS3ILrT:-Lo-S9N9EZQYXBS3ILrU:b-7bhh71) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b019e3510aea87371bda8c83e5e17b8fab4eab/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L1076)):*
> ```Go
> 	return func(op overload, target, v, _ string) string {
> 		return fmt.Sprintf(`
> 		  s, ns := %[2]s.Second(), %[2]s.Nanosecond()
> ```

What about using `UnixNano` instead?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40250)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/colserde/arrowbatchconverter_test.go, line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-RNgv-Kp5oz-niJIr:-Lrv0lAT8jqSXsN1zao2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b019e3510aea87371bda8c83e5e17b8fab4eab/pkg/col/colserde/arrowbatchconverter_test.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: don't think this is testing anything new, we should probably loop over the types and create a converter for each
</blockquote></details>

Done.
___
*[pkg/sql/exec/mem_estimation.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-LnxKqPH8DkIFn11eZto:-Lrv0qkr-UnqTdpIO5kv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b1f970dcfe6c60757a12868b4d7d788e6a0907/pkg/sql/exec/mem_estimation.go#L65)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: could we use `unsafe.SizeOf(time.Time{})` to be clearer?
</blockquote></details>

Done.
___
*[pkg/sql/exec/projection_ops_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-UAZgE7e90sbnkF4c:-Lrv1Aib4TtJd6bdgXV0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/projection_ops_test.go#L150)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Cool test! Could you add a small comment about what it does?
</blockquote></details>

Done.
___
*[pkg/sql/exec/projection_ops_test.go, line 157 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-Tscr63VdcU5-TFPq:-Lrv1A-3AXSPPZQIGyww:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/projection_ops_test.go#L157)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: extract `2048` into a const
</blockquote></details>

Done.
___
*[pkg/sql/exec/vec_elem_to_datum.go, line 29 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-UjcsElIHIlLSJYDO:-Lrv1GJjEtJCVVhIgH9T:bahufoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d64a30c04913895713a4c3cab9c0d43fd1f7f74/pkg/sql/exec/vec_elem_to_datum.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why was the `ct` type changed to a pointer?
</blockquote></details>

We're using `*types.T` everywhere.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 1076 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40250#-Lo-S9N9EZQYXBS3ILrT:-Lrv1Mji7_0oe7jLogRi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9b019e3510aea87371bda8c83e5e17b8fab4eab/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L1076)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What about using `UnixNano` instead?
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Superseded by #41662.

**Pull request closed without merging**
