### PR TITLE
sql: respect IntervalStyle for parsing

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Comment by otan** [comment]
thanks for the tip-off @mneverov

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cli/sql_util.go, line 446 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1KhP_AdZMClr-WmZQ:-Me1KhP_AdZMClr-WmZR:bbti5rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/cli/sql_util.go#L446)):*
> ```Go
> 
> 	// This should really be the same as the session's IntervalStyle
> 	// but that only affect for negative intervals in the magnitude
> ```

nit: should it say "the only effect for negative intervals is in the magnitude of days"?

had trouble reading this comment
___
*[pkg/sql/logictest/testdata/logic_test/interval, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1MNF1BVpcROAmbuYH:-Me1MNF1BVpcROAmbuYI:bnkb7q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0d51141179fd125ea23dea3ff62ee92e2e1c774/pkg/sql/logictest/testdata/logic_test/interval#L463)):*
> ```
> -10 years -22 months 1 day 01:02:03   -11 years -10 mons 1 day +01:02:03
> -10 years 22 months -1 day 01:02:03   -8 years -2 mons -1 days +01:02:03
> -10 years 22 months -1 day -01:02:03  -8 years -2 mons -1 days -01:02:03
> ```

i noticed in PG the `+` sign is very slightly different for the first two rows. i think it puts the `+` on the first non-negative one to make it more clear which ones are not negative?

```
 -10 years 22 months 1 day 01:02:03   | -8 years -2 mons +1 day 01:02:03
 -10 years -22 months 1 day 01:02:03  | -11 years -10 mons +1 day 01:02:03
 -10 years 22 months -1 day 01:02:03  | -8 years -2 mons -1 days +01:02:03
 -10 years 22 months -1 day -01:02:03 | -8 years -2 mons -1 days -01:02:03
```
___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me1NQo8-qSms9OKV6zz:brrcurs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
> ```Go
> 			}
> 
> 			for style := range duration.IntervalStyle_value {
> ```

did this test get moved?
___
*[pkg/sql/sem/tree/interval_test.go, line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NHUd2llm-t9iw3Pz:-Me1NHUd2llm-t9iw3Q-:brrcurs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L235)):*
> ```Go
> 		}
> 
> 		for style := range duration.IntervalStyle_value {
> ```

did this test get moved?
___
*[pkg/sql/sem/tree/pretty_test.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1KYZI9H-Vvxvq9r_-:-Me1KYZO8NKTXh0wjd4U:b-suka9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b1c68e3164d2585e6f6ab44d2387c8f42375cc/pkg/sql/sem/tree/pretty_test.go#L169)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 	tests := map[string]string{
> 		// Verify that INTERVAL is maintained.
> ```

nit: is this comment incorrect now?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/interval, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1MNF1BVpcROAmbuYH:-Me24Ynn79L4P0KOBIG-:b-ue8gwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0d51141179fd125ea23dea3ff62ee92e2e1c774/pkg/sql/logictest/testdata/logic_test/interval#L463)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i noticed in PG the `+` sign is very slightly different for the first two rows. i think it puts the `+` on the first non-negative one to make it more clear which ones are not negative?

```
 -10 years 22 months 1 day 01:02:03   | -8 years -2 mons +1 day 01:02:03
 -10 years -22 months 1 day 01:02:03  | -11 years -10 mons +1 day 01:02:03
 -10 years 22 months -1 day 01:02:03  | -8 years -2 mons -1 days +01:02:03
 -10 years 22 months -1 day -01:02:03 | -8 years -2 mons -1 days -01:02:03
```
</blockquote></details>

i've tacked on a commit to fix this bug.
___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me1seRgDLay6dPVDUIu:b-4p3s3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

did this test get moved?
</blockquote></details>

it just got indented, the test now works over all styles
___
*[pkg/sql/sem/tree/interval_test.go, line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NHUd2llm-t9iw3Pz:-Me1sbUB5LO6lkMOLqL5:b-4p3s3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L235)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

did this test get moved?
</blockquote></details>

it just got indented, the test now works over all styles

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me6PSc-ENVvWfjlSB8D:b-oucoz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it just got indented, the test now works over all styles
</blockquote></details>

i see.. i was just viewing the diff for the 3rd commit, and it shows that `for style := range duration.IntervalStyle_value` was removed from `TestValidSQLIntervalSyntax` and `TestInvalidSQLIntervalSyntax`. that's what i was asking about. (i do see that the range over all styles was added to other tests though.)

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me6ufyI2iv-USZAYUtF:b-u6tu78) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
> TestValidSQLIntervalSyntax

that one is still here

> TestInvalidSQLIntervalSyntax

ah I remember! it always errored (output is never set), so the logic after the `continue` never got hit. i removed it.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me7-tCe1MRyoNChVWR4:b-c69w3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> TestValidSQLIntervalSyntax

that one is still here

> TestInvalidSQLIntervalSyntax

ah I remember! it always errored (output is never set), so the logic after the `continue` never got hit. i removed it.
</blockquote></details>



it looks like `TestValidSQLIntervalSyntax` doesn't have it though :P -- look at lines 183 and 194 of the latest revision where it hardcodes `IntervalStyle_POSTGRES`.

But maybe the test should just be renamed if those test cases can't be parsed when using an intervalstyle other than Postgres?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/tree/interval_test.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-Me1NQo8-qSms9OKV6zy:-Me73jb63YWozEHn_5Kn:bhjhqg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcd345a937741ffb17a343187b846ba877395c3/pkg/sql/sem/tree/interval_test.go#L159)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>



it looks like `TestValidSQLIntervalSyntax` doesn't have it though :P -- look at lines 183 and 194 of the latest revision where it hardcodes `IntervalStyle_POSTGRES`.

But maybe the test should just be renamed if those test cases can't be parsed when using an intervalstyle other than Postgres?
</blockquote></details>

ah, yes.
woops, unremoved and also fixed a subtle bug that caught. nice catch, don't trust my tired self

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 3 of 4 files at r1, 18 of 24 files at r2, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67210#-:-MeT1Sqh4oxsb5VJ6lZ2:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by otan** [comment]
thanks!

bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
worst rebase conflict ever!

hopefully this will do

bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

**Comment by otan** [comment]
bors r=rafiss

flake on CI

**Pull request merged**
