### PR TITLE
kv: Remove the check on the descriptor range after truncation

### PR DESCRIPTION
**Pull request by kkaneda**
I might be totally misreading the code, but it seems this is needed since we no longer truncate the descriptor. No test hit this code path.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6419)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I don't think the old code had anything to do with truncation, but rather that a lookup of a (cached or uncached) descriptor could (can?) for some reason return one that does not contain that key. Mind doing a quick audit for that (documenting the result on the `getDescriptors` comment)? Maybe @nvanbenschoten remembers something as well - I know we discussed this when he improved the descriptor cache and last touched this code: https://reviewable.io/reviews/cockroachdb/cockroach/5911#-KEjqU7xRo9dEoeoL3Cu

I think it's be desirable to get rid of this check (i.e. have `getDescriptors` guarantee that it returns a descriptor that contains the "front" of the range lookup).

**Comment by nvanbenschoten** [comment]
Yeah I was always a little dubious about the necessity of this check, but I never looked close enough into why it was added to feel comfortable removing it. If it's the case that this was added to catch errors in descriptors that were returned from `RangeLookup`s, then that should now be getting caught by [this check](https://github.com/cockroachdb/cockroach/blob/master/kv/range_cache.go#L367) and subsequently retried before reaching the `includesFrontOfCurSpan` check. If the check is there to handle `rangeDescriptorCache` hits that are incorrect, then I would question why the `rangeDescriptorCache` is not 100% reliable. Either way, it would probably be most helpful to perform a little archaeological dig back in history and investigate why the check was added in the first place.

**Comment by kkaneda** [comment]
Thanks for taking a look, @tschottdorf , @nvanbenschoten !

The check was initially added by 45fa396f with the following comment:

```
// TODO(tschottdorf): hacky way to prevent the following: A range-
// spanning request hits a stale descriptor so that it misses parts
// of the keys it's supposed to scan after it's truncated to match
// the descriptor. Example revscan [a,g), first desc lookup for "g"
// returns descriptor [c,d) -> [d,g) is never scanned.
// This didn't happen prior to the refactor because the truncation
// was more ad-hoc.
```

The commit added `truncate()`, which I think is referred in the last sentence of the comment. On the other hand, `truncate()` is called after the check, so this might actually mean a lookup of a descriptor as discussed above. (The comment was later updated by b4febcdd.)

When 45fa396f was made, `rangeDescriptorCache.getCachedRangeDescriptorLocked` already checked that a given key actually belongs to the descriptor range.

```
	// Check that key actually belongs to the range.
	if !rd.ContainsKey(keys.KeyAddress(key)) {
		// The key is the EndKey and we're inclusive, so just return the range descriptor.
		if inclusive && key.Equal(rd.EndKey) {
			return metaEndKey, rd
		}
		return nil, nil
	}
```

For the non-cached case, I didn't find any specific check in `RangeLookup`. 

So, I'm suspecting that the `includesFrontOfCurSpan` was needed for the non-cached case, but it is no longer needed as we have [this check](https://github.com/cockroachdb/cockroach/blob/master/kv/range_cache.go#L367). It's not very conclusive investigation, though.. Does this make sense?

**Comment by kkaneda** [comment]
Btw, not directly related to this PR, but should the check in `LookupRangeDescriptor` consider that the exclusive end key is passed when `useReverseScan` is true?

```
--- a/kv/range_cache.go
+++ b/kv/range_cache.go
@@ -361,6 +361,9 @@ func (rdc *rangeDescriptorCache) LookupRangeDescriptor(
        // wrong RangeLookup (eg. from a double split), so if we did, return
        // a retryable lookupMismatchError with an unmodified eviction token.
        if res.desc != nil && !res.desc.ContainsKey(key) {
+               if useReverseScan && res.desc.EndKey.Equal(key) {
+                       return res.desc, res.evictToken, res.pErr
+               }
                return nil, evictToken, roachpb.NewError(lookupMismatchError{
                        desiredKey:     key,
                        mismatchedDesc: res.desc,
```

`getCachedRangeDescriptorLocked` has a similar check. If so, I'll create a separate PR.

**Comment by kkaneda** [comment]
Investigated a little bit more, and the check might actually still be needed. Will continue to look into, but will close the PR now..

**Comment by andreimatei** [comment]
Heya, is this party over?
I came across this `includesFrontOfCurSpan` code and I also wondered what the deal is / whether it's needed. I'm asking because I'm looking to copy/extract some of this code for a new place where we need to resolve key spans to ranges. I've also noticed that another place with similar code, `CountRanges`, doesn't do it.
https://github.com/cockroachdb/cockroach/blob/3869b40/kv/dist_sender.go#L344

Reading this thread, seems there was very little confidence that the check is required, until the last message where Kenji said that it might still be needed. Do you remember what was the reasoning there?
I'd love to replace the check with an error or a panic :)

<details><summary><i>Previously, kkaneda (Kenji Kaneda) wrote…</i></summary>
> Investigated a little bit more, and the check might actually still be needed. Will continue to look into, but will close the PR now..
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6419#-:-KI4Fx8DsLVxVJhcM1Ln:1469914628)*

**Comment by kkaneda** [comment]
Ah, I don't remember what I was thinking, but I remember my reasoning was wrong.. I couldn't come up with a concrete case where we hit this. `rangeDescriptorCache` has the same check, and I think we don't need to evict the cache from `DistSender` since the cache eviction will anyway happen when `ds.getDescriptors` is called again (and we call `clearOverlappingCachedRangeDescriptors`).

Panic looks good to me.. :)

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Heya, is this party over?
> I came across this `includesFrontOfCurSpan` code and I also wondered what the deal is / whether it's needed. I'm asking because I'm looking to copy/extract some of this code for a new place where we need to resolve key spans to ranges. I've also noticed that another place with similar code, `CountRanges`, doesn't do it.
> https://github.com/cockroachdb/cockroach/blob/3869b40/kv/dist_sender.go#L344
> 
> Reading this thread, seems there was very little confidence that the check is required, until the last message where Kenji said that it might still be needed. Do you remember what was the reasoning there?
> I'd love to replace the check with an error or a panic :)
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6419#-:-KI5g3Sc077b1f63EHjm:-892898366)*

**Comment by tamird** [comment]
@kkaneda can this branch be deleted?

**Comment by kkaneda** [comment]
sure, done!

**Pull request closed without merging**
