### PR TITLE
colexec: call StartInternal in Columnarizer

### LINKED ISSUE #58366: roachtest: nil ctx when draining
[(roachtest).sqlsmith/setup=seed-vec/setting=vec failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2550095&tab=buildLog) on [master@6d49a323b52966becfe8a2c38a1a8ccdf8ee58a1](https://github.com/cockroachdb/cockroach/commits/6d49a323b52966becfe8a2c38a1a8ccdf8ee58a1):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed-vec/setting=vec/run_1
	cluster.go:1637,context.go:140,cluster.go:1626,test_runner.go:841: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2550095-1609311871-12-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 7027
		4: 7801
		1: 10934
		2: dead
		Error: UNCLASSIFIED_PROBLEM: 2: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1850
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 2: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed-vec/setting=vec](https://teamcity.cockroachdb.com/viewLog.html?buildId=2550095&tab=artifacts#/sqlsmith/setup=seed-vec/setting=vec)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed-vec%2Fsetting%3Dvec.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #60994: roachtest: sqlsmith nil pointer in SpanFromContext
[(roachtest).sqlsmith/setup=seed-vec/setting=vec failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707822&tab=buildLog) on [master@5cfd7e5553a3072a1490d392390dddf968844215](https://github.com/cockroachdb/cockroach/commits/5cfd7e5553a3072a1490d392390dddf968844215):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed-vec/setting=vec/run_1
	cluster.go:1667,context.go:140,cluster.go:1656,test_runner.go:848: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2707822-1614064242-03-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 6010
		2: 5461
		4: dead
		1: 6192
		Error: UNCLASSIFIED_PROBLEM: 4: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1147
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:271
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:830
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1852
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 4: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed-vec/setting=vec](https://teamcity.cockroachdb.com/viewLog.html?buildId=2707822&tab=artifacts#/sqlsmith/setup=seed-vec/setting=vec)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed-vec%2Fsetting%3Dvec.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
Fixes #60994 
Fixes #58366

Release justification: fixes a possible crash.

Release note (bug fix): fixed an npe observed with a SpanFromContext call in
the stack trace.

### CODE REVIEW

**Comment by asubiotto** [comment]
Hmm, I think this fixes the issue but is incomplete. We probably need to call `InternalClose` in `Close`. Off to lunch but will update later. Anyway, worth taking a quick look to get the idea.

**Review by yuzefovich — COMMENTED** [review]
I was actually debugging a bit and was confused by our implementation of the columnarizer as a processor.

I agree that we should call `InternalClose` in `Close` instead of calling `input.ConsumerClosed` - this makes sense because if we've already called `DrainMeta`, then we will have drained everything and will call `InternalClose` too, and then the call in `Close` will be a noop.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-:-MUPDquXAeTQekLL_sdv:b-5mdr9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/columnarizer.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-MUPCo7RD-5_UStIlPj4:-MUPCo7RD-5_UStIlPj5:b-1hqtlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f35e52e18b171adad18b2c67ec0c011ebde467cb/pkg/sql/colexec/columnarizer.go#L135)):*
> ```Go
> 	if c.initStatus == colexecop.OperatorNotInitialized {
> 		c.accumulatedMeta = make([]execinfrapb.ProducerMetadata, 0, 1)
> 		c.ctx = c.StartInternal(c.ctx, "columnarizer")
> ```

nit: I think in all processors we call `Start` on input first and then call `StartInternal`.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/columnarizer.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-MUPCo7RD-5_UStIlPj4:-MUPdIkD6r1vkEh6KnDo:bnhdhpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f35e52e18b171adad18b2c67ec0c011ebde467cb/pkg/sql/colexec/columnarizer.go#L135)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think in all processors we call `Start` on input first and then call `StartInternal`.
</blockquote></details>

Hmm, looks like you're right, but is that correct? `StartInternal` creates a span, so the child "input" should execute within that context, right? I don't understand why it would be the other way round.

**Review by asubiotto — COMMENTED** [review]
Looks like the check is catching other instances of a nil ctx

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-:-MUPry7dEYu0VxcO28oX:bwgg0h0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Wow, a lot of failures :fearful: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-:-MUPuVIU838UmwrNEGqK:b-rk13j1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/columnarizer.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-MUPCo7RD-5_UStIlPj4:-MUPtwMYCq20A6E7uUO6:b8spbhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f35e52e18b171adad18b2c67ec0c011ebde467cb/pkg/sql/colexec/columnarizer.go#L135)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, looks like you're right, but is that correct? `StartInternal` creates a span, so the child "input" should execute within that context, right? I don't understand why it would be the other way round.
</blockquote></details>

Yeah, I dunno why it is the case currently. I agree with your reasoning.

How does anything ever work? lol

**Comment by asubiotto** [comment]
I think the new commit should fix some things (hopefully all). I'll keep the StartInternal calls ordered this way unless there's a strong reason not to since it makes more sense.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124#-:-MUUTlXT4vMse-QRVxYQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by asubiotto** [comment]
Modified the first commit to call InternalClose in TrailingMetaCallback. I think this is what is expected in ProcessorBase usage.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61124)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

**Comment by asubiotto** [comment]
Modified the first commit to not create a span for the columnarizer in `StartInternal` (the reason for the CI failures). Let's see if this next round of CI is green and will merge.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by yuzefovich** [comment]
I think we should backport this to 20.2.

**Pull request merged**
