### PR TITLE
colexec: improve single-group hash agg performance

### PR DESCRIPTION
**Pull request by jordanlewis**
I noticed that most of the time in the hash agg is currently spent doing
an N^2 search for equal items in the hash buffer, so I added a sort
phase to the hash buffer to avoid that.

This gives a 30% improvement to the single group case and 10% worse
performance for larger group case. Not sure if it's worth it.

```
name                                                                         old time/op    new time/op    delta
Aggregator/SUM/hash/int/groupSize=1/hasNulls=false/numInputBatches=64-24        126ms ± 3%      94ms ± 2%  -25.04%  (p=0.000 n=10+9)
Aggregator/SUM/hash/int/groupSize=1/hasNulls=true/numInputBatches=64-24         126ms ± 3%      94ms ± 4%  -25.32%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=false/numInputBatches=64-24       67.5ms ± 2%    56.2ms ± 4%  -16.77%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=true/numInputBatches=64-24        66.6ms ± 2%    54.4ms ± 3%  -18.40%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=false/numInputBatches=64-24     7.39ms ± 1%    8.34ms ± 1%  +12.88%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=true/numInputBatches=64-24      6.95ms ± 1%    7.84ms ± 0%  +12.74%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=false/numInputBatches=64-24    7.27ms ± 1%    7.91ms ± 1%   +8.79%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=true/numInputBatches=64-24     6.86ms ± 1%    7.44ms ± 1%   +8.38%  (p=0.000 n=10+10)

name                                                                         old speed      new speed      delta
Aggregator/SUM/hash/int/groupSize=1/hasNulls=false/numInputBatches=64-24     4.16MB/s ± 3%  5.53MB/s ± 3%  +32.90%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1/hasNulls=true/numInputBatches=64-24      4.17MB/s ± 3%  5.59MB/s ± 4%  +33.98%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=false/numInputBatches=64-24     7.77MB/s ± 2%  9.33MB/s ± 4%  +20.19%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=true/numInputBatches=64-24      7.87MB/s ± 2%  9.64MB/s ± 3%  +22.56%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=false/numInputBatches=64-24   71.0MB/s ± 1%  62.9MB/s ± 1%  -11.41%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=true/numInputBatches=64-24    75.4MB/s ± 1%  66.9MB/s ± 0%  -11.30%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=false/numInputBatches=64-24  72.1MB/s ± 1%  66.3MB/s ± 1%   -8.09%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=true/numInputBatches=64-24   76.4MB/s ± 1%  70.5MB/s ± 1%   -7.73%  (p=0.000 n=10+10)

name                                                                         old alloc/op   new alloc/op   delta
Aggregator/SUM/hash/int/groupSize=1/hasNulls=false/numInputBatches=64-24       31.3MB ± 0%    31.2MB ± 0%   -0.29%  (p=0.000 n=10+9)
Aggregator/SUM/hash/int/groupSize=1/hasNulls=true/numInputBatches=64-24        31.2MB ± 0%    31.1MB ± 0%   -0.32%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=false/numInputBatches=64-24       16.4MB ± 0%    16.3MB ± 0%   -0.06%  (p=0.004 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=true/numInputBatches=64-24        16.2MB ± 0%    16.2MB ± 0%   -0.04%  (p=0.001 n=10+8)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=false/numInputBatches=64-24      116kB ± 0%     120kB ± 0%   +3.53%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=true/numInputBatches=64-24       116kB ± 0%     120kB ± 0%   +3.54%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=false/numInputBatches=64-24    82.6kB ± 0%    86.7kB ± 0%   +4.96%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=true/numInputBatches=64-24     82.6kB ± 0%    86.7kB ± 0%   +4.96%  (p=0.000 n=10+10)

name                                                                         old allocs/op  new allocs/op  delta
Aggregator/SUM/hash/int/groupSize=1/hasNulls=false/numInputBatches=64-24         204k ± 0%      204k ± 0%   +0.05%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1/hasNulls=true/numInputBatches=64-24          191k ± 0%      191k ± 0%     ~     (p=0.052 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=false/numInputBatches=64-24         118k ± 0%      119k ± 0%   +0.14%  (p=0.004 n=10+10)
Aggregator/SUM/hash/int/groupSize=2/hasNulls=true/numInputBatches=64-24          115k ± 0%      115k ± 0%   +0.17%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=false/numInputBatches=64-24      1.17k ± 0%     1.30k ± 0%  +10.90%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=512/hasNulls=true/numInputBatches=64-24       1.17k ± 0%     1.30k ± 0%  +10.94%  (p=0.000 n=8+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=false/numInputBatches=64-24       910 ± 0%      1038 ± 0%  +14.07%  (p=0.000 n=10+10)
Aggregator/SUM/hash/int/groupSize=1024/hasNulls=true/numInputBatches=64-24        910 ± 0%      1038 ± 0%  +14.07%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50989#-MBVyYTK0s5deuLtoN7k:-MBVyYTK0s5deuLtoN7l:b-bl2qry) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d48e668d236cb14a2b5fc325a3a157b9de0d779/pkg/sql/colexec/hash_aggregator_tmpl.go#L89)):*
> ```Go
> 	// for context).
> 	op.scratch.hashCodeForSelsSlot = op.scratch.hashCodeForSelsSlot[:0]
> 	sort.Ints(hashBuffer)
> ```

I'm confused, I think this is incorrect, do the tests pass? Namely, the issue is that we have a 1-1 mapping from the tuples in the buffered batch and the hash codes in hash buffer, simply sorting the latter will mess up that mapping.

**Comment by jordanlewis** [comment]
haha, I didn't run the tests. was just playing around.

**Comment by yuzefovich** [comment]
I think it’s a good idea, just an incomplete implementation - we simply need to additionally switch the indices in the selection vector of the buffered batch when sorting hashBuffer, and it’ll probably work (if the selection is not yet set, we'll need to populate it with “identity” selection vector.

**Comment by yuzefovich** [comment]
I wrote up a commit that does the swapping of the selection vector of the batch in #51039, and the benchmarks are now expectedly not as clear-cut. I still think it's probably a beneficial change given the absolute speeds in big group sizes are still quite high. One interesting thing to look at is the speed comparison for the case when the selection vector is already present on the batch.

**Comment by jordanlewis** [comment]
I'm fairly sure this is closeable... it's ancient, and I'm definitely going to pick it up, and presumably the code has changed a ton since... any reason to keep these ideas around @yuzefovich?

**Review by yuzefovich — COMMENTED** [review]
No, this should be closed - this PR optimizes the old implementation of the hash aggregator that used a Goland map, and now we use the vectorized hash table.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50989#-:-MlXOTC56mUXa6hEI3B9:b-2jkex8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

**Comment by jordanlewis** [comment]
Woohoo! Love to delete old branches.

**Pull request closed without merging**
