### PR TITLE
multi-region: Unblock IMPORT into allowable multi-region tables

### PR DESCRIPTION
**Pull request by ajstorm**
Unblock IMPORTing into allowable multi-region tables.  We only support
importing into GLOBAL and REGIONAL BY TABLE tables as #61133 is blocking
IMPORT into any tables which have columns generated using a user defined
type (which covers REGIONAL BY ROW tables, as they have the crdb_region
column which is generated using the crdb_internal_region type).

This commit includes tests for both IMPORT and IMPORT INTO, as well as
cases which illustrate #61133 for non-multi-region tables.

Of note is the change to remove validation in create_table.go . This change was
required as the validation at this point is not possible from within
IMPORT, and it was uncovered through testing that this validation when
generating the LocalityConfig was not required anyway, as we validate
before writing the descriptors in all cases (i.e. after the
LocalityConfig is generated, but before the descriptors are written to
disk).

Release note: None

Release justification: Fixes bug in interaction between existing functionality and new multi-region feature.

### CODE REVIEW

**Comment by ajstorm** [comment]
Hold off on reviewing for now, diagnosing test failures....

**Review by otan — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @arulajmani)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUeMWfx0FuI50W2-x6c:-MUeMWfx0FuI50W2-x6d:bnr58k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/175725433dde778604a8eacc6049c1b31b3591b5/pkg/ccl/importccl/import_stmt_test.go#L34)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/ccl/backupccl"
> 	_ "github.com/cockroachdb/cockroach/pkg/ccl/kvccl"
> 	_ "github.com/cockroachdb/cockroach/pkg/ccl/multiregionccl"
> ```

hmm, correcting myself, i think `_ "github.com/cockroachdb/cockroach/pkg/ccl"` should do it.
___
*[pkg/sql/create_table.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUeMyXl5bmgclThZA8z:-MUeMyXl5bmgclThZA9-:b-4oul51) ([raw file](https://github.com/cockroachdb/cockroach/blob/175725433dde778604a8eacc6049c1b31b3591b5/pkg/sql/create_table.go#L369)):*
> ```Go
> 	dg := catalogkv.NewOneLevelUncachedDescGetter(params.p.txn, params.ExecCfg().Codec)
> 	if desc.LocalityConfig != nil {
> 		if err := desc.ValidateTableLocalityConfig(params.ctx, dg); err != nil {
> ```

are you sure we want to move this to `startExec`? this means other places which call `NewTableDesc` doesn't get validation

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @otan)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUeMWfx0FuI50W2-x6c:-MUhrrO20OzwRliazcw7:bkjdqit) ([raw file](https://github.com/cockroachdb/cockroach/blob/175725433dde778604a8eacc6049c1b31b3591b5/pkg/ccl/importccl/import_stmt_test.go#L34)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, correcting myself, i think `_ "github.com/cockroachdb/cockroach/pkg/ccl"` should do it.
</blockquote></details>

No dice.  Since we're in importccl, importing the the whole ccl directory causes a circular import.
___
*[pkg/sql/create_table.go, line 369 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUeMyXl5bmgclThZA8z:-MUhrGev-2jHYAitia3X:bvqqinc) ([raw file](https://github.com/cockroachdb/cockroach/blob/175725433dde778604a8eacc6049c1b31b3591b5/pkg/sql/create_table.go#L369)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

are you sure we want to move this to `startExec`? this means other places which call `NewTableDesc` doesn't get validation
</blockquote></details>

Have a look at the update commit record and let me know if this covers your concerns.

**Comment by ajstorm** [comment]
All tests are passing now.  @adityamaru, @arulajmani, ready for a look now (and another look from @otan).

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/backupccl/restore_job.go, line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUiEXdZDf9KQZH9sToE:-MUiEXdZDf9KQZH9sToF:blsnkp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6210fb760c798f84b87bffefc9c10f4fbf16109/pkg/ccl/backupccl/restore_job.go#L388)):*
> ```Go
> 				if table.GetLocalityConfig() != nil {
> 					return pgerror.Newf(pgcode.FeatureNotSupported,
> 						"cannot write descriptor for multi-region table %d into non-multi-region database %d",
> ```

Let's add the table & database names in addition to the table ID in this error message? It makes the message a lot easier to grok for users.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUiEXdZDf9KQZH9sToE:-MUiUpHA0Seqz9pWUIKU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6210fb760c798f84b87bffefc9c10f4fbf16109/pkg/ccl/backupccl/restore_job.go#L388)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Let's add the table & database names in addition to the table ID in this error message? It makes the message a lot easier to grok for users.
</blockquote></details>

Done.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUeMWfx0FuI50W2-x6c:-MUj0LV37fH0S44WG8Jr:b-vk3hba) ([raw file](https://github.com/cockroachdb/cockroach/blob/175725433dde778604a8eacc6049c1b31b3591b5/pkg/ccl/importccl/import_stmt_test.go#L34)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

No dice.  Since we're in importccl, importing the the whole ccl directory causes a circular import.
</blockquote></details>

ah it'd work if you renamed the test package to `importccl_test`, but no biggie

**Review by arulajmani — COMMENTED** [review]
Mostly looks good, just a couple minor suggestions and nits 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-:-MUkV9u2-7QkumHxoRye:b-anjr90)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkUFBMEI4RwYvGB2nM:-MUkUFBN2xcOkpWnC_ns:b9rxp8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/backupccl/restore_job.go#L380)):*
> ```Go
> 			}
> 			if dbDesc.GetRegionConfig() != nil {
> 				if table.GetLocalityConfig() == nil {
> ```

nit: unnecessary nesting, you could revert this diff
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkUnCI4-hfRScPXyuU:-MUkUnCI4-hfRScPXyuV:babx3mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L1219)):*
> ```Go
> 		verifyQuery string
> 		expected    [][]string
> 		err         bool
> ```

nit: non-empty error string <-> expect an error
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkT7TJ6aduNVeshISe:-MUkT7TJ6aduNVeshISf:b-1ufkzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6439)):*
> ```Go
> 
> 	const (
> 		nodes = 3
> ```

nit: unnecessary braces, you could just: `const nodes = 3`
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkS3l6-RIFWSaEYcB1:-MUkS3l6-RIFWSaEYcB2:b-j3ahku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6476)):*
> ```Go
> 	}
> 
> 	tc := testcluster.StartTestCluster(t, nodes, clusterArgs)
> ```

I'd recommend modifying `TestingCreateMultiRegionCluster` to accept a `baseDir` so that you don't have to do this whole setup thing here. 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6490 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkTQdUEWzQF3sbVwAj:-MUkTQdUEWzQF3sbVwAk:b-5o08kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6490)):*
> ```Go
> 
> 	// Table schemas for USING
> 	tableSchemaMR := fmt.Sprintf("nodelocal://0/%s", "simple-schema-multi-region.sql")
> ```

Is it worth adding one for GLOBAL tables here as well? 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6559 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkRaXw16mXNkqHEl21:-MUkRaXw16mXNkqHEl22:b-rc5wbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6559)):*
> ```Go
> 
> 			if test.err {
> 				if test.errString == "" {
> ```

nit: instead of having a err and an errString, you could make the empty string imply no error.

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajstorm)

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/backupccl/restore_job.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkUFBMEI4RwYvGB2nM:-MUncptv1xijS4pY1iPz:bdpyfg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/backupccl/restore_job.go#L380)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: unnecessary nesting, you could revert this diff
</blockquote></details>

The reason I wrote it this way was because I wanted to avoid an `else if` branch below, which we would need to confirm that the RegionConfig was nil.  I guess I could reorder it to avoid the nesting.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkUnCI4-hfRScPXyuU:-MUne8b62fYjARjRV9aD:b-txd76u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L1219)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: non-empty error string <-> expect an error
</blockquote></details>

good call.  Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkT7TJ6aduNVeshISe:-MUneMGH1T6fOcweHepG:b7tjttr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6439)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: unnecessary braces, you could just: `const nodes = 3`
</blockquote></details>

copy pasta.  Fixed.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkS3l6-RIFWSaEYcB1:-MUoNRCF2T8qqhxo-ntV:b-7xez1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6476)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'd recommend modifying `TestingCreateMultiRegionCluster` to accept a `baseDir` so that you don't have to do this whole setup thing here. 
</blockquote></details>

Good suggestion.  If only this had existed when I got start :-/. Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6490 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkTQdUEWzQF3sbVwAj:-MUoNc2L2OpQn1lGzKif:b9cqvef) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6490)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is it worth adding one for GLOBAL tables here as well? 
</blockquote></details>

We can if you feel passionate about it. Was reluctant as the RBR is the most different, and every table type requires a new schema file.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6559 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkRaXw16mXNkqHEl21:-MUoNkKA8Xo2fY-RKu3D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6559)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: instead of having a err and an errString, you could make the empty string imply no error.
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/backupccl/restore_job.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkUFBMEI4RwYvGB2nM:-MUpdaHP29Kx-UdHMh7O:buk2gjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/backupccl/restore_job.go#L380)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

The reason I wrote it this way was because I wanted to avoid an `else if` branch below, which we would need to confirm that the RegionConfig was nil.  I guess I could reorder it to avoid the nesting.
</blockquote></details>

Ah, I missed that part. Discard my nit 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6476 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUkS3l6-RIFWSaEYcB1:-MUpbyar6YZDQGadb1kB:b-zhzvv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1854947f4e643b622e4d65da535bc08f6a12528/pkg/ccl/importccl/import_stmt_test.go#L6476)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Good suggestion.  If only this had existed when I got start :-/. Done.
</blockquote></details>

Hehe you can blame me for that :P
___
*[pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUpcs_f3LbyjsxNa2HA:-MUpcs_f3LbyjsxNa2HB:bo524zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e80760da3da80acba309854255c3568e621b9bd/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go#L35)):*
> ```Go
> 	}
> 
> 	b := ""
> ```

nit: you could change baseDir to be a string instead of a string pointer and pass in an empty string in all the places where we pass `nil`.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUpcs_f3LbyjsxNa2HA:-MUpiyoJ8UiQIRM7_CWr:b8lzlb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e80760da3da80acba309854255c3568e621b9bd/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go#L35)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: you could change baseDir to be a string instead of a string pointer and pass in an empty string in all the places where we pass `nil`.
</blockquote></details>

Yeah, contemplated that, but it seemed more intuitive to me to have `nil` denote that something's not in use, as opposed to `""`.  If you feel strongly about it, I can make the change.

**Review by arulajmani — APPROVED** [review]
:shipit: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-:-MUpnVbdBGalMkmFXH1g:bizlbj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61192#-MUpcs_f3LbyjsxNa2HA:-MUpnJ1K3Jd_vzpow5UT:b4cejx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e80760da3da80acba309854255c3568e621b9bd/pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go#L35)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Yeah, contemplated that, but it seemed more intuitive to me to have `nil` denote that something's not in use, as opposed to `""`.  If you feel strongly about it, I can make the change.
</blockquote></details>

Naa no strong feelings, I'm fine merging as is

**Comment by ajstorm** [comment]
TFTRs @arulajmani @otan and @pbardea.

Will bors as soon as I can get a clean run through testrace, which is pretty reliably failing due to OOM.

**Comment by ajstorm** [comment]
bors r=otan,arulajmani,pbardea

**Pull request merged**
