### PR TITLE
sql: move makeTableDesc to planner, replace init usage with literals

### PR DESCRIPTION
**Pull request by dt**
This uses TableDescriptor literals for virtual tables, like the system tables.
This eliminates all usage of MakeTableDesc at init() times or where a planner
otherwise isn't available, except for the tests of the literals that replaced
those calls.

This allows makeTableDesc to move to planner, and thus handle FKs and Interleave
or other nodes in a CREATE TABLE statement AST that were previously unhandled
by makeTableDesc since doing so required a planner.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9327)

### CODE REVIEW

**Comment by paperstreet** [comment]
herocode

:lgtm_strong: 

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 978 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZjKCo1ZU_fO2AYhR-:-KRZjKCo1ZU_fO2AYhR0:b9wy9ad) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L978)):*
> ```Go
> }
> 
> func ensurePK(desc *sqlbase.TableDescriptor) error {
> ```

this seems a little funky. could this move to AllocateIDs?

---

*[sql/create.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiYhMtVMwYCcffhUz:-KRZiYhMtVMwYCcffhV-:bx4qq92) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L1092)):*
> ```Go
> // Will fail on complex tables where that operation requires e.g. looking up
> // other tables or otherwise utilizing a planner, since the planner used here is
> // just a nil placeholder.
> ```

nit: zero value placeholder

---

*[sql/information_schema_test.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiCMuzfRnlb6aVtOn:-KRZiCMuzfRnlb6aVtOo:b-jlzrv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema_test.go#L36)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			gen.Families = nil
> ```

comment on why

---

*[sql/sqlbase/structured.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiHVnI3LbEhRprnz0:-KRZiHVnI3LbEhRprnz1:bkgqvxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/sqlbase/structured.go#L720)):*
> ```Go
> 	}
> 
> 	// TODO(dt, nathan): virtual descs don't validate (missing privs, PK, etc).
> ```

this really needs to be fixed. make an issue, plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-:-KRZjkgHhjYMSsCnMWu7:b3sosm2)*

**Comment by nvanbenschoten** [comment]
Focused 

---

Reviewed 7 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZrC6c0aT5H1eLGtNg:-KRZrC6c0aT5H1eLGtNh:b-z2h1wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema.go#L102)):*
> ```Go
> );
> `,
> 	desc: sqlbase.TableDescriptor{Name: "columns", ID: 0xffffffff, Version: 0x1, Columns: []sqlbase.ColumnDescriptor{{Name: "TABLE_CATALOG", ID: 0x1, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "TABLE_SCHEMA", ID: 0x2, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "TABLE_NAME", ID: 0x3, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "COLUMN_NAME", ID: 0x4, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "ORDINAL_POSITION", ID: 0x5, Type: sqlbase.ColumnType{Kind: 1}, DefaultExpr: &zeroStr}, {Name: "COLUMN_DEFAULT", ID: 0x6, Type: sqlbase.ColumnType{Kind: 7}, Nullable: true, DefaultExpr: (*string)(nil)}, {Name: "IS_NULLABLE", ID: 0x7, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "DATA_TYPE", ID: 0x8, Type: sqlbase.ColumnType{Kind: 7}, DefaultExpr: &emptyStr}, {Name: "CHARACTER_MAXIMUM_LENGTH", ID: 0x9, Type: sqlbase.ColumnType{Kind: 1}, Nullable: true, DefaultExpr: (*string)(nil)}, {Name: "CHARACTER_OCTET_LENGTH", ID: 0xa, Type: sqlbase.ColumnType{Kind: 1}, Nullable: true, DefaultExpr: (*string)(nil)}, {Name: "NUMERIC_PRECISION", ID: 0xb, Type: sqlbase.ColumnType{Kind: 1}, Nullable: true, DefaultExpr: (*string)(nil)}, {Name: "NUMERIC_SCALE", ID: 0xc, Type: sqlbase.ColumnType{Kind: 1}, Nullable: true, DefaultExpr: (*string)(nil)}, {Name: "DATETIME_PRECISION", ID: 0xd, Type: sqlbase.ColumnType{Kind: 1}, Nullable: true, DefaultExpr: (*string)(nil)}}, NextColumnID: 0xe, PrimaryIndex: sqlbase.IndexDescriptor{Name: "", ID: 0x1, Unique: false, ColumnNames: []string(nil), ColumnDirections: []sqlbase.IndexDescriptor_Direction(nil), StoreColumnNames: []string(nil), ColumnIDs: []sqlbase.ColumnID(nil), ImplicitColumnIDs: []sqlbase.ColumnID(nil), Interleave: sqlbase.InterleaveDescriptor{Ancestors: []sqlbase.InterleaveDescriptor_Ancestor(nil)}, InterleavedBy: []sqlbase.ForeignKeyReference(nil)}, Indexes: []sqlbase.IndexDescriptor(nil), NextIndexID: 0x2, Privileges: emptyPrivileges, NextMutationID: 0x1, FormatVersion: 0x3},
> ```

I'm curious about the desired workflow for modifying these descriptors. Radu brought up integration with `go:generate` in https://github.com/cockroachdb/cockroach/pull/8141, which I agree would be nice, but I also agree that it might not be worth it. When changing the schema, should devs just be running `TestVirtualTableLiterals` and copying in the literal from the test failure? 

If so, I'm not sure I completely understand the benefit of this over init generation, given that these tables will never have the complex properties that will cause `CreateTestTableDescriptor` to fail (the previous change on the other hand was clearly needed to break the `sqlbase`->`sql` "dependency").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-:-KRZsBroOSljFQRu7EMj:b-wwdtua)*

**Comment by dt** [comment]
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 978 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZjKCo1ZU_fO2AYhR-:-KRZr5uZwWjItgCFwHyO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L978)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> this seems a little funky. could this move to AllocateIDs?
</details>
Done.

---

*[sql/create.go, line 1092 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiYhMtVMwYCcffhUz:-KRZr6GvtHXzfzQP11ft:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L1092)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: zero value placeholder
</details>
Done.

---

*[sql/information_schema.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZrC6c0aT5H1eLGtNg:-KRZtsaollsnnp9JyRMV:bopa5a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema.go#L102)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm curious about the desired workflow for modifying these descriptors. Radu brought up integration with `go:generate` in https://github.com/cockroachdb/cockroach/pull/8141, which I agree would be nice, but I also agree that it might not be worth it. When changing the schema, should devs just be running `TestVirtualTableLiterals` and copying in the literal from the test failure? 
> 
> If so, I'm not sure I completely understand the benefit of this over init generation, given that these tables will never have the complex properties that will cause `CreateTestTableDescriptor` to fail (the previous change on the other hand was clearly needed to break the `sqlbase`->`sql` "dependency").
</details>
w.r.t workflow: Yeah, I added the test and field to the struct (but none of the literals), and just let it fail, printing the desired output, then pasted that in and just had to fix the DefaultExprs by hand (since it prints out the pointers).

As far as motivation: My goal was to eliminate all the transformations of a SQL string to a TableDesc except for CREATE TABLE and unify/standardize TableDescriptor handling that as much as possible. I guess we could keep using a dummy planner approach until that breaks rather than switching to literals right away, though if we are going to do that, I'd rather we make these more like regular tables -- give them PKs, families, etc -- so that the regular tabledesc handling code will get along with them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327)*

**Comment by dt** [comment]
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/information_schema_test.go, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiCMuzfRnlb6aVtOn:-KR_8Xe1WPXi0Eyr3z-k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema_test.go#L36)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> comment on why
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 4 of 10 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 978 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZjKCo1ZU_fO2AYhR-:-KRbvGLeLExjOeBgjoHa:bnzpk8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L978)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Done.
</details>
What's the point of leaving the empty function?

---

*[sql/information_schema.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZrC6c0aT5H1eLGtNg:-KRbpxwId6b32LI5wdrr:b-fu4i0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema.go#L102)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> w.r.t workflow: Yeah, I added the test and field to the struct (but none of the literals), and just let it fail, printing the desired output, then pasted that in and just had to fix the DefaultExprs by hand (since it prints out the pointers).
> 
> As far as motivation: My goal was to eliminate all the transformations of a SQL string to a TableDesc except for CREATE TABLE and unify/standardize TableDescriptor handling that as much as possible. I guess we could keep using a dummy planner approach until that breaks rather than switching to literals right away, though if we are going to do that, I'd rather we make these more like regular tables -- give them PKs, families, etc -- so that the regular tabledesc handling code will get along with them.
</details>
It would be useful to leave some explanation similar to what we have for in `system.go:140` and `TestSystemTableLiterals` so whoever reads this in the future understands the workflow.

---

*[sql/information_schema_test.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRbqVv6e9IaU-1Y1ZGP:-KRbqVv6e9IaU-1Y1ZGQ:b-kitevl) ([raw file](https://github.com/cockroachdb/cockroach/blob/178d7ec4a3787885b6331e10907a7af825cc5263/sql/information_schema_test.go#L27)):*
> ```Go
> )
> 
> func TestVirtualTableLiterals(t *testing.T) {
> ```

explain what the test does since it's not trivial

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-:-KRbwMvzV7N8IYQLIDi_:bnfp4nl)*

**Comment by dt** [comment]
Review status: 3 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 978 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZjKCo1ZU_fO2AYhR-:-KRcjkMzDj068ssjfann:bsmg72q) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/create.go#L978)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What's the point of leaving the empty function?
</details>
lol, that was supposed to be deleted.
Done.

---

*[sql/information_schema.go, line 102 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZrC6c0aT5H1eLGtNg:-KRdC1m6EG4UPGwdbvXk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/information_schema.go#L102)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It would be useful to leave some explanation similar to what we have for in `system.go:140` and `TestSystemTableLiterals` so whoever reads this in the future understands the workflow.
</details>
Done.

---

*[sql/information_schema_test.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRbqVv6e9IaU-1Y1ZGP:-KRdC2Q7L0UZ4fnbkGOq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/178d7ec4a3787885b6331e10907a7af825cc5263/sql/information_schema_test.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> explain what the test does since it's not trivial
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327)*

**Comment by RaduBerinde** [comment]
Reviewed 5 of 10 files at r1, 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/sqlbase/structured.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327#-KRZiHVnI3LbEhRprnz0:-KRd_i6pzEQwySSOFQb1:b-udepfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/813c9acc90573db21ceceb13ca8f3e1c147a039b/sql/sqlbase/structured.go#L720)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> this really needs to be fixed. make an issue, plz
</details>
Done #9361

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9327)*

**Pull request merged**
