### PR TITLE
storage: Add a retry loop in replicate_queue removal

### PR DESCRIPTION
**Pull request by bdarnell**
During rebalancing, we reach this point quickly after committing an
upreplication. The combination of the chagned quorum size and the
newly-added node means its common for filterUnremovableReplicas to
find no eligible candidates, which returns an error and gives up until
the next scanner cycle. This leaves ranges in a vulnerable state for
too long.

Greatly reduces the impact of #12768. In one test the portion of data
at risk was reduced from an estimated 11% to less than 1% (maybe much
lower; it was below the effective resolution of the test)

Release note (bug fix): Reduced risk of data unavailability during
AZ/region failure.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Were you planning on adding a test for this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-:-LaqafiT8UWnSWLFVBwS:b6241nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/storage/replicate_queue.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-Laq_zYO2wPXpUOatENJ:-Laq_zYO2wPXpUOatENK:b-uw92vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/05658bf8676dfe1de24ed8f271ff05f8ef6e98c1/pkg/storage/replicate_queue.go#L390)):*
> ```
> timeutil.Now().Before(deadline)
> ```

What is this doing? Do you want `for ...; r.Next() && timeutil.Now().Before(deadline); {`

You could also use `retry.ForDuration` here.
___
*[pkg/storage/replicate_queue.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-LaqaqoGDBShLeor4rgD:-LaqaqoGDBShLeor4rgE:b-nji13m) ([raw file](https://github.com/cockroachdb/cockroach/blob/05658bf8676dfe1de24ed8f271ff05f8ef6e98c1/pkg/storage/replicate_queue.go#L396)):*
> ```Go
> 			}
> 			raftStatus := repl.RaftStatus()
> 			if raftStatus == nil {
> ```

Do we want this to be `raftStatus == nil || len(raftStatus.Progress) == 0 {`? I don't think `raftStatus` will actually be `nil` on a follower, just that it will have an empty progress. This is also in-line with what we do throughout the file.

**Review by bdarnell — COMMENTED** [review]
I can't think of a good way to test it. Maybe some assertions on the overreplicated metric in a roachtest?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-:-Laqf6uO8FqRDdbgVN5H:b9hayyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replicate_queue.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-Laq_zYO2wPXpUOatENJ:-LaqcDU595dKoagy-fY7:b-r7k8il) ([raw file](https://github.com/cockroachdb/cockroach/blob/05658bf8676dfe1de24ed8f271ff05f8ef6e98c1/pkg/storage/replicate_queue.go#L390)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> timeutil.Now().Before(deadline)
> ```

What is this doing? Do you want `for ...; r.Next() && timeutil.Now().Before(deadline); {`

You could also use `retry.ForDuration` here.
</blockquote></details>

D'oh! Yes, that's what I meant. Maybe that's why TestRepartitioning got so flaky. `retry.ForDuration` is deprecated. 
___
*[pkg/storage/replicate_queue.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-LaqaqoGDBShLeor4rgD:-LaqcceY13p3kMJH-3n7:b-n3wusi) ([raw file](https://github.com/cockroachdb/cockroach/blob/05658bf8676dfe1de24ed8f271ff05f8ef6e98c1/pkg/storage/replicate_queue.go#L396)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want this to be `raftStatus == nil || len(raftStatus.Progress) == 0 {`? I don't think `raftStatus` will actually be `nil` on a follower, just that it will have an empty progress. This is also in-line with what we do throughout the file.
</blockquote></details>

Yeah, this did nothing. It was an early attempt to fix the TestRepartitioning flakes; I guess it was just a fluke that it appeared to work. I've changed it to be `raftStatus == nil || raftStatus.State != raft.StateLeader` which makes more sense.

**Review by nvb — APPROVED** [review]
> Maybe some assertions on the overreplicated metric in a roachtest?

Yeah, I think a roachtest like what is proposed in https://github.com/cockroachdb/cockroach/pull/36098 would be useful even before atomic replication changes go in. We don't need to merge one with this though.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-:-LaqigcBArlQdn1f6C_V:blg56ff)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/replicate_queue.go, line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36117#-LaqaqoGDBShLeor4rgD:-LaqiS6n0ybxJb0i5Arn:b-6iqlsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/05658bf8676dfe1de24ed8f271ff05f8ef6e98c1/pkg/storage/replicate_queue.go#L396)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, this did nothing. It was an early attempt to fix the TestRepartitioning flakes; I guess it was just a fluke that it appeared to work. I've changed it to be `raftStatus == nil || raftStatus.State != raft.StateLeader` which makes more sense. 
</blockquote></details>

Either way is fine, although we already have `raftStatus == nil || len(raftStatus.Progress) == 0` in two other places in this file, so we might want to pull that into a helper func.

**Comment by bdarnell** [comment]
bors r=nvanbenschoten

**Comment by bdarnell** [comment]
bors r-

Too impatient for CI to tell me there's a misspelling.

**Comment by bdarnell** [comment]
bors r=nvanbenschoten

**Pull request merged**
