### PR TITLE
cli: make debug zip and node status more likely to work by default

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, the makeTenantSQLClient function did not pass the
-ccluster option if the caller requested the system tenant. But, if
the user has configured a default cluster that is not the system
tenant, than this meant we were actually connecting to the default
tenant.

Here, I always pass the ccluster option if a particular tenant was
specified. This allows `debug zip` to correctly collect data from the system
tenant without the user having to specify the `--url` option for the
system tenant manually.

Additionally, I've changed the `node ls` and `node status` command to
request the system tenant specifically since those commands currently
only work against the system tenant.

On versions CRDB 22.2 and before the ccluster option is ignored.

In 23.1 on stand-alone SQL servers, the option will produce an
error. We try to detect that error and retry the connection without
the option if we were attempting to contact the system tenant.  An
alternative to this fallback would be to modify how the debug zip
command works to detect when we are talking to standalone SQL server
and only request the "default" tenant, whatever that happens to be.

Note that we may want a follow-up task here to provide a
`--tenant-name` flag for CLI commands so that the user can more easily
use them against different tenants without having to specify a full
connection URL.

Epic: none

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I see that only 23.1 backport label is attached, I'm assuming 23.2 also needs it, right?

Seems reasonable to me, but this is the first time I'm looking at this code, so a second pair of eyes would be definitely helpful. Can we also add a unit test that verifies that the retried connection attempt succeeds?

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-:-Ngt_1MlDMxT_0-RkJRl:btdklsw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler and @stevendanna)

___
*[`pkg/cli/sql_client.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-Ngtany7BryitpOqTNuK:-Ngtany7BryitpOqTNuL:bub2dna) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f21cf360a3202815786721840d789636ca8984/pkg/cli/sql_client.go#L63)):*
> ```Go
> // If a password is needed, it also prompts for the password.
> //
> // If forceSystemDB is set, it also connects it to the `system`
> ```

nit: this comment was already stale, would be good to update.
___
*[`pkg/cli/sql_client.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgtbGsJ-ZigOYF3EsZ2:-NgtbGsJ-ZigOYF3EsZ3:befkwzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f21cf360a3202815786721840d789636ca8984/pkg/cli/sql_client.go#L67)):*
> ```Go
> // ignored.
> //
> // The appName given as argument is added to the URL even if --url is
> ```

nit: perhaps also mention `ccluster` option with non-empty `tenantName`.
___
*[`pkg/cli/sql_client.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgtcRCBA0-jIZDb8ZCu:-NgtcRCBA0-jIZDb8ZCv:b-o3whwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/10f21cf360a3202815786721840d789636ca8984/pkg/cli/sql_client.go#L95)):*
> ```Go
> 
> 	if cclusterOptionRequired {
> 		// If we've specified the ccluster option, we we don't know if
> ```

nit: "we we".

**Review by stevendanna — COMMENTED** [review]
The zip tests _technically_ were exercising the code, but you are right that an explicit unit test would be good. I've added one but it required a little code reorganization.

But, the good news is that it caught a latent bug that existed in the original code as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-:-NgxjwmrAg677BKpoQyM:b-r9p4pf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm: I'll leave it up to you to wait for a second review or not.

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-:-NgycCIKASxCyJWlxTxk:bz4lwti)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msbutler and @stevendanna)

___
*[`pkg/cli/sql_client.go` line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgybFPC6CzRV-G7i9wA:-NgybFPC6CzRV-G7i9wB:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/df42ddf279234abc841432f3ef55c6298287b737/pkg/cli/sql_client.go#L60)):*
> ```Go
> 
> // makeTenantSQLClient runs makeTenantSQLClient using the default cliContext
> // that has the connection settings set by the command-line flags
> ```

nit: missing period.
___
*[`pkg/cli/sql_client.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgybPqD5BELPmtFG4o3:-NgybPqD5BELPmtFG4o4:b-ajxfid) ([raw file](https://github.com/cockroachdb/cockroach/blob/df42ddf279234abc841432f3ef55c6298287b737/pkg/cli/sql_client.go#L91)):*
> ```Go
> 	if cclusterOptionRequired {
> 		// makeClientConnURL returns a memoized URL. If we've been asked
> 		// to connecto to a particular tenant, clone the URL so that we
> ```

nit: `s/connecto/connect/`.
___
*[`pkg/cli/sql_client.go` line 158 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgybXLR-vaGVa4rfpyH:-NgybXLR-vaGVa4rfpyI:bj0w2cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/df42ddf279234abc841432f3ef55c6298287b737/pkg/cli/sql_client.go#L158)):*
> ```Go
> 	sqlURL := baseURL.ToPQ().String()
> 
> 	// if log.V(2) {
> ```

nit: uncomment?
___
*[`pkg/server/pgurl/pgurl.go` line 313 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgyaT0wEWnGBzk5XO-o:-NgyaT0wEWnGBzk5XO-p:baywwbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/02fd0385325d79319f758be5c77c1d46abed60d5/pkg/server/pgurl/pgurl.go#L313)):*
> ```Go
> 	}
> 
> 	u2 := new(URL)
> ```

nit: are these two lines not effectively equivalent to `u2 := *u`?
___
*[`pkg/server/pgurl/pgurl.go` line 315 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112228#-NgyarJ85TNy8duQq_BJ:-NgyarJ85TNy8duQq_BK:b-mvgnro) ([raw file](https://github.com/cockroachdb/cockroach/blob/02fd0385325d79319f758be5c77c1d46abed60d5/pkg/server/pgurl/pgurl.go#L315)):*
> ```Go
> 	u2 := new(URL)
> 	*u2 = *u
> 	u2.extraOptions = make(url.Values)
> ```

nit: we could allocate the len precisely.

**Comment by stevendanna** [comment]
bors r=yuzefovich

**Pull request merged**
