### PR TITLE
distsqlrun: use batch row channel in input syncs

### LINKED ISSUE #25207: distsqlrun: implement batched channel RowReceiver for network receives
Change the RowReceiver implementation between the StreamDecoder and the first Processor in a flow to send batches across the Go channel.

Preliminary work on this shows a significant improvement:

```
BenchmarkRowChannelPipeline/length=1-8          20000000               109 ns/op          73.33 MB/s

BenchmarkBatchRowChannel/length=1-8              3000000               500 ns/op         255.66 MB/s
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the DistSQL input synchronizers used RowChannels to
send incoming messages to the first processor in every flow. Each
incoming message was sent by itself through the row channel. As we know,
sending a message through a Go channel is relatively slow - it's better
to send fewer, large messages through a channel than many, small ones.
Furthermore, incoming messages in DistSQL are already bundled into
batches by the DistSQL network layer, which sends a chunk of rows over
the network at once instead of row by row. The receiver used to get that
batch, just to decompose it into individual rows to send over the row
channel.

This commit introduces a new interface, BatchRowReceiver, along with a
matching BatchRowChannel implementation. It behaves as an ordinary
RowSource, returning a single row at once, but it permits batch Push
access with a new method PushBatch. This is much more efficient.

This change doesn't appear to change overall query performance, but
the microbenchmarks show a large change.

```
BenchmarkRowChannelPipeline/length=1-8          10000000               125 ns/op          63.53 MB/s
BenchmarkBatchRowChannel-8                       3000000               515 ns/op         248.23 MB/s
```

Closes #25207.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
That's an impressive speedup!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsqlrun/flow.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-LDNcQxZ0s_nYCjvp7Mu:-LDNcQxZ0s_nYCjvp7Mv:b-gwuid0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35ce21eb72206a88a2610555db99b17b5f3bebc/pkg/sql/distsqlrun/flow.go#L342)):*
> ```Go
> 			case InputSyncSpec_UNORDERED:
> 				if len(is.Streams) == 1 {
> 					rowChan := &BatchRowChannel{}
> ```

Don't you want to only do this when the input side of the row channel is an inbound stream? 

---

*[pkg/sql/distsqlrun/inbound.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-LDNdFsTE1ZKIxyvh8Rx:-LDNdFsTE1ZKIxyvh8Ry:b-3umhr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35ce21eb72206a88a2610555db99b17b5f3bebc/pkg/sql/distsqlrun/inbound.go#L205)):*
> ```Go
> 
> 			msgs = append(msgs, RowChannelMsg{Row: row, Meta: meta})
> 		}
> ```

There is a lot of duplication between this code and the code below. I wonder if you could put the `msgs` buf inside of `BatchRowChannel`. I'm imagining that `BatchRowChannel.Push` would add to the internal batch and `BatchRowChannel.PushBatch` would push the batch onto the channel. To make this work, you'd need to add a flag to `BatchRowChannel` that a caller can set to indicate that it is opting into to "batched" behavior. The benefit of this approach is I think you could get rid of the above, and add a few lines below when to the code path where there are no more rows and you have to call `PushBatch` if the receiver is a `BatchRowReceiver`. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-:-LDNe1df06cODMmvQd9B:b93a863)*

**Comment by RaduBerinde** [comment]
How does this fit in with the investigation @arjunravinarayan and @asubiotto did on row batching?

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-:-LDgNWDE7DVJcjvJ_K2V:bvxupyb)*

**Comment by asubiotto** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/base.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-LDhbb3E2Bj6z74MdhmV:-LDhbb3E2Bj6z74MdhmW:bi7n2mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35ce21eb72206a88a2610555db99b17b5f3bebc/pkg/sql/distsqlrun/base.go#L543)):*
> ```Go
> 
> // BatchRowChannel is a way of passing a batch of messages between goroutines.
> type BatchRowChannel struct {
> ```

I wonder what you think of instead extending the `RowChannel` with `PushBatch` (adding a `Batch` field to `RowChannelMsg`). I think this would avoid duplicate code. I think I went this approach when batching over a `RowChannel` (in case you're interested: https://github.com/cockroachdb/cockroach/pull/20621/commits/d90a2ff06a2ead8e6a9db2b6d04d6f49649ca4dd)

---

*[pkg/sql/distsqlrun/flow.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-LDNcQxZ0s_nYCjvp7Mu:-LDhaShwAWV2J5ShFrN0:b37q29k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35ce21eb72206a88a2610555db99b17b5f3bebc/pkg/sql/distsqlrun/flow.go#L342)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Don't you want to only do this when the input side of the row channel is an inbound stream? 
</blockquote></details>

+1, maybe make this BatchRowChannel in the `REMOTE` case in setupInboundStream?

---

*[pkg/sql/distsqlrun/flow.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26099#-LDhZcYd9oU2ZWBlzXvA:-LDhZcYd9oU2ZWBlzXvB:b-nz6noo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e35ce21eb72206a88a2610555db99b17b5f3bebc/pkg/sql/distsqlrun/flow.go#L352)):*
> ```Go
> 					mrc.Init(len(is.Streams), is.ColumnTypes)
> 					for _, s := range is.Streams {
> 						if err := f.setupInboundStream(ctx, s, mrc); err != nil {
> ```

I think this is a case where we would definitely benefit from batching over a RowChannel as well, otherwise you limit yourself to only supporting cases where there is a single input. This might be the reason you're not seeing that much improvement with the query library?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26099)*

**Comment by jordanlewis** [comment]
This ends up being a pessimization on real workloads because of the extra allocations that the BatchRowChannel (or its caller) needs to make to create the slices of EncDatumRows.

We wouldn't have to make any extra slices if the stream decoder just passed its entire buffer over the channel, leaving it up to the object downstream of the channel to do the decoding.

But that's more major surgery, so I'll close this for now.

**Pull request closed without merging**
