### PR TITLE
fix all errors in `go vet ./...`, update for errcheck

### PR DESCRIPTION
**Pull request by tbg**

### CODE REVIEW

**Comment by spencerkimball** [comment]
Why do all of the main test files need to be moved to _test packages?

**Comment by tschottdorf** [comment]
`errcheck` tripped over the one in `securitytest/main_test` and the rest for uniformity.

**Comment by spencerkimball** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM. Nice trick for the errcheck failure; I ran into that the other day and couldn't figure out how to make errcheck parse things correctly.

**Pull request merged**
