### PR TITLE
kv,sql: integrate row-level TTL reads with CPU limiter

### PR DESCRIPTION
**Pull request by irfansharif**
Part of #98722.

We do it at two levels, each appearing prominently in CPU profiles:
- Down in KV, where we're handling batch requests issued as part of row-level TTL selects. This is gated by kvadmission.low_pri_read_elastic_control.enabled.
- Up in SQL, when handling KV responses to said batch requests. This is gated by sqladmission.low_pri_read_response_elastic_control.enabled.

Similar to backups, rangefeed initial scans, and changefeed event processing, we've observed latency impact during CPU-intensive scans issued as part of row-level TTL jobs. We know from before that the existing slots based mechanism for CPU work can result in excessive scheduling latency for high-pri work in the presence of lower-pri work, affecting end-user latencies. This commit then tries to control the total CPU% used by row-level TTL selects through the elastic CPU limiter. For the KV work, this was trivial -- we already have integrations at the batch request level and now we pick out requests with the admissionpb.TTLLowPri bit set.

For the SQL portion of the work we introduce some minimal plumbing. Where previously we sought admission in the SQL-KV response queues after fetching each batch of KVs from KV as part of our volcano operator iteration, we now incrementally acquire CPU nanos. We do this specifically for row-level TTL work. Experimentally the CPU nanos we acquire here map roughly to the CPU utilization due to SQL work for row-level TTL selects.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'll defer to others for approval.

> Reviewed 7 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-:-Nbvs2N11kxpEnxuqvUb:b-4vsyy0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @irfansharif, @rachitgsrivastava, @rafiss, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbvkEnq1XN7GCIb7s2X:-NbvkEnq1XN7GCIb7s2Y:b-o204w) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L68)):*
> ```Go
> 	"controls how many CPU tokens are allotted for each ttl read request",
> 	10*time.Millisecond,
> 	func(duration time.Duration) error {
> ```

nit: consider extracting this validation function as a helper (or as a helper constructor), probably in `admission` package, to be used in three places.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
looks good

> Reviewed 7 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-:-NbzsyKtBGmMXGleW8Bn:b-47fafm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @irfansharif, @rachitgsrivastava, and @rafiss)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyLtYX0qBDyTra-sNH):*
fwiw, one could argue that this should be elastic work even if the slot based mechanism was working better, because an improved cpu admission mechanism for regular work will not try to keep scheduling latency as low as we do for elastic work.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyO65rBDr9OiqdL_u5:-NbyO65rBDr9OiqdL_u6:brhgbsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L397)):*
> ```Go
> 		// - We do the same for KV work done on the behalf of row-level TTL
> 		//   reads.
> 		isTTLRead := ba.IsReadOnly() && admissionInfo.Priority == admissionpb.TTLLowPri
> ```

I'm planning to fiddle with priorities, based on whether locks are held or not, and maybe more such changes in the future. So using the priority to decide whether something is a TTL scan is a bit brittle. One could argue that anything < UserLowPri is elastic work and ought to go through this path. Thoughts on the latter?
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzmoZC3_Me7BiIrX1v:-NbzmoZC3_Me7BiIrX1w:b-dga6q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L412)):*
> ```Go
> 			elasticWorkHandle, err := n.elasticCPUGrantCoordinator.ElasticCPUWorkQueue.Admit(
> 				ctx, admitDuration, admissionInfo,
> 			)
> ```

we're doing the initial admission, but the corresponding request processing code is not doing `admission.ElasticCPUWorkHandleFromContext(ctx)` in order to return if it consumes too much time. I suppose it isn't harming us because these requests are short lived, but I think this needs a code comment and a TODO.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-Nbzouki2UoeYPVJziLR:-Nbzouki2UoeYPVJziLS:bmgpfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/sql/row/kv_batch_fetcher.go#L376)):*
> ```Go
> 				CreateTime: txn.AdmissionHeader().CreateTime,
> 			})
> 	}
> ```

this code is duplicated. Can you pull it into a method, and call it TryInitAdmissionPacing (or something like that). And include a comment that for now we are only doing this for TTL.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzpZS35NyH2zcW3fig:-NbzpZS35NyH2zcW3fih:b-pa6q0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/sql/row/kv_batch_fetcher.go#L621)):*
> ```Go
> 	// Do admission control after we've accounted for the response bytes.
> 
> 	if br != nil {
> ```

This admission block is worth pulling out into a method too, and having a comment in that method implementation on why we are doing one or the other.

Also we need a code comment justifying why this pacing is effective for TTL work. Please work in some of the comments from the slack thread and maybe post the profiles onto the github issue so that the callstacks can be referenced here. I am assuming this is working because the bulk of the SQL CPU consumption for TTL work is happening on the goroutine that is driving this fetch.

And how will this be robust to future changes in the SQL code? This problem is not unique to this TTL instrumentation, so hopefully @yuzefovich can comment on how someone (perhaps sql-queries) could add unit tests. Also, I'm not suggesting it happen in this PR, but I worry about brittleness since:
- The admission roachtests typically don't have pass/fail conclusions, so we may not notice if TTL isolation breaks because the instrumentation point is no longer relevant.
- We have similar response path instrumentation in streamer.go. For some reason the TTL code is using `txnKVFetcher` and not that code, but presumably that could change.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @irfansharif, @rachitgsrivastava, @rafiss, and @sumeerbhola)

___
*[`pkg/sql/row/kv_batch_fetcher.go` line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzpZS35NyH2zcW3fig:-Nc-0brGERSViSRLyPcN:btyh1e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/sql/row/kv_batch_fetcher.go#L621)):*
> I am assuming this is working because the bulk of the SQL CPU consumption for TTL work is happening on the goroutine that is driving this fetch.

Yes, I believe that's the case because the SELECTs done by the TTL job are not distributed at SQL level (since our DistSQL physical planning heuristics deems it not worthy of distribution), and with the local plan we only have a single goroutine (unless `maybeParallelizeLocalScans` splits up the single scan into multiple TableReader processors).

> And how will this be robust to future changes in the SQL code? This problem is not unique to this TTL instrumentation, so hopefully @yuzefovich can comment on how someone (perhaps sql-queries) could add unit tests.

If you're wondering how we'd verify that TTL code still benefits from this elastic CPU pacing, I'd consider adding tests for the SELECT queries issued by the TTL to ensure that they have local plans with a single TableReader processor in multi-node clusters. The assumption that such plans have a single goroutine is pretty fundamental and won't be changed (until the TableReaders are powered by the streamer #82164).

> We have similar response path instrumentation in streamer.go. For some reason the TTL code is using `txnKVFetcher` and not that code, but presumably that could change.

Yes, that's a good point. This will change once #82164 is implemented, but that's not going to happen in 23.2. The streamer does have many goroutines involved, and the CPU intensive SQL work will happen on a different goroutine from the ones that evaluate the BatchRequests, so the integration will be much tricker there. However, we'll always have an option to disable the usage of the streamer in the TTL SELECT queries to preserve this elastic pacing.

**Review by irfansharif — COMMENTED** [review]
PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-:-NcOIOR4ByMxOGGpv9bq:b-83330m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @rafiss, @sumeerbhola, and @yuzefovich)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyLtYX0qBDyTra-sNH):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

fwiw, one could argue that this should be elastic work even if the slot based mechanism was working better, because an improved cpu admission mechanism for regular work will not try to keep scheduling latency as low as we do for elastic work.
</blockquote></details>

Edited the sentence earlier to reflect this.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbvkEnq1XN7GCIb7s2X:-NcNvIW26osJyAX5-SD6:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L68)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: consider extracting this validation function as a helper (or as a helper constructor), probably in `admission` package, to be used in three places.
</blockquote></details>

Good idea, done.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyO65rBDr9OiqdL_u5:-NcO5b1D8EuSRL32LanZ:b-6972mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L397)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm planning to fiddle with priorities, based on whether locks are held or not, and maybe more such changes in the future. So using the priority to decide whether something is a TTL scan is a bit brittle. One could argue that anything < UserLowPri is elastic work and ought to go through this path. Thoughts on the latter?
</blockquote></details>

Just saw the other PR. I was initially trying to be very targeted here, trying to affect only TTL reads, but applying it to < UserLowPri makes sense. Done.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzmoZC3_Me7BiIrX1v:-NcNvhhn0hIk-2U0hdH8:bdx11i) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L412)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we're doing the initial admission, but the corresponding request processing code is not doing `admission.ElasticCPUWorkHandleFromContext(ctx)` in order to return if it consumes too much time. I suppose it isn't harming us because these requests are short lived, but I think this needs a code comment and a TODO.
</blockquote></details>

We _are_ using `admission.ElasticCPUWorkHandleFromContext(ctx)` in order to return unused tokens. See below where we populate `ah.elasticCPUWorkHandle` and the calling code in `pkg/server/node.go`. The unused CPU nanos gets returned when calling `AdmittedKVWorkDone`.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 376 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-Nbzouki2UoeYPVJziLR:-NcNxczF26xP08TLdykD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/sql/row/kv_batch_fetcher.go#L376)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this code is duplicated. Can you pull it into a method, and call it TryInitAdmissionPacing (or something like that). And include a comment that for now we are only doing this for TTL.
</blockquote></details>

Done.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzpZS35NyH2zcW3fig:-NcOGazx2vysd-y8rCoW:bbm7l42) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/sql/row/kv_batch_fetcher.go#L621)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> I am assuming this is working because the bulk of the SQL CPU consumption for TTL work is happening on the goroutine that is driving this fetch.

Yes, I believe that's the case because the SELECTs done by the TTL job are not distributed at SQL level (since our DistSQL physical planning heuristics deems it not worthy of distribution), and with the local plan we only have a single goroutine (unless `maybeParallelizeLocalScans` splits up the single scan into multiple TableReader processors).

> And how will this be robust to future changes in the SQL code? This problem is not unique to this TTL instrumentation, so hopefully @yuzefovich can comment on how someone (perhaps sql-queries) could add unit tests.

If you're wondering how we'd verify that TTL code still benefits from this elastic CPU pacing, I'd consider adding tests for the SELECT queries issued by the TTL to ensure that they have local plans with a single TableReader processor in multi-node clusters. The assumption that such plans have a single goroutine is pretty fundamental and won't be changed (until the TableReaders are powered by the streamer #82164).

> We have similar response path instrumentation in streamer.go. For some reason the TTL code is using `txnKVFetcher` and not that code, but presumably that could change.

Yes, that's a good point. This will change once #82164 is implemented, but that's not going to happen in 23.2. The streamer does have many goroutines involved, and the CPU intensive SQL work will happen on a different goroutine from the ones that evaluate the BatchRequests, so the integration will be much tricker there. However, we'll always have an option to disable the usage of the streamer in the TTL SELECT queries to preserve this elastic pacing.
</blockquote></details>

Added a comment, TODOs, and a back reference in #82164 to this thread. Posting some internal experimental results over to #98722 for reference-ability.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @irfansharif, @rachitgsrivastava, @rafiss, and @sumeerbhola)

___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcPX-Zk3k2dD2lyU8Qx:-NcPX-Zk3k2dD2lyU8Qy:b-x2s95v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3738904d94c6307ff14ff537315d1b836a141bf/pkg/util/admission/elastic_cpu_work_queue.go#L34)):*
> ```Go
> // ValidateElasticCPUDuration is a validation function for the {minimum,maximum}
> // on-CPU time elastic requests can ask for when seeking admission.
> func ValidateElasticCPUDuration(duration time.Duration) error {
> ```

nit: I think this is no longer needed (and unused) given Raphael's changes to settings API.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @rafiss, @sumeerbhola, and @yuzefovich)

___
*[`pkg/util/admission/elastic_cpu_work_queue.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcPX-Zk3k2dD2lyU8Qx:-NcPZoeqDOTA95Py63OX:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3738904d94c6307ff14ff537315d1b836a141bf/pkg/util/admission/elastic_cpu_work_queue.go#L34)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think this is no longer needed (and unused) given Raphael's changes to settings API.
</blockquote></details>

Removed.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-:-NcSTi2MCZU5BxKgLpNJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @irfansharif, @rachitgsrivastava, @rafiss, and @yuzefovich)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyLtYX0qBDyTra-sNH):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Edited the sentence earlier to reflect this.
</blockquote></details>

Did you mean to collapse into 1 commit? The second commit description has been lost.
___
*[`pkg/cmd/roachtest/tests/admission_control_row_level_ttl.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcST6_38lyhF6KknONh:-NcST6_38lyhF6KknONi:bx3aiul) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/cmd/roachtest/tests/admission_control_row_level_ttl.go#L97)):*
> ```Go
> 						// The TPCC fixtures have dates from 2006 for the ol_delivery_d column.
> 						expirationExpr = `'((ol_delivery_d::TIMESTAMP) + INTERVAL ''1000 years'') AT TIME ZONE ''UTC'''`
> 					}
> ```

Can you add a TODO for what metric(s) we should read and aggregate to check that AC is working as expected. 
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzmoZC3_Me7BiIrX1v:-NcSPpLy7zncAiUGN1Al:byim3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L412)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We _are_ using `admission.ElasticCPUWorkHandleFromContext(ctx)` in order to return unused tokens. See below where we populate `ah.elasticCPUWorkHandle` and the calling code in `pkg/server/node.go`. The unused CPU nanos gets returned when calling `AdmittedKVWorkDone`.
</blockquote></details>

Yes, I realize that. I was referring to the fact that there is nothing in the processing code (like we have in mvcc.go for ExportRequest), that returns if 10ms has been exceeded. So in some sense the integration is incomplete, even though it is probably harmless.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSP0mQCpMUk0ksE2Yp:-NcSP0mQCpMUk0ksE2Yq:b-whm84f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/kv/kvserver/kvadmission/kvadmission.go#L365)):*
> ```Go
> 		//   isolation to non-elastic ("latency sensitive") work running on the
> 		//   same machine.
> 		// - We do the same internally submitted low priority reads in general
> ```

nit: same for internally
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSQtt-DIcrUzk81Zmc:-NcSQtt06cXY6zKAheQL:b-ivihu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L69)):*
> ```Go
> 	settings.SystemOnly,
> 	"sqladmission.elastic_cpu.duration_per_low_pri_read_response",
> 	"controls how many CPU tokens are allotted for handling responses for internally submitted low priority reads",
> ```

kvadmission.elastic_cpu.duration_per_low_pri_read is 10ms while this is 100ms. Can you add some code commentary on why the difference? Presumably there was some experimental basis for this.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSR5445eJShMt09na8:-NcSR5445eJShMt09na9:bmuykzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L75)):*
> ```Go
> 
> // internalLowPriReadElasticControlEnabled determines whether the sql portion of
> // internally submitted low-priorority reads (like row-level TTL selects)
> ```

nit: priority
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 350 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSRNLd8RYX_uyJHEy_:-NcSRNLd8RYX_uyJHEya:bd33d0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L350)):*
> ```Go
> ) {
> 	if sv == nil {
> 		return // only nil in tests
> ```

and in SQL pods?
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 650 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSSHtV5UCTdtT8gyah:-NcSSHtV5UCTdtT8gyai:b-u7rin8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L650)):*
> ```Go
> 	if f.admissionPacer != nil {
> 		// If admissionPacer is initialized, we're using the elastic CPU control
> 		// mechanism (the work is elastic in nature using the slots based
> ```

nit: nature and using

**Review by irfansharif — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-:-NcSdo6A6Ar-7ZuiNfo1:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @rafiss, @sumeerbhola, and @yuzefovich)

___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbyLtYX0qBDyTra-sNH):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Did you mean to collapse into 1 commit? The second commit description has been lost.
</blockquote></details>

Oops, separated back out.
___
*[`pkg/cmd/roachtest/tests/admission_control_row_level_ttl.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcST6_38lyhF6KknONh:-NcScsJt4zbdZcS2JfQ0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/cmd/roachtest/tests/admission_control_row_level_ttl.go#L97)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a TODO for what metric(s) we should read and aggregate to check that AC is working as expected.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvadmission/kvadmission.go` line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NbzmoZC3_Me7BiIrX1v:-NcSaiRE4ZpCK8g7TnP4:bav0nsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/96e69b9748c16fa3264a479855f4cbfde1ad534d/pkg/kv/kvserver/kvadmission/kvadmission.go#L412)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, I realize that. I was referring to the fact that there is nothing in the processing code (like we have in mvcc.go for ExportRequest), that returns if 10ms has been exceeded. So in some sense the integration is incomplete, even though it is probably harmless.
</blockquote></details>

Ah, understood. Yes it should be harmless, but I added a TODO.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSQtt-DIcrUzk81Zmc:-NcSbqQQCMP54wB0ibrB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

kvadmission.elastic_cpu.duration_per_low_pri_read is 10ms while this is 100ms. Can you add some code commentary on why the difference? Presumably there was some experimental basis for this.
</blockquote></details>

Done.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 350 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108815#-NcSRNLd8RYX_uyJHEy_:-NcSc2L00y5JtOro6Y4U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e54e9901eb5a2fa69e8f9c98aa4b0a9be528a72/pkg/sql/row/kv_batch_fetcher.go#L350)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

and in SQL pods?
</blockquote></details>

Done.

**Comment by rafiss** [comment]
This was backported to 23.1.9 and 22.2.14. The behavior is off-by-default in those releases. To enable, use the following hidden cluster settings:
```
SET CLUSTER SETTING kvadmission.low_pri_read_elastic_control.enabled = true;
SET CLUSTER SETTING sqladmission.low_pri_read_response_elastic_control.enabled = true;
```

In v23.2, this behavior is on-by-default, so those cluster settings are no longer needed.

**Pull request merged**
