### PR TITLE
spanconfig: introduce the ProtectedTSReader interface 

### PR DESCRIPTION
**Pull request by arulajmani**
See individual commits for details. 

Release justification: low risk, high benefit changes to existing
functionality.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
This had been on the back burner with all the other PTS related span config changes. Now that all those are in, I've dusted this off. Also changed the `PTSReader` to return a list of protection timestamps instead of encapsulating the "validity" logic based on our conversations in the pod. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-:-Mwlx1gx3Jqzr4-r54Mc:b-a3rdgd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @irfansharif, and @nvanbenschoten)

**Review by arulajmani — COMMENTED** [review]
> Dismissed @adityamaru from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 81 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mtxx-5IKPL9dOB25wJQ-r3-81:-Mx-lIDI4ffrY8Vtdfby:b81azwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/replica_protected_timestamp.go#L81)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I believe this condition is not required/incorrect?
</blockquote></details>

Yikes, not sure how that ended up here ... thanks for pointing it out! 
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mtxx-5IKPL9dOB25wJQ-r3-90:-Mx-ms4mAknB_A3Cz-ev:b-co1984) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/replica_protected_timestamp.go#L90)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we just assign to ts.earliestProtectionTimestamp and get rid of `earliestTS`?
</blockquote></details>

To confirm, you're still saying we should clear out the old `ts.earliestProtectionTimestamp` field here by setting it to an empty timestamp above, right? 

Looking at the diff, the old code didn't do that -- it should have, right?
___
*[pkg/kv/kvserver/protectedts/ptprovider/provider.go, line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-MwlwqaCVP2I_K9pwp4b-r3-68:-Mx02gBV2Ro-IQrkorMg:b-txtf5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/protectedts/ptprovider/provider.go#L68)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we delete the Cache field?
</blockquote></details>

See above. 
___
*[pkg/server/server.go, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-MwlwqaCVP2I_K9pwp4e-r3-530:-Mx-teCVDK6NokwdGc6o:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/server/server.go#L530)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we delete `ProtectedTimestampCache`?
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/protectedts/protectedts.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-MwlwqaCVP2I_K9pwp4X-r3-41:-Mx02f4uEovzD9SHhHIR:b60oz7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/protectedts/protectedts.go#L41)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we delete Cache from here too?
</blockquote></details>

We talked about this on offline, but capturing the conversation here as well -- I tried doing so but then I realized that the Cache is used by the GCJob as well. Thinking about this a bit more, adding the `spanconfig.ProtectedTSReader` on the provider wasn't correct -- the `Provider` is a SQL concept, whereas we expect the `spanconfig.ProtectedTSReader` to be a per-store thing going forward. To that end, instead of providing the `spanconfig.ProtectedTSReader` to KV via the `Provider` I think it makes more sense to instantiate one using the system tenant's `ptcache.Cache` (old substystem) and `KVSubscriber` (going forward). Made the change in `server.go`, PTAL. 

The GC job realization above does lead to something we hadn't considered yet -- secondary tenants need to consult their protected TS information in their GC Job. We can't re-use the `protectedts.Cache' as-is there. This is because the Cache works on spans (which secondary tenants never set, as we've moved to protecting schema objects). We'll need to consult something similar to the `spanconfig.ProtectedTSStateReader', which we use in the SQLTranslator, instead.

**Comment by adityamaru** [comment]
>The GC job realization above does lead to something we hadn't considered yet -- secondary tenants need to consult their protected TS information in their GC Job

Filed https://github.com/cockroachdb/cockroach/issues/77156 as a release blocker.

**Review by adityamaru — APPROVED** [review]
Nice! LGTM but I'll defer to KV for a final stamp.

**Review by nvb — APPROVED** [review]
:lgtm: 

@ajwerner might also want to take a look at this, as he was the original author of the protected timestamp system.

> Reviewed 3 of 4 files at r2, 15 of 15 files at r4, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-:-Mx4OugI2Wv-rVT_jlI9:bjp1cdo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfig.go, line 406 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx4LWjG9HsMbD49BH0d:-Mx4LWjG9HsMbD49BH0e:b-sz5gib) ([raw file](https://github.com/cockroachdb/cockroach/blob/17d97f49896917eefc4c17c3c3c39efa2fdbd5d5/pkg/spanconfig/spanconfig.go#L406)):*
> ```Go
> type ProtectedTSReader interface {
> 	// GetProtectionTimestamps returns all protected timestamps that apply to the
> 	// any part of the given key span. The time at which this protection timestamp
> ```

"to the any"
___
*[pkg/spanconfig/spanconfigptsreader/adapter.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx4LsoP6ZT07HJpfXCM:-Mx4LsoP6ZT07HJpfXCN:b-2cfgz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/17d97f49896917eefc4c17c3c3c39efa2fdbd5d5/pkg/spanconfig/spanconfigptsreader/adapter.go#L27)):*
> ```Go
> // V1 of the protected timestamp subsystem only allowed protections to be set
> // over spans belonging to the system tenant. These protections were stored in
> // memory by ptcache.Cache. V2 of the subsystem allows protections to be set
> ```

Is the "in memory" qualifier here meaningful? These protected timestamps are still backed by a system table, which is no different than with V2, so what are you trying to indicate?

Would we accomplish the same thing by saying "These protections were cached on each node in the cluster by ptcache.Cache."?
___
*[pkg/spanconfig/spanconfigptsreader/adapter.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx4NEXy9dhiN8fMWJPw:-Mx4NEXy9dhiN8fMWJPx:b-nar2kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/17d97f49896917eefc4c17c3c3c39efa2fdbd5d5/pkg/spanconfig/spanconfigptsreader/adapter.go#L38)):*
> ```Go
> //  subsystem, and we'd be able to get rid of this interface.
> //
> // TODO(arul): Embed the KVSubscriber here as well and actually encapsulate PTS
> ```

Since we plan to follow this PR up with this TODO, let's not embed the `Cache` in `adapter`. Instead, let's name the field and implement `ProtectedTSReader` explicitly. We don't want `adapter` to inherit all of `Cache`'s methods anyway.
___
*[pkg/kv/kvserver/client_protectedts_test.go, line 230 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx1BNr54ORV9TbjCHmQ:-Mx1BNr54ORV9TbjCHmR:bghiz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b815fba8b629b7efebfa63f807cb843a94bb5c/pkg/kv/kvserver/client_protectedts_test.go#L230)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// replica can read it from. We then verify (below) that the failed record
> ```

Did this comment get cut off?
___
*[pkg/kv/kvserver/client_protectedts_test.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx1BSw4Aq-d_36WD0AJ:-Mx1BSw4Aq-d_36WD0AK:bxgpy5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b815fba8b629b7efebfa63f807cb843a94bb5c/pkg/kv/kvserver/client_protectedts_test.go#L274)):*
> ```Go
> }
> 
> func verifyProtectionTimestampExistsOnSpans(
> ```

Let's give this a comment.
___
*[pkg/kv/kvserver/protectedts/protectedts.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-MwlwqaCVP2I_K9pwp4X-r3-41:-Mx4Oiyk9hStyF78rzy9:b-x9nbwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/protectedts/protectedts.go#L41)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We talked about this on offline, but capturing the conversation here as well -- I tried doing so but then I realized that the Cache is used by the GCJob as well. Thinking about this a bit more, adding the `spanconfig.ProtectedTSReader` on the provider wasn't correct -- the `Provider` is a SQL concept, whereas we expect the `spanconfig.ProtectedTSReader` to be a per-store thing going forward. To that end, instead of providing the `spanconfig.ProtectedTSReader` to KV via the `Provider` I think it makes more sense to instantiate one using the system tenant's `ptcache.Cache` (old substystem) and `KVSubscriber` (going forward). Made the change in `server.go`, PTAL. 

The GC job realization above does lead to something we hadn't considered yet -- secondary tenants need to consult their protected TS information in their GC Job. We can't re-use the `protectedts.Cache' as-is there. This is because the Cache works on spans (which secondary tenants never set, as we've moved to protecting schema objects). We'll need to consult something similar to the `spanconfig.ProtectedTSStateReader', which we use in the SQLTranslator, instead. 


</blockquote></details>

Do we have an issue tracking the GC job changes we'll need to land for this release?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigptsreader/adapter.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx4LsoP6ZT07HJpfXCM:-Mx5_F0f4_Ez2ATxTsm0:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/17d97f49896917eefc4c17c3c3c39efa2fdbd5d5/pkg/spanconfig/spanconfigptsreader/adapter.go#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the "in memory" qualifier here meaningful? These protected timestamps are still backed by a system table, which is no different than with V2, so what are you trying to indicate?

Would we accomplish the same thing by saying "These protections were cached on each node in the cluster by ptcache.Cache."?
</blockquote></details>

Done. 
___
*[pkg/spanconfig/spanconfigptsreader/adapter.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-Mx4NEXy9dhiN8fMWJPw:-Mx5UgH3AHKCZ4k3eQxo:b90l4wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/17d97f49896917eefc4c17c3c3c39efa2fdbd5d5/pkg/spanconfig/spanconfigptsreader/adapter.go#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Since we plan to follow this PR up with this TODO, let's not embed the `Cache` in `adapter`. Instead, let's name the field and implement `ProtectedTSReader` explicitly. We don't want `adapter` to inherit all of `Cache`'s methods anyway.
</blockquote></details>

Done. "embed" wasn't the right phrasing for the TODO above either. 
___
*[pkg/kv/kvserver/protectedts/protectedts.go, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-MwlwqaCVP2I_K9pwp4X-r3-41:-Mx510jf4vA6JcfBK4gG:b-f6yaem) ([raw file](https://github.com/cockroachdb/cockroach/blob/c58cdaac49b477dbef7b1e5441f968d22eb76f84/pkg/kv/kvserver/protectedts/protectedts.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we have an issue tracking the GC job changes we'll need to land for this release?
</blockquote></details>

Aditya filed https://github.com/cockroachdb/cockroach/issues/77156 and we've marked it a release blocker.

**Review by nvb — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @irfansharif)

**Review by ajwerner — APPROVED** [review]
:lgtm:

Though only gave it a cursory review. 

> Reviewed 3 of 4 files at r2, 15 of 15 files at r4, 14 of 21 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75285#-:-Mx5q-24EQ3lfbKQvREb:b3yh1fo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

**Comment by arulajmani** [comment]
TFTRs! CI failure is a flake, merging. 

bors r=adityamaru,nvanbenschoten,ajwerner

**Comment by arulajmani** [comment]
Flakes, plus didn't realize the PR description needs a release justification in addition to the commit messages. Let's try again! 

bors r=adityamaru,nvanbenschoten,ajwerner

**Pull request merged**
