### PR TITLE
sql: add cluster setting for opt-driven FK checks, rename experimental_enable_zigzag_join

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: add cluster setting for opt-driven FK checks

Also renames the session setting to remove the `experimental_` part.

Release note: None

#### sql: rename experimental_enable_zigzag_join

Remove the "experimental" since it's enabled by default (and has been
for a while).

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40307#-:-LnP0Xua2YXzUK6uJ4CD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

**Comment by RaduBerinde** [comment]
Made a few fixes: changed the name to end in `.enabled` and added the session setting to the list of settings that `EXPLAIN ENV` shows (if changed).

**Review by justinj — COMMENTED** [review]
:thumbsup: still lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40307#-:-LnSj-bq7xEQPB_K1WLo:bq0vdy7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
