### PR TITLE
jobs: remove all of the deprecated stuff

### PR DESCRIPTION
**Pull request by yuzefovich**
**jobs: factor out non-deprecated part from deprecatedInsert**

Previously, `deprecatedInsert` method contained the code for both old
and new approaches. This commit refactors it into two separate methods,
and the follow-up commit will remove the deprecated stuff altogether.

Release note: None

**jobs: remove all of the deprecated stuff**

In 20.2 release we refactored the jobs framework but kept the original
implementation in order to be able to migrate to 20.2 version. Now we
can remove the deprecated stuff.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
@ajwerner I looked into removing this stuff while I was pondering about the jobs unit test failure in the streaming internal executor. This PR is of very low priority, but I think it is RFAL.

In the second commit I'm removing several unit tests that explicitly use 20.1 version of CockroachDB cluster, I believe they are no longer relevant, but please let me know if we can/should refactor them to adjust to the new jobs infrastructure.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62781#-:-MX5OTAp3AyxSyDQ0qnj:b4wj87c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62781#-MX5OK0_04olukrvGvxB:-MX5OK0_04olukrvGvxC:bhp4kgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6f15915fe7ed5108df5adf439774047691a38ad/pkg/jobs/registry.go#L431)):*
> ```Go
> 		return nil, errors.Wrap(err, "error getting live session")
> 	}
> 	// TODO(yuzefovich): is using nil lease correct here?
> ```

Need to address this TODO in the first commit.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/server/server_sql.go, line 766 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62781#-MX5PEYgAzHol_M37Ub1:-MX5PEYgAzHol_M37Ub2:b3cby3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b855bb24da14082c56513a1165c9827f52fdd26/pkg/server/server_sql.go#L766)):*
> ```Go
> 
> 	// Start the sqlliveness subsystem.
> 	s.sqlLivenessProvider.Start(ctx)
> ```

The code changes here might require special attention.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/issues/54251 / #61417

**Comment by yuzefovich** [comment]
hehe, should've checked first.

I'll close this PR then.

**Pull request closed without merging**
