### PR TITLE
jobs, backupccl: store dependent schedule id on full/inc schedules

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, if a schedule was one of the two schedules that
was created when setting up a full+incremental backup, we
would store the recurrence crontab of each schedule on the
other. This was done to facilitate `SHOW CREATE SCHEDULE`
which outputs a `CREATE SCHEDULE` statement that is functionally
equivalent to the original `CREATE SCHEDULE` that was used to
setup the schedules.

This change replaces the dependent crontab, with the dependent
schedule ID. This means that we incur one extra lookup when
resolving the dependent crontab, but this is okay. Storing the
ID allows for more flexibility in the future (#68446) and establishes
a relationship between the two schedules that were implicitly
created in the first place.

This change also tweaks what the `first_run` will be set to
on the output of `SHOW CREATE SCHEDULE`. It will now be
set to the sooner of the scheduled run for the full and incremental.
Consider a case where a full is scheduled to run after 5 hours, but
an incremental is scheduled to run after 2 hours. If a user copy
pastes the output of `SHOW CREATE SCHEDULE` something should run
in two hours. That something can't be an incremental, cause we need
a full to start the chain.
If both full and inc have zero date scheduled runs, we set the next_run
to now().

Release note: None

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @annezhu98, and @dt)

___
*[pkg/ccl/backupccl/create_scheduled_backup.go, line 412 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68844#-MgxJGQE00xfkHrapJTK:-MgxJGQE00xfkHrapJTL:b1d5i5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/25103f1522027eb539866147c7e93285e1444da4/pkg/ccl/backupccl/create_scheduled_backup.go#L412)):*
> ```Go
> ) error {
> 	args := &ScheduledBackupExecutionArgs{}
> 	if err := pbtypes.UnmarshalAny(schedule.ExecutionArgs().Args, args); err != nil {
> ```

change signature of makeBackupSchedule to return schedule execution args so that you don't need to unmarshal anything.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68844)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @annezhu98, and @dt)

___
*[pkg/ccl/backupccl/backup.proto, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68844#-MgxJrQ2BZAu07AiusrF:-MgxJrQ2BZAu07AiusrG:b9gjloy) ([raw file](https://github.com/cockroachdb/cockroach/blob/25103f1522027eb539866147c7e93285e1444da4/pkg/ccl/backupccl/backup.proto#L165)):*
> ```protobuf
>   // the schedule ID of the other "dependent" schedule.
>   // i.e. the full schedule will have the inc schedules ID and vice versa.
>   int64 dependent_schedule_id = 5 [(gogoproto.customname) = "DependentScheduleID"];
> ```

perhaps explicitly state that 0 dependent schedule id means -- no dependent schedule?

**Review by annezhu98 — APPROVED** [review]
LGTM!

**Comment by adityamaru** [comment]
> perhaps explicitly state that 0 dependent schedule id means -- no dependent schedule?

done

> change signature of makeBackupSchedule to return schedule execution args so that you don't need to unmarshal anything.

done

**Comment by adityamaru** [comment]
I'm going to follow this up with some work on `DROP SCHEDULES`, TFTR!

bors r+

**Pull request merged**
