### PR TITLE
builtins: add unimplemented errors for full text search builtins

### PR DESCRIPTION
**Pull request by otan**
Refs: #7821, #51424 

Release note: None

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54573)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/sem/builtins/builtins.go, line 2867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54573#-MHXB2w5CyqD9IyWEsX4:-MHXB2w5CyqD9IyWEsX5:b-9h5dq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/301b72835737a0571568a0616385e2c325670550/pkg/sql/sem/builtins/builtins.go#L2867)):*
> ```Go
> 	"json_to_tsvector":     makeBuiltin(tree.FunctionProperties{UnsupportedWithIssue: 7821, Category: categoryFullTextSearch}),
> 	"jsonb_to_tsvector":    makeBuiltin(tree.FunctionProperties{UnsupportedWithIssue: 7821, Category: categoryFullTextSearch}),
> 	"phraseto_tsquery":     makeBuiltin(tree.FunctionProperties{UnsupportedWithIssue: 7821, Category: categoryFullTextSearch}),
> ```

This list doesn't seem to include all the functions from https://www.postgresql.org/docs/12/functions-textsearch.html. Is that intentional?

**Comment by otan** [comment]
___
*[pkg/sql/sem/builtins/builtins.go, line 2867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54573#-MHXB2w5CyqD9IyWEsX4:-MHXFA-k8SlyCK06xwi5:b-4ehtf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/301b72835737a0571568a0616385e2c325670550/pkg/sql/sem/builtins/builtins.go#L2867)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This list doesn't seem to include all the functions from https://www.postgresql.org/docs/12/functions-textsearch.html. Is that intentional? 
</blockquote></details>

ok, missed  a few with my pgproc query. fixed now!

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54573#-:-MHXItgI-qs63nSft2v8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by otan** [comment]
tftr!

bors r=arulajmani

**Pull request merged**
