### PR TITLE
storage: improve the heuristic for recomputing raft log size

### PR DESCRIPTION
**Pull request by tbg**
Improve a previous heuristic that would trigger a recomputation
of the Raft log size. The previous heuristic recomputed only
when the existing size was zero (in which case it was definitely
wrong, and is the case exercised after a restart without further
activity).

However, it can be wrong in other ways (restart with further activity)
and having an explicit bool that is reset whenever we know the state is
safe and invalidated whenever we suspect it has become unsafe is easier
to reason about and more effective.

The plan is to mark the log size as untrustworthy after applying a
snapshot, as that operation in the near future will avoid sending
the past Raft log to avoid stability problems if the Raft log is
very large (even if the log size doesn't reflect that).

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
why would sending a snapshot without the log make the log size invalid? Wouldn't the log size remain as it was, unaffected by the snapshot that we just received?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35685#-:-L_rUNm8BBZ1BljhQPCk:bwjhn16)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by andreimatei** [comment]
Or is it not that the stats become invalid, but that we'd want to trigger
GC regardless of the stats after the snapshot?

**Review by tbg — COMMENTED** [review]
The deltas for the Raft log truncation are computed at the leaseholder. Let's say the leaseholder has log `1..100` and sends a snapshot to the follower when it has applied log index `50`. In that case, the follower will have log `51..100`.

What the follower's tracked raft log size depends. If the follower is "new" (i.e. wasn't an initialized replica before) it'll be zero and is obviously invalid.
If the follower previously already had some log entries, they are deleted and replaced with whatever is in the snapshot (`51.100`). The previous `raftLogSize` is almost certainly invalid as well, because it tracked (perhaps correctly) what the previous log was. In practice, btw, the number of Raft log entries in the snapshot is expected to be very small thanks to avoiding the historical entries, though thanks to SST sideloading a single entry during IMPORT/RESTORE clocks in at ~25mb. So we're potentially off by a lot even if there's very little log, enough to trigger all of these "snapshot refused because log too large" errors.

We can try to jump through hoops to propagate the "correct" numbers (recompute and include it in the snapshot), but I'm declaring bankruptcy on that intentionally. I'm convinced that somewhere down the road we'll "localize" the truncation decisions, that is, not carry out log truncation through Raft commands. The way to make that easy to reason about is to do the correct computations only in the steady state and to simply invalidate them whenever there's a more complicated state change, or perhaps even a combination of not accounting for the size of the log and truncating the log more aggressively based on a timer.

These are obviously out of scope for 19.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35685#-:-L_rgPM1CXBoC1gQM37Q:b8i45o6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
Oh, and what I forgot to mention is this: the replicated nature of the raft log size breaks down because if in the scenario above the leader decides to truncate to index `70`, it will compute `size(1..70)` which is, say, 1mb. The follower however doesn't have `1..49` and by reducing its raft log size by 1mb, it has just clobbered its state even if it was correct.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35685#-:-L_tSsfZ0p9QCTJSaMdS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35685#-L_tSdGNEWhutNS6W7ae:-L_tSdGNEWhutNS6W7af:b-d2h4cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/23e518451744139243858d4b6c2c0516c0eddd61/pkg/storage/replica.go#L266)):*
> ```Go
> 		// If raftLogSizeTrusted is false, don't trust the above raftLogSize until
> 		// it has been recomputed.
> 		raftLogSizeTrusted bool
> ```

consider plumbing this to the range page on the UI

**Comment by tbg** [comment]
Good call, did the plumbing.
TFTR

bors r=andreimatei

**Comment by tbg** [comment]
Flaked on #34081 

bors r=andreimatei

**Pull request merged**
