### PR TITLE
sql: add a SQL benchmark that stresses storage and KV

### PR DESCRIPTION
**Pull request by sumeerbhola**
This benchmark is derived from the existing BenchmarkKV/Update/SQL
and does `UPDATE bench.kv SET v = v + 1 WHERE k IN (...)`
for 100 keys.

There is a long code comment that describes why this is a
good proxy for storage performance since it has two batches
with ~100 requests (100 ScanRequests and 100 PutRequests).

I am using this as a basis for Pebble optimizations for the
separated lock table and to measure the effect of an
existing post-20.2 Pebble optimization that was originally
motivated by inverted and lookup joins.

Here are some numbers illustrating how performance is
evolving. All of these are run with -benchtime 5000x so that
there is enough data to have some files in the LSM (not
everything in the memtable).

The following are compared:
- 20.2: no separated locks, of course.
- master_nosep: No separated locks (DisallowSeparatedIntent=true).
  This is not quite master since it includes bug
  fixes in https://github.com/cockroachdb/cockroach/pull/59097
  that I need to cleanup and merge, but should be the same from
  a performance perspective.
- master_sep: DisallowSeparatedIntents=false,
  enabledSeparatedIntents=true, i.e., it has separated locks.
  The performance is the same as enabledSeparatedIntents=false
  since the performance impact is due to needing two iterators,
  so I am not including this other setting below.

The master code includes the Pebble optimizations for multiple
ScanRequests in a batch, that were made post-20.2 in
https://github.com/cockroachdb/pebble/pull/951 and
https://github.com/cockroachdb/pebble/pull/947. We refer to it
as the SeekGEWithBounds optimization below.

- seekprefixge_nosep: No separated locks. This is master with
  the experimental Pebble optimization for SeekPrefixGE that is
  in
  https://github.com/sumeerbhola/pebble/commit/1d07c666129d2678700f2ff1c69cb7f3e9607504
  This optimization helps PutRequests in a batch.

- seekprefixge_sep: The previous, but with separated locks.

**old: 20.2 new: master_nosep**. The improvement is due to the SeekGEWithBounds optimization
```
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    4.88ms ± 2%    3.27ms ± 2%  -32.85%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16    5.02ms ± 1%    3.28ms ± 1%  -34.72%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    5.32ms ± 1%    3.65ms ± 1%  -31.44%  (p=0.008 n=5+5)

name                                old alloc/op   new alloc/op   delta
KVAndStorageUsingSQL/versions=2-16     662kB ± 0%     665kB ± 0%   +0.42%  (p=0.032 n=5+5)
KVAndStorageUsingSQL/versions=4-16     657kB ± 0%     659kB ± 0%   +0.36%  (p=0.016 n=5+5)
KVAndStorageUsingSQL/versions=8-16     659kB ± 0%     661kB ± 0%   +0.41%  (p=0.032 n=5+5)

name                                old allocs/op  new allocs/op  delta
KVAndStorageUsingSQL/versions=2-16     3.62k ± 0%     3.77k ± 0%   +4.20%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     3.62k ± 0%     3.77k ± 0%   +4.13%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     3.62k ± 0%     3.78k ± 0%   +4.25%  (p=0.008 n=5+5)
```

**old: 20.2 new: seekprefixge_nosep**. This includes the additional SeekPrefixGE optimization.
```
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    4.88ms ± 2%    2.07ms ± 2%  -57.48%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16    5.02ms ± 1%    2.07ms ± 0%  -58.81%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    5.32ms ± 1%    2.44ms ± 1%  -54.07%  (p=0.008 n=5+5)

name                                old alloc/op   new alloc/op   delta
KVAndStorageUsingSQL/versions=2-16     662kB ± 0%     663kB ± 0%     ~     (p=1.000 n=5+5)
KVAndStorageUsingSQL/versions=4-16     657kB ± 0%     658kB ± 0%   +0.15%  (p=0.016 n=5+5)
KVAndStorageUsingSQL/versions=8-16     659kB ± 0%     658kB ± 0%     ~     (p=0.222 n=5+5)

name                                old allocs/op  new allocs/op  delta
KVAndStorageUsingSQL/versions=2-16     3.62k ± 0%     3.75k ± 0%   +3.56%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     3.62k ± 0%     3.75k ± 0%   +3.50%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     3.62k ± 0%     3.75k ± 0%   +3.54%  (p=0.008 n=5+5)
```

**old: 20.2 new: master_sep**. Despite the SeekGEWithBounds optimization, we are slower
  with separated locks compared to 20.2
```
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    4.88ms ± 2%    5.62ms ±19%     ~     (p=0.690 n=5+5)
KVAndStorageUsingSQL/versions=4-16    5.02ms ± 1%    6.49ms ± 2%  +29.42%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    5.32ms ± 1%    7.42ms ± 2%  +39.55%  (p=0.008 n=5+5)

name                                old alloc/op   new alloc/op   delta
KVAndStorageUsingSQL/versions=2-16     662kB ± 0%     700kB ± 0%   +5.63%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     657kB ± 0%     696kB ± 0%   +6.00%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     659kB ± 0%     698kB ± 0%   +5.96%  (p=0.008 n=5+5)

name                                old allocs/op  new allocs/op  delta
KVAndStorageUsingSQL/versions=2-16     3.62k ± 0%     4.70k ± 0%  +29.83%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     3.62k ± 0%     4.71k ± 0%  +29.97%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     3.62k ± 0%     4.71k ± 0%  +30.04%  (p=0.008 n=5+5)
```

**old: 20.2 new: seekprefixge_sep**. With both Pebble optimizations, separated is faster
  than 20.2
```
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    4.88ms ± 2%    2.42ms ± 1%  -50.43%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16    5.02ms ± 1%    2.44ms ± 1%  -51.31%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    5.32ms ± 1%    3.62ms ± 1%  -31.88%  (p=0.008 n=5+5)

name                                old alloc/op   new alloc/op   delta
KVAndStorageUsingSQL/versions=2-16     662kB ± 0%     695kB ± 0%   +4.89%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     657kB ± 0%     688kB ± 0%   +4.78%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     659kB ± 0%     692kB ± 0%   +5.07%  (p=0.008 n=5+5)

name                                old allocs/op  new allocs/op  delta
KVAndStorageUsingSQL/versions=2-16     3.62k ± 0%     4.66k ± 0%  +28.75%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     3.62k ± 0%     4.66k ± 0%  +28.54%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     3.62k ± 0%     4.67k ± 0%  +28.93%  (p=0.008 n=5+5)
```

**old: seekprefixge_nosep new: seekprefixge_sep**. Turning on separated locks is slower,
as expected. That is, we are giving back some of the gains since 20.2, but since our
users aren't yet used to those gains, this is ok (would become a problem if we don't
enable separated locks in 21.1).
```
benchstat ~/sep_lt/bench.branch_with_seekprefix_opt.nosep ~/sep_lt/bench.branch_with_seekprefix_opt.sep
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    2.07ms ± 2%    2.42ms ± 1%  +16.58%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16    2.07ms ± 0%    2.44ms ± 1%  +18.20%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    2.44ms ± 1%    3.62ms ± 1%  +48.32%  (p=0.008 n=5+5)

name                                old alloc/op   new alloc/op   delta
KVAndStorageUsingSQL/versions=2-16     663kB ± 0%     695kB ± 0%   +4.86%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     658kB ± 0%     688kB ± 0%   +4.62%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     658kB ± 0%     692kB ± 0%   +5.25%  (p=0.008 n=5+5)

name                                old allocs/op  new allocs/op  delta
KVAndStorageUsingSQL/versions=2-16     3.75k ± 0%     4.66k ± 0%  +24.33%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16     3.75k ± 0%     4.66k ± 0%  +24.19%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16     3.75k ± 0%     4.67k ± 0%  +24.52%  (p=0.008 n=5+5)
```

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I've included all the storage folks primarily for the performance numbers, and for context for future Pebble PRs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-:-MRv1dv28bJVZhUV8uZE:byl0vdv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @nvanbenschoten, and @petermattis)

**Review by nvb — APPROVED** [review]
:lgtm_strong: it looks like https://github.com/sumeerbhola/pebble/commit/1d07c666129d2678700f2ff1c69cb7f3e9607504 is very beneficial.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-:-MS-107F162r6bqtjMMT:bci6wxx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[pkg/sql/tests/kv_test.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MRzyS4cE4c7Tg-DZNG7:-MRzyS4cE4c7Tg-DZNG8:b-nqkbzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L187)):*
> ```Go
> func (kv *kvSQL) UpdateWithShift(rows, run int) error {
> 	startRow := rows * run
> 	perm := rand.Perm(rows)
> ```

Should we stop permuting here as well then?
___
*[pkg/sql/tests/kv_test.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MRzz8Z86zLAaa2RjzJV:-MRzz8Z86zLAaa2RjzJW:b-g9f4fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L330)):*
> ```Go
> // numbers of rows is tricky due to the optimization that switches scans for a
> // large set specified by the SQL IN operator to full table scans that are not
> // bounded by the [smallest, largest] key in the set.
> ```

I wonder if this means that we aren't gathering stats for the `bench.kv` table before running the benchmark, so we're underestimating the number of rows in the table. Out of curiosity, do things change if you add an `ANALYZE bench.kv` to the end of `kvSQL.prep`?
___
*[pkg/sql/tests/kv_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS--hHx3Ufnvivb0e5x:-MS--hHy5W2WttYw-Yvk:bwjau46) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L342)):*
> ```Go
> // focusing on smaller batches because latency improvements for queries that
> // are small and already fast are not really beneficial to the user.
> // Specifically, these transactional update queries run as a 1PC transaction
> ```

are they run as 1PC? Is everything on the same Range?
___
*[pkg/sql/tests/kv_test.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS-0-jF3oFDPyWLbk3a:-MS-0-jF3oFDPyWLbk3b:bov1d0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L346)):*
> ```Go
> // - A read-only batch with 100 ScanRequests (this should eventually be
> //   optimised by SQL to 100 GetRequests
> //   https://github.com/cockroachdb/cockroach/issues/46758). The spans in the
> ```

It would be interesting to run the patch from https://github.com/cockroachdb/cockroach/issues/46758 (https://github.com/nvanbenschoten/cockroach/commit/8bce292019b7bacf2008e19b67b64925994a6394) on this benchmark and see if we can measure any improvement.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-:-MS-RqZ6-O_X_r9ftIx1:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @nvanbenschoten, and @petermattis)

___
*[pkg/sql/tests/kv_test.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MRzyS4cE4c7Tg-DZNG7:-MS-HOL1Aj4UPiTCPw3O:bd6049u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we stop permuting here as well then?
</blockquote></details>

The SQL code does the sort, so the permutation has no effect. And not expecting the user query to have keys in sorted order is possibly more realistic.
___
*[pkg/sql/tests/kv_test.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MRzz8Z86zLAaa2RjzJV:-MS-LikVC64Up0OWou8h:b-6vp44o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L330)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I wonder if this means that we aren't gathering stats for the `bench.kv` table before running the benchmark, so we're underestimating the number of rows in the table. Out of curiosity, do things change if you add an `ANALYZE bench.kv` to the end of `kvSQL.prep`?
</blockquote></details>

It seems to be fixed with the addition of  `ANALYZE bench.kv`. Thanks.

I still need to confirm where this optimization originates. I've added a TODO to merge this back, though I would still keep the long comment so that it doesn't hide among lots of parameterized tests. And this one is adding another parameterization dimension wrt `maxVersions` which doesn't apply to `kvInterface.Insert`, and I need to think of what to do about `kvInterface.Delete` wrt versions. So I somewhat prefer punting on this TODO for a future PR.
 
___
*[pkg/sql/tests/kv_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS--hHx3Ufnvivb0e5x:-MS-I3wi7a8XBi2GCOUw:b-7dhlgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

are they run as 1PC? Is everything on the same Range?
</blockquote></details>

Yes, I saw 1PC on the call stack in the instrumented code. And yes, I think everything, including the whole table being updated is on the same range, which is why I see `BatchRequests` on the replica with 100 ScanRequests and 100 PutRequests.
___
*[pkg/sql/tests/kv_test.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS-0-jF3oFDPyWLbk3a:-MS-PBi5DNl7L6L_c84r:bp8t3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L346)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would be interesting to run the patch from https://github.com/cockroachdb/cockroach/issues/46758 (https://github.com/nvanbenschoten/cockroach/commit/8bce292019b7bacf2008e19b67b64925994a6394) on this benchmark and see if we can measure any improvement.
</blockquote></details>

Interesting. IIUC, that hack is using the fact that any shared lock must be for a span that is a single key, even though there is an EndKey that isn't simply the Key + \x00 (it turns out to be Key + \xfe based on my instrumentation). Is that correct?

The code in that area has changed a bit and I am not sure what to do about the `RequestUnion_Scan`
https://github.com/cockroachdb/cockroach/blob/aaa44bde23b92123327c5cc02fc764c0b16ac5d9/pkg/sql/row/kv_batch_fetcher.go#L333-L343
So I didn't run it.

 I suspect that in the absence of the experimental Pebble change, it will usually (for maxVersions={2, 4}) be slower since the `SeekPrefixGE` is not yet optimized while the `SeekGE` with monotonic bounds is (used by the `ScanRequest`). With the Pebble experimental change it should be faster assuming that bloom filter checking is very cheap (probably cheap because I didn't spot it in any cpu profiles).

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59397)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @petermattis, and @sumeerbhola)

___
*[pkg/sql/tests/kv_test.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MRzz8Z86zLAaa2RjzJV:-MS06p9P5nEL1GRTOYAm:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L330)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It seems to be fixed with the addition of  `ANALYZE bench.kv`. Thanks.

I still need to confirm where this optimization originates. I've added a TODO to merge this back, though I would still keep the long comment so that it doesn't hide among lots of parameterized tests. And this one is adding another parameterization dimension wrt `maxVersions` which doesn't apply to `kvInterface.Insert`, and I need to think of what to do about `kvInterface.Delete` wrt versions. So I somewhat prefer punting on this TODO for a future PR.
 

</blockquote></details>

SGTM.
___
*[pkg/sql/tests/kv_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS--hHx3Ufnvivb0e5x:-MS06sDVC8aOHgksjQh4:b-wb8fp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L342)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, I saw 1PC on the call stack in the instrumented code. And yes, I think everything, including the whole table being updated is on the same range, which is why I see `BatchRequests` on the replica with 100 ScanRequests and 100 PutRequests.
</blockquote></details>

Got it. We may want to disable load-based splitting to prevent that from changing during a long version of this test.
___
*[pkg/sql/tests/kv_test.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS-0-jF3oFDPyWLbk3a:-MS0708W9Cbbxr9mt2WO:b-qvu544) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L346)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Interesting. IIUC, that hack is using the fact that any shared lock must be for a span that is a single key, even though there is an EndKey that isn't simply the Key + \x00 (it turns out to be Key + \xfe based on my instrumentation). Is that correct?

The code in that area has changed a bit and I am not sure what to do about the `RequestUnion_Scan`
https://github.com/cockroachdb/cockroach/blob/aaa44bde23b92123327c5cc02fc764c0b16ac5d9/pkg/sql/row/kv_batch_fetcher.go#L333-L343
So I didn't run it.

 I suspect that in the absence of the experimental Pebble change, it will usually (for maxVersions={2, 4}) be slower since the `SeekPrefixGE` is not yet optimized while the `SeekGE` with monotonic bounds is (used by the `ScanRequest`). With the Pebble experimental change it should be faster assuming that bloom filter checking is very cheap (probably cheap because I didn't spot it in any cpu profiles).

</blockquote></details>

Oh sorry, the hack is even worse than that. It's just using `FOR SHARED` because that's currently ignored, so it was a convenient way for me to say "only apply this change to the kv workload".

I can update that prototype and test it out on this benchmark once it's merged.
___
*[pkg/sql/tests/kv_test.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS06mWn5wvJcka4TTYR:-MS06mWn5wvJcka4TTYS:bilyl2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1b212073b8211c0f2d5b8a0237f0de0b216be73/pkg/sql/tests/kv_test.go#L274)):*
> ```Go
> 	var err error
> 	if numRowsInBatch > 0 {
> 		_, err = kv.db.Exec(kv.buf.String())
> ```

Looks like we're now missing error handling here.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59397)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/sql/tests/kv_test.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS--hHx3Ufnvivb0e5x:-MS4Ohhq3NU-HGAQYnqy:b-s8qw50) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Got it. We may want to disable load-based splitting to prevent that from changing during a long version of this test.
</blockquote></details>

Ack. I've added a TODO.
___
*[pkg/sql/tests/kv_test.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS-0-jF3oFDPyWLbk3a:-MS4P27b2i3CicR_nuwN:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4c3196c1826fad8bb74575ec5e744e5f6fc0c9/pkg/sql/tests/kv_test.go#L346)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Oh sorry, the hack is even worse than that. It's just using `FOR SHARED` because that's currently ignored, so it was a convenient way for me to say "only apply this change to the kv workload".

I can update that prototype and test it out on this benchmark once it's merged.
</blockquote></details>

Ack
___
*[pkg/sql/tests/kv_test.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59397#-MS06mWn5wvJcka4TTYR:-MS4Oe072jqh8Yka7HHJ:bxc7g56) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1b212073b8211c0f2d5b8a0237f0de0b216be73/pkg/sql/tests/kv_test.go#L274)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we're now missing error handling here.
</blockquote></details>

oops. Fixed

**Pull request merged**
