### PR TITLE
log/eventpb: make certain fields conditionally redactable

### LINKED ISSUE #65469: log: redact ApplicationName values that don't have a "$" prefix in logging events
**Describe the problem**

`ApplicationName` values that start with the "$" prefix are not redacted in telemetry; however those that _don't_ have that prefix are redacted.

We need to apply this special case for logging events so that we don't risk exposing PII. 

cc @knz @kevin-v-ngo 

Epic [CC-4113](https://cockroachlabs.atlassian.net/browse/CC-4113)

### PR DESCRIPTION
**Pull request by knz**
Fixes #65469.

We want application names that start with a `$` to not be redacted.
Also, for compatibility with pgwire authentication logging
we want the `User` field to not be redacted if it is populated with
`root` or `node`.

To achieve this, this commit extends the protobuf annotation
system with a new annotation `redact:"safeif:<regexp>"` which marks
strings as sensitive unless the regexp matches.

cc @cockroachdb/server 
cc @maryliag 

Release note (security update): The `User` and `ApplicationName` fields
of structured events pertaining to SQL queries are now marked
as non-sensitive when they contain certain values (`root`/`node` for
`User`, values starting with `$` for application names).

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm:

I'm curious why we have a manually written JSON encoder. Is this a performance issue or related to functionality details that are unique?

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66175#-:-MbmKe0_1YWRJqKS-UwJ:b22xz7m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
Unique functionality: the special treatment of redactable fields

**Comment by knz** [comment]
thanks.

bors r=dhartunian

@thtruo I take this will need to be backported to 21.1?

**Comment by thtruo** [comment]
> I take this will need to be backported to 21.1?

@knz yes please!

**Pull request merged**
