### PR TITLE
build,cloud: Bump Kubernetes/RHEL Docker image to 1.1.0

### PR DESCRIPTION
**Pull request by lgo**
#19214

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
Published: https://access.redhat.com/containers/#/registry.connect.redhat.com/cockroachdb/cockroach

**Comment by a-robinson** [comment]
Is there a reason that you closed this instead of merging it? We do typically want to persist these updates to the repo.

**Comment by lego** [comment]
o.O

Ah, I went to rebase because the base was failing due to links changing post-release and seem to have reset it instead. My bad!

**Comment by a-robinson** [comment]
Would you mind pulling in the flag changes from #18485 while you're at it? Either that or I'll merge that one after this, but we need to start specifying the `--cache` and `--max-sql-memory` flags to avoid limiting our memory usage too much.

**Comment by lego** [comment]
Pulled them in! Will merge when build passes.

**Comment by lego** [comment]
🤔 should this also be cherry-picked to 1.1? I don't know how these configs are typically used or referenced, but I reckon if anyone looks at the 1.1 branch it would be nice to see these versions.

**Comment by a-robinson** [comment]
Yeah, that would be reasonable, for the Kubernetes configs at least.

**Pull request merged**
