### PR TITLE
geo/geoproj: initial framework to import the PROJ library

### PR DESCRIPTION
**Pull request by otan**
This commit introduces PROJ v4.9.3 to CockroachDB's compilation. We
cannot use a later version as we would like to exclude installing
sqlite3 as a pre-requisite for now.

To get this to work, `bin/execgen` must depend on the `LIBPROJ` target
to compile, and removed the c-deps ban on `pkg/geo/geoproj`.

Added some stub functions (non-finalized) that test whether
functionality works as expected.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
alright, ready for review :D

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Looks good -- but I don't have a good understanding of our build, and I'm assuming Peter will give it that part a more careful look. 

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-:-M8LIV1e6xYiK4Eo5j_z:b-eng213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @petermattis)

___
*[pkg/geo/geoproj/geoproj.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8LHDKd3NUwTN3Y6aK8:-M8LHDKd3NUwTN3Y6aK9:blgstm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L27)):*
> ```Go
> // ProjPJ is the projPJ wrapper around the PROJ library's projPJ object.
> type ProjPJ struct {
> 	projPJ C.projPJ
> ```

does `projPJ` not need to be in the `proj.h` header file to be used here?
I am confused why `proj.cc` is doing `#include <proj_api.h>` instead of that being in `proj.h`.
___
*[pkg/geo/geoproj/geoproj.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8LIBrW6iUowk8EVHR3:-M8LIBrXAxbbwMm1SeRS:b-mkviv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L37)):*
> ```Go
> 
> // NewProjPJFromText initializes a ProjPJ from text.
> // TODO(otan): thread through thread contexts and retrieve error messages.
> ```

the error message when `C.pj_init_plus(str)` returns nil?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49560)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[pkg/geo/geoproj/geoproj.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8LHDKd3NUwTN3Y6aK8:-M8LRiryAOwSATujcRdo:b-3phcxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L27)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does `projPJ` not need to be in the `proj.h` header file to be used here?
I am confused why `proj.cc` is doing `#include <proj_api.h>` instead of that being in `proj.h`.
</blockquote></details>

this is all stubbed out for now to make sure things compile as expected. the <proj_api.h> will probably go away in a follow up PR.
___
*[pkg/geo/geoproj/geoproj.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8LIBrW6iUowk8EVHR3:-M8LRc2B3o6m8cfHM_WI:b-n7pmhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L37)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the error message when `C.pj_init_plus(str)` returns nil?
</blockquote></details>

yeah - we should be able to get that from creating a proj context. I haven't done the fancy work required for that yet.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-:-M8REpDu7RwzXMMuN0K_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

**Comment by otan** [comment]
@petermattis do you want to sanity check this before it goes in?

**Review by petermattis — APPROVED** [review]
> @petermattis do you want to sanity check this before it goes in?

:lgtm: just a few small questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-:-M8SjuzkB5szxI2VanSD:b-2obdbb)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[Makefile, line 1547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8SiYZABMJR3xZ9TaKL:-M8SiYZABMJR3xZ9TaKM:b-i0w8xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/Makefile#L1547)):*
> ```Makefile
> 	@mv -f $@.tmp $@
> 
> bin/execgen: $(LIBPROJ) $(CGO_FLAGS_FILES)
> ```

This is a surprising dependency. Where is it coming from?
___
*[pkg/geo/geoproj/geoproj.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8Sinnu3k-bjj1fIivn:-M8Sinnu3k-bjj1fIivo:b-clxcxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L25)):*
> ```Go
> import "unsafe"
> 
> // ProjPJ is the projPJ wrapper around the PROJ library's projPJ object.
> ```

What does the `PJ` suffix refer to?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49560)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[Makefile, line 1547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8SiYZABMJR3xZ9TaKL:-M8SkoO8DDc-JtfomywH:b-5rsv6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/Makefile#L1547)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is a surprising dependency. Where is it coming from?
</blockquote></details>

execgen imports tree imports imports geo imports geoproj (which is needed unless we wanted to get into fancy injection territory)
___
*[pkg/geo/geoproj/geoproj.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49560#-M8Sinnu3k-bjj1fIivn:-M8SkxDhEp5l84woGe1L:bdi11z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/14781baed48ee877d443fd65b11e34e122ceac0d/pkg/geo/geoproj/geoproj.go#L25)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What does the `PJ` suffix refer to?
</blockquote></details>

`PJ` seems to be the internal name for a PROJ object.

(unless you're asking what it stands for... projection? Peanut butter & Jelly?)

**Comment by otan** [comment]
bors r=petermattis,sumeerbhola

**Pull request merged**
