### PR TITLE
distsql: support UNION ALL operation

### PR DESCRIPTION
**Pull request by solongordon**
The distsql physical planner now supports UNION ALL, which simply merges
together the two streams. Normal UNION still to come, as well as
INTERSECT and EXCEPT.

Refers #10432

Release note (performance improvement): Support distributed execution of
UNION ALL queries.

### CODE REVIEW

**Comment by solongordon** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 752 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MIKCum3dE6LGCGtgA:-L0MIKCum3dE6LGCGtgB:bbzrec4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsqlplan/physical_plan.go#L752)):*
> ```Go
> // MergeResultTypes reconciles the ResultTypes between two plans. It enforces that each pair of
> // ColumnTypes must either match or be null, in which case the non-null type is used.
> func MergeResultTypes(left, right []sqlbase.ColumnType) ([]sqlbase.ColumnType, error) {
> ```

This could use a unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742)*

**Comment by RaduBerinde** [comment]
Thanks for working on this! Looks good overall.

Please add some logictests in one of the `distsql_` files (or make a new one), and include some testcases with plan URLs. I would make one of them be something like `select a,bc from abc union all select a,bc from cba` (with tables abc `(a INT PRIMARY KEY, b INT, c INT)`and cba `(c INT PRIMARY KEY, b INT, a INT)`) to verify that the projections are right.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1940 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0Ms1nqK2ql28dewRxr:-L0Ms1nqK2ql28dewRxs:bnbph4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1940)):*
> ```Go
> }
> 
> func (dsp *DistSQLPlanner) createPlanForUnion(
> ```

ForUnionAll

---

*[pkg/sql/distsql_physical_planner.go, line 1963 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MmUMJ6oYPnmJ93WUh:-L0MmUMJ6oYPnmJ93WUi:b-8azsl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1963)):*
> ```Go
> 	p.ResultTypes = resultTypes
> 
> 	// TODO(solon): Is this a reasonable expectation?
> ```

Yes, I think it should be (with the mapping caveat below). The `simplifyOrderings` pass only retains the parts of the orderings that are actually useful, and any difference between left and right is not useful.

---

*[pkg/sql/distsql_physical_planner.go, line 1970 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MntYeAWUR-aBrVtG5:-L0MntYeAWUR-aBrVtG6:bh28qqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1970)):*
> ```Go
> 	p.MergeOrdering = leftPlan.MergeOrdering
> 
> 	if !reflect.DeepEqual(leftPlan.planToStreamColMap, rightPlan.planToStreamColMap) {
> ```

We should check this first (because MergePlans, MergeResultTypes are bogus when the mappings don't match).  In general, we can't really assume the mappings match but I spent some time thinking of cases where this would happen with UNION and I couldn't find one.
I would also add a `TODO` before the return saying "if there are cases where this is not true, we could use AddProjection to "align"

---

*[pkg/sql/distsqlplan/physical_plan.go, line 751 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MmyXgBLrUif_ME9SC:-L0MmyXgBLrUif_ME9SD:b743685) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsqlplan/physical_plan.go#L751)):*
> ```Go
> 
> // MergeResultTypes reconciles the ResultTypes between two plans. It enforces that each pair of
> // ColumnTypes must either match or be null, in which case the non-null type is used.
> ```

Mention that this is used for cases like `(SELECT NULL) UNION (SELECT 1)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-:-L0MrPQ5CKGlsWRJ5sa2:b-m4ckjj)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1970 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MntYeAWUR-aBrVtG5:-L0MuTqmrkj3okNC6msZ:b-vn9pdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1970)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should check this first (because MergePlans, MergeResultTypes are bogus when the mappings don't match).  In general, we can't really assume the mappings match but I spent some time thinking of cases where this would happen with UNION and I couldn't find one.
I would also add a `TODO` before the return saying "if there are cases where this is not true, we could use AddProjection to "align"
</blockquote></details>

Actually, maybe something like this:

```
create table abc (a INT, b INT, c INT, PRIMARY KEY(a, b, c));
create table cba (c INT, b INT, a INT, PRIMARY KEY(c, b, a));
(select c from abc order by a) union all (select a from cba order by c, b);
```
I believe that the left side will have two columns (because results from multiple nodes need to be merged while maintaining ordering on `a`) and the right side will have three columns (because of `c, b`).

I think to support this odd case we can do `AddSingleGroupStage` (with a no-op processor) on each side to merge the results, then apply the necessary projections (`AddProjection`). We can also fall back to this if the `MergeOrdering`s don't match.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742)*

**Comment by solongordon** [comment]
I'd like to brainstorm some more logic test cases for `distsql_union`, but otherwise this should be ready for a second look.

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 1940 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0Ms1nqK2ql28dewRxr:-L0pvyZXFJnt2RCmbE2V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1940)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ForUnionAll
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 1970 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MntYeAWUR-aBrVtG5:-L0pw-4j5KDhcNjG73bo:b-wu5oim) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1970)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Actually, maybe something like this:

```
create table abc (a INT, b INT, c INT, PRIMARY KEY(a, b, c));
create table cba (c INT, b INT, a INT, PRIMARY KEY(c, b, a));
(select c from abc order by a) union all (select a from cba order by c, b);
```
I believe that the left side will have two columns (because results from multiple nodes need to be merged while maintaining ordering on `a`) and the right side will have three columns (because of `c, b`).

I think to support this odd case we can do `AddSingleGroupStage` (with a no-op processor) on each side to merge the results, then apply the necessary projections (`AddProjection`). We can also fall back to this if the `MergeOrdering`s don't match.
</blockquote></details>

Good call. I'm handling this now by calling `AddSingleGroupStage` and `AddProjection` if the result types or merge orderings aren't compatible. Another fun case that was broken was when the number of sort columns matched but they had different `ResultType`s.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 751 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MmyXgBLrUif_ME9SC:-L0pwBAdv4wXG9RpyKIf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsqlplan/physical_plan.go#L751)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention that this is used for cases like `(SELECT NULL) UNION (SELECT 1)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-:-L0py6AtC6PnL_-Kzx9q:b-y84t8w)*

**Comment by RaduBerinde** [comment]
:lgtm:

I like the tests (and the plans look good)!

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1970 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0MntYeAWUR-aBrVtG5:-L0ud5Mgg8JsBBo1FVr4:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4fb8436b1e04336842fd59b255f171c4b678060/pkg/sql/distsql_physical_planner.go#L1970)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Good call. I'm handling this now by calling `AddSingleGroupStage` and `AddProjection` if the result types or merge orderings aren't compatible. Another fun case that was broken was when the number of sort columns matched but they had different `ResultType`s.
</blockquote></details>

:thumbsup: 

---

*[pkg/sql/distsql_physical_planner.go, line 1936 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0ucWUCchmjbdFnmSkv:-L0ucWUCchmjbdFnmSkw:b-c87319) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2a5c7bc3945bb001123d6c3702e07856f70ead/pkg/sql/distsql_physical_planner.go#L1936)):*
> ```Go
> 
> 	// Merge the plans' planToStreamColMap, which should be equivalent.
> 	// TODO(solon): Are there any valid UNION ALL cases where these differ?
> ```

I'm not 100% sure but I can't think of one.. Mention in the comment that we could handle this case just like the one below (in case someone runs into it).

I would add a test along the lines of `SELECT x, y FROM xyz UNION ALL SELECT y, x FROM xyz`

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0udMsZU0Aq3988lKiR:-L0udMsZU0Aq3988lKiS:b-uxan5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2a5c7bc3945bb001123d6c3702e07856f70ead/pkg/sql/logictest/testdata/logic_test/distsql_union#L41)):*
> ```
> # Simple UNION ALL
> query I
> SELECT x FROM xyz UNION ALL SELECT x FROM xyz ORDER BY x
> ```

can you mention in the comment that `ORDER BY x` refers to the entire query 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-:-L0uecbq9DSfGYZrGvwR:b-9kwvwx)*

**Comment by solongordon** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1936 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0ucWUCchmjbdFnmSkv:-L1rXG9xLB03BZeVBqF5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2a5c7bc3945bb001123d6c3702e07856f70ead/pkg/sql/distsql_physical_planner.go#L1936)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not 100% sure but I can't think of one.. Mention in the comment that we could handle this case just like the one below (in case someone runs into it).

I would add a test along the lines of `SELECT x, y FROM xyz UNION ALL SELECT y, x FROM xyz`
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-L0udMsZU0Aq3988lKiR:-L1rXOLulGgcS4G1aaxm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2a5c7bc3945bb001123d6c3702e07856f70ead/pkg/sql/logictest/testdata/logic_test/distsql_union#L41)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

can you mention in the comment that `ORDER BY x` refers to the entire query 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742)*

**Comment by arjunravinarayan** [comment]
:lgtm: :shipit: 

---

Reviewed 3 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20742#-:-L1sBBG9XAjyCEkFceG7:byzm7aw)*

**Pull request merged**
