### PR TITLE
storage: document replica descriptor cache

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7683)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IRsgwayCpJnDCy_V:-KM6IRshqVMZEvgj2dlU:-2082838007) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L344)):*
> ```Go
> 		// ReplicaDescriptor. Normally, a replica knows about the other replica
> 		// descriptors for a range via the RangeDescriptor stored in
> 		// Replica.mu.state.desc. But that descriptor is only updated during a
> ```

`s/desc/Desc/`

---

*[storage/store.go, line 348 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IXJBd9WEan-d-vZR:-KM6IXJBd9WEan-d-vZS:1988078718) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L348)):*
> When a Replica is being newly created as the result of an incoming Raft message for it.

---

*[storage/store.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IsgpKk3EDGL2Xt8y:-KM6IsgpKk3EDGL2Xt8z:1412209702) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L350)):*
> ```Go
> 		// 1. When a replica is being newly created. The leader will be sending the
> 		// replica messages and the replica needs to be able to respond before it
> 		// has received the change-replicas command.
> ```

s/has received/can receive/, right? The command is in the log it is about to catch up on.

---

*[storage/store.go, line 352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6Ihy6KE2ER2Ob7GnI:-KM6Ihy6KE2ER2Ob7GnJ:1308739315) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L352)):*
> ```Go
> 		// has received the change-replicas command.
> 		//
> 		// 2. If the node containing a replica is partitioned or down while the
> ```

Isn't this exactly 1 (after all, the node who communicates with us could be any of them when leadership changes just after the conf change)?
I don't know if it's worth pointing out here, but while the standard scenario is that we receive a snapshot, there is also (I think) the odder code path in which we're removed and re-added in quick succession, so that we have a current enough state on top of which to replay the log. In that case we would actually run the changeReplicasTrigger. I would have to look at that code path to make sure what I describe above is actually true. Which means it should be documented unless it already is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IsgpKk3EDGL2Xt8y:-KM6MmTdW5-lLHvdDOdn:1787265264) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L350)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/has received/can receive/, right? The command is in the log it is about to catch up on.
</details>
Actually likely it won't ever receive the ChangeReplicas itself. See below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 348 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IXJBd9WEan-d-vZR:-KM6QN6P-AAId68E5H-y:965542064) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L348)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> > When a Replica is being newly created as the result of an incoming Raft message for it.
</details>
Maybe also comment that this is the common case for ChangeReplicas, and an uncommon case for splits.

---

*[storage/store.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IsgpKk3EDGL2Xt8y:-KM6O3ltnpeiYhrBBMSq:-722839807) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L350)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Actually likely it won't ever receive the ChangeReplicas itself. See below.
</details>
With preemptive snapshots, the new replica will actually receive the ChangeReplicas transaction in most cases. But ChangeReplicas is not the only way that raft messages may create uninitialized replicas. It's also possible during splits (the "snapshot wins" scenario of TestSplitSnapshotRace). `s/the change-replicas command/an updated range descriptor (via a snapshot, changeReplicasTrigger, or splitTrigger/` to cover all the possibilities.

---

*[storage/store.go, line 352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6Ihy6KE2ER2Ob7GnI:-KM6QUbIxVzEwqFldiSu:-482147990) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L352)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Isn't this exactly 1 (after all, the node who communicates with us could be any of them when leadership changes just after the conf change)?
> I don't know if it's worth pointing out here, but while the standard scenario is that we receive a snapshot, there is also (I think) the odder code path in which we're removed and re-added in quick succession, so that we have a current enough state on top of which to replay the log. In that case we would actually run the changeReplicasTrigger. I would have to look at that code path to make sure what I describe above is actually true. Which means it should be documented unless it already is.
</details>
It's not exactly 1 (at least as I interpret them). Case 1 is when there is *no* range descriptor; case 2 is when there is a descriptor that is out of date. 

---

*[storage/store.go, line 362 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6RWhzYslG0tUFsFG3:-KM6RWhzYslG0tUFsFG4:565754199) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L362)):*
> ```Go
> 		// for a replica (see Replica.sendRaftMessage).
> 		//
> 		// TODO(peter): It might be preferrable to move this cache to Replica and
> ```

While you're commenting this, mention that the current store-level cache is a historical artifact from the `multiraft` package.

---

*[storage/store.go, line 364 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6QlwIB8hbrV9DlDZ_:-KM6QlwIB8hbrV9DlDZa:253577977) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L364)):*
> ```Go
> 		// TODO(peter): It might be preferrable to move this cache to Replica and
> 		// change it to a map keyed by replicaID. The question then becomes
> 		// how/when to expire old entries from the cache. Presumably we could hook
> ```

If we move the cache to Replica, it could be very small (probably a single entry). We only need to be able to respond to the last node that talked to us. 

---

*[storage/store.go, line 367 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6RB1ua2fvS69xvZJ-:-KM6RB1ua2fvS69xvZJ0:-1339590449) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L367)):*
> ```Go
> 		// into Replica.setDesc to notice when a replicaID has been removed. There
> 		// is a potential downside to this move: removing a replica from
> 		// Store.mu.replicas will remove cached replica descriptor information.
> ```

That should be fine. When a replica is completely removed, it won't be recreated until there is another event that will repopulate the cache. When it is temporarily dropped and recreated, the newly recreated replica will have a complete range descriptor so it won't need to rely on this cache.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-:-KM6RddMwRejkPKb-GVQ:676834233)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 344 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IRsgwayCpJnDCy_V:-KM6wDlQzESTY28ucx4N:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L344)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> `s/desc/Desc/`
</details>
Done.

---

*[storage/store.go, line 348 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IXJBd9WEan-d-vZR:-KM6wRrtDK32GIfKUURw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L348)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Maybe also comment that this is the common case for ChangeReplicas, and an uncommon case for splits.
</details>
Done.

---

*[storage/store.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6IsgpKk3EDGL2Xt8y:-KM6wwaG7obTiFOn5eSP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L350)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> With preemptive snapshots, the new replica will actually receive the ChangeReplicas transaction in most cases. But ChangeReplicas is not the only way that raft messages may create uninitialized replicas. It's also possible during splits (the "snapshot wins" scenario of TestSplitSnapshotRace). `s/the change-replicas command/an updated range descriptor (via a snapshot, changeReplicasTrigger, or splitTrigger/` to cover all the possibilities.
</details>
Done.

---

*[storage/store.go, line 352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6Ihy6KE2ER2Ob7GnI:-KM6x6xEcpSN91ntIgY8:-883165263) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L352)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's not exactly 1 (at least as I interpret them). Case 1 is when there is *no* range descriptor; case 2 is when there is a descriptor that is out of date. 
</details>
Clarified.

@bdarnell Can you comment on the removed-and-quickly-re-added scenario?

---

*[storage/store.go, line 362 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6RWhzYslG0tUFsFG3:-KM6xIQzs7gjhe1JPX8M:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L362)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> While you're commenting this, mention that the current store-level cache is a historical artifact from the `multiraft` package.
</details>
Done.

---

*[storage/store.go, line 364 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6QlwIB8hbrV9DlDZ_:-KM6xTgPIHQOxRJPkomi:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L364)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> If we move the cache to Replica, it could be very small (probably a single entry). We only need to be able to respond to the last node that talked to us. 
</details>
Done.

---

*[storage/store.go, line 367 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6RB1ua2fvS69xvZJ-:-KM6xcPFWESGTBxc3aCZ:-265769321) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L367)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> That should be fine. When a replica is completely removed, it won't be recreated until there is another event that will repopulate the cache. When it is temporarily dropped and recreated, the newly recreated replica will have a complete range descriptor so it won't need to rely on this cache.
</details>
Added your comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6Ihy6KE2ER2Ob7GnI:-KM7Ckr3-xAJsWv00n1Z:1786869939) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L352)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Clarified.
> 
> @bdarnell Can you comment on the removed-and-quickly-re-added scenario?
</details>
Yes, removing and re-adding a replica (fast enough that replicaGCQueue cannot run) would be another way that case 2 could happen. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-KM6Ihy6KE2ER2Ob7GnI:-KM9SYzAV8hiQZrTLijH:-1281673814) ([raw file](https://github.com/cockroachdb/cockroach/blob/1851b21384e46a64b252e7404d9cbcc844bf46cf/storage/store.go#L352)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Yes, removing and re-adding a replica (fast enough that replicaGCQueue cannot run) would be another way that case 2 could happen. 
</details>
Added commentary about that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7683#-:-KM9VSfDyB22Q054ntc1:1417088721)*

**Pull request merged**
