### PR TITLE
RFC: streaming snapshots

### PR DESCRIPTION
**Pull request by bdarnell**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8151)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

@tschottdorf may have ideas about what could go wrong, but I can't think of anything; at least for phase 1. It also seems that phase 1 will get us most of the way towards addressing our current problems related to snapshots.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/streaming_snapshots.md, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-CSvKgI7qOMXbakh:-KNy-CSvKgI7qOMXbaki:122253964) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L83)):*
> ```Markdown
>   optional Status status = 1 [(gogoproto.nullable) = false];
>   optional string message = 2 [(gogoproto.nullable) = false];
>   optional bool final = 3 [(gogoproto.nullable) = false]
> ```

i think this was meant to be in the request rather than the response.

---

*[docs/RFCS/streaming_snapshots.md, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-QEjy4OGQ9IRpvuV:-KNy-QEjy4OGQ9IRpvuW:-1723927370) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L124)):*
> ```Markdown
> (along with the metadata required by raft). The UUID and RocksDB
> snapshot are saved in attributes of the `Replica`. In
> `sendRaftMessage`, we inspect and all outgoing `MsgSnap` messages. If
> ```

s/and//

---

*[docs/RFCS/streaming_snapshots.md, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-cdO0aln7nqk8wZD:-KNy-cdO0aln7nqk8wZE:2073985575) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L128)):*
> ```Markdown
> shouldn't happen). If it matches, we begin to send SnapshotRequests as
> described above; the `MsgSnap` is held to be sent in the snapshot's
> `Footer`.
> ```

s/footer/raft_message/? there's no footer in the protos.

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KNy0GQFhlTD7zPKq-dS:658619671) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
> ```Markdown
> # Unresolved questions
> 
> - Can this replace the reservation system, or do we need both?
> ```

Indeed, seems like they should be integrated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-:-KNy0N5N9b2PfJsoZ1Bj:-652412437)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/streaming_snapshots.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyMuAYfl69oKy19UIw:-KNyMuAYfl69oKy19UIx:585590201) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L43)):*
> ```Markdown
> These changes will be implemented in two phases. In the first phase,
> we introduce the new network protocol and use it to ensure that both
> senders and receivers can limit the number of snapshots they are
> ```

Can you expand on how the senders and receivers might limit the number of concurrent snapshots? This RFC is currently all about mechanism and not about policy. Even a brief note in unresolved questions would be good.

---

*[docs/RFCS/streaming_snapshots.md, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyKed1B6KWTSDKMNMV:-KNyKed1B6KWTSDKMNMW:-339114016) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L69)):*
> ```Markdown
> 
>   repeated KeyValue KV = 2 [(gogoproto.nullable) = false,
>       (gogoproto.customname) = "KV"];
> ```

We just write these `KVs` directly to RocksDB, right? Since we're introducing a new snapshot protocol, I wonder if we should take the opportunity to send the snapshot as an `engine.Batch.Repr()`. This is exactly the same data, but it would only be a single `bytes` field and would be quicker to write on the receiving end. Win win?

---

*[docs/RFCS/streaming_snapshots.md, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyLa8alND-grvushdt:-KNyLa8alND-grvushdu:668437616) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L142)):*
> ```Markdown
> raft, and if `raft.Ready` returns a snapshot to be applied with the
> given UUID (this is not guaranteed), the buffered snapshot will be
> applied.
> ```

It isn't spelled out here, but we should accumulate the snapshot into an `engine.Batch`. This will move the memory out of Go and into C, which we'll need to do anyways in order to process the `KVs` and raft log entries. 

---

*[docs/RFCS/streaming_snapshots.md, line 162 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyM6m2IKqKa5KtXZVl:-KNyM6m2IKqKa5KtXZVm:-2084857996) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L162)):*
> ```Markdown
> so we can't do anything else until we apply a snapshot. If the stream
> is closed without sending the final snapshot packet, we must mark the
> replica as corrupt.
> ```

Agreed that this is tricky. I expect we'll hold off on Phase 2 for quite a while.

---

*[docs/RFCS/streaming_snapshots.md, line 176 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyNA788FGhFMUiqnHm:-KNyNA788FGhFMUiqnHn:-23872324) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L176)):*
> ```Markdown
>   on the sender side.
> 
> # Unresolved questions
> ```

Will this new system be used for preemptive snapshots? Are there any issues with doing so?

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KNyNIjF5hyZ4_pxzQKJ:-1122386102) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Indeed, seems like they should be integrated.
</details>
The reservation system throttles allocation of ranges to a given node. This proposal will allow us to throttle snapshots for replicas already on a node. Similar, but slightly different. Might be possible to integrate the two, but I would be hesitant to try and doing so in the initial implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/streaming_snapshots.md, line 43 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyMuAYfl69oKy19UIw:-KO2abpSRkjCRsygRCHt:-1372740410) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L43)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Can you expand on how the senders and receivers might limit the number of concurrent snapshots? This RFC is currently all about mechanism and not about policy. Even a brief note in unresolved questions would be good.
</details>
I was thinking it would either integrate with the reservation system or use a separate store-wide counter/semaphore for the incoming snapshots.

---

*[docs/RFCS/streaming_snapshots.md, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyKed1B6KWTSDKMNMV:-KO2b4JtgwU_8ReYC_WZ:-903691467) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> We just write these `KVs` directly to RocksDB, right? Since we're introducing a new snapshot protocol, I wonder if we should take the opportunity to send the snapshot as an `engine.Batch.Repr()`. This is exactly the same data, but it would only be a single `bytes` field and would be quicker to write on the receiving end. Win win?
</details>
Good idea.  The one tricky thing is that I think phase two may need to care about the difference between regular data and log entries (We may need to require that all log entries are sent in one batch)

---

*[docs/RFCS/streaming_snapshots.md, line 83 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-CSvKgI7qOMXbakh:-KO2blCtv8BczgRSEs69:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L83)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think this was meant to be in the request rather than the response.
</details>
Done.

---

*[docs/RFCS/streaming_snapshots.md, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-QEjy4OGQ9IRpvuV:-KO2bpCAltjS0OcDUyh6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/and//
</details>
Done.

---

*[docs/RFCS/streaming_snapshots.md, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-cdO0aln7nqk8wZD:-KO2bpcuMNHB30cmXL69:292352334) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L128)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/footer/raft_message/? there's no footer in the protos.
</details>
s/footer/header/. There used to be a footer before I had worked out that phase 2 would need the MsgSnap first. 

---

*[docs/RFCS/streaming_snapshots.md, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyLa8alND-grvushdt:-KO2egB7UXNnpqEFQUlm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L142)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> It isn't spelled out here, but we should accumulate the snapshot into an `engine.Batch`. This will move the memory out of Go and into C, which we'll need to do anyways in order to process the `KVs` and raft log entries. 
</details>
Done.

---

*[docs/RFCS/streaming_snapshots.md, line 176 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyNA788FGhFMUiqnHm:-KO2c3LJGZobSNz3DPTi:1211119553) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L176)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Will this new system be used for preemptive snapshots? Are there any issues with doing so?
</details>
Yes, it will be used for preemptive snapshots, and will make them synchronous (if we haven't already solved that in another way by then). I don't see any issues with doing so in phase 1, but it's something we'll have to consider in phase 2. 

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KO2cEQGelo_ROyW1NQe:995232620) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The reservation system throttles allocation of ranges to a given node. This proposal will allow us to throttle snapshots for replicas already on a node. Similar, but slightly different. Might be possible to integrate the two, but I would be hesitant to try and doing so in the initial implementation.
</details>
For preemptive snapshots, they're effectively the same thing. The snapshot stream serves as a reservation, with the bonus that the reservation can be cancelled as soon as the stream closes instead of waiting for a timeout. It's true that this mechanism does a little more by controlling snapshots to replicas that are already present, but once we resolve our current issues with preemptive snapshots those should be quite rare. I lean towards integrating/replacing the reservation system with streaming snapshots.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/streaming_snapshots.md, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-cdO0aln7nqk8wZD:-KO2fXXCk1Jo93KcV4x3:766498083) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L128)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/footer/header/. There used to be a footer before I had worked out that phase 2 would need the MsgSnap first. 
</details>
Is the intention that only the first message in the outbound stream will have a non-empty header?

---

*[docs/RFCS/streaming_snapshots.md, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2g3DZB2WcKT3BOEJR:-KO2g3DZB2WcKT3BOEJS:832524130) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L56)):*
> ```Markdown
>   message Header {
>     optional roachpb.RangeDescriptor range_descriptor = 1 [(gogoproto.nullable) = false)];
>     optional int64 range_size = 2 [(gogoproto.nullable) = false];
> ```

what's this used for?

---

*[docs/RFCS/streaming_snapshots.md, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2gc_YKFJTjSJcijM9:-KO2gc_ZTsepnnnTaWIn:-1568601099) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L139)):*
> ```Markdown
> 
> The recipient will accumulate all `SnapshotRequests` in memory, into a
> rocksdb `Batch`, keyed by the UUID from the header. It sends the
> ```

there's no reason for this to be the same uuid as was generated on the sender, correct? perhaps spell out that it might be convenient for tracking snapshots around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/streaming_snapshots.md, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNyKed1B6KWTSDKMNMV:-KO4rbGfNx7Xsk-Fys3S:-837546354) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L69)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Good idea.  The one tricky thing is that I think phase two may need to care about the difference between regular data and log entries (We may need to require that all log entries are sent in one batch)
</details>
Yeah, I was thinking the batch would only be used for `KV` data and that we'd keep the `log_entries` for the raft log so that we can still use `Replica.append` to apply them. 

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KO4qzh4rQrJ0UZaJcc8:-655841245) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> For preemptive snapshots, they're effectively the same thing. The snapshot stream serves as a reservation, with the bonus that the reservation can be cancelled as soon as the stream closes instead of waiting for a timeout. It's true that this mechanism does a little more by controlling snapshots to replicas that are already present, but once we resolve our current issues with preemptive snapshots those should be quite rare. I lean towards integrating/replacing the reservation system with streaming snapshots.
</details>
The current reservation system doesn't block the replicate queue. That is, when a reservation fails because the target node has too many outstanding, the replicate queue can proceed with other work. To achieve the same effect, I suppose we can make preemptive snapshots fail if the target doesn't want to accept the snapshot for some reason. That would some indication in the `SnapshotRequest` that the snapshot is preemptive because we can't deny Raft snapshots the same way. 

---

*[docs/RFCS/streaming_snapshots.md, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2gc_YKFJTjSJcijM9:-KO4qWWoRx810lTkQ4C_:-748119267) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's no reason for this to be the same uuid as was generated on the sender, correct? perhaps spell out that it might be convenient for tracking snapshots around.
</details>
The `Batch` itself doesn't need to be keyed (because all of the `SnapshotRequests` are arriving via a grpc stream into a single goroutine), but I think we'll want some tracking of the inflight snapshots being streamed into a node and it makes sense to perform that tracking keyed by the UUID in the request. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-:-KO4sA2sGrBymHiDEQew:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KO5_dYjFfg4DahnCAJz:-81785832) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
>  To achieve the same effect, I suppose we can make preemptive snapshots fail if the target doesn't want to accept the snapshot for some reason.

Perhaps `SnapshotResponse.Status` should include a 4th variant `DECLINED`.

---

*[docs/RFCS/streaming_snapshots.md, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2gc_YKFJTjSJcijM9:-KO5_QRP8yQlgvjalHsL:882961063) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L139)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The `Batch` itself doesn't need to be keyed (because all of the `SnapshotRequests` are arriving via a grpc stream into a single goroutine), but I think we'll want some tracking of the inflight snapshots being streamed into a node and it makes sense to perform that tracking keyed by the UUID in the request. 
</details>
Sure. What I was really getting at is that there's no strict need to send the UUID in the request at all, so we should call out that we're doing it so that we can track snapshots around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/RFCS/streaming_snapshots.md, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy-cdO0aln7nqk8wZD:-KO6WLIz_lSbxE0TnBbE:-736215280) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L128)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Is the intention that only the first message in the outbound stream will have a non-empty header?
</details>
Yes. The first message has a header and nothing else; no other message has a header.

---

*[docs/RFCS/streaming_snapshots.md, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KNy0vro3e5f7XK-cQNH:-KO6YGHfV83dJJcUHGnC:-1975309278) ([raw file](https://github.com/cockroachdb/cockroach/blob/40bb137ce99551257e6b0442d6cde9e097936715/docs/RFCS/streaming_snapshots.md#L178)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> >  To achieve the same effect, I suppose we can make preemptive snapshots fail if the target doesn't want to accept the snapshot for some reason.
> 
> Perhaps `SnapshotResponse.Status` should include a 4th variant `DECLINED`.
</details>
Good point. Added a `DECLINED` state and a `can_decline` field to the header. I wonder if it should always decline when busy or if it might be better to wait for a slot to free up. 

---

*[docs/RFCS/streaming_snapshots.md, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2g3DZB2WcKT3BOEJR:-KO6WCqSltA48IuDXkyG:1476250288) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's this used for?
</details>
It'll be used by the reservation system assuming we make that integration. 

---

*[docs/RFCS/streaming_snapshots.md, line 139 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2gc_YKFJTjSJcijM9:-KO6_LH6S1_JvZMjobQM:-15086103) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Sure. What I was really getting at is that there's no strict need to send the UUID in the request at all, so we should call out that we're doing it so that we can track snapshots around.
</details>
It does need to be the same UUID on both sides - we need to match the  UUID in the `Snapshot.Data` that comes out of `raft.Ready` with the snapshot we received. Now that the `raftpb.Message` is present in the header instead of the footer, we could get rid of the separate `snapshot_id` field (it's easier to access here but probably better to only store this in one place).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/streaming_snapshots.md, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2g3DZB2WcKT3BOEJR:-KO6iRnZa26LDytlTE2T:-816394298) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It'll be used by the reservation system assuming we make that integration. 
</details>
Got it. Can you add that to the RFC, or is it already in here and I missed it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/streaming_snapshots.md, line 59 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KOC3fZdVte2N85jdBGb:-KOC3fZdVte2N85jdBGc:1805848886) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d519de154fcd805af8da338fa04a5c39712373/docs/RFCS/streaming_snapshots.md#L59)):*
> ```Markdown
> 
>     // A raft message of type MsgSnap. The raft snapshot data contains a UUID.
>     optional raftpb.Message raft_message = 4;
> ```

Should this and can_decline get their field ids decremented since we removed snapshot_id? As long as we haven't written the old version down anywhere we should be safe to keep the field ids compact to start.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/streaming_snapshots.md, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KO2g3DZB2WcKT3BOEJR:-KOGS1qg5B1k8sQek1sX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b65c08ef9e34027935e1cc0cbb0d6079f197fa5/docs/RFCS/streaming_snapshots.md#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Got it. Can you add that to the RFC, or is it already in here and I missed it?
</details>
Done.

---

*[docs/RFCS/streaming_snapshots.md, line 59 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151#-KOC3fZdVte2N85jdBGb:-KOGS2Mfh2732yyQIQ4A:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d519de154fcd805af8da338fa04a5c39712373/docs/RFCS/streaming_snapshots.md#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Should this and can_decline get their field ids decremented since we removed snapshot_id? As long as we haven't written the old version down anywhere we should be safe to keep the field ids compact to start.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8151)*

**Pull request merged**
