### PR TITLE
sql: check if CCL required before index truncation

### PR DESCRIPTION
**Pull request by eriktrinh**
This change performs an early check for if a CCL is required to modify
the zone config for a dropped index's table. If a license was previously
required, an error occurs would when attempting to remove the dropped index's
zone config after the data has been removed, triggering a roll back.

Release note (sql change): Removing index zone configs with
`removeIndexZoneConfigs` ignores returned CCL required errors. This does
not affect removing zone configs with `ALTER INDEX ... CONFIGURE ZONE DISCARD`.

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
I see removeIndexZoneConfigs() catching the CCL error and returning another error. Where is the original CCL error being returned from? I'd change removeIndexZoneConfigs() to fail gracefully and not return an error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNmTaTa1fQVG8IDiZdw:bm0hhr7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_index.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-LNmQuYy-N6E2VBSfSpP:-LNmQuYy-N6E2VBSfSpQ:bqyc8ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1f9c8787ebf4d4b0c6059072cc1db95bdaf10a/pkg/sql/drop_index.go#L127)):*
> ```Go
> 	if len(zone.Subzones) > 0 {
> 		st := p.ExecCfg().Settings
> 		if !st.Version.IsMinSupported(cluster.VersionPartitioning) {
> ```

version paritioning is the 2.0 version and this change is going into 2.2 so we don't need to run this check any more. Remove it!

**Review by eriktrinh — COMMENTED** [review]
The CCL error is returned in `GenerateSubzoneSpans`if there are remaining subzones to the table zone config after removing the index subzones. I'd rather not change `removeIndexZoneConfigs` and instead ignore the returned error when we want to.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNpGXTF90nFMXqmX8Uc:bqorint)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_index.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-LNmQuYy-N6E2VBSfSpP:-LNpGWTq9LYkGjj99Zcv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f1f9c8787ebf4d4b0c6059072cc1db95bdaf10a/pkg/sql/drop_index.go#L127)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

version paritioning is the 2.0 version and this change is going into 2.2 so we don't need to run this check any more. Remove it!
</blockquote></details>

Done.

**Review by vivekmenezes — COMMENTED** [review]
Thanks for making this update.

I still don't know where the CCl error is being returned in the current code. I'd originally thought: from removeIndexZoneConfigs()  but that doesn't seem to be the case.

The reason I ask is because it's not clear whether your change is indeed being tested because we still have another place in the code where the error is being returned. I'd like to hopefully see that removed so we know your change is being tested by existing tests.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNpO6B12fPsSnPJGfzW:b-endwh8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by eriktrinh — COMMENTED** [review]
`removeIndexZoneConfigs` will write the updated zone config for the table after removing the index subzones from it.  If the new table zone config still has remaining subzones, this will require the CCL to write them and the error is returned when it tries to generate spans for the remaining subzones (which is caught back in `removeIndexZoneConfigs` and a new error of the same type is returned).

The current test already checks that the index still exists, and one way we can know that this change is effective is if the DROP INDEX job was not created.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNpRCxx1AUivqfSP-us:b-1jql3n)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — COMMENTED** [review]
if sqlbase.IsCCLRequiredError(err) {
		return sqlbase.NewCCLRequiredError(fmt.Errorf("schema change requires a CCL binary "+
			"because table %q has at least one remaining index or partition with a zone config",
			tableDesc.Name))
	}

I'm seeing TestDropIndexWithZoneConfigOSS not test for this error

We should talk in person if you're confused. Sorry if I'm confused. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNpck63AFNgCo8qkbyz:bwaz3lk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by eriktrinh — COMMENTED** [review]
Done as discussed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNpjEkTC-JSJBEPsaiI:b-73fv7j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30849#-:-LNplpol3PvaJ1tf8Swy:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
I think there should be a release note for that change.

**Comment by eriktrinh** [comment]
> I think there should be a release note for that change.

Done.
bors r+

**Pull request merged**
