### PR TITLE
rocksdb: bump version to 4.11.2 and fix broken interface usage

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9616)

### CODE REVIEW

**Comment by petermattis** [comment]
@cuongdo Can you try reproducing #9029 using this commit? It is similar to #9609 except it bumps us up to RocksDB 4.11.2.

**Comment by cuongdo** [comment]
I can't build this, because the `GLOCKFILE` in this PR refers to a `c-rocksdb` SHA (23b12c21f186) that doesn't exist for me.

**Comment by petermattis** [comment]
Oops. You need https://github.com/cockroachdb/c-rocksdb/pull/28.

**Comment by tamird** [comment]
:dog: :lgtm:

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9616#-:-KSqGZQEHuCCRE89yceV:bvma1yx)*

**Comment by cuongdo** [comment]
3 runs of the Terraform test w/ RocksDB 4.11.2 have shown no traces of #9029. Previously, 3 runs would've been ample opportunity to exhibit the panic. 👍

**Comment by petermattis** [comment]
Mind trying a few more runs? Just to be extra sure.

**Comment by cuongdo** [comment]
sure, starting them now

**Comment by cuongdo** [comment]
The additional 4 runs are free of any RocksDB issues. That brings the total to 7 panic-free runs.

**Comment by cuongdo** [comment]
Total of 15 panic-free runs. I'll stop here unless you want more runs.

**Comment by petermattis** [comment]
That's sufficient. Thanks.

**Comment by petermattis** [comment]
Looks like this is good to go (see commentary in #9029), but I'm waiting for confirmation from the RocksDB folks (see https://github.com/facebook/rocksdb/issues/1370).

**Comment by tschottdorf** [comment]
Assigning `stability` label to mark for supervised merge.

**Comment by tamird** [comment]
What's the story here? Would be nice to get this in.

**Comment by petermattis** [comment]
I'm in no rush to merge while we have other stability concerns going on. Is there any urgency I'm not aware of?

**Comment by tamird** [comment]
No, just good to not fall too far behind; if we find issues, having them be
fresh in upstream's minds is helpful.

**Comment by dt** [comment]
fwiw, to check on the glide.sh script, I rebased this one on master: https://github.com/cockroachdb/cockroach/commit/e14366b6b199f80d7c9667627e0277779cdfd894

**Comment by petermattis** [comment]
Thanks @dt. I'm going to test a custom binary of this PR on one of the test clusters tomorrow.

**Comment by petermattis** [comment]
@dt Can you tell me what the magic invocation is to update this PR?

**Comment by dt** [comment]
@petermattis for the rebase, since tamir just changed up glide.yaml quite a bit, I'd probably opt to checkout master's version, and then re-apply just the version bump to it before re-generating the lock file and vendor dir:
```
g rebase upstream/master 
g co upstream/master glide.*
perl -pi -e s/b5ca031b93fde49bfa2ba99aba423136aebf3c06/894d369c4ea259b65f75563feeb06bea322a8450/g glide.yaml
./scripts/glide.sh up
# commit and push changes to /vendor to a new branch on the vendored remote so the PR can use it.
g -C vendor checkout -b "rocks" && g -C vendor add . && g -C vendor commit -m "bump rocksdb" && g -C vendor push origin rocks
g add glide.* vendor && g rebase --continue 
```

**Comment by petermattis** [comment]
This is running on `blue` and good to go, but I have to update the PR again do to a merge conflict. Grrr.

**Comment by petermattis** [comment]
I'm going to merge this when the tests pass.

**Pull request merged**
