### PR TITLE
sql: modify tests to have deterministic results

### PR DESCRIPTION
**Pull request by yuzefovich**
When using window functions in DistSQL, if ORDER BY
clause is not specified, rows will be processed in
arbitrary order which forces order-dependent window
functions like `row_number()` to not have a consistent
output.

Also remove a few unnecessary semicolons.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
It's unfortunate that this is changing some of the queries to the point where they give different results. You can achieve the same goal using the `rowsort` directive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHcjPTz6pqekYUSgFlv:b6feazw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
I might be misunderstanding `rowsort` directive, but it seems to me that it only sorts the expected and received rows lexicographically when matching the results whereas I want to enforce a particular order in which window functions will be processing each row within their frame. For example, there are multiple valid outputs for a query `SELECT k, row_number() OVER () FROM kv ORDER BY 1` - it all depends on in which order rows are received by window processor, and I'm not sure how to specify that order other than using `ORDER BY` clause on primary key.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHcx7z71fRR9D6WSUia:b-jli5k3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I could also create a separate `distsql_window` logic tests suite where I would put modified tests from local version. @RaduBerinde what is your take on this?

**Review by RaduBerinde — COMMENTED** [review]
It would be ideal if the "regular" logic test suite can still run in `fakedist` mode.

I don't see any problem with fixing tests that can in principle have different results (and not just in terms of ordering, which is what `rowsort` is for) because of an unspecified ordering. Something like `SELECT k, row_number() OVER () FROM kv ORDER BY 1` can (according to the SQL spec) return any permutation on the second column, so it doesn't make sense to expect a certain one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHdY-n8D_o0dYHBL8RB:bc1yyb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/window, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-LHdY8YqDsVFyAYQj2CV:-LHdY8YqDsVFyAYQj2CW:babdjqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5f267eae5bd3b10866674169dd462800c0e6289/pkg/sql/logictest/testdata/logic_test/window#L367)):*
> ```
> SELECT k, concat_agg(s) OVER (PARTITION BY v ORDER BY w, k) FROM kv ORDER BY 1
> ----
> 1  ba
> ```

how come this is shorter now? I'd at most expect it to be reshuffled.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-LHdYp341TaTxcQuqSSg:-LHdYp341TaTxcQuqSSh:bgggtep) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5f267eae5bd3b10866674169dd462800c0e6289/pkg/sql/logictest/testdata/logic_test/window#L1324)):*
> ```
> SELECT k, last_value(v) OVER (ORDER BY k) FROM kv ORDER BY 1
> ----
> 1   2
> ```

How come we get different results here and below?

**Review by yuzefovich — COMMENTED** [review]
I think I agree with your point. As far as I understood, this would require modifying the logic test framework, and I don't think I have sufficient knowledge for that. Should I file a separate issue for that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHdrCfh0bdg6xZJYBNA:baskl97)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/window, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-LHdY8YqDsVFyAYQj2CV:-LHdoWL6A4QbSJE1LR-v:bc6qa6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5f267eae5bd3b10866674169dd462800c0e6289/pkg/sql/logictest/testdata/logic_test/window#L367)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

how come this is shorter now? I'd at most expect it to be reshuffled.
</blockquote></details>

It is shorter because rows with `k=1` and `k=6` used to be considered peers because they have the same value of `w` (peers have the same result for window functions computations);  with the addition of ordering on `k`, they are no longer peers, so row with `k=7` is still processed first, then a single row `k=1` is processed, and only after that `k=6` is processed. Before it was: first `k=7`, and then `k=1` and `k=6` at the same time.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 1324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-LHdYp341TaTxcQuqSSg:-LHdpsVICARNgVWwK2mF:b9eim7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5f267eae5bd3b10866674169dd462800c0e6289/pkg/sql/logictest/testdata/logic_test/window#L1324)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come we get different results here and below?
</blockquote></details>

Another weirdness of window functions: without `ORDER BY` with default frame, all rows in the partition are considered peers, and `last_value` is the value of the expression at the last row. When I added ordering, rows became peers only with the ones that have the same value of `k` which, effectively, makes that query equal to `SELECT k, v FROM kv ORDER BY 1`.

**Comment by nvanbenschoten** [comment]
> I might be misunderstanding rowsort directive, but it seems to me that it only sorts the expected and received rows lexicographically when matching the results whereas I want to enforce a particular order in which window functions will be processing each row within their frame. For example, there are multiple valid outputs for a query SELECT k, row_number() OVER () FROM kv ORDER BY 1 - it all depends on in which order rows are received by window processor, and I'm not sure how to specify that order other than using ORDER BY clause on primary key.

I'm confused. If all you want is for the output to be deterministic so that there aren't test flakes then isn't `rowsort` exactly what we want? We don't want to eliminate an entire class of test cases because they don't produce deterministic output (like they shouldn't) just because that makes it harder to test.

**Review by yuzefovich — COMMENTED** [review]
Simply `rowsort` output is not enough - the "contents" of the rows might be interchanged. For example, we have two rows consisting of only `k` - primary key: (1) and (2). Say we're running a query `SELECT k, row_number FROM t ORDER BY k`. There are two possible outcomes:
1 1 ..... 1 2
2 2 ..... 2 1.
The former is obtained if the row `k=1` is processed first, the latter is when `k=2` is processed first. Both are valid outcomes based on the query. (Unless I'm missing something.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHdtzz_9KU-NLuNSSy4:b-y74r2r)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Sorry, the correct query would be `SELECT k, row_number() OVER () FROM t ORDER BY k`. And the formatting got messed up, two outputs are:
1 1
2 2
and
1 2
2 1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHdwSHo0u_t5ZcMqqAh:b-2fxk7s)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
Oh I see.

> Something like SELECT k, row_number() OVER () FROM kv ORDER BY 1 can (according to the SQL spec) return any permutation on the second column, so it doesn't make sense to expect a certain one.

I wasn't aware of that. Do you have a source for this?

**Review by RaduBerinde — COMMENTED** [review]
I don't have a specific reference for row_number / window functions but the standard says that FROM sources don't guarantee any particular ordering. @knz might have more specific knowledge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHe9QmoBK8DI8YFeQcx:b-ihi9mj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
yes I believe that's correct, window "buckets" are not ordered by the ORDER BY clause.

If you want particular orderings you need to write `select k, row_number() over (order by k) from kv`

(I don't know if we support that yet, but we'll need to to solve this particular problem.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHeB8iG2SJvti4trJuP:bg0ftp)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHeEoq8BiVXwxZMBu5u:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-LHdY8YqDsVFyAYQj2CV:-LHeEasC6XeuJn2YFraY:b-j7lvsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5f267eae5bd3b10866674169dd462800c0e6289/pkg/sql/logictest/testdata/logic_test/window#L367)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It is shorter because rows with `k=1` and `k=6` used to be considered peers because they have the same value of `w` (peers have the same result for window functions computations);  with the addition of ordering on `k`, they are no longer peers, so row with `k=7` is still processed first, then a single row `k=1` is processed, and only after that `k=6` is processed. Before it was: first `k=7`, and then `k=1` and `k=6` at the same time.
</blockquote></details>

I see. Probably the right way to do this is something like `SELECT k, concat_agg(s ORDER BY k) OVER (PARTITION BY v ORDER BY w, k) FROM kv ORDER BY 1`, except we don't yet support `ORDER BY` for aggregates (and postgres doesn't implement this for window functions either).

**Comment by nvanbenschoten** [comment]
Huh, it looks like SQLServer doesn't even allow window functions without an ORDER BY clause (https://sqlstudies.com/2018/02/21/windowing-without-a-partition-by-or-an-order-by/). Postgres does allow it though so we'll want to maintain support for it. The only thing I can find in PG's docs about this [is](https://www.postgresql.org/docs/9.1/static/tutorial-window.html):

> We already saw that ORDER BY can be omitted if the ordering of rows is not important. It is also possible to omit PARTITION BY, in which case there is just one partition containing all the rows.

There is also http://www.postgresqltutorial.com/postgresql-window-function/, which says that:

> If you omit the ORDER BY clause, the window function processes rows [within a partition] in an unspecified order.

My only real hesitation is that having an unspecified order in this case isn't particularly useful. We've had this discussion before with regard to the unspecified order when a top-level ORDER BY is omitted but I don't remember where we left off. @knz do you know what the resolution of that discussion was?

**Review by nvb — APPROVED** [review]
:lgtm:, but I'm worried about removing all tests that don't specify an ORDER BY clause. We should be careful about reducing test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27635#-:-LHeHJxSCehWDwgyZcod:b-2zp4mk)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by yuzefovich** [comment]
@nvanbenschoten I could add `window_local` test file with tests without ORDER BY clause. What do you think?

**Comment by knz** [comment]
> We've had this discussion before with regard to the unspecified order when a top-level ORDER BY is omitted but I don't remember where we left off. @knz do you know what the resolution of that discussion was?

Yes I remember and I know that the outcome was.

However before I share anything with you about this, I'd like to point out that this discussion was about the ordering for aggregates, not window functions. 

The discussion went as follows:
- the standard explicitly spells out that ORDER BY is not effective other than at the top-level
- postgres, like CockroachDB, extends this to the direct operand of non-standard relational operators where order definitely matters, for example LIMIT 
- then we opened the discussion about whether we should keep the requested ordering for the direct source operand of **aggregations**

The outcome was: although postgres doesn't keep it, but we will keep it, for two reasons. 1) because we don't support the SQL standard way to do things yet (`select max(x order by y)`) and 2) because it's just so much easier to grok.

Now, our decision was made on the understanding that aggregations have stronger "demand" for a non-standard behavior. This because they are just so common. We did not consider window functions at all.

I am not opposed to extending the outcome of the previous discussion to this new situation, but I do not want to do so casually. I think if we want to do that, we need to actually think this throughout and weigh alternatives. I want to know in particular:

- what's blocking us from implementing `over(... order by)`
- what would happen when an `order by` is specified both inside `over()` and in the source operand
- what would happen when there are mismatched specifications

**Comment by nvanbenschoten** [comment]
That sounds good, although it would also be nice to test as much as possible with DistSQL as well. Would a rowsorted query with all rows in different window partitions be deterministic?

**Comment by yuzefovich** [comment]
Yes, if a partition consists only of a single row, then the output will be deterministic. Great idea, I'll add tests like that.

**Comment by RaduBerinde** [comment]
There are plenty of tests left that have no `ORDER BY` - we do get deterministic results when the function is not order-dependent (e.g. a sum or a count).

**Pull request merged**
