### PR TITLE
deps: bump cockroachdb/redact

### LINKED ISSUE #64158: log: %s semantics different from stdlib for nil pointers
I've seen this in a log message, resulting from using `%s` for printing a nil pointer of a type that implements `SafeFormatter` on a value receiver.
```
%!s(PANIC=SafeFormatter method: value method github.com/cockroachdb/cockroach/pkg/roachpb.Lease.SafeFormat called using nil *Lease pointer
```
This is different from what `fmt.Printf` does for the Stringer interface, where it prints `<nil>`. If possible, it'd certainly take the `<nil>`. I've found this thread that might describe how to handle this case in the logging lib: https://github.com/golang/go/issues/20995

### PR DESCRIPTION
**Pull request by knz**
Fixes #64158

This introduces smart auto-formatting of structs and arrays
in redaction contexts.

This is a simplified version of  #66880 to avoid the bazel brokenness.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Looks like CI needs some attention still.

**Comment by knz** [comment]
oh my, the CI is even telling us there was an API regression (missing String method). I'll look at it now.

**Comment by knz** [comment]
fixed in https://github.com/cockroachdb/redact/pull/24. Rebasing

**Comment by knz** [comment]
ok this is flying now

bors r=tbg

**Pull request merged**
