### PR TITLE
*: fix `go vet` issues detected by go 1.8rc1

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12840)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/backup.go, line 553 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCu3fRQ3x5etNdVeSJ:-KaCu3fRQ3x5etNdVeSK:b-270lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/backup.go#L553)):*
> ```Go
> 	}
> 	if len(matches) == 0 {
> 		return nil, errors.Errorf("no tables found: '%s'", &table)
> ```

Doesn't `TableName.String` quote if necessary? For a table named `"hello world"` I think this could format as `no tables found: '"hello world"'`.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaCuP61m5imC7zvRZTZ:bkricra) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
> ```Go
> 				for _, e := range t.Exprs {
> 					typ := updateCols[i].Type.ToDatumType()
> 					e = fillDefault(e, typ, i, defaultExprs)
> ```

What's the vet warning here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-:-KaCuUY7jm6SMXbcx5g7:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/backup.go, line 553 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCu3fRQ3x5etNdVeSJ:-KaD1pRc0RsB-O7jgqFx:b-hm0orx) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/backup.go#L553)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Doesn't `TableName.String` quote if necessary? For a table named `"hello world"` I think this could format as `no tables found: '"hello world"'`.
</blockquote></details>

Hm, you might be right. Done.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaD3PITP8Dzs-lvSGoM:bn040ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What's the vet warning here?
</blockquote></details>

Shadowing the original value of `e`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaD3kZc7CdMx3x6cs-9:bzx2n1) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Shadowing the original value of `e`
</blockquote></details>

Yeah, but why is that a problem? This is a new scope, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaD5VG9DBl0ruYCR-9U:b6izkhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yeah, but why is that a problem? This is a new scope, right?
</blockquote></details>

No, it is not; `e` is the iteration variable defined in this scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaD5hKvwnFwe9yXkzMp:b-1mgvqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

No, it is not; `e` is the iteration variable defined in this scope.
</blockquote></details>

If it isn't a new scope, then wouldn't it be an error to redefine `e` here. That is, I would expect a `no new variables on left hand side` error.

Regardless, this change is fine, I'm just curious why vet is complaining about the previous code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/update.go, line 200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840#-KaCuP60MfqyylKkzLmo:-KaD6J9p8Z3J56ES04KH:b-ohshhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/55222605bf67e706cddc6349eb85fa6978a1eb39/pkg/sql/update.go#L200)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If it isn't a new scope, then wouldn't it be an error to redefine `e` here. That is, I would expect a `no new variables on left hand side` error.

Regardless, this change is fine, I'm just curious why vet is complaining about the previous code. 
</blockquote></details>

Good point. I'm not sure why vet is complaining either, but I have a guess - it's because `e` is present on the line declaring `e`. I've seen this before with patterns like `ctx, cancel := context.WithCancel(ctx)`.

Confirmed this is new in 1.8: https://github.com/golang/go/issues/18613.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12840)*

**Pull request merged**
