### PR TITLE
[wip] sql, roachpb: sample logical plans; save in statement statistics

### PR DESCRIPTION
**Pull request by vilterp**
Since plans are not designed to exceed the lifetime of a query execution, we convert them into a simple struct first.

This enables us to render them in on the Statement Details page: #28603

Release note: None

### CODE REVIEW

**Comment by vilterp** [comment]
@knz I did this as the fastest path toward showing query plans in the UI, but IIRC you wanted to store optimizer plans. For the UI, it doesn't make a huge difference — we'd just gain costs on each node, which is cool but not necessary for an initial version. Do you think it's important to rework this to use optimizer plans before merging?

**Comment by knz** [comment]
Wow, this is seriously nice. Congratulations on a job well done.

We can adapt this code to become compatible with the optimizer nodes later. Just ensure that the UI code does not make too many any assumptions about the node type strings and the k/v pairs. (or at least document them copiously).

Also your commit message needs some more details:

- an explanation of how often these plans are sampled.
-  a copious release note to explain what is going on.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-LEPmtGq91ZClStSEaX6:-LEPmtGq91ZClStSEaX7:bib13y) ([raw file](https://github.com/cockroachdb/cockroach/blob/473d9238395738011e6bc94690809b90ee5d32f0/pkg/sql/crdb_internal.go#L481)):*
> ```Go
>   key                 STRING NOT NULL,
>   anonymized          STRING,
>   most_recent_plan    STRING,
> ```

we have a JSON data type now. Please use it.

---

*[pkg/sql/crdb_internal.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-LEPmaDVCx9y7IhuD75m:-LEPmaDW3Bwm7q-A9e5P:b3teys6) ([raw file](https://github.com/cockroachdb/cockroach/blob/473d9238395738011e6bc94690809b90ee5d32f0/pkg/sql/crdb_internal.go#L596)):*
> ```Go
> }
> 
> type planNodeStack struct {
> ```

Very nice algorithm :100: 

You'll make me even more happy if you moved this logic to a separate file and added copious comments to explain what is going on. Not everyone is equally comfortable with this type of algorithm.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-:-LEPmwKl9TzkSDZWZcOy:bq8y46a)*

**Comment by knz** [comment]
1) consider adding an EXPLAIN option (`EXPLAIN(JSON)`) that exercises the same code path but is easier to use on arbitrary queries for tests

2) I also would like to see a SQL logic test that illustrates the produced JSON, both on the statmeent stats and EXPLAIN if you do it

**Comment by vilterp** [comment]
Thanks @knz; will respond to your suggestions.

Important note: if merged as is, this PR would cause unscrubbed plans (including values from user queries) to go to the reg cluster, which would be a data spill. So, I'll make changes to this PR s.t. the plan is deleted from the proto before reporting, possibly by creating a sub-message of stuff that's not supposed to be reported, and moving last_err there as well as the plan. Later, we can create an algorithm to scrub plans, and explicitly copy over scrubbed plans to the proto which will actually be reported.

(discussed w/ @dt and @couchand)

**Comment by vilterp** [comment]
@knz PTAL — responded to your comments, although I cut out exposing this to `crdb_internal` since the UI's endpoint now grabs the stats directly instead of going through SQL. (More efficient, since the stats are already in proto form, so it'd be silly to turn them into SQL datums and back). Someone can add that and `EXPLAIN (JSON)` in a later PR.

@dt please look at how I did `sensitive_info` (attempted to implement what we discussed), and advise on what work needs to be done to adapt the reg cluster to this new format. Thanks!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/crdb_internal.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-LEPmtGq91ZClStSEaX6:-LEzccGj4JXEE8Jl6Slo:b-ydtqee) ([raw file](https://github.com/cockroachdb/cockroach/blob/473d9238395738011e6bc94690809b90ee5d32f0/pkg/sql/crdb_internal.go#L481)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

we have a JSON data type now. Please use it.
</blockquote></details>

Agreed, but I think I'm going to cut scope and save this for another commit (or PR entirely)…

---

*[pkg/sql/crdb_internal.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-LEPmaDVCx9y7IhuD75m:-LEzcUo95THnTVZzVeH0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/473d9238395738011e6bc94690809b90ee5d32f0/pkg/sql/crdb_internal.go#L596)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Very nice algorithm :100: 

You'll make me even more happy if you moved this logic to a separate file and added copious comments to explain what is going on. Not everyone is equally comfortable with this type of algorithm.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-:-LEzcppx8Z83weFjzSDg:b-fa5h1u)*

**Comment by knz** [comment]
Reviewed 10 of 11 files at r2, 10 of 10 files at r3, 1 of 1 files at r4.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/walk.go, line 131 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26494#-LFJfsGnb4_D-A9laKy--r4-131:-LFcnlV_7DT45VjBfJT0:b81pvkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1027b25a2dc09b80c6a68a948aceecffd67e76d4/pkg/sql/walk.go#L131)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

the query `SELECT DISTINCT y, z FROM xyz` from a logic test fails if this check is not here (the entire `n` struct appears to be zeroed out)
</blockquote></details>

Here and below: you're taking this from the wrong end. You're attacking a symptom without addressing the root cause. Just changing this file without properly addressing what's going on will get you garbage plans.

The problem is that the planNode tree is modified in-place during query execution. It becomes garbage by the time execution completes. There's no way to extract useful information from it by that time.

What you need to do is to leave this file alone and instead sample your plan after planning completes and before execution starts.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26494)*

**Comment by vilterp** [comment]
Thanks Raphael, you're totally right — Jordan helped me go over these tests and we came to the same conclusion. Have some changes that sample the plan before execution; will push up soon.

**Comment by vilterp** [comment]
Superseded by #33020

**Pull request closed without merging**
