### PR TITLE
storage: Indirect all Replica access through a new ReplicaEvalContext

### PR DESCRIPTION
**Pull request by bdarnell**
A follow-up change will require that all accesses to the in-memory
fields of the Replica are accompanied by SpanSet declarations for the
corresponding on-disk keys.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14389)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_state.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGFmSo6OkCZFpdWogq:-KgGFmSo6OkCZFpdWogr:b-kisaub) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bfde4fc66d931209bfe4735d86269b57ea281b5/pkg/storage/replica_state.go#L29)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/protoutil"
> 	"github.com/coreos/etcd/raft/raftpb"
> ```

nit: grouping

---

*[pkg/storage/replica_state.go, line 586 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGFqu__J4wPhV6yDEc:-KgGFqu__J4wPhV6yDEd:bsbnie2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bfde4fc66d931209bfe4735d86269b57ea281b5/pkg/storage/replica_state.go#L586)):*
> ```Go
> }
> 
> // ReplicaEvalContext is the interface through which command
> ```

does anything enforce that `ReplicaEvalContext.repl` is not accessed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_state.go, line 723 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGie3Q3v183KmgU7_L:-KgGie3Q3v183KmgU7_M:b-lo2v11) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb49bbcf84d09bbfe4f3ffcd109ad8db123d981f/pkg/storage/replica_state.go#L723)):*
> ```Go
> func (rec ReplicaEvalContext) GetLease() (*roachpb.Lease, *roachpb.Lease, error) {
> 	lease, nextLease := rec.repl.getLease()
> 	return lease, nextLease, nil
> ```

Why does this method return an error if it is always `nil`? Probably has something to do with the yet-to-be-added `checkAllowed` calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-:-KgHW30Hpn-W6b2BOHj7:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_state.go, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGFmSo6OkCZFpdWogq:-KgHxGn6S7iKErB0kHNE:b-w0vxid) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bfde4fc66d931209bfe4735d86269b57ea281b5/pkg/storage/replica_state.go#L29)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: grouping
</blockquote></details>

Done since I had to rebase anyway, but I think we should stop caring about import formatting. Anything that `goimports` will accept should be acceptable to us.

---

*[pkg/storage/replica_state.go, line 586 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGFqu__J4wPhV6yDEc:-KgHxQ_AeZbrK0j-0sz6:b-an745y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bfde4fc66d931209bfe4735d86269b57ea281b5/pkg/storage/replica_state.go#L586)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

does anything enforce that `ReplicaEvalContext.repl` is not accessed?
</blockquote></details>

No. (although these static functions now use very little unexported state in package `storage`, so we're close to being able to move a chunk of this code into a subpackage and start to break up the `storage` monolith). 

---

*[pkg/storage/replica_state.go, line 723 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389#-KgGie3Q3v183KmgU7_L:-KgHxw_5d6A13OIYznfm:b-shav3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb49bbcf84d09bbfe4f3ffcd109ad8db123d981f/pkg/storage/replica_state.go#L723)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Why does this method return an error if it is always `nil`? Probably has something to do with the yet-to-be-added `checkAllowed` calls.
</blockquote></details>

Exactly. All the new methods that return errors will have `checkAllowed` calls added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14389)*

**Pull request merged**
