### PR TITLE
storage: Lessen "timestamps in future" errors

### PR DESCRIPTION
**Pull request by tbg**
When a `LeaderLease` request transfers leadership to another node, the
timestamp cache's low water mark was updated from MaxOffset added to the
previous lease's expiration. This change makes sure we use the local clock's
wall time (plus MaxOffset) if it gives the smaller result. Consider the
following (hypothetical, but potentially real - see #5822, #3087) scenario:

The following happens rapidly at some "real" time T (with `MaxOffset=250ms`):
- Coordinator hits Range1, but the lease is on another Node and just expired.
- Range1 gets lease, updates lowWater to `T+250ms`
- Coordinator gets response timestamp `T+~250ms` (which it'll use for future
  requests).
- By chance, Range2 has a lease that expires at `T+~250ms`.
- Coordinator hits Range2 just after (perceived) expiration of its lease, triggers leader lease request at `T+~250ms` with Node change. It updates its lowWater to `T+~500ms`.
- Coordinator gets response timestamp `T+~500ms` and uses it for the next request, boom.

Unfortunately, the new code still has that same problem, albeit hopefully less
pronounced. Some options are:
- If the timestamp cache runs into the lowWaterMark and that is a future
  timestamp (compared to the node's HLC), then don't return to the client
  until the node's clock has caught up (i.e. naively, sleep on the offset).
- Add a grace period to the time interval. That is, the lease owner must not
  actually use the lease during the last `MaxOffset` of the alotted interval.
  Instead such a request must extend the lease. Consequently, a new acquirer
  of the leader lease can simply use the old lease's expiration verbatim for
  its timestamp cache.

I would think that the second option is the preferrable one, but please
discuss/add to the above.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5845)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

An alternative to a "grace period" in which the last `MaxOffset` portion of the lease is unused, we could express the same thing by requiring a `MaxOffset` gap between the expiration of an old lease and the start time of a new one. It feels a little simpler to me to think of it as a gap during which the lease is unowned instead of a time when the lease is held but cannot be used, although I'm not sure if it would make things easier in practice. Either way, I agree it's probably better to build the MaxOffset adjustments into the endpoints of the leases rather than to use the timestamp cache to do this.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1353 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXKCvUoZKC0pNH46P3:-KEXKCvUoZKC0pNH46P4:986753497) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/replica_command.go#L1353)):*
Why disallow it? I don't understand what this new comment is saying. I think the previous comment was anticipating a world in which the lease timeout is much higher than its current 1s value (to mitigate lease-renewal overhead which cannot be coalesced like heartbeats), so we'd rely on leaders giving up their lease for quicker handoffs in practice.

---

*[storage/timestamp_cache.go, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXL1aBJW9okVEEO50e:-KEXL1aBJW9okVEEO50f:1787629277) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/timestamp_cache.go#L105)):*
We might be able to just remove the use of MaxOffset here. The `Clear()` method is only used in two places outside tests: at startup and in merge, and merges aren't happening for a long time. 

If we need this for startup (to get around the fact that we don't persist the HLC state) it's probably better to just sleep for MaxOffset before doing anything instead of pushing our HLC offset to the edge of its acceptable range (which we've already seen results in surprising behavior like timestamps that don't appear to move). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KEXNAu4NASZ9DNXBKRD:276111032)*

**Comment by tschottdorf** [comment]
I'll look at both options tomorrow, though I expect the gapless one to work out better (with an explicit renaming of fields, hopefully the grace period can be made very obvious). We'll see.

Will add changes to this PR.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1353 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXKCvUoZKC0pNH46P3:-KEXk-ctNw9GHI5Sug5x:-891139825) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/replica_command.go#L1353)):*
Yes, and I agree that it's useful, but I'm just worried about correctness with the current state of affairs.

If `NodeX` holds the lease until `T` , serves some reads at `T-1` and then shortens its lease to `T-100`, the next lease holder will not register `T` as the base for its low water mark, but `T-100` even though a read at `T-1` has been served.

The window for this is relatively small, but still - what's done here just doesn't seem right.
Planning to clean all of this stuff up tomorrow, so I'll make sure to clean up this code and remove the TODO.

---

*[storage/timestamp_cache.go, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXL1aBJW9okVEEO50e:-KEXkYH2zF17pTAGXpYu:-2106968614) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/timestamp_cache.go#L105)):*
Yeah, I was also planning on sleeping for `MaxOffset` at boot time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KEXkhCsF4LlVbrf5_n8:923150827)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1353 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXKCvUoZKC0pNH46P3:-KEXnMlu1CBwMNB8_UCp:970260421) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/replica_command.go#L1353)):*
Then that's the leader's fault: a leader that shortens its lease must never move the expiration before an operation that it has already served (and it must assume that the new expiration takes effect as soon as it proposes the command, without waiting for it to be applied). That's a potential source of error, sure, but we'll just have to watch out for that when and if we implement lease reductions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
Hopefully I'm missing something, but I went back and tried to spell out more precisely why the current code updates the low water mark in the way it does. The one problematic scenario I came up with is below. The problem with it is that messing with the low water mark really doesn't help (if anything it makes it worse), and the real remedy is not serving writes for the first `250ms` (a real-time `250ms` sleep) after applying the new lease or until we know that the old leader has applied it.

* A leader lease gets committed on the new leader (but not the old).
* Directly after, a client proposes and commits a write on new leader
  (with a timestamp just after the expiration of the old lease).
* As its next command, it tries to read what it wrote. A slow
  coordinator assigns the timestamp; it is covered by the old
  lease.
* The read is served by the old leader. This is possible if it still did
  not apply the new LeaderLease command and the coordinator still
  has it cached.
* The client does not see their own write.

Usually, the mechanism that prevents this failure of linearizability on a single register is that of uncertainty restarts, but since the local KV data at the old leader does not even have the new write, that's not happening here. A causality token would also have taken care of it, but again that isn't happening necessarily (it is in many situations, but not all).

So am I missing something in the above? If not, is that at least the "only" thing that can go wrong when changing leaders?

**Comment by bdarnell** [comment]
Yes, I think that's right. The "grace period" idea discussed above would prevent this without a sleep: the old leader would refuse to serve the read because it came too close to its expiration. But all of these solutions have the same result, which is that a change of lease holder requires a period of unavailability equal to the max offset.

**Comment by tschottdorf** [comment]
Pushed a new version which implement the "grace period". A little bit of WIP left (see commit message) and I haven't given the final diff a pass through, but it should be fit for some commentary - will clean up fully (my) tomorrow morning.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/replica_command.go, line 1353 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEXKCvUoZKC0pNH46P3:-KEfbxcdbNToor6rqYcQ:-635109333) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f02a6b2265b54ebf05e7f2e326f31b33ce64665/storage/replica_command.go#L1353)):*
I disabled this feature for now, it'll be easily reintroduced when when need it (and there's no a comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KEgL4cz43d2ceiJLhba:-443951522)*

**Comment by petermattis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/data.proto, line 326 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgq9quTQU_QWpm8cmX:-KEgq9quTQU_QWpm8cmY:253437146) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/roachpb/data.proto#L326)):*
Is there any danger with adding a new field to this proto? Looks like this proto is encoded by the `LeaderLease` command "below" raft. So a server which was built before this change would encoded the proto differently than one built afterwards.

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KEgr7yB57lhywxWKC1r:-1188053476) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
We don't change `hlc.Clock.MaxOffset` in a running cluster. Why does it need to be included in the `Lease` structure?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/data.proto, line 326 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgq9quTQU_QWpm8cmX:-KElf1cvRJOzjD8l9jj-:532208625) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/roachpb/data.proto#L326)):*
Yes, unfortunately. Fortunately we can drop it. I'd rather not, but if that's what it takes, why not.

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KElf7T_-WgCDvMHhYPX:1980561031) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
Because MaxOffset is configuration and **can** change at runtime (though it currently doesn't). In light of the migration story I think I'll make it so that changing MaxOffset in production is a panic (which will need some test fixes) and then I'll feel comfortable grabbing it from there. But if I had the choice, I'd want it on the lease because it's so pertinent to its semantics.

We need to fix that migration stuff very soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by petermattis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KElkyEUFBEWxmgedraB:-1611964487) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
Agreed about the need for migration infrastructure. We should use this as a motivating example and start thinking about a design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KEmMdWOwUR3LU3N2xbs:-972115114) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
Ok, I'll ponder a little bit. Can hopefully write something preliminary down before end of next week.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by bdarnell** [comment]
Reviewed 1 of 3 files at r1, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 97 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEmWxMiacNkalVI3Z5o:-KEmWxMjPMSBD-UnHs9E:421733363) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L97)):*
Maybe this could take a clock instead of the offset? It looks like every caller is just calling `MaxOffset` on some clock. 

It doesn't feel right for the lease duration to vary depending on the configured clock offset. I would expect the lease duration to be constant, but for a variable-sized duration to go unused. The default should perhaps be increased now that it's not all usable, but I'd still make it a constant.

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KEmZBe9s1otm6wMjt6S:-1900728413) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
I think this would have been safe from a proto-serialization perspective if we had enabled unrecognized fields (#5694) before beta, because the value that gets saved is a reserialization of a pre-raft value.  But that's probably not good enough, since even if the protos are serialized correctly all the replicas need to produce the same output from `Lease.Covers`.

However, it is safe in a stop-the-world upgrade. As long as the old and new versions don't mix, then no old server will apply a raft command generated by a new server, and new servers work gracefully with both old and new serialized protos. 

Let's think about how we'd do this in an online fashion but we have the stop-the-world option as a quick fix if we don't want to wait for the full solution. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
More changes but hopefully good to go soon. I implemented eager lease renewal. PTAL

---

Review status: 4 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/replica.go, line 97 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEmWxMiacNkalVI3Z5o:-KF9ESH83bXHRVU9i8v_:-991644554) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L97)):*
Agreed. I made this completely static by treating `DefaultMaxOffset` as a maximum allowed value (so you can't run a server with a higher one).
That way, `DefaultLeaderLeaseDuration` is a constant again. It's all kind of tedious but easy enough to make use of the clock again should the need arise (doubtful).

---

*[storage/replica.go, line 481 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEgr7yB57lhywxWKC1q:-KF8ybpPSbd1yagb78JQ:-509516766) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L481)):*
SGTM. I'd like to keep `MaxOffset` on the lease just to make everything explicit then. I'd also like to assert against MaxOffset==0, but then that would break - maybe that can be done later when the migration story is in place (but even then probably not worth it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KFFK-07su5HxsrOvkVT:-2139434297)*

**Comment by bdarnell** [comment]
Reviewed 13 of 16 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[base/defaults.go, line 36 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFZP0NcIgf6OpHOaFe:-KFFZP0NcIgf6OpHOaFf:543531273) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/base/defaults.go#L36)):*
We should really split this into `DefaultMaxOffset` and `MaxMaxOffset`. Even if they have the same value for now we should be clear about whether we're using the value as an upper bound or as the default. (and I think `MaxMaxOffset` should probably be at least 500ms; I think we have anecdotal reports of 300-400ms offsets in virtualized environments)

---

*[storage/replica.go, line 97 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEmWxMiacNkalVI3Z5o:-KFFcx8L-ljfRrpbu92R:1530368614) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L97)):*
Making the grace period static based on the worst-case `MaxOffset` doesn't seem like a great idea to me.  It limits the utility of configuring a lower `MaxOffset`. I'd still rather make the lease duration static but the grace period (and therefore renewal time) dynamic. 

---

*[storage/replica_command.go, line 1431 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFkp2b2lG0J0J-kd-M:-KFFkp2b2lG0J0J-kd-N:-1134152164) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/storage/replica_command.go#L1431)):*
s/expiraton timestamp/previous lease/

---

*[storage/replica_command.go, line 1433 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFkyDkZfvPBjjWulw4:-KFFkyDkZfvPBjjWulw5:1714767593) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/storage/replica_command.go#L1433)):*
What's an artificial timestamp? One with a non-zero logical component? Should we add an assertion for that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[base/defaults.go, line 36 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFZP0NcIgf6OpHOaFe:-KFKB8aR-voKseHaPtoz:-767827768) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/base/defaults.go#L36)):*
Looking at this today, I think I can back this out. After all, the MaxOffset is used only by the node which proposed it and holds/held leadership. Thus, it's completely fine whatever it is. If the cluster is running with an inhomogenous MaxOffset setting that's odd, but not really an issue as far as this code is concerned (though we would likely still want to point it out as a misconfiguration).

---

*[storage/replica.go, line 97 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KEmWxMiacNkalVI3Z5o:-KFKHVva4pPgNOkwLWY9:386686696) ([raw file](https://github.com/cockroachdb/cockroach/blob/540d3434680d4a87dfefeb2cc41d2b49a8fa90f1/storage/replica.go#L97)):*
I’m planning to just call the “duration” the thing without the grace period (i.e. the constant now known as defaultLeaderLeaseBaseDuration), which is (and will be constant). I can take the MaxOffset of the local clock and use the lease message with fields `Start, StartGrace, Expiration` (so that [Start,StartGrace) is the leader lease duration). 
Will ping.

---

*[storage/replica_command.go, line 1431 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFkp2b2lG0J0J-kd-M:-KFKB7YH14dvl8LXBhKX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/storage/replica_command.go#L1431)):*
Done.

---

*[storage/replica_command.go, line 1433 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFFkyDkZfvPBjjWulw4:-KFKAXYNP4ZVVWt-yKLN:761019785) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b57be11e19defea9a33b90f324ba5832ae20cf/storage/replica_command.go#L1433)):*
No, it's one for which we made up the wall time. Like what the old code was doing, where it simply added `250ms` to some existing timestamp. That new timestamp leaks into the clocks and leads others to believe that it was in fact some node's wall time. I've changed wording to "hand-constructed" for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
@bdarnell Ping and PTAL. Commit message updated. I think you might as well look at the total diff due to the churn.

---

Review status: 4 of 16 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KFLOSZhOZonEgVIqqwS:-785326239)*

**Comment by tschottdorf** [comment]
Tagging as noteworthy since it closes fairly old bugs and because it implements some leader lease stickiness (both of these have not been proven true in practice, but let's hope for the best).

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 3 of 16 files at r6, 11 of 12 files at r8.
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/parser/sql.y, line 270 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQFHpDaW71JOmPhFxu:-KFQFHpDaW71JOmPhFxv:-998220185) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/sql/parser/sql.y#L270)):*
Bad merge?

---

*[storage/replica_command.go, line 1359 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQM7t481SIX3tWUgiP:-KFQM7t5x7txdl1HyDZq:-942754762) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_command.go#L1359)):*
We could be replaying an old LeaderLease requests from the raft logs, which would not have a `StartStasis` value. We must permit `StartStasis` to be missing/zero here for backwards-compatibility. 

---

*[storage/replica_test.go, line 4265 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQGboDJOFxpVE_bRJX:-KFQGboDJOFxpVE_bRJY:-1831551603) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_test.go#L4265)):*
s/LeaseExpiry/leaseExpiry/ s/unix//

Can we consolidate this function with LeaderLeaseExpiration above? (at least put them next to each other)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-:-KFQNLEdZLHBUoDyQJ-Z:676834233)*

**Comment by tschottdorf** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/parser/sql.y, line 270 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQFHpDaW71JOmPhFxu:-KFQv090M9133UxkGjTi:1134352312) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/sql/parser/sql.y#L270)):*
Very much so, fixed.

---

*[storage/replica_command.go, line 1359 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQM7t481SIX3tWUgiP:-KFQv58Hd5TEF_k5aVrZ:495972826) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_command.go#L1359)):*
That can be done, but did you see my migration comment on the commit? If the consistency queue isn't in kill mode, I think we can comfortably get away with it. Let me know.

---

*[storage/replica_test.go, line 4265 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQGboDJOFxpVE_bRJX:-KFQvzgbqzfTRKnASVN-:-1824776534) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_test.go#L4265)):*
Probably doable in theory, but only at the expense of being less "on the point" in the tests which test a specific lease, which I think is worth avoiding. I moved them next to each other and added commentary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by bdarnell** [comment]
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1359 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQM7t481SIX3tWUgiP:-KFR298zYKj_FyHElut2:-1312701997) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_command.go#L1359)):*
Ah, I missed the updated commit message. Unfortunately we can't rely on the fact that the lease will be overwritten:  `applyRaftCommandInBatch` verifies that the (in-memory) lease is held by the node that originated the raft command (this is how we guard against cross-term replays). So we need to preserve consistency here even though the on-disk value will eventually get overwritten without a trace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tschottdorf** [comment]
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1359 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845#-KFQM7t481SIX3tWUgiP:-KFR6y-qA150p66eiWuK:866847786) ([raw file](https://github.com/cockroachdb/cockroach/blob/108f7ea5dad663f150685dae92193244fe44e0ff/storage/replica_command.go#L1359)):*
Ah, bummer. Ok, time to put some ugliness in the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by tamird** [comment]
Reviewed 3 of 12 files at r3, 1 of 18 files at r9, 17 of 17 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5845)*

**Comment by bdarnell** [comment]
Also noteworthy: this change requires a stop-the-world upgrade.

**Comment by tschottdorf** [comment]
Yep. Just to be sure, don't we require those for all changes currently?

On Sat, Apr 16, 2016 at 1:43 PM Ben Darnell <notifications@github.com>
wrote:

> Also noteworthy: this change requires a stop-the-world upgrade.
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/5845#issuecomment-210862522>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
It's a good question. We haven't documented this requirement before, although I'd be surprised if any of our beta releases so far would be 100% safe in an online upgrade. This change is riskier than most, however: even in a quiet cluster, leader lease requests are made frequently in the background, so if there is a command that is left unapplied in the raft log when everything shuts down, the odds are good that it's a leader lease command.

**Comment by andreimatei** [comment]
I've got a naive question about this old change: it looks to me like nowhere in here did we introduce an error corresponding to the stasis period at the end of a lease. What happens to a command with a timestamp in that period? If the node holding the lease is still around, it'll be able to renew the lease and serve the command. But if the node is not around anymore? The command will bounce around by NotLeader redirections endlessly? Somebody should tell the client that it needs to restart with a higher timestamp, no? I guess any node can tell that to the client as soon as the txn's timestamp falls below the start of the current lease?
On a related note, what's the story (if any) for historical reads, outside of the current lease? Who's supposed to serve them and how can they bypass the check for a lease?

I'm asking because I'm trying to do this lease transfer thing, and it exacerbates this problem. Once a replica wants to transfer away its lease, it'll have to act for a while like it's in the stasis period (so, don't serve anything), but it can't redirect or attempt to re-acquire. Should I return `TransactionRetryError`, updating the txn's timestamp to the end of the stasis, and have one of the `Sender`s sleep until then?

**Comment by tschottdorf** [comment]
> TransactionRetryError, updating the txn's timestamp to the end of the stasis

no, that would generate errors similar to why we introduced this change in the first place. Our timestamps are always tied to real clocks. You must not make up timestamps as you please or anomalies ensue.

> The command will bounce around by NotLeader redirections endlessly?

That's correct. There is a mandatory period of unavailability as the leader changes hands because of clock offsets.

**Comment by andreimatei** [comment]
OK, so maybe `TransactionRestartError` is not appropriate, but we should have an error that somehow tells the client to try again in 250ms if you're in the stasis period and can't renew, right? 
What's the appropriate response for a txn with a timestamp below the current lease?

**Comment by tschottdorf** [comment]
There's nothing transactional about this error, it affects all read/write
commands. Someone will have to wait - it's not clear that it should be the
client. Might as well be DistSender, which conveniently is also the entity
handling NotLeaderErrors. For example, we could augment `NotLeaderError` to
contain the generating node's current HLC timestamp and an offset
(indicating a backoff duration).

On Fri, May 27, 2016 at 4:28 PM Andrei Matei <notifications@github.com>
wrote:

> OK, so maybe TransactionRestartError is not appropriate, but we should
> have an error that somehow tells the client to try again in 250ms if you're
> in the stasis period and can't renew, right?
> What's the appropriate response for a txn with a timestamp below the
> current lease?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/5845#issuecomment-222245596>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135L18NnW-yvEkjv4pBvCoHkKqSwGlks5qF1PmgaJpZM4H_R-s>
> .
>
-- 

-- Tobias

**Comment by andreimatei** [comment]
I agree that the `DistSender` can do the waiting. But if the command the replica is trying to process is done in a txn, doesn't the txn's timestamp need to change? So doesn't the txn need to be restarted, meaning the error needs to be propagated back to the client (after the waiting)?

**Comment by tschottdorf** [comment]
The new leader will have to set the low watermark on the timestamp cache (to the old lease's expiration), so any txns affected by this are likely going to catch a restart. There is something to be optimized there, though in the presence of a MaxOffset delay I don't think that's worth optimizing for at this point.

**Comment by bdarnell** [comment]
This change didn't introduce such an error because it is generally impossible to determine that the leaseholder will be unable to renew: the lease holder will always attempt to renew, and other nodes will always attempt to redirect to the lease holder. The lease expires faster than any of our other failure detection mechanisms will notice that the node is down. (There is one exception, when the current lease holder rebalances the range away from itself. But we should fix that by making the rebalancer smart enough to only move followers instead of optimizing for this case)

The leadership transfer mechanism is the first time in which we will be able to definitively say that the lease holder will not be renewing its lease and there is nothing to do but wait out its expiration. So the introduction of leadership transfer would be the time to introduce a "retry after time T" error, if one is needed for that (depending on how leadership transfer is implemented, we may be able to align its effective start time with the lease expiration).

**Pull request merged**
