### PR TITLE
sql: fix locality information in show ranges

### LINKED ISSUE #43755: Incorrect use of store ids instead of node ids
**Describe the problem**

There is a bug rendering range locality. We use store ids instead of node ids. So in case where the store ids of a node differ from the node id - the locality information is incorrect. I haven't observed however constraint violation. The issues is just with the display.

**To Reproduce**

Start multiple nodes in parallel (not sequentially) seems to be the easiest way to repro this.

**Expected behavior**
I expect to see correct information in the result of `select replicas, replica_localities from crdb_internal.ranges`

**Environment:**
 - CockroachDB version [20.1]
 - Server OS: [n/a]
 - Client app [n/a]

**Additional context**
What was the impact?

It gave the wrong impression that constraints are being violated.

### PR DESCRIPTION
**Pull request by darinpp**
Previously the locality information in show ranges was incorrectly assuming
that range descriptors are node id based.
This was causing a mismatch between replicas tuple and the locality.
To address this, this change makes the locality info be based on store ids.

Fixes #43755, #30940

Release note (sql change): Show ranges now shows locality information
consistent with the range descriptor when node id and store id don't match..

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

___
*[pkg/sql/crdb_internal.go, line 2011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly50Z8S7lTd6hkNfr0B:-Ly50Z8T8QotfIwRuimM:bb7yrqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal.go#L2011)):*
> ```Go
> 			}
> 
> 			voterReplicas := append(
> ```

nit: I'd keep this on the same line. It gets a lot louder when spread over 4.
___
*[pkg/sql/crdb_internal.go, line 2015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly516JE2lbghUYS7A_t:-Ly516JFABfEL7YCxOT_:b-u6rmou) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal.go#L2015)):*
> ```Go
> 				desc.Replicas().Voters()...,
> 			)
> 			var learnerReplicas []int
> ```

rename this to `learnerReplicaStoreIDs`
___
*[pkg/sql/crdb_internal_test.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51rNJ62fhHSzrbO8F:-Ly51rNJ62fhHSzrbO8G:b-1xf9wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L38)):*
> ```Go
> )
> 
> func TestRangeLocalityBasedOnNodeIDs(t *testing.T) {
> ```

Add a comment about what this is testing.
___
*[pkg/sql/crdb_internal_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51Lrg8IRIHlCvt5sb:-Ly51Lrg8IRIHlCvt5sc:b-nzr7wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L64)):*
> ```Go
> 	)
> 
> 	//Set to 1 so the next store id will be 2
> ```

Missing space at the beginning of this comment. Also, comments that are sentences should have periods at the end.
___
*[pkg/sql/crdb_internal_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51hKM9vR9pIFoql6k:-Ly51hKM9vR9pIFoql6l:b-kyn40s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L67)):*
> ```Go
> 	tc.Servers[0].DB().Put(ctx, keys.StoreIDGenerator, 1)
> 
> 	// NodeID=3, StoreID=2
> ```

Is there a crdb_internal table we can read to test that this is true?

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43807)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 2011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly50Z8S7lTd6hkNfr0B:-LyBkx1g6mAQNoNzKQjm:b-afkh4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal.go#L2011)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I'd keep this on the same line. It gets a lot louder when spread over 4.
</blockquote></details>

moves to the same line.
___
*[pkg/sql/crdb_internal.go, line 2015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly516JE2lbghUYS7A_t:-LyBkz4e581RbLsWDVbW:b-hff6wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal.go#L2015)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

rename this to `learnerReplicaStoreIDs`
</blockquote></details>

renamed
___
*[pkg/sql/crdb_internal_test.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51rNJ62fhHSzrbO8F:-LyBl1e1Ch740kOuwoOw:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment about what this is testing.
</blockquote></details>

added
___
*[pkg/sql/crdb_internal_test.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51Lrg8IRIHlCvt5sb:-LyBl2saCX4lC38gcI88:bh13dux) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Missing space at the beginning of this comment. Also, comments that are sentences should have periods at the end.
</blockquote></details>

added space and period
___
*[pkg/sql/crdb_internal_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-Ly51hKM9vR9pIFoql6k:-LyBl6Ln54atlCDAqhQ_:b-fuac7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c9aa92488b0146efdb35ae507cefc282c92236/pkg/sql/crdb_internal_test.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a crdb_internal table we can read to test that this is true?
</blockquote></details>

added assertions for the store ids

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43807#-:-LyVDPaX5ZYEMPAiGDQ2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
