### PR TITLE
sqlbase: use ResumeSpan in kvfetcher

### PR DESCRIPTION
**Pull request by vivekmenezes**
Also ensure that the fetcher is not reading more than
one partial response.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8967)

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQSGcAkZ8iCNwAcrw8H:b-6kkujo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
> ```Go
> 		if len(result.Rows) > 0 {
> 			if readPartialResponse {
> 				return fmt.Errorf("read partial responses for more than one span %+v", b)
> ```

is logging the batch really the right thing here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/kvfetcher.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQW5TVw4u__QWvx4BVm:-KQW5TVw4u__QWvx4BVn:bjya1fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L148)):*
> ```Go
> 	for i := range spans {
> 		if reverse {
> 			copySpans[len(spans)-i-1] = spans[i]
> ```

We need to explain the requirements this function has on `spans` in the comment.

Are we assuming that if `reverse` is true, then the spans are in increasing order? We should check that and panic if they are not.

Now, the issue here is that there are cases (`indexJoin`) where `reverse` is `false` and the spans are NOT ordered. The flip side is that in that case we don't need to set any batch limits in that case (each span is a row so we are inherently limiting the results by limiting the number of spans) but we should assert that we don't ever send a request with unordered spans and a limit.

---

*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQW4Kx-miVWmikbtS9x:bp5200r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is logging the batch really the right thing here?
</details>
This is supposed to never happen right? We should do a `log.Errorf`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/kvfetcher.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQW99Exmo5aFUeLoJJY:-KQW99EywzxLMgHVurSM:b-61161n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L212)):*
> ```Go
> 			f.fetchEnd = false
> 		}
> 		f.spans[idxs[i]] = result.ResumeSpan
> ```

instead of using the`idx` array, could we reset `f.spans` before this loop and do something like `if results.ResumeSpan.Key != nil { f.spans = append(f.spans, result.ResumeSpan)}` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/kvfetcher.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQW5TVw4u__QWvx4BVm:-KQaRyoB963SazROaeQo:b-t9olev) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L148)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We need to explain the requirements this function has on `spans` in the comment.
> 
> Are we assuming that if `reverse` is true, then the spans are in increasing order? We should check that and panic if they are not.
> 
> Now, the issue here is that there are cases (`indexJoin`) where `reverse` is `false` and the spans are NOT ordered. The flip side is that in that case we don't need to set any batch limits in that case (each span is a row so we are inherently limiting the results by limiting the number of spans) but we should assert that we don't ever send a request with unordered spans and a limit.
</details>
I've added a comment specifying the ordered limitation on spans and how they should be specified. I've been unable to reproduce triggering the more than one partial response error. I think it's best that we create a separate issue to create a test that triggers that at the SQL layer based on 
TestMultiRangeBoundedBatchScanUnsortedOrder and fix it by removing the batch limit where necessary. For now a user will see the more than one partial response error.

---

*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQaNEYNacTlY7TewNsI:b-w495hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is supposed to never happen right? We should do a `log.Errorf`
</details>
I've been unable to reproduce this error using existing tests and with kvBatchSize=2 . It certainly slows down the tests but there are no test failures. I've changed the error message to return the new resume spans.

---

*[sql/sqlbase/kvfetcher.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQW99Exmo5aFUeLoJJY:-KQaLrenL-cIS8K3ttEL:b-dvnbpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L212)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> instead of using the`idx` array, could we reset `f.spans` before this loop and do something like `if results.ResumeSpan.Key != nil { f.spans = append(f.spans, result.ResumeSpan)}` here?
</details>
Good point! done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/kvfetcher.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6gECTNxxaeQ7gUaj:-KQb6gECTNxxaeQ7gUak:brcgepf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L197)):*
> ```Go
> 			// A span needs to be resumed.
> 			f.fetchEnd = false
> 			f.spans = append(f.spans, result.ResumeSpan)
> ```

So the spans that didn't get any results will get a ResumeSpan that is identical to the span we passed (possibly trimmed down)?

---

*[sql/sqlbase/kvfetcher.go, line 201 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6610KjpcOP26reVK:-KQb6610KjpcOP26reVL:b2faglx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L201)):*
> ```Go
> 		if len(result.Rows) > 0 {
> 			if readPartialResponse {
> 				return fmt.Errorf(
> ```

Use errors.Errorf. Also, raw spans are unreadable, should use PrettySpans

---

*[sql/sqlbase/kvfetcher.go, line 202 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6AX-xc_Mv2yb3eJf:-KQb6AX-xc_Mv2yb3eJg:bk908si) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L202)):*
> ```Go
> 			if readPartialResponse {
> 				return fmt.Errorf(
> 					"read partial responses for more than one span, new spans: %s", f.spans,
> ```

[nit] close paren on the same line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-:-KQb7AfUQtQhHGw-jipF:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/kvfetcher.go, line 197 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6gECTNxxaeQ7gUaj:-KQb8uW2zMjvJKID_JGH:b-qcdl8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> So the spans that didn't get any results will get a ResumeSpan that is identical to the span we passed (possibly trimmed down)?
</details>
that's right, a span that was not processed because the ranges were not read because the limit was hit is returned back to the user.

---

*[sql/sqlbase/kvfetcher.go, line 201 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6610KjpcOP26reVK:-KQbC924nXgeMTx5N-ty:bn35rki) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Use errors.Errorf. Also, raw spans are unreadable, should use PrettySpans
</details>
done. We should move PrettySpans to roachpb. Will do that separately

---

*[sql/sqlbase/kvfetcher.go, line 202 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQb6AX-xc_Mv2yb3eJf:-KQbCGaqJ_9wAQeVAscA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d78d508ea2d11a445e217e9ae7a0b5127e4821e1/sql/sqlbase/kvfetcher.go#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] close paren on the same line
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-:-KQbGmtD91PMqiH0ESr3:b-g2a5fb)*

**Comment by RaduBerinde** [comment]
*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQg97wOZO3cAxmRAKec:bhdwyqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I've been unable to reproduce this error using existing tests and with kvBatchSize=2 . It certainly slows down the tests but there are no test failures. I've changed the error message to return the new resume spans.
</details>
Hi Vivek,

I gave this some more thought. With the current KV implementtion, hitting this error is only possible if we have overlapping spans, right? This will never be the case - SQL should never send overlapping spans.

However, there is another condition that we are not checking for, and that is if we have unordered spans. 
Say we are doing an index join and the secondary index tells us that the rows we want from the primary index have PKs D, A, F. We would have spans something like D-E, A-B, F-G. We may receive row A, then row D, then row F. We get all the rows but they are in unexpected order - SQL relies on them being received in the initial order.

To check for this condition as well, we would need to set `readPartialResponse = true` for _any_ span that needs to be resumed, not just those with some results.

If it's hard for KV to return these in the batch order (even if there is no limit), it would be pretty easy to sort the spans in the SQL layer while remembering their order and then swap the received rows around. I can work on that if you think it's necessary (or if it makes the batch run more efficiently inside KV), and then the only cases we care about are for ordered, non-overlapping spans.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQmcLDKCKJpo4rKgA1O:b6brv6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Hi Vivek,
> 
> I gave this some more thought. With the current KV implementtion, hitting this error is only possible if we have overlapping spans, right? This will never be the case - SQL should never send overlapping spans.
> 
> However, there is another condition that we are not checking for, and that is if we have unordered spans. 
> Say we are doing an index join and the secondary index tells us that the rows we want from the primary index have PKs D, A, F. We would have spans something like D-E, A-B, F-G. We may receive row A, then row D, then row F. We get all the rows but they are in unexpected order - SQL relies on them being received in the initial order.
> 
> To check for this condition as well, we would need to set `readPartialResponse = true` for _any_ span that needs to be resumed, not just those with some results.
> 
> If it's hard for KV to return these in the batch order (even if there is no limit), it would be pretty easy to sort the spans in the SQL layer while remembering their order and then swap the received rows around. I can work on that if you think it's necessary (or if it makes the batch run more efficiently inside KV), and then the only cases we care about are for ordered, non-overlapping spans.
</details>
Radu, I think it's best for the sql layer to provide KV with sorted spans or else we would need to always check this in the KV layer. It's not too bad in the KV layer given that the check can be done in linear time. Even so, before we move forward on any of this I'd like us to write some SQL tests that break given the current implementation, so that we know what we are fixing. And hey, test driven development ain't bad. So let's write a test as mentioned above that breaks and create an issue. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Comment by RaduBerinde** [comment]
*[sql/sqlbase/kvfetcher.go, line 198 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967#-KQSGcAkZ8iCNwAcrw8G:-KQovBksBH3UVfWicddR:b-vf4kyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7db038ba109244cb28493e7da5e789dad0d6b875/sql/sqlbase/kvfetcher.go#L198)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Radu, I think it's best for the sql layer to provide KV with sorted spans or else we would need to always check this in the KV layer. It's not too bad in the KV layer given that the check can be done in linear time. Even so, before we move forward on any of this I'd like us to write some SQL tests that break given the current implementation, so that we know what we are fixing. And hey, test driven development ain't bad. So let's write a test as mentioned above that breaks and create an issue. Thanks!
</details>
I tried to reproduce and it seems that if the batch doesn't span ranges, we never get "unexpected" results. This makes it very hard to test that SQL doesn't break in certain cases. For example, there is no surprise this change passes all the logic tests even with a small kv batch size since the tests are small and won't span ranges.

To test this reliably, we would need a "stress test knob" that induces some of the "non-standard" results.

Anyway, here's a test that breaks with a kv batch size of 10: #9095

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8967)*

**Pull request merged**
