### PR TITLE
docs: clarify descriptions for tracing cluster settings

### PR DESCRIPTION
**Pull request by michae2**
The descriptions for sql.trace.txn.enable_threshold and
sql.trace.stmt.enable_threshold suggested that tracing was only enabled
for transactions and statements longer than the threshold duration. This
is not true, however: tracing is enabled for everything, and only
_logged_ for transactions and statements longer than the threshold
duration. Make this clear in the descriptions. Also make the description
for sql.trace.session_eventlog.enabled a "single" sentence to match the
style of other descriptions.

Release note: None

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @michae2)

___
*[`pkg/sql/exec_util.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81468#-N2Nht7F7skCu6LeHYmY:-N2Nht7F7skCu6LeHYmZ:b-gsdt9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f0ac27183a54340a4a03103961a3fa637acf47/pkg/sql/exec_util.go#L240)):*
> ```Go
> 	"sql.trace.stmt.enable_threshold",
> 	"enables tracing on all statements; statements executing for longer than "+
> 		"this duration will have their trace recorded (set to 0 to disable); "+
> ```

"recorded" means something else in the context of tracing. When this setting is active, all traces are recorded. Talk about logging.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @arulajmani)

___
*[`pkg/sql/exec_util.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81468#-N2Nht7F7skCu6LeHYmY:-N2NvWDS0oa1pcdXY3sD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8f0ac27183a54340a4a03103961a3fa637acf47/pkg/sql/exec_util.go#L240)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"recorded" means something else in the context of tracing. When this setting is active, all traces are recorded. Talk about logging.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81468#-:-N2O5NxH4HQR0FW99fGf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @michae2)

___
*[`pkg/sql/exec_util.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81468#-N2O5Ema4e1cV8A3yqgj:-N2O5Ema4e1cV8A3yqgk:b-o97f27) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5abdd90729b542fa72731523952bd8a26aa7d67/pkg/sql/exec_util.go#L226)):*
> ```Go
> 	"enables tracing on all transactions; transactions open for longer than "+
> 		"this duration will have their trace logged (set to 0 to disable); "+
> 		"note that enabling this may have a non-trivial negative performance "+
> ```

nit: I'd strike "non-trivial"

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @arulajmani)

___
*[`pkg/sql/exec_util.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81468#-N2O5Ema4e1cV8A3yqgj:-N2O93ki4dNeJn35Ud7h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5abdd90729b542fa72731523952bd8a26aa7d67/pkg/sql/exec_util.go#L226)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I'd strike "non-trivial"
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
Thanks for making this change so quick!

**Pull request merged**
