### PR TITLE
roachtest: tpcc with chaos

### PR DESCRIPTION
**Pull request by tbg**
This is an attempt to reproduce #28918.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
@andreimatei is this approximately what you're doing? Think I should be restarting more than one node?

**Comment by tschottdorf** [comment]
@benesch please poach whatever you want from this PR (probably not much) and close it at your convenience, thanks.

**Comment by benesch** [comment]
Ack. This is next in my queue.

**Comment by tschottdorf** [comment]
@benesch this is ready for a look.

**Review by benesch — APPROVED** [review]
:lgtm: sorry I lost track of this. All nits are totally optional.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29332#-:-LNsF1u20r3d2vRUPex8:b6ibbnh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29332#-LNsEcYj-M7w_9g8j10x:-LNsEcYj-M7w_9g8j10y:b-dnqin5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90d6c9ae1cfd622a5e11fc4202a3e4577cfa4a0/pkg/cmd/roachtest/tpcc.go#L43)):*
> ```Go
> 	Chaos      func() Chaos // for late binding of stopper
> 	Duration   time.Duration
> 	Zfs        bool
> ```

nit: `ZFS` is conventional capitalization, no?
___
*[pkg/cmd/roachtest/tpcc.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29332#-LNsFCsRAAVlbq3ROpzu:-LNsFCsRAAVlbq3ROpzv:b97l2i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90d6c9ae1cfd622a5e11fc4202a3e4577cfa4a0/pkg/cmd/roachtest/tpcc.go#L148)):*
> ```Go
> 
> 	r.Add(testSpec{
> 		Name:   "tpccchaos/w=100/nodes=3",
> ```

nit: why isn't the naming scheme `chaos=<true|false>`

**Review by tbg — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29332#-:-LNtA45Y3irXbowchlHS:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29332#-LNsFCsRAAVlbq3ROpzu:-LNt9w2lALVC6sA95g7Y:bx4ycp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90d6c9ae1cfd622a5e11fc4202a3e4577cfa4a0/pkg/cmd/roachtest/tpcc.go#L148)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: why isn't the naming scheme `chaos=<true|false>`
</blockquote></details>

I didn't want to rename the existing tests because someone surely relies on them. I made this `tpcc/w=100/nodes=3/chaos=true` but left everything else alone.

**Comment by tschottdorf** [comment]
bors r=benesch

**Pull request merged**
