### PR TITLE
deps: bump github.com/shirou/gopsutil

### LINKED ISSUE #51142: deps: error in gopsutil breaks build on FreeBSD
```
# github.com/shirou/gopsutil/disk
vendor/github.com/shirou/gopsutil/disk/disk_freebsd.go:195:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
```

this is new since the dep was bumped

### PR DESCRIPTION
**Pull request by knz**
Fixes #51142.

This imports a bunch of bug fixes, drops an unnecessary dependency,
and fixes the build on FreeBSD.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
cc @bdarnell to review the upstream changes

**Comment by knz** [comment]
@tbg @bdarnell also, since gopsutil seems to have so much functionality, wouldn't it make sense to drop hashicorp's gosigar and just use gopsutil directly?

**Comment by bdarnell** [comment]
The upstream diff is thousands of lines; too much for me to review.

As for switching, that was Pete V's plan when he introduced gopsutil (still on a checklist in #27085). See also some concerns about gopsutil in #31374; we should make sure that all of those are fixed before we switch.

**Comment by knz** [comment]
@otan what was the command to list the intermediate commits with hyperlinks to the diffs? to ease review.

**Comment by knz** [comment]
@bobvawter could you inspect casually the code of gopsutil and see if it has more advanced logic to detect available cores in k8s? If it does, that will give us one more incentive to replace our current detection logic by what gopsutil provides.

**Comment by bobvawter** [comment]
@knz I'm looking at taking care of this from the k8s side.  The cores/memory resource limits are available through the "downward" API, so I think there's a way to refit our yaml to pass this data via `GOMAXPROCS` and to set the cache sizes appropriately.

**Comment by otan** [comment]
@knz i made my own (https://github.com/otan-cockroach/otan-scripts/tree/master/gomodupdate), which was purpose built for Gopkg.lock vs vendor/modules.txt.

Judging by modules.txt though, not much in terms of packages has actually changed

**Comment by knz** [comment]
@otan my request is specifically to get the list of commits+diffs for the 1 updated package here (gopsutil)

**Comment by otan** [comment]
ah i just took the difference between the two SHAs, i.e. between v2.18.12 vs v2.20.6: http://github.com/shirou/gopsutil/compare/ccc1c1016bc5d10e803189ee43417c50cdde7f1b...10a398abdd2d49a0905dae63644eb0cafc2006e2

**Comment by knz** [comment]
@otan thanks!

@bdarnell ok let's try to be structured about this.

The patch changes many files, but the changes are neatly partitioned between the various targets.
Since we only support Linux in production, and Darwin for development, we can focus the review on this and ignore the other changes (I'll take charge of reviewing the FreeBSD parts).
This restricts the review to the following:

- Common:

  - [ ] [internal/common/common.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-384c781828ebaeef6d125bbd648de33e)

  - [ ] [cpu/cpu.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-d5b0ee6bbe2c5106d822972bd7d1b62b)
  - [ ] [cpu/cpu_fallback.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-db539d76d9b66637068a05ada6e2ae5c)
  - [ ] [host/host_posix.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-f0b0c74fc6b8e6322ddab72bcad24b52)

  - [ ] [net/net.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-14d9f56522a21392ed0808cf8eeab722)
  - [ ] [net/net_fallback.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-e0dc2f1fdc8b05d4bc808cfe69c23adb)
  - [ ] [net/net_unix.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-010a41f5915c90c3e3192eaf8d5bb752)  

  - [ ] [process/process.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-09cd0515dc6549de790249786c11ccdd)
  - [ ] [process/process_posix.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-c2e296caaae8ef6296404530c321d2ef)


- Linux:

  - [ ] [internal/common/common_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-7348ec63bd4ab9ba728776e7fd662d87)

  - [ ] [host/host_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-416f97d66804c0d621bf3b0b257db2c0)

  - [ ] [cpu/cpu_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-b5bbf1360c17a5412f6bb09a816f356d)

  - [ ] [disk/disk_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-aee17de3987ca34b62317464cbb41de9)

  - [ ] [load/load_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-b093ef74a191b380201b7d58c268842e)

  - [ ] [mem/mem_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-07d4fa88a5f1eab1992b295acc21465f)

  - [ ] [net/net_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-b38c1d57a476f4c1ad76ac32a6b8b3fe)

  - [ ] [process/process_linux.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-7152f29bacf7944776481ecf6c475816)

- Darwin:

  - [ ] [internal/common/common_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-b21011cfe4c7eb224ef790d6faa58802)

  - [ ] [host/host_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-d90a862ae1a599d2c44d83cc1b247680)
  - [ ] [host/host_darwin_cgo.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-592cc8a47fb6c617dcb9f2de129ecb39)
  - [ ] [host/host_darwin_nocgo.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-10334f82b8097dc3b6b777264f3b5ec7)
  - [ ] [host/smc_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-10d0cc8528d821c60fd42bf67aee6c60)
  - [ ] [host/smc_darwin.h](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-e261e3eae6529bee1d54ff5ee2143594)

  - [ ] [cpu/cpu_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-195bc9c867ae9f77490a8679eefdc695)

  - [ ] [disk/disk_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-777e00dab9a51728b212051e398f9456)
  - [ ] [disk/disk_darwin_cgo.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-1d0d6c5cc77e366351443794178f76eb)
  - [ ] [disk/iostat_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-86632743c840246fdb145c670babbcf5)
  - [ ] [disk/iostat_darwin.h](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-a9292cc4d240df44a9b1f8180962aee0)

  - [ ] [load/load_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-2c3089ebdbfe319cfff0a84927c53293)

  - [ ] [mem/mem_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-df296849899313a471ebac0892657962)

  - [ ] [net/net_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-770ee2d3fae47ff085cbf4dea35919c4)

  - [ ] [process/process_darwin.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-2309a6d19d50739a78762a2baf186e0b)
  - [ ] [process/process_darwin_cgo.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-c44767783cce356af3ac206ebe796afe)
  - [ ] [process/process_darwin_nocgo.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-c4cf7d2055b0d0f66c07fdcb70be04df)

- Windows:

  - [ ] [internal/common/common_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-26ea2a9f3f1e1bb1ed190a3627bb5a0c)

  - [ ] [cpu/cpu_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-5dd88ed487fca52c1846d723dae66e33)

  - [ ] [disk/disk_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-a08212f0a22b4e215620a829dc81d62f)

  - [ ] [host/host_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-9b37a7d450ebb7728d5bd285375eb8a4)

  - [ ] [net/net_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-e97ac4965f404631d75a5adf912d9d9c)

  - [ ] [process/process_windows.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-81206e3adf42b9269185df32e17bc9a1)
  - [ ] [process/process_windows_amd64.go](https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-a5c5157a9c0ecc1325bbe68749917f67)

**Comment by knz** [comment]
I could review the linux bits and you do the Darwin bits? Or maybe you do process and disk, and I do host and net? 

(We can also leave Windows alone - and let users discover any issues, since we don't fully support it in production anyway)

**Comment by knz** [comment]
I'm crossing out cpu/cpu.go, but I'm curious what you think of this specific line:
https://github.com/cockroachdb/vendored/compare/a591d5f1cf40aa524a0feaa9f92e91ed1c28ee21...e9c4618dddd6ae5b47a406def133f348c98ff805#diff-d5b0ee6bbe2c5106d822972bd7d1b62bR115

**Comment by knz** [comment]
> See also some concerns about gopsutil in #31374; we should make sure that all of those are fixed before we switch.

- the upstream issue that was filed https://github.com/shirou/gopsutil/issues/560 has been fixed.

- `cpu_darwin_cgo.go` is not altered in this diff, so the suspicious vm_deallocate remains; however, as Tobias points out, gosigar uses the same code so either we already have a bug there (and this PR doesn't change anything); or we are not using this code (and this PR does not change anything).

- `mem_darwin_cgo.go` is not altered in this diff, so the possibly missing deallocation is still missing.

In light of this, I would agree that it's still too early to switch from gopsutil to gosigar. However, I think we should still bump the dependency.

**Comment by knz** [comment]
Here's the actual APIs used currently in CockroachDB:

- `status/disk_counters.go`, **linux-only**: `disk.IOCountersWithContext()`

  (Darwin uses a different `iostat.ReadDriveStats()` from github.com/lufia/iostat.)

- `status/runtime.go`, `net.IOCountersWithContext()`
- `server/updates.go` (telemetry):
  - `cpu.InfoWithContext()`
  - `host.PlatformInformation()`
  - `host.Virtualization()`
  - `load.AvgWithContext()`
  - `mem.VirtualMemory()`

That's all - and it therefore completely reduces the scope of the review. I'll check off all the non-relevant files.

**Comment by bdarnell** [comment]
> I'm crossing out cpu/cpu.go, but I'm curious what you think of this specific line:

That link is dead, but I didn't see anything that caught my eye in cpu.go.

The remaining unchecked files look fine after a cursory review.

**Review by bdarnell — APPROVED** [review]

**Comment by knz** [comment]
Thanks

bors r=bdarnell

**Comment by knz** [comment]
Spurious agent timeout

bors r=bdarnell

**Pull request merged**
