### PR TITLE
deps: bump datadriven

### PR DESCRIPTION
**Pull request by knz**
To pick up bug fixes and improvements.

Release note: none

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by knz** [comment]
tfyr!

bors r+

**Comment by knz** [comment]
Will need to pick up https://github.com/cockroachdb/datadriven/pull/5 to fix

**Comment by knz** [comment]
done

bors r+

**Comment by knz** [comment]
:game_die: 

bors r+

**Comment by knz** [comment]
dang now it's the CLA assistant that's unhappy

**Pull request merged**
