### PR TITLE
server: include scrubbed appstats in diagnostics info sharing

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by BramGruneir** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates_test.go, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqByt6612HnvxuJ_v5:-KiqByt6612HnvxuJ_v6:by36hto) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/server/updates_test.go#L144)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 	}
> ```

obviously, these stats should be checked later on.  Would this whole test be better suited  as an example instead of a test?

---

*[pkg/sql/app_stats.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqCkbkIXPOQMJPjRoz:-KiqCkbkIXPOQMJPjRp-:bum9sun) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L305)):*
> ```Go
> 	ret := make(map[string]map[string]StatementStatistics)
> 	vt := e.virtualSchemas
> 	e.sqlStats.Lock()
> ```

Why not defer the unlock?  Or are we moving away from that pattern?

---

*[pkg/sql/app_stats.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqCZeYcNw3btgQLbo3:-KiqCZeYcNw3btgQLbo4:bhkce0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L313)):*
> ```Go
> 			if ok {
> 				stats.Lock()
> 				m[scrubbed] = stats.data
> ```

I think this would be a lot cleaner (with less chance of missing a lock) if there was a getData accessor that did the locking automatically.  But that's just a nit.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by benesch** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/app_stats.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqRFgjEuy0R1UexsLc:-KiqRFgjEuy0R1UexsLd:b-bs24pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L302)):*
> ```Go
> }
> 
> func (e *Executor) GetScrubedStmtStats() map[string]map[string]StatementStatistics {
> ```

I think you want `Scrubbed`!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/app_stats.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqS5biRaZoguut6-se:-KiqS5bjbCNSZahIOSG8:be485zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L302)):*
> ```Go
> }
> 
> func (e *Executor) GetScrubedStmtStats() map[string]map[string]StatementStatistics {
> ```

Also, doesn't this need a comment? An explanation of this map type would be quite helpful for my little monkey brain. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by knz** [comment]
the fix for create scrubbing is merged, you can rebase.
(Although you also probably want to wait until #15503 has merged to rebase)

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates_test.go, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqByt6612HnvxuJ_v5:-KityRrODKfYzl_n2n32:bw3xiwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/server/updates_test.go#L144)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

obviously, these stats should be checked later on.  Would this whole test be better suited  as an example instead of a test?
</blockquote></details>

Well, they are collected timings, so we can't quite do an example test as we don't know their values, but we can assert that individual keys appear and have >0 values.

---

*[pkg/sql/app_stats.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqRFgjEuy0R1UexsLc:-KittzR2ZeiMMQ09Date:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L302)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you want `Scrubbed`!
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqS5biRaZoguut6-se:-KitvWCPOg3Nr_qBYhgA:bl2d0qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L302)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Also, doesn't this need a comment? An explanation of this map type would be quite helpful for my little monkey brain. 
</blockquote></details>

Yep, sorry, this type deserves a descriptive alias on which we can throw a comment too. 

---

*[pkg/sql/app_stats.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqCkbkIXPOQMJPjRoz:-KittdLIE-jXs7KyDPMZ:bqoqe4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L305)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not defer the unlock?  Or are we moving away from that pattern?
</blockquote></details>

there are no early/conditional returns to benefit from it, plus the locks inside the loop want be released within the loop body, so I'd rather not have some deferred and some not.

---

*[pkg/sql/app_stats.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqCZeYcNw3btgQLbo3:-KittvTEw8FPiDOaRah4:b1bh3g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L313)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think this would be a lot cleaner (with less chance of missing a lock) if there was a getData accessor that did the locking automatically.  But that's just a nit.  
</blockquote></details>

similar to above: given the that we're explicitly handling the intermediate locks, i'd rather just take responsibility for all of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by dt** [comment]
@bram okay, added tests that assert the expected queries are in the report.

@knz looked like the scrubber was unhappy with the `!` and `+` flag prefixes -- I probably could have just used the string splitting helper, but ended up switching to using a real struct to keep the structured data separate end-to-end.

**Comment by tamird** [comment]
Looks good to me, but I'm not the authority on this by any means.

---

Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuZb87aqjjzUObG3i7:-KiuZb88AvWEAuoVj0A0:b-i0tvso) ([raw file](https://github.com/cockroachdb/cockroach/blob/3baca08155d9c9b4bb3a300284e7b46d13b737ed/pkg/server/updates.go#L91)):*
> ```Go
> 	Stores     []storeInfo                                   `json:"stores"`
> 	Schema     []sqlbase.TableDescriptor                     `json:"schema"`
> 	QueryStats map[string]map[string]sql.StatementStatistics `json:"sqlstats"`
> ```

apologies for the drive-by: is there any reason for these json struct tags? I'm thinking you could name this field `SQLStats` and then remove all the struct tags.

---

*[pkg/server/updates.go, line 261 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuxGPCrD-Y7T-6187V:-KiuxGPD7SL55aQOefJF:bmgj3yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates.go#L261)):*
> ```Go
> 	}
> 
> 	// TODO(dt): Reporting loop should own the resetting collected stats too.
> ```

did you mean to write "own resetting the collected stats"?

---

*[pkg/server/updates_test.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiv-OzvOU1SwsBfqoJA:-Kiv-OzvOU1SwsBfqoJB:b-rfreor) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates_test.go#L145)):*
> ```Go
> 	for i := 0; i < 10; i++ {
> 		for _, q := range []string{
> 			`SELECT * FROM %[1]s.%[1]s WHERE %[1]s = 1 AND '%[1]s' = '%[1]s'`,
> ```

Can you add a comment explaining why this doesn't use placeholders? I think there are two reasons:
- not all positions support them
- each placeholder has a single type, so you couldn't use $1 everywhere

But I could be missing something.

---

*[pkg/sql/app_stats.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiqCZeYcNw3btgQLbo3:-Kiv-6BAqTtszH8QH7Ky:b-r4n6dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51f8f5cb4e58de850d1f18afb8d141fbcb92bb0/pkg/sql/app_stats.go#L313)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

similar to above: given the that we're explicitly handling the intermediate locks, i'd rather just take responsibility for all of them.
</blockquote></details>

+1 to the current inline locking.

---

*[pkg/sql/app_stats.go, line 27 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuxNwimhiIYn473iLw:-KiuxNwimhiIYn473iLx:b-7c6htt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L27)):*
> ```Go
> 	"golang.org/x/net/context"
> 
> 	"crypto/sha512"
> ```

nit: group with other stdlib imports

---

*[pkg/sql/app_stats.go, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz-DgP4mWU9cLI-Pe:-Kiuz-DgP4mWU9cLI-Pf:b-x4nh9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L39)):*
> ```Go
> type stmtKey struct {
> 	stmt        string
> 	err         bool
> ```

can this be `isErr`, or something, so it's clear that it's not an error?

---

*[pkg/sql/app_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz8_REQsIYmh4eSgo:-Kiuz8_REQsIYmh4eSgp:bkr0e52) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L76)):*
> ```Go
> 
> func (s stmtKey) flags() string {
> 	if s.err && s.distSQLUsed {
> ```

Is this allocation sensitive? If not, you can avoid repeating yourself with a simpler construction:
```
var b bytes.Buffer
if s.err {
  b.WriteByte('!')
}
if s.distSQLUsed {
  b.WriteByte('+')
}
return b.String()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-:-Kiv-rNjel1mkilgv9bG:b-1xh23w)*

**Comment by knz** [comment]
There are a couple of polishing touches remaining, then it's good to go

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates_test.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiv-OzvOU1SwsBfqoJA:-KizN3IEVCPCSAAjphlN:bsrutbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates_test.go#L145)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Can you add a comment explaining why this doesn't use placeholders? I think there are two reasons:
- not all positions support them
- each placeholder has a single type, so you couldn't use $1 everywhere

But I could be missing something.
</blockquote></details>

+1 on the comment

also I would suggest *also* using some queries with placeholders.
Since we do now support inline prepare/exec, you can do `db.Exec(`PREPARE ....`)` and have the `PREPARE` queries in the same string array above.

---

*[pkg/sql/app_stats.go, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz-DgP4mWU9cLI-Pe:-KizLiO_e_31Kepizmpw:b-2332np) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can this be `isErr`, or something, so it's clear that it's not an error?
</blockquote></details>

I'd even go for `failed`

---

*[pkg/sql/app_stats.go, line 47 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KizLloIwGVZ_wvIyLW1:-KizLloIwGVZ_wvIyLW2:bfuioq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L47)):*
> ```Go
> 	syncutil.Mutex
> 
> 	stmts map[stmtKey]*stmtStats
> ```

:100: I didn't know you could use a struct as key. Yes, this is the better approach.

---

*[pkg/sql/app_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz8_REQsIYmh4eSgo:-KizLttAuSyNk0fRIRi2:b-h8qdck) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Is this allocation sensitive? If not, you can avoid repeating yourself with a simpler construction:
```
var b bytes.Buffer
if s.err {
  b.WriteByte('!')
}
if s.distSQLUsed {
  b.WriteByte('+')
}
return b.String()
```
</blockquote></details>

yeah this approach would be better as we could end up with more flags in the future.

---

*[pkg/sql/app_stats.go, line 344 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KizMHnR3iTI-Lv9H2Xr:-KizMHnTCnkc-AKWYO8K:bcjn6fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L344)):*
> ```Go
> // HashAppName 1-way hashes an application names for use in stat reporting.
> func HashAppName(appName string) string {
> 	hash := sha512.Sum512([]byte(appName))
> ```

sha512 is overkill (expensive in time and space) - just go for fnv https://golang.org/pkg/hash/fnv/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-:-KizNMbSSj-bOb0o79gD:b-8w5bp9)*

**Comment by dt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 91 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuZb87aqjjzUObG3i7:-Kj3yxU6uLW0n3IwkLix:b-5y20ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/3baca08155d9c9b4bb3a300284e7b46d13b737ed/pkg/server/updates.go#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

apologies for the drive-by: is there any reason for these json struct tags? I'm thinking you could name this field `SQLStats` and then remove all the struct tags.
</blockquote></details>

Eh, I prefer the explicit names, since we're serializing for an external API -- I generally assume an var name is safe to change as long as it compiles, and I'd rather not have that cause externally observable changes in behavior.

---

*[pkg/server/updates.go, line 261 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuxGPCrD-Y7T-6187V:-Kj4-68SQ--V_gzE31CF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates.go#L261)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

did you mean to write "own resetting the collected stats"?
</blockquote></details>

Done.

---

*[pkg/server/updates_test.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiv-OzvOU1SwsBfqoJA:-Kj40oH5CXHTyfJ-ryFs:b5bn1bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates_test.go#L145)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

+1 on the comment

also I would suggest *also* using some queries with placeholders.
Since we do now support inline prepare/exec, you can do `db.Exec(`PREPARE ....`)` and have the `PREPARE` queries in the same string array above.
</blockquote></details>

Done.

I think I found something strange in printer for `VALUES` AST nodes, but that doesn't need to go in to this change.

---

*[pkg/sql/app_stats.go, line 27 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KiuxNwimhiIYn473iLw:-Kj49rzNx3S5P2R34LFx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: group with other stdlib imports
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 39 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz-DgP4mWU9cLI-Pe:-Kj414FSyQDMO49np87Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd even go for `failed`
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 76 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiuz8_REQsIYmh4eSgo:-Kj40uLPRsQcItC6jDjJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah this approach would be better as we could end up with more flags in the future.
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 344 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-KizMHnR3iTI-Lv9H2Xr:-Kj49ok5OZIKH-el12aG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/sql/app_stats.go#L344)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sha512 is overkill (expensive in time and space) - just go for fnv https://golang.org/pkg/hash/fnv/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates_test.go, line 153 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4DLWWrpVOjUnP1I13:-Kj4DLWWrpVOjUnP1I14:b-3bttwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/server/updates_test.go#L153)):*
> ```Go
> 			}
> 		}
> 		// These don't use placeholders, as they are not allowed in some positions.
> ```

* some of these could use placeholders, like the various RHS expressions, right? This is similar to what you did above, so I'm left wondering about the inconsistency.

* could you document the positions in which placeholders are not allowed? that would help future good samaritans to clean this up if they were so inclined. (this one is optional)

---

*[pkg/sql/app_stats.go, line 342 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4CzHMUIEbOWUBP2RQ:-Kj4CzHMUIEbOWUBP2RR:b-eeh2wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/sql/app_stats.go#L342)):*
> ```Go
> func HashAppName(appName string) string {
> 	hash := fnv.New64a()
> 	// https://golang.org/pkg/hash: "It never returns an error."
> ```

In the service of setting precedent, consider checking this error anyway, and using this comment to justify a call to `panic`.

Optional.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by dt** [comment]
Review status: 2 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/server/updates_test.go, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kiv-OzvOU1SwsBfqoJA:-Kj4I8i4zzZE4kxcs1fe:b-r6ezl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa26a7d01d2d450634bdb720ea8b6da1222bd9e2/pkg/server/updates_test.go#L145)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.

I think I found something strange in printer for `VALUES` AST nodes, but that doesn't need to go in to this change.
</blockquote></details>

nvm, apparently the VALUES collapsing is working as (un)expected.

---

*[pkg/server/updates_test.go, line 153 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4DLWWrpVOjUnP1I13:-Kj4ElXMUK3JaL3Mu_d4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/server/updates_test.go#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

* some of these could use placeholders, like the various RHS expressions, right? This is similar to what you did above, so I'm left wondering about the inconsistency.

* could you document the positions in which placeholders are not allowed? that would help future good samaritans to clean this up if they were so inclined. (this one is optional)
</blockquote></details>

Done.

---

*[pkg/sql/app_stats.go, line 342 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4CzHMUIEbOWUBP2RQ:-Kj4EarTHlP4JZX6kxct:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/sql/app_stats.go#L342)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

In the service of setting precedent, consider checking this error anyway, and using this comment to justify a call to `panic`.

Optional.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates_test.go, line 153 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4DLWWrpVOjUnP1I13:-Kj4JfAA0Ihc5L4_zmYl:b-9cz7au) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/server/updates_test.go#L153)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, I see - this is testing that literal strings are also sanitized. Scratched my head for a moment.

---

*[pkg/sql/app_stats.go, line 342 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4CzHMUIEbOWUBP2RQ:-Kj4JJCpj3MSZ3tTjRx5:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/298e4488445571684d9a44105965073d4febef08/pkg/sql/app_stats.go#L342)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by dt** [comment]
TFTRs!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-:-Kj4L5v1CUYqsBSVv5wJ:bz5mair)*

**Comment by knz** [comment]
Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates_test.go, line 144 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4OZsM9xi8cZReilzQ:-Kj4OZsM9xi8cZReilzR:b-8bhodn) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/server/updates_test.go#L144)):*
> ```Go
> 	// Run some queries so we have some query statistics collected.
> 	for i := 0; i < 10; i++ {
> 		// Run some sameple queries. Each are passed a string and int by Exec.
> ```

"sameple" -> sample

---

*[pkg/server/updates_test.go, line 150 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4P1Z6s0mGmUnChVIg:-Kj4P1Z7w3patJq0qCpr:b-p0vpcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/server/updates_test.go#L150)):*
> ```Go
> 			`INSERT INTO %[1]s.%[1]s VALUES (length($1::string)), ($2)`,
> 		} {
> 			if _, err := db.Exec(fmt.Sprintf(q, elemName), elemName, 10003); err != nil {
> ```

Are you sure that the `db.Exec` interface does actually use the prepare API when using a test server? I can't see this clearly in the code.
That's why I was suggesting an explicit `PREPARE a AS ...; EXECUTE a(...); RELEASE a` in your common query strings below.

---

*[pkg/sql/testdata/logic_test/statement_statistics, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4Pdw0SM6tI0MKnV2u:-Kj4Pdw1-ez1QiDbhpQE:bhc90bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/sql/testdata/logic_test/statement_statistics#L26)):*
> ```
> SET application_name = ''
> 
> query TB valuesort
> ```

I checked in the TestLogic code and no, `value` sort is most likely the incorrect approach here.
What's the ordering problem precisely? 
I think that the correct approach is now `ORDER BY key, flags` since I split off the flags field in f37413aeb6399fd316d02f6e6d6fbc80d1ae7118.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-:-Kj4UPSTQSApLsIIcV9q:bnfp4nl)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates_test.go, line 144 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4OZsM9xi8cZReilzQ:-Kj4Ti2NUJgRY_-i987z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/server/updates_test.go#L144)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"sameple" -> sample
</blockquote></details>

Done.

---

*[pkg/server/updates_test.go, line 150 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4P1Z6s0mGmUnChVIg:-Kj4TiPjifPa7q8BOi0R:b-gn2fg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/server/updates_test.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure that the `db.Exec` interface does actually use the prepare API when using a test server? I can't see this clearly in the code.
That's why I was suggesting an explicit `PREPARE a AS ...; EXECUTE a(...); RELEASE a` in your common query strings below.

</blockquote></details>

Ah, gotcha. `Exec`with >0 args uses the pgwire prepare API, not the `PREPARE` syntax, to prepare the query before executing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/statement_statistics, line 26 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491#-Kj4Pdw0SM6tI0MKnV2u:-Kj4bAU_Q4F9dO4tul-R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ef36f024dab9f764fa56ab4b80450052226960/pkg/sql/testdata/logic_test/statement_statistics#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I checked in the TestLogic code and no, `value` sort is most likely the incorrect approach here.
What's the ordering problem precisely? 
I think that the correct approach is now `ORDER BY key, flags` since I split off the flags field in f37413aeb6399fd316d02f6e6d6fbc80d1ae7118.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15491)*

**Pull request merged**
