### PR TITLE
remove the "comparison with other databases" image

### PR DESCRIPTION
**Pull request by jess-edwards**
Replace the "comparison with other databases" image with a link to the comparison page on our docs site. The comparison page on the docs site is better maintained and has the benefit of being searchable.

PTAL: @bdarnell @jseldess @dianasaur323

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13450)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

The original image was more about introducing the SQL/NoSQL/NewSQL progression than comparisons with specific products, so this shifts the focus a bit. I don't think we have a page we can link to for that currently but we may want to add on and point this link there. (or maybe not. I'm not sure what we really want for this part of the readme)

**Comment by dianasaur323** [comment]
Agree with Ben that we might want to have content somewhere explaining SQL/NoSQL/NewSQL. My opinion is that we don't need this to sit in the readme, and we can consider adding a page on this further down the road. Spencer's next blog post will be related to this topic, so we can explore how to surface this topic then. For now, LGTM.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13450#-:-KcOIN8fQzInC59ZbfMQ:b624jaf)*

**Comment by knz** [comment]
LGTM, same comments as Ben

**Comment by tamird** [comment]
If we're removing this image from the readme, we should also remove the image file.

**Comment by jess-edwards** [comment]
@tamird Agreed. Removed on #13456

@bdarnell, @knz, @dianasaur323 
I will discuss with @sploiselle & @jseldess how best to include the NewSQL, NoSQL, and SQL definitions.

**Pull request merged**
