### PR TITLE
sql: include all schemas into schema.sql in the bundle

### LINKED ISSUE #91099: sql: fix statement bundle recreate with non-default schema
Currently, if a statement bundle is collected while using a non-default db, we won't be able to recreate it via `debug statement-bundle recreate` without manually modifying the schema (and possibly the statement). This is the case because we put fully-qualified table names into `schema.sql`, yet we don't recreate the database nor the schema of those objects. We could either teach the recreate command to handle such errors, or (which is better) include the SQL statements to create the necessary objects into `schema.sql` right away.

Jira issue: CRDB-21105

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that all schemas are added into the `schema.sql` file of the statement bundle using `SHOW CREATE ALL SCHEMAS;` statement (the only exception is the public schema that always exists in CRDB clusters). This will make it more likely that `debug statement-bundle recreate` succeeds on the bundles.

Fixes: #91099.

Epic: CRDB-14510

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-:-NFzfmqa0S-kyKFdoKS4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

**Review by michae2 — COMMENTED** [review]
Thank you for doing this!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-:-NFzgTud6eKVyG6Yh9_6:bff479j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/explain_bundle.go` line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-NFzgBMVBDgV2cpJ0Owf:-NFzgBMVBDgV2cpJ0Owg:b-cq1ls0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3917afa7e918f5cc0af58f9b50ba104ee052fd5/pkg/sql/explain_bundle.go#L494)):*
> ```Go
> 	rows, err := c.ie.QueryBufferedEx(
> 		c.ctx,
> 		"stmtEnvCollector",
> ```

Could we use a more descriptive name? Maybe something about the current statement bundle?
___
*[`pkg/sql/explain_bundle.go` line 738 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-NFzfWVQ827NuzPfrs9h:-NFzfWVQ827NuzPfrs9i:bso44ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3917afa7e918f5cc0af58f9b50ba104ee052fd5/pkg/sql/explain_bundle.go#L738)):*
> ```Go
> 	}
> 	for _, r := range createAllSchemas {
> 		if strings.HasPrefix(r, "CREATE SCHEMA "+catconstants.PublicSchemaName) {
> ```

Will this work if someone has a schema starting with "public", like `CREATE SCHEMA publicfoo`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91245)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @michae2)

___
*[`pkg/sql/explain_bundle.go` line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-NFzgBMVBDgV2cpJ0Owf:-NG2eGHM3rmrC2FPFqY0:b7dypwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3917afa7e918f5cc0af58f9b50ba104ee052fd5/pkg/sql/explain_bundle.go#L494)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Could we use a more descriptive name? Maybe something about the current statement bundle?
</blockquote></details>

It doesn't seem that important (it would only show up as a log tag), and I'd also like it to keep it for consistency with `query()` method. I guess places that use `query()` method can also be invoked during `EXPLAIN (OPT, ENV)` and that's why the opName is not very descriptive there, but the schemas are only used for the bundle.
___
*[`pkg/sql/explain_bundle.go` line 738 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-NFzfWVQ827NuzPfrs9h:-NG2eAoU9PXUxpWUN4bk:bdk9f9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3917afa7e918f5cc0af58f9b50ba104ee052fd5/pkg/sql/explain_bundle.go#L738)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Will this work if someone has a schema starting with "public", like `CREATE SCHEMA publicfoo`?
</blockquote></details>

Good point, made it an exact comparison.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-:-NG2gCRI6aHTwyIqCuqQ:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

___
*[`pkg/sql/explain_bundle.go` line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91245#-NFzgBMVBDgV2cpJ0Owf:-NG2g4Vn3aJYWX2osS0e:b-c1654y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3917afa7e918f5cc0af58f9b50ba104ee052fd5/pkg/sql/explain_bundle.go#L494)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It doesn't seem that important (it would only show up as a log tag), and I'd also like it to keep it for consistency with `query()` method. I guess places that use `query()` method can also be invoked during `EXPLAIN (OPT, ENV)` and that's why the opName is not very descriptive there, but the schemas are only used for the bundle.
</blockquote></details>

I see. That's fine, thanks for checking it out!

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
