### PR TITLE
sql: fix CREATE TABLE AS schema change job description

### LINKED ISSUE #107364: sql: CREATE TABLE AS schema change job has invalid description
The schema change job triggered by `CREATE TABLE AS` has a job description with invalid SQL.

**Repro steps**

```
demo@127.0.0.1:26257/demoapp/movr> CREATE TABLE t (id int PRIMARY KEY);                                                                                                                                                                  
CREATE TABLE

demo@127.0.0.1:26257/demoapp/movr> CREATE TABLE t2 AS SELECT * FROM t;                                                                                                                                                                   
CREATE TABLE AS

demo@127.0.0.1:26257/demoapp/movr> SELECT description                                                                                                                                                                                    
                                -> FROM [SHOW JOBS]                                                                                                                                                                                      
                                -> WHERE description LIKE '%t2%';                                                                                                                                                                        
                              description
------------------------------------------------------------------------
  CREATE TABLE movr.public.t2 (id INT8) AS SELECT * FROM movr.public.t
(1 row)

demo@127.0.0.1:26257/demoapp/movr> CREATE TABLE movr.public.t2 (id INT8) AS SELECT * FROM movr.public.t;                                                                                                                                 
ERROR: statement ignored: at or near "as": syntax error
SQLSTATE: 42601
```

**RCA**

`ColumnTableDef.Format` is incorrectly including the column type when part of a `CREATE TABLE AS` statement here
https://github.com/cockroachdb/cockroach/blob/e15b5bcc9255bd48ad950edc61f0084f99e7d006/pkg/sql/sem/tree/create.go#L757

Even though the AST created by the parser does not initially contain a `ColumnTableDef.Type`, the type is populated later on in these places:
- https://github.com/cockroachdb/cockroach/blob/e15b5bcc9255bd48ad950edc61f0084f99e7d006/pkg/sql/create_table.go#L1203
- https://github.com/cockroachdb/cockroach/blob/e15b5bcc9255bd48ad950edc61f0084f99e7d006/pkg/sql/create_table.go#L1216

Jira issue: CRDB-30010

Epic CRDB-27601

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #107364

This changes the CREATE TABLE AS schema change job description to no longer incorrectly
include column types.
For example
`CREATE TABLE movr.public.t2 (id INT8) AS SELECT * FROM movr.public.t;`
becomes
`CREATE TABLE movr.public.t2 (id) AS SELECT * FROM movr.public.t;`

Release note (bug fix): Fix CREATE TABLE AS schema change job description SQL syntax.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tX_t1105zUn08bv4x):*
What happened to the commit message?
___
*[`pkg/sql/delegate/show_function.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tZ7th4OPstBJjW1GE:-N_tZ7th4OPstBJjW1GF:b-75nppw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f179c381ed59b5d9dea21dc29a90d8c5c1ec4f9/pkg/sql/delegate/show_function.go#L52)):*
> ```Go
> 		if o.IsUDF {
> 			udfSchema = o.Schema
> 			break
> ```

Should we have some test coverage for this scenario?
___
*[`pkg/sql/create_as_test.go` line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tYRhf1nHn82e93Sbq:-N_tYRhf1nHn82e93Sbr:bthdqcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/49031ad957052db9577ea8ba05aa13a5575a899b/pkg/sql/create_as_test.go#L307)):*
> ```Go
> }
> 
> func TestFormat(t *testing.T) {
> ```

If you want something simpler this could just be a logic test

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tX_t1105zUn08bv4x):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

What happened to the commit message?
</blockquote></details>

I was originally working on a different fix and accidentally included the partially done commit from that. I just removed this.
___
*[`pkg/sql/create_as_test.go` line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tYRhf1nHn82e93Sbq:-N_tabor93vwls8fn7U_:b-ldjdps) ([raw file](https://github.com/cockroachdb/cockroach/blob/49031ad957052db9577ea8ba05aa13a5575a899b/pkg/sql/create_as_test.go#L307)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

If you want something simpler this could just be a logic test
</blockquote></details>

I'm using the parser to determine the table name.
___
*[`pkg/sql/delegate/show_function.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107367#-N_tZ7th4OPstBJjW1GE:-N_tahuO-EorV673JOQh:bhpm2ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f179c381ed59b5d9dea21dc29a90d8c5c1ec4f9/pkg/sql/delegate/show_function.go#L52)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should we have some test coverage for this scenario?
</blockquote></details>

Removed this commit.

**Review by fqazi — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by ecwall** [comment]
bors r=fqazi

**Pull request merged**
