### PR TITLE
workload: teach interleavedpartitioned about retryable transactions

### LINKED ISSUE #28567: roachtest: interleavedpartitioned failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/199436af8696d0028e1adfccec8a8fc61a5d347f

Parameters:

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=834301&tab=buildLog

```
	test.go:494,cluster.go:1104,interleavedpartitioned.go:118,interleavedpartitioned.go:126: /home/agent/work/.go/bin/roachprod get teamcity-834301-interleavedpartitioned histograms:1,4,7 /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20180814-834301/interleavedpartitioned/histograms: exit status 1

```

### PR DESCRIPTION
**Pull request by BramGruneir**
Also some other speedups and cleanups while I was in there.

Fixes #28567.

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
I'll run this few a few roachtests tomorrow to ensure it does fix it.

**Review by tbg — APPROVED** [review]
Thanks @BramGruneir!

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30944#-:-LNyrnU4AEus984WgApD:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30944#-LNyrLlnCEgNkWeX8XVN:-LNyrLlnCEgNkWeX8XVO:b4nh759) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a4113ad16c18b681a2df542eb49a91cff5f9fc5/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L413)):*
> ```Go
> 		if opRand < w.insertPercent {
> 			start := timeutil.Now()
> 			insertStatement, err := db.Prepare(insertQuery)
> ```

Are these database-level prepared statements a speedup? @nvanbenschoten discovered recently that there is an internal mutex (in `database/sql`) for database-level prepared statements that can become a contention point.

**Review by BramGruneir — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30944)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30944#-LNyrLlnCEgNkWeX8XVN:-LNzfGw45218EhbS9bnj:b-js1kut) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a4113ad16c18b681a2df542eb49a91cff5f9fc5/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L413)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are these database-level prepared statements a speedup? @nvanbenschoten discovered recently that there is an internal mutex (in `database/sql`) for database-level prepared statements that can become a contention point.
</blockquote></details>

I don't know if they're a speedup.  The original goal of this workload was to emulate the customer's workload as closely as possible.  So they do indeed prepare every statement.  I'll do a run without them to see if they make a significant difference.  But I'm going to merge this change first to get the test passing again.

**Review by BramGruneir — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30944#-:-LNzfhogBaOuPLCqeIlH:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by BramGruneir** [comment]
@petermattis 

To answer your question as to if the prepare statements speed things up, in this case, they clearly do:

```
east no prepare
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2455            4.1    978.8    939.5   1409.3   1610.6   3892.3  insert
  600.0s        0            329            0.5   1927.0    318.8   2080.4 103079.2 103079.2  retrieve
  600.0s        0            285            0.5   2013.0    268.4   1946.2 103079.2 103079.2  updates
east prepare
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2937            4.9   1093.1   1040.2   1543.5   1879.0   5905.6  insert
  600.0s        0            380            0.6   1912.4    209.7   2080.4  73014.4 103079.2  retrieve
  600.0s        0            330            0.5   2532.6    226.5   2952.8  90194.3 103079.2  updates

west no prepare
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           1369            2.3   1858.9   1879.0   2281.7   2415.9   3355.4  insert
  600.0s        0            153            0.3   1098.7    771.8   2281.7   2952.8   4563.4  retrieve
  600.0s        0            177            0.3   1282.9    872.4   2684.4   3758.1   6979.3  updates
west prepare
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           1762            2.9   1843.9   1879.0   2281.7   2550.1   3355.4  insert
  600.0s        0            223            0.4   3058.6    771.8   2550.1 103079.2 103079.2  retrieve
  600.0s        0            215            0.4   2677.8    872.4   8321.5  27917.3 103079.2  updates

central no
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           2204            3.7   1146.1   1476.4   2684.4   2952.8  38654.7  delete
central yes
 _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0           3422            5.7    849.7     37.7   2684.4   3221.2 103079.2  delete
```

**Comment by petermattis** [comment]
Ack. Thanks for checking.

**Pull request merged**
