### PR TITLE
kvserver,logstore: introduce log StateLoader

### PR DESCRIPTION
**Pull request by pav-kv**
Previously the `StateLoader` accessed both log and state machine state. This commit moves most of the log-specific accesstors to the `logstore` package.

Part of #91979
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: 

Mind adding `Epic: CRDB-220`? Something must've changed about the linter, it used to ask for an epic. 220 is our sep raft log epic.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92335#-:-NHYPX8R3zIGMmMncp8h:b-oiudk0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pavelkalinnikov)

**Comment by erikgrinaker** [comment]
>Mind adding Epic: CRDB-220? Something must've changed about the linter, it used to ask for an epic. 220 is our sep raft log epic.

I think it checks if the linked issue has an epic link, and #91979 is indeed linked to CRDB-220 -- but I thought it only supported the usual issue keywords like "fixes".

**Comment by pavelkalinnikov** [comment]
> I think it checks if the linked issue has an epic link, and #91979 is indeed linked to [CRDB-220](https://cockroachlabs.atlassian.net/browse/CRDB-220) -- but I thought it only supported the usual issue keywords like "fixes".

"Part of" is supported, it was included recently. So yeah, it picks the up the epic in the issue.

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by pavelkalinnikov** [comment]
bors retry

**Pull request merged**
