### PR TITLE
storage: add a `Require1PC` flag for `EndTransaction`

### LINKED ISSUE #14250: stability: cobalt wedged after ~5h.
`cobalt` was wiped and restarted as usual by continuous deployment, with sha 43f24c9
```
I170318 05:01:50.445249 1 cli/start.go:325  CockroachDB CCL 43f24c9-dirty (linux amd64, built 2017/03/18 04:35:44, go1.8)
```

It wedged about 4h45 later. All nodes are still up and running, but liveness dropped to 0 and all ranges are unavailable:
screen shot 2017-03-18 at 3 42 09 pm

Nothing shocking in the logs, just disconnects:
first 10 warning/errors per node at 9:45, +/- 5 minutes:
```
1: cockroach@cockroach-cobalt-0001.crdb.io
E170318 09:45:48.791445 1179 rpc/context.go:265  [n1] removing connection to cockroach-cobalt-06:26257 due to error: rpc error: code = 4 desc = context deadline exceeded
W170318 09:45:48.796514 1497406 storage/raft_transport.go:442  [n1] raft transport stream to node 6 failed: rpc error: code = 13 desc = transport is closing
W170318 09:45:49.668196 26151470 storage/replica.go:2255  [n1,s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80] context cancellation after 0.0s of attempting command [txn: e75cf19a], BeginTransaction [/Table/51/1/2974175659068629674/"f40c3fd8-fd4e-41de-8d24-c87c531489c1"/211563/0,/Min), ConditionalPut [/Table/51/1/2974175659068629674/"f40c3fd8-fd4e-41de-8d24-c87c531489c1"/211563/0,/Min), EndTransaction [/Table/51/1/2974175659068629674/"f40c3fd8-fd4e-41de-8d24-c87c531489c1"/211563/0,/Min)
W170318 09:45:58.054749 124 storage/node_liveness.go:293  [n1,hb] slow heartbeat took 3.1s
E170318 09:46:02.722310 26155567 storage/replica_range_lease.go:199  [n1,s1,r18/3:/Table/51/1/6{698565…-734385…},@c420fe7c00] result is ambiguous (error=retry txn "unnamed" id=c573330a key=/System/NodeLiveness/6 rw=true pri=0.00147368 iso=SERIALIZABLE stat=PENDING epo=0 ts=1489830361.037264980,1 orig=1489830360.531715504,0 max=1489830360.532661608,0 wto=false rop=false, pending RPCs=1)
W170318 09:47:06.013958 74 kv/dist_sender.go:1174  [raftlog,s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80,n1] have been waiting 1m0s sending RPC to r88 for batch: TruncateLog [/Table/51/1/2952735449336600996/"3c763570-c235-47d9-ae88-ecc57197c042"/30331,/Min)
E170318 09:47:06.014785 74 storage/queue.go:628  [raftlog,n1,s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80] failed to send RPC: sending to all 3 replicas failed; last error: rpc error: code = 4 desc = context deadline exceeded
W170318 09:47:06.017084 26160517 kv/dist_sender.go:1174  [s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80,n1] have been waiting 1m0s sending RPC to r1 for batch: [txn: 41234010], BeginTransaction [/System/NodeLiveness/6,/Min), ConditionalPut [/System/NodeLiveness/6,/Min), EndTransaction [/System/NodeLiveness/6,/Min)
W170318 09:47:06.250449 26160519 storage/replica.go:1119  [n1,s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80] have been waiting 1m0s attempting to acquire lease
W170318 09:47:06.271673 26160535 storage/replica.go:1119  [n1,s1,r88/3:/Table/51/1/29{52735…-88943…},@c421648a80] have been waiting 1m0s attempting to acquire lease

2: cockroach@cockroach-cobalt-0002.crdb.io
W170318 09:45:38.358728 33161005 storage/replica.go:1678  [n2,s2,r217/2:/Table/51/1/27{00152…-36138…},@c4245bc700] context canceled before command queue: [txn: 4a4c5cbc], BeginTransaction [/Table/51/1/2725211996826750562/"15541dd7-5903-422f-8768-672a5d829c9c"/213323/0,/Min), ConditionalPut [/Table/51/1/2725211996826750562/"15541dd7-5903-422f-8768-672a5d829c9c"/213323/0,/Min), EndTransaction [/Table/51/1/2725211996826750562/"15541dd7-5903-422f-8768-672a5d829c9c"/213323/0,/Min)
E170318 09:45:49.343297 553 rpc/context.go:265  [n2] removing connection to cockroach-cobalt-06:26257 due to error: rpc error: code = 4 desc = context deadline exceeded
W170318 09:45:49.358489 528 storage/raft_transport.go:442  [n2] raft transport stream to node 6 failed: rpc error: code = 13 desc = transport is closing
W170318 09:45:57.929061 123 storage/node_liveness.go:293  [n2,hb] slow heartbeat took 4.4s
W170318 09:47:06.106136 138 kv/dist_sender.go:1174  [raftlog,s2,r274/2:/Table/51/1/20{53125…-89017…},@c4243b0700,n2] have been waiting 1m0s sending RPC to r274 for batch: TruncateLog [/Table/51/1/2053125291445864015/"f0592470-12a0-4cd6-9f63-b50b057ca1de"/87438,/Min)
E170318 09:47:06.107127 138 storage/queue.go:628  [raftlog,n2,s2,r274/2:/Table/51/1/20{53125…-89017…},@c4243b0700] failed to send RPC: sending to all 3 replicas failed; last error: rpc error: code = 4 desc = context deadline exceeded
W170318 09:47:06.271619 6425 kv/dist_sender.go:1174  [client=127.0.0.1:55160,user=root,n2] have been waiting 1m0s sending RPC to r88 for batch: [txn: f610789d], BeginTransaction [/Table/51/1/2975494460006416432/"b209dfb8-e557-487e-ab13-a5e9c7d042f5"/211104/0,/Min), ConditionalPut [/Table/51/1/2975494460006416432/"b209dfb8-e557-487e-ab13-a5e9c7d042f5"/211104/0,/Min), EndTransaction [/Table/51/1/2975494460006416432/"b209dfb8-e557-487e-ab13-a5e9c7d042f5"/211104/0,/Min)
W170318 09:47:06.303226 33176369 storage/replica.go:1119  [n2,s2,r274/2:/Table/51/1/20{53125…-89017…},@c4243b0700] have been waiting 1m0s attempting to acquire lease
W170318 09:47:06.303746 33176378 kv/dist_sender.go:1174  [s2,r274/2:/Table/51/1/20{53125…-89017…},@c4243b0700,n2] have been waiting 1m0s sending RPC to r1 for batch: [txn: 0b7381ba], BeginTransaction [/System/NodeLiveness/6,/Min), ConditionalPut [/System/NodeLiveness/6,/Min), EndTransaction [/System/NodeLiveness/6,/Min)
W170318 09:47:06.411393 33176627 storage/replica.go:1119  [n2,s2,r274/2:/Table/51/1/20{53125…-89017…},@c4243b0700] have been waiting 1m0s attempting to acquire lease

3: cockroach@cockroach-cobalt-0003.crdb.io
W170318 09:41:23.021441 135 storage/engine/rocksdb.go:1200  batch [3/234/3] commit took 608.485346ms (>500ms):
W170318 09:41:23.021692 137 storage/store.go:3419  [n3,s3,r293/3:/Table/51/1/2{197436…-233295…},@c423acd180] handle raft ready: 0.6s [processed=0]
E170318 09:45:52.111950 138 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
E170318 09:45:57.970408 141 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
W170318 09:45:57.979826 163 storage/node_liveness.go:293  [n3,hb] slow heartbeat took 1.4s
E170318 09:45:57.986144 141 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
E170318 09:46:01.109208 140 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
E170318 09:46:05.608075 141 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
E170318 09:46:10.524643 141 storage/replica_proposal.go:465  [n3,s3,r1/3:/{Min-System/tsd/c…},@c4201e7880] couldn't scan node liveness records in span {/System/NodeLiveness /System/NodeLivenessMax}: conflicting intents on [/System/NodeLiveness/6]
E170318 09:46:13.188079 154 storage/queue.go:628  [replicate,n3,s3,r27/4:/Table/51/1/46{14528…-50349…},@c421879c00] range requires a replication change, but lacks a quorum of live replicas (1/2)

4: cockroach@cockroach-cobalt-0004.crdb.io
W170318 09:41:25.731059 20824357 storage/replica.go:1678  [n4,s4,r278/1:/Table/51/1/6{139615…-497616…},@c421218a80] context canceled before command queue: [txn: 00c93e7c], BeginTransaction [/Table/51/1/634763957670893886/"1bee5130-0f62-421e-b3e3-72e6b9d48ae9"/208191/0,/Min), ConditionalPut [/Table/51/1/634763957670893886/"1bee5130-0f62-421e-b3e3-72e6b9d48ae9"/208191/0,/Min), EndTransaction [/Table/51/1/634763957670893886/"1bee5130-0f62-421e-b3e3-72e6b9d48ae9"/208191/0,/Min)
W170318 09:45:57.928951 185 storage/node_liveness.go:293  [n4,hb] slow heartbeat took 2.8s
W170318 09:47:06.626234 911 kv/dist_sender.go:1174  [client=127.0.0.1:51054,user=root,n4] have been waiting 1m0s sending RPC to r88 for batch: [txn: 9f7fecc2], BeginTransaction [/Table/51/1/2973048484904638349/"89ddfd3c-8e20-483f-bfc5-bd30fa891a78"/210206/0,/Min), ConditionalPut [/Table/51/1/2973048484904638349/"89ddfd3c-8e20-483f-bfc5-bd30fa891a78"/210206/0,/Min), EndTransaction [/Table/51/1/2973048484904638349/"89ddfd3c-8e20-483f-bfc5-bd30fa891a78"/210206/0,/Min)
W170318 09:47:06.681174 944 kv/dist_sender.go:1174  [client=127.0.0.1:51090,user=root,n4] have been waiting 1m0s sending RPC to r274 for batch: [txn: 03e5c5f4], BeginTransaction [/Table/51/1/2068368049474089767/"107e75b5-f319-46ce-b121-0ce136071592"/210788/0,/Min), ConditionalPut [/Table/51/1/2068368049474089767/"107e75b5-f319-46ce-b121-0ce136071592"/210788/0,/Min), EndTransaction [/Table/51/1/2068368049474089767/"107e75b5-f319-46ce-b121-0ce136071592"/210788/0,/Min)
W170318 09:47:06.710624 949 kv/dist_sender.go:1174  [client=127.0.0.1:51034,user=root,n4] have been waiting 1m0s sending RPC to r88 for batch: [txn: 93a31da0], BeginTransaction [/Table/51/1/2966568604657505570/"f5f0d744-d1ad-41cd-a8e1-fdc1814f781d"/211506/0,/Min), ConditionalPut [/Table/51/1/2966568604657505570/"f5f0d744-d1ad-41cd-a8e1-fdc1814f781d"/211506/0,/Min), EndTransaction [/Table/51/1/2966568604657505570/"f5f0d744-d1ad-41cd-a8e1-fdc1814f781d"/211506/0,/Min)
W170318 09:47:07.595994 1016 kv/dist_sender.go:1174  [client=127.0.0.1:51128,user=root,n4] have been waiting 1m0s sending RPC to r88 for batch: [txn: 26863598], BeginTransaction [/Table/51/1/2961986085513196474/"69e74673-d65e-4590-8d0f-59c1567daf15"/211191/0,/Min), ConditionalPut [/Table/51/1/2961986085513196474/"69e74673-d65e-4590-8d0f-59c1567daf15"/211191/0,/Min), EndTransaction [/Table/51/1/2961986085513196474/"69e74673-d65e-4590-8d0f-59c1567daf15"/211191/0,/Min)
W170318 09:47:07.690726 1050 kv/dist_sender.go:1174  [client=127.0.0.1:51130,user=root,n4] have been waiting 1m0s sending RPC to r274 for batch: [txn: fc401569], BeginTransaction [/Table/51/1/2084987706437677431/"da19afdf-9b58-4ec3-9bd3-8c2863534c4e"/211533/0,/Min), ConditionalPut [/Table/51/1/2084987706437677431/"da19afdf-9b58-4ec3-9bd3-8c2863534c4e"/211533/0,/Min), EndTransaction [/Table/51/1/2084987706437677431/"da19afdf-9b58-4ec3-9bd3-8c2863534c4e"/211533/0,/Min)
W170318 09:47:07.812391 877 kv/dist_sender.go:1174  [client=127.0.0.1:51028,user=root,n4] have been waiting 1m0s sending RPC to r88 for batch: [txn: 19e664a2], BeginTransaction [/Table/51/1/2982186146000455665/"158252f4-9e30-4b6b-b549-8cfad20d55c3"/210252/0,/Min), ConditionalPut [/Table/51/1/2982186146000455665/"158252f4-9e30-4b6b-b549-8cfad20d55c3"/210252/0,/Min), EndTransaction [/Table/51/1/2982186146000455665/"158252f4-9e30-4b6b-b549-8cfad20d55c3"/210252/0,/Min)
W170318 09:47:07.826169 864 kv/dist_sender.go:1174  [client=127.0.0.1:51010,user=root,n4] have been waiting 1m0s sending RPC to r88 for batch: [txn: b5d401fd], BeginTransaction [/Table/51/1/2970462658508471530/"76d82251-18b1-4c9e-a22e-0644bd794cef"/211021/0,/Min), ConditionalPut [/Table/51/1/2970462658508471530/"76d82251-18b1-4c9e-a22e-0644bd794cef"/211021/0,/Min), EndTransaction [/Table/51/1/2970462658508471530/"76d82251-18b1-4c9e-a22e-0644bd794cef"/211021/0,/Min)
W170318 09:47:08.093697 990 kv/dist_sender.go:1174  [client=127.0.0.1:51126,user=root,n4] have been waiting 1m0s sending RPC to r274 for batch: [txn: 36c7155f], BeginTransaction [/Table/51/1/2067048875555022097/"cc9359e5-5bab-48f7-8962-d8a937e4de4d"/210950/0,/Min), ConditionalPut [/Table/51/1/2067048875555022097/"cc9359e5-5bab-48f7-8962-d8a937e4de4d"/210950/0,/Min), EndTransaction [/Table/51/1/2067048875555022097/"cc9359e5-5bab-48f7-8962-d8a937e4de4d"/210950/0,/Min)

5: cockroach@cockroach-cobalt-0005.crdb.io
W170318 09:40:20.752989 26072911 storage/replica.go:1678  [n5,s5,r60/3:/Table/51/1/33{13996…-49996…},@c421723c00] context canceled before command queue: [txn: dc0ed08e], BeginTransaction [/Table/51/1/3324223168211426361/"64ff8857-2123-4e9e-9b1d-39a7b43de9c1"/207340/0,/Min), ConditionalPut [/Table/51/1/3324223168211426361/"64ff8857-2123-4e9e-9b1d-39a7b43de9c1"/207340/0,/Min), EndTransaction [/Table/51/1/3324223168211426361/"64ff8857-2123-4e9e-9b1d-39a7b43de9c1"/207340/0,/Min)
E170318 09:40:31.178615 26089888 server.go:2751  http: TLS handshake error from 222.223.189.4:30183: EOF
W170318 09:44:54.561079 26510127 storage/replica.go:1678  [n5,s5,r154/3:/Table/51/1/40{00767…-36813…},@c424b48700] context canceled before command queue: [txn: 83ef17c1], BeginTransaction [/Table/51/1/4021438181977117867/"6b587bd7-b6a0-49f4-a379-ad2587f731a9"/211530/0,/Min), ConditionalPut [/Table/51/1/4021438181977117867/"6b587bd7-b6a0-49f4-a379-ad2587f731a9"/211530/0,/Min), EndTransaction [/Table/51/1/4021438181977117867/"6b587bd7-b6a0-49f4-a379-ad2587f731a9"/211530/0,/Min)
E170318 09:45:58.550040 26582988 storage/replica_range_lease.go:199  [n5,s5,r143/3:/Table/51/1/84{29070…-65288…},@c423a2d880] result is ambiguous (error=retry txn "unnamed" id=823a0425 key=/System/NodeLiveness/6 rw=true pri=0.04220987 iso=SERIALIZABLE stat=PENDING epo=0 ts=1489830351.961075647,1 orig=1489830351.461360018,0 max=1489830351.461924751,0 wto=false rop=false, pending RPCs=1)
W170318 09:45:58.555250 129 storage/node_liveness.go:293  [n5,hb] slow heartbeat took 4.9s
E170318 09:46:13.164268 154 storage/queue.go:628  [replicate,n5,s5,r196/3:/Table/51/1/90{43075…-79148…},@c42499ca80] range requires a replication change, but lacks a quorum of live replicas (1/2)
W170318 09:46:43.169685 149 storage/replica.go:4413  [n5,s5] could not acquire lease for range gossip: range 2 was not found
W170318 09:46:43.169957 149 storage/store.go:1405  [n5,s5] could not gossip system config: range 2 was not found
W170318 09:46:43.218035 149 storage/replica.go:4413  [n5,s5] could not acquire lease for range gossip: range 2 was not found
W170318 09:46:43.218086 149 storage/store.go:1405  [n5,s5] could not gossip system config: range 2 was not found

6: cockroach@cockroach-cobalt-0006.crdb.io
W170318 09:45:46.034257 218 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r215/1:/Table/51/1/2{772200…-808250…},@c423261500] 1 stepped down to follower since quorum is not active
W170318 09:45:46.235959 221 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r231/1:/Table/51/1/24{12769…-48677…},@c425eb7c00] 1 stepped down to follower since quorum is not active
E170318 09:45:46.411929 113 rpc/context.go:265  [n6] removing connection to cockroach-cobalt-02:26257 due to error: rpc error: code = 4 desc = context deadline exceeded
W170318 09:45:46.412689 82 gossip/gossip.go:1178  [n6] no incoming or outgoing connections
W170318 09:45:46.413551 265 storage/raft_transport.go:442  [n6] raft transport stream to node 2 failed: rpc error: code = 13 desc = transport is closing
W170318 09:45:46.434192 221 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r161/1:/Table/51/1/2{376819…-412769…},@c422d49500] 1 stepped down to follower since quorum is not active
W170318 09:45:46.634089 217 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r162/1:/Table/51/1/64{10904…-46916…},@c425d68000] 1 stepped down to follower since quorum is not active
W170318 09:45:46.834179 218 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r237/1:/Table/51/1/4{793396…-829177…},@c4267c1500] 1 stepped down to follower since quorum is not active
W170318 09:45:46.834355 217 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r28/1:/Table/51/1/23{04997…-40921…},@c421da5500] 1 stepped down to follower since quorum is not active
W170318 09:45:46.834381 219 vendor/github.com/coreos/etcd/raft/raft.go:793  [n6,s6,r211/1:/Table/51/1/{180876…-217076…},@c423d20380] 1 stepped down to follower since quorum is not active
```

cockroach-cobalt-0006 seems the culprit, but I'm having a hard time telling why.

cobalt is running with:
```
COCKROACH_ENABLE_LOAD_BASED_LEASE_REBALANCING=true
COCKROACH_ENTERPRISE_ENABLED=true
COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE=true
```

continuous deployment paused and alerts silenced for 2 days.

### PR DESCRIPTION
**Pull request by spencerkimball**
This allows simple updates which require an `EndTransaction` trigger to
insist that the operation complete without leaving write intents.

We now use this from `NodeLiveness`.

Fixes #14250

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14346)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 4122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfweHhwH1leu8CrFxJ4:-KfweHhwH1leu8CrFxJ5:b-ktc2s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3363d6d95393a22c893fea8967d70cb52f09f0/pkg/storage/replica.go#L4122)):*
> ```Go
> 				)
> 			}
> 			panic("unreachable")
> ```

I think you can combine this with the `if pErr == nil && ba.Timestamp == br.Timestamp {` above to avoid the need to panic here.

---

*[pkg/storage/replica_test.go, line 3823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfA87t0Fb2IJrF0I7:-KfwfA87t0Fb2IJrF0I8:b-745idj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3363d6d95393a22c893fea8967d70cb52f09f0/pkg/storage/replica_test.go#L3823)):*
> ```Go
> 
> 			// Send the batch command.
> 			if _, pErr := tc.Sender().Send(context.Background(), ba); pErr == nil {
> ```

check the specific error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-:-KfwfKpqiNySXY9lCRIQ:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

As discussed offline, this will require a stop-the-world upgrade (at least in theory - the chances of an inconsistency caused by failing to stop the world are as small as those for the hanging intent problem that this is fixing). 

---

Reviewed 2 of 6 files at r1, 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 4124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfC_J3NmteQ73N197:-KfwfC_J3NmteQ73N198:bo54p0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b981fb10740ba50dabf472ca943893aae0afb155/pkg/storage/replica.go#L4124)):*
> ```Go
> 		}
> 
> 		log.VEventf(ctx, 2, "1PC execution failed, reverting to regular execution for batch")
> ```

Put this log line below the `Require1PC` handling.

---

*[pkg/storage/replica.go, line 4135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfL6eXVD-zDWW9QIJ:-KfwfL6eXVD-zDWW9QIK:byq8dfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b981fb10740ba50dabf472ca943893aae0afb155/pkg/storage/replica.go#L4135)):*
> ```Go
> 			} else if ba.Timestamp != br.Timestamp {
> 				return nil, ms, nil, EvalResult{}, roachpb.NewErrorf(
> 					"could not require one phase commit: timestamp advanced from %s to %s", ba.Timestamp, br.Timestamp,
> ```

"could not commit in one phase as requested: timestamp advanced from %s to %s"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-:-KfwhAll5Hco7Sc9sC_8:bmb2a3o)*

**Comment by spencerkimball** [comment]
I wonder if it's worth bothering to warn about stop the world on this one...

---

Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 4122 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfweHhwH1leu8CrFxJ4:-Kfwho6SAzXMFHs9cj1Z:b-hf5fjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3363d6d95393a22c893fea8967d70cb52f09f0/pkg/storage/replica.go#L4122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you can combine this with the `if pErr == nil && ba.Timestamp == br.Timestamp {` above to avoid the need to panic here.
</blockquote></details>

As discussed, I'm just going to leave the panic in because this flow helps with closing out resources like the batch and the `MVCCStats`.

---

*[pkg/storage/replica.go, line 4124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfC_J3NmteQ73N197:-KfwjWb1fO2yu5NSO_Sr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b981fb10740ba50dabf472ca943893aae0afb155/pkg/storage/replica.go#L4124)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Put this log line below the `Require1PC` handling.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 4135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfL6eXVD-zDWW9QIJ:-KfwjdOkteKa81cQmEwC:b-lmieb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b981fb10740ba50dabf472ca943893aae0afb155/pkg/storage/replica.go#L4135)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"could not commit in one phase as requested: timestamp advanced from %s to %s"
</blockquote></details>

Actually, I realized that we need to return a retryable error here so that `NodeLiveness`, for example, will retry instead of logging an error and waiting for the next heartbeat cycle.

---

*[pkg/storage/replica_test.go, line 3823 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-KfwfA87t0Fb2IJrF0I7:-KfwjsxS6vcFKb6sEm_o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3363d6d95393a22c893fea8967d70cb52f09f0/pkg/storage/replica_test.go#L3823)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

check the specific error?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346#-:-KfwjS_utD64fJlNoYNw:bp2d1hr)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14346)*

**Pull request merged**
