### PR TITLE
Add CLI 'gen' command to generate bash autocompletion file and man pages

### PR DESCRIPTION
**Pull request by cuongdo**
Implements #3487

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4154)

### CODE REVIEW

**Comment by tamird** [comment]
nit: can you wrap the first line of your commit message at 50? additional words can go in the "body" and wrapped at 72.

see https://github.com/erlang/otp/wiki/Writing-good-commit-messages

Also, I think "implements #..." won't cause github to close the referenced issue, so you might want to use "Fixes".

LGTM

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[cli/cli_test.go, line 886 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJ_5yMuw3Az9iwOCd:-K9iJ_5yMuw3Az9iwOCe:677416866) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L886)):*
`:=`

---

*[cli/cli_test.go, line 892 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJan8lmzDNculzEUD:-K9iJan8lmzDNculzEUE:-2094676356) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L892)):*
`:=` if you're ok with the condition being at the bottom

---

*[cli/cli_test.go, line 924 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJoRE5SE2s8NRQjM8:-K9iJoRE5SE2s8NRQjM9:-556855247) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L924)):*
more instances of := but you get it

---

*[cli/gen.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iHdFqxm073zaDq7gh:-K9iHdFqxm073zaDq7gi:-1338681353) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L56)):*
nit: `err :=`; I don't think you intend to overwrite the outer error

---

*[cli/gen.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIr07anFuCqJpe_fn:-K9iIr07anFuCqJpe_fo:-1654212771) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L97)):*
maybe extract string constants? you're repeating yourself below.

---

*[cli/gen.go, line 108 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJ2Y-nE7AVZTT3h1J:-K9iJ2Y-nE7AVZTT3h1K:-1624938830) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L108)):*
Put a TODO here with your name to follow up.

---

*[cli/gen.go, line 134 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIc6zx_hXH2y-XtdU:-K9iIc6zx_hXH2y-XtdV:1975113132) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L134)):*
I think you want StringVar, not StringVarP

---

*[cli/gen.go, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIOb1Mmi84nzMlvHI:-K9iIOb1Mmi84nzMlvHJ:230414804) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L137)):*
extract local `genAutocompleteCmd.PersistentFlags()`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-:-K9iHDCwqs4Pq1pGRaKt:226489773)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[cli/cli_test.go, line 924 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iNJJLGixtZWNrHWAm:-K9iNJJLGixtZWNrHWAn:256937666) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/cli_test.go#L924)):*
This is unsafe; another test process (as in stress tests) could pick the same filename again once this one is closed. To be safe you need to use a temporary directory instead of a temporary file, and write to a filename in that directory.

---

*[cli/gen.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iNe7YAXKnDPnkRcoo:-K9iNe7YAXKnDPnkRcop:-1566091427) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L36)):*
Insert "and" between "pages bash"

---

*[cli/gen.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iOetlAryQLXFg-wtl:-K9iOetlAryQLXFg-wtm:79409512) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L38)):*
This is probably the right default because it doesn't require special permissions, but we should also give an example of how you'd run it to put the man pages somewhere that `man` can actually find.

---

*[cli/gen.go, line 109 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iQDsEixmiWpjbWRwP:-K9iQDsEixmiWpjbWRwQ:-1307279064) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L109)):*
See my comment on spf13/cobra#240; I don't think this is equivalent.

---

*[cli/gen.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iQx-AhZxTfPanv5xc:-K9iQx-AhZxTfPanv5xd:-1187530959) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L111)):*
You're relying on the umask here to make the file not world-writeable, right? You used `0755` above; it should probably be `0777` for the same reasons.

Autocomplete files should not be executable (so this one should be `0666`); they must be sourced instead of executed to have any effect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[cli/gen.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iOetlAryQLXFg-wtl:-K9j2ASZu4E-1pODjHR8:-289343268) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L38)):*
FYI, I came across this when looking at the `hugo` brew recipe which generated the man and bash pages and then installed them into the correct locations.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154)*

**Comment by cuongdo** [comment]
Thanks for the tip. I'll redo the commit message when I squash my commits.

---

Review status: 1 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[cli/cli_test.go, line 886 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJ_5yMuw3Az9iwOCd:-K9lVuvL2RtrF39YYMjs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L886)):*
Done.

---

*[cli/cli_test.go, line 892 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJan8lmzDNculzEUD:-K9lWXO45CkvPBKIbtT2:-83958327) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L892)):*
I think it's harder to read with the condition at the bottom, so I left it as-is

---

*[cli/cli_test.go, line 924 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJoRE5SE2s8NRQjM8:-K9lXPGlOriRQvcBRfgd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/cli_test.go#L924)):*
Done.

---

*[cli/cli_test.go, line 924 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iNJJLGixtZWNrHWAm:-K9ln6T6qZpH4OnTm6vs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/cli_test.go#L924)):*
Done.

---

*[cli/gen.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iHdFqxm073zaDq7gh:-K9lrQXDsnMR6bkFPPAJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L56)):*
Done.

---

*[cli/gen.go, line 97 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIr07anFuCqJpe_fn:-K9lov5BFyeeKq1dmtdz:-1818809912) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L97)):*
Code has been removed, because cobra has been fixed already (spf13/cobra@801364aa1521eb0ac9735f138901d5fe0f37b4b8). I've updated the GLOCKFILE to pull in the fixed version.

---

*[cli/gen.go, line 108 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iJ2Y-nE7AVZTT3h1J:-K9lp59VTY-U9rpuu2cF:-596536996) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L108)):*
Code has been removed, since the cobra author has implemented a workaround.

---

*[cli/gen.go, line 134 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIc6zx_hXH2y-XtdU:-K9lpbyM8fPYjA0lzWto:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L134)):*
Done.

---

*[cli/gen.go, line 137 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iIOb1Mmi84nzMlvHI:-K9lq4AzeGKIzyzhDEyV:-743344592) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5e90545ec630c801035dd6cd3785416df45f4e/cli/gen.go#L137)):*
Probably not needed any more now that `genAutocompleteCmd` only has a single flag?

---

*[cli/gen.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iNe7YAXKnDPnkRcoo:-K9lnH4taX-Ps98oyWqM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L36)):*
Done.

---

*[cli/gen.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iOetlAryQLXFg-wtl:-K9lYg5akO2yndjR-xZU:655255758) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L38)):*
Yes, I think a platform-specific package/installer is the right place to install. I've added more detail to the help message.

---

*[cli/gen.go, line 109 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iQDsEixmiWpjbWRwP:-K9lp2EX-T-SyC9r6Svk:-1976663447) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L109)):*
This has been worked around in cobra already (spf13/cobra@801364aa1521eb0ac9735f138901d5fe0f37b4b8), so I've removed my workaround.

---

*[cli/gen.go, line 111 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9iQx-AhZxTfPanv5xc:-K9lpL_zhvpOawk-y5iQ:69485735) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bdd598243285f7b26a393e3818bbf023c6394a8/cli/gen.go#L111)):*
This code has been removed thanks to spf13/cobra@801364aa1521eb0ac9735f138901d5fe0f37b4b8

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-:-K9lv94HmwZsgV5DK3M1:-1362143644)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/gen.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-K9mX293RN23UGGHP2vj:-K9mX294JgVkubl54dEn:424568483) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ac9fbf4b43dcac1eb2a56c21e2321e3c1e87e9d/cli/gen.go#L86)):*
s/flag/out/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-:-K9mYAuvswzRBPXXWslQ:676834233)*

**Comment by bdarnell** [comment]
Cobra can also generate markdown-formatted docs; we should see if they would be useful for @jseldess 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4154#-:-K9mYS2OR5-qLe9Thmdw:-1409028069)*

**Pull request merged**
