### PR TITLE
Update status to reflect 1.0 release

### PR DESCRIPTION
**Pull request by leereilly**
Noticed the `README.md` still thinks you're in beta. Potential fix attached for your consideration :metal: 

Congrats on the `1.0` release, Enterprise release and Series B 🎉

### CODE REVIEW

**Comment by dianasaur323** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15857#-:-Kjo0-FSu40KHDKK9W4Y:bnfp4nl)*

**Comment by benesch** [comment]
Good catch, @leereilly! @dianasaur323, should we instead link to https://github.com/cockroachdb/cockroach/issues/13517 as the product roadmap instead of the 1.1 milestone?

**Comment by dianasaur323** [comment]
We might actually stop reporting that wide product roadmap at some point, and opt for a more detailed 1.1 roadmap. Since we haven't released it yet, the milestone should be fine for now. @benesch

**Comment by benesch** [comment]
Ok, in that case, merging!

**Pull request merged**
