### PR TITLE
*: future proof tests for span configs

### PR DESCRIPTION
**Pull request by irfansharif**
This PR is a (mostly) test-only change that paves the way for enabling span
configs by default (#73876). Various tests throughout CRDB rely on timing
assumptions with respect to how quickly splits are induced or configs applied,
assumptions that are no longer true with the span configs infrastructure
because:
- updated descriptors/zone configs make its way to the global span config
   state `system.span_configurations` asynchronously, and
- kv learns about learns about these updates asynchronously.

Consider TestTruncatePreservesSplitPoints for example, which relied on range
split decisions to happen near-instantaneously (especially for the single node
variant) -- a fair assumption with the gossiped SystemConfigSpan, but no longer
applicable.

Another example is TestChangefeedProtectedTimestamps, where we use an
extremely low gc.ttlseconds. Given span configs makes use of rangefeeds
internally, feeds that error out if started at timestamps already GC-ed, we
need to ensure a sufficiently lax GC TTL.

For most of these tests, making them agnostic to either subsystem is just a
matter of throwing in a SucceedsSoon block at the right places. See individual
commits/commentary for the individual test changes.

Release note: None

---

First commit is from #74171 and should be reviewed there.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, 14 of 14 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-:-Mt4hD5J5ptJqx4j8t59:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[-- commits, line 51 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-Mt4cHO27M4ILecV4p7x):*
`s/the/then/`
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 3582 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-Mt4gO-K-otl24mi3unz:-Mt4gO-K-otl24mi3uo-:b-xffdya) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8803a49de4311daabc692305c73eb6ef16ebb1/pkg/ccl/changefeedccl/changefeed_test.go#L3582)):*
> ```Go
> 			sqlDB := sqlutils.MakeSQLRunner(db)
> 			sqlDB.Exec(t, `ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 100`)
> 			sqlDB.Exec(t, `ALTER RANGE system CONFIGURE ZONE USING gc.ttlseconds = 100`)
> ```

Why was the test dropping the gc.ttl so low? Does bumping it up make the test pass trivially even if a protected timestamp is not written?
___
*[pkg/ccl/multiregionccl/roundtrips_test.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-Mt4fnhNCfvilwnAavae:-Mt4fnhNCfvilwnAavaf:b-8nn03q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6493d71b5049586ab15b7814d8a8a2c68a3587ae/pkg/ccl/multiregionccl/roundtrips_test.go#L116)):*
> ```Go
> 		conn := tc.ServerConn(i)
> 		isLeaseHolder := false
> 		testutils.SucceedsSoon(t, func() error {
> ```

This seems like the wrong place to wait for the split. Should we do it right after creating the table?

**Review by irfansharif — COMMENTED** [review]
TFTR! Waiting for green.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-:-MtK3dPtCsoMIvny5_QF:b-6wqe8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 3582 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-Mt4gO-K-otl24mi3unz:-MtJnqGc6_HWyTTkAxie:b8uhrz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c8803a49de4311daabc692305c73eb6ef16ebb1/pkg/ccl/changefeedccl/changefeed_test.go#L3582)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why was the test dropping the gc.ttl so low? Does bumping it up make the test pass trivially even if a protected timestamp is not written?
</blockquote></details>

I'm not really sure, @ajwerner perhaps? (introduced in https://github.com/cockroachdb/cockroach/commit/84ce391f1667fedf31e0609e562b5768d62c455a.)

The test does assert on the protection record existing/not existing, and I don't we're executing anything that would cause GC to occur. My guess is to speed up the test? But don't know about the internals to say for sure.
___
*[pkg/ccl/multiregionccl/roundtrips_test.go, line 116 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/74265#-Mt4fnhNCfvilwnAavae:-MtK07j13qeqH9NlK2VZ:b-m2dctp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6493d71b5049586ab15b7814d8a8a2c68a3587ae/pkg/ccl/multiregionccl/roundtrips_test.go#L116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems like the wrong place to wait for the split. Should we do it right after creating the table?
</blockquote></details>

It's not just splits here, it's also the configs that the test is asserting on. (I had tried waiting for just splits earlier, but the config propagation itself was unaccounted for.) 

We don't have good testing library APIs that let you wait for a config to materialize in this way, and short of introducing introducing them, this felt more targeted. I think we'll soon want more of these APIs with the additional amount of asynchrony this infra bakes in.

**Comment by irfansharif** [comment]
CI failure is an existing flake: https://github.com/cockroachdb/cockroach/issues/74819.

**Pull request merged**
