### PR TITLE
exec: sort indices of the selection vector in the testing framework

### PR DESCRIPTION
**Pull request by yuzefovich**
The selection vector is shuffled, so the indices corresponding to
the actual tuples would be in a random order; however, the columnar
operators process and output the vectors sequentially, so we should
sort the indices corresponding to the actual testing data.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM, thanks for this cleanup

**Review by georgeutsin — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34018)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
Seems to be stuck in "pending", so let's try one more time.

bors r+

**Comment by yuzefovich** [comment]
Let's give it another shot.

bors r+

**Pull request merged**
