### PR TITLE
opt: cache not-null columns in the metadata

### PR DESCRIPTION
**Pull request by rytaft**
**opt: add a new query to the slow queries benchmark**

Release justification: non-production code changes

Release note: None

**opt: cache not-null columns in the metadata**

This commit adds a new table annotation for not null columns to avoid
rediscovering them multiple times per table. This improves performance
for queries over tables with a large number of columns and indexes.

Benchmark results:
```
name                         old time/op    new time/op    delta
SlowQueries/slow-query-3-10     123ms ± 1%      63ms ± 2%  -48.62%  (p=0.000 n=10+9)
SlowQueries/slow-query-1-10    20.3ms ± 1%    20.2ms ± 2%     ~     (p=0.353 n=10+10)
SlowQueries/slow-query-2-10     312ms ± 2%     313ms ± 4%     ~     (p=0.842 n=10+9)

name                         old alloc/op   new alloc/op   delta
SlowQueries/slow-query-3-10    59.3MB ± 0%    49.0MB ± 0%  -17.38%  (p=0.000 n=10+10)
SlowQueries/slow-query-1-10    12.3MB ± 0%    12.3MB ± 0%   -0.27%  (p=0.000 n=10+10)
SlowQueries/slow-query-2-10     181MB ± 0%     181MB ± 0%     ~     (p=0.739 n=10+10)

name                         old allocs/op  new allocs/op  delta
SlowQueries/slow-query-3-10      542k ± 0%      381k ± 0%  -29.72%  (p=0.000 n=9+10)
SlowQueries/slow-query-1-10      131k ± 0%      131k ± 0%   -0.39%  (p=0.000 n=10+10)
SlowQueries/slow-query-2-10     1.65M ± 0%     1.65M ± 0%     ~     (p=0.345 n=9+10)
```
Release justification: low risk, high benefit changes to existing
functionality

Release note (performance improvement): Planning time has been reduced
for queries over tables with a large number of columns and/or indexes.

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Nice speedup!
:lgtm: 

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-:-NA6sLud7Q5fDtMeqvew:bkw5ld3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Very nice!

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-:-NA7JCOoEMZY9tGnoZuK:b-j7qk9t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA7IgWa2Q3uDwky_JKQ:-NA7IgWa2Q3uDwky_JKR:b-9t9ygz) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L91)):*
> ```Go
> 	// ----------------
> 	// Initialize not-NULL columns from the table schema.
> 	rel.NotNullCols = makeTableNotNullCols(md, scan.Table).Copy()
> ```

Sounds like our fast int set large/small tests caught the missing `Copy`s? Good to know those tests are still working well.
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA78LuQEnMMYV4u0mPC:-NA78LuR-Lv76Ia1-vuA:b13xt3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L2209)):*
> ```Go
> // since it may be accessed multiple times during query optimization.
> func makeTableNotNullCols(md *opt.Metadata, tabID opt.TableID) opt.ColSet {
> 	cs, ok := md.TableAnnotation(tabID, opt.NotNullAnnID).(opt.ColSet)
> ```

What is the advantage of using this table annotation mechanism instead of a struct field? It's not obvious to me why this annotation mechanism needs to exist at all... Am I missing something obvious?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-:-NAA95F327OJ7wm9Rsu4:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA7IgWa2Q3uDwky_JKQ:-NAA4bd_CqFglOMuzckJ:bwoix9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L91)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sounds like our fast int set large/small tests caught the missing `Copy`s? Good to know those tests are still working well.
</blockquote></details>

Doesn't look like those tests caught them (not sure if we run those tests as part of CI), but there were some other test failures in our data driven tests (some columns that were `!null` before no longer were), as well as check_expr failures like "not null cols not a subset of output cols" that made me realize the need for `Copy`.
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA78LuQEnMMYV4u0mPC:-NAA7m6-5vGXpRxRu_j4:b-xfndx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L2209)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What is the advantage of using this table annotation mechanism instead of a struct field? It's not obvious to me why this annotation mechanism needs to exist at all... Am I missing something obvious?
</blockquote></details>

This mechanism has been around since the early days of the optimizer, so it's definitely possible that it's just an artifact of that time and struct fields would be just as good if not better. Looking back at the old commits I don't see any obvious explanation for why this is a better approach.

The existing annotations (stats and func deps) are also logical properties, so it seemed consistent to add not null columns as well. We could definitely look into removing this mechanism altogether, but I'd rather do that in a different PR if it's ok with you, since I want to backport this change.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86606)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA7IgWa2Q3uDwky_JKQ:-NABfN4w0KKadqyG5M4e:b-6tq0ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L91)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Doesn't look like those tests caught them (not sure if we run those tests as part of CI), but there were some other test failures in our data driven tests (some columns that were `!null` before no longer were), as well as check_expr failures like "not null cols not a subset of output cols" that made me realize the need for `Copy`.
</blockquote></details>

Oh. Well either way glad they caught it!
___
*[`pkg/sql/opt/memo/logical_props_builder.go` line 2209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86606#-NA78LuQEnMMYV4u0mPC:-NABfQJE67i2c2McKtcE:blrq08e) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a7e974a52134439b59419b8b813bc354c500da/pkg/sql/opt/memo/logical_props_builder.go#L2209)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This mechanism has been around since the early days of the optimizer, so it's definitely possible that it's just an artifact of that time and struct fields would be just as good if not better. Looking back at the old commits I don't see any obvious explanation for why this is a better approach.

The existing annotations (stats and func deps) are also logical properties, so it seemed consistent to add not null columns as well. We could definitely look into removing this mechanism altogether, but I'd rather do that in a different PR if it's ok with you, since I want to backport this change.
</blockquote></details>

Thanks for the context. And yes, no need to change this now, I was just asking for my own edification.

**Pull request merged**
