### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by tamird**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3712)

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 768 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712#-K7YDc55vOc8sBScf3Ph:-K7YDc55vOc8sBScf3Pi:-1824206234) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b4058831e1d27b36f9a5f358d83ef733cc5d435/storage/store.go#L768)):*
nit: I might clarify that the copy specifically allows releasing the RLock earlier, and thus the avoiding the doubly held lock, before showing the example call-tree. 

---

*[storage/store_testing.go, line 1 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712#-K7YFDcczffXkjJ0RoAQ:-K7YFDcczffXkjJ0RoAR:-517706281) ([raw file](https://github.com/cockroachdb/cockroach/blob/49098fab07965aa90da133c4b0be3f58e6fad740/storage/store_testing.go#L1)):*
2016?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 768 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712#-K7YDc55vOc8sBScf3Ph:-K7YIRfuFW5TME8jDTE6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b4058831e1d27b36f9a5f358d83ef733cc5d435/storage/store.go#L768)):*
Done.

---

*[storage/store_testing.go, line 1 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712#-K7YFDcczffXkjJ0RoAQ:-K7YISQYKr5rRLXTisXy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/49098fab07965aa90da133c4b0be3f58e6fad740/storage/store_testing.go#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712)*

**Comment by dt** [comment]
LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3712#-:-K7YJO6Ui9WgaOv1A8to:676834233)*

**Pull request merged**
