### PR TITLE
rpc: fix TestHeartbeatHealthTransport (again)

### LINKED ISSUE #18540: rpc: TestHeartbeatHealthTransport failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/2dea6ba656aca628bba8c089d2c5467d8b0ad374

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=353811&tab=buildLog

```
I170918 06:28:58.178488 121 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:56404->127.0.0.1:56081: use of closed network connection
I170918 06:28:58.178531 158 vendor/google.golang.org/grpc/grpclog/grpclog.go:60  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I170918 06:28:58.178830 152 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: authentication handshake failed: EOF"; Reconnecting to {127.0.0.1:56404 <nil>}
I170918 06:28:58.182350 163 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: Server.Serve failed to complete security handshake from "127.0.0.1:56084": write tcp 127.0.0.1:56404->127.0.0.1:56084: use of closed network connection
I170918 06:28:59.262514 137 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:56404->127.0.0.1:56142: use of closed network connection
I170918 06:28:59.262624 166 vendor/google.golang.org/grpc/grpclog/grpclog.go:60  transport: http2Client.notifyError got notified that the client transport was broken EOF.
	context_test.go:385: <nil>
```

### PR DESCRIPTION
**Pull request by tbg**
Make sure that after close the listener, there aren't any accepted-but-still-unhandled connections.

Fixes #18540.

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/context_test.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542#-KuL92o6GjjgCbtQE2F1:-KuL92o7ooJfa4a8iWO8:b-edgxrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad46075a8033796fab3ba3eb27ce82cafda8885c/pkg/rpc/context_test.go#L244)):*
> ```Go
> 
> 	if runtime.GOOS == "windows" {
> 		t.Skip("TODO(tamird): remove in Go 1.9; https://github.com/golang/go/commit/03d1aa6")
> ```

Do this in a separate commit, especially if you intend to cherry-pick this into 1.1.

---

*[pkg/rpc/context_test.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542#-KuL9LPxBCWrNRCLbMlX:-KuL9LPxBCWrNRCLbMlY:bqrm5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e1cd602917b16ddea171158da885cebf66f63e/pkg/rpc/context_test.go#L388)):*
> ```Go
> 	}
> 	if waitUnhealthy {
> 		t.Fatal("connection did not become unhealthy")
> ```

This could also occur if the connection became unhealthy then became healthy again. 

I'm confused about what's going on here. It seems like this should be two parts, a SucceedsSoon to wait for the connection to become unhealthy, and then this loop to ensure that it stays this way. But why doesn't the preceeding SucceedsSoon do that? Is it because the closeConns call comes before the one to ConnHealth? If you reorder those, do you still need this `waitUnhealthy` variable here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/context_test.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542#-KuL92o6GjjgCbtQE2F1:-KuPYvqHoz7EujmOXNdX:b-oz8tym) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad46075a8033796fab3ba3eb27ce82cafda8885c/pkg/rpc/context_test.go#L244)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do this in a separate commit, especially if you intend to cherry-pick this into 1.1.
</blockquote></details>

Good call.

---

*[pkg/rpc/context_test.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542#-KuL9LPxBCWrNRCLbMlX:-KuPYHiQXvdrGGXVuNVK:b-mnow88) ([raw file](https://github.com/cockroachdb/cockroach/blob/18e1cd602917b16ddea171158da885cebf66f63e/pkg/rpc/context_test.go#L388)):*
No, the basic problem is that we close the listener and wait for unhealthiness, but there's no guarantee that there wasn't a connection that was accepted but hasn't had a chance to get into the system.

> This could also occur if the connection became unhealthy then became healthy again.

Yeah, I agree this is too watered down. I'll refactor this once more to guarantee that once the listener is closed, there are no in-flight connections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542)*

**Comment by tschottdorf** [comment]
PTAL

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18542#-:-KuRMQN7O5c5N_-8dP95:bnfp4nl)*

**Pull request merged**
