### PR TITLE
grpcutil: debounce log spam when host has been removed from network

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes the log spam observed in
https://github.com/cockroachdb/cockroach/issues/9658#issuecomment-313474226

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/grpcutil/log.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16900#-KoO9N-rH2YZjA0em35C:-KoO9N-rH2YZjA0em35D:b9cl1pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/030a0884ae0aefdb03b7de2b1481bbfefd2d5c26/pkg/util/grpcutil/log.go#L74)):*
> ```Go
> 			regexp.QuoteMeta("No connection could be made because the target machine actively refused it"),
> 			// Host removed from the network and no longer resolvable
> 			regexp.QuoteMeta("no such host"),
> ```

Can you link to the specific error? https://github.com/golang/go/blob/go1.8.3/src/net/net.go#L566

The other errors here are OS-generated, which is why they aren't cited this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16900#-:-KoO9gg7y9WBOkaQ4hlu:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/grpcutil/log.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16900#-KoO9N-rH2YZjA0em35C:-KoOA2scNcRkqARx5znI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/030a0884ae0aefdb03b7de2b1481bbfefd2d5c26/pkg/util/grpcutil/log.go#L74)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Can you link to the specific error? https://github.com/golang/go/blob/go1.8.3/src/net/net.go#L566

The other errors here are OS-generated, which is why they aren't cited this way.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16900)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16900)*

**Pull request merged**
