### PR TITLE
dbconsole: overload page improvements

### LINKED ISSUE #120853: admission: Provide better description on Overload metrics page
The Overload metrics page of DB console has relatively sparse descriptions for the graphs, especially as you get further down the page and the graphs are generally more opaque.  We should provide more robust descriptions for the graphs on this page.  Examples:

image

image

Jira issue: CRDB-36902

Epic CRDB-36319

### PR DESCRIPTION
**Pull request by aadityasondhi**
This PR contains a series of improvements to the overload page of the DB console as part of https://github.com/cockroachdb/cockroach/issues/121574. It is separated into multiple commits for ease of review.

____

dbconsole: remove non useful charts on the overload page

In investigations, we have found that the following charts are not
useful and frequently cause confusion:
- Admission work rate
- Admission Delay rate
- Requests Waiting For Flow Tokens

Informs https://github.com/cockroachdb/cockroach/issues/121572

Release note (ui change): This patch removes "Admission Delay Rate",
"Admission Work Rate", and "Requests Waiting For Flow Tokens". These
charts often cause confusion and are not useful for general overload
investigations.

___

dbconsole: reorder overload page metrics for better readability

This patch reorders the existing metrics in a more usable order:
1. Metrics to help determine which resource is constrained (IO, CPU)
2. Metrics to narrow down which AC queues are seeing requests waiting
3. More advanced metrics about the system health (goroutine scheduler,
   L0 sublevels, etc.)

Informs https://github.com/cockroachdb/cockroach/issues/121572.

Release note (ui change): Reordering of metrics on the overload page to
help categorizing them better. They are roughly in the following order:
1. Metrics to help determine which resource is constrained (IO, CPU)
2. Metrics to narrow down which AC queues are seeing requests waiting
3. More advanced metrics about the system health (goroutine scheduler,
   L0 sublevels, etc.)

___

dbconsole: include better names and descriptions for overload page
This patch improves the metric descriptions for the metrics on the
overload page.

Fixes https://github.com/cockroachdb/cockroach/issues/120853.

Release note (ui change): The overload page now includes descriptions for all
metrics.

___

dbconsole: additional higher granularity metrics for overload

This patch adds additional metrics to the overload page that allow for
more granular look at the system:
- cr.store.storage.l0-sublevels
- cr.node.go.scheduler_latency-p99.9

Informs https://github.com/cockroachdb/cockroach/issues/121572.

Release note (ui change): Two additional metrics on the overload page
for better visibility into overloaded resources:
- cr.store.storage.l0-sublevels
- cr.node.go.scheduler_latency-p99.9

___

dbconsole: split Admission Queue graphs to avoid overcrowding

Informs https://github.com/cockroachdb/cockroach/issues/121572.

Release note (ui change): There are now 4 graphs for Admission Queue
Delay:
1. Foreground (regular) CPU work
2. Store (IO) work
3. Background (elastic) CPU work
4. Replication Admission Control, store overload on replicas

___

dbconsole: add elastic store metric to the overload page 

This patch uses the new sperated `elastic-stores` metrics for queing
delay from cockroachdb#123890.

Informs cockroachdb#121572.

Release note (ui change): The `Admission Queueing Delay – Store` chart
now separates elastic (background) work from the regular foreground
work.

___

dbconsole: add elastic io token exhausted duration to overload page 

This patch adds the metric `elastic_io_tokens_exhausted_duration.kv`
introduced in cockroachdb#124078.

Informs cockroachdb#121572.

Release note (ui change): The `Admission IO Tokens Exhausted` chart now
separates elastic and regular io work.

### CODE REVIEW

**Comment by aadityasondhi** [comment]
Some screenshots of the new page (in order of how the metrics show on the page).

https://docs.google.com/document/d/1txZ6zcAYR_8fnqR6LR53vCZ1dM6sZh0a52VUg_QIs78/edit?usp=sharing

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @abarganier)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWDfO7TgAzaVzYNz5:-NxFWDfPACDZhpf21OB7:bcammhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L39)):*
> ```XML
>       tenantSource={tenantSource}
>       showMetricsInTooltip={true}
>       tooltip={`CPU utilization as measured by the host, displayed per node.`}
> ```

CPU utilization for the CRDB process as measured ....
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWKcP5XMJkmmb1I4R:-NxFWKcP5XMJkmmb1I4S:b5uitcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L57)):*
> ```XML
>       tenantSource={tenantSource}
>       showMetricsInTooltip={true}
>       tooltip={`Duration of CPU slots exhaustion regular work, in microseconds. This metric indicates whether the CPU is overloaded and how long do we experience token exhaustion for regular work.`}
> ```

in microseconds/sec. ... we experience slot exhaustion for regular CPU work.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWUAY-Onqx5TPZ5hr:-NxFWUAY-Onqx5TPZ5hs:b-qonkjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L80)):*
> ```XML
>       tenantSource={tenantSource}
>       showMetricsInTooltip={true}
>       tooltip={`Duration of IO token exhaustion, in microseconds per second. This metric indicates whether the disk is overloaded and how long do we experience token exhaustion.`}
> ```

whether the store is overloaded ...
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWvFr-InXyxperXb5:-NxFWvFr-InXyxperXb6:bkm139k) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L99)):*
> ```XML
>       sources={storeSources}
>       tenantSource={tenantSource}
>       tooltip={`A 1-normalized IO overload score. A value above 1 indicates that the store is overloaded.`}
> ```

We don't want to change the definition of the metric yet, but the interpretation of this needs to change, and we can capture that in this comment. Something like:

Historically, a 1-normalized IO overload score. Currently, admission control attempts to maintain a score of 0.5.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFXZ8t5BJwwKXZrLjs:-NxFXZ8u1VkoNOc6DyeQ:b-w4hsm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L140)):*
> ```XML
> 
>     <LineGraph
>       title="Flow Tokens Wait Time: 99th percentile"
> ```

We should consider using the term "queuing delay" in this and other queue delay metrics. Consider calling this:

Flow Tokens Queueing Delay: 99th percentile
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 289 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFc2uX230MM6jo1WER:-NxFc2uX230MM6jo1WES:b-6982ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L289)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`P99 scheduling latency for goroutines. A value above 1ms typically indicates high load.`}
> ```

... indicates high load that causes elastic CPU work to be throttled.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 311 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFcCyR0NAzdkynmgoP:-NxFcCyR0NAzdkynmgoQ:bc0drr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L311)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`P99.9 scheduling latency for goroutines. A value above 1ms typically indicates high load.`}
> ```

we shouldn't say "A value above 1ms typically indicates high load" since we don't really know whether it indicates high load. This is just useful in realizing whether some high percentile user observed latency could be due to goroutine scheduling latency.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFcWxy8iOfVMhN3zEH:-NxFcWxy8iOfVMhN3zEI:bpuxcf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L333)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`The number of Goroutines waiting per CPU. A value above 32 typically indicates high load.`}
> ```

We should say: A value above 32 (sampled at 1ms) is used by admission control to throttle regular CPU work.

Instead of saying "A value above 32 typically indicates high load" since the former is more specific. The latter may result in someone thinking < 32 is not high load.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 351 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFdCeq-yPvMu97M-ps:-NxFdCeq-yPvMu97M-pt:buhtqba) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L351)):*
> ```XML
>       sources={storeSources}
>       tenantSource={tenantSource}
>       tooltip={`Number of sublevels in L0 of the LSM. A value above 20 typically indicates that the store is overloaded.`}
> ```

above 10 

(which happens to correspond to a score of 0.5)

**Review by aadityasondhi — COMMENTED** [review]
TFTR! I have made the changes PTAL. I also added a new commit to split the queue graphs as we discussed offline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-:-NxK35kYAe4Btb4YnXuY:b-y6wd6z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWKcP5XMJkmmb1I4R:-NxK2stOA9rBnGCVfRCa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

in microseconds/sec. ... we experience slot exhaustion for regular CPU work.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWUAY-Onqx5TPZ5hr:-NxK2tSX1MXkI-TZett9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L80)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

whether the store is overloaded ...
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFWvFr-InXyxperXb5:-NxK2xeCDgN-axKeqzSD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L99)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We don't want to change the definition of the metric yet, but the interpretation of this needs to change, and we can capture that in this comment. Something like:

Historically, a 1-normalized IO overload score. Currently, admission control attempts to maintain a score of 0.5.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFXZ8t5BJwwKXZrLjs:-NxK2yXg2z7UyASsephk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L140)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should consider using the term "queuing delay" in this and other queue delay metrics. Consider calling this:

Flow Tokens Queueing Delay: 99th percentile
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 289 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFc2uX230MM6jo1WER:-NxK30wOCOELRDh7OQ19:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L289)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... indicates high load that causes elastic CPU work to be throttled.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 311 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFcCyR0NAzdkynmgoP:-NxK31a9AeYsqRPHfI2A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L311)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we shouldn't say "A value above 1ms typically indicates high load" since we don't really know whether it indicates high load. This is just useful in realizing whether some high percentile user observed latency could be due to goroutine scheduling latency.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFcWxy8iOfVMhN3zEH:-NxK31vR3xfbx9_NbccZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L333)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We should say: A value above 32 (sampled at 1ms) is used by admission control to throttle regular CPU work.

Instead of saying "A value above 32 typically indicates high load" since the former is more specific. The latter may result in someone thinking < 32 is not high load.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 351 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxFdCeq-yPvMu97M-ps:-NxK3318854viDeidtII:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/499c4e5ce8071ad5619564baf72592da43fd0496/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L351)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

above 10 

(which happens to correspond to a score of 0.5)
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-:-NxOYV6p7A_BjRMncZRv:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @abarganier)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 180 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxOWITf2pjm0GmfygIf:-NxOWITg00X_A6eu5AJ-:bf320s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba86f547e33d8228d8c3a43c7509b2f2423ddf52/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L180)):*
> ```XML
> 
>     <LineGraph
>       title="Admission Queueing Delay – Store"
> ```

I just noticed there is a problem here in our code instrumentation. The metrics passed to `initWorkQueue` for the regular WorkQueue and elastic WorkQueue for a store are the same. So this will include queueing delay for elastic and regular. I think it is worth making a note here and mention in the tooltip that to break this down one should look at the per priority metrics.

I think we should fix this in the code and backport. And we could avoid plotting the p99 for the elastic store `WorkQueue` since that queueing should all be logical queueing due to replication AC, and the physical queueing effect of that is already reflected in `kvadmission.flow_controller.elastic_wait_duration-p99`. Though thinking some more, since the flow controller metric is at the source and the WorkQueue metric is at the destination, both can be useful -- the latter tells us the cause, and the former about who is affected.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 326 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxOY2HtEdImtplNlLDi:-NxOY2HtEdImtplNlLDj:bge6hqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba86f547e33d8228d8c3a43c7509b2f2423ddf52/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L326)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`P99 scheduling latency for goroutines. A high value here indicates high load that causes background (elastic) CPU work to be throttled.`}
> ```

A value above 1ms here indicates high load ...
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 348 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NxOY6SH2Ffw8MbDiUAR:-NxOY6SH2Ffw8MbDiUAS:blagpev) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba86f547e33d8228d8c3a43c7509b2f2423ddf52/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L348)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`P99.9 scheduling latency for goroutines. A high value here indicates high load that causes background (elastic) CPU work to be throttled.`}
> ```

something generic like the following, since we don't use p99.9 in AC decision making:
A high value here can be indicative of high tail latency in various queries.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-:-NxSuVc4BofWJnNYmOiZ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @abarganier)

**Comment by aadityasondhi** [comment]
@sumeerbhola could you please take a look at the last two commits. They are follow ups from https://github.com/cockroachdb/cockroach/pull/124078 and https://github.com/cockroachdb/cockroach/pull/123890.

Just adding those metrics in with their `regular` counterparts.

**Comment by aadityasondhi** [comment]
Apologies for the noise. Bad rebase.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-:-NyRLzEfBjKheWTkcany:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @abarganier)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 155 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NyR2dCyCvfDEGKKumrb:-NyR2dCyCvfDEGKKumrc:b-flfrhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7258e95cffccfe371d2c174659b2725ceed18b2b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L155)):*
> ```XML
> 
>     <LineGraph
>       title="Admission Queueing Delay – Foreground (Regular) CPU"
> ```

nit: I have a mild preference for putting "p99" in the titles too. Since not everyone looks at the tooltip.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123522)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 155 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/123522#-NyR2dCyCvfDEGKKumrb:-NyROTHr5aL5k6VOgWnI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7258e95cffccfe371d2c174659b2725ceed18b2b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L155)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: I have a mild preference for putting "p99" in the titles too. Since not everyone looks at the tooltip.
</blockquote></details>

Done.

**Comment by aadityasondhi** [comment]
TFTR!

bors r=sumeerbhola

**Pull request merged**
