### PR TITLE
Request version in the issue template

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Done already in #27811

**Comment by tim-o** [comment]
Hey @knz - I added your changes to a PR I already had open to make some other adjustments to the template: https://github.com/cockroachdb/cockroach/pull/27811. I'll close this since the changes you suggested have been pushed.

**Comment by knz** [comment]
The other PR was merged somewhere else than `master` so the changes were actually not performed. So I am re-opening this PR. Please review.

**Review by tim-o — APPROVED** [review]
Merged changes from the other branch here, apologies for the error.

**Comment by knz** [comment]
thank you!

bors r+

**Pull request merged**
