### PR TITLE
sql: introduce intermediate results logger for debugging

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit introduces a new processor that passes rows through and logs
all of them for debugging purposes. Both a processor and a columnar
operator are added. The logger is added after every processor in the
plan. It is enabled by the cluster setting
'sql.distsql.log_intermediate_results.enabled'.

Release note (sql change): A new cluster setting
'sql.distsql.log_intermediate_results.enabled' is introduced which allows
for logging all intermediate results during DistSQL execution.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
This is a good idea. I wonder if we could do more to integrate it into our tracing infrastructure? We should see if it makes sense to do so so that we could in the future leverage the structure of traces for visualizations.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-:-Lv5Mqn12dph435BYmBf:b-8cqskv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/intermediate_results_logger.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5Mc7z8dzlBzUI38Iz:-Lv5Mc7z8dzlBzUI38J-:b-pj38qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/colexec/intermediate_results_logger.go#L50)):*
> ```Go
> func (n *intermediateResultsLogger) Next(ctx context.Context) coldata.Batch {
> 	b := n.input.Next(ctx)
> 	if b.Length() > 0 {
> ```

nit: it's usually nicer to have the shorter conditional with a return first: `if b.Length == 0 { return ... }` in order to not indent the larger block of code.
___
*[pkg/sql/rowexec/intermediate_results_logger.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5MSRJ4RDI3lkVXGjI:-Lv5MSRJ4RDI3lkVXGjJ:buho3e3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/rowexec/intermediate_results_logger.go#L90)):*
> ```Go
> 		if outRow := n.ProcessRowHelper(row); outRow != nil {
> 			// TODO(yuzefovich): I can't seem to figure out which types to pass into
> 			// outRow.String(). I tried n.input.OutputTypes() and n.OutputTypes(),
> ```

That's surprising. `n.input.OutputTypes()` should match up exactly with the schema of the `row` returned from `Next`, there might be some extra digging to do here.

**Review by yuzefovich — COMMENTED** [review]
This was Jordan's idea. He suggested doing this to figure out what's causing the failure of `tpchvec` roachtest (where - at first glance - there seemed to be precision problems).

Do you have an example of what you mean by better integration with tracing? Maybe a pointer at how we do KV traces (since I only looked at the stats propagation via the tracing infra previously)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-:-LvMU9rZAhPlPH0Tsm7C:bwtll8t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/intermediate_results_logger.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5Mc7z8dzlBzUI38Iz:-LvMQd2W3luPucRob-Uc:boazho4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/colexec/intermediate_results_logger.go#L50)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: it's usually nicer to have the shorter conditional with a return first: `if b.Length == 0 { return ... }` in order to not indent the larger block of code.
</blockquote></details>

Indeed, that looked weird. Done.
___
*[pkg/sql/rowexec/intermediate_results_logger.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5MSRJ4RDI3lkVXGjI:-LvMQwu18_RYgRlM5pyj:b-gx6gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/rowexec/intermediate_results_logger.go#L90)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That's surprising. `n.input.OutputTypes()` should match up exactly with the schema of the `row` returned from `Next`, there might be some extra digging to do here.
</blockquote></details>

I spent an hour or two when I opened up the PR initially trying to understand the root cause but got nowhere. My hunch is that introduction of a new processor after each other processor somehow screws up the post-processing specs so that there is a mismatch between input schema and output schema for this logger processor.

**Review by asubiotto — COMMENTED** [review]
Take a look at the `traceKV` flag in the fetcher. It should be as simple as creating a span for the input operator and then logging the result rows into it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-:-LveRB79Az65E5y25ds2:b-3vl7ox)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowexec/intermediate_results_logger.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5MSRJ4RDI3lkVXGjI:-LveRQ710IpwvQiSREjj:bsdevui) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/rowexec/intermediate_results_logger.go#L90)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I spent an hour or two when I opened up the PR initially trying to understand the root cause but got nowhere. My hunch is that introduction of a new processor after each other processor somehow screws up the post-processing specs so that there is a mismatch between input schema and output schema for this logger processor.
</blockquote></details>

Do you think it's worth tracking down the root cause? It seems bad to have a type mismatch, even if it's just a logger processor.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/intermediate_results_logger.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42796#-Lv5MSRJ4RDI3lkVXGjI:-LwEojkD6IORU5EUJTw9:bpo1xyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62603912bdd6123984d1e24caa952fd98083bf/pkg/sql/rowexec/intermediate_results_logger.go#L90)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you think it's worth tracking down the root cause? It seems bad to have a type mismatch, even if it's just a logger processor.
</blockquote></details>

I looked into this when flying back to SF. Indeed, my hunch was correct - the insertion of this logger into the physical plan messed up adding rendering and projections, so the trivial solution I'm proposing in this PR doesn't work. I thought more about it and realized that we probably want to capture the intermediate results during the post-processing step - this way we don't need to modify the physical plan. And as it turns out, there is already some logging going on in there which more or less accomplishes what I wanted to do. I'll open up a separate PR with some tweaks.

**Comment by yuzefovich** [comment]
I'll open a separate PR, so I'm closing this one.

**Pull request closed without merging**
