### PR TITLE
opt: improve selectivity estimates

### LINKED ISSUE #30226: opt: Statistics builder makes inconsistent row estimates when constraints are tight
REPRO:
Look at the plans (with row estimates) for the following queries against the TPCH schema:
```
SELECT *
FROM lineitem
WHERE
    l_shipdate >= DATE '1995-09-01'
    AND l_shipdate < DATE '1995-10-01';

SELECT *
FROM lineitem
WHERE
    l_shipdate >= DATE '1995-09-01'
    AND l_shipdate::timestamptz < DATE '1995-10-01';
```
This is a simplified version of Q14.

ACTUAL: The optimizer estimates 333 rows will be returned for the first query and only 111 rows for the second query.

EXPECTED: Both queries should estimate 111 rows. The optimizer should use a min row count = 1/3 ** #conjuncts, as if every conjunct were unknown.

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, the statistics_builder in the optimizer
treated all constraints the same if they could not be applied to
the calculation of distinct counts. Constraints such as
`/a: [/'bar' - /'foo']` had the same selectivity as `/a: [/'bar' - ]`,
i.e., `1/3`.

This commit instead tries to estimate the number of conjuncts used
to build a given constraint, and uses selectivity `1/3` for each
conjunct. As a result, the selectivity of `/a: [/'bar' - /'foo']`
is now estimated to be `1/3 * 1/3 = 1/9`.

This commit also adds a hack to ensure that `x IS NOT NULL` is
considered less selective than other inequalities such as `x > 5`.
Once we track null counts, we can remove the hack and make this
more precise.

Fixes #30226

Release note: None

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-LMh3Xfp5G5mDlWBz589:-LMh3XfqBqWr6iR-vUMx:bt7utfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4111e1b4e96ac538a48d116af21fcccf88d20f1/pkg/sql/opt/memo/statistics_builder.go#L1735)):*
> ```Go
> // numConjunctsInConstraint returns a rough estimate of the number of conjuncts
> // used to build the given constraint.
> func (sb *statisticsBuilder) numConjunctsInConstraint(
> ```

How come we need to estimate this? We have the original conjuncts. What's wrong with computing `1/3 ** #conjuncts` and then using that as max distinct count?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-LMh3Xfp5G5mDlWBz589:-LMh4mNIBTeZ2UvbPNww:bfl47py) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4111e1b4e96ac538a48d116af21fcccf88d20f1/pkg/sql/opt/memo/statistics_builder.go#L1735)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come we need to estimate this? We have the original conjuncts. What's wrong with computing `1/3 ** #conjuncts` and then using that as max distinct count?
</blockquote></details>

The problem is that some of the constraints may have been applied, and it's not trivial to map the conjuncts to constraints.  I did it this way so that we're only computing `1/3 ** #conjuncts` for unapplied conjuncts.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-LMoQvCw1STCL7PFfjA0:-LMoQvCw1STCL7PFfjA1:bldcl8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/63cbd2e7686e102d8fcfb1095974e8ea06131dce/pkg/sql/opt/memo/statistics_builder.go#L1743)):*
> ```Go
> 	}
> 
> 	span := c.Spans.Get(0)
> ```

Seems strange that we base everything off the first span.. Maybe we should compute a "numConjuncts" for each span and return the minimum one?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-LMoQvCw1STCL7PFfjA0:-LMsimjl4Kf0prhWL3H5:br6bb4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/63cbd2e7686e102d8fcfb1095974e8ea06131dce/pkg/sql/opt/memo/statistics_builder.go#L1743)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Seems strange that we base everything off the first span.. Maybe we should compute a "numConjuncts" for each span and return the minimum one?
</blockquote></details>

Good idea - done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-:-LMstZeJ3zN2Jt1e0-QJ:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by rytaft** [comment]
Thanks! @andy-kimball, ok to merge?

**Review by andy-kimball — APPROVED** [review]
:lgtm:  Re: null counts, we should have reasonable behavior even when we don't have null counts available. I assume we'll have some default estimate for null count like we do for distinct count.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-:-LMt8vYs8IUkR00e_dk3:b-z74fgu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — COMMENTED** [review]
TFTR!

> I assume we'll have some default estimate for null count like we do for distinct count.

Yea, I agree. cc @itsbilal, who is planning to work on this next.

I made a small change to `numConjunctsInConstraint` since I realized we should only be looking at the first start and end key in each span. `/a/b: [/5 - ]` is more selective than `/a/b: [/4/5 - ]`, which is more selective than`/a/b: [/4 - ]`. But we should treat them all the same, with selectivity=1/3. Added a comment to that effect as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-:-LMxWatECBqrnc48I-w2:bezx4fn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30336#-:-LMyDcw61fiJhhYN4ZXY:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
