### PR TITLE
clusterversion: bump MinSupported to 24.2

### PR DESCRIPTION
**Pull request by RaduBerinde**
Once we advance the version to to 25.1, we will bump again to 24.3

Epic: REL-1292
Release note: None

### CODE REVIEW

**Review by celiala — DISMISSED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134340)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @jbowens, @mgartner, @nameisbhaskar, @RaduBerinde, and @rail)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB26IUBBh_333Jv6ZTH:-OB26IUBBh_333Jv6ZTI:b-svetpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades#L31)):*
> ```
> ----
> Seed:               12345
> Upgrades:           v23.1.4 → v23.2.0 → v24.1.1 → <current>
> ```

it seems like we should keep v24.1, since v24.1 is the regular release?

so perhaps instead [once .0 comes out]:

 v23.1.4 → v23.2.0 → v24.1.1 → v24.3.0 → <current>
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_skip_version` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB28AC759ZuIRcaTfwD:-OB28AC759ZuIRcaTfwE:birvfz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/106735320bea8e97948641d05ebcceef19c2da57/pkg/sql/logictest/testdata/logic_test/upgrade_skip_version#L2)):*
> ```
> # TODO(radu): reenable this test in 25.2 when we support upgrade from two
> # previous releases.
> ```

let's x-reference this tracking issue, so we don't forget:

https://github.com/cockroachdb/cockroach/issues/134455
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB28iSC-fylFNBOQVu5:-OB28iSC-fylFNBOQVu6:b95olpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go#L247)):*
> ```Go
> 			numUpgrades:       3,
> 			enableSkipVersion: true,
> 			expectedReleases:  []string{"23.1.17", "23.2.4", "24.1.1"},
> ```

should we leave a 24.1 release here?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-:-OB2DvSYBWBNdPavmrNE:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @celiala, @DarrylWong, @jbowens, @mgartner, @nameisbhaskar, and @rail)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB26IUBBh_333Jv6ZTH:-OB2CODf78JsxN-DPR4Y:bisw4ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades#L31)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

it seems like we should keep v24.1, since v24.1 is the regular release?

so perhaps instead [once .0 comes out]:

 v23.1.4 → v23.2.0 → v24.1.1 → v24.3.0 → <current>
</blockquote></details>

As far as I understand, this is the randomized sequence of versions that the test decides on with that seed. The old version was deciding to do a 24.2->current upgrade which is no longer allowed. It now chooses to skip 24.1 because 24.2 supported skipping experimentally.

Note that the test only sometimes allows skipping versions (with a random probability) so both ways get tested.
___
*[`pkg/sql/logictest/testdata/logic_test/upgrade_skip_version` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB28AC759ZuIRcaTfwD:-OB2CvVM1Y5hulfMiTvb:b-fznoh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/106735320bea8e97948641d05ebcceef19c2da57/pkg/sql/logictest/testdata/logic_test/upgrade_skip_version#L2)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

let's x-reference this tracking issue, so we don't forget:

https://github.com/cockroachdb/cockroach/issues/134455
</blockquote></details>

Good idea, done!
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB28iSC-fylFNBOQVu5:-OB2DX3zCdqrGi1h2c9w:b2xfn2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go#L247)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

should we leave a 24.1 release here?
</blockquote></details>

Like before, this is testing the logic of the test itself which always skips the latest possible skippable release in the chain (when version skipping is enabled).

**Review by celiala — APPROVED** [review]
thank you! :lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-:-OB2LWt_6UY0Zv8pBhYy:b-e4k8a7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @jbowens, @mgartner, @nameisbhaskar, @RaduBerinde, and @rail)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB26IUBBh_333Jv6ZTH:-OB2LAbK8f1lHC_Tqg55:b-g8epcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

As far as I understand, this is the randomized sequence of versions that the test decides on with that seed. The old version was deciding to do a 24.2->current upgrade which is no longer allowed. It now chooses to skip 24.1 because 24.2 supported skipping experimentally.

Note that the test only sometimes allows skipping versions (with a random probability) so both ways get tested.
</blockquote></details>

ah, thanks for the context. makes sense :thumbsup: 
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134340#-OB28iSC-fylFNBOQVu5:-OB2LT9FB5V9xDux4bjM:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/03e522af7d96f1f4c1a50902eaf7d95f07fbf242/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Like before, this is testing the logic of the test itself which always skips the latest possible skippable release in the chain (when version skipping is enabled).
</blockquote></details>

:thumbsup:

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Comment by RaduBerinde** [comment]
I got a failure "store last used with cockroach version v23.2 is too old for running version v24.2". Upgrading directly from 23.2 to 24.2 required `COCKROACH_ALLOW_VERSION_SKIPPING` which we no longer set in the test. Updating the logic to not allow any skip upgrades to 24.2.

**Pull request merged**
