### PR TITLE
log: minor copyedits to fatal error postamble

### PR DESCRIPTION
**Pull request by couchand**
A followup to #30898 with a few minor edits.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: mod comment

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30918#-:-LNu9OetCGVqBRwdGWPz:b-pgjf66)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/log/clog.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30918#-LNu9Enb0MTNcK4QCVDC:-LNu9Enb0MTNcK4QCVDD:b-n69gul) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5fd84ae1905f5b7f0e2c11267721026aade635/pkg/util/log/clog.go#L63)):*
> ```Go
> Please submit a crash report by following the instructions here:
> 
>     https://github.com/cockroachdb/cockroach/issues/new?template=bug_report.md
> ```

I intentionally didn't hard-code the template here. We're releasing this, and we might change the template, which drops users into a void instead: https://github.com/cockroachdb/cockroach/issues/new?template=bug_report_nope.md

**Comment by couchand** [comment]
> I intentionally didn't hard-code the template here. We're releasing this, and we might change the template

I had a similar thought.  What if we added a lint that the template must exist?

OTOH, we could make a shortlink that redirects here and then we're insulated if it needs to change to anything else, too...

**Review by tbg — COMMENTED** [review]
I personally would KISS here (the funnel will break as people fudge with the log files and realize they don't have a black hole to through them in, etc) but a lint sounds OK too. The shortlink option adds another link that can break so I'd rather not follow that direction.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30918#-:-LNuD4eA4RWQ44LZ2yp_:bex3vhz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by couchand** [comment]
Exactly right on the funnel: trying to remove a click was to shorten it.

Going with your original link for now to keep it simple.  The choose page also feels more like a landing page, whereas the bug report template itself is another big wall of text to parse, good to have a moment in between them.

**Comment by couchand** [comment]
bors r=tschottdorf

**Comment by tschottdorf** [comment]
Thanks @couchand. I'll backport my change and slap this on top of it.

**Pull request merged**
