### PR TITLE
workload/bank: batch initial row generation

### PR DESCRIPTION
**Pull request by danhhz**
Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39719#-:-LmjWJBnA5fUp2C-lZuy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/workload/bank/bank.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39719#-LmjUPdRCHv-EkoxSmji:-LmjUPdRCHv-EkoxSmjj:bysbjye) ([raw file](https://github.com/cockroachdb/cockroach/blob/38b3550c8ba8dc9e6bdb0b3007147ef9687d250d/pkg/workload/bank/bank.go#L129)):*
> ```Go
> // Tables implements the Generator interface.
> func (b *bank) Tables() []workload.Table {
> 	numBatches := int(math.Ceil(float64(b.rows) / float64(b.batchSize)))
> ```

Float arithmetic seems like it could cause issues. I'd favor integer arithmetic for something like this:
```
numBatches := (b.rows + b.batchSize - 1) / b.batchSize // ceil(b.rows/b.batchSize)
```

**Review by danhhz — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39719#-:-LmjogBI0i5RkrxPiwrH:b-l0r5kv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/workload/bank/bank.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39719#-LmjUPdRCHv-EkoxSmji:-LmjoZZoCwqsFEnvy9X9:byxccqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/38b3550c8ba8dc9e6bdb0b3007147ef9687d250d/pkg/workload/bank/bank.go#L129)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Float arithmetic seems like it could cause issues. I'd favor integer arithmetic for something like this:
```
numBatches := (b.rows + b.batchSize - 1) / b.batchSize // ceil(b.rows/b.batchSize)
```
</blockquote></details>

Whoops, totally agree. I meant to go back and do that myself before I PR'd this and forgot. Done

**Comment by danhhz** [comment]
Fixed my broken tests

bors r=nvanbenschoten

**Comment by danhhz** [comment]
Flake is #39653

bors r=nvanbenschoten

**Pull request merged**
