### PR TITLE
ui: fix database index and grants table sort and url

### LINKED ISSUE #85242: All sorts are selected on index stats on Table Details
When opening a Table Details page, the table for index stats have all columns with the sorting selected. Once any of them is clicked, it works as expected. 
Fix the default sorting to the total reads column

Screen Shot 2022-07-28 at 11 29 57 AM

Jira issue: CRDB-18132

### PR DESCRIPTION
**Pull request by j82w**
Before:
Going to the database page and navigating to a table page the index and grant table did not have a selected sort column. After selecting the sort it used the same object to store the sort for both tables. Selecting the sort on one table would cause the other table to lose the sort. The URL was also not updated to match the sort changes.
https://www.loom.com/share/d5f78053490349a49679371ea54ad43c

After:
Going to the database page and navigating to a table page the index and grant table both have a selected sort column, and update the URL to match the change.

https://www.loom.com/share/b565777690504f6bb87c5b23c23d9dc1

closes #85242

Screen Shot 2022-09-08 at 2 18 05 PM

Release justification: Category 2: Bug fixes and
low-risk updates to new functionality

Release note: (ui change): Fixed the index
and grant sorting on the database page to
have default column and to have url match
the user selection.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87632#-NBTMdzk2mnokT42hlvN):*
try adding more information to your PR description, using the template we show when committing something. 
Explaining what was happening previously and what this commit is doing.
Also, when the fix in on a behaviour that you can see just from the image, is good to add a video showing it working, you can use loom for it

**Comment by j82w** [comment]
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87632#-NBTMdzk2mnokT42hlvN):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

try adding more information to your PR description, using the template we show when committing something. 
Explaining what was happening previously and what this commit is doing.
Also, when the fix in on a behaviour that you can see just from the image, is good to add a video showing it working, you can use loom for it
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87632#-:-NBYPH_Y-eqo7HGk5I_j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Pull request merged**
