### PR TITLE
serverutils: change StartTenant to start a tenant with a given tenant ID

### PR DESCRIPTION
**Pull request by asubiotto**
The tenant was previously running with a system tenant ID.

Release note: None (testing change)

### CODE REVIEW

**Comment by asubiotto** [comment]
The plan is to triage the new logic test failures at a later date with the other logic test failures.

**Review by tbg — APPROVED** [review]
Thanks!

**Review by nvb — APPROVED** [review]
:lgtm: exciting!

> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49547#-:-M8ItZ7M7cKtjmc2TVns:bry284r)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
TFTR

bors r=tbg,nvanbenschoten

**Comment by tbg** [comment]
Friendly reminder to use the A-multitenancy label (already added!)

**Pull request merged**
