### PR TITLE
datadriven: move arg parsing into datadriven

### PR DESCRIPTION
**Pull request by RaduBerinde**
We have a few separate places where we parse the args into keys and
values. Moving this code in the datadriven wrapper.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: Nice consolidation

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/testutils/datadriven/datadriven.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281#-L6YSOfypJC2CiMuzIsn:-L6YSOfypJC2CiMuzIso:b-nisw6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9957e5ca26d09b9ec6bbce7b9fe954f9e0947ec/pkg/testutils/datadriven/datadriven.go#L126)):*
> ```Go
> //  - argument
> //  - argument=value
> //  - argument=(values, ...)
> ```

can you also give an example of the entire line? e.g. `cmd argument1=val1 argument2`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281#-:-L6YTTqeywk7eyMu6O_3:bbraauw)*

**Comment by RaduBerinde** [comment]
*[pkg/testutils/datadriven/datadriven.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281#-L6YSOfypJC2CiMuzIsn:-L6YUXJ8Q0ZM8ryjmTgq:b-e7pupw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9957e5ca26d09b9ec6bbce7b9fe954f9e0947ec/pkg/testutils/datadriven/datadriven.go#L126)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can you also give an example of the entire line? e.g. `cmd argument1=val1 argument2`
</blockquote></details>

There is a detailed description above (RunTest comment).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/testutils/datadriven/datadriven.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281#-L6YSOfypJC2CiMuzIsn:-L6YVnHVDC6IAP4Q-M8K:bb9lnpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9957e5ca26d09b9ec6bbce7b9fe954f9e0947ec/pkg/testutils/datadriven/datadriven.go#L126)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There is a detailed description above (RunTest comment).
</blockquote></details>

Ah I see - thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23281)*

**Comment by andy-kimball** [comment]
:lgtm:
The datadriven package is becoming really handy.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23281#-:-L6YhvQY94OVcVVblhds:b87e1an)*

**Pull request merged**
