### PR TITLE
kvclient/rangefeed: emit checkpoint events

### PR DESCRIPTION
**Pull request by irfansharif**
Grafted from #69269. This seems like a useful primitive for users of
this library. We intend to use it in #69661 and #69614.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
A test might be nice. I don't think it should be too hard. Namely, write a value and then make sure that you get a checkpoint after you write the value for a timestamp later than the value. You can adjust the closed timestamp interval to make this happen quickly. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70317#-:-MjjEIBw2X0sKtcx8SJf:b-sntlv3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by irfansharif — COMMENTED** [review]
Added, PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70317#-:-Mk3LOV71Zm0cJnpeUa3:boe53tc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70317#-:-Mk3OJIx-UNEzK06cxPH:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by irfansharif** [comment]
bors single on

**Comment by irfansharif** [comment]
I'm not really sure what's up with the bors failure. I assume it's some flake, cause regular github CI is green. Let a brother merge before PTO!

bors r+

**Pull request merged**
