### PR TITLE
sql: misc changes to support sqllogictest

### PR DESCRIPTION
**Pull request by tamird**
various things I discovered while trying to enable the aggregate tests

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3551)

### CODE REVIEW

**Comment by petermattis** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 4 of 4 files at r4, 2 of 2 files at r5.
Review status: 12 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/parser/eval.go, line 235 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jfoH0YyMqm5n16qv1:-K6jfoH1JunqcmVnO14X:155402475) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af212ae231cdc45d48251e7cec99ffb6417801/sql/parser/eval.go#L235)):*
This seems like a half-effort. We should either prohibit automatic conversions from `int` to `float` or we should allow them everywhere. Why allow such conversions only for multiplication and not for addition and subtraction?

---

*[sql/parser/expr.go, line 639 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jf4wNcFdBVVP9sbRG:-K6jf4wNcFdBVVP9sbRH:812992896) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a4b4f7ab2e9c65b35e62dde6e19706f8aa8ae76/sql/parser/expr.go#L639)):*
I'd rather this be an int type similar to `BinaryOp`. See what is done with `binaryOpName` to make printing of the values easy.

---

*[sql/parser/expr.go, line 644 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jfEri04Fq_P2KyRs2:-K6jfEri04Fq_P2KyRs3:24368967) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a4b4f7ab2e9c65b35e62dde6e19706f8aa8ae76/sql/parser/expr.go#L644)):*
Can these be named `Distinct` and `All`? The `Ast` prefix seen some places is a hold over from the vitess code.

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jdJ0CPd5hz3w8JE0g:-56405550) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
Was there a bug with the previous code where these "partial" expressions were outputting with a leading space?

---

*[sql/testdata/aggregate, line 37 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jg_8exTcrDCOwXO9-:-K6jg_8exTcrDCOwXO90:-1066958722) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/testdata/aggregate#L37)):*
So the `MIN(1)` constant evaluates to `1`? I think it might be better for aggregate functions to never get simplified by constant evaluation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by tamird** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/parser/eval.go, line 235 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jfoH0YyMqm5n16qv1:-K6jiQndmQRERiU6JThV:-1695215227) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af212ae231cdc45d48251e7cec99ffb6417801/sql/parser/eval.go#L235)):*
You're right. I've removed this commit as it's part of a bigger int-to-float upcasting conversation.

---

*[sql/parser/expr.go, line 639 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jf4wNcFdBVVP9sbRG:-K6jiNgympUTxfung4RT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a4b4f7ab2e9c65b35e62dde6e19706f8aa8ae76/sql/parser/expr.go#L639)):*
Done.

---

*[sql/parser/expr.go, line 644 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jfEri04Fq_P2KyRs2:-K6jh2Cpjkm4vlpEoTes:-485110604) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a4b4f7ab2e9c65b35e62dde6e19706f8aa8ae76/sql/parser/expr.go#L644)):*
Sure.

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jhU-hJgRHu8Aytlg7:-915856213) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
Yes. "unsupported FROM: %s" was outputting with a double space

---

*[sql/testdata/aggregate, line 37 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jg_8exTcrDCOwXO9-:-K6jgvuRhGOLbM5IH9nS:-1952154506) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/testdata/aggregate#L37)):*
Why not? MIN(1) is totally a valid simplification.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by petermattis** [comment]
Review status: 7 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jkL5DfluzLVPaskCB:-1663002243) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
Seems easier to just fix those error messages (and add a test case that they are formatted correctly). There are also a bunch of gratuitous changes here while you could have just removed the leading space.

---

*[sql/testdata/aggregate, line 37 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jg_8exTcrDCOwXO9-:-K6jkf3qPJirSOFCaNZO:613839840) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/testdata/aggregate#L37)):*
I just worry that not using the render expressions is going to cause other headaches. Let me look at this more closely.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by tamird** [comment]
Review status: 7 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jlBxNmgTFKAUpFxw2:2045952637) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
That's true. Now that this is done, do you want to see it backed out?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by petermattis** [comment]
Review status: 7 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/group.go, line 53 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jn0b-_-jAjFDto27l:-K6jn0b0Rg2ryEJQha-r:-574971073) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a970d5023caeaff74391f1fa0d3713fb9cd477c/sql/group.go#L53)):*
Ok, I looked at this closer and think this is ok. I think you should add a comment here explaining what is going on and why: 

```
// Determine if aggregation is being performed. This check is done on the raw Select expressions
// as simplification might have removed aggregation functions (e.g. `SELECT MIN(1)` -> `SELECT 1`).
```

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jlj6wnY0tbRIDTEZE:-1658393008) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
The implementation of `Select.String` is much less readable now. And the gratuitous changes should be reverted regardless unless there is some good rationale there that I'm not seeing (i.e. the new code has better performance or avoids a buggy pattern).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by tamird** [comment]
Review status: 7 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/group.go, line 53 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jn0b-_-jAjFDto27l:-K6jnqSFsAE7qsfLB8n_:99173412) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a970d5023caeaff74391f1fa0d3713fb9cd477c/sql/group.go#L53)):*
Stolen verbatim.

---

*[sql/parser/select.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jdJ0CPd5hz3w8JE0f:-K6jnuRb3Ej70v11SZT0:-150303124) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf515555fea1164943c3ca72e629a868839068a2/sql/parser/select.go#L274)):*
I'll leave this commit out for now, since it doesn't have tests anyhow.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by dt** [comment]
Review status: 4 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/group.go, line 364 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jinIEymva2Ku77dtT:-K6jinIEymva2Ku77dtU:-1598491478) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/group.go#L364)):*
Does it makes sense to also early-return here if v.aggregated is true, to prevent further recursion sooner?

---

*[sql/testdata/aggregate, line 32 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6joRTneYZH0cR81Qkp:-K6joRTneYZH0cR81Qkq:1882355750) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/testdata/aggregate#L32)):*
donno if it is worth noting that this `group by 1` isn't actually doing the right thing yet.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by dt** [comment]
Reviewed 1 of 2 files at r6.
Review status: 5 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by tamird** [comment]
Review status: 4 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/group.go, line 364 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6jinIEymva2Ku77dtT:-K6jp7_Hvbp1JVjaH-5R:-1975473902) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/group.go#L364)):*
I believe an early return here would never be reached.

---

*[sql/testdata/aggregate, line 32 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-K6joRTneYZH0cR81Qkp:-K6jpEaI23BGdAk2FiAm:1355136144) ([raw file](https://github.com/cockroachdb/cockroach/blob/b588c0f5420241b2db9463ad7d488288b7f9edc4/sql/testdata/aggregate#L32)):*
That's tracked in an issue, so I've changed this to group by "a"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by dt** [comment]
Reviewed 1 of 1 files at r9.
Review status: 5 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 5 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3551#-:-K6nDPSjW5EeE8P46dle:676834233)*

**Pull request merged**
