### PR TITLE
build: fix xgo builds on TeamCity

### PR DESCRIPTION
**Pull request by benesch**
xgo-build is a target that exists solely to pass LINKFLAGS to xgo.  It's
old implementation was hack to reuse the existing build recipe, but this
is actually far clearer as a separate recipe. This new recipe no longer
needs to depend on $(BOOTSTRAP_TARGET)--and it shouldn't, because xgo
will handle the entire compilation process--and so should fix the
TeamCity release build errors.

This additionally fixes a similar error with the install target, where a
`make install` in a fresh repository (as opposed to a `make
any-other-target`) would fail to bootstrap, because the install-specific
GOBIN propogated up to the .bootstrap target. The fix applied here is to
override GOBIN in the build/buildoss/install recipe itself, rather than
its target-specific variables.

### CODE REVIEW

**Comment by tamird** [comment]
>   It's
> old implementation was hack to reuse the existing build recipe, but this
> is actually far clearer as a separate recipe.

s/it's/its/
"was hack" <- missing article

> where a `make install`

superfluous article, or else it should be a "a `make install` invocation". same thing happens in the next sentence.


> rather than its target-specific variables.

s/its/in/?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhY14ppx1iIxN8YOwdz:b-lplybo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3729a238ec904c9a1137a914160e5d6c77425d/Makefile#L104)):*
> ```Makefile
> # rebuilt which is useful when switching between normal and race test builds.
> #
> # Also, note the restoration of GOBIN to its original value: we install the
> ```

why not override GOBIN more narrowly as we discussed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-:-KhY0dS7hDIC2gLZsBOP:b-fyvlcs)*

**Comment by benesch** [comment]
Done.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhY3h3ZOqA1Lyw7PmhX:bjqn5yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/92477a5390eeeb7d64a3e8cd05a3be84bf9d06d0/Makefile#L104)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not override GOBIN more narrowly as we discussed?
</blockquote></details>

I think this way is more future proof. (It's the reason I set the default this way to begin with.)  I can come up with a couple cases where we muck with rules to install dependencies—`go dep` is released, we have another `go generate` dependency like protoc that we don't want to install unless necessary—but I can't come up with another case where we'll want to install into `$ORIGINAL_GOBIN`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-:-KhY4bvRNVhpKkCk15c6:b-896fix)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhY4dpv-7rQNyiAMIoc:b18mqty) ([raw file](https://github.com/cockroachdb/cockroach/blob/92477a5390eeeb7d64a3e8cd05a3be84bf9d06d0/Makefile#L104)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think this way is more future proof. (It's the reason I set the default this way to begin with.)  I can come up with a couple cases where we muck with rules to install dependencies—`go dep` is released, we have another `go generate` dependency like protoc that we don't want to install unless necessary—but I can't come up with another case where we'll want to install into `$ORIGINAL_GOBIN`.
</blockquote></details>

Please excuse the random non-rendering Unicode characters that Reviewable has inexplicably inserted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhY5GOo_i0C6lw_3Cor:b6jl341) ([raw file](https://github.com/cockroachdb/cockroach/blob/810bee4da5bc48973a1c603bd20b8d84fb7af6b5/Makefile#L104)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Please excuse the random non-rendering Unicode characters that Reviewable has inexplicably inserted.
</blockquote></details>

I (think I) disagree - wouldn't it be more robust to factor out a `GOINSTALLDEP` that does the thing with the override?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhY6mMGPRIKUZzNVlfP:b-wked8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/810bee4da5bc48973a1c603bd20b8d84fb7af6b5/Makefile#L104)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I (think I) disagree - wouldn't it be more robust to factor out a `GOINSTALLDEP` that does the thing with the override?
</blockquote></details>

Target-specific variables propagate to prerequisites but not to dependencies, so no way that I know of to factor out that variable dep. We can't share targets a la build/buildoss because the targets that call `go install` are split between protobuf.mk and the root Makefile.

If you feel strongly, though, I'm happy to drop a `GOBIN := $(LOCAL_BIN)` in front of our existing `go install` commands. I don't feel strongly; that approach is actually pretty clean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhYAF2X1sSOa3pRljJf:b-317pwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/810bee4da5bc48973a1c603bd20b8d84fb7af6b5/Makefile#L104)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Target-specific variables propagate to prerequisites but not to dependencies, so no way that I know of to factor out that variable dep. We can't share targets a la build/buildoss because the targets that call `go install` are split between protobuf.mk and the root Makefile.

If you feel strongly, though, I'm happy to drop a `GOBIN := $(LOCAL_BIN)` in front of our existing `go install` commands. I don't feel strongly; that approach is actually pretty clean.
</blockquote></details>

As discussed in person, `GOINSTALLDEP` is just a variable - that seems to have won your approval :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Comment by benesch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhY14ppx1iIxN8YOwdy:-KhYCtazHOjI8-tJ8PiY:bls5rjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/810bee4da5bc48973a1c603bd20b8d84fb7af6b5/Makefile#L104)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

As discussed in person, `GOINSTALLDEP` is just a variable - that seems to have won your approval :)
</blockquote></details>

Yessir! RFAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[Makefile, line 105 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhYDBVvHsk1JpKiSU95:-KhYDBVvHsk1JpKiSU96:bemr8y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/979ee3e9b0e9a33c855d96a69823bab38a5897b0/Makefile#L105)):*
> ```Makefile
> #
> # Also, note the restoration of GOBIN to its original value: we install the
> # cockroach binary to the user-specified GOBIN (usually GOPATH/bin) rather than
> ```

no more restoration here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-:-KhYDPl85Egosi_EkzMC:bnfp4nl)*

**Comment by tamird** [comment]
> The fix applied here is to
> override GOBIN in the build/buildoss/install recipe itself, rather than
> in target-specific variables.

This bit of the commit message has rotted.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-:-KhYDTJn7mWwYrjI9XJD:bfqngi7)*

**Comment by benesch** [comment]
Thanks, done.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 105 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-KhYDBVvHsk1JpKiSU95:-KhYEurvWX53lX55_m8B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/979ee3e9b0e9a33c855d96a69823bab38a5897b0/Makefile#L105)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

no more restoration here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851#-:-KhYExzhPK3l1RoSS4Pw:bo3vl6y)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14851)*

**Pull request merged**
