### PR TITLE
sql: do trace recording in explain analyze (distsql) like nature intended

### PR DESCRIPTION
**Pull request by andreimatei**
`explain analyze (distsql) ... ` needs to record the execution of a
DistSQL plan.  Before this patch, it was doing it clumsily, using heavy
session tracing machinery. Now, it uses a simple recording span.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Alfonso, something is wrong, unfortunately.
As is, `make testshort PKG='./pkg/sql/logictest' TESTS=TestPlannerLogic` fails like I showed you - the stats don't show up for the procs on the gateway node. I can "fix it" by putting in the line with the `!!!`, but I don't know why that makes a difference given that I'm trying to not use the original `evalCtx`...
If you happen to know, tell me. Otherwise I'll track it down.

**Comment by andreimatei** [comment]
Ignore my comment above, but please check out #30806

**Review by andreimatei — COMMENTED** [review]
First 2 commits are #30806

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-:-LNmOm1eEX5J0uzvmUMb:b24hlxt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-LNpKf_1ETmQ-TQh4uPj:-LNpKf_1ETmQ-TQh4uPk:b98wadx) ([raw file](https://github.com/cockroachdb/cockroach/blob/614a8a1bcd3dab61b7269d55af710365b1a6561f/pkg/sql/explain_distsql.go#L140)):*
> ```Go
> 
> 		sp.Finish()
> 		spans = tracing.GetRecording(sp)
> ```

`GetRecording` returns the recording of all child spans, right? Is this an issue if you have multiple EXPLAIN ANALYZE statements?

**Review by andreimatei — COMMENTED** [review]
yeah, this is about `explain analyze (distsql)`. I've updated the commit msg.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-:-LNpfj93CXHy8cS6tyN3:b-i57qse)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-LNpKf_1ETmQ-TQh4uPj:-LNpnSP23c6CJLyTEh7p:b-mpvu27) ([raw file](https://github.com/cockroachdb/cockroach/blob/614a8a1bcd3dab61b7269d55af710365b1a6561f/pkg/sql/explain_distsql.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`GetRecording` returns the recording of all child spans, right? Is this an issue if you have multiple EXPLAIN ANALYZE statements?
</blockquote></details>

yes, it returns the recording of all child spans.
What issues do you have in mind / what do you mean by multiple `explain analyze` stmts? You're thinking of nested `explain analyze`?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-LNpKf_1ETmQ-TQh4uPj:-LNppkV9AXKurceclVIJ:b23qv30) ([raw file](https://github.com/cockroachdb/cockroach/blob/614a8a1bcd3dab61b7269d55af710365b1a6561f/pkg/sql/explain_distsql.go#L140)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yes, it returns the recording of all child spans.
What issues do you have in mind / what do you mean by multiple `explain analyze` stmts? You're thinking of nested `explain analyze`?
</blockquote></details>

Yes, I'm thinking of nested explain analyze statements. What I'm thinking about is that spans are annotated with processor IDs, that's how we link them back to the flow diagram. If you have nested explain analyze statements, you would have multiple spans with the same processor ID. You would get back the top level explain diagram with possible processors maybe reading from a wrapped explain analyze node but the processors might be annotated with the stats of the bottom level one.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-LNpKf_1ETmQ-TQh4uPj:-LNprlB76fXigLrRlO-O:b-8n532h) ([raw file](https://github.com/cockroachdb/cockroach/blob/614a8a1bcd3dab61b7269d55af710365b1a6561f/pkg/sql/explain_distsql.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yes, I'm thinking of nested explain analyze statements. What I'm thinking about is that spans are annotated with processor IDs, that's how we link them back to the flow diagram. If you have nested explain analyze statements, you would have multiple spans with the same processor ID. You would get back the top level explain diagram with possible processors maybe reading from a wrapped explain analyze node but the processors might be annotated with the stats of the bottom level one.
</blockquote></details>

If the parent span is recording, this patch creates a root span (so, a separate recording).
So the bottom `explain analyze` should work, and what it does is going to be invisible to the upper ones. What the diagram produced by those upper ones would look like exactly I don't know. But do we really care?

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/explain_distsql.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-LNpKf_1ETmQ-TQh4uPj:-LNpuEwmBwmhieIbWmW2:b-9cxu84) ([raw file](https://github.com/cockroachdb/cockroach/blob/614a8a1bcd3dab61b7269d55af710365b1a6561f/pkg/sql/explain_distsql.go#L140)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If the parent span is recording, this patch creates a root span (so, a separate recording).
So the bottom `explain analyze` should work, and what it does is going to be invisible to the upper ones. What the diagram produced by those upper ones would look like exactly I don't know. But do we really care?
</blockquote></details>

Great, thanks for clarifying.

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30781#-:-LNpy5Yy4IuIg7feqMbD:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
please consider this for a backport

**Comment by andreimatei** [comment]
You've said this on other PRs too and I didn't know what to say on it. The default is to *not* backport... Is there a specific reason you think it should?

**Comment by knz** [comment]
because it simplifies, enhance the troubleshooting experience for users, and will use less memory?

**Comment by bdarnell** [comment]
Every PR is beneficial in some way, but not all should be backported. At this point, only the most important changes (i.e. those that fix potential production outages or other serious bugs) should be considered for backporting.  We got into the bad habit of backport-by-default because we cut the release branch too early in this cycle, but in general only a small minority of PRs on master should ever be backported.

**Comment by andreimatei** [comment]
I don't think this is user visible (other than the fact that I think you couldn't do `explain analyze` inside a recording session before).
I don't know about less memory... Does this patch do anything? Even if it does, it's for `explain analyze`... who cares?

But anyway, there's a higher principle at play. Even if everything you say would hold water, I think it still would not be enough for a backport. It wouldn't have been enough a month ago after we branched, and it's definitely not enough today.
I've encouraged @bdarnell in the past to write down thought out and comprehensive guidelines for guiding this decision, so that all of us can avoid most of these conversations.

**Pull request merged**
