### PR TITLE
sql: improve the table name prefix resolution error message

### LINKED ISSUE #29594: sql: dubious error for missing database
```
./cockroach demo
root@127.0.0.1:56141/defaultdb> create table test.t(a int);
pq: no schema has been selected to create "test.t" in
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #29594.

Before:

```
root@127.0.0.1:44824/defaultdb> create table t.t(x int);
pq: no schema has been selected to create "t.t" in
HINT: verify that the current database and search_path are valid
```

After:

```
root@127.0.0.1:36392/defaultdb> create table t.t(x int);
pq: cannot create "t.t" because the target database or schema does not exist
HINT: verify that the current database and search_path are valid and/or the target database exists
```

Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm:

With some minor wording changes.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29623#-:-LLp9eY752QxE3D_lk-9:b-f5y44f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/resolver.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29623#-LLp8nYOBISu5bwRX0QG:-LLp8nYOBISu5bwRX0QH:b-hhcp5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4eb9eaf6027cdf87bc1fa9e5522356225a0a411/pkg/sql/resolver.go#L434)):*
> ```Go
> 			if requireTable {
> 				return nil, nil, pgerror.NewErrorf(pgerror.CodeUndefinedObjectError,
> 					"schema or database was not found while searching index: %q",
> ```

Should this be ordered like the other one, `database or schema`?

And are you missing a `for`?


database or schema was not found while searching for index: %q
___
*[pkg/sql/resolver.go, line 436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29623#-LLp9I167zsDYm8KsKJZ:-LLp9I167zsDYm8KsKJ_:beyqbqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4eb9eaf6027cdf87bc1fa9e5522356225a0a411/pkg/sql/resolver.go#L436)):*
> ```Go
> 					"schema or database was not found while searching index: %q",
> 					tree.ErrString(&index.Index)).SetHintf(
> 					"check the current database and search_path are valid")
> ```

Might as well word this one the same as above as well.

`verify that the current database and search_path are valid`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29623)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/resolver.go, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29623#-LLp8nYOBISu5bwRX0QG:-LMJmAAnEoYGLMTyxWZa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4eb9eaf6027cdf87bc1fa9e5522356225a0a411/pkg/sql/resolver.go#L434)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Should this be ordered like the other one, `database or schema`?

And are you missing a `for`?


database or schema was not found while searching for index: %q
</blockquote></details>

Done.
___
*[pkg/sql/resolver.go, line 436 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29623#-LLp9I167zsDYm8KsKJZ:-LMJmAkp8niQxYs5Fw_n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4eb9eaf6027cdf87bc1fa9e5522356225a0a411/pkg/sql/resolver.go#L436)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Might as well word this one the same as above as well.

`verify that the current database and search_path are valid`
</blockquote></details>

Done.

**Comment by knz** [comment]
build failed due to borked agent. Retrying

bors r+

**Comment by knz** [comment]
TC not happy today....

bors r+

**Comment by knz** [comment]
welp, I don't know what to do.

**Pull request merged**
