### PR TITLE
pgwire: gracefully error when pgwire messages are too big

### LINKED ISSUE #50330: pgwire: improve error messaging for large requests in prepared statements
A customer recently tried to complete a large transaction and ran into the hard limit of 16MB with this error message:
```SQL
Error message:
invalid syntax: statement ignored: unexpected error: write tcp 127.0.0.1:47362->127.0.0.1:26257: write: connection reset by peer
warning: error retrieving the transaction status: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
```
This error message is fairly opaque and hard to understand. We should try to improve this error message so that customers can understand that this is our limit. 

We could also add hints that encourage the customer to break this into smaller transactions.

### PR DESCRIPTION
**Pull request by otan**
May be deemed high-ish risk, if so we can move to after the stability period.

----

Release justification: low risk, high benefit changes to
existing functionality

Release note (sql change): When a message that is too big is sent to a
CRDB instance, we will now error with a graceful message. This
previously terminated the connection opaquely with little explanation.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I think this change is too disruptive for the stability period

- I don't think this is exercising enough the recovery after an error
- the logic is only in `ReadUntypedMsg` but we have other read functions, and all of them should be able to recover equally gracefully

**Comment by knz** [comment]
is there a way to push the error to the client, and then immediately close the connection, in the read function? that may be slightly better

**Comment by otan** [comment]
> is there a way to push the error to the client, and then immediately close the connection, in the read function? that may be slightly better

i tried this on pgx as an example, it will error trying to send additional messages and error out ungracefully if we close immediately.

**Comment by otan** [comment]
Tests failing on CI but not on master. This is indeed a scary change (probably worth refactoring that conn executor loop entirely) -- I'm going to suggest tabling this for 21.1

**Comment by otan** [comment]
> do you have other examples?

Apparently quit hits this path too. I've localised the slurping to only the pgwire read loop for now...

**Comment by otan** [comment]
Split out a safer version: #53790

**Pull request closed without merging**
