### PR TITLE
opt: consolidate index formatting in expression trees

### PR DESCRIPTION
**Pull request by mgartner**
A number of test outputs changed because all indexes are now formatted
with a table's name, not its alias. Previously, table aliases were
printed for Scans. This change made it easier to consolidate the index
formatting into a single function.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first two commits are from #55339 

> As a bonus, the output of a query with two joins on the same table is now more coherent.

This _may_ not be true. For something like an index join, is it more accurate to say that the lookup is happening on the generic table name, not the specific alias in the query?

**Review by RaduBerinde — COMMENTED** [review]
Having just the alias is a little annoying, sometimes you have to refer back to the SQL to know what table it's talking about. A bunch of tests switched from something useful to something very generic like "l1" or "d". Maybe we should just use the real table name everywhere.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-:-MJnJQ1RBnY083PeXHba:b-rls01l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MJnKCqxBK9_worQEBGu:-MJnKCqxBK9_worQEBGv:b9iiyll) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e9b336c3ea1fb5f35815a741c929803bfb2332/pkg/sql/opt/memo/testdata/stats/join#L1347)):*
> ```
> )
> ----
> inner-join (lookup t.public.def)
> ```

This is strange.. We changed to using the alias but we are now fully qualifying it?

**Review by mgartner — COMMENTED** [review]
SGTM. Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-:-MJnjzxD-wqVDRGmp-oJ:bdt2liv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MJnKCqxBK9_worQEBGu:-MJnhqvZBUAIczlGRltp:b-yfn7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e9b336c3ea1fb5f35815a741c929803bfb2332/pkg/sql/opt/memo/testdata/stats/join#L1347)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is strange.. We changed to using the alias but we are now fully qualifying it?
</blockquote></details>

Ya. `ExprFmtCtx.tableAlias` fully qualifies the alias unless `ExprFmtHideQualifications` is set via `format=hide-qual`.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-:-MJnsulm6sm2Ivb61PUl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MJnKCqxBK9_worQEBGu:-MJnsRYZ6cDJG30vdIVA:benvzco) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e9b336c3ea1fb5f35815a741c929803bfb2332/pkg/sql/opt/memo/testdata/stats/join#L1347)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ya. `ExprFmtCtx.tableAlias` fully qualifies the alias unless `ExprFmtHideQualifications` is set via `format=hide-qual`.
</blockquote></details>

Pretty strange, qualifying an alias with a database doesn't make sense (it's not a valid name).

**Review by rytaft — COMMENTED** [review]
> Reviewed 67 of 67 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/memo/expr_format.go, line 1049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-ug5I0Jttb9oZIjGF:-MK-ug5I0Jttb9oZIjGG:byiek92) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d9f0b3f256b77836cc513f574301c42f0d92e3/pkg/sql/opt/memo/expr_format.go#L1049)):*
> ```Go
> //   table_alias@index_name
> //
> // If the reverse is true, ",rev" is appended. If the index is a partial index,
> ```

[nit] the reverse -> reverse
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 866 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-xRX847t-6kABB6UE:-MK-xRX847t-6kABB6UF:b-1ifo33) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d9f0b3f256b77836cc513f574301c42f0d92e3/pkg/sql/opt/optbuilder/testdata/aggregate#L866)):*
> ```
>  │    └── inner-join (cross)
>  │         ├── columns: a.k:1!null a.v:2 a.w:3 a.s:4 a.crdb_internal_mvcc_timestamp:5 b.k:6!null b.v:7 b.w:8 b.s:9 b.crdb_internal_mvcc_timestamp:10
>  │         ├── scan kv
> ```

I really like that we're now printing the original table name, but it's a bit weird that the column names seem disconnected from the table (and sometimes it's also nice to know what the alias was). Would it be too much of a pain to print `scan kv AS a` (or `scan kv [as=a]` to match the formatting used below for aggregations)?
___
*[pkg/sql/opt/optbuilder/testdata/subquery, line 1337 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-yOUD1mmCuExZpybx:-MK-yOUD1mmCuExZpyby:bdefm37) ([raw file](https://github.com/cockroachdb/cockroach/blob/0973751e31c18eaa69c417d9f4b1ee6d39f51f28/pkg/sql/opt/optbuilder/testdata/subquery#L1337)):*
> ```
>  ├── inner-join (cross)
>  │    ├── columns: db1.public.kv.k:1!null db1.public.kv.v:2 db1.public.kv.crdb_internal_mvcc_timestamp:3 t.public.kv.k:4!null t.public.kv.v:5 t.public.kv.crdb_internal_mvcc_timestamp:6
>  │    ├── scan db1.public.kv
> ```

Shouldn't we respect the `fully-qualify-names` directive?

**Review by mgartner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 11 of 67 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MKLzfA33dcDyfp7HU6n:-MKLzfA33dcDyfp7HU6o:b-90wxpp) (no related file):*
I've reworked this a bit so PTAL!

---
___
*[pkg/sql/opt/memo/expr_format.go, line 1049 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-ug5I0Jttb9oZIjGF:-MKI09ek7XOCHxiwoU92:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d9f0b3f256b77836cc513f574301c42f0d92e3/pkg/sql/opt/memo/expr_format.go#L1049)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] the reverse -> reverse
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/join, line 1347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MJnKCqxBK9_worQEBGu:-MKLzRbOEgOft6j6u80S:b-a3u4d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9e9b336c3ea1fb5f35815a741c929803bfb2332/pkg/sql/opt/memo/testdata/stats/join#L1347)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Pretty strange, qualifying an alias with a database doesn't make sense (it's not a valid name).
</blockquote></details>

I've removed this function to avoid the confusing. There's now a `tableName` function which can fully qualify or not, but aliases are never fully qualified now.
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 866 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-xRX847t-6kABB6UE:-MKI3LfF23XwMBDAXvrT:b-zb0byq) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d9f0b3f256b77836cc513f574301c42f0d92e3/pkg/sql/opt/optbuilder/testdata/aggregate#L866)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I really like that we're now printing the original table name, but it's a bit weird that the column names seem disconnected from the table (and sometimes it's also nice to know what the alias was). Would it be too much of a pain to print `scan kv AS a` (or `scan kv [as=a]` to match the formatting used below for aggregations)?
</blockquote></details>

I love it. Do you think it looks okay in joins: e.g. `inner-join (lookup nyc_neighborhoods [as=n])`?
___
*[pkg/sql/opt/optbuilder/testdata/subquery, line 1337 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-yOUD1mmCuExZpybx:-MKLzLGHA1IBBjOVgTfR:b-pkzycw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0973751e31c18eaa69c417d9f4b1ee6d39f51f28/pkg/sql/opt/optbuilder/testdata/subquery#L1337)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Shouldn't we respect the `fully-qualify-names` directive?
</blockquote></details>

Yes, fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 56 of 65 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-:-MKMwi5iAotroDYCV73Y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 866 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55641#-MK-xRX847t-6kABB6UE:-MKMvq9H9muax0TQvTO3:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/50d9f0b3f256b77836cc513f574301c42f0d92e3/pkg/sql/opt/optbuilder/testdata/aggregate#L866)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I love it. Do you think it looks okay in joins: e.g. `inner-join (lookup nyc_neighborhoods [as=n])`?
</blockquote></details>

Looks great!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
