### PR TITLE
changefeedccl: support confluent-cloud sink scheme

### LINKED ISSUE #105226: changefeedccl: add confluent cloud integration
We should support the 'confluent-cloud://' syntax for creating changefeeds for confluent cloud 

Still support the following parameters:
- instead of sasl_user, api_key
- instead of sasl_password, api_secret
- topic_name
- topic_prefix
- kafka_sink_config (except for version?) and confluent_schema_registry can still be used
- other sasl_ options not mentioned here

Open question: 
- Does confluent cloud support certs? (I don't think so but need to double check)
- What about tls_enabled and insecure_tls_skip_verified? (I think we have to do tls_enabled and should just do away with both options but need to verify)
- What about sasl_enabled? (I think you have to use sasl_enabled=true so we would want to get rid of this?)

the end url should look something like this: 'confluent-cloud://pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092?api_key=[]&api_secret=[]&sasl_mechanism=PLAIN&topic_name=[]'

We should also add metadata to the client.id field.

Jira issue: CRDB-28928

Epic CRDB-28929

### PR DESCRIPTION
**Pull request by jayshrivastava**
### changefeedccl: support confluent-cloud sink scheme

This change lets users create kafka changefeeds with the `confluent-cloud://`
sink scheme. This scheme can be used to connect to kafka hosted on confluent cloud.
The required parameters are `api_key` and `api_secret` which are passed in as the
`sasl_user` and `sasl_password` of the kafka connection.

The options `tls_enabled=true`, `sasl_enabled=true`, `sasl_handshake=true`, and
`sasl_mechanism=PLAIN` are also needed, so they are set by default.

Release note (enterprise change): Changefeeds now support the `confluent-cloud://`
sink scheme. This scheme can be used to connect to kafka hosted on confluent cloud.
The scheme functions identically to kafka, but it has it's own authentication
parameters. Namely, it requires `api_key` and `api_secret` to be passed as
parameters in the sink URI. They must be URL encoded. An example URI is:
```
'confluent-cloud://pkc-lzvrd.us-west4.gcp.confluent.cloud:9092?api_key=<KEY>&api_secret=<SECRET>'
```
By default the options `tls_enabled=true`, `sasl_handshake=true`, `sasl_enabled=true`,
and `sasl_mechanism=PLAIN`, are applied. There is more information about authenticating
with confluent cloud, see https://docs.confluent.io/platform/current/security/security_tutorial.html#overview.

The sink scheme still supports non-authentication parameters such as `topic_name` and `topic_prefix`.
It also supports the standard kafka changefeed options (ex. `kafka_sink_config`).

Closes: https://github.com/cockroachdb/cockroach/issues/105226
Epic: [CRDB-28929](https://cockroachlabs.atlassian.net/browse/CRDB-28929)

---

### roachtest/cdc: test confluent-cloud scheme in cdc/kafka-auth roachtest
This change updates the `cdc/kafka-auth` roachtest to create a changefeed
with the `confluent-cloud` scheme.

Epic: None
Release note: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
There's an unrelated data race in the extended CI https://github.com/cockroachdb/cockroach/issues/111381

**Review by miretskiy — CHANGES_REQUESTED** [review]
I realize that we cannot (yet) have confluent-cloud roachtest, but before approving, we need to figure out a way to manually test this feature.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-:-NfVr1aV3h23MlujkMA0:b7iiegj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, and @renatolabs)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVpcwv6YqRFQxqo_aI:-NfVpcwv6YqRFQxqo_aJ:brs6wk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L881)):*
> ```Go
> 
> func buildDialConfig(u sinkURL) (kafkaDialConfig, error) {
> 	if u.Scheme == changefeedbase.SinkSchemeConfluentKafka {
> ```

perhaps this check should happen at the call site?
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVq2P_DKRgxcLnz5YN:-NfVq2P_DKRgxcLnz5YO:b-pavphi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L1018)):*
> ```Go
> 		return kafkaDialConfig{}, newRequiredValueError(changefeedbase.SinkParamSASLEnabled, "true")
> 	}
> 	// If sasl_mechanism is specified, it must be set to PLAIN.
> ```

That's not my read of the doc you link above:

```
For production deployments of Confluent Platform, [SASL/GSSAPI (Kerberos)](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_gssapi.html#kafka-sasl-auth-gssapi) or [SASL/SCRAM](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_scram.html#kafka-sasl-auth-scram) is recommended
```
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVqj276R92lNoZV-ZH:-NfVqj276R92lNoZV-ZI:b-t7bgxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L1051)):*
> ```Go
> 
> 	// Ignore all other configurations.
> 	return dialConfig, nil
> ```

it's a bit surprising to see so much code where in reality we are only changing 2 options. Isn't there a way to re-use existing build config code? Perhaps support "aliases" for those options?  Maybe add additional checks if needed after building default config?
___
*[`pkg/ccl/changefeedccl/sink_kafka_connection_test.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVowXm9e63pFmOubhT:-NfVowXm9e63pFmOubhU:b66mwtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L235)):*
> ```Go
> 			name:          "requires parameter sasl_mechanism=PLAIN",
> 			uri:           "confluent-cloud://nope?api_key=fee&api_secret=bar&sasl_mechanism=OAUTHBEARER",
> 			expectedError: "requires parameter sasl_mechanism=PLAIN",
> ```

should the error  be only PLAIN supported? or perhaps "unsupported feature .. OATH, only PLAIN supported"?

**Review by jayshrivastava — COMMENTED** [review]
I manually tested it by setting up confluent cloud. Showed the team during demos :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-:-NfWXpE23IgpXS4aXSCU:b-gsm3ik)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @miretskiy, and @renatolabs)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVpcwv6YqRFQxqo_aI:-NfWW1mn7t6zQNXqepsb:b-wshxug) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L881)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps this check should happen at the call site?
</blockquote></details>

I kind of like it here. The call site does not have to worry about if it's confluent or not. The kafka sink can decide which dial config it needs to make.
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1018 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVq2P_DKRgxcLnz5YN:-NfWWCYF93Vt5nxT-_Vk:b-3dfu91) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L1018)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

That's not my read of the doc you link above:

```
For production deployments of Confluent Platform, [SASL/GSSAPI (Kerberos)](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_gssapi.html#kafka-sasl-auth-gssapi) or [SASL/SCRAM](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_scram.html#kafka-sasl-auth-scram) is recommended
```
</blockquote></details>

`Confluent Platform` is something else. It doesn't refer to kafka in confluent cloud. I dislike how they have their docs laid out. There's no exclusive docs for confluent cloud. The page I linked is for security related to all of their products. The part relevant to confluent cloud is:

```
Confluent Cloud uses [SASL/PLAIN (or PLAIN)](https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html#kafka-sasl-auth-plain) over TLS v1.2 encryption for authentication because it offers broad client support while providing a good level of security. The usernames and passwords used in the SASL exchange are API keys and secrets that should be securely managed using a secrets store and rotated periodically.
``` 

Inside confluent cloud console, there are instructions for connecting

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVqj276R92lNoZV-ZH:-NfWWa9fDwhXcGjaw_X_:b-65a3cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka.go#L1051)):*
I know it's a lot of code, but I just feel better about having all of these checks that assert exactly what params can be present and which params cannot be. I feel like with the existing code, we have a very large number of security-related params and it's hard to tell what combinations work, which combinations work but should not work, which combinations should not be passed together but still work etc. I think in an ideal world, we split up `buildDialConfig` as much as possible for each way to authenticate. 

> Maybe add additional checks if needed after building default config?
I think it still ends up being a lot of code. We would have to iterate through all the fields of the dial config and assert that they are unset (ex. dialConfig.cacert, dialConfig.saslClientID, dialConfig.tokenUrl). Please correct me if I'm misunderstanding the suggestion. In my code, we can simply check that there are no query parameters left after the relevant ones are consumed.

> Perhaps support "aliases" for those options?
I think this works, but it might be unnecessary. api_key makes sense confluent cloud, so there's no need to have the alias code when not using the confluent cloud scheme. 
___
*[`pkg/ccl/changefeedccl/sink_kafka_connection_test.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-NfVowXm9e63pFmOubhT:-NfWXmPbD4Cd1ROkJq2T:b8kb9d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bf9026f760951f262e69cdb73daba9239e01f29/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L235)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should the error  be only PLAIN supported? or perhaps "unsupported feature .. OATH, only PLAIN supported"?
</blockquote></details>

Done. Updated the error message.

**Review by miretskiy — APPROVED** [review]
Ack. Appreciate it.  Let's add a todo/issue somewhere.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111368#-:-NfWddLFCstlVj8ZNMJl:b-ubsx0d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Pull request merged**
