### PR TITLE
release-23.2: go.mod: bump Pebble to 52e1a820246d

### PR DESCRIPTION
**Pull request by jbowens**
```
52e1a820 sstable: fix two-level iterator NextPrefix error propagation
7f4b9637 crl-release-23.2: minor fix to README.md
6f3a6cd3 crl-release-23.2: README: expand on format major versions and version compatibility
```

Epic: none
Release note: none
Release justification: non-production code changes, and a bug fix for an incorrect results / corruption issue where by an IO error could result in an iterator skipping keys.

### CODE REVIEW

**Comment by nicktrav** [comment]
EM LGTM ✅

**Review by RaduBerinde — APPROVED** [review]

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115644#-:-NkwMqK9EFru6E-8ZZ4O:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by jbowens** [comment]
TFTRs!

**Pull request merged**
