### PR TITLE
catalog: relax descriptor ID assumptions for system database

### PR DESCRIPTION
**Pull request by postamar**
Previously, all system tables had to have an ID < 50. We are now close
to exhausting that ID space and this commit relaxes the requirement for
system tables to have hard-coded IDs in this range.

Now, only the following descriptors now have hard-coded IDs:
- the system database (1),
- the descriptor table (3),
- the lease table (11),
- the rangelog table (13),
- the namespace table (30).
These descriptors are special in that they are never leased. This
effectively makes them immutable and so they are read from storage at
most once by each node, which caches the result.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I think there's more that need to have hard-coded IDs. In particular `settings`, `sqlliveness`, and  `sqlinstances`. All of these get used with raw kvs and so we'd need to plumb in their IDs at a low level. 

I haven't made it all the way through this, but it seems good. My main question is, do we need to get this in for this release?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68898#-:-MhE7ijb68uArespPZ-R:b-h8ao0u)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by postamar** [comment]
Agreed with the need for a fair amount of hard-coded IDs. As to your second question I'm wondering too. I'm still looking at the failing tests to get a sense of just how many assumptions we're making about descriptor IDs throughout the codebase.

**Comment by postamar** [comment]
I don't think this will make it in this release, there are too many changes to be done.

That being said, it's quite tractable, caching the namespace table contents for the system database makes sense and works well. Here's are some subtasks I've identified:
1. Stop inferring properties about a table based on its ID, unless it's one of those hard-coded IDs which we need. Use table descriptors instead when feasible. For instance in `pkg/sql/stats` we classify a table as a system table based on its ID alone, when in reality we'd much rather have the descriptor so as to exclude views from stats collection etc.
2. In the same vein we infer privileges on a system table based on its ID and this needs to change. Instead it'd be better hard-code them in a map keyed by name instead of by ID. As I looked further into this it became quite apparent there was a lot of privilege logic in descpb that simply didn't belong there. Instead all of this stuff should be moved into `defaultprivilegedesc` and we should rename that package to `catprivilege` or something like that. 
3. The bootstrapped system schema creates table descriptors for non-hardcoded tables in the user ID range. Instead of starting that at a hard-coded value of 50 this could be a metamorphic constant. For this to work we need to to remove the following constants in `keys`:  `MaxReservedDescID`, `MinUserDescID`, `MinNonPredefinedUserDescID`. This is a lot of work but these mostly show up in tests.
4. Speaking of tests, many of the test failures I've looked at in this PR are straightforward but a good many aren't. In particular those in `config` or `server` which make certain assumptions about ranges on a bootstrapped cluster.
5. This change properly speaking should be followed by a migration which relocates some small system tables outside of the reserved range, to free up more IDs on clusters which came into existence prior to this change. I'm not sure how practical this is. The problem remains that the reserved ID range lives on and the few IDs in it which are still available in there should not be used for anything other than new system tables for which we'll want to hard-code the ID thereof.

**Comment by postamar** [comment]
Closed in favour of https://github.com/cockroachdb/cockroach/pull/68915 https://github.com/cockroachdb/cockroach/pull/68997 and https://github.com/cockroachdb/cockroach/pull/69008 . I'll reinvestigate this again in a few weeks.

**Pull request closed without merging**
