### PR TITLE
schemachanger: add & adopt data elements

### LINKED ISSUE #89181: schemachanger: consolidate SCHEMA CHANGE GC jobs
Rather than a plethora of GC jobs we'd instead prefer to have one per schema change, or at least one per descriptor.

Jira issue: CRDB-20164

### PR DESCRIPTION
**Pull request by postamar**
This commit attaches db/table/index GC jobs to elements representing their data. This allows leveraging the rules system to create a minimum of necessary GC jobs in the same non-revertible mutation stage.

Fixes #89181.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
Could someone please take a look? I'm tired of rebasing.

**Review by fqazi — APPROVED** [review]
:lgtm: just a couple of minor nit comments

> Reviewed 392 of 392 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-:-NFJYaeY7DNzLzFPPvw0:bh06fzn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_database.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-NFJW1f30bYQYagCsD28:-NFJW1f30bYQYagCsD29:b-iq3zwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14a7b86b9d53d4bd05627057ca98b3afb53532e8/pkg/sql/schemachanger/scplan/internal/opgen/opgen_database.go#L57)):*
> ```Go
> 					return newLogEventOp(this, md)
> 				}),
> 				emit(func(this *scpb.Database, md *targetsWithElementMap) *scop.CreateGCJobForDatabase {
> ```

In terms of version compatibility, how is the mixed version state going to handle this? I know long term we were gonna bundle the previous version of the schema changer, but just want to confirm that.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-NFJWiLr8WupQZFeNwCg:-NFJWiLr8WupQZFeNwCh:b8z0syz) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4a883019bdf92a8bd4ea78ec2c2bf0e4ec44f/pkg/sql/schemachanger/scplan/internal/rules/dep_drop_object.go#L148)):*
> ```Go
> 
> // Rules affecting data.
> func init() {
> ```

This is empty?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_garbage_collection.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-NFJX2xbCVkmN9tLrGJX:-NFJX2xbCVkmN9tLrGJY:b-89cwbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4a883019bdf92a8bd4ea78ec2c2bf0e4ec44f/pkg/sql/schemachanger/scplan/internal/rules/dep_garbage_collection.go#L82)):*
> ```Go
> 
> 	// GC jobs should all be scheduled in the same transaction.
> 	registerDepRuleForDrop(
> ```

Nice use of rel
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-NFJYDQOAGCgN5EhsSCF:-NFJYDQOAGCgN5EhsSCG:b-t78zp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4a883019bdf92a8bd4ea78ec2c2bf0e4ec44f/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid#L2)):*
> ```
> setup
> CREATE TABLE t (a INT NOT NULL)
> ```

Why was this change made?

**Comment by postamar** [comment]
Thanks for the review!

> In terms of version compatibility, how is the mixed version state going to handle this? I know long term we were gonna bundle the previous version of the schema changer, but just want to confirm that.

I'm glad you noticed this because it appears that I have completely forgotten to do this when I last rebased. Ah, the dangers of stale PRs...

I'll take this back to draft mode.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89182)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89182#-NFJYDQOAGCgN5EhsSCF:-NFOarRq6158uPFQXqtT:b-6ykr1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b4a883019bdf92a8bd4ea78ec2c2bf0e4ec44f/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_drop_rowid#L2)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Why was this change made?
</blockquote></details>

IIRC I felt that it made the output more complicated in a way that was out of proportion with the value it provided. I don't feel strongly about this so I'm happy to put it back if you want

**Comment by postamar** [comment]
I've added the old legacy operation generation back, behind version gates. Changes since the review are not particularly significant IMHO so I'm going to go ahead and bors this. Thanks again for noticing this lack of mixed-version compatibility.

bors r+

**Pull request merged**
