### PR TITLE
roachtest: always send SIGKILL after SIGUSR1

### LINKED ISSUE #114558: roachtest: decommissionBench/nodes=4/warehouses=1000/duration=1h0m0s failed
roachtest.decommissionBench/nodes=4/warehouses=1000/duration=1h0m0s [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Coverage_RoachtestNightlyGce/12702441?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Coverage_RoachtestNightlyGce/12702441?buildTab=artifacts#/decommissionBench/nodes=4/warehouses=1000/duration=1h0m0s) on master @ [e19c24fb62d24595e74c0bae0aaad0a736c2bdc7](https://github.com/cockroachdb/cockroach/commits/e19c24fb62d24595e74c0bae0aaad0a736c2bdc7):

```
(decommissionbench.go:842).runDecommissionBenchLong: monitor failure: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/decommissionBench/nodes=4/warehouses=1000/duration=1h0m0s/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=16</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12702441/decommissionbench-nodes-4-warehouses-1000-duration-1h0m0s/1700130221028/1700132605342)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*decommissionBench/nodes=4/warehouses=1000/duration=1h0m0s.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33561

### LINKED ISSUE #114562: roachtest: multitenant-upgrade failed
roachtest.multitenant-upgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Coverage_RoachtestNightlyGce/12702441?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Coverage_RoachtestNightlyGce/12702441?buildTab=artifacts#/multitenant-upgrade) on master @ [e19c24fb62d24595e74c0bae0aaad0a736c2bdc7](https://github.com/cockroachdb/cockroach/commits/e19c24fb62d24595e74c0bae0aaad0a736c2bdc7):

```
(cluster.go:2058).Start: COMMAND_PROBLEM: exit status 1
(cluster.go:2169).Run: context canceled
(cluster.go:2169).Run: context canceled
test artifacts and logs in: /artifacts/multitenant-upgrade/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_metamorphicBuild=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12702441/multitenant-upgrade/1700140305943/1700140501683)

</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*multitenant-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-33565

### PR DESCRIPTION
**Pull request by RaduBerinde**
In coverage mode we send SIGUSR1 instead of SIGKILL so that we can
obtain the coverage data. However, upgrade tests use older Cockroach
versions which ignore SIGUSR1.

With this change we now always send SIGKILL if SIGUSR1 did not end the
process.

Epic: none
Release note: None

Fixes #114558
Fixes #114562

### CODE REVIEW

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114594)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @RaduBerinde)

___
*[`pkg/cmd/roachtest/cluster.go` line 2093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114594#-NjOY-1r1vcOIqfh55AO:-NjOY-1r1vcOIqfh55AP:boh1stb) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e50606ceb735f9f1d6b04a19638af34edd0641/pkg/cmd/roachtest/cluster.go#L2093)):*
> ```Go
> 		stopOpts.RoachprodOpts.Wait = true
> 		stopOpts.RoachprodOpts.MaxWait = 10
> 		_ = roachprod.Stop(ctx, l, c.MakeNodes(nodes...), stopOpts.RoachprodOpts)
> ```

Wont' we be sending `SIGUSR1` twice in this case? Am I missing something?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114594)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)

___
*[`pkg/cmd/roachtest/cluster.go` line 2093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114594#-NjOY-1r1vcOIqfh55AO:-NjOYqv84EAguAL0epM1:b-krn67d) ([raw file](https://github.com/cockroachdb/cockroach/blob/80e50606ceb735f9f1d6b04a19638af34edd0641/pkg/cmd/roachtest/cluster.go#L2093)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Wont' we be sending `SIGUSR1` twice in this case? Am I missing something?
</blockquote></details>

You're not, sorry, fixed. Good thing I haven't started test runs though, I want to run the two failed tests.

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=12716410&

**Review by renatolabs — APPROVED** [review]

**Comment by renatolabs** [comment]
The roachtest code to send `SIGUSR1` on coverage builds doesn't exist on 23.2. Is it on the pipeline to be backported? I'm a little lost keeping track of backports.

**Comment by RaduBerinde** [comment]
I will make sure it's on my backport list.

TFTR!

bors r+

**Comment by RaduBerinde** [comment]
Opened a backport for both the original change and this fix: https://github.com/cockroachdb/cockroach/pull/114663

**Pull request merged**
