### PR TITLE
cli: Add some tests for the locality setting features of cockroach demo

### PR DESCRIPTION
**Pull request by rohany**
Added some tests for locality settings in cockroach demo.

Release justification: Low risk tests for an existing feature.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with minor nit.

(beware, you'll want to manage the unavailability of the license server here in the same way as the other test #40734)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40602#-:-LozNcwu6shUfAWuvbaW:b7dxf8q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/cli/cli_test.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40602#-LozNYwU8Ztqeyw-uTnW:-LozNYwU8Ztqeyw-uTnX:b20wmu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4287e6bf2290e08f4b672004ff1dad16cb70609/pkg/cli/cli_test.go#L481)):*
> ```Go
> 		{`demo`, `--nodes`, `9`, `-e`, `select node_id, locality from crdb_internal.gossip_nodes`},
> 		{`demo`, `--nodes`, `3`, `--demo-locality=region=us-east1:region=us-east2:region=us-east3`,
> 			`-e`, `select node_id, locality from crdb_internal.gossip_nodes`},
> ```

Make this test more future-proof by adding the appropriate ORDER BY clause.

**Comment by rohany** [comment]
failure to contact the licensing server doesn't affect these tests -- the example test does not use the ccl binary, and the tcl tests will error out before license acquisition is attempted.

**Comment by rohany** [comment]
@knz, this doesn't seem to pass CI... according to here (https://teamcity.cockroachdb.com/viewLog.html?buildId=1493642&problemId=2684), the test seems to timeout in 45 minutes. I can't reproduce this locally with testrace. Do you have an idea of whats could be going on (i know this is a very broad question, but I can't seem to make headway)?

**Comment by knz** [comment]
just for clarification how did you try reproducing it locally? which command was run?

**Comment by rohany** [comment]
‘make testrace PKG=./pkg/cli TESTS=Example_demo_locality’ — the test output shows that testrace fails

**Comment by rohany** [comment]
This is pretty strange -- I moved the test into the other Example_demo test, and it didn't hang. Is there some sort of race between the different invocations of demo in these tests?

**Comment by knz** [comment]
That is a symptom of not resetting all the relevant `ctx` structs in `cli/context.go`.

**Comment by rohany** [comment]
Ok, this worked when i called setCLIDefaultsForTests() at the beginning of the tests to clean up the context.

bors r=knz

**Comment by rohany** [comment]
it doesnt seem like this is working (bors is stuck). I'll probably come back to this later, i think the root of the problem is that the demo command modifies the demoCtx. 

bors r-

**Comment by knz** [comment]
retrying

bors r=knz

**Comment by knz** [comment]
oh I think I found something

bors r-

**Comment by knz** [comment]
nvm it should work

bors r+

**Pull request merged**
