### PR TITLE
sql: deal with column renames on existing mutations

### PR DESCRIPTION
**Pull request by ajwerner**
This fixes a rather egregious bug that prevented renaming of columns which
have been referenced in earlier mutations.

Release note (bug fix): Fixed a bug which prevented renaming a column that
was referenced earlier in a transaction as part of a computed expression,
index predicate, check expression, or not null constraint.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/rename_column.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59384#-MRvnSda8oBVt_O2-jmW:-MRvnSda8oBVt_O2-jmX:ba4qzgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/23609f43b907a5a5d1203ab5a1318a9632aaa122/pkg/sql/rename_column.go#L160)):*
> ```Go
> 
> 	// Rename the column in CHECK constraints.
> 	// Renaming columns that are being referenced by checks that are being added is not allowed.
> ```

While reviewing this PR this comment caught my eye -- can we remove it after this patch or was there something more to it?

**Review by thoszhang — COMMENTED** [review]
What happens (both before and after this PR) when the schema element being added was added in an earlier transaction and the column rename is concurrent with the schema change job? It looks like the bug and the fix should be the same, but I want to confirm.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59384#-:-MRzO5mB8sEwwPi2BfBE:b-yi1t7b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/rename_column.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59384#-MRvnSda8oBVt_O2-jmW:-MRzOgjr-bh0az0SbMgO:b-5orjgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/23609f43b907a5a5d1203ab5a1318a9632aaa122/pkg/sql/rename_column.go#L160)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

While reviewing this PR this comment caught my eye -- can we remove it after this patch or was there something more to it?
</blockquote></details>

Apparently I wrote this comment, but I don't remember what I meant. I'm going to assume that this is incorrect in that there's nothing actually preventing trying to rename columns being referenced by check constraints being added.

**Review by ajwerner — COMMENTED** [review]
> What happens (both before and after this PR) when the schema element being added was added in an earlier transaction and the column rename is concurrent with the schema change job? It looks like the bug and the fix should be the same, but I want to confirm.

It's the same. I wrote a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59384#-:-MS3T3v4Bi3nC6IAOjgJ:byhufvm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @lucy-zhang)

___
*[pkg/sql/rename_column.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59384#-MRvnSda8oBVt_O2-jmW:-MSBcK_A459bKCR78uoz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23609f43b907a5a5d1203ab5a1318a9632aaa122/pkg/sql/rename_column.go#L160)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Apparently I wrote this comment, but I don't remember what I meant. I'm going to assume that this is incorrect in that there's nothing actually preventing trying to rename columns being referenced by check constraints being added.
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59384)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
