### PR TITLE
tenantcostclient: speed up query RU estimate test

### LINKED ISSUE #106350: tenantcostclient: figure out how to "unskip" TestEstimateQueryRUConsumption
Currently, `TestEstimateQueryRUConsumption` is unconditionally skipped which is no longer allowed under "test vision zero". The test has been skipped since its introduction in #89256 with the following comment:
```
	// This test becomes flaky when the machine/cluster is under significant
	// background load, so it should only be run manually.
```
We should figure out how to enable this test at least in some cases or, perhaps, use another skip mechanism that would make this test no longer show up as "skipped" if we truly cannot enable it without it becoming flaky.

cc @DrewKimball in case you have some thoughts

Jira issue: CRDB-29525

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit speeds up the query RU estimate test in two ways:
- it forces the production values for some of the metamorphic constants (this brought down the runtime from 93s to 37s for a particular seed)
- it reduces the number of rows inserted from 50k to 20k which should be (further bringing down the runtime to 13s).

Fixes: #106350.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-:-N_D2MZ84TZPnrR6Ksql:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2ANi4dD5rF5pLOg2:-N_D2ANi4dD5rF5pLOg3:brf4ow9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L82)):*
> ```Go
> 				// We disable the randomization of some batch sizes because with
> 				// some low values the test takes much longer.
> 				ForceProductionValues: true,
> ```

Good catch. The workmem randomization is a test runtime killer.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106730)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2WKlBpm-GPjJBQGH):*
Did you end up removing this part?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106730)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2WKlBpm-GPjJBQGH):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Did you end up removing this part?
</blockquote></details>

No, it's included - I adjusted the INSERT test query. Should it be done in some other way?
___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2ANi4dD5rF5pLOg2:-N_EubUaAV1-hSzTE5rK:b-97410q) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L82)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good catch. The workmem randomization is a test runtime killer.
</blockquote></details>

It wasn't the workmem randomization (which is only enabled for logic tests) - it was `default-batch-bytes-limit` which controls how much data a single BatchResponse can return.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_EvXE_DB5d42pvZb0r:-N_EvXE_DB5d42pvZb0s:bwl8wv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L182)):*
> ```Go
> 		return tenantRUs
> 	}
> 	tenantStartRUs := getTenantRUs()
> ```

Drew, shouldn't we delete all data from `abcd` table here? The way test is written right now is that we first insert 20k rows and run a bunch of other SELECT queries via EXPLAIN ANALYZE, then we insert another 20k rows and run the SELECTs again. The second run will have 40k rows, so it's expected to consume more RUs. If we delete all the data in-between, then we should be able to reduce the allowed delta.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106730)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2WKlBpm-GPjJBQGH):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

No, it's included - I adjusted the INSERT test query. Should it be done in some other way?
</blockquote></details>

No, just missed the change. LGTM.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_D2ANi4dD5rF5pLOg2:-N_F1EvTAnmHw3DNPo5P:b4d33og) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L82)):*
>It wasn't the workmem randomization (which is only enabled for logic tests) - it was `default-batch-bytes-limit` which controls how much data a single BatchResponse can return.

Ah, makes sense.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_EvXE_DB5d42pvZb0r:-N_F1SoHAXsXPsA04KKw:b-ound5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L182)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Drew, shouldn't we delete all data from `abcd` table here? The way test is written right now is that we first insert 20k rows and run a bunch of other SELECT queries via EXPLAIN ANALYZE, then we insert another 20k rows and run the SELECTs again. The second run will have 40k rows, so it's expected to consume more RUs. If we delete all the data in-between, then we should be able to reduce the allowed delta.
</blockquote></details>

Good catch. Maybe we could add a `DELETE` test case at the end then?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-:-N_FD4MA2zvopYXlB3_s:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106730#-N_EvXE_DB5d42pvZb0r:-N_FCxrE9WcEsFAPAVG6:bhoqui9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9317e2fb7851a85b96c36b9f5f080e027c45a8/pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go#L182)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Good catch. Maybe we could add a `DELETE` test case at the end then?
</blockquote></details>

Good point, I think I'll do it in a separate PR after having stressed it to find the new delta value.

**Pull request merged**
