### PR TITLE
Revert "storageccl: use NewPebbleIterator in restore data processor"

### PR DESCRIPTION
**Pull request by msbutler**
This reverts commit 4d1f66e12d174fb3bf59549c4f660931552ffc8d.

Release Note: none

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
I think the panics should have been addressed with https://github.com/cockroachdb/cockroach/pull/84449, but stamping this and leaving it to your discretion.

**Comment by msbutler** [comment]
bors r=erikgrinaker

**Comment by msbutler** [comment]
bor r-
Will bors it later this evening if there is no quick fix to currrent failing roachtests 

https://github.com/cockroachdb/cockroach/issues/84240#issuecomment-1185820180

https://github.com/cockroachdb/cockroach/issues/84162#issuecomment-1185918916

**Comment by msbutler** [comment]
bor r-

**Pull request merged**
