### PR TITLE
tscache: re-use memory arena when cycling intervalSkl pages

### PR DESCRIPTION
**Pull request by nvb**
The `intervalSkl` structure used by `sklImpl` uses 32 MB page sizes.
These are large enough to warrant special care to prevent from
re-allocating them continuously. This change re-uses arenas during
page rotation whenever possible (which is most of the time).

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/tscache/interval_skl.go, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300#-L-22Qc5CIH52ZLVqa62:-L-22Qc5CIH52ZLVqa63:b-v8mtfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab45b78719ca6f80c1a321c346c50cc4d28dcbb/pkg/storage/tscache/interval_skl.go#L400)):*
> ```Go
> 
> 		// Evict the page.
> 		oldArena = bp.list.Arena()
> ```

I'm not sure if this is kosher. While `oldArena` has data that is too old, how can you be sure there are no concurrent readers of its data? If this is kosher, it isn't obvious and deserves an explanatory comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/tscache/interval_skl.go, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300#-L-22Qc5CIH52ZLVqa62:-L-2AKeitAgVsd5mwPGW:b-ekahp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab45b78719ca6f80c1a321c346c50cc4d28dcbb/pkg/storage/tscache/interval_skl.go#L400)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure if this is kosher. While `oldArena` has data that is too old, how can you be sure there are no concurrent readers of its data? If this is kosher, it isn't obvious and deserves an explanatory comment. 
</blockquote></details>

Added an explanation of why this is safe. Also removed unnecessary atomics around here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/tscache/interval_skl.go, line 400 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300#-L-22Qc5CIH52ZLVqa62:-L-2BgWZL17Woi8_TGpe:b-l0dzj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab45b78719ca6f80c1a321c346c50cc4d28dcbb/pkg/storage/tscache/interval_skl.go#L400)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Added an explanation of why this is safe. Also removed unnecessary atomics around here.
</blockquote></details>

Thanks. Explanation is good. I had forgotten about the rotation mutex.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20300#-:-L-2BrQHMztSfeqRB-oV:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Thanks for the review.

**Pull request merged**
