### PR TITLE
opt: avoid generating trivial constrained scans

### LINKED ISSUE #114250: sql: Improve planGist to show Full Scan on hash-sharded indexes when entire set is read
The `plan gist` for the executed query whose plan is below does not return as a FULL SCAN.

```
info
------------------------------------------------------------------------------------------------
distribution: local
vectorized: true

• top-k
│ estimated row count: 1
│ order: -createdtime
│ k: 1
│
└── • filter
│ estimated row count: 1
│ filter: rebid = 205512205
│
└── • scan
estimated row count: 41,487,743 (100% of the table; stats collected 2 days ago)
table: os@pk_os
spans: [/0 - /29]
```

The planGIst for the executed query above does not show that 100% of the table was actually read.
```
select crdb_internal.decode_plan_gist('AgGsBgISEBETHyAtODk8QUNER09SVltfAgAAAxgFIAYg') as query_plan;

query_plan |
-----------------------------------------------+
• top-k |
│ order |
│ |
└── • filter |
│ |
└── • scan |
table: os@pk_os|
spans: 1+ spans |
```

[slack](https://cockroachlabs.slack.com/archives/C063CP41TG9/p1699637016285549)

Jira issue: CRDB-33420

gz#19284

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: extend constraint Contains method to handle common prefix

This patch extends the logic of `Constraint.Contains` to handle cases
when the columns of the left and right constraints differ beyond a common
prefix. The spans of one constraint can be compared with those of another
for containment when the following conditions are satisfied:
1. The common prefix between the left and right columns is non-empty.
2. Only one constraint can contain keys beyond the common prefix length.

These conditions ensure comparisons are valid by ensuring that comparison
only requires columns from the common prefix. Columns are only needed for
key comparisons up to the length of the shorter key, and the above conditions
guarantee that at least one key is always within the common prefix length.

Informs #114250

Release note: None

#### opt: avoid generating trivial constrained scans

This patch adds a check to the `GenerateConstrainedScans` optimizer rule
to prevent it from building trivial constrained scans that only use the
table's (non-selective) check constraints. This ensures that the resulting
plan will show a full scan as expected, and also prevents suboptimal index
joins in some cases.

Fixes #114250

Release note (sql change): The optimizer will no longer generate a
constrained scan that only uses filters from a check constraint. This
prevents cases where a constrained scan actually scans the entire table
because the constraints aren't selective.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Great find and fix!

> Reviewed 4 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-:-Nj9Ho9j5qcn4XwGhFUl:b-h1mmw6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/explain` line 2400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9H_OL8QS0KSw242Qb:-Nj9H_OL8QS0KSw242Qc:bkgerdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a612a4cd703796bc15721d2271c52137af1ea558/pkg/sql/opt/exec/execbuilder/testdata/explain#L2400)):*
> ```
>       └── k:6 = a:1 [outer=(1,6), constraints=(/1: (/NULL - ]; /6: (/NULL - ]), fd=(1)==(6), (6)==(1)]
> 
> # Regression test for #114250 - the EXPLAIN output should indicate a full scan.
> ```

nit: Not sure you really need this test. Either way, the message is confusing IMO since the fix doesn't have much to do about the EXPLAIN output—it's fixing a nonsense plan.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9FdX85Y-yJHMZlWDv:-Nj9FdX85Y-yJHMZlWDw:boz2bg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a612a4cd703796bc15721d2271c52137af1ea558/pkg/sql/opt/xform/testdata/rules/select#L2599)):*
> ```
> # scans the whole table using the table's check constraints.
> exec-ddl
> CREATE TABLE t114250 (x INT PRIMARY KEY USING HASH, y INT NOT NULL);
> ```

nit: it might be nice to have a test case with an explicit check constraint too.
___
*[`pkg/sql/opt/constraint/constraint_test.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9Dgza5txuiGF30qFN:-Nj9Dgza5txuiGF30qFO:b-rz20c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a42a17fccbeba7ff5bceecd8cb768007ff275d4a/pkg/sql/opt/constraint/constraint_test.go#L276)):*
> ```Go
> 			"/1/4: [/1 - /1]",
> 			"/1: [/1 - /1]",
> 			true,
> ```

nit: missing field names here. You can fix the existing test cases above without field names too if you'd like.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114332)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/explain` line 2400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9H_OL8QS0KSw242Qb:-NjC-MRf3BSdMPQVXCvW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a612a4cd703796bc15721d2271c52137af1ea558/pkg/sql/opt/exec/execbuilder/testdata/explain#L2400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Not sure you really need this test. Either way, the message is confusing IMO since the fix doesn't have much to do about the EXPLAIN output—it's fixing a nonsense plan.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2599 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9FdX85Y-yJHMZlWDv:-NjC-TCa5zHswT3FXzT7:bc3byvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a612a4cd703796bc15721d2271c52137af1ea558/pkg/sql/opt/xform/testdata/rules/select#L2599)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: it might be nice to have a test case with an explicit check constraint too.
</blockquote></details>

Good idea, done. Actually, it turns out you can't use `USING HASH` for optimizer tests anyway. I'm not sure why it worked before, but it seems like it wasn't actually testing what I wanted it to.
___
*[`pkg/sql/opt/constraint/constraint_test.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-Nj9Dgza5txuiGF30qFN:-NjC-AMS-jbeNMTRFwid:b4mzaqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a42a17fccbeba7ff5bceecd8cb768007ff275d4a/pkg/sql/opt/constraint/constraint_test.go#L276)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: missing field names here. You can fix the existing test cases above without field names too if you'd like.
</blockquote></details>

Oh, good catch. Fixed it.

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-:-NjEih6v-u3fSIwoPJan:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/constraint/columns.go` line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-NjEhtnz2U2fCASnwHqT:-NjEhtnz2U2fCASnwHqU:b-uqolnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3315f1facd21cd9c4a71edc85166e5f4e8cefcac/pkg/sql/opt/constraint/columns.go#L101)):*
> ```Go
> 	}
> 	length := 1
> 	for i := 0; i < len(c.otherCols) && i < len(other.otherCols); i++ {
> ```

TIL about this nice alternative to using two variables to iterate over slices. Cool trick!

**Review by mgartner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 8 of 8 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114332#-:-NjF9nHp70CHcJ1-5-5V:b-uwkowd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

**Pull request merged**
