### PR TITLE
roachprod: add dynamic bash completer

### PR DESCRIPTION
**Pull request by dt**
This replaces the previous attempt at completing cluster/hostnames by
putting them in `ValidArgs` when generating the completions file.

That appraoch did not work well -- even though the file itself was
regenerated whenever the cached cluster info was sync'ed, the static
completion definitions loaded from it often lived for days or weeks in
an open shell, requiring manual reloading to be updated.

This changes the approach so the static definitions no longer contain
the actual cluster/host names, but instead call out to a new subcommand
of `roachprod` called `cached-hosts` to get the set of valid clusters or
hosts within each cluster from its local cache. This is the same cache
that would actually be used to e.g. execute `adminurl foo:1`.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Cool. Should we document somewhere how developers can take advantage of this or does it happen automagically if roachprod is in PATH?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-:-LZu_4110hQPdSe1e__v:bf2w4n6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuXxfo0dNbMsGgs4fh:-LZuXxfo0dNbMsGgs4fi:b-1m38p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce03b673b3566ca4b9caa8676167b22791959f6/pkg/cmd/roachprod/main.go#L494)):*
> ```Go
> 			fmt.Print(c.Name)
> 			// when invokved by bash-completion, cachedHostsCluster is what the user
> 			// has currently typed -- if this cluster matches that, expand its hosts.
> ```

What does adding the hosts really give you? Is it about being able to cycle through the completions? It seems weird that we're going to output `ajwerner-test:3` when I've typed `ajwerner-test:1` and then tab though maybe bash and compgen just sort of deals with that?
___
*[pkg/cmd/roachprod/main.go, line 1391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuZaFG1eMpewGdmz1H:-LZuZaFG1eMpewGdmz1I:b-jtsvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce03b673b3566ca4b9caa8676167b22791959f6/pkg/cmd/roachprod/main.go#L1391)):*
> ```Go
> 
> 	}`,
> 		func(cmds ...*cobra.Command) string {
> ```

nit: how about
```
strings.Join(func(cmds ...*cobra.Command) (s []string) {
    for _, cmd := range cmds {
        s = append(s, rootCmd.Name()+"_"+cmd.Name())
    }
    return s
}(createCmd, listCmd, syncCmd, gcCmd, webCmd, dumpCmd), " | ")
```

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @tbg)

**Review by dt — COMMENTED** [review]
How to take advantage of this is same as before this change -- it's up to you when/where to source the completion file. Only difference is now you don't need to re-source it to get updated cluster names since it not longer changes the completions themselves, but rather has them query roachprod to get the current options.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-:-LZudbxK-Y4paqM62hK3:b-vfucjo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuXxfo0dNbMsGgs4fh:-LZue6B_5aeFNX8mSxIg:b45vkve) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce03b673b3566ca4b9caa8676167b22791959f6/pkg/cmd/roachprod/main.go#L494)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What does adding the hosts really give you? Is it about being able to cycle through the completions? It seems weird that we're going to output `ajwerner-test:3` when I've typed `ajwerner-test:1` and then tab though maybe bash and compgen just sort of deals with that?
</blockquote></details>

yeah, compgen deals with returning the right things.  Only reason to filter here to keep the options presented while you're first picking a cluster a bit smaller e.g. in case *someone has a 128 node cluster running.
___
*[pkg/cmd/roachprod/main.go, line 1391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuZaFG1eMpewGdmz1H:-LZufcmE2bJz-S-QLLdU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ce03b673b3566ca4b9caa8676167b22791959f6/pkg/cmd/roachprod/main.go#L1391)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: how about
```
strings.Join(func(cmds ...*cobra.Command) (s []string) {
    for _, cmd := range cmds {
        s = append(s, rootCmd.Name()+"_"+cmd.Name())
    }
    return s
}(createCmd, listCmd, syncCmd, gcCmd, webCmd, dumpCmd), " | ")
```
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-:-LZuh1OQ0JDjs254vYuB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 1396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuiSRK9XP7fF-cTcee:-LZuiSRK9XP7fF-cTcef:b10mmne) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f2b397bf890968bb45a34d2d6d282fd8485dda6/pkg/cmd/roachprod/main.go#L1396)):*
> ```Go
> 			}
> 			return s
> 		}(createCmd, listCmd, syncCmd, gcCmd, webCmd, dumpCmd), " | "),
> ```

Can we add some more commands here? putCmd, startCmd, stopCmd, wipeCmd, stageCmd, sqlCmd etc.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35301)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 1396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35301#-LZuiSRK9XP7fF-cTcee:-LZuj6sABeqr-i_qDe2S:bftzf4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f2b397bf890968bb45a34d2d6d282fd8485dda6/pkg/cmd/roachprod/main.go#L1396)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we add some more commands here? putCmd, startCmd, stopCmd, wipeCmd, stageCmd, sqlCmd etc.
</blockquote></details>

See the comment above: these are the commands which _don't_ get completions.

**Comment by ajwerner** [comment]
Whoops, ignore me. I got excited about the existence of bash completion, went and set it up without this patch, discovered it only worked on some of these commands with the old logic and in a rush forget that I had just read through that logic for the short circuit. Thanks for making the change!

**Comment by dt** [comment]
btw, if you're into bash completions, I added a completion generator to `workload` earlier this week.

**Pull request merged**
