### PR TITLE
roachtest: add test for elasticWorkload

### PR DESCRIPTION
**Pull request by andrewbaptist**
This commit adds three new perturbation tests:
perturbation/metamorphic/elasticWorkload
perturbation/full/elasticWorkload
perturbation/dev/elasticWorkload
The tests run an elastic workload as the perturbation.

Epic: none

Release note: None

### CODE REVIEW

**Comment by andrewbaptist** [comment]
I'll kick off a test (I already tried dev and it worked) - we can tweak it based on how this looks.

**Comment by kvoli** [comment]
Could you share the test results / metrics link here somewhere?

**Comment by andrewbaptist** [comment]
Here is the latest run with this code:
[Standard](
https://go.crdb.dev/roachtest-grafana/baptist-cockroachlabs-com-1729267247/perturbation-full-elasticworkload/1729267348969/1729269471993)
[Detailed](
https://grafana.testeng.crdb.io/d/J-yAVzkVddd/detailed?from=1729267348969&to=1729269471993&var-cluster=baptistcockroachlabscom-1729267247-01-n13cpu16lm&orgId=1)

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132914)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, @nameisbhaskar, and @pav-kv)

___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViSz52Q5aSBKw7PsX:-O9ViSz52Q5aSBKw7PsY:b-nv1klm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L320)):*
> ```Go
> // runs at 50% CPU this adds another 2x the stable rate so it will be slowed
> // down by AC.
> // TODO(baptist): Add whether we ramp or start full workload
> ```

Doesn't seem necessary to ramp -- its a good test of the burst.


___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViJld7NO4yLX1ho78:-O9ViJld7NO4yLX1ho79:b-e5a0hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L322)):*
> ```Go
> // TODO(baptist): Add whether we ramp or start full workload
> // TODO(baptist): Add max usage of the workload.
> // TODO(baptist): Add block size.
> ```

What did you have in mind? The block size being used is 4kb iiuc.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViFtV6i2ovAts2bqf:-O9ViFtV6i2ovAts2bqg:b4jfh73) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L323)):*
> ```Go
> // TODO(baptist): Add max usage of the workload.
> // TODO(baptist): Add block size.
> // TODO(baptist): Add a max rate.
> ```

The max rate probably isn't necessary, we want it to run as fast as possible.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9VikWD-4wvtkwj6lXk:-O9VikWD-4wvtkwj6lXl:bup9j6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L344)):*
> ```Go
> 	// new workloads. Otherwise the rate won't be relevant.
> 	runCmd := fmt.Sprintf(
> 		"./cockroach workload run kv --db elastic --txn-qos=background --duration=%s --max-rate=%d --max-block-bytes=%d --min-block-bytes=%d --concurrency=500 {pgurl%s}",
> ```

Could this run against the same DB, it might produce more interesting results if the keyspaces between the two workloads overlap.

**Review by andrewbaptist — COMMENTED** [review]
I cleaned up some of the comments and removed the max rate. I'm running one more time now and will post an update afterwards, but I think this is a good test because it at least highlights the advantages of non-Repl AC. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-:-O9vKqmJBS28SK2yxj2X:bg5ymc0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @kvoli, @nameisbhaskar, and @pav-kv)

___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViSz52Q5aSBKw7PsX:-O9v6eDl-EDFjcDVMme_:bh7htis) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L320)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Doesn't seem necessary to ramp -- its a good test of the burst.


</blockquote></details>

Good point, I'll leave that off. The idea was that maybe we would handle a ramp start better, but it seems like it is good enough as is so no need to complicated this further.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViJld7NO4yLX1ho78:-O9v6m6FCJGV-opMCkwQ:b-9igonl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L322)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

What did you have in mind? The block size being used is 4kb iiuc.
</blockquote></details>

I changed to use the same block size as the workload node so this comment was stale. I'll remove it.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViFtV6i2ovAts2bqf:-O9v6slI6Bw0Dcbm-r5f:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L323)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The max rate probably isn't necessary, we want it to run as fast as possible.
</blockquote></details>

Removed.
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9VikWD-4wvtkwj6lXk:-O9v7-4V-H93cnp4DPok:b-6cum0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L344)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could this run against the same DB, it might produce more interesting results if the keyspaces between the two workloads overlap.
</blockquote></details>

While this is a great idea, it doesn't easily work because of the approach to the fingerprints. Specifically the new workload and the old have overlapping fingerprints which means there are 1000s of traces from the elastic workload. There are workarounds, but they require modifying the query. I left a TODO and will look at this in the future.

**Comment by kvoli** [comment]
Is this ready for another review @andrewbaptist ?

**Comment by andrewbaptist** [comment]
@kvoli  - Yes. Please take another pass!

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-:-OA31Ylg2IK4yVfE41z8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, @nameisbhaskar, and @pav-kv)

___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViJld7NO4yLX1ho78:-OA31WvEExFDgeW0_cAG:b32wwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L322)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I changed to use the same block size as the workload node so this comment was stale. I'll remove it.
</blockquote></details>

sg
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9ViFtV6i2ovAts2bqf:-OA31WLnD8l-tu7D2gQK:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L323)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Thanks
___
*[`pkg/cmd/roachtest/tests/admission_control_latency.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132914#-O9VikWD-4wvtkwj6lXk:-OA31VOD2xpTEB2l4VQI:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b241a25f209cd23d571f39d59998eb3e7bfc3c21/pkg/cmd/roachtest/tests/admission_control_latency.go#L344)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

While this is a great idea, it doesn't easily work because of the approach to the fingerprints. Specifically the new workload and the old have overlapping fingerprints which means there are 1000s of traces from the elastic workload. There are workarounds, but they require modifying the query. I left a TODO and will look at this in the future.
</blockquote></details>

sgtm

**Pull request merged**
