### PR TITLE
kvclient, roachpb: cleanup the CPut API

### PR DESCRIPTION
**Pull request by andreimatei**
The CPut API was funky: it took an expected value as a roachpb.Value,
but the checksum in it and the timestamp didn't matter. This was
undocumented. The checksum in particular covers both the key and the
value, so its relationship with a CPut is weird (since the key for
which we're using the value might be different from the key from whence
it came). This choice of Value had consequences for the Batch API:
Batch.CPut() was taking a *roachpb.Value, for which it cleared and then
re-initialized the checksum. This was all surprising, and meant that
some callers had to copy the underlying bytes for the value before
passing them to CPut().

This patch changes all the interfaces to just take []byte. There's no
longer a checksum or a timestamp to speak of. CPut() now also internally
copies the expected value's bytes, so the caller no longer needs to
worry about ownership.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Basically looks good, had a few comments, thanks for working this out.

> Reviewed 9 of 9 files at r1, 27 of 27 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-:-MAAzqxA0cnA_3uguNi0:b-g8q5x7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @irfansharif, and @nvanbenschoten)

___
*[Makefile, line 1230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAxeJW6c5orXlPjyp7:-MAAxeJW6c5orXlPjyp8:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/Makefile#L1230)):*
> ```Makefile
> PROTO_MAPPINGS := $(PROTO_MAPPINGS)Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,
> PROTO_MAPPINGS := $(PROTO_MAPPINGS)Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,
> PROTO_MAPPINGS := $(PROTO_MAPPINGS)Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,
> ```

?
___
*[pkg/roachpb/api.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAyrqD8hDSdFZurNJL:-MAAyrqD8hDSdFZurNJM:bmvik11) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.go#L981)):*
> ```Go
> 	var expBytes *types.BytesValue
> 	if expValue != nil {
> 		expBytes = &types.BytesValue{
> ```

Why? This is an extra alloc, what value does this provide? Distinguishing between "nothing" and empty? You could also do that with an additional bool. (I'll defer to @nvanbenschoten on whether this is important enough to do, but it's the pattern I wished protobufs in Go used generally via a bitmap).
___
*[pkg/roachpb/api.proto, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAzO9m6IpA3e3VSy8O:-MAAzO9m6IpA3e3VSy8P:b-tu3n7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.proto#L193)):*
> ```protobuf
>   Value deprecated_exp_value = 3;
>   // exp_bytes represents the expected existing value for the key. If missing,
>   // the key is expected to not exist. If set to []byte{}, the value is expected
> ```

You can't set this to `[]byte{}`, make this precise.
___
*[pkg/roachpb/api.proto, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAz_8R92P7TBumWSpf:-MAAz_8R92P7TBumWSpg:bb6rrlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.proto#L202)):*
> ```protobuf
>   //
>   // Note that the existing value's timestamp doesn't matter, only its data. So,
>   // the CPut will succeed in ABA situations.
> ```

ABA?

**Review by andreimatei — COMMENTED** [review]
prepended a commit. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-:-MAD8UzE3LqsuH48kCYW:b6x740f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @irfansharif, @nvanbenschoten, and @tbg)

___
*[Makefile, line 1230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAxeJW6c5orXlPjyp7:-MACOD3H8PfSwejlHkfc:b-ck9j0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/Makefile#L1230)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

?
</blockquote></details>

for `google.protobuf.BytesValue`. But it's gone.
___
*[pkg/roachpb/api.go, line 981 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAyrqD8hDSdFZurNJL:-MAD8NqKEklbkxch1dbg:bf91piw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.go#L981)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why? This is an extra alloc, what value does this provide? Distinguishing between "nothing" and empty? You could also do that with an additional bool. (I'll defer to @nvanbenschoten on whether this is important enough to do, but it's the pattern I wished protobufs in Go used generally via a bitmap).
</blockquote></details>

The distinction has gone away. See the first commit.
___
*[pkg/roachpb/api.proto, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAzO9m6IpA3e3VSy8O:-MAD7kycAQHEwb90F9GD:bcfgp23) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.proto#L193)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You can't set this to `[]byte{}`, make this precise.
</blockquote></details>

Well the intention was that you could set it to that. But I've done some digging and decided to remove the distinction between missing keys and keys with empty values, since the latter don't actually exist. See now.
___
*[pkg/roachpb/api.proto, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAAz_8R92P7TBumWSpf:-MAD86xf8H0I3j3uiOI3:b-xytfxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9800b8ba891861b173ac291c485cf677c9ca86a3/pkg/roachpb/api.proto#L202)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

ABA?
</blockquote></details>

I thought it's a known term. Explained.

**Review by irfansharif — APPROVED** [review]
:lgtm: 

> Reviewed 33 of 33 files at r3, 9 of 9 files at r4, 26 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-:-MARJZEe4KoIEkaqUFPg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1963 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAREnBFCS1u34FHSvKE:-MAREnBFCS1u34FHSvKF:b-9bgcdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea00b4efc6771186fea6cf14174d7506c3b7c31/pkg/kv/kvserver/replica_command.go#L1963)):*
> ```Go
> // parsed RangeDescriptor directly as the expected value in a CPut, but proto
> // message encodings aren't stable so this was fragile. Calling this method and
> // then passing the returned nytes as the expected value in a CPut does the same
> ```

s/nytes/bytes
___
*[pkg/roachpb/api.proto, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MARG9kf4S92ZJ7Y0Dxv:-MARG9kf4S92ZJ7Y0Dxw:b-gku0rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea00b4efc6771186fea6cf14174d7506c3b7c31/pkg/roachpb/api.proto#L182)):*
> ```protobuf
>   // deprecated_exp_val represents the expected existing value for the key. If
>   // the existing value is different, the request will return a
>   // ConditionFailedError. A missing (Go nil) exp_value.raw_bytes means that the
> ```

s/exp_value/deprecated_exp_value

**Review by tbg — APPROVED** [review]
Looks good, I only reviewed the "clarify that Put() with nil value is not a thing" commit. Let me know if I should also re-visit anything else.

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-:-MAfrLk3DVm-B1h0YSwP:b-6rbzir)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @irfansharif, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1963 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MAREnBFCS1u34FHSvKE:-MAfpN0l2bSjMORfVkFJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea00b4efc6771186fea6cf14174d7506c3b7c31/pkg/kv/kvserver/replica_command.go#L1963)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/nytes/bytes
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-MARG9kf4S92ZJ7Y0Dxv:-MAfrc8O-IrCoMiyiw-b:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dea00b4efc6771186fea6cf14174d7506c3b7c31/pkg/roachpb/api.proto#L182)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/exp_value/deprecated_exp_value
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50408#-:-MAgl-zUCxnY0NlscyFp:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @irfansharif, @nvanbenschoten, and @tbg)

**Pull request merged**
