### PR TITLE
workload/schemachange: only allow PK change in single statement transactions

### PR DESCRIPTION
**Pull request by rafiss**
This will avoid errors of the form: "cannot perform other schema changes in the same transaction as a primary key change."

informs: #128615
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128834)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, @rafiss, and @vidit-bhat)

___
*[`pkg/workload/schemachange/operation_generator.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128834#-O46ubRjCiWT-UUH3PM7:-O46ubRjCiWT-UUH3PM8:b-lhxvrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f185a6d99fa3c15d6fbdf85533111e94a9f59a9/pkg/workload/schemachange/operation_generator.go#L200)):*
> ```Go
> 		if numOpsInTxn != 1 {
> 			// DML and PK changes are only allowed in single-statement transactions.
> 			if isDMLOpType(op) || op == alterTableAlterPrimaryKey {
> ```

We should allow this for declarative txns? Those support doing multiple operations

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128834)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @fqazi, @herkolategan, and @vidit-bhat)

___
*[`pkg/workload/schemachange/operation_generator.go` line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128834#-O46ubRjCiWT-UUH3PM7:-O47Nou74rvuvI9FWf4X:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f185a6d99fa3c15d6fbdf85533111e94a9f59a9/pkg/workload/schemachange/operation_generator.go#L200)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We should allow this for declarative txns? Those support doing multiple operations
</blockquote></details>

done

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128834#-:-O47O1VDAP4-OXPcRWer:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, and @vidit-bhat)

**Pull request merged**
