### PR TITLE
closedts: avoid logging failures on startup

### LINKED ISSUE #44846: kv: closed ts catch-up warning causes unnecessary alarm
User reports that the "closed ts" warning is alarming:

```
W200207 07:03:58.656484 81 storage/closedts/provider/provider.go:150 [ct-closer] unable to move closed timestamp forward: not live 
```

The warning occurs when the node is restarted as part of regular system administration operations. In that case it is expected that the closed timestamp cannot move forward, and thus a warning is not warranted.

### PR DESCRIPTION
**Pull request by ajwerner**
Before this commit it was commonly the case that nodes would fail to move the
closed timestamp due to not being live when they start up. This warning was
concerning to customers. Now we'll track whether we've ever been live and only
log if we find that we are not live later.

Fixes #44846

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
💯 thanks!

**Comment by ajwerner** [comment]
TFTR!

bors r=tbg

**Comment by ajwerner** [comment]
bors r=tbg

**Comment by ajwerner** [comment]
bors r=tbg

**Pull request merged**
