### PR TITLE
sql: support a limited subset of correlated SRFs

### PR DESCRIPTION
**Pull request by knz**
Next-to-last step before solving  #16971.

This patch extends the "project set" operator previously implemented
so that it can evaluate expressions using references to the rows of
the source. This makes it able to evaluate SRFs correlated with the
data source.

This patch then extends the transform of SRFs in render position
to use the new functionality. With this patch, a query like this now
runs properly: `SELECT unnest(indkey) from pg_index`

Although the execution logic is now able to run arbitrary correlated
SRFs, the planning for `ROWS FROM` is not yet adjusted to use this
functionality and therefore SRFs listed in `ROWS FROM` cannot be
correlated yet.

Release note (sql change): CockroachDB now can evaluate set-generating
functions with arguments that refer to the FROM clause. **In particular
this makes it possible to use `json_each()`, `json_object_keys()` etc
over JSON columns.**

cc @solongordon 
cc @justinj

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

But probably a good idea to have another set of eyes on this too.  Someone with a deeper history of planning.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/opt_needed.go, line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-LEQxH6kCjbqJzl8bJgv:-LEQxH6kCjbqJzl8bJgw:b13pcsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/da68eba86174e8d83a58ec88d4f832fd12f7fc0a/pkg/sql/opt_needed.go#L114)):*
> ```Go
> 				// needed. Remove it.
> 				n.exprs[i] = tree.DNull
> 			}
> ```

could this be an else if?

---

*[pkg/sql/logictest/testdata/logic_test/srfs, line 864 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-LEQbWT76UKIGN8AcsGA:-LEQbWT76UKIGN8AcsGB:bfw9qcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da68eba86174e8d83a58ec88d4f832fd12f7fc0a/pkg/sql/logictest/testdata/logic_test/srfs#L864)):*
> ```
> #          index_name,
> #          ordinal_position
> # ----
> ```

Are you missing an empty line at the end?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-:-LEQxRqL-aWUObrq6Pj3:bkbbfgg)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt_needed.go, line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-LEQxH6kCjbqJzl8bJgv:-LETwch16rN_JtGZbs88:b-r8wxxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/da68eba86174e8d83a58ec88d4f832fd12f7fc0a/pkg/sql/opt_needed.go#L114)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

could this be an else if?
</blockquote></details>

No but it can certainly be simplified. Done.

---

*[pkg/sql/logictest/testdata/logic_test/srfs, line 864 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-LEQbWT76UKIGN8AcsGA:-LETwiYv7NNRTp9-1smf:b-tqz3xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/da68eba86174e8d83a58ec88d4f832fd12f7fc0a/pkg/sql/logictest/testdata/logic_test/srfs#L864)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are you missing an empty line at the end?
</blockquote></details>

Yep, thanks for noticing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26503)*

**Comment by solongordon** [comment]
:lgtm: Great to see this functionality!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3, 2 of 6 files at r4, 2 of 2 files at r5.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26503#-:-LEkY0KyE3peVAfl_8ma:b-z647lk)*

**Comment by knz** [comment]
Thank you!

bors r+

**Pull request merged**
