### PR TITLE
sql: inline `addActiveQuery` anonymous function

### PR DESCRIPTION
**Pull request by mgartner**
#### opt/bench: disable some background work in `BenchmarkEndToEnd`

Automatic table stats collection and SQL stats (metrics) have been
disabled in the end-to-end benchmarks so that they better highlight the
performance of executing queries. Note that this will improve all the
benchmark results a bit, even though the code paths targeted by this
benchmark have not been changed.

Release note: None

#### sql: inline `addActiveQuery` anonymous function

The `addActiveQuery` anonymous function in `execStmtInOpenState`
modified the `ctx context.Context` parameter. This confused Go's escape
analysis into thinking that the `ctx` value must be heap allocated.
References to `ctx` in other closures must see the newly assigned value.
The lifetime of the closures in the function are not clear (for the
compiler or a human), and so I believe Go assumed that reassignment and
accesses could occur multiple times or at any point in the future.
Therefore, it required the value of `ctx` must not be stack allocated.

This commit inlines `addActiveQuery`, which was only invoked once. This
eliminates confusion about the `ctx` parameter during escape analysis
and it is no longer heap allocated. Note that there's likely a few
different changes to other closures that may have eliminated this
allocation, this is just one of the simpler ones.

Future work will simplify `execStmtInOpenState` further and eliminate
unnecessary allocations like this one.

Informs #135908

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
`BenchmarkEndToEnd` shows the elimination of 1 allocation per query:

```
name                                     old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple        129µs ± 4%     132µs ± 5%  +1.95%  (p=0.008 n=18+17)
EndToEnd/kv-read/vectorize=on/Prepared     77.8µs ± 5%    80.6µs ± 8%  +3.58%  (p=0.004 n=20+19)
EndToEnd/kv-read/vectorize=off/Simple       157µs ± 3%     157µs ± 2%    ~     (p=0.753 n=18+19)
EndToEnd/kv-read/vectorize=off/Prepared    85.8µs ±10%    83.8µs ± 6%    ~     (p=0.070 n=19+20)

name                                     old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Simple       31.6kB ± 5%    31.4kB ± 1%    ~     (p=0.162 n=18+16)
EndToEnd/kv-read/vectorize=on/Prepared     20.3kB ± 0%    20.2kB ± 0%    ~     (p=0.066 n=16+16)
EndToEnd/kv-read/vectorize=off/Simple      32.5kB ± 0%    32.5kB ± 0%    ~     (p=0.845 n=17+17)
EndToEnd/kv-read/vectorize=off/Prepared    21.4kB ± 0%    21.4kB ± 0%  -0.11%  (p=0.007 n=17+17)

name                                     old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Simple          296 ± 0%       295 ± 1%  -0.38%  (p=0.000 n=13+16)
EndToEnd/kv-read/vectorize=on/Prepared        208 ± 0%       207 ± 0%  -0.49%  (p=0.000 n=18+19)
EndToEnd/kv-read/vectorize=off/Simple         288 ± 0%       287 ± 0%  -0.35%  (p=0.000 n=15+17)
EndToEnd/kv-read/vectorize=off/Prepared       200 ± 0%       199 ± 0%  -0.54%  (p=0.000 n=17+18)```

**Review by yuzefovich — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-:-ODI79M92rXPsePFfppF:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @mw5h, @nvanbenschoten, and @RaduBerinde)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-ODI6k9T2aA02-uL2rAn:-ODI6k9T2aA02-uL2rAo:bn7vgb3):*
Should we backport this commit to have proper comparison with 24.3 branch?
___
*[`pkg/sql/conn_executor_exec.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-ODI7McKB9qyJn7KguTv:-ODI7McKB9qyJn7KguTw:bsrmov4) ([raw file](https://github.com/cockroachdb/cockroach/blob/82dfebb289a6cda87423b811d2bcaf5eea639312/pkg/sql/conn_executor_exec.go#L422)):*
> ```Go
> 		ex.incrementStartedStmtCounter(vars.ast)
> 		func(st *txnState) {
> 			ex.state.mu.Lock()
> ```

Why did this change? Should we remove the argument to anonymous function then?

**Comment by RaduBerinde** [comment]
*[`pkg/sql/conn_executor_exec.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-ODI7McKB9qyJn7KguTv:-ODITHIWDaC7zmiagKb4:ba9zd8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/82dfebb289a6cda87423b811d2bcaf5eea639312/pkg/sql/conn_executor_exec.go#L422)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why did this change? Should we remove the argument to anonymous function then?
</blockquote></details>

Do we need this func at all? Can't we just Lock, increment, Unlock. It's not like we expect that the increment might panic

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136730)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mw5h, @nvanbenschoten, @RaduBerinde, and @yuzefovich)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-ODI6k9T2aA02-uL2rAn:-ODIVP2Z2l7n7f2-aY8n:b-fixocr):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we backport this commit to have proper comparison with 24.3 branch?
</blockquote></details>

Sure, I will backport this to 24.3.
___
*[`pkg/sql/conn_executor_exec.go` line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-ODI7McKB9qyJn7KguTv:-ODIVRLf3mziKwhuwPqC:b5mnzm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/82dfebb289a6cda87423b811d2bcaf5eea639312/pkg/sql/conn_executor_exec.go#L422)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need this func at all? Can't we just Lock, increment, Unlock. It's not like we expect that the increment might panic
</blockquote></details>

I had had the same thought and accidentally had changes from both versions. I've removed the function entirely now.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-:-ODIWk165GWSXbRIGsQ7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mw5h, @nvanbenschoten, and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136730#-:-ODInL6zC8IMWsIRvLEE:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mw5h and @nvanbenschoten)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
