### PR TITLE
ui: add mvcc info to Database page

### LINKED ISSUE #82617: Add information on MVCC garbage data on the databases page
We should add observability into 'dead'/MVCC garbage data that has not been cleaned up which can potentially be impacting workload performance. 

This relates to the following [issue](https://github.com/cockroachdb/cockroach/issues/72048) but provides a higher-level view at the table level on the Databases page.

One potential user flow: SQL Activity -> Statements -> Details view -> Plan View -> [Index details](https://github.com/cockroachdb/cockroach/issues/82615)

[Slack context](https://cockroachlabs.slack.com/archives/C02R38EEPNV/p1654679913454319).

Column name: % of Non-live Data

Tool tip description: % of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.

Jira issue: CRDB-16540

### PR DESCRIPTION
**Pull request by maryliag**
This commit adds the mvcc info to:
- Column on the tables list inside Database page
- Table Details page

Fixes https://github.com/cockroachdb/cockroach/issues/82617

Screen Shot 2022-07-11 at 5 20 04 PM

Screen Shot 2022-07-11 at 5 20 53 PM

Screen Shot 2022-07-08 at 5 35 49 PM

Release note (ui change): Adds mvcc info to tables list inside
the Database page and on the Tables details page.

### CODE REVIEW

**Review by kevin-v-ngo — COMMENTED** [review]
Replication Size and Total doesn't seem to align. Any reason why? I would've guessed that Total was the non-replication size but that doesn't seem to be the case since they're so close. What's the replication factor of this cluster?

**Comment by ajwerner** [comment]
One note here is that it won't work in multi-tenant clusters as a general approach because we pack the tables together into a range. This isn't new and this does mean also that the live bytes calculation is garbage there too. We need some new tools. This fact imperils https://github.com/cockroachdb/cockroach/issues/81008.

**Comment by knz** [comment]
> The changes here affect DB Console only.
ok, but...
>  it won't work in multi-tenant clusters as a general approach because we pack the tables together into a range

This fact remains true and endangers our roadmap for INI-214.

Andrew and Marylia, could you collaborate to file a follow-up issue that describes the work needed to make this work on the DB Console of a  multi-tenant dedicated cluster?

Then you can set "Epic" field to CRDB-16704 in the issue description to link them together.

cc @ajstorm for tracking.

**Review by Annebirzin — APPROVED** [review]

**Comment by ajwerner** [comment]
I filed https://github.com/cockroachdb/cockroach/issues/84105 to build a mechanism which we can use for sub-range storage calculations and epic linked it. It may not contain enough details about hooking up that new mechanism to all the various use cases.

**Comment by knz** [comment]
thank you!

**Comment by maryliag** [comment]
Updates made (commit and PR message/images) to show info about live instead of non-live

**Review by matthewtodd — APPROVED** [review]
Frontend code LGTM

**Comment by maryliag** [comment]
TFTR!
bors r+

**Pull request merged**
