### PR TITLE
raft: consolidate all append message sending

### PR DESCRIPTION
**Pull request by pav-kv**
This PR consolidates all decision-making about sending append messages into a single `maybeSendAppend` method. Previously, the behaviour depended on the `sendIfEmpty` flag which was set/unset depending on the context in which the method is called. This is unnecessary because the `Progress` struct contains enough information about the leader->follower flow state, so `maybeSendAppend` can be made stand-alone.

In follow-up PRs, the consolidated `maybeSendAppend` method will be used to implement a more flexible message flow control.

Ported from https://github.com/etcd-io/raft/pull/134

Epic: CRDB-37515
Release note: none

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @pav-kv)

___
*[`pkg/raft/raft.go` line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnYNiA7DQ7sDzpKEI2:-NxnYNiB2xFIBZzkf84-:b-on4gxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L555)):*
> ```Go
> // log has been compacted) it can send a MsgSnap.
> //
> // In some cases, the MsgApp message can have zero entries, and yet being sent.
> ```

s/being/be/
___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-Nxna2Ar5bwkexvhCAVY:b4lugiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
> ```Go
> 	case pb.MsgHeartbeatResp:
> 		pr.RecentActive = true
> 		pr.PauseMsgAppProbes(false)
> ```

How will we want to handle this in a world where a raft group is not performing any heartbeats? Should the leader's tick loop periodically check which followers are connected (using e.g. store liveness) and call `r.maybeSendAppend` on those followers?
___
*[`pkg/raft/tracker/progress.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnWPfeEOlvVEd1ktNs:-NxnWPfeEOlvVEd1ktNt:byr851z) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L182)):*
> ```Go
> // the passed-in bool.
> func (pr *Progress) PauseMsgAppProbes(pause bool) {
> 	pr.MsgAppFlowPaused = pause
> ```

If we are changing the meaning of this flag to only refer to empty MsgApps, should we rename it to `MsgAppProbesPaused`?
___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-NxnZNnQ1e6hwxwQpRI2:b-7j03hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
> ```Go
> //
> // In StateSnapshot, we do not send append messages.
> func (pr *Progress) ShouldSendMsgApp(last, commit uint64) bool {
> ```

I'm finding the relationship between the `CanSendEntries`, `ShouldSendMsgApp`, and `IsPaused` predicates to be difficult to understand. `ShouldSendMsgApp` and `IsPaused` are close to inverses of each other, but they're not exactly inverses.

Are we intending to phase out `IsPaused`?

If not, can one be written in terms of the other to make the relationship more clear?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-NxsZfSI2p2VruMH7p5d:b-1qxd91) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How will we want to handle this in a world where a raft group is not performing any heartbeats? Should the leader's tick loop periodically check which followers are connected (using e.g. store liveness) and call `r.maybeSendAppend` on those followers?
</blockquote></details>

Will we still have the tick loop? I guess so, since there are some things still depending on it (including some timeouts, like the reproposal threshold, expressed as tick counts).

The way it works now: in a throttled state there is a `maybeSendAppend` roughly once per heartbeat interval (if the heartbeat responses indicate that the follower is connected).

To mimic this behaviour, we need to communicate the "peer is connected" bit to the MsgApp flow loop. We can use the liveness fabric to get this signal.

If we retain the tick loop, then we would be sending a MsgApp once in a few ticks. If we don't retain the tick loop, we need something else to schedule these periodic MsgApp heartbeats. For example, we can replace the tick loop with a MsgApp heartbeat loop, or tie this to some other periodic "scan all ranges" kind of job.
___
*[`pkg/raft/tracker/progress.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnWPfeEOlvVEd1ktNs:-NxsfZ3W4kt8iys8_Na7:b-311jz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L182)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we are changing the meaning of this flag to only refer to empty MsgApps, should we rename it to `MsgAppProbesPaused`?
</blockquote></details>

Yes, will add commit https://github.com/etcd-io/raft/pull/134/commits/91981c3f884a25f342795de031ee734974ca71be to this PR soon.
___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-NxsaqBZ0P61_lhGyS9b:b-m6fv5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm finding the relationship between the `CanSendEntries`, `ShouldSendMsgApp`, and `IsPaused` predicates to be difficult to understand. `ShouldSendMsgApp` and `IsPaused` are close to inverses of each other, but they're not exactly inverses.

Are we intending to phase out `IsPaused`?

If not, can one be written in terms of the other to make the relationship more clear?
</blockquote></details>

`IsPaused` is legacy. I would remove it here, but it looks like we're using it for replica pausing, so I made it return the same value as before.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @nvanbenschoten, and @pav-kv)

___
*[`pkg/raft/raft.go` line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Ny0kgI68AMjgB4RQqCu:-Ny0kgI79vb6bGZsRYqn:b-qm3apb) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L555)):*
> ```Go
> // log has been compacted) it can send a MsgSnap.
> //
> // In some cases, the MsgApp message can have zero entries, and yet being sent.
> ```

nit: ... yet be sent
___
*[`pkg/raft/raft.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Ny0l-s-3V-KnGfJQh4f:-Ny0l-s-3V-KnGfJQh4g:b-xuxs5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L557)):*
> ```Go
> // In some cases, the MsgApp message can have zero entries, and yet being sent.
> // When the follower log is not fully up-to-date, we must send a MsgApp
> // periodically so that eventually the flow is either accepted or rejected. Not
> ```

basic question: is this the built-in retrying inside raft to account for a lossy network?
___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-Ny0lcaOA6NctPhd4s2R:b9no2az) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
> where a raft group is not performing any heartbeats

Adding to this, in the future, if the higher layer has only asked for indices up to `i` for a peer, so the raft leader knows that only `...,i]` has been sent, and that peer has acked, so `Match == i`, there will be no retrying of `MsgApp` by raft, yes?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/raft/raft.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Ny0l-s-3V-KnGfJQh4f:-Ny1YaYg7c17MWHZjrrL:b-hm6czp) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L557)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

basic question: is this the built-in retrying inside raft to account for a lossy network?
</blockquote></details>

Yes. If there are any unacked entries, raft will optimistically send some, and then periodically send an empty MsgApp (roughly once per heartbeat interval currently). Eventually, it will get a response, adjust the flow state, and continue the loop.
___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-Ny1Z6178TrtbdmPJjk4:bz1yyhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> where a raft group is not performing any heartbeats

Adding to this, in the future, if the higher layer has only asked for indices up to `i` for a peer, so the raft leader knows that only `...,i]` has been sent, and that peer has acked, so `Match == i`, there will be no retrying of `MsgApp` by raft, yes?
</blockquote></details>

There will be no retrying of entries <= `Match`.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @nvanbenschoten, and @pav-kv)

___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-Ny2Bzvj25Mrdh6FFPdJ:b-w175a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

There will be no retrying of entries <= `Match`.
</blockquote></details>

My question phrasing was not great. I realize there isn't a need to resend entries <= Match, by definition of Match, but what I meant to ask is that since the higher layer has only asked up to `i`, the retrying logic will ignore the indices > `i`.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/raft/raft.go` line 1461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-Nxna2Ar5bwkexvhCAVX:-Ny5QbtM2KcTBYgpgypA:b-azlzb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/raft.go#L1461)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

My question phrasing was not great. I realize there isn't a need to resend entries <= Match, by definition of Match, but what I meant to ask is that since the higher layer has only asked up to `i`, the retrying logic will ignore the indices > `i`.
</blockquote></details>

Discussed offline. The `MsgApp` "retries" will not include any entries if we are in `StateReplicate`. These messages will have `Entries = nil` appended after `{index = Next-1, term = log.term(Next-1)}`.
___
*[`pkg/raft/tracker/progress.go` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnWPfeEOlvVEd1ktNs:-NyzRPdz-DgQxctN1blD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L182)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Yes, will add commit https://github.com/etcd-io/raft/pull/134/commits/91981c3f884a25f342795de031ee734974ca71be to this PR soon.
</blockquote></details>

Done
___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-NyzQRbS0AcxCahiGEl2:bcufs40) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

`IsPaused` is legacy. I would remove it here, but it looks like we're using it for replica pausing, so I made it return the same value as before.
</blockquote></details>

I made the relationship more clear: `ShouldSendMsgApp` now depends on `IsPaused`. PTAL.

**Comment by pav-kv** [comment]
@nvanbenschoten @sumeerbhola Addressed your comments. PTAL.

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 8 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @pav-kv, and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-NyzVozmCUVqWOeRp-8w:b-yd4t4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

I made the relationship more clear: `ShouldSendMsgApp` now depends on `IsPaused`. PTAL.
</blockquote></details>

I'm not sure that this is an improvement. We're still referencing `MsgAppFlowPaused` is two places and now we're inlining `CanSendEntries` as the `pr.Next <= last`.

Could this have been expressed as (with some of the improved commentary):
```go
return pr.CanBumpCommit(commit) ||
        pr.Match < last && (!pr.IsPaused() || pr.CanSendEntries(last))
```
___
*[`pkg/raft/tracker/progress.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NyzZQn9AhfGGuD_osOz:-NyzZQn9AhfGGuD_osP-:b9s2jqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b3ab554f5a85521000b1f93a56d320a8939723c/pkg/raft/tracker/progress.go#L100)):*
> or StateReplicate with saturated Inflights

Is this still true?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-NyzuYzc6ZXhom36VjD_:b13ztsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure that this is an improvement. We're still referencing `MsgAppFlowPaused` is two places and now we're inlining `CanSendEntries` as the `pr.Next <= last`.

Could this have been expressed as (with some of the improved commentary):
```go
return pr.CanBumpCommit(commit) ||
        pr.Match < last && (!pr.IsPaused() || pr.CanSendEntries(last))
```
</blockquote></details>

The expression you proposed not work (some tests fail). What works is the below (does it look clean?):

```golang
return pr.CanSendEntries(last) ||
	pr.CanBumpCommit(commit) ||
	pr.Match < last && !pr.MsgAppProbesPaused // need an empty "probe" MsgApp sometimes
```

But it doesn't depend on `IsPaused` again. This is really subtle, and I don't know a good way to not use `MsgAppProbesPaused` here.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NyzZQn9AhfGGuD_osOz:-Nz-5IwVCz6GNn7EihjA:bzgpe5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b3ab554f5a85521000b1f93a56d320a8939723c/pkg/raft/tracker/progress.go#L100)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> or StateReplicate with saturated Inflights

Is this still true?
</blockquote></details>

I think it is, see `ShouldSendMsgApp`. More precisely, the cases when this flag matters are:

1. `StateProbe` - throttle probes.
2. `StateReplicate` with `Inflights.Full()` - throttle empty `MsgApp`s.
3. `StateReplicate` with `Match < lastIndex && Next == lastIndex + 1` ("everything is in flight"). In this case we throttle the empty `MsgApps` too, until we're sure everything is replicated.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r7, 2 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-:-Nz-i9Kc0B7XW9jZ1xqA:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @pav-kv, and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-Nz-ghLf-nFxRWFT_9Bn:btotseq) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

The expression you proposed not work (some tests fail). What works is the below (does it look clean?):

```golang
return pr.CanSendEntries(last) ||
	pr.CanBumpCommit(commit) ||
	pr.Match < last && !pr.MsgAppProbesPaused // need an empty "probe" MsgApp sometimes
```

But it doesn't depend on `IsPaused` again. This is really subtle, and I don't know a good way to not use `MsgAppProbesPaused` here.
</blockquote></details>

This is cleaner to me, as it groups together real MsgApps, probe MsgApps, and commit-only MsgApps. Thanks for reworking it a few times.

The only nit I have (which you can ignore or address separately) is that you could extract `pr.Match < last && !pr.MsgAppFlowPaused` into a `Progress.ShouldSendProbe` method to package up that condition and centralize the commentary around it.
___
*[`pkg/raft/tracker/progress.go` line 100 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NyzZQn9AhfGGuD_osOz:-Nz-i13YBQLUtlSDfBNH:brg9hyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b3ab554f5a85521000b1f93a56d320a8939723c/pkg/raft/tracker/progress.go#L100)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

I think it is, see `ShouldSendMsgApp`. More precisely, the cases when this flag matters are:

1. `StateProbe` - throttle probes.
2. `StateReplicate` with `Inflights.Full()` - throttle empty `MsgApp`s.
3. `StateReplicate` with `Match < lastIndex && Next == lastIndex + 1` ("everything is in flight"). In this case we throttle the empty `MsgApps` too, until we're sure everything is replicated.
</blockquote></details>

Yeah I see, I had misread this as "is set to true" instead of "is used". The comment seems fine.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @nvanbenschoten, and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-Nz-s50O2nFaJqjk6b6k:b-ok8kz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is cleaner to me, as it groups together real MsgApps, probe MsgApps, and commit-only MsgApps. Thanks for reworking it a few times.

The only nit I have (which you can ignore or address separately) is that you could extract `pr.Match < last && !pr.MsgAppFlowPaused` into a `Progress.ShouldSendProbe` method to package up that condition and centralize the commentary around it.
</blockquote></details>

I'm thinking that maybe it would be better to return some enum or struct encapsulating what can be done, instead of having multiple semi-related `Progress` methods that have to be called in a certain order.

In `maybeSendAppend`, we call `ShouldSendMsgApp`, and then call `CanSendEntries` to determine (again, despite `ShouldSendMsgApp` has already done it) whether some entries can be attached. These can be tied together.

Similarly, the `Progress.ShouldSendProbe` method you described only makes sense in a context, after having ruled out the possibility of a "real" `MsgApp`.

I'll think about it a bit more, and may clean this up further in future PRs when this gets closer to the outer API.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124006)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @sumeerbhola)

___
*[`pkg/raft/tracker/progress.go` line 299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124006#-NxnZNnQ1e6hwxwQpRI1:-Nz0OdFY1744JgAxpBOt:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/95e61b37c58cccfd68ff565a78236a3be660f30a/pkg/raft/tracker/progress.go#L299)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

I'm thinking that maybe it would be better to return some enum or struct encapsulating what can be done, instead of having multiple semi-related `Progress` methods that have to be called in a certain order.

In `maybeSendAppend`, we call `ShouldSendMsgApp`, and then call `CanSendEntries` to determine (again, despite `ShouldSendMsgApp` has already done it) whether some entries can be attached. These can be tied together.

Similarly, the `Progress.ShouldSendProbe` method you described only makes sense in a context, after having ruled out the possibility of a "real" `MsgApp`.

I'll think about it a bit more, and may clean this up further in future PRs when this gets closer to the outer API.
</blockquote></details>

:thumbsup:

**Comment by pav-kv** [comment]
TFTRs!

bors r=nvanbenschoten

@arulajmani Feel free to add comments async, I will be iterating on this further and add you to future PR reviews.

**Pull request merged**
