### PR TITLE
opt,sql: run eval tests through optimizer

### PR DESCRIPTION
**Pull request by justinj**
We have all these scalar tests, might as well run them through the
optimizer to make sure it's representing them faithfully.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29066#-:-LL5Amxw4zOdGzI1bzoQ:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/eval_test.go, line 1451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29066#-LL5AQDkAPsyMTKDktKP:-LL5AQDkAPsyMTKDktKQ:b500v1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/50086c4206160f818ee193edfa2f5c91ee32030d/pkg/sql/sem/tree/eval_test.go#L1451)):*
> ```Go
> 	var o xform.Optimizer
> 	o.Init(evalCtx)
> 	o.DisableOptimizations()
> ```

Why are you disabling optimizations? Does it fail if they are turned on?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/eval_test.go, line 1451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29066#-LL5AQDkAPsyMTKDktKP:-LL5BD1dBltg0hSGNI2N:b-mgu7em) ([raw file](https://github.com/cockroachdb/cockroach/blob/50086c4206160f818ee193edfa2f5c91ee32030d/pkg/sql/sem/tree/eval_test.go#L1451)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why are you disabling optimizations? Does it fail if they are turned on?
</blockquote></details>

No reason, I copied this from the optbuilder tests. I turned them back on and they still pass so I'll leave it that way.

**Comment by justinj** [comment]
TFTRs!

bors r+

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/eval_test.go, line 1451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29066#-LL5AQDkAPsyMTKDktKP:-LL5CY7TEaRllBOhB55R:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/50086c4206160f818ee193edfa2f5c91ee32030d/pkg/sql/sem/tree/eval_test.go#L1451)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

No reason, I copied this from the optbuilder tests. I turned them back on and they still pass so I'll leave it that way.
</blockquote></details>

:thumbsup:

**Comment by knz** [comment]
please consider backporting this as this will be good to continue excercising the opt code in the 2.1 lifecycle

**Pull request merged**
