### PR TITLE
Make cli sql output prettier.

### PR DESCRIPTION
**Pull request by mberhault**
Use github.com/olekukonko/tablewriter rather than tabwriter,
it does tables just the way we want them.

Before:

``` sql
> select * from system.namespace
parentIDname    id
0 system    1
1 descriptor  3
1 namespace 2
```

After:

``` sql
> select * from system.namespace
+----------+------------+----+
| PARENTID |    NAME    | ID |
+----------+------------+----+
| 0        | system     | 1  |
| 1        | descriptor | 3  |
| 1        | namespace  | 2  |
+----------+------------+----+
```

### CODE REVIEW

**Comment by BramGruneir** [comment]
This looks great.  But can you add a test to make sure the output matches what we expect?

**Comment by tamird** [comment]
LGTM. :-1: on the test because that's testing a dependency.

**Comment by petermattis** [comment]
LGTM. Now I feel like we're really implementing SQL.

**Comment by BramGruneir** [comment]
Yes, we are testing a dependency, which is why it should be simple, but we should make sure it doesn't change out from under us.

**Comment by MBerhault** [comment]
@BramGruneir: ditto. we really need tests for all cli stuff (I've had #2008 against me for a while). I may do basic table stuff in there, but I'd rather avoid that entirely. As for changes, we control the revision.

**Comment by BramGruneir** [comment]
As long as we'll have some tests on the output somewhere, that works for me.

**Comment by mrtracy** [comment]
Agreed, it's going to be difficult to update that dependency with confidence unless we have some sort of test here.

**Comment by tamird** [comment]
@MBerhault I lied to you! It's `make storedeps`

**Comment by MBerhault** [comment]
Oops. forgot to squash. Oh well.

**Pull request merged**
