### PR TITLE
Try out increased block_size, it should help reduce memory usage for …

### PR DESCRIPTION
**Pull request by mberhault**
…readers

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7219)

### CODE REVIEW

**Comment by bdarnell** [comment]
How does increasing block_size increase write amplification? It's not mentioned on https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide and from my experience with bigtable the tradeoff was that higher block sizes were more space and memory efficient but performed worse on uncached reads. (Tuning this on a per-table basis was important for us. We need a global value for now but should think about how to provide this flexibility in the future). Maybe we should make this an environment variable for now so we can experiment with different values.

**Comment by mberhault** [comment]
ugh! I thought I corrected that typo. s/write/read/. It's not even in my uncommitted changes, so apparently I made the typo twice. great.

I can change it to an env variable, although I'm not sure we'll be playing with those any time soon.

**Comment by bdarnell** [comment]
LGTM

**Comment by mberhault** [comment]
added `COCKROACH_ROCKSDB_BLOCK_SIZE` (defined as a size). I'm still setting the default value at 32KiB (vs rocksdb's default of 4KiB)

**Pull request merged**
