### PR TITLE
Sql: upgrade connection count to use atomics

### PR DESCRIPTION
**Pull request by lyang24**
`max_connections_per_gateway` is a nice feature but it would be better performance wise to maintain a counter using atomics vs mutex.

inspired by looking at this pr https://github.com/cockroachdb/cockroach/pull/76401

linking issue https://github.com/cockroachdb/cockroach/issues/95403

**Epic: None
Release note: None**

### CODE REVIEW

**Comment by lyang24** [comment]
Hi @ecwall @mgartner, can you please share some feedbacks on this pr?

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for your contribution! there is one issue that should be addressed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-:-NM6w93S-wxqmu-wQ4tm:br4w2v0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @lyang24)

___
*[`pkg/sql/conn_executor.go` line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-NM6vDNg4Rqux9BtEgUG:-NM6vDNg4Rqux9BtEgUH:b-sbqsae) ([raw file](https://github.com/cockroachdb/cockroach/blob/15115e736002455cd7e9a6fc16c4ef84467cc6e4/pkg/sql/conn_executor.go#L762)):*
> ```Go
> // otherwise it does nothing and returns false.
> func (s *Server) IncrementConnectionCountIfLessThan(max int64) bool {
> 	lt := atomic.LoadInt64(&s.connectionCount) < max
> ```

previously, the whole function was atomic, but now it's not. a different goroutine may increment the connection count after this line, which would then cause the count to go up more then it should.

**Comment by lyang24** [comment]
> thanks for your contribution! there is one issue that should be addressed.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-:-NM6w93S-wxqmu-wQ4tm:br4w2v0)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @lyang24)
> 
> _[`pkg/sql/conn_executor.go` line 762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-NM6vDNg4Rqux9BtEgUG:-NM6vDNg4Rqux9BtEgUH:b-sbqsae) ([raw file](https://github.com/cockroachdb/cockroach/blob/15115e736002455cd7e9a6fc16c4ef84467cc6e4/pkg/sql/conn_executor.go#L762)):_
> 
> > ```go
> > // otherwise it does nothing and returns false.
> > func (s *Server) IncrementConnectionCountIfLessThan(max int64) bool {
> > 	lt := atomic.LoadInt64(&s.connectionCount) < max
> > ```
> 
> previously, the whole function was atomic, but now it's not. a different goroutine may increment the connection count after this line, which would then cause the count to go up more then it should.

great catch thanks! I implemented compare and swap here. please let me know what do your thoughts. if its too much i am also happy with using a mutex here.

**Comment by lyang24** [comment]
Hi @rafiss, do you mind take another look at the fixes?

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for the work here. i have one more request: for us to be sure that this influences performance meaningfully and positively, could you write a benchmark test?

you can add it to `pkg/sql/conn_executor_test.go` with a function named `func BenchmarkConnectionCount`. the benchmark should do a test with a single goroutine, and ideally another one with multiple concurrent goroutines (though this might be harder to write correctly).

if there's no substantial difference, it would be better to keep the mutex. one reason is that if the mutex is locked and causing latency, that can show up in a thread dump, but with a spinlock, it's harder to know if it has been spinning for a long time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-:-NMFXGwhE8TalAldBo6W:b-oiet3i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lyang24)

___
*[`pkg/sql/conn_executor.go` line 320 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95402#-NMFXAsCCPPisaGCuoMd:-NMFXAsCCPPisaGCuoMe:b-sgem90) ([raw file](https://github.com/cockroachdb/cockroach/blob/34ca1c0524e6be7ea20c59bc05f2922e38be43f8/pkg/sql/conn_executor.go#L320)):*
> ```Go
> 	idxRecommendationsCache *idxrecommendations.IndexRecCache
> 
> 	connectionCount int64
> ```

nit: could you name this `atomicConnectionCount`, so it's more clear that it should always be accessed using `atomic`?

**Comment by lyang24** [comment]
> no substantial

@rafiss great point on the easiness of debugging! i ran some test it suggest there are tiny bits of performance improvement probably will not justify this change. i am going to close this pr.
```
func BenchmarkConnectionCnt(t *testing.B) {
	s, _, _ := serverutils.StartServer(t, base.TestServerArgs{
		Insecure: true,
	})
	sqlServer := s.SQLServer().(*sql.Server)
	defer s.Stopper().Stop(ctx)
	var wg sync.WaitGroup

	for i := 0; i < 50; i++ {
		wg.Add(1)

		go func() {
			for c := 0; c < 1000; c++ {
				sqlServer.IncrementConnectionCountIfLessThan(3500)
			} 
			wg.Done()
		}()

		wg.Wait()
		println(sqlServer.GetConnectionCount())
	}
}
```
[current branch]
W230120 23:04:15.947200 17131 jobs/registry.go:1007  [T1,n1] 2272  canceling all adopted jobs due to stopper quiescing
W230120 23:04:15.947210 17469 kv/kvserver/intentresolver/intent_resolver.go:799  [T1] 2273  failed to gc transaction record: could not GC completed transaction anchored at /Table/3/1/100/2/1: node unavailable; try another peer
W230120 23:04:15.947235 17106 sql/sqlliveness/slinstance/slinstance.go:312  [T1,n1] 2274  exiting heartbeat loop
W230120 23:04:15.947253 17106 sql/sqlliveness/slinstance/slinstance.go:297  [T1,n1] 2276  exiting heartbeat loop
I230120 23:04:15.947227 17125 sql/stats/automatic_stats.go:508  [T1,n1] 2275  quiescing auto stats refresher
I230120 23:04:15.947396 17394 jobs/registry.go:1427  [T1,n1] 2277  AUTO SPAN CONFIG RECONCILIATION job 832914901356183553: stepping through state succeeded
E230120 23:04:15.947593 17394 jobs/registry.go:879  [T1,n1] 2278  error getting live session: node unavailable; try another peer
BenchmarkConnectionCnt-16    	1000000000	         **0.3218** ns/op
PASS

[master]
W230120 23:07:34.640291 18470 kv/kvserver/intentresolver/intent_resolver.go:799  [T1] 2387  failed to gc transaction record: could not GC completed transaction anchored at /Table/3/1/100/2/1: node unavailable; try another peer
I230120 23:07:34.640410 18332 sql/stats/automatic_stats.go:508  [T1,n1] 2388  quiescing auto stats refresher
W230120 23:07:34.640425 18209 sql/sqlliveness/slinstance/slinstance.go:312  [T1,n1] 2389  exiting heartbeat loop
W230120 23:07:34.640444 18209 sql/sqlliveness/slinstance/slinstance.go:297  [T1,n1] 2390  exiting heartbeat loop
W230120 23:07:34.640538 18389 jobs/registry.go:1007  [T1,n1] 2391  canceling all adopted jobs due to stopper quiescing
I230120 23:07:34.640575 18427 jobs/registry.go:1427  [T1,n1] 2392  AUTO SPAN CONFIG RECONCILIATION job 832915552718880769: stepping through state succeeded
E230120 23:07:34.640665 18427 jobs/registry.go:879  [T1,n1] 2393  error getting live session: node unavailable; try another peer
BenchmarkConnectionCnt-16    	1000000000	         **0.3405** ns/op

**Pull request closed without merging**
