### PR TITLE
jobs: add SHOW JOB command

### PR DESCRIPTION
**Pull request by spaskob**

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @spaskob)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlcojYODb2i4onYkJhE:-LlcojYODb2i4onYkJhF:b-s94tc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/94de5ce195729d70263304863ad8c744b82bc7e2/docs/generated/sql/bnf/stmt_block.bnf#L490)):*
> ```
> show_jobs_stmt ::=
> 	'SHOW' opt_automatic 'JOBS'
> 	| 'SHOW' 'JOB' iconst64
> ```

This should be an `a_expr` not iconst64.
See the logic of CANCEL QUERY for an example.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlcojYODb2i4onYkJhE:-LlgR8w39OzJ3lZKuH0J:blhfvq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/94de5ce195729d70263304863ad8c744b82bc7e2/docs/generated/sql/bnf/stmt_block.bnf#L490)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This should be an `a_expr` not iconst64.
See the logic of CANCEL QUERY for an example.
</blockquote></details>

Perhaps you are confused by the first commit where I only introduce only iconst64, this is later extended to a_expr in https://github.com/cockroachdb/cockroach/pull/39324/commits/eddc19a255d20c731af6b4a1239f2553720e250c

**Review by knz — COMMENTED** [review]
yes I was confused. Thank you.

Now just a minor fix and this is good to go.

> Reviewed 3 of 3 files at r2, 6 of 8 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-:-LlgU9LSBdsw2UOgikNC:brfo1t8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/sql/show_test.go, line 1043 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlgTpVh7LlZ8RLeru1P:-LlgTpViCdD_-kMOAJw3:b-py0kmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eddc19a255d20c731af6b4a1239f2553720e250c/pkg/sql/show_test.go#L1043)):*
> ```Go
> 	var out row
> 
> 	sqlDB.QueryRow(t, `SELECT job_id, job_type FROM [SHOW JOB 1]`).Scan(&out.id, &out.typ)
> ```

Please verify also that `SHOW JOB (SELECT 1)` works. (Note: `show job (select 1)` is syntactically unrelated to `show jobs select 1`. Both should be valid)

(If in doubt you can also manually verify that `show job 1+(select 0)` works but you don't need to write a test for that).
___
*[pkg/sql/sem/tree/show.go, line 209 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlgTb8l8A9KdsiBQdpO:-LlgTb8l8A9KdsiBQdpP:b9b92hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eddc19a255d20c731af6b4a1239f2553720e250c/pkg/sql/sem/tree/show.go#L209)):*
> ```Go
> 	if node.Jobs != nil {
> 		ctx.WriteString(" ")
> 		ctx.WriteString(node.Jobs.String())
> ```

`ctx.FormatNode(node.Jobs)`

**Review by spaskob — COMMENTED** [review]
> show job 1+(select 0)
Any tips on how to structure PRs better in order to avoid future confusions?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-:-Llh9m5hCLvi7TVyldlG:b-nmdyqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/sql/show_test.go, line 1043 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlgTpVh7LlZ8RLeru1P:-LlhALmm8LM0KrXPBgjv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eddc19a255d20c731af6b4a1239f2553720e250c/pkg/sql/show_test.go#L1043)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please verify also that `SHOW JOB (SELECT 1)` works. (Note: `show job (select 1)` is syntactically unrelated to `show jobs select 1`. Both should be valid)

(If in doubt you can also manually verify that `show job 1+(select 0)` works but you don't need to write a test for that).
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/show.go, line 209 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39324#-LlgTb8l8A9KdsiBQdpO:-LlhAyG42sU-CbUTq7c3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eddc19a255d20c731af6b4a1239f2553720e250c/pkg/sql/sem/tree/show.go#L209)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`ctx.FormatNode(node.Jobs)`
</blockquote></details>

Done.

**Comment by knz** [comment]
>  Any tips on how to structure PRs better in order to avoid future confusions?

The confusion is entirely mine. My apologies. You couldn't have done better.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
