### PR TITLE
settings: rename kv.raft_log.synchronize to kv.raft_log.disable_synchronization_unsafe

### LINKED ISSUE #33132: storage: kv.raft_log.synchronize is for internal testing only
See: https://github.com/cockroachlabs/support/issues/244#event-2024374098

Based on discussions with @bdarnell and @petermattis, users should never use change the `kv.raft_log.synchronize` to `false`. The consensus is that we should either remove this cluster setting or rename it to include `_unsafe`. @petermattis mentioned that the setting is useful for internal testing, so renaming might be better. 

Also, if there's a way to exclude the setting from the auto-generated cluster setting docs, similar to the `SKIP DOC` function for sql diagrams`, that would be great.

### PR DESCRIPTION
**Pull request by nvb**
Closes #33132.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Is there a migration concern here?

**Comment by nvanbenschoten** [comment]
Absolutely - I'm not sure if you looked at the code or not though. There's logic in there to handle it.

**Review by tbg — APPROVED** [review]
Oh, apologies. Hadn't skimmed this well enough.

LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33426#-:-LVDMSDSEb7MVIODBtxw:bs6kfsl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

I'll wait for the sign-off from @bdarnell and @jseldess before merging.

**Review by bdarnell — APPROVED** [review]
:lgtm: 

I think I'd be OK without any backwards-compatibility for the old name of this setting, since it is only for non-production usage anyway. 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33426#-:-LVES9W1ERSVwrnjl2EP:bivn8t6)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> I think I'd be OK without any backwards-compatibility for the old name of this setting, since it is only for non-production usage anyway.

Done. That simplifies things.

**Comment by jseldess** [comment]
LGTM, too. Thanks, Nathan.

**Pull request merged**
