### PR TITLE
*: upgrade to go 1.19.1

### LINKED ISSUE #85908: build: upgrade to go 1.19
We'd like to try out go 1.19 for the stability period of v22.2.

It's easier to try it out now, and later revert back to 1.18, than to try and push 1.19 later.

See [slack thread here](https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1660127675822459).

Jira issue: CRDB-18486

### PR DESCRIPTION
**Pull request by rickystewart**
* [ ] Adjust the Pebble tests to run in new version.
* [x] Adjust version in Docker image ([source](./builder/Dockerfile)).
* [x] Adjust version in the TeamCity agent image ([setup script](./packer/teamcity-agent.sh))
* [x] Rebuild and push the Docker image (following [Basic Process](#basic-process))
* [x] Run the `Internal / Release / Build and Publish Patched Go` build configuration in TeamCity with your latest version of the script above. This will print out the new URL's and SHA256 sums for the patched Go that you built above.
* [x] Update `build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` with the new version and adjust SHA256 sums as necessary.
* [x] Bump the version in `WORKSPACE` under `go_download_sdk`. You may need to bump [rules_go](https://github.com/bazelbuild/rules_go/releases). Also edit the filenames listed in `sdks` and update all the hashes to match what you built in the step above.
* [x] Run `./dev generate bazel` to refresh `distdir_files.bzl`, then `bazel fetch @distdir//:archives` to ensure you've updated all hashes to the correct value.
* [x] Bump the version in `builder.sh` accordingly ([source](./builder.sh#L6)).
* [x] Bump the version in `go-version-check.sh` ([source](./go-version-check.sh)), unless bumping to a new patch release.
* [ ] Bump the go version in `go.mod`. You may also need to rerun `make vendor_rebuild` if vendoring has changed.
* [x] Bump the default installed version of Go in `bootstrap-debian.sh` ([source](./bootstrap/bootstrap-debian.sh)).
* [x] Replace other mentions of the older version of go (grep for `golang:<old_version>` and `go<old_version>`).
* [ ] Update the `builder.dockerImage` parameter in the TeamCity [`Cockroach`](https://teamcity.cockroachdb.com/admin/editProject.html?projectId=Cockroach&tab=projectParams) and [`Internal`](https://teamcity.cockroachdb.com/admin/editProject.html?projectId=Internal&tab=projectParams) projects.
* [ ] Ask the Developer Infrastructure team to deploy new TeamCity agent images according to [packer/README.md](./packer/README.md)

Closes #85908.

Release justification: Upgrade to latest Go version
Release note (build change): upgrade to go 1.19.1

### CODE REVIEW

**Comment by rickystewart** [comment]
`gofmt` has new behavior in 1.19 where doc comments are formatted, leading to the very big diff.

This breaks `go-swagger` which we depend on for some generated documentation: https://github.com/go-swagger/go-swagger/issues/2759

**Comment by ajwerner** [comment]
> gofmt has new behavior in 1.19 where doc comments are formatted, leading to the very big diff.

Where we do have to use it? Do we have to use go1.19's `gofmt`? Given we're leaving go.mod at 1.17, I don't think we have to worry about older gofmt not working.

**Comment by rickystewart** [comment]
> Do we have to use go1.19's gofmt? Given we're leaving go.mod at 1.17, I don't think we have to worry about older gofmt not working.

`gofmt` is part of the Go distribution (when you get a new `go`, you automatically get a new `gofmt`) so just using a different one is easier said than done. We could conceivably use patched versions of the Go archives and just keep the 1.18 version of `gofmt` in our custom SDK's, but that's a bit of a high-friction fix and I think `go-swagger` will have a fix upstream relatively quickly.

Either way when developers upgrade their local `go` versions, they're going to get `gofmt` 1.19, and I don't think it's in our best interest if the latest `gofmt` disagrees with what CI wants the formatting to be.

**Comment by knz** [comment]
> I think go-swagger will have a fix upstream relatively quickly.

If we expect this to be available before 22.2 gets released, then I'd say let's temporarily disable the doc generation and re-enable it when the upstream fix is there.

(It's even likely 'that our APIs won't change until then, so we're not going to get doc drift even if we release 22.2 with the generator inactive)

**Comment by ajwerner** [comment]
> Either way when developers upgrade their local go versions, they're going to get gofmt 1.19, and I don't think it's in our best interest if the latest gofmt disagrees with what CI wants the formatting to be.

The thing that I find weird about that is that we all use `crlfmt` and if we don't CI will complain. As it stands, `gofmt` disagrees with what CI wants the formatting to be, no?

**Comment by rickystewart** [comment]
> If we expect this to be available before 22.2 gets released, then I'd say let's temporarily disable the doc generation and re-enable it when the upstream fix is there.

I'll have a look at that.

> The thing that I find weird about that is that we all use crlfmt and if we don't CI will complain. As it stands, gofmt disagrees with what CI wants the formatting to be, no?

Hmm. To my knowledge, running `crlfmt` has never been sufficient to ensure you don't fail any lint checks in CI. We run *both* `crlfmt` and `gofmt -s` during lints and expect both to come back clean (`TestCrlfmt`, `TestGofmtSimplify`).

**Comment by rodrigc** [comment]
I ran into this issue in my own code and asked about it here: https://groups.google.com/g/golang-nuts/c/sY7QFzfSMT4

**Comment by knz** [comment]
@yuzefovich could you have a look at the following lint failure after go 1.19 upgrade:
```
------- Stdout: -------
=== RUN   TestLint/TestGCAssert
=== PAUSE TestLint/TestGCAssert
=== CONT  TestLint/TestGCAssert
=== CONT  TestLint/TestGCAssert
    lint_test.go:2038: failed gcassert:
        ../../sql/colexec/hash_aggregator.eg.go:224:  idx := sel[i]: Found IsInBounds
        ../../sql/colexec/hash_aggregator.eg.go:256:  if op.distinctOutput[i] {
          {
            __retval_0 = true
            __retval_1 = i
          }
          goto findSplit_false_true_return_1
        }: Found IsInBounds
        ../../sql/colexec/hash_aggregator.eg.go:358:  idx := sel[i]: Found IsInBounds
        ../../sql/colexec/hash_aggregator.eg.go:390:  if op.distinctOutput[i] {
          {
            __retval_0 = true
            __retval_1 = i
          }
          goto findSplit_false_false_return_3
        }: Found IsInBounds
    --- FAIL: TestLint/TestGCAssert (24.64s)
```

**Comment by knz** [comment]
@rickystewart would you like help working through the SA1019 failures about ioutil? The change is mechanical and I can imagine it's a bit of a chore, but i know my ways around with perl

**Comment by knz** [comment]
The failure in TestExecBuild_hash_sharded_index
just needs a rewrite in the expected test result. It's innocuous.

**Comment by knz** [comment]
Ditto TestRulesYAML: the new yaml code sorts the fields differently I think?
(Let's check with `stress` that the output is deterministic at least)

**Comment by knz** [comment]
The failure in TestPrereqs has to do with an ignored file. I'm not sure it's important?

**Comment by yuzefovich** [comment]
> @yuzefovich could you have a look at the following lint failure after go 1.19 upgrade:

Seems like heuristics for bounds checks elimination have changed (since the generated code hasn't), so let's just remove some BCE assertions:
```
diff --git a/pkg/sql/colexec/hash_aggregator_tmpl.go b/pkg/sql/colexec/hash_aggregator_tmpl.go
index 62ac93b21d..8f97fef163 100644
--- a/pkg/sql/colexec/hash_aggregator_tmpl.go
+++ b/pkg/sql/colexec/hash_aggregator_tmpl.go
@@ -128,17 +128,13 @@ func (op *hashAggregator) populateEqChains(
 func findSplit(
        op *hashAggregator, start int, end int, sel []int, useSel bool, ascending bool,
 ) (bool, int) {
-       if useSel {
-               _ = sel[start]
-               _ = sel[end]
-       } else {
+       if !useSel {
                _ = op.distinctOutput[start]
                _ = op.distinctOutput[end]
        }
        if ascending {
                for i := start; i <= end; i++ {
                        if useSel {
-                               //gcassert:bce
                                idx := sel[i]
                                if op.distinctOutput[idx] {
                                        return true, i
@@ -153,7 +149,6 @@ func findSplit(
        } else {
                for i := start; i >= end; i-- {
                        if useSel {
-                               //gcassert:bce
                                idx := sel[i]
                                if op.distinctOutput[idx] {
                                        return true, i
```

**Comment by rodrigc** [comment]
@rickystewart in the go-swagger project, @casualjim is working on go1.19 fixes in this branch: https://github.com/go-swagger/go-swagger/pull/2808

I'm not familiar with the build system for cockroachdb.  Can you enumerate the minimum commands needed to just run the necessary commands to generate docs with go-swagger in this branch?

I can help test

**Comment by knz** [comment]
how can i help bring this over the finish line?

**Comment by rickystewart** [comment]
> how can i help bring this over the finish line?

Let me rebase and check on the remaining failures to see what else needs to be fixed here.

I will say that the conflict in `pkg/server/api_v2_sql_schema.go` (from `24b998c2645d1fd059ec5c60822ebbc69a464d55`) decreases my confidence that we can turn off generation for the swagger docs, since this is evidently not as stable as suggested.

**Comment by knz** [comment]
> I will say that the conflict in pkg/server/api_v2_sql_schema.go (from 24b998c2645d1fd059ec5c60822ebbc69a464d55) decreases my confidence that we can turn off generation for the swagger docs, since this is evidently not as stable as suggested.

We can let it drift for now, then do a manual generation when the time comes to publish our 22.2 docs if the upstream swagger has not been fixed yet.

**Comment by rickystewart** [comment]
I'm seeing this in an `acceptance` test:

```
 dockercluster.go:687: unexpected extra event &{0 die} (after [])
```

This is a failure with a [storied history](https://github.com/cockroachdb/cockroach/issues/58955). Maybe Go 1.19 doesn't play with the Docker Go library we have vendored? Or maybe this is just still buggy, but with the older Go runtimes we haven't been able to observe the bug.

`pkg/sql/schemachanger/scplan/internal/rules` is also failing, it looks like it's another thing to do with indentation, I'll have a look.

Finally, the unused lint is failing, which I'm still debugging now.

**Comment by rickystewart** [comment]
Remaining problems:

1. I think the `acceptance` test is still broken as above.
2. `TestGCAssert` is broken -- I think whatever check this might have done is broken under Go 1.19? Not sure of the details here.
3. `io/ioutil` is deprecated which is producing a lot of lint failures now.  I'll check to see what we can do about this.

**Comment by rickystewart** [comment]
@jordanlewis Do you have any insight about the `TestGCAssert` failure [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6191843?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)?

**Comment by jordanlewis** [comment]
No, I would have to dig into that. Either Go 1.19 changed the output format that gcassert expects, or Go 1.19 changed the heuristics for inlining and bounds checks - it could be either.

**Comment by jordanlewis** [comment]
I created this to see if gcassert still passes its own tests in Go 1.19

**Comment by rickystewart** [comment]
@jordanlewis I'll disable the test for now. GCAssert checks are still disabled on the Bazel side (#65485), so we should figure something out if we want any coverage on these checks.

**Comment by JeffSwenson** [comment]
Here is a PR that cleans up most callers of ioutil https://github.com/cockroachdb/cockroach/pull/86687. I wrote a script for migrating Cockroach Cloud and ran it against the CRDB repository.

**Comment by mgartner** [comment]
> jordanlewis I'll disable the test for now. GCAssert checks are still disabled on the Bazel side (https://github.com/cockroachdb/cockroach/issues/65485), so we should figure something out if we want any coverage on these checks.

FYI I created #86714 to track re-enabling the `gcassert` linter.

**Comment by knz** [comment]
re acceptance tests
> this is just still buggy, but with the older Go runtimes we haven't been able to observe the bug.

I have investigated this and yes I believe this is true. Also I suspect I understand how to fix this. I'm running some tests now.

**Comment by knz** [comment]
Here you are: #86862

**Comment by knz** [comment]
looks like the remaining problems are all addressed now :)

**Comment by rickystewart** [comment]
> I'm not familiar with the build system for cockroachdb. Can you enumerate the minimum commands needed to just run the necessary commands to generate docs with go-swagger in this branch?

In the `swaggertesting` branch [here](https://github.com/rickystewart/cockroach/tree/swaggertesting) I have a commit `092dd7c0eae30a422ad7310b7bc40906f8c8cd39` that integrates the latest commit from that PR. The `swagger` build can be tested by pulling this branch and then `bazel build docs/generated/swagger --verbose_failures --sandbox_debug`, which still produces the following error:

```
operation (listSessions): yaml: line 7: could not find expected ':'
```

It's possible the `gofmt` I did on the `swagger` comments was incorrect and I need to massage it in some way, I'm not quite sure how though.

**Comment by casualjim** [comment]
I looked at the errors in the swagger generation.  A lot of them have to do with liberal whitespace usage.
The error you're running into 

```
operation (listSessions): yaml: line 7: could not find expected ':'
```

Is because of the description. if you strip away the comment markers you'd still end up with invalid yaml because the description text is split across 2 lines.

The next error you'd run into is the security bit because it lost a `-` .

The comments for listSessions that do work are:

```go
// swagger:operation GET /sessions/ listSessions
//
// # List sessions
//
// List all sessions on this cluster. If a username is provided, only
// sessions from that user are returned.
//
// Client must be logged-in as a user with admin privileges.
//
//	---
//	parameters:
//	  - name: username
//	    type: string
//	    in: query
//	    description: Username of user to return sessions for; if unspecified, sessions from all users are returned.
//	    required: false
//	  - name: exclude_closed_sessions
//	    type: bool
//	    in: query
//	    description: Boolean to exclude closed sessions; if unspecified, defaults to false and closed sessions are included in the response.
//	    required: false
//	  - name: limit
//	    type: integer
//	    in: query
//	    description: Maximum number of results to return in this call.
//	    required: false
//	  - name: start
//	    type: string
//	    in: query
//	    description: Continuation token for results after a past limited run.
//	    required: false
//	produces:
//	- application/json
//	security:
//	- api_session: []
//	responses:
//	  "200":
//	    description: List sessions response.
//	    schema:
//	    "$ref": "#/definitions/listSessionsResp"
```

I think it would be better to insert a tab character in those YAML sections of your comments before running go 1.19 gofmt that way it will cause less breakage

**Comment by rickystewart** [comment]
Unfortunately `gofmt` wants to make a lot of changes to `.eg.go` files (namely, additional lines with empty comments, like `//`) that `execgen` [reverts](https://github.com/cockroachdb/cockroach/blob/94058f364d2a627859b8a299cff256a78e07f043/pkg/sql/colexec/execgen/cmd/execgen/main.go#L147), and since the two disagree, this PR can't be merged as-is. We'll have to refine `execgen` so that it knows to let through empty comments in blocks of `//` comments.

**Comment by jordanlewis** [comment]
I believe execgen used to (still does?) run a pass of gofmt somewhere. We could add the call to gofmt at the end of execgen instead of in the middle if it is still happening. Beware it does slow down execgen considerably (IIRC? it has been a while).

cc @yuzefovich

**Comment by knz** [comment]
I know how to address the execgen issue. I'll send a PR.

**Comment by knz** [comment]
Here you are: #87401

**Comment by jordanlewis** [comment]
Oooh, thank you Raphael 🙇

**Comment by knz** [comment]
ok i think this is unblocked

**Comment by rickystewart** [comment]
Rebased, we'll see how this CI run goes.

**Comment by knz** [comment]
This is looking much better already.

For the remaining codegen fail, you can do `gofmt -w pkg/util/log/log_channels_generated.go` with the 1.19 gofmt.

(There's some backup/restore test failing, but this might be unrelated. By unblocking the 'workplace clean' check we can get more CI targets to run)

**Comment by rickystewart** [comment]
It looks like `gofmt` and `dev generate go` still disagree about `pkg/sql/colexec/and_or_projection.eg.go`. @knz Can you look into this?

**Comment by knz** [comment]
here you are #87442

**Comment by knz** [comment]
feel free to cherry pick btw

**Comment by rickystewart** [comment]
This is pretty close, can probably be merged soon.

@knz Looks like that file is still problematic even after the cherry-pick?

**Comment by rickystewart** [comment]
> Looks like that file is still problematic even after the cherry-pick?

Oh, maybe I messed up something with the rebase. I'm trying again now.

**Comment by knz** [comment]
You will probably need #87485 to get over the remaining linter hurdle.

Then for the remaining test failure you need to update the expected test output (I think it's `dev test //sql/opt/exec/execbuilder --rewrite`)

**Comment by rickystewart** [comment]
> You will probably need https://github.com/cockroachdb/cockroach/pull/87485 to get over the remaining linter hurdle.

I pulled the changes into this commit, except for the uses of `ioutil` I couldn't get rid of easily, for which I added linter exclusions.

AFAICT this is ready for review now.

**Comment by knz** [comment]
i can spend time on the detailed review but with focused chaos it will likely spread over 2-3 days.

**Comment by rickystewart** [comment]
> i can spend time on the detailed review but with focused chaos it will likely spread over 2-3 days.

I'll check if there's someone on the team who has time to review.

**Review by mari-crl — APPROVED** [review]
Sanity check completed!
A lot of ASCII art in our codebase... Some of it seems like it may have gotten misaligned, but I don't think that's a fix to be made here. Get it in there!

:lgtm: 

> Reviewed 766 of 789 files at r11, 24 of 24 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86049#-:-NBNsops0JjE6cg9Gs7a:bb71i4e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @msbutler, and @srosenberg)

**Comment by knz** [comment]
Btw 1.19.1 was just released with applicable security patches. IMHO it would be useful to have this done here right away.

**Comment by rickystewart** [comment]
TFTR

YOLO

bors r=mari-crl p=99

**Review by knz — APPROVED** [review]
I'm ok doing a post-hoc review on this.

> Reviewed 7 of 789 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86049#-:-NBNtVd_4NolAZa3H7Es:bbcefa4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @msbutler, and @srosenberg)

**Comment by rickystewart** [comment]
bors r=mari-crl,knz p=99

**Pull request merged**
