### PR TITLE
RFCs: propose a syntax for pausing/resuming/canceling operations

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/16273)

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/RFCS/pause_resume_cancel.md, line 92 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-Kl_2QMD5fGYAw4wZCSm:-Kl_2QMD5fGYAw4wZCSn:bges2r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c005d596c79172c1a809689c88bd9a82e636acfd/docs/RFCS/pause_resume_cancel.md#L92)):*
> ```Markdown
> 
> ```sql
> ALTER SYSTEM KILL SESSION <session-id>;
> ```

`ALTER JOB [PAUSE|RESUME|CANCEL]` seems more natural to me, though I'm not opposed to adding new top-level syntax.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273)*

**Comment by bdarnell** [comment]
:lgtm:

I'm fine with either the proposed syntax or Peter's `ALTER (QUERY|JOB) (CANCEL|PAUSE|RESUME)`

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/pause_resume_cancel.md, line 71 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-Kl_ZaBFPiwukEGmiOE9:-Kl_ZaBFPiwukEGmiOEA:b-lz9t2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c005d596c79172c1a809689c88bd9a82e636acfd/docs/RFCS/pause_resume_cancel.md#L71)):*
> ```Markdown
> rolls back all backfill progress.
> 
> ## Postgres syntax
> ```

Postgres additionally has support for cancellation built in to the wire protocol: send a special packet on a new TCP connection (bypassing all the regular authentication. in its place, you pass a token that the server sends at the start of each connection). 

I have no idea how common each mode of operation is in practice. My guess is that only very postgres-specific tools like `psql` use the protocol-based mode, and anything more generic would use the function. 

---

*[docs/RFCS/pause_resume_cancel.md, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-Kl__TrpQIf3u75VthcP:-Kl__TrpQIf3u75VthcQ:bxsnt1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c005d596c79172c1a809689c88bd9a82e636acfd/docs/RFCS/pause_resume_cancel.md#L84)):*
> ```Markdown
> seem like they *should* have new syntax.
> 
> Alas, we may eventually end up supporting this syntax for compatibility's sake.
> ```

What type did we end up using as our query ids? Integers or bytes/strings? We may only be able to support `pg_cancel_backend` if we use integer query ids. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-:-Kl_bMnprHhRzYOggTgF:b-s8rbhk)*

**Comment by itsbilal** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/pause_resume_cancel.md, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-Kl__TrpQIf3u75VthcP:-Kl_bqUAeWt-qqr-8cyG:bu2uh6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c005d596c79172c1a809689c88bd9a82e636acfd/docs/RFCS/pause_resume_cancel.md#L84)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What type did we end up using as our query ids? Integers or bytes/strings? We may only be able to support `pg_cancel_backend` if we use integer query ids. 
</blockquote></details>

We haven't decided on that yet, but good point - we may want to stick to integer counters as query IDs for this reason alone.  We can also discuss this around the time my query cancellation RFC is out for review; it doesn't have to be finalized for this RFC.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-:-Kl_ctVXj3U1A6wgNYdc:bnfp4nl)*

**Comment by benesch** [comment]
IDs generated with unique_rowid or its moral equivalent? We should check to
see if Postgres IDs are int8s and not int4s.

**Comment by bdarnell** [comment]
Postgres "backend IDs" used for cancellation are 32 bits.

**Comment by a-robinson** [comment]
:lgtm: Thanks for including how different systems approach the problem!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-:-KlaumzVbFFJcqVPPmKr:b-epvm04)*

**Comment by jordanlewis** [comment]
:lgtm: IMO, `CANCEL/PAUSE/RESUME` is more natural than `ALTER QUERY/JOB`.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-:-Kld2Y-cEDzJIo-YZKGS:bcl3iiq)*

**Comment by benesch** [comment]
Since it seems no one is opposed to `CANCEL/PAUSE/RESUME` and we have a few votes in favor of it: entering final comment period!

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16273#-:-KlvDkjge6Hb2i_ko2F3:bnfp4nl)*

**Comment by benesch** [comment]
Hearing no objections, I'm merging!

**Pull request merged**
