### PR TITLE
sql: fix overzealous short-circuit in BETWEEN

### LINKED ISSUE #14682: sql: BETWEEN doesn't handle NULL correctly
In Postgres:

```
jordan=# select 80 between null and 74;
 ?column?
----------
 f
(1 row)
```

In CockroachDB:

```
root@:26257/> SELECT 80 BETWEEN null AND 74;
+------------------------+
| 80 BETWEEN NULL AND 74 |
+------------------------+
| NULL                   |
+------------------------+
(1 row)
```

`a BETWEEN x AND y` is supposed to be equivalent to `a >= x AND a <= y`. Since we properly handle `select 80 >= null and 80 <= 74`, returning `false`, we should make sure that the equivalent `BETWEEN` returns `false` as well and not `null`.

Note that for whatever reason, `NULL AND false` is supposed to return `false`, while `NULL AND true` is supposed to return `true`. We currently handle this correctly, the same as Postgres.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, certain carefully constructed `BETWEEN` queries would return
`NULL` instead of `false`, even though their normalized equivalents
using comparison and boolean operators would return `false` as expected.

For instance, `SELECT 5 BETWEEN NULL AND 1` would return `NULL` instead
of `false`, even though `SELECT 5 >= NULL AND 5 <= 1` correctly returns
`false`.

This was caused by a slightly overzealous normalization implementation
for `RangeExpr` that would return `NULL` if any of its parameters were
`NULL`, instead of the correct behavior.

Now, `BETWEEN` expressions always behave like their normalized
comparison/boolean operator forms.

Fixes #14682.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/normalize.go, line 513 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4I-xplnI8rMp6wPRK:-Kh4I-xrKbSGl34W8bVS:bzt5pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L513)):*
> ```Go
> 	leftCmp := GE
> 	rightCmp := LE
> 	makeOpExpr := func(left, right TypedExpr) normalizableExpr { return NewTypedAndExpr(left, right) }
> ```

We can do something like `makeOpExpr := NewTypedAndExpr` and later `makeOpExpr = NewTypedOrExpr`, right?

---

*[pkg/sql/parser/normalize.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4IeWYPuHxajntOS3A:-Kh4IeWYPuHxajntOS3B:b-7usriu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L522)):*
> ```Go
> 
> 	var newLeft, newRight TypedExpr
> 	if from == DNull {
> ```

are these NULL checks needed? Shouldn't we just delegate them to `ComparisonExpr.normalize` so that we're not duplicating logic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686)*

**Comment by jordanlewis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/normalize.go, line 513 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4I-xplnI8rMp6wPRK:-Kh4JDs4x00thh_ff70n:blfzl2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L513)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can do something like `makeOpExpr := NewTypedAndExpr` and later `makeOpExpr = NewTypedOrExpr`, right?
</blockquote></details>

No, since those functions don't return normalizeableExpr directly, the type system doesn't let us do that. I already tried that :(

---

*[pkg/sql/parser/normalize.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4IeWYPuHxajntOS3A:-Kh4JTuiN__yZqy6OY8-:b-8fp4oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L522)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

are these NULL checks needed? Shouldn't we just delegate them to `ComparisonExpr.normalize` so that we're not duplicating logic?
</blockquote></details>

Right now running `NewTypedComparisonExpr` panics if you give it any NULLs though, because it tries to look up the correct comparison expression to use and fails since it doesn't have the type information for the NULL expression.

Probably there's a refactor to be made to clean this up but I haven't seen it yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/normalize.go, line 513 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4I-xplnI8rMp6wPRK:-Kh4KfpmOU-1yFYYNTf1:bqaotdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L513)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

No, since those functions don't return normalizeableExpr directly, the type system doesn't let us do that. I already tried that :(
</blockquote></details>

Can we just cast the result of calling `makeOpExpr` to `normalizeableExpr`?

---

*[pkg/sql/parser/normalize.go, line 522 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4IeWYPuHxajntOS3A:-Kh4Kew7CUKwGXtVDDG3:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L522)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Right now running `NewTypedComparisonExpr` panics if you give it any NULLs though, because it tries to look up the correct comparison expression to use and fails since it doesn't have the type information for the NULL expression.

Probably there's a refactor to be made to clean this up but I haven't seen it yet.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-:-Kh4KpgVeEd8Ol0J2xcf:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Or is the issue that they each return their concrete type (`AndExpr` and `OrExpr`)?

**Comment by jordanlewis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/normalize.go, line 513 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686#-Kh4I-xplnI8rMp6wPRK:-Kh4M_9qDe1JOmt6ci8x:b4krvb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c83b611730f5a304efd54e80182bcad0a2d33e3/pkg/sql/parser/normalize.go#L513)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we just cast the result of calling `makeOpExpr` to `normalizeableExpr`?
</blockquote></details>

I don't follow your suggestion - but I'm pretty sure this is the best we can do. I even consulted with @tamird before I submitted this change =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14686)*

**Comment by jordanlewis** [comment]
> Or is the issue that they each return their concrete type (AndExpr and OrExpr)?

Yes, that is the issue.

**Comment by knz** [comment]
Nicely spotted. Thanks.

**Pull request merged**
