### PR TITLE
obsservice: remove the package

### PR DESCRIPTION
**Pull request by dhartunian**
This package is not used in production and is not being actively
developed. Removing for now.

The CLI flags were not documented so they are also removed without a
release note.

Resolves: CRDB-42484

Release note: None

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]

**Comment by rickystewart** [comment]
Looks like you haven't run `gazelle`? (`./dev gen bazel`)

**Comment by dhartunian** [comment]
yep yep @rickystewart just pushed it!

**Review by jlinder — COMMENTED** [review]
Great!

I think this line can also be removed because it's referencing something that is only in the obsservice: https://github.com/cockroachdb/cockroach/blob/f31617c5ded282076f36fe0f939b46c4862c448a/pkg/testutils/lint/lint_test.go#L304

**Comment by jlinder** [comment]
Can you also reference CRDB-42484 as the issue this is associated with?

**Pull request merged**
