### PR TITLE
cluster: remove a series of 2.1+ cluster versions

### PR DESCRIPTION
**Pull request by nvb**
I wanted to remove `VersionLazyTxnRecord` and `VersionPushTxnToInclusive`,
but while there I removed all of the following:
- VersionCascadingZoneConfigs
- VersionLoadSplits
- VersionExportStorageWorkload
- VersionLazyTxnRecord
- VersionSequencedReads
- VersionCreateStats
- VersionDirectImport
- VersionPushTxnToInclusive

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: mod some comments

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, 5 of 5 files at r4, 6 of 6 files at r5, 4 of 4 files at r6, 3 of 3 files at r7, 8 of 8 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-:-LiKE0dz9pCGYXDSwgUs:b-lk9jt9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica.go, line 1458 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKCsqhBWKqCS9yVOYW:-LiKCsqhBWKqCS9yVOYX:b-oeicgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f358ed804af05f8c4b404efc4d8a282d8e0916c/pkg/storage/replica.go#L1458)):*
> ```Go
> 				DeprecatedNow:   b.Header.Timestamp,
> 				PushType:        roachpb.PUSH_ABORT,
> 				InclusivePushTo: true,
> ```

Ah, this is subtle.
___
*[pkg/storage/batcheval/cmd_get.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKC9_c1alj8QfIX2sy:-LiKC9_c1alj8QfIX2sz:b3x81rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d963bab6fbc4909d0b5eb9cc942143cafbc7a5/pkg/storage/batcheval/cmd_get.go#L78)):*
> ```Go
> 	// active which proves that all nodes are running version 19.2.
> 	//
> 	// TODO(nvanbenschoten): Remove in 20.1. This serves only as documentation
> ```

I don't understand why you can't remove this now.  I do understand why VersionInclusivePush to needs to stay around, but this?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38446)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/replica.go, line 1458 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKCsqhBWKqCS9yVOYW:-LiKiFqb9hAJ7yopruPn:b8m825y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f358ed804af05f8c4b404efc4d8a282d8e0916c/pkg/storage/replica.go#L1458)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ah, this is subtle.
</blockquote></details>

Yeah, it's unfortunate.
___
*[pkg/storage/batcheval/cmd_get.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKC9_c1alj8QfIX2sy:-LiKiKId4FFcwtFbrwwQ:bkox8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d963bab6fbc4909d0b5eb9cc942143cafbc7a5/pkg/storage/batcheval/cmd_get.go#L78)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't understand why you can't remove this now.  I do understand why VersionInclusivePush to needs to stay around, but this?
</blockquote></details>

I'm leaving this around as documentation to explain that because we checked a cluster version to determine whether we should ignore sequence numbers in 19.1, 19.2 nodes can't blindly expect all nodes in their cluster to respect sequence numbers when reading. It's possible that a 19.2 node joins the cluster before all 19.1 nodes realize that the cluster version has been upgraded to 19.1.X. I reworded the comment slightly.

**Review by tbg — COMMENTED** [review]
> Reviewed 13 of 13 files at r10, 4 of 4 files at r11, 3 of 3 files at r12, 8 of 8 files at r13, 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38446)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_get.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKC9_c1alj8QfIX2sy:-LiMr6FVC54jV8jTjeaz:ba2rgtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d963bab6fbc4909d0b5eb9cc942143cafbc7a5/pkg/storage/batcheval/cmd_get.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm leaving this around as documentation to explain that because we checked a cluster version to determine whether we should ignore sequence numbers in 19.1, 19.2 nodes can't blindly expect all nodes in their cluster to respect sequence numbers when reading. It's possible that a 19.2 node joins the cluster before all 19.1 nodes realize that the cluster version has been upgraded to 19.1.X. I reworded the comment slightly.
</blockquote></details>

Feels like I'm missing something still. What confuses me is that I don't understand who you are documenting this for. After removing this and by extension `IgnoreSequence`, your code works the same; it's using the new behavior now (right?). From your comment, my best guess now is that this documentation is just in an awkward place. In this code, it looks very much like "19.2 nodes are blindly relying on correct sequence number behavior". According to your comment, there should be places where they have to be more careful. Where is that and why is the comment here and not there?

(It doesn't help that MVCCGetOptions.IgnoreIntent doesn't have any documentation, not sure that it's worth fixing now that it's basically obsolete)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38446)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/storage/batcheval/cmd_get.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38446#-LiKC9_c1alj8QfIX2sy:-LiUp97LCEj6UvzvaIbg:bsbyxhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7d963bab6fbc4909d0b5eb9cc942143cafbc7a5/pkg/storage/batcheval/cmd_get.go#L78)):*
> After removing this and by extension IgnoreSequence, your code works the same; it's using the new behavior now (right?)

Yes, this is the same as deleting all of the code. The plan was to do that in 20.1.

> Where is that and why is the comment here and not there?

I'm leaving this primarily for myself and @knz because we're going to need to be careful about this when fixing the Halloween problem. The point of the comment is to say that until 20.1, we need to be careful that not all nodes in the cluster will always consider sequence numbers when performing a scan, even though the codebase that we'll be programming against will. Leaving the code in until it is no longer relevant is a way to ensure that we don't completely forget about this migration period.

I don't see where a better place to put it would be. Moving it to `Transaction.Sequence` is likely to get lost. Leaving the code like this ensures that readers can understand what to expect from replicas before and after the old cluster setting is active.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38446)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
bors r=tbg

**Pull request merged**
