### PR TITLE
storage: plumb more contexts

### PR DESCRIPTION
**Pull request by RaduBerinde**
See individual commits.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9534)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Many of these newly plumbed operations carry no span, right? For instance, the `idAllocator` now has a span and uses it for `db.Run` but I don't see how that context is used meaningfully for tracing.

---

Reviewed 3 of 3 files at r1, 7 of 7 files at r2, 9 of 9 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 4 of 4 files at r6, 5 of 5 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9534#-:-KSaprZzmvxHk7-U5kjw:bo54c4d)*

**Comment by RaduBerinde** [comment]
Right. I'm not adding any spans here.

AFAICT are two operations in all these changes - the `db.Inc` in `idAllocator` and the `db.Run` in `maybeUpdateTransaction`. Should I open spans for these?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9534#-:-KSatr64C8XIZ0LACgKV:bned5un)*

**Comment by tschottdorf** [comment]
`maybeUpdateTransaction` is called as part of `(*Store).Send`, so that should have a context it can use already (or you can make a child span). I don't think the allocator increment is that important, but it's probably worth adding while we're at it.

More generally speaking, perhaps `db.*` should automatically start a span if here isn't one already, using the caller as the name. But doesn't have to be here.

:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9534#-:-KSaytVQXcG1BE9IIAkR:bmdslyy)*

**Comment by RaduBerinde** [comment]
I like the idea of `db.*` automatically opening up spans. Putting on my TODO list.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9534#-:-KSb-ZPFcwH5V9UsYuzB:b-f4ft0b)*

**Pull request merged**
