### PR TITLE
logictest: validate zone configs at the end of every logic test

### LINKED ISSUE #66749: multiregionccl: validate multi-region zone configurations in logic tests
**Is your feature request related to a problem? Please describe.**

Prompted as a followup for https://github.com/cockroachdb/cockroach/issues/66637. The bug in question happened because we weren't setting the multi-region implied zone config for an index. This was caught by the randomized schema changer test because we validate zone configs using the `crdb_internal.validate_multi_region_zone_configs` builtin. However, we don't do this for our data-driven logic tests. As these tests are auto rewritten a lot it is rather fragile. 

We should validate the system generated multi-region zone configs after each logic test run similar to how we validate descriptors. Descriptor validation is powered by the `crdb_internal.invalid_objects` internal table. We could create an analogous `crdb_interanl.invalid_multi_region_zone_configs` table and check against it after every logic test run. This has the additional benefit of allowing users to run introspection queries as well. It's unclear how valuable this is considering we already have that builtin above though. 

@otan suggested checking against this internal table after every logic test statement execution instead of checking once at the end of the run. While this has the added benefit of checking zone configurations at intermediate steps it might make the test slightly slower. 

** Alternatives **
Another alternative would be to validate inside the database itself. When performing a mutli-region op on a database or a table that implies regeneration of system generated zone configs we would perform some additional validation. For a database change, all zone configurations inside the database would be validated. For a table change, all table/table index zone configurations would be validated. 

This feels like a strictly superior alternative to the solution proposed above but might be tricky considering we've already shipped the [bug above](https://github.com/cockroachdb/cockroach/issues/66637).

### PR DESCRIPTION
**Pull request by otan**
Release justification: test only change

Resolves #66749

Ignore first commit.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/logictest/logic.go, line 3133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWSFbKCi4746uyECwq:-MiWSFbKCi4746uyECwr:b1zbjjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3133)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		dbs, err := t.db.Query(
> 			`SELECT database_name FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'postgres')`,
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error getting database names")
> 		}
> ```
</details>

thoughts on:

```go
var dbsArr pg.StringArray
if err := t.db.QueryRow(`
SELECT array_agg(database_name)
  FROM [SHOW DATABASES]
 WHERE database_name NOT IN ('system', 'postgres');
`).Scan(&dbsArr); err != nil {
    return errors.Wrap(err, "error getting database names")
}
```
___
*[pkg/sql/logictest/logic.go, line 3147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWQIepA3jRX3jwu8bb:-MiWQIepA3jRX3jwu8bc:bh8pkzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3147)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
> 		dbs, err := t.db.Query(
> 			`SELECT database_name FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'postgres')`,
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error getting database names")
> 		}
> 		defer func() {
> 			retErr = errors.CombineErrors(retErr, dbs.Close())
> 		}()
> 		var dbNames []string
> 		for dbs.Next() {
> 			if err := dbs.Err(); err != nil {
> 				return errors.Wrap(err, "error processing databases")
> 			}
> 			var dbName string
> 			if err := dbs.Scan(&dbName); err != nil {
> 				return errors.Wrap(err, "error scanning db name")
> 			}
> 			dbNames = append(dbNames, dbName)
> 		}
> ```
</details>

can you pull this listing of dbs out into a closure and then use it to address the TODO right below your validation loop?
___
*[pkg/sql/logictest/logic.go, line 3163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWQVbVAlT31VhP5fc4:-MiWQVbVAlT31VhP5fc5:b8vb6g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3163)):*
> ```Go
> 					return errors.Wrapf(err, "error validating zone config for database %s", dbName)
> 				}
> 				if _, err := conn.ExecContext(ctx, "SELECT crdb_internal.validate_multi_region_zone_configs()"); err != nil {
> ```

should we be validating these zone configs as part of descriptor validation one day? I know we currently lack the infrastructure to do so, but would it make sense? My sense is absolutely yes. If so, I'll file an issue.

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/logic.go, line 3163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWQVbVAlT31VhP5fc4:-MiWaVMX9JSSr6IElIg2:b7acw8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3163)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we be validating these zone configs as part of descriptor validation one day? I know we currently lack the infrastructure to do so, but would it make sense? My sense is absolutely yes. If so, I'll file an issue. 
</blockquote></details>

This `validate_multi_region_zone_configs` builtin constructs the expected value of these multi-region zone config fields (num_voters, num_replicas, constraints etc.) and compares them against the actual value. Users are allowed to change these fields even if they're using the multi-region primitives (although doing so is gated behind a session setting). We might break this use case if we introduce this validation as part of our descriptor validation. We'd have to be smarter/save some additional state on the descriptor if we do decide to do this.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/logictest/logic.go, line 3133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWSFbKCi4746uyECwq:-MiYSjRB66KjmQTDfkTl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3133)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		dbs, err := t.db.Query(
> 			`SELECT database_name FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'postgres')`,
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error getting database names")
> 		}
> ```
thoughts on:

```go
var dbsArr pg.StringArray
if err := t.db.QueryRow(`
SELECT array_agg(database_name)
  FROM [SHOW DATABASES]
 WHERE database_name NOT IN ('system', 'postgres');
`).Scan(&dbsArr); err != nil {
    return errors.Wrap(err, "error getting database names")
}
```
</blockquote></details>

Done.
___
*[pkg/sql/logictest/logic.go, line 3147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MiWQIepA3jRX3jwu8bb:-MiYSjtZ1u3luDogNjA8:b-bt34ac) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a869877d28a81bcda56a62763556f527dccc61/pkg/sql/logictest/logic.go#L3147)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		dbs, err := t.db.Query(
> 			`SELECT database_name FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'postgres')`,
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error getting database names")
> 		}
> 		defer func() {
> 			retErr = errors.CombineErrors(retErr, dbs.Close())
> 		}()
> 		var dbNames []string
> 		for dbs.Next() {
> 			if err := dbs.Err(); err != nil {
> 				return errors.Wrap(err, "error processing databases")
> 			}
> 			var dbName string
> 			if err := dbs.Scan(&dbName); err != nil {
> 				return errors.Wrap(err, "error scanning db name")
> 			}
> 			dbNames = append(dbNames, dbName)
> 		}
> ```
can you pull this listing of dbs out into a closure and then use it to address the TODO right below your validation loop?


</blockquote></details>

see separate commit.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-:-Mibo1Wp5N1X8H57rZ8P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/logictest/logic.go, line 3129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69680#-MibnFG93l9i-0Cb41F-:-MibnFG93l9i-0Cb41F0:bwqf6jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/85b130b43bd42b15e2d83f4bbc25686cd64f8560/pkg/sql/logictest/logic.go#L3129)):*
> ```Go
> 	if err := t.db.QueryRow(
> 		`SELECT array_agg(database_name) FROM [SHOW DATABASES] WHERE database_name NOT IN ('system', 'postgres')`,
> 	).Scan(&dbNames); err != nil {
> ```

I feel like there's one extra layer of pointer that doesn't need to be here. In fact, I'm sort of surprised that this works. What happens if you do `var dbNames pq.StringArray`?

**Comment by otan** [comment]
bors r=ajwerner

> I feel like there's one extra layer of pointer that doesn't need to be here. In fact, I'm sort of surprised that this works. What happens if you do var dbNames pq.StringArray?

works as well, i guess it reassigns the pointer if its a pointer parsed in and uses something from the heap?

**Pull request merged**
