### PR TITLE
storage/cloud: delegate redaction and implicit auth checks

### PR DESCRIPTION
**Pull request by dt**
storage/cloud: make implicit auth check funciton of conf

Previously we had two methods that dug through ExternalStorage URI params:
One, which extracted the params to create a structured config that would
actually be used to open and interact with that storage, and a second that
looked for authorization-releated params to decide if access was explicitly
or implicitly authorized (i.e. had credentials specified, or made use of the
access the node performing the action had).

This changes the latter to instead be a function of the former, so there is
only one method that extracts parameters from string URIs to produce a structured
configuration object, and then the determination of if a given configuration is
one that carries explicit authorization can be done from that config object.

storage/cloud: make implementations register redaction params

This changes the redaction of URIs from being done from a pre-defined map
of sensitive params to a runtime populated map, in which implementations
register their sensitive params during their registration during init.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
This is failing a bunch of tests since I made the query params to scrub be per-scheme, which I think is _correct_ but all our tests are adding AWS_SECRET_KEY or whatever to a nodelocal URI and then are written assuming it is redacted when that param isn't really applicable to nodelocal. Hmm.

**Comment by dt** [comment]
Okay, I walked back the per-scheme URI param scrubbing and just went back to scrubbing all sensitive params for any scheme from every scheme for now in the interest of keeping this change manageable. We can revisit per-scheme scrubbing later if we want.

I also switched the enum value names for each storage to match the user-facing names so we can just use the enum values in errors. This made the diff a bit messy since it seems like changing the string map values required changing the names of the generated go symbols too, but it's mostly mechanical replacements.

**Comment by dt** [comment]
Found a bug while I was here in the implicit-auth admin check on `SHOW BACKUP x IN y`: we were checking only `x` not `y/x` and then silently saying it was not auth'ed, when x's parsed scheme is empty. Not a big deal since it just spuriously required admin but the tests caught it after the refactor.

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/roachpb/api.go, line 1330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64662#-MZwKMlSDzzUqBYXPczV:-MZwKMlSDzzUqBYXPczW:b-11n1dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/847568791f7c039c6e727fcca20de5a9dc0a16d5/pkg/roachpb/api.go#L1330)):*
> ```Go
> 	case ExternalStorageProvider_s3:
> 		// custom endpoints could be a network resource only accessible via this
> 		// noode's network context and thus have an element of implicit auth.
> ```

nit: node's

**Review by dt — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64662#-:-MZxV5HN9klNhQgarHYP:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/roachpb/api.go, line 1330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64662#-MZwKMlSDzzUqBYXPczV:-MZxUuo81QQCE5Nlki8-:b-y6tkq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/847568791f7c039c6e727fcca20de5a9dc0a16d5/pkg/roachpb/api.go#L1330)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: node's
</blockquote></details>

nice catch, I'll get it in a follow-up since this is green now but roachpb changes make it conflict-prone.

**Pull request merged**
