### PR TITLE
sql: add 192auto to the hint for vectorize session variable

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: bug fixes and low-risk updates to new
functionality (only hint change).

`192auto` was forgotten to be added to the hint for `vectorize` session
variable.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/vars.go, line 395 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46623#-M3MUNfc3PFcCGz46UfJ:-M3MUNfdA7o9gLXBc9S7:bfjp73x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9e858953fef5b979f6b458ca9f26f6ba75205e/pkg/sql/vars.go#L395)):*
> ```Go
> 			if !ok {
> 				return newVarValueError(`vectorize`, s,
> 					"off", "192auto", "auto", "on", "experimental_always")
> ```

I wonder whether we should remove `experimental_always` as advertised option. Probably it's ok to have it though since it has "experimental" prefix.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46623#-:-M3MbnBZ6bB0lXNa5WpC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
