### PR TITLE
distsql: add table for local/final aggregation stages

### PR DESCRIPTION
**Pull request by RaduBerinde**
Many aggregation functions allow for a local stage that can perform some local
aggregation. For example, for COUNT, we can do a local COUNT stage and a
SUM_INT final stage that adds up the counts.

This change adds a look-up table for these stages and test code that verifies
they are correct.

In the future the plan is to also support things like AVG by having multiple
functions per stage plus an additional rendering stage.

CC @irfansharif

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12543)

### CODE REVIEW

**Comment by irfansharif** [comment]
LGTM modulo plans dealing with aggregation functions with `DISTINCT` specified. I presume this would entail an additional `distinct` stage, then distributed by hash + what's currently happening here.

---

Reviewed 8 of 11 files at r1, 11 of 11 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlplan/aggregator_funcs.go, line 45 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_7MNO83F8Np0vREzp:-KZ_7MNO83F8Np0vREzq:bthxzqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs.go#L45)):*
> ```Go
> 	},
> 
> 	distsqlrun.AggregatorSpec_COUNT: {
> ```

how are we accounting for `COUNT DISTINCT`? rather any aggregation function that isn't commutative/can't be split into LOCAL-FINAL when applied with `DISTINCT`?

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 246 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_9WI0jOGtqYHrhHIF:-KZ_9WI1sNsibIGxRjbz:b-p070x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L246)):*
> ```Go
> 		for colIdx := 1; colIdx < len(desc.Columns); colIdx++ {
> 			// See if this column works with this function.
> 			_, _, err := distsqlrun.GetAggregateInfo(fn, desc.Columns[colIdx].Type)
> ```

same as comment above, are we testing functions with `DISTINCT` on?

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_9hYzb15EAuC4ccqu:-KZ_9hZ-NgBzW8BMn4B2:b-tbxtzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L259)):*
> ```Go
> 		}
> 		if !foundCol {
> 			t.Errorf("no column suitable for %d", fn)
> ```

not completely sure what we're testing here. it seems like we have a column chosen specifically per aggregation function, it's worth adding a comment stating this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-:-KZ_BpTAa1NENHKmUWbB:b-8u0zt0)*

**Comment by RaduBerinde** [comment]
TFTR!

You are correct, all this stuff only works without DISTINCT. In general we can't do any local aggregation with DISTINCT (other than removing duplicates). As you say, the best way to distribute that would be to first do the distinct part and then the aggregation.

If we also have a group key (e.g. `SELECT SUM(DISTINCT z) FROM xyz GROUP BY y`), we can just distribute according to those columns and each bucket can do the entire aggregation (no local stage needed).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_9hYzb15EAuC4ccqu:-KZalCjdRCrA25qfZPwc:b5cdwwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L259)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

not completely sure what we're testing here. it seems like we have a column chosen specifically per aggregation function, it's worth adding a comment stating this.
</blockquote></details>

it's pretty much testing the test, just a check that we ran all the functions (if e.g. we remove the bool columns from the table, without this check the test would still pass without testing the bool funcs).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-:-KZalTlvk7-iuCdC8zbA:b-wrx1h2)*

**Comment by andreimatei** [comment]
:lgtm:
giddy up!

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbgRcMjQVg6nTTR_mh:-KZbgRcMjQVg6nTTR_mi:b-uhqv0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L79)):*
> ```Go
> // table. We assume the table's first column is the primary key, with values
> // from 1 to numRows. A non-PK column that works with the function is chosen.
> func testDistAggregationInfo(
> ```

nit: mind naming this something else than `testFoo`? 

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 207 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbixbJEKCe1jE9mOyl:-KZbixbKj1oKzW22fG0s:bwcxtxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L207)):*
> ```Go
> }
> 
> func TestDistAggregationTable(t *testing.T) {
> ```

nit:
```
// Test that distributing  agg functions according to DistAggregationTable yields correct results:
- we're going to run plan each aggregation as either the two-stage process described by the DistAggTable or as a single global process, and verify that the results are the same.
```

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 242 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbiTiwY3x3d9lHHHzb:-KZbiTiwY3x3d9lHHHzc:b-n6jejb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L242)):*
> ```Go
> 	desc := sqlbase.GetTableDescriptor(kvDB, "test", "t")
> 
> 	for fn, info := range DistAggregationTable {
> ```

nit:
```
// We're going to test each aggregation function on every column that can be used as input for it.
```

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_9hYzb15EAuC4ccqu:-KZbhz3rkkTDcJ01Zo3-:bwud7ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L259)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

it's pretty much testing the test, just a check that we ran all the functions (if e.g. we remove the bool columns from the table, without this check the test would still pass without testing the bool funcs).
</blockquote></details>

nit: "no column suitable for %d; aggregation function %s was not tested"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-:-KZbjSltZYqAN_sfohT8:b-p6cpi4)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 22 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 79 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbgRcMjQVg6nTTR_mh:-KZblN0qY88lvh16rHtn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L79)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: mind naming this something else than `testFoo`? 
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 207 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbixbJEKCe1jE9mOyl:-KZblclxL9Bxnc3YwR_m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L207)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit:
```
// Test that distributing  agg functions according to DistAggregationTable yields correct results:
- we're going to run plan each aggregation as either the two-stage process described by the DistAggTable or as a single global process, and verify that the results are the same.
```
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 242 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZbiTiwY3x3d9lHHHzb:-KZblknMUi7ChtGpggfb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L242)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit:
```
// We're going to test each aggregation function on every column that can be used as input for it.
```
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/aggregator_funcs_test.go, line 259 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-KZ_9hYzb15EAuC4ccqu:-KZblv4PTlDA7xODalZR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d176178c5226412cc729f391c77d75ab73aca6/pkg/sql/distsqlplan/aggregator_funcs_test.go#L259)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "no column suitable for %d; aggregation function %s was not tested"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12543#-:-KZblvy_0f0ZESyHkkkx:b-814g8k)*

**Pull request merged**
