### PR TITLE
timeutil: embed Go time zone data into CockroachDB

### PR DESCRIPTION
**Pull request by otan**
Refs #36864

* Use go's time/tzdata to embed timezone data.
* Modify timeutil package to always use this package.
* Remove cli checks for tzdata.
* Add lint rule to use timeutil.LoadLocation

The binary size changes by ~1MB here.

Release note (general change): The timezone data is now built in to the
CockroachDB binary, which is the fallback source of time if tzdata is
not located by the default Go standard library.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM, but can you investigate what the acceptance test is trying to tell you?

Also because of this PR we will now need to be more proactive about upgrading the go version that we use (or manually pull in new versions of tzdata into patch releases). What do you and @jlinder think about this? What's a good way to do this moving forward?

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56634#-:-MM0966vEDZz5Z1uBsbi:b-kwif6d)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
pretty sure the acceptance test failure is because i forgot to update the builder image. sending that for a re-run.

> Also because of this PR we will now need to be more proactive about upgrading the go version that we use (or manually pull in new versions of tzdata into patch releases). What do you and @jlinder think about this? What's a good way to do this moving forward?

feels like every major release from now on needs an explicit review of the embedded tzdata? i'm not totally sure what to answer here. it is a fallback in the end, so if users care about up-to-date tz data they would need to ensure their packages are up to date.

**Comment by otan** [comment]
looks like the gce workers are go1.14. how do they get installed?

**Comment by knz** [comment]
I thought this was from scripts/gceworker.sh
which in turn runs `build/bootstrap/bootstrap-debian.sh`

but apparently there's already 1.15 in there.

Also I see your CI is fine now.

So I'd say you can probably merge this?

**Comment by otan** [comment]
It was the need to run packer and update the TC image...

**Comment by otan** [comment]
bors r=knz

**Pull request merged**
