### PR TITLE
importccl: better error message for free-tier

### PR DESCRIPTION
**Pull request by spaskob**
For details see https://cockroachlabs.atlassian.net/browse/CC-2981

Release note: none.

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
Can we also add a test for this? Something like the following in `import_stmt_test.go` should do it

```
func TestImportDisallowedInTenant(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	ctx := context.Background()
	baseDir := filepath.Join("testdata")
	args := base.TestServerArgs{ExternalIODir: baseDir}
	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{ServerArgs: args})
	defer tc.Stopper().Stop(ctx)
	conn := tc.Conns[0]
	sqlDB := sqlutils.MakeSQLRunner(conn)

	_, conn10 := serverutils.StartTenant(t, tc.Server(0), base.TestTenantArgs{TenantID: roachpb.MakeTenantID(10)})
	defer conn10.Close()
	t10 := sqlutils.MakeSQLRunner(conn10)

	const userfileURI = "userfile://defaultdb.public.root/test.csv"
	const importStmt = "IMPORT TABLE foo (k INT PRIMARY KEY, v INT) CSV DATA ($1)"

	t10.ExpectErr(t, "error message to check", ` (k INT PRIMARY KEY, v INT) CSV DATA ("userfile://defaultdb.public.root/test.csv")`)
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-:-MSY5JZz6VSrLzI4sXI1:b-zatg2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/importccl/import_stmt.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-MSY3HQKEn31k5gHbSGS:-MSY3HQKEn31k5gHbSGT:b-27vyst) ([raw file](https://github.com/cockroachdb/cockroach/blob/be91f452b433826218cfe3cebb4e3a6ef6181843/pkg/ccl/importccl/import_stmt.go#L261)):*
> ```Go
> 	if !p.ExecCfg().Codec.ForSystemTenant() {
> 		return nil, nil, nil, false,
> 			errors.Errorf("IMPORT is not yet supported in the free tier version of CockroachCloud.")
> ```

Do you think that IMPORT should know about  "free tier" or even "CockroachCloud"? From the db side, I think it makes more sense to have an error message that is something like "IMPORT is not yet supported in tenants", what do you think?

nit: We can use `errors.New` here rather than `errors.Errorf` since there's no formatting going on in the string.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/importccl/import_stmt.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-MSY3HQKEn31k5gHbSGS:-MSY8cRZ3Y1Vyf7JIHDW:b-ge2iug) ([raw file](https://github.com/cockroachdb/cockroach/blob/be91f452b433826218cfe3cebb4e3a6ef6181843/pkg/ccl/importccl/import_stmt.go#L261)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do you think that IMPORT should know about  "free tier" or even "CockroachCloud"? From the db side, I think it makes more sense to have an error message that is something like "IMPORT is not yet supported in tenants", what do you think?

nit: We can use `errors.New` here rather than `errors.Errorf` since there's no formatting going on in the string.
</blockquote></details>

I supposed that the only users of tenants on 20.2 is cloud, so I don't feel too strongly about this. I do want to run it by @mwang1026 in case he has any thoughts here.

**Review by pbardea — COMMENTED** [review]
Whoops, I copied an outdated version, the check will probably look closer to:
```
func TestImportDisallowedInTenant(t *testing.T) {
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)

	ctx := context.Background()
	tc := testcluster.StartTestCluster(t, 1, base.TestClusterArgs{})
	defer tc.Stopper().Stop(ctx)

	_, conn10 := serverutils.StartTenant(t, tc.Server(0), base.TestTenantArgs{TenantID: roachpb.MakeTenantID(10)})
	defer conn10.Close()
	t10 := sqlutils.MakeSQLRunner(conn10)

	const userfileURI = "userfile://defaultdb.public.root/test.csv"
	const importStmt = "IMPORT TABLE foo (k INT PRIMARY KEY, v INT) CSV DATA ($1)"

	t10.ExpectErr(t, "error message to check", importStmt, userfileURI)
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-:-MSYCLiaE6xX1BV6vX2X:b-syrozs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

**Comment by spaskob** [comment]
PTAL

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/importccl/import_stmt.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-MSY3HQKEn31k5gHbSGS:-MSYZ-pyAdWY5sKHXXmi:b-ds0kfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/be91f452b433826218cfe3cebb4e3a6ef6181843/pkg/ccl/importccl/import_stmt.go#L261)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I supposed that the only users of tenants on 20.2 is cloud, so I don't feel too strongly about this. I do want to run it by @mwang1026 in case he has any thoughts here.
</blockquote></details>

I found that we error with `operation is unsupported in multi-tenancy mode`, on some unsupported features elsewhere. I think the best way forward is them something like "IMPORT is unsupported in multi-tenancy mode". Is that acceptable?

I do have concerns about specifically referring to "free tier" since this error is not specific to just free tier, but would also apply to a paid tenant offering. 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 5576 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59703#-MSYZh9g0zoExdNxvLr5:-MSYZh9g0zoExdNxvLr6:b-6lroaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b5fbde542404e3927537d30dd3ceef48166af4/pkg/ccl/importccl/import_stmt_test.go#L5576)):*
> ```Go
> 	const userfileURI = "userfile://defaultdb.public.root/test.csv"
> 	const importStmt = "IMPORT TABLE foo (k INT PRIMARY KEY, v INT) CSV DATA ($1)"
> 	t10.ExpectErr(t, "IMPORT is not yet supported in tenants.", importStmt, userfileURI)
> ```

(Also just a heads up that this error message doesn't match the one that we return)

**Comment by spaskob** [comment]
Thanks, done
PTAL

**Review by pbardea — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
