### PR TITLE
kvserver/rangelog: extract a package, use KVs

### LINKED ISSUE #35293: sql: unexpectedly high KV traffic on Namespace span resolving table name
Running a KV0 benchmark on a 128 node cluster leads to unexpectedly high QPS on a single range. 
screenshot_2019-02-28 replication dashboard cockroach console 1

An unfortunate thing about this traffic is it seems to sometimes have high correlation with increased raft log commit latency.

screenshot_2019-02-28 custom chart debug cockroach console 2

This range happens to be the SystemConfigSpan. When digging further with logspy we can see that all of the traffic to this range comes from the following query:

```
I190301 01:37:51.027024 3841768 storage/replica_evaluate.go:413  [n21,s21,r6/3:/Table/{SystemCon…-11}] evaluated Get command header:<key:"\212\211\274\022kv\000\001\213\211" > : header:<> value:<raw_bytes:"\264\354\223\312\001j" timestamp:<wall_time:1551403675956970817 > > , err=<nil>
```

This query seems to be the namespace resolution for the kv table. 
```
root@localhost:26257/defaultdb> SELECT crdb_internal.pretty_key('\212\211\274\022kv\000\001\213\211', 0);
  crdb_internal.pretty_key
+--------------------------+
  /2/1/52/"kv"/3/1
```
Where `2` is the [NamespaceTableID](https://github.com/cockroachdb/cockroach/blob/master/pkg/keys/constants.go#L297) `1` is its primary index, 52 is the database ID and `kv` is the table name. My best guess is that this is happening from this call https://github.com/cockroachdb/cockroach/blob/4cfbb6ecf7de234708cb855a9c95f85cea99e3ef/pkg/sql/database.go#L209.

Given nothing this database schema is not changing, why isn't the cache being hit more frequently? 

For reproduction, the above data was procured from a 128-node c5.xlarge AWS cluster running KV0 with 8192 split and 4 workload binaries running with concurrency 2048.

Jira issue: CRDB-4594

### LINKED ISSUE #89164: kvserver: stop using internal executor for rangelog
**Is your feature request related to a problem? Please describe.**
The rangelog table is written as part of the change replicas protocol. It can be useful for debugging. The implementation currently leverages the internal executor. In fact, it's the only use of the internal executor by kvserver at this point (AFAICT). It is problematic because we'd like the system database to be more like a regular database in terms of mutability. Today we cannot use leasing infrastructure for certain system tables because they are used by the internal executor which in turn is used by kvserver which starts up before that other infrastructure. 

**Describe the solution you'd like**

We can inject a much narrower interface into kvserver for writing eventlog entries and we can implement it using KV client APIs and lower-level sql encodings. In this way, we'll remove the bootstrapping dependency on sql-layer services. 

**Describe alternatives you've considered**
We could stop writing rangelogs synchronously altogether, and we may, but either way we should break this dependency.

**Additional context**

This will resolve https://github.com/cockroachdb/cockroach/issues/35293. 

Epic: CRDB-18596

Jira issue: CRDB-20156

### PR DESCRIPTION
**Pull request by ajwerner**
This sequence of commits extracts the rangelog logic to a subpackage, refactors the ID generation logic for more
control, adds some testing data and infrastructure, and, finally, swaps out the underlying implementation to use
raw KVs.

Fixes #89164
Fixes #35293

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM overall, but if we could decouple this further from the SQL layer by not depending on the SQL instance ID, that would be even better. Perhaps use the KV node ID instead of SQL instance ID? After all, the rangelog queries only run on the KV nodes where there may not be a SQL instance ID at all to go with.

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 9 of 9 files at r3, 16 of 16 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-:-NE68g8CD0pwXW6nMcev:b-fzrxli)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[`-- commits` line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE67HX_9TIVnO5ZsQq9):*
nit: of the interface.
___
*[`pkg/server/server.go` line 643 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE67sDm7A4qvRkunnXg:-NE67sDm7A4qvRkunnXh:brpztlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7488b17da06caf6d1b37b1d346c66d6fe0125809/pkg/server/server.go#L643)):*
> ```Go
> 	rangeLogWriter := rangelog.NewWriter(
> 		func() int64 {
> 			return int64(builtins.GenerateUniqueInt(idContainer.SQLInstanceID()))
> ```

Does it matter that we use the SQL instance ID for this? Does the locality property count? Could we not use purely random numbers, or perhaps even a UUID?



_Code quote (from pkg/kv/kvserver/rangelog/rangelog.go):_
```Go
NewWriter
```
___
*[`pkg/kv/kvserver/rangelog/rangelog_test.go` line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE68BlICl5JtLY6GIS_:-NE68BlICl5JtLY6GISa:b86dro3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6edb16a942bf328f1fe1baeda63cb420fc0ff3/pkg/kv/kvserver/rangelog/rangelog_test.go#L68)):*
> ```Go
> 	defer s.Stopper().Stop(ctx)
> 
> 	// Inject two table to write into. The first table will be written into by
> ```

nit: two tables

**Review by ajwerner — COMMENTED** [review]
The KV node ID is the SQL instance ID in the system tenant. I think that's actually sort of bad because of repaving problems, and if we ever did change it to use the same SQL instance ID infrastructure, I think that'd be good. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-:-NE6GQ1Y15Uqba9rlOZi:bmnfgox)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @nvanbenschoten)

___
*[`pkg/server/server.go` line 643 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE67sDm7A4qvRkunnXg:-NE6FoPeB3EdsIrOxCZ9:byweo2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7488b17da06caf6d1b37b1d346c66d6fe0125809/pkg/server/server.go#L643)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Does it matter that we use the SQL instance ID for this? Does the locality property count? Could we not use purely random numbers, or perhaps even a UUID?
</blockquote></details>

1) we cannot change the structure of the table without significant effort, so I'm inclined not to change that
2) The locality property doesn't really matter because the timestamp is in the primary key. However, I, for one, actively do not want to change the column types and I need a unique identifier.
3) It seems to me like what you're quarelling with is the term `SQLInstanceID` which in kv nodes we always assume to be the node ID -- so these are the same thing for the moment. If it placates you, I'll happily either use the node ID and cast it or change some signatures around `GenerateUniqueInt` and cast the node ID to int32 or something like that.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[`pkg/server/server.go` line 643 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE67sDm7A4qvRkunnXg:-NE6HfDx1Oq4pUN5X_Xu:b-n7j00s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7488b17da06caf6d1b37b1d346c66d6fe0125809/pkg/server/server.go#L643)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

1) we cannot change the structure of the table without significant effort, so I'm inclined not to change that
2) The locality property doesn't really matter because the timestamp is in the primary key. However, I, for one, actively do not want to change the column types and I need a unique identifier.
3) It seems to me like what you're quarelling with is the term `SQLInstanceID` which in kv nodes we always assume to be the node ID -- so these are the same thing for the moment. If it placates you, I'll happily either use the node ID and cast it or change some signatures around `GenerateUniqueInt` and cast the node ID to int32 or something like that.
</blockquote></details>

ok yes let's use the node ID instead of SQL instance ID. thanks

**Review by ajwerner — COMMENTED** [review]
I added a commit to try to make it all more explicit. Does it please you?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-:-NE6MgO_DaLvCFbcPNu-:bc8gfs2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin, @knz, @nvanbenschoten, and @stevendanna)

___
*[`-- commits` line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE67HX_9TIVnO5ZsQq9):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: of the interface.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangelog/rangelog_test.go` line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-NE68BlICl5JtLY6GIS_:-NE6MmVG4nUmJUe7_9L-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6edb16a942bf328f1fe1baeda63cb420fc0ff3/pkg/kv/kvserver/rangelog/rangelog_test.go#L68)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: two tables
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 7 of 30 files at r6, 1 of 3 files at r7, 4 of 9 files at r8, 12 of 16 files at r9, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89623#-:-NE6NK0K1eL1GySSbUtO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin, @nvanbenschoten, and @stevendanna)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
