### PR TITLE
client, sql: improve detection of retryable errors meant for a different transaction

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13028)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM, but I didn't look at the SQL parts that closely.

---

Reviewed 10 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 536 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbC0bf1jbVri82_gjGH:-KbC0bf1jbVri82_gjGI:bkakte5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f7a9a70e1a39c6d13c3d697ecbfa454fd363bd4/pkg/internal/client/txn.go#L536)):*
> ```Go
> 			// might get a RetryableTxnError if the closure ran another transaction
> 			// internally and let the error propagate upwards.
> 			return errors.Wrap(retErr, "terminated retryable error")
> ```

s/terminated retryable error/retryable error from another transaction/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-:-KbC2GHAFE2axqtO3QMd:bcx9pmc)*

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/txn.go, line 557 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBr6OZYbaAA2TKfz70:-KbBr6OZYbaAA2TKfz71:b-pnkwax) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/internal/client/txn.go#L557)):*
> ```Go
> // IsRetryableErrMeantForThisTransaction returns true if err is a retryable
> // error meant to restart txn.
> func IsRetryableErrMeantForThisTransaction(err *roachpb.RetryableTxnError, txn *Txn) bool {
> ```

The "This" seems off since we're passing the txn as an argument, maybe just `IsRetriableErrMeantForTxn`

---

*[pkg/internal/client/txn.go, line 631 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHAu9cn7CclvZXavH:-KbCHAu9cn7CclvZXavI:b36nj86) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/internal/client/txn.go#L631)):*
> ```Go
> 			// probably move the initialization of the txn ID here, in the client,
> 			// from the TxnCoordSender.
> 			panic(fmt.Sprintf("Got a retryable error meant for a different transaction. "+
> ```

`log.Fatalf(txn.Context`

---

*[pkg/sql/executor.go, line 683 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHFU8RDdHh4HW8lEs:-KbCHFU8RDdHh4HW8lEt:bgaodwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/executor.go#L683)):*
> ```Go
> 
> 		// Sanity check about not leaving KV txns open on errors.
> 		if err != nil && txnState.txn != nil {
> ```

can just add `&& !txnState.txn.IsFinalized()` here

---

*[pkg/sql/txn_restart_test.go, line 1223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBrvK7tknaTYbJuxoX:-KbBrvK7tknaTYbJuxoY:btvge7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1223)):*
> ```Go
> 
> // Test that a retryable error intended for a different transaction doesn't
> // cause another transaction to be retried.
> ```

I don't really understand what this is trying to say.. seems like the test verifies that the error is bubbled up for this txn even if it's for a different (bogus) txn?

---

*[pkg/sql/txn_restart_test.go, line 1239 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCJz5SealHPLEsq79n:-KbCJz5SealHPLEsq79o:b-7lhio9) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1239)):*
> ```Go
> 	}
> 
> 	_, err := sqlDB.Exec("UPDATE t.test SET v = 'updated' WHERE ("+
> ```

[nit] maybe use backquote like above for consistency

---

*[pkg/sql/txn_restart_test.go, line 1242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCIIlx24Cs50cupm2H:-KbCIIlysqKydW8GYzSi:btx9z05) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1242)):*
> ```Go
> 		"SELECT CRDB_INTERNAL.FORCE_RETRY('500ms':::INTERVAL, $1) > 0)", bogusTxnID)
> 	if isRetryableErr(err) {
> 		t.Fatalf("expected non-retryable error, got: %s", err)
> ```

`%v` in case `err == nil`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-:-KbCJhOPklyNXPkY52V0:bb6ywmx)*

**Comment by andreimatei** [comment]
Review status: 2 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/internal/client/txn.go, line 557 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBr6OZYbaAA2TKfz70:-KbCQaF73indg9DQJEbr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/internal/client/txn.go#L557)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The "This" seems off since we're passing the txn as an argument, maybe just `IsRetriableErrMeantForTxn`
</blockquote></details>

Done.

---

*[pkg/internal/client/txn.go, line 631 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHAu9cn7CclvZXavH:-KbCQfvKA8DY1tQmT0Nm:b-utg5d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/internal/client/txn.go#L631)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`log.Fatalf(txn.Context`
</blockquote></details>

I think the stack trace in this case is more valuable than the context tags, particularly give that there's no good tags at this level.

---

*[pkg/internal/client/txn.go, line 536 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbC0bf1jbVri82_gjGH:-KbCQOju5phdf63gBK76:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f7a9a70e1a39c6d13c3d697ecbfa454fd363bd4/pkg/internal/client/txn.go#L536)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/terminated retryable error/retryable error from another transaction/
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 683 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHFU8RDdHh4HW8lEs:-KbCRMBpqAOA_HXCnDqb:b-sn6gvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/executor.go#L683)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

can just add `&& !txnState.txn.IsFinalized()` here
</blockquote></details>

no (or at least I don't understand what you mean). If we're doing "user-directed retries" (i.e. `SAVEPOINT COCKROACH_RESTART`...) then we can have a retryable error and `!txnState.txn.IsFinalized`.

---

*[pkg/sql/txn_restart_test.go, line 1223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBrvK7tknaTYbJuxoX:-KbCS96FqdQwFLOmhjnG:b-w3gvmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1223)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't really understand what this is trying to say.. seems like the test verifies that the error is bubbled up for this txn even if it's for a different (bogus) txn?
</blockquote></details>

the error should be bubbled up, yes. But not as a *retryable* error. So, the query should not be retried.

---

*[pkg/sql/txn_restart_test.go, line 1239 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCJz5SealHPLEsq79n:-KbCS_wCy-DtJ22I2Qrg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1239)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe use backquote like above for consistency
</blockquote></details>

Done.

---

*[pkg/sql/txn_restart_test.go, line 1242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCIIlx24Cs50cupm2H:-KbCShbQmFtI8lNCstcr:bys8vpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1242)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`%v` in case `err == nil`
</blockquote></details>

done, also changed to a more idiomatic message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/internal/client/txn.go, line 631 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHAu9cn7CclvZXavH:-KbC_Tp8ZdQcQUczSNZ4:bnz6bdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/internal/client/txn.go#L631)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the stack trace in this case is more valuable than the context tags, particularly give that there's no good tags at this level.
</blockquote></details>

Ah `Fatalf` doesn't dump a stack trace? Sad!

---

*[pkg/sql/executor.go, line 683 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHFU8RDdHh4HW8lEs:-KbCYt0UjJXW6himSrW-:b-z88kob) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/executor.go#L683)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no (or at least I don't understand what you mean). If we're doing "user-directed retries" (i.e. `SAVEPOINT COCKROACH_RESTART`...) then we can have a retryable error and `!txnState.txn.IsFinalized`.
</blockquote></details>

the condition below is `!(finalized || retryable)` which is the same as `!finalized && !retryable` (to me it's actually easier to reason about it in this form). We can simply move the `!finalized` check up..

---

*[pkg/sql/txn_restart_test.go, line 1223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBrvK7tknaTYbJuxoX:-KbCZg_768KGkPJqOjoa:b-w3nibk) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1223)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the error should be bubbled up, yes. But not as a *retryable* error. So, the query should not be retried.
</blockquote></details>

ah ok.  I would say "Test that if as part of a transaction A we receive a retryable error intended for a different transaction B, we don't retry transaction A."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028)*

**Comment by andreimatei** [comment]
Review status: 2 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 683 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbCHFU8RDdHh4HW8lEs:-KbCeVwk4rsmtDPqw3Oe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/executor.go#L683)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

the condition below is `!(finalized || retryable)` which is the same as `!finalized && !retryable` (to me it's actually easier to reason about it in this form). We can simply move the `!finalized` check up..
</blockquote></details>

Done.

---

*[pkg/sql/txn_restart_test.go, line 1223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028#-KbBrvK7tknaTYbJuxoX:-KbCehPNjD5GOoN5TAlT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716508b00d4405cc46d53efad5c79614b769802e/pkg/sql/txn_restart_test.go#L1223)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ah ok.  I would say "Test that if as part of a transaction A we receive a retryable error intended for a different transaction B, we don't retry transaction A."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13028)*

**Pull request merged**
