### PR TITLE
colexec: Add COCKROACH_RANDOMIZE_BATCH_SIZE env variable to colexec test suites

### PR DESCRIPTION
**Pull request by Azhng**
Added `COCKROACH_BATCH_SIZE` environment variable so we can set the batch size when running test or benchmark. 

Release note (sql_change): Batch size randomization in vectorize engine
tests and benchmarks can now be disabled using COCKROACH_RANDOMIZE_BATCH_SIZE
env variable.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I believe this change will deserve a release note.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-:-M-3-Br5EKaPagS67o-r:bo1an6i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/main_test.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-M-2zZKU6cSsyb7gh9gA:-M-2zZKU6cSsyb7gh9gB:bx8qjx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e7b59c771b5b2b2abaf39352b3da4fa9c3c3933/pkg/sql/colexec/main_test.go#L62)):*
> ```Go
> 	randomBatchSize := coldata.MinBatchSize +
> 		rng.Intn(coldata.MaxBatchSize-coldata.MinBatchSize)
> 	batchSize := envutil.EnvOrDefaultInt("COCKROACH_BATCH_SIZE", randomBatchSize)
> ```

I think I would prefer an environment variable that disables randomization (something like `COCKROACH_RANDOMIZE_BATCH_SIZE` which is a boolean). If that value is set to `true`, then we would use the default batch size (1024). It seems more intuitive to me - some users might not care about a particular batch size value but still wanted determinism in their benchmarks.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/main_test.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-M-2zZKU6cSsyb7gh9gA:-M-3-Mrw8AcYs1QmU1W5:bb3lsx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e7b59c771b5b2b2abaf39352b3da4fa9c3c3933/pkg/sql/colexec/main_test.go#L62)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I would prefer an environment variable that disables randomization (something like `COCKROACH_RANDOMIZE_BATCH_SIZE` which is a boolean). If that value is set to `true`, then we would use the default batch size (1024). It seems more intuitive to me - some users might not care about a particular batch size value but still wanted determinism in their benchmarks.
</blockquote></details>

*oops, `s/true/false/g`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/main_test.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-M-2zZKU6cSsyb7gh9gA:-M-5vP13BZO070P7TItj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e7b59c771b5b2b2abaf39352b3da4fa9c3c3933/pkg/sql/colexec/main_test.go#L62)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

*oops, `s/true/false/g`.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

[nit]: the commit title (and the PR title) should be updated as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-:-M-6U763DuCGbGjO2fGQ:boje0wa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/colexec/main_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-M-6TsNU9xSiwr_evCJ0:-M-6TsNU9xSiwr_evCJ1:b-9qqkle) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2d156c068f59fc961c18bf3326912974489d81/pkg/sql/colexec/main_test.go#L50)):*
> ```Go
> 		defer testMemAcc.Close(ctx)
> 		// Pick a random batch size in [coldata.MinBatchSize, coldata.MaxBatchSize]
> 		// range unless it is overridden by the COCKROACH_BATCH_SIZE env variable.
> ```

[nit]: the comment needs to be updated.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colexec/main_test.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-M-6TsNU9xSiwr_evCJ0:-M-84507EusZFcWXVilc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af2d156c068f59fc961c18bf3326912974489d81/pkg/sql/colexec/main_test.go#L50)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment needs to be updated.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44618#-:-M-AlCE033ByEuGb0unl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by Azhng** [comment]
TFTR!

bors r+

**Pull request merged**
