### PR TITLE
distsqlrun: reduce allocations in merge join

### LINKED ISSUE #24534: distsqlrun: reuse memory in streamGroupAccumulator
Currently, the `streamGroupAccumulator` returns a safe slice of `EncDatumRows` - once that slice is returned, the values in that slice will never be overwritten. As a consequence, the accumulator must continue to allocate new slices of `EncDatumRows` when moving on to a new group.

I believe this is unnecessary. As far as I can tell, the downstream consumers of `streamGroupAccumulator` always exhaust the entire slice of `EncDatumRow` objects (by rendering them into a different form, copying out their internal `EncDatums` and throwing away their reference to the `EncDatumRow`) before calling `streamGroupAccumulator.nextGroup` again.

As a consequence, we should be able to modify the `streamGroupAccumulator` to not have to continuously allocate more `EncDatumRow` slices and simply reuse one.

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #24534.

Previously, the streamGroupAccumulator returned a safe slice of
EncDatumRows that could be referenced forever. As a consequence, the
accumulator had to continue to allocate new slices of EncDatumRows when
moving on to a new group.

This copying and allocation is unnecessary, because downstream consumers
of streamGroupAccumulator don't reference the returned EncDatumRows
object past the next call to nextGroup.

Now, the streamGroupAccumulator simply reuses the EncDatumRow slices
instead of throwing them away.

```
name                           old time/op    new time/op    delta
MergeJoiner/InputSize=0-8        3.16µs ± 8%    3.08µs ± 1%     ~     (p=0.353 n=10+10)
MergeJoiner/InputSize=4-8        5.74µs ± 3%    5.77µs ± 2%     ~     (p=0.764 n=10+9)
MergeJoiner/InputSize=16-8       9.32µs ± 1%    9.30µs ± 1%     ~     (p=0.219 n=9+10)
MergeJoiner/InputSize=256-8      83.1µs ± 2%    77.8µs ± 1%   -6.39%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8     1.25ms ± 1%    1.17ms ± 2%   -6.82%  (p=0.000 n=10+10)
MergeJoiner/InputSize=65536-8    20.5ms ± 1%    18.8ms ± 1%   -8.12%  (p=0.000 n=10+10)

name                           old alloc/op   new alloc/op   delta
MergeJoiner/InputSize=0-8        4.42kB ± 0%    4.42kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=4-8        7.50kB ± 0%    7.50kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=16-8       9.03kB ± 0%    9.03kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=256-8      41.3kB ± 0%    32.1kB ± 0%  -22.32%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8      594kB ± 0%     401kB ± 0%  -32.57%  (p=0.000 n=10+10)
MergeJoiner/InputSize=65536-8    9.44MB ± 0%    6.30MB ± 0%  -33.29%  (p=0.000 n=10+10)

name                           old allocs/op  new allocs/op  delta
MergeJoiner/InputSize=0-8          14.0 ± 0%      14.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=4-8          16.0 ± 0%      16.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=16-8         17.0 ± 0%      17.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=256-8        38.0 ± 0%      32.0 ± 0%  -15.79%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8        398 ± 0%       272 ± 0%  -31.66%  (p=0.000 n=10+10)
MergeJoiner/InputSize=65536-8     6.16k ± 0%     4.11k ± 0%  -33.23%  (p=0.000 n=10+10)

name                           old speed      new speed      delta
MergeJoiner/InputSize=4-8      5.58MB/s ± 3%  5.54MB/s ± 2%     ~     (p=0.762 n=10+9)
MergeJoiner/InputSize=16-8     13.7MB/s ± 1%  13.8MB/s ± 1%     ~     (p=0.234 n=9+10)
MergeJoiner/InputSize=256-8    24.7MB/s ± 2%  26.3MB/s ± 1%   +6.83%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8   26.2MB/s ± 1%  28.1MB/s ± 2%   +7.32%  (p=0.000 n=10+10)
MergeJoiner/InputSize=65536-8  25.6MB/s ± 1%  27.9MB/s ± 1%   +8.85%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 37 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-L9Mqt_34DSIZEStNIwJ:-L9Mqt_34DSIZEStNIwK:b2v7e9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce4e157a77f30e35eb16916fd578829c3f9b84/pkg/sql/distsqlrun/stream_group_accumulator.go#L37)):*
> ```Go
> 	datumAlloc sqlbase.DatumAlloc
> 
> 	leftoverRow sqlbase.EncDatumRow
> ```

This needs a comment

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 50 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-L9MqvHy9sC5vSCxJKcg:-L9MqvHy9sC5vSCxJKch:b-3kpcez) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce4e157a77f30e35eb16916fd578829c3f9b84/pkg/sql/distsqlrun/stream_group_accumulator.go#L50)):*
> ```Go
> }
> 
> func (s *streamGroupAccumulator) nextGroup(
> ```

This needs a comment to say that the results are only usable until the next call to nextGroup

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535)*

**Comment by jordanlewis** [comment]
> Previously, the streamGroupAccumulator returned a safe slice of
> EncDatumRows that could be referenced forever. As a consequence, the
> accumulator had to continue to allocate new slices of EncDatumRows when
> moving on to a new group.
> 
> This copying and allocation is unnecessary, because downstream consumers
> of streamGroupAccumulator don't reference the returned EncDatumRows
> object past the next call to nextGroup.
> 
> Now, the streamGroupAccumulator simply reuses the EncDatumRow slices
> instead of throwing them away.
> 
<details><summary><i alt="summary">Quoted 30 lines of code…</i></summary>

> ```
> name                           old time/op    new time/op    delta
> MergeJoiner/InputSize=0-8        3.16µs ± 8%    3.08µs ± 1%     ~     (p=0.353 n=10+10)
> MergeJoiner/InputSize=4-8        5.74µs ± 3%    5.77µs ± 2%     ~     (p=0.764 n=10+9)
> MergeJoiner/InputSize=16-8       9.32µs ± 1%    9.30µs ± 1%     ~     (p=0.219 n=9+10)
> MergeJoiner/InputSize=256-8      83.1µs ± 2%    77.8µs ± 1%   -6.39%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=4096-8     1.25ms ± 1%    1.17ms ± 2%   -6.82%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=65536-8    20.5ms ± 1%    18.8ms ± 1%   -8.12%  (p=0.000 n=10+10)
> 
> name                           old alloc/op   new alloc/op   delta
> MergeJoiner/InputSize=0-8        4.42kB ± 0%    4.42kB ± 0%     ~     (all equal)
> MergeJoiner/InputSize=4-8        7.50kB ± 0%    7.50kB ± 0%     ~     (all equal)
> MergeJoiner/InputSize=16-8       9.03kB ± 0%    9.03kB ± 0%     ~     (all equal)
> MergeJoiner/InputSize=256-8      41.3kB ± 0%    32.1kB ± 0%  -22.32%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=4096-8      594kB ± 0%     401kB ± 0%  -32.57%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=65536-8    9.44MB ± 0%    6.30MB ± 0%  -33.29%  (p=0.000 n=10+10)
> 
> name                           old allocs/op  new allocs/op  delta
> MergeJoiner/InputSize=0-8          14.0 ± 0%      14.0 ± 0%     ~     (all equal)
> MergeJoiner/InputSize=4-8          16.0 ± 0%      16.0 ± 0%     ~     (all equal)
> MergeJoiner/InputSize=16-8         17.0 ± 0%      17.0 ± 0%     ~     (all equal)
> MergeJoiner/InputSize=256-8        38.0 ± 0%      32.0 ± 0%  -15.79%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=4096-8        398 ± 0%       272 ± 0%  -31.66%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=65536-8     6.16k ± 0%     4.11k ± 0%  -33.23%  (p=0.000 n=10+10)
> 
> name                           old speed      new speed      delta
> MergeJoiner/InputSize=4-8      5.58MB/s ± 3%  5.54MB/s ± 2%     ~     (p=0.762 n=10+9)
> MergeJoiner/InputSize=16-8     13.7MB/s ± 1%  13.8MB/s ± 1%     ~     (p=0.234 n=9+10)
> MergeJoiner/InputSize=256-8    24.7MB/s ± 2%  26.3MB/s ± 1%   +6.83%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=4096-8   26.2MB/s ± 1%  28.1MB/s ± 2%   +7.32%  (p=0.000 n=10+10)
> MergeJoiner/InputSize=65536-8  25.6MB/s ± 1%  27.9MB/s ± 1%   +8.85%  (p=0.000 n=10+10)
> ```
</details>


PTAL

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 37 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-L9Mqt_34DSIZEStNIwJ:-L9Rm9Ar693fmHtfKt-G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce4e157a77f30e35eb16916fd578829c3f9b84/pkg/sql/distsqlrun/stream_group_accumulator.go#L37)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This needs a comment
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 50 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-L9MqvHy9sC5vSCxJKcg:-L9Rm9RL-OL2M5CapIS7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce4e157a77f30e35eb16916fd578829c3f9b84/pkg/sql/distsqlrun/stream_group_accumulator.go#L50)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This needs a comment to say that the results are only usable until the next call to nextGroup
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-:-L9RmAxA93c-BfkD8Or4:b-y6vdn0)*

**Comment by asubiotto** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-:-L9et8ei83tADkfxFxXi:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24535#-:-L9f15Go26Fzs9-Cgert:bnfp4nl)*

**Pull request merged**
