### PR TITLE
colexec: minor miscellaneous additions

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add casts from datum-backed types to bools**

While investigating unrelated test failures, I added this cast, so we
might as well merge it.

Addresses: #48135.

Release note: None

**colexec: add support for Values core with zero rows**

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Is the first commit tested somewhere?

> Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-:-M9TYI7f08F9ahokGLAJ:b2jhd6q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 642 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-M9TXvdp-I4nfdXF39XS:-M9TXvdp-I4nfdXF39XT:b-degi0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c8c75f887c0c81126706707ef727625b049338/pkg/sql/colexec/execplan.go#L642)):*
> ```Go
> 				return result, err
> 			}
> 			if core.Values.NumRows != 0 {
> ```

What does supporting only this specific case give us vs implementing a full values operator?

**Review by yuzefovich — COMMENTED** [review]
Good point, extended the randomized test we have. Unfortunately, I don't remember exactly what prompted me to add the cast from datum-backed type to a boolean (probably it was a typed `NULL` with a `CASE` expression or something like that), and the only datum-backed type that has a valid cast to bool is Collated String which is probably not that useful of an addition. However, the first commit does lay some groundwork for future additions of casts from datum-backed types, so I think it's still worth merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-:-M9ZNsKT8rafmhiH7Yn2:b-eqo4ow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execplan.go, line 642 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-M9TXvdp-I4nfdXF39XS:-M9ZPSfWBLEY-TWKl1fP:bcmunpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/90c8c75f887c0c81126706707ef727625b049338/pkg/sql/colexec/execplan.go#L642)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What does supporting only this specific case give us vs implementing a full values operator?
</blockquote></details>

This particular case came up when there is a subquery that evaluates to an empty set. True, general values operator would be more useful, and I briefly looked into that, it was more than 5 minutes effort, so I didn't proceed since this limited addition was sufficient to debug the thing I was working on. I'll file an issue to add support for `Values` core.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-:-M9sEVqd44Y2nc52AKk0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/cast_test.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-M9sE5id4DP8MBbH5AiZ:-M9sE5ie35DgfKUPw10a:bx3mh9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0033cb461d43579d990f38311af9f943a892108f/pkg/sql/colexec/cast_test.go#L87)):*
> ```Go
> 		toPhysType   func(tree.Datum) interface{}
> 		// getValidSet (when non-nil) is a function that returns a set of valid
> 		// datums of fromTyp type that can be casted to toTyp type. The test
> ```

nit: `s/casted/cast`
___
*[pkg/sql/colexec/cast_test.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-M9sEA0CCy0niALb17UV:-M9sEA0CCy0niALb17UW:bsc6h8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0033cb461d43579d990f38311af9f943a892108f/pkg/sql/colexec/cast_test.go#L89)):*
> ```Go
> 		// datums of fromTyp type that can be casted to toTyp type. The test
> 		// harness will be randomly choosing a datum from this set. This
> 		// function should be specified when random generation using
> ```

nit: "should be specified when random generation"

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-:-M9suUFaCx5EuOQyWnie:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/cast_test.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50001#-M9sE5id4DP8MBbH5AiZ:-M9sttx2-ZQQExYaeIpR:brfioge) ([raw file](https://github.com/cockroachdb/cockroach/blob/0033cb461d43579d990f38311af9f943a892108f/pkg/sql/colexec/cast_test.go#L87)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/casted/cast`
</blockquote></details>

I actually looked up what is the correct form when writing this comment (which is `cast`), but the comment below already had `casted`, so I decided to use the incorrect form to be inline with the other comment :) Updated in both places.

**Comment by otan** [comment]
bors r-

i don't think this builds

**Comment by yuzefovich** [comment]
Indeed, it didn't. Sorry about that. A function's signature has been changed, but the rebase didn't notice any conflicts.

**Pull request merged**
