### PR TITLE
build: upgrade to golang v1.21.3

### LINKED ISSUE #112088: *: upgrade to go 1.21
We want go 1.21 to support crdb 23.2.

Jira issue: CRDB-32231

### PR DESCRIPTION
**Pull request by rickystewart**
* [ ] Adjust the Pebble tests to run in new version.
* [x] Adjust version in the TeamCity agent image ([setup script](./packer/teamcity-agent.sh))
* [x] Update `build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` with the new version and adjust SHA256 sums as necessary.
* [x] Adjust `GO_VERSION` and `GO_FIPS_COMMIT` for the FIPS Go toolchain ([source](./teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh)).
* [x] Run the `Internal / Cockroach / Build / Toolchains / Publish Patched Go for Mac` build configuration in TeamCity with your latest version of the script above. Note the job depends on another job `Build and Publish Patched Go`. That job prints out the SHA256 of all tarballs, which you will need to copy-paste into `WORKSPACE` (see below). `Publish Patched Go for Mac` is an extra step that publishes the *signed* `go` binaries for macOS. That job also prints out the SHA256 of the Mac tarballs in particular.
* [x] Adjust `--@io_bazel_rules_go//go/toolchain:sdk_version` in [.bazelrc](../.bazelrc).
* [x] Bump the version in `WORKSPACE` under `go_download_sdk`. You may need to bump [rules_go](https://github.com/bazelbuild/rules_go/releases). Also edit the filenames listed in `sdks` and update all the hashes to match what you built in the step above.
* [x] Bump the version in `WORKSPACE` under `go_download_sdk` for the FIPS version of Go (`go_sdk_fips`).
* [x] Run `./dev generate bazel` to refresh `distdir_files.bzl`, then `bazel fetch @distdir//:archives` to ensure you've updated all hashes to the correct value.
* [x] Bump the go version in `go.mod`.
* [x] Bump the default installed version of Go in `bootstrap-debian.sh` ([source](./bootstrap/bootstrap-debian.sh)).
* [x] Replace other mentions of the older version of go (grep for `golang:<old_version>` and `go<old_version>`).
* [ ] Ask the Developer Infrastructure team to deploy new TeamCity agent images according to [packer/README.md](./packer/README.md)

Closes #112088.

Epic: none
Release note (general change): Updated Go version to 1.21.3

### CODE REVIEW

**Review by rail — APPROVED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @rharding6373, and @srosenberg)

**Review by rharding6373 — APPROVED** [review]
:lgtm: for SQL Queries

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112349#-:-NhSnoxe8HL-TI1ZcalU:b-83w576)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @herkolategan, @rickystewart, and @srosenberg)

___
*[`pkg/sql/crdb_internal_test.go` line 1032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112349#-NhSnLqE-RPPiUoYWwnY:-NhSnLqE-RPPiUoYWwnZ:b40muip) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81faf9b1d8869e604604cb6b401439c211dc113/pkg/sql/crdb_internal_test.go#L1032)):*
> ```Go
> 	require.NoError(t, errUpdate)
> 	end := timeutil.Now()
> 	require.GreaterOrEqual(t, end.Sub(start), 499*time.Millisecond)
> ```

Do you know why it doesn't like 500? I don't think this is a big deal, but it's an interesting change.

**Comment by rickystewart** [comment]
> Do you know why it doesn't like 500? I don't think this is a big deal, but it's an interesting change.

I saw a failure (probably a flake) that was like: "expected current time to be 500ms + the original time, but it's only 499.6(something) seconds". I don't know how this works: if it ends up eventually shelling out to a `go` runtime function, maybe the way that function figures out how long to sleep was updated in 1.21. Either way this solves the flake.

**Comment by rickystewart** [comment]
TFTR!

bors r=rail,rharding6373

**Pull request merged**
