### PR TITLE
Reapply "bootstrap: create an explicit zoneconfig for timeseries data"

### LINKED ISSUE #123762: sql: explicit zone configuration for the timeseries range on a new cluster
**Is your feature request related to a problem? Please describe.**
When a cluster is created, we create a zone configuration for the default zone as well as for most of the "special" ranges that are documented here: https://www.cockroachlabs.com/docs/v23.2/configure-replication-zones#create-a-replication-zone-for-a-system-range. The only system range we don't explicitly create a zone config for is the `timeseries` range. 

After a test cluster is created, it has the following configurations defined:
```
> select target from [show all zone configurations];
                       target
----------------------------------------------------
  RANGE default
  DATABASE system
  TABLE system.public.lease
  RANGE meta
  RANGE system
  RANGE liveness
  TABLE system.public.replication_constraint_stats
  TABLE system.public.replication_stats
  TABLE system.public.statement_statistics
  TABLE system.public.transaction_statistics
  TABLE system.public.tenant_usage
  TABLE system.public.span_stats_tenant_boundaries
  TABLE system.public.statement_activity
  TABLE system.public.transaction_activity
(14 rows)
```
Note that the 3 ranges for `meta`, `system`, and `liveness` have explicit zone configs, but `timeseries` doesn't`. 

**Describe the solution you'd like**
On a system creation, we should create an explicit `timeseries` zone config that exactly matches the `RANGE default` zone config. This would prevent confusion and allow users to make the right decisions on what RF they want. Otherwise users who don't carefully read the documentation are not likely to consider this range. 

**Describe alternatives you've considered**
1) We could just leave the system as it is. The default zone config change and the documentation may be sufficient.
2) We could have the timeseries range use the `system` configuration if there isn't a more explicit one set.

**Additional context**
In a test cluster where all the "visible" zone configurations were set with RF=5 and two nodes were brought down, we had a LoQ event for some of the timeseries ranges. This was confusing to debug since it required figuring out that the timeseries range was not included.  

Jira issue: CRDB-38531

Epic CRDB-40419

### PR DESCRIPTION
**Pull request by rafiss**
This partially reverts commit f9d47ce1c0165e9b2696fd65d0bfc9a8db94d340.

This time, rather than copying over the full zone config for the default range to the timeseries range, we only copy over gc.ttlseconds. This means that other attributes, most notably the replication factor, will be inherited from the default range.

This will make it more clear that the timeseries zone config can be changed independently from all the other zone configs.

fixes https://github.com/cockroachdb/cockroach/issues/123762

Release note (ops change): New clusters that are initialized for the first time will now have a zone config defined for the `timeseries` range. This zone config only specifies the gc.ttlseconds, so all the other attributes are inherited from the zone config of the `default` range, as they were before.

Clusters that are upgraded to v24.3 from a previous version will also
have this zone configuration applied to the timeseries range, as long as
that range does not already have a zone config.

### CODE REVIEW

**Comment by rafiss** [comment]
I started a roachtest run here to make sure the test passes without needing any changes (last time https://github.com/cockroachdb/cockroach/pull/127618 was needed, which is undesirable).

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16293779?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by arulajmani — COMMENTED** [review]
:lgtm: modulo comments. 

@rafiss did you have thoughts on whether this change needs to come with a migration or not? I don't have strong feelings either way, but as is, this introduces a difference between clusters that are bootstrapped on 24.3 and clusters that were upgraded to it. cc @andrewbaptist maybe you have thoughts here as well.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-:-O3i9kWN4KmrdaLv4asv:b-h44kfl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/gossip.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O3i8tPt5H9O3K3RGu8w:-O3i8tPt5H9O3K3RGu8x:bc6lw8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce996672ac08c312924cfbaeb37877e2c255a97c/pkg/cmd/roachtest/tests/gossip.go#L403)):*
> ```Go
> 	run(`ALTER RANGE meta %[1]s CONFIGURE ZONE %[2]s 'constraints: {"-rack=0"}'`)
> 	run(`ALTER RANGE liveness %[1]s CONFIGURE ZONE %[2]s 'constraints: {"-rack=0"}'`)
> 	run(`ALTER RANGE timeseries %[1]s CONFIGURE ZONE %[2]s 'constraints: {"-rack=0"}'`)
> ```

Do we need this change? Would we expect `RANGE DEFAULT`s constraints to apply to `timeseries` as well?

**Review by rafiss — COMMENTED** [review]
> did you have thoughts on whether this change needs to come with a migration or not?

I felt like it was safer not to include a migration. If a customer has already configured the timeseries range (which we may very well have advised them to do while supporting them), then running an upgrade migration would not be safe, or at best, would be surprising since it would clear out any customizations they have made.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-:-O3iBwyX87Q_bqfxCucs:bytso2a)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @arulajmani, @DarrylWong, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/gossip.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O3i8tPt5H9O3K3RGu8w:-O3iCHSx1f1ET35hAAU7:b1desdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce996672ac08c312924cfbaeb37877e2c255a97c/pkg/cmd/roachtest/tests/gossip.go#L403)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need this change? Would we expect `RANGE DEFAULT`s constraints to apply to `timeseries` as well?
</blockquote></details>

this change was needed to make this test pass. 

for that matter, the line for `TABLE system.public.replication_stats` also is needed, even though the zone config for that table also does not specify any constraints and should inherit.

there must be something in this test setup that ends up requiring each zone config to be updated.

**Review by arulajmani — COMMENTED** [review]
> If a customer has already configured the timeseries range (which we may very well have advised them to do while supporting them), then running an upgrade migration would not be safe, or at best, would be surprising since it would clear out any customizations they have made.

I was imagining that the migration wouldn't modify anything if the `timeseries` range was unset; we'd only add this explicit entry in `system.zones` if there wasn't one already. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-:-O3mul-I-w56OHTrLjIa:borlqeq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, and @renatolabs)

**Comment by rafiss** [comment]
> I was imagining that the migration wouldn't modify anything if the timeseries range was unset; we'd only add this explicit entry in system.zones if there wasn't one already.

I've added a migration that does this. PTAL.

**Review by arulajmani — COMMENTED** [review]
Looks good, modulo question about backup/restore. 

> Reviewed 2 of 3 files at r2, 17 of 17 files at r4, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-:-O4LnoFD4gNaDYxL5cKN:bsorpvc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O4LlR8D1T3uFbL3nnRS:-O4LlR8D1T3uFbL3nnRT:b-w4h2aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a08397a98e37ee34c1f1dace3ccc5b4533a9be32/pkg/upgrade/upgrades/upgrades.go#L107)):*
> ```Go
> 		clusterversion.V24_3_AddTimeseriesZoneConfig.Version(),
> 		addTimeseriesZoneConfig,
> 		upgrade.RestoreActionNotRequired("this zone config isn't necessary for restore"),
> ```

I may be missing something, but I would have expected there to be a need to add this zone configuration on the restore path as well. My understanding was that we backup and restore zone configurations, so we'd need to do handle adding this zone configuration on the restore path as well.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @DarrylWong, and @renatolabs)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O4LlR8D1T3uFbL3nnRS:-O4M6AebD6IMlkcy3ORj:b-72sd72) ([raw file](https://github.com/cockroachdb/cockroach/blob/a08397a98e37ee34c1f1dace3ccc5b4533a9be32/pkg/upgrade/upgrades/upgrades.go#L107)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I may be missing something, but I would have expected there to be a need to add this zone configuration on the restore path as well. My understanding was that we backup and restore zone configurations, so we'd need to do handle adding this zone configuration on the restore path as well.
</blockquote></details>

i assumed we didn't do that during restores, since the current restore logic also does not add in zone configs for other ranges/objects that may not have zone configs in old versions. for example, it doesn't add in zone configs for the system database or other tables that have zone configs added at bootstrap: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/bootstrap/metadata.go#L537-L541

right now it just copies the zones configs from whatever is in the backup.

i can easily change it to add the timeseries zone config, if we want to treat it differently for some reason. let me know what you think makes sense.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

Thanks for continuing to push on this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-:-O4MGMqj6H13JNJ8Lesj:b6kq3eo)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O4LlR8D1T3uFbL3nnRS:-O4MFZiX9BCH2bxUhbh3:b-sva5qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a08397a98e37ee34c1f1dace3ccc5b4533a9be32/pkg/upgrade/upgrades/upgrades.go#L107)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i assumed we didn't do that during restores, since the current restore logic also does not add in zone configs for other ranges/objects that may not have zone configs in old versions. for example, it doesn't add in zone configs for the system database or other tables that have zone configs added at bootstrap: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/bootstrap/metadata.go#L537-L541

right now it just copies the zones configs from whatever is in the backup.

i can easily change it to add the timeseries zone config, if we want to treat it differently for some reason. let me know what you think makes sense.
</blockquote></details>

Ack. I don't think there's a good reason to treat this differently. I'm just surprised that's how the current restore logic behaves. Would you mind filing an issue with DR if you agree?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @arulajmani, @DarrylWong, and @renatolabs)

___
*[`pkg/upgrade/upgrades/upgrades.go` line 107 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O4LlR8D1T3uFbL3nnRS:-O4MZnkc3L3fabGxDG1Y:b-dk16e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a08397a98e37ee34c1f1dace3ccc5b4533a9be32/pkg/upgrade/upgrades/upgrades.go#L107)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Ack. I don't think there's a good reason to treat this differently. I'm just surprised that's how the current restore logic behaves. Would you mind filing an issue with DR if you agree?
</blockquote></details>

sure thing! filed https://github.com/cockroachdb/cockroach/issues/129084

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128032)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @DarrylWong, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/gossip.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128032#-O3i8tPt5H9O3K3RGu8w:-O4Mpvut40N9QarbYXql:b7jk9cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce996672ac08c312924cfbaeb37877e2c255a97c/pkg/cmd/roachtest/tests/gossip.go#L403)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this change was needed to make this test pass. 

for that matter, the line for `TABLE system.public.replication_stats` also is needed, even though the zone config for that table also does not specify any constraints and should inherit.

there must be something in this test setup that ends up requiring each zone config to be updated.
</blockquote></details>

actually, i tracked this down too -- by initializing the zone config with `zonepb.NewZoneConfig()` rather than with `&zonepb.ZoneConfig{}` in the bootstrap code, we get the proper inheritance, so this test change isn't needed after all.

**Comment by rafiss** [comment]
TFTR!

bors r+

**Pull request merged**
