### PR TITLE
Fix filter component on 20.2 backport

### PR DESCRIPTION
**Pull request by Santamaura**
**What was there before:** Previously, cc console had a bug where the filter component had misalignments in the dropdowns
**Why was the change needed:** This made the ui look unaesthetic and hard to use
**What you did about it:** This was fixed by bumping react-select to ver 4.0.16 and adding some overriding styling to the component

ui: fix styling on filter component for cc console
Jira: [CC-4421](https://cockroachlabs.atlassian.net/browse/CC-4421)

### CODE REVIEW

**Comment by nathanstilwell** [comment]
So along with the code changes, if there is an upgrade to `react-select` you will need to follow the instructions in the [README](https://github.com/cockroachdb/cockroach/tree/master/pkg/ui#managing-dependencies) to upgrade the dependency in `yarn-vendored`.

To publish these changes, you will also need to "bump" the version of `cluster-ui` on this branch (read more about it [here](https://github.com/nathanstilwell/cockroach/blob/cluster-ui-publishing-help/pkg/ui/cluster-ui/README.md)). I think changing [the version](https://github.com/cockroachdb/cockroach/blob/release-20.2/pkg/ui/cluster-ui/package.json#L3) to `20.2.1` should do it.

**Comment by Santamaura** [comment]
PR for upgrading the `yarn-vendored` here: https://github.com/cockroachdb/yarn-vendored/pull/77

**Comment by Santamaura** [comment]
I have the PR up for upgrading `yarn-vendored` + did the bump @nathanstilwell let me know if its done correctly

**Comment by nathanstilwell** [comment]
The version bump looks good, but you will need to add the submodule update for `yarn-vendored`. When you updated the dependencies, the SHA should have changed. You need to add that change so the build can find the right dependencies.

**Review by nathanstilwell — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 2 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66566)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @Santamaura)

___
*[pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66566#-MdNB3ytC6VyqjxA0oZS:-MdNB3yu3Y3BPdVehbeC:b-q5tui5) ([raw file](https://github.com/cockroachdb/cockroach/blob/25d2c1f2d9002ac0a37c156dd3e922f3e413e3a7/pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx#L176)):*
> ```XML
>               options={appNames}
>               onChange={e => this.handleChange(e, "app")}
>               value={appNames.filter(app => app.label == filters.app)}
> ```

In JavaScript when comparing things, the _strict equality operator_ (`===`) should always be used. The discussion of _why_ is a **whole thing** and I would love to talk about it for hours, but for the sake of this review I will simply say we should **never** use `==` when writing JavaScript / TypeScript.

**Comment by nathanstilwell** [comment]
We are so close @Santamaura 😄 . I finally reviewed the code now that we have a green build. I'm not sure how to comment on the submodule changes in Reviewable, so you are getting a bit of a double review.

One thing I noticed about the changes coming in from the `yarn-vendored` change is that `@types/react-select@1.3.5` isn't included in `yarn-vendored` even though that version is specified in the `yarn.lock`. Also, do we need `@types/react-select@4.0.1` included for these changes? I think there may need to do one more minor update to `yarn-vendored` here.

**Review by Santamaura — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66566)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66566#-MdNB3ytC6VyqjxA0oZS:-MdNThde4pzz_Cc81Fm7:b-uhwuco) ([raw file](https://github.com/cockroachdb/cockroach/blob/25d2c1f2d9002ac0a37c156dd3e922f3e413e3a7/pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx#L176)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

In JavaScript when comparing things, the _strict equality operator_ (`===`) should always be used. The discussion of _why_ is a **whole thing** and I would love to talk about it for hours, but for the sake of this review I will simply say we should **never** use `==` when writing JavaScript / TypeScript.
</blockquote></details>

Done. It's worth mentioning these code changes were extracted from master so we should probably change this there as well.

**Comment by Santamaura** [comment]
For the `yarn-vendor` changes 1. `@types/react-select@1.3.5` may not show up in changes but I do notice it is already included. 2. I have removed the `@types/react-select@4.0.1` change.

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66566)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @nathanstilwell)

**Comment by nathanstilwell** [comment]
___
*[pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66566#-MdNB3ytC6VyqjxA0oZS:-MdXXGtv65aF1ASjS3D9:b6rhiqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/25d2c1f2d9002ac0a37c156dd3e922f3e413e3a7/pkg/ui/cluster-ui/src/transactionsPage/filter/filter.tsx#L176)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Done. It's worth mentioning these code changes were extracted from master so we should probably change this there as well.
</blockquote></details>

Noted. I commented on one of Marylia's PRs where I saw it as well.

**Comment by nathanstilwell** [comment]
:shipit: Post merge todo list,

- merge `yarn-vendored` PR
- publish `@cockrorachlabs/cluster-ui@20.2.1`

**Pull request merged**
