### PR TITLE
backupccl: avoid RAID0ing local NVMe and GP3 storage in restore roachtests

### LINKED ISSUE #97019: roachtest: restore/tpce/8TB/aws/nodes=10/cpus=8 failed
roachtest.restore/tpce/8TB/aws/nodes=10/cpus=8 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/8674346?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/8674346?buildTab=artifacts#/restore/tpce/8TB/aws/nodes=10/cpus=8) on master @ [2a7edbeb0737b1309064c25c641a309c2980d9ba](https://github.com/cockroachdb/cockroach/commits/2a7edbeb0737b1309064c25c641a309c2980d9ba):

```
test artifacts and logs in: /artifacts/restore/tpce/8TB/aws/nodes=10/cpus=8/run_1
(monitor.go:127).Wait: monitor failure: monitor task failed: full test specs: restore/tpce/8TB/inc-count=48/aws/nodes=10/cpus=8/volSize=2000GB: output in run_163914.880098375_n1_cockroach-sql-insecu: ./cockroach sql --insecure -e "RESTORE FROM LATEST IN 's3://cockroach-fixtures/backups/tpc-e/customers=500000/v22.2.1/inc-count=48?AUTH=implicit' AS OF SYSTEM TIME '2023-01-05 20:45:00'" returned: COMMAND_PROBLEM: ssh verbose log retained in ssh_163914.888338965_n1_cockroach-sql-insecu.log: exit status 1
```
<p>Parameters: <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=8</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*restore/tpce/8TB/aws/nodes=10/cpus=8.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by msbutler**
A long restore roachtest perf investigation revealed that roachprod can RAID0 local storage and AWS GP3 storage, a configuration that does not mix well with CRDB and does not reflect a reasonable customer environment. This patch avoids this RAID0ing in the restore roachtests, stabilizing test performance.

Informs #98783

Fixes #97019

Release note: none

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99723#-:-NRhSCgm10rUQBtPoOOQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lidorcarmel, @msbutler, and @smg260)

___
*[`pkg/cmd/roachtest/tests/restore.go` line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99723#-NRhS2pS0RTOs3fBmLMX:-NRhS2pS0RTOs3fBmLMY:bexjzhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/998cd43aff5a4ebf464145be86a2fc1ce2906b04/pkg/cmd/roachtest/tests/restore.go#L420)):*
> ```Go
> 		// https://github.com/cockroachdb/cockroach/issues/98783.
> 		//
> 		// This should be removed once we have found a real solution that avoids
> ```

Could you prefix the comment with `TODO`; it will be easier to find.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99723)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lidorcarmel, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/restore.go` line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99723#-NRhS2pS0RTOs3fBmLMX:-NRhX6UoARQ-iBdXPo6h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/998cd43aff5a4ebf464145be86a2fc1ce2906b04/pkg/cmd/roachtest/tests/restore.go#L420)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Could you prefix the comment with `TODO`; it will be easier to find.
</blockquote></details>

Done.

**Comment by msbutler** [comment]
TFTR!

bors r=srosenberg

**Comment by rail** [comment]
Looks like this PR made Roachtest AWS [panic](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/9353427?buildTab=log&focusLine=2676&expandAll=true) - `panic: low memory per CPU not available for AWS`

**Comment by msbutler** [comment]
I know what's going on. It's sad. Easy fix coming shortly.

**Pull request merged**
