### PR TITLE
storage: return error from {MVCC,Engine}Iterator.Value

### PR DESCRIPTION
**Pull request by sumeerbhola**
Informs cockroachdb/pebble#1170

Epic: CRDB-20378

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
`pkg/sql` changes LGTM

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94025#-:-NJpljO2CmzPMGnb89gQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @msbutler)

**Comment by sumeerbhola** [comment]
TFTRs!

**Comment by sumeerbhola** [comment]
bors r=mgartner,nicktrav

**Pull request merged**
