### PR TITLE
uuid: avoid using deprecated math/rand.Read

### LINKED ISSUE #110597: util/uuid: move to a non-deprecated randomness source
This usage of math/rand is deprecated as of go1.20: https://github.com/cockroachdb/cockroach/blob/f80ec9c292d43676d739fffabc847fb8b3195396/pkg/util/uuid/uuid_wrapper.go#L112-L118

https://pkg.go.dev/math/rand#Read
> Read generates len(p) random bytes from the default Source and writes them into p. It always returns len(p) and a nil error. Read, unlike the Rand.Read method, is safe for concurrent use.
>
> Deprecated: For almost all use cases, crypto/rand.Read is more appropriate. 

However, using crypto/rand has previously been shown to be a performance issue. See https://github.com/cockroachdb/cockroach/issues/30236#issuecomment-434588162 for that investigation.

For now, we will stick with the deprecated usage, but eventually we will have to update it.

Also note that go 1.21 (which we do not use as of 2023-09-13) includes this change, which improves the performance of math/rand: https://github.com/golang/go/commit/0b9974d3f09fe3132b4bc4aef67b839e3f84a8c8

We may want to use something similar to that, since UUID generation is something that can happen with high concurrency. Before the aforementioned go1.21 change, `math/rand.Read` was synchronized around a single mutex.

### PR DESCRIPTION
**Pull request by rafiss**
Now we generate uint64s instead and populate them into the UUID array.

```
goos: darwin
goarch: arm64
              │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.0cde11b885a │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.fbea7746013 │
              │                                      sec/op                                       │                          sec/op                            vs base                │
FastMakeV4-10                                                                         22.20n ± 0%                                                 28.34n ± 1%  +27.69% (p=0.000 n=10)

              │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.0cde11b885a │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.fbea7746013 │
              │                                       B/op                                        │                             B/op                               vs base            │
FastMakeV4-10                                                                          0.000 ± 0%                                                      0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal

              │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.0cde11b885a │ /var/folders/p3/c61_z_vd3r7dr1_hnztm3ryr0000gq/T/tmp.BIfUofSiKJ/bench.fbea7746013 │
              │                                     allocs/op                                     │                           allocs/op                            vs base            │
FastMakeV4-10                                                                          0.000 ± 0%                                                      0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```

fixes https://github.com/cockroachdb/cockroach/issues/110597
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
@bdarnell I gave this a shot, and it made the function ~28% slower. Is there a faster way to populate the backing UUID array?

**Comment by bdarnell** [comment]
I don't think there's a faster way to populate the array; I checked on godbolt.org and the encoding/binary functions appear to get inlined away. It must be a difference between the two calls to Uint64 vs one call to Read. Maybe because there are two lock acquisitions now? (Maybe. I also see references to a non-locking fast path in the math/rand source code but I haven't dug down to exactly what's happening)

Anyway, that's a pretty steep performance penalty just to avoid a deprecated function so I think I'd just leave it alone for now. Maybe a non-deprecated Read method (with a different name) will come back in the revised math/rand API.

**Comment by rafiss** [comment]
>  I also see references to a non-locking fast path in the math/rand source code but I haven't dug down to exactly what's happening

Were you referring to this change: https://github.com/golang/go/commit/0b9974d3f09fe3132b4bc4aef67b839e3f84a8c8? If so, that's only available in go1.21.

---

Anyway, for now I will close this out and leave the linked issue open.

**Comment by bdarnell** [comment]
Ah yes, that's what I saw.

**Comment by rafiss** [comment]
I created https://github.com/cockroachdb/cockroach/pull/110670 since working in this area made me see other worthwhile cleanups

**Pull request closed without merging**
