### PR TITLE
opt: avoid generating unqualified errors

### PR DESCRIPTION
**Pull request by knz**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @knz, and @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37767#-Lf_3qml9PuOiUdTpgrO:-Lf_3qml9PuOiUdTpgrP:b-tkdrlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/166db28e14e6e49cb15f4db1619698e1f13f9554/pkg/sql/opt/optbuilder/select.go#L458)):*
> ```Go
> 
> 		if _, ok := outScope.ctes[name.String()]; ok {
> 			panic(pgerror.Newf(
> ```

Shouldn't these be wrapped in `buildeError` as well?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37767#-Lf_3qml9PuOiUdTpgrO:-Lf_4OgA-Ns8F_cAREV8:b-om0xl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/166db28e14e6e49cb15f4db1619698e1f13f9554/pkg/sql/opt/optbuilder/select.go#L458)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Shouldn't these be wrapped in `buildeError` as well?
</blockquote></details>

No the builder panic catcher makes a special case for pgerror.Error.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @knz, and @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37767#-Lf_3qml9PuOiUdTpgrO:-Lf_D4vM0xZpz9Aa3wmv:b-pmwy0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/166db28e14e6e49cb15f4db1619698e1f13f9554/pkg/sql/opt/optbuilder/select.go#L458)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

No the builder panic catcher makes a special case for pgerror.Error.
</blockquote></details>

Then why do we need to wrap `UnimplementedWithIssueDetailf` into a `builderError`?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37767#-Lf_3qml9PuOiUdTpgrO:-Lf_Ff0fA37Z9AEVePGD:bqtses7) ([raw file](https://github.com/cockroachdb/cockroach/blob/166db28e14e6e49cb15f4db1619698e1f13f9554/pkg/sql/opt/optbuilder/select.go#L458)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Then why do we need to wrap `UnimplementedWithIssueDetailf` into a `builderError`?
</blockquote></details>

Oh good catch. We don't! removed.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Thanks for the fixes!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37767#-:-Lf_HgKD4A0wHe1pDL1W:boz7px3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
