### PR TITLE
jobs: avoid errors related to fraction completed

### PR DESCRIPTION
**Pull request by stevendanna**
See individual commits for details.

### CODE REVIEW

**Review by dt — APPROVED** [review]
Maybe we only backport the first?

**Comment by stevendanna** [comment]
@dt Exactly. I'll take the labels off so we don't get automatic backports as I plan to do them manually.

**Comment by stevendanna** [comment]
bors r=dt

**Comment by stevendanna** [comment]
I think this will help get this through CI: https://github.com/cockroachdb/cockroach/pull/122799

**Comment by stevendanna** [comment]
bors retry

**Pull request merged**
