### PR TITLE
sql/contention: turn on sql.contention.record_serialization_conflicts…

### PR DESCRIPTION
**Pull request by xinhaoz**
….enabled

Turn on sql.contention.record_serialization_conflicts.enabled by default and make this setting public.

Release note (ops change): The cluster setting
sql.contention.record_serialization_conflicts.enabled is now on by default. This means any 40001 errors that are returned containing conflicting transaction information will be recorded by the contention registry.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
does this turn on certain collections (e.g. traces) that it wouldn't with the setting off? Curious if turning on by default can cause performance degradation 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116664#-:-NlxaGEF5L6suVvPc52h:b-ocuq9z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @koorosh)

**Review by xinhaoz — COMMENTED** [review]
@maryliag No, it just allows the information to be recorded by the contention registry when it is available. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116664#-:-NlyAPGUDTZFVYaTwfwH:bfr26zo)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @koorosh)

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116664#-:-NlyD5_t9v2Cp4uvd-L7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @koorosh)

**Pull request merged**
