### PR TITLE
opt: derive constant computed columns for index selection

### PR DESCRIPTION
**Pull request by andy-kimball**
The optimizer uses explicitly specified filter constraints to qualify
available indexes during the exploration phase. It also uses implicit
filter constraints derived from table check constraints.

This commit adds new implicit filter constraints based on constant
computed columns. Constant computed columns are based on other columns in
the table that are constrained to be constant by other filters. For
example:

  CREATE TABLE hashed (
    k STRING,
    hash INT AS (fnv32(k) % 4) STORED,
    INDEX hash_index (hash, k)
  )

  SELECT * FROM hashed WHERE k = 'andy'

Here, the value of the hash column can be computed at query build time,
and therefore "hash_index" selected as the lowest cost index. The resulting
plan would be:

  scan hashed@secondary
   ├── columns: k:1(string!null) hash:2(int)
   ├── constraint: /2/1/3: [/1/'andy' - /1/'andy']
   └── fd: ()-->(1)

This improved ability to select indexes is useful for implementing HASH
indexes, which scatter keys across N buckets (see Issue #39340).

Release note (sql change): The optimizer can now derive constant computed
columns during index selection. This enables more efficient HASH indexes.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Very cool functionality and the code is very clean! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-:-LwukJlu7AFLeBiL_bpF:bvkfjg4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/constraint/span.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwfVWQTB8VEgVKeRbO7:-LwfVWQU4Lxqovi7tFXH:b-ii5bq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/constraint/span.go#L76)):*
> ```Go
> // the start key is the same as the end key, and both boundaries are inclusive.
> func (sp *Span) HasSingleKey(evalCtx *tree.EvalContext) bool {
> 	if sp.start.IsEmpty() || sp.end.IsEmpty() {
> ```

[nit] if we move the Length check first, we only need to check one of these
___
*[pkg/sql/opt/xform/custom_funcs.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwujbQG8D5YVlmr1tMw:-LwujbQG8D5YVlmr1tMx:b-sotyad) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/xform/custom_funcs.go#L567)):*
> ```Go
> 	}
> 
> 	var replace func(e opt.Expr) opt.Expr
> ```

Calling `Replace` when we don't end up folding to a constant can create a bunch of garbage. We could do these checks first using the OuterCols of the scalar expression, and only then call `Replace` (when we know for sure that all outer cols are in `constCols`)

**Review by RaduBerinde — COMMENTED** [review]
There's some interaction between this and #43405 (we need to handle these new expressions). I'm happy to update my PR once this goes in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-:-LwulMCKD0DvBjoZE9mP:b-321gkc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43450)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwujbQG8D5YVlmr1tMw:-Lwxq05X82c9dENonekb:b-13gpas) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/xform/custom_funcs.go#L567)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Calling `Replace` when we don't end up folding to a constant can create a bunch of garbage. We could do these checks first using the OuterCols of the scalar expression, and only then call `Replace` (when we know for sure that all outer cols are in `constCols`)
</blockquote></details>

Checking outer columns is a bit of a pain in this context, because we don't have props for the expression; we'd need to walk the expression to gather them.

I'll point out that there's only unnecessary garbage in the case where we perform at least one variable replacement, but then can't fully fold the entire expression. I'd think that was an edge case, like if there are multiple variables, or if there is a side-effecting function. If we can fold at least one variable in the expression, then it's likely the entire expression can be folded (since vast majority of check expressions ref a single variable).

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/xform/custom_funcs.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwujbQG8D5YVlmr1tMw:-Lwzo0ga2jSvxYcNPLgW:b-8rdkus) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/xform/custom_funcs.go#L567)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Checking outer columns is a bit of a pain in this context, because we don't have props for the expression; we'd need to walk the expression to gather them.

I'll point out that there's only unnecessary garbage in the case where we perform at least one variable replacement, but then can't fully fold the entire expression. I'd think that was an edge case, like if there are multiple variables, or if there is a side-effecting function. If we can fold at least one variable in the expression, then it's likely the entire expression can be folded (since vast majority of check expressions ref a single variable).
</blockquote></details>

It will try to construct existing expressions, right? Last time I looked at the factory code, it seemed like it would allocate in that case as well (but maybe I'm wrong?)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43450)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwujbQG8D5YVlmr1tMw:-LwzpbDaDzT5Ut7Fdo-d:bywws80) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/xform/custom_funcs.go#L567)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It will try to construct existing expressions, right? Last time I looked at the factory code, it seemed like it would allocate in that case as well (but maybe I'm wrong?)
</blockquote></details>

The `CopyAndReplace` methods will first copy, then replace. The `Replace` methods will only copy the parent if at least one child has been replaced.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/xform/custom_funcs.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-LwujbQG8D5YVlmr1tMw:-Lwzpcu37ZtIngUnOm3j:b-1y0b2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc43a533f9e2b6609b6a382760192c5f59f7082/pkg/sql/opt/xform/custom_funcs.go#L567)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The `CopyAndReplace` methods will first copy, then replace. The `Replace` methods will only copy the parent if at least one child has been replaced.
</blockquote></details>

Ah, nice.

**Review by rytaft — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43450)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 558 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-Lx2i_6H4z9j8_6WAAY9:-Lx2i_6H4z9j8_6WAAYA:b-kr8l9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfa5e8fec55d0d7609b1512d9f5bdb1a192ba54/pkg/sql/opt/xform/custom_funcs.go#L558)):*
> ```Go
> // ID into a constant value, by evaluating it with respect to a set of other
> // columns that are constant. If the computed column is constant, enter it into
> // the constCols map and return false. Otherwise, return false.
> ```

[nit] I think you meant "enter it into the constCols map and return true"
___
*[pkg/sql/opt/xform/testdata/rules/computed, line 102 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43450#-Lx2jOyYAusUDj-Bvm8g:-Lx2jOyYAusUDj-Bvm8h:b8b25vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfa5e8fec55d0d7609b1512d9f5bdb1a192ba54/pkg/sql/opt/xform/testdata/rules/computed#L102)):*
> ```
>       └── (k_int = 2) OR (k_int = 3) [type=bool, outer=(1), constraints=(/1: [/2 - /2] [/3 - /3])]
> 
> # Don't constrain the index for a NULL value.
> ```

Why not?

**Pull request merged**
