### PR TITLE
sql: lease acquisition of OFFLINE descs may starve bulk operations

### LINKED ISSUE #61798: sql/catalog/lease: high priority reads in lease acquisition of OFFLINE descs may starve bulk operations
**Describe the problem**

In (#46170, #46384) we made changes to use high priority read transaction in lease acquisitions in order to break deadlocks. This solution isn't wonderful: if users use `PRIORITY HIGH` on their DDL transactions, they can still hit these deadlocks. Given people tend not to do that, this proved to be a pretty good and pragmatic solution to a very serious problem. 

When code attempts to resolve descriptors it goes through the leasing mechanism. This is true even if the descriptor does not exist. This is made much worse in a case where you've got a multi-region cluster.

The scenario that causes specific pain is when you've got an application running and trying to hit some tables but you're in the process of restoring those tables. As part of the restore, we need to update the descriptors. If the restore job is far from the descriptor table leaseholder, then there's a long period of time for interceding queries to push the intent. After getting pushed, the query will need to refresh. If the pushing is happening more frequently than the refresh's duration, we'll get stuck in livelock. 

For what it's worth, all of this is modestly speculative. We saw the pushing but I don't know that we've captured enough data.

**To Reproduce**

In theory, start a restore in a global cluster and get the leaseholder on the system config span in a different region than the restore coordinator. Then spam the database being restored and see if you can hold off the restore.

**Some ideas**

* We could lease and cache the offline descriptor. This is probably the most compelling choice. It's not too hard. 
* We could make the lease acquisition low priority and fall back to reading from the store (probably not a good idea).
* We could get rid of the high priority hack altogether with some work involving child transactions (see #54633).

**Expected behavior**

The restore finishes.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #61798

Previously, offline descriptors would never have their leases
cached and they would be released once the reference count hit zero.
This was inadequate because when attempting to online these tables
again the lease acquisition could be pushed back by other operations,
leading to starvation / live locks. To address this, this patch will
allow the leases of offline descriptors to be cached.

Release note (bug fix): Lease acquisitions of descriptor in a
offline state may starve out bulk operations (backup / restore)

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62611)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/lease_test.go, line 2726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MWfP_zZ-rYNRuDPHd1Y:-MWfP_zZ-rYNRuDPHd1Z:b9yi9ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db656df9989cd081dad370822304e057563499d/pkg/sql/catalog/lease/lease_test.go#L2726)):*
> ```Go
> }
> 
> func TestOfflineLeaseRefresh(t *testing.T) {
> ```

a comment sketching the test and what it demonstrates would be nice. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 2750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MWfPY80CA03zDk-CWvq:-MWfPY80CA03zDk-CWvr:bvy1g1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db656df9989cd081dad370822304e057563499d/pkg/sql/catalog/lease/lease_test.go#L2750)):*
> ```Go
> 	params := base.TestServerArgs{Knobs: base.TestingKnobs{Store: knobs}}
> 
> 	//ReplicaRequestFilter
> ```

detritus 
___
*[pkg/sql/catalog/lease/lease_test.go, line 2812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MWfPvr1CJybKMhYv4dg:-MWfPvr1CJybKMhYv4dh:b-wwxm3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db656df9989cd081dad370822304e057563499d/pkg/sql/catalog/lease/lease_test.go#L2812)):*
> ```Go
> 
> 				// Select from an unrelated table
> 				_, err = s.InternalExecutor().(sqlutil.InternalExecutor).ExecEx(ctx, "inline-exec", txn, sessiondata.InternalExecutorOverride{User: security.RootUserName()}, "insert into d1.t2 values (10);")
> ```

nit: wrap and what not
___
*[pkg/sql/catalog/lease/lease_test.go, line 2823 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MWfQA6y582P4wbG8o1E:-MWfQA6zDi1c5IA8_Q3K:b-6sb9bz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db656df9989cd081dad370822304e057563499d/pkg/sql/catalog/lease/lease_test.go#L2823)):*
> ```Go
> 	for notify := range waitForTxn {
> 		close(notify)
> 		mu.RLock()
> ```

I think the locking here would bite you if the transaction above restarted. I feel like it can be simplified. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 2828 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MWfPs4d2i02w8Bz-XlC:-MWfPs4d2i02w8Bz-XlD:bsrwgmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db656df9989cd081dad370822304e057563499d/pkg/sql/catalog/lease/lease_test.go#L2828)):*
> ```Go
> 			// leasing out the table again
> 			_, err = conn.Query("select  * from d1.t1")
> 			if err == nil {
> ```

this conditional seems off.

**Review by ajwerner — COMMENTED** [review]
This probably should not make 21.1.0 but rather 21.1.1 as it is not new.

It seems like the test times out under stress. Run it on your gceworker with a shorter timeout to shake out these flakes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-:-MWxvYV0DJsHNsailZhu:bvly350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-:-MX29iWP39eZRcgAdjss:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/catalog/lease/lease.go, line 1432 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-MX29ANH7LPlsvIIpIoR:-MX29ANIEL1oWIFmB7N4:b-jxclbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/21bba8789105449ac017d1957e7d82e778de9cf2/pkg/sql/catalog/lease/lease.go#L1432)):*
> ```Go
> 				}
> 			}
> 			return descVersion.Descriptor, descVersion.expiration, nil
> ```

nit: roll thing into a helper to attach the commentary. Also note that this is to match behavior which existed before we leased offline descriptors.

**Review by ajwerner — COMMENTED** [review]
needs a bazel-generate

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-:-MX3B7Oz6ZaXo-VPexhj:b-7lxzix)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

**Comment by fqazi** [comment]
> needs a bazel-generate
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62611#-:-MX3B7Oz6ZaXo-VPexhj:b-7lxzix)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @fqazi)

Thanks @ajwerner , didn't realize what was needed

**Comment by fqazi** [comment]
bors r=ajwerner

**Comment by knz** [comment]
@fqazi is this a candidate for a backport?

**Comment by knz** [comment]
oh nvm please disregard my last comment, I see the changes have been reverted

**Pull request merged**
