### PR TITLE
distsqlrun: fix columnar operators test harness

### LINKED ISSUE #40525: teamcity: failed test: TestHashJoinerAgainstProcessor
The following tests appear to have failed on master (testrace): TestHashJoinerAgainstProcessor

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestHashJoinerAgainstProcessor).

[#1471016](https://teamcity.cockroachdb.com/viewLog.html?buildId=1471016):

```
TestHashJoinerAgainstProcessor
--- FAIL: testrace/TestHashJoinerAgainstProcessor (2.610s)

------- Stdout: -------
--- join type = LEFT_OUTER onExpr = "" seed = 908130567229589334 run = 2 ---
--- lEqCols = [2] rEqCols = [2] ---
--- inputTypes = [{{StringFamily 0 0 [] 0x8aa5210 0 <nil> [] [] 1043 <nil>}} {{DecimalFamily 0 0 [] 0x8aa5210 0 <nil> [] [] 1700 <nil>}} {{BytesFamily 0 0 [] 0x8aa5210 0 <nil> [] [] 17 <nil>}}] ---
    columnar_operators_test.go:256: different results: no match found for row 2 of processor output
        processor output:
        		[['U_yNE' -479035563456471.5719 NULL NULL NULL NULL] [NULL -0.237520451036119866 NULL NULL NULL NULL] [e'\x7f\x10' 841003.510225546096 '\x' e'`\x1d\x0b\x1eq`Hg' 5.776233569115936899E+30 '\x'] [e'\tfE7r>g\x11<' -787.6949047628281566 '\x' e'`\x1d\x0b\x1eq`Hg' 5.776233569115936899E+30 '\x'] [e'\x7f\x10' 841003.510225546096 '\x' e'5(/g|\x14{lI' NaN '\x'] [e'\tfE7r>g\x11<' -787.6949047628281566 '\x' e'5(/g|\x14{lI' NaN '\x'] ['^B9Y' -8.325911500003506620E+32 '\x27' NULL NULL NULL] [e'}s\x1aK' 247782395.5945897822 '\xa4d810b9' NULL NULL NULL] ['' 3052845.04045367018 '\xaf303fe62a0860bc94' NULL NULL NULL] ['' 5.002904114281552886E+25 '\xcbece64bace0' NULL NULL NULL] [e'w+E\x1bU}>' 528769334596063960.8 '\x08f8ba' NULL NULL NULL] [e'n-Bj\fLp\\' -6.540112128244789014E+34 '\xf2def7' NULL NULL NULL]]
        columnar operator output:
        		[[e'\tfE7r>g\x11<' -832.5911500003506620 '\x' e'`\x1d\x0b\x1eq`Hg' 5.776233569115936899E+30 '\x'] [e'\x7f\x10' 2477823.955945897822 '\x' e'`\x1d\x0b\x1eq`Hg' 5.776233569115936899E+30 '\x'] [e'\tfE7r>g\x11<' -479.0355634564715719 '\x' e'5(/g|\x14{lI' NaN '\x'] [e'\x7f\x10' 305284.504045367018 '\x' e'5(/g|\x14{lI' NaN '\x'] ['^B9Y' -8.325911500003506620E+32 '\x27' NULL NULL NULL] [e'}s\x1aK' 247782395.5945897822 '\xa4d810b9' NULL NULL NULL] ['U_yNE' -479035563456471.5719 NULL NULL NULL NULL] ['' 3052845.04045367018 '\xaf303fe62a0860bc94' NULL NULL NULL] ['' 5.002904114281552886E+25 '\xcbece64bace0' NULL NULL NULL] [e'w+E\x1bU}>' 528769334596063960.8 '\x08f8ba' NULL NULL NULL] [NULL -0.237520451036119866 NULL NULL NULL NULL] [e'n-Bj\fLp\\' -6.540112128244789014E+34 '\xf2def7' NULL NULL NULL]]




```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #40532: sql/distsqlrun: TestHashJoinerAgainstProcessor failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/1dcd4277286af06ba08b122e0d072b8b605c00c8

Parameters:
```
TAGS=
GOFLAGS=-parallel=4
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestHashJoinerAgainstProcessor PKG=github.com/cockroachdb/cockroach/pkg/sql/distsqlrun TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1471585&tab=buildLog

```
=== RUN   TestHashJoinerAgainstProcessor
--- join type = LEFT_OUTER onExpr = "" seed = 718521410144398180 run = 2 ---
--- lEqCols = [2] rEqCols = [2] ---
--- inputTypes = [{{BytesFamily 0 0 [] 0x68f5c20 0 <nil> [] [] 17 <nil>}} {{IntFamily 32 0 [] 0x68f5c20 0 <nil> [] [] 23 <nil>}} {{DecimalFamily 0 0 [] 0x68f5c20 0 <nil> [] [] 1700 <nil>}}] ---
--- FAIL: TestHashJoinerAgainstProcessor (0.22s)
    columnar_operators_test.go:256: different results: no match found for row 2 of processor output
        processor output:
        		[['\x' -1816199837 NULL NULL NULL NULL] ['\x2785f4' -1 NULL NULL NULL NULL] ['\x9fc870' -928511422 1 '\x98cf1e75' -1 1] ['\xe29883' 505830303 -596965785.8812846119 NULL NULL NULL] ['\x07025f06' -1726501833 -6.294747838156555919E+24 NULL NULL NULL] ['\x' 1748392228 -5.705256913496760141E+35 NULL NULL NULL] ['\x0ca460a31742' -1192195554 -657951773321553.3666 NULL NULL NULL] ['\x84663a36d4e29a00' 1632149487 -4.685869456599300391E+31 NULL NULL NULL] ['\xc256c1a7d62505' 1492141794 -1133361.090629371304 NULL NULL NULL] ['\xa8fa03' -603362162 -5.024820978753133782E+25 NULL NULL NULL]]
        columnar operator output:
        		[['\x9fc870' -928511422 5969657858812846119 '\x98cf1e75' -1 1] ['\xe29883' 505830303 -596965785.8812846119 NULL NULL NULL] ['\x07025f06' -1726501833 -6.294747838156555919E+24 NULL NULL NULL] ['\x' -1816199837 NULL NULL NULL NULL] ['\x' 1748392228 -5.705256913496760141E+35 NULL NULL NULL] ['\x2785f4' -1 NULL NULL NULL NULL] ['\x0ca460a31742' -1192195554 -657951773321553.3666 NULL NULL NULL] ['\x84663a36d4e29a00' 1632149487 -4.685869456599300391E+31 NULL NULL NULL] ['\xc256c1a7d62505' 1492141794 -1133361.090629371304 NULL NULL NULL] ['\xa8fa03' -603362162 -5.024820978753133782E+25 NULL NULL NULL]]

```

### LINKED ISSUE #40541: teamcity: failed test: TestHashJoinerAgainstProcessor
The following tests appear to have failed on master (test): TestHashJoinerAgainstProcessor

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestHashJoinerAgainstProcessor).

[#1472683](https://teamcity.cockroachdb.com/viewLog.html?buildId=1472683):

```
TestHashJoinerAgainstProcessor
--- FAIL: test/TestHashJoinerAgainstProcessor (2.670s)

------- Stdout: -------
--- join type = FULL_OUTER onExpr = "" seed = 3156148344945364751 run = 2 ---
--- lEqCols = [0] rEqCols = [0] ---
--- inputTypes = [{{IntFamily 32 0 [] 0x68f5c20 0 <nil> [] [] 23 <nil>}} {{DecimalFamily 0 0 [] 0x68f5c20 0 <nil> [] [] 1700 <nil>}} {{DecimalFamily 0 0 [] 0x68f5c20 0 <nil> [] [] 1700 <nil>}}] ---
    columnar_operators_test.go:256: different results: no match found for row 9 of processor output
        processor output:
        		[[NULL 0 NULL NULL NULL NULL] [NULL 4.599389919925572498E+19 -1.234E+401 NULL NULL NULL] [NULL NULL NULL 599879455 -564.3639851002337199 56122.05817039810147] [NULL NULL NULL -772971033 47717504032078108.39 217136.7997470298674] [NULL NULL NULL 2029044759 -9.025560477095914424E+32 -7.349288550458068915E+29] [NULL NULL NULL -723176853 4.012107507641596378E+33 3.359053838044171512E+29] [NULL NULL NULL 1431025952 6.959613017571207793E+36 -5733754374216559.165] [NULL NULL NULL 1788362826 -7.730346023918780146E+29 1] [NULL NULL NULL -128 -7.645378879668052805E+35 6.916825322951859362] [-1 -Infinity -1.571619311553669325E+25 -1 2.236229595568572387E+19 -72170998829.91031533] [NULL NULL NULL -190053485 286603981127.8335754 -4.038167489643855655E+23] [NULL NULL NULL NULL -3.452725743442529171E+32 -Infinity] [-2064648408 -1.651012147504060141E+29 -2639.279567860667507 NULL NULL NULL] [-1750012319 3.055642750244227607E+23 -885163539.5054607891 NULL NULL NULL] [127 9.5951891068250344E+34 NULL NULL NULL NULL] [-1660797895 -84809842199444197.96 -4936100081153.241408 NULL NULL NULL] [-1405963204 -0.04229093378124498701 -25252631.51597070550 NULL NULL NULL] [-341198697 -75664009.59103609899 -4.943310154372731046E+30 NULL NULL NULL] [2005550015 NaN -6.564024089259277457E+30 NULL NULL NULL]]
        columnar operator output:
        		[[NULL NULL NULL 599879455 -564.3639851002337199 56122.05817039810147] [NULL NULL NULL -772971033 47717504032078108.39 217136.7997470298674] [NULL NULL NULL 2029044759 -9.025560477095914424E+32 -7.349288550458068915E+29] [NULL NULL NULL -723176853 4.012107507641596378E+33 3.359053838044171512E+29] [NULL NULL NULL 1431025952 6.959613017571207793E+36 -5733754374216559.165] [NULL NULL NULL 1788362826 -7.730346023918780146E+29 1] [NULL NULL NULL -128 -7.645378879668052805E+35 6.916825322951859362] [-1 -Infinity -1.234E+10 -1 2.236229595568572387E+19 -72170998829.91031533] [NULL NULL NULL -190053485 286603981127.8335754 -4.038167489643855655E+23] [NULL NULL NULL NULL -3.452725743442529171E+32 -Infinity] [NULL 0 NULL NULL NULL NULL] [-2064648408 -1.651012147504060141E+29 -2639.279567860667507 NULL NULL NULL] [-1750012319 3.055642750244227607E+23 -885163539.5054607891 NULL NULL NULL] [127 9.5951891068250344E+34 NULL NULL NULL NULL] [-1660797895 -84809842199444197.96 -4936100081153.241408 NULL NULL NULL] [-1405963204 -0.04229093378124498701 -25252631.51597070550 NULL NULL NULL] [-341198697 -75664009.59103609899 -4.943310154372731046E+30 NULL NULL NULL] [NULL 4.599389919925572498E+19 -1.234E+401 NULL NULL NULL] [2005550015 NaN -6.564024089259277457E+30 NULL NULL NULL]]




```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when comparing the results as sets, we would accumulate
copies of the rows. These copies are shallow which can lead to problems
with decimals in particular when the same decimal is reused to return
the rows. Now this is fixed by accumulating string representation right
away.

Fixes: #40525.
Fixes: #40532.
Fixes: #40541.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
I don't super love the stringifying thing - I feel like this might cause a different kind of flakiness. Maybe we should change the repeatable batch source instead to always allocate new rows? that would be more realistic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40521#-:-Lo618gs060ntqlq71Al:bj9b0ua)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
We actually are not using repeatable *batch* source here at all - we have the following chain:
`RepeatableRowSource -> columnarizer -> col operator -> materializer`. My understanding is that the problem arises because columnarizer reuses the same batch to return as output, and we definitely don't want to allocate new batch in there.

**Comment by jordanlewis** [comment]
What I meant to say was repeatable row source. It reuses rows in an unrealistic way that doesn't happen outside of tests.

**Review by jordanlewis — APPROVED** [review]
LGTM

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
