### PR TITLE
storage: rename Iterator to MVCCIterator

### PR DESCRIPTION
**Pull request by sumeerbhola**
Also remove MVCCIterator, which was implemented for RocksDB.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-:-MK_FEyJ2-bOFPRkUETu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-MK_F33Y2s8q7rvmCn87:-MK_F33Y2s8q7rvmCn88:b-8yobfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20e6cfdb96faef28b9f0a2bd7dc130c350a6052/pkg/storage/engine.go#L42)):*
> ```Go
> // engine. SimpleIterator implementations are thread safe unless otherwise
> // noted. SimpleIterator is a subset of the functionality offered by MVCCIterator.
> type SimpleIterator interface {
> ```

Should this be renamed to `SimpleMVCCIterator`?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

And added a commit to rename `spanset.Iterator` to `spanset.MVCCIterator`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-:-MK_Nnm74gAO74V4Prh9:brdeop4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/engine.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-MK_F33Y2s8q7rvmCn87:-MK_NgVP4Z5OmBIY8-C2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20e6cfdb96faef28b9f0a2bd7dc130c350a6052/pkg/storage/engine.go#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be renamed to `SimpleMVCCIterator`? 
</blockquote></details>

Done

**Review by itsbilal — APPROVED** [review]
:lgtm:

I'm not sure how I feel about an `MVCCIterator` that doesn't actually embed any MVCC functionality other than key encode/decode, and an `MVCCIterator.Iterate` that iterates through all revisions anyway. But that's a subjective point and if you all prefer it this way to distinguish from `pebble.Iterator`, I'm more than happy to go along with it. 

> Reviewed 3 of 3 files at r1, 21 of 26 files at r2, 15 of 15 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-:-MK_U9m55Rdm4ySSFigm:b9fqu51)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 26 of 26 files at r2, 1 of 1 files at r3, 15 of 15 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-:-MK_dwfd5v1VIRpt-79S:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale)

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> I'm not sure how I feel about an MVCCIterator that doesn't actually embed any MVCC functionality other than key encode/decode, and an MVCCIterator.Iterate that iterates through all revisions anyway.

It's to distinguish from `EngineIterator`. `MVCCIterator` is for iterating over the MVCC key space. I will probably rename `Reader.Iterate` to `Reader.MVCCIterate`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55972#-:-MK_nuPu2xXf8x04IoSU:b-5dg6hh)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
