### PR TITLE
sql: fall back to raw SQL for statement diagnostics bundle, and add errors.txt

### LINKED ISSUE #94416: Crash: Node crashes when using EXPLAIN ANALYZE (DEBUG) AS OF SYSTEM TIME with a very small time interval
**Describe the problem**

This SQL crashes a node:

```
root@localhost:26257/defaultdb> EXPLAIN ANALYZE (DEBUG) SELECT * FROM t AS OF SYSTEM TIME '-0.0000001s';
*
* ERROR: a SQL panic has occurred while executing the following statement:
* EXPLAIN ANALYZE (DEBUG) SELECT * FROM t AS OF SYSTEM TIME '-0.0000001s'
*
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
*   | [...repeated from below...]
* Wraps: (2) while executing: EXPLAIN ANALYZE (DEBUG) SELECT * FROM _ AS OF SYSTEM TIME '_'
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:830
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:884
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:260
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:835
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:49
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:452
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AsStringWithFlags
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:590
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*PrettyCfg).docAsString
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/pretty.go:181
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*PrettyCfg).Doc
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/pretty.go:176
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*PrettyCfg).Pretty
*   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/pretty.go:165
*   | github.com/cockroachdb/cockroach/pkg/sql.(*stmtBundleBuilder).addTrace
*   | 	github.com/cockroachdb/cockroach/pkg/sql/explain_bundle.go:334
*   | github.com/cockroachdb/cockroach/pkg/sql.buildStatementBundle
*   | 	github.com/cockroachdb/cockroach/pkg/sql/explain_bundle.go:144
*   | github.com/cockroachdb/cockroach/pkg/sql.(*instrumentationHelper).Finish
*   | 	github.com/cockroachdb/cockroach/pkg/sql/instrumentation.go:393
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func5
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:466
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:611
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2412
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1928
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1932
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1854
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:832
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
*   | runtime.goexit
*   | 	GOROOT/src/runtime/asm_amd64.s:1594
* Wraps: (4) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
*
ERROR: unexpected EOF
warning: error retrieving the transaction status: connection closed unexpectedly: conn closed
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: failed to connect to `host=localhost user=root database=`: tls error (read tcp [::1]:44976->[::1]:26257: read: connection reset by peer)
```

There is protection if you use the query without `EXPLAIN ANALYZE...`:

```
root@localhost:26257/defaultdb> SELECT * FROM t AS OF SYSTEM TIME '-0.0000001s';
ERROR: AS OF SYSTEM TIME: interval value '-0.0000001s' too small, absolute value must be >= 1µs
```

**Environment:**
 - CockroachDB version v22.2.1

Jira issue: CRDB-22883

### PR DESCRIPTION
**Pull request by michae2**
**sql: fall back to raw SQL for statement diagnostics bundle**

When gathering the statement for a statement diagnostics bundle, fall
back to using the raw SQL when we cannot pretty-print the statement AST,
which happens for statements that fail with certain errors.

(This also fixes a crash in addTrace, which was not handling these
error cases. It looks like this crash was partially fixed in #56768 but
not completely.)

Fixes: #94416 #56705

Epic: None

Release note (bug fix): Fix a crash that occurs on the gateway node when
collecting a statement diagnostics bundle (e.g. `EXPLAIN ANALYZE
(DEBUG)`) on a statement that fails with certain errors. This crash has
existed in various forms since the introduction of statement bundles in
v20.1.0.

**sql: add errors.txt to statement diagnostics bundles**

Add an errors.txt file to statement diagnostics bundles containing the
printed messages of various error objects.

Informs: #94416

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
Now for that bad AOST query we get this `statement.sql` (notice the `EXPLAIN ANALYZE (DEBUG)` hasn't been stripped off):

```
EXPLAIN ANALYZE (DEBUG) SELECT * FROM t AS OF SYSTEM TIME '-0.0000001s'
```

and this `errors.txt`:

```
res error:
<nil>

payload error:
AS OF SYSTEM TIME: interval value '-0.0000001s' too small, absolute value must be >= 1µs

ret error:
<nil>
```

**Review by mgartner — APPROVED** [review]
Thanks for fixing this! :lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-:-NKV1pRE5nrKIWKywvXM:bj42jzh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV1UNo4_QcUmcxT2md):*
Can you make it explicit that this would crash the gateway node? Also, do we know how far back this was present?

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-:-NKV4QNRCtVPyIsfe4oa:be8rotp)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/explain_bundle.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV2cEaCqCNUfQgfoum:-NKV2cEaCqCNUfQgfoun:blj1fl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7361eaf1ea6c063a811664f9299e59c0142169a6/pkg/sql/explain_bundle.go#L215)):*
> ```Go
> }
> 
> // buildStatement saves the pretty-printed statement, without arguments.
> ```

nit: `/s/buildStatement/buildPrettyStatement/`.
___
*[`pkg/sql/explain_bundle.go` line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV2wRp-1qSO_ioIzm3:-NKV2wRp-1qSO_ioIzm4:bluoene) ([raw file](https://github.com/cockroachdb/cockroach/blob/7361eaf1ea6c063a811664f9299e59c0142169a6/pkg/sql/explain_bundle.go#L234)):*
> ```Go
> }
> 
> // addStatement adds the pretty-printed statement as file statement.txt.
> ```

nit: maybe mention that the pretty-printed statement is stored in `b.stmt`.
___
*[`pkg/sql/explain_bundle.go` line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV3gHy62HxoNZoiRJE:-NKV3gHy62HxoNZoiRJF:bb3dxn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85a9c89b013dd0f963e7d94b894251f6cf830ec/pkg/sql/explain_bundle.go#L134)):*
> ```Go
> 	trace tracingpb.Recording,
> 	placeholders *tree.PlaceholderInfo,
> 	resErr, payloadErr, retErr error,
> ```

nit: let's rename `resErr` to `queryErr` (it's an error encountered during the query optimization / execution) and `retErr` to `commErr` (since it should be about an error communicating with the client).
___
*[`pkg/sql/explain_bundle.go` line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV47Ub0Wozfw7NxyAh:-NKV47Ub0Wozfw7NxyAi:b-raemt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85a9c89b013dd0f963e7d94b894251f6cf830ec/pkg/sql/explain_bundle.go#L450)):*
> ```Go
> 		resErr, payloadErr, retErr,
> 	)
> 	b.z.AddFile("errors.txt", output)
> ```

It'd be good to add a simple unit test for this.

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94440)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV1UNo4_QcUmcxT2md):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you make it explicit that this would crash the gateway node? Also, do we know how far back this was present?
</blockquote></details>

Done. Looks like this existed back in v20.1.0 (when statement bundles were first introduced), and then was partially fixed in #56768 but remained an issue until now.
___
*[`pkg/sql/explain_bundle.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV2cEaCqCNUfQgfoum:-NKthBus0xKajjUmRcTL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7361eaf1ea6c063a811664f9299e59c0142169a6/pkg/sql/explain_bundle.go#L215)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `/s/buildStatement/buildPrettyStatement/`.
</blockquote></details>

Done.
___
*[`pkg/sql/explain_bundle.go` line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV2wRp-1qSO_ioIzm3:-NKthCiv-rICLPlWVGCc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7361eaf1ea6c063a811664f9299e59c0142169a6/pkg/sql/explain_bundle.go#L234)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe mention that the pretty-printed statement is stored in `b.stmt`.
</blockquote></details>

Done.
___
*[`pkg/sql/explain_bundle.go` line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV3gHy62HxoNZoiRJE:-NKthAAp7ae3H_F1S9ML:b-66yph8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85a9c89b013dd0f963e7d94b894251f6cf830ec/pkg/sql/explain_bundle.go#L134)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: let's rename `resErr` to `queryErr` (it's an error encountered during the query optimization / execution) and `retErr` to `commErr` (since it should be about an error communicating with the client).
</blockquote></details>

Ah, thank you! Done.
___
*[`pkg/sql/explain_bundle.go` line 450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94440#-NKV47Ub0Wozfw7NxyAh:-NKthDpTATi25X17DIT6:b-wsqgbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85a9c89b013dd0f963e7d94b894251f6cf830ec/pkg/sql/explain_bundle.go#L450)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It'd be good to add a simple unit test for this.
</blockquote></details>

Now checked in `TestExplainAnalyzeDebug/error`.

**Comment by michae2** [comment]
TFYRs!

bors r=mgartner,yuzefovich

**Pull request merged**
