### PR TITLE
sql/*: move name resolution from tree to catalog

### PR DESCRIPTION
**Pull request by ajwerner**
This series of commits moves the logic implementing name resolution from `tree` to `catalog/resolver`.
Along the way it attempts to do a bit of clean-up here and there.

### CODE REVIEW

**Comment by ajwerner** [comment]
Please take this one commit-by-commit. No individual commit should be too bad.

**Review by postamar — APPROVED** [review]
LGTM. This is nice.

**Comment by postamar** [comment]
While reviewing, I was curious at what `expandTableGlob` is and does, so I went down a rabbit hole. I was surprised to find so much name resolution logic in the opt catalog.

**Comment by ajwerner** [comment]
> While reviewing, I was curious at what expandTableGlob is and does, so I went down a rabbit hole. I was surprised to find so much name resolution logic in the opt catalog.

Indeed, that thing does a lot. Thus far we've been ignoring it and just taking care not to break it. I intend to continue that way with an eye towards eliminating duplication of code. Once the `catalog` house feels more in order, then I'll look to thin that layer. There are some small pieces that I'll definitely want to unhook sooner rather than later.

**Comment by ajwerner** [comment]
TFTR!

bors r=postamar

**Pull request merged**
