### PR TITLE
sql: operations do not use descriptors in the ABSENT state

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change allows the schema change logic to add
descriptor mutations in the ABSENT state. It tests
that all operations function properly when an
index descriptor in the ABSENT state references a
column mutation in any state.

A follow up change will actually start adding index
descriptors in the ABSENT state.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6757)

### CODE REVIEW

**Comment by paperstreet** [comment]
I haven't had time yet to get my head wrapped around enough of this to do the review any justice. My first question though is that it's unfortunate that we had to add the complication of another state. Is it really necessary?

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> #### sql: operations do not use descriptors in the ABSENT state
> 
> This change allows the schema change logic to add
> 
> descriptor mutations in the ABSENT state. It tests
> 
> that all operations function properly when an
> 
> index descriptor in the ABSENT state references a
> 
> column mutation in any state.
> 
> 
> 
> A follow up change will actually start adding index
> 
> descriptors in the ABSENT state.
> 
> 
> </details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6757#-:-KI-bMggPX6eHQcs5Sr5:165797975)*

**Comment by vivekmenezes** [comment]
There are a few options
1. This one.
2. Do not use SELECT while running UPDATE and DELETE. Change the implementation to read from the kv store directly. This will allow it to read columns that are not yet live for indexes.
3. Configure SELECT to read columns that are not yet live. (the least favorite approach IMHO)
4. leave the index descriptor out of the mutation list in another WAIT list (kind of similar to this)

I think 2 or 3 are muckier and I did give them a go before I realized I was make a number of very fragile changes, while this approach or any approach that keeps the index completely invisible until the columns are fully live are contained within the schema change code (preferred). I also tried another approach which is to ignore all mutations except the first one. this was cleaner

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I haven't had time yet to get my head wrapped around enough of this to do the review any justice. My first question though is that it's unfortunate that we had to add the complication of another state. Is it really necessary?</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6757#-:-KI-nyMU6C-wamhGabrn:-907287768)*

**Comment by paperstreet** [comment]
Okay that makes sense. I thought about this some more and I have a few followups. Sorry again if I'm missing obvious things because of my unfamiliarity with schema changes. It's probably also be worth getting other reviewers on this that are more familiar with the system.

I think a hybrid of 2 and 3 is my preferred solution, actually, though with a small twist. Update and Delete currently go through exactly the same Select codepath as one that comes directly from the parser. It seems like a small refactor to split validation of the publicness of the columns and could eliminate the fragility of that solution.

David mentioned during our in-person chat the other day that storing the definition protos of in-progress columns and indexes on the mutations has so been a bit of a maintenance burden for him. I've had the same experience. Addressing this seems in line with above.

I'm still uncomfortable with adding another state for this. It seems like unwarranted technical debt to me, especially for the problem we're currently solving. If you were making a case for this because of backfill complexity, for example, I think it'd make more sense.

I'm also a little confused about what the tests are proving. I could be totally misunderstanding things, but it seems like they pass now without actually making `ALTER TABLE foo ADD COLUMN bar UNIQUE` use the new state? Do we have any tests that let you sent a sql command that starts a schema change, blocks the backfill so it doesn't complete, lets you issue more sql commands, and finally manually unblock the backfill so the schema change can complete?

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> There are a few options
> 1. This one.
> 2. Do not use SELECT while running UPDATE and DELETE. Change the implementation to read from the kv store directly. This will allow it to read columns that are not yet live for indexes.
> 3. Configure SELECT to read columns that are not yet live. (the least favorite approach IMHO)
> 4. leave the index descriptor out of the mutation list in another WAIT list (kind of similar to this)
> 
> I think 2 or 3 are muckier and I did give them a go before I realized I was make a number of very fragile changes, while this approach or any approach that keeps the index completely invisible until the columns are fully live are contained within the schema change code (preferred). I also tried another approach which is to ignore all mutations except the first one. this was cleaner
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6757#-:-KI4C05M1aBDq-MomdHw:-1643683343)*

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/6789 is the completed change. I think it is reasonable given what we're trying to achieve. I'm going to close this PR for now.

I think we do need to introduce the notion of an ABSENT state for both this use case and David's use case where a new table has a foreign key to another table. In the FK use case David has introduced a State to the TableDescriptor and plans to use ADD to represent the ABSENT state.

Anyway lets follow up on this discussion on the new PR. 

Thanks

**Pull request closed without merging**
