### PR TITLE
sql/parser: add cluster_id builtin

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by dt** [comment]
@knz any suggestions on how to test this one?

**Comment by petermattis** [comment]
You can test that `crdb_internal.cluster_id()` returns a string of a particular length and that the value is not all 0s.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-:-Kmh1sxV_L8vr_rIaJ2A:b-yj45os)*

**Comment by knz** [comment]
Make a test in the `sql` package that spawns a test cluster, gets its ID via the internal API, then issues the SQL query over the test client connection to compare.

Rest of the code LGTM with a nit.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 1718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kmi0UuKKVp2aA5Ma3_p:-Kmi0UuKKVp2aA5Ma3_q:b-l6aadn) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b171fc21959e3bcfc53ee7b0a517aff9828604/pkg/sql/parser/eval.go#L1718)):*
> ```Go
> // TODO(andrei): remove or limit the duplication.
> type EvalContext struct {
> 	ClusterID uuid.UUID
> ```

Hmm ok

But since we now both have NodeID and ClusterID in here, is there no way to add a new API to `e.cfg` with type `func () *dbIDs`, with `dbIDs` defined as `type dbIDs struct {NodeID, ClusterID}`? Then just store that one pointer to both?

This would reduce the amount of code and the amount data copied. I'd rather keep the evalcontext as compact as possible given it's instantiated so many times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-:-Kmi-zOgtvq9PQKe8ld1:b-phhv85)*

**Comment by dt** [comment]
Done.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/eval.go, line 1718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kmi0UuKKVp2aA5Ma3_p:-Kn6OuyXH-MyNPndRS8v:bxw9zqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b171fc21959e3bcfc53ee7b0a517aff9828604/pkg/sql/parser/eval.go#L1718)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Hmm ok

But since we now both have NodeID and ClusterID in here, is there no way to add a new API to `e.cfg` with type `func () *dbIDs`, with `dbIDs` defined as `type dbIDs struct {NodeID, ClusterID}`? Then just store that one pointer to both?

This would reduce the amount of code and the amount data copied. I'd rather keep the evalcontext as compact as possible given it's instantiated so many times.
</blockquote></details>

Hmm, I think I'd rather wait for a couple more obviously grouped fields to start breaking up/nesting, but will nest it now if you feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-:-Kn6PsG0ohjjp2qP6-1o:b-896fix)*

**Comment by knz** [comment]
LGTM still but fix the comment in the test file.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/impure_builtin_test.go, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kn6QmNJ6AUVYMPCuqt5:-Kn6QmNKyjawY0XRIunC:b5icplh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f63b94d50326b286338ed1420fc32c5201e6f83/pkg/sql/impure_builtin_test.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

year -> 2017

---

*[pkg/sql/impure_builtin_test.go, line 15 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kn6QoRi7vPyOXYJDzWj:-Kn6QoRjdMyxKiCh9jXf:b3oovt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f63b94d50326b286338ed1420fc32c5201e6f83/pkg/sql/impure_builtin_test.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> //
> // Author: Marc Berhault (marc@cockroachlabs.com)
> ```

I'm not sure Marc is involved here

---

*[pkg/sql/parser/eval.go, line 1718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kmi0UuKKVp2aA5Ma3_p:-Kn6Qw3avZQjFQtWw1IF:bucu24o) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b171fc21959e3bcfc53ee7b0a517aff9828604/pkg/sql/parser/eval.go#L1718)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hmm, I think I'd rather wait for a couple more obviously grouped fields to start breaking up/nesting, but will nest it now if you feel strongly.
</blockquote></details>

It's all right. Thanks for considering.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-:-Kn6QyfyRwkZDSxqxXY0:bps687p)*

**Comment by dt** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/impure_builtin_test.go, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kn6QmNJ6AUVYMPCuqt5:-Kn6REybEevlLsZLoap5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f63b94d50326b286338ed1420fc32c5201e6f83/pkg/sql/impure_builtin_test.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

year -> 2017
</blockquote></details>

Done.

---

*[pkg/sql/impure_builtin_test.go, line 15 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542#-Kn6QoRi7vPyOXYJDzWj:-Kn6RAPg5OmqlK8Vr-Lu:b-y6wizv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f63b94d50326b286338ed1420fc32c5201e6f83/pkg/sql/impure_builtin_test.go#L15)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not sure Marc is involved here
</blockquote></details>

lol, whoops, that's what I get for copy/pasting the lic header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16542)*

**Pull request merged**
