### PR TITLE
c-deps/geos: add geos

### PR DESCRIPTION
**Pull request by petermattis**
Unlike other C libraries, libgeos is compiled as a shared library and is
intended to be dynamically loaded via `dlopen`. The shared library is
built in the `libs` directory with the intention that we'll add a
`--libs-path` flag that defaults to this directory.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Other than the issue with `build/builder.sh cmake` being too old, this should be good to go regarding the building of libgeos. The next step is to work on the cgo wrapper. @otan what is your intention with `github.com/otan-cockroach/gogeos/geos/`? My feeling is that we should create the cgo wrapper directly in the cockroach repo as it will be dependent on the `dlopen` approach we're using and thus not reusable by anyone else.

**Comment by otan** [comment]
We'll abandon the gogeos library. It uses SetFinalizer, is missing a few
things and in the end not what we'll end up doing :) .

**Review by danhhz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46549#-:-M3HD4V45b7Si4pkBVRe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @otan, @petermattis, and @sumeerbhola)

___
*[Makefile, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46549#-M3HD-lFDD0o5TgHz6kQ:-M3HBJag4pcSajuUEl6z:b-sln8ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/0634e2dba48652190a330c91e07e2edbcc0b72da/Makefile#L474)):*
> ```Makefile
> PROTOC      := $(PROTOC_DIR)/protoc
> 
> DYN_LIBS := libs
> ```

nit: isn't this usually lib (singular)?

**Review by petermattis — COMMENTED** [review]
TFTR!

> We'll abandon the gogeos library. It uses SetFinalizer, is missing a few things and in the end not what we'll end up doing :) .

How do you want to navigate creating a skeleton of the real cgo wrapper? My thought is that I could create the `dlopen` and Go-side skeleton, and leave it to you to put flesh on the bones. (I'd do this in a follow-on PR).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46549#-:-M3IIJsP4Ce1r_75lELt:bpzo36b)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[Makefile, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46549#-M3HD-lFDD0o5TgHz6kQ:-M3IIEuq-CwwMzQR5TJ3:bhokodj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0634e2dba48652190a330c91e07e2edbcc0b72da/Makefile#L474)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: isn't this usually lib (singular)?
</blockquote></details>

Done. And renamed the variable to `DYN_LIB_DIR`.

**Review by otan — COMMENTED** [review]
If you wanted to give that a go, happy for you to do so!

Make sure to use the `_r` functions as they are the threadsafe ones. These need a GEOS handle from `initGEOS`.

If you feel up to it - the other problem is that the GEOSGeometry object is created in the heap - the underlying data structure has vectors and things inside it that complicated the other example you gave. if we can figure a way to make the lifetime of that object be in Golang without using the finalizer that'd be great (otherwise, we'd have to put WKB/create a new GEOS Object and add points in manually GEOS library every time)...

If you wanted to borrow my skeleton it's here: https://github.com/otan-cockroach/otan-scripts/blob/master/geospatial-geos-cgo-test/dlopen.c

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46549#-:-M3IPPdGAhAUYvcYbHR2:b-n8knu8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

**Comment by otan** [comment]
sorry, by "complicated the other example you gave", i meant the one where you have put the bytes of the struct in Go, and have the C++ read the Go pointer for the object.

**Comment by petermattis** [comment]
As expected, CI is failing because the `cmake` in the builder image is too old. Perhaps I'll take a crack at fixing that. Do we care if `featurebranch_geo` is building on CI? 

> If you wanted to give that a go, happy for you to do so!

Feels like a good use of Friday. Maybe I'll squeeze it in between meetings tomorrow.

**Comment by danhhz** [comment]
> Do we care if featurebranch_geo is building on CI?

My internal metric for when we should restart the feature branch and do real code reviews is when we can get CI working on the branch.

**Comment by petermattis** [comment]
> My internal metric for when we should restart the feature branch and do real code reviews is when we can get CI working on the branch.

Ack. I have a PR out to fix the CI issue, so this should be a non-issue in a day or so.

**Comment by petermattis** [comment]
@otan or @danhhz in order for CI to be fixed, we need to rebase or merge `featurebranch_geo` with master to pick up the change to the builder image to contain a newer version of `cmake`. What is the proper way to do that? I could rebase `featurebranch_geo` on master and force push it. I could merge master into `featurebranch_geo` (though my naive attempt to do that ran into merge conflicts).

**Comment by danhhz** [comment]
Alternatively, should we make this the first PR in the "real" feature branch?

**Comment by otan** [comment]
^ happy to do this!

**Comment by petermattis** [comment]
Go for it, Oliver.

**Pull request closed without merging**
