### PR TITLE
roachtest: skip hotspotsplits on <20.1

### LINKED ISSUE #44742: roachtest: hotspotsplits/nodes=4 failed
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1729806&tab=buildLog) on [release-19.2@4654024871028124660244c6ffcead27b5bba6c0](https://github.com/cockroachdb/cockroach/commits/4654024871028124660244c6ffcead27b5bba6c0):

```
The test failed on branch=release-19.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	cluster.go:1410,context.go:135,cluster.go:1399,test_runner.go:778: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1729806-1580888519-08-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 4: skipped
		1: dead
		2: 4096
		3: 4036
		Error:  1: dead

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1729806&tab=artifacts#/hotspotsplits/nodes=4)
Related:
- #33660 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #44841: roachtest: hotspotsplits/nodes=4 failed
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1734688&tab=buildLog) on [release-19.1@407017cad14dfa63f19578055082dc10f3283cc4](https://github.com/cockroachdb/cockroach/commits/407017cad14dfa63f19578055082dc10f3283cc4):

```
The test failed on branch=release-19.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	cluster.go:1410,context.go:135,cluster.go:1399,test_runner.go:778: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1734688-1581059457-16-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 4: skipped
		1: dead
		3: 3789
		2: 3866
		Error:  1: dead

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1734688&tab=artifacts#/hotspotsplits/nodes=4)
Related:
- #44742 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #33660 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #45045: roachtest: hotspotsplits/nodes=4 failed
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1747142&tab=buildLog) on [44941@8e9a7f8ab8db3beabc9adc170dad6fefb1fb7ae6](https://github.com/cockroachdb/cockroach/commits/8e9a7f8ab8db3beabc9adc170dad6fefb1fb7ae6):

```
The test failed on branch=44941, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	hotspotsplits.go:85,hotspotsplits.go:102,test_runner.go:741: range size 650 MiB exceeded 192 MiB
		main.registerHotSpotSplits.func1.2
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/hotspotsplits.go:69
		github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		runtime.goexit
			/usr/local/go/src/runtime/asm_amd64.s:1357

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1747142&tab=artifacts#/hotspotsplits/nodes=4)
Related:
- #44841 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44742 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #33660 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #45284: roachtest: hotspotsplits/nodes=4 failed
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1760695&tab=buildLog) on [45179@12734324037949d8a864b8150ca6e7861d49369c](https://github.com/cockroachdb/cockroach/commits/12734324037949d8a864b8150ca6e7861d49369c):

```
The test failed on branch=45179, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	hotspotsplits.go:85,hotspotsplits.go:102,test_runner.go:741: range size 230 MiB exceeded 192 MiB
		main.registerHotSpotSplits.func1.2
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/hotspotsplits.go:69
		github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		runtime.goexit
			/usr/local/go/src/runtime/asm_amd64.s:1357

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1760695&tab=artifacts#/hotspotsplits/nodes=4)
Related:
- #45045 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-44941](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-44941) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44841 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44742 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #33660 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #45370: roachtest: hotspotsplits/nodes=4 failed
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1764809&tab=buildLog) on [provisional_202002240854_v20.1.0-beta.2@49e2b18471a42aed8a8ad7cb658863f045ea1aac](https://github.com/cockroachdb/cockroach/commits/49e2b18471a42aed8a8ad7cb658863f045ea1aac):

```
The test failed on branch=provisional_202002240854_v20.1.0-beta.2, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	hotspotsplits.go:85,hotspotsplits.go:102,test_runner.go:741: range size 511 MiB exceeded 192 MiB
		main.registerHotSpotSplits.func1.2
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/hotspotsplits.go:69
		github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
			/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		runtime.goexit
			/usr/local/go/src/runtime/asm_amd64.s:1357

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1764809&tab=artifacts#/hotspotsplits/nodes=4)
Related:
- #45284 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-45179](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-45179) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #45045 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-44941](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-44941) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44841 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #44742 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-19.2](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-19.2) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

- #33660 roachtest: hotspotsplits/nodes=4 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
Closes #45370.
Closes #45284.
Closes #45045.
Closes #44841.
Closes #44742.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]

**Comment by ajwerner** [comment]
My bad on this! I'll fix the test.

**Comment by ajwerner** [comment]
Actually, I misread some of these failures. It's not clear that this is totally related to the range size change.

**Comment by tbg** [comment]
No, not related to range size IMO.

bors r=nvanbenschoten

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/45792

bors r=nvanbenschoten

**Comment by tbg** [comment]
Testrace ran out of time again. I'm just bors'ing a skip that will shave 10min off, so now we're hopefully good to go

bors r=nvanbenschoten

**Pull request merged**
