### PR TITLE
storage: reformat Replica.CanCreateTxnRecord() comment for godoc

### PR DESCRIPTION
**Pull request by ajwerner**
This comment is a masterpiece which needed minor reformatting to display well
in godoc.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Before:

image

After:
Screenshot_2020-01-15 storage - Go Documentation Server(1)

Screenshot_2020-01-15 storage - Go Documentation Server

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43993#-LybkLge1Tg1kJAh8VCF:-LybkLggAgUnlcikzQUc:bk1jeda) ([raw file](https://github.com/cockroachdb/cockroach/blob/631b4cff20a48c2044d50f7400ab7e8414314522/pkg/storage/replica_tscache.go#L399)):*
> ```Go
> //     transaction's intents.
> //
> //     The first reason here no longer holds. Concurrent actors now bump the
> ```

This probably needs an update given the removal of the write timestamp cache.

**Review by nvb — APPROVED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43993#-:-LyeDGcTEM-ZQXxTbzCt:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43993#-LybkLge1Tg1kJAh8VCF:-LyeCs0f2NQ0rhZisL6_:b-6ao8j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/631b4cff20a48c2044d50f7400ab7e8414314522/pkg/storage/replica_tscache.go#L399)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This probably needs an update given the removal of the write timestamp cache. 
</blockquote></details>

Do you mind just taking out the word "write". That will make it correct. And maybe also reference the "tombstone marker".

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43993#-:-LyhCazWDZd8F59np1wG:b-l0r5kv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
Flaked on #44070.

bors r=nvanbenschoten

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Pull request merged**
