### PR TITLE
colfetcher: don't fetch an extra key when limit hint is present

### PR DESCRIPTION
**Pull request by yuzefovich**
**row: update examples in the comment on batch sizes**

We recently bumped the KV batch size from 10k to 100k but forgot to
update the examples.

Release note: None

**colfetcher: don't fetch an extra key when limit hint is present**

Previously, the SQL fetchers - in presence of the limit hints - would
always ask for an extra key for the first KV batch so that it is
guaranteed that the last row can be finalized. This extra key is needed
for the row fetcher (where we rely on the KV coming from the next row to
indicate that the last row is safe to finalize); however, it is not
needed for the cFetcher at all because the cFetcher is eagerly
finalizing each row once it knows that all KVs comprising that row have
been fetched.

Consider several cases:
- the table has only one column family - then we can finalize each
  row right after the first KV is decoded;
- the table has multiple column families:
  - KVs for all column families are present for all rows - then for
    each row, when its last KV is fetched, the row can be finalized
    (and cFetcher knows that);
  - KVs for some column families are omitted for some rows - then we
    will actually fetch more KVs than necessary, but we'll decode
    `limitHint` number of rows.

Touches: #72739.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
cc @nvanbenschoten this PR has some context why we need an extra key in some cases (asked in #72739).

I did a bit of historical investigation and found that we've had this extra key requirement since very long time ago (#4778), and I believe it is not necessary for the hard limits.

**Comment by nvanbenschoten** [comment]
Nice investigation! This seems like a great win in general, and especially for cases where the per-row iteration cost is high, like when there is a large amount of garbage between keys or when the select is acquiring locks due to a `FOR UPDATE` clause.

This second point begs the question: are we acquiring locks on more keys than expected when performing a `SELECT ... LIMIT ... FOR UPDATE` query? If so, could this lead to unexpected contention and blocking? Sure enough:

```sql
### client 1 ###

root@127.0.0.1:49554/defaultdb> create table kv (k int primary key, v int);
CREATE TABLE

root@127.0.0.1:49554/defaultdb> insert into kv (select generate_series(1, 10), 11);
INSERT 10

root@127.0.0.1:49554/defaultdb> begin;
BEGIN

root@127.0.0.1:49554/defaultdb  OPEN> select * from kv where k >= 2 limit 3 for update;
  k | v
----+-----
  2 | 11
  3 | 11
  4 | 11
(3 rows)
```

```sql
### client 2 ###

root@127.0.0.1:49554/defaultdb> select * from kv where k >= 6 limit 3 for update;
  k | v
----+-----
  6 | 11
  7 | 11
  8 | 11
(3 rows)

root@127.0.0.1:49554/defaultdb> select * from kv where k >= 5 limit 3 for update;

... this blocks ...
```

**Review by rharding6373 — APPROVED** [review]
Looks pretty good. I left a comment about test coverage of the hard limit, but otherwise nice work! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72963#-:-Mot903LB4t23LrQjLUo:b-pqun7d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/row/fetcher_test.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72963#-Mot8f08AGSx14LBtoRM:-Mot8f08AGSx14LBtoRN:b6el27y) ([raw file](https://github.com/cockroachdb/cockroach/blob/96724bb1d3aaa2792952800fe65bd75a2345facc/pkg/sql/row/fetcher_test.go#L474)):*
> ```Go
> 		// Set a limitHint of 1 to more quickly end the first batch, causing a
> 		// batch that ends between rows.
> 		rowinfra.MakeRowLimit(1),
> ```

Would it be possible to test with a hard limit, too?

**Review by yuzefovich — COMMENTED** [review]
The test failure in the row engine prompted me to look into this deeper, and I realized that both fetchers operate differently, and we can remove the extra key for both soft and hard limits in the vectorized engine whereas for the row engine we need the extra key in both cases. I added a comment describing why `cFetcher` can get away without that extra key, but the TL;DR is that cFetcher does more bookkeeping and finalizes each row eagerly whereas the `row.Fetcher` relies on the KV from the next row to be told that the previous row is safe to finalize. The good news is that in Nathan's example above with locking and soft limits the vectorized engine no longer grabs the lock on that next key; the bad news is that the row engine still has the old behavior, and I don't see an easy way to improve that (but it's also probably not of a very high priority).

I also added another tiny commit to fix up some comments. Please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72963#-:-Motuh5iBpANAMTOCd-6:b-kdakgt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rharding6373)

___
*[pkg/sql/row/fetcher_test.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72963#-Mot8f08AGSx14LBtoRM:-MotufrnD_KSw9Fcaxwa:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/96724bb1d3aaa2792952800fe65bd75a2345facc/pkg/sql/row/fetcher_test.go#L474)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Would it be possible to test with a hard limit, too?
</blockquote></details>

Removed.

**Review by rharding6373 — APPROVED** [review]
Sorry it didn't work out with the row fetcher :-( :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72963#-:-MotyhnOAtCjXM7_gcYE:b-sf4ui3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rharding6373)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
