### PR TITLE
rpc: avoid possible deadlock on Quiesce

### PR DESCRIPTION
**Pull request by tbg**
If a probe exited due to quiescing, previously it would not signal
`c.connFuture`. But if a caller was sitting on `c.ConnectNoBreaker`, it would
never get signaled as a result, which could lead to deadlocks during quiesce (as observed in CI).

The future is now always signaled with an error if the probe refuses to start or
exits due to the stopper quiescing.

No release note since bug in no release.

Epic: None

### CODE REVIEW

**Review by aliher1911 — APPROVED** [review]
💯

**Comment by tbg** [comment]
Commit not found, etc, something broke in bors, not a test failure.

bors r+

**Comment by tbg** [comment]
bors r+

https://github.com/cockroachdb/cockroach/pull/104864#issuecomment-1594748774

**Pull request merged**
