### PR TITLE
workload: switch tpcc to pgx and SQLRunner

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### workload: refactor tpccTx

Refactoring tpccTx to allow per-worker state. This will be necessary
for preparing statements in advance.

Release note: None

#### workload: use SQLRunner for queries without tuples

Switch TPCC to use pgx; use SQLRunner for queries that have a fixed
number of arguments.

Release note: None

Benchmark results here: https://docs.google.com/spreadsheets/d/13tcnYoRA3ArkZQtEHUMbJOOVdayyhgf43D94fFMiAPY/edit#gid=1942348447

The averages are about the same, but the distribution is very different (p50 through p95 are way better and p99, pMax are much worse). This is probably due to differences in how `pgx` and `gosql` manage their connection pools (we have 100 workers using 10 connections).

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Review by nvb — APPROVED** [review]
:lgtm: nice, I like this structure a lot.

> Reviewed 7 of 7 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-:-LOyAeH4CFQFNU-fK8XS:bxcip7d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/pgx_helpers.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOy9Sxw-MLazrW1UYX1:-LOy9Sxw-MLazrW1UYX2:b-rxcbp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/pgx_helpers.go#L128)):*
> ```Go
> ) (gosql.Result, error) {
> 	_, err := (*pgx.Tx)(tx).ExecEx(ctx, sql, nil /* QueryExOptions */, args...)
> 	return nil, err
> ```

Leave a comment about why this is ok.
___
*[pkg/workload/sql_runner.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyA09B8qU9Oc8xZ_1z:-LOyA09B8qU9Oc8xZ_2-:b-7vppxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L115)):*
> ```Go
> 		panic("already initialized")
> 	}
> 	sr.name = name
> ```

What's the point of this name?
___
*[pkg/workload/sql_runner.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOy9dRp5-oScrKc4WFv:-LOy9dRp5-oScrKc4WFw:b-qhkf32) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L206)):*
> ```Go
> // Query executes a query that returns rows.
> //
> // See pgx.Tx.Query.
> ```

Did you mean to change this?
___
*[pkg/workload/tpcc/order_status.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyAMl6-sSgzFv8fJUe:-LOyAMl6-sSgzFv8fJUf:b-lq63aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/tpcc/order_status.go#L53)):*
> ```Go
> 	oID        int
> 	oEntryD    time.Time
> 	oCarrierID pgtype.Int8
> ```

What prompted this change? Just interested.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31465)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/sql_runner.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyA09B8qU9Oc8xZ_1z:-LOyDtY55g1aIpaKDyW7:b-byjrtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L115)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's the point of this name?
</blockquote></details>

It's used to generate names for the prepared statements (e.g. `kv-1`, kv-2`, etc), figured it could help debugging things.
___
*[pkg/workload/tpcc/order_status.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyAMl6-sSgzFv8fJUe:-LOyE9hOAXnGMWEF3QMs:b-nphcni) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/tpcc/order_status.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What prompted this change? Just interested.
</blockquote></details>

We populate this from a result set (by passing it as a pointer to `Scan`). The implementor of Scan (pgx) needs to know how to work with that type.

**Review by nvb — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31465)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/workload/sql_runner.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyA09B8qU9Oc8xZ_1z:-LOyHzQF4cPJizche1cU:b-3839rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L115)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's used to generate names for the prepared statements (e.g. `kv-1`, kv-2`, etc), figured it could help debugging things.
</blockquote></details>

Ah ok, but `sr.name` is never actually used. That's what confused me.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-:-LOyRZxV8NYhN9ppbx6S:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/pgx_helpers.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOy9Sxw-MLazrW1UYX1:-LOyRKYBEb_tJqBhVmNd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/pgx_helpers.go#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a comment about why this is ok.
</blockquote></details>

Done.
___
*[pkg/workload/sql_runner.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOyA09B8qU9Oc8xZ_1z:-LOyR13-4hN17DhqFnrJ:bf83pa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L115)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ah ok, but `sr.name` is never actually used. That's what confused me.
</blockquote></details>

Ah, indeed, removed the field.
___
*[pkg/workload/sql_runner.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31465#-LOy9dRp5-oScrKc4WFv:-LOyRPdZ-ZLsNdlaSWMn:b-vfkka4) ([raw file](https://github.com/cockroachdb/cockroach/blob/134677fe199b0993faed64a45ebc99191d456e84/pkg/workload/sql_runner.go#L206)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to change this?
</blockquote></details>

No, fixed.

**Pull request merged**
