### PR TITLE
Update misc dependencies

### PR DESCRIPTION
**Pull request by RaduBerinde**
- [x] https://github.com/PuerkitoBio/goquery/compare/e1271ee3...2d2796f4
 - [x] https://github.com/StackExchange/wmi/compare/ea383cf3...5d049714
 - [x] https://github.com/andybalholm/cascadia/compare/349dd020...901648c8
 - [x] https://github.com/armon/go-radix/compare/1fca145d...1a2de0c2
 - [x] https://github.com/axiomhq/hyperloglog/compare/baba800b...e8c19f17
 - [x] https://github.com/cenkalti/backoff/compare/2ea60e5f...62661b46
 - [x] https://github.com/certifi/gocertifi/compare/3fd9e1ad...deb3ae2e
 - [x] https://github.com/client9/misspell/compare/59894abd...b90dc15c
 - [x] https://github.com/cpuguy83/go-md2man/compare/1d903dcb...20f5889c
 - [x] https://github.com/davecgh/go-spew/compare/346938d6...8991bc29
 - [x] https://github.com/dustin/go-humanize/compare/77ed8078...9f541cc9
 - [x] https://github.com/eapache/go-resiliency/compare/6800482f...ea41b0fa
 - [x] https://github.com/eapache/go-xerial-snappy/compare/bb955e01...776d5712
 - [x] https://github.com/eapache/queue/compare/ded5959c...44cc805c
 - [x] https://github.com/elastic/gosigar/compare/306d5198...237dff72
 - [x] https://github.com/ghemawat/stream/compare/78e682ab...696b145b
 - [x] https://github.com/go-logfmt/logfmt/compare/390ab793...07c9b44f
 - [x] https://github.com/golang-commonmark/markdown/compare/11a7a839...a8f13905
 - [x] https://github.com/google/btree/compare/e89373fe...4030bb1f
 - [x] https://github.com/google/go-github/compare/e48060a2...35781f7f
 - [x] https://github.com/google/go-querystring/compare/53e6ce11...44c6ddd0
 - [x] https://github.com/google/pprof/compare/d723c723...3ea8567a
 - [x] https://github.com/googleapis/gax-go/compare/317e0006...b001040c
 - [x] https://github.com/gorilla/websocket/compare/ea4d1f68...66b9c49e
 - [x] https://github.com/ianlancetaylor/demangle/compare/4883227f...5e5cf602
 - [x] https://github.com/kisielk/errcheck/compare/b1445a9d...55d8f507
 - [x] https://github.com/kisielk/gotool/compare/d6ce6262...80517062
 - [x] https://github.com/knz/go-libedit/compare/e51c9742...f49778aa
 - [x] https://github.com/kr/pretty/compare/cfb55aaf...73f6ac0b
 - [x] https://github.com/kr/text/compare/7cafcd83...e2ffdb16
 - [x] https://github.com/linkedin/goavro/compare/9e3ffbc2...1beee2a7
 - [x] https://github.com/mattn/go-isatty/compare/0360b2af...6ca4dbf5
 - [x] https://github.com/mattn/go-runewidth/compare/9e777a83...ce7b0b5c
 - [x] https://github.com/matttproud/golang_protobuf_extensions/compare/3247c845...c12348ce
 - [x] https://github.com/mitchellh/reflectwalk/compare/63d60e9d...eecee6c9
 - [x] https://github.com/montanaflynn/stats/compare/72625ec1...db72e6ca
 - [x] https://github.com/nightlyone/lockfile/compare/6a197d5e...0ad87eef
 - [x] https://github.com/nlopes/slack/compare/8ab4d0b3...b9033a72
 - [x] https://github.com/olekukonko/tablewriter/compare/b8a9be07...e6d60cf7
 - [x] https://github.com/opencontainers/image-spec/compare/ab7389ef...d6009917
 - [x] https://github.com/pierrec/lz4/compare/08c27939...635575b4
 - [x] https://github.com/prometheus/client_golang/compare/96778905...505eaef0
 - [x] https://github.com/prometheus/client_model/compare/6f380601...5c3871d8
 - [x] https://github.com/prometheus/common/compare/1bab55dd...4724e925
 - [x] https://github.com/prometheus/procfs/compare/8b1c2da0...1dc9a6cb
 - [x] https://github.com/rcrowley/go-metrics/compare/1f30fe90...3113b840
 - [x] https://github.com/russross/blackfriday/compare/4048872b...05f32357
 - [x] https://github.com/shirou/gopsutil/compare/4a180b20...0f70a4a0
 - [x] https://github.com/sirupsen/logrus/compare/f006c2ac...bcd833df
 - [x] https://github.com/spf13/cobra/compare/7b2c5ac9...ef82de70
 - [x] https://github.com/spf13/pflag/compare/e57e3eeb...298182f6
 - [x] https://github.com/stretchr/testify/compare/69483b4b...f35b8ab0

### CODE REVIEW

**Comment by danhhz** [comment]
Thanks for the heads up in slack! We're (sadly) still not done with changefeed work in 2.1.x and I'd greatly prefer we don't upgrade sarama until we are. I was planning to bump it myself slightly later in the release cycle.

**Comment by benesch** [comment]
Signing off on StackExchange/wmi and google/go-github.

**Comment by RaduBerinde** [comment]
@danhhz thanks for that, I am removing `sarama`

**Comment by benesch** [comment]
Signing off on ghemawat/stream, ianlancetaylor/demangle, hashicorp/go-version, cenkalti/backoff, and dustin/go-humanize.

**Comment by couchand** [comment]
Signing off on elastic/gosigar & google/go-querystring.

**Comment by couchand** [comment]
Signing off on prometheus/client_model and prometheus/procfs.

**Comment by RaduBerinde** [comment]
I am removing `hashicorp/go-version` from the updates since I couldn't get it to work (the problem: `detected server version: 2.2.0-alpha.20181119-650-g0479b81, required: >= 1.2-alpha.20171026`). I filed https://github.com/hashicorp/go-version/issues/43

**Comment by RaduBerinde** [comment]
I've been reviewing changes but there's a lot of packages. CCing more people who might be able to help @petermattis @tbg @a-robinson @nvanbenschoten

**Comment by benesch** [comment]
Signing off on kisielk/gotool, mattn/go-isatty, mitchellh/reflectwalk, kr/pretty, kr/text, and google/pprof.

**Comment by benesch** [comment]
Also signing off on olekukonko/tablewriter and nlopes/slack.

**Comment by tbg** [comment]
Looks like all the boxes are checked except for logrus. Unfortunately that has 224 commits. We use it here:

```
vendor/github.com/nlopes/slack/logger.go
vendor/github.com/jackc/pgx/CHANGELOG.md
vendor/github.com/jackc/pgx/README.md
vendor/github.com/jackc/pgx/doc.go
vendor/github.com/golang/dep/gps/solve_failures.go
vendor/github.com/docker/docker/pkg/term/windows/windows.go
```

**Review by tbg — APPROVED** [review]

**Comment by RaduBerinde** [comment]
I looked through the diffs for `logrus` as well, there weren't a huge number of changes to non-test code.

**Pull request merged**
