### PR TITLE
roachtest: pull a debug zip into artifacts when a test fails

### PR DESCRIPTION
**Pull request by ajwerner**
Tested by adding a test that failed and ensured that a debug zip got copied over. Let me know if you want more testing.

Inspired by #32497. 

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This is a good idea, though there is a bit of duplication in fetching both the logs and the debug zip (which will contain the logs). Also, I'm anxious about your attempt at unifying the code paths for fetching the logs on failure and timeout. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-:-LVLCbvK9m-qlnjUHMUl:bdn9xbm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLB7839mdBXZsoCw1Y:-LVLB7839mdBXZsoCw1Z:b50378) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/cluster.go#L907)):*
> ```Go
> func (c *cluster) FetchDebugZip(ctx context.Context) error {
> 	if c.nodes == 0 {
> 		// For tests.
> ```

Nit: this comment isn't terribly interesting. Perhaps `No nodes implies nothing to do`.
___
*[pkg/cmd/roachtest/cluster.go, line 923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLBKoc5x7AL-u6N__2:-LVLBKoc5x7AL-u6N__3:b62scyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/cluster.go#L923)):*
> ```Go
> 	}
> 	err := execCmd(execCtx, c.l, roachprod, "ssh", c.name+":1", "--",
> 		"./cockroach", "debug", "zip", "--insecure", zipName)
> ```

Does `debug zip` take a `--url` parameter. If yes, it would be better to pass `{pgurl:1}` instead of `--insecure`. `{pgurl:1}` should work correctly on secure clusters.
___
*[pkg/cmd/roachtest/test.go, line 1107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLC42L3CzjGrYN5DRo:-LVLC42L3CzjGrYN5DRp:b-90w3vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/test.go#L1107)):*
> ```Go
> 			case <-time.After(timeout):
> 				t.printfAndFail("test timed out (%s)\n", timeout)
> 				close(timedOut)
> ```

I'm anxious about changing the logic here as I don't think there is sufficient test coverage. I'm guessing you're trying to unify fetching of logs and debug zips on failure and timeout. Rather than the change here, I'd prefer to see the addition of an `onFailure` closure which fetches the logs and debug zip.

One problem I suspect your change has is that closing `timedOut` won't actually kill the test, while the previous code will destroy the cluster which would kill the test.

**Review by ajwerner — COMMENTED** [review]
I'll update the logic to fetch the debug zip on timeout or failure and to only fetch the logs in the happy case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-:-LVLEJ_T2Oc72Zdu1XeW:bs103e2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 907 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLB7839mdBXZsoCw1Y:-LVLDsbt800JRnNIYmCy:b8bhi9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/cluster.go#L907)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: this comment isn't terribly interesting. Perhaps `No nodes implies nothing to do`.
</blockquote></details>

Copied from FetchLogs, will update both.
___
*[pkg/cmd/roachtest/cluster.go, line 923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLBKoc5x7AL-u6N__2:-LVLEYg_8Ql1VYnt-Z2c:bhy9ot6) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/cluster.go#L923)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does `debug zip` take a `--url` parameter. If yes, it would be better to pass `{pgurl:1}` instead of `--insecure`. `{pgurl:1}` should work correctly on secure clusters.
</blockquote></details>

Will do.
___
*[pkg/cmd/roachtest/test.go, line 1107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLC42L3CzjGrYN5DRo:-LVLE01m-MmlxkeBiHkM:b-myzvhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/test.go#L1107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm anxious about changing the logic here as I don't think there is sufficient test coverage. I'm guessing you're trying to unify fetching of logs and debug zips on failure and timeout. Rather than the change here, I'd prefer to see the addition of an `onFailure` closure which fetches the logs and debug zip.

One problem I suspect your change has is that closing `timedOut` won't actually kill the test, while the previous code will destroy the cluster which would kill the test. 
</blockquote></details>

I did not think about the destruction of the cluster killing the test. It just seemed like we were fetching the logs unconditionally and again when timing out, though now I'm realizing that once we've destroyed the cluster, the second fetching of the logs will fail. I'll revert this.

**Review by ajwerner — COMMENTED** [review]
Updated, PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-:-LVLI_xq659SYSazhCKy:b1e9dsp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cluster.go, line 923 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLBKoc5x7AL-u6N__2:-LVLIdJOEOwGEJTh0mvU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/cluster.go#L923)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/test.go, line 1107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-LVLC42L3CzjGrYN5DRo:-LVLIhoO1IZRuWH-QLYG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20f2a97793914870329c57fd7c0a97c90d23f023/pkg/cmd/roachtest/test.go#L1107)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did not think about the destruction of the cluster killing the test. It just seemed like we were fetching the logs unconditionally and again when timing out, though now I'm realizing that once we've destroyed the cluster, the second fetching of the logs will fail. I'll revert this. 
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-:-LVLJ2Yi83ihULMeONi5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33485#-:-LVLP4vnC4UZ4DzNE347:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
bors r=petermattis

**Pull request merged**
