### PR TITLE
sql: minor fixes for virtual computed columns

### PR DESCRIPTION
**Pull request by ajwerner**
See individual commits.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61713#-:-MVMtPrGARn9BJhsl4fc:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by rafiss** [comment]
Shall we get this into `release-21.1`?

**Comment by ajwerner** [comment]
yes, backport inbound

**Pull request merged**
