### PR TITLE
sql, server: surface full scan and last retry reason properties for active queries

### LINKED ISSUE #79124: sql, server, ui: surface more information on active queries and transactions in active executions API
Add the following information for the active executions respons for active executions v2:

- lastRetryReason
- full scan

Figma: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=6152%3A136586

Jira issue: CRDB-14586

### PR DESCRIPTION
**Pull request by xinhaoz**
### Commit 1: sql, server: add IsFullScan to active query meta
Part of https://github.com/cockroachdb/cockroach/issues/79124

This commit adds additional ways to observe whether or not a
running query contains a full table or index scan.

The property isFullScan is now tracked in the queryMeta struct
for active queries. The field is included in the ListSessions
api response for the active query in a session under the field
`IsFullScan`. The column `full_scan` is also added to the
{cluster,node}_queries virtual tables and is also added to
the `SHOW QUERIES` command.

Release note (sql change, api change): Information has been
added describing whether a query contains a full table or
index scan. Note that this information is only valid when
the query is in the `executing` phase.

The `ListSessions` api includes this info under the field
`is_full_scan` in the active query for a session.

The `crdb_internal.{cluster,node}_queries` has a new column
`full_scan`. This column is included in the `SHOW QUERIES`
command.

### Commit 2: server: add LastAutoRetryReason to ListSessions response
Closes https://github.com/cockroachdb/cockroach/issues/79124

This commit adds additional ways to observe the reason for an
automatic retry for a currently running transaction. The field
`LastAutoRetryReason` is added to the `ListSessions` response
under the field `LastAutoRetryReason` which is accessible through
the session's `ActiveTxn` field. This field is a string describing
the error causing an automatic retry  for the current transaction.
The same information is also added to the `{cluster,node}_transactions`
virtual tables and the `SHOW TRANSACTIONS` command under the column
`last_auto_retry_reason`.

Release note (api change, sql change): The ListSessions api has a new
field `last_auto_retry_reason` under the `active_txn` field for a
session. This field contains the string describing the retry
reason or nil if none exists.

This is also surfaced in the `crdb_internal.{cluster,node}_transactions`
tables and the `SHOW TRANSACTIONS` command under the `last_auto_retry_reason`
column.

### CODE REVIEW

**Comment by rickystewart** [comment]
@xinhaoz -- this PR didn't have a CI run due to a TC misconfiguration. If you force-push to this branch now you can trigger another CI run.

**Review by jocrl — COMMENTED** [review]
🎉
Does this need/need to update tests?
Otherwise, LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-:-N2lfXlj2gE3GN4gzA_Z:b-wpbrqd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 6 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/server/serverpb/status.proto` line 965 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-gZ9AE8tM_yJmLQdL:-N3-gZ9AE8tM_yJmLQdM:bx96l3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/server/serverpb/status.proto#L965)):*
> ```protobuf
>   google.protobuf.Timestamp end = 15
>       [ (gogoproto.nullable) = true, (gogoproto.stdtime) = true ];
> ```

nit: remove extra line
___
*[`pkg/sql/crdb_internal.go` line 1627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-hRLFD2hQUMHzRebO:-N3-hRLFD2hQUMHzRebP:b5c7wkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/sql/crdb_internal.go#L1627)):*
> ```Go
>   num_retries INT,                 -- the number of times the transaction was restarted
>   num_auto_retries INT,            -- the number of times the transaction was automatically restarted
>   last_auto_retry_reason STRING    -- the number of times the transaction was automatically restarted
> ```

this definition needs to be updated
___
*[`pkg/sql/logictest/testdata/logic_test/create_statements` line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-i3D68AZ_WgKN6qNF:-N3-i3D68AZ_WgKN6qNG:bqnfhht) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/sql/logictest/testdata/logic_test/create_statements#L306)):*
> ```
>    distributed BOOL NULL,
>    phase STRING NULL,
>    full_scan BOOL NULL
> ```

do we need to create migrations when there is a change on crdb_internal tables?

**Review by xinhaoz — COMMENTED** [review]
It doesn't seem like we have a precedent of testing for the validity of fields like this explicitly. Is this something we want to do moving forward? cc @maryliag 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-:-N30H1opCOMWW3-HnHcY:b-tqjal1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/serverpb/status.proto` line 965 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-gZ9AE8tM_yJmLQdL:-N3-sTHb5xp5fiS4tLDs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/server/serverpb/status.proto#L965)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove extra line
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 1627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-hRLFD2hQUMHzRebO:-N3-shBC7K1NZqLTWkT7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/sql/crdb_internal.go#L1627)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this definition needs to be updated
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/create_statements` line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-N3-i3D68AZ_WgKN6qNF:-N3-wwo-5R1GpSzGiAXb:b-5ddch6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9a35c1f76052fb0693225cad99860a54e4cdb8/pkg/sql/logictest/testdata/logic_test/create_statements#L306)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

do we need to create migrations when there is a change on crdb_internal tables?
</blockquote></details>

Checked some PRs with similar changes and it does not seem so!

**Review by maryliag — COMMENTED** [review]
great job!
Regarding tests: don't we have any fixtures/stories files for the active queries that needs to be updated?

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-:-N34w42G2Hut-IRLOene:b-j78cld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
> great job! Regarding tests: don't we have any fixtures/stories files for the active queries that needs to be updated?
> 
> > Reviewed 9 of 9 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-:-N34w42G2Hut-IRLOene:b-j78cld)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

Yeah, I've updated them already, but we don't have any server-side testing that properly checks/validates all the fields in the sessions response. If that is something we want to do, I can either add a test just for the fields added in this PR and file a ticket to do the rest, or file a ticket to add all the tests at once. LMK!

**Review by maryliag — APPROVED** [review]
let's go with creating an issue to add better tests in general for this type of changes
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81531#-:-N3ZkZwD6Md92VgZJMHN:bt1ch3o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
bors r=maryliag
Issue filed: https://github.com/cockroachdb/cockroach/issues/82353

**Pull request merged**
