### PR TITLE
storage,keys: rename RaftTombstone to RangeTombstone, delete RaftTombstoneIncorrectLegacyKey

### PR DESCRIPTION
**Pull request by irfansharif**
**storage,keys: rename RaftTombstone to RangeTombstone**

    We've been using the RaftTombstone key to guard against the re-use of
    replica IDs. There's no "raft" data stored as part of this, and was a
    visible wart in #44410 where it was a key prefixed with "Raft" but
    decidedly not one assigned to the raft engine. RangeTombstone is a more
    appropriate name to be using here.

    Release note: None

**keys: delete RaftTombstoneIncorrectLegacyKey**

    RaftTombstoneIncorrectLegacyKey used to return a system-local key for a
    raft tombstone. This key was accidentally made replicated though it
    shouldn't have been. This was addressed in #21120 (which renamed the old
    tombstone key to `RaftIncorrectLegacyTombstoneKey` and introduced the
    correctly unreplicated `RaftTombstoneKey`).

    `RaftIncorrectLegacyTombstoneKey` was slated to be removed for
    binary versions > 2.1, and was long overdue. This PR just closes the
    loop on this issue.

    Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but @tbg should give this a :thumbsup: as well before merging.

> Reviewed 4 of 4 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44550#-:-Lzrl6RREuDq_YdxVVFy:b-rn8130)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/keys/constants.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44550#-Lzrkmi2C3JFxUtCghIX:-Lzrkmi2C3JFxUtCghIY:b-vbzjw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/912a4f0914567a08c0ad74dd9cda24a09c6e7e16/pkg/keys/constants.go#L113)):*
> ```Go
> 	// together or individually in a single scan.
> 	localRangeIDUnreplicatedInfix = []byte("u")
> 	// LocalRangeTombstoneSuffix is the suffix for the range tombstone.
> ```

Give this a small comment about why this key is "rf.." instead of "rl.."

**Review by irfansharif — COMMENTED** [review]
TFTR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44550#-:-LzrrUfkAuxkdONtFvlq:b-814g87)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44550#-Lzrkmi2C3JFxUtCghIX:-LzrrZFwDXE1Qfx4yP-b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/912a4f0914567a08c0ad74dd9cda24a09c6e7e16/pkg/keys/constants.go#L113)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a small comment about why this key is "rf.." instead of "rl.."
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
@tbg: Gentle ping.

**Review by tbg — APPROVED** [review]
:lgtm: sorry about the wait.

> Reviewed 4 of 4 files at r1, 20 of 22 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44550#-:-M-ENAOXEO3jpw9-Kxao:baf40ud)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by irfansharif** [comment]
TFTRs

**Comment by irfansharif** [comment]
bors retry

**Pull request merged**
