### PR TITLE
sql,ccl: improve the implementation of the TENANT clauses in sql syntax

### PR DESCRIPTION
**Pull request by knz**
This ensures that the tenant ID is subject to formatting flags.

Release justification: bug fix

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
I'm not super well-versed in the backup code, but it looks to me that making this support more complex expressions is actually not too hard. Might be more elegant!

**Review by rafiss — APPROVED** [review]
i think this change is still an improvement, so i vote to merge this

does it need to change to account for the cluster setting syntax that just merged?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77218#-:-MxBl4G42sGVVlNzIvWf:b-fh52t1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @knz, and @stevendanna)

___
*[pkg/sql/sem/tree/tenant.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77218#-MxBkunR5gUCn2iDDc1T:-MxBkunR5gUCn2iDDc1U:b-vwcl9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a39052600df2789859bd092f89254943c1ce7e14/pkg/sql/sem/tree/tenant.go#L28)):*
> ```Go
> 	// the case when the value was anonymized. In other places, the
> 	// value used for anonymized integer literals is 0, but we can't use
> 	// 0 for TenantID as this is refused during parsing, nor can we use
> ```

do we have a good reason for rejecting 0 at the parsing step rather than rejecting it during semantic analysis?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @rafiss, and @stevendanna)

___
*[pkg/sql/sem/tree/tenant.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77218#-MxBkunR5gUCn2iDDc1T:-MxECBgW0qouFZ0x5cYd:bji7ncv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a39052600df2789859bd092f89254943c1ce7e14/pkg/sql/sem/tree/tenant.go#L28)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we have a good reason for rejecting 0 at the parsing step rather than rejecting it during semantic analysis?
</blockquote></details>

IMHO, no, but as long as the tree object embeds a roachpb.TenantID, it's going to be checked in roachpb.MakeTenantID.

My preference would be for this to use an Expr, and have the translation Expr -> TenantID done at planning time (with expr eval).

**Review by knz — COMMENTED** [review]
> does it need to change to account for the cluster setting syntax that just merged?

Oh good catch. That's a different situation though. This can be made to support expressions right away. Actually, the way this syntax was implemented... :man_facepalming:  Good time to clean it up. Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77218#-:-MxOpzLuCQnXtEMOsc0S:b-lsjem4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @rafiss, and @stevendanna)

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
Just noticed SHOW CLUSTER SETTING FOR TENANT was affected too. Fixing that as well.

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
This is failing in CI in the backupccl package, seemingly for unrelated reasons? Unsure. Will need to look next week.

**Comment by knz** [comment]
added a skip

bors r=rafiss

**Comment by rafiss** [comment]
I noticed this changed the syntax to `ALTER ALL TENANTS` instead of `ALTER TENANT ALL`. Is that required?

I guess it's not a big deal, but `ALTER ALL TENANTS` is misaligned from other syntax we've implemented, like `ALTER ROLE ALL ... SET ...`. (That syntax was borrowed from [Postgres](https://www.postgresql.org/docs/current/sql-alterrole.html).)

**Comment by knz** [comment]
yes I changed this to avoid a syntax ambiguity (`all` is a valid identifier)

> I guess it's not a big deal, but ALTER ALL TENANTS is misaligned from other syntax we've implemented, like ALTER ROLE ALL

AFAIK `ROLE` does not accept an expression in pg's dialect? And if we wanted it to, it'd probably be painful?

**Comment by knz** [comment]
The alternative was `TENANT *`  since `*` is an expression. But I thought this would feel a little too "magic".

**Comment by knz** [comment]
I was not aware of this lookahead technique (or, I had forgotten it)
In any case, I felt confident merging this because this feature is not restricted by backward-compatibility. If you think that's important, feel free to propose the LA solution.

**Comment by knz** [comment]
(regardless of the RFC, SQL is meant to be "readable english", and I find "TENANT ALL"  less grammatical and less readable than "ALL TENANTS")

**Comment by rafiss** [comment]
Sure, I don't mind making that PR. Just wanted to understand the context before I did.

**Pull request merged**
