### PR TITLE
sqlccl: handle descriptor changes in MVCC BACKUP/RESTORE

### PR DESCRIPTION
**Pull request by dt**
Release note (enterprise change): experimental ‘revision_history’ backup/restore handles schema changes.

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_-1ZE966XUj3Rn86j:-L3_-1ZE966XUj3Rn86k:b-7ql98r) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L125)):*
> ```Go
> }
> 
> // getRelventDescChanges find the changes between start and end time to the SQL
> ```

finds

---

*[pkg/ccl/sqlccl/backup.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_-w-4GcIlSVzYEnI8:-L3_-w-4GcIlSVzYEnI9:b-8s5zgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L128)):*
> ```Go
> // descriptors matching `descs` or `expandedDBs`, ordered by time. A descriptor
> // revision matches if it is an earlier revision of a descriptor in descs (same
> // ID) or has a a parentID in `expanded`. Deleted descriptors are represented as
> ```

"a a"

---

*[pkg/ccl/sqlccl/backup.go, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dcwc7PNA3ZvJ2Cpfu:-L3dcwc7PNA3ZvJ2Cpfv:bgife7) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L130)):*
> ```Go
> // ID) or has a a parentID in `expanded`. Deleted descriptors are represented as
> // nil.
> func getRelventDescChanges(
> ```

Relvent is misspelled

---

*[pkg/ccl/sqlccl/backup.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_05LGch-Lo6rcOj65:-L3_05LGch-Lo6rcOj66:b-iiixk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L143)):*
> ```Go
> 	}
> 
> 	// If not descriptors changed, we can just stop now and have RESTORE use the
> ```

not -> no

---

*[pkg/ccl/sqlccl/backup.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dcmK4RWEHRNPxLTbT:-L3dcmK4RWEHRNPxLTbU:bwuowpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L192)):*
> ```Go
> 
> 	for _, change := range allChanges {
> 		if _, ok := interestingIDs[change.ID]; ok {
> ```

Why don't need to care about interestingParents here too?

---

*[pkg/ccl/sqlccl/restore.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dgGnWaB_xSFNbTf_6:-L3dgGnWaB_xSFNbTf_7:b-ec2zoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/restore.go#L84)):*
> ```Go
> 
> 	for _, b := range backupDescs {
> 		if asOf.Less(b.StartTime) {
> ```

In the case where asOf is less than the first b.StartTime, this will set lastBackupDesc to last descriptor in backupDescs from 5 lines above. Is that correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_-1ZE966XUj3Rn86j:-L3iRTZ_XupTGoOrCeSC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L125)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

finds
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_-w-4GcIlSVzYEnI8:-L3iRU5nFodd1GUigQpf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L128)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

"a a"
</blockquote></details>

Done

---

*[pkg/ccl/sqlccl/backup.go, line 130 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dcwc7PNA3ZvJ2Cpfu:-L3iRka1a-vQAlOywKDr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L130)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Relvent is misspelled
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3_05LGch-Lo6rcOj65:-L3iRnbpp12RRFgVkTqj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L143)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

not -> no
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dcmK4RWEHRNPxLTbT:-L3iU1QFMX8XIW9-dTth:b-giy5il) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/backup.go#L192)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Why don't need to care about interestingParents here too?
</blockquote></details>

yep, nice catch -- I meant to do this and forgot once I actually wrote it up. 

While we've already used interestingParents above to seed interestingIDs with any tables that were in an interesting DB at the beginning of the interval -- and have added all tables in the matched set at the end of the window too -- if a table is moved into the interesting parents during the window, we need to note that as well -- not only is _that_ and interesting change, but we need to then expand interestingIDs in case it is also deleted.  Also added more comments to this effect.

---

*[pkg/ccl/sqlccl/restore.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L3dgGnWaB_xSFNbTf_6:-L3ijboOcMdV4_X5_2S8:bw7nr2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/365effaa7348aa3837c4b88911f1d2f99c442aa7/pkg/ccl/sqlccl/restore.go#L84)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

In the case where asOf is less than the first b.StartTime, this will set lastBackupDesc to last descriptor in backupDescs from 5 lines above. Is that correct?
</blockquote></details>

That is _not_ correct, but we have a check at the very beginning of RESTORE ... AS OF SYSTEM TIME that we have an MVCC backup covering that time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717)*

**Comment by dt** [comment]
Okay, added tests with adding and drop tables and indexes, truncating and moving a table in and out of the target DB, RFAL.

The main missing piece left is non-DB backups, where we'll need #21895, but I don't want to block on that -- as discussed with @dianasaur323, the `BACKUP DATABASE` + `RESTORE DATABASE` workflow is our top priority, and that doesn't depend on #21895 since the DB of both the pre- and post-truncate table is the same.

**Comment by mjibson** [comment]
:lgtm: I think? This stuff is complicated.

---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.go, line 354 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L4djjeYpQ7PyciTfYJm:-L4djjeZr9phD5E31QEo:b-1sevpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/986bb9a8c10a2145d66f6c146e2da3153d23a724/pkg/ccl/sqlccl/backup.go#L354)):*
> ```Go
> 	}
> 	// if there are desc revisions, ensure that we also add any index spans
> 	// in them that we didn't already get above.
> ```

Can you list the conditions where this happens in the comment?

---

*[pkg/ccl/sqlccl/restore.go, line 110 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L4dky-A8giHNyxv53YM:-L4dky-A8giHNyxv53YN:bw10f4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/986bb9a8c10a2145d66f6c146e2da3153d23a724/pkg/ccl/sqlccl/restore.go#L110)):*
> ```Go
> 	for _, desc := range byID {
> 		if t := desc.GetTable(); t != nil {
> 			// A table revsions may have been captured before it was in a DB that is
> ```

revsions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-:-L4dl648DAJaZ5E6DpAl:b7yzwwq)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 354 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L4djjeYpQ7PyciTfYJm:-L4fdhs-KRdnfimyQUek:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/986bb9a8c10a2145d66f6c146e2da3153d23a724/pkg/ccl/sqlccl/backup.go#L354)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Can you list the conditions where this happens in the comment?
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/restore.go, line 110 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717#-L4dky-A8giHNyxv53YM:-L4fcJDHXzJwQG_A_nG5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/986bb9a8c10a2145d66f6c146e2da3153d23a724/pkg/ccl/sqlccl/restore.go#L110)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

revsions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21717)*

**Pull request merged**
