### PR TITLE
sql: Rename type codes (patch 2/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Rename types.ColumnType_SemanticType to types.SemanticType.
Rename types.ColumnType_VisibleType to types.VisibleType.
Rename visible type constants to be prefixed with VisibleType_ in order to
keep them separate from semantic types (less chance for confusion).

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I have reviewed nearly all files but a few. Please clarify what is happening with `UUID` vs `Uuid`. I *seem* to understand that the all-caps name is for the ColumnType, whereas the `Uuid` form is for the `types.T` instance. Is my understanding correct?

In any case, please include the explanation on this specific point in the commit message. This will help future  readers to follow along.

Thanks

> Reviewed 74 of 87 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc5bhzC3OymzqN8ynZb:b2h50xz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_decompose_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5aEmDA2WTLOAurnot:-Lc5aEmDA2WTLOAurnou:b-ulpzn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ad8942882af47b5ab8c967a02193154b8ff835/pkg/sql/opt_decompose_test.go#L37)):*
> ```Go
> 		ParentID: 1000,
> 		Columns: []sqlbase.ColumnDescriptor{
> 			{Name: "a", Type: types.ColumnType{SemanticType: types.INT}},
> ```

Can you file an issue / to-do item to add uuid and inet columns to this list. Thanks
___
*[pkg/sql/distsqlrun/materializer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5agSS5jC0Zk8Fhg3o:-Lc5agSS5jC0Zk8Fhg3p:bkb91v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/distsqlrun/materializer.go#L76)):*
> ```Go
> 		ct := typs[i]
> 		switch ct.SemanticType {
> 		case types.ColumnType_BOOL:
> ```

please add a to-do item to add collated strings, uuids and inet values to this list.
___
*[pkg/sql/distsqlrun/materializer_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5aX2T8fhCk1pHwSeq:-Lc5aX2U7p2jFPRnfGi8:bkb91v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/distsqlrun/materializer_test.go#L93)):*
> ```Go
> 		{SemanticType: types.ColumnType_STRING},
> 		{SemanticType: types.ColumnType_BYTES},
> 		{SemanticType: types.ColumnType_NAME},
> ```

please add a to-do item to add collated strings, uuids and inet values to this list.
___
*[pkg/sql/exec/types/conv/conv.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5arl1CVbv0I-C9XYS:-Lc5arl1CVbv0I-C9XYT:b-nqg0yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/exec/types/conv/conv.go#L29)):*
> ```Go
> 
> // FromColumnType returns the T that corresponds to the input ColumnType.
> func FromColumnType(ct semtypes.ColumnType) types.T {
> ```

I am making a note of this for myself, but also as a question: what becomes of this function throughout #36598? It seems to me we would prefer this not to exist.
(I hope to be able to discard this comment myself as I discover/learn the answer during the review -- however, if you know the answer @andy-kimball please advise preemptively.)
___
*[pkg/sql/sqlbase/structured_test.go, line 1329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5baNVC3pYtGY3zRrJ:-Lc5baNVC3pYtGY3zRrK:b19vni5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/sqlbase/structured_test.go#L1329)):*
> ```Go
> }
> 
> func TestDatumTypeToColumnSemanticType(t *testing.T) {
> ```

Why did you remove this function? Has it moved?

**Comment by knz** [comment]
This is the first commit where the linter fails.
Please fix the linter in here, so that we get the confirmation of a green TC build at this point (so as to facilitate the interpretation of possible red builds in the later patches).

Regarding this point as to how to fix the linter: https://github.com/cockroachdb/cockroach/pull/36598#issuecomment-480892560

At this point in the patch series both `UUID` and `Uuid` exist side-by-side. The linter needs to tolerate both.

However it's also not great idiomatic Go to have two identifiers that differ only by case. Alternatively, you can consider renaming the column type `UUID` to `COLTYPE_UUID` (for the prefix of the patch series until the two types merge).

**Comment by RaduBerinde** [comment]
AFAICT the final state after the larger PR is that `UUID` is the semantic type (`SemanticType` proto enum) and `Uuid` is the "full type" (`T`).

I agree this is a little confusing. Could we move the semantic types enum to a different package (maybe `types/semtypes`)? I think we can split the proto and it will still be compatible.

**Review by andy-kimball — COMMENTED** [review]
I agree that `types.INT` vs. `types.Int` is not idiomatic Go. But neither was `types.ColumnType_INT`. All I did was shorten one un-idiomatic form into another. As for moving enum into a different package, that would impede discoverability. I think it'd be confusing/unexpected for new developers that an enum is in a different package. I could see people getting confused by that, just like they might get confused by caps vs. non-caps. Are there any other ideas?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc6SUD94Aup3T1Ff-Bc:b-r9kgof)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by RaduBerinde** [comment]
Not worried about whether a name is idiomatic, just about the fact that we have *both* `INT` and `Int` which mean different things.

Another idea is to rename `SemanticType` to `Family` and leave them as `Family_INT`? Or give them custom names like `IntFamily`? (not sure if gogoproto gives you that possibility, but we could define our own `const IntFamily = Family_INT`.

**Comment by knz** [comment]
I don't think we need to rework the code / logic really, because in the end this gets "flattened" in a later patch.

I just think it's important to explain what is going on in the commit message.

**Comment by knz** [comment]
> I don't think we need to rework the code / logic really, because in the end this gets "flattened" in a later patch.

Radu convinced me that my understanding was wrong.

I am not too fond of the end result in  #36598 but I think we can proceed as follows:

- let the name change in this patch remain as-is (so as to not disrupt the remainder of the patch series)

- consider adding one more commit to the series to rename the all-caps names to `TypeCode_XXX` -- to highlight that they are numeric magic values as opposed to objects.

**Review by andy-kimball — COMMENTED** [review]
How about `types.IntCode`, `types.StringCode`, etc? I could live with that. I think `TypeCode_INT`, etc. is too verbose (and not idiomatic either).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc6vlm15LcYgEDcqP3x:b3hlyjz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
I could do that as follow-on patch to the PR, as you say, to avoid too much disruption. Would be easy with GoLand rename.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc6wGOR3RHVPc5GZhMU:b-q1a515)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by andy-kimball — COMMENTED** [review]
If we went that direction, would it be better to call the method `TypeCode` instead of `SemanticType`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc6wgGy9WMs3RBHa9wW:b8r6x77)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by knz** [comment]
Your proposal is good. OK to add as an extra patch.

Meanwhile there are also a few comments in my review at the top that can be addressed here.

**Comment by RaduBerinde** [comment]
Yes, I'd rename `SemanticType()` to `TypeCode()` or even better just `Code()`. I still like `Family` better than `Code` though but either works.

**Comment by andy-kimball** [comment]
OK, @knz do you have an opinion of `Code` vs. `Family`? I'd be OK with either. We did use the term `Family` previously, so there's precedent with using that term.

**Comment by knz** [comment]
No clear opinion. 
The name should convey that each value corresponds to multiple types. Family would work, but so does "kind" perhaps.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Review by andy-kimball — COMMENTED** [review]
OK, I'll use `Family` then, as Radu suggests, in a follow-on PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc9ASOq6bUSQNugEhs-:b-4lep4f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Review by jordanlewis — APPROVED** [review]
+1 on family over code.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-Lc9Xf-X3dM_tQOOjp-7:b4xvka9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/sql/distsqlrun/materializer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5agSS5jC0Zk8Fhg3o:-Lc9X8U240rX2LXz1Wcv:b-w59nw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/distsqlrun/materializer.go#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add a to-do item to add collated strings, uuids and inet values to this list.
</blockquote></details>

This codepath doesn't support those types yet, please don't worry about it.
___
*[pkg/sql/distsqlrun/materializer_test.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5aX2T8fhCk1pHwSeq:-Lc9XGk-26g-fUwjP_E7:birt0kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/distsqlrun/materializer_test.go#L93)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add a to-do item to add collated strings, uuids and inet values to this list.
</blockquote></details>

Not necessary, thanks though
___
*[pkg/sql/exec/types/conv/conv.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5arl1CVbv0I-C9XYS:-Lc9XN6X7Rl5WbNMttNr:b-hdk9hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/exec/types/conv/conv.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am making a note of this for myself, but also as a question: what becomes of this function throughout #36598? It seems to me we would prefer this not to exist.
(I hope to be able to discard this comment myself as I discover/learn the answer during the review -- however, if you know the answer @andy-kimball please advise preemptively.)
</blockquote></details>

Let this live for a while - there's a separate conversation brewing about what to do with the types (physical types) that the vectorized code uses. We can do a refactor of this stuff later.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @knz)

___
*[pkg/sql/opt_decompose_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5aEmDA2WTLOAurnot:-Lc9DkFa5We6rvIaXwV6:b-scrie5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ad8942882af47b5ab8c967a02193154b8ff835/pkg/sql/opt_decompose_test.go#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you file an issue / to-do item to add uuid and inet columns to this list. Thanks
</blockquote></details>

I just added them, since it was trivial.
___
*[pkg/sql/distsqlrun/materializer.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5agSS5jC0Zk8Fhg3o:-Lc9Ji7-8BwaL29qJA7w:bt6zkni) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/distsqlrun/materializer.go#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add a to-do item to add collated strings, uuids and inet values to this list.
</blockquote></details>

I added a TODO. I think an issue is too heavy-weight, since Jordan, et. al. know well they don't support these other types yet in columnar execution -- they're not going to forget without an issue to remind them (and we have an overwhelming backlog of issues as-is). Or if you feel it's important to have an issue, I won't stop you from filing. : )
___
*[pkg/sql/exec/types/conv/conv.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5arl1CVbv0I-C9XYS:-Lc9IWBA6xEr4ie-7aHv:b-w3hmke) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/exec/types/conv/conv.go#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am making a note of this for myself, but also as a question: what becomes of this function throughout #36598? It seems to me we would prefer this not to exist.
(I hope to be able to discard this comment myself as I discover/learn the answer during the review -- however, if you know the answer @andy-kimball please advise preemptively.)
</blockquote></details>

According to @jordanlewis, it still needs to be here, because they want to map multiple SQL types to the same exec type. So he wants to retain a separate enumeration. I think the package should be renamed to `exectypes`, since it's confusing that we have two `types` packages. But I didn't want to further complicate this PR with doing that.m
___
*[pkg/sql/sqlbase/structured_test.go, line 1329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5baNVC3pYtGY3zRrJ:-Lc9Kr5ZEeg3fhkmVPkN:b-578utm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/sqlbase/structured_test.go#L1329)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did you remove this function? Has it moved?
</blockquote></details>

I think just because the `datumTypeToColumnSemanticType` function had moved, and I knew that would go away anyway. I added back the test for now; i'll change a future PR to remove it.

**Review by knz — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 66 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-:-LcB1Cxi8a9FMueluRqg:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/exec/types/conv/conv.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36699#-Lc5arl1CVbv0I-C9XYS:-LcB1A6rE9l5hdsdbldz:b95m4hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8cbaf2b0c102641154135e7d80861f617236a3/pkg/sql/exec/types/conv/conv.go#L29)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

According to @jordanlewis, it still needs to be here, because they want to map multiple SQL types to the same exec type. So he wants to retain a separate enumeration. I think the package should be renamed to `exectypes`, since it's confusing that we have two `types` packages. But I didn't want to further complicate this PR with doing that.m
</blockquote></details>

Thanks for explaining.

**Pull request closed without merging**
