### PR TITLE
plpgsql: add support for unnamed cursors

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: add builtin to generate unique cursor names

This patch adds a builtin function `crdb_internal.plpgsql_gen_cursor_name`
that generates a unique name for a PLpgSQL cursor if the supplied name
is NULL. It then returns the resulting name to be used when opening
a cursor. This will be used in a following commit to implement unnamed
PLpgSQL cursors.

Informs #109709

Release note: None

#### plpgsql: add support for unnamed cursors

This patch adds support for opening an "unnamed" cursor in a PLpgSQL
routine. A PLpgSQL cursor is unnamed when the value for the cursor
variable is `NULL`. When an unnamed cursor is opened, a name will be
generated for it like `<unnamed portal 1>` that is guaranteed not to
conflict with an existing cursor or portal name. The PLpgSQL variable
that represents the cursor's name is updated to reflect the generated
name.

Informs #109709

Release note (sql change): Added support for unnamed PLpgSQL cursors,
which generate a unique name when no cursor name was specified.

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first two commits are #110709.

**Review by rharding6373 — COMMENTED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-:-NfSUAnZAYqiDRXp8Vme:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSQKmH0GPdwYhqUFvu):*
nit: s/An/A
___
*[`pkg/sql/sem/builtins/builtins.go` line 8450 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSPcR17NGMUggF4HnA:-NfSPcR17NGMUggF4HnB:b-rzjsk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c9a3b93590f4cc5bc7da7c67096312ad15cf01/pkg/sql/sem/builtins/builtins.go#L8450)):*
> ```Go
> 				return args[0], nil
> 			},
> 			Info:              "This function is used internally to implement the PLpgSQL RAISE statement.",
> ```

Copy paste error?
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_cursor` line 492 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSTZac4DlzvItgjRui:-NfSTZac4DlzvItgjRuj:b-tsls1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/694e86e918f615f12fa555e4e81caacbaf5376c4/pkg/sql/logictest/testdata/logic_test/plpgsql_cursor#L492)):*
> ```
> <unnamed portal 9>
> 
> # Do not generate a new name if one was supplied.
> ```

Need one more call to an unnamed cursor after this test to verify that the unnamed portal counter didn't increase. This will have the added benefit of testing that a call from a new function keeps incrementing the same counter.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_cursor` line 520 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSU2Lc-gm2KjZaSnhG:-NfSU2Lc-gm2KjZaSnhH:b-tfbu55) ([raw file](https://github.com/cockroachdb/cockroach/blob/694e86e918f615f12fa555e4e81caacbaf5376c4/pkg/sql/logictest/testdata/logic_test/plpgsql_cursor#L520)):*
> ```
> 
> statement ok
> ABORT;
> ```

Could you also add a test where we fetch from the unnamed cursor?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111329)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSQKmH0GPdwYhqUFvu):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: s/An/A
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 8450 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSPcR17NGMUggF4HnA:-NfScsZ44ttArI2sy5Ex:bmzvot9) ([raw file](https://github.com/cockroachdb/cockroach/blob/40c9a3b93590f4cc5bc7da7c67096312ad15cf01/pkg/sql/sem/builtins/builtins.go#L8450)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Copy paste error?
</blockquote></details>

Yes, thanks for catching that. Fixed it.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_cursor` line 492 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSTZac4DlzvItgjRui:-NfSdYlyBT0zpOyuCpG6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/694e86e918f615f12fa555e4e81caacbaf5376c4/pkg/sql/logictest/testdata/logic_test/plpgsql_cursor#L492)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Need one more call to an unnamed cursor after this test to verify that the unnamed portal counter didn't increase. This will have the added benefit of testing that a call from a new function keeps incrementing the same counter.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_cursor` line 520 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NfSU2Lc-gm2KjZaSnhG:-NfSed7u9KFndQf28h7F:bikgyi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/694e86e918f615f12fa555e4e81caacbaf5376c4/pkg/sql/logictest/testdata/logic_test/plpgsql_cursor#L520)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you also add a test where we fetch from the unnamed cursor?
</blockquote></details>

Great idea. I added fetches in a couple places.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 14 files at r3, 31 of 31 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-:-Nflp1ah6w59DU6OUfgG:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_builtins` line 69 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NflkxyG-QrOfiqXtNq5:-NflkxyHBy7v8tEv8WOE:bl52ldp) ([raw file](https://github.com/cockroachdb/cockroach/blob/93541b5332f9b990ebcf90497718807c875b7f19/pkg/sql/logictest/testdata/logic_test/plpgsql_builtins#L69)):*
> ```
> SELECT crdb_internal.plpgsql_gen_cursor_name(NULL);
> ----
> <unnamed portal 8>
> ```

nit: add a test after `user testuser newsession` (you might have to improve the parsing for `user` statements in logic.go so that `nodeIdx` is not required) to test that the name start back at 1.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Very nice! Sorry for the delay.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-:-Nflq6kA9iKhYG6QOfYF:b-alzaet)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-:-NfmJLXp5S1OXS384wF8:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/plpgsql_builtins` line 69 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111329#-NflkxyG-QrOfiqXtNq5:-NfmIqff10SiP9XnnpMt:b8howb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/93541b5332f9b990ebcf90497718807c875b7f19/pkg/sql/logictest/testdata/logic_test/plpgsql_builtins#L69)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add a test after `user testuser newsession` (you might have to improve the parsing for `user` statements in logic.go so that `nodeIdx` is not required) to test that the name start back at 1.
</blockquote></details>

It looks like `user testuser` starts a new session for that user. I added a test that switches between users.

**Pull request merged**
