### PR TITLE
kvserver: add leader leases to TestSnapshotAfterTruncationWithUncommittedTail

### PR DESCRIPTION
**Pull request by miraradeva**
The test partitions a leader from the rest of the followers and expects the lease and leadership to move to one of the followers. The test does so by installing unreliable Raft listeners. For leader leases, this is not enough because the leader is still supporter by the followers in store liveness.

This commit extends the partition to also apply to store liveness.

Part of: #133763

Release note: None

### CODE REVIEW

**Comment by miraradeva** [comment]
This also needs the Raft commit from [#135707](https://github.com/cockroachdb/cockroach/pull/135707) to make sure transfers work.

**Review by arulajmani — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135722)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135722#-OC4eYUXAytRQUUtHLTP:-OC4eYUXAytRQUUtHLTQ:bggjzm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/855a0b876d709e7ce7869e506c22fc9b444679a2/pkg/kv/kvserver/client_raft_test.go#L885)):*
> ```Go
> 	store := tc.GetFirstStoreFromServer(t, 0)
> 
> 	key := tc.ScratchRangeWithExpirationLease(t)
> ```

Is this test actually using leader leases given the scratch range we're constructing uses expiration based leases?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135722)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 885 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135722#-OC4eYUXAytRQUUtHLTP:-OC4gILJ395Odvl0n0UC:bo3nwvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/855a0b876d709e7ce7869e506c22fc9b444679a2/pkg/kv/kvserver/client_raft_test.go#L885)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is this test actually using leader leases given the scratch range we're constructing uses expiration based leases?
</blockquote></details>

Hmm, that's a very good point. I added assertions throughout the test, and it is indeed an expiration lease after each of the steps. So, no leader leases but fortification and store liveness are on.

Without the store liveness partition, the test fails [here](https://github.com/cockroachdb/cockroach/blob/855a0b876d709e7ce7869e506c22fc9b444679a2/pkg/kv/kvserver/client_raft_test.go#L1004), at the transfer step. The Raft layer doesn't know anything about the preferred lease type, so it acts as if it's running with leader leases; i.e. the partitioned leader is not stepping down because it still has store liveness support.

**Comment by arulajmani** [comment]
Reviewable seems broken for me on this PR for some reason, so I'll reply in-line here:

> Hmm, that's a very good point. I added assertions throughout the test, and it is indeed an expiration lease after each of the steps. So, no leader leases but fortification and store liveness are on.

> Without the store liveness partition, the test fails [here](https://github.com/cockroachdb/cockroach/blob/855a0b876d709e7ce7869e506c22fc9b444679a2/pkg/kv/kvserver/client_raft_test.go#L1004), at the transfer step. The Raft layer doesn't know anything about the preferred lease type, so it acts as if it's running with leader leases; i.e. the partitioned leader is not stepping down because it still has store liveness support.

I wonder if it makes sense to just change this test to always use leader leases in that case. If I had to guess, we're using expiration based leases here because we don't want to deal with the placement of the `NodeLiveness` range. I don't think that concern exists with leader leases, so I wonder if we could change this test to always use leader leases and use a regular scratch range instead. Wdyt?

**Comment by miraradeva** [comment]
> I wonder if it makes sense to just change this test to always use leader leases in that case. If I had to guess, we're using expiration based leases here because we don't want to deal with the placement of the NodeLiveness range. I don't think that concern exists with leader leases, so I wonder if we could change this test to always use leader leases and use a regular scratch range instead. Wdyt?

I like that idea. We can actually still have it run with expiration leases (metamorphically), but exclude epoch leases.

One thing to note about this test is that I had to remove the manual clock manipulation because it resulted in store liveness support being withdrawn throughout the cluster, which in turn disrupts Raft. As a result, the test is slower now (25s) as opposed to <10s before. I guess I could override the lease interval, but not sure how we usually deal with this and leader leases.

**Comment by miraradeva** [comment]
Closing in lieu of https://github.com/cockroachdb/cockroach/pull/136174.

**Pull request closed without merging**
