### PR TITLE
workload: add zones to tpcc

### PR DESCRIPTION
**Pull request by m-schneider**
This patch will allow us to explicitly specify the zones we're using for
partition constraints in tpcc. Then when we write automated testing, we
can pass the same zones to roachprod and tpcc to make geo partitioning
more explicit.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/workload/tpcc/partition.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-LDIybsOA2MhXvoAr0PJ:-LDIybsOA2MhXvoAr0PK:b-4m3xrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/31523415f4f19834dcd591ff9bd485f76a16f4be/pkg/workload/tpcc/partition.go#L28)):*
> ```Go
> )
> 
> func configureZone(db *gosql.DB, table, partition string, constraint int, zones []string) {
> ```

Leave a comment on this function. Mention that zones is optional and discuss what happens when it's included and when it's not.

---

*[pkg/workload/tpcc/partition.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-LDIyF0gAlIHVa-X0_jT:-LDIyF0gAlIHVa-X0_jU:b3bwxx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/31523415f4f19834dcd591ff9bd485f76a16f4be/pkg/workload/tpcc/partition.go#L31)):*
> ```Go
> 	if len(zones) > 0 {
> 		sql := fmt.Sprintf(
> 			`ALTER PARTITION %s OF TABLE %s EXPERIMENTAL CONFIGURE ZONE 'constraints: [+zone=%s]'`,
> ```

I'd pull the strings `[+zone=%s]` vs `[+rack=%d]` into a variable so that the rest of this can be shared. For instance:

```
var constraints string
if len(zones) > 0 {
    constriaints = fmt.Sprintf("[+zone=%s]", zones[constraint])
} else {
    constriaints = fmt.Sprintf("[+rack=%d]", constraint)
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26049)*

**Comment by m-schneider** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/workload/tpcc/partition.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-LDIybsOA2MhXvoAr0PJ:-LDha8TX3k4Wo6uHfgFJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31523415f4f19834dcd591ff9bd485f76a16f4be/pkg/workload/tpcc/partition.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a comment on this function. Mention that zones is optional and discuss what happens when it's included and when it's not.
</blockquote></details>

Done.

---

*[pkg/workload/tpcc/partition.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-LDIyF0gAlIHVa-X0_jT:-LDhZxw0C3mPdQSRfmNO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31523415f4f19834dcd591ff9bd485f76a16f4be/pkg/workload/tpcc/partition.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd pull the strings `[+zone=%s]` vs `[+rack=%d]` into a variable so that the rest of this can be shared. For instance:

```
var constraints string
if len(zones) > 0 {
    constriaints = fmt.Sprintf("[+zone=%s]", zones[constraint])
} else {
    constriaints = fmt.Sprintf("[+rack=%d]", constraint)
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26049)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-:-LDheDlwAOwVZeHvd4-m:bnfp4nl)*

**Comment by m-schneider** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-:-LDm9RuN6q3ZdvmVPifo:b-ydi9ay)*

**Comment by m-schneider** [comment]
bors r+

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26049#-:-LDqilMm6U7vkWfMgfxD:b-ydi9ay)*

**Pull request merged**
