### PR TITLE
sql: cleanups + new "project set" relop + ROWS FROM + local exec logic

### LINKED ISSUE #20511: sql: address discrepancy with pg and SRFs
Postgres:
```
justin=# select generate_series(1,2), generate_series(1,2);
 generate_series | generate_series
-----------------+-----------------
               1 |               1
               2 |               2
(2 rows)
```

Us:
```
root@:26257/> select generate_series(1,2), generate_series(1,2);
+-----------------+-----------------+
| generate_series | generate_series |
+-----------------+-----------------+
|               1 |               1 |
|               1 |               2 |
|               2 |               1 |
|               2 |               2 |
+-----------------+-----------------+
(4 rows)
```

See https://stackoverflow.com/questions/39863505/what-is-the-expected-behaviour-for-multiple-set-returning-functions-in-select-cl/39864815#39864815

cc @knz @benesch

### PR DESCRIPTION
**Pull request by knz**
This PR provides support for pg's "Project Set" logical plan operator, which underlies both the handling of set-generating functions (SRFs) and the `ROWS FROM` input SQL syntax.

Formally, this operator takes a relational operator R and a list of SRF applications L. Its semantics is a relation which performs a lateral cross join between R and (conceptually) `ROWS FROM (L)`, the functional zip of the value generators in L.

Reminder: the functional zip over iterators a,b,c returns tuples of values from a,b,c picked "simultaneously". NULLs are used when an iterator is "shorter" than another. For example `zip([1,2,3], ['a','b'])` is `[(1,'a'), (2,'b'), (3, null)]`.

The PR also greatly simplifies / clean up the typing logic around SRFs by getting rid of `TTable` and `DTable` entirely.

It also cleans up the docs of SRF built-in functions so that their return type is displayed in simple form (e.g. the documented return type of generate_series is now `int` and not `setof tuple{int as ...}`)

This PR serves several purposes simultaneously.

1. to solve #20511.
2. to provide more compatibility with pg's wrt the `ROWS FROM` syntax.
3. to serve as baseline for testing the new "ApplySRF" (really, "project set") functionality in distsql (SQL Execution team)
4. to serve as common intermediate language for the optimizer code, and as baseline for future
    optimizer code that will look into SRF transformations (SQL Optimizer team). /cc @andy-kimball 

Fixes #20511.

### CODE REVIEW

**Comment by knz** [comment]
@RaduBerinde feel free to check that I haven't screwed up the planning logic

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/data_source.go, line 414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpXNgDEuzSvGumZUH:-LDlpXNgDEuzSvGumZUI:b-mgwa0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/data_source.go#L414)):*
> ```Go
> }
> 
> func (p *planner) getRowsFromPlan(
> ```

[nit] "get rows from plan" reads like something else, maybe add a little comment mentioning `ROWS FROM`, or rename to `getPlanForRowsFrom`

---

*[pkg/sql/function_scan.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloVdKEa5VNhpXmIte:-LDloVdKEa5VNhpXmItf:b-6ydi2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L25)):*
> ```Go
> 
> // funcScanNode zips through one or more SRFs.
> type funcScanNode struct {
> ```

Why not call this `zipNode`? There's nothing specific about functions in what the node does.

---

*[pkg/sql/function_scan.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloc5-B6esWcxqdFsz:-LDloc5-B6esWcxqdFt-:bfwo3wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L29)):*
> ```Go
> 	columns sqlbase.ResultColumns
> 
> 	run applySRFRun
> ```

This type should match the node name

---

*[pkg/sql/function_scan.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlp4M4-h3OwS6XHLqZ:-LDlp4M4-h3OwS6XHLq_:b-9eytxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L72)):*
> ```Go
> }
> 
> func (n *funcScanNode) Next(params runParams) (bool, error) {
> ```

Very nice logic.

---

*[pkg/sql/function_scan.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpyheBGjfRMUIS8Dj:-LDlpyheBGjfRMUIS8Dk:b-g82otq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L84)):*
> ```Go
> 				return false, err
> 			}
> 			n.run.done[i] = !hasVals
> ```

[nit] move this inside the `else` below

---

*[pkg/sql/function_scan.go, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlqARhC4P7OTKPDPxu:-LDlqARhC4P7OTKPDPxv:b-q8nwke) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L100)):*
> ```Go
> 
> 		// Advance to the next column group.
> 		colIdx += numCols
> ```

[nit] could slice the row instead of using colIdx in a bunch of places (`row = row[numCols:]`)

---

*[pkg/sql/logictest/testdata/planner_test/rows_from, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpDWD8V3xLefvUqLu:-LDlpDWD8V3xLefvUqLv:brtka76) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/logictest/testdata/planner_test/rows_from#L6)):*
> ```
> 
> query TTTTT
> EXPLAIN(VERBOSE) SELECT * FROM ROWS FROM(information_schema._pg_expandarray(array[5,6,7]), generate_series(1,4))
> ```

[nit] logictests usually have a space after EXPLAIN. I'm only mentioning it because I've found myself grepping for `EXPLAIN (VERBOSE)` a bunch of times.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-:-LDlpQm86xOCbfTlFFR2:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 22 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 414 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpXNgDEuzSvGumZUH:-LDm02tw85Q-BwAf8RIP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/data_source.go#L414)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] "get rows from plan" reads like something else, maybe add a little comment mentioning `ROWS FROM`, or rename to `getPlanForRowsFrom`
</blockquote></details>

Done.

---

*[pkg/sql/function_scan.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloVdKEa5VNhpXmIte:-LDm03sT1EcMbwJ_P72U:bsq8rby) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why not call this `zipNode`? There's nothing specific about functions in what the node does.
</blockquote></details>

It's the same name as used in postgres. Until we've iterated around #26234 which also uses a zip operator and demonstrate that both SQL-level features can use the same relational operator, I'd prefer to separate the two logical operators by name like pg does.

---

*[pkg/sql/function_scan.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloc5-B6esWcxqdFsz:-LDm0QqZ4ztv3aD4yHAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This type should match the node name
</blockquote></details>

Done.

---

*[pkg/sql/function_scan.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpyheBGjfRMUIS8Dj:-LDm0aFsEudRYtNs4vNV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L84)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] move this inside the `else` below
</blockquote></details>

Done.

---

*[pkg/sql/function_scan.go, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlqARhC4P7OTKPDPxu:-LDm0dDxCbmVEgKUXeku:b-b5248e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L100)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could slice the row instead of using colIdx in a bunch of places (`row = row[numCols:]`)
</blockquote></details>

I think this way is clearer for the reader.

---

*[pkg/sql/logictest/testdata/planner_test/rows_from, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDlpDWD8V3xLefvUqLu:-LDm0fHAC6Z2miCu788x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/logictest/testdata/planner_test/rows_from#L6)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] logictests usually have a space after EXPLAIN. I'm only mentioning it because I've found myself grepping for `EXPLAIN (VERBOSE)` a bunch of times.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/function_scan.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloVdKEa5VNhpXmIte:-LDm4fpc6f0WSQA6zdW8:b-i63y3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L25)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It's the same name as used in postgres. Until we've iterated around #26234 which also uses a zip operator and demonstrate that both SQL-level features can use the same relational operator, I'd prefer to separate the two logical operators by name like pg does.
</blockquote></details>

Your call, but I don't find whether we can use it for another purpose relevant. The nodes are mostly named around what they do not what they are used for (e.g. filterNode, renderNode). This one just zips a bunch of inner plans, whatever those plans may be.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223)*

**Comment by BramGruneir** [comment]
:lgtm: (I didn't go through the planning and opts stuff, as that is Radu's domain.)

---

Review status: 17 of 22 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/plan_columns.go, line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmUSky7vSnzXbAEmOd:-LDmUSkzBIdc9Xq57po6:b-8j20fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/plan_columns.go#L78)):*
> ```Go
> 	case *windowNode:
> 		return n.run.values.columns
> 	case *showTraceNode:
> ```

Is there a reason all the return n.columns isn't just a comma separated list?

---

*[pkg/sql/logictest/testdata/logic_test/rows_from, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmUp4c5AydVGjTXj-l:-LDmUp4c5AydVGjTXj-m:bpig3fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/logictest/testdata/logic_test/rows_from#L4)):*
> ```
> 
> query II colnames
> SELECT * FROM ROWS FROM (generate_series(1,2), generate_series(4,8))
> ```

Can you also check the opposite, where the nulls happen to the second SRF?

---

*[pkg/sql/logictest/testdata/logic_test/rows_from, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmVRSN2XQtT4QhirIO:-LDmVRSN2XQtT4QhirIP:bqhyjqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/logictest/testdata/logic_test/rows_from#L16)):*
> ```
> SELECT * FROM ROWS FROM (generate_series(1,0), generate_series(1,0))
> ----
> generate_series  generate_series
> ```

Add a case where one is (1,0), one is (1,1) one is (1,2).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-:-LDmW3tP3L2e57rZRSKF:bcnm9ji)*

**Comment by knz** [comment]
Review status: 0 of 39 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/plan_columns.go, line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmUSky7vSnzXbAEmOd:-LDsPfRUAf73fxhxs1q7:bsqr1g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/plan_columns.go#L78)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is there a reason all the return n.columns isn't just a comma separated list?
</blockquote></details>

yes, unfortunately all the different node types have a different layout in memory, so the Go compiler cannot generate a single code path for all of them.

---

*[pkg/sql/logictest/testdata/logic_test/rows_from, line 4 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmUp4c5AydVGjTXj-l:-LDsPlds87vY0PVyghZy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/logictest/testdata/logic_test/rows_from#L4)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you also check the opposite, where the nulls happen to the second SRF?
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/rows_from, line 16 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDmVRSN2XQtT4QhirIO:-LDsPzpN8I2YIbxkzrxZ:b7gfvbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2474da1984341103ac329f06df70f75a93ca80/pkg/sql/logictest/testdata/logic_test/rows_from#L16)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Add a case where one is (1,0), one is (1,1) one is (1,2).
</blockquote></details>

Can you explain further? Any generator that produces no value will constrain the entire result to be an empty table, regardless of the other expressions.

---

*[pkg/sql/function_scan.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDloVdKEa5VNhpXmIte:-LDsQAUG0Vp5TUu_pUl0:b-yvq3p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e153bab59c4d7c3c3276d626d9ee0f20a0486f21/pkg/sql/function_scan.go#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Your call, but I don't find whether we can use it for another purpose relevant. The nodes are mostly named around what they do not what they are used for (e.g. filterNode, renderNode). This one just zips a bunch of inner plans, whatever those plans may be.
</blockquote></details>

I evolved the code with Andy's advice to actually implement the whole she-bang of zipping again and again for every row of an input plan. So this is not a zip any more, it's more "for each row, zip" which is what we tried to call "applySRF" but is called "set projection" in pg. Renamed accordingly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223)*

**Comment by RaduBerinde** [comment]
Very cool!

---

Review status: 0 of 39 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/plan_physical_props.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsgcsL5m3l5ctgvCcF:-LDsgcsL5m3l5ctgvCcG:b17o2cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/plan_physical_props.go#L49)):*
> ```Go
> 		// TODO(knz): the result is ordered by any of the underlying
> 		// SRF orders, not just the source first.
> 		return planPhysicalProps(n.source)
> ```

[nit] mention that we can pass through properties because we preserve all input columns, and they come first.

---

*[pkg/sql/project_set.go, line 27 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDseynX18no1IcF-TnB:-LDseynX18no1IcF-TnC:b-jfu5ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L27)):*
> ```Go
> )
> 
> // projectSetNode zips through a list of generators for every row of
> ```

[nit] Comment could be a bit more verbose so someone who doesn't have experience with "zip" or SRFs can understand (perhaps an example). It would be good to mention the output "schema" as well

---

*[pkg/sql/project_set.go, line 64 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDshHI4B4ZZotZB0DUh:-LDshHI4B4ZZotZB0DUi:b-kxpfx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L64)):*
> ```Go
> 	// input. They appear first in the input so that any indexed vars
> 	// that refered to the original source stay valid.
> 	copy(n.columns, srcCols)
> ```

Isn't this a no-op? `n.columns` is empty at this point. Is it possible with the stuff we currently support to have a logictest and/or plannertest with a case where the input has columns?

---

*[pkg/sql/project_set.go, line 138 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsfTJN8EOEdx4CWFrn:-LDsfTJN8EOEdx4CWFro:bsymu4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L138)):*
> ```Go
> 	numColsInSource int
> 
> 	// exprs are the constant-folded, type checked expressions specified
> ```

`exprs`, `funcs`, `gens` should be in `projectSetNode` (maybe `numColsInSource` too)

---

*[pkg/sql/project_set.go, line 187 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDslzzH3lu8jXleoEpy:-LDslzzH3lu8jXleoEpz:b-qe5gms) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3fdb274e011f9035eda129f1bcaf8b98825a7a/pkg/sql/project_set.go#L187)):*
> ```Go
> 				if fn == nil {
> 					// This is a regular scalar expression. Evaluate it just once, store
> 					// the result in rowBuffer. The result will be produced multiple times.
> ```

It seems that we produce the result only once, not multiple times. It might be cleaner to run Eval inside the `A simple scalar result.` block below

---

*[pkg/sql/project_set.go, line 246 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsmJ_X4UzFEEB-_9D2:-LDsmJ_X4UzFEEB-_9D3:bsy2g06) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3fdb274e011f9035eda129f1bcaf8b98825a7a/pkg/sql/project_set.go#L246)):*
> ```Go
> 				// Do we still need to produce the scalar value? (first row)
> 				if !n.run.done[i] {
> 					// Yes. Produce it once, then indicate it's "done".
> ```

mention that n.run.rowBuffer[colIdx] was set above

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-:-LDskM8c8-jwVx3u1FKw:b-jdo7t9)*

**Comment by knz** [comment]
Review status: 0 of 45 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/sql/plan_physical_props.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsgcsL5m3l5ctgvCcF:-LEK9TH_1Wmh1dpkHwXG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/plan_physical_props.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] mention that we can pass through properties because we preserve all input columns, and they come first.
</blockquote></details>

Done.

---

*[pkg/sql/project_set.go, line 27 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDseynX18no1IcF-TnB:-LEKAD4U8SwrNg-1PfPs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Comment could be a bit more verbose so someone who doesn't have experience with "zip" or SRFs can understand (perhaps an example). It would be good to mention the output "schema" as well
</blockquote></details>

Done.

---

*[pkg/sql/project_set.go, line 64 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDshHI4B4ZZotZB0DUh:-LEKAESD2J84cWVgYbNr:bvws7re) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Isn't this a no-op? `n.columns` is empty at this point. Is it possible with the stuff we currently support to have a logictest and/or plannertest with a case where the input has columns?
</blockquote></details>

Yes this becomes populated when we transform the SRFs properly.

---

*[pkg/sql/project_set.go, line 138 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsfTJN8EOEdx4CWFrn:-LEKAPqC5TWL6ErGvQV9:bi04znk) ([raw file](https://github.com/cockroachdb/cockroach/blob/83c80a4b259e818ab6b178dc8c4d3569abfe226e/pkg/sql/project_set.go#L138)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`exprs`, `funcs`, `gens` should be in `projectSetNode` (maybe `numColsInSource` too)
</blockquote></details>

Not `gens` but the others you're right, they are used in planning.
Done.

---

*[pkg/sql/project_set.go, line 187 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDslzzH3lu8jXleoEpy:-LEKBVyk7ZdMExD4HZyn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3fdb274e011f9035eda129f1bcaf8b98825a7a/pkg/sql/project_set.go#L187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It seems that we produce the result only once, not multiple times. It might be cleaner to run Eval inside the `A simple scalar result.` block below
</blockquote></details>

Done.

---

*[pkg/sql/project_set.go, line 246 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-LDsmJ_X4UzFEEB-_9D2:-LEKBVlTECp2v1IarwFn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e3fdb274e011f9035eda129f1bcaf8b98825a7a/pkg/sql/project_set.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

mention that n.run.rowBuffer[colIdx] was set above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223)*

**Comment by solongordon** [comment]
:lgtm: Good stuff!

---

Review status: 0 of 50 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26223#-:-LELXXphCMrVAqZ9EROv:b-m6xbb3)*

**Comment by knz** [comment]
thanks for all the reviews!

bors r+

**Pull request merged**
