### PR TITLE
sql: properly support CTEs inside views

### LINKED ISSUE #23833: sql: view creation improperly initializes the CTE context
This works:

```
> with a as (select 1 as x) select x from a;
+---+
| x |
+---+
| 1 |
+---+
(1 row)
```

This doesn't:

```
> create view w as with a as (select 1 as x) select x from a;
pq: relation "a" does not exist
```

cc @jordanlewis

### PR DESCRIPTION
**Pull request by knz**
Fixes #23833.

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31007)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/dependencies, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31007#-LO5Ci3-9iHSyCHrX_gZ:-LO5Ci3-9iHSyCHrX_g_:b-ady88q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e99d5b4294006645784d9e207af961bc5e83453/pkg/sql/logictest/testdata/logic_test/dependencies#L140)):*
> ```
> ----
> descriptor_id  descriptor_name    index_id  dependedonby_id  dependedonby_type  dependedonby_index_id  dependedonby_name  dependedonby_details
> 63             blog_posts_id_seq  NULL      64               sequence           0                      NULL               Columns: [0]
> ```

I don't understand these test changes. Why are the descriptor ids changing?
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31007#-LO5CkUn037ShfShgS8s:-LO5CkUn037ShfShgS8t:b-rslvhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e99d5b4294006645784d9e207af961bc5e83453/pkg/sql/logictest/testdata/logic_test/pg_catalog#L284)):*
> ```
> 4084598993  primary       393119649     0        NULL      NULL   0            0
> 4084598994  t3_a_b_idx    393119649     0        NULL      NULL   0            0
> 4252432642  v1            393119649     0        NULL      NULL   0            0
> ```

likewise, what caused these changes?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31007)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/dependencies, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31007#-LO5Ci3-9iHSyCHrX_gZ:-LOCaOdI1YK6ElFGaSmr:b-ko0ehe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e99d5b4294006645784d9e207af961bc5e83453/pkg/sql/logictest/testdata/logic_test/dependencies#L140)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't understand these test changes. Why are the descriptor ids changing?
</blockquote></details>

The previous code was performing name resolution of the table names on the AST during the semantic analysis, thereby acquiring a lease. This caused the subsequent transaction that was creating the view and update the leased table desc to abort with a retry error. However since the ID generation is not transactional, we'd "lose" a desc ID this way.

The new code skips this name resolution with lease (the name resolution is performed using uncached/unleased table descs instead) and so the retry error does not occur, so the first generated ID can be used.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 284 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31007#-LO5CkUn037ShfShgS8s:-LOCbvzb3JhgHUKJjTw5:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e99d5b4294006645784d9e207af961bc5e83453/pkg/sql/logictest/testdata/logic_test/pg_catalog#L284)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

likewise, what caused these changes?
</blockquote></details>

ditto

**Comment by knz** [comment]
rebased, RFAL

**Comment by knz** [comment]
ping?

**Comment by knz** [comment]
(just a rubber stamp since the same commits were approved in #31051)

**Review by jordanlewis — APPROVED** [review]
Oops, I didn't realize that I hadn't reviewed this before letting the backport go in... this all looks good to me but I wonder if @vivekmenezes should take a look with regards to the simpler lease stuff, which I don't quite understand.

**Comment by knz** [comment]
I think it's fair that Vivek and I look into this together again, because in truth I do not understand all of it myself.

However since this commit went into 2.1 already I will merge the PR as-is. If there are additional fixes needed I'll make a new PR.

Thanks

bors r+

**Comment by jordanlewis** [comment]
Sounds good

**Pull request merged**
