### PR TITLE
sql: make the table reference syntax carry its alias, if any

### PR DESCRIPTION
**Pull request by knz**
This patch extends the numeric table reference syntax (e.g. `[123]`)
with the ability to give the source and its columns an alias.

The following new syntax forms are allowed:

- `[123(1,2,3) as t]` the same as `[123(1,2,3)] as t`.
- `[123 as t(x,y,z)]` the same as `[123] as t(x,y,z)`.
- `[123(1,2,3) as t(x,y,z)]` the same as `[123(1,2,3]) as t(x,y,z)`.

Meanwhile things like `[123 as t] as u` are still possible.

Reminder: the previously supported syntax `[123(1,2,3)]`is  a data 
source providing only columns 1,2,3 from table 123. Its column names
are those listed in the table descriptor.

The new syntax forms are introduced in preparation of a subsequent
patch to enhance the handling of view descriptors.

Also,the new syntax captures the alias definition (AS clause) inside
the square brackets, as we plan to replace table names by this square
bracket syntax, and the replacement must syntactically fit in a way
that does not cause grammar error. In a table expression of the form
`foo as t`, a naive replacement using `[123] as foo as t` would be
syntactically invalid, whereas `[123 as foo] as t` is valid.

I am extracting this functionality from the more complex #15388, because I would like to rebase #16884 on top of it.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Can you include some motivation in the commit message? Why is this better? `[123] AS t` seems closer to the regular syntax.

Are there any upgrade concerns for existing views?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17031#-:-Kp2WMyt4plyukhx1GT9:byfa4x2)*

**Comment by knz** [comment]
I am sorry the commit message was so terse. I have extended it. There is no concern for existing descriptors / queries, the syntax is backward compatible.

**Comment by RaduBerinde** [comment]
Thanks, LGTM!

**Comment by knz** [comment]
TFYR!

**Pull request merged**
