### PR TITLE
raftentry: fix accidental no-op in truncateFrom

### LINKED ISSUE #61990: roachtest: hotspotsplits/nodes=4 failed [inconsistency]
[(roachtest).hotspotsplits/nodes=4 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2776621&tab=buildLog) on [master@e09b93fe62541c3a94f32a723778660b528a0792](https://github.com/cockroachdb/cockroach/commits/e09b93fe62541c3a94f32a723778660b528a0792):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hotspotsplits/nodes=4/run_1
	cluster.go:1754,test_runner.go:862: r38 (/Table/53/1/-182447479829764077) is inconsistent: RANGE_INCONSISTENT 
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).CheckReplicaDivergenceOnDB
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1705
		  | main.(*cluster).FailOnReplicaDivergence.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1751
		  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:140
		  | main.(*cluster).FailOnReplicaDivergence
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1748
		  | main.(*testRunner).runTest
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:862
		  | main.(*testRunner).runWorker
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:472
		  | main.(*testRunner).Run.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:275
		  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) r38 (/Table/53/1/-182447479829764077) is inconsistent: RANGE_INCONSISTENT 
		  | (n3,s3):3: checksum 099280635e0ad488ea26cb5f253acebde95ceaa12eb3a8088e41ce92866507e5a664046b208ad370517d6af5c839c135dd1c27e612bbb0d59f75357a06084b61 [minority]
		  | - stats: contains_estimates:0 last_update_nanos:1615788916721166939 intent_age:0 gc_bytes_age:0 live_bytes:301241874 live_count:1149 key_bytes:28077 key_count:1149 val_bytes:301213797 val_count:1149 intent_bytes:0 intent_count:0 separated_intent_count:0 sys_bytes:702 sys_count:6 abort_span_bytes:0 
		  | - stats.Sub(recomputation): last_update_nanos:1615788916721166939 live_bytes:301241874 live_count:1149 key_bytes:28077 key_count:1149 val_bytes:301213797 val_count:1149 sys_bytes:702 sys_count:6 
		  | (n2,s2):2: checksum ff3cbc427622cc2ebf8ae40b42f37870f5662226a33bd636662a3423b268d19c15ae26c4f10181e9a80e531d00bb5127cbbcd44c21088fe8e5745d10653687fa
		  | - stats: contains_estimates:0 last_update_nanos:1615788916721166939 intent_age:0 gc_bytes_age:0 live_bytes:300979696 live_count:1148 key_bytes:28052 key_count:1148 val_bytes:300951644 val_count:1148 intent_bytes:0 intent_count:0 separated_intent_count:0 sys_bytes:702 sys_count:6 abort_span_bytes:0 
		  | - stats.Sub(recomputation): last_update_nanos:1615788916721166939 live_bytes:300979696 live_count:1148 key_bytes:28052 key_count:1148 val_bytes:300951644 val_count:1148 sys_bytes:702 sys_count:6 
		  | (n1,s1):1: checksum ff3cbc427622cc2ebf8ae40b42f37870f5662226a33bd636662a3423b268d19c15ae26c4f10181e9a80e531d00bb5127cbbcd44c21088fe8e5745d10653687fa
		  | - stats: contains_estimates:0 last_update_nanos:1615788916721166939 intent_age:0 gc_bytes_age:0 live_bytes:300979696 live_count:1148 key_bytes:28052 key_count:1148 val_bytes:300951644 val_count:1148 intent_bytes:0 intent_count:0 separated_intent_count:0 sys_bytes:702 sys_count:6 abort_span_bytes:0 
		  | - stats.Sub(recomputation): last_update_nanos:1615788916721166939 live_bytes:300979696 live_count:1148 key_bytes:28052 key_count:1148 val_bytes:300951644 val_count:1148 sys_bytes:702 sys_count:6
		Error types: (1) *withstack.withStack (2) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/hotspotsplits/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=2776621&tab=artifacts#/hotspotsplits/nodes=4)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahotspotsplits%2Fnodes%3D4.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by tbg**
When entries are appended to the raft log, they are also added to the
raft entry cache. Appending indexes, say, `100, 101, 102` to the raft
log has the (absolutely crucial for correctness) effect of removing any
higher indexes in the raft log ( `103` and up) and for correctness, the
raft entry cache must follow the same semantics, so that it is always
a coherent subset of the raft log.

It turns out it didn't do that in one edge case, namely when appending
a slice of entries that didn't fit into the cache, but whose first
entry preceded the currently cached entries. For a concrete example,
imagine the cache contains

    [101, 102, 103, 104]

and we are attempting to add a slice of large entries at indexes `[50,
51, 52]` which can not fit the cache at all (i.e. their aggregate size
exceeds that of the cache).

What *should* be the result of this addition is an empty cache. This
is because the true raft log now ends at index 52. In reality though,
the cache accidentally turned this operation into a no-op, as it was
using an iterator that would be invalid when positioned to an index
not currently cached (in this example, index `50`, whereas the first
cached index would be `101`).

It took us a while to identify this bug, as it manifested itself to us
only through a very rare replica inconsistency failure (#61990) of the
`hotspotsplits/nodes=4` roachtest (which was only caught thanks to
 #36241) that would then take days to reproduce. When we finally
managed to get a reproduction that contain the entire history of disk
writes for the cluster, we found that the inconsistency had occured
due to entries from a past term being replicated to the divergent
follower. Concretely, where the leader had something like

| idx  | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 |
|------|-----|-----|-----|-----|-----|-----|-----|-----|
| term | 9   | 9   | 9   | 9   | 9   | 9   | 9   | 9   |

the divergent follower would have this:

| idx  | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 |
|------|-----|-----|-----|-----|-----|-----|-----|-----|
| term | 9   | 9   | *7* | *7* | *7* | 9   | 9   | 9   |

This made it likely that the issue was connected to a raft leadership
change in which the "old" leader for term 7 had proposed entries for
indexes up to and including at least index 105, which the term 8 and
9 leaders had then discarded and replaced by entries for term 9. Of
course, these entries should consequently never have been committed
and in particular, the term can never regress in the raft log, even
for uncommitted entries, at least when Raft is working correctly.

From the WAL writes, we were able to ascertain that the leader (who
itself had the correct writes in the log) had in fact replicated the
incorrect (term 7) entries to the follower. This meant that that we
were either looking at pebble flat-out serving stale reads (highly
unlikely) or a bug in the raft entry cache. Being unable to find
issues through direct inspection, we added invariants and tweaked the
test to exacerbate what we considered the triggering conditions
(relatively frequent term changes).

A crucial assertion that allowed identifying this bug was adding
invariant checks (which will be re-added in a future commit) that
verified that the truncation had indeed removed subsequent entries.
This highlighted that we were hitting this bug in at least ~5% of
hotspotsplits runs, but possibly more frequently (the assertion did not
catch all instances of the bug). `hotspotsplits` brings the crucial
ingredients here: it's doing concentrated 256KiB inserts which puts the
raft group into mild overload; many entries pile up and get processed in
aggregate, which leads to constantly taking the path in which
truncations are erroneously ignored. However, most of the time omitting
the eviction does not yield replica inconsistency. For this to happen,
the erroneously cached entries need to be picked up by raft for sending
to a follower; they need to be the "incorrect" (which necessitates a
discarded log and term change at the right moment), and finally they
must be in log positions at which the correct entries actually had an
effect (which is to be fair mostly the case).

The history of this bug is actually interesting. The code that has
the bug was introduced in #36360. However, that PR fixed a much more
egregious version of this bug - prior to that PR, the raft entry
cache simply didn't evict entries at higher positions at all, i.e.
it exhibited the bug in many more scenarios, and this consequently
lead to more frequent inconsistencies (as referenced in the issue).
So we went from bad, moderately rare bug to bad, very very rare bug
and, in this PR, hopefully, to no bug.

A rough calculation suggests that we spent around 800.000 minutes of
`n2-standard-4` instances minutes on reproductions related to this bug
in this instance alone, which I think boils down to around $39.000. I
like to think we got off cheap here.

Closes #61990.

Release note (bug fix): A rare issue that could cause replica divergence
was fixed. These issues would be reported by the replica consistency
checker, typically within 24 hours of occurrence, which would cause
nodes to terminate.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Excellent work!

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MXlVGw-B56xenovH3uQ:b-3dqv3z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/raftentry/cache.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlUTMWAe0s3AtuOY4g:-MXlUTMWAe0s3AtuOY4h:b-vandoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/cache.go#L381)):*
> ```Go
> 		}
> 		if i != 0 && e.Term < prevTerm {
> 			err := errors.Errorf("term regression idx %d: %d -> %d", prevIndex, e.Term, prevTerm)
> ```

I think `e.Term` and `prevTerm` should be swapped here.

**Review by petermattis — COMMENTED** [review]
Excellent sleuthing. Some drive-by comments because I was curious about this. I'm not at all familiar with this code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MXlz79A1UlgjO0F89S-:b-yq1p7p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlye3g9t_tu_-35gcg:-MXlye3g9t_tu_-35gch:b-fw82vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/ring_buffer.go#L75)):*
> ```Go
> 			// (say the buf is idx=[100, 101, 102] and `lo` is 99),
> 			// we need to truncate everything.
> 			it, ok = iterateFrom(b, first(b).index(b))
> ```

`first(b)` is an iterator, which you're retrieving the index of to create another iterator that is at the index of `first(b)`. I think `it == first(b)` unless I'm totally misunderstanding something. Which means you can simplify this to:

```
if f := first(b); f.index(b) > lo {
  it, ok = f, true
}
```

The semantics of `iterateFrom` are a bit surprising. I would think it would always return an iterator if there are any entries `>= index`. Did you consider putting this logic in `iterateFrom`? Would doing so break other use cases. It looks like `ringBuf.get` would need to be fixed, but this would fix `ringBuf.scan`.

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/raftentry/cache.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXm25tF925kgPgZtVdB:-MXm25tF925kgPgZtVdC:bwzjhxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c925489b623b6fd93ba81648631e1b42f181438/pkg/kv/kvserver/raftentry/cache.go#L187)):*
> ```Go
> 	}
> 	if truncate {
> 		// Note that if !add, ents[0].Index may not even be in the cache
> ```

I think there's still an odd case here where `add = true, truncate = true` but we are attempting to insert a set of non-overlapping, earlier entries. In that case, it appears that `ringBuf.add` will be a no-op because it can't allow gaps. By definition, this is a case where truncating from the first index in `ents` will be equivalent to truncating from the last entry in `ents` - both broken before this PR, both fixed after it.

However, even after this PR, I think this will lead to the cache being empty instead of the higher-index entries being truncated and replaced by the lower-index entries. So we'll immediately miss the cache next time we try to query for those new entries.

Do you mind trying to create this scenario in a test? It will be something like `add([10, 11, 12], true)`, `add([4, 5, 6], true)`. We should end up with `[4, 5, 6]`, but I suspect we'll end up with `[]`.

This subtle interaction leads me to believe that we should be truncating before adding. We should probably also remove the `Some entries were already overwritten` branch to avoid the truncate operation's correctness depending on the add operation doing something that it doesn't always promise to do - overwriting every entry.
___
*[pkg/kv/kvserver/raftentry/cache.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlUTMWAe0s3AtuOY4g:-MXm6iWg3NNhARyX63ud:btd51a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/cache.go#L381)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think `e.Term` and `prevTerm` should be swapped here.
</blockquote></details>

I agree.
___
*[pkg/kv/kvserver/raftentry/cache_test.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXm4PwE0tIj7IIIMM7h:-MXm4PwE0tIj7IIIMM7i:b-m0yimu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c925489b623b6fd93ba81648631e1b42f181438/pkg/kv/kvserver/raftentry/cache_test.go#L196)):*
> ```Go
> 	// Cache has entries 4, 5. Offer an oversize entry at index 3 (which is
> 	// notably before 4) and request truncation. This should clear all entries
> 	//>= 3, i.e. everything.
> ```

nit: spacing at beginning of line.
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlye3g9t_tu_-35gcg:-MXm4vv45Pu7BjTZMU1q:bn3tvgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/ring_buffer.go#L75)):*
> Which means you can simplify this to

+1 I also find this easier to understand, but we may want to make it even more clearly `max(lo, first)`. How about something like:
```
it, ok := iterateFrom(b, max(lo, first(b).index(b)))
```

> but this would fix ringBuf.scan

I'm not sure that it would. The contract of Scan is "If any entries are returned for the specified indices, they will start with index lo and proceed sequentially without gaps". So we seem to prefer returning nothing over skipping the lower bound index and returning other entries.
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXm6wpV2Zd739hdjFml:-MXm6wpV2Zd739hdjFmm:bp23l5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/ring_buffer.go#L91)):*
> ```Go
> 		if b.len > 0 {
> 			if lastIdx := last(b).index(b); lastIdx >= lo {
> 				err := errors.Errorf(
> ```

nit: why the separate variable definition?

**Review by tbg — COMMENTED** [review]
Thanks for the reviews! Feedback addressed (all in a new commit). Appreciate another close look before I merge this.

> Dismissed @erikgrinaker and @nvanbenschoten from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MXr0x7r3zV6tE5dnKMi:b6xzk8f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/raftentry/cache.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXm25tF925kgPgZtVdB:-MXqzvL65V0TdSZG09uM:bl7bjkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c925489b623b6fd93ba81648631e1b42f181438/pkg/kv/kvserver/raftentry/cache.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think there's still an odd case here where `add = true, truncate = true` but we are attempting to insert a set of non-overlapping, earlier entries. In that case, it appears that `ringBuf.add` will be a no-op because it can't allow gaps. By definition, this is a case where truncating from the first index in `ents` will be equivalent to truncating from the last entry in `ents` - both broken before this PR, both fixed after it.

However, even after this PR, I think this will lead to the cache being empty instead of the higher-index entries being truncated and replaced by the lower-index entries. So we'll immediately miss the cache next time we try to query for those new entries.

Do you mind trying to create this scenario in a test? It will be something like `add([10, 11, 12], true)`, `add([4, 5, 6], true)`. We should end up with `[4, 5, 6]`, but I suspect we'll end up with `[]`.

This subtle interaction leads me to believe that we should be truncating before adding. We should probably also remove the `Some entries were already overwritten` branch to avoid the truncate operation's correctness depending on the add operation doing something that it doesn't always promise to do - overwriting every entry.
</blockquote></details>

:thumbsup: thanks, this is a good simplification. Test case is added and passes now (it did not originally, just like you suspected).
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlye3g9t_tu_-35gcg:-MXqztwH8OwDfQbgcKmi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/ring_buffer.go#L75)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Which means you can simplify this to

+1 I also find this easier to understand, but we may want to make it even more clearly `max(lo, first)`. How about something like:
```
it, ok := iterateFrom(b, max(lo, first(b).index(b)))
```

> but this would fix ringBuf.scan

I'm not sure that it would. The contract of Scan is "If any entries are returned for the specified indices, they will start with index lo and proceed sequentially without gaps". So we seem to prefer returning nothing over skipping the lower bound index and returning other entries.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
> Dismissed @petermattis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @petermattis)

___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXlye3g9t_tu_-35gcg:-MXr177n5wzGL50CMjOP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2c1cbd810dc37e2ddab00347c89193770ce84/pkg/kv/kvserver/raftentry/ring_buffer.go#L75)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by petermattis — COMMENTED** [review]
LGTM, though I'm too distant from this code to give it a real stamp of approval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MXrP0prCdf4d_B-1l31:b-q3ipo6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MXsYheEDxPitl5cei7T:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/raftentry/cache.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsWbSp94jQFL2rf814:-MXsWbSp94jQFL2rf815:b-733prz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/cache.go#L184)):*
> ```Go
> 	var bytesAdded, entriesAdded, bytesRemoved, entriesRemoved int32
> 	// We truncate (if requested) before adding. This can lead to "wasted"
> 	// work we're were zeroing out entries we would repopulate anyway, but
> ```

`s/we're were/where we're/`
___
*[pkg/kv/kvserver/raftentry/cache_test.go, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsWyGS2PepZ0JTBs9m:-MXsWyGS2PepZ0JTBs9n:b6qardv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/cache_test.go#L104)):*
> ```Go
> 		act = append(act, it.index(b))
> 		if len(act) > 1000 {
> 			panic("x")
> ```

Did you mean to say something here?
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsY3W13g8LRAmz6w1D:-MXsY3W13g8LRAmz6w1E:b-diades) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/ring_buffer.go#L76)):*
> ```Go
> 		// (say the buf is idx=[100, 101, 102] and `lo` is 99),
> 		// we need to truncate everything and need to use the
> 		// first index that gives us a valid iterator back.
> ```

I would point out explicitly that `iterateFrom` returns `!ok` if given an index below the first index in the buffer.
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsXcRq5Ozl2GowohYB:-MXsXcRq5Ozl2GowohYC:b3fc47m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/ring_buffer.go#L80)):*
> ```Go
> 	}
> 	it, ok := iterateFrom(b, lo)
> 	if !ok {
> ```

Do we need this early return? The rest of the method works without it, which is probably an indication that we shouldn't add unnecessary branching which could eventually hide a bug.
___
*[pkg/kv/kvserver/raftentry/ring_buffer_test.go, line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsYllNBziI_oyKi4rB:-MXsYllNBziI_oyKi4rC:bcbsies) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/ring_buffer_test.go#L17)):*
> ```Go
> 
> 	"github.com/stretchr/testify/require"
> )
> ```

Think it's worth adding testing for each of the methods in the `ringBuf`'s external interface (those in `rangeCache`)? These may be a bit redundant with the testing we already have for `Cache`, but given how much difficulty we seem to be having with getting this to be correct, tests at a few layers may not be a bad idea.

Or maybe we could have someone with fresh eyes (and a bit less on their plate at the moment) come and add some tests here.

**Review by tbg — COMMENTED** [review]
TFTRs!

bors r=nvanbenschoten,erikgrinaker

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-:-MY4Bb0D33EiulyGdcms:b-cm59jc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @nvanbenschoten)

___
*[pkg/kv/kvserver/raftentry/cache_test.go, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsWyGS2PepZ0JTBs9m:-MY3jihi89kLXLLZYe8E:b-zdk9bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/cache_test.go#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to say something here?
</blockquote></details>

Oops, this is leftover debugging from fixing the bug where an iter on the empty buf accidentally ended up always valid. Removed.
___
*[pkg/kv/kvserver/raftentry/ring_buffer.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsXcRq5Ozl2GowohYB:-MY3kJxp7lr-9g0RojIL:b61f338) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/ring_buffer.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this early return? The rest of the method works without it, which is probably an indication that we shouldn't add unnecessary branching which could eventually hide a bug.
</blockquote></details>

We don't, good call.
___
*[pkg/kv/kvserver/raftentry/ring_buffer_test.go, line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63302#-MXsYllNBziI_oyKi4rB:-MY3oYyv4IjjOVBA4pz9:bikwbri) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e338fdee7aef3fa3244fae633b8da0a9882cf12/pkg/kv/kvserver/raftentry/ring_buffer_test.go#L17)):*
> Or maybe we could have someone with fresh eyes (and a bit less on their plate at the moment) come and add some tests here.

Heh, that'll never happen. I wrote unit tests. They didn't turn up anything, but it's nice to have them.

**Comment by irfansharif** [comment]
We should mint this PR as an NFT.

**Pull request merged**
