### PR TITLE
storage: improve message on slow Raft proposal

### PR DESCRIPTION
**Pull request by tbg**
Touches #33007.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Doesn't this change deserve a release note that says more than "none"?

**Comment by tbg** [comment]
Definitely. I'll make sure it has one as it gets closer to merging.

**Comment by spencerkimball** [comment]
This is a fundamental change to the way CRDB handles problems. Because errors are returned after 60s of waiting, the system will still effectively seize up, but applications will begin to receive errors. Perhaps an alternative mechanism makes sense where this is a cluster setting (on by default), where the range itself tracks last forward progress and after 60s (cluster setting could control this), clears all waiting proposals, and begins to refuse new proposals immediately. That feels like a more understandable error condition than each new request hitting the range taking an additional 60s to report an error.

**Comment by tbg** [comment]
PTAL, I've removed the proactive return path but kept the improved logging.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-:-LYSc_W4Ckiu6pIQ321N:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_write.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-LYSbxJv9mlEpMLQrL1W:-LYSbxJv9mlEpMLQrL1X:b-93julg) ([raw file](https://github.com/cockroachdb/cockroach/blob/95a811c82bb303f3bad84500e933f652eb365f78/pkg/storage/replica_write.go#L227)):*
> ```Go
> 			log.Warningf(ctx, `have been waiting %.2fs for proposing command %s.
> This range is likely unavailable.
> Please submit this message along with
> ```

Submit an issue? Do you want to include the github new-issue link?
___
*[pkg/storage/replica_write.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-LYScQ7V2w4VAFbaUAV2:-LYScQ7V2w4VAFbaUAV3:b3djh71) ([raw file](https://github.com/cockroachdb/cockroach/blob/95a811c82bb303f3bad84500e933f652eb365f78/pkg/storage/replica_write.go#L242)):*
> ```Go
> 				contextStr := ""
> 				if err := ctx.Err(); err != nil {
> 					contextStr = " with context cancellation"
> ```

Shouldn't this be using `err.Error()`? What if there is a different error than cancellation here?

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=petermattis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-:-LYT0Apv-3D9Jg9_9ngi:b-spmsx3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_write.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-LYSbxJv9mlEpMLQrL1W:-LYSzXyr2UFVNhs8WVcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/95a811c82bb303f3bad84500e933f652eb365f78/pkg/storage/replica_write.go#L227)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Submit an issue? Do you want to include the github new-issue link?
</blockquote></details>

Done.
___
*[pkg/storage/replica_write.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34296#-LYScQ7V2w4VAFbaUAV2:-LYSzZn5E6oCj1jc-mwp:b-lzgvp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/95a811c82bb303f3bad84500e933f652eb365f78/pkg/storage/replica_write.go#L242)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't this be using `err.Error()`? What if there is a different error than cancellation here?
</blockquote></details>

`ctx.Err()` is always `context.{DeadlineExceeded,Timeout}` so its `.Error()` isn't relevant. However, I realized that we already have a naked return for `pErr` which is much better! I didn't want to introduce it because it's ugly, but now that it's there we might as well use it.

**Comment by tbg** [comment]
Linter.

bors r=petermattis

**Pull request merged**
