### PR TITLE
compose: add postgres compare test

### LINKED ISSUE #33477: sql: implement a test generator that exercises SQL mutations for crdb and pg side-by-side
We want a random schema generator + random mutation generator, that generates mutation statements valid for both postgres and cockroachdb.

The generator for schemas must generate
- variable number of families
- variable uses of DEFAULT
- variable uses of CHECK
- variable uses of NOT NULL constraints
- variable index combinations (unique and non-unique)
- variable FK definitions
- variable interleaving definitions
- variable alter column scenarios (i.e. SQL mutations inside a txn with some ALTERs before the mutation statement)

The generator for mutations must generate
- various RETURNING clauses
- various combinations of target columns
- various source data plans
- various uses of USING DEFAULTS
- various uses of the DEFAULT keyword in VALUES clauses
- various column lists in ON CONFLICT(...)
- occurrences of ON CONFLICT DO NOTHING
- various assignments in UPDATE and ON CONFLICT DO UPDATE
- various ORDER BY + LIMIT clauses to control input batching

In all scenarios the code must exercise with different starting situations in the target table: with no data, with some data, with enough data that more than 1 mutation batch is executed.

In all scenarios the comparison code with pg must ensure that:
- the result of the mutation in the target table is compatible with that of pg (same data modulo ordering)
- the result row counts are compatible (when no RETURNING)
- the result sets (with RETURNING) are compatible modulo ordering

Optionally the generator can exercise crdb-only UPSERT syntax (without comparison to pg)

### PR DESCRIPTION
**Pull request by madelynnblue**
Add a docker-compose test that spins up postgres and cockroach servers for
differential testing. Run some sqlsmith on them and verify the output is
identical. Has already found a few incorrectness bugs. The test framework
is written in such a way that, although a single query is generated per
run, each connection can have different mutations (which shouldn't change
the output) applied. In addition, two cockroach servers are started so
that they can be configured differently to ensure output doesn't change
when, say, there's different vectorized settings (there's no tests yet
that do this, but the framework is here for them to be added).

The cmpconn package has been changed to remove its go routines and
test row-by-row instead of fetching all of the rows. This is because
there was a bug that sometimes messed up the order of the rows. It is
possibly slower due to not using multiple goroutines for comparison,
but I have not seen any false positives since this change.

This has been added as a new compose package that is designed to run
nightly teamcity jobs needing docker-compose. The acceptance tests aren't
a good fit for nightlies since these need to run for a while. The makefile
has been taught about `make compose` to run these.

Fixes #33477

### CODE REVIEW

**Comment by mjibson** [comment]
@bobvawter can you review the make and bash scripts in the last commit and asses the design (i.e., is it a good idea to make a new package to do this)? @yuzefovich can you review the rest? Thanks.

On the chance that I go out on paternity leave before this is in, can @yuzefovich see this through to getting merged?

**Review by bobvawter — COMMENTED** [review]
The `Makefile` and shell scripts look good to me.  At some point when we switch to a newer kernel ABI we'll need to fix up the filenames, but that's an easy grep.

> Reviewed 3 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-:-LzDFqOvBCA2kCNF1f9M:bw25vrn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
The rest :lgtm: And no worries, I'll make sure it gets merged :)

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 8 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-:-LzDWL108Eti3feKdctJ:b-kdmoh9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/smithcmp/cmpconn/compare.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDQteZDsv-jxNo_1Ph:-LzDQteZDsv-jxNo_1Pi:b-5cp4gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5b3f5325b703637f250a1dbdeedf10c6ff02f9/pkg/cmd/smithcmp/cmpconn/compare.go#L149)):*
> ```Go
> 		}),
> 		cmp.Comparer(func(x, y *apd.Decimal) bool {
> 			x.Abs(x)
> ```

Shouldn't we compare the signs here first before using the absolute values?
___
*[pkg/compose/compare/compare/compare_test.go, line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDUcN71VPLqx2cbLeQ:-LzDUcN805M24RdQrZHx:b-n1qsqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/compose/compare/compare/compare_test.go#L39)):*
> ```Go
> 		"postgres":   "postgresql://postgres@postgres:5432/",
> 		"cockroach1": "postgresql://root@cockroach1:26257/?sslmode=disable",
> 		"cockroach2": "postgresql://root@cockroach2:26257/?sslmode=disable",
> ```

Is it not used at the moment but the intent is to maybe use vectorized engine later?
___
*[pkg/compose/compare/compare/empty.go, line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDVegF57T4uJ4dP0n5:-LzDVegF57T4uJ4dP0n6:b-afgg3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/compose/compare/compare/empty.go#L13)):*
> ```Go
> package compare
> 
> // This file is here so go test always finds at least one file.
> ```

Why does `go test` need to find at least one file?
___
*[pkg/sql/mutations/mutations.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDRprG38_4qqAH2ZIU:-LzDRprG38_4qqAH2ZIV:b-ojhcji) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d6baf00eb7651bf7a6addd35446a157b17ea64/pkg/sql/mutations/mutations.go#L38)):*
> ```Go
> 	ColumnFamilyMutator StatementMutator = sqlbase.ColumnFamilyMutator
> 
> 	// PostgresMutator applies modifies strings such that they execute identically
> ```

[nit]: "applies modifies."
___
*[pkg/cmd/smithcmp/cmpconn/conn.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDT_G3BJv8zgZKXA6C:-LzDT_G3BJv8zgZKXA6D:bxaq5xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/cmd/smithcmp/cmpconn/conn.go#L142)):*
> ```Go
> 		for name, rows := range connRows {
> 			if !rows.Next() {
> 				minCount = rowCounts[name]
> ```

I think an `if` statement is missing before updating `minCount`.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44127)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/smithcmp/cmpconn/compare.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDQteZDsv-jxNo_1Ph:-LzDahZ59YNUa5AlEkKA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a5b3f5325b703637f250a1dbdeedf10c6ff02f9/pkg/cmd/smithcmp/cmpconn/compare.go#L149)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Shouldn't we compare the signs here first before using the absolute values?
</blockquote></details>

Done.
___
*[pkg/compose/compare/compare/compare_test.go, line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDUcN71VPLqx2cbLeQ:-LzDb4wU1VbMryPG0uBh:btqqu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/compose/compare/compare/compare_test.go#L39)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is it not used at the moment but the intent is to maybe use vectorized engine later?
</blockquote></details>

Correct.
___
*[pkg/compose/compare/compare/empty.go, line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDVegF57T4uJ4dP0n5:-LzDb67Q1Jm1jq7RakHv:b-bh1zvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/compose/compare/compare/empty.go#L13)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why does `go test` need to find at least one file?
</blockquote></details>

Because otherwise it exits with an error. This is needed because `make test` will error because of that.
___
*[pkg/sql/mutations/mutations.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDRprG38_4qqAH2ZIU:-LzDbUZb-2kayYij9Ujq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d6baf00eb7651bf7a6addd35446a157b17ea64/pkg/sql/mutations/mutations.go#L38)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: "applies modifies."
</blockquote></details>

Done.
___
*[pkg/cmd/smithcmp/cmpconn/conn.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDT_G3BJv8zgZKXA6C:-LzDavpyCseptbzzuJT4:bulwrnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/cmd/smithcmp/cmpconn/conn.go#L142)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think an `if` statement is missing before updating `minCount`.
</blockquote></details>

minCount can only be set one time since the break after this exits the ReadRows for loop, so I think this is correct as is.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 3 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44127)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter, @mjibson, and @yuzefovich)

___
*[pkg/compose/compare/compare/empty.go, line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDVegF57T4uJ4dP0n5:-LzDmDq6333lIJseHX9d:bl0xfe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/compose/compare/compare/empty.go#L13)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Because otherwise it exits with an error. This is needed because `make test` will error because of that.
</blockquote></details>

Ok, cool.
___
*[pkg/cmd/smithcmp/cmpconn/conn.go, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44127#-LzDT_G3BJv8zgZKXA6C:-LzDm4724mzcOfiimL55:b5qbpas) ([raw file](https://github.com/cockroachdb/cockroach/blob/019124fa7dfc9a164c08befcb7566eefc778334b/pkg/cmd/smithcmp/cmpconn/conn.go#L142)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

minCount can only be set one time since the break after this exits the ReadRows for loop, so I think this is correct as is.
</blockquote></details>

Oh yeah, I misunderstood the code.

**Comment by andreimatei** [comment]
On my machine `TestComposeCompare` fails saying
```
docker.credentials.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
```

Would you mind please finding a way to keep `make test` (or at the very least `make testshort`) working (without specifying a package).

**Comment by yuzefovich** [comment]
Matt is out on paternity leave, and I'm very unfamiliar with the build setup and what not. @bobvawter could you please look into it?

**Comment by yuzefovich** [comment]
@andreimatei not sure whether you're still interested in fixing the failure, but I got the same error when I tried to run `make compose` locally and was able to go around it by following [this](https://github.com/docker/compose/issues/6517#issuecomment-518646263) (I did `s/"desktop"/""/` in `~/.docker/config.json` and restarted docker desktop). It appears to be an issue with docker on mac, and I'm not sure whether we should be fixing it somehow through `make` invocation.

**Pull request merged**
