### PR TITLE
*: License hygiene updates

### PR DESCRIPTION
**Pull request by bdarnell**
Ensure that all CCL-licensed files are under directories named `ccl`, and that all OSS files have a standardized CRL Apache license headers. There is a slight functional change to the Makefile in the second commit. The last commit is the big mechanical one; you may want to look at the first four commits individually.

### CODE REVIEW

**Comment by tbg** [comment]
@bdarnell mind fixing up CI before I take a look? That plays better with reviewable.

**Comment by bdarnell** [comment]
OK, CI is fixed (by dropping the change to the UI and makefile. This leaves a CCL file in the `distccl` directory instead of one named exactly `ccl` but that's more trouble than it's worth to clean up right now.

**Review by petermattis — APPROVED** [review]
:lgtm:

I just noticed we say `Cockroach Authors` everywhere. Should that say `CockroachDB Authors`?

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37924#-:-LgT-aazAn35h1UHjaKR:bz9i3ul)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by bdarnell** [comment]
bors r+

> I just noticed we say Cockroach Authors everywhere. Should that say CockroachDB Authors?

I'll leave that for another day, and point out that the repo and binary are both named "cockroach", not "CockroachDB".

**Pull request merged**
