### PR TITLE
roachtest: update pgjdbc version under test

### LINKED ISSUE #127209: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16082126?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAzureBazel/16082126?buildTab=artifacts#/pgjdbc) on master @ [eccb77d2320955b477bb03bc1f1aee137bd1de76](https://github.com/cockroachdb/cockroach/commits/eccb77d2320955b477bb03bc1f1aee137bd1de76):

```
(pgjdbc.go:131).func1: all attempts failed for building pgjdbc (without tests): full command output in run_222310.772912392_n1_cd-mntdata1pgjdbcpgj.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/pgjdbc/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=azure</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for azure clusters_</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40317

### LINKED ISSUE #127250: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16088573?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16088573?buildTab=artifacts#/pgjdbc) on release-24.2 @ [238d10a22cff57ddc8393b149cffb58883a2a89f](https://github.com/cockroachdb/cockroach/commits/238d10a22cff57ddc8393b149cffb58883a2a89f):

```
(pgjdbc.go:131).func1: all attempts failed for building pgjdbc (without tests): full command output in run_150542.807505855_n1_cd-mntdata1pgjdbcpgj.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/pgjdbc/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16088573/pgjdbc/1721140290908/1721142481745)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #127232 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-release-23.1.24-rc release-blocker]
- #127209 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40341

### PR DESCRIPTION
**Pull request by rafiss**
This keeps our tests up to date with the latest release, and also resolves upstream dependency issues.

fixes: https://github.com/cockroachdb/cockroach/issues/127209
fixes: https://github.com/cockroachdb/cockroach/issues/127250
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127388#-:-O21H_k13f3CDkUB80YC:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar and @vidit-bhat)

**Comment by rafiss** [comment]
tftr

bors r+

**Comment by rafiss** [comment]
i kicked off a sample run here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16120838?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

i'll make sure that works correctly before merging

bors r-

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
