### PR TITLE
backupccl: support encrypted backup files

### PR DESCRIPTION
**Pull request by dt**
This adds an 'encryption_passphrase' option to the BACKUP and RESTORE commands.

Including this option in the WITH clause of the BACKUP command will
cause it to encrypt the files it writes -- the BACKUP manifest(s) and
data files -- using the supplied passphrase to derive a key. To RESTORE
such a backup, the same option (with the same passphrase of course) must
then be passed to the RESTORE command. Example usage:

```
> BACKUP DATABASE myapp TO 'nfs://shared/backups/myapp' WITH encryption_passphrase = 'abc123';
...
> RESTORE DATBASE myapp FROM 'nfs://shared/backups/myapp' WITH encryption_passphrase = 'abc123';
```

When used with incremental backups, the 'encryption_passphrase' option
is applied to all the supplied BACKUP URIs, meaning that the same
passphrase must be used when appending another incremental backup to an
existing backup. Similarly, when used with partitioned backups, the key
provided is applied to files in all partitions.

Under the hood, encryption is done using AES-256-GCM. GCM is used to
both encrypt and authenticate the files. A random per-file salt is used
to derive per-file AES keys from the supplied passphrase. Based on the
structure of the current implementation, BACKUP and RESTORE will use
more memory when using encryption, as during encryption and decryption,
both the plain-text and cipher-text of a given file are held in memory.

Release note (enterprise change): Add support for encrypting backup files to and BACKUP/RESTORE via the 'encryption_passphrase' option.

### CODE REVIEW

**Comment by dt** [comment]
this still needs a couple end-to-end tests in backup but figured I'd get it out for first impressions in the meantime.

**Review by pbardea — COMMENTED** [review]
The approach looks good to me.

Although I think that the safeguards of needing to pass some encryption options is good, I wanted to suggest an external storage interface that may allow us to push the encryption logic entirely in the storage layer and further prevent accidental forgetting of passing encryption options.

I'm strawman I'm thinking of is along the lines of a) Defining a new interface `EncryptedExternalStorage` which is similar to our current `ExternalStorage` interface but takes in an `EncryptionOptions`. b) Create an encrypted external storage wrapper struct which could own (embed?) an `ExternalStorage` object and handle the encryption itself, calling out to the non-encrypted {Read,Write}File methods. Then the export stores in backup/restore could be changed to the encrypted ones and wrapped which would help ensure that the export options were always passed through.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-:-LzD6yjM8lkYzCpewbx6:b-bsreeh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @pbardea)

**Comment by dt** [comment]
I looked at wrapping ExternalStorage initially. I ended up not doing that for two reasons: 

a) we _make_ new instances of ExternalStorage pretty regularly from URIs, so I'm not actually convinced it'd prevent accidental misuse -- you'd still need to be sure you passed the correct options every time. Embedding options in the URI could be an option, but then it gets messy since we have many URIs (incremental or partitioned) but ideally (for simplicity) don't have different encryption options (otherwise every File needs to start keeping its options as it gets shuffled around).

b) `ExternalStorage`'s Read/WriteFile has a streaming and seekable interface -- while you can make a streaming AES cipher, go's isn't seekable (though with CTR it _could_ be), but beyond that, if we want to do _authenticated_ encryption, steaming is really messy -- you shouldn't use any bytes until you authenticate them, but if you give someone a stream, they might do so.

**Comment by dt** [comment]
I chatted with @aaron-crl a bit yesterday and I'm going to re-work this a little. We want to make key derivation more expensive, but that isn't ideal if every file we write in every RPC has to do its own key derivation.

Rather than re-deriving a key from a passphrase on per-file basis (and with a unique per-file salt as a prefix of every file), we're going to switch to deriving only one key, from one salt, and then send that _key_ in the RPCs that then write individual data files (which will then pick unique IVs and store those as prefixes).

This will require some re-working to keep track of that salt in the coordinator and keep it constant across partitions/incrementals/etc.

**Comment by dt** [comment]
note that the first commit here has been split out to be reviewed separately and merge first in #44474, so this PR will only be updating the backup/restore logic to use those helpers.

**Comment by dt** [comment]
Okay, this has been updated so the BACKUP/RESTORE usage reflects the API changes discussed in #44474 and added a test which makes a table/partition/user/setting/etc all containing sentinel values and then does a couple partitioned, incremental backups and then searches for the sentinel anywhere in the backup directories to ensure we didn't miss any files, so I think this part is ready for review too now.

**Review by miretskiy — APPROVED** [review]
> Reviewed 7 of 15 files at r1, 2 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/backup.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-M-Lx-bo-kPoQVSfM1IC:-M-LwXrv1UPsnyUkp0g8:b8wxhns) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86eaa3bb620b1c6b63e1c805ccedcb02a763a0/pkg/ccl/backupccl/backup.go#L129)):*
> ```Go
> 	backupDesc, err := readBackupDescriptor(ctx, exportStore, BackupDescriptorName, encryption)
> 	if err != nil {
> 		backupManifest, manifestErr := readBackupDescriptor(ctx, exportStore, BackupManifestName, encryption)
> ```

BackupManifestName is the "future" name, if I'm not mistaken... Should we attempt to read it first?
Regardless if you choose to change it, perhaps drop a short comment inside this if block... (ie.g. try new version )
___
*[pkg/ccl/backupccl/backup.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-M-LwImcD3vo5lGyKON7:-M-LwImcD3vo5lGyKON8:bspiw0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86eaa3bb620b1c6b63e1c805ccedcb02a763a0/pkg/ccl/backupccl/backup.go#L167)):*
> ```Go
> 	if err := protoutil.Unmarshal(descBytes, &backupDesc); err != nil {
> 		if encryption == nil && storageccl.AppearsEncrypted(descBytes) {
> 			return BackupDescriptor{}, errors.Wrapf(err, "file appears encrypted -- try specifying %q", backupOptEncPassphrase)
> ```

any way to wrap this long line?
___
*[pkg/ccl/backupccl/backup.go, line 561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-M-LxUlT3WTOQekdZKdw:-M-LxUlT3WTOQekdZKdx:bek8jsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86eaa3bb620b1c6b63e1c805ccedcb02a763a0/pkg/ccl/backupccl/backup.go#L561)):*
> ```Go
> 		if v := opts[k]; v != "" {
> 			if k == backupOptEncPassphrase {
> 				v = "<redacted>"
> ```

I'm probably a bit paranoid... But if this value gets displayed somehow on the web page (job status? etc?) those "<>" might not look too good... Maybe choose different brackets?
___
*[pkg/roachpb/api.proto, line 1290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-M-LyhST8fIQrdHApSVM:-M-LyhST8fIQrdHApSVN:b-iq0io8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86eaa3bb620b1c6b63e1c805ccedcb02a763a0/pkg/roachpb/api.proto#L1290)):*
> ```protobuf
>   // Key specifies the key to use for encryption or decryption.
>   bytes key = 1;
> ```

extra \n?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44177)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/backup.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44177#-M-Lx-bo-kPoQVSfM1IC:-M-MEaXk8RnXYFVHgzhc:bwiop8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86eaa3bb620b1c6b63e1c805ccedcb02a763a0/pkg/ccl/backupccl/backup.go#L129)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

BackupManifestName is the "future" name, if I'm not mistaken... Should we attempt to read it first?
Regardless if you choose to change it, perhaps drop a short comment inside this if block... (ie.g. try new version )
</blockquote></details>

Eh, that's an unrelated change. I'd rather keep this diff focused on just encryption-related changes, and revisit that separately.

**Pull request merged**
