### PR TITLE
libroach: add basic encryption stats.

### PR DESCRIPTION
**Pull request by mberhault**
New endpoint: `/_status/stores` which for now only returns the store ID
and encryption stats.

The encryption stats is a serialized protobuf containing active key
information (but not the key itself).

This will be handled by CCL UI code since it needs access to CCL protos.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---

*[c-deps/libroach/engine.cc, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCqQPvAE_A-3rVvyiJ:-LDCqQPvAE_A-3rVvyiK:b67kkbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/engine.cc#L216)):*
> ```cpp
> 
>   std::string encryption_status;
>   auto status = this->env_mgr->env_stats_handler->GetEncryptionStats(&encryption_status);
> ```

It feels a bit weird for `GetEncryptionStats` to pass back the stats in a string. If there is every more than one implementation of `GetEncryptionStats`, we'll need all of them to encode the same proto. That makes me think that `GetEncryptionStats` should populate a proto and this method should be where the proto is serialized to a string.

Note that in other places we pass stats from C++ to Go using C structs. For example, `MVCCStatsResult`. I'm curious why we're using a proto here.

---

*[c-deps/libroach/testutils.h, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCoNED8eXV9up7wczw:-LDCoNED8eXV9up7wczx:b-oxmrun) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/testutils.h#L24)):*
> ```objc
> 
> // Returns initialized DBOptions with reasonable values for unittests.
> DBOptions defaultDBOptions() {
> ```

I think you need to mark this as inline. It's ok to place templated methods in a header, but for non-templated methods if you don't mark them as inline you can hit problems during linking with multiple definitions. This is dependent on the linker (i.e. it succeed on Linux but fail on Windows).

---

*[pkg/server/serverpb/status.proto, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCp-yS5n9KVthpFLsZ:-LDCp-yS5n9KVthpFLs_:bctetse) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/server/serverpb/status.proto#L609)):*
> ```protobuf
> 
> message StoresRequest {
>   // TODO(tamird): use [(gogoproto.customname) = "NodeID"] below. Need to
> ```

I'm guessing tamird isn't going to get to this. Let's either remote the TODO or put someone else's name there.

---

*[pkg/storage/engine/engine.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCpJvY8Dj05rSC_2Fh:-LDCpJvY8Dj05rSC_2Fi:bmh71kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/storage/engine/engine.go#L347)):*
> ```Go
> // EnvStats is a set of RocksDB env stats, including encryption status.
> type EnvStats struct {
> 	// EncryptionStatus is a serialized	ccl/storageccl/engineccl/enginepbccl/stats.go::EncryptionStatus protobuf.
> ```

`s/stats.go/stats.proto/g`? Not sure if you need the full path above. It also makes the line very long. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850)*

**Comment by bdarnell** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[c-deps/libroach/engine.cc, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCqQPvAE_A-3rVvyiJ:-LDCvlPu8eloInBWdriN:b-2tp8j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/engine.cc#L216)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It feels a bit weird for `GetEncryptionStats` to pass back the stats in a string. If there is every more than one implementation of `GetEncryptionStats`, we'll need all of them to encode the same proto. That makes me think that `GetEncryptionStats` should populate a proto and this method should be where the proto is serialized to a string.

Note that in other places we pass stats from C++ to Go using C structs. For example, `MVCCStatsResult`. I'm curious why we're using a proto here.
</blockquote></details>

The problem here is that the OSS code doesn't have access to the proto, it's deeply CCL only. This serialized proto is generated in `ccl/db.cc` and will only be read by CCL code in the UI (and potentially CCL hooks into metrics). The OSS code just passes around an opaque blob.

This is an unfortunate thing we've had to do over and over again for encryption due to the many components that need to talk to each other through OSS.

---

*[c-deps/libroach/testutils.h, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCoNED8eXV9up7wczw:-LDCwf6194uU3JogRwUQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/testutils.h#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you need to mark this as inline. It's ok to place templated methods in a header, but for non-templated methods if you don't mark them as inline you can hit problems during linking with multiple definitions. This is dependent on the linker (i.e. it succeed on Linux but fail on Windows).
</blockquote></details>

Done.

---

*[pkg/server/serverpb/status.proto, line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCp-yS5n9KVthpFLsZ:-LDD-_7nBQzzXS-qLYVC:b-u0eu59) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/server/serverpb/status.proto#L609)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm guessing tamird isn't going to get to this. Let's either remote the TODO or put someone else's name there.
</blockquote></details>

Removed TODO.

---

*[pkg/storage/engine/engine.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCpJvY8Dj05rSC_2Fh:-LDD-WHy826B1Dcja0JS:bt04s) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/storage/engine/engine.go#L347)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/stats.go/stats.proto/g`? Not sure if you need the full path above. It also makes the line very long. 
</blockquote></details>

Done. And shrunk to `enginepbccl/stats.proto`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850)*

**Comment by petermattis** [comment]
Can we add an end-to-end test in the CCL code that the new endpoint returns non-empty encryption status?

---

Review status: 23 of 28 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/engine.cc, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCqQPvAE_A-3rVvyiJ:-LDEcAkL5Deop5lbdpMO:bq9zfnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/engine.cc#L216)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

The problem here is that the OSS code doesn't have access to the proto, it's deeply CCL only. This serialized proto is generated in `ccl/db.cc` and will only be read by CCL code in the UI (and potentially CCL hooks into metrics). The OSS code just passes around an opaque blob.

This is an unfortunate thing we've had to do over and over again for encryption due to the many components that need to talk to each other through OSS.
</blockquote></details>

Ack. It doesn't seem problematic for the OSS code to define an encryption stats struct that is used by CCL. If you leave the code as-is, at least add a comment alluding to the hoops which are causing this structure.

Update: I completely missed that the stats fields are `KeyInfo` proto. You could still use a struct, though I suppose that is more onerous that I was imagining when I suggested it.

---

*[c-deps/libroach/ccl/db.cc, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDEfeaV2CcAW1n_bXNu:-LDEfeaV2CcAW1n_bXNv:bdaibqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2ae813683d5e5360e2e323460cf3d26eb1808f/c-deps/libroach/ccl/db.cc#L42)):*
> ```cpp
> 
>     bool has_stats = false;
>     if (this->store_key_manager_ != nullptr) {
> ```

Nit: no need for the explicit `this->`. We don't use `this` in other parts of our C++ code.

---

*[c-deps/libroach/ccl/db.cc, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDEf9A3EBgmi-c66ZbW:-LDEf9A3EBgmi-c66ZbX:b-e9sot4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2ae813683d5e5360e2e323460cf3d26eb1808f/c-deps/libroach/ccl/db.cc#L45)):*
> ```cpp
>       has_stats = true;
>       // Transfer ownership of new key info to status proto, this frees any previous value.
>       enc_status.set_allocated_active_store_key(store_key_manager_->CurrentKeyInfo().release());
> ```

Transferring ownership is surprising.  I'm also surprised you don't need any locking here. Seems like calling `DBGetEnvStats` concurrently is unsafe, and calling it consecutively will return different values. 

---

*[pkg/storage/engine/engine.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCpJvY8Dj05rSC_2Fh:-LDEdadO3jbwLpiQwDv6:bns6x61) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/storage/engine/engine.go#L347)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Done. And shrunk to `enginepbccl/stats.proto`.
</blockquote></details>

Nit: you've got some spurious spaces after the word "serialized".

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-:-LDEh3no6A076pGFuO1c:b55y27s)*

**Comment by mberhault** [comment]
bors r=bdarnell

**Comment by petermattis** [comment]
Was this merged prematurely? I didn't see an LGTM or an approved. My comment below about locking needs an answer. Am I missing something?

---

Review status: 23 of 28 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-:-LDHzKAT3KnSmf5zsY7D:b-31iabh)*

**Comment by mberhault** [comment]
uh. oops. that was definitely premature. I'll address the nits in a followup PR. The locking isn't needed though.

---

Review status: 23 of 28 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/engine.cc, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCqQPvAE_A-3rVvyiJ:-LDI2CER2132ryc4eMd2:b-holm4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/c-deps/libroach/engine.cc#L216)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. It doesn't seem problematic for the OSS code to define an encryption stats struct that is used by CCL. If you leave the code as-is, at least add a comment alluding to the hoops which are causing this structure.

Update: I completely missed that the stats fields are `KeyInfo` proto. You could still use a struct, though I suppose that is more onerous that I was imagining when I suggested it.
</blockquote></details>

There's a struct for the returns from `GetEnvStats` into go code, but the encryption_status field is just that opaque blob as it reuses a lot of the CCL-only protos. Eventually other stats will be OSS (eg: file/size counts) since those use OSS fields and will be in that same struct. Since this is the only field touched by `GetEncryptionStats`, it doesn't need to get the outer `DBEnvStatsResult`.

---

*[c-deps/libroach/ccl/db.cc, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDEfeaV2CcAW1n_bXNu:-LDI3fGD50YdGEbQmRn5:bab0hfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2ae813683d5e5360e2e323460cf3d26eb1808f/c-deps/libroach/ccl/db.cc#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: no need for the explicit `this->`. We don't use `this` in other parts of our C++ code.
</blockquote></details>

Good point. Removing in upcoming PR.

---

*[c-deps/libroach/ccl/db.cc, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDEf9A3EBgmi-c66ZbW:-LDI2YgoEVm60ynb2bYy:b-axge0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2ae813683d5e5360e2e323460cf3d26eb1808f/c-deps/libroach/ccl/db.cc#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Transferring ownership is surprising.  I'm also surprised you don't need any locking here. Seems like calling `DBGetEnvStats` concurrently is unsafe, and calling it consecutively will return different values. 
</blockquote></details>

The object returned by `CurrentKeyInfo` is a unique_ptr of a copy of the current key, so it needs to be released to prevent deletion of the KeyInfo. The store_key_manager does not currently lock as it is write-once (at initialization time, locking is a TODO once we add post-initialization reload). 

---

*[pkg/storage/engine/engine.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDCpJvY8Dj05rSC_2Fh:-LDI3cBO8xWClkkrQ8aL:bl1v3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/620d1a02112a6b385d19bf218b9b2167e77ce1fa/pkg/storage/engine/engine.go#L347)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: you've got some spurious spaces after the word "serialized".
</blockquote></details>

oops. fixing in upcoming PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-:-LDI4TUL4Y3eWpVVo-VS:bceqm9d)*

**Comment by petermattis** [comment]
Review status: 23 of 28 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[c-deps/libroach/ccl/db.cc, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25850#-LDEf9A3EBgmi-c66ZbW:-LDIvIf74VDQoFwAuBq2:bn8rhyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d2ae813683d5e5360e2e323460cf3d26eb1808f/c-deps/libroach/ccl/db.cc#L45)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

The object returned by `CurrentKeyInfo` is a unique_ptr of a copy of the current key, so it needs to be released to prevent deletion of the KeyInfo. The store_key_manager does not currently lock as it is write-once (at initialization time, locking is a TODO once we add post-initialization reload). 
</blockquote></details>

Ah, the comment was confusing me. It sounds like you're transferring ownership from `store_key_manager_`, but really you're transferring ownership for the unique pointer. I think the comment should be adjusted. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25850)*

**Pull request merged**
