### PR TITLE
sql: clean-up/improve the handling of session vars + extend

### PR DESCRIPTION
**Pull request by knz**
Clean-up and simplification.

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm:

So a lot of these settings are ignored on our side.  How about we add a pg_comment field or something like that that gets output with the hint, so if they are set to something weird, we make it clear that it's for compatibility only that we allow the "setting" of the value at all.

Probably a good idea to double check each setting to see if all error cases are checked in tests.

> Reviewed 6 of 6 files at r1, 29 of 29 files at r2, 7 of 7 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27947#-:-LIMFBJd9aqGfy-7XUaN:b-121ir1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
> How about we add a pg_comment field or something like that that gets output with the hint, so if they are set to something weird, we make it clear that it's for compatibility only that we allow the "setting" of the value at all.

Very nice idea! Done.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 21 of 21 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27947#-:-LIMPtk77vj6GrbITAik:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by knz — COMMENTED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27947#-:-LIMSpY5901omCuuKOm9:bd5l6mr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
