### PR TITLE
kv: cleanup txn more eagerly

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, when a txn got a non-retriable error, its heartbeat
loop (if any) was left running until the client sent a rollback.
This patch makes the txn cleanup more eager - we do it immediately on
receiving the error.
Besides seeming sane (why wait for the client when we know what must
happen), this also makes the TxnCoordSender state more internally
consistent: if a non-retriable error contains an Aborted txn, we now
stop the hb loop before that loop has the opportunity to freakout about
running with an Aborted txn. It's unclear if non-retriable errors could
contain Aborted txns, but see below.

This patch also refactors the state update code in an attempt to make it
more readable.

In #34337 we see a crash due to the fact that a heartbeat is running for
a transaction whose proto status is no longer PENDING. It's not entirely
clear to me how that can happen since we "clean up the txn" - i.e. stop
the hb loop - after commits and roll backs as well on
TransactionAbortedErrors, but it's also not very convincing that it
can't happen. The thing is that the protocol between the "client" and
the "server" wrt communicating txn updates from the server is lax and
it's not very clear what kind of responses can carry an Aborted or
Committed proto in them.

This patch also makes leaf TxnCoordSender nimbler by not using
interceptors needed only by roots.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjo7h6YwvomVaqfcC:-LXVjo7h6YwvomVaqfcD:bhxn9bu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_coord_sender.go#L678)):*
> ```Go
> 	}
> 
> 	assertConsistentState := func() {
> ```

Is the goal to keep this forever? Adding in these assertions with no immediate plan to remove them doesn't seem great to me. They end up sitting around, making code harder to read, and preventing other cleanup.
___
*[pkg/kv/txn_coord_sender.go, line 687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVkGRNBMpNnZYoeo3O:-LXVkGRNBMpNnZYoeo3P:b-cjjecs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_coord_sender.go#L687)):*
> ```Go
> 
> 	// Move to the error state on non-retriable errors.
> 	if pErr != nil {
> ```

Why isn't this logic in `updateStateLocked`?
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjP5iEtTS2S9FOEdw:-LXVjP5iEtTS2S9FOEdx:b-kxtsxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b916e782e76e86bde30e5e4b725fdef98a962c47/pkg/kv/txn_interceptor_heartbeat.go#L39)):*
> ```Go
> // eliding EndTransaction requests on read-only transactions.
> //
> // txnHeartbeat should only be used for root transactions; leafs don't perform
> ```

Why remove this?
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjRJ9A3lwTpoXoCpP:-LXVjRJ9A3lwTpoXoCpQ:b-6myg9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_interceptor_heartbeat.go#L488)):*
> ```Go
> 
> 		// We need to be prepared here to handle the case of a
> 		// TransactionAbortedError with no transaction proto in it.
> ```

Could you leave a TODO for me to make this the only case where we get back an ABORTED error?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjo7h6YwvomVaqfcC:-LXWK_Fs9gltUb096Gs-:bcn9gbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_coord_sender.go#L678)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the goal to keep this forever? Adding in these assertions with no immediate plan to remove them doesn't seem great to me. They end up sitting around, making code harder to read, and preventing other cleanup.
</blockquote></details>

I've removed the assertion. Let's hope that the new cleanup makes the crash go away.
___
*[pkg/kv/txn_coord_sender.go, line 687 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVkGRNBMpNnZYoeo3O:-LXXtbPT2yYyRb3mnN9z:bkyuu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_coord_sender.go#L687)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why isn't this logic in `updateStateLocked`?
</blockquote></details>

yeah... I put some makeup on the pig; see if you like it now.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjP5iEtTS2S9FOEdw:-LXXtX_iDtDTx5yvS58p:btrd316) ([raw file](https://github.com/cockroachdb/cockroach/blob/b916e782e76e86bde30e5e4b725fdef98a962c47/pkg/kv/txn_interceptor_heartbeat.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why remove this?
</blockquote></details>

cause it wasn't true. The leaf TCS still has all the interceptors.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjRJ9A3lwTpoXoCpP:-LXXtX9I3WCg7dyOc7hq:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c9e0d62890e10894741feb8b33cc88a0552b177/pkg/kv/txn_interceptor_heartbeat.go#L488)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you leave a TODO for me to make this the only case where we get back an ABORTED error?
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
friendly ping :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-:-LY3ZPN93LwBYq5j05_s:b-shtn0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/txn_coord_sender.go, line 873 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3dhJkBaKWWBqbMuKI:-LY3dhJkBaKWWBqbMuKJ:b-lg5tax) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L873)):*
> ```Go
> // starting tracking the transaction - i.e. this is the case for DistSQL, which
> // just does reads and passes 0.
> func (tc *TxnCoordSender) updateStateLocked(
> ```

This logic is much cleaner!
___
*[pkg/kv/txn_coord_sender.go, line 900 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3dF2p6ZjVTa3HJ5hJ:-LY3dF2p6ZjVTa3HJ5hK:b-un1iwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L900)):*
> ```Go
> 
> 	if pErr == nil {
> 		if br.Txn != nil {
> ```

I was wondering about these checks a few days ago. What do you think about them? Now that we have the `CrossRangeTxnWrapperSender`, should anything in the TxnCoordSender have to deal with non-transactional batches or responses? If we're worried about malformed responses, maybe we just perform a single validation in the `txnLockGatekeeper`?

Or for now, just get rid of the check here, because `Update` is already a no-op for nil txns.
___
*[pkg/kv/txn_coord_sender.go, line 911 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3ftUO7YJVDN_uhUYq:-LY3ftUO7YJVDN_uhUYr:b-1eft1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L911)):*
> ```Go
> 			// transaction is not supposed to be used any more after a retriable
> 			// error.
> 			// Separately, the error needs to make its way back to the root.
> ```

Re-wrap?
___
*[pkg/kv/txn_coord_sender.go, line 922 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3ggc92g920ERDFkLC:-LY3ggc92g920ERDFkLD:bm64xwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L922)):*
> ```Go
> 			cp := pErr.GetTxn().Clone()
> 			tc.mu.txn.Update(&cp)
> 			tc.cleanupTxnLocked(ctx)
> ```

This is ok even on leafs? Hmm, I wonder if that could cause issues like counting metrics for the same transaction on a leaf node and a root node. All the more reason to have a restricted set of interceptors on leaf nodes.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjP5iEtTS2S9FOEdw:-LY3c1Fg1ehL8qLc62lt:b-gu9goa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b916e782e76e86bde30e5e4b725fdef98a962c47/pkg/kv/txn_interceptor_heartbeat.go#L39)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

cause it wasn't true. The leaf TCS still has all the interceptors.
</blockquote></details>

Let's fix that then! Maybe leave a TODO when we're constructing the interceptor stack that we can skip certain interceptors on leaf nodes. That's part of what makes the design appealing.

Are we currently relying on the leaf txns to not perform any writes? If one accidentally did, could we have two heartbeat loops?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 900 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3dF2p6ZjVTa3HJ5hJ:-LY9Agrn3ysf29scqCLW:b-e10bkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L900)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was wondering about these checks a few days ago. What do you think about them? Now that we have the `CrossRangeTxnWrapperSender`, should anything in the TxnCoordSender have to deal with non-transactional batches or responses? If we're worried about malformed responses, maybe we just perform a single validation in the `txnLockGatekeeper`?

Or for now, just get rid of the check here, because `Update` is already a no-op for nil txns.
</blockquote></details>

done the latter
___
*[pkg/kv/txn_coord_sender.go, line 911 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3ftUO7YJVDN_uhUYq:-LY9Alqr43iikldWiO2B:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L911)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Re-wrap?
</blockquote></details>

done
___
*[pkg/kv/txn_coord_sender.go, line 922 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LY3ggc92g920ERDFkLC:-LY9SYoj-2SA5ZCJqA8n:b7o8g76) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2ae00fdadd45124d306c6ba3df72227c5cd923/pkg/kv/txn_coord_sender.go#L922)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is ok even on leafs? Hmm, I wonder if that could cause issues like counting metrics for the same transaction on a leaf node and a root node. All the more reason to have a restricted set of interceptors on leaf nodes.
</blockquote></details>

good catch. I removed the metrics and other interceptor from leaves.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LXVjP5iEtTS2S9FOEdw:-LY9T6O15umoaAmC6Hfl:b-qsseby) ([raw file](https://github.com/cockroachdb/cockroach/blob/b916e782e76e86bde30e5e4b725fdef98a962c47/pkg/kv/txn_interceptor_heartbeat.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's fix that then! Maybe leave a TODO when we're constructing the interceptor stack that we can skip certain interceptors on leaf nodes. That's part of what makes the design appealing.

Are we currently relying on the leaf txns to not perform any writes? If one accidentally did, could we have two heartbeat loops?
</blockquote></details>

fixed!

**Review by nvb — APPROVED** [review]
:lgtm: nice cleanup!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-:-LYRu8iaB9s5Kw8GqCcR:b-qbsc6n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/txn_coord_sender.go, line 459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-LYRtkbk8T2dq_a8cyEQ:-LYRtkbk8T2dq_a8cyER:bncenaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/10880162ed59968d9b508241784e66a13ba039e5/pkg/kv/txn_coord_sender.go#L459)):*
> ```Go
> 		mu:      &tcs.mu,
> 	}
> 	if typ == client.RootTxn {
> ```

:thumbsup: let's see if this breaks anything.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34387#-:-LYXPfdYA0e56BOaypsf:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
