### PR TITLE
cmd/reduce: add a multi-region option

### PR DESCRIPTION
**Pull request by rytaft**
Add a multi-region option to `reduce` so that it's possible to reduce failures of the multi-region configurations of `costfuzz` and `unoptimized-query-oracle`.

Epic: None
Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102713)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/cmd/reduce/main.go` line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-NUOSHJg5qdalpdnvQOE:-NUOSHJg5qdalpdnvQOF:b-pqk8t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f956c63da231d5ef3b5dec1929bbee1230a9437e/pkg/cmd/reduce/main.go#L298)):*
> ```Go
> 				"--multitenant=false",
> 				"--set=errexit=false",
> 				"--format=tsv",
> ```

Should this use the `--multi-region` or `--geo-partitioned-replicas` option?  Or both?

**Comment by rytaft** [comment]
*[`pkg/cmd/reduce/main.go` line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-NUOSHJg5qdalpdnvQOE:-NUOTTH7Bx36nMLXu5Wc:b-ir6txp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f956c63da231d5ef3b5dec1929bbee1230a9437e/pkg/cmd/reduce/main.go#L298)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this use the `--multi-region` or `--geo-partitioned-replicas` option?  Or both?
</blockquote></details>

There is no `--multi-region` option (as far as I know), and `--geo-partitioned-replicas` is just used to set up the `movr` database with the old-style multi-region settings. `--nodes 9` is all that is needed to create the right kind of multi-region cluster.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-:-NUOX_IoCPIXs5Ccjg-9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/cmd/reduce/main.go` line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-NUOSHJg5qdalpdnvQOE:-NUOX9gVBNLIL0oxLUde:b-dbt5fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f956c63da231d5ef3b5dec1929bbee1230a9437e/pkg/cmd/reduce/main.go#L298)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

There is no `--multi-region` option (as far as I know), and `--geo-partitioned-replicas` is just used to set up the `movr` database with the old-style multi-region settings. `--nodes 9` is all that is needed to create the right kind of multi-region cluster.
</blockquote></details>

OK. Yeah, I just checked and didn't see the `--multi-region` option in code. I had just seen use of it here, so thought it might exist:
https://github.com/cockroachdb/cockroach/blob/d5c90f73093b3722aeabaf916784206213e52529/pkg/cli/interactive_tests/test_demo_partitioning.tcl.disabled#L87

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-:-NUOtjjN8hS9AtRw7wDt:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/cmd/reduce/main.go` line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102713#-NUOSHJg5qdalpdnvQOE:-NUOtemi1YrE5bkrsc95:b-onue6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f956c63da231d5ef3b5dec1929bbee1230a9437e/pkg/cmd/reduce/main.go#L298)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK. Yeah, I just checked and didn't see the `--multi-region` option in code. I had just seen use of it here, so thought it might exist:
https://github.com/cockroachdb/cockroach/blob/d5c90f73093b3722aeabaf916784206213e52529/pkg/cli/interactive_tests/test_demo_partitioning.tcl.disabled#L87
</blockquote></details>

Hmm strange :woman_shrugging:

**Pull request merged**
