### PR TITLE
sql: check replace view columns earlier

### LINKED ISSUE #99000: QA: internal error from ARRAY[*] expression in CREATE VIEW statement
From [star expressions in view definitions QA](https://gist.github.com/msirek/f8a9d1515244043088ec44d00accbe99),

The following CREATE VIEW statement with `*` in an ARRAY definition causes an internal error:
```sql
CREATE TABLE films (id int PRIMARY KEY, title text, kind text, classification CHAR(1), year int, language text, studio text, runtime float, country_code CHAR(2));
CREATE OR REPLACE VIEW comedies AS SELECT ARRAY[films.*]::string FROM films;
ERROR: internal error: relation "comedies" (105): column ID 2 found in depended-on-by references, no such column in this relation
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:693: ValidateSelf()
github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:80: func1()
github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:198: validateDescriptorsAtLevel()
github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:76: Validate()
github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:41: Self()
github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:539: AllocateIDs()
github.com/cockroachdb/cockroach/pkg/sql/create_view.go:706: addResultColumns()
github.com/cockroachdb/cockroach/pkg/sql/create_view.go:602: replaceViewDesc()
github.com/cockroachdb/cockroach/pkg/sql/create_view.go:199: 1()
github.com/cockroachdb/cockroach/pkg/sql/create_view.go:366: func1()
github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:414: runWithOptions()
github.com/cockroachdb/cockroach/pkg/sql/create_view.go:193: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:524: func2()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:112: func1()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:299: visitInternal()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:79: visit()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:43: walkPlan()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:527: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:172: Start()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183: Init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94: init()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103: Init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246: func1()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245: init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:285: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:309: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:866: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1843: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1579: func2()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1582: PlanAndRunAll()

HINT: You have encountered an unexpected error.
```

Jira issue: CRDB-25646

### PR DESCRIPTION
**Pull request by rharding6373**
Before this change, we could encounter internal errors while attempting to add result columns during a `CREATE OR REPLACE VIEW` if the number of columns in the new view was less than the number of columns in the old view. This led to an inconsistency with postgres, which would only return the error `cannot drop columns from view`.

This PR moves the check comparing the number of columns before and after the view replacement earlier so that the correct error returns.

Co-authored-by: sirek@cockroachlabs.com

Fixes: #99000
Epic: None

Release note (bug fix): Fixes an internal error that can occur when `CREATE OR REPLACE VIEW` replaces a view with fewer columns and another entity depended on the view.

### CODE REVIEW

**Comment by rharding6373** [comment]
Test failures appear to be flakes.

**Review by chengxiong-ruan — APPROVED** [review]
LGTM. Also curious where is the old check of this? I feel good about keeping them though. But still curious.

**Review by rharding6373 — COMMENTED** [review]
TFTR! The old check is in `verifyReplacingViewColumns` https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/create_view.go#L716

I left the check there for now in case the function gets reused in the future, since it's good to do bounds checking before the other work in the helper function.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99057#-:-NR3bTss5TJ--4EH8YeL:bip9nkb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by rharding6373** [comment]
TFTR! bors r+

**Pull request merged**
