### PR TITLE
opt: Use datadriven test to test JSON operators

### PR DESCRIPTION
**Pull request by andy-kimball**
Convert to use datadriven test for JSON operators, now that they're
supported in optbuilder.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24675#-:-L9pDTZN5QwsYlqVxcfZ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24675#-:-L9pFKBM0mPMKdGghcIV:bnfp4nl)*

**Comment by justinj** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24675#-:-L9pFpLpCuKwWmWwCPNP:bnfp4nl)*

**Pull request merged**
