### PR TITLE
server: Add HotRanges status endpoint

### PR DESCRIPTION
**Pull request by a-robinson**
Release note (admin ui change): Added a debug endpoint listing the
hottest ranges by QPS on each node/store.

---

This doesn't provide any UX around it, and note that the values being served are cached and only recalculated every minute, but this is all it takes to implement something that cheaply lists the hottest N (where N=128) ranges on each store.

cc @rolandcrosby @vilterp @rkruze

### CODE REVIEW

**Review by tbg — APPROVED** [review]
This seems useful. I don't trust the QPS numbers so it'll be nice to be able to see them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33336#-:-LUp3wZf3GL2m3M52Xgx:bviofsc)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/serverpb/status.proto, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33336#-LUp3i0RAZ3A05tUrG1M:-LUp3i0RAZ3A05tUrG1N:bjgrgqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ef7abf32784b8e837d18d10173ef083010ad45/pkg/server/serverpb/status.proto#L805)):*
> ```protobuf
>     };
>   }
> ```

Spurious?

**Review by a-robinson — COMMENTED** [review]
Ditto on not trusting the QPS numbers (cc https://github.com/cockroachdb/cockroach/issues/31147)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33336#-:-LUpxzpGBWvUbgcSIRNQ:bjl8hlg)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/serverpb/status.proto, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33336#-LUp3i0RAZ3A05tUrG1M:-LUpxqdu3A-5GXnbM5aR:b-ehz4d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/98ef7abf32784b8e837d18d10173ef083010ad45/pkg/server/serverpb/status.proto#L805)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Spurious?
</blockquote></details>

There didn't seem to be any reason for the newline there.

**Comment by a-robinson** [comment]
bors r+

TestRemoteDebugModeSetting flake

**Pull request merged**
