### PR TITLE
opt: expand set expression and Max1Row FD sets

### LINKED ISSUE #61795: opt: internal error: ordering column group contains non-equivalent columns (op distinct-on)
I ran sqlsmith for 5 minutes to test some changes to the random table generator, and ran into the error below. I'll work on minimizing the reproduction of this to make it easier to debug.

```
expected success, but found
                (XX000) internal error: ordering column group (4,8,11) contains non-equivalent columns (op distinct-on)
                ordering.go:361: in checkRequired()
                DETAIL: stack trace:
                github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/ordering.go:361: checkRequired()
                github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/ordering.go:43: BuildChildRequired()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/physical_props.go:80: BuildChildPhysicalProps()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:503: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:251: optimizeExpr()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:506: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:251: optimizeExpr()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:506: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:639: optimizeEnforcer()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:582: enforceProps()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:491: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:251: optimizeExpr()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:506: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:251: optimizeExpr()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:506: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:639: optimizeEnforcer()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:582: enforceProps()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:491: optimizeGroupMember()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:451: optimizeGroup()
                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:225: Optimize()
                github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:512: buildExecMemo()
                github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:194: makeOptimizerPlan()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:933: makeExecPlan()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:814: dispatchToExecutionEngine()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:652: execStmtInOpenState()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:120: execStmt()
```

** To reproduce **

```
statement ok
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;
SET CLUSTER SETTING sql.defaults.interleaved_tables.enabled = true;

statement ok
CREATE TABLE table1 (
  col1_0 TIMESTAMP NOT NULL,
  col1_1 BYTES,
  col1_2 "char",
  col1_3 REGTYPE NOT NULL,
  col1_4 UUID NOT NULL,
  col1_5 INT8 NOT NULL,
  col1_6 STRING NOT NULL,
  col1_7 BOOL NOT NULL,
  col1_8 TIMETZ NOT NULL,
  PRIMARY KEY (col1_4 DESC, col1_7, col1_6 ASC, col1_5),
  col1_9 STRING NULL AS (lower(CAST(col1_3 AS STRING))) STORED,
  UNIQUE (col1_7, col1_9 ASC, col1_0, col1_6, col1_5, col1_3 DESC) WHERE (((((((table1.col1_9 < '':::STRING) OR (table1.col1_8 = '24:00:00-15:59:00':::TIMETZ)) AND (table1.col1_2 = '"':::STRING)) OR table1.col1_7) OR (table1.col1_1 = '\x00':::BYTES)) OR (table1.col1_5 >= (-9223372036854775807):::INT8)) AND (table1.col1_6 <= '"':::STRING)) OR (table1.col1_0 = '-4713-11-24 00:00:00':::TIMESTAMP),
  UNIQUE (col1_0 DESC, col1_1 DESC, col1_3) WHERE table1.col1_9 > '"':::STRING,
  INDEX (col1_9 DESC, col1_8 ASC, col1_5 DESC) STORING (col1_2, col1_3),
  UNIQUE (col1_4 ASC) WHERE (table1.col1_0 = '294276-12-31 23:59:59.999999':::TIMESTAMP) AND (table1.col1_8 <= '24:00:00-15:59:00':::TIMETZ),
  FAMILY (col1_9),
  FAMILY (col1_1, col1_5),
  FAMILY (col1_7, col1_8, col1_6),
  FAMILY (col1_4, col1_2, col1_3),
  FAMILY (col1_0),
  UNIQUE (col1_2)
);

statement ok
CREATE TABLE table2 (
  col2_0 DECIMAL NOT NULL,
  col2_1 VARCHAR NOT NULL,
  col2_2 NAME NOT NULL,
  col2_3 NAME NOT NULL,
  col2_4 STRING NOT NULL,
  col2_5 REGNAMESPACE NOT NULL,
  PRIMARY KEY (col2_2, col2_4 DESC, col2_3 DESC, col2_1 DESC, col2_0, col2_5),
  col2_6 STRING NOT NULL AS (lower(col2_4)) STORED,
  col2_7 STRING NOT NULL AS (lower(col2_4)) VIRTUAL,
  col2_8 STRING NOT NULL AS (lower(col2_2)) STORED,
  INDEX (col2_2 ASC, col2_8 DESC, col2_4, col2_5 ASC, col2_7 DESC, col2_6 ASC, col2_0 DESC, col2_1),
  INDEX (col2_6) STORING (col2_8) WHERE table2.col2_6 < e'\U00002603':::STRING,
  FAMILY (col2_8, col2_6, col2_5),
  FAMILY (col2_2),
  FAMILY (col2_3),
  FAMILY (col2_4),
  FAMILY (col2_1),
  FAMILY (col2_0)
);

statement ok
ALTER TABLE table2 ADD FOREIGN KEY (col2_1) REFERENCES table1 (col1_2) ON DELETE RESTRICT ON UPDATE RESTRICT;

statement ok
WITH
  with_119586 (col_690441) AS (SELECT * FROM (VALUES ((-1013698117950504423):::INT8)) AS tab_292661 (col_690441))
SELECT
  tab_292662.col1_2 AS col_690442,
  tab_292662.col1_0 AS col_690443,
  tab_292662.col1_2 AS col_690444,
  tab_292662.col1_2 AS col_690445,
  1015127876:::OID AS col_690446,
  NULL AS col_690447
FROM
  table1@table1_col1_2_key AS tab_292662
  JOIN table2 AS tab_292663
  JOIN table1 AS tab_292664 ON (tab_292663.col2_2) = (tab_292664.col1_2) ON
    (tab_292662.col1_6) = (tab_292664.col1_2)
    AND (tab_292662.col1_9) = (tab_292663.col2_2)
    AND (tab_292662.col1_2) = (tab_292663.col2_2)
    AND (tab_292662.col1_9) = (tab_292664.col1_2)
    AND (tab_292662.col1_6) = (tab_292663.col2_2)
    AND (tab_292662.col1_2) = (tab_292664.col1_2)
WHERE
  (tab_292662.col1_7 OR (tab_292664.col1_2 NOT LIKE tab_292664.col1_2))
ORDER BY
  tab_292662.col1_2 ASC, tab_292662.crdb_internal_mvcc_timestamp ASC, tab_292662.col1_5 DESC
LIMIT
  72:::INT8
```

### PR DESCRIPTION
**Pull request by mgartner**
This commit makes two FD-related changes to satisfy the
`ordering.checkRequired` test-build assertion for UnionAll expressions
built by the SplitDisjunction exploration rule. This assertion requires
that columns in an ordering column group are known to be equivalent via
the expression's FDs. These two changes allow equivalence dependencies
to propagate to a UnionAll expression based on the FDs of its inputs.

  1. FDs for set expressions have been expanded to include known
     equivalencies. For the set expressions Union, UnionAll, and
     LocalityOptimizedSearch the output columns at ordinals `i` and `j`
     are equivalent if both the left and right input columns at ordinals
     `i` and `j` are also equivalent. For Intersect, IntersectAll,
     Except and ExceptAll, the output columns at ordinals `i` and `j`
     are equivalent if the left input columns at ordinals `i` and `j`
     are equivalent, because Except and ExceptAll only produce rows from
     the left input.

  2. Previously, `FuncDepSet.MakeMax1Row` removed existing equivalence
     dependencies from an FD set. This function now retains equivalence
     dependencies so that this information is not lost.

Fixes #61795

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Nice improvement!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-:-MVr71bf5n_lvW8UHg68:b-6f8vr5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqxzWDBppeeShkQzfV:-MVqxzWDBppeeShkQzfW:b-ul2ljn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/logical_props_builder.go#L723)):*
> ```Go
> 	}
> 	switch setNode.Op() {
> 	case opt.UnionOp, opt.UnionAllOp, opt.IntersectOp, opt.IntersectAllOp:
> ```

can you add `LocalityOptimizedSearchOp` here?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqy6Wg1BazYitLjkf7:-MVqy6Wg1BazYitLjkf8:b1b12vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/logical_props_builder.go#L735)):*
> ```Go
> 			}
> 		}
> 	case opt.ExceptOp, opt.ExceptAllOp:
> ```

Can't you move the intersect ops here too? They also only output rows from the left side.
___
*[pkg/sql/opt/memo/testdata/logprops/set, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqzAkM-K-exIwc1_ZY:-MVqzAkN9MRcbo_tONb5:bfofae5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/testdata/logprops/set#L455)):*
> ```
> 
> # Except FDs include equivalencies for columns that have equivalencies in the
> # left input.
> ```

can you add a test for intersect too?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqxzWDBppeeShkQzfV:-MVscHKbEX4mT98YxiuK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/logical_props_builder.go#L723)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add `LocalityOptimizedSearchOp` here?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqy6Wg1BazYitLjkf7:-MVsc1Q-BFWwI3vdK7MG:bahi3b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/logical_props_builder.go#L735)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can't you move the intersect ops here too? They also only output rows from the left side.
</blockquote></details>

Great point. Can't believe I messed that up. Done.
___
*[pkg/sql/opt/memo/testdata/logprops/set, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVqzAkM-K-exIwc1_ZY:-MVscnMD7sWOBtLsQfZZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a111a4e1dac15249eb05df26a1175861c59f7912/pkg/sql/opt/memo/testdata/logprops/set#L455)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add a test for intersect too?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-:-MVslAax075q3FEIIoSz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVskv9dBM_ZrDL1_FV-:-MVskv9dBM_ZrDL1_FV0:biwvec9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/memo/logical_props_builder.go#L736)):*
> ```Go
> 		}
> 	case opt.IntersectOp, opt.IntersectAllOp, opt.ExceptOp, opt.ExceptAllOp:
> 		// Intersect, IntersectALl, Except and ExceptAll only output rows from
> ```

[nit] IntersectALl -> IntersectAll

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 738 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVvkR6H3R9KIyBJRTT7:-MVvkR6H3R9KIyBJRTT8:bk001qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/memo/logical_props_builder.go#L738)):*
> ```Go
> 		// Intersect, IntersectALl, Except and ExceptAll only output rows from
> 		// the left input, so if columns at ordinals (i, j) are equivalent in
> 		// the left input, then they are equivalent in the output.
> ```

Isn't the *entire* FD information from the left side valid? (we may need column ID remapping functionality; maybe just add a TODO for now).

For Intersect, we would want to combine the FD information from both sides.
___
*[pkg/sql/opt/props/func_dep.go, line 781 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVvmR8t0umMpXL8P0Za:-MVvmR8t0umMpXL8P0Zb:b27od5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/props/func_dep.go#L781)):*
> ```Go
> 	for i := range f.deps {
> 		fd := &f.deps[i]
> 		if fd.equiv && fd.to.SubsetOf(cols) && fd.from.SubsetOf(cols) {
> ```

This should be `fd.to.Intersects()` and then we would update the dep to use the `Intersection()`. Otherwise, an extra equivalency information can make the end-result worse. Note that `fd.from` is a single column if `equiv` is true.

We should add some unit tests in func_dep_test.go.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVskv9dBM_ZrDL1_FV-:-MVw1XNp8tNPCAecKf1J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/memo/logical_props_builder.go#L736)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] IntersectALl -> IntersectAll
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 738 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVvkR6H3R9KIyBJRTT7:-MVwAA8LBDzwpiU2zJf5:bedirtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/memo/logical_props_builder.go#L738)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Isn't the *entire* FD information from the left side valid? (we may need column ID remapping functionality; maybe just add a TODO for now).

For Intersect, we would want to combine the FD information from both sides.
</blockquote></details>

Ahh, you're right. I think we could get away without remapping because we build INSERSECT and EXCEPT expressions with the same left and output column IDs, but it may be brittle. I've left a TODO for now and I'll follow up with a PR (probably one that I won't try to backport to 21.1).
___
*[pkg/sql/opt/props/func_dep.go, line 781 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-MVvmR8t0umMpXL8P0Za:-MVw9q8aEvatZhemYdJk:bllaydm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f91bd55e81a7be712740c728134585499a35e7/pkg/sql/opt/props/func_dep.go#L781)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be `fd.to.Intersects()` and then we would update the dep to use the `Intersection()`. Otherwise, an extra equivalency information can make the end-result worse. Note that `fd.from` is a single column if `equiv` is true.

We should add some unit tests in func_dep_test.go.
</blockquote></details>

Great catch! Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61941#-:-MVwdKdlDeHR4nNZocVE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
