### PR TITLE
[DNM] Demonstrate DistSQL MaxOffset correctness problem

### PR DESCRIPTION
**Pull request by tbg**
NB: This PR is a mess as it includes ongoing experiments that I'm running
for a different issue. This PR is just something I ran into and wanted to
document as it requires resolution.

In this WIP, we run a workload in which there are multiple concurrent
operations. Each of those is either a fast non-conflicting write, or a
sequence of two reads, the first grabbing just one row, and the second
sleeping for a short time and then touching everything.

The table here is very small (due to the short duration of the test) and
there is no manual transaction management.

The only statement that can't be auto-retried at the gateway is the second
read, and the only error that read expects is a
ReadWithinUncertaintyIntervalError.

When we “visit” a node and make a note of its timestamp, we aren’t actually
guaranteed that we won’t see RWUs for a future read. Say a txn starts with
Orig=1, Max=10 and then reads some insignificant key at node1 at 5. So the
next time we visit node1 again for a full range scan. Now in that range,
there are various values at timestamps between 1 and 5 that we didn’t see
before, and all of those are going to trigger RWUs, since they’re in the
window `[OrigTimestamp, 5)`. So TL;DR: we expect to see RWUs in this
workload.

This experiment shows that when distsql=off (or auto), we get these errors (in
~10% of ops, and remember that only 50% of ops are even reads that can get this
error, so it's really one out of five reads that fails that way -- pretty
frequent).

However, with distsql=on (which will force the first read through DistSQL; the
second one is always using DistSQL when not disabled), they vanish (with rare
exceptions).

This exposes a problem in the DistSQL execution path that has been pointed out
by @andreimatei before: we try to mark the "local node" as "super certain" (i.e.
`MaxTiemstamp = OrigTimestamp`) eagerly to optimize for this case, but with
DistSQL execution, the node that code runs on isn't necessary local (it's the
one being planned on). So when we force the first (small) select through
DistSQL, it'll schedule it on the lease holder, and the lease holder will mark
that node as certain (even though it's not, at least not for
`txn.OrigTimestamp`; it would be safe with a timestamp off that node's clock).
This means that when the "big" select query comes in, it will never see RWUs as
`MaxTimestamp == OrigTimestamp`.

It's a bit unfortunate that we didn't address this known problem earlier (since
it's a correctness problem), and we should fix it now.

Assigning to @andreimatei for discussion. We definitely have to move that
code elsewhere, is the suggestion in your comment still appropriate?

### CODE REVIEW

**Comment by andreimatei** [comment]
@tschottdorf, where is the `MaxTimestamp = OrigTimestamp` optimization done?
@spencerkimball is working on discriminating more between the `client.Txn` objects used by the gateway versus the ones used by DistSQL processors running on remote nodes. I'm hoping this will make it trivial to inhibit the optimization when it shouldn't apply.

**Comment by tschottdorf** [comment]
`dist_sender.go`:

```go
		if len(ba.Txn.ObservedTimestamps) == 0 {
			// Ensure the local NodeID is marked as free from clock offset;
			// the transaction's timestamp was taken off the local clock.
			// TODO(andrei): This is broken when Txn.OrigTimestamp has not been, in
			// fact, taken off this node's clock. This happens when the transaction
			// was created remotely and is being run through the ExternalClient. I
			// think we shold move this initialization to client.Txn.
			if nDesc := ds.getNodeDescriptor(); nDesc != nil {
				// TODO(tschottdorf): future refactoring should move this to txn
				// creation in TxnCoordSender, which is currently unaware of the
				// NodeID (and wraps *DistSender through client.Sender since it
				// also needs test compatibility with *LocalSender).
				//
				// Taking care below to not modify any memory referenced from
				// our BatchRequest which may be shared with others.
				//
				// We already have a clone of our txn (see above), so we can
				// modify it freely.

				// OrigTimestamp is the HLC timestamp at which the Txn started, so
				// this effectively means no more uncertainty on this node.
				ba.Txn.UpdateObservedTimestamp(nDesc.NodeID, ba.Txn.OrigTimestamp)
			}
		}
```

**Comment by tschottdorf** [comment]
@andreimatei I've lost track of the PRs that affected this path. Is this still an issue?

**Comment by andreimatei** [comment]
Probably. Spencer was talking to me earlier about it; he said he'll lift the setting of the gateway observed timestamp out of the DistSender.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21266#-:-L5t2tP6j2K37kmvPXID:b9pfafi)*

**Pull request closed without merging**
