### PR TITLE
sql: use catalog.TableDescriptor instead of tabledesc.Immutable

### LINKED ISSUE #59486: sql: use catalog.TableDescriptor instead of tabledesc.Immutable
This is a child of #56306. Should be self-explanatory.

### PR DESCRIPTION
**Pull request by postamar**
This PR makes the tabledesc.Immutable type private and makes use of the
catalog.TableDescriptor interface instead.

Fixes #59486.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
opt_catalog and opt_exec_factory changes LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-:-MS5E6n445eYEsWao8FX:bu8tuy0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by postamar** [comment]
@ajwerner @lucy-zhang I realize that with this change, `Collection`'s immutable getters return `dbdesc.Immutable` `schemadesc.Immutable` `typedesc.Immutable` but for tables it's now `catalog.TableDescriptor`. Breaking this pattern is the price to pay for making `tabledesc.Immutable` private -- which it doesn't have to be, but it's kinda neat.

**Review by thoszhang — COMMENTED** [review]
LGTM, just a few minor comments.

> Reviewed 1 of 1 files at r1, 117 of 117 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 6 of 6 files at r6, 3 of 3 files at r7, 5 of 5 files at r8, 119 of 119 files at r9, 10 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-:-MSG-5YU15Nbny_MQmSi:b-wtxtfj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @postamar)

___
*[pkg/sql/drop_sequence.go, line 180 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-MSFqYJ260cU5iadeJaB:-MSFqYJ260cU5iadeJaC:ba7hva8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4a56c1c127c7764b9873dbe34fa1a10fca473b3/pkg/sql/drop_sequence.go#L180)):*
> ```
> 		affectsNoColumns := true
> 		canBeSafelyRemoved := false
> ```

I think these could benefit from some documentation comments on what they mean. Using the iterator makes the logic less obvious.
___
*[pkg/sql/catalog/descriptor.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-MSFvE7R5bOuQNgY1XtM:-MSFuZAZ2XMtumSGl0MF:b2uberk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6149b951c938f6a3693b4a2aed9e5b16ef2384b/pkg/sql/catalog/descriptor.go#L248)):*
> ```Go
> 
> 	HasColumnBackfillMutation() bool
> 	MakeFirstMutationPublic(includeConstraints bool) (MutableDescriptor, error)
> ```

I suspect we should be able to convert all the callers of this function to just use `catalog.TableDescriptor`. I don't think constraint validation needs to mutate these descriptors. #58906 should also help.

**Review by postamar — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-:-MSTNNCx0BQIeA0AdkYF:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @lucy-zhang)

___
*[pkg/sql/drop_sequence.go, line 180 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-MSFqYJ260cU5iadeJaB:-MSTN5030oSjcVdXrotp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4a56c1c127c7764b9873dbe34fa1a10fca473b3/pkg/sql/drop_sequence.go#L180)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> ```
> 		affectsNoColumns := true
> 		canBeSafelyRemoved := false
> ```

I think these could benefit from some documentation comments on what they mean. Using the iterator makes the logic less obvious.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descriptor.go, line 248 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59495#-MSFvE7R5bOuQNgY1XtM:-MSTNBXHB1Cv5gK1j3iG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6149b951c938f6a3693b4a2aed9e5b16ef2384b/pkg/sql/catalog/descriptor.go#L248)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I suspect we should be able to convert all the callers of this function to just use `catalog.TableDescriptor`. I don't think constraint validation needs to mutate these descriptors. #58906 should also help.
</blockquote></details>

Done.

**Comment by postamar** [comment]
Rebased on master to resolve conflict, and edited the commit message for the `MakeFirstMutationPublic` commit, which I'd forgotten to do.

**Comment by postamar** [comment]
Rebased again to fix a few more conflicts.

**Comment by postamar** [comment]
Sorry for the noise, just silly build failures due to having had to rebase.

**Pull request merged**
