### PR TITLE
release-23.1: server: make the span stats fan-out more fault tolerant

### LINKED ISSUE #106097: sql: `SHOW RANGES` does not work with offline node
This works in 23.1 but not on `master`. To reproduce:

```
roachprod create local -n 3
roachprod start local
cockroach workload init kv --splits 1000
roachprod sql local:1

> show ranges from database kv with details;

roachprod stop local:3

> show ranges from database kv with details;
ERROR: failed to dial into node 3 (NODE_STATUS_UNAVAILABLE): initial connection heartbeat failed: grpc: connection error: desc = "transport: error while dialing: dial tcp 10.166.0.3:26261: connect: connection refused" [code 14/Unavailable]
```

Jira issue: CRDB-29397

### PR DESCRIPTION
**Pull request by zachlite**
Backport 1/1 commits from #108456 

-------

This commit adds improved fault tolerance to the span stats fan-out:

1. Errors encountered during the fan-out will not invalidate the entire request. Now, a span stats fan-out will always return a roachpb.SpanStatsResponse that has been updated by values from nodes that service their requests without error. In the extreme case where there's a failure encountered on every node, an empty response is returned.

Errors that are encountered are logged, and then appended to the response in the newly added `Errors` field.

2. Nodes must service requests within the timeout passed to `iterateNodes`. For span stats, the value comes from a new cluster setting: 'server.span_stats.node.timeout', with a default value of 1 minute.

Resolves #106097
Epic: none
Release note (ops change): Span stats requests will return a partial result if the request encounters any errors. Errors that would have previously terminated the request are now included in the response.

-------
Release justification: low risk fault tolerance improvements

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
since this is a backport it needs to have that on the title, so `# release-23.1: server: make...` and then you need to add `Release justification:` to the PR description

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109008#-:-Nc8LUkR22TMWxiYRRYv:b-j2rlok)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @zachlite)

___
*[`pkg/server/status.go` line 2851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109008#-Nc8QnU63XYI0o9m9X0s:-Nc8QnU63XYI0o9m9X0t:b-5iii08) ([raw file](https://github.com/cockroachdb/cockroach/blob/f137ca2c794ca92c9cbd2ab1cf78c398619b10d5/pkg/server/status.go#L2851)):*
> ```Go
> }
> 
> const noTimeout time.Duration = 0
> ```

on master this const is created on the file pagination.go, this file doesn't exist on this branch?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[`pkg/server/status.go` line 2851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109008#-Nc8QnU63XYI0o9m9X0s:-Nc8RpDK19pa8t-6Ziim:b-ly1xix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f137ca2c794ca92c9cbd2ab1cf78c398619b10d5/pkg/server/status.go#L2851)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

on master this const is created on the file pagination.go, this file doesn't exist on this branch?
</blockquote></details>

I'm working on a separate backport for https://github.com/cockroachdb/cockroach/pull/107796.
We can wait and rebase this PR on top of that upcoming backport.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109008)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @zachlite)

___
*[`pkg/server/status.go` line 2851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109008#-Nc8QnU63XYI0o9m9X0s:-Nc8SR7R0CxGUPIg-B2B:btxbmb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f137ca2c794ca92c9cbd2ab1cf78c398619b10d5/pkg/server/status.go#L2851)):*
<details><summary><i>Previously, zachlite wrote…</i></summary><blockquote>

I'm working on a separate backport for https://github.com/cockroachdb/cockroach/pull/107796.
We can wait and rebase this PR on top of that upcoming backport.
</blockquote></details>

Sounds better! Let's get that one if first! thank you

**Review by maryliag — APPROVED** [review]
Nice!
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109008#-:-NcNWlx1Dn7iSNxgECBO:bkjg46h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
