### PR TITLE
sql: propagate row-level locking modes through execbuilder to row.Fetcher

### PR DESCRIPTION
**Pull request by nvb**
Relates to #40205.

This commit is a follow-up to #44015. It propagates the row-level locking modes
from the optbuilder all the way down to the row.Fetcher. This requires passing
the locking information through the execbuilder and then through DistSQL. The
commit leaves off at the point where `roachpb.ScanRequest`s are constructed.

I couldn't find a good way to test this. It's possible I missed something and
would love any tips, but I think we may need to wait until the plumbing into
the KV API is complete before performing end-to-end tests.

The next step will be to hook the locking modes into the KV API.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I took a quick glance, and I see that we're modifying existing processor protos. I think we might need to bump `DistSQLVersion` so that there was no problem in a mixed-version cluster scenario.

**Review by rohany — COMMENTED** [review]
Overall PR LGTM besides yahor's comment. I agree, its unclear how to test this until the lock strength actually does something (it's basically a noop at the kvfetcher layer)

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44429#-:-LzeUnng3hQ3kO6v-XId:b-9a5pp6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/sqlbase/locking.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44429#-LzeUbtb6lQwmBbzeOG4:-LzeUbtb6lQwmBbzeOG5:b-eir8hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb2a05239041f9dc819835744233086bcf2b5470/pkg/sql/sqlbase/locking.go#L21)):*
> ```Go
> // ToScanLockingStrength converts a tree.LockingStrength to its corresponding
> // ScanLockingStrength.
> func ToScanLockingStrength(s tree.LockingStrength) ScanLockingStrength {
> ```

Why do we need a locking strength defined in sqlbase and tree?

**Review by nvb — COMMENTED** [review]
TFTRs! I added one more commit to disable distributing `TableReaders` that intend to perform row-level locking.

> I think we might need to bump DistSQLVersion so that there was no problem in a mixed-version cluster scenario.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44429#-:-LzhoD1pEeSkDxZAOS84:b1z4scn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/sqlbase/locking.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44429#-LzeUbtb6lQwmBbzeOG4:-LzhoEUA3GAHRgXL3Sab:bmmfzhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb2a05239041f9dc819835744233086bcf2b5470/pkg/sql/sqlbase/locking.go#L21)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Why do we need a locking strength defined in sqlbase and tree?
</blockquote></details>

We need it in `tree` because the variants correspond to AST nodes. `sqlbase` has a dependency on `tree`, so we can't have `tree` reference this enum without creating a dependency cycle. We need it in `sqlbase` because we need to send these over the wire in processor specs, so they need to be protobuf enums. I'm open to a better way to do this, but I couldn't find one.

**Pull request merged**
