### PR TITLE
server: capture info about hardware and OS in diagnostics

### PR DESCRIPTION
**Pull request by dt**
Information about cores and memory commonly used to run Cockroach can help us size caches, tune recommendations, etc.

First draft of what we discussed. Will need to think about testing a bit though.

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
For testing, we'll just have to make sure that there are values present and not default ones for everything except for the virtualization stuff I think.  Just make sure it runs properly on TC and we can get a linux user to test on their machine too.

The proto needs a wee bit of cleanup, and we should take a look at the cloud stuff in another PR.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28676#-:-LK274840_avscaVwcVe:bp4tfj1)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by dt** [comment]
as discussed, moved virtualization to `Hardware` since it can mess with the detected hardware numbers (e.g. seeing 4 x 1core cpus inside my docker builder session), added a few sanity-check level tests, and think this is RFAL.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28676#-:-LK3-bll4uqa0l0nhALW:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by vilterp** [comment]
Ben noted on a different PR that the CPU info returned by gopsutil is wonky: https://github.com/cockroachdb/cockroach/pull/27662#pullrequestreview-138088290

So we should use caution while interpreting those numbers, or find another library for CPU info (I don't know of one offhand). I think `runtime.NumCPU()` is an accurate measure of what we really care about though, which is how many goroutines can we run at once.

**Comment by dt** [comment]
@vilterp yep, we have `numcpu` in there first. the other stuff may or may not be interesting, but I'm inclined to trust numcpu over the sockets/cores numbers given my observations and what ben said there.

**Pull request merged**
