### PR TITLE
opt: nil presentation should not equal the 0-column presentation

### LINKED ISSUE #39435: sql: internal error: cannot map variable 13 to an indexed var
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g % 2 = 0 AS _bool, g::STRING AS _bytes
	FROM
		generate_series(0, 0) AS g;

SELECT
	NULL
FROM
	tab_orig AS tab_22780
WHERE
	NOT
		(
			EXISTS(
				SELECT
					(
						SELECT
							NULL
						FROM
							tab_orig
							INNER JOIN tab_orig AS tab_22784 ON tab_22780._bool
						LIMIT
							1
					)
				FROM
					tab_orig AS tab_22781 RIGHT JOIN tab_orig ON true
				WHERE
					true AND '' IN (tab_22781._bytes,)
			)
			AND true
		);
```

```
pq: internal error: cannot map variable 13 to an indexed var
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:149: indexedVar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:134: buildVariable()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:91: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:163: buildTuple()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:91: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:229: buildComparison()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:91: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:212: buildBoolean()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:91: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:181: buildBoolean()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:91: buildScalar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:491: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:192: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1140: buildOrdinality()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:219: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:780: initJoinBuild()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:715: buildHashJoin()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:299: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:528: buildProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:195: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:117: build()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:105: Build()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:267: Next()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171: Next()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:581: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:333: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:942: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:910: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417: execStmtInOpenState()
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: enhance apply execbuilder error

We have seen a series of bugs where the execbuilder hits an assertion
error inside Apply. This change adds a detail to the error containing
the formatted opt tree.

Release note: None

#### opt: nil presentation should not equal the 0-column presentation

The nil presentation means that we want all columns in no particular
order, whereas the 0-column presentation means that we don't need any
of the columns (e.g. EXISTS subqueries). Only the nil presentation
is `Any()`. But `Equals()` was incorrectly treating these as equal.
This confused the interner and a nil presentation became a 0-column
presentation which led to some internal errors in Apply.

For completeness, we also fix `HashPhysProps` to differentiate
between these two, but note that this isn't required for correctness.

Fixes #39435.

Release note (bug fix): Fixed internal errors generated during
execution of some complicated cases of correlated subqueries.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39818#-:-Lmte30T5qSLqu-7HDg_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/interner.go, line 525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39818#-LmtbsvL5FBOM-xYVxXM:-LmtbsvL5FBOM-xYVxXN:b-pt1mdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d0ba976b4923a79b06232f5e8ca4f5c8616c4db/pkg/sql/opt/memo/interner.go#L525)):*
> ```Go
> 
> func (h *hasher) HashPhysProps(val *physical.Required) {
> 	// Note: the Any presentation is not the same with the 0-column presentation.
> ```

nit: "is not the same *as*"?
___
*[pkg/sql/opt/props/physical/required.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39818#-Lmtdph85CPbyOLT5-8I:-Lmtdph85CPbyOLT5-8J:b-scpvow) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d0ba976b4923a79b06232f5e8ca4f5c8616c4db/pkg/sql/opt/props/physical/required.go#L118)):*
> ```Go
> // presentation.
> func (p Presentation) Equals(rhs Presentation) bool {
> 	// The 0 column presentation is not the same with the nil presentation.
> ```

nit: same as? or "is not equal to"

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39818)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/interner.go, line 525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39818#-LmtbsvL5FBOM-xYVxXM:-Lmtg1PyDH6bf_ry18bq:b3dk9jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d0ba976b4923a79b06232f5e8ca4f5c8616c4db/pkg/sql/opt/memo/interner.go#L525)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: "is not the same *as*"?
</blockquote></details>

In Soviet Russia, English learns you!

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39818#-:-LmtkJ9vEw3K6dwX0j75:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj)

**Pull request merged**
