### PR TITLE
kv: fix request wedging on network partitions

### LINKED ISSUE #13541: CockroachDB stoped serving requests when a leader got separated from the rest of the nodes
Is this a question, feature request, or bug report? It's a bug.

Hi folks,

I was testing a 3-nodes deployment of a CockroachDB cluster and observed a situation when CockroachDB stoped serving requests when a leader got separated from the rest of the nodes.

The version of the CockroachDB is

<pre>
Build Tag:    beta-20170209
Build Time:   2017/02/09 16:11:47
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.7.5
C Compiler:   gcc 4.9.3
Build SHA-1:  3271ce4097dcb2d7ad74b877b011dd6ee62f04d5
Build Type:   release</pre>

During the run `cockroach start` I specified the following flags: `port`, `http-port`, `insecure`, `host`, `store` and `join`.

The client app opened a connection to each of the nodes and was continiously running the following loop per each of them:

1. read a value by a key
2. if the wasn't set then set it to 0
3. increment the value
4. write it back
5. increment a number of successful iterations
6. repeat the loop

Each connection used its own key to avoid collision. If there was an error during the loop then it closed the current connection, opened a new one and began the next iteration.

Once in a second it dumped aggregated number of successful iterations per cluster and per each node for a last second.

When I separated a leader (10.0.0.6) from the peers with the following command:

`sudo iptables -A INPUT -s 10.0.0.4 -j DROP; sudo iptables -A INPUT -s 10.0.0.5 -j DROP`

the cluster became unavailable for more than a minute (the rate of successful iterations dropped to zero), I tried to undo the effect of the partitioning with

`sudo iptables -D INPUT -s 10.0.0.4 -j DROP; sudo iptables -D INPUT -s 10.0.0.5 -j DROP`

but it didn't help and the system remained unavailable. Only when I explicitly killed the former leader the other nodes elected a new one and started serving the requests.

Please see this repo for the client's code: https://github.com/rystsov/perseus-cockroach

### PR DESCRIPTION
**Pull request by tamird**
Needs tests, and I intend to squash the last 3 commits.

(will close https://github.com/cockroachdb/cockroach/issues/13541)

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13654)

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not sure about this approach. I was thinking we'd try to find a way to have the request to the partitioned node return with an error instead of hanging indefinitely, perhaps using node liveness or the RPC connection heartbeats.

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 1218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdChl2pceQklqcz_q2s:-KdChl2pceQklqcz_q2t:b-apvwhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/313bdc345a1e73f55b1d720deec5800182fcd27f/pkg/kv/dist_sender.go#L1218)):*
> ```Go
> 							}
> 							log.Infof(ctx, "l.Expiration=%s", l.Expiration.GoTime())
> 							defer time.AfterFunc(l.Expiration.GoTime().Sub(now.GoTime()), func() {
> ```

This won't do anything for epoch-based leases, which will be the majority soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-:-KdCi_w9FVfwT8VuFJuO:b-kw7jgn)*

**Comment by tamird** [comment]
> I was thinking we'd try to find a way to have the request to the partitioned node return with an error instead of hanging indefinitely, perhaps using node liveness or the RPC connection heartbeats.

Took a look at doing this with node liveness, and the short answer is that it's a fair amount of surgery, since node liveness isn't plumbed to the dist sender currently.

I'm looking at using rpc heartbeats, while avoiding a revert of https://github.com/cockroachdb/cockroach/commit/f74137a33251e1a42b3becd1c2cc73b8335dd007.

**Comment by petermattis** [comment]
> I'm looking at using rpc heartbeats, while avoiding a revert of f74137a.

Can we cancel the RPCs without closing the connection? Do you recall why closing the connection was problematic?

**Comment by tamird** [comment]
On Fri, Feb 17, 2017 at 5:17 PM, Peter Mattis <notifications@github.com>
wrote:

> Can we cancel the RPCs without closing the connection?


Not in any way that I'm aware of.


> Do you recall why closing the connection was problematic?


I think it was just unnecessary - in many cases if we get an explicit
(fast) failure, it is likely that this failure will also be noticed by
other RPCs. At least, that's the comment I'm going with for now (still
wrangling tests).

It's also possible that it just made tests harder (many induce failure by
letting heartbeats time out, which now causes the connection to close
completely).

**Comment by tamird** [comment]
This is ready for another look. I'll remove the kv solution (which only works for non-epoch leases) and its revert after review.

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/rpc/context.go, line 308 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdXFB9UtisRBmlS-AMk:-KdXFB9UtisRBmlS-AMl:b-ojor99) ([raw file](https://github.com/cockroachdb/cockroach/blob/d622326908eadf646c2c7a1f7bdfaf3eb74efa03/pkg/rpc/context.go#L308)):*
> ```Go
> 	})
> 
> 	defer func() {
> ```

This is odd. Why is this being done via a defer? And why aren't you initializing `meta.err` to `errNotHeartbeated`. Doing this here seems to be racey with `runHeartbeat`. Perhaps there is a method to the madness. If so, it should be documented in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/context.go, line 308 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdXFB9UtisRBmlS-AMk:-KdXuRi5Z5KyCSYnXtPk:bky6wxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d622326908eadf646c2c7a1f7bdfaf3eb74efa03/pkg/rpc/context.go#L308)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is odd. Why is this being done via a defer? And why aren't you initializing `meta.err` to `errNotHeartbeated`. Doing this here seems to be racey with `runHeartbeat`. Perhaps there is a method to the madness. If so, it should be documented in a comment.
</blockquote></details>

This is using a separate member now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/context.go, line 107 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdY3pyNBuRBhoLS46vJ:-KdY3pyOsd50WRiQ5ZqY:b-vcx2tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af3dcadacbfef27d2ee7d22c64902bb6925d919/pkg/rpc/context.go#L107)):*
> ```Go
> 	sync.Once
> 	conn *grpc.ClientConn
> 	err  error
> ```

Should this field be renamed `dialErr`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-:-KdY4DZrd1tVoXB7bbJR:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

Remember to remove `[WIP]` from the PR title.

---

Reviewed 1 of 2 files at r5, 2 of 4 files at r8, 1 of 1 files at r14, 3 of 3 files at r15.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 1181 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdZ0rbqIr8sL3xGMkCf:-KdZ0rbqIr8sL3xGMkCg:b-5y2549) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af3dcadacbfef27d2ee7d22c64902bb6925d919/pkg/kv/dist_sender.go#L1181)):*
> ```Go
> 			err := call.Err
> 			if err == nil {
> 				switch tErr := call.Reply.Error.GetDetail().(type) {
> ```

FWIW, I think this was clearer with the separate method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-:-KdZ106DyKs4dfVMPuFE:b-sw0d4u)*

**Comment by tamird** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1218 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdChl2pceQklqcz_q2s:-KdaSHz2vlvmVdsPwVhL:b-49f5xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/313bdc345a1e73f55b1d720deec5800182fcd27f/pkg/kv/dist_sender.go#L1218)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This won't do anything for epoch-based leases, which will be the majority soon.
</blockquote></details>

This is gone.

---

*[pkg/kv/dist_sender.go, line 1181 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdZ0rbqIr8sL3xGMkCf:-KdaRbGzt4Z2Lvbi_idF:bgnutud) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4db3898558bc12c9dbfd436eed199c30741f10/pkg/kv/dist_sender.go#L1181)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

FWIW, I think this was clearer with the separate method.
</blockquote></details>

Really? I found that logic much harder to follow, and also found the "abstraction" to be an obstacle when I needed more access to the calling scope in an earlier iteration of this fix.

---

*[pkg/rpc/context.go, line 107 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654#-KdY3pyNBuRBhoLS46vJ:-KdaRxDYt6F9leXa43Ka:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4db3898558bc12c9dbfd436eed199c30741f10/pkg/rpc/context.go#L107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this field be renamed `dialErr`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13654)*

**Pull request merged**
