### PR TITLE
multitenant: make the tenant watcher watch more stuff

### PR DESCRIPTION
**Pull request by knz**
We don't want to watch just capability changes; we also want
to watch the service mode. (Also later we will want to watch the
name.)

This commit extends the logic accordingly.
Epic: CRDB-21836

### CODE REVIEW

**Comment by knz** [comment]
@arulajmani with this PR I'm realizing the watcher is not named properly - it deserves to have a more general name and serve more purposes.

Could you suggest to me:
- what would be a better name
- what would be a better package location
- whether what i've done here is going to work

**Review by arulajmani — COMMENTED** [review]
Haven't given this a detailed look, but I agree that we should re-evaluate the package structure around here, now that we're watching for more things. 

Do you think it makes sense to pull the `Watcher` up into the `multitenant` package? I would personally be okay still calling it a `Watcher` once we make the move.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95657#-:-NMUWxvr4flqFaZiq230:b-gksz0c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @msirek)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go` line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95657#-NMUdPM9EMsFEa_vfPzb:-NMUdPM9EMsFEa_vfPzc:b82bsur) ([raw file](https://github.com/cockroachdb/cockroach/blob/871bbb7b4d3575c495bcbafa36e97e40f87408dc/pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go#L93)):*
> ```Go
> // GetSharedServiceTenants retrieves the list of tenants with service
> // mode SHARED.
> func (w *Watcher) GetSharedServiceTenants() map[roachpb.TenantID]struct{} {
> ```

Should we define a new interface 

(strawman):

```
type ServiceModeStatus interface {
   GetSharedServiceTenants() map[roachpb.TenantID]struct{}
}
```

and have the `Watcher` implement it instead? 

(separately, does this function need to return a map or would a slice of tenant IDs work as well?

**Review by msirek — COMMENTED** [review]
Changes look good from a SQL Team perspective.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95657#-:-NMap7ctBzKz18Fh52hJ:b-xkuuby)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

**Comment by knz** [comment]
Superseded by #105441.

**Pull request closed without merging**
