### PR TITLE
server/license: use system.migrations to check if cluster is new or old

### PR DESCRIPTION
**Pull request by spilchen**
The grace period when no license is installed varies based on whether the cluster is new or existing. Older clusters receive a 30-day grace period, while new clusters only get 7 days. This logic was introduced in a previous commit, but it relied on state being passed down to the license enforcer, which was really only intended for debugging purposes.

This update changes that approach by allowing the enforcer to determine whether the cluster is new or old independently, using the minimum timestamp from system.migrations. If the enforcer's start time is within a 2-hour window of the earliest timestamp in system.migrations, the cluster is considered new.

This change will be backported to 23.1, 23.2, 24.1 and 24.2.

Epic: CRDB-39988
Informs: CRDB-39991
Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for getting to this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-:-O7-mSFn7JDBPpDFcDUf:b-901z3x)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen and @xinhaoz)

___
*[`pkg/server/license/enforcer.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-lmPXBOui70BvSTui:-O7-lmPXBOui70BvSTuj:b-vem3yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer.go#L212)):*
> ```Go
> 		// need to write a new timestamp. So, we optimize for the case where the
> 		// timestamp already exists.
> 		val, err := txn.KV().Get(ctx, keys.GracePeriodInitTimestamp)
> ```

should the key be renamed? it no longer stores the grace period init timestamp, right?

should the function be renamed too?
___
*[`pkg/server/license/enforcer.go` line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-jf5S2NlDuRSTCtfq:-O7-jf5S2NlDuRSTCtfr:b-1pwig3) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer.go#L515)):*
> ```Go
> 	// value for debugging purposes.
> 	data, err = txn.QueryRow(ctx, "fetch min completed_at", txn.KV(),
> 		"select completed_at from system.migrations WHERE internal = 99")
> ```

nit: why do we use internal=99 here, instead of a query like `SELECT min(completed_at) ...`? when i checked a fresh cluster, i didn't see any row with internal=99.

also, we could avoid needing to execute two queries if the earlier one that is at the top of the function queries for `min(completed_at)`; and instead of comparing that to the `startTime` in SQL, the comparison can be made in golang code using `ts.After(...)` and `ts.Before(...)`
___
*[`pkg/server/license/enforcer_test.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-mLZu8aGH9NHJXGSc:-O7-mLZu8aGH9NHJXGSd:b-oanjep) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer_test.go#L133)):*
> ```Go
> 			err := db.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
> 				_, err := txn.Exec(ctx, "add new min to system.migrations", txn.KV(),
> 					"INSERT INTO system.migrations VALUES (0, 0, 0, 99, $1)", tc.minSysMigrationTime)
> ```

same question here; where does this row with internal=99 come from?

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130867)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @xinhaoz)

___
*[`pkg/server/license/enforcer.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-lmPXBOui70BvSTui:-O73zPZHEIDCZ_2S83IX:b-7qoi34) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer.go#L212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should the key be renamed? it no longer stores the grace period init timestamp, right?

should the function be renamed too?
</blockquote></details>

Good point. Since it's now the timestamp of when the grace period ends, I have been calling it the grace period set during cluster initialization. Or shortened as `ClusterInitGracePeriondTimestamp`. I will rename the key, but I think the function name is okay still. What do you think?
___
*[`pkg/server/license/enforcer.go` line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-jf5S2NlDuRSTCtfq:-O73xkgFCmC-PFp-K9YU:btw4zhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer.go#L515)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: why do we use internal=99 here, instead of a query like `SELECT min(completed_at) ...`? when i checked a fresh cluster, i didn't see any row with internal=99.

also, we could avoid needing to execute two queries if the earlier one that is at the top of the function queries for `min(completed_at)`; and instead of comparing that to the `startTime` in SQL, the comparison can be made in golang code using `ts.After(...)` and `ts.Before(...)`
</blockquote></details>

Whoops. I added this to debug a failed test case. Then I convinced myself this is good debug code to have in general. But I forgot to remove the the special '99' internal version that the test adds. I like your suggestion about having a single query though. So, I will apply that to clean this up.
___
*[`pkg/server/license/enforcer_test.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-O7-mLZu8aGH9NHJXGSc:-O73y7Tm64v-nplfdR6m:becel3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/173e6401555edebc0eb96c7c2f4bb3f64a8dc1ba/pkg/server/license/enforcer_test.go#L133)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same question here; where does this row with internal=99 come from?
</blockquote></details>

It's just a random number the test adds. I going to change this to update an existing row instead of adding a new one. The test will now set the new min with: `UPDATE system.migrations SET completed_at=$1 LIMIT 1`

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130867#-:-O761zZ13mmtdYysaa-9:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by spilchen** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
