### PR TITLE
kvserver: mitigate unavailability due to backpressure when reducing range size

### LINKED ISSUE #46271: kv: lowering the range size can cause unavailability
**Describe the problem**

When a range (well, most ranges) get too large (2x the `range_max_bytes` as dictated by the zone config), we apply back pressure to writes and block them until a split occurs. In the normal course of business when a split is due to write traffic to the range, this is reasonable. We expect this situation to be quite rate. Once a range exceeds `range_max_bytes` by even a bit, we'd expect a split to happen soon. A common case where this backpressure can occur is when a range is unsplittable because all of its data is due to a single key. 

There is however, a case where this backpressure is particularly bad: lowering the `range_max_bytes`  for a range. Imagine you have a large number of ranges with the new default range size of `512 MiB` and you try to lower it to the old default of `64 MiB`. At that point, all writes to those ranges will be blocked until the range splits twice!

**To Reproduce**

Create a  large number of ranges with the new default range size of `512 MiB` and you try to lower it to the old default of `64 MiB`. At that point, all writes to those ranges will be blocked until the range splits twice!

**Expected behavior**

Lowering the `max_range_size` causes graceful splitting.

**Additional context**

Also pretty terrible is that this impacts the time series data. Check out the part of this graph where no time series data was written:

image

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in three commits which, taken together, should effectively mitigate the problems caused by reducing the range size.

1) Detect when a range is much larger than the maximum size allowed with the backpressure policy and assume that the range got that big because the maximum range size used to be larger. This "much larger" threshold is controlled by a private cluster setting and defaults to 2MB.

2) Remember, in-memory, previous large range sizes and use that previous range size to decide whether to backpressure.

3) Prioritize splitting ranges which are currently backpressuring writes. 

Fixes #46271

Release note (bug fix): When reducing the `range_max_size` zone configuration, queries will no experience longer experience backpressure based on the new, smaller value until the range size has first been reduced to below that value.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
I like this change. The mitigations aren't super elegant in that multiple are needed to cover different cases, but you did a nice job isolating them and testing them. I feel ok about this making it into the release.

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-:-M3vr9Se1VB5xjQMAENB:b-vqdytq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vkSo6-yBehToLkeJL:-M3vkSo6-yBehToLkeJM:bstj10m) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L36)):*
> ```Go
> )
> 
> // Test that mitigations to backpressure when reducing the range size works.
> ```

`s/works/work/`
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vpC9P-O9OJG-DELML:-M3vpC9P-O9OJG-DELMM:b-6i3skd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L62)):*
> ```Go
> 		waitForBlockedRange func(id roachpb.RangeID),
> 	) {
> 		// Add a testing knob to block split traGet(repl.RangeID)nsactions which we'll enable before
> ```

Something got messed up here.
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vqLr36nWLfclNhMQ9:-M3vqLr49ix_lNaEo-fT:bh91ded) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L179)):*
> ```Go
> 	})
> 
> 	t.Run("no backpressure when much larger on new node", func(t *testing.T) {
> ```

Could you add a comment here about why this case differs from the previous one? It's clear once you understand the implementation of these mitigations, but not if you're just reading the test.
___
*[pkg/kv/kvserver/replica_backpressure.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vjDxB9zPuBCRnKF0v:-M3vjDxB9zPuBCRnKF0w:b-o30t2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/replica_backpressure.go#L45)):*
> ```Go
> // range size by anything larger than the backpressureRangeSizeMultiplier would
> // immediately mean that all ranges require backpressure. To mitigate this
> // unwanted backpressure we say that any range which is large than the
> ```

larger
___
*[pkg/kv/kvserver/replica_backpressure.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vp1wo3E9JBjlywpkw:-M3vp1wo3E9JBjlywpkx:bqidftl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica_backpressure.go#L55)):*
> ```Go
> // We additionally mitigate this situation further by:
> //
> //  1) We store in-memory on each replica the largest zone configuration range
> ```

We should mention somewhere why this is insufficient to be the sole mitigation.
___
*[pkg/kv/kvserver/split_queue_test.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vr0NE0W9YQOq0S869:-M3vr0NE0W9YQOq0S86A:b-n7trvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue_test.go#L60)):*
> ```Go
> 		// No intersection, max bytes+1, no load.
> 		{roachpb.RKeyMin, roachpb.RKey(keys.MetaMax), 64<<20 + 1, 64 << 20, true, 1},
> 		// No intersection, max bytes * 2 + 2, no load, should backpressure
> ```

nit: missing punctuation.

**Review by irfansharif — APPROVED** [review]
:lgtm: (this was pleasant to review)

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-:-M3wHbzIEb3rqdufcnb8:b-cb245c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3w92lv5MhVUyj-A33t:-M3w92lx92W7PK0PhRPq:bjxx0d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L44)):*
> ```Go
> 
> 	const (
> 		rowSize  = 32 << 10
> ```

// 32 Kib
// 32 Mib
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wB-Wf59gFOUA_x5qi:-M3wB-Wf59gFOUA_x5qj:btglpf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L144)):*
> ```Go
> 		tdb.Exec(t, "UPSERT INTO foo VALUES ($1, $2)",
> 			rRand.Intn(10000000), randutil.RandBytes(rRand, rowSize))
> 		// Now we'll change the range_max_bytes to be 2x the range size.
> ```

Looking at just this commit, I don't quite follow how the newMax math below gives you 2x the range size. Isn't it half the range size - 32kb?
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wFBSL9sej7tgkgjzp:-M3wFBSL9sej7tgkgjzq:bg1c7ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L113)):*
> ```Go
> 		unblockSplit = func() {
> 			closeOnce.Do(func() {
> 				allowSplits.Store(true)
> ```

Is the previous commit buggy by not having this there?
___
*[pkg/kv/kvserver/helpers_test.go, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wEM6C4mGCACEqOtqe:-M3wEM6C4mGCACEqOtqf:b-3np2hx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/helpers_test.go#L385)):*
> ```Go
> // LargestPreviousMaxRangeSizeBytes returns the in-memory value used to mitigate
> // backpressure when the zone.RangeMaxSize is decreased.
> func (r *Replica) LargestPreviousMaxRangeSizeBytes() int64 {
> ```

Do we want this to be suffixed with `MuLocked`?
___
*[pkg/kv/kvserver/replica.go, line 478 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wDwuV96lxghh8Edwo:-M3wDwuV96lxghh8Edwp:b-mjwqxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica.go#L478)):*
> ```Go
> 		// size. It is set when the zone config changes to a smaller value and the
> 		// current range size exceeds the new value. It is cleared after the range's
> 		// size drops below its current zone.MaxRangeBytes or the zone.MaxRangeBytes
> ```

s/the/if
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wDKVB6c6OPw4Tlzje:-M3wDKVB6c6OPw4Tlzjf:b-ooplfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica_application_state_machine.go#L839)):*
> ```Go
> 
> 	// If the range is now less than its RangeMaxBytes, clear the history of its
> 	// larger previous max bytes.
> ```

s/larger/largest 
___
*[pkg/kv/kvserver/split_queue.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wGEAPBIjRKm1i_9Pq:-M3wGEAPBIjRKm1i_9Pr:bdssxu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue.go#L113)):*
> ```Go
> 
> 	// additionalPriorityDueToBackpressure is a mechanism to prioritize splitting
> 	// ranges which will actively backpressuring writes.
> ```

s/backpressuring/backpressure?
___
*[pkg/kv/kvserver/split_queue.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wG7UC0-UTrId7XhmB:-M3wG7UC0-UTrId7XhmC:b-xqb9h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue.go#L123)):*
> ```Go
> 	// the limit, we will backpressure. We strongly prefer to split over
> 	// backpressure.
> 	const addiitonalPriorityDueToBackpressure = 50
> ```

Typo here.

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-:-M3wrsqWBJFDUd1vHlwS:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vkSo6-yBehToLkeJL:-M3wjEIU96aHdrz6gLaJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/works/work/`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3w92lv5MhVUyj-A33t:-M3wh1Nn73lv467hTbM-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L44)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

// 32 Kib
// 32 Mib
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wB-Wf59gFOUA_x5qi:-M3whTzXC5_PwrpenHfe:bo5rdul) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd823cb2d0588959acc7d53f0f5dba665f21593d/pkg/kv/kvserver/client_replica_backpressure_test.go#L144)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Looking at just this commit, I don't quite follow how the newMax math below gives you 2x the range size. Isn't it half the range size - 32kb?
</blockquote></details>

The comment is wrong. Updated
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vpC9P-O9OJG-DELML:-M3wgrigCC4bHcVAS8ZO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L62)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Something got messed up here.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wFBSL9sej7tgkgjzp:-M3wjUvb4znkBCwxq6L-:b-ih2lpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L113)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Is the previous commit buggy by not having this there?
</blockquote></details>

I don't think so. Without this, the splits would be unblocked but would fail. This is needed to make the splits actually succeed which is used to check that the `LargestPreviousMaxRangeSizeBytes`is cleared. 
___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vqLr36nWLfclNhMQ9:-M3wkFlHBVBIa5RkZX_C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/client_replica_backpressure_test.go#L179)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you add a comment here about why this case differs from the previous one? It's clear once you understand the implementation of these mitigations, but not if you're just reading the test.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/helpers_test.go, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wEM6C4mGCACEqOtqe:-M3wiEZW-WOh8i-GxQDM:bnnv5tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/helpers_test.go#L385)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we want this to be suffixed with `MuLocked`?
</blockquote></details>

erm I meant to grab the lock, fixed. Thanks
___
*[pkg/kv/kvserver/replica.go, line 478 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wDwuV96lxghh8Edwo:-M3wkU8d2l8-MI5nuChM:b-xs5e1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica.go#L478)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/the/if
</blockquote></details>

I feel like the `after` reasonably distributes over the `or` but :shrug: 
___
*[pkg/kv/kvserver/replica_application_state_machine.go, line 839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wDKVB6c6OPw4Tlzje:-M3wmBIY36OSz1LjEoVw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica_application_state_machine.go#L839)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/larger/largest 
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_backpressure.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vp1wo3E9JBjlywpkw:-M3wmR3w07WAzxHC_LWa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0eb90352bfd7bcce72423dc309a95c0c293b4f79/pkg/kv/kvserver/replica_backpressure.go#L55)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should mention somewhere why this is insufficient to be the sole mitigation.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/split_queue.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wGEAPBIjRKm1i_9Pq:-M3wmStTBdwN07Paqn4n:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue.go#L113)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/backpressuring/backpressure?
</blockquote></details>

Yes, done.
___
*[pkg/kv/kvserver/split_queue.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wG7UC0-UTrId7XhmB:-M3wmkbX4CjjLKGr3HPU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue.go#L123)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Typo here.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/split_queue_test.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3vr0NE0W9YQOq0S869:-M3wmjkp9d6ABS1Yr9Bq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5b0d150322addc8486b407492b0641ed0f67e4/pkg/kv/kvserver/split_queue_test.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: missing punctuation.
</blockquote></details>

Done.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 213 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wy1fo0cJm-wZVB3El:-M3wy1fo0cJm-wZVB3Em:b-jtimab) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9660cc017e71ef34fbaac2175291c67aa89358/pkg/kv/kvserver/client_replica_backpressure_test.go#L213)):*
> ```Go
> 		tdb.Exec(t, "SET CLUSTER SETTING kv.range.backpressure_byte_tolerance = '1 KiB'")
> 
> 		// Now we'll change the range_max_bytes to be 2x the range size and within the
> ```

This comment looks wrong as well. Also, "slop"?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_replica_backpressure_test.go, line 213 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-M3wy1fo0cJm-wZVB3El:-M3xLqi13hqLt3s_5Q-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9660cc017e71ef34fbaac2175291c67aa89358/pkg/kv/kvserver/client_replica_backpressure_test.go#L213)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This comment looks wrong as well. Also, "slop"?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r5, 1 of 5 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46863#-:-M3xncp35Tr_LZJeWHId:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

**Comment by ajwerner** [comment]
TFTR!

bors r=irfansharif ,nvanbenschoten

**Pull request merged**
