### PR TITLE
release: `update-versions` bug fixes

### PR DESCRIPTION
**Pull request by renatolabs**
This fixes two issues found in the `update-versions` automation found while attempting to run it in the process of releasing 22.2.6.

* the `isLatestStableBranch` function would only consider the current released version to be the latest if it is greater than the last known release. However, this automation is run after the release is published and the corresponding tag created, so the comparison should actually be that the released version be greater than or equal to the latest release.

* the `set-cockroach-version` part of the update should only run if we are releasing something v23 or newer. This updates the logic to ignore `version.txt` related updates otherwise.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Output is not what I expected it to be on 22.2.6: <https://teamcity.cockroachdb.com/buildConfiguration/Internal_Cockroach_Release_Process_CreateVersionUpdatePRs/8918691?buildTab=log&focusLine=3&linesState=282.286>

**Comment by renatolabs** [comment]
@rail friendly ping. Could you take a look when you get the chance, please?

**Comment by rail** [comment]
Sure!

**Review by rail — APPROVED** [review]

**Comment by renatolabs** [comment]
bors r=rail

TFTR!

**Pull request merged**
