### PR TITLE
sql/tests: deflake TestErrorDuringExtendedProtocolCommit and TestCancelQueriesRace

### LINKED ISSUE #98843: sql: TestCancelQueriesRace failed
sql.TestCancelQueriesRace [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9108939?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9108939?buildTab=artifacts#/) on master @ [11fbbca584e3bd774ebee3ee94c49ca30a096b26](https://github.com/cockroachdb/cockroach/commits/11fbbca584e3bd774ebee3ee94c49ca30a096b26):

```
=== RUN   TestCancelQueriesRace
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestCancelQueriesRace12901595
    test_log_scope.go:79: use -show-logs to present logs inline
    show_test.go:1213: -- test log scope end --
    show_test.go:1213: Leaked goroutine: goroutine 1437970 [IO wait]:
        internal/poll.runtime_pollWait(0x7f490ae9bf28, 0x72)
        	GOROOT/src/runtime/netpoll.go:305 +0x89
        internal/poll.(*pollDesc).wait(0xc012f4dc80?, 0xc005696020?, 0x0)
        	GOROOT/src/internal/poll/fd_poll_runtime.go:84 +0x32
        internal/poll.(*pollDesc).waitRead(...)
        	GOROOT/src/internal/poll/fd_poll_runtime.go:89
        internal/poll.(*FD).Read(0xc012f4dc80, {0xc005696020, 0x1, 0x200})
        	GOROOT/src/internal/poll/fd_unix.go:167 +0x25a
        net.(*netFD).Read(0xc012f4dc80, {0xc005696020?, 0x7f9765?, 0x435d8d?})
        	GOROOT/src/net/fd_posix.go:55 +0x29
        net.(*conn).Read(0xc00f4b6a20, {0xc005696020?, 0xc005059c18?, 0x436d16?})
        	GOROOT/src/net/net.go:183 +0x45
        io.ReadAtLeast({0x5f1d4c0, 0xc00f4b6a20}, {0xc005696020, 0x1, 0x200}, 0x1)
        	GOROOT/src/io/io.go:332 +0x9a
        io.ReadFull(...)
        	GOROOT/src/io/io.go:351
        github.com/lib/pq.(*conn).ssl(0xc005696000, 0xc0191ba7e0?)
        	github.com/lib/pq/external/com_github_lib_pq/conn.go:1108 +0x16a
        github.com/lib/pq.(*conn).cancel(0xc0072b2f00, {0x5f4ee90, 0xc0191ba7e0})
        	github.com/lib/pq/external/com_github_lib_pq/conn_go18.go:162 +0x2b4
        github.com/lib/pq.(*conn).watchCancel.func1()
        	github.com/lib/pq/external/com_github_lib_pq/conn_go18.go:126 +0x128
        created by github.com/lib/pq.(*conn).watchCancel
        	github.com/lib/pq/external/com_github_lib_pq/conn_go18.go:105 +0xf5
--- FAIL: TestCancelQueriesRace (5.79s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCancelQueriesRace.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25545

### LINKED ISSUE #103892: sql/tests: TestErrorDuringExtendedProtocolCommit failed
sql/tests.TestErrorDuringExtendedProtocolCommit [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10242715?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/10242715?buildTab=artifacts#/) on release-23.1 @ [aff76d86d3475eb66e77fbbb44c4950d7e45f85f](https://github.com/cockroachdb/cockroach/commits/aff76d86d3475eb66e77fbbb44c4950d7e45f85f):

```
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2279 +0xf70
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2281 +0xb96
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2096 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:892 +0x1be
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:767 +0x607

Goroutine 10926 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:174 +0x345
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:1013 +0x1311
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:721 +0x297
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIterator()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:707 +0x13e
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).getExpectedRunningTenants()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_orchestration.go:190 +0x1ea
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).scanTenantsForRunnableServices()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_orchestration.go:100 +0x93
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).start.func1()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_orchestration.go:60 +0x21a
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 10927 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:676 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:393 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:178 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:814 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*systemServerWrapper).serveConn()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:93 +0x1fa
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux()
      github.com/cockroachdb/cockroach/pkg/server/server_controller_sql.go:73 +0x4fc
  github.com/cockroachdb/cockroach/pkg/server.(*serverController).sqlMux-fm()
      <autogenerated>:1 +0xc7
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1755 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6
==================
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #101673 sql/tests: TestErrorDuringExtendedProtocolCommit failed [C-test-failure O-robot T-sql-foundations todo-deprecate.branch-release-23.1.0]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestErrorDuringExtendedProtocolCommit.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-28244

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/98843
fixes https://github.com/cockroachdb/cockroach/issues/103892

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
good catch

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
