### PR TITLE
opt: use new function volatility to determine constant folding

### PR DESCRIPTION
**Pull request by madelynnblue**
Some non-immutable functions are whitelisted when we know them to be safe
(i.e., when cache plans containing them are correctly evicted from the
cache when they would change).

Release notes: None

### CODE REVIEW

**Comment by mjibson** [comment]
The optbuilder/upsert test changed pretty substantially. I'm unsure if it's still testing what it was supposed to or not. There's no expect there so it's unclear.

**Review by RaduBerinde — COMMENTED** [review]
There are a lot of test failures. Some of them seem SRF-related (like generate_series). We probably want to check the `Generator` field, and perhaps `AggregateFunc`, `WindowFunc`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48747#-:-M7AvnWUBxw5yQc8UzO8:b-6dct8b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by mjibson** [comment]
Updated to check the function property class to avoid non-normal functions (aggregate, window, generator).

**Comment by mjibson** [comment]
RFAL

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48747#-:-M7FQ9_-2J-ImuxufBVQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/opt/norm/fold_constants.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48747#-M7FPkrS4th8FyRXN-41:-M7FPh0v8kQOethPP7qX:byv4h8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/548117a22da59795466059eaf50d56b885cbf6f9/pkg/sql/opt/norm/fold_constants.go#L329)):*
> ```Go
> 	args memo.ScalarListExpr, private *memo.FunctionPrivate,
> ) opt.ScalarExpr {
> 	if private.Properties.Class != tree.NormalClass {
> ```

[nit] add a comment explaining why only normal class functions can be folded.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48747#-:-M7Idc4eA-LJz3gwOA0Y:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mjibson)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48747#-:-M7IdpaCDgRBRhHdCWXb:bg7igkv)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @mjibson)

**Pull request merged**
