### PR TITLE
sql: add telemetry/dashboard for configured and used isolation level

### LINKED ISSUE #115647: sql: add observability for whether read committed isolation is being requested
We need metrics and telemetry to understand how read committed isolation is being used in 23.2. I think we should probably have metrics and telemetry for:

- serializable transactions
- snapshot transactions
- read committed transactions
- snapshot transactions requested, but run as serializable
- read committed transactions requested, but run as serializable

(There might be a better way to frame those last two.)

Jira issue: CRDB-34141

Epic CRDB-34172

### PR DESCRIPTION
**Pull request by rafiss**
This telemetry will allow us to see when non-SERIALIZABLE isolation levels are used, and also when they are requested but automatically upgraded to SERIALIZABLE due to settings not being enabled yet.

This does not track instances of SERIALIZABLE transactions, since that is the default, so the noise would overwhelm the other telemetry data.

The telemetry is under the following feature counters:
- sql.txn.isolation.executed_at.level
- sql.txn.isolation.upgraded_from.level

This also adds a chart to the DB Console to help discover if you are affected by changes to isolation level support.
image

fixes https://github.com/cockroachdb/cockroach/issues/115647

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118497)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rafiss)

___
*[`pkg/sql/sqltelemetry/isolation.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuTtlZBJLGcnXzVl0t:-NpuTtlZBJLGcnXzVl0u:b-hurm4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/953e1061d79f99617bb7fca1a2883051e2e56b8d/pkg/sql/sqltelemetry/isolation.go#L27)):*
> ```Go
> // and enabled by the cluster, which may differ from the one the user requested.
> func IsolationLevelCounter(level isolation.Level) telemetry.Counter {
> 	telemetryKey := strings.ToLower(level.String())
> ```

We can use `isolation.Level.StringLower` here and below.

Although, we should probably just precompute the strings without string formatting to avoid a performance cost for each call. Something like:
```go
func IsolationLevelCounter(level isolation.Level) telemetry.Counter {
	const prefix = "sql.txn.isolation.executed_at."
	var key string
	switch level {
	case isolation.Serializable:
		key = prefix + "serializable"
	case isolation.Snapshot:
		key = prefix + "snapshot"
	case isolation.ReadCommitted:
		key = prefix + "read_committed"
	default:
		panic("unexpected")
	}
	return telemetry.GetCounter(key)
}
```
And then a similar approach for `IsolationLevelUpgradedCounter`.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuWtfD1QUBa5Jm-26m:-NpuWtfD1QUBa5Jm-26n:boi4tdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c886e1f63627578f0ca7417a2e617a3c1cd6bf9/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L83)):*
> ```XML
>       sources={nodeSources}
>       tenantSource={tenantSource}
>       tooltip={`The total number of times a SQL transaction was upgraded to a stronger isolation level ${tooltipSelection}. If this metric is non-zero, then your application will be affected by the upcoming support of READ COMMITTED isolation level.`}
> ```

`s/will/may/`?

It's possible that their application is asking for SNAPSHOT isolation, which will still behave the same in v24.1, but then might change in v24.2.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118497)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @nvanbenschoten)

___
*[`pkg/sql/sqltelemetry/isolation.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuTtlZBJLGcnXzVl0t:-Npv6NZMEgCap7-Ycw7B:bsbfpwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/953e1061d79f99617bb7fca1a2883051e2e56b8d/pkg/sql/sqltelemetry/isolation.go#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can use `isolation.Level.StringLower` here and below.

Although, we should probably just precompute the strings without string formatting to avoid a performance cost for each call. Something like:
```go
func IsolationLevelCounter(level isolation.Level) telemetry.Counter {
	const prefix = "sql.txn.isolation.executed_at."
	var key string
	switch level {
	case isolation.Serializable:
		key = prefix + "serializable"
	case isolation.Snapshot:
		key = prefix + "snapshot"
	case isolation.ReadCommitted:
		key = prefix + "read_committed"
	default:
		panic("unexpected")
	}
	return telemetry.GetCounter(key)
}
```
And then a similar approach for `IsolationLevelUpgradedCounter`.
</blockquote></details>

good point; fixed
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuWtfD1QUBa5Jm-26m:-Npv4O6W5DDLDKDKXqDV:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c886e1f63627578f0ca7417a2e617a3c1cd6bf9/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/will/may/`?

It's possible that their application is asking for SNAPSHOT isolation, which will still behave the same in v24.1, but then might change in v24.2.
</blockquote></details>

fixed

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118497)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/sqltelemetry/isolation.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuTtlZBJLGcnXzVl0t:-Npv6WR467-MHSApY7US:btjupnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/953e1061d79f99617bb7fca1a2883051e2e56b8d/pkg/sql/sqltelemetry/isolation.go#L27)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

good point; fixed
</blockquote></details>

Should we include the `default` case to avoid silent bugs if we ever add a new isolation level or call these functions incorrectly?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118497)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/sqltelemetry/isolation.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-NpuTtlZBJLGcnXzVl0t:-Npv7D1FDtMgSlXu-6-l:b-6lm5i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/953e1061d79f99617bb7fca1a2883051e2e56b8d/pkg/sql/sqltelemetry/isolation.go#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we include the `default` case to avoid silent bugs if we ever add a new isolation level or call these functions incorrectly?
</blockquote></details>

i didn't think we should panic the node in the default case, but i will add logging

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118497#-:-Nq-5Ziw3lcs-ihtDL2B:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
