### PR TITLE
opt: Eliminate various CASE WHEN expressions

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
This isn't exactly the PR I wanted to send. I was trying to do something like:

```
(Case
  $input:*
  [ ... (When $input $val:*) ... ]
)
```

which wasn't allowed (`match pattern cannot use variable references`) so I hard coded `True` instead, which makes this rule much less interesting.

Mostly I was interested in understanding the rule syntax and wanted to write a simple one. Because of that I'm totally happy to close this PR unmerged because it's kinda boring, not useful, or maybe even makes things slower for no possible benefit, or whatever other reason.

**Review by RaduBerinde — COMMENTED** [review]
You can do something like `(When $input2 $val:*) & (SameGroup $input $input2)` for that (and add a `CustomFuncs.SameGroup` function).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LM2Hkci0e5YvuOgcoCA:bxggm3r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/conditional, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2IZt7EtNpcb1HQTcL:-LM2IZt7EtNpcb1HQTcM:bxb210o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/logictest/testdata/logic_test/conditional#L68)):*
> ```
> query TTTT
> SELECT
> 	CASE WHEN false THEN 'one' WHEN true THEN 'two' ELSE 'three' END,
> ```

[nit] no tabs in these files
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2Fj3W1gsXT0LZ5EhW:-LM2Fj3W1gsXT0LZ5EhX:b-9avx58) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L209)):*
> ```
> )
> 
> # CaseWhenTrueSimplify simplifes a CASE where a branch is known to match
> ```

[nit] `SimplifyCaseWhenTrue` for consistency with other rule names
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2G3Yy0F3ruu_zzY0X:-LM2G3Yy0F3ruu_zzY0Y:bo2xz93) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L247)):*
> ```
> )
> 
> # CaseOnlyElse converts CASE expressions with the final ELSE present
> ```

[nit] EliminateCaseOnlyElse

"with only the final ELSE present to its input expr"

What about the case where there was no `ELSE` in the original statement? I think it may be covered because we handle that case as if it was `ELSE NULL`, but it should be mentioned. Also, if that's the case, I would update the comment for `Case` in `ops/scalar.opt` and say that  the "else" value is always present; it currently suggests it is optional.

**Review by RaduBerinde — COMMENTED** [review]
correction `(When $input2:* $val:*)`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LM2J1Vn1PkC8pB66vpK:b6vcx0p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
I think just testing whether two expressions are the same is not always correct. For example, what if `$input` is `Null`? I think rather than being `IsSameGroup`, it'd need to be something like:
```
(Case
  $input:(Const *)
  [
    (When
      $condition:(Const *) & (IsEqual $input $condition)
      $val:*
    )
    ...
  ]
)
=>
$val
```
where `IsEqual` is a function that uses SQL equals semantics to do the comparison.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LM2fZdHCJz5FB-uu9SO:b-161n3d)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2hcUSDxFA7YsydYSb:-LM2hcUSDxFA7YsydYSc:b-2w8ccm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L222)):*
> ```
> (Case
>   (True)
>   [ ... (When (True) $val:*) ... ]
> ```

This isn't quite right, because it will match *any* `When` rather than just the first `When`. For example, say the SQL is this:
```
CASE True
  WHEN a=1 THEN 10
  WHEN True THEN 20
END
```
`CASE` has shortcut semantics, so we can't replace that expression with `20`. We must evaluate the `a=1` expression in case it turns out to be true first.

The solution is to only match the first item in the list:
```
[ (When (True) $val:*) ... ]
```
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2G3Yy0F3ruu_zzY0X:-LM2ihGM3RLWzz_Qeeqt:blokda2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] EliminateCaseOnlyElse

"with only the final ELSE present to its input expr"

What about the case where there was no `ELSE` in the original statement? I think it may be covered because we handle that case as if it was `ELSE NULL`, but it should be mentioned. Also, if that's the case, I would update the comment for `Case` in `ops/scalar.opt` and say that  the "else" value is always present; it currently suggests it is optional.

</blockquote></details>

I don't think we require that the `else` value always be present, do we? Assuming we don't require that, the rule could just become this instead:
```
(Case
  *
  [ $item:^(When) ]
)
=>
$item
```
However, we'd also want a rule that mapped the empty `Case` to `Null`, since that would now be possible with the `CaseWhenTrueRemoveFalse` removal rule.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2G3Yy0F3ruu_zzY0X:-LM2tYKi1QvP-r7z9mis:b-24s05d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L247)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't think we require that the `else` value always be present, do we? Assuming we don't require that, the rule could just become this instead:
```
(Case
  *
  [ $item:^(When) ]
)
=>
$item
```
However, we'd also want a rule that mapped the empty `Case` to `Null`, since that would now be possible with the `CaseWhenTrueRemoveFalse` removal rule.
</blockquote></details>

It looks like the execbuilder does assume that: https://github.com/cockroachdb/cockroach/blob/6ff29952748856c4cf43ccf518c670b8dced0b75/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L261

Ideally, we would have an `Else` child of `Case` but it's already using all its children slots.

**Comment by rytaft** [comment]
This is great! Assuming you make the changes suggested by @andy-kimball and @RaduBerinde (`IsEqual` rule above and other changes below), I think this will entirely replace the need for `CASE` constant folding rules.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2hcUSDxFA7YsydYSb:-LM4GnxR7O3sbo9ch0Cj:bzgv4pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L222)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This isn't quite right, because it will match *any* `When` rather than just the first `When`. For example, say the SQL is this:
```
CASE True
  WHEN a=1 THEN 10
  WHEN True THEN 20
END
```
`CASE` has shortcut semantics, so we can't replace that expression with `20`. We must evaluate the `a=1` expression in case it turns out to be true first.

The solution is to only match the first item in the list:
```
[ (When (True) $val:*) ... ]
```
</blockquote></details>

The godoc on the lang package says "If multiple items match, then the list matcher binds to the first match". Is that not the case?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2G3Yy0F3ruu_zzY0X:-LM4I2pp7FYk6M09Q-SP:b6nm7zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It looks like the execbuilder does assume that: https://github.com/cockroachdb/cockroach/blob/6ff29952748856c4cf43ccf518c670b8dced0b75/pkg/sql/opt/exec/execbuilder/scalar_builder.go#L261

Ideally, we would have an `Else` child of `Case` but it's already using all its children slots.
</blockquote></details>

An empty Case with no expressions also doesn't have a type since the expressions determine the type, so we couldn't even create a NULL at that point anyway.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2hcUSDxFA7YsydYSb:-LM4R9nv1Q5ZUNmh_RB_:b-625l6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L222)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The godoc on the lang package says "If multiple items match, then the list matcher binds to the first match". Is that not the case?
</blockquote></details>

Yes, but in the case of your rule, the `(When (True) $val:*)` will only match the 2nd input in my example, because `(True)` won't match the `a=1` expression.
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2G3Yy0F3ruu_zzY0X:-LM4Ramy-WclV23z68R3:b-d1v7ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L247)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

An empty Case with no expressions also doesn't have a type since the expressions determine the type, so we couldn't even create a NULL at that point anyway.
</blockquote></details>

Yes, that's a good point. We need to be careful when removing expressions from the `Case`. Rather than try to create separate rules for each of the various cases (i.e. removing When without Else, removing When with else, removing last When, etc.), I think an approach like we took with `SimplifyAnd` would be easier as well as more efficient.

**Comment by mjibson** [comment]
Rewrote most of the rules and added some custom funcs. RFAL.

I'm minorly confused about the need for both `Const` and `True` rules, and the `SimplifyCaseWhenUnreachable` rule doesn't trigger in the `True` case. Is there a way to have `Const | True | False`? When I try that I get a panic on `c.ExtractConstValue`. Should I just teach IsConstEqual to test for true, false, and null specially?

**Comment by mjibson** [comment]
Hold off on reviewing. I was told about `ConstValue`. I'm going to redo this so it covers false, true, and null as well.

**Review by RaduBerinde — COMMENTED** [review]
LGTM

Not sure how much we care but if we have a true branch that's not the first one, we can still remove all branches that follow it (and convert the true branch to the "else" value).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LMEI8U68ScqC5IqXDRP:b-cstc3h)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1029 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMEGlbC7wxM-wDpepQB:-LMEGlbC7wxM-wDpepQC:belp6ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/1734be52572e92d11d0f84b9ae735b00d4cce474/pkg/sql/opt/norm/custom_funcs.go#L1029)):*
> ```Go
> 	op1 := c.mem.NormOp(const1)
> 	op2 := c.mem.NormOp(const2)
> 	if op1 != op2 || op1 == opt.NullOp || op2 == opt.NullOp {
> ```

[nit] the last check is not necessary
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1046 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMEH5xD079sos1AQ0c9:-LMEH5xD079sos1AQ0cA:b-85sdg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1734be52572e92d11d0f84b9ae735b00d4cce474/pkg/sql/opt/norm/custom_funcs.go#L1046)):*
> ```Go
> // SimplifyWhens removes known unreachable WHEN cases and constructs a new
> // CASE statement. If only the ELSE remains, its expression is returned.
> func (c *CustomFuncs) SimplifyWhens(condition memo.GroupID, whens memo.ListID) memo.GroupID {
> ```

mention that the function assumes that `condition` is a `ConstValue`
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1064 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMEHF7U3q-XG0yWs7NB:-LMEHF7V0Nh4Yn0ljS_s:bwdm3dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1734be52572e92d11d0f84b9ae735b00d4cce474/pkg/sql/opt/norm/custom_funcs.go#L1064)):*
> ```Go
> 
> 		default:
> 			if lb.Empty() {
> ```

[nit] add a comment saying this is the "else" value
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2hcUSDxFA7YsydYSb:-LMEGNX17qlOhA5tF40r:bajlhuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L222)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, but in the case of your rule, the `(When (True) $val:*)` will only match the 2nd input in my example, because `(True)` won't match the `a=1` expression.
</blockquote></details>

Please explain this subtlety in the comment for the rule.
___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 548 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMEHoSs8H_b5QKPoqcp:-LMEHoSs8H_b5QKPoqcq:bj19wxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1734be52572e92d11d0f84b9ae735b00d4cce474/pkg/sql/opt/norm/testdata/rules/scalar#L548)):*
> ```
>       └── const: 'one' [type=string]
> 
> opt expect-not=SimplifyCaseWhenEqual
> ```

Would be good to add some comments explaining what it is verifying, here it's that the true branch isn't the first one

**Review by madelynnblue — COMMENTED** [review]
Added more logic to stop adding things after a matching condition and convert it to the ELSE.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LMF86vsEpZVVPR2bYZG:bcqzi3c)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LM2hcUSDxFA7YsydYSb:-LMF5pDr5DRBoHS9OwN7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f986d29f3cf6e2894f8c289270a051c5c53fc16/pkg/sql/opt/norm/rules/scalar.opt#L222)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Please explain this subtlety in the comment for the rule.
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1063 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG7iX91AHhQRGPy0wl:-LMG7iX91AHhQRGPy0wm:b2pwvao) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/custom_funcs.go#L1063)):*
> ```Go
> 					continue
> 				}
> 				// If this is true, we won't ever match anything else, so convert this to
> ```

This is good, but it won't run in all cases where this simplification can be made. E.g. a `CASE 1 WHEN x, WHEN 1, WHEN y` won't match `SimplifyCaseWhenUnreachable`
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG7dusAyowevlSbcrr:-LMG7dusAyowevlSbcrs:b-skg9rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/custom_funcs.go#L1069)):*
> ```Go
> 				}
> 				lb.AddItem(when.Value())
> 				break Loop
> ```

[nit] maybe just `return c.f.ConstructCase(condition, lb.BuildList())` instead of the label
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1075 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG8DbNDUU_rs_SHpGJ:-LMG8DbNDUU_rs_SHpGK:b-pjq9e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/custom_funcs.go#L1075)):*
> ```Go
> 		default:
> 			if lb.Empty() {
> 				// No ELSE is the only clause (there are no WHENs), remove the CASE.
> ```

remove "No"
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG7TcDElLrnfFVFoSe:-LMG7TcDElLrnfFVFoSf:b-3ezcox) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/rules/scalar.opt#L210)):*
> ```
> 
> # SimplifyCaseWhenEqual simplifes a CASE where the first branch is known
> # to match its expr. We cannot simpliy use the expression from the first
> ```

`simply`

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1063 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG7iX91AHhQRGPy0wl:-LMJCOPM2MRhisdCGoPi:b-exfdgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/custom_funcs.go#L1063)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is good, but it won't run in all cases where this simplification can be made. E.g. a `CASE 1 WHEN x, WHEN 1, WHEN y` won't match `SimplifyCaseWhenUnreachable`
</blockquote></details>

Ah ha! Yes! IsConstValue is smart enough now that I was able to completely remove one of the new normalization rules because it is a subset of the other one. This is much simpler now. Thanks for the pushback.

**Comment by knz** [comment]
Also maybe this could use a release note. 

Either it has a measurable perf boost, in which case the boost should be reported;

or it has no measurable perf boost, in which case I would question this PR as premature optimization that adds non-justified overhead to the opt phase?

**Comment by RaduBerinde** [comment]
I am sure you can appreciate that in the vast majority of queries it won't make a difference, and at the same time you could manufacture some where it makes a dramatic difference. So I'm not sure what measurement you would publish. I don't think this needs a release note (by that token most recent opt changes would need release notes).

**Comment by mjibson** [comment]
None of the recent commits to this directory have any release note, and do much more than this one, so I think I'm following precedent in leaving it empty. @rytaft has already said that this PR removes the need for some work she was going to do, so I think it's justified in going in.

But I defer to the opt team for both of these questions.

**Comment by knz** [comment]
My comment was indeed more a general remark about the opt work than about this particular PR. I think most of these optimizations deserve a release note.

**Review by RaduBerinde — APPROVED** [review]
:lgtm_strong: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-:-LMJY3NWEJHfCRZm6zfN:bfdlkw5)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1063 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMG7iX91AHhQRGPy0wl:-LMJXm5W5Dtod74anUkg:b65il3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5d85c6b633e6f332fbd402b5b7e46691c9b959/pkg/sql/opt/norm/custom_funcs.go#L1063)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ah ha! Yes! IsConstValue is smart enough now that I was able to completely remove one of the new normalization rules because it is a subset of the other one. This is much simpler now. Thanks for the pushback.
</blockquote></details>

Wow, nice! Great observation - if the value is constant and a branch is constant, we can always simplify something one way or another.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1063 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMJXbCk2lhbg2fCCvqH:-LMJXbCk2lhbg2fCCvqI:b-uk9v6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece7b065bb8e64502965bf4da6ffaf15c4e470cb/pkg/sql/opt/norm/custom_funcs.go#L1063)):*
> ```Go
> 				}
> 				// If this is true, we won't ever match anything else, so convert this to
> 				// the ELSE (or just return it if there are no other values).
> ```

[nit] s/other values/earlier items.
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 212 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29990#-LMJXJhv5q_gQVCciJ-2:-LMJXJhv5q_gQVCciJ-3:b-iczh01) ([raw file](https://github.com/cockroachdb/cockroach/blob/ece7b065bb8e64502965bf4da6ffaf15c4e470cb/pkg/sql/opt/norm/rules/scalar.opt#L212)):*
> ```
> # branch known to match is used as the ELSE and further WHEN conditions
> # are skipped. If all WHEN conditions have been removed, the ELSE
> # expression is used. We cannot simply use the expression from the first
> ```

The "we cannot simply" sentence is a bit out of place now, I think the comments in `SimplifyWhens` are sufficient.

**Comment by rytaft** [comment]
Please make sure to backport this - thanks!

**Pull request merged**
