### PR TITLE
upgrades: remove all v22.1 upgrades

### PR DESCRIPTION
**Pull request by dt**
See commits.

### CODE REVIEW

**Comment by dt** [comment]
first commit will likely land on its own in #85530

**Review by irfansharif — APPROVED** [review]

**Comment by dt** [comment]
revised `upgrades: delete ensureSpanConfigSubscription/Migration upgrades` commit to also remove pkg/ccl/upgradesccl

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
