### PR TITLE
roachtest: wait before calling WaitForRebalance in disagg-rebalance

### LINKED ISSUE #111817: roachtest: disagg-rebalance/aws/n4cpu4 failed
roachtest.disagg-rebalance/aws/n4cpu4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/12059861?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/12059861?buildTab=artifacts#/disagg-rebalance/aws/n4cpu4) on master @ [6b08842e45668287861af596c28dce58c352d77e](https://github.com/cockroachdb/cockroach/commits/6b08842e45668287861af596c28dce58c352d77e):

```
(disagg_rebalance.go:94).func1: 24s elapsed without changes, but replica count standard deviation is 47.00 (>10.00)
test artifacts and logs in: /artifacts/disagg-rebalance/aws/n4cpu4/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/storage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*disagg-rebalance/aws/n4cpu4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32078

### PR DESCRIPTION
**Pull request by itsbilal**
This change addresses a relatively rare flake seen in #111817 where waitForRebalance returned rightaway after being called after a node was added to the cluster, as it sees that the last replica movement on the cluster was before the node's addition and was sufficiently far in the past to consider the node rebalanced. This change waits for the new node to at least get one replica before calling `waitForRebalance` to avoid that race.

Fixes #111817.

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @itsbilal, @jbowens, and @smg260)

___
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-NgLojOn9NMkfjdfq1dh:-NgLojOn9NMkfjdfq1di:b-ud9d6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2353fcdef9f770658b169b8a4e85f7d898596/pkg/cmd/roachtest/tests/disagg_rebalance.go#L90)):*
> ```Go
> 			db := c.Conn(ctx, t.L(), 4)
> 			var throwaway int
> 			if err := db.QueryRow("SELECT count(*) FROM tpcc.warehouse").Scan(&throwaway); err != nil {
> ```

We should add a comment explaining why we're doing this.. Seems pretty random, does the fact that we're running a query matter or is it just because it takes a bit more time before we call `waitForRebalance`?

**Comment by itsbilal** [comment]
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-NgLojOn9NMkfjdfq1dh:-NgPb9kv88G8H3DGXX1n:b-t5d23a) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2353fcdef9f770658b169b8a4e85f7d898596/pkg/cmd/roachtest/tests/disagg_rebalance.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should add a comment explaining why we're doing this.. Seems pretty random, does the fact that we're running a query matter or is it just because it takes a bit more time before we call `waitForRebalance`?
</blockquote></details>

The fact that we're doing a count(*) should hopefully result in enough reads to at least get one replica to move over to the new node by the time we call `waitForRebalance`? I agree it's somewhat finicky, open to other ideas (maybe a `SucceedsSoon` that checks for replica count on this new node being > 0?)

**Comment by RaduBerinde** [comment]
I like the SucceedsSoon idea, it's more to the point..

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jbowens, @RaduBerinde, and @smg260)

___
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-NgLojOn9NMkfjdfq1dh:-NgPlnss0Lb6-p1HQ9XL:b-iejw10) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2353fcdef9f770658b169b8a4e85f7d898596/pkg/cmd/roachtest/tests/disagg_rebalance.go#L90)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

The fact that we're doing a count(*) should hopefully result in enough reads to at least get one replica to move over to the new node by the time we call `waitForRebalance`? I agree it's somewhat finicky, open to other ideas (maybe a `SucceedsSoon` that checks for replica count on this new node being > 0?)
</blockquote></details>

Just went ahead and did this. PTAL!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-:-NgQ9DGR80i1FXF1zjhy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @jbowens, and @smg260)

___
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-NgLojOn9NMkfjdfq1dh:-NgQ9F1f0n5k3glhzWJV:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae2353fcdef9f770658b169b8a4e85f7d898596/pkg/cmd/roachtest/tests/disagg_rebalance.go#L90)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Just went ahead and did this. PTAL!
</blockquote></details>

Nice!

**Comment by jbowens** [comment]
CI failure appears to be fixed in #112025.

**Review by itsbilal — COMMENTED** [review]
TFTR! Rebased, will merge after CI green

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111975#-:-NgQSewn2cKt_w89TjYB:b-qdtpb1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @jbowens, and @smg260)

**Comment by itsbilal** [comment]
bors r=RaduBerinde

**Comment by itsbilal** [comment]
blathers backport 23.2

**Pull request merged**
