### PR TITLE
workload: check that TPCH workload returns expected results

### PR DESCRIPTION
**Pull request by yuzefovich**
Now, by default, whenever TPCH workload is being run on scale factor of 1,
the returned output is checked against the expected results (which have been
roughly confirmed with PostgreSQL). This behavior can be disabled
with a flag `--disable-checks=true` to the workload command.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Some concerns are:
1. I modified date output from `1994-04-07 00:00:00+00:00` (returned by our cli) to `1994-04-07 00:00:00 +0000 +0000` (returned by the workload)
2. an error on query 11
3. `6202` represented by ASCII codes by the workload (`[54 50 48 50]`)

**Review by jordanlewis — APPROVED** [review]
:lgtm: let's get this merged, although we won't currently pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34891#-:-LiP15tTAGr23iAqIa9B:bfsv1mm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/workload/tpch/tpch.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34891#-LiP12y5DBanHUO0G1Hd:-LiP12y5DBanHUO0G1He:bk2wosp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a6b2503a0b3c7c217726d1d79f72586c4954b6/pkg/workload/tpch/tpch.go#L56)):*
> ```Go
> }
> 
> // TODO(yuzefovich): this seems to not be used anywhere, should we delete it?
> ```

init functions get automatically run by Go.

**Review by yuzefovich — COMMENTED** [review]
Query 11 has since been fixed, but it returns 1048 rows, so I added a check only for the number of rows returned for it (same as query 16).

Query 12 is still skipped (I'm not sure what the problem is, running query through cli gives the expected result, but via a workload it for some reason returns ASCII encoding of the output `Error: wrong result on query 12 in row 0 in column 1: got "[54 50 48 50]", expected "6202"`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34891#-:-LiQ79fWCjT8HPXTllYC:b5b5baw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/workload/tpch/tpch.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34891#-LiP12y5DBanHUO0G1Hd:-LiQ6zvt2JiBB-iQojhz:bddonkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a6b2503a0b3c7c217726d1d79f72586c4954b6/pkg/workload/tpch/tpch.go#L56)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

init functions get automatically run by Go.
</blockquote></details>

Yeah, I didn't know about this at the time, thanks!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
