### PR TITLE
distsql: rip out the experimental lookup join code

### PR DESCRIPTION
**Pull request by RaduBerinde**
Before the optimizer, we had an experimental flag for lookup join,
which caused the distsql planner to plan lookup joins whenever
possible. This flag is now obsolete, and it involves a lot of specific
code. In particular, with this flag, the JoinReader had to be able to
perform a second lookup into the primary index (when the index is
non-covering). This is not used by the optimizer, which plans two
separate lookup joins in this case.

This change removes the flag and all related code.

Release note (sql change): The experimental_force_lookup_join setting
has been removed.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Bumpity

**Comment by solongordon** [comment]
This is so satisfying to see. Tentatively looks good but I'll take a closer look at `joinreader.go` later this morning. Also it looks like TPCC is still using the `experimental_force_lookup_join` setting (see `stock_level.go`).

**Comment by jordanlewis** [comment]
Will defer to @solongordon on this but very happy to see it done!

**Review by solongordon — CHANGES_REQUESTED** [review]
Awesome. Looks great in general, with a couple minor comments and the TPCC change I mentioned above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-:-LWvg0M86cwPv7gfb4II:bpskf71)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @solongordon)

___
*[pkg/sql/distsqlrun/joinreader.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWveD_94ACsxNCg5nmJ:-LWveD_94ACsxNCg5nmK:bv4swvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfed96f39ba8440604c1e86d348c1abda790a64d/pkg/sql/distsqlrun/joinreader.go#L295)):*
> ```Go
> 	//   return more rows than the input batch size.
> 	// - If the index is a secondary index which does not contain all the needed
> 	//   output columns, perform a second lookup on the primary index.
> ```

Out of date comment
___
*[pkg/sql/distsqlrun/joinreader.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWve6kt9M2lmLHK212I:-LWve6kt9M2lmLHK212J:b-taog35) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfed96f39ba8440604c1e86d348c1abda790a64d/pkg/sql/distsqlrun/joinreader.go#L399)):*
> ```Go
> 
> // performLookup reads the next batch of index rows (performing a second lookup
> // against the primary index if necessary), joins them to the corresponding
> ```

Out of date comment.
___
*[pkg/sql/distsqlrun/stats.proto, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWvfXZKEE1jcjpYQIwS:-LWvfXZKEE1jcjpYQIwT:b-437pgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9b554007cf96e280b1562d2e32159eaf0b4521/pkg/sql/distsqlrun/stats.proto#L75)):*
> ```protobuf
>   InputStats input_stats = 1 [(gogoproto.nullable) = false];
>   InputStats index_lookup_stats = 2 [(gogoproto.nullable) = false];
>   InputStats primary_index_lookup_stats = 3;
> ```

Wouldn't hurt to ensure that 3 is not reused, though seems rather unlikely it would cause any issues.

**Review by RaduBerinde — COMMENTED** [review]
Thanks! I removed the setting of the flag from tpcc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-:-LWvxkCX5U-S3dvwGoNM:b-y9w05h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/distsqlrun/joinreader.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWveD_94ACsxNCg5nmJ:-LWvxZaj1DgQWiXgXzpU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfed96f39ba8440604c1e86d348c1abda790a64d/pkg/sql/distsqlrun/joinreader.go#L295)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Out of date comment
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/joinreader.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWve6kt9M2lmLHK212I:-LWvxbFZ9WlltuDUA1yp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfed96f39ba8440604c1e86d348c1abda790a64d/pkg/sql/distsqlrun/joinreader.go#L399)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Out of date comment.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/stats.proto, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-LWvfXZKEE1jcjpYQIwS:-LWvxcC7DDdkriJkZ_qE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9b554007cf96e280b1562d2e32159eaf0b4521/pkg/sql/distsqlrun/stats.proto#L75)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Wouldn't hurt to ensure that 3 is not reused, though seems rather unlikely it would cause any issues.
</blockquote></details>

Done.

**Review by solongordon — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34142#-:-LWw9sknAD4agMBxbCZV:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

**Pull request merged**
