### PR TITLE
plpgsql: add support for nested blocks

### LINKED ISSUE #114775: sql: support nested blocks in PL/pgSQL
We don't currently support nested blocks in PL/pgSQL.

Here's a demonstration:

```sql
CREATE FUNCTION f() RETURNS integer AS $$
BEGIN
  BEGIN
    RETURN 1;
  END;
END;
$$ LANGUAGE plpgsql;
SELECT f();
```

Returns `unimplemented: attempted to use a PL/pgSQL statement that is not yet supported`

Jira issue: CRDB-33676
Epic: CRDB-34165

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: change order of params and variables

Previously, the parameters of a continuation sub-routine would be chosen
by first appending the variables of the (single) block, then the parameters
of the PL/pgSQL routine. In preparation for supporting nested blocks, this
commit changes the order to first add the routine's parameters, and then the
variables from the block. This prepares to enforce an invariant that the
parameters/arguments of a parent sub-routine are always a prefix of those
of a child sub-routine. This will simplify exception handling later on.

#### plpgsql: allow early exit for visitor

This commit makes two changes to the plpgsql Visitor interface and
implementation - first, the `changed` return value has been replaced
with pointer comparisons. Second, a new return value, `recurse`,
indicates whether a node's children should be visited. This will
allow for Visitor implementations that have to return early.

#### plpgsql: refactor logic for building PL/pgSQL blocks

This commit pulls the logic for handling a PL/pgSQL block into a single
method. Information specific to a given block (including a pointer to the
parent block) is stored in a new struct, `blockScope`, which is allocated
when the block is built. Note that nested blocks are still not allowed in
this commit.

#### plpgsql: add support for nested blocks

This commit makes the final change to support nested blocks with some
limitations, and adds corresponding tests. Currently, variable shadowing
is not allowed, and a block cannot be nested in another block that has an
exception handler.

Fixes #114775

Release note (sql change): PL/pgSQL now supports nested blocks, with
the following limitations for now: variable shadowing is disallowed,
and exception handlers cannot be used in a routine with nested blocks.

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first two commits are from #117608.

**Review by rharding6373 — COMMENTED** [review]
This looks very clean! I want to take a closer look at r5, but on a first glance, it looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-:-NoSI6GL4UfpoLqP945v:beczt1h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 746 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSFuMf9c5kj9unmJIM:-NoSFuMf9c5kj9unmJIN:bou5aqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/364e40d4faf522c9fbbd1fe0ccda8cee61192bcd/pkg/sql/opt/optbuilder/plpgsql.go#L746)):*
> ```Go
> func (b *plpgsqlBuilder) resolveOpenQuery(open *ast.Open) tree.Statement {
> 	var boundStmt tree.Statement
> 	for i := len(b.blocks) - 1; i >= 0; i-- {
> ```

Is there a reason why this has to be done in reverse block order?
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSI25_CsKzbauAT3y_:-NoSI25_CsKzbauAT3ya:b-y97mqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8b26d3f125e434cac5a1b4eab86c5d9a068662/pkg/sql/sem/plpgsqltree/statements.go#L120)):*
> ```Go
> 					newStmt = s.CopyNode()
> 				}
> 				newStmt.(*Block).Decls[i] = decl
> ```

s/decl/newDecl

Should fix the rewrite test.
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSIVLp268V_OUsRF6N:-NoSIVLp268V_OUsRF6O:b-or1ehk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8b26d3f125e434cac5a1b4eab86c5d9a068662/pkg/sql/sem/plpgsqltree/statements.go#L120)):*
> ```Go
> 					newStmt = s.CopyNode()
> 				}
> 				newStmt.(*Block).Decls[i] = decl
> ```

Speaking of the rewrite test, it would be great if you could add some nested blocks with references that need to be rewritten. It's a good way to test the visitors.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117710)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 746 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSFuMf9c5kj9unmJIM:-NoS__xq9cbvXfv83nvF:bzgb8lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/364e40d4faf522c9fbbd1fe0ccda8cee61192bcd/pkg/sql/opt/optbuilder/plpgsql.go#L746)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is there a reason why this has to be done in reverse block order?
</blockquote></details>

Variable shadowing isn't allowed now, but when it is, we want to look at more recent blocks first. I'll add a comment.
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSI25_CsKzbauAT3y_:-NoSaMEv1Dxo42WSEQHd:b-klwj6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8b26d3f125e434cac5a1b4eab86c5d9a068662/pkg/sql/sem/plpgsqltree/statements.go#L120)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

s/decl/newDecl

Should fix the rewrite test.
</blockquote></details>

Agh, thanks for catching that. Done.
___
*[`pkg/sql/sem/plpgsqltree/statements.go` line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSIVLp268V_OUsRF6N:-NoSaPyR3FZiFLPDIcOy:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc8b26d3f125e434cac5a1b4eab86c5d9a068662/pkg/sql/sem/plpgsqltree/statements.go#L120)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Speaking of the rewrite test, it would be great if you could add some nested blocks with references that need to be rewritten. It's a good way to test the visitors.
</blockquote></details>

Good idea, done.

**Review by mgartner — APPROVED** [review]
:lgtm_strong: Amazing! Great job on this!

> Reviewed 1 of 3 files at r3, 51 of 51 files at r7, 31 of 31 files at r8, 28 of 28 files at r9, 45 of 45 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-:-Np6dMV1BUlKdvzU1BYe:b5t44ip)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6_WB-9HU0nybL_MFR:-Np6_WB-9HU0nybL_MFS:b-jnhkd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1376)):*
> ```Go
> 	}
> 	args := make(memo.ScalarListExpr, 0, len(con.def.Params))
> 	addArg := func(name ast.Variable, typ *types.T) {
> ```

nit: `typ` is not used in this function
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1579 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6Zp7tAbXAlauiLkt3:-Np6Zp7tAbXAlauiLkt4:b-db68n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1579)):*
> ```Go
> }
> 
> func (b *plpgsqlBuilder) pushBlock(bs plBlock) *plBlock {
> ```

nit: add short description
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1584 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6Zs9-0OMIwydtvey3:-Np6Zs9-0OMIwydtvey4:b-db68n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1584)):*
> ```Go
> }
> 
> func (b *plpgsqlBuilder) popBlock() {
> ```

nit: add short description
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1604 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6_kAN52qrBdV0uHpl:-Np6_kAN52qrBdV0uHpm:b-osh28w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1604)):*
> ```Go
> 	var count int
> 	for i := range b.blocks {
> 		count += len(b.blocks[i].varTypes)
> ```

Why `len(varTypes)` and not `len(vars)`?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block` line 251 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6cGgyBK_7LCpX51Oj:-Np6cGgz02Y3HNOJYI0l:b-jdo7t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/89db332e655d246b99b9b2614ef5a91f45849504/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block#L251)):*
> ```
> 
> # If an exception is thrown and caught within an inner block, the outer block
> # is not rolled back, and execution can continue.
> ```

Very cool!
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block` line 461 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6clWL5SFh6JCHCDW5:-Np6clWL5SFh6JCHCDW6:b-15zkz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/89db332e655d246b99b9b2614ef5a91f45849504/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block#L461)):*
> ```
> 
> # A block cannot currently be nested in a block with an exception handler
> # (tracked in #foo).
> ```

Did you mean to put an issue number here?

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-:-NpMMEeH1T88k9nPjZKf:b-8gk8uj)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 746 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-NoSFuMf9c5kj9unmJIM:-NpMM5Xf7s98HAkA23v4:beua70l) ([raw file](https://github.com/cockroachdb/cockroach/blob/364e40d4faf522c9fbbd1fe0ccda8cee61192bcd/pkg/sql/opt/optbuilder/plpgsql.go#L746)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Variable shadowing isn't allowed now, but when it is, we want to look at more recent blocks first. I'll add a comment.
</blockquote></details>

Ok, thanks for the clarification!

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-:-NpWQRiN7BdKpGa_Lqgm:bz5mair)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6_WB-9HU0nybL_MFR:-NpWQM3m0wvXyoulMr8-:b-4tqtz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1376)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `typ` is not used in this function
</blockquote></details>

Good catch, Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1579 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6Zp7tAbXAlauiLkt3:-NpWJEhG7wc_3cupvzuE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1579)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add short description
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1584 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6Zs9-0OMIwydtvey3:-NpWJF7uBbkmdFDw2BY3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1584)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add short description
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 1604 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6_kAN52qrBdV0uHpl:-NpWIbYz8FSTyN0ZtM6H:b75vtwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6c8101769bee46c1be3a2398b75b04c91f378a8/pkg/sql/opt/optbuilder/plpgsql.go#L1604)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why `len(varTypes)` and not `len(vars)`?
</blockquote></details>

No particular reason. `vars` does seem more self-explanatory, so I changed it to that.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block` line 461 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/117710#-Np6clWL5SFh6JCHCDW5:-NpWHGRV6vteYXTSHono:ba6ipmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/89db332e655d246b99b9b2614ef5a91f45849504/pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block#L461)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you mean to put an issue number here?
</blockquote></details>

Oops, fixed that.

**Pull request merged**
