### PR TITLE
tests: silence some warnings

### PR DESCRIPTION
**Pull request by knz**
This will improve investigations for failures like #111541.

Epic: CRDB-18499.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Thank you!

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111571)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/logictest/logic.go` line 1556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111571#-Nfl9jX75qg3eJOnwbst:-Nfl9jX75qg3eJOnwbsu:bwo743v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d71ed0f451e51a19068c15fb9df49b61afa5146c/pkg/sql/logictest/logic.go#L1556)):*
> ```Go
> 			}
> 
> 			tenant, err := t.cluster.Server(i).TenantController().StartTenant(context.Background(), tenantArgs)
> ```

I was also annoyed by this - #111537.

**Comment by yuzefovich** [comment]
Go ahead with this one - there is a timeout under stress on that PR, I need to investigate that.

**Comment by knz** [comment]
bors r=yuzefovich

**Pull request merged**
