### PR TITLE
deps: switch to maintained fork of go-bindata

### PR DESCRIPTION
**Pull request by RaduBerinde**
Updating the dependencies to use a maintained fork of `go-bindata`
(this fork is trusted by homebrew). Part of the reason is to fix some
staticcheck (linter) failures around capitalized error messages.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
It's a bit ridiculous that linters would complain about error messages in deps. I thought we weren't vetting deps.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37177#-:-LdU1X_W-viv5FXaeigU:b-ichd8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
It's about error messages in generated files like `embedded.go`.

**Comment by tbg** [comment]
Ah, duh. Ok, I wish we didn't lint that as well (probably takes lots of
resources), but I realize that's harder to do.

**Comment by RaduBerinde** [comment]
Yeah. I don't think we can avoid the linter loading the files because things wouldn't build without the. We could ignore the lints for these files, but it seemed like a good idea to use a maintained fork anyway.

**Pull request merged**
