### PR TITLE
ui: Add Jest as test runner to DB Console

### PR DESCRIPTION
**Pull request by nathanstilwell**
DB Console is the last place Cockroach Labs is using a test runner other than [Jest](https://jestjs.io/). This PR adds Jest as the test runner intended to replace [Mocha](https://mochajs.org/). Mocha runs in a headless browser via [Karma](https://karma-runner.github.io/latest/index.html) whereas Jest will run tests in NodeJS and simulate a browser environment using [jsdom](https://github.com/jsdom/jsdom). Due to this change in environment, you will see not only files to set up the Jest test runner, but changes to some tests, some mocking of browser globals that are not included in jsdom by default, and some configuration adjustment to the `tsconfig.json`.

Since configuration changes are infrequent and are highly contextual, we decided to err on the side of verbose inline documentation in configuration files.

Details about individual changes to configs or tests are documented in commit messages.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Great work, a lot of changes! :D    
I added just a few comments

> Reviewed 2 of 7 files at r2, 12 of 20 files at r3, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 4 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 6 of 10 files at r15, 5 of 9 files at r17, 3 of 3 files at r18, 1 of 1 files at r19, 5 of 5 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-:-N5l11Zk3rCYhns3Btgh:b1kv9ss)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @nathanstilwell)

___
*[`pkg/ui/workspaces/db-console/src/setupTests.js` line 17 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5kzZ9r5VTuOMzLp5rh:-N5kzZ9sBHds3LTs681g:b1ovjz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/setupTests.js#L17)):*
> ```JavaScript
> 
> /**
>  * Various thing in DB Console use global fetch. `fetch` is generally
> ```

nit: things
___
*[`pkg/ui/workspaces/db-console/src/redux/analytics.ts` line 19 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5kzgsm12bue3q6oqFT:-N5kzgsm12bue3q6oqFU:b-1v9rex) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/redux/analytics.ts#L19)):*
> ```XML
> import { versionsSelector } from "src/redux/nodes";
> import { AdminUIState } from "src/redux/state";
> import { history } from "src/redux/history";
> ```

just curious, what's the diff between the history from /history vs /state?
___
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 398 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l00qSAZV1gVfjBKcv:-N5l00qSAZV1gVfjBKcw:b8iz927) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L398)):*
> ```XML
>     it("routes to <ActiveStatementsView> component with view=active", () => {
>       navigateToPath("/sql-activity?tab=Statements&view=active");
>       assert.lengthOf(appWrapper.find(StatementsPage), 1);
> ```

we have a new view inside the Statements Page specific for active statements (the default view is the historical), so this test wants to check if that view was indeed selected, so I think it should be the `ActiveStatementsView` as it was
___
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 418 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l0HrTEHzxhpIEjiaB:-N5l0HrTEHzxhpIEjiaC:b-pv5jez) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L418)):*
> ```XML
>     it("routes to <ActiveTransactionsView> component with view=active", () => {
>       navigateToPath("/sql-activity?tab=Transactions&view=active");
>       assert.lengthOf(appWrapper.find(TransactionsPage), 1);
> ```

same things as above

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 398 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l00qSAZV1gVfjBKcv:-N5lSmvRCQFZfHL212SJ:bug6mqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L398)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we have a new view inside the Statements Page specific for active statements (the default view is the historical), so this test wants to check if that view was indeed selected, so I think it should be the `ActiveStatementsView` as it was
</blockquote></details>

For some reason the `ActiveStatementsView` isn't found and so causes this test to fail. Does that ActiveStatementsView depend on a network request to load or some specific data to be present?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82161)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag, @nathanstilwell, and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 398 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l00qSAZV1gVfjBKcv:-N5lVviI29aX04ii6SQ7:b-ki0mf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L398)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

For some reason the `ActiveStatementsView` isn't found and so causes this test to fail. Does that ActiveStatementsView depend on a network request to load or some specific data to be present? 
</blockquote></details>

cc @xinhaoz

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/db-console/src/redux/analytics.ts` line 19 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5kzgsm12bue3q6oqFT:-N5lWG2c2CUPcDFbDu3N:b9yhoj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/redux/analytics.ts#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

just curious, what's the diff between the history from /history vs /state?
</blockquote></details>

I believe it is the same (in that they are both created from `createHashHistory()`), but this was extracted to remove a circular dependency.

**Review by matthewtodd — APPROVED** [review]
:tada: wow. Thanks, @nathanstilwell! Other than the open `ActiveStatementsView` conversation, :lgtm: 

> Reviewed 2 of 7 files at r2, 11 of 20 files at r3, 6 of 31 files at r21, 4 of 9 files at r22, 3 of 3 files at r23, 5 of 10 files at r24, 14 of 18 files at r25, 9 of 9 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-:-N6DrHloAqd_5wS4HpMB:b-dxi0gu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag, @nathanstilwell, and @xinhaoz)

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 398 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l00qSAZV1gVfjBKcv:-N6K5S4xB8vtB_cpQMMV:b-88n3hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L398)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

cc @xinhaoz 
</blockquote></details>

The page should load fine if there's no data, were there any other errors encountered?

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 398 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/82161#-N5l00qSAZV1gVfjBKcv:-N6iMmrj0dAWR9cz9H20:b-z96n7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3b8df51fe3f9f1f5ee3166df90b3434a2995e8a/pkg/ui/workspaces/db-console/src/app.spec.tsx#L398)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

The page should load fine if there's no data, were there any other errors encountered?
</blockquote></details>

@xinhaoz The test simply fails to find the `ActiveStatementsView` component in the `appWrapper`.

**Pull request merged**
