### PR TITLE
storage/engine: assert that Go and C agree on sizeof(DBSlice)

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/engine/rocksdb.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42954#-LvHhY7RBxtxI8fEWLLQ:-LvHhY7SEGMw_OAW5mxw:b-ll2a7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0cd02f1b61b032b8963a823d9ae65968511121/pkg/storage/engine/rocksdb.go#L137)):*
> ```Go
> }
> 
> func init() {
> ```

Where is this called?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/storage/engine/rocksdb.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42954#-LvHhY7RBxtxI8fEWLLQ:-LvHjlEOCjaHasM_hrVT:b5y6554) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0cd02f1b61b032b8963a823d9ae65968511121/pkg/storage/engine/rocksdb.go#L137)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Where is this called?
</blockquote></details>

Functions named `init()` are called before `main()` is invoked.

**Review by petermattis — COMMENTED** [review]
This is ready for a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42954#-:-LvI-eeq9q4bp3lM0hiF:bvbv8bn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

___
*[pkg/cli/debug.go, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42954#-LvI-Zac10TqyUN3FXEs:-LvI-Zac10TqyUN3FXEt:bqx855l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a993fc904dda4872a670fa4fc18283a4d256a9c2/pkg/cli/debug.go#L117)):*
> ```Go
> // If 'readOnly' is true, opens the store in read-only mode.
> func OpenExistingStore(dir string, stopper *stop.Stopper, readOnly bool) (engine.Engine, error) {
> 	fmt.Printf("OpenExistingStore: forcing CI to stressrace the cli package\n")
> ```

I'm going to revert this change before merging. It is intended merely to demonstrate the CI failure.

**Comment by knz** [comment]
Makefile change LGTM

**Comment by petermattis** [comment]
I think I’ll just remove the first commit. This was  definitely the
problem. No need to keep that level of paranoid checking.

**Review by itsbilal — COMMENTED** [review]
:+1: on dropping the runtime size check, now that we’ve narrowed this down. 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42954#-:-LvIIo2v9p3DiY6KxSLX:b-q785ke)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @itsbilal, and @tbg)

**Comment by petermattis** [comment]
TFTR!

bors r+

**Comment by tbg** [comment]
Does this need a backport to basically all other branches? If a build without this patch but the old sizeof(DBSlice) follows a build with the new sizeof(DBSlice), won't it run into the same problem again unless its Makefile is also fixed?

**Comment by petermattis** [comment]
> Does this need a backport to basically all other branches? If a build without this patch but the old sizeof(DBSlice) follows a build with the new sizeof(DBSlice), won't it run into the same problem again unless its Makefile is also fixed?

Good point. Maybe to the second question, though figuring out for certain if a backport isn't needed will be onerous. This PR is innocuous enough that preemptively backporting seems reasonable.

**Pull request merged**
