### PR TITLE
storage: handle preemptive snapshots that span merges

### LINKED ISSUE #28369: roachtest: clearrange failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/bf76db84cb64dc90f65d8b2e129c75028127cda2

Parameters:

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=822738&tab=buildLog

```
	test.go:494,cluster.go:762,clearrange.go:53: /home/agent/work/.go/bin/roachprod start teamcity-822738-clearrange: exit status 1

```

### PR DESCRIPTION
**Pull request by benesch**
Preemptive snapshots can indirectly "widen" an existing replica.
Consider a replica that is removed from a range immediately before a
merge, then re-added to the range immediately after the merge. If the
replica is not GC'd before it is re-added to the range, the existing
replica will receive a preemptive snapshot with a larger end key.

This commit teaches the snapshot reception code to handle this case
properly. If widening the existing replica would cause overlap other
replicas, the preemptive snapshot is rejected. Otherwise, a placeholder
for the new keyspace is installed and the snapshot is applied.

Release note: None

Fix #28369.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

The tests fail before the last commit, right?

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-:-LK14zqfCY3zo3icAa0P:bzfecp7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK13sMbDPtnHY6L6I1c:-LK13sMbDPtnHY6L6I1d:b9qw4ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/client_merge_test.go#L1551)):*
> ```Go
> 	// Give store2 the lease to force all commands to be applied, including the
> 	// ChangeReplicas.
> 	mtc.transferLease(ctx, lhsDesc.RangeID, 0, 2)
> ```

Should there be a version of this test where the GC is automatic? We want to make sure that this conflict also triggers a GC of the replica. Not necessary if you think this is already covered elsewhere and you would just be duplicating that here.
___
*[pkg/storage/raft.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK14HJWBJUHCtWBieIy:-LK14HJWBJUHCtWBieIz:b-qwq8c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/raft.go#L187)):*
> ```Go
> }
> 
> func (h *SnapshotRequest_Header) isPreemptive() bool {
> ```

Why not export this? These structs shouldn't be living in `storage` in the first place (they should be in `storagepb` and then they'd need to be exported anyway, though that's not for this PR). Feel free to ignore.
___
*[pkg/storage/store_snapshot.go, line 410 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK14qB54R8KqrR08A2R:-LK14qB54R8KqrR08A2S:be6a1ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L410)):*
> ```Go
> 		// by checking the keyspace covered by the snapshot but not the existing
> 		// replica.
> 		desc.StartKey = existingDesc.EndKey
> ```

Making up a "fake" descriptor here irks me somewhat, but I also don't know how to do this better.

**Review by bdarnell — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28683)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_snapshot.go, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK2XUt63JyMvUWS89Ga:-LK2XUt63JyMvUWS89Gb:btkg83u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L399)):*
> ```Go
> 	desc := snapHeader.State.Desc
> 	if v, ok := s.mu.replicas.Load(int64(desc.RangeID)); ok && (*Replica)(v).IsInitialized() {
> 		// We have an initialized replica. Raft snapshots can always be applied with
> ```

Don't raft snapshots that widen the replica have the same problem? If they're impossible for other reasons we should panic if we get a raft snapshot that tries to widen.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28683)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK13sMbDPtnHY6L6I1c:-LK2zTN4E_6FAsJd2MGN:bib2cq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/client_merge_test.go#L1551)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Should there be a version of this test where the GC is automatic? We want to make sure that this conflict also triggers a GC of the replica. Not necessary if you think this is already covered elsewhere and you would just be duplicating that here.
</blockquote></details>

Yeah, definitely, but it's fairly low priority. This situation is surprisingly unlikely; you only see it after about 5m of merging during the clear range test. It's a bit tricky to get right; you need _all_ of the overlapping ranges to get queued, and you need them to get queued from left to right or you can't make progress. tl;dr we're going to have to get fairly clever to make this perfectly efficient. For now I think it's ok to rely on the scanner + replica GC queue to make things right eventually. We have branch coverage of the code path that queues the replica for GC via the tests in client_raft_test, so things can't be downright broken.
___
*[pkg/storage/raft.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK14HJWBJUHCtWBieIy:-LK3-8Al5wKOJZGQI4kP:b-2t19z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/raft.go#L187)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Why not export this? These structs shouldn't be living in `storage` in the first place (they should be in `storagepb` and then they'd need to be exported anyway, though that's not for this PR). Feel free to ignore.
</blockquote></details>

¯\_(ツ)_/¯  I just default to making things unexpected where possible. I've marked it as exported now! I'll leave the protobuf movement to another PR.
___
*[pkg/storage/store_snapshot.go, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK2XUt63JyMvUWS89Ga:-LK3-Jn47RiYdCF9MjB3:b-667fuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L399)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't raft snapshots that widen the replica have the same problem? If they're impossible for other reasons we should panic if we get a raft snapshot that tries to widen. 
</blockquote></details>

Indeed. Raft snapshots are special because they _have_ to be applied, but we guarantee that we have a contiguous set of RHS replicas that we can subsume so it's OK. I have that hacky WIP, #28533, to solve this. For now I'm going to proceed with this PR as is, as it simply fixes one of the two ways that we mishandle snapshots. (I.e., it's not introducing a new incorrect codepath for Raft snapshots.)
___
*[pkg/storage/store_snapshot.go, line 410 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK14qB54R8KqrR08A2R:-LK3-DJd4udGPIT3UoPG:bp2zeg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L410)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Making up a "fake" descriptor here irks me somewhat, but I also don't know how to do this better.
</blockquote></details>

Agreed. I tried to use a span instead, but getOverlappingKeyRangeLocked takes a `roachpb.RangeDescriptor` (ugh!), and fixing that is a whole can of worms.

**Comment by benesch** [comment]
> The tests fail before the last commit, right?

Yep, the new tests fail without the corresponding snapshot changes!

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28683)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/store_snapshot.go, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK2XUt63JyMvUWS89Ga:-LK3DRbyDNM7ICKkgHV4:b-klzsk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L399)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Indeed. Raft snapshots are special because they _have_ to be applied, but we guarantee that we have a contiguous set of RHS replicas that we can subsume so it's OK. I have that hacky WIP, #28533, to solve this. For now I'm going to proceed with this PR as is, as it simply fixes one of the two ways that we mishandle snapshots. (I.e., it's not introducing a new incorrect codepath for Raft snapshots.)
</blockquote></details>

OK, but change "can always be applied with no further checks" to something like "cannot be rejected at this point, so the constraints that ensure they are safe to apply must be performed elsewhere" (with pointers to those checks where possible)

**Comment by benesch** [comment]
Agh agh agh! TestStoreRangeSplitRaceUninitializedRHS just failed in the new AssertInvariants with:

```
F180816 19:32:18.978542 110458 storage/helpers_test.go:246  [s2] [n2,s2,r11/2:a�{�-�}] misplaced in replicasByKey; found [n2,s2,r1/2:{/Min-a��}] instead```

Yikes! I really hope this is a bug in AssertInvariants.

**Review by benesch — COMMENTED** [review]
The AssertInvariants failure I mentioned in the last comment did, in fact, turn out to be a bug in AssertInvariants. Turns out we need to be more careful when we call that; there can't be any in-flight traffic to the store. I've added a comment to the method explaining all this.

:crossed_fingers: really hope this finally passes CI

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-:-LK3OnnV-Qf-3Zk41LdP:b-eakwl4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/store_snapshot.go, line 399 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28683#-LK2XUt63JyMvUWS89Ga:-LK3Omx7BROvBQUJWUn-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e07b0f9fca93c66a80ba575224dae4959a8ec92/pkg/storage/store_snapshot.go#L399)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

OK, but change "can always be applied with no further checks" to something like "cannot be rejected at this point, so the constraints that ensure they are safe to apply must be performed elsewhere" (with pointers to those checks where possible)
</blockquote></details>

Done.

**Comment by benesch** [comment]
All is well.

bors r=bdarnell,tschottdorf

**Pull request merged**
