### PR TITLE
roachtest: add read committed variants of ycsb

### LINKED ISSUE #107112: roachtest: support ycsb under read committed
As part of the Read Committed implementation, nightly testing of YCSB will be adapted to run at the Read Committed isolation level. When doing so, transaction retry loops will be removed from the workload to validate that retry errors are rare or non-existent under weak isolation.

YCSB provides a useful sandbox to test weaker isolation levels because it contains a diverse collection of simple operations run with high contention.

Jira issue: CRDB-29897

### PR DESCRIPTION
**Pull request by nvb**
Closes #107112.

This PR adds the following six roachtest variants:
```
ycsb/A/nodes=3/cpu=32/isolation-level=read-committed
ycsb/B/nodes=3/cpu=32/isolation-level=read-committed
ycsb/C/nodes=3/cpu=32/isolation-level=read-committed
ycsb/D/nodes=3/cpu=32/isolation-level=read-committed
ycsb/E/nodes=3/cpu=32/isolation-level=read-committed
ycsb/F/nodes=3/cpu=32/isolation-level=read-committed
```

It does so after adding an `--isolation-level` flag to ycsb, which controls the isolation level to run the workload transactions under. If unset, the workload will run with the default isolation level of the database.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I'll kick off some iterations of each workload to compare vs. serializable.

**Comment by nvanbenschoten** [comment]
> I think I'm going to switch that to be the default even for serializable. We've seen external users of our YCSB benchmark get tripped up on this difference vs. the official benchmark.

This change is in https://github.com/cockroachdb/cockroach/pull/107537.

**Comment by nvanbenschoten** [comment]
I updated this PR to reflect the change to the default value of `--read-modify-write-in-txn` in https://github.com/cockroachdb/cockroach/pull/107537. @michae2 PTAL when you get a chance.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107517#-:-NaJ3eEp7A-VSY3I2ivt:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @nvanbenschoten, and @smg260)

___
*[`pkg/workload/connection.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107517#-NaEVvYpEgXGEgrFnZ7l:-NaEVvYpEgXGEgrFnZ7m:b-bn3vda) ([raw file](https://github.com/cockroachdb/cockroach/blob/062f970de8dc96b980d3842fe92949c28dbdb135/pkg/workload/connection.go#L123)):*
> ```Go
> 	// NOTE: validation of the isolation level value is done by the server during
> 	// connection establishment.
> 	return setUrlParam(urls, "default_transaction_isolation", isoLevel)
> ```

If isoLevel is snapshot, should this also set `sql.txn.snapshot_isolation.enabled`?

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=michae2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107517#-:-NaJ9ney8VOZgD8QhG4F:b-v7u84)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @michae2, and @smg260)

___
*[`pkg/workload/connection.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107517#-NaEVvYpEgXGEgrFnZ7l:-NaJ9u6A9C1AHZnjCM4c:bkxnqva) ([raw file](https://github.com/cockroachdb/cockroach/blob/062f970de8dc96b980d3842fe92949c28dbdb135/pkg/workload/connection.go#L123)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If isoLevel is snapshot, should this also set `sql.txn.snapshot_isolation.enabled`?
</blockquote></details>

If there was a session variable to enable snapshot isolation, I think it would be a good idea to set it here. As is, we only have the cluster setting, and we generally don't like workloads silently manipulating cluster settings, so I'll leave for now. Please let me know if you'd like me to revisit.

**Pull request merged**
