### PR TITLE
sql: inverted index accelerate json ? string, json ?& array, and json ?| array ops

### LINKED ISSUE #81114: sql: support inverted index acceleration for json ?, ?|, and ?& text
The `?` operator returns true if the json document on the left contains the string on the right as a top level object key or array element.

The `?|` operator returns true if the json document on the left contains *any* of the strings in the array on the right as top level object keys or array elements.

Finally, the `?&` operator returns true if the json document on the left contains *all* of the strings in the array on the right as top level object keys or array elements.

There's no reason I can think of for why we can't accelerate this operator using the JSON inverted index encoding that we use. We should support this acceleration.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #81114

This commit adds support for accelerating the json ? string operator
when the json argument is a column that has an inverted index over it.

Release note (sql change): the json ? string operator is now index
accelerated if there is an inverted index over the json column referred
to on the left hand side of the expression.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Very cool! Left mostly minor comments. 

> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-:-N2D8jh02CalQ2RKPWis:b-jji4b9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`-- commits` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2D8KB-0TOhCS4aBwma):*
nit: mention that the right hand side must be constant values.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CXd0w95cLD0hZePMx:-N2CXd0w95cLD0hZePMy:b5e2gfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/invertedidx/json_array.go#L270)):*
> ```Go
> 						case treecmp.JSONAllExists:
> 							invertedExpr = getInvertedExprForJSONIndexForExists(evalCtx, d)
> 					*/
> ```

nit: remove these lines from the first commit
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 483 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CWoGQC-APRs-obmyk:-N2CWoGQC-APRs-obmyl:b-9ru0mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/invertedidx/json_array.go#L483)):*
> ```Go
> 
> // extractJSONExistsCondition extracts an InvertedExpression
> // representing an inverted filter over the planner's inverted index, based
> ```

nit: "representing an inverted filter **with the JSONExists (?) operator**, based on ..."
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CWW1j1i6XcsKEacEU:-N2CWW1j1i6XcsKEacEV:blb8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/invertedidx/json_array.go#L500)):*
> ```Go
> 	}
> 	d := memo.ExtractConstDatum(constantVal)
> 	return getInvertedExprForJSONIndexForExists(evalCtx, d)
> ```

nit: you could move these last two lines into the `if` block above, and get rid of `constantVal` and the explicit `else` block.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2D7Ng34qIslYwFmKmz:-N2D7Ng34qIslYwFmKn-:b-hopl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/77f13d324fa524339da7b1d7aa95eca3763baa7a/pkg/sql/opt/invertedidx/json_array.go#L515)):*
> ```Go
> // If some is true, only one of the input RHS keys must exist. If some is false,
> // all of the input RHS keys must exist.
> func (j *jsonOrArrayFilterPlanner) extractJSONExistsArrayCondition(
> ```

This function looks the same as the one above. Is there a difference I'm not seeing?
___
*[`pkg/sql/rowenc/index_encoding.go` line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2D7hgwDlKIox2UMimc:-N2D7hgwDlKIox2UMimd:blld6eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/77f13d324fa524339da7b1d7aa95eca3763baa7a/pkg/sql/rowenc/index_encoding.go#L652)):*
> ```Go
> //
> // If val is an array, then the inverted expression is a disjunction if all is
> // true, and a conjunction otherwise.
> ```

nit: this is the opposite of the logic below - if `all` is true then a conjunction is generated.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CbCUP1o6o-HB_xOo9:-N2CbCUP1o6o-HB_xOoA:b-sgx5z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/logictest/testdata/logic_test/inverted_index#L1108)):*
> ```
>   (7, '["aargh"]'),
>   (8, '"a"'),
>   (9, '[]'),
> ```

Can you add rows with `NULL`, json `null`, json integer, and json boolean?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CbZOeBGpbeWyCXcrD:-N2CbZOeBGpbeWyCXcrE:bsz1oen) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L766)):*
> ```
> 
> # TODO(jordan): why does this query not use the inverted index? I think it's
> # a stats issue.
> ```

It looks like we're not able to determine the selectivity of the filter, so we apply a default selectivity of 1/3, hence the 333/1000 rows. You could add a hint for now.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2Cc5W38rbixB4QBbwM:-N2Cc5W38rbixB4QBbwN:b-2bhmas) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L792)):*
> ```
> • index join
> │ columns: (a, b)
> │ estimated row count: 12 (missing stats)
> ```

Our stats looks bad for this case too - an index join should never result in more or less rows than its input. I don't think out stats estimation is very accurate for inverted filters in general, so for now you can leave a TODO and/or create an issue to track this.

**Review by jordanlewis — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-:-N2ETBvy0iu8p6QOoz45:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2D7Ng34qIslYwFmKmz:-N2EG9V25XgfLVQ1tvMM:bjqmd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/77f13d324fa524339da7b1d7aa95eca3763baa7a/pkg/sql/opt/invertedidx/json_array.go#L515)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This function looks the same as the one above. Is there a difference I'm not seeing?
</blockquote></details>

Good catch, it passes the `all` variable, but besides that it's the same. Consolidated.
___
*[`pkg/sql/rowenc/index_encoding.go` line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2D7hgwDlKIox2UMimc:-N2EPT9W2gXjGBK5MZuk:b-svtfs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/77f13d324fa524339da7b1d7aa95eca3763baa7a/pkg/sql/rowenc/index_encoding.go#L652)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: this is the opposite of the logic below - if `all` is true then a conjunction is generated.
</blockquote></details>

Oops! Thanks.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 1108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CbCUP1o6o-HB_xOo9:-N2EQkOl60xe3NQjcsnh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/logictest/testdata/logic_test/inverted_index#L1108)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add rows with `NULL`, json `null`, json integer, and json boolean?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2CbZOeBGpbeWyCXcrD:-N2EQm58Bz4196DAIU0j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L766)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like we're not able to determine the selectivity of the filter, so we apply a default selectivity of 1/3, hence the 333/1000 rows. You could add a hint for now.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/inverted_index` line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2Cc5W38rbixB4QBbwM:-N2ESWIv8Wk1PVETiNuD:b-rjqfho) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1cc045d56f01853cb96e427c5f6582d59bc01a2/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L792)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Our stats looks bad for this case too - an index join should never result in more or less rows than its input. I don't think out stats estimation is very accurate for inverted filters in general, so for now you can leave a TODO and/or create an issue to track this.
</blockquote></details>

A bunch of the other pre-existing tests in this file are similarly broken, so I'll just add a reference to this to the bigger improvements to inverted indexes issue.

**Comment by jordanlewis** [comment]
> A bunch of the other pre-existing tests in this file are similarly broken, so I'll just add a reference to this to the bigger improvements to inverted indexes issue.

This exists I think in this bullet: " implement stats for invertedFilter by supporting INTERSECTION and UNION operations on histograms."

**Review by rytaft — COMMENTED** [review]
Sorry for the late drive by, but similar to my comments on https://github.com/cockroachdb/cockroach/pull/79705, I feel like this could use some additional tests. I added a some comments below where I think it would be good to add them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-:-N2dQuBh6zdvny5zbqI8:b-d1ldsw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/invertedidx/json_array.go` line 267 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2dUZCL-og6o4wb3UmG:-N2dUZCL-og6o4wb3UmH:b-rffg93) ([raw file](https://github.com/cockroachdb/cockroach/blob/1996774e001c302000ca38c986e4cf0fa045c65e/pkg/sql/opt/invertedidx/json_array.go#L267)):*
> ```Go
> 				case treecmp.Overlaps:
> 					invertedExpr = getInvertedExprForArrayIndexForOverlaps(evalCtx, d)
> 				case treecmp.JSONExists:
> ```

FYI, I believe this function is used for executing inverted joins, which you haven't added support for with these operations. I think it's fine to keep these cases here, but you might consider opening an issue to track adding support for joins in the future.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 385 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2dTWLj-Y0vkgTSR9u4:-N2dTWLk0d_wlzH-U0it:blhvq43) ([raw file](https://github.com/cockroachdb/cockroach/blob/1996774e001c302000ca38c986e4cf0fa045c65e/pkg/sql/opt/invertedidx/json_array.go#L385)):*
> ```Go
> 	case *memo.ContainedByExpr:
> 		invertedExpr = j.extractJSONOrArrayContainsCondition(evalCtx, t.Left, t.Right, true /* containedBy */)
> 	case *memo.JsonExistsExpr:
> ```

It would be good to add unit tests for these. You can update `TestTryFilterJsonOrArrayIndex`.
___
*[`pkg/sql/rowenc/index_encoding.go` line 656 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/81253#-N2dVB7e0YDowoJmAq8F:-N2dVB7e0YDowoJmAq8G:b3k6g2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1996774e001c302000ca38c986e4cf0fa045c65e/pkg/sql/rowenc/index_encoding.go#L656)):*
> ```Go
> // The spans are returned in an inverted.SpanExpression, which represents the
> // set operations that must be applied on the spans read during execution.
> func EncodeExistsInvertedIndexSpans(
> ```

It would be good to add a unit test for this (similar to `TestEncodeContainedJSONInvertedIndexSpans`, etc.).

**Comment by jordanlewis** [comment]
Thanks for the suggestions @rytaft, I will add these.

**Comment by jordanlewis** [comment]
> FYI, I believe this function is used for executing inverted joins, which you haven't added support for with these operations. I think it's fine to keep these cases here, but you might consider opening an issue to track adding support for joins in the future.

Ah, I see - I don't really understand inverted joins at all. What would it take to add support? Filed #81642

**Comment by rytaft** [comment]
Thanks!

> What would it take to add support?

Shouldn't be too difficult, as the machinery is all in place. I updated the issue with some pointers.

**Comment by jordanlewis** [comment]
Sure glad you asked me to add those unit tests! I had added test cases to ensure that ? didn't accidentally return arrays and strings that were prefixed by the search term to ?, but forgot to add a test case that ensured the same thing for *object keys* that were prefixed by the search term, and lo and behold that case was broken due to creating too wide of a span... #81646

**Comment by rytaft** [comment]
Nice! Yea, these JSON ops are tricky... you were the one who originally suggested adding randomized testing for the initial work with `@>`, and it definitely paid off!

**Pull request merged**
