### PR TITLE
partitionccl: move subzone utilities to BSL

### PR DESCRIPTION
**Pull request by andreimatei**
This patch moves some utilities from CCL to BSL.
The root of the tree is the partitionccl.GenerateSubzoneSpans()
function. This function takes a table descriptor and a list of zone
configs referencing partitions in this table and generates the key spans
covered by each partition. The result will be used to populate the
SubzoneSpans structure of the parent zone config.

I'm moving this function, and everything it pulls with it, into BSL -
into the sql package. I'm doing it because I want to use this function
for upcoming test for the "constraint conformance reports". These
reports deal with zones and subzones, and pretty much the only way to
generate subzones is through this code.
One can argue that the existing code layout was already shaky because
the concepts of partitions and subzones (and subzone spans) was already
understood by BSL code by necessity, but the only facility to generate
these constructs lived elsewhere.

Due to this patch, some operations on partitions and partitioned indexes
that used to not work in binaries that don't link in CCL code start
working. That's a good thing. The list of operations in question can be
seen in the small edits to the tests I've had to make.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @darinpp

**Review by bdarnell — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/zone_config.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40512#-Lo1ndaw4JDmXrGXn6Tt:-Lo1ndaw4JDmXrGXn6Tu:b-6nzv6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/320465bd93e4be5177514bb457a3f86ceab69d0e/pkg/sql/zone_config.go#L216)):*
> ```Go
> }
> 
> // !!!
> ```

Remove this.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40512#-:-Lo6-7TK7qGBGQPmIQIa:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/sql/zone_config.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40512#-Lo1ndaw4JDmXrGXn6Tt:-Lo5zOEfCiKzf_L5wldL:b-lhs69o) ([raw file](https://github.com/cockroachdb/cockroach/blob/320465bd93e4be5177514bb457a3f86ceab69d0e/pkg/sql/zone_config.go#L216)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

done, thanks

**Review by andreimatei — COMMENTED** [review]
flaked on #40200 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40512#-:-Lo7Iyg002PAxQgr6Mik:bg6piur)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40512#-:-Lo7pooh7SG7mYKNVZI2:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Pull request merged**
