### PR TITLE
cli: server logging improvements

### LINKED ISSUE #67518: server: runtime stats log messages were dehumanized
Observe the following log message:
```
I210712 23:49:40.153137 471 2@util/log/event_log.go:32 ⋮ [n1] 307 ={"Timestamp":1626133780153135266,"EventType":"runtime_stats","MemRSSBytes":272957440,"GoroutineCount":337,"MemStackSysBytes":4816896,"GoAllocBytes":48553440,"GoTotalBytes":98093112,"GoStatsStaleness":0.001095539,"HeapFragmentBytes":8585760,"HeapReservedBytes":13041664,"HeapReleasedBytes":193437696,"CGoAllocBytes":73521504,"CGoTotalBytes":80556032,"CGoCallRate":0.099993266,"CPUUserPercent":1.6998855,"CPUSysPercent":0.6999529,"GCRunCount":89,"NetHostRecvBytes":84446,"NetHostSendBytes":95344}
```

Observe how this log message used to read:
```
I210711 03:04:11.257023 2225 2@server/status/runtime.go:569 n19] 13674  runtime stats: 12 GiB RSS, 1221 goroutines (stacks: 11 MiB), 171 MiB/395 MiB Go alloc/total (heap fragmentation: 36 MiB, heap reserved: 101 MiB, heap released: 1.5 GiB), 8.0 GiB/10 GiB CGO alloc/total (0.1 CGO/sec), 79.3/11.7 %(u/s)time, 0.1 %gc (0x), 601 MiB/306 MiB (r/w)net
```

I want the old one back.

I had spent considerable effort making that message as readable as I could, and then my toy was broken in https://github.com/cockroachdb/cockroach/pull/65024 because "our users have expressed interest in making this information more reliably parsable" (#63750). I have yet to see a user parse these. In contrast, I routinely want to read the damn thing; "our users" also expressed an interest in us reading their logs.

Please, let's find a way to get the old message back under the default logging settings. Generally, when people are not doing anything custom (i.e. when all the logging channels are multiplexed onto one log file) I think we should primarily aim for this file being read by humans. When I change the logging settings, that's another matter - perhaps we can make it such that I can get both somehow.

In the case of this particular message with the runtime stats, I also question whether anyone ever wants to parse this message, given that we have timeseries for some of these numbers. I think it'd be marginally useful if *we* had a tool to parse these logs, given that debug.zips don't have timeseries at the moment.

### LINKED ISSUE #69781: cli: change the default logging configuration for regular server
Discussed with @andreimatei 
This issue covers the non-test case (separate issue #69765 for test)

For regular servers we would like the following:

- rewrite certain log.Health.Info calls which are under `log.V` to be regular `log.Info` or `log.Dev.Info` — i.e. they are not meant for the HEALTH channel anyway
- generally assign the HEALTH channel to a separate file sink away from the DEV channel
- also include HEALTH events at severity WARNING or higher on the default file sink (alongside the other channels that share it with DEV)
- regarding this PR #69701 (the runtime stats message)
  - make both machine-readable and human-readable message go the HEALTH channel
  - we accept the duplication for the time being, under the condition that we work on tooling (likely `debug merge-log`) so the tool becomes able to reformat structured events in a human-readable form.

    Regarding this last point, we could have a standard database of go templates to be applied on these structured events (we'd have our preferred/suggested impl inside the code, but can be extended from the command line).

- for STORAGE, we already redirect the traffic to a separate sink by default. We also want WARNING/ERRORS from STORAGE go to the default sink.

### PR DESCRIPTION
**Pull request by knz**
Fixes #69781.
Fixes #67518.

This PR intends to generally improve the ability of operators to troubleshoot node-to-node connectivity issues.

It also creates a new "security" log file in the default config to  capture the channels PRIVILEGES and USER_ADMIN.

Notable changes:

- in the default log config for servers:
  - HEALTH events are now redirected to separate log file `cockroach-health.log`.
  - PRIVILEGES and USER_ADMIN events are now redirected to a separate log file `cockroach-security.log`
  - events at severity WARNING or higher from all channels are now copied to the default sink used for the DEV channel.
- the main node-to-node connectivity events are now always logged (to the HEALTH channel).

See the individual commits and release notes for details.

### CODE REVIEW

**Comment by knz** [comment]
@maryliag we'll also want to backport this to the 22.1 branch.

I am somewhat on the fence about considering this as GA blocker.
On the one hand, it is not solving bugs that prevent end-users from using CockroachDB.
On the other hand, it changes the default configuration of new servers. We don't like to change default configs in patch releases, so it may be better to ensure the PR is there before 21.1.0 is released. What do you think?

**Comment by maryliag** [comment]
We can bring this on the release meeting. 
It doesn't necessary needs to be a blocker, but considering it's a good to have for the initial release (because of the change on configuration), it should be included sooner then later.

**Comment by joshimhoff** [comment]
Thanks for making this chnage!

**Review by andreimatei — APPROVED** [review]
:lgtm: 
thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-:-Mk2nS7n7Q44aZvyRmf5:b-uysk58)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/log_flags.go, line 435 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hEZQ3h3PrSv-uyaT:-Mk2hEZQ3h3PrSv-uyaU:b638k0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L435)):*
> ```Go
> }
> 
> // predefinedLogFiles are the files defined when the --log flag
> ```

can you pls comment how this relates to the `default` file-group? I haven't been able to quickly figure out where that group comes from. I'm surprised it isn't in here.

Hmm, in the next commit the `default` file-group is indeed introduced here. So where was it before?
___
*[pkg/cli/log_flags.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hdfx8FcuSGNJbCH7:-Mk2hdfx8FcuSGNJbCH8:bz7whkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L447)):*
> ```Go
>   sql-audit:              { channels: SENSITIVE_ACCESS, auditable: true }
>   sql-exec:               { channels: SQL_EXEC }
>   sql-schema:             { channels: SQL_SCHEMA }
> ```

FWIW, I think the SQL_SCHEMA messages are another case where I'd like to have human-readable messages in the default log file, in addition to whatever is now going to this new file. I see the messages in question come from protos, so I don't know how readable they are. But if they're readable enough and this channel is not too spammy (which it isn't AFAICT), I'd vote to send the messages to both files. These events are pretty important, and I'd like to continue to just look at the default file to the greatest degree possible.
___
*[pkg/cli/log_flags.go, line 436 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2k_wG9MiU9On0Ww6A:-Mk2k_wG9MiU9On0Ww6B:b4zaux0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c31a310a939214f361eed28d4e62234c781cb21b/pkg/cli/log_flags.go#L436)):*
> ```Go
> 	// For every dedicated file sink, add the events from its channels
> 	// at severity WARNING or higher to the default sink.
> 	defSink := c.Sinks.FileGroups["default"]
> ```

Why not hardcode the configuration in `predefinedLogFiles`? If that's possible, I'd certainly prefer seeing a statically-defined configuration that I can easily read. We could perhaps have a test for it to assert that all channels are present in its `default` file-group.
___
*[pkg/rpc/connection_class.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2lw8QEYwb5n5GyusX:-Mk2lw8QEYwb5n5GyusY:b-uxyqc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/connection_class.go#L44)):*
> ```Go
> )
> 
> // connectionClassName maps classes to their name.
> ```

no love for `//go:generate stringer -type=ConnectionClass` ?
___
*[pkg/rpc/context.go, line 336 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2mMGbEZAFQNUPVxK2:-Mk2mMGbEZAFQNUPVxK3:b-zhv91y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/context.go#L336)):*
> ```Go
> var _ redact.SafeFormatter = connKey{}
> 
> // SafeFormat implements the redact.SafeFormatter interface.
> ```

Remind me again why implementing `SafeVAlue` is not appropriate here? I'd find it less surprising to implement `String()` and `SafeValue`. I saw a fly-by discussion between you and Alex Sarkesian recently where he was asking the same.
___
*[pkg/rpc/context.go, line 683 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2mupKD8VtQez96wte:-Mk2mupKD8VtQez96wtf:b-k1etbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/context.go#L683)):*
> ```Go
> 		ctx.conns.Delete(key)
> 	}
> 	log.Health.Infof(ctx.masterCtx, "closing %+v", keys)
> ```

what's the difference between `%+v` and `%s` for a `SafeFormatter`? Cause `%s` would definitely be less surprising.
___
*[pkg/rpc/heartbeat.go, line 119 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2n9Mt1UWxLYSfiLPY:-Mk2n9Mt1UWxLYSfiLPZ:bodrzgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/heartbeat.go#L119)):*
> ```Go
> // with the requester's address.
> func (hs *HeartbeatService) Ping(ctx context.Context, args *PingRequest) (*PingResponse, error) {
> 	if log.V(2) {
> ```

if `log.ExpensiveLogEnabled(ctx, 2)` since you're in here.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70388)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/cli/log_flags.go, line 435 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hEZQ3h3PrSv-uyaT:-Mk4DmJU4RZp4sGu3OJt:b-s5yjp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L435)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you pls comment how this relates to the `default` file-group? I haven't been able to quickly figure out where that group comes from. I'm surprised it isn't in here.

Hmm, in the next commit the `default` file-group is indeed introduced here. So where was it before?
</blockquote></details>

It's automatically added by the config system if it doesn't exist yet and there are channels without a sink assigned yet.
But yes now it doesn't matter since the thing spells everything out explicitly.
___
*[pkg/cli/log_flags.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hdfx8FcuSGNJbCH7:-Mk4Dt1a7GCP4K0ki1mo:b-q9ac9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L447)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

FWIW, I think the SQL_SCHEMA messages are another case where I'd like to have human-readable messages in the default log file, in addition to whatever is now going to this new file. I see the messages in question come from protos, so I don't know how readable they are. But if they're readable enough and this channel is not too spammy (which it isn't AFAICT), I'd vote to send the messages to both files. These events are pretty important, and I'd like to continue to just look at the default file to the greatest degree possible.
</blockquote></details>

I don't see why SQL_SCHEMA is more special in that regard than, say, USER_ADMIN or HEALTH. I think you may be biased because you happen to have done a lot of work that was influenced by schema changes. 
A person in SQL would probably use the SQL_EXEC channel to troubleshoot issues.

We are choosing to separate events by default because it's easier to merge log streams together than to split them after the fact. `debug merge-logs` can help here.
___
*[pkg/cli/log_flags.go, line 436 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2k_wG9MiU9On0Ww6A:-Mk4DjME0rrVd7Je29TB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c31a310a939214f361eed28d4e62234c781cb21b/pkg/cli/log_flags.go#L436)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Why not hardcode the configuration in `predefinedLogFiles`? If that's possible, I'd certainly prefer seeing a statically-defined configuration that I can easily read. We could perhaps have a test for it to assert that all channels are present in its `default` file-group.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70388)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/rpc/connection_class.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2lw8QEYwb5n5GyusX:-Mk4ExN9BNMUppEPH_7Z:bk5w4z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/connection_class.go#L44)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no love for `//go:generate stringer -type=ConnectionClass` ?
</blockquote></details>

Not for this PR - I don't have a working `make bazel-generate` and I don't want to break the build.
___
*[pkg/rpc/context.go, line 336 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2mMGbEZAFQNUPVxK2:-Mk4F6IX6KD9PPVDoZqB:begipma) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/context.go#L336)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Remind me again why implementing `SafeVAlue` is not appropriate here? I'd find it less surprising to implement `String()` and `SafeValue`. I saw a fly-by discussion between you and Alex Sarkesian recently where he was asking the same.
</blockquote></details>

Because `SafeValue` would print the node ID as a naked integer, and I want the `n` in front of it.
___
*[pkg/rpc/context.go, line 683 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2mupKD8VtQez96wte:-Mk4FAHp4bbhpJ1XLlst:bwvqaat) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/context.go#L683)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the difference between `%+v` and `%s` for a `SafeFormatter`? Cause `%s` would definitely be less surprising.
</blockquote></details>

`keys` is an array. `%s` would cause a printf error, `%+v` expands the array to print the individual elements.
___
*[pkg/rpc/heartbeat.go, line 119 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2n9Mt1UWxLYSfiLPY:-Mk4FG2-0sB4NL8TmZrb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/heartbeat.go#L119)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if `log.ExpensiveLogEnabled(ctx, 2)` since you're in here.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70388)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @knz)

___
*[pkg/cli/log_flags.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hdfx8FcuSGNJbCH7:-Mk4GQN-Ex-EVJZzftU-:bbjmorn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L447)):*
> I don't see why SQL_SCHEMA is more special in that regard than, say, USER_ADMIN or HEALTH. 

The difference from `USER_ADMIN` is that those operations are unlikely to destabilize a cluster and make me look a logs, whereas (the start of) schema changes are heavy operation that can be quite relevant.
The difference from `HEALTH` is that `SQL_SCHEMA` does not have periodic spammy message (as far as I can tell).

> A person in SQL would probably use the SQL_EXEC channel to troubleshoot issues.

But that's the thing - I'd make the argument that these schema change messages are important for "a person in KV", because they relate to such heavy operations.

Take it or leave it.
___
*[pkg/rpc/connection_class.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2lw8QEYwb5n5GyusX:-Mk4HDLj9nEZV9NJV_na:brzrv3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/connection_class.go#L44)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not for this PR - I don't have a working `make bazel-generate` and I don't want to break the build.
</blockquote></details>

:)
consider using the generator, including the new file in the bazel file by hand, and seeing what CI has to say about it

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70388)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/cli/log_flags.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2hdfx8FcuSGNJbCH7:-Mk4JP5DBKuknChY4viS:b-7pq0kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ddc873dfff429cc2a4d3e1abe19f91455f8efbfe/pkg/cli/log_flags.go#L447)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> I don't see why SQL_SCHEMA is more special in that regard than, say, USER_ADMIN or HEALTH. 

The difference from `USER_ADMIN` is that those operations are unlikely to destabilize a cluster and make me look a logs, whereas (the start of) schema changes are heavy operation that can be quite relevant.
The difference from `HEALTH` is that `SQL_SCHEMA` does not have periodic spammy message (as far as I can tell).

> A person in SQL would probably use the SQL_EXEC channel to troubleshoot issues.

But that's the thing - I'd make the argument that these schema change messages are important for "a person in KV", because they relate to such heavy operations.

Take it or leave it.
</blockquote></details>

I'd like to try this as-is first, and see how we feel about the result.
To be honest I'd rather keep the config a little bit symmetrical, so that it remains simple to explain. If we introduce a special case later, it needs to be crystal clear why it deserves the exception.
___
*[pkg/rpc/connection_class.go, line 44 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/70388#-Mk2lw8QEYwb5n5GyusX:-Mk4J_uh7-8BfdaFqOQt:b88c7c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/connection_class.go#L44)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

:)
consider using the generator, including the new file in the bazel file by hand, and seeing what CI has to say about it
</blockquote></details>

Again, not this PR. I'd like this to merge today, and I already kicked CI

**Comment by knz** [comment]
yes it was backproted #70411

**Pull request merged**
