### PR TITLE
logictest: add test for mixed-version configs

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit adds a test that verifies that for each supported previous release we have a logictest config that bootstraps the cluster at that version.

Informs: #112629
Release note: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114309)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @celiala and @RaduBerinde)

___
*[`pkg/sql/logictest/logictestbase/logictestbase_test.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114309#-Nj90xWjAMS9ClTKNNVp:-Nj90xWjAMS9ClTKNNVq:bwt4z6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e070cea77f7a64a9ffd37401289907a99c6655bb/pkg/sql/logictest/logictestbase/logictestbase_test.go#L19)):*
> ```Go
> )
> 
> func TestLogicTestConfigs(t *testing.T) {
> ```

Do we maybe want to name this test something like `TestLogicTestConfigsHasMixedVersionConfigs`? Or alternatively put this into a subtest with `t.Run("verify there is a mixed-version config for each supported release", ...)`?
___
*[`pkg/sql/logictest/logictestbase/logictestbase_test.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114309#-Nj90r-l3PgKTH4dPSGc:-Nj90r-l3PgKTH4dPSGd:br6mb2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e070cea77f7a64a9ffd37401289907a99c6655bb/pkg/sql/logictest/logictestbase/logictestbase_test.go#L24)):*
> ```Go
> 		found := false
> 		for _, c := range LogicTestConfigs {
> 			if c.BootstrapVersion == v {
> ```

It might be useful to also check that `c.DisableUpgrade == true`.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114309#-:-Nj92yNL8mIKB3pVe6IU:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @celiala, and @rafiss)

___
*[`pkg/sql/logictest/logictestbase/logictestbase_test.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114309#-Nj90xWjAMS9ClTKNNVp:-Nj92i-y5CO6I1DOC_Dk:b-56ee29) ([raw file](https://github.com/cockroachdb/cockroach/blob/e070cea77f7a64a9ffd37401289907a99c6655bb/pkg/sql/logictest/logictestbase/logictestbase_test.go#L19)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do we maybe want to name this test something like `TestLogicTestConfigsHasMixedVersionConfigs`? Or alternatively put this into a subtest with `t.Run("verify there is a mixed-version config for each supported release", ...)`?
</blockquote></details>

Good point, renamed to `TestLogicTestMixedVersionConfigs`

**Review by andyyang890 — APPROVED** [review]
Nice! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114309#-:-Nj9CiCU3SmpyoFqpzeM:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala and @rafiss)

**Review by rafiss — APPROVED** [review]
that's a great check to add, thanks

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
