### PR TITLE
sql: use separate lookahead of WITH for BUCKET_COUNT

### LINKED ISSUE #75604: sql/tests: TestRandomSyntaxGeneration failed [bucket count syntax]
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4224430&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4224430&tab=artifacts#/) on master @ [83e2df701688745fe7e7d8a0d0e5e7a4ba8633c8](https://github.com/cockroachdb/cockroach/commits/83e2df701688745fe7e7d8a0d0e5e7a4ba8633c8):

```
    rsg_test.go:755: 1m20s of 5m0s: 42374 executions, 606 successful
    rsg_test.go:755: 1m25s of 5m0s: 46534 executions, 661 successful
    rsg_test.go:755: 1m30s of 5m0s: 48930 executions, 701 successful
    rsg_test.go:755: 1m35s of 5m0s: 50146 executions, 720 successful
    rsg_test.go:755: 1m40s of 5m0s: 51845 executions, 751 successful
    rsg_test.go:755: 1m45s of 5m0s: 56463 executions, 810 successful
    rsg_test.go:755: 1m50s of 5m0s: 62181 executions, 880 successful
    rsg_test.go:755: 1m55s of 5m0s: 70478 executions, 987 successful
    rsg_test.go:755: 2m0s of 5m0s: 71771 executions, 1006 successful
    rsg_test.go:755: 2m5s of 5m0s: 75690 executions, 1067 successful
    rsg_test.go:755: 2m10s of 5m0s: 77210 executions, 1094 successful
    rsg_test.go:755: 2m15s of 5m0s: 77830 executions, 1099 successful
    rsg_test.go:755: 2m20s of 5m0s: 78010 executions, 1101 successful
    rsg_test.go:755: 2m25s of 5m0s: 80454 executions, 1145 successful
    rsg_test.go:755: 2m30s of 5m0s: 82277 executions, 1170 successful
    rsg_test.go:755: 2m35s of 5m0s: 87504 executions, 1249 successful
    rsg_test.go:755: 2m40s of 5m0s: 88881 executions, 1270 successful
    rsg_test.go:755: 2m45s of 5m0s: 90518 executions, 1287 successful
    rsg_test.go:755: 2m50s of 5m0s: 91128 executions, 1297 successful
    rsg_test.go:755: 2m55s of 5m0s: 93883 executions, 1336 successful
    rsg_test.go:755: 3m0s of 5m0s: 95275 executions, 1352 successful
    rsg_test.go:755: 3m5s of 5m0s: 97438 executions, 1377 successful
    rsg_test.go:755: 3m10s of 5m0s: 98214 executions, 1388 successful
    rsg_test.go:755: 3m15s of 5m0s: 104256 executions, 1466 successful
    rsg_test.go:755: 3m20s of 5m0s: 107298 executions, 1506 successful
    rsg_test.go:755: 3m25s of 5m0s: 108693 executions, 1525 successful
    rsg_test.go:755: 3m30s of 5m0s: 110567 executions, 1563 successful
    rsg_test.go:755: 3m35s of 5m0s: 111577 executions, 1581 successful
    rsg_test.go:755: 3m40s of 5m0s: 115696 executions, 1632 successful
    rsg_test.go:755: 3m45s of 5m0s: 118104 executions, 1655 successful
    rsg_test.go:755: 3m50s of 5m0s: 121010 executions, 1689 successful
    rsg_test.go:755: 3m55s of 5m0s: 129304 executions, 1801 successful
    rsg_test.go:755: 4m0s of 5m0s: 130694 executions, 1815 successful
    rsg_test.go:755: 4m5s of 5m0s: 133790 executions, 1849 successful
    rsg_test.go:755: 4m10s of 5m0s: 142484 executions, 1961 successful
    rsg_test.go:755: 4m15s of 5m0s: 143866 executions, 1972 successful
    rsg_test.go:755: 4m20s of 5m0s: 144424 executions, 1973 successful
    rsg_test.go:755: 4m25s of 5m0s: 147298 executions, 2021 successful
    rsg_test.go:755: 4m30s of 5m0s: 151125 executions, 2064 successful
    rsg_test.go:755: 4m35s of 5m0s: 158770 executions, 2135 successful
    rsg_test.go:755: 4m40s of 5m0s: 162088 executions, 2173 successful
    rsg_test.go:755: 4m45s of 5m0s: 163495 executions, 2188 successful
    rsg_test.go:755: 4m50s of 5m0s: 168619 executions, 2254 successful
    rsg_test.go:755: 4m55s of 5m0s: 171720 executions, 2313 successful
    rsg_test.go:755: 5m0s of 5m0s: 172831 executions, 2327 successful
    rsg_test.go:791: 172839 executions, 2333 successful
    rsg_test.go:799: cannot parse output of Format: sql="EXPLAIN IMPORT INTO FAMILY . LC_CTYPE ( ident ) ident DATA ( 'string' , POSITION ) WITH OPTIONS ( BUCKET_COUNT = 'string' , 'string' = OWNED , 'string' = PLACEHOLDER )", formattedSQL="EXPLAIN IMPORT INTO \"family\".lc_ctype(ident) IDENT DATA ('string', 'position') WITH bucket_count = 'string', \"string\" = 'owned', \"string\" = 'placeholder'": at or near "with": syntax error
    rsg_test.go:252: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxGeneration2043379524
--- FAIL: TestRandomSyntaxGeneration (304.67s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #74271 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-21.2]
- #65210 sql/tests: TestRandomSyntaxGeneration failed [C-test-failure O-robot branch-release-21.1]
</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-12739

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Fixes #75604

In #75231 we use the `WITH_LA` to resolve conflicts on the
`WITH BUCKET_COUNT` clause. I suspect it somehow made the
random sql generator generate sqls like this:
```
IMPORT INTO FAMILY . FAMILY . CHAR ( ident , ident ) PUBLICATION DATA ( PLACEHOLDER ) WITH OPTIONS ( BUCKET_COUNT = PLACEHOLDER );
```
which is formatted into:
```
IMPORT INTO "family"."family"."char"(ident, ident) PUBLICATION DATA ('placeholder') WITH bucket_count = 'placeholder'
```
this fails the parser for sure, since it's not a legit statement in crdb.
This PR creates a new lookahead token to prevent the sql generator
from generating `IMPORT` statement with `BUCKET_COUNT` in it.

Release note: None

### CODE REVIEW

**Review by chengxiong-ruan — COMMENTED** [review]
To be clear that I ran a roachprod stress to repro but I was just not lucky enough to make it fail on the same case. So I wasn't able to prove my theory with a `it failed before but fixed after` verification :(

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75878#-:-MuvdaRO4XbHKYY-nP3W:b-4kfyk8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for fixing this! can you add a regression test case in `pkg/sql/parser/testdata`?

**Comment by rafiss** [comment]
i.e. apply this patch
```
diff --git a/pkg/sql/parser/testdata/import_export b/pkg/sql/parser/testdata/import_export
index e7f367c4c2..1223d1c033 100644
--- a/pkg/sql/parser/testdata/import_export
+++ b/pkg/sql/parser/testdata/import_export
@@ -85,3 +85,7 @@ EXPORT INTO CSV 's3://my/path/%part%.csv' WITH delimiter = '|' FROM SELECT a, su
 EXPORT INTO CSV ('s3://my/path/%part%.csv') WITH delimiter = ('|') FROM SELECT (a), ((sum)((b))) FROM c WHERE ((d) = (1)) ORDER BY ((sum)((b))) DESC LIMIT (10) -- fully parenthesized
 EXPORT INTO CSV '_' WITH delimiter = '_' FROM SELECT a, sum(b) FROM c WHERE d = _ ORDER BY sum(b) DESC LIMIT _ -- literals removed
 EXPORT INTO CSV 's3://my/path/%part%.csv' WITH _ = '|' FROM SELECT _, sum(_) FROM _ WHERE _ = 1 ORDER BY sum(_) DESC LIMIT 10 -- identifiers removed
+
+parse
+IMPORT INTO FAMILY . FAMILY . CHAR ( ident , ident ) PUBLICATION DATA ( PLACEHOLDER ) WITH OPTIONS ( BUCKET_COUNT = PLACEHOLDER );
+----
```

then run `make test PKG=./pkg/sql/parser TESTS='TestParseDatadriven' TESTFLAGS='-rewrite'`

**Comment by chengxiong-ruan** [comment]
@rafiss thanks for the hint, but the issue here is the random sql generator generated unexpected sql statement. so the statement would fail anyway. I played with the test you mentioned above and it just failed with `parse_test.go:47: at or near "with": syntax error`.

**Comment by rafiss** [comment]
Ah I see, then I'm not sure this fix will change that -- the `opt_with_options` rule in sql.y could still lead to an option with a name of an unreserved_keyword to be used. Maybe we need to update the random syntax generator itself.

**Comment by chengxiong-ruan** [comment]
oh yeah, agreed... I just suspect my previous change cause it so hope this change would solve it.
Now looks like it's probably just the timing that we were lucky enough and never hit into the failure before, but only after my change merged. Closing this pr for now. Do you know who might be the best person to ask for advice how the random generator can be fixed?

**Comment by rafiss** [comment]
Yeah looks like unlucky timing with your PR! Since it wasn't caused by that, feel free to reassign the issue back to me.

But if you would still like to keep working on it, that would be very appreciated :)

> Do you know who might be the best person to ask for advice how the random generator can be fixed?

No one's worked on it for a while unfortunately. Asking in #sql-experience might be the best way.

**Review by chengxiong-ruan — COMMENTED** [review]
I probably don't have enough bandwidth at the moment :( Assigning back to you for now. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75878#-:-Muw3liE0j-aUWoAhtDU:bciojzr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Pull request closed without merging**
