### PR TITLE
sql: fix semantic analysis and type checking of window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, performing semantic analysis and type checking of
related to window functions expressions was performed as a part
of analysis of FuncExpr. However, this is not sufficient in all
cases: for example, on the query like
SELECT rank() OVER (w RANGE 1 PRECEDING) FROM t WINDOW w
AS (ORDER BY a),
in order to correctly analyze 1, we need to have information about
ORDER BY clause coming from window definition w. This information
is only available after we constructed window definitions in
window.go.

Additionally, this commit now requires an ORDER BY clause with
GROUPS mode of framing (which is exactly what PostgreSQL does).
Actually, without the ordering clause, GROUPS mode doesn't make
sense since all rows will be a part of the same peer group which
probably indicates a user error, so we will return an error in
such cases.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
This currently breaks optimizer with an internal error on the following query (from our logic tests):
`SELECT sum(a) OVER (PARTITION BY count(a) OVER ()) FROM x`

```
                testdata/logic_test/window:3008: 
                expected:
                window function calls cannot be nested
                
                got:
                pq: internal error: cannot map variable 3 to an indexed var
                HINT: You have encountered an unexpected error inside CockroachDB.
                
                Please check https://github.com/cockroachdb/cockroach/issues to check
                whether this problem is already tracked. If you cannot find it there,
                please report the error with details at:
                
                    https://github.com/cockroachdb/cockroach/issues/new/choose
                
                If you would rather not post publicly, please contact us directly at:
                
                    support@cockroachlabs.com
                
                The Cockroach Labs team appreciates your feedback.
                
                DETAIL: stack trace:
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go:148: in indexedVar()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go:137: in buildVariable()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar_builder.go:94: in buildScalar()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:482: in buildProject()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:178: in buildRelational()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:1336: in buildWindow()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:220: in buildRelational()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:1336: in buildWindow()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:220: in buildRelational()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:466: in buildProject()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go:178: in buildRelational()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:89: in build()
                github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:77: in Build()
                github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:155: in makeOptimizerPlan()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:761: in makeExecPlan()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:648: in dispatchToExecutionEngine()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:412: in execStmtInOpenState()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:100: in execStmt()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1200: in execCmd()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1136: in run()
                github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:436: in ServeConn()
                github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580: in func1()
```
So there appears to be other changes to the optimizer code required, but I don't know what those are. cc @justinj please help :)

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1039 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LduLvp324VmYmyCx09L:-LduLvp324VmYmyCx09M:b-dp7ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/904e03a9180fbeedeba789741a4fd79b0c4ce804/pkg/sql/opt/optbuilder/scope.go#L1039)):*
> ```Go
> 		// TODO(yuzefovich): is this the right way to do what planner.analyzeExpr
> 		// does in HP?
> 		typedExpr := s.resolveAndRequireType(e, types.Any)
> ```

This just calls `TypeCheck` again, which is redundant with the call above. I think the problem is that you deleted the TypeCheck code for window frame (see my comment there)
___
*[pkg/sql/sem/tree/type_check.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LduMUTE8tZO7CVKALVD:-LduMUTF2R5XyENKxIM3:b-v22ox6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ea19c895d714058c0ed59bbe349e813a4c7803/pkg/sql/sem/tree/type_check.go#L946)):*
> ```Go
> // TypeCheck checks that offsets of the window frame (if present) are of the
> // appropriate type.
> func (f *WindowFrame) TypeCheck(ctx *SemaContext, windowDef *WindowDef) error {
> ```

The problem with deleting this function is now the optimizer has no way to access this logic. I think you probably want `analyzeWindowFrame` to call this function, rather than moving all the logic there.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/sem/tree/type_check.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LduMUTE8tZO7CVKALVD:-LdunnGpBl4R9UI7HELY:bsts4mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ea19c895d714058c0ed59bbe349e813a4c7803/pkg/sql/sem/tree/type_check.go#L946)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The problem with deleting this function is now the optimizer has no way to access this logic. I think you probably want `analyzeWindowFrame` to call this function, rather than moving all the logic there.
</blockquote></details>

Thanks for taking a look! Unfortunately, I don't think that your suggestion can be applied here - the whole purpose of this PR is to move the logic (that is now in `analyzeWindowFrame`) out of TypeCheck. The reason is that in some cases we don't have enough information to do the type checking of window frames yet when FuncExpr is getting type-checked.

For example, with a query like this `SELECT rank() OVER (w RANGE 1 PRECEDING) FROM t WINDOW w AS (ORDER BY a)`, to correctly type check that constant `1` we need to know the type of column `a` that comes from `WINDOW` clause. And (at least in the HP at the moment) we only have that information after we've constructed window definitions in `sql/window.go`. The reason for why the type of `a` is necessary to know is that if it is a numerical column (int, float, decimal), then `1` must be of the same type; if `a` is of date-time related type, then `1` must be an interval.

**Comment by rytaft** [comment]
___
*[pkg/sql/sem/tree/type_check.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LduMUTE8tZO7CVKALVD:-LdzOPvfDEYsocrq93Z1:by6ssr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ea19c895d714058c0ed59bbe349e813a4c7803/pkg/sql/sem/tree/type_check.go#L946)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Thanks for taking a look! Unfortunately, I don't think that your suggestion can be applied here - the whole purpose of this PR is to move the logic (that is now in `analyzeWindowFrame`) out of TypeCheck. The reason is that in some cases we don't have enough information to do the type checking of window frames yet when FuncExpr is getting type-checked.

For example, with a query like this `SELECT rank() OVER (w RANGE 1 PRECEDING) FROM t WINDOW w AS (ORDER BY a)`, to correctly type check that constant `1` we need to know the type of column `a` that comes from `WINDOW` clause. And (at least in the HP at the moment) we only have that information after we've constructed window definitions in `sql/window.go`. The reason for why the type of `a` is necessary to know is that if it is a numerical column (int, float, decimal), then `1` must be of the same type; if `a` is of date-time related type, then `1` must be an interval.
</blockquote></details>

Ok, but couldn't you just take out the code that calls this function from `FuncExpr.TypeCheck` (as you've already done above)? Then you could still call `WindowFrame.TypeCheck` from `sql.window.go` (as the previous code was doing). That would allow you to easily reuse this logic in the optimizer. At the moment, the new code you've written is not getting called by the optimizer.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/sem/tree/type_check.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LduMUTE8tZO7CVKALVD:-Lf20cBu9t2DiEMPjaCD:b3o4rcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2ea19c895d714058c0ed59bbe349e813a4c7803/pkg/sql/sem/tree/type_check.go#L946)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok, but couldn't you just take out the code that calls this function from `FuncExpr.TypeCheck` (as you've already done above)? Then you could still call `WindowFrame.TypeCheck` from `sql.window.go` (as the previous code was doing). That would allow you to easily reuse this logic in the optimizer. At the moment, the new code you've written is not getting called by the optimizer.
</blockquote></details>

Sorry for the long delay. I think during our investigation with Jordan, we came to a conclusion that doing any type checking on window definition within `FuncExpr.TypeCheck` didn't make sense. I guess I need to somehow expose what's happening within `constructWindowDefinitions` and `analyzeWindowFrame` in `sql/window.go` to the optimizer. Any ideas? cc @jordanlewis

**Comment by yuzefovich** [comment]
Hooray! All tests now pass. It required some code copy/pasting from HP to CBO, but everything appears to be working. @justinj @rytaft @jordanlewis RFAL.

What is the "fate" of the code in HP now that CBO fully supports window functions? I guess we'll be removing window functions related code from the former shortly, so it seems ok to have duplicated code in two places for now.

**Comment by RaduBerinde** [comment]
Yeah, the plan is to remove the HP code for everything that's needed for DML statements in 19.2 (but we still have some work to get there, because of various internal paths that still work with just the HP).

**Review by rytaft — COMMENTED** [review]
Nice! Looking much better now....

> Reviewed 5 of 7 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-:-LhksABHD6IRt3sLjNFc:bqoi35n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1091 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkoUm28f5VxNQNYexB:-LhkoUm28f5VxNQNYexC:bew6fgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1091)):*
> ```Go
> 	f = typedFunc.(*tree.FuncExpr)
> 
> 	if err := s.builder.semaCtx.CheckFunctionUsage(f, def); err != nil {
> ```

This call already happens inside the `TypeCheck` call above.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkpS8KBejuVkDA0fWy:-LhkpS8KBejuVkDA0fWz:bara5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1100)):*
> ```Go
> 		s.builder.semaCtx.Properties.Derived.InWindowFunc,
> 	)
> 	s.builder.semaCtx.Properties.Derived.InWindowFunc = true
> ```

This is also already set in `TypeCheck` above.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqEp35eCiiVoH5Ij0:-Lhkmea323k3mSjZXtp8:b-o3z93c) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1103)):*
> ```Go
> 
> 	for i, e := range f.WindowDef.Partitions {
> 		typedExpr := s.resolveAndRequireType(e, types.Any)
> ```

since you're passing `types.Any`, just call `resolveType`
___
*[pkg/sql/opt/optbuilder/scope.go, line 1104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqGL5Ameot046WwCw:-Lhkn9aL9B7CkGh-_tx5:b-262ufw) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1104)):*
> ```Go
> 	for i, e := range f.WindowDef.Partitions {
> 		typedExpr := s.resolveAndRequireType(e, types.Any)
> 		f.WindowDef.Partitions[i] = typedExpr.(tree.TypedExpr)
> ```

this cast is unnecessary
___
*[pkg/sql/opt/optbuilder/scope.go, line 1110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqK8i-1wCVDYjBRkE:-LhkqK8i-1wCVDYjBRkF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1110)):*
> ```Go
> 			panic(builderError{errOrderByIndexInWindow})
> 		}
> 		typedExpr := s.resolveAndRequireType(e.Expr, types.Any)
> ```

ditto
___
*[pkg/sql/opt/optbuilder/scope.go, line 1111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqMliE05AilN3V5lR:-LhkqMliE05AilN3V5lS:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1111)):*
> ```Go
> 		}
> 		typedExpr := s.resolveAndRequireType(e.Expr, types.Any)
> 		f.WindowDef.OrderBy[i].Expr = typedExpr.(tree.TypedExpr)
> ```

ditto
___
*[pkg/sql/opt/optbuilder/scope.go, line 1146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkrhbG8p6w5pSwHSZk:-LhkrhbG8p6w5pSwHSZl:b1w3x0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1146)):*
> ```Go
> var (
> 	errOrderByIndexInWindow = pgerror.New(pgcode.FeatureNotSupported, "ORDER BY INDEX in window definition is not supported")
> 	errVarOffsetGroups      = pgerror.New(pgcode.Syntax, fmt.Sprintf("GROUPS offset cannot contain variables"))
> ```

unnecessary `fmt.Sprintf`
___
*[pkg/sql/sem/tree/type_check.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-Lhkpwqm-0iqThYBdX0t:-LhkpwqnA0tKhp8qlqat:b-ceaq8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/sem/tree/type_check.go#L186)):*
> ```Go
> 	// parameters of a window function in order to reject nested window
> 	// functions.
> 	InWindowFunc bool
> ```

shouldn't need to export this
___
*[pkg/sql/sem/tree/type_check.go, line 734 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkpzLiDxD3lMSJPapR:-LhkpzLiDxD3lMSJPapS:b-ceaq8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/sem/tree/type_check.go#L734)):*
> ```Go
> // CheckFunctionUsage checks whether a given built-in function is
> // allowed in the current context.
> func (sc *SemaContext) CheckFunctionUsage(expr *FuncExpr, def *FunctionDefinition) error {
> ```

shouldn't need to export this

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1091 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkoUm28f5VxNQNYexB:-Lhkxf4QA2ZLgutKHUFP:bfouy83) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1091)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This call already happens inside the `TypeCheck` call above.
</blockquote></details>

Indeed, this seems unnecessary.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkpS8KBejuVkDA0fWy:-Lhkxhg-BVxY7MaNpgBB:b-p7jaqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1100)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is also already set in `TypeCheck` above.
</blockquote></details>

True, it is set there, but then it is reset upon exiting `FuncExpr.TypeCheck` call. And because I'm removing type checking of PARTITION BY and ORDER BY clauses from `FuncExpr.TypeCheck`, when we're actually doing the type checking on those clauses a few lines below, `semaCtx` will think that we're not in a window function, so the call to `s.resolveType` on partitions and order by will not error out.

As a concrete example, on the query `SELECT sum(a) OVER (PARTITION BY count(a) OVER ()) FROM x` from our logic test without changing `inWindowFunc` we get:
`expected "window function calls cannot be nested", but no error occurred`.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqEp35eCiiVoH5Ij0:-LhkyI3zE-iX3i9WpHe6:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1103)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

since you're passing `types.Any`, just call `resolveType`
</blockquote></details>

Nice, thanks!
___
*[pkg/sql/opt/optbuilder/scope.go, line 1104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqGL5Ameot046WwCw:-LhkyJnl7Ue4KqCsGvRz:b-ufbjmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1104)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

this cast is unnecessary
</blockquote></details>

Indeed, thanks!
___
*[pkg/sql/opt/optbuilder/scope.go, line 1110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqK8i-1wCVDYjBRkE:-LhkyMo294a7gBtla0gt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1110)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkqMliE05AilN3V5lR:-LhkyOu4DAclcr_NvUrY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1111)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 1146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkrhbG8p6w5pSwHSZk:-LhkyTldEZ4CHfOeMuHP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1146)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

unnecessary `fmt.Sprintf`
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/type_check.go, line 734 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkpzLiDxD3lMSJPapR:-LhkyWjZ1XMDzr56A_lV:b-eapff3) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/sem/tree/type_check.go#L734)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't need to export this
</blockquote></details>

Resolved.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-:-Lhl1OJ_5IgwJjeezec-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/window.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-Lhl0nhS8hoJfDUliB-z:-Lhl0nhS8hoJfDUliB0-:b5wsidl) ([raw file](https://github.com/cockroachdb/cockroach/blob/13e09ba4af071cb13e983676627f2474c5b5d791/pkg/sql/window.go#L177)):*
> ```Go
> var (
> 	errOrderByIndexInWindow = pgerror.New(pgcode.FeatureNotSupported, "ORDER BY INDEX in window definition is not supported")
> 	errVarOffsetGroups      = pgerror.New(pgcode.Syntax, fmt.Sprintf("GROUPS offset cannot contain variables"))
> ```

another unnecessary `fmt.Sprintf`
___
*[pkg/sql/opt/optbuilder/scope.go, line 1100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-LhkpS8KBejuVkDA0fWy:-Lhl12uaCocb8IM8eDo1:bdkzweb) ([raw file](https://github.com/cockroachdb/cockroach/blob/718f9aeed196efa691d4c375e0cd4f316b09fbf4/pkg/sql/opt/optbuilder/scope.go#L1100)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

True, it is set there, but then it is reset upon exiting `FuncExpr.TypeCheck` call. And because I'm removing type checking of PARTITION BY and ORDER BY clauses from `FuncExpr.TypeCheck`, when we're actually doing the type checking on those clauses a few lines below, `semaCtx` will think that we're not in a window function, so the call to `s.resolveType` on partitions and order by will not error out.

As a concrete example, on the query `SELECT sum(a) OVER (PARTITION BY count(a) OVER ()) FROM x` from our logic test without changing `inWindowFunc` we get:
`expected "window function calls cannot be nested", but no error occurred`.
</blockquote></details>

Cool, thanks for the explanation!

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @justinj, and @rytaft)

___
*[pkg/sql/window.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-Lhl0nhS8hoJfDUliB-z:-Lhl3cDvEuYqGyDU0E0s:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/13e09ba4af071cb13e983676627f2474c5b5d791/pkg/sql/window.go#L177)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

another unnecessary `fmt.Sprintf`
</blockquote></details>

Thanks!

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

**Review by justinj — COMMENTED** [review]
:lgtm: Thanks for the fix!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-:-LhlJLQoApM6Hz8jNiCH:b-6baz2x)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @justinj)

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37251#-:-LhlJrXu8yC1JdiX0FKM:bctxt4d)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Pull request merged**
