### PR TITLE
ui: fix vscode type-checking and autocomplete

### PR DESCRIPTION
**Pull request by maxlang**
cc @tamird

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9158)

### CODE REVIEW

**Comment by mrtracy** [comment]
LGTM, but could you add a comment in the readme or the tsconfig.json (I don't know if that's possible, but maybe) about the tsconfig.build.json file?  That's the most interesting change here.

Also, add some brief description about what you did in the commit message.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-:-KR54mJy8TVmTy6utdhz:b-e7c92d)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[ui/config.js, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-KR55qKngX2s_-shYLmQ:-KR55qKngX2s_-shYLmR:bkj7jia) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8ec5b10b1ec031fd983fe07b7c5dd67a668a572/ui/config.js#L6)):*
> ```JavaScript
>   typescriptOptions: {
>     "typeCheck": "strict",
>     "tsconfig": "tsconfig.build.json"
> ```

i think you might be able to keep just one `tsconfig.json` if you add the `files: ...` entry here under `typescriptOptions`.

---

*[ui/tsconfig.json, line 4 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-KR55aHHwMLxO5pBz4k1:-KR55aHIxtgbEGDpCt-p:b-izo9id) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8ec5b10b1ec031fd983fe07b7c5dd67a668a572/ui/tsconfig.json#L4)):*
> ```JSON
>   "compilerOptions": {
>     "allowJs": true,
>     "allowSyntheticDefaultImports": true,
> ```

isn't this the default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158)*

**Comment by maxlang** [comment]
Done.

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[ui/config.js, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-KR55qKngX2s_-shYLmQ:-KR58ZScTw6TeHHpvDpm:bogf002) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8ec5b10b1ec031fd983fe07b7c5dd67a668a572/ui/config.js#L6)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think you might be able to keep just one `tsconfig.json` if you add the `files: ...` entry here under `typescriptOptions`.
</details>
I've tried it and it doesn't seem to work. 

It also isn't actually listed as a special configuration option here: https://github.com/frankwallis/plugin-typescript#configuration

If you know of a good way to point systemjs to `typings/index.d.ts` I'd prefer that.

---

*[ui/tsconfig.json, line 4 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-KR55aHHwMLxO5pBz4k1:-KR58hOvKJJ_xAqtwUpF:b-h1q10d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8ec5b10b1ec031fd983fe07b7c5dd67a668a572/ui/tsconfig.json#L4)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't this the default?
</details>
Only if the module type is `system`. The default module type is `commonJS` if the target isn't `ES6`, so that's what vscode is defaulting to here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9158#-:-KR5HCxYGgBDBrqj5z5l:b-896fix)*

**Comment by maxlang** [comment]
@tamird any further considerations before I merge?

**Comment by tamird** [comment]
Yes, I'm looking a bit further into this.

**Comment by maxlang** [comment]
I'm also fine merging this and creating an issue to look into removing the duplication, since I want type-checking in vscode and don't think it's worth sinking much more time into for either of us.

**Comment by mrtracy** [comment]
What's the relationship of this to #9346?  Was this merged to master in another commit?

**Comment by tamird** [comment]
Nothing of this work has gone to master, I believe.

**Comment by mrtracy** [comment]
It looks like #9219 was merged instead of this, is that accurate?

**Comment by tamird** [comment]
Yes, but also to develop.

**Comment by mrtracy** [comment]
That's fine, I'm just trying to figure out if this should be closed.  My assumption was that is was superseded by a different commit.

**Comment by maxlang** [comment]
Closed in favor of #9346 and #9219

**Pull request closed without merging**
