### PR TITLE
sql: change help token to ?? (from ?)

### PR DESCRIPTION
**Pull request by justinj**
Unforuntately, `?` collides with a JSON operator, meaning keeping it as
the help token could cause some confusion and parsing issues. Change it
to ?? per discussion.

### CODE REVIEW

**Comment by knz** [comment]
You also need to have a look at ` (c *cliState) GetCompletions` in pkg/cli/sql.go.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/interactive_tests/test_contextual_help.tcl, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-Kvv6XTnyulX_s_L8YBo:-Kvv6XTnyulX_s_L8YBp:bd2pcq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a754f42dc4a079c9296c7ddc73ada5edeb90af0c/pkg/cli/interactive_tests/test_contextual_help.tcl#L29)):*
> ```Tcl
> eexpect "ROLLBACK"
> eexpect "??"
> send "\010\010"
> ```

I'm not sure this needed to change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-:-Kvv6RrBwCEC5hwirMAn:b-nungbo)*

**Comment by justinj** [comment]
Done, missed that.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/interactive_tests/test_contextual_help.tcl, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-Kvv6XTnyulX_s_L8YBo:-KvwI_7kjyFOMskXlZ93:bhs9drr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a754f42dc4a079c9296c7ddc73ada5edeb90af0c/pkg/cli/interactive_tests/test_contextual_help.tcl#L29)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm not sure this needed to change.
</blockquote></details>

Unless I misunderstand what you mean, it does, since otherwise it only backspaces over one of the question marks:

```
root@:26257/> ??\u0008\u001b[Kselect 1;
invalid syntax: statement ignored: syntax error at or near "?"
DETAIL: source SQL:
?select 1;
^
root@:26257/> " (spawn_id exp5) match glob pattern "1 row"? no
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-:-KvwIW4jF24D_pz_RcQ8:b-gh4ykj)*

**Comment by justinj** [comment]
Any outstanding concerns with this PR?

**Comment by knz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cli/interactive_tests/test_contextual_help.tcl, line 29 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-Kvv6XTnyulX_s_L8YBo:-Kw1lnEgLRTejJmnB4X9:bpevxnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a754f42dc4a079c9296c7ddc73ada5edeb90af0c/pkg/cli/interactive_tests/test_contextual_help.tcl#L29)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Unless I misunderstand what you mean, it does, since otherwise it only backspaces over one of the question marks:

```
root@:26257/> ??\u0008\u001b[Kselect 1;
invalid syntax: statement ignored: syntax error at or near "?"
DETAIL: source SQL:
?select 1;
^
root@:26257/> " (spawn_id exp5) match glob pattern "1 row"? no
```
</blockquote></details>

Oh I wasn't reading \010 properly. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19108#-:-Kw1lveiX14EDTW9Bi4v:bnfp4nl)*

**Comment by justinj** [comment]
TFTR!

**Pull request merged**
