### PR TITLE
cdc: Test for falling behind schema TTL

### LINKED ISSUE #28644: changefeedccl: error if a changefeed falls behind kv TTL
Related to https://github.com/cockroachdb/cockroach/issues/28636.

If a changefeed falls behind enough, some of the historical values will be garbage collected. If this happens, the changefeed should error instead of returning bad data (presumably missing the gc'd chagnes).

### PR DESCRIPTION
**Pull request by mrtracy**
Add a test that ensures that changefeeds properly exit if they fall far
enough behind that schema information has been lost due to the GC TTL
(that is, a historical row version can no longer be read because the
schema at its timestamp has been garbage collected).

I have also discovered why the sister test (for the table TTL, not the
schema) required a 3 second sleep: the GC queue enforces that replicas
must have an appropriately high "score" before being GCed, even when the
"shouldQueue" process is skipped. To get around this, I have changed
"ManuallyEnqueueSpan" to a more explicit "ManuallyGCSpan", which
directly calls the processing implementation of the gcQueue on the
appropriate replicas. Both that sister test, and the new schema TTL
test, now only require a more predictable 1 second sleep.

Resolves #28644

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-:-LOJDWlq6a7rmURP8763:bhnhlex)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 706 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-LOJD7b-DlSMtjcmUbBE:-LOJD7b-DlSMtjcmUbBF:bd8njc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe51cfcac966dab5a3962c69daa3732db64f2758/pkg/ccl/changefeedccl/helpers_test.go#L706)):*
> ```Go
> 	sqlDB *sqlutils.SQLRunner,
> 	database, table string,
> ) {
> ```

probably want a t.Helper() at the beginning of this
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-LOJD-pq5fOyJgyqz5RM:-LOJD-prBfaOqd3n2s6E:beesfs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe51cfcac966dab5a3962c69daa3732db64f2758/pkg/ccl/changefeedccl/helpers_test.go#L711)):*
> ```Go
> 		stmt = `ALTER DATABASE system CONFIGURE ZONE USING gc.ttlseconds = $1`
> 	} else {
> 		fmt.Sprintf(`ALTER TABLE %s.%s CONFIGURE ZONE USING gc.ttlseconds = $1`, database, table)
> ```

the result of this Sprintf call seems unused

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31020)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 706 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-LOJD7b-DlSMtjcmUbBE:-LOK6zlX4YGlYxdZh14z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe51cfcac966dab5a3962c69daa3732db64f2758/pkg/ccl/changefeedccl/helpers_test.go#L706)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

probably want a t.Helper() at the beginning of this
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-LOJD-pq5fOyJgyqz5RM:-LOK7-Pz-ztUo-xiRtQF:b-z9tin4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe51cfcac966dab5a3962c69daa3732db64f2758/pkg/ccl/changefeedccl/helpers_test.go#L711)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the result of this Sprintf call seems unused
</blockquote></details>

You're correct, and so is the linter/failing tests.

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31020)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 711 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31020#-LOJD-pq5fOyJgyqz5RM:-LOKHbY_8Th0olXdwbrD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe51cfcac966dab5a3962c69daa3732db64f2758/pkg/ccl/changefeedccl/helpers_test.go#L711)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

You're correct, and so is the linter/failing tests.
</blockquote></details>

Done.

**Comment by vivekmenezes** [comment]
I believe the change to store.go to run a GC is unnecessary. See TestIndexBackfillAfterGC

**Comment by mrtracy** [comment]
Hah, thanks Vivek, wish I had found that earlier! I did not think to look for a request, I was only looking for test hooks.

This actually means the tests do not need the sleep at all, that's 4 total seconds of test time back. Nice! Finishing up the change now.

**Comment by mrtracy** [comment]
bors r=danhhz

**Pull request merged**
