### PR TITLE
server: Make --storage-engine flag non-sticky, use Pebble by default

### LINKED ISSUE #52775: storage: remove "sticky" semantics of --storage-engine flag
The `--storage-engine` flag is currently "sticky". If the flag is omitted from the `cockroach start` command line, whatever the previous value of the flag was is used. More precisely, if the flag is omitted we read the OPTIONS file from the first store directory and determine whether RocksDB or Pebble was last used on the store. For 20.2 we'd like to change these semantics to encourage switching to Pebble. Rather than `--storage-engine` being sticky, we'd like it to default to Pebble if omitted. If you start a node using `--storage-engine=rocksdb` and then restart without the `--storage-engine` flag being specified, the node would switch to using Pebble. Users will still be able to stay on RocksDB using `--storage-engine=rocksdb`, but this will help accelerate the switch to Pebble allowing for the removal of RocksDB as an option for 21.1.

Cc @rmloveland as this will require a docs change when this happens.

### PR DESCRIPTION
**Pull request by itsbilal**
Previously, the --storage-engine CLI flag would be sticky; when
unspecified, it would use the storage engine that was last used to
write to the store directory. This required opening the OPTIONS
file to check what the version string was.

As part of the upgrade path to 20.2, we want to ensure all
upgrading clusters move onto Pebble. This change makes the
default for the --storage-engine flag to be Pebble regardless
of what storage engine was last used. Using RocksDB in 20.2
would require specifying `--storage-engine=rocksdb` on every
`cockroach start` invocation.

Fixes #52775.

Release note (cli change): The --storage-engine CLI flag no longer
defaults to using the last-used storage engine when unspecified.
Instead, pebble is used by default unless otherwise specified using
the --storage-engine flag.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52944)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[pkg/cli/cliflags/flags.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEySDtfCccdhPm1-Ono:-MEySDtfCccdhPm1-Onp:b-485wme) ([raw file](https://github.com/cockroachdb/cockroach/blob/4090bb47462f15b0a690dd8d185c4d2055193f05/pkg/cli/cliflags/flags.go#L844)):*
> ```Go
> 		Name: "storage-engine",
> 		Description: `
> Storage engine to use for all stores on this cockroach node. Options are pebble,
> ```

nit: s/pebble, or /pebble or /
___
*[pkg/storage/enginepb/engine.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEyTGBSCyhdDWEQLDmV:-MEyTGBSCyhdDWEQLDmW:b-f1h2so) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ad048f9935dd565dede9153ebf441e4346e004f/pkg/storage/enginepb/engine.proto#L32)):*
> ```protobuf
>   // Denotes TeePebbleRocksDB as the underlying storage engine type. Only use
>   // for testing purposes.
>   EngineTypeTeePebbleRocksDB = 3;
> ```

I don't think we can renumber the enum variants because the numbers are used in the wire protocol, and changing them breaks compatibility for messages that are serialized with the previous version of the proto definition: eg, running a previous version of Cockroach. Not sure if that's a practical concern or not with this particular proto, but either way I think it's good hygiene to never renumber enums.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52944)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[pkg/cli/cliflags/flags.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEySDtfCccdhPm1-Ono:-MF0vdWU4t48p69Ywj6i:b52bicd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4090bb47462f15b0a690dd8d185c4d2055193f05/pkg/cli/cliflags/flags.go#L844)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: s/pebble, or /pebble or /
</blockquote></details>

Ha, the Oxford comma debate :stuck_out_tongue: Done.
___
*[pkg/storage/enginepb/engine.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEyTGBSCyhdDWEQLDmV:-MF0vkzNE-uFGKtin7jH:b8f4f32) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ad048f9935dd565dede9153ebf441e4346e004f/pkg/storage/enginepb/engine.proto#L32)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I don't think we can renumber the enum variants because the numbers are used in the wire protocol, and changing them breaks compatibility for messages that are serialized with the previous version of the proto definition: eg, running a previous version of Cockroach. Not sure if that's a practical concern or not with this particular proto, but either way I think it's good hygiene to never renumber enums.
</blockquote></details>

This is fine because it's never wired over to other nodes. It's only for node-internal use.  We need Pebble to have the 0 value to make it the real default without threading through a lot of setter code everywhere.

Plus, we made the same kind of change when we introduced `Default` as an engine type in #45512.

**Review by jbowens — APPROVED** [review]
:LGTM:

> Reviewed 4 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-:-MF1mV-U3S8Yj_iiCBir:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/enginepb/engine.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEyTGBSCyhdDWEQLDmV:-MF1mRBcEvmGwtTPlwS4:b-1lshby) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ad048f9935dd565dede9153ebf441e4346e004f/pkg/storage/enginepb/engine.proto#L32)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This is fine because it's never wired over to other nodes. It's only for node-internal use.  We need Pebble to have the 0 value to make it the real default without threading through a lot of setter code everywhere.

Plus, we made the same kind of change when we introduced `Default` as an engine type in #45512.
</blockquote></details>

Ok, sgtm

**Comment by itsbilal** [comment]
Realized that I had forgotten to delete `TestDockerCLI/test_storage_engine_sticky.tcl`, which was failing for obvious reasons. Removed.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52944)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/enginepb/engine.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEyTGBSCyhdDWEQLDmV:-MFBeI8X2x04x1nfxnLz:b-88gw6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ad048f9935dd565dede9153ebf441e4346e004f/pkg/storage/enginepb/engine.proto#L32)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Ok, sgtm
</blockquote></details>

Does this enum need to be defined in a proto? I think we'd only need it defined in a proto if we are using it for on-disk storage or sending it in an RPC, but if we are doing either of those things it isn't safe to renumber.

**Comment by itsbilal** [comment]
___
*[pkg/storage/enginepb/engine.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52944#-MEyTGBSCyhdDWEQLDmV:-MFCHivsDd1DhncqXLEY:b-t7vjkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ad048f9935dd565dede9153ebf441e4346e004f/pkg/storage/enginepb/engine.proto#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does this enum need to be defined in a proto? I think we'd only need it defined in a proto if we are using it for on-disk storage or sending it in an RPC, but if we are doing either of those things it isn't safe to renumber. 
</blockquote></details>

Just realized, it's sent as part of `EngineStats` in the statusServer. Seems like we never make any decisions off of that value, so nothing should break too much, but it is reported to the admin UI. I'll do another PR to change the values back, and have default just mean Pebble.

**Pull request merged**
