### PR TITLE
opt: execution for set operations

### PR DESCRIPTION
**Pull request by RaduBerinde**
Execbuilder code for Union, Intersect, Except (with their All
variants).

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71Vl6yrKHn-R4h3D2-:-L71Vl6yrKHn-R4h3D20:b-8ebgzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L320)):*
> ```Go
> 	// We need to make sure that the two sides render the columns in the same
> 	// order; otherwise we add projections.
> 	// TODO(radu): we don't have to respect the exact order in the two ColLists;
> ```

I don't really understand this comment.... can you give an example?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-:-L71WxcE9PRgPYDAuCMU:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71XUVJ9fzkLqEzQ0qH:-L71XUVK1OymVFlWsb9k:bd89tqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L365)):*
> ```Go
> // given list of columns.
> func (b *Builder) ensureColumns(input execPlan, colList opt.ColList) (exec.Node, error) {
> 	// Check if we need a projection.
> ```

In what case(s) would these not match?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71XUVJ9fzkLqEzQ0qH:-L71ZVvTNBzc6tEawjFD:bpe0ktr) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L365)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In what case(s) would these not match?
</blockquote></details>

`SELECT a, b FROM ab UNION SELECT y, x FROM xy`. The projections would be removed during normalization, we need to add the `y, x` projection back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71Vl6yrKHn-R4h3D2-:-L71fFFu5yu9Hkb7Rp5-:b-j06wbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L320)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't really understand this comment.... can you give an example?
</blockquote></details>

I'll improve the comment. At a high level, if we permute the three ColLists in SetOpColmap with the same permutation, the operation is the same. I'll try to come up with an actual example though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71Vl6yrKHn-R4h3D2-:-L756w0escjVT2C-iWxq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L320)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'll improve the comment. At a high level, if we permute the three ColLists in SetOpColmap with the same permutation, the operation is the same. I'll try to come up with an actual example though.
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71XUVJ9fzkLqEzQ0qH:-L757wm7FsCP1gFaOGu9:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L365)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`SELECT a, b FROM ab UNION SELECT y, x FROM xy`. The projections would be removed during normalization, we need to add the `y, x` projection back.
</blockquote></details>

Added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by rytaft** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71Vl6yrKHn-R4h3D2-:-L75LOa8v-DpO23fVUVt:b-rvgovr) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L320)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good. Can you add a final sentence saying something like, "the presentation physical property will ensure that the columns are presented correctly in the output (i.e., in the order `b, c, a`)."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 320 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-L71Vl6yrKHn-R4h3D2-:-L75NNZ3ZiFzwc4PihBJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/547099063656eadacf4b30af42e20c0a9d08824b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L320)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks good. Can you add a final sentence saying something like, "the presentation physical property will ensure that the columns are presented correctly in the output (i.e., in the order `b, c, a`)."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23568#-:-L75QBy8pVxmfrB48rE5:bnfp4nl)*

**Pull request merged**
