### PR TITLE
cloud: add read rate limiters

### PR DESCRIPTION
**Pull request by dt**
Addresses https://github.com/cockroachdb/cockroach/issues/79588

Release note (sql change): The cluster settings cloudstorage.<provider>.read.node_rate_limit and cloudstorage.<provider>.read.node_burst_limit can now be used to limit throughput when reading from cloud storage during a RESTORE or IMPORT.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07OZ9r-tIqhsTaZQbS:b-qr5g9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
> ```Go
> 	l.pool += int64(n)
> 	const batchedWriteLimit = 128 << 10
> 	if l.pool > batchedWriteLimit {
> ```

Should we do the waiting beforehand if the pool is big enough and then just add to the pool at the end? It seems sort of lame to read the bytes and then hold them in RAM. 



_Code quote:_
```Go
	const batchedWriteLimit = 128 << 10
	if l.pool > batchedWriteLimit {
		if err := l.lim.WaitN(ctx, l.pool); err != nil {
			log.Warningf(ctx, "failed to throttle write: %+v", err)
		}
		l.pool = 0
	}
```

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07P3at3ybtq4fpstx3:b9zvog8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Should we do the waiting beforehand if the pool is big enough and then just add to the pool at the end? It seems sort of lame to read the bytes and then hold them in RAM. 
</blockquote></details>

We don't know how much we'll read until we actually read though, so we don't know how long to wait, right?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07PTkiDyxzaMW1ijO4:b-z2cp9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

We don't know how much we'll read until we actually read though, so we don't know how long to wait, right?
</blockquote></details>

Are you thinking we wait for whatever is in pool if it is big enough first, then read and inc pool and return? i.e. pay for last Read's bytes in the next call?

As far as holding in ram, `p` is in RAM no matter when we wait -- the only difference before vs after the Read() is the values of the bytes in it.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07RSIg8fPrUPMKzf6m:b-8vc56f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
> As far as holding in ram

:facepalm:... right

The idea of waiting up front was to deal with the case where, say, you're big time in debt already and shouldn't be allowed to read anything. It seems bad to issue a request up front. I guess that's already a risk with this amoritzation we're doing here. In the kv layer, what we do for reads is we ask for one byte before and then `N-1` bytes after. Another option is to slightly modify the `RateAlloc` to let you partially return bytes to it and then reserve the total size of your buffer and return the part you didn't read. It would be a small change. Maybe like:

```go
+func (ra *RateAlloc) ReturnPart(n int64) {
+       if n < ra.alloc {
+               ra.alloc = n
+       }
+       ra.Return()
+}
```

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07T01CE_8Itmb1P29Z:b-mjbyz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> As far as holding in ram

:facepalm:... right

The idea of waiting up front was to deal with the case where, say, you're big time in debt already and shouldn't be allowed to read anything. It seems bad to issue a request up front. I guess that's already a risk with this amoritzation we're doing here. In the kv layer, what we do for reads is we ask for one byte before and then `N-1` bytes after. Another option is to slightly modify the `RateAlloc` to let you partially return bytes to it and then reserve the total size of your buffer and return the part you didn't read. It would be a small change. Maybe like:

```go
+func (ra *RateAlloc) ReturnPart(n int64) {
+       if n < ra.alloc {
+               ra.alloc = n
+       }
+       ra.Return()
+}
```
</blockquote></details>

Eh. I'm pretty ambivalent about the debt case -- we'll wait for it soon enough. The spikes here are by a buffer size, and like, it's like a couple mb, so I'm not too worried about it.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-:-N07V-pD9YAA2fd7ewAG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @dt, and @miretskiy)

___
*[pkg/cloud/impl_registry.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-N07OZ9q5-Wy68v01LzE:-N07UsQSBr4qCfqcmkFQ:b-jnts5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99488d83462ca6054fb1ca6e3cb05cde1c17d5/pkg/cloud/impl_registry.go#L305)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh. I'm pretty ambivalent about the debt case -- we'll wait for it soon enough. The spikes here are by a buffer size, and like, it's like a couple mb, so I'm not too worried about it.
</blockquote></details>

fair enough

**Comment by dt** [comment]
pulled #80264 into this so it all backports together

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80261#-:-N07mW653WrEDDaMMZ-w:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
blathers backport 22.1

**Comment by dt** [comment]
blathers backport 22.1

**Pull request merged**
