### PR TITLE
ui: serve ETag header and respect If-None-Match req. header for assets

### PR DESCRIPTION
**Pull request by sjbarag**
Reimplements changes from #78460 but doesn't perform hashing via `init()` to avoid panics reported (and fixed) in https://github.com/cockroachdb/cockroach/pull/78936

CockroachDB has included a "Cache-Control: no-cache" response header when serving static, embedded assets for several years now (dating back to as early as 2015 [1]), but offered no other way for clients to cache those. Since then, asset sizes have grown considerably larger (currently including ~30MB of JavaScript, a size that will be addressed via other methods) and preventing client-side caching causes noticeable loading delays. Add support for the If-None-Match / ETag pair of request/response headers [2], which allows browsers serve assets from their caches if the cached copy of a requested asset is still the latest copy.

[1] 5e8151f176 (Add support for snappy compression over http., 2015-04-07)
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

Release note (performance improvement): Browser caching of files loaded in the admin UI is now supported.

Jira issue: CRDB-14765

### CODE REVIEW

**Comment by sjbarag** [comment]
Currently just a CI-only PR — will convert to a proper PR later today

**Comment by tbg** [comment]
Approach looks good, thank you!
Looking forward to the snappy UI experience coming from this.

**Review by dhartunian — APPROVED** [review]
:lgtm: just some nits.
thanks for this @sjbarag! I assume the etags implementation is from before. let me know if there are any particular changes.

> Reviewed 4 of 4 files at r1, 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-:-MzWUGUF2vo8xXtpvTES:b-6qke7o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart, @sjbarag, and @tbg)

___
*[-- commits, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWQrTdBtU2aexvrbYQ):*
nit: grammar
___
*[go.mod, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzR2wfxBq-hISjfUFZ5:-MzR2wfxBq-hISjfUFZ6:b4v6y24) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c9384ed64e786330c79c3a63dff5ddd5ca8a5c/go.mod#L136)):*
> ```XML
> 	github.com/shirou/gopsutil/v3 v3.21.12
> 	github.com/slack-go/slack v0.9.5
> 	github.com/spf13/afero v1.6.0
> ```

not sure what our dependency policy is re: backports but this approach may be undesirable for that reason....but if it was indirect before then the code was included anyway :shrug: 
___
*[pkg/ui/ui.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWTZg8EtpXEfY9OC42:-MzWTZg8EtpXEfY9OC43:bcj78a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fce48cbb111b993d0b2a2e55b9948d252127c65/pkg/ui/ui.go#L122)):*
> ```Go
> 	if HaveUI && Assets != nil {
> 		// Only compute hashes for UI-enabled builds
> 		err := httputil.ComputeEtags(Assets, etags)
> ```

is there any advantage to letting `ComputeEtags` return a map instead of having to pass one in? ah I guess you still want the empty map sitting here in the "no assets" situation for requests to pass through.
___
*[pkg/ui/ui.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWTGth3suxSb62oRS6:-MzWTGth3suxSb62oRS7:bp78jr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fce48cbb111b993d0b2a2e55b9948d252127c65/pkg/ui/ui.go#L128)):*
> ```Go
> 	}
> 
> 	handlerChain := httputil.EtagHandler(
> ```

nit: consider naming it `fileHandlerChain` for clarity, it's not all the endpoints, just the assets.
___
*[pkg/util/targz/targz.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWSq2r4lGcRc7onqHL:-MzWSq2r4lGcRc7onqHM:bex5s30) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c9384ed64e786330c79c3a63dff5ddd5ca8a5c/pkg/util/targz/targz.go#L47)):*
> ```Go
> 	fsys := afero.NewMemMapFs()
> 
> 	var fileCount int
> ```

what is the purpose of this counter?

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78978)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @rickystewart, @sjbarag, and @tbg)

___
*[go.mod, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzR2wfxBq-hISjfUFZ5:-Mz_u-CV3ZBmFXpZ7_x4:bl6au6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c9384ed64e786330c79c3a63dff5ddd5ca8a5c/go.mod#L136)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

not sure what our dependency policy is re: backports but this approach may be undesirable for that reason....but if it was indirect before then the code was included anyway :shrug: 
</blockquote></details>

I'll ask in #dev-inf w.r.t. to a backport, but I imagine it won't be an issue.  We gzip-compress assets in 22.1, but not in 21.2 so we should be able to drop this commit for that backport.
___
*[pkg/ui/ui.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWTZg8EtpXEfY9OC42:-Mz_uDod6AMn_4Y_ttZh:b18akpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fce48cbb111b993d0b2a2e55b9948d252127c65/pkg/ui/ui.go#L122)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there any advantage to letting `ComputeEtags` return a map instead of having to pass one in? ah I guess you still want the empty map sitting here in the "no assets" situation for requests to pass through.
</blockquote></details>

Yep — although I could easily declare the `etags` map as a `var` and assign it here?  Seems pretty even either way, so unless there are major objections I'll just keep it as-is.
___
*[pkg/util/targz/targz.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWSq2r4lGcRc7onqHL:-Mz_uoAQ2HO2eJKi9ojS:b-uwp61r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c9384ed64e786330c79c3a63dff5ddd5ca8a5c/pkg/util/targz/targz.go#L47)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

what is the purpose of this counter?
</blockquote></details>

I could have sworn we printed the number of discovered files, but perhaps that was some debugging code that I lost track of.  I'll remove it!

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78978)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @rickystewart, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-Mza05mi9nGFIJwtLnJd:-Mza05mi9nGFIJwtLnJe:bl1o55k) (no related file):*
Changes in patchset 2:

* Removed spurious `fileCount` var
* Renamed `handlerChain` -> `fileHandlerChain`
* Fixed grammar in commit "ui: use afero MemMapFS to expose …"

---
___
*[pkg/util/targz/targz.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-MzWSq2r4lGcRc7onqHL:-Mza00k27uZhXS6TOwnG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c9384ed64e786330c79c3a63dff5ddd5ca8a5c/pkg/util/targz/targz.go#L47)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

I could have sworn we printed the number of discovered files, but perhaps that was some debugging code that I lost track of.  I'll remove it!
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
> Reviewed 10 of 10 files at r3, 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78978)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @rickystewart, @sjbarag, and @tbg)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/78978#-Mza05mi9nGFIJwtLnJd:-MzoyhiW18oS7Da2JMxd:b-cxpm2) (no related file):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Changes in patchset 2:

* Removed spurious `fileCount` var
* Renamed `handlerChain` -> `fileHandlerChain`
* Fixed grammar in commit "ui: use afero MemMapFS to expose …"
</blockquote></details>

:lgtm: thx for the tweaks.

---

**Comment by sjbarag** [comment]
bors r=[dhartunian,tbg]

**Comment by sjbarag** [comment]
blathers backport 21.2 22.1

**Pull request merged**
