### PR TITLE
sql: switch to our forked yacc to prevent NTYPES error

### PR DESCRIPTION
**Pull request by tamird**
Makes a bunch of scripts stricter while I'm here.

This prevents a silent `go generate` failure in `sql/parser`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8957)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql_union.sh, line 13 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8957#-KQRwtxMjWVyREg663-Z:-KQRwtxMjWVyREg663-_:b4fei6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1526355134edfa111fb679af05d126f5730844/sql/parser/sql_union.sh#L13)):*
> ```Shell
> # compiler does not type check Go code.
> function type_check() {
>     ret=$(go tool yacc -o /dev/null -p sql sql.y)
> ```

This is done different in `develop`: https://github.com/cockroachdb/cockroach/blob/20f9815d20b6c4ac5787b2c59687580d7df70419/sql/parser/sql_union.sh#L15

The way here is arguably better since it's much shorter and simpler. Is there a good way to do git stuff here so that develop and/or master doesn't think it's missing a commit from the other?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8957)*

**Comment by tschottdorf** [comment]
The `develop` fix would still exit zero if the process exits nonzero but happens to returns something that matches the grep. We really want `set -o pipefail` in all of our scripts - too easy to forget.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1, 18 of 18 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8957#-:-KQS06kCVXySCrabyhoG:bnfp4nl)*

**Comment by tamird** [comment]
@mjibson nah, I'm going to have to deal with a conflict when I merge 'em next.

**Pull request merged**
