### PR TITLE
sql: support more than 1 result row in pg prepared tests

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5987)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice! Just one comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 484 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5a9bNcmA4B7NaG3hO:-KF5a9bNcmA4B7NaG3hP:1844587325) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L484)):*
Add a comment like `// Unexpected line. Get and print out the details.`

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5XfV6hJhPEmedhDuq:665391785) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
This is very unintuitive and seems kind of crazy, we are setting `dst[i]` to the address of a temporary variable of type `interface{}` which is set to the "zero" value `dst[i]`? I see this is an adaptation of what we already have above, but that seems equally crazy..

It would be a lot clearer if we just had two arrays `vals := make([]interface{}, len(cols)` and `ptrs := make([]*interface{}, len(cols));` initialized with `for i := range cols { ptrs[i] = &vals[i] }`. This applies to the existing code above as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-:-KF5_8sEY6Ei8Ya2Susr:822743356)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF5mdyK02FPlhpTtz_A:-1997805458) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
is this actually used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF5oXGxXx5oc85Y53Dt:-803151624) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
I must not understand your question. Yes, this is used below where we loop on `test.results`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 484 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5a9bNcmA4B7NaG3hO:-KF5oim10IrRy2-URgwC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L484)):*
Done.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5onTgphm2-9q1RNbU:-1358395946) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Sadly this doesn't work. The parameters to `rows.Scan` are `[]interface{}`, not `[]*interface{}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF5pv2erHL1BPger26a:-445218789) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
is `Results` ever called more than once on the same receiver? the change to use `append` is what I mean when I ask if "this" is being used.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5qTrp7YE791iRmfX3:-996899503) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
taking a reference to a `range` binding is definitely not going to do the right thing though. I wonder if `reflect.ValueOf` makes a copy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5sfHT5LW-s-aVbcYs:202565150) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Ah, right, it should work with`ptrs := make([]interface{}, len(cols));`. Initialization still the same `ptrs[i] = &vals[i]`

Then we can just use `vals` when using at the results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5tesgX4P1z6KJrvBN:1423461321) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Using:

```
dst = make([]interface{}, len(expected))
ptrs = make([]interface{}, len(expected))
for i := range dst {
	ptrs[i] = &dst[i]
}
if err := rows.Scan(ptrs); err != nil {
	t.Error(err)
}
```

Prints the error:

sql: Scan error on column index 0: destination not a pointer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF5uXJjmjEmJYQrLJUe:17653455) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Oh derp. needed `ptrs...`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF6-iUaKrl95hpXYiKD:-1740103788) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
I've been doing more work on this and any solution I try ends up with other problems. Currently with the one proposed above, `rows.Scan` doesn't know the type of the thing to marshal, since it's just a `*interface{}`. Thus, it must always marshal an int into an int64. Similarly, anytime a string is expected it uses a `[]uint8`. This creates confusion in the equality comparison code, which now has to take this stuff into account. I propose leaving things as they are because it works correctly and simplifying the code here results in more complication elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF68aLcjuFTXn2ThgZl:-1537271331) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
I added 2 tests that use Results multiple times and things are still working. I think you're rightly worried about setting `results` on `base` and having it affect other tests, but that doesn't seem to be happening.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF69HZpXsRyBYpAVb_j:1194239913) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
I wasn't really worried about that - I was just pointing out that this bit of functionality wasn't being used. Anyway, given the support for `Others()`, I'd probably revert this back to a simple setter rather than make the test changes you just made.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF69im-zHpitZEEEHrv:-959085052) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Since you're no longer taking a reference to a `range` variable, I think this is fine. I think you can make the code above (which currently uses reflect) the same as this, for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF670ngqMnnI7aIhFyU:-1528724859) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Ah, sorry, the existing code above is fine - it uses `d` which comes from `expected[i]`, not `dst[i]`. So there is no self-reference.

It's just the new code which is is crazy because `dst` references itself. Maybe just do `var d interface{}` instead of having `d` come from `dst`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6AxFTP6H91Qk4NL__:738832255) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
Is this line any different than `dst[i] = &d` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF6B9a6iLoOOvBn7HAQ:293613453) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
I think that is an important addition. I would have liked to use that in #5977 to verify more than one line of results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5mdyK02FPlhpTtz_9:-KF6Bo2Kfin32C1c2Ofa:-489118315) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L261)):*
Okay.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6Bovn9uhKU4Mdo5w9:1614709213) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
This is actually making a new pointer; it's not referring to `d` at all.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KF6BvF2Z1igSl0uCstm:-168915557) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Ah, the above code is actually making a pointer of a specific type. Ignore my suggestion to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6CtzXeZ_EWW6Zujmz:1671678981) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
Ah, right. In both cases we end up with a newly allocated pointer to something of `d`s type, but with the `reflect` version the thing we point to is zero (which is safer because if `Scan` doesn't actually set a value, we want the test to fail)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6FURR_Vn0TtzqeUpM:1330975999) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
`d`'s type is also known and concrete up here, but down below it's just `interface{}` - I'm not really sure why it's not OK to simply forgo the loop below and simply pass `dst...` into `Scan`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6Hyyl1hWNiH8wukgV:1498662810) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
`Scan` checks if each argument can be cast to `*interface{}` in which case it sets the target `interface{}` to something. So we need to initialize `dst[i]` to contain a valid pointer to an `interface{}`. The loop below works because `d` is a copy, it's as if we just did `dst[i] := &interface{}(nil)` (which would be clearer).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6Ji0nDQbzMlmKPZ_F:-1696109602) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
I think you want `new(interface{})` - if `Scan` sets the pointer's target (which is nil), well, that would NPE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 462 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF6AxFTP6H91Qk4NL_Z:-KF6LoxKgtj-wNklaUDz:-2053018471) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L462)):*
Right, forgot about `new`, that's what I was trying to do :)  I was trying to contract `var d interface{}; dst[i] = &d` in one line but it doesn't work as I wrote it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/pgwire_test.go, line 486 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-KF5XfV6hJhPEmedhDup:-KFAR988VuwLf924ORjq:-1066517862) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef13ebc16f3ef22b43778e9cdd842ba559416f/sql/pgwire_test.go#L486)):*
Changed to use `new(interface{})` which should be clear. I don't think we can change the one above, since it needs a specific type. LGTY'all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-:-KFASGVDgB4M46lmZDse:1417088721)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5987#-:-KFAVoPhd8fHfjeywlAJ:1417088721)*

**Pull request merged**
