### PR TITLE
release-23.1: sql/schemachanger: alter pk would temporarily disable secondary indexes

### PR DESCRIPTION
**Pull request by fqazi**
Backport 1/1 commits from #111313.

/cc @cockroachdb/release

---

Previously, when ALTER PRIMARY KEY was issued, the declarative schema changer would instantly move all existing indexes to VALIDATED. Meaning they would no longer be accessible for any read operations. This was problematic because query performance could degrade since the secondary indexes backing a table would be missing until a new secondary index was prepared. To address this, this patch adds a new rule inside the declarative schema changer that says for secondary index re-creates, we need to ensure that the new index is ready to take over before the old one is disabled.

Fixes: #111076

Release note (bug fix): ALTER PRIMARY KEY would incorrectly disable secondary indexes while new secondary indexes were being backfilled when using the declarative schema changer.

The second commit is focused on mixed version compatibility since we need this change to be backportable. It adds a flag into the state to prevent us from using this on states generated on older versions (i.e., they could have the secondary index disabled earlier).

Release justification: This fix addresses a severe performance regression with alter primary key, which could severely degrade concurrent workloads that need secondary indexes. The fix involved is fairly low risk and involves adding rules to correct the ordering of operations to avoid disabling the secondary index.

### CODE REVIEW

**Comment by rafiss** [comment]
With this new policy, should we still backport this? https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy

How severe do you consider this bug?

**Comment by fqazi** [comment]
@rafiss The performance tanking here would be pretty severe, so we should deal with this one. If someone does an ALTER PRIMARY KEY, their query workload could go from seconds to minutes because all the secondary indexes are disabled. We saw that in our internal testing, but it hasn't been hit by any customers yet or they simply aren't aware that this happened to them.

**Review by rafiss — COMMENTED** [review]
@fqazi could you answer the following in the PR comments? (questions are from https://cockroachlabs.atlassian.net/wiki/x/_YEuPg)

-   Are all of the changes protected via a flag or option, new syntax, an environment variable or default-disabled cluster setting?
    
-   What are the risks to backporting this change? Can the risks of backporting be mitigated? What are the risks to _not_ backporting?
    
-   Does this change _really_ need to be backported? Or can it reasonably wait until the next major release to be addressed?
    
-   Is this the smallest possible change that can be made?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113183#-:-NiaXCLm9HInhg3LW3fX:b-d16hxt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @jayshrivastava)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113183#-NiaWw6g0y4u3H7bS2Wn:-NiaWw6g0y4u3H7bS2Wo:b-tgsuhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf008f50c6a24214e97decfe5abb77fef61c756a/pkg/sql/schemachanger/scpb/elements.proto#L271)):*
> ```proto
>   // secondary index that we are trying to replace (this
>   // is done for primary key changes).
>   uint32 recreate_source_id = 4 [(gogoproto.customname) = "RecreateSourceIndexID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.IndexID"];
> ```

since this is a new proto field, do you know how this would behave in a mixed v23.1.11/v23.1.12 cluster?

**Comment by fqazi** [comment]
> @fqazi could you answer the following in the PR comments? (questions are from https://cockroachlabs.atlassian.net/wiki/x/_YEuPg)
> 
> * Are all of the changes protected via a flag or option, new syntax, an environment variable or default-disabled cluster setting?

There are no new settings.

> * What are the risks to backporting this change? Can the risks of backporting be mitigated? What are the risks to _not_ backporting?

The main risk is probably rollback scenarios, where the old version attempts to rollback an ALTER PRIMARY KEY with the new plan. The rules are less constrained on the old version, so this should be okay.

> * Does this change _really_ need to be backported? Or can it reasonably wait until the next major release to be addressed?

Sadly, the current ALTER PRIMARY KEY bug leads to a severe regression since concurrent queries will lose their secondary indexes until the PK backfill completes.

> * Is this the smallest possible change that can be made?

Yes, this modifies the planning rules to avoid disabling secondary indexes early by being more atomic.

> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113183#-:-NiaXCLm9HInhg3LW3fX:b-d16hxt)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @jayshrivastava)
> 
> _[`pkg/sql/schemachanger/scpb/elements.proto` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113183#-NiaWw6g0y4u3H7bS2Wn:-NiaWw6g0y4u3H7bS2Wo:b-tgsuhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf008f50c6a24214e97decfe5abb77fef61c756a/pkg/sql/schemachanger/scpb/elements.proto#L271)):_
> 
> > ```proto
> >   // secondary index that we are trying to replace (this
> >   // is done for primary key changes).
> >   uint32 recreate_source_id = 4 [(gogoproto.customname) = "RecreateSourceIndexID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.IndexID"];
> > ```
> 
> since this is a new proto field, do you know how this would behave in a mixed v23.1.11/v23.1.12 cluster?

In a mixed version state the old version will not use this field and generate the *old* bad plan. The new version if it doesn't see this field it will generate the same bad plan.

**Review by rafiss — APPROVED** [review]

**Pull request merged**
