### PR TITLE
spanconfig: re-write spanconfig.Splitter

### PR DESCRIPTION
**Pull request by irfansharif**
The earlier implementation relied on decoding keys in order to determine
precise split points. When plugging this library into the component
designed for tenant-side span config limiting (#77337, to address
\#70555), we realized it's not possible to grab a hold of type-hydrated
table descriptors (needed for decoding). This is because today it's
possible to GC type descriptors before GC-ing table descriptors that
refer to them. Given the integration point for this library was around
the GC job, we had to forego decoding routines.

Instead of computing the precise split keys, we can however compute how
many there are without having to look at keys at all. We

Consider our table hierarchy:

    table -> index -> partition -> partition -> (...) -> partition

Each partition is either a PARTITION BY LIST kind (where it can then be
further partitioned, or not), or a PARTITION BY RANGE kind (no further
partitioning possible). We can classify each parent-child link into two
types:

(a) Contiguous      {index, list partition} -> range partition
(b) Non-contiguous  table -> index, {index, list partition} -> list partition

- Contiguous links are the sort where each child span is contiguous with
  another, and that the set of all child spans encompass the parent's
  span. For an index that's partitioned by range:
```
    CREATE TABLE db.range(i INT PRIMARY KEY, j INT)
    PARTITION BY RANGE (i) (
      PARTITION less_than_five       VALUES FROM (minvalue) to (5),
      PARTITION between_five_and_ten VALUES FROM (5) to (10),
      PARTITION greater_than_ten     VALUES FROM (10) to (maxvalue)
    );
```
  With table ID as 106, the parent index span is `/Table/106/{1-2}`. The
  child spans are `/Table/106/1{-/5}`, `/Table/106/1/{5-10}` and
  `/Table/106/{1/10-2}`. They're contiguous; put together they wholly
  encompass the parent span.

- Non-contiguous links, by contrast, are when child spans are neither
  contiguous with respect to one another, nor do they start and end at
  the parent span's boundaries. For a table with a secondary index:
```
    CREATE TABLE db.t(i INT PRIMARY KEY, j INT);
    CREATE INDEX idx ON db.t (j);
    DROP INDEX db.t@idx;
    CREATE INDEX idx ON db.t (j);
```
  With table ID as 106, the parent table span is `/Table/10{6-7}`. The
  child spans are `/Table/106/{1-2}` and `/Table/106/{3-4}`. Compared to the
  parent span, we're missing `/Table/106{-/1}`, `/Table/106/{2-3}`,
  `/Table/10{6/4-7}`.

For N children:
- For a contiguous link, the number of splits equals the number of child
  elements (i.e. N).
- For a non-contiguous link, the number of splits equals N + 1 + N. For N
  children, there are N - 1 gaps. There are also 2 gaps at the start and end
  of the parent span. Summing that with the N children span themselves, we
  get to the formula above. This assumes that the N child elements aren't
  further subdivided, if they are (we can compute it recursively), the
  formula becomes N + 1 + Σ(grand child spans).

Computing split count this way does come with one down-side: we might be
overcounting. When comparing keys, we could for example recognize that
partition-by-list values are adjacent, therefore there's no "gap"
between them. We can also do this by potentially comparing encoded keys
with one other. We just didn't because it's more annoying code to write,
and over-counting here is more than fine for our purposes usages.

Release justification: non-production code
Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Most of the diff is just testdata code, the actual logic here is super tiny. PTAL.

**Comment by ajwerner** [comment]
Are we at all worried about the pain that will come with any eventual migration to change the computation? Like, how could you do it?

**Comment by irfansharif** [comment]
> Are we at all worried about the pain that will come with any eventual migration to change the computation? Like, how could you do it?

I'm not following, have an example? Like a migration that changes how table+partition descriptors are structured?

**Comment by irfansharif** [comment]
If you meant changing how we compute this value, then no I'm not worried. I'm imaging a tenant migration that iterates over all descriptors and seeds `system.span_count` with the newly-computed-value, and a cluster version gate to start using the new approach thereafter. If every schema change serializes over accesses to `system.span_count`, I think it's a vanilla migration to roll out. Is there some complexity here I'm missing?

**Comment by irfansharif** [comment]
If for some reason that too doesn't work or we're fearful of clobbering it with both kinds of mechanisms in play, we could always add a new column to hold the newer-mechanism-value and use the same rollout approach for existing descriptors we're using in #77337 -- i.e. scan through all descriptors and seed the initial count, and going forward start tracking `span_count` for subsequent schema change operations.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 8 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77639#-:-Mxr68POC1NULlIvGBDl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by irfansharif** [comment]
Thanks!

bors r+

**Pull request merged**
