### PR TITLE
roachtest: improvements to retry api

### LINKED ISSUE #105753: roachtest: allow commands to opt-out from retrying
Certain commands are supposed to run for a long period of time (several hours). In these cases, we don't want to retry the command if it fails with a 255 error, even if it's a legitimate SSH flake. If the command is retried, either other things will fail (due to state changes), or the entire test will timeout.

We should provide an API that gives the user the ability to opt-out of command retrying. One immediate application is commands that run workloads for several hours, such as `weekly/tpcc/headroom`, which runs `tpcc` for 96h. This type of error has caused a couple of flakes so far: #105304, #105747.

Jira issue: CRDB-29174

### PR DESCRIPTION
**Pull request by herkolategan**
SSH retries are implemented when executing commands via roachprod, transparent to the user. i.e. As a result, today, commands executed via `c.Run` retry automatically if the error has an exit code of `255` (ssh issue). 

In order to make this more configurable for the caller the following changes are introduced:

1. Implement an options struct to specify run options:
   * `install.RunOptions` can be constructed by specifying the nodes the operation intends to run on.
   * The options can be customised by calling the convenience `.With` methods.
2. Refactor existing options
   * Remove `install.RetryOpts` which contains `retry.Options` and `func(*RunResultDetails) bool` into separately specifiable options. This exposes the more familiar `retry.Options` directly to callers.
   * Expose `WithRetryOpts(...)` and `WithRetryFn(...)`
   * Set retry defaults in `c.Parallel` which are overridable by callers.

3. The existing API functions in `roachtest` have been left untouched for now, but will be updated to use the `RunOptions` struct in a follow-up PR.

The goal is to introduce the new API without changing any of the tests (via preserving the existing API). A future change will remove the old functions, and rename the new ones.

Follow up PRs to
- Remove custom retry logic in favour of roachprod retries
- Disable retries on certain long running tests such as `weekly/tpcc/headroom`
- Update the default roachprod ssh retry, which is enabled automatically
- Refactor `roachtest` calls to use the `RunOptions` struct in the `run` functions.

Epic: none
Release note: none
Fixes: #105753

### CODE REVIEW

**Review by DarrylWong — APPROVED** [review]
Feel free to wait for another review, but overall this looks good to me. Just one tiny typo and a few random thoughts. I think it would be nice to see a roachtest use `RunExt()` or any of the `Ext()` functions though. Could be as a followup, after we confirm that the default retryOpts behavior is indeed preserved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-:-Nie_dOP1oSzrJubeBwi:b-hmqall)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster/cluster_interface.go` line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiebZ9w7wIifQgsdCy0:-NiebZ9x9b5DbJc8Jiwv:b8yy5v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/cmd/roachtest/cluster/cluster_interface.go#L93)):*
> ```Go
> 	RunWithDetails(ctx context.Context, testLogger *logger.Logger, nodes option.NodeListOption, args ...string) ([]install.RunResultDetails, error)
> 
> 	RunWithDetailsExt(ctx context.Context, testLogger *logger.Logger, nodes option.NodeListOption, args []string, opts ...install.RunOption) ([]install.RunResultDetails, error)
> ```

No actionable comment here, just more wondering if it's confusing to anyone else when we use both `args` and `opts` in the same function. I see it's a fairly common pattern in the code so maybe just me.
___
*[`pkg/roachprod/install/cluster_synced.go` line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiecyAnDs7FnYowEXFS:-NiecyAnDs7FnYowEXFT:b-w4fyxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/cluster_synced.go#L121)):*
> ```Go
> // substrings, in which cases retries are unlikely to help.
> var noScpRetrySubstrings = []string{"no such file or directory", "permission denied", "connection timed out"}
> var defaulSCPShouldRetryFn = func(res *RunResultDetails) bool {
> ```

Looks like the t got deleted on accident :anguished:   

Should be `defaultSCPShouldRetryFn`
___
*[`pkg/roachprod/install/cluster_synced.go` line 1275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiegNjs7RZM0URKTJEg:-NiegNjs7RZM0URKTJEh:b-1n132b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/cluster_synced.go#L1275)):*
> ```Go
> ) ([]RunResultDetails, error) {
> 	display := fmt.Sprintf("%s:%v: %s", c.Name, nodes, title)
> 	defaultOpts := []RunOption{WithDisplay(display), WithFailSlow(true)}
> ```

What happens here if opts contains `WithFailSlow(false)`? I think it should preserve `WithFailSlow(false)` since it would be added second, but maybe worth avoiding this behavior all together?
___
*[`pkg/roachprod/install/run_options.go` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-Nie_VtQ0YfrdS5z3HVn:-Nie_VtQ0YfrdS5z3HVo:b-2aquo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/run_options.go#L18)):*
> ```Go
> 	// RetryOptions are the retry options
> 	RetryOptions *retry.Options
> 	// ShouldRetryFn is only applciable when RetryOptions is not nil
> ```

nit: applicable
___
*[`pkg/roachprod/install/run_options.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-Nie_LDE8NynYV7hiaYl:-Nie_LDE8NynYV7hiaYm:b-myw4yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/run_options.go#L28)):*
> ```Go
> 	// behaviour is to exit immediately on the first error, in which case the
> 	// slice of ParallelResults will only contain the one error result.
> 	// Named as such to make clear that this is not eneabled by default.
> ```

nit: enabled

**Review by RaduBerinde — COMMENTED** [review]
Instead of `RunOption`, I would pass a `RunOptions` struct directly, and I'd move the node list inside `RunOptions`.
I would make a `RunOptions` constructor `OnNodes(nodes)` and make the other options methods that return a RunOptions so you can do `OnNodes(nodes).WithRetry().WithConcurrency()`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-:-Niev_5X6uBJCsUbxrO2:b-p8x3ac)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

**Review by herkolategan — COMMENTED** [review]
@RaduBerinde I have taken over this PR so unfortunately I do not have full context of the reasoning behind the original design. It seems to stem from the fact that the base run functions in `roachprod.go` (`Run`, and `RunWithDetails`) have different "defaults" that are still allowed to be overridden (@DarrylWong pointed out some possible ambiguity in relation to that). As well as trying to preserve the call footprint to some degree by using variadic args.

But I would prefer if we didn't have the `Ext` functions in `roachtest` to try and support multiple variadic function scenarios. I've adapted the solution to work with an options struct, but it had small caveats, which was to support a bool `FailSlow` with an overridable default value (now changed to `FailOption` so it's clear when it's specifically specified).

Changes were added as a new commit to preserve the previous approach if need be.

TC Run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12607959

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-:-NiicjCs8FnZV_hxekD5:b-4m72z1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

___
*[`pkg/roachprod/install/cluster_synced.go` line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiecyAnDs7FnYowEXFS:-NiifHMYACHYaBfSa6zz:bhmhk5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/cluster_synced.go#L121)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Looks like the t got deleted on accident :anguished:   

Should be `defaultSCPShouldRetryFn`
</blockquote></details>

Nice catch! Done.
___
*[`pkg/roachprod/install/cluster_synced.go` line 1275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiegNjs7RZM0URKTJEg:-NiifaWlC-jsNP0JbJu-:blxfmk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/cluster_synced.go#L1275)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

What happens here if opts contains `WithFailSlow(false)`? I think it should preserve `WithFailSlow(false)` since it would be added second, but maybe worth avoiding this behavior all together?
</blockquote></details>

I'll revisit this in addition to the changes Radu requested.
___
*[`pkg/roachprod/install/run_options.go` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-Nie_VtQ0YfrdS5z3HVn:-NiifSOe6xHszKGxD_lu:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/run_options.go#L18)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: applicable
</blockquote></details>

Thanks! Done.
___
*[`pkg/roachprod/install/run_options.go` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-Nie_LDE8NynYV7hiaYl:-NiifXxA5PArrQzB4d44:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/roachprod/install/run_options.go#L28)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

nit: enabled
</blockquote></details>

Thanks! Done.
___
*[`pkg/cmd/roachtest/cluster/cluster_interface.go` line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-NiebZ9w7wIifQgsdCy0:-Niie_pOENDofeCDxuMF:b-s0t4ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda2860e7a1e5b817cd20361f838851d5f59e132/pkg/cmd/roachtest/cluster/cluster_interface.go#L93)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

No actionable comment here, just more wondering if it's confusing to anyone else when we use both `args` and `opts` in the same function. I see it's a fairly common pattern in the code so maybe just me.
</blockquote></details>

I can see how it can be confusing, and it's maybe a side effects of shortening names, rather than saying `commandLineArguments` and `runOptions`. But generally the `args` here refer to command line arguments that is executed on the target nodes. And the opts are options that relate to how the command is executed.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

I would update the description of the PR with the newer design so it's accurate when someone looks at it later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-:-Nj9APwz-D4SqENJU47b:b-gofoqi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

**Review by herkolategan — COMMENTED** [review]
Good point, updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112411#-:-NjHeb2UBoRoXhqv_ahm:b-clh693)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @renatolabs, and @srosenberg)

**Comment by herkolategan** [comment]
bors r=raduberinde,darrylwong

**Pull request merged**
