### PR TITLE
parser: add READ COMMITTED isolation level

### LINKED ISSUE #100142: sql: support parsing of weak isolation levels
We currently map all isolation levels to Serializable in the SQL grammar:
https://github.com/cockroachdb/cockroach/blob/476cd8522cc658d39a3f43a7a64dcbd7b0aeba57/pkg/sql/parser/sql.y#L6846-L6866

We'll need to change this to support statements like:
```sql
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- or
BEGIN; SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- or
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
```

Jira issue: CRDB-26561

Epic CRDB-26545

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/100142

The parser will now accept BEGIN and SET TRANSACTION statements that specify this isolation level.

No release note yet, since this is just parsing, and a later commit that implements the functionality will include a release note.

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103435#-:-NV_Ka6o0TfTSX4FHNBH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by chengxiong-ruan — APPROVED** [review]

**Review by nvb — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103435)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/parser/sql.y` line 6689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103435#-NV_MIDWBalNC0Qoqru8:-NV_MIDWBalNC0Qoqru9:bfh6roh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be822ea5ebf041057de216be59ed37045ae8937/pkg/sql/parser/sql.y#L6689)):*
> ```Yacc
> // SET [SESSION] <var> { TO | = } <values...>
> // SET [SESSION] TIME ZONE <tz>
> // SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { READ COMMITTED | SERIALIZABLE }
> ```

While we're here, do we also want to add support back for SNAPSHOT (and REPEATABLE READ, which we'll eventually map to SNAPSHOT)? We can continue mapping those both to Serializable above the parser.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103435)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/parser/sql.y` line 6689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103435#-NV_MIDWBalNC0Qoqru8:-NVaCPgN4jx-R2DoLK95:bgz2a1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be822ea5ebf041057de216be59ed37045ae8937/pkg/sql/parser/sql.y#L6689)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

While we're here, do we also want to add support back for SNAPSHOT (and REPEATABLE READ, which we'll eventually map to SNAPSHOT)? We can continue mapping those both to Serializable above the parser.
</blockquote></details>

yeah, let's do it. i will do it separately, since i want to first merge in the logic for storing the isolation level in the transaction.  i think that layer would be a good place to add a setting that determines if SNAPSHOT is allowed, or just treated as serializable.

**Comment by rafiss** [comment]
tftr!

bors r=nvanbenschoten,michae2,chengxiong-ruan

**Pull request merged**
