### PR TITLE
*: Build APIv2 spec using go-swagger, annotate endpoints

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds a dependency on `go-swagger/go-swagger`, and
uses it as part of `make generate` to regenerate the swagger
spec in `docs/generated/swagger/spec.json`, whenever
one of the APIv2 files in `pkg/server/` are changed.

The spec, once generated, can be served as docs using
the command:

    bin/swagger serve -p 8080 ./docs/generated/swagger/spec.json

Also adds related annotations to `pkg/server/api*.go` to populate
said spec.

Part of #55947 , and the docs story around it.

Release note (general change): Add docs for api v2 endpoints.
Release note (build change): Adds go-swagger dependency, updates
Makefile to call it to rebuild spec in docs/generated/swagger/
which will eventually be used for API docs.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:clap: :clap: :clap: 

LGTM

you may want to backport this too

> Reviewed 4 of 4 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62560#-:-MWdAqG53_aepo9cr6WF:bnt23pu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @itsbilal)

___
*[docs/generated/swagger/spec.json, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62560#-MWdAhA16y7FVh40mQzB:-MWdAhA16y7FVh40mQzC:b9lbgks) ([raw file](https://github.com/cockroachdb/cockroach/blob/66acfc55369892dfa9e1881e9085b500a355a08f/docs/generated/swagger/spec.json#L23)):*
> ```JSON
>     "/health/": {
>       "get": {
>         "description": "Helper endpoint to check for node helath. If `ready` is true, it also checks\nif this node is fully operational and ready to accept SQL connections.\nOtherwise, this endpoint always returns a successful response (if the API\nserver is up, of course).",
> ```

node helath -> node health

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62560#-:-MWdqw4p7k9EPssfBmEf:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[docs/generated/swagger/spec.json, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62560#-MWdAhA16y7FVh40mQzB:-MWdqx46EAZNpO8I3mW9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66acfc55369892dfa9e1881e9085b500a355a08f/docs/generated/swagger/spec.json#L23)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

node helath -> node health
</blockquote></details>

Done.

**Comment by itsbilal** [comment]
TFTR!

bors r=knz

**Pull request merged**
