### PR TITLE
streamingccl: support rolling back to a timestamp on job cancel

### LINKED ISSUE #57404: streaming: ingestion job to rollback to resolved timestamp OnFailOrCancel
Once the ingestion job is maintaining its ingested timestamp (the low-watermark resolved timestamp across all processors, see https://github.com/cockroachdb/cockroach/issues/57400), the job should be able to rollback to this timestamp when the job is cancelled or fails.

The job will perform a `RevertRange` request over the entire keyspace on which it has been ingesting. After this change, the ingestion job should be able to ingest a stream and leave the cluster in a consistent state.

### PR DESCRIPTION
**Pull request by pbardea**
Stream ingestion jobs can now rollback to the high watermark timestamp
stored in their progress field.

The progress field is not yet updated, but is expected to be updated
based on the output of the frontier processor.

Closes https://github.com/cockroachdb/cockroach/issues/57404.

Release note: None

### CODE REVIEW

**Review by adityamaru — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/ccl/streamingccl/stream_ingestion_job.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmSCJaExKWweWe4VyF:-MQmSCJaExKWweWe4VyG:b-23yugl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/ccl/streamingccl/stream_ingestion_job.go#L56)):*
> ```Go
> 
> 	// Plan and run the DistSQL flow.
> 	// TODO: Updates from this flow need to feed back into the job to update the
> ```

should be addressed in https://github.com/cockroachdb/cockroach/pull/58672
___
*[pkg/ccl/streamingccl/stream_ingestion_job.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmS8Hu3XC2rpV2kA5O:-MQmS8Hu3XC2rpV2kA5P:bwtql37) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/ccl/streamingccl/stream_ingestion_job.go#L93)):*
> ```Go
> 	highWaterMark := s.job.Progress().Details.(*jobspb.Progress_StreamIngest).StreamIngest.HighWater
> 	var b kv.Batch
> 	b.AddRawRequest(&roachpb.RevertRangeRequest{
> ```

should we set the TBI optimization to true?
___
*[pkg/jobs/jobspb/jobs.proto, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmSYP-2LoM7Bs4r66L:-MQmSYP-2LoM7Bs4r66M:b-4j81qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/jobs/jobspb/jobs.proto#L89)):*
> ```protobuf
> 
> message StreamIngestionProgress {
>   util.hlc.Timestamp high_water = 1 [(gogoproto.nullable) = false];
> ```

in https://github.com/cockroachdb/cockroach/pull/58672 I've just used https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobspb/jobs.proto#L576. This is what Changefeed uses. I don't feel strongly either way, just calling it out.
___
*[pkg/jobs/jobspb/jobs.proto, line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmTuxWCGehEnyLrDzT:-MQmTuxX9ojlrI5L0aMp:b-z2p9zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/jobs/jobspb/jobs.proto#L576)):*
> ```protobuf
>     SchemaChangeGCDetails schemaChangeGC = 21;
>     TypeSchemaChangeDetails typeSchemaChange = 22;
>     StreamIngestionDetails streamIngesiton = 23;
> ```

nit: streamIngestion

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/streamingccl/stream_ingestion_job.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmSCJaExKWweWe4VyF:-MQmwQHeA2QK4a1s6ARN:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/ccl/streamingccl/stream_ingestion_job.go#L56)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

should be addressed in https://github.com/cockroachdb/cockroach/pull/58672
</blockquote></details>

:+1: 
___
*[pkg/ccl/streamingccl/stream_ingestion_job.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmS8Hu3XC2rpV2kA5O:-MQmwU-33kP23bg86qjP:b-taqnoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/ccl/streamingccl/stream_ingestion_job.go#L93)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

should we set the TBI optimization to true?
</blockquote></details>

Yep! Done.
___
*[pkg/jobs/jobspb/jobs.proto, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmSYP-2LoM7Bs4r66L:-MQmwVyK2ohIbzGbECmu:b-5c7kmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/jobs/jobspb/jobs.proto#L89)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

in https://github.com/cockroachdb/cockroach/pull/58672 I've just used https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobspb/jobs.proto#L576. This is what Changefeed uses. I don't feel strongly either way, just calling it out.
</blockquote></details>

Ah, good call. I'm still going to include the empty progress details to match the other jobs but will update to use this.
___
*[pkg/jobs/jobspb/jobs.proto, line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58693#-MQmTuxWCGehEnyLrDzT:-MQmwakx4Ej7llwGmsFT:bt8gcjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f5625f99eac21b3a96a1afac86264dc25942364/pkg/jobs/jobspb/jobs.proto#L576)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: streamIngestion
</blockquote></details>

Thanks for catching! Updated.

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58693)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by pbardea** [comment]
TFTR!
bors r=adityamaru

**Comment by pbardea** [comment]
This needed a rebase after the proto changes.
bors r=adityamaru

**Comment by pbardea** [comment]
bors r=adityamaru

**Pull request merged**
