### PR TITLE
rfcs: new RFC and tech note about time series for tenants

### PR DESCRIPTION
**Pull request by knz**
RFC text: https://github.com/knz/cockroach/blob/20220821-tenant-timeseries/docs/RFCS/20220821_tenant_timeseries.md

Tech note: https://github.com/knz/cockroach/blob/20220821-tenant-timeseries/docs/tech-notes/timeseries.md

Release justification: docs only change

Epic: CRDB-18797

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Great work on the tech note and proposal

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-:-NA5QJzC11xO5P5_Ncqi:b-xy2h54)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA56rO_3fWkz4ZLjpRc:-NA56rO_3fWkz4ZLjpRd:b3na3yo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L249)):*
> ```Markdown
>   - etc.
> 
>   They will also be suffixed with the SQL instance ID, for example:
> ```

Thinking about this in a DB Console user context - do you envision a charts page where we allow secondary tenant users to dimension metrics by SQL instance ID? Or instead, to "hide" the concept of multiple SQL instances via aggregations? 



_Code quote:_
```Markdown
 They will also be suffixed with the SQL instance ID, for example:
```
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA57cPwCxGJSX_h3Fpa:-NA57cPwCxGJSX_h3Fpb:bb9olye) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L259)):*
> ```Markdown
> the SQL instance ID and node ID will match exactly and there will be no change in cardinality.
> 
> ## Automatic classification of metrics
> ```

Thanks for addressing this! 



_Code quote:_
```Markdown
## Automatic classification of metrics
```
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA57qPh1FuusLfBiBSV:-NA57qPh1FuusLfBiBSW:b-akipyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L277)):*
> ```Markdown
> 
> We will introduce the ID as prefix only for metrics defined in the 2nd
> registry (as explained below), leavint hose from the 1st registry unchanged.
> ```

nit: typo - "leaving those"



_Suggestion:_
```Markdown
leavint hose
```
___
*[`docs/tech-notes/timeseries.md` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA4zCNH6RtQy5Dv3Y_z:-NA4zCNH6RtQy5Dv3Ya-:b-mgy928) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/tech-notes/timeseries.md#L1)):*
> ```Markdown
> # The internal time series database (tsdb)
> ```

This is a wonderful piece of community service you've done writing this - thank you so much!



_Code quote:_
```Markdown
# The internal time series database (tsdb)
```

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5OquG-3vojNISMO0B:-NA5OquHCOSt9xNrorBV:b-prh6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L141)):*
> ```Markdown
> 
> 2. then, even if hypothetically we did start the tsdb collector,
>    we would then see *ambiguity in all the SQL timeseries*.
> ```

Do we have a sense for _how_ significant of a problem this will turn out to be in practice?  I'd think that the number of SQL statements being run from the system/admin tenant would be a small fraction of those executed in the app tenant.  With that in mind, are there specific examples you can cite where the UX is confusing?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5PNpjDZm96Vh-5M4P:-NA5PNpjDZm96Vh-5M4Q:boxi93b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L165)):*
> ```Markdown
>    data points.
> 
> ## Objective 2: desired semantics
> ```

I found it a bit confusing that the objectives were split by the "Problems with..." section.  Does it make sense to cover the "Problems with..." topic first, and then cover the two objectives back-to-back?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5PvvNC3feCufzSakB:-NA5PvvNC3feCufzSakC:b-zgvzfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L174)):*
> ```Markdown
>   able to see historical metrics for the app tenant's SQL layer.
> 
> - By default, users accessing the DB Console for the application
> ```

Can you explain the motivation for this one?  I'd think that users access the DB Console would need _some_ way to access the storage metrics, but that method could be to toggle to the system tenant and view them there.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5Q7fZ4f6BxryKGrTh:-NA5Q7fZ4f6BxryKGrTi:ba6teu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L176)):*
> ```Markdown
> - By default, users accessing the DB Console for the application
>   tenant must be able to see the storage metrics (KV-level) too,
>   however an option must exist to revoke this access: in CC Dedicated,
> ```

CC Dedicated _and_ Serverless?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5RC-x2A1jcHFJpzgH:-NA5RC-x2A1jcHFJpzgI:buvud4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L201)):*
> ```Markdown
> - we will introduce a tenant ID prefix for only those timeseries that
>   are scoped to a tenant (i.e. KV-level timeseries will not be
>   prefixed, but SQL-level timeseries will).
> ```

Can you explain the motivation for not adding a tenant prefix for KV-level timeseries data?  Is it because it's largely unnecessary?  Helps with upgrades?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6GOfn-S2yBvx2omph:-NA6GOfn-S2yBvx2ompi:boj72fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L343)):*
> ```Markdown
> 
> - SQL metrics will be exported separately, one per tenant, with the
>   tenant *name* (not ID) included as a metric label
> ```

Can you add a comment here as to why we're going with tenant name and not tenant ID?  Is there any concern down the road that we may have to change the name and this will create an upgrade challenge?  Alternatively, if we ever allow _true_ multi-tenancy (or even one additional tenant) within a shared process, will each tenant have to be named?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6I6wyEfiupWxeGKzz:-NA6I6wyEfiupWxeGL--:bwu6im9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L459)):*
> ```Markdown
>   matches the tenant ID prefix in the timeseries name.
> 
> The capability WRITE_TENANT_TIMESERIES will not be granted for CC
> ```

Does this imply that for Serverless, there will continue to be no SQL metrics written for tenants?  If so, do you see this as a temporary state?  Or do you think that long-term we'd not want to generate SQL metrics for tenants?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6JERk7QJtBJ7CqNTn:-NA6JERk7QJtBJ7CqNTo:b-jggtev) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L616)):*
> ```Markdown
> It also introduces the option (but not the mandate) to make separate
> SQL pods able to record their timeseries in KV, via the new capability
> WRITE_TENANT_TIMESERIES.
> ```

Is this also required to make this proposal work for Serverless?  If so, perhaps you want to motivate the need for this further by leaning on that additional use case.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5RC-x2A1jcHFJpzgH:-NA6L0E-CBY1PUmCHJXI:b3hucpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L201)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you explain the motivation for not adding a tenant prefix for KV-level timeseries data?  Is it because it's largely unnecessary?  Helps with upgrades?
</blockquote></details>

What would it mean to add a tenant prefix for kv-level timeseries data? There are *some* kv metrics would could be viewed as tenant scoped, in which case, we could publish tenant-level timeseries data with such a prefix, but the majority of KV metrics don't map nicely to tenants. 
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6GOfn-S2yBvx2omph:-NA6LhHR5Mq2Qr43d7Lw:b-pq4jt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L343)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you add a comment here as to why we're going with tenant name and not tenant ID?  Is there any concern down the road that we may have to change the name and this will create an upgrade challenge?  Alternatively, if we ever allow _true_ multi-tenancy (or even one additional tenant) within a shared process, will each tenant have to be named?
</blockquote></details>

We could choose to export use both name and ID. It would not affect the cardinality of metrics and it would allow a future where we export tenant metrics without a tenant_name label. Note that kvserver already exports metrics with a `tenant_id` label to prometheus 
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 641 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6M-Ok84cpdXOyWvu_:-NA6M-Ok84cpdXOyWvua:bnkpb2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L641)):*
> ```Markdown
> # Unresolved questions
> 
> N/A
> ```

I think we may as well list metrics related to non-app secondary tenants as unresolved.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajstorm, @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5OquG-3vojNISMO0B:-NA8jOMx1moNB7JpABTB:bgggi5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L141)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we have a sense for _how_ significant of a problem this will turn out to be in practice?  I'd think that the number of SQL statements being run from the system/admin tenant would be a small fraction of those executed in the app tenant.  With that in mind, are there specific examples you can cite where the UX is confusing?
</blockquote></details>

If a customer comes to us and says "I didn't run this statement, and yet the counter is increasing, how can I even trust this counter?" what do you propose we tell them?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5PvvNC3feCufzSakB:-NA8jkAuDhrcG42y4T28:bvmyac2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L174)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can you explain the motivation for this one?  I'd think that users access the DB Console would need _some_ way to access the storage metrics, but that method could be to toggle to the system tenant and view them there.
</blockquote></details>

Good Q. After all I too was personally where you are here.

1) The proposal here stems from a strong request from the O11y team / PM to offer a DB console experience that's a "drop in" replacement for the single-tenancy experience. They think that _mandating_ that toggle for users who are evolving from single-tenancy is adding too much friction.

2) We've been requested to offer CC Dedicated users the ability to view KV-level metrics, as some of these metrics can be used for performance optimizations. Since Dedicated users won't have access to system tenant db console, we need to achieve this in a different way.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5Q7fZ4f6BxryKGrTh:-NA93v1-5WKbbGFfPrhz:bm86lan) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L176)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

CC Dedicated _and_ Serverless?
</blockquote></details>

Both indeed.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5RC-x2A1jcHFJpzgH:-NA93y4F60m92ud00Rt-:b-r34hfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L201)):*
> There are some kv metrics would could be viewed as tenant scoped

Andrew that's interesting, do you have some examples in mind?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA56rO_3fWkz4ZLjpRc:-NA944jbAP1SZn3mrD69:buk4in5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L249)):*
> we allow secondary tenant users to dimension metrics by SQL instance ID? 

I was hoping that we would trick the DB console into considering the SQL instance ID as a node ID, without any change in the code. And then the UX would be the same with SQL instances as nodes currently.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA57qPh1FuusLfBiBSV:-NA94NCT5_LoSQgJS8Ia:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L277)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: typo - "leaving those"
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajstorm, @ajwerner, @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6I6wyEfiupWxeGKzz:-NA99ZsjDqOTRltGfFFQ:baj1ako) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L459)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does this imply that for Serverless, there will continue to be no SQL metrics written for tenants?  If so, do you see this as a temporary state?  Or do you think that long-term we'd not want to generate SQL metrics for tenants?
</blockquote></details>

I have no opinion on this. The RFC aims to introduce the mechanisms, it's then for PM to decide how to use them.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 616 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6JERk7QJtBJ7CqNTn:-NA99hfLAEv0VTKkiBFS:bslogh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L616)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is this also required to make this proposal work for Serverless?  If so, perhaps you want to motivate the need for this further by leaning on that additional use case.
</blockquote></details>

I don't think we have pressure either way, so I don't think the RFC needs to mention that here.

(A RFC's purpose is not to discuss product-level trade-offs.)
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 641 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6M-Ok84cpdXOyWvu_:-NA99qVZCtoiCyTs7T0Q:b-lbut5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L641)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think we may as well list metrics related to non-app secondary tenants as unresolved. 
</blockquote></details>

What do you mean?

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajwerner, @andreimatei, @dhartunian, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5OquG-3vojNISMO0B:-NAPk8uy8Bor_coVepua:b-d479l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L141)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If a customer comes to us and says "I didn't run this statement, and yet the counter is increasing, how can I even trust this counter?" what do you propose we tell them?
</blockquote></details>

Yeah, I could see how it could be confusing from an "app tenant" perspective once SH/Dedicated customers start internalizing the separation of roles between the system and app tenants.  My question was more around the short term confusion for early adopters of the UA who haven't yet switched mindsets to an isolated world.  
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5PvvNC3feCufzSakB:-NAPkvMP4WI0JMMeyZGl:b-vjqtl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L174)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Good Q. After all I too was personally where you are here.

1) The proposal here stems from a strong request from the O11y team / PM to offer a DB console experience that's a "drop in" replacement for the single-tenancy experience. They think that _mandating_ that toggle for users who are evolving from single-tenancy is adding too much friction.

2) We've been requested to offer CC Dedicated users the ability to view KV-level metrics, as some of these metrics can be used for performance optimizations. Since Dedicated users won't have access to system tenant db console, we need to achieve this in a different way.
</blockquote></details>

Interesting.  I was unaware of (1), and didn't see it in my last review of the DB Console design for UA.  Is this notion formalized somewhere?  (2) is new to me too, but makes sense.   
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5RC-x2A1jcHFJpzgH:-NAPlQqi8S8sbGcvJJbN:bn1z848) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L201)):*
> What would it mean to add a tenant prefix for kv-level timeseries data? 
I was just thinking that there might be value to prefixing KV metrics with 0, to denote that they were emitted by the system tenant.  Are there any benefits to being explicit here instead of implicit?
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6GOfn-S2yBvx2omph:-NAPlxS37Cj4nBqporOF:buamv83) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L343)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We could choose to export use both name and ID. It would not affect the cardinality of metrics and it would allow a future where we export tenant metrics without a tenant_name label. Note that kvserver already exports metrics with a `tenant_id` label to prometheus 
</blockquote></details>

That SGTM.  I do worry that _requiring_ a name could be fragile.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6I6wyEfiupWxeGKzz:-NAPmCpz2tjF6NDGIbP-:b-8iypoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L459)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I have no opinion on this. The RFC aims to introduce the mechanisms, it's then for PM to decide how to use them.
</blockquote></details>

That makes sense.  We might want to soften the language here to say "...will not _initially_ be granted for CC Serverless tenant, _but may be granted at some point down the road_".

**Review by dhartunian — COMMENTED** [review]
Added some high level comments. I'm in disagreement about whether we should do this.

I understand the motivation to:
1. provide a path independent of obs service
2. cover the scenario where sql runs in a separate process in dedicated
but I'm not convinced that those are strong enough requirements given our limited time available.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-:-NApdDn-9qOeecDE7vzZ:b-9pwurz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajstorm, @ajwerner, @andreimatei, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5OquG-3vojNISMO0B:-NApa5n7BcIfbbuMTDUr:b-gtkpd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L141)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Yeah, I could see how it could be confusing from an "app tenant" perspective once SH/Dedicated customers start internalizing the separation of roles between the system and app tenants.  My question was more around the short term confusion for early adopters of the UA who haven't yet switched mindsets to an isolated world.  
</blockquote></details>

We currently have this behavior from a workload vs system perspective and I am not aware that this is a source of confusion for customers.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5PvvNC3feCufzSakB:-NApadb83it7Ihhp7trr:b-5r7z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L174)):*
> The proposal here stems from a strong request from the O11y team / PM to offer a DB console experience that's a "drop in" replacement for the single-tenancy experience. They think that mandating that toggle for users who are evolving from single-tenancy is adding too much friction.

I can understand this desire to have the metrics there by default but I assumed this would be done through access to all the global metrics, instead of by making separate tenant metrics for SQL stuff.
 
> We've been requested to offer CC Dedicated users the ability to view KV-level metrics, as some of these metrics can be used for performance optimizations. Since Dedicated users won't have access to system tenant db console, we need to achieve this in a different way.

This can be accomplished by allowing tsdb access for the app tenant.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NAp_DF8-wyuLtpbXsr_:-NAp_DF8-wyuLtpbXsra:byl76ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca628733837c7e701458c7fd1f19acbfc7319ea8/docs/RFCS/20220821_tenant_timeseries.md#L19)):*
> ```Markdown
>   (Tenant timeseries storage would not be enabled
>   in CC Serverless, but it would be in Self-hosted
>   and CC Dedicated for the time being.)
> ```

I am not on the same page with you about this project.
My thinking was that multi-tenant tsdb storage was not something we should do since it complicates an aging timeseries subsystem that we want to reduce reliance on instead of continue extending.

My expectation:
TSDB should continue to work as-is and tenants should gain access to query it through the capabilities subsystem.
Dedicated clusters with multiple tenants *do not get per-tenant metrics in tsdb*.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NApaSQq6HWBN9IiyPyp:-NApaSQq6HWBN9IiyPyq:b-gpnw91) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca628733837c7e701458c7fd1f19acbfc7319ea8/docs/RFCS/20220821_tenant_timeseries.md#L163)):*
> ```Markdown
>    This means that when DB Console is opened for the application
>    tenant, it cannot even call the `/ts/db` operation to retrieve
>    data points.
> ```

I assumed this would be achieved via tenant capabilities to query the "global" tsdb.
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 625 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NApd1Ys8PdNPKhssR9u:-NApd1Ys8PdNPKhssR9v:bden3y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca628733837c7e701458c7fd1f19acbfc7319ea8/docs/RFCS/20220821_tenant_timeseries.md#L625)):*
> ```Markdown
> 
> The main alternative is “do nothing”, but this will result in a UX
> regression when a CC Dedicated/SH user migrates to multi-tenancy.
> ```

The option of keeping a global tsdb and letting tenants access the whole thing should be considered here.

**Review by ajwerner — COMMENTED** [review]
Sorry for not publishing these comments when I typed them over a month ago. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-:-NFFW9638vMd3jUyjBQE:bitobsf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @ajstorm, @andreimatei, and @knz)

___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA5RC-x2A1jcHFJpzgH:-NA9jyumDDvp1ruJQTv5:b-9r716u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L201)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> There are some kv metrics would could be viewed as tenant scoped

Andrew that's interesting, do you have some examples in mind?
</blockquote></details>

The kvserver exports per-tenant metrics to prometheus for storage [here](https://github.com/cockroachdb/cockroach/blob/61e541fa8bbb08e29541cf98f881905b791ab239/pkg/kv/kvserver/metrics.go#L1917-L1944) and rate-limiting [here](https://github.com/cockroachdb/cockroach/blob/61674bc51ae20005b9fde0bd548c4c4a4f2e9e1c/pkg/kv/kvserver/tenantrate/metrics.go#L23-L29). Those are the only per-tenant metrics we track. 
___
*[`docs/RFCS/20220821_tenant_timeseries.md` line 641 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86524#-NA6M-Ok84cpdXOyWvu_:-NA9kP4Z9eWf4dbZ-azf:b4h4qaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a214db5e30b347766422ec173f2e6882282604da/docs/RFCS/20220821_tenant_timeseries.md#L641)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

Above you state that the RFC doesn't take a position on whether secondary tenant sql pods should write metrics to the internal timeseries database. If they were to, we'd need to figure out the cost-control and fairness aspects of that RPC. It feels like you could add something down here about how secondary tenants in serverless and their interactions with the timeseries database remains unresolved.

**Comment by knz** [comment]
@aadityasondhi as we discussed, I just added a commit into the branch to simplify/reduce the implementation sections to not be too detailed. Here are the next steps:

1. copy the file into a new PR, same title, new date.
2. keep the same motivations/objectives.
3. update the implementation section to sketch how you did the work.
4. add some notes in the impl section to refer to what has not been done yet (foremost, the ability for secondary tenants to query the system's metrics but not that of other tenants)
5. update the summary at the top.

When you have the new PR number, feel free to add a link to it here, so we can merge this PR (with the old RFC).

**Comment by knz** [comment]
Note to self (or maybe for you Aaditya) - we need to file a followup issue to change the code to:

- make tenants able to observe their own timeseries without a capability
- make the new capability control access to system-wide metrics by a tenant (but not that of other tenants)

**Comment by knz** [comment]
Here's the new issue about the tsdb capability: #102414

**Comment by knz** [comment]
@aadityasondhi yes, these changes work. Can you squash + rebase on latest master? That will unlock CI.

**Comment by aadityasondhi** [comment]
Rebased, squashed, and green CI

**Comment by knz** [comment]
LGTM.

@aadityasondhi since you have reviewed it, can you approve the PR? We need the approval to merge.

**Review by aadityasondhi — APPROVED** [review]

**Comment by knz** [comment]
bors r=aadityasondhi

**Comment by knz** [comment]
bors r=aadityasondhi

**Pull request merged**
