### PR TITLE
distsql: remove EvaluatorSpec.Types and fix aggregate check

### PR DESCRIPTION
**Pull request by RaduBerinde**
EvaluatorSpec.Types are tedious to populate and aren't really required; we can
get the types from the first input row.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10700)

### CODE REVIEW

**Comment by irfansharif** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/evaluator.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWch8yZllCiRXdBqdO-:-KWch8y_3623tqHunPuo:bwj6g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/evaluator.go#L30)):*
> ```Go
> 
> type evaluator struct {
> 	flowCtx *FlowCtx
> ```

comment below, we can just store `evalCtx *parser.EvalContext` now.

---

*[pkg/sql/distsql/evaluator.go, line 48 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWcgMVP8zllsF3AaU5V:-KWcgMVP8zllsF3AaU5W:bij1was) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/evaluator.go#L48)):*
> ```Go
> ) (*evaluator, error) {
> 	ev := &evaluator{
> 		flowCtx:   flowCtx,
> ```

we can just store `flowCtx.evalCtx` now.

---

*[pkg/sql/distsql/evaluator.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWcgXP0vqPrmkQkLsen:-KWcgXP0vqPrmkQkLseo:b-m27rgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/evaluator.go#L90)):*
> ```Go
> 			}
> 			for i, expr := range ev.specExprs {
> 				err := ev.exprs[i].init(expr, types, ev.flowCtx.evalCtx)
> ```

comment above, we can simply store the `evalCtx` instead of doing `flowCtx.evalCtx`.

---

*[pkg/sql/distsql/processors.proto, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWcfkGQpiZlxaAmWCpC:-KWcfkGQpiZlxaAmWCpD:b-kro7d2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/processors.proto#L126)):*
> ```protobuf
> // 'program'.
> message EvaluatorSpec {
>   repeated Expression exprs = 2 [(gogoproto.nullable) = false];
> ```

The numbered tag can be reduced back to `1` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-:-KWchkfadMmuiskl4u-m:bg7igkv)*

**Comment by RaduBerinde** [comment]
TFTR. I added another commit, PTAL.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/evaluator.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWch8yZllCiRXdBqdO-:-KWcia_GgAIMWj-2hp6X:bi75rod) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/evaluator.go#L30)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> comment below, we can just store `evalCtx *parser.EvalContext` now.
</details>
why? most processors have a FlowCtx reference; there is other useful stuff in there that may be useful if we need to add debug logs (e.g. flow id).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-:-KWcj8wKi8jTggL6Ra0V:b-sab11j)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsql/processors.proto, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWcfkGQpiZlxaAmWCpC:-KWcoD1i85miIwCo14qO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/processors.proto#L126)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> The numbered tag can be reduced back to `1` now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700)*

**Comment by irfansharif** [comment]
:lgtm:, thanks for sending this in.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/evaluator.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-KWch8yZllCiRXdBqdO-:-KWcna48APeKx8wZ2ewc:beb908z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8427715e15e7906914b30e20de7d429726654fbf/pkg/sql/distsql/evaluator.go#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> why? most processors have a FlowCtx reference; there is other useful stuff in there that may be useful if we need to add debug logs (e.g. flow id).
</details>
hmm, my reasoning was simply because we weren't using those parts yet. as for possibly wanting to log flow id, I thought the general pattern would be decorating the internal `ctx context.Context` instead. no strong opinions on this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10700#-:-KWcuiwgsNb3RfvpF2fj:b-ttf0qy)*

**Pull request merged**
