### PR TITLE
cli: fix double-quote escaping for JSON values with format=sql

### LINKED ISSUE #131257: Incorrect json value string escaping in `cockroach sql --format sql`
**Describe the problem**

Somewhere between v23.1.2 and v24.1.2, the string escaping from `cockroach sql --format sql` changed in such a way that JSON values are incorrectly escaped.

**To Reproduce**

On v24.1.2, I first set up an example table:
```
root@127.0.0.1:26257/alda> create table test_escaping (value json);
root@127.0.0.1:26257/alda> insert into test_escaping values ('"there are \"quotes\" in this json string"');
root@127.0.0.1:26257/alda> select * from test_escaping;
                    value
----------------------------------------------
  "there are \"quotes\" in this json string"
```

Next I select from the table in `--format=sql`:
```
cockroach-local sql -d alda -e 'select * from test_escaping;' --format=sql

CREATE TABLE results (
  value STRING
);
INSERT INTO results VALUES (e'"there are \"quotes\" in this json string"');
```

The string literal is not correct. There should be two backslashes in front of the quotes because the e-string unescapes once, and then the quotes in the json value still need to be escaped.

The problem means you can't run the INSERT statement back into the `test_escaping` table:
```
root@127.0.0.1:26257/alda> INSERT INTO test_escaping VALUES (e'"there are \"quotes\" in this json string"');
ERROR: could not parse JSON: unable to decode JSON: while decoding 40 bytes at offset 13:
...|"there are "quotes" in this j|...
...|.............^...............|...: trailing characters after JSON document
SQLSTATE: 22P02
```

**Expected behavior**

If I do the same thing on v23.1.2, I get a different output, with correct escaping:
```
cockroach-local sql -d alda -e 'select * from test_escaping;' --format=sql

CREATE TABLE results (
  value STRING
);
INSERT INTO results VALUES (e'"there are \\"quotes\\" in this json string"');
```

**Environment:**
 - CockroachDB version v24.1.2
 - Server: Single node server on my MacOS laptop.
 - Client app: `cockroach sql`.

Jira issue: CRDB-42461

Epic CRDB-40419

### PR DESCRIPTION
**Pull request by rafiss**
A previous commit (98f9c8afaa603cd8d57340468345e0e3653751a6) made an attempt to fix how JSON values are escaped when they contain invalid UTF8 codes and are displayed in the CLI using the --format=sql flag (see #107518).

That commit ended up breaking how JSON values are escaped when they contain double quotes.

Luckily it turns out that both problems were actually caused by a long-lived mistake in the `clisqlexec.FormatVal` function. It shouldn't use `fmt.Sprintf("%+q", s)` to escape a string that has invalid characters, as that conflicts with how SQL strings are normally escaped. The proper way is to use `lexbase.EscapeSQLString(s)`.

fixes https://github.com/cockroachdb/cockroach/issues/131257
Release note (bug fix): Fixed a bug where the CLI would not correctly escape JSON values that had double-quotes inside of a string when using the --format=sql flag.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

Looks good one suggestion

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131881#-:-O8MzDuM3Ey73gkkA3JY:b7xwv44)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

___
*[`pkg/cli/clisqlexec/format_sql_test.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131881#-O8Mz7uD9oKdtOqCJ6TG:-O8Mz7uD9oKdtOqCJ6TH:b-vcx71e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc362102b572d8cc606502c4c431a3ab99b3c2c/pkg/cli/clisqlexec/format_sql_test.go#L14)):*
> ```Go
> 	defer c.Cleanup()
> 
> 	testData := []string{
> ```

Nit: I'm guessing we can't have an automated comaparison in this family of tests?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131881)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @rharding6373)

___
*[`pkg/cli/clisqlexec/format_sql_test.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131881#-O8Mz7uD9oKdtOqCJ6TG:-O8MzVfTC8NckcdLDu1c:b-nxnvz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc362102b572d8cc606502c4c431a3ab99b3c2c/pkg/cli/clisqlexec/format_sql_test.go#L14)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: I'm guessing we can't have an automated comaparison in this family of tests?
</blockquote></details>

what did you mean by automated comparison?

this test does assert that it has the correct output. for example: https://github.com/cockroachdb/cockroach/actions/runs/11174532794/job/31064361460?pr=131881

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131881)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @rharding6373)

___
*[`pkg/cli/clisqlexec/format_sql_test.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131881#-O8Mz7uD9oKdtOqCJ6TG:-O8N5tfm7sWf_VUyFQZi:b-k3rg0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc362102b572d8cc606502c4c431a3ab99b3c2c/pkg/cli/clisqlexec/format_sql_test.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what did you mean by automated comparison?

this test does assert that it has the correct output. for example: https://github.com/cockroachdb/cockroach/actions/runs/11174532794/job/31064361460?pr=131881
</blockquote></details>

further reading: https://go.dev/blog/examples

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131881)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

___
*[`pkg/cli/clisqlexec/format_sql_test.go` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131881#-O8Mz7uD9oKdtOqCJ6TG:-O8N5o-v87FIUALDE83Y:b-i97845) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc362102b572d8cc606502c4c431a3ab99b3c2c/pkg/cli/clisqlexec/format_sql_test.go#L14)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

further reading: https://go.dev/blog/examples
</blockquote></details>

TIL, thank you.

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
