### PR TITLE
execinfrapb: refactor ExprHelper and reduce allocations

### PR DESCRIPTION
**Pull request by mgartner**
#### flowinfra: add benchmark for render setup

`BenchmarkFlowRenderSetup` has been added to benchmark the setup cost of
renders.

Release note: None

#### execinfrapb: remove ExprHelper's String method

Release note: None

#### rowexec: update signature of joinreader span generators

A few span generator functions now take `tree.TypedExpr`s as arguments
instead of `*execinfrapb.ExprHelper`s.

Release note: None

#### execinfrapb: add MultiExprHelper

A new struct, `MultiExprHelper`, has been added that should be used
instead of `ExprHelper` when there are multiple expressions to evaluate.
Both helpers now wrap a non-exported base implementation, `exprHelper`,
whose implementation remains mostly unchanged.

A `MultiExprHelper` is now used in `execinfra.ProcOutputHelper` and
`rowexec.projectSetProcessor`. In the former, this significantly reduces
allocations for processors that contain many render expressions and
input columns because a single `tree.IndexedVarHelper` is used for all
expressions instead of one for each render expression.

Release note: None

#### execinfrapb: refactor DeserializeExpr and RunFilter

This commit moves two functions that were tangled up in method
definitions of a struct.

Release note: None

#### execinfrapb: unexport fields of exprHelper

This commit tightens up the `ExprHelper` API by unexporting all exported
fields of `exprHelper`, which is embedded in `ExprHelper`.

Release note: None

#### execinfrapb: remove util.NoCopy from exprHelper

This field was added long ago, and the usage of `exprHelper` has since
changed. There's no obvious reason to prevent `exprHelper`s from being
copied, so the field has been removed. In addition, all `ExprHelper` and
`MultiExprHelper` fields that were embedded as references in other
structs are now embedded as values.

Epic: None

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Hm, maybe try `BenchmarkFilterer` in `rowexec`? Or adjust `BenchmarkFlowSetup` a bit to add some rendering in `flowinfra`?

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-:-NnkduW54jbiPvCLTaRD:bc87k94)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/execinfra/processorsbase.go` line 165 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-Nnkd69f16WPbJFW0zqv:-Nnkd69f16WPbJFW0zqw:b-gjvxe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff74017f643689b3f5bceacd5a22c27a778f26b/pkg/sql/execinfra/processorsbase.go#L165)):*
> ```Go
> 		}
> 	} else if nRenders := len(post.RenderExprs); nRenders > 0 {
> 		h.eh.Init(ctx, coreOutputTypes, semaCtx, evalCtx)
> ```

We seem to have two `Init` calls on each loop iteration.
___
*[`pkg/sql/execinfrapb/expr.go` line 191 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnkdNd_AhsW9hI_Pj_S:-NnkdNd_AhsW9hI_Pj_T:b-tezo7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff74017f643689b3f5bceacd5a22c27a778f26b/pkg/sql/execinfrapb/expr.go#L191)):*
> ```Go
> }
> 
> // PrepareExpr returns converts the given Expression into a tree.TypedExpr.
> ```

nit: "returns converts".

**Comment by yuzefovich** [comment]
Another existing benchmark you could use is `BenchmarkRenderPlanning` in `colbuilder`. But probably it'd be worth creating a targeted one for the case you have in mind.

**Comment by mgartner** [comment]
> Hmm, I wonder if the API would be better if it the expr helpers stored the expressions.

I think this cleaned and tightened up the API quite nicely. It also reduced the collateral changes required.

**Review by yuzefovich — COMMENTED** [review]
I agree, this looks pretty nice.

> Reviewed 9 of 9 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-:-NnpkujKAKjwK5WzeQVD:b-upkghb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/execinfrapb/expr.go` line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpjbiV0pXZ9FGpzq0G:-NnpjbiV0pXZ9FGpzq0H:buyagrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/execinfrapb/expr.go#L194)):*
> ```Go
> }
> 
> // AddExpression sets the given expression as the i-th expression in the helper.
> ```

nit: `s/AddExpression/AddExpr/`.
___
*[`pkg/sql/execinfrapb/expr.go` line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpjiJh1W2sdGPoWV23:-NnpjiJh1W2sdGPoWV24:bxwe5o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/execinfrapb/expr.go#L196)):*
> ```Go
> // AddExpression sets the given expression as the i-th expression in the helper.
> func (eh *MultiExprHelper) AddExpr(ctx context.Context, expr Expression, i int) (err error) {
> 	if eh.exprs[i], err = eh.h.prepareExpr(ctx, expr); err != nil {
> ```

nit: could just return the err, without the nil check.
___
*[`pkg/sql/rowexec/project_set.go` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-Nnpk76d2B-tZt1Z3P54:-Nnpk76d2B-tZt1Z3P55:bk48tj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L36)):*
> ```Go
> 	spec  *execinfrapb.ProjectSetSpec
> 
> 	// exprHelpers are the constant-folded, type checked expressions specified
> ```

nit: the comment needs an update.
___
*[`pkg/sql/rowexec/project_set.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpkPZa1EO_EDqFj1hN:-NnpkPZdCXznj26jqo-t:b-uywnhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L40)):*
> ```Go
> 	// (anything that is "function-like" including COALESCE, NULLIF) not just
> 	// SRFs.
> 	eh *execinfrapb.MultiExprHelper
> ```

nit: could we store `MultiExprHelper` by value to avoid an initialization in the constructor?

**Comment by mgartner** [comment]
Results from the benchmark I added:

```
name                                                 old time/op    new time/op    delta
FlowRenderSetup/vectorize=true/distribute=true-10      1.72ms ±10%    1.67ms ± 3%     ~     (p=0.421 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10     1.48ms ± 2%    1.48ms ± 2%     ~     (p=0.548 n=5+5)
FlowRenderSetup/vectorize=false/distribute=true-10     2.40ms ± 1%    1.51ms ± 2%  -36.92%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=false/distribute=false-10    2.21ms ± 2%    1.32ms ± 2%  -40.29%  (p=0.008 n=5+5)

name                                                 old alloc/op   new alloc/op   delta
FlowRenderSetup/vectorize=true/distribute=true-10      1.08MB ± 1%    1.08MB ± 1%     ~     (p=1.000 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      991kB ± 2%     986kB ± 0%     ~     (p=0.905 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10     11.2MB ± 0%     0.9MB ± 0%  -92.30%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=false-10    11.1MB ± 0%     0.8MB ± 0%  -92.93%  (p=0.008 n=5+5)

name                                                 old allocs/op  new allocs/op  delta
FlowRenderSetup/vectorize=true/distribute=true-10       10.7k ± 3%     10.7k ± 3%     ~     (p=0.968 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      7.36k ± 2%     7.32k ± 0%     ~     (p=0.905 n=5+4)
FlowRenderSetup/vectorize=false/distribute=true-10      8.91k ± 2%     8.30k ± 0%   -6.81%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=false-10     5.63k ± 3%     5.04k ± 0%  -10.56%  (p=0.008 n=5+5)
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/execinfra/processorsbase.go` line 165 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-Nnkd69f16WPbJFW0zqv:-NnuJ8Y8BDFHUM-ckBvv:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/dff74017f643689b3f5bceacd5a22c27a778f26b/pkg/sql/execinfra/processorsbase.go#L165)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We seem to have two `Init` calls on each loop iteration.
</blockquote></details>

Fixed.
___
*[`pkg/sql/rowexec/project_set.go` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-Nnpk76d2B-tZt1Z3P54:-NnuKIRzA1ppnVuV6dNd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L36)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment needs an update.
</blockquote></details>

Done.
___
*[`pkg/sql/rowexec/project_set.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpkPZa1EO_EDqFj1hN:-NnuK88Q7ApJ10yVIc2m:b-tih0qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L40)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: could we store `MultiExprHelper` by value to avoid an initialization in the constructor?
</blockquote></details>

`go vet` might complain due to the `_ util.NoCopy` in `execHelper`, but let's see..

**Review by yuzefovich — COMMENTED** [review]
First commit seems out of place.

Nice improvement! Curious also to see the numbers for the new `BenchmarkRenderPlanning` too. I also have a couple more comments / suggestions.

> Reviewed 14 of 14 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 8 of 8 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-:-No2eEy33v1nIyADhKhK:b-41oscl)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/execinfrapb/expr.go` line 303 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2g2R60m4NgFACM85p:-No2g2R60m4NgFACM85q:bhfxd2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/22f6667be883294624f2599d1afaf7ae4f3001cc/pkg/sql/execinfrapb/expr.go#L303)):*
> ```Go
> }
> 
> // Init initializes the exprHelper.
> ```

nit: `s/Init/init/`.
___
*[`pkg/sql/rowexec/project_set.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpkPZa1EO_EDqFj1hN:-No2gDaY95WGtyAQngTT:b-yen4ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L40)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`go vet` might complain due to the `_ util.NoCopy` in `execHelper`, but let's see..
</blockquote></details>

Hm, this `_ util.NoCopy` in the expr helper was introduced very long time ago in https://github.com/cockroachdb/cockroach/commit/b04e4bf18bba437bf06e48898ff618aa35227e8a. My intuition says that it should be ok to allow copying this struct, so we could remove the NoCopy marker. There is definitely some inconsistency in how we use the ExprHelper already - in `filtererProcessor` and `projectSetProcessor` we store it by reference, but in other places we store it by value. It seems like it'd be nice to unify things (and store it by value everywhere) given that we're cleaning this code up.
___
*[`pkg/sql/execinfra/base_test.go` line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2eVmd47nflAJMIwPK:-No2eVmd47nflAJMIwPL:bx2qsuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdd38d012a44e06bdd676a1bca7bcb29ce5a70d/pkg/sql/execinfra/base_test.go#L139)):*
> ```Go
> }
> 
> // BenchmarkRenderPlanning is similar to BenchmarkRenderPlanning, but
> ```

nit: perhaps do `colbuilder.BenchmarkRenderPlanning` for the second mention?
___
*[`pkg/sql/execinfra/base_test.go` line 151 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2emAr15L6My-cAIC7:-No2emAr15L6My-cAIC8:b-crdl9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdd38d012a44e06bdd676a1bca7bcb29ce5a70d/pkg/sql/execinfra/base_test.go#L151)):*
> ```Go
> 
> 	sqlDB := sqlutils.MakeSQLRunner(db)
> 	sqlDB.Exec(b, "SET CLUSTER SETTING sql.defaults.vectorize = off")
> ```

nit: seems like it'd be nice to do both vectorize on and off here too.
___
*[`pkg/sql/flowinfra/flow_test.go` line 101 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2f7lW9bWu6y9cRMg_:-No2f7lW9bWu6y9cRMga:blplrby) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdd38d012a44e06bdd676a1bca7bcb29ce5a70d/pkg/sql/flowinfra/flow_test.go#L101)):*
> ```Go
> 
> 	s, conn, _ := serverutils.StartServer(b, base.TestServerArgs{
> 		Settings: cluster.MakeTestingClusterSettings(),
> ```

nit: I think this line is not necessary (i.e. `Settings` can remain `nil`).

**Review by mgartner — COMMENTED** [review]
Thanks for the thorough review!

The benchmark still looks good:

```
name                                                 old time/op    new time/op    delta
FlowRenderSetup/vectorize=true/distribute=true-10      1.75ms ± 8%    1.61ms ± 0%   -7.99%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10     1.44ms ± 0%    1.44ms ± 0%     ~     (p=0.413 n=4+5)
FlowRenderSetup/vectorize=false/distribute=true-10     2.59ms ± 3%    1.46ms ± 0%  -43.53%  (p=0.008 n=5+5)
FlowRenderSetup/vectorize=false/distribute=false-10    2.44ms ±12%    1.30ms ± 0%  -46.88%  (p=0.008 n=5+5)

name                                                 old alloc/op   new alloc/op   delta
FlowRenderSetup/vectorize=true/distribute=true-10      1.08MB ± 1%    1.08MB ± 1%     ~     (p=0.690 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      991kB ± 2%     993kB ± 2%     ~     (p=0.690 n=5+5)
FlowRenderSetup/vectorize=false/distribute=true-10     11.2MB ± 0%     0.9MB ± 0%  -92.30%  (p=0.016 n=5+4)
FlowRenderSetup/vectorize=false/distribute=false-10    11.1MB ± 0%     0.8MB ± 0%  -92.94%  (p=0.008 n=5+5)

name                                                 old allocs/op  new allocs/op  delta
FlowRenderSetup/vectorize=true/distribute=true-10       10.7k ± 3%     10.7k ± 3%     ~     (p=0.841 n=5+5)
FlowRenderSetup/vectorize=true/distribute=false-10      7.36k ± 2%     7.37k ± 2%     ~     (p=0.833 n=5+5)
FlowRenderSetup/vectorize=false/distribute=true-10      8.83k ± 0%     8.30k ± 0%   -5.93%  (p=0.029 n=4+4)
FlowRenderSetup/vectorize=false/distribute=false-10     5.64k ± 3%     5.04k ± 0%  -10.64%  (p=0.008 n=5+5)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-:-NoHf4ei9mVePDktF4k4:b-gw0ogt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/rowexec/project_set.go` line 40 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NnpkPZa1EO_EDqFj1hN:-NoHeZVA4kW3fcM_8DCU:bvsk7j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4168612239af3002c916609ad6150414e0ef42b2/pkg/sql/rowexec/project_set.go#L40)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, this `_ util.NoCopy` in the expr helper was introduced very long time ago in https://github.com/cockroachdb/cockroach/commit/b04e4bf18bba437bf06e48898ff618aa35227e8a. My intuition says that it should be ok to allow copying this struct, so we could remove the NoCopy marker. There is definitely some inconsistency in how we use the ExprHelper already - in `filtererProcessor` and `projectSetProcessor` we store it by reference, but in other places we store it by value. It seems like it'd be nice to unify things (and store it by value everywhere) given that we're cleaning this code up.
</blockquote></details>

Sounds good to me. Done!
___
*[`pkg/sql/execinfra/base_test.go` line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2eVmd47nflAJMIwPK:-NoHYaFd3qwGa7VgJg-P:bva0e9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdd38d012a44e06bdd676a1bca7bcb29ce5a70d/pkg/sql/execinfra/base_test.go#L139)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps do `colbuilder.BenchmarkRenderPlanning` for the second mention?
</blockquote></details>

I messed up these commits somehow. This was an early version of the benchmark that showed no improvment. I meant to delete it.
___
*[`pkg/sql/flowinfra/flow_test.go` line 101 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-No2f7lW9bWu6y9cRMg_:-NoHc9_4EBFzH1gmef6J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdd38d012a44e06bdd676a1bca7bcb29ce5a70d/pkg/sql/flowinfra/flow_test.go#L101)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think this line is not necessary (i.e. `Settings` can remain `nil`).
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
Nice work! I have a couple of comments, but :lgtm: (assuming the failure on CI is a simple fix).

> Reviewed 17 of 17 files at r14, 6 of 6 files at r15, 7 of 7 files at r16, 13 of 13 files at r17, 6 of 6 files at r18, 8 of 8 files at r19, 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-:-NoIsWkT8xl4Q7M8dVBI:b9wn0ci)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 55 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIrsr-4YmNJ65tAerO):*
nit: I'm not sure whether the build before the commit that removes `util.NoCopy` marker is green - it might be necessary to reorder the commits so that the marker is removed before MultiExprHelper is introduced. It'd be good to double check that, for example, the newly-added benchmark can be built on each commit.
___
*[`pkg/sql/execinfrapb/expr.go` line 297 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIsIT97DOZiSVYsaJQ:-NoIsIT97DOZiSVYsaJR:b254yut) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1860d67a38f65b838cdfb9d96515b5f5119556/pkg/sql/execinfrapb/expr.go#L297)):*
> ```Go
> 	evalCtx    *eval.Context
> 	semaCtx    *tree.SemaContext
> 	datumAlloc *tree.DatumAlloc
> ```

nit: why make `datumAlloc` a pointer? Is the idea to reduce the size of `exprHelper` when `init` is not called on it?

**Comment by mgartner** [comment]
*[`pkg/sql/execinfrapb/expr.go` line 297 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIsIT97DOZiSVYsaJQ:-NoMnIM-0h06qW6ofXYu:b-engt1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1860d67a38f65b838cdfb9d96515b5f5119556/pkg/sql/execinfrapb/expr.go#L297)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: why make `datumAlloc` a pointer? Is the idea to reduce the size of `exprHelper` when `init` is not called on it?
</blockquote></details>

`tree.DatumAlloc` also has a `util.NoCopy` field that requires this to be a reference. The copy originates here: https://github.com/cockroachdb/cockroach/blob/c4ca22df6df4723fc1e326430448bfde56a64dff/pkg/sql/execinfra/processorsbase.go#L439

Maybe there is an alternative here that I haven't yet seen.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 55 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIrsr-4YmNJ65tAerO):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'm not sure whether the build before the commit that removes `util.NoCopy` marker is green - it might be necessary to reorder the commits so that the marker is removed before MultiExprHelper is introduced. It'd be good to double check that, for example, the newly-added benchmark can be built on each commit.
</blockquote></details>

It's only a lint failure, so I don't think it's worth re-ordering commits. Let me know if you disagree.

**Review by yuzefovich — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117588)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 55 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIrsr-4YmNJ65tAerO):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's only a lint failure, so I don't think it's worth re-ordering commits. Let me know if you disagree.
</blockquote></details>

Yeah, lint failures are ok - I just wanted to make sure that running the tests / benchmarks (for git bisect in the future, should we need to) would work.
___
*[`pkg/sql/execinfrapb/expr.go` line 297 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/117588#-NoIsIT97DOZiSVYsaJQ:-NoNJKOM6UM_tQKGmuTf:b30ffor) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b1860d67a38f65b838cdfb9d96515b5f5119556/pkg/sql/execinfrapb/expr.go#L297)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`tree.DatumAlloc` also has a `util.NoCopy` field that requires this to be a reference. The copy originates here: https://github.com/cockroachdb/cockroach/blob/c4ca22df6df4723fc1e326430448bfde56a64dff/pkg/sql/execinfra/processorsbase.go#L439

Maybe there is an alternative here that I haven't yet seen.
</blockquote></details>

Ah, forgot about that, nvm then.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
