### PR TITLE
storage: Replica.String, Replica.Desc, and Replica logging refactor

### LINKED ISSUE #7852: storage: Replica.String fosters deadlocks
`Replica.String` calls `Replica.Desc` which grabs `r.mu.Mutex`. This makes `Replica.String` unsafe to call from any method which is already holding `r.mu.Mutex`. This issue is exacerbated by any log messages which wish to format a `Replica` using `%s`.

### PR DESCRIPTION
**Pull request by rjnn**
Fixes #7852.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7871)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: modulo comments.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvNMdiZa-0ADjSi0XS:-KMvNMdjdJA1c0YTunqT:-1168898484) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L207)):*
> ```Go
> 		// The state of the Raft state machine.
> 		state storagebase.ReplicaState
> 		// rangeDesc is a rangeDescriptor that can be atomically read from. All
> ```

`s/rangeDescriptor/*RangeDescriptor/g`

---

*[storage/replica.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvNZCHugekWN4L5_kt:-KMvNZCHugekWN4L5_ku:420499568) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L208)):*
> ```Go
> 		state storagebase.ReplicaState
> 		// rangeDesc is a rangeDescriptor that can be atomically read from. All
> 		// updates to state.desc should be duplicated here (as is done in
> ```

`s/state.desc/state.Desc/g`

---

*[storage/replica.go, line 633 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvOlNpu0oTEiP43Bod:-KMvOlNpu0oTEiP43Boe:-2021982339) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L633)):*
> ```Go
> // Desc returns the range's descriptor.
> func (r *Replica) Desc() *roachpb.RangeDescriptor {
> 	return r.mu.rangeDesc.Load().(*roachpb.RangeDescriptor)
> ```

@bdarnell I'm not familiar enough with the subtleties of this code to know if this is kosher.

It would be a more conservative change to leave this method untouched and to change `String()` to use `r.mu.rangeDesc.Load().(*roachpb.RangeDescriptor)`.

---

*[storage/replica.go, line 787 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvON1oZtOmrhhbgtNR:-KMvON1oZtOmrhhbgtNS:1252644436) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L787)):*
> ```Go
> 	var err error
> 	if ri.LastVerification, err = r.getLastVerificationTimestamp(); err != nil {
> 		log.Warningf("range %s: %v", r, err)
> ```

You should get rid of the `range ` prefix everywhere. As it it currently is, the log messages will look like `range node=1 store=2 range=3`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-:-KMvPmYFbKhzP8TjSBKe:252484863)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6JpPxibR8k-yH5pv:-KMw6JpQIAuV5sL-L2Lm:1038132592) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L211)):*
> ```Go
> 		// updateRangeDescriptorLocked()) so that it can be read without acquiring
> 		// the lock.
> 		rangeDesc atomic.Value
> ```

why is it better to have this in two places? either we need atomic-with-other-things updates or we don't.

---

*[storage/replica.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6gXwhUwHJ3RMFo_4:-KMw6gXwhUwHJ3RMFo_5:1503098872) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L396)):*
> ```Go
> func (r *Replica) String() string {
> 	desc := r.Desc()
> 	return fmt.Sprintf("node=%d store=%d range=%d [%s-%s)", r.store.Ident.NodeID, r.store.Ident.StoreID, desc.RangeID, desc.StartKey, desc.EndKey)
> ```

why not %+v the ident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6gXwhUwHJ3RMFo_4:-KMxr811MKmVVA-EpWeX:-1337915196) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L396)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not %+v the ident?
</details>
`roachpb.StoreIdent` includes the cluster ID which isn't useful to print in every log message. But instead of printing `node=%d store=%d`, we could use `Store.String()`:

```
  return fmt.Sprintf("%s range=%d [%s-%s)", r.store, d
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6gXwhUwHJ3RMFo_4:-KMxt_MW-MXd5Ii39svP:-1845334308) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L396)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `roachpb.StoreIdent` includes the cluster ID which isn't useful to print in every log message. But instead of printing `node=%d store=%d`, we could use `Store.String()`:
> 
> ```
>   return fmt.Sprintf("%s range=%d [%s-%s)", r.store, d
> ```
</details>
That should read:

```
  return fmt.Sprintf("%s range=%d [%s-%s)", r.store, desc.RangeID, desc.StartKey, desc.EndKey)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by arjunravinarayan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvNMdiZa-0ADjSi0XS:-KMyVkdQwyozfPsltt8k:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L207)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/rangeDescriptor/*RangeDescriptor/g`
</details>
Done.

---

*[storage/replica.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvNZCHugekWN4L5_kt:-KMyVlPTM5vpMy0EofVH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L208)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `s/state.desc/state.Desc/g`
</details>
Done.

---

*[storage/replica.go, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6JpPxibR8k-yH5pv:-KMyHmj3BnXuJz6n5oiR:711749933) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L211)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why is it better to have this in two places? either we need atomic-with-other-things updates or we don't.
</details>
See @bdarnell's comment on #7852 (or this commit message).

---

*[storage/replica.go, line 396 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6gXwhUwHJ3RMFo_4:-KMyI8uZpFU02oJlxaCL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L396)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> That should read:
> 
> ```
>   return fmt.Sprintf("%s range=%d [%s-%s)", r.store, desc.RangeID, desc.StartKey, desc.EndKey)
> ```
</details>
Done.

---

*[storage/replica.go, line 633 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvOlNpu0oTEiP43Bod:-KMyT6YAWrNpZLbj-SDo:-473276340) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L633)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @bdarnell I'm not familiar enough with the subtleties of this code to know if this is kosher.
> 
> It would be a more conservative change to leave this method untouched and to change `String()` to use `r.mu.rangeDesc.Load().(*roachpb.RangeDescriptor)`.
</details>
That's fair. I'm pretty sure it's kosher, but given our current stability issues, let's conservatively leave Desc() alone. Done.

---

*[storage/replica.go, line 787 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvON1oZtOmrhhbgtNR:-KMz-57y5i4DYK4dLZrz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L787)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You should get rid of the `range ` prefix everywhere. As it it currently is, the log messages will look like `range node=1 store=2 range=3`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by petermattis** [comment]
Still :lgtm:, though I think there are some `log` calls in `replica_raftstore.go` that could be adjusted.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-:-KMz-u4nGtY-Rm66HEsj:-1739023753)*

**Comment by arjunravinarayan** [comment]
Added changes in `replica_raftstore.go`. PTAL.

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-:-KMz3oUpiH8CkvC3RAIc:-794232723)*

**Comment by petermattis** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_raftstorage.go, line 435 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMz5y5WIN8hzxU8tEZj:-KMz5y5XbQSEQW-m6T7x:-1458621841) ([raw file](https://github.com/cockroachdb/cockroach/blob/485ca49e57ee0c8969386695040cfd850d294360/storage/replica_raftstorage.go#L435)):*
> ```Go
> 	}
> 
> 	log.Infof("generated snapshot at index %d in %s. encoded size=%d, %d KV pairs, %d log entries",
> ```

You need to include `r` in the prefix of this message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by arjunravinarayan** [comment]
*[storage/replica_raftstorage.go, line 435 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMz5y5WIN8hzxU8tEZj:-KMzAfqDUC8gasBFRyLc:-598051055) ([raw file](https://github.com/cockroachdb/cockroach/blob/485ca49e57ee0c8969386695040cfd850d294360/storage/replica_raftstorage.go#L435)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> You need to include `r` in the prefix of this message.
</details>
Huh, I accidentally clobbered that line. I've reverted it to the original version (since we do not in fact have a replica in this function, only a `roachpb.RangeID`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMw6JpPxibR8k-yH5pv:-KMzyuBEU_wRJJkKzeG0:290362910) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L211)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Ravi Narayan) wrote…</i></summary>
> See @bdarnell's comment on #7852 (or this commit message).
</details>
Ah, I forgot about the `ReplicaState` refactoring. I was thinking we'd change `r.mu.desc` instead of creating two copies of it. But since `ReplicaState` is a protobuf we can't do that.

If we're storing this in two places anyway then the `atomic.Value` copy should be outside the `mu` struct.

---

*[storage/replica.go, line 633 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-KMvOlNpu0oTEiP43Bod:-KMzzXyOExw633PM4at5:799239724) ([raw file](https://github.com/cockroachdb/cockroach/blob/f82e4ca951830a6a89149d5cfa6aeca4f7cbe9b0/storage/replica.go#L633)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Ravi Narayan) wrote…</i></summary>
> That's fair. I'm pretty sure it's kosher, but given our current stability issues, let's conservatively leave Desc() alone. Done.
</details>
I think it would be safe to change `Desc()` and would prefer to do so. Then `Desc()` is the only thing that accesses the descriptor through `atomic.Value.Load`. 

I think it's safe because anything that calls `Desc()` must already be tolerant of concurrent changes: they release the lock before actually doing anything with the descriptor. In cases where consistency of the descriptor matters we don't call `Desc()`; we get the lock and access `r.mu.state.Desc`directly  under that lock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871#-:-KN-0GIEiUJ15yCl-szj:1417088721)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7871)*

**Pull request merged**
