### PR TITLE
roachprod: library-ifying roachprod (first pass)

### PR DESCRIPTION
**Pull request by healthy-pod**
In #71660, roachprod library was created under pkg/roachprod
by moving the logic under pkg/cmd/roachprod to pkg/roachprod and
pointing the binary subcommands to the library.

This patch updates the logic to make it more suitable for a library
than a binary and integrates those changes into related tools such
as pkg/cmd/roachprod and pkg/cmd/roachtest.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Looks good so far, nice to see the first roachprod-then-parse invocations gone.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-:-Mnj_kOX4Oq3maKYmonA:buf2de1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[pkg/cmd/roachprod/main.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjYsNK8RXZjQ7dVz2h:-MnjYsNK8RXZjQ7dVz2i:b-ciz5s7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachprod/main.go#L80)):*
> ```Go
> 	secure            = false
> 	extraSSHOptions   = ""
> 	putFileMode       = "755"
> ```

seems unusual to use strings here, for consistency with the standard library it might be better to stick to an int with `0755`.
___
*[pkg/cmd/roachprod/main.go, line 1080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZ0Ps2iKabBiwpeLZ:-MnjZ0Ps2iKabBiwpeL_:b-krbj5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachprod/main.go#L1080)):*
> ```Go
> 
> 	putCmd.Flags().BoolVar(&useTreeDist, "treedist", useTreeDist, "use treedist copy algorithm")
> 	putCmd.Flags().StringVar(&putFileMode, "mode", "755", "file mode on remote node (example 755)")
> ```

ah, that's why. I suppose that's fine.
___
*[pkg/cmd/roachtest/cluster.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZAZeC0mERAPnp4YR:-MnjZAZeC0mERAPnp4YS:b899eae) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachtest/cluster.go#L43)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/spec"
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test"
> 	roachprodlibrary "github.com/cockroachdb/cockroach/pkg/roachprod"
> ```

Why can't import this as `roachprod`? If this needs a custom name you may want to consider the shorter `rplib` (Just a suggestion).
___
*[pkg/cmd/roachtest/cluster.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZ6NU1ScxMMUV6fXy:-MnjZ6NU1ScxMMUV6fXz:b-9stbc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachtest/cluster.go#L44)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test"
> 	roachprodlibrary "github.com/cockroachdb/cockroach/pkg/roachprod"
> 	_ "github.com/cockroachdb/cockroach/pkg/roachprod/vm"
> ```

Add comments about these imports.
___
*[pkg/cmd/roachtest/cluster.go, line 1035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZN807a-N8wtoyYHl:-MnjZN807a-N8wtoyYHm:bftyhsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachtest/cluster.go#L1035)):*
> ```Go
> 	c.status("checking that existing cluster matches spec")
> 
> 	cloudClusters, err := roachprodlibrary.List(true /*quiet*/, false /*listMine*/, c.name /*clusterNamePattern*/)
> ```

`/* x */` instead of `/*x*/` and a method that takes more than one bool should take options:

```go
roachprodlibrary.List(c.name, roachprodlibrary.ListOpts{Quiet: true})
```
___
*[pkg/cmd/roachtest/cluster.go, line 2324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZgoL7X5JQ-pf7Knq:-MnjZgoM-IsSuhJAKDWA:b-j827h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachtest/cluster.go#L2324)):*
> ```Go
> 	l.PrintfCtx(ctx, "extending cluster by %d minutes", minutes)
> 
> 	clusterOpts := roachprodlibrary.DefaultSyncedCluster()
> ```

This dance seems a little odd, I'm not quite sure why `Extend` takes a `clusterOpts` and why it's ok to call an ominous `DefaultSyncedCluster` and then mutate its name. Why doesn't this only take the cluster name and an extension duration? That's what I would have expected from roachprod-as-a-lib.
___
*[pkg/roachprod/install/cluster_synced.go, line 1255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-Mnj_8AZ9u0Mp6ncdxmS:-Mnj_8AZ9u0Mp6ncdxmT:b8kz03j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/roachprod/install/cluster_synced.go#L1255)):*
> ```Go
> 	}
> 
> 	cmd := fmt.Sprintf("chmod %s %s", mode, dest)
> ```

This seems weird on two levels. First, sprintf'ing stuff into a string certainly won't do the correct escaping. Second, why are you passing `cmd` twice to `Run`?
___
*[pkg/roachprod/install/cluster_synced.go, line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-Mnj_DJUDQJ3WUnCQhs_:-Mnj_DJUDQJ3WUnCQhsa:b3ubcsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/roachprod/install/cluster_synced.go#L1258)):*
> ```Go
> 	err := c.Run(os.Stdout, os.Stderr, c.Nodes, cmd, cmd)
> 	if err != nil {
> 		log.Fatalf(context.Background(), "chmod failed", err)
> ```

I mentioned this in an earlier comment, but `log.Fatal` is not something `roachprod` should ever call; it is taylored to the CRDB server and will print long messages specific to that.

Why aren't we propagating errors throughout? Is the old code just using `log.Fatal`? Would be nice to rectify that (doesn't have to be in this PR). As a stop-gap, let's at least replace all uses of `log.Fatal` with something like `roachprod.fatalf` which "just" prints `err` to `os.Stderr` and then `os.Exit(1)`.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod)

___
*[pkg/roachprod/install/cluster_synced.go, line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-Mnj_DJUDQJ3WUnCQhs_:-MoDgPRa-U1y7prnFDrV:b-28jd9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/roachprod/install/cluster_synced.go#L1258)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I mentioned this in an earlier comment, but `log.Fatal` is not something `roachprod` should ever call; it is taylored to the CRDB server and will print long messages specific to that.

Why aren't we propagating errors throughout? Is the old code just using `log.Fatal`? Would be nice to rectify that (doesn't have to be in this PR). As a stop-gap, let's at least replace all uses of `log.Fatal` with something like `roachprod.fatalf` which "just" prints `err` to `os.Stderr` and then `os.Exit(1)`.
</blockquote></details>

Just to double down on this, the current behavior is causing lots of spam and making roachtest investigations more difficult. For example here: https://github.com/cockroachdb/cockroach/issues/72083#issuecomment-965790580

The real problem is that `./cockroach start` exits nonzero in `roachprod start`. So `roachprod start` exits using `log.Fatal` and it's really hard to find the actual error. It should just exit nonzero without printing so much extraneous logging, certainly stacks are not needed here.

Might be worth sending a one-off PR to remove `log.Fatal` instead of lumping it in with this slower-moving change.

**Review by healthy-pod — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @rail, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 2324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MnjZgoL7X5JQ-pf7Knq:-Mp7W5ei7opLMCoSCgMz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/cmd/roachtest/cluster.go#L2324)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This dance seems a little odd, I'm not quite sure why `Extend` takes a `clusterOpts` and why it's ok to call an ominous `DefaultSyncedCluster` and then mutate its name. Why doesn't this only take the cluster name and an extension duration? That's what I would have expected from roachprod-as-a-lib.
</blockquote></details>

Done
___
*[pkg/roachprod/install/cluster_synced.go, line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-Mnj_DJUDQJ3WUnCQhs_:-Mp7WIoW88dOGZJ94nJW:bo2oolw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66426c24f8d6a10fbd0dd4fb6408d745c2a2b3b/pkg/roachprod/install/cluster_synced.go#L1258)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just to double down on this, the current behavior is causing lots of spam and making roachtest investigations more difficult. For example here: https://github.com/cockroachdb/cockroach/issues/72083#issuecomment-965790580

The real problem is that `./cockroach start` exits nonzero in `roachprod start`. So `roachprod start` exits using `log.Fatal` and it's really hard to find the actual error. It should just exit nonzero without printing so much extraneous logging, certainly stacks are not needed here.

Might be worth sending a one-off PR to remove `log.Fatal` instead of lumping it in with this slower-moving change.
</blockquote></details>

Resolved in #72703

**Review by tbg — CHANGES_REQUESTED** [review]
With the size of the diff, I wasn't able to really scrutinize any individual piece of this PR, but from a high level this looks good. Given how big this diff is I would advocate for merging it as soon as possible, and addressing my comments separately.

I ran `roachtest run version/mixed/nodes=5` as a sanity check and it blew up in my face, so I think there are still some snags here. Here's the relevant log:

```
=== RUN   version/mixed/nodes=5
10:06:12 cluster.go:696: test status: staging binary
Resolved release url for cockroach version v21.2.0: https://s3.amazonaws.com/binaries.cockroachdb.com/cockroach-v21.2.0.linux-amd64.tgz
tobias-1637661800-01-n6cpu4: staging cockroach release binary....
   1: 
   2: 
   3: 
   4: 
   5: 
10:06:17 cluster.go:696: test status: 
10:06:17 cluster.go:696: test status: uploading file
tobias-1637661800-01-n6cpu4: putting (scp) /Users/tobias/go/src/github.com/cockroachdb/cockroach/bin/workload ./workload
..........................................
   6: done
10:06:59 cluster.go:696: test status: 
10:06:59 cluster.go:696: test status: starting nodes :1-5
10:06:59 cluster.go:403: > /Users/tobias/go/src/github.com/cockroachdb/cockroach/bin/roachprod start --encrypt=false tobias-1637661800-01-n6cpu4:1-5
tobias-1637661800-01-n6cpu4: starting nodes
0: ~ ./cockroach version: exit status 127
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/roachprod/install.getCockroachVersion
  | 	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/roachprod/install/cockroach.go:99
  | github.com/cockroachdb/cockroach/pkg/roachprod/install.(*SyncedCluster).Start.func1
  | 	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/roachprod/install/cockroach.go:145
  | github.com/cockroachdb/cockroach/pkg/roachprod/install.(*SyncedCluster).ParallelE.func1.1
  | 	/Users/tobias/go/src/github.com/cockroachdb/cockroach/pkg/roachprod/install/cluster_synced.go:1969
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1581
Wraps: (2) ~ ./cockroach version
  | bash: ./cockroach: No such file or directory
```

So something got broken either with `c.Stage` or with `c.Start`. Definitely want to get at least this test passing before the merge.

There might still be a few of the more exotic tests that perhaps discover some snags, but it seems fine dealing with these problems as they occur as long as we're reasonably certain that "most tests" will be fine. You may want to check https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+label%3AO-roachtest the day after this merges.

In a follow-up, you can then also remove this bit which requires `roachprod` when running `roachtest` but this is no longer necessary:

https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/cluster.go#L233-L237

> Reviewed 7 of 20 files at r2, 2 of 13 files at r3, 16 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-:-MpBELDn7iEcPV2Ej61x:bzgo1tu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @RaduBerinde, and @rail)

___
*[pkg/cmd/roachtest/cluster.go, line 847 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB6HkV60QB5rYFDZu1:-MpB6HkW9GbeAR_fzra-:bmpltre) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/cluster.go#L847)):*
> ```Go
> 	}
> 
> 	if overrideFlagset != nil && overrideFlagset.Changed("nodes") {
> ```

This whole `override`isn't easy to understand. Could you add commentary on `overrideFlagset` and perhaps on `createFlagsOverride` too (if even to just point at the other comment)? I think these are the flags on roachtest that allow mutating the spec that would otherwise be used for a test. What I don't understand is the indirection, namely assigning `runCmd.Flags()` to `overrideFlagset`, in my view things would be a little simpler if we operated on `runCmd.Flags()` directly to avoid the mental indirection?
___
*[pkg/cmd/roachtest/cluster.go, line 908 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB65nKEJVdCN07AqMs:-MpB65nKEJVdCN07AqMt:bh3iep8) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/cluster.go#L908)):*
> ```Go
> 			}
> 			createFlagsOverride(overrideFlagset, &createVMOpts)
> 			// make sure c.expiration is changed if --lifetime override flag is passed
> ```

nit: `// Make ... passed.`
___
*[pkg/cmd/roachtest/main.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB74VdBGbeD1WwwWlh:-MpB74VdBGbeD1WwwWli:bxrfp46) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/main.go#L45)):*
> ```Go
> const runnerLogsDir = "_runner-logs"
> 
> // only used if passed otherwise refer to ClusterSpec
> ```

nit: Only
___
*[pkg/roachprod/install/cluster_settings.go, line 98 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB8FUhBeyWuZzRhO0t:-MpB8FUhBeyWuZzRhO0u:b-54w0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/roachprod/install/cluster_settings.go#L98)):*
> ```Go
> 		NumRacks: 0,
> 	}
> 	// override default values using the passed options (if any)
> ```

// Override ... (if any).
___
*[pkg/roachprod/install/download.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB8ISREi95a3voc6QI:-MpB8ISREi95a3voc6QJ:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/roachprod/install/download.go#L75)):*
> ```Go
> 		src := filepath.Join(c.localVMDir(downloadNodes[0]), dest)
> 		cpCmd := fmt.Sprintf(`cp "%s" "%s"`, src, dest)
> 		// var results []RunResultDetails
> ```

?
___
*[pkg/roachprod/install/install.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB8KsiDHGn2k-s1xqi:-MpB8KsiDHGn2k-s1xqj:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/roachprod/install/install.go#L163)):*
> ```Go
> func Install(c *SyncedCluster, args []string) error {
> 	do := func(title, cmd string) error {
> 		// var buf bytes.Buffer
> ```

?

**Review by healthy-pod — COMMENTED** [review]
Thanks for pointing this out! It turned out to be specific to GCE and caused by inconsistent ssh username usage (stages or puts files using local username so it stages files under `/user/ahmad` or `/user/tobias` but then tries to run other commands such as `./cockroach` with `ubuntu` as username hence looking for the binary under `/user/ubuntu`. It should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-:-MpKQcqi2Y0XzlCPHTDn:bw7m4ta)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @RaduBerinde, @rail, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 847 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB6HkV60QB5rYFDZu1:-MpKS6UFCn8cQwHPIav8:bx6w88f) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/cluster.go#L847)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This whole `override`isn't easy to understand. Could you add commentary on `overrideFlagset` and perhaps on `createFlagsOverride` too (if even to just point at the other comment)? I think these are the flags on roachtest that allow mutating the spec that would otherwise be used for a test. What I don't understand is the indirection, namely assigning `runCmd.Flags()` to `overrideFlagset`, in my view things would be a little simpler if we operated on `runCmd.Flags()` directly to avoid the mental indirection?
</blockquote></details>

We operate on `overrideFlagset` because runCmd is local to `main()` so we can't access it from `cluster.go`.  We apply the overrides in `cluster.go` and not in `main.go` because we need to get the test spec then apply the overrides to that spec and we only get the test spec in `cluster.go`. I added a TODO in this PR to globalize commands variables like we do in `roachprod` and made the changes on another branch where I also made a lot of roachtest code cleanup but I didn't want to add new changes to this PR due to the size of it!
___
*[pkg/cmd/roachtest/cluster.go, line 908 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB65nKEJVdCN07AqMs:-MpKU85XEXmgCJHAl3Vk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/cluster.go#L908)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: `// Make ... passed.`
</blockquote></details>

Done
___
*[pkg/cmd/roachtest/main.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB74VdBGbeD1WwwWlh:-MpKUAxT80F2cOv9Lss_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/cmd/roachtest/main.go#L45)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: Only
</blockquote></details>

Done
___
*[pkg/roachprod/install/cluster_settings.go, line 98 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpB8FUhBeyWuZzRhO0t:-MpKUH-H4j4DMxaOrdds:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33414ef44cc53c8fe456915460e3c1b6914db758/pkg/roachprod/install/cluster_settings.go#L98)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

// Override ... (if any).
</blockquote></details>

Done

**Review by tbg — APPROVED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72473)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @RaduBerinde, and @rail)

___
*[pkg/roachprod/roachprod.go, line 617 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/72473#-MpMLW_Q2QWDr8ImXcIh:-MpMLW_Q2QWDr8ImXcIi:b-es8vvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad3bd1355463cefdc07e995765fa82adfe391d05/pkg/roachprod/roachprod.go#L617)):*
> ```Go
> // Wipe wipes the nodes in a cluster.
> func Wipe(clusterName string, preserveCerts bool) error {
> 	if err := LoadClusters(); err != nil {
> ```

This repeated pattern where we're populating a global indicates that we need to do some more work to make this a proper library (right now it's half-way inbetween, these are the libraries that are hardest to use correctly - why are we even calling this here is not a question I can answer). I think the clearest place to see this is here in the cli:

https://github.com/cockroachdb/cockroach/blob/ad3bd1355463cefdc07e995765fa82adfe391d05/pkg/cmd/roachprod/main.go#L895-L908

where we're calling a few magic functions that set up the globals before we can invoke commands. The way I would structure this is the following:

```go
// In ./pkg/roachprod/roachprod.go

type Instance struct {
  syncedClusters cloud.Clusters
  clustersDir string
  debugDir string
  // Anything else needed here? For example from InitProviders?
}

func NewInstanceFromEnv() (*Instance, error) {
  // Do the stuff that InitProviders, InitDirs, and LoadClusters do, but don't mess with
  // any globals, instead return an `&Instance{...}`. This method should never os.Exit,
  // instead it should return an error.
}

func (i *Instance) Wipe(clusterName string, preserveCerts bool) error {
  // Same code as before but everything operates on `i` without globals.
}
```

```go
// In pkg/cmd/main.go
func main() {
  // ...
  rpi, err := roachprod.NewInstanceFromEnv()
  if err != nil { /* ... */ }
  config.Roachprod = rpi
  if err := rootCmd.Execute(); err != nil { /* ... */ }
}
```

I'll leave it to your (or rather you and your team :-) ) whether to clean this up in this PR or after. If you have high confidence that this code is now correct & you've validated this sufficiently, I'd support merging now.

**Review by rail — APPROVED** [review]
LGTM, :shipit:
Let's do it!

**Comment by healthy-pod** [comment]
TFTR @tbg and @rail! I will merge now and deal with `LoadClusters` in the next PR. Next PR should remove any traces of the `roachprod binary` and this makes dealing with LoadClusters easier because we will only deal with one state, i.e we won't be calling roachprod in multiple ways.

**Comment by healthy-pod** [comment]
bors r=[tbg,rail]

**Pull request merged**
