### PR TITLE
sql: add tests for add/drop index with virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
Logictests for adding and dropping indexes on virtual columns and
partial indexes using virtual columns in the predicate.

Release notes: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60200#-:-MT77nHs-Yn6PL_Tiiy2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by mgartner** [comment]
Looks like your build failed due to random ordering of the output in some cases.

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60200)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60200#-:-MT8Ib7ME5DR6okF1gvL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
