### PR TITLE
sql: implement SHOW CLUSTER SETTING FOR TENANT

### LINKED ISSUE #77471: sql: store tenant settings in new system table
As per new RFC by Radu and the syntax work performed by Adam.

Jira issue: CRDB-13614

Epic CRDB-6671

### PR DESCRIPTION
**Pull request by knz**
All commits but the last 2 from #77742.
(Reviewers: only the last 2 commits belong to this PR.)

Fixes #77471

Release justification: fixes to high-priority bugs

### CODE REVIEW

**Comment by knz** [comment]
RFAL

**Review by rafiss — CHANGES_REQUESTED** [review]
no major comments; all just nits or optional feedback

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-:-MyzKFOEEQEuSrAyKu6T:bohkapf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[-- commits, line 38 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzGNqS2JnX9Se91szt):*
does this need a release note?
___
*[pkg/settings/bool.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzCUph2KREbcINgHqN:-MyzCUpj1Iees40DaTB-:b-5bzuqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/settings/bool.go#L49)):*
> ```Go
> // DecodeToString decodes and renders an encoded value.
> func (b *BoolSetting) DecodeToString(encoded string) (string, error) {
> 	bv, err := b.DecodeValue(encoded)
> ```

i see it's not related to this PR, but what's the purpose of `DecodeToString`? it looks like it calls `strconv.ParseBool` and then calls `strconv.FormatBool(b)`
___
*[pkg/sql/show_cluster_setting.go, line 101 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzD72U0-BrHUfqm_P4:-MyzD72U0-BrHUfqm_P5:bw5jz0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L101)):*
> ```Go
> 					}
> 
> 					res = string(kvRawVal)
> ```

it seems fine, but i'm just wondering why this needed to change
___
*[pkg/sql/show_cluster_setting.go, line 129 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzE9e_7sX3A6gjHmwY:-MyzE9e_7sX3A6gjHmwZ:buhwgvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L129)):*
> ```Go
> 	setting, ok := val.(settings.NonMaskedSetting)
> 	if !ok {
> 		return nil, errors.AssertionFailedf("setting is masked: %v", name)
> ```

is this supposed to be an assertion error, or would a user-friendly error be better?
___
*[pkg/sql/show_cluster_setting.go, line 143 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzKA4481HYmpdqwKhC:-MyzKA4481HYmpdqwKhD:b-2dyc85) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L143)):*
> ```Go
> }
> 
> func planShowClusterSetting(
> ```

would this more naturally be a method with a `*planner` receiver?
___
*[pkg/sql/show_cluster_setting.go, line 211 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzGAlO3KsQ-NiPCPcd:-MyzGAlO3KsQ-NiPCPce:brxeybd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L211)):*
> ```Go
> 					}
> 					d = &tree.DInterval{Duration: duration.MakeDuration(v.Nanoseconds(), 0, 0)}
> 				case *settings.DurationSettingWithExplicitUnit:
> ```

could `Duration` and `DurationWithInterval` be combined into one case?
___
*[pkg/sql/tenant_settings.go, line 259 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzJckyBjObAGOui_s3:-MyzJckyBjObAGOui_s4:bqltuo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/tenant_settings.go#L259)):*
> ```Go
> 	}
> 
> 	return &delayedNode{
> ```

why is this delayedNode needed here? could it instead use the node returned by `planShowClusterSetting`? and maybe change `planShowClusterSetting` so that it sets the name as we desire

this part could be done before the call to `planShowClusterSetting`

```
			// Evaluate the tenant ID expression.
			_, tenantID, err := resolveTenantID(p, typedTenantID)
			if err != nil {
				return nil, err
			}
			if err := assertTenantExists(ctx, p, tenantID); err != nil {
				return nil, err
			}
```
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 227 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzIAeQ1lzPBjflMkxA:-MyzIAeQ1lzPBjflMkxB:b-7b9vl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/logictest/testdata/logic_test/cluster_settings#L227)):*
> ```
> 
> onlyif config 3node-tenant
> statement error SHOW CLUSTER SETTING FOR TENANT can only be called by system operators
> ```

would the term "system tenant" be more consistent with the error message below on line 236? (instead of "operator")

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rafiss)

___
*[-- commits, line 38 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzGNqS2JnX9Se91szt):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this need a release note?
</blockquote></details>

I'm not sure, since the tenant config override stuff is not accessible to end users? WDYT?
___
*[pkg/settings/bool.go, line 49 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzCUph2KREbcINgHqN:-MzpXamYE0EZgOsuArs0:b31v398) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/settings/bool.go#L49)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see it's not related to this PR, but what's the purpose of `DecodeToString`? it looks like it calls `strconv.ParseBool` and then calls `strconv.FormatBool(b)`
</blockquote></details>

it's part of the interface. Other setting types do not use such a trivial function.

Also it checks for syntax errors in the encoded value, in this case e.g. it verifies that `"wowow"` causes an error and is not just rendered as-is.
___
*[pkg/sql/show_cluster_setting.go, line 101 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzD72U0-BrHUfqm_P4:-Mzpahu07G1n9hF0htgD:b-wlws5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L101)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems fine, but i'm just wondering why this needed to change
</blockquote></details>

Previously, the function was called `showVersionSetting` and it was responsible for returning the *decoded* value.

Now it's called `getCurrentEncodedVersionSettingValue` and is responsible for returning the *encoded* value.

Added a comment to clarify.
___
*[pkg/sql/show_cluster_setting.go, line 129 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzE9e_7sX3A6gjHmwY:-MzpYUuqB9W3PwhMAJ4U:b-pudbdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L129)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this supposed to be an assertion error, or would a user-friendly error be better?
</blockquote></details>

We'd be encountering a bug in Lookup. added a comment to explain.
___
*[pkg/sql/show_cluster_setting.go, line 143 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzKA4481HYmpdqwKhC:-MzpYqG83x0LFZVNsS4w:b-g0djtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L143)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would this more naturally be a method with a `*planner` receiver?
</blockquote></details>

I wanted to be more specific about the exact data that it needs, instead of leaking all the contents of planner into it. You'll notice that the body of the function doesn't need the planner, it's merely passed through from the `constructor` closure to the `getEncodedValue` function. I'd like this property (the fact the body doesn't need planner) to be maintained, which would be hard if the thing was passed as argument.
___
*[pkg/sql/show_cluster_setting.go, line 211 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzGAlO3KsQ-NiPCPcd:-Mzp_GJ3A9jKioZDvPux:b-wlhjh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed319b50133d35a93a2752d400cf76794d6afadf/pkg/sql/show_cluster_setting.go#L211)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could `Duration` and `DurationWithInterval` be combined into one case?
</blockquote></details>

I tried but alas, DecodeValue is not part of the interface (it returns a different type for each instance) so when we combine the cases, the call to DecodeValue becomes invalid.
___
*[pkg/sql/tenant_settings.go, line 259 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzJckyBjObAGOui_s3:-Mzp_yPREO0-Ug7-GQyE:b86r3n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/tenant_settings.go#L259)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is this delayedNode needed here? could it instead use the node returned by `planShowClusterSetting`? and maybe change `planShowClusterSetting` so that it sets the name as we desire

this part could be done before the call to `planShowClusterSetting`

```
			// Evaluate the tenant ID expression.
			_, tenantID, err := resolveTenantID(p, typedTenantID)
			if err != nil {
				return nil, err
			}
			if err := assertTenantExists(ctx, p, tenantID); err != nil {
				return nil, err
			}
```

</blockquote></details>

no, we can't call `.Eval()` (inside `resolveTenantID`) on the typed expr during planning, because it's the planning phase, not execution phase. The call to Eval must be delayed until execution (under `startExec`).

Alternatively, we could remove the call to `resolveTenantID` / `ssertTenantExists` entierly, and put the checks inside the SQL statement like what is done in `delegate/show_all_cluster_settings.go`. WDYT?
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 227 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzIAeQ1lzPBjflMkxA:-MzpaSim6no04rh7j9x-:bo9yx5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/logictest/testdata/logic_test/cluster_settings#L227)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would the term "system tenant" be more consistent with the error message below on line 236? (instead of "operator")
</blockquote></details>

Arguably it's the one saying "system tenant" that's inconsistent with the rest :)

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-:-MzvUxBwAPTEtlcO4VeX:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RaduBerinde, and @rafiss)

___
*[pkg/sql/tenant_settings.go, line 259 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzJckyBjObAGOui_s3:-MzvUM5J8ARJVWpox1-g:bfbjg2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/tenant_settings.go#L259)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

no, we can't call `.Eval()` (inside `resolveTenantID`) on the typed expr during planning, because it's the planning phase, not execution phase. The call to Eval must be delayed until execution (under `startExec`).

Alternatively, we could remove the call to `resolveTenantID` / `ssertTenantExists` entierly, and put the checks inside the SQL statement like what is done in `delegate/show_all_cluster_settings.go`. WDYT?
</blockquote></details>

i see, thanks. yes it sounds good to keep the `resolveTenantID` in the exec phase like this

for consistency with `show all` i could see it being helpful to do the resolve/assert in SQL, but i don't feel strongly about it

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rafiss)

___
*[pkg/sql/tenant_settings.go, line 259 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/77794#-MyzJckyBjObAGOui_s3:-Mzzmm7p2jBtMZX4CWGP:brt7f8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5dd0336ef4b3e4a79dc0a9a1517fbdb6012dda9/pkg/sql/tenant_settings.go#L259)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see, thanks. yes it sounds good to keep the `resolveTenantID` in the exec phase like this

for consistency with `show all` i could see it being helpful to do the resolve/assert in SQL, but i don't feel strongly about it
</blockquote></details>

ok, simplified.

**Comment by knz** [comment]
TFYR!

bors r=rafiss

**Pull request merged**
