### PR TITLE
json,tree,geopb: remove dependency from kvpb on geo

### PR DESCRIPTION
**Pull request by ajwerner**
The `kvpb` protobuf package shouldn't depend on geospatial C dependencies. It was a mistake that they did. This PR has two commits:

1) Move `geoindex.Config` to `geopb.Config`.
2) Move the code to convert geometry and geography data to json from the low-level json package (which kvpb depends on via coldata) to tree which already depends on both types.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 49 of 49 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @michae2)

___
*[`pkg/geo/geopb/config.proto` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-NljRImm4bSlet1R0i7f:-NljRImm4bSlet1R0i7g:b2f4vsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfed3e097bf71263e596471ff74ccf4e567c5aa/pkg/geo/geopb/config.proto#L12)):*
> ```proto
> 
> syntax = "proto3";
> package cockroach.geo.geopb;
> ```

Don't we need to keep this protobuf package name unchanged to keep backwards compatibility? E.g. in `processors_sql.proto` we have a comment about it.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/geo/geopb/config.proto` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-NljRImm4bSlet1R0i7f:-NljTG0lEomcxyQ4qHMa:b-wu6ijv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfed3e097bf71263e596471ff74ccf4e567c5aa/pkg/geo/geopb/config.proto#L12)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Don't we need to keep this protobuf package name unchanged to keep backwards compatibility? E.g. in `processors_sql.proto` we have a comment about it.
</blockquote></details>

I know it matters for gRPC methods and if you use `google.Any` or if you use the JSON stuff, but I didn't think it mattered otherwise. If you look at the PR that introduced that warning, there was a gRPC service and methods defined in the file at the time: https://github.com/cockroachdb/cockroach/pull/3657

I'm happy to not change the package name though

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/geo/geopb/config.proto` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-NljRImm4bSlet1R0i7f:-NljTpAQA9st_om6BHCr:bdfx8ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfed3e097bf71263e596471ff74ccf4e567c5aa/pkg/geo/geopb/config.proto#L12)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I know it matters for gRPC methods and if you use `google.Any` or if you use the JSON stuff, but I didn't think it mattered otherwise. If you look at the PR that introduced that warning, there was a gRPC service and methods defined in the file at the time: https://github.com/cockroachdb/cockroach/pull/3657

I'm happy to not change the package name though
</blockquote></details>

Err https://github.com/cockroachdb/cockroach/pull/36572

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/geo/geopb/config.proto` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-NljRImm4bSlet1R0i7f:-NljgO0J4EMVVUBv_Gi2:bgt3lki) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfed3e097bf71263e596471ff74ccf4e567c5aa/pkg/geo/geopb/config.proto#L12)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Err https://github.com/cockroachdb/cockroach/pull/36572
</blockquote></details>

Hm, perhaps you're right, but I'm not familiar enough with this stuff to approve it. I know that @nvanbenschoten recently ran into some difficulties with errors and protobuf movement (which under the hood IIRC did use `google.Any` somewhere), so maybe Nathan can sign off on changing the package name here.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2, @nvanbenschoten, and @yuzefovich)

___
*[`pkg/geo/geopb/config.proto` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-NljRImm4bSlet1R0i7f:-NltHc6fBwhKfoICTnAy:beaw0ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cfed3e097bf71263e596471ff74ccf4e567c5aa/pkg/geo/geopb/config.proto#L12)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, perhaps you're right, but I'm not familiar enough with this stuff to approve it. I know that @nvanbenschoten recently ran into some difficulties with errors and protobuf movement (which under the hood IIRC did use `google.Any` somewhere), so maybe Nathan can sign off on changing the package name here.
</blockquote></details>

I moved the package name back to avoid any controversy.

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm:

bors r=yuzefovich

> Reviewed 9 of 9 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116570#-:-Nly5upWBSCnDVS-UOpE:b-yqhcz8)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

**Pull request merged**
