### PR TITLE
sql: fix TestQueryProgress flake

### LINKED ISSUE #51356: sql: TestQueryProgress failed
[(sql).TestQueryProgress failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2084372&tab=buildLog) on [master@4c2da99f879bc2bc3922bc421ac8fee80995b134](https://github.com/cockroachdb/cockroach/commits/4c2da99f879bc2bc3922bc421ac8fee80995b134):

```
=== RUN   TestQueryProgress
    TestQueryProgress: test_log_scope.go:77: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestQueryProgress044936620
    TestQueryProgress: test_log_scope.go:58: use -show-logs to present logs inline
    TestQueryProgress: conn_executor_test.go:569: waiting for query to make progress...
    TestQueryProgress: conn_executor_test.go:529: stalling on scan 6 at /Table/53/1/701/0 and waiting for test to unblock...
    TestQueryProgress: conn_executor_test.go:571: query is now stalled. checking progress...
    TestQueryProgress: conn_executor_test.go:587: 
        	Error Trace:	conn_executor_test.go:587
        	Error:      	Expect "executing (38.40%)" to match "executing \([45]\d\."
        	Test:       	TestQueryProgress
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestQueryProgress044936620
--- FAIL: TestQueryProgress (0.39s)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestQueryProgress PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestQueryProgress.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
Release justification: non-production code change

The test would not be using the latest statistics, which would cause an
inability to report progress.

Release note: None

Fixes #51356

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Nice, I couldn't figure this out ... i don't really understand how this works but LGTM

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54043#-:-MGio5yqB013uvUzf8E2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
TFTR, will also backport to 20.1 since the test fails on that branch too. It's not necessary to backport this to 20.2 since the test is skipped on that branch.

bors r=rytaft

**Comment by rytaft** [comment]
Thanks! I also suggest backporting to 19.2, since the stats cache changes were backported there.

**Comment by asubiotto** [comment]
I think this test was added mid-november 2019 so shouldn't be included on that branch, but I'll double check.

**Pull request merged**
