### PR TITLE
sql: Add command to show range information about a row/rows

### LINKED ISSUE #40679: sql: Get range ID for a specific row
Currently, you can see how a table maps to underlying key-value ranges (`show ranges`). But you can't see which range contains the data for a specific row. This ability would let users validate, for example, that when you change the partition value of a row (e.g., `chicago` to `new york`), we move that record to the correct partition.

### PR DESCRIPTION
**Pull request by rohany**
This PR adds a command to see range information about a row.

The syntax of the command is as follows:

```
SHOW RANGE FROM TABLE <t> FOR ROW (row, values, here)
SHOW RANGE FROM INDEX <t@i> FOR ROW (row, values, here)
```

It returns
start key, end key, range id, leaseholder id, leaseholder locality,
replica ids, and replica localities.

Fixes #40679.

Release justification: Low risk improvement to visibility.

Release note (sql change): Add a command to show range information for a particular
row.

### CODE REVIEW

**Comment by rohany** [comment]
cc @awoods187 @drewdeally

**Comment by rohany** [comment]
I want to get some feedback on this approach / syntax before digging and fixing some TODO's and adding tests. What are peoples opinions on this?

**Comment by rohany** [comment]
Sample usage:
```
root@127.0.0.1:61131/movr> show range from table vehicles for row ('san francisco');
     start_key     |          end_key           | range_id | lease_holder | lease_holder_locality | replicas |                           replica_localities
+------------------+----------------------------+----------+--------------+-----------------------+----------+------------------------------------------------------------------------+
  /"san francisco" | /"san francisco"/PrefixEnd |      120 |            5 | region=us-west1,az=b  | {4,5,6}  | {"region=us-west1,az=a","region=us-west1,az=b","region=us-west1,az=c"}
(1 row)

Time: 9.042ms
```

**Comment by drewdeally** [comment]
Let’s connect Monday am I’ll ping you on slack

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @rohany)

___
*[pkg/sql/delegate/show_range_for_row.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpTve6-7tkecNEO8XEl:-LpTve604YVAAdzEugv0:byvd31h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6637869aab2e8e3709aa7cc3255dda2f80656a53/pkg/sql/delegate/show_range_for_row.go#L73)):*
> ```Go
> 	for i := 0; i < len(keyDatums); i++ {
> 		columnIDs = append(columnIDs, sqlbase.ColumnID(idx.Column(i).ColID()))
> 		colIdentityMap[sqlbase.ColumnID(idx.Column(i).ColID())] = i
> ```

This code is pretty sketchy - in principle the opt catalog implementation is free to make `ColID()` something else. I would move all this functionality to build a key into a catalog method (probably on the `Index`)

**Comment by rohany** [comment]
To handle extra columns being added with secondary indexes, I pushed some of this logic into the catalog, and now require the entire row, rather than just the columns explicitly used in the index.

**Comment by knz** [comment]
cc @BramGruneir who was asking me about this today.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/delegate/show_range_for_row.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpTve6-7tkecNEO8XEl:-LpUM-3g5pOpe1OpxqRO:b-l0sehd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6637869aab2e8e3709aa7cc3255dda2f80656a53/pkg/sql/delegate/show_range_for_row.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This code is pretty sketchy - in principle the opt catalog implementation is free to make `ColID()` something else. I would move all this functionality to build a key into a catalog method (probably on the `Index`)
</blockquote></details>

Even if I move it into the catalog, I don't want to duplicate the logic that Index.Column does of searching through columnIDs/extraColumnIDs/StoredCols

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @RaduBerinde, and @rohany)

___
*[pkg/sql/delegate/show_range_for_row.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpTve6-7tkecNEO8XEl:-LpUOjsdBqGZSP9qMtWb:ba644dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6637869aab2e8e3709aa7cc3255dda2f80656a53/pkg/sql/delegate/show_range_for_row.go#L73)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Even if I move it into the catalog, I don't want to duplicate the logic that Index.Column does of searching through columnIDs/extraColumnIDs/StoredCols
</blockquote></details>

Sure you can call that code (you can probably call `lookupColumnOrdinal` directly) - it would be the opt catalog implementation using a specific detail of that same implementation. We wouldn't be breaking through the abstraction like ware doing here.

Note that the only reason this code isn't under `opt/` is because it is shared by the heuristic planner (which is being removed); this code might move under `opt/` afterward. We really don't want `opt` code to care about the internal details of descriptors etc.

**Review by rohany — COMMENTED** [review]
Added some tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-LpUXetXEBAFmnFAoTJk:b51dhys)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Review by knz — CHANGES_REQUESTED** [review]
I don't see the tests, where are they?

> Reviewed 5 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-LpXL4xCDOZHxOxWhaq-:bsu2l8l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/opt_catalog.go, line 967 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXK3CJA_gcFei6iPdN:-LpXK3CJA_gcFei6iPdO:b-22g42k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L967)):*
> ```Go
> 
> // EncodeKey is part of the cat.Index interface.
> func (oi *optIndex) EncodeKey(values []tree.Datum) (roachpb.Key, error) {
> ```

My preference + recommendation would be to put the encode logic in a SQL built-in function, if you feel able to achieve this.

Then the SQL query could be 
```sql
CASE WHEN r.start_key < crdb_internal.encode_key(table_id, index_id, value_tuple) ..
```

The advantage of this is that we then can then use the built-in function for other purposes.

(If you don't feel confident in this, we can push to later)
___
*[pkg/sql/opt_catalog.go, line 982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXJccB4AnN2-67hw5o:-LpXJccC7I3UXq_kvUv1:b-w1k9ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L982)):*
> ```Go
> 
> 	// TODO (rohany): is this comparison always valid? i.e. does proto ensure that the addresses are the same?
> 	if oi.desc == &oi.tab.desc.PrimaryIndex {
> ```

Compare the index IDs, that's reliable.
___
*[pkg/sql/opt_catalog.go, line 1006 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXJlou1mBAbVLgB9RL:-LpXJlou1mBAbVLgB9RM:bhbcufi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L1006)):*
> ```Go
> 		return nil, err
> 	}
> 	// TODO (rohany): what to do here for an inverted index?
> ```

Return a "feature not supported" error.
That should always be your go-to implementation. Silently failing or ignoring what the user wants is _never_ a good option.
___
*[pkg/sql/delegate/show_range_for_row.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXKWuU47R8qvTH4tXs:-LpXKWuU47R8qvTH4tXt:b4h4vd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/delegate/show_range_for_row.go#L43)):*
> ```Go
> 	for i, expr := range n.Key {
> 		colTyp := table.Column(i).DatumType()
> 		typedExpr, err := sqlbase.SanitizeVarFreeExpr(expr, colTyp, "range-for-row", &semaCtx, false)
> ```

Note: expected type != mandatory type. You probably need to check the type matches after type checking, still.
___
*[pkg/sql/parser/sql.y, line 3860 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXL-HEAPlXvJEq-Ywa:-LpXL-HEAPlXvJEq-Ywb:b-cdfvyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/parser/sql.y#L3860)):*
> ```Yacc
>   }
> 
> show_range_for_row_stmt:
> ```

Missing:

- tests in parse_test.go
- help text
- test for help text

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/parser/sql.y, line 3860 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXL-HEAPlXvJEq-Ywa:-LpXLBKMAziPTSj0azt3:b-sstfuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/parser/sql.y#L3860)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Missing:

- tests in parse_test.go
- help text
- test for help text
</blockquote></details>

also, the error branch.

**Comment by BramGruneir** [comment]
@rohany, this is wonderful!  

Any way to get the node ids for the replicas as well?  

Also, please make sure this works with composite primary keys, since they are very common with partitioned tables.

**Comment by knz** [comment]
For the node ID I'd say it's trivial to do a SQL join to extract the other things, so I'd suggest only adding it in the base statement if it's a freebie cost-wise.

The point about composite keys is super important however. Rohan please add a test for that.

**Comment by knz** [comment]
Yes correct.

Oh and another thing since we're in that area, I'd invite a test for composite encodings too (a subtly different thing: a single column that has separate parts for the key and the value)

**Comment by rohany** [comment]
What do you mean by composite encodings? Can you give a small example?

**Comment by knz** [comment]
Columns of type DECIMAL, collated strings and (IIRC) FLOAT have two parts when they are listed in an index: a key part that's used to narrow K/V lookups, and a value part that equality-compared during SQL lookups.

**Comment by BramGruneir** [comment]
Bah, I meant composite keys, not encodings.  But yes, make sure it works with encodings too!

**Review by RaduBerinde — APPROVED** [review]
Opt part LGTM, thanks for the refactor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-LpYyTtd6Vc4kDSdxthw:bs70biq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/opt/cat/index.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpYxcPr63DqT4y7-V7Y:-LpYxcPr63DqT4y7-V7Z:b-p924oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt/cat/index.go#L136)):*
> ```Go
> 
> 	// EncodeKey creates a key for a given row of the table associated with this index.
> 	EncodeKey(values []tree.Datum) (roachpb.Key, error)
> ```

[nit] Need to explain the `values` argument, specifically that there is a value for each column table, in the order of their ordinals (I assume)

**Comment by rohany** [comment]
I added alot more tests, and performed a decently large refactor moving the key encoding logic into a builtin function. PTAL

**Comment by rohany** [comment]
Friendly ping

**Review by knz — COMMENTED** [review]
Thanks for all the improvements. Just a few minor things and this is good to go.

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-Lq6waMH2xtfBe913dLq:bl7sei4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/delegate/show_range_for_row.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXKWuU47R8qvTH4tXs:-Lq6tY_kDS6zLi0ilIJ9:b-o5eddu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/delegate/show_range_for_row.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Note: expected type != mandatory type. You probably need to check the type matches after type checking, still.
</blockquote></details>

sorry I may have missed your earlier answer on this point. What do you think about this?
Have you tried to pass a value with the wrong type, what happens?
___
*[pkg/sql/sem/builtins/builtins.go, line 2961 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vcsx24ETKiDFKmZ-:-Lq6vcsx24ETKiDFKmZ0:b-1axc7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2961)):*
> ```Go
> 				rowDatums, ok := tree.AsDTuple(args[2])
> 				if !ok {
> 					return nil, errors.Newf("expected DTuple, found %s", args[2])
> ```

`errors.AssertionFailedf`
___
*[pkg/sql/sem/builtins/builtins.go, line 2970 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vn1D7DBqInJIMdn8:-Lq6vn1D7DBqInJIMdn9:b-t0kjci) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2970)):*
> ```Go
> 
> 				if len(rowDatums.D) != len(tableDesc.Columns) {
> 					return nil, errors.New("number of values provided must equal number of columns in table")
> ```

`pgerror.Newf(pgcode.Syntax, ...)`
___
*[pkg/sql/sem/builtins/builtins.go, line 2983 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vpCu2-Urf3aL0kdn:-Lq6vpCu2-Urf3aL0kdo:b-j9v90h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2983)):*
> ```Go
> 					if d.ResolvedType() == types.Unknown {
> 						if !tableDesc.Columns[i].Nullable {
> 							return nil, errors.New("NULL provided as a value for a non-nullable column")
> ```

`pgerror.Newf(pgerror.NotNullViolation, ...)`
___
*[pkg/sql/sem/builtins/builtins.go, line 2990 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vzkNDbal36c77-Xw:-Lq6vzkNDbal36c77-Xx:b-40hkr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2990)):*
> ```Go
> 						newDatum, err = tree.PerformCast(ctx, d, expectedTyp)
> 						if err != nil {
> 							return nil, errors.Wrap(err, "try to explicitly cast each value to the corresponding column type")
> ```

`errors.WithHint`
___
*[pkg/sql/sem/builtins/builtins.go, line 3020 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6w1-w4GD3ICInux9d:-Lq6w1-xDgVWS5kTq-e6:blwj19m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L3020)):*
> ```Go
> 				// which this command does not support right now.
> 				if len(res) > 1 {
> 					return nil, errors.New("inverted indexes not supported right now")
> ```

file an issue then use `unimplemented.NewWithIssue(.., ...)`

**Review by rohany — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-Lq72UDS1A1a4yKRIIq5:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/opt_catalog.go, line 967 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXK3CJA_gcFei6iPdN:-LpZLZHs3TDbkbuNvG0p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L967)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

My preference + recommendation would be to put the encode logic in a SQL built-in function, if you feel able to achieve this.

Then the SQL query could be 
```sql
CASE WHEN r.start_key < crdb_internal.encode_key(table_id, index_id, value_tuple) ..
```

The advantage of this is that we then can then use the built-in function for other purposes.

(If you don't feel confident in this, we can push to later)
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXJccB4AnN2-67hw5o:-LpZLZ_q6UJd-fI_8p3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L982)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Compare the index IDs, that's reliable.
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 1006 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXJlou1mBAbVLgB9RL:-LpZL_FZBTO3JNYPfNIa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/opt_catalog.go#L1006)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Return a "feature not supported" error.
That should always be your go-to implementation. Silently failing or ignoring what the user wants is _never_ a good option.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_range_for_row.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXKWuU47R8qvTH4tXs:-LpZLc5q2Fy6EPouFBWA:b-hspvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/delegate/show_range_for_row.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

sorry I may have missed your earlier answer on this point. What do you think about this?
Have you tried to pass a value with the wrong type, what happens?
</blockquote></details>

SanitizeVarFreeExpr is already performing that check, so an error is thrown.
___
*[pkg/sql/parser/sql.y, line 3860 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-LpXL-HEAPlXvJEq-Ywa:-LpZOagv6HcHZH8b7reL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab415bffb82aa9f23cf0eab5327bc68caf42047/pkg/sql/parser/sql.y#L3860)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

also, the error branch.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2961 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vcsx24ETKiDFKmZ-:-Lq71bUWASeP1tYK0Lv6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2961)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.AssertionFailedf`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2970 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vn1D7DBqInJIMdn8:-Lq71iGK6ENP-aowPyPa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2970)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`pgerror.Newf(pgcode.Syntax, ...)`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2983 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vpCu2-Urf3aL0kdn:-Lq71t7r5BmkyadCQP0W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2983)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`pgerror.Newf(pgerror.NotNullViolation, ...)`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 2990 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6vzkNDbal36c77-Xw:-Lq72CvA4RxPBOjvzhKL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L2990)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.WithHint`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 3020 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-Lq6w1-w4GD3ICInux9d:-Lq72N8Q27Myat40nEEl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fd30572578357c693b125be42b8ba4e88f03170/pkg/sql/sem/builtins/builtins.go#L3020)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

file an issue then use `unimplemented.NewWithIssue(.., ...)`
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: Thank you!!!

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40954#-:-Lq7K7xvALBTqrrvdUIv:br1z6vb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rohany** [comment]
bors r=knz

**Comment by rohany** [comment]
Thanks for the reviews!

**Comment by jseldess** [comment]
Wow, thanks for getting this into 19.2, @rohany!

**Comment by knz** [comment]
I do think this should be marked as "experimental" in docs though, it's likely the UX will evolve in a backward-incompatible manner in the next release.

**Comment by rohany** [comment]
should i rename the command to `show experimental_range ... `?

**Comment by knz** [comment]
I don't think you need to rename. We're making it clearer in docs that anything that SHOWs outputs is susceptible for change anyway. A "experimental" call out in docs will be another reminder on top of that.

**Comment by ericharmeling** [comment]
@rohany I know this was already reviewed and merged, but I have a couple UX questions:

1. Is there a reason why we use `SHOW RANGE` instead of `SHOW RANGES` for this statement (other than it making more practical sense)? I know `SHOW RANGE` and `SHOW RANGES` are separated in the grammar, but it could be slightly confusing to document them as separate things (i.e. on separate pages), since they are returning the same thing, just with different scopes. It's also confusing that you can't just append "`FOR ROWS`" to an otherwise-valid `SHOW RANGES FROM TABLE <table>` or `SHOW RANGES FROM TABLE <index>`. Making `SHOW RANGE` an alias for `SHOW RANGES` (and vice-versa) might fix that, but IDK if that's a practical solution.

2. > To handle extra columns being added with secondary indexes, I pushed some of this logic into the catalog, and now require the entire row, rather than just the columns explicitly used in the index.

   I don't understand what this means, but it took me a while to realize that you have to specify all values in the row, and not just an ordinal row number or the values in the index columns, in order for the statement to work at all for `cockroach demo` tables. (e.g., running `SHOW RANGE FROM TABLE users FOR ROW (1, 2);` or `SHOW RANGE FROM TABLE users FOR ROW ('san francisco');` just returns `pq: number of values in row must equal number of columns in the requested table`). This doesn't seem to be the case for other tables though... (looking at https://github.com/cockroachdb/cockroach/pull/40954/files#diff-b4c48a112a46763098fb659a8747b051R431). Am I missing something here...?

**Comment by awoods187** [comment]
@ericharmeling also see https://github.com/cockroachdb/cockroach/issues/41422 and https://github.com/cockroachdb/cockroach/issues/41421

**Comment by rohany** [comment]
@ericharmeling 

Re 1. It is confusing i think, but this command will never return more than one range, so i don't think it makes sense for it to be called show ranges vs show range. 
Re 2. that comment is outdated. I'm sorry, i should have put this into the release note, but I forgot. I created a new builtin function called `encode_key`, which takes in a table id, index id and row, and constructs a full key for the row, and use that here. In the link you sent, all the table require needing all the values in the row.

**Comment by ericharmeling** [comment]
@awoods187 Should we call this experimental in the syntax if its behavior is subject to change? I'm marking it as experimental in the docs.

**Comment by awoods187** [comment]
I think @knz 's proposal is that since SHOW is inherently porcelain it's okay for us to not name this something like `SHOW EXPERIMENTAL RANGE FROM TABLE`. That being said, I expect this format to change in 20.1. I could see us leaving it as SHOW with no mention, providing a docs page mention that this is subject to change, or taking additional action. What do you want to do?

**Comment by ericharmeling** [comment]
@jseldess and I spoke about this briefly this morning. I think that SHOW statements (and other "porcelain" but maybe not "experimental" features) are something around which the API stability doc will provide a lot of clarity.

For now (see https://github.com/cockroachdb/docs/pull/5612), I added a note about this statement being experimental, and I added this statement to the list of "experimental features".

**Pull request merged**
