### PR TITLE
sql: skip dropped descriptors in REASSIGN OWNED BY

### PR DESCRIPTION
**Pull request by fqazi**
This PR will make the following changes

1. REASSIGN OWNED BY incorrectly worked on all descriptors previously, which meant this operation would attempt to modify authorization on descriptors that were dropped as well. This could be problematic in some cases since this operation needs the parent objects to be around for tables to be successful.
2. getQualifiedTableName did not properly return an error if the parent schema object was missing.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Does `DROP OWNED BY` have any sort of similar problem?

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90291#-:-NEm4Gc-9qH3mfLDm2tP:b-rl47st)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by fqazi — COMMENTED** [review]
DROP OWNED BY shouldn't have the same problem since we make the element list based on the namespace table (for schemas). So, if the entry is removed during the pre-commit phase then it won't be visible when building the set of elements. Additionally, we filter out elements that are marked as absent @ajwerner. I was paranoid and stepped through a debugger to better understand why its safe. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90291#-:-NEq0nKvB9nLq12zDmw0:b833fj8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90291#-:-NEqQj3Z0woX8g6OyOML:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@ajwerner TFTR!

bors r+

**Pull request merged**
