### PR TITLE
release-22.1: security: don't enable scram by default

### LINKED ISSUE #80280: [placeholder] change defaults in 22.1
See discussion in #80246

### PR DESCRIPTION
**Pull request by knz**
As per issue #80246: we want to use a different upgrade path
to SCRAM between self-hosted and CockroachCloud.

Fixes  #80280.

Release justification: prevents a UX regression for client apps

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by rafiss** [comment]
just curious how this will affect our internal cluster when we update it to v22.1.0?

**Comment by knz** [comment]
> just curious how this will affect our internal cluster when we update it to v22.1.0

for our internal clsuter that's alerady upgraded to scram, this will prevent any *new* sql user credentials from being auto-converted.

Already-converted credentials will not be toruched. We can revert them back by issuing an ALTER USER WITH PASSWORD statement explicitly.

**Review by rafiss — APPROVED** [review]
thank you!

**Comment by knz** [comment]
i think i fixed the tests. feel free to merge on green

**Pull request merged**
