### PR TITLE
ui next: Line Graph Component

### PR DESCRIPTION
**Pull request by mrtracy**
Commit adds the `LineGraph` component. This component is designed to be placed
inside of a MetricsDataProvider component. Most of the NVD3 code has been taken
directly from the previous UI, with some modifications to work with the new data
model.

Commit also changes the name of 'Selector' to 'Metric', to avoid confusion with
the Reselect library's selectors.

Commit also adds a TODO list in app/app.tsx, cataloging the remaining
unimplemented components and pages in the ui next project.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6638)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/next/app/components/linegraph.tsx, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KHWYLj8OYILLbhh5GTg:-KHWYLj9TWKz-Bcz7DyL:1014770977) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L12)):*
> ```XML
> 
> type TSResponseMessage = cockroach.ts.TimeSeriesQueryResponseMessage;
> type TSResult = cockroach.ts.TimeSeriesQueryResponse.Result;
> ```

shouldn't this be `ResultMessage`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/next/app/components/linegraph.tsx, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KHWYLj8OYILLbhh5GTg:-KH_p9yolIjKLwVPDQYi:286898236) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L12)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this be `ResultMessage`?</details>
No, actually; the repeated property "Results" on a TSResponseMessage is of type Result, not ResultMessage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/next/app/components/linegraph.tsx, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KHWYLj8OYILLbhh5GTg:-KHa2L4YUwBwe9AsM2G7:-1912744063) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L12)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> No, actually; the repeated property "Results" on a TSResponseMessage is of type Result, not ResultMessage.</details>
Ah, I see. Can the `let result: TSResult = this.props.data.results[idx];` below be written as `let result = this.props.data.results[idx];` without loss of type information?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638)*

**Comment by maxlang** [comment]
:lgtm:

<details><summary><i>Previously, mrtracy wrote…</i></summary>
> #### ui next: Line Graph Component
> 
> Commit adds the `LineGraph` component. This component is designed to be placed
> 
> inside of a MetricsDataProvider component. Most of the NVD3 code has been taken
> 
> directly from the previous UI, with some modifications to work with the new data
> 
> model.
> 
> 
> 
> Commit also changes the name of 'Selector' to 'Metric', to avoid confusion with
> 
> the Reselect library's selectors.
> 
> 
> 
> Commit also adds a TODO list in app/app.tsx, cataloging the remaining
> 
> unimplemented components and pages in the ui next project.
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/next/app/components/graphs.tsx, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_l5S0AEtjtdC3jAwf:-KH_l5S0AEtjtdC3jAwg:-1597798115) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/graphs.tsx#L52)):*
> ```XML
>     yLow: 0,
>     yHigh: 1,
>   };
> ```

How is this used? I see mention of a `getDefaultProps` function in the docs.

---

*[ui/next/app/components/linegraph.tsx, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_vOFwiUYM5BZKtpRE:-KH_vOFxOwcIBI2Age8M:-1254324449) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L44)):*
> ```XML
>     (props: {children?: any}) => props.children,
>     (children) => {
>       let axes: React.ReactElement<AxisProps>[] = findChildrenOfType(children, Axis);
> ```

Just for my own edification - currently Axis will always be one level below LineGraph right?

---

*[ui/next/app/containers/cluster.tsx, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_lQe6EcQgMd18q-7V:-KH_lQe6EcQgMd18q-7W:-601490901) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/containers/cluster.tsx#L40)):*
> ```XML
>       <Metric name="cr.node.sql.delete.count" title="Delete" nonNegativeRate />
>     </Axis>
>   </LineGraph>,
> ```

I love the way this reads now.

---

*[ui/next/app/util/find.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_nOhJUPlbTkGPD9RG:-KH_nOhJUPlbTkGPD9RH:-1294925159) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/util/find.ts#L21)):*
> ```XML
>       let { props } = child;
>       if (props.children) {
>         childrenToSearch = React.Children.toArray(props.children).concat(childrenToSearch);
> ```

Can also be written `childrenToSearch.unshift(...React.Children.toArray(props.children))` for ES6 coolness.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-:-KHa4Gozc0Y8QpIJkJgg:1417088721)*

**Comment by mrtracy** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[ui/next/app/components/graphs.tsx, line 52 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_l5S0AEtjtdC3jAwf:-KHa5luVV9X_wUiR7jJN:1392127602) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/graphs.tsx#L52)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> How is this used? I see mention of a `getDefaultProps` function in the docs.</details>
If you instantiate a react component and don't send it a prop which is in the "defaultProps" collection, the default value is used.

---

*[ui/next/app/components/linegraph.tsx, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KHWYLj8OYILLbhh5GTg:-KHa6NBc6Sgb50UI2Iw7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L12)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, I see. Can the `let result: TSResult = this.props.data.results[idx];` below be written as `let result = this.props.data.results[idx];` without loss of type information?</details>
Done.

---

*[ui/next/app/components/linegraph.tsx, line 44 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_vOFwiUYM5BZKtpRE:-KHa5wTXBDCNdCUsZ9kU:677251276) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/components/linegraph.tsx#L44)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Just for my own edification - currently Axis will always be one level below LineGraph right?
> 
> </details>
Yes.

---

*[ui/next/app/containers/cluster.tsx, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_lQe6EcQgMd18q-7V:-KHa60MpOxzqZyRUVjQd:-899833069) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/containers/cluster.tsx#L40)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I love the way this reads now.</details>
Yep, it's a lot better.  Really happy with how this turned out; really, it convinces me that React is totally compatible with the concept of "Web Components".

---

*[ui/next/app/util/find.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638#-KH_nOhJUPlbTkGPD9RG:-KHaVkFEU1K7--fUW11h:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a9305b88e21c47625c9f45ec3f3f15410a4f12/ui/next/app/util/find.ts#L21)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Can also be written `childrenToSearch.unshift(...React.Children.toArray(props.children))` for ES6 coolness.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6638)*

**Pull request merged**
