### PR TITLE
keys: pretty print /Meta* keys recursively

### LINKED ISSUE #3228: keys: better PrettyPrint for meta keys
`keys.PrettyPrint` displays meta keys as: `/System/Meta2/"\xff\f\x03\xe8"`. Meta keys are keys about keys. `PrettyPrint` should recursively pretty print the `\xff\f\x03\xe8` suffix of the meta key which is itself a key.

@veteranlu

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #3228.
Closes #3237.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4055)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[keys/printer.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkDW4gkFl046KQOGQ:-K9PkDW4gkFl046KQOGR:-1807703707) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L235)):*
WriteString here and in a few other places?

---

*[keys/printer.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkJOBfJYvOFoNNTrn:-K9PkJOBfJYvOFoNNTro:-1777834068) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L247)):*
`buf.WriteString(e.name+e.ppFunc(key))`?

---

*[keys/printer.go, line 253 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkN1pqwG-QVedqFks:-K9PkN1pqwG-QVedqFkt:-1711205994) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L253)):*
why is `[]byte()` needed here?

---

*[keys/printer.go, line 260 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkRjJ7T2FOFIILAd-:-K9PkRjJ7T2FOFIILAd0:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L260)):*
ditto

---

*[keys/printer.go, line 298 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkUctkWAAZE0gYIrJ:-K9PkUctkWAAZE0gYIrK:-1402355816) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L298)):*
`key.Equal(k.value)`?

---

*[keys/printer.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkYdA6PhQ-DOYFfOO:-K9PkYdA6PhQ-DOYFfOP:-1654088746) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L308)):*
just concat the strings

---

*[keys/printer.go, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9Pka6JEK67EG1tZJg6:-K9Pka6JEK67EG1tZJg7:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L311)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[keys/printer.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkDW4gkFl046KQOGQ:-K9SPxj7sT6Fkj6TM3gp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L235)):*
Done.

---

*[keys/printer.go, line 247 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkJOBfJYvOFoNNTrn:-K9SPy7HFJxFvnbpMKBp:-143944570) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L247)):*
Yeah, but this isn't performance critical code so I'd rather keep the `fmt.Fprintf` for now as I feel it is (very slightly) easier to read.

---

*[keys/printer.go, line 253 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkN1pqwG-QVedqFks:-K9SQ566hyR2REPQoPhs:-2018788215) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L253)):*
`roachpb.Key` implements [fmt.Formatter](https://golang.org/pkg/fmt/#Formatter). If we didn't cast to a `[]byte` we'd recursively call ourselves.

---

*[keys/printer.go, line 298 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkUctkWAAZE0gYIrJ:-K9SREbhLlYB_ZadWbBp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L298)):*
Done.

---

*[keys/printer.go, line 308 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9PkYdA6PhQ-DOYFfOO:-K9SRS0qA_IOey3lKn67:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L308)):*
Done.

---

*[keys/printer.go, line 311 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-K9Pka6JEK67EG1tZJg6:-K9SRRkl9Y83di4ohYjU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a5e0e126cde63c02e837a1cadc918a7d08f45b/keys/printer.go#L311)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055)*

**Comment by petermattis** [comment]
@tamird: Was that review an LGTM?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-:-K9XV2eNfzogF0a6ftAY:-1860173286)*

**Comment by tamird** [comment]
yep lgtm

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4055#-:-K9XVQkjG_YQlDNFY7rO:1003042037)*

**Pull request merged**
