### PR TITLE
kvserver: use type-safe atomics in raftSendQueue

### PR DESCRIPTION
**Pull request by pav-kv**
Go 1.19 introduced atomic types that enforce atomic access to variables, which in many situation is less error-prone. This commit resolves a TODO to take advantage of these types.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
In https://github.com/cockroachdb/cockroach/pull/88506, I mentioned to @arulajmani that leaving our [go directive](https://go.dev/ref/mod#go-mod-file-go) in `go.mod` set to 1.17 should have prevented use of the new atomic stdlib additions from compiling. I think I misunderstood the go directive. It prevents use of new language features (e.g. generics), but not of library additions (e.g. atomic.Int64).

So this LGTM.

**Comment by pavelkalinnikov** [comment]
> In #88506, I mentioned to @arulajmani that leaving our [go directive](https://go.dev/ref/mod#go-mod-file-go) in `go.mod` set to 1.17 should have prevented use of the new atomic stdlib additions from compiling. I think I misunderstood the go directive. It prevents use of new language features (e.g. generics), but not of library additions (e.g. atomic.Int64).
> 
> So this LGTM.

Huh, my previous knowledge of this directive is: it just instructs which `go.mod` syntax/features to use, but apparently it's more nuanced than that.

**Comment by pavelkalinnikov** [comment]
bors r=nvanbenschoten

**Comment by pavelkalinnikov** [comment]
bors retry

**Pull request merged**
