### PR TITLE
sql: generate `crdb_internal.cluster_locks` using worker and memory accounting

### PR DESCRIPTION
**Pull request by AlexTalks**
**sql: convert `crdb_internal.cluster_locks` virtual table to use worker**

This change updates the generator for the `crdb_internal.cluster_locks`
virtual table to be able to wrap it in a worker Goroutine by calling
`setupGenerator`. While previously the virtual table generator did not
run in a separate Goroutine, wrapping it as a worker running in a
separate Goroutine allows for cancellation during table generation,
eliminating potentially unnecessary RPCs. This follows the pattern set
by other virtual tables within `crb_internal`.

**sql: account for memory used in generating `crdb_internal.cluster_locks`**

This change adds memory monitoring to the memory used in generating the
virtual table `crdb_internal.cluster_locks`. Utilizing the
`BoundAccount` as part of the planner's `EvalContext`, it accounts for
the memory used by the `QueryLocksResponse` returned from the RPC fanout
needed to generate the table. As such, if the memory budget allocated
has been reached, the call to `acct.Grow()` will be denied and return an
error that will stop row generation, thus ensuring that the memory used
in the generation of this table will not cause memory exhaustion.

Release justification: Minor improvements.

Depends on #77876, #80422, #79623

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 6069 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80216#-N0EHOivDpSRWSV3zEUc:-N0EHOivDpSRWSV3zEUd:b-30iutg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf01f1c67cc2f0da01432f61abf4bc33478d2a6/pkg/sql/crdb_internal.go#L6069)):*
> ```Go
> 		resumeSpan = resp.ResumeSpan
> 
> 		if err = acct.Grow(ctx, int64(resp.Size())); err != nil {
> ```

We're adding to our memory account when we get a response and freeing that before the next request. I have two questions about this:
1. Should we be requesting bytes from the budget _before_ sending the request to avoid ever exceeding our memory budget? Maybe requesting `b.Header.TargetBytes` ahead of time?
2. Does this leave the memory account with some accounted bytes after the last request is sent? Is that ok?

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @nvanbenschoten)

___
*[`pkg/sql/crdb_internal.go` line 6069 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80216#-N0EHOivDpSRWSV3zEUc:-N0XcxQqADx1Kw6DazaE:b-irsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf01f1c67cc2f0da01432f61abf4bc33478d2a6/pkg/sql/crdb_internal.go#L6069)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're adding to our memory account when we get a response and freeing that before the next request. I have two questions about this:
1. Should we be requesting bytes from the budget _before_ sending the request to avoid ever exceeding our memory budget? Maybe requesting `b.Header.TargetBytes` ahead of time?
2. Does this leave the memory account with some accounted bytes after the last request is sent? Is that ok?
</blockquote></details>

Perhaps @azhng can answer this a bit better than me, but as I understand it:

1. It seems like requesting budget with `acct.Grow(..)` is generally done after a request is made and we have the response object, at least here in `crdb_internal.go`.  If we should do this differently - e.g. allocate `TargetBytes` aka 10MB prior to each request, and then shrink it down to the actual response size, definitely let me know.
2. I don't believe so because of the `defer acct.Close()`.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks and @nvanbenschoten)

___
*[`pkg/sql/crdb_internal.go` line 6069 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80216#-N0EHOivDpSRWSV3zEUc:-N0XgqwD2mpD9anCv_Cm:b-ls8ze2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf01f1c67cc2f0da01432f61abf4bc33478d2a6/pkg/sql/crdb_internal.go#L6069)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Perhaps @azhng can answer this a bit better than me, but as I understand it:

1. It seems like requesting budget with `acct.Grow(..)` is generally done after a request is made and we have the response object, at least here in `crdb_internal.go`.  If we should do this differently - e.g. allocate `TargetBytes` aka 10MB prior to each request, and then shrink it down to the actual response size, definitely let me know.
2. I don't believe so because of the `defer acct.Close()`.
</blockquote></details>

Currently, SQL Stats's memory accounting within the `crdb_internal.go` is quite problematic for a few reasons:
1. SQL Stats's node-level API is not paginated, and it's difficult to implement pagination on it since it's essentially an hash aggregation. (Hence SQL Stats is quite aggressively pushing data into the system table at a 10 mins interval, when reading from table, DistSQL has its own internal memory accounting).
2. Without pagination, the RPC client doesn't have a good way to communicate to the Server about the maximum number of bytes it would accept from the RPC response, 

With that being said, the memory accounting done within `crdb_internal.go` for SQL Stats is so that it's "better than nothing". 

I think since KV RPC request has the ability to paginate, and also the ability specify maximum target bytes in the RPC request header, we should perform memory accounting *before* sending the RPC request. IIRC, I think similar memory accounting is implemented between [SQL<->KV boundary](https://github.com/cockroachdb/cockroach/blob/6cab2330d43c044106e7fdfaaa3973215ffa7dd7/pkg/sql/row/kv_batch_fetcher.go#L342).

**Review by AlexTalks — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @nvanbenschoten)

___
*[`pkg/sql/crdb_internal.go` line 6069 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/80216#-N0EHOivDpSRWSV3zEUc:-N0YBlEqEWcwplXwX-Km:bw6olpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cf01f1c67cc2f0da01432f61abf4bc33478d2a6/pkg/sql/crdb_internal.go#L6069)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Currently, SQL Stats's memory accounting within the `crdb_internal.go` is quite problematic for a few reasons:
1. SQL Stats's node-level API is not paginated, and it's difficult to implement pagination on it since it's essentially an hash aggregation. (Hence SQL Stats is quite aggressively pushing data into the system table at a 10 mins interval, when reading from table, DistSQL has its own internal memory accounting).
2. Without pagination, the RPC client doesn't have a good way to communicate to the Server about the maximum number of bytes it would accept from the RPC response, 

With that being said, the memory accounting done within `crdb_internal.go` for SQL Stats is so that it's "better than nothing". 

I think since KV RPC request has the ability to paginate, and also the ability specify maximum target bytes in the RPC request header, we should perform memory accounting *before* sending the RPC request. IIRC, I think similar memory accounting is implemented between [SQL<->KV boundary](https://github.com/cockroachdb/cockroach/blob/6cab2330d43c044106e7fdfaaa3973215ffa7dd7/pkg/sql/row/kv_batch_fetcher.go#L342). 
</blockquote></details>

Discussed this with @azhng on Slack a bit more - we agreed that the goal here is to account for memory used in generation (i.e. RPC responses and other temp buffers), rather than for the actual row data, which is likely better left to other parts of SQL to track.

One thing we discussed is requesting a budget of `TargetBytes` (I.e. 10MB) at the start of generation, and simply leaving it as is (since we only hold onto one page of data at a time).  However on second thought, this might be a bit of overkill, especially given that the "paged" response is per-table descriptor.  It seems like other usages of memory accounting do in fact perform [a sort of "trailing" accounting](https://github.com/cockroachdb/cockroach/blob/7f1683118f2132ec029c49c55bea147769e19903/pkg/sql/catalog/descs/kv_descriptors.go#L273) when you don't have expectations on the response size, so hopefully that is sufficient for tracking.  If we need to request the budget up front, however, we can do that.

**Pull request closed without merging**
