### PR TITLE
storage: Add comments about leases and liveness

### PR DESCRIPTION
**Pull request by bdarnell**
I had to study this code for #35986, so I took the opportunity to
update the documentation while it's fresh in my mind.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-:-Ld9QWnf-_JqBvEkiyFz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/node_liveness.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9P3n62nFawyxsC7-m:-Ld9P3n62nFawyxsC7-n:b-yb3xyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L132)):*
>  it is
___
*[pkg/storage/node_liveness.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PN4s3BgfzE-LdTuy:-Ld9PLR74rzIVfnPENp0:b-wxasn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L145)):*
> ```Go
> // not working. Transactions were used only to piggyback on the
> // transaction commit trigger). The leaseholder of the liveness range
> // gossips its contents whenever they change; no other node reads from
> ```

You could mention that we don't blindly gossip everything but attempt to gossip only that which has changed.
___
*[pkg/storage/node_liveness.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PMdo8Jzd2qFYMGEW:-Ld9PMdo8Jzd2qFYMGEX:b-3yr6hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L146)):*
> ```Go
> // transaction commit trigger). The leaseholder of the liveness range
> // gossips its contents whenever they change; no other node reads from
> // this range directly.
> ```

https://github.com/cockroachdb/cockroach/blob/a134caac1feb57b13def48314661d63f5eef3130/pkg/storage/node_liveness.go#L266-L269
___
*[pkg/storage/node_liveness.go, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PYzU4BNbtJKCSbVE:-Ld9PYzV7b_ozUJdR6vy:bn4pfkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L544)):*
> ```Go
> // This method is rarely called directly; heartbeats are normally sent
> // by the StartHeartbeat loop.
> // TODO(bdarnell): Should we just remove this synchronous heartbeat completely?
> ```

Sounds like it, though you'll probably run into trouble actually doing so.
___
*[pkg/storage/node_liveness.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9Pein7b2QjirMhz7x:-Ld9Pein7b2QjirMhz7y:b-y2mkn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L620)):*
> ```Go
> 		// expired while in flight, so maybe we don't have to care about
> 		// that and only need to distinguish between same and different
> 		// epochs in our return value.
> ```

Anything in git blame for this check?
___
*[pkg/storage/replica_range_lease.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PvW799roeptkF2Bi:-Ld9PvW799roeptkF2Bj:b-tekpco) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/replica_range_lease.go#L25)):*
> , and any

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36984)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/storage/node_liveness.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9P3n62nFawyxsC7-m:-LdFochbCX7qJX6K2iVK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L132)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

>  it is
</blockquote></details>

Done.
___
*[pkg/storage/node_liveness.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PN4s3BgfzE-LdTuy:-LdFod5l2RVIN0nC1Rts:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L145)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You could mention that we don't blindly gossip everything but attempt to gossip only that which has changed.
</blockquote></details>

Done.
___
*[pkg/storage/node_liveness.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PMdo8Jzd2qFYMGEW:-LdFosBe94yUFy6jQ15H:b-8q84re) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L146)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/a134caac1feb57b13def48314661d63f5eef3130/pkg/storage/node_liveness.go#L266-L269
</blockquote></details>

Oops. Changed to "other nodes rarely read from this range directly", and added a todo to consider making the stronger form true. 
___
*[pkg/storage/node_liveness.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9Pein7b2QjirMhz7x:-LdFrh_b0PPwxl9gRhF8:blv8ais) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/node_liveness.go#L620)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Anything in git blame for this check?
</blockquote></details>

It's been there since the beginning (#10305) without much discussion. 
___
*[pkg/storage/replica_range_lease.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36984#-Ld9PvW799roeptkF2Bi:-LdFs9RnCuXbDCTh8nwU:b-y0lpyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0fcc5243ba9386bcc1567cf2463f9fd0f7bf082/pkg/storage/replica_range_lease.go#L25)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> , and any
</blockquote></details>

I mean "but any". Reworded to "The current arrangement is not perfect, and some opportunities for improvement appear, but any changes must be made very carefully".

**Comment by bdarnell** [comment]
bors r=tbg

**Comment by bdarnell** [comment]
bors r=tbg

**Pull request merged**
