### PR TITLE
cloud: Update Kubernetes docs to reflect the changes in version 1.5

### PR DESCRIPTION
**Pull request by a-robinson**
There are also a couple new features that'll enable us to avoid colocation of cockroach instances and minimize disruption, but I'll add those in a follow-up. This is basically just a find-and-replace of PetSet to StatefulSet.

https://github.com/cockroachdb/docs/issues/932

@jseldess 

Should we also consider updating the blog post, @jess-edwards, or just leave that as it was when published?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12536)

### CODE REVIEW

**Comment by a-robinson** [comment]
I've added a commit to this PR to start using the new features to (a) try to keep cockroachdb pods from landing on the same nodes and (b) ensure that too many pods aren't taken down for voluntary reasons like node drains and upgrades.

**Comment by jseldess** [comment]
LGTM. 

Related doc updates in https://github.com/cockroachdb/docs/pull/940

**Comment by jess-edwards** [comment]
@a-robinson 

Updating the blog post makes sense in this case. Do you want go in and make the updates yourself, or do you want to send them to me? We would also add a note up top: [Updated on XXXX]

**Comment by a-robinson** [comment]
I'm happy to do it, but what format is best for me to do it in? Update the original doc? Send you a diff of things that should change?

**Comment by jess-edwards** [comment]
Yeah, if you update the original doc using "suggested" that will be easiest. It's the equivalent of a diff and the fastest way for me to understand what needs changing.

**Comment by a-robinson** [comment]
Ack, done.

**Pull request merged**
