### PR TITLE
storage: batch allocate command queue entries

### PR DESCRIPTION
**Pull request by petermattis**
The lifetime of the entries is tied together because they are removed in
bulk, so we might as well allocate all of the entries together.

```
name                  old time/op    new time/op    delta
KVInsert1_SQL-32         492µs ± 2%     494µs ± 2%    ~     (p=0.270 n=20+19)
KVInsert10_SQL-32        935µs ± 2%     942µs ± 2%    ~     (p=0.057 n=19+20)
KVInsert100_SQL-32      5.09ms ± 2%    5.10ms ± 3%    ~     (p=0.478 n=20+20)
KVInsert1000_SQL-32     49.9ms ± 6%    49.5ms ± 8%    ~     (p=0.214 n=19+20)
KVInsert10000_SQL-32     659ms ±12%     637ms ± 8%  -3.27%  (p=0.024 n=19+20)

name                  old allocs/op  new allocs/op  delta
KVInsert1_SQL-32           304 ± 0%       301 ± 0%  -0.99%  (p=0.000 n=16+17)
KVInsert10_SQL-32          754 ± 0%       733 ± 0%  -2.79%  (p=0.000 n=17+15)
KVInsert100_SQL-32       5.04k ± 0%     4.84k ± 0%  -3.98%  (p=0.000 n=19+20)
KVInsert1000_SQL-32      48.7k ± 2%     46.4k ± 1%  -4.77%  (p=0.000 n=20+20)
KVInsert10000_SQL-32      570k ±15%      517k ±13%  -9.15%  (p=0.000 n=20+20)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6411)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6411#-:-KGZd5zOZjp-3yx_iY1F:1417088721)*

**Comment by nvanbenschoten** [comment]
LGTM, although I'm curious how this compares to using a pool for these `entries`, given that we have such convenient access to their lifetimes.

**Comment by tschottdorf** [comment]
LGTM (also curious in `sync.Pool` though).

> --

-- Tobias

**Comment by petermattis** [comment]
The benchmark I was looking at was performing a batch with 20k CPuts. I would be surprised if using `sync.Pool` to allocate the command queue entries for those 20k spans individually would be better than the batch allocation being performed here. That said, I'm tabling this PR while I work on improving #6412 which provides a much more significant performance increase.

**Comment by petermattis** [comment]
Obsoleted by #6412.

**Pull request closed without merging**
