### PR TITLE
docs: RFC for db-console Bazel build

### PR DESCRIPTION
**Pull request by koorosh**
Described proposal and changes required for
`pkg/ui` UI projects to establish Bazel build
workflow and integration with other bazel
rules.

Release note: None

### CODE REVIEW

**Review by nathanstilwell — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-McKe5Kg5S0NSxRVT1DU:-McKe5Kg5S0NSxRVT1DV:b-tanos7) ([raw file](https://github.com/cockroachdb/cockroach/blob/773e720e74ba219008b6f87e3851c490682c29e0/docs/RFCS/20210423_db-cosole-bazel-build.md#L150)):*
> ```Markdown
> - restructure `ui` code. It includes following NPM projects: `db-console` (root project), `cluster-ui`, and
> `crdb-protobufjs-client` projects. These projects depend on each other and reuse same dependencies.
> `db-console` and `cluster-ui` projects can be merged into a single project to simplify and speed up project build.
> ```

I can imagine how combining the `db-console` and `cluster-ui` projects together would simplify the project, but I wonder how would we do this in a way where it remains possible to publish `@cockroachlabs/cluster-ui` for use in CockroachCloud Console?

Perhaps we could move the presentational components from cluster-ui into the main ui package (db console) and expose them as an unpublished exports. What I mean is perhaps it's possible to use the same file dependency technique to have an independent package only for published CockroachCloud dependency separate from the db console code. This could improve the DB Build, but I'm not sure it would do much for the CockroachCloud integration in terms of simplifying the architecture or development process.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-McKe5Kg5S0NSxRVT1DU:-McOn6_57t4H-7heAhzI:b-z3vgwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/773e720e74ba219008b6f87e3851c490682c29e0/docs/RFCS/20210423_db-cosole-bazel-build.md#L150)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I can imagine how combining the `db-console` and `cluster-ui` projects together would simplify the project, but I wonder how would we do this in a way where it remains possible to publish `@cockroachlabs/cluster-ui` for use in CockroachCloud Console?

Perhaps we could move the presentational components from cluster-ui into the main ui package (db console) and expose them as an unpublished exports. What I mean is perhaps it's possible to use the same file dependency technique to have an independent package only for published CockroachCloud dependency separate from the db console code. This could improve the DB Build, but I'm not sure it would do much for the CockroachCloud integration in terms of simplifying the architecture or development process.
</blockquote></details>

just realized that "merging two projects" isn't quite precise improvement, so I would try to describe specific issues and how they might be solved:
#### 1) issue https://github.com/cockroachdb/cockroach/pull/66342 when `cluster-ui` has to upgrade "protos" dependencies after changes. 
This issue happened because `cluster-ui` installs "protos" package instead of linking it. And it's not possible to link this dependency because of "hoisting" issue. 
`cluster-ui` and `protos` packages import different versions of "protobufjs" dependency which but has to be the same instance (to consume the same initial configuration).
#### 2) when we remove offline npm packages support (`yarn-vendor`),  installation time of dependencies will increase
To solve these two issues, project structure can be changed to support `yarn workspaces`:
```
pkg/ui
├── package.json
├── node_modules # <-- hoist all common dependencies to decrease installation time
├── workspaces
            ├── protos <-- code from pkg/ui/src/js (@cockroachlabs/crdb-protobuf-client)
            ├── cluster-ui
            ├── db-console <-- code from pkg/ui
```
this project structure will force both `cluster-ui` and `protos` packages use the same `protobufjs` dependency with proper initialization.
#### 3) issue with auto generated protobuf client code. 
Currently, we generate separate instances for `ccl` and `oss` licenses where `ccl` is almost identical to `oss` with only few additional definitions.
Currently,
- `cluster-ui` package always depends on `oss protos` which is established as `@cockroachlabs/crdb-protobuf-client` NPM package.
- `db-console` can depend on either `oss` or `ccl` protos and it imports them directly as local modules.
this causes final bundle for `db-console` to include:
- one instance of `@cockroachlabs/crdb-protobuf-client`
- and one more instance of oss or ccl protos.
Every module is preprocessed with `babel` (which slows down build) and the it increases bundle size
##### Possible solution
- Build single instance of `protos` (for ccl license) which can be used for builds targeted different licenses;
- `oss` builds won't be able to use `ccl` definitions because `ccl` specific components excluded from build (in webpack configuration)
- change import paths in`db-console` from locally importing `protos` (`import * as protos from "src/js/protos";`) to importing from `import * as protos from "@cockroachlabs/crdb-protobuf-client";`)
it will allow to bundle single instance across `cluster-ui` and `db-console` and as result decrease build time and bundle size.

**Comment by nathanstilwell** [comment]
I think we can merge this draft. This is in active development / prototyping, so I think we can get it merged. If there are major changes to architecture or decisions, we can review them in future PRs.

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Review by dhartunian — COMMENTED** [review]
Is this waiting on anything? If the recommendations in here have been mostly implemented then we should merge it. Otherwise, are there outstanding issues to resolve?

@koorosh before merging, can you update the PR message to match the commit message?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-:-MmQ3S8q2_uS6uF49HBC:b-gw9xrf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @nathanstilwell, and @nkodali)

___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-MmQ3Kui0qsINDRoybvG:-MmQ3Kui0qsINDRoybvH:b-w3y0bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebdbbb0152e4b8436c6ebfebfae7a37c2b441b2a/docs/RFCS/20210423_db-cosole-bazel-build.md#L5)):*
> ```Markdown
> - Start Date: 2021-04-23
> - Authors: Andrii Vorobiov
> - RFC PR: (PR # after acceptance of initial draft)
> ```

Update this with PR number now that we have it
___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-MlonlmN7nkIUQV8Ti4B:-MlonlmN7nkIUQV8Ti4C:b-webq46) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebdbbb0152e4b8436c6ebfebfae7a37c2b441b2a/docs/RFCS/20210423_db-cosole-bazel-build.md#L15)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> **Remember, you can submit a PR with your RFC before the text is
> complete. Refer to the [README](README.md#rfc-process) for details.**
> 
> **Remember, you can either fill in this template from scratch, for
> example if you prefer working from a blank slate, or you can follow
> the writing prompts in the [GUIDE](GUIDE.md). In any case, please ensure
> at the end that you have all relevant topics from the guide covered in
> your prose.**
> ```
</details>


You can remove the guidance from the RFC itself

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65924)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @nathanstilwell, and @nkodali)

___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-MmQ3Kui0qsINDRoybvG:-MmRst0i93MfMTBGnqYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebdbbb0152e4b8436c6ebfebfae7a37c2b441b2a/docs/RFCS/20210423_db-cosole-bazel-build.md#L5)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Update this with PR number now that we have it
</blockquote></details>

Done.
___
*[docs/RFCS/20210423_db-cosole-bazel-build.md, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65924#-MlonlmN7nkIUQV8Ti4B:-MmRstqKCXae2p6m0Xzg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebdbbb0152e4b8436c6ebfebfae7a37c2b441b2a/docs/RFCS/20210423_db-cosole-bazel-build.md#L15)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

> ```
> **Remember, you can submit a PR with your RFC before the text is
> complete. Refer to the [README](README.md#rfc-process) for details.**
> 
> **Remember, you can either fill in this template from scratch, for
> example if you prefer working from a blank slate, or you can follow
> the writing prompts in the [GUIDE](GUIDE.md). In any case, please ensure
> at the end that you have all relevant topics from the guide covered in
> your prose.**
> ```

You can remove the guidance from the RFC itself
</blockquote></details>

Done.

**Pull request merged**
