### PR TITLE
kv: remove the vestigial kv.DB external KV API

### PR DESCRIPTION
**Pull request by spencerkimball**
This API is a historical remnant. It was the original transactional
KV API for use with HTTP servers. It was then deprecated but still used by the
CLI, admin UI, and acceptance tests. Later it was moved to use GRPC. Over time,
we eliminated usage from the admin UI (complete) and from the CLI (almost complete).

This PR removes it entirely and attempts to shore up existing uses of it by
moving them to using SQL where possible, and leaving unimplemented errors where
the existing functionality doesn't yet exist in SQL. In particular, the use of
the KV API to transfer leases and split ranges.

Release note: None

### CODE REVIEW

**Comment by spencerkimball** [comment]
@mrtracy could you comment on the assertion here that there is zero usage from the admin UI of this old external KV API?

**Comment by mrtracy** [comment]
You are correct, there is no usage of this from the Admin UI.

**Comment by bdarnell** [comment]
:lgtm_strong: 

---

Reviewed 28 of 28 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393#-:-L2_x3fubYEsCk_9WT_K:b-uwkowd)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/localcluster/cluster.go, line 389 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393#-L2_zhQlLV63hwXbBdus:-L2_zhQlLV63hwXbBdut:bko4d20) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d2f199a6bac85db2eea2b53af7a5cb9a2b4fbc/pkg/acceptance/localcluster/cluster.go#L389)):*
> ```Go
> // alive node in the range.
> func (c *Cluster) TransferLease(nodeIdx int, r *rand.Rand, key roachpb.Key) (bool, error) {
> 	return false, errors.Errorf("TransferLease is unimplemented and should be re-implemented using SQL")
> ```

Unless you plan to fix this right away, let's file an issue about this and `Cluster.Split`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393#-:-L2a-PG1QegWJ7kE2-SY:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

+cc @tschottdorf so you're aware

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393#-:-L2a0APAbo9hteCnB3SL:b-i6222b)*

**Comment by spencerkimball** [comment]
*[pkg/acceptance/localcluster/cluster.go, line 389 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393#-L2_zhQlLV63hwXbBdus:-L2a0q_0rZgdoHfyEaS3:b-ou4i0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/89d2f199a6bac85db2eea2b53af7a5cb9a2b4fbc/pkg/acceptance/localcluster/cluster.go#L389)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Unless you plan to fix this right away, let's file an issue about this and `Cluster.Split`.
</blockquote></details>

Filed #21399 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21393)*

**Comment by tschottdorf** [comment]
Didn't review thoroughly, but `¡LGTM!` in spirit!

**Pull request merged**
