### PR TITLE
rsg: add sqlsmith test

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
LGTM! I still feel like the general structure of the code could do with some love (but the changes you made already improved it a lot), but since it seems to be finding panics already I'm in favour of getting it running nightly ASAP.

We should open a tracking issue for supporting more SQL features, off the top of my head:
* update/delete/upsert (these will be fairly straightforward, i think)
* group by (this will be hard)
* CTEs (probably not too bad?)

cc. @jordanlewis who is into sqlsmith related stuff.

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-:-LXGnsXo0Zdcmw-b0X8V:b-p3f54w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-LXGov7U2mcaLV0J-i2n:-LXGov7V2zV8mN3TG8h4:bbtag1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d04525f5fb722fdf7293e45922ef992d035722/pkg/internal/sqlsmith/relational.go#L24)):*
> ```Go
> 		if s.level < d6() && d6() < 3 {
> 			outScope, ok = s.makeValues(desiredTypes)
> 			//} else if d6() < 3 {
> ```

I think this can be uncommented, I think I fixed the bug in cockroach I had this commented for.
___
*[pkg/internal/sqlsmith/relational.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-LXGp4dl8KxW6T_AwJj7:-LXGp4dl8KxW6T_AwJj8:bvr8snn) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d04525f5fb722fdf7293e45922ef992d035722/pkg/internal/sqlsmith/relational.go#L264)):*
> ```Go
> 	}
> 
> 	// TODO: make this error less by not generating constants
> ```

I realize now I didn't explain this very well, can you change the comment to this:
```
This can error a lot because it will often generate ORDER BY's like `order by 'foo'`, which is invalid. The only constant that can appear in ORDER BY is an integer and it must refer to a column ordinal. We should make it so the only constants it generates are integers less than the number of columns (or just disallow constants).
``
```

___
*[pkg/internal/sqlsmith/scalar.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-LXGmYnp9hO_D_bSua2Z:-LXGmYnp9hO_D_bSua2_:bq142i) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d04525f5fb722fdf7293e45922ef992d035722/pkg/internal/sqlsmith/scalar.go#L11)):*
> ```Go
> )
> 
> // makeScalar attempts constructs a scalar expression of the requested type.
> ```

nit: `attempts to construct`

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/internal/sqlsmith/relational.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-LXGov7U2mcaLV0J-i2n:-LXKnFScAPohHior7JEV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d04525f5fb722fdf7293e45922ef992d035722/pkg/internal/sqlsmith/relational.go#L24)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this can be uncommented, I think I fixed the bug in cockroach I had this commented for.
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34281#-LXGp4dl8KxW6T_AwJj7:-LXKnG2D7gG_GbVAjnfF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d04525f5fb722fdf7293e45922ef992d035722/pkg/internal/sqlsmith/relational.go#L264)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I realize now I didn't explain this very well, can you change the comment to this:
```
This can error a lot because it will often generate ORDER BY's like `order by 'foo'`, which is invalid. The only constant that can appear in ORDER BY is an integer and it must refer to a column ordinal. We should make it so the only constants it generates are integers less than the number of columns (or just disallow constants).
``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Pull request merged**
