### PR TITLE
sql: Add support for the ILIKE operator

### PR DESCRIPTION
**Pull request by nvb**
While adding support for the Postgres-specific REGEXP operators (see https://github.com/cockroachdb/cockroach/issues/7515), it
became apparent that in the name of symmetry, we should also add support
for the case-insensitive LIKE operator.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7635)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: modulo the "optimized" function

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/eval.go, line 2056 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7635#-KLxpOEIiEg9SSCxjb0W:-KLxoxaltsKIm9QCRMDg:-305650344) ([raw file](https://github.com/cockroachdb/cockroach/blob/33981454828524b70c6eb48737277534768cfcfc/sql/parser/eval.go#L2056)):*
> ```Go
> 					substr := pattern[1 : len(pattern)-1]
> 					if caseInsensitive {
> 						s, substr = strings.ToUpper(s), strings.ToUpper(substr)
> ```

is this still faster than regex matching?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7635#-:-KLxq29cXElylqgh53rV:984791173)*

**Comment by tamird** [comment]
Seems legit.

**Comment by nvanbenschoten** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/eval.go, line 2056 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7635#-KLxpOEIiEg9SSCxjb0W:-KLxtnlGMdjHK8fRLmHH:1961624265) ([raw file](https://github.com/cockroachdb/cockroach/blob/33981454828524b70c6eb48737277534768cfcfc/sql/parser/eval.go#L2056)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this still faster than regex matching?
</details>
Yep, check out the new commit. I added benchmarks for the `ILIKE` operator, and while doing so, tested disabling the optimization. Overall, this hurt the benchmarks by about a factor of 3. Furthermore, when I only ran a test case that would hit this exact optimization (`%test%`), it hurt benchmarks by about a factor of 40 (`518 ns/op` vs `24181 ns/op`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7635)*

**Comment by nvanbenschoten** [comment]
TFTR

**Pull request merged**
