### PR TITLE
settings: allow overriding the default for settings

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by darinpp** [comment]
Looks fine. I do prefer slightly the simpler solution (that is currently in the branch) that doesn't require changing each of the setting classes. 
Don't you need to change all setting classes in your case? StringSetting and StateMachineSetting as well?

**Review by darinpp — APPROVED** [review]

**Review by andreimatei — COMMENTED** [review]
There's two reason why I've done it this way:
1. Ergonomics. I think it's much nicer to change the default for a setting only by calling methods on that setting (instead of also having to interact with a `SV`)
2. Consistency. Dealing with defaults values is already the responsibility of the different `Setting` implementations (the `setToDefault()` methods).

> Don't you need to change all setting classes in your case? StringSetting and StateMachineSetting as well?

I don't _need_ to. The `Override` method is not part of the `Setting` interface, and nor should it be. For `StateMachineSetting` in particular, there's no notion of a "default", so there should also not be a notion of overriding it. That's another plus if this patch vs the alternative.

I'll merge this also because it's more ready then the alternative - it's its own commit (which it has to be) and it has a test :p

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40429#-:-LoMxmsuBt9C8NNQS_Ic:blybnmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
failure because of broken/polluting existing test. Fixed in a separate new commit.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40429#-:-LoNBdQJ7B9t-XQmSLXD:b9f49a2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40429#-:-LoOTYKI5inVIGn5uCTT:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
failure is some TCL flake, although I can't say what exactly

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40429#-:-LoOYRunEcDGnoY_dzjK:b9enw5j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
