### PR TITLE
cli: change exit codes from constant functions to consts

### PR DESCRIPTION
**Pull request by rauchenstein**
This is mostly just a style issue, though it also makes clear there can be no dependency on
global state.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I believe this change introduces a regression in semantics.
With the current code, the following is forbidden:

```
var c := exit.Success()
c = 123
```

i.e. the only way to use a new value for exit.Code is to modify exit/codes.go first to give it a name.
The benefit of this structure is that any code encountered "in the wild" can be reliably traced back to exit/codes.go and the explanatory comment for it.

With your change, anyone can create a variable of the type and give it an arbitrary value. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65433#-:-Ma3QItV1kmGM81GQPHW:b9d3hsc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by knz** [comment]
(If this wasn't clear when you first encountered this, maybe your PR can be amended to add an explanatory comment.)

**Review by itsbilal — APPROVED** [review]
Code LGTM, one point about comments (to echo Raphael's comment).

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65433#-:-Ma5Z6dA8mkUaAcc9WbZ:bjkx4h8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/cli/exit/codes.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65433#-Ma5ZGHZ8MbgDV5wxz6S:-Ma5ZGHZ8MbgDV5wxz6T:b-qwnj1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/37106887e995bc3483913963ee43942425816268/pkg/cli/exit/codes.go#L16)):*
> ```Go
> 	//
> 	// Codes that are common to all command times (server + client) follow.
> 	//
> ```

Based on Raphael's comment, you could probably add a comment here about how the consts should be used directly (to allow for easy traceability) instead of assigning it to vars then passing those around?

**Review by knz — COMMENTED** [review]
Also as discussed yesterday, this patch makes it possible to write `exit.WithCode(exit.Code(123))` and we'd lose traceability to the explanatory comments in the exit package.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65433#-:-Ma7z2r87UYkN88W1tpG:b8nw9fr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

**Pull request closed without merging**
