### PR TITLE
kv, storage: mandate presence of range/store ID in batch requests

### PR DESCRIPTION
**Pull request by benesch**
Even if this looks good I'll wait until next week to merge it. Stability period and all.

Also apologies if I'm sending this to the wrong folks. Still learning who owns what on core.

---

Some test code was relying on an ancient and obscure feature of the
Stores sender where batch requests without a range and/or store ID could
be routed by the request key. Normally, this routing is handled by
DistSender. Remove this feature so that requests in tests follow the
same path as requests in production. Fix the few tests that were relying
on it to manually route their requests to the correct range/store.

There are no mixed-version compatibility concerns here. Production code
paths, with one exception, have long since guaranteed that batch request
headers contain a range ID and store ID by the time they reach the
Stores sender. The one exception is during bootstrapping of a fresh
cluster, but there are no concerns about version compatibility because
the requests are directed to the local store before any other nodes have
joined the cluster. That code has been adjusted to use a wrapping sender
that installs an appropriate range and store ID.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-:-LAwVh4dB865s5ms-WpS:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/storage/client_replica_test.go, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-LAxG3ea0IRThw5R05AW:-LAxG3eb9wsPWhsRwD4r:bx9lkgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/76a32d994c24dacccf6cc09eabb1cad748c3e2d5/pkg/storage/client_replica_test.go#L552)):*
> ```Go
> 	}
> 
> 	sendRead := func(i int) *roachpb.Error {
> ```

nit: give this argument a better name. `replicaIdx`? Same below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-:-LAxGUXg6EKnznSvANBR:bnfp4nl)*

**Comment by benesch** [comment]
> This closes #9014.

Ha! So it does. Thanks for spotting that. With a little more work I was able to nuke `stores.{LookupReplica,FirstRange}`. PTAL at the last commit.

---

Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/client_replica_test.go, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-LAxG3ea0IRThw5R05AW:-LAxdvbF4TqLXCf7tTT5:brfsnx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/76a32d994c24dacccf6cc09eabb1cad748c3e2d5/pkg/storage/client_replica_test.go#L552)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: give this argument a better name. `replicaIdx`? Same below.
</blockquote></details>

Done. (I thought `storeIdx` made more sense than `replicaIdx`.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-:-LAxeBPH7RNkIxBTzvz6:b-qz7cb0)*

**Comment by bdarnell** [comment]
LGTM

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25061#-:-LAxgwEk6Znp5e1dSQdc:bb6ywmx)*

**Review by nvb — APPROVED** [review]

**Comment by benesch** [comment]
bors r=nvanbenschoten,bdarnell,tschottdorf

**Pull request merged**
