### PR TITLE
opt: normalize RightJoin to LeftJoin

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change converts the `CommuteRightJoin` exploration rule to a
normalization rule. This allows simplification of normalization rules
which no longer need to worry about RightJoin.

The execution tests that changed are cases where the estimated row
count of both sides is equal, and the normalized expression is chosen.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Maybe just do a quick check to see if there are any rules that aren't sufficiently tested since you removed a number of test cases. I added comments for a couple of cases I noticed.

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-:-LwJssdT2ff9NoHK3IU0:bd0k7gp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/join.opt, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJqSk5A14Wed_p-kXu:-LwJqSk67snBd-lN9qor:b-6dyola) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86e8d473c438dee8dd3fc1badb3ff3e846b3ba3/pkg/sql/opt/norm/rules/join.opt#L8)):*
> ```
> # inputs swapped. This allows other normalization rules to only worry about the
> # LeftJoin case.
> [CommuteRightJoin, Normalize]
> ```

should this be `HighPriority`?
___
*[pkg/sql/opt/norm/testdata/rules/join, line 1497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJr9K1APKdLXPeeNqn:-LwJr9K23XyeVEuuClF8:b-28o3ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86e8d473c438dee8dd3fc1badb3ff3e846b3ba3/pkg/sql/opt/norm/testdata/rules/join#L1497)):*
> ```
> SELECT * FROM (SELECT count(*) FROM b) FULL JOIN a ON True
> ----
> right-join (hash)
> ```

why is this still a right join?
___
*[pkg/sql/opt/norm/testdata/rules/select, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsDg66H61mBjdYxlD:-LwJsDg66H61mBjdYxlE:bpgsugq) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L618)):*
> ```
> 
> # Only the filters bound by the right side are mapped and pushed down.
> opt expect=PushSelectCondRightIntoJoinLeftAndRight
> ```

Can you add another test for this rule? Maybe with FULL join?
___
*[pkg/sql/opt/norm/testdata/rules/select, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsTP9-N91COPfMvzD:-LwJsTPA2pBxHq86tB4l:b-mcfh0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L842)):*
> ```
> # PushSelectIntoJoinRight
> # --------------------------------------------------
> opt expect=PushSelectIntoJoinRight
> ```

Can you add some tests that use this rule?

**Review by RaduBerinde — COMMENTED** [review]
TFTR! I did check that all the `RIGHT JOIN` cases I removed still have a `FULL JOIN` variant somewhere, that one might just be testing multiple rules at the same time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-:-LwJy4EJCTKpchdJeZQR:b-ecung2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/norm/rules/join.opt, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJqSk5A14Wed_p-kXu:-LwJwlQ_BlDzCM1jDHp_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86e8d473c438dee8dd3fc1badb3ff3e846b3ba3/pkg/sql/opt/norm/rules/join.opt#L8)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this be `HighPriority`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/join, line 1497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJr9K1APKdLXPeeNqn:-LwJwzr52LrGjI3jFo0n:b8wmbjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e86e8d473c438dee8dd3fc1badb3ff3e846b3ba3/pkg/sql/opt/norm/testdata/rules/join#L1497)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why is this still a right join?
</blockquote></details>

We were using `opt` and this was the cheaper variant after exploration. Changed it to `norm`
___
*[pkg/sql/opt/norm/testdata/rules/select, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsDg66H61mBjdYxlD:-LwJxBZa1ePE2rsM7CX3:b-t3wbiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L618)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add another test for this rule? Maybe with FULL join?
</blockquote></details>

There is an existing test with full join, it's just under "PushSelectCondLeftIntoJoinLeftAndRight + PushSelectCondRightIntoJoinLeftAndRight"
___
*[pkg/sql/opt/norm/testdata/rules/select, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsTP9-N91COPfMvzD:-LwJxVGd85oxWcHhUq-p:bt4wqcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L842)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add some tests that use this rule?
</blockquote></details>

There are some, under `PushSelectIntoJoinLeft + PushSelectIntoJoinRight + MergeSelectInnerJoin`

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-:-LwJzxLUEKykERz9k7I-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 2039 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJywtSCVNCLpGTzVZ5:-LwJywtSCVNCLpGTzVZ6:b-hj6wor) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2589c7c875afa15e98a387cb95bc35c571eae29/pkg/sql/opt/norm/custom_funcs.go#L2039)):*
> ```Go
> 	}
> 
> 	// swap is a helper function which swaps the values of two (single-bit) flags.
> ```

this is cute!

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/select, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsDg66H61mBjdYxlD:-LwK7uQY-_0D1geZixTN:b-vehu9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L618)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There is an existing test with full join, it's just under "PushSelectCondLeftIntoJoinLeftAndRight + PushSelectCondRightIntoJoinLeftAndRight"
</blockquote></details>

But do any tests have `expect=PushSelectCondRightIntoJoinLeftAndRight`?
___
*[pkg/sql/opt/norm/testdata/rules/select, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsTP9-N91COPfMvzD:-LwK8AhA4llQ-I1MDFrH:bm7hkcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L842)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There are some, under `PushSelectIntoJoinLeft + PushSelectIntoJoinRight + MergeSelectInnerJoin`
</blockquote></details>

Same here, can you add `expect=PushSelectIntoJoinRight` to the relevant tests?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/select, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsDg66H61mBjdYxlD:-LwKBrtu3zMD8_tthcks:b7k6raj) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L618)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But do any tests have `expect=PushSelectCondRightIntoJoinLeftAndRight`?
</blockquote></details>

Ah. You're right. I found that this rule no longer makes sense, it will never fire because `MergeSelectInnerJoin` would push the filter into the `InnerJoin`. Basically any other rule that tries to match `(Select (InnerJoin))` is unnecessary. I removed it, and similarly removed the `InnerJoin | InnerJoinApply` from the Left variant.

 Thanks for catching this!
___
*[pkg/sql/opt/norm/testdata/rules/select, line 842 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsTP9-N91COPfMvzD:-LwKCX8j3ETSuSiEwrch:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L842)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Same here, can you add `expect=PushSelectIntoJoinRight` to the relevant tests?
</blockquote></details>

Same as above.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-:-LwKPR0k3lY612PwY5WO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/select, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43175#-LwJsDg66H61mBjdYxlD:-LwKOrPR-mM76T9SRXHF:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/beb69e089b6eadc0fde6c92eb533b08d248938fe/pkg/sql/opt/norm/testdata/rules/select#L618)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah. You're right. I found that this rule no longer makes sense, it will never fire because `MergeSelectInnerJoin` would push the filter into the `InnerJoin`. Basically any other rule that tries to match `(Select (InnerJoin))` is unnecessary. I removed it, and similarly removed the `InnerJoin | InnerJoinApply` from the Left variant.

 Thanks for catching this!
</blockquote></details>

Nice!

**Pull request merged**
