### PR TITLE
rowexec: fix TestDrainingProcessorSwallowsUncertaintyError

### LINKED ISSUE #48373: sql/rowexec: TestDrainingProcessorSwallowsUncertaintyError failed
[(sql/rowexec).TestDrainingProcessorSwallowsUncertaintyError failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1919982&tab=buildLog) on [master@b8ecf62deb88da45a344912f721b0609b5df2187](https://github.com/cockroachdb/cockroach/commits/b8ecf62deb88da45a344912f721b0609b5df2187):

```
I200504 20:52:02.554308 14188 kv/kvserver/stores.go:255  [n3] wrote 2 node addresses to persistent storage
I200504 20:52:02.558119 14191 kv/kvserver/stores.go:255  [n1] wrote 2 node addresses to persistent storage
I200504 20:52:02.561026 14684 kv/kvserver/stores.go:255  [n2] wrote 2 node addresses to persistent storage
I200504 20:52:02.590011 14188 server/node.go:572  [n3] bootstrapped store [n3,s3]
I200504 20:52:02.591145 14188 server/node.go:472  [n3] node=3: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I200504 20:52:02.592613 14188 server/server.go:1435  [n3] starting https server at 127.0.0.1:37737 (use: 127.0.0.1:37737)
I200504 20:52:02.592761 14188 server/server.go:1440  [n3] starting postgres server at 127.0.0.1:36471 (use: 127.0.0.1:36471)
I200504 20:52:02.595772 14188 server/server.go:1442  [n3] starting grpc server at 127.0.0.1:34289
I200504 20:52:02.595877 14188 server/server.go:1443  [n3] advertising CockroachDB node at 127.0.0.1:34289
I200504 20:52:02.593565 15644 server/server.go:1066  active cluster version is now 20.1-2 (up from 19.1-1)
I200504 20:52:02.742376 15707 sql/temporary_schema.go:453  [n3] skipping temporary object cleanup run as it is not the leaseholder
I200504 20:52:02.742630 15707 sql/temporary_schema.go:454  [n3] completed temporary object cleanup job
I200504 20:52:02.742999 15707 sql/temporary_schema.go:581  [n3] temporary object cleaner next scheduled to run at 2020-05-04 21:22:02.739480928 +0000 UTC
I200504 20:52:02.768426 14188 server/server_sql.go:636  [n3] done ensuring all necessary migrations have run
I200504 20:52:02.768613 14188 server/server.go:1753  [n3] serving sql connections
I200504 20:52:02.774359 15721 sqlmigrations/migrations.go:663  [n3] starting wait for upgrade finalization before schema change job migration
I200504 20:52:02.784960 15721 sqlmigrations/migrations.go:689  [n3] schema change job migration already complete
I200504 20:52:02.832404 15706 sql/event_log.go:132  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:127.0.0.1:34289 Attrs: Locality:region=test,dc=dc3 ServerVersion:20.1-2 BuildTag:v20.1.0-beta.4-1287-gb8ecf62deb StartedAt:1588625522552483286 LocalityAddress:[] ClusterName: SQLAddress:127.0.0.1:36471} ClusterID:7e5f4dce-7168-4c3b-9ad2-f34bf179c058 StartedAt:1588625522552483286 LastUp:1588625522552483286}
I200504 20:52:02.852644 15705 server/server_update.go:55  [n3] no need to upgrade, cluster already at the newest version
I200504 20:52:02.853458 14247 gossip/gossip.go:1539  [n1] node has connected to cluster via gossip
I200504 20:52:02.854166 14247 kv/kvserver/stores.go:255  [n1] wrote 2 node addresses to persistent storage
I200504 20:52:02.865997 15684 sql/event_log.go:132  [n1,client=127.0.0.1:47614,hostssl,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:kv.range_merge.queue_enabled Value:false User:root}
I200504 20:52:03.003232 15684 sql/event_log.go:132  [n1,client=127.0.0.1:47614,hostssl,user=root] Event: "create_database", target: 52, info: {DatabaseName:test Statement:CREATE DATABASE IF NOT EXISTS test User:root}
I200504 20:52:03.057381 15684 sql/event_log.go:132  [n1,client=127.0.0.1:47614,hostssl,user=root] Event: "create_table", target: 53, info: {TableName:test.public.t Statement:CREATE TABLE test.public.t (x INT8 PRIMARY KEY) User:root}
I200504 20:52:03.186953 15684 kv/kvserver/replica_command.go:397  [n1,s1,r32/1:/{Table/36-Max}] initiating a split of this range at key /Table/53/1/6 [r33] (manual)
I200504 20:52:03.256444 15684 kv/kvserver/replica_command.go:1602  [n1,s1,r33/1:/{Table/53/1/6-Max}] change replicas (add [(n2,s2):2LEARNER] remove []): existing descriptor r33:/{Table/53/1/6-Max} [(n1,s1):1, next=2, gen=1, sticky=9223372036.854775807,2147483647]
I200504 20:52:03.313447 15684 kv/kvserver/replica_raft.go:247  [n1,s1,r33/1:/{Table/53/1/6-Max}] proposing SIMPLE(l2) ADD_REPLICA[(n2,s2):2LEARNER]: after=[(n1,s1):1 (n2,s2):2LEARNER] next=3
I200504 20:52:03.333313 15684 kv/kvserver/store_snapshot.go:931  [n1,s1,r33/1:/{Table/53/1/6-Max}] sending LEARNER snapshot 6a13a6d8 at applied index 15
I200504 20:52:03.333449 16083 kv/kvserver/raft_snapshot_queue.go:126  [n1,raftsnapshot,s1,r33/1:/{Table/53/1/6-Max}] skipping snapshot; replica is likely a learner in the process of being added: (n2,s2):2LEARNER
I200504 20:52:03.335095 15684 kv/kvserver/store_snapshot.go:974  [n1,s1,r33/1:/{Table/53/1/6-Max}] streamed snapshot to (n2,s2):2LEARNER: kv pairs: 11, log entries: 0, rate-limit: 8.0 MiB/sec, 0.01s
I200504 20:52:03.350457 16052 kv/kvserver/replica_raftstorage.go:780  [n2,s2,r33/2:{-}] applying LEARNER snapshot [id=6a13a6d8 index=15]
I200504 20:52:03.364464 16052 kv/kvserver/replica_raftstorage.go:801  [n2,s2,r33/2:/{Table/53/1/6-Max}] applied LEARNER snapshot [total=14ms ingestion=4@11ms id=6a13a6d8 index=15]
I200504 20:52:03.377416 15684 kv/kvserver/replica_command.go:1602  [n1,s1,r33/1:/{Table/53/1/6-Max}] change replicas (add [(n2,s2):2] remove []): existing descriptor r33:/{Table/53/1/6-Max} [(n1,s1):1, (n2,s2):2LEARNER, next=3, gen=2, sticky=9223372036.854775807,2147483647]
I200504 20:52:03.399292 15684 kv/kvserver/replica_raft.go:247  [n1,s1,r33/1:/{Table/53/1/6-Max}] proposing SIMPLE(v2) ADD_REPLICA[(n2,s2):2]: after=[(n1,s1):1 (n2,s2):2] next=3
I200504 20:52:03.494643 16042 kv/kvserver/replica_command.go:1602  [n2,s2,r33/2:/{Table/53/1/6-Max}] change replicas (add [] remove [(n1,s1):1VOTER_DEMOTING]): existing descriptor r33:/{Table/53/1/6-Max} [(n1,s1):1, (n2,s2):2, next=3, gen=3, sticky=9223372036.854775807,2147483647]
I200504 20:52:03.556110 16042 kv/kvserver/replica_raft.go:247  [n2,s2,r33/2:/{Table/53/1/6-Max}] proposing ENTER_JOINT(r1 l1) REMOVE_REPLICA[(n1,s1):1VOTER_DEMOTING]: after=[(n1,s1):1VOTER_DEMOTING (n2,s2):2] next=3
I200504 20:52:03.565247 16042 kv/kvserver/replica_command.go:1602  [n2,s2,r33/2:/{Table/53/1/6-Max}] change replicas (add [] remove []): existing descriptor r33:/{Table/53/1/6-Max} [(n1,s1):1VOTER_DEMOTING, (n2,s2):2, next=3, gen=4, sticky=9223372036.854775807,2147483647]
I200504 20:52:03.593066 16042 kv/kvserver/replica_raft.go:247  [n2,s2,r33/2:/{Table/53/1/6-Max}] proposing LEAVE_JOINT: after=[(n1,s1):1LEARNER (n2,s2):2] next=3
I200504 20:52:03.601888 16042 kv/kvserver/replica_command.go:1602  [n2,s2,r33/2:/{Table/53/1/6-Max}] change replicas (add [] remove [(n1,s1):1LEARNER]): existing descriptor r33:/{Table/53/1/6-Max} [(n1,s1):1LEARNER, (n2,s2):2, next=3, gen=5, sticky=9223372036.854775807,2147483647]
I200504 20:52:03.658549 16042 kv/kvserver/replica_raft.go:247  [n2,s2,r33/2:/{Table/53/1/6-Max}] proposing SIMPLE(r1) REMOVE_REPLICA[(n1,s1):1LEARNER]: after=[(n2,s2):2] next=3
I200504 20:52:03.664579 14277 kv/kvserver/store_remove_replica.go:122  [n1,s1,r33/1:/{Table/53/1/6-Max}] removing replica r33/1
I200504 20:52:03.744692 15684 sql/event_log.go:132  [n1,client=127.0.0.1:47614,hostssl,user=root] Event: "set_cluster_setting", target: 0, info: {SettingName:sql.defaults.results_buffer.size Value:0 User:root}
I200504 20:52:03.873864 15005 gossip/gossip.go:1539  [n2] node has connected to cluster via gossip
I200504 20:52:03.875154 15005 kv/kvserver/stores.go:255  [n2] wrote 2 node addresses to persistent storage
--- FAIL: TestDrainingProcessorSwallowsUncertaintyError (3.72s)
=== RUN   TestDrainingProcessorSwallowsUncertaintyError/vectorize=true
    --- FAIL: TestDrainingProcessorSwallowsUncertaintyError/vectorize=true (0.21s)
=== RUN   TestDrainingProcessorSwallowsUncertaintyError/vectorize=true/dummy=false
        --- FAIL: TestDrainingProcessorSwallowsUncertaintyError/vectorize=true/dummy=false (0.07s)
            processors_test.go:663: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1588625524.078933299,2 encountered previous write with future timestamp 1588625524.078933300,2 within uncertainty interval `t <= 1588625524.578933297,0`; observed timestamps: [{1 1588625524.078933297,0} {2 1588625524.092301335,0}] (SQLSTATE 40001)

```

<details><summary>More</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestDrainingProcessorSwallowsUncertaintyError PKG=./pkg/sql/rowexec TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2ATestDrainingProcessorSwallowsUncertaintyError.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by asubiotto**
The test was not resetting a condition to block reads on a node that would
unconditionally return uncertainty errors, resulting in cases where this error
would be returned when no error was expected.

Release note: None (testing change)

Fixes #48373

### CODE REVIEW

**Comment by asubiotto** [comment]
CI failure is fixed by #48336

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48336#-:-M6V8lLB4mtIkWbwccq7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Pull request merged**
