### PR TITLE
sql: support PARTITION BY when creating indexes

### PR DESCRIPTION
**Pull request by danhhz**
Adds parsing, descriptor bookkeeping, and SHOW CREATE TABLE support for:

CREATE INDEX ... PARTITION BY
CREATE UNIQUE INDEX ... PARTITION BY
CREATE INDEX IF NOT EXISTS ... PARTITION BY
CREATE UNIQUE INDEX IF NOT EXISTS ... PARTITION BY
CREATE TABLE ... (INDEX ... PARTITION BY)
CREATE TABLE ... (UNIQUE ... PARTITION BY)
CREATE TABLE ... (UNIQUE INDEX ... PARTITION BY)

Also sneak in support for PARTITION BY on CREATE TABLE IF NOT EXISTS

@benesch this could probably use more tests of the various error conditions and validations, but my brain is wiped for the day and it works, so I figured I'd get it on your radar.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/create.go, line 1343 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzEBLtxsbrNQ_dDa_uW:-KzEBLtytPSHcqGrP7xr:ba4q4il) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/create.go#L1343)):*
> ```Go
> 	var cols []sqlbase.ColumnDescriptor
> 	for i := 0; i < len(partBy.Fields); i++ {
> 		if colOffset+i >= len(indexDesc.ColumnNames) {
> ```

Curious: why did this need to change? AFAIK it's more expensive to look up by name than by ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110)*

**Comment by danhhz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/create.go, line 1343 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzEBLtxsbrNQ_dDa_uW:-KzPLFYV5HVci86KWD1r:bx6dfwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/create.go#L1343)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curious: why did this need to change? AFAIK it's more expensive to look up by name than by ID.
</blockquote></details>

Good eye. The ids have not been allocated at the time this code is run, so they're all the 0-value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/create.go, line 1343 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzEBLtxsbrNQ_dDa_uW:-KzPNSkyetqUVLXUNZSo:br0ozh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/create.go#L1343)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Good eye. The ids have not been allocated at the time this code is run, so they're all the 0-value
</blockquote></details>

Would be great to add a comment to remind the reader of this.
Also, does this mean there was a bug previously? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110)*

**Comment by danhhz** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/create.go, line 1343 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzEBLtxsbrNQ_dDa_uW:-KzPrHvyNwtDslbvEdiL:bbgehoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/create.go#L1343)):*
Done!

> Also, does this mean there was a bug previously?

Ah, I spoke inexactly. There was one callsite before, which was fine. The new callsites added in this PR were the ones that were affected. So no bug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110)*

**Comment by knz** [comment]
:lgtm: for the sql part but I'd like Nikhil to have a second look.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-:-KzPtBsNNm6V_5gUqUU8:bjzd4s0)*

**Comment by benesch** [comment]
:lgtm_strong: 

So straightforward! I'm impressed. We could use a boatload more tests, but that's true in general and this is more than plenty to merge with.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/partitioning, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzS4fIf8csSELRph3Cj:-KzS4fIf8csSELRph3Ck:b6u5z3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/logictest/testdata/logic_test/partitioning#L521)):*
> ```
>    PARTITION p1 VALUES IN ((1)),
>    PARTITION p2 VALUES IN ((2))
> )
> ```

Am I missing something here? What does this test that's not already covered?

---

*[pkg/sql/logictest/testdata/logic_test/partitioning_index, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzS5UG_-krNI_MdoKTu:-KzS5UG_-krNI_MdoKTv:b-7s7p47) ([raw file](https://github.com/cockroachdb/cockroach/blob/2878ba9fa8e2df92839bd87f8c5461da66ca6082/pkg/sql/logictest/testdata/logic_test/partitioning_index#L89)):*
> ```
> )
> 
> statement error PARTITION p1: name must be unique
> ```

Don't spend the CI now, but this ideally this would say "must be unique across all indexes" or something. I imagine this could be pretty frustrating otherwise when looking at this statement in isolation.

---

*[pkg/sql/parser/parse_test.go, line 915 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzS5HVTTFymbC5gil8u:-KzS5HVTTFymbC5gil8v:bcon51z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2878ba9fa8e2df92839bd87f8c5461da66ca6082/pkg/sql/parser/parse_test.go#L915)):*
> ```Go
> 			`CREATE TABLE a (b INT, CONSTRAINT foo UNIQUE (b) INTERLEAVE IN PARENT c (d))`},
> 		{`CREATE TABLE a (UNIQUE INDEX (b) PARTITION BY LIST (c) (PARTITION d VALUES IN (1)))`,
> 			`CREATE TABLE a (UNIQUE (b) PARTITION BY LIST (c) (PARTITION d VALUES IN (1)))`},
> ```

Heh, good thought to test this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-:-KzS5lYuE49bhrg8JrGi:bon14k2)*

**Comment by danhhz** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/partitioning, line 521 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzS4fIf8csSELRph3Cj:-KzUBpXXtaS6O6ZpcAWD:b-t7i67w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5805d18bff2c652f8e1a6fc39452b475bb24b3eb/pkg/sql/logictest/testdata/logic_test/partitioning#L521)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Am I missing something here? What does this test that's not already covered?
</blockquote></details>

we previously did not support partitioning `CREATE TABLE IF NOT EXISTS`

---

*[pkg/sql/logictest/testdata/logic_test/partitioning_index, line 89 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-KzS5UG_-krNI_MdoKTu:-KzUBuBfhtAlnnkdzG_e:b-m4fq9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2878ba9fa8e2df92839bd87f8c5461da66ca6082/pkg/sql/logictest/testdata/logic_test/partitioning_index#L89)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Don't spend the CI now, but this ideally this would say "must be unique across all indexes" or something. I imagine this could be pretty frustrating otherwise when looking at this statement in isolation.
</blockquote></details>

good point. i'll make a note in the q/a buddy notes since they already have a bunch of error message things

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20110#-:-KzUC1Hk3yypVsl9FSM6:b-814g8k)*

**Pull request merged**
