### PR TITLE
sql,rpc/nodedialer: improve distsql node health checks

### LINKED ISSUE #28704: distsql: checkNodeHealth system needs to take into account circuit breaker state
The new node dialer circuit breakers make it so that the current mechanism for node health checks during distsql physical planning aren't sufficient - I think we also need to make sure that the nodeDialer won't return a circuit breaker tripped error for each of the nodes.

We need to figure out a way to keep the liveness check accurate with respect to this circuit breaker, or we'll get spurious failures during flow setup.

### LINKED ISSUE #29149: teamcity: failed tests on master: acceptance/bank/node-restart
The following tests appear to have failed:

[#864595](https://teamcity.cockroachdb.com/viewLog.html?buildId=864595):

```
--- FAIL: acceptance/TestNodeRestart (8.210s)
test_log_scope.go:81: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestNodeRestart083184425
test_log_scope.go:62: use -show-logs to present logs inline
--- FAIL: acceptance/TestNodeRestart: TestNodeRestart/runMode=local (8.210s)
zchaos_test.go:152: pq: unable to dial n1: breaker open
------- Stdout: -------
CockroachDB node starting at 2018-08-27 20:44:25.653667204 +0000 UTC (took 0.7s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp269295897
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              initialized new cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
CockroachDB node starting at 2018-08-27 20:44:25.784217118 +0000 UTC (took 0.8s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26262
sql:                 postgresql://root@127.0.0.1:26261?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26261 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/3
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3/cockroach-temp395953582
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              2
CockroachDB node starting at 2018-08-27 20:44:25.79403994 +0000 UTC (took 0.8s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26260
sql:                 postgresql://root@127.0.0.1:26259?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26259 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/2
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2/cockroach-temp206654075
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              4
CockroachDB node starting at 2018-08-27 20:44:25.843164199 +0000 UTC (took 0.9s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26264
sql:                 postgresql://root@127.0.0.1:26263?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26263 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/4
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4/cockroach-temp941819280
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              3
CockroachDB node starting at 2018-08-27 20:44:28.052850002 +0000 UTC (took 0.7s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp034657623
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              restarted pre-existing node
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
E180827 20:44:31.426595 6963 acceptance/zchaos_test.go:272  round 1: failed to do consistency check against node 3: Consistency checking is unimplmented and should be re-implemented using SQL
CockroachDB node starting at 2018-08-27 20:44:32.133032435 +0000 UTC (took 0.6s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp004689993
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              restarted pre-existing node
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestNodeRestart083184425
--- FAIL: acceptance/TestNodeRestart (8.210s)
test_log_scope.go:81: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestNodeRestart083184425
test_log_scope.go:62: use -show-logs to present logs inline
--- FAIL: acceptance/TestNodeRestart: TestNodeRestart/runMode=local (8.210s)
zchaos_test.go:152: pq: unable to dial n1: breaker open
------- Stdout: -------
CockroachDB node starting at 2018-08-27 20:44:25.653667204 +0000 UTC (took 0.7s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp269295897
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              initialized new cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
CockroachDB node starting at 2018-08-27 20:44:25.784217118 +0000 UTC (took 0.8s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26262
sql:                 postgresql://root@127.0.0.1:26261?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26261 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/3
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3/cockroach-temp395953582
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/3
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              2
CockroachDB node starting at 2018-08-27 20:44:25.79403994 +0000 UTC (took 0.8s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26260
sql:                 postgresql://root@127.0.0.1:26259?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26259 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/2
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2/cockroach-temp206654075
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/2
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              4
CockroachDB node starting at 2018-08-27 20:44:25.843164199 +0000 UTC (took 0.9s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26264
sql:                 postgresql://root@127.0.0.1:26263?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26263 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/4
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4/cockroach-temp941819280
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/4
status:              initialized new node, joined pre-existing cluster
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              3
CockroachDB node starting at 2018-08-27 20:44:28.052850002 +0000 UTC (took 0.7s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp034657623
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              restarted pre-existing node
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
E180827 20:44:31.426595 6963 acceptance/zchaos_test.go:272  round 1: failed to do consistency check against node 3: Consistency checking is unimplmented and should be re-implemented using SQL
CockroachDB node starting at 2018-08-27 20:44:32.133032435 +0000 UTC (took 0.6s)
build:               CCL v2.1.0-alpha.20180702-2035-gf47e44b @ 2018/08/27 20:34:40 (go1.10.3)
webui:               http://127.0.0.1:26258
sql:                 postgresql://root@127.0.0.1:26257?sslmode=disable
client flags:        /home/agent/work/.go/src/github.com/cockroachdb/cockroach/cockroach --host=127.0.0.1:26257 --insecure
logs:                /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/TestNodeRestart/runMode=local/1
temp dir:            /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/cockroach-temp004689993
external I/O path:   /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1/extern
store[0]:            path=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster413238900/1
status:              restarted pre-existing node
clusterID:           c57929c9-0394-4a97-b769-f24308b3e766
nodeID:              1
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestNodeRestart083184425

```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
Improve distsql node health checks so that the presence of an open
circuit breaker is consider. Previously it was possible for distsql to
plan a processor on a node with an open circuit breaker which ensured an
"unable to dial" error when the plan was run.

Fixes #29149
Fixes #28704

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Also closes #28704, right? This is great - thanks for taking it on.

**Comment by petermattis** [comment]
@jordanlewis Yep.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30987#-:-LO3VywN2QV7eyqc49ED:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30987#-LO3V7qP9xvjBDpgKG-M:-LO3V7qP9xvjBDpgKG-N:bvdt54j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e634d780b16b68e9746af039928f476b2808c86/pkg/rpc/nodedialer/nodedialer.go#L153)):*
> ```Go
> 	// RPCs fail when dial fails due to an open breaker. Reset the breaker here
> 	// as a stop-gap before the reconciliation occurs.
> 	n.getBreaker(nodeID).Reset()
> ```

Thoughts about moving this below `ConnectionReady`? What does that even do?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30987)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/rpc/nodedialer/nodedialer.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30987#-LO3V7qP9xvjBDpgKG-M:-LO3_O8W4k2EJwsYtj4E:b-dkmda0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e634d780b16b68e9746af039928f476b2808c86/pkg/rpc/nodedialer/nodedialer.go#L153)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Thoughts about moving this below `ConnectionReady`? What does that even do?
</blockquote></details>

Done. `ConnectionReady` checks to see if the connection is in the "transient failure" state. I've added a comment about why it is useful (though I'm not 100% sure about whether that scenario can happen, I think we tear down connections really quickly when a heartbeat fails).

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30987)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
