### PR TITLE
storage: only backpressure writes to UserTableData keyspace 

### PR DESCRIPTION
**Pull request by nvb**
In [this TeamCity build failure](https://teamcity.cockroachdb.com/viewLog.html?buildId=523120&buildTypeId=Cockroach_MergeToMaster), we saw cases where NodeLiveness
updates were being backpressured because they were part of a single
monolithic range that was taking a long time to split. Even though this
won't be possible outside of tests, it still seems like a good idea to avoid
backpressuring any writes to meta keys, system keys, or system tables.

This seems to fix the flake seen in the referenced TeamCity build.

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
OTOH, I think we do want to be able to backpressure timeseries writes, and backpressuring writes to system tables could be a good idea (imagine a DoS attack that creates/drops a bunch of tables). Maybe we should only whitelist the liveness span instead of everything but user tables. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771#-:-L5YawNd5KR16NpXgeuE:b-hi91cn)*

**Comment by nvanbenschoten** [comment]
> OTOH, I think we do want to be able to backpressure timeseries writes, and backpressuring writes to system tables could be a good idea (imagine a DoS attack that creates/drops a bunch of tables).

Good point, I introduced a whitelist of spans that can be backpressured. It consists of the timeseries spans and the table data span. PTAL.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22771#-:-L5ooQUg1-6_LhSXE3_f:b-nx3b62)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 937 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771#-L5uYTNRWHQmrb6ZVo_k:-L5uYTNRWHQmrb6ZVo_l:b640az2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90bfcc68dff00e0316e951042afde738306f315a/pkg/storage/client_split_test.go#L937)):*
> ```Go
> 
> 	var activateSplitFilter int32
> 	splitKey := roachpb.RKey(keys.UserTableDataMin)
> ```

maybe drop a hint here that we don't backpressure some other spans

---

*[pkg/storage/replica_backpressure.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771#-L5uYdYJn0AgQ2Vz1ail:-L5uYdYJn0AgQ2Vz1aim:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90bfcc68dff00e0316e951042afde738306f315a/pkg/storage/replica_backpressure.go#L76)):*
> ```Go
> func canBackpressureBatch(ba roachpb.BatchRequest) bool {
> 	// Don't backpressure splits themselves.
> 	if ba.Txn != nil && ba.Txn.Name == splitTxnName {
> ```

nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771#-:-L5uZ5GARo2QqX43jikG:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_split_test.go, line 937 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771#-L5uYTNRWHQmrb6ZVo_k:-L5v5mVQAiYiqIn9ScXM:bc6czzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/90bfcc68dff00e0316e951042afde738306f315a/pkg/storage/client_split_test.go#L937)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe drop a hint here that we don't backpressure some other spans
</blockquote></details>

I'd rather avoid another CI cycle. Let me know if you feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22771)*

**Pull request merged**
