### PR TITLE
cli/zip: issue per-node requests concurrently

### PR DESCRIPTION
**Pull request by knz**
Requested by @ajwerner and @andreimatei 
First commit from  #64081.

Release note (cli change): `cockroach debug zip` now attempts to pull
data from multiple nodes concurrently, up to 15 nodes at a time. This
change is meant to accelerate the data collection when a cluster
contains multiple nodes. This behavior can be changed with the new
command-line flag `--concurrency`.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Nice. Do we have any parallel testing though? I know we won't be able to say too much about the output (unless we invest in the logging), but just kicking the tires would be worth it in itself imo.

> Reviewed 4 of 11 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-:-MT08-3S8X0U-2-E8I0Y:bjil9mq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

___
*[pkg/cli/context.go, line 321 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT06J8O94SSRa2HTulM:-MT06J8O94SSRa2HTulN:b-2bh0dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/context.go#L321)):*
> ```Go
> 	// Whether to run the collection sequentially. The code attempts to
> 	// access multiple nodes concurrently by default.
> 	sequential bool
> ```

Just a suggestion: you could have this be a `--parallelism` flag that defaults to `15` instead. This seems more general and avoids the opaque hard-coding of the value 15.
___
*[pkg/cli/zip.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT06aMT1MIEwCudW7Ha:-MT06aMUBZa3ps0z7xW5:bm6oc06) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/zip.go#L99)):*
> ```Go
> 	fn func(ctx context.Context, node statuspb.NodeStatus) error,
> ) error {
> 	if zipCtx.sequential {
> ```

If this were a `parallelism` flag, you could lose the special casing here. Actually can't you lose it now? I see below that in this  case the semaphore is initialized with a size of one. If the special casing adds value, please add a small comment explaining why.

Oh, ha. It's the determinism for testing, right? You should be able to get that back if below, you do `zc.sem.Acquire(ctx, 1)` on the main goroutine and the defer on the spawned one (which is maybe even better anyway? Spawns goroutines only when they also commence their work).
___
*[pkg/cli/zip_per_node.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT07RS-0qQRUhZwFu1_:-MT07RS-0qQRUhZwFu1a:b-8jl5go) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/zip_per_node.go#L109)):*
> ```Go
> 		go func(ctx context.Context, i int) {
> 			defer wg.Done()
> 			zc.sem.Acquire(ctx, 1)
> ```

The CPU profiles are most useful when they are captured at around the same time. I think this is fine, consider adding a comment though. Ideally, in a future where https://github.com/tbg/cockroach/tree/pprof-experiment is productionized, we want to "make sure" (to the degree the parallelism allows it) to run these at the same time, as it will be more important then (labels then propagate across RPCs, but only if the sender is profiling, too)

**Review by knz — COMMENTED** [review]
>  Do we have any parallel testing though? 

Concurrent output was completely busted. I reworked the output code by adding a concurrent progress reporter, then added a test to go with it (sorting the lines to make the output deterministic).

PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-:-MTGYmI35iSfjDtQZhWU:b-mdz6vx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

___
*[pkg/cli/context.go, line 321 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT06J8O94SSRa2HTulM:-MTGXQgMDy-U1QG7-J_D:b-nrx3j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/context.go#L321)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just a suggestion: you could have this be a `--parallelism` flag that defaults to `15` instead. This seems more general and avoids the opaque hard-coding of the value 15.
</blockquote></details>

Done.

(NB: you mean concurrency. Concurrency is the degree of flexibility you give to the scheduler. Parallelism is the degree to which things actually run simultaneously.)
___
*[pkg/cli/zip.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT06aMT1MIEwCudW7Ha:-MTGYkOw9xt8L4D4mr_f:b-9gr108) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/zip.go#L99)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

If this were a `parallelism` flag, you could lose the special casing here. Actually can't you lose it now? I see below that in this  case the semaphore is initialized with a size of one. If the special casing adds value, please add a small comment explaining why.

Oh, ha. It's the determinism for testing, right? You should be able to get that back if below, you do `zc.sem.Acquire(ctx, 1)` on the main goroutine and the defer on the spawned one (which is maybe even better anyway? Spawns goroutines only when they also commence their work).
</blockquote></details>

I think I like the special case here because it clarifies / documents what is going on below.
___
*[pkg/cli/zip_per_node.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT07RS-0qQRUhZwFu1_:-MTGWog8CcJN2qejZuO6:b-vpehny) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/zip_per_node.go#L109)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The CPU profiles are most useful when they are captured at around the same time. I think this is fine, consider adding a comment though. Ideally, in a future where https://github.com/tbg/cockroach/tree/pprof-experiment is productionized, we want to "make sure" (to the degree the parallelism allows it) to run these at the same time, as it will be more important then (labels then propagate across RPCs, but only if the sender is profiling, too)
</blockquote></details>

I removed the semaphore here and added your explanation as a comment on the function.

**Review by knz — COMMENTED** [review]
(Rebased on top of #60529)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-:-MTKu5rMCwFgqhF0e2jj:b-rqt7cm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @tbg)

**Review by tbg — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-:-MTe9Hr-0XIpTf3wFJ9Y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @tbg)

___
*[pkg/cli/zip.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MT06aMT1MIEwCudW7Ha:-MTe6d7x4K-xA9RWM65d:bcwyjjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dcbf15359ef1e855cbe0fd19d60db56ec64a003/pkg/cli/zip.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think I like the special case here because it clarifies / documents what is going on below.
</blockquote></details>

I mostly just worry that we're not testing the "complex" case appropriately, but I see that you added parallel testing too, so no objection.
___
*[pkg/cli/zip.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MTe7_Ef9e5p-jqGVEw8:-MTe7_Ef9e5p-jqGVEw9:b-ivejqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db22cd69a9dfc6c4444e99eab8f3500dbd2d358/pkg/cli/zip.go#L147)):*
> ```Go
> 	status := serverpb.NewStatusClient(conn)
> 	admin := serverpb.NewAdminClient(conn)
> 	s.done()
> ```

Is it fine to leak these on error returns?
___
*[pkg/cli/zip_helpers.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MTe899x5lbaKkbC8da8:-MTe899x5lbaKkbC8da9:b-s4niix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db22cd69a9dfc6c4444e99eab8f3500dbd2d358/pkg/cli/zip_helpers.go#L291)):*
> ```Go
> func newZipReporter(format string, args ...interface{}) *zipReporter {
> 	return &zipReporter{
> 		flowing: zipCtx.concurrency == 1,
> ```

Is this idiomatic? I always try to keep constructors "pure". You could anchor `newZipReporter` on `zipCtx` perhaps?

**Review by knz — COMMENTED** [review]
TFYR. I have rebased this and plan to merge if CI is happy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-:-MYtlsYk9YXGU_fbvhHC:b-gehd11)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @knz, and @tbg)

___
*[pkg/cli/zip.go, line 147 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MTe7_Ef9e5p-jqGVEw8:-MYtkcnJCfe9cxTL9ogk:buydz7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db22cd69a9dfc6c4444e99eab8f3500dbd2d358/pkg/cli/zip.go#L147)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is it fine to leak these on error returns?
</blockquote></details>

There were two missing calls to `s.fail()` in here. Good catch.
___
*[pkg/cli/zip_helpers.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59863#-MTe899x5lbaKkbC8da8:-MYtlTkZBD9gI8gamC9Z:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1db22cd69a9dfc6c4444e99eab8f3500dbd2d358/pkg/cli/zip_helpers.go#L291)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this idiomatic? I always try to keep constructors "pure". You could anchor `newZipReporter` on `zipCtx` perhaps?
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
CI currently failing due to #64079. Will address that first

**Comment by knz** [comment]
ok this appears to be green

bors r=tbg

**Comment by knz** [comment]
cc @thtruo

**Pull request merged**
