### PR TITLE
opt: add partial index implication logic for inexact atoms

### LINKED ISSUE #50218: opt: more advance prover of filter => predicate implication
https://github.com/cockroachdb/cockroach/blob/c1d0b4ac64711ab4fed3f13878e1ff3c523c8d74/pkg/sql/opt/partialidx/predicate.go#L57-L58

### PR DESCRIPTION
**Pull request by mgartner**
### opt: rename partialidx/testdata/predicate/exact-atom to atom

This commit renames the `exact-atom` test file. Future commits will be
adding tests to this file that are not exact matches to atoms, which
would make the current file name confusing.

Release note: None

#### opt: add partial index implication logic for inexact atoms

This commit adds support for proving that a query filter implies a
partial index predicate when it contains expressions that do not exactly
match expressions in the predicate.

For example, the filter `a > 10` implies the predicate `a > 0`, because
all values greater than 10 are also greater than 0.

An atom A (an expression that is not a conjunction or disjunction)
implies another atom B when B contains A. To determine if an atom
contains another, we rely on the `constraints` package, which robustly
handles many types of operators (inequalities, `IN` expressions, etc.)
and operands (integers, strings, tuples, etc.).

Fixes #50218

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/partialidx/predicate.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAhZRek6dXnK5y2Qllx:-MAhZRek6dXnK5y2Qlly:b31pq0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L359)):*
> ```Go
> func (im *implicator) atomContainsAtom(a, b opt.ScalarExpr) bool {
> 	aSet, aTight := memo.BuildConstraints(a, im.md, im.evalCtx)
> 	bSet, bTight := memo.BuildConstraints(b, im.md, im.evalCtx)
> ```

Building constraints for each atom can happen multiple times. This is one of the most expensive parts of proving implication.

I'm working on a follow-up PR that caches the constraints so we don't have to re-build them as we traverse the filters and predicate expression trees. I also would like to keep the cache around between calls to `FiltersImplyPredicate`, so I'll probably make an `Implicator` struct with `FiltersImplyPredicate` as a method. This will be useful during some xform rules - as we loop through indexes, we can use the same `Implicator` to prove implication. This would increase the value of the cache—constraints for atoms in the filter only have to be built once.

We could take it a step further, and instantiate an `Implicator` on the `CustomFuncs` struct that is used across rules. Multiple rules will use an `Implicator`, so keeping it around and relying on the same cached values would further reduce the number of times `BuildConstraints` is called.

**Review by rytaft — COMMENTED** [review]
Nice work!

> Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-:-MAmUwF4BeXMCxKBnYs4:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/constraint/columns.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmN9La4LEocxrTuCq_:-MAmN9Lb0_-YP6Rwx4KY:b-slczar) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/columns.go#L89)):*
> ```Go
> }
> 
> // IsStrictPrefixOf returns true if the columns in c are a strict prefix of the
> ```

what is a "strict" prefix? It sounds to me like a strict subset, which would mean that this function should return false if the two are equal.
___
*[pkg/sql/opt/constraint/constraint.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmNrnL5oZfLni7Yuk7:-MAmNrnMApGvkb17nLHQ:b7zqdqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint.go#L240)):*
> ```Go
> 
> 	// Unconstrained constraints or contradictions cannot contain each other.
> 	if c.IsUnconstrained() || other.IsUnconstrained() || c.IsContradiction() || other.IsContradiction() {
> ```

If `c` is unconstrained or `other` is a contradiction, shouldn't this return true?
___
*[pkg/sql/opt/constraint/constraint_test.go, line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmOaWa44Up7w30_h7l:-MAmOaWbA8haTH1ls2Cq:b5d6kdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint_test.go#L199)):*
> ```Go
> 		},
> 		{
> 			a:        "/1: [/0 - /1] [/3 - /6]",
> ```

duplicate
___
*[pkg/sql/opt/partialidx/predicate.go, line 350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmPeBC9QZ1exE8BGZX:-MAmPeBDCXlYjNiSfNji:b-ilh9jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L350)):*
> ```Go
> }
> 
> // atomContainedByAtom returns true if atom expression a is contained by atom
> ```

atomContainedByAtom -> atomContainsAtom
(I think you might also need to update the text of the comment)
___
*[pkg/sql/opt/partialidx/predicate.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAhZRek6dXnK5y2Qllx:-MAmQJDJ72WLCeXVlMQ6:bp9bbq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L359)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Building constraints for each atom can happen multiple times. This is one of the most expensive parts of proving implication.

I'm working on a follow-up PR that caches the constraints so we don't have to re-build them as we traverse the filters and predicate expression trees. I also would like to keep the cache around between calls to `FiltersImplyPredicate`, so I'll probably make an `Implicator` struct with `FiltersImplyPredicate` as a method. This will be useful during some xform rules - as we loop through indexes, we can use the same `Implicator` to prove implication. This would increase the value of the cache—constraints for atoms in the filter only have to be built once.

We could take it a step further, and instantiate an `Implicator` on the `CustomFuncs` struct that is used across rules. Multiple rules will use an `Implicator`, so keeping it around and relying on the same cached values would further reduce the number of times `BuildConstraints` is called.
</blockquote></details>

We already have constraints for each `FiltersItem`, so if an atom is a top-level `FiltersItem` you should be able to reuse instead of recalculating.
___
*[pkg/sql/opt/partialidx/testdata/predicate/atom, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmTJv_7rvalRHZGij8:-MAmTJv_7rvalRHZGij9:b-k6ezhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/testdata/predicate/atom#L179)):*
> ```
> @1 > @2
> =>
> @1 >= @2
> ```

duplicate test
___
*[pkg/sql/opt/partialidx/testdata/predicate/atom, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmTUri5PjASmRc4SL2:-MAmTUri5PjASmRc4SL3:b5d6kdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/testdata/predicate/atom#L207)):*
> ```
> @1 >= 2
> =>
> (@1, @2) > (2, 0)
> ```

duplicate

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/constraint/columns.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmN9La4LEocxrTuCq_:-MB024mtC5ZVX13zbl3h:b-hvk65j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/columns.go#L89)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what is a "strict" prefix? It sounds to me like a strict subset, which would mean that this function should return false if the two are equal.
</blockquote></details>

Ahh. I was following the wording of `IsStrictSuffix`, but didn't understand that's what "strict" meant. I've updated to `IsPrefixOf`.
___
*[pkg/sql/opt/constraint/constraint.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmNrnL5oZfLni7Yuk7:-MB035gT2pVXUxfSnegp:bxrou6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint.go#L240)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

If `c` is unconstrained or `other` is a contradiction, shouldn't this return true?
</blockquote></details>

Good point. I'm thinking that `unconstrained` contains both `unconstrained` and `contradiction`, and `contradiction` contains `contradaction`. I've updated and added tests for all these cases.
___
*[pkg/sql/opt/constraint/constraint_test.go, line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmOaWa44Up7w30_h7l:-MB071mp0ETiJv7Dkq8v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint_test.go#L199)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/predicate.go, line 350 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmPeBC9QZ1exE8BGZX:-MB07sH4EyIxKp_yx5ph:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L350)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

atomContainedByAtom -> atomContainsAtom
(I think you might also need to update the text of the comment)
</blockquote></details>

Done.
___
*[pkg/sql/opt/partialidx/predicate.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAhZRek6dXnK5y2Qllx:-MB07QRL1KSE8eUUBUEz:bo3zwyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L359)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We already have constraints for each `FiltersItem`, so if an atom is a top-level `FiltersItem` you should be able to reuse instead of recalculating.
</blockquote></details>

Good point. I'll keep that in mind when I follow up with caching logic.
___
*[pkg/sql/opt/partialidx/testdata/predicate/atom, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmTJv_7rvalRHZGij8:-MB08FxGETBOtZNK-Wi8:bkkif33) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/testdata/predicate/atom#L179)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

duplicate test
</blockquote></details>

Wow, great catch! Theses dupes weren't even next to each other. You have an eagle-eyed attention to detail. :eagle: 
___
*[pkg/sql/opt/partialidx/testdata/predicate/atom, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmTUri5PjASmRc4SL2:-MB08wpT3rNCA_Cw83Sw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/testdata/predicate/atom#L207)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-:-MB0bADNAxDo0G5PXMsE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/constraint/constraint.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmNrnL5oZfLni7Yuk7:-MB0D6Jx2gov7XipQ-Fc:bmx2vs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint.go#L240)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good point. I'm thinking that `unconstrained` contains both `unconstrained` and `contradiction`, and `contradiction` contains `contradaction`. I've updated and added tests for all these cases.
</blockquote></details>

But if other is `contradiction`, does it matter what `c` is? Doesn't every constraint contain `contradiction`?
___
*[pkg/sql/opt/partialidx/predicate.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAhZRek6dXnK5y2Qllx:-MB0aYKA2OPBzTzDqztu:bp7vbga) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/predicate.go#L359)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good point. I'll keep that in mind when I follow up with caching logic.
</blockquote></details>

sounds good.
___
*[pkg/sql/opt/partialidx/testdata/predicate/atom, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmTJv_7rvalRHZGij8:-MB0abdD61ig5zozNqwa:b-5y77ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/partialidx/testdata/predicate/atom#L179)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Wow, great catch! Theses dupes weren't even next to each other. You have an eagle-eyed attention to detail. :eagle: 
</blockquote></details>

Haha thanks :)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/constraint/constraint.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50672#-MAmNrnL5oZfLni7Yuk7:-MB0dmq_3c2hlK0cdTGY:bt8cp73) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1b777480e45c00b2ed792b8f2fed5cf7d801ad1/pkg/sql/opt/constraint/constraint.go#L240)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

But if other is `contradiction`, does it matter what `c` is? Doesn't every constraint contain `contradiction`?
</blockquote></details>

Oh... yes :upside_down_face:  Updated.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50672)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
bors r=rytaft

**Pull request merged**
