### PR TITLE
cli: add network systembench test

### PR DESCRIPTION
**Pull request by m-schneider**
Release note: None

### CODE REVIEW

**Comment by m-schneider** [comment]
___
*[pkg/cli/cliflags/flags.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HVMS5lt6lye3905-:-LT4HVMS5lt6lye39050:bacgf9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/cliflags/flags.go#L850)):*
> ```Go
> 	}
> 
> 	BenchServer = FlagInfo{
> ```

I left this as is, but should I use a string mode flag instead?

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32911)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/network_test_client.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HiDi6enGdrnI_nTZ:-LT4HiDi6enGdrnI_nT_:b24pved) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L112)):*
> ```Go
> 				fmt.Printf("%8s %16s %13d %10.1f %8.1f %8.1f %8.1f %8.1f %8.1f\n",
> 					time.Duration(elapsed.Seconds())*time.Second,
> 					tick.Name,
> ```

This makes the output looks like this, not sure if we want to get rid of the seconds.
```
_elapsed____address_____________ops/sec___mb/sec__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s 104.196.163.37:8080       16.0      2.0    104.9    184.5    184.5    184.5
      1s 35.190.133.176:8080       16.0      2.0    104.9    184.5    184.5    184.5
```

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32911)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HVMS5lt6lye3905-:-LT4MH1z-5DH9YCBRlHQ:b-eeask1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/cliflags/flags.go#L850)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I left this as is, but should I use a string mode flag instead?
</blockquote></details>

I'm not understanding your question. Can you elaborate?
___
*[pkg/cli/systembench/network_test_client.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4MZbS8y-QIKT4ZzBu:-LT4MZbS8y-QIKT4ZzBv:b-9o3k1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L49)):*
> ```Go
> 		packetSize = 56
> 	} else {
> 		packetSize = 1 << 17 //128kb
> ```

Nit: Add a space before `128kb`.

Also, `1 << 17` isn't obviously `128kb`, but `128 << 10` is.
___
*[pkg/cli/systembench/network_test_client.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HiDi6enGdrnI_nTZ:-LT4LzxY1sO7XXHENbCH:b-9o9tmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L112)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

This makes the output looks like this, not sure if we want to get rid of the seconds.
```
_elapsed____address_____________ops/sec___mb/sec__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s 104.196.163.37:8080       16.0      2.0    104.9    184.5    184.5    184.5
      1s 35.190.133.176:8080       16.0      2.0    104.9    184.5    184.5    184.5
```

</blockquote></details>

Can you elaborate on what you mean by "get rid of the seconds"? Perhaps I'm not understanding the problem here. 

Why are the latency numbers identical above?
___
*[pkg/cli/systembench/systembenchpb/ping.proto, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4MQAZAot_R5kmoq_C:-LT4MQAZAot_R5kmoq_D:b-2zb8gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/systembenchpb/ping.proto#L14)):*
> ```protobuf
> service Pinger {
>   rpc Ping (PingRequest) returns (PingResponse) {}
>   rpc PingStream (stream PingRequest) returns (stream PingResponse) {}
> ```

You're not using `PingStream`. Let's delete it.

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32911)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HVMS5lt6lye3905-:-LTNoygu4K3uMgC71ad8:b-slhplk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/cliflags/flags.go#L850)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not understanding your question. Can you elaborate?
</blockquote></details>

Sure, I have the server flag as a boolean. I don't know how clean this is compared to a string mode flag with client and server as the two options.
___
*[pkg/cli/systembench/network_test_client.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4MZbS8y-QIKT4ZzBu:-LTNp7lf0iepy8SB7gtV:b-v8cghb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L49)):*
> 128 << 10
Sure!
___
*[pkg/cli/systembench/network_test_client.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HiDi6enGdrnI_nTZ:-LTNpP6S9TsH7HneWq-U:b-4lduoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L112)):*
> 128 << 10
The more servers we have the more spammy it'll get, I was thinking of maybe adding another line that just prints the seconds? The identical numbers are a coincidence. Here's some more output:

```
_elapsed__________________address____ops/sec___mb/sec__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s       35.227.52.121:8080       12.0      1.5    151.0    209.7    209.7    209.7
      1s        35.237.63.65:8080       12.0      1.5    142.6    201.3    201.3    201.3
      2s       35.227.52.121:8080       16.0      2.0    121.6    167.8    167.8    167.8
      2s        35.237.63.65:8080       16.0      2.0    121.6    184.5    184.5    184.5
      3s       35.227.52.121:8080       15.0      1.9    121.6    167.8    167.8    167.8
      3s        35.237.63.65:8080       15.0      1.9    134.2    167.8    167.8    167.8
      4s       35.227.52.121:8080       18.0      2.3    117.4    125.8    125.8    125.8
      4s        35.237.63.65:8080       18.0      2.3    125.8    134.2    134.2    134.2
      5s       35.227.52.121:8080       14.0      1.8    151.0    176.2    176.2    176.2
      5s        35.237.63.65:8080       14.0      1.8    130.0    226.5    226.5    226.5
      6s       35.227.52.121:8080       14.0      1.8    117.4    251.7    251.7    251.7
      6s        35.237.63.65:8080       14.0      1.8    125.8    226.5    226.5    226.5
      7s       35.227.52.121:8080       17.0      2.1    109.1    151.0    151.0    151.0
      7s        35.237.63.65:8080       17.0      2.1    113.2    167.8    167.8    167.8
      8s       35.227.52.121:8080       15.0      1.9    142.6    167.8    167.8    167.8
      8s        35.237.63.65:8080       15.0      1.9    134.2    184.5    184.5    184.5
      9s       35.227.52.121:8080       15.0      1.9    125.8    167.8    167.8    167.8
      9s        35.237.63.65:8080       15.0      1.9    117.4    176.2    176.2    176.2
     10s       35.227.52.121:8080       15.0      1.9    130.0    184.5    184.5    184.5
     10s        35.237.63.65:8080       15.0      1.9    117.4    226.5    226.5    226.5
```
___
*[pkg/cli/systembench/systembenchpb/ping.proto, line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4MQAZAot_R5kmoq_C:-LTNx0w21vfcJl-8v_FY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/systembenchpb/ping.proto#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You're not using `PingStream`. Let's delete it.
</blockquote></details>

Done.

**Comment by m-schneider** [comment]
ping

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32911)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HVMS5lt6lye3905-:-LTxqasrE-xPiB3t7NE4:b25qjti) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/cliflags/flags.go#L850)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Sure, I have the server flag as a boolean. I don't know how clean this is compared to a string mode flag with client and server as the two options.
</blockquote></details>

This is fine as-is.
___
*[pkg/cli/systembench/network_test_client.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4MZbS8y-QIKT4ZzBu:-LTxqewg3UjwDlvaQ9uK:bhvgyjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L49)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

> 128 << 10
Sure!
</blockquote></details>

Nit: Add a space before `128kb`. Also, `KB`, not `kb` (kilobytes, not kilobits).
___
*[pkg/cli/systembench/network_test_client.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32911#-LT4HiDi6enGdrnI_nTZ:-LTxqL6I6dBcBuHi-sq6:bmslcjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80c59f4c1691ef41be9ed2c5aa49035bfa84c22/pkg/cli/systembench/network_test_client.go#L112)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

> 128 << 10
The more servers we have the more spammy it'll get, I was thinking of maybe adding another line that just prints the seconds? The identical numbers are a coincidence. Here's some more output:

```
_elapsed__________________address____ops/sec___mb/sec__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s       35.227.52.121:8080       12.0      1.5    151.0    209.7    209.7    209.7
      1s        35.237.63.65:8080       12.0      1.5    142.6    201.3    201.3    201.3
      2s       35.227.52.121:8080       16.0      2.0    121.6    167.8    167.8    167.8
      2s        35.237.63.65:8080       16.0      2.0    121.6    184.5    184.5    184.5
      3s       35.227.52.121:8080       15.0      1.9    121.6    167.8    167.8    167.8
      3s        35.237.63.65:8080       15.0      1.9    134.2    167.8    167.8    167.8
      4s       35.227.52.121:8080       18.0      2.3    117.4    125.8    125.8    125.8
      4s        35.237.63.65:8080       18.0      2.3    125.8    134.2    134.2    134.2
      5s       35.227.52.121:8080       14.0      1.8    151.0    176.2    176.2    176.2
      5s        35.237.63.65:8080       14.0      1.8    130.0    226.5    226.5    226.5
      6s       35.227.52.121:8080       14.0      1.8    117.4    251.7    251.7    251.7
      6s        35.237.63.65:8080       14.0      1.8    125.8    226.5    226.5    226.5
      7s       35.227.52.121:8080       17.0      2.1    109.1    151.0    151.0    151.0
      7s        35.237.63.65:8080       17.0      2.1    113.2    167.8    167.8    167.8
      8s       35.227.52.121:8080       15.0      1.9    142.6    167.8    167.8    167.8
      8s        35.237.63.65:8080       15.0      1.9    134.2    184.5    184.5    184.5
      9s       35.227.52.121:8080       15.0      1.9    125.8    167.8    167.8    167.8
      9s        35.237.63.65:8080       15.0      1.9    117.4    176.2    176.2    176.2
     10s       35.227.52.121:8080       15.0      1.9    130.0    184.5    184.5    184.5
     10s        35.237.63.65:8080       15.0      1.9    117.4    226.5    226.5    226.5
```
</blockquote></details>

As discussed in person, this is fine. You're allowing a single benchmark to test multiple servers simultaneously. I think that will be rare, though it doesn't hurt to leave it in.

**Pull request merged**
