### PR TITLE
server: set up and plumb a closedts.Container

### PR DESCRIPTION
**Pull request by tbg**
The container is only set up and plumbed but not used. Unfortunately,
since the NodeID is known only late but servers have to be registered
early, the initialization process has become a little more complicated,
tough not overly so.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-:-LIdld-Q-2QmrNEKzI6w:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdier-AjEjNbITieul:-LIdier-AjEjNbITieum:bn43r8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/rpc/nodedialer/nodedialer.go#L29)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/roachpb"
> 	"github.com/cockroachdb/cockroach/pkg/rpc"
> 	"github.com/cockroachdb/cockroach/pkg/storage/closedts"
> ```

This seems like kind of a strange dependency to establish. I'm curious why you moved this out of `closedts/container`.
___
*[pkg/storage/node_liveness.go, line 1011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdjUXZEvyXkyBMeEav:-LIdjUXZEvyXkyBMeEaw:bsocs8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/storage/node_liveness.go#L1011)):*
> ```
> errors.New("not live")
> ```

Move this to the top of this file as a static variable.
___
*[pkg/storage/store.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdjgJW--ziboLK0-Rx:-LIdjgJW--ziboLK0-Ry:b-5edurq) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/storage/store.go#L579)):*
> ```Go
> 	RPCContext   *rpc.Context
> 
> 	CT *container.Container
> ```

nit: the naming of this is inconsistent with every other field else in this struct.

`ClosedTimestamp *container.Container`?

**Review by tbg — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-:-LIeleQT8jAlUcuhp5Eu:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdier-AjEjNbITieul:-LIe63jC2ZLtu4VVHQUu:bs0ewtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/rpc/nodedialer/nodedialer.go#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems like kind of a strange dependency to establish. I'm curious why you moved this out of `closedts/container`.
</blockquote></details>

I'm not sure the dependency is strange. `closedts` has basically no dependencies of its own and it's a natural API to have the "converter" into an interface sitting on the object itself (we technically don't even need to depend on `closedts` for this). We had the choice for the dialer, but with the node liveness clock wrapper we have no way of doing it the other way around - the liveness proto sits in storage and storage already imports `container`. (Of course the liveness protos should be moved out of storage, but the point basically remains - the container depending on node liveness is more awkward). Either way, happy to discuss more (or move it) if you disagree.
___
*[pkg/storage/node_liveness.go, line 1011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdjUXZEvyXkyBMeEav:-LIeByvAEDzJMcx0P6h6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/storage/node_liveness.go#L1011)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> errors.New("not live")
> ```

Move this to the top of this file as a static variable.
</blockquote></details>

Done.

**Comment by tschottdorf** [comment]
bors r=nvanbenschoten

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28006)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28006#-LIdier-AjEjNbITieul:-LIfeg73B47iLnkUbAnC:b-ot6n88) ([raw file](https://github.com/cockroachdb/cockroach/blob/73558aa4e4a0d33ba87995aaff91040a56a187c1/pkg/rpc/nodedialer/nodedialer.go#L29)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'm not sure the dependency is strange. `closedts` has basically no dependencies of its own and it's a natural API to have the "converter" into an interface sitting on the object itself (we technically don't even need to depend on `closedts` for this). We had the choice for the dialer, but with the node liveness clock wrapper we have no way of doing it the other way around - the liveness proto sits in storage and storage already imports `container`. (Of course the liveness protos should be moved out of storage, but the point basically remains - the container depending on node liveness is more awkward). Either way, happy to discuss more (or move it) if you disagree.
</blockquote></details>

Makes sense, thanks for explaining the logic.

**Pull request merged**
