### PR TITLE
kv, server: deflake TestHotRangesStats test

### LINKED ISSUE #101994: pkg/server/structlogging/structlogging_test: TestHotRangesStats failed
pkg/server/structlogging/structlogging_test.TestHotRangesStats [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9724616?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9724616?buildTab=artifacts#/) on master @ [8124bff03d073f35f4d2b6a2048c7f4417d757d9](https://github.com/cockroachdb/cockroach/commits/8124bff03d073f35f4d2b6a2048c7f4417d757d9):

```
=== RUN   TestHotRangesStats
I230421 11:40:35.582118 1 (gostd) rand.go:243  [-] 1  random seed: -6383124987784266328
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/0efd4b21e7a2d6ab8afc437d5552beda/logTestHotRangesStats2895896217
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestHotRangesStats.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27206

### PR DESCRIPTION
**Pull request by koorosh**
kv, server: rewrite hot ranges stats collection per tenant
This patch includes following changes
- refactor RRAccumulatorByTenant and ReplicaRankingMap to follow the
same pattern as RRAccumulator and RRAccumulator accumulator respectively;
- collect hottest replicas per tenant and per QPS and CPU rebalance objectives;
- resolve data race issues

Resolves: #101994

Release note: None

Epic: CRDB-25476

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @zachlite)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgN_s6sLXVKMIqvFC:-NUzgN_s6sLXVKMIqvFD:bp8ekdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L178)):*
> ```Go
> 	length := pq.Len()
> 	sorted := make([]CandidateReplica, length)
> 	heap.Init(pq)
> ```

Is this an actual bug? If so can we add more info the description explaining the fix.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgbg17NKd3J1Z6zR4:-NUzgbg17NKd3J1Z6zR5:bqpyi56) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L260)):*
> ```Go
> 		rr.mu.items[tenantID] = r
> 	}
> 	res := make([]CandidateReplica, len(r.entries))
> ```

Why do we need to clone the info into a new array?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @zachlite)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgN_s6sLXVKMIqvFC:-NV0tVsR0-XSqJNRDk1n:b-dg62k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L178)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is this an actual bug? If so can we add more info the description explaining the fix.
</blockquote></details>

yes, it is. Without init, it shifts sorted results on one position in a list with consequent calls.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgbg17NKd3J1Z6zR4:-NV0trXlD535FveCKR8V:brtl5xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L260)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Why do we need to clone the info into a new array?
</blockquote></details>

It is needed to prevent returning `r.entries` that is under `rr.mu.Lock()`

**Review by kvoli — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @koorosh, and @zachlite)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1nlra7qKtsaIk95iZ):*
Could you add a commit message describing the bug that previously occurred and what you did to address it.

If it is only a 1-2 line very obvious deflake e.g. increase test timeout - then certainly that would be overkill. However this commit is doing a fair bit more than that.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgN_s6sLXVKMIqvFC:-NV1egvZ4jnAPQrGruRF:b343krr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L178)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

yes, it is. Without init, it shifts sorted results on one position in a list with consequent calls.
</blockquote></details>

If this is required it means we are breaking the heap invariant somewhere - I think we are breaking it below by writing into `pq.entries` with the consumed output in `ReplicaRankingsMap.TopQPS` which is sorted, whereas the heap maintains a different mapping, see https://github.com/golang/go/blob/aa4d5e739f32397969fd5c33cbc95d316686039f/src/container/heap/heap.go#L26.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1jxv16OeVORCUJjbe:-NV1jxv16OeVORCUJjbf:b-mxidsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L257)):*
> ```Go
> 	}
> 	if r.Len() > 0 {
> 		r.entries = consumeAccumulator(&r)
> ```

I can't recall from the previous PR but why don't we keep a separate "consumed" slice of replicas instead of rewriting the output of the accumulator back into itself?

In this example, it would need to be a map from from tenantID such as:

```
type ReplicaRankingMap struct {
	mu struct {
		syncutil.Mutex
		items RRAccumulatorByTenant
                // You may also want to consider moving the tenant map higher up and shifting byQPS down into it.
                byQPS map[roachpb.TenantID]rrPriorityQueue
	}
}
```
___
*[`pkg/kv/kvserver/replica_rankings.go` line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgbg17NKd3J1Z6zR4:-NV1kjeHAvE5z-hnsNUt:bxzk1mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L260)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It is needed to prevent returning `r.entries` that is under `rr.mu.Lock()`
</blockquote></details>

I don't think we need to clone this, `r.entries` is being written into by calling `consumeAccumulator(&r)` above, yet `r.entries` refers to the heap list for `r`, which should only be accessed via `Pop` and `Push`. 

If you look at `ReplicaRankings.TopLoad(...)`, it is writing in the consumed output into a separate list that is maintained until there is a subsequent call to `ReplicaRankings.Update(...)` then `ReplicaRankings.TopLoad(...)`.

This should instead store the sorted slice (consumed from rr) per tenant within the  RRMap struct, see my comment above.



_Code snippet:_
```Go
	if rr.mu.dimAccumulator != nil && rr.mu.dimAccumulator.dims[dimension].Len() > 0 {
		rr.mu.byDim = consumeAccumulator(rr.mu.dimAccumulator.dims[dimension])
	}
	return rr.mu.byDim
```
___
*[`pkg/kv/kvserver/store_test.go` line 2621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1fKGj-k0HP_GVPpFX:-NV1fKGk8uAGQxwlY2WK:bvcip8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/store_test.go#L2621)):*
> ```Go
> 	require.Equal(t, 4, len(hotReplicas))
> 
> 	// test requesting data under race
> ```

nit: Use full sentence.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @kvoli, and @zachlite)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1jxv16OeVORCUJjbe:-NV4s4h3DotfhEMud-NZ:b-5nyirq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L257)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I can't recall from the previous PR but why don't we keep a separate "consumed" slice of replicas instead of rewriting the output of the accumulator back into itself?

In this example, it would need to be a map from from tenantID such as:

```
type ReplicaRankingMap struct {
	mu struct {
		syncutil.Mutex
		items RRAccumulatorByTenant
                // You may also want to consider moving the tenant map higher up and shifting byQPS down into it.
                byQPS map[roachpb.TenantID]rrPriorityQueue
	}
}
```
</blockquote></details>

Thanks for pointing out on this! Gonna revisit how replica rankings by tenant collected!

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @kvoli, and @zachlite)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgN_s6sLXVKMIqvFC:-NV9uobiBcYyAXDhCoD-:b-v6s1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L178)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

If this is required it means we are breaking the heap invariant somewhere - I think we are breaking it below by writing into `pq.entries` with the consumed output in `ReplicaRankingsMap.TopQPS` which is sorted, whereas the heap maintains a different mapping, see https://github.com/golang/go/blob/aa4d5e739f32397969fd5c33cbc95d316686039f/src/container/heap/heap.go#L26.
</blockquote></details>

Removed. 
___
*[`pkg/kv/kvserver/replica_rankings.go` line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1jxv16OeVORCUJjbe:-NV9uRNFBVho0UMGp2sz:b5r0l62) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L257)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Thanks for pointing out on this! Gonna revisit how replica rankings by tenant collected!
</blockquote></details>

Done, I've updated `ReplicaRankingMap` implementation to keep most recent computed values.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgbg17NKd3J1Z6zR4:-NV9v0jL7Lqt-a79osOd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L260)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I don't think we need to clone this, `r.entries` is being written into by calling `consumeAccumulator(&r)` above, yet `r.entries` refers to the heap list for `r`, which should only be accessed via `Pop` and `Push`. 

If you look at `ReplicaRankings.TopLoad(...)`, it is writing in the consumed output into a separate list that is maintained until there is a subsequent call to `ReplicaRankings.Update(...)` then `ReplicaRankings.TopLoad(...)`.

This should instead store the sorted slice (consumed from rr) per tenant within the  RRMap struct, see my comment above.

</blockquote></details>

Done
___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV9v3s34OuCX_Jy9w0h:-NV9v3s34OuCX_Jy9w0i:b-szhv98) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings_test.go#L479)):*
> ```Go
> 			acc.AddReplica(cr)
> 
> 			if c.qps <= 1 {
> ```

This is not necessary anymore because we might rank replicas by different objectives (ie QPS or CPU)
___
*[`pkg/kv/kvserver/store_test.go` line 2621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1fKGj-k0HP_GVPpFX:-NV9uMDzANEbBAefl9sG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/store_test.go#L2621)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Use full sentence.
</blockquote></details>

Done

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-:-NVVUwBc4GAoPZ21WnXO:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w, @koorosh, and @zachlite)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV1nlra7qKtsaIk95iZ):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you add a commit message describing the bug that previously occurred and what you did to address it.

If it is only a 1-2 line very obvious deflake e.g. increase test timeout - then certainly that would be overkill. However this commit is doing a fair bit more than that.
</blockquote></details>

Thanks
___
*[`pkg/kv/kvserver/replica_rankings.go` line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NUzgbg17NKd3J1Z6zR4:-NVVURwO4TcgVTqwyZlT:b3ca9fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings.go#L260)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks, looks good.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NVVUO983L9V-OHdU_Gc:-NVVUO99BAm_sNQTsPCJ:b-oovi39) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0b06bf61700d5192f171c6ebaec7e8a10fa6e6/pkg/kv/kvserver/replica_rankings.go#L16)):*
> ```Go
> 	"container/heap"
> 	"context"
> ```

nit: add back empty line to appease CI.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NVVUJFVAjY0gVNLgo9t:-NVVUJFVAjY0gVNLgo9u:b-5n9cqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/165370b2b1998596bd9a0125f8dd60472d6491e2/pkg/kv/kvserver/replica_rankings.go#L257)):*
> ```Go
> 
> // TopLoad returns the highest load CandidateReplicas that are tracked.
> func (rr *ReplicaRankingMap) TopLoad(tenantID roachpb.TenantID, dimension load.Dimension) []CandidateReplica {
> ```

nit: format to 80 lines to appease CI
___
*[`pkg/kv/kvserver/replica_rankings_test.go` line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NV9v3s34OuCX_Jy9w0h:-NVVUYTS8LcbzbbhfOJB:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7174299cc5571c77a475d0253c11ba79360686e9/pkg/kv/kvserver/replica_rankings_test.go#L479)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

This is not necessary anymore because we might rank replicas by different objectives (ie QPS or CPU)
</blockquote></details>

ack
___
*[`pkg/kv/kvserver/store_test.go` line 2622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NVVUiXoDlEl508xu66h:-NVVUiXp9udvDcTv9PFw:b5icen9) ([raw file](https://github.com/cockroachdb/cockroach/blob/165370b2b1998596bd9a0125f8dd60472d6491e2/pkg/kv/kvserver/store_test.go#L2622)):*
> ```Go
> 	require.Equal(t, 4, len(hotReplicas))
> 
> 	// Test requesting hottest replicas asynchronously to detect data race.
> ```

nit: It may be more interesting to add in Update() as well.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102766)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w, @kvoli, and @zachlite)

___
*[`pkg/kv/kvserver/replica_rankings.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NVVUO983L9V-OHdU_Gc:-NVa8v4E65UhgdcRUOsH:b-i21bbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e0b06bf61700d5192f171c6ebaec7e8a10fa6e6/pkg/kv/kvserver/replica_rankings.go#L16)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: add back empty line to appease CI.
</blockquote></details>

Thanks. Done.
___
*[`pkg/kv/kvserver/replica_rankings.go` line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102766#-NVVUJFVAjY0gVNLgo9t:-NVaCDW-AdgvyI19fhTK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/165370b2b1998596bd9a0125f8dd60472d6491e2/pkg/kv/kvserver/replica_rankings.go#L257)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: format to 80 lines to appease CI
</blockquote></details>

Done.

**Pull request merged**
