### PR TITLE
rfc: pgwire-compatible query cancellation

### PR DESCRIPTION
**Pull request by rafiss**
refs https://github.com/cockroachdb/cockroach/issues/41335

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @petermattis, and @rafiss)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3v-TbBtdH5T1vBzI9:-Mv3v-TbBtdH5T1vBzIA:b-luyrot) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L16)):*
> ```Markdown
> ## Summary
> 
> The Postgres query cancel protocol is hard to implement since it only uses 64
> ```

I think the summary needs to start with a sentence that says what the query cancel protocol is and why it's important.
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3v9MQE-qoPLNH3fAo:-Mv3v9MQE-qoPLNH3fAp:b7g6a25) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L19)):*
> ```Markdown
> bits of data as an identifier, and is sent over a separate (unauthenticated)
> connection, different from the SQL connection. For dedicated clusters, these 64
> bits of data need to identify a node and query to cancel. We can use 32 bits to
> ```

node and session. The query is implicit (current query).

Ben says we should think about the query, but I disagree. This is explained here: 

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20220122_cancel_rfc.md#target-the-query-in-the-request-not-the-session
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3vpJy-OlF9iEEjXqp:-Mv3vpJy-OlF9iEEjXqq:b-wzv3io) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L91)):*
> ```Markdown
> #### SQL Node Changes
> 
> The connExecutor will be updated to generate a random 32-bit integer (secretID)
> ```

Technically, we only need a secretID per connExec that's associated with a client SQL session, not for those used inside InternalExecutor.
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3w04i4Q2rTOef4wCt:-Mv3w04i4Q2rTOef4wCu:bdjlw9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L97)):*
> ```Markdown
> BackendKeyData that is sent back to the client.
> 
> The status server will have a new endpoint named PGWireCancelQuery, analogous to
> ```

I'd call it `CancelQueryByKey`, no need to say "pg" in there.
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3w98YAn7s_ga8AY0G:-Mv3w98YAn7s_ga8AY0H:b-36mamf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L108)):*
> ```Markdown
> cancellation requests. If a cancel request fails, which is likely to only happen
> if an attacker is spamming requests, it will be penalized by holding onto the
> semaphore for an extra second. If we set the concurrency of the semaphore to 256
> ```

You have not explained what this semaphore is yet at this point.

Also, as explained in the PR review already, I think the semaphore should be at the ingress, on the first sql server that receives the cancel request over pgwire, not in the target handler of the RPC; otherwise an attacker can flood the pod-to-pod network with bogus requests.

See https://github.com/cockroachdb/cockroach/pull/75211/files#diff-761942b79b747d28c579a01c4862c3a8300605c8be65b2a6e52709760849abc9R32
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3wiuIEdBGzxlHqT-V:-Mv3wiuJ4YSLNnPUqMJ-:bm7b965) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
> ```Markdown
> When a proxy sees a CancelRequest, it first extracts the IP address component of
> the message. If needed, it will forward the request to the proxy with that
> address using an RPC that is only for proxy-proxy communication. This RPC
> ```

This proxy-to-proxy communication is new. The RFC should highlight this, and contain a sub-section that explains how proxies will authenticate themselves to each other.

**Review by petermattis — COMMENTED** [review]
I skimmed this RFC at it matches up with my understanding of what was discussed elsewhere. I'll leave the detailed review to others.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-:-MvAY5Il9GQLRt7jlM0_:b-r2h2qm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvB4iQY9mfP23qeWFx2:-MvB4iQY9mfP23qeWFx3:b6drfaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L94)):*
> ```Markdown
> when it is initialized, and register it with the server’s
> [SessionRegistry](https://github.com/cockroachdb/cockroach/blob/a434c8418c36dbeb64e73588bcd4dd5b248c3238/pkg/sql/conn_executor.go#L1692).
> The 32-bit SQLInstanceID and the random 32 bit secretID will be used as the
> ```

In a multi-tenant setting, SQLInstanceID should never be more than 15 bits. We need this to be true for `unique_rowid` to remain sound. We have an outstanding problem whereby we use the node ID as the instance ID indiscriminately. We potentially ought to change the dedicated servers to utilize the same leasing protocol used in multi-tenant settings for `unique_rowid()` and potentially this as well. If we do so, we can have a bunch more bits for the secret, which will make the argument more compelling. I suggest we leave that as future work, because it's a lot to stake on this project right now, but it doesn't seem too far off.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3v-TbBtdH5T1vBzI9:-MvCYGvy-rZEVbknPwhs:bdaek36) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L16)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the summary needs to start with a sentence that says what the query cancel protocol is and why it's important.
</blockquote></details>

good point
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3v9MQE-qoPLNH3fAo:-MvCYWb93ESsWW6JQRaR:b-jg6ewz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L19)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

node and session. The query is implicit (current query).

Ben says we should think about the query, but I disagree. This is explained here: 

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20220122_cancel_rfc.md#target-the-query-in-the-request-not-the-session
</blockquote></details>

nice catch
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3vpJy-OlF9iEEjXqp:-MvCYaGsAbJclI3FxBG0:bb7pcsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L91)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Technically, we only need a secretID per connExec that's associated with a client SQL session, not for those used inside InternalExecutor.
</blockquote></details>

true
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvB4iQY9mfP23qeWFx2:-MvCXX6SArAkk6zrs11_:b-bm72lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L94)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In a multi-tenant setting, SQLInstanceID should never be more than 15 bits. We need this to be true for `unique_rowid` to remain sound. We have an outstanding problem whereby we use the node ID as the instance ID indiscriminately. We potentially ought to change the dedicated servers to utilize the same leasing protocol used in multi-tenant settings for `unique_rowid()` and potentially this as well. If we do so, we can have a bunch more bits for the secret, which will make the argument more compelling. I suggest we leave that as future work, because it's a lot to stake on this project right now, but it doesn't seem too far off. 
</blockquote></details>

i think we can still use more bits in basically all cases, without needing to do that future work. Thanks to @knz for the idea back in his initial review of my PR from 6 months ago

I'm including something like this in the next revision of my original PR
```
const (
	lower32BitsMask uint64 = 0x00000000FFFFFFFF
	lower52BitsMask uint64 = 0x000FFFFFFFFFFFFF
	leadingBitMask         = 1 << 63
)

func MakeBackendKeyData(rng *rand.Rand, sqlInstanceID base.SQLInstanceID) BackendKeyData {
	ret := rng.Uint64()
	if sqlInstanceID < 1<<11 {
		// Only keep the lower 52 bits
		ret = ret & lower52BitsMask
		// Set the upper 12 bits based on the sqlInstanceID.
		ret = ret | (uint64(sqlInstanceID) << 52)
	} else {
		// Only keep the lower 32 bits.
		ret = ret & lower32BitsMask
		// Set the leading bit.
		ret = ret | leadingBitMask
		// Set the other upper 31 bits based on the sqlInstanceID.
		ret = ret | (uint64(sqlInstanceID) << 32)
	}
	return BackendKeyData(ret)
}
```
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3w04i4Q2rTOef4wCt:-MvCYfqx0woLPiU0qJfJ:b-7rl0jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L97)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd call it `CancelQueryByKey`, no need to say "pg" in there.
</blockquote></details>

donce
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3w98YAn7s_ga8AY0G:-MvCYhkF1Eh-fQCt7mOV:b-u0hu2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L108)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You have not explained what this semaphore is yet at this point.

Also, as explained in the PR review already, I think the semaphore should be at the ingress, on the first sql server that receives the cancel request over pgwire, not in the target handler of the RPC; otherwise an attacker can flood the pod-to-pod network with bogus requests.

See https://github.com/cockroachdb/cockroach/pull/75211/files#diff-761942b79b747d28c579a01c4862c3a8300605c8be65b2a6e52709760849abc9R32

</blockquote></details>

definitely agree about adding the semaphore at the ingress. i'm already incorporating that in the next revision of my original PR, which i'll publish soon

will update RFC
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3wiuIEdBGzxlHqT-V:-MvCYtMJCcmlPwuEiDr5:b-thz1d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This proxy-to-proxy communication is new. The RFC should highlight this, and contain a sub-section that explains how proxies will authenticate themselves to each other.
</blockquote></details>

will add a proxy-proxy communication highlight.

i'm not sure how proxies will authenticate themselves to each other. would it be sufficient to say that they don't need to if they are all in the same private subnet? (proxies aren't exposed to the internet, since they are behind a cloud load balancer)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3wiuIEdBGzxlHqT-V:-MvJ5iRV9h1j_VO5ijkd:bro22gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
>  would it be sufficient to say that they don't need to if they are all in the same private subnet? 

heh, no. Defense in depth, remember? If private subnets were sufficient, we wouldn't care about using TLS throughout the CC infrastructure. And yet we do.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-Mv3wiuIEdBGzxlHqT-V:-MvKIVTK8s5CLVK_yIaJ:b-g1m917) ([raw file](https://github.com/cockroachdb/cockroach/blob/6df50d18c7b3d0084074b2ab945d81a8747de087/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

>  would it be sufficient to say that they don't need to if they are all in the same private subnet? 

heh, no. Defense in depth, remember? If private subnets were sufficient, we wouldn't care about using TLS throughout the CC infrastructure. And yet we do.


</blockquote></details>

got it, added more details now

**Review by otan — COMMENTED** [review]
things here make sense, must've been a lot of discussions :)

i think a few diagrams here would make it easier to digest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-:-MvRLS_5DhJxmeW8pUFv:btu1450)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRGbM3CM6jIybFRsp_:-MvRGbM3CM6jIybFRspa:bnb2dyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L11)):*
> ```Markdown
> 
> The proposal here is entirely dependent on many thoughtful discussions and prior
> work with Jordan Lewis, knz, Andrew Werner, Andy Kimball, Peter Mattis, Ben
> ```

haha that's not a full name :')
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRHDikEOxGwZRd_Azz:-MvRHDikEOxGwZRd_B--:b4f0bg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L48)):*
> ```Markdown
> Nearly all Postgres drivers support the Postgres query cancellation protocol.
> For example, the PGJDBC
> [setQueryTimeout](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/jdbc/PgStatement.html#setQueryTimeout-int-)
> ```

nit: if you want to avoid these long lines you could use the markdown thing where you put links down at the bottom.
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRHmmd7h7Nom3aJK-E:-MvRHmmd7h7Nom3aJK-F:b3now67) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L101)):*
> ```Markdown
> set to the SQLInstanceID. Note that SQLInstanceIDs are always positive, so it's
> safe to use the leading bit in this way. This BackendKeyData is sent back to the
> client.
> ```

it would be great if we could have a visualisation of how the 64 bit space is used (but i am a very visual person so up to you)
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRIf5Y2r95L79SPQOu:-MvRIf5Y2r95L79SPQOv:b-iu6x6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L113)):*
> ```Markdown
> 
> Since this endpoint is unauthenticated, before performing any business logic, it
> will use a semaphore to guard the number of concurrent cancellation requests. If
> ```

are we penalised if the query *just* succeeded before the CANCEL QUERY request?
not saying it's too important, but i can imagine a crazy-ish case where say there's a blocked query, we issue 3000 cancels to all existing queries, blocked query gets cancelled, everything else succeeds but we still gotta wait 3000/concurrency seconds. very hypothetical and not important, just curious.
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRJKVKAI8xoTyiaQAl:-MvRJKVKAI8xoTyiaQAm:bqm4e7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
> ```Markdown
> to the server.
> 
> When a proxy sees a BackendKeyData, it will generate a new random 32-bit secret
> ```

it would be great to get a sequence diagram of the protocol here

**Review by knz — APPROVED** [review]
:lgtm_strong: with nit about clarifying semaphore semantics.

I'll let oliver finish iterating with you.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-:-MvT-0-72BkX2unpm0V0:blaamq9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRIf5Y2r95L79SPQOu:-MvSzt6E9Mdat0T9LnAL:b6c8xma) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L113)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

are we penalised if the query *just* succeeded before the CANCEL QUERY request?
not saying it's too important, but i can imagine a crazy-ish case where say there's a blocked query, we issue 3000 cancels to all existing queries, blocked query gets cancelled, everything else succeeds but we still gotta wait 3000/concurrency seconds. very hypothetical and not important, just curious.
</blockquote></details>

good point. I see in the code it's a TryAcquire, not Acquire, but that's worth explaining here.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75870)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRGbM3CM6jIybFRsp_:-MvUUBsnEsFLR-OE4sRu:b2nh52p) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L11)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

haha that's not a full name :')
</blockquote></details>

:D 
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRHDikEOxGwZRd_Azz:-MvUU9AkDjHczbglhDrx:b-ywt5bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L48)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: if you want to avoid these long lines you could use the markdown thing where you put links down at the bottom.
</blockquote></details>

eh i'm not a huge fan of that actually
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRHmmd7h7Nom3aJK-E:-MvUU7MR3qhKyoTu3X6z:bhpf69h) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L101)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it would be great if we could have a visualisation of how the 64 bit space is used (but i am a very visual person so up to you)
</blockquote></details>

nice idea
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRIf5Y2r95L79SPQOu:-MvUXD8_9XBzG_uugKvS:bllrl9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

good point. I see in the code it's a TryAcquire, not Acquire, but that's worth explaining here.
</blockquote></details>

adding more details
___
*[docs/RFCS/20220202_pgwire_compatible_cancel.md, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75870#-MvRJKVKAI8xoTyiaQAl:-MvUXPYu4XQRVw0CE6Kk:b-85egnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/307882343aa99db13a07e146a9c22f4e859d1454/docs/RFCS/20220202_pgwire_compatible_cancel.md#L138)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it would be great to get a sequence diagram of the protocol here
</blockquote></details>

will try to add something. let's see how my text diagram skills are

**Comment by rafiss** [comment]
thanks for the reviews all. I've added a few diagrams as suggested.

bors r=otan,knz

**Pull request merged**
