### PR TITLE
util/log: protofy Severity

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8626)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/log/file_test.go, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPPpyWjVjLxMCVr-q3o:-KPPpyWjVjLxMCVr-q3p:b-c9vkbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/98073c805e0288e72e35cca49def50bdffa7e456/util/log/file_test.go#L64)):*
> ```Go
> 		// NONE is not used, subtract 1 from the modulus to avoid it.
> 		// FATAL is not used in this test, subtract 1 from the modulus to avoid it.
> 		sev := Severity(i%(int(Severity_NONE)-1-1) + 1)
> ```

`SEVERITY_INFO + i % (SEVERITY_FATAL - SEVERITY_INFO + 1)`

---

*[util/log/log.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPPpmkg_fyT4q0yxtlM:-KPPpmkg_fyT4q0yxtlN:bvnpr09) ([raw file](https://github.com/cockroachdb/cockroach/blob/98073c805e0288e72e35cca49def50bdffa7e456/util/log/log.proto#L29)):*
> ```protobuf
>   ERROR = 3;
>   FATAL = 4;
>   NONE = 5;
> ```

Do we really need both UNKNOWN and NONE? Can't we have just `NONE = 0`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626)*

**Comment by tamird** [comment]
Unknown and None serve different purposes; unknown is used to avoid
accidental zero value use; none is the "end sentinel" which is used to size
various arrays.

I'll add a comment on none when I'm next at a computer.

**Comment by RaduBerinde** [comment]
Got it, then Severity_LAST or Severity_END would be a better name than Severity_NONE. I have also used the equivalent of `len(Severity_values)` in the past instead of a sentinel, though I don't think it works in constant expressions.

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-:-KPQOSjlyPENIjTqmCrY:b-p5m3dy)*

**Comment by tamird** [comment]
Correct, `len(...)` won't work in a constant expression.

---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[util/log/clog.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPQQOB-D4LxVE8Brt8b:-KPQQOB-D4LxVE8Brt8c:b-thby1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/00eabe50c87a5e2e9945a25f9266f5783e2724ab/util/log/clog.go#L68)):*
> ```Go
> 	ErrorLog:    "ERROR",
> 	FatalLog:    "FATAL",
> 	NumSeverity: "NONE",
> ```

@raduberinde I had to use the name NONE to match this behaviour.

---

*[util/log/file_test.go, line 64 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPPpyWjVjLxMCVr-q3o:-KPQQS5nWfRqR9kWWpHj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98073c805e0288e72e35cca49def50bdffa7e456/util/log/file_test.go#L64)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> `SEVERITY_INFO + i % (SEVERITY_FATAL - SEVERITY_INFO + 1)`
</details>
Done.

---

*[util/log/log.proto, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPPpmkg_fyT4q0yxtlM:-KPQRi4-83BWaMlwxC1V:b-bizqh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/98073c805e0288e72e35cca49def50bdffa7e456/util/log/log.proto#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Do we really need both UNKNOWN and NONE? Can't we have just `NONE = 0`?
</details>
Added comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-:-KPQQwpQP96VpgF5AjGx:b-25rv6x)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Reviewed 9 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/log/clog.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-KPQQOB-D4LxVE8Brt8b:-KPSJAxFnutLBtJzL0Xy:bkclf7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/00eabe50c87a5e2e9945a25f9266f5783e2724ab/util/log/clog.go#L68)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> @raduberinde I had to use the name NONE to match this behaviour.
</details>
Ah, got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-:-KPSJXlJVuk5m6j10vdm:bnfp4nl)*

**Comment by tamird** [comment]
@maxlang this changes some UI code. PTAL

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 9 of 12 files at r1, 4 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8626#-:-KPT2diBSvdqb2kHoNEv:bnfp4nl)*

**Comment by maxlang** [comment]
LGTM, though unfortunately we'll still need something like the code in `format.ts` currently.

**Pull request merged**
