### PR TITLE
ui: degrade gracefully when regions aren't known

### PR DESCRIPTION
**Pull request by matthewtodd**
Part of #89949

Previously, when a tenant SQL instance had spun down (leaving us no way to remember which region it had been in), the SQL Activity pages would claim that statements and transactions had occurred in an "undefined" region.

This change moves from saying "undefined" to saying nothing at all, a slightly nicer user experience.

This broader problem of losing the region mapping has been described in #93268; we'll begin addressing it shortly.

Release note: None

### CODE REVIEW

**Comment by matthewtodd** [comment]
Here are some screenshots from before this fix. Note the "undefined"s and the trailing commas.

Screen Shot 2022-12-19 at 7 32 28 PM
Screen Shot 2022-12-19 at 7 32 36 PM
Screen Shot 2022-12-19 at 7 32 46 PM
Screen Shot 2022-12-19 at 7 32 57 PM

**Comment by matthewtodd** [comment]
Bazel Extended CI failures are unrelated, fallout from #93754.

```
[19:50:50][Bench //pkg/sql/opt/partialidx:partialidx_test] --- FAIL: BenchmarkImplicator
[19:50:50][Bench //pkg/sql/opt/partialidx:partialidx_test]     implicator_test.go:284: unexpected error while building filters: invalid syntax @5
[19:50:50][Bench //pkg/sql/opt/partialidx:partialidx_test] FAIL
[19:50:50][Bench //pkg/sql/opt/partialidx:partialidx_test] I221220 19:50:50.475685 1 (gostd) testmain.go:80  [-] 1  Test //pkg/sql/opt/partialidx:partialidx_test exited with error code 1
[19:50:51][Bench //pkg/sql/opt/partialidx:partialidx_test] Process exited with code 1
```

**Review by maryliag — COMMENTED** [review]
any way to remove the value so there is no `,` on the column, without any values after the `,` ?


> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93985#-:-NJp23Of3JrvbwAFTDVY:bhq5x3t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by matthewtodd — COMMENTED** [review]
Yes! Sorry I wasn't clear. That's what this PR does, remove the comma. (The screenshots are of the Before Times.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93985#-:-NJp5FTrCLAk3oUb044q:b-nlcula)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by maryliag — APPROVED** [review]
Ah cool!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93985#-:-NJp5rIf42GYcShV0pHS:b-romyxe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Comment by matthewtodd** [comment]
Thanks, @maryliag!

bors r+

**Pull request merged**
