### PR TITLE
import,backup,*: switch to AddSSTableRequest.DisallowShadowingBelow

### PR DESCRIPTION
**Pull request by dt**
The new parameter DisallowShadowingBelow replaces DisallowShadowing for all current users.

The previous flag allowed keys that exactly matched -- including their timestamp --
with exactly the same value to exist without triggering an error to allow for retried
AddSSTables or job resumption. However, going forward, adding the same SSTable repeatedly
will no longer add the same key, as the added sstable's keys will have timestamps that
now reflect their addition time. Thus the prior API would no longer work, as keys would
never match. This new API allows overwriting keys if the value matches and the timestamp
being overwritten is not older than the passed value. The fact that the value must match
exactly means this version provides the same preservation of uniqueness as the exact time
match, but now allows for retries.

While I'm here, tweak cmd_add_sstable and api.proto slightly to allow specifying both DisallowShadowing and DisallowShadowingBelow at the same time, in which case the latter wins.

Release note: none.

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @dt)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppUo5yBDbP9qxul8YL:-MppUo5yBDbP9qxul8YM:bblojvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/ccl/backupccl/restore_data_processor.go#L386)):*
> ```Go
> 	// this comes at the cost of said overlap check, but in the common case of
> 	// non-overlapping ingestion into empty spans, that is just one seek.
> 	disallowShadowingBelow := hlc.Timestamp{Logical: 1}
> ```

This could just use `DisallowConflicts`, which might be clearer. Effect is the same though.
___
*[pkg/kv/bulk/sst_batcher.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppWnHP9EQrsVusro3B:-MppWnHP9EQrsVusro3C:b-r9hege) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L66)):*
> ```Go
> 	splitAfter func() int64
> 
> 	// allows ingestion of keys where the MVCC.Key would shadow an existing row.
> ```

This comment should be extended to explain the "below" semantics.
___
*[pkg/kv/bulk/sst_batcher.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppXLwL8VSz-Ny9584Z:-MppXLwL8VSz-Ny9584_:bab3ivo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L469)):*
> ```Go
> 				// This will fail if the range has split but we'll check for that below.
> 				err = db.AddSSTable(ctx, item.start, item.end, item.sstBytes, false, /* disallowConflicts */
> 					!item.disallowShadowingBelow.IsEmpty(), item.disallowShadowingBelow, &item.stats,
> ```

Since we're deprecating `DisallowShadowing` anyway, and presumably removing all users here, maybe we should simply remove the `DisallowShadowing` parameter from `DB.AddSSTable()` entirely? For backwards compatibility, we'd always set it to true when `Below` is non-empty.
___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppYz079dATvR_GTipg:-MppYz079dATvR_GTiph:bvkgf4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L83)):*
> ```Go
> 		// If DisallowShadowingBelow is set, ignore the value of DisallowShadowing
> 		// to allow callers to specify both for forward and backward compatibility.
> 		disallowShadowing := args.DisallowShadowing && args.DisallowShadowingBelow.IsEmpty()
> ```

We may want to change `CheckSSTConflicts` to have `DisallowShadowingBelow take precedence over `DisallowShadowing`, I think it just needs a tweak to a couple of conditionals and a test case. It's clearer to keep all of this logic in the same place.
___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppZXkH5yguY_SyzxFU:-MppZXkH5yguY_SyzxFV:buktabl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L403)):*
> ```Go
> 			noShadow:      true,
> 			noShadowBelow: 5,
> 			data:          []mvccKV{{"a", 5, ""}},
> ```

Set a value here, otherwise this is a tombstone which we're always allowed to shadow (i.e. the test doesn't check that `DisallowShadowingBelow` actually takes effect).

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @dt)

___
*[pkg/storage/sst.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MprOSc27U1HsRNMOTVU:-MprOSc37JzstxUh3r9Y:b-wp5pdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/78643cea57c7cd5f653783e1e27dde5cfff965e7/pkg/storage/sst.go#L59)):*
> ```Go
> 	// disallowShadowingBelow supersedes disallowShadowing, allowing the latter to
> 	// be passed for backwards compatibility.
> 	disallowShadowing = disallowShadowing && !disallowShadowingBelow.IsEmpty()
> ```

This needs to be `IsEmpty()` rather than `!IsEmpty()`. I'm glad to see that the tests lit up. :)

Might be cleaner to just change the involved conditionals though, but this works too.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @erikgrinaker)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppUo5yBDbP9qxul8YL:-MpqB8Cr3rplAD8UMtvS:b-bga4kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/ccl/backupccl/restore_data_processor.go#L386)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This could just use `DisallowConflicts`, which might be clearer. Effect is the same though.
</blockquote></details>

I think I prefer using disallow-below here to be consistent with IMPORT and the other bulk jobs, since then it less distinct plumbing to keep track of, only one flag that authors/maintainers of bulk jobs need to know how to use correctly, and if/when we persist the earliest write time for RESTORE, this call could get a little stricter too by passing that. But in the short term, less plumbing on its own is nice too.
___
*[pkg/kv/bulk/sst_batcher.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppWnHP9EQrsVusro3B:-MpqAi5VBZuCwY-oL6-G:b-ogxhsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L66)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This comment should be extended to explain the "below" semantics.
</blockquote></details>

Updated to just point to the (much more comprehensive) comment in api.proto.
___
*[pkg/kv/bulk/sst_batcher.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppXLwL8VSz-Ny9584Z:-Mpq9a5A7LeQzQKg4eYr:b-w84xp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L469)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Since we're deprecating `DisallowShadowing` anyway, and presumably removing all users here, maybe we should simply remove the `DisallowShadowing` parameter from `DB.AddSSTable()` entirely? For backwards compatibility, we'd always set it to true when `Below` is non-empty.
</blockquote></details>

I toyed with that briefly but it is a lot of churn, particularly in the AddSST tests where, we still need to test disallowed=true + Below=0 for coverage, so I opted to just leave the param for now and let callers explicitly set it, and then when we can just delete the old flag outright it just all goes away after release-22.1.
___
*[pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppZXkH5yguY_SyzxFU:-MpqAfPICqKMZbYTmwFg:b8jjy1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L403)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Set a value here, otherwise this is a tombstone which we're always allowed to shadow (i.e. the test doesn't check that `DisallowShadowingBelow` actually takes effect).
</blockquote></details>

Whoops, Done.
___
*[pkg/storage/sst.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MprOSc27U1HsRNMOTVU:-MqK9G0E3XQxi0_FMRor:btrei3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/78643cea57c7cd5f653783e1e27dde5cfff965e7/pkg/storage/sst.go#L59)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This needs to be `IsEmpty()` rather than `!IsEmpty()`. I'm glad to see that the tests lit up. :)

Might be cleaner to just change the involved conditionals though, but this works too.
</blockquote></details>

Ah, indeed, nice to see tests caught it. Just flipped the conditional below instead as suggested.

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

___
*[pkg/ccl/backupccl/restore_data_processor.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppUo5yBDbP9qxul8YL:-MqP83oH-BRVcbEQsMhq:b-ne82y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/ccl/backupccl/restore_data_processor.go#L386)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think I prefer using disallow-below here to be consistent with IMPORT and the other bulk jobs, since then it less distinct plumbing to keep track of, only one flag that authors/maintainers of bulk jobs need to know how to use correctly, and if/when we persist the earliest write time for RESTORE, this call could get a little stricter too by passing that. But in the short term, less plumbing on its own is nice too.
</blockquote></details>

Sure, that's fine.
___
*[pkg/kv/bulk/sst_batcher.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppXLwL8VSz-Ny9584Z:-MqP8tFE7nwrqUJeMbLU:bi6y1re) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L469)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I toyed with that briefly but it is a lot of churn, particularly in the AddSST tests where, we still need to test disallowed=true + Below=0 for coverage, so I opted to just leave the param for now and let callers explicitly set it, and then when we can just delete the old flag outright it just all goes away after release-22.1.
</blockquote></details>

Yeah, we can clean it up later.

Btw, please call out that we're setting `disallowShadowing = !disallowShadowingBelow` to maintain backwards compatibility with 21.2, and add an API comment such that callers know that the behavior will regress to `disallowShadowing` with 21.2 nodes (unless they check the `MVCCAddSSTable` version gate).

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @erikgrinaker)

___
*[pkg/kv/bulk/sst_batcher.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-MppXLwL8VSz-Ny9584Z:-MqSbJ2p0vXEwJsDXQiq:bolyfms) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d121ad840ec043e1a88cb2729ac834a9e82170/pkg/kv/bulk/sst_batcher.go#L469)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, we can clean it up later.

Btw, please call out that we're setting `disallowShadowing = !disallowShadowingBelow` to maintain backwards compatibility with 21.2, and add an API comment such that callers know that the behavior will regress to `disallowShadowing` with 21.2 nodes (unless they check the `MVCCAddSSTable` version gate).
</blockquote></details>

Done, updated the BulkAdderOptions field comment.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73324#-:-MqUroxF0UblivaA4xkL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
