### PR TITLE
sql: introduce a new ORDER BY syntax to reuse index orderings

### LINKED ISSUE #17005: sql: support for ORDER BY PRIMARY KEY would be useful
The precise syntax is bikesheddable, but it would be nice to have a shorthand syntax for ordering results by primary key ordering.

Postgres doesn't officially guarantee ordering if the ordering is unspecified, but typically a `SELECT * LIMIT 1` gives you the first row by PK order (at least, in my experience). In a distributed setting like CockroachDB, this is far less likely to be the case: You just get the first row that's (latency-wise) closest to you. The ordering volatility is far higher with CockroachDB than Postgres, so having helper syntax to mitigate this is more important for us than what just following Postgres' feature-set would indicate.

Sometimes I work with a table that has a complex multi-column primary key, and typing "ORDER BY" with a subquery on `information_schema` is tedious. It would be nice to have a syntactic shorthand for this. This situation also occurs frequently in testing when I'm probing a table to choose a split point (for subsequently using `ALTER TABLE SPLIT AT VALUES...`).

cc @knz

### PR DESCRIPTION
**Pull request by knz**
This patch makes it possible to demand the same ordering on the
results of a query as the ordering used by an index. For example:

```sql
SELECT * FROM kv ORDER BY PRIMARY KEY kv
SELECT * FROM kv ORDER BY INDEX kv@primary
```

Previously, CockroachDB allowed the user to specify an index for the
table scan, e.g. `SELECT * FROM kv@primary`. However, this *index
hint* does not guarantee ordering of the results, for example if the
query is distributed.

The special syntax `ORDER BY PRIMARY KEY` is introduced in addition to
`ORDER BY INDEX` because a user may want to "order by the primary key,
whatever its name" and the primary key index is not always named
"primary".

Both `ORDER BY INDEX` and `ORDER BY PRIMARY KEY` require the user
to specify the table name explicitly. This is necessary because
the data source (FROM clause) may contain more than one table name,
for example with a join.

The new ORDER BY syntax merely expands into a list of `ORDER BY
<column>` corresponding to that index' columns. This makes it possible
to combine it with other columns, for example:

```sql
SELECT * FROM abc ORDER BY INDEX abc@ab, c
SELECT * FROM abc ORDER BY c, PRIMARY KEY abc
```

Requested by @arjunravinarayan.

Fixes  #17005.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm_strong: on the excellent design choice, documentation (e.g. wonderful top-level comment at `rewriteIndexOrderings` and the structuring into a separate function), and commit description, :dog: on the actual implementation, so please wait for Radu to weigh in on that.

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-:-Kp1BAbMf56knIbRzJ43:bg37biq)*

**Comment by RaduBerinde** [comment]
Great feature! :lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sort.go, line 325 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1JCgNwAHEXJvsg25s:-Kp1JCgNwAHEXJvsg25t:b-s8ml5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L325)):*
> ```Go
> }
> 
> // choseDirection translates the specified IndexDescriptor_Direction
> ```

choose

---

*[pkg/sql/sort.go, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1JGBN_nhspXCaS1wK:-Kp1JGBN_nhspXCaS1wL:bvm3o9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L326)):*
> ```Go
> 
> // choseDirection translates the specified IndexDescriptor_Direction
> // into a parser.Direction. If the wantedDir is DESCENDING, the idxDir
> ```

[nit] This is arguably stretching the meaning of ASCENDING/DESCENDING. I would keep it but pass an `invert` flag here so the "DESCENDING means inverse" logic stays inside `rewriteIndexOrderings`.

---

*[pkg/sql/sort.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1KE-RMtTNwmWdJeg_:-Kp1KE-SlJwq7Xmv1Fz0:besjv1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L337)):*
> ```Go
> 		return parser.Descending
> 	}
> 	if idxDir == sqlbase.IndexDescriptor_ASC {
> ```

[nit] The two cases can be coalesced to `if (ixDir == sqlbase.IndexDescriptor_ASC) != inverse` (`!=` is equivalent to logical XOR).

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IW2ir--9vnAF3tzL:-Kp1IW2ir--9vnAF3tzM:bo58ju9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L80)):*
> ```
> 1          spans  ALL
> 
> # The INDEX/PRIMARY syntax can only be used when the data source
> ```

What happens if I have SELECT * FROM kv AS a, kv AS b ORDER BY PRIMARY KEY kv?

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IDheJfGDKQrKiOVV:-Kp1IDheJfGDKQrKiOVW:b-9z3rx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L90)):*
> ```
> # TODO(knz,radu): as long as required orderings do not propagate through joins
> # (e.g. by using a merge join), an ORDER BY INDEX clause on the result of the join
> # does not imply use of that index by the underlying scan.
> ```

I think that is the case in general. E.g. if you have a WHERE clause that makes another index more appropriate, it will be used (and we may have to sort). I think this feature is perpendicular to index hinting (you can do both).

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 92 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IcN6Wfq9j6Byukkn:-Kp1IcN7UwxLdTeh6iy7:bni3634) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L92)):*
> ```
> # does not imply use of that index by the underlying scan.
> #
> ```

We should add some tests where tables that are not part of the query are used. (`SELECT * FROM kv ORDER BY PRIMARY KEY some_other_table`).

We should also add some cases where DESC is passed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-:-Kp1KpaxpkAIyaKZ8Siw:b8ytsjt)*

**Comment by knz** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sort.go, line 325 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1JCgNwAHEXJvsg25s:-Kp1LjYTLz1GzU5BKh_a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L325)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

choose
</blockquote></details>

Done.

---

*[pkg/sql/sort.go, line 326 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1JGBN_nhspXCaS1wK:-Kp1LjpBY6NDueERLz7m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L326)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This is arguably stretching the meaning of ASCENDING/DESCENDING. I would keep it but pass an `invert` flag here so the "DESCENDING means inverse" logic stays inside `rewriteIndexOrderings`.
</blockquote></details>

Done.

---

*[pkg/sql/sort.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1KE-RMtTNwmWdJeg_:-Kp1Lfks6i9Af246QEd5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L337)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The two cases can be coalesced to `if (ixDir == sqlbase.IndexDescriptor_ASC) != inverse` (`!=` is equivalent to logical XOR).
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IW2ir--9vnAF3tzL:-Kp1LvgLKdQkRLIe-UgE:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What happens if I have SELECT * FROM kv AS a, kv AS b ORDER BY PRIMARY KEY kv?
</blockquote></details>

Added a test.

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IDheJfGDKQrKiOVV:-Kp1M6Mwa3P4jzZocfnf:b-84z828) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think that is the case in general. E.g. if you have a WHERE clause that makes another index more appropriate, it will be used (and we may have to sort). I think this feature is perpendicular to index hinting (you can do both).
</blockquote></details>

Ack. Changed to a note.

---

*[pkg/sql/logictest/testdata/logic_test/order_by_index, line 92 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1IcN6Wfq9j6Byukkn:-Kp1MghoXJOZ8iRzwDtH:bvgh1k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/logictest/testdata/logic_test/order_by_index#L92)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should add some tests where tables that are not part of the query are used. (`SELECT * FROM kv ORDER BY PRIMARY KEY some_other_table`).

We should also add some cases where DESC is passed.
</blockquote></details>

Done.

The tests with DESC are already present at the beginning of the test file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sort.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1KE-RMtTNwmWdJeg_:-Kp1NVOZ9L5woEKVwSs3:bwddk96) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L337)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is not correct, we can't invert a boolean with `&&`. Specifically if `invert` is true and `idxDir` is DESC, we need to return Ascending.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023)*

**Comment by knz** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sort.go, line 337 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-Kp1KE-RMtTNwmWdJeg_:-Kp1OVnSJ50-MpWjAnqK:b-hixeri) ([raw file](https://github.com/cockroachdb/cockroach/blob/7314fe10bc78bbd6b9c963f2bd4dd4e580953bf4/pkg/sql/sort.go#L337)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is not correct, we can't invert a boolean with `&&`. Specifically if `invert` is true and `idxDir` is DESC, we need to return Ascending.
</blockquote></details>

Thanks for explaining. Fixed and added a test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17023#-:-Kp1POzUWZtqhHl_E2A_:b-uwkowd)*

**Comment by knz** [comment]
TFYRs

**Pull request merged**
