### PR TITLE
opt: Make additional perf improvements

### PR DESCRIPTION
**Pull request by andy-kimball**
Make several more fixes:

1. Do not qualify column names in metadata, since that
requires expensive string formatting up-front (also cleanup
the factoring of this code, which had gotten messy).
2. Inline Metadata into Memo.
3. Inline logicalPropsBuilder into the Memo.

Together, these changes improve KV perf from:
```
Phases/kv-read/OptBuild  18.4µs ± 1%
```
to:
```
Phases/kv-read/OptBuild  17.8µs ± 1%
```

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 45 of 45 files at r4, 83 of 83 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-:-LJy6un7807cdWyjjXKt:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/bench/out, line 0 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy2eqM-morNGGjFfd_:-LJy2eqM-morNGGjFfda:bnp415h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59acf37a044e9b3dd9cbfb9d5c093dbb7051616/pkg/sql/opt/bench/out#L0)):*
I think this file was added by accident
___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy2tQBBvRUj0T414pV:-LJy2tQBBvRUj0T414pW:bofjw7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecabf9f4ee4017ba63f16be12d4a79da1e49978c/pkg/sql/opt/exec/execbuilder/testdata/join#L185)):*
> ```
> ----
> render               ·         ·                  (x, two, plus1)     ·
>  │                   render 0  COALESCE(x, x)     ·                   ·
> ```

I thought in this case the name would be qualified since x is ambiguous...
___
*[pkg/sql/opt/memo/expr_view_format.go, line 546 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy4DQ-7xG3i7I6FkRq:-LJy4DQ-7xG3i7I6FkRr:b-cidoy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59acf37a044e9b3dd9cbfb9d5c093dbb7051616/pkg/sql/opt/memo/expr_view_format.go#L546)):*
> ```Go
> // as "a.x + b.x" to "x". It is better to err on the side of not shortening
> // than to incorrectly shorten a column name representing an expression.
> func isSimpleColumnName(label string) bool {
> ```

The comment for this function needs to be updated since now we're only using it to decide whether to wrap an expression in quotation marks.  Alternatively, maybe we can just delete it since column names are no longer expressions. (Unnamed columns are now `?column?`).
___
*[pkg/sql/opt/memo/memo_format.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy0HG85xEea1n6cdQn:-LJy0HG85xEea1n6cdQo:bi05o3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecabf9f4ee4017ba63f16be12d4a79da1e49978c/pkg/sql/opt/memo/memo_format.go#L244)):*
> ```Go
> }
> 
> // forEachDependency runs f for each child group of g.
> ```

update comment - f doesn't exist anymore

**Review by petermattis — APPROVED** [review]
`r2` looks good to me. The rest is beyond me.

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 45 of 45 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-:-LJyUx3h-JiUqU_j7pqE:b-m5f0en)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28609)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/join, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy2tQBBvRUj0T414pV:-LJzxhQZ21Zp43G1efvM:b-wjz2nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecabf9f4ee4017ba63f16be12d4a79da1e49978c/pkg/sql/opt/exec/execbuilder/testdata/join#L185)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I thought in this case the name would be qualified since x is ambiguous...
</blockquote></details>

The `execbuilder` is not using the qualified names code. It *sometimes* uses `ColumnLabel`, if there happen to be at least one synthesized columns in the projection list. But if there are only passthrough columns, it does not even use `ColumnLabel`. Therefore, I thought it best just to make it consistent for now, in that it will never use qualified names. As an example of a test case that doesn't use qualified names, see this one above in the file:

`EXPLAIN (VERBOSE) SELECT * FROM twocolumn AS a JOIN twocolumn AS b ON a.x = 44`

I also spoke to Radu, and he's fine with changing this behavior for this edge case, since column names below the top-level are only used for debugging.
___
*[pkg/sql/opt/memo/expr_view_format.go, line 546 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy4DQ-7xG3i7I6FkRq:-LK-9AtY8a7JBu1B2foL:b-azsx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59acf37a044e9b3dd9cbfb9d5c093dbb7051616/pkg/sql/opt/memo/expr_view_format.go#L546)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The comment for this function needs to be updated since now we're only using it to decide whether to wrap an expression in quotation marks.  Alternatively, maybe we can just delete it since column names are no longer expressions. (Unnamed columns are now `?column?`).
</blockquote></details>

I updated the comment, since it's still useful for column names that have spaces, etc.
___
*[pkg/sql/opt/memo/memo_format.go, line 244 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy0HG85xEea1n6cdQn:-LK-9sD18vGUuKwH6gn3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecabf9f4ee4017ba63f16be12d4a79da1e49978c/pkg/sql/opt/memo/memo_format.go#L244)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update comment - f doesn't exist anymore
</blockquote></details>

Done.
___
*[pkg/sql/opt/bench/out, line  at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-LJy2eqM-morNGGjFfd_:-LJzxaSj8Ks1GKpZ3FHu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d59acf37a044e9b3dd9cbfb9d5c093dbb7051616/pkg/sql/opt/bench/out#L)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this file was added by accident
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 114 files at r6, 1 of 7 files at r7, 29 of 44 files at r9, 83 of 83 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28609)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28609#-:-LK23-bK2cAPNROqf8PV:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
