### PR TITLE
testutils/lint: convert some checkers to go/analysis

### PR DESCRIPTION
**Pull request by madelynnblue**
Convert float, unconvert, and timer to go/analysis
(https://godoc.org/golang.org/x/tools/go/analysis). This is the new,
official static analysis framework for Go. These were previously
disabled. Although now they work again, they are not yet hooked up. It
appears difficult to run these from inside a test. The Go people
apparently are steering us toward using the CLI instead. Hence, roachlint.

Add roachlint, a program to run these checkers. Not yet hooked up to
TestLint.

See #33669. Although that mentions using honnef.co/go/tools, that tool
now uses go/analysis: https://staticcheck.io/changes/2019.2#go-analysis.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
Patterns copied from official Go checkers. See https://github.com/golang/tools/tree/master/go/analysis/passes/atomic.

**Comment by RaduBerinde** [comment]
Thanks for taking this on!

**Comment by mjibson** [comment]
RFAL. Added all the linters and hooked it up to `make lint`. Separated out commits since many of the linters were now failing.

@bdarnell can you review the second commit, with the password stuff we discussed earlier today?

**Comment by bdarnell** [comment]
Second commit LGTM

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 19 of 20 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 25 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39159#-:-Llb3gdqEMgmfp8Pv5XC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter)

**Pull request merged**
