### PR TITLE
clusterversion,kvserver,sql: remove AutoStatsTableSettings

### PR DESCRIPTION
**Pull request by celiala**
This commit removes the 22.1 `AutoStatsTableSettings` version gate.

Cleanup was done following guidance from [21.2 cleanup](https://github.com/cockroachdb/cockroach/pull/74270#issuecomment-1000693734):

> For the most part, if the gates were just simple if !version.IsActive { return x } or something, I just removed the block, and even if it was a little more complicated, like args = [x]; if version { args = append(args, y) }; foo(args) I still tried to mostly inline it such that it looked natural (i.e. remove that append and make it args = [x, y]).

> However for just a couple more complicated cases that were referring to <21.2 versions that needed to be replaced when those were deleted, I added a placeholder clusterversion.TODOPre21_2 alias for 21.2. Replacing those calls with this alias shouldn't change their behavior -- it was already always true, since the code today should never run in a <21.2 cluster -- but means we can delete those older versions in the meantime and then the owners of these bits can decide how to update them.

Partially addresses https://github.com/cockroachdb/cockroach/issues/80663

Release note: None
Release justification: remove old version gates.

### CODE REVIEW

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85939#-:-N9CAM1FDvSVp6XLtnVf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala)

**Comment by celiala** [comment]
TFTR!

FYI @msirek that I'm removing `TestAutoStatsTableSettingsDisallowedOnOldCluster` -- please scream and shout if this should be kept!

Removing `TestAutoStatsTableSettingsDisallowedOnOldCluster` since:
- it was failing (expected "feature not available yet" error but instead got nil)
- it depended on both `ClusterLocksVirtualTable` and `AutoStatsTableSettings` --  both of which are 22.1 version gates

**Review by msirek — COMMENTED** [review]
It should be OK.  This change will only be in 22.2.  My understanding is, upgrades are only allowed one minor release at a time, so any nodes running an old version of CRDB would be on 22.1 at the oldest, which does support `AutoStatsTableSettings`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85939#-:-N9HFfg8DP8e8JRIW9c2:bws2bj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)

**Comment by celiala** [comment]
`TestLogic_external_connection_privileges` is failing all of https://github.com/cockroachdb/cockroach/pull/85937 , https://github.com/cockroachdb/cockroach/pull/85938 , https://github.com/cockroachdb/cockroach/pull/85939, so I'm going to assume that it's not related to changes in this commit.

```
off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/external_connection_privileges:24: SELECT * FROM system.privileges
        expected:
            root      /externalconn/foo  {ALL}         {}
            testuser  /externalconn/foo  {DROP,USAGE}  {}
        but found (query options: "") :
            testuser  /externalconn/foo  {DROP,USAGE}  {}
            root      /externalconn/foo  {ALL}         {}
```

**Comment by celiala** [comment]
TFTR!

bors r=msirek

**Pull request merged**
