### PR TITLE
Fix some test breakage.

### LINKED ISSUE #5539: circleci: failed tests (15180):
The following test appears to have failed:

[#15180](https://circleci.com/gh/cockroachdb/cockroach/15180):

```

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by knz**
Fixes #5539.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5541)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM please merge when green.

**Comment by tamird** [comment]
Looks like the build is further broken because `timeutil` no longer imports `util/log`. Remember this? https://github.com/cockroachdb/cockroach/commit/29d9bb2ad7a0fc536007417a2f04fe692c6e262f#diff-2f2ccd1d0c20d77cff06fd257ed19458R24

**Comment by knz** [comment]
What I am left to wonder at this point is why "make test" and "make acceptance" did not fail on my machine :(

**Comment by dt** [comment]
this is `make check`

**Comment by tamird** [comment]
Nah, the flags issue is `make test`, and the reason is that we pass
`--verbosity 2` in CI, but you didn't pass it locally.

**Comment by knz** [comment]
I added the fix in a new commit.

**Comment by tamird** [comment]
Commit message is wrong now.

**Comment by knz** [comment]
There you go.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5541#-:-KDe7Anp4-2Ji5tAO10l:1417088721)*

**Pull request merged**
