### PR TITLE
exec: fix calculation of selectivity stat when num batches is zero

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]

**Review by rohany — COMMENTED** [review]
LGTM -- were there cases where this was panicing (divide by zero)?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38972#-:-Lk5qMs-Czgeso1MQm1Z:bq21bp0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rohany — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38972#-:-Lk5qUY76vIqXa75zOoC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
It was probably panicking, but the panic would be caught, and it resulted with this
Screen Shot 2019-07-18 at 1 52 08 PM

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
