### PR TITLE
log: add `version` field to `json` formatted log entries

### LINKED ISSUE #70202: log: add `crdb_version` field to telemetry logs
Related to [CC-4889](https://cockroachlabs.atlassian.net/browse/CC-4889?focusedCommentId=59786): we are currently missing the `crdb_version` field in our sampled query logs

cc @knz @logston @kevin-v-ngo

### PR DESCRIPTION
**Pull request by cameronnunez**
Fixes [#70202](https://github.com/cockroachdb/cockroach/issues/70202).

Release note (cli change): version details have been added to all json formatted 
log entries. Refer to the reference docs for details about the field.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Let's not implement this as a payload field. We want/need the version details on all events, not just certain event types. So it belongs to the envelope.

We're looking at a new entry in `jsonTags` (json_encode.go), and a new WriteString sequence in `formatJSON`.

Then instead of `p.execCfg.Settings.Version.BinaryVersion().String()` use more simply `build.BinaryVersion()`.
You'll need to add that function to the `build` package like this:

```
// Version returns the version prefix, patch number and metadata of the current build.
func Version() string {
        v, err := version.Parse(tag)
        if err != nil {
                return "dev"
        }
        return v.String()
}
```

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-:-MjhMy1gBN3FWywnFlqL:b-2x9qdd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
This will also need a test.

**Review by knz — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70285)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/util/log/format_json.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-MjkCeD37eO56nlXYX8q:-MjkCeD37eO56nlXYX8r:b-tgs87l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee5f319e16fe792adbbf93eb88b587781385c50/pkg/util/log/format_json.go#L176)):*
> ```Go
> 	'x': {[2]string{"x", "cluster_id"},
> 		"The cluster ID where the event was generated, once known. Only reported for single-tenant of KV servers.", true},
> 	'v': {[2]string{"v", "crdb_version"},
> ```

you can simplify this to just `version`.
The product person wrote "crdb version" because from their perspective there are  many other components besides crdb. but from crdb's perspective, there's just one version to deal with.
___
*[pkg/util/log/log_entry.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-MjkCydk3i83McoVbvbP:-MjkCydk3i83McoVbvbQ:bnhoyuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee5f319e16fe792adbbf93eb88b587781385c50/pkg/util/log/log_entry.go#L64)):*
> ```Go
> 	ch Channel
> 	// The CockroachDB binary version with which the event was generated.
> 	version string
> ```

Where is the field populated?

**Review by cameronnunez — COMMENTED** [review]
Understood. Fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-:-MjkJfU629Ij-AalMNC4:b-9qxuxw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/format_json.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-MjkCeD37eO56nlXYX8q:-MjkJjAl9m3mqfLL2Gge:b-4hvi0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee5f319e16fe792adbbf93eb88b587781385c50/pkg/util/log/format_json.go#L176)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can simplify this to just `version`.
The product person wrote "crdb version" because from their perspective there are  many other components besides crdb. but from crdb's perspective, there's just one version to deal with.
</blockquote></details>

Got it.
___
*[pkg/util/log/log_entry.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-MjkCydk3i83McoVbvbP:-MjkJlGg1yDjv4PSyGif:buapiw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ee5f319e16fe792adbbf93eb88b587781385c50/pkg/util/log/log_entry.go#L64)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Where is the field populated?
</blockquote></details>

Apologies I should have marked this PR as a draft. My changes have been incremental. Still need to write up the test as well.

**Review by knz — COMMENTED** [review]
Functionality LGTM. There's an optimization needed though, see my comment below.

> Reviewed 1 of 13 files at r3, 12 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-:-MjmP2aC2TTu2Km4OuPK:bze7jzv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/util/log/log_entry.go, line 123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-MjmNYM3EYz_WO4Jxfja:-MjmNYM42rlSEXZ_YUsc:b-aqym5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee3b809c6a04bab67a28514a92f012e9a1df8013/pkg/util/log/log_entry.go#L123)):*
> ```Go
> 		sev:       s,
> 		ch:        c,
> 		version:   build.Version(),
> ```

ouch, we're hitting a little nag here. This Version() call is re-parsing the tag and re-allocating a string on the heap every time a log entry is created. That seems expensive, and unnecessary. We want to compute that version string just once and reuse it for all log entries.

However, at the same time we cannot simply create a global variable here with the  result of calling `build.Version`, because then the call to `TestingOverrideTag` in the test code will become ineffective.

I suggest the following:

1. add such a new global variable alongside `tag` in the `build` package:

    `var ( .... version = computeVersion(tag)`

2. implement `computeVersion` and `Version()` as follows:

```go
func computeVersion(tag string) string { /* same code you currently have in Version */ }

/* we're also renaming Version to BinaryVersion to clarify */
func BinaryVersion() string {
   return version
}
```

3. ensure that `TestingOverrideTag()` updates `version` too:

```go
func TestingOverrideTag(t string) func() {
        prev := tag
        prevVersion := version
        tag = t
        version = computeVersion(tag)
        return func() { tag = prev; version = prevVersion }
}
```

4. use `build.BinaryVersion()` here which now reuses a global variable.

**Comment by knz** [comment]
there's also another test that needs an update as indicated in CI.

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70285#-:-Mjq5WfK9YbYG3Z66MgH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cameronnunez)

**Comment by knz** [comment]
this will need a backport to the 21.2 branch, but is not a release blocker.
cc @thtruo

**Comment by knz** [comment]
@cameronnunez please also update the PR title (and commit title) before this merges.

**Comment by cameronnunez** [comment]
thanks @knz!

bors r=knz

**Comment by knz** [comment]
blathers backport 21.2

**Comment by knz** [comment]
blathers backport 21.1

**Comment by knz** [comment]
bors r-

this does not pass CI yet. missing bazel definition

**Comment by cameronnunez** [comment]
> bors r-
> 
> this does not pass CI yet. missing bazel definition

Seems like a npm error is preventing `make bazel-generate` from working. 

`ERROR: An error occurred during the fetch of repository 'npm':`
`ERROR: generate_build_file.ts failed: `

thoughts?

```
Generating DEPS.bzl and BUILD files using gazelle
./build/bazelutil/bazel-generate.sh
+ bazel run //:gazelle -- update-repos -from_file=go.mod -build_file_proto_mode=disable_global -to_macro=DEPS.bzl%go_deps -prune=true
INFO: Build option --run_under has changed, discarding analysis cache.
INFO: Analyzed target //:gazelle (77 packages loaded, 7390 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  _bazel/bin/gazelle-runner.bash
  _bazel/bin/gazelle
INFO: Elapsed time: 9.264s, Critical Path: 0.06s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Running command line: _bazel/bin/gazelle update-repos '-from_file=go.mod' '-build_file_proto_mode=disable_global' '-to_macro=DEPS.bzl%gINFO: Build completed successfully, 5 total actions
+ bazel run //pkg/cmd/generate-test-suites '--run_under=cd /Users/cameronnunez/go/src/github.com/cockroachdb/cockroach && '
Loading: 
Loading: 0 packages loaded
INFO: Build option --run_under has changed, discarding analysis cache.
Analyzing: target //pkg/cmd/generate-test-suites:generate-test-suites (1 packages loaded, 0 targets configured)
INFO: Analyzed target //pkg/cmd/generate-test-suites:generate-test-suites (1 packages loaded, 7272 targets configured).
INFO: Found 1 target...
[0 / 3] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //pkg/cmd/generate-test-suites:generate-test-suites up-to-date:
  _bazel/bin/pkg/cmd/generate-test-suites/generate-test-suites_/generate-test-suites
INFO: Elapsed time: 0.884s, Critical Path: 0.03s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: /bin/bash -c 'cd /Users/cameronnunez/go/src/github.com/cockroachdb/cockroach &&  _bazel/bin/pkg/cmd/generate-test-suites/generate-test-suites_/generate-test-suites '
INFO: Build completed successfully, 2 total actions
2021/09/21 17:30:12 Could not query Bazel tests: got error exit status 7
2021/09/21 17:30:12 Run `bazel query 'kind(go_test, //pkg/...)'` to reproduce the failure
make: *** [bazel-generate] Error 1
```

**Comment by knz** [comment]
That problem is really #70398.

 you work around by editing the file `util/log/BUILD.bzl` manually and add the missing line as recommended by the CI linter

**Comment by cameronnunez** [comment]
bors r=knz

**Comment by cameronnunez** [comment]
blathers backport 21.2

**Pull request merged**
