### PR TITLE
remove sql/driver

### PR DESCRIPTION
**Pull request by madelynnblue**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4845)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. I think you can squash my commit into yours. cc @petermattis @spencerkimball @vivekmenezes 

---

Reviewed 1 of 4 files at r1, 25 of 25 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4845#-:-KByg-WBS0ulN6K5XkBb:224814345)*

**Comment by petermattis** [comment]
Yay! I've been looking forward to this for a while. Didn't review the code, but I believe this fixes #3511.

**Comment by mjibson** [comment]
Yes, that issue is listed in the last commit.

**Comment by vivekmenezes** [comment]
Awesome!

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4845)*

**Comment by petermattis** [comment]
@tamird Can you take over responsibility for merging this PR?

**Comment by tamird** [comment]
Yep, I'm on it.

**Comment by tamird** [comment]
test failure is docker nonsense, merging

**Pull request merged**
