### PR TITLE
sql: add ddl analysis roundtrip tests for basic cases

### LINKED ISSUE #48498: sql: begin analysis of DDL roundtrips
We should analyze existing DDL statements to understand the roundtrips that they perform. Doing so may uncover patterns to make systematic improvements to DDL statement performance.

Tasks:
- [x] Figure out how to parse traces for roundtrips
- [x] Create a datadriven test that counts roundtrips for a query
- [x] Add a test for each DDL statement

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: write ddl analysis roundtrip tests for basic cases 

Tested cases for:
alter_table
create_alter_role
drop
grant_revoke
grant_revoke_role
truncate

Fixes #48498 

Release note: None

### CODE REVIEW

**Comment by RichardJCai** [comment]
I think this is ready for some comments.

Some things that jump out are DROP ROLE takes a pretty high amount of roundtrips for even dropping a single role (37). Looks like there some high overhead there.

Dropping multiple objects generally seems to increase nonlinearly, ie dropping 1 table takes 7 roundtrips, dropping 2 takes 16.

Interesting that truncating an empty table requires more round trips than truncating a table with values in it which seems to take a constant amount.

**Comment by rohany** [comment]
Overall, I'd like to see more tests like the one we have for `GRANT ROLE` where there are larger number of tables/indexes/columns/etc in the mix. I don't think there's much value in having these tests when there is only a single table with a single column -- these aren't the cases we're worried about.

**Comment by RichardJCai** [comment]
> Overall, I'd like to see more tests like the one we have for `GRANT ROLE` where there are larger number of tables/indexes/columns/etc in the mix. I don't think there's much value in having these tests when there is only a single table with a single column -- these aren't the cases we're worried about.

I would argue there is some value in the single table with a single column since it still is a baseline to catch regressions, but I'll try to "scale" these tests wherever I can.

**Comment by RichardJCai** [comment]
I think one example of low hanging fruit is for the case of CREATE ROLE and ALTER ROLE, the number of roundtrips increases linearly with the number of privileges, we should be easily able to batch this one.
I'll create an issue for it.

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_role.go#L182

**Comment by rohany** [comment]
We can discuss this in our meeting today, but I really feel that these small cases are things we want to avoid. They're likely to change during regular changes to the code, and most of those changes will all be OK. We don't care if a single alter command on a single table used to take 10 round trips, but now takes 11. We care more if an alter command suddenly starts taking O(tables) rts -- these small cases aren't going to catch those, and once we have the big cases there isn't a point of the small cases right?

**Comment by RichardJCai** [comment]
> We can discuss this in our meeting today, but I really feel that these small cases are things we want to avoid. They're likely to change during regular changes to the code, and most of those changes will all be OK. We don't care if a single alter command on a single table used to take 10 round trips, but now takes 11. We care more if an alter command suddenly starts taking O(tables) rts -- these small cases aren't going to catch those, and once we have the big cases there isn't a point of the small cases right?

We still probably want to test the cases with one object so we can compare how the complexity increases as we increase the number of objects right?

**Comment by rohany** [comment]
We'd want to test them as part of the analysis, but I don't think that they should be checked in and run as part of the test suite.

**Comment by RichardJCai** [comment]
> We'd want to test them as part of the analysis, but I don't think that they should be checked in and run as part of the test suite.

I'd argue there are some benefits to checking it in as well. For example in the grant privileges test, I think it's sort of useful to see that it takes 10 roundtrips to perform a grant on a single table and that the relation doesn't increase linearly. 
Without knowing how many roundtrips it takes to do one operation, we don't really have the context to know how the complexity is changing. If we only had the test for the  GRANT on 10 tables, I think it would be harder to historically track the complexity of the operation on multiple tables.

```
exec
CREATE TABLE t0()
----

count
GRANT ALL ON * TO TEST
----
10

count
REVOKE ALL ON * FROM TEST
----
10

exec
CREATE TABLE t1();
CREATE TABLE t2();
CREATE TABLE t3();
CREATE TABLE t4();
CREATE TABLE t5();
CREATE TABLE t6();
CREATE TABLE t7();
CREATE TABLE t8();
CREATE TABLE t9();
CREATE TABLE t10();
----

count
GRANT ALL ON * TO TEST
----
160

count
REVOKE ALL ON * FROM TEST
----
160
```

**Comment by RichardJCai** [comment]
Updated to remove the tests that test a single operation.

**Comment by rohany** [comment]
LGTM, lets see what others have to say as well.

**Review by solongordon — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50661)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai, @rohany, and @solongordon)

___
*[pkg/sql/testdata/ddl_analysis/alter_table, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50661#-MBF0z8-8S1hEZggSGcM:-MBF0z8-8S1hEZggSGcN:b-brb84j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36d3a6b0521b193d8493ac7318459be8b7d17b/pkg/sql/testdata/ddl_analysis/alter_table#L115)):*
> ```
> ALTER TABLE alter_table UNSPLIT AT VALUES (2), (3)
> ----
> 4
> ```

`ALTER TABLE ... CONFIGURE ZONE` and `ALTER TABLE ... PARTITION BY ...` might also be interesting to test.
___
*[pkg/sql/testdata/ddl_analysis/drop, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50661#-MBExzh04T2hwsX9P3lk:-MBExzh04T2hwsX9P3ll:b-k3wz3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36d3a6b0521b193d8493ac7318459be8b7d17b/pkg/sql/testdata/ddl_analysis/drop#L9)):*
> ```
> DROP ROLE a
> ----
> 36
> ```

This is interesting. Do you have intuition for what all these fetches are? Is it related to something like the number of objects in the db or the number of other roles?
___
*[pkg/sql/testdata/ddl_analysis/drop, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50661#-MBEyitK8Biwtqr_Z_mf:-MBEyitK8Biwtqr_Z_mg:b9j83kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d36d3a6b0521b193d8493ac7318459be8b7d17b/pkg/sql/testdata/ddl_analysis/drop#L126)):*
> ```
> DROP SEQUENCE s1, s2, s3
> ----
> 21
> ```

How about DROP DATABASE?
___
*[pkg/sql/testdata/ddl_analysis/ddl_analysis, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50661#-MBEz34j1yUMdeevY8md:-MBEz34j1yUMdeevY8me:b809ilf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbf51513c92c702d51f8046e08aba58bad5146bb/pkg/sql/testdata/ddl_analysis/ddl_analysis#L7)):*
> ```
> # NOTE: If the count (number of kv batch operations) increase is expected or
> # insignificant or the count decreases, update the test counts.
> # The rewrite option can be used to overwrite all the counts.
> ```

Should this comment be moved to a README.md in the directory or something?

**Comment by RichardJCai** [comment]
Done here. https://github.com/cockroachdb/cockroach/pull/50953

**Pull request closed without merging**
