### PR TITLE
sql/parser: Add new RETURNING NOTHING syntax

### PR DESCRIPTION
**Pull request by nvb**
This syntax is needed for #13160. It necessitated moving `NOTHING` from
an unreserved_keyword to a reserved_keyword, because the parser needs to
be able to distinguish it from expressions.

This change reworks the AST for RETURNING clauses. The old `ReturningExprs`
clause and the new `ReturningNothing` clause are now their own nodes in the
expression tree. A third `NoReturningClause` variant was added to avoid
`nil` values. This is made possible by a new shared `ReturningClause`
interface to provide this indirection.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13802)

### CODE REVIEW

**Comment by knz** [comment]
This is good. I like seeing the proposal "coming to action". 
My main comment is that I'd rather see less "valid uses" of nil pointers in our syntax code, not more. There is another way.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/returning.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrB_-SjGxPsMAMcvFc:-KdrB_-SjGxPsMAMcvFd:b-8c5llf) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/returning.go#L28)):*
> ```Go
> 
> func (*ReturningExprs) returningClause()  {}
> func (ReturningNothing) returningClause() {}
> ```

See below for my remark about a potential 3rd type `NoReturningClause`

---

*[pkg/sql/parser/stmt.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrAzt74H4UlPBovHIK:-KdrAzt8wOnQ9cBcMVqb:b-npnjur) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/stmt.go#L151)):*
> ```Go
> // StatementType implements the Statement interface.
> func (n *Delete) StatementType() StatementType {
> 	if n.Returning != nil {
> ```

Instead of this dance with the nil pointer, you could have a new struct `NoReturningClause` to represent this case, and implement the interface as well and do everything with that (either methods on it, or as a switch case)

---

*[pkg/sql/parser/stmt.go, line 481 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrAdef2oSBCtGNSCF3:-KdrAdef2oSBCtGNSCF4:b-qkpd0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/stmt.go#L481)):*
> ```Go
> func (n *RenameTable) String() string              { return AsString(n) }
> func (n *ReturningExprs) String() string           { return AsString(n) }
> func (n ReturningNothing) String() string          { return AsString(n) }
> ```

I wonder if it may not be interesting to have `ReturningNothing` implement this interface as pointer, and use a common instance everywhere it's needed.

---

*[pkg/sql/parser/update.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrBDEX7Ju2SXOO5tSq:-KdrBDEYl_FVjb_kPlbQ:b7ze511) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/update.go#L42)):*
> ```Go
> 	FormatNode(buf, f, node.Exprs)
> 	FormatNode(buf, f, node.Where)
> 	if node.Returning != nil {
> ```

see above my remark about using a 3rd type for "no returning clause"

---

*[pkg/sql/testdata/pipelining, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrBQz91s_GrdTRsXn0:-KdrBQz91s_GrdTRsXn1:b-nx7xqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/testdata/pipelining#L8)):*
> ```
> 
> statement error unimplemented: RETURNING NOTHING syntax is not yet supported
> DELETE FROM kv WHERE k = 1 RETURNING NOTHING
> ```

Since you're only adding syntax in this commit, a parser test is sufficient. Please delay introducing this file until it's needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-:-KdrBviadDLkrmGlgRdh:b-7w8trs)*

**Comment by nvanbenschoten** [comment]
Thanks for the advice! I like the `NoReturningType` variant proposal, even though it does go against Go's "useful zero values" mantra. PTAL.

---

Review status: 4 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/parser/returning.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrB_-SjGxPsMAMcvFc:-KdsXEO8xONlGbVo6f9Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/returning.go#L28)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See below for my remark about a potential 3rd type `NoReturningClause`
</blockquote></details>

Done.

---

*[pkg/sql/parser/stmt.go, line 151 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrAzt74H4UlPBovHIK:-KdsXH2wXNrtgBSTHHri:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/stmt.go#L151)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Instead of this dance with the nil pointer, you could have a new struct `NoReturningClause` to represent this case, and implement the interface as well and do everything with that (either methods on it, or as a switch case)
</blockquote></details>

Done.

---

*[pkg/sql/parser/stmt.go, line 481 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrAdef2oSBCtGNSCF3:-KdsXIALDUiwQKIrNyf2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/stmt.go#L481)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I wonder if it may not be interesting to have `ReturningNothing` implement this interface as pointer, and use a common instance everywhere it's needed.
</blockquote></details>

Done.

---

*[pkg/sql/parser/update.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrBDEX7Ju2SXOO5tSq:-KdsXIroXJfsbIPqHDQ-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/parser/update.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see above my remark about using a 3rd type for "no returning clause"
</blockquote></details>

Done.

---

*[pkg/sql/testdata/pipelining, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-KdrBQz91s_GrdTRsXn0:-KdsXJOJcaRmFZRPQ06O:b-6ziu6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/675c1f4ef0c1663bacc94f8d6eb6945f2801366a/pkg/sql/testdata/pipelining#L8)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since you're only adding syntax in this commit, a parser test is sufficient. Please delay introducing this file until it's needed.
</blockquote></details>

I think it's valuable to make sure that none of these cases crash and that even before the pipelining functionality is added, that they are handled correctly by the `sql` package and produce valid results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-:-KdsXVdhG0X1RDg69dTH:b-uzg84o)*

**Comment by knz** [comment]
LGTM, great :)

---

Review status: 4 of 18 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13802#-:-Kdu7u5YH5gf2ViYAOjv:b-bsxk6p)*

**Comment by nvanbenschoten** [comment]
TFTR

**Pull request merged**
