### PR TITLE
tracing: add an Unlock before panic, to prevent potential double lock

### PR DESCRIPTION
**Pull request by lzhfromustc**
***Description***
In cockroach/pkg/util/tracing/tracer_span.go, [func (*spanGroup).getSpans](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/tracing/tracer_span.go#L524), `s.mu.Lock()` is at line 532, and `s.mu.Unlock()` is at line 594. However, there is a panic at line 555. If the `panic` is executed, `s.mu` will still be locked even after recovery.

***How it is fixed***
Add an `s.mu.Unlock()` before `panic`.

***Something else***
I found the similar "missing unlock before panic" problems in 4 functions in cockroach/pkg/testutils/net.go. Shall I open another PR to fix them together?

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> I found the similar "missing unlock before panic" problems in 4 functions in cockroach/pkg/testutils/net.go. Shall I open another PR to fix them together?

If you wish, but probably not worth it. That file is just used by some tests, and behavior after a panic is not particularly important.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41621#-:-LrK1jfe8qN29w2SNbQP:bng2lwp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @lzhfromustc)

___
*[pkg/util/tracing/tracer_span.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41621#-LrK1RsG5zVJJZnTtl8M:-LrK1RsHAefoKRPvD3DV:b-ntz9b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c3b4cbce9c92e765c62834c0fae25234c8236c9/pkg/util/tracing/tracer_span.go#L555)):*
> ```Go
> 			stats, err := types.MarshalAny(s.mu.stats)
> 			if err != nil {
> 				s.mu.Unlock()
> ```

This seems too fragile to me. I think it'd be better to put all the locked blocked into an anonymous function and defer the unlock. Currently the existing unlock is too far from the lock anyway.

**Comment by lzhfromustc** [comment]
@andreimatei Thanks for the suggestion!
I'm not sure what you meant by putting locked blocks into anonymous function. 
If I put what's between Line 532 and Line 596 into an anonymous function, it may be too big. Do you think it is better to create a new function for this? Then how should I name it? I am really bad at naming XD

**Review by andreimatei — COMMENTED** [review]
>  Do you think it is better to create a new function for this?

I'd make a method on the `span` called `getRecording()` that returns a `RecordedSpan`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41621#-:-Lrinivz-UHINj-oiAr5:b-vva2we)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lzhfromustc)

**Comment by lzhfromustc** [comment]
@andreimatei Sounds great to me. 
Now I created a new method (*span).getRecording to return `rs`, and used `defer s.mu.Unlock()` to protect the whole method. 
I hope the way I wrote annotation for the new method is appropriate.

**Review by andreimatei — COMMENTED** [review]
Thanks!
I've rebased to get rid of the test failures, and slightly reworded the commit msg and a comment. I don't have permissions to push to your branch, so can you please pull from https://github.com/andreimatei/cockroach/commits/pr/41621 and then I'll merge it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41621#-:-Lro01YyBUPuCl4c0Y3I:beamypp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lzhfromustc)

**Comment by lzhfromustc** [comment]
@andreimatei Sorry, I missed your message until yesterday. 
I merged pr/41621 from your repo, and now our two branches have no diff.

**Comment by andreimatei** [comment]
Something was not right with the commits. There were 3 instead of 1 :P
I've merged the thing as #42075, so closing this.

Thanks for the contribution!

**Pull request closed without merging**
