### PR TITLE
allocator2: constraints module

### PR DESCRIPTION
**Pull request by sumeerbhola**
Contains helper classes and functions for the allocator related to
constraint satisfaction, where "constraints" include both replica counts
and constraints conjunctions. The primary ones are normalizedSpanConfig
and rangeAnalyzedConstraints.

Other misc pieces: storeIDPostingList represents a set of stores, and is
used here and will be used elsewhere for set operations.
localityTierInterner is used for interning the tiers to avoid string
comparisons, used for diversity computation. It will also be used
elsewhere.

The goal here is to decompose the allocator functionality into modules: the
constraints module does not know about the full set of stores in a cluster,
and only has a glimpse into those stores via knowing about the current set
of replica stores for a range and what constraints they satisfy.
rangeAnalyzedConstraints has various methods to aid in allocator
decision-making, and these return two kinds of candidates: candidates
consisting of existing replicas (which can be explicitly enumerated), and
candidates representing an unknown set that needs to satisfy some
constraint expression. The constraint expression is represented by a
constraintDisj.

Epic: none

Release note: None

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NRi6qs0-sWFb0orkjHq:-NRi6qs1EbuQEjjcRfW1:b3tt9ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bb3fddc0a6e011b72b54ce4a77709c41c98dbd/pkg/kv/kvserver/allocator/allocator2/constraint.go#L435)):*
> ```Go
> 	sumReplicaScore += srs
> 	numReplicaSamples += nrs
> 	srs, nrs = diversityFunc(rac.replicas[voterIndex], rac.replicas[nonVoterIndex], false)
> ```

Could you explain this part more, is this the same as taking the union of voters+nonVoters and calculating the diversity score of the set? why is the sameStores flag necessary for nonVoter X voter?
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NRi7qkeB6MP5Xtdu6KO:-NRi7qkeB6MP5Xtdu6KP:b-xw5ic0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bb3fddc0a6e011b72b54ce4a77709c41c98dbd/pkg/kv/kvserver/allocator/allocator2/constraint.go#L446)):*
> ```Go
> // Usage for a range that may need attention:
> //
> //				if notEnoughVoters() {
> ```

This seems logical and a lot easier to follow than the current necessary/valid and sprawl of logic in the replicate queue, allocator (scorer) that functions similar. 
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NRhyHDsBTVNLrNknziU:-NRhyHDsBTVNLrNknziV:bwaty6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bb3fddc0a6e011b72b54ce4a77709c41c98dbd/pkg/kv/kvserver/allocator/allocator2/constraint.go#L579)):*
> ```Go
> // more optimally fix things without moving replicas.
> //
> // TODO(sumeer): do we do this in the current allocator? If not, should we
> ```

We don't afaik, or at least we don't prioritize it. Kai added prioritization for the promotion case.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98877)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NRi6qs0-sWFb0orkjHq:-NRiU_ru0kBSKexww_96:bsqb4bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bb3fddc0a6e011b72b54ce4a77709c41c98dbd/pkg/kv/kvserver/allocator/allocator2/constraint.go#L435)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you explain this part more, is this the same as taking the union of voters+nonVoters and calculating the diversity score of the set? why is the sameStores flag necessary for nonVoter X voter?
</blockquote></details>

Yep, it is the same as taking the union. The sameStores parameter is false since there won't be duplicates across these two set, so we don't need to de-dup pairs.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NRhyHDsBTVNLrNknziU:-NRiVJm7--wxQ4MIBwJ2:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bb3fddc0a6e011b72b54ce4a77709c41c98dbd/pkg/kv/kvserver/allocator/allocator2/constraint.go#L579)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

We don't afaik, or at least we don't prioritize it. Kai added prioritization for the promotion case. 
</blockquote></details>

Ack

**Review by kvoli — COMMENTED** [review]
:lgtm:

No material comments. I follow the structure and the interaction example seems great. I may revisit once I'm writing code here.

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-:-NTq9eYv6pxI8mJRiOMF:baaelf0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 858 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NTq88OL5YccGj0q9wpg:-NTq88OM8D48Cdk_Jjkt:b-hhet4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b78cc4c72becc78730cf53a2c4ec6f1e8533bfb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L858)):*
> ```Go
> 	toAdd constraintsDisj,
> ) {
> 	// TODO(sumeer): implement
> ```

Are you okay with merging these TODOs? I'm guessing that was the intention to enable concurrent work.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 945 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NTq6OZE9NaFJ4tMeJqk:-NTq6OZE9NaFJ4tMeJql:bzfg0yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b78cc4c72becc78730cf53a2c4ec6f1e8533bfb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L945)):*
> ```Go
> 			n := len(lti.stringToInt)
> 			if n == math.MaxUint32 {
> 				log.Fatalf(context.Background(), "overflowed localities")
> ```

Are there any benefits to using log.Fatalf with bg ctx over a panic here?

**Review by kvoli — APPROVED** [review]

**Comment by kvoli** [comment]
Looks like the bazel entry needs to be generated to appease CI.

**Review by sumeerbhola — COMMENTED** [review]
> Looks like the bazel entry needs to be generated to appease CI.

Done

Also moved some allocator.go changes from the second commit in #99977 to here

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-:-NTu3Wdm6lbsZXwqXGkh:b-89xctd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 858 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NTq88OL5YccGj0q9wpg:-NTu2Mu01ibbFxe_q6zv:b3d392h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b78cc4c72becc78730cf53a2c4ec6f1e8533bfb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L858)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Are you okay with merging these TODOs? I'm guessing that was the intention to enable concurrent work.
</blockquote></details>

Yep. And all the TODO(sumeer)'s are actually for either of us to pick up.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 945 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-NTq6OZE9NaFJ4tMeJqk:-NTu31AlDKXBslrWExze:bpan88z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b78cc4c72becc78730cf53a2c4ec6f1e8533bfb/pkg/kv/kvserver/allocator/allocator2/constraint.go#L945)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Are there any benefits to using log.Fatalf with bg ctx over a panic here?
</blockquote></details>

changed to panic

**Review by sumeerbhola — COMMENTED** [review]
I will merge as soon as I've fixed all the unused lint errors.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98877#-:-NTuSqog4vxWjM98DxqK:b-la9mps)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
