### PR TITLE
tracing: support storing Tracer in Context

### PR DESCRIPTION
**Pull request by RaduBerinde**
Allowing NewServer to be passed a context that can have a Tracer already set.
This would (for example) allow disabling tracing for this server without using
the global Disable().

The intention is that we will remove the Tracer fields from various contexts and
instead plumb Contexts.

@andreimatei @petermattis

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8467)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Side note - there is confusion between context.Context and our own Contexts. It would be great if we could find another name for the latter but I can't think of anything. Al I can think of is "Env" (as in environment) or "backdrop" (pretty bad haha)

**Comment by dt** [comment]
I'll add `Configuration` to this bike shed.

**Comment by bdarnell** [comment]
I like `Config` for things that are just input parameters (like `storage.StoreContext`) but not for stateful things like `rpc.Context` (but maybe that should be refactored into an `rpc.Config` object and a separate `rpc.Client`)

**Comment by petermattis** [comment]
Yeah, I think we should get rid of the `Context` terminology from our code. `Env` is good. I've used that in a previous life. I could also be happy with `Options` or `Config`.

**Comment by RaduBerinde** [comment]
Thanks! I think I will start out by renaming the things which are strictly input parameters to `Config`, and probably use `Env` for what's left.

In a lot of cases I want to pass a `context.Context` inside a `Config` (which gets stored), but then I may need to modify that context (e.g. to set a node id tag when the node id becomes available). I'm thinking out loud if we should always avoid modifying things inside a `Config`. Maybe the `Config` should have a fixed `baseCtx` and I should store the potentially modified `ctx` separately inside the parent structure.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-:-KOu4eymwlZNWL-99xFW:bnvs2qd)*

**Comment by RaduBerinde** [comment]
Updated after some renamings

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/context.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvUlLYk25qSmHE8JFk:-KOvUlLZ1rZkZZ--SW_b:bb3ukda) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/server/context.go#L164)):*
> ```Go
> 	TestingKnobs base.TestingKnobs
> 
> 	// Base context.Context for the server.
> ```

does this pass golint? note that https://github.com/cockroachdb/cockroach/pull/8490 just went in.

Also, @bdarnell recently mentioned on one of my PRs that storing context.Context on structs is considered by the Go team to be a bad pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/tracing/tracer.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvVTsAnCB_-LODG1Ki:-KOvVTsAnCB_-LODG1Kj:b-wh5336) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/util/tracing/tracer.go#L154)):*
> ```Go
> 
> func TracerFromCtx(ctx context.Context) opentracing.Tracer {
> 	tracerVal := ctx.Value(contextTracerKeyType{})
> ```

nit:
```
if tracer := ctx.Value(contextTracerKeyType{}); tracer != nil {
  return tracer.(opentracing.Tracer)
}
return nil
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/context.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvUlLYk25qSmHE8JFk:-KOvYBlGY_igk_xPBFlK:b-iz8mrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/server/context.go#L164)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this pass golint? note that https://github.com/cockroachdb/cockroach/pull/8490 just went in.
> 
> Also, @bdarnell recently mentioned on one of my PRs that storing context.Context on structs is considered by the Go team to be a bad pattern.
</details>
Fixed.

I found and read the discussion and the doc. In this case we are probably going beyond the intended use of `Context` - the docs say Values are only for "request-scoped" data but here we are using them for `Tracer` (and soon node ID log tag) which has a long-lived scope. Plus the ship has kind of sailed in that we store contexts in a lot of structs, most importantly in `Txn`.

---

*[util/tracing/tracer.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvVTsAnCB_-LODG1Ki:-KOvYJGKtUQo-mPjBppS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/util/tracing/tracer.go#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit:
> ```
> if tracer := ctx.Value(contextTracerKeyType{}); tracer != nil {
>   return tracer.(opentracing.Tracer)
> }
> return nil
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/context.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvUlLYk25qSmHE8JFk:-KOvaRtsVSfCSZrIk8sA:b8ynvc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/server/context.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Fixed.
> 
> I found and read the discussion and the doc. In this case we are probably going beyond the intended use of `Context` - the docs say Values are only for "request-scoped" data but here we are using them for `Tracer` (and soon node ID log tag) which has a long-lived scope. Plus the ship has kind of sailed in that we store contexts in a lot of structs, most importantly in `Txn`.
</details>
Eh, "the ship has sailed" is not convincing. Is there a fundamental reason we can't pass this context in function scope instead?

Btw, "request scoped" is poorly defined - it's really "context scoped", so as long as we're true to that, I think we're OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/context.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvUlLYk25qSmHE8JFk:-KOvbDRWP5DSEixadUos:bbw5zgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/server/context.go#L164)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Eh, "the ship has sailed" is not convincing. Is there a fundamental reason we can't pass this context in function scope instead?
> 
> Btw, "request scoped" is poorly defined - it's really "context scoped", so as long as we're true to that, I think we're OK.
</details>
The fundamental reason is that it is a context that is long lived (longer than any given operation) and it's intended to be associated with top-level server operations. E.g. when `Server.Start()` is called, the context I want to be operating on is the server's context, not the context of how the caller came around to calling `Start()`.

I think the "request scoped" thing is not mere phrasing - it seems at the root of what Context was designed for (it's centered around deadlines, cancellation etc). We are going a bit beyond that with the long-lived contexts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/context.go, line 164 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOvUlLYk25qSmHE8JFk:-KOw75Da-_6NPUAbJC-X:b-gni1j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab7cf1e626d91a5d739b2ea8734e9645b50470b1/server/context.go#L164)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The fundamental reason is that it is a context that is long lived (longer than any given operation) and it's intended to be associated with top-level server operations. E.g. when `Server.Start()` is called, the context I want to be operating on is the server's context, not the context of how the caller came around to calling `Start()`.
> 
> I think the "request scoped" thing is not mere phrasing - it seems at the root of what Context was designed for (it's centered around deadlines, cancellation etc). We are going a bit beyond that with the long-lived contexts.
</details>
The rule about not storing contexts in structs is not strict. The Google folks break it themselves with the [`http.Request`](https://tip.golang.org/src/net/http/request.go?s=10070:10113#L271) and [`grpc.serverStream`](https://github.com/grpc/grpc-go/blob/master/stream.go#L433-L435). I haven't reviewed this code, just pointing out that we shouldn't have a strict prohibition about doing this but should consider the context of the usage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KOyn0VU08Ar4jD5qTKj:b-1gxwo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
> ```Go
> 
> 	// Ctx is the base context.Context for the server.
> 	Ctx context.Context
> ```

Would it be better to include the tracer explicitly here instead of passing it in `Ctx`? And if the tracer is passed explicitly, would `Ctx` every be different than `context.Background()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KOz-7tCGkN4LpUaxRRH:b89bxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Would it be better to include the tracer explicitly here instead of passing it in `Ctx`? And if the tracer is passed explicitly, would `Ctx` every be different than `context.Background()`?
</details>
My intention is to allow any function anywhere to start a span (or call other Tracer functions) by having just a context. That is how the tracing APIs are intended to work, we just made it harder by having multiple `Tracer`s.

Even if we didn't have the `Tracer` in the context, I would like this context to contain a `node=X` log tag so any top-level log `server` messages would show that. Finally, if we want to eventually rely on traces more than logs, we may want this context to have a span open so that we can collect all the top-level log messages for the server (e.g. in a specific test).

I want every level (sql executor, TxnCoordSender etc) to have a context that can be used for their "top-level" messages, and to derive more specific contexts for txns etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KOzH-cGAwCM7v8LAXYF:b71ljir) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> My intention is to allow any function anywhere to start a span (or call other Tracer functions) by having just a context. That is how the tracing APIs are intended to work, we just made it harder by having multiple `Tracer`s.
> 
> Even if we didn't have the `Tracer` in the context, I would like this context to contain a `node=X` log tag so any top-level log `server` messages would show that. Finally, if we want to eventually rely on traces more than logs, we may want this context to have a span open so that we can collect all the top-level log messages for the server (e.g. in a specific test).
> 
> I want every level (sql executor, TxnCoordSender etc) to have a context that can be used for their "top-level" messages, and to derive more specific contexts for txns etc.
</details>
I agree with the desire to have a context for the different entities that has appropriate log tags set on it. But in this case, the caller doesn't know the server's node ID. So the server internally needs to add that log tag when it discovers it (either after bootstrapping or after reading it from disk).

Your other point seems good to, it just isn't obvious while the creator of the `server.Context` would add the tracer to the context vs doing it inside `server.NewServer`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KOzJihYVKvoQYEYxREp:b-971179) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I agree with the desire to have a context for the different entities that has appropriate log tags set on it. But in this case, the caller doesn't know the server's node ID. So the server internally needs to add that log tag when it discovers it (either after bootstrapping or after reading it from disk).
> 
> Your other point seems good to, it just isn't obvious while the creator of the `server.Context` would add the tracer to the context vs doing it inside `server.NewServer`.
</details>
Ah sorry I misunderstood what you were asking.  This field has a dual purpose:
 - storing a long-lived context inside the `Server`. Indeed, this context will need to be modified to add a nodeID log tag so it may be appropriate to put it directly inside `Server` and not modify it inside this embedded structure (TBD).

 - allows the caller to pass a context to `NewServer` (I think this is what you asked about, but I had the other thing in mind, sorry).  I think this can be useful for a number of things:
  - Passing a context allows the caller to set up a tracing span to capture the top-level server messages
  - If we are starting a test cluster we may want to have a base context for all the servers in that cluster. So that e.g. if we have a test with multiple test clusters we can use clusterID log tags to differentiate, or set up a tracing span for each cluster.
  - I think that soon each go test will have a context and everything that test does should be derived from that context. That would allow things like having a tracing span for the entire test, or adding log tags for the test to distinguish log messages when running multiple tests in parallel.

 In general, any time we hardcode a `context.Background()` somewhere, we are wasting an opportunity to  allow that thing to be properly used from inside another things (whether that is a test, test cluster, or whatnot).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KPEcxFPJWFY39l-zqNz:bn3ubka) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah sorry I misunderstood what you were asking.  This field has a dual purpose:
>  - storing a long-lived context inside the `Server`. Indeed, this context will need to be modified to add a nodeID log tag so it may be appropriate to put it directly inside `Server` and not modify it inside this embedded structure (TBD).
> 
>  - allows the caller to pass a context to `NewServer` (I think this is what you asked about, but I had the other thing in mind, sorry).  I think this can be useful for a number of things:
>   - Passing a context allows the caller to set up a tracing span to capture the top-level server messages
>   - If we are starting a test cluster we may want to have a base context for all the servers in that cluster. So that e.g. if we have a test with multiple test clusters we can use clusterID log tags to differentiate, or set up a tracing span for each cluster.
>   - I think that soon each go test will have a context and everything that test does should be derived from that context. That would allow things like having a tracing span for the entire test, or adding log tags for the test to distinguish log messages when running multiple tests in parallel.
> 
>  In general, any time we hardcode a `context.Background()` somewhere, we are wasting an opportunity to  allow that thing to be properly used from inside another things (whether that is a test, test cluster, or whatnot).
</details>
I think there's agreement that a `Server` should have a long-lived `Context`.
So focusing on whether the `Context` should be passed through this `server.Context` struct:
- if we end up with the field here, we should comment that it's optional, and if not filled in, `newServer` will init a proper ctx
- maybe it'd be useful to have a shared `Context` for all the servers in a cluster, but I don't clearly see the use yet. I don't think we're going to have tests with more than one cluster...? A cluster is the cockroach universe, there's no federation across clusters... What could you test with more than one cluster? And for a single cluster, I think there's no logical operations across the cluster that would require new spans. Like, there's no such thing as stopping the whole cluster and restating it; you do that separately for each server.
- there should be a span for the lifetime of a `Server`. And it'd be cool if the span ended when we stop the server, and a new span starts when we start it up again. But I don't see why the caller would control this span, as opposed to creating in `Server.Start`. Would it be useful to have a span for the lifetime of a cluster?
- there's the use-case with tests, where maybe you want the server started by the test and the rest of the test code to share a context... But I don't clearly see why... In the real world, there's no context across the server and the (SQL) clients... And the testing framework already isolates log messages from different tests.

So I'm not convinced that this field is needed. Maybe it can indeed just be replaced with a tracer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KPEkHRzg_b7sgXRTi2S:b1on67s) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
> there should be a span for the lifetime of a Server

Well, not in production right? Because that span will never Finish and just keep growing in memory. So maybe we want that just for tests. But that means that the caller will need to control it. If it's not going to be done via the context, we will need to add more arguments for that..  I don't see how passing a `Tracer` and then later a `Span` (or a flag to start a Span) is somehow preferable to a context which is much more versatile.

>  I don't clearly see the use yet. I don't think we're going to have tests with more than one cluster...?

I could see the possibility of having a test that spawns multiple test clusters with different configurations, and runs random operations, cross-checking results.

> And the testing framework already isolates log messages from different tests.

I don't think that will be the case if we start running some tests in parallel..


Anyway, this is a lot of debating about a field.. Frankly I don't see the downside of passing it but I can remove it. I thought that you and I agreed that everything should be passed a context (and that each test will have its context)..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467)*

**Comment by andreimatei** [comment]
:lgtm:

Other stuff discussed offline - prevent a cancelable context in NewServer, maybe rely on the singleton tracer

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 165 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KOyn0VU08Ar4jD5qTKi:-KPFCn3v82_1i0396O8I:bnwrx1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/59b12c8c6870e413a15b2fbd2620f81f544d570c/server/context.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> > there should be a span for the lifetime of a Server
> 
> Well, not in production right? Because that span will never Finish and just keep growing in memory. So maybe we want that just for tests. But that means that the caller will need to control it. If it's not going to be done via the context, we will need to add more arguments for that..  I don't see how passing a `Tracer` and then later a `Span` (or a flag to start a Span) is somehow preferable to a context which is much more versatile.
> 
> >  I don't clearly see the use yet. I don't think we're going to have tests with more than one cluster...?
> 
> I could see the possibility of having a test that spawns multiple test clusters with different configurations, and runs random operations, cross-checking results.
> 
> > And the testing framework already isolates log messages from different tests.
> 
> I don't think that will be the case if we start running some tests in parallel..
> 
> 
> Anyway, this is a lot of debating about a field.. Frankly I don't see the downside of passing it but I can remove it. I thought that you and I agreed that everything should be passed a context (and that each test will have its context)..
</details>
OK, you had me at the ever growing span in production. So this field looks better to me now.

---

*[server/server.go, line 109 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KPFFJTVD-01jtGnfjCF:-KPFFJTXlkLBf7ti1vza:b-m63ju9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d844522af777e9e855730fb768db1c236f4a2d/server/server.go#L109)):*
> ```Go
> 
> 	if srvCtx.Ctx == nil {
> 		// TODO(radu): we should make sure the callers set this explicitly instead.
> ```

Mmm I'd get rid of the todo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-:-KPFMfE9XaYfaoeKfzPh:b-38mzmq)*

**Comment by RaduBerinde** [comment]
TFTR. Updated.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 109 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-KPFFJTVD-01jtGnfjCF:-KPFVP-GfrTSy5ZAJblO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46d844522af777e9e855730fb768db1c236f4a2d/server/server.go#L109)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Mmm I'd get rid of the todo
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-:-KPFVQGbl4Ck0WnTCYDM:b3royfu)*

**Comment by andreimatei** [comment]
still LGTM

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8467#-:-KPOWyOqN9h3TcepG99O:bh5f435)*

**Pull request merged**
