### PR TITLE
cli: add retries on datadog metrics upload requests

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously datadog metrics upload command would fail once we receive an error in datadog request. This was resulting in re-running the entire upload. This change adds retries on datadog requests. Command would skip particular datadog upload request once retries are exhausted.

Epic: CC-27740
Release note: None

### CODE REVIEW

**Review by arjunmahishi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130857#-:-O7Dz_QcDicO0T6zRUTd:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons and @dhartunian)

**Review by angles-n-daemons — APPROVED** [review]
:lgtm: out of curiosity, does the failure rate increase dramatically with the size of the upload?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130857#-:-O7Ele4i7i4if2Vp0C13:bwmvb4)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by aa-joshi** [comment]
> :lgtm: out of curiosity, does the failure rate increase dramatically with the size of the upload?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130857#-:-O7Ele4i7i4if2Vp0C13:bwmvb4)_ status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dhartunian)

No, It is irrespective of upload size. We are uploading ~2MB of gzip data with each request.

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Pull request merged**
