### PR TITLE
sql/randgen/rowenc: organize random generator test utilities

### PR DESCRIPTION
**Pull request by mgartner**
#### randgen/rowenc: move random generators to new randgen package

This commit moves random generator test utilities from the `rowenc`
package, which provides unrelated encoding utilities, to a new `randgen`
package. In order to prevent an import cycle, some tests in the `rowenc`
package have been moved to the `rowenc_test` package.

Release note: None

#### sql/randgen: refactor randgen package

This commit splits the single file of the `randgen` package into
multiple files organized by the theme of the contained utility
functions.

This commit also moves `randgen.OneIntCol`, `randgen.TwoIntCols`, and
other non-random, type-related test helpers to the `types` package in
`pkg/sql/types/testutils.go`.

Release note: None

#### randgen: add doc.go

Release note: None

#### randgen/mutations: move mutators to randgen

This commit moves random SQL statement mutators from the `mutations` to
the `randgen` package, which is a more appropriate home for them.

Note that there are still a few test utility functions in the
`mutations` package, though I'm not convinced they belong there. If
someone knows of a better package for them, I'd gladly eliminate the
`mutations` package altogether.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This mostly moves a bunch of stuff around. I tried to minimize changes beyond copy/pasting big blocks of code. There's probably some more refactoring to be done, but I'll save that for a future PR.

There's a few functions remaining in the `mutations` package which I didn't have a great idea where to put - but if there is a better place, that package can be eliminated.

**Review by ajwerner — APPROVED** [review]
The tiny stuff in `mutations_utils.go` seems like it could just go in the `rows` package. Save that change for a different PR as it is worthy of independent discussion.

:lgtm: 

> Reviewed 122 of 122 files at r1, 50 of 51 files at r2, 1 of 1 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63358#-:-MXqwfqE8rxELqzu6IZF:b-i0ao18)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @mgartner, and @RaduBerinde)

___
*[pkg/sql/testutils.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63358#-MXqvWkp6SmGHftOtEDE:-MXqvWkp6SmGHftOtEDF:bpwrt09) ([raw file](https://github.com/cockroachdb/cockroach/blob/844407b0caa56ef47d9456ec742cd3fe5c9cc850/pkg/sql/testutils.go#L156)):*
> ```Go
> 
> // The following variables are useful for testing.
> // TODO(mgartner): There's no randomness for these variables or MakeIntCols, so
> ```

This comment seems stale given these are now in `sql`

**Review by mgartner — COMMENTED** [review]
> The tiny stuff in mutations_utils.go seems like it could just go in the rows package. Save that change for a different PR as it is worthy of independent discussion.

SGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63358#-:-MXrZ07XDeq8tPT894q8:bbiqyah)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @RaduBerinde)

___
*[pkg/sql/testutils.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63358#-MXqvWkp6SmGHftOtEDE:-MXrZ12FBQ4XpgFLL-2I:bves986) ([raw file](https://github.com/cockroachdb/cockroach/blob/844407b0caa56ef47d9456ec742cd3fe5c9cc850/pkg/sql/testutils.go#L156)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This comment seems stale given these are now in `sql`
</blockquote></details>

Good catch! Fixed.

**Review by ajwerner — COMMENTED** [review]
Somewhere you've got a `pkg/errors`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63358#-:-MY8AqkqEiKwq3RPdih5:bwlglgc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @RaduBerinde)

**Comment by mgartner** [comment]
Had to move those type-related test helpers out of `sql` package due to import cycle. I moved them to `types` instead.

**Comment by mgartner** [comment]
How naïve of me to think it'd be this easy. Of course these random generators live in `rowenc` because they depend on `rowenc` functions and `rowenc` tests depend on the random generators.

**Comment by mgartner** [comment]
Fixed the cycle by moving some tests in `rowenc` to `rowenc_test`, which maybe isn't ideal, but there's already some `rowenc_test` tests, so I don't think it's terribly worse.

**Review by ajwerner — APPROVED** [review]
LGTM!

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
