### PR TITLE
obsservice: create batches for insert insights

### PR DESCRIPTION
**Pull request by maryliag**
Note to reviewers: The values for 100 Insights and the at least 1 minute are random for now. Later we can check if another value makes more sense.

---
Previously, all insights were being inserted as soon as exported to obsservice.
This commit introduces a cache to batch insights and do less inserts.
When the caches reaches 100 entries or it has been at least a minute since last insert, we do an insert.

Fixes CC-26215

Demo: https://www.loom.com/share/ecf706d41155484eb2fd532414a4f7b6

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @maryliag)

___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNFvm91K0oMdvxR1yf:-NkNFvm91K0oMdvxR1yg:b-7g33a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L30)):*
> ```Go
> 
> 		lastExportTs time.Time
> 		insights     *cache.UnorderedCache
> ```

Why do you need `UnorderedCache`? Can you use a slice here instead? I don't think you will ever need random access to the elements, only in order of insertion.
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNIE928rcsJYPJ6HnX:-NkNIE928rcsJYPJ6HnY:b-uvxrq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L61)):*
> ```Go
> 	p.mu.insights.Add(string(stmtInsight.ID), stmtInsight)
> 	if p.mu.insights.Len() >= InsightsBatchMax || timeutil.Since(p.mu.lastExportTs) > time.Minute {
> 		err := p.exportInsights(ctx)
> ```

It seems like if you do this, you will leave `p.mu` locked until you finish the insert which will block writes. You might want to grab the list of "stuff to insert", reset the array, and release the lock so that inserts can continue.
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNHEHO89eiOd9EEv3d:-NkNHEHO89eiOd9EEv3e:b-smkm80) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L123)):*
> ```Go
> 			tree.DNull,
> 		)
> 		rows = rows + fmt.Sprintf(`%s ($%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, $%v, 
> ```

can you use `strings.Join` to add the comma in between a list of insert clauses?
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNGQinBRtvtRUT_w_C:-NkNGQinBRtvtRUT_w_D:bpmydzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L129)):*
> ```Go
> 			placeholder+14, placeholder+15, placeholder+16, placeholder+17, placeholder+18, placeholder+19, placeholder+20,
> 			placeholder+21, placeholder+22, placeholder+23, placeholder+24, placeholder+25, placeholder+26, placeholder+27,
> 			placeholder+28, placeholder+29, placeholder+30)
> ```

can you construct a slice of placeholder IDs and then put them here like you did with `args` below?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNFvm91K0oMdvxR1yf:-NkRpArh2d6D3YdXDl-r:b-1h8m34) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L30)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why do you need `UnorderedCache`? Can you use a slice here instead? I don't think you will ever need random access to the elements, only in order of insertion.
</blockquote></details>

Changed to slice.
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNIE928rcsJYPJ6HnX:-NkRpEWkAPUZ2ct0mo_A:b21urit) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L61)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

It seems like if you do this, you will leave `p.mu` locked until you finish the insert which will block writes. You might want to grab the list of "stuff to insert", reset the array, and release the lock so that inserts can continue.
</blockquote></details>

Good point, I made some changes to only lock when using the mutex.
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNHEHO89eiOd9EEv3d:-NkRpKLr1HUNmecQj91L:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L123)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you use `strings.Join` to add the comma in between a list of insert clauses?
</blockquote></details>

Done
___
*[`pkg/obsservice/obslib/process/stmt_insights_processor.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-NkNGQinBRtvtRUT_w_C:-NkRpLN1-o-k_6_hkagJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/de0666dfdcd54bc3cac8c5ee3839af58657edd2a/pkg/obsservice/obslib/process/stmt_insights_processor.go#L129)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you construct a slice of placeholder IDs and then put them here like you did with `args` below?
</blockquote></details>

Done

**Review by dhartunian — APPROVED** [review]
:lgtm: fine for demo. thx for making the changes. in the future if you keep working on this code, consider making the processor more unit test friendly by extracting out all the SQL stuff to a separate struct so you can run tests on the flush logic.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115201#-:-Nkb_2vk4I1fxx2DC-EB:b-inj72s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by maryliag** [comment]
TFTRs!
bors r+

**Pull request merged**
