### PR TITLE
storage: simplify reservation system

### PR DESCRIPTION
**Pull request by tamird**
Removes reservationsByRangeID since all reservation state is now
function-scoped.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12201)

### CODE REVIEW

**Comment by petermattis** [comment]
This will cause merge conflicts with my PR which is not cool.

**Comment by tamird** [comment]
Yeah, I don't mind solving the conflicts - your PR inspired me to write
this, though.

**Comment by BramGruneir** [comment]
LGTM besides the dead replica check.  

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/reservation.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-KYWT3yPaXxsEsxgJ57q:-KYWT3yPaXxsEsxgJ57r:b-i2p4ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d29ab7654f6e3be5fb9de4c48260963f99e5fd7/pkg/storage/reservation.go#L63)):*
> ```Go
> 
> // Reserve attempts to reserve a replica and returns a boolean indicating
> // success. If reservation is successful, the returned function must be called
> ```

If **the** reservation is ...

---

*[pkg/storage/reservation.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-KYWYbMki5XAQra4PPcS:-KYWYbMki5XAQra4PPcT:b-qhkluj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e53ec1c1c78b18ffe6e23417424fed0b9f4533/pkg/storage/reservation.go#L132)):*
> ```Go
> 
> 	// Make sure that we don't add back a destroyed replica.
> 	for _, rep := range deadReplicas {
> ```

Are you sure removing this is safe?  You were mentioning that there was another system to protect against adding back a replica when a dead replica exists. 

If it is needed, can you add in a test for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-:-KYWc8aewIYtehwtVSax:b-gyrrf7)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/reservation.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-KYWT3yPaXxsEsxgJ57q:-KYYYCIFw4zG5_9Rkxu_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d29ab7654f6e3be5fb9de4c48260963f99e5fd7/pkg/storage/reservation.go#L63)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

If **the** reservation is ...
</blockquote></details>

Done.

---

*[pkg/storage/reservation.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-KYWYbMki5XAQra4PPcS:-KYYXB7E3AhY29aOtUnj:b-sgs32g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e53ec1c1c78b18ffe6e23417424fed0b9f4533/pkg/storage/reservation.go#L132)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are you sure removing this is safe?  You were mentioning that there was another system to protect against adding back a replica when a dead replica exists. 

If it is needed, can you add in a test for it?
</blockquote></details>

As the original author of this stuff - you tell me.

`deadReplicas` here is a slice of corrupted replicas, and corrupted replicas are correctly handled in `(*Store).tryGetOrCreateReplica`, which is called from the preemptive snapshot path. So it seems that it is impossible today for this check to catch anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201)*

**Comment by petermattis** [comment]
Given the direction you're suggesting I go in #12192, I think you should close this PR and let me replace `bookie` with a channel semaphore. This would remove being able to limit reservations based on size, but we're not currently using that anyway. 

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-:-KYYuTgQmsNemcBnppUY:b-f6l971)*

**Comment by tamird** [comment]
Works for me.

On Dec 9, 2016 09:11, "Peter Mattis" <notifications@github.com> wrote:

Given the direction you're suggesting I go in #12192
<https://github.com/cockroachdb/cockroach/pull/12192>, I think you should
close this PR and let me replace bookie with a channel semaphore. This
would remove being able to limit reservations based on size, but we're not
currently using that anyway.
------------------------------

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved
discussions, all commit checks successful.
------------------------------

*Comments from Reviewable
<https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-:-KYYuTgQmsNemcBnppUY:b-f6l971>*

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/pull/12201#issuecomment-266022437>,
or mute the thread

**Comment by BramGruneir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/reservation.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201#-KYWYbMki5XAQra4PPcS:-KYZ32rUlRNTQUP1-W7K:b-fedtqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e53ec1c1c78b18ffe6e23417424fed0b9f4533/pkg/storage/reservation.go#L132)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

As the original author of this stuff - you tell me.

`deadReplicas` here is a slice of corrupted replicas, and corrupted replicas are correctly handled in `(*Store).tryGetOrCreateReplica`, which is called from the preemptive snapshot path. So it seems that it is impossible today for this check to catch anything.
</blockquote></details>

So you are correct in that the snapshot will error if a corrupted replica exists.  But it takes a longer path to get there.  This check is much quicker to detect it and reject the reservation.  If we go through tryGet, we end up locking raftmu as well, which isn't the case with the reservation.

But it looks like we're going to go with the removal of the bookie entirely.  So this is kinda moot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12201)*

**Pull request closed without merging**
