### PR TITLE
sqlbase: test that column families are stored in sorted order

### PR DESCRIPTION
**Pull request by rohany**
Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Lets see if tests pass 😰

**Comment by rohany** [comment]
Lets go -- column families are sorted!

**Review by jordanlewis — APPROVED** [review]
:lgtm: let's gooo

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45521#-:-M1RRO_v31E_WXR2YDG2:b7spegg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rohany** [comment]
bors r=jordanlewis

**Pull request merged**
