### PR TITLE
cli: Support execution of system commands on interactive CLI

### PR DESCRIPTION
**Pull request by nak3**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5961)

### CODE REVIEW

**Comment by bdarnell** [comment]
What's the use case for this? I see that both `psql` and `mysql` support this (with the same `\!` syntax), but it seems redundant to me. Why wouldn't you just use `ctrl-z` to suspend the sql shell to get back to your real shell, run your command, and `fg` to get back into sql?

One reason to support this may be for windows, where the `ctrl-z` backgrounding feature doesn't exist. But it can't work on windows if you're hard-coding `/bin/sh`. Even on posix, wouldn't it be better to use the user's chosen shell (from the `$SHELL` environment variable?) instead of always using `/bin/sh`?

**Comment by nak3** [comment]
@bdarnell Can you use `ctrl-z` on interactive shell? I can't use it on my env (Linux/Fedora23).

**Comment by bdarnell** [comment]
Ah, good point. `ctrl-z` works in `psql` and `mysql`, but not in our shell.

**Comment by nak3** [comment]
In terms of Windows support, I updated the PR to stop using `/bin/sh`.

**Comment by knz** [comment]
Please find a separate issue for the lack of support for Ctrl+Z. It might be a bug upstream with the readline library we're using.

**Comment by nak3** [comment]
Agree. I noticed that `ctrl+l` also doesn't work.

**Comment by knz** [comment]
cc @guanqun @chzyer

**Comment by chzyer** [comment]
@knz readline is not supporting `Ctrl+Z` yet, I had created a issue.

**Comment by tamird** [comment]
Since an issue has been filed upstream, can we close this?

**Comment by bdarnell** [comment]
There's an upstream issue for `ctrl-z` support, but we may still want to support `\!` given the precedent in `psql` and `mysql` (and for windows, when we can build the `cockroach` tool there). I think it seems like a reasonable addition, although we'd probably want to stream the command output to the terminal instead of buffering the whole thing with `CombinedOutput`.

**Comment by knz** [comment]
@nak3 see the commend by @bdarnell. Could you address the point about buffering?

Also, if you are interested to work on this part of the product, there's one related feature: the ability to pipe the output of an external command into the current SQL shell.  This may (or may not) be a relatively straightforward extension of the code you have prepared already. If you are interested to extend your code in this direction then this PR would become very exciting to us.

**Comment by nak3** [comment]
@bdarnell @knz Sure! I will try. Thank you for your suggestion.

**Comment by nak3** [comment]
This modified patch has contains:

- Support execution of system command. 
- Support execution of command pipepline. 
- Support pipe the output of an external command into the current SQL by "`-`". 

__Example:__
~~~
root@:26257> \! cat /tmp/sql.txt
select * from t;
root@:26257> \! cat /tmp/sql.txt | -
+----+
| id |
+----+
|  2 |
|  3 |
+----+
~~~

**Comment by knz** [comment]
Ok this is going in the right direction.
First I recommend against handling a pipeline in your own code. I think that the string passed after \! should be passed as-is to the user's shell as a single argument, i.e. `exec.Command("/bin/sh", "-c", command)`. If the user uses pipes in there, let the shell handle it.

Then regarding piping the output in the current shell. For this I recommend against detecting "| -" at the end of the command, as this is taking over the role of the shell (and making the logic overall more complex). Instead I recommend introducing another top-level command prefix `\|` next to `\!`. Then use the same shell invocation code for both prefixes, with `\|` also reading SQL code from the command's standard output. Does this make sense?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-:-KFZKyUS7FoscOTeHxpQ:1318694130)*

**Comment by bdarnell** [comment]
Do other databases have anything like `\|`? I don't see it in the docs. For the simple case of reading a file, mysql has `\. file.sql` (or `source file.sql`), and psql has `\i file.sql`). I'm not sure if running a command and executing its output is common enough to deserve dedicated support.

**Comment by knz** [comment]
From my own experience as a SQL client user, I have been annoyed by the lack of this feature many times. Although I seem to recall either mysql or psql allow \source | command by detecting the pipe at the beginning as a suggestion to use popen().

**Comment by nak3** [comment]
Thank you. I updated them. This modified patch support the syscommands as:

* Support execution of system command by `\!`.
* Support pipe the output of an external command into the current SQL by `\|`.

__NOTE__: Commands are run by the shell which is in `$PATH`(Linux) or `%COMP%`(Windows).

**Comment by knz** [comment]
Looks good! Only minor adjustements needed.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 67 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFf8gzkrkXLAPvgeEY4:-KFf8gzkrkXLAPvgeEY5:-678446790) ([raw file](https://github.com/cockroachdb/cockroach/blob/453dac1103d094d3b6da2531fb9e55978f30cd27/cli/sql.go#L67)):*
\! to run an external command and print its results on standard output
\| to run an external command and run its output as SQL statements

---

*[cli/sql.go, line 135 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFf94B_PrKPkDF3pVrP:-KFf94B_PrKPkDF3pVrQ:1711809982) ([raw file](https://github.com/cockroachdb/cockroach/blob/453dac1103d094d3b6da2531fb9e55978f30cd27/cli/sql.go#L135)):*
Please move this part of the logic to read SHELL/COMSPEC to the package util/envutils. We want to contain all calls to os.Getenv there. You could make a command there which returns the prefix to run commands. for example an array of strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-:-KFf9Ia01pSeEQADxoXF:1006827882)*

**Comment by nak3** [comment]
Thank you again. I should have run `make check`. I updated them. And I added `os/exec:Run` to `errcheck -ignore`.

**Comment by knz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[Makefile, line 216 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBMQeSl9iI39YCKna:-KFiBMQfIPY88ZB8nlmf:1858954207) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/Makefile#L216)):*
Can you explain why this is needed?

---

*[cli/sql.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBQLSnFYUskqbjCbh:-KFiBQLSnFYUskqbjCbi:-1993424179) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/cli/sql.go#L137)):*
I think this is not going to work on Windows. I think that the function GetShellEnv should return an array of strings, not just the name of the shell. So on Windows it returns {comspec, "/C"} and unix {shell, "-c"}. Unless COMSPEC usually accepts argument "-c"?

---

*[util/envutil/env.go, line 75 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBhuDmP-n8FxySQRN:-KFiBhuDmP-n8FxySQRO:1440281956) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/util/envutil/env.go#L75)):*
This function should return xxx, error.

---

*[util/envutil/env.go, line 77 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBl3qsJrw2cnnC_B_:-KFiBl3qsJrw2cnnC_Ba:-869322120) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/util/envutil/env.go#L77)):*
return shell, nil

---

*[util/envutil/env.go, line 79 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBmMgdtSsMo8i7md4:-KFiBmMgdtSsMo8i7md5:-869322120) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/util/envutil/env.go#L79)):*
return shell, nil

---

*[util/envutil/env.go, line 83 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBnQN9wC0MPvUNhzs:-KFiBnQN9wC0MPvUNhzt:543209963) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/util/envutil/env.go#L83)):*
return nil, errors.New("shell not found, check SHELL (unix) or COMSPEC (Windows)")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[Makefile, line 216 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBMQeSl9iI39YCKna:-KFiVqb2JG1V8VQOkOHv:-1760502153) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/Makefile#L216)):*
I reverted it and used `log.V(2)` for the error handling of `os/exec:Run()`.

The reason was that `os/exec:Run()` returns "exit status xxx" message when the command failed. So, if I handled the error as below,

~~~
        if err := cmd.Run(); err != nil {
                fmt.Printf("%s\n", err)
        }
~~~

it returns following output.

~~~
root@127.0.0.1:26257> \! dummycommand
/bin/bash: dummycommand: command not found
exit status 127
root@127.0.0.1:26257> \! ls dummy-file
ls: cannot access dummy-file: No such file or directory
exit status 2
~~~

I thought the message `exit status xxx` is redundant and it's better to show same error as shell (without `exit status xxx`). 

Now I avoid the redundant message by `log.V(2)` and reverted the Makefile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiBQLSnFYUskqbjCbh:-KFiWbh625raK1hjzcZ3:161840700) ([raw file](https://github.com/cockroachdb/cockroach/blob/61ecab6fe713f2aababc61cbcc30d27505e7839f/cli/sql.go#L137)):*
You are right. I'm sorry, it was my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by knz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[cli/sql.go, line 145 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiWkBZttGJLoS1-xnS:-KFiWkBZttGJLoS1-xnT:-2083776146) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L145)):*
Ah but then if the command fails it is likely that its output cannot be used. So I would actually return the error from the command, that is:
```
if err := cmd.Run(); err != nil {
    return nil, fmt.Errorf("error in external command: %s", err)
}
```

---

*[cli/sql.go, line 162 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiX5oOY1Bc4hMW5ruw:-KFiX5oOY1Bc4hMW5rux:1032314887) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L162)):*
Here I would recommend propagating the error further to the caller function.

---

*[cli/sql.go, line 180 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiXDOxc6gGftof9Wo3:-KFiXDOyYasshRVQZyEk:-203192602) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L180)):*
Same above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 145 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiWkBZttGJLoS1-xnS:-KFiu1MUmGfthl8q7Rug:2080513712) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L145)):*
Yes, sounds good. Thank you. I updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 162 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiX5oOY1Bc4hMW5ruw:-KFiuLxoBWcpAhu2w6Ku:-560131576) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L162)):*
Alright. I updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 162 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiX5oOY1Bc4hMW5ruw:-KFiunEVbGIgl1wJXZKo:-2014545602) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L162)):*
(I hope I didn't misunderstand your suggestion.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by knz** [comment]
Reviewed 1 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[cli/sql.go, line 162 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiX5oOY1Bc4hMW5ruw:-KFj7-BcndvW7Nqho-JX:2117664626) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L162)):*
Yes that's what I meant. Although I would drop the conditional on log.V and always print the error if one occurs.

---

*[cli/sql.go, line 152 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFj7QDWLJWhHmoQJKfG:-KFj7QDWLJWhHmoQJKfH:1112875301) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/cli/sql.go#L152)):*
I think command := line[2:] may be sufficient. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by knz** [comment]
This looks good overall. I think it may be time to ask one of my colleagues for a 2nd review.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-:-KFj7YD15oEOhJ6ZjaWz:-1333270815)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[util/envutil/env.go, line 75 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjeJQ1ttrEWpcMYT1X:-KFjeJQ1ttrEWpcMYT1Y:1470392620) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L75)):*
It doesn't return the path to the system shell, it returns a prefix of a command line (to which the caller must append the real command). I think it would be better if this function returned a complete command, instead of asking the caller to append to its result: `func GetShellCommand(cmd string) ([]string, error)`

---

*[util/envutil/env.go, line 77 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjfGmdGW8jZjzPtqK6:-KFjfGmdGW8jZjzPtqK7:-2070637447) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L77)):*
We should check `runtime.GOOS` first: the `SHELL` variable shouldn't be special on windows.

---

*[util/envutil/env.go, line 83 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjf6yYVsBSTFr9QWME:-KFjf6yZDTUSVgJnt8Rq:2114276488) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L83)):*
It would be nice if this defaulted to `/bin/sh` on non-windows platforms when no `SHELL` variable is present (and `command.com` or whatever its successor is on windows).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-:-KFjgLPf5e9fyuoKJUZd:676834233)*

**Comment by nak3** [comment]
*[util/envutil/env.go, line 77 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjfGmdGW8jZjzPtqK6:-KFl8yUcZXfoxQUawI_H:-446375288) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L77)):*
You mean

~~~
        if shell := os.Getenv("SHELL"); runtime.GOOS != "windows" && len(shell) > 0 {
~~~

,right? I was considered about it, and I thought it will failed to run on  (cygwin)[https://www.cygwin.com/). But OK, I can second you, since cygwin users are not so many.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 152 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFj7QDWLJWhHmoQJKfG:-KFmV_mAmgaKifcbBn87:-1357365553) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/cli/sql.go#L152)):*
I agree. It is smarter. I updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[cli/sql.go, line 162 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFiX5oOY1Bc4hMW5ruw:-KFmVtex00LSn_1Z51jH:1757210042) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f06501e00f02260c788240f700f9970e8cdcb78/cli/sql.go#L162)):*
I see. I dropped `log.V`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[util/envutil/env.go, line 83 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjf6yYVsBSTFr9QWME:-KFmW79pFJvj6tBanoRb:257709932) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L83)):*
I agree. I updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by nak3** [comment]
*[util/envutil/env.go, line 75 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961#-KFjeJQ1ttrEWpcMYT1X:-KFmWImakp2jAhh7u4ai:793344042) ([raw file](https://github.com/cockroachdb/cockroach/blob/cad4f344d0d502b156aa41d9933433fff09bf7e3/util/envutil/env.go#L75)):*
I understand. I updated. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by chzyer** [comment]
@knz The supporting of `Ctrl+Z` is done, all you need is pulling the latest commit :)

**Comment by knz** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5961)*

**Comment by knz** [comment]
LGTM too. Thanks @nak3 !

**Comment by nak3** [comment]
Thank you @knz and @bdarnell . I am very grateful for your review.

**Comment by knz** [comment]
@jseldess for the docs I suggest the following example:

```sql
> create table t (x int);
> \| for ((i=0;i<10;++i)); do echo "insert into t values ($i);"; done
INSERT 1
> select * from t;
+---+
| x |
+---+
| 0 |
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
| 6 |
| 7 |
| 8 |
| 9 |
+---+
```

And reading a CSV file:

```sql
> \| cat test.csv
12, 13, 14
10, 20, 30
> create table f (x int, y int, z int);
> \| IFS=","; while read a b c; do echo "insert into f values ($a, $b, $c);"; done <t.csv;
INSERT 1
> select * from f;
+----+----+----+
| x  | y  | z  |
+----+----+----+
| 12 | 13 | 14 |
| 10 | 20 | 30 |
+----+----+----+
```

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/270

**Pull request merged**
