### PR TITLE
roachtest: make roachtest recognize 21.1

### LINKED ISSUE #56407: roachtest: django failed
[(roachtest).django failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/django/run_1
	django.go:173,django.go:214,test_runner.go:755: No django blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/django](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/django)
Related:
- #56187 roachtest: django failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Adjango.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56408: roachtest: gopg failed
[(roachtest).gopg failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/gopg/run_1
	gopg.go:99,gopg.go:162,test_runner.go:755: No gopg blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/gopg](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/gopg)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Agopg.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56409: roachtest: hibernate failed
[(roachtest).hibernate failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/hibernate/run_1
	hibernate.go:109,hibernate.go:180,test_runner.go:755: No hibernate blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/hibernate](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/hibernate)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ahibernate.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56413: roachtest: lib/pq failed
[(roachtest).lib/pq failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/lib/pq/run_1
	libpq.go:86,test_runner.go:755: No lib/pq blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/lib/pq](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/lib/pq)
Related:
- #54338 roachtest: lib/pq failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-release-20.1](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-release-20.1)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Alib%2Fpq.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56414: roachtest: pgx failed
[(roachtest).pgx failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/pgx/run_1
	pgx.go:80,pgx.go:131,test_runner.go:755: No pgx blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/pgx](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/pgx)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Apgx.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56415: roachtest: psycopg failed
[(roachtest).psycopg failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/psycopg/run_1
	psycopg.go:96,psycopg.go:135,test_runner.go:755: No psycopg blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/psycopg](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/psycopg)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Apsycopg.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56417: roachtest: tpchvec/disk failed
[(roachtest).tpchvec/disk failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/disk/run_1
	tpchvec.go:667,tpchvec.go:695,test_runner.go:755: unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		(1) attached stack trace
		  -- stack trace:
		  | main.toCRDBVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:49
		  | main.runTPCHVec
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:665
		  | main.registerTPCHVec.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:695
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		Error types: (1) *withstack.withStack (2) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/disk](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/tpchvec/disk)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fdisk.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56418: roachtest: sqlalchemy failed
[(roachtest).sqlalchemy failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlalchemy/run_1
	sqlalchemy.go:146,sqlalchemy.go:38,test_runner.go:755: No sqlalchemy blocklist defined for cockroach version v21.1.0-alpha.00000000-7-g61c96aaca6

```

<details><summary>More</summary><p>

Artifacts: [/sqlalchemy](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/sqlalchemy)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlalchemy.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56420: roachtest: tpchvec/perf_no_stats failed
[(roachtest).tpchvec/perf_no_stats failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/perf_no_stats/run_1
	tpchvec.go:667,tpchvec.go:727,test_runner.go:755: unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		(1) attached stack trace
		  -- stack trace:
		  | main.toCRDBVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:49
		  | main.runTPCHVec
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:665
		  | main.registerTPCHVec.func5
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:727
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		Error types: (1) *withstack.withStack (2) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/perf_no_stats](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/tpchvec/perf_no_stats)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fperf_no_stats.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56421: roachtest: tpchvec/smallbatchsize failed
[(roachtest).tpchvec/smallbatchsize failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/smallbatchsize/run_1
	tpchvec.go:667,tpchvec.go:707,test_runner.go:755: unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		(1) attached stack trace
		  -- stack trace:
		  | main.toCRDBVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:49
		  | main.runTPCHVec
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:665
		  | main.registerTPCHVec.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:707
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		Error types: (1) *withstack.withStack (2) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/smallbatchsize](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/tpchvec/smallbatchsize)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fsmallbatchsize.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #56422: roachtest: tpchvec/smithcmp failed
[(roachtest).tpchvec/smithcmp failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=buildLog) on [master@61c96aaca632dfba5154d55d82c5af0732053b72](https://github.com/cockroachdb/cockroach/commits/61c96aaca632dfba5154d55d82c5af0732053b72):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/smithcmp/run_1
	tpchvec.go:667,tpchvec.go:717,test_runner.go:755: unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		(1) attached stack trace
		  -- stack trace:
		  | main.toCRDBVersion
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:49
		  | main.runTPCHVec
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:665
		  | main.registerTPCHVec.func4
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpchvec.go:717
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:755
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) unrecognized version: v21.1.0-alpha.00000000-7-g61c96aaca6
		Error types: (1) *withstack.withStack (2) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec/smithcmp](https://teamcity.cockroachdb.com/viewLog.html?buildId=2424980&tab=artifacts#/tpchvec/smithcmp)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec%2Fsmithcmp.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by thoszhang**
Fixes #56407
Fixes #56408
Fixes #56409
Fixes #56413
Fixes #56414
Fixes #56415
Fixes #56418
Fixes #56417
Fixes #56420
Fixes #56421
Fixes #56422

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56424#-:-MLZ_E_z6J7qd9qeTz8l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Review by yuzefovich — COMMENTED** [review]
bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56424#-:-MLZ_ICVBUwjPMfEyTmL:b-ewwdc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Comment by lucy-zhang** [comment]
```
------- Stdout: -------
=== RUN   TestLogic/5node-spec-planning/distsql_merge_join/ParentChildDifferentSize
--- done: testdata/logic_test/distsql_merge_join with config 5node-spec-planning: 67 tests, 0 failures
--- total progress: 123425 statements/queries
SIGQUIT: quit
PC=0x47bb71 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x7b52008, 0x80, 0x0, 0x0, 0x7ffc00000000, 0x425212, 0xc02801e148, 0xc000000001, 0x7ffcc39c57e8, 0x42532f, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x7b52008, 0xc000000000, 0xffffffffffffffff)
	*** Test killed: ran too long (31m0s).
FAIL	github.com/cockroachdb/cockroach/pkg/sql/logictest	1872.003s
```

This might be #56348 but in any case it's unrelated.

**Comment by lucy-zhang** [comment]
bors r=yuzefovich

**Pull request merged**
