### PR TITLE
importccl: add skip_foreign_keys option

### PR DESCRIPTION
**Pull request by dt**
This allows skipping foreign key definitions during IMPORT.

It also plumbs through to whether or not foreign keys are supported by
a given format and thus if resolution should even be allowed -- and then
potentially fail with a message about missing tables -- or if it should
be immediately rejected with a more helpful error.

Release note (sql change): allow skipping foreign keys in IMPORTs that support them.

### CODE REVIEW

**Review by madelynnblue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27606)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZFB3O6wMfkh4eea5K:-LHZFB3O6wMfkh4eea5L:b-fwhmaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L175)):*
> ```Go
> 			}
> 			if fks.skip {
> 				create.Defs = append(create.Defs[:i], create.Defs[i+1:]...)
> ```

This mutates create.Defs while iterating over it. I don't think that is safe. https://play.golang.org/ Should there be a test that would catch this? I think the tests were passing because this def was always the last element in the list and so the for loop didn't have another iteration.
___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZTpbPCXPcVk0nPmeh:-LHZTpbQ2_zYembhZYAO:b-iwp29g) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L1019)):*
> ```Go
> 	b := txn.NewBatch()
> 	for _, tbl := range details.Tables {
> 		if tbl.Desc == nil {
> ```

When can this happen?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27606)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZFB3O6wMfkh4eea5K:-LH_0rvu864nWVMGYBSX:b-wtms3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L175)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This mutates create.Defs while iterating over it. I don't think that is safe. https://play.golang.org/ Should there be a test that would catch this? I think the tests were passing because this def was always the last element in the list and so the for loop didn't have another iteration.
</blockquote></details>

i think it is the opposite; `weather_city_fkey` *isn't* the last def. I think to make it panic i'd need to add a second FK to the weather table.
___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZTpbPCXPcVk0nPmeh:-LH_2Y8F4vswxmgWyF-8:b-bvsroy) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L1019)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

When can this happen?
</blockquote></details>

There's a longer comment on the proto, but TLDR is when filtering to a subset of tables, we fill the map keys with their names, but nil values indicating they should be parsed during sampling.

**Review by madelynnblue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27606)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZTpbPCXPcVk0nPmeh:-LH_7j1b5bETvU9YlDVe:b-s36m69) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L1019)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

There's a longer comment on the proto, but TLDR is when filtering to a subset of tables, we fill the map keys with their names, but nil values indicating they should be parsed during sampling.
</blockquote></details>

Were we missing a test that would have found this or is it only possible now with fk skipping?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27606)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 1019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27606#-LHZTpbPCXPcVk0nPmeh:-LHcmKQJ64Aoq5wWSwb7:b-6vp832) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a6326cd553faf22e3bf66893377559683149c2/pkg/ccl/importccl/import_stmt.go#L1019)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Were we missing a test that would have found this or is it only possible now with fk skipping?
</blockquote></details>

unrelated to FKs -- I can remove it from this change. to hit it, I think you'd need fail a job that was doing schema-during-sampling, before sampling finished. i think I hit it at some point when I was testing but nothing hits it right now.

**Review by madelynnblue — APPROVED** [review]

**Pull request merged**
