### PR TITLE
libroach/engine: plumb support for SingleDelete operation

### PR DESCRIPTION
**Pull request by nvb**
Informs #8979.

This commit doesn't actually use the operation yet, but any experiments
will require this plumbing, so it made sense to pull it out and properly
test it.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33440)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/batch.cc, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwkw5CG5cpr0e5D1w:-LVEwkw67n-B-W0Gw4Jh:b-yu817w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/c-deps/libroach/batch.cc#L89)):*
> ```cpp
>       break;
>     }
>     case rocksdb::kSingleDeleteRecord:
> ```

Can you give more detail on the outcome here? Does this mean that after a SingleDelete, the "deleted" value remains visible? I see that the code is simple in this case, but is this really sane?
___
*[c-deps/libroach/batch.cc, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwDPf5VIFgmaRpFA2:-LVEwDPf5VIFgmaRpFA3:bd6eims) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/c-deps/libroach/batch.cc#L91)):*
> ```cpp
>     case rocksdb::kSingleDeleteRecord:
>       // These semantics don't quite mirror SingleDelete's expected
>       // implementation, but they don't violate the its contract from
> ```

the its
___
*[pkg/storage/engine/rocksdb.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwd7nAkc4uisd7i1Y:-LVEwd7nAkc4uisd7i1Z:b-l6emhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/pkg/storage/engine/rocksdb.go#L796)):*
> ```Go
> }
> 
> // Clear removes the most recent item from the db with the given key.
> ```

SingleClear

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33440)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/batch.cc, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwkw5CG5cpr0e5D1w:-LVFP26gERaDFhUyf0LA:b-z9s07) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/c-deps/libroach/batch.cc#L89)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you give more detail on the outcome here? Does this mean that after a SingleDelete, the "deleted" value remains visible? I see that the code is simple in this case, but is this really sane?
</blockquote></details>

Done. It actually means that the SingleDelete is treated like a standard Delete operation (we're in C++, so the fallthrough is implicit).
___
*[c-deps/libroach/batch.cc, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwDPf5VIFgmaRpFA2:-LVFP_kc4v2O4lnAjMYq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/c-deps/libroach/batch.cc#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

the its
</blockquote></details>

Done.
___
*[pkg/storage/engine/rocksdb.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwd7nAkc4uisd7i1Y:-LVFPgbe8FyaP_0lM2Gd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/pkg/storage/engine/rocksdb.go#L796)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

SingleClear
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-:-LVFcvVX9bBR5xu9ddt6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[c-deps/libroach/batch.cc, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVEwkw5CG5cpr0e5D1w:-LVFcnpQ2tr72D5NGYUV:b-hhz2qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6492023796d2273d49f056a8104a51d7877549e2/c-deps/libroach/batch.cc#L89)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done. It actually means that the SingleDelete is treated like a standard Delete operation (we're in C++, so the fallthrough is implicit).
</blockquote></details>

Ah, makes sense, thanks.
___
*[c-deps/libroach/batch.cc, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVFclO27Ic-fHzD0c1m:-LVFclO34NElc11SVckd:b-7j8xgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfc001a78758448e5751af40536f0a4a6082f702/c-deps/libroach/batch.cc#L92)):*
> ```cpp
>       // Treating a SingleDelete operation as a standard Delete doesn't
>       // quite mirror SingleDelete's expected implementation, but it
>       // don't violate the operation's contract:
> ```

nit: doesn't ;-)

**Review by petermattis — APPROVED** [review]
:lgtm:

I really dislike how we translate from `Clear` -> `Delete` when going from CRDB to RocksDB. Peer ack for whoever fixes this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-:-LVFh0PmAJqJ6p0OFl1X:bn9mc4u)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-:-LVFghT1923HrijLmslC:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[c-deps/libroach/batch.cc, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33440#-LVFclO27Ic-fHzD0c1m:-LVFgmw58FEf324cYbON:b5ffasy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfc001a78758448e5751af40536f0a4a6082f702/c-deps/libroach/batch.cc#L92)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: doesn't ;-)
</blockquote></details>

lol, that don't sound wrong to me... done.

**Comment by nvanbenschoten** [comment]
> I really dislike how we translate from Clear -> Delete when going from CRDB to RocksDB.

I was talking to @benesch about this today. I guess the idea is that in CRDB code "delete" implies MVCC-awareness (i.e. leaving tombstones) while "clear" doesn't. I don't really like it either so if you're on board I'd happily switch it over. Just give the 👍.

**Comment by petermattis** [comment]
> I was talking to @benesch about this today. I guess the idea is that in CRDB code "delete" implies MVCC-awareness (i.e. leaving tombstones) while "clear" doesn't. I don't really like it either so if you're on board I'd happily switch it over. Just give the 👍.

The current situation is very confusing. `DeleteRange` in CRDB should correspond to `DeleteRange` in RocksDB. If we need a term for laying down tombstones on a range, it shouldn't be `Delete`.

**Pull request merged**
