### PR TITLE
opt: Fall back on existing planner for unsupported statements.

### PR DESCRIPTION
**Pull request by andy-kimball**
The new optimizer supports only read-only query statements. For other
statements, fall back on the existing planner.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

[nit] Maybe we want to update the comment for OptimizerOn https://github.com/cockroachdb/cockroach/blob/4b78b77dbac64311d30f7b3e54d8ec925156c822/pkg/sql/sessiondata/session_data.go#L138

It might be useful to have an `OptimizerAlways` for testing, so we can be sure that we are not falling back.

**Comment by andy-kimball** [comment]
I updated the comment to this: `// OptimizerOn means that we use the optimizer for all supported statements.`. We can add another mode, but I'm worried that it would be largely untested and likely to crash the server. Is that OK?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22616#-:-L5BMg8aWHAa5X16uDuE:b-5winay)*

**Comment by andy-kimball** [comment]
Actually, I see that DistSQL has this same thing. I just went ahead and added it. PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22616#-:-L5BQN2dTI-CgG-ckFIE:beh0o1u)*

**Comment by RaduBerinde** [comment]
LGTM

**Pull request merged**
