### PR TITLE
backupccl: deflake tests with multiple schema changes in the same txn

### PR DESCRIPTION
**Pull request by mgartner**
Informs #122353
Informs #122595

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125011)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @stevendanna)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZ3NtkCvkNYAdfI_aJ:-NzZ3NtkCvkNYAdfI_aK:b-v8jb9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c66a0fe920d81db0c45cace0b0a5c14cf2e81d0/pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures#L2)):*
> ```
> # Test backing up and restoring a database with PL/pgSQL procedures.
> skip issue-num=122353
> ```

Should we unskip all these files on master?
___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZ3mt60bhaUV2hn5OB:-NzZ3mt60bhaUV2hn5OC:blwi9wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c66a0fe920d81db0c45cace0b0a5c14cf2e81d0/pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions#L189)):*
> ```
> ----
> 
> exec-sql
> ```

nit: should we be using `cluster=s1` here and in the next several stmts?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125011)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZ3NtkCvkNYAdfI_aJ:-NzZLYnp5HvzGJQPyUPu:basee6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c66a0fe920d81db0c45cace0b0a5c14cf2e81d0/pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures#L2)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we unskip all these files on master?
</blockquote></details>

I suppose so.
___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZ3mt60bhaUV2hn5OB:-NzZLVMECCLUyBM1C4uV:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c66a0fe920d81db0c45cace0b0a5c14cf2e81d0/pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions#L189)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we be using `cluster=s1` here and in the next several stmts?
</blockquote></details>

done

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-:-NzZXMMU8kTynUOL7YVd:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @stevendanna)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZX24AEeSyI9b2Mevy:-NzZX24AEeSyI9b2Mevz:b-4w9q9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c96f1facb6e90b68b5ed7628a5814866250f704/pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions#L2)):*
> ```
> # Test backing up and restoring a database with user defined functions.
> skip issue-num=122353
> ```

nit: one more :)
___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-types` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZXHA--4r4GyfDTr4z:-NzZXHA--4r4GyfDTr5-:bc8u1r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c96f1facb6e90b68b5ed7628a5814866250f704/pkg/ccl/backupccl/testdata/backup-restore/user-defined-types#L49)):*
> ```
> CREATE TABLE d2.t2 (x d2.farewell[]);
> ----
> ```

nit: `exec-sql` missing.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125011)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZX24AEeSyI9b2Mevy:-NzZw3hNDpY5FNW54x-c:bdu4sd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c96f1facb6e90b68b5ed7628a5814866250f704/pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions#L2)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: one more :)
</blockquote></details>

Thanks for catching! Done.
___
*[`pkg/ccl/backupccl/testdata/backup-restore/user-defined-types` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125011#-NzZXHA--4r4GyfDTr4z:-NzZwEji6Eaa2ihUjK-k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c96f1facb6e90b68b5ed7628a5814866250f704/pkg/ccl/backupccl/testdata/backup-restore/user-defined-types#L49)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `exec-sql` missing.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Looks like we haven't had a failure since this PR went in, so let's backport to 24.1

blathers backport release-24.1

**Pull request merged**
