### PR TITLE
sql: detect more ambiguity cases in ORDER BY.

### LINKED ISSUE #12239: sql: ORDER BY does not detect ambiguous renders
Repro with:

```
SELECT * FROM kv AS a JOIN kv AS b USING(k) ORDER BY v
```

The ORDER BY should detect that `v` is ambiguous in the render list but currently it picks the first one.

### PR DESCRIPTION
**Pull request by knz**
Fixes #12239.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12255)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Comment by knz** [comment]
My original approach at fixing this wasn't entirely right. In the process of finding why, I found some opportunities to clean up the code so I added some intermediate commits to do just that. Then I fixed the bug for real. PTAL!

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/group.go, line 206 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYocTH7cVdIaf1poD2L:-KYocTH7cVdIaf1poD2M:b-bw1ie9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/group.go#L206)):*
> ```Go
> 		// aggregate function so the merge loop cannot encounter an
> 		// equivalent expression in the aggregation list.
> 		_ = s.addOrMergeRenders(cols, exprs, false)
> ```

We could just do a loop and call `addRenderColumn` directly and avoid this explanation..

---

*[pkg/sql/select.go, line 545 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYobVrrvHip67OH1mw6:-KYobVrszZCvEBhfYFYD:bljuh7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f499acd05d11bb1848b9a35d07645c0db4c1dd73/pkg/sql/select.go#L545)):*
> ```Go
> // expand the "*" into a list of columns. A ResultColumns and Expr
> // pair is returned for each column.
> func checkRenderStar(
> ```

The semantics kind of weird with the new flag.. I would split it up into `isRenderStar` and `expandRenderStar`. If not, at least add a comment explaining the flag.

---

*[pkg/sql/select.go, line 508 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYodgcNsS8T9xAwnI-c:-KYodgcNsS8T9xAwnI-d:bfn7b06) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/select.go#L508)):*
> ```Go
> 		}
> 		s.isStar = s.isStar || hasStar
> 		_ = s.addOrMergeRenders(cols, exprs, false)
> ```

maybe remove the `_ =`

---

*[pkg/sql/targets.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYodwO3QUWjmwK7MQLw:-KYodwO3QUWjmwK7MQLx:b-g776r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/targets.go#L67)):*
> ```Go
> 	cols ResultColumns, exprs []parser.TypedExpr, reuseExistingRender bool,
> ) (colIdxs []int) {
> 	for i := range cols {
> ```

minor optimization: `colIdxs := make([]int, len(cols))` and just set `colIdxs[i]`

---

*[pkg/sql/window.go, line 195 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYocyRdz8kjyGr-PFB-:-KYocyRdz8kjyGr-PFB0:b-ytz5g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/window.go#L195)):*
> ```Go
> 		// Validate ORDER BY clause.
> 		for _, orderBy := range windowDef.OrderBy {
> 			// FIXME: does ORDER BY allow star expansion?
> ```

Looks like `pg` allows it but only when it's qualified with the table name `a.*`. Same for `GROUP BY` (though for some reason you can't use a column of `a` in the render expressions if it's mentioned implicitly via `*).  I don't feel strongly of whether we want to support this kind of thing, it's pretty strange.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-:-KYoetMYZFENMBO7Gw7n:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

---

Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/group.go, line 206 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYocTH7cVdIaf1poD2L:-KYsqjZpzN_meFGqfGVu:b-590h8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/group.go#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We could just do a loop and call `addRenderColumn` directly and avoid this explanation..
</blockquote></details>

Yes that was my first idea however notice there is a nicety here: although the additional group by columns won't be merged with the aggregate columns (which would be a bug otherwise), we do get the advantage to merge the group by columns among themselves! So that e.g. `group by x, x` only produces one column.

---

*[pkg/sql/select.go, line 545 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYobVrrvHip67OH1mw6:-KYsu0d-gyV9UrvNptmX:beosusb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f499acd05d11bb1848b9a35d07645c0db4c1dd73/pkg/sql/select.go#L545)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The semantics kind of weird with the new flag.. I would split it up into `isRenderStar` and `expandRenderStar`. If not, at least add a comment explaining the flag.
</blockquote></details>

Since there is just one user of this method I think splitting the code is not that advantageous. I did add a comment though.

---

*[pkg/sql/select.go, line 508 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYodgcNsS8T9xAwnI-c:-KYsqz0EssxPSORMemhw:bhda7c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/select.go#L508)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

maybe remove the `_ =`
</blockquote></details>

I think that would be a lint error.

---

*[pkg/sql/targets.go, line 67 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYodwO3QUWjmwK7MQLw:-KYsuEOIYmfU_lS9GQwt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/targets.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

minor optimization: `colIdxs := make([]int, len(cols))` and just set `colIdxs[i]`
</blockquote></details>

Done.

---

*[pkg/sql/window.go, line 195 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYocyRdz8kjyGr-PFB-:-KYt0hS68X-P7QvkwsaL:b-qac0kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/window.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Looks like `pg` allows it but only when it's qualified with the table name `a.*`. Same for `GROUP BY` (though for some reason you can't use a column of `a` in the render expressions if it's mentioned implicitly via `*).  I don't feel strongly of whether we want to support this kind of thing, it's pretty strange.
</blockquote></details>

Thanks, I enabled it and added the corresponding tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-:-KYt0lhmkkSR7SEtyYtW:b-814cj3)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/group.go, line 206 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYocTH7cVdIaf1poD2L:-KYt5znDpcP8FfwbyYsc:brz31v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/group.go#L206)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes that was my first idea however notice there is a nicety here: although the additional group by columns won't be merged with the aggregate columns (which would be a bug otherwise), we do get the advantage to merge the group by columns among themselves! So that e.g. `group by x, x` only produces one column.
</blockquote></details>

Ah, I see, did not realize that (maybe mention that in the comment).

---

*[pkg/sql/select.go, line 508 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-KYodgcNsS8T9xAwnI-c:-KYt6689FemOzICHRUBp:b5yuoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efe2d3e10787419e6b2add9e3336249aec58ac9/pkg/sql/select.go#L508)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think that would be a lint error.
</blockquote></details>

I thought the linter complains only for errors. Anyway, it's fine either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12255#-:-KYt6j_B1t8i_o-HF4--:bnfp4nl)*

**Pull request merged**
