### PR TITLE
metric: Ensure correct metrics registry usage

### PR DESCRIPTION
**Pull request by miretskiy**
Every exported metric must be registered with metrics registry.

It is very easy to make silly mistakes when doing so (for example, by having an unexported field in the struct, or forgetting to implement `metric.Struct` interface).

See #107384 where the newly introduced struct
`DistsenderRangeFeedMetrics` did not implement `metric.Struct` interface.

In addition, the recently deprecated `chart_catalog_test.go` removed the only remaining sanity check.  Thus, mistakes in metrics registration are easy to make and very easy to remain undetected.

This PR ensures that registered metrics are sane.  The sanity checking happens only when running under test, and if any violations are detected, the process panics.

Epic: None
Issue: None

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @rhu713)

___
*[`pkg/sql/mem_metrics.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108196#-NbF6l-oAClCjOW6QAEp:-NbF6l-oAClCjOW6QAEq:b-9ny5ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/c19c4d8158e75a103d0d0dea8f8c1405c82ea6c3/pkg/sql/mem_metrics.go#L27)):*
> ```Go
> 
> // MetricStruct implements the metrics.Struct interface.
> func (BaseMemoryMetrics) MetricStruct() {}
> ```

is it worth adding the interface type check line? 
___
*[`pkg/util/metric/registry.go` line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108196#-NbFVrRJ8cn6o5LmUjKy:-NbFVrRJ8cn6o5LmUjKz:b-huxvqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e54a4ec581ed6d5801a9562d481a6124273e6b7/pkg/util/metric/registry.go#L220)):*
> ```Go
> }
> 
> var panicHandler = log.Errorf
> ```

I think the intention is for this to be `log.Fatalf` to match the handler reset function below, and to fail when run during tests. Otherwise, this doesn't fail fast. My understanding is that the test flag just skips the `panicHandler` invocation altogether, so there's no need for it to be modified for non-test builds.

**Comment by miretskiy** [comment]
@dhartunian -- okay.. I got clean CI; I decided to keep log.Fatal as the handler (instead of just calling panic).  I think log.Fatal produces better stack, but I can't use it in tests because it calls os.exit -- and I need to catch panics.
I think it's ready for another look.

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for this!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108196#-:-Nb_tNXRA1169RkCTSEH:bb82xvo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @rhu713)

**Pull request merged**
