### PR TITLE
builtins: implement regr_intercept, regr_r2, and regr_slope aggregation functions

### PR DESCRIPTION
**Pull request by mneverov**
builtins: implement regr_intercept, regr_r2, and regr_slope aggregation functions

See #41274

Release note (sql change): implement regr_intercept, regr_r2, and regr_slope aggregation functions.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for working on this! The code looks good to me, but I've just realized that Postgres returns a float when both arguments are decimals:
```
yuzefovich=# select pg_typeof(regr_intercept(dy, dx)) from statistics_agg_test;
    pg_typeof     
------------------
 double precision
```
That appears to be the case for all statistics functions. Since we aim for PG compatibility, I think we should refactor the recent additions of aggregate builtins and return floats too. That refactor could be the first commit in this PR with the new additions commit not having separate decimal-regression variants.

Apologies for not checking that earlier and for encouraging you to do what-now-appears-to-be-redundant work to support decimal return value.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-:-MLPybf578t8NQnBDEqg:b-1rjjb8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mneverov — COMMENTED** [review]
@yuzefovich thanks for the reviews! My bad, I should have payed more attention to the [pg_table](https://www.postgresql.org/docs/9.1/functions-aggregate.html). 

`Postgres returns a float when both arguments are decimals`
As I understand Postgres returns a float when at least one argument is decimal. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-:-MLSMjBv6-uoSE5pNQQG:b-aes1hc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
> As I understand Postgres returns a float when at least one argument is decimal.

Yeah, that's what I meant to say.

Thanks! :lgtm: I only have one nit, and you'll also need to rebase on top of the latest master to regenerate the protobuf files.

> Reviewed 16 of 16 files at r2, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-:-MLUfzrH777CcOJVgaKN:b-8kmu7n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 1977 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-MLUfqEgCpfFekRFQn3I:-MLUfqEgCpfFekRFQn3J:b4z3ofg) ([raw file](https://github.com/cockroachdb/cockroach/blob/348149f255953aef5d3444224f03653ce91116d9/pkg/sql/sem/builtins/aggregate_builtins.go#L1977)):*
> ```Go
> }
> 
> // regressionInterceptAggregate represents y-intercept for Ints and Floats.
> ```

nit: the comments should be updated to remove the mention of ints and floats or also add a mention of decimals.

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56296)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 1977 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-MLUfqEgCpfFekRFQn3I:-MLWZkgYC5RoGj3uUs7v:b-y6oakf) ([raw file](https://github.com/cockroachdb/cockroach/blob/348149f255953aef5d3444224f03653ce91116d9/pkg/sql/sem/builtins/aggregate_builtins.go#L1977)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: the comments should be updated to remove the mention of ints and floats or also add a mention of decimals.
</blockquote></details>

Fixed, thx

**Review by yuzefovich — APPROVED** [review]
Thanks for your contribution!

bors r=yuzefovich

> Reviewed 2 of 16 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56296#-:-MLZ_bWn9xo2_DFozsq7:b-5br0rs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
