### PR TITLE
workload: set application_name

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

Release justification: low-risk, non-production code.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]

**Comment by knz** [comment]
I recommend a release note:

```
Release note (cli change): The `workload` command now sets its `application_name` to XXX, which facilitates recognition of its queries in the web UI.
```

**Comment by dt** [comment]
bors r+

another day, another fight with bors.

**Comment by knz** [comment]
@dt if it says "retrying" you don't have to poke it, it will simply do it again (later)

**Comment by dt** [comment]
yeah, sometimes it says that but never comes back. This time I guess it was dutifully still actually retrying though.

**Pull request merged**
