### PR TITLE
Revert "systemschema: use ExcludeDataFromBackup on some tables"

### PR DESCRIPTION
**Pull request by stevendanna**
This reverts commit 3d87bec3d1a7a17d079ef496c625b245a9721982.

We've begun seeing failing tests related to both backup, physical replication, and possibly other features. Bisect on one of the failing tests led to this commit. I don't yet understand the cause, but if I had to guess it would be that the change to the lease table is revealing some unexpected behavior.

We should investigate further, but reverting this commit may allows us to stablize CI as we figure out what is happening.

Epic: none
Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
My current hand-wavey theory is that the reason this is a problem for secondary tenants has something to do with range boundaries, the delayed application of span configuration, and how exclude from backup is implemented.

Namely, the decision about whether data is excluded from an ExportRequest is made by the replica. So what I'm envisioning is something where a newly created table is technically part of a range whose span config has exclude from backup set.

**Comment by stevendanna** [comment]
```
I240308 09:53:44.195226 9866 kv/kvserver/replica_command.go:440 ⋮ [T1,Vsystem,n1,split,s1,r81/1:‹/Tenant/10/Table/{25-106/…}›] 531  initiating a split of this range at key /Tenant/10/Table/26 [r82] (span config)
I240308 09:53:44.195740 9851 kv/kvserver/batcheval/cmd_export.go:112 ⋮ [T1,Vsystem,n1,tenant=10,s1,r81/1:‹/Tenant/10/Table/{25-106/…}›] 532  [/Tenant/10/Table/106/1, /Tenant/10/Table/106/1/‹1›) is part of a table excluded from backup, returning empty ExportResponse
```

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/issues/120122

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
>  best to revert until

Yep, concur (and in line with recently circulated guidance too IIRC)

**Comment by stevendanna** [comment]
bors r=dt

@rafiss If you disagree with this, let me know. I don't mind taking on the work of re-applying this once we understand the full scope of what is going on.

**Review by rafiss — APPROVED** [review]

**Pull request merged**
