### PR TITLE
sql: enable use of multi-column foreign keys

### LINKED ISSUE #7866: sql: allow compound (multi-col) foreign keys
Currently only the `REFERENCES` _column_ qualification is supported.

The majority of the implementation is in terms of just comparing indexes, so supporting multi-col foreign keys should mostly just require adding the handling of the table qualification and extending the resolution of which index to use to do multi-col resolution.

### PR DESCRIPTION
**Pull request by dt**
Fixes #7866

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8033)

### CODE REVIEW

**Comment by paperstreet** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 431 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbgjuDxhMz7CYWfylR:-KNbgjuDxhMz7CYWfylS:-1968074326) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L431)):*
> ```Go
> 	ret.target = target
> 
> 	// If a column isn't specified, attempt to default to PK.
> ```

nit: s/a column isn't/no columns are/

---

*[sql/create.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbh123cnRNYi_v6zeJ:-KNbh123cnRNYi_v6zeK:106682473) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L433)):*
> ```Go
> 	// If a column isn't specified, attempt to default to PK.
> 	if len(targetColNames) == 0 {
> 		if len(target.PrimaryIndex.ColumnNames) != len(srcCols) {
> ```

this check is redundant with one below. is the error message better enough to keep the duplication?

---

*[sql/create.go, line 439 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbhG6HgCucOCVUWdvA:-KNbhG6IepeDWJ-aK1Fj:-1342048245) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L439)):*
> ```Go
> 	}
> 
> 	targetCols := make([]sqlbase.ColumnDescriptor, len(targetColNames))
> ```

It might be worth moving this block to be a method on TableDescriptor

---

*[sql/create.go, line 478 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbhcvYtal7jHWoA6A-:-KNbhcvYtal7jHWoA6A0:473478584) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L478)):*
> ```Go
> 
> 	if constraintName == "" {
> 		constraintName = parser.Name(fmt.Sprintf("fk_%s_ref_%s", fromCols[0], target.Name))
> ```

this feels more likely to conflict than the old version, what happens if it does?

---

*[sql/create.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbfGvcVh6pKTOvFTzr:-KNbfGvdJyPwB5sZebqG:-667637045) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L508)):*
> ```Go
> func colNames(cols []sqlbase.ColumnDescriptor) string {
> 	var s bytes.Buffer
> 	s.WriteString("(\"")
> ```

Use backticks instead of escaping these, here and throughout this function

---

*[sql/create.go, line 336 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbiUPMRhB_o9bE7WoR:-KNbiUPN1WOezyVzBAZV:796171663) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff4fc748000a19b88522524c5a1766dc1c27b6/sql/create.go#L336)):*
> ```Go
> 	}
> 
> 	// Multiple FKs from the same column would potentially result in ambiguous or
> ```

can this be moved to ValidateTable?

---

*[sql/parser/create.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbeWn09WyOVimkRqcQ:-KNbeWn1-cbX6nnyu63I:-2144561664) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8ae75f9ea3bee68414e53e975292c4c1b4379f/sql/parser/create.go#L459)):*
> ```Go
> 	}
> 	buf.WriteString("FOREIGN KEY ")
> 	buf.WriteByte('(')
> ```

Combine this with the above WriteString

---

*[sql/testdata/fk, line 306 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbjOWqsV8zWuelJryd:-KNbjOWqsV8zWuelJrye:-1097152281) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff4fc748000a19b88522524c5a1766dc1c27b6/sql/testdata/fk#L306)):*
> ```
> CREATE TABLE refpairs (a INT, b STRING, FOREIGN KEY (a, b) REFERENCES pairs2, INDEX (b, a))
> 
> # TODO(dt): allow using a strict prefix of an index
> ```

fwiw, I need this for interleaved. fast follow?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 431 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbgjuDxhMz7CYWfylR:-KNbx1rHtUkwPnq4cLCc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L431)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> nit: s/a column isn't/no columns are/
</details>
Done.

---

*[sql/create.go, line 433 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbh123cnRNYi_v6zeJ:-KNc5A0zoOsWU0RHFGDr:84515915) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L433)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> this check is redundant with one below. is the error message better enough to keep the duplication?
</details>
Seemed a little clearer since it might be strange when it says "found 3" or something, but I don't feel strongly.
Done.

---

*[sql/create.go, line 439 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbhG6HgCucOCVUWdvA:-KNc5a1pPRK4quHpSdrS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L439)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> It might be worth moving this block to be a method on TableDescriptor
</details>
Done.

---

*[sql/create.go, line 478 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbhcvYtal7jHWoA6A-:-KNbx2_pC1PEomckLehu:1954198557) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L478)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> this feels more likely to conflict than the old version, what happens if it does?
</details>
it can't, since `fromCols[0]` participates in at-most-one FK.

---

*[sql/create.go, line 508 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbfGvcVh6pKTOvFTzr:-KNbxPMGq0Uo_uku7DOZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L508)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Use backticks instead of escaping these, here and throughout this function
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 336 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbiUPMRhB_o9bE7WoR:-KNcC-I82Ojsafq40lkh:-398893274) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff4fc748000a19b88522524c5a1766dc1c27b6/sql/create.go#L336)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> can this be moved to ValidateTable?
</details>
it could potentially _also_ be in Validate, but at this point, the FKs aren't in the descriptor yet, just in the `fkTargets` and we call Validate before writing the desc, but we can't add the FKs (in finalizeFKs) until after that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/parser/create.go, line 459 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbeWn09WyOVimkRqcQ:-KNcFLVBOEHRpgdGZtzO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8ae75f9ea3bee68414e53e975292c4c1b4379f/sql/parser/create.go#L459)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Combine this with the above WriteString
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 478 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbhcvYtal7jHWoA6A-:-KNcuXqwqvyeo9T8fS5R:676538604) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8dcab519bde29098dccc9e28b12b86f1d1af8ad/sql/create.go#L478)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it can't, since `fromCols[0]` participates in at-most-one FK.
</details>
Aha!

---

*[sql/create.go, line 336 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbiUPMRhB_o9bE7WoR:-KNcvJTMgdvIlA7bjfoq:1397563081) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff4fc748000a19b88522524c5a1766dc1c27b6/sql/create.go#L336)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it could potentially _also_ be in Validate, but at this point, the FKs aren't in the descriptor yet, just in the `fkTargets` and we call Validate before writing the desc, but we can't add the FKs (in finalizeFKs) until after that.
</details>
stick a TODO in Validate plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-:-KNcwCyQICP2JhQTfMwj:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 336 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033#-KNbiUPMRhB_o9bE7WoR:-KNge4rFkxp2ZPdFpeGg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff4fc748000a19b88522524c5a1766dc1c27b6/sql/create.go#L336)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> stick a TODO in Validate plz
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8033)*

**Pull request merged**
