### PR TITLE
cli/sql: remove the smart prompt logic

### LINKED ISSUE #46074: cli/sql: remove the handling of multi-line transactions
Today the SQL shell detects when the user is starting a txn with BEGIN, and will do its best to try to collect all the statements for the txn client-side before sending the txn **as a whole** to the server.

This increases the chance that the server be able to perform all retries server-side, and also reduces the overall duration of a txn (and thus reduces the chances of conflicts with current regular application load on the db).

This functionality was requested by @andreimatei in October 2016, and introduced in the code via #10187. At the time the PR was highly desired and the review concluded with:

> @andreimatei  :lgtm: really nice

Now, today @andreimatei changed his mind and as reported in #45816:

> Also Rafa remind me where you stand on getting rid of this message? I for one never want it.
> I challenge you to conduct a poll of 10 people; if any single one says that they prefer the smart_prompt option set by default, I'll shut up.

So this issue is to remove the code, which does indeed make the handling of the command line relatively complex.

### PR DESCRIPTION
**Pull request by knz**
Fixes #46074

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: though there is something funky about the grammar in the first sentence in the release note. 

> CockroachDB's own SQL shell (cockroach sql/demo) does not any more attempt to prompt for more lines of input
after the user enters BEGIN, before BEGIN and these extra lines of
input are sent to the server.

`s/does not any more attempt to prompt/no longer prompts/g`

The other part that is funky here is the fragment "after the user enters BEGIN, before BEGIN". I'm not quite clear on what you were trying to convey there. Ah, re-reading this again. Perhaps something like: `no longer prompts for more lines of input after the user enters BEGIN before sending the statement to the server`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-:-M6_Cu1wChODihaM5C2K:b-1t7sf5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-:-M6_ufCZ5d_1-hSUoHQl:bb6ywmx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/cli/sql.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-M6_uYyK0OWcSXYrJg4U:-M6_uYyK0OWcSXYrJg4V:bbb6yd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d6e9f7ca2a9ad588fbde130c234df9faf3f287/pkg/cli/sql.go#L367)):*
> ```Go
> 	},
> 	`smart_prompt`: {
> 		description:               "detect open transactions and propose entering multi-line statements",
> ```

replace the description with just "deprecated"?
___
*[pkg/cli/sql.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-M6_uVqe1wqgm6cY6EDo:-M6_uVqfDns4SaZ5-ni1:b-7wagff) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d6e9f7ca2a9ad588fbde130c234df9faf3f287/pkg/cli/sql.go#L370)):*
> ```Go
> 		isBoolean:                 true,
> 		validDuringMultilineEntry: false,
> 		set:                       func(c *cliState, _ string) error { c.smartPrompt = true; return nil },
> ```

should this `c.smartPrompt` go away?

**Review by knz — COMMENTED** [review]
Thanks peter for your recommendation. Adopted.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-:-M6al5tt0feCDyFw--sW:brj48xm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/cli/sql.go, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-M6_uYyK0OWcSXYrJg4U:-M6akZKo61LScotg1Mgf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d6e9f7ca2a9ad588fbde130c234df9faf3f287/pkg/cli/sql.go#L367)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

replace the description with just "deprecated"?
</blockquote></details>

Done.
___
*[pkg/cli/sql.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48433#-M6_uVqe1wqgm6cY6EDo:-M6akZc83DJY_JXbO5s2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09d6e9f7ca2a9ad588fbde130c234df9faf3f287/pkg/cli/sql.go#L370)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

should this `c.smartPrompt` go away?
</blockquote></details>

Done.

**Comment by knz** [comment]
bors r=petermattis,andreimatei

**Pull request merged**
