### PR TITLE
workload/tpch: port loadgen/tpch to implement workload.Generator 

### PR DESCRIPTION
**Pull request by danhhz**
This one is a little awkward because we don't have a go implementation
for generating the table data, but I've glanced at the `dbgen` source
and it doesn't seem out of the question that we could do it eventually.

I still think it's useful to have the queryload part ported, plus
there's some potential upcoming work with store dump fixtures and having
this will let us keep them in the standard locations.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Friendly ping : - )

**Comment by arjunravinarayan** [comment]
I did not review queries.go or the schema definitions, I just skimmed it as I assume its just a copy as-is.

:LGTM:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23332#-:-L718dqPjXHmkj3tWeFt:b-wxw7g5)*

**Comment by dt** [comment]
nit: schema defs might want specify primary keys -- they are allowed in the spec and should make it perform better / take up less space.

**Comment by danhhz** [comment]
> schema defs might want specify primary keys (indeed, instead of some of the unique indexes)

Done. RFAL @dt

**Review by dt — APPROVED** [review]
I think @arjunravinarayan told me that `lineitem` get's `PRIMARY KEY (l_orderkey, l_linenumber)`. (there's no corresponding unique idx in loadgen which is why I missed it, but that's apparently just oversight)

**Comment by danhhz** [comment]
> I think @arjunravinarayan told me that lineitem get's PRIMARY KEY (l_orderkey, l_linenumber). (there's no corresponding unique idx in loadgen which is why I missed it, but that's apparently just oversight)

Done

**Review by dt — APPROVED** [review]

**Comment by arjunravinarayan** [comment]
LGTM Thanks for catching this long-thought-about fix @dt!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23332#-:-L71WJkvvgMw5mCPnaE1:bjbswsk)*

**Comment by danhhz** [comment]
TFTRs!

**Pull request merged**
