### PR TITLE
cmd/roachtest: add --count flag for running tests multiple times

### LINKED ISSUE #25284: roachtest: add --count flag
This makes it easier to "stress" test a roachtest, something we should do habitually before merging one (and eventually automate).

- this should work with the `-c` flag (reuse cluster).
- this could interact with the `--parallelism` flag by running multiple copies of the test in parallel (only when `-c` is not specified)

@petermattis, assigning you as the resident roachtest expert.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #25284

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Don't review this yet. The implementation is too simple and won't work with parallel execution of the same test.

**Comment by petermattis** [comment]
Ok, fixed the issue with parallel execution of the same test. This is ready for a look.

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25311#-:-LBfdJFRC1Jw5zAAVv0I:bnfp4nl)*

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
