### PR TITLE
rowexec,execinfrapb: add support for filtering a table using an inverted index 

### PR DESCRIPTION
**Pull request by sumeerbhola**
InvertedFiltererSpec is the filtering spec. invertedFilterer
is the implementation -- it uses the
batchedInvertedExprEvaluator and DiskBackedNumberedRowContainer
to do the real work.

The first commit is from #48720.
This PR lacks tests -- I am looking for early feedback before adding tests.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
This all looks reasonable to me, but I'm not familiar with a lot of the conventions used in the execution code, so @asubiotto and @yuzefovich will probably have better feedback.

> Reviewed 2 of 2 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8GOVDu3iENAvVVfi4c:b6yh822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GGhj7EB9WGe01jgb3:-M8GGhj7EB9WGe01jgb4:bnbl25k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/execinfrapb/processors_sql.proto#L552)):*
> ```protobuf
>   // Optional expression involving the primary key columns, where
>   // @1 refers to the first PK column, and so on. The inverted index
>   // column is not part of this numbering.
> ```

This seems fine to me, but is there a reason you're doing this differently from the `InvertedJoinerSpec`? That numbering includes all the columns of the table, not just the PK columns.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GHFNX6PbT9_xoI5uv:-M8GHFNX6PbT9_xoI5uw:b-fgomgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L35)):*
> ```Go
> 
> const (
> 	ifStateUnknown invertedFiltererState = iota
> ```

[nit] I know "if" is short for invertedFilterer, but it looks a lot like the word "if". Maybe this should be `ifsUnknown`, `ifsReadingInput`, and `ifsEmittingRows`?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GI4cgAqLjMbFBl5xG:-M8GI4cgAqLjMbFBl5xH:b-77y69t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L89)):*
> ```Go
> 
> 	// Prepare inverted evaluator for later evaluation. The returned spans are
> 	// ignored since the input is already setup to provide rows from the spans.
> ```

[nit] setup -> set up
___
*[pkg/sql/rowexec/inverted_filterer.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GJWml0TOdpaqTxGig:-M8GJWmm2UGN-vT6Hv19:b-ufr83g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L147)):*
> ```Go
> 	// - Evaluate the inverted expression
> 	// - Retrieve the results and for each row evaluate the on expression and output.
> 	for ifr.State == execinfra.StateRunning {
> ```

Can this state change in any of the code below?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GNLtH-wDLiAqwCwb2:-M8GNLtH-wDLiAqwCwb3:b14iq2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L184)):*
> ```Go
> 		evalResult := ifr.invertedEval.evaluate()
> 		ifr.rc.SetupForRead(ifr.Ctx, evalResult)
> 		ifr.evalResult = evalResult[0]
> ```

Why are you setting this to `evalResult[0]`?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GKjNZ78Ueh8Ar0m3H:-M8GKjNZ78Ueh8Ar0m3I:be27og0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L194)):*
> ```Go
> 	}
> 	// Add the primary key in the row to the row container.
> 	keyIndex, err := ifr.rc.AddRow(ifr.Ctx, row[1:])
> ```

can you always guarantee that you only need to skip over one column of the row?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GMQskBc0Ggu4N4E-t:-M8GM-3Q0yMEcgwXKlrP:b-o5peny) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L217)):*
> ```Go
> 		return ifStateUnknown, nil, ifr.DrainHelper()
> 	}
> 	if ifr.resultIdx > len(ifr.evalResult) {
> ```

What is the purpose of this check? A comment would help.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8I3nZ830162cvMwkVI:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rytaft, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GGhj7EB9WGe01jgb3:-M8Hx_sxElMR-_zDM5hw:b-pi7q7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/execinfrapb/processors_sql.proto#L552)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This seems fine to me, but is there a reason you're doing this differently from the `InvertedJoinerSpec`? That numbering includes all the columns of the table, not just the PK columns.
</blockquote></details>

I did this because the spec does not mention the `TableDescriptor` (unlike `InvertedJoinerSpec`). I'm happy to follow whatever the convention is in such a situation.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GHFNX6PbT9_xoI5uv:-M8Hylxs5lfuS8RlL2OX:bw7snif) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L35)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I know "if" is short for invertedFilterer, but it looks a lot like the word "if". Maybe this should be `ifsUnknown`, `ifsReadingInput`, and `ifsEmittingRows`?
</blockquote></details>

Changed to `ifr` prefix since that is also what is being used in the method signatures.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GI4cgAqLjMbFBl5xG:-M8Hz2JL9z21KgjVA7rP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L89)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] setup -> set up
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GJWml0TOdpaqTxGig:-M8HzWW6D0z-f7dcSZ8M:b-bpdaig) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L147)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can this state change in any of the code below?
</blockquote></details>

Yes. `StateRunning` is part of `ProcessorBase` and `ProcessorBase.MoveToDraining` will change it.
This is following the style I've seen in other processors (e.g. `hashAggregator.Next`)
___
*[pkg/sql/rowexec/inverted_filterer.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GNLtH-wDLiAqwCwb2:-M8I1n0T2NTl3tzXmAq7:beadh26) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L184)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why are you setting this to `evalResult[0]`?
</blockquote></details>

The batch has a single expression. I've added a comment.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GKjNZ78Ueh8Ar0m3H:-M8I2HgIAgfaH6GATD1e:b-xkn682) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L194)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you always guarantee that you only need to skip over one column of the row?
</blockquote></details>

I believe so, given how we currently write inverted indexes. I've added a comment.
This may change with geo partitioned inverted indexes.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GMQskBc0Ggu4N4E-t:-M8I3TOJ5UBEUkQUBsbB:b-smu75) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L217)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

What is the purpose of this check? A comment would help.
</blockquote></details>

This was slightly incorrect. This is the condition when all rows have been emitted. Added a comment.

**Review by yuzefovich — COMMENTED** [review]
The code LGTM, just some nits from me.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8ItxW3BCxpNSYBYLZG:b-pntleh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rytaft, and @sumeerbhola)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GGhj7EB9WGe01jgb3:-M8IoysABME09480xZFr:bde1lzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/execinfrapb/processors_sql.proto#L552)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I did this because the spec does not mention the `TableDescriptor` (unlike `InvertedJoinerSpec`). I'm happy to follow whatever the convention is in such a situation.
</blockquote></details>

We don't seem to have a precedent for such scenario, and the current comment sounds good to me, so I'm in favor of keeping it as is.
___
*[pkg/sql/opt/invertedexpr/span_expression.proto, line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IpHla4yfiNHcOFc4O:-M8IpHla4yfiNHcOFc4P:bpn58li) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/opt/invertedexpr/span_expression.proto#L12)):*
> ```protobuf
> 
> syntax = "proto3";
> package cockroach.sql.opt.invertedexpr;
> ```

I'm just curious: this typo wasn't caught because this `SpanExpressionProto` wasn't used?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GJWml0TOdpaqTxGig:-M8IrNNvEhQ1ezTNQaP3:b-mjwu0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L147)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes. `StateRunning` is part of `ProcessorBase` and `ProcessorBase.MoveToDraining` will change it.
This is following the style I've seen in other processors (e.g. `hashAggregator.Next`)
</blockquote></details>

All processors pretty much follow this pattern.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8Iq1XB2naor2L2ZOVv:-M8Iq1XB2naor2L2ZOVw:b6qgals) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L61)):*
> ```Go
> }
> 
> var _ execinfra.Processor = (*invertedFilterer)(nil)
> ```

nit: we usually use something like `var _ execinfra.Processor = &invertedFilterer{}` for this.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IqHykCQVHE8fULkdj:-M8IqHykCQVHE8fULkdk:b-1o6iqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L90)):*
> ```Go
> 	// Prepare inverted evaluator for later evaluation. The returned spans are
> 	// ignored since the input is already set up to provide rows from the spans.
> 	ifr.invertedEval.getSpans()
> ```

nit: given the comment that "returned spans are ignored" I wonder whether `getSpans` should be renamed/refactored to something like `init` and a separate `getSpans` method.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IqZom3B6UGFNA9MPC:-M8IqZom3B6UGFNA9MPD:b-zchzkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L92)):*
> ```Go
> 	ifr.invertedEval.getSpans()
> 
> 	outputColTypes := make([]*types.T, len(ifr.inputTypes)-1)
> ```

A quick comment about which column is being omitted would be helpful.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IrJ2r5AD7QoJCRELw:-M8IrJ2r5AD7QoJCRELx:byohg2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L146)):*
> ```Go
> 	//   to the invertedEval.
> 	// - Evaluate the inverted expression
> 	// - Retrieve the results and for each row evaluate the on expression and output.
> ```

nit: `s/on/ON/g`.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IsUTJBqv2UfFvwX_z:-M8IsUTJBqv2UfFvwXa-:bjqnbwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L225)):*
> ```Go
> 		drainFunc(ifr.rc.UnsafeReset(ifr.Ctx))
> 	}
> 	currRowIdx := ifr.resultIdx
> ```

super nit: it's quite unusual to see "current" truncated as "curr", maybe `s/curr/cur/g`?

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @sumeerbhola)

___
*[pkg/sql/rowexec/inverted_filterer.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GJWml0TOdpaqTxGig:-M8KxZcW63rFg6_IlMF6:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L147)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

All processors pretty much follow this pattern.
</blockquote></details>

Got it - thanks!
___
*[pkg/sql/rowexec/inverted_filterer.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GMQskBc0Ggu4N4E-t:-M8KxwxJAAS_o4bB6hw4:bvwchd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L217)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This was slightly incorrect. This is the condition when all rows have been emitted. Added a comment.
</blockquote></details>

It's just strange that you're checking the length of `ifr.evalResult`, but you're actually getting rows from `ifr.rc`. Are those guaranteed to be the same length? Why not just check `ifr.rc`? Along those lines, why do you even need to store `ifr.evalResult`? Doesn't seem like you're using it other than right here....

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

I've added a test for `invertedFilterer`, and rebased now that `batchedInvertedExprEvaluator` is merged.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8NEhBA4KTEphKFkErc:bchzfbf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rytaft, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GGhj7EB9WGe01jgb3:-M8MaqRBEUVFHD3sYM7O:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/execinfrapb/processors_sql.proto#L552)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We don't seem to have a precedent for such scenario, and the current comment sounds good to me, so I'm in favor of keeping it as is.
</blockquote></details>

Ack
___
*[pkg/sql/opt/invertedexpr/span_expression.proto, line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IpHla4yfiNHcOFc4O:-M8Maz2D-3_pFPQpGRif:b-dquqaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/opt/invertedexpr/span_expression.proto#L12)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm just curious: this typo wasn't caught because this `SpanExpressionProto` wasn't used?
</blockquote></details>

It wasn't used in a `.proto` file -- the generated Go code was used.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8GMQskBc0Ggu4N4E-t:-M8MfK2V8cS9dVHcUUa1:b-iacbv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a58eebcd22b474be09584dab3e2e01893225f08/pkg/sql/rowexec/inverted_filterer.go#L217)):*

> It's just strange that you're checking the length of ifr.evalResult, but you're actually getting rows from ifr.rc. Are those guaranteed to be the same length?

The container has all the input primary keys, and we don't know which ones we will need until after the expression is evaluated. So, no, the length of the `evalResult` and the container are not the same. The former is a subset.

> Why not just check ifr.rc? Along those lines, why do you even need to store ifr.evalResult? Doesn't seem like you're using it other than right here....

Lack of test :). The `GetRow()` call below should have used `ifr.evalResult`.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8Iq1XB2naor2L2ZOVv:-M8MdwW8B67M66NUAig6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L61)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: we usually use something like `var _ execinfra.Processor = &invertedFilterer{}` for this.
</blockquote></details>

Done
___
*[pkg/sql/rowexec/inverted_filterer.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IqHykCQVHE8fULkdj:-M8NE5BqD8SC9dCLyFFX:b7iklte) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L90)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: given the comment that "returned spans are ignored" I wonder whether `getSpans` should be renamed/refactored to something like `init` and a separate `getSpans` method.
</blockquote></details>

I've renamed `getSpans` to `init`, which returns the spans.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IqZom3B6UGFNA9MPC:-M8Metkt2_nb6GVlc-WJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L92)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

A quick comment about which column is being omitted would be helpful.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IrJ2r5AD7QoJCRELw:-M8Mf--j1ZhtrpuR8jZD:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L146)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/on/ON/g`.
</blockquote></details>

Done
___
*[pkg/sql/rowexec/inverted_filterer.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-M8IsUTJBqv2UfFvwX_z:-M8Mg6ghCu4VJ_mFG2c2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78fd24f790d8a11489113882f959adec4aabb3c2/pkg/sql/rowexec/inverted_filterer.go#L225)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: it's quite unusual to see "current" truncated as "curr", maybe `s/curr/cur/g`?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8NIyts3V-KB4bmqax1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49446#-:-M8Nr8Kx7JwEbLG5ZtD4:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)

**Pull request merged**
