### PR TITLE
sql: add user_id column to system.web_sessions table

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds a new `user_id` column to the `system.web_sessions` table,
which corresponds to the existing `username` column. Migrations are
also added to alter and backfill the table in older clusters.

Part of #87079

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, looks good overall! just had a few nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-:-NOM-O15BgsHMZt288JR:b-kqzc9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/cli/democluster/session_persistence.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOLzuiXD6OeaE7GP_pJ:-NOLzuiXD6OeaE7GP_pK:b7h6awn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/cli/democluster/session_persistence.go#L211)):*
> ```Go
> 		}
> 
> 		// TODO(yang): Update this to insert new user_id column.
> ```

can we do this right now?
___
*[`pkg/server/authentication.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOM-3Nf1OnzBeZJ-R-_:-NOM-3Nf1OnzBeZJ-R-a:bfgfsvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/server/authentication.go#L493)):*
> ```Go
> 	ctx context.Context, userName username.SQLUsername,
> ) (int64, []byte, error) {
> 	privilegesTableHasUserIDCol := s.sqlServer.execCfg.Settings.Version.IsActive(ctx,
> ```

should this be using `WebSessionsTableHasUserIDColumn`?
___
*[`pkg/upgrade/upgrades/web_sessions_table_user_id_migration_test.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOM-FNF6qRTQST3kquT:-NOM-FNF6qRTQST3kquU:bnd7zb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/upgrade/upgrades/web_sessions_table_user_id_migration_test.go#L100)):*
> ```Go
> 		}
> 		txRunner.Exec(t, fmt.Sprintf("CREATE USER testuser%d", i))
> 		txRunner.Exec(t, fmt.Sprintf(`
> ```

nit: can you add a comment saying that this INSERT is meant to mimic what the real auth code does?

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/cli/democluster/session_persistence.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOLzuiXD6OeaE7GP_pJ:-NOM9rwk7FkNQWUmrRF7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/cli/democluster/session_persistence.go#L211)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can we do this right now?
</blockquote></details>

Done.
___
*[`pkg/server/authentication.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOM-3Nf1OnzBeZJ-R-_:-NOM9spwD_3CRfCNVSnB:b-8jw02g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/server/authentication.go#L493)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be using `WebSessionsTableHasUserIDColumn`?
</blockquote></details>

Oops, yeah. Good catch!
___
*[`pkg/upgrade/upgrades/web_sessions_table_user_id_migration_test.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96896#-NOM-FNF6qRTQST3kquT:-NOMA2-JE0gbDhnorq8A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9962e8f5b81006a362476d5429725b34dcf7dc/pkg/upgrade/upgrades/web_sessions_table_user_id_migration_test.go#L100)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can you add a comment saying that this INSERT is meant to mimic what the real auth code does?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Comment by andyyang890** [comment]
seems like bors got stuck

bors r=rafiss

**Comment by andyyang890** [comment]
bors r=rafiss

**Pull request merged**
