### PR TITLE
util/mon: reduce sizes of BytesMonitor and BoundAccount structs

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR audits BytesMonitor and BoundAccount structs in order to clean up their creation and reduce their memory footprint. In particular, BytesMonitor goes from 208 bytes to 160 bytes and BoundAccount from 32 bytes to 24 bytes.

See each commit for more details.

Microbenchmarks are [here](https://gist.github.com/yuzefovich/f61ad24da47dacfee92dc06dd214d26f) - the improvement is solely due to stack allocating a slice of children in one of the commits.

Inspired by https://github.com/cockroachlabs/support/issues/2847.

Epic: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1, 63 of 63 files at r2, 21 of 21 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 5 of 5 files at r8, 1 of 1 files at r9, 103 of 103 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-:-Nt1oVz91uEmFcRmU7_4:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1QGnT4S0xktRacg5r):*
nit: reduing => reducing
___
*[`-- commits` line 120 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1nYaG3oELyy311203):*
nit: remove "size class"??
___
*[`-- commits` line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1niNN-BfFsLuvZ87d):*
I don't have a strong opinion here, but this is the most questionable change, IMO. Maybe worth a discussion? I guess the major argument in support of this is that they were usually unactionable. Maybe you can expand a bit more. Are you aware of any bugs we discovered based on this type of sentry report?
___
*[`pkg/util/mon/bytes_usage.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1OcbI-VRltY-DpDFf:-Nt1OcbI-VRltY-DpDFg:b-v9g50q) ([raw file](https://github.com/cockroachdb/cockroach/blob/763d3e1b8d400a7636befdc404913d1d491c7cab/pkg/util/mon/bytes_usage.go#L394)):*
> ```Go
> // NewUnlimitedMonitor calls. If a particular argument is not set, then a
> // reasonable default will be used.
> type NewMonitorArgs struct {
> ```

nit: `MonitorOptions` or `NewMonitorOptions`?
___
*[`pkg/util/mon/bytes_usage.go` line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1R6BI8J77HWv3ICtV:-Nt1R6BI8J77HWv3ICtW:b6ucq98) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ae02f38edcb12046c681955409bde73966de5c/pkg/util/mon/bytes_usage.go#L692)):*
> ```Go
> type EarmarkedBoundAccount struct {
> 	BoundAccount
> 	earmark int64
> ```

I don't understand why this field is needed. It looks like it's only incremented in `Reserve` and never read.
___
*[`pkg/util/mon/bytes_usage.go` line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1lhdG1WxyfV7q0Nfy:-Nt1lhdH51Vk_uBsvxgU:bq51fzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/464c99e0ad3c378dc16a39bda16d931ce8938c04/pkg/util/mon/bytes_usage.go#L215)):*
> ```Go
> 		// NB: this field doesn't need mutex protection but is inside of mu
> 		// struct in order to reduce the struct size.
> 		relinquishAllOnReleaseBytes bool
> ```

I didn't realize that a sub-struct must obey alignment rules too.

Proof of this, for posterity: https://go.dev/play/p/mPJcR53DY4Y
___
*[`pkg/util/mon/bytes_usage.go` line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1S_ye0aI7DASPNrOJ:-Nt1S_ye0aI7DASPNrOK:b-m7065r) ([raw file](https://github.com/cockroachdb/cockroach/blob/464c99e0ad3c378dc16a39bda16d931ce8938c04/pkg/util/mon/bytes_usage.go#L283)):*
> ```Go
> 	}
> 	if accountSize := unsafe.Sizeof(BoundAccount{}); accountSize != expectedAccountSize {
> 		panic(errors.AssertionFailedf("expected account size to be %d, found %d", expectedAccountSize, accountSize))
> ```

FYI: I recently learned about a way to enforce struct sizes at compile time: https://github.com/cockroachdb/swiss/pull/30/files

Though I don't think that'll work for the structs with sizes dependent on `util.RaceEnabled`.
___
*[`pkg/util/mon/bytes_usage.go` line 202 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1nES0DFuTh8pKsf00:-Nt1nES0DFuTh8pKsf01:b1rox9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e1377f3dd7b828126544336a9b7887877ef41be/pkg/util/mon/bytes_usage.go#L202)):*
> ```Go
> 		// ever becomes a concrete struct, then we should remove the layer of
> 		// indirection.
> 		maxBytesHist *metric.IHistogram
> ```

nit: this is the most questionable change IMO. Do we think it's worth the extra layer of indirection, the heap allocation of the interface box, and the oddness of keeping a pointer to an interface?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review! I removed the last two commits that are somewhat controversial but will merge all other ones to reduce the amount of diffs.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-:-Nt2D-ER9FZc-dbrEs5e:b-sn741u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/util/mon/bytes_usage.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1OcbI-VRltY-DpDFf:-Nt27v4x-_MyZDTe4Kdg:bulgzdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/763d3e1b8d400a7636befdc404913d1d491c7cab/pkg/util/mon/bytes_usage.go#L394)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `MonitorOptions` or `NewMonitorOptions`?
</blockquote></details>

I switched to just `Options` - in many places we already have `mon.` prefix, so `mon.MonitorOptions` sounds somewhat redundant.
___
*[`pkg/util/mon/bytes_usage.go` line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1R6BI8J77HWv3ICtV:-Nt29zGb4wMm26lM5pMI:be8bk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ae02f38edcb12046c681955409bde73966de5c/pkg/util/mon/bytes_usage.go#L692)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand why this field is needed. It looks like it's only incremented in `Reserve` and never read.
</blockquote></details>

It is read in `EarmarkedBoundAccount.Shrink` - note the different conditional in `BoundAccount.Shrink` and `EarmarkedBoundAccount.Shrink`.
___
*[`pkg/util/mon/bytes_usage.go` line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1S_ye0aI7DASPNrOJ:-Nt26R6B3qpB_AwjyWMR:b-dfcs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/464c99e0ad3c378dc16a39bda16d931ce8938c04/pkg/util/mon/bytes_usage.go#L283)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

FYI: I recently learned about a way to enforce struct sizes at compile time: https://github.com/cockroachdb/swiss/pull/30/files

Though I don't think that'll work for the structs with sizes dependent on `util.RaceEnabled`.
</blockquote></details>

Interesting, TIL.

The difficulty with the race build is that `Sizeof(syncutil.Mutex{})` is 12 bytes under race and 8 bytes without race, yet due to padding `Sizeof(BytesMonitor{})` increases by 8 bytes. Also GoLand is not happy with compile time assertion, so I decided to keep the "init" time one.

**Comment by yuzefovich** [comment]
Oops, need `dev gen bazel`.

bors r-

**Comment by yuzefovich** [comment]
Will wait for a green CI this time.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120529)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/util/mon/bytes_usage.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1OcbI-VRltY-DpDFf:-Nt2dEt70fQkRQ6DPFyH:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/763d3e1b8d400a7636befdc404913d1d491c7cab/pkg/util/mon/bytes_usage.go#L394)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I switched to just `Options` - in many places we already have `mon.` prefix, so `mon.MonitorOptions` sounds somewhat redundant.
</blockquote></details>

SGTM
___
*[`pkg/util/mon/bytes_usage.go` line 692 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120529#-Nt1R6BI8J77HWv3ICtV:-Nt2dXYD1mBXIsV_X6Lv:bo8xdqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1ae02f38edcb12046c681955409bde73966de5c/pkg/util/mon/bytes_usage.go#L692)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It is read in `EarmarkedBoundAccount.Shrink` - note the different conditional in `BoundAccount.Shrink` and `EarmarkedBoundAccount.Shrink`.
</blockquote></details>

Oh sorry - don't know how I missed that.

**Pull request merged**
