### PR TITLE
Refactor locking in `Store`

### PR DESCRIPTION
**Pull request by bdarnell**
Removes `raftGroupLocker` and prevents deadlocks including the one in #3038.

The new locking semantics are better documented and hopefully easier to reason about.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3119)

### CODE REVIEW

**Comment by bdarnell** [comment]
Hmm, looks like I spoke too soon. This passed 100 iterations before but now that I've rebased on master the deadlock is happening again, and more often than before.

**Comment by bdarnell** [comment]
OK, that's what I get for trying to slip a "harmless" one-line change in without testing before the review. It should be fixed now.

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[multiraft/multiraft.go, line 526 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xWTXYggsuuociwgZe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L526)):</sup>
don't you need to hold the lock when you do this?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by bdarnell** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[multiraft/multiraft.go, line 526 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xWTXYggsuuociwgZe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L526)):</sup>
No. Like all attributes of `state`, `state.storageLocked` is only touched from the state's goroutine. The lock governs access to the Storage itself, not the `state`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[multiraft/multiraft.go, line 526 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xWTXYggsuuociwgZe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L526)):</sup>
Can you add a comment explaining this?  it's also weird that this ordering is not symmetric with `unlockStorage()`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by BramGruneir** [comment]
Could you pull the memoryStorage out of storage into it's own file?  That way storage is just the interface and clean.

**Comment by tschottdorf** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[multiraft/multiraft.go, line 526 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xWTXYggsuuociwgZe)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L526)):</sup>
the comment on `type state` has this covered imo:

> // state represents the internal state of a MultiRaft object. All variables here
// are accessible only from the state.start goroutine so they can be accessed without
// synchronization.


---

<sup>**[multiraft/multiraft.go, line 528 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xgp1ogzihjZdFStA-)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L528)):</sup>
nit: `if locker := s.Storage().RaftLocker(); locker != nil { locker.Lock() }`


---

<sup>**[multiraft/multiraft.go, line 1278 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xhQxJO-5ebEXYv4yx)** ([raw file](https://github.com/cockroachdb/cockroach/blob/f010b98297ea5862dd13889e5749a4f7f52b35e2/multiraft/multiraft.go#L1278)):</sup>
add `assertStorageLocked`?


---

<sup>**[multiraft/storage.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xgHEHwSfKh-Ym1Xrt)** ([raw file](https://github.com/cockroachdb/cockroach/blob/44b0260aa55926157983e45cd83219f507ba3d82/multiraft/storage.go#L130)):</sup>
Can you add a comment explaining why that's enough?


---

<sup>**[storage/store.go, line 935 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xj1-aBpkV7GoRTDMa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/30b69cbf21562a41067139ff67099ec5a9e1cbe9/storage/store.go#L935)):</sup>
a particular reason for this change?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by tschottdorf** [comment]
LGTM. Much clearer indeed.


---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by BramGruneir** [comment]
LGTM with only the s.storagelocked issue and a small wording nit.

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/store.go, line 935 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xj1-aBpkV7GoRTDMa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/30b69cbf21562a41067139ff67099ec5a9e1cbe9/storage/store.go#L935)):</sup>
This block is the point of the whole PR: we had to get the call to `multiraft.RemoveGroup` out from under `store.mu` to avoid the deadlock. And without that synchronization, we have to loop to make sure the group wasn't recreated (i.e. the protection we intended to get with `raftGroupLocker`)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by tschottdorf** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/store.go, line 935 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xj1-aBpkV7GoRTDMa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/30b69cbf21562a41067139ff67099ec5a9e1cbe9/storage/store.go#L935)):</sup>
sorry, I commented on r5->r6, where the only change is from
`for _, ok := ...; ok {` to `for { if _, ok := .. }``.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[storage/store.go, line 935 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119#-K2xj1-aBpkV7GoRTDMa)** ([raw file](https://github.com/cockroachdb/cockroach/blob/30b69cbf21562a41067139ff67099ec5a9e1cbe9/storage/store.go#L935)):</sup>
Ah. That was a commit that was squashed away in the final history. I was trying to be clever and optimize away the for/if combination, but the `for` version was incorrect and keeping the `for` and `if` as separate statements is clearer than combining them both into a single `for`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3119)

**Pull request merged**
