### PR TITLE
sql: handle binary JSONB values

### PR DESCRIPTION
**Pull request by justinj**
I thought I had written some tests for this but I guess I didn't. This
commit adds tests for the binary format of transmitting JSONB values and
corrects what we were doing before.

Release note (bug fix): support the binary format for JSONB values.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/generate-binary/main.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23114#-L6MtF00bV7XJGpF6XrB:-L6MtF00bV7XJGpF6XrC:b-yijn5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1fba4a7d6b9e506a33cce422fa9d2f2ee34c63/pkg/cmd/generate-binary/main.go#L231)):*
> ```Go
> 	`{"\uD83D\uDE80": "hello"}`,
> 	`[1, 2, 3]`,
> 	`{"foo": 123}`,
> ```

Do we need any more complex test cases? There are no nested containers in these inputs. Also no `null`, `true` or `false` values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23114#-:-L6MtCnHMplC0XLfwro8:bg7igkv)*

**Comment by justinj** [comment]
Heads up that I made some slight changes to the generator to make it more usable with JSON stuff.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/generate-binary/main.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23114#-L6MtF00bV7XJGpF6XrB:-L6Nq1kBaUF05of3LA2h:b-4zva2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae1fba4a7d6b9e506a33cce422fa9d2f2ee34c63/pkg/cmd/generate-binary/main.go#L231)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do we need any more complex test cases? There are no nested containers in these inputs. Also no `null`, `true` or `false` values.
</blockquote></details>

Good call - I added some more tests, although I'm not particularly worried about having wide coverage here, since the format is basically just text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23114#-:-L6Nq8PAqIRhZBaAcp_w:bjuayns)*

**Comment by jordanlewis** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23114)*

**Comment by justinj** [comment]
TFTR!

**Pull request merged**
