### PR TITLE
release-21.2: clusterversion,migration: combine migrations for new stats tables

### LINKED ISSUE #71476: migrations: duplicate use of migration leads to skipped migration
**Describe the problem**

In https://github.com/cockroachdb/cockroach/blob/ab0c462672cff1e6928aba2dfc3a5429466aea39/pkg/migration/migrations/migrations.go#L75-L86

We use the same migration key more than once. Nothing prevents that and nothing complains. It also isn't supported. This means that when we upgrade to 21.2 from 21.1, we never create the `statement_statistics` table. 

**Proposed solution**

We need to copy the key for the migration in question to the end of the set of cluster versions. We should probably make two cluster versions for the two migrations and use the latter as the version gate. This new patch will make sure that the migration runs. We'll also add some code to crash if we duplicate a migration.

### PR DESCRIPTION
**Pull request by ajwerner**
Before this PR, the two migrations were separate but were keyed on the same
version. This led to only one of them running. It also moves the migrations
to a later point in the migration chain so that they will run on clusters
which previously failed to create the missing table.

Fixes #71476.

Release note (bug fix): Fixed a bug from an earlier beta whereby a migration
to create the system.statement_statistics table was not run.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71477)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-MlpaU3tDfl8hgPO9i-1:-MlpaU3tDfl8hgPO9i-2:bcksza3) (no related file):*
This looks reasonable to me.  CreateSystemTable is idempotent so this should be safe.

---
___
*[pkg/clusterversion/cockroach_versions.go, line 290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-Mlp_rae4yFpyo3f6r3C:-Mlp_rae4yFpyo3f6r3D:b-orph31) ([raw file](https://github.com/cockroachdb/cockroach/blob/49994a232f964850ec33247f386659655baeb7ea/pkg/clusterversion/cockroach_versions.go#L290)):*
> ```Go
> 	// compaction on cluster startup and ensures that there is only one entry for
> 	// the schedule.
> 	SQLStatsCompactionScheduledJob
> ```

I'm assuming we're moving this because the job didn't get created because of the missing table.
___
*[pkg/migration/migrations/migrations.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-Mlp_b6M8NwuEcTmP4Ir:-Mlp_b6M8NwuEcTmP4Is:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/49994a232f964850ec33247f386659655baeb7ea/pkg/migration/migrations/migrations.go#L148)):*
> ```Go
> 	for _, m := range migrations {
> 		if _, exists := registry[m.ClusterVersion()]; exists {
> 			panic(errors.AssertionFailedf("duplicate migration registration for %v", m.ClusterVersion()))
> ```

:100:

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71477)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Azhng)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-Mlpc46m3ejuVZrNZVhw):*
s/clusterverison/clusterversion/

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71477)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-MlpaU3tDfl8hgPO9i-1:-MlpcdnH85wz6loa4VRW:b-g9frl6) (no related file):*
> CreateSystemTable is idempotent so this should be safe.

That was the idea.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-Mlpc46m3ejuVZrNZVhw):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

s/clusterverison/clusterversion/
</blockquote></details>

Done.
___
*[pkg/clusterversion/cockroach_versions.go, line 290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71477#-Mlp_rae4yFpyo3f6r3C:-MlpcaY7EXkYSxVQKNTa:blpkobz) ([raw file](https://github.com/cockroachdb/cockroach/blob/49994a232f964850ec33247f386659655baeb7ea/pkg/clusterversion/cockroach_versions.go#L290)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I'm assuming we're moving this because the job didn't get created because of the missing table.
</blockquote></details>

That was the thought.

**Review by Azhng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71477)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @stevendanna)

**Pull request merged**
