### PR TITLE
sql: implement convert_to/convert_from

### LINKED ISSUE #26267: sql: Implement convert_from/convert_to
When we changed bytes/string casts in #18843, we lost the ability to convert between (utf-8) bytes and character strings without any additional interpretation (the encode/decode functions perform some additional transformations). We need to implement the `convert_from` and `convert_to` functions (at least when the second argument is `UTF8`) to allow direct conversions between bytes and strings. 

The context in which this need arose was to parse a value of type BYTES as JSON, which doesn't appear to be possible in cockroachdb today (`encode('{}'::bytes, 'escape')::json` almost works, but only if your data is ascii-only).

cc @mjibson

### PR DESCRIPTION
**Pull request by knz**
Fixes  #26267.

For docs: these built-in functions must be mentioned in the docs for the types string and bytes.

cc @bdarnell

### CODE REVIEW

**Review by yuzefovich — CHANGES_REQUESTED** [review]
LGTM

nit: in release note to first commit there is a typo in 'NULL'.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27328#-:-LH3NC191NVOMpXU3xM3:bpatmsx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27328#-LH3OPYz4tf5YI7CJmQ5:-LH3OOD_-2iWCyIOFULC:b-2wdyao) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfcd3fc9cc912c7ef515a0fa9222a37ec7ab5aaa/pkg/sql/sem/builtins/builtins.go#L260)):*
> ```Go
> 				enc := strings.ToLower(string(tree.MustBeDString(args[1])))
> 				switch enc {
> 				case "utf8", "utf-8", "unicode", "cp65001":
> ```

Is converting to `utf8` when asked for `unicode` the expected behavior?

**Review by yuzefovich — APPROVED** [review]

**Review by knz — COMMENTED** [review]
Thanks for your review!

> nit: in release note to first commit there is a typo in 'NULL'.

The word "NULL" is the name given to invalid pointers or references (or the "unknown" value in SQL). 

The *character* with code 0 is called "NUL" (that's its *name*) and *described* as "the null character": https://en.wikipedia.org/wiki/Null_character and https://unicode-table.com/en/0000/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27328#-:-LH3Uk4oCfR7FG8viSF1:bwxtlr8)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/builtins/builtins.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27328#-LH3OPYz4tf5YI7CJmQ5:-LH3W-oA03j5ZuiLwWSy:bkj4nen) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfcd3fc9cc912c7ef515a0fa9222a37ec7ab5aaa/pkg/sql/sem/builtins/builtins.go#L260)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is converting to `utf8` when asked for `unicode` the expected behavior?
</blockquote></details>

Yeah, isn't that odd? Added a comment to clarify.

**Review by yuzefovich — COMMENTED** [review]
Good to know, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27328#-:-LH3PV0Z2sin631gGCFa:bgzdldr)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
