### PR TITLE
Switch from MiB, GiB, TiB, etc. to MB, GB, TB, etc in admin UI

### LINKED ISSUE #4735: ui: GiB vs. GB (1024^3 vs. 1000^3)
tl;dr Let's allow the *iB designations, but make the *B designations also use 1024^i and also make them the defaults for documentation and user interface output.

Let's not confuse our users the way that hard drive manufacturers confused theirs in the 90s. I'm fine with allowing the [MGTPE]iB designations, but I strongly disagree with making [MBTPE]B mean 1000^i bytes instead of 1024^i bytes. Most people expect 1024^i, so that's what we should use. If you Google the difference, you'll find _many_ explanations. Most people are very confused when they see the "i". I didn't know what it meant, for example. I'm sure others here didn't know. My expectation is that byte sizes are specified in 1024^i increments. Why are we actually agreeing with the idiocy of hard drive manufacturers and adopting their nomenclature?

Other tools I've used which specify byte sizes in 1024^i increments using the standard [MGTPE]B designations:

```
pprof
colossus
leveldb/rocksdb
hdfs
cassandra
java
```

cc @BramGruneir

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #4735

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5679)

### CODE REVIEW

**Comment by tamird** [comment]
I didn't realize we had consensus on this. Still against it, FWIW.

**Comment by petermattis** [comment]
I don't think there is a "right" answer here. Pretty sure we should do what makes El Jefe happy.

**Comment by BramGruneir** [comment]
I am also against this.

**Comment by maxlang** [comment]
Staying out of the fray, but code LGTM.

**Comment by andreimatei** [comment]
Are you guys defending
```
if (Math.abs(bytes) < kibi)
```
?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5679#-:-KE2vGfaa5n-vEDrvx84:-659819662)*

**Comment by mberhault** [comment]
as much as I dislike seeing `iB` I agree that it's completely unambiguous and for that reason alone we may want to stick to it.

**Comment by JackKrupansky** [comment]
Unless I am mistaken, nobody asked for my input on this change... For that I am grateful!

Actually, I'll +1 anything that conserves screen real estate and increases whitespace.

(When I first saw GiB on a UI screen shot I actually thought the i was a semicolon - G;B vs. GiB.)

**Comment by bdarnell** [comment]
LGTM, but I'd also prefer `const kilo: number = 1000;`

**Comment by tamird** [comment]
Is it time to close this?

**Comment by maxlang** [comment]
Closing because #4735 was closed

**Pull request closed without merging**
