### PR TITLE
go.mod: bump Pebble to fb76a24ac098

### PR DESCRIPTION
**Pull request by dt**
fb76a24a db: Add BackingType, Locator to SSTableInfo
d9bbb98b db: Add EstimateDiskUsageByBackingType
628c4107 db: improve metrics formatting
bf5f4c44 sharedcache: reduce the scope of TestSharedCacheRandomized under race
5f5be26c pebble: Fix TestGetSSTableMetricsSingleNode flake

Release note (log format change): formatting improvements to Pebble metrics; tools that parse these metrics from the logs might need updating.

Epic: none.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by dt** [comment]
TFTRs!

bors r+

**Comment by dt** [comment]
DockerCLI test fixed, trying again

bors r+

**Comment by RaduBerinde** [comment]
Thanks for updating those tests!

**Pull request merged**
