### PR TITLE
workload: add idle-conns flag for adding idle connections to tpcc

### PR DESCRIPTION
**Pull request by RichardJCai**
workload: add idle-conns flag for adding idle connections to tpcc

Release note: None

#62526

### CODE REVIEW

**Comment by RichardJCai** [comment]
@rafiss 

Did some manual testing with the flag on a local setup. Do we actually want to add some configurations to roachtest?

Also there is a flag for configuring number of connections `conns` which is active connections so I didn't change that. We can add a flag for number of conns per pool but not sure if that's valuable right now.

[idle_0.txt](https://github.com/cockroachdb/cockroach/files/6223951/idle_0.txt)
[idle_10.txt](https://github.com/cockroachdb/cockroach/files/6223952/idle_10.txt)
[idle_100.txt](https://github.com/cockroachdb/cockroach/files/6223953/idle_100.txt)
[idle_1000.txt](https://github.com/cockroachdb/cockroach/files/6223954/idle_1000.txt)
[idle_10000.txt](https://github.com/cockroachdb/cockroach/files/6223955/idle_10000.txt)

**Comment by RichardJCai** [comment]
Ran more tests with idle conns, tpcc for 300s on 3 node roachprod cluster, don't see a trend for latencies and idle conns.

[idle_0.txt](https://github.com/cockroachdb/cockroach/files/6231046/idle_0.txt)
[idle_10.txt](https://github.com/cockroachdb/cockroach/files/6231047/idle_10.txt)
[idle_100.txt](https://github.com/cockroachdb/cockroach/files/6231048/idle_100.txt)
[idle_1000.txt](https://github.com/cockroachdb/cockroach/files/6231049/idle_1000.txt)
[idle_5000.txt](https://github.com/cockroachdb/cockroach/files/6231050/idle_5000.txt)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/workload/tpcc/tpcc.go, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62740#-MX3hPPI2ZR5fem5PWdw:-MX3hPPJ8TDpTu-a-xOn:b-gfmptz) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fb9158b6013896f284d0a90687bb0d7bdf4e1f/pkg/workload/tpcc/tpcc.go#L681)):*
> ```Go
> 
> 	fmt.Printf("Initializing %d idle connections...\n", w.idleConns)
> 	var conns []*pgxv4.Conn
> ```

any reason to use pgx/v4 just for this part? i think it'd be better to use the same version everywhere in the same package
___
*[pkg/workload/tpcc/tpcc.go, line 682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62740#-MX3esPe44OAA3ry3J9_:-MX3esPe44OAA3ry3J9a:bhevvpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fb9158b6013896f284d0a90687bb0d7bdf4e1f/pkg/workload/tpcc/tpcc.go#L682)):*
> ```Go
> 	fmt.Printf("Initializing %d idle connections...\n", w.idleConns)
> 	var conns []*pgxv4.Conn
> 	for i := 0; i < w.idleConns; i++ {
> ```

ah interesting. this seems like a good knob to have!

i didn't quite have this mind -- i was imagining that we would want more/better configuration for the `MultiConnPool` that is set up above (lines 620-630).

i thought the place to start would be to make `MaxConnsPerPool` not be hardcoded to 50. hmm but reading how pg_helpers.NewMultiConnPool works, maybe that setting isn't so relevant. we already have configuration for `MaxTotalConnections` which is more relevant for determining pool size (and influence the number of idle connections)

i think the issue here is that the pgxpool isn't that configurable. turns out all the interesting options (like MaxConnLifetime and MaxConnIdleTime) are only in v4... https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool

do you have an idea of how complicated it would be to upgrade this code to use pgx/v4 everywhere?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/workload/tpcc/tpcc.go, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62740#-MX3hPPI2ZR5fem5PWdw:-MX4tY7Y88uc6WFVGD9t:bjvbnip) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fb9158b6013896f284d0a90687bb0d7bdf4e1f/pkg/workload/tpcc/tpcc.go#L681)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

any reason to use pgx/v4 just for this part? i think it'd be better to use the same version everywhere in the same package
</blockquote></details>

Yeah going to use the same version.
___
*[pkg/workload/tpcc/tpcc.go, line 682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62740#-MX3esPe44OAA3ry3J9_:-MX4tdglD5miiQfM9mIY:b-21cof8) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fb9158b6013896f284d0a90687bb0d7bdf4e1f/pkg/workload/tpcc/tpcc.go#L682)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah interesting. this seems like a good knob to have!

i didn't quite have this mind -- i was imagining that we would want more/better configuration for the `MultiConnPool` that is set up above (lines 620-630).

i thought the place to start would be to make `MaxConnsPerPool` not be hardcoded to 50. hmm but reading how pg_helpers.NewMultiConnPool works, maybe that setting isn't so relevant. we already have configuration for `MaxTotalConnections` which is more relevant for determining pool size (and influence the number of idle connections)

i think the issue here is that the pgxpool isn't that configurable. turns out all the interesting options (like MaxConnLifetime and MaxConnIdleTime) are only in v4... https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool

do you have an idea of how complicated it would be to upgrade this code to use pgx/v4 everywhere?

</blockquote></details>

It would be a fair bit of manual work to upgrade it to pgx/v4, we have to update MultiConnPool in `pgx_helpers.go` to pgx/v4 as well which has a lot of uses. We would have to completely rework `MultiConnPool` since it has a pgx.ConnPool which from what I've seen, pgx/v4 does not actually have, decent amount of plumbing to replace it but I'll make an issue for it.

**Review by rafiss — APPROVED** [review]
lgtm! hopefully either you or i can get to that followup issue later after the first batch of work is done

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62740#-:-MX8E8eV2oxidAbIgKT8:b-dnh4gm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by RichardJCai** [comment]
I think it flaked, will try again
bors r=rafiss

**Pull request merged**
