### PR TITLE
distsqlrun: simplify Processor implementation burden

### PR DESCRIPTION
**Pull request by jordanlewis**
Note to reviewers: here's my stab at making processors not have to deal with ProducerMetadata. As a freebie, they also don't have to deal with ProcOutputHelper. Seeking input on the names (SimpleRowSource is not great, RowSourceInput might be better, and the combination of the two is probably horrible).

This commit adds a new set of interfaces to distsqlrun that seeks to
make it easier to implement Processors. Specifically, there are two
goals: to prevent implementations from having to deal with

1. metadata or errors from upstream Processors
2. cooking their output rows with ProcOutputHelper

This is accomplished by two new interfaces and two new implementations /
helpers:

1. `SimpleRowSource`, which is an extension of `RowSource` with a method
   `SimpleNext() (EncDatumRow, error)` that is meant to be implemented
   by Processors instead of `Next`.
2. `RowSourceInput`, which is an extension of `RowSource` with a method
   `NextFromInput() EncDatumRow` that is meant to be consumed by
   Processors instead of a raw `RowSource`.

These interfaces are made possible by:

1. A default implementation of `Next` on `ProcessorBase` that calls
   `SimpleNext` on the `ProcessorBase`'s embedding struct, taking care of
   converting any output errors or nil rows into the corresponding
   creation of metadata or draining, as well as cooking output rows from
   processors with their corresponding `ProcOutputHelper`.
2. A function called `MakeRowSourceInput` that wraps a `RowSource` along
   with a consuming `ProcessorBase` into a `RowSourceInput` that takes
   care of forwarding metadata from upstream processors.

As a result, processor implementations can be less confusing. They don't
have to properly forward metadata from upstream processors, which has
proven to be error-prone and a source of bugs that are difficult to test
for ahead of time.

This commit converts 2 processors to the new interface, the no-op
processor and the distinct processor. The rest can be done later.

Release note: None

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
I do find the combination of `SimpleRowSource` and `RowSourceInput` kind of confusing since it's not clear they're related. Maybe `SimpleRowSource` and `SimpleInput`?

Another thing to consider is that if this is going to be the more common case, we could rename the existing interface instead (e.g. `Next()` for the simple case and `NextRowOrMeta()` for the other.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-:-LMh6AVL8tkuMcBszBFv:b-vb3c1m)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2tCOE8ZT9GRISqz-:-LMh2tCOE8ZT9GRISqz0:b-pbddqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L531)):*
> ```Go
> 	trailingMeta []ProducerMetadata
> 
> 	nextRow sqlbase.EncDatumRow
> ```

When is this non-nil?
___
*[pkg/sql/distsqlrun/processors.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2-XXAqE2a2cxQRE3:-LMh2-XXAqE2a2cxQRE4:bn73ukf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L824)):*
> ```Go
> func (pb *ProcessorBase) Next() (sqlbase.EncDatumRow, *ProducerMetadata) {
> 	for pb.State == StateRunning {
> 		if len(pb.trailingMeta) > 0 {
> ```

This might not matter but it seems like trailing metadata used to only be returned during `stateTrailingMeta`. Are we ok with changing that?

**Review by solongordon — COMMENTED** [review]
Meant to say, excited for this improvement!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-:-LMh7tnJDoK_hWc-BBWb:b8ox1sw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — CHANGES_REQUESTED** [review]
Excited for this improvement too. This is a good start, but I feel like we could do more to explore this separation (not in this PR, later on, clarified in the last paragraph)

re naming, you could maybe go with renaming the current `RowSource` interface to be `RowMetadataSource` (or `MetadataRowSource`) and `SimpleRowSource` becomes `RowSource`.

I also am not convinced you need `RowSourceInput` (I think you can achieve the same thing reusing `SimpleRowSource`).

I think embedding ProcessorBase does not make sense to me anymore (processors reference processorbase as well as passing themselves in to be referenced in return). The idea is a good one but it seems to me like we're sticking too much into it. I think we should consider splitting `ProcessorBase` into two different things:
1) Common struct members & (hopefully little-to-no) functionality that is necessary for a processor to execute its specific purpose. This should be embedded (e.g. memory monitor) (a la joinerBase, but more general and lightweight).
2) A struct that represents a group of processors, sort of similar to how we are thinking of grouping columnar operators into a processor. This would allow us to extract processor functionality that is not necessary for it to execute its specific purpose (e.g. metadata, consumerdone behavior, etc..). It would also avoid allocating a processor base struct per processor.

This struct would implement the actual `RowSource` (with metadata) interface and processors that need to generate metadata (I believe that most processors do not) would implement a generate metadata method that would be called by this struct after `nil, nil` is returned by the last processor in the chain and passed on. This chain would be broken only when doing hash routing or reading from the network. This would also be a good opportunity to simplify processor construction by removing post, output, processorID from most of the constructor signatures. I want to give this idea more thought as it might not be a good one but I feel like this separation can be explored further.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-:-LMmNnc49q7pPAEGFmKZ:b-e617ih)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/base.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmHtoQBb1YTNTjE5Kt:-LMmHtoQBb1YTNTjE5Ku:b-cm8d68) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L227)):*
> ```Go
> //           // encouraged to just use MoveToDraining() for uniformity; DrainHelper()
> //           // will transition to stateTrailingMeta() quickly.
> //           p.MoveToDraining(nil /* err */)
> ```

Do you still need the `MoveToDraining` call here? I see that you just return nil, nil in `Distinct`
___
*[pkg/sql/distsqlrun/base.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMn7c6Y0ETcVggRzrSn:-LMn7c6Y0ETcVggRzrSo:b9tkrwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L233)):*
> ```Go
> //       }
> //
> //       return outRow, nil
> ```

`s/outRow/row/` I believe
___
*[pkg/sql/distsqlrun/base.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmPMbh4_qTEsu4W2VF:-LMmPMbh4_qTEsu4W2VG:bse6ld8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L244)):*
> ```Go
> //
> type SimpleRowSource interface {
> 	RowSource
> ```

I think eventually we would want to embed `SimpleRowSource` in `RowSource` instead of having it this way (`SimpleRowSource` implementations shouldn't need to implement `RowSource`) but it's hard to do it now because all `RowSource`s would have to implement `SimpleRowSource`. I would leave a TODO.
___
*[pkg/sql/distsqlrun/base.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmQM3b2ZjazKYdloUO:-LMmQM3b2ZjazKYdloUP:bap3q0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L252)):*
> ```Go
> // shouldn't be implemented by Processor code - it's designed to be used by
> // Processors that implement the SimpleRowSource interface with help from
> // ProcessorBase. The inputs to SimpleRowSource implementors should be wrapped
> ```

Why not just use the `SimpleRowSource` interface?
___
*[pkg/sql/distsqlrun/distinct.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmUpdM486HzpLqPjvG:-LMmUpdM486HzpLqPjvH:b-cad5w7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/distinct.go#L38)):*
> ```Go
> 
> 	input            RowSourceInput
> 	statCollector    *InputStatCollector
> ```

Why do we need this? Could you cast input to a `RowSource` when passing to `getInputStats` instead?
___
*[pkg/sql/distsqlrun/noop.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmVDzI4kj_YRtR7zGw:-LMmVDzI4kj_YRtR7zGx:bzhrwc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/noop.go#L66)):*
> ```Go
> func (n *noopProcessor) SimpleNext() (sqlbase.EncDatumRow, error) {
> 	// noop - just pass row through.
> 	return n.input.NextFromInput(), nil
> ```

:heart_eyes: 
___
*[pkg/sql/distsqlrun/processors.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2-XXAqE2a2cxQRE3:-LMmX2D69E_B6HcQhbOh:b-bsdjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L824)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This might not matter but it seems like trailing metadata used to only be returned during `stateTrailingMeta`. Are we ok with changing that?
</blockquote></details>

I think these `trailingMeta` lines are not needed. `MoveToDraining` will move us out of `StateRunning` so we hit `DrainHelper` on subsequent `Next` calls.

**Review by jordanlewis — COMMENTED** [review]
I'll rename the interfaces as you both suggested. `RowSource` will become `RowMetadataSource`, `SimpleRowSource` will become `RowSource`, `Next` will become `NextRowOrMeta`, `NextFromInput` will remain, and `SimpleNext` will become `Next`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-:-LMnBV8X7_aAbiHU5u88:b-f17da8)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/base.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmHtoQBb1YTNTjE5Kt:-LMnAEKX3G2JlSMce0qp:b-p5t8t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L227)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you still need the `MoveToDraining` call here? I see that you just return nil, nil in `Distinct`
</blockquote></details>

Nope, good point!
___
*[pkg/sql/distsqlrun/base.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMn7c6Y0ETcVggRzrSn:-LMnANtj9K34eKWYG8mg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L233)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/outRow/row/` I believe
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/base.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmPMbh4_qTEsu4W2VF:-LMnAP4i4vpiL_mzZGYJ:br8xzc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L244)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think eventually we would want to embed `SimpleRowSource` in `RowSource` instead of having it this way (`SimpleRowSource` implementations shouldn't need to implement `RowSource`) but it's hard to do it now because all `RowSource`s would have to implement `SimpleRowSource`. I would leave a TODO.
</blockquote></details>

They currently do need to implement `RowSOurce` because of some other methods that `RowSource` provide. I'm not sure what the TODO will say. I think this is all going to change relatively soon if we adopt your good ideas about having a chain of rowsources managed by some kind of processorbase, so it'll be fine to leave it alone i think.
___
*[pkg/sql/distsqlrun/base.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmQM3b2ZjazKYdloUO:-LMnAWAg3SnAgNgR34m-:b7cu0w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L252)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not just use the `SimpleRowSource` interface?
</blockquote></details>

Because `RowSourceInput`s never return errors, and it's silly to force consumers of `RowSourceInput` to handle an error that will always be nil.
___
*[pkg/sql/distsqlrun/distinct.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmUpdM486HzpLqPjvG:-LMnAdl5C3GwpjtRK5j6:bquijv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/distinct.go#L38)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do we need this? Could you cast input to a `RowSource` when passing to `getInputStats` instead?
</blockquote></details>

`getInputStats` would need to learn to unwrap the RowSourceInput wrapper :(
___
*[pkg/sql/distsqlrun/processors.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2tCOE8ZT9GRISqz-:-LMnAscHEgIT5AQdVBUX:b-n0bu4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L531)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

When is this non-nil?
</blockquote></details>

Oops, this was a failed and forgotten experiment - i was trying to make sure metadata and rows got returned always in the same order, but gave up  - it's alittle tricky and not that important. Deleted.
___
*[pkg/sql/distsqlrun/processors.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2-XXAqE2a2cxQRE3:-LMnB6TP-BJ_jyVLppcq:b-my5dva) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L824)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think these `trailingMeta` lines are not needed. `MoveToDraining` will move us out of `StateRunning` so we hit `DrainHelper` on subsequent `Next` calls.
</blockquote></details>

This is necessary because of the way that `NextFromInput` on `rowSourceWrapper` forwards metadata to the `ProcessorBase`. If an upstream gives us metadata, we need to return it sooner than during the draining phase. The `ProcessorBase` is now responsible for actively listening to incoming metadata that got set from its inputs, which gets added to trailingMeta via `AppendTrailingMetadata`.

**Review by jordanlewis — COMMENTED** [review]
Actually, renaming `RowSource` and `Next` is going to make a huge diff. What if we left them until we finished converting all of the processors to use `SimpleNext`? In the meantime, I renamed `RowSourceInput` to be `SimpleInput`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-:-LMnFm0iC3OLUTcVXpCC:b-ktw8wv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30271)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/base.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMmQM3b2ZjazKYdloUO:-LNBlv8YAeWchBy9jH6m:b-cedo5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/base.go#L252)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Because `RowSourceInput`s never return errors, and it's silly to force consumers of `RowSourceInput` to handle an error that will always be nil.
</blockquote></details>

But you avoid the overhead of having to think about another interface. Up to you.
___
*[pkg/sql/distsqlrun/processors.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30271#-LMh2-XXAqE2a2cxQRE3:-LNBpJAF3rU3tSWDYwqm:b-owdl00) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d3236dcd601ca90d8e76dbdda057b747c7f6a05/pkg/sql/distsqlrun/processors.go#L824)):*
> If an upstream gives us metadata, we need to return it sooner than during the draining phase

Why? My assumption is that the ordering of metadata relative to rows does not matter so if there is non-err metadata to forward (err would put us into draining) it's fine to wait until draining.

**Comment by RaduBerinde** [comment]
This definitely cleans up some tedious and error-prone logic.

I would run a quick benchmark to see if there are any regressions (due to another per-row virtual call).

Tracing the logic might be difficult for folks trying to understand this code for the first time. Consider an alternate version where each processor still implements `Next` but that just calls out to a `ProcessorBase.nextHelper` which takes simpleNext as a func argument. This costs some extra indentation in the code but makes what's going on more explicit (and might also be faster, not sure).

**Comment by jordanlewis** [comment]
Good idea @RaduBerinde - i'm going to make a benchmark that tests this soon.

Just want to jot down that #30819 and other bugs like it would be prevented by an approach like this PR. We've seen other bugs just like that one - it would be good to remove the possibility of such a thing.

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=30271) it.</sub>

**Pull request closed without merging**
