### PR TITLE
sql: Remove excessive allocation in upsert conflict index enumeration

### LINKED ISSUE #26367: sql: the UPSERT/INSERT ON CONFLICT index lookup allocates excessively
This code in `sql/upsert.go`

```go
       for _, index := range tableDesc.Indexes {
               if indexMatch(index) {
                       return onConflict.Exprs, &index, nil
```

forces a heap copy of the item from `tableDesc.Indexes`

Instead, a direct reference to that item could be returned.

### PR DESCRIPTION
**Pull request by emsal0**
Release note: none

closes #26367

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/upsert.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26591#-LEjOKpu-9qQjQvFAtTm:-LEjOKpv0-F7iIs576R5:b-cxruq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a6daba616709a07f2bbb0467f9d0d72a6915d0/pkg/sql/upsert.go#L766)):*
> ```Go
> 	}
> 	for i := range tableDesc.Indexes {
> 		index := tableDesc.Indexes[i]
> ```

This does not change the allocation behavior. You should double check Go's semantics and/or use the "goescape" script that Nathan documented on the wiki ( https://github.com/cockroachdb/cockroach/wiki/Rando-scripts )

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26591)*

**Comment by knz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/upsert.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26591#-LEjOKpu-9qQjQvFAtTm:-LEjOiHc6vQr5rOUZ3RQ:b-s6qabe) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a6daba616709a07f2bbb0467f9d0d72a6915d0/pkg/sql/upsert.go#L766)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This does not change the allocation behavior. You should double check Go's semantics and/or use the "goescape" script that Nathan documented on the wiki ( https://github.com/cockroachdb/cockroach/wiki/Rando-scripts )
</blockquote></details>

To be specific, the problem here is that you are defining `index` as a new copy, and that copy is then set to escape below. The escape of the copy causes an additional heap alloc. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26591)*

**Comment by emsal1863** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/upsert.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26591#-LEjOKpu-9qQjQvFAtTm:-LEjVC980KPX5U51JqTQ:b-tg80xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a6daba616709a07f2bbb0467f9d0d72a6915d0/pkg/sql/upsert.go#L766)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

To be specific, the problem here is that you are defining `index` as a new copy, and that copy is then set to escape below. The escape of the copy causes an additional heap alloc. 
</blockquote></details>

Should `tableUpserter` still take a `*IndexDescriptor` or should that also be changed to `IndexDescriptor` to avoid any other escapes?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26591)*

**Comment by emsal1863** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/upsert.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26591#-LEjOKpu-9qQjQvFAtTm:-LEjVTz8A6Zmcl_4FhnY:b-vszcu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a6daba616709a07f2bbb0467f9d0d72a6915d0/pkg/sql/upsert.go#L766)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Should `tableUpserter` still take a `*IndexDescriptor` or should that also be changed to `IndexDescriptor` to avoid any other escapes?
</blockquote></details>

Sorry, my mistake - `conflictIndex` field in `tableUpserter` is just an `IndexDescriptor`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26591)*

**Comment by knz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/upsert.go, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26591#-LEjOKpu-9qQjQvFAtTm:-LEjWflr8dDIvbhKqwi8:b-mz85fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a6daba616709a07f2bbb0467f9d0d72a6915d0/pkg/sql/upsert.go#L766)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Sorry, my mistake - `conflictIndex` field in `tableUpserter` is just an `IndexDescriptor`.
</blockquote></details>

Think about it the other way: if you return a pointer to something that is already on the heap, then no extra allocation is needed. This is the change needed here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26591)*

**Review by knz — APPROVED** [review]
thanks !

**Comment by knz** [comment]
don't forget to squash and clean up the commit message

**Comment by knz** [comment]
:+1: thanks!

**Pull request merged**
