### PR TITLE
sql: fix two bugs with TRUNCATE

### PR DESCRIPTION
**Pull request by vivekmenezes**
sql: correctly resolve schema mutations during TRUNCATE
related to #27687

sql: mark schema change job as successful when table DROP/TRUNCATE
The job is modified in the same transaction as the user's DROP/TRUNCATE transaction.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
First two commits :lgtm_strong: .

Last commit: :lgtm: on principle, I like the idea to cancel ongoing jobs. However I recommend to actually stop the jobs with an error message that says "table was dropped" so that the reason can be inspected with SHOW JOBS. 

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-:-LK3P6lg9PIQwqo1plUg:bl1lvoe)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3OCyk88CoSFi5kxNE:-LK3OCyk88CoSFi5kxNF:b-8gulf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L359)):*
> ```Go
> 	}
> 
> 	// Mark all jobs scheduled for schema changes as successful.
> ```

Just for clarity: can you extend the commit message and the PR description to explain this new behavior, and outline at a high level:

- what happens if the DROP is aborted (e.g. its txn is rolled back) -- what happens with these jobs?
- what happens if the DROP is retried -- what happens with the jobs?
- what happens if a user uses AS OF SYSTEM TIME or a restore in-between the time the schema change jobs were issued, and the time where DROP was issued.
___
*[pkg/sql/drop_table.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3Ox4U81gb7foMB7Gv:-LK3Ox4U81gb7foMB7Gw:b70qrqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L372)):*
> ```Go
> 				return err
> 			}
> 			if err := job.WithTxn(p.txn).Succeeded(ctx, jobs.NoopFn); err != nil {
> ```

Maybe instead fail the job with an error that says "table has been dropped". This way the reason why the job was stopped becomes clear in the event log / SHOW JOBS.

**Review by vivekmenezes — COMMENTED** [review]
Thanks for review this.

The code path can be executed via TRUNCATE and DROP.  In the case of TRUNCATE the schema changes were short circuited and indeed finished. In the case of DROP, the table has been dropped so one argue those schema changes were short circuited to and completed. I suppose one can ask, is there an action the user can take if there saw the extra message, or would they find it uncomfortable to see the schema change complete?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-:-LK4F4690CyJmb4ycBWn:btrngiv)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3OCyk88CoSFi5kxNE:-LK4G00Y6g2A3A6t6D0C:b-ajnt61) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L359)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Just for clarity: can you extend the commit message and the PR description to explain this new behavior, and outline at a high level:

- what happens if the DROP is aborted (e.g. its txn is rolled back) -- what happens with these jobs?
- what happens if the DROP is retried -- what happens with the jobs?
- what happens if a user uses AS OF SYSTEM TIME or a restore in-between the time the schema change jobs were issued, and the time where DROP was issued.


</blockquote></details>

Added a comment to the PR saying that the change to jobs table is done in the same txn. The AS OF SYSTEM TIME question seems to be irrelevant to this PR.

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3Ox4U81gb7foMB7Gv:-LK4J_poE-3mEOentsNx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L372)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe instead fail the job with an error that says "table has been dropped". This way the reason why the job was stopped becomes clear in the event log / SHOW JOBS.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
Yes my point in my previous comment is that if the job gets aborted because the table is dropped, this is not a normal schema change completion. 

If a schema change is marked to have completed successfully, then there exists a point in time which the user can use with AS OF SYSTEM TIME to go and observe the data just after the schema change has completed.

If you make the job table lie about the completion (by marking the job as completed whereas the change did not, in fact, complete), then the user who uses AS OF SYSTEM TIME to go to the end of the job will see incorrect/invalid/incomplete data in their database.

This is why I think it is important to mark the job as failed and not succeeded.

> Reviewed 6 of 6 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-:-LK4Pa1p--OKowFK2kUk:b-vblan5)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3OCyk88CoSFi5kxNE:-LK4POz31C0KdNNTYKAf:b6zo042) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L359)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Added a comment to the PR saying that the change to jobs table is done in the same txn. The AS OF SYSTEM TIME question seems to be irrelevant to this PR.
</blockquote></details>

Where is the comment?
I was thinking to paste it at the top of the PR (in the first description) because this is the text that gets copied to the git log. Comments below that do not go to the git log.
___
*[pkg/sql/drop_table.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3Ox4U81gb7foMB7Gv:-LK4PMWe2bdNeTkhg-T0:by8pr4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L372)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a change?

**Review by vivekmenezes — COMMENTED** [review]
Thanks for taking the time to review this and I appreciate your comments.

Well what I'm saying is that the job is marked successful when the schema change has completed. The job has a timestamp at which it was marked successful. If you use AS OF SYSTEM TIME before that time you should not expect the schema change to have been completed. If you use a timestamp after that you can expect 1. The schema change complete on a TRUNCATE table, or  2. The schema change complete on a DROP table (which has no schema by definition).

If there is some confusion in this matter it's worthy to consider 1. that this set of events happens rarely, and 2. when it does happen is there really going to be confusion.

Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-:-LK6zxOECdgKK8teYVpu:b-sq6mo9)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3OCyk88CoSFi5kxNE:-LK7001V-nTZnZQfbe2l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L359)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Where is the comment?
I was thinking to paste it at the top of the PR (in the first description) because this is the text that gets copied to the git log. Comments below that do not go to the git log.
</blockquote></details>

Done.
___
*[pkg/sql/drop_table.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3Ox4U81gb7foMB7Gv:-LK703m3353pmksMdt3x:b-2xbsr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L372)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't see a change?
</blockquote></details>

I'm arguing against this change.

**Comment by vivekmenezes** [comment]
@knz do you have any thoughts on this PR? Thanks!

**Review by knz — COMMENTED** [review]
You still have me on record that if a schema change is *aborted* by a DROP, then it should be marked as aborted not completed. 

But in the end this is a subjective argument from the perspective of UX, not a correctness argument. So your guess is probably as good as mine.

I have approved the PR already so feel free to move forward.

> Reviewed 5 of 6 files at r8, 2 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-:-LKx3-rM7KGpOqFfnWd_:bco91gt)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/drop_table.go, line 372 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28721#-LK3Ox4U81gb7foMB7Gv:-LKx2wXiD2Tz2bYPVolk:bgg86o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/066917ea2c85b1f8d32000e8de2a496c4c9825b8/pkg/sql/drop_table.go#L372)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'm arguing against this change.
</blockquote></details>

I was confused by the word "Done".

**Comment by vivekmenezes** [comment]
Thank you for the review!

**Pull request merged**
