### PR TITLE
ui: fix default value of filter to All

### PR DESCRIPTION
**Pull request by maryliag**
A recent commit changed the default value of filter
to be an empty string, but we do have transactions that have
no associated app names to it, so All and empty string
should be treated as different cases. This commit reverse
that changes and use All

Release note (bug fix): Show All statements when filter All is
selected and not only the ones with empty string

### CODE REVIEW

**Review by matthewtodd — COMMENTED** [review]
Looks like the bug was introduced in response to [this comment](https://github.com/cockroachdb/cockroach/pull/71175#pullrequestreview-773907792) about `?app=all` not working in the query string. Does this change preserve the desired behavior there?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71567#-:-MlzJPlq5F-RlK30Ycf-:b-qnciit)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by maryliag — COMMENTED** [review]
yes, the issue with the comment was that if you pass "all" it doesn't return results, but using "All" or null works, as long as we don't use empty string

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71567#-:-MlzMqnZ7Dk1HQJB5jQd:b-d5zsns)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71567#-:-MlzNu4DApH6SlioICPp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by Azhng — APPROVED** [review]

**Pull request merged**
