### PR TITLE
telemetry: add FIPS-specific channel

### PR DESCRIPTION
**Pull request by rail**
Previously, all official builds were reporting using the same telemetry channel.

This PR adds an new telemetry channel for the FIPS build target.

Fixes: CC-24110
Epic: DEVINF-478
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
thank you

**Comment by rail** [comment]
bors r=knz

**Comment by rail** [comment]
@knz something tells me that I less care about backporting this to 22.2... What do you think?

**Comment by knz** [comment]
> @knz something tells me that I less care about backporting this to 22.2... What do you think? 

what's your reasoning?

**Comment by rail** [comment]
Because we treat 22.2 as an experimental branch for FIPS.

**Comment by knz** [comment]
let's ask abhinav for input. he's the consumer of the telemetry data after all.

**Pull request merged**
