### PR TITLE
sql: don't reinitialize the entire planner and evalcontext every time

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: improve query cache benchmark

Extending BenchmarkQueryCache to support multiple issuing methods.

Release note: None

#### sql: don't reinitialize the entire planner and evalcontext every time

A nontrivial time is spent doing `resetPlanner` because it populates a
ton of fields. Most of these fields can be set once. This change
splits the function into an `initPlanner` to be called once and a
`resetPlanner` to be called before every query.

This also fixes a bug where the query cache session info was being
reset on every query, defeating the mechanism to tone down the caching
when the hit rate is low.

Finally, this sets us up for a follow-up change which will reuse the
opt catalog (and its cached objects) across queries.

```
name                                               old time/op  new time/op  delta
QueryCache/small/clients-1/simple/cache-off         361µs ± 2%   362µs ± 2%    ~     (p=0.478 n=11+11)
QueryCache/small/clients-1/simple/cache-on          285µs ± 3%   285µs ± 2%    ~     (p=0.843 n=12+12)
QueryCache/small/clients-1/prepare-once/cache-off   306µs ± 4%   301µs ± 2%  -1.72%  (p=0.033 n=12+12)
QueryCache/small/clients-1/prepare-once/cache-on    306µs ± 4%   302µs ± 2%    ~     (p=0.266 n=12+12)
QueryCache/small/clients-1/prepare-each/cache-off   502µs ± 3%   502µs ± 3%    ~     (p=0.833 n=11+12)
QueryCache/small/clients-1/prepare-each/cache-on    446µs ± 4%   434µs ± 2%  -2.60%  (p=0.006 n=12+12)
QueryCache/large/clients-1/simple/cache-off         373µs ± 3%   375µs ± 3%    ~     (p=0.525 n=12+11)
QueryCache/large/clients-1/simple/cache-on          407µs ± 3%   408µs ± 5%    ~     (p=0.755 n=12+12)
QueryCache/large/clients-1/prepare-once/cache-off   313µs ± 2%   307µs ± 1%  -1.94%  (p=0.000 n=11+12)
QueryCache/large/clients-1/prepare-once/cache-on    313µs ± 2%   306µs ± 1%  -2.30%  (p=0.000 n=11+12)
QueryCache/large/clients-1/prepare-each/cache-off   514µs ± 3%   509µs ± 4%    ~     (p=0.219 n=12+12)
QueryCache/large/clients-1/prepare-each/cache-on    454µs ± 2%   440µs ± 2%  -2.96%  (p=0.000 n=11+12)
```

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-:-LZgLve7AhPsd9MWJGL5:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/conn_executor.go, line 1804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgJOgg4xX_IkDEaiPj:-LZgJOgg4xX_IkDEaiPk:bibpn8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/conn_executor.go#L1804)):*
> ```Go
> // same across multiple statements. resetEvalCtx must also be called before each
> // statement, to reinitialize other fields.
> func (ex *connExecutor) initEvalCtx(ctx context.Context, p *planner, evalCtx *extendedEvalContext) {
> ```

nit: make the evalCtx the 2nd param
___
*[pkg/sql/conn_executor.go, line 1840 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgLMiY-Oye_cesZxLQ:-LZgLMiZC4Gi604aGuB4:bw1n3yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/conn_executor.go#L1840)):*
> ```Go
> }
> 
> // evalCtx creates an ExtendedEvalCtx corresponding to the current state of the
> ```

this comment seems stale, and also the reference to the planner below
___
*[pkg/sql/conn_executor.go, line 1851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgLgLf8ZJFSczf9iut:-LZgLgLf8ZJFSczf9iuu:bvrl3mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/conn_executor.go#L1851)):*
> ```Go
> // shouldn't be reused across statements.
> func (ex *connExecutor) resetEvalCtx(
> 	txn *client.Txn, stmtTS time.Time, evalCtx *extendedEvalContext,
> ```

make `evalCtx` the first arg
___
*[pkg/sql/internal.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgKR9j5nSBRnPErZ8O:-LZgKR9j5nSBRnPErZ8P:b-6n07c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/internal.go#L147)):*
> ```Go
> }
> 
> // CopySessionData populates the session data for an internal executor.
> ```

maintain the comment about how the copy is needed so that this executor doesn't update the parent session somewhere.
Conversely, I don't remember why it'd be bad to update the parent session... So maybe we can just get rid of this copying, and the session data can be shared with the parent, and at that point maybe this method doesn't need to exist any more and `sessionData` can be passed to the constructor again.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35217)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor.go, line 1840 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgLMiY-Oye_cesZxLQ:-LZjpEt_3euB6q5XYhTO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/conn_executor.go#L1840)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment seems stale, and also the reference to the planner below
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 1851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgLgLf8ZJFSczf9iut:-LZjq2M_EpG3e3cVAyR3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/conn_executor.go#L1851)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

make `evalCtx` the first arg
</blockquote></details>

Done.
___
*[pkg/sql/internal.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgKR9j5nSBRnPErZ8O:-LZjq3WCEXcL3GPuF_CF:beiydqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/internal.go#L147)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maintain the comment about how the copy is needed so that this executor doesn't update the parent session somewhere.
Conversely, I don't remember why it'd be bad to update the parent session... So maybe we can just get rid of this copying, and the session data can be shared with the parent, and at that point maybe this method doesn't need to exist any more and `sessionData` can be passed to the constructor again.
</blockquote></details>

I switched to sharing the sessionData directly. Things seem to work but the comment said that we would also need to share a `sessionDataMutator` if we do this?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35217)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/internal.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35217#-LZgKR9j5nSBRnPErZ8O:-LZk3Uwh6LQ7Ea_KLGMu:b-vdd84n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2565e8206fb80ae31aaa196a1aee03c3d231a0d7/pkg/sql/internal.go#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I switched to sharing the sessionData directly. Things seem to work but the comment said that we would also need to share a `sessionDataMutator` if we do this?
</blockquote></details>

I reverted to copying since that change escalates quickly.

**Pull request merged**
