### PR TITLE
release-23.1: roachprod: add DNS support for services

### PR DESCRIPTION
**Pull request by herkolategan**
Backport 1/1 commits from #106497.

/cc @cockroachdb/release

---

This change lays the foundation for adding DNS providers to `roachprod`. It is
required to be able to keep track of multiple services that are running on the
same VM. For example running multiple external SQL processes and a shared
process on the same VM. A service denotes a unit of functionality provided on a
set of given hosts and ports(i.e., a singular service can be served by multiple
VMs)

An implementation for local clusters is introduced as well as an interface for
managing DNS records. The local implementation does not use true DNS services,
but emulates it through local storage. This is to avoid the complexities of a
per operating system implementation for local-only DNS resolution. The feature
is currently disabled for cloud clusters. Once a DNS cloud provider
implementation is completed for the interface the feature can be enabled more
widely.

Each VM is required to have a public DNS name for the services functionality to
function. The typical layout of DNS records for services pertaining to a cluster
will look as follows:

`_<tenant>-<service_type>._<proto>.<cluster>.<dns_zone> -> host:port`
For example:
```
_system-sql._tcp.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (26257)
_system-sql._tcp.cluster-name.roachprod-managed.crdb.io -> cluster-name-0002.roachprod.crdb.io : sql port (26257)
_system-sql._tcp.cluster-name.roachprod-managed.crdb.io -> cluster-name-0003.roachprod.crdb.io : sql port (26257)
```

When multiple tenants are running on the same VM (0001) the records will take this form:
```
_tenant1-sql._tcp.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (29001)
_tenant2-sql._tcp.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (29002)
```
Note the DNS SRV records here point to the same host, but different ports.

Services will also need to find open ports on VMs when multiple services are
running on the VM to avoid a port collision. To facilitate this a new script has
been added to scan for open ports given a starting port. Having nondeterministic
ports introduces a dependency on the DNS service to be able to determine which
services are running on which ports.

Providers are currently not required to provide a DNS implementation, nor are
VMs required to specify a DNS Provider. The VM functions that invoke DNS
operations are lenient in order to allow falling back to default service-less
topologies. For now a fallback is provided to supply the default ports if no DNS
provider is present.

It is now possible to specify ports for SQL and UI services via `StartOpts`.
These ports are used when registering DNS records against a DNS provider. This
provides the functionality to not only start external service processes on
different ports, but the host cluster as well. To facilitate this the port
resolution is done prior to starting a cluster, as nodes need the information
beforehand to be able to join the cluster.

A few things are not covered in this change:
1. The `roachprod` log and stop commands need revisiting to support more than
one process on a single VM.
2. Implementations of the DNS interface for a cloud provider.
3. Update all areas where connection information is assumed rather than queried.

Epic: [CRDB-18499](https://cockroachlabs.atlassian.net/browse/CRDB-18499)
Release note: None
Release justification: Test only change

### CODE REVIEW

**Comment by renatolabs** [comment]
Thanks for doing this! Were there a lot of conflicts? Do you think it's worth running a very small build on this branch?

**Comment by herkolategan** [comment]
> Thanks for doing this! Were there a lot of conflicts? Do you think it's worth running a very small build on this branch?

Had the same thought, I will start a small run.

**Comment by herkolategan** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11416612
Select prob = 0.1

**Comment by herkolategan** [comment]
TC run (prob=0.1): https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11447074
Cluster creation failure at one point:
```
Unable to create (or reuse) cluster for test restore/tpce/400GB/aws/nodes=9/cpus=8/zones=us-east-2b,us-west-2b,eu-west-1b due to: in provider: gce: Command: gcloud [compute instances create --subnet default --scopes cloud-platform --image ubuntu-2004-focal-v20210603 --image-project ubuntu-os-cloud --boot-disk-type pd-ssd --service-account 21965078311-compute@developer.gserviceaccount.com --maintenance-policy MIGRATE --create-disk type=pd-ssd,size=1000GB,auto-delete=yes --machine-type n2-standard-8 --labels usage=roachtest,lifetime=12h0m0s,arch=amd64,created=2023-08-23t00_44_25z,roachprod=true,cluster=teamcity-11447074-1692741896-56-n9cpu8-geo --metadata-from-file startup-script=/tmp/gce-startup-script2437441013 --project cockroach-ephemeral --boot-disk-size=32GB --zone us-east-2b teamcity-11447074-1692741896-56-n9cpu8-geo-0001 teamcity-11447074-1692741896-56-n9cpu8-geo-0002 teamcity-11447074-1692741896-56-n9cpu8-geo-0003]
[00:45:00 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11447074?buildTab=log&focusLine=5934&logView=flowAware&linesState=5934)  Output: ERROR: (gcloud.compute.instances.create) Could not fetch resource:
[00:45:00 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11447074?buildTab=log&focusLine=5935&logView=flowAware&linesState=5935)   - Permission denied on 'locations/us-east-2b' (or it may not exist).: exit status 1.
```

**Review by renatolabs — APPROVED** [review]

**Pull request merged**
