### PR TITLE
sql: include KV regions information

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adjusts "regions" field of EXPLAIN ANALYZE output to include regions of KV nodes too. In the past, this has been a source of confusion since only regions of SQL instances were included. It is done in a similar manner to how we added KV node IDs recently - by extending ScanStats proto and asking the KV server to populate the new field.

Since this has caused confusion in the past, and we're updating the contents of existing field, I'll mark it as bug fix.

Informs: #91774.
Epic: None

Release note (bug fix): "Regions" field of EXPLAIN ANALYZE output has been fixed to include regions of KV nodes (previously, only regions of SQL nodes involved in query processing were included).

### CODE REVIEW

**Comment by yuzefovich** [comment]
My thinking about KV nodes vs SQL nodes and KV regions and SQL regions: it seems to me what separating out KV node from SQL nodes can be quite useful (for example, it highlights the distributed nature of the database even when "local SQL execution" is chosen) - this is why in the other PR I introduced a separate field / separate column; at the same time, I don't see much value from separating KV regions from SQL regions, and that's why I'm updating the existing field / column to include both SQL and KV regions and treating this as a "bug fix". Thoughts?

**Comment by DrewKimball** [comment]
> I don't see much value from separating KV regions from SQL regions, and that's why I'm updating the existing field / column to include both SQL and KV regions and treating this as a "bug fix". Thoughts?

This makes sense to me.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124888#-:-NzB3ZufAT-CFztuwG9I:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Added updating `Regions` field in `MakeDeterministic` just to be safe.

TFTR!

bors r+

**Pull request merged**
