### PR TITLE
builtins: improve performance of has_table_privilege and has_column_privilege

### LINKED ISSUE #65551: sql: has_column_privilege makes graphile introspection query slow
Graphile uses this big introspection query: https://gist.githubusercontent.com/benjie/914776880c85d2ac7a3c260e08aa29b7/raw/b3993e17e4c56999c7470452a7a401437db2b2ac/introspection_query_cut_down_for_cockroach.sql

With #65550 this query now runs but it takes a very long time (20-30s).

I have narrowed the problem (or at least a problem) to the `attribute_partial` CTE; in particular the use of `has_column_privilege`:
```
      exists(select 1 from accessible_roles where has_column_privilege(accessible_roles.oid, att.attrelid, att.attname, 'SELECT')) as "aclSelectable",
      exists(select 1 from accessible_roles where has_column_privilege(accessible_roles.oid, att.attrelid, att.attname, 'INSERT')) as "aclInsertable",
      exists(select 1 from accessible_roles where has_column_privilege(accessible_roles.oid, att.attrelid, att.attname, 'UPDATE')) as "aclUpdatable",
```
It looks like every single evaluation of this function internally spawns multiple internal queries! The optimizer is trying to decorrelate and creates nested joins, with these expressions pushed down (which is making the problem worse). But even a manual rewrite that keeps these at the top is still pretty slow: https://gist.github.com/RaduBerinde/51a348331e5a019e2c25dbf3c4be7241#file-graphile-1-sql

We can pull on two threads here:
 - how can we make `has_column_privilege` faster?
 - is there a better way to obtain the information that this query is trying to obtain?

CC @rafiss @jordanlewis 

Epic CRDB-2410

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details

Resolves #65551

### CODE REVIEW

**Review by RichardJCai — APPROVED** [review]
LGTM mod nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65766#-:-Mb7J5ytB5NRnUmdijwz:bi1l8pr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @otan, and @rafiss)

___
*[pkg/sql/resolver.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65766#-Mb7Fo3P0J9BFoOgvgRh:-Mb7Fo3P0J9BFoOgvgRi:bhaqvnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff36a80b2d8e123c75488fb2d623897aa266c2a3/pkg/sql/resolver.go#L336)):*
> ```Go
> 	hasPrivilege := func(priv privilege.Kind) bool {
> 		for _, role := range allRoles {
> 			for _, pu := range privilegeDesc.Users {
> ```

I think we can call `privilegeDesc.CheckPrivilege` here
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65766#-Mb7IljS5NxysK0lWDQG:-Mb7IljS5NxysK0lWDQH:b-qxu8qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f217f8337ebb194cffe3b7dca68d7763c2e5d24/pkg/sql/sem/builtins/pg_builtins.go#L1333)):*
> ```Go
> 				return nil, err
> 			}
> 			colArg := tree.UnwrapDatum(ctx, args[1])
> ```

Can we leave a similar comment to before stating that the column arg is only checked to see if the column exists in the table?
Makes it more clear that we're still only checking the table for privileges.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @otan, @rafiss, and @RichardJCai)

___
*[pkg/sql/resolver.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65766#-Mb7Fo3P0J9BFoOgvgRh:-Mb8Zraz7lZn_786q1PR:b-zdqapk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff36a80b2d8e123c75488fb2d623897aa266c2a3/pkg/sql/resolver.go#L336)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think we can call `privilegeDesc.CheckPrivilege` here
</blockquote></details>

i changed it, but it revealed (what i think is a) bug. can you re-check the last commit?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @RichardJCai)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1333 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65766#-Mb7IljS5NxysK0lWDQG:-Mb8acbk50baq5pSEzUN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f217f8337ebb194cffe3b7dca68d7763c2e5d24/pkg/sql/sem/builtins/pg_builtins.go#L1333)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Can we leave a similar comment to before stating that the column arg is only checked to see if the column exists in the table?
Makes it more clear that we're still only checking the table for privileges.
</blockquote></details>

Done.

**Review by RichardJCai — APPROVED** [review]

**Comment by otan** [comment]
bors r=richardjcai

**Pull request merged**
