### PR TITLE
logictest: randomize distsql_workmem in all configs

### LINKED ISSUE #77645: sql: randomize distsql_workmem value more
Randomizing the value of `distsql_workmem` variable would increase the test coverage, in particular it would be interesting for the ongoing `Streamer` work. I think a combination of `fakedist` logic test mode with this randomization could be quite powerful.

Jira issue: CRDB-13692

### PR DESCRIPTION
**Pull request by yuzefovich**
**logictest: clean up filters in queries of events**

This commit cleans up queries that check the contents of `settings` and
`eventlog` system tables (there, we want to ignore some of the
non-default cluster setting values). Additionally, this commit removes
an empty file introduced in 28ed7d0b8a128f1de4d4d5d33059a4556f8cdd65.

Release note: None

**logictest: randomize distsql_workmem in all configs**

This commit makes it so that `sql.distsql.temp_storage.workmem` cluster
setting is randomized in `[10KiB, 100KiB)` range in every config with
50% probability. This increases test coverage. Note that `*-disk`
configs use a different knob, so they are still useful to keep. The
randomization is only disabled for opt logic tests.

This required changing the way we handle small limits in the windower
(there, we used to return an error if there isn't enough workmem budget,
and we silently bump it up to the minimum - this is what we already do
for the join reader) as well as minor cleanups to the logic tests.

Fixes: #77645.

Release note: None

Jira issue: CRDB-14802

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm relatively confident that this should not be flakey - I ran the CI a couple of times with the hard-coded lowest possible value. SQL lite logic test should also be ok time-wise since we already run it with `fakedist-disk` config that should be slower than randomized workmem thing, but it's possible that sqllite logic tests will start to time out, we'll see.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-:-Mzvtit68Yn-54agQvxk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/rowexec/windower.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzvtcSSCne7IfH3gKbb:-MzvtcSSCne7IfH3gKbc:b-yu5w3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/rowexec/windower.go#L149)):*
> ```Go
> 	if limit < memRequiredByWindower {
> 		// The limit is set very low, likely by the tests, but the windower
> 		// requires some amount of RAM, so we override the limit.
> ```

Would 10MB set by the randomize be too low? Might be worth mentioning that in the comment if so.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[pkg/sql/rowexec/windower.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzvtcSSCne7IfH3gKbb:-MzxDKGn4F60101yru-a:bz1n3w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/rowexec/windower.go#L149)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would 10MB set by the randomize be too low? Might be worth mentioning that in the comment if so.
</blockquote></details>

Are you referring to 10KiB, the lowest possible random value of random `workmem`? Which comment are you referring to?

I don't remember the details, but I picked 100KiB as the minimum required by windower. The reasoning was that it has some internal state that it cannot spill to disk. Originally, I made it return an error if `workmem` is too low; but I think it's better to silently bump it to the minimum required (we don't expect anyone in production to use such low values of `workmem`), as we do for the join reader.

**Review by cucaroach — COMMENTED** [review]
SQL lite logic test runs with crdb_test_off to be immune from metamorphics.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-:-MzyisVo8R8ickHBz1mv:b-5kprso)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by cucaroach — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/event_log, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzyjzzN8iPrZRuC7NQ-:-MzyjzzN8iPrZRuC7NQ0:bzafay0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/logictest/testdata/logic_test/event_log#L4)):*
> ```
> # distsql_workmem value is randomized, so we'll override it to the production
> # value.
> # TODO(yuzefovich): figure it out.
> ```

Interesting, missing rowsort?

**Review by yuzefovich — COMMENTED** [review]
This randomization (at least the way it is currently implemented) is agnostics of `crdb_test` flags, so it will apply to SQL lite logic tests too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-:-MzzVIVTCTXFLl3giVeV:bqnzrlk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/event_log, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzyjzzN8iPrZRuC7NQ-:-MzzVXRN35huhBzEnPjS:bp9jnyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/logictest/testdata/logic_test/event_log#L4)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Interesting, missing rowsort?
</blockquote></details>

No, it's not that. I don't remember exactly but some "events" are either added or missing. It's possible that low `distsql_workmem` value causes queries in this file to be slower, so there is enough time for new internal operations to execute, but I decided it wasn't worth digging into that.

**Comment by mgartner** [comment]
*[pkg/sql/rowexec/windower.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzvtcSSCne7IfH3gKbb:-MzzXI-S0nMcwFypUD7a:b-qf92xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/rowexec/windower.go#L149)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Are you referring to 10KiB, the lowest possible random value of random `workmem`? Which comment are you referring to?

I don't remember the details, but I picked 100KiB as the minimum required by windower. The reasoning was that it has some internal state that it cannot spill to disk. Originally, I made it return an error if `workmem` is too low; but I think it's better to silently bump it to the minimum required (we don't expect anyone in production to use such low values of `workmem`), as we do for the join reader.
</blockquote></details>

Sorry for the confusion. Yes, I meant 10KiB. I was referring to "The limit is set very low, likely by the tests,". It's not clear to me whether this means that it is likely set low explicitly by a test or by the metamorphic testing, or both.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-:-MzzZtCv6_FhtcWzza2h:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @mgartner)

___
*[pkg/sql/rowexec/windower.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzvtcSSCne7IfH3gKbb:-MzzZ5gu5zb5cTeFVSBi:b-rrmmpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/rowexec/windower.go#L149)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sorry for the confusion. Yes, I meant 10KiB. I was referring to "The limit is set very low, likely by the tests,". It's not clear to me whether this means that it is likely set low explicitly by a test or by the metamorphic testing, or both.
</blockquote></details>

I see. I don't think it matters much what kind of testing lowered the limit, but I added a bit more color to the comment.

**Comment by mgartner** [comment]
*[pkg/sql/rowexec/windower.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75759#-MzvtcSSCne7IfH3gKbb:-Mzza1zVDrIQIbaTht8s:b-qbxl94) ([raw file](https://github.com/cockroachdb/cockroach/blob/3120f2220b06ccd2b90a5224ff9e55b18d45842d/pkg/sql/rowexec/windower.go#L149)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I see. I don't think it matters much what kind of testing lowered the limit, but I added a bit more color to the comment.
</blockquote></details>

Looks great, thanks!

**Pull request merged**
