### PR TITLE
sql: add crdb_internal.set_vmodule, remove server.remote_debug.vmodule

### PR DESCRIPTION
**Pull request by tbg**
A cluster setting is impractical due to the inability to change it on a sufficiently broken cluster. Instead, use a SQL builtin that is only accessible to root.

Original message preserved below for posterity.

--

A cluster setting cannot be changed when the cluster is in a sufficiently bad state.
Vmodule is typically not useful unless the cluster is in a sufficiently bad state.

Consequently, allow vmodule by default. @nvanbenschoten and I were stopped in our tracks
while investigating #17524 today because of this.

Informs #17904, #16489.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
LGTM!! 🎉

**Comment by bdarnell** [comment]
Why is the solution to default this setting to on instead of just restarting the existing binaries with `--vmodule=whatever`? I'd argue that any production cluster should have remote vmodule setting disabled, so if the cluster is so hosed that the setting can't be changed, restarting the server should be the preferred solution.

**Comment by tschottdorf** [comment]
@bdarnell while I appreciate that opinion, it isn't particularly helpful -- while we're in a webex session debugging a stuck cluster and we have traced out the precise mapping of lease holders to nodes, etc, we don't want to restart nodes -- even if the problem persisted (it may well not!), it would take us another half hour to get back to the level of understanding that we had before since things may shift around. We also can't reasonably be expected to be allowed to restart nodes at all in this situation.

We may want to look into another way of overriding this setting out-of-band (say, the operator runs a cli debug thing that changes it one-off) if your concerns are big enough. Either way, I'd like to merge this -- we have enough time to replace it with something that you find more palatable before releasing `1.1`. For `1.2`, I've entertained the idea of building better tools that obviate vmodule and that aren't as dangerous.

**Comment by bdarnell** [comment]
I see this as a security/DoS issue - production clusters shouldn't have unauthenticated debugging interfaces enabled that have as dramatic an effect as setting vmodule. So if a production cluster got into this state, I don't want this interface enabled no matter how useful it is; requiring a restart is an acceptable price in my view. For the cluster currently being debugged, you can run a custom build without merging this.

I'd be OK with an *authenticated* interface to set vmodule (e.g. a root-only SQL function).

**Comment by petermattis** [comment]
Is `/debug/vmodule` covered by `server.remote_debugging.mode` as well? If yes, I don't see a problem to setting the default to `true` since by default only someone from localhost would be able to change the vmodule value.

**Comment by tschottdorf** [comment]
Yes, it's already covered by `server.remote_debugging.mode`, which defaults to localhost access only.

**Comment by petermattis** [comment]
Adding a `crdb_internal` SQL function to change the vmodule setting for the connected to node also seems reasonable.

**Comment by tschottdorf** [comment]
Yeah, if that's ok with everyone here that seems workable. However, we'll need to make sure that we can always get at least that far. I *assume* that'll be the case (similar to how `SELECT 1` "always" works)?

**Comment by tschottdorf** [comment]
Done, PTAL

**Comment by knz** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17914#-:-KsNdZl4C9Xmu-c8hH4s:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
I think you missed the [`/debug` page](https://github.com/cockroachdb/cockroach/blob/b421d208da6a30e7cc441738f661e0186dc4aada/pkg/ui/src/views/reports/containers/debug/index.tsx#L195).

**Comment by tschottdorf** [comment]
Thanks @nvanbenschoten, fixed. @bdarnell, are you happy with this?

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17914#-:-KsPna44le9LwPSWOD3L:bnfp4nl)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17914#-:-KsPorI1g770soZPp4KM:bnfp4nl)*

**Pull request merged**
