### PR TITLE
kvserver,batcheval: replace TestingSetTxnAutoGC with field on BatchEvalTestingKnobs

### LINKED ISSUE #101764: kv: replace TestingSetTxnAutoGC with field on BatchEvalTestingKnobs
`TestingSetTxnAutoGC` is a testing function that controls a global variable dictating whether `Transaction` entries are automatically gc'ed upon `EndTxn`. Using global variables to inject testing-only instrumentation or configuration is an anti-pattern.

We should replace this function with a boolean field on `BatchEvalTestingKnobs`.

Jira issue: CRDB-27123

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, the global variable `txnAutoGC` and the function `TestingSetTxnAutoGC` were used to control auto-gc of Transaction entries after EndTxn. Having such control is useful in some tests. However, global variables are an antipattern, so this change introduces a new boolean knob in BatchEvalTestingKnobs to achieve the same functionality.

Fixes: #101764
Epic: CRDB-27123

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102776)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miraradeva)

___
*[`pkg/kv/kvserver/batcheval/cmd_end_transaction.go` line 705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102776#-NUh8GqY6MISnLDKBjEv:-NUh8GqY6MISnLDKBjEw:b-y9yt07) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6e7807e58660f056267257e58d17df7f463e8a/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L705)):*
> ```Go
> 	recordAlreadyExisted bool,
> 	externalLocks []roachpb.Span,
> 	evalCtx EvalContext,
> ```

nit: Let's move this to the third argument to match the order in the signature of `func EndTxn`. That helps separate inputs with a broad scope from inputs with a small scope.

Also, while we're here, do you mind adding another commit that does the same for `resolveLocalLocks` and `resolveLocalLocksWithPagination`. So e.g. instead of:
```
resolveLocalLocks(ctx, desc, readWriter, ms, args, reply.Txn, cArgs.EvalCtx)
```
something like:
```
resolveLocalLocks(ctx, readWriter, cArgs.EvalCtx, ms, args, reply.Txn)
```
This also encourages us to push `desc := cArgs.EvalCtx.Desc()` into `resolveLocalLocksWithPagination`.
___
*[`pkg/kv/kvserver/kvserverbase/knobs.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102776#-NUh9vud-ObixSM77vj8:-NUh9vud-ObixSM77vj9:b-74o7ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6e7807e58660f056267257e58d17df7f463e8a/pkg/kv/kvserver/kvserverbase/knobs.go#L54)):*
> ```Go
> 	UseRangeTombstonesForPointDeletes bool
> 
> 	// DisableTxnAutoGc disables automatically gc-ing Transaction entries upon
> ```

The previous comment was using pretty old terminology. Consider replacing with:
```go
// DisableTxnAutoGC disables automatically gc-ing transaction record entries
// upon EndTxn. Without this knob, synchronous transaction record cleanup is
// performed in cases when a transaction has only locks on the same range as its
// record (which can be resolved synchronously with EndTxn). This is useful in
// certain tests.
```
___
*[`pkg/kv/kvserver/kvserverbase/knobs.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102776#-NUhBLRVCqJbLq3WOn7X:-NUhBLRVCqJbLq3WOn7Y:bmkgjzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b6e7807e58660f056267257e58d17df7f463e8a/pkg/kv/kvserver/kvserverbase/knobs.go#L54)):*
> ```Go
> 	UseRangeTombstonesForPointDeletes bool
> 
> 	// DisableTxnAutoGc disables automatically gc-ing Transaction entries upon
> ```

nit: It's technically described in the Go style guide that acronyms in names should not be camel-case. So this would be `DisableTxnAutoGC`, even though I agree that it's moderately less readable.

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102776)* status: :shipit: complete! 0 of 0 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/102776#-NV0wuTj5bqR5mf09pD9:-NV0wuTj5bqR5mf09pDA:bdocaw0) (no related file):*
After seeing the data race warning in a previous build, I tried to make the `DisableTxnAutoGC` knob of type `atomic.Bool` instead of just bool. That would have worked I think but it required significant changes in many places because now we can't just pass `EvalContext` as such; we would need a pointer to it. This change would also make the `DisableTxnAutoGC` knob a bit inconsistent compared to other knobs.

So instead I tried to refactor the two tests that required changing the knob after the test store has started. In `store_test.go` I managed to set the knob before the test store was started. In `replica_test.go` however, I ended up doing more refactoring: I split the tests into two groups (with and without auto gc). I think it's less messy than a potential `EvalContext`refactor.

___

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102776#-:-NVVM37C0exa_P0H_pKI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Pull request merged**
