### PR TITLE
kvclient: add metrics for proxy requests

### PR DESCRIPTION
**Pull request by andrewbaptist**
Proxy behavior was added in a previous commit. This commit adds 4 new
metrics to track the client and server side of proxying and the number
of errors that occured as a result of the proxy. These statistics will
normally be zero or close to zero. While there is a partial partition
the metric will be increased.

Epic: none

Release note: Adds four new metrics: `distsender.rpc.proxy.sent`,
`distsender.rpc.proxy.err`, `distsender.rpc.proxy.forward.sent`,
`distsender.rpc.proxy.forward.err` to track the number and outcome of
proxy requests. Operators should monitor and alert on
`distsender.rpc.proxy.sent` as it indicates there is likely a network
partition in the system.

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120239)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpSVhH9CGbEO4EJ3JP:-NtpSVhH9CGbEO4EJ3JQ:b-hfxekc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a1b6910e40ba9712d7fd851ca5031f3f2cb0e96/pkg/kv/kvclient/kvcoord/dist_sender.go#L206)):*
> ```Go
> 	metaDistSenderProxySentCount = metric.Metadata{
> 		Name:        "distsender.rpc.proxy.sent",
> 		Help:        `This counts the number of proxy attempts for Send requests which originated on this client`,
> ```

nit: consider making this more understandable to operators -- they don't know what Send requests or stacks are, and to them a client is a SQL client not a DistSender. Something along the lines of "Number of gateway attempts to proxy a request to an unreachable leaseholder via a follower replica." Same goes for the other descriptions.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpVXc--2hmajSm78h_:-NtpVXc--2hmajSm78ha:bmmet9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/47162bc96023c174223397896e788a26a2b53442/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L207)):*
> ```XML
> 
>     <LineGraph
>       title="Proxy requests"
> ```

Should we try to present some of these in the same chart? For example, we could group either of proxy/forward or requests/errors into 2 charts rather than having 4 charts.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpVS9w9KkMi3SYfH5a:-NtpVS9w9KkMi3SYfH5b:bvif8k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/47162bc96023c174223397896e788a26a2b53442/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L264)):*
> ```XML
> 
>     <LineGraph
>         title="Proxy forwards"
> ```

Should this be "Proxy forward errors"?

**Review by erikgrinaker — APPROVED** [review]
Whoops, accidentally published before approving.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-:-NtpVsckCXtBbk8AVQk4:b3nevaf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Review by andrewbaptist — COMMENTED** [review]
No problem! Thanks for the quick review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-:-NtpaiUvBFHkn0RE3HhU:brswfx9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpSVhH9CGbEO4EJ3JP:-NtpcaWB76e-5WPFMsNR:b-u67p1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a1b6910e40ba9712d7fd851ca5031f3f2cb0e96/pkg/kv/kvclient/kvcoord/dist_sender.go#L206)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: consider making this more understandable to operators -- they don't know what Send requests or stacks are, and to them a client is a SQL client not a DistSender. Something along the lines of "Number of gateway attempts to proxy a request to an unreachable leaseholder via a follower replica." Same goes for the other descriptions.
</blockquote></details>

I cleaned up this text. Good suggestion.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpVXc--2hmajSm78h_:-NtpcfXb3mc7iYq_-C7d:b-9fpy5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/47162bc96023c174223397896e788a26a2b53442/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L207)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Should we try to present some of these in the same chart? For example, we could group either of proxy/forward or requests/errors into 2 charts rather than having 4 charts.
</blockquote></details>

I had a conversation with the UI team about this, and they recommended to keep seperate graphs. Multiple per-node lines on a single graph are discouraged as they don't scale well
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx` line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120239#-NtpVS9w9KkMi3SYfH5a:-NtpeKHeETaf_YZle8q7:bdcun61) ([raw file](https://github.com/cockroachdb/cockroach/blob/47162bc96023c174223397896e788a26a2b53442/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L264)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Should this be "Proxy forward errors"?
</blockquote></details>

Yep - there were some other small typos I cleaned up as well. Thanks!

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker

TFTR!

**Pull request merged**
