### PR TITLE
cli: enhance errors reported upon conn failures

### LINKED ISSUE #24788: cli: Improve error messages for `init`
Is this a question, feature request, or bug report?
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
# grep -F '[config]' cockroach-data/logs/cockroach.log
grep: cockroach-data/logs/cockroach.log: No such file or directory
# cockroach version
Build Tag:    v2.0.0
Build Time:   2018/04/03 20:56:09
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  a6b498b7aff14234bcde23107b9e7fa14e6a34a8
Build Type:   release
# uname -a
Linux cockroach-us-central1-f 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux



# cockroach init --insecure
E180413 17:59:19.184767 1 cli/error.go:109  unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Failed running "init"
```

2. Please describe the issue you observed:

- What did you do?

Tried to initialize a cluster

- What did you expect to see?

Startup as experienced on many other systems

- What did you see instead?

rpc errors with no code and a stacktrace that only points back to an error handling function.

I get the same error when running with certs dir or host (even localhost):

```
# cockroach init --certs-dir=/etc/cockroachdb/certs --host=cockroach-us-central1-f.us-central1-f.c.**********.internal
E180413 17:59:02.041910 1 cli/error.go:109  unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Failed running "init"

# cockroach init --host localhost --insecure
E180413 18:02:35.749030 1 cli/error.go:109  unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
Failed running "init"
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #24788.

Prior to this patch, the various CLI commands were making
a halfhearted attempt at decorating the underlying error with some
troubleshooting instructions.

Unfortunately, this was mixing up situations where the TCP connection
failed outright, those where the security settings were incorrect, and
connections dropped later, after the initial handshake was
successful.

In practice, we've noticed that the troubleshooting steps are rather
different for both kinds of situations. So this patch enhances the
code to clarify what is going on. It attempts to distinguish:

- TCP connection problem ("check --host vs --advertise-host").
- secure conn to insecure server ("use --insecure?")
- invalid TLS settings / TLS auth error ("check credentials").
- timeouts.
- connection lost (e.g. conn closed by server).

Release note (cli change): The various `cockroach` client comments
now better attempt to inform the user about why a connection is failing.

### CODE REVIEW

**Comment by knz** [comment]
I'm taking suggestions as to how to best test this.

**Review by petermattis — COMMENTED** [review]
> I'm taking suggestions as to how to best test this.

I would look at adapting the infrastructure in `cli/cli_test.go`. But rather than using `cliTest.RunWithArgs`, you call `cli.Run` directly for various commands and flag settings which exercise your new error messages.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28200#-:-LIvwTe66fRX60t5cKEp:b-nzeuq2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
ok thanks will look into it

**Comment by knz** [comment]
Now with tests. RFAL.
I used TCL tests because of the diversity of certs/insecure/non-cockroachdb environments that needed to be tested.

**Review by bdarnell — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28200)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/error.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28200#-LJEokZEAcLI1kzlvlwH:-LJEokZEAcLI1kzlvlwI:bi9s8g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/27154cc3002c68fc488b40928c8e85a140609d35/pkg/cli/error.go#L87)):*
> ```Go
> 		connFailed := func() error {
> 			const format = "cannot dial server.\n" +
> 				"Is the server started already?\n" +
> ```

s/started already/running/

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28200)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/error.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28200#-LJEokZEAcLI1kzlvlwH:-LJIVzfb3xcXz1jveyKe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27154cc3002c68fc488b40928c8e85a140609d35/pkg/cli/error.go#L87)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/started already/running/
</blockquote></details>

Done.

**Comment by knz** [comment]
thanks!

bors r+

cc @jseldess

**Pull request merged**
