### PR TITLE
cherry-pick 2.0: sql: use the EXPERIMENTAL_ prefix for experimental features

### PR DESCRIPTION
**Pull request by knz**
Picks #24696.
cc @cockroachdb/release

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by RaduBerinde** [comment]
If some users are already using some of these (which we know to be the case for TESTING_RANGES), I don't think it's a good idea to change them between 2.0 and 2.0.x.  There is not much benefit but there is definitely a downside.

**Comment by RaduBerinde** [comment]
Oh. I missed the fact that TESTING_RANGES is still supported.. Never mind.

**Pull request merged**
