### PR TITLE
builder: various cleanup

### PR DESCRIPTION
**Pull request by benesch**
See commit messages for details.

tl;dr: builder image is 1GB smaller and should be way less painful to rebuild when you're not changing the cross-compilation toolchains.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
LGTM commits 1,2, 3, I have to :dog: out of commit 4, there's too much change in there, and I can't cross reference every single line that's removed to one that's added. Want to take a stab at fixing it, or do you want me to look through it carefully? There's clearly some issue there as CI is failing as well.

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20505#-:-L-cY8cBnZRHibK11JFj:bncq0b1)*

**Comment by benesch** [comment]
Let me try to split up that last commit!

**Comment by benesch** [comment]
Ok, @arjunravinarayan, please take another look! I've split the last commit into two and the penultimate commit is now strictly code movement. Or at least it should be. 

FYI I had to remove the commit that installed Go from a binary release instead of compiling it from source. That was breaking CI for Reasons™ that I don't have the fortitude to address in this PR.

**Comment by arjunravinarayan** [comment]
:lgtm: thanks for splitting up the commits! Makes its a breeze to review.

---

Reviewed 1 of 13 files at r1, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20505#-:-L-ilQN-YIlA_Lnafp9x:b-9x8mhm)*

**Comment by benesch** [comment]
You bet. Sorry for being sloppy the first time around! TFTR!

**Pull request merged**
