### PR TITLE
contention: store contention events on non-SQL keys

### LINKED ISSUE #60669: sql: tolerate non-SQL keys in AddContentionEvent
**Describe the problem**

`contentionRegistry.AddContentionEvent` currently assumes that all keys passed to it are SQL keys. This is not true, as evidenced by this test failure in `acceptance/multitenant`:

```
| ERROR: ensuring SQL migrations: failed to run migration "alter scheduled jobs": alter-scheduled-jobs: polling for queued jobs to complete: poll-show-jobs: unable to add contention event to registry: invalid uvarint length of 9
```

**To Reproduce**

Run acceptance/multitenant with a version of `(*DistSQLReceiver).Push` that does not throw away errors from `AddContentionEvent`.

**Expected behavior**
I would expect the contention registry to handle such keys gracefully. It could either ignore them, but it's likely worth looking into whethercontention on non-SQL keys should be tracked (since the error above results from a SQL operation).

**Environment:**
- first observed on #59992 (which added a quick fix to ignore the error and resulted in filing this issue)

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, whenever we tried to add a contention event on a non-SQL
key, it would encounter an error during decoding tableID/indexID pair,
and the event was dropped. This commit extends the contention registry
to additionally store information about contention on non-SQL keys. That
information is stored in two levels:
- on the top level, all `SingleNonSQLKeyContention` objects are ordered
  by their keys
- on the bottom level, all `SingleTxnContention` objects are ordered by the
  number of times that transaction was observed to contend with other
  transactions.

`SingleTxnContention` protobuf message is moved out of
`SingleKeyContention` and is reused for non-SQL keys. This commit also
updates the status server API response. I assume that no changes are
needed with regards to backwards compatibility since the original
version was merged just a few weeks ago, and we haven't had a beta
released since then.

Fixes: #60669.

Release note (sql change): CockroachDB now also stores the information
about contention on non-SQL keys.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61828)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/contention/registry.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61828#-MVU9IrB25-n6nFeO5Rb:-MVU9IrB25-n6nFeO5Rc:bkp11y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ce534e2d0e41f90d9fd8a1e64c4849365c8aa8/pkg/sql/contention/registry.go#L83)):*
> ```Go
> 	const estimatedAverageKeySize = 64
> 	txnsMapSize := maxNumTxns * int(unsafe.Sizeof(uuid.UUID{})+unsafe.Sizeof(int(0)))
> 	orderedKeyMapSize := orderedKeyMapMaxSize * (int(unsafe.Sizeof(comparableKey{})+estimatedAverageKeySize) + txnsMapSize)
> ```

Notable change here, I think the previous calculation was incorrect.

Also, what do we want to do with this method? We're now using the registry, but it's estimated max memory footprint (assuming it is about 4.5MiB) seems low enough to me that we can just ignore it since it is on a per node basis. I think we could be concerned if the keys in the contention events are large, but then the estimate doesn't help us much.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61828#-:-MVq-hKW8HFPUIlMT3X_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/contention/registry.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61828#-MVU9IrB25-n6nFeO5Rb:-MVpy_RYEMv8hqA92adP:b-f5v5dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ce534e2d0e41f90d9fd8a1e64c4849365c8aa8/pkg/sql/contention/registry.go#L83)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Notable change here, I think the previous calculation was incorrect.

Also, what do we want to do with this method? We're now using the registry, but it's estimated max memory footprint (assuming it is about 4.5MiB) seems low enough to me that we can just ignore it since it is on a per node basis. I think we could be concerned if the keys in the contention events are large, but then the estimate doesn't help us much.
</blockquote></details>

I think it's fine to delete it.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61828)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/contention/registry.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61828#-MVU9IrB25-n6nFeO5Rb:-MVqmkRb2iLetjfZEOIm:b-bnqu6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0ce534e2d0e41f90d9fd8a1e64c4849365c8aa8/pkg/sql/contention/registry.go#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it's fine to delete it.
</blockquote></details>

Cool, removed.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
