### PR TITLE
sql/parser: prevent panic by switching missing CASE type to DNull

### PR DESCRIPTION
**Pull request by dt**
Workaround to avoid crash in #4691

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4695)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-KBU18QH-5HBeVrmj_mw:-KBU18QH-5HBeVrmj_mx:800892446) ([raw file](https://github.com/cockroachdb/cockroach/blob/8238b5b562a869f74de2536d243e53ced06304f7/sql/parser/type_check.go#L109)):*
does this actually fix the problem? Does it end up inferring `NULL` everywhere?

Looking at the test case you added, I don't understand how it works, but maybe it doesn't, since it doesn't affect any rows. The only source of type information there is the column being updated, but the current type inference mechanism doesn't flow that information into this function, so an error seems to be the only reasonable strategy.

---

*[sql/parser/type_check.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-KBU0qXBeAjRORXoBf6H:-KBU0qXBeAjRORXoBf6I:185244039) ([raw file](https://github.com/cockroachdb/cockroach/blob/8238b5b562a869f74de2536d243e53ced06304f7/sql/parser/type_check.go#L140)):*
what happens if you remove `dummyVal == nil` here? that check appears to be nonsense, so let's remove it rather than leave it for the next person to scratch their head over.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/type_check.go, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-KBU18QH-5HBeVrmj_mw:-KBUGRGXVP9lHwVQZvd4:10766727) ([raw file](https://github.com/cockroachdb/cockroach/blob/8238b5b562a869f74de2536d243e53ced06304f7/sql/parser/type_check.go#L109)):*
Oh, yeah, I need to `t.Skip` that test -- as I said, this doesn't _fix_ the issue, just dodges the panic until we do.

---

*[sql/parser/type_check.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-KBU0qXBeAjRORXoBf6H:-KBUGztTcSpsj5CwihyG:711681798) ([raw file](https://github.com/cockroachdb/cockroach/blob/8238b5b562a869f74de2536d243e53ced06304f7/sql/parser/type_check.go#L140)):*
yeah, fair -- I wasn't entirely sure what the intent was so I didn't want to go mucking it up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/pgwire_test.go, line 519 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-KBUHvJmn0U9nyFiA91V:-KBUHvJmn0U9nyFiA91W:-1440887341) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a0a6a58785c3f4c486166df933c77161aa3b391/sql/pgwire_test.go#L519)):*
instead of leaving this as a comment, i would suggest moving it up into the failing prepare tests; at least there it would provide some documentation of this behaviour, broken as it may be.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695)*

**Comment by mjibson** [comment]
I would prefer to not merge this PR so I can get a real fix in instead. Is this panic blocking anything right now?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4695#-:-KBUNtES8uSWkE3Liptu:1156942164)*

**Pull request closed without merging**
