### PR TITLE
execinfra: mark 'sql.distsql.temp_storage.workmem' as public

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note (sql change): `sql.distsql.temp_storage.workmem` cluster
setting is now marked as public and is included into the documentation.
It determines how much RAM a single operation of a single query can use
before it must spill to temporary storage. Note the operations that
don't support the disk spilling will ignore this setting and are subject
only to `--max-sql-memory` startup argument.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Will backport only the first commit to 21.1.0.

**Comment by yuzefovich** [comment]
Let's actually separate two commits out.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63947#-:-MYlscfo6_zvybMEsSVQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
