### PR TITLE
bazel: add unused lint

### LINKED ISSUE #76933: bazel: staticcheck unused lint not catching some failures
Compare two CI runs, non-Bazel and Bazel, at the same commit:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4432500?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4432517?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

The Bazel CI should be finding the following unused errors:

```
=== RUN   TestLint/TestStaticCheck
    lint_test.go:1733:
        pkg/cmd/publish-artifacts/main.go:53:2: var latestStr is unused (U1000)
    lint_test.go:1733:
        pkg/cmd/publish-artifacts/main.go:126:6: func buildOneWorkload is unused (U1000)
    --- FAIL: TestLint/TestStaticCheck (855.48s)
```

Epic CRDB-8036

Jira issue: CRDB-13332

### PR DESCRIPTION
**Pull request by rickystewart**
1. Pull in `7336768b31d5af41cd46d5defb58560a93b3ba98` for `rules_go`
   which adds the `unused.out` file to the `.x` archive for each
   compiled library.
2. Add a helper binary `build/bazelutil/unused_checker`. This binary
   takes a list of `.x` archives on the command-line, parses out the
   JSON in the `unused.out` file, and aggregates all this data producing
   a list of unused objects.
3. Update `pkg/cmd/generate-test-suites` to produce more granular
   information about the targets in `pkg/...` and move this data to
   `build/bazelutil/targets.bzl`.
4. Add `unused.bzl` which captures the `unused_test`. This file
   implements an `aspect` that traverses all of the targets in tree,
   accumulating the transitive list of `.x` archives for each, then
   passing it over to `unused_checker`.

Closes https://github.com/cockroachdb/cockroach/issues/76933.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Failures will look like this:

Screen Shot 2022-07-01 at 12 34 55 PM

**Comment by rickystewart** [comment]
Successful [run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_UnusedLint/5727522?buildTab=log&focusLine=806&linesState=53.634.639.640).

**Review by mari-crl — APPROVED** [review]
Heckin nice work! Thanks for putting this together and for modifying it - it looks great this way! :lgtm_strong: 

> Reviewed 181 of 577 files at r1, 795 of 829 files at r2, 1 of 2 files at r3, 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83665#-:-N6sT3Fh-FEu9-AdgqQR:b502gmp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mari-crl)

**Comment by rickystewart** [comment]
TFTR, I know this one couldn't have been easy :) 

YOLO!

bors r=mari-crl

**Comment by rickystewart** [comment]
bors r=mari-crl

**Comment by irfansharif** [comment]
Could we rename the autogenerated `get_x_data` things to something closer to `get_unused_lint_data`? It's entirely a naming nit so feel free to disregard, I felt it'd make it bit easier to understand to folks unfamiliar with what that directive is actually doing.

**Pull request merged**
