### PR TITLE
kv: avoid setting EndTxn.Key again after a refresh

### LINKED ISSUE #34982: sql/logictest: TestParallel failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/22119c85d2e7aca50f21f61408ae55207679569d

Parameters:
```
TAGS=
GOFLAGS=-race
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestParallel PKG=github.com/cockroachdb/cockroach/pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1140728&tab=buildLog

```
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:496 +0x20c
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1139 +0x422
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:798 +0x19ae
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:710 +0x6ea
  github.com/cockroachdb/cockroach/pkg/internal/client.lookupRangeFwdScan()
      /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/range_lookup.go:318 +0x5be
  github.com/cockroachdb/cockroach/pkg/internal/client.RangeLookup()
      /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/range_lookup.go:201 +0x7b4
  github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).RangeLookup()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:343 +0xba
  github.com/cockroachdb/cockroach/pkg/kv.(*RangeDescriptorCache).performRangeLookup()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:412 +0x400
  github.com/cockroachdb/cockroach/pkg/kv.(*RangeDescriptorCache).lookupRangeDescriptorInternal.func3()
      /go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:285 +0x166
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:118 +0x4c

Goroutine 148 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x14fb
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.serveConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:167 +0x275
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:509 +0xc0d
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func20.1()
      /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1710 +0x1b7
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:139 +0xdf
==================
--- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
I190215 08:44:48.972145 396 sql/logictest/logic.go:907  --- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
--- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
I190215 08:44:49.059996 487 sql/logictest/logic.go:907  --- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
--- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
I190215 08:44:49.205905 438 sql/logictest/logic.go:907  --- done: testdata/parallel_test/subquery_retry/txn with config : 1 tests, 0 failures
I190215 08:44:49.206114 39 sql/logictest/parallel_test.go:159  testdata/parallel_test/subquery_retry/test.yaml: run list 2: 0:final
--- done: testdata/parallel_test/subquery_retry/final with config : 2 tests, 0 failures
I190215 08:44:49.225712 508 sql/logictest/logic.go:907  --- done: testdata/parallel_test/subquery_retry/final with config : 2 tests, 0 failures
I190215 08:44:49.226140 509 util/stop/stopper.go:547  quiescing; tasks left:
1      [async] transport racer
1      [async] intent_resolver_batcher
1      [async] closedts-rangefeed-subscriber
I190215 08:44:49.226512 509 util/stop/stopper.go:547  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-rangefeed-subscriber
I190215 08:44:49.228329 509 util/stop/stopper.go:547  quiescing; tasks left:
1      [async] transport racer
I190215 08:44:49.293822 166 kv/transport_race.go:113  transport race promotion: ran 42 iterations on up to 1147 requests
    --- FAIL: TestParallel/subquery_retry (3.43s)
        testing.go:771: race detected during execution of test

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #34982.

The `txnCommitter` is beneath the `txnSpanRefresher` in the `TxnCoordSender`'s
interceptor stack. Because the span refresher can re-issue batches, it
needs to be careful about what parts of the batch it mutates. We weren't
being careful enough about setting the `EndTxn.Key` after a refresh,
even though we were setting it to the same value. This looked like a
data race to the race detector and the `raceTransport`.

I would really like to pull the `txnCommitter` above the `txnSpanRefresher`
but I don't think that would actually clean things up for two reasons:
1. Once we introduce parallel commits, it would be very nice if the
   span refresher never had to know about `STAGING` txns.
2. The committer will need to generate retryable errors when any
   in-flight write is pushed, even if the write's request itself
   doesn't generate these errors.

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
I'm confused about this race. You'd think the interceptors synchronize with each other... So how do they race exactly?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35003#-:-LYma-NL2oH-8LxMj0Ep:bqa0hps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 483 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35003#-LYm_i4F5gIjYlb6EgS0:-LYm_i4G2rBOBU09QgYc:b6fobm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/563dbae003ea79b017842b24bc9d81b574e0a367/pkg/kv/txn_coord_sender.go#L483)):*
> ```Go
> 			// span refresher can re-issue batches, it needs to be careful about
> 			// what parts of the batch it mutates. Any mutation needs to be
> 			// idempotent and should avoid writing to memory when not changing
> ```

I think the addition to the comment will quickly turn confusing. Writing to memory without changing it? I don't think I'd understand what this means.

**Review by nvb — COMMENTED** [review]
It's not a real race - it's caused by the `raceTransport ` trying to enforce that we don't modify something we've already sent. In this case, we refresh and set `EndTxn.Key` to the same thing it was already set to, but the race detector doesn't know that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35003#-:-LYmdJ_MCRR-XzhC-ATE:b-ec96jm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by andreimatei** [comment]
Oh that damn `raceTransport`. But should it allow changes to the requests after this patch?
https://github.com/cockroachdb/cockroach/pull/30485/commits/1f95897a3d351a34365a17591e9231b90201c6d5

Feel free to merge this if you want to fix tests, but I'm hoping we can allow the interceptor to do what it was doing without qualms about the `raceTransport`...

**Comment by nvanbenschoten** [comment]
> But should it allow changes to the requests after this patch? [1f95897](https://github.com/cockroachdb/cockroach/commit/1f95897a3d351a34365a17591e9231b90201c6d5)

I think the problem is that that only performs a shallow copy of the requests slice, so inner mutations are still flagged as data races.

TFTR, going to merge this as is to fix the test. I'll still be working to clean up this area as pipelining comes in.

bors r+

**Review by andreimatei — APPROVED** [review]
Try now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35003#-:-LYnUJZ2BAd26ue9z24P:b-pa6190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
