### PR TITLE
kvserver/concurrency: misc lock table tests to cover functionality

### PR DESCRIPTION
**Pull request by sumeerbhola**
that was not tested before and three bug fixes

Some of the following was based on looking at test coverage results:
- added wait_self: covers reservation by a different request from the
  the same txn and lock acquisition by the same txn
- we were not adding to the sequence nums in discoveredLock
  which was a bug found when printing the sequence numbers
- dup_access: added test when a request is both reading and writing
  to a key and the lock is held after it stops waiting for write
- added lock_changes: misc state changes for a lock that were not covered
  by existing tests
- added ignored seqnum tests to the update testdata file. It found
  a bug
- UpdateLocks now ignores updates with the same epoch but lower timestamp.
  It used to trigger an error after the ts had been updated which was
  severely muddled (tell the caller of the error after making the erroneous
  state change!).

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1g_s6B3RUqLERdQqqU:-M1g_s6C2QahYTzQzChX:b-44s0az) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1454)):*
> ```Go
> 		// Else txn.Epoch < holderTxn.Epoch, so only the timestamp has been
> 		// potentially updated.
> 		isLocked = true
> ```

Is this change from the second commit the desired behavior?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45769)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1gbthb1oL3e2yJoS30:-M1gbthb1oL3e2yJoS31:be0xyku) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1450)):*
> ```Go
> 				continue
> 			}
> 			l.holder.holder[i].txn = txn
> ```

Should this assignment also be conditional on `advancedTs`. This unconditional assignment could mean that the timestamps inside `txn` and the sequence num are not monotonic.

**Review by nvb — COMMENTED** [review]
I'm happy to see this testing expanded.

> Reviewed 15 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-:-M1ktmWMEc7B4t4_8rPR:b-s0ugm9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kmoiA0HN9nRCkhrMT:-M1kmoiA0HN9nRCkhrMU:b945xyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L699)):*
> ```Go
> 	}
> 	waitingOnStr := func(txn *enginepb.TxnMeta, ts hlc.Timestamp) string {
> 		// TODO(sbhola): strip the leading 0 bytes from the UUID string since tests are assigning
> ```

If you're feeling inspired, you might consider doing something similar to a5695481bb5ef08509ac08ae813e9b6aa03aac28 to address this. You would only want to shorten the UUID when that doesn't lose information though because I expect that we will hook this up to debugging output sometime soon.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kmbir4shMNWXliwoE:-M1kmbir4shMNWXliwoF:b4eg9ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L702)):*
> ```Go
> 		// UUIDs using a counter and makes this output more readable.
> 		var seqStr string
> 		if txn.Sequence != 0 {
> ```

Should we get rid of this now?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kk--g6luMLdUsbFGR:-M1kk--g6luMLdUsbFGS:b-51ie8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L707)):*
> ```Go
> 		return fmt.Sprintf("txn: %v, ts: %v%s", txn.ID, ts, seqStr)
> 	}
> 	holderInfoStr := func() string {
> ```

Not that it really matters given the limited uses of this `lockState.Format` right now, but ideally we wouldn't create these intermediate strings and then write them to the top-level `strings.Builder`. This creates wasted memory allocations and copies.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kkVnIE7dsP1PaO2FZ:-M1kkVnJD8-Z1tEl4k-r:buqtfy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L718)):*
> ```Go
> 			}
> 			first = false
> 			h := &l.holder.holder[i]
> ```

nit: move this directly below the `for i := range l.holder.holder {` line.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kkwF43K6gdpjgT0g5:-M1kkwF43K6gdpjgT0g6:btwsex6) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L1414)):*
> ```Go
> 	}
> 
> 	ts := up.Txn.WriteTimestamp
> ```

minor nit: re-order this line and the next. We work with the tuple of `(txn, ts)` throughout this file.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1ksVL0E2lpNScoAxCd:-M1ksVL0E2lpNScoAxCe:b-pkac16) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1434)):*
> ```Go
> 		// way of this request. For unreplicated locks the lock table is the
> 		// source of truth so we best-effort mirror the behavior of
> 		// mvccResolveWriteIntent() by updating the timestamp.
> ```

You might want to note that this isn't always going to be the case and that eventually, the lockTable will become the source of truth for replicated locks as well.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1gbthb1oL3e2yJoS30:-M1ktCTcBcHxtbwudAuj:bc7n62q) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1450)):*
> Should this assignment also be conditional on advancedTs

Yes, I think so. I think we should be able to mirror the logic in `MVCCResolveWriteIntent` and only update the txn's `WriteTimestamp`
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1g_s6B3RUqLERdQqqU:-M1ktEq1EcwsC9syZSTI:b55z006) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1454)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this change from the second commit the desired behavior?
</blockquote></details>

It seems desirable to me. Can you expand on why it wouldn't be?
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1km12U9l3FvPs8uzCm:-M1km12V9NFlkfAZQFyD:b-p152re) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table_test.go#L79)):*
> ```Go
>  Releases locks for the named transaction.
> 
> update txn=<name> ts=<int>[,<int>] epoch=<int> span=<start>[,<end>] [ignored-seqs=<int>[,<int>]]
> ```

Any interest in supporting ranges of `ignored-seqs`? I think that would make this grammer look like `[ignored-seqs=<int>[-<int>][,<int>[-<int>]]]`. Would that exercise new code paths?
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1klWQD9rVQ87Y1tQVZ:-M1klWQE3fq-rTCPKVFb:b7mwsas) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table_test.go#L133)):*
> ```Go
> 				make(map[string]lockTableGuard)
> 		}
> 		txnsByName, txnCounter, requestsByName, guardsByReqName := newState()
> ```

Is there a reason to create these before `new-lock-table`? We start each test off with `new-lock-table`, so we seem to be doing this all twice right at the beginning of a test.

I ask mostly because it would be nice to just inline the constructors in `newState` into `new-lock-table`.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access, line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1koND28A4O5ZgmDFd_:-M1koND28A4O5ZgmDFda:bfugtse) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access#L671)):*
> ```
> local: num=0
> 
> # req12 ignores the lock at "b" when it encounters it again as a reader.
> ```

What do you mean by "ignores"? Isn't it moving into the `waitForDistinguished` state? Do you mean that it's in this state as a writer and not a reader?
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kogmHC7lJvHEQ2kCX:-M1kogmHC7lJvHEQ2kCY:b-806k9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L9)):*
> ```
> # Lock being released is held by a different transaction.
> # ---------------------------------------------------------------------------------
> ```

I was recently reminded that datadriven tests have a notion of subtests. For instance, I think if you added `subtest lock_released_by_different_transaction` here, you would install a subtest until you either created a new subtest or issued `subtest end`. It might be worth playing around with because these sequences of tests are so structured.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kptpx4f9pNakxHgeF:-M1kptpx4f9pNakxHgeG:b4n79kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L26)):*
> ```
> local: num=0
> 
> print
> ```

Any reason why you're `print`ing after each `acquire` and `release`, even though they also do the same?
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kq6KVENr9X_upxyHi:-M1kq6KVENr9X_upxyHj:b-l67trk) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L72)):*
> ```
> 
> # ---------------------------------------------------------------------------------
> # Reader waits until it the timestamp of the lock is updated.
> ```

s/it the/the/
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqDWq01lRa2Tus47F:-M1kqDWr2ODO2kUezj2K:b-r2iwsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L82)):*
> ```
> start-waiting: true
> 
> guard-state r=req3
> ```

Could you inspect the `guard-state` after the reader is released?
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqQIaAB9IwGruypgG:-M1kqQIaAB9IwGruypgH:b-3lrimy) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L137)):*
> ```
> global: num=1
>  lock: "a"
>   holder: txn: 00000000-0000-0000-0000-000000000001, ts: 0.000000014,0, seq: 1, info: epoch: 1, seqs: [1], epoch: 1, seqs: [0, 1]
> ```

It seems like we should add the durability of the guard to the `info` text. This is ambiguous.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/update, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqiDGC2Va_k7CUKS1:-M1kqiDGC2Va_k7CUKS2:b-xzzqtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/update#L302)):*
> ```
> # Lock is held at multiple seqnums and then updated to ignore
> # either a seqnum that is not in the held list or one that is
> # in the list. When all the seqnumes are ignored, the lock is
> ```

s/seqnumes/seqnums/
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/update, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqlNJ0DrQkK9P7kL2:-M1kqlNJ0DrQkK9P7kL3:b-rgppr) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/update#L303)):*
> ```
> # either a seqnum that is not in the held list or one that is
> # in the list. When all the seqnumes are ignored, the lock is
> # no longer held.
> ```

s/no longer held/released/
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1krrPgAPSeTDg0D3Mk:-M1krrPgAPSeTDg0D3Ml:b-6mhmou) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self#L29)):*
> ```
> ----
> 
> new-request r=req4 txn=txn2 ts=10 spans=w@a
> ```

nit: I think this test would be easier to read if you renamed `req2` and `req4` to `req2a` and `req2b` to make it clear that they're part of the same transaction.

**Review by sumeerbhola — COMMENTED** [review]
Thanks for the review. Addressed all comments and added a test for the changed `UpdateLock()` behavior.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-:-M1zpT5FBSlV7wQyESu_:b-anuv3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kmoiA0HN9nRCkhrMT:-M1vNhZE-mnu511NoWDF:b7bvuvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L699)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If you're feeling inspired, you might consider doing something similar to a5695481bb5ef08509ac08ae813e9b6aa03aac28 to address this. You would only want to shorten the UUID when that doesn't lose information though because I expect that we will hook this up to debugging output sometime soon.
</blockquote></details>

Yes, I'd noticed that when reviewing and have it in my TODO list for a later PR.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kmbir4shMNWXliwoE:-M1vPr2nAFrAEzBqGrKg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L702)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we get rid of this now?
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kk--g6luMLdUsbFGR:-M1vVczl8_i2xRyIw-N1:b-gn1scg) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L707)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not that it really matters given the limited uses of this `lockState.Format` right now, but ideally we wouldn't create these intermediate strings and then write them to the top-level `strings.Builder`. This creates wasted memory allocations and copies.
</blockquote></details>

Removed all the intermediate strings.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kkVnIE7dsP1PaO2FZ:-M1vPpoH5OVOYhHtvIHI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L718)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this directly below the `for i := range l.holder.holder {` line.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kkwF43K6gdpjgT0g5:-M1vVzMYD_Mn4I-nI6Sf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table.go#L1414)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

minor nit: re-order this line and the next. We work with the tuple of `(txn, ts)` throughout this file.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1ksVL0E2lpNScoAxCd:-M1zPYJz0Mnrl6dxp5rR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1434)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You might want to note that this isn't always going to be the case and that eventually, the lockTable will become the source of truth for replicated locks as well.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1gbthb1oL3e2yJoS30:-M1zTIJmAaFeeYc71UFT:bsl2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1450)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Should this assignment also be conditional on advancedTs

Yes, I think so. I think we should be able to mirror the logic in `MVCCResolveWriteIntent` and only update the txn's `WriteTimestamp`
</blockquote></details>

I've added some more commentary and adjusted the code. The code does not update the `WriteTimestamp` since the `lockHolderInfo.ts` is the source of truth regarding the timestamp at which the lock is held. It makes me nervous to fiddle with the `TxnMeta` instead of replacing one with another, but maybe I am being paranoid. Let me know what you think. 
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 1454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1g_s6B3RUqLERdQqqU:-M1zU3Ob-5GZW9Fy3Dt1:bjpuct2) ([raw file](https://github.com/cockroachdb/cockroach/blob/977fabf577a686583faa34acb56dad21154b10eb/pkg/kv/kvserver/concurrency/lock_table.go#L1454)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems desirable to me. Can you expand on why it wouldn't be?
</blockquote></details>

Just confirming. I've added some more code comments.
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1km12U9l3FvPs8uzCm:-M1zWotW8s0MtQf9-arr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table_test.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any interest in supporting ranges of `ignored-seqs`? I think that would make this grammer look like `[ignored-seqs=<int>[-<int>][,<int>[-<int>]]]`. Would that exercise new code paths?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1klWQD9rVQ87Y1tQVZ:-M1zhq5i18KviFXq2eSi:b71s9e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/lock_table_test.go#L133)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to create these before `new-lock-table`? We start each test off with `new-lock-table`, so we seem to be doing this all twice right at the beginning of a test.

I ask mostly because it would be nice to just inline the constructors in `newState` into `new-lock-table`.
</blockquote></details>

Yes, this was silly. Fixed.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access, line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1koND28A4O5ZgmDFd_:-M1zgaTW6rkRg3-8I6z2:b-11y3o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access#L671)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you mean by "ignores"? Isn't it moving into the `waitForDistinguished` state? Do you mean that it's in this state as a writer and not a reader?
</blockquote></details>

It is entering `doneWaiting` state below. I've added a comment.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kogmHC7lJvHEQ2kCX:-M1zf0jw2bZsklmGWgpi:booq0l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L9)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was recently reminded that datadriven tests have a notion of subtests. For instance, I think if you added `subtest lock_released_by_different_transaction` here, you would install a subtest until you either created a new subtest or issued `subtest end`. It might be worth playing around with because these sequences of tests are so structured.
</blockquote></details>

Based on looking at `testdata/savepoints` it is just a way to put data for different tests in the same file. Is that correct?
So whenever we end up with a sequence of tests in our current files where a test ends with an empty lock table we could end that subtest. Yhat would allow us to restart the request numbering from 1. We would need to define the txn objects again, but that is fine -- it would enhance the readability.
Is that what you had in mind? If so, I think it is worth doing, but as a separate pure-refactoring change -- I would prefer not to mix it with bug fixes like in this PR.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kptpx4f9pNakxHgeF:-M1zZJiWAgp6sK6U44i3:b-c0zcon) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason why you're `print`ing after each `acquire` and `release`, even though they also do the same?
</blockquote></details>

Forgot to remove. Done.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kq6KVENr9X_upxyHi:-M1zZGxM26JB-a4CKHHf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/it the/the/
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqDWq01lRa2Tus47F:-M1z_Hdf2b_gGmQONzRs:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you inspect the `guard-state` after the reader is released?
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqQIaAB9IwGruypgG:-M1zZ4MOBM4Njki3A3cW:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems like we should add the durability of the guard to the `info` text. This is ambiguous.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/update, line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqiDGC2Va_k7CUKS1:-M1zX5yp9frpHr_WEvJ3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/update#L302)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/seqnumes/seqnums/
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/update, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kqlNJ0DrQkK9P7kL2:-M1zX9qVCf1mp1eh0TEp:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/update#L303)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/no longer held/released/
</blockquote></details>

Done
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1krrPgAPSeTDg0D3Mk:-M1zXNrT1Z_RHyODEsb9:bw1djmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self#L29)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I think this test would be easier to read if you renamed `req2` and `req4` to `req2a` and `req2b` to make it clear that they're part of the same transaction.
</blockquote></details>

The difficulty with general request names is that the lockTable does not know about names, and printing the lockTable only outputs the seqnum of the request. So these tests try to keep the request names the same as the seqnums.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-:-M2-14iv5hxZsC_BKu3O:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access, line 671 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1koND28A4O5ZgmDFd_:-M2-0WEk--uclopyQmfr:b-lsa7i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/dup_access#L671)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is entering `doneWaiting` state below. I've added a comment.
</blockquote></details>

Got it. The comment helps.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1kogmHC7lJvHEQ2kCX:-M2-0Z-c072r6NCZsYYO:ba4yg5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/lock_changes#L9)):*
> Is that what you had in mind? If so, I think it is worth doing, but as a separate pure-refactoring change -- I would prefer not to mix it with bug fixes like in this PR.

Yes, that's what I had in mind. I played around with this in #45830 and it seems to work well. Making the change in a separate PR, if at all, SGTM.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45769#-M1krrPgAPSeTDg0D3Mk:-M2-10sT5vTWDfXIHnk4:b-8zp2lr) ([raw file](https://github.com/cockroachdb/cockroach/blob/620a30fc26a1827e62214c1aa40b6a0a5e99378d/pkg/kv/kvserver/concurrency/testdata/lock_table/wait_self#L29)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The difficulty with general request names is that the lockTable does not know about names, and printing the lockTable only outputs the seqnum of the request. So these tests try to keep the request names the same as the seqnums.
</blockquote></details>

Ack. Makes sense.

**Pull request merged**
