### PR TITLE
release-22.2: bump Pebble

### LINKED ISSUE #108676: roachtest: backup-restore/mixed-version failed -- a 22.2 restore of a mixed version backup (23.1,22.2) is slow
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11300127?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11300127?buildTab=artifacts#/backup-restore/mixed-version) on release-23.1.9-rc @ [d417968cd3eb53414a97b29692ba61cf1466276d](https://github.com/cockroachdb/cockroach/commits/d417968cd3eb53414a97b29692ba61cf1466276d):

```
(mixedversion.go:478).Run: mixed-version test failure while running step 24 (run "verify some backups"): mixed-version: waiting for job to finish: job 890771612152594435: current status "running", waiting for "succeeded"
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11300127-1691905326-21-n5cpu4/1691910341102/1691917022887)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30583

### LINKED ISSUE #109078: roachtest: hotspotsplits/nodes=4 failed
roachtest.hotspotsplits/nodes=4 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11390670?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11390670?buildTab=artifacts#/hotspotsplits/nodes=4) on release-22.2 @ [4e79bd45da5d6c2fd8a4adecb93d34a742efed48](https://github.com/cockroachdb/cockroach/commits/4e79bd45da5d6c2fd8a4adecb93d34a742efed48):

```
test artifacts and logs in: /artifacts/hotspotsplits/nodes=4/run_1
(test_runner.go:985).runTest: test timed out (10h0m0s)
(hotspotsplits.go:87).func1: dial tcp 35.231.235.157:26257: connect: connection refused
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*hotspotsplits/nodes=4.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30767

### PR DESCRIPTION
**Pull request by RaduBerinde**
crl-release-22.2: db: don't clear logNum when appending flushable batch
  sstable: optimize twoLevelIterator, when exhausted, for SeekGE & SeekPrefixGE

Fixes #109078
Fixes #108676

Release note (bug fix): fixed very rare condition where the storage engine stops making progress, reporting a "flush next log number is unset" background error.

Release justification: fixes rare but serious condition, found via a roachtest.

### CODE REVIEW

**Comment by renatolabs** [comment]
This should also close #108676, right?

**Comment by RaduBerinde** [comment]
Not sure, @sumeerbhola can you confirm?

**Comment by jbowens** [comment]
> Not sure, @sumeerbhola can you confirm?

Yeah, it will

**Review by jbowens — APPROVED** [review]
lgtm

**Pull request merged**
