### PR TITLE
ui: create a cached data reducer that operates on data with ids

### PR DESCRIPTION
**Pull request by maxlang**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7971)

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/redux/keyedCachedDataReducer.ts, line 15 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNYoCb0Ebcp30XDJ6iS:-KNYoCb1126jfpe4-85T:1339989076) ([raw file](https://github.com/cockroachdb/cockroach/blob/072ab71c330e8dfa7473d21e9edf0e8fa53566d0/ui/app/redux/keyedCachedDataReducer.ts#L15)):*
> ```XML
> }
> 
> export class KeyedCachedDataReducer<TRequest, TResponseMessage> extends CachedDataReducer<TRequest, TResponseMessage> {
> ```

*desperately* needs a comment.  The behavior here is way too complicated; the class is polymorphic (which I don't like with a non-abstract base), and the idGenerator input is not documented.

By the way, what do you save by making this polymorphic? Can the KeyedCachedReducer just contain a CachedReducer that it uses internally?  Then you wouldn't have to change any methods of existing CachedReducers; all of those `null` arguments are suspect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by maxlang** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/app/redux/keyedCachedDataReducer.ts, line 15 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNYoCb0Ebcp30XDJ6iS:-KNbukg61JKxMEXESMyv:-1771651367) ([raw file](https://github.com/cockroachdb/cockroach/blob/072ab71c330e8dfa7473d21e9edf0e8fa53566d0/ui/app/redux/keyedCachedDataReducer.ts#L15)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> *desperately* needs a comment.  The behavior here is way too complicated; the class is polymorphic (which I don't like with a non-abstract base), and the idGenerator input is not documented.
> 
> By the way, what do you save by making this polymorphic? Can the KeyedCachedReducer just contain a CachedReducer that it uses internally?  Then you wouldn't have to change any methods of existing CachedReducers; all of those `null` arguments are suspect.
</details>
Ok I combined them into one reducer and tried to comment it up a bit. Let me know if it needs more, since there's some confusing branching logic going on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 4 of 12 files at r1, 3 of 7 files at r2, 4 of 7 files at r3.
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/app/interfaces/action.d.ts, line 18 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNksn4wBCEePETBXHky:-KNksn4wBCEePETBXHkz:-530766331) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/interfaces/action.d.ts#L18)):*
> ```XML
> 
> /**
>  * WithID implements the very common case of an action payload that an
> ```

"has"

---

*[ui/app/redux/apiReducers.spec.ts, line 7 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNkstu1BE3YYMOnl5pP:-KNkstu1BE3YYMOnl5pQ:-2057908159) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.spec.ts#L7)):*
> ```XML
> describe("table id generator", function () {
>   it("generates encoded db/table id", function () {
>     assert.equal(generateTableID("a.a.a.a", "a.a.a"), encodeURIComponent("a.a.a.a") + "/" + encodeURIComponent("a.a.a"));
> ```

extract the string "a.a.a.a" into a local const and use a more interesting one so that encodeURIComponent has to do something.

---

*[ui/app/redux/apiReducers.spec.ts, line 13 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNkt5N8ZtUbj_-Up8-y:-KNkt5N9q7S-Yvm6pbCW:562411710) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.spec.ts#L13)):*
> ```XML
> describe("request to string functions", function () {
>   it("correctly generates a string from a database details request", function () {
>     let database = "testDatabase";
> ```

nit: all these `let`s are `const`s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 1 of 7 files at r3.
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[ui/app/redux/apiReducers.ts, line 60 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOHR_zXtvX3lBnID4:-KNlOHR_zXtvX3lBnID5:1540285257) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L60)):*
> ```XML
> // NOTE: We encode the db and table name so we can combine them as a string.
> // TODO(maxlang): there's probably a nicer way to do this
> export function generateTableID(db: string, table: string) {
> ```

why is this exported? i'm not even sure why it's a separate function.

---

*[ui/app/redux/apiReducers.ts, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOdqbLvbubRFpT3lq:-KNlOdqbLvbubRFpT3lr:248882954) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L66)):*
> ```XML
> export let tableRequestToID = (req: TableDetailsRequest): string => generateTableID(req.database, req.table);
> 
> export let tableDetailsReducerObj = new CachedDataReducer<TableDetailsRequest, TableDetailsResponseMessage>(api.getTableDetails, "tableDetails", tableRequestToID);
> ```

a bunch of these guys are needlessly exported?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by maxlang** [comment]
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[ui/app/interfaces/action.d.ts, line 18 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNksn4wBCEePETBXHky:-KNsnFZPWz_Ki1YfOwPs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/interfaces/action.d.ts#L18)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "has"
</details>
Done.

---

*[ui/app/redux/apiReducers.spec.ts, line 7 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNkstu1BE3YYMOnl5pP:-KNspzU-g8nUT8Eqkw2h:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.spec.ts#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> extract the string "a.a.a.a" into a local const and use a more interesting one so that encodeURIComponent has to do something.
</details>
Done.

---

*[ui/app/redux/apiReducers.spec.ts, line 13 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNkt5N8ZtUbj_-Up8-y:-KNsnJDhqzSZ6y7hoSeb:-241245490) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.spec.ts#L13)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: all these `let`s are `const`s
</details>
Happy do start doing this going forward as well. Most of our `let`s could be `const`s but I've just been in the habit of using `let`.

Done.

---

*[ui/app/redux/apiReducers.ts, line 60 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOHR_zXtvX3lBnID4:-KNsqEhy9KOtLylKZPBY:-721448087) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L60)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why is this exported? i'm not even sure why it's a separate function.
</details>
It's separate/exported so it can be tested. It was a personal sanity check.

---

*[ui/app/redux/apiReducers.ts, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOdqbLvbubRFpT3lq:-KNsqblkqfKxw8-s4JwG:-710406240) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> a bunch of these guys are needlessly exported?
</details>
I think we used to use the exports before your change indicating the shape of `APIReducerState`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r4.
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 60 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOHR_zXtvX3lBnID4:-KNss_a2pg0ca9N3VoiQ:-213119021) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L60)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> It's separate/exported so it can be tested. It was a personal sanity check.
</details>
right but the function that uses it is basically trivial. why not just test _that_?

---

*[ui/app/redux/apiReducers.ts, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOdqbLvbubRFpT3lq:-KNssgYdQQpv5Yh3n13F:355191953) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L66)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I think we used to use the exports before your change indicating the shape of `APIReducerState`?
</details>
Dunno. Also, can these `let`s be consts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by mrtracy** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/app/redux/cachedDataReducer.ts, line 21 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KO1w-DQFsvcB8Enfldh:-KO1w-DQFsvcB8Enfldi:127457162) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9334bdb1328ba2e6c2baf76147e2a936fdc1f21/ui/app/redux/cachedDataReducer.ts#L21)):*
> ```XML
> // KeyedCachedDataReducerState is used to track the state of the cached data
> // that is associated with a key.
> export class KeyedCachedDataReducerState<TResponseMessage> {
> ```

So this is the opposite of the pattern we discussed earlier; this is a KeyedCachedDataReducer that contains CachedDataReducers at each key.  I suggested the opposite; creating a KeyedCachedDataReducer at the bottom level, and then the CachedDataReducer manages an *internal* KeyedCachedDataReducer that contains only one key.

I think it would make this code much clearer to explicitly make Keyed and Unkeyed reducers separate classes; as it is, you have a single class that behaves significantly different depending on if "idGenerator" exists or not.  There are numerous if statements and ternary operators inside of this class that alter its behavior; it is confusing to read.

Just interested to hear your thoughts on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by maxlang** [comment]
Review status: 9 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 60 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOHR_zXtvX3lBnID4:-KO2UXqKuy-Uwg2Ih1-u:1166439132) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L60)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> right but the function that uses it is basically trivial. why not just test _that_?
</details>
I forgot, it's also used in `tableDetails.tsx` to determine the id based on the url params.

---

*[ui/app/redux/apiReducers.ts, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KNlOdqbLvbubRFpT3lq:-KO2VChLsVKygf8y0uuk:-254470828) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d2ad45c2cf5262e031286ace1b3a6304c058ce/ui/app/redux/apiReducers.ts#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Dunno. Also, can these `let`s be consts?
</details>
Sure? But so can a ton of other `let`s. I guess we'll just change them as we go.

---

*[ui/app/redux/cachedDataReducer.ts, line 21 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KO1w-DQFsvcB8Enfldh:-KO4C-9E0Fqo9cprl16K:-1499250171) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9334bdb1328ba2e6c2baf76147e2a936fdc1f21/ui/app/redux/cachedDataReducer.ts#L21)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> So this is the opposite of the pattern we discussed earlier; this is a KeyedCachedDataReducer that contains CachedDataReducers at each key.  I suggested the opposite; creating a KeyedCachedDataReducer at the bottom level, and then the CachedDataReducer manages an *internal* KeyedCachedDataReducer that contains only one key.
> 
> I think it would make this code much clearer to explicitly make Keyed and Unkeyed reducers separate classes; as it is, you have a single class that behaves significantly different depending on if "idGenerator" exists or not.  There are numerous if statements and ternary operators inside of this class that alter its behavior; it is confusing to read.
> 
> Just interested to hear your thoughts on this.
</details>
I started implementing the way we'd discussed, or at least the way I thought we'd discussed, but I didn't like the extra unnecessary key that complicated the code elsewhere. Wherever the state was accessed I had to import the default key and add an extra null check and lookup and it just felt messy.

The `reducer` and `refresh` functions are shared exactly between the two classes, and the main difference is just that the payloads are wrapped with an ID. I've pulled that logic out to another function so the difference between the two is just two functions (barring the slight magic to keep the constructors simpler) and the fact that you have to use `keyedReducer` instead of `reducer`.

I'm happy to use one extra class to distinguish `KeyedCachedDataReducer` from `CachedDataReducer` so that both export a method named `reducer` but overall I find that the overlap is pretty large so I don't think it's necessary to have the extra complexity live in the state (with the unnecessary default key) which is what developers will be working with more frequently anyway.

I can also add some more comments to make it clear that the behavior is slightly different depending on whether it's "keyed" or not. I don't think the code is that difficult to read once you get the basic idea that it's nesting the state under an ID if it has a way to generate that ID, and it, accordingly, needs to wrap data with the ID when creating the actions, and unwrap them in the reducer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 3 of 5 files at r5.
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by maxlang** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/cachedDataReducer.ts, line 21 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KO1w-DQFsvcB8Enfldh:-KOH8NZq3HJnM01dbkI1:-1698035178) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9334bdb1328ba2e6c2baf76147e2a936fdc1f21/ui/app/redux/cachedDataReducer.ts#L21)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I started implementing the way we'd discussed, or at least the way I thought we'd discussed, but I didn't like the extra unnecessary key that complicated the code elsewhere. Wherever the state was accessed I had to import the default key and add an extra null check and lookup and it just felt messy.
> 
> The `reducer` and `refresh` functions are shared exactly between the two classes, and the main difference is just that the payloads are wrapped with an ID. I've pulled that logic out to another function so the difference between the two is just two functions (barring the slight magic to keep the constructors simpler) and the fact that you have to use `keyedReducer` instead of `reducer`.
> 
> I'm happy to use one extra class to distinguish `KeyedCachedDataReducer` from `CachedDataReducer` so that both export a method named `reducer` but overall I find that the overlap is pretty large so I don't think it's necessary to have the extra complexity live in the state (with the unnecessary default key) which is what developers will be working with more frequently anyway.
> 
> I can also add some more comments to make it clear that the behavior is slightly different depending on whether it's "keyed" or not. I don't think the code is that difficult to read once you get the basic idea that it's nesting the state under an ID if it has a way to generate that ID, and it, accordingly, needs to wrap data with the ID when creating the actions, and unwrap them in the reducer.
</details>
After discussing this a bit in person, I re-separated `CachedDataReducer` and `KeyedCachedDataReducer`. `KeyedCachedDataReducer` now contains a `CachedDataReducer` (because this keeps the state simpler) but the logic in `CachedDataReducer` is now generic enough that it works for both without needing to switch based on the presence of `requestToID` (previously called `idGenerator`.) The only difference between the two is the default `stateAccessor` function that is passed in to `refresh` and overrides how the reducer accesses its relevant state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 5 of 6 files at r6.
Review status: 12 of 13 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[ui/app/redux/cachedDataReducer.ts, line 44 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHOzU9IPBAIKeSR3U7:-KOHOzUA03PazBjAz_1p:-971917176) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L44)):*
> ```XML
> 
>   /**
>    *  There are two constructors for CachedDataReducer.
> ```

is this still true?

---

*[ui/app/redux/cachedDataReducer.ts, line 106 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNKbMBtcHflVy-JVf:-KOHNKbNKK86105wDFE5:2053036069) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L106)):*
> ```XML
> 
>   // receiveData is the RECEIVE action creator.
>   receiveData = (data: TResponseMessage, request: TRequest): PayloadAction<WithRequest<TResponseMessage, TRequest>> => {
> ```

can you flip the args and call them `request, response`?

---

*[ui/app/redux/cachedDataReducer.ts, line 139 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNZ51KEgOG0ypxbXF:-KOHNOyrQUfvOcjQ_B48:697229729) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L139)):*
> ```XML
>    * stateAccessor (optional) - a helper function that accesses this reducer's state given the global state object
>    */
>   refresh = <S>(req?: TRequest, stateAccessor = (state: any, r: TRequest) => state.cachedData[this.actionNamespace]) => {
> ```

you can call this `r` `req`, there's no collision =/

---

*[ui/app/redux/cachedDataReducer.ts, line 167 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNfFXg11YKR5JNM_F:-KOHNfFXg11YKR5JNM_G:88218465) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L167)):*
> ```XML
> 
> /**
>  * KeyedCachedDataReducer is a wrapper object that contains a redux reducer and an instance of CachedDataReducer.
> ```

can you wrap all these comments at 80? That's the convention we use in Go, I don't see a reason to deviate.

---

*[ui/app/redux/cachedDataReducer.ts, line 178 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHP0ZfzVIembc1ZL4d:-KOHP0ZfzVIembc1ZL4e:1564153266) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L178)):*
> ```XML
> 
>   /**
>    *  There are two constructors for CachedDataReducer.
> ```

is this still true? this is a different class now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by mrtracy** [comment]
The underlying pattern is much better now; LGTM module tamir's comments.

---

Review status: 12 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-:-KORHKobtv2FPFC7pe9s:b-gyjreo)*

**Comment by tamird** [comment]
Reviewed 1 of 6 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[ui/app/redux/cachedDataReducer.spec.ts, line 25 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KORHtP8b40gPKW7QVCW:-KORHtP8b40gPKW7QVCX:b-2fxxs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.spec.ts#L25)):*
> ```XML
>     describe("actions", function () {
>       it("requestData() creates the correct action type.", function () {
>         assert.equal(testReducerObj.requestData(null).type, testReducerObj.REQUEST);
> ```

all these nulls here are making me nervous in light of future hops of strictNullChecks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by maxlang** [comment]
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/cachedDataReducer.spec.ts, line 25 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KORHtP8b40gPKW7QVCW:-KOVa6OwKgUKj2IsF8mn:b-56hb7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.spec.ts#L25)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> all these nulls here are making me nervous in light of future hops of strictNullChecks
</details>
We can deal with that when we're ready to turn that on. It's not really a priority right now, and these are easy enough to track down. 

I removed some of the `null`s since the request is optional.

---

*[ui/app/redux/cachedDataReducer.ts, line 44 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHOzU9IPBAIKeSR3U7:-KOVaD3c03mA-myAqqz8:bha46wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this still true?
</details>
Ah whoops, not anymore.

---

*[ui/app/redux/cachedDataReducer.ts, line 106 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNKbMBtcHflVy-JVf:-KOVemnxMdl6-qlmoX-W:b-qkobf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L106)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you flip the args and call them `request, response`?
</details>
The pattern for all the action creators is (payload, request) because the payload is more important than the request which may be `null/undefined`. I added `?` to drive this home.

---

*[ui/app/redux/cachedDataReducer.ts, line 139 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNZ51KEgOG0ypxbXF:-KOVacUOLSO2SFcYD-Gx:b-d5qdpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L139)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you can call this `r` `req`, there's no collision =/
</details>
Annoyingly there actually is a collision.

---

*[ui/app/redux/cachedDataReducer.ts, line 167 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHNfFXg11YKR5JNM_F:-KOVeMhF0CETKV9cKv-c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L167)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you wrap all these comments at 80? That's the convention we use in Go, I don't see a reason to deviate.
</details>
Done.

---

*[ui/app/redux/cachedDataReducer.ts, line 178 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971#-KOHP0ZfzVIembc1ZL4d:-KOVh7lAFTzVTz0rXX5P:b-53co2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/11e2ea8fbe66b7ef66dab4f0b828bb4dd8c7501d/ui/app/redux/cachedDataReducer.ts#L178)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this still true? this is a different class now.
</details>
Ah bad copy/paste.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7971)*

**Pull request merged**
