### PR TITLE
roachprod: alternative fast DNS lookup

### PR DESCRIPTION
**Pull request by herkolategan**
Previously, all DNS lookups were done via `gcloud` CLI to provide stability for
roachtest and avoid flaky DNS servers. This change adds the ability to perform
lookups through Go's standard net tools if `config.FastDNS` is set to true.

`roachprod` CLI will default to enabling `FastDNS` whereas `roachtest` will
only use the cloud provider's utilities for stability.

Release Note: None
Epic: None

### CODE REVIEW

**Comment by srosenberg** [comment]
> Previously, all DNS lookups were done via `gcloud` CLI to provide stability for roachtest and avoid flaky DNS servers. This change adds the ability to perform lookups through Go's standard net tools if `config.FastDNS` is set to true.
> 

What's the expected (relative) latency of `config.FastDNS`? Is there some other context for this optimization? i.e., are there cases where CLI induces timeouts?

**Comment by herkolategan** [comment]
>What's the expected (relative) latency of config.FastDNS

I measured this locally, the difference is about ~1.5 seconds for roachprod ip / pgurl. With the gcloud version taking ~2 - 3 seconds, and the net lookup version taking ~1.5 - 2 seconds total. I'll post the results as part of the commit.

**Review by DarrylWong — APPROVED** [review]
Related question, do you know how much time is spent waiting for records to be available? Seems dependent on how often it needs to retry of course, but it seems to me that if you have to retry a few times then you're not saving any time? Or is it that in those cases GCloud CLI takes longer as well?

Change itself LGTM!

**Comment by herkolategan** [comment]
> Related question, do you know how much time is spent waiting for records to be available? Seems dependent on how often it needs to retry of course, but it seems to me that if you have to retry a few times then you're not saving any time? Or is it that in those cases GCloud CLI takes longer as well?
> 
> Change itself LGTM!

Good question, the wait for records to become available is part of the `starting a cluster/cockroach` cost, which is long in any case and makes multiple calls via ssh etc.

The cost we are trying to reduce here is for light commands like ip / pgurl - where we don't wait for records anymore but will just check for its existence.

**Review by renatolabs — APPROVED** [review]

**Comment by herkolategan** [comment]
TFTRs!

bors r=DarrylWong,renatolabs

**Pull request merged**
