### PR TITLE
distsql: add processor IDs

### LINKED ISSUE #25301: distsql: add processor IDs
These should be generated at the planning stage in a similar manner to [`StageID`](https://github.com/cockroachdb/cockroach/blob/f548ce2fa02d6d2013246be0c86d4fe5fbe0ece1/pkg/sql/distsql_physical_planner.go#L951).

Uses:
- Display this ID on the visual query plan.
- Annotate spans with this ID, associated stats can then be displayed on the visual query plan on the processor with the matching ID.
- Log this ID. When debugging issues, parsing log statements and referring to the visual query plan for the associated ID will help in creating a mind map of the query state at the time of the issue.

### PR DESCRIPTION
**Pull request by asubiotto**
Closes #25301

This change also adds processor ids to log and span tags for
identification and stat parsing, respectively.

Release note: None

cc @RaduBerinde 

There are still some changes to test files that need to be made but putting this up for feedback.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZImcuCaG2_9FyTNfa:-LCZImcuCaG2_9FyTNfb:b2kcb9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/864bc2b6603e127c31d9edde7954d104c7ac41cd/pkg/sql/distsqlplan/physical_plan.go#L127)):*
> ```Go
> 	p.processorCounter++
> 	proc.Spec.ProcessorID = p.processorCounter
> 	p.Processors = append(p.Processors, proc)
> ```

Can't we assign IDs when we finalize the plan, and just use the index in `p.Processors`?

---

*[pkg/sql/distsqlplan/physical_plan.go, line 853 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZIz4W4PvBuCZazKoo:-LCZIz4W4PvBuCZazKop:b8kbdzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/864bc2b6603e127c31d9edde7954d104c7ac41cd/pkg/sql/distsqlplan/physical_plan.go#L853)):*
> ```Go
> 			},
> 		}
> 		// TODO(asubiotto): Any reason why AddProcessor wasn't called?
> ```

I don't think so, it just didn't do anything more for us

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZJIuVAMwSusikhHi9:-LCZJIuVAMwSusikhHiA:b2x7vds) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f0ac4835320748f8ea07fde3dd23a66c2ad1d/pkg/sql/distsqlrun/flow_diagram.go#L437)):*
> ```Go
> 			// Add processor ID before summary details.
> 			proc.Core.Details = append(
> 				proc.Core.Details, fmt.Sprintf("Processor ID: %d", p.ProcessorID),
> ```

This seems very verbose.. maybe we could include just the number in the title (e.g. `0: TableReader` or `TableReader (0)`).

Do you have an example of a diagram generated with the new code?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25513)*

**Comment by asubiotto** [comment]
Here's a screenshot:


---

Review status: 0 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZImcuCaG2_9FyTNfa:-LCZseiKCdBMrQBaMHmT:bc1k7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/864bc2b6603e127c31d9edde7954d104c7ac41cd/pkg/sql/distsqlplan/physical_plan.go#L127)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can't we assign IDs when we finalize the plan, and just use the index in `p.Processors`?
</blockquote></details>

Done. Much simpler, thanks!

---

*[pkg/sql/distsqlplan/physical_plan.go, line 853 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZIz4W4PvBuCZazKoo:-LCZsiON1BB0zwzV8CEo:b-d8tukk) ([raw file](https://github.com/cockroachdb/cockroach/blob/864bc2b6603e127c31d9edde7954d104c7ac41cd/pkg/sql/distsqlplan/physical_plan.go#L853)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think so, it just didn't do anything more for us
</blockquote></details>

Keeping as is because I changed the ID assignment to be in `FinalizePlan`.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LCZJIuVAMwSusikhHi9:-LCZt1pG-ot3Bgs0hGzP:b-y0mmq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/039f0ac4835320748f8ea07fde3dd23a66c2ad1d/pkg/sql/distsqlrun/flow_diagram.go#L437)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems very verbose.. maybe we could include just the number in the title (e.g. `0: TableReader` or `TableReader (0)`).

Do you have an example of a diagram generated with the new code?
</blockquote></details>

Sorry, I took a screenshot but forgot to upload it. I changed it to `Tablereader/0` to be in line with the log messages and uploaded a screenshot.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-:-LCZxeqo3xi9N2P4Of6F:b-9ol3nx)*

**Comment by solongordon** [comment]
:lgtm:

The display format is a little confusing to me. "TableReader/4" makes it sound like it's the 4th TableReader. "4. TableReader" or "4: TableReader" might be clearer. But if the slash syntax is to match the logs that's fine with me.

---

Review status: 0 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.go, line 775 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LD2nJ62DNmrzRiNS8IW:-LD2nJ62DNmrzRiNS8IX:b-3628s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f47a84adf4a7a5eb592a915f4aa650d6e98e50f3/pkg/sql/distsqlrun/processors.go#L775)):*
> ```Go
> func (pb *processorBase) startInternal(ctx context.Context, name string) context.Context {
> 	logTag := procNameToLogTag[name]
> 	logTag += fmt.Sprintf("/%d", pb.processorID)
> ```

readability nit:
```
logTag := fmt.Sprintf("%s/%d", procNameToLogTag[name], pb.processorID)
```

---

*[pkg/sql/distsqlrun/processors.proto, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LD2noe26BlOUB_XD0ba:-LD2noe26BlOUB_XD0bb:b-bmrvfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f47a84adf4a7a5eb592a915f4aa650d6e98e50f3/pkg/sql/distsqlrun/processors.proto#L74)):*
> ```protobuf
>                                (gogoproto.customname) = "StageID"];
> 
>   optional int32 processor_id = 6 [(gogoproto.nullable) = false,
> ```

Add a comment about what ProcessorID is used for?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-:-LD2o1b01oS-3BLZACHv:b-7bb5yd)*

**Comment by jordanlewis** [comment]
:lgtm: mod Solon's concerns

---

Reviewed 26 of 27 files at r1, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.go, line 775 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LD2nJ62DNmrzRiNS8IW:-LD3gNyI1TZSz1_ii9yb:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/f47a84adf4a7a5eb592a915f4aa650d6e98e50f3/pkg/sql/distsqlrun/processors.go#L775)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

readability nit:
```
logTag := fmt.Sprintf("%s/%d", procNameToLogTag[name], pb.processorID)
```
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-:-LD3gY-24mhFdETOYT7I:bg59k2t)*

**Comment by asubiotto** [comment]
Review status: 20 of 56 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/distsqlrun/processors.go, line 775 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LD2nJ62DNmrzRiNS8IW:-LD3UBKY0jGvEu4XLzRX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f47a84adf4a7a5eb592a915f4aa650d6e98e50f3/pkg/sql/distsqlrun/processors.go#L775)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

readability nit:
```
logTag := fmt.Sprintf("%s/%d", procNameToLogTag[name], pb.processorID)
```
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25513#-LD2noe26BlOUB_XD0ba:-LD3VitFCCoJUXrUExx2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f47a84adf4a7a5eb592a915f4aa650d6e98e50f3/pkg/sql/distsqlrun/processors.proto#L74)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Add a comment about what ProcessorID is used for?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25513)*

**Pull request merged**
