### PR TITLE
move sql.ClusterWideID to clusterunique.ID

### PR DESCRIPTION
**Pull request by matthewtodd**
This move breaks a dependency cycle to allow the upcoming outliers
subsystem to use these ids, see #80503.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Nicely done!

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80667#-:-N0kIzC-632K6Q71aFyq:b-msncp4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80667#-:-N0kKHr8CihmJ3dxlRgW:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by matthewtodd** [comment]
Thanks, all!

bors r+

**Pull request merged**
