### PR TITLE
ui: Network latency tooltip

### LINKED ISSUE #45228: ui: Add line break to localities on Network latency tooltip + style updates
Update latency tool tips. [Designs here](https://www.figma.com/file/7ibbkObA1alv7Q3htOcG4l/obsrv_admin-ui-network-latency?node-id=1100%3A2688)

- [ ] tooltip width should be ~384px wide 
- [ ] Break locality info onto separate lines 
- [ ] Update all text in tooltip to Source Sans Pro (related to #45471) 
- [ ] Update time stamp colors (ie. 27.03ms roundtrip):  
     - `Disconnected`= `#FFCD02`  
     - `Mean` = `#E7ECF3` 
     - `< -1` and `< -2` = `#76DE49`
     - `> +1` and `> +2` = `#74BDFD`

Network-Latency-06

### PR DESCRIPTION
**Pull request by vladlos**
Updated tooltip styles.

Resolves: #45228

Release note (ui): none

### CODE REVIEW

**Comment by nathanstilwell** [comment]
I'm finding this one hard to test. Using `roachprod` to run 4 local clusters I was able to give it a try, and when I shut down Node 3, I'm seeing the chips showing up as green.

Screen Shot 2020-03-05 at 16 28 25

Upon inspecting the chips, I see `<span class="Chip Chip--green yellow">--</span>` which seems like `type` classname is both `green` and `yellow` in this block,

```
  const type: any = classNames({
    "green":
      std.stddev > 0 && latency < std.stddevMinus2,
    "lightgreen":
      std.stddev > 0 && latency < std.stddevMinus1 && latency >= std.stddevMinus2,
    "grey":
      std.stddev > 0 && latency >= std.stddevMinus1 && latency <= std.stddevPlus1,
    "lightblue":
      std.stddev > 0 && latency > std.stddevPlus1 && latency <= std.stddevPlus2,
    "blue":
      std.stddev > 0 && latency > std.stddevPlus2,
    "yellow":
      latency === -2,
  });
```

from debugging, I can see the values of ...

```
std: {
  stddev: 0.03362820156951603
  stddevMinus2: 0.5842825968609678
  stddevMinus1: 0.6179107984304839
  stddevPlus1: 0.685167201569516
  stddevPlus2: 0.7187954031390321
},
latency: -2
```

To help with reproduction, install [roachprod](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachprod) (you may not have to setup `gcloud` if you are only running local clusters)

Then I ran,

```
> roachprod create local; # to create the cluster
> roachprod start local; # I had to start the nodes for some reason
> roachprod status local; # to see what the ports were so that I could `make ui-watch TARGET=http://localhost:[port]`
```

then, to stop a node (in this case I stopped 3)

```
> roachprod stop local:3;
```

**Review by nathanstilwell — CHANGES_REQUESTED** [review]
See comment with screenshot

**Comment by elkmaster** [comment]
tooltip

**Review by dhartunian — CHANGES_REQUESTED** [review]
@elkmaster can we add some storybook components illustrating the scenario in @nathanstilwell's comments. Would be great to see all the possible colors and multi-region tooltips in one story!

Sorry this PR has sat around forever. It's mostly because it's complex to test so I'm hoping the storybook renders will help :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45638#-:-M3fquEZDPIM_GmwqpXB:b-mwpzu)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by elkmaster** [comment]
@dhartunian, added storybook for latency table, display all possible chip state

**Review by dhartunian — CHANGES_REQUESTED** [review]
Thanks for adding these!

Given the bug we just had, can you make a second story with empty localities and ensure it renders correctly?

In cases where the activity is empty and the color is the light orange, the tooltip still shows "-2ms".


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45638#-:-M7h-QJkC6bj-IpCoUK_:b-x6xuxk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by elkmaster** [comment]
removed `roundrip` if it less than 0
Screenshot 2020-05-20 at 18 04 56

examples of table with no localities
Screenshot 2020-05-20 at 18 04 41
Screenshot 2020-05-20 at 18 04 48

**Review by dhartunian — APPROVED** [review]
Thanks @elkmaster.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45638#-:-M7moS0r9ZQx_WAq7CQU:b-qz7u8a)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
