### PR TITLE
server: enable test cluster to take different store configurations

### PR DESCRIPTION
**Pull request by BramGruneir**
2 commits:
- base/server: move store_spec from server to base
  This move will allow us to configure testclusters with store level granularity
  which would otherwise cause circular dependencies.
- server: enable testserver to take different store configurations
  testServerArgs will now take StoreSpecs instead of just a number of stores.
  This also adds StoreSpecsPerNode on testClusterArgs to enable per node store
  settings. Currently, only in-memory stores are supported.

Part of work towards #8473.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8817)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[acceptance/cluster/localcluster.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1v2OUr2cXNis7u1v-:-KQ1v2OUr2cXNis7u1v0:b5a7co8) ([raw file](https://github.com/cockroachdb/cockroach/blob/988c2e9ce75d9b36d96970a0ee69cd790bf77993/acceptance/cluster/localcluster.go#L47)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/rpc"
> 	"github.com/cockroachdb/cockroach/security"
> 	"github.com/cockroachdb/cockroach/server"
> ```

I forgot `localcluster` existed. Do you know who uses this?

---

*[base/store_spec.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1vDHg5Ytwj0xWVkPr:-KQ1vDHg5Ytwj0xWVkPs:b-op5sg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/81305f15ffcb069d3dea5db2c8d93a9feaeaf1f8/base/store_spec.go#L37)):*
> ```Go
> 
> // MinimumStoreSize is the smallest size in bytes that a store can have. This
> // number was originally based on config's defaultZoneConfig's RangeMaxBytes,
> ```

nit: "originally" is confusing here, makes one think it's not based on that any more (even though in spirit it still is). I'd strip it.

---

*[base/test_server_args.go, line 83 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1vtc6RHpqfjfHd0Vv:-KQ1vtc6RHpqfjfHd0Vw:bpvv73) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/base/test_server_args.go#L83)):*
> ```Go
> 
> 	// StoreSpecsPerNode adds specific stores to specific nodes. The map's keys
> 	// match the node number passed into StartTestCluster. These work in
> ```

nit: "match a node's index within TestCluster.Servers"

---

*[base/test_server_args.go, line 86 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1w92CGFiHCT4tTbdW:-KQ1w92CGFiHCT4tTbdX:b-mocz7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/base/test_server_args.go#L86)):*
> ```Go
> 	// conjunction with the StoreSpecs already in TestServerArgs and can be
> 	// used to supplement those stores that are already on all nodes.
> 	StoreSpecsPerNode map[int][]StoreSpec
> ```

hmmm so what if I want to overwrite the stores on a node (in particular the default store)?
I vote we keep these structures normalized, even though that's pedantic (but since nobody seems to actually even be using this field now, it won't matter). So make `ServerArgs` an array (with the asterisk that you can put a single item in there and it'll be copied to every Server) and then you can customize each Server as you wish.

---

*[server/status_test.go, line 155 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1xmQBOIue0ltnUn_w:-KQ1xmQBOIue0ltnUn_x:bxt544x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/server/status_test.go#L155)):*
> ```Go
> func startServer(t *testing.T) *TestServer {
> 	tsI, _, kvDB := serverutils.StartServer(t, base.TestServerArgs{
> 		StoreSpecs: []base.StoreSpec{
> ```

if you happen to know, please add a comment here as to why this tests needs or wants multiple stores.

---

*[server/testserver.go, line 235 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1y4mWB4e3Z_V4cKz_:-KQ1y4mWB4e3Z_V4cKza:bxa5jee) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/server/testserver.go#L235)):*
> ```Go
> 			))
> 		} else {
> 			panic(fmt.Sprintf("test server does not yet support in non-memory stores: %s", storeSpec))
> ```

just curious, why not? Just the lack of cleanup code? Maybe add a comment if you know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817)*

**Comment by BramGruneir** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[acceptance/cluster/localcluster.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1v2OUr2cXNis7u1v-:-KQ1zT02LrXuPEY_62Ew:b-hbi24) ([raw file](https://github.com/cockroachdb/cockroach/blob/988c2e9ce75d9b36d96970a0ee69cd790bf77993/acceptance/cluster/localcluster.go#L47)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I forgot `localcluster` existed. Do you know who uses this?
</details>
This is all acceptance tests.  Local docker runs that is.

---

*[base/store_spec.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1vDHg5Ytwj0xWVkPr:-KQ1zpP5iGttrs9rQoI8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81305f15ffcb069d3dea5db2c8d93a9feaeaf1f8/base/store_spec.go#L37)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nit: "originally" is confusing here, makes one think it's not based on that any more (even though in spirit it still is). I'd strip it.
</details>
Done.

---

*[base/test_server_args.go, line 83 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1vtc6RHpqfjfHd0Vv:-KQ2AQlYLFURoaJ3xrmR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/base/test_server_args.go#L83)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> nit: "match a node's index within TestCluster.Servers"
</details>
Done.

---

*[base/test_server_args.go, line 86 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1w92CGFiHCT4tTbdW:-KQ2EDlvA1O6MqqscT4z:bm0ae1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/base/test_server_args.go#L86)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> hmmm so what if I want to overwrite the stores on a node (in particular the default store)?
> I vote we keep these structures normalized, even though that's pedantic (but since nobody seems to actually even be using this field now, it won't matter). So make `ServerArgs` an array (with the asterisk that you can put a single item in there and it'll be copied to every Server) and then you can customize each Server as you wish.
</details>
I just made this an override map of serverArgs.  So we can customize everything.

---

*[server/status_test.go, line 155 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1xmQBOIue0ltnUn_w:-KQ2G5ujNOLkK-TXb7kr:bc3vqhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/server/status_test.go#L155)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> if you happen to know, please add a comment here as to why this tests needs or wants multiple stores.
</details>
Not 100% sure, but I think it's to ensure that metrics are recorded correctly for more than one store per node.

---

*[server/testserver.go, line 235 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ1y4mWB4e3Z_V4cKz_:-KQ2F0nn0vgErTSsSEd2:b-obwf3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c08b6e5de85b5d4ce15cfc9078c8f166d2de9e93/server/testserver.go#L235)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> just curious, why not? Just the lack of cleanup code? Maybe add a comment if you know.
</details>
Done.  And exactly, we need to add cleanup code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-:-KQ2LH9IChZ_OT3wC8CL:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 6 of 7 files at r1, 3 of 6 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[base/store_spec.go, line 40 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2Mg1be0a-IG9luGjy:-KQ2Mg1be0a-IG9luGjz:b3jimnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/base/store_spec.go#L40)):*
> ```Go
> // extremely stable. To avoid adding the dependency on config here, it is just
> // hard coded to 640MiB.
> const MinimumStoreSize = 10 * 64 << 20
> ```

It may be nicer to define this in terms of `config.DefaultZoneConfig`.

---

*[server/testserver.go, line 235 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2MvW6pDZnVUFfs5a-:-KQ2MvW6pDZnVUFfs5a0:b8s8w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/server/testserver.go#L235)):*
> ```Go
> 			))
> 		} else {
> 			// TODO(bram): This will require both cleanup and on failure or if
> ```

there's something not right about this sentence.

---

*[server/testserver.go, line 237 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2N-lpyPWXml0Tws_x:-KQ2N-lpyPWXml0Tws_y:bfcu7fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/server/testserver.go#L237)):*
> ```Go
> 			// TODO(bram): This will require both cleanup and on failure or if
> 			// desired, not cleanup (perhaps on failure).
> 			panic(fmt.Sprintf("test server does not yet support in non-memory stores: %s", storeSpec))
> ```

"in non-memory" is an odd way to say this. "persistent"?

---

*[testutils/testcluster/testcluster.go, line 137 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2NHJRpHjnKtWJLgMC:-KQ2NHJRpHjnKtWJLgMD:b-s3vjln) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/testutils/testcluster/testcluster.go#L137)):*
> ```Go
> 	tc.stopper = stop.NewStopper()
> 
> 	args.ServerArgs.PartOfCluster = true
> ```

shouldn't this have been removed? if not, why was it also added below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817)*

**Comment by BramGruneir** [comment]
@tamird, I'll address your comments in a follow up PR shortly.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-:-KQ2O_E20dUI5s258g0q:b-8aerpm)*

**Comment by BramGruneir** [comment]
Addressed all feedback in #8836

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[base/store_spec.go, line 40 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2Mg1be0a-IG9luGjy:-KQ2OKHyg_k1R8Ov_zcN:b-ffxzz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/base/store_spec.go#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> It may be nicer to define this in terms of `config.DefaultZoneConfig`.
</details>
Nice yes, but that bring in another import to base.  Which I'm trying to avoid.

---

*[server/testserver.go, line 235 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2MvW6pDZnVUFfs5a-:-KQ2WtEWOv4hsdbfTyfO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/server/testserver.go#L235)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's something not right about this sentence.
</details>
Done.

---

*[server/testserver.go, line 237 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2N-lpyPWXml0Tws_x:-KQ2WwPW_cJ9m2StPKPX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/server/testserver.go#L237)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "in non-memory" is an odd way to say this. "persistent"?
</details>
Done.

---

*[testutils/testcluster/testcluster.go, line 137 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-KQ2NHJRpHjnKtWJLgMC:-KQ2WxxlLjd3SwOGgj3u:b-6kl0fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2022bc2932c9eeed50354dbf443f5b784686c2b8/testutils/testcluster/testcluster.go#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this have been removed? if not, why was it also added below?
</details>
PartOfCluster is required to be true when running a cluster.  When starting up a testserver without a testcluster is when the value can be false.  I've added a comment to the struct to denote that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8817#-:-KQ2YTHZAEHahifOE594:bi09x6d)*

**Pull request merged**
