### PR TITLE
docs: detail our commit message guidelines

### PR DESCRIPTION
**Pull request by knz**
Requested/suggested by @jseldess in https://github.com/cockroachdb/docs/pull/2406#issuecomment-360097499.

Release note: none

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[CONTRIBUTING.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dQTXBUU3U_kWfR6wU:-L3dQTXBUU3U_kWfR6wV:bp3voqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L108)):*
> ```Markdown
> https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages
> 
> In summary (not exhaustive - check the linked wiki page if it's your first time):
> ```

If this 8-point summary is "not exhaustive", we have too many rules. We can link to the wiki page for more background/rationale, but you should be able to rely solely on what's in this file. 

---

*[CONTRIBUTING.md, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dNukE9ObVFqrrHD_S:-L3dNukE9ObVFqrrHD_T:b4u9aif) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L115)):*
> ```Markdown
> - [Include a release note annotation](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#release-note), in the right position
> - [Use the imperative mood in the subject line](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#commit-title)
> - [Limit the subject line to 50 characters](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#commit-title)
> ```

This is an extremely restrictive rule and we've never followed it (roughly half our commit messages are longer than this). I know it's copied from some standard bit of git guidance, but I don't think it's appropriate for us. 

The rationale for the 50-column limit is so that the message plus some metadata can fit in an 80-column terminal. Since we already use 100 columns instead of 80, we should allow at least 70 columns for the commit title.

---

*[CONTRIBUTING.md, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dPEIemxjHqSsOA6DV:-L3dPEIemxjHqSsOA6DW:bmcs5a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L116)):*
> ```Markdown
> - [Use the imperative mood in the subject line](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#commit-title)
> - [Limit the subject line to 50 characters](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#commit-title)
> - [Wrap the body at 100, preferably 72 characters](https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages#commit-description)
> ```

If 100 is allowed, why is 72 "preferable"? I don't particularly care what limit we have here (or if we have one at all), but there's no reason to have more than one number (this should not be interpreted as "everyone should configure their editors to wrap in exactly the same way". It just isn't that important). "Wrap long lines in the body at no more than 100 characters"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[CONTRIBUTING.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dQTXBUU3U_kWfR6wU:-L3eFxH6sDnOsbL8NGCh:bsz2ebh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L108)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If this 8-point summary is "not exhaustive", we have too many rules. We can link to the wiki page for more background/rationale, but you should be able to rely solely on what's in this file. 
</blockquote></details>

It was exhaustive; the intro sentence was poorly phrased.

---

*[CONTRIBUTING.md, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dNukE9ObVFqrrHD_S:-L3eG08SrPBPH6aWlrDS:bs0vktl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L115)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is an extremely restrictive rule and we've never followed it (roughly half our commit messages are longer than this). I know it's copied from some standard bit of git guidance, but I don't think it's appropriate for us. 

The rationale for the 50-column limit is so that the message plus some metadata can fit in an 80-column terminal. Since we already use 100 columns instead of 80, we should allow at least 70 columns for the commit title.
</blockquote></details>

The rationale is to force the author to think how to keep it as concise as possible. The specific width doesn't really matter. I relaxed the phrasing here; the wiki page clarifies. 

---

*[CONTRIBUTING.md, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-L3dPEIemxjHqSsOA6DV:-L3eG8u7hXneN1iodYJ1:b-75n3hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d115256a4d2a987c0f312e63c87a4086ec2b2b1/CONTRIBUTING.md#L116)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If 100 is allowed, why is 72 "preferable"? I don't particularly care what limit we have here (or if we have one at all), but there's no reason to have more than one number (this should not be interpreted as "everyone should configure their editors to wrap in exactly the same way". It just isn't that important). "Wrap long lines in the body at no more than 100 characters"
</blockquote></details>

Yes, agreed. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-:-L3eQ9QWTmF7wGIVnwpU:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21741#-:-L3eS5slhIOUiVK2RfIi:b-814cj3)*

**Pull request merged**
