### PR TITLE
schemachange/leasing-benchmark: fix benchmark test flakiness

### LINKED ISSUE #121602: roachtest: schemachange/leasing-benchmark failed
roachtest.schemachange/leasing-benchmark [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/14675256?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/14675256?buildTab=artifacts#/schemachange/leasing-benchmark) on master @ [7166724ff02b9b7f0d5787f74d919487ca347bd0](https://github.com/cockroachdb/cockroach/commits/7166724ff02b9b7f0d5787f74d919487ca347bd0):

```
(multiregion_leasing.go:174).runSchemaChangeMultiRegionBenchmarkLeasing: lower than expected improvement in execution time
test artifacts and logs in: /artifacts/schemachange/leasing-benchmark/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=aws</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

_Grafana is not yet available for aws clusters_</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/leasing-benchmark.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37367

### LINKED ISSUE #121856: roachtest: schemachange/leasing-benchmark failed
roachtest.schemachange/leasing-benchmark [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14706006?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14706006?buildTab=artifacts#/schemachange/leasing-benchmark) on release-24.1 @ [ab15ba5ecd31719682e19805ebc03cd291dccf94](https://github.com/cockroachdb/cockroach/commits/ab15ba5ecd31719682e19805ebc03cd291dccf94):

```
(multiregion_leasing.go:161).runSchemaChangeMultiRegionBenchmarkLeasing: Expected session based leasing to be faster with many descriptors (6m34.854173098s > 6m6.338776291s).
test artifacts and logs in: /artifacts/schemachange/leasing-benchmark/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14706006/schemachange-leasing-benchmark/1712340122644/1712341295623)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121602 roachtest: schemachange/leasing-benchmark failed [C-test-failure O-roachtest O-robot P-1 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/leasing-benchmark.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37588

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the benchmark test was having flakes where not enough of a noticeable improvement was being observed. This could happen because of the variability in our test setup since it is sensitive to the latency between the different regions. To address this, this patch will get a more stable result by running the same test 3 times and taking the median. Additionally, it addresses transaction retry errors when creating tables.

Fixes: #121602

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks! just had a small request

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-:-Nuj4gwv47Bzb02NnZMa:b-tox3j9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-Nuj4YqR1ytCOSajG8zv:-Nuj4YqR1ytCOSajG8zw:b6harif) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64216c0b6c0d3994dc2f6b6bb3bb0d57c767ae7/pkg/cmd/roachtest/tests/multiregion_leasing.go#L208)):*
> ```Go
> 
> 	// Track the percentage improvement between the two.
> 	improvementPct := ((durations[1][mid] * 100) / durations[0][mid]) - 100
> ```

it would be useful to log all of the results here, that way we can see how close we were if an error occurs

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121816)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-NukAAIi2lFIqXeXEHDV:-NukAAIi2lFIqXeXEHDW:b-2vmj9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/618de760a4f56ea0f5f2688415794bd8398701f4/pkg/cmd/roachtest/tests/multiregion_leasing.go#L206)):*
> ```Go
> 			"the following percentages %v.",
> 			medianPercentage,
> 			percentages))
> ```

IMO, we should just log the percentages always (in the `t.Status` call below).

otherwise if this fails in the `medianPercentage < 15` case, we won't have any logs showing what the results were. also, i have a slight preference for logging the raw measurements, not the percentages, but up to you
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-NukA_SO7iXR1kaR6nKl:-NukA_SO7iXR1kaR6nKm:b-3i483f) ([raw file](https://github.com/cockroachdb/cockroach/blob/618de760a4f56ea0f5f2688415794bd8398701f4/pkg/cmd/roachtest/tests/multiregion_leasing.go#L210)):*
> ```Go
> 
> 	// Track the percentage improvement between the two.
> 	t.Status(fmt.Sprintf("session based leasing produced an improvement of %d%% "+
> ```

we could just stick this `t.Status` call in a loop that iterates over `durations`

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121816)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-Nuj4YqR1ytCOSajG8zv:-NukEWV70QFLkBBi6kws:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d64216c0b6c0d3994dc2f6b6bb3bb0d57c767ae7/pkg/cmd/roachtest/tests/multiregion_leasing.go#L208)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it would be useful to log all of the results here, that way we can see how close we were if an error occurs
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-NukAAIi2lFIqXeXEHDV:-NukDmRdAHRkbJWhoxST:b-tsr14i) ([raw file](https://github.com/cockroachdb/cockroach/blob/618de760a4f56ea0f5f2688415794bd8398701f4/pkg/cmd/roachtest/tests/multiregion_leasing.go#L206)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

IMO, we should just log the percentages always (in the `t.Status` call below).

otherwise if this fails in the `medianPercentage < 15` case, we won't have any logs showing what the results were. also, i have a slight preference for logging the raw measurements, not the percentages, but up to you
</blockquote></details>

Done.

Good point, and I'll log both
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121816#-NukA_SO7iXR1kaR6nKl:-NukF2mNCRfwV5Sd7J65:b-ux600a) ([raw file](https://github.com/cockroachdb/cockroach/blob/618de760a4f56ea0f5f2688415794bd8398701f4/pkg/cmd/roachtest/tests/multiregion_leasing.go#L210)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we could just stick this `t.Status` call in a loop that iterates over `durations`
</blockquote></details>

Done.

I added this as well.

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Pull request merged**
