### PR TITLE
cli: flag doc updates

### PR DESCRIPTION
**Pull request by knz**
See the individual commits for details.

Epic: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-:-NImuzCb-iCJmgZP9H8M:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/context.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImrDC45OJCwF_JaxED:-NImrDC45OJCwF_JaxEE:b4w1kpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/context.go#L174)):*
> ```Go
> 	// are shutdown, if any are enabled, or until a timeout is triggered.
> 	logShutdownFn func()
> 	// logOverrides encodes the pre-v21.1 discrete flag overrides for
> ```

I think the mention of "pre-v21.1" is confusing. Better say how these related to `logConfig`.
___
*[`pkg/cli/flags.go` line 835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImriSg9MuoWsVVxmd4:-NImriSg9MuoWsVVxmd5:bj383ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/983dc06901a1a89396b02f9e262414a721e68532/pkg/cli/flags.go#L835)):*
> ```Go
> 		cliflagcfg.BoolFlag(f, &demoCtx.NoExampleDatabase, cliflags.UseEmptyDatabase)
> 
> 		// --no-example-database was defined as candidate replacement to --empty
> ```

This comment is very long. How about:
```
// --no-example-database is an old name for --empty.
```
___
*[`pkg/cli/flags.go` line 836 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NIms5v_6RsSTfAeyrCI:-NIms5v_6RsSTfAeyrCJ:btb7nej) ([raw file](https://github.com/cockroachdb/cockroach/blob/983dc06901a1a89396b02f9e262414a721e68532/pkg/cli/flags.go#L836)):*
> ```Go
> 
> 		// --no-example-database was defined as candidate replacement to --empty
> 		// between v21.1 up to and including v22.2, but it never stuck: --empty
> ```

Change `NoExampleDatabase` and `UseEmptyDatabase` to point to each other the other way around.
___
*[`pkg/cli/flags.go` line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImsLFf8rhBri09prUT:-NImsLFf8rhBri09prUU:b-55hhg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L330)):*
> ```Go
> 		cliflagcfg.StringSliceFlag(pf, &cliCtx.logConfigVars, cliflags.LogConfigVars)
> 
> 		// Pre-v21.1 convenience overrides.
> ```

get rid of "pre-v21.1"
___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImstYCBzzkjrk-U9Ru:-NImstYCBzzkjrk-U9Rv:bmijmf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
> ```Go
> 
> 		// Pre-v21.1 convenience overrides.
> 		cliflagcfg.VarFlag(pf, &cliCtx.logOverrides.stderrThreshold, cliflags.StderrThresholdOverride)
> ```

Please add to the flag description saying that this doesn't need an argument, and what it does when specified without an argument.
___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImt1m54BgAnaTbhGft:-NImt1m54BgAnaTbhGfu:bw65q92) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
> ```Go
> 
> 		// Pre-v21.1 convenience overrides.
> 		cliflagcfg.VarFlag(pf, &cliCtx.logOverrides.stderrThreshold, cliflags.StderrThresholdOverride)
> ```

Could we take the kv-distribution channel out of the stderr sink when `--logtostderr` is specified and `--log-config` is not specified?
Or, rather, can we make `--logtostderr` mean
```
       channels: {
INFO: [DEV, OPS], 
WARNING: [HEALTH, STORAGE, SESSIONS, SQL_SCHEMA,
           USER_ADMIN, PRIVILEGES, SENSITIVE_ACCESS, SQL_EXEC, SQL_PERF, SQL_INTERNAL_PERF,
           TELEMETRY,KV_DISTRIBUTION]
}
```
?

Maybe all these flags should be incompatible with `--log-config`, to keep the semantics clear? I guess I'd ignore them if `--log-config` is specified and print a message about it.
Btw, I think we can also remove all except `--logtostderr` and `--redactable-logs`
___
*[`pkg/cli/flags.go` line 349 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImsVpL4sm1lZXoU9YG:-NImsVpL4sm1lZXoU9YH:b69qei) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L349)):*
> ```Go
> 
> 		cliflagcfg.VarFlag(pf, &cliCtx.logOverrides.redactableLogs, cliflags.RedactableLogsOverride)
> 		_ = pf.MarkHidden(cliflags.RedactableLogsOverride.Name)
> ```

I wouldn't hide this flag; it's useful enough.
___
*[`pkg/cli/flags.go` line 790 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImutsX1xhu3slN37p8:-NImutsX1xhu3slN37p9:bfndqvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5609d3a08822ec30e10556d2a191944ab98a66b8/pkg/cli/flags.go#L790)):*
> ```Go
> 		cliflagcfg.VarFlag(f, &demoCtx.demoNodeSQLMemSizeValue, cliflags.DemoNodeSQLMemSize)
> 		cliflagcfg.VarFlag(f, &demoCtx.demoNodeCacheSizeValue, cliflags.DemoNodeCacheSize)
> 		// NB: Insecure for `cockroach demo` is deprecated. See #53404.
> ```

Delete or rephrase this comment?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93255)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/cli/context.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImrDC45OJCwF_JaxED:-NImylYsE9QR4Df5j_ke:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/context.go#L174)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the mention of "pre-v21.1" is confusing. Better say how these related to `logConfig`.
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImriSg9MuoWsVVxmd4:-NImzuEz7mwFnpR2fTDV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/983dc06901a1a89396b02f9e262414a721e68532/pkg/cli/flags.go#L835)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment is very long. How about:
```
// --no-example-database is an old name for --empty.
```
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 836 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NIms5v_6RsSTfAeyrCI:-NImzvMM57TlnxIwqhEd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/983dc06901a1a89396b02f9e262414a721e68532/pkg/cli/flags.go#L836)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Change `NoExampleDatabase` and `UseEmptyDatabase` to point to each other the other way around.
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 330 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImsLFf8rhBri09prUT:-NImyqXX7fEEpJ2P7njC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L330)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

get rid of "pre-v21.1"
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImstYCBzzkjrk-U9Ru:-NImz73l9FXyB2iZRHor:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please add to the flag description saying that this doesn't need an argument, and what it does when specified without an argument.
</blockquote></details>

Done.
___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImt1m54BgAnaTbhGft:-NImz7h3EO2lJ3kKinSg:byzt4do) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
> Maybe all these flags should be incompatible with --log-config, to keep the semantics clear?

I don't have an opinion on this. Today the semantics are clear to me: the overrides apply to the default config, and then the specific config is loaded on top of that and can customize further. We can either make them incompatible or document the behavior better. In any case, I don't believe it's for me to make a decision here any more.

>  I think we can also remove all except --logtostderr and --redactable-logs

Andy was pretty specific about not removing flags. I don't want to litigate this with him further.
___
*[`pkg/cli/flags.go` line 349 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImsVpL4sm1lZXoU9YG:-NImzhrF2Dd4jptZ4th8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L349)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I wouldn't hide this flag; it's useful enough.
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR

bors r=andreimatei

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93255)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImt1m54BgAnaTbhGft:-NIn4qIFCZv2dzcMN6cm:buwrwer) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
> Or, rather, can we make --logtostderr mean

Can we do this part?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93255)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[`pkg/cli/flags.go` line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93255#-NImt1m54BgAnaTbhGft:-NIn5LB15C5T15RXTUld:b-eev6uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac46c565f51f0008c99cf1038786eea91596704/pkg/cli/flags.go#L331)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Or, rather, can we make --logtostderr mean

Can we do this part?
</blockquote></details>

Separate PR.

**Pull request merged**
