### PR TITLE
kvserver: improve system lease observability

### LINKED ISSUE #99472: kvserver: metric and logging to pinpoint liveness leaseholder
**Is your feature request related to a problem? Please describe.**

The `leases.expiration` metric has been useful as a tool to pinpoint the liveness leaseholder, but it's annoying because there are currently two expiration-based ranges: meta1/2 and the liveness range. Also, we're possibly going to have many more expiration-based ranges. The liveness range is very important: we need to have a perfect lease history for it.

**Describe the solution you'd like**

- [ ] Add a metric `leases.liveness` that is 1 if and only if the store has a liveness replica that is active leaseholder.
- [ ] log whenever a liveness lease is applied, especially if it's a non-cooperative acquisition.

x-ref https://github.com/cockroachlabs/support/issues/2182

Jira issue: CRDB-25893

Epic CRDB-27235

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: add `leases.liveness` metric**

This patch adds the metric `leases.liveness` tracking the number of liveness range leases per node (generally 1 or 0). This is useful to find out which node had the liveness lease at a particular time.

I ran a 10k range cluster to look at the CPU cost of the key comparisons, it didn't show up on CPU profiles.

Epic: none
Release note (ops change): added the metric `leases.liveness` showing the number of liveness range leases per node (generally 1 or 0), to track the liveness range leaseholder.
  
**kvserver: log system range lease acquisition**

This patch logs acquisition of meta/liveness range leases to the health log. These leases are critical to cluster health, and during debugging it's useful to know their location over time.

Resolves #99472.

Epic: none
Release note: none

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
bors retry

**Pull request merged**
