### PR TITLE
fix gossip register fail after re-init store with multi-nodes

### PR DESCRIPTION
**Pull request by xiaoyulei**
#3465 fix issue

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3478)

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM. Good catch.

**Comment by bdarnell** [comment]
Is it possible to add a test for this?

**Comment by YuleiXiao** [comment]
OK, let me try to add test.

**Comment by YuleiXiao** [comment]
Hi @bdarnell, I have add a test for this problem. PTAL

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
