### PR TITLE
colrpc: add memory accounting for temporary data in inbox/outbox

### LINKED ISSUE #67051: sql: add memory accounting for temporary memory usage for serialization/deserialization in inbox and outbox
The vectorized engine's inbox and outbox implementations need to do a good deal of serialization and deserialization, to transform the flatbuffer-encapsulated arrow batches into the vectorized engine's in-memory format.

The temporary memory used here is currently not memory accounted, which presents an issue because the temporary memory used can be quite large.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colrpc: fix memory accounting in inbox a bit**

Previously, we forgot to update the allocator once we have deserialized
the batch in the inbox (i.e. we would register only the original
allocation, upon the batch's creation). This could result in
under-accounting for variable length types, and it is now fixed.

Release note: None

**colrpc: add memory accounting for temporary data in inbox/outbox**

Previously, we were missing the memory accounting for the temporary
usage of serialized/deserialized bytes in the inbox/outbox pair. The
worst offense was that in the outbox we reuse the same scratch Bytes
buffer that is never truncated and can only increase in capacity
throughout the lifetime of the outbox, yet it wasn't accounted for. This
commit fixes those omissions.

Fixes: #67051.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm kinda debating whether it's worth adding the memory accounting to the inbox/outbox in the row-by-row engine since it'll require more plumbing and seems less useful. Thoughts?

**Review by cucaroach — APPROVED** [review]
Don't know enough to say but sounds plausible.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-:-MeWx_a1-QdPRBSzi3Ku:b-4knhh0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by cucaroach — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-:-MeWyRSxBDo5WhhFC397:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX4W9n10k2cUT7Vipq:-MeX4W9n10k2cUT7Vipr:b-c3t5zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/inbox.go#L354)):*
> ```Go
> 		// At this point, we have lost all references to the serialized bytes,
> 		// so we update the allocator accordingly.
> 		i.allocator.AdjustMemoryUsage(-numSerializedBytes)
> ```

At this point, don't we still have roughly the same amount of data in `i.scratch.data`? Seems like that doesn't get released until the next call to `Next`. Maybe instead of counting `m.Data` which is so short-lived we should count `i.scratch.data`?
___
*[pkg/sql/colflow/colrpc/outbox.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX7Bvw3FFcqLMUVYrU:-MeX7Bvw3FFcqLMUVYrV:beh9rzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/outbox.go#L118)):*
> ```Go
> 	o.scratch.buf = nil
> 	o.scratch.msg = nil
> 	o.allocator.AdjustMemoryUsage(-o.allocator.Used())
> ```

nit: maybe Allocator should have a Close method that does this?
___
*[pkg/sql/colflow/colrpc/outbox.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX7Oox6WMkUjfS07Dx:-MeX7Ooy1YCBWokuftWD:b-7wbiqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/outbox.go#L305)):*
> ```
> 			if newBufCap := o.scratch.buf.Cap(); newBufCap > oldBufCap {
> 				o.allocator.AdjustMemoryUsage(int64(newBufCap - oldBufCap))
> 			}
> ```

nit: do we need this to be conditional?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @michae2)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX4W9n10k2cUT7Vipq:-MeXBnmCBEozmrz4Dzuo:b-bnnvvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/inbox.go#L354)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

At this point, don't we still have roughly the same amount of data in `i.scratch.data`? Seems like that doesn't get released until the next call to `Next`. Maybe instead of counting `m.Data` which is so short-lived we should count `i.scratch.data`?
</blockquote></details>

Actually `ArrowToBatch` nils out fields in `i.scratch.data`, so I believe that all references to the memory are truly lost and at this point we only have the reference to data inside of `i.scratch.b` which is accounted for. Updated the comment.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX7Bvw3FFcqLMUVYrU:-MeXD5mh6g_tA2gTUz7o:b-ir7oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/outbox.go#L118)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: maybe Allocator should have a Close method that does this?
</blockquote></details>

Hm, I think it might be confusing because `BoundAccount` has `Close` method and `Allocator.Close` currently shouldn't call it because the account is closed on the flow cleanup. I guess my expectation is if we were to introduce `Allocator.Close`, then it must call `Allocator.acc.Close` too which would require changes to other places.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX7Oox6WMkUjfS07Dx:-MeXEAc56dmQWFGTYCjO:byxkpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/outbox.go#L305)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 			if newBufCap := o.scratch.buf.Cap(); newBufCap > oldBufCap {
> 				o.allocator.AdjustMemoryUsage(int64(newBufCap - oldBufCap))
> 			}
> ```

nit: do we need this to be conditional?
</blockquote></details>

No, refactored.

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-:-MeXFPrHAi1b2IZbMFYU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

___
*[pkg/sql/colflow/colrpc/inbox.go, line 354 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX4W9n10k2cUT7Vipq:-MeXF6a481pgxCASxySe:b-9nakzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/inbox.go#L354)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Actually `ArrowToBatch` nils out fields in `i.scratch.data`, so I believe that all references to the memory are truly lost and at this point we only have the reference to data inside of `i.scratch.b` which is accounted for. Updated the comment.
</blockquote></details>

Ah, great! Never mind, thank you!
___
*[pkg/sql/colflow/colrpc/outbox.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-MeX7Bvw3FFcqLMUVYrU:-MeXFGvJ8oAIPJg75dBh:b-a89jqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f012bc89a1782c0f097b6418f3c80be2fd64bf2/pkg/sql/colflow/colrpc/outbox.go#L118)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I think it might be confusing because `BoundAccount` has `Close` method and `Allocator.Close` currently shouldn't call it because the account is closed on the flow cleanup. I guess my expectation is if we were to introduce `Allocator.Close`, then it must call `Allocator.acc.Close` too which would require changes to other places.
</blockquote></details>

Ok, that's fine.

**Review by yuzefovich — COMMENTED** [review]
Added a minor adjustment to the outbox closure.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577#-:-MeXIYTUE3Z97hnNjyks:b-k646nt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach)

**Review by cucaroach — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67577)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
blathers backport 21.1

**Comment by yuzefovich** [comment]
blathers backport 21.1

**Pull request merged**
