### PR TITLE
increase timeout for range split test

### PR DESCRIPTION
**Pull request by dt**
See #3714

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3741)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by bdarnell** [comment]
While you're in there can you make a `const splitTimeout = 10 * time.Second` (or 5s; that's what most of the existing tests use) at the top of the file and use it for all `{Succeeds,IsTrue}Within` calls in this file? There's no reason for these to differ.

**Comment by dt** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3741#-:-K7m6X3UaXWvgRLbEqlh:-499146009)*

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3741)*

**Pull request merged**
