### PR TITLE
build: Move issue-posting script from TC config to repo

### PR DESCRIPTION
**Pull request by bdarnell**
This is cleaned up from the previous version and modified to work
for any project, not just merge-to-master.

I got a little carried away from cleaning up all the python one-liners in the previous script (but not so carried away as to rewrite the whole thing in go)

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm_strong: +2 shipit etc. Thank you! Not that I'm in any position to complain, since this is so much better than the hacked up bash script that it is replacing, but the script could use a brief top-level comment about what it does and what environment variables it requires.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19766#-:-Kxyjl0A-mUI6zgbT9NY:bnjocyo)*

**Comment by benesch** [comment]
It's so readable! ❤️ 

(I'd be in favor of doing more of this stuff in Python. I don't find Go well-suited to this sort of task.)

**Comment by bdarnell** [comment]
Added comments.

To complete the change, I should cherry-pick this into both release branches and then change teamcity to call it instead of the inline shell script (since this step isn't run for open PRs there won't be any other transitional steps), right?

**Comment by jordanlewis** [comment]
Yes, that should do it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19766#-:-Ky1G33ULJ_0QN9c9hY2:bio3xyw)*

**Pull request merged**
