### PR TITLE
sql: Move RBAC into the BSL license.

### LINKED ISSUE #45980: Move RBAC into the BSL
After discussing the issue with eng, docs, and sales, let's [RBAC](https://www.cockroachlabs.com/docs/stable/roles.html), in its entirety, into the BSL for 20.1. However, all functionality designed to integrate CockroachDB with SSO systems like Active Directory (via GSSAPI or LDAP) will be enterprise. 

The main driver for our push to make RBAC BSL was Postgres compatibility, which will make CockroachDB work with more tooling and patterns that developers have come to expect. 

cc @jordanlewis @knz @Amruta-Ranade @piyush-singh

### PR DESCRIPTION
**Pull request by RichardJCai**
Fixes #45980

Release note (sql change): All RBAC features (CREATE ROLE, ALTER ROLE, DROP ROLE, GRANT ROLE, REVOKE ROLE)
are available to non-enterprise users. All RBAC features are now BSL features.

Release note (sql change): The statement tag returned to the client upon success for CREATE USER, ALTER USER, DROP USER
now include the word "ROLE" instead of "USER", for compatibility with PostgreSQL.
These three statements are now aliases for CREATE ROLE, ALTER ROLE, DROP ROLE.

Release justification: Low risk change, moving code out of CCL and into BSL. Done for full postgres compatility.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with nits.

Also add this release note next to the one you already had.

```
Release note (sql change): The statement tag returned to the client upon success for CREATE USER and DROP USER 
now include the word "ROLE" instead of "USER", for compatibility with PostgreSQL.
These two statements are now aliases for CREATE/DROP ROLE. 
```

> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-:-M2Z61zB9ye3uubxbjso:b-8del7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/cmd/docgen/diagrams.go, line 669 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-M2Z5SiPAAbgG2TTGiAb:-M2Z5SiPAAbgG2TTGiAc:b-f0ayj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/321b1f38d73f67d51554d658dc87f5e7b6839496/pkg/cmd/docgen/diagrams.go#L669)):*
> ```Go
> 	},
> 	{
> 		name:    "drop_role_stmt",
> ```

Here and in the CREATE ROLE diagram declaration: `inline: []string{"role_or_group_or_user"}`
___
*[pkg/sql/grant_role.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-M2Z5dSQD8e6ecnHPkiO:-M2Z5dSQD8e6ecnHPkiP:bc6kiz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/321b1f38d73f67d51554d658dc87f5e7b6839496/pkg/sql/grant_role.go#L47)):*
> ```Go
> 	sqltelemetry.IncIAMGrantCounter(n.AdminOption)
> 
> 	// TODO(dan): Move this span into sql.
> ```

remove the todo
___
*[pkg/sql/revoke_role.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-M2Z5uL28-_xL6HTyFWI:-M2Z5uL28-_xL6HTyFWJ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/321b1f38d73f67d51554d658dc87f5e7b6839496/pkg/sql/revoke_role.go#L47)):*
> ```Go
> 	sqltelemetry.IncIAMRevokeCounter(n.AdminOption)
> 
> 	// TODO(dan): Move this span into sql.
> ```

ditto
___
*[pkg/sql/walk.go, line 895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-M2Z5yunBEsYOV9xNFo0:-M2Z5yunBEsYOV9xNFo1:bs7mk9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/321b1f38d73f67d51554d658dc87f5e7b6839496/pkg/sql/walk.go#L895)):*
> ```Go
> 	reflect.TypeOf(&renameTableNode{}):       "rename table",
> 	reflect.TypeOf(&renderNode{}):            "render",
> 	reflect.TypeOf(&RevokeRoleNode{}):        "revoke roles",
> ```

just curious: where does the plural come from?
___
*[pkg/sql/parser/sql.y, line 5154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46042#-M2Z47yn-XtUOeEN5goz:-M2Z47yo5nkJrpTFLeCo:b6x5q3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/321b1f38d73f67d51554d658dc87f5e7b6839496/pkg/sql/parser/sql.y#L5154)):*
> ```Yacc
> | USER
>   {
>   $$.val = false
> ```

nit: indentation

**Comment by knz** [comment]
cc @Amruta-Ranade you'll need to process this with your other changes.

**Comment by knz** [comment]
@RichardJCai you also need to remove the `roleccl` package imports in various places, as indicated by the linter.

**Comment by RichardJCai** [comment]
bors r=knz

**Pull request merged**
