### PR TITLE
dev: symlink binaries built by dev into the workspace

### PR DESCRIPTION
**Pull request by rickystewart**
For convenience, parse the location of the built binaries and symlink them into
the workspace.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
(this is my first go code, sorry 😬)

**Review by irfansharif — COMMENTED** [review]
Ha, nothing to apologize for! Left some minor suggestions below, they'll help retain some type safety during parsing.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-:-MS_F06r27PPWAG8gtfV:bvh4hus)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/dev/build.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Ek5QCzNYIP90hGZQ:-MS_Ek5QCzNYIP90hGZR:b9pswxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L82)):*
> ```Go
> 		return err
> 	}
> ```

[nit] Mild preference for packaging everything below into a helper method, `symlinkBinaries` or something.
___
*[pkg/cmd/dev/build.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CYWO5gfwqsMEkOjO:-MS_CYWO5gfwqsMEkOjP:b-y3kwev) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L83)):*
> ```Go
> 	}
> 
> 	workspaceBuf, err := executeReturningStdout(ctx, "bazel", "info", "workspace")
> ```

The stdlib actually has a handy helper that lets us do just this, so we can skip defining `executeReturningStdout`
```go
var workspace string
{
  out, err := exec.Command("bazel", "info", "workspace").Output()
  if err != nil {
    return err
  }
  workspace = strings.TrimSpace(string(out))
}
```
___
*[pkg/cmd/dev/build.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_ByrtCguLHS5xr4Qq:-MS_ByrtCguLHS5xr4Qr:bu7xqmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L89)):*
> ```Go
> 	workspace := strings.TrimSpace(workspaceBuf.String())
> 
> 	var binDirCreated bool
> ```

We don't actually need to check if `bin` existed previously, `os.MkdirAll` is a no-op if the path already exists. Let's unconditionally create it here, before the symlink loop below.
___
*[pkg/cmd/dev/build.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Cu8vB_12jDe-VGGy:-MS_Cu8vB_12jDe-VGGz:b-2zvihp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L92)):*
> ```Go
> 	for _, target := range targets {
> 		buildTarget := buildTargetMapping[target]
> 		output, err := getPathToGoBin(ctx, buildTarget)
> ```

[nit] Let's use a better name here, `binaryPath` perhaps? Could also use `symlinkPath` for `dest` below.
___
*[pkg/cmd/dev/build.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CGWW0b8bhVzLW4N4:-MS_CGWW0b8bhVzLW4N5:b-ro0kvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L97)):*
> ```Go
> 		}
> 		
> 		base := path.Base(output)
> ```

Instead of parsing out `base`, we can simply use `target` from up above.
___
*[pkg/cmd/dev/util.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_DiEI2n10X18LGqBn:-MS_DiEI2n10X18LGqBo:buqlzsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L81)):*
> ```Go
> }
> 
> func executeReturningStdout(ctx context.Context, name string, args ...string) (*bytes.Buffer, error) {
> ```

See comment above; this can go away.
___
*[pkg/cmd/dev/util.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MSZzifq7D2q4UWo0ZR-:-MSZzifq7D2q4UWo0ZR0:b-k1suzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L101)):*
> ```Go
> }
> 
> func getPathToGoBin(ctx context.Context, target string) (string, error) {
> ```

Heh, I actually only learnt this trick [this week](https://github.com/irfansharif/utils/commit/20945841e669e4d5f6807c4529afe2e07cb51f05), but Go lets us make use of type safety when unmarshalling JSON.

```go
func getBinaryPathFor(target string) (string, error) {
	// actionQueryResult is used to unmarshal the results of the bazel action
	// query.
	type actionQueryResult struct {
		Artifacts []struct {
			ID       string `json:"id"`
			ExecPath string `json:"execPath"`
		} `json:"artifacts"`

		Actions []struct {
			Mnemonic  string   `json:"mnemonic"`
			OutputIds []string `json:"outputIds"`
		} `json:"actions"`
	}

	buf, err := exec.Command("bazel", "aquery", target, "--output=jsonproto").Output()
	if err != nil {
		return "", err
	}

	var result actionQueryResult
	if err := json.Unmarshal(buf, &result); err != nil {
		return "", err
	}

	const binaryMnemomic = "GoLink"
	for _, action := range result.Actions {
		if action.Mnemonic == binaryMnemomic {
			id := action.OutputIds[0]
			for _, artifact := range result.Artifacts {
				if artifact.ID == id {
					return artifact.ExecPath, nil
				}
			}
		}
	}

	return "", fmt.Errorf("could not find path to binary %q", target)
}
```
___
*[pkg/cmd/dev/util.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Dvz1-OnHh_DNyYmz:-MS_Dvz1-OnHh_DNyYn-:b-uttijc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L104)):*
> ```Go
> 	// We could pass --output=proto instead, but then we'd have to import
> 	// the generated Go code for the proto definition. For now, until we're
> 	// comfortable depending on that, just parse the JSON instead.
> ```

Using JSON is probably the preferable way any, it's versioned and parsing is made easy with the unmarshalling trick above.

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/cmd/dev/build.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Ek5QCzNYIP90hGZQ:-MScp8j15k8y5jOoPJV0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L82)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Mild preference for packaging everything below into a helper method, `symlinkBinaries` or something.
</blockquote></details>

Done.
___
*[pkg/cmd/dev/build.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CYWO5gfwqsMEkOjO:-MScpA-32Ey81uhVlYwv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L83)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

The stdlib actually has a handy helper that lets us do just this, so we can skip defining `executeReturningStdout`
```go
var workspace string
{
  out, err := exec.Command("bazel", "info", "workspace").Output()
  if err != nil {
    return err
  }
  workspace = strings.TrimSpace(string(out))
}
```
</blockquote></details>

Done.
___
*[pkg/cmd/dev/build.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_ByrtCguLHS5xr4Qq:-MScpAfp9j9sb_82_eek:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L89)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We don't actually need to check if `bin` existed previously, `os.MkdirAll` is a no-op if the path already exists. Let's unconditionally create it here, before the symlink loop below.
</blockquote></details>

Done.
___
*[pkg/cmd/dev/build.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Cu8vB_12jDe-VGGy:-MScpB6a-IjcJsDfjohO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L92)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Let's use a better name here, `binaryPath` perhaps? Could also use `symlinkPath` for `dest` below.
</blockquote></details>

Done.
___
*[pkg/cmd/dev/build.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CGWW0b8bhVzLW4N4:-MScpBUnCZ6b2sFeLcyg:b-7na94w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L97)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Instead of parsing out `base`, we can simply use `target` from up above.
</blockquote></details>

Wasn't really sure about this suggestion. I'd have to split `target` on `/`and get the last element of the array, but that seems less obvious than just doing this.
___
*[pkg/cmd/dev/util.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_DiEI2n10X18LGqBn:-MScpyO3EK1GnJeUYSfx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L81)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

See comment above; this can go away.
</blockquote></details>

Done.
___
*[pkg/cmd/dev/util.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MSZzifq7D2q4UWo0ZR-:-MScpvnb5Uow3ZCXrGbb:bojmz2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L101)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Heh, I actually only learnt this trick [this week](https://github.com/irfansharif/utils/commit/20945841e669e4d5f6807c4529afe2e07cb51f05), but Go lets us make use of type safety when unmarshalling JSON.

```go
func getBinaryPathFor(target string) (string, error) {
	// actionQueryResult is used to unmarshal the results of the bazel action
	// query.
	type actionQueryResult struct {
		Artifacts []struct {
			ID       string `json:"id"`
			ExecPath string `json:"execPath"`
		} `json:"artifacts"`

		Actions []struct {
			Mnemonic  string   `json:"mnemonic"`
			OutputIds []string `json:"outputIds"`
		} `json:"actions"`
	}

	buf, err := exec.Command("bazel", "aquery", target, "--output=jsonproto").Output()
	if err != nil {
		return "", err
	}

	var result actionQueryResult
	if err := json.Unmarshal(buf, &result); err != nil {
		return "", err
	}

	const binaryMnemomic = "GoLink"
	for _, action := range result.Actions {
		if action.Mnemonic == binaryMnemomic {
			id := action.OutputIds[0]
			for _, artifact := range result.Artifacts {
				if artifact.ID == id {
					return artifact.ExecPath, nil
				}
			}
		}
	}

	return "", fmt.Errorf("could not find path to binary %q", target)
}
```

</blockquote></details>

Hey, this is great, thanks. (Pretty unfortunate this isn't front and center on the `json` documentation for Golang, but what do I know.)

Done.
___
*[pkg/cmd/dev/util.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_Dvz1-OnHh_DNyYmz:-MScpw8S57Hoot4FMJo0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L104)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Using JSON is probably the preferable way any, it's versioned and parsing is made easy with the unmarshalling trick above.
</blockquote></details>

Done.

**Review by irfansharif — APPROVED** [review]
:lgtm: thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-:-MScwMLN0VSCKOkF7QEZ:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/dev/build.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CGWW0b8bhVzLW4N4:-MScufMA57aoUOgfb1rs:b-mtqcte) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L97)):*
<details><summary><i>Previously, rickystewart wrote…</i></summary><blockquote>

Wasn't really sure about this suggestion. I'd have to split `target` on `/`and get the last element of the array, but that seems less obvious than just doing this.
</blockquote></details>

We wouldn't? I wasn't talking about `buildTarget`, I was talking about `target`, which is what the user specifies by hand (so `cockroach-short`, or `crlfmt`, etc.) We could simply use `path.Join(workspace, target)` below.
___
*[pkg/cmd/dev/util.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MSZzifq7D2q4UWo0ZR-:-MScvXiD93CiOsHXXNGs:b-hpdnnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/util.go#L101)):*
<details><summary><i>Previously, rickystewart wrote…</i></summary><blockquote>

Hey, this is great, thanks. (Pretty unfortunate this isn't front and center on the `json` documentation for Golang, but what do I know.)

Done.
</blockquote></details>

Agreed, I had to cobble it together from random source code like it was the 90s. It's weird and subtle too; the fields have to be public members (which is kind of ugly, but probably a good reason for it which I couldn't find).
___
*[pkg/cmd/dev/util.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MScvDpRDr3Pxdc8Q6Ea:-MScvDpRDr3Pxdc8Q6Eb:b-80bumq) ([raw file](https://github.com/cockroachdb/cockroach/blob/748f3cad81dd0d48c2e4d302d06c92bef4c2392b/pkg/cmd/dev/util.go#L79)):*
> ```Go
> }
> 
> func getPathToGoBin(ctx context.Context, target string) (string, error) {
> ```

Isn't `ctx` unused? Also, [nit] all binaries we'd generate here are go binaries, so I think dropping "Go" would make sense.

**Review by rickystewart — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59725)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif)

___
*[pkg/cmd/dev/build.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MS_CGWW0b8bhVzLW4N4:-MSd2KEo2p7_hVzmt8_l:bah9pin) ([raw file](https://github.com/cockroachdb/cockroach/blob/c12fd8f9d80551443e6b1d43dbdfa89067e039ac/pkg/cmd/dev/build.go#L97)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

We wouldn't? I wasn't talking about `buildTarget`, I was talking about `target`, which is what the user specifies by hand (so `cockroach-short`, or `crlfmt`, etc.) We could simply use `path.Join(workspace, target)` below.
</blockquote></details>

Ah, no, you're right :) Done.
___
*[pkg/cmd/dev/util.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59725#-MScvDpRDr3Pxdc8Q6Ea:-MSd2TsQD1UUBQ9nVio-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/748f3cad81dd0d48c2e4d302d06c92bef4c2392b/pkg/cmd/dev/util.go#L79)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Isn't `ctx` unused? Also, [nit] all binaries we'd generate here are go binaries, so I think dropping "Go" would make sense.
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
Not for this PR, but like mentioned elsewhere, we could pull out this into its own repo. I think that'll also tell us that we'll start needing to add (simple) go tests as we continue working here.

**Pull request merged**
