### PR TITLE
testlogic: temporarily switch auto stats default to off to deflake TestLogic

### PR DESCRIPTION
**Pull request by danhhz**
Background stats collection is enabled by default, but we've seen tests
flake with it on. When the issue manifests, it seems to be around a
schema change transaction getting pushed, which causes it to increment a
table ID twice instead of once, causing non-determinism.

In the short term, in TestLogic, we disable auto stats by default to
avoid the flakes.

In the long run, these tests should be running with default settings as
much as possible, so we likely want to address this. Two options are
either making schema changes more resilient to being pushed or possibly
making auto stats avoid pushing schema change transactions. There might
be other better alternatives than these.

Touches #37751

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Some of the `logicTestConfigs` already override `overrideAutoStats` to false, why not add it to the others too instead? I don't quite see the reasoning for disabling it in some configs but not others.

**Comment by danhhz** [comment]
I don't know why it's disabled in those either but manually adding it to each one for something we plan to revert when the underlying issue is fixed doesn't seem right to me. The intent of this PR is to alter the default for TestLogic in the absence of an override and that's exactly what I'm doing.

**Review by nvb — APPROVED** [review]

**Comment by RaduBerinde** [comment]
Ok either way. My thinking was that the "optimizer off" configs will go away soon hopefully (and the optimizer configs already have `overrideAutoStats=false`).

**Comment by danhhz** [comment]
Oh I see. Yeah that makes sense too. I’m still inclined to merge this as-is because it’s more obvious that it’s a temporary thing to stop the flakes from affecting bors while we figure out what should be done long term. TFTRs!

bors r+

**Pull request merged**
