### PR TITLE
irgen: improve the Makefile, add an S-expression printer

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by benesch** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/ir/Makefile, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17169#-Kpauu0FGbHEuSvRdE0N:-Kpauu0FGbHEuSvRdE0O:b-sxw14d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62bd62495f59ca6970adb4c497968f52ed9adc/pkg/sql/ir/Makefile#L27)):*
> ```Makefile
> # Those three items are then taken together to construct
> # a valid command line with $^
> %.ir.go: irgen/irgen $$(subst .ir,,$$(subst $$(firstword $$(subst /, ,$$@))/,,$$@)) $$(firstword $$(subst /, ,$$@)).def
> ```

I feel like this would be way more understandable with two functions extracted:

```
# example/base/base.ir.go -> example
first_dir = $(subst $(firstword $(subst /, ,$1)))

# example/base/base.ir.go -> base/base.go
template_path = $(subst .ir,,$(subst $(call first_dir,$1)/,,$1))
```

And I think that would still work with secondary expansion?

```
%.ir.go: irgen/irgen $$(call template_path,$$@)) $$(call first_dir,$$@).def
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17169)*

**Comment by knz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/ir/Makefile, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17169#-Kpauu0FGbHEuSvRdE0N:-KpbbDJY9Si7Xx4VgirE:bcujtxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b62bd62495f59ca6970adb4c497968f52ed9adc/pkg/sql/ir/Makefile#L27)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I feel like this would be way more understandable with two functions extracted:

```
# example/base/base.ir.go -> example
first_dir = $(subst $(firstword $(subst /, ,$1)))

# example/base/base.ir.go -> base/base.go
template_path = $(subst .ir,,$(subst $(call first_dir,$1)/,,$1))
```

And I think that would still work with secondary expansion?

```
%.ir.go: irgen/irgen $$(call template_path,$$@)) $$(call first_dir,$$@).def
```
</blockquote></details>

Good suggestion! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17169)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17169#-:-KppPtgofvHGD5XjFFyk:bnfp4nl)*

**Comment by tamird** [comment]
Does it make sense for @cockroachdb/build to own this stuff? I've never reviewed any of this.

**Comment by knz** [comment]
The owners are @cockroachdb/sql-language. I'm not sure why CODEOWNERS didn't do it.

The reason why @cockroachdb/build is pinged here is that I made a change to `style_test.go`. You can have a look at that!

**Comment by knz** [comment]
Also this particular PR has been reviewed already!

**Review by tamird — APPROVED** [review]
style_test.go lgtm.



screen shot 2017-08-02 at 13 32 52

**Comment by knz** [comment]
This notification says "I" did it but really GH did it automatically as a side-effect of me committing on top of a repo with a CODEOWNER file. The fact my name is attached to it is ... just because I authored the commit.

**Comment by tamird** [comment]
I see.

**Pull request merged**
