### PR TITLE
debug: productionize pprof labels, add to debug zip 

### PR DESCRIPTION
**Pull request by tbg**
We take CPU profiles in various places. Add a number of helpers that
allow them all to use the richer functionality (labels toggle) which
we've had for a while but which has been close to forgotten.
This commit brushes up this functionality, defaults it to `on` and,
as a first application, exposes a profile with labels on the status
server for inclusion (per node) in debug zip.

The immediate win here is that if a customer pulls a debug zip off a
cluster that is seeing high CPU utilization, we will be able to look at
labels in which parts of the CPU usage are attributed to SQL client
connections, statement types, users, and app names. I expect this to be
a big win as this kind of investigation has proven to be quite time
consuming and difficult in the recent past.

There is more work to be done here, such as also labelling across RPC
boundaries, but it's a good start.

Note: I'm not able to make good use of the labels in the pprofui - they
are shown (in the dot graph, which is often unavailable on real
deployments anyway) but it's unclear whether they let you derive much.
The most useful anticipated use is just `tags`. For example, here's what
that outputs on a single node running the default `kv` workload:

```
$ ./debug/pprof-summary.sh
 addr: Total 750.0ms
       120.0ms (16.00%): 127.0.0.1:57906
        70.0ms ( 9.33%): 127.0.0.1:57899
        70.0ms ( 9.33%): 127.0.0.1:57904
        50.0ms ( 6.67%): 127.0.0.1:57867
        50.0ms ( 6.67%): 127.0.0.1:57898
        50.0ms ( 6.67%): 127.0.0.1:57902
        50.0ms ( 6.67%): 127.0.0.1:57913
        50.0ms ( 6.67%): 127.0.0.1:57914
        40.0ms ( 5.33%): 127.0.0.1:57901
        40.0ms ( 5.33%): 127.0.0.1:57903
        40.0ms ( 5.33%): 127.0.0.1:57907
        30.0ms ( 4.00%): 127.0.0.1:57910
        30.0ms ( 4.00%): 127.0.0.1:57911
        30.0ms ( 4.00%): 127.0.0.1:57915
        20.0ms ( 2.67%): 127.0.0.1:57905
        10.0ms ( 1.33%): 127.0.0.1:57912

 appname: Total 750.0ms
          750.0ms (  100%): kv

 pebble: Total 10.0ms
         10.0ms (  100%): wal-sync

 stmt.anonymized: Total 750.0ms
                  750.0ms (  100%): UPSERT INTO kv(k, v) VALUES ($1, $2)

 stmt.tag: Total 750.0ms
           750.0ms (  100%): INSERT
```

Release note (general change): CPU profiles are now taken as part of
the `debug zip` command.
Release note (general change): CPU profiles taken from CockroachDB
servers now contain more profiler labels related to ongoing SQL
processing.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:
I think you should talk at some eng team meeting to show us the goods too.

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-:-MAf3fG57dQ3zRIEjuKC:bxp5zva)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @tbg)

___
*[pkg/server/debug/server.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-MAf3Qxn7zQauCpAeRY7:-MAf3Qxn7zQauCpAeRY8:b-in3wr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8564bba0754366136b06fcd4c901a6a95edb9c3f/pkg/server/debug/server.go#L161)):*
> ```Go
> 			// this problematic. In practice, `do()` wraps the pprof handler which will
> 			// return an error if there's already a profile going on just the same.
> 			log.Infof(context.Background(), "unable to start CPU profile: %s", err)
> ```

Warningf instead of Infof maybe?

**Comment by tbg** [comment]
@knz mind giving this another look? I parallelized fetching the profiles from all live nodes at the beginning of taking the zip. This makes sure they all cover the same time slice (more or less). I also added a `-cpu-profile-duration` flag.

**Review by knz — COMMENTED** [review]
> Reviewed 19 of 19 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @tbg)

___
*[pkg/cli/zip.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-MCBbqJ65yTTxlXj5ROp:-MCBbqJ65yTTxlXj5ROq:b-td7c57) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab0241c54fb66ca8ee42a7327aa9091340a5d83/pkg/cli/zip.go#L403)):*
> ```Go
> 					defer wg.Done()
> 
> 					if zipCtx.cpuProfDuration == 0 {
> ```

Could you pull this up to avoid the loop and waitgroup altogether?
___
*[pkg/server/debug/server.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-MAf3Qxn7zQauCpAeRY7:-MCBc5HL80JO_Bj9YM3b:bb7dx2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8564bba0754366136b06fcd4c901a6a95edb9c3f/pkg/server/debug/server.go#L161)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Warningf instead of Infof maybe?
</blockquote></details>

bump

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @knz)

___
*[pkg/cli/zip.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-MCBbqJ65yTTxlXj5ROp:-MCBnTbM4T1m_4YoEXR-:b-8sl4f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab0241c54fb66ca8ee42a7327aa9091340a5d83/pkg/cli/zip.go#L403)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Could you pull this up to avoid the loop and waitgroup altogether?
</blockquote></details>

Done. It was a silly idea to have this here in the first place, I somehow thought this would be better for testing the concurrency deeply, but.. no.
___
*[pkg/server/debug/server.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50625#-MAf3Qxn7zQauCpAeRY7:-MCBkNI12stm-VQiF-_6:b-n1hrfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8564bba0754366136b06fcd4c901a6a95edb9c3f/pkg/server/debug/server.go#L161)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

bump
</blockquote></details>

Didn't feel strongly, but done.

**Review by knz — APPROVED** [review]
> Reviewed 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50625)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @knz)

**Comment by tbg** [comment]
bors r=knz

**Pull request merged**
