### PR TITLE
*: replace "testdata" with sed scripts

### PR DESCRIPTION
**Pull request by otan**
Not a proper audit, but 80% of the way there.
Refs: #71928

See individual commits for details

### CODE REVIEW

**Comment by rickystewart** [comment]
Looks like you've got just a few more failing tests.

**Comment by otan** [comment]
all good now

**Review by rickystewart — APPROVED** [review]
Assuming that the tests all pass, stamp. :) 

Thanks for looking at this Oliver.

**Comment by otan** [comment]
remaining failure looks like an unrelated timeout

bors r=rickystewart

**Comment by otan** [comment]
bors r=rickystewart

**Pull request merged**
