### PR TITLE
util/tracing: simplify log messages in trace recordings

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, the RecordedSpan proto stored log messages in a very
awkward way: each message was stored as a collection of key/values, with
only one such pair present (using a well-known key). This was confusing,
unnecessary, hard to work with and hard to track for figuring out what
keys and values are in there (with the answer being only one key). This
patch simplifies the log messages, making them be represented by a
single string as nature intended. A bunch of code gets simplified in
consequence.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Please don't merge until https://github.com/cockroachdb/cockroach/pull/70562
is either discarded or merged, thanks! That PR will need backported if it
does get merged to master, and there will be time pressure.

**Review by abarganier — APPROVED** [review]
Nice work! Overall :lgtm:, just a couple minor nits and questions. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-MkJEEFc6I7JGkH2NK3R:bs9xsh5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @andreimatei)

___
*[pkg/util/tracing/recording.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkItvi79W5g4ePcXIWL:-MkItvi79W5g4ePcXIWM:bxhaaer) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5ae04c165a0141de7090223ab99215b5cdbdcd0/pkg/util/tracing/recording.go#L93)):*
> ```
> ""
> ```
is empty string needed here? 
___
*[pkg/util/tracing/recording.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkJ-NItApkLZVLzXtkw:-MkJ-NItApkLZVLzXtkx:b-sayu29) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5ae04c165a0141de7090223ab99215b5cdbdcd0/pkg/util/tracing/recording.go#L203)):*
> ```Go
> 	for _, k := range tags {
> 		if !first {
> 			sb.WriteRune(' ')
> ```

nit: do we need this if we already wrote whitespace above on line 190? 

```
	if len(sp.Tags) > 0 {
		sb.WriteRune(' ')
	}
```

If so, instead of tracking `first` here, can we just write the whitespace prior to the loop `if len(tags) > 0`? Could further simplify the loop.
___
*[pkg/util/tracing/recording.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkJD9ML00qqt1T1EOUs:-MkJD9MMADaV7XA94ouy:b-u7ktmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8560bf81bea8828bc6a784217f0094cb794bca18/pkg/util/tracing/recording.go#L363)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 				Fields: []jaegerjson.KeyValue{{
> 					Value: l.Msg(),
> 
> 					Type:  "STRING",
> 				}},
> ```
</details>

I'm not experienced with Jaeger, so wanted to confirm - is it okay to omit a key here? Will it still display nicely in a jaeger UI without a key?

**Review by andreimatei — COMMENTED** [review]
> Please don't merge until #70562 is either discarded or merged, thanks! That PR will need backported if it does get merged to master, and there will be time pressure.

Well, is #70562 discarded? I don't think this patch would get in your way.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-MkKiq6E0WFcPuFNM8U_:b-yqxphp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier)

___
*[pkg/util/tracing/recording.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkItvi79W5g4ePcXIWL:-MkKdmJU7afw6elvAX8K:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5ae04c165a0141de7090223ab99215b5cdbdcd0/pkg/util/tracing/recording.go#L93)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> ""
> ```
is empty string needed here? 
</blockquote></details>

removed
___
*[pkg/util/tracing/recording.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkJ-NItApkLZVLzXtkw:-MkKeUjW3H4VF5oC5mmA:b-2phgpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5ae04c165a0141de7090223ab99215b5cdbdcd0/pkg/util/tracing/recording.go#L203)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: do we need this if we already wrote whitespace above on line 190? 

```
	if len(sp.Tags) > 0 {
		sb.WriteRune(' ')
	}
```

If so, instead of tracking `first` here, can we just write the whitespace prior to the loop `if len(tags) > 0`? Could further simplify the loop.
</blockquote></details>

This was writing the spaces before every tag *except* the first. But you're right that this code was needlessly complicated. Simplified.
___
*[pkg/util/tracing/recording.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-MkJD9ML00qqt1T1EOUs:-MkKi9ap95XGEU5lHnKI:bpflq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8560bf81bea8828bc6a784217f0094cb794bca18/pkg/util/tracing/recording.go#L363)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 				Fields: []jaegerjson.KeyValue{{
> 					Value: l.Msg(),
> 
> 					Type:  "STRING",
> 				}},
> ```
I'm not experienced with Jaeger, so wanted to confirm - is it okay to omit a key here? Will it still display nicely in a jaeger UI without a key?
</blockquote></details>

It rendered fine. But on second thought, you're right; the log messages do show up with an "event" key when the spans are created and collected by Jaeger through OpenTelemetry. So I've given them the same key on this code path (this is the code path used by `explain analyze (debug)` and friends), for consistency.

**Review by abarganier — APPROVED** [review]
Not sure about #70562, but everything else :lgtm:! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-MkNOHWq53M3teBGUzv3:b7l5it5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by knz — COMMENTED** [review]
> Reviewed 21 of 21 files at r7, 12 of 12 files at r8, 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @andreimatei)

___
*[pkg/server/node_tenant.go, line 33 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9xF23NPTNi1qgHbf:-Mkh9xF23NPTNi1qgHbg:b-e9aj9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/545ed0a950883909b52558aa71a34466573a2893/pkg/server/node_tenant.go#L33)):*
> ```Go
> 		for j := range sp.Logs {
> 			record := &sp.Logs[j]
> 			record.Message = record.Message.Redact()
> ```

what's going on here? 
1. did you intend to edit Message in-place inside the span? Don't you want to take a copy?
2. why does this commit need to add a Redact call? I thought Tobias' PR was already taking care of doing the right thing? Did we forget this call in the previous PR? (If so, we'll need to create a separate PR with just this fix and issue an emergency backport)
___
*[pkg/util/tracing/recording.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8Wox0XQaxH6cIZTo:-Mkh8Woy8SuwUxPwVLno:b-sv90kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L81)):*
> ```Go
> // TODO(andrei): this should be unified with
> // SessionTracing.generateSessionTraceVTable().
> func (r Recording) String() string {
> ```

You could have Recording implement `SafeFormatter`
and propagate the markers in the individual log entries.
___
*[pkg/util/tracing/recording.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8iJ002xZ8apufp5L:-Mkh8iJ002xZ8apufp5M:bs62zph) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L139)):*
> ```Go
> }
> 
> // FindLogMessage returns the first log message in the recording that matches
> ```

Can you explain this function is used only in testing
(maybe even rename it to `TestingFindLogMessage`)

and mention that it's relatively slow and heavy on allocations.
___
*[pkg/util/tracing/recording.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9-VlEur0kqq_LUJB:-Mkh9-VlEur0kqq_LUJC:b5zjrj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L212)):*
> ```Go
> 	for _, l := range sp.Logs {
> 		lastLog := ownLogs[len(ownLogs)-1]
> 		ownLogs = append(ownLogs, conv("event:"+l.Msg(), l.Time, lastLog.Timestamp))
> ```

ugh, is there a way to prepend that `"event:"` sometime later, e.g. when `logRecord` instances are formatted?
___
*[pkg/util/tracing/recording.go, line 226 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh99-s6zU9N2GYNXga:-Mkh99-s6zU9N2GYNXgb:b-k0cbrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L226)):*
> ```Go
> 			lastLog := ownLogs[len(ownLogs)-1]
> 			var sb redact.StringBuilder
> 			sb.SafeString("structured:")
> ```

that looks like a regression. Prior to your change, in Tobias's PR we were assuming that structured payloads were safe. Now you're making this code consider the entire JSON thing as unsafe. Was that intnetional?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @knz, and @tbg)

___
*[pkg/server/node_tenant.go, line 33 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9xF23NPTNi1qgHbf:-MkhEUtaEwDt3_EBF3kw:b-x9hhhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/545ed0a950883909b52558aa71a34466573a2893/pkg/server/node_tenant.go#L33)):*
> did you intend to edit Message in-place inside the span? Don't you want to take a copy?

I did. I'm doing what the function was already doing - modifying the recording (this function doesn't return anything). I've added a comment to the function.

> why does this commit need to add a Redact call?

The `record.Message` field is new; that's what this commit does. It's a replacement for the old `Fields` collection.
___
*[pkg/util/tracing/recording.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8Wox0XQaxH6cIZTo:-MkhGfjrCBWyWGjXAKRz:ba1xutd) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You could have Recording implement `SafeFormatter`
and propagate the markers in the individual log entries.

</blockquote></details>

ack. I'll leave for next time though.
___
*[pkg/util/tracing/recording.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8iJ002xZ8apufp5L:-MkhHPaEAhGJYv71bPOo:bejcfmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L139)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain this function is used only in testing
(maybe even rename it to `TestingFindLogMessage`)

and mention that it's relatively slow and heavy on allocations.
</blockquote></details>

Well the function is not particularly test specific... It's fairly natural for only tests to be interested in doing any sort of comprehension (or rather, sloppy reg-ex based comprehension) of trace recordings, but as far as the function itself is concerned, I don't see any big reason to keep it away from production code.
As to the performance of the thing, well, it is what it is. I don't really thinks it warrants a comment...

FWIW, this patch isn't really doing much to this function. To the extent that it does anything, it just makes the fact that there's a `StripMarkers` in there more visible by lifting it out of the `LogRecord.Msg()` method.
___
*[pkg/util/tracing/recording.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9-VlEur0kqq_LUJB:-Mkhob6o6mRudkqFdJ9G:b-3n3qwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L212)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ugh, is there a way to prepend that `"event:"` sometime later, e.g. when `logRecord` instances are formatted?
</blockquote></details>

Not without making things more complicated. All of the span start message, the log message, and the structured messages are represented as the same `logRecord` type, which doesn't encode the difference between them. It's not worth doing too much for this function, it's only used by `Recording.String()`.

Perhaps you were taking objection to using `+` between a literal and a `RedactableString`, since it wasn't obvious what will happen to the literal? See now, I've turned it into a `sb.Printf`.
___
*[pkg/util/tracing/recording.go, line 226 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh99-s6zU9N2GYNXga:-MkhsnD34lROhdzaP6QW:beli0nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that looks like a regression. Prior to your change, in Tobias's PR we were assuming that structured payloads were safe. Now you're making this code consider the entire JSON thing as unsafe. Was that intnetional?
</blockquote></details>

Well before my change, safe versus unsafe considerations did not apply to this function. This function is only used by `Recording.String()`, and it returned `opentracing.LogRecord`, which doesn't understand such things. All markers were removed from all messages; structured on unstructured. Now, this function returns redactable messages. It doesn't matter too much, since the only caller, `Recording.String()`, strips all the markers anyway.

As far as the safety of structured messages, I'm not sure it has been determined that they're indeed safe. We can't strip them at the boundary between KV and a tenant, because SQL needs them. I'm not sure they're all safe since, for example, a `ContentionEvent` has a key in it, and I think that key can come from a meta range. I think I raised this on Slack a few days ago and I don't think I heard back. Anyway as far as I can tell, I don't think we "show" these events to users (e.g. I don't think they show up for `show trace for session`). Perhaps @tbg can chime on whether there's been thinking around them.
Anyway, for the purposes of this code here, I think there's no harm in considering them unsafe, and also it doesn't matter because again the caller strips all the markers anyway.

**Review by knz — COMMENTED** [review]
> Reviewed 9 of 12 files at r11, 13 of 14 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @knz)

___
*[pkg/util/tracing/recording.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8iJ002xZ8apufp5L:-Mki-IbuDI4RhhhB0AHB:bczq65l) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L139)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well the function is not particularly test specific... It's fairly natural for only tests to be interested in doing any sort of comprehension (or rather, sloppy reg-ex based comprehension) of trace recordings, but as far as the function itself is concerned, I don't see any big reason to keep it away from production code.
As to the performance of the thing, well, it is what it is. I don't really thinks it warrants a comment...

FWIW, this patch isn't really doing much to this function. To the extent that it does anything, it just makes the fact that there's a `StripMarkers` in there more visible by lifting it out of the `LogRecord.Msg()` method.
</blockquote></details>

The reason why I pinged you on this is that I find it sad to re-call `StripMarker` on this every time the logs are being traversed. That re-processing (and the allocs that go with it) is ok for test code, but not for production code.
___
*[pkg/util/tracing/recording.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9-VlEur0kqq_LUJB:-Mki-SFB2cqcPvfYIdgC:b-n2eevx) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L212)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Not without making things more complicated. All of the span start message, the log message, and the structured messages are represented as the same `logRecord` type, which doesn't encode the difference between them. It's not worth doing too much for this function, it's only used by `Recording.String()`.

Perhaps you were taking objection to using `+` between a literal and a `RedactableString`, since it wasn't obvious what will happen to the literal? See now, I've turned it into a `sb.Printf`.

</blockquote></details>

your previous code was fine. I was just annoyed by the extra heap alloc and string copy implied here.
___
*[pkg/util/tracing/recording.go, line 226 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh99-s6zU9N2GYNXga:-Mki-qjXCTA8t-ZjKTjd:b-bfw151) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L226)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well before my change, safe versus unsafe considerations did not apply to this function. This function is only used by `Recording.String()`, and it returned `opentracing.LogRecord`, which doesn't understand such things. All markers were removed from all messages; structured on unstructured. Now, this function returns redactable messages. It doesn't matter too much, since the only caller, `Recording.String()`, strips all the markers anyway.

As far as the safety of structured messages, I'm not sure it has been determined that they're indeed safe. We can't strip them at the boundary between KV and a tenant, because SQL needs them. I'm not sure they're all safe since, for example, a `ContentionEvent` has a key in it, and I think that key can come from a meta range. I think I raised this on Slack a few days ago and I don't think I heard back. Anyway as far as I can tell, I don't think we "show" these events to users (e.g. I don't think they show up for `show trace for session`). Perhaps @tbg can chime on whether there's been thinking around them.
Anyway, for the purposes of this code here, I think there's no harm in considering them unsafe, and also it doesn't matter because again the caller strips all the markers anyway.
</blockquote></details>

Ok I'm 100% on board with the idea that these structured events are generally unsafe until proven safe. As such, your current implementation is OK.

You can add a TODO here (and in the docstring of `MessageToJSONString`)  that we should update the json serializer to do the same as the structured events in `eventpb`, where the JSON serializer (`(EventPayload).AppendJSONFields`) does redactability separately per-field using field tags.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier and @knz)

___
*[pkg/util/tracing/recording.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh8iJ002xZ8apufp5L:-Mki3MCq0sPY-NuFzJgV:b-71z4qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L139)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The reason why I pinged you on this is that I find it sad to re-call `StripMarker` on this every time the logs are being traversed. That re-processing (and the allocs that go with it) is ok for test code, but not for production code.
</blockquote></details>

ok, added an efficiency note
___
*[pkg/util/tracing/recording.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9-VlEur0kqq_LUJB:-Mki3Pnw-2o_bpW3s7sx:bm9mxgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L212)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

your previous code was fine. I was just annoyed by the extra heap alloc and string copy implied here.
</blockquote></details>

well, once I looked at it, I didn't like the old code because to me it wasn't clear at all if the `"event"` part was going to be considered safe or not. I think it was going to be considered safe, but I think that's more a bug/limitation of the type system rather than a good thing, no? What I have now is more explicit and better, isn't it?
___
*[pkg/util/tracing/recording.go, line 226 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh99-s6zU9N2GYNXga:-Mki4D143fX1t5U6ThWW:b8vlcqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L226)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok I'm 100% on board with the idea that these structured events are generally unsafe until proven safe. As such, your current implementation is OK.

You can add a TODO here (and in the docstring of `MessageToJSONString`)  that we should update the json serializer to do the same as the structured events in `eventpb`, where the JSON serializer (`(EventPayload).AppendJSONFields`) does redactability separately per-field using field tags.
</blockquote></details>

Added the TODO to `MessageToJSONString`.

**Review by knz — APPROVED** [review]
> Reviewed 2 of 15 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @knz)

___
*[pkg/util/tracing/recording.go, line 212 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-Mkh9-VlEur0kqq_LUJB:-Mki6UOP2VVFP02sIZFX:bu6sec) ([raw file](https://github.com/cockroachdb/cockroach/blob/441ec3a47529eace208ca1565c5ffb892f947242/pkg/util/tracing/recording.go#L212)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well, once I looked at it, I didn't like the old code because to me it wasn't clear at all if the `"event"` part was going to be considered safe or not. I think it was going to be considered safe, but I think that's more a bug/limitation of the type system rather than a good thing, no? What I have now is more explicit and better, isn't it?
</blockquote></details>

this is good too.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-MkmkOhH4EGDEyUtw5oV:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @knz)

**Review by andreimatei — COMMENTED** [review]
#70896 for the failure

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-MknotdR6Ju1vqVzCAXW:bcgbkuh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @knz)

**Review by andreimatei — COMMENTED** [review]
failure is #70659

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70502#-:-Mkr9ehW9yDsCIUcNsMm:b-iuo44u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @andreimatei, and @knz)

**Pull request merged**
