### PR TITLE
sql/sem/parser: fork targets for grant_targets vs backup_targets

### LINKED ISSUE #84074: sql: GRANT unexpectedly accepts a TENANT target
**Describe the problem**

The following syntax is valid:

```sql
> GRANT SELECT ON TENANT 1 TO abc;
```

This is incorrect.

The problem exists because the grammar rule `targets`, which was defined for GRANT originally, was mistakenly (ab)used for BACKUP (in `opt_backup_targets`), and then also extended to include TENANT.

**Expected behavior**

I am expecting error 42601, "invalid syntax: at or near "tenant": syntax error"

This should be achieved by using a separate target rule for BACKUP.

cc @adityamaru for triage.

Jira issue: CRDB-17447

### PR DESCRIPTION
**Pull request by dt**
At one point, backups could be made on a table, pattern of tables or database, and grants
could be performed on the same set of targets, so it made sense for both to use the same
grammar rule. Today however this is not the case: backups can be made of tenants, which
are invalid grant targets, while grants can be issues on types, which are invalid backup
targets.

This change forks the targets grammar rule they previously shared, providing one copy
for use by grants named grant_targets and one copy for use by backup and restore titled
backup_targets.

For the most part, this should not be a user-visible change with the exception that some
of the invalid statements, such as GRANT ... ON TENANT 5, no longer parse. No tests had
to be altered for this change.

Fixes #84074.

Release note: none.

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
Trivial cdc change LGTM. We forked changefeed_targets from grant_targets very recently too. There's probably more refactoring of the various targets to come since there's some shared logic between backup and cdc that uses target objects, and we may want to make changefeed targets a subset of grant targets to help with granular permissions.

> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-:-N6xTX-qDZrO-Mad9L_j:b-w1n71s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @rhu713)

**Comment by knz** [comment]
maybe "fixes #84074" in the pr desc?

**Review by knz — APPROVED** [review]
LGTM modulo fixing the docgen rules.

> Reviewed 21 of 23 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-:-N6xiEIfCYzQWLT71mWy:b-l1c4xs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @rhu713)

___
*[`docs/generated/sql/bnf/create_schedule_for_backup_stmt.bnf` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhadqAcesUbq_KTsZ:-N6xhadqAcesUbq_KTs_:b7xfyyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/create_schedule_for_backup_stmt.bnf#L2)):*
> ```
> create_schedule_for_backup_stmt ::=
> 	'CREATE' 'SCHEDULE' schedule_label_spec 'FOR' 'BACKUP' backup_( | ( 'TABLE' | ) table_pattern ( ( ',' table_pattern ) )* | 'DATABASE' database_name ( ( ',' database_name ) )* ) 'INTO' string_or_placeholder 'WITH' backup_options_list 'RECURRING' cronexpr 'FULL' 'BACKUP' sconst_or_placeholder 'WITH' 'SCHEDULE' 'OPTIONS' kv_option_list
> ```

this does not look right. you need to change the substitution rules in docgen
___
*[`docs/generated/sql/bnf/restore.bnf` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhg5v7GgeEWQ9yAQ2:-N6xhg5v7GgeEWQ9yAQ3:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/restore.bnf#L14)):*
> ```
> 	| 'RESTORE' 'FROM' ( ( subdirectory | 'LATEST' ) ) 'IN' ( collectionURI | '(' localityURI ( ',' localityURI )* ')' )  'WITH' 'OPTIONS' '(' restore_options_list ')'
> 	| 'RESTORE' 'FROM' ( ( subdirectory | 'LATEST' ) ) 'IN' ( collectionURI | '(' localityURI ( ',' localityURI )* ')' )  
> 	| 'RESTORE' backup_( 'TABLE' table_pattern ( ( ',' table_pattern ) )* | 'DATABASE' database_name ( ( ',' database_name ) )* ) 'FROM' ( collectionURI | '(' localityURI ( ',' localityURI )* ')' ) 'AS' 'OF' 'SYSTEM' 'TIME' timestamp 'WITH' restore_options_list
> ```

ditto
___
*[`docs/generated/sql/bnf/show_grants_stmt.bnf` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhiXN94B1K01KAekg:-N6xhiXN94B1K01KAekh:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/show_grants_stmt.bnf#L10)):*
> ```
> 	| 'SHOW' 'GRANTS' 'ON' 'TYPE' type_name ( ( ',' type_name ) )* 'FOR' role_spec_list
> 	| 'SHOW' 'GRANTS' 'ON' 'TYPE' type_name ( ( ',' type_name ) )* 
> 	| 'SHOW' 'GRANTS' 'ON' grant_( | 'TABLE' table_name ( ( ',' table_name ) )* | 'DATABASE' database_name ( ( ',' database_name ) )* ) 'FOR' role_spec_list
> ```

ditto
___
*[`pkg/sql/parser/sql.y` line 7200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhwV84-YL1Rz0Cvdv:-N6xhwV84-YL1Rz0Cvdw:b-dql2ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/pkg/sql/parser/sql.y#L7200)):*
> ```Yacc
>     $$.val = tree.GrantTargetList{Tables: tree.TableAttrs{SequenceOnly: false, TablePatterns: $2.tablePatterns()}}
>   }
> // TODO(knz): This should learn how to parse more complex expressions
> ```

This comment belongs equally to the various clauses, so you could pull it up as comment to `grant_target`

It _also_ applies to `backup_targets` below.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84304)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @rhu713)

___
*[`pkg/sql/parser/sql.y` line 7200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhwV84-YL1Rz0Cvdv:-N6xkJ2uC0yGB_XndSX0:bfr3f81) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/pkg/sql/parser/sql.y#L7200)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This comment belongs equally to the various clauses, so you could pull it up as comment to `grant_target`

It _also_ applies to `backup_targets` below.
</blockquote></details>

pulled it up.

backup_targets comment already points readers to grant_targets so I think that side is set.
___
*[`docs/generated/sql/bnf/create_schedule_for_backup_stmt.bnf` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhadqAcesUbq_KTsZ:-N6xkZEZ-PrwA9hAx3Ny:b-hr6f88) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/create_schedule_for_backup_stmt.bnf#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this does not look right. you need to change the substitution rules in docgen
</blockquote></details>

Nice catch!

Done.
___
*[`docs/generated/sql/bnf/restore.bnf` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhg5v7GgeEWQ9yAQ2:-N6xk_pe0bPtuas_Pkd6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/restore.bnf#L14)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`docs/generated/sql/bnf/show_grants_stmt.bnf` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-N6xhiXN94B1K01KAekg:-N6xkaYr1K2lmY5MV97E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/989270365c8758ea8178533104d02f53ab230b26/docs/generated/sql/bnf/show_grants_stmt.bnf#L10)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
still lgtm

> Reviewed 2 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84304#-:-N72BePU8hp49AYdQBAs:bh6086p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @rhu713)

**Comment by dt** [comment]
TFTRs!

bors+

**Pull request merged**
