### PR TITLE
sql/parser: add `sequence_name_list` and `view_name_list`

### LINKED ISSUE #86059: Update sql.y to reference `sequence_name` instead of `table_name` in DROP SEQUENCE
null

Jira issue: CRDB-18548

### PR DESCRIPTION
**Pull request by ajwerner**
This will hopefully make for better diagrams.

Fixes #86059

Release justification: docs only change

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
I'm not certain that this is an improvement. Maybe it is. Who's our parser guru?

**Comment by ajwerner** [comment]
What I do not understand is why the view and sequence types get nice list names in their diagrams, but the `DROP TABLE` statement doesn't.

**Comment by ajwerner** [comment]
Oh, I figured it out -- it's here https://github.com/cockroachdb/cockroach/blob/03170d5eea13d8310ba5811fdf0d0c429c397f2c/pkg/cmd/docgen/diagrams.go#L863

I don't know what we want -- should we just *not* inline `table_name_list`? Was it nice to inline it? Should I make a list variety for each of the subtypes and then inline all of them? That's probably the most consistent.

**Comment by stbof** [comment]
> Oh, I figured it out -- it's here
> 
> https://github.com/cockroachdb/cockroach/blob/03170d5eea13d8310ba5811fdf0d0c429c397f2c/pkg/cmd/docgen/diagrams.go#L863
> 
> I don't know what we want -- should we just _not_ inline `table_name_list`? Was it nice to inline it? Should I make a list variety for each of the subtypes and then inline all of them? That's probably the most consistent: but also the most ugly.

Choosing to inline something is at writer discretion. I don't know why those choices were made, as it was before my time. You can revert that if you feel it's appropriate.

**Comment by ajwerner** [comment]
I've removed the inlining. Whether this is an improvement, I don't know. I'll let you @stbof decide or advise on further refinement.

**Comment by stbof** [comment]
> I've removed the inlining. Whether this is an improvement, I don't know. I'll let you @stbof decide or advise on further refinement.

I'll build the updated diagrams and see how they look.

**Review by ghost — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r=stbof

**Pull request merged**
