### PR TITLE
sql: consolidate opt variants of logic tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
Because of differences between the HP and CBO, we had to split up
various logic tests into opt-only variants. Now that the HP is gone,
we can merge these back.

The fk and cascades still have two variants because we still have two
FK-related code paths.

The commit includes a minor fix for a crash when using
`COCKROACH_DISTSQL_LOG_PLAN=1`.

Release note: None.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-:-Lrosq6U27RjIV5svSCw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-LrorO6f-WUaFGfnz16u:-LrorO6f-WUaFGfnz16v:b-e73qg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c699575ffe1914d78a811da459327bf5f22960/pkg/sql/distsql_running.go#L326)):*
> ```Go
> 
> 	if logPlanDiagram {
> 		log.VEvent(ctx, 1, "creating plan diagram")
> ```

did you mean to get rid of this logging statement?
___
*[pkg/sql/logictest/testdata/logic_test/numeric_references_opt, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-Lros-eh2XWEJrC9oWqS:-Lros-eh2XWEJrC9oWqT:b-htsg7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c699575ffe1914d78a811da459327bf5f22960/pkg/sql/logictest/testdata/logic_test/numeric_references_opt#L4)):*
> ```
> # ------------------------------------------------------------------------------
> # Numeric References Tests.
> # These are put at the beginning of the file to ensure the numeric table
> ```

Is this comment relevant anymore?
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-LrosGy05eDuhkum-KSx:-LrosGy05eDuhkum-KSy:b5xc1ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/49916f586b5c45fef4674b7218b9a550a1d6ee34/pkg/sql/logictest/testdata/logic_test/subquery#L527)):*
> ```
> INSERT INTO abc VALUES (1,2, (SELECT crdb_internal.force_error('foo', 'bar')))
> 
> # Regression test for #37263. This test is broken in the heuristic planner
> ```

Maybe remove reference to heuristic planner here?

**Review by justinj — COMMENTED** [review]
nice :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-:-LroxmAVBSDXaFONVXCZ:bh3gxoq)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41817)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/distsql_running.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-LrorO6f-WUaFGfnz16u:-Lrp-FDK6iCOiZaoMGeN:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c699575ffe1914d78a811da459327bf5f22960/pkg/sql/distsql_running.go#L326)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to get rid of this logging statement?
</blockquote></details>

Good catch, fixed.
___
*[pkg/sql/logictest/testdata/logic_test/numeric_references_opt, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-Lros-eh2XWEJrC9oWqS:-Lrp-Uqr4Rv2UXJVL9Rh:bj14rma) ([raw file](https://github.com/cockroachdb/cockroach/blob/55c699575ffe1914d78a811da459327bf5f22960/pkg/sql/logictest/testdata/logic_test/numeric_references_opt#L4)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this comment relevant anymore?
</blockquote></details>

No, it's stale, the tests were converted to use `let $num_ref_id` rather than hardcoded ids a while back.
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-LrosGy05eDuhkum-KSx:-Lrp-f_Y3mWcbDSM6L3L:b-h523z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/49916f586b5c45fef4674b7218b9a550a1d6ee34/pkg/sql/logictest/testdata/logic_test/subquery#L527)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Maybe remove reference to heuristic planner here?
</blockquote></details>

Done. I also grepped for `heuristic` and `HP` and found more things to clean up.

**Review by rytaft — APPROVED** [review]
:lgtm: nice cleanup!

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41817#-:-Lrp7J-uE9txAnSykH9p:b-qbsc6n)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
