### PR TITLE
sql: don't panic on unimplemented

### LINKED ISSUE #4355: sql: Unimplemented SQL should not panic
It's currently trivial to kill the server by sending a SQL statement we don't implement (`ALTER TABLE tbl ADD CONSTRAINT ...`). We need to replace the `panic("TODO(pmattis): unimplemented")` in `sql.y` with a softer approach to error handling.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #4355

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4425)

### CODE REVIEW

**Comment by mjibson** [comment]
The added test here without the accompanying change panics the server.

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/parse.go, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425#-KAhFubRmAbP8yMbRYD8:-KAhFubRmAbP8yMbRYD9:-1353630705) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e07b412f672e27df8b27098e0323e2fba485abb/sql/parser/parse.go#L72)):*
I'm not really sure why there's a type cast here.
```go
switch r := recover() {
case nil:
case errUnimplemented:
  err = r
default:
  panic(r)
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425)*

**Comment by mjibson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/parse.go, line 72 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425#-KAhFubRmAbP8yMbRYD8:-KAhI7di5kZMDmylfpCL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e07b412f672e27df8b27098e0323e2fba485abb/sql/parser/parse.go#L72)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425#-:-KAhJ78i14snsNd6_bxA:676834233)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4425#-:-KAjoK8VumTepbEd3LSR:676834233)*

**Pull request merged**
