### PR TITLE
*: improve inline code comments

### PR DESCRIPTION
**Pull request by Azhng**
Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-:-N1YfB-y5onK8eflwBJT:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81108)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @Azhng)

___
*[`pkg/sql/tests/server_params.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-N1dX2JXDsJWCswmYlAi:-N1dX2JXDsJWCswmYlAj:bqad2kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42bd3fbbada785e4f11ce5656c8ef248322cdd6/pkg/sql/tests/server_params.go#L49)):*
I see. But I still find the wide use of this knob questionable. It sounds like in production these "descriptor not found" errors are possible for new clusters, so why should so many unit tests get a blanket blue pill? How many tests would need to set this knob to keep working?

> //       Additionally, we don't want to completely remove the AOST clause in the
> //       unit test.

Any particular reason why don't we want to completely remove it? If the only reason is that removing it completely would be harder / require more code, I'd scratch the whole paragraph.
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-N1dSx_a6J2hVrwrRLPk:-N1dSx_a6J2hVrwrRLPl:b-dm6s1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42bd3fbbada785e4f11ce5656c8ef248322cdd6/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L277)):*
> ```Go
> // stats system table that are in the current aggregation window and previous
> // aggregation window. Before running the SQL Stats compaction, we lower the
> // row limit in the stats table so that all thw rows will be deleted by the
> ```

thw -> the
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-N1dTrKY48gKCrzyHOGq:-N1dTrKY48gKCrzyHOGr:bm67ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42bd3fbbada785e4f11ce5656c8ef248322cdd6/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L281)):*
> ```Go
> // aggregation window. This test asserts that, since some of generated rows live
> // in the current aggregation interval, those rows will not be deleted by the
> // StatsCompactor.
> ```

Now I understand what's going on; thanks. Please consider adding a comment to `StatsCompactor.getQargs` saying that the reason the last hour is excluded is to avoid contention.

I'd consider changing the name of this test; by putting "interference" in there, you suggest that we're directly testing for "interference" - I expected a trace to be collected or something to check for the absence of contention. Instead, this test checks a straight-forward mechanism (the fact that the current interval is exempt from contention), as so I'd name it as such - consider `TestSQLStatsCompactionCurrentIntervalExempt` and add the comment to remind why the interval is exempt. Going deeper into nit territory :), the comment as written is a bit long and convoluted. I'd say more simply something like:
```
Test that stats belonging to the current aggregation interval are exempt from deletion by the stats compactor. We exempt them, at the risk of an unbounded number of stats, in order to avoid contention between the compaction job and foreground stats insertions/updates.
```

Btw, I don't see any checks in this test that the compactor deletes any rows (from the previous interval). So, is the part where we `Generate some data that are older than the current aggregation window` relevant to the test?

**Review by Azhng — COMMENTED** [review]
Thanks for taking a look. I don't think I will have enough time to push this PR through before end of today so someone else prolly need to take over.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-:-N1eN7zo2ieePJUGSG8j:b-v6k33v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @Azhng)

___
*[`pkg/sql/tests/server_params.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-N1dX2JXDsJWCswmYlAi:-N1eMruH4I6pqlkmR_sR:bjskxdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42bd3fbbada785e4f11ce5656c8ef248322cdd6/pkg/sql/tests/server_params.go#L49)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see. But I still find the wide use of this knob questionable. It sounds like in production these "descriptor not found" errors are possible for new clusters, so why should so many unit tests get a blanket blue pill? How many tests would need to set this knob to keep working?

> //       Additionally, we don't want to completely remove the AOST clause in the
> //       unit test.

Any particular reason why don't we want to completely remove it? If the only reason is that removing it completely would be harder / require more code, I'd scratch the whole paragraph.

</blockquote></details>

I remember quite a few tests flaked back then and it was deflaked when this knobs are introduced. Tbh I think it's not too difficult to write a bit of more code in the knobs to clean this up. 
___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81108#-N1dTrKY48gKCrzyHOGq:-N1eM-QmEuf8Ge9adz1-:btrj3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42bd3fbbada785e4f11ce5656c8ef248322cdd6/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L281)):*


> Btw, I don't see any checks in this test that the compactor deletes any rows (from the previous interval). So, is the part where we Generate some data that are older than the current aggregation window relevant to the test?

This is checked by writing [20 rows](https://github.com/cockroachdb/cockroach/pull/81108/files#diff-c481b38f2f966271e4273bf057d6a9c1d05066333792f32118a107d82f20049eL296-L301) into the system table, then assert latter that only [10 rows](https://github.com/cockroachdb/cockroach/pull/81108/files#diff-c481b38f2f966271e4273bf057d6a9c1d05066333792f32118a107d82f20049eL318-L332) remains. Since 10 out of the 20 rows written is exempted. Any rows that no longer remain are presumed to be deleted by the stats compactor.

**Pull request merged**
