### PR TITLE
tsearch: speed up TSVector.String

### LINKED ISSUE #98595: tsvector: speed up DTSVector.Size
As discovered while working on #98513, `DTSVector.Size` can be quite inefficient. This is because we're simply calling `String` and then take its length; `String` internally allocates many `strings.Builder`s. Ideally, we'd implement separate `Size` method that avoids actually writing the stringified version.

Screenshot 2023-03-14 at 10 17 23 AM

Jira issue: CRDB-25350

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #98595.

**tsearch: speed up TSVector.String**

This commit speeds up `TSVector.String` by reusing exactly the same
`strings.Builder` object for all parts of the TSVector.

This commit also introduces a simple benchmark for this method.
`benchstat` seems to be busted a bit, but the impact of this commit is:
```
                       │ /tmp/tmp.Unz2XLUFdB/bench.HEAD^^ │   /tmp/tmp.Unz2XLUFdB/bench.HEAD^   │
                       │              sec/op              │   sec/op     vs base                │
TSVector/String-24                           14.590m ± 0%   8.272m ± 0%  -43.31% (p=0.000 n=10)
TSVector/StringSize-24                       14.654m ± 0%   8.269m ± 0%  -43.57% (p=0.000 n=10)
geomean                                       14.62m        8.270m       -43.44%

                       │ /tmp/tmp.Unz2XLUFdB/bench.HEAD^^ │   /tmp/tmp.Unz2XLUFdB/bench.HEAD^    │
                       │               B/op               │     B/op      vs base                │
TSVector/String-24                           4.516Mi ± 0%   2.319Mi ± 0%  -48.65% (p=0.000 n=10)
TSVector/StringSize-24                       4.516Mi ± 0%   2.319Mi ± 0%  -48.65% (p=0.000 n=10)
geomean                                      4.516Mi        2.319Mi       -48.65%

                       │ /tmp/tmp.Unz2XLUFdB/bench.HEAD^^ │   /tmp/tmp.Unz2XLUFdB/bench.HEAD^   │
                       │            allocs/op             │  allocs/op   vs base                │
TSVector/String-24                            273.6k ± 0%   105.6k ± 0%  -61.41% (p=0.000 n=10)
TSVector/StringSize-24                        273.6k ± 0%   105.6k ± 0%  -61.41% (p=0.000 n=10)
geomean                                       273.6k        105.6k       -61.41%
```

Release note: None

**tsearch: add optimize StringSize method**

This commit introduces `TSVector.StringSize` method which is optimized
equivalent of `len(TSVector.String())` which avoids the construction of
the string. This method is now utilized by `DTSVector.Size`. This
results in some code duplication but it seems worth it:
```
                       │ /tmp/tmp.zD8FYqMrdo/bench.HEAD^ │   /tmp/tmp.zD8FYqMrdo/bench.HEAD    │
                       │             sec/op              │   sec/op     vs base                │
TSVector/String-24                           8.404m ± 0%   8.135m ± 0%   -3.20% (p=0.000 n=10)
TSVector/StringSize-24                       8.381m ± 0%   3.547m ± 0%  -57.67% (p=0.000 n=10)
geomean                                      8.393m        5.372m       -35.99%

                       │ /tmp/tmp.zD8FYqMrdo/bench.HEAD^ │    /tmp/tmp.zD8FYqMrdo/bench.HEAD    │
                       │              B/op               │     B/op      vs base                │
TSVector/String-24                          2.349Mi ± 0%   2.323Mi ± 0%   -1.12% (p=0.000 n=10)
TSVector/StringSize-24                     2405.6Ki ± 0%   192.1Ki ± 0%  -92.02% (p=0.000 n=10)
geomean                                     2.349Mi        675.9Ki       -71.90%

                       │ /tmp/tmp.zD8FYqMrdo/bench.HEAD^ │   /tmp/tmp.zD8FYqMrdo/bench.HEAD    │
                       │            allocs/op            │  allocs/op   vs base                │
TSVector/String-24                           106.7k ± 0%   105.8k ± 0%   -0.88% (p=0.000 n=10)
TSVector/StringSize-24                      106.72k ± 0%   61.46k ± 0%  -42.41% (p=0.000 n=10)
geomean                                      106.7k        80.63k       -24.44%
```

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Nice speedup!

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98609#-:-NQaAveU8EYWvkHjXUl-:b9lpb3n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/util/tsearch/tsvector.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98609#-NQa8s63BrittUq1Uv7C:-NQa8s63BrittUq1Uv7D:b96i8g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3518ac84600d2041bb7144629054d501185081f8/pkg/util/tsearch/tsvector.go#L148)):*
> ```Go
> 
> // uint16ToString is a map of all possible uint16 values to their string
> // representation.
> ```

nit: I'm not sure this is really worth the giant lookup table. `strconv.Itoa` already uses something like this for ints 0-99. I vote we get rid of this and just use `strconv.Itoa`.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

I'll give Marcus a chance to take a look as well, but it's not required, so Marcus feel free to ignore this PR, and I'll merge tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98609#-:-NQahh8n8lht8r8suXeq:b-d6y7gb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/util/tsearch/tsvector.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98609#-NQa8s63BrittUq1Uv7C:-NQadBpa2jODKZQhk3qx:b-ymhsud) ([raw file](https://github.com/cockroachdb/cockroach/blob/3518ac84600d2041bb7144629054d501185081f8/pkg/util/tsearch/tsvector.go#L148)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I'm not sure this is really worth the giant lookup table. `strconv.Itoa` already uses something like this for ints 0-99. I vote we get rid of this and just use `strconv.Itoa`.
</blockquote></details>

Hm, I made the change to use `strconv.Itoa`, and here is the perf impact of that (for some reason new `benchstat` seems busted):
```
                       │ /tmp/tmp.Tn9lszhPs8/bench.HEAD^ │   /tmp/tmp.Tn9lszhPs8/bench.HEAD    │
                       │             sec/op              │   sec/op     vs base                │
TSVector/String-24                           6.192m ± 8%   8.115m ± 0%  +31.05% (p=0.000 n=10)
TSVector/StringSize-24                       1.830m ± 0%   3.572m ± 0%  +95.16% (p=0.000 n=10)
geomean                                      3.367m        5.384m       +59.93%

                       │ /tmp/tmp.Tn9lszhPs8/bench.HEAD^ │    /tmp/tmp.Tn9lszhPs8/bench.HEAD    │
                       │              B/op               │     B/op      vs base                │
TSVector/String-24                        2.106Mi ± 0%     2.352Mi ± 0%  +11.66% (p=0.000 n=10)
TSVector/StringSize-24                      0.0Ki ± 0%     195.1Ki ± 0%        ? (p=0.000 n=10)
geomean                                                ¹   685.4Ki       ?
¹ summaries must be >0 to compute geomean

                       │ /tmp/tmp.Tn9lszhPs8/bench.HEAD^ │    /tmp/tmp.Tn9lszhPs8/bench.HEAD     │
                       │            allocs/op            │  allocs/op    vs base                 │
TSVector/String-24                         44.30k ± 0%     106.96k ± 0%  +141.47% (p=0.000 n=10)
TSVector/StringSize-24                      0.00k ± 0%      62.42k ± 0%         ? (p=0.000 n=10)
geomean                                                ¹    81.71k       ?
¹ summaries must be >0 to compute geomean
```

I wrote a few lines to estimate the size of this array, and and it came out to 1.3MiB. Perhaps this improvement is, indeed, not worth it, removed.

**Comment by yuzefovich** [comment]
unrelated flake

bors r+

**Pull request merged**
