### PR TITLE
server, ui, storage: added warnings when node locality doesn't match cluster

### PR DESCRIPTION
**Pull request by d4l3k**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9077)

### CODE REVIEW

**Comment by BramGruneir** [comment]
@maxlang, I'll review the server side code.

Also, an unrelated thought, should we be starting to consider doing i18n translations soon?

@d4l3k, this is a quick implementation of a basic warning system, but I think some more thought as to where they should live, how often they should be updated, might be warranted.  
But I love the idea.

---

Reviewed 6 of 16 files at r1.
Review status: 6 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin_test.go, line 898 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9077#-KQvWETHC7Yrkksjwj6R:-KQvWETHC7Yrkksjwj6S:b3395nx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4026b85a63dba5468197f5c618e8c06c17f597f6/server/admin_test.go#L898)):*
> ```Go
> }
> 
> func TestServerWarnings(t *testing.T) {
> ```

Shouldn't this test actually try returning 0, 1 and 2 warnings?  

---

*[storage/store_pool.go, line 420 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9077#-KQvWodNoRxQaz49jv8B:-KQvWodOHFGAeThuJgzh:b-zhz4f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4026b85a63dba5468197f5c618e8c06c17f597f6/storage/store_pool.go#L420)):*
> ```Go
> // Warnings returns all warnings that should be seen by the user.
> func (sp *StorePool) Warnings() []serverpb.ServerWarning {
> 	var warnings []serverpb.ServerWarning
> ```

Since these are server warnings, should this storage of the warnings be on server or node?  The storepool seems like a strange place to store them.

---

*[storage/store_pool_test.go, line 554 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9077#-KQvXEn8KIDQ4Lq-rr3F:-KQvXEn8KIDQ4Lq-rr3G:b-1wh3oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4026b85a63dba5468197f5c618e8c06c17f597f6/storage/store_pool_test.go#L554)):*
> ```Go
> 
> func TestStorePoolWarnings(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> ```

This test should actually show warnings and non-warnings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9077#-:-KQvTY2zJENrVxEBVbrn:b-je1ifm)*

**Comment by tamird** [comment]
Rebased this, but it doesn't compile because various store pool methods have changed. @BramGruneir could you take a look?

**Comment by tamird** [comment]
Ah, shoot. I can't actually push to @d4l3k's fork. Tristan, could you give me commit access? I'll carry this PR through.

**Comment by d4l3k** [comment]
@tamird, just added you! Sorry for the delay

**Comment by BramGruneir** [comment]
@piyush-singh  We need to resurrect this idea, but not this specific code.  Can you file a new issue.

**Pull request closed without merging**
