### PR TITLE
ui: Add "roundtrip" clarification for tooltip values on Network latency metrics

### LINKED ISSUE #45221: ui: indicate network latencies page measure RTT
The network latency matrix page and tooltips are currently ambiguous about whether the listed times are one way or round trip times. We should make this clearer on the page or at the very least on hover in the tooltips.

Thank you to @irfansharif for pointing this out. cc @Annebirzin

### PR DESCRIPTION
**Pull request by koorosh**
Resolves: #45221

Change tooltip text to clarify what values mean. 

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> ui: Enhance tooltip text for Network latency metrics

Can you rename this PR and commit to be more specific? The change is only adding the "roundtrip" string.

Also add a Release justification

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45647#-:-M2eW8HXE6OK_rHBd0Vk:bp5rx4z)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by koorosh** [comment]
> > ui: Enhance tooltip text for Network latency metrics
> 
> Can you rename this PR and commit to be more specific? The change is only adding the "roundtrip" string.
> 
> Also add a Release justification
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45647#-:-M2eW8HXE6OK_rHBd0Vk:bp5rx4z)_ status: :shipit: complete! 0 of 0 LGTMs obtained

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

I don't want to do another update on this but please keep first line of commit message short in the future so that it appears nicely in git logs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45647#-:-M2jIDcf1Lpof3tlEhUg:bqhmc7h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
