### PR TITLE
makefile: add a ui target to the main makefile

### PR DESCRIPTION
**Pull request by BramGruneir**
So now you can invode the ui makefile without changing directories.

### CODE REVIEW

**Comment by tamird** [comment]
I'm :-1: on adding random stuff to the Makefiles. In this case, you might be able to get the same effect by locally defining an alias for `make -C pkg/ui`.

**Comment by BramGruneir** [comment]
I think we should add this as part of the new `make check`.
I don't think it's random to be able to make the ui.

**Comment by tamird** [comment]
> I don't think it's random to be able to make the ui.

This is a straw. You can already build the UI, this is just an alias. I'll let others weigh in.

**Comment by BramGruneir** [comment]
Besides the ui, is there any other aspect of our codebase that can't be built via the main makefile?  Seems strange to isolate it.

**Comment by tamird** [comment]
The UI can already be built via `make generate`; does that serve your
needs? That invocation doesn't run the tests, though.

**Comment by BramGruneir** [comment]
I'll let other chime in, but I'd rather test the UI as well to make sure nothing is broken.

**Comment by tamird** [comment]
As a development workflow, testing the UI via `make` is probably not what you want; instead, we should surface a persistent test session that runs the tests whenever you save a file or refresh a browser. Running via unary `make` commands will be terribly slow (~1 minute just to compile the sources, each time).

**Comment by benesch** [comment]
I think @BramGruneir's long-standing desire is a `make pre-commit` target that verifies all linters and tests pass locally, and it's okay if it takes ~10m to run. Is that fair to say, Bram?

This seems like a necessary step towards exposing such a target. I'm thinking something like:

```bash
pre-commit: generate test lint ui
```

**Comment by BramGruneir** [comment]
Yep, that's exactly what I'd like to do.  Instead of waiting on TC to do that work for me.  Which is typically a much longer wait.

**Comment by benesch** [comment]
Closing since this got grafted onto #15909! @BramGruneir, let me know if `make pre-push` falls short of your hopes and dreams.

**Pull request closed without merging**
