### PR TITLE
ccl: add support for additional sasl mechanisms (SCRAM-SHA-256 and SCRAM-SHA-512)

### PR DESCRIPTION
**Pull request by stevendanna**
This add support to specify the SASL mechanism for Kafka Changefeed
DSNs via the `sasl_mechanism` option. Further, we add support for
SCRAM-SHA-256 and SCRAM-SHA-512 in addition to the previously
supported PLAIN mechanism.

Release note (ccl change): Add `sasl_mechanism` parameter to Kafka
Changefeed DSNs to specify SASL mechanism. CockroachDB supports the
PLAIN, SCRAM-SHA-256, and SCRAM-SHA-512 SASL mechanisms.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[pkg/cmd/roachtest/cdc.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60150#-MT7IQOH7jEUIP-iTDO7:-MT7IQOH7jEUIP-iTDO8:b-vctze3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc75a420832fadce803482b0bcbe4bec5a3623a6/pkg/cmd/roachtest/cdc.go#L550)):*
> ```Go
> 	if err := db.QueryRow(
> 		`CREATE CHANGEFEED FOR auth_test_table INTO $1`,
> 		fmt.Sprintf("%s?tls_enabled=true&ca_cert=%s&sasl_enabled=true&sasl_user=plain&sasl_password=plain-secret", kafka.sinkURLSASL(ctx), testCerts.CACertBase64()),
> ```

Are we losing all our tests of non-SCRAM logins here?
___
*[pkg/cmd/roachtest/cdc.go, line 921 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60150#-MT7IJIC8w0DXahpg81-:-MT7IJIDCO8CoJ0nH-3n:b-ntdmz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da9bc474b9bc13fda904c7681b4292656e1bcb1/pkg/cmd/roachtest/cdc.go#L921)):*
> ```Go
>    org.apache.kafka.common.security.plain.PlainLoginModule required
>    username="admin"
>    password="admin-secret"
> ```

We should probably use different usernames/passwords for the different login methods so the test makes sure that we're not succeeding on the plaintext path and all the SASL stuff is getting ignored.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @dt)

___
*[pkg/cmd/roachtest/cdc.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60150#-MT7IQOH7jEUIP-iTDO7:-MT7VvWU3uJ3o9Z6KqD8:but4v5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc75a420832fadce803482b0bcbe4bec5a3623a6/pkg/cmd/roachtest/cdc.go#L550)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Are we losing all our tests of non-SCRAM logins here?
</blockquote></details>

D'oh. Thanks for catching this. We can test all three, I just was too aggressive when fixing a rebase conflict.
___
*[pkg/cmd/roachtest/cdc.go, line 921 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60150#-MT7IJIC8w0DXahpg81-:-MT7WFBZBI-RpCLUdSin:b-bkpwya) ([raw file](https://github.com/cockroachdb/cockroach/blob/3da9bc474b9bc13fda904c7681b4292656e1bcb1/pkg/cmd/roachtest/cdc.go#L921)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We should probably use different usernames/passwords for the different login methods so the test makes sure that we're not succeeding on the plaintext path and all the SASL stuff is getting ignored. 
</blockquote></details>

We do use different usernames for each login method that is used from cockroach.  I've kept the "admin" password the same, but that should only be used by kafka internally for inter-broker communication.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60150)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @dt)

___
*[pkg/cmd/roachtest/cdc.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60150#-MT7IQOH7jEUIP-iTDO7:-MT7Z5-O7UQIvBBRy0xz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc75a420832fadce803482b0bcbe4bec5a3623a6/pkg/cmd/roachtest/cdc.go#L550)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

D'oh. Thanks for catching this. We can test all three, I just was too aggressive when fixing a rebase conflict.
</blockquote></details>

Done.

**Comment by stevendanna** [comment]
bors r=bdarnell

**Comment by Neustradamus** [comment]
@stevendanna: Thanks a lot for all about SCRAM.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-xmpp/info/issues/1
- https://github.com/cockroachdb/cockroach/issues/42519
- https://github.com/cockroachdb/cockroach/issues/55788
- https://github.com/cockroachdb/cockroach/pull/60150
- https://github.com/cockroachdb/cockroach/issues/74300
- https://github.com/cockroachdb/cockroach/pull/74301

**Pull request merged**
