### PR TITLE
sql: set default for large_full_scan_rows to 0

### LINKED ISSUE #130726: sql: explore setting default for large_full_scan_rows to 0
Now that #122708 is fixed, we should explore whether we can set the default for `large_full_scan_rows` to 0. This would make the behavior of `disallow_full_table_scans` less surprising for most users.

Jira issue: CRDB-42192

### PR DESCRIPTION
**Pull request by michae2**
In #69371 we set the default for `large_full_scan_rows` to 1000. This default can be surprising for users of `disallow_full_table_scans`. Now that #122708 is fixed, let's set the default to 0 so that the exemption for small tables is opt-in rather than opt-out.

Fixes: #130726

Release note (sql change): Set the default for session variable `large_full_scan_rows` to 0. This means that by default, `disallow_full_table_scans` will disallow _all_ full table scans, even full scans on very small tables. If `large_full_scan_rows` is set > 0, `disallow_full_table_scans` will allow full scans estimated to read fewer than `large_full_scan_rows`.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-:-O7AxzTX-lLRnKctjxkU:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @mw5h)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-O7Ax7naCgcbfDZd0oHa):*
We should probably update the docs [here](https://www.cockroachlabs.com/docs/stable/set-vars) to make it ultra clear what the defaults of `large_full_scan_rows` are within the description of `disallow_full_table_scans` and what the implications are when enabling `disallow_full_table_scans`: that ALL queries with a full table scan will result in an error. cc @taroface I believe those descriptions are owned by the docs team, and not in code, but correct me if I'm wrong.
___
*[`pkg/sql/exec_util.go` line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-O7AxmC441NnDw8H5Ngc:-O7AxmC441NnDw8H5Ngd:boy922b) ([raw file](https://github.com/cockroachdb/cockroach/blob/967996ce9547697fa077165877d38f0e164b49ce/pkg/sql/exec_util.go#L714)):*
> ```Go
> 	"default value for large_full_scan_rows session setting which determines "+
> 		"the maximum table size allowed for a full scan when disallow_full_table_scans "+
> 		"is set to true",
> ```

nit: add something like this helpful bit from the session setting docs: "To reject all full table or index scans, set to `0`."

**Comment by taroface** [comment]
> :lgtm: Thanks!
> 
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-:-O7AxzTX-lLRnKctjxkU:b-g2a5fb)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @mw5h)
> 
> _[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-O7Ax7naCgcbfDZd0oHa):_ We should probably update the docs [here](https://www.cockroachlabs.com/docs/stable/set-vars) to make it ultra clear what the defaults of `large_full_scan_rows` are within the description of `disallow_full_table_scans` and what the implications are when enabling `disallow_full_table_scans`: that ALL queries with a full table scan will result in an error. cc @taroface I believe those descriptions are owned by the docs team, and not in code, but correct me if I'm wrong.

That's correct -- since this PR has a release note, it will generate a corresponding DOC (product change) issue when merged. The doc update will be tracked in that issue.

**Review by michae2 — COMMENTED** [review]
TFTR!

bors r=mgartner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-:-O7GY6UI3l4kRGJ9bMrI:b838j8n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @mw5h)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-O7Ax7naCgcbfDZd0oHa):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should probably update the docs [here](https://www.cockroachlabs.com/docs/stable/set-vars) to make it ultra clear what the defaults of `large_full_scan_rows` are within the description of `disallow_full_table_scans` and what the implications are when enabling `disallow_full_table_scans`: that ALL queries with a full table scan will result in an error. cc @taroface I believe those descriptions are owned by the docs team, and not in code, but correct me if I'm wrong.
</blockquote></details>

This one is generated, so I went ahead and updated it.
___
*[`pkg/sql/exec_util.go` line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131040#-O7AxmC441NnDw8H5Ngc:-O7GYMTp0mGOa6gDb1p3:b-th2zke) ([raw file](https://github.com/cockroachdb/cockroach/blob/967996ce9547697fa077165877d38f0e164b49ce/pkg/sql/exec_util.go#L714)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add something like this helpful bit from the session setting docs: "To reject all full table or index scans, set to `0`."
</blockquote></details>

good call, done

**Comment by mw5h** [comment]
:lgtm:

**Pull request merged**
