### PR TITLE
server,ui: Fix authentication bugs and inconsistencies

### LINKED ISSUE #51781: ui: Admin UI login is not case-insensitive like SQL shell
The SQL shell lower cases all characters in usernames upon creation, however the admin UI does not do something similar which can lead to confusion. From @florence-crl:

root@:26257/movr> CREATE USER Admin1 WITH PASSWORD 'cockroach' ;
CREATE ROLE

root@:26257/movr> GRANT admin to Admin1;
GRANT

root@:26257/movr> SHOW USERS;
  username |  options   | member_of
-----------+------------+------------
  admin    | CREATEROLE | {}
  admin1   |            | {admin}
  root     | CREATEROLE | {admin}
In Admin UI,
(A) If you sign in with all lower case username admin1, privileges work correctly.
(B) If you sign in with all mixed case username Admin1, privileges will NOT work correctly; most noticeably on the Databases and Statements pages

### LINKED ISSUE #55370: ui: users/roles with the NOLOGIN option are allowed to log in via OIDC
The OIDC flow does not check the NOLOGIN role option properly.

This allows users without the LOGIN bit to access the UI via OIDC. This is incorrect.

cc @dhartunian

### PR DESCRIPTION
**Pull request by knz**
Fixes #51781
Fixes #55370

This fixes two bugs. The one of the two that is a sec vuln only exists in 20.2.

### CODE REVIEW

**Comment by knz** [comment]
@bdarnell I think we need to backport the last commit to 20.2; should we also backport the other two changes?

**Review by dhartunian — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55371)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dhartunian, and @knz)

___
*[pkg/server/authentication.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-MJCs_Pc-AtYbiaHYAgA:-MJCs_Pc-AtYbiaHYAgB:b-r8wog0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8adc21b4db2abb062a9dada371e76a35b3b7f5b/pkg/server/authentication.go#L148)):*
> ```Go
> 	// table: the APIs extract the username from the session table
> 	// without further normalization.
> 	username = tree.Name(username).Normalize()
> ```

Could we replace the `string` type for a username with a custom type that enforces the normalization in one place? Looks like otherwise we have to keep track of this in many locations and it currently depends on you knowing them.
___
*[pkg/server/authentication.go, line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-MJCub0KETwj5d5MUQhR:-MJCub0LB1BWdVI9FrL4:b-31pwjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8adc21b4db2abb062a9dada371e76a35b3b7f5b/pkg/server/authentication.go#L415)):*
> ```Go
> 	// table: the APIs extract the username from the session table
> 	// without further normalization.
> 	username = tree.Name(username).Normalize()
> ```

Is this necessary here? I believe it's only called from `createSessionFor` which is used by `UserLoginFromSSO` and `UserLogin` which already normalize earlier.

**Review by bdarnell — APPROVED** [review]
:thumbsup: to backporting all three commits to 20.2.

> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-:-MJCzMQU4A1oxqOKNeOI:b81g404)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55371)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/server/authentication.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-MJCs_Pc-AtYbiaHYAgA:-MJDMP5QDhLg-842LcqI:b-1zkxua) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8adc21b4db2abb062a9dada371e76a35b3b7f5b/pkg/server/authentication.go#L148)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Could we replace the `string` type for a username with a custom type that enforces the normalization in one place? Looks like otherwise we have to keep track of this in many locations and it currently depends on you knowing them.
</blockquote></details>

That is a good idea. I will prepare a separate PR for this, as I  found that it also reveals (and fixes) a couple of unrelated SQL bugs.
___
*[pkg/server/authentication.go, line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-MJCub0KETwj5d5MUQhR:-MJD9V4h8mb3zD5JToaI:b-la9uzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8adc21b4db2abb062a9dada371e76a35b3b7f5b/pkg/server/authentication.go#L415)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is this necessary here? I believe it's only called from `createSessionFor` which is used by `UserLoginFromSSO` and `UserLogin` which already normalize earlier.
</blockquote></details>

Good catch! Simplified.

**Comment by knz** [comment]
@dhartunian ok to merge this even without the typing enhancement?

**Review by dhartunian — APPROVED** [review]
:lgtm: happy to do type enhancement in a separate PR. thanks!

> Reviewed 3 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55371#-:-MJDMlEp9f9OWwG5u_gp:b-24ghtm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @dhartunian)

**Comment by knz** [comment]
TFYRs!

bors r=dhartunian,bdarnell

**Pull request merged**
