### PR TITLE
sql/pgwire: change formatting of floating point infinity values

### LINKED ISSUE #62601: Cannot read floating point infinity values from JDBC
**Describe the problem**

PostgreSQL supports `'Inf'` as a valid literal for the floating point special value Infinity, but the JDBC driver can't seem to read it from CockroachDB

**To Reproduce**

```java
try (PreparedStatement s = connection.prepareStatement("select real 'Inf', double precision 'Inf'")) {
    try (ResultSet rs = s.executeQuery()) {
        while (rs.next()) {
            System.out.println(rs.getFloat(1));
            System.out.println(rs.getDouble(1));
        }
    }
}
```

**Expected behavior**

This works as expected in PostgreSQL, producing 2 times `Infinity`, but it doesn't work on CockorachDB, where I'm getting this error:

```
Exception in thread "main" org.postgresql.util.PSQLException: Unzulässiger Wert für den Typ float : +Inf.
	at org.postgresql.jdbc.PgResultSet.toFloat(PgResultSet.java:3091)
	at org.postgresql.jdbc.PgResultSet.getFloat(PgResultSet.java:2411)
```

One could argue the JDBC driver should understand it as well given that I can use the string literal in casts, too, even in PostgreSQL (`'Inf'::real`). But for interoperability reasons, but as it stands now, I can't seem to read these values from JDBC in CockroachDB, short of reading strings.

**Environment:**
 - CockroachDB version: CockroachDB CCL v21.1.0-alpha.1 (x86_64-unknown-linux-gnu, built 2020/12/08 17:01:49, go1.15.5)
 - Server OS: Linux in Docker in Windows
 - Client app: JDBC

### PR DESCRIPTION
**Pull request by iAziz786**
Fixes #62601 

Postgres drivers such as JDBC rely on infinite values to be
formatted as full words in order to be able to parse the
value.

Release note (sql change): Floating point infinity values are now
formatted as `Infinity` (or `-Infinity` if negative). This is for
compatibility with Postgres.

### CODE REVIEW

**Comment by iAziz786** [comment]
@rafiss I ran the test cases but for some reason, they were not hitting `func (d *DFloat) Format`. When I add `fmt.Println` into that function I only saw one log. Anything am I missing?

**Comment by rafiss** [comment]
@iAziz786 sorry for misdirecting you! it looks like the change to `func (d *DFloat) Format` is not necessary.

instead, this change needs to be done in pkg/sql/pgwire/types.go `writeTextDatum` in the `DFloat` case.

**Comment by rafiss** [comment]
That's interesting -- it looks like it's because the CLI has extra parse/format logic so that it displays the value as a golang infinity. if you connect with the `psql` tool (e.g. `psql -h localhost -p 26257 -U root -w -d defaultdb`), you should see your change in effect

this likely also explains why our other SQL tests are not affected by your change.

yes, please make this ready to review. before that, you will need to update the commit message (and PR message) to have a proper release note. See https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes

also, the title of the commit message should be adjusted. cockroachdb already supports infinity values -- this is just changing the formatting. see https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

 so a full commit message could be:

```
sql/pgwire: change formatting of floating point infinity values

Postgres drivers such as JDBC rely on infinite values to be
formatted as full words in order to be able to parse the
value.

Release note (sql change): Floating point infinity values are now
formatted as `Infinity` (or `-Infinity` if negative). This is for
compatibility with Postgres
```

Thanks for your work here! This is almost ready to go.

**Review by rafiss — APPROVED** [review]
thank you for your contribution!

bors r+

**Pull request merged**
