### PR TITLE
raft: do not campaign if supporting fortified leader 

### PR DESCRIPTION
**Pull request by arulajmani**
This patch ensures that peers that have promised fortification support
to a leader do not campaign unless StoreLiveness indicates support for
the leader's epoch has expired. This patch only affects campaigning
(either directly or in response to the randomized election timeout
elapsing) -- in a subsequent patch, we'll handle voting.

Note that once StoreLiveness indicates support for the leader has
expired, we aim to act swiftly. In particular, care is taken to
ensure a follower doesn't need to wait out its election timeout before
campaigning. We do preserve randomness to prevent hung elections though.

Informs https://github.com/cockroachdb/cockroach/issues/125351

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
I might want to add a pre-vote variant of the datadriven tests here as well. It shouldn't make much material difference, but it's good to have. I'll bundle it with review comments/a rebase once the other PR lands.

**Comment by arulajmani** [comment]
@nvanbenschoten rebased and should be good for a look.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 901 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vE4zy3QrFGDBj6E6N:-O4vE4zy3QrFGDBj6E6O:b-7p8wne) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L901)):*
> ```Go
> 				r.id, r.electionTimeout,
> 			)
> 			r.electionElapsed = r.electionTimeout - 1 // -1 because we'll add one below.
> ```

We're also going to set `r.electionElapsed` to 0 down below if we decide to call an election. Doesn't that mean that we'll repeatedly hit thing branch on each tick and call elections every `[0, electiontimeout)` ticks?

When we had discussed this over a call, I think we had included a `deFortify` call in here to avoid that. I'm curious what you think of that. In theory, it seems like it's safe to defortify whenever `supportingFortifiedLeader` returns false.
___
*[`pkg/raft/raft.go` line 1040 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vFUsk4PrRoQZIOsoJ:-O4vFUsk4PrRoQZIOsoK:b7lszl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L1040)):*
> ```Go
> 		return
> 	}
> 	if r.supportingFortifiedLeader() && t != campaignTransfer {
> ```

Do we need the `t != campaignTransfer` condition anymore, now that we have the concept of defortification? Can the corresponding `MsgTimeoutNow` be in charge of defortification? That will ensure that a MsgTimeoutNow from an old leader at an earlier term does not accidentally grant a follower permission to subvert the leader at a newer term.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 901 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vE4zy3QrFGDBj6E6N:-O4zni2l4B_H2V2XkrEF:b-m8t5sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L901)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're also going to set `r.electionElapsed` to 0 down below if we decide to call an election. Doesn't that mean that we'll repeatedly hit thing branch on each tick and call elections every `[0, electiontimeout)` ticks?

When we had discussed this over a call, I think we had included a `deFortify` call in here to avoid that. I'm curious what you think of that. In theory, it seems like it's safe to defortify whenever `supportingFortifiedLeader` returns false.
</blockquote></details>

The `leadEpoch` gets set to 0 whenever we campaign. For normal elections, we call `reset`. For pre-vote elections, we handle this in `becomePreCandidate`.

But you raise a good point -- maybe we should be calling `deFortify` to make this more explicit. Thoughts on whether we should do this in `tickElection` or `campaign`? I'm leaning towards the latter. 

(Note to self) We'll also need to expand the assertion in `deFortify` to let a follower de-fortify if it no longer supports a fortified leader.
___
*[`pkg/raft/raft.go` line 1040 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vFUsk4PrRoQZIOsoJ:-O4ziQ5xAVKuNndOq-Zf:bma6r0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L1040)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need the `t != campaignTransfer` condition anymore, now that we have the concept of defortification? Can the corresponding `MsgTimeoutNow` be in charge of defortification? That will ensure that a MsgTimeoutNow from an old leader at an earlier term does not accidentally grant a follower permission to subvert the leader at a newer term.
</blockquote></details>

We don't. Removed. 

Note that we can't call `deFortify` from `MsgTimeoutNow` just yet because of this TODO:

https://github.com/cockroachdb/cockroach/blob/b1359ae64de710bcd928f5e0fef91a59a8f4a309/pkg/raft/raft.go#L1809-L1817

**Comment by arulajmani** [comment]
> I might want to add a pre-vote variant of the datadriven tests here as well. It shouldn't make much material difference, but it's good to have. I'll bundle it with review comments/a rebase once the other PR lands.

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-:-O5-gi9i8T-O09d0Hd_M:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 901 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vE4zy3QrFGDBj6E6N:-O5-ZRxg8Oq-kpkZrx7z:b-jojei1) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L901)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The `leadEpoch` gets set to 0 whenever we campaign. For normal elections, we call `reset`. For pre-vote elections, we handle this in `becomePreCandidate`.

But you raise a good point -- maybe we should be calling `deFortify` to make this more explicit. Thoughts on whether we should do this in `tickElection` or `campaign`? I'm leaning towards the latter. 

(Note to self) We'll also need to expand the assertion in `deFortify` to let a follower de-fortify if it no longer supports a fortified leader.
</blockquote></details>

Ah ok, thanks for explaining. Resetting `leadEpoch` to 0 in `reset` feels a bit implicit. If we do that, we probably want an assertion in there demonstrating that it's safe to do. But that assertion might be difficult to make.

An alternative is to call `deFortify` right after `!r.supportingFortifiedLeader()` here and elsewhere where we know defortification is safe, and then assert that `leadEpoch == 0` in `reset`. If we do that, I suggest that we do it in `tickElection` so that it's right next to the `!r.supportingFortifiedLeader()` call.

Or we could push the `leadEpoch = 0` into `r.supportingFortifiedLeader()`, so that there's never a case where the method returns false but `leadEpoch` is not reset.

----

We can either do this in this PR or a separate PR. Up to you.
___
*[`pkg/raft/raft.go` line 898 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5-gKjD4Gb63E6ZP6vX:-O5-gKjD4Gb63E6ZP6vY:b-gl05d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/24551a6b6349bc6b23bd161ee932e546b25703e1/pkg/raft/raft.go#L898)):*
> ```Go
> 			// at r.electionTimeout. Also see pastElectionTimeout.
> 			r.logger.Debugf(
> 				"%d setting election elapsed to start from: %d after store liveness support expired",
> ```

nit: I found "from: %d" to be a little unclear when reading the logic tests. Consider "from %d ticks".

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 901 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O4vE4zy3QrFGDBj6E6N:-O5EoHzsE8uZfGf79U9w:b-me85zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/befddc278fc211fe0213de6946bf00864c9f0c1f/pkg/raft/raft.go#L901)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ah ok, thanks for explaining. Resetting `leadEpoch` to 0 in `reset` feels a bit implicit. If we do that, we probably want an assertion in there demonstrating that it's safe to do. But that assertion might be difficult to make.

An alternative is to call `deFortify` right after `!r.supportingFortifiedLeader()` here and elsewhere where we know defortification is safe, and then assert that `leadEpoch == 0` in `reset`. If we do that, I suggest that we do it in `tickElection` so that it's right next to the `!r.supportingFortifiedLeader()` call.

Or we could push the `leadEpoch = 0` into `r.supportingFortifiedLeader()`, so that there's never a case where the method returns false but `leadEpoch` is not reset.

----

We can either do this in this PR or a separate PR. Up to you.
</blockquote></details>

We discussed this offline and decided to make the assertion change to `leadEpoch == 0` in reset in a followup PR. 

@nvanbenschoten I did add an explicit call to `deFortify` in `tickElection` as we seemed aligned on that.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-:-O5F8k_hCX8xpg24p1yk:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 898 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5-gKjD4Gb63E6ZP6vX:-O5F8WSV3EVupHKuSKo4:bssks93) ([raw file](https://github.com/cockroachdb/cockroach/blob/24551a6b6349bc6b23bd161ee932e546b25703e1/pkg/raft/raft.go#L898)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I found "from: %d" to be a little unclear when reading the logic tests. Consider "from %d ticks".
</blockquote></details>

Doesn't look like the "ticks" part made it into the log message.
___
*[`pkg/raft/raft.go` line 889 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5F8vLUAElRpcvAxtG2:-O5F8vLUAElRpcvAxtG3:b-ku06xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/356fc2ca58b3ed075510896a8b83d936f01f90dd/pkg/raft/raft.go#L889)):*
> ```Go
> 		}
> 		// We're no longer supporting the fortified leader. Let's make this
> 		// de-fortification explicit.
> ```

Could we mention how this will mean that we won't hit the same `r.leadEpoch != 0` path again on the next tick unless the term changes or we get refortified by the leader?
___
*[`pkg/raft/raft.go` line 975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5F8lTK3TYGR1m8_niN:-O5F8lTK3TYGR1m8_niO:b416pfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/356fc2ca58b3ed075510896a8b83d936f01f90dd/pkg/raft/raft.go#L975)):*
> ```Go
> 
> func (r *raft) becomePreCandidate() {
> 	assertTrue(!r.supportingFortifiedLeader(),
> ```

nit: pull this assertion below the `r.state` assertion to more closely mirror the logic in `becomeLeader`.

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-:-O5FU64e2OVZyWCrEyQW:b-l0r5kv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 898 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5-gKjD4Gb63E6ZP6vX:-O5FThWv8ddXDb4w74F0:b59bew8) ([raw file](https://github.com/cockroachdb/cockroach/blob/24551a6b6349bc6b23bd161ee932e546b25703e1/pkg/raft/raft.go#L898)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't look like the "ticks" part made it into the log message.
</blockquote></details>

Mb, fixed.
___
*[`pkg/raft/raft.go` line 889 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129158#-O5F8vLUAElRpcvAxtG2:-O5FTVuTEfiP3a0P7oiL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/356fc2ca58b3ed075510896a8b83d936f01f90dd/pkg/raft/raft.go#L889)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we mention how this will mean that we won't hit the same `r.leadEpoch != 0` path again on the next tick unless the term changes or we get refortified by the leader?
</blockquote></details>

Done.

**Pull request merged**
