### PR TITLE
opt: add a small cost for all operators with unbounded cardinality

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the coster so that a small cost is added for any
operator with unbounded cardinality. This ensures we prefer plans that
push limits as far down the tree as possible, all else being equal.

Release note (performance improvement): Updated the optimizer cost
model so that all else being equal, the optimizer prefers plans in which
LIMIT operators are pushed as far down the tree as possible. This can
reduce the number of rows that need to be processed by higher operators
in the plan tree, thus improving performance.

Release justification: low risk, high benefit change to existing
functionality

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[pkg/sql/opt/xform/coster.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiX0ex_AmMKzdhSvniJ:-MiX0ex_AmMKzdhSvniK:b-hjmb7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b58d359cd13bba4f46ee8f4245703e13c32225/pkg/sql/opt/xform/coster.go#L532)):*
> ```
> any operator with unbounded cardinality
> ```
Out of curiosity, why not apply to only computeLimitCost to reduce the scope of this change?
___
*[pkg/sql/opt/xform/testdata/coster/limit, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiWzUIV3fj7DtDl2Jkr:-MiWzUIV3fj7DtDl2Jks:b-hlql3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae3e492583110b50deb5fb641cfa0e977418f63/pkg/sql/opt/xform/testdata/coster/limit#L13)):*
> ```
> 
> # Ensure that the extra cost for unbounded cardinality operators causes the
> # limit to be pushed below the index join.
> ```

drive-by nit: add context about the limit exceeding the number of rows in stats.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 42 of 42 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-:-MiX2b5c76p2Ge3SowmA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-:-MiXIPM_4dLz136gPAq_:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/opt/xform/testdata/external/tpce, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiXHnyHBOEZ3iUbLG_R:-MiXHnyHBOEZ3iUbLG_S:b-l6v3gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b58d359cd13bba4f46ee8f4245703e13c32225/pkg/sql/opt/xform/testdata/external/tpce#L1041)):*
> ```
>  │    │    │    │    │    │    ├── key: (35)
>  │    │    │    │    │    │    ├── fd: ()-->(83)
>  │    │    │    │    │    │    ├── inner-join (lookup security@secondary)
> ```

Interesting - we swapped the two lookup joins because now the bottom one has a cardinality bound.

**Review by rytaft — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-:-MiXUnU58TljtxcaCCEM:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @mgartner, and @rharding6373)

___
*[pkg/sql/opt/xform/coster.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiX0ex_AmMKzdhSvniJ:-MiXPYFsAcP-O0Fgy8OR:b-uwfm5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b58d359cd13bba4f46ee8f4245703e13c32225/pkg/sql/opt/xform/coster.go#L532)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

> ```
> any operator with unbounded cardinality
> ```
Out of curiosity, why not apply to only computeLimitCost to reduce the scope of this change?
</blockquote></details>

We chatted about this offline, but just to close the loop: limit always has bounded cardinality (at least when the limit is constant), so adding the cost there wouldn't change the plan. What matters is how the limit affects the cardinality of the operators around it in the tree.
___
*[pkg/sql/opt/xform/testdata/coster/limit, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiWzUIV3fj7DtDl2Jkr:-MiXUZfK5CBGEGC-1_-B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ae3e492583110b50deb5fb641cfa0e977418f63/pkg/sql/opt/xform/testdata/coster/limit#L13)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

drive-by nit: add context about the limit exceeding the number of rows in stats.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/external/tpce, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-MiXHnyHBOEZ3iUbLG_R:-MiXQ0TLDtKucgZuyf1V:bb7s9kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4b58d359cd13bba4f46ee8f4245703e13c32225/pkg/sql/opt/xform/testdata/external/tpce#L1041)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Interesting - we swapped the two lookup joins because now the bottom one has a cardinality bound.
</blockquote></details>

yea!

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69688#-:-MiY-jT516v4U5BCSHtX:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @mgartner, and @rharding6373)

**Pull request merged**
