### PR TITLE
*: use bootstrap.BootstrappedSystemIDChecker in tests

### PR DESCRIPTION
**Pull request by postamar**
Instead of relying on hard-coded constants, tests now rely on the
bootstrapped system schema to determine which IDs belong to system
tables or not.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
This is fine. I sort of think it might be better to plumb in an object as we might eventually make it so that we bootstrap testclusters with a store dir from an old version or from a different upgrade path, but for now this is good.

**Comment by postamar** [comment]
Sorry for the CI noise. I'm getting there. I followed up on this PR by removing the `keys.SystemIDChecker` interface altogether. There were a few use-cases outside of tests, especially in backupccl/importccl but I was able to work around all of them.

**Review by ajwerner — COMMENTED** [review]
:lgtm: other than the restore questions

> Reviewed 20 of 52 files at r1, 7 of 9 files at r2, 28 of 28 files at r3, 37 of 41 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-:-MuNd0JH27XMJZD-0Vre:b-facdpw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @srosenberg)

___
*[pkg/ccl/backupccl/restore_job.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_4Fy0laaHuqPkQtU:-MuN_4Fz8ZebLTLP0mYX:b6wb36i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecb90553ffa45db05e4211643de7c89ed194632/pkg/ccl/backupccl/restore_job.go#L121)):*
> ```Go
> 	ctx, span := tracing.ChildSpan(ctx, "WriteDescriptors")
> 	defer span.Finish()
> 	defer func() {
> ```

did anything change here other than de-denting and decorating the error? I didn't spot anything
___
*[pkg/ccl/backupccl/restore_job.go, line 756 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNaQkx0nDRJB0V2lRn:-MuNaQkx0nDRJB0V2lRo:b-s03jte) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L756)):*
> ```Go
> 	for id := range details.DescriptorRewrites {
> 		if id > tempSystemDBID {
> 			tempSystemDBID = id
> ```

I wish that I understood this logic. It's going to set the tempSystemDBID to the max value of the rewrite sources? What is that? 

It seems to me like this maybe just works because we assume the database is empty and so we never end up in this loop? I'm stumped by this code. @dt do you have any ideas? This was added in https://github.com/cockroachdb/cockroach/pull/55685. 

I'm not blocking this PR on retaining this logic, but I do want to understand what's going on here. 
___
*[pkg/ccl/backupccl/restore_job.go, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_UGL-syVtwKBJqDM:-MuN_UGL-syVtwKBJqDN:b6pigl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecb90553ffa45db05e4211643de7c89ed194632/pkg/ccl/backupccl/restore_job.go#L881)):*
> ```Go
> 	var tempSystemDBID descpb.ID
> 	if details.DescriptorCoverage == tree.AllDescriptors {
> 		for id := range details.DescriptorRewrites {
> ```

does this have a gnarly edge case if there are no rewrites? In particular, imagine restoring an empty full cluster backup. 
___
*[pkg/ccl/backupccl/restore_job.go, line 2490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_rbJEP_XLnjKvGcn:-MuN_rbJEP_XLnjKvGco:b-mg28df) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L2490)):*
> ```Go
> 		if table.GetParentID() != tempSystemDBID {
> 			continue
> 		}
> ```

Does this definitely do nothing? Seems like this could very easily be meaningful. 



_Code quote:_
```Go
		if table.GetParentID() != tempSystemDBID {
			continue
		}
```
___
*[pkg/keys/system.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNHKTl-lagfkDhBZDA:-MuNHKTl-lagfkDhBZDB:biemgd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f00edaed98cefc4853e4eda45eaaf8f5e1e44c3/pkg/keys/system.go#L44)):*
> ```Go
> // MinUserDescriptorID returns the smallest possible non-system descriptor ID
> // after a cluster is bootstrapped.
> func MinUserDescriptorID(idChecker SystemIDChecker) uint32 {
> ```

Note to self: come back and caveat and/or remove this function



_Code quote:_
```Go
// MinUserDescriptorID returns the smallest possible non-system descriptor ID
// after a cluster is bootstrapped.
func MinUserDescriptorID(idChecker SystemIDChecker) uint32 {
```
___
*[pkg/sql/catalog/bootstrap/metadata.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNHYzQ6Prryes3keea:-MuNHYzQ6Prryes3keeb:b4v4fug) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f00edaed98cefc4853e4eda45eaaf8f5e1e44c3/pkg/sql/catalog/bootstrap/metadata.go#L409)):*
> ```Go
> // from the minimum value allowed in a simple unit test setting.
> func TestingUserDescID(offset uint32) uint32 {
> 	return keys.MinUserDescriptorID(BootstrappedSystemIDChecker()) + offset
> ```

in practice doesn't this end up being dumb because of the `defaultdb` and `postgres` databases? We should just bootstrap those too and get rid of the forever migration. I hate that thing. Leave it to me for a subsequent PR. Just mentioning that this isn't really right and might work by happenstance in the few use cases.

**Review by postamar — COMMENTED** [review]
Thanks for the review. I provided some answers and added some comments in the code that should satisfy you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-:-MuO4C2wBZIex-jZ8fH_:b-foehob)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @srosenberg)

___
*[pkg/ccl/backupccl/restore_job.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_4Fy0laaHuqPkQtU:-MuNz6QWDAQRINfaL3Nt:b-w7q3pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecb90553ffa45db05e4211643de7c89ed194632/pkg/ccl/backupccl/restore_job.go#L121)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

did anything change here other than de-denting and decorating the error? I didn't spot anything
</blockquote></details>

Nothing of substance changed here. The error decoration was, in fact, already there. I removed the closure because it was useless and annoying. I meant to put that in a separate commit and forgot, sorry.
___
*[pkg/ccl/backupccl/restore_job.go, line 756 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNaQkx0nDRJB0V2lRn:-MuNzeUs6f5OQd2NQubh:b-af70q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L756)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wish that I understood this logic. It's going to set the tempSystemDBID to the max value of the rewrite sources? What is that? 

It seems to me like this maybe just works because we assume the database is empty and so we never end up in this loop? I'm stumped by this code. @dt do you have any ideas? This was added in https://github.com/cockroachdb/cockroach/pull/55685. 

I'm not blocking this PR on retaining this logic, but I do want to understand what's going on here. 
</blockquote></details>

Note: for some reason reviewable is placing this comment nowhere near the code it's quoting, which pertains to the computation of `tempSystemDBID` when executing the restore.

It took me a while to figure out too. The restore planner pre-allocates enough descriptor IDs for each of the descriptors in the backup, plus one extra for the temporary system database in the case where it's planning full cluster restore. Thus, the temporary system database descriptor ID is the last in this pre-allocated range, which is encoded in the keys of `DescriptorRewrites`.

This also explains how we "know" that `DescriptorRewrites` isn't empty: it never is in the case of a full cluster restore, because we always at least restore the system database.

I mean, really, this ID should be stored in a separate field in the restore job details, instead of inferring it like this. I'll add a comment explaining this.
___
*[pkg/ccl/backupccl/restore_job.go, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_UGL-syVtwKBJqDM:-MuO3Dcz7kSbdAkBePJL:b-lgkfi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ecb90553ffa45db05e4211643de7c89ed194632/pkg/ccl/backupccl/restore_job.go#L881)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does this have a gnarly edge case if there are no rewrites? In particular, imagine restoring an empty full cluster backup. 
</blockquote></details>

As explained above, the `if` above ensures that there is at least one rewrite, that of the temp system db desc.
___
*[pkg/ccl/backupccl/restore_job.go, line 2490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_rbJEP_XLnjKvGcn:-MuO3n-L9iIRPKQCB_R_:bhzkbu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L2490)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this definitely do nothing? Seems like this could very easily be meaningful. 
</blockquote></details>

I'm not finding this in my current revision, and the comment seems out of place in reviewable. Is this comment stale?
___
*[pkg/keys/system.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNHKTl-lagfkDhBZDA:-MuO44sq38SFgKFyLpdv:b60q92x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f00edaed98cefc4853e4eda45eaaf8f5e1e44c3/pkg/keys/system.go#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Note to self: come back and caveat and/or remove this function
</blockquote></details>

This has since been removed.
___
*[pkg/sql/catalog/bootstrap/metadata.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNHYzQ6Prryes3keea:-MuO48Id9MlXRynvWMKe:bly0624) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f00edaed98cefc4853e4eda45eaaf8f5e1e44c3/pkg/sql/catalog/bootstrap/metadata.go#L409)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

in practice doesn't this end up being dumb because of the `defaultdb` and `postgres` databases? We should just bootstrap those too and get rid of the forever migration. I hate that thing. Leave it to me for a subsequent PR. Just mentioning that this isn't really right and might work by happenstance in the few use cases. 
</blockquote></details>

I certainly have no objection!

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-:-MuOOiMn5IJKWGtWrECU:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @postamar, and @srosenberg)

___
*[pkg/ccl/backupccl/restore_job.go, line 2490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_rbJEP_XLnjKvGcn:-MuOOJb_6BqrnXo3HD8M:b-xvdivf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L2490)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm not finding this in my current revision, and the comment seems out of place in reviewable. Is this comment stale?
</blockquote></details>

Well that's exactly it, you removed this logic, but it's not clear that this logic was doing nothing. It was checking whether the table had its parentID set to the tempSystemDBID. It seem possible that there was a code path that called this with tables in the slice that had some other parent set and thus should be skipped. 
___
*[pkg/keys/system.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuNHKTl-lagfkDhBZDA:-MuOOfe22HKGE8guXk_n:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f00edaed98cefc4853e4eda45eaaf8f5e1e44c3/pkg/keys/system.go#L44)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This has since been removed.
</blockquote></details>

:100:

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75464)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @srosenberg)

___
*[pkg/ccl/backupccl/restore_job.go, line 2490 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75464#-MuN_rbJEP_XLnjKvGcn:-MuOPwEY3gz031QiBZJA:b-tw881b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e932c325bc6b255d104552bba0e10de2e696920/pkg/ccl/backupccl/restore_job.go#L2490)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Well that's exactly it, you removed this logic, but it's not clear that this logic was doing nothing. It was checking whether the table had its parentID set to the tempSystemDBID. It seem possible that there was a code path that called this with tables in the slice that had some other parent set and thus should be skipped. 
</blockquote></details>

I misunderstood, sorry. I'll put it back. Chesterton's fence and all that.



_Code quote:_
```Go
		if table.GetParentID() != tempSystemDBID {
			continue
		}
```

**Pull request merged**
