### PR TITLE
sql/physicalplan: make more tests compatible with secondary tenants 

### PR DESCRIPTION
**Pull request by knz**
Informs #76378.
Links to #108763.
Epic: CRDB-18499

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
The general changes and the ones from sql_stats: :lgtm: 
I will leave the kv, multiregion and plans changes to be reviewed by their respective teams

> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108764#-:-NbtIK_D8wuwwctbj2pb:b-x2q8kj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108764#-:-Nbtz9go2Cv8YlWQCb8S:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @knz, and @rachitgsrivastava)

___
*[`pkg/server/testserver.go` line 1689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108764#-NbtxoNtCF77M2cU_vBl:-NbtxoNtCF77M2cU_vBm:b-zblnf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e77588484fb276492182ac2d116b0f404fa8cd/pkg/server/testserver.go#L1689)):*
> ```Go
> }
> 
> // LocalityRef is part of the serverutils.StorageLayerInterface.
> ```

nit: do we still need this method? I don't see any renaming in the first commit, so it looks like it's actually no longer used. Also, it's now removed from the storage layer interface.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108764)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DarrylWong, @maryliag, @rachitgsrivastava, and @yuzefovich)

___
*[`pkg/server/testserver.go` line 1689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108764#-NbtxoNtCF77M2cU_vBl:-Nbu36995O4ZsKbuVZkV:bzahyws) ([raw file](https://github.com/cockroachdb/cockroach/blob/40e77588484fb276492182ac2d116b0f404fa8cd/pkg/server/testserver.go#L1689)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do we still need this method? I don't see any renaming in the first commit, so it looks like it's actually no longer used. Also, it's now removed from the storage layer interface.
</blockquote></details>

Good call. Removed.

**Comment by knz** [comment]
TFYRs

bors r=maryliag,yuzefovich

**Pull request merged**
