### PR TITLE
sql: user account expiration (role LOGIN option and password expiry via VALID UNTIL option)

### LINKED ISSUE #41396: pgwire,sql: user account expiration
Requested by large customer account:

- disable a user (but not delete) temporarily
- disable a user at a specific date
- disable a user "some time after" the last log-in

The first two points are equivalent, the last is separate.

### PR DESCRIPTION
**Pull request by RichardJCai**
Fixes #41396

Release note (sql change): Added LOGIN option to enable login for roles/users.
When using CREATE USER syntax, LOGIN is enabled by default whereas when using CREATE ROLE,
LOGIN is not enabled by default.

Release note (sql change): Added VALID UNTIL option to indicate passwords are only valid until a given timestamp.
VALID UNTIL only affects PASSWORDS - if passwords are disabled, VALID UNTIL has no effect.
(Can login even with expired password if passwords are not required to login - same as PG)

Release note (sql change): SHOW USERS now shows all roles/users that have LOGIN enabled.

Release note (security update): User and role principals can now be prevented from logging in
using the NOLOGIN attribute which can be set using ALTER USER/ROLE.

Release note (security update): The password field (used exclusively for password-based authentication)
can now be configured to have an expiry date using the VALID UNTIL attribute, which can be set with ALTER USER/ROLE.
Note that the attribute sets an expiry date for the password, not the user account.
This is consistent with PostgreSQL.

Release note (security update): Any role created prior to 20.1 will be able to log in into
clusters started with --insecure, unless/until they are granted the NOLOGIN privilege.
For secure clusters, roles cannot log in by virtue of not having a password nor a client certificate.

### CODE REVIEW

**Comment by otan** [comment]
you can probably take our sql-execution from reviewers :)

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, and @rohany)

___
*[pkg/sql/drop_role.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1h3jKt9i2QiHLLwmbh:-M1h3jKt9i2QiHLLwmbi:bbzq1lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0b2a87aa75eefce3773e917d106ebac0228847b/pkg/sql/drop_role.go#L232)):*
> ```Go
> 	if numRoleOptionsDeleted > 0 {
> 		// Some role options have been deleted, bump role_options table version to
> 		// force a refresh of role membership.
> ```

Realized you don't need to force a refresh of the role options table - it contains the source of truth every time it is queried.

**Review by knz — COMMENTED** [review]
Thanks for letting me review this.
Overall I like the approach taken here.

There is just one high level comment that I think is very important. I do not believe there is wisdom in having separate LOGIN and NOLOGIN rows in the `role_options` table. I believe your PR would be better if you were to maintain the equivalence "a user has LOGIN option if and only if the NOLOGIN option is not present in `role_options`".

In other words _absence_ of NOLOGIN in role_options gives LOGIN privilege.
It immediately follows that all users created pre-20.1 or in mixed-version clusters properly get LOGIN privilege by default. It also simplifies your code.

Separately, I have approached you with the question of why SHOW ROLES is starting to show non-role users. You told me "product decision". Overall I do not disagree with the product decision but it is a very separate change that is fully orthogonal to your work here. Therefore, it belongs to a different PR.

I have modified your ShowRoles delegate SQL query to preserve the previous behavior, see comment below. If you want to do the "product decision" PR, please issue that PR separately (after this one merges).

There's also a point about performance that's somewhat important, see below, but it shouldn't be a big issue.

Again it's nice work overall.

Finally regarding the release note: your text is fine but it should be split in different release notes. Also, there's a security update. Try this:

```
Release note (sql change): Added LOGIN option to enable login for roles/users.
When using CREATE USER syntax, LOGIN is enabled by default whereas when using CREATE ROLE,
LOGIN is not enabled by default.

Release note (sql change): Added VALID UNTIL option to indicate passwords are only valid until a given timestamp.
VALID UNTIL only affects PASSWORDS - if passwords are disabled, VALID UNTIL has no effect.
(Can login even with expired password if passwords are not required to login - same as PG)

Release note (sql change): SHOW USERS now shows all roles/users that have LOGIN enabled.

Release note (security update): User and role principals can now be prevented from logging in using the NOLOGIN attribute which can be set using ALTER USER/ROLE. 

Release note (security update): The password field (used exclusively for password-based authentication) can now be configured to have an expiry date using the VALID UNTIL attribute, which can be set with ALTER USER/ROLE. Note that the attribute sets an expiry date for the password, not the user account. This is consistent with PostgreSQL.)
```

(I am removing "SHOW ROLES shows every role/user (now that roles=users)." - this can be added as a release note to your separate PR)

> Reviewed 19 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-:-M1kkFkg-6tf8ZJ_hnsI:bemj0zu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @otan, @RichardJCai, and @rohany)

___
*[pkg/clusterversion/cockroach_versions.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kgX3U-06_DD8oZsk2:-M1kgX3U-06_DD8oZsk3:bchduyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/clusterversion/cockroach_versions.go#L430)):*
> ```Go
> 		Version: roachpb.Version{Major: 19, Minor: 2, Unstable: 14},
> 	},
> ```

you can revert the changes in this file. No need to touch files when there's no change.
___
*[pkg/server/authentication_test.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kh-Gi97MiNw1Jo5sL:-M1kh-Gj2OCrEq3VQGyI:biuwcxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/server/authentication_test.go#L200)):*
> ```Go
> 
> 		{"richardc", "12345", "NOLOGIN", ""},
> 		{"epoch", "12345", "", "VALID UNTIL '1970-01-01'"},
> ```

can you add dates before the epoch too? thanks
___
*[pkg/sql/alter_role.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khCLZ4_7eFbp1pg3G:-M1khCLZ4_7eFbp1pg3H:b3xksfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/alter_role.go#L173)):*
> ```Go
> 	}
> 
> 	stmts, err := n.roleOptions.GetSQLStmts()
> ```

Please add a comment that explains what this does.
___
*[pkg/sql/alter_role.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khF3w7zgo6mm772nr:-M1khF3w7zgo6mm772ns:by1itmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/alter_role.go#L181)):*
> ```Go
> 		qargs := []interface{}{normalizedUsername}
> 
> 		if value != nil {
> ```

Explain in a comment why this is important.
___
*[pkg/sql/create_role.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khY1fALAr_p7jLZaB:-M1khY1fALAr_p7jLZaC:blk8z9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L71)):*
> ```Go
> 
> 	// Using CREATE USER syntax enables LOGIN by default.
> 	if !isRole && !roleOptions.Contains(roleoption.LOGIN) &&
> ```

Why did you include `!roleOptions.Contains(roleoptions.LOGIN)` in the condition? (not saying that it's wrong -  I don't understand it yet)
___
*[pkg/sql/create_role.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khelt4oEC4WGGxcZI:-M1khelt4oEC4WGGxcZJ:b-x2bzfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L185)):*
> ```Go
> 		qargs := []interface{}{normalizedUsername}
> 
> 		if value != nil {
> ```

please add a comment here too.
___
*[pkg/sql/drop_role.go, line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khrfACN6mqUYM_akp:-M1khrfACN6mqUYM_akq:bzgskfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/drop_role.go#L211)):*
> ```Go
> 			fmt.Sprintf(
> 				`DELETE FROM %s WHERE username=$1`,
> 				RoleOptionsTableName,
> ```

I think you need `tree.NameString` here.
___
*[pkg/sql/user.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1ki3w9EaIyzDui5PIS:-M1ki3w9EaIyzDui5PIT:bppwmzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/user.go#L73)):*
> ```Go
> 		}
> 		// Root user cannot have password expiry and must have login.
> 		validUntilFn := func(ctx context.Context) (*tree.DTimestampTZ, error) {
> ```

You've already added checks elsewhere that `validUntilFn` is not called if it is `nil`. I think you can simply return `nil` for it here.
___
*[pkg/sql/user.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kia-A4s5BQYhwEo_5:-M1kia-A4s5BQYhwEo_6:bd6mfe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/user.go#L128)):*
> ```Go
> 		}
> 
> 		getNoLoginOption := `SELECT 1 FROM system.role_options ` +
> ```

Performing 3 different queries here is not the right way to go. It's very expensive for no good reason.
What about this: 

```sql
SELECT option, value
  FROM system.role_options
 WHERE username=$1 AND option IN ('LOGIN', 'NOLOGIN', 'VALID UNTIL')
```

Then get the rows with a for loop, and assign the fields depending on each observed value of `option`. Make the timestamp conversion here, not in SQL.
___
*[pkg/sql/delegate/show_users.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kjAOz4rZvhAZ13cup:-M1kjAOz4rZvhAZ13cuq:b-o28lxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/delegate/show_users.go#L18)):*
> ```Go
> // Privileges: SELECT on system.users.
> func (d *delegator) delegateShowUsers(n *tree.ShowUsers) (tree.Statement, error) {
> 	return parse(`SELECT username AS user_name FROM ` +
> ```

This will break in mixed-version clusters where the LOGIN row is not created yet.

Try this:

```sql
SELECT username AS user_name
   FROM system.users u
WHERE NOT EXISTS (
   SELECT 1
     FROM system.role_options
    WHERE username=u.username AND option = 'NOLOGIN'
)
```
___
*[pkg/sqlmigrations/migrations.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kkBNy4jpZflVC9kJr:-M1kkBNy4jpZflVC9kJs:b-krv7n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sqlmigrations/migrations.go#L1101)):*
> ```Go
> 	// Upsert the Login flag to root user.
> 	const upsertRootLogin = `
>           UPSERT INTO system.role_options ("username", "option", "value") VALUES ($1, 'LOGIN', NULL)
> ```

This is not needed. See my comment at top.

**Comment by knz** [comment]
You'll also need to rebase on top of #45193 when it merges, then add additional audit logging to indicate when a login was denied or a password has expired. Then the corresponding auth logging tests.

**Review by jordanlewis — COMMENTED** [review]
Raphael, thank you very much for adding your review! Richard, I think Raphael's suggestion to make a separate PR is good but I don't think it'll block the merge here if you make sure to spell out the release notes a bit better. You can do it if you want, sound ok Raphael?

Overall I think this looks good mod Raphael's comments. I would like to see some SQL logic tests for the new role options, which I think is missing (unless I missed something).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-:-M1knoV43dftDA7rL963:bsv9p87)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @otan, @RichardJCai, and @rohany)

___
*[pkg/sql/create_role.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khY1fALAr_p7jLZaB:-M1kmW9u--C4Ahn1sWc5:b-d1mbhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did you include `!roleOptions.Contains(roleoptions.LOGIN)` in the condition? (not saying that it's wrong -  I don't understand it yet)
</blockquote></details>

I think it's because you can override it if you want - this is the default behavior if there's no LOGIN option specified

**Comment by knz** [comment]
> Richard, I think Raphael's suggestion to make a separate PR is good but I don't think it'll block the merge

At least make a separate commit...

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, @RichardJCai, and @rohany)

___
*[pkg/clusterversion/cockroach_versions.go, line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kgX3U-06_DD8oZsk2:-M1l2KJBE5-AwmC2v9Cy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/clusterversion/cockroach_versions.go#L430)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can revert the changes in this file. No need to touch files when there's no change.
</blockquote></details>

Done.
___
*[pkg/server/authentication_test.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kh-Gi97MiNw1Jo5sL:-M1l2fKn48BcT-dchlXO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/server/authentication_test.go#L200)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you add dates before the epoch too? thanks
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khCLZ4_7eFbp1pg3G:-M1l4TER8jLeb44IDWbb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/alter_role.go#L173)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add a comment that explains what this does.
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khF3w7zgo6mm772nr:-M1l4To7-kk9_AcNw8Qk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/alter_role.go#L181)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Explain in a comment why this is important.
</blockquote></details>

Done.
___
*[pkg/sql/create_role.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khY1fALAr_p7jLZaB:-M1l38kH3_I-V0EB9nmn:b-nered4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L71)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it's because you can override it if you want - this is the default behavior if there's no LOGIN option specified
</blockquote></details>

Yeah, Jordan is right. When no LOGIN option is specified for the CREATE USER syntax, LOGIN should be included by default - however we don't want to add it if it's already there.
___
*[pkg/sql/create_role.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khelt4oEC4WGGxcZI:-M1l52fl0ic0V__OQZag:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L185)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add a comment here too.
</blockquote></details>

Done.
___
*[pkg/sql/user.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1ki3w9EaIyzDui5PIS:-M1l5MtW7aKHy572Ekiu:b-prr07t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/user.go#L73)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You've already added checks elsewhere that `validUntilFn` is not called if it is `nil`. I think you can simply return `nil` for it here.
</blockquote></details>

In the verifyPassword function, it calls validUntilFn without validating if it's null.

For the sake of consistency with the passwordRetrievalFn behavior here, I'll leave it as a function that returns nil for now - unless you have strong opinions about changing this.


L
```	
func (s *authenticationServer) verifyPassword(
	ctx context.Context, username string, password string,
) (valid bool, expired bool, err error) {
	exists, canLogin, pwRetrieveFn, validUntilFn, err := sql.GetUserHashedPassword(
		ctx, s.server.execCfg.InternalExecutor, username,
	)
	if err != nil {
		return false, false, err
	}
	if !exists || !canLogin {
		return false, false, nil
	}
	hashedPassword, err := pwRetrieveFn(ctx)
	if err != nil {
		return false, false, err
	}

	validUntil, err := validUntilFn(ctx)
	if err != nil {
		return false, false, err
	}
	if validUntil != nil {
		if validUntil.Time.Sub(timeutil.Now()) < 0 {
			return false, true, nil
		}
	}

	return security.CompareHashAndPassword(hashedPassword, password) == nil, false, nil
}
```
___
*[pkg/sql/user.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kia-A4s5BQYhwEo_5:-M1lE-SDEWcjpWaJtuk7:bo7sddm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/user.go#L128)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Performing 3 different queries here is not the right way to go. It's very expensive for no good reason.
What about this: 

```sql
SELECT option, value
  FROM system.role_options
 WHERE username=$1 AND option IN ('LOGIN', 'NOLOGIN', 'VALID UNTIL')
```

Then get the rows with a for loop, and assign the fields depending on each observed value of `option`. Make the timestamp conversion here, not in SQL.
</blockquote></details>

Changed it to use one query.
___
*[pkg/sql/delegate/show_users.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kjAOz4rZvhAZ13cup:-M1llRJaCjdjlJvN46Is:b6b1lwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/delegate/show_users.go#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This will break in mixed-version clusters where the LOGIN row is not created yet.

Try this:

```sql
SELECT username AS user_name
   FROM system.users u
WHERE NOT EXISTS (
   SELECT 1
     FROM system.role_options
    WHERE username=u.username AND option = 'NOLOGIN'
)
```
</blockquote></details>

This doesn't exactly handle the case of ROLES created before 20.1 can't login.
Will make separate PR to fix this to simplify this PR.
___
*[pkg/sqlmigrations/migrations.go, line 1101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kkBNy4jpZflVC9kJr:-M1lebhMEy740RYCjskc:bybc9lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sqlmigrations/migrations.go#L1101)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is not needed. See my comment at top.
</blockquote></details>


Removed.

**Review by knz — COMMENTED** [review]
Nice tests!

I am almost good with this. As we've discussed before Iam still not convinced of the wisdom of _storing_ NOLOGIN. I think the PR would be better without, with no loss in generality.
Let's make one little more iteration.

> Reviewed 2 of 24 files at r1, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-:-M1m4r2a5IfKuDMvpwqa:b5thoq9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, @RichardJCai, and @rohany)

___
*[pkg/sql/create_role.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khY1fALAr_p7jLZaB:-M1m2PvQ0tFAbRIkiNYA:bxygowo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L71)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah, Jordan is right. When no LOGIN option is specified for the CREATE USER syntax, LOGIN should be included by default - however we don't want to add it if it's already there.
</blockquote></details>

if by chance you agree that the LOGIN privilege does not need to be spelled out in role_options, this can be simplified.
___
*[pkg/sql/user.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1ki3w9EaIyzDui5PIS:-M1m2b976pkHy7GfN0cB:bcukgpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/user.go#L73)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

In the verifyPassword function, it calls validUntilFn without validating if it's null.

For the sake of consistency with the passwordRetrievalFn behavior here, I'll leave it as a function that returns nil for now - unless you have strong opinions about changing this.


L
```	
func (s *authenticationServer) verifyPassword(
	ctx context.Context, username string, password string,
) (valid bool, expired bool, err error) {
	exists, canLogin, pwRetrieveFn, validUntilFn, err := sql.GetUserHashedPassword(
		ctx, s.server.execCfg.InternalExecutor, username,
	)
	if err != nil {
		return false, false, err
	}
	if !exists || !canLogin {
		return false, false, nil
	}
	hashedPassword, err := pwRetrieveFn(ctx)
	if err != nil {
		return false, false, err
	}

	validUntil, err := validUntilFn(ctx)
	if err != nil {
		return false, false, err
	}
	if validUntil != nil {
		if validUntil.Time.Sub(timeutil.Now()) < 0 {
			return false, true, nil
		}
	}

	return security.CompareHashAndPassword(hashedPassword, password) == nil, false, nil
}
```
</blockquote></details>

oh sorry I had misread that other code. You're good.
___
*[pkg/sql/user.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m2umU6d6a2N51CzIZ:-M1m2umU6d6a2N51CzI_:b-ferbzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/user.go#L164)):*
> ```Go
> 					validUntil, err = tree.ParseDTimestamp(timeCtx, ts, time.Microsecond)
> 					if err != nil {
> 						return err
> ```

add an `errors.Wrap` here to explain what the error is about.
___
*[pkg/sql/delegate/show_users.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kjAOz4rZvhAZ13cup:-M1m4PtK1aqTYmgP0Cim:b-dpn2z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/delegate/show_users.go#L18)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

This doesn't exactly handle the case of ROLES created before 20.1 can't login.
Will make separate PR to fix this to simplify this PR.
</blockquote></details>

Discussed offline: this is a separate concern (probably not really a concern actually).
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m4eZp9QnoOdxA4XTt:-M1m4eZp9QnoOdxA4XTu:b-q56hn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/pgwire/testdata/auth/conn_log#L245)):*
> ```
> ERROR: usernologin does not have login privilege
> 
> authlog 5
> ```

change this to 4 to avoid the last message from the previous test
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m4g3b7TYxPEp_B8eQ:-M1m4g3c-iImBvb2VXex:b-rmkjxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/pgwire/testdata/auth/conn_log#L258)):*
> ```
> ERROR: password is expired
> 
> authlog 5
> ```

change this to 6 or 7 to see the connection message

**Review by knz — COMMENTED** [review]
Please pull the final line "Fixes #41396" at the top of the commit message, otherwise it becomes part of the release note.
Or even better: remove it from the commit message and put it at the top of the PR desc. (this is idiomatic)

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-:-M1mCRIrAdA-SXOsfhKu:b-gatv0m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @otan, @RichardJCai, and @rohany)

___
*[pkg/sql/delegate/show_users.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kjAOz4rZvhAZ13cup:-M1mDCGc-yg38FDaalME:beutggl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/delegate/show_users.go#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Discussed offline: this is a separate concern (probably not really a concern actually).
</blockquote></details>

You need to swap this around now.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rohany)

___
*[pkg/sql/create_role.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1khY1fALAr_p7jLZaB:-M1mF4rcB3AHLCFpVWwN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/create_role.go#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

if by chance you agree that the LOGIN privilege does not need to be spelled out in role_options, this can be simplified.
</blockquote></details>

Done.
___
*[pkg/sql/user.go, line 164 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m2umU6d6a2N51CzIZ:-M1mC_kL22kGqHQ-ebHn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/user.go#L164)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add an `errors.Wrap` here to explain what the error is about.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_users.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1kjAOz4rZvhAZ13cup:-M1mFA4fBCDRgUA8alq8:btfb8qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1dd885b222659c3f42030deed1e6064ee4ca71b/pkg/sql/delegate/show_users.go#L18)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to swap this around now.
</blockquote></details>

Will handle SHOW USERS / SHOW ROLES in a different PR.
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 245 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m4eZp9QnoOdxA4XTt:-M1mCangER_7So0Osm2t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/pgwire/testdata/auth/conn_log#L245)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

change this to 4 to avoid the last message from the previous test
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/testdata/auth/conn_log, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-M1m4g3b7TYxPEp_B8eQ:-M1mCbM_8G-dLU7YfIIa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a2cdd5b3ba81ae210b72c38cf160f36a3227855/pkg/sql/pgwire/testdata/auth/conn_log#L258)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

change this to 6 or 7 to see the connection message
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
LGTM and good to go after you pull the "Fixes" in the commit msg at the top.

Well done!

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45541#-:-M1mH6Ah2_k6pzcsGqIi:b-xrqz7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

**Comment by RichardJCai** [comment]
Thanks for the reviews! @jordanlewis @knz

**Pull request merged**
