### PR TITLE
util/log: automatic log redaction

### LINKED ISSUE #46031: cli: support `debug zip --anonymize`
We should provide this switch so that diagnosing of issues is not hindered by manual scrubbing by the user -- which could be prone to mistakes as well.

Few examples:
-  The table/key names (XXXX) in log lines:
```
I200311 07:21:32.053215 826880069 storage/replica_command.go:797 [n8,replicate,s8,r16277/42:/Table/131{-/1/"XXXX…}] change replicas (REMOVE_REPLICA (n5,s5):37): read existing descriptor r16277:/Table/131{-/1/"XXXX^51b23f4c1607fe220acebc023621568f"} [(n4,s4):40, (n8,s8):42, (n5,s5):37, (n11,s11):43, next=44, gen=8]
```
- The same as above in range reports, rangelog.json
- User names used to log into the admin UI

### PR DESCRIPTION
**Pull request by knz**
Fixes #46031 

See "log redaction" RFC from #48076 for details.

General concept:

- logs stored on disk contain markers around data items potentially
  containing PII or confidential data (“unsafe data”).

- `debug zip`, `debug merge-log`, and the `Logs` and `LogFiles` RPCs
  edit the log entries upon request to replace all the unsafe data by
  `‹×›`.

See also the release notes below for a summary of UX.

Example redacted output:

```
I200426 20:06:45.558765 1 cli/start.go:671 ⋮ GEOS initialized at ‹×›
I200426 20:06:45.558772 1 cli/start.go:676 ⋮ starting cockroach node
I200426 20:06:45.562212 75 storage/rocksdb.go:606 ⋮ opening rocksdb instance at ‹×›
I200426 20:06:45.574608 75 server/server.go:750 ⋮ [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I200426 20:06:45.574782 75 storage/rocksdb.go:606 ⋮ opening rocksdb instance at ‹×›
I200426 20:06:45.581451 75 server/config.go:576 ⋮ [n?] ‹×› storage engine‹×› initialized
I200426 20:06:45.581459 75 server/config.go:579 ⋮ [n?] ‹×›
I200426 20:06:45.581466 75 server/config.go:579 ⋮ [n?] ‹×›
I200426 20:06:45.602204 75 server/server.go:1270 ⋮ [n?] **** add additional nodes by specifying --join=‹×›
I200426 20:06:45.602218 75 server/init.go:166 ⋮ [n?] no stores bootstrapped and --join flag specified, awaiting init command or join with an already initialized node.
I200426 20:06:45.602234 75 server/init.go:186 ⋮ [n?] **** cluster ‹×› has been created
I200426 20:06:47.676567 117 gossip/gossip.go:1538 ⋮ [n1] node has connected to cluster via gossip
I200426 20:06:47.676620 117 kv/kvserver/stores.go:255 ⋮ [n1] wrote ‹×› node addresses to persistent storage
I200508 12:34:37.238123 1346 kv/kvserver/replica_consistency.go:255 ⋮ [n1,consistencyChecker,s2,r‹×›] triggering stats recomputation to resolve delta of ‹×›
```

This output was produced from the following raw log:

```
I200426 20:06:45.558765 1 cli/start.go:671 ⋮ GEOS initialized at ‹/data/home/kena/src/go/src/github.com/cockroachdb/cockroach/lib/libgeos_c.so›
I200426 20:06:45.558772 1 cli/start.go:676 ⋮ starting cockroach node
I200426 20:06:45.562212 75 storage/rocksdb.go:606 ⋮ opening rocksdb instance at ‹"/data/home/kena/src/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp302681397"›
I200426 20:06:45.574608 75 server/server.go:750 ⋮ [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled
I200426 20:06:45.574782 75 storage/rocksdb.go:606 ⋮ opening rocksdb instance at ‹"/data/home/kena/src/go/src/github.com/cockroachdb/cockroach/cockroach-data"›
I200426 20:06:45.581451 75 server/config.go:576 ⋮ [n?] ‹1› storage engine‹› initialized
I200426 20:06:45.581459 75 server/config.go:579 ⋮ [n?] ‹RocksDB cache size: 128 MiB›
I200426 20:06:45.581466 75 server/config.go:579 ⋮ [n?] ‹store 0: RocksDB, max size 0 B, max open file limit 1878853›
I200426 20:06:45.602204 75 server/server.go:1270 ⋮ [n?] **** add additional nodes by specifying --join=‹kenax:26257›
I200426 20:06:45.602218 75 server/init.go:166 ⋮ [n?] no stores bootstrapped and --join flag specified, awaiting init command or join with an already initialized node.
I200426 20:06:45.602234 75 server/init.go:186 ⋮ [n?] **** cluster ‹2a7d34b5-a2aa-469b-8efd-ef7deb62ca73› has been created
I200426 20:06:47.676567 117 gossip/gossip.go:1538 ⋮ [n1] node has connected to cluster via gossip
I200426 20:06:47.676620 117 kv/kvserver/stores.go:255 ⋮ [n1] wrote ‹0› node addresses to persistent storage
I200508 12:34:37.238123 1346 kv/kvserver/replica_consistency.go:255 ⋮ [n1,consistencyChecker,s2,r‹4/1:/System{/tsd-tse}›] triggering stats recomputation to resolve delta of ‹{ContainsEstimates:1438 LastUpdateNanos:1588941276231756380 IntentAge:0 GCBytesAge:0 LiveBytes:-35159 LiveCount:-692 KeyBytes:-33660 KeyCount:-692 ValBytes:-1499 ValCount:-692 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}›
```

Release note (cli change): Certain kinds of advanced troubleshooting
information, for example internal details from the Go runtime, are now
output to a separate log file in the configured log directory.  This
file is named `<program>-stderr.xxx.log`.

Release note (cli change): The server CLI commands (`start`,
`start-single-node`, `demo`) now support a new flag
`--redactable-logs`, which introduces markers in generated log entries
to facilitate redaction of sensitive information by `cockroach debug
zip` and other CockroachDB APIs. This flag is currently not enabled by
default, but is recommended for all deployments and will be enabled by
default in a later version.

This feature is experimental.

Note: the flag is *advertised* (in `--help`) by `cockroach start` and
`cockroach start-single-node`, where log files are expected as a
matter of course; it is also supported, yet *hidden* (from `--help`),
by every other CLI command because every command can also produce log
entries when passed `--log-dir` or `--logtostderr`.

Release note (cli change): The commands `cockroach debug zip` and
`cockroach debug merge-logs` support a new flag `--redact-logs`. When
specified, it causes log messages that potentially contain
confidential data or PII to be redacted away.

This feature is experimental.

Note 1: At the time of this writing, this redaction is extremely
aggressive and may hinder the ability of Cockroach Labs to investigate
issues from log files, especially if `--redactable-logs` is not
enabled server-side.

Note 2: Other potentially-confidential data may still be retrieved by
`cockroach debug zip`; the new flag only applies to retrieved log
files inside the output zip file.

### CODE REVIEW

**Comment by petermattis** [comment]
I haven't looked at the change in detail, but the redacted output looks like it should be redacting keys from log tags which it is not currently doing:

```
I200426 20:06:49.615435 524 kv/kvserver/replica_consistency.go:255  [n1,consistencyChecker,s1,r4/1:/System{/tsd-tse}] triggering stats recomputation to resolve delta of <REDACTED>
```

Specifically, the `/System{/tsd-tse}` part of the log tag can contain table keys. Is this something you're planning to address in a subsequent PR?

**Comment by knz** [comment]
> Specifically, the /System{/tsd-tse} part of the log tag can contain table keys. Is this something you're planning to address in a subsequent PR?

I already called it out in the commit message as "left over work" that needs to be addressed in this PR before it even merges.

I put the PR out to stimulate discussion this week about the approach. I'm not keen on advancing in this direction if the discussion steers me somewhere else.

**Comment by bdarnell** [comment]
> The markers are selected to be no-op on standard unix terminals.

But not in `less`, `emacs`, or `vim` (where they appear as `^N` and `^O`). 

> logs need preprocessing to be greppable

What do you mean? I just made a test file and it works for me. But losing easy greppability seems like a significant downside.


I'm not a fan of digging up obscure characters that seem to be unused (and invisible!) in practice and giving them new meanings. This seems likely to bite us somehow. (For example, as part of a convoluted security vulnerability, inserting `^O` characters into someone's database might be a way to defeat their log redactions).

We have occasional requests for changes to our log format (e.g. https://github.com/cockroachdb/cockroach/issues/44755), which is non-standard (and kind of annoying even when you're used to it - that leading `IWEF` character was a bad choice). Maybe it's time to introduce a second log stream in a structured format (which would make pre-processing effectively mandatory) from which the redacted and unredacted logs could be generated. We could continue logging the current format for a time as well.

**Comment by knz** [comment]
I'm preparing a RFC, this will be a better place for a discussion.

Misc feedback:

> But not in less, emacs, or vim (where they appear as ^N and ^O).

`less -R` works. For emacs/vim, that's easy to solve with editor configurations.

> > logs need preprocessing to be greppable
> What do you mean?

Most of the text is still greppable (that was a big motivation for this particular approach!!), but you need to be careful about text that straddles a marker boundary.

> (For example, as part of a convoluted security vulnerability, inserting ^O characters into someone's database might be a way to defeat their log redactions).

I've thought about this, they will be escaped appropriately.

> Maybe it's time to introduce a second log stream in a structured format which would make pre-processing effectively mandatory

That is indeed planned, but I consider this to be orthogonal. Moreover, the mandatory pre-processing does not bring us in a better place than the proposal here.

**Comment by knz** [comment]
RFC at #48076

**Comment by knz** [comment]
I think this now does what is said in #48076 so ready for review.

**Review by tbg — APPROVED** [review]

**Review by bdarnell — COMMENTED** [review]
> Reviewed 45 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @petermattis)

___
*[pkg/util/log/redact.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48051#-M8S0HRl0pMDa2oYNo5e:-M8S0HRl0pMDa2oYNo5f:bczxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a83da2247dae783041d34f35d3f227784c27b7/pkg/util/log/redact.go#L106)):*
> ```Go
> // TODO(knz): consider using richer arguments, like fmt.Formatter.
> type SafeFormatter interface {
> 	SafeFormat(w io.Writer)
> ```

The methods of `io.Writer` return `errors`. That means that either `SafeFormat` needs to return an `error` as well, or it needs to be documented that `SafeFormat` may only be called with Writers what guarantee that their `Write` method returns no error (`strings.Builder` satisfies this)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @knz, and @petermattis)

___
*[pkg/util/log/redact.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48051#-M8S0HRl0pMDa2oYNo5e:-M8e21BV68S7AFo7eE-x:beh08x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a83da2247dae783041d34f35d3f227784c27b7/pkg/util/log/redact.go#L106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The methods of `io.Writer` return `errors`. That means that either `SafeFormat` needs to return an `error` as well, or it needs to be documented that `SafeFormat` may only be called with Writers what guarantee that their `Write` method returns no error (`strings.Builder` satisfies this)
</blockquote></details>

1) See the discussion thread on #49457 where this is discussed - I'll update this PR accordingly 

2) I hear you but I'm not convinced by your argument. The `fmt.Formatter` interface does not allow the Format method to return errors, and they don't say much about it.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @petermattis)

___
*[pkg/util/log/redact.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48051#-M8S0HRl0pMDa2oYNo5e:-M8kYjsD-7kRLcUJD9pE:b-v5ngco) ([raw file](https://github.com/cockroachdb/cockroach/blob/01a83da2247dae783041d34f35d3f227784c27b7/pkg/util/log/redact.go#L106)):*
> The fmt.Formatter interface does not allow the Format method to return errors, and they don't say much about it.

That's kind of surprising, but OK. I'm fine with following the example of fmt.Formatter. However, we should still check the returned error in all implementations of SafeFormat and panic if it's non-nil (the fmt package does specify that it recovers from panics in this case).

**Comment by knz** [comment]
Heads up that there's an unforeseen small roadblock: we have historically redirected stderr (file descriptor 2) to go to the log file, because the Go runtime is print-happy whenever it detects something is amiss, and fd2 is hardcoded in the Go runtime sources. Example uses:

- panic message + traceback upon crashes
- detected heap corruptions
- unexpected signals
- out of memory
- stack depth exceeded

etc

Now, there's so much potentially printed in there that we cannot assume all of it is safe. Additionally, anything printed by the Go runtime into a CockroachDB log files *makes that output logically part of the last log entry printed*, **because we don't have terminating delimiters for log entries.**

I have tried to spawn a goroutine internally that uses `os.Pipe` to provision fd2, and adds redaction annotation to everything printed there. Unfortunately, when the Go runtime is unhappy, that goroutine is not given a chance to run (or not on time) and we lose the output.

I am seeing two ways forward here; either:

1. **stop redirecting fd2** to the crdb log file;
2. **introduce a terminating delimiter for log entries**, that would be inserted at the end of the log entry whenever the entry is redactable. Then we'd make the entry reader/parser ignore everything after the delimiter and before the start of the next valid entry.

The advantage of (2) is that it keeps the runtime messages in the log files as previously. However it adds even more markers into the logging output. Also, more concerning, **writes to fd2 by the runtime and the log file by `log` could be interleaved**, causing the unsafe runtime output to appear "inside" a log entry.

This makes my preference go to (1), which has the advantage of remaining fully safe.

We could stop redirecting fd2 completely, and then tell users "give us your stderr output whenever you contact support". Or we could instead redirect it to a separate "stderr output file" in the log directory, which would be gathered separately by `debug zip`, not gathered when redaction is enabled, and not visible to the log file retrieval RPC.

Thoughts?

**Comment by tbg** [comment]
Hmm, that's unfortunate. I agree that option 2) seems untenable. I agree
that we should go forward with option 1), though it would be a bummer to
lose the stack traces when redaction is on. `panicparse`[1] will let us
safely recover any stack traces and we can probably also get the relevant
information from the `panic: ` line if there is one. It's work, but not too
bad.

[1]: https://github.com/maruel/panicparse

**Comment by knz** [comment]
We'll get the stack traces for panic, that's not an issue. We get them because the stopper ensures the stacks are printed to logs (and sent to sentry) when a task finishes with a panic.

The main issue is all the non-stacktrace details, for example heap corruptions etc.

**Comment by bdarnell** [comment]
> We could stop redirecting fd2 completely, and then tell users "give us your stderr output whenever you contact support". Or we could instead redirect it to a separate "stderr output file" in the log directory, which would be gathered separately by debug zip, not gathered when redaction is enabled, and not visible to the log file retrieval RPC.

I think we need to use a separate stderr file in the log directory. It's not tenable to ask users to save stderr and be able to give it to us on request; the difficulty of doing that in practice across the diversity of deployment environments is why we implemented the (hacky) fd2 redirection in the first place. 

It's unfortunate to lose these files completely when redacting. I don't know how often we end up getting useful information here, but I think it's rare for them to contain sensitive information. We may want to have an option to collect stderr files without unredacting all the rest (maybe showing them to the user for inspection.

**Comment by knz** [comment]
> We may want to have an option to collect stderr files without unredacting all the rest (maybe showing them to the user for inspection.

yes agreed. I'll try to cook something up towards that.

**Comment by knz** [comment]
I found an elegant solution: keep the stderr redirect to a regular log file, but use a secondary logger. Then make the "reportable" flag (and thus the vertical ellipsis marker) per-logger, and disable it from the stderr log file.

This way the stderr output remains naturally visible via the RPCs and `debug zip`

**Comment by knz** [comment]
the stderr redirection stuff works fine. I'll wrap this up soon.

**Review by knz — COMMENTED** [review]
I have implemented the SafeFormatter mechanism we discussed earlier and applied it in a few places in roachpb.
For example here:
https://github.com/cockroachdb/cockroach/pull/48051/files#diff-8daf13806c92216f1e390e1411fdf6cbR295-R322

It nicely makes the code more compact, and allows us to share code between the String() and SafeFormat() methods.

Feel free to have a look and provide further feedback. Otherwise I plan to merge this by EOD tomorrow.

Some additional notes for follow-up work:

- this PR leaves the new feature disabled by default, until I expose the results to a few co-workers and gather a go/no-go decision on flipping the switch.
- currently the `errors` package does not know about the SafeFormatter mechanism and still relies on the (now-obsolete) SafeMessager interface. The result is that the amount of details potentially reported to Sentry decreases with this PR. I plan to reconcile this in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48051#-:-M9EgKG1AUPtsP5nt4oV:b-4xhlw5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, @knz, and @petermattis)

**Comment by knz** [comment]
I'll process any further feedback in followup PRs.

bors r=tbg,bdarnell

**Pull request merged**
