### PR TITLE
sql: add the builtin crdb_internal.list_sql_keys_in_range

### LINKED ISSUE #54975: sql: introduce shorthand to retrieve sql keys for a given range
**Is your feature request related to a problem? Please describe.**

During support calls we've frequently seen the need to go from a know problematic range to the SQL table/index/database corresponding to that range. We end up stitching together usage of [`SHOW RANGES`](https://www.cockroachlabs.com/docs/v19.2/show-ranges.html#show-ranges-for-a-database) to narrow down which keys a given range contains. We also consult the start/end keys of a given range to narrow down the specific table ID in question (`/234/<...`) and then look to find the table name, and so on.

**Describe the solution you'd like**

It'd be very useful to have a readily usable helper/query to quickly go from range ID to the SQL keyspace in question. It would shorten the debug loop by removing the tedious and error-prone manual steps needed to go from range ID to rows of interest. Straw man proposal (pulled out of thin air, almost definitely not what we want):

```sql
SHOW DATA FOR RANGE <range id>;
```
```
     database     |          table/index           | key (not the raw MVCC key, a SQL key that I can readily use)
+-----------------+--------------------------------+-------------------------------------------------------------+
  ...
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by rohany**
Fixes #54975.

Add the internal builtin function crdb_internal.list_sql_keys_in_range.
This function return all SQL keys within a target range (given by
RangeID).

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Happy to bikeshed about naming, return values/types etc, whether you still want this etc

**Review by irfansharif — APPROVED** [review]
Nice, thanks for sending this! :lgtm: but I'm also not an expert here, so cc-ing @solongordon.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-:-MPopOULCJw6N4cDPMeg:bv4i8zf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[docs/generated/sql/functions.md, line 2568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPolzCIE5JRmcJ9ax3y:-MPolzCIE5JRmcJ9ax3z:b-1aqw43) ([raw file](https://github.com/cockroachdb/cockroach/blob/6603f16693d4db4cd297fdb7ac73c70a51f827f6/docs/generated/sql/functions.md#L2568)):*
> ```Markdown
> <tr><td><a name="crdb_internal.lease_holder"></a><code>crdb_internal.lease_holder(key: <a href="bytes.html">bytes</a>) &rarr; <a href="int.html">int</a></code></td><td><span class="funcdesc"><p>This function is used to fetch the leaseholder corresponding to a request key</p>
> </span></td></tr>
> <tr><td><a name="crdb_internal.list_sql_keys_in_range"></a><code>crdb_internal.list_sql_keys_in_range(range_id: <a href="int.html">int</a>) &rarr; tuple{string AS key, string AS value}</code></td><td><span class="funcdesc"><p>TODO (rohany): Fill this out</p>
> ```

Remember to address this.
___
*[pkg/sql/logictest/testdata/logic_test/sql_keys, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPomLlY-kqO3PgsPWHM:-MPomLlY-kqO3PgsPWHN:beehfeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6603f16693d4db4cd297fdb7ac73c70a51f827f6/pkg/sql/logictest/testdata/logic_test/sql_keys#L1)):*
> ```
> # LogicTest: local
> ```

Mind moving this test into `crdb_internal`?
___
*[pkg/sql/logictest/testdata/logic_test/sql_keys, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPondkjDX1fO5HHq1LS:-MPondkjDX1fO5HHq1LT:b7evno6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6603f16693d4db4cd297fdb7ac73c70a51f827f6/pkg/sql/logictest/testdata/logic_test/sql_keys#L13)):*
> ```
> 
> # TODO (rohany): I thought ranges were split automatically on table creation, but
> #  I seem to have to do the SPLIT AT above. Is something different in logic tests?
> ```

Dunno, but I think we're having to do the same thing here: https://github.com/cockroachdb/cockroach/blob/ad3dea8af9a417203d2496dcd47a6e98f3019a9c/pkg/sql/logictest/testdata/logic_test/crdb_internal#L370-L380
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPooe3iDz89YhvJayG3:-MPooe3iDz89YhvJayG4:b-gmx99v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6603f16693d4db4cd297fdb7ac73c70a51f827f6/pkg/sql/sem/builtins/generator_builtins.go#L1313)):*
> ```Go
> 	}
> 	// Scan all of the K/V's within the target range.
> 	// TODO (rohany): Is it OK to have maxRows = 0 here? Since range sizes are capped (64 mb),
> ```

Range sizes now 512mb by default, and given we'd typically expect to use this when debugging live, minimizing any sort of impact seems prudent. Is it much work to fold it into the iterator instead?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58314)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1315 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPorDKjCizSnhx83FxL:-MPorDKk7fNQx5NXGXUA:b-eszqg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6603f16693d4db4cd297fdb7ac73c70a51f827f6/pkg/sql/sem/builtins/generator_builtins.go#L1315)):*
> ```Go
> 	// TODO (rohany): Is it OK to have maxRows = 0 here? Since range sizes are capped (64 mb),
> 	//  we shouldn't OOM here. If not, we can do these scans as part of the iterator.
> 	kvs, err := txn.Scan(ctx, rangeDesc.StartKey, rangeDesc.EndKey, 0 /* maxRows */)
> ```

Please don't issue the `Scan` for all the rows inside `Start()` and then load them in RAM.

There should be buffering in the generator struct, and a conditional re-call of `Scan` in the `Next()` function instead.

At any point in time there should be no more than N bytes of data buffered inside the builtin struct, where N is fixed, small-ish (let's say, less than 1KiB) and independent of the range's actual size.

Also add a TODO: the KV interface currently has a `maxRows` parameters, but we're changing that to have a `maxBytes` parameter instead. That's what we really want. If some keys happen to be very large, `maxRows` doesn't help with memory usage.

**Comment by rohany** [comment]
> Remember to address this.

Done, forgot to remake

> Mind moving this test into crdb_internal?

I wanted to keep this test separate as it depends on descriptor ID's. The `crdb_internal` tests are already a minefield of descriptor ID dependencies.

Moved the builtin to a buffering / paged version.

**Review by knz — COMMENTED** [review]
very nice. thanks.
just noticed that the meta scan has the same issue, see comment

> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-:-MPpCeb85I_4VFBitSay:b-pz5ctz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @rohany)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPpC5R7AGgVXDvK-pYp:-MPpC5R82pI1yiaxafV5:b-5hhj4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7983cff58d4e4007acc4c5003222ef3b4abc617b/pkg/sql/sem/builtins/generator_builtins.go#L1248)):*
> ```Go
> // rangeKeyIterator requests at a time. If this changes, make sure
> // to update the test in sql_keys.
> // TODO (kv): The current KV API only supports a maxRows limitation
> ```

nit: there's a linter that wants `TODO(kv)` without a space
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPpC8YO6sGoWeyS_ezX:-MPpC8YO6sGoWeyS_ezY:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7983cff58d4e4007acc4c5003222ef3b4abc617b/pkg/sql/sem/builtins/generator_builtins.go#L1254)):*
> ```Go
> 
> var rangeKeyIteratorType = types.MakeLabeledTuple(
> 	// TODO (rohany): These could be bytes if we don't want to display the
> ```

ditto
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPpCKxY4hSfQADAuBBU:-MPpCKxY4hSfQADAuBBV:b-stwrul) ([raw file](https://github.com/cockroachdb/cockroach/blob/7983cff58d4e4007acc4c5003222ef3b4abc617b/pkg/sql/sem/builtins/generator_builtins.go#L1307)):*
> ```Go
> func (rk *rangeKeyIterator) Start(ctx context.Context, txn *kv.Txn) error {
> 	rk.txn = txn
> 	// Scan the range meta K/V's to find the target range.
> ```

similar comment to previous: if there are many ranges in the cluster, then this is going to blow up too.
I'd suggest to page through meta with no more than 100 or 1000 ranges at a time. (This can be achieved with maxRows.)

**Comment by rohany** [comment]
Thanks on the heads up for the linter fixed.

> similar comment to previous: if there are many ranges in the cluster, then this is going to blow up too.
I'd suggest to page through meta with no more than 100 or 1000 ranges at a time. (This can be achieved with maxRows.)

Done, nice catch. The existing ScanMetaKV's API / users didn't lend well to a paging style use, so I inlined some of the logic here.

**Review by knz — COMMENTED** [review]
LGTM modulo placing the code in the right place(s).

> Reviewed 2 of 6 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-:-MPpLT6d59Q7m8w_02CO:blfgrn2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1308 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58314#-MPpL20X2G58eNg8IdBK:-MPpL20Y-sRX59XxVQl7:bi8ilz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f30c6f4d075ee70bdcaf2b63809f88673eb210/pkg/sql/sem/builtins/generator_builtins.go#L1308)):*
> ```Go
> 	// Scan the range meta K/V's to find the target range. We do this in a
> 	// chunk-wise fashion to avoid loading all ranges into memory.
> 	var ranges []kv.KeyValue
> ```

I appreciate that the existing kv scan function was not appropriate, but the code you have written here is not really appropriate for a "SQL builtins" package either. It's very much low level  and belongs to KV.

Therefore I'd encourage you to move this code into a new function in the appropriate package, and call it from here.

**Comment by rohany** [comment]
Do you have a suggestion of a package that this could go in? I'm not familiar with the packages in `kv`.

**Comment by knz** [comment]
can you put them in `pkg/kv/kvserver` (new file `scan_meta.go`) 

then also move `sql.ScanMetaKVs` there and update the call points accordingly

(as well as the reference in a comment in `pkg/keys/keys.go`)

**Comment by knz** [comment]
sorry I meant `kvclient` not `kvserver`, my bad

**Comment by rohany** [comment]
Done, thanks!

**Review by knz — APPROVED** [review]
> Reviewed 16 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany)

**Comment by rohany** [comment]
looks like this finally passed tests. Can one of you bors this ?

**Comment by knz** [comment]
this looks like an infra flake.

bors r+

**Pull request merged**
