### PR TITLE
sql: create system tables for SQL stats

### PR DESCRIPTION
**Pull request by Azhng**
This PR creates two new system tables: system.sql_statement_stats
and system.sql_transaction_stats per RFC #63752.

This is the initial step that addresses #64743.

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/catalog/systemschema/system.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zZjkp7wRbdnNrSbWJ:-M_zZjkp7wRbdnNrSbWK:b-m8yjno) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L370)):*
> ```Go
> 
> 	SQLStatementStatsTableSchema = `
> CREATE TABLE system.sql_statement_stats (
> ```

nit: I think those two tables should use plural, otherwise looks like is several stats for one statement/transaction. So `sql_statements_stats` and `sql_transactions_stats`
Also update in all references, e.g. `SQLStatementsStatsTableSchema`
___
*[pkg/sql/catalog/systemschema/system.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zaS0XAhyAmOWq9hoM:-M_zaS0XAhyAmOWq9hoN:b-lt6fww) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L386)):*
> ```Go
> 
>     PRIMARY KEY (aggregated_ts, fingerprint_id, plan_hash, app_name, node_id)
>       USING HASH WITH BUCKET_COUNT = 8,
> ```

You mentioned on the RFC that the size of bucket as 8 was arbitrary and that would require some benchmark testing to choose the value. Was that done? If not, should we add a comment here explaining and that this value could be replaced?
___
*[pkg/sql/catalog/systemschema/system.go, line 1852 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zbBQd7Rr6O7qMhwLL:-M_zbBQd7Rr6O7qMhwLM:bfk0vno) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L1852)):*
> ```Go
> 	})
> 	// SQLStatementStatsTable is the descriptor for the SQL statement stats table.
> 	// It stores statistics for statistics for statement fingerprints.
> ```

nit: It stores statistics for statements fingerprints.
___
*[pkg/sql/catalog/systemschema/system.go, line 1952 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zb_8FB6etdz5bRh3D:-M_zb_8FB6etdz5bRh3E:b72d67p) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L1952)):*
> ```Go
> 
> 	// SQLTransactionStatsTable is the descriptor for the SQL transaction stats
> 	// table. It stores statistics for statistics for transaction fingerprints.
> ```

nit: It stores statistics for transactions fingerprints.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @maryliag)

___
*[pkg/sql/catalog/systemschema/system.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zZjkp7wRbdnNrSbWJ:-Ma-pB3187po3u7purcP:b-w8uxwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L370)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: I think those two tables should use plural, otherwise looks like is several stats for one statement/transaction. So `sql_statements_stats` and `sql_transactions_stats`
Also update in all references, e.g. `SQLStatementsStatsTableSchema`
</blockquote></details>

I think currently our system view is named `crdb_internal.node_statement_statistics`. So it's slightly breaking the convention here if we named it plural. @kevin-v-ngo What do you think? 
___
*[pkg/sql/catalog/systemschema/system.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-M_zaS0XAhyAmOWq9hoM:-Ma-pAPgELq51Va1AJOp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285f2e5931cf7558f524b5da8822fef8f300f593/pkg/sql/catalog/systemschema/system.go#L386)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

You mentioned on the RFC that the size of bucket as 8 was arbitrary and that would require some benchmark testing to choose the value. Was that done? If not, should we add a comment here explaining and that this value could be replaced?
</blockquote></details>

Done.

**Comment by pbardea** [comment]
(Bulk IO changes look like mainly plumbing which LGTM, so going to untag myself)

**Review by Azhng — COMMENTED** [review]
Thank you. Who should I tag for changes related to system table schema? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-Ma0ZC3o8zmbv3fVV7EL:bov250b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @maryliag)

**Comment by nihalpednekar** [comment]
> Thank you. Who should I tag for changes related to system table schema?

@rytaft might be a good reviewer to add, as a contributor to the file and `pkg/sql/stats` owner.

**Review by rytaft — APPROVED** [review]
:lgtm: although I haven't touched most of this code in several years. Might be good to also check with someone on the SQL schema team...

> Reviewed 8 of 11 files at r1, 29 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-Ma5Nmmr2g0eI2TbS_Un:by0yhi6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, and @maryliag)

___
*[pkg/sql/catalog/bootstrap/metadata.go, line 352 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-Ma5KqTH4_uGMN_Kp7dG:-Ma5KqTH4_uGMN_Kp7dH:bar8kxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5fb52a9f64b6727eacc0f9712e61eaf3ae4b68/pkg/sql/catalog/bootstrap/metadata.go#L352)):*
> ```Go
> 
> 	// Tables introduced in 21.2.
> 	target.AddDescriptor(keys.SystemDatabaseID, systemschema.SQLStatementStatsTable)
> ```

nit: add a blank line above to be consistent with previous versions
___
*[pkg/sql/catalog/systemschema/system.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-Ma5LkkKBrNhVoc6cXtq:-Ma5LkkL3VfWuR-hPD2b:b-xf5a1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5fb52a9f64b6727eacc0f9712e61eaf3ae4b68/pkg/sql/catalog/systemschema/system.go#L456)):*
> ```Go
> 	singleID1              = []descpb.ColumnID{1}
> 	sqlStmtHashComputeExpr = "mod(fnv32(COALESCE(CAST(aggregated_ts AS STRING), '':::STRING)) + (fnv32(COALESCE(CAST(app_name AS STRING), '':::STRING)) + (fnv32(COALESCE(CAST(fingerprint_id AS STRING), '':::STRING)) + (fnv32(COALESCE(CAST(node_id AS STRING), '':::STRING)) + fnv32(COALESCE(CAST(plan_hash AS STRING), '':::STRING))))), 8:::INT8)"
> 	sqlTxnHashComputeExpr  = "mod(fnv32(COALESCE(CAST(aggregated_ts AS STRING), '':::STRING)) + (fnv32(COALESCE(CAST(app_name AS STRING), '':::STRING)) + (fnv32(COALESCE(CAST(fingerprint_id AS STRING), '':::STRING)) + fnv32(COALESCE(CAST(node_id AS STRING), '':::STRING)))), 8:::INT8)"
> ```

where did these expressions come from? A comment would help
___
*[pkg/sql/tests/system_table_test.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-Ma5NQpk6u8FnHu7Hmw4:-Ma5NQpk6u8FnHu7Hmw5:b-4c7fx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5fb52a9f64b6727eacc0f9712e61eaf3ae4b68/pkg/sql/tests/system_table_test.go#L172)):*
> ```Go
> 		LocalOnlySessionData: sessiondata.LocalOnlySessionData{
> 			EnableUniqueWithoutIndexConstraints: true,
> 			HashShardedIndexesEnabled:           true,
> ```

instead of adding the sessionDataOverride, is there a reason you can't just update the session data in the test file and set this to true? Does it break anything?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-Ma5LkkKBrNhVoc6cXtq:-Ma5j1Ac4ooJ9LlbNKp0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5fb52a9f64b6727eacc0f9712e61eaf3ae4b68/pkg/sql/catalog/systemschema/system.go#L456)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

where did these expressions come from? A comment would help
</blockquote></details>

Done.
___
*[pkg/sql/tests/system_table_test.go, line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-Ma5NQpk6u8FnHu7Hmw4:-Ma5gwUi87qnjOsa_TVn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5fb52a9f64b6727eacc0f9712e61eaf3ae4b68/pkg/sql/tests/system_table_test.go#L172)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

instead of adding the sessionDataOverride, is there a reason you can't just update the session data in the test file and set this to true? Does it break anything?
</blockquote></details>

Done.

**Review by Azhng — COMMENTED** [review]
Table names have been renamed to "system.statement_statistics" and "system.transaction_statistics" per feedback on the RFC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-Ma5jBBj-v__ml9oNZJ0:bt26gb1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: Might want to ask @ajwerner for a quick glance at the system table stuff.

> Reviewed 27 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-Ma8p-OG9IDy0HpDf73L:b-x2blw0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaTQbPeAG2koXkjIOFH:bjh6027) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
> ```Go
> 
>     PRIMARY KEY (aggregated_ts, fingerprint_id, app_name, node_id)
>       USING HASH WITH BUCKET_COUNT = 8,
> ```

I wonder if we're going to be horribly sad about this soon. @mgartner, IIUC, is going to look at switching hash sharded indexes to no longer be physically stored columns. It's a bummer that we need to create this extra hash column and makes the implementation somewhat messy. I worry we'll carry this vestige of the original implementation with us forever if we choose to use it now. 

What was the back-of-the-envelope for write throughput of a cluster that convinced us that we needed to hash this index?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag, @mgartner, and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZDhvmEzBGRotgqe-1:b-ea9r8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I wonder if we're going to be horribly sad about this soon. @mgartner, IIUC, is going to look at switching hash sharded indexes to no longer be physically stored columns. It's a bummer that we need to create this extra hash column and makes the implementation somewhat messy. I worry we'll carry this vestige of the original implementation with us forever if we choose to use it now. 

What was the back-of-the-envelope for write throughput of a cluster that convinced us that we needed to hash this index? 
</blockquote></details>

Is the switch to no longer physically storing hash column going to happen this release? IIUC, we can always change the system table schema without worrying about migrations before the 21.2 happens. 

I think the back-of-the-envelope for write throughput based on the data we have in snowflake for CC, the [worst case](https://github.com/cockroachdb/cockroach/pull/63752#pullrequestreview-652591999) would be 14 GB/hr for a 32 node cluster. Though it is one of the extreme cases. Most of the other clusters would generate tens to hundreds of MB of writes.

**Comment by mgartner** [comment]
___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZJ0I38_57UXEwkLC0:b5fctsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
> Is the switch to no longer physically storing hash column going to happen this release?

We're exploring simplifying the hash-sharded index implementation this release by using virtual computed columns. But there are still some unanswered questions, like, does this even make sense given that the hash-sharded column has to be park of the PK.

But I don't expect the syntax for creating a hash-sharded index to change. What problems would arise if the underlying hash-sharded implementation changes if there's already this existing system table in a cluster?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, @mgartner, and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZP8G2BwGIFlwMpD6W:b-fnfpr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
> But there are still some unanswered questions, like, does this even make sense given that the hash-sharded column has to be park of the PK.

In this case, you mean? Generally, the hash-sharded column does not need to be part of the primary key. You are right that if we keep it in the primary key, then it's a total wash.

> I think the back-of-the-envelope for write throughput based on the data we have in snowflake for CC, the worst case would be 14 GB/hr for a 32 node cluster. Though it is one of the extreme cases.

That is a lot.
___
*[pkg/sql/catalog/systemschema/system.go, line 423 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaZQMWa45of_A8fYQ8L:-MaZQMWa45of_A8fYQ8M:b28onp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L423)):*
> ```Go
>     PRIMARY KEY (aggregated_ts, fingerprint_id, app_name, node_id)
>       USING HASH WITH BUCKET_COUNT = 8,
>     INDEX "fingerprint_stats_idx" (fingerprint_id, aggregated_ts, app_name, node_id),
> ```

I'm somewhat suspect of this choice of primary and secondary index. It'd be nice to have some data generation and then some benchmarking. Changing this schema may be somewhat painful after it merges, at least to some extent. I worry that, in the long term, we'll wish that the hash-sharded index had small values and that the primary index were more scattered. Did you consider using `fingerprint_stats_idx` as the primary index and the current primary index as a secondary index? I think that'll allow for fast loading of a page for a given fingerprint and reduce the size of data that needs to be replicated to the hash sharded index by several orders of magnitude.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @maryliag, @mgartner, and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZV70MBRYs8dZ-MMKy:b-vzv6y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
> You are right that if we keep it in the primary key, then it's a total wash.

I'm not quite following this. Can you elaborate more?

 > That is a lot.

The write throughput scales based on unique number of fingerprints (~1 KiB per fingerprint) and number of nodes in the cluster. During the RFC discussion, knz pointed out that the performance sensitive clusters tend to tune their workload to have small number of unique number of fingerprints. This means in these clusters, we will be seeing a lot less unique fingerprints. 
___
*[pkg/sql/catalog/systemschema/system.go, line 423 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaZQMWa45of_A8fYQ8L:-MaZSOUF5C9DjLUgi7fW:b-ggqzm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L423)):*
> Did you consider using fingerprint_stats_idx as the primary index and the current primary index as a secondary index?

We did consider this as the original design. However, this table also will power the loading for the statement page, which displays aggregated execution statistics for **all** statement fingerprints for a given time interval. Since we [considered](https://github.com/cockroachdb/cockroach/pull/63752#pullrequestreview-641431592) (grep for 'statement page') loading statement page to be a more important use case compared to loading statistics for a single fingerprint, we chose the design of using hash sharded PK. 

> Changing this schema may be somewhat painful after it merges, at least to some extent

Even if we change prior to the 21.2  release ?

**Comment by mgartner** [comment]
___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZZPPU55l39Tr5h0Cq:b-e3cz4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
> In this case, you mean? Generally, the hash-sharded column does not need to be part of the primary key. You are right that if we keep it in the primary key, then it's a total wash.

For a hash-sharded primary index, the hash-sharded column is the first column in the PK, no?

**Review by ajwerner — COMMENTED** [review]
Can I make a procedural recommendation here that may derail this stuff a tad? I just went through the RFC a bit and I think this project could really benefit from some go interfaces. I'm increasingly on board with this layout etc but think everything will fall into place better with some interface structure that we put in place first rather that last. I don't want to get too in your way here, I know this is way more than you bargained for.

I think we're in a bit of a mess right now with the in-memory implementation and how we're just injecting the entire `*sql.Server` into the status APIs and calling arbitrary methods.

A pattern that has been working well from my perspective lately is a set of low-dependency interfaces sitting in a package and some implementations sitting in separate subpackages. This way we can trivially do things like compose the retrieval and combination of persisted stats with in-memory stats without changing any clients. We can also test things about the implementation via the interface.

How do you feel about something like a `stmtstats` package which has interfaces like `Reader` and `Writer` that provide access to the various layers? Then we can compose some of these implementations, simplify clients, and dramatically simplify testing of different layers. 

Maybe you've got a code structure plan in mind. I'd love to reach some alignment before we just glom more arbitrary functionality onto gigantic objects like `*sql.Server`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-MaZZ9sFCt1JK1uhx1F3:bwha4nd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng, @maryliag, and @rytaft)

___
*[pkg/sql/catalog/systemschema/system.go, line 422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaTQbPeAG2koXkjIOFG:-MaZb0tq4l8vq_IckBBF:bd22g7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L422)):*
>> In this case, you mean? Generally, the hash-sharded column does not need to be part of the primary key. You are right that if we keep it in the primary key, then it's a total wash.
>
> For a hash-sharded primary index, the hash-sharded column is the first column in the PK, no?

Correct
___
*[pkg/sql/catalog/systemschema/system.go, line 423 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-MaZQMWa45of_A8fYQ8L:-MaZarGyAXnUl_6IAHKN:b-4wjng1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c26f95b00194e73a03a539e0513813b0eeaf2a9/pkg/sql/catalog/systemschema/system.go#L423)):*
>> Changing this schema may be somewhat painful after it merges, at least to some extent
> 
> Even if we change prior to the 21.2 release ?

Not too painful, just non-zero.

**Review by knz — COMMENTED** [review]
:+1: on Andrew's suggestion.

> Reviewed 2 of 27 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-MacCzq13kvgeRH46LFM:b-ke1e1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Review by Azhng — COMMENTED** [review]
Discussed with @ajwerner offline and decided to move forward with the refactoring. Also filed a [tracking issue](https://github.com/cockroachdb/cockroach/issues/65699)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-MadHlIH0YOe6ELSf_7z:b-z0wdxj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Comment by Azhng** [comment]
Rebased to resolve the merge conflict. See follow up PR #67090 for the SQL Stats flush mechanism. @ajwerner  can you take another look.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 31 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65374#-:-MdwQy0984ZMUG9wC-a6:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @maryliag, and @rytaft)

**Comment by Azhng** [comment]
TFTR! 

bors r+

**Pull request merged**
