### PR TITLE
sql: refactor MetadataUpdater to properly share txns/collections

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the code that we added for the metadata updater, which
is used to update descriptor metadata had code paths that could
end up creating new transactions/collections. This was problematic because
those updates were not executing under the same user transaction.
This patch simplifies the metadata updater logic to no longer
have a factory and share collections/transactions properly.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Great change, see how you feel about my one suggestion. Otherwise, :lgtm: 

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83592#-:-N5kVBzvEBOxhx6wxVWQ:bgzjxtp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/descmetadata/metadata_updater.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83592#-N5kUymaCZcxPwK31spj:-N5kUymaCZcxPwK31spk:b-ooyqjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9abbef395251f168cd7f1181bacd8ab1feb041a3/pkg/sql/descmetadata/metadata_updater.go#L56)):*
> ```Go
> 	// code modifying this metadata would use a circular executor that would ignore
> 	// any settings set later on. We will intentionally, unset problematic settings
> 	// here.
> ```

You could just store the `ieFactory` in the struct and make a new one each time you need to use the ie?



_Code quote:_
```Go
	// Unfortunately, we can't use the session data unmodified, previously the
	// code modifying this metadata would use a circular executor that would ignore
	// any settings set later on. We will intentionally, unset problematic settings
	// here.
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83592)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/descmetadata/metadata_updater.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83592#-N5kUymaCZcxPwK31spj:-N5kXA1VEyB8rZUdqte6:b-1m9xl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9abbef395251f168cd7f1181bacd8ab1feb041a3/pkg/sql/descmetadata/metadata_updater.go#L56)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You could just store the `ieFactory` in the struct and make a new one each time you need to use the ie?
</blockquote></details>

Modified to store the ieFactory and things required to construct one

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83592)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/descmetadata/metadata_updater.go` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83592#-NAkq-tn9vfof_lfaaQ4:-NAkq-tn9vfof_lfaaQ5:b-dcc82c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d015a6524425a681951c31ebdfa497c77f16b90/pkg/sql/descmetadata/metadata_updater.go#L60)):*
> ```Go
> 	// here.
> 	modifiedSessionData := sessionData.Clone()
> 	modifiedSessionData.ExperimentalDistSQLPlanningMode = sessiondatapb.ExperimentalDistSQLPlanningOn
> ```

Unexpected log messages during a test debugging brought me here: why are we setting `ExperimentalDistSQLPlanningOn`? That setting doesn't support many things, so many queries will perform a somewhat redundant work that will be discarded later due to unsupported features. If we need to override this particular setting (why do we need though?), we should use `ExperimentalDistSQLPlanningOff`.

**Pull request merged**
