### PR TITLE
build: Add PATH to .bazelrc for dev builds

### PR DESCRIPTION
**Pull request by benbardin**
Release note: none

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
Looks like the `go.mod` and `go.sum` file changes are not intended?

**Review by rickystewart — APPROVED** [review]
Oh, there you go, beat me to it. This works.

**Comment by benbardin** [comment]
Yup, thanks! I confirmed locally that this works.

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
One nit, but which probably isn't worth another CI cycle over: we typically prefix commit and PR titles with the package, component, or topic being modified (e.g. sql/opt: foo, or kvserver: bar, or scripts: xyz). Something like this where it isn't in a package could use a category like `build: Add PATH ...` or just `.bazelrc: Add PATH ...`. Again, minor nit for future but probably not worth amending for it.

**Comment by rickystewart** [comment]
Oh yeah, sorry, I didn't even check the title. That's my bad. I would use `build: ` for the prefix, not a huge deal if it gets merged as-is though.

**Comment by benbardin** [comment]
Thanks for the tip! I don't mind rerunning CI, I updated the descriptions.

**Pull request merged**
