### PR TITLE
docgen: update SQL diagrams for SQL docs refactor

### PR DESCRIPTION
**Pull request by taroface**
Updated existing & added some new SQL diagrams. These will be used in the SQL docs being refactored as per https://cockroachlabs.atlassian.net/browse/DOC-5850

Epic: none

Release note: none

Release justification: non-production code change

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Parser changes :lgtm:, but I have a question about the diagrams change

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-:-NMFOkxO1RXholnxzjpU:b-cxmk1w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[`pkg/cmd/docgen/diagrams.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-NMFOOUS50TbcsxjQmY-:-NMFOOUS50TbcsxjQmY0:b-fqfawx) ([raw file](https://github.com/cockroachdb/cockroach/blob/892d80d1ec05d7c1aca44ff314065305f5d3b7eb/pkg/cmd/docgen/diagrams.go#L403)):*
> ```Go
> 	},
> 	{
> 		name:	"alter_database",
> ```

I'm not familiar with this file or how to review changes here. Is there something I can look at?

**Comment by taroface** [comment]
> Parser changes :lgtm:, but I have a question about the diagrams change
> 
> > Reviewed 19 of 19 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-:-NMFOkxO1RXholnxzjpU:b-cxmk1w)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)
> 
> _[`pkg/cmd/docgen/diagrams.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-NMFOOUS50TbcsxjQmY-:-NMFOOUS50TbcsxjQmY0:b-fqfawx) ([raw file](https://github.com/cockroachdb/cockroach/blob/892d80d1ec05d7c1aca44ff314065305f5d3b7eb/pkg/cmd/docgen/diagrams.go#L403)):_
> 
> > ```go
> > 	},
> > 	{
> > 		name:	"alter_database",
> > ```
> 
> I'm not familiar with this file or how to review changes here. Is there something I can look at?

Yes, the results are in `alter-diagram.bnf` in this PR. I previewed it by plugging it into https://www.bottlecaps.de/rr/ui

**Comment by taroface** [comment]
Added the `backport-22.2.x` label hoping this will also generate the appropriate files in the `22.2` branch for me to embed in docs.

**Review by rytaft — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-:-NMFjSlA4SGN9Tqkq2ow:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @taroface)

___
*[`pkg/cmd/docgen/diagrams.go` line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95591#-NMFOOUS50TbcsxjQmY-:-NMFjOJK3jQ18PV3GxlY:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/892d80d1ec05d7c1aca44ff314065305f5d3b7eb/pkg/cmd/docgen/diagrams.go#L403)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Yes, the results are in `alter_database.bnf` in this PR. I previewed it by plugging it into https://www.bottlecaps.de/rr/ui
</blockquote></details>

Thanks!

**Comment by taroface** [comment]
bors r=rytaft

**Comment by renatolabs** [comment]
bors r-

See`Bazel Essential CI` failures.

**Comment by taroface** [comment]
bors r=rytaft

**Pull request merged**
