### PR TITLE
opt: pretty-print encoded inverted keys in constraints

### PR DESCRIPTION
**Pull request by mgartner**
Encoded inverted keys in constraints are now printed in a more
human-readable format.

Epic: None

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice! Are there any examples of what this would look like for other types than `STRING`?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-:-O83jjnpEs7QuIbsllmW:bsjy175)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
>Nice! Are there any examples of what this would look like for other types than `STRING`?

I expanded this to inverted spans as well, so now there are array and JSON examples.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131607)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/xform/testdata/rules/select` line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O83pSVL5rSb8_bU8Kwz:-O83pSVL5rSb8_bU8Kx-:b-y416td) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea670072c14922bddddb3f8146bd13042b07a88/pkg/sql/opt/xform/testdata/rules/select#L3032)):*
> ```
>       │    └── union spans
>       │         ├── [Arr/{}, Arr/{}]
>       │         └── [???, ???)
> ```

Any idea what's up with the question marks here?

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/testdata/rules/select` line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O83pSVL5rSb8_bU8Kwz:-O8CNL3b92WXMwo8mRWq:b-hhyo7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea670072c14922bddddb3f8146bd13042b07a88/pkg/sql/opt/xform/testdata/rules/select#L3032)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Any idea what's up with the question marks here?
</blockquote></details>

Those were encoded keys that ended with the `Arr` marker. In an encoded key this marker is usually followed by a value(s), but in inverted spans it sometimes is not followed by a value in order to scan all non-empty arrays. For example the inverted index keys for `ARRAY[11, 33]` would be `..Table/Index/Arr/11/pk` and `..Table/Index/Arr/33/pk`. In order to scan all non-empty arrays in the index, the start key would be `../Table/Index/Arr/`.

I've updated the pretty printer to correctly recognize these cases. I also discovered a bug while I looked into this - see the first commit which is new.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 14 of 14 files at r3, 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131607)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/util/encoding/encoding.go` line 902 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O8EJeHp2LgRRqYfvepz:-O8EJeHp2LgRRqYfveq-:bmlu1ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/82dd33e8c57cb7ecd082e0c003262cfd6b776508/pkg/util/encoding/encoding.go#L902)):*
> ```Go
> 			outBytes = outBytes + "Arr/"
> 			if i+2 >= len(tempB) {
> 				// The key encodes a non-empty JSON array.
> ```

Is this meant to be "empty" instead of "non-empty"?
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O83pSVL5rSb8_bU8Kwz:-O8EIYeS8e95aYmCAWgD:bp2d927) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea670072c14922bddddb3f8146bd13042b07a88/pkg/sql/opt/xform/testdata/rules/select#L3032)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Those were encoded keys that ended with the `Arr` marker. In an encoded key this marker is usually followed by a value(s), but in inverted spans it sometimes is not followed by a value in order to scan all non-empty arrays. For example the inverted index keys for `ARRAY[11, 33]` would be `..Table/Index/Arr/11/pk` and `..Table/Index/Arr/33/pk`. In order to scan all non-empty arrays in the index, the start key would be `../Table/Index/Arr/`.

I've updated the pretty printer to correctly recognize these cases. I also discovered a bug while I looked into this - see the first commit which is new.
</blockquote></details>

There are still question marks in some of these start spans, something to do with that last `\xff` byte? Looks like that's `escaped00`. It seems orthogonal to this PR, though.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131607)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/util/encoding/encoding.go` line 902 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O8EJeHp2LgRRqYfvepz:-O8JEBm39oSleH-x_GZy:bqf0wmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/82dd33e8c57cb7ecd082e0c003262cfd6b776508/pkg/util/encoding/encoding.go#L902)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is this meant to be "empty" instead of "non-empty"?
</blockquote></details>

If the key ends in this, it is used for spanning all non-empty arrays, e.g., if the start of the span ends in `escapedJSONArray` then anything greater than it (to some end point) will be a non-empty array. Empty JSON arrays use a marker distinct from `escapedJSONArray`. I updated the comment to clarify.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O83pSVL5rSb8_bU8Kwz:-O8JE33L2D8rnL_Rt-qL:b-1515h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea670072c14922bddddb3f8146bd13042b07a88/pkg/sql/opt/xform/testdata/rules/select#L3032)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

There are still question marks in some of these start spans, something to do with that last `\xff` byte? Looks like that's `escaped00`. It seems orthogonal to this PR, though.
</blockquote></details>

Good catch. This represents an escaped null byte. I wasn't sure the best way to visually represent it, but I went with `-` for now.

**Review by DrewKimball — APPROVED** [review]
Thanks, :lgtm:

> Reviewed 21 of 21 files at r5, 21 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-:-O8JFC3Q2ihkGMJEPdb5:bh3f2ni)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
*[`pkg/sql/opt/xform/testdata/rules/select` line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131607#-O83pSVL5rSb8_bU8Kwz:-O8JFv6350NC7LY3D8jn:b-keycsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea670072c14922bddddb3f8146bd13042b07a88/pkg/sql/opt/xform/testdata/rules/select#L3032)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good catch. This represents an escaped null byte. I wasn't sure the best way to visually represent it, but I went with `-` for now.
</blockquote></details>

Hmm, actually the `-` character is confusing because in some places it is a separator between the start and end of a span. I think I'll just print no characters in this case, which has one unfortunate side effect of being printed as `""` in some cases. I think this is ok for now though.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
