### PR TITLE
sql: only register the session if it's not internal

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes an oversight of the session registry as well as the
closed session cache (observability tools) where we were erroneously
registering the internal sessions too.

Release note: None (no release with this bug)

### CODE REVIEW

**Comment by rafiss** [comment]
I feel that this was working as intended. I think it's useful for internal exec sessions to be shown in o11y interfaces, since they can have real performance impacts on the cluster.

But the "Release note: None (no release with this bug)" implies that this is new behavior. Do you know the background here?

**Comment by yuzefovich** [comment]
> But the "Release note: None (no release with this bug)" implies that this is new behavior. Do you know the background here?

Initially, I saw that some of the things (namely the closed session cache) this PR is removing were introduced in #78650 for the observability tooling, and I assumed that all of them were. That was incorrect though as the session registry was introduced way back in 2017 when the conn executor was created. So it looks like at least the session registry should not be removed.

Then the question is for the SQL O11y team - @kevin-v-ngo @maryliag - was it intentional that we include the "internal" sessions into the closed session cache?

**Comment by kevin-v-ngo** [comment]
To provide context, we received external user feedback that showing ‘internal’ SQL activity was confusing and cluttered the UI. Internal users then provided feedback that ‘internal’ SQL activity can be critical for debugging purposes as they can impact the cluster. The ideal experience we decided for was including ‘internal’ SQL Activity in the UI but hiding it by default.

However, we had to remove ‘internal’ SQL activity in the UI altogether due to scale (perf/volume) issues with the Statement/Transaction pages querying persisted statistics. The fix for this limitation is tracked under the Obs service. To be consistent in the console, we decided to hide all 'internal' SQL activity. For instance, avoid broken navigation from Sessions -> Transactions -> Statements with internal activity. 

So ideally, no issues with still capturing internal SQL activity in our crdb_internal tables (closed session cache?). It's the UI that we are temporarily filtering out internals with the intention of adding it back in the future.

**Comment by yuzefovich** [comment]
I see, thanks for the context. Then it seems like there is nothing to do.

**Pull request closed without merging**
