### PR TITLE
vendor: Bump pebble to 481920c693f14e0926064e8c7c3f89eea728ae8f

### PR DESCRIPTION
**Pull request by itsbilal**
Commits of note:
  * internal/arenaskl: remove extValueThreshold detritus
  * db: add flushableEntry which wraps a flushable
  * db: better ingestion heuristic
  * db: fix WAL replay in read-only mode
  * db: properly lock compaction picking and ingestion
  * internal/cache: move the bulk of allocations off the Go heap
  * internal/cache: explicitly manage Cache lifetime
  * sstable: Unset external format version for self-made SSTs

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM, though this bump is going to require some more effort due to the Pebble cache lifetime change. We have to be strict about unreferencing the Pebble cache. I started pulling on this thread earlier, but probably won't get it finished for a day or two. It is possible this only affects `COCKROACH_STORAGE_ENGINE=pebble make test`. I suppose CI will tell us soon.

**Comment by petermattis** [comment]
Yep, CI failure has `pebble: cache (0xc0001f80f0) has non-zero reference count: 1`. This is what needs to be fixed. I'm happy to take on this bumpage given that I'm the cause of this new requirement.

**Comment by itsbilal** [comment]
Sounds good. Take it away; and let me know if you want me to do some of that work.

**Comment by petermattis** [comment]
> Sounds good. Take it away; and let me know if you want me to do some of that work.

The work should mostly be mechanical (build with the "invariants" tag, track down misbehaving test). I'm going to create a new PR cause I want to grab an additional Pebble commit.

**Pull request closed without merging**
