### PR TITLE
sql, builtins: implement format

### LINKED ISSUE #68330: sql: implement `format()` builtin
**Describe the problem**

Using the format function in any query doesn't work.

**To Reproduce**

Use `format()`

**Expected behavior**
To work.

**Additional data / screenshots**
https://www.postgresql.org/docs/9.3/functions-string.html#FUNCTIONS-STRING-FORMAT

**Environment:**
 - CockroachDB version 21.1
 - Server OS: macOS 11.4

*Workaround*

I'm using the replace function, but using it with more than 1 argument becomes tedious.

Jira issue: CRDB-8990

### PR DESCRIPTION
**Pull request by HonoreDB**
Closes https://github.com/cockroachdb/cockroach/issues/68330.

Unfortunately hooking into fmt by implementing the Formatter interface
doesn't give us the postgres-style syntax, so instead I've
implemented my own very stripped-down version of fmt by
copying golang's.

Release note (sql change): Added the format builtin function. format interpolates arguments into a string in the style of C's sprintf. For example, format('Hello, %s', 'world') returns 'Hello, world'.

### CODE REVIEW

**Comment by HonoreDB** [comment]
Need to fix the logic tests, they need escaping I think. And ideally add some sqlsmith tests to check that all types work as expected (ideally `%L` is roundtrippable).

**Comment by HonoreDB** [comment]
This is ready for a look.

**Review by rafiss — CHANGES_REQUESTED** [review]
very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-:-N6u4pqv9bJ124Ib-mMw:biokytv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tOHLiDSIF25p0xfIf):*
nit: needs newlines here
___
*[`pkg/sql/sem/builtins/format.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tPhds8c8_PTj6ywK6:-N6tPhds8c8_PTj6ywK7:ba18dq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L62)):*
> ```Go
> 	p := pp{
> 		ctx: ctx,
> 		buf: ctx.FmtCtx(tree.FmtArrayToString),
> ```

have you checked that this is the correct flag to use here?
___
*[`pkg/sql/sem/builtins/format.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tPs_i2ynD_qDn3QCX:-N6tPs_i2ynD_qDn3QCY:b-6u9x45) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L68)):*
> ```Go
> 		return "", err
> 	}
> 	s := p.buf.String()
> ```

this should use `p.buf.CloseAndGetString()` so that the buffer is reset correctly.
___
*[`pkg/sql/sem/builtins/format.go` line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tQOku9vGn5uxAYiAs:-N6tQOkv-mLeIOIy_CUv:bcgz0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L95)):*
> ```Go
> 
> func (p *pp) printArg(arg tree.Datum, verb rune) error {
> 	var writeFunc func(*tree.FmtCtx) int
> ```

nit: perhaps comment here on what the return value of `writeFunc` is
___
*[`pkg/sql/sem/builtins/format.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tQDsO4l3zkrLTo4ZR:-N6tQDsO4l3zkrLTo4ZS:b-dl1t1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L103)):*
> ```Go
> 			return errors.New("NULL cannot be formatted as a SQL identifier")
> 		case 'L':
> 			writeFunc = func(buf *tree.FmtCtx) int { buf.WriteString(nullLiteral); return 4 }
> ```

i'd also be fine to just do `WriteString("NULL")` and remove the `const`, but i'm fine either way
___
*[`pkg/sql/logictest/testdata/logic_test/builtin_function` line 2485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6u4YNyCpGSL3Uvxfai:-N6u4YNzERN6cnU_JR7y:b-jh9hl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/logictest/testdata/logic_test/builtin_function#L2485)):*
> ```
> NULL  NULL
> 
> # Examples from https://www.postgresql.org/docs/9.3/functions-string.html#FUNCTIONS-STRING-FORMAT
> ```

would you mind also adding the tests from their test suite too?

https://github.com/postgres/postgres/blob/4ca9985957881c223b4802d309c0bbbcf8acd1c1/src/test/regress/sql/text.sql#L55

feel free to do it in a new file

**Review by HonoreDB — COMMENTED** [review]
Added a bespoke fuzzer but now realize Matt probably meant hooking into the existing fuzz harness, so I'll add that too. I'll extract this to a new package. Think it would be a good idea to give it a more general name like pgstringfunctions and extract other existing string implementations along with it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-:-N6xQcb55psN6pVxQ3kw:b-to3bdd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/format.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tPhds8c8_PTj6ywK6:-N6xPFLZ3dZ4XoW41ALd:b-kpiosv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

have you checked that this is the correct flag to use here?
</blockquote></details>

In a sense it's definitely not the correct flag because of its name, but since the flag was created to emulate a similar postgres function, it is giving me what I need outside of, ironically, the `('%L', array)` cases. Open to suggestions, though (suspect there should actually be different flags for each of the three verbs (s, I, L)).
___
*[`pkg/sql/sem/builtins/format.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tPs_i2ynD_qDn3QCX:-N6xOzr0DIXvzoDQOE5i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L68)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should use `p.buf.CloseAndGetString()` so that the buffer is reset correctly.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/format.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6tQDsO4l3zkrLTo4ZR:-N6xP0Iz0Hxvt5fdO4eX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/sem/builtins/format.go#L103)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'd also be fine to just do `WriteString("NULL")` and remove the `const`, but i'm fine either way
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/builtin_function` line 2485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N6u4YNyCpGSL3Uvxfai:-N6xP2WX8zXREIYAQILL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6c5d093b4c103df75285d63ddecb743848e4b4/pkg/sql/logictest/testdata/logic_test/builtin_function#L2485)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would you mind also adding the tests from their test suite too?

https://github.com/postgres/postgres/blob/4ca9985957881c223b4802d309c0bbbcf8acd1c1/src/test/regress/sql/text.sql#L55

feel free to do it in a new file
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84107)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/format` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJPpC6BB0Ol_rLS1m:-N7sJPpD7F0o41YnFvAS:ba95y5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L1)):*
> ```
> # LogicTest: !fakedist-spec-planning
> ```

do you know why this configuration needs to be excluded?
___
*[`pkg/sql/logictest/testdata/logic_test/format` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJaDA07T1AyNaAIFu:-N7sJaDA07T1AyNaAIFv:b-yk7214) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L63)):*
> ```
> 
> # Many of the below tests involve strings with a literal $.
> # This can break TestLogic under some conditions. If you're seeing mysterious errors in this file,
> ```

huh, this is actually very surprising. what was breaking with `$`?
___
*[`pkg/sql/logictest/testdata/logic_test/format` line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJwNz2ENib1rTPsrU:-N7sJwNz2ENib1rTPsrV:b-htd8a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L195)):*
> ```
> # This is an error in postgres, but our
> # implementation allows width and position flags
> # to be in either order.
> ```

if it's all the same to our implementation, i'd prefer if we had the same validation as postgres. that is, unless we can find proof that PG had no good reason for doing that validation.
___
*[`pkg/sql/sem/builtins/builtins_test.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sKOr65wFJ4SCMgO2w:-N7sKOr65wFJ4SCMgO2x:b-tr4bec) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/builtins_test.go#L309)):*
> ```Go
> }
> 
> func TestFormatWithWeirdFormatStrings(t *testing.T) {
> ```

can we move this into the pgformat package?
___
*[`pkg/sql/sem/builtins/pgformat/format.go` line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sMKUc3MHha3wX9udz:-N7sMKUc3MHha3wX9ue-:b-8ax05y) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/pgformat/format.go#L166)):*
> ```Go
> 		}
> 		// This is much more permissive than postgres.
> 		dInt, err := eval.PerformCast(ctx, datum, types.Int)
> ```

i think instead this should use the `cast.ValidCast()` function
___
*[`pkg/sql/sem/builtins/pgformat/format.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sN-9R5vjY6J5YP-G1:-N7sN-9R5vjY6J5YP-G2:b-qkaum4) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/pgformat/format.go#L214)):*
> ```Go
> 				}
> 				if argNum >= len(a) {
> 					return errors.New("not enough arguments")
> ```

since this is the pgformat package, can we match the PG error codes as well, using `pgerror.New()`? it seems like PG returns `22023` (invalid parameter value) for all of these

**Review by HonoreDB — COMMENTED** [review]
Keeping it as just the one extracted function for now, as sql/sem/builtins/pgformat. Comments addressed--I've also reworked the %L implementation to give roundtrippable values for arrays.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-:-N8AF0Ax6nKHDDlYXZa8:b-ii00mr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/format` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJaDA07T1AyNaAIFu:-N89t9Uz1HUTJ4-DfOc1:b-lef9jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

huh, this is actually very surprising. what was breaking with `$`?
</blockquote></details>

The tests I added in pkg/sql/logictest/testdata/logic_test/builtin_function needed the $ escaped--it looked like something was replacing them with copies of the query string or something, but I wasn't sure if it was an issue with the test harness (which it looks like does implement $ variables using string replacement as a preprocessor) or the SQL client was interpreting them as placeholders.
___
*[`pkg/sql/logictest/testdata/logic_test/format` line 195 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJwNz2ENib1rTPsrU:-N8ACx0t5hZqWnk-hutT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L195)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if it's all the same to our implementation, i'd prefer if we had the same validation as postgres. that is, unless we can find proof that PG had no good reason for doing that validation.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins_test.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sKOr65wFJ4SCMgO2w:-N8ADEgH2gwKPrVv0hWl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/builtins_test.go#L309)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can we move this into the pgformat package?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/pgformat/format.go` line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sMKUc3MHha3wX9udz:-N8AC0bL-L5DUOXyku7t:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/pgformat/format.go#L166)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think instead this should use the `cast.ValidCast()` function
</blockquote></details>

Makes sense, done.
___
*[`pkg/sql/sem/builtins/pgformat/format.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sN-9R5vjY6J5YP-G1:-N8AC2TxA2S3_Za8HhQM:b-lymhid) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/pgformat/format.go#L214)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since this is the pgformat package, can we match the PG error codes as well, using `pgerror.New()`? it seems like PG returns `22023` (invalid parameter value) for all of these
</blockquote></details>

I'm using `pgerror.Wrap(err, pgcode.InvalidParameterValue` in the builtin definition, which feels a little safer as it can wrap, e.g. cast errors? I could move it to this level if you'd rather.

**Review by rafiss — APPROVED** [review]
looks great, thanks! i did just have one question about the excluded logic test config

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-:-N93DsCXCKraZp3rqYRF:bc3mpy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/format` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJPpC6BB0Ol_rLS1m:-N93CaIzBCTpW39m2dCG:b-p55mnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know why this configuration needs to be excluded?
</blockquote></details>

friendly ping on this
___
*[`pkg/sql/logictest/testdata/logic_test/format` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJaDA07T1AyNaAIFu:-N93Ctq08LTgUNWFNhfb:bvh7o9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L63)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

The tests I added in pkg/sql/logictest/testdata/logic_test/builtin_function needed the $ escaped--it looked like something was replacing them with copies of the query string or something, but I wasn't sure if it was an issue with the test harness (which it looks like does implement $ variables using string replacement as a preprocessor) or the SQL client was interpreting them as placeholders.
</blockquote></details>

If I had to guess, it would be the janky test harness `$var` replacing logic
___
*[`pkg/sql/sem/builtins/pgformat/format.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sN-9R5vjY6J5YP-G1:-N93DlMXDUdzr5qHwH5-:be3davo) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/sem/builtins/pgformat/format.go#L214)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I'm using `pgerror.Wrap(err, pgcode.InvalidParameterValue` in the builtin definition, which feels a little safer as it can wrap, e.g. cast errors? I could move it to this level if you'd rather.
</blockquote></details>

your way makes more sense to me

**Review by HonoreDB — COMMENTED** [review]
Thanks for the review!

___
*[`pkg/sql/logictest/testdata/logic_test/format` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84107#-N7sJPpC6BB0Ol_rLS1m:-N93LW0F08x2pmvduw-p:b-4jk1lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/493d59623020ebf6465590ec9f87bd02cb2573de/pkg/sql/logictest/testdata/logic_test/format#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

friendly ping on this
</blockquote></details>

That was just copypasta, it doesn't need to be excluded (and isn't anymore).

**Comment by HonoreDB** [comment]
bors r=[rafiss]

**Pull request merged**
