### PR TITLE
opt: eliminate trivial Select filters and constrained scans

### LINKED ISSUE #114470: sql: flake in TestTenantLogic_temp_table/create_after_discard_and_drop_database
Seen on seemingly unrelated bors batch [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12685076&buildTypeId=Cockroach_BazelEssentialCi):
```
Failed
=== RUN   TestTenantLogic_temp_table/create_after_discard_and_drop_database
    logic.go:2177: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4937/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/temp_table:395: 
        expected success, but found
        (42P01) relation "pg_temp.t" does not exist
        errors.go:167: in NewUndefinedRelationError()
[02:11:25] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4937/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/temp_table with config 3node-tenant: 89 tests, 1 failures
    --- FAIL: TestTenantLogic_temp_table/create_after_discard_and_drop_database (0.48s)
```

Jira issue: CRDB-33524

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: add rule to generate pseudo partial index scans

This commit adds a new exploration rule, `GeneratePseudoPartialIndexScans`,
which plans partial index scans when the index predicate is implied by
the table's check constraints. This will allow following commits to remove
`SELECT` filters that are implied by the table's check constraints without
introducing plan regressions. Not that this isn't expected to be a common
case, but has arisen in tests.

Informs #114470

Release note: None

#### opt: add rule to eliminate trivial Select filters

This patch adds a new normalize rule, `EliminateTrivialFilter`, which
attempts to prove that a Select filter is trivial using check constraints
when the input is a table scan. This can avoid the need for extra work
evaluating the filter, and may allow other optimizer rules to match.

Informs #114470

Release note: None

#### opt: revert the reversion for the trivial constrained scan fix

This patch reverts the revert of `45b8d05` because the previous commit
fixes the flaking test that motivated the revert. The flakes seem to have
been due to a regression introduced by `45b8d05` in the case of a trivial
explicit filter (as opposed to a generated "optional" filter). Before
`45b8d05`, generating a constrained scan with that filter would effectively
remove the `Select` operator even though the constraint wasn't selective.
After `45b8d05`, the `Select` would remain. This slightly increased the
latency for an internal query that inserts into the `system.span_count`
table, which could cause (or increase) contention on that table.
This apparently caused the `temp_table` logic test to flake by preventing
or slowing the creation and cleanup of tables.

Fixes #114470

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
Looks pretty close, just the test failure needs to be resolved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-:-NkHBMVY4671PXoDb1GG:b-p38c9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/norm/select_funcs.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH5svD2Gimo0ToW5GL:-NkH5svEEeTa0VFBGJ1A:btx4y32) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L430)):*
> ```Go
> // FilterIsTrivial returns true if the given filter is implied by the table's
> // check constraints. This is best-effort, so false negatives are possible.
> func (c *CustomFuncs) FilterIsTrivial(item *memo.FiltersItem, scanPrivate *memo.ScanPrivate) bool {
> ```

super nit: s/FilterIsTrivial/IsFilterTrivial
___
*[`pkg/sql/opt/norm/rules/select.opt` line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH7v_A8tUfzhBElWiU:-NkH7v_BEaSO4cvo9UUL:b-d2y7al) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/rules/select.opt#L456)):*
> ```
> # because check constraints are static guarantees about the table's rows, rather
> # than filters that are applied to them.
> [EliminateTrivialFilter, Normalize]
> ```

It looks like there's a test failure in TestLogic_enums/regression_63138 that may be a bad interaction with this new rule (in case you haven't looked into it yet). Maybe a chicken and egg problem where we're removing a filter because of the constraint on the index being added?
___
*[`pkg/sql/opt/norm/testdata/rules/select` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH72RZ-vWl7Yptmjzu:-NkH72RZ-vWl7Yptmjzv:b-s5yljt) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/testdata/rules/select#L33)):*
> ```
>   b INT NOT NULL,
>   c INT,
>   CHECK (a = 5),
> ```

Should we test a more complex constraint, i.e., involving 2 variables?

**Review by mgartner — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/select_funcs.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrH9jDEgQMfo0dv41J:-NkrH9jDEgQMfo0dv41K:begq0ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L430)):*
> ```Go
> // FilterIsTrivial returns true if the given filter is implied by the table's
> // check constraints. This is best-effort, so false negatives are possible.
> func (c *CustomFuncs) FilterIsTrivial(item *memo.FiltersItem, scanPrivate *memo.ScanPrivate) bool {
> ```

Can you come up with a better name for this function? "Trivial" doesn't naturally imply a tautology nor a contradiction. Maybe `IsFilterImpliedByConstraints` or something?
___
*[`pkg/sql/opt/norm/select_funcs.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrHF7J86kuJHfnxkrO:-NkrHF7J86kuJHfnxkrP:b-7030jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L442)):*
> ```Go
> 	// Check whether any of the table's check constraints implies the filter.
> 	checkConstraintFilters := c.CheckConstraintFilters(scanPrivate.Table)
> 	for i := range checkConstraintFilters {
> ```

Drive-by thought: I wonder if we could use `partialidx.Implicator` here instead. It might be more expensive, but it might cover some cases where the constraints aren't tight on the entire filter. No need to change this, but wanted to mention it.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrHWaUAinCk0pmi_zA:-NkrHWaUAinCk0pmi_zB:b-t5okop) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L502)):*
> ```Go
> // Similarly, the secondary index could also be used. All such index scans
> // will be added to the memo group.
> func (c *CustomFuncs) CheckConstraintFilters(tabID opt.TableID) memo.FiltersExpr {
> ```

nit: you could put this in `norm/general_funcs.go` since it'd used in various places in `xform` too.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrJAd4-AALcTT3GJ85:-NkrJAd4-AALcTT3GJ86:b-5xqshb) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e23d9339ade6b9ba308e0d92937736ea39bd92/pkg/sql/opt/norm/select_funcs.go#L445)):*
> ```Go
> // table's check constraints. This is best-effort, so false negatives are
> // possible.
> func (c *CustomFuncs) ConstraintIsTrivial(
> ```

nit: ditto, is there a better name?
___
*[`pkg/sql/opt/norm/rules/select.opt` line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrH4smD0FBgr0RVEQ_:-NkrH4smD0FBgr0RVEQa:b-fgtefk) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/rules/select.opt#L456)):*
> ```
> # because check constraints are static guarantees about the table's rows, rather
> # than filters that are applied to them.
> [EliminateTrivialFilter, Normalize]
> ```

Ditto regarding the use of "trivial" here.

**Review by DrewKimball — COMMENTED** [review]
Thanks for the reviews! I'm sorry I took so long to return to this. I ended up adding a simple rule in the (now) first commit, in order to fix the logictest failure.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-:-Nr8xk_z45BRRK7a7kID:bi48qfq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/norm/select_funcs.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH5svD2Gimo0ToW5GL:-Nr7LFgT1Ecrq0Qim-0r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L430)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

super nit: s/FilterIsTrivial/IsFilterTrivial
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 430 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrH9jDEgQMfo0dv41J:-Nr7LG7Q421nPvSzUsrx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L430)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you come up with a better name for this function? "Trivial" doesn't naturally imply a tautology nor a contradiction. Maybe `IsFilterImpliedByConstraints` or something?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrHF7J86kuJHfnxkrO:-Nr7MedvC5xXAiJy3F6U:br26dhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L442)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Drive-by thought: I wonder if we could use `partialidx.Implicator` here instead. It might be more expensive, but it might cover some cases where the constraints aren't tight on the entire filter. No need to change this, but wanted to mention it.
</blockquote></details>

Good idea, I opened an issue and added a TODO that references it.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrHWaUAinCk0pmi_zA:-Nr7N1TA18VFZmFjhzUJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/select_funcs.go#L502)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could put this in `norm/general_funcs.go` since it'd used in various places in `xform` too.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/select_funcs.go` line 445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrJAd4-AALcTT3GJ85:-Nr7MdhK17el7SEUQWS6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01e23d9339ade6b9ba308e0d92937736ea39bd92/pkg/sql/opt/norm/select_funcs.go#L445)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: ditto, is there a better name?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/rules/select.opt` line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkrH4smD0FBgr0RVEQ_:-Nr7OSG575_M67LJ8RIc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/rules/select.opt#L456)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ditto regarding the use of "trivial" here.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/rules/select.opt` line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH7v_A8tUfzhBElWiU:-Nr8wPJ18a_-Ybse1E5f:bndiikc) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/rules/select.opt#L456)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It looks like there's a test failure in TestLogic_enums/regression_63138 that may be a bad interaction with this new rule (in case you haven't looked into it yet). Maybe a chicken and egg problem where we're removing a filter because of the constraint on the index being added?
</blockquote></details>

Yeah, it's an internal query that's failing. I solved this by adding a rule `GeneratePseudoPartialIndexScans`, which attempts to plan partial-index scans when the partial index expression is implied by the table's constraints.
___
*[`pkg/sql/opt/norm/testdata/rules/select` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NkH72RZ-vWl7Yptmjzu:-Nr8wq5q58_I4TxCUNkK:bl72m4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/79bba8b5e08fed7c01b67b176d75fb3c114ec0e8/pkg/sql/opt/norm/testdata/rules/select#L33)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we test a more complex constraint, i.e., involving 2 variables?
</blockquote></details>

Great idea. This actually highlighted that I missed an opportunity - we can check if _any_ `constraint.Constraint` in a check constraint's `constraint.Set` implies the filters, rather than requiring that there be only one `Constraint` present. I've added handling for that case, as well as some tests.

**Review by mgartner — COMMENTED** [review]
:lgtm:

> Reviewed 14 of 14 files at r3, 4 of 4 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-:-NrC-n8R5MzeBEqWp6zS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/norm/general_funcs.go` line 1254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NrBd-D39ZHSfWDjxLXh:-NrBd-D39ZHSfWDjxLXi:by97xwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/19bb678143e318ac615308cee0410ea0b6e36186/pkg/sql/opt/norm/general_funcs.go#L1254)):*
> ```Go
> // indexes to be constrained and used. Consider the following example:
> //
> // CREATE TABLE abc (
> ```

nit: I think you'll be able to get the formatting you want here if you indent this first like by an additional space.

update: Oh I see this function is copied. No need to fix it here then. I don't think this function needed to be move in this commit, though I see it does need to be moved in the second commit.
___
*[`pkg/sql/opt/xform/testdata/rules/scan` line 1388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/114790#-NrC-ChB5UBP5hUn7mNt:-NrC-ChB5UBP5hUn7mNu:bpgrjf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3be99e98ebf48c34572cdf3d271acfaec91d57fb/pkg/sql/opt/xform/testdata/rules/scan#L1388)):*
> ```
>       ├── b:2 > 5 [outer=(2), constraints=(/2: [/6 - ]; tight)]
>       ├── (d:4 > 5) AND (e:5 = 5) [outer=(4,5), constraints=(/4: [/6 - ]; /5: [/5 - /5]; tight), fd=()-->(5)]
>       └── (h:8 < 5) OR (h:8 > 5) [outer=(8), constraints=(/8: (/NULL - /4] [/6 - ]; tight)]
> ```

Shouldn't all these filters here and below be eliminated by the new rule in the second commit?

**Comment by DrewKimball** [comment]
Closing this in favor of the much simpler #119505.

**Pull request closed without merging**
