### PR TITLE
opt: various formatting improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change makes the following improvements:

 - variable columns are now shown along with their id in the usual format.

 - expressions that are projection/aggregation/zip/window items now show the
   relevant information, e.g. `[projected as x:1]`; this improves usability when
   looking for projected expression and resolves the hack where window functions
   were sometimes under a `windows-item` node just to show the frame
   information.

 - optbuilder tests now show compact scalars by default (except `build-scalar`).
   Only in the scalar tests we care exactly about how scalars are constructed,
   in all the other cases it is just clutter.

 - the type and !null were controlled by the HideFlags flags; now the !null is
   controlled by a separate formatting flag. We now hide types by default in
   optbuilder (except `build-scalar) / norm / xform tests.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-:-M0s8J6j5skKok27xlhD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s7YxgB5ZX503MUdiV:-M0s7YxgB5ZX503MUdiW:b-isujo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/exec/execbuilder/testdata/explain#L985)):*
> ```
>       │              └── const: 1 [type=int]
>       └── projections
>            └── mult [type=int, outer=(1,2)] [projected as column4:4]
> ```

What about this instead:
```
└── mult [as=column4:4, type=int, outer=(1,2)]
```
Maybe it doesn't stand out enough?
___
*[pkg/sql/opt/memo/expr_format.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s6IWBAI6Qongsld3f:-M0s6IWBAI6Qongsld3g:b-q8fr6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L850)):*
> ```Go
> 
> 	case *ProjectionsExpr, *AggregationsExpr:
> 		// XXX
> ```

NIT: Remove XXX comment

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 986 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s8hR8Ae0BXyO05wZS:-M0s8hR9Ck83B2iR_iKT:b-e5w4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/exec/execbuilder/testdata/explain#L986)):*
> ```
>       └── projections
>            └── mult [type=int, outer=(1,2)] [projected as column4:4]
>                 ├── variable: a:1 [type=int]
> ```

I like it, I'll take a look to see how hard it would be to add.

**Review by rytaft — APPROVED** [review]
:lgtm: Nice improvements!!

Seems like there are several places where `[projected as ...]` is not included -- I think it would be good to include it everywhere, similar to `[aggregated as ...]`

> Reviewed 179 of 179 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-:-M0sCqgE1ah9AU0RbX2m:bmilxqv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/memo/expr_format.go, line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s4PxY2cc0Zlpy0Vh6:-M0s4PxY2cc0Zlpy0Vh7:b-syxzs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3f5aae9d8b058aa54f21040ad32a03ef41e1d6f/pkg/sql/opt/memo/expr_format.go#L1057)):*
> ```Go
> 	case *opt.ColumnID:
> 		fullyQualify := !f.HasFlags(ExprFmtHideQualifications)
> 		if f.Memo != nil {
> ```

do you want to add this check inside `formatCol` so that it won't break for debugging purposes?
___
*[pkg/sql/opt/memo/expr_format.go, line 1089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s4A5918LacHeKpNEz:-M0s4A5918LacHeKpNF-:b-wmo6ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L1089)):*
> ```Go
> 	switch t := private.(type) {
> 	case *opt.ColumnID:
> 		formatCol(f, "" /* label */, *t, opt.ColSet{} /* notNullCols */, true /* omitType */)
> ```

omitType -> omitTypeAndNotNull
___
*[pkg/sql/opt/memo/expr_format.go, line 1093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s4CF77c30QFlZ_FAA:-M0s4CF77c30QFlZ_FAB:b-wmo6ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L1093)):*
> ```Go
> 	case *opt.ColList:
> 		for _, col := range *t {
> 			formatCol(f, "" /* label */, col, opt.ColSet{} /* notNullCols */, true /* omitType */)
> ```

omitType -> omitTypeAndNotNull
___
*[pkg/sql/opt/memo/expr_format.go, line 1226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s3zZC5d0ORwtP4GKe:-M0s3zZC5d0ORwtP4GKf:b-jvj9ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L1226)):*
> ```Go
> 		// Nothing to show; flags are shown separately.
> 
> 	case *ExplainPrivate, *opt.ColSet /*, *opt.ColList*/, *SetPrivate, *types.T, *ExportPrivate:
> ```

this comment got a bit messed up
___
*[pkg/sql/opt/memo/testdata/format, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s57ZU4kvk8Ng5ErCY:-M0s57ZV0EPQNZtiL9ji:b-c3vtnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/testdata/format#L317)):*
> ```
>       │              └── variable: b:2
>       └── projections
>            └── a + 1
> ```

why doesn't this have `[projected as...]`?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/testdata/format, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s57ZU4kvk8Ng5ErCY:-M0sNCJ09O8hQggkwYi3:b-4as1a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/testdata/format#L317)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why doesn't this have `[projected as...]`?
</blockquote></details>

Hm, looks like it's because of the interceptor used to show compact expressions. I will work more on this.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s7YxgB5ZX503MUdiV:-M0tLZ-m3aWGoHiZv7wU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/exec/execbuilder/testdata/explain#L985)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What about this instead:
```
└── mult [as=column4:4, type=int, outer=(1,2)]
```
Maybe it doesn't stand out enough?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/expr_format.go, line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s4PxY2cc0Zlpy0Vh6:-M0tPEYN8lQ_cF05NVxh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3f5aae9d8b058aa54f21040ad32a03ef41e1d6f/pkg/sql/opt/memo/expr_format.go#L1057)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you want to add this check inside `formatCol` so that it won't break for debugging purposes?
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/expr_format.go, line 1089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s4A5918LacHeKpNEz:-M0tP85Z3m_qgS1gWYIB:b-jm1h98) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L1089)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

omitType -> omitTypeAndNotNull
</blockquote></details>

Removed altogether.
___
*[pkg/sql/opt/memo/expr_format.go, line 1226 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0s3zZC5d0ORwtP4GKe:-M0tPaZL3zmnh3xmbFRL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/expr_format.go#L1226)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this comment got a bit messed up
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
Looks like the zip columns disappeared (I thought they were useful). Otherwise, :lgtm: 

> Reviewed 164 of 165 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-:-M0t_NxG69WubI7GODCG:bacafuz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/expr_format.go, line 758 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tTMfdD36wM0NWrk8s:-M0tTMfdD36wM0NWrk8t:bslhxb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/memo/expr_format.go#L758)):*
> ```Go
> 			}
> 			if item.Frame != def {
> 				emitProp("as=%s", f.ColumnString(item.Col))
> ```

Is this redundant with the one above?
___
*[pkg/sql/opt/memo/expr_format.go, line 1025 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tTlFr786GVBPd1B7Q:-M0tTlFsERHRBMAd-tyE:b-ceo3u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/memo/expr_format.go#L1025)):*
> ```Go
> }
> 
> // formatColSimpl outputs the specified column into the context's buffer using the
> ```

Simpl -> Simple
___
*[pkg/sql/opt/memo/testdata/stats/srfs, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tVYGT9RVxjYZEc0XO:-M0tVYGT9RVxjYZEc0XP:b-m2j7yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/testdata/stats/srfs#L28)):*
> ```
>  │    │    │    └── tuple [type=tuple]
>  │    │    └── zip
>  │    │         ├── const: 'DEF' [type=string] [columns: upper:2]
> ```

did you mean to get rid of the columns listed here and below?
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tXNTG23rEQoKQIT53:-M0tXNTH580eFsKweFU8:bpw37b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L23)):*
> ```
>  │    └── (200, 1)
>  └── f-k-checks
>       └── f-k-checks-item: child(p) -> parent(p) [type=undefined]
> ```

this new type annotation doesn't seem very useful
___
*[pkg/sql/opt/optbuilder/testdata/misc_statements, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tXsuqABTLcyVNrjH4:-M0tXsuqABTLcyVNrjH5:buzegg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/misc_statements#L158)):*
> ```
>  ├── 'nodelocal://foo'
>  └── k-v-options
>       ├── k-v-options-item foo [type=undefined]
> ```

another undefined type annotation
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tZJzZ2n6UMTg7OOlp:-M0tZJzZ2n6UMTg7OOlq:blz7188) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/window#L1447)):*
> ```
>       │    └── columns: k:1!null v:2 w:3 f:4 d:5 s:6 b:7
>       └── windows
>            ├── rank [as=rank:8, as=rank:8, frame="range from unbounded to current-rowexclude current row"]
> ```

yep, looks like it's duplicated

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/memo/expr_format.go, line 758 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tTMfdD36wM0NWrk8s:-M0tgzkb4ua_IhhxGRDe:b-yb5dpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/memo/expr_format.go#L758)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this redundant with the one above?
</blockquote></details>

Done. Also changed these to be conditional on HideColumns (so e.g. they don't show up in `EXPLAIN (OPT)`).
___
*[pkg/sql/opt/memo/expr_format.go, line 1025 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tTlFr786GVBPd1B7Q:-M0th0Pg9X325JO5xVrv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/memo/expr_format.go#L1025)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Simpl -> Simple
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/srfs, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tVYGT9RVxjYZEc0XO:-M0ti2IBBexLne6qN5xF:beq69oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46ee9faa97456084df18e584b66d4f83192a548/pkg/sql/opt/memo/testdata/stats/srfs#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to get rid of the columns listed here and below?
</blockquote></details>

Yeah, it would be a bit of a pain to add them now. I put in a TODO.
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tXNTG23rEQoKQIT53:-M0thAIFDsTPVS9R5M6n:b6kxso7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L23)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this new type annotation doesn't seem very useful
</blockquote></details>

Was a bug, fixed.
___
*[pkg/sql/opt/optbuilder/testdata/misc_statements, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tXsuqABTLcyVNrjH4:-M0thCBoCrclWLYNk8iY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/misc_statements#L158)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

another undefined type annotation
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/window, line 1447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45324#-M0tZJzZ2n6UMTg7OOlp:-M0th2MeDcmwhnUl9iwD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9fd01a27cd4ccb82c9a8333bfd515bfbf34450f/pkg/sql/opt/optbuilder/testdata/window#L1447)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

yep, looks like it's duplicated
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 39 of 39 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45324)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball)

**Pull request merged**
