### PR TITLE
workload: port querybench to workload

### PR DESCRIPTION
**Pull request by solongordon**
querybench runs arbitrary queries from an input file. Since this is a
superset of the 'singlequery' workload, I renamed that to 'querybench'
and added the logic for reading in and running multiple queries. Each
worker just runs the queries sequentially in a loop.

Refers #25011

Release note: None

### CODE REVIEW

**Comment by solongordon** [comment]
Hm, Reviewable didn't detect the file rename. Might be easier to review via the Github diff.

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[pkg/workload/querybench/query_bench.go, line 100 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/25012#-LAoIL0F6e0vkIl3zuUE:-LAoIL0GCOKFvEU9xpRr:b764hn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ee127234c1cf7941ecbe8e12b23216ebf3a9f0d/pkg/workload/querybench/query_bench.go#L100)):*
> ```Go
> 	db.SetMaxIdleConns(g.connFlags.Concurrency + 1)
> 
> 	queries, err := getQueries(g.queryFile)
> ```

any particular reason to do this here instead of in Validate?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/25012#-:-LAoIt3c0Yu1r774nmN7:bnfp4nl)*

**Comment by solongordon** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/workload/querybench/query_bench.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25012#-LAoIL0F6e0vkIl3zuUE:-LAs-DMX41Pfq9_CNMO0:b-6i1ca6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ee127234c1cf7941ecbe8e12b23216ebf3a9f0d/pkg/workload/querybench/query_bench.go#L100)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

any particular reason to do this here instead of in Validate?
</blockquote></details>

Nope! Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25012)*

**Review by asubiotto — APPROVED** [review]

**Pull request merged**
