### PR TITLE
ci: report failure to generate code as a test failure to teamcity

### LINKED ISSUE #78368: ci: failure to run `./dev generate bazel` should be reported as a test failure to TeamCity
[Internal discussion](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1648067978849259)

Currently a failure to run `./dev generate bazel` is reported in TeamCity via the script `build/teamcity/ci/tests/check_generated_code_impl.sh`, specifically via `check_workspace_clean` in `build/teamcity-support.sh`. Currently if there is a failure we just write the message to `stderr` and `exit 1`, but we could log this as a test failure to TeamCity via `##teamcity[testFailed name='%s' details='%s' flowId='%s']"`.

Epic CRDB-8306

Jira issue: CRDB-14093

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #78368.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
See what a failure looks like now: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4666729?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true

Screen Shot 2022-03-24 at 12 22 21 PM

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
