### PR TITLE
engine: Update pebble MVCC scanner to be more in line with CPP impl

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates the pebble MVCC scanner to be more in line with
the C++ implementation in libroach/mvcc.h. This was done because
we are more confident with that implementation, and don't expect
testing to be comprehensive enough to catch minor-yet-consequential
bugs in this part of the code.

Most major changes involve implementing the ability to "peek" the
previous key without changing the current key, as well as returning
iterator validity as a bool in almost all helper functions.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Looking at this side-by-side with the C++ I noticed two differences pretty quickly:
1. The lack of `addAndAdvance`.
2. The different ordering of the methods.

The second bit makes doing a side-by-side comparison more difficult than it should be. Can you add a commit which just reorders the methods in `pebble_mvcc_scanner.go` to match the ordering in `libroach/mvcc.h`?

There are a handful of additional comments below, but I'll wait on doing a further review into the method ordering matches. Note that I don't particularly care about the method ordering in the C++ code, just about making this code easier to review in a side-by-side manner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsJHVPX8NnB7KgJGS9C:b-skt505)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIvyP_-SH6VWbahQGe:-LsIvyP_-SH6VWbahQGf:b-g0d0v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L166)):*
> ```Go
> func (p *pebbleMVCCScanner) scan() {
> 	if p.reverse {
> 		p.seekReverse(p.end)
> ```

You can return early here: `if !p.seekReverse() { return }`.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIw6Wj6IeK1ovS1pA3:-LsIw6Wj6IeK1ovS1pA4:bpqi7v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L171)):*
> ```Go
> 	}
> 
> 	for p.results.count < p.maxKeys && p.getAndAdvance() {
> ```

The C++ code looks like `for p.getAndAdvance()`. Why is this checking `p.results.count`?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIwgUj6rcepQj9z-qc:-LsIwgUkCaALOeYm7IeE:b-izgdor) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L174)):*
> ```Go
> 	}
> 
> 	if p.results.count < p.maxKeys || p.err != nil || !p.parent.Valid() {
> ```

The C++ code looks different here. If we filled up to `p.maxKeys`, we need to advance one more time to find the resume key. Seems like this may partially be done in `pebbleIterator.MVCCScan`, but I'm not sure. Seems better to encapsulate the logic here.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIx8R_8_ZfUnt4-F4M:-LsIx8R_8_ZfUnt4-F4N:b-l17ozn) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L187)):*
> ```Go
> func (p *pebbleMVCCScanner) get() {
> 	p.keyBuf = EncodeKeyToBuf(p.keyBuf[:0], MVCCKey{p.start, hlc.Timestamp{}})
> 	p.parent.SeekPrefixGE(p.keyBuf)
> ```

This can be `if !p.parent.SeekPrefixGE(...) { return }`.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsJHQOMB8XQqFtQ7aIV:-LsJHQOMB8XQqFtQ7aIW:b-yzxpy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L492)):*
> ```Go
> // iteration can continue.
> func (p *pebbleMVCCScanner) getAndAdvance() bool {
> 	if !p.parent.Valid() {
> ```

This check shouldn't be necessary if you get all of the early returns right. The C++ code doesn't have it.

**Review by itsbilal — COMMENTED** [review]
`addAndAdvance` is basically `if p.ts != (hlc.Timestamp{}) { p.addKV(p.curRawKey, p.curValue) } return advanceKey()` which you see in `seekVersion`. I had inlined it since it was only called there, but I've pulled it into its own method now. Also reordered methods.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsMzTRj-G7pVzrTbwMj:b-9qzkkw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIvyP_-SH6VWbahQGe:-LsN2IZ83W5euhYVYu3W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L166)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can return early here: `if !p.seekReverse() { return }`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIw6Wj6IeK1ovS1pA3:-LsN-Ul66EK7k1fwZQ8C:bkemhuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L171)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The C++ code looks like `for p.getAndAdvance()`. Why is this checking `p.results.count`?
</blockquote></details>

Not all paths (eg the ones where we unwrap intents, or the fast path in getAndAdvance) do a `count` check, even in the C++ code (see how `getFromIntentHistory` is being used). So I brought this check out here instead to enforce it better and to check it in just one place.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIwgUj6rcepQj9z-qc:-LsN1mBL5Yj7awTdEwMo:b-8fehxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L174)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The C++ code looks different here. If we filled up to `p.maxKeys`, we need to advance one more time to find the resume key. Seems like this may partially be done in `pebbleIterator.MVCCScan`, but I'm not sure. Seems better to encapsulate the logic here.
</blockquote></details>

The difference between the C++ code and our code here is that we always `advanceKey` in the go code, even if we've hit `maxKeys`. So `curKey` is already at the next key, and MVCCScan can just copy it into the resumeSpan.

The special case code in `MVCCScan` around reverse scanning is only to ensure that `curKey` is less than the end bound of the span.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsIx8R_8_ZfUnt4-F4M:-LsN2D4z1htgzSUXn8jO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L187)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This can be `if !p.parent.SeekPrefixGE(...) { return }`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsJHQOMB8XQqFtQ7aIV:-LsN2JUAESKXsfm-KDFw:b-rwbt2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/80c4bc2d9596fee982f199e244931326665b1c3d/pkg/storage/engine/pebble_mvcc_scanner.go#L492)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This check shouldn't be necessary if you get all of the early returns right. The C++ code doesn't have it.
</blockquote></details>

Done. Wasn't firing anyway.

**Review by petermattis — APPROVED** [review]
:lgtm:

I'm still scrutinizing this side-by-side with the C++ code, but this PR is a large step to making them uniform and I think it can merge now while I continue the scrutinization.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsRPneUCYSsKRcze0g_:b-hz99n3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsRPYnQBICRx09Q5ZPI:-LsRPYnQBICRx09Q5ZPJ:b-m74jsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae62636d53dd5d8073adfc5e51b5995e2ed32c97/pkg/storage/engine/pebble_mvcc_scanner.go#L213)):*
> ```Go
> // Returns an uncertainty error with the specified timestamp and p.txn.
> func (p *pebbleMVCCScanner) uncertaintyError(ts hlc.Timestamp) error {
> 	if ts.WallTime == 0 && ts.Logical == 0 {
> ```

The C++ code doesn't do these checks. Were they necessary for some reason?

**Review by itsbilal — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsS0JqV1XxiBI4fEJ_U:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsRPYnQBICRx09Q5ZPI:-LsS0M568wSD8jb-5HYt:b-j1x9bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae62636d53dd5d8073adfc5e51b5995e2ed32c97/pkg/storage/engine/pebble_mvcc_scanner.go#L213)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The C++ code doesn't do these checks. Were they necessary for some reason?
</blockquote></details>

Nope, there's no reason for them. Removed.

**Review by sumeerbhola — COMMENTED** [review]
sorry about the late comments/questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsSj1jo7NJCH7btQN9c:b7exkj0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSaI_y36mSwAUXYBl6:-LsSaI_y36mSwAUXYBl7:b-vrbsyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L162)):*
> ```Go
> 	}
> 
> 	if p.results.count < p.maxKeys || p.err != nil || !p.parent.Valid() {
> ```

do we have tests that cover iterator error handling?
(in a previous setting I found that to be the biggest source of bugs because files being iterated were remote and there were cancellation caused errors that needed to be correctly propagated)
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSd64A1NUWO1f5ZFHN:-LsSd64A1NUWO1f5ZFHO:bigevxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L300)):*
> ```Go
> 	if p.inconsistent {
> 		// 6. The key contains an intent and we're doing an inconsistent
> 		// read at a timestamp newer than the intent. We ignore the
> ```

it seems we are here because the previous if-condition was not true, so `maxVisibleTS >= metaTS || ownIntent` is true. The comment talks about `maxVisibleTS >= metaTS` but not the `ownIntent` case. Can we say something about that?

Also, if `maxVisibleTS >= metaTS` is it possible that `p.ts < metaTS` -- why don't we do stuff related to `checkUncertainty` here --- I am assuming that is because this intent corresponds to an uncommitted transaction so it could not have committed before this transaction. But don't we also encounter intents that have committed but not yet cleaned up. Is the uncertainty checking on intents happening at a higher level in the code? 
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSdjrBENVZvFuQxDn7:-LsSdjrBENVZvFuQxDn8:biy38p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L309)):*
> ```Go
> 			// we're adding the resume key. We don't want to add the
> 			// intent here as the intents should only correspond to KVs
> 			// that lie before the resume key.
> ```

I didn't quite understand what invariants must be satisfied by resumption points -- is there something I should read?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSgZTmCZ9yQSgmqlJc:-LsSgZTmCZ9yQSgmqlJd:bz9ax57) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L339)):*
> ```Go
> 			// as the intent timestamp may have been pushed forward by another
> 			// transaction. Txn's always need to read their own writes.
> 			return p.seekVersion(metaTS, false)
> ```

if the read timestamp was 5 and the intent timestamp is 10 and this causes us to start reading from 10 won't we pick up a different transaction write that happened at 7 so the reads of this transaction are no longer consistent.
It is possible that my mental model is broken: I assumed all reads of a transaction (even if was pushed) happen at the timestamp of the first read (except for also wanting to see its own writes) to ensure consistent reads. Is that correct?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsShzhD0k-cqZ1xYp1A:-LsShzhD0k-cqZ1xYp1B:bjq7rau) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L358)):*
> ```Go
> 		// timestamp we're reading at is a historical timestamp < the intent
> 		// timestamp.
> 		return p.seekVersion(prevTS, false)
> ```

similar example:
the read timestamp was 5 and the intent timestamp was 10 but there was nothing in the intent lower than the sequence number of the read (btw, I don't know why a transaction could be reading at a lower sequence number than previous intents -- is it because of intra-transaction parallelism?), then we read from 9 onwards?
(I'm oversimplifying HLC(10).Prev() to be 9)

**Review by itsbilal — COMMENTED** [review]
No worries! I answered most of your questions that I knew the answers to. The last two are going to require some reading from me as well.

For correctness purposes, `seekVersion` here in the pebble scanner has always closely matched the C++ version in `mvcc.h` in terms of implementation. Not sure if that helps understand it better, but it does lend confidence.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-:-LsXC9DS8-4nDH2aYuyw:beceoa)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSaI_y36mSwAUXYBl6:-LsX9PiCEONsoEEW4SHA:b-nwellk) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L162)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we have tests that cover iterator error handling?
(in a previous setting I found that to be the biggest source of bugs because files being iterated were remote and there were cancellation caused errors that needed to be correctly propagated)
</blockquote></details>

Good point - and not as far as I know. We already test things like uncertainty errors generated by the MVCC code itself, but not errors coming from underneath the iterator.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 300 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSd64A1NUWO1f5ZFHN:-LsX9kqr5V-dpJCmdLmm:b-dlxwjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L300)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

it seems we are here because the previous if-condition was not true, so `maxVisibleTS >= metaTS || ownIntent` is true. The comment talks about `maxVisibleTS >= metaTS` but not the `ownIntent` case. Can we say something about that?

Also, if `maxVisibleTS >= metaTS` is it possible that `p.ts < metaTS` -- why don't we do stuff related to `checkUncertainty` here --- I am assuming that is because this intent corresponds to an uncommitted transaction so it could not have committed before this transaction. But don't we also encounter intents that have committed but not yet cleaned up. Is the uncertainty checking on intents happening at a higher level in the code? 
</blockquote></details>

Good point, we probably should say something about it. Basically `p.inconsistent` implies `p.txn == nil` (otherwise `MVCCScan` would have short-circuited a long time ago), so we're guaranteed to have `ownIntent` as false.

I'm also pretty sure (though someone can correct me on this) that checkUncertainty is supposed to only be returned with consistent reads, so we don't need to address it here.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSdjrBENVZvFuQxDn7:-LsXAvTB2uPuJ7oo3NNY:b2g84ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L309)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't quite understand what invariants must be satisfied by resumption points -- is there something I should read?
</blockquote></details>

I don't think there's any single good place with documentation on this, but the point about resumption keys is that we should never stop/resume between multiple MVCC versions of the same `roachpb.Key`.  You'll notice that the `resumeSpan` is defined as `roachpb.Key` and not `MVCCKey`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSdjrBENVZvFuQxDn7:-LsXUgcA7mYWCv8rGeKJ:beaxs1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L309)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I don't think there's any single good place with documentation on this, but the point about resumption keys is that we should never stop/resume between multiple MVCC versions of the same `roachpb.Key`.  You'll notice that the `resumeSpan` is defined as `roachpb.Key` and not `MVCCKey`. 
</blockquote></details>

The resume key is simply the next key that would be reached during iteration. The invariant is that it must be the next key (or prev for reverse iteration). It can't be one of the keys being returned, and there can't be a gap.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsSgZTmCZ9yQSgmqlJc:-Lsc2x10DXU2E12pS-Gx:b-5h2qxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if the read timestamp was 5 and the intent timestamp is 10 and this causes us to start reading from 10 won't we pick up a different transaction write that happened at 7 so the reads of this transaction are no longer consistent.
It is possible that my mental model is broken: I assumed all reads of a transaction (even if was pushed) happen at the timestamp of the first read (except for also wanting to see its own writes) to ensure consistent reads. Is that correct?
</blockquote></details>

I took another look and it seems that we know that we will find our intent when we read at the intent timestamp, and then `seekVersion()` will move to the next user key. And when reading our own intents we don't want to add them to `p.intents`. Is this correct?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsShzhD0k-cqZ1xYp1A:-Lsc8BC84GlkJ5hBuFO_:b-qjd6eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L358)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

similar example:
the read timestamp was 5 and the intent timestamp was 10 but there was nothing in the intent lower than the sequence number of the read (btw, I don't know why a transaction could be reading at a lower sequence number than previous intents -- is it because of intra-transaction parallelism?), then we read from 9 onwards?
(I'm oversimplifying HLC(10).Prev() to be 9)
</blockquote></details>

I think `metaTS >= p.ts`.
- when `metaTS == p.ts`, `prevTS = metaTS.Prev()`, which is also `p.ts.Prev()`. So seeking there will give us the latest value `< p.ts`. This is correct.
- when `metaTS > p.ts`, `prevTS = p.ts`. Since the intents laid down by this transaction were at `metaTS`, by seeking to `p.ts` we will skip those. What happens if there are many versions written by this txn, and one of those versions was at `p.ts` before the transaction was pushed? `MVCCMetadata.Timestamp` says "The timestamp of the most recent versioned value", so based on that it seems we could erroneously read a higher sequence number value written by the same transaction.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsShzhD0k-cqZ1xYp1A:-LscFng18oMbQ50bdWB4:b-iwl3ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L358)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think `metaTS >= p.ts`.
- when `metaTS == p.ts`, `prevTS = metaTS.Prev()`, which is also `p.ts.Prev()`. So seeking there will give us the latest value `< p.ts`. This is correct.
- when `metaTS > p.ts`, `prevTS = p.ts`. Since the intents laid down by this transaction were at `metaTS`, by seeking to `p.ts` we will skip those. What happens if there are many versions written by this txn, and one of those versions was at `p.ts` before the transaction was pushed? `MVCCMetadata.Timestamp` says "The timestamp of the most recent versioned value", so based on that it seems we could erroneously read a higher sequence number value written by the same transaction.

</blockquote></details>

according to @nvanbenschoten  in response to "If the same transaction wrote to a key multiple times and it was pushed between those writes, will the MVCCMetadata.Timestamp represent the most recent timestamp or the oldest or something else?": "It should be the timestamp of the most recent version"

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 520 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LscILRw8_DoAdKGjOcf:-LscEA1BEDGqIeo4vwlJ:b-w70of2) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L520)):*
> ```Go
> 		if !ts.Less(p.curTS) {
> 			p.incrementItersBeforeSeek()
> 			if uncertaintyCheck && p.ts.Less(p.curTS) {
> ```

this part of this function is hard to understand since it is easy to overlook that there are three (not two) timestamps that are relevant to the logic: `p.ts`, `p.curTS`, `ts` and while we are checking `ts >= p.curTS` in deciding whether to use this version, we are using `p.ts` to do the uncertainty check. The immediate thought(s) that comes to mind -- why are we not comparing with `p.txn.MaxTimestamp`, and how would that relate to `ts` to make sure we even see the potential uncertainty when iterating?
Then I looked at the call sites and noticed that the only call with `uncertaintyCheck=true` is called with `ts=MaxTimestamp`. A function level comment would really help.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41960)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41960#-LsShzhD0k-cqZ1xYp1A:-Lsw4P2NCetnfqxKZEcI:bsjg6m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c47889da0fd8f595ef5b7459ed44890c1e13a1/pkg/storage/engine/pebble_mvcc_scanner.go#L358)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

according to @nvanbenschoten  in response to "If the same transaction wrote to a key multiple times and it was pushed between those writes, will the MVCCMetadata.Timestamp represent the most recent timestamp or the oldest or something else?": "It should be the timestamp of the most recent version" 
</blockquote></details>

Nathan mentioned on another thread that there is only one provisional value. That answers this question.

**Pull request merged**
