### PR TITLE
[DNM]: experiment for contending 1PC txns

### PR DESCRIPTION
**Pull request by tbg**
See #15797 for context.

The main problem here are `WriteTooOldError`s, which lay down an intent. If
this happens frequently, performance suffers dramatically since there is almost
always an intent on the key, forcing everyone into conflict resolution (which
is sure to lay down another intent thanks to `WriteTooOld`).

With this change we don't lay down intents for this workload, but the 1PC
transactions could be starved.

We could do even better (making the hack in #15863 correct): If we knew that
the 1PC transaction wasn't previously used for any reads (or it's SNAPSHOT), we
could in theory commit it directly again from the Store (saving the roundtrip
to the gateway/client). If it's SERIALIZABLE and there were previous reads, we
can't simulate a restart internally and the client must do it properly.

It also stands to reason that on a restart, the client shouldn't take the
existing timestamp but simply use `hlc.Now()` which is less stale.

Neither of the last two paragraphs are explored in this PR. Here, we should
discuss whether it's OK to expose 1PC txns to starvation in the first place.

```
go run $GOPATH/src/github.com/cockroachdb/loadgen/kv/main.go --cycle-length 1 --concurrency $c --duration 30s
// this PR, c=10
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   30.0s        0          14905          496.8     16.3     17.8     29.4              0 / 0
// this PR and master, c=1
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   30.0s        0          22204          740.1      1.6      3.5     15.7              0 / 0
// master, c=10
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   30.0s        0           3185          106.2    369.1    604.0   1811.9              0 / 0
```

btw @petermattis, your uncontended numbers in #15797 seemed much faster (than
mine on my laptop). Do you still see the same number and on which system?

### CODE REVIEW

**Comment by tschottdorf** [comment]
My main concern here is that while making 1PC transactions really fast is great, it's going to make it even more surprising to folks who add an index and find that performance drops significantly as they don't get the 1PC path any more.

**Comment by spencerkimball** [comment]
I dislike the idea of optimizing for this case, which I suspect is middling unusual, at the expense of possible starvation. I do like some of the suggestions in the PR description though. In particular, it would be interesting to augment the `EndTransaction` with the keys read during the txn (if 3 or less and serializable let's say). Then, we could either commit despite the write too old error if snapshot or number of keys read is 0. If serializable, and we have the list of keys read, we could ping those keys with a new RPC that instead of reading, verifies and updates the timestamp cache entry. The verification and update is basically a compare and set on the entry's timestamp. If equal to the expected `txn.Timestamp`, would update the entry to the txn commit timestamp; if not equal, then would return an error, leading to a txn rety.

This is definitely non-trivial but depending on how many read keys we're willing to track, could short circuit a lot of serializable retries.

**Comment by bdarnell** [comment]
> I dislike the idea of optimizing for this case, which I suspect is middling unusual, at the expense of possible starvation.

I agree.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17121#-:-KpW8_gZQ3YohFty2tkw:bqhpsfx)*

**Comment by petermattis** [comment]
@tschottdorf My uncontended numbers are right in line with yours. Wonder why it was faster on May 9.

```
~ kv --cycle-length 1 --concurrency 1 --duration 30s
...
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   30.0s        0          23091          769.6      1.4      1.7     10.5              0 / 0
```

**Comment by petermattis** [comment]
Tested with ce9d95dd646ecb4c489233c282cc9484efa0b904 (a commit from May 9th):

```
~ kv --cycle-length 1 --concurrency 1 --duration 30s
...
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   30.0s        0          61102         2036.7      0.7      2.0     11.5              0 / 0
```

That's worth investigating!

**Comment by tschottdorf** [comment]
Wowzers, someone broke something. Will take a look next week (unless you beat me to it, @petermattis).

As for the PR, looks like we all agree that optimizing the 1PC path more is not a good idea. I'll write up some of the learnings in an issue and abandon this PR.

**Comment by petermattis** [comment]
I'm already bisecting. Will know later tonight.

**Comment by petermattis** [comment]
Ah, it's 82cbb49ff7e1db6e1b01d96f1100954b599b6c5f. Specifically, the default 1ms value for `rocksdb.min_wal_sync_interval`. So this result is to be expected when there is no concurrency.

**Comment by tschottdorf** [comment]
Hmm, ok. Is there a lightweight way to make the `1ms` interval adaptive? Single-threaded inserts aren't found in many real-world workloads, but they're probably the first stupid benchmark people run.

**Comment by petermattis** [comment]
> Hmm, ok. Is there a lightweight way to make the 1ms interval adaptive? Single-threaded inserts aren't found in many real-world workloads, but they're probably the first stupid benchmark people run.

Maybe. I haven't thought about it too much. Or we could set the default to 0ms and only use 1ms for benchmarking.

**Comment by tschottdorf** [comment]
Nothing to do here.

**Pull request closed without merging**
