### PR TITLE
cli: push tsdump upload failed metrics to datadog logs

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, we were displaying failed tsdump upload metrics on CLI output. This was inadequate because CLI output might get truncated in case of high number of metric failure. To address this, this patch ships failed metrics to datadog as part of logs so that we can see all failed uploaded metrics as part of logs.

Part of: CRDB-44835
Epic: None
Release note: None

Log snippet:
Screenshot 2024-12-11 at 1 53 10 PM

### CODE REVIEW

**Review by arjunmahishi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137250)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @angles-n-daemons)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpIeNyBSWWMflhTecj:-ODpIeNyBSWWMflhTeck:bjei9d7):*
Last 3 lines got in from the commit message template
___
*[`pkg/cli/tsdump_upload.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpUSKw2CL-octZSSmk:-ODpT7kXDm4BPTSSreCA:b-vkmes2) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L447)):*
> ```Go
> 			fmt.Println("\nPushing failed metrics to datadog logs...")
> 			for metric := range metricsUploadState.uploadFailedMetrics {
> 				wg.Add(1)
> ```

I have not seen a waitGroup being reused before (i.e calling `Add()` again after a `Wait()` call). Have you verified that this works? 
___
*[`pkg/cli/tsdump_upload.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpUUT-CdW-RFKQRW46:-ODpUUT-CdW-RFKQRW47:b89ndnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L449)):*
> ```Go
> 				wg.Add(1)
> 				go func() {
> 					logMessage := fmt.Sprintf(logMessageFormat, metric)
> ```

The `metric` should be passed as an arg to the anonymous function. Or this will have flaky behaviour. Because the it's being read concurrently and the underlying value can be mutated by the for loop. I am surprised this did not get flagged by the linter :thinking: 

```go
for metric := range metricsUploadState.uploadFailedMetrics {
    go func(m type) {
        ...
    }(metric)
}
```

OR I think you can also do this

```go
for metric := range metricsUploadState.uploadFailedMetrics {
    metric := metric // create a locally scoped copy of metric
    go func() {
        ...
    }()
}
```
___
*[`pkg/cli/tsdump_upload.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpVSKcDSFCmXoyt7HW:-ODpVSKcDSFCmXoyt7HX:b-bkz12r) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L474)):*
> ```Go
> 			fmt.Println("Failed to pushed some metrics to datadog logs. Please refer CLI output for all failed metrics.")
> 		} else {
> 			fmt.Println("Pushing failed metrics to datadog logs...done")
> ```

NIT
Something along this line might be more clear



_Suggestion:_
```Go
fmt.Println("Pushing logs of metric upload failures to datadog...done")
```

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137250)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @arjunmahishi)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpIeNyBSWWMflhTecj:-ODpl5Ed6bdamxgwBayU:b-kfcv46):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Last 3 lines got in from the commit message template
</blockquote></details>

Thanks! I missed to remove them.
___
*[`pkg/cli/tsdump_upload.go` line 447 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpUSKw2CL-octZSSmk:-ODplJOb4-GOIuPq4hEr:b-ubvw0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L447)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

I have not seen a waitGroup being reused before (i.e calling `Add()` again after a `Wait()` call). Have you verified that this works?
</blockquote></details>

Yes, I have verified the behaviour in local testing.
___
*[`pkg/cli/tsdump_upload.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpUUT-CdW-RFKQRW46:-ODpm_pG6aWSuubJ3-g8:b8nkx40) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L449)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

The `metric` should be passed as an arg to the anonymous function. Or this will have flaky behaviour. Because the it's being read concurrently and the underlying value can be mutated by the for loop. I am surprised this did not get flagged by the linter :thinking: 

```go
for metric := range metricsUploadState.uploadFailedMetrics {
    go func(m type) {
        ...
    }(metric)
}
```

OR I think you can also do this

```go
for metric := range metricsUploadState.uploadFailedMetrics {
    metric := metric // create a locally scoped copy of metric
    go func() {
        ...
    }()
}
```
</blockquote></details>

Interesting! I didn't notice concurrency issue during my testing. The CLI & datadog line count was matching. However, it makes more sense to pass them as parameter. Thanks!
___
*[`pkg/cli/tsdump_upload.go` line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-ODpVSKcDSFCmXoyt7HW:-ODpn-RX3iuzfMOmQL7p:bb6tyiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/52db9f47ae27a799894db1a1a13eec1fae2e42be/pkg/cli/tsdump_upload.go#L474)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

NIT
Something along this line might be more clear
</blockquote></details>

DONE

**Review by arjunmahishi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137250#-:-ODtNrHr6lL-aMwV3SfJ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons)

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Pull request merged**
