### PR TITLE
clisqlshell: implement `COPY ... FROM STDIN` for CLI

### LINKED ISSUE #16392: cli/sql: support COPY FROM STDIN in the sql shell
```
root@:26257/test> create table z(a int);
CREATE TABLE
root@:26257/test> copy z(a) from stdin;
pq: unknown response for simple query: 'G'
root@:26257 ?>
```

Jira issue: CRDB-6066

Epic CRDB-14477

### PR DESCRIPTION
**Pull request by otan**
Resolves #16392

Steps:
* Add a lower level API to lib/pq for use.
* Add some abstraction boundary breakers in `clisqlclient` that allow a
  lower level handling of the COPY protocol.
* Altered the state machine in `clisqlshell` to account for copy.

Release note (cli change): COPY ... FROM STDIN now works from the
cockroach CLI. It is not supported inside transactions.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
The general design is very nice :100: 

I have one remaiining concern on semantics, see below.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-:-N-9Go_w8OIxfc84y49Q:b-aazgwm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/cli/clisqlshell/sql.go, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-9GHH815FprINOEXEL:-N-9GHH815FprINOEXEM:b41nc8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/af53d44018adf3b0afcb6f039fa048803ebbcc40/pkg/cli/clisqlshell/sql.go#L1703)):*
> ```Go
> 	c.exitErr = c.runWithInterruptableCtx(func(ctx context.Context) error {
> 		if scanner.FirstLexicalToken(c.concatLines) == lexbase.COPY {
> 			return c.beginCopyFrom(ctx, c.concatLines)
> ```

wowzer, how does this behave if the user enters `copy ...; select ...` as one line at the prompt?
I want to see tests for this.

I think the code should refuse to treat COPY as a special case unless `c.singleStatement` is true.

**Comment by otan** [comment]
*[pkg/cli/clisqlshell/sql.go, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-9GHH815FprINOEXEL:-N-A8m0EB3rUBkBNkhY0:be36mi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/af53d44018adf3b0afcb6f039fa048803ebbcc40/pkg/cli/clisqlshell/sql.go#L1703)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

wowzer, how does this behave if the user enters `copy ...; select ...` as one line at the prompt?
I want to see tests for this.

I think the code should refuse to treat COPY as a special case unless `c.singleStatement` is true.
</blockquote></details>

there is a test for this:

```
start_test "multi statement with COPY"
send "SELECT 1; COPY t FROM STDIN CSV;\r"
eexpect "COPY together with other statements in a query string is not supported"
eexpect root@
send "COPY t FROM STDIN CSV;SELECT 1;\r"
eexpect "COPY together with other statements in a query string is not supported"
eexpect root@
end_test
```

**Comment by otan** [comment]
*[pkg/cli/clisqlshell/sql.go, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-9GHH815FprINOEXEL:-N-ACkBuAO37tnAdxI8Y:b-s8ef9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/af53d44018adf3b0afcb6f039fa048803ebbcc40/pkg/cli/clisqlshell/sql.go#L1703)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

there is a test for this:

```
start_test "multi statement with COPY"
send "SELECT 1; COPY t FROM STDIN CSV;\r"
eexpect "COPY together with other statements in a query string is not supported"
eexpect root@
send "COPY t FROM STDIN CSV;SELECT 1;\r"
eexpect "COPY together with other statements in a query string is not supported"
eexpect root@
end_test
```
</blockquote></details>

(it's already handled by the driver)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[go.mod, line 373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-PZAxz2Wl-GvpaoCaO:-N-PZAxz2Wl-GvpaoCaP:b-4befva) ([raw file](https://github.com/cockroachdb/cockroach/blob/8041b66c0bdd060e48b3c94b1f4bace189faf03c/go.mod#L373)):*
> ```XML
> replace github.com/maruel/panicparse/v2 => github.com/cockroachdb/panicparse/v2 v2.0.0-20211103220158-604c82a44f1e
> 
> replace github.com/lib/pq => github.com/cockroachdb/pq v0.0.0-20220408053752-c3ffc8d4376f
> ```

i think this fork is missing some of the latest lib/pq changes (they don't look too important, but might as well include them, or merge them into the upstream)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/cli/clisqlshell/sql.go, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-9GHH815FprINOEXEL:-N-PZjYu4HU_ex7vj01d:bc42xon) ([raw file](https://github.com/cockroachdb/cockroach/blob/af53d44018adf3b0afcb6f039fa048803ebbcc40/pkg/cli/clisqlshell/sql.go#L1703)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(it's already handled by the driver)
</blockquote></details>

to clarify, the "COPY together with other statements in a query string is not supported" message is actually coming from the CRDB server: https://github.com/cockroachdb/cockroach/blob/e4a9f6694c2cb91783c22f0fa965fdc4c1444285/pkg/sql/pgwire/conn.go#L846-L854

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[go.mod, line 373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-PZAxz2Wl-GvpaoCaO:-N-PdrLo5poDnrk4gR9M:b-j7v8bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8041b66c0bdd060e48b3c94b1f4bace189faf03c/go.mod#L373)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this fork is missing some of the latest lib/pq changes (they don't look too important, but might as well include them, or merge them into the upstream)
</blockquote></details>

last time i did some tests failed; also in terms of backportability this is much neater.
___
*[pkg/cli/clisqlshell/sql.go, line 1703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79629#-N-9GHH815FprINOEXEL:-N-PdwJ_C8vZ6yfTOKKj:b6prs8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/af53d44018adf3b0afcb6f039fa048803ebbcc40/pkg/cli/clisqlshell/sql.go#L1703)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to clarify, the "COPY together with other statements in a query string is not supported" message is actually coming from the CRDB server: https://github.com/cockroachdb/cockroach/blob/e4a9f6694c2cb91783c22f0fa965fdc4c1444285/pkg/sql/pgwire/conn.go#L846-L854
</blockquote></details>

even better!

**Comment by knz** [comment]
huh I hadn't seen you introduced a fork of lib/pq here. can you upstream them directly instead? we have a commit bit there.

**Comment by otan** [comment]
i've tried upgrading lib/pq instead, let's see if all tests pass.

**Comment by otan** [comment]
ok looks good

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

**Pull request merged**
