### PR TITLE
sql: null array element in cast is null

### PR DESCRIPTION
**Pull request by justinj**
Prior, `ARRAY[NULL]::STRING[]` would be `ARRAY['NULL']`, rather than
`ARRAY[NULL]`. This was because the evaluation of a CastExpr prior would
handle nulls by itself and so the extra case in the switch statement
went unnoticed.

Release note (bug fix): Casting arrays now correctly preserves NULL
values.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: nice find! :100: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28860#-:-LKO0Fec1hylbRzMvNGh:b-bjpc8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by justinj** [comment]
TFTR!

bors r+

**Comment by justinj** [comment]
bors r-

need to update some tests

**Pull request merged**
