### PR TITLE
sql: add timezone conversion builtin and syntax

### LINKED ISSUE #16382: sql: support AT TIME ZONE for tz casts
Feature Request

Description:
pgsql supports casting timestamp with time zone into any other time zone.
```
select NOW() AT TIME ZONE 'America/New_York'
```
We run all our postgres servers configure for UTC, and heavily use the casting mechanisms when reading data to display/export data in user-specific time zones, as well as with range queries using timestamps.

```
SELECT * from report where tstamp >= user_tz_to_utc($1, $2) and tstamp < next_day(user_tz_to_utc($1, $3))
```
where:
* $1 is the user id
* $2 is start tstamp (local to user)
* $3 is end tstamp (local to user)
* user_tz_to_utc/2 converts the tstamp from user's configured TZ to UTC
* next_day sets a UTC tstamp to 00:00:00 the following day

### LINKED ISSUE #32005: sql: Support the "at tz" operator
Support `<timestamp value> at tz` to convert timezones 

This is a top requested telemetry feature.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #16382.
Closes #32005.

Release note (sql change): implement the timezone() builtin and AT TIME
ZONE syntax, which allow converting a timestamptz into a timezone at a
specified timezone, and converting a timestamp into a timestamptz at a
specified timezone.

### CODE REVIEW

**Comment by tlvenn** [comment]
Thank you so much @jordanlewis for this PR !

**Comment by jordanlewis** [comment]
No problem @tlvenn! always appreciate your feature requests (especially when they're little ones :-)

**Review by knz — COMMENTED** [review]
LGTM modulo adding the missing doc link

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39186#-:-LlIJcu08v6bbEIDpyKm:b-wib8nt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @mjibson)

___
*[pkg/sql/sem/builtins/builtins.go, line 2340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39186#-LlIJUTM-GJ-EhonPazd:-LlIJUTN7X494g9r2fmV:b-t5fb0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c34239ad8d08dfaaa66a5fa741911231e73d53c7/pkg/sql/sem/builtins/builtins.go#L2340)):*
> ```Go
> 	),
> 
> 	"timezone": makeBuiltin(defProps(),
> ```

Can you add a comment at the top with a link to the relevant pg docs. Also add this link to the commit message.
Thanks

**Comment by jordanlewis** [comment]
Done. TFTR!

bors r+

**Pull request merged**
