### PR TITLE
sql: wait to drop until backrefs are cleaned up

### PR DESCRIPTION
**Pull request by dt**
Currently we wait for one version of the table being dropped, e.g. for all leases on the pre-drop version to expire. We do not however wait for one version of the tables it referenced, which are edited to remove the fact they are referenced when the referencing table is dropped.

Ideally we should wait until all nodes have the edited versions of those tables before actually dropping the referencing table.

In practice, any node with a lease on a referenced table will also have had a lease on referencing table to actually do fk checks. While we wait for the leases to expire on table being droppped before dropping it, those leases will likely expire as well,  making it very difficult to observe a case where this would cause a problem, but it is easy enough to guard against.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12540)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Your description is inaccurate. We never allow leases on table descriptors
with dropped.

**Comment by dt** [comment]
hm, I didn't think I was implying we leased tabled in DROP state, but reworded it to try to be clearer

**Comment by vivekmenezes** [comment]
David, It's not clear what exactly you are fixing here. To me this commit description reads like we're holding up the pants using a belt, and here are some additional suspenders just in case. It would be valuable to perhaps write a test that fails and then see that this fixes it. Thanks

**Comment by dt** [comment]
Any idea how we'd observe this in a test?
As mentioned, it is difficult to hit this in practice, since any leases on the edited tables happen to expire while we wait for the leases on the table being dropped to expire.

**Comment by vivekmenezes** [comment]
Sorry to drag this on. I'm only trying to understand under the rare circumstances what can go wrong, so that we know what we're fixing here. Thanks

**Comment by dt** [comment]
Yeah, I'm just worried those circumstances might be so rare that it won't reproduce without such a contrived case (e.g. messing with leases manually) that it no longer really has as much value as a test. I'll keep thinking about it though and see if I can come up with something that looks more like the real world -- fortunately, since we think this one is rare, it isn't urgent to merge.

**Pull request closed without merging**
