### PR TITLE
sql: add FORCE_INVERTED_INDEX hint

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/parser: add parse-no-verify test command

The `parse-no-verify` test command has been added to data-driven parser
tests. In addition, the `error` test command now asserts that parsing
the statement results in an error.

Release note: None

#### sql/parser: move index hint tests to new file

This is purely a mechanical movement of parser tests with index hints
into a new file.

Release note: None

#### sql/parser: support FORCE_INVERTED_INDEX hint

This commit adds parsing support for the `FORCE_INVERTED_INDEX` hint. The
hint currently has no effect.

Release note: None

#### sql: support FORCE_INVERTED_INDEX hint

Epic: None

Release note (sql change): The `FORCE_INVERTED_INDEX` hint is now
supported. This makes the optimizer prefer a query plan scan over any
inverted index of the hinted table. The query will result in an error if
no such query plan can be generated.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice!

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120384#-:-Nsoxf3B0HTFGZ22viqE:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/parser/sql.y` line 941 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120384#-NsowBDN4pkBysK8n1Zc:-NsowBDN4pkBysK8n1Zd:b-ufk0l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00befd619e0ee0d72ca499e20ef76baa785648ef/pkg/sql/parser/sql.y#L941)):*
> ```Yacc
> %token <str> FAILURE FALSE FAMILY FETCH FETCHVAL FETCHTEXT FETCHVAL_PATH FETCHTEXT_PATH
> %token <str> FILES FILTER
> %token <str> FIRST FLOAT FLOAT4 FLOAT8 FLOORDIV FOLLOWING FOR FORCE FORCE_INDEX FORCE_INVERTED_SCAN
> ```

Should it be `FORCE_INVERTED_INDEX` instead? You could justify either, but it'll be hard to change once we go with one.

**Comment by mgartner** [comment]
*[`pkg/sql/parser/sql.y` line 941 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120384#-NsowBDN4pkBysK8n1Zc:-Nsy9xWL9fJP8LRDx3o4:b-rkhh1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/00befd619e0ee0d72ca499e20ef76baa785648ef/pkg/sql/parser/sql.y#L941)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should it be `FORCE_INVERTED_INDEX` instead? You could justify either, but it'll be hard to change once we go with one.
</blockquote></details>

Hmmm, tough call. On the one hand `FORCE_INVERTED_INDEX` would be more consistent with the existing `FORCE_INDEX` hint. On the other hand, with `FORCE_INDEX` you must specify an index to force, which could be non-inverted or inverted, while this new hint will not allow specifying an index, so `FORCE_INVERTED_SCAN` might be better? On the third hand, in the future we could extend `FORCE_INVERTED_INDEX` to allow specifying an inverted index.

**Comment by mgartner** [comment]
*[`pkg/sql/parser/sql.y` line 941 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120384#-NsowBDN4pkBysK8n1Zc:-Nt2ICzlAiNAZ0iWtVML:b-oncobl) ([raw file](https://github.com/cockroachdb/cockroach/blob/00befd619e0ee0d72ca499e20ef76baa785648ef/pkg/sql/parser/sql.y#L941)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmmm, tough call. On the one hand `FORCE_INVERTED_INDEX` would be more consistent with the existing `FORCE_INDEX` hint. On the other hand, with `FORCE_INDEX` you must specify an index to force, which could be non-inverted or inverted, while this new hint will not allow specifying an index, so `FORCE_INVERTED_SCAN` might be better? On the third hand, in the future we could extend `FORCE_INVERTED_INDEX` to allow specifying an inverted index.
</blockquote></details>

I went with `FORCE_INVERTED_INDEX`. Thanks for the feedback!

**Comment by mgartner** [comment]
TFTR!

bors r=DrewKimball

**Comment by mgartner** [comment]
blathers backport 23.1

**Comment by mgartner** [comment]
blathers backport 23.2

**Comment by mgartner** [comment]
blather backport 24.1

**Comment by rytaft** [comment]
blathers backport 24.1

**Comment by mgartner** [comment]
Lol, thanks for the assist. Looks like I'm doing these all manually though. 🙃

**Comment by rytaft** [comment]
Haha oh well...

**Comment by mgartner** [comment]
This doesn't need to be backported to 24.1—it was merged before the `release-24.1` branch was cut.

**Pull request merged**
