### PR TITLE
sql, encoding: update apd, with NaN, Inf support

### PR DESCRIPTION
**Pull request by madelynnblue**
Sync to most recent apd branch that has NaN, Infinity, and negative
zero support. The Traps have been cleared because we no longer need to
error in these cases since apd always returns something. This changes
the decimal implementation to return the same values as floats to
for operations that return NaN or Infinity.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14302)

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-:-Kfqfr-yJEQ_OQ6YaM8t:bnfp4nl)*

**Comment by knz** [comment]
LGTM, but can you please also make a random sample in our team to ask opinions about whether having separate +0 and -0 for DECIMAL is a good thing (especially in the context of using DECIMAL for monetary amount). Ensure that your sample includes @dt and @tschottdorf

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-:-KfrgufZoYG8-laPBZhJ:byicf5t)*

**Comment by mjibson** [comment]
Some functionality has been changed in the latest revision. The Traps are now left as they were, producing errors in almost all cases as before. The notable difference is `power(0, -1)`, which produces infinity (and is perhaps the only known way to produce infinity using arithmetic). This is because the GDA spec tests consider this a valid operation. It sadly differs from postgres. However, these differences from postgres are already present and inconsistent, so it's no worse than we already were, and will be fixed sometime soon.

Leaving the Traps as they were also fixed the normalization errors because those now produce the same errors as before. Overall this new revision is more conservative and changes less things at once. We can make some policy decisions later about if we want to change the other stuff or not.

**Comment by mjibson** [comment]
RFAL. Significant changes have been made to add encoding functionality and tests for Inf, NaN, and -0.

**Comment by knz** [comment]
LGTM but cc @nvanbenschoten

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/testdata/logic_test/decimal, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-8uwHUjwJ0U3e2Ug-:-Kg-8uwHUjwJ0U3e2Ug0:b-n7kkiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/testdata/logic_test/decimal#L87)):*
> ```
> 	(2.0::decimal, 2.0::decimal),
> 	(3::decimal, 3::decimal),
> 	('NaN'::decimal, 'NaN'::decimal),
> ```

Please add a NULL in the table to highlight the relative sort order of NaN and NULL.

---

*[pkg/sql/testdata/logic_test/decimal, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-9Cdtx2spVE9h_vLH:-Kg-9CduVu9zGF1Nbq61:bnb1osf) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/testdata/logic_test/decimal#L135)):*
> ```
> -0
> 1
> Infinity
> ```

Add example queries that show how to retrieve each of the special values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-:-Kg-9eRlzLpr9jY7DiyZ:b-sltvre)*

**Comment by nvanbenschoten** [comment]
:lgtm: with a few questions. Happy to see this all finally working!

---

Reviewed 1 of 8 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 534 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-QwkOWq5jQvdMnLfB:-Kg-QwkOWq5jQvdMnLfC:bikxoln) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/parser/datum.go#L534)):*
> ```Go
> 		panic(makeUnsupportedComparisonMessage(d, other))
> 	}
> 	// NaNs sort first in SQL.
> ```

There's a nice `isNaN` function waiting in `eval.go` for this change.

Also, please add some cases for decimal NaN and decimal Inf to `TestEval`. We already have similar ones for floats.

---

*[pkg/util/encoding/decimal.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-TJMDCk36eVxRtcKi:-Kg-TJMDCk36eVxRtcKj:bbhq0qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/util/encoding/decimal.go#L63)):*
> ```Go
> func encodeDecimal(appendTo []byte, d *apd.Decimal, invert bool) []byte {
> 	if d.IsZero() {
> 		// Negative and positive zero are encoded identically. Only nonsorting
> ```

Is this going to be an issue?

---

*[pkg/util/encoding/decimal_test.go, line 158 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-TgsztVC7rF2NQI4O:-Kg-TgsztVC7rF2NQI4P:b9xnwb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/util/encoding/decimal_test.go#L158)):*
> ```Go
> 		{mustDecimalFloat64(-math.SmallestNonzeroFloat64), []byte{0x26, 0xf6, 0xa1, 0xf5, 0x00}},
> 		{apd.New(-11, -66666), []byte{0x26, 0xf7, 0x82, 0x34, 0xe9, 0x00}},
> 		{&apd.Decimal{Negative: true}, []byte{0x27}},
> ```

Any way we can make this test case (and the one below) more clear? Even something like `parse("-0")` would be less obscure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-:-Kg-TsFwe0OeB3pt3bFn:b5t3qw9)*

**Comment by mjibson** [comment]
Review status: 10 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/parser/datum.go, line 534 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-QwkOWq5jQvdMnLfB:-Kg0vfSTqAPkQESdTKLl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/parser/datum.go#L534)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's a nice `isNaN` function waiting in `eval.go` for this change.

Also, please add some cases for decimal NaN and decimal Inf to `TestEval`. We already have similar ones for floats.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/decimal, line 87 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-8uwHUjwJ0U3e2Ug-:-Kg0zNgVLEvtVh1KKk46:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/testdata/logic_test/decimal#L87)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add a NULL in the table to highlight the relative sort order of NaN and NULL.
</blockquote></details>

Done.

---

*[pkg/sql/testdata/logic_test/decimal, line 135 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-9Cdtx2spVE9h_vLH:-Kg12KRPwRFQAtvAJnZK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/sql/testdata/logic_test/decimal#L135)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add example queries that show how to retrieve each of the special values.
</blockquote></details>

Done.

---

*[pkg/util/encoding/decimal.go, line 63 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-TJMDCk36eVxRtcKi:-Kg12KvosbEwl6WXqOIM:bo46fye) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/util/encoding/decimal.go#L63)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this going to be an issue?
</blockquote></details>

I don't think so. It's certainly no worse than the zero truncation we already do. The solution will just have to also be aware of the -0 special. Composite indexes should be able to fix this correctly.

---

*[pkg/util/encoding/decimal_test.go, line 158 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg-TgsztVC7rF2NQI4O:-Kg12oFf9xoNgSFE0noh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/891661a92ccc92bf454964bbfe29ff4478ee483d/pkg/util/encoding/decimal_test.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any way we can make this test case (and the one below) more clear? Even something like `parse("-0")` would be less obscure.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302)*

**Comment by knz** [comment]
I found your distSQL issue, see my comment below.
Also curious about tests that check PK behavior.

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/datum.go, line 582 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg3qQ8-I8mXyqdoKvVh:-Kg3qQ8-I8mXyqdoKvVi:b6t640a) ([raw file](https://github.com/cockroachdb/cockroach/blob/81075fb1b2267856a9881c67c55b90c6515f1bff/pkg/sql/parser/datum.go#L582)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (d *DDecimal) Format(buf *bytes.Buffer, f FmtFlags) {
> 	buf.WriteString(d.Decimal.ToStandard())
> ```

This is what you need to change to fix the broken distSQL tests.
The code in `format.go` (`FormatNode()` lines 137-154 to be specific) re-formats all decimal datums as its value according to `(*DDecimal).Format()` followed by `:::decimal`.
You'll need to format infinities and nans as an explicit *cast* here: `'nan'::decimal`, `'inf'::decimal` (note the *two* colons); the pretty-printed expression will become correct and the extra `:::decimal` appended by `FormatNode()` after that will stay innocuous.

(Also, add tests for this in `TypeCheckTest` (`type_check_test.go`))

---

*[pkg/sql/testdata/logic_test/decimal, line 178 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg3pRfQjR7SMsbI9-ko:-Kg3pRfQjR7SMsbI9-kp:b-5t0f1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/81075fb1b2267856a9881c67c55b90c6515f1bff/pkg/sql/testdata/logic_test/decimal#L178)):*
> ```
> SELECT * FROM s WHERE d = 'inf'::decimal
> ----
> Infinity
> ```

I can't seem to find it: can you point me to the test(s) where you check that a decimal PK column rejects duplicate values properly? (namely: NaN and -NaN, 0 and -0, 0.000 and 0.00000)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-:-Kg3pnYK2vuqg1GpYAMd:b-mjjijc)*

**Comment by mjibson** [comment]
Review status: 15 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/parser/datum.go, line 582 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg3qQ8-I8mXyqdoKvVh:-KgDD-fHZ9P_yQ9m2i2H:bab7ckx) ([raw file](https://github.com/cockroachdb/cockroach/blob/81075fb1b2267856a9881c67c55b90c6515f1bff/pkg/sql/parser/datum.go#L582)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is what you need to change to fix the broken distSQL tests.
The code in `format.go` (`FormatNode()` lines 137-154 to be specific) re-formats all decimal datums as its value according to `(*DDecimal).Format()` followed by `:::decimal`.
You'll need to format infinities and nans as an explicit *cast* here: `'nan'::decimal`, `'inf'::decimal` (note the *two* colons); the pretty-printed expression will become correct and the extra `:::decimal` appended by `FormatNode()` after that will stay innocuous.

(Also, add tests for this in `TypeCheckTest` (`type_check_test.go`))
</blockquote></details>

Done, however I can't see how to add tests for this in TestTypeCheck. I've added tests there, but they render something first asserted a string and then coerced to a decimal.

---

*[pkg/sql/testdata/logic_test/decimal, line 178 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-Kg3pRfQjR7SMsbI9-ko:-KgD0w_rJ-abpM5bZVG9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81075fb1b2267856a9881c67c55b90c6515f1bff/pkg/sql/testdata/logic_test/decimal#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I can't seem to find it: can you point me to the test(s) where you check that a decimal PK column rejects duplicate values properly? (namely: NaN and -NaN, 0 and -0, 0.000 and 0.00000)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/type_check_test.go, line 105 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-KgI8eI-LIVOcKnf7Yio:-KgI8eI-LIVOcKnf7Yip:b-t3jpyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/70db91be7a3e15ffebd5f8dbea316e1e8630c892/pkg/sql/parser/type_check_test.go#L105)):*
> ```Go
> 		{`1:::DECIMAL + $1`, `1:::DECIMAL + $1:::DECIMAL`},
> 		{`$1:::INT`, `$1:::INT`},
> ```

Make a new function `TestTypeCheckAndNormalize` which does the same as `TestTypeCheck` but adds a call to `NormalizeExpr()` after `TypeCheck()`. That will reveal and test the pretty-print of naked Decimal datums.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302)*

**Comment by mjibson** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/parser/type_check_test.go, line 105 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302#-KgI8eI-LIVOcKnf7Yio:-KgIG9r3MbA1-QZ8STi-:b-vg730v) ([raw file](https://github.com/cockroachdb/cockroach/blob/70db91be7a3e15ffebd5f8dbea316e1e8630c892/pkg/sql/parser/type_check_test.go#L105)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make a new function `TestTypeCheckAndNormalize` which does the same as `TestTypeCheck` but adds a call to `NormalizeExpr()` after `TypeCheck()`. That will reveal and test the pretty-print of naked Decimal datums.
</blockquote></details>

Ah, thanks. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14302)*

**Comment by mjibson** [comment]
@nvanbenschoten can you give this a final look over since Raphael is out?

**Comment by knz** [comment]
LGTM (sorry I had looked but forgot to answer)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
