### PR TITLE
storage: Improve/test rebalancing behavior when cluster is nearly full

### LINKED ISSUE #21400: storage: test/improve rebalancing behavior when cluster is nearly full
We currently rebalance away from a store when it has used more than 95% of its available disk space. In v1.1, this can cascade the problem if other nodes are also very full, since rebalancing onto them will will them up as well. And because we don't reclaim the disk space until rocksdb compactions happen, the full nodes remain full.

In more recent builds after https://github.com/cockroachdb/cockroach/pull/21178, we at least reclaim the disk space, but could easily get into thrashing situations where we rebalance from node 1 to node 2, which makes node 1 under the 95% cap and node 2 over it, causing node 2 to rebalance back to node 1, and so on.

More work and testing is needed to ensure the system maintains stability when it nears fullness.

### PR DESCRIPTION
**Pull request by a-robinson**
Should fix #21400, but I need to run another real cluster test on the final version of these changes to verify before merging. See individual commit messages for descriptions.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 4 of 4 files at r7, 2 of 2 files at r8.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/allocator_scorer.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42gyfWbH1-aKG8InkQ:-L42gyfXeaSV8JvyT73z:b-16jnn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/270d7aeff6e0d0b7bc95e85f2c4000a4b47b24c7/pkg/storage/allocator_scorer.go#L54)):*
> ```Go
> 	// hypothetically ping pong back and forth between two nodes, making one full
> 	// and then the other.
> 	rebalanceToMaxFractionUsedThreshold = 0.925
> ```

I assume this was pulled out of the air. 

---

*[pkg/storage/allocator_test.go, line 3252 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42hdGConWN8nMXuNZZ:-L42hdGDYzX5maE4xPpZ:bapushg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3abab6c5f520203b280e3a8c78713b8f5af7fb7/pkg/storage/allocator_test.go#L3252)):*
> ```Go
> 	// Mimic a real Store's behavior of rejecting preemptive snapshots when full.
> 	if !maxCapacityCheck(ots.StoreDescriptor) {
> 		log.Infof(context.TODO(), "s%d too full to accept snapshot from s%d: %v", ots.StoreID, ts.StoreID, ots.Capacity)
> ```

Did you intended to leave these log messages in? If yes, `s/TODO/Background/g`

---

*[pkg/storage/allocator_test.go, line 3273 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42ktIsgB28tVY6T7lf:-L42ktIsgB28tVY6T7lg:btmx83o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3273)):*
> ```Go
> }
> 
> func TestAllocatorFullDisks(t *testing.T) {
> ```

This is quite complex, though I don't have a suggestion for simplification. 

---

*[pkg/storage/allocator_test.go, line 3319 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42l5q7gl2cE9RLBWnV:-L42l5q7gl2cE9RLBWnW:b2v9jnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3319)):*
> ```Go
> 	const capacity = (1 << 30) + 1
> 	const rangeSize = 16 << 20
> 	const rangesPerNode = 60 // 60 * 16 = 960MB per node, i.e. ~95% full
> ```

Perhaps this should be `capacity * 0.95 / rangeSize`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-:-L42lSq6t3XS-JXOVXvN:bnfp4nl)*

**Comment by a-robinson** [comment]
Whoops, I forgot to respond to this when I pushed out my changes. TFTR! Part 2 is in https://github.com/cockroachdb/cockroach/pull/22235, which is the full version I'll test on before merging either.

---

Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_scorer.go, line 54 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42gyfWbH1-aKG8InkQ:-L46bKTvbKoyPiqLGpJQ:b1rgkve) ([raw file](https://github.com/cockroachdb/cockroach/blob/270d7aeff6e0d0b7bc95e85f2c4000a4b47b24c7/pkg/storage/allocator_scorer.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I assume this was pulled out of the air. 
</blockquote></details>

Yup. I originally went with `0.9` but that restricted rebalancing a little too much in the test, since once all nodes got to 90% full no more rebalancing could happen. It's possible that rather than being its own number this should just be a couple percent less than `maxFractionUsedThreshold`.

---

*[pkg/storage/allocator_test.go, line 3252 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42hdGConWN8nMXuNZZ:-L46bjGghJUip4JP2oG3:b-hvrglh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3abab6c5f520203b280e3a8c78713b8f5af7fb7/pkg/storage/allocator_test.go#L3252)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you intended to leave these log messages in? If yes, `s/TODO/Background/g`
</blockquote></details>

Yes, they're great to have if the test fails. Changed.

---

*[pkg/storage/allocator_test.go, line 3273 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42ktIsgB28tVY6T7lf:-L46c5MSEUCedyzEn0cP:b-1n2bqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3273)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is quite complex, though I don't have a suggestion for simplification. 
</blockquote></details>

I think the real simplification would be writing more of a black-box test. As is, the test is partially testing things and partially mimicking fixes (like not accepting snapshots when full).

---

*[pkg/storage/allocator_test.go, line 3319 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42l5q7gl2cE9RLBWnV:-L46ct_iF3JyuWbhtiKS:bwx3hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3319)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps this should be `capacity * 0.95 / rangeSize`.
</blockquote></details>

I don't really love that using `math.Floor` prevents me from marking these as `const`, but done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-:-L48QcNgm3b5jqi46lgX:b-y6vig3)*

**Comment by petermattis** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 3319 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42l5q7gl2cE9RLBWnV:-L48k-qiqkmDayUwlP5k:b4gqy6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3319)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't really love that using `math.Floor` prevents me from marking these as `const`, but done.
</blockquote></details>

I think you can do `int(capacity * 0.95 / rangeSize)` in order to let a stay a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866)*

**Comment by a-robinson** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/allocator_test.go, line 3319 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L42l5q7gl2cE9RLBWnV:-L4BrON99fV9-3cLZDMH:b-6ik1yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1427abd55dd90aefcb515926312a319eda4b953/pkg/storage/allocator_test.go#L3319)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you can do `int(capacity * 0.95 / rangeSize)` in order to let a stay a constant.
</blockquote></details>

Apparently not, it gives a `constant truncated to integer` error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866)*

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

> Gossiping is so much cheaper adding/removing a range that I can't
imagine this will have any discernible cost in the cluster.

`s/cheaper adding/cheaper than adding/`

---

Reviewed 6 of 6 files at r10, 1 of 1 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_scorer.go, line 45 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L4Euhq-bHu8DZin1ybT:-L4Euhq-bHu8DZin1ybU:bxapjiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1d254a032f90710a8184c377db71f410a27bae5/pkg/storage/allocator_scorer.go#L45)):*
> ```Go
> 	// capacity is greater than this value, it will never be used as a rebalance
> 	// or allocate target and we will actively try to move replicas off of it.
> 	maxFractionUsedThreshold = 0.95
> ```

consider calling this `rebalanceFromMaxFractionUsedThreshold` so that it parallels the other const. Take it or leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-:-L4EvHaL3dQHGyNAJgSZ:beb5kgv)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator_scorer.go, line 45 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866#-L4Euhq-bHu8DZin1ybT:-L4GuF_lIXIERnhox2KX:bdmmal4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1d254a032f90710a8184c377db71f410a27bae5/pkg/storage/allocator_scorer.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

consider calling this `rebalanceFromMaxFractionUsedThreshold` so that it parallels the other const. Take it or leave it.
</blockquote></details>

It's used for more than just rebalancing from - it also determines whether a node is eligible to be up-replicated to (if a range is under-replicated) and whether it's first in line to have a replica removed from it when down-replicating (if a range is over-replicated).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21866)*

**Pull request merged**
