### PR TITLE
opt: break up spans in opt plans

### PR DESCRIPTION
**Pull request by RaduBerinde**
Break up multi-span constraints to make the plans more readable
(especially for partitioning-constrainted scans).

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
it's more beautiful than I imagined :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44499#-:-LzmqjPF9LsatWHSBO92:bhkk19a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44499#-:-LzrOGud8B2t5yFgv62h:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
