### PR TITLE
build/teamcity: add changes to enable openmetrics in nightly roachtests

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
There was a regression in https://github.com/cockroachdb/cockroach/pull/135239.
The change was reverted and this PR aims to fix the regressions

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-41852

Release note: None

### CODE REVIEW

**Comment by sambhav-jain-16** [comment]
Test runs:

json: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Roachtest_Openmetrics_Gce/17906085?buildTab=log&focusLine=2934&logView=flowAware&linesState=571

openmetrics: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Roachtest_Openmetrics_Gce/17906084?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Review by DarrylWong — COMMENTED** [review]
I think there's a couple benchmark tests that are on the `weekly` suite. We should export `-e EXPORT_OPENMETRICS -e ROACHPERF_OPENMETRICS_CREDENTIALS` to the `weekly_*.sh` scripts as well.

> There was a regression in https://github.com/cockroachdb/cockroach/pull/135239.

Out of curiosity, what exactly was the regression?

**Comment by sambhav-jain-16** [comment]
> Out of curiosity, what exactly was the regression?

An error was introduced while trying to read `EXPORT_OPENMETRICS` as being an unbounded variable.

> I think there's a couple benchmark tests that are on the weekly suite. We should export -e EXPORT_OPENMETRICS -e ROACHPERF_OPENMETRICS_CREDENTIALS to the weekly_*.sh scripts as well.

ok

**Review by nameisbhaskar — APPROVED** [review]
LGTM!

**Comment by sambhav-jain-16** [comment]
TFTR!

bors r=@nameisbhaskar

**Pull request merged**
