### PR TITLE
sql/mutations: add match and action to FK constraints

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42451#-:-LtivVmq0VJJ_G7CzxrH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @mjibson)

___
*[pkg/sql/mutations/mutations.go, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42451#-LtivYzXDmZwjH7Pkb-2:-LtivYzXDmZwjH7Pkb-3:b-wsgtc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4280611cc0febf3abef7e8426b9fa1ac103ec47/pkg/sql/mutations/mutations.go#L293)):*
> ```Go
> 				for refI, refCol := range availCols {
> 					var equiv bool
> 					switch fkCol.Type.Family() {
> ```

What's this for? Comment maybe.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42451)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/mutations/mutations.go, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42451#-LtivYzXDmZwjH7Pkb-2:-Ltzeghk24Cnw-oDA7gW:b-bv4rx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4280611cc0febf3abef7e8426b9fa1ac103ec47/pkg/sql/mutations/mutations.go#L293)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What's this for? Comment maybe.
</blockquote></details>

Removed. I added it because I thought it was needed, but there was really another bug going on that was presenting like this.

**Comment by mjibson** [comment]
I'm getting v bored of these test flakes.

**Pull request merged**
