### PR TITLE
sql/upgrades: add upgrade logic so that sequences are referenced by ID

### LINKED ISSUE #61017: Migrate old sequences to be referenced by ID
**Describe the problem**

Now that new sequences are referenced by ID and thus can be renamed, we want to migrate old (existing) sequences to be the same (stored by ID). 

Jira issue: CRDB-3084

### PR DESCRIPTION
**Pull request by Xiang-Gu**
A few releases ago, sequences are referenced by name but we have
changed it to be by ID (to enable things like `RENAME AS`). However,
the necessary migration work, supposedly tracked in #61017, somehow
fell out of the team's radar unfortunately. This PR filled this gap by
implementing the migration logic, among many from v22.1 to v22.2, that
iterates over all table (or view) descriptor and upgrade their sequence
reference from by name to by ID, if not already.

fixed: #61017

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
nice work on this, so sorry about the very slow review. Just nits 

> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-:-N3tTBTv2RbXASRS4TmV:bsoq2ns)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`pkg/upgrade/tenant_upgrade.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-N3tSzqYDb_xWFlgcoRr:-N3tSzqYDb_xWFlgcoRs:bh6btbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/798e7699b21b55a0c888ebc4f9a3aea6f7b30ef4/pkg/upgrade/tenant_upgrade.go#L47)):*
> ```Go
> 
> 	TestingKnobs               *TestingKnobs
> 	InternalPlannerConstructor func(txn *kv.Txn, descriptors *descs.Collection, currDb string) (interface{}, func())
> ```

can you narrow this to `resolver.SchemaResolver` for the return type?
___
*[`pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-N3tShyk70Q8VQzI6Bb_:-N3tShyk70Q8VQzI6Bba:by6v3ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/798e7699b21b55a0c888ebc4f9a3aea6f7b30ef4/pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go#L151)):*
> ```Go
> 
> 	// Construct an internal planner
> 	planner, cleanup := d.InternalPlannerConstructor(txn, descriptors, dbDesc.GetName())
> ```

@chengxiong-ruan almost got the `schemaResolver` fully extracted from the planner. What do you think about finishing that work by extracting `sql.schemaResolver` into a new package and then constructing that thing directly? I think it'll be a good deal cleaner and will make me happy. Feel free to do it in follow-up. 



_Code quote:_
```Go
,
```

**Review by Xiang-Gu — COMMENTED** [review]
Thanks. I address the comments to change the return types. RFAL again.

I'm interested in finishing up @chengxiong-ruan's refactoring in a follow-up (also an exercise to learn more about the codebase) PR. I left a few questions in the comment below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-:-N3uX37b9Y-j9vq8rxE-:b3po910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/upgrade/tenant_upgrade.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-N3tSzqYDb_xWFlgcoRr:-N3uKkh-BXbyfXo9Ir91:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/798e7699b21b55a0c888ebc4f9a3aea6f7b30ef4/pkg/upgrade/tenant_upgrade.go#L47)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you narrow this to `resolver.SchemaResolver` for the return type?
</blockquote></details>

done
___
*[`pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-N3tShyk70Q8VQzI6Bb_:-N3uQimV312InA1jVOfC:b-v6iyv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/798e7699b21b55a0c888ebc4f9a3aea6f7b30ef4/pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go#L151)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

@chengxiong-ruan almost got the `schemaResolver` fully extracted from the planner. What do you think about finishing that work by extracting `sql.schemaResolver` into a new package and then constructing that thing directly? I think it'll be a good deal cleaner and will make me happy. Feel free to do it in follow-up. 
</blockquote></details>

I'd love to do that in a follow-up! Before that, can you explain a bit more about what needs to be done to finish that work?

I read @chengxiong-ruan's pr for his refactoring effort and learned that, previously, planner implemented the `resolver.SchemaResolver` interface, and Chengxiong moved them into a struct `sql.schemaResolver` and let this struct implement the `resolver.SchemaResolver` interface. He also left a TODO there saying "refactor this out into a separate package", which resonates with what you said. I don't, however, understand what's the "end state" we'd like to see to finish this work and what's required.

More concretely, 
1. Where should this "separate" package be? Should it be the "resolver" package or somewhere else?

2. What do you mean by "constructing that thing directly"? 

3. What is the "end-state" we'd like to see to finish this refactoring effort?

**Review by fqazi — APPROVED** [review]
> Reviewed 4 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81583)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81583)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go` line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81583#-N3tShyk70Q8VQzI6Bb_:-N47w7LY2XHUa8OA6EQ_:b4nsa94) ([raw file](https://github.com/cockroachdb/cockroach/blob/798e7699b21b55a0c888ebc4f9a3aea6f7b30ef4/pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go#L151)):*
> 1. Where should this "separate" package be? Should it be the "resolver" package or somewhere else?

It need to be somewhere else, like a `schemaresolver` package under sql package.

> 2. What do you mean by "constructing that thing directly"?

It means you construct the SchemaResolver directly instead of the big mighty planner.

> 3. What is the "end-state" we'd like to see to finish this refactoring effort?

The end state is that `schemaResolver` is not embedded within planner, instead, it's separate child field it depends on. So you see that planner itself won't be a SchemaResolver anymore. It'd be a happy lighter object.

**Pull request merged**
