### PR TITLE
sql,opt: collect small histograms on all non-index columns, update test fixtures

### LINKED ISSUE #49374: sql, stats: collect small histograms on all columns
Currently, we only collect histograms on the first column of each index in a table. The reason for this is that the default size of histograms is 200 buckets, so they use a non-trivial amount of space and require a non-trivial amount of computation in order to collect them and use them in the optimizer. Still, it's generally worth the extra space and computation for index columns; index columns are likely to be used in predicates, so histograms are likely to be useful for cardinality estimation.

We could still get some benefit from collecting smaller histograms on other columns, however. Collecting a histogram with 2 buckets would be equivalent to storing the maximum and minimum value for a column, which could significantly improve our selectivity estimation for some queries. Instead of assuming all inequalities (e.g., `x < 10`) have selectivity equal to 1/3, we can make an educated guess based on the domain of the variable.

### LINKED ISSUE #52484: opt: update opt stats test fixtures for TPC-C, TPC-H to include histograms on index columns
Now that we collect histograms for all indexed columns, we should update the opt stats test fixtures to also include histograms on index columns.

Related: https://github.com/cockroachdb/cockroach/pull/52448#issuecomment-669977387

### PR DESCRIPTION
**Pull request by rytaft**
**sql: collect small histograms on all non-index columns**

This commit updates the logic for automatic statistics collection
so that 2-bucket histograms are collected on non-index columns.
200-bucket histograms are still collected for all index columns.

Fixes #49374

Release note (performance improvement): Maximum and minimum
values, represented as 2-bucket histograms, are now collected
for all non-index columns (up to 100 columns per table) as part of
automatic statistics collection. 200-bucket histograrms are still
collected for all index columns. This change enables the optimizer
to make better cardinality estimates and may result in better query
plans in some cases.

**opt: update TPC-C and TPC-H test fixtures with new stats**

This commit updates the stats in the TPC-C and TPC-H optimizer
tests to reflect the stats that are now collected automatically.
These stats include full histograms for all index columns, as well
as 2-bucket histograms for all other columns.

This commit also fixes the TPC-C schema to include some missing
foreign key indexes.

Fixes #52484

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExFB8uBWyOPHCTlkxE:-MExFB8uBWyOPHCTlkxF:b-m9yxo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L78)):*
> ```
>     h_data   varchar(24),
>     primary key (h_w_id, rowid),
>     index history_customer_fk_idx (h_c_w_id, h_c_d_id, h_c_id),
> ```

These were removed on purpose. They may not have been removed from all fixtures, @rohany should know what was updated and what wasn't.

**Comment by rohany** [comment]
> These were removed on purpose. They may not have been removed from all fixtures, @rohany should know what was updated and what wasn't. 

The schemas in the optimizer are more up to date right now than the ones in workload.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rohany)

___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExFB8uBWyOPHCTlkxE:-MExU7Xp7tqpHYATpRtV:bg3l04m) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These were removed on purpose. They may not have been removed from all fixtures, @rohany should know what was updated and what wasn't. 
</blockquote></details>

Got it, thanks. In that case I'll revert these changes and manually delete the indexes from my running cluster.
___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExUMp85SSDEeKov9XO:-MExUMp85SSDEeKov9XP:b-mgi9f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L146)):*
> ```
>     s_data       varchar(50),
>     primary key (s_w_id, s_i_id),
>     index stock_item_fk_idx (s_i_id),
> ```

should this one be removed too?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExUMp85SSDEeKov9XO:-MExVNkn0v8MaE8Zn89L:btxzalo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L146)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should this one be removed too?
</blockquote></details>

No, I believe that one was shown to be beneficial.

**Comment by rohany** [comment]
> should this one be removed too?

No -- initial testing showed that we still need that one, but I'm not sure why yet.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52905)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExFB8uBWyOPHCTlkxE:-MExji6Y-FXG2Ip3jlU5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L78)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Got it, thanks. In that case I'll revert these changes and manually delete the indexes from my running cluster.
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExUMp85SSDEeKov9XO:-MExjjbJ7KrLRuVDW-ZB:b5vjmdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eabf08c09ecfef8372a14568e67e46efa0187da1/pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema#L146)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

No, I believe that one was shown to be beneficial.
</blockquote></details>

Got it - thanks.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-:-MExmN5X4HIgZiAgpEzA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/distsql_plan_stats.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExmK8V6HEGM_8TfAZS:-MExmK8V6HEGM_8TfAZT:bnfss2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/633de7aff7f5d510c34ad6ce19144c31940a907a/pkg/sql/distsql_plan_stats.go#L43)):*
> ```Go
> 
> const histogramSamples = 10000
> const histogramBuckets = 200
> ```

This constant is duplicated now

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-:-MExpIjPAbUTsHxtFSup:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/distsql_plan_stats.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52905#-MExmK8V6HEGM_8TfAZS:-MExoYXDE8FsOhJoOs_t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633de7aff7f5d510c34ad6ce19144c31940a907a/pkg/sql/distsql_plan_stats.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This constant is duplicated now
</blockquote></details>

Done.

**Pull request merged**
