### PR TITLE
Events and cleaned up cluster overview

### PR DESCRIPTION
**Pull request by maxlang**
Ignore the help us flow commit (PR here: https://github.com/cockroachdb/cockroach/pull/4397)
- adds events to the the cluster overview page
- adds an events tab to the nodes page
- cleans up the cluster overview graphs
- general tidying (especially in the top nav)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4587)

### CODE REVIEW

**Comment by maxlang** [comment]
Also sets xhr timeouts to 2 seconds

**Comment by maxlang** [comment]
**Original cluster overview for comparison**
screen shot 2016-02-23 at 2 17 11 am

**Cluster overview cleanup**
screen shot 2016-02-23 at 2 12 33 am

**Events on the cluster overview page**
screen shot 2016-02-23 at 2 12 44 am

**Events tab on the nodes page**
screen shot 2016-02-23 at 2 12 52 am

**Comment by mrtracy** [comment]
Hey, this actually LGTM!

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4587#-:-KBFRCeFuGRqm9ht82l9:-1656791809)*

**Comment by tschottdorf** [comment]
Those graphs with negative values should be anchored at zero.

**Comment by maxlang** [comment]
@tschottdorf nvd3 doesn't really make that easy - let's punt on it for this PR

**Pull request merged**
