### PR TITLE
storage: avoid clobbering leases on lease commands

### LINKED ISSUE #10414: stability: lease and freeze handling for proposer-evaluated KV
At the time of writing, proposer-evaluated KV does not correctly deal with leases. More precisely, the logic downstream of Raft is missing:

* it is not verified that a command applies under the lease it was proposed (which is necessary)
* `{Request,Transfer}Lease` have no special downstream-of-Raft handling which is necessary to avoid lease clobbering.

Similarly, `ChangeFrozen` (or any other command that can be proposed by anyone) needs such special handling. The changes should be made in a way that makes sure that we can't accidentally change the semantics of existing commands or add new ones that would also need special casing.

Assigning @petermattis for proper reassignment.

### PR DESCRIPTION
**Pull request by spencerkimball**
To guarantee verification of leases on lease-based requests, we provide
the lease from the time the TransferLease or RequestLease command was
proposed and verify it when processing the Raft command.

Fixes #10414

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12209)

### CODE REVIEW

**Comment by spencerkimball** [comment]
I'll get to the unittest tomorrow.

**Comment by bdarnell** [comment]
LGTM pending a test.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/replica.go, line 1968 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWhndt1zwOS05CpT5O:-KYWhnduVpexGSn8LKeF:bf71bp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/storage/replica.go#L1968)):*
> ```Go
> 	} else {
> 		// For lease commands, use the provided previous lease for verification.
> 		switch t := ba.Requests[0].GetInner().(type) {
> ```

Instead of this type switch, we could define an interface and a method on the request types (like we did for `roachpb.combinable`). I prefer to keep things like this in the `roachpb` package; it's not obvious otherwise that every request with the `skipLease` flag needs a corresponding entry here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-:-KYWihfjfDxGJtLyn1Sm:buldunh)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.go, line 835 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWLfad6JrI2GxIav8_:-KYWLfad6JrI2GxIav8a:btf1ubc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/roachpb/api.go#L835)):*
> ```Go
> 	// `redirectOnOrAcquireLease` call because, by the time that call is made, the
> 	// replica has registered that a transfer is in progress and
> 	// `redirectOnOrAcquire` already tentatively redirects to the future lease
> ```

redirectOnOrAcquireLease?

---

*[pkg/storage/replica.go, line 1967 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWLxAOsp16F32d1nH8:-KYWLxAOsp16F32d1nH9:b28cux5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/storage/replica.go#L1967)):*
> ```Go
> 		}
> 	} else {
> 		// For lease commands, use the provided previous lease for verification.
> ```

nit: this would be easier to read if the `if` was written with the positive case first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.go, line 835 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWLfad6JrI2GxIav8_:-KYneN-4CycWuEwZSz6Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/roachpb/api.go#L835)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

redirectOnOrAcquireLease?
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 1967 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWLxAOsp16F32d1nH8:-KYneNkTjUWbFqg0IQh0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/storage/replica.go#L1967)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: this would be easier to read if the `if` was written with the positive case first.
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 1968 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYWhndt1zwOS05CpT5O:-KYnpMrIfEDlq5xQqksL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f106eb47a99e50bdd5f4e4a207e0b9ed754d3ab1/pkg/storage/replica.go#L1968)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Instead of this type switch, we could define an interface and a method on the request types (like we did for `roachpb.combinable`). I prefer to keep things like this in the `roachpb` package; it's not obvious otherwise that every request with the `skipLease` flag needs a corresponding entry here. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209)*

**Comment by spencerkimball** [comment]
Writing a unittest for this is proving incredibly difficult. Because this change seems to actually prevent badness during node recovery after chaos events, I'd like to get it in. I'm filing an issue (#12285) for writing a unittest and would appreciate suggestions.

**Comment by tamird** [comment]
Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209)*

**Comment by andreimatei** [comment]
LGTM

What's up with the changes in the queues?

For a unit test, what would we like? A prop-eval-kv-only test demonstrating that a command evaluated under one lease and applied under another is rejected at apply time? If so, I guess you could add a testing hook in `replica.propose()`, similar to `TestingCommandFilter`, and block a lease transfer just before `raftGroup.Propose()`. Then perform another transfer and let it complete, unblock the original and check that it doesn't do anything?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYo_zWICrNYdsM-_Ob2:-KYo_zWICrNYdsM-_Ob3:b-5dyvfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.go#L139)):*
> ```Go
> // was proposed.
> type leaseRequestor interface {
> 	prevLease() *Lease
> ```

would `proposedUnder` be a better name?
It's also called `originLease` in the RaftCmd and the EvalResult....

---

*[pkg/roachpb/api.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoaL5s5bLt03uCAV6b:-KYoaL5s5bLt03uCAV6c:b4ph5eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.go#L849)):*
> ```Go
> func (*TransferLeaseRequest) flags() int {
> 	// TransferLeaseRequest requires the lease, which is checked in
> 	// `AdminTransferLease()` at proposal time and in the usual way for write
> ```

maybe this comment needs to be updated now for prop-eval KV, seeing how there's no longer an "apply time" to speak of here.

---

*[pkg/roachpb/api.proto, line 624 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoahRwOw7rv-AqdcSY:-KYoahRwOw7rv-AqdcSZ:bcxl5nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.proto#L624)):*
> ```protobuf
>   // The previous lease is specified by the caller to verify
>   // it has not changed when executing this command.
>   optional Lease prev_lease = 3;
> ```

maybe `proposed_under`?

---

*[pkg/roachpb/batch.go, line 156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYocuLPLr1rV3fWVdGA:-KYobRHkaR5jtIn-C-Jj:b3o9xsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/batch.go#L156)):*
> ```Go
> // of proposal, for a request lease or transfer lease request. If the
> // batch does not contain a single lease request, returns an error.
> func (ba *BatchRequest) GetPrevLeaseForLeaseRequest() (*Lease, error) {
> ```

is this method on the batch really needed? Just replace it in the caller with `ba.Requests[0].GetInner().(leaseRequestor).prevLease()`. The caller is in a `if IsSingleSkip...` block.

---

*[pkg/roachpb/batch.go, line 162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoau1uyAjgkMc4C3t_:-KYoau1uyAjgkMc4C3ta:bwfvp0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/batch.go#L162)):*
> ```Go
> 	lr, ok := ba.Requests[0].GetInner().(leaseRequestor)
> 	if !ok {
> 		return nil, errors.Errorf("request %T does not implement leaseRequestor", ba.Requests[0])
> ```

nit: bleah, let's just do a naked type assertion and panic if interface is not implemented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-:-KYohWDBs6IJ29OtMd59:b-vzwbpv)*

**Comment by spencerkimball** [comment]
The queues didn't require the lease status as originally anticipated, so I simplified them.

I've pasted your comment into the issue tracking the proposed unittest.

---

Review status: 16 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/roachpb/api.go, line 139 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYo_zWICrNYdsM-_Ob2:-KYp8Lqbwsml8TKxTaly:b9oi4qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.go#L139)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would `proposedUnder` be a better name?
It's also called `originLease` in the RaftCmd and the EvalResult....
</blockquote></details>

`originLease` isn't quite right and risks confusion. `prevLease` seems fine to me. Is there something technically inaccurate about the name or you just think it's too pedestrian?

---

*[pkg/roachpb/api.go, line 849 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoaL5s5bLt03uCAV6b:-KYp8lfK1NJF-RoZ0Nak:bp0tvad) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.go#L849)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe this comment needs to be updated now for prop-eval KV, seeing how there's no longer an "apply time" to speak of here.
</blockquote></details>

I added a TODO for you.

---

*[pkg/roachpb/api.proto, line 624 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoahRwOw7rv-AqdcSY:-KYp8nNPNTjlOU0Yl8yh:bjy3gfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/api.proto#L624)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe `proposed_under`?
</blockquote></details>

See previous comment. I don't think that the rename is giving us anything extra. It might even be more confusing because this isn't guaranteed to be what the lease command is in fact proposed under. It might be changed between when it's set and when it's proposed. Talking about proposals here risks confusing this code path with the actual Raft proposal which is at a lower level.

---

*[pkg/roachpb/batch.go, line 156 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYocuLPLr1rV3fWVdGA:-KYp9P8nTczbKWPSZImQ:b998s5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/batch.go#L156)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this method on the batch really needed? Just replace it in the caller with `ba.Requests[0].GetInner().(leaseRequestor).prevLease()`. The caller is in a `if IsSingleSkip...` block.
</blockquote></details>

Well the reason to have this method on the batch is to avoid exporting any of this, similar to the `combinable` interface.

---

*[pkg/roachpb/batch.go, line 162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-KYoau1uyAjgkMc4C3t_:-KYp9bWfsjcz4TP0T7G6:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb5e1adbc9eb523897cc8ceb5045c3d58d5d08e/pkg/roachpb/batch.go#L162)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: bleah, let's just do a naked type assertion and panic if interface is not implemented
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12209#-:-KYp7vfjcP5gyAZlEMAT:bvpc1oj)*

**Pull request merged**
