### PR TITLE
vendor: bump Pebble to 01067adc

### PR DESCRIPTION
**Pull request by sumeerbhola**
01067adc db: add test for ingest idempotence
69de2263 internal/manifest: fix typo in comment for SeekGE
4e7ee20a db: fix Iterator direction switching behavior
7c3b8ea9 Merge pull request #983 from otan-cockroach/go1.15
d87c944f travis: upgrade to go 1.15 for testing

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLojdRM2RPxukngR8j1:bf1axlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
> ```XML
> 	github.com/cockroachdb/crlfmt v0.0.0-20200116191136-a78e1c207bc0
> 	github.com/cockroachdb/datadriven v1.0.1-0.20201022032720-3e27adf87325
> 	github.com/cockroachdb/errors v1.8.0
> ```

The cockroachdb/errors and x/sys changes got picked up when running `go get -u github.com/cockroachdb/pebble@01067adc`

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLrc_7D0IngbI4ihMhY:b-yxyg22) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The cockroachdb/errors and x/sys changes got picked up when running `go get -u github.com/cockroachdb/pebble@01067adc`
</blockquote></details>

I looked at the pebble versions for these, and it is at an earlier version than cockroachdb
github.com/cockroachdb/errors v1.2.4
golang.org/x/sys v0.0.0-20200519105757-fe76b779f299

So I don't understand why `go get` is making these changes.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, @otan, and @petermattis)

___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLrecPh-Jz9YBLvWzMe:bb7uh50) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I looked at the pebble versions for these, and it is at an earlier version than cockroachdb
github.com/cockroachdb/errors v1.2.4
golang.org/x/sys v0.0.0-20200519105757-fe76b779f299

So I don't understand why `go get` is making these changes.

</blockquote></details>

@otan Can you tell us what is going on here? These spurious bumps of packages cause me anxiety when all we want to bump is Pebble.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @otan)

___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLrh-IqDXNt9E4IKz5x:bjt6kw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@otan Can you tell us what is going on here? These spurious bumps of packages cause me anxiety when all we want to bump is Pebble.
</blockquote></details>

Oliver is on vacation today. Not sure if anyone else would know the answer. Perhaps ping #dev-inf.

**Comment by itsbilal** [comment]
If the side-bumps are concerning enough, I've often pushed a vendor bump PR where I've manually reverted all the SHA changes other than `cockroachdb/pebble`. It requires a manual step but averts this discussion.

**Review by sumeerbhola — COMMENTED** [review]
> If the side-bumps are concerning enough, I've often pushed a vendor bump PR where I've manually reverted all the SHA changes other than cockroachdb/pebble. It requires a manual step but averts this discussion.

I'll do that and close this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-:-MLrtE1T1rDIIStjqHU2:b-j9yn8g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @otan)

**Comment by sumeerbhola** [comment]
https://github.com/cockroachdb/cockroach/pull/56578

**Comment by otan** [comment]
___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLuYYqfBAT4a82BFYAx:bmfozr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oliver is on vacation today. Not sure if anyone else would know the answer. Perhaps ping #dev-inf.
</blockquote></details>

go get seems to like upgrading things (especially sys) because some other dependent package does not have it pinned. my guess is some test. it's kind of annoying, but i'm not sure how to find out what it is, e.g.

```
$ go mod why github.com/cockroachdb/errors@v1.8.0
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-bin
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-cockroach
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-out
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-testlogs
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
# github.com/cockroachdb/errors@v1.8.0
(main module does not need package github.com/cockroachdb/errors@v1.8.0)

$  go mod why golang.org/x/sys
go: finding module for package golang.org/x/sys
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-bin
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-cockroach
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-out
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-testlogs
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
# golang.org/x/sys
(main module does not need package golang.org/x/sys)
```

**Comment by otan** [comment]
___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLudcEf8iH8ex0-VgAL:bxscmqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

go get seems to like upgrading things (especially sys) because some other dependent package does not have it pinned. my guess is some test. it's kind of annoying, but i'm not sure how to find out what it is, e.g.

```
$ go mod why github.com/cockroachdb/errors@v1.8.0
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-bin
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-cockroach
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-out
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-testlogs
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
# github.com/cockroachdb/errors@v1.8.0
(main module does not need package github.com/cockroachdb/errors@v1.8.0)

$  go mod why golang.org/x/sys
go: finding module for package golang.org/x/sys
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-bin
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-cockroach
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-out
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/bazel-testlogs
warning: ignoring symlink /Users/otan/go/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
# golang.org/x/sys
(main module does not need package golang.org/x/sys)
```
</blockquote></details>

apparently from my browsing on line it's because of some transitive package o_o

**Comment by otan** [comment]
___
*[go.mod, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56534#-MLojdRLBthBylO-zsm6:-MLudnQT8iWXRDySeEMe:b-1u4two) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e3c07a186ec099d8424ab14da41bfa65f0b5746/go.mod#L39)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

apparently from my browsing on line it's because of some transitive package o_o
</blockquote></details>

and we can force pins by having a replace at the bottom, e.g. `replace golang.org/x/sys => golang.org/x/sys <version>`

**Pull request closed without merging**
