### PR TITLE
opt,sql: teach the optimizer that inverted join can preserve ordering

### LINKED ISSUE #52625: opt: inverted join can preserve input ordering
The optimizer needs to be taught that the inverted joiner can preserve the input ordering (like [lookup join](https://github.com/cockroachdb/cockroach/blob/635aad38079d0ef93d39663bb514add012339351/pkg/sql/opt/ordering/ordering.go#L119)).

Once we do that, the [factory method](https://github.com/cockroachdb/cockroach/blob/635aad38079d0ef93d39663bb514add012339351/pkg/sql/opt_exec_factory.go#L728) can no longer ignore the output ordering - it needs to be stored in the `invertedJoinNode` and hooked up to [planReqOrdering](https://github.com/cockroachdb/cockroach/blob/635aad38079d0ef93d39663bb514add012339351/pkg/sql/plan_ordering.go#L23) (which will be used by the [distsql physical planner](https://github.com/cockroachdb/cockroach/blob/635aad38079d0ef93d39663bb514add012339351/pkg/sql/distsql_physical_planner.go#L2163) to maintain order when merging distributed streams).

### PR DESCRIPTION
**Pull request by rytaft**
Release justification: Since the inverted join is a new operator for this
release, this change fits into category 2: bug fixes and low-risk updates
to new functionality.

This commit teaches the optimizer that an inverted join can pass through
the ordering of its input. This allows us to push sorts down the tree below
an inverted join, or take advantage of the output ordering for more efficient
`GROUP BY` operations.

Fixes #52625

Release note (performance improvement): The optimizer is now aware that the
inverted join operator can preserve the ordering of its input. This enables
the optimizer to eliminate unnecessary sort operations and produce more
efficient plans in some cases.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53502#-:-MFgi7gn7TaEW2QxMTBk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by RaduBerinde — APPROVED** [review]
I think the distsql version should be bumped.

**Review by rytaft — COMMENTED** [review]
TFTRs!

> I think the distsql version should be bumped.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53502#-:-MFhB__lEOrBGzbreOnV:bmaj2vw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53502#-:-MFhRE4bAEH0w_OYLqUA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53502#-:-MFhlMrL0Cal4TzP7ftL:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
