### PR TITLE
tracing: optimize context.Context allocations

### PR DESCRIPTION
**Pull request by tbg**
Since in our practical usage of tracing each created `Span` is certain to
be wrapped in a `Context`, it makes sense to allocate that wrapping
Context alongside the Span.

This does not immediately change the allocations in my sanity check

```
go test -benchtime 1000x -benchmem -memprofilerate 1 -memprofile ctx.prof \
        -bench 'BenchmarkScan/MultinodeCockroach/count=1$/limit=1$' \
        ./pkg/bench/
[...] 809 allocs/op
```

because the current hot path in `startSpanGeneric` is that in which the
noop span is returned, and that path does not benefit from the
optimization.

However, with `trace.mode = background`, we get ~850 alloc/ops with this
commit, and ~884 allocs/op without. (There is certainly a fair bit of noise in
this, so don't walk away from this thinking that we've saved 34 allocs - the
message is "it helps in that case").

Additionally, the newly added microbenchmark shows that StartSpanCtx clocks in
at a single allocation (when called without options that require additional
allocations).

More optimizations are possible and will be driven by experiments. I expect
that these will primarily target the allocation overhead of constructing
SpanOptions, and the implementation of WithTags.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
"First to commits" refers to an issue, not a PR. Which PR is it?

Last 3 commits LGTM, but I'd like to have a look after the necessary rebase.

> Reviewed 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58123#-:-MP4QI5SAzwETANncW4D:b-xv7uvr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Review by tbg — COMMENTED** [review]
I did the rebase - no conflicts. The previous PR was the StartSpanCtx PR. I removed the reference since the rebase is now complete.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58123#-:-MP4UcDQ3O-Jtxmiiodh:bb70n55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r6, 2 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58123#-:-MP4YStK7AwScMOyVvsT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Comment by tbg** [comment]
TFTR! Fixed the (somewhat bogus) lint failure.

bors r=knz

**Pull request merged**
