### PR TITLE
roachtest/decomission: no t.Fatal on goroutine

### LINKED ISSUE #51553: roachtest: Nightly job aborting after running 28 tests
**Describe the problem**

It looks like the last 3 Roachtest Nightly jobs for the master branch quit early after only running 28 tests. Examples: [one](https://teamcity.cockroachdb.com/viewLog.html?buildId=2096175&buildTypeId=Cockroach_Nightlies_WorkloadNightly), [two](https://teamcity.cockroachdb.com/viewLog.html?buildId=2093071&buildTypeId=Cockroach_Nightlies_WorkloadNightly), and [three](https://teamcity.cockroachdb.com/viewLog.html?buildId=2090320&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildResultsDiv&branch_Cockroach_Nightlies=%3Cdefault%3E). 

I don't know if it's the cause of the problem, but I see this in all the logs:

```
[02:23:38][Step 2/2] panic: t.Fatal() was called
[02:23:38][Step 2/2] 
[02:23:38][Step 2/2] goroutine 5417 [running]:
[02:23:38][Step 2/2] main.(*test).fatalfInner(0xc000166d80, 0x0, 0x0, 0xc000d4e5b0, 0x1, 0x1)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:279 +0xcd
[02:23:38][Step 2/2] main.FatalIfErr(...)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test.go:285
[02:23:38][Step 2/2] main.(*cluster).Start(0xc000a921e0, 0x4846940, 0xc0006daf00, 0xc000166d80, 0xc0010e5f00, 0x2, 0x2)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1996 +0xe5
[02:23:38][Step 2/2] main.runDecommission.func5(0x0, 0x0)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/decommission.go:251 +0x926
[02:23:38][Step 2/2] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000426720, 0xc000d305f0)
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
[02:23:38][Step 2/2] created by golang.org/x/sync/errgroup.(*Group).Go
[02:23:38][Step 2/2] 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
[02:23:38][Step 2/2] + upload_stats
[02:23:38][Step 2/2] + [[ master == \m\a\s\t\e\r ]]
[02:23:38][Step 2/2] + bucket=cockroach-nightly-gce
[02:23:38][Step 2/2] + [[ gce == \g\c\e ]]
[02:23:38][Step 2/2] + bucket=cockroach-nightly
[02:23:38][Step 2/2] + cd /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts
[02:23:38][Step 2/2] ++ sed 's/^\.\///'
[02:23:38][Step 2/2] ++ find . -name stats.json
[02:23:38][Step 2/2] + IFS=
[02:23:38][Step 2/2] + read -r f
[02:23:38][Step 2/2] + gsutil cp '' gs://cockroach-nightly/artifacts/20200716-2093071/
[02:23:38][Step 2/2] CommandException: No URLs matched: 
[02:23:39][Step 2/2] Process exited with code 1
```

**To Reproduce**

Run a Roachtest Nightly job.

**Expected behavior**

All of the tests should run. There are a few hundred tests.

**Additional context**

The fact that not all tests are being run isn't super obvious. See: #50618

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #51553

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jlinder, and @tbg)

___
*[pkg/cmd/roachtest/decommission.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51649#-MCmXQaV6fUAXstIC5vs:-MCmXQaV6fUAXstIC5vt:bi4loys) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb579e3aa868babcd5d518fa26ef786584bf916/pkg/cmd/roachtest/decommission.go#L251)):*
> ```
> --join
> ```


I think now I see why the error was happening in the first place -- it's passing the `--join` flag here, but as of very recently, that causes an error when used with `start-single-node`. roachprod will automatically use `start-single-node` if it's making a 1 node cluster.

idk if this PR should also address this usage of `--join`

cc @irfansharif

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @tbg)

___
*[pkg/cmd/roachtest/decommission.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51649#-MCmXQaV6fUAXstIC5vs:-MCmYsz94eo5tliNay2V:b3xi8zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb579e3aa868babcd5d518fa26ef786584bf916/pkg/cmd/roachtest/decommission.go#L251)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> ```
> --join
> ```


I think now I see why the error was happening in the first place -- it's passing the `--join` flag here, but as of very recently, that causes an error when used with `start-single-node`. roachprod will automatically use `start-single-node` if it's making a 1 node cluster.

idk if this PR should also address this usage of `--join`

cc @irfansharif 
</blockquote></details>

You're right that this was what was causing the failure. This PR shouldn't, I'll send one separately. https://github.com/cockroachdb/cockroach/issues/51652.

**Review by andreimatei — COMMENTED** [review]
someone stamp a bro please

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51649#-:-MCmavok9fN9_PyvX7hU:b21nehm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder, @rafiss, and @tbg)

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51649)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jlinder, and @tbg)

___
*[pkg/cmd/roachtest/decommission.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51649#-MCmXQaV6fUAXstIC5vs:-MCmbDuwCLSMPLTJcpbI:b-b89gs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb579e3aa868babcd5d518fa26ef786584bf916/pkg/cmd/roachtest/decommission.go#L251)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

You're right that this was what was causing the failure. This PR shouldn't, I'll send one separately. https://github.com/cockroachdb/cockroach/issues/51652. 
</blockquote></details>

thanks! then this one lgtm!

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51649#-:-MCmdqbL6Br8luDz0OIh:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @jlinder, and @tbg)

**Pull request merged**
