### PR TITLE
opt: do not inline NOT MATERIALIZED CTEs with side-effects

### LINKED ISSUE #95360: opt: InlineWith should not inline mutations into subqueries and apply-joins
The `InlineWith` normalization rule can inline a mutation into subqueries or apply-joins, causing the mutations to be executed more than once. For example, notice that the INSERT is executed five times:

```
defaultdb> SELECT version();
                                          version
-------------------------------------------------------------------------------------------
  CockroachDB CCL v22.2.2 (aarch64-apple-darwin21.2, built 2023/01/04 17:38:41, go1.19.1)
(1 row)

defaultdb> CREATE TABLE corr ( k INT PRIMARY KEY, i INT);
CREATE TABLE

defaultdb> CREATE TABLE corr2 (k INT, i INT);
CREATE TABLE

defaultdb> INSERT INTO corr VALUES (1, 10), (2, 22), (3, 30), (4, 40), (5, 50);
INSERT 0 5

defaultdb> WITH insVals AS NOT MATERIALIZED (INSERT INTO corr2 VALUES (1, 10) RETURNING k)
SELECT * FROM corr
WHERE EXISTS (SELECT * FROM insVals WHERE k = corr.k UNION ALL SELECT k FROM corr c3 WHERE k = corr.k);
  k | i
----+-----
  1 | 10
  2 | 22
  3 | 30
  4 | 40
  5 | 50
(5 rows)

defaultdb> SELECT * FROM corr2;
  k | i
----+-----
  1 | 10
  1 | 10
  1 | 10
  1 | 10
  1 | 10
(5 rows)
```

This is not consistent with Postgres which guarantees that:

> Data-modifying statements in WITH are executed exactly once, and always to completion, independently of whether the primary query reads all (or indeed any) of their output.

_^ From the [Postgres Docs](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-MODIFYING)._

We should prevent `InlineWith` from inlining into correlated subqueries (and maybe uncorrelated, unless they are guaranteed to execute onle once - even lazy ones?), and apply-joins.

Jira issue: CRDB-23481

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: use enum for CTE materialize clause

The `tree.MaterializeClause` struct has been replaced with a 3-value
enum to represent `MATERIALIZED`, `NOT MATERIALIZED`, and an empty
materialization clause (the default). These three clauses represent
three distinct modes of behavior for CTEs. Previously, the
`tree.MaterializeClause` struct had both a `Set` boolean and a
`Materialize` boolean which allowed four possible combinations, and
confusingly implied that `NOT MATERIALIZED` (`Set: true, Materialize:
false`) was equivalent to an empty clause (`Set: false, Materialize:
false`), with the only difference being the explicitness of the clause
in the source SQL. In reality, there are behavioral differences between
a CTE with an empty materialize clause and `NOT MATERIALIZED`. Using an
enum to represent these clauses is more natural and less error-prone
than a two-boolean struct.

Release note: None

#### opt: do not inline NOT MATERIALIZED CTEs with side-effects

Previously, any `NOT MATERIALIZED` CTE was inlined, even if it had
side-effects (e.g., a volatile expression or mutation). This did not
match Postgres's behavior. The Postgres documentation mentions that
"data-modifying statements in WITH are executed exactly once"[^1], but
omits any specifics about data-modifying statements in
`NOT MATERIALIZED` CTEs. A comment in the Postgres source code makes the
intended behavior clear[^2].

Fixes #95360

Release note (bug fix): A bug has been fixed that could cause
expressions with side-effects (e.g., volatile expressions or
data-modifying statements like `INSERT`s) in `NOT MATERIALIZED` CTEs to
be executed more than once. This bug was present since
`NOT MATERIALIZED` was first supported in version 20.2.0. Our CTE docs
should be updated with the following changes:
  1. Under "Data-modifying statements", we should mention that they are
     guaranteed to be executed exactly once, even if the
     `NOT MATERIALIZED` is specified.
  2. In the description of `MATERIALIZED` / `NOT MATERIALIZED`, we
     should mention: `MATERIALIZED` forces the CTE to be materialized so
     that it is only executed once, and `NOT MATERIALIZED` is a hint to
     the optimizer to inline the CTE as long as it doesn't affect other
     objects in the database, even if it is used in the query multiple
     times.

[^1]: https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-MODIFYING
[^2]: https://github.com/postgres/postgres/blob/15eb1228800a35042ef318f941173aa8b89002d1/src/backend/optimizer/plan/subselect.c#L921-L951

#### opt: refactor InlineAnyWithScan rule

The `InlineAnyWithScan` rules has be renamed `InlineAnyWithScanOfValues`
and the code and comments have been refactored to make it clear that
this rule is only valid for WithScan expressions that reference Values
expressions.

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
Thanks for fixing this!

> Reviewed 14 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-:-NM5UcAnASADUouRSlls:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5QB6SAEBS3PPdKPeI):*
Should this indicate it's more than a bug fix, since according to our docs it sounds like it's working as designed. Under the "MATERIALIZED/NOT MATERIALIZED" clause it says:
> Override the optimizer's decision to materialize (i.e., store the results) of the common table expression. By default, the optimizer materializes the common table expression if it affects other objects in the database, or if it is used in the query multiple times.

So, instead of a hard override it will now only override in legal non-mutation cases. The more we can put in here as instructions for the docs writers, the better.
___
*[`pkg/sql/opt/memo/expr_format.go` line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5OQoo4ZT_tW7s_Yee:-NM5OQoo4ZT_tW7s_Yef:brhriao) ([raw file](https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/opt/memo/expr_format.go#L697)):*
> ```Go
> 			tp.Child("materialized")
> 		case tree.CTEMaterializeNever:
> 			tp.Child("not-materialized")
> ```

Do we want to print "not-materialized" for the `CTEMaterializeDefault` case too, so we can easily see in the EXPLAIN the materialization choice made (and to aid in debugging).  Since the `WithExpr` has a binding at this time, we could also examine it to see if it's volatile, and if so, print "materialized".
___
*[`pkg/sql/opt/norm/with_funcs.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5W6xI7l7EYP8pmT_u:-NM5W6xI7l7EYP8pmT_v:b-tj3ssa) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L44)):*
> ```Go
> func (c *CustomFuncs) CanInlineWith(binding, expr memo.RelExpr, private *memo.WithPrivate) bool {
> 	if private.Mtr == tree.CTEMaterializeAlways ||
> 		binding.Relational().VolatilitySet.HasVolatile() {
> ```

Should we instead update `private.Mtr` to be `tree.CTEMaterializeAlways` when the binding expression is volatile?  We already do that for cases with an ordering:
https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/opt/optbuilder/with.go#L97-L100

That way all the info needed is held in `Mtr`.
___
*[`pkg/sql/opt/norm/with_funcs.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5Tvc04MwRzqE5eT1y:-NM5Tvc04MwRzqE5eT1z:bv6o8w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L105)):*
> ```Go
> 		return false
> 	}
> 	expr := c.mem.Metadata().WithBinding(private.With)
> ```

Should we put in an explicit check here? :
```
	if expr.Relational().VolatilitySet.HasVolatile() {
		return false
	}

```
...to make sure if someone modifies this function in the future to handle more cases they don't try to handle volatile expressions.

**Review by DrewKimball — COMMENTED** [review]
Nice! :lgtm: after comments are addressed.

> Reviewed 14 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-:-NM5fM8_DnxIpL8DUGNT:b53thz0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/with_funcs.go` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5eAMa3bOJ2H5HLnRi:-NM5eAMa3bOJ2H5HLnRj:b-idhzi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L25)):*
> ```Go
> //
> //  1. The CTE expression is not volatile.
> //  2. The CTE expression does not contain mutation statements, like
> ```

[nit] Doesn't the presence of mutations imply volatility?
___
*[`pkg/sql/sem/tree/with.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5d4lT709SbeyVq3Bv:-NM5d4lT709SbeyVq3Bw:b-3g52d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/sem/tree/with.go#L30)):*
> ```Go
> type CTEMaterializeClause int8
> 
> // The values for NullType.
> ```

[nit] This comment needs to be updated.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5QB6SAEBS3PPdKPeI):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this indicate it's more than a bug fix, since according to our docs it sounds like it's working as designed. Under the "MATERIALIZED/NOT MATERIALIZED" clause it says:
> Override the optimizer's decision to materialize (i.e., store the results) of the common table expression. By default, the optimizer materializes the common table expression if it affects other objects in the database, or if it is used in the query multiple times.

So, instead of a hard override it will now only override in legal non-mutation cases. The more we can put in here as instructions for the docs writers, the better.

</blockquote></details>

Great idea. I've added some suggested docs changes to the release note. Let me know if you think this is sufficient.
___
*[`pkg/sql/opt/memo/expr_format.go` line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5OQoo4ZT_tW7s_Yee:-NM6-3omBZk6clV8Mgvh:b-tbwdv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/opt/memo/expr_format.go#L697)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Do we want to print "not-materialized" for the `CTEMaterializeDefault` case too, so we can easily see in the EXPLAIN the materialization choice made (and to aid in debugging).  Since the `WithExpr` has a binding at this time, we could also examine it to see if it's volatile, and if so, print "materialized".
</blockquote></details>

We already print `volatile` if it's volatile. I think `materialized` and `not-materialized` should map to the options provided to the CTE to avoid having multiple definitions for those terms.
___
*[`pkg/sql/opt/norm/with_funcs.go` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5eAMa3bOJ2H5HLnRi:-NM659Q2EOtPa_py5pxb:bbct8n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L25)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Doesn't the presence of mutations imply volatility?
</blockquote></details>

Yes, good point. I've updated the comment.
___
*[`pkg/sql/opt/norm/with_funcs.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5W6xI7l7EYP8pmT_u:-NM61Kui7A4S8VTE8sHM:bniwk9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L44)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should we instead update `private.Mtr` to be `tree.CTEMaterializeAlways` when the binding expression is volatile?  We already do that for cases with an ordering:
https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/opt/optbuilder/with.go#L97-L100

That way all the info needed is held in `Mtr`.
</blockquote></details>

I'd rather not conflate the two distinct concepts. One represents the desire to materialize or not, and the other is a property of the inner expression. `CanInlineWith` seems like the best place to consider both of those pieces of information to determine if a CTE can be inlined.
___
*[`pkg/sql/opt/norm/with_funcs.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5Tvc04MwRzqE5eT1y:-NM65gE42nsTue6asGYq:b-te3wxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L105)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should we put in an explicit check here? :
```
	if expr.Relational().VolatilitySet.HasVolatile() {
		return false
	}

```
...to make sure if someone modifies this function in the future to handle more cases they don't try to handle volatile expressions.
</blockquote></details>

This made me think - this rule doesn't respect the desired behavior that by default a multiply-referenced CTE should not be inlined, but since it only operates on constant Values expressions, which are basically "materialized" by definition, I think it should be fine. But I don't think this rule is valid for non-Values expressions, so I've added another commit that makes this clear and less likely for the rule to be incorrectly altered in the future.
___
*[`pkg/sql/sem/tree/with.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5d4lT709SbeyVq3Bv:-NM62xxV0vBFP-BvJ5-w:b5i1zjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/sem/tree/with.go#L30)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This comment needs to be updated.
</blockquote></details>

Good catch, I removed it.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-:-NM6rGG92dRZYx7NYGQo:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5QB6SAEBS3PPdKPeI):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great idea. I've added some suggested docs changes to the release note. Let me know if you think this is sufficient.
</blockquote></details>

Looks good. Be sure to also update the Github comment. I believe that's where the final commit message comes from.
___
*[`pkg/sql/opt/norm/with_funcs.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5W6xI7l7EYP8pmT_u:-NM6pcrSA2lS_5M0pQZi:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L44)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'd rather not conflate the two distinct concepts. One represents the desire to materialize or not, and the other is a property of the inner expression. `CanInlineWith` seems like the best place to consider both of those pieces of information to determine if a CTE can be inlined.
</blockquote></details>

OK
___
*[`pkg/sql/opt/norm/with_funcs.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5Tvc04MwRzqE5eT1y:-NM6pmUl-9ekouNXIqIc:b-pg6qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/93090e0c6dd3f36296cf4dca1adea4a784d336cc/pkg/sql/opt/norm/with_funcs.go#L105)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This made me think - this rule doesn't respect the desired behavior that by default a multiply-referenced CTE should not be inlined, but since it only operates on constant Values expressions, which are basically "materialized" by definition, I think it should be fine. But I don't think this rule is valid for non-Values expressions, so I've added another commit that makes this clear and less likely for the rule to be incorrectly altered in the future.
</blockquote></details>

OK. The refactor looks good. I recall when creating this rule there were some other non-Values expressions that would be useful to handle. But a new rule could always be added to keep each case separate.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/memo/expr_format.go` line 697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5OQoo4ZT_tW7s_Yee:-NM6rYol4ucN49HIgjGE:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/11c1914461564b6cd770cf57b92299e21723d388/pkg/sql/opt/memo/expr_format.go#L697)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We already print `volatile` if it's volatile. I think `materialized` and `not-materialized` should map to the options provided to the CTE to avoid having multiple definitions for those terms.
</blockquote></details>

OK

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95454)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @msirek)

___
*[`-- commits` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95454#-NM5QB6SAEBS3PPdKPeI):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Looks good. Be sure to also update the Github comment. I believe that's where the final commit message comes from.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
