### PR TITLE
security: move logic in `security/password.go` to `security/password`

### PR DESCRIPTION
**Pull request by ZhouXing19**
This commit is to host the password logic in a separate package,
`security/password/`.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks for the hard work :100: 

you also need to move password_test.go. see my comment below.

No release note needed here.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-:-N0Cxhab0P_1mx7WoL_H:b-2tfp3j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[pkg/security/password_test.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0CxZIR87lX52ktvtLe:-N0CxZIR87lX52ktvtLf:bvjs0ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ac5a206aa1e5b65d7b27559aee445ff87888c5/pkg/security/password_test.go#L1)):*
> ```Go
> // Copyright 2022 The Cockroach Authors.
> ```

This test file should be moved to the new package.

Use `package password_test` at the top to ensure the dependencies are separate.

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/security/password_test.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0CxZIR87lX52ktvtLe:-N0D-FTl6xmi_ZQoAB0O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ac5a206aa1e5b65d7b27559aee445ff87888c5/pkg/security/password_test.go#L1)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This test file should be moved to the new package.

Use `package password_test` at the top to ensure the dependencies are separate.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0F79h839Fapjxuxt1A):*
?
___
*[pkg/security/password/password_test.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0F7GXLCxyHXzl3QGpz:-N0F7GXLCxyHXzl3QGq-:b4lmf4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/259ef7351d00f236c265e1709fa59663842a23a1/pkg/security/password/password_test.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package password
> ```

Are you sure `package password_test` is not needed? By placing the test file inside the same package, you bring in the settings/cluster dependency to package `password`.

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0F79h839Fapjxuxt1A):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed.
___
*[`pkg/security/password/password_test.go` line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-N0F7GXLCxyHXzl3QGpz:-N0W4xmaAEzqttf4169U:b-wergtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/259ef7351d00f236c265e1709fa59663842a23a1/pkg/security/password/password_test.go#L11)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure `package password_test` is not needed? By placing the test file inside the same package, you bring in the settings/cluster dependency to package `password`.
</blockquote></details>

Added the `password_test` package.

**Review by rafiss — APPROVED** [review]
lgtm!

the failure is from linting:
```
        pkg/security/password/password.go:94:6: type name will be used as password.PasswordHash by other packages, and that stutters; consider calling this Hash
    --- FAIL: TestLint/TestGolint (58.64s)
```

I'm not sure I agree with the litner's suggestion. we could add an exception here, which it looks like others have done too: https://github.com/cockroachdb/cockroach/blob/c67668928b7d9bbfe3df5d293397585dca4ca9d6/pkg/testutils/lint/lint_test.go#L1668

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-:-N0bRnKt9UaVwh68iX2b:b-km2s73)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by ZhouXing19 — COMMENTED** [review]
Thanks! Added this case in `lint_test.go`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332#-:-N0bYfNuBV9B1AxglkkN:b-u6n096)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — APPROVED** [review]
> Reviewed 8 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ZhouXing19)

**Comment by ZhouXing19** [comment]
Thanks!

bors r+

**Pull request merged**
