### PR TITLE
workload/schemachange: enable alter pk

### LINKED ISSUE #128656: roachtest: backup-restore/small-ranges failed [schemachange workload failed to receive error when indexable column used for PK)
roachtest.backup-restore/small-ranges [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16387742?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16387742?buildTab=artifacts#/backup-restore/small-ranges) on master @ [2558f3f3a1dab0907db3dafd510ec5bc2464073f](https://github.com/cockroachdb/cockroach/commits/2558f3f3a1dab0907db3dafd510ec5bc2464073f):

```
(monitor.go:154).Wait: monitor failure: full command output in run_062055.945796018_n4_COCKROACHRANDOMSEED9.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/backup-restore/small-ranges/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16387742/backup-restore-small-ranges/1723183169143/1723187540959)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/small-ranges.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-41128

### LINKED ISSUE #130196: workload/schemachange: fix is_unique check for alter PK op
Currently, our workload determines whether a column is unique by the following query:
https://github.com/cockroachdb/cockroach/blob/47b252bed0b7a54505deac3e6be4bfc9d9547b88/pkg/workload/schemachange/operation_generator.go#L2546-L2553

This is not entirely accurate as a unique constraint that gets added by a schemachange like:
```
demo@127.0.0.1:26257/demoapp/movr> create table t(i int not null, j int not null, primary key (i, j));                              
CREATE TABLE

Time: 11ms total (execution 11ms / network 0ms)
```

Applies to the composite key (i, j) -- not i and j separately. However, the above query will say that both i & j individually have unique constraints 

<details>

<summary> contents of table for table t </summary>

```
demo@127.0.0.1:26257/demoapp/movr> select * from crdb_internal.table_indexes join crdb_internal.index_columns using (descriptor_id) 
                                -> where table_indexes.is_unique and table_indexes.descriptor_id = 't'::regclass::oid;              
  descriptor_id | descriptor_name | index_id | index_name | index_type | is_unique | is_inverted | is_sharded | is_visible | visibility | shard_bucket_count |        created_at         |                   create_statement                    | descriptor_name | index_id | index_name | column_type | column_id | column_name | column_direction | implicit
----------------+-----------------+----------+------------+------------+-----------+-------------+------------+------------+------------+--------------------+---------------------------+-------------------------------------------------------+-----------------+----------+------------+-------------+-----------+-------------+------------------+-----------
            116 | t               |        1 | t_pkey     | primary    |     t     |      f      |     f      |     t      |          1 |               NULL | 2024-09-05 21:31:21.02943 | CREATE UNIQUE INDEX t_pkey ON public.t (i ASC, j ASC) | t               |        1 | t_pkey     | key         |         1 | i           | ASC              |    f
            116 | t               |        1 | t_pkey     | primary    |     t     |      f      |     f      |     t      |          1 |               NULL | 2024-09-05 21:31:21.02943 | CREATE UNIQUE INDEX t_pkey ON public.t (i ASC, j ASC) | t               |        1 | t_pkey     | key         |         2 | j           | ASC              |    f
(2 rows)

Time: 12ms total (execution 11ms / network 1ms)
```

</details>

This can become an issue with our workload if the following set of events occur:
```
demo@127.0.0.1:26257/demoapp/movr> create table t(i int not null, j int not null, primary key (i, j));                              
CREATE TABLE

Time: 11ms total (execution 11ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> insert into t values (1, 1);                                                                     
INSERT 0 1

Time: 4ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> insert into t values (1, 2);                                                                     
INSERT 0 1

Time: 1ms total (execution 1ms / network 0ms)

-- here, since column 'i' is_unique, it is an acceptable column for our workload to choose here
demo@127.0.0.1:26257/demoapp/movr> alter table t alter primary key using columns (i);                                               
ERROR: failed to ingest index entries during backfill: duplicate key value violates unique constraint "t_pkey"
SQLSTATE: 23505
DETAIL: Key (i)=(1) already exists.
CONSTRAINT: t_pkey
```

Jira issue: CRDB-41919

### PR DESCRIPTION
**Pull request by annrpom**
### workload/schemachange: avoid hidden columns in random column selection
This patch ensures that we avoid hidden columns during random column
selection. Prior to this, we would only filter out `rowid`, but columns
like those created from adding a hash-sharded-index should also be
excluded.

Release note: None

---

### builtins: add crdb_internal.type_is_indexable builtin
This patch adds the `crdb_internal.type_is_indexable`
builtin -- which determines whether or not a given
type oid is indexable.

This builtin is used to choose "proper" columns for
a primary key schema change.

Release note: None

---

### workload/schemachange: fix is_unique check for alter pk op
This patch uses a different query for determining whether or not
a column has a unique constraint. In particular, we want to distinguish
between a column with a unique constraint (this patch) vs a column that
is a part of a composite key with a unique constraint.

Fixes: https://github.com/cockroachdb/cockroach/issues/130196
Release note: None

---

### workload/schemachange: enable alterPK
This patch enables `ALTER TABLE ... ALTER PRIMARY KEY`
in the schemachange workload.

Fixes: #128656
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
The changes look good to me. I just have one question regarding mixed-version testing.

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-:-O6Mnp_4-ae-pBuK6K3S:be5frmm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, and @renatolabs)

___
*[`pkg/sql/sem/builtins/builtins.go` line 8867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6MiEDF7WDOscfPY13a:-O6MiEDF7WDOscfPY13b:b-1jebph) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3c02e1d299d1eebea4f0047012a76980d6290c/pkg/sql/sem/builtins/builtins.go#L8867)):*
> ```Go
> 				return tree.MakeDBool(tree.DBool(colinfo.ColumnTypeIsIndexable(typ))), nil
> 			},
> 			Info:       "Returns whether given type OID is indexable.",
> ```

nit: suggest different wording



_Suggestion:_
```Go
Info:       "Returns whether the given type OID is indexable.",
```
___
*[`pkg/workload/schemachange/operation_generator.go` line 2536 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6MkkwnBfGs-O4_Qo8f:-O6MkkwoCWinxerz9Jnz:bkcvzot) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe99fdc3b3105e3bf8c227f487ce8e87c28e95d/pkg/workload/schemachange/operation_generator.go#L2536)):*
> ```Go
> 	// Primary Keys are backed by a unique index, therefore we can only use
> 	// columns that are of an indexable type. This information is only available
> 	// via the colinfo package (not SQL) and is subject to change across
> ```

Are we no longer concerned about mixed-version tests? What happens if, in the future, we decide to index a column type that wasn’t previously supported? I suppose, if that happens we would have to reintroduce this indexable families check.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @spilchen)

___
*[`pkg/sql/sem/builtins/builtins.go` line 8867 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6MiEDF7WDOscfPY13a:-O6N0R2775qI7N5G6tct:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/df3c02e1d299d1eebea4f0047012a76980d6290c/pkg/sql/sem/builtins/builtins.go#L8867)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: suggest different wording
</blockquote></details>

done
___
*[`pkg/workload/schemachange/operation_generator.go` line 2536 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6MkkwnBfGs-O4_Qo8f:-O6N0z1s-htks7-GadQD:b-4ur27d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe99fdc3b3105e3bf8c227f487ce8e87c28e95d/pkg/workload/schemachange/operation_generator.go#L2536)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Are we no longer concerned about mixed-version tests? What happens if, in the future, we decide to index a column type that wasn’t previously supported? I suppose, if that happens we would have to reintroduce this indexable families check.
</blockquote></details>

I wonder if I'm misunderstanding the comment I deleted here:

I understood their logic to be: we will keep this small allow-list of indexableFamilies because to provide the same extensive list as colinfo would be difficult/error-prone since indexable types can change between versions

So this would run into problems since we rely on the `workload` binary to be the source of truth -- even if the `cockroach` binary is at a different version

Now, since we are calling a builtin that calls on `colinfo.ColumnTypeIsIndexable`, the `cockroach` binary will be the source of truth again

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, 5 of 5 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-:-O6NVt1E14HmfMLO63Lp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2536 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6MkkwnBfGs-O4_Qo8f:-O6NUTQ_9-1o2pcUAGbI:bloq9qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbe99fdc3b3105e3bf8c227f487ce8e87c28e95d/pkg/workload/schemachange/operation_generator.go#L2536)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

I wonder if I'm misunderstanding the comment I deleted here:

I understood their logic to be: we will keep this small allow-list of indexableFamilies because to provide the same extensive list as colinfo would be difficult/error-prone since indexable types can change between versions

So this would run into problems since we rely on the `workload` binary to be the source of truth -- even if the `cockroach` binary is at a different version

Now, since we are calling a builtin that calls on `colinfo.ColumnTypeIsIndexable`, the `cockroach` binary will be the source of truth again
</blockquote></details>

Ah, I see. Yeah, you might be right. Feel free to disregard this comment.

**Comment by annrpom** [comment]
Oh wait you are right to be concerned about mixed-version, though — crdb_internal.type_is_indexable won't exist in other versions :/

Wonder if we should version gate it and see if we can just add a potential error code -- hmm

**Review by spilchen — COMMENTED** [review]
Could we reintroduce the check for indexable families while keeping `crdb_internal.type_is_indexable`? Then, once all supported versions have the new builtin, we can remove the indexable families logic again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-:-O6Qji8103C48yre44L3:b-wx5zyl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Comment by annrpom** [comment]
> Could we reintroduce the check for indexable families while keeping crdb_internal.type_is_indexable? Then, once all supported versions have the new builtin, we can remove the indexable families logic again.

yes; so, I added the old check back in, version-gated any usages of `crdb_internal.type_is_indexable`, and then i plan on backporting just the first 4 commits of this PR

let me kick off a roachtest run

**Review by spilchen — CHANGES_REQUESTED** [review]
I might be misunderstanding something here, so I just have a couple of questions to help clarify.

> Reviewed 6 of 6 files at r9, 4 of 5 files at r10, 3 of 3 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-:-O6Vq6RD0MuydR_eLrJ-:b-dpx6v9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom, @herkolategan, and @renatolabs)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2555 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VnqwM19KYL0fnluZl:-O6VnqwM19KYL0fnluZm:bnpqyae) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2555)):*
> ```Go
> 	// bit of coverage for stability. It may be worth while to add index-ability
> 	// information to `SHOW COLUMNS` or an internal SQL function in the future.
> 	// TODO(sql-foundations): once #130271 is in the latest release, we can remove
> ```

Just to clarify, do we need to wait until 24.3 is the minimum supported server version before we can remove this? It seems like waiting for 130271 to be included in the latest release isn’t sufficient, since older versions (pre-24.3) could still be in use during mixed-version testing.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2704 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VpRMK96rkPYDCz7mG:-O6VpRMK96rkPYDCz7mH:be2rg25) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2704)):*
> ```Go
> 		// the set of columns we consider not indexable may not be accurate. We
> 		// will add a potential error message instead to account for this.
> 		expectedErr = pgcode.SuccessfulCompletion
> ```

I'm a bit confused here. Wouldn't this mean that during mixed-version testing, we expect success when attempting to index an unindexable column? If so, could we instead skip this generation case in mixed-version testing to avoid that scenario?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @spilchen)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2555 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VnqwM19KYL0fnluZl:-O6WSfcEBGwbIVjuXtNA:bhri5rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2555)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Just to clarify, do we need to wait until 24.3 is the minimum supported server version before we can remove this? It seems like waiting for 130271 to be included in the latest release isn’t sufficient, since older versions (pre-24.3) could still be in use during mixed-version testing.
</blockquote></details>

Ah this is a problem with my wording; I meant specifically once `130271` is in the latest release for all versions

So for now, we can use this builtin as long as the cockroach binary we are using is on master (but this is subject to change)
___
*[`pkg/workload/schemachange/operation_generator.go` line 2704 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VpRMK96rkPYDCz7mG:-O6WUE_S2SnVvKr2mdjm:bkekfbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2704)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I'm a bit confused here. Wouldn't this mean that during mixed-version testing, we expect success when attempting to index an unindexable column? If so, could we instead skip this generation case in mixed-version testing to avoid that scenario?
</blockquote></details>

The solution with adding an expected success error & a potential exec error (later on after we get our opStmt) is the outcome of how a `GenerationCase` is structured; the issue that it was trying to solve is that for this generation case, we may or may not pick an unindexable column since the set of unindexable columns is just the set of columns not included in our small set if indexable columns

We also can change how `GenerationCase` is structured, but I like the idea of skipping this generation case in the versions we backport this to for now

**Review by spilchen — APPROVED** [review]
:lgtm: Thanks for the explanations.

> Reviewed 2 of 2 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-:-O6WdGpxCqs-l_F5zofz:bujxrs6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2555 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VnqwM19KYL0fnluZl:-O6Wb3Zl1V-vOV690R8Q:b-ncd0ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2555)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

Ah this is a problem with my wording; I meant specifically once `130271` is in the latest release for all versions

So for now, we can use this builtin as long as the cockroach binary we are using is on master (but this is subject to change)
</blockquote></details>

Okay, got it. We were on the same page.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2704 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/130271#-O6VpRMK96rkPYDCz7mG:-O6WdA87-HO_CIzUxj5s:b1o90mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bffa0837e16f40988c327843cfe00fb7422d9e86/pkg/workload/schemachange/operation_generator.go#L2704)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

The solution with adding an expected success error & a potential exec error (later on after we get our opStmt) is the outcome of how a `GenerationCase` is structured; the issue that it was trying to solve is that for this generation case, we may or may not pick an unindexable column since the set of unindexable columns is just the set of columns not included in our small set if indexable columns

We also can change how `GenerationCase` is structured, but I like the idea of skipping this generation case in the versions we backport this to for now
</blockquote></details>

Okay, makes sense now. I agree skipping on older versions makes sense.

**Comment by annrpom** [comment]
squashed the last two commits

TFTR! ('-')7

bors r=spilchen

**Pull request merged**
