### PR TITLE
serverutils: nil check system config cache

### PR DESCRIPTION
**Pull request by ajwerner**
See [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6797223?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
Thanks for fixing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89419#-:-NDdGMpjB5BI-bXXrD8Z:b-whxd1j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @msirek)

___
*[`pkg/testutils/serverutils/test_cluster_shim.go` line 267 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89419#-NDdGQmD9Hozvm7hAE27:-NDdGQmE1FypN_CLHuxK:b-nze064) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5e4b266ce7bc3132602ad24101a3967b25d71cd/pkg/testutils/serverutils/test_cluster_shim.go#L267)):*
> ```Go
> 		sysconfigProvider := cluster.Server(i).SystemConfigProvider()
> 		if sysconfig := sysconfigProvider.GetSystemConfig(); sysconfig != nil {
> 			sysconfig.PurgeZoneConfigCache()
> ```

If `sysconfig` could be nil, would you mind also fixing this location? :

https://github.com/cockroachdb/cockroach/blob/e0e59112d60b9657600fc9c4641763536282018f/pkg/sql/logictest/logic.go#L2263-L2269

**Comment by ajwerner** [comment]
Looking more closely, I don't think I understand https://github.com/cockroachdb/cockroach/pull/87391. It clears a cache but the cache's source data should be immutable. Every time the system config values change, we construct a new `SystemConfig` object.

**Review by msirek — COMMENTED** [review]
I am not sure about the details of how the zone config gets propagated, but I've seen the `SystemConfig` get created and be available, but at the time `getZoneEntry` is called for a database (as the referenced parent of a table), the zone config is not available yet, so calling the`zoneConfigHook` causes a nil `ZoneConfig` to be returned:
https://github.com/cockroachdb/cockroach/blob/4c43c2b8c7be2858daf53e90e0a5d99b3090bcaa/pkg/sql/zone_config.go#L197-L199
We cache the nil `ZoneConfig`, so even if the config becomes available later, we won't load it because the nil is cached.  Clearing out the cache causes future calls to`getZoneEntry` to look it up again and find it.  I saw this comment in tests, not sure if it's related:
https://github.com/cockroachdb/cockroach/blob/d5f3be189b8cebf83b3f6b16b8508f95dffab4ed/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L4-L10
Is it problematic for zone configs to not be immediately available if a table which depends on one is used?  I don't know if there's a bigger issue here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89419#-:-NDeBCLX3PzPv3Pos8x0:bp69iar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @msirek)

**Comment by ajwerner** [comment]
The part I don't get is that when the changes propagate, the object is replaced wholesale -- cache included. Do you know of a test which fails without the cache clearing change?

**Comment by msirek** [comment]
> Do you know of a test which fails without the cache clearing change?

Yes, `regional_by_row_query_behavior` fails under `--stress` unless the cache is cleared.  #87391

**Comment by msirek** [comment]
Fixing this through #90802, including the `PurgeZoneConfigCache` call in pkg/sql/logictest/logic.go.

**Pull request closed without merging**
