### PR TITLE
sql: remove connect privilege warning

### LINKED ISSUE #61560: sql: warning in demo on `use system` - CONNECT privilege
One way or another, I don't think demo should be telling me this (or pehaps the real question is what's gonna happen when I do this in "future release") ?

```
demo@127.0.0.1:26257/movr> use system;
NOTICE: CONNECT privilege will be required to connect to databases in a future release
HINT: See: https://go.crdb.dev/issue-v/59875/v21.1
SET
```

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: remove connect privilege warning

Release justification: No functionality, removing warning
Release note: None

Resolves #61560

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! thoughts on giving the `admin` role the connect privilege?

**Comment by RichardJCai** [comment]
> lgtm! thoughts on giving the `admin` role the connect privilege?

`admin` role should have connect privilege already as it's has ALL when a new db is created.

However it does not for the system db though as admin is only given GRANT/SELECT on it. We should give it CONNECT though, I'll open a separate PR for it. 

I think we also need a migration to give CONNECT to admin for system dbs created before 21.1. Thoughts?

**Comment by RichardJCai** [comment]
Thanks for the review!
bors r=rafiss

**Comment by RichardJCai** [comment]
Wait oops, I'll wait for CI to pass first
bors r-

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by RichardJCai** [comment]
bors r=rafiss

**Comment by rafiss** [comment]
> I think we also need a migration to give CONNECT to admin for system dbs created before 21.1. Thoughts?

Hmm yes I suppose we should. I guess if it's annoying to do we can always push it off until we decide to enforce CONNECT privilege rules. lol or maybe we should just hardcode every role/user to have CONNECT privilege and make it impossible to revoke....

**Comment by RichardJCai** [comment]
> > I think we also need a migration to give CONNECT to admin for system dbs created before 21.1. Thoughts?
> 
> Hmm yes I suppose we should. I guess if it's annoying to do we can always push it off until we decide to enforce CONNECT privilege rules. lol or maybe we should just hardcode every role/user to have CONNECT privilege and make it impossible to revoke....

I don't think it would be annoying to do the migration, I wouldn't say it's urgent or necessary as of now as CONNECT only allows users to see metadata and admin can already see metadata on the system database anyway.

**Pull request merged**
