### PR TITLE
opt: fix various TODOs

### PR DESCRIPTION
**Pull request by RaduBerinde**
Removing TODOs that are no longer accurate. Reenabling tests that can
be enabled. Updating some TODOs.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28781#-:-LK9bUVz2IDmSemTz9zD:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28781#-:-LKDOLiJ8WjC0jbuRNZS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28781#-LKDNSHbBhNnMMHKvLRV:-LKDNSHbBhNnMMHKvLRW:bhx1dtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc958eb63d30bd96a14966d87d829cba1600e7d/pkg/sql/opt/exec/execbuilder/testdata/orderby#L766)):*
> ```
> # The underlying index can be forced manually, of course.
> query TTTTT
> EXPLAIN (VERBOSE) SELECT k FROM kv@foo a NATURAL JOIN kv@foo ORDER BY INDEX kv@foo
> ```

do you know why we're not using a merge join here?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28781)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 766 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28781#-LKDNSHbBhNnMMHKvLRV:-LKEDoA6CUlIVivtfHWU:b-7ualbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfc958eb63d30bd96a14966d87d829cba1600e7d/pkg/sql/opt/exec/execbuilder/testdata/orderby#L766)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

do you know why we're not using a merge join here?
</blockquote></details>

Good catch, you found a bug. I'll send out a separate PR.

**Pull request merged**
