### PR TITLE
opt: change JoinMultiplicity from a Relational prop to a join field

### LINKED ISSUE #49821: opt: JoinMultiplicity shouldn't be a Relational prop
JoinMultiplicity shouldn't be a Relational prop. Relational properties are shared by all expressions in a memo group, and there are exploration rules that can switch join inputs. This leads can lead to a join with an incorrect JoinMultiplicity field.

I don't think this can be reproduced on master, since it was only exposed by a rule I'm working on adding (limit pushdown into inner joins). But it's still a problem that could manifest later if we don't fix. This is the query:
```
CREATE TABLE trade_type (tt_id INT PRIMARY KEY);
CREATE TABLE exchange (ex_id INT PRIMARY KEY);
CREATE TABLE status_type (st_id INT PRIMARY KEY);
CREATE TABLE security (
    s_symb  INT PRIMARY KEY,
    s_st_id INT NOT NULL,
    s_ex_id INT NOT NULL,
    FOREIGN KEY (s_st_id) REFERENCES status_type (st_id),
    FOREIGN KEY (s_ex_id) REFERENCES exchange (ex_id)
);
CREATE TABLE trade (
    t_st_id  INT NOT NULL,
    t_tt_id  INT NOT NULL,
    t_s_symb INT NOT NULL,
    FOREIGN KEY (t_st_id) REFERENCES status_type (st_id),
    FOREIGN KEY (t_tt_id) REFERENCES trade_type (tt_id),
    FOREIGN KEY (t_s_symb) REFERENCES security (s_symb)
);
SELECT *
FROM trade, status_type, trade_type, security, exchange
WHERE st_id = t_st_id
  AND tt_id = t_tt_id
  AND s_symb = t_s_symb
  AND ex_id = s_ex_id
LIMIT 50;
```
Expected:
```
├── inner-join (cross)
     ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
     ├── inner-join (cross)
     ├── scan status_type
     └── filters (true)
```
Found:
```
├── inner-join (cross)
     ├── multiplicity: left-rows(zero-or-more), right-rows(one-or-more)
     ├── inner-join (cross)
     ├── scan status_type
     └── filters (true)
```
We can fix this by making JoinMultiplicity a property of the join operator itself, rather than one of its Relational props.

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the JoinMultiplicity property was stored as a Relational
prop. This is a problem because all expressions in a memo group share
the same Relational props during exploration, and there are exploration
rules that can flip a join's left/right multiplicity.

This patch instead stores JoinMultiplcity as a join field that is
initialized during construction of the join. This fixes the shared
Relational props issue, and also  makes it possible for JoinMultiplicity
to aid in calculating other logical properties.

Fixes #49821

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
I ended up just leaving the multiplicity output code (in expr_format) with the RuleProps, but I'm open to alternative suggestions. One possibility is to give JoinMultiplicity its own expr format flag.

**Review by rytaft — COMMENTED** [review]
Nice! I think you should print out the `UnfilteredCols` property along with the other `RuleProps`. Otherwise just a couple of comments need updating.

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-:-M8wtlo68oG4iyifaLAO:b6tl6kk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8whmUc7oGujLXXrOmI:-M8whmUc7oGujLXXrOmJ:b-w6m4p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/multiplicity_builder.go#L83)):*
> ```Go
> }
> 
> // GetJoinMultiplicity recursively derives the UnfilteredCols field and
> ```

GetJoinMultiplicity -> deriveUnfilteredCols
___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wqkLeCM4S6XHRIwMC:-M8wqkLeCM4S6XHRIwMD:bow6xhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/multiplicity_builder.go#L84)):*
> ```Go
> 
> // GetJoinMultiplicity recursively derives the UnfilteredCols field and
> // populates the props.Relational.Rule.MultiplicityProps field as it goes to
> ```

this comment is out of date
___
*[pkg/sql/opt/memo/testdata/logprops/join, line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wrru0AobeO_H5Ctl1:-M8wrru0AobeO_H5Ctl2:b-13kzk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/testdata/logprops/join#L2201)):*
> ```
> 
> # Regression test for #49821.
> opt format=show-ruleprops
> ```

Since you're showing rule props you should print the unfiltered cols.
___
*[pkg/sql/opt/props/logical.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wsenH4eCA_n-sOMIw:-M8wsenI9Eb6jGRjWeoA:b1prqa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/props/logical.go#L343)):*
> ```Go
> 		// cannot add any columns, as it may have filtered rows.
> 		//
> 		// UnfilteredCols is lazily populated by DeriveJoinMultiplicity. It is only
> ```

DeriveJoinMultiplicity -> GetJoinMultiplicityFromInputs

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49822)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8whmUc7oGujLXXrOmI:-M8x9Emt0bCRbsfIVdHO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/multiplicity_builder.go#L83)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

GetJoinMultiplicity -> deriveUnfilteredCols
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wqkLeCM4S6XHRIwMC:-M8x9GNY91wsiS4sM5xX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/multiplicity_builder.go#L84)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this comment is out of date
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/logprops/join, line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wrru0AobeO_H5Ctl1:-M8xBSzQ1EUlN_Zb8VMX:b3g5pgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/memo/testdata/logprops/join#L2201)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since you're showing rule props you should print the unfiltered cols.
</blockquote></details>

I was worried that this might lead to long output strings, but it actually turned out to be really compact. Done.
___
*[pkg/sql/opt/props/logical.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8wsenH4eCA_n-sOMIw:-M8x8qC73B0arw3Atkfn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad5c6d09f41bd4e421ba2f9315990826ace22ce5/pkg/sql/opt/props/logical.go#L343)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

DeriveJoinMultiplicity -> GetJoinMultiplicityFromInputs
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-:-M8zCH6_-pCHlIY_IXaf:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice!

One thing is that we should only need to derive unfiltered cols in those special cases where we have a self-join or a foreign key join. I realize that would make the logic even more complicated.. But we could at least exit early in some simple cases (no self-joins, and no foreign keys in the tables involved).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-:-M8zjkA14UZ-ti3l_MD-:b-5ko5av)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/memo/expr.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zhp-33aFPV0soxiKO:-M8zhp-33aFPV0soxiKP:b-jo2eu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr.go#L452)):*
> ```Go
> // supported (currently InnerJoin, LeftJoin, and FullJoin) to be treated
> // polymorphically.
> type multiplicityJoin interface {
> ```

Having both multiplicityJoin and JoinMultiplicity is a bit confusing. Maybe change this to `joinWithMultiplicity`
___
*[pkg/sql/opt/memo/expr.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zi91K9jaijyfgigSK:-M8zi91K9jaijyfgigSL:b-1lty3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr.go#L456)):*
> ```Go
> 	getMultiplicity() props.JoinMultiplicity
> }
> ```

[nit] add some type assertions here to make it clear what types implement it (`var _ multiplicityJoin = &InnerJoinExpr{}`)
___
*[pkg/sql/opt/memo/expr_format.go, line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8ziYV9E_GUX94-tqYy:-M8ziYV9E_GUX94-tqYz:b-xz5es1) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr_format.go#L696)):*
> ```Go
> 			tp.Childf("unfiltered-cols: %s", r.UnfilteredCols.String())
> 		}
> 		if join, ok := e.(multiplicityJoin); ok {
> ```

We have `ExprFmtHideMiscProps`, maybe move this in that block
___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zl_y47OAUwKkdwG79:-M8zl_y47OAUwKkdwG7A:b-fv5mzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/multiplicity_builder.go#L33)):*
> ```Go
> 		right := t.Child(1).(RelExpr)
> 		filters := *t.Child(2).(*FiltersExpr)
> 		multiplicity := GetJoinMultiplicityFromInputs(t.Op(), left, right, filters)
> ```

[nit] DeriveJoinMultiplicityFromInputs would be a better name for this one

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49822)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zhp-33aFPV0soxiKO:-M8zrQET3VRa__wcgqEY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr.go#L452)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Having both multiplicityJoin and JoinMultiplicity is a bit confusing. Maybe change this to `joinWithMultiplicity`
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/expr.go, line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zi91K9jaijyfgigSK:-M8zrboqA65iwAzFlmAZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr.go#L456)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add some type assertions here to make it clear what types implement it (`var _ multiplicityJoin = &InnerJoinExpr{}`)
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/expr_format.go, line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8ziYV9E_GUX94-tqYy:-M8zrfdO5lufpnybrN_u:b9a5wnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr_format.go#L696)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We have `ExprFmtHideMiscProps`, maybe move this in that block
</blockquote></details>

Done. This causes JoinMultiplicity to be outputted more often though, is that ok?
___
*[pkg/sql/opt/memo/multiplicity_builder.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8zl_y47OAUwKkdwG79:-M8zsd2pCEl2PVqqr_fR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/multiplicity_builder.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] DeriveJoinMultiplicityFromInputs would be a better name for this one
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/expr_format.go, line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49822#-M8ziYV9E_GUX94-tqYy:-M9-1EtM7wGfWGr-cuFC:b-6o2qdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b901593feaeb32f8e61b922b8c907af80f54e3/pkg/sql/opt/memo/expr_format.go#L696)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Done. This causes JoinMultiplicity to be outputted more often though, is that ok?
</blockquote></details>

It doesn't seem less important than the other "misc props", I'd say yes

**Pull request merged**
