### PR TITLE
sql: introduce spanBasedDependencyAnalyzer for parallel statement execution

### PR DESCRIPTION
**Pull request by nvb**
Dependency analysis portion of #13160.

This change introduces a new `DependencyAnalyzer` implementation called
`spanBasedDependencyAnalyzer`. This analyzer determines `planNode`
dependence by comparing the spans that each `planNode` touches, and
applying the rule that independent plans do not have their write spans
overlapping with any of the other's spans. This is facilitated through
the inclusion of a new method on the `planNode` interface called
`Spans`. This method collects all of the `roachpb.Spans` that a
`planNode` expects to touch during execution. Additionally, the new
`DependencyAnalyzer` implementation is aware of monotonically-constrained
functions like `statement_timestamp`, which prevent statement reordering.

The last commit is experimental, and I'm not sure how people are going to feel about
it. I included it here because I had a feeling the idea would be brought up in the initial
review, but I'll move it to its own PR for a closer look if it's well received. The idea
is to constrain `client.Batches` to the limited set of spans predicted by a `planNode`.
It does so by introducing a `SpanConstraints` field on a `client.Batch`, which asserts
that all read and write operations take place within specified ranges. The ability to
constrain batch operations is then used by the `spanBasedDependencyAnalyzer` to
assert that the `roachpb.Spans` reported by `planNode.Spans` is accurate. This sanity
check assures that no plans have unaccounted for span accesses.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14553)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 51 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/index_join.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgplowA7U7F2Rd7uzsP:-KgplowA7U7F2Rd7uzsQ:bl56urf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/index_join.go#L244)):*
> ```Go
> func (n *indexJoinNode) Spans(ctx context.Context) (_, _ roachpb.Spans) {
> 	indexRead, indexWrite := n.index.Spans(ctx)
> 	tableRead, tableWrite := n.table.Spans(ctx)
> ```

`n.table.Spans` is not useful here.. It is populated dynamically with each batch of rows from the index when we actually run the node. I think it is empty in the beginning.

We probably want the entire table span here because we don't know ahead of time exactly what spans we will read?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553)*

**Comment by RaduBerinde** [comment]
I think the proposal to constrain batches is a very good idea. A bug in collecting the spans could otherwise cause hard to debug problems. If the extra constraints are a performance problem, we can disable them outside of tests.

---

Review status: 0 of 51 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-:-KgptKA00-9OFTcQk6ew:b14c9q4)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 52 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/index_join.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgplowA7U7F2Rd7uzsP:-Kh3zzHdhcIwfo7ybGHw:b-w2fhac) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/index_join.go#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`n.table.Spans` is not useful here.. It is populated dynamically with each batch of rows from the index when we actually run the node. I think it is empty in the beginning.

We probably want the entire table span here because we don't know ahead of time exactly what spans we will read?
</blockquote></details>

Very good point. I created a new `AllIndexSpans` method on `TableDescriptor`, which we now use for `indexJoinNode` as well as from the `tableWriter` interfaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553)*

**Comment by nvanbenschoten** [comment]
Adding @danhhz because of his familiarity with `tableWriter` and @eisenstatdavid to make sure none of this conflicts with interleaved tables.

**Comment by danhhz** [comment]
tableWriter stuff lgtm. some meta comments:

- there are an awful lot of panics here. seems like spans wants to return an error
- I think it should be a requirement that we check these things to make sure they don't rot (something like your proposal). However, I think the approach in r6 is also prone to rot. Consider storing something other than a *client.Txn on planner which errors if `Constrain` is not called first

---

Review status: 0 of 52 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/index_join.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgplowA7U7F2Rd7uzsP:-KhNhtLiuV74hkOiyRuG:b-dbredx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/index_join.go#L244)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Very good point. I created a new `AllIndexSpans` method on `TableDescriptor`, which we now use for `indexJoinNode` as well as from the `tableWriter` interfaces.
</blockquote></details>

IIUC, you only need the span for the primary index and whatever index is being scanned. This looks like it's including every secondary index

---

*[pkg/sql/pipelining_test.go, line 352 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhNitxymYs3Xl91ePmF:-KhNitxymYs3Xl91ePmG:b-w5dmxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bff96959a9bd8a34f1047b58e5145fe669a142/pkg/sql/pipelining_test.go#L352)):*
> ```Go
> 	}
> 	if _, err := db.Exec(`CREATE TABLE bar (
> 						      k INT PRIMARY KEY, 
> ```

nit: indentation here is weird. reviewable is also showing me a red dot at the end of the line but I don't know what the means (windows style newline?)

---

*[pkg/sql/tablewriter.go, line 71 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhNmcOkJetJNRshpe99:-KhNmcOkJetJNRshpe9A:b2cguab) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bff96959a9bd8a34f1047b58e5145fe669a142/pkg/sql/tablewriter.go#L71)):*
> ```Go
> 
> 	// spans collects the upper bound set of read and write spans that the
> 	// tableWriter expects to touch when executed.
> ```

nit: "expects to touch" sounds like best-effort but this is actually contractual. maybe tighten up the language a bit here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-:-KhNnVaVRr_wyt1z_rzH:b-cuhz6d)*

**Comment by eisenstatdavid** [comment]
Looks like you're only using higher level key construction functions, so :lgtm: wrt interleaved.

---

Reviewed 38 of 38 files at r3, 39 of 39 files at r4, 2 of 2 files at r5, 24 of 24 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-:-KhNx8-F9zK1RHIZSDUc:bazz2br)*

**Comment by nvanbenschoten** [comment]
Thanks for the reviews!

@danhhz I addressed your first comment by adding an error return value to `Spans`. As promised, I'm pulling the SpanConstraint commit out of here because I think it deserves a closer inspection on its own. We can discuss more in that PR, but it sounds like rot is a serious concern. My plan was only to constrain batches when `plan.Spans` had been called, which at the moment would only be for RETURNING NOTHING (parallelized) statements. Do you think this is too conservative?

---

Review status: 0 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/index_join.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgplowA7U7F2Rd7uzsP:-KhRPqvh9BjWm2l7itYt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/index_join.go#L244)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

IIUC, you only need the span for the primary index and whatever index is being scanned. This looks like it's including every secondary index
</blockquote></details>

Done.

---

*[pkg/sql/pipelining_test.go, line 352 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhNitxymYs3Xl91ePmF:-KhRRYGvf2DXGOBxSwHu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bff96959a9bd8a34f1047b58e5145fe669a142/pkg/sql/pipelining_test.go#L352)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: indentation here is weird. reviewable is also showing me a red dot at the end of the line but I don't know what the means (windows style newline?)
</blockquote></details>

Done.

---

*[pkg/sql/tablewriter.go, line 71 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhNmcOkJetJNRshpe99:-KhRRus5Fd7MFlE-0axO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bff96959a9bd8a34f1047b58e5145fe669a142/pkg/sql/tablewriter.go#L71)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: "expects to touch" sounds like best-effort but this is actually contractual. maybe tighten up the language a bit here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-:-KhRU0OFXTvJOe2nxAUy:b-hpmot8)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 39 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/index_join.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgplowA7U7F2Rd7uzsP:-KhS7DfMsehRI-tmF-dN:b32vy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/index_join.go#L244)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LG

---

*[pkg/sql/index_join.go, line 244 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhS6wE8I6t87qGABTax:-KhS6wE8I6t87qGABTay:bojwamc) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a21594000b29ca5158208e2041ea06477a54b9/pkg/sql/index_join.go#L244)):*
> ```Go
> 
> func (n *indexJoinNode) Spans(ctx context.Context) (reads, writes roachpb.Spans, err error) {
> 	// We can not be sure which spans in the table we will read based only on the
> ```

[nit] This comment belongs below, before `PrimaryIndexSpan()`.

---

*[pkg/sql/join.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgpwVlcrQ-RXI20vR5U:-KgpwVlcrQ-RXI20vR5V:b4voyln) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/join.go#L301)):*
> ```Go
> func (n *joinNode) Spans(ctx context.Context) (reads, writes roachpb.Spans) {
> 	leftReads, leftWrites := n.left.plan.Spans(ctx)
> 	rightReads, rightWrites := n.right.plan.Spans(ctx)
> ```

The left and right spans may overlap if we are joining a table with itself. Is the overlap a problem?

---

*[pkg/sql/tablewriter.go, line 807 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhS7ulSTnwAY2bjosf4:-KhS7ulSTnwAY2bjosf5:bpkcsp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a21594000b29ca5158208e2041ea06477a54b9/pkg/sql/tablewriter.go#L807)):*
> ```Go
> 	desc *sqlbase.TableDescriptor, fks sqlbase.FkSpanCollector,
> ) (reads, writes roachpb.Spans, err error) {
> 	tableSpans := desc.AllIndexSpans()
> ```

Maybe a comment explaining that we don't in general know which spans we will be modifying so we are being conservative and assuming anything in the table might change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 39 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/index_join.go, line 244 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhS6wE8I6t87qGABTax:-KhSflkDqiIyYTJHY0V2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a21594000b29ca5158208e2041ea06477a54b9/pkg/sql/index_join.go#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This comment belongs below, before `PrimaryIndexSpan()`.
</blockquote></details>

Done.

---

*[pkg/sql/join.go, line 301 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KgpwVlcrQ-RXI20vR5U:-KhSfoa7O6mDYnSndkRT:b-ozxeb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1815d681480ce5fddbd498ff11aa6e27d17cc70/pkg/sql/join.go#L301)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The left and right spans may overlap if we are joining a table with itself. Is the overlap a problem?
</blockquote></details>

Not a problem, these `Spans` are all merged by consumers of Spans anyway and the method makes no guarantees about overlaps within sets or between sets. Clarified that comment.

---

*[pkg/sql/tablewriter.go, line 807 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553#-KhS7ulSTnwAY2bjosf4:-KhSkLsSb8BLKvLoXTs4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a21594000b29ca5158208e2041ea06477a54b9/pkg/sql/tablewriter.go#L807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe a comment explaining that we don't in general know which spans we will be modifying so we are being conservative and assuming anything in the table might change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14553)*

**Pull request merged**
