### PR TITLE
store (external) intents in committed txn records

### PR DESCRIPTION
**Pull request by tbg**
prep work for #2062.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3118)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1, 16 of 16 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

<sup>**[kv/txn_coord_sender.go, line 140 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xO4GJ-RZDIIzBFewz)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/kv/txn_coord_sender.go#L140)):</sup>
Rename this method?


---

<sup>**[roachpb/api.proto, line 214 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xO86gqkW5Q1x2r-NE)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/roachpb/api.proto#L214)):</sup>
rename this field?


---

<sup>**[roachpb/batch.go, line 101 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xOBJvsIlOZAPnkG3o)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/roachpb/batch.go#L101)):</sup>
rename


---

<sup>**[roachpb/data.proto, line 276 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xPPq4-NrAwugpIBFK)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/roachpb/data.proto#L276)):</sup>
How come embed?


---

<sup>**[roachpb/data.proto, line 272 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xQ4CiPCwddMW9zHdf)** ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8927e7874b7aa0f468b01956b5b904cb6d29a3/roachpb/data.proto#L272)):</sup>
Why this naming?


---

<sup>**[storage/gc_queue.go, line 156 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xOTuxMtyhOKC6w-48)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/storage/gc_queue.go#L156)):</sup>
intentSpanMap?


---

<sup>**[storage/replica_command.go, line 331 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xOlTqri3ZLTZ4DlWx)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/storage/replica_command.go#L331)):</sup>
intentSpans?


---

<sup>**[storage/replica_command.go, line 334 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xOrf0tDwM1VLHwZmV)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/storage/replica_command.go#L334)):</sup>
i think i would prefer:
```
ret := make([]roachpb.Intent, 0, len(intentSpans)
for _, intentSpan := range intents {
  ret = append(ret, roachpb.Intent{...}
}
```


---

<sup>**[storage/replica_command.go, line 437 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xPGnU7Xvy0zBwEe5Q)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/storage/replica_command.go#L437)):</sup>
a few renames here would help things, I think.


---

<sup>**[storage/replica_command.go, line 465 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xQGV0PkqKOi1OYT0t)** ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8927e7874b7aa0f468b01956b5b904cb6d29a3/storage/replica_command.go#L465)):</sup>
i think you can safely use the append style here


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118)

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1, 16 of 16 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118)

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
Review status: 8 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[roachpb/data.proto, line 276 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xPPq4-NrAwugpIBFK)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/roachpb/data.proto#L276)):</sup>
it's convenient and used a bunch in `replica.go`.


---

<sup>**[storage/replica_command.go, line 334 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xOrf0tDwM1VLHwZmV)** ([raw file](https://github.com/cockroachdb/cockroach/blob/93f24cf3d662ed1faa0f9603835bcde70404d2b2/storage/replica_command.go#L334)):</sup>
I avoid `append` when I can have a pre-initialized slice of non-pointer values.


---

<sup>**[storage/replica_command.go, line 465 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118#-K2xQGV0PkqKOi1OYT0t)** ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8927e7874b7aa0f468b01956b5b904cb6d29a3/storage/replica_command.go#L465)):</sup>
I avoid `append` when the length is known and the slice is of non-pointer type.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118)

**Comment by tamird** [comment]
Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3118)

**Pull request merged**
