### PR TITLE
sql: some performance optimizations in the makePlan path

### PR DESCRIPTION
**Pull request by jordanlewis**
Two optimizations along the `makePlan` codepath. I observed a ~5% improvement  vs master to read-only query throughput against a single-node local cluster via `kv --read-percent 100`, from 13798 to 14623 ops/s.

- avoid planner allocation in executor
A planner is quite expensive, weighing in at 6200 bytes. Allocating one
per query is wasteful during serial execution, since planners are
session-scoped and sessions do not execute more than one query at once
unless the query is parallelizeable and running within a transaction.

- don't copy overloadImpls around
Previously, `typeCheckOverloadedExprs` modified its input slice of
`overloadImpls`, requiring that callers make a copy. This copy was very
expensive, representing a large proportion of the typechecking time for
a simple equality comparison.
Now, the input slice is not modified, and callers don't have to make a
copy.

Updates #14927.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: though someone more familiar with the type-checking code should review the second commit.

---

Reviewed 2 of 2 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-KkYa3d5VnwCVsnOzl54:b-ofvf00) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
> ```Go
> 		// We're not executing in parallel. We can use the cached planner on the
> 		// session.
> 		planner = &session.planner
> ```

I wonder if we need to do something like `session.planner = planner{}` after executing the statement. Unfortunately, with `planner` weighing in at 6200 bytes, doing so will be expensive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-:-KkYauIXEL2fVBVvFz4D:bugs99c)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-Kk_AquDhfcvD1Ig11EY:b-c7i4wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we need to do something like `session.planner = planner{}` after executing the statement. Unfortunately, with `planner` weighing in at 6200 bytes, doing so will be expensive.
</blockquote></details>

That's what the `reset` method is for. I am not too concerned.

---

*[pkg/sql/parser/function_definition.go, line 42 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_BM8rkFA6quduCr9j:-Kk_BM8snVGgqlop88m4:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/function_definition.go#L42)):*
> ```Go
> 	overloads := make([]overloadImpl, len(def))
> 	for i, d := range def {
> 		overloads[i] = d
> ```

:100: 

---

*[pkg/sql/parser/overload.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_CcnVAUnbxpGi7mQu:-Kk_CcnVAUnbxpGi7mQv:b9z379e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/overload.go#L327)):*
> ```Go
> 				i++
> 			} else {
> 				overloadIdxs[i], overloadIdxs[len(overloadIdxs)-1] = overloadIdxs[len(overloadIdxs)-1], overloadIdxs[i]
> ```

The only thing this function does is remove zero or more overloads from the candidate list. Blatantly the order does not matter.
Depending on how much we want to get rid of the allocation above altogether (if I am not mistaken, you've replaced the allocation of an `[]overloadImpl` on every type check by another allocation of `[]int`, I'm not sure you're winning anything by doing that), there's another method: use a bitmap in a single uint64. (With the suitable assert that there's never more than˙64 overloads for a function)

To keep things fast and smooth you'd need the bitmap `overloads uint64`.
Remove an overload with `overloads &^= (1 << i)`
Iterate with `for i, b := 0, overloads; b != 0; b >>= 1 { if b & 1 == 0 { continue }; ... }`
You can encapsulate in a small struct for clarity.
You may need another var `nrOverloads` counting the number of bits sets and perhaps`firstOverloadIdx` as well to keep "access the first overload" (= counting consecutive trailing zero bits) fast and smooth too, but perhaps a for loop to search for it will be ok too. Or use https://graphics.stanford.edu/~seander/bithacks.html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-KkaGK-nXxf_a_LyT1iG:b3qai3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's what the `reset` method is for. I am not too concerned.
</blockquote></details>

My (small) concern is that we're doing the reset at the start of processing a query. After finishing processing a query we're holding onto the planner and any memory dangling off it until the next query is received. For a small query this isn't a problem. Could it be a problem for a large query? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by knz** [comment]
> After finishing processing a query we're holding onto the planner and any memory dangling off it until the next query is received. For a small query this isn't a problem.

reset as far as I can see does not release memory -- it merely reinitializes some fields. I think that holding onto the data structures across queries is actually a feature that will reduce GC pressure here. Don't you think so?

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_CcnVAUnbxpGi7mQu:-KkaOaFqYBqvVF773RVJ:b-9lj079) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/overload.go#L327)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The only thing this function does is remove zero or more overloads from the candidate list. Blatantly the order does not matter.
Depending on how much we want to get rid of the allocation above altogether (if I am not mistaken, you've replaced the allocation of an `[]overloadImpl` on every type check by another allocation of `[]int`, I'm not sure you're winning anything by doing that), there's another method: use a bitmap in a single uint64. (With the suitable assert that there's never more than˙64 overloads for a function)

To keep things fast and smooth you'd need the bitmap `overloads uint64`.
Remove an overload with `overloads &^= (1 << i)`
Iterate with `for i, b := 0, overloads; b != 0; b >>= 1 { if b & 1 == 0 { continue }; ... }`
You can encapsulate in a small struct for clarity.
You may need another var `nrOverloads` counting the number of bits sets and perhaps`firstOverloadIdx` as well to keep "access the first overload" (= counting consecutive trailing zero bits) fast and smooth too, but perhaps a for loop to search for it will be ok too. Or use https://graphics.stanford.edu/~seander/bithacks.html.

</blockquote></details>

You are correct that I've replaced the `[]overloadImpl` allocation and copy with an `[]int` allocation. I am also surprised that this makes a difference, but it really does - this path alone reduced the slice of the `makePlan` pie taken up by `TypeCheck` from 22% to 14%.

Nice idea about the bitmap! I'll check to see if it improves performance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by petermattis** [comment]
> reset as far as I can see does not release memory -- it merely reinitializes some fields. I think that holding onto the data structures across queries is actually a feature that will reduce GC pressure here. Don't you think so?

Yes, reducing GC pressure is good for performance, but we also need to pay attention to possible memory leaks. This wouldn't be a traditional leak, but similar to some of the ones in core-land where we're accidentally holding on to excessive memory. My concern is only theoretical as I'm not terribly familiar with this code anymore. I'll leave it in your hands to judge if it is worth worrying about.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-:-KkcOLcAe62GZ2nzq6o6:bu2440c)*

**Comment by jordanlewis** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_CcnVAUnbxpGi7mQu:-KkvbPP72cV-M5vey__4:b-8uzhrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/overload.go#L327)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You are correct that I've replaced the `[]overloadImpl` allocation and copy with an `[]int` allocation. I am also surprised that this makes a difference, but it really does - this path alone reduced the slice of the `makePlan` pie taken up by `TypeCheck` from 22% to 14%.

Nice idea about the bitmap! I'll check to see if it improves performance.
</blockquote></details>

The bitmap approach hurts typechecking performance by about 25% :(

From c8e998cc2f12804cb2ff805e8123380b7f200596 Mon Sep 17 00:00:00 2001
From: Jordan Lewis <jordanthelewis@gmail.com>
Date: Wed, 24 May 2017 13:55:18 -0400
Subject: [PATCH] sql/parser: optimization in overload chooser

The overload resolver now uses a bitmap to keep track of the remaining
valid overloads.
---
 pkg/sql/parser/overload.go | 71 +++++++++++++++++++++++++++++-----------------
 1 file changed, 45 insertions(+), 26 deletions(-)

diff --git a/pkg/sql/parser/overload.go b/pkg/sql/parser/overload.go
index f8709ba10..2cc29a409 100644
--- a/pkg/sql/parser/overload.go
+++ b/pkg/sql/parser/overload.go
@@ -313,19 +313,36 @@ func typeCheckOverloadedExprs(
 		return typedExprs, nil, nil
 	}
 
-	overloadIdxs := make([]int, len(overloads))
-	for i := 0; i < len(overloads); i++ {
-		overloadIdxs[i] = i
-	}
+	// This struct holds the indexes of the valid overloads in the overloads
+	// list using a bitmap.
+	oi := struct {
+		// bitmap is a bitmap where the ith bit, starting at the LSB, is set if the
+		// ith overoad in the overloads list is valid.
+		bitmap uint64
+		// cnt is the number of valid overloads in the overloads list.
+		cnt    uint8
+		// first is the index of the first valid overload in the overloads list.
+		first  uint8
+	}{}
+	oi.cnt = uint8(len(overloads))
+	oi.bitmap = 1 << (oi.cnt - 1)
+	oi.bitmap |= oi.bitmap - 1
+	oi.first = 0
 
 	// Function to filter overloads which return false from the provided closure.
 	filterOverloads := func(fn func(overloadImpl) bool) {
-		for i := 0; i < len(overloadIdxs); {
-			if fn(overloads[overloadIdxs[i]]) {
-				i++
-			} else {
-				overloadIdxs[i], overloadIdxs[len(overloadIdxs)-1] = overloadIdxs[len(overloadIdxs)-1], overloadIdxs[i]
-				overloadIdxs = overloadIdxs[:len(overloadIdxs)-1]
+		found := false
+		for i, b := oi.first, oi.bitmap>>oi.first; b != 0; i, b = i+1, b>>1 {
+			if b&1 == 1 {
+				if fn(overloads[i]) {
+					if !found {
+						oi.first = i
+						found = true
+					}
+				} else {
+					oi.bitmap &^= 1 << i
+					oi.cnt--
+				}
 			}
 		}
 	}
@@ -350,10 +367,10 @@ func typeCheckOverloadedExprs(
 	// Filter out overloads on resolved types.
 	for _, expr := range resolvableExprs {
 		paramDesired := TypeAny
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			// Once we get down to a single overload candidate, begin desiring its
 			// parameter types for the corresponding argument expressions.
-			paramDesired = overloads[overloadIdxs[0]].params().getAt(expr.i)
+			paramDesired = overloads[oi.first].params().getAt(expr.i)
 		}
 		typ, err := expr.e.TypeCheck(ctx, paramDesired)
 		if err != nil {
@@ -369,14 +386,14 @@ func typeCheckOverloadedExprs(
 	// if we should stop overload resolution, along with a nullable overloadImpl to return if
 	// we should stop overload resolution.
 	checkReturn := func() (bool, overloadImpl, error) {
-		switch len(overloadIdxs) {
+		switch oi.cnt {
 		case 0:
 			if err := defaultTypeCheck(false); err != nil {
 				return true, nil, err
 			}
 			return true, nil, nil
 		case 1:
-			o := overloads[overloadIdxs[0]]
+			o := overloads[oi.first]
 			p := o.params()
 			for _, expr := range constExprs {
 				des := p.getAt(expr.i)
@@ -439,7 +456,7 @@ func typeCheckOverloadedExprs(
 	}
 
 	if len(constExprs) > 0 {
-		before := overloadIdxs
+		before := oi
 
 		// The second heuristic is to prefer candidates where all numeric constants can become
 		// a homogeneous type, if all resolvable expressions became one. This is only possible
@@ -460,13 +477,13 @@ func typeCheckOverloadedExprs(
 				}
 			}
 		}
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			if ok, fn, err := checkReturn(); ok {
 				return typedExprs, fn, err
 			}
 		}
 		// Restore the expressions if this did not work.
-		overloadIdxs = before
+		oi = before
 
 		// The third heuristic is to prefer candidates where all numeric constants can become
 		// their "natural"" types.
@@ -478,13 +495,13 @@ func typeCheckOverloadedExprs(
 				})
 			}
 		}
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			if ok, fn, err := checkReturn(); ok {
 				return typedExprs, fn, err
 			}
 		}
 		// Restore the expressions if this did not work.
-		overloadIdxs = before
+		oi = before
 
 		// The fourth heuristic is to prefer candidates that accepts the "best" mutual
 		// type in the resolvable type set of all numeric constants.
@@ -521,18 +538,20 @@ func typeCheckOverloadedExprs(
 		}
 	}
 
-	if err := defaultTypeCheck(len(overloadIdxs) > 0); err != nil {
+	if err := defaultTypeCheck(oi.cnt > 0); err != nil {
 		return nil, nil, err
 	}
 
 	var preferred overloadImpl
-	for _, i := range overloadIdxs {
-		c := overloads[i]
-		if c.preferred() {
-			if preferred != nil {
-				return typedExprs, nil, nil
+	for i, b := oi.first, oi.bitmap>>oi.first; b != 0; i, b = i+1, b>>1 {
+		if b&1 == 1 {
+			c := overloads[i]
+			if c.preferred() {
+				if preferred != nil {
+					return typedExprs, nil, nil
+				}
+				preferred = c
 			}
-			preferred = c
 		}
 	}
 	return typedExprs, preferred, nil
-- 
2.12.2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by jordanlewis** [comment]
Whoops, I butchered the formatting there, look on GitHub for the updated comment.

**Comment by knz** [comment]
ack

**Comment by knz** [comment]
LGTM too, but jordan do you have a thought to react to peter's concern above?

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-KkvsljZU4HQoKyYzVqX:bus1g63) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My (small) concern is that we're doing the reset at the start of processing a query. After finishing processing a query we're holding onto the planner and any memory dangling off it until the next query is received. For a small query this isn't a problem. Could it be a problem for a large query? 
</blockquote></details>

Might be better to use a `sync.Pool` here. I think we'd get the majority of the speedup and wouldn't have an issue with a disused `planner` hanging around forever as it would be released at the next GC cycle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-KkvehKNpXxGiCeAcRGJ:b-636dp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might be better to use a `sync.Pool` here. I think we'd get the majority of the speedup and wouldn't have an issue with a disused `planner` hanging around forever as it would be released at the next GC cycle.
</blockquote></details>

I'm going to experiment with using the sync.pool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by jordanlewis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/executor.go, line 1356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-KkYa3d5VnwCVsnOzl53:-Kkvx6863An0Q19NC7Md:blw0kvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf9f36b07ec1e0f4dab96f977e5ef76ec7e7aa5e/pkg/sql/executor.go#L1356)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm going to experiment with using the sync.pool.
</blockquote></details>

Okay, I did some tests. The baseline kv read numbers on my machine are ~15700 ops/sec at r2 of this review.

Using a `sync.Pool` marginally hurts performance, clocking in at 15400 ops/sec.

Zeroing the `planner` after execution (using a "const" `emptyPlanner` struct - doing it with `session.planner = planner{}` is quite slow) marginally improves performance, resulting in ~16130 ops/sec.

I've made the latter change to this PR - it resolves Peter's concerns without introducing the extra cognitive overhead (and apparently CPU overhead as well) of the `sync.Pool`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/overload.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_CcnVAUnbxpGi7mQu:-KkzpT0VBJH7Gz-KBt9m:b3gz9yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/overload.go#L327)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The bitmap approach hurts typechecking performance by about 25% :(

From c8e998cc2f12804cb2ff805e8123380b7f200596 Mon Sep 17 00:00:00 2001
From: Jordan Lewis <jordanthelewis@gmail.com>
Date: Wed, 24 May 2017 13:55:18 -0400
Subject: [PATCH] sql/parser: optimization in overload chooser

The overload resolver now uses a bitmap to keep track of the remaining
valid overloads.
---
 pkg/sql/parser/overload.go | 71 +++++++++++++++++++++++++++++-----------------
 1 file changed, 45 insertions(+), 26 deletions(-)

diff --git a/pkg/sql/parser/overload.go b/pkg/sql/parser/overload.go
index f8709ba10..2cc29a409 100644
--- a/pkg/sql/parser/overload.go
+++ b/pkg/sql/parser/overload.go
@@ -313,19 +313,36 @@ func typeCheckOverloadedExprs(
 		return typedExprs, nil, nil
 	}
 
-	overloadIdxs := make([]int, len(overloads))
-	for i := 0; i < len(overloads); i++ {
-		overloadIdxs[i] = i
-	}
+	// This struct holds the indexes of the valid overloads in the overloads
+	// list using a bitmap.
+	oi := struct {
+		// bitmap is a bitmap where the ith bit, starting at the LSB, is set if the
+		// ith overoad in the overloads list is valid.
+		bitmap uint64
+		// cnt is the number of valid overloads in the overloads list.
+		cnt    uint8
+		// first is the index of the first valid overload in the overloads list.
+		first  uint8
+	}{}
+	oi.cnt = uint8(len(overloads))
+	oi.bitmap = 1 << (oi.cnt - 1)
+	oi.bitmap |= oi.bitmap - 1
+	oi.first = 0
 
 	// Function to filter overloads which return false from the provided closure.
 	filterOverloads := func(fn func(overloadImpl) bool) {
-		for i := 0; i < len(overloadIdxs); {
-			if fn(overloads[overloadIdxs[i]]) {
-				i++
-			} else {
-				overloadIdxs[i], overloadIdxs[len(overloadIdxs)-1] = overloadIdxs[len(overloadIdxs)-1], overloadIdxs[i]
-				overloadIdxs = overloadIdxs[:len(overloadIdxs)-1]
+		found := false
+		for i, b := oi.first, oi.bitmap>>oi.first; b != 0; i, b = i+1, b>>1 {
+			if b&1 == 1 {
+				if fn(overloads[i]) {
+					if !found {
+						oi.first = i
+						found = true
+					}
+				} else {
+					oi.bitmap &^= 1 << i
+					oi.cnt--
+				}
 			}
 		}
 	}
@@ -350,10 +367,10 @@ func typeCheckOverloadedExprs(
 	// Filter out overloads on resolved types.
 	for _, expr := range resolvableExprs {
 		paramDesired := TypeAny
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			// Once we get down to a single overload candidate, begin desiring its
 			// parameter types for the corresponding argument expressions.
-			paramDesired = overloads[overloadIdxs[0]].params().getAt(expr.i)
+			paramDesired = overloads[oi.first].params().getAt(expr.i)
 		}
 		typ, err := expr.e.TypeCheck(ctx, paramDesired)
 		if err != nil {
@@ -369,14 +386,14 @@ func typeCheckOverloadedExprs(
 	// if we should stop overload resolution, along with a nullable overloadImpl to return if
 	// we should stop overload resolution.
 	checkReturn := func() (bool, overloadImpl, error) {
-		switch len(overloadIdxs) {
+		switch oi.cnt {
 		case 0:
 			if err := defaultTypeCheck(false); err != nil {
 				return true, nil, err
 			}
 			return true, nil, nil
 		case 1:
-			o := overloads[overloadIdxs[0]]
+			o := overloads[oi.first]
 			p := o.params()
 			for _, expr := range constExprs {
 				des := p.getAt(expr.i)
@@ -439,7 +456,7 @@ func typeCheckOverloadedExprs(
 	}
 
 	if len(constExprs) > 0 {
-		before := overloadIdxs
+		before := oi
 
 		// The second heuristic is to prefer candidates where all numeric constants can become
 		// a homogeneous type, if all resolvable expressions became one. This is only possible
@@ -460,13 +477,13 @@ func typeCheckOverloadedExprs(
 				}
 			}
 		}
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			if ok, fn, err := checkReturn(); ok {
 				return typedExprs, fn, err
 			}
 		}
 		// Restore the expressions if this did not work.
-		overloadIdxs = before
+		oi = before
 
 		// The third heuristic is to prefer candidates where all numeric constants can become
 		// their "natural"" types.
@@ -478,13 +495,13 @@ func typeCheckOverloadedExprs(
 				})
 			}
 		}
-		if len(overloadIdxs) == 1 {
+		if oi.cnt == 1 {
 			if ok, fn, err := checkReturn(); ok {
 				return typedExprs, fn, err
 			}
 		}
 		// Restore the expressions if this did not work.
-		overloadIdxs = before
+		oi = before
 
 		// The fourth heuristic is to prefer candidates that accepts the "best" mutual
 		// type in the resolvable type set of all numeric constants.
@@ -521,18 +538,20 @@ func typeCheckOverloadedExprs(
 		}
 	}
 
-	if err := defaultTypeCheck(len(overloadIdxs) > 0); err != nil {
+	if err := defaultTypeCheck(oi.cnt > 0); err != nil {
 		return nil, nil, err
 	}
 
 	var preferred overloadImpl
-	for _, i := range overloadIdxs {
-		c := overloads[i]
-		if c.preferred() {
-			if preferred != nil {
-				return typedExprs, nil, nil
+	for i, b := oi.first, oi.bitmap>>oi.first; b != 0; i, b = i+1, b>>1 {
+		if b&1 == 1 {
+			c := overloads[i]
+			if c.preferred() {
+				if preferred != nil {
+					return typedExprs, nil, nil
+				}
+				preferred = c
 			}
-			preferred = c
 		}
 	}
 	return typedExprs, preferred, nil
-- 
2.12.2


</blockquote></details>

I'm surprised the bitmap approach hurt performance. 

Rather than initializing `overloadIdxs` and then removing values, you could do:

```
overloadIdxs := make([]int, 0, len(overloads))

filterOverloads := func(fn func(overloadImpl) bool) {
		for i, overload := range overloads {
			if fn(overload) {
				overloadIdxs = append(overloadIdxs, i)
			}
		}
	}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-:-Kkzp4vf--4vob728qg2:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/overload.go, line 327 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040#-Kk_CcnVAUnbxpGi7mQu:-KkzrrOWxHZcknhPOV8K:b3okcje) ([raw file](https://github.com/cockroachdb/cockroach/blob/a390bcb2a13373d4cfbc70d68c057e4a5ba55c91/pkg/sql/parser/overload.go#L327)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm surprised the bitmap approach hurt performance. 

Rather than initializing `overloadIdxs` and then removing values, you could do:

```
overloadIdxs := make([]int, 0, len(overloads))

filterOverloads := func(fn func(overloadImpl) bool) {
		for i, overload := range overloads {
			if fn(overload) {
				overloadIdxs = append(overloadIdxs, i)
			}
		}
	}
```
</blockquote></details>

Oh, I suppose that doesn't work because we filter the overloads multiple times. Carry on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16040)*

**Pull request merged**
