### PR TITLE
*: Add fast gzip compression library.

### PR DESCRIPTION
**Pull request by miretskiy**
Add https://github.com/klauspost/pgzip fast gzip
compression library.

Addresses https://github.com/cockroachdb/cockroach/issues/88585

Release notes: None

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

**Comment by cucaroach** [comment]
Marked as draft to test out some experimental code to try to figure out some CI stress failures I can't reproduce locally.

**Comment by srosenberg** [comment]
blathers backport 22.2

**Pull request merged**
