### PR TITLE
rangefeed: actually ignore intents on catch up scan

### PR DESCRIPTION
**Pull request by nvb**
This PR fixes a bug where a rangefeed's catch up scan failed to ignore
intent values. The catch up scan would ignore the intent's MVCCMetadata
key but not scan past the provisional key-value. This caused
`TestRegistrationCatchUpScan` to fail once its kvs were corrected
to accurately represent intents.

Discovered by Dan and I staring at the code. Confirmed with a manual
reproduction.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Good find. Glad Dan and you are getting some stares in together.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-:-LZByDJL6z1FwdgunUhe:b25jt3x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/storage/rangefeed/registry.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZBxn0q2euNgOLYfJcG:-LZBxn0q2euNgOLYfJcH:b9o62ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L260)):*
> ```Go
> 				// scan to the following key after it.
> 				unsafeKey.Timestamp = hlc.Timestamp(meta.Timestamp)
> 				r.catchupIter.Seek(unsafeKey)
> ```

I think this would be a little clearer if you didn't reuse `unsafeKey`. Can you just `r.catchupIter.Seek(SomethingKey{....})`?
___
*[pkg/storage/rangefeed/registry_test.go, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZBxxJv3hIrxtTj3Cfw:-LZBxxJv3hIrxtTj3Cfx:b6797kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry_test.go#L231)):*
> ```Go
> 		makeKV("m", "val8", 1),
> 		makeIntent("n", txn1, "txnKey1", 12),
> 		makeProvisionalKV("n", "txnKey1", 12),
> ```

Isn't this inviting this sort of error in the future? Why doesn't `makeIntent` automatically generate a provisional KV? It sort of ruins the way this composes here, but still.

**Review by danhhz — APPROVED** [review]
:lgtm: once @tbg is happy

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-:-LZC-YCO7IEwfNoNuxo5:b-bt2ykf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/rangefeed/registry.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZC-Daz2LeBFT15LeKc:-LZC-Daz2LeBFT15LeKd:bydn3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L255)):*
> ```Go
> 			}
> 			if !meta.IsInline() {
> 				// This is an MVCCMetadata key for an intent. Ignore this and
> ```

Can you inline here the reason why the catchup scan doesn't care about intents?
___
*[pkg/storage/rangefeed/registry.go, line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZC-PZ30c8CJQRZoTAN:-LZC-PZ30c8CJQRZoTAO:b-mwm3gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L258)):*
> ```Go
> 				// skip past the corresponding provisional key-value. To do
> 				// this, scan directly to the provisional key and let the loop
> 				// scan to the following key after it.
> ```

nit: "let the loop scan to" -> "let the loop Next to"

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35099)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/rangefeed/registry.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZC-Daz2LeBFT15LeKc:-LZC02JM1xJ_W-e7XKuB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L255)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Can you inline here the reason why the catchup scan doesn't care about intents?
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry.go, line 258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZC-PZ30c8CJQRZoTAN:-LZC05kG0en8IdqyqnXw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L258)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: "let the loop scan to" -> "let the loop Next to"
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry.go, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZBxn0q2euNgOLYfJcG:-LZC0Nqd99G89Mo7Cdwv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry.go#L260)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think this would be a little clearer if you didn't reuse `unsafeKey`. Can you just `r.catchupIter.Seek(SomethingKey{....})`?
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry_test.go, line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35099#-LZBxxJv3hIrxtTj3Cfw:-LZC4soU3eil-94zYWsU:b-rg46wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a87fac1b0bc8354c6cef2883847a3abdb0c39ef/pkg/storage/rangefeed/registry_test.go#L231)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't this inviting this sort of error in the future? Why doesn't `makeIntent` automatically generate a provisional KV? It sort of ruins the way this composes here, but still.
</blockquote></details>

Yeah, I wanted to do something like `func makeIntent() (engine.MVCCKeyValue, engine.MVCCKeyValue)`, but that doesn't work with the slice literal. I added an assertion in `newTestIterator` that all intent metadata keys are correctly paired with provisional key-values. That would catch issues like a missing `makeProvisionalKV`.

On the plus side, this keeps things explicit here that there are two keys present for an intent.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35099)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
TFTRs

bors r+

**Pull request merged**
