### PR TITLE
kvserver: stop miscomputing equivalence classes during replica rebalancing

### PR DESCRIPTION
**Pull request by aayushshah15**
**kvserver: fix bug with computing equivalence class**

Previously, while computing the stores that belong inside the same equivalence
class, we were incorrectly including an existing store in the list of candidate
stores.

For instance, an equivalence class that should look like the following:
```
eqClass:
	existing: [n1, n2]
	candidates: [n3, n4]
```
was instead being computed as the following:
```
eqClass:
	existing: [n1, n2]
	candidates: [n1, n3, n4]
```

This was throwing things off in the logic implemented by https://github.com/cockroachdb/cockroach/pull/72296

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
First commit from https://github.com/cockroachdb/cockroach/pull/73614

**Comment by aayushshah15** [comment]
@nvanbenschoten I've removed the commit that strips node ids out like we discussed. This PR should now be ready for a look.

**Review by irfansharif — APPROVED** [review]

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73597)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 915 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73597#-Mr0SWqQ6jq6d2rn7p5Z:-Mr0SWqQ6jq6d2rn7p5_:bnww4sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8050265aebc2e2e4e97748d1560550f459c8004d/pkg/kv/kvserver/allocator_scorer.go#L915)):*
> ```Go
> 				diversityScore: diversityScore,
> 			}
> 			if !cand.less(existing) && cand.store.StoreID != existing.store.StoreID {
> ```

Should we wait until we get all the way here in this loop before continuing? Would it make more sense to move this up to the top of the loop?
___
*[pkg/kv/kvserver/allocator_scorer.go, line 967 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73597#-Mr0T2DQBoPPneVWkbOc:-Mr0T2DQBoPPneVWkbOd:b-6yy6d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8050265aebc2e2e4e97748d1560550f459c8004d/pkg/kv/kvserver/allocator_scorer.go#L967)):*
> ```Go
> 			// replicas in terms of diversity and disk fullness, check whether the
> 			// existing replicas' stats are divergent enough to justify a rebalance.
> 			if len(sl.stores) > 0 && options.shouldRebalanceBasedOnThresholds(ctx, existing.store, sl) {
> ```

When do we expect to hit the `len(sl.stores) > 0` case? Is that when we don't have an equivalence class for an existing store?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73597)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 915 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73597#-Mr0SWqQ6jq6d2rn7p5Z:-Mr4EUusAY4MTuf3e6-3:bs40vxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8050265aebc2e2e4e97748d1560550f459c8004d/pkg/kv/kvserver/allocator_scorer.go#L915)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we wait until we get all the way here in this loop before continuing? Would it make more sense to move this up to the top of the loop?
</blockquote></details>

moved up. 
___
*[pkg/kv/kvserver/allocator_scorer.go, line 967 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73597#-Mr0T2DQBoPPneVWkbOc:-Mr4EWDy7mbCkzVkP7eu:b3w53gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8050265aebc2e2e4e97748d1560550f459c8004d/pkg/kv/kvserver/allocator_scorer.go#L967)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When do we expect to hit the `len(sl.stores) > 0` case? Is that when we don't have an equivalence class for an existing store?
</blockquote></details>

we'd expect `len(candidateSL)` > 0 if there are any replacement candidates for the existing store that are at least as good in terms of diversity. Otherwise, we expect that slice to be empty. I moved the length check inside the `shouldRebalanceBasedOnThresholds` methods.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73597#-:-Mr9IjyQ6mXWyFDV5kxu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by aayushshah15** [comment]
TFTR

bors r+

**Pull request merged**
