### PR TITLE
sql: prohibit creation of prepared EXPLAIN ANALYZE statements

### LINKED ISSUE #98731: sql: consider prohibiting creation of prepared EXPLAIN ANALYZE statements
```sql
PREPARE p AS EXPLAIN ANALYZE SELECT 1;
EXECUTE p;
```
results in
```
ERROR: EXPLAIN ANALYZE can only be used as a top-level statement
```
We should just return on an error on PREPARE right away.

Postgres doesn't allow any flavor of EXPLAIN as the prepared statement (in CRDB prepared non-ANALYZE EXPLAIN works ok but maybe also should be disallowed?). 

Jira issue: CRDB-25472

### PR DESCRIPTION
**Pull request by highpon**
Fixes: #98731.

Release note (sql change): PREPARE'ing of EXPLAIN ANALYZE statements is
now prohibited. Previously, this was allowed, but then attempting to
EXECUTE the prepared EXPLAIN ANALYZE statements would result in an
error.

### CODE REVIEW

**Comment by highpon** [comment]
I forgot to write the test. My apologies.
When I finish writing the test, I will open this pull request again

**Review by yuzefovich — APPROVED** [review]
:lgtm:

I adjusted some nits I had, will merge on green CI, thank you for your contribution!

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103259#-:-NVVDdly1jVePzUgSmpj:be6jge0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @highpon)

**Comment by yuzefovich** [comment]
bors r=yuzefovich

**Comment by highpon** [comment]
Thank you for your help yuzefovich!

**Pull request merged**
