### PR TITLE
storage: add Reader and Writer wrappers for separated intents

### PR DESCRIPTION
**Pull request by sumeerbhola**
The first commit contains some preparation for the intent demultiplexing writer:
- Move SingleClearEngineKey back into the Writer interface.
- Add PrecedingIntentState to the storage interface.
- Add optional TxnDidNotUpdateMeta to MVCCMetadata.

The second commit contains the wrappers:
- the signature of PutIntent and ClearIntent is extended.
- intentDemuxWriter implements 3 methods in the Writer
  interface.
- intentInterleavingReader is a wrapped Reader that can
  read separated intents.
- The existing Reader, Writer implementations are changed
  to use these wrappers.
- There are TODOs to fix the callers of PutIntent and
  ClearIntent to pass the correct parameters -- these will
  be fixed in a later PR.

Separated intents are not enabled since we are not done
with code changes to prepare for it.

Informs cockroachdb#41720

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I owe a unit test for `intentDemuxWriter` and `intentInterleavingReader`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-:-MMXoGGlEKghoyRotiBQ:b-s2pt2p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYFc201ws0DkoSzkAt:-MMYFc201ws0DkoSzkAu:b-uvn5wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/engine.go#L347)):*
> ```
> txnDidNotUpdateMeta
> ```

What does the future hold for this parameter, along with `MVCCMetadata.TxnDidNotUpdateMeta`? Will they be needed once the interleaved intents have been fully migrated away? Will we guarantee that lock table keys are SingleDelete-able even if they are updated? In other words, will we SingleDelete + Put when updating lock table keys?
___
*[pkg/storage/intent_reader_writer.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYSMz_6XViRGfrNrMe:-MMYSMz_6XViRGfrNrMf:bl7kpa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L64)):*
> ```Go
> 
> func (idw intentDemuxWriter) ClearIntent(
> 	key roachpb.Key, state PrecedingIntentState, possiblyUpdated bool, txnUUID uuid.UUID,
> ```

Should we keep all of these `txnDidNotUpdateMeta/possiblyUpdated/precedingPossiblyUpdated` names the same?
___
*[pkg/storage/intent_reader_writer.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYS5E02ka-xqu18ZVF:-MMYS5E02ka-xqu18ZVG:bslvdol) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L73)):*
> ```Go
> 			Key:      key,
> 			Strength: lock.Exclusive,
> 			TxnUUID:  txnUUID[:],
> ```

Does this plus the call to `ToEngineKey` cause the uuid array to escape to the heap?
___
*[pkg/storage/intent_reader_writer.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYSjbr69mZNiMGGXNH:-MMYSjbr69mZNiMGGXNI:boyzbj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L74)):*
> ```Go
> 			Strength: lock.Exclusive,
> 			TxnUUID:  txnUUID[:],
> 		}.ToEngineKey()
> ```

Drive-by comment: can we combine the two slice allocations in `ToEngineKey()` into a single alloc? Seems like the size would be `len(LocalRangeLockTablePrefix) + len(LockTableSingleKeyInfix) + len(key) + 3 + engineKeyVersionLockTableLen`.
___
*[pkg/storage/intent_reader_writer.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYT-Sg6wYOhhX221lV:-MMYT-Sg6wYOhhX221lW:b1o7cp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L100)):*
> ```Go
> 	}
> 	if state == ExistingIntentSeparated && !enabledSeparatedIntents {
> 		// Switching this intent from separated to to interleaved.
> ```

"to be"?
___
*[pkg/storage/intent_reader_writer.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTZqP2le5s1yAA2Yw:-MMYTZqP2le5s1yAA2Yx:b-ie1hiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L133)):*
> ```Go
> 	lstart, _ := keys.LockTableSingleKey(start, nil)
> 	lend, _ := keys.LockTableSingleKey(end, nil)
> 	err = idw.w.ClearRawRange(lstart, lend)
> ```

nit: any reason not to `return idw.w.ClearRawRange(lstart, lend)`?
___
*[pkg/storage/intent_reader_writer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTqr1Er2T6SaGBhCh:-MMYTqr1Er2T6SaGBhCi:baas42v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L157)):*
> ```Go
> }
> 
> func tryWrapReader(r wrappableReader, iterKind MVCCIterKind) (reader Reader, wrapped bool) {
> ```

This diverges from `tryWrapIntentWriter` in two ways. I'm not sure that either are intentional or whether we'll want to change things here or up above for uniformity.
1. Should this be called `tryWrapIntentReader`?
2. Should this return an `intentInterleavingReader` or a `Reader` instance? The former may avoid an allocation in some cases, depending on the caller.
___
*[pkg/storage/intent_reader_writer.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYUpqk5mWV8_TzxCcd:-MMYUpqk5mWV8_TzxCce:bv9cwlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L183)):*
> ```Go
> 	valid, err := iter.SeekEngineKeyGE(EngineKey{Key: ltKey})
> 	if !valid || err != nil {
> 		return nil, err
> ```

Are we closing the `iter` on this path? Should we `defer iter.Close()` above?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

I'll ping when the test is ready.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-:-MMb1d1D9-LEKzk9ddrJ:bywo48g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/engine.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYFc201ws0DkoSzkAt:-MMaEBRW-4AH2kxSpbR7:b-1za3su) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/engine.go#L347)):*
> What does the future hold for this parameter, along with MVCCMetadata.TxnDidNotUpdateMeta? Will they be needed once the interleaved intents have been fully migrated away?

My plan was to keep this forever.

> Will we guarantee that lock table keys are SingleDelete-able even if they are updated? In other words, will we SingleDelete + Put when updating lock table keys?

No, we only do SingleDelete when resolving intents, or when moving from separated to interleaved (which will go away in the fully separated world). If we start doing SingleDelete+Put instead of Put, when updating, we would need to be sure that we are not causing a performance regression. The tracking for this field is quite straightforward, based on my experience in the prototype -- it is localized to callers of `putBuffer` in `mvcc.go`. 
___
*[pkg/storage/intent_reader_writer.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYSMz_6XViRGfrNrMe:-MMaH03C9hVKU_XfVVKy:bfeixij) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we keep all of these `txnDidNotUpdateMeta/possiblyUpdated/precedingPossiblyUpdated` names the same?
</blockquote></details>

Oops (used Goland to find all interface implementations and of course this doesn't implement Writer). Fixed.
___
*[pkg/storage/intent_reader_writer.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYS5E02ka-xqu18ZVF:-MMaJ4Hw39Dk2EVs6vTB:b-ymw2xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this plus the call to `ToEngineKey` cause the uuid array to escape to the heap?
</blockquote></details>

Good question. I've checked and it doesn't.
___
*[pkg/storage/intent_reader_writer.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYSjbr69mZNiMGGXNH:-MMaevv711GM5TuN1Orx:b-fsi2lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Drive-by comment: can we combine the two slice allocations in `ToEngineKey()` into a single alloc? Seems like the size would be `len(LocalRangeLockTablePrefix) + len(LockTableSingleKeyInfix) + len(key) + 3 + engineKeyVersionLockTableLen`.
</blockquote></details>

I've combined the allocations, and added some commentary around length estimation in `keys.go`. Also, changed `pebbleBatch` to pass in a buffer that can be reused since that is the single-threaded user of this (unlike `Pebble`).
___
*[pkg/storage/intent_reader_writer.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYT-Sg6wYOhhX221lV:-MMamJEM2otkoMeusQ00:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L100)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"to be"?
</blockquote></details>

Done
___
*[pkg/storage/intent_reader_writer.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTZqP2le5s1yAA2Yw:-MMamQUgEyEdZSQT6KBt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L133)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: any reason not to `return idw.w.ClearRawRange(lstart, lend)`?
</blockquote></details>

Done
___
*[pkg/storage/intent_reader_writer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTqr1Er2T6SaGBhCh:-MMan7zF3zF9uVMnvDAa:b-c1r7ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L157)):*
> This diverges from tryWrapIntentWriter in two ways. I'm not sure that either are intentional or whether we'll want to change things here or up above for uniformity.
> 
> Should this be called tryWrapIntentReader?

It was intentional. `intentInterleavingReader` implements `Reader`, while `intentDemuxWriter` does not implement `Writer`.
- `intentDemuxWriter` does not implement `Writer` to avoid introducing a level of indirection via an interface for functions that don't need it -- e.g. `pebbleBatch.clearMVCC` can directly do its thing.
- `intentInterleavingReader` implements `Reader` since it needs to be passed onto various functions like `pebbleExportToSst`, that need a `Reader`. So they are already using an interface, and returning an `intentInterleavingReader` won't help. There is one case where returning an `intentInterleavingReader` would help with avoiding the itable lookup -- `NewMVCCIterator`. But then all the other cases that do something like
```
r, _ := tryWrapReader(p, MVCCKeyAndIntentsIterKind)
return doSomething(r)
```

would become
```
if r, wrapped := tryWrapReader(p, MVCCKeyAndIntentsIterKind); wrapped {
  return doSomething(r)
}
return doSomething(p)
```
Which is a bit uglier. And I'm assuming `NewMVCCIterator` is not where we care about an extra itable lookup.

> Should this return an intentInterleavingReader or a Reader instance? The former may avoid an allocation in some cases, depending on the caller.

Trying to understand this allocation concern: `intentInterleavingReader` has one member, `wrappableReader` which will be implemented by a struct pointer (Pebble/pebbleBatch/...). If the struct pointer needs to be on the heap, and `intentInterleavingReader` does not fit into a single machine word, then we would need another heap allocation for the `intentInterleavingReader` (and the interface would have a pointer to this allocated space). Is that the allocation you are concerned about?
I assumed escape analysis could tell us, so I tried the following:
```
var r1 Reader
var r2 intentInterleavingReader

func TestIntentInterleavingReader(t *testing.T) {
	iir1 := intentInterleavingReader{wrappableReader: &Pebble{}}
	iir2 := intentInterleavingReader{wrappableReader: &Pebble{}}
	r1 = iir1
	r2 = iir2
}
```
Which results in
```
./intent_reader_writer_test.go:19:52: &Pebble literal escapes to heap
./intent_reader_writer_test.go:20:52: &Pebble literal escapes to heap
./intent_reader_writer_test.go:21:5: iir1 escapes to heap
```
So your concern is valid, but it wasn't clear why. So I looked at sizeof(intentInterleavingReader) and it is 16, which makes sense since it contains an interface, which is 16 bytes.
___
*[pkg/storage/intent_reader_writer.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYUpqk5mWV8_TzxCcd:-MMb1LQI2mpSUqKJGynR:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we closing the `iter` on this path? Should we `defer iter.Close()` above?
</blockquote></details>

Done

**Review by sumeerbhola — COMMENTED** [review]
Added a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-:-MMllvesDO4NIoM53jrS:b-7gclag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/storage/intent_reader_writer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTqr1Er2T6SaGBhCh:-MMbnQBz553myhVA-ESy:bjmlvm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L157)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> This diverges from tryWrapIntentWriter in two ways. I'm not sure that either are intentional or whether we'll want to change things here or up above for uniformity.
> 
> Should this be called tryWrapIntentReader?

It was intentional. `intentInterleavingReader` implements `Reader`, while `intentDemuxWriter` does not implement `Writer`.
- `intentDemuxWriter` does not implement `Writer` to avoid introducing a level of indirection via an interface for functions that don't need it -- e.g. `pebbleBatch.clearMVCC` can directly do its thing.
- `intentInterleavingReader` implements `Reader` since it needs to be passed onto various functions like `pebbleExportToSst`, that need a `Reader`. So they are already using an interface, and returning an `intentInterleavingReader` won't help. There is one case where returning an `intentInterleavingReader` would help with avoiding the itable lookup -- `NewMVCCIterator`. But then all the other cases that do something like
```
r, _ := tryWrapReader(p, MVCCKeyAndIntentsIterKind)
return doSomething(r)
```

would become
```
if r, wrapped := tryWrapReader(p, MVCCKeyAndIntentsIterKind); wrapped {
  return doSomething(r)
}
return doSomething(p)
```
Which is a bit uglier. And I'm assuming `NewMVCCIterator` is not where we care about an extra itable lookup.

> Should this return an intentInterleavingReader or a Reader instance? The former may avoid an allocation in some cases, depending on the caller.

Trying to understand this allocation concern: `intentInterleavingReader` has one member, `wrappableReader` which will be implemented by a struct pointer (Pebble/pebbleBatch/...). If the struct pointer needs to be on the heap, and `intentInterleavingReader` does not fit into a single machine word, then we would need another heap allocation for the `intentInterleavingReader` (and the interface would have a pointer to this allocated space). Is that the allocation you are concerned about?
I assumed escape analysis could tell us, so I tried the following:
```
var r1 Reader
var r2 intentInterleavingReader

func TestIntentInterleavingReader(t *testing.T) {
	iir1 := intentInterleavingReader{wrappableReader: &Pebble{}}
	iir2 := intentInterleavingReader{wrappableReader: &Pebble{}}
	r1 = iir1
	r2 = iir2
}
```
Which results in
```
./intent_reader_writer_test.go:19:52: &Pebble literal escapes to heap
./intent_reader_writer_test.go:20:52: &Pebble literal escapes to heap
./intent_reader_writer_test.go:21:5: iir1 escapes to heap
```
So your concern is valid, but it wasn't clear why. So I looked at sizeof(intentInterleavingReader) and it is 16, which makes sense since it contains an interface, which is 16 bytes.


</blockquote></details>

btw, I didn't make a change here since there are only 2 kinds of callers to `tryWrapReader`
- immediately call a single method on the returned `Reader` and return, so `intentInterleavingReader` will not escape to the heap.
- pass on to another function that expects a `Reader`, so returning `intentInterleavingReader` from here will not help.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-:-MMn9q_i5T5MDiD5UDUk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/keys/keys.go, line 431 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMn1nl89__by8QI_z-Y:-MMn1nl89__by8QI_z-Z:bb22kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79387922e38c1f6465cd42b6a36a24d559424561/pkg/keys/keys.go#L431)):*
> ```Go
> func LockTableSingleKey(key roachpb.Key, buf []byte) (roachpb.Key, []byte) {
> 	// The +3 accounts for the bytesMarker and terminator. Note that this is an
> 	// estimate, since the escaping done by EncodeBytesAscending depends on what
> ```

This is an estimate, but also a lower bound, right?
___
*[pkg/storage/engine.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYFc201ws0DkoSzkAt:-MMn1HC7ECSEndjuJBhR:b-5w5rsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/engine.go#L347)):*
> If we start doing SingleDelete+Put instead of Put, when updating, we would need to be sure that we are not causing a performance regression.

Ack. Do you think this will be a worthwhile test to run at some point, or do you have suspect that it won't be worth it?
___
*[pkg/storage/intent_reader_writer.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYS5E02ka-xqu18ZVF:-MMn3DoA7F0sJXjbJQ59:b-nav911) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Good question. I've checked and it doesn't.
</blockquote></details>

Thanks for checking.
___
*[pkg/storage/intent_reader_writer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTqr1Er2T6SaGBhCh:-MMn4fQX92UdQ1mUXpo8:b-9e5mxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L157)):*
> Is that the allocation you are concerned about?

Right, that's the one I'm referring to.

> So I looked at sizeof(intentInterleavingReader) and it is 16, which makes sense since it contains an interface, which is 16 bytes.

I'm not sure that the fact that sizeof(intentInterleavingReader) is larger than a single machine word is coming into play here. Even if it was only 8 bytes large, stuffing it by value into an interface will still result in it escaping to the heap. This has been true ever since the Go compiler rewrite from C to Go in Go 1.4. For more on this, see "The implementation of interface values has been modified. ..." in https://golang.org/doc/go1.4#impl. There has been a bit of work in recent revisions of the compiler to avoid dynamically allocating all values placed in interfaces, but nothing dramatic: https://utcc.utoronto.ca/~cks/space/blog/programming/Go115InterfaceSmallInts.

The moral of the story, at least to me, is that implementing interfaces by value almost never makes sense, except under very specific situations. For instance, it can occasionally be useful due to the way [interface comparison works](https://golang.org/ref/spec#Comparison_operators).
___
*[pkg/storage/intent_reader_writer_test.go, line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMn9kKzBcSVsQIGrwmZ:-MMn9kKzBcSVsQIGrwm_:b-kszn3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/79387922e38c1f6465cd42b6a36a24d559424561/pkg/storage/intent_reader_writer_test.go#L252)):*
> ```Go
> 				printEngContents(&pw.b, eng)
> 				return pw.b.String()
> 			case "clear-range":
> ```

Did you want to test this?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/keys/keys.go, line 431 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMn1nl89__by8QI_z-Y:-MMpSbot-EShiS3yCgBq:b-fvwm01) ([raw file](https://github.com/cockroachdb/cockroach/blob/79387922e38c1f6465cd42b6a36a24d559424561/pkg/keys/keys.go#L431)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is an estimate, but also a lower bound, right?
</blockquote></details>

Correct. I've updated the comment.
___
*[pkg/storage/engine.go, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYFc201ws0DkoSzkAt:-MMpUULfCRtnQtIsz1Re:bpq85n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/engine.go#L347)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> If we start doing SingleDelete+Put instead of Put, when updating, we would need to be sure that we are not causing a performance regression.

Ack. Do you think this will be a worthwhile test to run at some point, or do you have suspect that it won't be worth it?
</blockquote></details>

It is worth it, since I'm assuming repeated Puts by the same transaction won't be common. I've added a TODO.
___
*[pkg/storage/intent_reader_writer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMYTqr1Er2T6SaGBhCh:-MMpUtD98_OHKYfWR6uU:b-oporf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0197e46ac0b87b6da5a3ee1e7e48b5c8284dfe62/pkg/storage/intent_reader_writer.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Is that the allocation you are concerned about?

Right, that's the one I'm referring to.

> So I looked at sizeof(intentInterleavingReader) and it is 16, which makes sense since it contains an interface, which is 16 bytes.

I'm not sure that the fact that sizeof(intentInterleavingReader) is larger than a single machine word is coming into play here. Even if it was only 8 bytes large, stuffing it by value into an interface will still result in it escaping to the heap. This has been true ever since the Go compiler rewrite from C to Go in Go 1.4. For more on this, see "The implementation of interface values has been modified. ..." in https://golang.org/doc/go1.4#impl. There has been a bit of work in recent revisions of the compiler to avoid dynamically allocating all values placed in interfaces, but nothing dramatic: https://utcc.utoronto.ca/~cks/space/blog/programming/Go115InterfaceSmallInts.

The moral of the story, at least to me, is that implementing interfaces by value almost never makes sense, except under very specific situations. For instance, it can occasionally be useful due to the way [interface comparison works](https://golang.org/ref/spec#Comparison_operators).
</blockquote></details>

Thanks -- these links were very helpful.
___
*[pkg/storage/intent_reader_writer_test.go, line 252 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMn9kKzBcSVsQIGrwmZ:-MMpXq6M9p10AxjIpqe5:b1qutl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/79387922e38c1f6465cd42b6a36a24d559424561/pkg/storage/intent_reader_writer_test.go#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you want to test this?
</blockquote></details>

Oops. Glad you noticed :)
Done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-:-MMpo88Q7YItplG7--qM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56934)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/intent_reader_writer.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56934#-MMvMn4G0W7DnlNXRIo9:-MMvMn4G0W7DnlNXRIoA:b8i84nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a93a534818b0ad0716bb101856bcc468c2acc86/pkg/storage/intent_reader_writer.go#L45)):*
> ```Go
> // happen yet).
> const disallowSeparatedIntents = true
> const enabledSeparatedIntents = false
> ```

@nvanbenschoten @petermattis 

I'm thinking through the testing plan for end-to-end correctness testing. Ideally we would want to run all CRDB tests with all of the following cases:
A. disallowSeparatedIntents=true (which we currently do)
B. disallowSeparatedIntents=false, enabledSeparatedIntents=false
C. disallowSeparatedIntents=false, enabledSeparatedIntents=true
D. disallowSeparatedIntents=false and switching back and forth between enabledSeparatedIntents={false,true}

There are issues with this:
- The cost of running all tests 4 times. Should we be running them nightly instead, and how would we accomplish that? And should this differ for unit tests vs roachtests?
- How to run case D.
  - For the unit testing here I've injected `enabledSeparatedIntents` into `intentDemuxWriter`. But that isn't viable for code that doesn't know or care about how intents are implemented. One possibility is to inject a value at node startup.
  - Do you have suggestions for existing unit and roach tests that use multiple nodes or restart nodes where I could inject different values of enabledSeparatedIntents for different nodes or when restarting?

Any other ideas?

**Comment by petermattis** [comment]
> The cost of running all tests 4 times. Should we be running them nightly instead, and how would we accomplish that? And should this differ for unit tests vs roachtests?

One thing we've done in the past is to randomly select a different configuration when running a test. Running all of the tests 4 times is likely too cost prohibitive. Certainly we can do one-off runs, though.

**Comment by nvanbenschoten** [comment]
One-off runs for A, B, and C seem reasonable. We could hook the values up to environment variables and then control them in roachtests.

For D, would a random coin flip each time we consult the value be sufficient to get good test coverage? Perhaps we could introduce an `enabledSeparatedIntents=rand` option and then add that into the mix of configs we test nightly?

**Pull request merged**
