### PR TITLE
opt: support ShowVar

### PR DESCRIPTION
**Pull request by RaduBerinde**
Move `ShowVar` implementation to `delegate`.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37193#-:-LdeudAa1AFTmMjpTEGK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Comment by RaduBerinde** [comment]
oops, didn't see the CI failure.

bors r-

**Pull request merged**
