### PR TITLE
cleanup according to `make unused`

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6312)

### CODE REVIEW

**Comment by bdarnell** [comment]
The removals LGTM, but I'd rather not introduce dummy references to things just to silence the unused warnings (unless this gets us to the point that we can promote `unused` to `make check`). It's better to either add a test (even if it's a stupid test, like a test for EnvOrDefaultBytes that only tests the default case) or leave them unused.

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[client/txn_test.go, line 39 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6312#-KGHrnJFjS5CPhNESrPV:-KGHrnJGBhQZR8XdtRub:2098197404) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad01e630c3f887687ed7e7132a9a13bbe8c85c02/client/txn_test.go#L39)):*
This can be done outside of an `init` function:

```
var _ = (*Txn).InitPut
```

When I've done this in the past, I've also added a `TODO`. Such silencing should only be a stop-gap and should be done to draw attention to an item that should either be removed or tested. Something like:

```
// TODO(pmattis): Container.Pause is neither used or tested. Silence unused
// warning.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6312#-:-KGHs_9SpIZLl9BAdLwH:1417088721)*

**Comment by tschottdorf** [comment]
Done. I'll PR absorbing `unused` into `check` separately as that might actually require some discussion.

**Comment by petermattis** [comment]
@tschottdorf See #5602.

**Comment by tschottdorf** [comment]
@petermattis, thanks. #6317.

**Pull request merged**
