### PR TITLE
[prototype] sql,server: wire up reconciliation job to connector

### LINKED ISSUE #66394: kvserver: establish per-store rangefeed over `system.span_configurations`
Part of #66348. Use it to maintain an in-memory cache/tree of spans and the corresponding span configs. We'll want to consult this data structure to determine splits and configs for individual ranges.

```go
type SpanConfigs interface {
  GetConfigFor(key roachpb.Key) roachpb.SpanConfig
  GetSplitsBetween(start, end roachpb.Key) []roachpb.Key
}
```

### PR DESCRIPTION
**Pull request by irfansharif**
And also establish a rangefeed per store on the span-configurations
table. The reconciliation job, when run (for each tenant), for now
continually writes a dummy entry that's picked up by all stores.

We extend the same functionality for the host tenant, which does not
need to go through the connector object. This commit also restructures
some of our recent work around a shared package.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 32 of 32 files at r1, 11 of 11 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 14 of 14 files at r5, 11 of 11 files at r6, 1 of 32 files at r8, 49 of 78 files at r9, 22 of 36 files at r10, 17 of 18 files at r11, 2 of 3 files at r12, 1 of 1 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66892)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/server/reconciliation_test.go, line 12 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev4gd2D3RkFHvkiMsa:-Mev4gd2D3RkFHvkiMsb:b-i1rxy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/server/reconciliation_test.go#L12)):*
> ```Go
> 
> package server
> ```

How do you feel about adding a bit more testing around the Watcher? Something where we seed the span config table to begin with and then update/delete entries to make sure the Watcher is sending the forth the right Updates. 
___
*[pkg/spanconfig/spanconfig.go, line 28 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev6LgA3F1Ylnucxs5i:-Mev6LgA3F1Ylnucxs5j:b-if9pmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfig.go#L28)):*
> ```Go
> 	// GetSpanConfigsFor retrieves the span configurations over the requested
> 	// span.
> 	GetSpanConfigsFor(ctx context.Context, span roachpb.Span) ([]roachpb.SpanConfigEntry, error)
> ```

nit: s/GetSpanConfigsFor/GetSpanConfigEntry/s 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 31 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev2R6ZDvXS8v5BD8TN:-Mev2R6ZDvXS8v5BD8TO:b-apcvul) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfigmanager/manager.go#L31)):*
> ```Go
> 	db    *kv.DB
> 	jr    *jobs.Registry
> 	ie    tree.InternalExecutor
> ```

The comment in `eval.go` seems to warn against using this interface -- do we have to, or can we get by by using sql.InternalExecutor or sqlutil.InternalExecutor? 
___
*[pkg/spanconfig/spanconfigwatcher/decoder.go, line 58 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-MefsbsI1i23U4JjZueL:-MefsbsI1i23U4JjZueM:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/813f0751beb58eb93ce4e5e877e728fa7108bdab/pkg/spanconfig/spanconfigwatcher/decoder.go#L58)):*
> ```Go
> 		}
> 		if !matches {
> 			return roachpb.SpanConfigEntry{}, errors.AssertionFailedf("system.span_configurations descriptor does not match key: %v", kv.Key)
> ```

nit: long line
___
*[pkg/spanconfig/spanconfigwatcher/watcher.go, line 64 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev0YKS6wSFilk5MHow:-Mev0YKS6wSFilk5MHox:b5b965u) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfigwatcher/watcher.go#L64)):*
> ```Go
> 		deleted := !ev.Value.IsPresent()
> 		var value roachpb.Value
> 		if !deleted {
> ```

nit: maybe it's just me, but I'd find structuring this as:
```
value := ev.Value
if deleted {
...
}
```
much clearer

**Review by irfansharif — COMMENTED** [review]
Mind stamping it away?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-:-Mf-N-YD4DQi5mcSDzYl:bpv0cz8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/server/reconciliation_test.go, line 12 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev4gd2D3RkFHvkiMsa:-Mf-MQbh9QNiaAU_Idip:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/server/reconciliation_test.go#L12)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

How do you feel about adding a bit more testing around the Watcher? Something where we seed the span config table to begin with and then update/delete entries to make sure the Watcher is sending the forth the right Updates. 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 28 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev6LgA3F1Ylnucxs5i:-Mf-MS-Q5wy9AR_LBmEX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfig.go#L28)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/GetSpanConfigsFor/GetSpanConfigEntry/s 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 31 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev2R6ZDvXS8v5BD8TN:-Mf-MV3d6A2UD0P8M5sb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfigmanager/manager.go#L31)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The comment in `eval.go` seems to warn against using this interface -- do we have to, or can we get by by using sql.InternalExecutor or sqlutil.InternalExecutor? 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigwatcher/decoder.go, line 58 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-MefsbsI1i23U4JjZueL:-Mf-MTiZ3odWYU0zbYnQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/813f0751beb58eb93ce4e5e877e728fa7108bdab/pkg/spanconfig/spanconfigwatcher/decoder.go#L58)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigwatcher/watcher.go, line 64 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mev0YKS6wSFilk5MHow:-Mf-Mw_h2267oVUuSaZm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acba3788f5017eb76e5d3c478a0c60d40e880369/pkg/spanconfig/spanconfigwatcher/watcher.go#L64)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: maybe it's just me, but I'd find structuring this as:
```
value := ev.Value
if deleted {
...
}
```
much clearer
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 20 files at r15, 2 of 4 files at r16, 7 of 13 files at r17, 2 of 2 files at r18, 2 of 11 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-:-Mf-daO_-kgbCGbU-pkA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 48 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mf-aviG3NPgQhSJLGCF:-Mf-aviHEtGS2ijET8tZ:b-z50np6) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f93d6630a8944310c4a886f923a6843bbad8de/pkg/spanconfig/spanconfigmanager/manager.go#L48)):*
> ```Go
> 	ie sqlutil.InternalExecutor,
> 	accessor spanconfig.Accessor,
> 	knobs *spanconfigwatcher.TestingKnobs,
> ```

Should we move the knobs back into the `spanconfig` package? Putting them in `spanconfigwatcher` seems weird considering they (among other things) control job creation.

**Review by irfansharif — COMMENTED** [review]
For some reason this branch keeps tripping up TestDockerCLI/test_secure.tcl. The build log is not helpful, and I'm not getting anywhere -- so just commenting that bit out for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-:-Mf-ucTTB49HjbhMUsAA:b-wqgwi2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 48 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/66892#-Mf-aviG3NPgQhSJLGCF:-Mf-uWZQAS3zx6VOIosc:bhlwuun) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f93d6630a8944310c4a886f923a6843bbad8de/pkg/spanconfig/spanconfigmanager/manager.go#L48)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we move the knobs back into the `spanconfig` package? Putting them in `spanconfigwatcher` seems weird considering they (among other things) control job creation.
</blockquote></details>

Meant to move it to the spanconfigmanager package. Need it there because of the dependency on jobs.

**Pull request merged**
