### PR TITLE
sql: stop SQLRunner from swallowing query errors

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by knz** [comment]
This might want a test.

**Comment by andreimatei** [comment]
friendly ping

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24994#-:-LB1SvDA9NveJqqh0Jf0:b-50swta)*

**Comment by knz** [comment]
Thanks for the test! But I think it can be simplified. I'm not very fond of the new built-in. See suggestion below.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/testutils/sqlutils/sql_runner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24994#-LB1TXDX8yb0EpBiwa65:-LB1TXDX8yb0EpBiwa66:b-tb3ol7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe0b3185315cbc493be0c6dd8da9d64299d3339/pkg/testutils/sqlutils/sql_runner_test.go#L37)):*
> ```Go
> 	// We'll run a query that only fails after returning some rows, so that the
> 	// error is discovered by RowsToStrMatrix below.
> 	rows, err := db.Query("SELECT crdb_internal.generate_series_err(10)")
> ```

I'd recommend `select generate_series(10) union all select crdb_internal.force_error('00000', 'foo')` instead, and remove that very ugly generate_series_err. :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24994#-:-LB1Ty0e6RjUowmcE5iE:bnlkv6a)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/testutils/sqlutils/sql_runner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24994#-LB1TXDX8yb0EpBiwa65:-LB1bPnB6YEz39e-wJNr:bo1oe24) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fe0b3185315cbc493be0c6dd8da9d64299d3339/pkg/testutils/sqlutils/sql_runner_test.go#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd recommend `select generate_series(10) union all select crdb_internal.force_error('00000', 'foo')` instead, and remove that very ugly generate_series_err. :)
</blockquote></details>

done, good suggestion

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24994)*

**Comment by andreimatei** [comment]
bors r+

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24994#-:-LB1bak7Da13Kuiwhh82:b-ydi9ay)*

**Pull request merged**
