### PR TITLE
acceptance: updates to try to resolve flakiness

### PR DESCRIPTION
**Pull request by rafiss**
This is an experiment to see if there's any effect on the errors described in #58955 (and 5 or so tests that are flaky because of that issue).

```
dockercluster.go:683: unexpected extra event &{0 die} (after [])
```

caused by

```
  000006.log:
 +orig err: open â€¹/data0.0/000006.logâ€º: no such file or directory
 +list err: readdirent: no such file or directory
 !goroutine 260 [running]:
 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x8170900, 0x203000, 0x203000, 0x7f892f0bd998)
 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb9
 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000eaf280, 0xc0025ab4a0, 0x24, 0x1, 0x0, 0x0, 0x0, 0x16610602dd2562ba, 0x400000000, 0x3, ...)
 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:277 +0xc67
 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(0x5650740, 0xc000e7d650, 0x2, 0x300000004, 0x4969015, 0x1d, 0xc002b68390, 0x3, 0x3)
 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:58 +0x198
 !github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.FatalfDepth(...)
 !	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:2022
 !github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf(...)
 !	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:401
 !github.com/cockroachdb/pebble/internal/base.MustExist(0x5794980, 0xc000d9d800, 0xc00231baa0, 0x13, 0x7f892f0c4000, 0xc000d9d8e0, 0x55b7de0, 0xc002865260)
 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:132 +0x6a8
 !github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0xc000600800, 0xc001776960, 0x18115, 0x20000)
 !	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:1419 +0x110f
```

As described in https://github.com/cockroachdb/cockroach/issues/57192#issuecomment-744550828, it's possible that these `no such file` errors had been happening before, but an update to pebble in v20.2 might have made this fail louder.

### cluster: update default image

The acceptance test harness has two docker images. This default image is used by `StartCluster`.
There is another image (`acceptanceImage`) used when calling `l.OneShot`

See https://github.com/cockroachdb/cockroach/blob/7be33c18a9ae9c70bb7b223812136734ea8cd04b/pkg/acceptance/util_docker.go#L64-L66

IDK what the two images are used for, but it seemed like the default one was quite old.

### vendor: update to docker v20.10.6

I believe there have been changes to filesystem mounting in Docker since v17. It could be related.

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
@tbg @rickystewart -- tagging the two of you since you seemed most active on #58955 before. do you think this PR is helpful to try out, or will it just add more noise/variables to an already flaky situation?

**Review by rickystewart — COMMENTED** [review]
No comment either way on this -- it's conceivable this could help, and I'm in favor of additional experimentation to reduce flakiness here. You might want to get a sign-off from someone who's more well-versed in the acceptance tests themselves, but otherwise I'll stamp if you get this out of the draft state.

**Review by tbg — APPROVED** [review]
It's worth a shot, thanks Rafi.

**Comment by rafiss** [comment]
tftr! let's see..

bors r=tbg

**Pull request merged**
