### PR TITLE
geo/geomfn: implement DWithin for geometry types

### LINKED ISSUE #48923: geo/geomfn: implement ST_DWithin({geometry,geometry,float8})
Implement `ST_DWithin` on arguments {geometry,geometry,float8}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_DWithin.html).

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end.
* Ensure the documentation is regenerated by calling `make buildshort`.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-05-17T19:29:36Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Moved the core of the logic for distance calculation operations to the
`geodist` package, with required methods interface-d into the package
for geometry/geography calculations. The code is mostly the same as it
was in geogfn/distance.go, just the spheroid/sphere calculations mvoed
out.

The geometry based operations are contained in geomfn/distance.go. All
math is annotated with links as well.

Changed MinDistance to use the self-made implementation. The tests still
call GEOS to make sure the return values are similar.

Needed to bring some vendored packages in from go-geom for this to work.

Resolves https://github.com/cockroachdb/cockroach/issues/48923.

Release note (sql change): Implemented DWithin for Geometry types.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PBGJE4Rc7NTPSTNHS:-M7PBGJE4Rc7NTPSTNHT:b-xyus8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df2923f471cf2b3fe23e03e06fb54c36fdd5be/docs/generated/sql/functions.md#L748)):*
> ```Markdown
> </span></td></tr>
> <tr><td><a name="st_distance"></a><code>st_distance(geometry_a: geometry, geometry_b: geometry) &rarr; <a href="float.html">float</a></code></td><td><span class="funcdesc"><p>Returns the distance between the given geometries.</p>
> <p>This function utilizes the GEOS module.</p>
> ```

not using GEOS for distance?
I was expecting we would use geos.MinDistance to implement DWithin too -- why the change?
___
*[pkg/geo/geodist/geodist.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCEZ096ZYoooiioA6:-M7PCEZ096ZYoooiioA7:bisv0wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L75)):*
> ```Go
> type DistanceUpdater interface {
> 	// Update updates the distance based on two provided points,
> 	// returning if the function should return early.
> ```

I understand that hooks are needed for distance calculation, but why for keeping track of the current distance?
And `Update()` looks like a distance calculation hook in an interface that is keeping track of the current distance.
Are we tracking what was done for the Geography code too closely? 
___
*[pkg/geo/geodist/geodist.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCsk1AP595KK2tXko:-M7PCsk1AP595KK2tXkp:byy31mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L83)):*
> ```Go
> }
> 
> // Crosser is a provided hook that has a series of functions that can help
> ```

there aren't a "series of functions". And maybe this can be renamed `EdgeCrosser`.
___
*[pkg/geo/geodist/geodist.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PD2pGCzdj6PLjoELL:-M7PD2pGCzdj6PLjoELM:b-v0d75w) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L87)):*
> ```Go
> type Crosser interface {
> 	// ChainCrosser compares the previously evaluated point and the current point
> 	// and checks whether it crosses another given line.
> ```

This comment is not very clear.
Is the EdgeCrosser handling crossing for an edge it is initialized with?
Is it crossing between that edge and the edge defined by the (p1, p2) where the calls were `ChainCrossing(p1)`, `ChainCrossing(p2)`?
Does the first call to `ChainCrossing()` always return false?
___
*[pkg/geo/geodist/geodist.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDT8c1NLhJrTkYhVs:-M7PDT8c1NLhJrTkYhVt:b9bns53) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L94)):*
> ```Go
> // the distance between two shapes.
> type DistanceCalculator interface {
> 	// DistanceUpdater returns the DistanceUpdater for the given point.
> ```

why does the calculator have an updater? Is is possible to keep the geo math separate?
What "given point"?
___
*[pkg/geo/geodist/geodist.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDg6p1okvDodF2q5y:-M7PDg6p1okvDodF2q5z:b8dwah5) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L96)):*
> ```Go
> 	// DistanceUpdater returns the DistanceUpdater for the given point.
> 	DistanceUpdater() DistanceUpdater
> 	// NewCrosser returns a new Crosser.
> ```

this needs a longer comment.
If we call `NewCrosser(e, p1)` and then ChainCrossing(p2), is it comparing e with (p1, p2)?
___
*[pkg/geo/geodist/geodist.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PE8Z057gTu7nwPoaX:-M7PE8Z057gTu7nwPoaY:bymwh5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L104)):*
> ```Go
> 	ClosestPointToEdge(edge Edge, point Point) (Point, bool)
> }
> ```

I haven't looked at the rest of this file too closely, since it seems to follow the pattern for geography, before this refactoring.
___
*[pkg/geo/geogfn/distance.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PFC6tEtxD_GJ8DDNP:-M7PFC6tEtxD_GJ8DDNQ:b-goo0ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geogfn/distance.go#L259)):*
> ```Go
> 	b := bInterface.(*s2GeodistPoint).Point
> 
> 	// Calculate the sphere distance first, as it is much cheaper.
> ```

This "Calculate the sphere distance first" seems stale -- it looks like this is meant to only be the sphere distance and that it is `Distance()` function that does the spheroid calculation.

As mentioned in an earlier comment, calculating the distance between points seems out of place in an updater interface. Also, s1.ChordAngle is a float64, so it does seem that we can have a general updater that keeps the min distance as a float64 and the final call to speroidDistance() can happen at the caller? Would that be too awkward?
___
*[pkg/geo/geomfn/distance.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PHVVX0f0ctFD_Fgag:-M7PHVVX0f0ctFD_Fgah:bp9h9rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L47)):*
> ```Go
> 
> // minDistanceInternal finds the minimum distance between two geometries.
> // This implementation is done in-house, as compared to using GEOS.
> ```

is this a speed issue? Do we have a benchmark?
Aren't we opening ourselves to more compatibility issues with PostGIS by not using GEOS.
___
*[pkg/geo/geomfn/distance.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PImkADAR0Hjv4MD11:-M7PImkADAR0Hjv4MD12:b-6dupy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L303)):*
> ```Go
> // This includes the boundary.
> // It only checks whether X _or_ Y is within the range of values covered by the edge.
> func (c *geomDistanceCalculator) inBoundingCross(
> ```

this is a semantically confusing predicate. What does it really mean in geometric terms?
___
*[pkg/geo/geomfn/distance.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PIu8U8453GdMAwozT:-M7PIu8U8453GdMAwozU:bxm2wxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L306)):*
> ```Go
> 	p geom.Coord, eV0 geom.Coord, eV1 geom.Coord,
> ) bool {
> 	return (eV0.X() <= p.X() && p.X() < eV1.X()) || (eV1.X() <= p.X() && p.X() < eV0.X()) ||
> ```

The X coordinates are considered [start, end), and same for Y?

These 4 functions in this file seem to be the new computations introduced in this PR -- I made a first pass but will take another close look.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PBGJE4Rc7NTPSTNHS:-M7QXPLA4M5oAzR1CnGP:b-phvlsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df2923f471cf2b3fe23e03e06fb54c36fdd5be/docs/generated/sql/functions.md#L748)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

not using GEOS for distance?
I was expecting we would use geos.MinDistance to implement DWithin too -- why the change?
</blockquote></details>

a) PostGIS doesn't use GEOS
b) I wanted the distance / dwithin functions to match each other
c) avoid CGO
d) GEOS gives answers that are a little off due to precision compared to doing it ourselves (and doing it ourselves matches PostGIS results more closely. one result was 0.9999996 in GEOS but 0.9999998 ourselves/in PostGIS, for example).
___
*[pkg/geo/geodist/geodist.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCEZ096ZYoooiioA6:-M7QXgmz7aKyfI1e1kcA:b-m5uat4) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I understand that hooks are needed for distance calculation, but why for keeping track of the current distance?
And `Update()` looks like a distance calculation hook in an interface that is keeping track of the current distance.
Are we tracking what was done for the Geography code too closely? 
</blockquote></details>

Well, this is really useful for doing MaxDistance as well. I'd rather keep this in, unless you had another suggestion.
___
*[pkg/geo/geodist/geodist.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCsk1AP595KK2tXko:-M7QXzs44zij6wqXlB_8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L83)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there aren't a "series of functions". And maybe this can be renamed `EdgeCrosser`.
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PD2pGCzdj6PLjoELL:-M7QYeoJ3dAO7O-MpbAB:bjfl3ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L87)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This comment is not very clear.
Is the EdgeCrosser handling crossing for an edge it is initialized with?
Is it crossing between that edge and the edge defined by the (p1, p2) where the calls were `ChainCrossing(p1)`, `ChainCrossing(p2)`?
Does the first call to `ChainCrossing()` always return false?
</blockquote></details>

Done. Clarified the comments are bit.
___
*[pkg/geo/geodist/geodist.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDT8c1NLhJrTkYhVs:-M7QYgbRAHNJURyAEgJQ:bo1xn0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L94)):*
> why does the calculator have an updater?
less interfaces to pass around...

>  Is is possible to keep the geo math separate?
How do you mean?

> What "given point"?
Clarified?
___
*[pkg/geo/geodist/geodist.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDg6p1okvDodF2q5y:-M7QZ1HVDY7D_2_Mwkhi:b-eowr3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L96)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this needs a longer comment.
If we call `NewCrosser(e, p1)` and then ChainCrossing(p2), is it comparing e with (p1, p2)?
</blockquote></details>

Clarified.
___
*[pkg/geo/geodist/geodist.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PE8Z057gTu7nwPoaX:-M7QZ2Q10eVM1BdPkzX_:b-q54fm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L104)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I haven't looked at the rest of this file too closely, since it seems to follow the pattern for geography, before this refactoring.
</blockquote></details>

Yep. Crosser is the same as s2.NewChainEdgeCrosser, if that helps
___
*[pkg/geo/geogfn/distance.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PFC6tEtxD_GJ8DDNP:-M7QZAK31sDI2O7BbuNf:b-n9s46g) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geogfn/distance.go#L259)):*
> This "Calculate the sphere distance first" seems stale -- it looks like this is meant to only be the sphere distance and that it is Distance() function that does the spheroid calculation.

yep, relic statement.

> As mentioned in an earlier comment, calculating the distance between points seems out of place in an updater interface. Also, s1.ChordAngle is a float64, so it does seem that we can have a general updater that keeps the min distance as a float64 and the final call to speroidDistance() can happen at the caller? Would that be too awkward?

can you give an example of what you want it to look like? i wanted to avoid having to pass two interfaces everywhere, and update technically does update the value by computing the distance between the two points. i can merge the updater and calculator interfaces if that makes it clearer.
___
*[pkg/geo/geomfn/distance.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PHVVX0f0ctFD_Fgag:-M7QZgAN0_PUAKLOK1nh:b9rz0gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L47)):*
> is this a speed issue? Do we have a benchmark?
we don't know (i'd rather get working code as a base), and no.

> Aren't we opening ourselves to more compatibility issues with PostGIS by not using GEOS.
see comment above.
___
*[pkg/geo/geomfn/distance.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PImkADAR0Hjv4MD11:-M7Q_KnSBNPKoWnhpN8S:b932waj) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L303)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is a semantically confusing predicate. What does it really mean in geometric terms?
</blockquote></details>

i've merged it with the place it is used to be clearer.
___
*[pkg/geo/geomfn/distance.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PIu8U8453GdMAwozT:-M7Q_koEBPi7DBHawDri:b-s3lqud) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geomfn/distance.go#L306)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The X coordinates are considered [start, end), and same for Y?

These 4 functions in this file seem to be the new computations introduced in this PR -- I made a first pass but will take another close look.
</blockquote></details>

Clarified why we do it this way.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geogfn/distance.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PFC6tEtxD_GJ8DDNP:-M7_qFDl6kuPR1sG5P9R:bobpjsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geogfn/distance.go#L259)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> This "Calculate the sphere distance first" seems stale -- it looks like this is meant to only be the sphere distance and that it is Distance() function that does the spheroid calculation.

yep, relic statement.

> As mentioned in an earlier comment, calculating the distance between points seems out of place in an updater interface. Also, s1.ChordAngle is a float64, so it does seem that we can have a general updater that keeps the min distance as a float64 and the final call to speroidDistance() can happen at the caller? Would that be too awkward?

can you give an example of what you want it to look like? i wanted to avoid having to pass two interfaces everywhere, and update technically does update the value by computing the distance between the two points. i can merge the updater and calculator interfaces if that makes it clearer.
</blockquote></details>

(tried merging the updater and calculator interfaces and it's a bit messier than desired. the spheroid calculator stuff and the max distance makes it hard to make it separate as you may want it)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geodist/geodist.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCEZ096ZYoooiioA6:-M7cLeiQ63A0eq76cqRN:b-v27jxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L75)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Well, this is really useful for doing MaxDistance as well. I'd rather keep this in, unless you had another suggestion.
</blockquote></details>

Ack -- I noticed the MaxDistance in the other PR after writing the comment.
___
*[pkg/geo/geodist/geodist.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDT8c1NLhJrTkYhVs:-M7cMI1h15DtQJcKT_9Z:b-758ajf) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L94)):*
>> why does the calculator have an updater?

> less interfaces to pass around...

That is reasonable
___
*[pkg/geo/geodist/geodist.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cLmjl4J8m2a5G1Zrs:-M7cLmjl4J8m2a5G1Zrt:bl8v0s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L83)):*
> ```Go
> }
> 
> // EdgeCrosser is a provided hook that calculates whether edges inters.
> ```

intersect.
___
*[pkg/geo/geodist/geodist.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cMjQY2KfyVsOL_xDf:-M7cMjQY2KfyVsOL_xDg:b-jghunc) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L154)):*
> ```Go
> 
> // onPointToEdgeEnds updates the distance using the edges between a point and a shape.
> // It will only check the ends of the edges, and assumes the check against .Edge(0).V0 is not required.
> ```

This is more like `onPointToEdgesExceptFirstEdgeStart(...)`

Since it doesn't only check against the ends -- it checks against the interior of the edge.
___
*[pkg/geo/geodist/geodist.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cNZWi5MBofeIiHgxS:-M7cNZWi5MBofeIiHgxT:b5z20g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L187)):*
> ```Go
> func onPointToPolygon(c DistanceCalculator, a Point, b Polygon) bool {
> 	// If the exterior ring does not cover the outer ring, we just need to calculate the distance
> 	// to the outer ring.
> ```

did you mean
If the exterior ring does not contain the point, we just need to calculate the distance to the exterior ring.
___
*[pkg/geo/geodist/geodist.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cOl_E3pA9v_sU4xu4:-M7cOl_E3pA9v_sU4xu5:b2lxu5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L269)):*
> ```Go
> 	// * If polyline A is within the given distance, we can immediately return.
> 	// * If polyline A does not intersect the hole but there is at least one point inside
> 	//   the hole, we can immediately return since all points must be inside that hole
> ```

... must be inside that hole and so the distance of this polyline to this hole is the minimum distance of this polyline to this polygon (since ...
___
*[pkg/geo/geogfn/distance.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PFC6tEtxD_GJ8DDNP:-M7cPbhM6F-PWl9DV-BQ:b-l876q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geogfn/distance.go#L259)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(tried merging the updater and calculator interfaces and it's a bit messier than desired. the spheroid calculator stuff and the max distance makes it hard to make it separate as you may want it)
</blockquote></details>

I reread and this looks fine now.
___
*[pkg/geo/geomfn/distance.go, line 339 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cZxDoBhYvMZv9v3lk:-M7cZxDoBhYvMZv9v3ll:bi3wc3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geomfn/distance.go#L339)):*
> ```Go
> 	// See also: https://en.wikipedia.org/wiki/Winding_number
> 	// See also: https://en.wikipedia.org/wiki/Nonzero-rule
> 	windingNumber := 0
> ```

The steps to go from the description in those links to the following algorithm are non-obvious.
I found http://geomalgorithms.com/a03-_inclusion.html to be useful
Any thoughts on how the two relate?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[docs/generated/sql/functions.md, line 748 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PBGJE4Rc7NTPSTNHS:-M7ci5M43nSnWVaDC8EZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65df2923f471cf2b3fe23e03e06fb54c36fdd5be/docs/generated/sql/functions.md#L748)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

a) PostGIS doesn't use GEOS
b) I wanted the distance / dwithin functions to match each other
c) avoid CGO
d) GEOS gives answers that are a little off due to precision compared to doing it ourselves (and doing it ourselves matches PostGIS results more closely. one result was 0.9999996 in GEOS but 0.9999998 ourselves/in PostGIS, for example).
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PCEZ096ZYoooiioA6:-M7ci6d1Dv4n2gNniyDn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L75)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ack -- I noticed the MaxDistance in the other PR after writing the comment.
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDT8c1NLhJrTkYhVs:-M7ci7iZ68f5ddGf_OOs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L94)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

>> why does the calculator have an updater?

> less interfaces to pass around...

That is reasonable
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PDg6p1okvDodF2q5y:-M7ci8Wv8xAtz3l6XHK_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Clarified.
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PE8Z057gTu7nwPoaX:-M7ci8ro0hNGtGGs8FHU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geodist/geodist.go#L104)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yep. Crosser is the same as s2.NewChainEdgeCrosser, if that helps
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cLmjl4J8m2a5G1Zrs:-M7ciIFa9HhHr4g93s5f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L83)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

intersect.
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 154 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cMjQY2KfyVsOL_xDf:-M7ciRat7LksLqVCCZ0t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L154)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is more like `onPointToEdgesExceptFirstEdgeStart(...)`

Since it doesn't only check against the ends -- it checks against the interior of the edge.
</blockquote></details>

Done.
___
*[pkg/geo/geodist/geodist.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cNZWi5MBofeIiHgxS:-M7ciYe75lPWF6a0vp-7:b-kbn1th) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L187)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did you mean
If the exterior ring does not contain the point, we just need to calculate the distance to the exterior ring.
</blockquote></details>

Yep. fixed.
___
*[pkg/geo/geodist/geodist.go, line 269 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cOl_E3pA9v_sU4xu4:-M7cj7tq5FCn_A5JsP1m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geodist/geodist.go#L269)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... must be inside that hole and so the distance of this polyline to this hole is the minimum distance of this polyline to this polygon (since ...
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/distance.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7PFC6tEtxD_GJ8DDNP:-M7cj8Bf4o23st2anEAy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c168ccbf77b27dd78b1b96263325f9d0dde547/pkg/geo/geogfn/distance.go#L259)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I reread and this looks fine now.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/distance.go, line 339 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-M7cZxDoBhYvMZv9v3lk:-M7ciyRz1A08qhK8qM4z:bqmjwcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/972745a99954c55c0ed2bb023bcac476b7dc319b/pkg/geo/geomfn/distance.go#L339)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The steps to go from the description in those links to the following algorithm are non-obvious.
I found http://geomalgorithms.com/a03-_inclusion.html to be useful
Any thoughts on how the two relate?
</blockquote></details>

Added!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49085#-:-M7d1W8nB7JGnPvkxPzP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
