### PR TITLE
sql: not reuse renders for arguments to window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
windowNode no longer reuses renders that are
arguments to window function for PARTITION BY/
ORDER BY clauses and IndexedVars. As a result,
rows will likely be slightly longer which
corresponds to increased memory usage. In the
long run, however, DistSQL implementation
should take over, and this change - I think -
is necessary step for that.

Related to: #27140.

Adds support for specifying a number of
initial renders not to be reused.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
The code looks good but I still don't understand why this is needed. Mind adding a sentence or two stating the rationale? Is this due to a DistSQL specific or limitation?

**Review by yuzefovich — COMMENTED** [review]
I added a more detailed description to the comment.

Thanks for your review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-:-LICPvhs94XKqmpyBZu0:b3wnhe3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — APPROVED** [review]
LGTM, but this PR does not really stand on its own -- the motivation why distsql needs this is not visible at all, and actually I'd dare say you don't know it's really necessary just yet (because you haven't done the distsql work yet)

My personal opinion is that you should keep this PR open build upon its commit in your next iteration of the work (towards distsql) and embed this commit in the PR that also proposes the distsql work.

You can then either reuse the PR (rephrase its description, request a second round of reviews) or create a new one and inform the reviewers that the first commit was reviewed here already.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-:-LID9l5g55yD4vxgx8wt:b-4wlehe)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/targets.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-LID9Jv3EfmPdVVIWeDw:-LID9Jv46SSIOGCnI2Jx:b-exig6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2ed74a66f17e572d2e1a6628612e22ee9b8846/pkg/sql/targets.go#L115)):*
> ```Go
> }
> 
> // addOrReuseRenders adds the given result columns to the select render list and
> ```

nit/tip: Move the new function `addOrReuseRenders` below just above `addOrReuseRendersStartinFromIdx` so as to simplify the diff.
___
*[pkg/sql/window.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-LID9_yE9w-dXuVTtXTJ:-LID9_yF2NejMlGnNug4:b-h7ygji) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2ed74a66f17e572d2e1a6628612e22ee9b8846/pkg/sql/window.go#L61)):*
> ```Go
> 	//
> 	// Currently, we do not want to reuse these renders because the columns these renders
> 	// refer to will not be outputted by window processors in DistSQL once
> ```

will not be output*

**Review by yuzefovich — COMMENTED** [review]
I actually have working implementation in DistSQL already, and this change is necessary for the approach I took (see https://reviewable.io/reviews/cockroachdb/cockroach/27140).

I talked to Nathan earlier today, and he suggested a different architecture which my team (and myself) liked a lot and which doesn't require these changes (so these might be reverting in the future - or the way renders are set up in `windowNode` might be refactored). However, it would require major overhaul of the code I produced so far (and the approach is more complicated), so we decided that I should go ahead and merge the current approach (currently waiting on the reviews) since it's a significant improvement over the local execution.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-:-LIDFUR980QOxfG-KXAy:b-x7eabj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27864#-LID9_yE9w-dXuVTtXTJ:-LIDFR-SALUeFCyyZpFM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b2ed74a66f17e572d2e1a6628612e22ee9b8846/pkg/sql/window.go#L61)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

will not be output*
</blockquote></details>

Done.

**Pull request merged**
