### PR TITLE
deps: upgrade cockroachdb/errors

### PR DESCRIPTION
**Pull request by knz**
This picks up all the incremental improvements without
the upgrade from raven-go to sentry-go.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47278#-:-M4UcMrxD_aDZ1MnqfAN:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

**Comment by knz** [comment]
woah there's something majorly broken in the new code. I'll need to investigate that.

**Comment by knz** [comment]
I found the bug. will fix in `errors` first then backport here

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47278#-:-M4W4tRP7zCudS6txmJr:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by knz** [comment]
I fixed the problem in https://github.com/cockroachdb/errors/pull/28

Waiting for that PR over there to get approved and merged before completing this one.

**Comment by knz** [comment]
TFYR

bors r=andreimatei

**Pull request merged**
