### PR TITLE
sql: use user transaction if we have one to prepare queries

### LINKED ISSUE #46447: sql: deadlock due to planning query for `SHOW TABLE`
When planning a query we use a different transaction. We do this, at least in part, to ensure that reads of the schema performed during planning are cacheable. See here:

https://github.com/cockroachdb/cockroach/blob/e5bb2683f2b6b81d3873193d672a3fa31444c15b/pkg/sql/conn_executor_prepare.go#L163-L172

Unfortunately, we do use this transaction for more than just a timestamp. This transaction makes its way to name resolution. An example of a problematic case is here:

https://github.com/cockroachdb/cockroach/blob/e5bb2683f2b6b81d3873193d672a3fa31444c15b/pkg/sql/delegate/show_table.go#L172

Imagine that we have Txn1 and Txn2:

```
Txn1: BEGIN;
Txn1: ALTER TABLE foo ...
Txn2: BEGIN;
Txn2: ALTER TABLE bar ...
Txn2: ALTER TABLE foo ... // blocks on Txn1
Txn1: SHOW COLUMNS FROM bar // blocks on Txn2 in planner txn
```

Had the planner been using the user's transaction then deadlock detection would have kicked in and we would have been fine. The problem here is that deadlock detection has no way to associate the planner txn with Txn1. 

The fix for the short term is likely to be to follow the pattern of #46384 and #46170 and make the transaction used here high priority. Unlike in those cases however, the result of this query is not necesarily going to be cached as a shared resource. In fact, if we do this, then there's a chance that we can introduce a live-lock scenario where concurrent `SHOW COLUMN ...` can hold off a schema change. I'm not certain that that's the worst thing. I think for now it's the right thing to do.

A better solution might be to explicitly relate the planner txn to Tx1 for deadlock detection. Perhaps something like a read-only child transaction which carries its parent in push requests. @nvanbenschoten I think you've been having thoughts in this area.

----

This is fallout from #46402.

### PR DESCRIPTION
**Pull request by ajwerner**
Prepartion of certain queries requires performing reads against the database.
If the user has already laid down intents, these reads may become part of a
dependency cycle. Prior to this commit, these reads would be on a different
transaction and thus this cycle would not be detected by our deadlock detection
mechanism.

This change opts to use the user's transaction for planning if there is one
and thus will properly interact with deadlock detection.

Fixes #46447.

Release justification: fixes for high-priority or high-severity bugs in
existing functionality

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
hold off on looking at this, the testing is busted.

**Comment by ajwerner** [comment]
Alright, fixed the tests, RFAL.

**Review by petermattis — COMMENTED** [review]
@ajwerner Is this something that can be and should be backported to 19.2? The `schemachange` workload can reproduce wedging on both 19.1 and 19.2. I'm presuming it is this same deadlock.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-:-M3M8OGL4xOkxCrnTAjK:bwxhucn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by ajwerner** [comment]
Yes this and the two other high priority txn usage fixes should all be backported to 19.2 and probably 19.1. Will do that after this goes in. 

There’s still one more PR inbound to deal with a different sort of deadlock uncovered by the test.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/sql/conn_executor_prepare.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NAonQB5qN1eHEEYXP:-M3NAonQB5qN1eHEEYXQ:b11t94e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_prepare.go#L184)):*
> ```Go
> 	flags, err := ex.populatePrepared(ctx, txn, placeholderHints, p)
> 	if err != nil {
> 		// NB: if this is not a new transaction then we should let the connExecutor
> ```

what do you mean "we should"? Do we or don't we?
I see that we do, except not very well. The code below doesn't handle retriable errors:
https://github.com/cockroachdb/cockroach/blob/e7afadb5cea431491f9a7ffe5455a5a6339f868f/pkg/sql/conn_executor_prepare.go#L35
___
*[pkg/sql/conn_executor_test.go, line 599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NCT0P-yMrWvptfJC3:-M3NCT0P-yMrWvptfJC4:b-5vz9l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L599)):*
> ```Go
> 	case <-time.After(time.Millisecond):
> 	case <-errCh:
> 		t.Fatal("expected the transaction to block")
> ```

put the error in the message
___
*[pkg/sql/conn_executor_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NC3t-3B5JaKXSK9M1:-M3NC3t-3B5JaKXSK9M2:b1c2y87) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L654)):*
> ```Go
> 	// This test will create an explicit transaction that encounters an error on
> 	// a latter statement during planning of SHOW COLUMNS. The planning for this
> 	// SHOW COLUMNS	will be run in the user's transaction. The test will inject
> ```

nit: spaces
___
*[pkg/sql/conn_executor_test.go, line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NDReT8-bnwWdcL4jX:-M3NDReT8-bnwWdcL4jY:bdrdwf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L690)):*
> ```Go
> 	_, err = tx.Prepare("SELECT NULL FROM [SHOW COLUMNS FROM bar] LIMIT 1")
> 	require.Regexp(t,
> 		"restart transaction: TransactionRetryWithProtoRefreshError: boom", err)
> ```

As I was saying above, I suspect this is currently broken since we're not actually returning the retriable code here. If you switch the code to pgx, you can assert on the error code.
In fact, I think that if things were to function correctly, this prepare should be auto-retried (endlessly, I guess, given your filter).

**Review by ajwerner — COMMENTED** [review]
@andreimatei thanks for the review, it's ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-:-M3SY9pMDZrDOXy-ekbi:b1hbvu0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor_prepare.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NAonQB5qN1eHEEYXP:-M3NtypT-iszsLvUU8Ts:byq5z5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_prepare.go#L184)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what do you mean "we should"? Do we or don't we?
I see that we do, except not very well. The code below doesn't handle retriable errors:
https://github.com/cockroachdb/cockroach/blob/e7afadb5cea431491f9a7ffe5455a5a6339f868f/pkg/sql/conn_executor_prepare.go#L35

</blockquote></details>

yeah makes sense. Fixed.
___
*[pkg/sql/conn_executor_test.go, line 599 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NCT0P-yMrWvptfJC3:-M3SXgKh5Q-bVT-7ohBp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L599)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put the error in the message
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_test.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NC3t-3B5JaKXSK9M1:-M3SXmhJ4ZgirSTdKz4k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L654)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: spaces
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_test.go, line 690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-M3NDReT8-bnwWdcL4jX:-M3NtrBA6TZBdJEBwGDi:bbsc0zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e718c4ad2679217c84e6fff84c900f57e1721095/pkg/sql/conn_executor_test.go#L690)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

As I was saying above, I suspect this is currently broken since we're not actually returning the retriable code here. If you switch the code to pgx, you can assert on the error code.
In fact, I think that if things were to function correctly, this prepare should be auto-retried (endlessly, I guess, given your filter).
</blockquote></details>

We got back a response from inserting a row, I don't think it should auto-retry (and it doesn't).

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46588#-:-M3lBaKzDMNaBZETFH9D:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by ajwerner** [comment]
TFTR!

bors r=andreimatei

**Pull request merged**
