### PR TITLE
workload: introduce Ledger workload

### PR DESCRIPTION
**Pull request by nvb**
This change introduces a new workload called Ledger. Ledger simulates
an accounting system using double-entry bookkeeping. It is made up of
a simple schema containing 4 tables:
- `customer`
- `transaction`
- `entry`
- `session`

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/workload/ledger/balance.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErL-mQ7yOo3Vn0wYDf:-LErL-mQ7yOo3Vn0wYDg:bunbsa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/balance.go#L31)):*
> ```Go
> var _ ledgerTx = balance{}
> 
> func (bal balance) run(config *ledger, db *gosql.DB) (interface{}, error) {
> ```

these are all spread out in different files in tpcc as an artifact of trying to make the review diffs smaller when it got moved in. i don't particularly find that it helps readability, but ymmv

---

*[pkg/workload/ledger/ledger.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErKgkTCKCNacmRqs2E:-LErKgkU7avo9sOYo58s:b-sxxu9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/ledger.go#L56)):*
> ```Go
> 	Name:        `ledger`,
> 	Description: `Ledger simulates an accounting system using double-entry bookkeeping`,
> 	Version:     `2.1.0`,
> ```

nit: no reason not to start at 1.0.0

---

*[pkg/workload/ledger/random.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErLm9A6ImAZmF_V1pP:-LErLm9A6ImAZmF_V1pQ:b-m27nif) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/random.go#L31)):*
> ```Go
> 
> func init() {
> 	rand.Seed(timeutil.Now().UnixNano())
> ```

is this needed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26673)*

**Review by nvb — COMMENTED** [review]
Updated. @justinj mind giving this a quick look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-:-LL6-qosE1Dmb0b-t5Nt:b-fbchap)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ledger/balance.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErL-mQ7yOo3Vn0wYDf:-LL6-WpK7hnePrvNJp9h:b-6ar99c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/balance.go#L31)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

these are all spread out in different files in tpcc as an artifact of trying to make the review diffs smaller when it got moved in. i don't particularly find that it helps readability, but ymmv
</blockquote></details>

Eh, I don't think it's worth changing now. I don't think it hurts readability either.
___
*[pkg/workload/ledger/ledger.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErKgkTCKCNacmRqs2E:-LL6-cX2-NP0_dvEcHPt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/ledger.go#L56)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: no reason not to start at 1.0.0
</blockquote></details>

Done.
___
*[pkg/workload/ledger/random.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26673#-LErLm9A6ImAZmF_V1pP:-LL6-iKt3v31JAeZ2qCM:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec76201b4c70b57a52c13a7087dead951bf8f698/pkg/workload/ledger/random.go#L31)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

Removed.

**Comment by justinj** [comment]
🔬 🐶 lgtm!

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
