### PR TITLE
kv: consolidate range lease construction

### PR DESCRIPTION
**Pull request by nvb**
This commit consolidates the creation of lease objects into one place, a new `kv/kvserver/leases` package. This avoids the diffuse construction of leases that was previously spread between `replica_range_lease.go`, `cmd_lease_request.go`, `cmd_lease_transfer.go`, and `cmd_lease.go`.

This makes the logic easier to understand and easier to test. It will also make the logic easier to adjust when we add support for leader leases.

First part of #123498. The next PR will consolidate lease validation logic (before latches, after latches, before proposing) into one place.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
loving this refactor -- it is bringing some sanity to this code!

Minor comments only. And I haven't looked at the test yet.

> Reviewed 4 of 4 files at r1, 12 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-:-Nzd9eZF1XpkxT77G0th:b-zd5bvc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd7WcZ4Dmd31eLKobj:-Nzd7WcZ4Dmd31eLKobk:b-mlm902) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/replica_range_lease.go#L469)):*
> ```Go
> 		// However, we only do so in the event that the next leaseholder is
> 		// considered live at this time. If not, there's no sense in
> 		// incrementing the expired leaseholder's epoch.
> ```

I've never understood why this code is correct, in that can't we be fallible in determining whether the node is dead, in which case we may not increment the epoch and the node is actually alive?
Can you add some code commentary here.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd9wLG4NHiV_1ZhW3z:-Nzd9wLG4NHiV_1ZhW4-:blm7rqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/replica_range_lease.go#L484)):*
> ```Go
> 			// considered dead but revived without having its epoch
> 			// incremented, i.e. that it was in fact live at
> 			// status.Timestamp.
> ```

nit: the reference to status is stale.
___
*[`pkg/kv/kvserver/batcheval/cmd_lease.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzcZKe-2pWrz5LinKeT:-NzcZKe06SWgajxBidhz:b-ylsi2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a99ae2b887cf6b64e801b93e8c13ddfb9b6f1a4/pkg/kv/kvserver/batcheval/cmd_lease.go#L79)):*
> ```Go
> 
> 	// Verify that requesting replica is part of the current replica set.
> 	desc := rec.Desc()
> ```

I can't quite relate this removal to the commit message "This change avoids the need for a separate call to GetReplicaDescriptor(StoreID) in evalNewLease, which validates the same thing.".

Is there something missing at the end of that statement, such as "validates the same thing as CheckCanReceiveLease which has already been done in both the code paths TransferLease and RequestLease that call here".
___
*[`pkg/kv/kvserver/leases/build.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzceN0s1J9gLZ_hm0Q8:-NzceN0s1J9gLZ_hm0Q9:b-no35vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L40)):*
> ```Go
> // NodeLivenessManipulation contains a set of instructions for manipulating node
> // liveness records during the lease acquisition process. These actions must be
> // taken before the next lease can be requested.
> ```

Does this map directly to a `LivenessUpdate` struct. Some code comment on what `Heartbeat` and `Increment` represent would be helpful and when they can be nil. If both are non-nil, is `Increment.Epoch` required to be `Hearbeat.Epoch+1`? Any other invariants?

Hmm, maybe this encompasses the Heartbeating we must do in the case of promoting from expiration to epoch, and when extending an expired epoch-based lease.

----
Edit: I see now that these are unrelated, and at most one can be non-nil. Still worth spelling this out in a code comment.
___
*[`pkg/kv/kvserver/leases/build.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzciH0L-dym7JaCjcPa:-NzciH0L-dym7JaCjcPb:b-8rukb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L44)):*
> ```Go
> 	Heartbeat *livenesspb.Liveness
> 	Increment *livenesspb.Liveness
> }
> ```

Should there be other output instructions like calling `RevokeLease`?
___
*[`pkg/kv/kvserver/leases/build.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcgfi81CUHvB_7mPXZ:-Nzcgfi81CUHvB_7mPX_:bq9utrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L55)):*
> ```Go
> 	// Information about the previous lease.
> 	PrevLease             roachpb.Lease
> 	PrevLeaseNodeLiveness livenesspb.Liveness
> ```

is `PrevLeaseNodeLiveness` populated iff `PrevLease` is an epoch-based lease.

Also, if `PrevLeaseExpired` does it imply that `Now` is greater than `PrevLease.Expiration` for an expiration-based lease, or greater than `PrevLeaseNodeLiveness.Expiration` for an epoch-based lease.

Some code comments regarding such invariants would be helpful. And how about some more invariant checking in this package for the newly documented invariants, since the cost is immaterial given the relative rarity of new leases.
___
*[`pkg/kv/kvserver/leases/build.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzcgCoL4xWjX4q9SCAj:-NzcgCoL4xWjX4q9SCAk:bld05tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L94)):*
> ```Go
> 		// If this is a non-cooperative lease change (i.e. an acquisition), it
> 		// is up to us to ensure that Lease.Start is greater than the end time
> 		// of the previous lease. This means that if status refers to an expired
> ```

nit: there is no LeaseStatus here, so consider changing the reference to "status" in this long comment.
___
*[`pkg/kv/kvserver/leases/build.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcianp1UY4UvRQ756d:-Nzcianp1UY4UvRQ756e:b-myoe8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L123)):*
> ```Go
> 	NextLease                roachpb.Lease
> 	NodeLivenessManipulation NodeLivenessManipulation
> }
> ```

Is this structured as output instructions since some of this needs to happen after latching?
Looking at `pendingLeaseRequest.requestLease`, the NodeLivenessManipulation seems to happen there, and that looks to be before latching. But it is in an async task, so perhaps that is why it is not being done in the leases package itself?
___
*[`pkg/kv/kvserver/leases/build.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzclevN1afCZJwFrgBp:-NzclevN1afCZJwFrgBq:b-v2vbi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L213)):*
> ```Go
> }
> 
> func leaseReplica(i Input) roachpb.ReplicaDescriptor {
> ```

nit: why are some of these funcs with a `Input` parameter instead of private methods on `Input`?
___
*[`pkg/kv/kvserver/leases/build.go` line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcm6mEClgtz7xXb_UE:-Nzcm6mEClgtz7xXb_UF:bulbuep) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L225)):*
> ```Go
> 		// For lease transfers, we initially set the lease start time to now.
> 		// However, this will be adjusted during request evaluation to a clock
> 		// reading captured after the previous lease has been revoked (RevokeLease).
> ```

If we added an output instruction `RevokeLeaseAndCaptureClockForStart` or something, this would be harder to forget.
___
*[`pkg/kv/kvserver/leases/build.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzczGBtAHxv1AnxFRKF:-NzczGBtAHxv1AnxFRKG:b-k7r0ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L234)):*
> ```Go
> 		// If the lease holder promised to not propose any commands below
> 		// MinProposedTS, it must also not be allowed to extend a lease before that
> 		// timestamp. We make sure that when a node restarts, its earlier in-flight
> ```

I realize this comment is lifted from cmd_lease_request.go, but I am wondering whether the "We make sure ..." part should be extended to talk about the other cases where `MinLeaseProposedTS` is bumped up, like `RevokeLease` or range splits.
___
*[`pkg/kv/kvserver/leases/build.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd-Dnx1QQ2fjmFMPk3:-Nzd-Dnx1QQ2fjmFMPk4:bpdx8cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L270)):*
> ```Go
> 	}
> 	exp := i.Now.ToTimestamp().Add(int64(st.RangeLeaseDuration), 0)
> 	exp.Forward(i.PrevLease.GetExpiration())
> ```

in cmd_lease_request.go we are only doing this for the `isExtension` case. Is this necessary to do for other cases? Presumably it is harmless for a transfer. And if this is an acquisition that is not an extension, the previous one would have expired so this would be a noop.
___
*[`pkg/kv/kvserver/leases/build.go` line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd0jQO5sfA3epMLrZV:-Nzd0jQP9k_VX_RnYJbk:b-i8281w) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L276)):*
> ```Go
> func leaseEpoch(
> 	nl NodeLiveness, i Input, nextType roachpb.LeaseType,
> ) (int64, *livenesspb.Liveness, error) {
> ```

nit: could this be (livenesspb.Liveness, error) such that the proto is populated if err is nil.
The epoch is contained in the liveness proto, so odd to return both.
___
*[`pkg/kv/kvserver/leases/build.go` line 298 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd1bs20QqF6tmdiIBF:-Nzd1bs20QqF6tmdiIBG:bju5jrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L298)):*
> ```Go
> }
> 
> func leaseSequence(st Settings, i Input, nextLease roachpb.Lease) roachpb.LeaseSequence {
> ```

I am super glad that the sequence assignment has been lifted into here, instead of buried in the last stage in `evalNewLease`.
___
*[`pkg/kv/kvserver/leases/build.go` line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd44BCB_EskqvaF8y_:-Nzd44BCB_EskqvaF8ya:bk9e6i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L351)):*
> ```Go
> 			// If not owner, increment previous leaseholder's epoch to invalidate its
> 			// lease and prevent it from ever becoming valid again.
> 			return NodeLivenessManipulation{Increment: &prevLeaseNodeLiveness}
> ```

Can you add a code comment that the reason we don't need to grab a timestamp after the increment and use that as the lease start is that this Increment field is used a pre-condition in the conditional put, so if this increment succeeds we know that the liveness was not extended.
___
*[`pkg/kv/kvserver/leases/build.go` line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd3vs9-LMKM6UoOiII:-Nzd3vs9-LMKM6UoOiIJ:bryhf7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L389)):*
> ```Go
> 		// If this is not an extension nor a transfer, the next lease's start time
> 		// cannot overlap with the previous lease interval (prevLease.expiration >
> 		// nextLease.start is NOT ok).
> ```

This is a noop when prevLease is an epoch-based lease, yes?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-:-O-7vugJBYY7fasynhIT:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd7WcZ4Dmd31eLKobj:-O-76tGq3ALzUI0yR_6x:bkafk91) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/replica_range_lease.go#L469)):*
> in that can't we be fallible in determining whether the node is dead, in which case we may not increment the epoch and the node is actually alive?

Yes, that's correct. In that case, the `IncrementEpoch` will fail (`ErrEpochCondFailed`) and will will return an error below. The error handling is subtle, which may be what's tripping you up.

I updated the comment to reference the various error cases.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd9wLG4NHiV_1ZhW3z:-O-7856z3F5m493xqw-U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/replica_range_lease.go#L484)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: the reference to status is stale.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/batcheval/cmd_lease.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzcZKe-2pWrz5LinKeT:-O-76X-_9p6zezJWg1ri:b-1o23au) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a99ae2b887cf6b64e801b93e8c13ddfb9b6f1a4/pkg/kv/kvserver/batcheval/cmd_lease.go#L79)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I can't quite relate this removal to the commit message "This change avoids the need for a separate call to GetReplicaDescriptor(StoreID) in evalNewLease, which validates the same thing.".

Is there something missing at the end of that statement, such as "validates the same thing as CheckCanReceiveLease which has already been done in both the code paths TransferLease and RequestLease that call here".
</blockquote></details>

Updated the commit message to call out that CheckCanReceiveLease is called in both the code paths that call `evalNewLease` (TransferLease and RequestLease).
___
*[`pkg/kv/kvserver/leases/build.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzceN0s1J9gLZ_hm0Q8:-O-78o4W8YQCrC6LvJMP:biol9ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L40)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Does this map directly to a `LivenessUpdate` struct. Some code comment on what `Heartbeat` and `Increment` represent would be helpful and when they can be nil. If both are non-nil, is `Increment.Epoch` required to be `Hearbeat.Epoch+1`? Any other invariants?

Hmm, maybe this encompasses the Heartbeating we must do in the case of promoting from expiration to epoch, and when extending an expired epoch-based lease.

----
Edit: I see now that these are unrelated, and at most one can be non-nil. Still worth spelling this out in a code comment.
</blockquote></details>

Added commentary around each of these fields.
___
*[`pkg/kv/kvserver/leases/build.go` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzciH0L-dym7JaCjcPa:-O-78yKc8qrn5maJPcDh:bvkfufr) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L44)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should there be other output instructions like calling `RevokeLease`?
</blockquote></details>

There could be, but we won't use that instruction right away because we need to wait until after we acquire latches and control flow splits between RequestLease and TransferLease to revoke the lease.
___
*[`pkg/kv/kvserver/leases/build.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcgfi81CUHvB_7mPXZ:-O-79PzI8wQd6nRKxLXw:bxjqpbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L55)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is `PrevLeaseNodeLiveness` populated iff `PrevLease` is an epoch-based lease.

Also, if `PrevLeaseExpired` does it imply that `Now` is greater than `PrevLease.Expiration` for an expiration-based lease, or greater than `PrevLeaseNodeLiveness.Expiration` for an epoch-based lease.

Some code comments regarding such invariants would be helpful. And how about some more invariant checking in this package for the newly documented invariants, since the cost is immaterial given the relative rarity of new leases.
</blockquote></details>

Yes and yes. Added commentary and new validation. This required some test churn to get the stricter validation passing.
___
*[`pkg/kv/kvserver/leases/build.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzcgCoL4xWjX4q9SCAj:-O-7IOBq54P3Ait5JIr0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L94)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: there is no LeaseStatus here, so consider changing the reference to "status" in this long comment.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/build.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcianp1UY4UvRQ756d:-O-7IVYh2az5q8xUcuuK:byj313x) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L123)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this structured as output instructions since some of this needs to happen after latching?
Looking at `pendingLeaseRequest.requestLease`, the NodeLivenessManipulation seems to happen there, and that looks to be before latching. But it is in an async task, so perhaps that is why it is not being done in the leases package itself?
</blockquote></details>

Right, the `NodeLivenessManipulation` is done before latching but in an async task that does not hold the replica mutex.
___
*[`pkg/kv/kvserver/leases/build.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzclevN1afCZJwFrgBp:-O-7Inap6LLvSpwm71dH:b-8ofayh) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L213)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: why are some of these funcs with a `Input` parameter instead of private methods on `Input`?
</blockquote></details>

A free function with an `Input` parameter just like the right relationship to me. These aren't attributes of an Input. They're closer to pure functions that use an `Input` to compute a part of the next Lease. I don't feel strongly.
___
*[`pkg/kv/kvserver/leases/build.go` line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcm6mEClgtz7xXb_UE:-O-7Ji15B99SEsT1RChF:b-a7yfc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L225)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If we added an output instruction `RevokeLeaseAndCaptureClockForStart` or something, this would be harder to forget.
</blockquote></details>

I'm curious if you think this flag would be worthwhile to add for documentation purposes even if we don't directly use it.
___
*[`pkg/kv/kvserver/leases/build.go` line 234 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzczGBtAHxv1AnxFRKF:-O-7jksd3LzEQ35nneFx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L234)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I realize this comment is lifted from cmd_lease_request.go, but I am wondering whether the "We make sure ..." part should be extended to talk about the other cases where `MinLeaseProposedTS` is bumped up, like `RevokeLease` or range splits.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/build.go` line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd-Dnx1QQ2fjmFMPk3:-O-7jwYIDnr6ba_YnRks:b-s9a0m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L270)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

in cmd_lease_request.go we are only doing this for the `isExtension` case. Is this necessary to do for other cases? Presumably it is harmless for a transfer. And if this is an acquisition that is not an extension, the previous one would have expired so this would be a noop.
</blockquote></details>

Right, this is harmless for the other cases. We could scope this logic to just extensions like the previous code was doing, but doing so is not necessary.
___
*[`pkg/kv/kvserver/leases/build.go` line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd0jQO5sfA3epMLrZV:-O-7kvGy3pMXcfegPjLu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L276)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: could this be (livenesspb.Liveness, error) such that the proto is populated if err is nil.
The epoch is contained in the liveness proto, so odd to return both.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/build.go` line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd44BCB_EskqvaF8y_:-O-7tWUq-k9lx2pQk4Y1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L351)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment that the reason we don't need to grab a timestamp after the increment and use that as the lease start is that this Increment field is used a pre-condition in the conditional put, so if this increment succeeds we know that the liveness was not extended.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/leases/build.go` line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzd3vs9-LMKM6UoOiII:-O-7trdc9-jMvNybfgIY:bowqzyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L389)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is a noop when prevLease is an epoch-based lease, yes?
</blockquote></details>

Yes, that's correct. I updated this to make the validation work even for epoch-based leases.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 18 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-:-O-DMUrS797eNTGCyXHI:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 474 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DC-KC8mtWjB808XEc:-O-DC-KC8mtWjB808XEd:b-h1yzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_range_lease.go#L474)):*
> ```Go
> 				return errors.NewAssertionErrorWithWrappedErrf(liveness.ErrRecordCacheMiss, "after heartbeat")
> 			}
> 			if l.Expiration.ToTimestamp().Less(nl.HeartbeatMinExpiration) {
> ```

We didn't do this before, and just created an `errors.AssertionFailedf`, yes? Just curious if some testing uncovered this case.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DCWL570GNT8hMpfIQ:-O-DCWL570GNT8hMpfIR:bde4k5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_range_lease.go#L477)):*
> ```Go
> 				log.Infof(ctx, "expiration of liveness record %s is not greater than "+
> 					"expiration of the previous lease after liveness heartbeat, retrying...", l)
> 				curLiveness = l.Liveness
> ```

If I am reading correctly we don't retry on an error, and we only retry for this race condition. That race cannot be repeated since the racing heartbeat will have started after this loop began, so it will bump up the expiration sufficiently. Is that correct? If yes, why should we do an exponential backoff before retrying -- shouldn't we just retry immediately, and count the retries and return an assertion failure if we need to retry more than once?
___
*[`pkg/kv/kvserver/leases/build.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-NzclevN1afCZJwFrgBp:-O-DEjsz7b3O_ljCbxaL:bt6hb6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L213)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A free function with an `Input` parameter just like the right relationship to me. These aren't attributes of an Input. They're closer to pure functions that use an `Input` to compute a part of the next Lease. I don't feel strongly.
</blockquote></details>

I don't feel strongly either.
___
*[`pkg/kv/kvserver/leases/build.go` line 225 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-Nzcm6mEClgtz7xXb_UE:-O-DErTiBEhFUbQTA8tj:bl2by5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/084d5252f68002521eb37b483ee8f7d5ef575576/pkg/kv/kvserver/leases/build.go#L225)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm curious if you think this flag would be worthwhile to add for documentation purposes even if we don't directly use it.
</blockquote></details>

If that extra field can't be plumbed through to after latch acquisition, it doesn't seem beneficial. I don't have a strong opinion.
___
*[`pkg/kv/kvserver/replica_test.go` line 1239 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DFkaZCTsNV_nJTzS2:-O-DFkaZCTsNV_nJTzS3:b-o3ywkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_test.go#L1239)):*
> ```Go
> 		{storeID: tc.store.StoreID(),
> 			start: now.Add(16, 0), expiration: now.Add(25, 0)},
> 		// The other store tries again, this time without the overlap.
> ```

Is this "tries again" stale, given the first try has been removed?
Is this removal causing some loss of test coverage?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124682)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 474 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DC-KC8mtWjB808XEc:-O-MpDVr5y8ePTaJoBqh:b1wnsw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_range_lease.go#L474)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We didn't do this before, and just created an `errors.AssertionFailedf`, yes? Just curious if some testing uncovered this case.
</blockquote></details>

This change came from https://github.com/cockroachdb/cockroach/pull/124885, which addressed some test failures that are referenced on the PR.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DCWL570GNT8hMpfIQ:-O-MpJ7E1q2TwKRgC_N6:b-vdscr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_range_lease.go#L477)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If I am reading correctly we don't retry on an error, and we only retry for this race condition. That race cannot be repeated since the racing heartbeat will have started after this loop began, so it will bump up the expiration sufficiently. Is that correct? If yes, why should we do an exponential backoff before retrying -- shouldn't we just retry immediately, and count the retries and return an assertion failure if we need to retry more than once?
</blockquote></details>

You're right on both accounts. We shouldn't need the exponential backoff, we should just retry immediately. We also should be able to assume that the second attempt succeeds. I'll make those changes in a different PR.

I'm also hoping to remove all of this soon and replace it with https://github.com/cockroachdb/cockroach/issues/125235.
___
*[`pkg/kv/kvserver/replica_test.go` line 1239 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124682#-O-DFkaZCTsNV_nJTzS2:-O-Mq_wN0bUSWR6PZCw7:b-4m4vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9a15bedf4bb701fc89ab81d6dbb205038b9c4f/pkg/kv/kvserver/replica_test.go#L1239)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this "tries again" stale, given the first try has been removed?
Is this removal causing some loss of test coverage?
</blockquote></details>

Good catch on the comment, it was stale. Updated.

The removal is not losing test coverage, as this coverage has been moved to the `pkg/kv/kvserver/leases`. Specifically, the two interactions that are being tested here are that 1) a lease extension never shortens the expiration, and 2) that an acquisition will never overlap with the previous lease.

These two interactions are now tested by `TestBuild/extension/extend_expiration,_avoid_shortening` and `TestInputValidation/acquisition_before_expiration`+`TestInputValidation/previous_lease_expired_incorrect,_computed_false`, respectively. We also have a layer of validation for the second point in `validateStart`.

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Comment by nvanbenschoten** [comment]
bors r-

I want to make sure that this isn't changing the behavior of self-directed lease transfers before merging.

**Pull request merged**
