### PR TITLE
sql: removed redundant error stored in plan nodes

### PR DESCRIPTION
**Pull request by vivekmenezes**
Also removed done boolean from editNodeRun

the error boolean is still in group.go and subquery.go . I'll see what I can do with those later.
#6921

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6934)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice, :lgtm: 

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> #### sql: removed redundant error stored in plan nodes
> 
> Also removed done boolean from editNodeRun
> 
> 
> 
> the error boolean is still in group.go and subquery.go . I'll see what I can do with those later.
> 
> 
> 
> 
> 
> 
</details>


---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/scan.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934#-KIip46qWVKjtO4UZGsP:-KIip46qWVKjtO4UZGsQ:1506842992) ([raw file](https://github.com/cockroachdb/cockroach/blob/addaa4b58e9746f64b75ca8ca086335bfb40e987/sql/scan.go#L130)):*
> ```Go
> 
> // initScan sets up the rowFetcher and starts a scan.
> func (n *scanNode) initScan() (err error) {
> ```

no need for `err` here, I'm guessing it's leftover

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934#-:-KIipPRIXBLHRshVBPh4:-1773020066)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/scan.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934#-KIip46qWVKjtO4UZGsP:-KIjgEn5_95uQ659uCyD:-627608149) ([raw file](https://github.com/cockroachdb/cockroach/blob/addaa4b58e9746f64b75ca8ca086335bfb40e987/sql/scan.go#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> no need for `err` here, I'm guessing it's leftover
</details>
I don't quite follow your comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934)*

**Comment by RaduBerinde** [comment]
*[sql/scan.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934#-KIip46qWVKjtO4UZGsP:-KIjr5fXHlGkwGnzD8iW:-1051998139) ([raw file](https://github.com/cockroachdb/cockroach/blob/addaa4b58e9746f64b75ca8ca086335bfb40e987/sql/scan.go#L130)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I don't quite follow your comment
</details>
Why `(err error)` when all functions like this just return `error`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/scan.go, line 130 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934#-KIip46qWVKjtO4UZGsP:-KIk2ehTgOWbjhxTRaAb:1604392292) ([raw file](https://github.com/cockroachdb/cockroach/blob/addaa4b58e9746f64b75ca8ca086335bfb40e987/sql/scan.go#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Why `(err error)` when all functions like this just return `error`?
</details>
gotcha. Putting it in the newest PR and merging. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6934)*

**Pull request merged**
