### PR TITLE
colexec,colflow: catch expected errors from Init at the root

### LINKED ISSUE #55077: sql: v20.1.6: uncaught expected error in the vectorized engine
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1925129034/?referrer=webhooks_plugin

Panic message:

>conn_executor.go:477: panic while executing 1 statements: SELECT _._ AS _, CASE WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ ELSE _ END AS _, CASE WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ ELSE _ END AS _, CASE WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ WHEN (_._ IS NOT _) AND (_._ != _) THEN _._ ELSE _ END AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $1) LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $2) LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $1) LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $2) LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $1) LEFT JOIN _ AS _ ON (_._ = _._) AND (_._ = $2) JOIN _ AS _ ON _._ = _._ JOIN _ AS _ ON _._ = _._ WHERE _._ = $3 LIMIT _: caused by <redacted>

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor.go#L476-L478 in pkg/sql.(*Server).ServeConn.func1
/usr/local/go/src/runtime/panic.go#L678-L680 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/flowinfra/flow.go#L401-L403 in pkg/sql/flowinfra.(*FlowBase).Wait
/usr/local/go/src/runtime/panic.go#L678-L680 in runtime.gopanic
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/execerror/error.go#L191-L193 in pkg/sql/colexec/execerror.VectorizedInternalPanic
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/allocator.go#L92-L94 in pkg/sql/colexec.(*Allocator).NewMemBatchWithSize
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/allocator.go#L84-L86 in pkg/sql/colexec.(*Allocator).NewMemBatch
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/columnarizer.go#L90-L92 in pkg/sql/colexec.(*Columnarizer).Init
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/mergejoiner.go#L439-L441 in pkg/sql/colexec.(*mergeJoinBase).initWithOutputBatchSize
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/mergejoiner.go#L430-L432 in pkg/sql/colexec.(*mergeJoinBase).Init
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/mergejoiner.go#L439-L441 in pkg/sql/colexec.(*mergeJoinBase).initWithOutputBatchSize
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/mergejoiner.go#L430-L432 in pkg/sql/colexec.(*mergeJoinBase).Init
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/materializer.go#L138-L140 in pkg/sql/colexec.(*Materializer).Start
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/rowexec/noop.go#L61-L63 in pkg/sql/rowexec.(*noopProcessor).Start
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/columnarizer.go#L96-L98 in pkg/sql/colexec.(*Columnarizer).Init
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/colexec/materializer.go#L138-L140 in pkg/sql/colexec.(*Materializer).Start
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/execinfra/processorsbase.go#L747-L749 in pkg/sql/execinfra.(*ProcessorBase).Run
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/flowinfra/flow.go#L369-L371 in pkg/sql/flowinfra.(*FlowBase).Run
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/distsql_running.go#L404-L406 in pkg/sql.(*DistSQLPlanner).Run
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/distsql_running.go#L1018-L1020 in pkg/sql.(*DistSQLPlanner).PlanAndRun
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor_exec.go#L938-L940 in pkg/sql.(*connExecutor).execWithDistSQLEngine
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor_exec.go#L831-L833 in pkg/sql.(*connExecutor).dispatchToExecutionEngine
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor_exec.go#L536-L538 in pkg/sql.(*connExecutor).execStmtInOpenState
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor_exec.go#L95-L97 in pkg/sql.(*connExecutor).execStmt
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor_exec.go#L151-L153 in pkg/sql.(*connExecutor).execPortal
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor.go#L1460-L1462 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor.go#L1334-L1336 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/conn_executor.go#L478-L480 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/be8c0a720e98a147263424cc13fc9bfc75f46013/pkg/sql/pgwire/conn.go#L581-L583 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 477
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 679
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Wait at line 402
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 679
pkg/sql/colexec/execerror/error.go in pkg/sql/colexec/execerror.VectorizedInternalPanic at line 192
pkg/sql/colexec/allocator.go in pkg/sql/colexec.(*Allocator).NewMemBatchWithSize at line 93
pkg/sql/colexec/allocator.go in pkg/sql/colexec.(*Allocator).NewMemBatch at line 85
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 91
pkg/sql/colexec/mergejoiner.go in pkg/sql/colexec.(*mergeJoinBase).initWithOutputBatchSize at line 440
pkg/sql/colexec/mergejoiner.go in pkg/sql/colexec.(*mergeJoinBase).Init at line 431
pkg/sql/colexec/mergejoiner.go in pkg/sql/colexec.(*mergeJoinBase).initWithOutputBatchSize at line 440
pkg/sql/colexec/mergejoiner.go in pkg/sql/colexec.(*mergeJoinBase).Init at line 431
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Start at line 139
pkg/sql/rowexec/noop.go in pkg/sql/rowexec.(*noopProcessor).Start at line 62
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 97
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Start at line 139
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBase).Run at line 748
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 370
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 405
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1019
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 939
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 832
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 537
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 96
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 152
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1461
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1335
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 479
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 582
```

| Tag | Value |
|---|---|
| Cockroach Release | `v20.1.6` |
| Cockroach SHA: | be8c0a720e98a147263424cc13fc9bfc75f46013 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v20.1.6 |
| Command | server |
| Go Version | `go1.13.9`|
| # of CPUs |4 |
| # of Goroutines |3145 |

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec,roachtest: inject panics into the vectorized flow in sqlsmith**

This commit adds a utility operator that randomly injects panics in
`Init` and `Next` methods of other operators with the goal of making
sure that we have the catchers (of our "panic-catcher" mechanism of
error propagation) in all necessary places. Those panic injectors are
planned when newly added session variable
`testing_vectorize_inject_panics` is set to `true` (which we now do for
`sqlsmith` roachtest).

Release note: None

**colexec,colflow: catch expected errors from Init at the root**

`Operator.Init` method might emit expected errors (e.g. when an operator
attempts to allocate a batch but hits the memory budget limit), and
previously we were not catching those - this would result in a crash.
This commit adds a catcher at components that can serve as the root of
the Operator tree (materializers and outboxes).

Fixes: #55077.

Release note (bug fix): CockroachDB could previously crash when
executing a query via the vectorized engine when most of the SQL memory
(determined via `--max-sql-memory` startup argument) has already been
reserved. This is now fixed.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Are the allocations in `Init` necessary? Why aren't they done in the constructor? It worries me that we're allowing `Init` to bubble up errors because suddenly you have to wrap all calls to an operator with a catcher. What about `DrainMeta`, for example?

In any case, I think this deserves a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MIZd3Uk6agY0WqnulGR:by0x56a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/materializer.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZcz7rALZLfGpb3ZWc:-MIZcz7rALZLfGpb3ZWd:b62vtyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colexec/materializer.go#L209)):*
> ```Go
> 	// reached), so we need to wrap it with a catcher.
> 	if err := colexecerror.CatchVectorizedRuntimeError(m.input.Init); err != nil {
> 		m.MoveToDraining(err)
> ```

Is it correct to `MoveToDraining` before we call `StartInternal`?
___
*[pkg/sql/colflow/colrpc/outbox.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZdLqH26uUIwng_YFI:-MIZdLqH26uUIwng_YFJ:bt4az1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colflow/colrpc/outbox.go#L330)):*
> ```Go
> 	// reached), so we need to wrap it with a catcher.
> 	if errToSend = colexecerror.CatchVectorizedRuntimeError(o.Input().Init); errToSend == nil {
> 		terminatedGracefully, errToSend = o.sendBatches(ctx, stream, cancelFn)
> ```

I think this would also need to happen in the hash router.

**Review by yuzefovich — COMMENTED** [review]
> Are the allocations in `Init` necessary? Why aren't they done in the constructor?

Doing these allocations in the constructor is a bad idea (without some code modifications) because we have `SupportsVectorized` check with a fake flow creator and we don't want to allocate anything then, so we always put the allocations into `Init` or `Next`. I believe initially most such allocations were done in `Init` because, well, they allocations need to be done once and it simplified `Next` methods. However, for things that we can fall over to disk-backed algorithms we moved the allocations into `Next` so that we didn't need to complicate disk-spilling logic. I think - if we ignore the error propagation thing - `Init` is the right place to do these allocations.

> It worries me that we're allowing `Init` to bubble up errors because suddenly you have to wrap all calls to an operator with a catcher.

I don't see a problem with it because we do need to wrap calls to `Next` somewhere, so why be concerned if we need to do the same for `Init`? It's the price we're paying for the current error propagation machinery.

> What about `DrainMeta`, for example?

Hm, good point. I believe you're thinking about parallel unordered synchronizer. Yes, we would need to add a catcher somewhere, but again we can do it at the root level if we don't care if the already accumulated metadata is dropped. I don't think there are many places where we call `Init` in `DrainMeta`, so it's not a big a concern to me.

I'll look into adding a test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MIZfVve2LOpaQCJvFiG:b-ct1azf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/materializer.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZcz7rALZLfGpb3ZWc:-MIZed1p0IuGlwF2HzBP:b-8stwgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colexec/materializer.go#L209)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it correct to `MoveToDraining` before we call `StartInternal`?
</blockquote></details>

Yeah, I believe so - I examined the code and there appears to be nothing that would care about whether `StartInternal` was called. We could rearrange the function calls to be certain though.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZdLqH26uUIwng_YFI:-MIZf1YcEt8upXoZ1w3M:bbau81f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colflow/colrpc/outbox.go#L330)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this would also need to happen in the hash router.
</blockquote></details>

I don't think it's necessary - for every node participating in the flow we either have a root materializer (the gateway) or a "root" outbox (remote nodes) whereas a hash router will never be the root (it can be an input to the root outbox though).

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Init because, well, they allocations need to be done once and it simplified Next methods

Makes sense

> I don't see a problem with it because we do need to wrap calls to Next somewhere, so why be concerned if we need to do the same for Init?

Because it's not obvious. It makes sense to do this exceptionally for Next because we'd also like to catch execution panics (e.g. nil pointers) without panicking the server. Can you add this to the interface contract? I wonder if there's a "level above" we could be doing this panic catching to not have to wrap every "root" call to `Init`/`Next`.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MIZjTUbE00Qp3iFnH2F:b-kohs1u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/materializer.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZcz7rALZLfGpb3ZWc:-MIZj8ix15nj2RxlKftH:b-u5n28n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colexec/materializer.go#L209)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, I believe so - I examined the code and there appears to be nothing that would care about whether `StartInternal` was called. We could rearrange the function calls to be certain though.
</blockquote></details>

I would prefer that just to be safe
___
*[pkg/sql/colflow/colrpc/outbox.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZdLqH26uUIwng_YFI:-MIZiJ8g-HlslGh87uyD:b3dr22a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colflow/colrpc/outbox.go#L330)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think it's necessary - for every node participating in the flow we either have a root materializer (the gateway) or a "root" outbox (remote nodes) whereas a hash router will never be the root (it can be an input to the root outbox though).
</blockquote></details>

The hash router is a root (it needs to run in its own goroutine). However, looking at the code it looks like it already wraps `Init`.

I think `sendBatches` already has a panic catcher for `Next`. Maybe it makes sense to get rid of this one and call `sendBatches` in `CatchVEctorizedRuntime` error as well, we might be able to get rid of the `terminatedGracefully` return parameter.

**Review by yuzefovich — COMMENTED** [review]
Updated the contract.

The level above would be wrapping the functions which we spin up in separate goroutines with the catcher (that would be `headProc.Run` in `FlowBase.Run` and all startable functions that we add using `vectorizedFlowCreatorHelper.accumulateAsyncComponent`.

However, there are only a handful components that would correspond to the things in those categories - the only processor that we can currently have is the materializer, and we only add outboxes and hash routers as startables. The only other component that spins up goroutines internally is the parallel unordered synchronizer (which calls `Init` on its inputs from the same goroutine as its "root" - no need for the catcher there - this also addresses the question about `DrainMeta`), and it wraps `Next` calls with the catcher.

Given all of these observations, I think the current approach of using the catcher in several places is reasonable. Additionally, I don't think we'll be introducing a new source of concurrency any time soon, so I feel like this should be the last time for a while when we need to think whether the catchers are everywhere they need to be. I also added another commit that should help us catch any regressions if they occur. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MIa8yfK6S-z0QQDtsG9:b2ijrwn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/materializer.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZcz7rALZLfGpb3ZWc:-MIa4zRXA0VoRAKMmXXV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colexec/materializer.go#L209)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would prefer that just to be safe
</blockquote></details>

Done.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MIZdLqH26uUIwng_YFI:-MIa5Oy332bgJ5hESOmz:b3pfos7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c45f3b906128d074e39ebb3f76870331f6903023/pkg/sql/colflow/colrpc/outbox.go#L330)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The hash router is a root (it needs to run in its own goroutine). However, looking at the code it looks like it already wraps `Init`.

I think `sendBatches` already has a panic catcher for `Next`. Maybe it makes sense to get rid of this one and call `sendBatches` in `CatchVEctorizedRuntime` error as well, we might be able to get rid of the `terminatedGracefully` return parameter.
</blockquote></details>

Good point about the hash router - we need to have a catcher wherever we spin up a new goroutine (apart from the root of the Operator tree on each node).

In `sendBatches` we have a scenario when `terminatedGracefully == false` but not because we caught an error - when sending on the stream failed. I refactored the code to have only a single catcher without changing the semantics of `sendBatches`.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, 3 of 3 files at r3, 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6XDPLBQVyYNiV613q:-MJ6XDPM9JNUIQ39TR34:bfbkbwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/700f59c45a1c288af5b75f8206d8e9527e4f405f/pkg/cmd/roachtest/sqlsmith.go#L104)):*
> ```Go
> 		// engine (and will ignore the injected errors) in order to test that
> 		// the panic-catching mechanism of error propagation works as expected.
> 		setup += "SET testing_vectorize_inject_panics=true;"
> ```

Is there any way to do this without a session variable? I don't feel comfortable exposing this to users. I wonder why sqlsmith doesn't use a testserver so that it can set internal testing knobs. Maybe @jordanlewis has an opinion here.

Also, if a sqlsmith query encounters an error, it's just discarded, right?
___
*[pkg/internal/sqlsmith/setup.go, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6ZZ-W2ea2JebUraVp:-MJ6ZZ-W2ea2JebUraVq:b-tnz9s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/43e02ad3d8b7ad34d620f9855914a572d32f30d4/pkg/internal/sqlsmith/setup.go#L185)):*
> ```Go
> // is designed to be used with anything in Setups, which may violate that
> // restriction.
> var SettingVectorize = staticSetting(Parallel, Vectorizable())
> ```

I think we need to keep all this stuff because `sqlsmith` is run against prior versions of cockroach since it's a roachtest right?
___
*[pkg/sql/colflow/vectorized_flow.go, line 1035 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6Xgka3XfYEph9RknO:-MJ6Xgka3XfYEph9RknP:b8eb9mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/700f59c45a1c288af5b75f8206d8e9527e4f405f/pkg/sql/colflow/vectorized_flow.go#L1035)):*
> ```Go
> 					result.Op = colexec.NewInvariantsChecker(result.Op)
> 				}
> 				if st := flowCtx.Cfg.Settings; st != nil {
> ```

Why are you checking if settings is non-nil? It's not used below.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6XDPLBQVyYNiV613q:-MJ8S_D3-SD-cY1YGy9r:b-xet5o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/700f59c45a1c288af5b75f8206d8e9527e4f405f/pkg/cmd/roachtest/sqlsmith.go#L104)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there any way to do this without a session variable? I don't feel comfortable exposing this to users. I wonder why sqlsmith doesn't use a testserver so that it can set internal testing knobs. Maybe @jordanlewis has an opinion here.

Also, if a sqlsmith query encounters an error, it's just discarded, right?
</blockquote></details>

As discussed, we'll proceed with the session variable for now, and I opened #55348 to improve the situation later.

Yes, the user of this setting (in this case `sqlsmith` roachtest) is responsible for making sure to ignore such errors (and the test ignores everything except for `internal error` and `communication error`).
___
*[pkg/internal/sqlsmith/setup.go, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6ZZ-W2ea2JebUraVp:-MJ8U9jq1-j2Hv9o8t0V:b-rd9z8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/43e02ad3d8b7ad34d620f9855914a572d32f30d4/pkg/internal/sqlsmith/setup.go#L185)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we need to keep all this stuff because `sqlsmith` is run against prior versions of cockroach since it's a roachtest right?
</blockquote></details>

Hm, interesting point. As a roachtest, yes, it could be run against any prior version, but on 20.2 and master the vectorized engine should support most of the types of operations, so I don't see much benefit in keeping these special configs. On 20.1 and 19.2 there is some benefit in keeping these configs, but the roachtests on those branches should be run fairly infrequently (only when there is a backport or a release), so I think it would be ok to remove these things. I don't feel strongly about it, so feel free to push back.

However, thinking about this made me realize that we probably should do `SET vectorize_row_count_threshold=0;` in all setups, what do you think? Or maybe we change the meaning of "vec" setup to be the one with 0 row count threshold but without limiting the types of things sqlsmith generates?
___
*[pkg/sql/colflow/vectorized_flow.go, line 1035 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6Xgka3XfYEph9RknO:-MJ8TW0b8jZVpAkuC_6a:bgfu895) ([raw file](https://github.com/cockroachdb/cockroach/blob/700f59c45a1c288af5b75f8206d8e9527e4f405f/pkg/sql/colflow/vectorized_flow.go#L1035)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are you checking if settings is non-nil? It's not used below.
</blockquote></details>

Good catch. This is a leftover artifact from my initial attempt (I used a cluster setting at first instead of a session variable).

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r5, 3 of 3 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MJRjtygDHt0gJLs8s7-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/internal/sqlsmith/setup.go, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6ZZ-W2ea2JebUraVp:-MJRhml1AXIOVq-hrvI6:b-r34ovj) ([raw file](https://github.com/cockroachdb/cockroach/blob/43e02ad3d8b7ad34d620f9855914a572d32f30d4/pkg/internal/sqlsmith/setup.go#L185)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, interesting point. As a roachtest, yes, it could be run against any prior version, but on 20.2 and master the vectorized engine should support most of the types of operations, so I don't see much benefit in keeping these special configs. On 20.1 and 19.2 there is some benefit in keeping these configs, but the roachtests on those branches should be run fairly infrequently (only when there is a backport or a release), so I think it would be ok to remove these things. I don't feel strongly about it, so feel free to push back.

However, thinking about this made me realize that we probably should do `SET vectorize_row_count_threshold=0;` in all setups, what do you think? Or maybe we change the meaning of "vec" setup to be the one with 0 row count threshold but without limiting the types of things sqlsmith generates?
</blockquote></details>

I think we should keep these in until we no longer support versions that don't have vectorized on by default.

`vectorize_row_count_threshold` was only used when `auto`, right? I think you're right that we have to set it to `0` for 20.2, but probably don't need to do anything for previous releases (but why not since it doesn't hurt). Maybe I'm misunderstanding what you're saying.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-:-MJSY50-DmprObjnGf-1:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/internal/sqlsmith/setup.go, line 185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55087#-MJ6ZZ-W2ea2JebUraVp:-MJSWMYa3lKq7kM3kVCl:b-dhfow7) ([raw file](https://github.com/cockroachdb/cockroach/blob/43e02ad3d8b7ad34d620f9855914a572d32f30d4/pkg/internal/sqlsmith/setup.go#L185)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we should keep these in until we no longer support versions that don't have vectorized on by default.

`vectorize_row_count_threshold` was only used when `auto`, right? I think you're right that we have to set it to `0` for 20.2, but probably don't need to do anything for previous releases (but why not since it doesn't hurt). Maybe I'm misunderstanding what you're saying.
</blockquote></details>

Ok, removed the third commit.

I forgot that `vectorize_row_count_threshold` only mattered for `auto` pre-20.2, good point. We should set it for 20.2 though as you're saying, I'll open up a separate PR.

**Comment by yuzefovich** [comment]
Actually, since we'll be removing `vectorize_row_count_threshold` setting soon, I think I won't add a change to set it to 0 in sqlsmith - it'll be annoying trying gate that based on the CRDB version later.

**Pull request merged**
