### PR TITLE
rowenc: various improvements to IndexFetchSpec initialization

### PR DESCRIPTION
**Pull request by RaduBerinde**
First commit is #76788.

#### catalog: store IndexFetchSpec key columns in table descriptor

We now cache the IndexFetchSpec_KeyAndSuffixColumns in the table
descriptor, making it cheaper to populate an IndexFetchSpec.

Release note: None

#### catalog: cleanup KeysPerRow

This change renames KeysPerRow to IndexKeysPerRow and changes the
argument to an IndexDescriptor, removing the error case.

Release note: None

#### catalog: cache family default columns in table descriptor

We now cache the `IndexFetchSpec_FamilyDefaultColumn`s in the table
descriptor, to avoid an allocation when creating an `IndexFetchSpec`.

Release note: None

#### rowenc: calculate key prefix length without allocating

We now calculate the key prefix length directly instead of creating a
throw-away key.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 6 of 6 files at r3, 4 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-:-MwEoqhy4thg8S-trDiR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/catalog/descriptor.go, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEbECI--kxtnuyUIsq:-MwEbECJ-qN8WqvWT0it:bejtz32) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/catalog/descriptor.go#L512)):*
> ```Go
> 	IndexStoredColumns(idx Index) []Column
> 
> 	// FetchSpecKeyAndSuffixColumns returns information about the key and suffix
> ```

nit: `s/FetchSpec/IndexFetchSpec/`.
___
*[pkg/sql/catalog/tabledesc/column.go, line 382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEc9rpCHWLx0oFfrSQ:-MwEc9rpCHWLx0oFfrSR:b9xfnfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/catalog/tabledesc/column.go#L382)):*
> ```Go
> 		invertedColumnID = idx.InvertedColumnID()
> 	}
> 	var compositeIDs catalog.TableColSet
> ```

nit: I think you can do `idx.CollectCompositeColumnIDs` for this.
___
*[pkg/sql/catalog/tabledesc/column.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEb_jfAzsp3NLzt9x-:-MwEb_jfAzsp3NLzt9x0:b-gsq6xb) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/catalog/tabledesc/column.go#L390)):*
> ```Go
> 		col := ic.all[i]
> 		if col == nil {
> 			// This is an invalid descriptor.
> ```

When can this occur? Maybe extend a comment?
___
*[pkg/sql/rowenc/index_fetch.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEcGLz79Gq7dZjCGev:-MwEcGLz79Gq7dZjCGew:bv10wm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/rowenc/index_fetch.go#L35)):*
> ```Go
> 	fetchColumnIDs []descpb.ColumnID,
> ) error {
> 	//oldKeyAndSuffixCols := s.KeyAndSuffixColumns
> ```

nit: seems like there are some leftovers in this file in the second commit.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-:-MwEu9yD4nLJljeBBphD:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/catalog/tabledesc/column.go, line 382 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEc9rpCHWLx0oFfrSQ:-MwEuC7O7V_TIGfR1Jo9:b-9mif11) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/catalog/tabledesc/column.go#L382)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think you can do `idx.CollectCompositeColumnIDs` for this.
</blockquote></details>

That's an `Index` method, we only have a `descpb.IndexDescriptor` here.
___
*[pkg/sql/catalog/tabledesc/column.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-MwEb_jfAzsp3NLzt9x-:-MwEuNd_BcMxYUe0TKc5:b-hozkeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/069b1984bc013e752b6b450c4a753aa6f58fbc0f/pkg/sql/catalog/tabledesc/column.go#L390)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

When can this occur? Maybe extend a comment?
</blockquote></details>

Added to a comment above. There are other weird things I had to tolerate (like `nil` columns or 0 column IDs).

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76795#-:-MwJSyA-EYvIVxILK9Ye:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Pull request merged**
