### PR TITLE
opt: add cluster setting to enable histograms

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds the cluster setting `sql.stats.histogram_collection.enabled`
to enable or disable histogram collection. When enabled, histograms are
collected by default for all index columns (specifically the first column
in each index) during automatic statistics collection. If a single column
statistic is explicitly requested using manual invocation of `CREATE STATISTICS`,
a histogram will be collected, regardless of whether or not the column is part
of an index.

When `sql.stats.histogram_collection.enabled` is disabled, histograms are never
collected, either as part of automatic statistics collection or manual
invocation of `CREATE STATISTICS`.

`sql.stats.histogram_collection.enabled` is currently disabled by default.

Release note (sql change): Added cluster setting
sql.stats.histogram_collection.enabled to enable collection of histograms
during statistics collection.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm: super nit: consider including the name of the cluster setting in the release note

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-:-LjX1Ah78wpUUiVEYoVO:b1mnseu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/jobs/jobspb/jobs.proto, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjWtnR1ABo3coPjZVbz:-LjWtnR297NYGB90BqE6:b1399zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/jobs/jobspb/jobs.proto#L220)):*
> ```protobuf
> 
>   // This should be a slice of the same length as the column lists slice above.
>   // It indicates whether each column stat should include a histogram.
> ```

Have these been serialized anywhere? If they have, should it be noted that this invariant might not hold true in the case of older versions? Also, :dog::microscope: is there a reason the `6` field comes after the `7`? Is there some reason the `fq_table_name` should be at the end? I also don't know much about protobuf design, but is there a reason you did this over adding it as a field to the submessage(?) defined above?
___
*[pkg/sql/create_stats.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjX0eVg3yZ3j2K-MKEI:-LjX0eVg3yZ3j2K-MKEJ:b-7qyy8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/sql/create_stats.go#L272)):*
> ```Go
> //
> // In addition to the index columns, we collect stats on up to maxNonIndexCols
> // other columns from the table. We only collect histograms for index columns.
> ```

Will we compute histograms multiple times for columns which are indexed multiple times (say, in a georeplicated scenario?)

**Review by rytaft — COMMENTED** [review]
TFTR!
> consider including the name of the cluster setting in the release note

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-:-Ljafaj5-e3GiTa9yitv:b-26y8bb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/jobs/jobspb/jobs.proto, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjWtnR1ABo3coPjZVbz:-LjaeIr15HHY2AYcdxbg:bfri17p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/jobs/jobspb/jobs.proto#L220)):*
I thought keeping them separate would be more backwards compatible, but after thinking about it and doing a bit of research, it seems like your idea is better.
> If you add new fields, any messages serialized by code using your "old" message format can still be parsed by your new generated code. You should keep in mind the default values for these elements so that new code can properly interact with messages generated by old code. Similarly, messages created by your new code can be parsed by your old code: old binaries simply ignore the new field when parsing. 

Also seems to be ok to rename the submessage and field name.

Not sure why `6` comes after `7` -- looks like that was a change from @RaduBerinde. I put them back in increasing order.
___
*[pkg/sql/create_stats.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjX0eVg3yZ3j2K-MKEI:-LjafrlDAFPpnnEcsSPR:b-w6f556) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/sql/create_stats.go#L272)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Will we compute histograms multiple times for columns which are indexed multiple times (say, in a georeplicated scenario?)
</blockquote></details>

Nope -- we deduplicate columns in the code below using the `requestedCols` ColSet

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38812)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/jobs/jobspb/jobs.proto, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjWtnR1ABo3coPjZVbz:-Ljal9Q1A0KGw-AzO1ss:b-2i13mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/jobs/jobspb/jobs.proto#L220)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I thought keeping them separate would be more backwards compatible, but after thinking about it and doing a bit of research, it seems like your idea is better.
> If you add new fields, any messages serialized by code using your "old" message format can still be parsed by your new generated code. You should keep in mind the default values for these elements so that new code can properly interact with messages generated by old code. Similarly, messages created by your new code can be parsed by your old code: old binaries simply ignore the new field when parsing. 

Also seems to be ok to rename the submessage and field name.

Not sure why `6` comes after `7` -- looks like that was a change from @RaduBerinde. I put them back in increasing order.
</blockquote></details>

In general, fields should be grouped as it makes sense conceptually, not by their IDs. If you try to keep the IDs sorted you are forced to keep the fields in the order in which they were added in the code, which is pretty lame. IMO max_fraction_idle belongs near asOf as they're both "knobs" for how the stats are run.

**Comment by rytaft** [comment]
___
*[pkg/jobs/jobspb/jobs.proto, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38812#-LjWtnR1ABo3coPjZVbz:-LjfaDyM5kspGy74D1bt:b-117pck) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fcbdd3819cfb75fcdd540e6412309e8389cc0cf/pkg/jobs/jobspb/jobs.proto#L220)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In general, fields should be grouped as it makes sense conceptually, not by their IDs. If you try to keep the IDs sorted you are forced to keep the fields in the order in which they were added in the code, which is pretty lame. IMO max_fraction_idle belongs near asOf as they're both "knobs" for how the stats are run.
</blockquote></details>

Ok fair enough -- moved it back.

**Pull request merged**
