### PR TITLE
backupccl: unskip TestBackupWorkerFailure

### LINKED ISSUE #64773: backupccl: TestBackupWorkerFailure is skipped
ccl/backupccl.TestBackupWorkerFailure [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2956776&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2956776&tab=artifacts#/) on master @ [72a144d8041361ecf1ad50669b729659e18a8139](https://github.com/cockroachdb/cockroach/commits/72a144d8041361ecf1ad50669b729659e18a8139):

```
=== RUN   TestBackupWorkerFailure
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackupWorkerFailure131095055
    test_log_scope.go:74: use -show-logs to present logs inline
E210506 10:49:03.464647 547011 jobs/registry.go:703  [-] 1  error processing claimed jobs: could not query for claimed jobs: select-running/get-claimed-jobs: context canceled
E210506 10:49:03.473442 547009 jobs/registry.go:683  [-] 2  failed to serve pause and cancel requests: could not query jobs table: cancel/pause-requested: context canceled
E210506 10:49:04.320674 566490 jobs/adopt.go:260  [n1] 3  job 656106261710569473: adoption completed with error could not reload backup manifest when retrying: reading backup checkpoint: checksum mismatch; expected 9cf355b6, got e3b0c442
    backup_test.go:8240: pq: could not reload backup manifest when retrying: reading backup checkpoint: checksum mismatch; expected 9cf355b6, got e3b0c442
E210506 10:49:04.387327 545596 jobs/registry.go:693  [-] 4  error claiming jobs: could not query jobs table: claim-jobs: context canceled
E210506 10:49:04.388295 547443 jobs/registry.go:703  [-] 5  error processing claimed jobs: could not query for claimed jobs: select-running/get-claimed-jobs: context canceled
E210506 10:49:04.390203 547441 jobs/registry.go:678  [-] 6  error expiring job sessions: expire-sessions: context canceled
E210506 10:49:04.391358 545594 jobs/registry.go:678  [-] 7  error expiring job sessions: expire-sessions: context canceled
E210506 10:49:04.391848 547441 jobs/registry.go:683  [-] 8  failed to serve pause and cancel requests: context canceled
E210506 10:49:04.393039 545594 jobs/registry.go:683  [-] 9  failed to serve pause and cancel requests: context canceled
E210506 10:49:04.398011 545596 jobs/registry.go:703  [-] 10  error processing claimed jobs: could not query for claimed jobs: select-running/get-claimed-jobs: context canceled
    panic.go:636: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestBackupWorkerFailure131095055
--- FAIL: TestBackupWorkerFailure (32.18s)
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestBackupWorkerFailure PKG=./pkg/ccl/backupccl TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
/cc @cockroachdb/bulk-io @adityamaru
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackupWorkerFailure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Epic CRDB-7778

Jira issue: CRDB-7240

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

Fixes: #64773.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Looks good to me.

For the verification, I wonder if we could speed it up a bit by restoring into a different database name to avoid the drop and using crdb_internal.fingerprint to do the verification.

**Review by stevendanna — APPROVED** [review]
Looks good to me.

For the verification, I wonder if we could speed it up a bit by restoring into a different database name to avoid the drop and using crdb_internal.fingerprint to do the verification.

**Comment by dt** [comment]
I timed each stmt and it was the RESTORE rather than the DROP that was taking 39s (but only sometimes). It seemed worth digging into (so I filed #109194) but didn’t want to block getting the test of the worker failure back to running on digging into restore speeds.

**Comment by dt** [comment]
While I still can’t get this to pass under race — on CI it times out and locally I get legit errors from tenant distsql planning — _not_ under race the tolerance of retryable errors in the progress writer, along with the other test chnages, seems to have made stress pass for me on gceworker 3 times and on the PR CI.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
