### PR TITLE
distsql: pool physical plans

### PR DESCRIPTION
**Pull request by jordanlewis**
First 2 commits are part of #30607 

```
name                           old time/op    new time/op    delta
FlowSetup/distribute=false-24    16.3µs ± 2%    15.9µs ± 2%  -1.96%
(p=0.001 n=8+9)

name                           old alloc/op   new alloc/op   delta
FlowSetup/distribute=false-24    25.6kB ± 0%    25.1kB ± 0%  -2.29%
(p=0.000 n=10+10)

name                           old allocs/op  new allocs/op  delta
FlowSetup/distribute=false-24       246 ± 0%       243 ± 0%  -1.22%
(p=0.000 n=10+10)
```

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30884)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1098 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30884#-LNzgpVxBY3nRabaAiUv:-LNzgpVxBY3nRabaAiUw:b-mn602g) ([raw file](https://github.com/cockroachdb/cockroach/blob/68437964b4520f025e828234bd8092dd0e20ed82/pkg/sql/distsql_physical_planner.go#L1098)):*
> ```Go
> 	nPartitions := len(spanPartitions)
> 	if cap(p.ResultRouters) >= nPartitions {
> 		p.ResultRouters = p.ResultRouters[:nPartitions]
> ```

We may be relying on these slices starting out as zero. In this case we are resurrecting the last state. (btw I'd go back and check your other similar changes with this in mind).

I believe that go 1.11 recognizes statements like `append(s, make([]T, n)...)` and avoids the allocation. So these could all become `x = append(x[:0], make([]T, n)...)`, assuming you're not looking to backport.

**Comment by jordanlewis** [comment]
Yeah I thought I was fastidious about checking for assumptions like that - I must have missed some. Also we de-upgraded from Go 1.11, or else I'd use your syntax.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30884)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30884#-LOZ0gj51TAz63iAlcEC:-LOZ0gj51TAz63iAlcED:b-g8qkzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/68437964b4520f025e828234bd8092dd0e20ed82/pkg/sql/distsql_physical_planner.go#L1153)):*
> ```Go
> 		nTypes = len(n.desc.Columns)
> 	}
> 	types := p.ResultTypes[:0]
> ```

nit: This reslicing is unnecessary I think.
___
*[pkg/sql/distsql_physical_planner.go, line 2031 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30884#-LOZ6djn0t7THWS1XP1e:-LOZ6djn0t7THWS1XP1f:b-jioa6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/68437964b4520f025e828234bd8092dd0e20ed82/pkg/sql/distsql_physical_planner.go#L2031)):*
> ```Go
> }
> 
> var physicalPlanPool = sync.Pool{
> ```

I would stick these next to `PhysicalPlan.Release`

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30884) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=30884) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=30884) it.</sub>

**Pull request closed without merging**
