### PR TITLE
authors: add jameswsj10 to authors

### PR DESCRIPTION
**Pull request by jameswsj10**
Release justification: non-production change
Release note: None

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jameswsj10)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69910#-Mj4wDo_4qmQsLdc3_hH):*
Hi @jameswsj10, we are at a special time of the year when we are preparing for a new release and the system requires a `Release justification` in the commit message and in the PR description. Would you please add a line with `Release justification: non-production change` above the `Release note` both in the commit message and in the PR description?

To change the commit message:

- amend the commit with `git commit --amend`
- push the new branch head to your remote with `git push --force-with-lease YOUR_FORK_NAME jamesjung_authors`

**Comment by jameswsj10** [comment]
amended commit to include the Release justification: non-production change line

**Review by jlinder — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jameswsj10)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69910#-Mj4wDo_4qmQsLdc3_hH):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Hi @jameswsj10, we are at a special time of the year when we are preparing for a new release and the system requires a `Release justification` in the commit message and in the PR description. Would you please add a line with `Release justification: non-production change` above the `Release note` both in the commit message and in the PR description?

To change the commit message:

- amend the commit with `git commit --amend`
- push the new branch head to your remote with `git push --force-with-lease YOUR_FORK_NAME jamesjung_authors`
</blockquote></details>

Ah! It's also important to keep a blank second line in the commit message. Can you add it back?

You can read about why it's important [here](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#General-structure-of-a-commit-message).

**Comment by jameswsj10** [comment]
Done! Thank you for the resource!

**Review by jlinder — APPROVED** [review]
:lgtm:

Welcome aboard!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69910#-:-Mj55Gxe6_cpUFR0PDNx:b-jjbub7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jameswsj10)

**Pull request merged**
