### PR TITLE
sql: Remove SNAPSHOT isolation

### LINKED ISSUE #26475: *: Remove SNAPSHOT isolation
Our implementation of `SNAPSHOT` isolation is buggy (#23176, #26460) and under-tested. Since the introduction of `RefreshSpans` in 2.0, it doesn't even improve performance significantly in most cases. We have discouraged its use by mapping all four ANSI isolation levels to `SERIALIZABLE`, so users wouldn't get `SNAPSHOT` unless they specifically requested it. We should go the rest of the way and remove it completely.

We could remove the `WriteTooOld` and `RetryOnPush` fields of `Transaction` when `SNAPSHOT` isolation is gone. I think we might also be able to eliminate the distinction between the read and write timestamp cache. 

In 2.1, we should map the SQL SNAPSHOT isolation level to SERIALIZABLE, but we'll need to leave all the supporting machinery in place until 2.2.

### PR DESCRIPTION
**Pull request by bdarnell**
The SNAPSHOT isolation level is no longer accessible from SQL.
Requests for SNAPSHOT will be remapped to SERIALIZABLE (in the same
way that the other ANSI levels already are).

KV-level support will remain through the next release cycle to support
transactions that began during a rolling upgrade.

Fixes #26475

Release note (sql change): The SNAPSHOT isolation level has been
removed. Transactions that request to use it are now mapped to
SERIALIZABLE.

The change in `lease_test.go` is the most complicated part here - I tried to adapt the test to a serializable transaction, but it's possible I misunderstood the intent of the test.

I left tests that used `BEGIN TRANSACTION SNAPSHOT` in place to ensure this syntax still works, and just changed the tests to reflect the new behavior of `SHOW transaction_isolation`.

While making this change I found that the previous change to map all the ANSI isolation levels to SERIALIZABLE was incomplete. There were some paths (such as `SET default_transaction_isolation`) that still used the old mapping of `READ COMMITTED` to `SNAPSHOT`. 

Also fixes a bug in `SET transaction_isolation='serializable'`, which was previously setting `snapshot` instead.

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

---

Reviewed 1 of 13 files at r1.
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/lease_test.go, line 865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG5uMl4AyOa664p6lcc:-LG5uMl55xpIuCaxnokl:b-gc7wos) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd0ba948f3135a7d030da04c2c95b2de1e541a55/pkg/sql/lease_test.go#L865)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	// Set the isolation level to Snapshot. This is because the test wants to
> ```

wasn't this comment relevant? Does the test test what it's supposed to test now? Like, does the error the txn receives on the first `release` have anything to do with the deadline, or is it a regular serialization restart? I'm thinking it's the latter cause I don't think we're smart enough to turn deadline errors into retriable errors.
If that's the case, I think you could turn the way the txn is pushed such that the span refresh would allow it to succeed if it wasn't for the deadline.
I have to admit though that I'm not entirely sure how the txn currently gets pushed. This test would benefit from more explanations.

---

*[pkg/sql/lease_test.go, line 870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG5uUsR7vr7z6ETnvun:-LG5uUsR7vr7z6ETnvuo:bsakco4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0695869a4fc4470030a5bb44f36f7efe622571/pkg/sql/lease_test.go#L870)):*
> ```Go
> 	}
> 
> 	// Insert an entry so that the transaction is guaranteed to be
> ```

this can go away since you're here. Timestamps are now assigned when the txn is created.

---

*[pkg/sql/sem/tree/txn.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG5vyzC2hkiIqRA4m3p:-LG5vyzC2hkiIqRA4m3q:b6lwbxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0695869a4fc4470030a5bb44f36f7efe622571/pkg/sql/sem/tree/txn.go#L40)):*
> ```Go
> // IsolationLevelMap is a map from string isolation level name to isolation
> // level, in the lowercase format that set isolation_level supports.
> var IsolationLevelMap = map[string]IsolationLevel{
> ```

consider getting rid of this map, or at least turning it into a set

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-:-LG5siaM7MXIvF6BMoxX:bvdsxq1)*

**Comment by bdarnell** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/lease_test.go, line 865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG5uMl4AyOa664p6lcc:-LG6bjqZ9iGprwnTWHGC:b-8qyc5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd0ba948f3135a7d030da04c2c95b2de1e541a55/pkg/sql/lease_test.go#L865)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wasn't this comment relevant? Does the test test what it's supposed to test now? Like, does the error the txn receives on the first `release` have anything to do with the deadline, or is it a regular serialization restart? I'm thinking it's the latter cause I don't think we're smart enough to turn deadline errors into retriable errors.
If that's the case, I think you could turn the way the txn is pushed such that the span refresh would allow it to succeed if it wasn't for the deadline.
I have to admit though that I'm not entirely sure how the txn currently gets pushed. This test would benefit from more explanations.
</blockquote></details>

You're right, this test isn't testing what it used to. I was having a hard time figuring out how to generate the deadline-exceeded error in a serializable transaction, but fortunately @vivekmenezes already did in #23681 (which never got reviewed/merged). I'm going to cherry-pick that change into this branch.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040)*

**Comment by bdarnell** [comment]
OK, I've replaced the `lease_test` change with #23681 by @vivekmenezes (with one small change to fix a typo that was breaking the build) and it looks like it's doing the right thing now. 

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-:-LG6fgsvBYMi_gtPCPns:bb9cofr)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/lease_test.go, line 888 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG76ibF8--RjwchBs17:-LG76ibF8--RjwchBs18:b-whqsjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L888)):*
> ```Go
> 	}
> 
> 	checkSelectResults := func() {
> ```

make this take `rows` as an arg, and also close them and check the err on close

---

*[pkg/sql/lease_test.go, line 931 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG75SWtBIi-t208RtB4:-LG75SWtBIi-t208RtB5:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L931)):*
> ```Go
> 	// The transaction read at one timestamp and wrote at another so it
> 	// has to be restarted because the spans read were modified by the backfill.
> 	if err := txReadWrite.Commit(); !testutils.IsError(err, "TransactionRetryError: retry txn \\(RETRY_SERIALIZABLE\\)") {
> ```

long line

---

*[pkg/sql/lease_test.go, line 948 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG75f5r6MRntkfM7VF9:-LG75f5r6MRntkfM7VFA:b-yw19do) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L948)):*
> ```Go
> 
> 	// Test the deadline exceeded error with a CREATE/DROP INDEX.
> 	testCases := []struct{ sql string }{
> ```

nit: `testCases` is not a great name since the tests are not independent. `schemaChanges`.

---

*[pkg/sql/lease_test.go, line 959 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG75tgi9AqMTanASj4k:-LG75tgi9AqMTanASj4l:b-1cf6h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L959)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		txUpdate, err := sqlDB.Begin()
> ```

pls say something about this `txnUpdate`. Why is it necessary / what is it testing? Cause I don't get it.

---

*[pkg/sql/lease_test.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG77SmB3YfgDt8vVYdm:-LG77SmB3YfgDt8vVYdn:b2k83jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L970)):*
> ```Go
> 
> 		// This INSERT will cause the transaction to be pushed transparently,
> 		// which will be detected when we attempt to Commit() below only because
> ```

I don't get what's the difference between this txn that gets the deadline error (so span refresh succeeds) and `txReadWrite` above for whom the refresh doesn't succeed. That one says something about the backfill writing data. How come this one doesn't have the same problem?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-:-LG77mk_BvRPDq7GDCOL:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/lease_test.go, line 888 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG76ibF8--RjwchBs17:-LG7F8ys0S8wrYbwpTEP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L888)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

make this take `rows` as an arg, and also close them and check the err on close
</blockquote></details>

Done.

---

*[pkg/sql/lease_test.go, line 931 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG75SWtBIi-t208RtB4:-LG7FLFF1Q2hMxDNHqbg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L931)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.

---

*[pkg/sql/lease_test.go, line 959 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG75tgi9AqMTanASj4k:-LG7Gt2O-KIrGnZZ-Uhq:bj75o77) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L959)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls say something about this `txnUpdate`. Why is it necessary / what is it testing? Cause I don't get it.
</blockquote></details>

I think this `txWrite` and `txUpdate` are both doing the same thing, for INSERT and UPDATE statements respectively: Do a transaction that spans a schema change and see that it gets a deadline error. I'm not sure, though. We may need an answer from @vivekmenezes. 

---

*[pkg/sql/lease_test.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-LG77SmB3YfgDt8vVYdm:-LG7IN7JCFCGvRoM_2CD:b-ttll7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/09df285a7b06f0caf78e2f202bfc20be34ca31af/pkg/sql/lease_test.go#L970)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't get what's the difference between this txn that gets the deadline error (so span refresh succeeds) and `txReadWrite` above for whom the refresh doesn't succeed. That one says something about the backfill writing data. How come this one doesn't have the same problem?
</blockquote></details>

I think the difference is in the schema changes: the backfill process/state machine for index changes is different from the one for adding a column. If I change `testCases` to add a column, I see the serializable failure as above.

This test needs some more documentation and should probably be refactored so all the different schema changes are handled through one loop with different expectations. But I'm not confident I understand what's going on here well enough to do that, so I'd like to go ahead and merge this and leave the cleanup to @vivekmenezes. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040)*

**Comment by andreimatei** [comment]
merge at will

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27040#-:-LG7TZOF9-U3nxGJwaVG:b6i6fo2)*

**Pull request merged**
