### PR TITLE
opt: fix wrong results due to sorting 1st join of paired join

### LINKED ISSUE #89603: sql: incorrect results due to sort in-between paired joins
roachtest.costfuzz [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6837153?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6837153?buildTab=artifacts#/costfuzz) on release-22.2 @ [64049e4b9210de3af4a1d814a9af0123b59a055f](https://github.com/cockroachdb/cockroach/commits/64049e4b9210de3af4a1d814a9af0123b59a055f):

```
		  | + 	``a	,0,NULL,X,0``,
		  | + 	``a	,0,NULL,X,0``,
		  |   	"a,0,0,X,0",
		  |   	"a,0,NULL,X,0",
		  |   	... // 166 identical elements
		  |   	"\x8eC\xec,0,NULL,X,0",
		  |   	"\x8eC\xec,0,NULL,X,0",
		  | + 	"\x8eC\xec,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,0,X,0",
		  | - 	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	"\xa7\xa8\xa1\xcc\xfd\xa6\xc2\xc1,0,NULL,X,0",
		  |   	... // 64 identical elements
		  |   	"á,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,0,X,0",
		  | + 	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	... // 30 identical elements
		  |   	"\xc4\x12|\x19\xab,0,NULL,X,0",
		  |   	"\xca,0,0,X,0",
		  | - 	"\xca,0,NULL,X,0",
		  |   	"\xca,0,NULL,X,0",
		  |   	"\xca,0,NULL,X,0",
		  |   	... // 64 identical elements
		  |   }
		  | sql: SELECT
		  | 	tab_17534.col1_3 AS col_52140,
		  | 	0:::OID AS col_52141,
		  | 	tab_17533.col1_7 AS col_52142,
		  | 	'\x58':::BYTES AS col_52143,
		  | 	0:::OID AS col_52144
		  | FROM
		  | 	defaultdb.public.table1@[0] AS tab_17533
		  | 	RIGHT JOIN defaultdb.public.table1@[0] AS tab_17534
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17535 ON
		  | 				(tab_17534.crdb_internal_mvcc_timestamp) = (tab_17535.crdb_internal_mvcc_timestamp)
		  | 				AND (tab_17534.col1_4) = (tab_17535.col1_4)
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17536 ON
		  | 				(tab_17535.col1_1) = (tab_17536.col1_1)
		  | 				AND (tab_17535.col1_3) = (tab_17536.col1_3)
		  | 				AND (tab_17534.col1_6) = (tab_17536.col1_6)
		  | 		JOIN defaultdb.public.table1@[0] AS tab_17537
		  | 			JOIN defaultdb.public.table1@[0] AS tab_17538 ON
		  | 					(tab_17537.crdb_internal_mvcc_timestamp) = (tab_17538.crdb_internal_mvcc_timestamp) ON
		  | 				(tab_17536.col1_2) = (tab_17538.col1_2) AND (tab_17535.col1_4) = (tab_17537.col1_4) ON
		  | 			(tab_17533.col1_3) = (tab_17537.col1_3) AND (tab_17533.col1_6) = (tab_17536.col1_6)
		  | ORDER BY
		  | 	tab_17535.col1_4, tab_17535.col1_3 DESC
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #86796 roachtest.costfuzz failed due to scientific notation v. decimal notation [C-test-failure T-sql-queries]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*costfuzz.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20329

### PR DESCRIPTION
**Pull request by msirek**
Fixes #89603

This fixes an issue where an illegal paired join plan is created by the
optimizer where the first join in the pair is sorted. This breaks the
assumption required in paired joiner logic that the first join in the
pair is never sorted or distributed for proper interpretation of the
continuation column:
```
// ContinuationCol is the column ID of the continuation column when
// IsFirstJoinInPairedJoiner is true. The continuation column is a
// boolean column that indicates whether an output row is a
// continuation of a group corresponding to a single left input row.
ContinuationCol opt.ColumnID
```

Function `lookupJoinCanProvideOrdering` allows the required ordering to
be passed to the child of the first join in a paired join if only the
input columns are projected (no lookup columns). This is not sufficient
because only when the first join can further pass the required ordering
on to its input can a sort be avoided.

The solution is to modify `lookupJoinCanProvideOrdering` to indicate the
second join in a paired join can provide an ordering if both the first
join and the first join's child can provide the ordering.

Release note (bug fix): This patch fixes possible, but rare, incorrect
results from paired lookup joins where the first join in the pair is
sorted.

xform: assertion for unenforcible props

This commit adds an assertion that a sort on the first join of a paired 
join is never enforced.

Fixes #89603

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
OK, that should be my last push. Just making sure the sanity check works.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NECL6urDSh9nMBE3zco:b-pkqbpp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

**Review by DrewKimball — COMMENTED** [review]
I'm not convinced this will actually solve the problem (or at least that the test will verify it does). We should probably use the `memo` format for the test.  I'm suspicious of #84689 - I think maybe we need to add a `!lookupJoin.IsSecondJoinInPairedJoiner` check to the branch I added.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NECe8fZ6iw5PdLvTgL2:bmkydnf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @sumeerbhola)

___
*[`pkg/sql/opt/xform/optimizer.go` line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-NECewF62O06tpO4qKel:-NECewF62O06tpO4qKem:bij6tg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0269b75a73d525700dcc9b8370d5b1e5c7c2b0b0/pkg/sql/opt/xform/optimizer.go#L589)):*
> ```Go
> 	// Was a required physical property applied which is unenforcible on the group
> 	// member and might do something bad like require an illegal sort?
> 	o.assertEnforcibleProps(member, required)
> ```

Seems like the overhead for this could be non-negligible, should it be a test-only check?
___
*[`pkg/sql/opt/xform/testdata/rules/join` line 12944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-NECWzfxBKT0kKHlnX7h:-NECWzfxBKT0kKHlnX7i:b-bpwdna) ([raw file](https://github.com/cockroachdb/cockroach/blob/a444d6751a7db722b2307158f2b78fb96e84b17e/pkg/sql/opt/xform/testdata/rules/join#L12944)):*
> ```
> # The sort must be done as the last step instead of in between the first and
> # second joins of the paired join.
> opt set=testing_optimizer_random_seed=4057832385546395198 set=testing_optimizer_cost_perturbation=1.0
> ```

[nit] could probably use a less verbose format here.

**Review by msirek — COMMENTED** [review]
I tried reverting #84689, and the problem is still there, so I don't think it's related.  Ideally there would be a way to not even optimize an enforcer.  Right now we're just sort of relying on the sort operation to not get chosen because the input can provide the ordering.  But as long as we're adding the enforcer to the memo, it might get chosen if costs are low.  I was trying some other fixes to avoid optimizing the enforcer at all for the first join in the pair, but that seemed like a risky change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NEClA7gCQ9LBIHdGmLW:b-p4zx03)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @sumeerbhola)

**Comment by DrewKimball** [comment]
How does the `(lookupJoin.IsFirstJoinInPairedJoiner || lookupJoin.IsSecondJoinInPairedJoiner)` prevent cases where we plan a sort on top of the first paired join? Any time we require an ordering, we call `optimizeEnforcer` with an enforcer added, so we don't really have a way to only propagate the child ordering.

Also, this has me thinking we should add the `(lookupJoin.IsFirstJoinInPairedJoiner || lookupJoin.IsSecondJoinInPairedJoiner)` check to the `canProjectUsingOnlyInputCols` case as well.

**Comment by DrewKimball** [comment]
What are the options for preventing this? Maybe it's too hacky, but one thing we could try would be to cost a sort on top of the first join in a paired join with `hugeCost`. Another solution could be to just check for this specific case in the optimizer somewhere (sounds like you tried this?). Finally, we could have an optimizer-only expression that wraps paired joins to prevent cases like this, since treating them as independent has lead to a few bugs already

**Review by msirek — COMMENTED** [review]
It doesn't prevent it entirely I think. It just makes selection of the optimized expression without sort much more likely due to costs. Like I said above, I was trying a fix to avoid optimizing the SortExpr entirely, but it's risky. Maybe we could do something like what's done in `Builder.buildDistribute` where a `NoOpDistribution` is removed entirely.  If we have a No-Op sort, would it be safe to remove it, I wonder?  Are there any query plans created that rely on a sort taking place, and removing the sort could cause problems?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NEDKA8I9QujRvO_NA1w:b-ro6jw9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @sumeerbhola)

**Review by msirek — COMMENTED** [review]
I was considering the `hugeCost` solution, but we'd have to make sure that kicks in even when fuzzing costs and that fuzzed costs of other expressions are never greater than `hugeCost`.  Yeah, I'm not sure if I like that or not, since there's still an illegal group member in the memo.  I will take a look at the #84689 code too and see if we should try to play it safe with paired joins.  Even if we disable some optimizations, we could always re-enable them later after more testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NEDMPsP55cy7hcHj0vR:b3pqtzl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @sumeerbhola)

**Comment by DrewKimball** [comment]
I think I'm leaning toward unifying paired lookup joins into one expression during optimization - that seems like it should solve problems of this nature for certain

**Review by msirek — COMMENTED** [review]
OK, I might let this ruminate a bit; looking at something else this afternoon.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89840#-:-NEDTZ0sEBukkrQYSXJE:b-3e0viz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @sumeerbhola)

**Comment by msirek** [comment]
Closing in favor of #92632

**Pull request closed without merging**
