### PR TITLE
sql: Add information_schema.table_constraints table

### PR DESCRIPTION
**Pull request by nvb**
This table contains all constraints belonging to tables.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8498)

### CODE REVIEW

**Comment by dt** [comment]
Is NOT NULL a constraint?

**Comment by paperstreet** [comment]
NOT NULL is not a table constraint. Looks like these four are all mysql supports

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KOywgeDCMUxcQsQ7WOt:bhuu4h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
> ```Go
> 				}
> 				var constraints []constraint
> 				if table.PrimaryIndex.IsSet() {
> ```

wait, isn't is always true? even if you don't specify a primary key, we create the row_id column and stick that in here

in fact, just checked and ValidateTable will return an error if PrimaryIndex has no column ids

---

*[sql/information_schema.go, line 200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOyyn5uGOAjRHVoObiU:-KOyyn5uGOAjRHVoObiV:bluej9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L200)):*
> ```Go
> 						parser.NewDString(db.Name),     // constraint_schema
> 						dStringOrNull(constraint.name), // constraint_name
> 						parser.NewDString(db.Name),     // table_schema
> ```

both of these `_schema`s are supposed to be db.Name? Sorry for the CR laziness, I tried to google this but didn't immediately find it and it's already loaded up in your head

---

*[sql/sqlbase/structured.go, line 231 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOyy4oZu2_5MoVsK56q:-KOyy4oZu2_5MoVsK56r:b-psvq31) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/sqlbase/structured.go#L231)):*
> ```Go
> 
> // IsSet returns whether or not the index actually references a column.
> func (desc *IndexDescriptor) IsSet() bool {
> ```

I actually dislike this as a helper. In both places you're using it, it's much more clear what's going on if you inline the definition (the `foo.IsSet() && foo[0]` in particular makes me uncomfortable). And it's not likely that the repetition will be a maintenance burden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-:-KOyxX9PqsX3pWAnMPFT:bdfn4yx)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KPKER5i25Eddzt35iep:b2nume0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> wait, isn't is always true? even if you don't specify a primary key, we create the row_id column and stick that in here
> 
> in fact, just checked and ValidateTable will return an error if PrimaryIndex has no column ids
</details>
Yeah I'm confused too, PrimaryIndex should always have columns.. Maybe what we want to check is whether all columns in the PrimaryIndex are `Hidden`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KPKFgGjojCNJds4IUnl:b6o3df6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Yeah I'm confused too, PrimaryIndex should always have columns.. Maybe what we want to check is whether all columns in the PrimaryIndex are `Hidden`?
</details>
The reason I added this is because virtual table descriptors do not have primary indexes. I guess I could replace all of these calls with `isVirtualDescriptor` calls, but I figured this is more expressive and allows for more extensibility (eg. if it is ever not true that a table has a primary key, like in the case of temp tables). What do you think?

---

*[sql/information_schema.go, line 200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOyyn5uGOAjRHVoObiU:-KPJwyJnDVWbL3nwVuFZ:b-97as9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L200)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> both of these `_schema`s are supposed to be db.Name? Sorry for the CR laziness, I tried to google this but didn't immediately find it and it's already loaded up in your head
</details>
Yeah, the standard is a little verbose, but this is how both PG and MySQL implement it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498)*

**Comment by RaduBerinde** [comment]
*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KPKHTKKL5HuhInVzn7K:bojsnob) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> The reason I added this is because virtual table descriptors do not have primary indexes. I guess I could replace all of these calls with `isVirtualDescriptor` calls, but I figured this is more expressive and allows for more extensibility (eg. if it is ever not true that a table has a primary key, like in the case of temp tables). What do you think?
</details>
Ah, I see, then please add a comment before (`virtual table descriptors don't have primary indexes")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KPKIzGqHd30BYsGP-Qp:ba6byxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, I see, then please add a comment before (`virtual table descriptors don't have primary indexes")
</details>
Got it, thanks Radu. I'll add that comment to the `IsSet` method as well so that its clear why we need to call it in the other location as well. @paperstreet, does this sound good? Or do you still not like the idea of `PrimaryIndex.IsSet()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498)*

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/information_schema.go, line 172 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-KOywgeDCMUxcQsQ7WOs:-KPOogvB4xt3-TMz_bX3:b22d7cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1836c7f52869686137a99caf2fb55b69b3da75d4/sql/information_schema.go#L172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Got it, thanks Radu. I'll add that comment to the `IsSet` method as well so that its clear why we need to call it in the other location as well. @paperstreet, does this sound good? Or do you still not like the idea of `PrimaryIndex.IsSet()`?
</details>
As discussed offline, I think the semantics of a `hasNoPrimaryKey` method at the table level are better than IsSet on every index. Assuming there's some comment about virtual tables having no primary key in that method definition, I'm happy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-:-KPOp0ffIJ-q1v1jhn53:bnfp4nl)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8498#-:-KPEH5er7vpye-uH3YMw:bnfp4nl)*

**Pull request merged**
