### PR TITLE
opt/constraint: use already built constraints; build constraints for "bare" boolean vars

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: use already built constraints

The constraints code does something silly: when we have a conjunction
we recursively build constraints for the conjuncts, even though we
already calculated constraints for these expressions.

This change fixes this by looking up the constraints in the logical
properties instead. We treat untyped NULLs as an exception, as they
can be used as a boolean and don't have constraints calculated.

Release note: None

#### opt: constraints for "bare" boolean vars

Build constraints for `x` and `NOT x` when `x` is bool.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-:-LCA4xS-3an83FJBTZl9:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAF4qD9hbr4Pn5FDgN:-LCAF4qD9hbr4Pn5FDgO:bi3ofk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/constraint_builder.go#L253)):*
> ```Go
> 
> 	case opt.VariableOp:
> 		// Support (x) as (x = TRUE) if x is boolean.
> ```

This comment (and the one below) confused me a bit at first. The way it is written it sounds almost like a TODO.

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAFY5x9Iz2B3CiCVd8:-LCAFY5x9Iz2B3CiCVd9:b-15l94p) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/testdata/logprops/constraints#L495)):*
> ```
>  │    ├── columns: abc.a:1(int) abc.b:2(bool) abc.c:3(string)
>  │    └── stats: [rows=1000]
>  └── filters [type=bool, outer=(2), constraints=(/2: (/NULL - /false]; tight)]
> ```

are you going to do `preferInclusive` on boolean values at some point? Maybe add a TODO somewhere?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-:-LCAOfUW2-GH92DM1gxO:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAF4qD9hbr4Pn5FDgN:-LCB6Zs8EVbcJCFE32J8:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/constraint_builder.go#L253)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment (and the one below) confused me a bit at first. The way it is written it sounds almost like a TODO.
</blockquote></details>

Reworded.

---

*[pkg/sql/opt/memo/testdata/logprops/constraints, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAFY5x9Iz2B3CiCVd8:-LCB6b98Dhb2Q2UEQ25c:b3g0cd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/testdata/logprops/constraints#L495)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

are you going to do `preferInclusive` on boolean values at some point? Maybe add a TODO somewhere?
</blockquote></details>

we do use it, that's how here we have ` - /false]` and not `- /true)`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366)*

**Comment by RaduBerinde** [comment]
Rebased and merged some conflicts.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-:-LCB9aYM1co3BunFQeSH:bh4z9df)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAFY5x9Iz2B3CiCVd8:-LCEeHTyAb909IRAT9yu:b-c4vaer) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/testdata/logprops/constraints#L495)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why doesn't it convert `(/NULL - /false]` to `[/false - /false]`?
</blockquote></details>

Yeah, it's a good question. It would be a special case - we would have to check if the datum type has a minimum value. There are cases where that might be undesirable, e.g. if the minimum datum is unwieldy (`(/NULL - /5]` -> `[-9223372036854775808 - /5]`. By the same token, would we convert `[ - 5]` to `[ -9223372036854775808 - 5]`? They are both preferable in some cases (e.g. we can continue the start span if we also have a constraint on the next column), but in most cases we would just do extra encoding (not to mention the cosmetic aspect).

I am putting this on my TODO list, I'll think some more about it. Maybe we can do it just on a few specific types, like bool.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25366#-LCAFY5x9Iz2B3CiCVd8:-LCEmyh5Esc9KzgdGxRV:b-55w2ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb8fd12decd47c27afd5c6650b5c7257330a2/pkg/sql/opt/memo/testdata/logprops/constraints#L495)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, it's a good question. It would be a special case - we would have to check if the datum type has a minimum value. There are cases where that might be undesirable, e.g. if the minimum datum is unwieldy (`(/NULL - /5]` -> `[-9223372036854775808 - /5]`. By the same token, would we convert `[ - 5]` to `[ -9223372036854775808 - 5]`? They are both preferable in some cases (e.g. we can continue the start span if we also have a constraint on the next column), but in most cases we would just do extra encoding (not to mention the cosmetic aspect).

I am putting this on my TODO list, I'll think some more about it. Maybe we can do it just on a few specific types, like bool.
</blockquote></details>

Sounds good - thanks for the explanation!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25366)*

**Pull request merged**
