### PR TITLE
sql: add closest-instance physical planning

### PR DESCRIPTION
**Pull request by dt**
This changes physical planning, specifically how the SQL instance for a
given KV node ID is resolved, to be more generalized w.r.t. different
locality tier taxonomies.

Previously this function had a special case that checked for, and only
for, a specific locality tier with the key "region" and if it was
found, picked a random instance from the subset of instances where their
value for that matched the value for the KV node.

Matching on and only on the "region" tier is both too specific and not
specific enough: it is "too specific" in that it requires a tier with
the key "region" to be used and to match, and is "not specific enough"
in that it simultaneously ignores more specific locality tiers that
would indicate closer matches (e.g. subregion, AZ, data-center or rack).

Instead, this change generalizes this function to identify the subset of
instances that have the "closest match" in localities to the KV node and
pick one of them, where closest match is defined as the longest matching
prefix of locality tiers. In a simple, single-tier locality taxonomy
using the key "region" this should yield the same behavior as the
previous implementation, as all instances with a matching "region" will
have the same longest matching prefix (at length 1), however this more
general approach should better handle other locality taxonomies that use
more tiers and/or tiers with names other than "region".

Currently this change only applies to physical planning for secondary
tenants until physical planning is unified for system and secondary
tenants.

Release note: none.
Epic: CRDB-16910

### CODE REVIEW

**Review by knz — COMMENTED** [review]
i like it :100:  - but let's see what our sql queries folk think of it.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-:-NQQ6XBx5T60-OxlICyc:b-eghgfd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

**Review by rharding6373 — APPROVED** [review]
:lgtm: Very elegant. Thank you for this!

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-:-NQR0yAx5SijKZuzPIgx:b-vo2esg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
I agree, nice work! :lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-:-NQRDbF9BFhYYORd00x4:bzbha0r)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dt)

___
*[`pkg/roachpb/metadata.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-NQRAlQ8BBVadSiZUCH5:-NQRAlQ8BBVadSiZUCH6:beiqiid) ([raw file](https://github.com/cockroachdb/cockroach/blob/92257e33d43327f439e40175fc2a082bb1b4a4b5/pkg/roachpb/metadata.go#L615)):*
> ```Go
> }
> 
> // SharedPrefix returns the number of this locality's tiers which match those
> ```

nit: something sounds off in "those the passed locality", like a preposition "of" is missing or something.
___
*[`pkg/sql/distsql_physical_planner.go` line 1381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-NQRCcqu3QGY7UsNeQgX:-NQRCcqu3QGY7UsNeQgY:b-4ka5ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91b05544a435a651c14a39f69fe9f914801a73d/pkg/sql/distsql_physical_planner.go#L1381)):*
> ```Go
> 	}
> 
> 	// If we were able to determine the region information for at least some
> ```

nit: this comment needs a minor adjustment now, probably just `s/region/locality/g`.

**Review by dt — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-:-NQRISj25_4kJG-8Hox_:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz, @rharding6373, and @yuzefovich)

___
*[`pkg/roachpb/metadata.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-NQRAlQ8BBVadSiZUCH5:-NQRIN23AuUDuVV7QOgg:b1ral9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/92257e33d43327f439e40175fc2a082bb1b4a4b5/pkg/roachpb/metadata.go#L615)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: something sounds off in "those the passed locality", like a preposition "of" is missing or something.
</blockquote></details>

Done.

Yep, indeed was supposed to say "of the passed..."
___
*[`pkg/sql/distsql_physical_planner.go` line 1381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-NQRCcqu3QGY7UsNeQgX:-NQRIIv07Hht8KUmUhYt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c91b05544a435a651c14a39f69fe9f914801a73d/pkg/sql/distsql_physical_planner.go#L1381)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment needs a minor adjustment now, probably just `s/region/locality/g`.
</blockquote></details>

Done

**Review by mgartner — APPROVED** [review]
:100: 

> Reviewed 1 of 2 files at r1, 4 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98468#-:-NQR_JJkAGfDAfLGbNo-:bmi8ppe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @dt)

**Pull request merged**
