### PR TITLE
restore: split left and right before scatter in online restore

### PR DESCRIPTION
**Pull request by dt**
If we don't split to the right before we scatter, our scatter can race with other workers that are putting down their LHS split, as that changes the descriptor of the range we are scattering.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by kvoli — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124513)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @msbutler)

___
*[`pkg/ccl/backupccl/restore_online.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-NySIhRu670nHeonmmGq:-NySIhRu670nHeonmmGr:b5tg4j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb313fc9ab02d4a922f528c389f749330b5774a/pkg/ccl/backupccl/restore_online.go#L189)):*
> ```Go
> 			}
> 			if err := sendSplitAt(ctx, execCtx, start); err != nil {
> 				log.Warningf(ctx, "failed to split during experimental restore: %v", err)
> ```

Q: why is this experimental restore, instead of online restore?
___
*[`pkg/ccl/backupccl/restore_online.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-NySJ4DY0RAexmw7pShz:-NySJ4DY0RAexmw7pSi-:bh7rxht) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb313fc9ab02d4a922f528c389f749330b5774a/pkg/ccl/backupccl/restore_online.go#L252)):*
> ```Go
> 
> 			log.Infof(ctx, "flushing %s batch of %d SSTs at end of restore span entry %s", sz(batchSize), len(toAdd), entry.Span)
> 			if err := flush(nil, entry.ElidedPrefix); err != nil {
> ```

Q: What is this doing? Why isn't `end` used, as was previously done?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124513)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @msbutler)

___
*[`pkg/ccl/backupccl/restore_online.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-NySIhRu670nHeonmmGq:-NyV4mQv03Sl77ocva6J:b-kuln33) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb313fc9ab02d4a922f528c389f749330b5774a/pkg/ccl/backupccl/restore_online.go#L189)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Q: why is this experimental restore, instead of online restore?
</blockquote></details>

"experimental" was already a keyword in the sql grammar so we used it in the syntax for the prototype and have continued to use it in user-facing things like log messages. "online" so far is only used in internal things like tickets/epics/file names. When we get to go-to-market phase we'll figure out one name to rule them all but until then it is all placeholders.
___
*[`pkg/ccl/backupccl/restore_online.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-NySJ4DY0RAexmw7pShz:-NyV5FR-Blw9GLX_RBMM:b-daes6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb313fc9ab02d4a922f528c389f749330b5774a/pkg/ccl/backupccl/restore_online.go#L252)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Q: What is this doing? Why isn't `end` used, as was previously done?
</blockquote></details>

The key passed to `flush`, if not nil, is split before `flush` ingests all the files in the buffer. The caller normally passes the start key of the file next file, the one to the right of all the files that are to be flushed, so that flush can lay down a split to the right of the files it will flush before flushing them into what is then its own private range.

This call to `flush` is _after_ the body of the loop over all all files in the chunk, and is flushing just any partially full residual buffer that wasn't flushed above, which would be the last few files at the far right side of the chunk.

At the top of this diff we changed the way we start the chunk to be to split at the chunk's start and end keys before scattering the chunk's start key -- this is the split-RHS-before-scattering that we discussed to avoid the race -- so we now already have a split to the right of these files at the upper end of our chunk, so when we flush them we don't need to make it again.

**Review by stevendanna — COMMENTED** [review]
Overall this change makes sense to me.

One thing it highlights is that we are scattering on the basis of restoreSpanEntries and not before every flush.  Personally, I think we may want to leave ourselves a block comment somewhere describing the interaction between the logic we have in generateAndSendImportSpans and the logic we have here.  Although, I'm happy to leave that until our logic here settles for a bit.

**Review by kvoli — APPROVED** [review]
:lgtm:  - Will likely want someone from DR to actually stamp.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-:-Nya6QXb8mTwtD-2gzbG:b-lqco3x)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @msbutler)

___
*[`pkg/ccl/backupccl/restore_online.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124513#-NySJ4DY0RAexmw7pShz:-Nya6MIICeUM3tyQGYaL:b-wsvas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fb313fc9ab02d4a922f528c389f749330b5774a/pkg/ccl/backupccl/restore_online.go#L252)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

The key passed to `flush`, if not nil, is split before `flush` ingests all the files in the buffer. The caller normally passes the start key of the file next file, the one to the right of all the files that are to be flushed, so that flush can lay down a split to the right of the files it will flush before flushing them into what is then its own private range.

This call to `flush` is _after_ the body of the loop over all all files in the chunk, and is flushing just any partially full residual buffer that wasn't flushed above, which would be the last few files at the far right side of the chunk.

At the top of this diff we changed the way we start the chunk to be to split at the chunk's start and end keys before scattering the chunk's start key -- this is the split-RHS-before-scattering that we discussed to avoid the race -- so we now already have a split to the right of these files at the upper end of our chunk, so when we flush them we don't need to make it again.
</blockquote></details>

Thanks for the explanation.

**Comment by dt** [comment]
DR reviewers: if this is good to go, feel free to bors it; further changes to this area over in https://github.com/cockroachdb/cockroach/pull/124640

**Review by msbutler — APPROVED** [review]

**Pull request merged**
