### PR TITLE
kvcoord: retry `ReplicaUnavailableError` against other replicas

### LINKED ISSUE #105167: kvserver: replica circuit breakers counterproductive under partial partitions
Consider this partial network partition:

```
         (gateway)
             n1
            /  \
           /    \
(leader) n2 xxxx n3 (leaseholder)
```

The leaseholder on n3 will be unable to propose writes to the leader on n1. With expiration-based leases, the lease will eventually expire, and get picked up by n2.

However, this scenario will cause n3's replica circuit breakers to fire, and the circuit breaker errors were specifically designed not to be retried. If n3 happens to have the lowest latency from n1's point of view, it will keep sending requests to n3 and immediately error out, before discovering the new lease on n2, resulting in permanent unavailabilty.

Jira issue: CRDB-28906

Epic CRDB-25200

### LINKED ISSUE #118266: kvclient: DistSender must retry replica circuit breaker errors
It's possible for a replica circuit breaker to trip even though the range is fully functional. The only criteria is that a replica proposal (e.g. a lease request) does not succeed in 60 seconds. This can happen e.g. if the replica is partitioned away from the leader, if the replica is stale and no longer part of the range, if the replica has stalled, etc.

If a DistSender encounters this replica (e.g. it's cached as the previous leaseholder, or it happens to be the first replica it attempts) then it will return an error to the client immediately, without trying other replicas. This can lead to the range appearing unavailable to clients using this DistSender, even though the range itself may be fully functional.

The DistSender needs to retry circuit breaker errors by moving onto the next replica in line. If the range is in fact unavailable, then there are two possibilities: either each retry must wait for the next replicas's circuit breaker to trip in sequence (1 minute per replica), or all replica's circuit breakers are already tripped in which case we'll incur RTT latencies for each replica. This seems acceptable, considering the alternative is permanent unavailability, and an optimization to attempt replicas in parallel can be considered separately (e.g. #109320).

Jira issue: CRDB-35649

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: add test cases for `ReplicaUnavailableError` mark**

**kvpb: add error type for `ReplicaUnavailableError`**

This allows accessing the error via `kvpb.Error.GetDetail()`.

**kvcoord: retry `ReplicaUnavailableError` against other replicas**

Previously, a `ReplicaUnavailableError` returned by a tripped replica circuit breaker was not retried by the DistSender, instead failing fast back to the client. This was sort of by design, since these errors are intended to avoid clients getting stuck in infinite retry loops.

However, a single replica having a tripped circuit breaker does not imply that the range is unavailable -- it's possible that e.g. this replica is partially partitioned away from the quorum, or is a stale replica waiting to be caught up. If a DistSender attempts this replica first, e.g. because it was the last-known leaseholder or it's the lowest latency replica, then it will always error out, giving the appearance of an unavailable range to the client.

This patch adds DistSender retry handling of `ReplicaUnavailableError`, which attempts to contact other replicas in case a functional lease exists elsewhere, while also taking care to avoid retry loops where other replicas return a `NotLeaseHolderError` pointing back to the unavailable replica.

Resolves #118266.
Resolves #105167.
Epic: none
Release note (bug fix): if an individual replica's circuit breaker had tripped but the range was otherwise functional, e.g. because the replica was partially partitioned away from the leaseholder, it was possible for a gateway to persistently error when contacting this replica instead of retrying against a functional leaseholder elsewhere. The gateway will now retry such errors against other replicas once.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I have to look into what the error type addition means for backports. It's a bit unfortunate, but I don't know if it can be avoided.

@nvanbenschoten I don't think your idea of rejecting lease requests if we're not the leader will work with replica circuit breakers in their current form, see https://github.com/cockroachdb/cockroach/issues/118435#issuecomment-1923670443.

**Comment by erikgrinaker** [comment]
>I have to look into what the error type addition means for backports. It's a bit unfortunate, but I don't know if it can be avoided.

This shouldn't affect backports, afaict. We just implement `ErrorDetailInterface` for `ReplicaUnavailableError`, which allows retrieving it locally via `GetDetail()` and adds a DistSender error metric for it. It doesn't affect the wire format, so it doesn't matter if the `ReplicaUnavailableError` originates from a node with or without this patch.

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118737)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2673 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118737#-NqYl32W4QSUQEzvuDBX:-NqYl32W4QSUQEzvuDBY:b9k5vdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f1316415b42496895c750bb6afd3d8b4becda6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2673)):*
> ```Go
> 							if rue := (*kvpb.ReplicaUnavailableError)(nil); errors.As(err, &rue) {
> 								if lh.IsSame(rue.Replica) {
> 									return nil, replicaUnavailableError
> ```

There is a problematic case worth considering as it could be common. 

Initial state - r1-r5 healthy, r2 is the leaseholder, and r3 is lagging.

Fault: r2 fails (becomes unavailable)
New state:
r1 - leaseholder
r2 - unavailable
r3 - lagging
r4, r5 - not-lagging

Client has ordered replicas as r2, r3, ... 
Hits r2 - gets replica unavailable
Hits r3 - gets NotLeaseholder with leaseholder = r2.

Client hits this check and returns the `ReplicaUnavailableError`. 

Future requests will hit the same replicas (r2, r3) and keep returning error until r3 catches up. 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2941 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118737#-NqYnA9L21wkpcqX7m77:-NqYnA9L21wkpcqX7m78:b-tnfzyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f1316415b42496895c750bb6afd3d8b4becda6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2941)):*
> ```Go
> 		return noMoreReplicasErr(
> 			ambiguousError,
> 			nil, // ignore the replicaUnavailableError, retry with new routing info
> ```

I'm not sure if this matters, but should we also clear the `replicaUnavailableError` since we are re-creating the routing? I'm not sure what the implications of not clearing it would be.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118737)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2673 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118737#-NqYl32W4QSUQEzvuDBX:-NqgeSrH-SgQ7LkTdwIG:bimpkaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f1316415b42496895c750bb6afd3d8b4becda6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2673)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

There is a problematic case worth considering as it could be common. 

Initial state - r1-r5 healthy, r2 is the leaseholder, and r3 is lagging.

Fault: r2 fails (becomes unavailable)
New state:
r1 - leaseholder
r2 - unavailable
r3 - lagging
r4, r5 - not-lagging

Client has ordered replicas as r2, r3, ... 
Hits r2 - gets replica unavailable
Hits r3 - gets NotLeaseholder with leaseholder = r2.

Client hits this check and returns the `ReplicaUnavailableError`. 

Future requests will hit the same replicas (r2, r3) and keep returning error until r3 catches up.
</blockquote></details>

I didn't think this case would be any different than what already happens with other errors, e.g. in the case of a dead node where we'll hit a connection refused. But I think it is, because `MoveToFront()` will simply swap the assumed leaseholder with the next pending replica. So if we hit r3 -> r2, and r2 fails again, we'll move onto r4 instead of spinning on r3.

There is another way we could handle this, by ignoring NLHEs that point back to a RUE, and instead keep trying replicas until we run out. I don't _think_ this should end up in NLHE loops either (if nodes disagree on the NLHE leaseholder), but should doublecheck.

Does that sound reasonable? I'll update the PR when I get a chance.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2941 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118737#-NqYnA9L21wkpcqX7m77:-NqgdocB4LtfAOWUkYDe:b8669t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f1316415b42496895c750bb6afd3d8b4becda6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2941)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm not sure if this matters, but should we also clear the `replicaUnavailableError` since we are re-creating the routing? I'm not sure what the implications of not clearing it would be.
</blockquote></details>

We're in a different scope, so we can't clear it here. It doesn't matter either, since the error will be returned back up past `sendToReplicas`, and we'll re-enter it with a new, empty `replicaUnavailableError`.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118737)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2673 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118737#-NqYl32W4QSUQEzvuDBX:-Nr098C_1UmmTlb2POhq:b-f3zkei) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f1316415b42496895c750bb6afd3d8b4becda6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2673)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I didn't think this case would be any different than what already happens with other errors, e.g. in the case of a dead node where we'll hit a connection refused. But I think it is, because `MoveToFront()` will simply swap the assumed leaseholder with the next pending replica. So if we hit r3 -> r2, and r2 fails again, we'll move onto r4 instead of spinning on r3.

There is another way we could handle this, by ignoring NLHEs that point back to a RUE, and instead keep trying replicas until we run out. I don't _think_ this should end up in NLHE loops either (if nodes disagree on the NLHE leaseholder), but should doublecheck.

Does that sound reasonable? I'll update the PR when I get a chance.
</blockquote></details>

Updated the PR to simply skip NLHEs pointing back to a RUE. I believe this should avoid retry loops since we only update the leaseholder with newer generations and don't retry replicas that haven't had a NLHE point to them.

Nice catch, thanks!

**Comment by erikgrinaker** [comment]
kv95 benchmarks are inconclusive due to noise. I think it's probably fair to say that even the cancel tracking doesn't make a significant difference here, considering the p50 is at 1.12ms and we're looking at sub-µs penalties. I'll see if I can run some more conclusive benchmarks with larger sample sizes.

```
name                                       ops/sec    p50        p95        p99
kv95/enc=false/nodes=3/cpu=32/cb=disabled  138k ± 7%  1.12 ±11%  3.38 ± 9%  5.40 ± 7%  n=5
kv95/enc=false/nodes=3/cpu=32/cb=enabled   139k ± 8%  1.12 ±11%  3.36 ± 8%  5.40 ± 7%  n=5
kv95/enc=false/nodes=3/cpu=32/cb=cancel    141k ± 8%  1.08 ±11%  3.34 ±11%  5.30 ± 6%  n=5
```

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

The complexity of this code and looping makes me a little sad and nervous, but I don't see any issues with it. I'm hoping I can build some `dist_sender_nemesis` type testing in the future and simplifying the way the transport is used.

**Comment by erikgrinaker** [comment]
> The complexity of this code and looping makes me a little sad and nervous, but I don't see any issues with it. I'm hoping I can build some dist_sender_nemesis type testing in the future and simplifying the way the transport is used.

Yeah, I never feel particularly confident about changes here, and I forget how it works between each time I touch it. Could definitely do with a better test harness.

TFTR!

bors r+

**Comment by erikgrinaker** [comment]
Hm, I'll have to doublecheck the interactions with AmbiguousError here -- I think we have to wrap these as ambiguous if they are commits, since the breaker can trip while the command is in flight.

bors r-

**Comment by erikgrinaker** [comment]
>Hm, I'll have to doublecheck the interactions with AmbiguousError here -- I think we have to wrap these as ambiguous if they are commits, since the breaker can trip while the command is in flight.

Indeed, updated the PR to mark these as ambiguous when used with commits.

**Pull request merged**
