### PR TITLE
sql: store physical props in indexJoinNode

### PR DESCRIPTION
**Pull request by justinj**
The change in #25292 was incomplete, this change finishes that work to
store the physical props on the indexJoinNode and not simply pass
through to the index scan.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/index_join.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEB_bmj2CJBQQmLeaDL:-LEB_bmj2CJBQQmLeaDM:bdhgwje) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/index_join.go#L218)):*
> ```Go
> 		},
> 		// In the heuristic planner, since all the columns are present in the index
> 		// join node, we don't need to do any translation here.
> ```

[nit] this wording is a bit awkward. I'd also explicitly mention the optimizer to explain why this is needed at all.

---

*[pkg/sql/opt_needed.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEBajsO3Up47VCndxAl:-LEBaipi7rkyXDd2cNI-:biz8iif) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/opt_needed.go#L72)):*
> ```Go
> 		// These will always line up with the columns in the table, since this
> 		// function is only used by the heuristic planner, and it plans such that
> 		// things line up that way.
> ```

[nit] This comment is a bit confusing. Maybe just say the length of `needed` equals the length of `resultColumns`? Also, it might be worth adding a panic if they are not the same length....

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-:-LEBdErn1k_g89STNHRT:bnfp4nl)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEF6efU0Qj54YQeVQ9m:-LEF6efU0Qj54YQeVQ9n:b-a5y2mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/expand_plan.go#L705)):*
> ```Go
> 
> 	case *indexJoinNode:
> 		n.index.props.trim(usefulOrdering)
> ```

Add a comment here saying that indexJoinNodes created by the heuristic planner always have the same schema with the underlying tables, so we can pass through `usefulOrdering`.

---

*[pkg/sql/opt_needed.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEBajsO3Up47VCndxAl:-LEF5znz6Oce5vUgB7l_:bmqknti) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/opt_needed.go#L72)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] This comment is a bit confusing. Maybe just say the length of `needed` equals the length of `resultColumns`? Also, it might be worth adding a panic if they are not the same length....
</blockquote></details>

This comment explains why it's ok to call `setNeededColumns(n.table, needed)` without any translation, it should be above. The loop seems legit regardless if the columns line up.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-:-LEF6hx_8b1pErDNPPw0:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEK5fyiE7uBrFFDCygR:-LEK5fyj4E6wdRQYXAWF:b-h0ocng) ([raw file](https://github.com/cockroachdb/cockroach/blob/de745e4d78054587f569d283d5363bd0bf467c2d/pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin#L39)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT w FROM t WHERE v > 10 AND v < 50 ORDER BY v]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJyslL9uqzAYR_f7FFe_9foq2JA_ZWJNh6SKulUMFH-KkBKMbFO1qnj3KjhSTdU4RGHE9vmOz4A_UStJm-JIBukLOBgEGGIwJGCYI2dotCrJGKVPRxywlu9II4aqblrrlm1lD4QUSkvSJMEgyRbVoZ-b8X_Iu5yhVJqQfp_eqP-qma0Gp_OOQbX2PDlnMLbYE9K4Y56de_ZfBj8XrwfaUSFJz6LhZd4yC4Zta9O_GWeZwCUhv0X4qKr67EuGvkZXx0J_eNb4olIMlGJ8I5-k8YrQa5xP1RiPbxSTNF4Reo2LqRqT8Y3xJI1XhF7jcqrGKKzckWlUbWjUnx6dngqSe3JPi1GtLulJq7LXuM9tz_ULkox1uw_uY127rdMFfZgHYRGGRRCOBjD_CcdBOAmbk3vM8yC8CJsX95iXQXgVNq9uMufdn68AAAD__5mfNlw=
> ```

This plan looks incorrect (we are discarding `v` and sorting by `w` in the final merge). Could you add a logic test that reproduces the problem? A similar query should show the incorrect order in `fakedist` mode.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26373)*

**Comment by justinj** [comment]
Review status: 4 of 10 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/expand_plan.go, line 705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEF6efU0Qj54YQeVQ9m:-LEKdTcS6ZWhp5FDBWYd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/expand_plan.go#L705)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add a comment here saying that indexJoinNodes created by the heuristic planner always have the same schema with the underlying tables, so we can pass through `usefulOrdering`.
</blockquote></details>

Done.

---

*[pkg/sql/index_join.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEB_bmj2CJBQQmLeaDL:-LEKd-CY14CFNRFHy8uL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb2b676b8a27467447d41e71d8ffa702f5afb792/pkg/sql/index_join.go#L218)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] this wording is a bit awkward. I'd also explicitly mention the optimizer to explain why this is needed at all.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26373)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26373#-LEK5fyiE7uBrFFDCygR:-LEKdfxO3iBNIsBjBaGa:b-qbxl94) ([raw file](https://github.com/cockroachdb/cockroach/blob/de745e4d78054587f569d283d5363bd0bf467c2d/pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin#L39)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Ok, added in `select_index`.
</blockquote></details>

Looks great, thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26373)*

**Comment by justinj** [comment]
Moved the explain test to the execbuild tests

bors r+

**Comment by RaduBerinde** [comment]
I'd remove the INSERT from the test with the explain..

**Comment by justinj** [comment]
bors cancel

**Pull request merged**
