### PR TITLE
storage: assert local single delete safety

### PR DESCRIPTION
**Pull request by jbowens**
During intent resolution, examine internal keys when intending to delete an
intent using a single delete tombstone to validate that it is indeed safe
within the local Engine. This is a safety measure to validate that we do not
violate the invariants that make singe deletion deterministic and cause replica
divergence. False negatives are possible, since this safety mechanism only
examines the local engine state and only the state visible to the open lock
table iterator at the time of proposal evaluation.

Release note: none
Epic: none
Informs https://github.com/cockroachdb/cockroach/issues/114492.
Informs https://github.com/cockroachdb/cockroach/issues/114421.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This approach seems good to me, as long as we can gain some confidence that this won't introduce a meaningful performance regression.

> False negatives are possible, since this safety mechanism only examines the local engine state and only the state visible to the open lock table iterator at the time of proposal evaluation.

This is an unfortunate limitation of the approach because it seems believable that if we are getting this wrong, then we are likely getting it wrong on follower replicas who (1) have just applied range snapshots or (2) are catching up on a large chunk of their raft log or (3) aren't applying entries sequentially with minimal batching of writes to the same key (like we'd expect on the leaseholder) for some other reason.

Still, I think this is a good start.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-:-NjnCH8MDQKDIuJ1GLJr:b4y7eil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 5052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-Njn8oWg5w98_vsv-XZ0:-Njn8oWg5w98_vsv-XZ1:b-rjq04h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e275332a1b27a6746139fdfb283140f46f4ee502/pkg/storage/mvcc.go#L5052)):*
> ```Go
> }
> 
> type lockOutcome int8
> ```

`lockResolutionOutcome`?
___
*[`pkg/storage/mvcc.go` line 5080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-Njn90w178K8RmE9F9CT:-Njn90w178K8RmE9F9CU:b-rlp8l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e275332a1b27a6746139fdfb283140f46f4ee502/pkg/storage/mvcc.go#L5080)):*
> ```Go
> ) (outcome lockOutcome, err error) {
> 	if meta.Txn == nil || meta.Txn.ID != intent.Txn.ID {
> 		return outcome, errors.Errorf("txn does not match: %v != %v", meta.Txn, intent.Txn)
> ```

nit: We generally prefer to return the zero value literal on error return paths, to avoid questions of whether the variable was meaningfully set to some value. So `return 0, errors.Errorf(...)` instead.
___
*[`pkg/storage/mvcc.go` line 4963 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-NjnBORd3iE7IvNtSpl8:-NjnBORd3iE7IvNtSpl9:b-p798sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f05093cbd6db8346ce40b3b63ed3eb6e473f60b/pkg/storage/mvcc.go#L4963)):*
> ```Go
> 			// and it also doesn't guarantee the single delete will be okay on
> 			// other replicas' engines.
> 			if ok, err := ltIter.CanDeterministicallySingleDelete(); err != nil {
> ```

I understand the reasoning behind wanting this assertion on even in production builds. At the same time, it feels risky to be landing it so close to a release without much testing to determine whether it will fire (due to a real bug or due to a false positive) or whether it will harm performance.

Maybe we should at least put it behind a gate so that we have an ability to disable it if we ever get stuck. Even an environment variable to opt-out would provide some recourse if someone's cluster starts crash-looping.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-:-NjnN4hz1fF_yTwJGm0x:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/storage/engine.go` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-NjnLAJJEQfGXqOo7WiW:-NjnLAJJEQfGXqOo7WiX:b-32psc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f05093cbd6db8346ce40b3b63ed3eb6e473f60b/pkg/storage/engine.go#L404)):*
> ```Go
> 	// CanDeterministicallySingleDelete does not change the iterator position
> 	// (all subsequent iterator operations should behave as if
> 	// CanDeterministicallySingleDelete was never invoekd), although it DOES
> ```

invoked

**Review by jbowens — COMMENTED** [review]
Agreed, its limitations are unfortunate. We've considered assertions within Pebble, but there's nowhere we already have the full merged view of the LSM like here. The view of a compaction is so limited that it's very unlikely for enough internal keys to detect misuse to meet in a single compaction.

Another possibility is to look for these single deletion violations in the background during unrelated lock table iteration. This might actually be feasible, but seems involved enough to be infeasible this late in the release.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-:-NjoEnXi2fNHwm3GOpeS:b6iqicy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @sumeerbhola)

___
*[`pkg/storage/engine.go` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-NjnLAJJEQfGXqOo7WiW:-Njnv73Q-LKaHEoZCnBU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f05093cbd6db8346ce40b3b63ed3eb6e473f60b/pkg/storage/engine.go#L404)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

invoked
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 5052 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-Njn8oWg5w98_vsv-XZ0:-Njnv7zc4q5s0g8BOJAx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e275332a1b27a6746139fdfb283140f46f4ee502/pkg/storage/mvcc.go#L5052)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`lockResolutionOutcome`?
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 5080 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-Njn90w178K8RmE9F9CT:-Njnv8fpCutK9iE3O5tq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e275332a1b27a6746139fdfb283140f46f4ee502/pkg/storage/mvcc.go#L5080)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: We generally prefer to return the zero value literal on error return paths, to avoid questions of whether the variable was meaningfully set to some value. So `return 0, errors.Errorf(...)` instead.
</blockquote></details>

Done.
___
*[`pkg/storage/mvcc.go` line 4963 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114820#-NjnBORd3iE7IvNtSpl8:-Njnv9WiAlffVw_EBIPR:b-bpqv1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f05093cbd6db8346ce40b3b63ed3eb6e473f60b/pkg/storage/mvcc.go#L4963)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I understand the reasoning behind wanting this assertion on even in production builds. At the same time, it feels risky to be landing it so close to a release without much testing to determine whether it will fire (due to a real bug or due to a false positive) or whether it will harm performance.

Maybe we should at least put it behind a gate so that we have an ability to disable it if we ever get stuck. Even an environment variable to opt-out would provide some recourse if someone's cluster starts crash-looping.
</blockquote></details>

I agree the risk of a false positive bug or performance regression is real, and it makes me nervous. I'm not too concerned about detecting a real bug, because if we do, the fataling is preferable to whatever undefined behavior might result from the corruption. These assertions add additional risk themselves, but they simultaneously mitigate risk of a corruption bug with proven existence.

Good idea to have a gate. I added an environment variable.

**Comment by jbowens** [comment]
TFTRs! I’m going to merge this to keep things moving for the backport and we can continue discussion there.

bors r=sumeerbhola

**Pull request merged**
