### PR TITLE
util: FastIntSet improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### util: use intsets.Sparse in FastIntSet

Improving the code for FastIntSet to use a `intsets.Sparse` when we have
elements outside of the [0,64) range. We don't just use `Sparse` directly
because it's larger (56 bytes) and must be on the heap (we can't have slices of
`Sparse`).

Also improving the interface to use `int`s and adding a `SubsetOf` method.

#### util: improve FastIntSet with math/bits

Use the new `math/bits` primitives in `FastIntSet`.

#

Please ignore the first commit (separate PR). Note that I will be out for two weeks and don't plan to merge these PRs until I come back, so there is no rush to review.

### CODE REVIEW

**Comment by knz** [comment]
I did not review the first commit since I believe it comes from #18475. 2nd and 3rd commit LGTM.
I am curious about the performance difference on the ordering computations when switching from small to large int sets...

---

Reviewed 10 of 10 files at r2, 1 of 1 files at r3.
Review status: 10 of 28 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KuI8CuheMfRwcr-LqqW:b-5snu7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
> ```Go
> // Add adds a value to the set. No-op if the value is already in the set.
> func (s *FastIntSet) Add(i int) {
> 	if i >= 0 && i < smallCutoff && s.large == nil {
> ```

Either document in the comment above that negative values are accepted and a no-op, or remove this condition here.

I think I'd rather remove it, and document that negative values are not allowed, and ensure that the callers don't provide one, because I think that where we use this API a negative value here would be a bug.

---

*[pkg/util/fast_int_set.go, line 90 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI993dIjxUwJoFZ35R:-KuI993dIjxUwJoFZ35S:bmweq14) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L90)):*
> ```Go
> 		return s.large.Has(i)
> 	}
> 	return i >= 0 && i < smallCutoff && (s.small&(1<<uint64(i))) != 0
> ```

ditto about i >= 0 - either comment above or remove this condition. Here I think probably the condition can stay, I can see why it is useful.

---

*[pkg/util/fast_int_set.go, line 106 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIA66b9faFO0RcdA0r:-KuIA66cekodENClXixm:b-12gbu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L106)):*
> ```Go
> 	}
> 	if startVal < smallCutoff {
> 		if startVal < 0 {
> ```

ditto, if a negative value is valid document it above.
I'm not sure why it is useful here, perhaps remind the reader why you did this.

---

*[pkg/util/fast_int_set.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIB4XjtnSjZrYIx6Kh:-KuIB4XjtnSjZrYIx6Ki:b-8k2m1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L155)):*
> ```Go
> 		return s.large.AppendTo([]int(nil))
> 	}
> 	// TODO(radu): when we switch to go1.9, use the new math/bits.OnesCount64 to
> ```

Regarding this: it's a bit dangerous, depending on the platform OneCount64 may actually iterate. What we'd really want is the bits package offering this function directly...

---

*[pkg/util/fast_int_set_test.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIBuSlm2_95BVV0bcm:-KuIBuSlm2_95BVV0bcn:bz5a14s) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set_test.go#L27)):*
> ```Go
> func TestFastIntSet(t *testing.T) {
> 	for _, m := range []int{1, 8, 30, smallCutoff, 2 * smallCutoff, 4 * smallCutoff} {
> 		t.Run(fmt.Sprintf("%d", m), func(t *testing.T) {
> ```

nit: t.Parallel()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-:-KuI8s2R4Ezqg-HcZYZu:bsck7yz)*

**Comment by petermattis** [comment]
Review status: 10 of 28 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIB4XjtnSjZrYIx6Kh:-KuKGjn2qxbvQpoQzHST:bbfqdn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Regarding this: it's a bit dangerous, depending on the platform OneCount64 may actually iterate. What we'd really want is the bits package offering this function directly...
</blockquote></details>

`math/bits.OnesCount64`does [something clever](https://golang.org/src/math/bits/bits.go?s=4586:4616#L124) in the portable implementation, but on the platforms we care about it is implemented by a compiler intrinsic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by andreimatei** [comment]
:lgtm: for 2nd and 3rd commits

---

Review status: 10 of 28 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 50 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuMFZpg-MGkIrAcacag:-KuMFZpg-MGkIrAcacah:baaoagn) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L50)):*
> ```Go
> // Returns the bit encoded set from 0 to 63, and a flag that indicates whether
> // there are elements outside this range.
> func (s *FastIntSet) largeToSmall() (small uint64, otherValues bool) {
> ```

I wonder if this method is really necessary. When I saw it I wondered if we call it after every `Remove()`. Since we don't, the other uses don't seem too impressive to me; we could handle all the comparisons by only working on large sets.

---

*[pkg/util/fast_int_set.go, line 111 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuMHVESZ6rOza5B5bJS:-KuMHC2tUTi0YHPz6k9R:bb7ek88) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8dae5071c4200b8f7891635cd4bddfbb87003d/pkg/util/fast_int_set.go#L111)):*
> ```Go
> 		}
> 
> 		if ntz := bits.TrailingZeros64(s.small >> uint64(startVal)); ntz < 64 {
> ```

cute

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-:-KuMIAyf21N4Zpkp04rn:b-fxqoee)*

**Comment by RaduBerinde** [comment]
Review status: 10 of 28 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvTzx3bFKtjiiscbv3C:b320nur) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Either document in the comment above that negative values are accepted and a no-op, or remove this condition here.

I think I'd rather remove it, and document that negative values are not allowed, and ensure that the callers don't provide one, because I think that where we use this API a negative value here would be a bug.
</blockquote></details>

Negative values are allowed, and they're not a no-op; they are treated just like large values (i.e. `large` is used).

---

*[pkg/util/fast_int_set.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIB4XjtnSjZrYIx6Kh:-KvU0UGnqFv8Gimp24tO:b9qd3b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L155)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`math/bits.OnesCount64`does [something clever](https://golang.org/src/math/bits/bits.go?s=4586:4616#L124) in the portable implementation, but on the platforms we care about it is implemented by a compiler intrinsic.
</blockquote></details>

Not sure what the concern is. It's well defined what`OneCount64` returns and it's not platform dependent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by RaduBerinde** [comment]
Review status: 10 of 28 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/util/fast_int_set.go, line 50 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuMFZpg-MGkIrAcacag:-KvU65SvMvBrNTDlinJW:b-db2i0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I wonder if this method is really necessary. When I saw it I wondered if we call it after every `Remove()`. Since we don't, the other uses don't seem too impressive to me; we could handle all the comparisons by only working on large sets.
</blockquote></details>

To work on large sets, we either convert the small to large just for that operation, or we permanently change the representation of that set. I don't like either: the former can incur an allocation on every `Equals/SubsetOf` call, and the latter can cause the representation to change (unfavorably) simply because `Equals/SubsetOf` was called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by petermattis** [comment]
Review status: 10 of 28 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/util/fast_int_set.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIB4XjtnSjZrYIx6Kh:-KvUWOrtdWyVH0tUrGKc:b-h0lt7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L155)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure what the concern is. It's well defined what`OneCount64` returns and it's not platform dependent.
</blockquote></details>

I think @knz was concerned that `bits.OnesCount64` might be implemented using a naive iteration that is O(num-bits). That is, the concern was about the resulting performance, not correctness. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 28 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_set_test.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIBuSlm2_95BVV0bcm:-KvXel0oRq71z7yQ7vPu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set_test.go#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: t.Parallel()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by knz** [comment]
Please merge #18475 and rebase this before I can complete the review.

**Comment by RaduBerinde** [comment]
Rebased.

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-:-KvXksJRP5nayL6W8HtO:bncvegj)*

**Comment by knz** [comment]
Reviewed 8 of 10 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXlNR16BM0cxlznpvY:bfri148) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Negative values are allowed, and they're not a no-op; they are treated just like large values (i.e. `large` is used).
</blockquote></details>

Huh then where in the rest code do you assert that no invalid column index (-1) is added to a set?

---

*[pkg/util/fast_int_set.go, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuIB4XjtnSjZrYIx6Kh:-KvXlWO7ZPzodldsBktV:b-7aitaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L155)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think @knz was concerned that `bits.OnesCount64` might be implemented using a naive iteration that is O(num-bits). That is, the concern was about the resulting performance, not correctness. 
</blockquote></details>

Thanks for clarifying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXlpTRJAJU987LrplM:b-ca1ow5) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Huh then where in the rest code do you assert that no invalid column index (-1) is added to a set?
</blockquote></details>

We don't.. we rely on test cases to verify that we populate columns correctly.

I wanted to keep this structure general-purpose, and make it no less functional than `intsets.Sparse`. But if you feel strongly, I can require non-negative indices.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXmfzSxD6VBDqucKac:b-c5np0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We don't.. we rely on test cases to verify that we populate columns correctly.

I wanted to keep this structure general-purpose, and make it no less functional than `intsets.Sparse`. But if you feel strongly, I can require non-negative indices.
</blockquote></details>

I can see the value of supporting negative values -- we could use that to implement other things later. 

However in the previous code it was easy to catch an invalid column index, because Go would refuse the indexing of a slice and issue a panic. In the new code I fear that negative indexes will be propagated longer, more silently. Perhaps it is worth asserting this in the caller of Add() instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXoSh8TrxEHOFpxTO7:b-l6xzja) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I can see the value of supporting negative values -- we could use that to implement other things later. 

However in the previous code it was easy to catch an invalid column index, because Go would refuse the indexing of a slice and issue a panic. In the new code I fear that negative indexes will be propagated longer, more silently. Perhaps it is worth asserting this in the caller of Add() instead.
</blockquote></details>

There are many callers of Add.. Are there any specific ones that are concerning? In most cases what we pass to `Add` is the result of `eqGroups.Find()` which does panic on -1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXpbgUt6-XV5bjalzP:b-lfxhrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There are many callers of Add.. Are there any specific ones that are concerning? In most cases what we pass to `Add` is the result of `eqGroups.Find()` which does panic on -1.
</blockquote></details>

Your response contains the answer: the caller of `Add` that do not use the result of `eqGroups.Find`, if any. Likewise you can exclude the callers that already assert the value is non-negative by other means (e.g. via `len` or others).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by RaduBerinde** [comment]
*[pkg/util/fast_int_set.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492#-KuI8CuheMfRwcr-LqqV:-KvXqTlPK4EA_rF1yW6y:btkdmh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/850aa2e222f7afda39c05206fa8b658fdd47bab9/pkg/util/fast_int_set.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Your response contains the answer: the caller of `Add` that do not use the result of `eqGroups.Find`, if any. Likewise you can exclude the callers that already assert the value is non-negative by other means (e.g. via `len` or others).
</blockquote></details>

Ok, I did an audit and it looks like all cases do `Find` first. There's a single exception in RowFetcher.Init where the value is a range loop variable which is always non-negative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18492)*

**Comment by knz** [comment]
Thanks for checking.

LGTM (modulo addressing the linter errors)

**Pull request merged**
