### PR TITLE
vendor: bump Pebble to 4cc0974fdade

### PR DESCRIPTION
**Pull request by jbowens**
```
4cc0974f *: propagate pointer to InternalIteratorStats
9c2bc013 metamorphic: print out correct options name on test failure
b83dd2c7 *: fix error handling in simpleLevelIter
70943038 *: use Equal for more efficient equality comparisons
7030aaab metamorphic: fix iterSeekLTWithlimit
89408b27 tool: support range keys
```

Release note: None
Release justification: Non-production code changes, low-risk
high-benefit changes to existing functionality and bug fixes for new
functionality.

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-:-NAB9e3yCK37GotuEwik:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86692)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msbutler)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-NABOaS80CzVpK98uRD6:-NABOaS80CzVpK98uRD7:b-c7ka4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/112160813c78b4036eb69ff6ca079c7d1f1c858b/pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only#L176)):*
> ```
> RESTORE DATABASE d FROM LATEST IN 'nodelocal://0/full_database_backup/' with schema_only, verify_backup_table_data, new_db_name='d4';
> ----
> pq: importing 2 ranges: pebble/table: invalid table 000000 (checksum mismatch at 0/121)
> ```

@msbutler — this is as expected, right?

And the above TODO is still relevant, yes?

**Review by msbutler — APPROVED** [review]
LGTM, Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-:-NABR9k16AtRqs-Sbl41:brdz4f9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @msbutler, and @nicktrav)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-NABOaS80CzVpK98uRD6:-NABQnJ71LcyyvkB7A3F:bu2q9p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/112160813c78b4036eb69ff6ca079c7d1f1c858b/pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only#L176)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

@msbutler — this is as expected, right?

And the above TODO is still relevant, yes?
</blockquote></details>

Yeah, i can get rid of that todo once this lands https://github.com/cockroachdb/cockroach/pull/86423

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86692)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msbutler and @nicktrav)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-NABOaS80CzVpK98uRD6:-NAFCgbSEKl4r952Ijyw:b480i2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/112160813c78b4036eb69ff6ca079c7d1f1c858b/pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only#L176)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

Yeah, i can get rid of that todo once this lands https://github.com/cockroachdb/cockroach/pull/86423
</blockquote></details>

looks like the block length is non-deterministic. was this error previously massaged into something deterministic?

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86692)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens, @msbutler, and @nicktrav)

___
*[`pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86692#-NABOaS80CzVpK98uRD6:-NAFMGWw2zYNIz2YaOrz:b-iycnxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/112160813c78b4036eb69ff6ca079c7d1f1c858b/pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only#L176)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

looks like the block length is non-deterministic. was this error previously massaged into something deterministic?
</blockquote></details>

ah, try revising the test to:
```
exec-sql expect-error-regex='pebble/table: invalid table 000000'
RESTORE DATABASE d FROM LATEST IN 'nodelocal://0/full_database_backup/' with schema_only, verify_backup_table_data, new_db_name='d4';
----
regex matches error
```

If that doesn't work, I can deal with it.

**Comment by jbowens** [comment]
TFTRs!

bors r=nicktrav,msbutler

**Pull request merged**
