### PR TITLE
sql: Fix panic with date_trunc during a distSQL query

### LINKED ISSUE #20464: distsqlrun: panic when calling date_trunc in a distSQL plan
The following schema and statements will cause a panic.
```sql
CREATE TABLE topics (created_at TIMESTAMP NULL);

INSERT INTO topics VALUES ('2017-12-05 04:04:04.913231+00:00');

SELECT date_trunc('month', created_at) AS date_trunc_month_created_at FROM "topics";
```

When running in the local execution engine, everything is fine.

```sql
panic: invalid datum type given: timestamptz, expected timestamp

goroutine 23358 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x69ef300, 0xc4271d65a0, ...)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:122 +0x26e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc4244b1c00, 0x12, 0x12, 0x80, 0x14fd4a35d3c48708, 0x0, 0x0, ...)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:330 +0x7ae
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).EmitRow(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc4244b1c00, 0x12, 0x12, 0xc42290ab00, 0xc42290ab70, 0x0)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:264 +0x8e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc4257f4a00, 0x69defc0, 0xc4239de300, 0xc42290aa88)
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:171 +0x3f9
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/Users/joey/.go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:419 +0x3d7
```

(yours truly, the gift that keeps giving: 💎-🛤 testing)

### PR DESCRIPTION
**Pull request by lgo**
Fixes #20464.

Prior to this patch, date_trunc was defined for timestamp, timestamptz,
time, and date. Each of these definitions returned the same type that
the input was. In the case of timestamp and date though, the type
signature did not match the output datum, which was a DTimestampTZ.
This discrepency between the known type and the actual datum type
in the cases of time and date would cause a panic in distSQL if
the query called date_trunc with a date or timestamp.

This change modifies the built-in date_trunc to change the signature to
the following:

    date_trunc(string, timestamp)   -> timestamp (no change)
    date_trunc(string, timestamptz) -> timestamptz (no change)
    date_trunc(string, time)        -> interval (previously time)
    date_trunc(string, date)        -> timestamptz (previously date)

It also fixes the output for date_trunc(string, timestamp) -> timestamp,
as the output had a timezone (and was actually a timestamptz).

See the following snippet from running the functions in postgres

      postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::timestamp));
                pg_typeof
      -----------------------------
      timestamp without time zone

      postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::date));
              pg_typeof
      --------------------------
      timestamp with time zone

      postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::time));
      pg_typeof
      -----------
      interval

Also mentioned in the PostgreSQL documentation, https://www.postgresql.org/docs/10/static/functions-datetime.html
> source is a value expression of type timestamp or interval. (Values
> of type date and time are cast automatically to timestamp or interval,
> respectively.)

Release note (bug fix): Fix a panic when using
date_trunc(STRING,TIMESTAMP) or date_trunc(STRING,DATE) during queries
that run with the distributed execution engine.

Release note (bug fix): Fixed a bug where date_trunc(STRING,TIMESTAMP)
would return a TIMESTAMPTZ.

Release note (sql change): In order to more accurately match the
behavior of PostgreSQL, the return type of date_trunc(STRING,TIME) was
changed from TIME to INTERVAL, and the return type of
date_trunc(STRING,DATE) was changed from DATE to TIMESTAMPTZ.

### CODE REVIEW

**Comment by lego** [comment]
I ran the logic tests with `-rewrite-results-in-testfiles` and it rewrote results for calls to `date_trunc` depending on the input type. In the case of `Date` inputs, there is no longer any time part.

It also appears that according to the postgres documentation [documentation](https://www.postgresql.org/docs/9.6/static/functions-datetime.html), `date_trunc` is only defined on  `Timestamp`/`TimestampTZ`, and not for `Date`. cc: @rytaft

**Comment by rytaft** [comment]
:lgtm: but cc @dt just in case.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-:-L-b8wej1GwS_tZF2SeF:b-yw9njf)*

**Comment by lego** [comment]
Ah, it seems like postgres may have only defined the `date_trunc` on Timestamp, TimestampTZ, and Interval. For `date` and `time` they are getting casted to `timestamptz` and `interval` respectively.

```
postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::date));
        pg_typeof
--------------------------
 timestamp with time zone
(1 row)

postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::time));
 pg_typeof
-----------
 interval
(1 row)

postgres=# select pg_typeof(date_trunc('month', '2017-04-11 00:00:00'::timestamp));
          pg_typeof
-----------------------------
 timestamp without time zone
(1 row)
```

**Comment by lego** [comment]
So I've changed this to have overloads which will handle this implicit casting behavior in order to match postgres. I also found the snippet to verify this behavior from their docs:
> source is a value expression of type timestamp or interval. (Values of type date and time are cast automatically to timestamp or interval, respectively.)

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sem/builtins/builtins.go, line 1340 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-L-bSwfI3GjdWzcoxRXV:-L-bSwfI3GjdWzcoxRXW:bc23sev) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c9cba755828446f5cfdca3116603f1954beb3a/pkg/sql/sem/builtins/builtins.go#L1340)):*
> ```Go
> 	},
> 
> 	// https://www.postgresql.org/docs/10/static/functions-datetime.html#functions-datetime-trunc
> ```

Please extend both 1) the commit message 2) this comment 
with the pg examples you have in one of the PR comments.
The examples directly contradict the documentation URL which you quote -- that specifies that `date_trunc` always returns `timestamp`, which the examples show to be untrue.

Also extend the PR description to indicate how this should be documented.

Also since this fixes a crash I'd recommend cherry-picking into 1.1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467)*

**Comment by lego** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/builtins/builtins.go, line 1340 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-L-bSwfI3GjdWzcoxRXV:-L-cBmA8qhzVu7hpa0bc:b-x5a7pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/27c9cba755828446f5cfdca3116603f1954beb3a/pkg/sql/sem/builtins/builtins.go#L1340)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please extend both 1) the commit message 2) this comment 
with the pg examples you have in one of the PR comments.
The examples directly contradict the documentation URL which you quote -- that specifies that `date_trunc` always returns `timestamp`, which the examples show to be untrue.

Also extend the PR description to indicate how this should be documented.

Also since this fixes a crash I'd recommend cherry-picking into 1.1.
</blockquote></details>

Done, thanks for pointing this.

---

*[pkg/sql/sem/builtins/builtins.go, line 1349 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-L-cC946kDL8RwjkDtlP:-L-cC946kDL8RwjkDtlQ:b-60qg19) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1187201a1ac36cc0fc707842cd5ef7392dcf9d/pkg/sql/sem/builtins/builtins.go#L1349)):*
> ```Go
> 	//
> 	//  date_trunc(string, time)        -> interval
> 	//  date_trunc(string, date)        -> timestamptz
> ```

I am not very confident about returning a timestamptz here. I could not find anything discussing how timezone vs. no timezone works in postgres, but it seems to be the standard behaviour in postgres that calling date_trunc with a date yields a timestamptz.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467)*

**Comment by knz** [comment]
Re the commit message:

> This change modifies the built-in date_trunc to change the signature to
> the following:
> 
>     date_trunc(string, time) -> interval (previously time)
>     date_trunc(string, date) -> timestamptz (previously date)

this description is inaccurate: the signature *also* includes the original variant `date_trunc(string, timestamp) -> timestamp`

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/builtins/builtins.go, line 1349 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-L-cC946kDL8RwjkDtlP:-L-cHMXrn8TJZWLiPW3y:b-oczldt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1187201a1ac36cc0fc707842cd5ef7392dcf9d/pkg/sql/sem/builtins/builtins.go#L1349)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

I am not very confident about returning a timestamptz here. I could not find anything discussing how timezone vs. no timezone works in postgres, but it seems to be the standard behaviour in postgres that calling date_trunc with a date yields a timestamptz.
</blockquote></details>

Your explanation about implicit casts is ... confusing and probably untrue. If pg was indeed implementing the function only once (in the documented form: from timestamp to timestamp), then *even with implicit cast of the argument the result type should remain the same*. It seems obvious to me from your experiments that pg is actually overloading the function although it doesn't document so, and there is no implicit cast involved.

 I'd say the following, using bullet points:

- pg only documents data_trunc on timestamps (without timezone)
- using a pg client and the `pg_typeof` function, one can readily see that pg is doing more (you can copy-paste your tests here and their results)
- for compatibility, we do the same as pg below, even if it does more than what the doc specify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-:-L-cI9Q2SKOpql-u34-1:b-btab0s)*

**Comment by lego** [comment]
Updated the commit descriptions list to include all date_trunc  signatures.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/sem/builtins/builtins.go, line 1349 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-L-cC946kDL8RwjkDtlP:-L-gP2pu4QM2HAsiRozt:b-tqcy9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1187201a1ac36cc0fc707842cd5ef7392dcf9d/pkg/sql/sem/builtins/builtins.go#L1349)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Your explanation about implicit casts is ... confusing and probably untrue. If pg was indeed implementing the function only once (in the documented form: from timestamp to timestamp), then *even with implicit cast of the argument the result type should remain the same*. It seems obvious to me from your experiments that pg is actually overloading the function although it doesn't document so, and there is no implicit cast involved.

 I'd say the following, using bullet points:

- pg only documents data_trunc on timestamps (without timezone)
- using a pg client and the `pg_typeof` function, one can readily see that pg is doing more (you can copy-paste your tests here and their results)
- for compatibility, we do the same as pg below, even if it does more than what the doc specify.


</blockquote></details>

I updated the comment to hopefully clear up some confusion here. Specifically
- date_trunc is documented on timestamp[tz] and interval
- It is explicitly called out that time will be cast to interval and that a date will cast to a timestamp. 
   
   The part I'm scratching my head over is that it does not specify whether the date casts to a timestamp with or without TZ. By observation, it is with TZ but I do not know if there are settings that change this behavior.


Something I omitted is:
- all functions on time/timestamp without tz are also defined with their corresponding type with tz

I could put it at the top here, although I wasn't sure if this would be the best since this statement applies to all functions that operate on timestamp/time. This is the first line on postgres' datetime functions page, so it is called out well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-:-L-gO73Siyom8fuc1hQo:b-e8iud7)*

**Comment by knz** [comment]
:lgtm_strong:  thank you!!

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20467#-:-L-gWD9wLStcyUQ4j60K:b-u3f0mc)*

**Comment by lego** [comment]
No need to cherrypick to 1.1, these built-ins weren't in it.

Also sorry for the commit churn. The last round was to just re-generate docs.

**Pull request merged**
