### PR TITLE
opt: set all session settings to their global default

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: reformat benchmark slow-queries.sql

Release note: None

#### opt: set all session settings to their global default

All session settings in optimizer tests and benchmarks are now set to
their global defaults. Prior to this commit each new session setting had
to be manually set in both tests and benchmarks. This step could be
forgotten, such as with `optimizer_merge_joins_enabled` which was
unknowingly disabled in benchmarks when it was added. Now, all session
settings with global defaults are automatically set.

Additionally, `sql.SetSessionVariable` has been renamed to
`sql.TestingSetSessionVariable` to discourage its use outside of tests.

NOTE: Now that `optimizer_merge_joins_enabled` is enabled, some
benchmarks will appear to regress.

Epic: None

Release note: None

#### opt: enable implicit SELECT FOR UPDATE locking in opt tests

Implicit `SELECT ... FOR UPDATE` locking has been enabled in optimizer
tests, matching the default value for the corresponding session setting
`enable_implicit_select_for_update`.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I think we may want to backport this to make benchmarks across release branches accurate.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice catch!

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-:-O2WOBtk0fh4LJVqODxF:bqvm1h6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/vars.go` line 3569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-O2WJmXjAR5m8dZtN9ij:-O2WJmXjAR5m8dZtN9ik:b-2eovha) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a527b5cfa84e3b04f3a11398f90a2d23885d396/pkg/sql/vars.go#L3569)):*
> ```Go
> func TestingResetSessionVariables(ctx context.Context, evalCtx eval.Context) (err error) {
> 	sdMutatorBase := sessionDataMutatorBase{
> 		// defaults: make(map[string]string),
> ```

Should this be removed?
___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-O2WO13O2OuWZnuFF6HJ:-O2WO13O2OuWZnuFF6HK:b-9pu7o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7227a606e137387c7eba8345c1ba18ab5c7d9d8c/pkg/sql/opt/testutils/opttester/opt_tester.go#L324)):*
> ```Go
> 	ot.evalCtx.SessionData().OptimizerProveImplicationWithVirtualComputedColumns = true
> 	ot.evalCtx.SessionData().OptimizerPushOffsetIntoIndexJoin = true
> 	ot.evalCtx.SessionData().OptimizerUsePolymorphicParameterFix = true
> ```

Would it be worth adding a test that does `SHOW VARIABLES` with the OptTester to make sure everything is set the way we expect?

**Review by michae2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127652)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-O2WO13O2OuWZnuFF6HJ:-O2WOesz1bcuvEtS4Xu_:b9y7joz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7227a606e137387c7eba8345c1ba18ab5c7d9d8c/pkg/sql/opt/testutils/opttester/opt_tester.go#L324)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Would it be worth adding a test that does `SHOW VARIABLES` with the OptTester to make sure everything is set the way we expect?
</blockquote></details>

(Sorry, I mean `SHOW ALL`.)

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice! Backporting makes sense to me.

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-:-O2Y5nLX7vlUYegV9-CE:bj0ppwv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127652)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/vars.go` line 3569 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-O2WJmXjAR5m8dZtN9ij:-O2_E2o15GRwOQLErH6L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a527b5cfa84e3b04f3a11398f90a2d23885d396/pkg/sql/vars.go#L3569)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 324 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127652#-O2WO13O2OuWZnuFF6HJ:-O2_Di4K7mN4RTcWw6Eb:b-pz5796) ([raw file](https://github.com/cockroachdb/cockroach/blob/7227a606e137387c7eba8345c1ba18ab5c7d9d8c/pkg/sql/opt/testutils/opttester/opt_tester.go#L324)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

(Sorry, I mean `SHOW ALL`.)
</blockquote></details>

We don't start a full SQL server in optimizer tests, so `SHOW ALL` is not supported. We could support it, but I think that's outside the scope here.

**Pull request merged**
