### PR TITLE
ui: switch the /debug/tracez page to React

### PR DESCRIPTION
**Pull request by andreimatei**
This commit adds a single-page component that facilitates viewing active
trances and taking snapshots. The state that this page manages is
entirely self-contained and does not interact with the application's
redux store.

This patch also adds a bunch of tracing-related RPCs backing the new
page.

This new page replaces the pre-existing /debug/tracez page, which is
deleted. The old page used hand-rolled HTML templates, javascript, and a
dubious javascript table library. The new page is more inline with all
the respectable React pages in the DB Console.

Developed with dhartunian.

Release note (ui change): Active operations can now be inspected in a
new page linked from "Advanced Debug".
Release justification: Low risk, pretty important obs feature.

### CODE REVIEW

**Comment by andreimatei** [comment]
Replaces https://github.com/cockroachdb/cockroach/pull/75685.

@dhartunian I've cleaned up your patch, squashed, rebased, etc.
Instead of pushing to your branch, I thought I'd open a new PR.

Give this a stamp and it'll fly.

**Review by dhartunian — COMMENTED** [review]
There are typescript errors in the tsx due to the mismatch in proto names since you edited a few. I marked the changes you'll need.

I see some other typescript issues which are in unrelated files that I don't see obvious causes or solutions to, consider rebasing on `master` if they continue to bug CI.

> Reviewed 3 of 3 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-:-My3I8084bgwq3tjZTUn:b-3fb3rd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3HyB63JUcU40MsH11:-My3HyB63JUcU40MsH12:bkkiwzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L41)):*
> ```XML
> import GetTraceRequest = cockroach.server.serverpb.GetTraceRequest;
> import IGetTraceResponse = cockroach.server.serverpb.IGetTraceResponse;
> import ITag = cockroach.server.serverpb.ITag;
> ```

Rename to `ISpanTag`
___
*[pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3I2kB-RkrMGRd7gzp:-My3I2kB-RkrMGRd7gzq:boen6hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L76)):*
> ```XML
> 
> interface SnapshotRow {
>   span: cockroach.server.serverpb.ISpan;
> ```

Rename all usages to `ITracingSpan` throughout.
___
*[pkg/util/tracing/span_test.go, line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3JmE35uYvrUzIRH_q:-My3JmE35uYvrUzIRH_r:b8r5r4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/util/tracing/span_test.go#L636)):*
> ```Go
> 		TraceID:       traceID,
> 		ParentSpanID:  parentSpanID,
> 		RecordingMode: tracingpb.RecordingMode_STRUCTURED,
> ```

Not sure if it matters, but does this change need to be in the first commit?

**Review by andreimatei — COMMENTED** [review]
> There are typescript errors in the tsx due to the mismatch in proto names since you edited a few. I marked the changes you'll need.

Thanks, fixed. FWIW, the UI did seem to be working even with the errors. That's expected, right? How did you see these errors?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-:-My4YxFiBYf6K51osElh:b-qv5hcy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3HyB63JUcU40MsH11:-My4Wjib-eVeAfvHP6pT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L41)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Rename to `ISpanTag`
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3I2kB-RkrMGRd7gzp:-My4WkCl0_zcnuCmpByf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/ui/workspaces/db-console/src/views/tracez/tracez.tsx#L76)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Rename all usages to `ITracingSpan` throughout.
</blockquote></details>

Done.
___
*[pkg/util/tracing/span_test.go, line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-My3JmE35uYvrUzIRH_q:-My4YGNC7zQdPG3UOrh1:b-suagm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a547f56c9e1dee8931b17c4e11b9577ddee1564c/pkg/util/tracing/span_test.go#L636)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Not sure if it matters, but does this change need to be in the first commit?
</blockquote></details>

yup, moved, thanks.

**Review by dhartunian — APPROVED** [review]
:lgtm:

> Thanks, fixed. FWIW, the UI did seem to be working even with the errors. That's expected, right? How did you see these errors?

Yes, that's expected because you only changed the name of the messages, not the names of fields AFAIK (or at least no names that were used in the JS code). Because the types are erased when you run the TS compiler, you code can still compile into JS and run if you just ignore the output of the type checker.

I see the output of the TS typechecker when I run `make ui-lint`. I am not sure about the bazel support of this build step.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-:-My5Nbie4cq1jZze8qFZ:bz7xc6g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77712#-:-My8g55d0MffpwKtJ0lS:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Pull request merged**
