### PR TITLE
storage: add replicated locks to MVCCStats

### LINKED ISSUE #109645: storage: add replicated locks to MVCCStats
As part of https://github.com/cockroachdb/cockroach/issues/100193, we'll want to start tracking durable locks in the MVCCStats.

In the [Replicated Locks: Implementation Outline](https://docs.google.com/document/d/1_wruMmq5B-Gl8vNJu3QE8WthCMyYSIVVruXTsoLlb0g/edit?usp=sharing) doc, we decided to extend and rename the existing `IntentBytes`, `IntentCount`, and `IntentAge` fields for this purpose. We can then keep `SeparatedIntentCount` (renamed to `IntentCount`) as an intent-specific metric.

Jira issue: CRDB-31029

Epic CRDB-26544

### PR DESCRIPTION
**Pull request by nvb**
Fixes #109645.
Informs #100193.

This commit adds `MVCCStats` for replicated locks.

To do so, it first adds a new field to the stats struct, `LockBytes`. `LockBytes` is the encoded size of replicated locks with shared or exclusive strengths, which are stored in the lock table keyspace. The field includes the size of the locks' keys and their values.

For historical reasons, the field excludes the size of intent metadata key-values, even though they are also stored in the lock table keyspace. Intent metadata keys are tracked under KeyBytes and their values are tracked under ValBytes. This is not to be confused with the provisional versioned values protected by the intents, which are tracked by the IntentBytes field (and also by KeyBytes and ValBytes). Hence the vague "without their meta keys" comment above.

The patch then begins accounting for the contributions of replicated locks to `LockBytes`, `LockCount`, and `LockAge`, of which the second two fields already exist. This accounting is straightforward.

The less straightforward part of the patch is MVCC stats computation. Scanning the lock table requires the use of an EngineIterator. To this point, all stats computation has taken place on an MVCCIterator. The patch addresses this by directly scanning the lock table with an EngineIterator (wrapped in a LockTableIterator) during stats computation.

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 19 of 19 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-:-NfMctgXDlS2AS54UomQ:b593w57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @nvanbenschoten, @renatolabs, and @sumeerbhola)

___
*[`pkg/storage/enginepb/mvcc.proto` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfMac5F2b56gorkNaz_:-NfMac5F2b56gorkNaza:b-2oylo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecef0bcd6c5218acbe81e350cdc1d96b70f9523/pkg/storage/enginepb/mvcc.proto#L213)):*
> ```proto
>   // table keyspace. Intent metadata keys are tracked under key_bytes
>   // and their values are tracked under val_bytes. This is not to be
>   // confused with the provisional versioned values protected by the
> ```

nit: s/protected/locked?

(in the commit message as well)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r1, 15 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-:-NfN60eW8PEOM7J3IiRX:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @herkolategan, @nvanbenschoten, and @renatolabs)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN-tQMESh2GBFFEVUm):*
Is LockAge used somewhere to try to do intent resolution for abandoned locks?
___
*[`-- commits` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN1NR0BFXz5jJoakZf):*
MVCCStats is confusing. I think part of the problem is that the code comments in MVCCStats are written as if (a) the scheme is normal and obvious, (b) there is no example showing older versions, latest version, latest provisional value with an intent and clearly saying where the various bytes will be accounted.
It would be awesome if the comment deficiency could be fixed by this commit, given that it is adding `LockBytes` which also has to behave in a peculiar manner due to the legacy behavior.
___
*[`pkg/storage/mvcc.go` line 1486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN3Eu69ftYfdpHIAte:-NfN3Eu69ftYfdpHIAtf:br9hchb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecef0bcd6c5218acbe81e350cdc1d96b70f9523/pkg/storage/mvcc.go#L1486)):*
> ```Go
> func (b *putBuffer) lockTableKey(
> 	key roachpb.Key, str lock.Strength, txnID uuid.UUID,
> ) (EngineKey, int64) {
> ```

nit: can you name the return value since the meaning of an int64 is not obvious.
___
*[`pkg/storage/enginepb/mvcc.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN08zpBKJmySlXttsj:-NfN08zpBKJmySlXttsk:bnojrqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d02a4e891d9e7eca6290cf8884633c28c497ef/pkg/storage/enginepb/mvcc.go#L137)):*
> ```Go
> 
> 	ms.GCBytesAge += ms.GCBytes() * diffSeconds
> 	ms.LockAge += ms.LockCount * diffSeconds
> ```

what will happen in a mixed version cluster where a newer version node will calculate differently. Is it harmless in that IntentCount==LockCount until the cluster version is updated?

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-:-NfNxiN9AjtfR1DZRN8X:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @herkolategan, @renatolabs, and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN-tQMESh2GBFFEVUm):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is LockAge used somewhere to try to do intent resolution for abandoned locks?
</blockquote></details>

Yes, it is used by the GC queue to score ranges (see `makeMVCCGCQueueScoreImpl`), which determines whether they are queued for processing and, if so, whether they are prioritized. @arulajmani is in the process of hooking the GC queue up to actually resolve abandoned locks.
___
*[`-- commits` line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN1NR0BFXz5jJoakZf):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

MVCCStats is confusing. I think part of the problem is that the code comments in MVCCStats are written as if (a) the scheme is normal and obvious, (b) there is no example showing older versions, latest version, latest provisional value with an intent and clearly saying where the various bytes will be accounted.
It would be awesome if the comment deficiency could be fixed by this commit, given that it is adding `LockBytes` which also has to behave in a peculiar manner due to the legacy behavior.
</blockquote></details>

I agree, but also want to avoid adding a sizable amount of work here to give this documentation effort the time that it deserves. I opened https://github.com/cockroachdb/cockroach/issues/111391 and will commit to spending some time on it once the release branch is cut and we're in stability.
___
*[`pkg/storage/mvcc.go` line 1486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN3Eu69ftYfdpHIAte:-NfNsKPUBEbl-djTBXNQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecef0bcd6c5218acbe81e350cdc1d96b70f9523/pkg/storage/mvcc.go#L1486)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you name the return value since the meaning of an int64 is not obvious.
</blockquote></details>

Done.
___
*[`pkg/storage/enginepb/mvcc.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN08zpBKJmySlXttsj:-NfNpuehCQRabXghld9e:b-8pkqn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d02a4e891d9e7eca6290cf8884633c28c497ef/pkg/storage/enginepb/mvcc.go#L137)):*
> Is it harmless in that IntentCount==LockCount until the cluster version is updated?

Right, until a cluster version is updated and it starts acquiring replicated locks, IntentCount == LockCount. Recall that is just a rename of `SeparatedIntentCount`, performed by https://github.com/cockroachdb/cockroach/pull/110590.

I don't know of any reason why `IntentCount` and `SeparatedIntentCount` would not be the same after [the migration](https://github.com/cockroachdb/cockroach/pull/66445) to clear out interleaved intents. I also looked at a collection of debug.zips to sanity check and did not find any discrepancies. Are you aware of any cases where this equality does not hold?
___
*[`pkg/storage/enginepb/mvcc.proto` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfMac5F2b56gorkNaz_:-NfNsTwqEJsW5AI3L99v:b-x4rp1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/eecef0bcd6c5218acbe81e350cdc1d96b70f9523/pkg/storage/enginepb/mvcc.proto#L213)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/protected/locked?

(in the commit message as well)
</blockquote></details>

I don't think we usually say that the "version is locked", but rather that the "key is locked" and the version is associated with the intent that locks the key. So I think I'll keep "protected" here.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111293)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @herkolategan, @nvanbenschoten, and @renatolabs)

___
*[`pkg/storage/enginepb/mvcc.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111293#-NfN08zpBKJmySlXttsj:-NfRms706eB3A4AXOYj9:bpe5iey) ([raw file](https://github.com/cockroachdb/cockroach/blob/06d02a4e891d9e7eca6290cf8884633c28c497ef/pkg/storage/enginepb/mvcc.go#L137)):*
> Are you aware of any cases where this equality does not hold?

No, not aware of any.

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
