### PR TITLE
tracing,distsql: structure span stat addition to tags and have tableReader use this

### PR DESCRIPTION
**Pull request by asubiotto**
With the addition of stat collection scoped to the query, and more precisely, to a span, we've introduced the problem of how to send these stats back to an interested party. A solution to this needs to be general enough to be used by any level of the stack which crosses out sending stats back as distsql `ProducerMetadata`. The idea then was to add stats as proto messages to a `RecordedSpan`. However, we have many types of possible stats and it's not feasible to have to define a proto every time you want to collect some stats.

The thinking then turned to using a `map[string]int` or something of the sort which ended up with the decision to just use span tags which is represented as a `map[string]interface{}`, but sent over the wire as a `map[string]string` (as part of the RecordedSpan). This solution additionally shows the span stats in opentracing-compliant tracing UIs.

However, this is not as simple as just adding stats to a span once they are collected. The only information a consumer gets is two strings: the stat name and the stat value in some unit representation. There is also no difference between a normal span tag and a span stat tag. Therefore, a light "registry" has been added to the tracing package so that we can store information associated with a span name, allowing the consumer to do things like retrieve all stats from a span, display help text associated with a stat, render the stat in a more human-readable format (e.g. a memory stat was collected in bytes but should be humanized).

@tschottdorf, making you the reviewer since you'll be using some of this when collecting tombstone stats
cc @solongordon

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks good! The dance between the registry and the tags is a little awkward, but I have no great ideas for making it better. Could you make sure to figure out how the cockroach-specific span tags are printed in `SHOW TRACE`? There's likely something awkward there. There's no method to retrieve the tags [on opentracing.Span](https://github.com/opentracing/opentracing-go/blob/6c572c00d1830223701e155de97408483dfcd14a/span.go#L27) and I'm not sure we record the tags into `RecordedSpans` in the first place.

---

Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.go, line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwdBTSDSr3jPH6ZAYX:-LAwdBTSDSr3jPH6ZAYY:bmjxqm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/sql/distsqlrun/processors.go#L535)):*
> ```Go
> 	inputsToDrain []RowSource
> 
> 	// registry is the registry for the stats collected for a processor.
> ```

Mention that it's often nil and what that means.

---

*[pkg/sql/distsqlrun/tablereader.go, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAw_PBl-oP10Nf239op:-LAw_PBn-cTXJzqPz5MK:bpabwa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/sql/distsqlrun/tablereader.go#L309)):*
> ```Go
> // makeInputStats makes an InputStats struct for the tableReader.
> func (tr *tableReader) makeInputStats() InputStats {
> 	return InputStats{
> ```

Make this a static method (it is independent of the tablereader). That also makes it nicer to call it in init.

---

*[pkg/util/tracing/stats.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwWtyy4uOTrq-lAeX9:-LAwWtyy4uOTrq-lAeXA:bx2de2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L32)):*
> ```Go
> 
> // statPrefix is a prefix used on
> const statPrefix = "stat."
> ```

`cockroach.stat.` and make this exported (as it's being referenced in doc).

---

*[pkg/util/tracing/stats.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwWzbZCyoPPUQ4FGYU:-LAwWzbZCyoPPUQ4FGYV:b-rpy6yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L48)):*
> ```Go
> // RegisterStat adds stat to the registry.
> func RegisterStat(stat SpanStatDescriptor) {
> 	spanStatRegistry[stat.Name] = stat
> ```

panic if it's already set.

---

*[pkg/util/tracing/stats.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwX1-J2TD3ZqBT6zb3:-LAwX1-J2TD3ZqBT6zb4:bqdr7c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L51)):*
> ```Go
> }
> 
> // GetStat returns the SpanStatDescriptor associated with name. nil, false is
> ```

`(nil, false)`

---

*[pkg/util/tracing/stats.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwXBE94HRnrsRMGqKi:-LAwXBE94HRnrsRMGqKj:b-w8yuni) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L66)):*
> ```Go
> func SetStat(os opentracing.Span, name string, value interface{}) error {
> 	if _, ok := spanStatRegistry[name]; !ok {
> 		return errors.New("adding unregistered stat")
> ```

Don't want to just panic?

---

*[pkg/util/tracing/stats.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAweXTpCxhUBWezB4Ex:-LAweXTpCxhUBWezB4Ey:b-p7z5d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/util/tracing/stats.go#L47)):*
> ```Go
> var spanStatRegistry = make(map[string]SpanStatDescriptor)
> 
> // RegisterStat adds a stat to the registry.
> ```

Must only be called at init() time.

---

*[pkg/util/tracing/stats.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAweTrECLxzSoLNETzw:-LAweTrECLxzSoLNETzx:b6467vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/util/tracing/stats.go#L65)):*
> // SetStat must previously have been called with a SpanStatDescriptor with a matching name.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-:-LAwenhW-Z6IWJr0TzYN:bdmk0oy)*

**Comment by RaduBerinde** [comment]
CC @andreimatei

**Comment by RaduBerinde** [comment]
> My intuition is that we set the tag on a zipkin shadow span for the zipkin collector which is then converted into jaeger spans here

This sounds right.

An alternative to tags is to make them logs (`LogFields`/`LogKV`). I am not sure how jaeger displays custom log fields (other than the normal "event" one), but I'd be surprised if they don't show up. This option would be useful if we might want to emit the same kinds of stats multiple times within a span (e.g. stats at the beginning and stats at the end).

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/tablereader.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1yAug8DfTZ8U61u6x:-LB1yAug8DfTZ8U61u6y:b-htbe2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/sql/distsqlrun/tablereader.go#L227)):*
> ```Go
> 				sd.Render(fmt.Sprintf("%v", unwrappedVal)),
> 			)
> 			if sp := opentracing.SpanFromContext(tr.ctx); sp != nil {
> ```

[nit] could be set once before `Each`

---

*[pkg/util/tracing/stats.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1xEnF-nmhNVskuK-c:-LB1xEnF-nmhNVskuK-d:blqliwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L35)):*
> ```Go
> 
> // SpanStatDescriptor describes a stat that could be stored in a span's tags.
> type SpanStatDescriptor struct {
> ```

This looks like a weird alternative to having an interface..

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-:-LB1ywAJ-Kb9q2_5AmwA:bh6xd1)*

**Comment by asubiotto** [comment]
Added a commit to print out tags in `SHOW TRACE` PTAL.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.go, line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwdBTSDSr3jPH6ZAYX:-LB1EcpP5KfLFr2-BwLz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/sql/distsqlrun/processors.go#L535)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Mention that it's often nil and what that means.
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwWtyy4uOTrq-lAeX9:-LAy9sAd2s9EkhP45mWW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L32)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The prefix semantically makes sense since it leaks into the stats, and that is a global namespace potentially shared by your whole infrastructure (i.e. stuff that's not cockroach). This is a bit hypothetical at this point, but I'd prefer keeping it.
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwWzbZCyoPPUQ4FGYU:-LAy839-1Ix15UXIoEN7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L48)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

panic if it's already set.
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwX1-J2TD3ZqBT6zb3:-LAy-FCZ0aduDo2IupU0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L51)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`(nil, false)`
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAwXBE94HRnrsRMGqKi:-LAxziyU54KH_hmtKJSe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L66)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Don't want to just panic?
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAweXTpCxhUBWezB4Ex:-LAy9tKQ1JkwFWCuUxei:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/util/tracing/stats.go#L47)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Must only be called at init() time.
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LAweTrECLxzSoLNETzw:-LAxzjgo2TFEyP5lrbXq:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/util/tracing/stats.go#L65)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> // SetStat must previously have been called with a SpanStatDescriptor with a matching name.
</blockquote></details>

Reworded.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-:-LB2JEIvEoKeO5n38ylt:b-4slwqy)*

**Comment by asubiotto** [comment]
Thanks for pointing that out @RaduBerinde. It's an interesting alternative although I'm unclear what information we'd like to emit multiple times. WRT to varying stats, like memory/disk/network I think it's sufficient to output the high watermark in span tags and if we want to do a deeper analysis over time we could (I assume) hook up the metrics to prometheus. The `LogFields` approach seems to be pretty equivalent to the span tags though, and Jaeger definitely displays the log fields (I've seen `event`s displayed). I want to build this right so although I have a bias towards span tags because of this code it might be worth having a more in-depth conversation about `LogField`s.

---

Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/sql/distsqlrun/tablereader.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1yAug8DfTZ8U61u6x:-LB2NPNM-26y7V4FSQKa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f582d8fa2bfb2acf814984ef4012b8d35a181c/pkg/sql/distsqlrun/tablereader.go#L227)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could be set once before `Each`
</blockquote></details>

Done.

---

*[pkg/util/tracing/stats.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1xEnF-nmhNVskuK-c:-LB2NRHD30IFqx3mNgQb:b-pkz839) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This looks like a weird alternative to having an interface..
</blockquote></details>

This started off as an interface but the `SpanStatDescriptor`s will probably be so similar it's unclear to me if it would be better to make it an interface. Do you think it would be better to do so? I don't have a strong opinion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-:-LB2O6gOB-xrRV7kEanh:b-pexb9g)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/util/tracing/stats.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1xEnF-nmhNVskuK-c:-LB2SsaH8nVUWDNlDWYy:b-3qvpu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L35)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This started off as an interface but the `SpanStatDescriptor`s will probably be so similar it's unclear to me if it would be better to make it an interface. Do you think it would be better to do so? I don't have a strong opinion.
</blockquote></details>

You can provide a "base" implementation of the interface here that stores `Name` and `Help` and has a no-op `Render` function. Other implementations can embed it and redefine `Render`, and it can also be used directly where appropriate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042)*

**Comment by andreimatei** [comment]
What's wrong with having a protobuf for all stats hanging from a `RecordedSpan`? It could be a protobuf with [extensions](https://developers.google.com/protocol-buffers/docs/proto#extensions) to be defined by different packages.

---

Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-:-LBMUUO95bypAsxLxy3D:b-3bp6yj)*

**Comment by asubiotto** [comment]
I just imagine it will become something unnecessarily complicated. You need to define where the stats were collected to be able to interpret them (i.e. these memory stats were collected in x processor) and would have to define a proto per object that referenced more generic stats (e.g. these `InputStats`). Then if you have the possibility of many different types of stats (e.g. "this proto is for rocksdb stats", "this one for tablereader stats"), I would imagine there would be a lot of unused fields in each `RecordedSpan`. We could maybe think about a hybrid solution where stats protos in a `RecordedSpan` are described to some extent by its tags, but using span tags for this just seem like a simpler solution.

**Comment by asubiotto** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/util/tracing/stats.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25042#-LB1xEnF-nmhNVskuK-c:-LBRG-101tRGigL2VaI9:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/82a582bd173912a6f8f0a47f2c0f56af1b6a0579/pkg/util/tracing/stats.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You can provide a "base" implementation of the interface here that stores `Name` and `Help` and has a no-op `Render` function. Other implementations can embed it and redefine `Render`, and it can also be used directly where appropriate.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25042)*

**Comment by asubiotto** [comment]
This is no longer a WIP and should be ready for a final review @tschottdorf

**Comment by asubiotto** [comment]
Reworking this PR based off of Andrei's suggestion. This extension approach also gives us a free registry.

**Comment by asubiotto** [comment]
Made a new PR to make the review easier: #25296

**Comment by asubiotto** [comment]
Closing in favor of the new approach: #25296

**Pull request closed without merging**
