### PR TITLE
build,cmd/workload: stop using danhhz/roachperf

### PR DESCRIPTION
**Pull request by danhhz**
roachperf has been merged into roachprod and the danhhz fork's patches
have been merged upstream.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
If you have a sec, can you replace the invocation of `docker run --env=A=B...` with `build/builder.sh env A=B...`? Should fix the agent-bricking-after-cancellation problem.

**Comment by danhhz** [comment]
Possibly dumb question, but how do I pass extra env vars through build/builder.sh? The auth stuff is why I still have the manual one

**Comment by benesch** [comment]
build/builder.sh env VAR=VAL real-command-to-run

(It’s not the most natural pattern, but we do it in a few places.)

**Comment by petermattis** [comment]
:lgtm:

@benesch Is there a reason for having the `roachprod` nightlies in the `roachprod` repo?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-L43fUjy7BxwhLDtEcMi:-L43fUjy7BxwhLDtEcMj:b9hlh5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7539434e70edc061cc93cd0b8c81aed8e3881803/pkg/cmd/workload/teamcity-nightlies.go#L63)):*
> ```Go
> 			exec.Command(`roachprod`, `sync`),
> 			exec.Command(`roachprod`, `put`, clusterName, `./cockroach`, `./cockroach`),
> 			exec.Command(`roachprod`, `put`, clusterName, `./workload`, `./workload`),
> ```

It is sort of recursive that `workload` uses `roachprod` to upload and run `workload`. 

My thinking is that we should create a `nightly` package that contains `*_test.go` files protected with a `nightly` build tag. These tests can exec `roachprod` as necessary, just as `runTeamcityNightlies()` is currently doing. I can prototype this if my words are unclear 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-:-L43elChBYfzVvcl4wJL:b-1r0k89)*

**Comment by benesch** [comment]
@petermattis I ported them from roachperf in the interest of never decreasing test coverage. We should nuke them in favor of @danhhz's work here.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-L43fUjy7BxwhLDtEcMi:-L43kQaT8s-ocyRlQ7xk:bv89rxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7539434e70edc061cc93cd0b8c81aed8e3881803/pkg/cmd/workload/teamcity-nightlies.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It is sort of recursive that `workload` uses `roachprod` to upload and run `workload`. 

My thinking is that we should create a `nightly` package that contains `*_test.go` files protected with a `nightly` build tag. These tests can exec `roachprod` as necessary, just as `runTeamcityNightlies()` is currently doing. I can prototype this if my words are unclear 
</blockquote></details>

Yes, this bothered me too. I like this nightly package a lot.

Ideally we'd call it something other than nightly because it will inevitably contain things that are run both more and less frequently than every night. But I don't have anything better to offer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-:-L43kgY-IiLJFLeAHSZ8:b-x2azxa)*

**Comment by petermattis** [comment]
> @petermattis I ported them from roachperf in the interest of never decreasing test coverage. We should nuke them in favor of @danhhz's work here.

Yes. I don't think anyone is currently using them.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-L43fUjy7BxwhLDtEcMi:-L43lJHsmu1xbTh7OqHt:b-30kyej) ([raw file](https://github.com/cockroachdb/cockroach/blob/7539434e70edc061cc93cd0b8c81aed8e3881803/pkg/cmd/workload/teamcity-nightlies.go#L63)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yes, this bothered me too. I like this nightly package a lot.

Ideally we'd call it something other than nightly because it will inevitably contain things that are run both more and less frequently than every night. But I don't have anything better to offer.
</blockquote></details>

Well, `acceptance` is already taken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-:-L43lGL8eBat9GDcMm7p:bh3trni)*

**Comment by danhhz** [comment]
TFTRs!

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-L43fUjy7BxwhLDtEcMi:-L47m17rl8qEbulgCEsl:b5f885h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7aa61573215d028222fdad15bcc3162285bda575/pkg/cmd/workload/teamcity-nightlies.go#L63)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Well, `acceptance` is already taken.
</blockquote></details>

Totally +1 on this idea. I also realized we want go test compatible output so we can hook it up to go-test-teamcity. This PR is blocking nikhil's partitioning stuff, so I'm going to leave it for a followup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21899#-:-L47mJABNf12_jxHVo8t:bz5mair)*

**Pull request merged**
