### PR TITLE
storage: clean up and rename RangeState

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7256)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 8 files at r1, 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7256)*

**Comment by tschottdorf** [comment]
@tamird you were right about not setting LastIndex in your comment on the parent PR. Good thing that's not the only thing I messed up - I added it in here.

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7256#-:-KKM-eb8khKxDsTj32dj:-553290750)*

**Comment by tamird** [comment]
:lgtm: but there's no hurry here, let @bdarnell take a look.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7256#-:-KKM075ZprEr2HbCSIaQ:916345835)*

**Comment by tschottdorf** [comment]
Sure. Added two more commits to satisfy your previous "ew".

On Wed, Jun 15, 2016 at 10:23 PM Tamir Duberstein <notifications@github.com>
wrote:

> [image: :lgtm:]
> <https://camo2.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67>
> but there's no hurry here, let @bdarnell <https://github.com/bdarnell>
> take a look.
> ------------------------------
>
> Reviewed 2 of 2 files at r3.
> Review status: all files reviewed at latest revision, all discussions
> resolved, some commit checks pending.
> ------------------------------
>
> *Comments from Reviewable
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7256#-:-KKM075ZprEr2HbCSIaQ:916345835>*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7256#issuecomment-226372122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135MnYbZpv5ixdKnQb67Wnt_tbDQroks5qMLONgaJpZM4I23H1>
> .
>
-- 

-- Tobias

**Comment by tamird** [comment]
Reviewed 2 of 6 files at r2, 9 of 9 files at r4, 10 of 10 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7256)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7256#-:-KKOUEENaFWR8o7jm1fF:1417088721)*

**Pull request merged**
