### PR TITLE
storage: Split pkg cloud into cloud interface and cloud impl

### PR DESCRIPTION
**Pull request by adityamaru**
Previously, both the ExternalStorage interface and all the specialized
implementations were in `pkg/storage/cloud`.

This PR moves the interface and factory method signatures to
`pkg/storage/cloud` and all the implementations to
`pkg/storage/cloudimpl`.  The motivation behind this is to ensure that
other packages such `pkg/sql` and `pkg/kv` depend on just the
interface/factory signatures (not the concrete impl) to prevent
dependency cycles.

More concreteley, we need to plumb an InternalExecutor and kv.DB for our
new user scoped file-table storage. This was previously not possible
because of a `pkg/sql -> pkg/storage/cloud ->pkg/sql` cycle. Now, since
the executor will be used in `cloudimpl` this cycle will not occur.

Informs: #47211

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
I will rebase once #50493 is merged. I just wanted to get a CI run in to make sure I haven't botched up the move.

**Review by miretskiy — APPROVED** [review]
> Reviewed 38 of 38 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/storage/cloud/external_storage.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50644#-MAg-7AH0rJPXm8A70xI:-MAg-7AH0rJPXm8A70xJ:bot9k7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/26aa14efae0932ebf0d32fa98eeb9bb176740660/pkg/storage/cloud/external_storage.go#L19)):*
> ```
> // ExternalStorage provides functions t
> ```

You should update the comment "ExternalStorage provides API..."
Also make it very clear that this file should not have any implementation code -- it's for interfaces only.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/storage/cloud/external_storage.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50644#-MAg-7AH0rJPXm8A70xI:-MAl0CkgEm0VqaiUPAkG:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26aa14efae0932ebf0d32fa98eeb9bb176740660/pkg/storage/cloud/external_storage.go#L19)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> // ExternalStorage provides functions t
> ```

You should update the comment "ExternalStorage provides API..."
Also make it very clear that this file should not have any implementation code -- it's for interfaces only.
</blockquote></details>

done.
___
*[pkg/testutils/lint/lint_test.go, line 441 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50644#-MAl0PaaBADojKSaC9V0:-MAl0PabDKQJUGmPSB8t:b-esom52) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f3ac7f5c528bd9f862aaad3de69a5faa21569c/pkg/testutils/lint/lint_test.go#L441)):*
> ```
> cloudimpl
> ```
@miretskiy fyi I had to update the lint allow list for using os.getEnv

**Comment by adityamaru** [comment]
TFTR!

bors r=miretskiy

**Pull request merged**
