### PR TITLE
sql: reduce context allocations related to pausable portals

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: pass current context to pausable portal cleanup funcs

Previously, cleanup functions for pausable portals referenced contexts
from the initial execution of the portal. This was probably incorrect,
though there are no known bugs caused by this. This also caused
unnecessary heap allocations of contexts in some cases.

Release note: None

#### sql: remove namedFunc struct

The `fName` field of the `namedFunc` struct was never read. The entire
struct has been removed and replaced with the `func(context.Context)`
type.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
```
name                                        old time/op    new time/op    delta
EndToEnd/kv-read/vectorize=on/Simple-10        186µs ± 2%     189µs ± 7%    ~     (p=0.436 n=10+10)
EndToEnd/kv-read/vectorize=on/Prepared-10      106µs ± 2%     105µs ± 1%    ~     (p=0.743 n=8+9)
EndToEnd/kv-read/vectorize=off/Simple-10       184µs ± 1%     184µs ± 0%    ~     (p=0.481 n=9+8)
EndToEnd/kv-read/vectorize=off/Prepared-10     103µs ± 1%     104µs ± 2%    ~     (p=0.408 n=8+10)

name                                        old alloc/op   new alloc/op   delta
EndToEnd/kv-read/vectorize=on/Prepared-10     20.7kB ± 0%    20.6kB ± 1%  -0.21%  (p=0.037 n=8+10)
EndToEnd/kv-read/vectorize=on/Simple-10       32.3kB ± 0%    32.3kB ± 0%  -0.09%  (p=0.017 n=10+10)
EndToEnd/kv-read/vectorize=off/Simple-10      33.5kB ± 1%    33.5kB ± 0%    ~     (p=0.269 n=8+8)
EndToEnd/kv-read/vectorize=off/Prepared-10    21.8kB ± 1%    21.8kB ± 1%    ~     (p=0.150 n=10+9)

name                                        old allocs/op  new allocs/op  delta
EndToEnd/kv-read/vectorize=on/Prepared-10        190 ± 0%       189 ± 0%  -0.68%  (p=0.000 n=8+10)
EndToEnd/kv-read/vectorize=off/Prepared-10       182 ± 0%       181 ± 0%  -0.55%  (p=0.000 n=9+8)
EndToEnd/kv-read/vectorize=on/Simple-10          277 ± 0%       276 ± 0%  -0.36%  (p=0.000 n=10+10)
EndToEnd/kv-read/vectorize=off/Simple-10         270 ± 0%       269 ± 0%  -0.32%  (p=0.001 n=8+8)
```

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137741#-:-OESLo1a-5wQ4nygpXkB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137741#-:-OEUHc8KDGVjQji8t9BR:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
