### PR TITLE
ssmemstorage: improve lock contention on RecordStatement

### LINKED ISSUE #55285: sql: refactor appStats to have a RWMutex instead of a Mutex
There are various places in the code where appStats can benefit from acquiring a read lock (such as https://github.com/cockroachdb/cockroach/blob/5965426b8823d60345bb8a5b29503b009777691f/pkg/sql/app_stats.go#L251). We should refactor appStats to start using a RWMutex and acquire read locks wherever appropriate. 

Jira issue: CRDB-3680

### LINKED ISSUE #106789: StatementStatistics: improve lock contention performance
1. This [lock](https://github.com/cockroachdb/cockroach/blob/708e6f052da4efed5a7932fc25c8b84d21a3c48f/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L107) for the stats object is taken for the rest of the method. The lock should be released [here](https://github.com/cockroachdb/cockroach/blob/708e6f052da4efed5a7932fc25c8b84d21a3c48f/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L193) before the insights method is called. 

2. Any computation like converting to string and getting the percentiles should be done before taking the lock to reduce the time the lock needs to be held.

3. Remove [unnecessary set ](https://github.com/cockroachdb/cockroach/blob/708e6f052da4efed5a7932fc25c8b84d21a3c48f/pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go#L166)as it is part of the key. 

Jira issue: CRDB-29716

### PR DESCRIPTION
**Pull request by j82w**
1. The stats object lock was being held even during the insights event
creation and insert which has it's own lock. The insights logic is now
moved above the stats lock.
2. Moved latency calculation outside the stats lock.
3. Moved error code calculation outside the stats lock.
4. ss_mem_storage converted to use a RWMutex. Each object in the map
has it's own lock. Read lock allows mulitple threads to read from the
map at the same time which is the common case. Writes are only done the
first time a statement is seen.

Fixes: #106789, Fixes: https://github.com/cockroachdb/cockroach/issues/55285

```
./dev bench pkg/sql/sqlstats/sslocal -f BenchmarkRecordStatement  --ignore-cache --verbose  --test-args='-test.mutexprofile=mutex_pr.out -test.cpuprofile=cpu_pr.out -test.benchtime=30s' --timeout "10m"
```

```
// Master no changes
BenchmarkRecordStatement/RecordStatement:_Parallelism_10-10         	64775088	       558.8 ns/op
    sql_stats_test.go:655: -- test log scope end --
PASS
================================================================================
INFO: Elapsed time: 37.529s, Critical Path: 37.26s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
//pkg/sql/sqlstats/sslocal:sslocal_test                                  PASSED in 37.2s
```
```
// Changes after the PR
BenchmarkRecordStatement/RecordStatement:_Parallelism_10-10         	67960656	       523.8 ns/op
    sql_stats_test.go:655: -- test log scope end --
PASS
================================================================================
INFO: Elapsed time: 37.031s, Critical Path: 36.69s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
//pkg/sql/sqlstats/sslocal:sslocal_test                                  PASSED in 36.7s
```

Release note (performance improvement): Reduced lock contention on `ssmemstorage.RecordStatement`. This is useful for workloads that execute the same statement concurrently on the same SQL instance.

### CODE REVIEW

**Comment by j82w** [comment]
```
// master
BenchmarkRecordStatement/RecordStatement:_Parallelism_1-10         	181417803	       398.4 ns/op
BenchmarkRecordStatement/RecordStatement:_Parallelism_4-10         	181211433	       397.6 ns/op
BenchmarkRecordStatement/RecordStatement:_Parallelism_10-10         	185404830	       387.5 ns/op
```

```
// Opt: 
BenchmarkRecordStatement/RecordStatement:_Parallelism_1-10         	127601151	       563.6 ns/op
BenchmarkRecordStatement/RecordStatement:_Parallelism_4-10         	128141902	       564.6 ns/op
BenchmarkRecordStatement/RecordStatement:_Parallelism_10-10         	127074118	       565.2 ns/op
```

[profile_PR.out.zip](https://github.com/cockroachdb/cockroach/files/12073089/profile_PR.out.zip)

**Review by maryliag — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5Srv3vyvZEwqHXJ9:-N_e5Srv3vyvZEwqHXJA:bomy29y) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L569)):*
> ```Go
> 	}
> 
> 	// Key does
> ```

key does....? (also add period to your comments, including above)
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5fX3CHohE5vkLvoi:-N_e5fX3CHohE5vkLvoj:b-v0f6qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L581)):*
> ```Go
> 	// doesn't exist yet.
> 	stats, ok := s.mu.stmts[key]
> 	if ok {
> ```

can you combine the two things? so `ok || !createIfNonexistent` ?
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5vHu0-RbMHZZxHzB:-N_e5vHu0-RbMHZZxHzC:b-ia41wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L630)):*
> ```Go
> 
> 	// Avoid taking the full lock
> 	if !createIfNonexistent {
> ```

same comment as above
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5ysBEQ-pUtWeIlD5:-N_e5ysBEQ-pUtWeIlD6:b-ia41wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L651)):*
> ```Go
> 	}
> 
> 	if !createIfNonexistent {
> ```

same comment as above

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5Srv3vyvZEwqHXJ9:-N_eHPBUBRvwC6Pni-xm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L569)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

key does....? (also add period to your comments, including above)
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5fX3CHohE5vkLvoi:-N_eHPSL7Aa1jCc_fWMD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L581)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you combine the two things? so `ok || !createIfNonexistent` ?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5vHu0-RbMHZZxHzB:-N_eHPzU8pHfnGXq2N6H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L630)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.
___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 651 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_e5ysBEQ-pUtWeIlD5:-N_eHQPsAAIbpUeS3Gb1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec86258af6fa1647e27e4cfaa5bdfa779b3e295/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L651)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.

**Comment by xinhaoz** [comment]
*[`pkg/sql/sqlstats/insights/detector.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_eIMHu8S3hYjkuuA7N:-N_eIMHv3bxEyMG4p84l:bdev8dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/92af25b4842acd00daa2a9a7a421eaf260601914/pkg/sql/sqlstats/insights/detector.go#L97)):*
> ```Go
> 	id appstatspb.StmtFingerprintID, shouldFlush bool,
> ) PercentileValues {
> 	// latencySummary.Query might modify its own state (Stream.flush), so a read-write lock is necessary.
> ```

Is this comment no longer true? If so it looks like it needs to be updated.

**Comment by xinhaoz** [comment]
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_eLIJ8BzcIIsiN0y1h:-N_eLIJ8BzcIIsiN0y1i:bojy3fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/92af25b4842acd00daa2a9a7a421eaf260601914/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L982)):*
> ```Go
> 	key sampledPlanKey,
> ) (lastSampled time.Time, found bool) {
> 	s.mu.RLock()
> ```

Should this be the muPlanCache Rlock?

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go` line 982 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_eLIJ8BzcIIsiN0y1h:-N_eNi900GTC_VFYfBOj:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/92af25b4842acd00daa2a9a7a421eaf260601914/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L982)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Should this be the muPlanCache Rlock?
</blockquote></details>

Fixed
___
*[`pkg/sql/sqlstats/insights/detector.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-N_eIMHu8S3hYjkuuA7N:-N_eMf7b4TPsk4BH4JmU:b-49huss) ([raw file](https://github.com/cockroachdb/cockroach/blob/92af25b4842acd00daa2a9a7a421eaf260601914/pkg/sql/sqlstats/insights/detector.go#L97)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Is this comment no longer true? If so it looks like it needs to be updated.
</blockquote></details>

I'll revert it for now. In a future PR the latencySummary should have it's own lock.

**Review by maryliag — APPROVED** [review]
Thank you for looking into this! Really nice changes!
:lgtm: 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106860#-:-N_iHuTl1VnZA_mx9VsS:bv7m35v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Pull request merged**
