### PR TITLE
opt: use pointers to cache index visibility

### PR DESCRIPTION
**Pull request by DrewKimball**
In #111698 we changed the index-visibility cache for a `TableMeta` to use `intsets.Fast` instead of a go map in order to avoid a performance regression. However, since the `small` portion of `intsets.Fast` is copied by value, this could cause the visibility cache of a table to diverge after it is copied. This patch changes the cache to use `intsets.Fast` pointers instead, so that the cache is shared between copies of a `TableMeta` as before.

Informs #111118

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
Impact of this change:
```
I231019 21:53:40.957125 1 (gostd) rand.go:250  [-] 1  random seed: 5911083777914468169
I231019 21:53:41.016806 1 (gostd) rand.go:250  [-] 1  random seed: -26122806702962825
goos: darwin
goarch: arm64
BenchmarkPhases
BenchmarkPhases/many-columns-and-indexes-a
BenchmarkPhases/many-columns-and-indexes-a/Prepared
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4786	    245857 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4842	    243932 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4891	    244530 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4884	    246820 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4813	    246786 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4782	    245970 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4839	    244609 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4886	    243922 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4838	    245166 ns/op	    5504 B/op	      31 allocs/op
BenchmarkPhases/many-columns-and-indexes-a/Prepared/Explore-10 	    4791	    247935 ns/op	    5504 B/op	      31 allocs/op
```
I think this is small enough to justify the extra assurance.

**Comment by DrewKimball** [comment]
Note that a table copy will end up with a different cache if the maps get initialized after the copy. However, this is the same behavior as before. The initial fix.

**Review by mgartner — APPROVED** [review]
> Impact of this change:

Do you have a delta?

:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112727#-:-NhDICZz6C4UbZr0Cj-u:b-o02mk2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
Sorry, I thought I copied it earlier. Here:
```
name                                                   old time/op    new time/op    delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10     244µs ± 1%     246µs ± 1%  +0.84%  (p=0.000 n=10+10)

name                                                   old alloc/op   new alloc/op   delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10    5.46kB ± 0%    5.50kB ± 0%  +0.88%  (p=0.000 n=10+10)

name                                                   old allocs/op  new allocs/op  delta
Phases/many-columns-and-indexes-a/Prepared/Explore-10      29.0 ± 0%      31.0 ± 0%  +6.90%  (p=0.000 n=10+10)
```

**Comment by DrewKimball** [comment]
TFTR!

bors r+

**Pull request merged**
