### PR TITLE
opt/optbuilder: refactor builder.go

### PR DESCRIPTION
**Pull request by rytaft**
`builder.go` was getting too large (well over 1000 lines of code).
This commit breaks `builder.go` up into logical components:

`distinct.go`
`groupby.go` (already refactored in #22917)
`join.go`
`project.go`
`scalar.go`
`select.go`

No code has been modified - just moved around.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-L6NnCYWe71VkAOHgcip:-L6NnCYWe71VkAOHgciq:b8xmqu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea2aaa3da3fd3de2ae07c1daccbba15180cccc2/pkg/sql/opt/optbuilder/groupby.go#L371)):*
> ```Go
> // Here "1" refers to the first item in the SELECT list, "a". The returned index
> // is 0.
> func colIndex(numOriginalCols int, expr tree.Expr, context string) int {
> ```

[nit] I realize this is currently only used by groupby code, but I don't think it belongs here. The example in the comment above has nothing to do with aggregation. Maybe keep it in select.go?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-:-L6Nnt8MBZkj9mvbBFhS:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-L6NnCYWe71VkAOHgcip:-L6NoS-nenMv4VhlEbJZ:bzacs5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea2aaa3da3fd3de2ae07c1daccbba15180cccc2/pkg/sql/opt/optbuilder/groupby.go#L371)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I realize this is currently only used by groupby code, but I don't think it belongs here. The example in the comment above has nothing to do with aggregation. Maybe keep it in select.go?
</blockquote></details>

Maybe put utility functions like this in `builder.go`? Or a separate `util.go`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-:-L6Nom-5-aI1R072lgo1:bnfp4nl)*

**Comment by andy-kimball** [comment]
Thanks for doing this. It will help us keep adding and scaling without ending up with a giant 5k line file!

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-:-L6Nomz9ka4wH9_HYtfC:b2qbbyv)*

**Comment by rytaft** [comment]
:thumbsup: Thanks for the reviews!

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-L6NnCYWe71VkAOHgcip:-L6NvzMVcoxijbyFHxFP:bawbz4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bea2aaa3da3fd3de2ae07c1daccbba15180cccc2/pkg/sql/opt/optbuilder/groupby.go#L371)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe put utility functions like this in `builder.go`? Or a separate `util.go`?
</blockquote></details>

I created `util.go` with this and a few other utility functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23172#-:-L6NwDXY6-2uxrFKdw35:b-1dqzps)*

**Pull request merged**
