### PR TITLE
opt: Improve building and traversing lowest cost expression tree

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains several improvements with how we build and traverse
the lowest cost expression tree (i.e. bestExpr):

1. bestExpr now stores its (lowest cost) children. This improves
   traversal times. More importantly, it will enable us to make more
   complex decisions about what physical properties to require of
   children. For example, the MergeJoin operator will be able to pick
   an arbitrary pair of left/right child expressions to merge.

2. Temporary optimization state is now separate from bestExpr. This
   sets us up to split out memo-related structs into another package.

3. memoGroup and bestExpr optimize for the case where there is only
   one expression in the group, and one bestExpr in the group. This is
   very common, such as in the case of a scalar expression. By storing
   the first expr and the first N best children inline, we avoid
   allocations in the common case.

4. ExprView now use bestExpr to traverse the lowest cost expression
   tree, which is fast because bestExpr now stores its children.

The sum total of these improvements significantly improved the
ExprViewBenchmark:

  name          old time/op   new time/op
  ExprView/0-8  365ns ± 1%    233ns ± 2%

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

Nice improvement!  I think this also makes the traversal logic more clear - having to derive the child required properties each time made things complicated.

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/opt/xform/memo_group.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971#-L7kppysnpFKoZS9onhZ:-L7kppytHSgclzq_TP5I:b-poqbd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87990c935046b301ceb4c0ebd4bc340351ca699/pkg/sql/opt/xform/memo_group.go#L113)):*
> ```Go
> // bestExprCount returns the number of bestExprs in the group.
> func (g *memoGroup) bestExprCount() int {
> 	if g.firstBestExpr.required == 0 {
> ```

[nit] This was a bit confusing at first (I incorrectly thought that 0 means "no properties required"). I'd hide the check behind a `bestExpr.isInitialized()` method and use that, then the intent is clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971#-:-L7kqEVstYEfYJeCltAn:b8upkvh)*

**Comment by andy-kimball** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/xform/memo_group.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971#-L7kppysnpFKoZS9onhZ:-L7l4WM7gcmkYhsC9OBx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d87990c935046b301ceb4c0ebd4bc340351ca699/pkg/sql/opt/xform/memo_group.go#L113)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This was a bit confusing at first (I incorrectly thought that 0 means "no properties required"). I'd hide the check behind a `bestExpr.isInitialized()` method and use that, then the intent is clear.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971)*

**Comment by rytaft** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/best_expr.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971#-L7yWjxJlQiMRXCDI_sJ:-L7yWjxJlQiMRXCDI_sK:bt3myxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/227bfac7761eff07fe9fd01d18583cd3a94e9794/pkg/sql/opt/xform/best_expr.go#L85)):*
> ```Go
> 		return be.initial[nth]
> 	}
> 	return be.remainder[nth-opt.MaxOperands]
> ```

Shouldn't this be `nth-be.initialCount`? What if `initialCount` is less than `opt.MaxOperands`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971)*

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/xform/best_expr.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971#-L7yWjxJlQiMRXCDI_sJ:-L7yZefFj5JGWYCLsrI4:b-w2f4sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/227bfac7761eff07fe9fd01d18583cd3a94e9794/pkg/sql/opt/xform/best_expr.go#L85)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Shouldn't this be `nth-be.initialCount`? What if `initialCount` is less than `opt.MaxOperands`?
</blockquote></details>

If it were less than `opt.MaxOperands` then `be.remainder` wouldn't be used. Only once we've "filled" `be.initial` do we start to add to `be.remainder`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23971)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/best_expr.go, line 85 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23971#-L7yWjxJlQiMRXCDI_sJ:-L7yaK_0CEvAGi_yIaNW:bjtb84p) ([raw file](https://github.com/cockroachdb/cockroach/blob/227bfac7761eff07fe9fd01d18583cd3a94e9794/pkg/sql/opt/xform/best_expr.go#L85)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

If it were less than `opt.MaxOperands` then `be.remainder` wouldn't be used. Only once we've "filled" `be.initial` do we start to add to `be.remainder`.
</blockquote></details>

got it - thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23971)*

**Pull request merged**
