### PR TITLE
keys,storage: delete all references to RaftLastIndexKey

### PR DESCRIPTION
**Pull request by irfansharif**
Our last usage of RaftLastIndexKey was way back in #18717. This was
deprecated then, though never marked as such. It's safe for removal
seeing as how it was an unreplicated key to begin with. We also no
longer have code looking through RaftLastIndexKey (instead we reverse
scan raft log entries to determine the last index).

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-:-LzsJXF9A3JbblzmluDV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/keys/constants.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-LzsJLyk3PIMuU538ty4:-LzsJLyk3PIMuU538ty5:bkuwrq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c434a8dfaf98dee56e00d5f9acaa1b45e78291e2/pkg/keys/constants.go#L118)):*
> ```Go
> 	// LocalRaftHardStateSuffix is the Suffix for the raft HardState.
> 	LocalRaftHardStateSuffix = []byte("rfth")
> 	// LocalRaftLastIndexSuffix is the suffix for raft's last index.
> ```

We usually keep these around with a comment like: `// No longer used; exists only to reserve the key so we don't use it.` For instance, see `LocalRangeFrozenStatusSuffix`.

**Review by irfansharif — COMMENTED** [review]
TFTR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-:-LzsgRpA2Uec7ULiN69-:b-814g87)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @tbg)

___
*[pkg/keys/constants.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-LzsJLyk3PIMuU538ty4:-LzsZfS-1kOA6l-jmrVH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c434a8dfaf98dee56e00d5f9acaa1b45e78291e2/pkg/keys/constants.go#L118)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We usually keep these around with a comment like: `// No longer used; exists only to reserve the key so we don't use it.` For instance, see `LocalRangeFrozenStatusSuffix`.
</blockquote></details>

Done.

**Review by irfansharif — COMMENTED** [review]
I removed the publicly exposed interfaces for other unused/deprecated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-:-LzsgimE7GF2BHopROSs:b-i5l5rk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @tbg)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44554#-:-LzwOMM-0GtBXA1xkuPR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by irfansharif** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/44529. bors retry

**Comment by irfansharif** [comment]
bors retry

**Pull request merged**
