### PR TITLE
sqlinstance: Update instancereader with cache backed by rangefeed

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR adds rangefeed backed cache for the sqlinstance
table. This will prevent the SQL instance lookup code from
making multiple roundtrips. This should have good performance
gains for when we support multi-region for serverless.

Release note (performance improvement): The sqlinstance subsystem
no longer reads from the backing SQL table for every request for
SQL instance details. This will result in improved performance
for when we support multi-region setup for the multi-tenant
architecture.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/sql/catalog/lease/lease_internal_test.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_A5041XlqkROkM2lV:-Mj_A5041XlqkROkM2lW:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/catalog/lease/lease_internal_test.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

?
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_B1QDCO-DvNuUXwq9:-Mj_B1QDCO-DvNuUXwqA:bl5or3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader.go#L77)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	cacheConfig := cache.Config{
> 		Policy: cache.CacheLRU,
> 		ShouldEvict: func(size int, key, value interface{}) bool {
> 			// SQL instance data is expected to stay small enough
> 			// (order of a few KB), so we don't need an eviction strategy
> 			// and can retain cached data indefinitely.
> 			return false
> 		},
> 	}
> 	r.mu.instances = cache.NewUnorderedCache(cacheConfig)
> ```
</details>

why use this data structure if you're never going to evict? Why not just a `*btree.BTree`?
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_COgXEf3Rv_zAazRH:-Mj_COgXEf3Rv_zAazRI:b-vr5z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader.go#L163)):*
> ```Go
> 	}
> 
> 	instancesTablePrefix := r.codec.TablePrefix(uint32(r.tableID))
> ```

Consider tightening this to just the primary  index. 
___
*[pkg/sql/sqlinstance/instancestorage/instancereader_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_D1rO4Avl5JPggkzZ:-Mj_D1rO4Avl5JPggkz_:b1ehqw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader_test.go#L52)):*
> ```Go
> 	tDB := sqlutils.MakeSQLRunner(tc.ServerConn(0))
> 	dbName := t.Name()
> 	s := tc.Server(0)
> ```

The test is failing because rangefeeds aren't enabled on the table used for the test. They are enabled by default on all system table ranges and on all tenant ranges.

See this error:
```
W210914 16:49:20.321486 1529 kv/kvclient/rangefeed/rangefeed.go:228  [rangefeed=sql_instances] 62  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:151: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v21.2/change-data-capture.html#enable-rangefeeds-to-reduce-latency
```

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/sql/sqlinstance/sqlinstance.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MjbS_Pg4-XevhF6nsjO:-MjbS_Pg4-XevhF6nsjP:bqm26hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/sqlinstance.go#L33)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> // AddressResolver exposes API for retrieving the instance address and all live instances for a tenant.
> type AddressResolver interface {
> 	// GetInstance returns the InstanceInfo for a pod given the instance ID.
> 	// Returns a NonExistentInstanceError if an instance with the given ID
> 	// does not exist.
> 	GetInstance(context.Context, base.SQLInstanceID) (InstanceInfo, error)
> 	// GetAllInstances returns a list of all SQL instances for the tenant.
> 	GetAllInstances(context.Context) ([]InstanceInfo, error)
> }
> ```
</details>

I've been thinking about these interface a bit. How would you feel about simplifying the interface like what I have below. I also took a hammer to the type names. Consider reading them as `sqlinstance.Info`, `sqlinstance.InfoIterator`, `sqlinstance.Resolver` etc. 

```go
// Info exposes information on a SQL instance such as ID, network address and
// the associated sqlliveness.SessionID.
type Info struct {
	InstanceID   base.SQLInstanceID
	InstanceAddr string
	SessionID    sqlliveness.SessionID
}

// InfoIterator is used to iterate instance info stored in a resolver. 
type InfoIterator func(Info) error

// Resolver exposes API for retrieving the instance address and all live instances for a tenant.
type Resolver interface {
    // Iterate iterates the set of known, live instances stored in the resolver.
    // From indicates the first instance from which iteration should occur. Iteration
    // proceeds in ascending order, halting after the instance with the largest known
    // instance ID. Returning iterutil.StopIteration will stop the iteration and return
    // no error. 
    Iterate(ctx context.Context, from base.SQLInstanceID, f InfoIterator) error
}

// GetInfo returns the Info for an instance given the instance ID as reported
// by the Resolver. Returns a NonExistentInstanceError if an instance with the given ID
// does not exist.
func GetInfo(ctx context.Context, r Resolver, id base.SQLInstanceID) (Info, error) {
   var ret Info
   if err := r.Iterate(ctx, id, func(info Info) error {
      ret = info
      return iterutil.StopIteration()
   }); err != nil {
      return Info{}, err
   }
   if ret.ID == id {
      return ret, nil
   }
   return Info{}, NonExistentInstanceError
}
```

You can then implement this interface on a slice like:

```go
// Infos is a slice of Info. If it is sorted, it can be used as a Resolver. Calls to
// Iterate have undefined behavior if Infos is not sorted.
type Infos []Info

var _ Resolver = (Infos)(nil)

// Iterate can be used to 
func (infos Infos) Iterate(ctx context.Context, from base.SQLInstanceID, f InfoIterator) error {
    idx := sort.Search(len(infos), func(i int) bool {
        return infos[i].ID >= from
    })
    for i := idx; i < len(infos); i++ {
        if err := f(infos[i]); err != nil {
            if iterutils.Done(err) {
                err = nil
            }
            return err
        }
    }
    return nil
}
```

I think that such an interface will make the cache nicer to use.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rimadeodhar)

___
*[pkg/sql/sqlinstance/sqlinstance.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MjbS_Pg4-XevhF6nsjO:-Mjjn1q6CMQiCnNemsJn:b7e2564) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/sqlinstance.go#L33)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // AddressResolver exposes API for retrieving the instance address and all live instances for a tenant.
> type AddressResolver interface {
> 	// GetInstance returns the InstanceInfo for a pod given the instance ID.
> 	// Returns a NonExistentInstanceError if an instance with the given ID
> 	// does not exist.
> 	GetInstance(context.Context, base.SQLInstanceID) (InstanceInfo, error)
> 	// GetAllInstances returns a list of all SQL instances for the tenant.
> 	GetAllInstances(context.Context) ([]InstanceInfo, error)
> }
> ```
I've been thinking about these interface a bit. How would you feel about simplifying the interface like what I have below. I also took a hammer to the type names. Consider reading them as `sqlinstance.Info`, `sqlinstance.InfoIterator`, `sqlinstance.Resolver` etc. 

```go
// Info exposes information on a SQL instance such as ID, network address and
// the associated sqlliveness.SessionID.
type Info struct {
	InstanceID   base.SQLInstanceID
	InstanceAddr string
	SessionID    sqlliveness.SessionID
}

// InfoIterator is used to iterate instance info stored in a resolver. 
type InfoIterator func(Info) error

// Resolver exposes API for retrieving the instance address and all live instances for a tenant.
type Resolver interface {
    // Iterate iterates the set of known, live instances stored in the resolver.
    // From indicates the first instance from which iteration should occur. Iteration
    // proceeds in ascending order, halting after the instance with the largest known
    // instance ID. Returning iterutil.StopIteration will stop the iteration and return
    // no error. 
    Iterate(ctx context.Context, from base.SQLInstanceID, f InfoIterator) error
}

// GetInfo returns the Info for an instance given the instance ID as reported
// by the Resolver. Returns a NonExistentInstanceError if an instance with the given ID
// does not exist.
func GetInfo(ctx context.Context, r Resolver, id base.SQLInstanceID) (Info, error) {
   var ret Info
   if err := r.Iterate(ctx, id, func(info Info) error {
      ret = info
      return iterutil.StopIteration()
   }); err != nil {
      return Info{}, err
   }
   if ret.ID == id {
      return ret, nil
   }
   return Info{}, NonExistentInstanceError
}
```

You can then implement this interface on a slice like:

```go
// Infos is a slice of Info. If it is sorted, it can be used as a Resolver. Calls to
// Iterate have undefined behavior if Infos is not sorted.
type Infos []Info

var _ Resolver = (Infos)(nil)

// Iterate can be used to 
func (infos Infos) Iterate(ctx context.Context, from base.SQLInstanceID, f InfoIterator) error {
    idx := sort.Search(len(infos), func(i int) bool {
        return infos[i].ID >= from
    })
    for i := idx; i < len(infos); i++ {
        if err := f(infos[i]); err != nil {
            if iterutils.Done(err) {
                err = nil
            }
            return err
        }
    }
    return nil
}
```

I think that such an interface will make the cache nicer to use. 
</blockquote></details>

Maybe its just me, but I find this interface harder to use. Also, I'm kind of averse to updating the external facing API of the `sqlinstance` subsystem for a caching change which should be an internal implementation detail for `sqlinstance`. I could be convinced otherwise if the reason was compelling enough. But in this case, I feel like the original interface is good enough. Thoughts?
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_B1QDCO-DvNuUXwq9:-Mjjnc7y3hucKehmLq37:b95wfak) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader.go#L77)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	cacheConfig := cache.Config{
> 		Policy: cache.CacheLRU,
> 		ShouldEvict: func(size int, key, value interface{}) bool {
> 			// SQL instance data is expected to stay small enough
> 			// (order of a few KB), so we don't need an eviction strategy
> 			// and can retain cached data indefinitely.
> 			return false
> 		},
> 	}
> 	r.mu.instances = cache.NewUnorderedCache(cacheConfig)
> ```
why use this data structure if you're never going to evict? Why not just a `*btree.BTree`?
</blockquote></details>

I just (mistakenly) assumed you use the cache data structure everywhere within the code while caching. I'll update this.
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_COgXEf3Rv_zAazRH:-MjjnkUxCb_XHd79gE8J:bg1r40p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader.go#L163)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Consider tightening this to just the primary  index. 
</blockquote></details>

Please can you elaborate on this? How can I reference just the primary index? All other rangefeeds seems to reference the entire table, is this the recommended approach going forward?
___
*[pkg/sql/sqlinstance/instancestorage/instancereader_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_D1rO4Avl5JPggkzZ:-Mjjns_CA0mhe9gF64eX:b1b3o3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader_test.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The test is failing because rangefeeds aren't enabled on the table used for the test. They are enabled by default on all system table ranges and on all tenant ranges.

See this error:
```
W210914 16:49:20.321486 1529 kv/kvclient/rangefeed/rangefeed.go:228  [rangefeed=sql_instances] 62  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:151: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v21.2/change-data-capture.html#enable-rangefeeds-to-reduce-latency
```
</blockquote></details>

Thanks!! This fixed the test.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

___
*[pkg/server/server_sql.go, line 951 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAaGlp-9nvDs5YzbhY:-MkAaGlp-9nvDs5YzbhZ:bo6xle5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/server/server_sql.go#L951)):*
> ```Go
> 	// sqlInstanceProvider must always be started after sqlLivenessProvider
> 	// as sqlInstanceProvider relies on the session initialized and maintained by
> 	// sqlLivenessProvider
> ```

[nit] period missing
___
*[pkg/sql/sqlinstance/sqlinstance.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MjbS_Pg4-XevhF6nsjO:-MkAca0c3SdKtodCZVmS:bqkec8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/sqlinstance.go#L33)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Maybe its just me, but I find this interface harder to use. Also, I'm kind of averse to updating the external facing API of the `sqlinstance` subsystem for a caching change which should be an internal implementation detail for `sqlinstance`. I could be convinced otherwise if the reason was compelling enough. But in this case, I feel like the original interface is good enough. Thoughts?
</blockquote></details>

FWIW I also think the proposed interface feels harder to use..
___
*[pkg/sql/sqlinstance/sqlinstance.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAgiAEA-5m2e0zzH2q:-MkAgiAEA-5m2e0zzH2r:bzgxr8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/sqlinstance.go#L50)):*
> ```Go
> 	Instance(context.Context) (base.SQLInstanceID, error)
> 	// Start starts the instanceprovider. This will block until
> 	// the instancereader has been started.
> ```

[nit] `instancereader` doesn't mean much in the context of documenting the interface
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAbXFO9ihap9qs4lj7:-MkAbXFO9ihap9qs4lj8:bucmm31) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L101)):*
> ```Go
> 			r.stopper.AddCloser(rf)
> 		}
> 		return r.getStartError()
> ```

[nit] I think it would be cleaner to send the error through the channel
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAakJlDAqkxTZW0L-p:-MkAakJlDAqkxTZW0L-q:b-a2p1qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L110)):*
> ```Go
> 	}
> }
> func (r *Reader) maybeStartRf(ctx context.Context) *rangefeed.RangeFeed {
> ```

[nit] maybeStartRangeFeed. 
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAdMkNEDB0H00IWmm7:-MkAdMkNEDB0H00IWmm8:b385y0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L112)):*
> ```Go
> func (r *Reader) maybeStartRf(ctx context.Context) *rangefeed.RangeFeed {
> 	if r.started() {
> 		// Nothing to do, return
> ```

[nit] We're doing a bunch of stuff to tolerate invalid usage like calling Start twice or calling the other functions without Start; this feels unnecessary.
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAe7s-2Dftie8CNFJ2:-MkAe7s-2Dftie8CNFJ3:b-lpac8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L133)):*
> ```Go
> 		// This event corresponds to a deletion.
> 		if tombstone {
> 			r.updateInstanceMap(instance, true)
> ```

[nit] can just do `r.updateInstanceMap(instance, tombstone)`
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAg1mb4uLXxM4SM5dj:-MkAg1mb4uLXxM4SM5dk:bcxnsna) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L196)):*
> ```Go
> }
> 
> // GetAllInstances implements sqlinstance.AddressResolver interface.
> ```

[nit] It's worth documenting that this implementation does not block (on RPCs or the like). Well, at least when `slReader` is a cached reader but I assume that's the case outside of tests.
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAf-f42Xk0-AEkqILi:-MkAf-f42Xk0-AEkqILj:b-ogi9sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L254)):*
> ```Go
> 
> // getAllInstanceRows returns all instancerow objects contained
> // within the map.
> ```

[nit] add ", in arbitrary order."
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAegNUAksvl4zg3WJm:-MkAegNUAksvl4zg3WJn:b6wzi7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L286)):*
> ```Go
> }
> 
> func (r *Reader) getStartError() error {
> ```

[nit] `checkStarted` might be a better name
___
*[pkg/sql/sqlinstance/instancestorage/instancestorage.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAhN9P2Xe9flg3FUip:-MkAhN9P2Xe9flg3FUiq:bpmd5pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L166)):*
> ```Go
> 		return instancerow{}, errors.Wrapf(err, "could not decode data for instance %d", instanceID)
> 	}
> 	if tombstone {
> ```

[nit] this seems redundant with the Value check above. I'd just ignore the new return.
___
*[pkg/sql/sqlinstance/instancestorage/instancestorage.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAhV-T7qt61dtMiQ0p:-MkAhV-T7qt61dtMiQ0q:b1m4p0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L212)):*
> ```Go
> 		}
> 		if tombstone {
> 			// Corresponds to deleted data, continue.
> ```

[nit] A Scan does not return deleted data. I'd just ignore the new return.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

___
*[pkg/sql/sqlinstance/sqlinstance.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MjbS_Pg4-XevhF6nsjO:-MkCKtlL9Qw8l9e33pBz:b-qge6vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/sqlinstance.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

FWIW I also think the proposed interface feels harder to use..
</blockquote></details>

I buy that :). My motivation was:

1) The returned slice is mutable so either we're going to allocate a new one each time or we need the caller to not mutate it. I am almost definitely over-allergic to allocations. 
2) I was hoping to unify getting a single ID and getting multiple. 

I'm willing to accept neither are worth it.

Let's note that the slice ordering properties if we keep the slice. Ideally it'd be sorted. Also note the mutability properties.
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-Mj_COgXEf3Rv_zAazRH:-MkCLqrN19rk-4IYQu9_:bg5mgql) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9d127204cffa87cda55b546245ecf6c19f26f8/pkg/sql/sqlinstance/instancestorage/instancereader.go#L163)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Please can you elaborate on this? How can I reference just the primary index? All other rangefeeds seems to reference the entire table, is this the recommended approach going forward?
</blockquote></details>

I think in the other cases it's just being sort of lazy and knowing that we only have a single index, the primary index. That's the case here too. It's interesting to think about what it would mean to run a schema change on this table in subsequent releases. The method would be `codec.IndexPrefix` and in this case, the primary index is `1`. 


In light of schema changes, we'd need to consider taking a catalog.TableDescriptor or something like that. Definitely future work. For now the whole table and the index are synonymous.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAbXFO9ihap9qs4lj7:-MkNuHTv57gJTC2SOgzJ:bh45k9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think it would be cleaner to send the error through the channel
</blockquote></details>

I have kept it separate as we reuse this method elsewhere to return an error if the `Start` method hasn't been called/returns an error. 
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MkAdMkNEDB0H00IWmm7:-MkNu3d9DIQAuBnrRLxV:b-cwtw1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8e757063ca2f3fb11255ab282cfc7a19bea76d0/pkg/sql/sqlinstance/instancestorage/instancereader.go#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We're doing a bunch of stuff to tolerate invalid usage like calling Start twice or calling the other functions without Start; this feels unnecessary.
</blockquote></details>

I agree, but it feels like it would be necessary though as the functionality executed in Start() is critical to the `Reader` working correctly for other methods.

**Review by rimadeodhar — COMMENTED** [review]
Updated the PR based on the comments so far. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-:-MkNuVv-9AzHEI7ad7Gq:b3qd2jw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

**Review by rimadeodhar — COMMENTED** [review]
@ajwerner: Gentle ping for a review. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-:-MkriVDb1FshfqffFbRm:bk2lefg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

**Review by ajwerner — COMMENTED** [review]
Sorry it took me so long to get back to this :sweat: 

> Reviewed 1 of 11 files at r1, 1 of 7 files at r2, 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-:-MmtC3hdBfSYAwh9T65S:bthbdxv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rimadeodhar)

___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MmtBsFsB3Gr00gE5qXE:-MmtBsFsB3Gr00gE5qXF:bxcbug1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5727bbebbe3028c4e7c70c2074b7a45d273ef415/pkg/sql/sqlinstance/instancestorage/instancereader.go#L96)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	case <-r.initialScanDone:
> 		if rf != nil {
> 			// Add rangefeed to the stopper to ensure it
> 			// is shutdown correctly.
> 			r.stopper.AddCloser(rf)
> 		}
> 		return r.checkStarted()
> ```
</details>

FWIW: this means that starting the subsystem is a synchronous scan. I'm not sure we need that. Perhaps a TODO or something to make the waiting for an initial scan lazy until calls to read? 
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MmtBdoI3sCOGn0M11I9:-MmtBdoI3sCOGn0M11IA:b-hbrjpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5727bbebbe3028c4e7c70c2074b7a45d273ef415/pkg/sql/sqlinstance/instancestorage/instancereader.go#L124)):*
> ```Go
> 		})
> 		if err != nil {
> 			log.Ops.Warningf(ctx, "failed to decode settings row %v: %v", keyVal.Key, err)
> ```

return?
___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MmtB-7O8EgCjU2NKV4J:-MmtB-7O8EgCjU2NKV4K:bq2emsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5727bbebbe3028c4e7c70c2074b7a45d273ef415/pkg/sql/sqlinstance/instancestorage/instancereader.go#L154)):*
> ```Go
> 		EndKey: instancesTablePrefix.PrefixEnd(),
> 	}
> 	rf, err := r.f.RangeFeed(ctx, "sql_instances", instancesTableSpan, r.clock.Now(), updateCacheFn, rangefeed.WithInitialScan(initialScanDoneFn), rangefeed.WithOnInitialScanError(initialScanErrFn))
> ```

nit: wrap this

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/sqlinstance/instancestorage/instancereader.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MmtBsFsB3Gr00gE5qXE:-MmxV2-I6c-shPUjiESM:b-gxrcfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5727bbebbe3028c4e7c70c2074b7a45d273ef415/pkg/sql/sqlinstance/instancestorage/instancereader.go#L96)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	case <-r.initialScanDone:
> 		if rf != nil {
> 			// Add rangefeed to the stopper to ensure it
> 			// is shutdown correctly.
> 			r.stopper.AddCloser(rf)
> 		}
> 		return r.checkStarted()
> ```
FWIW: this means that starting the subsystem is a synchronous scan. I'm not sure we need that. Perhaps a TODO or something to make the waiting for an initial scan lazy until calls to read? 
</blockquote></details>

Okay, I have added a TODO for now. Will make a followup PR with the change.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-:-Mmxb1HUCFHqlhg0yleM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69976)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @RaduBerinde, and @rimadeodhar)

___
*[pkg/sql/sqlinstance/instancestorage/instancereader_test.go, line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69976#-MmxlKaU6Cwo5PFhHdn1:-MmxlKaU6Cwo5PFhHdn2:bhzc5sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e63022d59f67b7b523bd0c72a1641932f9b8076/pkg/sql/sqlinstance/instancestorage/instancereader_test.go#L272)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> 				if err != sqlinstance.NonExistentInstanceError {
> 					return errors.Newf("expected non existent instance error")
> 				}
> 				return nil
> 			})
> 		}
> 		// Verify request for instance with expired session results in an error.
> 		{
> 			err := slStorage.Delete(ctx, sessionIDs[1])
> 			if err != nil {
> 				t.Fatal(err)
> 			}
> 			testutils.SucceedsSoon(t, func() error {
> 				_, err = reader.GetInstance(ctx, instanceIDs[0])
> 				if err != sqlinstance.NonExistentInstanceError {
> ```
</details>

the linter wants `errors.Is` here

**Comment by rimadeodhar** [comment]
Yes, if the only blocker to run GetAllInstances every time was caching, then you can go ahead and make the change. The `sqlinstance` subsystem caches all instance data and `GetAllInstances` simply retrieves the data from the cache without issuing any SQL queries.

**Pull request merged**
