### PR TITLE
kvclient: add `ReturnOnRangeBoundary` request field 

### LINKED ISSUE #70564: kvclient: return partial DistSender responses on range boundaries when paginating
In an [internal Slack thread](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1630007804010500), @dt argues that when the client has requested pagination via `MaxSpanRequestKeys` or `TargetBytes` limits, DistSender should return partial results (if any) when encountering a range boundary rather than adjusting the limits and sending additional requests to subsequent ranges. The rationale is that DistSender can otherwise end up sending requests with very small limits, resulting in a larger number of range requests overall as the client paginates over the entire span.

Since the client must already be prepared to handle `ResumeSpan`, it should not make any difference if one is returned early. However, we must audit callers to make sure this is always the case -- in particular, a SQL `LIMIT` clause must not simply be passed through to DistSender with the expectation that the response will always be filled up to the limit.

Broadly, the DistSender logic would be as follows: when encountering a range boundary, if `MaxSpanRequestKeys` or `TargetBytes` is set and a partial response has been obtained, immediately return the response with an appropriate `ResumeSpan` and `ResumeReason: RESUME_RANGE_BOUNDARY`.

Related to ongoing work for #68050 in #68370.

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch adds an option `ReturnOnRangeBoundary` which causes
DistSender to return partial non-empty responses on range boundaries
with reason `RESUME_RANGE_BOUNDARY`. This avoids sending requests with
small remaining limits to subsequent ranges, which would increase the
overall number of range RPC requests. It is opt-in because it could be
detrimental in some cases, e.g. with large batches of `Get` requests.

A version gate is not included, since this change is entirely on the KV
client side: the caller and the DistSender are assumed to be upgraded in
sync.

Resolves #70564.
Touches #47044.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[pkg/kv/kvserver/batcheval/cmd_export_test.go, line 359 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkbV-fl5Uhr0HGQGTTV:-MkbV-fl5Uhr0HGQGTTW:b-i7ik3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d973123a3322e5b4c601bc5c03ee8be17e00f578/pkg/kv/kvserver/batcheval/cmd_export_test.go#L359)):*
> ```
> 		// No TargetSize and TargetBytes is equal to the size of a single KV. This
> 		// will end up exporting the entire set of KVs, but with an incorrect
> 		// NumBytes equal to the requested TargetBytes.
> ```

@dt FYI, we're retaining this behavior for backwards compatibility with older DistSender clients, but we should consider revamping this -- either using a version gate, or waiting for the 22.2 release cycle.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @erikgrinaker)

___
*[-- commits, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcrKSbDZ4G8ZNwuPCx):*
Consider whether what you're doing here can play a role in #47044

FWIW, we used to have a mechanism for a range-limited scan - #19300. I think it got removed because nobody used it. I don't remember how it interacted with the maximum key limit. Perhaps what you're doing here is the same as that, but you're making it the only option? Perhaps peruse for inspiration.
___
*[-- commits, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcvDpZ4FE9WKJClNUi):*
I think making this the default for large scans if OK, but I'm not sure about the lookup-join batches for 10k gets. With a `Get` per range, I'd like the `DistSender` to do more work than a single one of them... How about making this short-read behavior optional, and making it the default for scans done through the `{DB,Txn}.Scan()` method?
In any case, I think I'd prefer the short reads to be explicitly configured (even if they're the default) because introducing a new `struct` with such options will open the door to extending the mechanism to let the client ask for a read to be cut short when a conflicting lock is hit.

WDYT?+
___
*[pkg/kv/txn.go, line 544 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcphKl4TccuO9F9e4o:-MkcphKl4TccuO9F9e4p:b-mec47i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf13fae6dbf82a3b23aa104f81b720cba540abc/pkg/kv/txn.go#L544)):*
> ```Go
> //
> // The returned []KeyValue will contain up to maxRows elements (or all results
> // when zero is supplied). NB: even if there are further results, it is not
> ```

these comments are in the wrong commit, right? Let's set them straight.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1357 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkctQHzAYRkqz_GwuU0:-MkctQHzAYRkqz_GwuU1:b-um2wuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b61859e68e31fb2cfb3a4ecc04666a24c6273e8b/pkg/kv/kvclient/kvcoord/dist_sender.go#L1357)):*
> ```Go
> 						return
> 					}
> 					hasResults = hasResults || h.NumKeys > 0 || h.NumBytes > 0
> ```

is the `|| h.NumBytes` part necessary? Can `h.numKeys` be != 0 and `h.NumBytes` be > 0?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[-- commits, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcrKSbDZ4G8ZNwuPCx):*
> Consider whether what you're doing here can play a role in #47044

Thanks for the pointer. I need to understand a little better what the specific problem there is, but I'll make sure we address that issue while we're working on this anyway.

> Perhaps what you're doing here is the same as that, but you're making it the only option? Perhaps peruse for inspiration.

Thanks, this is useful.
___
*[-- commits, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcvDpZ4FE9WKJClNUi):*
> I think making this the default for large scans if OK, but I'm not sure about the lookup-join batches for 10k gets.

Right, the overhead could get pretty bad in that case. And I guess those batches would at the very least use `TargetBytes` to avoid memory blowup, which would trigger the range boundary behavior.

> How about making this short-read behavior optional, and making it the default for scans done through the `{DB,Txn}.Scan()` method?

I was hoping to avoid another option here, since the number of option combinations surrounding this stuff is sort of blowing up -- especially when #68370 lands. But if we can't avoid it then so be it. I'll have a look.

Do you have any opinions on this @dt?
___
*[pkg/kv/txn.go, line 544 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcphKl4TccuO9F9e4o:-Mkff3mx8_Se0ZNQAvPh:b-ubb87g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecf13fae6dbf82a3b23aa104f81b720cba540abc/pkg/kv/txn.go#L544)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

these comments are in the wrong commit, right? Let's set them straight.
</blockquote></details>

Good catch, thanks.
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1357 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkctQHzAYRkqz_GwuU0:-Mkff7Y27J7SdjG7rK9u:bl3cxu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b61859e68e31fb2cfb3a4ecc04666a24c6273e8b/pkg/kv/kvclient/kvcoord/dist_sender.go#L1357)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is the `|| h.NumBytes` part necessary? Can `h.numKeys` be != 0 and `h.NumBytes` be > 0?
</blockquote></details>

Are all non-empty responses guaranteed to set `NumKeys`?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @dt)

___
*[-- commits, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MkcvDpZ4FE9WKJClNUi):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> I think making this the default for large scans if OK, but I'm not sure about the lookup-join batches for 10k gets.

Right, the overhead could get pretty bad in that case. And I guess those batches would at the very least use `TargetBytes` to avoid memory blowup, which would trigger the range boundary behavior.

> How about making this short-read behavior optional, and making it the default for scans done through the `{DB,Txn}.Scan()` method?

I was hoping to avoid another option here, since the number of option combinations surrounding this stuff is sort of blowing up -- especially when #68370 lands. But if we can't avoid it then so be it. I'll have a look.

Do you have any opinions on this @dt?
</blockquote></details>

Added an option `ReturnOnRangeBoundary` for this, and rebased on top of #68370 -- PTAL. Let's keep it opt-in for now, to be conservative.

**Comment by erikgrinaker** [comment]
Wrote a [benchmark](https://github.com/cockroachdb/cockroach/blob/1bd6317f4c03dc7c2145c4f19e28d2c94c33ccd2/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L3157-L3158) to compare the cost of additional DistSender RPCs against the cost of additional sender stack traversals when scanning across a set of ranges within a transaction. Parameters:

```go
Ranges                = 10   // number of ranges to create
KeysPerRange          = 9    // number of keys to write per range
MaxSpanRequestKeys    = 10   // max number of keys in each scan response
ReturnOnRangeBoundary = true // if true, enable ReturnOnRangeBoundary
Latency               = 0    // additional RPC request latency
```

This favors `ReturnOnRangeBoundary`, since the old behavior will have to do about twice as many RPC requests overall -- it will e.g. fetch 9 rows from range 1 and then go to range 2 only to fetch a single row. Results, where old/new is `ReturnOnRangeBoundary = false/true`, and the `Latency` results are with additional RPC latency (1ms is roughly inter-AZ latency, 5ms simulates additional IO latency):

```
name                              old time/op  new time/op  delta
ReturnOnRangeBoundary              616µs ± 4%   386µs ± 3%  -37.31%  (p=0.000 n=9+10)
ReturnOnRangeBoundary-1msLatency  23.7ms ± 3%  13.5ms ± 3%  -42.99%  (p=0.000 n=10+9)
ReturnOnRangeBoundary-5msLatency   102ms ± 2%    57ms ± 1%  -44.45%  (p=0.000 n=10+9)
```

If we instead favor the old behavior by allowing it to gather all results in one go with `MaxSpanRequestKeys = 100` while the new behavior has to traverse the sender stack for each range, we find:

```
name                              old time/op  new time/op  delta
ReturnOnRangeBoundary              311µs ± 3%   386µs ± 1%  +24.19%  (p=0.000 n=10+8)
ReturnOnRangeBoundary-1msLatency  13.0ms ± 1%  13.8ms ± 8%  +6.71%   (p=0.000 n=9+10)
ReturnOnRangeBoundary-5msLatency  55.6ms ± 2%  56.0ms ± 1%   ~       (p=0.113 n=10+9)
```

Thus, with negligible request latency the tradeoff is highly dependant on how the spans, limits and range boundaries overlap, which the caller must take into account. However, as request latency increases, the relative worst-case cost of `ReturnOnRangeBoundary` approaches 0.

**Comment by erikgrinaker** [comment]
Friendly ping for reviews.

@andreimatei Can you look this over, or let me know if I should reassign to someone else on KV?
@dt Does this cover Bulk's needs?
@RaduBerinde Does this cover SQL's needs for #47044?

**Comment by dt** [comment]
> @dt Does this cover Bulk's needs?
Looks great, should get us the current behavior but without tricking with ExportResponse's fake sizes -- so much cleaner, thanks!

(I only looked at the diff in api.proto and dist_sender.go, so leaving review/approving to a KV reviewer)

**Review by andreimatei — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-:-MoFp9EsDl8xqCnfF3Px:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @dt, @erikgrinaker, and @RaduBerinde)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1386 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFobRL0ZNoI1n-N1L4:-MoFobRL0ZNoI1n-N1L5:b-l7jt7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/kv/kvclient/kvcoord/dist_sender.go#L1386)):*
I think the code is fine, but I'm fairly confused about this comment. 

>  and so the generated resume span won't hit this range again anyway.

What is this telling me? Is this about the code above or the code below?
Perhaps if you explain to me in... different words... what we're talking about, I might have suggestions for making it clear.
___
*[pkg/roachpb/api.proto, line 2163 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFmyTw7eJVV3u8NKmS:-MoFmyTw7eJVV3u8NKmT:b-1nrgsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/roachpb/api.proto#L2163)):*
> ```
> requests with very small remaining limits to subsequent ranges
> ```

Consider spelling out more about what you mean, otherwise I think readers will not understand; make the connection with `TargetBytes`.
___
*[pkg/roachpb/api.proto, line 2168 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFmaUE4tDoB_w5aPXE:-MoFmaUE4tDoB_w5aPXF:b9yc0ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/roachpb/api.proto#L2168)):*
>   //  this relative cost
>  // approaches zero as range RPC request latency increases above 1 ms.


nit: for my personal taste, I would not include this kind of subjective judgement in this API comment.
___
*[pkg/server/server_test.go, line 439 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFnIwk1KS41ArFt0mo:-MoFnIwk1KS41ArFt0mp:b-9vky00) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/server/server_test.go#L439)):*
> ```Go
> // and/or TargetBytes to break up result sets works properly, even across
> // ranges.
> func TestMultiRangeScanWithPagination(t *testing.T) {
> ```

wow what is this test doing in the `server` package? Consider taking the opportunity to move it into KV.
Also the test above it. What were people thinking in 2014.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70763)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @dt, and @RaduBerinde)

___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 1386 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFobRL0ZNoI1n-N1L4:-MoFutC0Crgld6QqMvxE:bosl1pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/kv/kvclient/kvcoord/dist_sender.go#L1386)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the code is fine, but I'm fairly confused about this comment. 

>  and so the generated resume span won't hit this range again anyway.

What is this telling me? Is this about the code above or the code below?
Perhaps if you explain to me in... different words... what we're talking about, I might have suggestions for making it clear.

</blockquote></details>

The comment likely isn't necessary -- I'll remove it.

It applies to the edge case where a range request exactly hits a configured limit, but does not exceed it. In that case, the range response itself will not have a resume span, but we'll generate a resume span for the batch response above because the limit has been hit exactly. For that resume span, we somewhat arbitrarily prefer `RESUME_BYTE_LIMIT` over `RESUME_RANGE_BOUNDARY`. The comment attempts to clarify that these two options are functionally equivalent. There is no risk of hitting the previous range again with what would be a futile request by preferring the resource limit over the range boundary, since the range request must have exhausted the range already (otherwise its response would have included a resume span). But I suppose that's obvious, and I think you're right that it's more confusing than helpful.
___
*[pkg/roachpb/api.proto, line 2163 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFmyTw7eJVV3u8NKmS:-MoG2TfvBlTKCMvXB0GU:b-y1o4qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/roachpb/api.proto#L2163)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> requests with very small remaining limits to subsequent ranges
> ```

Consider spelling out more about what you mean, otherwise I think readers will not understand; make the connection with `TargetBytes`.

</blockquote></details>

Thanks, I've expanded the comment a bit.
___
*[pkg/roachpb/api.proto, line 2168 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFmaUE4tDoB_w5aPXE:-MoFyL_Z2vfeSAuRlkcc:b-fdjpwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/roachpb/api.proto#L2168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

>   //  this relative cost
>  // approaches zero as range RPC request latency increases above 1 ms.


nit: for my personal taste, I would not include this kind of subjective judgement in this API comment.
</blockquote></details>

It isn't subjective, the benchmark results above demonstrate it: with no request latency we see ~25% overhead in the worst case (when the overall number of requests is not decreased), at 1ms latency that's reduced to ~5%, and at 5ms latency the overhead is ~0%.

It was meant to provide a rule of thumb for when it's appropriate to enable this (requests that take >1ms, e.g. scans but not gets). But perhaps we're better off asking users to run their own benchmarks.
___
*[pkg/server/server_test.go, line 439 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/70763#-MoFnIwk1KS41ArFt0mo:-MoG4XhtCcy7H4_ZXGGw:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bc94ef03d468aef567a65f88364e5e3e80d5178/pkg/server/server_test.go#L439)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wow what is this test doing in the `server` package? Consider taking the opportunity to move it into KV.
Also the test above it. What were people thinking in 2014.
</blockquote></details>

Good catch, done.

**Comment by erikgrinaker** [comment]
TFTRs!

bors r=andreimatei,dt

**Pull request merged**
