### PR TITLE
sql/parser: Add TypeEqual method to Datum and use during type checking

### LINKED ISSUE #4075: Datum is not always comparable, but it's possible to cause the comparison and crash CockroachDB
The Datum type `DTuple` is not [comparable](https://golang.org/ref/spec#Comparison_operators) because it contains a slice. Still, throughout the TypeCheck routines, we compare sentinel variables of Datum (`DummyInt`, `DummyTuple`, etc.) to check/work with expressions' types. Whenever these comparisons are made between incomparable types, the type checking will panic and bring down the server.

Examples of queries that will currently cause this to crash:
- `SELECT CASE true WHEN true THEN (4, 4) ELSE (2,3) END;` will break [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L111) and [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L121)
- `SELECT NULLIF((1,2), (3,4));` will break [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L369)

While these two cases could be fixed pretty easily for `DTuple`, these crashes are a symptom of a more serious issue, which arose when I introduced an incomparable [DDecimal](https://github.com/cockroachdb/cockroach/pull/4045#issuecomment-177754419) Datum type. With a "non-special" incomparable type, a number of Datum comparisons also have the potential to fail (e.g. [here](https://github.com/cockroachdb/cockroach/blob/master/sql/values.go#L60) and [here](https://github.com/cockroachdb/cockroach/blob/master/sql/table.go#L161)). The required fix to this would be to either to:

- Rethink our TypeChecking approach, potentially passing around [`reflect.Value`](https://golang.org/pkg/reflect/#Value)s instead of sentinel Datum values to signify Datum types. This is a fairly invasive change, and would require us to rework a number of functions we share between the type checking stage and the evaluation stage, like [`foldComparisonExpr `](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L592). The performance impacts of extensive use of reflection are also not clear at this point. Note that it would not be possible to pass around `reflect.Type`s (although this is what should be compared), because of the need for the contained types in containers like `DTuple` to be inspected and recursively compared using [`Value.Index`](https://golang.org/pkg/reflect/#Value.Index).
- Guarantee that two incomparable types are never compared directly. This would continue to allow the type checking phase to pass around `Datum` and continue to allow comparisons against "safe" sentinel values (like `DNull` and `DummyDecimal`). However, whenever comparing two unknown Datum (often results of sub-`TypeCheck` calls) or whenever comparing against unsafe datum types (we currently never do the latter), we would need to make the comparison indirectly. This could either be by comparing reflect types like `reflect.TypeOf(a) == reflect.TypeOf(b)` or by comparing type strings like `a.Type() == b.Type()`. This way feels a lot more hacky, but at the moment would only require four changes across the code base. Still, I'm wary about fixing this issue so indirectly.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #4075.

The commit also adds unit tests for 4 different queries that previously would have caused type checking to panic.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4082)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM. Consider introducing another function that also returns `true` if the argument is `DNull` - that might reduce some boilerplate.

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/datum.go, line 746 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-K9XmcXy2TVfd0BdMkuN:-K9XmcXy2TVfd0BdMkuO:-2018713084) ([raw file](https://github.com/cockroachdb/cockroach/blob/c00c9426b78acfcbf1107370d94efe118f19721c/sql/parser/datum.go#L746)):*
Should this recursively check the equality of the tuple elements? Does doing so break anything?

---

*[sql/parser/type_check.go, line 147 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-K9Xn1BzERORdZrzlOd1:-K9Xn1BzERORdZrzlOd2:1722788328) ([raw file](https://github.com/cockroachdb/cockroach/blob/c00c9426b78acfcbf1107370d94efe118f19721c/sql/parser/type_check.go#L147)):*
Should pull these slices out into globals so that they are not allocated on each call to `CastExpr.TypeCheck()`. Something along the lines of `var boolCastTypes []Datum{...}`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-:-K9XnICKRq6gWgT4DSG_:676834233)*

**Comment by nvanbenschoten** [comment]
@tamird It would get a little messy because half the time we're actually checking if the receiver is `DNull`. We could flip around the receiver and arg in these cases, but for correctness going down this path, we would need to litter these methods with `DNull` handling, and potentially even propagate these situations back. Probably easier to just let the caller deal with `DNull` however they want when necessary.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/datum.go, line 746 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-K9XmcXy2TVfd0BdMkuN:-K9XqAfkAEffusA6xak0:1257563646) ([raw file](https://github.com/cockroachdb/cockroach/blob/c00c9426b78acfcbf1107370d94efe118f19721c/sql/parser/datum.go#L746)):*
Doing so doesn't break anything because we never try to compare against `dummyTuple` and I don't think it ever would make sense to because a tuple of (INT, INT) is a different type than (INT, FLOAT), which are both obviously different than an empty tuple. Done.

---

*[sql/parser/type_check.go, line 147 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-K9Xn1BzERORdZrzlOd1:-K9XppsB6sNMixH34fXo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c00c9426b78acfcbf1107370d94efe118f19721c/sql/parser/type_check.go#L147)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4082#-:-K9XqxdVNkMZHCUJB-R3:-1830312066)*

**Comment by mjibson** [comment]
I just thought of this now: it is possible that ValArgs should always panic (or something) because there is no case when a DValArg should be compared to anything. A DValArg isn't a valid type when you are checking function arguments or other stuff, for example.

**Comment by nvanbenschoten** [comment]
I would support always returning false for `DValArg.TypeEqual`, even if other Datum is another `DValArg`, but I don't think it should panic.

**Comment by mjibson** [comment]
I like the always false idea. However it breaks some stuff so I'll look into it.

**Pull request merged**
