### PR TITLE
workload: don't retry endlessly the prepation phase of TPCC

### PR DESCRIPTION
**Pull request by andreimatei**
Stop retrying the load-generator-creation phase of workload after 10m,
even when --tolerate-errors is passed. Before this patch, this step
could retry endlessly (up to the parent roachtest's timeout (default
10h)). This step is not under the control of --duration (I think for
good reason) and so I've hardcoded a 10m cutoff.

We've seen in #51785 that, under chaos, this step can retry endlessly.
With this patch, the test will fail quicker.

Touches #51785

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: mod the comment about `retry.Retry`.

> Reviewed 2 of 2 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52262#-:-MDpbGd80ZYeKiwTWP2k:bhplj6o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/workload/cli/run.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52262#-MDpadtBANLrDI5IzAwa:-MDpadtBANLrDI5IzAwb:baefgdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a46a0cde20e6d49e953ddd6fd62002a90d3b842/pkg/workload/cli/run.go#L356)):*
> ```Go
> 	prepareStart := timeutil.Now()
> 	log.Infof(ctx, "creating load generator...")
> 	for i := 1; ; i++ {
> ```

Does `retry.Retry` with a context (with timeout) not do what we want here? If so, let's avoid the custom retry logic.

EDIT: the next commit adds this timeout. Even more reason to switch over.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52262)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @RaduBerinde)

___
*[pkg/workload/cli/run.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52262#-MDpadtBANLrDI5IzAwa:-MDq3KgX83fO02OhZ6OX:bdvi6io) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a46a0cde20e6d49e953ddd6fd62002a90d3b842/pkg/workload/cli/run.go#L356)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `retry.Retry` with a context (with timeout) not do what we want here? If so, let's avoid the custom retry logic.

EDIT: the next commit adds this timeout. Even more reason to switch over.
</blockquote></details>

done in the 2nd commit

**Review by nvb — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52262#-:-MDqMP5Q9PQjzTloX_Rl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52262#-:-MDr2mgt-xTTXAKH87Ef:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @RaduBerinde)

**Pull request merged**
