### PR TITLE
sql: run TestMonotonicInserts with distsql both off and on

### PR DESCRIPTION
**Pull request by RaduBerinde**
I think this test is important enough to run with both classic and distsql.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/monotonic_insert_test.go, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-KizREIyu-WEYyrkUo4J:-KizREIyu-WEYyrkUo4K:bo3lopp) ([raw file](https://github.com/cockroachdb/cockroach/blob/906672f00235c02339d5240267a9aeaf4541f5ab/pkg/sql/monotonic_insert_test.go#L87)):*
> ```Go
> 
> 	for _, distSQLMode := range []sql.DistSQLExecMode{sql.DistSQLOff, sql.DistSQLOn} {
> 		t.Run(fmt.Sprintf("distsql%s", distSQLMode), func(t *testing.T) {
> ```

can you make this `"distsql=%s"` (add an equal sign)

---

*[pkg/sql/session.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-KizRcfKM00tkLUnAvXK:-KizRcfKM00tkLUnAvXL:blxqfzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/906672f00235c02339d5240267a9aeaf4541f5ab/pkg/sql/session.go#L30)):*
> ```Go
> 	"golang.org/x/net/trace"
> 
> 	"strings"
> ```

move up to stdlib imports please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-:-KizRzpnVTb1UT97Adix:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/monotonic_insert_test.go, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-KizREIyu-WEYyrkUo4J:-KizuORsXpgNh1COu4Q0:boopawo) ([raw file](https://github.com/cockroachdb/cockroach/blob/906672f00235c02339d5240267a9aeaf4541f5ab/pkg/sql/monotonic_insert_test.go#L87)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you make this `"distsql=%s"` (add an equal sign)
</blockquote></details>

TFTR! Done.

---

*[pkg/sql/session.go, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-KizRcfKM00tkLUnAvXK:-KizuPtTGrYTmqG836Sq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906672f00235c02339d5240267a9aeaf4541f5ab/pkg/sql/session.go#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

move up to stdlib imports please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/monotonic_insert_test.go, line 93 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-Kj41S8AkussI46MS_vO:-Kj41S8AkussI46MS_vP:b5xg16i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5314f5f6ad73db68453e0c077504fe75b18304d3/pkg/sql/monotonic_insert_test.go#L93)):*
> ```Go
> }
> 
> func testMonotonicInserts(t *testing.T, distSQLMode sql.DistSQLExecMode) {
> ```

consider inlining this in the parent

---

*[pkg/sql/session.go, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-Kj41ffnSbYAOG7mYFH4:-Kj41ffnSbYAOG7mYFH5:b-q9bavp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5314f5f6ad73db68453e0c077504fe75b18304d3/pkg/sql/session.go#L97)):*
> ```Go
> )
> 
> func (m DistSQLExecMode) String() string {
> ```

consider using the `stringer` code generation tool. I think that's what we do for other enums. Look for `//go:generate stringer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-:-Kj423gIzRKymUmBqF8s:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/monotonic_insert_test.go, line 93 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-Kj41S8AkussI46MS_vO:-Kj4L5BngQ5FYM_wC8yh:b-u9ipq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5314f5f6ad73db68453e0c077504fe75b18304d3/pkg/sql/monotonic_insert_test.go#L93)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider inlining this in the parent
</blockquote></details>

I did that originally but it made the diff harder to look at.

---

*[pkg/sql/session.go, line 97 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-Kj41ffnSbYAOG7mYFH4:-Kj4LAy3chDG4i_Rwkf7:buv5l4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5314f5f6ad73db68453e0c077504fe75b18304d3/pkg/sql/session.go#L97)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider using the `stringer` code generation tool. I think that's what we do for other enums. Look for `//go:generate stringer`
</blockquote></details>

We need them to be "off", "on" not "DistSQLOff" etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15479#-:-Kj4LEbwbebmB6DFGica:b-814g8k)*

**Pull request merged**
