### PR TITLE
opt: constraints for NeOp/IsNotOp and IS (NOT) NULL

### LINKED ISSUE #22450: sql, opt: improve handling of maximal values in span constraints
We can do a better job at trimming away spans that we can prove are empty. For example:

```
build-scalar,normalize,index-constraints vars=(bool) index=(@1)
@1 != true
----
(/NULL - /false]
(/true - ]             <--- this can be dropped

build-scalar,normalize,index-constraints vars=(bool) index=(@1)
@1 != false
----
(/NULL - /false)  <--- this can be dropped
[/true - ]
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt/idxconstraint: trim empty spans for NeOp/IsNotOp

The index span generation code for NeOp/IsNotOp can generate empty
spans like `(/true - ]`. This change adds code to recognize minimum
and maximum datums and omit these spans. This is possibly a minor
performance improvement, but it's mostly a cosmetic fix.

Fixes #22450.

Release note: None

#### opt: constraints for NeOp/IsNotOp

Port the index constraints code for single-column NeOp/IsNotOp.

Release note: None

#### opt: constraints for IS (NOT) NULL

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr55rR9CCg-HvzeIbt:-LBr55rR9CCg-HvzeIbu:b-mwfat4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee63f0df480ad842916a66cf1d8162b69f376fa/pkg/sql/opt/idxconstraint/index_constraints.go#L264)):*
> ```Go
> 		key := constraint.MakeKey(datum)
> 		descending := c.columns[offset].Descending()
> 		if !datum.IsMin(c.evalCtx) {
> ```

Can you add some examples/comments here? It's not immediately obvious why you're setting a contradiction if the datum is the minimum value.  Also - what about nulls in the case of IsNotOp?

---

*[pkg/sql/opt/idxconstraint/testdata/single-column, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr5af_0c77-nK1OTkw:-LBr5af_0c77-nK1OTkx:bwrsm18) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee63f0df480ad842916a66cf1d8162b69f376fa/pkg/sql/opt/idxconstraint/testdata/single-column#L179)):*
> ```
> 
> index-constraints vars=(bool) index=(@1)
> @1 IS NOT FALSE
> ```

could it be null?

---

*[pkg/sql/opt/memo/constraint_builder.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr6jva8zn_-IqYLm3h:-LBr6jva8zn_-IqYLm3i:b1dmbff) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d97a111f2ec67912a3d2eef8660bb9ddd16721/pkg/sql/opt/memo/constraint_builder.go#L125)):*
> ```Go
> 		key := constraint.MakeKey(datum)
> 		c := constraint.Contradiction
> 		if !datum.IsMin(cb.evalCtx) {
> ```

what about null for IsNotOp?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25338)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr55rR9CCg-HvzeIbt:-LBrvwZT4NgW3VlVt3-q:b-rtqkin) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee63f0df480ad842916a66cf1d8162b69f376fa/pkg/sql/opt/idxconstraint/index_constraints.go#L264)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add some examples/comments here? It's not immediately obvious why you're setting a contradiction if the datum is the minimum value.  Also - what about nulls in the case of IsNotOp?
</blockquote></details>

Good catch, fixed the null handling (both here and in the corresponding change in the constraint builder). Also added a comment.

---

*[pkg/sql/opt/idxconstraint/testdata/single-column, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr5af_0c77-nK1OTkw:-LBrwHqk7_iuIdJhe0H6:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee63f0df480ad842916a66cf1d8162b69f376fa/pkg/sql/opt/idxconstraint/testdata/single-column#L179)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

could it be null?
</blockquote></details>

Good catch.

---

*[pkg/sql/opt/memo/constraint_builder.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-LBr6jva8zn_-IqYLm3h:-LBs2VXf54W83xDCA_wq:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2d97a111f2ec67912a3d2eef8660bb9ddd16721/pkg/sql/opt/memo/constraint_builder.go#L125)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what about null for IsNotOp?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-:-LBs2XA532nLKIFYjsxs:b-814g8k)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r5, 1 of 4 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25338#-:-LBs8yfE68hvnDi6H703:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Note to self: add some logic tests (with actual data).

**Pull request merged**
