### PR TITLE
sql: introduce variable to disable auto-rehoming 

### LINKED ISSUE #69619: multiregion: gate rehome_row ON UPDATE using a cluster setting
as per title

### PR DESCRIPTION
**Pull request by otan**
See commits for details.

Resolves: #69619

Release justification: gating a new feature.

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
A couple minor comments, but otherwise :lgtm: 

> Reviewed 3 of 3 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-:-MiZ5kua1pYPqkpoAZpx:b68kndm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-MiZ3F6i-G2iId72FwoW:-MiZ3F6j1KhkLgkMXntd:bs65oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/54de5f4665eecface3c449eed548f1556ef8bd22/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming#L24)):*
> ```
> 
> # Re-home to another region using UPSERT.
> query TIT nodeidx=2
> ```

Didn't know we could do this nodeidx thing in logic tests! 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-MiZ4VKLEwqpdz8SP_fK:-MiZ4VKLEwqpdz8SP_fL:bggfac6) ([raw file](https://github.com/cockroachdb/cockroach/blob/322d834c12431ef8b0412f1d59938a457152ae9c/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming#L55)):*
> ```
> ----
> ca-central-1  1  cya
> ```

Let's add a test to ensure that the `on_update_rehome` session variable has no effect on other ON UPDATE expressions? 
___
*[pkg/sql/opt/cat/column.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-MiZ5-Jq6j45_-B-5f_P:-MiZ5-Jq6j45_-B-5f_Q:bko857) ([raw file](https://github.com/cockroachdb/cockroach/blob/322d834c12431ef8b0412f1d59938a457152ae9c/pkg/sql/opt/cat/column.go#L118)):*
> ```Go
> 
> // UseOnUpdate returns true if there is an ON UPDATE expression which does not
> // match rehome_row().
> ```

Let's call out that if the expression matches `rehome_row()` we will check the session variable? 

Separately, it might also be worth explaining why this special casing exists to begin with for future readers of this code.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69626)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-MiZ3F6i-G2iId72FwoW:-MiZJbR26klpSBdNhEN9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54de5f4665eecface3c449eed548f1556ef8bd22/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming#L24)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Didn't know we could do this nodeidx thing in logic tests! 
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69626#-MiZ4VKLEwqpdz8SP_fK:-MiZJa9wCVIR9cN_5UG6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/322d834c12431ef8b0412f1d59938a457152ae9c/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming#L55)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add a test to ensure that the `on_update_rehome` session variable has no effect on other ON UPDATE expressions? 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69626)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @otan)

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
