### PR TITLE
sql/parser: allow READ ONLY/WRITE in txn grammar

### PR DESCRIPTION
**Pull request by madelynnblue**
Postgres supports READ ONLY/WRITE in their various transaction
settings. Add parsing support for both options, however READ WRITE
is the only one support (and it doesn't change anything since that's
what we were before). See lib/pq#619 for motivation of this change.

Refactor the transaction modes so they use a common code path. This
will greatly simplify adding other options in the future.

See #16309

### CODE REVIEW

**Comment by knz** [comment]
Nice!

LGTM on principle, some aesthetic nits remaining.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/txn.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2qFRS19i2XEQLqtft:-Km2qFRS19i2XEQLqtfu:b-rdn413) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/txn.go#L80)):*
> ```Go
> }
> 
> func (p *planner) setReadOnly(readOnly parser.ReadOnly) error {
> ```

s/setReadOnly/setReadWriteMode/

---

*[pkg/sql/parser/sql.y, line 1561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2pVUMfUR1nBvAdjEB:-Km2pVUMfUR1nBvAdjEC:b-vbctbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/sql.y#L1561)):*
> ```Yacc
>   }
> 
> read_only:
> ```

I would prefer to use this this rule instead:
```
opt_read_mode:
   READ ONLY { ... }
|  READ WRITE { ... }
| /* empty */ { $$.val = Unspecified... }
```

---

*[pkg/sql/parser/sql.y, line 2438 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2pKYnY0k9D-G3oZTC:-Km2pKYop-Pong52OKeD:b-og5d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/sql.y#L2438)):*
> ```Yacc
>     a := $1.transactionModes()
>     b := $3.transactionModes()
>     if b.Isolation != UnspecifiedIsolation {
> ```

Please capture this logic in a method of TransactionMode (`merge` or something) and use it here.

---

*[pkg/sql/parser/txn.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2ptYBYUuq7hKk67xb:-Km2ptYBYUuq7hKk67xc:b-1anyxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L75)):*
> ```Go
> 
> // ReadOnly holds the read only setting for a transaction.
> type ReadOnly int
> ```

s/ReadOnly/ReadWriteMode/ here and below.

---

*[pkg/sql/parser/txn.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2q5xMPGzkIRav-Z3q:-Km2q5xMPGzkIRav-Z3r:bs5y6ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L80)):*
> ```Go
> const (
> 	UnspecifiedReadOnly ReadOnly = iota
> 	Only
> ```

s/Only/ReadOnly/ here and below

---

*[pkg/sql/parser/txn.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2q7NiXZ52NUUYRpND:-Km2q7NiXZ52NUUYRpNE:b-f5y6f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L81)):*
> ```Go
> 	UnspecifiedReadOnly ReadOnly = iota
> 	Only
> 	Write
> ```

s/Write/ReadWrite/ here and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2qIPbyjYUDt_sMAt9:b-t2ohhi)*

**Comment by mjibson** [comment]
Ok with calling it `ReadMode` instead of `ReadWriteMode`?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2uDiXuYso3iaK4jZy:b-pqgxad)*

**Comment by knz** [comment]
But why? If the user enters "READ WRITE" it's not a "read mode"...

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2ueyMCAwh8N-D6_O8:b-2vx4ek)*

**Comment by knz** [comment]
Also perhaps the better name for the type is "AccessModeHint"

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2umlnYgEUNC7TSd7Y:budurtj)*

**Comment by mjibson** [comment]
The read modes are WRITE or ONLY. But I don't want to bikeshed this too much so ReadWriteMode is fine. I don't think AccessModeHint is descriptive enough.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/txn.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2qFRS19i2XEQLqtft:-Km2wOliz4dvcj2axUmc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/txn.go#L80)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/setReadOnly/setReadWriteMode/
</blockquote></details>

Done.

---

*[pkg/sql/parser/sql.y, line 1561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2pVUMfUR1nBvAdjEB:-Km2um9qUtvMA3EuNDbT:bzhlrdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/sql.y#L1561)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would prefer to use this this rule instead:
```
opt_read_mode:
   READ ONLY { ... }
|  READ WRITE { ... }
| /* empty */ { $$.val = Unspecified... }
```




</blockquote></details>

I've merged these two rules into one, but have left out the opt part because that is covered elsewhere.

---

*[pkg/sql/parser/sql.y, line 2438 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2pKYnY0k9D-G3oZTC:-Km2wLKUW9LfuhA8a5Tu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/sql.y#L2438)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please capture this logic in a method of TransactionMode (`merge` or something) and use it here.
</blockquote></details>

Done.

---

*[pkg/sql/parser/txn.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2ptYBYUuq7hKk67xb:-Km2wMu3UcRj8hhEh1_4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L75)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/ReadOnly/ReadWriteMode/ here and below.
</blockquote></details>

Done.

---

*[pkg/sql/parser/txn.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2q5xMPGzkIRav-Z3q:-Km2wMi_0zGEfGDW0wW3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L80)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/Only/ReadOnly/ here and below
</blockquote></details>

Done.

---

*[pkg/sql/parser/txn.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-Km2q7NiXZ52NUUYRpND:-Km2wMZ9qFjuiN_nVQo3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd7b86a4823d8eee75808fd950466b0a23219232/pkg/sql/parser/txn.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/Write/ReadWrite/ here and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2wbH7Nh7K0D73nXSx:bin8c9m)*

**Comment by knz** [comment]
Basically I think this is less bikeshed and more setting foundations for later. I think the difference between our views is that you have seen the common READ keyword for both syntaxes and modeled this feature in your head as "READ followed by a mode"; whereas in my head when I see "READ ONLY" and "READ WRITE" I also see "WRITE ONLY" glaringly missing, as these are the 3 possible values of an overall "access mode" option on the transaction.

(write-only txns are a thing, and they may be very interesting to us  because they guarantee 1PC is always a valid optimization)

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km2yHs-loqvPFwn5zXi:b-y578ds)*

**Comment by benesch** [comment]
FWIW, I also see `READ ONLY` and `READ WRITE` instead of `READ <mode>`. Perhaps because `ORDER BY` is a thing.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km31ly8OB1HVXYQ8AHz:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm:, FWIW I'm happy with ReadWriteMode over AccessModeHint - it's not a hint as it actually enforces behavior.

---

Reviewed 4 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16387#-:-Km329B_lvaMW1LuN1z0:bprn6wd)*

**Pull request merged**
