### PR TITLE
geo/geos: fix compile error with Make

### PR DESCRIPTION
**Pull request by otan**
We've used CSlice where we should have used CString in various places.
This only came out when compiling with Make.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
thanks blathers, you are my friend

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geos/geos_unix.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47084#-M4G6gvy9J4NCldawPSt:-M4G6gvy9J4NCldawPSu:bdsns9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4b573a4bf3c5209ababbd4bac50c169663047/pkg/geo/geos/geos_unix.go#L99)):*
> ```Go
> 	}
> 	b := []byte(str)
> 	return C.CR_GEOS_String{
> ```

btw, this fix is already in https://github.com/cockroachdb/cockroach/pull/47061 including the function comment.
___
*[pkg/geo/geos/geos_unix.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47084#-M4G7PwP52byAc7ceqPV:-M4G7PwP52byAc7ceqPW:bfuranr) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4b573a4bf3c5209ababbd4bac50c169663047/pkg/geo/geos/geos_unix.go#L106)):*
> ```Go
> 
> // cStringToUnsafeGoBytes converts a CR_GEOS_String to go bytes.
> func cStringToUnsafeGoBytes(s C.CR_GEOS_String) []byte {
> ```

Do we really need both `CR_GEOS_String` and `CR_GEOS_Slice`? It matters whether we are converting from a Go string or Go bytes only wrt needing to cast to `[]byte`. But the actual C++ structs are the same and it is confusing to maintain both. The fact that some of the C interfaces cannot deal with binary data is something that this interface can't really enforce since the Go string can have the \0 byte -- just like a C++ `std::string`, which we use in `CR_GEOS_StringToString`.

**Comment by otan** [comment]
___
*[pkg/geo/geos/geos_unix.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47084#-M4G7PwP52byAc7ceqPV:-M4GR9zVDYMoC0rN2uvA:b-jyljvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4b573a4bf3c5209ababbd4bac50c169663047/pkg/geo/geos/geos_unix.go#L106)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we really need both `CR_GEOS_String` and `CR_GEOS_Slice`? It matters whether we are converting from a Go string or Go bytes only wrt needing to cast to `[]byte`. But the actual C++ structs are the same and it is confusing to maintain both. The fact that some of the C interfaces cannot deal with binary data is something that this interface can't really enforce since the Go string can have the \0 byte -- just like a C++ `std::string`, which we use in `CR_GEOS_StringToString`.
</blockquote></details>

I think we can get rid of it. Was form following DBSlice.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47084)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geos/geos_unix.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47084#-M4G7PwP52byAc7ceqPV:-M4GUGsv6FqpwKCNXWgH:bvuiweh) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d4b573a4bf3c5209ababbd4bac50c169663047/pkg/geo/geos/geos_unix.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think we can get rid of it. Was form following DBSlice. 
</blockquote></details>

I'll do some cleanup. The difference between `DBString` and `DBSlice` was that the Go code did not need to free the latter -- it didn't have anything to do with binary data. Parameters to C++ were all DBSlices. The return values were of both kinds. The `DBSlice` return value was useful in the engine since there are memory allocation optimizations in iterators, which reuse the same memory during iteration.

**Pull request closed without merging**
