### PR TITLE
colexec: implement resizing in the hash table

### LINKED ISSUE #52257: colexec: implement rehashing in the vectorized hash table
Currently, the vectorized hash table only supports fixed number of buckets which is set in the constructor (and has different values based on different use cases for the hash table). However, we should support rehashing behavior. This will likely provide noticeable performance improvements in many operators (hash joiner, unordered distinct, hash aggregator).

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: improve benchmarks of hash aggregation and some cleanup**

Previously, we would populate groups in ordered fashion for both ordered
and hash aggregators, but this is not very realistic in case of the hash
aggregation. This commit makes the groups distribution random (but still
adhering to the target group sizes). It also adds variation of number of
input batches to the benchmark of the aggregators.

This commit also removes an unused parameter from the tuple distributor.

Release note: None

**colexec: clean up mixed-type equality checks in the joins**

We currently only support the cases of same-type as well as integers of
mixed widths in the equality conditions (all other allowed mixed-type
comparisons are pushed into the ON condition, see 43060), so we will
now generate the code only for same-type comparisons and for integer
ones in the hash table.

This limitation became apparent when the resizing of the hash table was
put in place, and TestHashJoinerAgainstProcessor became flaky. Note that
the test could flake before, but it was impossibly unlikely - we had
a fixed large number of hash buckets, so the chance of a hash collision
was a lot lower.

This commit updates the test to deflake it (to generate comparable types
only of the cases that could occur in non-test environment) as well as
updates the hash table template to not generate some dead code.

Release note: None

**colexec: implement resizing in the hash table**

This commit implements the resizing logic in the vectorized hash table.
Previously, the number of hash buckets has been fixed at 2^16 and now
it'll start out at coldata.BatchSize() and will grow exponentitally while
maintaining the target load factor (the average number of tuples per
bucket).

Note that we don't have a maximum number of buckets because this commit
also adds memory accounting for the internal auxiliary slices of the hash
table. Not having a maximum is acceptable because every bucket takes up
16 bytes, and if we are going to hit the memory limit, mostly likely
it'll be because of the tuples stored in `ht.vals` and
`buildScratch.next` slice (which is of the same length as `ht.vals`).

All users of the hash table (hash joiner, hash aggregator, and unordered
distinct) have been benchmarked using microbenchmarks and TPCH queries
and the load factor has been chosen separately. I also tried out different
initial numbers of buckets, but using coldata.BatchSize() showed the most
stable performance. The reasoning for such choice:
- on one hand, we make several other allocations that have to be at
least coldata.BatchSize() in size, so we don't win much in the case of
the input with small number of tuples;
- on the other hand, if we start out with a larger number, we won't be
using vast of majority of the buckets on the input with small number of
tuples (a downside) while not gaining much in the case of the input with
large number of tuples.

#Fixes: #52257.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks show most improvement on [unordered distinct](https://gist.github.com/yuzefovich/4dadc169eac0dc08852a9f51e4301527), noticeable improvement on [hash joiner](https://gist.github.com/yuzefovich/0c0a4ec903785efc48081419db3ff28e) on small input (however, this could have been achieved without the resizing logic), and mostly improvement on [hash aggregator](https://gist.github.com/yuzefovich/9f107712e9d5cc29dfb36901b6e6c3c6). I also ran `tpchvec/bench` for the load factor for hash joiner and hash aggregator and chose the values on both microbenchmarks and queries.

**Comment by yuzefovich** [comment]
Comparing TPCH before and after on 5 runs:
```
1:	before: 2.93s	after: 2.67s	diff: 9.59%
2:	before: 0.24s	after: 0.23s	diff: 5.22%
3:	before: 2.04s	after: 2.07s	diff: -1.83%
4:	before: 2.49s	after: 2.44s	diff: 1.97%
5:	before: 2.93s	after: 2.67s	diff: 9.42%
6:	before: 10.12s	after: 9.67s	diff: 4.67%
7:	before: 7.50s	after: 7.32s	diff: 2.46%
8:	before: 1.33s	after: 1.25s	diff: 6.41%
9:	before: 4.83s	after: 4.51s	diff: 7.05%
10:	before: 2.77s	after: 2.82s	diff: -1.84%
11:	before: 0.78s	after: 0.74s	diff: 4.58%
12:	before: 6.81s	after: 6.09s	diff: 11.83%
13:	before: 2.73s	after: 3.17s	diff: -13.89%
14:	before: 0.78s	after: 0.80s	diff: -2.76%
15:	before: 4.28s	after: 4.18s	diff: 2.34%
16:	before: 1.15s	after: 1.18s	diff: -2.71%
17:	before: 0.65s	after: 0.64s	diff: 2.20%
18:	before: 4.67s	after: 4.49s	diff: 4.05%
19:	before: 3.85s	after: 3.59s	diff: 7.12%
20:	before: 13.13s	after: 12.58s	diff: 4.36%
21:	before: 11.82s	after: 11.42s	diff: 3.43%
22:	before: 0.94s	after: 0.88s	diff: 6.61%
1:	before min: 2.62s	max: 3.43s	after min: 2.21s	max: 3.92s
2:	before min: 0.23s	max: 0.25s	after min: 0.21s	max: 0.25s
3:	before min: 1.94s	max: 2.08s	after min: 1.77s	max: 2.64s
4:	before min: 2.21s	max: 2.75s	after min: 2.19s	max: 2.73s
5:	before min: 2.36s	max: 3.85s	after min: 2.29s	max: 3.15s
6:	before min: 9.19s	max: 10.51s	after min: 8.51s	max: 10.20s
7:	before min: 7.02s	max: 8.25s	after min: 6.40s	max: 7.79s
8:	before min: 1.20s	max: 1.43s	after min: 1.10s	max: 1.33s
9:	before min: 4.44s	max: 5.41s	after min: 4.00s	max: 4.93s
10:	before min: 2.54s	max: 2.99s	after min: 2.59s	max: 2.99s
11:	before min: 0.70s	max: 0.85s	after min: 0.69s	max: 0.80s
12:	before min: 5.95s	max: 9.74s	after min: 5.58s	max: 6.98s
13:	before min: 1.87s	max: 3.66s	after min: 2.46s	max: 4.38s
14:	before min: 0.74s	max: 0.82s	after min: 0.76s	max: 0.83s
15:	before min: 4.04s	max: 4.54s	after min: 3.98s	max: 4.46s
16:	before min: 1.11s	max: 1.20s	after min: 1.07s	max: 1.27s
17:	before min: 0.63s	max: 0.67s	after min: 0.59s	max: 0.66s
18:	before min: 4.20s	max: 5.55s	after min: 3.76s	max: 6.08s
19:	before min: 3.48s	max: 4.45s	after min: 3.02s	max: 5.21s
20:	before min: 11.77s	max: 15.12s	after min: 11.17s	max: 14.26s
21:	before min: 10.15s	max: 12.74s	after min: 10.16s	max: 11.94s
22:	before min: 0.90s	max: 0.96s	after min: 0.74s	max: 0.97s
```
Note that Q13 shows noticeable regression, but a comparable increase in latency occurred with `vectorize=off`, so I think it's just unlucky data distribution.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice to see this

> Reviewed 6 of 6 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-:-MEvvfLm8Xoh8h6pxPml:b-pj8ij2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregators_test.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvkktbAKqYhZlJqgSn:-MEvkktbAKqYhZlJqgSo:b-g690hi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L980)):*
> ```Go
> 	aggFn := execinfrapb.AggregatorSpec_MIN
> 	for _, agg := range aggTypes {
> 		for _, numInputBatches := range []int{4, 64, 1024} {
> ```

Is `1024` too large or is it fine?
___
*[pkg/sql/colexec/aggregators_test.go, line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvdNOFAGSZsKUXXt42:-MEvdNOFAGSZsKUXXt43:bespydn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L997)):*
> ```Go
> // enough signal on the speeds of aggregate functions. For more diverse
> // configurations look at BenchmarkAggregator.
> func BenchmarkAllOptimizedAggregateFunctions(b *testing.B) {
> ```

Should we skip these benchmarks if run with the `-short` flag?
___
*[pkg/sql/colexec/hash_aggregator.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvvbJU9j_wMP7qwfoq:-MEvvbJU9j_wMP7qwfor:b7r5xui) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hash_aggregator.go#L142)):*
> ```Go
> 	op.scratch.intSlice = make([]int, coldata.BatchSize())
> 	op.scratch.anotherIntSlice = make([]int, coldata.BatchSize())
> 	const hashTableLoadFactor = 0.25
> ```

Comment
___
*[pkg/sql/colexec/hashjoiner.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvvdK25kXOh4WESfPi:-MEvvdK25kXOh4WESfPj:b7r5xui) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashjoiner.go#L231)):*
> ```Go
> 		probeMode = hashTableDeletingProbeMode
> 	}
> 	const hashTableLoadFactor = 8.0
> ```

Comment
___
*[pkg/sql/colexec/hashtable.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvpI995JijMidBbYK1:-MEvpI9A6H6qWer6fCbb:b-e768kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashtable.go#L194)):*
> ```Go
> func newHashTable(
> 	allocator *colmem.Allocator,
> 	loadFactor float64,
> ```

Please comment `loadFactor`. How does a caller choose a good `loadFactor`? Does it make sense to provide a default `loadFactor`? I'm also not sure `loadFactor` is the best naming choice, but let's discuss.

Also, how do golang's maps behave here (i.e. choosing when to resize)? Maybe we could mimic their existing behavior?
___
*[pkg/sql/colexec/hashtable.go, line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvpTFw3BC-iDsJgyw4:-MEvpTFw3BC-iDsJgyw5:b-zfnmxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashtable.go#L214)):*
> ```Go
> 	// the input with small number of tuples;
> 	// - on the other hand, if we start out with a larger number, we won't be
> 	// using vast of majority of the buckets on the input with small number of
> ```

nit: `s/using vast of/using the vast`
___
*[pkg/sql/colexec/hashtable.go, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvu373E2CnwTvQ_I8W:-MEvu374AumOyZxkNb3q:bcjq4v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashtable.go#L489)):*
> ```Go
> 
> 	// Check if we received more tuples than the current allocation size and
> 	// increase it if so (limiting in by coldata.BatchSize()).
> ```

nit: `limiting in by`
___
*[pkg/sql/colexec/unordered_distinct.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvr2C-2SvIwIa4Y174:-MEvr2C-2SvIwIa4Y175:b-36ljot) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/unordered_distinct.go#L29)):*
> ```Go
> 	allocator *colmem.Allocator, input colexecbase.Operator, distinctCols []uint32, typs []*types.T,
> ) colexecbase.Operator {
> 	const hashTableLoadFactor = 2.0
> ```

It's probably worth commenting this here and in every constructor, otherwise it just seems like a magic number.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregators_test.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvkktbAKqYhZlJqgSn:-MF6cLXzC-OPgVG1xT0v:b-b7uqmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L980)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is `1024` too large or is it fine?
</blockquote></details>

I don't see a problem with such number. Are you concerned about the runtime of such benchmark? I think it'll roughly take the same amount of time as with smaller number of input batches by simply making less iterations of the benchmark. This whole benchmark now takes about 2 minutes.
___
*[pkg/sql/colexec/aggregators_test.go, line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvdNOFAGSZsKUXXt42:-MF6dDVM0Rb_IkecccSL:b1wyu7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L997)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we skip these benchmarks if run with the `-short` flag?
</blockquote></details>

The benchmark takes about 1 minute, so I don't think it should be skipped. I think my rule of thumb is that I want to skip benchmark if they take like 5 minutes or more.

I think we had discussion about `-short` flag before, and we don't have any guidelines on how to decide. I think that if we want to make `make benchshort` useful, someone needs to audit all benchmarks.
___
*[pkg/sql/colexec/hash_aggregator.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvvbJU9j_wMP7qwfoq:-MF6iLgH-vq7kIueB2nS:bnxfxct) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hash_aggregator.go#L142)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

By the way, my statement that this factor can have like 2-3x performance difference seems wrong. I've just tried a few values, and I see up to 30-40% difference in some cases (maybe I saw bigger number when the load factor was some unreasonable value like 100).
___
*[pkg/sql/colexec/hashjoiner.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvvdK25kXOh4WESfPi:-MF6iMEF9sDqJ7SwoigY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashjoiner.go#L231)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hashtable.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvpI995JijMidBbYK1:-MF6i-pb68xO8ZgDoFAE:b1aeodp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hashtable.go#L194)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Please comment `loadFactor`. How does a caller choose a good `loadFactor`? Does it make sense to provide a default `loadFactor`? I'm also not sure `loadFactor` is the best naming choice, but let's discuss.

Also, how do golang's maps behave here (i.e. choosing when to resize)? Maybe we could mimic their existing behavior?
</blockquote></details>

Added a comment and also shared some reasoning during the standup.
___
*[pkg/sql/colexec/unordered_distinct.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvr2C-2SvIwIa4Y174:-MF6iKiyElT10WrP7ooM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/unordered_distinct.go#L29)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's probably worth commenting this here and in every constructor, otherwise it just seems like a magic number.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
I added another commit (as the second one) to fix a test flake that became a lot more likely once the resizing logic is put in place.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3, 6 of 6 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregators_test.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvkktbAKqYhZlJqgSn:-MF9yDoT5yl24Z2J-CEN:bq57dxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L980)):*
Yeah, I'm concerned about an unnecessary increase in runtime. Does 1024 give us any signal we're missing? If we get the same information from half that number of batches I don't see why we shouldn't try that.

> I think it'll roughly take the same amount of time as with smaller number of input batches by simply making less iterations of the benchmark.

Because of `b.N`? I'm not sure but it's possible. Have you checked?

Also, I think it would be good to reduce the number of iterations under short (by only running with a single group size and number of input batches.
___
*[pkg/sql/colexec/aggregators_test.go, line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvdNOFAGSZsKUXXt42:-MF9yJjb8LrPfLl5JwB6:b-icy6fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L997)):*
> someone needs to audit all benchmarks

What do you mean by this? My opinion is that each team is responsible for their benchmarks, I don't see someone auditing everyone's benchmarks. 

I agree that we need guidelines, but maybe we can already contribute by being conscious about this. Could we limit the benchmark to only run one aggregate function under short? One minute is long.
___
*[pkg/sql/colexec/hash_aggregator.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvvbJU9j_wMP7qwfoq:-MFA30PfEsuHjHMPveCX:b-9b2qho) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a918623f94e4422675e893012b7a409d2c24d82/pkg/sql/colexec/hash_aggregator.go#L142)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.

By the way, my statement that this factor can have like 2-3x performance difference seems wrong. I've just tried a few values, and I see up to 30-40% difference in some cases (maybe I saw bigger number when the load factor was some unreasonable value like 100).
</blockquote></details>

\<sarcasm\> Only 30/40%?! :scream: \</sarcasm\>
___
*[pkg/sql/colexec/hashtable.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MFA1jSG5s3rPVBJR1T-:-MFA1jSG5s3rPVBJR1T0:b-mt6tds) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d66ff1c185680aa08ce88b9d931d885e3c5ff5c/pkg/sql/colexec/hashtable.go#L193)):*
> ```Go
> 
> // newHashTable returns a new hashTable.
> // - loadFactor determines the average number of tuples per bucket exceeding of
> ```

nit: `s/exceeding of which/which, if exceeded,`
___
*[pkg/sql/colexec/hashtable.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MFA2DttCjXCsWVCBzyO:-MFA2DttCjXCsWVCBzyP:b-8jk77m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d66ff1c185680aa08ce88b9d931d885e3c5ff5c/pkg/sql/colexec/hashtable.go#L194)):*
> ```Go
> // newHashTable returns a new hashTable.
> // - loadFactor determines the average number of tuples per bucket exceeding of
> // which will trigger resizing the hash table. This number can have noticeable
> ```

nit: `s/can have noticeable/can have a noticeable`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregators_test.go, line 980 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvkktbAKqYhZlJqgSn:-MFBDwgX8A-HFf4RGzXZ:b8spcdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L980)):*
I chose 4, 64, and 1024 as a factor of 16 smaller and a factor of 16 larger than the original number (64).

> Because of `b.N`? I'm not sure but it's possible. Have you checked?

Yes, I ran the benchmark and it uses only 2 or 3 iterations, so the runtime for each case appears to take about the same time.
___
*[pkg/sql/colexec/aggregators_test.go, line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvdNOFAGSZsKUXXt42:-MFBC3is5OVKIh1JpzMg:bklag3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L997)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> someone needs to audit all benchmarks

What do you mean by this? My opinion is that each team is responsible for their benchmarks, I don't see someone auditing everyone's benchmarks. 

I agree that we need guidelines, but maybe we can already contribute by being conscious about this. Could we limit the benchmark to only run one aggregate function under short? One minute is long.
</blockquote></details>

I think if we want to maintain this `benchshort` thing, then the correct sequence of action is
1. coming up with exact guidelines on how we should write the benchmarks, what is an acceptable amount of time for short ones, etc
2. writing those guidelines down and sharing them with the whole org so that everyone is aware
3. every team audits the benchmarks they own to satisfy the guidelines.

Currently, we don't have the guidelines, so I'm pushing back on your suggestions because I have a different expectation for `-short` benchmarks. Once we have the guidelines in place, such points of contention should be gone.

Additionally, I'm not sure who and when uses `make benchshort`, and I think it is the only user of `-short` flag, right?

We have discussed it previously and are spending noticeable amount of time typing out the comments right now, so I'll adjust the benchmarks to your liking, but I think  maintaining `-short` behavior according to our "feelings" which - as we can see right now - differ between you and me is not the best use of our time without clear guidelines.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregators_test.go, line 997 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MEvdNOFAGSZsKUXXt42:-MFBGomr0F1X3wlAde99:b-1nuxie) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7dae5cdeac7eb95d4402b36f874634aaf5238cb/pkg/sql/colexec/aggregators_test.go#L997)):*
> because I have a different expectation for `-short` benchmarks

To be more precise, I don't have an expectation at all. For me, if a benchmark takes longer than several minutes, then it should be skipped under short, but that's it. That's why I'm pushing that we need to have the guidelines first before we want to enforce anything here.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r6, 6 of 6 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-:-MFBgKxm-jrQXhyCbtEA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregators_test.go, line 1005 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-MFBgA6W6QU3rErTmU6R:-MFBgA6X7pMT1zwkYJ_e:budfkrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/419106781890e1f33d2cb294a20293fa433ef872/pkg/sql/colexec/aggregators_test.go#L1005)):*
> ```Go
> 		numFnsToRun = 1
> 	}
> 	for aggFnNumber := 0; aggFnNumber < len(execinfrapb.AggregatorSpec_Func_name) && numFnsToRun > 0; aggFnNumber++ {
> ```

nit: `aggFnNumber < numFnsToRun` and you can avoid `numFnsToRun--` below.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52799#-:-MFBi1YN4MhvZvIedo7B:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Needed to rebase on top of master to fix the merge conflict.

bors r+

**Pull request merged**
