### PR TITLE
sql: array_to_json builtin

### PR DESCRIPTION
**Pull request by changangela**
Relates to #20120.

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
This is looking great! I have a few comments below. Also, it looks like the linter was unhappy with you - take a look at what it said by following the link to TeamCity at the bottom of the PR page.

> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-:-LLpEEXf1xCyr6hStDtt:b-lbjb1x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LLpDqql7qPZajmsqWBA:-LLpDqql7qPZajmsqWBB:b-plrhnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe549b01e3d6399e77a3bf59921d2d4b5894e45e/pkg/sql/logictest/testdata/logic_test/json_builtins#L93)):*
> ```
> query error pq: array_to_json\(\): pretty printing is not supported
> SELECT array_to_json(ARRAY[1, 2, 3], true)
> ```

These tests look pretty good! I would recommend adding a few more that test different datatypes, though - it's very common that something will work okay with integers but not with strings, decimals, collated strings, etc. You don't have to be exhaustive, but at least do strings as well.

Also, you should definitely add some tests for `NULL` inputs to the function. `NULL` data types are a common source of bugs in builtins and relational operators alike.
___
*[pkg/sql/sem/builtins/builtins.go, line 3312 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LLpDVoqDWRUmZ6oqUS0:-LLpDVor6-drJh9t5r4X:bjdfn90) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe549b01e3d6399e77a3bf59921d2d4b5894e45e/pkg/sql/sem/builtins/builtins.go#L3312)):*
> ```Go
> 		ReturnType: tree.FixedReturnType(types.JSON),
> 		Fn: func(_ *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 			prettyPrint := *(args[1].(*tree.DBool))
> ```

There's a shortcut function for this that we use all over called `MustBeDBool` - use that instead to be more similar to the code around this file.

**Review by jordanlewis — COMMENTED** [review]
The code and tests :lgtm:! Can you rename the commit to the same title as the PR, though? We like to make commit titles have the same format, where there's a package/area prefix like `sql: array_to_json builtin`. Once you've done that, you should be ready to merge!

Also, I'll show you offline, but when you finish uploading a patch that responds to a review you should go to Reviewable, respond to the comments and hit Publish so the reviewer knows that you're ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-:-LLpYNab9jk_nYwJ1FVB:bk6ylus)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LLpDqql7qPZajmsqWBA:-LLpZORdA-18Og6-kPuj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe549b01e3d6399e77a3bf59921d2d4b5894e45e/pkg/sql/logictest/testdata/logic_test/json_builtins#L93)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These tests look pretty good! I would recommend adding a few more that test different datatypes, though - it's very common that something will work okay with integers but not with strings, decimals, collated strings, etc. You don't have to be exhaustive, but at least do strings as well.

Also, you should definitely add some tests for `NULL` inputs to the function. `NULL` data types are a common source of bugs in builtins and relational operators alike.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 3312 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LLpDVoqDWRUmZ6oqUS0:-LLpZPaK-5TpSlFBXk8E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe549b01e3d6399e77a3bf59921d2d4b5894e45e/pkg/sql/sem/builtins/builtins.go#L3312)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There's a shortcut function for this that we use all over called `MustBeDBool` - use that instead to be more similar to the code around this file.
</blockquote></details>

Done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-:-LM2_YNz-0KNT4O-pMAd:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LLpDqql7qPZajmsqWBA:-LM2XzBr9zQWzAMvimqj:b-3toh7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe549b01e3d6399e77a3bf59921d2d4b5894e45e/pkg/sql/logictest/testdata/logic_test/json_builtins#L93)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great tests. Consider also adding a test where `array_to_json` is given an unsupported type.
___
*[pkg/sql/sem/builtins/builtins.go, line 3300 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LM2Y_IC02ryH_jrroVH:-LM2Y_IC02ryH_jrroVI:b-y2kdu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd5c1ef9b204137eb448190886070ba4976b85e/pkg/sql/sem/builtins/builtins.go#L3300)):*
> ```Go
> 		ReturnType: tree.FixedReturnType(types.JSON),
> 		Fn: func(_ *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 			j, err := tree.AsJSON(args[0])
> ```

This impl seems like what `toJSONImpl` does. Do you think there is a way to share the code? You might be able to set `Fn: toJSONImpl.Fn`
___
*[pkg/sql/sem/builtins/builtins.go, line 3317 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LM2ZHv8EI1RGpEdU5yy:-LM2ZHv8EI1RGpEdU5yz:b-mmqlvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd5c1ef9b204137eb448190886070ba4976b85e/pkg/sql/sem/builtins/builtins.go#L3317)):*
> ```Go
> 			}
> 
> 			j, err := tree.AsJSON(args[0])
> ```

Same here, maybe a better thing would be do add a function at the end of the file sort of similar to `asJSONObjectKey` that returns a given datum as a `JSON` object which is then used here, above, and in `toJSONImpl`. What do you think?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/builtins/builtins.go, line 3300 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LM2Y_IC02ryH_jrroVH:-LM2rsCr2zqA5m_iSFiZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd5c1ef9b204137eb448190886070ba4976b85e/pkg/sql/sem/builtins/builtins.go#L3300)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This impl seems like what `toJSONImpl` does. Do you think there is a way to share the code? You might be able to set `Fn: toJSONImpl.Fn`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 3317 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-LM2ZHv8EI1RGpEdU5yy:-LM2ra9v-1sVeEo0LIeV:b-8hz3g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bd5c1ef9b204137eb448190886070ba4976b85e/pkg/sql/sem/builtins/builtins.go#L3317)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same here, maybe a better thing would be do add a function at the end of the file sort of similar to `asJSONObjectKey` that returns a given datum as a `JSON` object which is then used here, above, and in `toJSONImpl`. What do you think?
</blockquote></details>

Yep I think that makes more sense. Done.

**Review by asubiotto — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29818#-:-LM3-NCn-CrHfGeVeabt:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — APPROVED** [review]

**Comment by changangela** [comment]
bors r=asubiotto,jordanlewis

**Comment by asubiotto** [comment]
bors delegate+

**Comment by changangela** [comment]
bors r=asubiotto,jordanlewis

**Pull request merged**
