### PR TITLE
changefeedccl: add ignore_disable_changefeed_replication option

### LINKED ISSUE #119891: changefeedccl: allow individual changefeed jobs to configure filtering
In 23.2, changefeeds would unconditionally filter out events that originated from a session that had the `disable_changefeed_replication` session variable set or row-level TTL deletes if the `sql.ttl.changefeed_replication.disabled` cluster setting was set.

In 24.1, we want to allow changefeeds to individually configure whether they will respect the filtering settings (i.e. a changefeed can be configured to ignore the session variable/cluster setting and emit events for all changes).

Jira issue: CRDB-36370

Epic CRDB-34240

### PR DESCRIPTION
**Pull request by andyyang890**
Fixes #119891 

Release note (enterprise change): A new boolean changefeed option
named `ignore_disable_changefeed_replication` has been added.
When set, the changefeed will not filter events even if CDC
filtering is configured, which is currently available via the
`disable_changefeed_replication` session variable,
`sql.ttl.changefeed_replication.disabled` cluster setting, and the
`ttl_disable_changefeed_replication` table storage parameter.

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
Nice work! I have fairly minor comments.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-:-Nsu93Mc6MG3AkaS4ptc:b-gcv765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @herkolategan, @jayshrivastava, @miraradeva, and @renatolabs)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-Nsu6eUjAhwT4SPg6bIk):*
I think the description of `changefeedReplicationDisabled` should be expanded to say that changefeeds with this option will not filter TTL delete events.
___
*[`pkg/cmd/roachtest/tests/cdc_filtering.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NstnHPZ3weOOwk_A8Qv:-NstnHPZ3weOOwk_A8Qw:by63yy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2c5d4020ef0a0c2f763c599e2301c562c89371/pkg/cmd/roachtest/tests/cdc_filtering.go#L271)):*
> ```Go
> 		// Produce a canonical format that we can assert on. The format is of the
> 		// form: id@exp_at|<deleted> (before: id@exp_at).
> 		eventToString := func(before *state, after *state) string {
> ```

Can this function be moved into a shared helper function? It seems like there's duplicate logic here.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120255)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @jayshrivastava, @miraradeva, @renatolabs, and @rharding6373)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-Nsu6eUjAhwT4SPg6bIk):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think the description of `changefeedReplicationDisabled` should be expanded to say that changefeeds with this option will not filter TTL delete events.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/cdc_filtering.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NstnHPZ3weOOwk_A8Qv:-NsvGW4D-VS-21W5BQu3:b-1art30) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2c5d4020ef0a0c2f763c599e2301c562c89371/pkg/cmd/roachtest/tests/cdc_filtering.go#L271)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can this function be moved into a shared helper function? It seems like there's duplicate logic here.
</blockquote></details>

Good call. I've refactored the code into a `makeEventString` function.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-:-NsxNv-f1y7Uo7D88AI2:b-2t11ox)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @herkolategan, @jayshrivastava, @miraradeva, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cdc_filtering.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NstnHPZ3weOOwk_A8Qv:-NsxMToU5JvHeQd-Q2sN:b-1p2gol) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2c5d4020ef0a0c2f763c599e2301c562c89371/pkg/cmd/roachtest/tests/cdc_filtering.go#L271)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Good call. I've refactored the code into a `makeEventString` function.
</blockquote></details>

This was an even cleaner refactor than what I considered. Very nice! Thanks for doing that.
___
*[`pkg/sql/ttl/ttlbase/ttl_helpers.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NsxN_5p00KVxgajAKKy:-NsxN_5p00KVxgajAKKz:b6qm8yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e4de35a66649070e7d53e6367fd7d383e64d5b/pkg/sql/ttl/ttlbase/ttl_helpers.go#L78)):*
> ```Go
> 		"sql.ttl.changefeed_replication.disabled",
> 		"if true, deletes issued by TTL will not be replicated via changefeeds "+
> 			"(except changefeeds that have the ignore_disable_changefeed_replication option set)",
> ```

nit: add something like ", which will always replicate TTL deletes" to the text in parens for clarity.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120255)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @jayshrivastava, @miraradeva, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc_filtering.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NstnHPZ3weOOwk_A8Qv:-NsxRuAB2WCjWeTTRapY:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d2c5d4020ef0a0c2f763c599e2301c562c89371/pkg/cmd/roachtest/tests/cdc_filtering.go#L271)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This was an even cleaner refactor than what I considered. Very nice! Thanks for doing that.
</blockquote></details>

Thanks!
___
*[`pkg/sql/ttl/ttlbase/ttl_helpers.go` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120255#-NsxN_5p00KVxgajAKKy:-NsxRw6WBJJjOJ7LlhXv:b-qtns7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e4de35a66649070e7d53e6367fd7d383e64d5b/pkg/sql/ttl/ttlbase/ttl_helpers.go#L78)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: add something like ", which will always replicate TTL deletes" to the text in parens for clarity.
</blockquote></details>

Updated, hopefully it's more clear now.

**Comment by andyyang890** [comment]
TFTR!

bors r=rharding6373

**Comment by andyyang890** [comment]
Seems like it didn't get added to the bors queue

bors r=rharding6373

**Pull request merged**
