### PR TITLE
sql: use gosql.Conn directly when setting statement timeout

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a few tests where we used `gosql.DB` object to set a statement timeout. IIUC, this does not guarantee that further calls to `gosql.DB.QueryContext` and alike methods will have the statement timeout set (a different connection or a new session might be used under the hood), so the statement timeout was not always being applied. I've looked over all tests that set the statement timeout and fixed them to use `gosql.Conn` object that should have the timeout get propagated.

Informs: #122766.
Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Ignore the first commit - it's being merged in #123344.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you for fixing my mistake!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123700#-:-NxFMphD0o1AX5RPwu9F:bpcr1lt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Failure is CDC flake.

bors r+

**Comment by yuzefovich** [comment]
Hm, seems like a different flake.

bors r+

**Pull request merged**
