### PR TITLE
build: include the sources when tar'ing up binaries

### LINKED ISSUE #8167: stress: failed test in cockroach/cli/cli.test: Example_zone
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b624f98deda333293ba82b5bf9bf603e6670728d

Stress build found a failed test:

```
=== RUN   Example_zone
I160801 05:19:19.804500 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160801 05:19:19.807813 gossip/gossip.go:1006  not connected to cluster; use --join to specify a connected node
I160801 05:19:19.808906 server/node.go:397  store store=0:0 ([]=) not bootstrapped
I160801 05:19:19.811386 storage/replica_command.go:1716  store=1:1 ([]=) range=1 [/Min-/Max): new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 408341h19m24.310769663s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-08-01 05:19:19.811276504 +0000 UTC]
I160801 05:19:19.811965 server/node.go:323  **** cluster {b87a5076-42cf-47e6-a46a-ebe5575dd2f3} has been created
I160801 05:19:19.811998 server/node.go:324  **** add additional nodes by specifying --join=127.0.0.1:34395
I160801 05:19:19.812661 storage/store.go:2774  system config not yet available
I160801 05:19:19.812734 server/node.go:410  initialized store store=1:1 ([]=): {Capacity:536870912 Available:536870912 RangeCount:0}
I160801 05:19:19.812769 server/node.go:298  node ID 1 initialized
I160801 05:19:19.812825 storage/stores.go:302  read 0 node addresses from persistent storage
I160801 05:19:19.812884 server/node.go:533  connecting to gossip network to verify cluster ID...
I160801 05:19:19.813618 server/node.go:554  node connected via gossip and verified as part of cluster {"b87a5076-42cf-47e6-a46a-ebe5575dd2f3"}
I160801 05:19:19.813657 server/node.go:351  node=1: started with [[]=] engine(s) and attributes []
I160801 05:19:19.813686 server/server.go:427  starting https server at 127.0.0.1:45865
I160801 05:19:19.813705 server/server.go:428  starting grpc/postgres server at 127.0.0.1:34395
I160801 05:19:19.814040 storage/split_queue.go:100  splitting store=1:1 ([]=) range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160801 05:19:19.814233 sql/event_log.go:103  Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:34395} Attrs:} ClusterID:{UUID:b87a5076-42cf-47e6-a46a-ebe5575dd2f3} StartedAt:1470028759813637011}
I160801 05:19:19.847024 storage/replica_command.go:2305  store=1:1 ([]=) range=1 [/Min-/Max): initiating a split of this range at key /Table/11
I160801 05:19:19.847888 sql/event_log.go:103  Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:34395} Attrs:} ClusterID:{UUID:b87a5076-42cf-47e6-a46a-ebe5575dd2f3} StartedAt:1470028759813637011}
I160801 05:19:19.850759 storage/log.go:84  Range Event: "split", range: 1, info: {"UpdatedDesc":{"range_id":1,"end_key":"kw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":2,"start_key":"kw==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160801 05:19:19.855220 storage/replica_command.go:2305  store=1:1 ([]=) range=2 [/Table/11-/Max): initiating a split of this range at key /Table/12
I160801 05:19:19.856488 storage/log.go:84  Range Event: "split", range: 2, info: {"UpdatedDesc":{"range_id":2,"start_key":"kw==","end_key":"lA==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":3,"start_key":"lA==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160801 05:19:19.860077 storage/replica_command.go:2305  store=1:1 ([]=) range=3 [/Table/12-/Max): initiating a split of this range at key /Table/13
I160801 05:19:19.862502 storage/log.go:84  Range Event: "split", range: 3, info: {"UpdatedDesc":{"range_id":3,"start_key":"lA==","end_key":"lQ==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":4,"start_key":"lQ==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160801 05:19:19.865088 storage/replica_command.go:2305  store=1:1 ([]=) range=4 [/Table/13-/Max): initiating a split of this range at key /Table/14
I160801 05:19:19.866648 storage/log.go:84  Range Event: "split", range: 4, info: {"UpdatedDesc":{"range_id":4,"start_key":"lQ==","end_key":"lg==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":5,"start_key":"lg==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key ls]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key set system --file=./testdata/zone_attrs.yaml]
Error: error reading zone config: open ./testdata/zone_attrs.yaml: no such file or directory
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key ls]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key get system.nonexistent]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key get system.lease]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key set system --file=./testdata/zone_range_max_bytes.yaml]
Error: error reading zone config: open ./testdata/zone_range_max_bytes.yaml: no such file or directory
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key get system]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key rm system]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key ls]
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key rm .default]
Error: unable to remove .default
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key set .default --file=./testdata/zone_range_max_bytes.yaml]
Error: error reading zone config: open ./testdata/zone_range_max_bytes.yaml: no such file or directory
[zone --host=127.0.0.1 --port=34395 --insecure=false --ca-cert=/tmp/cli-test717586342/ca.crt --cert=/tmp/cli-test717586342/node.crt --key=/tmp/cli-test717586342/node.key get system]
--- FAIL: Example_zone (0.52s)
got:
zone ls
.default
zone set system --file=./testdata/zone_attrs.yaml
error reading zone config: open ./testdata/zone_attrs.yaml: no such file or directory
zone ls
.default
zone get system.nonexistent
system.nonexistent not found
zone get system.lease
.default
replicas:
- attrs: []
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 86400
zone set system --file=./testdata/zone_range_max_bytes.yaml
error reading zone config: open ./testdata/zone_range_max_bytes.yaml: no such file or directory
zone get system
.default
replicas:
- attrs: []
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 86400
zone rm system
DELETE 0
zone ls
.default
zone rm .default
unable to remove .default
zone set .default --file=./testdata/zone_range_max_bytes.yaml
error reading zone config: open ./testdata/zone_range_max_bytes.yaml: no such file or directory
zone get system
.default
replicas:
- attrs: []
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 86400
want:
zone ls
.default
zone set system --file=./testdata/zone_attrs.yaml
INSERT 1
replicas:
- attrs: [us-east-1a, ssd]
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 86400
zone ls
.default
system
zone get system.nonexistent
system.nonexistent not found
zone get system.lease
system
replicas:
- attrs: [us-east-1a, ssd]
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 86400
zone set system --file=./testdata/zone_range_max_bytes.yaml
UPDATE 1
replicas:
- attrs: [us-east-1a, ssd]
range_min_bytes: 1048576
range_max_bytes: 134217728
gc:
  ttlseconds: 86400
zone get system
system
replicas:
- attrs: [us-east-1a, ssd]
range_min_bytes: 1048576
range_max_bytes: 134217728
gc:
  ttlseconds: 86400
zone rm system
DELETE 1
zone ls
.default
zone rm .default
unable to remove .default
zone set .default --file=./testdata/zone_range_max_bytes.yaml
UPDATE 1
replicas:
- attrs: []
range_min_bytes: 1048576
range_max_bytes: 134217728
gc:
  ttlseconds: 86400
zone get system
.default
replicas:
- attrs: []
range_min_bytes: 1048576
range_max_bytes: 134217728
gc:
  ttlseconds: 86400
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
1 runs completed, 1 failures, over 13s
FAIL
```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by tamird**
Note that we're still not tar'ing up the git repo itself. This should
grant us most of the space savings we were previously enjoying.

Fixes #8167.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8189)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Makefile, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO62_VksozvNbx--ogV:-KO62_VksozvNbx--ogW:702723520) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/Makefile#L95)):*
> ```Makefile
> .PHONY: testbuild
> testbuild:
> 	for golist in $(shell $(GO) list -f '{{.Name}}?{{.ImportPath}}?{{.Dir}}' -tags '$(TAGS)' $(PKG)); do \
> ```

I think this works to get the variables in a slightly cleaner way (haven't tested in a Makefile):

```
$(GO) list -f '{{.Name}}?{{.ImportPath}}?{{.Dir}}' -tags '$(TAGS)' $(PKG) | \
while IFS='?' read name import_path dir; do \
  $(GO) test ... \
done
```

Or even (unsure about quoting/escaping here; this is even less tested):

```
$(GO) list -f '$(GO) test -v $(GOFLAGS) -tags '$(TAGS)' -c -o "{{.Dir}}/{{.Name}}.test" -ldflags '$(LDFLAGS)' "{{.ImportPath}}" $(TESTFLAGS) || exit 1;' -tags '$(TAGS)' $(PKG) | $(SHELL)
```

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO61FsHxebM3yJJtenV:-1476519053) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
> ```Shell
> 
> rm -f static-tests.tar.gz
> time tar cfz static-tests.tar.gz -C ../ cockroach/ --exclude '.git'
> ```

If `go generate` has been run in this source tree, the `ui/{node_modules,jspm_packages}` directories are pretty large. It might be better to make this a whitelist instead of a blacklist: `$(git ls-files) $(find . -name '*.test') cockroach`.

I think we could also narrow the inclusion further, to just the `testdata` directories  (`sql/partestdata` doesn't quite fit the pattern but that could be fixed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-:-KO677svhm4wMpnsno6t:676834233)*

**Comment by mberhault** [comment]
LGTM.

Do we run go generate on those? If so, we should indeed include specific directories.

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Makefile, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO62_VksozvNbx--ogV:-KO6AKhU2UZpukfyImcO:-2062961213) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/Makefile#L95)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think this works to get the variables in a slightly cleaner way (haven't tested in a Makefile):
> 
> ```
> $(GO) list -f '{{.Name}}?{{.ImportPath}}?{{.Dir}}' -tags '$(TAGS)' $(PKG) | \
> while IFS='?' read name import_path dir; do \
>   $(GO) test ... \
> done
> ```
> 
> Or even (unsure about quoting/escaping here; this is even less tested):
> 
> ```
> $(GO) list -f '$(GO) test -v $(GOFLAGS) -tags '$(TAGS)' -c -o "{{.Dir}}/{{.Name}}.test" -ldflags '$(LDFLAGS)' "{{.ImportPath}}" $(TESTFLAGS) || exit 1;' -tags '$(TAGS)' $(PKG) | $(SHELL)
> ```
</details>
Ha, that's awesome. It worked.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6DVe4Jp1I0FaLBriu:1897698157) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> If `go generate` has been run in this source tree, the `ui/{node_modules,jspm_packages}` directories are pretty large. It might be better to make this a whitelist instead of a blacklist: `$(git ls-files) $(find . -name '*.test') cockroach`.
> 
> I think we could also narrow the inclusion further, to just the `testdata` directories  (`sql/partestdata` doesn't quite fit the pattern but that could be fixed)
</details>
Good point. I've stuck with all the files for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6LqFRQaASQPU-V-o9:-38010893) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Good point. I've stuck with all the files for now.
</details>
Also needs `cockroach/cockroach`. 

This also moves the `static-tests.tar.gz` output file from the repo root to `..`, so the output should probably be `cockroach/static-tests.tar.gz`.

`git -C cockroach ls-files` doesn't do what you want - it still prints the paths relative to `cockroach` instead of the current directory. 

Why exactly are we trying to tar everything up relative to the parent directory? It may be simpler to stop doing that and fix up the scripts on the other side that use this tarball.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6PKu6-OCirpRJsMd3:810901996) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Also needs `cockroach/cockroach`. 
> 
> This also moves the `static-tests.tar.gz` output file from the repo root to `..`, so the output should probably be `cockroach/static-tests.tar.gz`.
> 
> `git -C cockroach ls-files` doesn't do what you want - it still prints the paths relative to `cockroach` instead of the current directory. 
> 
> Why exactly are we trying to tar everything up relative to the parent directory? It may be simpler to stop doing that and fix up the scripts on the other side that use this tarball.
</details>
@mberhault @jordanlewis can y'all enumerate users of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6QZdvrX_QI4Fgy698:1275386332) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> @mberhault @jordanlewis can y'all enumerate users of this?
</details>
I believe they're used by the `stress` and `benchmark` tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6RJ1JsbHIC0FOziKj:-1496830900) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I believe they're used by the `stress` and `benchmark` tests.
</details>
Specifically, look at `cloud/gce/{stress/main.tf},{benchmarks/{main,variables}.tf}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/build-static-binaries.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-KO61FsHxebM3yJJtenU:-KO6ozHbQNqOqLX8AvmV:676965300) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba45b457b0c58409ece69347ed6aecd72288cdad/build/build-static-binaries.sh#L20)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Specifically, look at `cloud/gce/{stress/main.tf},{benchmarks/{main,variables}.tf}`.
</details>
PTAL

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8189#-:-KO6qB_J4fZZx3ON9rmM:1417088721)*

**Pull request merged**
