### PR TITLE
sql: use rowUpdater for schema change backfills

### PR DESCRIPTION
**Pull request by danhhz**
The existing code makes assumptions about the layout of the sql to k/v mapping
that will no longer be true with column families.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6970)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/backfill.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ6Pg7sg90NJjwOIbs9:-KJ6Pg7sg90NJjwOIbsA:-1532501921) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9f30edbef4ed710ba0dfb48d7c64c23c3075d5/sql/backfill.go#L206)):*
> ```Go
> 
> 	// Remember any new non nullable column with no default value.
> 	nonNullableColumn := ""
> ```

this can be a boolean now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[sql/backfill.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ6Pg7sg90NJjwOIbs9:-KJ7Tt-A5r3g0QotXzVb:1379724297) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9f30edbef4ed710ba0dfb48d7c64c23c3075d5/sql/backfill.go#L206)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this can be a boolean now.
</details>
I think you can get rid of it altogether

---

*[sql/backfill.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UE8mr2tIHxIGyCu6:-KJ7UE8mr2tIHxIGyCu7:-1936361928) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L261)):*
> ```Go
> 
> 		updateCols := append(added, dropped...)
> 		// TODO(dan): Tighten up the bound on fetchCols.
> ```

Wha do you mean? fetchCols doesn't seem to be here.

---

*[sql/backfill.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UjGiVQxZWD0JDTFY:-KJ7UjGiVQxZWD0JDTFZ:1490177726) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L284)):*
> ```Go
> 		for i := range valNeededForCol {
> 			_, valNeededForCol[i] = ru.fetchColIDtoRowIndex[tableDesc.Columns[i].ID]
> 		}
> ```

The above can also be 
valNeededForCol := make([]bool, 0, len(tableDesc.Columns))
for _, col := range tableDesc.Columns {
     _, ok := ru.fetchColIDtoRowIndex[column.ID]
     valNeededForCol = append(valNeededForCol, ok)
}

perhaps rename it to 

isValNeededForCol

---

*[sql/backfill.go, line 289 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7W3AdQ_sz0ruFQbKA:-KJ7W3AdQ_sz0ruFQbKB:-107846396) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L289)):*
> ```Go
> 			return err
> 		}
> 		if err := rf.StartScan(txn, sqlbase.Spans{sp}, 0); err != nil {
> ```

How do you configure a limit on this scan? The backfill would like to limit the number of keys it reads on every transaction to reduce contention.

---

*[sql/backfill.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7Wvz-SXrg4M34hHdl:-KJ7Wvz-SXrg4M34hHdm:-852879078) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L309)):*
> ```Go
> 
> 			updateValues := make(parser.DTuple, len(updateCols))
> 			for i, col := range added {
> ```

You've changed this to iterate over the added columns versus defaultExprs as done before. Any reason to do that?  defaultExprs[i] might panic I think. 

It will be nice to add a test that adds two columns in the same ALTER TABLE command, one with and without a default expression and see that this all works.

---

*[sql/backfill.go, line 323 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7Y0_QVQ91rXVUwoYx:-KJ7Y0_R0JmhRsejP4-O:-229469145) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L323)):*
> ```Go
> 			}
> 			for i := range dropped {
> 				updateValues[i+len(defaultExprs)] = parser.DNull
> ```

perhaps you want to use len(addd) here?

---

*[sql/rowwriter.go, line 477 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7TUBWU7WKEFFbbZ80:-KJ7TUBXp4oeSLwhkOnF:367338167) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/rowwriter.go#L477)):*
> ```Go
> // isSimpleUpdate returns true if this rowUpdater is only updating column data
> // (in contrast to updating the primary key or other indexes).
> func (ru *rowUpdater) isSimpleUpdate() bool {
> ```

isColumnOnlyUpdate() ? or perhaps you can call it doesNotUpdateIndexes() which is what it's doing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970)*

**Comment by paperstreet** [comment]
TFTRs! This is ready for another look

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> #### sql: use rowUpdater for schema change backfills
> 
> The existing code makes assumptions about the layout of the sql to k/v mapping
> 
> that will no longer be true with column families.
> 
> 
> 
</details>


---

Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/backfill.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ6Pg7sg90NJjwOIbs9:-KJ7g-M3UMXBG2px-RGf:2122190917) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9f30edbef4ed710ba0dfb48d7c64c23c3075d5/sql/backfill.go#L206)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I think you can get rid of it altogether
</details>
AFAIC, this is the only thing that throws the error if you add a non-nullable column with no default expr. Changed to a bool.

---

*[sql/backfill.go, line 261 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UE8mr2tIHxIGyCu6:-KJ7gPslnT3J-9qJ789a:496107440) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L261)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Wha do you mean? fetchCols doesn't seem to be here.
</details>
Yeah that's confusing. Updated the comment.

---

*[sql/backfill.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UjGiVQxZWD0JDTFY:-KJ7gZm1CoB76WDT60jC:1585308712) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L284)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> The above can also be 
> valNeededForCol := make([]bool, 0, len(tableDesc.Columns))
> for _, col := range tableDesc.Columns {
>      _, ok := ru.fetchColIDtoRowIndex[column.ID]
>      valNeededForCol = append(valNeededForCol, ok)
> }
> 
> perhaps rename it to 
> 
> isValNeededForCol
</details>
I'm sorry, but I don't follow why this is better?

valNeededForCol is what this is called everywhere else, so I'd like to keep it consistent.

---

*[sql/backfill.go, line 289 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7W3AdQ_sz0ruFQbKA:-KJ7hFkbIeJIFnNwD4mi:1711884843) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L289)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> How do you configure a limit on this scan? The backfill would like to limit the number of keys it reads on every transaction to reduce contention.
</details>
I'm using ColumnTruncateAndBackfillChunkSize to limit the number of rows. It's not worth it to try splitting by number of keys in the middle of a row, so I think we could just adjust the constant here to be number of rows instead of number of keys. To do a key count limit, we could estimate the number of keys it's scanning per row and increment `i` using that instead, but that number is not something RowFetcher currently exposes.

---

*[sql/backfill.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7Wvz-SXrg4M34hHdl:-KJ7i1YTpHLPK8wjPBS5:287342110) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L309)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> You've changed this to iterate over the added columns versus defaultExprs as done before. Any reason to do that?  defaultExprs[i] might panic I think. 
> 
> It will be nice to add a test that adds two columns in the same ALTER TABLE command, one with and without a default expression and see that this all works.
</details>
At the moment, makeDefaultExprs always returns nil or something that lines up 1:1 with the cols passed in. I tried it both ways and thought the col iteration read better, but I can flip them if you like

Added a test

---

*[sql/backfill.go, line 323 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7Y0_QVQ91rXVUwoYx:-KJ7vq-DUHxq1BV7YD9v:-1349437807) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L323)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> perhaps you want to use len(addd) here?
</details>
Ah yes. Good catch.

---

*[sql/rowwriter.go, line 477 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7TUBWU7WKEFFbbZ80:-KJ7w0WIei3pPnUDXUJ1:-805690430) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/rowwriter.go#L477)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> isColumnOnlyUpdate() ? or perhaps you can call it doesNotUpdateIndexes() which is what it's doing
</details>
I like isColumnOnlyUpdate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-:-KJ7x6IVG4wodsBeaj9f:1863585089)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/backfill.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ6Pg7sg90NJjwOIbs9:-KJBMbXMSH8OLsLTLU9W:-1251152419) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9f30edbef4ed710ba0dfb48d7c64c23c3075d5/sql/backfill.go#L206)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> AFAIC, this is the only thing that throws the error if you add a non-nullable column with no default expr. Changed to a bool.
</details>
can you give the binding a better name? `addingNonNullableColumn`, perhaps?

---

*[sql/backfill.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UjGiVQxZWD0JDTFY:-KJBMzeVQe1WaHo2_MLN:1814609936) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L284)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I'm sorry, but I don't follow why this is better?
> 
> valNeededForCol is what this is called everywhere else, so I'd like to keep it consistent.
</details>
Probably better because it doesn't need to call `colIDtoRowIndexFromCols`?

---

*[sql/backfill.go, line 208 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJBMYUv7VoiiPbzFwnx:-KJBMYUwGM6k2JHzTx7a:-38379724) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1685868c3e80409c0cf76ba73b267cfd1017821/sql/backfill.go#L208)):*
> ```Go
> 		if columnDesc.DefaultExpr == nil && !columnDesc.Nullable {
> 			nonNullableColumn = true
> 			break
> ```

:beers: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970)*

**Comment by paperstreet** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[sql/backfill.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ6Pg7sg90NJjwOIbs9:-KJBPi3jq9wIr9_lbDWg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9f30edbef4ed710ba0dfb48d7c64c23c3075d5/sql/backfill.go#L206)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you give the binding a better name? `addingNonNullableColumn`, perhaps?
</details>
Done.

---

*[sql/backfill.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UjGiVQxZWD0JDTFY:-KJBPT1fy8y7uQ6VxJty:1482309546) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L284)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Probably better because it doesn't need to call `colIDtoRowIndexFromCols`?
</details>
colIDtoRowIndex is needed for the RowFetcher, not for computing valNeededForCol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[sql/backfill.go, line 284 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7UjGiVQxZWD0JDTFY:-KJBQmmBlyqDE5sw79Ny:5173665) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L284)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> colIDtoRowIndex is needed for the RowFetcher, not for computing valNeededForCol
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970)*

**Comment by vivekmenezes** [comment]
:lgtm:

please run

make stress TESTS="TestRaceWithBackfill" PKG="./sql"

for 2000 iterations before merging this. Thanks!

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> TFTRs! This is ready for another look
</details>


---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/backfill.go, line 289 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7W3AdQ_sz0ruFQbKA:-KJBVWBl3D3L31_QQEg-:-1465083171) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L289)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I'm using ColumnTruncateAndBackfillChunkSize to limit the number of rows. It's not worth it to try splitting by number of keys in the middle of a row, so I think we could just adjust the constant here to be number of rows instead of number of keys. To do a key count limit, we could estimate the number of keys it's scanning per row and increment `i` using that instead, but that number is not something RowFetcher currently exposes.
</details>
I agree that we should use a row limit here which is good. I'm fine leaving it the way it is for now. Can you add a comment for the 0 value passed in

---

*[sql/backfill.go, line 309 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7Wvz-SXrg4M34hHdl:-KJBW8YMHlzmqPS9iyVp:795446739) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L309)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> At the moment, makeDefaultExprs always returns nil or something that lines up 1:1 with the cols passed in. I tried it both ways and thought the col iteration read better, but I can flip them if you like
> 
> Added a test
</details>
thanks!

---

*[sql/backfill.go, line 287 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJBV63gfsl5DgXI63GG:-KJBV63gfsl5DgXI63GH:550334940) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c8119c92006220b7944c560962d8f33cb9853b/sql/backfill.go#L287)):*
> ```Go
> 			_, valNeededForCol[i] = ru.fetchColIDtoRowIndex[tableDesc.Columns[i].ID]
> 		}
> 		err = rf.Init(tableDesc, colIDtoRowIndex, &tableDesc.PrimaryIndex, false, false, valNeededForCol)
> ```

can you add a comment for the two false values of the form: false /* var-name */

---

*[sql/backfill.go, line 310 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJBWv4HQIhoyv9cFjA2:-KJBWv4I33G2uvVSDYD7:-1483686662) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c8119c92006220b7944c560962d8f33cb9853b/sql/backfill.go#L310)):*
> ```Go
> 				&tableDesc.PrimaryIndex, colIDtoRowIndex, row, indexKeyPrefix)
> 
> 			updateValues := make(parser.DTuple, len(updateCols))
> ```

let's move this allocation outside the for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-:-KJBYmg6TNJhZRyzf2RH:-1712354326)*

**Comment by paperstreet** [comment]
Done!

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> :lgtm:
> 
> please run
> 
> make stress TESTS="TestRaceWithBackfill" PKG="./sql"
> 
> for 2000 iterations before merging this. Thanks!
</details>


---

Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[sql/backfill.go, line 289 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJ7W3AdQ_sz0ruFQbKA:-KJBkqDxpV09X9KfHr71:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d10e392e1a633a5b859927aefce1e71fdf80/sql/backfill.go#L289)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I agree that we should use a row limit here which is good. I'm fine leaving it the way it is for now. Can you add a comment for the 0 value passed in
</details>
Done.

---

*[sql/backfill.go, line 287 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJBV63gfsl5DgXI63GG:-KJBk896V4dXzy4rOqOO:150494169) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c8119c92006220b7944c560962d8f33cb9853b/sql/backfill.go#L287)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> can you add a comment for the two false values of the form: false /* var-name */
</details>
These sorts of comments tend to rot and IMO do more harm than good. I'm sad that go doesn't let you name them at the callsite, which is prevented from rotting by the compiler.

---

*[sql/backfill.go, line 310 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-KJBWv4HQIhoyv9cFjA2:-KJBkrsqbBuxhFT3nkZd:-1510379395) ([raw file](https://github.com/cockroachdb/cockroach/blob/42c8119c92006220b7944c560962d8f33cb9853b/sql/backfill.go#L310)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> let's move this allocation outside the for loop.
</details>
Good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6970#-:-KJCdnlFj0XrSaTx_Ilq:-499146022)*

**Pull request merged**
