### PR TITLE
sql.y: update inline help for IMPORT INTO

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by knz — APPROVED** [review]
thanks

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, and @mwang1026)

___
*[pkg/sql/parser/sql.y, line 1937 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-M1a2xzr8VKIcbXJ4cSR:-M1a2xzr8VKIcbXJ4cSS:bpxpg7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca79ef77c4f0b46ab3beed08697b50ca2fb1a2bb/pkg/sql/parser/sql.y#L1937)):*
> ```Yacc
> //        [ WITH <option> [= <value>] [, ...] ]
> //
> // Format must be one of PGDUMP or MYSQLDUMP.
> ```

`Format must be one of` > `Format must be`
___
*[pkg/sql/parser/sql.y, line 1945 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-M1a35oE1aAFrO6PLYHk:-M1a35oE1aAFrO6PLYHl:bmhunrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca79ef77c4f0b46ab3beed08697b50ca2fb1a2bb/pkg/sql/parser/sql.y#L1945)):*
> ```Yacc
> //        DATA ( <datafile> [, ...] )
> //        [ WITH <option> [= <value>] [, ...] ]
> //
> ```

Add accepted formats here too.

**Comment by mwang1026** [comment]
Will this text also appear if someone tries `\h IMPORT INTO` ?

**Comment by mwang1026** [comment]
Also, what's the bar for what options are or are not included? And in general what's the reason behind having separate "fields terminated by" and "delimeter" options, one for 'delimited' and one for 'csv'?

**Review by lnhsingh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45676)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @mwang1026)

___
*[pkg/sql/parser/sql.y, line 1960 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-M1b03rHCy6sJ6l4upNK:-M1b03rHCy6sJ6l4upNL:b-gtoh3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca79ef77c4f0b46ab3beed08697b50ca2fb1a2bb/pkg/sql/parser/sql.y#L1960)):*
> ```Yacc
> //    MYSQLDUMP
> //
> // Options:
> ```

re: @mwang1026 comment-- We could also add a link to the docs for more options: https://www.cockroachlabs.com/docs/dev/import.html#import-options (can we dynamically change the docs URL to point to the correct corresponding version?)

**Review by knz — COMMENTED** [review]
I would recommend moving forward with this PR during the stability period. Especially adding the doc link in the See Also entry would be a UX improvement.

> Will this text also appear if someone tries \h IMPORT INTO ?

No, it only appears with `\h IMPORT` (not `\h IMPORT TABLE` nor `\h IMPORT INTO`).

> Also, what's the bar for what options are or are not included?

The contextual help is meant to display the most commonly used options only. For the detailed docs, there's the reference manual online.

> And in general what's the reason behind having separate "fields terminated by" and "delimeter" options, one for 'delimited' and one for 'csv'?

I don't know the answer for this - @dt what do you know about this?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-:-M2PYr5B08VKGbwDKWb0:b5sbl0s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lnhsingh, and @mwang1026)

___
*[pkg/sql/parser/sql.y, line 1945 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-M1a35oE1aAFrO6PLYHk:-M2PYZt37fgLORByQSku:b-i679ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca79ef77c4f0b46ab3beed08697b50ca2fb1a2bb/pkg/sql/parser/sql.y#L1945)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

Add accepted formats here too.
</blockquote></details>

No need to repeat since it's the same referent as above.
___
*[pkg/sql/parser/sql.y, line 1960 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45676#-M1b03rHCy6sJ6l4upNK:-M2PYfkJ1DD8xckOL1kc:biyzfx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca79ef77c4f0b46ab3beed08697b50ca2fb1a2bb/pkg/sql/parser/sql.y#L1960)):*
<details><summary><i>Previously, lnhsingh (Lauren Hirata Singh) wrote…</i></summary><blockquote>

re: @mwang1026 comment-- We could also add a link to the docs for more options: https://www.cockroachlabs.com/docs/dev/import.html#import-options (can we dynamically change the docs URL to point to the correct corresponding version?)
</blockquote></details>

@dt you can add the link as a `%SeeAlso: WEBDOCS/...` below. There's precedent elsewhere.

**Pull request closed without merging**
