### PR TITLE
server: fix node decommissioning itself

### LINKED ISSUE #56718: server: decommissioning self can hang
When a node is marked as decommissioned, it loses access to the cluster. When a node is decommissioned through itself (i.e. when the decommission cli is pointed at the node that is to be decommissioned, a common pattern), it can happen that the cluster learns that the node is decommissioned before the node itself does. In that case, the user will experience the decommissioning command hanging indefinitely. Typically, the server side of the endpoint is hanging in the KV layer, unable to perform KV operations.

I've seen this in #56568 when the very last step allows decommissioning through itself (I am changing that PR now to avoid this bug for now).

When this issue is closed, the last decommission step should read

```go
fullyDecommissionStep(h.getRandNodeOtherThan(pinnedUpgrade), h.getRandNode(),
```

or explicit coverage of this case should be introduced (preferrably).

### PR DESCRIPTION
**Pull request by erikgrinaker**
Previously, if a node was asked to decommission itself, the
decommissioning process would sometimes hang or fail since the node
would become decommissioned and lose RPC access to the rest of the
cluster while it was building the response.

This patch returns an empty response from the
`adminServer.Decommission()` call when setting the final
`DECOMMISSIONED` status, thereby avoiding further use of cluster RPC
after decommissioning itself. It also defers self-decommissioning until
the end if multiple nodes are being decommissioned.

This change is backwards-compatible with old CLI versions, which will
simply output the now-empty status result set before completing with
"No more data reported on target nodes". The CLI has been updated to
simply omit the empty response.

Resolves #56718.

A separate commit ensures errors with `codes.PermissionDenied` abort
RPC retries and return immediately, to prevent operations hanging with
indefinite internal retries when RPC access is lost.

Release justification: bug fixes and low-risk updates to new functionality

Release note (bug fix): Fixed a bug from 21.1-alpha where a node
decommissioning process could sometimes hang or fail when the
decommission request was submitted via the node being decommissioned.

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: nice thanks

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-:-MUrywoW1K9e1C0dN1pB:b7fw271)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
We never released this bug as part of a major release (it is in the 21.1 alphas), so I don't *think* it needs a release note? Let's keep the release note but add explicitly that this problem was only present in 21.1 alpha releases, and not in 20.2 and earlier.

:lgtm: very nice work.

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 11 of 12 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-:-MUsjY720XcIBBGZPRvj:b-mbuqgu)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

___
*[pkg/server/admin_test.go, line 2017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-MUskTQc26_rzhJTafHX:-MUskTQc26_rzhJTafHY:bjc4s00) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa1de35614e97ee4a3423288134e9f952fad4bc/pkg/server/admin_test.go#L2017)):*
> ```Go
> 
> func TestDecommissionSelf(t *testing.T) {
> 	skip.UnderStress(t) // can't handle 7-node clusters
> ```

Was this one necessary as well? I think we run other 7node tests under stress. The one to really avoid is `race`, which you do below. Check out https://github.com/cockroachdb/cockroach/blob/9fbbb1a7ed622f5974516e72186fec948096a1be/pkg/kv/kvserver/client_merge_test.go#L4110 for an example of a test that also runs under stress and seems to be doing ok (it's even run under stressrace, which, I don't know, bad idea honestly)

This isn't to say that you can't blow your local machine - try `make stress STRESSFLAGS='-p 4'` to limit the concurrency. This is also what we do in CI when we stress packages.
___
*[pkg/testutils/testcluster/testcluster.go, line 1427 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-MUsmtEU52ae8VOt4yUU:-MUsmtEU52ae8VOt4yUV:bo28om3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa1de35614e97ee4a3423288134e9f952fad4bc/pkg/testutils/testcluster/testcluster.go#L1427)):*
> ```Go
> 	ctx context.Context, t testing.TB, serverIdx int,
> ) *grpc.ClientConn {
> 	srv := tc.Server(serverIdx)
> ```

Don't you just want `srv.GRPCDialRaw(srv.RPCAddr())`?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61356)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/server/admin_test.go, line 2017 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-MUskTQc26_rzhJTafHX:-MUszmfOD5AJBPbhUtMs:bm444tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa1de35614e97ee4a3423288134e9f952fad4bc/pkg/server/admin_test.go#L2017)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Was this one necessary as well? I think we run other 7node tests under stress. The one to really avoid is `race`, which you do below. Check out https://github.com/cockroachdb/cockroach/blob/9fbbb1a7ed622f5974516e72186fec948096a1be/pkg/kv/kvserver/client_merge_test.go#L4110 for an example of a test that also runs under stress and seems to be doing ok (it's even run under stressrace, which, I don't know, bad idea honestly)

This isn't to say that you can't blow your local machine - try `make stress STRESSFLAGS='-p 4'` to limit the concurrency. This is also what we do in CI when we stress packages.
</blockquote></details>

You're right, stress runs just fine. 👍
___
*[pkg/testutils/testcluster/testcluster.go, line 1427 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61356#-MUsmtEU52ae8VOt4yUU:-MUswK8j0kNMXBQPohFm:b-3t4azd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa1de35614e97ee4a3423288134e9f952fad4bc/pkg/testutils/testcluster/testcluster.go#L1427)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Don't you just want `srv.GRPCDialRaw(srv.RPCAddr())`?
</blockquote></details>

Maybe, but turns out we no longer need this method at all, since we're not testing error propagation anymore.

**Comment by erikgrinaker** [comment]
bors r=knz,tbg

**Comment by erikgrinaker** [comment]
bors r-

Seeing a CI hang in `TestDecommissionedNodeCannotConnect`, investigating.

**Comment by erikgrinaker** [comment]
bors r=knz,tbg

**Pull request merged**
