### PR TITLE
kv: ensure secondary tenants route follower reads to the closest replica

### LINKED ISSUE #81000: kvcoord: secondary tenants do not take network latency into account when routing batch requests
**Describe the problem**

The `DistSender` sends batch requests that interact with a range to its replicas. In general, it does so by ordering replicas based on the latency between the requesting node and the node on which the replica lives. If the request must be sent to the leaseholder (and the leaseholder is known) the leaseholder is moved to the front of the queue. See:

https://github.com/cockroachdb/cockroach/blob/4d1f40b992b5f2406bf37b22f59a6f4bc5491d12/pkg/kv/kvclient/kvcoord/dist_sender.go#L1951-L1975

For follower read requests, this has the effect that they are always routed to the nearest replica. Unfortunately, this doesn't work quite as intended for secondary tenants. Instead, because a secondary tenant's `DistSender` is unaware of which node it is running on, it ends up randomly ordering the replica slice because of: 

https://github.com/cockroachdb/cockroach/blob/4d1f40b992b5f2406bf37b22f59a6f4bc5491d12/pkg/kv/kvclient/kvcoord/replica_slice.go#L205-L208

To see why a secondary tenant's dist sender is unaware of which node it is running on, it's because this cast fails:
https://github.com/cockroachdb/cockroach/blob/cc155a1efe057be7d9432d160744186059767140/pkg/kv/kvclient/kvcoord/dist_sender.go#L564-L568
@nvanbenschoten was this the hazard you had in mind in the TODO above, or is there more here?

**To Reproduce**

I discovered this when trying to convert our `follower_reads` roachtest to run as secondary tenants. TODO(arul): link a WIP PR. 

**Expected behavior**

Secondary tenants should take network latency into account when routing requests. Consequently, follower reads issued by secondary tenants should be served from the nearest replica (instead of a random one).

**Additional context**

We'd want to solve this to harness many of the benefits listed in https://github.com/cockroachdb/cockroach/issues/72593 for secondary tenants. 

cc @cockroachdb/kv 

Jira issue: CRDB-15402

Epic: CRDB-14202

### PR DESCRIPTION
**Pull request by arulajmani**
The dist sender uses node locality information to rank replicas of a
range by latency. Previously, this node locality information was read
off a node descriptor available in Gossip. Unfortunately, secondary
tenants do not have access to Gossip, and as such, would end up
randomizing this list of replicas. This manifested itself through
unpredictable latencies when running follower reads.

We're no longer susceptible to this hazard with this patch. This is done
by eschewing the need of a node descriptor from gossip in the
DistSender; instead, we now instantiate the DistSender with locality
information.

However, we do still use Gossip to get the current node's
ID when ranking replicas. This is done to ascertain if there is a local
replica, and if there is, to always route to it. Unfortunately, because
secondary tenants don't have access to Gossip, they can't conform to
these semantics. They're susceptible to a hazard where a request may
be routed to another replica in the same locality tier as the client
even though the client has a local replica as well. This shouldn't be
a concern in practice given the diversity heuristic.

Resolves https://github.com/cockroachdb/cockroach/issues/81000

Release note (bug fix): fix an issue where secondary tenants could
route follower reads to a random, far away replica instead of one
closer.

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten, I'm planning on tacking on a third commit that removes the use of `getNodeDescriptor` on here, but other than that this should be good for a look.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @nvanbenschoten, and @smg260)

___
*[`-- commits` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93aCmD8bvNLDXsAdr5):*
This also shouldn't be a concern in practice because tenant SQL pods don't run in process with KV nodes.
___
*[`pkg/kv/kvserver/replica_follower_read.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93bJ9Y4bJI5Y9b91pm:-N93bJ9Y4bJI5Y9b91pn:bd2om4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2742534184eb64e3b28ccece50b7cab5a8050a/pkg/kv/kvserver/replica_follower_read.go#L105)):*
> ```Go
> 	// TODO(tschottdorf): once a read for a timestamp T has been served, the replica may
> 	// serve reads for that and smaller timestamps forever.
> 	log.Eventf(ctx, "%s; query timestamp below closed timestamp by %s", safedetails.Safe(kvbase.FollowerReadServingMsg), -tsDiff)
> ```

I think you want `redact.Safe`. This function is deprecated and not used elsewhere.
___
*[`pkg/server/node.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93a0Oa5nTh1sjlv9j4:-N93a0Oa5nTh1sjlv9j5:b-gzzr4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L155)):*
> ```Go
> 		settings.NonNegativeDurationWithMaximum(maxGraphiteInterval),
> 	).WithPublic()
> 	redactServerTracesForSecondaryTenants = settings.RegisterBoolSetting(
> ```

It's probably worthwhile to have @knz take a look at this commit as well.
___
*[`pkg/server/node.go` line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93_tmL0VXZMWzZRUo8:-N93_tmL0VXZMWzZRUo9:b-uqv41c) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L1168)):*
> ```Go
> 	ctx context.Context, tenID roachpb.TenantID, ba *roachpb.BatchRequest,
> ) (context.Context, spanForRequest) {
> 	return setupSpanForIncomingRPC(ctx, tenID, ba, n.storeCfg.AmbientCtx.Tracer, n.settings)
> ```

Do we need to add the new field to `Node`? Isn't this the same as `n.storeCfg.Settings`?
___
*[`pkg/server/server.go` line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93bbzU0GUkj9Utx6eN:-N93bbzU0GUkj9Utx6eO:brspz3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2742534184eb64e3b28ccece50b7cab5a8050a/pkg/server/server.go#L358)):*
> ```Go
> 	}
> 	retryOpts.Closer = stopper.ShouldQuiesce()
> 	distSenderCfg := kvcoord.DistSenderConfig{
> ```

nit here and in `tenant.go`: keep the fields in the same order as in the struct definition.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93btsGCI8GWm42nuOE:-N93btsGCI8GWm42nuOF:b-nzhcal) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2742534184eb64e3b28ccece50b7cab5a8050a/pkg/sql/physicalplan/replicaoracle/oracle.go#L178)):*
> ```Go
> 		return roachpb.ReplicaDescriptor{}, err
> 	}
> 	replicas.OptimizeReplicaOrder(o.nodeDesc.NodeID, o.latencyFunc, o.nodeDesc.Locality)
> ```

How does this work in a multi-tenant cluster? Is `o.nodeDesc` empty? Do we need to plumb in the locality here as well so that DistSQL planning is handled properly as well? I think that might mean doing the same `NodeDescriptor` -> `(NodeID, Locality)` switch in `DistSQLPlanner.SetSQLInstanceInfo` and `physicalplan.NewSpanResolver`.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @knz, @nvanbenschoten, and @smg260)

___
*[`pkg/kv/kvserver/replica_follower_read.go` line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93bJ9Y4bJI5Y9b91pm:-N93f9hbEj0B-WAp2gaA:b-fl54in) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2742534184eb64e3b28ccece50b7cab5a8050a/pkg/kv/kvserver/replica_follower_read.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you want `redact.Safe`. This function is deprecated and not used elsewhere.
</blockquote></details>

Faster than CI haha 
___
*[`pkg/server/node.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93a0Oa5nTh1sjlv9j4:-N93fDJGElgYLKAsgkFJ:bk27100) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L155)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's probably worthwhile to have @knz take a look at this commit as well.
</blockquote></details>

I was initially going with a testing knob, but @ajstorm mentioned on Slack that we might want a cluster setting here instead. Rafa, lemme know what you think as well!

**Review by arulajmani — COMMENTED** [review]
Thanks for the quick look, addressed your comments, should be good for another pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-:-N97tKZZAlUhCSndKr-1:b-4bsmrk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @knz, @nvanbenschoten, and @smg260)

___
*[`-- commits` line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93aCmD8bvNLDXsAdr5):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This also shouldn't be a concern in practice because tenant SQL pods don't run in process with KV nodes.
</blockquote></details>

Good point, amended the commit message. 
___
*[`pkg/server/node.go` line 1168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93_tmL0VXZMWzZRUo8:-N97bSMD0PFPcv21gxEr:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L1168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to add the new field to `Node`? Isn't this the same as `n.storeCfg.Settings`?
</blockquote></details>

Done. 
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93btsGCI8GWm42nuOE:-N97n1Jv1LYgs7p9UeIO:bqmv16f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2742534184eb64e3b28ccece50b7cab5a8050a/pkg/sql/physicalplan/replicaoracle/oracle.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this work in a multi-tenant cluster? Is `o.nodeDesc` empty? Do we need to plumb in the locality here as well so that DistSQL planning is handled properly as well? I think that might mean doing the same `NodeDescriptor` -> `(NodeID, Locality)` switch in `DistSQLPlanner.SetSQLInstanceInfo` and `physicalplan.NewSpanResolver`.
</blockquote></details>

You're right, made the change in the last commit. It might be worth syncing with someone from queries/@ajstorm about the effects of this change and if we can unblock some tests for secondary tenants given this change.

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 16 of 16 files at r4, 2 of 2 files at r5, 13 of 13 files at r6, 2 of 2 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @knz, and @smg260)

___
*[`pkg/server/server.go` line 1395 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9804HHAVjdOvIHMfzM:-N9804HHAVjdOvIHMfzN:bxhtivu) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f2d6e40cce1e1f91dd954e330806fb5121c005/pkg/server/server.go#L1395)):*
> ```Go
> 		func(desc roachpb.NodeDescriptor) {
> 			s.sqlServer.execCfg.DistSQLPlanner.SetGatewaySQLInstanceID(base.SQLInstanceID(desc.NodeID))
> 			s.sqlServer.execCfg.DistSQLPlanner.MaybeConstructAndSetSpanResolver(desc.NodeID, desc.Locality)
> ```

Should we use `s.cfg.Locality` so we maintain consistency with the locality information used by `DistSender`, instead of passing through the `NodeDescriptor`?

EDIT: actually, this `nodeDescriptorCallback` handling seems awkward and unnecessary. I think we can get rid of it now that we're operating on NodeID and Locality, both of which are passed in to `s.node.start`.

**Review by arulajmani — COMMENTED** [review]
I also modified one of the oracle tests to actually make use of the locality information. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-:-N98f3nbCHaOUnF-HKaE:b-8e0f6d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @knz, @nvanbenschoten, and @smg260)

___
*[`pkg/server/server.go` line 1395 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9804HHAVjdOvIHMfzM:-N98f2mC7EIiXFyMwN7K:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/47f2d6e40cce1e1f91dd954e330806fb5121c005/pkg/server/server.go#L1395)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we use `s.cfg.Locality` so we maintain consistency with the locality information used by `DistSender`, instead of passing through the `NodeDescriptor`?

EDIT: actually, this `nodeDescriptorCallback` handling seems awkward and unnecessary. I think we can get rid of it now that we're operating on NodeID and Locality, both of which are passed in to `s.node.start`.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r9, 2 of 2 files at r10, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-:-N98iD-v4H_BiCZ8tXT3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @knz, and @smg260)

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 16 files at r4, 1 of 2 files at r5, 7 of 13 files at r6, 1 of 11 files at r9, 2 of 2 files at r10, 10 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @smg260)

___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go` line 307 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BEXfqAPb_G2V2eHbo:-N9BEXfqAPb_G2V2eHbp:b8nvvrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go#L307)):*
> ```Go
> 		// down in kvserver we disable their redaction.
> 		systemTenantSQL := sqlutils.MakeSQLRunner(tc.StorageClusterConn())
> 		systemTenantSQL.Exec(t, `SET CLUSTER SETTING server.secondary_tenants.redact_trace.enabled = 'false'`)
> ```

This might cause the test to flake. Have you thought about a setting override instead?
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 792 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BEih8C1B2wzvWKVgQ:-N9BEih8C1B2wzvWKVgR:b-uty4d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L792)):*
> ```Go
> 		// use follower_read_timestamp(). Note that we need to override the setting
> 		// for the tenant as well, because the builtin is run in the tenant's sql pod.
> 		systemSQL := sqlutils.MakeSQLRunner(tc.Conns[0])
> ```

Have you thought about setting overrides, instead of this and the wait loop below?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 562 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BEDRT76fGUwdjujaq:-N9BEDRT76fGUwdjujar:b-k9j5ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/kv/kvclient/kvcoord/dist_sender.go#L562)):*
> ```Go
> 	// replica (if one exists). Not knowing the node ID, and thus not being able
> 	// to take advantage of this optimization is okay, given secondary tenants
> 	// run in separate processes to KV nodes (so there's no optimization to take
> ```

See my other comments: secondary tenants can definitely run in-process with KV instances.

The comment is incorrect, even though the logic is fine. What matters is not secondary vs system tenant; is in-process vs separate-process.

The comment should explain "the node ID optimization is only available to tenants running in-process; if they are not, it doesn't matter anyway because the connection will be networked in the end."
___
*[`pkg/server/node.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93a0Oa5nTh1sjlv9j4:-N9BCDDTCLw6IQe5NalS:b-eeadnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I was initially going with a testing knob, but @ajstorm mentioned on Slack that we might want a cluster setting here instead. Rafa, lemme know what you think as well! 
</blockquote></details>

A setting looks fine.

Why TenantReadOnly though? Is this not SystemOnly? (the redaction occurs on the kv side, right?)
___
*[`pkg/server/node.go` line 1123 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDtJ85pbB5NJl1nEy:-N9BDtJ85pbB5NJl1nEz:b-uqh86b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/server/node.go#L1123)):*
> ```Go
> 		// (and tenID might be set), but it will go to the tenant only indirectly
> 		// through the response of a parent RPC. In that case, the parent RPC is
> 		// responsible for the redaction.
> ```

See my other comments about same-process vs different-process: secondary tenants may run inside the same process, and may use the local connector. I'm not sure this paragraph is correct.

However, does it matter though? It doesn't look like the condition you've implemented is sensitive to the deployment style?
___
*[`pkg/server/server.go` line 1304 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BCbgH1Imn_soU8lZg:-N9BCbgH1Imn_soU8lZh:b-mp07ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/server/server.go#L1304)):*
> ```Go
> 	// Ensure components in the DistSQLPlanner that rely on the node ID are
> 	// initialized before store startup continues.
> 	s.sqlServer.execCfg.DistSQLPlanner.SetGatewaySQLInstanceID(base.SQLInstanceID(state.nodeID))
> ```

Why is this done here and not in `server_sql.go`, `newSQLServer`? 
___
*[`pkg/sql/distsql_physical_planner.go` line 228 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BCych7bWQoyp_XhAS:-N9BCych7bWQoyp_XhAT:by1udfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/distsql_physical_planner.go#L228)):*
> ```Go
> // MaybeConstructAndSetSpanResolver constructs and sets the planner's
> // SpanResolver if it is unset. It's a no-op otherwise.
> // TODO(arul): Should we get rid of this maybe and just fatal if it's set
> ```

Yes that sounds right. Or panic/return an assertion error.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 156 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDAxk-9HwfUnW_f3f:-N9BDAxk-9HwfUnW_f3g:b-qcqe82) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/physicalplan/replicaoracle/oracle.go#L156)):*
> ```Go
> 	// NodeID may be 0 (and is expected to be in case of secondary tenants), in
> 	// which case the current node will not be given any preference. This is sane,
> 	// given secondary tenant SQL pods are never run in process with KV nodes.
> ```

This comment is incorrect. tenant SQL pods *will* run in-process with KV nodes, sooner than later.

I think the semantics are OK, but you need to explain them differently here (and possibly in the commit message):

```
// NodeID may be zero, to indicate there is no KV instance available inside the same process.
// If there is a same-process KV instance, we prefer that if it contains a replica.
```
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 210 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDkuu9fNnJzXxQh_v:-N9BDkuu9fNnJzXxQh_w:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/physicalplan/replicaoracle/oracle.go#L210)):*
> ```Go
> 	// current node and others "close" to it.
> 	//
> 	// NodeID may be 0 (and is expected to be in case of secondary tenants), in
> ```

ditto

**Review by arulajmani — COMMENTED** [review]
> Dismissed @knz from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85853)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, @knz, @nvanbenschoten, and @smg260)

___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go` line 307 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BEXfqAPb_G2V2eHbo:-N9SL-d441bbB3GI5-3f:b5ilptg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go#L307)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This might cause the test to flake. Have you thought about a setting override instead?
</blockquote></details>

I realized this getting this test to work with secondary tenants is a bit harder than what I'd initially thought, given it makes use of SQL testing knobs that aren't passed into the `TestTenant`. Ended up reverting this.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 562 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BEDRT76fGUwdjujaq:-N9SKVlr0q7H59ZOGIFN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/kv/kvclient/kvcoord/dist_sender.go#L562)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

See my other comments: secondary tenants can definitely run in-process with KV instances.

The comment is incorrect, even though the logic is fine. What matters is not secondary vs system tenant; is in-process vs separate-process.

The comment should explain "the node ID optimization is only available to tenants running in-process; if they are not, it doesn't matter anyway because the connection will be networked in the end."
</blockquote></details>

Done.
___
*[`pkg/server/node.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N93a0Oa5nTh1sjlv9j4:-N9S92DnDroLW8m1uMmw:b-t5bpq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/65d6eb9d07679a8899ccccfa6f3fce6faaa4f797/pkg/server/node.go#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

A setting looks fine.

Why TenantReadOnly though? Is this not SystemOnly? (the redaction occurs on the kv side, right?)
</blockquote></details>

D'op, switched to SystemOnly. 
___
*[`pkg/server/node.go` line 1123 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDtJ85pbB5NJl1nEy:-N9SIfLc2JLwuRO6O7x3:b-hi6mo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/server/node.go#L1123)):*
>However, does it matter though? It doesn't look like the condition you've implemented is sensitive to the deployment style?

Yeah, I'm not quite sure what this paragraph was trying to say and much of this was here before I got here. Removed the stuff around deployment styles. 
___
*[`pkg/server/server.go` line 1304 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BCbgH1Imn_soU8lZg:-N9SDfVjAMjRpjY9H7Gd:b-stt2xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/server/server.go#L1304)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why is this done here and not in `server_sql.go`, `newSQLServer`? 
</blockquote></details>

I'm definitely not intimate with this code, but from my reading we only get to know our `NodeID` in when trying to Start the server (in `PreStart`) so this is where we bind it. 
___
*[`pkg/sql/distsql_physical_planner.go` line 228 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BCych7bWQoyp_XhAS:-N9SC5h88ObyYxRqaoaD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/distsql_physical_planner.go#L228)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes that sounds right. Or panic/return an assertion error.
</blockquote></details>

Done.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 156 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDAxk-9HwfUnW_f3f:-N9SHdw17OoyD7uBCTSV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/physicalplan/replicaoracle/oracle.go#L156)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This comment is incorrect. tenant SQL pods *will* run in-process with KV nodes, sooner than later.

I think the semantics are OK, but you need to explain them differently here (and possibly in the commit message):

```
// NodeID may be zero, to indicate there is no KV instance available inside the same process.
// If there is a same-process KV instance, we prefer that if it contains a replica.
```
</blockquote></details>

Done.
___
*[`pkg/sql/physicalplan/replicaoracle/oracle.go` line 210 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/85853#-N9BDkuu9fNnJzXxQh_v:-N9SH7om3yEs5i15Qmy9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de875fc7548cf1f288f2443621bfda5de861f9e/pkg/sql/physicalplan/replicaoracle/oracle.go#L210)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by arulajmani** [comment]
TFTRs! 

bors r+

**Pull request merged**
