### PR TITLE
sql: deflake TestIdleCancelSession

### LINKED ISSUE #36645: sql: TestIdleCancelSession failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/59247ae2b8276c7f5e6f58080547096a52818cc8

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stress TESTS=TestIdleCancelSession PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1229359&tab=buildLog

```
I190409 06:01:34.504129 99096 server/node.go:672  [n2] bootstrapped store [n2,s2]
I190409 06:01:34.504247 99096 server/node.go:546  [n2] node=2: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I190409 06:01:34.504534 99096 server/status/recorder.go:609  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I190409 06:01:34.504557 99096 server/server.go:1820  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I190409 06:01:34.504625 99096 server/server.go:1534  [n2] starting https server at 127.0.0.1:39535 (use: 127.0.0.1:39535)
I190409 06:01:34.504640 99096 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:37471
I190409 06:01:34.504652 99096 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:37471
I190409 06:01:34.508391 99096 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I190409 06:01:34.508413 99096 server/server.go:1593  [n2] serving sql connections
I190409 06:01:34.523960 99579 rpc/nodedialer/nodedialer.go:95  [n1] unable to connect to n2: failed to resolve n2: unable to look up descriptor for n2
I190409 06:01:34.527554 99361 server/server_update.go:67  [n2] no need to upgrade, cluster already at the newest version
I190409 06:01:34.528314 99099 storage/stores.go:261  [n1] wrote 1 node addresses to persistent storage
I190409 06:01:34.533400 99571 sql/event_log.go:126  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:37471} Attrs: Locality: ServerVersion:2.1 BuildTag:v2.1.6-24-g59247ae StartedAt:1554789694502505637 LocalityAddress:[]} ClusterID:df672c4e-689f-4ea4-84fa-d9a0b76e9bb7 StartedAt:1554789694502505637 LastUp:1554789694502505637}
I190409 06:01:35.324449 99784 storage/replica_consistency.go:127  [n1,consistencyChecker,s1,r1/1:/M{in-ax}] triggering stats recomputation to resolve delta of {ContainsEstimates:true LastUpdateNanos:1554789694516643996 IntentAge:0 GCBytesAge:0 LiveBytes:-44656 LiveCount:-932 KeyBytes:-43412 KeyCount:-932 ValBytes:-1244 ValCount:-932 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I190409 06:01:35.977933 99434 gossip/gossip.go:1489  [n2] node has connected to cluster via gossip
I190409 06:01:35.978141 99434 storage/stores.go:261  [n2] wrote 1 node addresses to persistent storage
I190409 06:01:36.200191 99136 gossip/gossip.go:1489  [n1] node has connected to cluster via gossip
I190409 06:01:36.200398 99136 storage/stores.go:261  [n1] wrote 1 node addresses to persistent storage
I190409 06:01:44.318445 99323 server/status/runtime.go:465  [n1] runtime stats: 188 MiB RSS, 654 goroutines, 23 MiB/60 MiB/105 MiB GO alloc/idle/total, 17 MiB/54 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (707x), 83 MiB/83 MiB (r/w)net
W190409 06:01:44.361478 99325 server/node.go:886  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:1}]}
I190409 06:01:44.508571 99535 server/status/runtime.go:465  [n2] runtime stats: 189 MiB RSS, 654 goroutines, 28 MiB/55 MiB/105 MiB GO alloc/idle/total, 17 MiB/54 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (707x), 83 MiB/83 MiB (r/w)net
E190409 06:01:44.524555 99391 sql/distsqlrun/flow_registry.go:230  [intExec=read orphaned table leases] flow id:3a11ca53-bcd6-4d0f-8e59-9b6fc1d1ac38 : 1 inbound streams timed out after 10s; propagated error throughout flow
I190409 06:01:44.875719 99941 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I190409 06:01:44.875824 99940 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W190409 06:01:44.880748 99434 gossip/gossip.go:1475  [n2] no incoming or outgoing connections
I190409 06:01:44.882309 99941 util/stop/stopper.go:537  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
--- FAIL: TestIdleCancelSession (10.62s)
	run_control_test.go:321: expected 2 sessions but found 3

```

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #36645.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thank you for the new test!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37071#-:-LdDGr8T7ER5qgUkyPcI:b-he441f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/run_control_test.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37071#-LdDGC_M3BFSpAaBRx4j:-LdDGC_N-5rWIRtCJZrm:bnrnl8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/209e286152b0ccbc191d92095cdf36792bbe9d0c/pkg/sql/run_control_test.go#L227)):*
> ```Go
> 		// Exclude internal session (they have $ in their app name)
> 		rows, err := conn2.QueryContext(ctx,
> 			"SELECT * FROM [SHOW CLUSTER SESSIONS] WHERE application_name NOT LIKE '$'")
> ```

1) I think you're missing a `%` pattern in that LIKE argument

2) Maybe add a `const SharedAppNamePrefix = "$"` alongside the others in `app_stats.go` and use that here, to avoid a hard dependency on the $ character

**Comment by jordanlewis** [comment]
Done, TFTR!

**Review by knz — APPROVED** [review]
ok (I trust that you're ok with `ReportableAppNamePrefix` which expands to `$` + space—i.e. not just `"$"`—to ensure the test doesn't flake)

**Comment by jordanlewis** [comment]
Yes, thanks!

**Comment by jordanlewis** [comment]
Heh, looks like the test @danhhz suggested in #28033 is still catching a race. Thanks, Dan!

**Pull request closed without merging**
