### PR TITLE
opt: Infer types for opt scalar expressions.

### PR DESCRIPTION
**Pull request by andy-kimball**
Add a Scalar field to the LogicalProps struct, containing a Type
field. Populate the type field when the logical properties are
constructed. A leaf expression gets its type from its private field.
A non-leaf expression infers its type from its children. These types
will be used to build the planner tree.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/build/builder.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4K87PySzL5fxqbR9fi:-L4K87PySzL5fxqbR9fj:b-c4ktae) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/build/builder.go#L50)):*
> ```Go
> 	tree.RegIMatch:         (opt.Factory).ConstructRegIMatch,
> 	tree.NotRegIMatch:      (opt.Factory).ConstructNotRegIMatch,
> 	tree.IsDistinctFrom:    (opt.Factory).ConstructIsNot,
> ```

Thank you! :) "is not distinct from" is terrible phrasing

---

*[pkg/sql/opt/xform/expr.go, line 175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MHf7X9uizeq7DmFxR:-L4MHf7X9uizeq7DmFxS:b-j4nz9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/expr.go#L175)):*
> ```Go
> 	// Don't panic if scalar properties don't yet exist when printing
> 	// expression.
> 	if scalar != nil {
> ```

[nit] Maybe we want `type=unknown` in the scalar=nil case so it's more visible (in case there's a bug).

---

*[pkg/sql/opt/xform/logical_props_factory.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MIplEw0QS09bH0YO2:-L4MIplEw0QS09bH0YO3:b-o158xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/logical_props_factory.go#L215)):*
> ```Go
> func (f *logicalPropsFactory) constructScalarProps(ev *ExprView) (props LogicalProps) {
> 	props.Scalar = &ScalarProps{Type: inferType(ev)}
> 	return
> ```

[nit] `return props` or `return LogicalProps{Scalar: ...}` (we try to avoid naked returns).

---

*[pkg/sql/opt/xform/typing.go, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MMbZr0yHCYqf5vkok:-L4MMbZr0yHCYqf5vkol:b-utkz17) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/typing.go#L57)):*
> ```Go
> 		opt.OrOp:                typeAsBool,
> 		opt.NotOp:               typeAsBool,
> 		opt.EqOp:                typeAsBool,
> ```

[nit] I'm wondering if it would be useful to define some static arrays `ComparisonOps = [...]Operator{EqOp, .. }`, `boolOps`, etc. and use those to initialize arrays like this. It would cut down on the places that need modification if we add/change operators.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-:-L4MNgMPj1U5At6DQqUC:b-uwkowd)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-:-L4MSbnRT1Vk6oWTPWzc:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/expr.go, line 175 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MHf7X9uizeq7DmFxR:-L4NICBehD84_7eYoNjz:b9dasgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/expr.go#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Maybe we want `type=unknown` in the scalar=nil case so it's more visible (in case there's a bug).
</blockquote></details>

OK, I set type=undefined.

---

*[pkg/sql/opt/xform/logical_props_factory.go, line 215 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MIplEw0QS09bH0YO2:-L4NIljfwHeb3Z_CC30R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/logical_props_factory.go#L215)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `return props` or `return LogicalProps{Scalar: ...}` (we try to avoid naked returns).
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/typing.go, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MMbZr0yHCYqf5vkok:-L4NIsGQT8ECCbUIDlrv:b-83q7g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/typing.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'm wondering if it would be useful to define some static arrays `ComparisonOps = [...]Operator{EqOp, .. }`, `boolOps`, etc. and use those to initialize arrays like this. It would cut down on the places that need modification if we add/change operators.
</blockquote></details>

I'm not sure I follow. Can you give a more complete example?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/xform/typing.go, line 57 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319#-L4MMbZr0yHCYqf5vkok:-L4Nh2OriSkdXO1OMLu7:bbkwjg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/typing.go#L57)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm not sure I follow. Can you give a more complete example?
</blockquote></details>

If we had a `ComparisonOps = [...]Operator{EqOp, LtOp, etc}` we could do
`for _, o := range opt.ComparisonOps { typingFuncMap[o] = typeAsBool }`
Similar for bool ops, bit ops, binary ops, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22319)*

**Comment by andy-kimball** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/xform/typing.go, line 57 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22319#-L4MMbZr0yHCYqf5vkok:-L4Nic5-AJHP1by4js1l:b-9s5y7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/99c34274a3a4d7df7dcdcde4d3add7405236114e/pkg/sql/opt/xform/typing.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we had a `ComparisonOps = [...]Operator{EqOp, LtOp, etc}` we could do
`for _, o := range opt.ComparisonOps { typingFuncMap[o] = typeAsBool }`
Similar for bool ops, bit ops, binary ops, etc.
</blockquote></details>

Ah, interesting. We could do that by tagging the operators and then having that code auto-generated. I'll think about it more and perhaps put it in a separate PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22319)*

**Pull request merged**
