### PR TITLE
sqlccl: return job information in RESTORE

### PR DESCRIPTION
**Pull request by benesch**
Adjust RESTORE queries to return the same columns as BACKUP, namely,
`job_id`, `status`, and `fraction_completed`. See fb5edc6 for rationale
behind these fields.

### CODE REVIEW

**Comment by benesch** [comment]
FYI I do not understand the implications of switching out `batch.Run` for `client.SendWrappedWith`. I just made `Restore` look like `Backup`.

**Comment by danhhz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/restore.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbwvtTawDEm_695pL3:-KhbwvtTawDEm_695pL4:b-eevl8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/ccl/sqlccl/restore.go#L81)):*
> ```Go
> 		KeyRewrites: kr,
> 	}
> 	res, pErr := client.SendWrappedWith(ctx, db.GetSender(), roachpb.Header{}, req)
> ```

`client.SendWrapped` is the same but it specifies the empty header for you

This seems fine to me. I never liked the AddRawRequest call we had. When we added the SendWrappedWith in Backup, ben mentioned that it had traditionally been used for testing code, but that there was no real reason not to use it there

---

*[pkg/ccl/storageccl/import.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbvWQyzoGvudb2kfBy:-KhbvWQyzoGvudb2kfBz:b-k1wkkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/ccl/storageccl/import.go#L56)):*
> ```Go
> 
> 	if err := beginLimitedRequest(ctx); err != nil {
> 		return nil, err
> ```

you're inconsistently using nil vs &roachpb.ImportResponse{} when an error is returned. Either always return nil or make this return a non-pointer roachpb.ImportResponse (the former if the semantic of that are okay, I don't know offhand)

---

*[pkg/roachpb/api.proto, line 831 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbuwsQ7Urzd3PlttyX:-KhbuwsQ7Urzd3PlttyY:b32vch) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/roachpb/api.proto#L831)):*
> ```protobuf
> message ImportResponse {
>   optional ResponseHeader header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   optional int64 data_size = 3 [(gogoproto.nullable) = false];
> ```

3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861)*

**Comment by benesch** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/restore.go, line 81 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbwvtTawDEm_695pL3:-KhcINUWlGSWJw2GSIdP:b-neuz60) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/ccl/sqlccl/restore.go#L81)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

`client.SendWrapped` is the same but it specifies the empty header for you

This seems fine to me. I never liked the AddRawRequest call we had. When we added the SendWrappedWith in Backup, ben mentioned that it had traditionally been used for testing code, but that there was no real reason not to use it there
</blockquote></details>

Gotcha! Done.

---

*[pkg/ccl/storageccl/import.go, line 56 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbvWQyzoGvudb2kfBy:-KhcIPqI1KPuqncurlpr:b-8ztt1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/ccl/storageccl/import.go#L56)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

you're inconsistently using nil vs &roachpb.ImportResponse{} when an error is returned. Either always return nil or make this return a non-pointer roachpb.ImportResponse (the former if the semantic of that are okay, I don't know offhand)
</blockquote></details>

Made them all `nil`.

---

*[pkg/roachpb/api.proto, line 831 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-KhbuwsQ7Urzd3PlttyX:-KhcIRZk_fuxhD59HBKo:b-yzr9pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0810af7bb63798f6a8357a7474fddd4254d7a2b9/pkg/roachpb/api.proto#L831)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

3?
</blockquote></details>

Hah, thanks. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861)*

**Comment by danhhz** [comment]
LGTM

Reference  in 14296 the commit message, plz.

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 236 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-Khwt3PP3inbYfh2IWtz:-Khwt3PQRYD-nduRfwXl:b-mor743) ([raw file](https://github.com/cockroachdb/cockroach/blob/921909c4e009dd6516fa561a3dba6feaac2a07c8/pkg/ccl/sqlccl/backup_test.go#L236)):*
> ```Go
> func TestBackupRestoreStatementResult(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	if !storage.ProposerEvaluatedKVEnabled() {
> ```

no longer necessary (merge skew)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14861#-:-Khwtv0DMzptP7UPTNus:b-lmz5ua)*

**Pull request merged**
