### PR TITLE
storage: handle snapshots that span merges

### PR DESCRIPTION
**Pull request by benesch**
This needs a fair bit of cleanup, but I wanted to get it out for early review. Does this general approach seem reasonable? I'm actually kind of shocked by how little code is involved.

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/helpers_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJobblF9J8AqKGMdP8m:-LJobblF9J8AqKGMdP8n:bc8hm54) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/helpers_test.go#L239)):*
> ```Go
> 
> // CheckConsistency verifies that the store's bookkeping is self-consistent.
> func (s *Store) CheckConsistency() {
> ```

This name is confusingly similar to Replica.CheckConsistency (sounds like it might be a wrapper for calling CheckConsistency on all Replicas). 
___
*[pkg/storage/replica.go, line 3938 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoi7wmArcD0AUBu-kh:-LJoi7wnCNCgkx5MhahW:ba2ri6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3938)):*
> ```Go
> 			}
> 			repl.raftMu.Lock()
> 			subsumedRepls = append(subsumedRepls, repl)
> ```

How do we know that we're subsuming this replica, instead of the RHS being the result of a split that postdates this snapshot? 
___
*[pkg/storage/replica.go, line 3966 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJohmIq3DbKWEpx0eWl:-LJohmIq3DbKWEpx0eWm:b-n2shkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3966)):*
> ```Go
> 				atomic.AddInt32(&r.store.counts.filledPlaceholders, 1)
> 			}
> 			r.store.mu.Unlock()
> ```

I don't think this is safe - we need to process the range descriptor update under the same lock of Store.mu as removing the placeholder. 
___
*[pkg/storage/replica_raftstorage.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoed6j0otE2WtWVjGL:-LJoed6j0otE2WtWVjGM:beml6i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica_raftstorage.go#L881)):*
> ```Go
> 	oldDesc := r.mu.state.Desc
> 	r.mu.state = s
> 	r.mu.state.Desc = oldDesc // TODO(benesch): ewwwww
> ```

For a slightly less gross version, how about

    s.Desc = r.mu.state.Desc
    r.mu.state = s

Either way, this needs commentary about why we're keeping the old desc in place. 

If the old descriptor was uninitialized, do we need to preserve it? 


I'm concerned about the atomicity of this change. We've written keys to disk that are not reflected in the replica's (in-memory) descriptor. We haven't even necessarily added a placeholder to the store (right?). We need to install placeholders for any keyspace that will be written where we don't currently have a replica to subsume. 

I can't remember the history behind the `setDescWithoutProcessUpdate`/`processRangeDescriptorUpdate` split, but I'm not sure it's safe to move the pieces across critical sections like this.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/helpers_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJobblF9J8AqKGMdP8m:-LJomfEL2GwPqwVROVpi:brt7nv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/helpers_test.go#L239)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This name is confusingly similar to Replica.CheckConsistency (sounds like it might be a wrapper for calling CheckConsistency on all Replicas). 
</blockquote></details>

Hmm. How about `CheckMetadata`?
___
*[pkg/storage/replica.go, line 3938 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoi7wmArcD0AUBu-kh:-LJomhLnEjfGc1pEyzlc:b-dssxtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3938)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How do we know that we're subsuming this replica, instead of the RHS being the result of a split that postdates this snapshot? 
</blockquote></details>

If this replica receives a Raft snapshot that spans a merge, we know that, at the time of the merge, its store contained the RHS of the merge. The replica GC queue won't be able to remove that replica of the RHS until the merge applies (via that left-looking generation checker from the last PR), so we won't be able to accept snapshots for new, split ranges. So these ranges are guaranteed to be ours to subsume.

I'll put that all in a comment in the next revision for sure.
___
*[pkg/storage/replica.go, line 3966 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJohmIq3DbKWEpx0eWl:-LJonRR4AzldMgSsTmTR:b-uujbzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3966)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think this is safe - we need to process the range descriptor update under the same lock of Store.mu as removing the placeholder. 
</blockquote></details>

Good point. This should be easy enough to do with a `setDescStoreMuLocked` (ew) or hopefully something better I come up with.
___
*[pkg/storage/replica_raftstorage.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoed6j0otE2WtWVjGL:-LJonx2T8lYOyAYq5WhW:b-lo7at) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica_raftstorage.go#L881)):*
> I'm concerned about the atomicity of this change. We've written keys to disk that are not reflected in the replica's (in-memory) descriptor.

Yeah, so am I. I think we need to make these replica removals atomic with the application of the merge's EndTxn. The only reason I restructured all this `setDesc` stuff was to avoid tripping over an overlapping ranges assertion in `Store.removeReplicaImpl`. You can't remove replica [b, c) once [a, b)'s in memory descriptor is [a, c).

FWIW the non-snapshot path suffers from this non-atomicity too. 

> We haven't even necessarily added a placeholder to the store (right?). We need to install placeholders for any keyspace that will be written where we don't currently have a replica to subsume.

We always have a replica to subsume now that we require ranges to be collocated before merging.

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/helpers_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJobblF9J8AqKGMdP8m:-LJsPfGICD5rU_uJS-9w:bx9ashc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/helpers_test.go#L239)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Hmm. How about `CheckMetadata`?
</blockquote></details>

SGTM, or `AssertInvariants`.
___
*[pkg/storage/replica.go, line 3942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJsQ9ok4ZArdxrZBMUV:-LJsQ9ok4ZArdxrZBMUW:b-ffhqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3942)):*
> ```Go
> 		}
> 		if !endKey.Equal(inSnap.State.Desc.EndKey) {
> 			log.Fatalf(ctx, "attempted to apply snapshot that ends in middle of replica %s", endKey)
> ```

"ends in middle" could be rephrased as "doesn't reach required end key %s"

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/helpers_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJobblF9J8AqKGMdP8m:-LJtd1yvB61JUVORnGla:bb3m1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/helpers_test.go#L239)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

SGTM, or `AssertInvariants`.
</blockquote></details>

I like `AssertInvariants`.
___
*[pkg/storage/replica_raftstorage.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoed6j0otE2WtWVjGL:-LJtg_nk77mNMxaqzdVw:b-fgoixf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica_raftstorage.go#L881)):*
> We always have a replica to subsume now that we require ranges to be collocated before merging.

Yeah, that helps and addresses a lot of my concerns. But what if our replica of the range was not the one that immediately preceded the merge?

- LHS range on A, B, C
- Rebalance to B, C, D. Replica GC does not occur for some reason. 
- Colocate RHS range to B, C, D
- Merge
- Truncate log
- Rebalance merged range back to A, B, C

Node A will receive a snapshot which will apply on top of its old copy of the LHS with no copy of the RHS. 

In this case we probably need to block the snapshot (similar to what we do for the split/snapshot race) and then treat it like an entirely new range.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_raftstorage.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoed6j0otE2WtWVjGL:-LJtl07K9dOYb11DzNA0:butjerp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica_raftstorage.go#L881)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> We always have a replica to subsume now that we require ranges to be collocated before merging.

Yeah, that helps and addresses a lot of my concerns. But what if our replica of the range was not the one that immediately preceded the merge?

- LHS range on A, B, C
- Rebalance to B, C, D. Replica GC does not occur for some reason. 
- Colocate RHS range to B, C, D
- Merge
- Truncate log
- Rebalance merged range back to A, B, C

Node A will receive a snapshot which will apply on top of its old copy of the LHS with no copy of the RHS. 

In this case we probably need to block the snapshot (similar to what we do for the split/snapshot race) and then treat it like an entirely new range. 
</blockquote></details>

Yes, that sounds right. I think we just want to forbid any preemptive snapshots that attempt to widen the existing replica.

**Comment by benesch** [comment]
I've repurposed this branch for an updated implementation. Definitely don't review yet. Still very much WIP.

**Review by benesch — COMMENTED** [review]
> I've repurposed this branch for an updated implementation. Definitely don't review yet. Still very much WIP.

I take that back. I moved some code around and now this is pretty much done. (At least, it passes the tests.) Needs a fair few comments, but I'd definitely appreciate some high-level feedback.

FYI I've rebased on top of #28683, so ignore the first few commits. I'll strip those out if/when Bors ever manages to land that stupid PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-:-LK3_47F8EadMkt5pajl:b-dhbgut)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/helpers_test.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJobblF9J8AqKGMdP8m:-LK3_-chEt1Dr7D8eCBX:bm5lu1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/helpers_test.go#L239)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I like `AssertInvariants`.
</blockquote></details>

Done. (In a different PR.)

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4068 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK3_fxr6QLf_4wm9sui:-LK3_fxr6QLf_4wm9suj:b-zaaqsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc61d798a9ced1f576b3c0dd4791820372bfa06/pkg/storage/replica.go#L4068)):*
> ```Go
> 			rhsRepl.raftMu.Lock()
> 			defer rhsRepl.raftMu.Unlock()
> 		}
> ```

FYI, thanks to the RHS up-to-dateness rules, it turns out there can only be exactly one replica to subsume. I'll write up the rationale in a comment when I get the chance.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4068 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK3_fxr6QLf_4wm9sui:-LK4vpLo046KZRvKQAIu:bd8cdf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc61d798a9ced1f576b3c0dd4791820372bfa06/pkg/storage/replica.go#L4068)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

FYI, thanks to the RHS up-to-dateness rules, it turns out there can only be exactly one replica to subsume. I'll write up the rationale in a comment when I get the chance.
</blockquote></details>

Scratch that. I don't think that's even a little bit true.

**Review by benesch — COMMENTED** [review]
Ok, I think I finally got this right. Please take a look for real!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-:-LK5NWPWCfqtOllmMLZP:b-g289lx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 3938 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoi7wmArcD0AUBu-kh:-LK5NgE-5k21Fh6-bwRJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3938)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

If this replica receives a Raft snapshot that spans a merge, we know that, at the time of the merge, its store contained the RHS of the merge. The replica GC queue won't be able to remove that replica of the RHS until the merge applies (via that left-looking generation checker from the last PR), so we won't be able to accept snapshots for new, split ranges. So these ranges are guaranteed to be ours to subsume.

I'll put that all in a comment in the next revision for sure.
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 3942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJsQ9ok4ZArdxrZBMUV:-LK5Ngft3D-U3O0xTyE3:bujoq95) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3942)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

"ends in middle" could be rephrased as "doesn't reach required end key %s"
</blockquote></details>

I went with a slightly different phrasing, but it sounds less dumb now.
___
*[pkg/storage/replica.go, line 3966 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJohmIq3DbKWEpx0eWl:-LK5NraTB2NjMoAFNWLv:b-keoomm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica.go#L3966)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Good point. This should be easy enough to do with a `setDescStoreMuLocked` (ew) or hopefully something better I come up with.
</blockquote></details>

This is reverted.
___
*[pkg/storage/replica_raftstorage.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LJoed6j0otE2WtWVjGL:-LK5O2LE1cSq8llcS9np:b7epcf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/replica_raftstorage.go#L881)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yes, that sounds right. I think we just want to forbid any preemptive snapshots that attempt to widen the existing replica.
</blockquote></details>

Fixed in #28683.

**Review by tbg — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 1690 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8XEEM77IzDCH6ZsHF:-LK8XEEM77IzDCH6ZsHG:b-ta3iin) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/client_merge_test.go#L1690)):*
> ```Go
> 	}
> 
> 	// Restore Raft traffic to the LHS on store2.
> ```

Might be worth verifying that the Raft snapshots metric increases after this point.
___
*[pkg/storage/replica.go, line 5530 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8Y7L2EgFxWxhET5Nd:-LK8Y7L2EgFxWxhET5Ne:b48i2ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica.go#L5530)):*
> ```Go
> 	endKey := r.Desc().EndKey
> 	if endKey == nil || !endKey.Less(inSnap.State.Desc.EndKey) {
> 		// The existing replica is unitialized or this snapshot does not widen the
> ```

uninitialized

If the replica is uninitialized, we're good because...?
___
*[pkg/storage/replica_raftstorage.go, line 715 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8ZLy9CChoaw_pwfdI:-LK8ZLy9CChoaw_pwfdJ:b-tzqgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L715)):*
> ```Go
> // responsibility to call r.store.processRangeDescriptorUpdate(r) after a
> // successful applySnapshot. This method requires that r.raftMu is held.
> func (r *Replica) applySnapshot(
> ```

Elsewhere we have method names like `handleEvalResultRaftMuLocked`. I'm on the fence on whether to add this here too as it'll probably proliferate to many other methods as well.
___
*[pkg/storage/replica_raftstorage.go, line 796 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8ZdKw0RGqu1HWRBXn:-LK8ZdKw0RGqu1HWRBXo:b-xwft7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L796)):*
> ```Go
> 	// of the removed range. In this case, however, it's copacetic, as subsumed
> 	// ranges _can't_ have new replicas.
> 	const subsumedNextReplicaID = math.MaxInt32
> ```

Can you check that we never do any math with these numbers that would overflow (and perhaps add a comment on the field in the tombstone proto)?
___
*[pkg/storage/replica_raftstorage.go, line 909 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8_5jaAtp-4DFBTD9N:-LK8_5jaAtp-4DFBTD9O:b-w6ppdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L909)):*
> ```Go
> 		// leaves the store in a consistent state, and access to the replicas
> 		// themselves is protected by their raftMus, which are held from start to
> 		// finish.
> ```

There's some code that pokes around the replica without the raftMu, but I agree that when you're reading from the engine poking at the replica data you're not going to be able to tell what you expect unless you also hold raftMu.
___
*[pkg/storage/store.go, line 3450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8_TCR1XQuJ4yhZk4_:-LK8_TCR1XQuJ4yhZk4a:b-wx4dqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/store.go#L3450)):*
> ```Go
> 				// applied successfully or not.
> 				if addedPlaceholder {
> 					s.mu.Lock()
> ```

What's this change about?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 1690 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8XEEM77IzDCH6ZsHF:-LK8at10Dd8qPDnY3yJs:bhq8o26) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/client_merge_test.go#L1690)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Might be worth verifying that the Raft snapshots metric increases after this point.
</blockquote></details>

Done. I put the check below the `mtc.waitForValues` otherwise it races with the snapshot application.
___
*[pkg/storage/replica.go, line 5530 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8Y7L2EgFxWxhET5Nd:-LK8bHkPECvrDYh7OmgN:b-853qtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica.go#L5530)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

uninitialized

If the replica is uninitialized, we're good because...?
</blockquote></details>

we've already installed a placeholder! Added that to the comment.
___
*[pkg/storage/replica_raftstorage.go, line 715 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8ZLy9CChoaw_pwfdI:-LK8bNXS6svUfPawI948:bijjrl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L715)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Elsewhere we have method names like `handleEvalResultRaftMuLocked`. I'm on the fence on whether to add this here too as it'll probably proliferate to many other methods as well.
</blockquote></details>

Yeah, plus it's really `applySnapshotRaftMuLockedAllSubsumedReplsRaftMusLocked` :grin:
___
*[pkg/storage/replica_raftstorage.go, line 796 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8ZdKw0RGqu1HWRBXn:-LK8cFst3DZdE1-4NIYe:b-9w3a5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L796)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Can you check that we never do any math with these numbers that would overflow (and perhaps add a comment on the field in the tombstone proto)?
</blockquote></details>

No math; just direct comparisons. FYI we already do exactly this in the replica GC queue. This comment is copy/pasted from there.
___
*[pkg/storage/replica_raftstorage.go, line 909 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8_5jaAtp-4DFBTD9N:-LK8bfvw29dsw3sAvN8m:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1409e0eebbe1e0600bc5253518ddd5a5342eaa42/pkg/storage/replica_raftstorage.go#L909)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

There's some code that pokes around the replica without the raftMu, but I agree that when you're reading from the engine poking at the replica data you're not going to be able to tell what you expect unless you also hold raftMu.
</blockquote></details>

Ack.
___
*[pkg/storage/store.go, line 3450 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8_TCR1XQuJ4yhZk4_:-LK8bhd1EKIKyY0zg7Ht:b-ggu7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a64e26c2b696ad7c7037f085c9c74b98c2a62e3/pkg/storage/store.go#L3450)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

What's this change about?
</blockquote></details>

Me trying to work around a locking issue in the first iteration of this. It was removed in r6 or r7 when I reworked this PR more sanely.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-:-LK8elOH52ff1fXTQOYx:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1702 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8eWFd4cY_bYfHlDPN:-LK8eWFd4cY_bYfHlDPO:b-p2bnjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42e9b64bb0147d74eaf4a208fec9714191614be/pkg/storage/client_merge_test.go#L1702)):*
> ```Go
> 	}
> 
> 	if n := store2.Metrics().RangeSnapshotsNormalApplied.Count(); n != 1 {
> ```

I was thinking you'd grab the number before the Listen and make sure it's at least one higher at some point later, but if this isn't flaky it works for me.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28533)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1702 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28533#-LK8eWFd4cY_bYfHlDPN:-LK8hTAu5KBWIKyrpWEJ:bp3r2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e42e9b64bb0147d74eaf4a208fec9714191614be/pkg/storage/client_merge_test.go#L1702)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I was thinking you'd grab the number before the Listen and make sure it's at least one higher at some point later, but if this isn't flaky it works for me.
</blockquote></details>

lol, whoops, this was definitely flaky. The initial splits seem to result in a Raft snapshot about one out of every hundred tries. Adjusted this to check the before/after diff as you suggested. Seems stable now.

**Pull request merged**
