### PR TITLE
colexecagg: share agg func allocs between different functions if possible

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, for every aggregate function we would always create a fresh `aggregateFuncAlloc` struct. That allocator is used to batch-allocate buckets. However, we would never share the alloc between different output columns even if the same aggregate function type overload is used. This commit addresses that inefficiency by enumerating all possible aggregate overloads for optimized aggregate functions and storing them in a single stack-allocated slice for reuse. This slice first stores 11 anyNotNull aggregates, then 6 avg aggregates, then 1 boolAnd aggregate, etc. In other words, each aggregate overload has a fixed spot in the array. This scheme was chosen over two dimensional array to remove any unused slots (we could have a separate slice for each aggregate type, and that slice would be up to 11 - the maximum number of type overloads any aggregate can have right now).

The main observation that allows us to easily reuse these allocs is the fact that there is no concurrency when allocating buckets.

For hash aggregation we currently use 128 allocation size in these allocators whereas for ordered / window aggregation we use just 1. This commit additionally extends `aggregateFuncAlloc` interface to add a method to increment the alloc size by 1. Namely, we don't change anything in case of the hash aggregation (meaning the same pool of 128 size can now be shared among multiple functions), but for ordered and window aggregations we increment the alloc size every time we reuse the allocator - this will make it so that for ordered / window aggs we batch-allocate all necessary objects at once.

Still, by far the main benefit of this change will be observed in case of the hash aggregation with small number of groups (buckets).

Addresses: #117546.

Epic: None.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmarks of `colexec` package are [here](https://gist.github.com/yuzefovich/67ccbbe53b1b0e17c4ae98c5a93fcd65). `BenchmarkAggregator` is the most interesting one, and it shows clear reduction in allocations when multiple functions share the same alloc. The speedup in this run can be somewhat misleading because there appear to be some noise in the benchmark (sometimes there is a regression with `numSameAggs=1`, in other times improvement), but for `numSameAggs=4` it's always an improvement (as expected):
```
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/numInputRows=1-24                                                                      11.8µs ± 3%     11.0µs ± 2%   -6.27%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/numInputRows=32-24                                                                     16.4µs ± 3%     15.4µs ± 2%   -6.00%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=2/numInputRows=32-24                                                                     15.5µs ± 4%     14.7µs ± 3%   -5.36%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=32/numInputRows=32-24                                                                    13.2µs ± 1%     12.7µs ± 2%   -4.30%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/numInputRows=1024-24                                                                    157µs ± 2%      148µs ± 2%   -5.22%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=2/numInputRows=1024-24                                                                    129µs ± 2%      125µs ± 2%   -2.80%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=32/numInputRows=1024-24                                                                  56.5µs ± 2%     53.6µs ± 1%   -5.21%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=128/numInputRows=1024-24                                                                 48.1µs ± 2%     47.0µs ± 1%   -2.37%  (p=0.001 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1024/numInputRows=1024-24                                                                45.6µs ± 1%     44.4µs ± 1%   -2.71%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/numInputRows=32768-24                                                                  5.08ms ± 4%     4.85ms ± 3%   -4.58%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=2/numInputRows=32768-24                                                                  4.56ms ± 1%     4.32ms ± 2%   -5.23%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=32/numInputRows=32768-24                                                                 1.32ms ± 0%     1.30ms ± 1%   -1.51%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=128/numInputRows=32768-24                                                                 780µs ± 0%      766µs ± 1%   -1.80%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1024/numInputRows=32768-24                                                                628µs ± 2%      613µs ± 2%   -2.40%  (p=0.000 n=10+9)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1/numInputRows=1048576-24                                                                 251ms ± 2%      255ms ± 5%     ~     (p=0.133 n=7+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=2/numInputRows=1048576-24                                                                 253ms ± 3%      244ms ± 6%   -3.87%  (p=0.004 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=32/numInputRows=1048576-24                                                               75.8ms ± 2%     75.3ms ± 2%     ~     (p=0.280 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=128/numInputRows=1048576-24                                                              54.9ms ± 0%     54.9ms ± 2%     ~     (p=0.696 n=8+10)
Aggregator/ANY_NOT_NULL/hash/int/groupSize=1024/numInputRows=1048576-24                                                             26.5ms ± 0%     26.5ms ± 0%     ~     (p=0.720 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=1-24                                                        16.2µs ± 3%     13.0µs ± 3%  -19.73%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=32-24                                                       23.9µs ± 2%     19.9µs ± 1%  -16.77%  (p=0.000 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=2/numInputRows=32-24                                                       26.0µs ± 3%     18.3µs ± 2%  -29.67%  (p=0.000 n=8+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=32/numInputRows=32-24                                                      22.9µs ± 9%     14.6µs ± 1%  -36.17%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=1024-24                                                      296µs ± 3%      254µs ± 2%  -14.12%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=2/numInputRows=1024-24                                                      227µs ± 0%      197µs ± 2%  -13.13%  (p=0.000 n=7+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=32/numInputRows=1024-24                                                    73.0µs ± 4%     59.4µs ± 2%  -18.64%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=128/numInputRows=1024-24                                                   56.2µs ±10%     49.8µs ± 2%  -11.30%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1024/numInputRows=1024-24                                                  54.4µs ±18%     46.9µs ± 2%  -13.85%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=32768-24                                                    10.8ms ± 6%      9.3ms ± 2%  -13.91%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=2/numInputRows=32768-24                                                    9.25ms ± 5%     7.79ms ± 4%  -15.74%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=32/numInputRows=32768-24                                                   1.67ms ± 1%     1.62ms ± 1%   -3.08%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=128/numInputRows=32768-24                                                   863µs ± 1%      845µs ± 1%   -2.06%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1024/numInputRows=32768-24                                                  641µs ± 1%      629µs ± 1%   -1.83%  (p=0.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1/numInputRows=1048576-24                                                   464ms ± 2%      484ms ± 4%   +4.43%  (p=0.002 n=8+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=2/numInputRows=1048576-24                                                   473ms ± 2%      475ms ± 2%     ~     (p=0.447 n=9+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=32/numInputRows=1048576-24                                                  156ms ± 4%      152ms ± 4%   -2.24%  (p=0.035 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=128/numInputRows=1048576-24                                                 100ms ± 3%      100ms ± 3%     ~     (p=1.000 n=10+10)
Aggregator/ANY_NOT_NULL/hash/int/numSameAggs=4/groupSize=1024/numInputRows=1048576-24                                               32.2ms ± 1%     31.9ms ± 0%   -0.84%  (p=0.000 n=10+10)
```

**Review by DrewKimball — APPROVED** [review]
Had a suggestion, but this :lgtm: if you think the current implementation is best.

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-:-NntiSif9xxpBPYq_7jH:b-1jj3gk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/colexec/colexecagg/aggregate_funcs.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-Nnth6Jj5kvq0TaxcMyt:-Nnth6Jj5kvq0TaxcMyu:be28dh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d13735ca8ae26003ed26db036437abd0b6c5e14/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L339)):*
> ```Go
> 	//   takes arguments of a single type, then only 0th position is used), an
> 	//   "index".
> 	var allocs [numOptimizedAggFns][maxNumOverloads]aggregateFuncAlloc
> ```

This comes out to ~1KB per aggregator, could that be significant for the use cases where the optimization matters? 
Could we instead have an allocs slice that we append to, and de-dup by iterating through it and checking the implementation?

In the absolute worst case we'd only have to iterate through 121 entries, and it seems likely to be much less than that in practice.

**Comment by DrewKimball** [comment]
>This comes out to ~1KB per aggregator, could that be significant for the use cases where the optimization matters?
Could we instead have an allocs slice that we append to, and de-dup by iterating through it and checking the implementation?

Ah, I didn't consider that the array is stack allocated. I think in that case I'm happy with whatever you think is most ergonomic.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117649)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/colexec/colexecagg/aggregate_funcs.go` line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-Nnth6Jj5kvq0TaxcMyt:-NnvPjCQALf3u5X3xRjd:b1lcp5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d13735ca8ae26003ed26db036437abd0b6c5e14/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L339)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

This comes out to ~1KB per aggregator, could that be significant for the use cases where the optimization matters? 
Could we instead have an allocs slice that we append to, and de-dup by iterating through it and checking the implementation?

In the absolute worst case we'd only have to iterate through 121 entries, and it seems likely to be much less than that in practice.
</blockquote></details>

(Sorry, forgot to push this comment after the push of the WIP commit.)

You're right that 11 x 11 array is about 1KB in size, but it's a stack allocation (so hopefully should be pretty cheap and wouldn't trigger the goroutine stack growth ever). My intuition says that there could be really bad cases where the linear search over 53 items (that's the actual number of different overloads we can have - meaning that in two-dimensional array we had lots of unused cells) can be non-trivial. So I just pushed an update to flatten the array into a single dimension to use 53 elements precisely, let me what you think (and I'll kick of a set of benchmark runs).

----

Benchmarks don't show any change in the allocations, but there are some minor changes in speed, a bit more negative on average (could be noise though). The complexity of this optimization seems manageable, so I think we should keep it.

**Review by DrewKimball — APPROVED** [review]
:lgtm: This is a nice improvement!

> Reviewed 24 of 25 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-:-NnwB2zM8_c2-DTNNtDr:b-k2cb3o)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Very nice! I think this will have a huge benefit to some workloads.

**Review by mgartner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 1 of 5 files at r3, 23 of 25 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117649)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/colexec/colexecagg/aggregate_funcs.go` line 512 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-NnziRl1Dvp-JlTQITQ9:-NnziRl1Dvp-JlTQITQA:b-os6arh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d39f563d60ded23b606515e079208a986bc565af/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L512)):*
> ```Go
> 				// case since we have allocSize = 1, so for all usages of this
> 				// allocator (except for the first one) we want to bump
> 				// funcAllocs[i].allocSize by 1.
> ```

I'm having trouble understanding the reasoning for bumping `allocSize` by 1. It starts at 128, correct?

**Review by yuzefovich — COMMENTED** [review]
I updated the gist to refer to the latest benchmark numbers.

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-:-Nnznr9sEGOBITEIE45Z:bh96gkp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/colexec/colexecagg/aggregate_funcs.go` line 512 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-NnziRl1Dvp-JlTQITQ9:-NnznsdB6YvqWq8mWDfN:b-qleuce) ([raw file](https://github.com/cockroachdb/cockroach/blob/d39f563d60ded23b606515e079208a986bc565af/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L512)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm having trouble understanding the reasoning for bumping `allocSize` by 1. It starts at 128, correct?
</blockquote></details>

We use 128 size for hash aggregation, but only 1 for ordered (streaming) and window aggregation (because then we only have at most one bucket active at any point in time, so we can reuse it). This commit makes it so that the same agg func alloc can be shared for all aggregation kinds, so now if we happen to have two ordered `sum`s for example, without bumping the alloc size, that alloc struct would do two allocations.

Also, alloc size is fixed throughout the whole execution, and it will remain 128 for hash aggregation (unless we make it configurable), but will be equal to the number of times a single alloc struct is used by different columns in ordered / window aggregation.

**Comment by mgartner** [comment]
*[`pkg/sql/colexec/colexecagg/aggregate_funcs.go` line 512 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117649#-NnziRl1Dvp-JlTQITQ9:-NnzpvQQ269LWFMzaS-i:bhhddl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d39f563d60ded23b606515e079208a986bc565af/pkg/sql/colexec/colexecagg/aggregate_funcs.go#L512)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We use 128 size for hash aggregation, but only 1 for ordered (streaming) and window aggregation (because then we only have at most one bucket active at any point in time, so we can reuse it). This commit makes it so that the same agg func alloc can be shared for all aggregation kinds, so now if we happen to have two ordered `sum`s for example, without bumping the alloc size, that alloc struct would do two allocations.

Also, alloc size is fixed throughout the whole execution, and it will remain 128 for hash aggregation (unless we make it configurable), but will be equal to the number of times a single alloc struct is used by different columns.
</blockquote></details>

I see. So for ordered aggregators we can allocate the exact size of agg funcs we need ahead of time because we only need to handle one group at a time, and we know how many different agg funcs we need to compute. For non-ordered aggregators we don't know how many groups we'll have so we allocate at least 128 in preparation for a bunch of groups. Makes sense to me. Thanks!

**Pull request merged**
