### PR TITLE
changefeedccl: refactor schema registry code to fail early 

### PR DESCRIPTION
**Pull request by stevendanna**
This is built on top of #65713

--

I noted that even for some bogus confluent_schema_registry URLs, we
didn't provide the user with an error until the job had already
started. This is because we don't connect to the registry until we
actually have rows to send and because url.Parse can parse a large
number of URLs, very few of which work for making HTTP requests.

This change moves some of the schema registry code out of the encoder
and implements a Ping() message that we can call at creation time to
check if we have basic connectivity to the registry before creating
the Job.

I stopped short of fully excising the schema registry setup from the
encoder setup, so as a side effect, getEncoder now takes a context. I
think we can do better, but wanted to get this improvement in first.

Release Note (enterprise change): CHANGEFEEDs will now report more
schema registry connection problems immediately at job creation time.

### CODE REVIEW

**Comment by stevendanna** [comment]
@spiffyyeng Apologies for moving these files around so soon after you worked at them.  I went to go fix a small thing about the error handling, and got carried away.

**Review by HonoreDB — APPROVED** [review]
Nice, this was definitely a pain point in local testing, and I like using `GET /mode` as the ping . I'm a little wary of introducing a context to getEncoder, since it needs to run identically in, well, different contexts. Unless we do that region-specific encryption thing, I guess. I haven't seen any idiomatic way to restrict what gets accessed on a context object though, and we have dependent method signatures that rely on it. Maybe at some point I'll find or create a library that takes a Context and a list of fields and returns a Context that wraps the original but errors if you try to access anything not in that list.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65775#-:-MaiCRSr13V3ONpWgz9-:b-m9ltw9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @spiffyyeng)

**Comment by spiffyyeng** [comment]
might want to rebase here so it's easier to tell what's part of this PR vs the last one (plus merge conflicts 😬)

**Review by spiffyy99 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/schema_registry.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65775#-MaiYKyt-4xPsT2UobQ9:-MaiYKyt-4xPsT2UobQA:bmmtk2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac48123417cb0b35c986ea7c89b6ca6a9515c9cc/pkg/ccl/changefeedccl/schema_registry.go#L31)):*
> ```Go
> const confluentSchemaContentType = `application/vnd.schemaregistry.v1+json`
> 
> type schemaRegistry interface {
> ```

interesting, do we plan on supporting non-confluent schema registries down the road? 🤔 (not aware of these myself)
___
*[pkg/ccl/changefeedccl/schema_registry.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65775#-Mai_5ZV3983FeC75Ac6:-Mai_5ZV3983FeC75Ac7:byn04sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac48123417cb0b35c986ea7c89b6ca6a9515c9cc/pkg/ccl/changefeedccl/schema_registry.go#L88)):*
> ```Go
> 
> 	retryOpts := base.DefaultRetryOptions()
> 	retryOpts.MaxRetries = 2
> ```

maybe we want to set retry functionality as configurable in the future?

**Comment by stevendanna** [comment]
> I'm a little wary of introducing a context to getEncoder, since it needs to run identically in, well, different contexts. 

Yeah, what I'm thinking is that the schema-registry is something that should get passed to the encoder.  We'll need to untangle some of the options handling a bit though.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @spiffyyeng)

___
*[pkg/ccl/changefeedccl/schema_registry.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65775#-MaiYKyt-4xPsT2UobQ9:-Mai_YBs2NSrC61jcR0S:b-f5ekdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac48123417cb0b35c986ea7c89b6ca6a9515c9cc/pkg/ccl/changefeedccl/schema_registry.go#L31)):*
<details><summary><i>Previously, spiffyyeng (Ryan Min) wrote…</i></summary><blockquote>

interesting, do we plan on supporting non-confluent schema registries down the road? 🤔 (not aware of these myself)
</blockquote></details>

No comitted plans, but Google's Pub/Sub service has its own schema registry. Really, I just put this in because I sometimes find it a nice way to stub out the design of a thing while programming and then I decided to leave it in.  My guess is this interface will need to change a bit if we decided to add more.
___
*[pkg/ccl/changefeedccl/schema_registry.go, line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65775#-Mai_5ZV3983FeC75Ac6:-MaiaMedD8-iLw1KgJM_:b-4ufwjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac48123417cb0b35c986ea7c89b6ca6a9515c9cc/pkg/ccl/changefeedccl/schema_registry.go#L88)):*
<details><summary><i>Previously, spiffyyeng (Ryan Min) wrote…</i></summary><blockquote>

maybe we want to set retry functionality as configurable in the future? 
</blockquote></details>

Indeed! :D. I've just started work on making our retries in general more configurable -- at least at the code level and then potentially to users in some places.

**Comment by stevendanna** [comment]
bors r=[HonoreDB,spiffyyeng]

**Pull request merged**
