### PR TITLE
acceptance: log where the certs are

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. While you're at it, wanna create a root cert automatically?

**Comment by tamird** [comment]
I thought about it, but are we really gonna sql against acceptance? I feel like that can wait until the first acceptance test that wants to execute sql.

**Comment by tschottdorf** [comment]
could be pretty soon. I for one am not planning to run any clusters manually, instead I just want to let the acceptance tests do the work for me. But adding when needed works for me.

**Comment by tamird** [comment]
:+1:

**Pull request merged**
