### PR TITLE
sql: Add range size to SHOW RANGES command.

### LINKED ISSUE #39767: sql: add range size to show ranges
We now have a more mature `SHOW RANGES` that provides good information:
```SQL
root@127.0.0.1:63253/movr> show ranges from table rides;
        start_key       |        end_key        | range_id | replicas | lease_holder |    locality
+-----------------------+-----------------------+----------+----------+--------------+-----------------+
  NULL                  | /"chicago"            |       23 | {1,2,3}  |            1 | region=us-east1
  /"chicago"            | /"chicago"/PrefixEnd  |       28 | {1,2,3}  |            1 | region=us-east1
  /"chicago"/PrefixEnd  | /"new york"           |       31 | {1,2,3}  |            1 | region=us-east1
  /"new york"           | /"new york"/PrefixEnd |       27 | {1,2,3}  |            1 | region=us-east1
  /"new york"/PrefixEnd | /"seattle"            |       29 | {1,2,3}  |            1 | region=us-east1
  /"seattle"            | /"seattle"/PrefixEnd  |       30 | {1,2,3}  |            1 | region=us-east1
  /"seattle"/PrefixEnd  | NULL                  |       32 | {1,2,3}  |            1 | region=us-east1
(7 rows)

Time: 31.467ms
```

However, this command could also be expanded to show range size. This recently came up with a customer seeking a way to get this information outside of the webui. cc @roncrdb

### PR DESCRIPTION
**Pull request by rohany**
Fixes #39767.

This is done by adding a new builtin function `crdb_internal.range_stats` that returns a json object containing stats about the requested range.

Release note (sql change): Add range size information to SHOW RANGES. Adds a builtin function crdb_internal.range_stats which returns a json object containing stats about the requested range.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Thanks for getting this out so fast @rohany. There are a few things here that we'll likely want to change before merging this.

The first is that we almost certainly don't want to include this information in `crdb_internal.ranges_no_leases`. The reason for the split between `crdb_internal.ranges_no_leases` and `crdb_internal.ranges` is because `crdb_internal.ranges` is so much more expensive due to its per-range lookups. We created `crdb_internal.ranges_no_leases` as a means of quickly accessing the state about ranges that can be gathered exclusively from a meta keyspace scan so that we could continue to expose something relatively fast. This PR is regressing on this front. To avoid this, we'll only want to add this new column to `crdb_internal.ranges`.

Similarly, it doesn't seem particularly desirable to have the logic for retrieving these stats locked up inside of the virtual schema generator function. I would have expected us to introduce a builtin that mirrors `crdb_internal.lease_holder` and use that from `crdb_internal.ranges`. In fact, introducing a `crdb_internal.range_stats` builtin function that returns a JSON blob of a range's stats seems like a generally useful change in and of itself. We would then use this function from the `crdb_internal.ranges` view just like we use `crdb_internal.lease_holder`. Did you consider implementing this PR like that?

@jordanlewis should take a look at this as well, since he reviewed https://github.com/cockroachdb/cockroach/pull/30601.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-:-LnNqG5nA5YMcU1ulNjJ:b-e2qr7e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/crdb_internal.go, line 1874 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnNpwGr31OViS-4BiTQ:-LnNpwGr31OViS-4BiTR:bdks7p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/00741099486c5aab2959561b515885e071b1646f/pkg/sql/crdb_internal.go#L1874)):*
> ```Go
> 	split_enforced_until,
> 	crdb_internal.lease_holder(start_key) AS lease_holder,
>   range_size
> ```

Mind fixing this spacing?
___
*[pkg/sql/crdb_internal.go, line 1910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnNptvZDIg78NscVgef:-LnNptvZDIg78NscVgeg:bdks7p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/00741099486c5aab2959561b515885e071b1646f/pkg/sql/crdb_internal.go#L1910)):*
> ```Go
>   table_name           STRING NOT NULL,
>   index_name           STRING NOT NULL,
> 	replicas             INT[] NOT NULL,
> ```

Mind fixing this spacing?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @rohany)

___
*[pkg/sql/sem/builtins/builtins.go, line 3084 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnP_GtuC7Fk-atn_YRc:-LnP_GtuC7Fk-atn_YRd:b-trgcvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4f6831c938dd5b49bdc27a05f572febd59ff2fd/pkg/sql/sem/builtins/builtins.go#L3084)):*
> ```Go
> 				{"key", types.Bytes},
> 			},
> 			ReturnType: tree.FixedReturnType(types.Int),
> ```

This would be even more useful if we made it `crdb_internal.range_stats` and it returned a JSON type that included every field in the MVCCStats. You could then pull our the size from the JSON datum. Are there any blockers to doing that?

By the way, I think you want `Total()` (`KeyBytes + ValBytes`).

**Comment by rohany** [comment]
Yeah, that makes sense -- sorry for not doing it the first time.

**Comment by rohany** [comment]
RFAL

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @rohany)

___
*[pkg/sql/sem/builtins/builtins.go, line 3098 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnTKaNH-FowLk1kWtA4:-LnTKaNH-FowLk1kWtA5:bgkvbkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0597b118f5202883e3e236ffec02b54101c8aa5/pkg/sql/sem/builtins/builtins.go#L3098)):*
> ```Go
> 				}
> 				resp := b.RawResponse().Responses[0].GetInner().(*roachpb.RangeStatsResponse).MVCCStats
> 				jsonStr, err := gojson.Marshal(&resp)
> ```

@justinj do you mind confirming that this is the best way to do this conversion?
___
*[pkg/sql/sem/builtins/builtins.go, line 3108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnTKerm7vNmI48oe6NN:-LnTKerm7vNmI48oe6NO:b4szc52) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0597b118f5202883e3e236ffec02b54101c8aa5/pkg/sql/sem/builtins/builtins.go#L3108)):*
> ```Go
> 				return jsonDatum, nil
> 			},
> 			Info: "This function is used to retrieve the size of a range in bytes.",
> ```

This info looks stale.

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40281)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @nvanbenschoten, and @rohany)

___
*[pkg/sql/sem/builtins/builtins.go, line 3098 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnTKaNH-FowLk1kWtA4:-LnrvmBR5901k28Evvzo:bxwcz2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0597b118f5202883e3e236ffec02b54101c8aa5/pkg/sql/sem/builtins/builtins.go#L3098)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@justinj do you mind confirming that this is the best way to do this conversion?
</blockquote></details>

Seems fine to me, if a little fragile? I guess it depends if you want this to be automatically updated if `MVCCStats` changes. the method lgtm

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-:-LnsGqGL0l8US93K72rA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @rohany)

___
*[pkg/sql/sem/builtins/builtins.go, line 3108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40281#-LnTKerm7vNmI48oe6NN:-LnsGOIr5OyPnOmJXLCC:bmaf50z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0597b118f5202883e3e236ffec02b54101c8aa5/pkg/sql/sem/builtins/builtins.go#L3108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This info looks stale.
</blockquote></details>

Statistics, not status.

**Comment by rohany** [comment]
Sorry about that.

TFTR!

bors r+

**Pull request merged**
