### PR TITLE
sql: partially implement CONFIGURE ZONE logic during CREATE TABLE

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): CREATE TABLE ... LOCALITY ... statements now
modify the zone configs to be in line with the desired locality.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2t-lM4EJGiqadFT1S:-MO2nYGe4Vz--QQVc_6A:bah5p92) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L147)):*
> ```Go
> 		return []zonepb.ConstraintsConjunction{
> 			{
> 				NumReplicas: 1,
> ```

Nit: There's talk of doing something fancier here if we go to 5 replicas in the REGION FAILURE case.  Your call, but we might want to add a TODO here to leave a trail of breadcrumbs.  
___
*[pkg/sql/region_util.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2oEAfDdFiI4pL19JQ:-MO2oEAfDdFiI4pL19JR:b-wxzyjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L165)):*
> ```Go
> ) (*zonepb.ZoneConfig, error) {
> 	ret := zonepb.ZoneConfig{
> 		NumReplicas: proto.Int32(zoneConfigNumReplicasFromRegionConfig(regionConfig)),
> ```

Nit: just a heads-up that we're probably going to be changing the default number of replicas to 5 for SURVIVE REGION tables.  In that case, the above call will have to pass in a survival goal to get the correct number.
___
*[pkg/sql/region_util.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2pXhZ6ugGJNxc9U1r:-MO2pXhZ6ugGJNxc9U1s:b-1ebmkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L173)):*
> ```Go
> 		// Technically, we do not need to run any zone config changes here at all
> 		// (the outer loop can return early). However, it is much easier to think about state
> 		// if we force an entry into system.zones even for global configurations.
> ```

Does this imply that if we ever need to move the database back to a non-multi-region database, we'd have to loop through all of these tables and remove their zone configs?  Or, if the user wanted to make a wide-spread change to the number of replicas, that we'd need to update all tables as well?  If so, I'm thinking we might not want to set a zone config here.
___
*[pkg/sql/region_util.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2qgr_Bh0zFI4jYbwR:-MO2qgra7JyhUOICNTRq:b893klj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L177)):*
> ```Go
> 		ret.InheritedLeasePreferences = true
> 	case *descpb.TableDescriptor_LocalityConfig_RegionalByTable_:
> 		preferredRegion := regionConfig.PrimaryRegion
> ```

I think that in this case, we should rely on the database-level zone config unless the Region is explicitly set.  This allows us to change the primary region for all tables with a single update to the database-level zone configs.
___
*[pkg/sql/region_util.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2uVv20pEaiZUPEVKw:-MO2uVv3-Cz8tAcj3M-f:bj3w6g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L192)):*
> ```Go
> 		// We need to fill the table with PARTITION BY to get the ball rolling on this.
> 		// For now, return a dummy field for now so that other tests relying on this path of code to
> 		// exercise other functionality (i.e. SHOW) passes.
> ```

Nit: grammar - passes -> pass.
___
*[pkg/sql/region_util_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO31P9t0Wd4sPYdpLW8:-MO31P9t0Wd4sPYdpLW9:bk4f4bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util_test.go#L158)):*
> ```Go
> }
> 
> func TestZoneConfigFromTableLocalityConfig(t *testing.T) {
> ```

Before I review these, we might want to get consensus on the above (setting or not setting zone configs on GLOBAL and REGIONAL BY TABLE IN PRIMARY REGION tables.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2t-lM4EJGiqadFT1S:-MO3kHKtE_jiDNp_atDZ:buyk39a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L147)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: There's talk of doing something fancier here if we go to 5 replicas in the REGION FAILURE case.  Your call, but we might want to add a TODO here to leave a trail of breadcrumbs.  
</blockquote></details>

I think region is still 1 in the conjunction clause, but there's a TODO prefixing this function to correct this anyway.
___
*[pkg/sql/region_util.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2oEAfDdFiI4pL19JQ:-MO3kM0C2ktk5t_BXOqS:b-u6bdr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L165)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: just a heads-up that we're probably going to be changing the default number of replicas to 5 for SURVIVE REGION tables.  In that case, the above call will have to pass in a survival goal to get the correct number.
</blockquote></details>

regionConfig contains survival goal, so that's fine. TODO in main comment covers this
___
*[pkg/sql/region_util.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2pXhZ6ugGJNxc9U1r:-MO3kZY22NdlTOcBP7Lg:b-796cfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L173)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Does this imply that if we ever need to move the database back to a non-multi-region database, we'd have to loop through all of these tables and remove their zone configs?  Or, if the user wanted to make a wide-spread change to the number of replicas, that we'd need to update all tables as well?  If so, I'm thinking we might not want to set a zone config here.
</blockquote></details>

I think we inherit the GLOBAL zone config at the moment from the database, not regional by table in primary region. I'd prefer being explicit here in case, e.g. range_min_bytes was set by the user to be something else.
___
*[pkg/sql/region_util.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2qgr_Bh0zFI4jYbwR:-MO3koAuEhzidn_-uHxe:b-iikf9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L177)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I think that in this case, we should rely on the database-level zone config unless the Region is explicitly set.  This allows us to change the primary region for all tables with a single update to the database-level zone configs.
</blockquote></details>

the database level config at the moment is configured to be the GLOBAL-style configuration.
if we decide to change that, I'd think that change should come later. this is pretty placeholder-y TBH -- i'd rather aayush comes in later and cleans this up, since not everything is implement and it seems unclear what we want for the configs for GLOBAL/REGIONAL BY TABLE setups in the current configuration.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2t-lM4EJGiqadFT1S:-MO42YeV9MQdH285tZgT:bjqeryp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L147)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think region is still 1 in the conjunction clause, but there's a TODO prefixing this function to correct this anyway.
</blockquote></details>

I think it's going to be 2 in the primary region, so that we only have to go to one neighbouring region for quorum.  Anyway, I agree that the TODO above should cover it, but to be 100% safe, we should generalize it to say that the constraints may need to change too.
___
*[pkg/sql/region_util.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2pXhZ6ugGJNxc9U1r:-MO43g5b56y9dwAakvUY:b-czxwde) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L173)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I think we inherit the GLOBAL zone config at the moment from the database, not regional by table in primary region. I'd prefer being explicit here in case, e.g. range_min_bytes was set by the user to be something else.
</blockquote></details>

The database zone config should be for REGIONAL BY TABLE tables, and global tables should require the additional `non_blocking_range` flag in theirs.  We can continue to discuss over Slack, but I'm still of the opinion that we shouldn't lay down zone configs for REGIONAL BY TABLE tables if we don't have to.  In contrast with the issue below, I think we should resolve this one on this PR, as it's not as obvious that this one will get cleaned up properly.
___
*[pkg/sql/region_util.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2qgr_Bh0zFI4jYbwR:-MO44CMm8DSZimWcGU6q:b-mwqezn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L177)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the database level config at the moment is configured to be the GLOBAL-style configuration.
if we decide to change that, I'd think that change should come later. this is pretty placeholder-y TBH -- i'd rather aayush comes in later and cleans this up, since not everything is implement and it seems unclear what we want for the configs for GLOBAL/REGIONAL BY TABLE setups in the current configuration.
</blockquote></details>

I'm fine with that.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/region_util.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2t-lM4EJGiqadFT1S:-MO488716zs_fw5JFPsm:b-6eel58) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L147)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I think it's going to be 2 in the primary region, so that we only have to go to one neighbouring region for quorum.  Anyway, I agree that the TODO above should cover it, but to be 100% safe, we should generalize it to say that the constraints may need to change too.
</blockquote></details>

the playbook says 1 ;) but it also does it for leaseholder_constraints.
done TODO!
___
*[pkg/sql/region_util.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2pXhZ6ugGJNxc9U1r:-MO48FZt0ZIvnR_vm-5F:b-gixtfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L173)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

The database zone config should be for REGIONAL BY TABLE tables, and global tables should require the additional `non_blocking_range` flag in theirs.  We can continue to discuss over Slack, but I'm still of the opinion that we shouldn't lay down zone configs for REGIONAL BY TABLE tables if we don't have to.  In contrast with the issue below, I think we should resolve this one on this PR, as it's not as obvious that this one will get cleaned up properly.
</blockquote></details>

Alright, easy to change if we decide to go the other way!
___
*[pkg/sql/region_util_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO31P9t0Wd4sPYdpLW8:-MO49etX99GEW4aUtfcp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util_test.go#L158)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Before I review these, we might want to get consensus on the above (setting or not setting zone configs on GLOBAL and REGIONAL BY TABLE IN PRIMARY REGION tables.
</blockquote></details>

Done.

**Review by ajstorm — APPROVED** [review]
:lgtm: Only nits left.

Great first crack at this!  Should lay a good foundation for the future stuff.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-:-MO4NOVI84SPhi0CdSeL:b-nz4i3g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2t-lM4EJGiqadFT1S:-MO4Kxrs2fYRp0yvHuli:bdjk2ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L147)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

the playbook says 1 ;) but it also does it for leaseholder_constraints.
done TODO!
</blockquote></details>

looks good, thanks!  I think this stuff is still evolving, which is why the playbook might already be out of date (at least based on the prevailing thoughts as of this morning).
___
*[pkg/sql/region_util.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO2pXhZ6ugGJNxc9U1r:-MO4LEUa48OIc6aOyvYt:b-4tdyap) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util.go#L173)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Alright, easy to change if we decide to go the other way!
</blockquote></details>

Agreed, let's get this bad-boy in.
___
*[pkg/sql/region_util_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO31P9t0Wd4sPYdpLW8:-MO4LzrSE-4g-HtB47eR:b-wkatak) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d53c03a8ca4ade3f8e362fd5a649d0537af229b/pkg/sql/region_util_test.go#L158)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Look good for now.  Once we circle back on these, I'll have another look.
___
*[pkg/sql/region_util_test.go, line 236 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO4MXTUB4L1aqJxMzFN:-MO4MXTUB4L1aqJxMzFO:b-jhpoej) ([raw file](https://github.com/cockroachdb/cockroach/blob/04c0ca0bf3944df9e2326f5f7fdfc82db557a8c7/pkg/sql/region_util_test.go#L236)):*
> ```Go
> 		},
> 		{
> 			desc: "4-region global table with zone survival on primary region",
> ```

Nit: Is this description correct?  Shouldn't it be "4-region regional by table..."?
___
*[pkg/sql/region_util_test.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO4MiYG0XqP9W75AwH7:-MO4MiYG0XqP9W75AwH8:b20gi4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/04c0ca0bf3944df9e2326f5f7fdfc82db557a8c7/pkg/sql/region_util_test.go#L252)):*
> ```Go
> 		},
> 		{
> 			desc: "4-region global table with regional survival on primary region",
> ```

Nit: Same comment as above.
___
*[pkg/sql/region_util_test.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO4MtmpCyIFrWahITA2:-MO4MtmpCyIFrWahITA3:blf3x7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/04c0ca0bf3944df9e2326f5f7fdfc82db557a8c7/pkg/sql/region_util_test.go#L268)):*
> ```Go
> 		},
> 		{
> 			desc: "4-region global table with zone survival on non primary region",
> ```

Nit: And here...

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57654)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/region_util_test.go, line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57654#-MO4MtmpCyIFrWahITA2:-MO5X2UC6nIYOy06TaMX:bp7rc3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/04c0ca0bf3944df9e2326f5f7fdfc82db557a8c7/pkg/sql/region_util_test.go#L268)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: And here...
</blockquote></details>

you got my copy pasta!

**Comment by otan** [comment]
thanks!

bors r=ajstorm

**Pull request merged**
