### PR TITLE
roachtest: add sql20 benchmark

### PR DESCRIPTION
**Pull request by asubiotto**
Informs #34408

Release note: None

cc @awoods187

### CODE REVIEW

**Comment by vivekmenezes** [comment]
thanks!

**Review by jordanlewis — APPROVED** [review]
Can you fix the lint errors? This :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34500#-:-LXt7-z4ACRQDrYX7lJ4:b-ot3xu3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by asubiotto** [comment]
TFTR, lint errors should be fixed

bors r+

**Pull request merged**
