### PR TITLE
sql: add pg_catalog.pg_collation

### LINKED ISSUE #12976: sql: Implement pg_catalog.pg_collation as virtual table
As seen in #12783, ActiveRecord expects the `pg_collation` table to be available.

### PR DESCRIPTION
**Pull request by jordanlewis**
`pg_catalog.pg_collation` is now populated based on the values of the locales returned by the [`tag.Provided()`](https://godoc.org/golang.org/x/text/collate#Supported) method in Go's collation library. It's missing the columns that link collations to their corresponding names in `LC_COLLATE` and `LC_CTYPE` format because I couldn't figure out how to easily generate those names. I don't think these columns are critical for us.

The `pg_attribute.attcollation` column is now present, which links database columns to their associated collation if any. The `pg_type.typcollation` field is now updated to link types to their default collations.

cc @eisenstatdavid

Resolves #12976.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12983)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Nice!

---

Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb24iUD6X8c58U9mQgZ:-Kb24iUD6X8c58U9mQg_:b3vnpmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L332)):*
> ```Go
> }
> 
> var (
> ```

move these variables, which are defined for `pgCatalogConstraintTable`, below `pgCatalogCollationTable`.

---

*[pkg/sql/pg_catalog.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb24cUQDHQyzFOZgPef:-Kb24cURMosMdE_14OE5:b-rbtzs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L365)):*
> ```Go
> )
> 
> var pgCatalogCollationTable = virtualSchemaTable{
> ```

This is missing a link to the pg docs on this table.

---

*[pkg/sql/pg_catalog.go, line 1420 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb26JjFq6CzkuR44Pva:-Kb26JjFq6CzkuR44Pvb:b-lsdtqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda0a02fc1af5dd664b232d3b0ddc807e0ea95e6/pkg/sql/pg_catalog.go#L1420)):*
> ```Go
> 	if typ.FamilyEqual(parser.TypeAny) {
> 		return zeroVal
> 	} else if typ.Equivalent(parser.TypeString) || typ.Equivalent(parser.TypeStringArray) {
> ```

We can use `FamilyEquals` for these two and avoid worrying about `TypeAny` above, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-:-Kb26g_K1s_Ead7NlIFJ:b-83sjoh)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb5PR9-78tQhf83ccA4:-Kb5PR9-78tQhf83ccA5:bn9wn8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L388)):*
> ```Go
> 				datEncodingUTFId,            // collencoding
> 				// It's not clear how to translate a Go collation tag into the format
> 				// required by LC_COLLATE and LC_CTYPE.
> ```

I think you'd be fine with `strings.Replace(collName,'-','_')+'.UTF-8'`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 332 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb24iUD6X8c58U9mQgZ:-KbB4g4yinhDmT6SofY1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L332)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

move these variables, which are defined for `pgCatalogConstraintTable`, below `pgCatalogCollationTable`.
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb24cUQDHQyzFOZgPef:-KbB4hQJOFVOH0NSKkvw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is missing a link to the pg docs on this table.
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 388 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb5PR9-78tQhf83ccA4:-KbB4pnXKlLbx77tkkOj:b31b4el) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ab0f463c488d977811bebb048759efef6b52250/pkg/sql/pg_catalog.go#L388)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you'd be fine with `strings.Replace(collName,'-','_')+'.UTF-8'`. 
</blockquote></details>

Possibly. I think I'm going to err on the side of not including these for now unless we decided they're required. Collations, and the differences between Go's support and Unix locales, are subtle enough that I'm nervous we'll make a mistake with this simple mapping. I'd rather not introduce a broken mapping just to fill out these columns.

---

*[pkg/sql/pg_catalog.go, line 1420 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-Kb26JjFq6CzkuR44Pva:-KbB6WbWJwgX8ec5av1A:b-t2b6xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda0a02fc1af5dd664b232d3b0ddc807e0ea95e6/pkg/sql/pg_catalog.go#L1420)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can use `FamilyEquals` for these two and avoid worrying about `TypeAny` above, right?
</blockquote></details>

No, because `FamilyEqual` on `tArray` returns true for all array types. We only want to select arrays of type String here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12983#-:-KbBqXsocp-gVeXpz3Qe:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTRs!

**Pull request merged**
