### PR TITLE
kv: document DeleteRange (SI) and Delete (SSI) anomalies

### PR DESCRIPTION
**Pull request by tbg**
# DeleteRange

The newly added test (which was pruned to make its runtime palatable) currently
returns ~22 failing histories at SNAPSHOT isolation owing to two anomalies.
This was found looking into #6124, but is not technically related to it (but see the next section).
The first (and more severe) anomaly:

```
iso=[SNAPSHOT SNAPSHOT SNAPSHOT], pri=[3 2 1]
I1.1(A)[1] C1.1 DR3.1(A-C) R2.1(A)[1] C3.1 W2.1(B-A)[1] C2.1
```

In other words
- the value A=1 is written and committed
- transaction 3 deletes A-C (which means leaving an intent on A and
  populating the write timestamp cache interval A-C.
- transaction 2 pushes the intent on A and reads A=1.
  The write timestamp cache entry on A isn't updated properly in the process
  (which is an unrelated issue that likely incurs anomalies).
- transaction 2 writes B=1, commits.
  This is the anomaly: logically, there is DeleteRange intent sitting there
  with a higher timestamp, so this should be a write-write conflict. But there
  isn't an actual intent there (since the key was previously vacant, just like
  the countably infinite rest of vacant keys around it).
- transaction 3 commits (at its higher timestamp), so now A=<nil>,
  but note that we still have B=1 (written by transaction 2).

Note that this example should fail in the same way with only transaction 3 at
SNAPSHOT isolation.

The one obvious fix that comes to mind is to "somehow" push the whole range
entry in the timestamp cache forward along with the push of one of its intents.
However, that seems brittle and may not reliably be possible since the
timestamp cache's current implementation freely splits up its intervals as new
entries are added.

Then there's also this failing history (the key point is essentially that the
read of A and the range deletion are interchanged):

```
iso=[SNAPSHOT SNAPSHOT SNAPSHOT], pri=[2 3 1]
I1.1(A)[1] C1.1 R2.1(A)[1] DR3.1(A-C) W2.1(B-A)[1] C3.1 C2.1
```

In other words:
- write and commit A=1 as before
- txn2 reads A=1
- txn3 deletes A-C (so `ts(txn3) > ts(txn2)`)
- txn2 writes B=1 (pushing its timestamp due to tsCache entry on A-C); now
  again `ts(txn3) < ts(txn2)`
- both commit and the visible values are A=<nil>, B=1; we've again lost txn3's
  deletion of B.

This seems a little less anomalous than the above since essentially what
happens is that txn2 has write skew: It reads a stale value of A and writes
it somewhere, except that this "somewhere" would be a write-write conflict in
most monolithic databases.
# Delete

As pointed out in #6124, `Delete` currently neither populates the timestamp
cache nor leaves a tombstone when there is no previous value.

Consider the history `I1(A) C1 R2(A) D3(A) D3(B) W2(B-A) C2 C3`
- A=1 is written and committed
- txn2 reads `A=1`
- txn3 deletes A and B (the latter of which is vacant, i.e. has no old version)
  There is no conflict since `ts(txn3) > ts(txn2)`.
- txn2 writes `B=1` and both txns commit.
  This is illegal since `txn2` wrote into the past of `txn3`s deletion of B.

A tombstone on B would have fixed this (txn2 would have caught write-too-old),
or an entry in the write timestamp cache.

Writing the tombstone is likely the more economical option.

See #6124 for discovery and discussion of this anomaly.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6227)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
In the second failing history is ts2 still reading A=1?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-:-KFyAIz6y_X72qUwybX0:-9517558)*

**Comment by vivekmenezes** [comment]
I've to step out for an hour and a half. I'll review it when I get back.

**Comment by bdarnell** [comment]
LGTM. 

For the DeleteRange anomaly, what if we marked intents laid down by commands that also update the timestamp cache (just DeleteRange?) as unpushable, so the intent would never move to a timestamp inconsistent with the cache?  I guess that would be equivalent to making all transactions containing DeleteRange SSI instead of SI. That seems easier than trying to update the timestamp cache when a transaction is pushed.

**Comment by vivekmenezes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[kv/txn_correctness_test.go, line 471 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFybKaxiDpsiWuqLzii:-KFybKaxiDpsiWuqLzij:-536856646) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L471)):*
can you document this in the comment above?

---

*[kv/txn_correctness_test.go, line 696 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFy_ireuGQz7lQK5wJW:-KFy_ireuGQz7lQK5wJX:1924100336) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L696)):*
delete key?

---

*[kv/txn_correctness_test.go, line 783 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFya8P_X4e31QDKJmJO:-KFya8P_X4e31QDKJmJP:-666169160) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L783)):*
issue #6277 doesn't exist

You can make this my TODO since I'm fixing the delete case in #6124

---

*[kv/txn_correctness_test.go, line 796 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFybzTY7LKqjqSoioVj:-KFybzTY7LKqjqSoioVk:1540718753) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L796)):*
update to the correct issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227)*

**Comment by tschottdorf** [comment]
@vivekmenezes yes, txn2 always reads A=1 in the failing cases.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[kv/txn_correctness_test.go, line 471 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFybKaxiDpsiWuqLzii:-KFynQuRrVuhO9rIi3VF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L471)):*
Done.

---

*[kv/txn_correctness_test.go, line 696 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFy_ireuGQz7lQK5wJW:-KFynWq-AqE0kwuFPZB8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L696)):*
Done.

---

*[kv/txn_correctness_test.go, line 783 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFya8P_X4e31QDKJmJO:-KFyoxKA1RuvP7E4spbW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L783)):*
Done.

---

*[kv/txn_correctness_test.go, line 796 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-KFybzTY7LKqjqSoioVj:-KFyoyHr0u-ogPZ8rRzu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a806e2c774891c051823a5e64f074adce6b9d6f3/kv/txn_correctness_test.go#L796)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-:-KFyp4i_d9W6getfN7-b:-285211100)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6227#-:-KFytISUaTkHmO_-saE-:1417088721)*

**Pull request merged**
