### PR TITLE
RFCs: update backup/restore RFC to match implementation

### PR DESCRIPTION
**Pull request by benesch**
Extracted from #16633.

### CODE REVIEW

**Comment by knz** [comment]
reminder: don't forget to rebase if you plan to continue work on this, and pick up the new RFC sections + naming convention.

**Comment by benesch** [comment]
Ping @danhhz!

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/backup_restore.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oHlVe3q7ZJwILHE11:-L5oHlVe3q7ZJwILHE12:b-4224tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L11)):*
> ```Markdown
> # Summary
> 
> Full Backup / Incremental Backup / Restore from Backup / Bulk Load
> ```

nit: this is Import now, but since what you have is strictly better than what's there and you're just trying to clear out PRs, i'm fine leaving this

---

*[docs/RFCS/backup_restore.md, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oHxJm_o61Kr0w7bDo:-L5oHxJm_o61Kr0w7bDp:b-8zsye) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L83)):*
> ```Markdown
> All range descriptors are scanned in a txn and each one becomes a keyrange
> segment for backup. Optionally, a selected set of tables can be backed up. The
> backup's progress is written to [the `system.jobs` table](./system_jobs.md) and
> ```

update link plz

---

*[docs/RFCS/backup_restore.md, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oI1YBg1oLwFNUu16i:-L5oI1YBg1oLwFNUu16j:bs428jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L150)):*
> ```Markdown
> corresponding segment data. The replica streams in the data, merging full and
> incremental backups as appropriate, and rewrites keys with the new table ID.
> These are applied in batches using the proposer evaluated kv `WriteBatch` or
> ```

nit: kill WriteBatch reference

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-:-L5oIFyG0hEBogExlqIP:bnfp4nl)*

**Comment by benesch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/backup_restore.md, line 11 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oHlVe3q7ZJwILHE11:-L5oIO7bBFy9rJx-IxcD:bku4wkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L11)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: this is Import now, but since what you have is strictly better than what's there and you're just trying to clear out PRs, i'm fine leaving this
</blockquote></details>

:thumbsup: yeah, IMPORT is sufficiently different than what's described here that I'm inclined to just leave this as historical reference.

---

*[docs/RFCS/backup_restore.md, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oHxJm_o61Kr0w7bDo:-L5oIam_51vjXgNAcTPi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L83)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

update link plz
</blockquote></details>

Done.

---

*[docs/RFCS/backup_restore.md, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738#-L5oI1YBg1oLwFNUu16i:-L5oIdkMYXrwU_jMEf2S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f8a90ccfc1505d70baccf15ad64e90a2a71fdf/docs/RFCS/backup_restore.md#L150)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: kill WriteBatch reference
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16738)*

**Comment by benesch** [comment]
Thanks!

**Pull request merged**
