### PR TITLE
kv/concurrency: deflake TestContentionEventTracer

### PR DESCRIPTION
**Pull request by nvb**
I was occasionally seeing this flake with errors like:
```
--- FAIL: TestContentionEventTracer (0.00s)
    assertion_compare.go:332:
        	Error Trace:	lock_table_waiter_test.go:1000
        	Error:      	"178µs" is not less than "178µs"
        	Test:       	TestContentionEventTracer
        	Messages:   	[]
```

This was because the test was expecting passage of time in the system
clock between two events. This commit resolves the issue by eliminating
the dependency on the system clock and replacing it with a manual clock.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Did the test need one microsecond to pass, or one nanosecond?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81139#-:-N1eEocTEPQUfEZCWKx7:bwrt1x3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
I think it just needed 1 ns between each event, but somehow it wasn't even getting that sometimes when stressed with bazel.

**Comment by nvanbenschoten** [comment]
Gentle ping.

**Comment by andreimatei** [comment]
> I think it just needed 1 ns between each event, but somehow it wasn't even getting that sometimes when stressed with bazel.

I feel like I don't believe it. Let me try it too.

**Comment by andreimatei** [comment]
This shouldn't be necessary any more since https://github.com/cockroachdb/cockroach/pull/81484

**Pull request closed without merging**
