### PR TITLE
release-21.2: vendor: bump Pebble to e0860f772edf

### PR DESCRIPTION
**Pull request by jbowens**
```
e0860f7 compaction: fix nil pointer during errored compactions
```

Informs #70443.

Release note: none

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The question at https://github.com/cockroachdb/pebble/pull/1282#pullrequestreview-760127629 is relevant to this bump

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70499#-:-Mk8eaUp6OTRQYkifo5j:b7mycqb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jbowens — COMMENTED** [review]
> The question at cockroachdb/pebble#1282 (review) is relevant to this bump

I think realistically this bump will be subsumed by a new bump that includes the SetWithDelete changes, since this PR must wait until Monday's release triage meeting for merge approval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70499#-:-Mk8vfus06aOvffZLCoA:bxur589)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by sumeerbhola** [comment]
Is there anything we need after https://github.com/cockroachdb/pebble/pull/1287 is merged, before the monday meeting? If so, I can wait before creating another bump PR.

**Comment by jbowens** [comment]
> Is there anything we need after cockroachdb/pebble#1287 is merged, before the monday meeting? If so, I can wait before creating another bump PR.

I think that's it! I'm going to close this one out.

**Pull request closed without merging**
