### PR TITLE
sql: support labeled tuples in distsql

### PR DESCRIPTION
**Pull request by rjnn**

### CODE REVIEW

**Review by knz — CHANGES_REQUESTED** [review]
Wow this is surprisingly straightforward. Kudos on making this so concise.

:lgtm: modulo a nit

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-:-LIRjSmo7tv082ofuhNF:b7fmpam)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.go, line 2333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRk7MgDpijbYmuJV-d:-LIRk7MgDpijbYmuJV-e:b-ajkk05) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2333)):*
> ```Go
> 			}
> 		}
> 		ctyp.TupleLabels = make([]string, len(t.Types))
> ```

This code always allocates a len-sized label slice even if there are no labels in `t`.

And then even if you were to use `len(t.Labels)` I'd still avoid invoking `make` if len(c.Labels) == 0
(otherwise you get a heap allocation for a 0-sized slice. The conditional is cheaper than the 0-sized alloc.)
___
*[pkg/sql/sqlbase/structured.go, line 2410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRjfUM9j2Z4AbDSnfy:-LIRjfUM9j2Z4AbDSnfz:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2410)):*
> ```Go
> 		datums := types.TTuple{
> 			Types:  make([]types.T, len(c.TupleContents)),
> 			Labels: make([]string, len(c.TupleLabels)),
> ```

ditto

**Review by knz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27985)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 2333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRk7MgDpijbYmuJV-d:-LIRr2EPAPQRTNKd5Elu:b-a07lal) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2333)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This code always allocates a len-sized label slice even if there are no labels in `t`.

And then even if you were to use `len(t.Labels)` I'd still avoid invoking `make` if len(c.Labels) == 0
(otherwise you get a heap allocation for a 0-sized slice. The conditional is cheaper than the 0-sized alloc.)
</blockquote></details>

Radu just taught me that no this does not go to the heap alloc, a make with a zero len is a special thing that's fast. (TIL)

So your code is fine as long as you use `len(t.Labels)` here.

However I just go another idea: the TTuple instances are immutable. So I think it's probably safe for you to do `ctyp.TupleLabels =  t.Labels` directly.
___
*[pkg/sql/sqlbase/structured.go, line 2410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRrMRF33iemF2dqzl8:-LIRrMRF33iemF2dqzl9:b2h77cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2410)):*
> ```Go
> 		datums := types.TTuple{
> 			Types:  make([]types.T, len(c.TupleContents)),
> 			Labels: make([]string, len(c.TupleLabels)),
> ```

ditto perhaps  `Labels: c.TupleLabels` is safe. Less sure about that one (you'll need to check that the ColumnType instance is not rewritten in-place by the caller. I don't think it is.)

**Review by rjnn — COMMENTED** [review]
TFTR!
This part is straightforward, but I've been banging my head against the `ROW(1)` problem for a couple days now. Decided to split this part off to get it in early.

will merge on green.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-:-LIRvDtiDzdo1Ur_s8LR:b8f9m47)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.go, line 2333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRk7MgDpijbYmuJV-d:-LIRvfHJDOrMfzBjzDp7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2333)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Radu just taught me that no this does not go to the heap alloc, a make with a zero len is a special thing that's fast. (TIL)

So your code is fine as long as you use `len(t.Labels)` here.

However I just go another idea: the TTuple instances are immutable. So I think it's probably safe for you to do `ctyp.TupleLabels =  t.Labels` directly.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRjfUM9j2Z4AbDSnfy:-LIRwOZR2VotgKhIsfbS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2410)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27985#-LIRrMRF33iemF2dqzl8:-LIRwYs-6HETiuc2-AlK:btudrrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eda811fbcb7b9b30dfbb748e73af4d30b572a077/pkg/sql/sqlbase/structured.go#L2410)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto perhaps  `Labels: c.TupleLabels` is safe. Less sure about that one (you'll need to check that the ColumnType instance is not rewritten in-place by the caller. I don't think it is.)
</blockquote></details>

Done. It is safe. It is never modified.

**Review by knz — APPROVED** [review]

**Pull request merged**
