### PR TITLE
roachtest: delete tpchvec/smithcmp

### LINKED ISSUE #119055: roachtest: tpchvec/smithcmp failed
roachtest.tpchvec/smithcmp [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13935520?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13935520?buildTab=artifacts#/tpchvec/smithcmp) on release-23.2 @ [11ad4340c4949d16546de5f4064357d7c39882fe](https://github.com/cockroachdb/cockroach/commits/11ad4340c4949d16546de5f4064357d7c39882fe):

```
(tpchvec.go:580).smithcmpTestRun: full command output in run_075436.054138355_n1_smithcmp-tpchvecsmit.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/tpchvec/smithcmp/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13935520/tpchvec-smithcmp/1707551589273/1707551815132)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #119054 roachtest: tpchvec/smithcmp failed [C-test-failure O-roachtest O-robot T-sql-queries branch-release-23.1 release-blocker]
- #119053 roachtest: tpchvec/smithcmp failed [C-test-failure O-roachtest O-robot T-sql-queries branch-release-23.1.15-rc release-blocker]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpchvec/smithcmp.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36006

### PR DESCRIPTION
**Pull request by yuzefovich**
This tpchvec config was added about 4 years ago, uses `smithcmp` binary to issue TPCH queries with randomized placeholder values against a cluster with preloaded data set, and then compares results of `vectorize=off` against `vectorize=on` connections. However, this test has never found a single problem, so it doesn't seem that useful. Recently there were some changes to roachtest infra that made the test fail on older branches, so I think the burden of maintaining this test outweighs its benefits, so this commit removes it altogether (and it'll be removed on older branches too).

This commit also does a minor cleanup of the roachtest to inline some parameters that now have only one variant.

Fixes: #119055.

Epic: None

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119102#-:-NqU5QxFCD2-47nABQNZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @herkolategan)

**Review by DarrylWong — APPROVED** [review]
LGTM but just a heads up that #118988 in bors queue right now will probably cause merge conflicts.  You're good to delete all the `tpchvec` logic added there though.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
