### PR TITLE
sql: EncDatum.Compare

### PR DESCRIPTION
**Pull request by RaduBerinde**
Implementing EncDatum compare function which can operate directly on encodings
as long as they are order-preserving.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7304)

### CODE REVIEW

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/encoded_datum_test.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxXb7Nb_U_8hwirQh:-KKQxXb7Nb_U_8hwirQi:153138876) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L91)):*
> ```Go
> }
> 
> // checkEncDatumCompare encodes the given vales using the given encodings,
> ```

nit: values

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKQxeIrTgnScwAmnG1l:-726554025) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
> ```Go
> 	noncmp := DatumEncoding_VALUE
> 
> 	checkEncDatumCmp(t, a, v1, v2, asc, asc, -1, false)
> ```

Unless there's some reason I'm not seeing, a table driven test is more idiomatic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-:-KKQyAldzoNPbihzCChY:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTMCPHc6wIJYOuJqvq:-1602476163) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Unless there's some reason I'm not seeing, a table driven test is more idiomatic
</details>
TFTR! Given that we only have one line per test, this is actually more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTN_iu0lxqSvDCR8SO:784620086) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> TFTR! Given that we only have one line per test, this is actually more readable.
</details>
In the case of failure, how do you know which one failed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTSitIdUFnNkhF6CLe:-920212558) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> In the case of failure, how do you know which one failed?
</details>
From the error message. (And if I had a table driven and called `checkEncDatumCmp` in a loop, how would that help?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTW-rRz5pf3POUQrAv:-1655661131) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> From the error message. (And if I had a table driven and called `checkEncDatumCmp` in a loop, how would that help?)
</details>
you'd include the loop variable in the message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTWlfqrpoCDka7KVfo:164100230) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> you'd include the loop variable in the message
</details>
I am including everything that's relevant already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTXcO2EDeP0fyRKUvp:568311250) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I am including everything that's relevant already.
</details>
We can agree to disagree, but I think this is much less readable than a table driven test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/encoded_datum_test.go, line 151 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304#-KKQxeIrTgnScwAmnG1k:-KKTYHIM5Tk9YaBuEefK:-1389795667) ([raw file](https://github.com/cockroachdb/cockroach/blob/3857e0a1f51ce20ce58d143f825d9398c84b14ea/sql/sqlbase/encoded_datum_test.go#L151)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> We can agree to disagree, but I think this is much less readable than a table driven test.
</details>
Given that at table is how I started and then decided it was just unnecessary boilerplate in this case, we definitely agree to disagree. Good thing it's pretty inconsequential :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7304)*

**Pull request merged**
