### PR TITLE
colexec: account for some things during the aggregation

### LINKED ISSUE #54360: Node killed by OOM
It’s a 10 nodes cluster, running on gcp with this config n2-standard-8 (8 vCPUs, 32 GB memory)
It is running on Ubuntu 18.04 without Kubernetes.
The problem is exists on both V20.2.0-ALPHA.3 and V20.1.5..

All nodes start with this command 

ulimit -n 65536 && ./cockroach start --cache=25%  --max-sql-memory=25%  --background --locality=cloud=gcp,region=us-east1,datacenter=us-east1-c --store=path=/mnt/d1,attrs=ssd,size=90% --log-dir=log --certs-dir=certs --max-disk-temp-storage=100GB --locality-advertise-addr=cloud=gcp@172.28.0.29,region=us-east1@172.28.0.29,datacenter=us-east1-c@172.28.0.29 --join=172.28.0.29,172.28.0.30,172.28.0.31,172.28.0.32,172.28.0.33,172.28.0.34,172.28.0.35 --advertise-addr=172.28.0.29

Here is the schema and query

CREATE TABLE t_baseid (
             bid INT8 NOT NULL,
             emailcrc INT8 NOT NULL,
             emailmd5 STRING(32) NOT NULL,
             emailsha1 STRING(40) NOT NULL,
             email STRING NOT NULL,
             CONSTRAINT "primary" PRIMARY KEY (bid ASC),
             INDEX idx_emailsha1 (emailsha1 ASC),
             INDEX idx_emailcrc (emailcrc ASC),
             INDEX idx_emailmd5 (emailmd5 ASC),
             FAMILY "primary" (bid, emailcrc, emailmd5, emailsha1, email)

root@:26257/filu> explain select email,count(0) from t_baseid group by email having count(0) > 1;
         tree         |    field    |   description
----------------------+-------------+-------------------
                      | distributed | true
                      | vectorized  | false
  filter              |             |
   │                  | filter      | count > 1
   └── group          |             |
        │             | aggregate 0 | email
        │             | aggregate 1 | count(column6)
        │             | group by    | email
        └── render    |             |
             └── scan |             |
                      | table       | t_baseid@primary
                      | spans       | FULL SCAN
(12 rows)

Time: 157.441488ms

The oom issue happened on a v20.1.5 cluster on the 4th try, but it could also happen on the first try. 

root@:26257/filu> select email,count(0) from t_baseid group by email having count(0) > 1;
ERROR: root: memory budget exceeded: 1073741824 bytes requested, 7883292672 currently allocated, 8419290112 bytes in budget
SQLSTATE: 53200
root@:26257/filu> select email,count(0) from t_baseid group by email having count(0) > 1;
ERROR: root: memory budget exceeded: 1073741824 bytes requested, 7930335232 currently allocated, 8419290112 bytes in budget
SQLSTATE: 53200
root@:26257/filu> select email,count(0) from t_baseid group by email having count(0) > 1;
ERROR: root: memory budget exceeded: 1073741824 bytes requested, 8021225472 currently allocated, 8419290112 bytes in budget
SQLSTATE: 53200
root@:26257/filu> select email,count(0) from t_baseid group by email having count(0) > 1;
ERROR: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp 127.0.0.1:26257: connect: connection refused
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the database name: dial tcp 127.0.0.1:26257: connect: connection refused
root@:26257/? ?>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: account for some things during the aggregation**

Previously, we didn't account for several things during the aggregation
(which can be non-trivial in case of the hash aggregation)
- any_not_null and min/max aggregates can hold on to byte slices and
datums of arbitrary size for a long time (namely, until the input to the
aggregation has been fully consumed in case of the hash aggregation)
- we didn't account for the overhead of slices of different aggregate
functions that we use to batch-allocate them. These can add up to
non-trivial amount with many groups
- we didn't performed the accounting on the output batch after `Flush`
is performed (any_not_null and min/max didn't do it either), so we might
grow the output vector and not update the allocator.

These shortcomings are now fixed.

Fixes: #54360.

Release note (bug fix): CockroachDB previously didn't account for all
the memory used by the vectorized hash aggregation which could lead to
an OOM crash.

**colexec: move some code around for unification**

This commit is a mechanical change to have the same layout among all
aggregate function files. Also, it manually inlines one utility function
of concat aggregate.

Release note: None

**colexec: add missing memory accounting in projection operators**

We weren't using `PerformOperation` call in the projection operators
which is acceptable for fixed-size types. However, it is not acceptable
in general, and this commit fixes that.

Release note: None

**colmem: precisely account for decimals**

`apd.Decimal` supports decimals of arbitrary precision, so a single
object can be of an artibtrary size. We use 50 bytes as an estimate;
however, we can be more precise when calculating the footprint of the
vector of decimals which is now added in this commit.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The [benchmarks](https://gist.github.com/yuzefovich/db3ce32272ec19847489e2a630de6003) don't show visible changes (which is what we want).

**Review by asubiotto — COMMENTED** [review]
> Reviewed 31 of 31 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyFg5IC8r4cE4kmrhJ:-MIyFg5IC8r4cE4kmrhK:bey3w23) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/any_not_null_agg_tmpl.go#L173)):*
> ```Go
> 	)
> 	// {{if eq .VecMethod "Bytes"}}
> 	newCurAggSize := len(a.curAgg)
> ```

So this `curAgg` is an issue because we'll store it per hash aggregate function until the end of the aggregation? Are there any other aggregate functions that have this issue?
___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyGfZ84_Z225DfFnVK:-MIyGfZ84_Z225DfFnVL:b-6l4ddy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/any_not_null_agg_tmpl.go#L206)):*
> ```Go
> 	}
> 	// {{end}}
> 	a.curAgg = nil
> ```

How does this change things?
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyHnRM8DEVcTq7nKjs:-MIyHnRM8DEVcTq7nKjt:bhrby3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/602aa34aca935b5dc17e2cde6c71b672866ec770/pkg/sql/colexec/concat_agg_tmpl.go#L104)):*
> ```Go
> 	a.curIdx++
> 	// {{end}}
> 	a.allocator.PerformOperation(
> ```

Were these `PerformOperation` calls noops?
___
*[pkg/sql/colexec/default_agg_tmpl.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyInsyBHqcWlUDABSh:-MIyInsyBHqcWlUDABSi:blp5via) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/default_agg_tmpl.go#L168)):*
> ```Go
> 	} else {
> 		coldata.SetValueAt(a.vec, a.resultConverter(res), outputIdx)
> 	}
> ```

Any references that we can release in the wrapped aggregate function?
___
*[pkg/sql/colexec/hash_aggregator.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyIwbw-2NQoh__aI6L:-MIyIwbw-2NQoh__aI6M:b8tc2dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/hash_aggregator.go#L259)):*
> ```Go
> 					bucket := op.buckets[curOutputIdx]
> 					for _, fn := range bucket.fns {
> 						fn.Flush(curOutputIdx)
> ```

`Flush` could probably use a comment on the interface about memory ownership (i.e. make sure to account)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyFg5IC8r4cE4kmrhJ:-MIzA22r-bIbN0tmHhdi:bupix0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/any_not_null_agg_tmpl.go#L173)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So this `curAgg` is an issue because we'll store it per hash aggregate function until the end of the aggregation? Are there any other aggregate functions that have this issue?
</blockquote></details>

Yes, that's the problem. Only `anyNotNull` and `min/max` are susceptible to this issue among the optimized aggregate funcs (for all other optimized funcs `curAgg` is of non-variable size type, so it is appropriately accounted for when a function object is allocated). The accounting for `curAgg` in the default agg function is done by the wrapped row-exec aggregate builtin, so there is no need to do anything there.
___
*[pkg/sql/colexec/any_not_null_agg_tmpl.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyGfZ84_Z225DfFnVK:-MIzAdHgCIYuUWcnQork:bjwyxaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/any_not_null_agg_tmpl.go#L206)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How does this change things?
</blockquote></details>

This setting to `nil` is an optimization. Consider the following scenario: we have 10 buckets with 1MB of data in `curAgg`, once we've consumed the input, we'll be `Flush`ing each bucket. In there we will copy 1MB of data from `curAgg` into the output vector, and the output vector will have 10MB of data. However, once we've copied the data over we no longer need the references to each 1MB chunk, and this setting to `nil` releases the references eagerly (which might help with GC). It was an idea implemented in `concatAgg` by an external contributor, and I think it's nice to have it here as well (and in min/max).
___
*[pkg/sql/colexec/concat_agg_tmpl.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyHnRM8DEVcTq7nKjs:-MIzBLT1A8LN-cJ4w2_t:bjwwaro) ([raw file](https://github.com/cockroachdb/cockroach/blob/602aa34aca935b5dc17e2cde6c71b672866ec770/pkg/sql/colexec/concat_agg_tmpl.go#L104)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Were these `PerformOperation` calls noops?
</blockquote></details>

No, but now all calls to `Flush` are wrapped with `PerformOperation`, so the "internal" call is redundant.
___
*[pkg/sql/colexec/default_agg_tmpl.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyInsyBHqcWlUDABSh:-MIzBtnq72IcSqRDGf3P:bcsr7yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/default_agg_tmpl.go#L168)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any references that we can release in the wrapped aggregate function?
</blockquote></details>

`tree.AggregateFunc` interface doesn't have a method for that. There is `Reset`, but it keeps the reference to the memory if possible. If we change `colexec.aggregateFunc` interface to remove its `Reset` method, then we could be calling `a.fn.Close` which would release the references to the internal memory. I don't think it's important to do though at this point.
___
*[pkg/sql/colexec/hash_aggregator.go, line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MIyIwbw-2NQoh__aI6L:-MIzCoRV-TQEEN2ziNVq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aac15118df937591b8f966f4a9307d7b2211f83/pkg/sql/colexec/hash_aggregator.go#L259)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`Flush` could probably use a comment on the interface about memory ownership (i.e. make sure to account)
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Hm, I guess another data type with variable size is a decimal, but I think in most cases a size of a single `apd.Decimal` should be limited by a constant, right? I'm inclined to not care about it (at least for the time being).

**Review by asubiotto — COMMENTED** [review]
> I think in most cases a size of a single apd.Decimal should be limited by a constant

I don't know if that's true. What's the overhead of adding this? In any case, I think you should consider extracting the size calculation somewhere to avoid having to update multiple places with the `Decimal` size now or in the future.

> Reviewed 11 of 11 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-:-MJ6b_JTDLYahlIYKUpb:b-xpuudl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Found another place where we were missing `PerformOperation` call and added the precise accounting for `apd.Decimal`s.

> What's the overhead of adding this?

In some quick benchmarks (of the projection operators), the overhead is on the order of 3-5%.  I think it is the upper bound on the overhead, so it should be acceptable.

I'll open up a PR to add the `Size` method to `apd.Decimal` itself.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-:-MJ8uLbD6PmRoxC6YW-2:b-fiss9p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Updated, PTAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, 4 of 4 files at r6, 6 of 6 files at r7, 10 of 10 files at r8, 4 of 4 files at r9, 6 of 6 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 106 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MJW8HNq3VzXZhzIfW_M:-MJW8HNq3VzXZhzIfW_N:b-srexoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39370560db751d79084932699d58715a70b08b1/pkg/sql/colexec/proj_const_ops_tmpl.go#L106)):*
> ```Go
> 		// updating the output Nulls from within _ASSIGN functions when the result
> 		// of a projection is Null.
> 		_outNulls := projVec.Nulls()
> ```

What has this got to do with this commit? The description only talks about `PerformOperation`. If this is is unrelated, please extract it into a separate commit.
___
*[pkg/sql/sem/tree/datum.go, line 1070 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MJW8ufb3a2p-QfK9CbJ:-MJW8ufcDSIWJYjR59lY:b-ksj2c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c21af21c55191dc90a9ccd317f3cd071cce8dea/pkg/sql/sem/tree/datum.go#L1070)):*
> ```Go
> // sizeOfFixedPartOfDecimal is the size of the fixed part of apd.Decimal in
> // bytes.
> const sizeOfFixedPartOfDecimal = unsafe.Sizeof(apd.Decimal{})
> ```

nit: `s/sizeOfFixedPartOfDecimal/shallowDecimalSize` or something similar, to avoid multiple "of"s

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 106 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MJW8HNq3VzXZhzIfW_M:-MJXZ0bh2ruPYTfAvGgT:b-nczmb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39370560db751d79084932699d58715a70b08b1/pkg/sql/colexec/proj_const_ops_tmpl.go#L106)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What has this got to do with this commit? The description only talks about `PerformOperation`. If this is is unrelated, please extract it into a separate commit.
</blockquote></details>

Note that it was already present - only the indentation changed. This particular logic was recently added by Marcus.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 106 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MJW8HNq3VzXZhzIfW_M:-MJXxKkCEfqBHZZEwtlN:b-u9ap4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39370560db751d79084932699d58715a70b08b1/pkg/sql/colexec/proj_const_ops_tmpl.go#L106)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Note that it was already present - only the indentation changed. This particular logic was recently added by Marcus.
</blockquote></details>

You're right, for some reason reviewable was showing this as a new line. Carry on.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/proj_const_ops_tmpl.go, line 106 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-MJW8HNq3VzXZhzIfW_M:-MJXyFkX7Dh1IWg-_N6i:bc4cufa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b39370560db751d79084932699d58715a70b08b1/pkg/sql/colexec/proj_const_ops_tmpl.go#L106)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You're right, for some reason reviewable was showing this as a new line. Carry on.
</blockquote></details>

I believe I responded to all the comments, any other feedback?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55195#-:-MJb6L7k9w3Ky0ZcfFFj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
