### PR TITLE
Improve performance of admin UI under loss of quorum

### PR DESCRIPTION
**Pull request by cuongdo**
This makes the admin UI perform inconsistent reads, which required adding support for inconsistent reads to the KV client.

This also moves events API call to the events page. Previously, we were always hitting the events API, which issues SQL queries that just hang when we lose our quorum.

cc @maxlang for events change, @tschottdorf for KV changes

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5519)

### CODE REVIEW

**Comment by tamird** [comment]
There's a bunch of prose in the PR description which is absent from the commit messages. Can you fit that into the commits? Looks like the second one would be the better place.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-:-KD_El_47voCSeeP2S3S:1309507859)*

**Comment by tschottdorf** [comment]
:lgtm: on kv and acceptance mod my comments.

---

Reviewed 9 of 9 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[acceptance/admin_test.go, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_JIXAtrDZMBXgU-RR:-KD_JIXAtrDZMBXgU-RS:1956532068) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf1ce1cf75270381338baaecbd3d5d282f1e63c/acceptance/admin_test.go#L33)):*
The right condition should be `c.NumNodes() < 2` (a two node cluster with one node is valid to test this for).

---

*[acceptance/admin_test.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_JeetOtI01K2HOJr3:-KD_JeetOtI01K2HOJr4:395232336) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf1ce1cf75270381338baaecbd3d5d282f1e63c/acceptance/admin_test.go#L72)):*
It doesn't matter because the server can't tell whether it's valid before it queries, right?

---

*[client/batch.go, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_HnNe_qkCkuxCVGo7:-KD_HnNfwAqDEFNCvJd3:-1441418503) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/batch.go#L54)):*
better to make sure you can't write in `INCONSISTENT`, unless that's really tricky for some reason.

---

*[client/client_test.go, line 719 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_HzeHu-75YMzZK56y:-KD_HzeHu-75YMzZK56z:953159055) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/client_test.go#L719)):*
you don't need to start an actual server. Just use this code which lives in `client/sender.go`:

```go
// SenderFunc is an adapter to allow the use of ordinary functions
// as Senders.
type SenderFunc func(context.Context, roachpb.BatchRequest) (*roachpb.BatchResponse, *roachpb.Error)

// Send calls f(ctx, c).
func (f SenderFunc) Send(ctx context.Context, ba roachpb.BatchRequest) (*roachpb.BatchResponse, *roachpb.Error) {
	return f(ctx, ba)
}
```

and make a `SenderFunc` that takes the role of your `RPCSendFn`. A lot of things will go away.

---

*[client/db_test.go, line 371 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_ImOV4DN0Mq6sS8H5:-KD_ImOV4DN0Mq6sS8H6:-1383032131) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/db_test.go#L371)):*
Could you white/blacklist those explicitly?

---

*[client/txn.go, line 548 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_IyfLOBnLAIkiApjl:-KD_IyfLOBnLAIkiApjm:-817195299) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/txn.go#L548)):*
What requires this parameter?

---

*[kv/dist_sender.go, line 122 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_J3TSDLduS3XKRORI:-KD_J3TSDLduS3XKRORJ:-1947872136) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/kv/dist_sender.go#L122)):*
Can be unexported again with my comment above.

---

*[kv/send.go, line 287 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_J8p-Fpd2ca_5ZTbS:-KD_J8p-Fpd2ca_5ZTbT:2065126139) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/kv/send.go#L287)):*
ditto about unexporting, hopefully.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-:-KD_JuD9MtlN1eFIMXs6:-1326285663)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519)*

**Comment by cuongdo** [comment]
@tamird: done (I've also updated the pull request message, since @mrtracy and I fixed an issue that was mentioned there)

---

Reviewed 1 of 7 files at r2.
Review status: 2 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[acceptance/admin_test.go, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_JIXAtrDZMBXgU-RR:-KDaFhCikee0B9hXq6di:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf1ce1cf75270381338baaecbd3d5d282f1e63c/acceptance/admin_test.go#L33)):*
Done.

---

*[acceptance/admin_test.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_JeetOtI01K2HOJr3:-KDaFhtN6RP3p8fn1JaV:-301593926) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf1ce1cf75270381338baaecbd3d5d282f1e63c/acceptance/admin_test.go#L72)):*
Yes, all that matters is that we're issuing a KV request to service the time-series query.

---

*[client/batch.go, line 54 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_HnNe_qkCkuxCVGo7:-KDaQNyLdOaoSvhltaMp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/batch.go#L54)):*
Done.

---

*[client/client_test.go, line 719 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_HzeHu-75YMzZK56y:-KDaJTJbYAtEM1oHiIGC:1704032847) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/client_test.go#L719)):*
Much cleaner now! Done.

---

*[client/db_test.go, line 371 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_ImOV4DN0Mq6sS8H5:-KDaKkQmXoZKi8CWQ6M8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/db_test.go#L371)):*
Done.

---

*[client/txn.go, line 548 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_IyfLOBnLAIkiApjl:-KDaKvg3UCoRSJSzLT8u:-1028260829) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/client/txn.go#L548)):*
`(*DB).Run(*Batch)` calls `(*DB).sendAndFill()`, which passes `Batch.ReadConsistency` to this method.

---

*[kv/dist_sender.go, line 122 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_J3TSDLduS3XKRORI:-KDaLnV6gZyZ2a0LwCB2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/kv/dist_sender.go#L122)):*
Done.

---

*[kv/send.go, line 287 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-KD_J8p-Fpd2ca_5ZTbS:-KDaQP5_iDJxgUkuWQjK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/62ed93db4764060b5c1ace9109781e3c45fe92f8/kv/send.go#L287)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-:-KDaFJlPac86N2-9aaT8:305451797)*

**Comment by cuongdo** [comment]
@mrtracy, @maxlang: any comments about the TypeScript?

---

Review status: 2 of 14 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5519#-:-KDaQT7cHsqWHda12fwc:-995106843)*

**Pull request merged**
