### PR TITLE
storage: clean up newNotLeaseHolderError

### LINKED ISSUE #3670: storage: some confusion about newNotLeaseHolderError
Why call ```FindReplica``` to get the leader, but not use ```l.Replica```? They are different?

```
func (r *Replica) newNotLeaderError(l *roachpb.Lease, originStoreID roachpb.StoreID) error {
	err := &roachpb.NotLeaderError{}
	if l != nil && l.Replica.ReplicaID != 0 {
		desc := r.Desc()

		err.RangeID = desc.RangeID
		_, err.Replica = desc.FindReplica(originStoreID)
		_, err.Leader = desc.FindReplica(l.Replica.StoreID)
	}
	return
```

### PR DESCRIPTION
**Pull request by tbg**
Make more explicit why we are consulting the range descriptor in
newNotLeaseHolderError.

Fixes #3670.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8224)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica.go, line 556 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOArUxT0UGuACs6p6vk:-KOArUxT0UGuACs6p6vl:1695767211) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/storage/replica.go#L556)):*
> ```Go
> 
> // newNotLeaseHolderError returns a NotLeaseHolderError initialized with the
> // replica for the holder (if any) of the given lease.
> ```

nit: blank line between paragraphs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-:-KOArsr5XQV0JvbfXWXq:1417088721)*

**Comment by tschottdorf** [comment]
TFTR!

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 556 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOArUxT0UGuACs6p6vk:-KOAsqR_Trz5FXlD5EmN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/storage/replica.go#L556)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> nit: blank line between paragraphs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-:-KOAsvIHBWVBYHq_yid2:-485616692)*

**Comment by tamird** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[roachpb/errors.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOAn6OXF-G1HdcQVdXn:-KOAn6OXF-G1HdcQVdXo:-1960117785) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/roachpb/errors.proto#L35)):*
> ```protobuf
> // holder. If the lease holder is known, its Replica is set in the error.
> message NotLeaseHolderError {
>   // The replica the error originated from. Used in its string representation.
> ```

s/its/the/? maybe i'm not understanding the second sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224)*

**Comment by tschottdorf** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[roachpb/errors.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOAn6OXF-G1HdcQVdXn:-KOAtWtAn9z-VBkAhyLe:178668966) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/roachpb/errors.proto#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/its/the/? maybe i'm not understanding the second sentence.
</details>
Used in its (the error's) string representation. No bueno?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[roachpb/errors.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOAn6OXF-G1HdcQVdXn:-KOAuuwRmnXKjefFMHxv:-265571875) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/roachpb/errors.proto#L35)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Used in its (the error's) string representation. No bueno?
</details>
Yeah, it's not clear what the subject is. It could be the replica's string representation - that's why I suggested "the" but perhaps there's something better still.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[roachpb/errors.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOAn6OXF-G1HdcQVdXn:-KOAvp1rWDW0u9u9iXBD:-744520826) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/roachpb/errors.proto#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, it's not clear what the subject is. It could be the replica's string representation - that's why I suggested "the" but perhaps there's something better still.
</details>
I read "its" as referring to the replica too. "the" is a little better but still unclear; I'd say "the error's"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-:-KOAwNjLKc_YKXZDhJzr:1417088721)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[roachpb/errors.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-KOAn6OXF-G1HdcQVdXn:-KOB0YqzOx7A4jlvHOzN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5280dd4026d9ab56c054bdadb137d4ca48919fb/roachpb/errors.proto#L35)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I read "its" as referring to the replica too. "the" is a little better but still unclear; I'd say "the error's"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8224#-:-KOB2x4FOFkfjl1IVfCL:1417088721)*

**Pull request merged**
