### PR TITLE
rpc: run grpc interceptors for local RPCs

### LINKED ISSUE #74732: rpc: unify InternalLocalClient optimization with regular request paths
**Is your feature request related to a problem? Please describe.**

When a gRPC client and gRPC server are local to each other, we avoid going through the network:

https://github.com/cockroachdb/cockroach/blob/775c2b0b0302ebf4b0c8c8515e015b793b8585ce/pkg/rpc/nodedialer/nodedialer.go#L158-L175

As an unfortunate side effect, this bypasses all of our gRPC interceptors:

https://github.com/cockroachdb/cockroach/blob/3f8c928c91966b4fd8f6837bb3fa2a119f57141d/pkg/rpc/context.go#L169-L174

and, perhaps less importantly, the client side ones:

https://github.com/cockroachdb/cockroach/blob/3f8c928c91966b4fd8f6837bb3fa2a119f57141d/pkg/rpc/context.go#L827-L828

This introduces subtle behavior changes between the two code paths that are
undesirable. The interceptors house tracing and auth logic, for example. In
principle any change to the interceptors requires a second round through the
internal code path, which rarely happens, leading to potential and actual
bugs.

**Describe the solution you'd like**

It seems desirable for the local vs regular code paths to share as much as
possible while preserving the performance benefit. Since we want to avoid
serialization, we can't use dialer trickery. Instead, the sweet spot might be
linking the respective interceptors into the right places.

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-12234

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, the gRPC interceptors that we normally run on the
client and the server were not being run for "RPCs" to the "Internal"
sevice going to the local node. Such RPCs are done through the
localClientAdapter, which bypasses gRPC for performance reasons. Not
running these interceptors is bad - they do useful things around
creating tasks, tracing, authentication/authorization.
Some of the things done by the interceptors was done separately and
redundantly in random places to account for the RPC local case.

This patch unifies the paths of local and remote RPCs by having the
localClientAdapter run the client and server interceptors. Care was
taken for the performance regression on the local path; still, one
new allocation is imposed by the client interceptor interface for
(unary) RPC calls: the result of the RPC needs to be allocated before
the RPC is made, and the proto that the server returns needs to be
copied over.
I've run some benchmarks with this change and it didn't show anything.

Node.batchInternal was simplified slightly to not create a task, since
the server interceptor now does it in all cases. Before, creating the
task was redundant in the non-local RPC case.

Fixes https://github.com/cockroachdb/cockroach/issues/74732

### CODE REVIEW

**Comment by tbg** [comment]
Awesome, thanks for tackling this! Will review tomorrow.

**Review by knz — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/rpc/context.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvXxvEwAGlejNsZcMkJ:-MvXxvEwAGlejNsZcMkK:b6fq6el) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L290)):*
> ```Go
> 		ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler,
> 	) (interface{}, error) {
> 		return handler(ctx, req)
> ```

I'm confused, what is this interceptor good for? It looks like the identity function to me.
___
*[pkg/rpc/context.go, line 727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvY-SNZAMv9t8BOzeKt:-MvY-SN_81y0nFXVCZrP:baoyzc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L727)):*
> ```Go
> 	i := 0
> 	var callNextInterceptor grpc.UnaryHandler
> 	callNextInterceptor = func(ctx context.Context, req interface{}) (interface{}, error) {
> ```

I think it would be useful here and below to explain that you (we) did not invent this code, you essentially copy-pasted it from `grpc/server.go`, `chain.*Interceptor()`.
Also explain that we're not relying on the grpc mechanism here because we want the chaining to be used also for local calls, not only remote, and grpc only calls the interceptors on remote calls.
(Essentially what you explain in the commit message, but copy-pasted in comments around this file.)

**Review by tbg — COMMENTED** [review]
> I don't know whether we should try to make this interceptor work or not.

I think we should. Bypassing the auth interceptor makes me a teeny bit nervous and the special casing around it (with the idx) while not exactly brittle (if it broke, we'd be using the auth interceptors on local RPCs, which would be obvious since they would prevent the local path from working) it is unsavory. Also, shouldn't this already work?

https://github.com/cockroachdb/cockroach/blob/d7569dae28d405437f5af670346d45c2d6deb42a/pkg/rpc/auth.go#L100-L106

The auth interceptor will treat anything with that context bit set as the system tenant, which is exactly what we want. This also shouldn't incur any additional allocations (if it does, they should be preventable).

Going to hold off on the line-by-line review, but I am generally liking what I see here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-MvYDlzm69DQTA9XR2EY:b-hhiuq0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @tbg)

___
*[pkg/rpc/context.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYCNh-8y7_5q8RTLR0:-MvYCNh-8y7_5q8RTLR1:b-2ogh8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L162)):*
> ```Go
> }
> 
> // ServerInterceptorInfo contains the serve interceptors that a server created
> ```

server?
___
*[pkg/rpc/context.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYDTAq20Yboe9kJp4I:-MvYDTAq20Yboe9kJp4J:b-ir3b68) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L167)):*
> ```Go
> 	// UnaryInterceptors lists the interceptors for regular (unary) RPCs.
> 	UnaryInterceptors []grpc.UnaryServerInterceptor
> 	// UnaryAuthIdx is the position of the Auth interceptor withing
> ```

within



_Code quote:_
```Go
 withing
```
___
*[pkg/rpc/context.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYDUpOCfnDqKKAQM_Z:-MvYDUpOCfnDqKKAQM__:b-ir3b68) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L172)):*
> ```Go
> 	// StreamInterceptors lists the interceptors for streaming RPCs.
> 	StreamInterceptors []grpc.StreamServerInterceptor
> 	// StreamAuthIdx is the position of the Auth interceptor withing
> ```

within



_Code quote:_
```Go
withing
```

**Comment by andreimatei** [comment]
Ready for another look.

**Comment by andreimatei** [comment]
The auth interceptor is no longer excluded from the local call path.

**Review by knz — COMMENTED** [review]
LGTM with nits

> Reviewed 1 of 7 files at r1, 15 of 15 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-Mw6xwxM5SbNRGyMTLec:b3nilp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[-- commits, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6xr6r4crRQDqofxDu):*
Can you explain in the commit message also why it's OK not to run the client interceptors at this point.
___
*[pkg/rpc/context.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6x-3_DjMxJqPB5_3l:-Mw6x-3_DjMxJqPB5_3m:bkxevir) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L568)):*
> ```Go
> 	ba.AdmissionHeader.SourceLocation = roachpb.AdmissionHeader_LOCAL
> 	// Create a new context from the existing one with the "local request" field set.
> 	// This tells the handler that this is an in-process request, bypassing ctx.Peer checks.
> ```

nit: make the context on a standalone line, so it's clear(er) what the comment refers to.
___
*[pkg/rpc/context.go, line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6wpAE1yFzWbr9ZXhC:-Mw6wpAE1yFzWbr9ZXhD:b1ozade) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L577)):*
> ```Go
> ) (roachpb.Internal_RangeFeedClient, error) {
> 	ctx, cancel := context.WithCancel(ctx)
> 	ctx, sp := tracing.ChildSpan(ctx, "/cockroach.roachpb.Internal/RangeFeed")
> ```

nit: is it possible to extract this method name string from the roachpb package somehow?
___
*[pkg/rpc/context.go, line 586 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6wTNcE0IiTrloe_Lw:-Mw6wTNcE0IiTrloe_Lx:b-3ddr1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L586)):*
> ```Go
> 	go func() {
> 		defer cancel()
> 		defer sp.Finish()
> ```

nit: finish the span before canceling the parent context
___
*[pkg/rpc/context.go, line 705 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6x_AY5f81ITZ57F5C:-Mw6x_AY5f81ITZ57F5D:bny7eng) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4d7302f491777d4fb5a8c7557ed63316ec932b/pkg/rpc/context.go#L705)):*
> ```Go
> 
> 		info := &grpc.StreamServerInfo{
> 			FullMethod:     "/cockroach.roachpb.Internal/RangeFeed",
> ```

ditto, use a go const and share the string in both places.

**Review by andreimatei — COMMENTED** [review]
I've now added the client interceptors too. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N1zLg2710zInfpizpSt:bx9nrq5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @shermanCRL, and @tbg)

___
*[`-- commits` line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6xr6r4crRQDqofxDu):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain in the commit message also why it's OK not to run the client interceptors at this point.
</blockquote></details>

I've added the client interceptors too now.
___
*[`pkg/rpc/context.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYCNh-8y7_5q8RTLR0:-Mw43Wys9f_vE6UhaJCj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L162)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

server?
</blockquote></details>

done
___
*[`pkg/rpc/context.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYDTAq20Yboe9kJp4I:-Mw43_Rb8K4LBnUKUvLn:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L167)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

within
</blockquote></details>

removed
___
*[`pkg/rpc/context.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvYDUpOCfnDqKKAQM_Z:-Mw43a8P8MvAjnpvnmF4:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L172)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

within
</blockquote></details>

removed
___
*[`pkg/rpc/context.go` line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvXxvEwAGlejNsZcMkJ:-Mw43wtD9JaME3Au6EUv:b-k12qfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L290)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'm confused, what is this interceptor good for? It looks like the identity function to me.
</blockquote></details>

this was leftover :S
Removed.
___
*[`pkg/rpc/context.go` line 727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-MvY-SNZAMv9t8BOzeKt:-Mw45JAZ11SRv2baQT7p:b-575zfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1abeee2310c2b245d1dea18974b4dc413802bdb6/pkg/rpc/context.go#L727)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think it would be useful here and below to explain that you (we) did not invent this code, you essentially copy-pasted it from `grpc/server.go`, `chain.*Interceptor()`.
Also explain that we're not relying on the grpc mechanism here because we want the chaining to be used also for local calls, not only remote, and grpc only calls the interceptors on remote calls.
(Essentially what you explain in the commit message, but copy-pasted in comments around this file.)
</blockquote></details>

I've added a link to gRPC here.
I've added a note to the definition of `internalClientAdapter` about how it runs interceptors even though it otherwise doesn't use gRPC.
___
*[`pkg/rpc/context.go` line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6x-3_DjMxJqPB5_3l:-N1zL9gqD-kwqIisjP-A:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L568)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: make the context on a standalone line, so it's clear(er) what the comment refers to.
</blockquote></details>

done
___
*[`pkg/rpc/context.go` line 577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6wpAE1yFzWbr9ZXhC:-N1zLGR2525AeZ0Tf0ge:b-63e8vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L577)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: is it possible to extract this method name string from the roachpb package somehow?
</blockquote></details>

unfortunately not
___
*[`pkg/rpc/context.go` line 586 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6wTNcE0IiTrloe_Lw:-N1zLTC23dwNl8j0oMl1:bqrz63s) ([raw file](https://github.com/cockroachdb/cockroach/blob/254de758dbcb6368c1e518fa357a6bd67ca80349/pkg/rpc/context.go#L586)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: finish the span before canceling the parent context
</blockquote></details>

this code is gone. But the Finish() was before the cancel...
___
*[`pkg/rpc/context.go` line 705 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-Mw6x_AY5f81ITZ57F5C:-N1zLZAo4feDmr6UG61x:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4d7302f491777d4fb5a8c7557ed63316ec932b/pkg/rpc/context.go#L705)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, use a go const and share the string in both places.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
@knz friendly ping for whenever :)
I'm short of victims for this, unfortunately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N3ec1wF2NvnD2J3HoO7:bwon37b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @knz, and @tbg)

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 92 files at r5, 1 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @knz, and @tbg)

**Review by knz — APPROVED** [review]
:lgtm: but you should _really_ get a second pair of eyes on this. Maybe @tbg or @erikgrinaker .

> Reviewed 11 of 11 files at r4, 92 of 92 files at r5, 16 of 17 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N3tPIS_1Xia_a0Czyu7:b7jthey)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
Not a line-by-line review, but conceptually looks good. Thanks Andrei!

> Reviewed 8 of 15 files at r2, 8 of 8 files at r3, 11 of 11 files at r4, 92 of 92 files at r5, 17 of 17 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N3xOSQX3aJjPGLWZS64:bm0giag)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/rpc/context.go` line 613 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3xO4Fq9ho59Y0DNlBt:-N3xO4Fq9ho59Y0DNlBu:b-8szdnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fea76956135da4b7521d781c6963ae254d57a8f/pkg/rpc/context.go#L613)):*
> ```Go
> 
> 	if tracer := rpcCtx.Stopper.Tracer(); tracer != nil {
> 		// TODO(tbg): re-write all of this for our tracer.
> ```

Nice try, past Tobias.

**Review by erikgrinaker — APPROVED** [review]
:lgtm: at a high level. Really appreciate the cleanups!

> Reviewed 5 of 15 files at r2, 11 of 11 files at r4, 92 of 92 files at r5, 17 of 17 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N3xRih52GjwR8-WZLLs:bfrr8u3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/rpc/context.go` line 613 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3xO4Fq9ho59Y0DNlBt:-N3ytd1H0tggB2TlA_Jv:bx5i0sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fea76956135da4b7521d781c6963ae254d57a8f/pkg/rpc/context.go#L613)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Nice try, past Tobias.
</blockquote></details>

dropped. Unless you tell me what it meant.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 17 files at r6, 4 of 110 files at r8, 85 of 97 files at r9, 12 of 19 files at r10, 14 of 14 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @tbg)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3yuwwZ8eyxtLpu1u-I:-N3yuwwZ8eyxtLpu1u-J:b-esmqvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a729ba469bb6ef0c4dc7829a8cdbc2349125281/pkg/sql/sem/builtins/generator_probe_ranges.go#L158)):*
> ```Go
> 		})
> 		if err != nil {
> 			return nil, errors.Wrapf(err, "%s", sp.FinishAndGetConfiguredRecording().String())
> ```

`"%v`, sp.FinishAndGetConfiguredRecording()` ?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz and @tbg)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3yuwwZ8eyxtLpu1u-I:-N3ywLPBAgC4VCSKVhky:b-wd3aef) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a729ba469bb6ef0c4dc7829a8cdbc2349125281/pkg/sql/sem/builtins/generator_probe_ranges.go#L158)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`"%v`, sp.FinishAndGetConfiguredRecording()` ?
</blockquote></details>

meh, I don't think it's worth taking the blame to remove the `String()` call
Or, any particular reason why you want`%v` instead of `%s`?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @tbg)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3yuwwZ8eyxtLpu1u-I:-N3yxEWxEkae_yakfz3M:bh4brps) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a729ba469bb6ef0c4dc7829a8cdbc2349125281/pkg/sql/sem/builtins/generator_probe_ranges.go#L158)):*
%v/%s doesn't matter much, however
> I don't think it's worth taking the blame to remove the String() call

Dropping `.String()` will ensure that if there's a mix of redactable/non-redactable items in the recording, the error will preserve that mix.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz and @tbg)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3yuwwZ8eyxtLpu1u-I:-N3z22xNDbeELhxCQCE8:bn6reml) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a729ba469bb6ef0c4dc7829a8cdbc2349125281/pkg/sql/sem/builtins/generator_probe_ranges.go#L158)):*
> Dropping .String() will ensure that if there's a mix of redactable/non-redactable items in the recording, the error will preserve that mix.

You mean if `Recording` were to implement `redact.SafeFormatter` (which it doesn't)?

**Comment by knz** [comment]
> You mean if Recording were to implement redact.SafeFormatter (which it doesn't)?

yes

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @knz and @tbg)

___
*[`pkg/sql/sem/builtins/generator_probe_ranges.go` line 158 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-N3yuwwZ8eyxtLpu1u-I:-N3z5F9N2P0wZvkpWWoz:bqpw0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a729ba469bb6ef0c4dc7829a8cdbc2349125281/pkg/sql/sem/builtins/generator_probe_ranges.go#L158)):*
(copying your answer back inline...)

> yes

It does seem reasonable that we'll implement `SafeFormatter` on recordings in. I just spent a few minutes reminding myself how readaction for tenants works.
I'll send a separate PR to change this line.

**Review by andreimatei — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76306#-:-N3z_fQd-wqFG7PcEmhG:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @erikgrinaker, @knz, and @tbg)

**Pull request merged**
