### PR TITLE
sql: add check constraint 

### LINKED ISSUE #2474: sql: support CHECK(expr) constraints
A `CHECK` constraint is an expression that is evaluated when a row is inserted or updated and must return `not-FALSE` in order for the check to pass. This enhancement should primarily be a matter of bookkeeping.

### PR DESCRIPTION
**Pull request by seiflotfy**
This is forked and fixed from https://github.com/cockroachdb/cockroach/pull/5010

This partly fixes #2474 As I commented in the source code, there are still more TODOs such as more corner case checking, table constraint, update hook etc. But I think this is a good start as to see if I'm in the right direction. :)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6044)

### CODE REVIEW

**Comment by petermattis** [comment]
Thanks for picking this up.

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 202 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGF2r03kU7P9MG45_o:-KFGF2r1tgCKFGDY3i3V:366023168) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L202)):*
`s/constraints/constraints./g`

---

*[sql/insert.go, line 209 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGLIQTUlx2BVTnG3e:-KFGGLIQTUlx2BVTnG3f:1023025890) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L209)):*
I think this can be pulled out of the `rows.Next()` loop. That is, you can resolve the qualified names (qnames) once for the insert and then just populate the `qvals` map and evaluate the expression for each row. 

---

*[sql/insert.go, line 213 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGFqfQ_-1Ub3mNMPQm:-KFGFqfQ_-1Ub3mNMPQn:-1711678374) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L213)):*
`s/qvals/qvals./g`

---

*[sql/insert.go, line 218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHcNZoVex4_5CZN0h:-KFGHcNZoVex4_5CZN0i:1132550042) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L218)):*
Let's add a little more detail: `failed to to find column %d in row`

---

*[sql/insert.go, line 229 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHm80t21zShn_58jb:-KFGHm81_B453NlF1f8s:24193996) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L229)):*
`s/Failed/failed/g` error messages are usually not capitalized.

---

*[sql/insert.go, line 469 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGpJv6LcDCjokg6St:-KFGGpJv6LcDCjokg6Su:1946339803) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L469)):*
If you changed this to `numCheck` then you could initialize `checkExprs` to the correct size below: `checkExprs := make([]parser.Expr, 0, numCheck)`

---

*[sql/testdata/check_constraints, line 31 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHAFqf2yoJ6QYcNXO:-KFGHAFriDS2GD4_D710:260434098) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/testdata/check_constraints#L31)):*
Add a test case where a `CHECK` constraint references a column and then the column is renamed. This should cause  subsequent`INSERTs` to fail. On column rename we'll need to rewrite the `CHECK` expressions. That should be handled in a follow-on PR.

Also add a test case where a `CHECK` constraint references a non-existent column. This should ideally fail on table creation, but currently won't. Again, this is fine to fix in a follow-on PR. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-:-KFGIJF5GMeKFlxjk5F5:-1296231239)*

**Comment by seiflotfy** [comment]
*[sql/insert.go, line 209 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGLIQTUlx2BVTnG3e:-KFOI_LJ7SWKyJBDcn3n:1639862611) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L209)):*
Not really confident on how to do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by seiflotfy** [comment]
*[sql/insert.go, line 209 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGLIQTUlx2BVTnG3e:-KFOI_LJ7SWKyJBDcn3n:1639862611) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L209)):*
Not really confident on how to do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by petermattis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 209 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGLIQTUlx2BVTnG3e:-KFOuL1t9KlYcPkmKeRB:-634339314) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L209)):*
There are several things going on here that are inefficient. For one, qualified-name resolution (`resolveQNames`) only needs to be performed once for each check-expr in this method as the expressions are not changing. Second, we don't need a separate `qvals` map for each expression. Lastly, we don't need to populate the `qvals` map separately for each expression. My suggestion is to hoist the `resolveQNames` call out of the loop. Something like:

```
// Prepare the check expressions.
var qvals qvalMap
if len(checkExprs) > 0 {
  qvals = make(qvalMap)
   table := tableInfo {
     columns: makeResultColumns(tableDesc.Columns)
   }
  for i := range checkExprs {
    expr, err := resolveQNames(checkExprs[i], &table, qvals, &p.qnameVisitor)
    if err != nil {
      return nil, roachpb.NewUError(err)
    }
    checkExprs[i] = expr
  }
}

for rows.Next() {
  ...
  if len(checkExprs) > 0 {
    // Populate the qvals map for this row.
    for ref, qval := range qvals {
      ...
    }
    for _, expr := range checkExprs {
      if d, err := expr.Eval(p.evalCtx); err != nil {
        ...
      }
      ...
    }
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by seiflotfy** [comment]
*[sql/insert.go, line 209 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGLIQTUlx2BVTnG3e:-KFP2nRgHW3DuMIXQpHM:1055926046) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L209)):*
Thanks works like charm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by seiflotfy** [comment]
*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by petermattis** [comment]
:lgtm:

During code reviews we usually acknowledge each of the comments reviewers provide with a simple `Done` response. If you're using reviewable there is even a little button for this.

---

Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/testdata/check_constraints, line 30 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFP9kiFyypZVYZSWKii:-KFP9kiGq0W4NItSw4DV:-1812398670) ([raw file](https://github.com/cockroachdb/cockroach/blob/e04fb8bcf2aadb28c525fd3060a78ba4c40a2a7e/sql/testdata/check_constraints#L30)):*
Can the error message include the failing expression? Fine to do in a follow-on PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-:-KFPA-9nx-UCHV_CRVuq:-135225549)*

**Comment by petermattis** [comment]
@seiflotfy Looks like this needs to be rebased before it can be merged.

**Comment by seiflotfy** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 202 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGF2r03kU7P9MG45_o:-KFPD9LVeFn43hGsLu91:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L202)):*
Done.

---

*[sql/insert.go, line 213 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGFqfQ_-1Ub3mNMPQm:-KFPD8uN4eKdKNWyrt_p:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L213)):*
Done.

---

*[sql/insert.go, line 218 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHcNZoVex4_5CZN0h:-KFPD8PuvycyyjfVUoW6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L218)):*
Done.

---

*[sql/insert.go, line 229 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHm80t21zShn_58jb:-KFPD861X1KEPJsz3sD5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L229)):*
Done.

---

*[sql/insert.go, line 469 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGGpJv6LcDCjokg6St:-KFPD8ag4Ie4o04kWefQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/insert.go#L469)):*
Done.

---

*[sql/testdata/check_constraints, line 31 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFGHAFqf2yoJ6QYcNXO:-KFPD6dOJ2N_QFwk6YGz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff0c2acc12a9f1f2a1d287ce1cd857c946c6e857/sql/testdata/check_constraints#L31)):*
Done.

---

*[sql/testdata/check_constraints, line 30 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-KFP9kiFyypZVYZSWKii:-KFPD60j9QfmPPTdjSq9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/e04fb8bcf2aadb28c525fd3060a78ba4c40a2a7e/sql/testdata/check_constraints#L30)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by petermattis** [comment]
Reviewed 3 of 10 files at r1, 1 of 1 files at r3, 4 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6044#-:-KFPH3J68QF36TW8-91j:1417088721)*

**Comment by petermattis** [comment]
@seiflotfy Do you mind squashing the commits as well? Multi-commit PRs are ok, but each commit should be a good state (tests pass, etc) and not the side-effect of the development/code-review process.

**Comment by seiflotfy** [comment]
Should I squash all 8 commits in 1?

**Comment by seiflotfy** [comment]
Done

**Comment by petermattis** [comment]
Yep, 1 commit is good. Just waiting on CI to finish.

**Pull request merged**
