### PR TITLE
cli/demo: simplify the initialization code

### PR DESCRIPTION
**Pull request by knz**
This commit reduces the number of conditionals and makes the init
synchronization easier to read.

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
Looks like the tests are broken, I think it's because of the close/double read of startCh

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-:-LvD3jk-A-8rHdZkKhMw:b5zjmx1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/cli/demo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2F5Q3LUI3EfjZ6vk:-LvD2F5Q3LUI3EfjZ6vl:btommq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L353)):*
> ```Go
> 		// readyCh is closed when the server is ready to accept connections.
> 		readyCh chan struct{}
> 		// When latency simulation is requested.
> ```

up to you nit: `contextTestingKnobs is set when latency simulation is requested`
___
*[pkg/cli/demo.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2wXd6MfGzccLZk_d:-LvD2wXeB5ph_SKQRJTW:b4f0fd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L486)):*
> ```Go
> 		case <-servers[i].readyCh:
> 			// Done waiting for readiness.
> 		case err := <-servers[i].startCh:
> ```

should this be `err, ok := <-servers[i].startCh`?  also looks like this can be read twice, despite only being sent once?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/demo.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2wXd6MfGzccLZk_d:-LvD4kxt0EToDATzw5L9:b-safltq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L486)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

should this be `err, ok := <-servers[i].startCh`?  also looks like this can be read twice, despite only being sent once?
</blockquote></details>

ah no i see - you're relying on it being pciked up before. not sure what the CI errors are.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/demo.go, line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD5Jsf2eadG5z-I61x:-LvD5Jsf2eadG5z-I61y:b2k8z72) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L422)):*
> ```Go
> 			// Start() completed early, with an error. CombineErrors()
> 			// returns the existing error if the other argument is `nil`.
> 			log.Errorf(ctx, "demo node at i = %d failed: %v", err)
> ```

i think this is missing a `if err != nil` if the rpcAddrReadyCh loses the race.
___
*[pkg/cli/demo.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2wXd6MfGzccLZk_d:-LvD5Q5PCYGK-KCxPfGY:bwr8myy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L486)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah no i see - you're relying on it being pciked up before. not sure what the CI errors are.
</blockquote></details>

i think this is missing a `if err != nil` though? `Start` can send down `nil` right?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cli/demo.go, line 353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2F5Q3LUI3EfjZ6vk:-LvG1y1F0TFHZfOHX51l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L353)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

up to you nit: `contextTestingKnobs is set when latency simulation is requested`
</blockquote></details>

Done.
___
*[pkg/cli/demo.go, line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD5Jsf2eadG5z-I61x:-LvG1-xGAO3bV8raG9D4:bglzaq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L422)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think this is missing a `if err != nil` if the rpcAddrReadyCh loses the race.
</blockquote></details>

Oh right. woops.
___
*[pkg/cli/demo.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42929#-LvD2wXd6MfGzccLZk_d:-LvG2Ton4rR0NmEShTxM:bdji9rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd5af4e3ba7854a98d12a97f6d05197c54255ca/pkg/cli/demo.go#L486)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think this is missing a `if err != nil` though? `Start` can send down `nil` right?
</blockquote></details>

Indeed. woops again.

**Comment by knz** [comment]
Based on my testing I have achieved the following:

- the code is indeed simplified and the initial start waits on node readiness properly
- there was a node ID <-> slice index that was causing the TCL tests to fail, I fixed that
- however, there is still a snappy-related error (#42634) upon shutting down nodes.

For this latest failure I am still tracking this down and I believe the problem a race in the RPC `Drain` call by `doShutdown`. Something along these lines:

1. the _client_ part of the demo session initiates the Drain call
2. server-side, the call succeeds, but the shutdown process immediately causes the RPC session between the client and server to be interrupted
3. the _client_ grpc code sees the interruption and re-tries the call internally.
4. by that time, the RPC server has stopped its RPC listener but the TCP listen socket is still active, and so the client receives a protocol error.

I am not yet 100% sure of this, but one possible way to side-step this interaction entirely is to eschew the RPC and call the API directly in-process.

(Oliver, if that indeed becomes the solution, that would be an acknowledgement that my push to use RPCs in your initial PR was mistaken.)

**Comment by knz** [comment]
We've addressed this since.

**Pull request closed without merging**
