### PR TITLE
Remove the client scan benchmarks.

### PR DESCRIPTION
**Pull request by petermattis**
These benchmarks are now uninteresting because the client is only ever
utilized via a DistSender (not an RPC sender as used by these tests) and
higher level benchmarks in the `sql` package more accurately capture the
usage we're interested in.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4102)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
Do we have any other benchmarks that could identify the SSL performance penalty?

**Comment by petermattis** [comment]
I thought the SSL performance penalty went away in Go 1.5. Regardless, we're not using either the `rpc` or `rpcs` sender in any of the code. They are only used from tests and the cli.

**Comment by tamird** [comment]
I doubt it went away completely.

LGTM

**Comment by petermattis** [comment]
True, but what are you proposing? These benchmarks are not represented of anything right now. If we want to measure the SSL overhead (e.g. at the pgwire level) we should add benchmarks that disable SSL at that level.

**Comment by tamird** [comment]
Yep, I agree. That's what I meant by 'LGTM' in the last comment.

**Pull request merged**
