### PR TITLE
crosscluster/logical: add failed row insert as json object to DLQ

### PR DESCRIPTION
**Pull request by msbutler**
This patch changes the incoming_row column in the DLQ table to a JSON type, allowing the user to query for specific column values in the DLQ.

Epic: none

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
If this approach looks reasonable, I can follow up with a test that puts random rows into the dlq

**Review by stevendanna — APPROVED** [review]
Looks pretty reasonable to me.

**Comment by msbutler** [comment]
TFTR!

bors r=stevendanna

**Comment by msbutler** [comment]
blathers backport 24.2

**Pull request merged**
