### PR TITLE
storage: prevent quiescence if Raft leadership transfer is in progress

### PR DESCRIPTION
**Pull request by petermattis**
Add TestReplicaShouldQuiesce to test both the new functionality and the
existing conditions which prevent quiescence.

See #13523

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:, though @bdarnell should take a look as well.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica.go, line 3749 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-KtEjBXjO015kRHUaGyN:-KtEjBXjO015kRHUaGyO:b10f0uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff8713c95458a31c4847246997b0f0ca713360c/pkg/storage/replica.go#L3749)):*
> ```Go
> 	if status.Commit != lastIndex {
> 		if log.V(4) {
> 			log.Infof(ctx, "not quiescing: commit (%d) != last-index (%d)",
> ```

nit while you're here: s/last-index/lastIndex/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-:-KtEjl7HHGQUhs9ozGcb:bq19wz6)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 3749 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-KtEjBXjO015kRHUaGyN:-KtHg-L3LcPV89J3TF7V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bff8713c95458a31c4847246997b0f0ca713360c/pkg/storage/replica.go#L3749)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit while you're here: s/last-index/lastIndex/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 3661 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-KtHg9JlucJjueKeLZe8:-KtHg9JlucJjueKeLZe9:btj25e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/719ea489d914f9c1ac01a747fde6cf9a1291e7d1/pkg/storage/replica.go#L3661)):*
> ```Go
> 
> type quiescer interface {
> 	Clock() *hlc.Clock
> ```

Maybe `shouldReplicaQuiesce` should take a `now hlc.Timestamp` instead of having access to a `Clock`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-:-KtHgVxsmUCzRQsB0lrL:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 3661 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202#-KtHg9JlucJjueKeLZe8:-KtHgqjfEkUtdceLq_P0:b7myzce) ([raw file](https://github.com/cockroachdb/cockroach/blob/719ea489d914f9c1ac01a747fde6cf9a1291e7d1/pkg/storage/replica.go#L3661)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe `shouldReplicaQuiesce` should take a `now hlc.Timestamp` instead of having access to a `Clock`.
</blockquote></details>

I was anxious about there being too many arguments to that method. Let me see what that looks like.

Ok. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18202)*

**Pull request merged**
