### PR TITLE
server: add session_id to CommonConnectionDetails

### LINKED ISSUE #104984: server: add session_id to CommonConnectionDetails
Add `session_id` to `CommonConnectionDetails` for observability.

`CommonConnectionDetails` appears in these log events:
- `ClientConnectionStart`
- `ClientConnectionEnd`
- `ClientSessionEnd`
- `ClientAuthenticationFailed`
- `ClientAuthenticationOk`
- `ClientAuthenticationInfo`

The `session_id` can be retrieved by the client via `SHOW session_Id;` so it can be traced from client to server without relying on client/server hostname:port which can be altered by proxies.

Jira issue: CRDB-28810

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #104984

Add `session_id` to `CommonConnectionDetails` for observability.

`CommonConnectionDetails` appears in these log events:
- `ClientConnectionStart`
- `ClientConnectionEnd`
- `ClientSessionEnd`
- `ClientAuthenticationFailed`
- `ClientAuthenticationOk`
- `ClientAuthenticationInfo`

The `session_id` can be retrieved by the client via `SHOW session_Id;` so it can be traced from client to server without relying on client/server hostname:port which can be altered by proxies.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is a great cleanup. i just had minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-:-NY4DJcH2mpE_o-sIVn8:baxtwfa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @mgartner)

___
*[`pkg/sql/pgwire/server.go` line 827 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY47uHzCozQuUtDZMsa:-NY47uHzCozQuUtDZMsb:b-qwmecp) ([raw file](https://github.com/cockroachdb/cockroach/blob/23fea0d4292b585508c240fd95e4c6ecd3ae4c8b/pkg/sql/pgwire/server.go#L827)):*
> ```Go
> 
> 	ctx, cancelConn := context.WithCancel(ctx)
> 	defer cancelConn()
> ```

to reduce the number of parameters, can `ctx, cancelConn := context.WithCancel(ctx)` be moved to be inside of `newConn`. then this could look like:

```
	conn := server.newConn(
		ctx,
		netConn,
		sql.SessionArgs{ConnResultsBufferSize: 16 << 10},
		timeutil.Now(),
	)
	defer conn.cancelConn()
```

or to be even more explicit, `newConn` could return a `cleanupConn` function that all callers must call.
___
*[`pkg/sql/pgwire/server.go` line 885 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY4B1m430alcP_g19qJ:-NY4B1m430alcP_g19qK:bedv7kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23fea0d4292b585508c240fd95e4c6ecd3ae4c8b/pkg/sql/pgwire/server.go#L885)):*
> ```Go
> 
> 	var sentDrainSignal bool
> 	rtc.checkExitConds = func() error {
> ```

why does `rtc.CheckExitConds` need to be set here, rather than when `rtc` is declared?
___
*[`pkg/util/log/eventpb/session_events.proto` line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY4BoPp8Lw2Zp-5CZh6:-NY4BoPp8Lw2Zp-5CZh7:b6ii7q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294997ae2bb24f03d5cace5053d88d81f855dbf/pkg/util/log/eventpb/session_events.proto#L48)):*
> ```proto
>   string remote_address = 3 [(gogoproto.jsontag) = ",omitempty"];
>   // The connection's hex encoded session id.
>   string session_id = 4 [(gogoproto.customname) = "SessionID", (gogoproto.jsontag) = ",omitempty"];
> ```

i think you need to add `(gogoproto.moretags) = "redact:\"nonsensitive\""]` to all the places where you declare the session ID. otherwise, we won't see the ID in splunk

while you're at it, i think we should also mark the ID type as safe from redaction too

```
diff --git a/pkg/sql/clusterunique/id.go b/pkg/sql/clusterunique/id.go
index 8e3a45b4a06..d2b8b109622 100644
--- a/pkg/sql/clusterunique/id.go
+++ b/pkg/sql/clusterunique/id.go
@@ -18,6 +18,7 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/util/hlc"
 	"github.com/cockroachdb/cockroach/pkg/util/uint128"
 	"github.com/cockroachdb/errors"
+	"github.com/cockroachdb/redact"
 )
 
 // ID represents an identifier that is guaranteed to be unique across
@@ -27,6 +28,11 @@ type ID struct {
 	uint128.Uint128
 }
 
+var _ redact.SafeValue = ID{}
+
+// SafeValue implements the redact.SafeValue interface.
+func (ID) SafeValue() {}
+
 // GenerateID takes a timestamp and SQLInstanceID, and generates a
 // ID.
 func GenerateID(timestamp hlc.Timestamp, instID base.SQLInstanceID) ID {
```

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/pgwire/server.go` line 827 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY47uHzCozQuUtDZMsa:-NY4ISnM6Xevn6hLpveV:brtv55o) ([raw file](https://github.com/cockroachdb/cockroach/blob/23fea0d4292b585508c240fd95e4c6ecd3ae4c8b/pkg/sql/pgwire/server.go#L827)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to reduce the number of parameters, can `ctx, cancelConn := context.WithCancel(ctx)` be moved to be inside of `newConn`. then this could look like:

```
	conn := server.newConn(
		ctx,
		netConn,
		sql.SessionArgs{ConnResultsBufferSize: 16 << 10},
		timeutil.Now(),
	)
	defer conn.cancelConn()
```

or to be even more explicit, `newConn` could return a `cleanupConn` function that all callers must call.
</blockquote></details>

I tried this, but it requires further investigation. Some of the usages of `ctx` later on need to be affected by `cancelConn` also, but I did not figure out which ones (it causes tests to hang).

I think I can address this in another PR because the server/connection code can be further cleaned up to follow a similar pattern:
```
a := CreateA()
defer a.Close()
useA(a)
```
vs what we have now:
```
a := CreateA()
useA(a) // a gets closed somewhere deep in the stack, but it is hard to trace
```
___
*[`pkg/sql/pgwire/server.go` line 885 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY4B1m430alcP_g19qJ:-NY4JYzA2s8EA06hg6JQ:b-vi2bm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/23fea0d4292b585508c240fd95e4c6ecd3ae4c8b/pkg/sql/pgwire/server.go#L885)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why does `rtc.CheckExitConds` need to be set here, rather than when `rtc` is declared?
</blockquote></details>

It is a chicken an egg problem: `conn` references `rtc`, but `rtc.checkExitConds` references `conn` (`c.stmtBuf.Push`).
___
*[`pkg/util/log/eventpb/session_events.proto` line 48 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY4BoPp8Lw2Zp-5CZh6:-NY4T9a7-Siza4PxDqqC:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294997ae2bb24f03d5cace5053d88d81f855dbf/pkg/util/log/eventpb/session_events.proto#L48)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think you need to add `(gogoproto.moretags) = "redact:\"nonsensitive\""]` to all the places where you declare the session ID. otherwise, we won't see the ID in splunk

while you're at it, i think we should also mark the ID type as safe from redaction too

```
diff --git a/pkg/sql/clusterunique/id.go b/pkg/sql/clusterunique/id.go
index 8e3a45b4a06..d2b8b109622 100644
--- a/pkg/sql/clusterunique/id.go
+++ b/pkg/sql/clusterunique/id.go
@@ -18,6 +18,7 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/util/hlc"
 	"github.com/cockroachdb/cockroach/pkg/util/uint128"
 	"github.com/cockroachdb/errors"
+	"github.com/cockroachdb/redact"
 )
 
 // ID represents an identifier that is guaranteed to be unique across
@@ -27,6 +28,11 @@ type ID struct {
 	uint128.Uint128
 }
 
+var _ redact.SafeValue = ID{}
+
+// SafeValue implements the redact.SafeValue interface.
+func (ID) SafeValue() {}
+
 // GenerateID takes a timestamp and SQLInstanceID, and generates a
 // ID.
 func GenerateID(timestamp hlc.Timestamp, instID base.SQLInstanceID) ID {
```

</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104906)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @mgartner)

___
*[`pkg/sql/pgwire/server.go` line 827 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/104906#-NY47uHzCozQuUtDZMsa:-NY4u8VB7ID4dsgQohja:bappyjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/23fea0d4292b585508c240fd95e4c6ecd3ae4c8b/pkg/sql/pgwire/server.go#L827)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I tried this, but it requires further investigation. Some of the usages of `ctx` later on need to be affected by `cancelConn` also, but I did not figure out which ones (it causes tests to hang).

I think I can address this in another PR because the server/connection code can be further cleaned up to follow a similar pattern:
```
a := CreateA()
defer a.Close()
useA(a)
```
vs what we have now:
```
a := CreateA()
useA(a) // a gets closed somewhere deep in the stack, but it is hard to trace
```
</blockquote></details>

oh right, i see what you mean. the new `ctx` is also passed into s.serveImpl

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
