### PR TITLE
opt: add test to verify AggregateIgnoresDuplicates

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds a tests that attempts to prove that
`opt.AggregateIgnoresDuplicates` only returns true for aggregate
functions that actually ignore duplicates. This test is meant to catch
incorrectly marking new operators as ignoring duplicates when they don't
in fact ignore them. This test was motivated by #111556.

Epic: None

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is from #112729.

**Review by DrewKimball — APPROVED** [review]
:lgtm: This is great!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-:-NhEA99W7jQFnkpTJa7C:b48xzcn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
Very nice! :lgtm: I have a bunch of nits for your consideration, but please feel to ignore them :) (perhaps I'm more nit-picky this morning than usual lol)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-:-NhIA8L38DT9eAGH6a-a:bkzpqtf)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/main_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI8smVAbjUcheUtzSm:-NhI8smVAbjUcheUtzSn:b-whozy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/main_test.go#L29)):*
> ```Go
> 	randutil.SeedForTests()
> 	serverutils.InitTestServerFactory(server.TestServerFactory)
> 	serverutils.InitTestClusterFactory(testcluster.TestClusterFactory)
> ```

nit: I think we're only using test server, so we don't need to initialize the cluster factory.
___
*[`pkg/sql/opt/operator_agg_test.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI94CtBjfdSB9Na18k:-NhI94CtBjfdSB9Na18l:b-7tpras) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L38)):*
> ```Go
> // For each test case's operator and type, we choose a random datum of that type
> // and aggregate the datum a varying number of times. The result of each
> // aggregation is inserted into a table. The table after all the aggregations
> ```

nit: probably `s/The table after all/After all/`.
___
*[`pkg/sql/opt/operator_agg_test.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI9guT37_7qAE6tf_-:-NhI9guUCadTDnJ3A_an:budz8mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L155)):*
> ```Go
> 
> 			// Generate a random datum.
> 			datum := randgen.RandDatum(rng, tc.typ, false /* nullOk */)
> ```

`false /* nullOk */` makes me think whether we should extend this test to also cover "aggregate ignores nulls" logic. WDYT?
___
*[`pkg/sql/opt/operator_agg_test.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhIA-3mETi3InxJ3-o2:-NhIA-3mETi3InxJ3-o3:bawm9zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L168)):*
> ```Go
> 					"INSERT INTO results SELECT %s(d) FROM (SELECT %s::%s FROM generate_series(1, %d)) g(d)",
> 					sqlOp, datumStr, tc.typ.SQLString(), numInputs)
> 				fmt.Println(query)
> ```

nit: `t.Logf` might preferable to `fmt.Println`.
___
*[`pkg/sql/opt/operator_agg_test.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI9J3mET6tTyVMeIGm:-NhI9J3mET6tTyVMeIGn:b-8mg24) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L175)):*
> ```Go
> 		// Ensure that there is only one distinct result in the results
> 		// table.
> 		rows := tDB.Query(t, "SELECT count(*) FROM (SELECT r FROM results GROUP BY r)")
> ```

nit: `SELECT count(DISTINCT r) FROM results` seems more intuitive for this, no?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112775)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/operator_agg_test.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI9J3mET6tTyVMeIGm:-NhII1Gn6H00c-38oXUA:buj47pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L175)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `SELECT count(DISTINCT r) FROM results` seems more intuitive for this, no?
</blockquote></details>

I guess then we'd not use the aggregate logic?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112775)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/main_test.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI8smVAbjUcheUtzSm:-Ni17lVq4tx7EKhTFAcW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/main_test.go#L29)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we're only using test server, so we don't need to initialize the cluster factory.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/operator_agg_test.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI94CtBjfdSB9Na18k:-Ni17vI7-YRtQQfI8sUm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L38)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably `s/The table after all/After all/`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/operator_agg_test.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI9guT37_7qAE6tf_-:-Ni180QM7OegcjVp6pAv:bmkot4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`false /* nullOk */` makes me think whether we should extend this test to also cover "aggregate ignores nulls" logic. WDYT?
</blockquote></details>

Yes we can. I've left a TODO for now.
___
*[`pkg/sql/opt/operator_agg_test.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhIA-3mETi3InxJ3-o2:-Ni18D0mB-U-PgR5axhC:b-moi6l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L168)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `t.Logf` might preferable to `fmt.Println`.
</blockquote></details>

Good catch. This was left-over from debugging. Removed it.
___
*[`pkg/sql/opt/operator_agg_test.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-NhI9J3mET6tTyVMeIGm:-Ni18I316qrlp6GeoHLC:b-4pxih) ([raw file](https://github.com/cockroachdb/cockroach/blob/8abeb27c907971d6502565af269e74f4c5fd3e0e/pkg/sql/opt/operator_agg_test.go#L175)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I guess then we'd not use the aggregate logic?
</blockquote></details>

`count(DISTINCT ...)` does not consider `NULL`s to be duplicates with each other, whild `GROUP BY` does. Since some of the aggregates can result in `NULL`, I've used `GROUP BY`.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112775#-:-Ni195xR6Bf1RlcF1mp0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Pull request merged**
