### PR TITLE
kvserver: run leader leases with TestUninitializedReplicaRemainsQuiesced

### PR DESCRIPTION
**Pull request by arulajmani**
This patch changes TestUninitializedReplicaRemainsQuiesced to run with all lease types, and extends the test to ensure ranges using leader leases, like expiration based leases, do not quiesce. While here, also extend the test.

References https://github.com/cockroachdb/cockroach/issues/133763

Release note: None

### CODE REVIEW

**Review by iskettaneh — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136335)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136335#-OCnVZdI7erEnNkY09lP:-OCnVZdI7erEnNkY09lQ:blnf4wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a6d9c28d597c2dadbd1140b5096bcc65ccd6ff/pkg/kv/kvserver/replica_store_liveness.go#L38)):*
> ```Go
> 	// TODO(nvanbenschoten): make this a metamorphic constant once raft leader
> 	// fortification and leader leases are sufficiently stable.
> 	envutil.EnvOrDefaultFloat64("COCKROACH_LEADER_FORTIFICATION_FRACTION_ENABLED", 1.0),
> ```

Is this intended?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136335)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136335#-OCnVZdI7erEnNkY09lP:-OCnhSw_CcbFTPiqvTQL:bbmxefn) ([raw file](https://github.com/cockroachdb/cockroach/blob/33a6d9c28d597c2dadbd1140b5096bcc65ccd6ff/pkg/kv/kvserver/replica_store_liveness.go#L38)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Is this intended?
</blockquote></details>

Nup, reverted.

**Review by iskettaneh — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136335)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by iskettaneh — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136335#-:-OCo_hD15D8BnKXCgdjZ:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by iskettaneh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136335#-:-OCo_j5NEu12xm2X7kEO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks!

bors r=iskettaneh

**Pull request merged**
