### PR TITLE
kv: fix RangeDescriptorCache eviction with meta2 splits

### PR DESCRIPTION
**Pull request by nvb**
Related to #18578.

Previously, it was possible for meta2 splits to cause incorrect meta2
range descriptors to be evicted from the `RangeDescriptorCache`. The
reason for this is that `evictCachedRangeDescriptor` would evict the
`RangeMetaKey` of the lookup key, instead of the `EndKey` of the
user-space descriptor. The comment below explains this in more detail:

> Evicting 'meta(descKey)' instead of 'meta(cachedDesc.EndKey)' could be
> incorrect here because it could result in us evicting the wrong meta2
> descriptor. Imagine that descriptors are in the configuration:
>
> meta2 descs:  [/meta2/a,/meta2/m),  [/meta2/m,/meta2/z)
> user  descs:  [a,f),   [f,k),   [k,p),   [p,u),   [u,z)
>
> A lookup for the key 'l' would return the third user-space descriptor
> [k,p), after a continuation lookup. This descriptor is stored on the
> second meta2 range because its end key is p, which maps to /meta2/p.
> If we later want to evict this user-space descriptor, we also want to
> evict the meta2 descriptor for the range that contains it. However,
> if we naively evicted meta('l'), we'd end up evicting the first meta2
> descriptor. Instead, we want to evict meta('p'), since 'p' is the end
> key of the user-space descriptor.

First four commits are from #18706. Can be ignored.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
While making this change I had a realization that I hope is wrong. I think that
we'll be able to have 3 levels of descriptor indirection for the last range in the
system once we allow meta2 splits again. To make that concrete, take for
example:
```
 r1: [/min,/meta2/)
 r2: [/meta2/,/meta2/m)
 r3: [/meta2/m,/metaMax) <- can't split at meta2max
 r4: [/metaMax,keymax)
```
r4's desc lives on r3, r3's desc lives on r2, r2's desc
lives on r1. Remember `meta(MetaMax) -> /meta2/metaMaxByte`.
The problem here is that the `EndKey` of a range that contains meta2
descriptors doesn't need to be a meta2 key itself, meaning that `RangeMetaKey`
will give a meta2 key address. Consequences of this include that evicting
`keymax` will evict two meta2 descriptors, but there are a lot more.

Is this ok? Do we expect to have meta2 descriptors stored in meta2 ranges?
For reference, I think the fundamental issue here was also the cause of https://github.com/cockroachdb/cockroach/pull/1206.
Life would be so much easier if we stored meta keys at `meta(desc.StartKey)`.

**Comment by petermattis** [comment]
I was recently trying to wrap my head around the cause of #1206. I'm not seeing anything wrong with your logic, but I've just spent the day outside so perhaps my brain in sun baked.

**Comment by bdarnell** [comment]
> Do we expect to have meta2 descriptors stored in meta2 ranges?

No, we don't. Meta1 lookups are supposed to be sufficient for finding all meta2 entries. But while it's surprising, I'm not immediately seeing any severe consequences here (I'm probably just missing things). It helps that with our current automatic split policies, the last range in the system is always empty. 

Is this unique to splits at exactly `/metaMax`? Could we avoid this by disallowing splits at that point too?

**Comment by nvanbenschoten** [comment]
> Is this unique to splits at exactly /metaMax

No, this will happen if there is a split anywhere between (`/meta2max`,`/metaMax`], which there always has to be. This is because the last range descriptor in the system will always be stored at exactly `/meta2max` (`RangeMetaKey(KeyMax)`), which means that the smallest key that the last meta2 range can end at while still containing this descriptor is `/meta2max.Next()`.

**Comment by nvanbenschoten** [comment]
Actually, I might be wrong about that. Ending meta2 ranges at `Meta2KeyMax.Next()` would also avoid this issue.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/kv/range_cache.go, line 471 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-KuorOyJrgqienDQZB4I:-KuorOyJrgqienDQZB4J:b-80svrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L471)):*
> ```Go
> 	}
> 
> 	for {
> ```

It's been a long time since I've looked at this code, but this seems nuts. Evicting the meta range descriptors is expensive and we shouldn't do it until we have evidence that they're out of date. 

Evicting the meta descriptors is currently tricky because we do inconsistent reads for range lookups, which could go to arbitrarily stale replicas. But we don't need the read-from-any-replica semantics of inconsistent reads (do we?), we just need to be able to look behind pending intents. I think we should probably stop using the inconsistent mode for range lookups and instead use a flag specific to RangeLookupRequest that controls how it handles intents. Then I think we'd be able to handle evictions one meta level at a time instead of eagerly evicting multiple levels because we're not sure where we got bad information. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-:-KuowFLaIDTx8rwL0zla:bnfp4nl)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/kv/range_cache.go, line 452 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-KutaA1lxDFeL5pBgJWj:-KutaA1lxDFeL5pBgJWk:b-yexhlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L452)):*
> ```Go
> }
> 
> // evictCachedRangeDescriptorLocked is like evictCachedRangeDescriptor, but it
> ```

Since you're polishing up comments, I think it'd be useful if you gave a little example for `inclusive` here (assuming you eat another CI anyways).

---

*[pkg/kv/range_cache.go, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-Kut_n11Lf_RIhxYUEn8:-Kut_n11Lf_RIhxYUEn9:b-ydaei4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L458)):*
> ```Go
> ) error {
> 	cachedDesc, entry, err := rdc.getCachedRangeDescriptorLocked(descKey, inclusive)
> 	if err != nil || cachedDesc == nil {
> ```

Didn't think we'd ever cache a `nil` `cachedDesc`. How does that happen?

---

*[pkg/kv/range_cache.go, line 471 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-KuorOyJrgqienDQZB4I:-KutaWUCGO4aKq4GTBSI:b-baw0o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L471)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's been a long time since I've looked at this code, but this seems nuts. Evicting the meta range descriptors is expensive and we shouldn't do it until we have evidence that they're out of date. 

Evicting the meta descriptors is currently tricky because we do inconsistent reads for range lookups, which could go to arbitrarily stale replicas. But we don't need the read-from-any-replica semantics of inconsistent reads (do we?), we just need to be able to look behind pending intents. I think we should probably stop using the inconsistent mode for range lookups and instead use a flag specific to RangeLookupRequest that controls how it handles intents. Then I think we'd be able to handle evictions one meta level at a time instead of eagerly evicting multiple levels because we're not sure where we got bad information. 
</blockquote></details>

I agree, and I can't remember there being a strong reason to evict unconditionally.

The inconsistent reads might've been premature optimization. Would be nice to see them go, especially given how unpredictable they are. They could be a good fallback for the case of unavailable meta ranges (to lessen the impact on the cluster), but let's see if that's ever necessary.

---

*[pkg/kv/range_cache.go, line 510 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-Kuta3P9Wn_cRrR8iqmm:-Kuta3P9Wn_cRrR8iqmn:bjxbegk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L510)):*
> ```Go
> 		}
> 
> 		cachedDesc, entry, err = rdc.getCachedRangeDescriptorLocked(descKey, false)
> ```

optio-nit: `false /* !inclusive */`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-:-Kutb3fJUqGxtCl0sFni:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kv/range_cache.go, line 452 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-KutaA1lxDFeL5pBgJWj:-KvYJ0wvY2_ITDZioI0q:bh7o5gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L452)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Since you're polishing up comments, I think it'd be useful if you gave a little example for `inclusive` here (assuming you eat another CI anyways).
</blockquote></details>

Added a second commit that switches from the term `inclusive` in this package to `inverted`. Added a comment.

---

*[pkg/kv/range_cache.go, line 458 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-Kut_n11Lf_RIhxYUEn8:-KvYIDYyGfslglJpKy9h:b-97ogdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L458)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Didn't think we'd ever cache a `nil` `cachedDesc`. How does that happen?
</blockquote></details>

We won't cache a `nil` descriptor, but `getCachedRangeDescriptorLocked` [returns `nil`](https://github.com/cockroachdb/cockroach/blob/a07fe20c2bb29210a446bafd6a942b258ad9e4db/pkg/kv/range_cache.go#L527) if it doesn't find a descriptor for the desired key (for instance, because of an eviction).

---

*[pkg/kv/range_cache.go, line 471 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-KuorOyJrgqienDQZB4I:-KvYIdZir-kd3ikeMvjM:b-88z01c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L471)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I agree, and I can't remember there being a strong reason to evict unconditionally.

The inconsistent reads might've been premature optimization. Would be nice to see them go, especially given how unpredictable they are. They could be a good fallback for the case of unavailable meta ranges (to lessen the impact on the cluster), but let's see if that's ever necessary.
</blockquote></details>

I opened #18988 to follow this.

---

*[pkg/kv/range_cache.go, line 510 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709#-Kuta3P9Wn_cRrR8iqmm:-KvYIwiKLaeKJ6w-MTH4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cebbf3a2c7e5c66329562de956295ceca6e7da0/pkg/kv/range_cache.go#L510)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

optio-nit: `false /* !inclusive */`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18709)*

**Pull request merged**
