### PR TITLE
all: make all comments for false constants match the style guide

### PR DESCRIPTION
**Pull request by andreimatei**
Changing all the f(false /* !foo */) to f(false /* foo */). The inline
comment is supposed to be the name of the argument.

### CODE REVIEW

**Comment by andreimatei** [comment]
I'll cherry-pick this into 1.1 so it doesn't create future cherry-pick pains.

**Comment by BramGruneir** [comment]
ugg, reviewable hates this PR!  Have to click between each file.

:lgtm: Thanks for doing this clean up!

---

Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19528#-:-KxJ99FQWyhu4XEttT80:b98rfha)*

**Comment by bdarnell** [comment]
-1 on cherry-picking this to a release branch. Individual cherry-picks should update things to the new style when conflicts occur.

**Comment by andreimatei** [comment]
@bdarnell but why tho? Not that I care too much, but this time the cherry-pick really seems pure upside, zero downside - since the PR only touches comments. Are you making a policy-enforcement comment, or a more targeted comment?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19528#-:-KxJCAhcHLVnuFlqvPCL:b9i1rwn)*

**Comment by nvanbenschoten** [comment]
:lgtm_strong: but I agree with Ben.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19528#-:-KxJClpxJJwqoCnO9PgG:bb5dhj4)*

**Comment by bdarnell** [comment]
The upside is small because most cherry-picks won't experience a conflict, and for those that do the fix is trivial. The downside is that it's unnecessary churn in the release branch.

**Pull request merged**
