### PR TITLE
kv: prevent dist sender from processing past a specified span of keys

### LINKED ISSUE #12603: storage: span and descriptor do not overlap
sha: 789f7499a1e02b11240e58bd5d1232c7827c2943

I'm playing with scalability, this time running photos against a pre-split tables, then running photos on each node locally (using https://github.com/cockroachdb/examples-go/pull/90)
I'm getting the following error:
```
I161229 23:11:40.269828 9 user.go:158  failed to run create photo op for 2598: pq: span and descriptor's range do not overlap: {/Table/52/2/2598/2016-12-29T23:11:40.046354Z/0 /Table/52/1/"Xc]ﻕ\xd4ḤKW\u007f\xc9\xe62|"} vs range_id:1918 start_key:"\274\211\022\377\371\324\242\006yJF\260\267\336-\210s\226;\000\001" end_key:"\275" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4
```

eg, from `cockroach-sky-0001.eastus2.cloudapp.azure.com`'s `logs/photos.stderr`, but other nodes show this as well.

@nvanbenschoten, I see a todo with your name in `data.go`.
```
// Intersect returns the intersection of the current span and the
// descriptor's range. Returns an error if the span and the
// descriptor's range do not overlap.
// TODO(nvanbenschoten) Investigate why this returns an endKey when
// rs.EndKey is nil. This gives the method unexpected behavior.
func (rs RSpan) Intersect(desc *RangeDescriptor) (RSpan, error) {
  if !rs.Key.Less(desc.EndKey) || !desc.StartKey.Less(rs.EndKey) {
    return rs, errors.Errorf("span and descriptor's range do not overlap: %s vs %s", rs, desc)
  }
```

### PR DESCRIPTION
**Pull request by spencerkimball**
The dist sender's `divideAndSendBatchToRanges` method can be reentrant
if ranges are split or merged concurrently. When this happens, the new span
provided to `divideAndSendBatchToRanges` may be a sub-span of the original.
However, because the requests in the original batch remain the same, calls
to `next(roachpb.BatchRequest)` and `prev(roachpb.BatchRequest)` may
extend the iteration past the sub-span. We now check for this and exit
appropriately.

Fixes #12603

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 839 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-Khj-yjNKbW6X5F3GJQu:-Khj-yjNKbW6X5F3GJQv:b-d1ayrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/kv/dist_sender.go#L839)):*
> ```Go
> 		// a sub-span of the original, causing next() and prev() methods
> 		// to potentially return values which invert the span.
> 		if !ri.NeedAnother(rs) || !nextRS.Key.Less(nextRS.EndKey) {
> ```

Is it possible to add a test that more specifically exercises this condition?

---

*[pkg/roachpb/data.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-Khj-GMFJ67O1dJDM4oP:-Khj-GMFJ67O1dJDM4oQ:b-6xsypo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/data.go#L65)):*
> ```Go
> 	// implemented in package git.com/cockroachdb/cockroach/keys to avoid
> 	// package circle import.
> 	PrettyPrintRange func(b *bytes.Buffer, start, end Key, maxChars int)
> ```

It's asymmetric that this function takes a `*bytes.Buffer` while `PrettyPrintKey` returns a `string`. I think you could hide this, though perhaps I'm just being OCD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-:-Khj02fafvqjDMsGdU_n:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/metadata.go, line 176 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjXbx-mAmrjtXp_fSa:-KhjXbx-mAmrjtXp_fSb:b9n0fth) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L176)):*
> ```Go
> }
> 
> func (r RangeDescriptor) String() string {
> ```

heh, cc @andreimatei 

---

*[pkg/roachpb/metadata.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjY1gyu3lStm81dC4-:-KhjY1gzX1DV0cZPchxt:b452jx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L183)):*
> ```Go
> 		buf.WriteString("{-}")
> 	} else {
> 		const maxRangeChars = math.MaxInt32
> ```

can be implemented using r.Span() (or r.RSpan()? I don't remember which one exists)

---

*[pkg/roachpb/metadata.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjXogIQzhrEiqYpWsw:-KhjXogIQzhrEiqYpWsx:bs4u5u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L195)):*
> ```Go
> 	}
> 	if len(r.Replicas) > 0 {
> 		fmt.Fprintf(&buf, ", next=%d]", r.NextReplicaID)
> ```

always want this, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952)*

**Comment by spencerkimball** [comment]
Review status: 5 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/kv/dist_sender.go, line 839 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-Khj-yjNKbW6X5F3GJQu:-Khmkc2qL3o68IRRuB4k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/kv/dist_sender.go#L839)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is it possible to add a test that more specifically exercises this condition?
</blockquote></details>

Done.

---

*[pkg/roachpb/data.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-Khj-GMFJ67O1dJDM4oP:-Khmkd4Sz8g7hy5inuaM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/data.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It's asymmetric that this function takes a `*bytes.Buffer` while `PrettyPrintKey` returns a `string`. I think you could hide this, though perhaps I'm just being OCD.
</blockquote></details>

Done.

---

*[pkg/roachpb/metadata.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjY1gyu3lStm81dC4-:-Khml8FtydaU3JlG3DWo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L183)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can be implemented using r.Span() (or r.RSpan()? I don't remember which one exists)
</blockquote></details>

Done.

---

*[pkg/roachpb/metadata.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjXogIQzhrEiqYpWsw:-KhmkkJrRYqGMBn3obdw:bqjk3av) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

always want this, no?
</blockquote></details>

well it's not always useful, but when it is, it really is. Since we were printing this value before, seems good to keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/metadata.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjY1gyu3lStm81dC4-:-KhqMbS0w7A977yeNzz-:b-sqrjf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L183)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not `r.RSpan().String`?

---

*[pkg/roachpb/metadata.go, line 195 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhjXogIQzhrEiqYpWsw:-KhqMS3kO68z4ICNjeG9:b-6zvt4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ca7a33d9be8e28356dda8af0a322e6d8d7359b7/pkg/roachpb/metadata.go#L195)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

well it's not always useful, but when it is, it really is. Since we were printing this value before, seems good to keep it.
</blockquote></details>

I mean that you might want to print the next replica ID even when there are no replicas.

---

*[pkg/storage/replica.go, line 234 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952#-KhqMjxQAd9IFzgIES3C:-KhqMjxQAd9IFzgIES3D:b-ux03b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6546bfa633efe7cde93dc955a8f57ba952d4020/pkg/storage/replica.go#L234)):*
> ```Go
> 	} else {
> 		const maxRangeChars = 30
> 		rngStr := keys.PrettyPrintRange(roachpb.Key(desc.StartKey), roachpb.Key(desc.EndKey), maxRangeChars)
> ```

`buf.WriteString(desc.RSpan().String())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14952)*

**Comment by spencerkimball** [comment]
@tamrid: see new PR.

**Pull request merged**
