### PR TITLE
sql: Add aggregation functions for VARIANCE and STDDEV

### PR DESCRIPTION
**Pull request by nvb**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3786)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/group.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCiWi2W_L8XItOllX:-K7rCiWi2W_L8XItOllY:-1911205350) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9c8906002d9f3de28e24e7416b7aed3e63bae3/sql/group.go#L832)):*
ditto the below. isn't this always float?

---

*[sql/group.go, line 869 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCZzcMy13mVJSLZm7:-K7rCZzcMy13mVJSLZm8:766003253) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9c8906002d9f3de28e24e7416b7aed3e63bae3/sql/group.go#L869)):*
i think i'd do an unchecked cast here; if this thing is not a DFLoat, we have a bug - there's no sense reporting this error to the user.

---

*[sql/testdata/aggregate, line 529 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rAieidcRBSyQojJ1W:-K7rAieidcRBSyQojJ1X:-1826299968) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b9c8906002d9f3de28e24e7416b7aed3e63bae3/sql/testdata/aggregate#L529)):*
should fix your editor to always append the trailing newline

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/group.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCiWi2W_L8XItOllX:-K7rFiEcPV8LGp2JLCCX:1788368836) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L832)):*
The input to `VARIANCE` and `STDDEV` can be a `DInt` or a `DFloat`, so we can't do an unchecked cast here.

---

*[sql/group.go, line 869 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCZzcMy13mVJSLZm7:-K7rEd_E3_aw9Ga5Fisd:-453568741) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L869)):*
For now this will only be a `DFloat` so I made the change for now, but I'm starting to look into adding a decimal type and that will flow through all of this, which was why some of this is written this way.

---

*[sql/testdata/aggregate, line 529 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rAieidcRBSyQojJ1W:-K7rHbDl6fWFpos8xeBB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/testdata/aggregate#L529)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/group.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCiWi2W_L8XItOllX:-K7rNo7BG_dGFXjKiQNx:-1948817780) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L832)):*
OK, maybe I don't remember the interaction between aggregates and their `builtin.fn`s, but doesn't `VARIANCE`'s `builtin.fn` always return a `DFloat`? If that `builtin.fn` doesn't actually ever get called, populating it is misleading, and we should remove all the aggregates' `builtin.fn`s.

---

*[sql/group.go, line 869 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCZzcMy13mVJSLZm7:-K7rOGQQqAMLL0D0a_fT:-346988265) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L869)):*
Ah, I see. As a matter of convention, we typically use `util.Errorf` to emit errors that indicate we (the cockroach devs) made a mistake, and `fmt.Errorf` to emit errors that indicate the user made a mistake.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/group.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCiWi2W_L8XItOllX:-K7rSv7Nzyp6FvcfSuOt:1387206266) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L832)):*
The `builtin.fn`s do get run, they just immediately return their first argument without doing any type checking because that is all handled in `sql.groupNode`. And yeah `VARIANCE`'s `builtin.fn` always returns a `DFloat`, but it can take `DFloat` or `DInt` arguments. 

---

*[sql/group.go, line 869 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7rCZzcMy13mVJSLZm7:-K7rSjlz4U1YugVkXscv:1600580186) ([raw file](https://github.com/cockroachdb/cockroach/blob/322e28f2f6b46a3407ab15533eaa7d277ebc81d6/sql/group.go#L869)):*
Ah ok, good to know. I made the switch in a few spots that I found were incorrect in this file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/group.go, line 866 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7s7uCPyx8MWX2-gxWq:-K7s7uCPyx8MWX2-gxWr:1589957585) ([raw file](https://github.com/cockroachdb/cockroach/blob/970084cc22855e4d914f2a7aec1707334f1d3344/sql/group.go#L866)):*
since the "unexpected argument type" errors are elsewhere in this file, feel free to return this to the type switch form you had originally.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/group.go, line 866 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786#-K7s7uCPyx8MWX2-gxWq:-K7s8uB7HXoIC2oMod2l:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/970084cc22855e4d914f2a7aec1707334f1d3344/sql/group.go#L866)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3786)*

**Pull request merged**
