### PR TITLE
protoc-gen-gogoroach: preserve unrecognized fields

### PR DESCRIPTION
**Pull request by tamird**
Notable exceptions:
- storage/engine.MVCCStats (unsafe to change)
- util.UnresolvedAddr (used as map key, unlikely to change)

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5694)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 53 files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3U7uRFPkgCMdxUOAT:-KE3U7uS4avKh4aJGUG3:-1383770274) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/Makefile#L67)):*
Not sure I agree with this, but I suppose I can ask for the order I want. 

---

*[cli/cli_test.go, line 516 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3T8H8_vG8-S17KPVR:-KE3T8H8_vG8-S17KPVS:173644750) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/cli/cli_test.go#L516)):*
That sucks. Is there anyway to hide the `xxx_unrecognized` from YAML output.

---

*[storage/engine/mvcc.proto, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3TshRyIvLPbGZN6fS:-KE3TshRyIvLPbGZN6fT:1721169250) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/storage/engine/mvcc.proto#L73)):*
You might want to add a big WARNING comment here about the danger and complexity of adding new fields to this structure.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-:-KE3UGG-e5ir-cPULeCY:1417088721)*

**Comment by bdarnell** [comment]
What are the specific concerns here? Proto3 has removed the ability to preserve unrecognized fields (notice that gossip.pb.go has no substantial changes), so if we need that functionality we'll need to stay on proto2 (and either move our proto3 files back to proto2 or articulate why some files need it and some don't).

I have a vague sense that the preserve-unrecognized functionality is useful and that proto3 is taking a step backwards, but it's also really difficult to reason about and I'm not sure how much it really helps us. For example, in raft commands you can't safely use any new fields until 100% of the nodes recognize them, so passing them along from the gateway as unrecognized would just be a false sense of safety. 

---

Review status: 0 of 53 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Makefile, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3U7uRFPkgCMdxUOAT:-KE6KS-_RtdzSmeWlWAR:2041878661) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/Makefile#L67)):*
I still think that `make` should be equivalent to `make build`, especially as we start to get users who are not developing cockroachdb. 

And if we want a do-it-all build/test command, `testrace` should be in there. My routine before sending a PR is `make test check testrace acceptance`. 

---

*[cli/cli_test.go, line 516 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3T8H8_vG8-S17KPVR:-KE6LD0NdqGqhlwjbvzv:-525124548) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/cli/cli_test.go#L516)):*
The code generator adds a struct tag to hide xxx_unrecognized from JSON output; it would be straightforward to do the same for yaml, although upstream might view this as a slippery slope to add more formats that they don't care about. 

Could we hack it by doing proto-to-json-to-yaml or are we relying on structure that cannot be represented cleanly in json?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-:-KE6Htf5fkgWtO9sDDzu:-1343073726)*

**Comment by tamird** [comment]
@bdarnell that's a good point about proto3, I hadn't realized (or perhaps I forgot) that they had removed this functionality.

On the other hand, proto3 is still not "live", and having these unrecognized fields in our structs is more restrictive in how these structs can be used (i.e. can't be directly compared), so perhaps leaving this in for now is the more prudent thing to do rot-wise.

---

Review status: 0 of 53 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Makefile, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3U7uRFPkgCMdxUOAT:-KE6pf2YTRe-mkH8CNXm:-945177121) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/Makefile#L67)):*
I'll take this commit out. FWIW, `check` before `test` tends to be faster because `check` reports test compilation failures.

---

*[cli/cli_test.go, line 516 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3T8H8_vG8-S17KPVR:-KE70gu_KWCKwM2ATcFi:-2071698141) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/cli/cli_test.go#L516)):*
perhaps we could use json here instead of yaml?

---

*[storage/engine/mvcc.proto, line 73 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3TshRyIvLPbGZN6fS:-KE70pLypAzTrfGsWpuY:1425029905) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/storage/engine/mvcc.proto#L73)):*
Yes, will do pending the outcome of ongoing discussion here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-:-KE6p6FwWRTM6XDeTUC_:-852426152)*

**Comment by petermattis** [comment]
Review status: 0 of 53 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cli/cli_test.go, line 516 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694#-KE3T8H8_vG8-S17KPVR:-KE71Pwko_jxVXEKyyRV:-142200623) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c292ed65bfe5a76d1f3d1d3bbe795f98e465cb6/cli/cli_test.go#L516)):*
We've documented this use of yaml here. I'm not particularly fond of yaml, but I don't think json would be any better. I'd be fine with some hack to strip out the `xxx_unrecognized` from the yaml.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5694)*

**Comment by bdarnell** [comment]
> On the other hand, proto3 is still not "live"

And yet we're using it in a few places. If we merge this, I think we should also change all of our proto3 files to proto2. 

I could go either way. I feel like preserving unrecognized fields has some value, but it's mainly a vague suspicion and the proto3 team has come to the opposite conclusion.

**Comment by tamird** [comment]
OK, I think I'm reasonably convinced that we are OK without this. What's more, the general unsafety of changing any proto that goes through raft pointed out in #5753 makes this moot, I think.

**Pull request closed without merging**
