### PR TITLE
sql: do not set tag about an implicit txn in the span

### PR DESCRIPTION
**Pull request by yuzefovich**
It seems to me that we don't use that tag anywhere(?).

It was added in #22946. This should not be merged (if ever)
until the branch is cut.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
What do you mean by "not using it"? It shows up in traces, doesn't it?

**Comment by yuzefovich** [comment]
I don't think it shows up, at least I don't see in the output of `SHOW TRACE FOR SESSION;` after executing tracing a simple `SELECT * FROM t` query.

**Comment by andreimatei** [comment]
In session tracing for some reasons we filter out tags that don't start with some prefix:
https://github.com/cockroachdb/cockroach/blob/1e3f1b7ed4638d1818080c161ee44b9351d3461e/pkg/sql/exec_util.go#L2021
@asubiotto do you remember what's up with that?

But anyway, session tracing is not a particularly important thing. Tags show up when you collect the traces via OpenTracing. For example Jaeger:
Screen Shot 2021-02-26 at 1 53 41 PM

**Comment by asubiotto** [comment]
According to https://reviewable.io/reviews/cockroachdb/cockroach/25296#-LCZIvn-3uCbnay9H5Q0 it looks like it's just to keep things pretty because of the extra tags that don't mean anything (e.g. snowball tag). Should've put that in a comment. In any case, there doesn't seem to be a strong reason.

**Comment by yuzefovich** [comment]
Alright, thanks, closing.

**Pull request closed without merging**
