### PR TITLE
storage: abstract away pebbleResults as an interface

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit introduces a `results` interface (currently only implemented by `pebbleResults`) and teaches the `pebbleMVCCScanner` to use it. This interface will get a new implementation for the KV projection pushdown work in a follow-up commit.

As expected, this results in a minor perf [hit](https://gist.github.com/yuzefovich/d423c3f480069a97d4ea9b8b591e2e56), but there is no way around it, so it seems acceptable.

Epic: CRDB-14837

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxC3ps7N-1tNWl9ojH:-NKxC3ps7N-1tNWl9ojI:b-y8a31s) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L37)):*
> ```Go
> 
> func pebbleSizeOf(lenKey, lenValue int) int {
> 	return kvLenSize + lenKey + lenValue
> ```

this size computation is based on how `pebbleResults` stores the results. So in that sense, it belongs in the interface.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxAe5JDuMGRB8mQGfM:-NKxAe5K-C7IjVvYJMXy:b-277tbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L52)):*
> ```Go
> 	clear()
> 	// getNumKeys returns the number of KVs currently in the results.
> 	getNumKeys() int64
> ```

nits: how about calling these `numKeys` and `numBytes`, i.e., drop the get prefix. 
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NKxD1S62-0d2I1VAAIJ:b-c3bg6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
> ```Go
> 	}
> 
> 	// Check if adding the key would exceed a limit.
> ```

There are repeated calls to `getNumBytes` and `getNumKeys` that could be lifted out before these conditional blocks. That may help with the benchmarks.
Also, if `pebbleSizeOf` becomes part of the interface (and so no longer inlines), we can avoid that repeated call too.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxDUOA9zbxutjzvWEB:-NKxDUOA9zbxutjzvWEC:byvpjqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1201)):*
> ```Go
> 	// (~0.5% for large scans), but avoids the potentially large cost of scanning
> 	// lots of garbage before the next key -- especially when maxKeys is small.
> 	if p.maxKeys > 0 && p.results.getNumKeys() >= p.maxKeys {
> ```

related to the earlier comment about calling `getNumKeys` once. I assume if `put` returned without an error, this is just +1?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxC3ps7N-1tNWl9ojH:-NKy-9Mr0jVPnlOsJXP0:bt6cq4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L37)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this size computation is based on how `pebbleResults` stores the results. So in that sense, it belongs in the interface.
</blockquote></details>

I agree philosophically speaking. I'm not yet sure how we will calculate the footprint with the KV projection pushdown work, so I didn't initially include this method into the interface, but I refactored the code given your suggestions, so now it's implicitly in the interface.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxAe5JDuMGRB8mQGfM:-NKxpfuE5nnQYhOf7aRg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L52)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nits: how about calling these `numKeys` and `numBytes`, i.e., drop the get prefix. 
</blockquote></details>

Done.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NKy-wlR8XNUBrLZgGTl:blvnni6) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

There are repeated calls to `getNumBytes` and `getNumKeys` that could be lifted out before these conditional blocks. That may help with the benchmarks.
Also, if `pebbleSizeOf` becomes part of the interface (and so no longer inlines), we can avoid that repeated call too.
</blockquote></details>

I was debating on doing that too. My reasoning for not doing this was the fact that we don't call these methods at all in some cases (if we don't have any limits set), but we probably do set the limits (MaxSpanRequestKeys and / or TargetSize) in most cases, so it makes to extract it out like you're suggesting. Done.

I also decided to include `pebbleSizeOf` into `numBytes` as a second return parameter to reduce the number of function calls. What do you think of that? What do you think about squashing `numKeys` and `numBytes` into a single method to further reduce the number of interface dispatches?
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxDUOA9zbxutjzvWEB:-NKy0fYUAb_3N94GLg5s:bssxczp) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1201)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

related to the earlier comment about calling `getNumKeys` once. I assume if `put` returned without an error, this is just +1?
</blockquote></details>

Yes, sounds right to me, done.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NKz52Wq0Ox50coh70TA:b-9qvgwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I was debating on doing that too. My reasoning for not doing this was the fact that we don't call these methods at all in some cases (if we don't have any limits set), but we probably do set the limits (MaxSpanRequestKeys and / or TargetSize) in most cases, so it makes to extract it out like you're suggesting. Done.

I also decided to include `pebbleSizeOf` into `numBytes` as a second return parameter to reduce the number of function calls. What do you think of that? What do you think about squashing `numKeys` and `numBytes` into a single method to further reduce the number of interface dispatches?
</blockquote></details>

I ran the benchmarks several times with larger run counts, and the benchmark diff is not always the same - sometimes they actually show that this PR results in an improvement. Thus, I think the regression is quite minor (when using end-to-end benchmarks).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NKzciQe0qjeN1zCfmF3:bmwdh5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I ran the benchmarks several times with larger run counts, and the benchmark diff is not always the same - sometimes they actually show that this PR results in an improvement. Thus, I think the regression is quite minor (when using end-to-end benchmarks).
</blockquote></details>

I also ran lower level benchmarks ([here](https://gist.github.com/yuzefovich/07babbdb46ecbb79f44011493b6ef46f)), and they do show the minor perf hit more reliably.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-:-NL2ehVA2oYYi99buIjO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NL2e5rw3jxl9Z7qBeJm:bus05x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I also ran lower level benchmarks ([here](https://gist.github.com/yuzefovich/07babbdb46ecbb79f44011493b6ef46f)), and they do show the minor perf hit more reliably.
</blockquote></details>

I am fine with squashing `numKeys` and `numBytes` into a single method. We call both as a pair in both of the non-test callsites.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NL2dKOv5fDzPUQve0ve:-NL2dKOv5fDzPUQve0vf:b-iinz6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cadc916b7e35fe700fd442d64d8e0ae49f94b30/pkg/storage/pebble_mvcc_scanner.go#L137)):*
> ```Go
> const pebbleResultsKVLenSize = 8
> 
> func (p *pebbleResults) sizeOf(lenKey, lenValue int) int {
> ```

can this be `func pebbleResultsKVSizeOf(lenKey, lenValue int)` since it's not part of the interface.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-:-NL30TjH00LICt6mh47y:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 1141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NKxD1S62-0d2I1VAAII:-NL3-tCd--zxNB-6d5KF:b8wcpyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0d9ba8385e46a6e3fd4ef86d390cec06effff2/pkg/storage/pebble_mvcc_scanner.go#L1141)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I am fine with squashing `numKeys` and `numBytes` into a single method. We call both as a pair in both of the non-test callsites.
</blockquote></details>

Right, sgtm, squashed them into one.
___
*[`pkg/storage/pebble_mvcc_scanner.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94446#-NL2dKOv5fDzPUQve0ve:-NL2zJxXA409ZfJpaL1_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cadc916b7e35fe700fd442d64d8e0ae49f94b30/pkg/storage/pebble_mvcc_scanner.go#L137)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can this be `func pebbleResultsKVSizeOf(lenKey, lenValue int)` since it's not part of the interface.
</blockquote></details>

Done.

**Pull request merged**
