### PR TITLE
sql: Clear all multi-region fields on table locality changes

### PR DESCRIPTION
**Pull request by ajstorm**
See individual commits for details.

### CODE REVIEW

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MY3gXk58pND_SKDHqSd:-MY3gXk58pND_SKDHqSe:bc9n2gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/514df9b2b25d81ceb571f8abfd577ab94d590400/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L820)):*
> ```
> 
> statement ok
> ALTER TABLE tbl2 SET LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> ```

nit: trailing `;`s here and above
___
*[pkg/config/zonepb/zone.go, line 640 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MY3g2Ir7BahoioZXnVa:-MY3g2Ir7BahoioZXnVb:b-uwo7cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/514df9b2b25d81ceb571f8abfd577ab94d590400/pkg/config/zonepb/zone.go#L640)):*
> ```Go
> 				// (and other isn't) continue here so that we can report the
> 				// difference at the subzone level below.
> 				if z.IsSubzonePlaceholder() {
> ```

this check seems inadequate / can cause confusion as well.
what if z is a placeholder, but other has explicitly set num_replicas to say 5? we'd report no error in this case.
we should probably set some var like `isMismatchingNumreplicas := true`, and return an error after the subzones check for just num_replicas being broken in this case.

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MY3gXk58pND_SKDHqSd:-MY5deop83XJ2I82N0IN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/514df9b2b25d81ceb571f8abfd577ab94d590400/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L820)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: trailing `;`s here and above
</blockquote></details>

Fixed.
___
*[pkg/config/zonepb/zone.go, line 640 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MY3g2Ir7BahoioZXnVa:-MY5dltl5Y5Bzr8vsaqy:b-qwlmt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/514df9b2b25d81ceb571f8abfd577ab94d590400/pkg/config/zonepb/zone.go#L640)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this check seems inadequate / can cause confusion as well.
what if z is a placeholder, but other has explicitly set num_replicas to say 5? we'd report no error in this case.
we should probably set some var like `isMismatchingNumreplicas := true`, and return an error after the subzones check for just num_replicas being broken in this case.
</blockquote></details>

Yeah, I considered that too, but realized that there's no way to currently get into that as MR is defined today (at least, I can't think of a way).  That being said, you're right that this function could be used more broadly down the road.  I've changed things as you suggested.

**Review by otan — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by ajstorm** [comment]
Could I get you to take a quick second (or is it third now) look?  Had to
refactor something to (a) make it more idiomatic and (b) not panic.  I'm
hopeful that the new code will be much more to your liking.

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 731 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0INI7Hiqp3OP1puD:-MYC0INI7Hiqp3OP1puE:b-d6kwt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L731)):*
> ```
> SET override_multi_region_zone_config = true;
> ALTER INDEX tbl1@tbl1_i_idx CONFIGURE ZONE USING num_replicas=10;
> SET override_multi_region_zone_config = false;
> ```

nit: trailing ; here and a few lines below up to CREATE TABLE tbl2
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Q7iBamT-mZOKVSL:-MYC0Q7iBamT-mZOKVSM:b-4i8wam) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L741)):*
> ```
> SET override_multi_region_zone_config = true;
> ALTER TABLE tbl1 SET LOCALITY GLOBAL;
> SET override_multi_region_zone_config = false;
> ```

can we double check the zone configuration here? `SHOW ZONE CONFIGURATION FOR INDEX tbl1@tbl1_i_idx`
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYC0Z1vCD2R8hPcLLb_:bq0r5jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
> ```
> SET override_multi_region_zone_config = false
> 
> statement error attempting to update zone config which contains an extra zone configuration for index tbl2@tbl2_i_idx with field num_replicas populated
> ```

can we add a test that sets gc.ttlseconds on this index and make sure it does not get modified after these overrides?
___
*[pkg/sql/region_util.go, line 518 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC-rtC5552qH4r7aL_:-MYC-rtC5552qH4r7aLa:b-98ghio) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/sql/region_util.go#L518)):*
> ```Go
> 	// zone config so that the user won't have to override again the next time
> 	// the want to ALTER the table locality.
> 	newSubZones := zc.Subzones[:0]
> ```

nit: for consistency, newSubzones (just how we call it elsewhere)

**Review by ajstorm — COMMENTED** [review]
All addressed but one.  Need clarification on the GC TTL request.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-:-MYC58E24l-rEw0Zkt2b:b5mksol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 731 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0INI7Hiqp3OP1puD:-MYC2rWTBy90eIRvHP_3:b-1ymef8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L731)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: trailing ; here and a few lines below up to CREATE TABLE tbl2
</blockquote></details>

Cleaned up the rest of the file;
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 741 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Q7iBamT-mZOKVSL:-MYC3gDhAuLRohrwoHlm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L741)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we double check the zone configuration here? `SHOW ZONE CONFIGURATION FOR INDEX tbl1@tbl1_i_idx`
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYC4Q983VZwY5cJsT7R:b2q6ru3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we add a test that sets gc.ttlseconds on this index and make sure it does not get modified after these overrides?
</blockquote></details>

"make sure" how exactly?

**Comment by otan** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYCCRDi88f6QOF2mtUG:b-2jhdbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

"make sure" how exactly?
</blockquote></details>

* set gc.ttlseconds and num_replicas on index
* set override = true
* change locality
* ensure the gc.ttlseconds is still on the index

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYCuJGn00GO0-T6vJjk:b-sdl0lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

* set gc.ttlseconds and num_replicas on index
* set override = true
* change locality
* ensure the gc.ttlseconds is still on the index
</blockquote></details>

ahhh!  What confused me is that you were talking about GC TTL and I thought the "it" above was the the index (as in, it was somehow going to be modified by the GC).  All good.

The only problem is that this doesn't do what you're expecting.  Since this is a RBR->GLOBAL transition, we blow away all of the index zone configs unconditionally with `dropZoneConfigsForMultiRegionIndexes`.  

We probably want to change that to be more subtle, but I'll leave that for the next PR.

This one keeps on giving...

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYD2c-xEybM6FSmlKpV:bxezns8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

ahhh!  What confused me is that you were talking about GC TTL and I thought the "it" above was the the index (as in, it was somehow going to be modified by the GC).  All good.

The only problem is that this doesn't do what you're expecting.  Since this is a RBR->GLOBAL transition, we blow away all of the index zone configs unconditionally with `dropZoneConfigsForMultiRegionIndexes`.  

We probably want to change that to be more subtle, but I'll leave that for the next PR.

This one keeps on giving...
</blockquote></details>

happy for it to be blown away, as long as it's tested!

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63461)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs, line 811 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/63461#-MYC0Z1vCD2R8hPcLLbZ:-MYD2wr0CpObQ1kC8Pay:bo3n2jg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3077f2bd41afd0ba0ce377f31ed4de41e1bebc86/pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs#L811)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

happy for it to be blown away, as long as it's tested!
</blockquote></details>

The problem is that it's a bit strange that we unconditionally blow them away for RBR and selectively do it for GLOBAL and REGIONAL BY TABLE.  Seems like we'd want to be consistent about it.  

https://github.com/cockroachdb/cockroach/issues/63614

**Comment by ajstorm** [comment]
TFTR!

bors r=otan

**Pull request merged**
