### PR TITLE
opt: inline constant insert values in uniqueness checks

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: move constant value helpers to memo package

This commit moves some logic in normalization custom functions to the
memo package so that it can be used more generally in the future.

Release note: None

#### opt: inline constant insert values in uniqueness checks

In uniqueness checks, WithScans that buffer the mutation's input are now
replaced with Values expression when inserted values are constant. This
allows further optimization of the uniqueness check sub-expression. It
is particularly beneficial for `REGIONAL BY ROW` tables and hash-sharded
`REGIONAL BY ROW` tables because it reduces the search space for
duplicate values.

Note that this inlining does not occur for FK checks. The FK insert fast
path relies on WithScans in FK checks. Until this limitation is lifted,
inlining constant insert values would prevent the fast path from being
planned.

Informs #63882

Release note (performance improvement): Previously, uniqueness checks
performed for inserts into REGIONAL BY ROW tables always searched all
regions for duplicates. In some cases, these checks will now only search
a subset of regions when inserting a single row of constant values.

### CODE REVIEW

**Comment by mgartner** [comment]
This commit revives an old PR where I attempted to do the same: #65093. The main difference is that this PR only inlines values in uniqiueness checks. It does not inline values into FK checks to avoid breaking the insert fast path. I have some ideas on how to overcome this limitation, but I'll save that for a future PR.

---

cc @chengxiong-ruan who might be interested in some of the improvements to queries with hash-sharded indexes.

**Review by msirek — APPROVED** [review]
Very nice!  I'm curious how much speedup this yields in common cases.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-:-MyK8NQO0E3FiFj-Pngd:b9decv0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyJwA84C1XnOogLi30a:-MyJwA84C1XnOogLi30b:b-tfwv56) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2ad76c55eec1df2cce150b4340dec9336eae0f/pkg/sql/opt/memo/expr.go#L843)):*
> ```Go
> 	if project, ok := input.(*ProjectExpr); ok {
> 		for i := range project.Projections {
> 			item := &project.Projections[i]
> ```

I know this is just moving the function, but I wonder if it's useful to examine Passthrough columns too and peek into the child operation to look for the constant.  Maybe there are no use cases where this is needed though.



_Code quote:_
```Go
ExtractColumnFromProjectOrValues
```
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MyK1ZJc6ouC5jZ40uPv:b-7fxz2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
> ```
>                             │     estimated row count: 1 (missing stats)
>                             │     table: t_unique_hash_pk@t_unique_hash_pk_pkey
>                             │     spans
> ```

This looks like when intersecting `spans` the result is empty.  Do you think it would be worth opening an issue to eliminate the UNION ALL when one side is known to return zero rows.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyJwA84C1XnOogLi30a:-MyNYAv_51h4A2NM6AOp:b-nllrm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2ad76c55eec1df2cce150b4340dec9336eae0f/pkg/sql/opt/memo/expr.go#L843)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I know this is just moving the function, but I wonder if it's useful to examine Passthrough columns too and peek into the child operation to look for the constant.  Maybe there are no use cases where this is needed though.
</blockquote></details>

I don't think it's necessary because normalization rules should merge all the Projects together, or merge the Projects into a subexpression that is a single Values row.

For example:

```
optsteps
SELECT a + 1 FROM (VALUES (1)) AS v(a)
----
================================================================================
Initial expression
  Cost: 0.05
================================================================================
  project
   ├── columns: "?column?":2!null
   ├── cardinality: [1 - 1]
   ├── immutable
   ├── key: ()
   ├── fd: ()-->(2)
   ├── values
   │    ├── columns: column1:1!null
   │    ├── cardinality: [1 - 1]
   │    ├── key: ()
   │    ├── fd: ()-->(1)
   │    └── (1,)
   └── projections
        └── column1:1 + 1 [as="?column?":2, outer=(1), immutable]
================================================================================
InlineProjectConstants
  Cost: 0.05
================================================================================
   project
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
    ├── immutable
    ├── key: ()
    ├── fd: ()-->(2)
    ├── values
    │    ├── columns: column1:1!null
    │    ├── cardinality: [1 - 1]
    │    ├── key: ()
    │    ├── fd: ()-->(1)
    │    └── (1,)
    └── projections
  -      └── column1:1 + 1 [as="?column?":2, outer=(1), immutable]
  +      └── 1 + 1 [as="?column?":2, immutable]
================================================================================
FoldBinary
  Cost: 0.05
================================================================================
   project
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
  - ├── immutable
    ├── key: ()
    ├── fd: ()-->(2)
    ├── values
    │    ├── columns: column1:1!null
    │    ├── cardinality: [1 - 1]
    │    ├── key: ()
    │    ├── fd: ()-->(1)
    │    └── (1,)
    └── projections
  -      └── 1 + 1 [as="?column?":2, immutable]
  +      └── 2 [as="?column?":2]
================================================================================
MergeProjectWithValues
  Cost: 0.02
================================================================================
  -project
  +values
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
    ├── key: ()
    ├── fd: ()-->(2)
  - ├── values
  - │    ├── columns: column1:1!null
  - │    ├── cardinality: [1 - 1]
  - │    ├── key: ()
  - │    ├── fd: ()-->(1)
  - │    └── (1,)
  - └── projections
  -      └── 2 [as="?column?":2]
  + └── (2,)
================================================================================
Final best expression
  Cost: 0.02
================================================================================
  values
   ├── columns: "?column?":2!null
   ├── cardinality: [1 - 1]
   ├── key: ()
   ├── fd: ()-->(2)
   └── (2,)
```

Anything beneath the Project should be non-constant (or at least not provably constant).
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MyN7B9JEt67f65HCo2o:bqlutf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

This looks like when intersecting `spans` the result is empty.  Do you think it would be worth opening an issue to eliminate the UNION ALL when one side is known to return zero rows.
</blockquote></details>

Great eye! I spent all day yesterday working on ways to eliminate the scan with a contradiction constraint and the union all. It's a bit tricky, but I'll keep at it. I've created an issue to track: https://github.com/cockroachdb/cockroach/issues/78026

**Review by msirek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/memo/expr.go, line 843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyJwA84C1XnOogLi30a:-MyNbtJZ0HsB6Mj3O037:brujztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2ad76c55eec1df2cce150b4340dec9336eae0f/pkg/sql/opt/memo/expr.go#L843)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't think it's necessary because normalization rules should merge all the Projects together, or merge the Projects into a subexpression that is a single Values row.

For example:

```
optsteps
SELECT a + 1 FROM (VALUES (1)) AS v(a)
----
================================================================================
Initial expression
  Cost: 0.05
================================================================================
  project
   ├── columns: "?column?":2!null
   ├── cardinality: [1 - 1]
   ├── immutable
   ├── key: ()
   ├── fd: ()-->(2)
   ├── values
   │    ├── columns: column1:1!null
   │    ├── cardinality: [1 - 1]
   │    ├── key: ()
   │    ├── fd: ()-->(1)
   │    └── (1,)
   └── projections
        └── column1:1 + 1 [as="?column?":2, outer=(1), immutable]
================================================================================
InlineProjectConstants
  Cost: 0.05
================================================================================
   project
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
    ├── immutable
    ├── key: ()
    ├── fd: ()-->(2)
    ├── values
    │    ├── columns: column1:1!null
    │    ├── cardinality: [1 - 1]
    │    ├── key: ()
    │    ├── fd: ()-->(1)
    │    └── (1,)
    └── projections
  -      └── column1:1 + 1 [as="?column?":2, outer=(1), immutable]
  +      └── 1 + 1 [as="?column?":2, immutable]
================================================================================
FoldBinary
  Cost: 0.05
================================================================================
   project
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
  - ├── immutable
    ├── key: ()
    ├── fd: ()-->(2)
    ├── values
    │    ├── columns: column1:1!null
    │    ├── cardinality: [1 - 1]
    │    ├── key: ()
    │    ├── fd: ()-->(1)
    │    └── (1,)
    └── projections
  -      └── 1 + 1 [as="?column?":2, immutable]
  +      └── 2 [as="?column?":2]
================================================================================
MergeProjectWithValues
  Cost: 0.02
================================================================================
  -project
  +values
    ├── columns: "?column?":2!null
    ├── cardinality: [1 - 1]
    ├── key: ()
    ├── fd: ()-->(2)
  - ├── values
  - │    ├── columns: column1:1!null
  - │    ├── cardinality: [1 - 1]
  - │    ├── key: ()
  - │    ├── fd: ()-->(1)
  - │    └── (1,)
  - └── projections
  -      └── 2 [as="?column?":2]
  + └── (2,)
================================================================================
Final best expression
  Cost: 0.02
================================================================================
  values
   ├── columns: "?column?":2!null
   ├── cardinality: [1 - 1]
   ├── key: ()
   ├── fd: ()-->(2)
   └── (2,)
```

Anything beneath the Project should be non-constant (or at least not provably constant).
</blockquote></details>

OK, thanks.
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MyNbwpNEVMM4rmnXg8A:b-tgvwwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great eye! I spent all day yesterday working on ways to eliminate the scan with a contradiction constraint and the union all. It's a bit tricky, but I'll keep at it. I've created an issue to track: https://github.com/cockroachdb/cockroach/issues/78026
</blockquote></details>

Thanks for looking into it. It shouldn't hold up this PR, but I was just curious about this. We don't currently have a lot of normalization rules matching on UNION ALL, but maybe it's possible to train `EliminateSetLeft` and `EliminateSetRight` to handle this.  I see they call `HasZeroRows` which calls `Relational().Cardinality.IsZero()`.  Maybe `HasZeroRows` could also look for a `ScanExpr` inside a `ProjectExpr` or `SelectExpr` and see if there's a contradiction constraint.

**Comment by mgartner** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MyNhrOxB_JROxStIcbo:bknismo) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Thanks for looking into it. It shouldn't hold up this PR, but I was just curious about this. We don't currently have a lot of normalization rules matching on UNION ALL, but maybe it's possible to train `EliminateSetLeft` and `EliminateSetRight` to handle this.  I see they call `HasZeroRows` which calls `Relational().Cardinality.IsZero()`.  Maybe `HasZeroRows` could also look for a `ScanExpr` inside a `ProjectExpr` or `SelectExpr` and see if there's a contradiction constraint.
</blockquote></details>

The problem is that normalization rules only apply when `norm.Factory.ConstructXxxx` functions are called. When `SplitDisjunction` calls `Factory.ConstructUnionAll`, the left side is an expression like `(Select (Scan ...) Filters)`. This doesn't appear to be a contradiction, so the left side is not simplified to an empty values expression, thus the `UnionAll` is not eliminated. 

Only later on, when `GenerateConstrainedScans` fires, is it determined that the Select's filters and the computed column expression form a contradiction. At this point, there is no opportunity for `EliminateSetLeft` to fire because the `UnionAll` has already been constructed.

I think we'd also have trouble making an exploration rule that eliminates the `UnionAll`. The `(Select (Scan ...) Filters)` created on the left side of the `UnionAll` by `SplitDisjunction` is the first member of a new group. The Cardinality in the logical properties of this group is not zero because, like I mentioned above, it's not apparent that there is a contradiction. `GenerateConstrainedScans` adds the `(Scan contradiction)` to this same group. However, the cardinality of the scan remains non-zero because logical properties are shared by all members of a group.

I do have a somewhat promising idea, though. We can add the computed column equality into the filters during normalization, and the other normalization rules should fire to eliminate the `OR` entirely. Then SplitDisjunction never matches, and the `UnionAll` is never created. I mentioned this in #78026. It is a non-trivial rule, however, mostly because there's not an obvious way to prevent the rule from matching over and over again forever.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MyNowFR-oGVbD55D7gG:b-c6f73t) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The problem is that normalization rules only apply when `norm.Factory.ConstructXxxx` functions are called. When `SplitDisjunction` calls `Factory.ConstructUnionAll`, the left side is an expression like `(Select (Scan ...) Filters)`. This doesn't appear to be a contradiction, so the left side is not simplified to an empty values expression, thus the `UnionAll` is not eliminated. 

Only later on, when `GenerateConstrainedScans` fires, is it determined that the Select's filters and the computed column expression form a contradiction. At this point, there is no opportunity for `EliminateSetLeft` to fire because the `UnionAll` has already been constructed.

I think we'd also have trouble making an exploration rule that eliminates the `UnionAll`. The `(Select (Scan ...) Filters)` created on the left side of the `UnionAll` by `SplitDisjunction` is the first member of a new group. The Cardinality in the logical properties of this group is not zero because, like I mentioned above, it's not apparent that there is a contradiction. `GenerateConstrainedScans` adds the `(Scan contradiction)` to this same group. However, the cardinality of the scan remains non-zero because logical properties are shared by all members of a group.

I do have a somewhat promising idea, though. We can add the computed column equality into the filters during normalization, and the other normalization rules should fire to eliminate the `OR` entirely. Then SplitDisjunction never matches, and the `UnionAll` is never created. I mentioned this in #78026. It is a non-trivial rule, however, mostly because there's not an obvious way to prevent the rule from matching over and over again forever. 
</blockquote></details>

Interesting idea.  Would the rule keep firing because the idea adds computed column equality within a normalization rule?  Would it be possible to add the equality around the same location as `Builder.addCheckConstraintsForTable()` is called?  Maybe not all required info is available at that location though.

Another option may be to re-run normalization rules on all `RelExpr`s after all transformation rules are applied.  But that would require pulling all of the normalization rules out into functions instead of inlining them in the `norm.Factory.ConstructXxxx` functions; a slightly drastic change, but may be worth thinking about.  Something like that might mean items in the `internCache` would need to get removed and re-added if their hash changes.

**Comment by mgartner** [comment]
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MyK1ZJc6ouC5jZ40uPu:-MzGpvyh1TDyAQnoM1cU:b-qeklsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/99f4be6fc5c3de544ea279ec1281fb9b0f05b315/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
> Would the rule keep firing because the idea adds computed column equality within a normalization rule? 

A simple implementation of the rule would match something like `(Select (Scan) $filters:*)` and produce `(Select (Scan) (ConcatFilters $filters $compColFilters))`. The generated Go would be a block in `ConstructSelect` that recursively calls `ConstructSelect`. After the new filters have been added the first time, we need a way to prevent the rule from matching on the subsequent recursive calls.

> Another option may be to re-run normalization rules on all RelExprs after all transformation rules are applied.

This has come up before, but we've been reluctant to try it because it won't work in _all_ cases. If we do a pass of normalization rules after the lowest cost plan has been selected, we might not end up with the optimal plan. The optimal plan could be one that only has the lowest cost after that final round of normalization rules.

**Comment by mgartner** [comment]
@rytaft do you mind taking a look at this when you get a chance? No rush.

**Review by rytaft — COMMENTED** [review]
Very nice! So sorry for the delay.

> Reviewed 2 of 2 files at r1, 12 of 12 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-:-MzVph1f6slUkPQk_sE1:b-llsaeh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVj6S65xXAqc6guL8i:-MzVj6S65xXAqc6guL8j:b-v7c1q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/sql/opt/optbuilder/mutation_builder.go#L1329)):*
> ```Go
> // non-nullable table columns).
> //
> // fk should be true when building inputs for FK checks, and false otherwise.
> ```

nit: I'd call this `isFK`
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVkcpD1HP9E7VmD1DH:-MzVkcpD1HP9E7VmD1DI:b3acsx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L86)):*
> ```
> # TODO (mgartner): there is a lookup join with lookup condition checking every
> # single shard. This is unnecessary and could be improved by having the shard
> # number calculated instead of looking at all possible shards.
> ```

can you remove this TODO now?
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVlSWV-og5WalY1A3G:-MzVlSWV-og5WalY1A3H:b-w2a73d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
> ```
>                             │     estimated row count: 1 (missing stats)
>                             │     table: t_unique_hash_pk@t_unique_hash_pk_pkey
>                             │     spans
> ```

what is this expression?  looks like a full table scan?
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit, line 781 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVmGyQC8K1sBBe6TcA:-MzVmGyQC8K1sBBe6TcB:b-7wysz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L781)):*
> ```
>     └── • error if rows
>         │
>         └── • norows
> ```

awesome!

We could potentially optimize this to remove the constraint check altogether in this case (in a future PR)

Edit: I see you added a TODO for this elsewhere
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 1524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVnCqN5Rj6q2h-h243:-MzVnCqN5Rj6q2h-h244:b-tqikk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L1524)):*
> ```
> # TODO(treilly): The constraint check for uniq_idx should use uniq_idx but due
> # to stats issues w/ empty stats, partial indexes and multicol stats its not.
> # Hopefully fixing #67583 (and possibly #67479) will resolve this.
> ```

wonder if we can remove this TODO
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 2207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVo8na6ZoQwA7ciE_D:-MzVo8na6ZoQwA7ciE_E:b-vc89j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2207)):*
> ```
> │                         missing stats
> │                         table: regional_by_row_table_virt_partial@regional_by_row_table_virt_partial_pkey
> │                         spans: [/'ap-southeast-2' - /'ap-southeast-2'] [/'ca-central-1' - /'us-east-1']
> ```

Not related to this PR, but here's an example where I think we probably want to enable @msirek's stats logic to get distinct counts / histograms from check constraints even when there are no stats available.

**Review by mgartner — COMMENTED** [review]
No worries!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-:-MzXAi1K6D9wkRoPFdS-:b-vqkjus)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1329 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVj6S65xXAqc6guL8i:-MzXBKGc9TLav7Vgavvi:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/sql/opt/optbuilder/mutation_builder.go#L1329)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I'd call this `isFK`
</blockquote></details>

Good idea. Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVkcpD1HP9E7VmD1DH:-MzXDNb36k4aaz5t4jIW:b-qphs9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L86)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you remove this TODO now?
</blockquote></details>

There is still the FK check where the values are not inlined, so all shards are searched. I think if we can inline the values in the FK check in the future, only a single shard would be searched. I've left the TODO but reworded it to make it more clear that it is referencing the FK check, not the uniqueness check.
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVlSWV-og5WalY1A3G:-MzXEEAH0G1dJVcJWfXe:b-wkey9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

what is this expression?  looks like a full table scan?
</blockquote></details>

It's actually a span with a contradiction constraint. See the discussion Mark and I had above. It's quite peculiar. I've already created an issue to track this: https://github.com/cockroachdb/cockroach/issues/78026
___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit, line 781 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVmGyQC8K1sBBe6TcA:-MzXEzUEDZCq01EKFxmh:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit#L781)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

awesome!

We could potentially optimize this to remove the constraint check altogether in this case (in a future PR)

Edit: I see you added a TODO for this elsewhere
</blockquote></details>

:+1: 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 1524 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVnCqN5Rj6q2h-h243:-MzXGHv6C4aR90s0_79J:b-7ob79h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L1524)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

wonder if we can remove this TODO
</blockquote></details>

Ya, looks like `uniq_idx` is now being used. I'm removed the TODO.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior, line 2207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVo8na6ZoQwA7ciE_D:-MzXGY3z1fk_vlIgfqtR:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2207)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Not related to this PR, but here's an example where I think we probably want to enable @msirek's stats logic to get distinct counts / histograms from check constraints even when there are no stats available.
</blockquote></details>

:+1:

**Review by rytaft — APPROVED** [review]
:lgtm: This feels like something we could consider backporting for 22.1.1 -- what do you think?

> Reviewed 12 of 12 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-:-MzXk0wr4c7HJlRUxNFP:b-q6g6mv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan, line 390 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77943#-MzVlSWV-og5WalY1A3G:-MzXjkne44GkQZ3kcM9k:bgm9lwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee4e37d6f8a780f5a41e4d02054a08f16040324/pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan#L390)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's actually a span with a contradiction constraint. See the discussion Mark and I had above. It's quite peculiar. I've already created an issue to track this: https://github.com/cockroachdb/cockroach/issues/78026
</blockquote></details>

Ohhh got it. Thanks!

**Comment by mgartner** [comment]
> This feels like something we could consider backporting for 22.1.1 -- what do you think?

Seems fine to me. I'll add the backport label.

TFTRs!

bors r+

**Pull request merged**
