### PR TITLE
authors: add <yecs1999> to authors file

### PR DESCRIPTION
**Pull request by yecs1999**
adding name to AUTHORS

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
Discussed offline, but please clean up the commit history.

**Review by rickystewart — CHANGES_REQUESTED** [review]
A couple requests:

1. Your commit needs a release justification or it won't make it through CI. A line like `Release justification: Non-production code change` would be fine.
2. Rename the PR. You usually want it to have the same name as your commit. So `authors: add <yecs1999> to authors file`

**Comment by rickystewart** [comment]
(fyi the release justification note doesn't usually apply, you just happened to have joined the company the week where it's necessary)

**Comment by yecs1999** [comment]
I think it should be okay now, I had to force push again to change the message.

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
