### PR TITLE
storeliveness,inspectz,sql: expose store liveness state

### PR DESCRIPTION
**Pull request by miraradeva**
The first commit introduces two new inspectz endpoints:

- `/inspectz/storeliveness/supportFrom`: for each store on the local server, returns the set of stores the local store is receiving support from, along with the corresponding epochs and expiration timestamps.

- `/inspectz/storeliveness/supportFor`: for each store on the local server, returns the set of stores the local store is providing support for, along with the corresponding epochs and expiration timestamps.

The second commit adds two new `crdb_internal` tables that expose the node-level view of the local stores' support for and from other stores. They are powered by the /inspectz server API.

Both new tables have the same schema:

```
CREATE TABLE crdb_internal.store_liveness_support_{for,from} (
node_id INT NOT NULL,
store_id INT NOT NULL,
support_{for,from}_node_id INT NOT NULL,
support_{for,from}_store_id INT NOT NULL,
support_epoch INT NOT NULL,
support_expiration TIMESTAMP NOT NULL
```

These tables will be empty unless both store liveness and Raft leader fortification are enabled.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-:-O9uLBoH0TRc67UR3lC6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @arulajmani, @iskettaneh, @mgartner, @miraradeva, and @xinhaoz)

___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uIjB4854YkfAAmi74:-O9uIjB4854YkfAAmi75:b9yt8qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L130)):*
> ```Go
> // Liveness state to be combined into a per-node view. It powers the inspectz
> // Store Liveness functionality.
> // TODO(mira): This may not be the best place for this definition and the ones
> ```

Since this isn't operating at the replica level, I think this should live somewhere else (e.g. in a `pkg/kv/kvserver/store_liveness.go` file or a `pkg/kv/kvserver/stores_store_liveness.go` file).
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uIsDD2UJRYGM2AEXk:-O9uIsDD2UJRYGM2AEXl:bhkfjt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L150)):*
> ```Go
> 
> // InspectAllSupportFrom implements the InspectAllStoreLiveness interface. It
> // iterates over all stores and aggregates their SupportStates.
> ```

nit: "aggregates their SupportFrom SupportStates"? And same thing down below?
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJ5ZgA8OJ0MvVELOE:-O9uJ5ZgA8OJ0MvVELOF:b-aev6jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L157)):*
> ```Go
> 		sspf = append(sspf, s.storeLiveness.InspectSupportFrom())
> 		return nil
> 	}); err != nil {
> ```

Should we have these methods return `errors`?
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJL184KhLPjTw-ena:-O9uJL184KhLPjTw-enb:bupcfah) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/requester_state.go#L157)):*
> ```Go
> 	rsh.mu.RLock()
> 	defer rsh.mu.RUnlock()
> 	var supportStates []slpb.SupportState
> ```

We can pre-allocate this slice with the correct capacity.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJdfQ3JbQWrXSXIMR:-O9uJdfQ3JbQWrXSXIMS:blzjrl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/support_manager.go#L56)):*
> ```Go
> }
> 
> var _ Fabric = &SupportManager{}
> ```

nit: ` = (*SupportManager)(nil)`, like below.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJVsdEUU_EtYEcGTl:-O9uJVsdEUU_EtYEcGTm:blrfn1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/support_manager.go#L124)):*
> ```Go
> }
> 
> var _ InspectFabric = (*SupportManager)(nil)
> ```

nit: this isn't needed, since we embed `InspectFabric` into `Fabric` and already have the type assertion above.
___
*[`pkg/kv/kvserver/storeliveness/supporter_state.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJO6n6RbPlYHE4n0i:-O9uJO6n6RbPlYHE4n0j:bupcfah) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/supporter_state.go#L117)):*
> ```Go
> 	ssh.mu.RLock()
> 	defer ssh.mu.RUnlock()
> 	var supportStates []slpb.SupportState
> ```

We can pre-allocate this slice with the correct capacity.
___
*[`pkg/sql/crdb_internal.go` line 9596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uKwe43oAt2iEtxp3O:-O9uKwe43oAt2iEtxp3P:blctnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaf1750511b984e7ccea166e7a48d43df6b7c487/pkg/sql/crdb_internal.go#L9596)):*
> ```Go
> 				tree.NewDInt(tree.DInt(ss.Target.StoreID)),
> 				tree.NewDInt(tree.DInt(ss.Epoch)),
> 				&tree.DTimestamp{Time: timeutil.Unix(0, ss.Expiration.WallTime).Round(time.Microsecond)},
> ```

Can we use `TimestampToInexactDTimestamp` here?
___
*[`pkg/cli/zip_test.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uL8ID4bmoZFs_1jrl:-O9uL8ID4bmoZFs_1jrm:b53ipo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaf1750511b984e7ccea166e7a48d43df6b7c487/pkg/cli/zip_test.go#L121)):*
> ```Go
> 	'statement_statistics_persisted_v22_2',
> 	'store_liveness_support_for',
>   'store_liveness_support_from',
> ```

nit: what's up with the indentation in this test?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132252)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @arulajmani, @iskettaneh, @mgartner, @nvanbenschoten, and @xinhaoz)

___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uIjB4854YkfAAmi74:-OAJD5kK964zVft9UXQe:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Since this isn't operating at the replica level, I think this should live somewhere else (e.g. in a `pkg/kv/kvserver/store_liveness.go` file or a `pkg/kv/kvserver/stores_store_liveness.go` file).
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uIsDD2UJRYGM2AEXk:-OAJDcJh5OLj0bK084Mf:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: "aggregates their SupportFrom SupportStates"? And same thing down below?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJ5ZgA8OJ0MvVELOE:-OAJF4jU3UI0O-SOVrx1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/replica_store_liveness.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we have these methods return `errors`?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/requester_state.go` line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJL184KhLPjTw-ena:-OAJFUtyBirS1oPTBHEu:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/requester_state.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can pre-allocate this slice with the correct capacity.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJdfQ3JbQWrXSXIMR:-OAJFdI9AqiOch8YfwOT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/support_manager.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: ` = (*SupportManager)(nil)`, like below.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJVsdEUU_EtYEcGTl:-OAJFdpdCrCl9xq_wq7N:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/support_manager.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this isn't needed, since we embed `InspectFabric` into `Fabric` and already have the type assertion above.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/supporter_state.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uJO6n6RbPlYHE4n0i:-OAJFfCNADoHtTVDi2GF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9d3e78f1d16abff958ce14e3aedcd7daacde4b/pkg/kv/kvserver/storeliveness/supporter_state.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can pre-allocate this slice with the correct capacity.
</blockquote></details>

Done
___
*[`pkg/sql/crdb_internal.go` line 9596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uKwe43oAt2iEtxp3O:-OAJIy6a7KUKNNWC5w8H:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaf1750511b984e7ccea166e7a48d43df6b7c487/pkg/sql/crdb_internal.go#L9596)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use `TimestampToInexactDTimestamp` here?
</blockquote></details>

Done
___
*[`pkg/cli/zip_test.go` line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-O9uL8ID4bmoZFs_1jrl:-OAJJCDo85XfXCHz16Ka:b-bucoi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaf1750511b984e7ccea166e7a48d43df6b7c487/pkg/cli/zip_test.go#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: what's up with the indentation in this test?
</blockquote></details>

It's tabs vs two spaces. I converted the few stragglers to tabs. But it might be something `--rewrite` does.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132252#-:-OAJOlHsAzFh_cpdN9as:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @arulajmani, @iskettaneh, @mgartner, and @xinhaoz)

**Comment by miraradeva** [comment]
bors r=nvanbenschoten

**Pull request merged**
