### PR TITLE
sql: introduce SET ROLE 

### LINKED ISSUE #15005: sql: enable changing the current user of a session with SET ROLE
Add support for the [`SET ROLE`](https://www.postgresql.org/docs/13/static/sql-set-role.html) command and variants from PostgreSQL. This command sets or resets the user for the current session.

This should also support `SET LOCAL ROLE`, which changes the role just for the current transaction. This is related to, but not dependent on `SET LOCAL` for session variables: #32562

At least one client, Flyway, requires support for this syntax. Graphile uses this too.

Epic CRDB-7217

### PR DESCRIPTION
**Pull request by otan**
Release justification: low risk, high reward change

Release note (sql change): This commit introduces `SET ROLE`, which
allows users with certain permissions to assume the identity of another
user. It is worth noting that due to cross-version compatibility,
`session_user` will always return the same as `current_user` until
v22.1. Instead, use `session_user()` if you require this information.

Resolves #15005

### CODE REVIEW

**Comment by otan** [comment]
hmm, i have the permissions checks for these all wrong. will fix it later.

**Comment by otan** [comment]
this is good to review.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/exec_util.go, line 2422 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVWVgY8XpDVLJXcnVu:-MhVWVgZ9YsIcWbYnHCv:b-ycxx9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/exec_util.go#L2422)):*
> ```Go
> }
> 
> func (m *sessionDataMutator) SetRole(ctx context.Context, pc permissionsChecker, s string) error {
> ```

can `s` be a `security.SQLUsername` so that it's normalzed earlier?

specifically, what happens if the value of `s` is `NoNe`? the `if s == security.NoneRole` check will fail it seems
___
*[pkg/sql/exec_util.go, line 2454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVXAko-UXEPa2oB5FV:-MhVXAko-UXEPa2oB5FW:b-jxlru5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/exec_util.go#L2454)):*
> ```Go
> 		if !exists {
> 			return pgerror.Newf(
> 				pgcode.UndefinedObject,
> ```

postgres returns `InvalidParameterValue` for this
___
*[pkg/sql/vars.go, line 1000 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVXKhO42NWcJQrFqoN:-MhVXKhO42NWcJQrFqoO:byhawq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/vars.go#L1000)):*
> ```Go
> 	},
> 
> 	// See https://www.postgresql.org/docs/current/sql-set-role.html.
> ```

do you think we should modify the `SetVar` formatting logic so that it capitalizes `ROLE`? if so, add a ParseDataDriven test

also, just curious about the decision to implement this as a session variable rather than as a separate command (it seems Postgres has a separate SET ROLE command?)
___
*[pkg/sql/vars.go, line 1001 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVVN1U8wxLq2secDJW:-MhVVN1VD9kY-M6ZSWCh:btdxhov) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/vars.go#L1001)):*
> ```Go
> 
> 	// See https://www.postgresql.org/docs/current/sql-set-role.html.
> 	`role`: {
> ```

could you add `role` as one of the variables disallowed to be configured using `ALTER ROLE ... SET`

here: https://github.com/cockroachdb/cockroach/blob/fa40263413d8abe3b5780f47970b97c91f384140/pkg/sql/alter_role.go#L417-L421
___
*[pkg/sql/logictest/testdata/logic_test/set_role, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVYiwY82szVAjLE-bs:-MhVYiwY82szVAjLE-bt:b-86zjwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/logictest/testdata/logic_test/set_role#L200)):*
> ```
> # Revoke admin but give testuser privileges for testuser2.
> # Make a testrole role.
> # Check testuser2 can become testuser and testrole as they are still
> ```

maybe too edge casey to worry about ... but what happens if `user_a` is an admin, then becomes `user_b`, and then admin is revoked from `user_a`. i'm guessing PG doesn't auto-undo the SET ROLE? but then at this point can you still do `SET ROLE `user_a` successfully?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/exec_util.go, line 2422 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVWVgY8XpDVLJXcnVu:-MhVgYC3Cf12kB_ET9sy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/exec_util.go#L2422)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can `s` be a `security.SQLUsername` so that it's normalzed earlier?

specifically, what happens if the value of `s` is `NoNe`? the `if s == security.NoneRole` check will fail it seems
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 2454 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVXAko-UXEPa2oB5FV:-MhVgwh-0aGhoQx8ug2S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/exec_util.go#L2454)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

postgres returns `InvalidParameterValue` for this
</blockquote></details>

Done.
___
*[pkg/sql/vars.go, line 1000 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVXKhO42NWcJQrFqoN:-MhVgz8tDblmsZXj1pFY:bsrvkqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/vars.go#L1000)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you think we should modify the `SetVar` formatting logic so that it capitalizes `ROLE`? if so, add a ParseDataDriven test

also, just curious about the decision to implement this as a session variable rather than as a separate command (it seems Postgres has a separate SET ROLE command?)
</blockquote></details>

i'm not sure it does.
i don't think postgres has a separate SET ROLE command, it treats it like a `var`.
___
*[pkg/sql/vars.go, line 1001 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVVN1U8wxLq2secDJW:-MhVk0EX1eA3CaqX4r-7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/vars.go#L1001)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add `role` as one of the variables disallowed to be configured using `ALTER ROLE ... SET`

here: https://github.com/cockroachdb/cockroach/blob/fa40263413d8abe3b5780f47970b97c91f384140/pkg/sql/alter_role.go#L417-L421
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/set_role, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVYiwY82szVAjLE-bs:-MhVkpBU-8X15b8kTftr:b-p9abli) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/logictest/testdata/logic_test/set_role#L200)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe too edge casey to worry about ... but what happens if `user_a` is an admin, then becomes `user_b`, and then admin is revoked from `user_a`. i'm guessing PG doesn't auto-undo the SET ROLE? but then at this point can you still do `SET ROLE `user_a` successfully?
</blockquote></details>

just tested, pg doesn't reset the role, and you can no longer do `set role user_a`. added a test.

**Review by ajwerner — COMMENTED** [review]
Nothing major from me. 

> Reviewed 2 of 5 files at r2, 1 of 16 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-:-MhWApbh65hAlznsYJuu:b33916p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/exec_util.go, line 2422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhWACh89tur5O5N0obn:-MhWACh89tur5O5N0obo:b-td99l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/exec_util.go#L2422)):*
> ```Go
> }
> 
> func (m *sessionDataMutator) SetRole(
> ```

Could I request some commentary here that talks about the `SessionUserProto` and its relationship to `UserProto`? 
___
*[pkg/sql/exec_util.go, line 2502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhW8f6e--QCoHHeqAtn:-MhW8f6e--QCoHHeqAto:bvb5qn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/exec_util.go#L2502)):*
> ```
> 
> 	if sessionUser.IsRootUser() {
> ```
does this let you become `node`? That thing is more powerful than root. I'm not sure how I feel about making it easy for `root` to become `node`. 
___
*[pkg/sql/vars.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhWA_tkBLhjgKS34MS2:-MhWA_tkBLhjgKS34MS3:b3wvjsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/vars.go#L59)):*
> ```
> // permissionsCheck contains permissions checks which are needed for SET ROLE.
> type permissionsChecker interface {
> 	MemberOfWithAdminOption(
> ```
do y'all ever dream of package boundaries around these sorts of things?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

___
*[pkg/sql/exec_util.go, line 2422 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhWACh89tur5O5N0obn:-MhWPN8k2EtMyTXizmyA:bm4tm2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/exec_util.go#L2422)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Could I request some commentary here that talks about the `SessionUserProto` and its relationship to `UserProto`? 
</blockquote></details>

added a comment here, the protobuf variable has more commentary.
___
*[pkg/sql/exec_util.go, line 2502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhW8f6e--QCoHHeqAtn:-MhWOyvi0xzwRJpqg2V8:bat33is) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/exec_util.go#L2502)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 	if sessionUser.IsRootUser() {
> ```
does this let you become `node`? That thing is more powerful than root. I'm not sure how I feel about making it easy for `root` to become `node`. 
</blockquote></details>

does node exist? i don't see it in `system.roles`

```
root@127.0.0.1:26257/movr> set role node;
ERROR: role node does not exist
SQLSTATE: 22023
```
___
*[pkg/sql/vars.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhWA_tkBLhjgKS34MS2:-MhWPdtc26pmWRyZ4wIL:b44u3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/vars.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // permissionsCheck contains permissions checks which are needed for SET ROLE.
> type permissionsChecker interface {
> 	MemberOfWithAdminOption(
> ```
do y'all ever dream of package boundaries around these sorts of things? 
</blockquote></details>

🙃

**Comment by otan** [comment]
found a way of doing this without needing that new `permissionsChecker` interface.

**Review by rafiss — APPROVED** [review]
just a small comment but this looks good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-:-Mhn_fN59rOCeARUkGVS:b-gov8rn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @rafiss)

___
*[pkg/sql/exec_util.go, line 2502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhW8f6e--QCoHHeqAtn:-MhnZe3YADv_2GlKJ2nl:b-mx2sa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1ace70003e1f45e41360ccc397c6d62ca56fcb/pkg/sql/exec_util.go#L2502)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does node exist? i don't see it in `system.roles`

```
root@127.0.0.1:26257/movr> set role node;
ERROR: role node does not exist
SQLSTATE: 22023
```
</blockquote></details>

`node` is a magic pseudo-role, and so is `public`. https://github.com/cockroachdb/cockroach/blob/108c410b342ad6a79a67f19bfd0fea06f6313329/pkg/security/username.go#L96

 as long as the `set role` implementation works by consulting the system table, it wouldn't allow you to become those roles, but maybe worth adding a test or special-casing them.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @rafiss)

___
*[pkg/sql/vars.go, line 1000 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhVXKhO42NWcJQrFqoN:-Mhna5g_-3rkl5vzngFt:b-lcaadr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d46cae0f9c6c331d52b67473108cb79df937e380/pkg/sql/vars.go#L1000)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i'm not sure it does.
i don't think postgres has a separate SET ROLE command, it treats it like a `var`.
</blockquote></details>

i see. i just saw that it got its own page: https://www.postgresql.org/docs/current/sql-set-role.html

so from the parser perspective, i think it still would be useful to add a ParseDataDriven test for:
- the `ROLE` token is capitalized
- don't need a `=` or `TO` token in the `SET ROLE username` command

**Review by ajwerner — APPROVED** [review]
Commentary nits from me. Otherwise :lgtm: 

> Reviewed 3 of 27 files at r6, 2 of 14 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-:-MhncQtiCRDidDuDf-7v:b31glzw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @otan, and @rafiss)

___
*[pkg/sql/user.go, line 461 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhncLDv2XXx_91ixQ4W:-MhncLDv2XXx_91ixQ4X:b6ojas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f99178401e9df1ae3fe41c206056d3258c54371/pkg/sql/user.go#L461)):*
> ```Go
> 	// Buffer the ParamStatusUpdate.
> 	updateStr := "off"
> 	willBecomeAdmin, err := p.UserHasAdminRole(ctx, becomeUser)
> ```

If we're already an admin, should we be sending this? 
___
*[pkg/sql/user.go, line 470 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-Mhnb5w2Byhhah1v410o:-Mhnb5w2Byhhah1v410p:btwaroc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f99178401e9df1ae3fe41c206056d3258c54371/pkg/sql/user.go#L470)):*
> ```Go
> 	m.paramStatusUpdater.BufferParamStatusUpdate("is_superuser", updateStr)
> 
> 	// The "none" user does a reset if we are in a SET ROLE.
> ```

Is this `reset` terminology defined anywhere? Could we make it a method on the `sessionDataMutator` and put some nice commentary on that method?
___
*[pkg/sql/user.go, line 478 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhncGMI4JHmozp9AzOM:-MhncGMI4JHmozp9AzON:b-3km9ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f99178401e9df1ae3fe41c206056d3258c54371/pkg/sql/user.go#L478)):*
> ```Go
> 		return nil
> 	}
> ```

Should we short-circuit in the case where we're becoming ourself? 
___
*[pkg/sql/sessiondata/session_data.go, line 129 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhnbeWo5B0yEXVB71QZ:-MhnbeWo5B0yEXVB71Q_:btivzl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f99178401e9df1ae3fe41c206056d3258c54371/pkg/sql/sessiondata/session_data.go#L129)):*
> ```Go
> }
> 
> // SessionUser retrieves the session_user.
> ```

This feels like a nice place to reiterate the distinction between `SessionUser` and `User`. 
___
*[pkg/sql/sessiondatapb/session_data.go, line 111 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68973#-MhnbmpxAM5VmVOUQ9_D:-MhnbmpxAM5VmVOUQ9_E:b-fwkpq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f99178401e9df1ae3fe41c206056d3258c54371/pkg/sql/sessiondatapb/session_data.go#L111)):*
> ```Go
> }
> 
> // User retrieves the current user.
> ```

Given this change, it's probably worth a sentence pointing out that `SessionUser` exists and is distinct from this user. I have a feeling that in general you want to use this and not that. Commenting both places with hints feels valuable.

**Comment by otan** [comment]
bors r=rafiss,ajwerner

**Pull request merged**
