### PR TITLE
distsql: implement router by mirror

### PR DESCRIPTION
**Pull request by irfansharif**
Implementation of MIRROR router, distributes rows to multiple streams so
all rows end up in all streams.

Part of #7588

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9039)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Cool! Some comments, nothing major.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/routers.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQb7eTyA7lkyMxk04Hc:-KQb7eTyA7lkyMxk04Hd:b-jfo5im) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers.go#L98)):*
> ```Go
> 	// unnecessary.
> 	for _, s := range mr.streams {
> 		s.PushRow(row)
> ```

The documentation for PushRow states: `The sender must not use the row anymore after calling this function.`

I think we can change the model to support this as written though. We should say for `RowReceiver.PushRow()` that "The sender must not modify the row after calling", and for `RowSource.NextRow()` that the caller isn't allowed to modify the received row.

---

*[sql/distsql/routers_test.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbBeIhuvBiw_r-ZB4G:-KQbBeIhuvBiw_r-ZB4H:bu755ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers_test.go#L118)):*
> ```Go
> 	vals := sqlbase.RandEncDatumColumns(rng, numCols, numRows)
> 
> 	testCases := []struct {
> ```

Don't leave stuff like this if it's not doing anything useful, just do `for numBuckets := 1; numBuckets <= 3; numBuckets++ {}`

---

*[sql/distsql/routers_test.go, line 150 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbA7g8zU9J3sVw-y5I:-KQbA7g8zU9J3sVw-y5J:b3p81fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers_test.go#L150)):*
> ```Go
> 		mr.Close(nil)
> 
> 		// Verify each row is sent to each of the output streams.
> ```

In the test above, we were checking something more complicated. Here we just need to:
 - check that all the bufs have the same amount of rows
 - check that row i is the same across all bufs, e.g. just compare with `bufs[0].rows[i]`

---

*[sql/sqlbase/testutils.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbAfPemC6D6b-SSf4e:-KQbAfPemC6D6b-SSf4f:b1kdj71) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/sqlbase/testutils.go#L140)):*
> ```Go
> // RandEncDatumColumns generates EncDatum columns with random values, each
> // column with a single random type.
> func RandEncDatumColumns(rng *rand.Rand, numCols, numRows int) [][]EncDatum {
> ```

The "column" terminology here is confusing.  `[][]EncDatum` is a matrix with numCols rows and numRows columns :)

I would use Set/Sets instead of Column (RandEncDatumSet generates a set of EncDatum values of the same random type). And here we would have numSets, numValsPerSet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-:-KQb8qq3MCL19R-eJs9m:b-1g5v01)*

**Comment by irfansharif** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/distsql/routers.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbGLSGclICCn9-mQFD:-KQbGLSGclICCn9-mQFE:b-jqmxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers.go#L104)):*
> ```Go
> 
> // Close is part of the RowReceiver interface.
> func (mr *mirrorRouter) Close(err error) {
> ```

here i noticed that the `Close` method is identical to the one for `hashRouter` and likely will be the same for `rangeRouter`,  for each type the fields `streams` and `err` are common. don't know if idiomatic to Go but i was thinking the extract to commonalities to a `router` type and embedding that into each of the `mirrorRouter`, `hashRouter` and `rangeRouter` type with the `Close` method attached to `router` directly. thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/distsql/routers.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbGLSGclICCn9-mQFD:-KQbLOVCpZ68hYc_CU3h:b-874hxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers.go#L104)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> here i noticed that the `Close` method is identical to the one for `hashRouter` and likely will be the same for `rangeRouter`,  for each type the fields `streams` and `err` are common. don't know if idiomatic to Go but i was thinking the extract to commonalities to a `router` type and embedding that into each of the `mirrorRouter`, `hashRouter` and `rangeRouter` type with the `Close` method attached to `router` directly. thoughts?
</details>
Makes sense, we do this quite a bit. Usually the name would be `routerBase`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by irfansharif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/distsql/routers.go, line 98 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQb7eTyA7lkyMxk04Hc:-KQbfx8tLJ9w_KobmP5c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers.go#L98)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The documentation for PushRow states: `The sender must not use the row anymore after calling this function.`
> 
> I think we can change the model to support this as written though. We should say for `RowReceiver.PushRow()` that "The sender must not modify the row after calling", and for `RowSource.NextRow()` that the caller isn't allowed to modify the received row.
</details>
Done.

---

*[sql/distsql/routers.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbGLSGclICCn9-mQFD:-KQbQAzPlQHObHjAuBiV:bg520qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Makes sense, we do this quite a bit. Usually the name would be `routerBase`
</details>
perfect, thought as much. added.

---

*[sql/distsql/routers_test.go, line 118 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbBeIhuvBiw_r-ZB4G:-KQbQdu5st6t4q88gVhL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers_test.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Don't leave stuff like this if it's not doing anything useful, just do `for numBuckets := 1; numBuckets <= 3; numBuckets++ {}`
</details>
Done.

---

*[sql/distsql/routers_test.go, line 150 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbA7g8zU9J3sVw-y5I:-KQbYYiCYx0Y98qqSIfQ:bba2h23) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/distsql/routers_test.go#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> In the test above, we were checking something more complicated. Here we just need to:
>  - check that all the bufs have the same amount of rows
>  - check that row i is the same across all bufs, e.g. just compare with `bufs[0].rows[i]`
</details>
agreed, done.

---

*[sql/sqlbase/testutils.go, line 140 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQbAfPemC6D6b-SSf4e:-KQbe7b-TPEtWRRgYy0u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e84cf1060cd2dc5080b0df5ecdf9b944efe57d15/sql/sqlbase/testutils.go#L140)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The "column" terminology here is confusing.  `[][]EncDatum` is a matrix with numCols rows and numRows columns :)
> 
> I would use Set/Sets instead of Column (RandEncDatumSet generates a set of EncDatum values of the same random type). And here we would have numSets, numValsPerSet
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/distsql/routers.go, line 72 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQcY_2xkxXkWxwldpkz:-KQcY_2xkxXkWxwldpl-:b-e2cg68) ([raw file](https://github.com/cockroachdb/cockroach/blob/129772ee58f1327e38f4a0dcbf24ddf703ee5b23/sql/distsql/routers.go#L72)):*
> ```Go
> 
> var crc32Table = crc32.MakeTable(crc32.Castagnoli)
> ```

[nit] We shouldn't interleave the code for one type with the code for the other for no reason (it makes the code harder to read). The routerBase methods should come first.

---

*[sql/distsql/routers_test.go, line 151 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQcYwdhaA--pMU7E29x:-KQcYwdhaA--pMU7E29y:b-w1vq2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/129772ee58f1327e38f4a0dcbf24ddf703ee5b23/sql/distsql/routers_test.go#L151)):*
> ```Go
> 				t.Errorf("buckets %d and %d have different number of rows", 0, bIdx)
> 			}
> 			if !b.closed {
> ```

these two checks should come before `if bIdx == 0 { continue }`

---

*[sql/distsql/routers_test.go, line 163 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQcZ7Y8zUk0XeQc8TVj:-KQcZ7Y8zUk0XeQc8TVk:b-p17xio) ([raw file](https://github.com/cockroachdb/cockroach/blob/129772ee58f1327e38f4a0dcbf24ddf703ee5b23/sql/distsql/routers_test.go#L163)):*
> ```Go
> 
> 				equal := true
> 				for j, c := range row {
> ```

The router is supposed to send all the rows in the same order.. So row j of `buf[0]` should be the same with row `j` of `buf[i]` no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by irfansharif** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/distsql/routers_test.go, line 163 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQcZ7Y8zUk0XeQc8TVj:-KQddyWgHpbXSdSDvx02:b-6mq4qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/129772ee58f1327e38f4a0dcbf24ddf703ee5b23/sql/distsql/routers_test.go#L163)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> The router is supposed to send all the rows in the same order.. So row j of `buf[0]` should be the same with row `j` of `buf[i]` no?
</details>
`j` here is the 'column' number, i'm simply comparing each datum in each row of `buf[i]` with the corresponding row `buf[0]` (and the corresponding datums).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks, that was very quick! :)

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/distsql/routers_test.go, line 163 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQcZ7Y8zUk0XeQc8TVj:-KQf0vPNnMGp8eelDrHd:be8pf18) ([raw file](https://github.com/cockroachdb/cockroach/blob/129772ee58f1327e38f4a0dcbf24ddf703ee5b23/sql/distsql/routers_test.go#L163)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> `j` here is the 'column' number, i'm simply comparing each datum in each row of `buf[i]` with the corresponding row `buf[0]` (and the corresponding datums).
</details>
Ah, duh, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-:-KQf128gK31WnFJcOybl:b-riyrm3)*

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r2, 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/testutils.go, line 130 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQfBYYQ6GOB6UVICoia:-KQfBYYRp9KIEjzcfg8a:b-4sikui) ([raw file](https://github.com/cockroachdb/cockroach/blob/5728b98f9cceb39b6d9bddc3513a33329534458b/sql/sqlbase/testutils.go#L130)):*
> ```Go
> // RandEncDatumSet generates a set of random EncDatum values of the same random
> // type.
> func RandEncDatumSet(rng *rand.Rand, numVals int) []EncDatum {
> ```

s/Set/Slice/g? `set` might mean something different to future readers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by irfansharif** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/testutils.go, line 130 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQfBYYQ6GOB6UVICoia:-KQfI7Smy2J6EiXW43-0:bern2k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5728b98f9cceb39b6d9bddc3513a33329534458b/sql/sqlbase/testutils.go#L130)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/Set/Slice/g? `set` might mean something different to future readers.
</details>
i'd prefer `set` here, context being simply the collection of `EncDatum`s. also was suggested following discussion [here](https://github.com/cockroachdb/cockroach/pull/9039#issuecomment-244184305).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by tamird** [comment]
I'll leave it up to @raduberinde, but "set" implies non-duplication to me.

**Comment by RaduBerinde** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/sqlbase/testutils.go, line 130 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQfBYYQ6GOB6UVICoia:-KQfMs2x4lclCwlmJ5YT:b5bmyiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5728b98f9cceb39b6d9bddc3513a33329534458b/sql/sqlbase/testutils.go#L130)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> i'd prefer `set` here, context being simply the collection of `EncDatum`s. also was suggested following discussion [here](https://github.com/cockroachdb/cockroach/pull/9039#issuecomment-244184305).
</details>
Slice is even better. Note that if you use vim (with vim-go plugin) you can do :GoRename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by irfansharif** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/sqlbase/testutils.go, line 130 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-KQfBYYQ6GOB6UVICoia:-KQfSzzVIXYFZl0NH-8D:bkeylhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5728b98f9cceb39b6d9bddc3513a33329534458b/sql/sqlbase/testutils.go#L130)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Slice is even better. Note that if you use vim (with vim-go plugin) you can do :GoRename.
</details>
cool, updated to `RandEncDatumSlice` and `RandEncDatumSlices`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9039#-:-KQfTZQk6pEM7R5yEtXi:bnfp4nl)*

**Pull request merged**
