### PR TITLE
opt: don't disallow ExplainDistSQL for subqueries

### PR DESCRIPTION
**Pull request by rjnn**
Subqueries are now supported, so show the DistSQL plan diagrams, even
though the plan will only show the outer plans with the subqueries
evaluated.

This will need a backport.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
This might need some tests. Are there no conditions later in that code that expect there to be no subqueries?

**Review by rjnn — COMMENTED** [review]
I added some tests, but there aren't consistent results for each test across opt versions. I think this is gated on fixing #29350, since the non-opt versions of the tests show the subquery results, but the opt versions say <unknown>. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29353#-:-LLBDjnf8HQ1rkN6BJX6:bqrgf4j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by arjunravinarayan** [comment]
Sorry, I didn't add tests to this PR, I wrote some locally and observed that failure mode.

**Comment by jordanlewis** [comment]
Ah... in that case can you just make them `statement ok` tests with a `TODO` that's gated on that issue? I'd just like to make sure we're not panicking and that we don't regress here.

**Review by rjnn — COMMENTED** [review]
No I'd bork existing tests and have to revert them as well. I guess I could make a new testfile, but I'm fine holding this PR open until that issue progresses.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29353#-:-LLBGYeh7A0S-oAWB50q:b-gw9bbd)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
👋 hey Arjun! This is stale and got superseded by something else, so I'm closing it. Cheers! 🍻

**Pull request closed without merging**
