### PR TITLE
*: format maybe-nil errors as %v

### PR DESCRIPTION
**Pull request by tamird**
This produces "<nil>" rather than "%!s(<nil>)".

PRing to master because this is a test-only change and affects workflow (so I'd like it to be on both branches).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8661)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/logic_test.go, line 780 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU40OhNdm9ExT_lqQ1:-KPU40OhNdm9ExT_lqQ2:b-igan7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/sql/logic_test.go#L780)):*
> ```Go
> 		return t.unexpectedError(sql, pos, err)
> 	}
> 	if !(expectErr == "" && err == nil || testutils.IsError(err, expectErr)) {
> ```

Why the change here? I think the idea is that we could have only one of `expectErr` or `expectErrCode` set, and we verify the error matches whichever is set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by bdarnell** [comment]
-1 on applying this to master. It's such a minor improvement that it can either go on develop or wait until after the code yellow.

**Comment by arjunravinarayan** [comment]
Reviewed 26 of 28 files at r1.
Review status: 26 of 28 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[keys/keys_test.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU6LFnOJjsD3dCY9eK:-KPU6LFovWwIW-ghrYNS:b-yv00vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/keys/keys_test.go#L232)):*
> ```Go
> 
> 		if err != nil && !testutils.IsError(err, test.expError) {
> 			t.Errorf("expected error: %s ; got %v", test.expError, err)
> ```

shouldn't `%s` suffice here? We know `err != nil`, and according to your change to `STYLE.md`, that is the only condition where an elevation to `%v` is required.

---

*[kv/db_test.go, line 202 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU6Y8QP8WPmWNfBvkg:-KPU6Y8QP8WPmWNfBvkh:b-ul6adb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/kv/db_test.go#L202)):*
> ```Go
> 			t.Errorf("%d: unexpected success calling %s", i, args.Method())
> 		} else if !testutils.IsError(err, "contains an internal request|contains commit trigger") {
> 			t.Errorf("%d: unexpected error for %s: %v", i, args.Method(), err)
> ```

Same here as above (and in many situations below where we know that `err != nil`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by dt** [comment]
I'd almost rather always print unexpected (test) errs with `%+v` to get stacks as we use pkg/errors more.

**Comment by tamird** [comment]
Review status: 26 of 28 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[keys/keys_test.go, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU6LFnOJjsD3dCY9eK:-KPUGDlrrwQUwcAtz14t:b-a4y9ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/keys/keys_test.go#L232)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary>
> shouldn't `%s` suffice here? We know `err != nil`, and according to your change to `STYLE.md`, that is the only condition where an elevation to `%v` is required.
</details>
Good eye. Updated.

---

*[kv/db_test.go, line 202 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU6Y8QP8WPmWNfBvkg:-KPUHZUCinSZxAZLvelY:bkxfr98) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/kv/db_test.go#L202)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary>
> Same here as above (and in many situations below where we know that `err != nil`).
</details>
This is the only change in this file - what other situations are you referring to?

---

*[sql/logic_test.go, line 780 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU40OhNdm9ExT_lqQ1:-KPUHRSdtAqwDd9_VRWM:b-ju2q9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/sql/logic_test.go#L780)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Why the change here? I think the idea is that we could have only one of `expectErr` or `expectErrCode` set, and we verify the error matches whichever is set.
</details>
Based on usage, that doesn't seem to be the case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by arjunravinarayan** [comment]
Reviewed 2 of 2 files at r2.
Review status: 26 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[kv/txn_coord_sender_test.go, line 1283 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPUIJQNn5UdMrytyCMk:-KPUIJQOhICVfFK9Oih6:b-a3l4xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee42d3b0bec9cc91806669948bdb8c110dff94e/kv/txn_coord_sender_test.go#L1283)):*
> ```Go
> 			t.Fatalf("Get succeeded on abandoned txn")
> 		} else if !testutils.IsError(err, "writing transaction timed out") {
> 			t.Fatalf("unexpected error from Get on abandoned txn: %v", err)
> ```

`err != nil` here, so `%v not required`.

---

*[storage/store_pool_test.go, line 565 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPUIYQOGj4FBEg1a_Wk:-KPUIYQOGj4FBEg1a_Wl:b6v4job) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee42d3b0bec9cc91806669948bdb8c110dff94e/storage/store_pool_test.go#L565)):*
> ```Go
> 			t.Errorf("%d: expected an error:%s, got none", i, testCase.expErr)
> 		} else if !testutils.IsError(err, testCase.expErr) {
> 			t.Errorf("%d: expected error:%s, actual:%v", i, testCase.expErr, err)
> ```

`err != nil` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by RaduBerinde** [comment]
Review status: 26 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/logic_test.go, line 780 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU40OhNdm9ExT_lqQ1:-KPUJQ9MvhZ2PCJIgP1h:bshgwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/sql/logic_test.go#L780)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Based on usage, that doesn't seem to be the case.
</details>
Then remove the `expectErrCode == ""` check from the previous `if`. Then we can just do `if testutils.IsError()` here.
Could also panic if expectErr is "" and expectErrCode is not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by tamird** [comment]
Review status: 24 of 28 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[kv/txn_coord_sender_test.go, line 1283 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPUIJQNn5UdMrytyCMk:-KPUKkzO3bmxwyh6wMxt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee42d3b0bec9cc91806669948bdb8c110dff94e/kv/txn_coord_sender_test.go#L1283)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary>
> `err != nil` here, so `%v not required`.
</details>
Done.

---

*[sql/logic_test.go, line 780 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPU40OhNdm9ExT_lqQ1:-KPUM0hVjUyen6NpXkRs:bqh96sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf78ec79a5eda45ef9ff4e85b4e8f056a354ebd7/sql/logic_test.go#L780)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Then remove the `expectErrCode == ""` check from the previous `if`. Then we can just do `if testutils.IsError()` here.
> Could also panic if expectErr is "" and expectErrCode is not.
</details>
Done...sort of.

---

*[storage/store_pool_test.go, line 565 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-KPUIYQOGj4FBEg1a_Wk:-KPUKoGs-Mf-uwDQqX3K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee42d3b0bec9cc91806669948bdb8c110dff94e/storage/store_pool_test.go#L565)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary>
> `err != nil` here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 24 of 28 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-:-KPUNrzM4CDhdHSGTDE_:bnfp4nl)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 28 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8661#-:-KPUOF2nVeazInT6t3PT:bnfp4nl)*

**Pull request merged**
