### PR TITLE
kvstreamer: improve behavior when responses vary in size

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: create Results for empty Get responses**

We recently merged a change to skip Get responses that came back empty
(because there is no corresponding key found) in the `Streamer` which
cleaned up some code. However, for the upcoming work on the `InOrder`
mode the `Streamer` needs to know about such responses. We could
introduce a separate tracking mechanism for empty Get responses and
continue not emitting them, but that seems like unnecessary complication
to the code, so this commit, instead, restores the creation of Results
for empty Get responses.

Additionally it fixes a nit in the test where we hard-code the table ID
(table IDs recently have changed a bit).

Release note: None

**colfetcher: fix memory limiting in the ColIndexJoin**

`ColIndexJoin` operator carefully measures the footprint of the input
rows that it uses to generate spans to lookup. It wants to find the
largest number of rows that have the total footprint not exceeding the
target size (4MiB or a quarter of `workmem`, whichever is smaller), but
always it includes at least one row into the "input batch". Previously,
it incorrectly could include an extra row when the limit is reached
because we incorrectly determined whether any rows are already included
into the input batch (essentially we always thought "no"). This commit
fixes this problem.

Release note: None

**kvstreamer: fix a couple of bugs**

This commit fixes a rare concurrency bug where the newly enqueued
requests could be incorrectly sliced off. This could occur because it is
possible for a request to be issued asynchronously, responded to,
returned to the client before the deferred function in
`issueRequestsForAsyncProcessing` is executed. For the time being the
fix is to just append the newly-enqueued requests to the old ones, but
the follow-up work on the `InOrder` mode will clean this up properly.

Additionally, this commit fixes another deadlock that could occur
whenever the last request in flight returns without creating any results
and the worker coordinator is waiting for more budget at the same time.
Previously, it was possible for the signal on the condition variable to
be missed by the worker coordinator, so it could wait forever.

There are no explicit regression tests for these bugs because they are
exercised by the improved testing in the following commit.

Release note: None

**kvstreamer: improve behavior when responses vary in size**

This commit improves the behavior of the `Streamer` when the responses
vary in size significantly. Previously, we could get into a situation
when the `Streamer` issues many requests that come back with empty
responses because `TargetBytes` limit is too small. This can be the case
when some small responses come back first making our estimate for the
average response size to be too small, and we later would use that
estimate to set the `TargetBytes` limit on the new requests. If those
new requests have large responses, we would keep getting empty responses
until a request becomes the "head-of-the-line" (we could issue hundreds
of such requests that would receive empty response).

This behavior is now fixed by utilizing `ResumeNextBytes` hint from the
KV layer about the size of the next KV pair. The KV layer on
a best-effort basis provides this hint whenever it cannot fulfill the
request fully. If a particular request keeps getting an empty response,
we ensure that it is always issued with a larger `TargetBytes` limit
every time.

This commit additionally adds some `Printf` statements hidden behind
a constant `debug=false` flag. I want to keep this in code for the time
being since it's been very helpful during the debugging. Since it's
a compile time constant set to `false`, it should have no performance
impact.

In order to verify that the `Streamer` does, in fact, make a reasonable
number of KV requests, an existing test has been refactored and
extended. In particular, it now looks at the trace of the query and
counts how make async requests are issued by the `Streamer`.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First commit is #76641.

**Comment by yuzefovich** [comment]
Apologies for all the pushing. I think I figured out the failures, so this is RFAL.

**Review by rharding6373 — CHANGES_REQUESTED** [review]
Nice work!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r4, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-:-MwDEH_M04fzij_T_td_:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwCxmjmCdRAizTSeDcZ:-MwCxmjmCdRAizTSeDc_:b-khztej) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca93e4b065e3e6fddf38f9f3670605cc5bc7410/pkg/kv/kvclient/kvstreamer/streamer.go#L1334)):*
> ```Go
> // average response size, and telling the Streamer about these results.
> //
> // This method assumes that results has length greater than zero.
> ```

nit: add a warning or error if it is 0
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 559 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwD2smQ0CgpK5Y-TCRt:-MwD2smR-JdJzIVjzVla:bn27m8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0da774e3df3fdf26c004b803457011a44db3e25/pkg/kv/kvclient/kvstreamer/streamer.go#L559)):*
> ```Go
> 	// responded to, returned to the client before the deferred function in
> 	// issueRequestsForAsyncProcessing is executed.
> 	// TODO(yuzefovich): clean this up.
> ```

Is the TODO still relevant? Seems relatively straightforward to me...
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 687 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwD3EgJAh8OhvBwZ599:-MwD3EgJAh8OhvBwZ59A:bfrolli) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0da774e3df3fdf26c004b803457011a44db3e25/pkg/kv/kvclient/kvstreamer/streamer.go#L687)):*
> ```Go
> 	if delta < 0 {
> 		// If we're decrementing the number of requests in flight, we want to
> 		// acquire the budget's mutex so that if we signal the budget below, it
> ```

minor nit: s/it/the worker coordinator
___
*[pkg/kv/kvclient/kvstreamer/large_keys_test.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwDDvhQ6Xhw3Bmkd1K3:-MwDDvhQ6Xhw3Bmkd1K4:b-lrhav7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96f2f3e5e1183a1eeb8e8f2dac3508ff2240414/pkg/kv/kvclient/kvstreamer/large_keys_test.go#L181)):*
> ```Go
> 									// we use a 4x multiple on the number of
> 									// rows.
> 									require.Greater(t, 4*numRows, numStreamerRequests)
> ```

This seems prone to flakiness. What is the point of checking for a "reasonable" number of requests? Is it always true that we will make at least `numRows` requests, so could we check that instead?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-:-MwDMrRw7MfXBHyZISaZ:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 559 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwD2smQ0CgpK5Y-TCRt:-MwDL2SSE6WlQRyW59R0:b-ypzoud) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0da774e3df3fdf26c004b803457011a44db3e25/pkg/kv/kvclient/kvstreamer/streamer.go#L559)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is the TODO still relevant? Seems relatively straightforward to me...
</blockquote></details>

It is still relevant and as I mention in the commit message it'll be addressed in the work on `InOrder` mode (there we'll introduce some abstractions that make addressing this TODO easier).
___
*[pkg/kv/kvclient/kvstreamer/large_keys_test.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-MwDDvhQ6Xhw3Bmkd1K3:-MwDM4iJ1MT2wh-l8AWZ:bawb8u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d96f2f3e5e1183a1eeb8e8f2dac3508ff2240414/pkg/kv/kvclient/kvstreamer/large_keys_test.go#L181)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This seems prone to flakiness. What is the point of checking for a "reasonable" number of requests? Is it always true that we will make at least `numRows` requests, so could we check that instead?
</blockquote></details>

The goal of this check is to enforce an upper bound. Before the fix in this commit for 20 rows we could have issued like 1000 requests out of which 950 would come back empty, so I do want to have an upper bound. The lower bound is not that interesting (as it would be 1 since in some cases it's possible to get all results in a single request when only small values happen to be generated). I've stressed this test overnight with no failures, so I don't think it should be flakey - there is already quite a bit of leeway in this 4x bound.

**Review by rharding6373 — APPROVED** [review]
Thanks for addressing the comments :-) :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76761#-:-MwDtDG2BCD8jAICRSiy:bx4w36e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

**Pull request merged**
