### PR TITLE
cli: add probe_range in debug.zip

### LINKED ISSUE #80360: cli: include probe_range in debug.zip
**Is your feature request related to a problem? Please describe.**

PR #79546 introduces `crdb_internal.probe_range`, but it won't be available during troubleshooting sessions unless included in a `debug.zip`.

**Describe the solution you'd like**

Include a query such as

```
SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL ‘1000ms’, ‘write’) WHERE error != '' ORDER BY end_to_end_latency DESC LIMIT 100;
```

(the `LIMIT` gives a very approximately ~1000ms*100 target on how long this can
take, so that running `debug.zip` against an unavailable cluster won't take too
long)

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-15754

### PR DESCRIPTION
**Pull request by j82w**
PR #79546 introduces `crdb_internal.probe_range`. This PR adds the `crdb_internal.probe_range` to the debug.zip. The LIMIT gives a very approximately ~1000ms*100 target on how long this can take, so that running debug.zip against an unavailable cluster won't take too long.

closes: #80360

Release note (cli change): The debug.zip now includes the `crdb_internal.probe_range` table with a limit of 100 rows to avoid the query from taking to long.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @j82w)

___
*[`pkg/cli/zip_table_registry.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNBPhK-M3usuTKzdBh:-NaNBPhK-M3usuTKzdBi:bt126ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L232)):*
> ```Go
> 	},
> 	"crdb_internal.probe_ranges_1s_write_limit_100": {
> 		customQueryRedacted: `SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'write') WHERE error != '' ORDER BY end_to_end_latency DESC LIMIT 100;
> ```

is this right? I'm on master and getting:

```
root@127.0.0.1:26257/movr> SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'write') WHERE error != '' ORDER BY
                        -> end_to_end_latency DESC LIMIT 100;
ERROR: column "end_to_end_latency" does not exist
```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @j82w)

___
*[`pkg/cli/zip_table_registry.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNCAqO7sIJJB0acpxW:-NaNCAqO7sIJJB0acpxX:bnjkt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L232)):*
> ```Go
> 	},
> 	"crdb_internal.probe_ranges_1s_write_limit_100": {
> 		customQueryRedacted: `SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'write') WHERE error != '' ORDER BY end_to_end_latency DESC LIMIT 100;
> ```

I don't see any columns getting marked as sensitive for this table, so you can use `customQueryUnredacted` here too

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @j82w)

___
*[`pkg/cli/zip_table_registry.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNCiR8DGeq-c6hrQZU:-NaNCiR8DGeq-c6hrQZV:b163wzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L231)):*
> ```Go
> 		FROM crdb_internal.cluster_settings`,
> 	},
> 	"crdb_internal.probe_ranges_1s_write_limit_100": {
> ```

I believe this should be just the name of the table, with no extra info, so no `1s_write_limit_100`

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/cli/zip_table_registry.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNCiR8DGeq-c6hrQZU:-NaNSy-78ys-gGJggb3l:bwo9ycb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L231)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I believe this should be just the name of the table, with no extra info, so no `1s_write_limit_100`
</blockquote></details>

In the case where no custom queries are defined, this [table name is used to construct the query](https://github.com/cockroachdb/cockroach/blob/fa33c28abd95f5c0c586484b99dedc5597356a94/pkg/cli/zip_table_registry.go#L92), so it indeed has to be the name of the actual table.

But, if you use custom queries, I don't think it has to be a real table name, because we return the custom query instead. In this case, the name would just be used as the filename that the output is written to.

But in that case, as noted in another comment below, you *also* need to define a `customQueryUnredacted`. Otherwise, the name [will be used to make a `TABLE` query](https://github.com/cockroachdb/cockroach/blob/fa33c28abd95f5c0c586484b99dedc5597356a94/pkg/cli/zip_table_registry.go#L76), which will error if the name doesn't match any real table.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @maryliag)

___
*[`pkg/cli/zip_table_registry.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNCiR8DGeq-c6hrQZU:-NaNSLaZ7IqR4HXGlJQJ:b-99kqox) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L231)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

In the case where no custom queries are defined, this [table name is used to construct the query](https://github.com/cockroachdb/cockroach/blob/fa33c28abd95f5c0c586484b99dedc5597356a94/pkg/cli/zip_table_registry.go#L92), so it indeed has to be the name of the actual table.

But, if you use custom queries, I don't think it has to be a real table name, because we return the custom query instead. In this case, the name would just be used as the filename that the output is written to.

But in that case, as noted in another comment below, you *also* need to define a `customQueryUnredacted`. Otherwise, the name [will be used to make a `TABLE` query](https://github.com/cockroachdb/cockroach/blob/fa33c28abd95f5c0c586484b99dedc5597356a94/pkg/cli/zip_table_registry.go#L76), which will error if the name doesn't match any real table.
</blockquote></details>

I did this on purpose to avoid confusion. Almost all the other tables in debug zip are select * without any constraints. People will assume that is the case for this information too which will cause confusion. Once they realize it's limited they will want to know how and by how much. I figured putting it in the table name made it very clear to everyone looking at the file what was actually in it.
___
*[`pkg/cli/zip_table_registry.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNBPhK-M3usuTKzdBh:-NaNT1ScC83zn3FCjuiD:b3a352m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L232)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this right? I'm on master and getting:

```
root@127.0.0.1:26257/movr> SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'write') WHERE error != '' ORDER BY
                        -> end_to_end_latency DESC LIMIT 100;
ERROR: column "end_to_end_latency" does not exist
```

</blockquote></details>

I meant to upload the PR as a draft.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/cli/zip_table_registry.go` line 231 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-NaNCiR8DGeq-c6hrQZU:-NaNar-i3ax6EswvohqZ:buppdd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aeadf31f2cf5662cb8991dab88a5997739c66e2/pkg/cli/zip_table_registry.go#L231)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

I did this on purpose to avoid confusion. Almost all the other tables in debug zip are select * without any constraints. People will assume that is the case for this information too which will cause confusion. Once they realize it's limited they will want to know how and by how much. I figured putting it in the table name made it very clear to everyone looking at the file what was actually in it.
</blockquote></details>

Gotcha! To clarify, I'm OK with that approach, we'll just need the `customQueryUnredacted` in that case :thumbsup:

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107720#-:-NaRiQiP4FUpg-Y-hHT3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Comment by joshimhoff** [comment]
I bet y'all are aware but `probe_ranges` recently had an egregious bug: https://github.com/cockroachdb/cockroach/issues/101549

Can I make a few requests, based on the postmortem that came out of ^^ (https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/2985951249)?

1. Can you get approval from KV regarding this PR? Probing is dangerous. Want to keep them in loop as owner of system under probe.
2. If backports, can you send review to KV?
3. Can you discuss any changes to system tests that we may need to make with KV too? This was a postmortem AI from the linked PM.

Thank you for considering!

**Comment by nvanbenschoten** [comment]
Thanks for bringing this to attention @joshimhoff. The change doesn't strike me as inherently dangerous, but I think this may be the first time we are introducing writes into the `debug.zip` process, meaning that it will now mutate the cluster that it is meant to observe. Is this risky? Maybe. Could it change the state of the cluster in ways that hide the artifacts we are trying to introspect? Maybe.

Did we consider using a read-only probe to start? Are there other parts of `debug.zip` which write to the cluster?

Independently, I don't know how debug.zip works, but I see that it runs SQL. Is the SQL query guaranteed to be executed by a node with a fix to https://github.com/cockroachdb/cockroach/issues/101549 if run in a mixed version cluster?

**Comment by joshimhoff** [comment]
> Independently, I don't know how debug.zip works, but I see that it runs SQL. Is the SQL query guaranteed to be executed by a node with a fix to https://github.com/cockroachdb/cockroach/issues/101549 if run in a mixed version cluster?

Great question. Isn't this debug zip code run on the CLI side? I think it is sorta common to run a new `cockroach CLI` against an old server. 

Moving to a read-only probe is a cheap fix to avoid needing to check that  https://github.com/cockroachdb/cockroach/issues/101549 is running on the server side. 

If we want to do write probes, I guess we could do a server version check somehow.

My soft preference is to do a read-only probes for now.

**Comment by joshimhoff** [comment]
Friendly poke, @j82w.

**Comment by j82w** [comment]
The read-only probe seems like a good idea. I'm not aware of other parts of `debug.zip` that writes to the cluster. I was just trying to improve observability by closing the issue: https://github.com/cockroachdb/cockroach/issues/80360. I wasn't aware there was a read-only option. Can you file an issue or send a PR to switch it to read-only?

**Comment by dhartunian** [comment]
@j82w to clarify a bit why Josh is concerned here:

The blast radius of the bug that led to https://github.com/cockroachdb/cockroach/issues/101549 was more or less contained because we only triggered that builtin ourselves on managed clusters. By running it as part of debug zip we expose all customers on older versions to this bug. Moreover, this would be via a command that we often **tell** customers to run. Could result in a bad outcome if someone uses a new CLI build to run on an older self-hosted cluster.

**Comment by dhartunian** [comment]
I put up a PR to modify: https://github.com/cockroachdb/cockroach/pull/108313

**Comment by j82w** [comment]
Thanks for the PR. I agree with your concerns. I'm not that familiar with this code, so I was looking for a consensus on if the correct solution was to revert the PR or was switch it to reads.

**Pull request merged**
