### PR TITLE
sql: Add precision to timestamp objects, with 6 as the default precision value

### PR DESCRIPTION
**Pull request by rohany**
This PR implements support for `TIMESTAMP` and `TIMESTAMPTZ` objects to be given a precision when created, for example `TIMESTAMP(0)`. `TIMESTAMP` objects have precision 6 by default, and only the precision values 0 and 6 are supported right now.

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
Looks like a good start. BTW, this was not explicit in the issue but we want to support 0 precision for TIMESTAMPTZ and TIME as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-:-Lg80G9W1po3zzsv0wJu:b-j7stw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by rohany** [comment]
Ok, this is ready for review -- I'll squash the commits and update the messages once it is ready for landing.

**Review by solongordon — CHANGES_REQUESTED** [review]
Added a testing suggestion. I'm still puzzling through some of the types stuff.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-:-LgYx0YBDWo-O1gE-25q:bqt4hkq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/timestamp, line 20 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-LgYum_Y46BxGxNQzxjn:-LgYum_ZEx5L5q0V3gyU:b-kch6lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/606fbf9f98d477cf3efdc38555252a58ddbd8a56/pkg/sql/logictest/testdata/logic_test/timestamp#L20)):*
> ```
> 
> statement ok
> CREATE TABLE timestamp_test (x TIMESTAMP(0)); INSERT INTO timestamp_test VALUES ('1-1-18 1:00:00.001'), ('1-1-18 1:00:00.00');
> ```

Generally I think we try not to have multiple statements per line in these tests, just to keep things readable.

Actually creating a table seems unnecessary here. You can just do `SELECT '1-1-18 1:00:00.001':::TIMESTAMP(0)` and verify the result. (Same for all the following tests.)

**Review by solongordon — CHANGES_REQUESTED** [review]
The rest LGTM with some nits. The whole default -1 thing bugs me a little bit but I can't think of a great alternative.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-:-LgZ-u3eCPQdk1zM1duR:b-t6val9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/types/types.go, line 1090 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-LgZ-Rcq-ceuYzkh1Jqr:-LgZ-Rcq-ceuYzkh1Jqs:b-8aw5dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/606fbf9f98d477cf3efdc38555252a58ddbd8a56/pkg/sql/types/types.go#L1090)):*
> ```Go
> 		return "JSONB"
> 	case TimestampFamily, TimestampTZFamily:
> 		// This is default timestamp
> ```

Maybe clearer to say it's a timestamp with the default precision.
___
*[pkg/sql/types/types.go, line 1094 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-LgYzp-y1Js-oY6p9tpZ:-LgYzp-y1Js-oY6p9tp_:b-qwh1wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/606fbf9f98d477cf3efdc38555252a58ddbd8a56/pkg/sql/types/types.go#L1094)):*
> ```Go
> 			return strings.ToUpper(t.Name())
> 		}
> 		return fmt.Sprintf("%s(%d)", strings.ToUpper(t.Name()), t.Precision())
> ```

Nit: Slightly simpler would be to just do:
```
if t.Precision() != -1 {
  return fmt.Sprintf("%s(%d)", strings.ToUpper(t.Name()), t.Precision())
}
```
and just rely on the default case for when precision == -1.
___
*[pkg/sql/types/types.go, line 1097 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-LgYzZTVB3tkG2LC3ECW:-LgYzZTVB3tkG2LC3ECX:b-c30gz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/606fbf9f98d477cf3efdc38555252a58ddbd8a56/pkg/sql/types/types.go#L1097)):*
> ```Go
> 	case TimeFamily:
> 		if t.Precision() > 0 {
> 			return fmt.Sprintf("TIME(%d)", t.Precision())
> ```

Nit: Might as well continue using `strings.ToUpper(t.Name())` here rather than hard-coding `TIME`.

**Comment by rohany** [comment]
I don't like the -1 default either, but it is tricky for printing purposes to know whether the timestamp precision is "default 6" or manually set to 6

**Comment by solongordon** [comment]
The alternative would be to add a boolean field specifying if Precision is set, but not sure that's an improvement in this case.

**Comment by rohany** [comment]
yeah, i would prefer to avoid changing protos and use elsewhere of the type

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37920#-:-LgZC_7T7PYDJ224WVjZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

**Comment by jordanlewis** [comment]
@rohany this is great! Could you please update the PR title and body to match the commit, to make it more obvious that this PR is about more than just 0 precision timestamp objects (which I think it is)?

**Comment by rohany** [comment]
@jordanlewis is that good, or do you have something else in mind?

**Comment by jordanlewis** [comment]
The title's good - can you update the body too? (like the first message in the PR). You can just edit it to be the same as your commit message. The reason it's important is to make sure that when someone inevitably goes back to this PR to try to figure out what the change was, they'll be able to understand the final merged state of the PR just by reading the subject.

**Comment by rohany** [comment]
Ok great -- sorry, I didn't know what you meant by update the body!

**Comment by jordanlewis** [comment]
Perfect - thanks!

**Comment by awoods187** [comment]
This pr was for this issue: https://github.com/cockroachdb/cockroach/issues/32098

**Comment by awoods187** [comment]
Also related to https://github.com/cockroachdb/cockroach/issues/16349

**Pull request merged**
