### PR TITLE
exec: add physical types; columnarizer and materializer

### PR DESCRIPTION
**Pull request by jordanlewis**
- exec: add physical types enum
- exec: add columnarizer and materializer

An exec physical type corresponds to a particular type's bytes
representation, from the perspective of exec. For example, OID
types and Integers are represented the same way - as int64s.
And Integers with bounded precisions may be represented as
int32, int16, or int8, depending on the precision bounds.

The columnarizer and materializer are the the components that map
data between the EncDatumRow representation and the exec.ColBatch
representation.

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
:lgtm: in general. I left a few thoughts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-:-LOtIIdv50WJ0B3GE__9:b-bw4ijr)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/columnarizer.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtDsJ92vgwfOeRGwTK:-LOtDsJ92vgwfOeRGwTL:b-o71slz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L192)):*
> ```Go
> 
> // unsafeConvertStringToBytes converts a string to a byte array to be used with string encoding functions.
> func unsafeConvertStringToBytes(s string) []byte {
> ```

Any reason not to share with `util.encoding` rather than duplicating?
___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtE8ZX1GgZU7ivu7gU:-LOtE8ZX1GgZU7ivu7gV:b-3bpxyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer_test.go#L51)):*
> ```Go
> 			if bat.Length() == 0 {
> 				break
> 			}
> ```

Would be nice to add a simple check on expected number of batches here. (Lesson learned from the tablereader benchmark issue.)
___
*[pkg/sql/distsqlrun/materializer.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtHCo83kIJ5K9qR2Rd:-LOtHCo83kIJ5K9qR2Re:b-ginxnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer.go#L117)):*
> ```Go
> 		sel := m.batch.Selection()
> 
> 		rowIdx := m.curIdx
> ```

Did you consider processing the entire batch here into an `EncDatumRows` buffer, rather than one row at a time? Seems like we could see a speed-up there since you could convert each column vector to EncDatums in a tight loop.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/columnarizer.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtDsJ92vgwfOeRGwTK:-LOtJ5MwBr-w52CLx982:b-5t6sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L192)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Any reason not to share with `util.encoding` rather than duplicating?
</blockquote></details>

Nope, I'll export from there, not sure why I didn't do that to start with.
___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtE8ZX1GgZU7ivu7gU:-LOtJ8HM5fx5ZSHnsr_t:b-ovwaw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer_test.go#L51)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Would be nice to add a simple check on expected number of batches here. (Lesson learned from the tablereader benchmark issue.)
</blockquote></details>

Good idea.
___
*[pkg/sql/distsqlrun/materializer.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtHCo83kIJ5K9qR2Rd:-LOtJ922BAtmPpgBx4iw:bc2u9g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer.go#L117)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Did you consider processing the entire batch here into an `EncDatumRows` buffer, rather than one row at a time? Seems like we could see a speed-up there since you could convert each column vector to EncDatums in a tight loop.
</blockquote></details>

Fantastic idea. Do you want to take that on? I'll plan to merge as-is and we can upgrade it later.

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/materializer.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtHCo83kIJ5K9qR2Rd:-LOtJMvfE-fziPypYAqp:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer.go#L117)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Fantastic idea. Do you want to take that on? I'll plan to merge as-is and we can upgrade it later.
</blockquote></details>

:thumbsup:

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/columnarizer.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt6dIr1E7ttGkrGq7B:-LOt6dIs9ryo6W--l0MV:b-edoe5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L47)):*
> ```Go
> 		input: input,
> 	}
> 	c.InitWithEvalCtx(
> ```

If you're just passing in `flowCtx.NewEvalCtx` might as well use `Init` (maybe explicitly call `ProcessorBase.Init` to avoid confusion)
___
*[pkg/sql/distsqlrun/columnarizer.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtRMRXErDN1lc0mDhC:-LOtRMRXErDN1lc0mDhD:b-x5jx36) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L62)):*
> ```Go
> }
> 
> func (c *columnarizer) Init() {
> ```

I feel like this might take the col batch size as an argument at some point since it should probably be a function of the L1 cache size (and maybe the number of columns?). I'm sure there's some literature on this.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtXNBO0CInGNjy2uIF:-LOtXNBO0CInGNjy2uIG:b-qipcgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L76)):*
> ```Go
> 	nRows := uint16(0)
> 	columnTypes := c.OutputTypes()
> 	for ; nRows < exec.ColBatchSize; nRows++ {
> ```

I think that `ColBatchSize` should be number of bytes, not number of rows.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtPEv6AvUSpo9dQMBJ:-LOtPEv775ysW7R7ZEo6:b8l8b1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L80)):*
> ```Go
> 
> 		if meta != nil {
> 			panic("metadata")
> ```

At some point we'll need to `c.ProcessorBase.AppendTrailingMeta(meta)` here, right? The materializer should probably have a reference to the upstream columnarizer.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtQOKu2ICU6lCePh-H:-LOtQOKu2ICU6lCePh-I:b-bnnwgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L85)):*
> ```Go
> 			break
> 		}
> 		c.buffered[nRows] = row
> ```

Are we going to have to copy here?
___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtTM5n3LorW2VsfCNe:-LOtTM5n3LorW2VsfCNf:bv1qkh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer_test.go#L48)):*
> ```Go
> 	for i := 0; i < b.N; i++ {
> 		for {
> 			bat := c.Next()
> ```

nit: do we want to be using the term `bat`?
___
*[pkg/sql/distsqlrun/materializer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtWIpdA1j5ImZCBLeC:-LOtWIpdA1j5ImZCBLeD:be8sccr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer_test.go#L28)):*
> ```Go
> )
> 
> func TestColumnarizeMaterialize(t *testing.T) {
> ```

We should think about adding randomization.
___
*[pkg/sql/exec/types/types.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt2axV05QuT3_WBEFN:-LOt2axW0GW7Bkzt7_Hf:b9x20br) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dafbcb556ae32f2313e8d1fcdd35acf1eae061f/pkg/sql/exec/types/types.go#L25)):*
> ```Go
> // T represents an exec physical type - a bytes representation of a particular
> // column type.
> type T int
> ```

Have you considered making this a `byte`?
___
*[pkg/sql/exec/types/types.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt3Dvq9ZH-srqRV3lb:-LOt3Dvq9ZH-srqRV3lc:b-pb5xhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dafbcb556ae32f2313e8d1fcdd35acf1eae061f/pkg/sql/exec/types/types.go#L61)):*
> ```Go
> 			return Int64
> 		}
> 		panic(fmt.Sprintf("integer with unknown width %d", ct.Width))
> ```

Do you think it might be better to just have `Int64` be a catch-all as a `default` case?

**Review by solongordon — APPROVED** [review]

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/columnarizer.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOxa4crDIMrq8I68Fh7:-LOxa4crDIMrq8I68Fh8:bdbdwn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L139)):*
> ```Go
> 				col := vec.Int64()
> 				for i := uint16(0); i < nRows; i++ {
> 					if c.buffered[i][idx].Datum == nil {
> ```

Any reason you didn't use the `Datum == nil` optimization for every column type? Same question for avoiding the `ed :=` assignment.

**Comment by jordanlewis** [comment]
> Any reason you didn't use the Datum == nil optimization for every column type? Same question for avoiding the ed := assignment.

Lack of templating. I only was playing with the int64 one - the implementation that's there for the int64 type was the fastest according to the benchmark.

**Review by solongordon — COMMENTED** [review]
Thanks, that's what I figured. I'll include those in the template.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-:-LOxfHzL0tGDl5ZaSfnH:bdgazbh)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/columnarizer.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt6dIr1E7ttGkrGq7B:-LOyNNTkAyubOIVZGMG1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L47)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you're just passing in `flowCtx.NewEvalCtx` might as well use `Init` (maybe explicitly call `ProcessorBase.Init` to avoid confusion)
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtRMRXErDN1lc0mDhC:-LOyNO7F-kNnDhzyhsBQ:bgy5bll) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L62)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I feel like this might take the col batch size as an argument at some point since it should probably be a function of the L1 cache size (and maybe the number of columns?). I'm sure there's some literature on this.
</blockquote></details>

Agreed, though for now it'll be easier to just keep things parameterized on a global. We can tune this later as needed.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtXNBO0CInGNjy2uIF:-LOyNUXw3zduIX6tLdv0:b-pql5r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L76)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think that `ColBatchSize` should be number of bytes, not number of rows.
</blockquote></details>

That's going to be very tricky, as it will lead to a different number of rows per column vector. I think for now we can stick with number of rows. If you're motivated to do so, you should benchmark whether this makes a difference.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtPEv6AvUSpo9dQMBJ:-LOyNfIw3AF7jkQFXsXq:bacly3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L80)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

At some point we'll need to `c.ProcessorBase.AppendTrailingMeta(meta)` here, right? The materializer should probably have a reference to the upstream columnarizer.
</blockquote></details>

Yes, we'll need that at some point.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtQOKu2ICU6lCePh-H:-LOyNkMW6d9I4XaMk4lr:bm3urn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L85)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are we going to have to copy here?
</blockquote></details>

Great point, fixed. Now we preallocate rows of the right size in startup, and copy the EncDatums into their rows.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtDsJ92vgwfOeRGwTK:-LOyOX4v8VqynBzuJItb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L192)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nope, I'll export from there, not sure why I didn't do that to start with.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtTM5n3LorW2VsfCNe:-LOyNwBHCD2rdbmOv5qA:bt2aqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer_test.go#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: do we want to be using the term `bat`?
</blockquote></details>

Just short for batch, I didn't mean to make it sound like BAT. Fixed.
___
*[pkg/sql/distsqlrun/materializer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtWIpdA1j5ImZCBLeC:-LOySeAd2OSlF2Z3kqhy:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer_test.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We should think about adding randomization.
</blockquote></details>

Agreed.
___
*[pkg/sql/exec/types/types.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt2axV05QuT3_WBEFN:-LOySgT_7ceC8ap4ICsC:b2wqcaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dafbcb556ae32f2313e8d1fcdd35acf1eae061f/pkg/sql/exec/types/types.go#L25)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Have you considered making this a `byte`?
</blockquote></details>

Interesting idea - I think that unlike the other datatypes we were discussing this one is less critical to make small, since it's not touched in the hot path - should be either just during planning or once per patch.
___
*[pkg/sql/exec/types/types.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOt3Dvq9ZH-srqRV3lb:-LOySu-f10OrCsi05BIR:b-gq7ltr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dafbcb556ae32f2313e8d1fcdd35acf1eae061f/pkg/sql/exec/types/types.go#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you think it might be better to just have `Int64` be a catch-all as a `default` case?
</blockquote></details>

I think for now I like the panic because it shows us that something is going very wrong. We shouldn't have a width that aren't those above values.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/columnarizer.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtPEv6AvUSpo9dQMBJ:-LP1RVbM4oQdGGg04IwD:bv24ixt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L80)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yes, we'll need that at some point.
</blockquote></details>

Maybe add a TODO
___
*[pkg/sql/distsqlrun/columnarizer.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtQOKu2ICU6lCePh-H:-LP1R_qaEZUcYHMkAYED:b-94s5pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L85)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Great point, fixed. Now we preallocate rows of the right size in startup, and copy the EncDatums into their rows.
</blockquote></details>

Now that we do need to copy, I wonder if it might be better to just immediately write out the column values and avoid the copy?
___
*[pkg/sql/distsqlrun/materializer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtWIpdA1j5ImZCBLeC:-LP1UIMr7iFKNlp602cd:boy71zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer_test.go#L28)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Could you add a TODO?

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-:-LP2430a4YSqNE7eyc7a:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/columnarizer.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtPEv6AvUSpo9dQMBJ:-LP242QE6QCCYCV7eyv_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L80)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe add a TODO
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/columnarizer.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtQOKu2ICU6lCePh-H:-LP241YnBJjjm8ON7Ri1:b-7g6inw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/columnarizer.go#L85)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Now that we do need to copy, I wonder if it might be better to just immediately write out the column values and avoid the copy?
</blockquote></details>

Added a todo.
___
*[pkg/sql/distsqlrun/materializer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LOtWIpdA1j5ImZCBLeC:-LP24-z6EH0dIXirUMbr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d591483a930d1132157db3229154d6d8e64d3c68/pkg/sql/distsqlrun/materializer_test.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you add a TODO?
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
bors r-

Pushed the wrong rev.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31353)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec/colbatch.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31353#-LP7RjOp4CSDy6wOQ10O:-LP7RjOp4CSDy6wOQ10P:b-7ghx7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6746fbd4ff62a5e23f7372ca7f3a4ebed7792546/pkg/sql/exec/colbatch.go#L46)):*
> ```Go
> // NewMemBatch allocates a new in-memory ColBatch.
> // TODO(jordan): pool these allocations.
> func NewMemBatch(types ...types.T) ColBatch {
> ```

OOC, what's the thinking behind making this a list of args vs a slice of types? I assume we avoid allocating when we don't need to? However, the only use of this I see so far unpacks a slice

**Comment by jordanlewis** [comment]
I thought it'd be convenient for tests, but I don't care one way or the other

**Pull request merged**
