### PR TITLE
sql: in doctor skip namespace checks for namespace tables

### PR DESCRIPTION
**Pull request by spaskob**
When migrating from 19.2 to 20.1 cluster the migration from `system.namespace`
to `system.namespace2` leaves certain inconsistencies in the namespace mapping
which should not be flagged by the doctor tool.

Touches #55237.

Release note: none.

### CODE REVIEW

**Review by thoszhang — COMMENTED** [review]
I think I'd prefer an approach that could detect inconsistencies also in the namespace entries for system.namespace and system.namespace2 themselves. There are really only 3 possible states (pre-20.1, 20.1 pre-migration, and 20.1 post-migration), right? I think it'd be good to just account for those specific states.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55113#-:-MIbxuYTCju-o-Z6Y_gF:b-ux0ww4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by spaskob** [comment]
Sure - how can I detect that the cluster is in these states, either on a live cluster or from a debug zip?

**Review by thoszhang — APPROVED** [review]
I'm not sure if there is a way to do that.

Thinking about this more, I think I'd prefer that we just enumerate all the possible non-20.1 possibilities (the ones we encountered in that customer issue), and emit a warning if one of those states is encountered without returning a nonzero exit status and fail otherwise. But that's a more complicated change. I think I'm fine with this the way it is alongside a TODO and an issue for having more fine-grained namespace table entry validation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55113#-:-MIwVDL4ArsjenoygzEb:bcuwmd0)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by spaskob — COMMENTED** [review]
Thank you - I filed https://github.com/cockroachdb/cockroach/issues/55237

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55113#-:-MIwxqun2f9OlwrdsDA_:b-s8nye5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
