### PR TITLE
sql: add TestLogicDistSQL

### PR DESCRIPTION
**Pull request by RaduBerinde**
Add a variant of the logic test which turns DistSQL on.

Opened #13025 to discuss whether we want to run this only in TeamCity.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13026)

### CODE REVIEW

**Review by knz — APPROVED** [review]

**Comment by arjunravinarayan** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logic_test.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBAVhXrOuWEf1eGrU8:-KbBAVhYDVmQs7QDUamB:b-kejlm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1189)):*
> ```Go
> 	// during a local `make test`).
> 
> 	defer sql.SetDefaultDistSQLMode("ON")()
> ```

can we just set the env var?

---

*[pkg/sql/logic_test.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBA4dJ46eBamDM8pSq:-KbBA4dK-HCPuT5T0Pan:bxqz41w) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1190)):*
> ```Go
> 
> 	defer sql.SetDefaultDistSQLMode("ON")()
> 	defer sql.EnableDistSQLDiagramLog()()
> ```

do we need to enable these diagrams? Maybe put it behind a flag? Or maybe the env var that we already have is enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logic_test.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBAVhXrOuWEf1eGrU8:-KbBDblmTXbiouTgJdCy:bsrf5cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1189)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we just set the env var?
</blockquote></details>

hmm, how? we would need to move the test into some script around the invocation of `make test` no?

---

*[pkg/sql/logic_test.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBA4dJ46eBamDM8pSq:-KbBDHobZzFHaCiPI1RU:b-n4wof3) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1190)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do we need to enable these diagrams? Maybe put it behind a flag? Or maybe the env var that we already have is enough?
</blockquote></details>

The diagrams will help debug any failures and there's not much of a downside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logic_test.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBAVhXrOuWEf1eGrU8:-KbCOQr-JXDf0wPMDZrK:b-9f2v6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

hmm, how? we would need to move the test into some script around the invocation of `make test` no?
</blockquote></details>

`os.SetEnv()`?

---

*[pkg/sql/logic_test.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBA4dJ46eBamDM8pSq:-KbCOTVVPMy07SYpxtX7:bwbfg2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1190)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The diagrams will help debug any failures and there's not much of a downside.
</blockquote></details>

well that json sure is long and spammy tho

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-:-KbCOc6C1VcZ_WMzhO8L:bnfp4nl)*

**Comment by tamird** [comment]
Messing with the environment does not seem better to me.

**Comment by RaduBerinde** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/logic_test.go, line 1189 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBAVhXrOuWEf1eGrU8:-KbCY1gCeCroB2K-aH6m:b-wxnmrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1189)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`os.SetEnv()`?
</blockquote></details>

The env var is only read once on process init.

---

*[pkg/sql/logic_test.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026#-KbBA4dJ46eBamDM8pSq:-KbCYXbsOEzp_SH7En0j:bqq3ctf) ([raw file](https://github.com/cockroachdb/cockroach/blob/687c19afa321a37eafd24406bee72dcdfd54434d/pkg/sql/logic_test.go#L1190)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well that json sure is long and spammy tho
</blockquote></details>

ok, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13026)*

**Pull request merged**
