### PR TITLE
sql/parser: support ENCODING='UTF8' no-op in CREATE DATABASE

### LINKED ISSUE #6426: sql: Allow for encoding keyword in create database statement - Ecto / Elixir
As outlined in #5582, when Ecto tries to create the database, it will specify the encoding by default:
` CREATE DATABASE test ENCODING='UTF8';`

At the moment, the `ENCODING` keyword is not known and therefore the statement does not work.

The keyword should be added and probably silently ignored so such statement do work. I suspect some other 'ORM' will also attempt to set the encoding when creating a database.

### PR DESCRIPTION
**Pull request by danhhz**
Closes #6426.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6614)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Dan Harrison) wrote…</i></summary>
> #### sql/parser: support ENCODING=&#39;UTF8&#39; no\-op in CREATE DATABASE
> 
> Closes #6426.
> 
> 
> </details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/parse_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDxUDMIq07Oh8ZQPW:-KHQDtTHcgsTKG61E0UT:2013885612) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/parser/parse_test.go#L51)):*
> ```Go
> 		{`CREATE DATABASE a ENCODING='UTF8'`},
> 		{`CREATE DATABASE IF NOT EXISTS a`},
> 		{`CREATE DATABASE IF NOT EXISTS a ENCODING='UTF8'`},
> ```

add a test with an unsupported encoding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-:-KHQDzQUrQGr9YVcLRsk:1417088721)*

**Comment by petermattis** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm:</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDvdeIlER3PpDnG_7:-KHQDvdeIlER3PpDnG_8:-564525300) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/create.go#L49)):*
> ```Go
> 		}
> 		// We only support UTF8.
> 		if *encoding.(*parser.DString) != "UTF8" {
> ```

Should this be a case-insensitive comparison?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-:-KHQE5HqB2U_DFBQoFsf:1417088721)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDvdeIlER3PpDnG_7:-KHQGbk_BwxuFcCFnX5B:1218317844) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/create.go#L49)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Should this be a case-insensitive comparison?</details>
It is case-insensitive in postgres. It also accepts "unicode" (documented) and "utf-8" (undocumented) as aliases for "UTF8". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614)*

**Comment by paperstreet** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 49 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDvdeIlER3PpDnG_7:-KHQIG8qbDXsPJwA_F7l:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/create.go#L49)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It is case-insensitive in postgres. It also accepts "unicode" (documented) and "utf-8" (undocumented) as aliases for "UTF8". </details>
Done.

---

*[sql/parser/parse_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDxUDMIq07Oh8ZQPW:-KHQG4EcBL3fJnBJopBm:-1398215031) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/parser/parse_test.go#L51)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> add a test with an unsupported encoding.</details>
Done. It's accepted here but rejected in the logic tests, that's what you meant right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/parse_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614#-KHQDxUDMIq07Oh8ZQPW:-KHQIdjx4DNpzEVmzYmr:-2032172072) ([raw file](https://github.com/cockroachdb/cockroach/blob/204873b5324a1b93f590a408a7730fabd91683f2/sql/parser/parse_test.go#L51)):*
<details><summary><i>Previously, paperstreet (Dan Harrison) wrote…</i></summary>
> Done. It's accepted here but rejected in the logic tests, that's what you meant right?</details>
Yep, that's what I meant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6614)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/290

**Pull request merged**
