### PR TITLE
sql: improve SHOW, EXPLAIN and VALUES

### PR DESCRIPTION
**Pull request by knz**
- SHOW: delay populating the valuesNode until query execution time.
  - bug fix: if SHOW TRANSACTION ISOLATION LEVEL is prepared then
    executed, this patch ensures SHOW reports the isolation level of
    the txn where the execute took place, not where it was prepared.
  - improvement: this patch avoids allocating a RowsContainer while
    the plan is being constructed (we'd like to avoid monitored
    allocations during prepare).
- VALUES: EXPLAIN on VALUES, or things that use valuesNode internally,
  also reports the number of rows in the node.
- EXPLAIN can now be used with SHOW and ALTER TABLE .. SPLIT.
  EXPLAIN ALTER TABLE ... SPLIT AT now properly shows the plan for subqueries.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10013)

### CODE REVIEW

**Comment by knz** [comment]
cc @asubiotto: if this merges before your PR, ensure you follow the pattern for SHOW USERS.

**Comment by mjibson** [comment]
Does the bug fix for `SHOW TRANSACTION ISOLATION LEVEL` affects all the other similar SHOW statements too? If so, can that be noted in the commit message?

---

Reviewed 5 of 17 files at r1.
Review status: 5 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10013#-:-KUGhi47U555K321x6z1:bvrhxgz)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 5 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10013#-:-KUGi6Chz8VuYCvW5bOX:bnfp4nl)*

**Comment by knz** [comment]
I have updated the commit message as suggested. TFYR!

**Comment by knz** [comment]
For docs: simply document EXPLAIN can be used with SHOW too. It's not very interesting but this way the user can inspect the schema of the results.

**Pull request merged**
