### PR TITLE
storage: better gossiping of first range on lease acquisition

### PR DESCRIPTION
**Pull request by petermattis**
Only gossip the first range when the lease holder changes. Also gossip
the first range after a change replicas in case the lease holder is not
changing.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7823)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica_command.go, line 2820 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb4JcON5j-DL9n6Eft:-KMb4JcON5j-DL9n6Efu:-2021355173) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2820)):*
> ```Go
> 	cpy.Replicas = change.UpdatedReplicas
> 	cpy.NextReplicaID = change.NextReplicaID
> 	if err := r.setDesc(&cpy); err != nil {
> ```

@bdarnell, @tschottdorf: Should this call to `setDesc` happen within a `batch.Defer`? What happens if the batch doesn't commit? In the split code path, we update the LHS descriptor via a call to `Store.SplitRange` which occurs in a `batch.Defer`. At the very least this isn't symmetric and deserves a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 2468 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb7MY9NSiiNm9SWBy7:-KMb7MY9NSiiNm9SWBy8:1233329823) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica.go#L2468)):*
> ```Go
> }
> 
> func (r *Replica) gossipFirstRange(ctx context.Context, desc *roachpb.RangeDescriptor) {
> ```

this desc is always r.mu.state.desc, seems pretty unsatisfying to have to pass it in because of locking. Perhaps we could require that this function is always called under lock?

---

*[storage/replica_command.go, line 2857 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb91Tb2pCvA0-mwbf6:-KMb91TcP6pwE6Qz3-Iw:2028273530) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2857)):*
> ```Go
> 		batch.Defer(func() {
> 			// We need to run the gossip in an async task because gossiping requires
> 			// the range lease and we'll deadlock if we try to acquire it will
> ```

s/will/while/

---

*[storage/replica_command.go, line 2863 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb72deXxB_ArKezwmK:-KMb72deXxB_ArKezwmL:-1161202710) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2863)):*
> ```Go
> 			// processRaftMu (and running on the processRaft goroutine).
> 			r.store.Stopper().RunAsyncTask(func() {
> 				ctx := r.context(context.Background())
> ```

we have a `ctx` in scope

---

*[storage/replica_command.go, line 2864 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb8PzdkbQ1SMzZYLnW:-KMb8PzdkbQ1SMzZYLnX:950743307) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2864)):*
> ```Go
> 			r.store.Stopper().RunAsyncTask(func() {
> 				ctx := r.context(context.Background())
> 				if ok, err := r.getLeaseForGossip(ctx); !ok || err != nil {
> ```

nit: this pattern is odd. could it be:
```
if hasLease, pErr := r.getLeaseForGossip(ctx); hasLease {
  r.gossipFirstRange(...)
} else {
  log.Infof("unable to gossip first range; hasLease: %t, err: %v", hasLease, err)
}
```

If you make this change, can you do likewise above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1641 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMbeHHovhXnAl83N7wS:-KMbeHHovhXnAl83N7wT:-460204558) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L1641)):*
> ```Go
> 				// lease request and attempt to gossip the first range.
> 				//
> 				// TODO(peter): This might be excessive. We could avoid gossiping if the
> ```

You can remove this TODO; I think limiting the gossip to times when the lease changes hands is enough.

---

*[storage/replica_command.go, line 2820 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb4JcON5j-DL9n6Eft:-KMbeYES7tZ36X1G5QO9:247807687) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2820)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @bdarnell, @tschottdorf: Should this call to `setDesc` happen within a `batch.Defer`? What happens if the batch doesn't commit? In the split code path, we update the LHS descriptor via a call to `Store.SplitRange` which occurs in a `batch.Defer`. At the very least this isn't symmetric and deserves a comment.
</details>
I agree it looks like this should happen in a batch.Defer for symmetry; I can't remember if there's any reason why this is different from splits.

---

*[storage/replica_command.go, line 2863 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb72deXxB_ArKezwmK:-KMbezRL6G6AqtCx26jZ:-291270536) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2863)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> we have a `ctx` in scope
</details>
But using it might result in use-after-finish of the tracer it contains. Better to create a new context for async tasks like this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-:-KMbfBU1ghYFYvJofpJE:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 2468 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb7MY9NSiiNm9SWBy7:-KMc1F8CWk-wFzBAA-Kr:1775589054) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica.go#L2468)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this desc is always r.mu.state.desc, seems pretty unsatisfying to have to pass it in because of locking. Perhaps we could require that this function is always called under lock?
</details>
I agree.

---

*[storage/replica_command.go, line 2820 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb4JcON5j-DL9n6Eft:-KMc0z6Qi0b7ePGNB21v:610297001) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2820)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I agree it looks like this should happen in a batch.Defer for symmetry; I can't remember if there's any reason why this is different from splits.
</details>
I think it should go into a `Defer`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 2468 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb7MY9NSiiNm9SWBy7:-KMjcBZAajCmJ-Cuo-V8:205491145) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica.go#L2468)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I agree.
</details>
Done. This found a bug in `applyNewLeaseLocked`.

---

*[storage/replica_command.go, line 1641 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMbeHHovhXnAl83N7wS:-KMj_yFUJK94zqZ5ovqm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L1641)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> You can remove this TODO; I think limiting the gossip to times when the lease changes hands is enough.
</details>
Done.

---

*[storage/replica_command.go, line 2820 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb4JcON5j-DL9n6Eft:-KMj_zR3bYvNfUf4N9DY:-1844732245) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2820)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I think it should go into a `Defer`.
</details>
Filed #7851.

---

*[storage/replica_command.go, line 2857 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb91Tb2pCvA0-mwbf6:-KMja9x3ddNiBBx0CC4A:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2857)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/will/while/
</details>
Done.

---

*[storage/replica_command.go, line 2863 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb72deXxB_ArKezwmK:-KMjaAJuoQO6NeHPBHyr:543516598) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2863)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> But using it might result in use-after-finish of the tracer it contains. Better to create a new context for async tasks like this. 
</details>
What @bdarnell said. Added a comment.

---

*[storage/replica_command.go, line 2864 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMb8PzdkbQ1SMzZYLnW:-KMjbYf_vaZHgiQwpFqY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4844d132d27f31ff9d9e9157382b837a89e33afc/storage/replica_command.go#L2864)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: this pattern is odd. could it be:
> ```
> if hasLease, pErr := r.getLeaseForGossip(ctx); hasLease {
>   r.gossipFirstRange(...)
> } else {
>   log.Infof("unable to gossip first range; hasLease: %t, err: %v", hasLease, err)
> }
> ```
> 
> If you make this change, can you do likewise above?
</details>
Done.

---

*[storage/replica_command.go, line 1645 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMjcoCbOSC7lLr-0aM2:-KMjcoCbOSC7lLr-0aM3:-2006417063) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5f5b41852d8e88c0b31019373364d67baca2e4/storage/replica_command.go#L1645)):*
> ```Go
> 			// range descriptor hasn't changed recently though we'd have to figure out
> 			// what reliable signal to use to determine that.
> 			if r.IsFirstRange() && r.mu.state.Lease.Covers(r.store.Clock().Now()) {
> ```

@tschottdorf Is the `Lease.Covers` check necessary? If it is shouldn't all of the code in this area be protected with that check? If it isn't necessary, why not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by petermattis** [comment]
PS I'm going to work on testing these code paths using `TestCluster` and leadership transfer. 

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-:-KMjd6SQA_VmIiqEOmY3:-2130783301)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 1645 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMjcoCbOSC7lLr-0aM2:-KMkP3RP7A-UGugHp2Jv:-1738464222) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d5f5b41852d8e88c0b31019373364d67baca2e4/storage/replica_command.go#L1645)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @tschottdorf Is the `Lease.Covers` check necessary? If it is shouldn't all of the code in this area be protected with that check? If it isn't necessary, why not?
</details>
We may be replaying an old log entry; if so we don't want to gossip our outdated information. We only want to gossip if our new lease is valid at the time we are processing this entry. This is a rare edge case that probably doesn't matter much but we might as well keep it.

The following section which calls TransferLeader should also be under this check. I'm not sure about the previous SetLowWater call, but it's safer to do it regardless of the current time. We must not use store.Clock().Now() outside of this Deferred function; the main body of the command must be executed the same way regardless of the current time. Only side effects like this which are outside of the "state machine" may access the clock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by petermattis** [comment]
I added a test that verifies we're gossiping the first range on lease transfer, replica addition and replica removal. PTAL.

**Comment by petermattis** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica.go, line 2468 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMzbNr4P4Bqdrryw_Hi:-KMzehvLyEnQwn-sWQeF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e7d8c984d18ef1493b40a0cc359204ce741a55/storage/replica.go#L2468)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> `s/err/pErr` (it's `*roachpb.Error` afaict)
</details>
Done.

---

*[storage/replica_command.go, line 2870 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KMzbVKI-sTmkpieN63t:-KMzer2NxVK3KKOcfmTu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e7d8c984d18ef1493b40a0cc359204ce741a55/storage/replica_command.go#L2870)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/tracer/trace/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-:-KN-3V_EUUKUFn0R9doM:1417088721)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica_command.go, line 2874 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823#-KN-gq_mYbetCz2JOxdE:-KN-gq_mYbetCz2JOxdF:2091076893) ([raw file](https://github.com/cockroachdb/cockroach/blob/2745a4ae6edd5acd693d6a02c3774017ded885f6/storage/replica_command.go#L2874)):*
> ```Go
> 			// because we're not processing raft messages due to holding
> 			// processRaftMu (and running on the processRaft goroutine).
> 			_ = r.store.Stopper().RunAsyncTask(func() {
> ```

i think we should log this error. this has been discussed elsewhere - ignoring this error can end up costing someone serious time in debugging an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7823)*

**Pull request merged**
