### PR TITLE
ccl/storageccl: support HTTP_PROXY env vars

### LINKED ISSUE #32803: storageccl: allow user to specify an HTTP proxy for cloud storage
It's not uncommon for enterprises to have restrictions on which nodes can talk to which external servers, and to require whitelisted external traffic to be piped through an HTTP proxy. Right now, if you want to use an HTTP proxy, you have to proxy all CockroachDB traffic including traffic between nodes; this is not ideal and can lead to network bottlenecks. There is a workaround of sorts where a user can specify an AWS_ENDPOINT parameter for S3 cloud storage operations, which would allow the user to use an internal HTTP server as a transparent proxy to a hardcoded external S3 URL, but this is less flexible than just supporting standard HTTP proxies.

When a user wants to back up their data to cloud storage, or perform other bulk I/O operations like restore and import, CockroachDB should allow the user to specify an HTTP proxy address and port use for these external connections. We should also consider allowing the user to specify a default proxy to use for cloud storage requests, e.g. a `cloudstorage.http.proxy` cluster setting.

### PR DESCRIPTION
**Pull request by madelynnblue**
HTTP and S3 storage both used a wrapped http.Client, but it didn't copy
and modify http.DefaultTransport, instead making one from scratch. This
meant that the normally supported settings like proxy and timeouts
were zero'd.

Fixes #32803

Release note (enterprise change): Support standard HTTP proxy environment
variables in HTTP and S3 storage.

### CODE REVIEW

**Review by dt — APPROVED** [review]
I guess this is annoying to test and presumably the underlying stdlib tests cover it, so it'd really just be a "do the flags work" test.

**Comment by dt** [comment]
We have existing users complaining about the lack of proxy support -- do we want to consider this for a backport? It is fixing a user-visible defect (and $ users at that) and is pretty tightly contained change. I think it is low-risk too?

**Comment by mjibson** [comment]
Roland reported that the proxy settings were already working for S3, although I'm not sure how. I think it makes sense to make a full test to ensure we don't regress and to figure out if it already worked, and if so, why. I'll rework this PR with a test.

**Comment by mjibson** [comment]
Added a pretty annoying test. I verified that it fails without the accompanying change. This leads me to believe that the S3 client has its own proxy stuff which is why the customer reported it working, but the test needed the change to pass since the tests uses HTTP. I do think this warrants a backport in either case.

**Comment by knz** [comment]
I like this change. Thank you for making it! Is there still a chance to merge this and backport?

**Comment by mjibson** [comment]
Yes. @dt can you review the test?

**Comment by mjibson** [comment]
Although this is kind of annoying because the httpproxy package would have to be vendored just for this test. Not sure if it's worth it.

**Comment by dt** [comment]
still lgtm -- I'm fine with or without the test. I'd say vendoring the lib isn't unreasonable, though doing it again for the backport seems like it's really getting into diminishing returns.

**Comment by mjibson** [comment]
Thanks. I cut the test. But I was glad to write it to verify things worked as expected.

**Pull request merged**
