### PR TITLE
sql: accept floats when expecting ints during logic tests

### LINKED ISSUE #3271: sql: integer division returns float, sqllogic test expects int
The following (currently disabled) test performs integer division. Cockroach returns a float instead of the expected int. Integer division is the only binary operator that takes integers and returns a float.

https://github.com/cockroachdb/sqllogictest/blob/a88396b84bb1fe62edf2e072e585d68c0b2ecdca/test/select1.test#L101

I propose allowing the test logic to accept both ints and floats when it expects an int. This would allow any sqllogic test using integer division to succeed. It would be an additional if statement at https://github.com/cockroachdb/cockroach/blob/21e3e6c26be6a1f4a53cca53a3f095fd7d267686/sql/logic_test.go#L460.

### PR DESCRIPTION
**Pull request by madelynnblue**
fixes #3271

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3543)

### CODE REVIEW

**Comment by tamird** [comment]
This isn't quite enough; i was playing with adding the logic tests enabled by GROUP BY support (#3494) and found for example: `SELECT DISTINCT 20 / - 97 FROM tab0` which expects "0" but gets "0.20...". We'll need to convert these floats to integers in this special case.

**Comment by tamird** [comment]
Actually, even that doesn't work, because of cases like `SELECT DISTINCT col1 / 2 FROM tab1` where `col1` is an integer; this query will not behave correctly with respect to `DISTINCT`.

**Comment by bdarnell** [comment]
What special case, exactly? Are you suggesting that `DISTINCT int / int` should convert the result to an int, but `int / int` in other cases should return a float? That seems like a bad idea to me.

The fact that `SELECT DISTINCT 20 / - 97 FROM tab0` returns different results for us than it does in other databases is a simple consequence of the fact that we have chosen to have integer division return floats rather than ints; we expect and accept that this decision will not be 100% compatible.

**Comment by tamird** [comment]
Yes, feel free to ignore the first of my two comments. We will need to either accept this incompatibility and simply skip or massage offending test cases, or else revert to integer division.

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3543#-:-K6jLfnjGHX3a7TTqBCI:676834233)*

**Comment by mjibson** [comment]
We decided to use another solution. Closing.

**Pull request closed without merging**
