### PR TITLE
storage: disallow nil via types rather than comments

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM




---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15783#-:-KjdpE-PmcQDJdL24mk9:beo10rp)*

**Comment by petermattis** [comment]
A `roachpb.Lease` is a non-trivial structure (80-bytes in size). Passing it and returning it by value has cost (copying and stack growth), especially if a pointer is readily available. This makes me mildly anxious that this PR will have a performance impact.

---

Reviewed 2 of 2 files at r1, 15 of 15 files at r2.
Review status: 9 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15783#-:-KjdsiPuKOQGiwGxfwhq:b-atbm4i)*

**Comment by petermattis** [comment]
PS I'm not really sure what to do to allay my anxiety either, which puts my concern straight up in the FUD category.

---

Review status: 9 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15783#-:-KjduC2dvuaMaXpSHtKT:b8boa22)*

**Comment by tamird** [comment]
On Mon, May 8, 2017 at 5:14 PM, Peter Mattis <notifications@github.com>
wrote:

> PS I'm not really sure what to do to allay my anxiety either, which puts
> my concern straight up in the FUD category.


Yet it's a valid concern. Are there any benchmarks that would help here?
Perhaps a loadgen run of some duration?

**Comment by petermattis** [comment]
> Yet it's a valid concern. Are there any benchmarks that would help here? Perhaps a loadgen run of some duration?

I would start with `kv --read-percent 0 --duration 5m` and `kv --read-percent 95 --duration 5m`. 

I didn't look terribly closely at the changes yet. Another thought is to see which inner code path is potentially affected and to select a benchmark/load-generator which stresses it. It is possible `kv` would be sufficient.

**Comment by tamird** [comment]
I went with a slightly unscientific 30 seconds rather than 5 minutes, but
the results show a substantial performance *increase*. Yeah, I'm surprised
too.

Before:

> $ kv --read-percent 0 --duration 30s
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>       1s        0          924.4          924.3     12.6     15.2     18.9
>       2s        0          909.8          917.1     13.1     17.8     22.0
>       3s        0          838.3          890.9     15.2     27.3     37.7
>       4s        0          825.5          874.5     15.7     19.9     23.1
>       5s        0          934.4          886.5     12.6     15.2     18.9
>       6s        0          847.2          879.9     13.6     19.9     50.3
>       7s        0          831.5          873.0     14.2     19.9     29.4
>       8s        0          930.4          880.2     13.1     30.4     58.7
>       9s        0         1032.8          897.1     11.0     14.7     15.2
>      10s        0          830.9          890.4     16.3     26.2     33.6
>      11s        0          704.9          873.6     23.1     35.7     41.9
>      12s        0          867.8          873.1     14.2     18.9     26.2
>      13s        0          854.2          871.7     16.3     18.9     27.3
>      14s        0          812.6          867.4     17.8     22.0     23.1
>      15s        0          816.8          864.1     15.7     18.9     30.4
>      16s        0          851.7          863.3     15.7     19.9     25.2
>      17s        0          835.9          861.7     15.7     28.3     46.1
>      18s        0          866.1          861.9     14.7     21.0     32.5
>      19s        0          908.9          864.4     13.6     16.8     23.1
>      20s        0          818.8          862.1     15.7     29.4     56.6
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>      21s        0          903.4          864.1     13.6     17.8     33.6
>      22s        0          805.5          861.4     17.8     24.1     56.6
>      23s        0          888.6          862.6     13.6     17.8     19.9
>      24s        0          907.9          864.5     13.6     17.8     22.0
>      25s        0          927.2          867.0     13.1     16.8     21.0
>      26s        0          751.6          862.6     17.8     31.5     37.7
>      27s        0          824.4          861.1     15.7     24.1     32.5
>      28s        0          824.7          859.8     17.8     33.6     41.9
>      29s        0         1001.0          864.7     12.6     17.8     25.2
>      30s        0          905.0          866.1     14.2     17.8     28.3
>
> _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
>    30.0s        0          25982          866.1     15.2     22.0     58.7
>          0 / 25990
> BenchmarkBlocks   25982   1154667.9 ns/op
> $ kv --read-percent 95 --duration 30s
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>       1s        0         5019.7         5019.5      6.0     10.0     31.5
>       2s        0         5655.1         5337.4      5.2      9.4     39.8
>       3s        0         6691.8         5788.4      5.0      8.1     21.0
>       4s        0         6786.3         6037.9      4.7      7.6     21.0
>       5s        0         6743.4         6179.1      4.5      7.9     22.0
>       6s        0         6687.0         6263.7      4.7      7.6     23.1
>       7s        0         6177.7         6251.4      5.0      8.1     32.5
>       8s        0         5330.4         6136.2      5.8     10.0     50.3
>       9s        0         4357.9         5938.2      6.6     15.2     71.3
>      10s        0         4015.1         5746.2      6.8     12.6     58.7
>      11s        0         4585.7         5640.9      6.3     10.5     24.1
>      12s        0         5571.1         5635.1      5.5      8.4     18.9
>      13s        0         5378.3         5615.4      5.5      9.4     32.5
>      14s        0         5378.0         5598.4      5.8      8.9     32.5
>      15s        0         4771.2         5543.3      6.3     12.6     44.0
>      16s        0         4176.1         5457.8      6.8     14.2     88.1
>      17s        0         4086.5         5377.1      6.8     14.2     37.7
>      18s        0         4921.4         5351.8      5.8      9.4     32.5
>      19s        0         4489.3         5306.5      6.0     12.1     79.7
>      20s        0         5496.6         5316.0      5.0      8.1     65.0
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>      21s        0         5436.2         5321.7      5.5      9.4     19.9
>      22s        0         5544.2         5331.9      5.2      8.9     62.9
>      23s        0         5506.9         5339.5      5.2      8.9     16.8
>      24s        0         5503.6         5346.3      5.5      8.4     71.3
>      25s        0         5568.6         5355.2      5.5      8.9     28.3
>      26s        0         5258.7         5351.5      5.5      8.9     67.1
>      27s        0         5497.3         5356.9      5.0      8.9     65.0
>      28s        0         5312.5         5355.3      5.8     10.0     48.2
>      29s        0         5271.1         5352.4      5.8      9.4     28.3
>      30s        0         4956.9         5339.2      6.0     10.0     27.3
>
> _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
>    30.0s        0         160180         5339.2      5.5      9.4     88.1
>           0 / 8038
> BenchmarkBlocks  160180    187293.4 ns/op


After:

> $ kv --read-percent 0 --duration 30s
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>       1s        0         1370.7         1370.6      9.4     12.6     17.8
>       2s        0         1426.6         1398.5      8.9     10.5     14.7
>       3s        0         1378.0         1391.7      9.4     11.5     14.2
>       4s        0         1427.0         1400.5      9.4     11.5     13.6
>       5s        0         1354.8         1391.3     10.0     13.1     22.0
>       6s        0         1440.4         1399.5      8.9     11.5     15.7
>       7s        0         1352.8         1392.8     10.0     12.6     15.2
>       8s        0         1382.4         1391.5     10.0     12.1     14.7
>       9s        0         1417.0         1394.3     10.5     13.6     17.8
>      10s        0         1322.0         1387.1     11.0     13.1     15.7
>      11s        0         1300.8         1379.3     11.0     16.3     32.5
>      12s        0         1378.7         1379.2     10.0     12.1     16.3
>      13s        0         1410.1         1381.6     10.0     13.1     15.7
>      14s        0         1444.3         1386.1     10.0     12.1     15.7
>      15s        0         1395.7         1386.7     10.0     13.6     15.7
>      16s        0         1250.0         1378.2     11.5     15.7     30.4
>      17s        0         1326.1         1375.1     10.5     15.2     24.1
>      18s        0         1295.8         1370.7     11.0     13.6     17.8
>      19s        0         1426.2         1373.6      9.4     12.6     18.9
>      20s        0         1413.0         1375.6      9.4     14.2     18.9
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>      21s        0         1351.9         1374.5     10.5     15.2     27.3
>      22s        0         1315.0         1371.8     11.5     14.2     17.8
>      23s        0         1413.1         1373.6      9.4     12.1     14.7
>      24s        0         1368.7         1373.4     10.0     13.6     21.0
>      25s        0         1437.2         1375.9      9.4     12.1     17.8
>      26s        0         1387.1         1376.4     10.0     14.7     19.9
>      27s        0         1448.8         1379.0     10.5     14.7     25.2
>      28s        0         1535.3         1384.6     10.0     13.1     17.8
>      29s        0         1562.7         1390.8      9.4     12.1     16.3
>      30s        0         1528.4         1395.4      8.9     15.2     21.0
>
> _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
>    30.0s        0          41865         1395.4     10.0     13.1     32.5
>          0 / 41873
> BenchmarkBlocks    41865      716665.9 ns/op
> $ kv --read-percent 95 --duration 30s
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>       1s        0         5729.3         5729.1      4.1      7.1     27.3
>       2s        0         5730.8         5730.1      3.9      7.6     19.9
>       3s        0         5779.9         5746.7      3.9      7.6     19.9
>       4s        0         5501.2         5685.4      4.5      7.9     19.9
>       5s        0         5722.9         5692.9      3.8      8.9     88.1
>       6s        0         5217.1         5613.4      4.5     10.5     37.7
>       7s        0         4980.6         5523.2      4.5     12.1    100.7
>       8s        0         5467.7         5516.3      4.2     10.0     28.3
>       9s        0         4673.1         5422.6      5.2     11.5     54.5
>      10s        0         5039.5         5384.3      4.7     10.0     30.4
>      11s        0         5261.1         5373.1      4.7      9.4     33.6
>      12s        0         5382.9         5373.9      4.5      9.4     37.7
>      13s        0         5586.3         5390.2      4.1     10.0     39.8
>      14s        0         5759.0         5416.5      4.1      7.9     25.2
>      15s        0         5740.7         5438.2      4.5      7.9     37.7
>      16s        0         5691.0         5454.0      4.2      7.6     41.9
>      17s        0         5136.5         5435.3      4.7      9.4     33.6
>      18s        0         5578.9         5443.3      4.5      7.6     35.7
>      19s        0         4994.0         5419.6      5.0     10.0     35.7
>      20s        0         4883.3         5392.8      5.0     10.5     39.8
> _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
>      21s        0         5039.5         5376.0      4.7      8.9     52.4
>      22s        0         5348.6         5374.8      4.7      8.4     37.7
>      23s        0         4731.6         5346.8      5.2     11.5     28.3
>      24s        0         5788.7         5365.2      4.2      6.8     24.1
>      25s        0         5182.3         5357.9      4.7     10.5     48.2
>      26s        0         4887.2         5339.8      5.0     10.0     48.2
>      27s        0         5320.0         5339.1      4.7      9.4     79.7
>      28s        0         5216.2         5334.7      5.0     10.0     37.7
>      29s        0         5449.3         5338.6      4.7      8.4     30.4
>      30s        0         5457.7         5342.6      4.7      9.4     24.1
>
> _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
>    30.0s        0         160281         5342.6      4.5      9.4    100.7
>           0 / 7995
> BenchmarkBlocks   160281      187174.3 ns/op

**Comment by petermattis** [comment]
Hmm, that makes no sense.

**Comment by tamird** [comment]
Fewer allocations, perhaps?

**Comment by petermattis** [comment]
Also, what happened to performance? Something changed very recently. I was seeing ~10k ops/sec on a local single node last week.

**Comment by tamird** [comment]
I was running a 3 node cluster locally and I have full disk encryption enabled.

**Comment by petermattis** [comment]
> I was running a 3 node cluster locally and I have full disk encryption enabled.

Yeah, but I'm testing on master and seeing ~5k ops/sec in a configuration which I normally see double that.

**Comment by tamird** [comment]
I'll hold off on this while you bisect. Hopefully the culprit isn't the pointer-to-value changes in #15711.

**Comment by bdarnell** [comment]
:lgtm:, although the performance is puzzling. I can't see how this could make so much difference.

---

Reviewed 2 of 2 files at r1, 19 of 19 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15783#-:-Kje2DoMJeRQakCy7g-8:b8l2h3f)*

**Comment by petermattis** [comment]
I think something weird must have happened when @tamird tested. I see a very slight slowdown, that might very well be noise:

```
kv --read-percent 0 --duration 5m

  before:
  _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
    300.0s        0        1431071         4770.1      8.4     12.1     65.0
  
  after:
  _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
    300.0s        0        1402575         4675.2      8.4     12.6     79.7

kv --read-percent 95 --duration 5m

  before:
  _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
    300.0s        0        4497343        14991.1      2.5      6.8     83.9
  
  after:
  _elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)
    300.0s        0        4457612        14858.5      2.5      6.8     88.1
```

These were on single-node clusters. We really, really need some infrastructure to run some of these simple performance tests on every PR and track the numbers over time. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15783#-:-KjehYNdh_2p4PT_454w:bs692a3)*

**Comment by tamird** [comment]
I tested this again in my az worker (with 3 nodes) and still saw an increase in performance, this time in the read workload:
before,write:
```
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   59.5s        0          61081         1026.1     39.8     46.1     88.1          0 / 61113
```
after,write:
```
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   59.5s        0          59814         1005.2     41.9     48.2     71.3          0 / 59846
```
before,read:
```
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   59.5s        0         662549        11131.2      7.6     12.6     56.6          0 / 33502
```
after,read:
```
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   59.6s        0         937349        15731.9     11.0     25.2    100.7          0 / 47165
```

**Comment by tamird** [comment]
Anyway, I'm going to merge this now to avoid rot.

**Comment by petermattis** [comment]
Can you try that read test again? I'll go out on a limb and claim it is impossible that this change had such a large performance impact. Something funky is going on. Are you starting from a fresh cluster for each of the runs?

**Comment by tamird** [comment]
Fresh cluster for each SHA - that is: nuke, write, read, nuke, write, read.

I'll run it again.

**Comment by tamird** [comment]
Just ran the --read-percent 95 this time, and I get ~15k ops/sec now in
both "before" and "after". I guess there was no performance difference
after all.

**Pull request merged**
