### PR TITLE
sql: Implement minus for JSON and text array

### LINKED ISSUE #23293: sql: support `json` - `text[]` operator
Cockroach:

```
> select '{"a": "b", "c": "d"}'::jsonb - '{a,c}'::text[];
pq: unsupported binary operator: <jsonb> - <string[]>
```

Postgres:

```
# select '{"a": "b", "c": "d"}'::jsonb - '{a,c}'::text[];
 ?column? 
----------
 {}
```

### PR DESCRIPTION
**Pull request by emsal0**
* Added another case for the `Minus` operation to take a JSON Object on the left and a text array on the right
* Added JSON logic tests for this new functionality 

Release note: Implemented the minus operation between a JSON Object and a text array.

closes #23293

### CODE REVIEW

**Comment by emsal1863** [comment]
* Is `str` a good name for the variable? I originally chose `idx` because the things being removed are being removed by the json keys. Perhaps `key` could work?
* The failing tests are golang linting-related (with no stacktrace) but `golint` passes on the one golang file that I modified. How do I pinpoint what went wrong?

**Comment by benesch** [comment]
> The failing tests are golang linting-related (with no stacktrace) but golint passes on the one golang file that I modified. How do I pinpoint what went wrong?

That's just confusing TeamCity output. TestLint is the parent test, which failed because TestLint/Megacheck failed:

```
[/gosimple] lint_test.go:843: /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:913:5: should merge variable declaration with assignment on next line (S1021)
```

That error will disappear once you drop the `err = nil` line as @knz recommended.

**Comment by knz** [comment]
Thanks for the update. See below for a last code comment.

Also consider using Reviewable to answer to the comments inline with the code, instead of at a top-level github comment.

Finally, the release note doesn't have a valid format. I am surprised that the commit message linter didn't explain this to you. The release note should also contain the category, for example `Release note (sql change): ...`.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/sem/tree/eval.go, line 916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-LDjtJYDALF6zFClvUwo:-LDjtJYE1jEHMA_Zh5AG:btfxf93) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6907f56888db34f6f8c27d48837be3ebf4c6e7/pkg/sql/sem/tree/eval.go#L916)):*
> ```Go
> 					var err error
> 					j, _, err = j.RemoveString(string(MustBeDString(str)))
> ```

Another style thing: the test on `err` is not separated from the assignment by an empty line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-:-LDjtSwPDLxcTU0x7yeb:b-toujo6)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-LDjtJYDALF6zFClvUwo:-LDlOOcKDe0VTNOqFVDA:b-2naqha) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6907f56888db34f6f8c27d48837be3ebf4c6e7/pkg/sql/sem/tree/eval.go#L916)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Another style thing: the test on `err` is not separated from the assignment by an empty line.
</blockquote></details>

Sorry I wasn't clear. The definition of `err` may or may not be separated from the line after by an empty line, but that's not what I was looking at.

I was looking at the *test* on `err` (`if err != nil`). That test must *not* be separated from the assignment to `err` by an empty line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183)*

**Comment by knz** [comment]
Now that this code is looking better, time has come to prepare it to merge.

The general rule of thumb is:

- one commit per concern
- the tests should be able to pass successfully for each commit in isolation

So if you work on different things on a PR it's OK to have multiple commits, but if you have just one concern at the end you should squash the commits that address that concern together.

That would be the case here.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-:-LDlOdwLElFOgYgVZ74x:bi7ch66)*

**Comment by benesch** [comment]
Looks like a flake related to the Yarn registry being down. Triggered a rerun by hitting the "Run" button on the build. Do you have the TC permissions to do the same yet, @emsal1863?

**Comment by emsal1863** [comment]
@benesch I do not

**Comment by emsal1863** [comment]
@benesch Done

**Comment by benesch** [comment]
Great, you should be all set. Let me know if you don't see the "Run" button
on TC builds now.

**Comment by knz** [comment]
Looks better. But have you opened Reviewable to check the open comments? It looks like you haven't and there is still a comment open.

Also, the title of the commit itself should also start with a scope prefix `sql:` like the PR title does.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-LDmFUIG560V1jK_Hb5E:-LDmFUIG560V1jK_Hb5F:b-kotju1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2aab4fef79814d274f60992a9a7df90dd5d28a/pkg/sql/sem/tree/eval.go#L917)):*
> ```Go
> 
> 					j, _, err = j.RemoveString(string(MustBeDString(str)))
> ```

I still see an empty line here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-:-LDmFW0p12c_8NkNnd-x:b-gps3sq)*

**Comment by knz** [comment]
And the release note in the commit message still has not the right format.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-:-LDmGAa-43RVzrUF9XJj:b-lf9r13)*

**Comment by emsal1863** [comment]
@knz empty line issue should be fixed.

to clarify, is the extent of the release note formatting change placing the category in brackets like `(sql change)`?

**Comment by knz** [comment]
yes. The `git commit` command will issue a warning if the format is invalid.

**Comment by knz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-:-LDqPcve4KbEssXUYd0e:bnfp4nl)*

**Comment by emsal1863** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sem/tree/eval.go, line 916 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-LDjtJYDALF6zFClvUwo:-LDqPhoD06P3o7RGDD57:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a6907f56888db34f6f8c27d48837be3ebf4c6e7/pkg/sql/sem/tree/eval.go#L916)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Sorry I wasn't clear. The definition of `err` may or may not be separated from the line after by an empty line, but that's not what I was looking at.

I was looking at the *test* on `err` (`if err != nil`). That test must *not* be separated from the assignment to `err` by an empty line.


</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval.go, line 917 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26183#-LDmFUIG560V1jK_Hb5E:-LDqPguK1X_XlL-iiXPJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b2aab4fef79814d274f60992a9a7df90dd5d28a/pkg/sql/sem/tree/eval.go#L917)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I still see an empty line here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26183)*

**Pull request merged**
