### PR TITLE
roachtest: refactor github issue posting and expose actual vm args for reporting

### LINKED ISSUE #81846: roachtest: refactor ClusterSpec to allow easier reporting of configs
`ClusterSpec`[1] is the struct that defines the infrastructure where a roachtest will run. Some fields in that struct are defined via a command line flag (e.g., `cloud`) and never changed again, while others may or may not be specified by tests and are resolved later when left blank (e.g., `InstanceType`, whether to use ZFS, encryption-at-rest, etc).

When a value is not specified and is resolved later, it is often not easy to find the value used. For instance, tests can opt-in to randomly use ZFS (`RandomlyUseZfs`).  When enabled, there's a 20% chance of running with ZFS [2]; however, there's no easy way to report whether ZFS was used in a test failure because that value is not exported in a way that is easy to consume by other callers (most notably, when reporting parameters for a test failure [3]). This same happens for instance/machine type [4] and encryption-at-rest [5].

Ideally, we want to be able to have all these computed values easily accessible to higher layers in the stack when we report test failures.

Related issues and pull requests: #80799, #81845.

[1] https://github.com/cockroachdb/cockroach/blob/467a86fced31ef7c011f3bb8ab47499c6a6f497b/pkg/cmd/roachtest/spec/cluster_spec.go#L39-L62?plain=1
[2] https://github.com/cockroachdb/cockroach/blob/467a86fced31ef7c011f3bb8ab47499c6a6f497b/pkg/cmd/roachtest/spec/cluster_spec.go#L225-L230?plain=1
[3] https://github.com/cockroachdb/cockroach/blob/467a86fced31ef7c011f3bb8ab47499c6a6f497b/pkg/cmd/internal/issues/formatter_unit.go#L76?plain=1
[4] https://github.com/cockroachdb/cockroach/blob/467a86fced31ef7c011f3bb8ab47499c6a6f497b/pkg/cmd/roachtest/spec/cluster_spec.go#L192-L200?plain=1
[5] https://github.com/cockroachdb/cockroach/blob/467a86fced31ef7c011f3bb8ab47499c6a6f497b/pkg/cmd/roachtest/test_runner.go#L606-L616?plain=1

Jira issue: CRDB-16093

### PR DESCRIPTION
**Pull request by smg260**
The change is split into 2 commits. 
1. More strictly addresses [81846](https://github.com/cockroachdb/cockroach/issues/81846).  Also addresses [this](https://github.com/cockroachdb/cockroach/pull/87304/files#diff-1e3ec1fc5bade2df4b8681c44959be2a390f703839f30a979da98f963769c9fcR1046) existing TODO
2. Refactors functions related to posting an issue to github into a separate source file and adds tests.

These commits can be squashed but are separate at the moment for convenience. 

Resolves: https://github.com/cockroachdb/cockroach/issues/81846

Release justification: test-only change
Release note: none

### CODE REVIEW

**Review by renatolabs — CHANGES_REQUESTED** [review]
Great job, thanks for all the refactorings!

A couple of comments/notes:

* Could you add more detailed commit descriptions to your commits? I feel like they (especially the first one) could use some context for the change.
* Now that we have access to the `vm.CreateOpts`, another parameter we can include in the reports is if we are using local SSD

Something I've been thinking about lately that relates to this PR is that it would be nice if we had an API where we could aggregate relevant state during the execution of a test, and that state was reported in case the test failed. Something like `t.SetParam("seed", seed)`. The rationale is that tests currently log this type of granular data and they are often necessary to understand what a test did or to help reproduce it (such as a pseudo-random seed, as an example). So the roachtest framework could add its own parameters (prefixed with `ROACHTEST_` as they are today), but we would also expose the ability for test writers to add test-specific context. I feel like this would be helpful especially in cases where we have multiple failures in a single GitHub issue; it allows us to get a quick glimpse of these parameters in the issue report itself, perhaps even surfacing patterns.

We don't need to adopt something like this for this PR, just wanted to hear if anyone has thoughts on this. 

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-:-NBONr_AAYDK5Xx64wJ6:b-lzmdga)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

___
*[`pkg/cmd/roachtest/github.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO8P6k14qTHRYYiOnH:-NBO8P6k14qTHRYYiOnI:bcrwnum) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L27)):*
> ```Go
> )
> 
> type githubIssues interface {
> ```

We don't need the interface in this case, as it doesn't add much value. If we want to indicate to outside callers which methods on `githubIssues` they should call, we can use upper and lowercase method names, to mimic public and private methods. 
___
*[`pkg/cmd/roachtest/github.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFRmj8Jsmc1FsWPEJ:-NBOFRmj8Jsmc1FsWPEK:b12gdb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L41)):*
> ```Go
> 	cluster      *clusterImpl
> 	vmCreateOpts *vm.CreateOpts
> 	issuePoster  func(ctx context.Context, formatter issues.IssueFormatter, req issues.PostRequest) error
> ```

The signature here was taken from `issues.Post`, I believe. It creates an unnecessary coupling and as far as I can tell, we are only injecting this function like this in order to test `maybePost`. Suggestion: what if instead this struct had a method `buildRequest` that created the `issues.PostRequest` that you want to test. You could then have unit tests for `shouldPost` and `buildRequest`, making `maybePost` dumb enough to not require unit tests (just `shouldPost` + `issues.Post`).
___
*[`pkg/cmd/roachtest/github.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOBVvd0GnlL_oFwN9A:-NBOBVvd0GnlL_oFwN9B:bs5wk2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L52)):*
> ```Go
> 		t.Spec().(*registry.TestSpec).Cluster.NodeCount > 0
> }
> func roachtestPrefix(p string) string {
> ```

Don't you need a newline here? I thought the formatter would add that automatically.
___
*[`pkg/cmd/roachtest/github_test.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFzm2AkNjiRGkiQGZ:-NBOFzm44anYQ0jqlyZ2:bmb2wos) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

We should use `2022` here as this is a new file.
___
*[`pkg/cmd/roachtest/github_test.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOGSUn0QhDMLM6Mytq:-NBOGSUn0QhDMLM6Mytr:bl9upih) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L35)):*
> ```Go
> 
> 	data := []byte(teams)
> 	err := os.WriteFile("TEAMS.yaml", data, 0644)
> ```

Running this test will lead to a `TEAMS.yaml` being created, which is not ideal. We could delete the file after the test.

*Or*, perhaps a better approach is to use `loadTeams()` instead of `DefaultLoadTeams()`. The former is already overwritten during tests. You could even specify your own version here if necessary.
___
*[`pkg/cmd/roachtest/github_test.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOL8Gx68kSkbWAvTxz:-NBOL8Gx68kSkbWAvTy-:bwk12wo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L103)):*
> ```Go
> 		testSpec := &registry.TestSpec{
> 			Name:    "githubPost",
> 			Owner:   "unowned",
> ```

Can be replaced by `OwnerUnitTest`.
___
*[`pkg/cmd/roachtest/github_test.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOLCiu3OIlYJLXRyjG:-NBOLCiu3OIlYJLXRyjH:b-ubw7nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L104)):*
> ```Go
> 			Name:    "githubPost",
> 			Owner:   "unowned",
> 			Run:     func(ctx context.Context, t test.Test, c cluster.Cluster) {},
> ```

Doesn't need to be specified.
___
*[`pkg/cmd/roachtest/github_test.go` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOKQkN76USZQ_BtslI:-NBOKQkN76USZQ_BtslJ:bhs9st) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L127)):*
> ```Go
> 			cluster:      testClusterImpl,
> 			l:            nilLogger(),
> 			issuePoster: func(ctx context.Context, formatter issues.IssueFormatter, req issues.PostRequest) error {
> ```

All of the assertions here could be simplified if we use `github.com/stretchr/testify/require` (e.g., `require.Equal(t, a, b)`
___
*[`pkg/cmd/roachtest/test_runner.go` line 1135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO7hs53AaHYKZlgmFI:-NBO7hs53AaHYKZlgmFJ:b-ozh7te) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd85617b70259ca24b232d6a21442c0e8fe4bbc2/pkg/cmd/roachtest/test_runner.go#L1135)):*
> ```Go
> 
> // TODO(tbg): nothing in this method should have the `t`; they should have a `Logger` only.
> // Maybe done
> ```

Seems like the TODO has been addressed, right? We can remove the comment.

**Review by smg260 — COMMENTED** [review]
Yes you're absolutely right. I will absolutely amend the commit messages. 

It makes sense to me being able to specify a seed for probabilistic branches in the tests, which also is not a big change to make. 


Another thing worth thinking about is as we improve reporting and information on issues, are they being presented in the best way possible. That's not to say pushing these values via additional `parameters` is not adequate, but the more information we pass, the more information an engineer has to parse. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-:-NBSrkqb0IOQJtiU7Nn4:b-7f1ai9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @smg260, @srosenberg, and @tbg)

___
*[`pkg/cmd/roachtest/github.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO8P6k14qTHRYYiOnH:-NBSm3YD4hBvKPts-Sy-:b6rrfmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L27)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We don't need the interface in this case, as it doesn't add much value. If we want to indicate to outside callers which methods on `githubIssues` they should call, we can use upper and lowercase method names, to mimic public and private methods. 
</blockquote></details>

Does having the interface makes it easier to ultimately increase coverage of `runTest` in `test_runner.go`? My immediate thought was to abstract it since it is making an external call - though I can see it makes little sense as private functions.
___
*[`pkg/cmd/roachtest/github.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFRmj8Jsmc1FsWPEJ:-NBSmpncATasQMIUooBv:bkmsxr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L41)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

The signature here was taken from `issues.Post`, I believe. It creates an unnecessary coupling and as far as I can tell, we are only injecting this function like this in order to test `maybePost`. Suggestion: what if instead this struct had a method `buildRequest` that created the `issues.PostRequest` that you want to test. You could then have unit tests for `shouldPost` and `buildRequest`, making `maybePost` dumb enough to not require unit tests (just `shouldPost` + `issues.Post`).
</blockquote></details>

Agreed, and it was my initial approach as well, but wanted to keep this refactor as close to the original as possible. I will make this change.
___
*[`pkg/cmd/roachtest/github.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOBVvd0GnlL_oFwN9A:-NBSn9V6E-lWVzxeLbH9:b-ea8mof) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L52)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Don't you need a newline here? I thought the formatter would add that automatically.
</blockquote></details>

Formatter was being pretty aggressive everywhere - not sure why it wasn't here.
___
*[`pkg/cmd/roachtest/github_test.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFzm2AkNjiRGkiQGZ:-NBSnIndDqnw3S3qxHkH:batcsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L1)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

We should use `2022` here as this is a new file.
</blockquote></details>

Will do, thanks
___
*[`pkg/cmd/roachtest/github_test.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOGSUn0QhDMLM6Mytq:-NBSnPRY2uZ0Kb1BITTI:b-mvn84z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L35)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Running this test will lead to a `TEAMS.yaml` being created, which is not ideal. We could delete the file after the test.

*Or*, perhaps a better approach is to use `loadTeams()` instead of `DefaultLoadTeams()`. The former is already overwritten during tests. You could even specify your own version here if necessary.
</blockquote></details>

I don't think there's anything inherently bad about creating files in a unit test and afaik, they are run in a sandboxed environment. 

`LoadTeams` would require another argument to be passed in (`io.Reader`) by the caller. 
___
*[`pkg/cmd/roachtest/github_test.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOL8Gx68kSkbWAvTxz:-NBSphEZ1UnvrK3X0HAy:bebrt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L103)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Can be replaced by `OwnerUnitTest`.
</blockquote></details>

Will do
___
*[`pkg/cmd/roachtest/github_test.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOLCiu3OIlYJLXRyjG:-NBSqav98y9hObON2KIQ:b-usahqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L104)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Doesn't need to be specified.
</blockquote></details>

you're right - I was initially looking at `test_runner.go` which explicitly checks that `Run` is specified
___
*[`pkg/cmd/roachtest/github_test.go` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOKQkN76USZQ_BtslI:-NBSqn5F3fpeUoas4tq_:brkzo9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L127)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

All of the assertions here could be simplified if we use `github.com/stretchr/testify/require` (e.g., `require.Equal(t, a, b)`
</blockquote></details>

Will do - that's much better - thanks.
___
*[`pkg/cmd/roachtest/test_runner.go` line 1135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO7hs53AaHYKZlgmFI:-NBSqtH9Eo6aw68nV_uy:b-h5g115) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd85617b70259ca24b232d6a21442c0e8fe4bbc2/pkg/cmd/roachtest/test_runner.go#L1135)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Seems like the TODO has been addressed, right? We can remove the comment.
</blockquote></details>

Yep - wasn't sure if there was more to it. Looks straightforward but will run by @tbg . This was a boy scout change

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @smg260, @srosenberg, and @tbg)

___
*[`pkg/cmd/roachtest/github.go` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFRmj8Jsmc1FsWPEJ:-NBTFCNzCbozJTCrZxQO:b-g6uvxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L41)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Agreed, and it was my initial approach as well, but wanted to keep this refactor as close to the original as possible. I will make this change.
</blockquote></details>

On 2nd thought, even if I dumb down the maybePost, it is still a method which has branches in it. Regardless of its simplicity, I feel that if branches *can* be covered without compromising the code too much, they should. Injecting the function enables this. 

Regarding coupling, is the code really any more coupled that calling `issues.Post directly`? By its nature, we are coupled to the API signature already.

I think there may be a compromise here somewhere. Let me work it.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @srosenberg, and @tbg)

___
*[`pkg/cmd/roachtest/github_test.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOFzm2AkNjiRGkiQGZ:-NBTqjnl1tACrhOob35K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L1)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Will do, thanks
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/github_test.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOGSUn0QhDMLM6Mytq:-NBTqgg9AEH93rITC5B9:b-x9b4ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L35)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

I don't think there's anything inherently bad about creating files in a unit test and afaik, they are run in a sandboxed environment. 

`LoadTeams` would require another argument to be passed in (`io.Reader`) by the caller. 


</blockquote></details>

Refactored
___
*[`pkg/cmd/roachtest/github_test.go` line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOL8Gx68kSkbWAvTxz:-NBTqYtG2Lwqo8MwmfC6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L103)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/github_test.go` line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOLCiu3OIlYJLXRyjG:-NBTTTzi0HZvHNhM2-A-:bd4rwpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L104)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

you're right - I was initially looking at `test_runner.go` which explicitly checks that `Run` is specified
</blockquote></details>

`shouldPost` actually checks for `Run` - so this is required
___
*[`pkg/cmd/roachtest/github_test.go` line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBOKQkN76USZQ_BtslI:-NBTq_YV6kVYMBvu_3qy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github_test.go#L127)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Will do - that's much better - thanks.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/test_runner.go` line 1135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO7hs53AaHYKZlgmFI:-NBXXHZkEcf3NT_PdoMs:bcv7m2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd85617b70259ca24b232d6a21442c0e8fe4bbc2/pkg/cmd/roachtest/test_runner.go#L1135)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Yep - wasn't sure if there was more to it. Looks straightforward but will run by @tbg . This was a boy scout change
</blockquote></details>

Yessir! Looking good.

**Comment by smg260** [comment]
Sorry for the notification to review everyone. Looks like it was caused by an erroneous rebase.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Great job!

> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-:-NCLMCAh3m79YRwmopHq:b-45zx5k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/github_test.go` line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NCLLoUL6YRn_QkUKxM5:-NCLLoUL6YRn_QkUKxM6:b-52zmwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7427e51f4492ab5b17123c406b0dd692640dcab/pkg/cmd/roachtest/github_test.go#L197)):*
> ```Go
> 						require.Equal(t, v, req.ExtraParams[k])
> 					}
> 				}
> ```

Is this needed? I thought the `require` call above would be sufficient.
___
*[`pkg/cmd/roachtest/github_test.go` line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NCLLv3wARlF5rHd1bh6:-NCLLv3wARlF5rHd1bh7:b-55v5x6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7427e51f4492ab5b17123c406b0dd692640dcab/pkg/cmd/roachtest/github_test.go#L204)):*
> ```Go
> 				require.Equal(t, "release-blocker", lastLabel)
> 			} else {
> 				require.Equal(t, "O-roachtest", lastLabel)
> ```

Nit: from the test's perspective, all we care about is that we have the `O-roachtest` label, and -- conditionally -- the `release-blocker` label. So we could change the test to look for the presence of the labels, rather than their position in the array to make it less tied to the implementation.

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87304)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/github.go` line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NBO8P6k14qTHRYYiOnH:-NBXu-XIEzA0G00YNPC9:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6f21eea7607d2699d6dfddb38e3e24abb078e9/pkg/cmd/roachtest/github.go#L27)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Does having the interface makes it easier to ultimately increase coverage of `runTest` in `test_runner.go`? My immediate thought was to abstract it since it is making an external call - though I can see it makes little sense as private functions.
</blockquote></details>

Done
___
*[`pkg/cmd/roachtest/github_test.go` line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NCLLoUL6YRn_QkUKxM5:-NCNRYWw86u7OSNpj-Pz:b-aiv0gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7427e51f4492ab5b17123c406b0dd692640dcab/pkg/cmd/roachtest/github_test.go#L197)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is this needed? I thought the `require` call above would be sufficient.
</blockquote></details>

:facepalm:  Fixed. 
___
*[`pkg/cmd/roachtest/github_test.go` line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/87304#-NCLLv3wARlF5rHd1bh6:-NCNSBTVCZ5Qh5hE9sNQ:b-h620tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7427e51f4492ab5b17123c406b0dd692640dcab/pkg/cmd/roachtest/github_test.go#L204)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: from the test's perspective, all we care about is that we have the `O-roachtest` label, and -- conditionally -- the `release-blocker` label. So we could change the test to look for the presence of the labels, rather than their position in the array to make it less tied to the implementation.
</blockquote></details>

Yes you're right. I was trying to avoid iterating over the slice but we have an existing utility. Fixed

**Comment by smg260** [comment]
bors r=renatolabs

**Comment by smg260** [comment]
blathers backport 22.2

**Pull request merged**
