### PR TITLE
multitenant: listen for setting overrides

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### settings: add EncodedValue proto, update tenant settings API

This commit consolidates multiple uses of encoded setting values (raw
value and type strings) into a `settings.EncodedValue` proto.

The tenant settings roachpb API (not used yet) is updated to use this.

Release note: None

#### multitenant: listen for setting overrides

This implements the tenant side code for setting overrides.
Specifically, the tenant connector now implements the
`OverridesMonitor` interface using the `TenantSettings` API.

The server side of this API is not yet implemented, so this commit
does not include end-to-end tests. Basic functionality is verified
through a unit test that mocks the server-side API.

Informs #73857.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Friendly ping.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75711#-:-MuvQ1iL7hoJEFFxJRCU:b-u78c44)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75711#-:-MvHVizp4hbK8IwpMRMk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @RaduBerinde)

___
*[pkg/ccl/kvccl/kvtenantccl/setting_overrides.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75711#-MvHV96AAGKQO_bLq-fz:-MvHV96AAGKQO_bLq-g-:bfg95j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/01d5134275e8d789fbcf727253d6ad4131e888ca/pkg/ccl/kvccl/kvtenantccl/setting_overrides.go#L85)):*
> ```Go
> 	if firstEventInStream && e.Incremental {
> 		return errors.Newf("first event must not be Incremental")
> 	}
> ```

This check happens here and above this call. The handling seems the same. Pick one? Maybe remove this one?



_Code quote:_
```Go
	if firstEventInStream && e.Incremental {
		return errors.Newf("first event must not be Incremental")
	}
```

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75711#-:-MvPa4uI2RaeGO4K9XIC:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Pull request merged**
