### PR TITLE
server: replace stored context with AmbientContext

### PR DESCRIPTION
**Pull request by RaduBerinde**
Also, we now open spans for periodic checks and usage reporting.

Part of #9807. CC @andreimatei @tamird @tschottdorf

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9925)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTuuCnOPxg1YUq9yii2:b-8qh4yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
> ```Go
> 	nodeLogTagVal log.DynamicIntValue
> 
> 	log.AmbientContext
> ```

cfg is already embedded by value (meaning copied from the caller), why not use its AmbientContext instead of adding another member?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-:-KTuuRDCsjPU6xxdAUqA:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTv8NGEqDhPVtz2RfpS:b-6mnvze) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> cfg is already embedded by value (meaning copied from the caller), why not use its AmbientContext instead of adding another member?
</details>
I was plannning to make embedding it the pattern everywhere. Primarily so we can just call `s.AnnotateCtx()`. It also feels a bit off to modify stuff in `cfg`.

If you feel strongly, I can do it and add a `server.AnnotateCtx()` method as a convenience.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTv9vzvZOCa_6iNZkw3:b7gnw5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I was plannning to make embedding it the pattern everywhere. Primarily so we can just call `s.AnnotateCtx()`. It also feels a bit off to modify stuff in `cfg`.
> 
> If you feel strongly, I can do it and add a `server.AnnotateCtx()` method as a convenience.
</details>
I don't feel strongly, just weird to have two ways of getting to an ambient context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTvAG7PlTIQjv14cGR6:bjchq57) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I don't feel strongly, just weird to have two ways of getting to an ambient context.
</details>
Fair point, I'll try it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTvBNUlarbXzzWZygwd:b-3rcsc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Fair point, I'll try it out.
</details>
Ah, there are two versions of `AnnotateCtx` we would need to wrap, I'd rather leave it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/server.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-KTuuCnOPxg1YUq9yii1:-KTvCvn9CvDvV3wHbrqA:bjmu33u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab2b0be213ed22bd751238d67d8efed19ed7be8a/pkg/server/server.go#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, there are two versions of `AnnotateCtx` we would need to wrap, I'd rather leave it as is.
</details>
On second (third?) thought, updated :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925)*

**Comment by tamird** [comment]
:100: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9925#-:-KTvFEayvr-6BrKwAYfn:bmi8ppe)*

**Pull request merged**
