### PR TITLE
server: avoid missing service mode changes 

### LINKED ISSUE #112077: server: server orchestrator can fail to start tenant
Seen [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12121007&buildTypeId=Cockroach_BazelExtendedCi) on #110932 that shouldn't cause this flake:
```
Failed
=== RUN   TestRevertTenantToTimestamp/reverts_changes_inside_a_tenant
    stream_ingestion_manager_test.go:85: condition failed to evaluate within 45s: pq: service unavailable for target tenant (target)
    --- FAIL: TestRevertTenantToTimestamp/reverts_changes_inside_a_tenant (46.91s)
```
I'm assuming we want to skip this test under stress.

Jira issue: CRDB-32225

### PR DESCRIPTION
**Pull request by stevendanna**
In https://github.com/cockroachdb/cockroach/pull/112001 we introduced a bug and an unintended behaviour change.

The bug is that if we receive a notification of a state change from
none to shared when the server is still shutting down, that state
change will be ignored. Namely, the following can happen:

1. ALTER VIRTUAL CLUSTER a STOP SERVICE
2. Watcher gets notification of shutdown and notifies virtual
   cluster's SQL server.
3. Tenant 1 starts shutdown but does not fully complete it
4. ALTER VIRTUAL CLUSTER a START SERVICE SHARED
5. Watcher notifies the server orchestrator; but, since the SQL server has
   not finished stopping from the previous stop request, it appears as if
   it is already started.
6. Tenant 1 finishes shutdown.
7. Server orchestrator never again tries to start the virtual cluster.

The newly added test reveals this under stress.

The behaviour change is that previously if a SQL server for a virtual
cluster failed to start up, it would previously be restarted.

Here, we fix both of these by re-introducing a periodic polling of the
service state.  Unlike the previous polling, we poll the watcher state
so we are not generating a SQL query every second.

Further, since we are now calling the tenantcapabailities watcher
GetAllTenants method every second in addition to on every update, I've
moved where we allocate the list of all tenants to our handle update
call.

An alternative here would be to revert https://github.com/cockroachdb/cockroach/pull/112001 completely.  I think
there are still advantage to using the watcher: not generating a SQL
query on every node once per second and after the integration of

Fixes https://github.com/cockroachdb/cockroach/issues/112077

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
First commit is https://github.com/cockroachdb/cockroach/pull/112166

**Review by adityamaru — APPROVED** [review]

**Review by adityamaru — APPROVED** [review]
This LGTM, but this is my first time reading this code so let's wait for Yahor too to give this a thumb

**Review by yuzefovich — APPROVED** [review]
Seems reasonable to me too, :lgtm:

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112295#-:-Ngdy51w8oUty6KwckHZ:b2qc2nv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`-- commits` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112295#-Ngdt-sr2H1Qi8STChRA):*
nit: "tenant 1" and VC "a" is the same virtual cluster, right?
___
*[`-- commits` line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112295#-Ngdx1zgA1Kb1IzpeCDm):*
nit: incomplete sentence.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112295#-Ngdsg7I-xRi9p72cVtv:-Ngdsg7I-xRi9p72cVtw:b-f3o33d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ca95ae6719967bc3db3c5caa862a2470f8aaa60/pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go#L53)):*
> ```Go
> 		allTenants []tenantcapabilities.Entry
> 
> 		// anyChangeChs is closed on any change to the set of
> ```

nit: `s/anyChangeChs/anyChangeCh/`.
___
*[`pkg/server/server_controller_test.go` line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112295#-Ngdxd0WCqgRd2DFoGtB:-Ngdxd0X3qUmFIRoe2Zr:b-e19h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ca95ae6719967bc3db3c5caa862a2470f8aaa60/pkg/server/server_controller_test.go#L75)):*
> ```Go
> }
> 
> // TestServerControllStopStart is, when run under stress, a regression
> ```

nit: `s/TestServerControllStopStart/TestServerControllerStopStart/`.

**Comment by stevendanna** [comment]
bors r=adityamaru,yuzefovich

**Pull request merged**
