### PR TITLE
server: report more configuration upon initialization.

### LINKED ISSUE #16207: server: Log memory info at startup
We've had a number of users report crashes that appear to be caused by running out of memory (either explicit failures to allocate more memory or logs that end abruptly because the process was terminated by the OOM killer). We often have to ask these users how much memory they've allocated to the VM even after they've sent us their logs. We should collect this information in the logs automatically by logging the amount of physical memory we believe to be available (and the cgroup limit).

### PR DESCRIPTION
**Pull request by knz**
Fixes #16207.

### CODE REVIEW

**Comment by knz** [comment]
Example output:
```
I170530 18:11:44.545553 1 server/config.go:281  available memory from cgroups (8.0 EiB) exceeds system memory 7.8 GiB, using system memory
I170530 18:11:44.545604 1 server/config.go:345  system total memory: 7.8 GiB
I170530 18:11:44.545614 1 server/config.go:347  server configuration:
I170530 18:11:44.545632 1 server/config.go:348  - max offset: 500ms
I170530 18:11:44.545641 1 server/config.go:349  - cache size: 1.9 GiB
I170530 18:11:44.545650 1 server/config.go:350  - SQL memory pool size: 1.9 GiB
I170530 18:11:44.545663 1 server/config.go:351  - scan interval: 10m0s
I170530 18:11:44.545705 1 server/config.go:352  - scan max idle time: 200ms
I170530 18:11:44.545793 1 server/config.go:353  - consistency check interval: 24h0m0s
I170530 18:11:44.545806 1 server/config.go:354  - metrics sample interval: 10s
I170530 18:11:44.545820 1 server/config.go:355  - time until store dead: 5m0s
I170530 18:11:44.545834 1 server/config.go:356  - send next timeout: 500ms
I170530 18:11:44.545847 1 server/config.go:357  - pending RPC timeout: 1m0s
I170530 18:11:44.545859 1 server/config.go:358  - event log enabled: true
I170530 18:11:44.545871 1 server/config.go:359  - linearizable: false
I170530 18:11:44.546090 13 cli/start.go:340  starting cockroach node
I170530 18:11:44.552847 13 storage/engine/rocksdb.go:379  opening rocksdb instance at "/home/kena/cockroach/cockroach-data"
I170530 18:11:44.867136 13 server/config.go:459  1 storage engine initialized
I170530 18:11:44.867180 13 server/config.go:461  RocksDB cache size: 1.9 GiB
I170530 18:11:44.867189 13 server/config.go:461  store 0: RocksDB, max size 0 B, max open file limit -1
```

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-:-KlPiML-k_Vxizlsviu-:bnfp4nl)*

**Comment by a-robinson** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/server/config.go, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPhprjM_Go8SUVOpmQ:-KlPhprjM_Go8SUVOpmR:bpf6rlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L261)):*
> ```Go
> 	var buf []byte
> 	if buf, err = ioutil.ReadFile(defaultCGroupMemPath); err != nil {
> 		log.Infof(context.TODO(), "can't read available memory from cgroups (%s), using system memory %s instead", err,
> ```

You don't have to, but it'd have been nice to plumb the context in here

---

*[pkg/server/config.go, line 349 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPiLOvlsPJ0Yn0Ja8G:-KlPiLOvlsPJ0Yn0Ja8H:b2amway) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L349)):*
> ```Go
> 		log.Infof(ctx, "system total memory: %s", humanizeutil.IBytes(memSize))
> 	}
> 	log.Info(ctx, "server configuration:")
> ```

Any reason why we're putting each of these settings into a separate log message? Our logging does support multi-line messages (and already emits them in certain other places), and that would probably be more readable than having the long log prefix on each line before each config item.

Along the same lines, if it didn't print directly to the log, this printing of the Config object might make sense as a `(*Config).String()` method.

---

*[pkg/server/config.go, line 433 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPjNj8VAqSzNZxGPbO:-KlPjNj8VAqSzNZxGPbP:b-224v0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L433)):*
> ```Go
> 			}
> 			details = append(details, fmt.Sprintf("store %d: in-memory, size %s\n",
> 				i, humanizeutil.IBytes(sizeInBytes)))
> ```

I don't think you want the trailing newline on this or the message below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209)*

**Comment by knz** [comment]
As per Alex' suggestion, output changed to:
```
I170530 19:13:38.857967 1 server/config.go:381  server configuration:
max offset                   500ms
cache size                   1.9 GiB
SQL memory pool size         1.9 GiB
scan interval                10m0s
scan max idle time           200ms
consistency check interval   24h0m0s
metrics sample interval      10s
time until store dead        5m0s
send next timeout            500ms
pending RPC timeout          1m0s
event log enabled            true
linearizable                 false
```

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/config.go, line 261 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPhprjM_Go8SUVOpmQ:-KlPkUQoKSy-CSmMGkTj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L261)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You don't have to, but it'd have been nice to plumb the context in here
</blockquote></details>

Done.

---

*[pkg/server/config.go, line 349 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPiLOvlsPJ0Yn0Ja8G:-KlPkVBNPr_wXGSq4sBn:b-shb0sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L349)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Any reason why we're putting each of these settings into a separate log message? Our logging does support multi-line messages (and already emits them in certain other places), and that would probably be more readable than having the long log prefix on each line before each config item.

Along the same lines, if it didn't print directly to the log, this printing of the Config object might make sense as a `(*Config).String()` method.
</blockquote></details>

Our logging supports multi-line messages but does not insert a timestamp prefix on every line after the first... nevertheless, I like the idea of a `String()` method.
Done.

---

*[pkg/server/config.go, line 433 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPjNj8VAqSzNZxGPbO:-KlPkdu1r7BQqEV6aoaI:b-376vyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/867012367b688354bde33de023a44920318400ae/pkg/server/config.go#L433)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't think you want the trailing newline on this or the message below
</blockquote></details>

Done. Good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-:-KlPlv-0zqnJBIrWmWPq:b-ktcot4)*

**Comment by a-robinson** [comment]
Thanks, :lgtm_strong: 

---

Reviewed 1 of 4 files at r3.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/config.go, line 346 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPnQWu3szlX_vO6j4N:-KlPnQWv1ca0ACJyGfQN:b-3lhh0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6984aba7840caa012e3be9ecaa32044a14d8f0/pkg/server/config.go#L346)):*
> ```Go
> 
> // String implements the fmt.Stringer interface.
> func (cfg *Config) String() string {
> ```

The one thing I worry about here is that we're just ignoring the contents `base.Config`, but this is definitely good enough for our current purposes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-:-KlPngoa3WRFEK3tWRg7:b8qikpc)*

**Comment by knz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/config.go, line 346 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209#-KlPnQWu3szlX_vO6j4N:-KlPq7F7ELsdmDFt0L6o:b-netvdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6984aba7840caa012e3be9ecaa32044a14d8f0/pkg/server/config.go#L346)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The one thing I worry about here is that we're just ignoring the contents `base.Config`, but this is definitely good enough for our current purposes.
</blockquote></details>

My reasoning, correct me if I'm wrong, is that most of the customizable other settings are already reported in the start-up message below. I wanted to avoid duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16209)*

**Pull request merged**
