### PR TITLE
sql: Improve error message for PREPARE/EXECUTE stmts

### PR DESCRIPTION
**Pull request by nvb**
This links the error messages back to the open issue.

Requested by @jseldess

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7667)

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

**Comment by tamird** [comment]
Pedantic: those statements are not supported at all. What the wire protocol does is not a statement.

**Comment by jseldess** [comment]
@tamird, @nvanbenschoten: Would it be more accurate to avoid the statement names and say something like this?

- Prepared statements are supported only via the Postgres wire protocol
- Executing prepared statements is supported only via the Postgres wire protocol

Some alternatives:

- Statements can be prepared for server-side execution only via the Postgres wire protocol
- Prepared statements can be executed server-side only via the Postgres wire protocol
 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7667#-:-KM1oIBvgnN1snh3CuSa:-784022444)*

**Comment by tamird** [comment]
@jseldess both proposals LGTM.

**Comment by nvanbenschoten** [comment]
Good point, done.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7667#-:-KM4hELm6bTWxVcbGt6o:926693478)*

**Comment by jseldess** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7667#-:-KM4i8q6wCee2p8CqHdp:1417088721)*

**Comment by jseldess** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7667)*

**Pull request merged**
