### PR TITLE
settings: code cleanup and improvements

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### setting: clean up DefaultString

It makes no sense for this method to return an error, especially when
the `String()` method doesn't. This was the consequence of a
round-about way of implementing it.

Epic: none
Release note: None

#### settings: add decodeAndSet/decodeAndSetDefaultOverride methods

Replace type switches with methods.

Epic: none
Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @shubhamdhama)

___
*[`pkg/settings/protobuf.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125644#-O-LvWBe5DbGshtRjfp1:-O-LvWBe5DbGshtRjfp2:b2g0ilp) ([raw file](https://github.com/cockroachdb/cockroach/blob/be38883cee4bfa784f22ab9cf259c65d9f43936e/pkg/settings/protobuf.go#L52)):*
> ```Go
> 	json, err := s.MarshalToJSON(s.defaultValue)
> 	if err != nil {
> 		panic(errors.Wrapf(err, "marshaling %s: %+v", proto.MessageName(s.defaultValue), s.defaultValue))
> ```

this doesn't seem ideal - does this mean that an error with serializing a protobuf setting will crash the node? previously it would have displayed an error.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @shubhamdhama)

___
*[`pkg/settings/protobuf.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125644#-O-LvWBe5DbGshtRjfp1:-O-M48z6CrSMRTqB1wlA:b51tgn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/be38883cee4bfa784f22ab9cf259c65d9f43936e/pkg/settings/protobuf.go#L52)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this doesn't seem ideal - does this mean that an error with serializing a protobuf setting will crash the node? previously it would have displayed an error.
</blockquote></details>

This is the default value we set from the code. If that can't be serialized, then we should crash.. In any case, we crash above in `String()` just the same.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @shubhamdhama)

___
*[`pkg/settings/protobuf.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125644#-O-LvWBe5DbGshtRjfp1:-O-M6Bg26ECLqoGxHqgR:baityby) ([raw file](https://github.com/cockroachdb/cockroach/blob/be38883cee4bfa784f22ab9cf259c65d9f43936e/pkg/settings/protobuf.go#L52)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is the default value we set from the code. If that can't be serialized, then we should crash.. In any case, we crash above in `String()` just the same.
</blockquote></details>

i see, thanks for pointing that out.

**Comment by RaduBerinde** [comment]
*[`pkg/settings/protobuf.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125644#-O-LvWBe5DbGshtRjfp1:-O-M7kb56kyejU_x_DEi:bktk888) ([raw file](https://github.com/cockroachdb/cockroach/blob/be38883cee4bfa784f22ab9cf259c65d9f43936e/pkg/settings/protobuf.go#L52)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see, thanks for pointing that out.
</blockquote></details>

I filed https://github.com/cockroachdb/cockroach/issues/125685

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
