### PR TITLE
storage: Move SSTWriter to engine, use it instead of Rocks-based writer

### LINKED ISSUE #41657: storage: use pebble.sstable.Writer for writing to sstables instead of the SstFileWriter in RocksDB
Currently, the C++ based `RocksDBSstFileWriter` is used in a couple places in storage code - `replica_sst_snapshot_storage.go`, `store_remove_replica.go`, etc, to name a few. There's a similar SST writer, `SSTWriter`, in `pkg/storage/bulk/sst_writer.go` that uses pebble's `sstable.Writer`.

This issue involves replacing usage of the RocksDB-based writer with that of the pebble-based one written in Go, at least when the flag `--storage-engine pebble` is specified at runtime. If backward compatibility with RocksDB is not a concern, then the pebble-based writer should be used regardless of the chosen storage engine.

### PR DESCRIPTION
**Pull request by itsbilal**
Currently, we use `RocksDBSstFileWriter` for writing SSTs when receiving cockroach snapshots. This incurs some extra performance overhead with cgo crossings that we can avoid by using the `sstable.Writer` in pebble.

This PR moves a wrapper for the Pebble-based writer that currently resides in `bulk` to `engine`, then adds methods to it so it could be used as a drop-in replacement (almost) for the RocksDB writer. In the second commit, all non-test uses of `RocksDBSstFileWriter` are moved to `SSTWriter`.

Parts taken from #39802 , and fixes #41657.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Looks good, though my comments below indicate that there will be work to do in a follow-on PR.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-Lt5U5RY6wnG9v7Y-VF0:b-7ibfaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/importccl/load.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5Tr2j5kE-zOF_xmGJ:-Lt5Tr2j5kE-zOF_xmGK:bcvabeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a050f75ffe48ed460c8c2a9bee996794a601187/pkg/ccl/importccl/load.go#L365)):*
> ```Go
> 	}
> 
> 	if err := base.WriteFile(ctx, filename, bytes.NewReader(sstContents)); err != nil {
> ```

We build the sstable in memory, only to immediately write it to disk. More evidence that there is further API cleanup needed here (not for this PR).
___
*[pkg/storage/engine/sst_writer.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5S0bsBmO5__OYwwXT:-Lt5S0bsBmO5__OYwwXU:b6a4zpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L27)):*
> ```Go
> 	f  *memFile
> 	// DataSize tracks the total key and value bytes added so far.
> 	DataSize uint64
> ```

What is this used for? `sstable.Writer.EstimatedSize()` will give a more accurate estimation of the final sstable size.
___
*[pkg/storage/engine/sst_writer.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SHj56l0-Jf4y4BFX:-Lt5SHj56l0-Jf4y4BFY:blxzmpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L42)):*
> ```Go
> 		MergerName:              "nullptr",
> 		TablePropertyCollectors: PebbleTablePropertyCollectors,
> 	}
> ```

Better to use `DefaultPebbleOptions().MakeWriterOptions(0)` here and then override `TableFormat` to be LevelDB. That way, changes to the default options show up here.
___
*[pkg/storage/engine/sst_writer.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5T6dn-TtELp-b5tfS:-Lt5T6dn-TtELp-b5tfT:b-wmkica) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L85)):*
> ```Go
> // Truncate returns the in-memory buffer from the previous call to Truncate
> // (or the start), until now.
> func (fw *SSTWriter) Truncate() ([]byte, error) {
> ```

What is this about? Seems like an odd method to exist here. 

Oh, it is used by `multiSSTWriter` to stream the data out to disk. That is just convoluted. We should instead have `SSTWriter` write directly to disk. Can you add a TODO that this method should be removed and `SSTWriter` should take an optional path to write to disk.
___
*[pkg/storage/engine/sst_writer.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5RmQl0D3T5b_L5PmA:-Lt5RmQl0D3T5b_L5PmB:b-2nxu9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L173)):*
> ```Go
> }
> 
> type memFile struct {
> ```

We should expose a writable version of `vfs.NewMemFile`, though I suppose you don't get access to the `data`. 
___
*[pkg/storage/engine/sst_writer.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SvFd8FYfZoaoy6Lv:-Lt5SvFd8FYfZoaoy6Lw:b-uyjfh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L195)):*
> ```Go
> }
> 
> func (f *memFile) ReadAt(p []byte, off int64) (int, error) {
> ```

Do you need `Read` and `ReadAt`? I'm pretty sure `sstable.Writer` doesn't need those methods.

**Review by itsbilal — COMMENTED** [review]
Just went down the rabbit hole and actually updated engine.SSTWriter to take file handles, in the third commit. The stuff in `store_snapshot.go` became a lot simpler as a result. PTAL!

I could also do a fourth commit where I move over the last remaining RocksDBSstFileWriter uses to the pebble one (all in tests), except for the one test that compares the two.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-Lt6pyd_7CvE97vmX5JC:b-zyxem)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/importccl/load.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5Tr2j5kE-zOF_xmGJ:-Lt6oVDwC5c87iGYozVz:bz8ki2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a050f75ffe48ed460c8c2a9bee996794a601187/pkg/ccl/importccl/load.go#L365)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We build the sstable in memory, only to immediately write it to disk. More evidence that there is further API cleanup needed here (not for this PR).
</blockquote></details>

Done. TODO added. This is a particularly annoying instance, the interface that base belongs to doesn't let us get a file handle easily that we could just pass to SSTWriter.
___
*[pkg/storage/engine/sst_writer.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5S0bsBmO5__OYwwXT:-Lt6pawOAshCHBQjAUlA:b3pbci3) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is this used for? `sstable.Writer.EstimatedSize()` will give a more accurate estimation of the final sstable size.
</blockquote></details>

It's used to determine whether we wrote anything of use to the SSTable, and if we should call `SSSS.NewFile()` There are times when EstimatedSize would return a non-zero number while this wouldn't, so it's probably worth keeping.
___
*[pkg/storage/engine/sst_writer.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SHj56l0-Jf4y4BFX:-Lt6paT5-5C0qxRIqUfe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L42)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Better to use `DefaultPebbleOptions().MakeWriterOptions(0)` here and then override `TableFormat` to be LevelDB. That way, changes to the default options show up here.
</blockquote></details>

Done.
___
*[pkg/storage/engine/sst_writer.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5T6dn-TtELp-b5tfS:-Lt6ptT63Nx38NGDZK53:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L85)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

What is this about? Seems like an odd method to exist here. 

Oh, it is used by `multiSSTWriter` to stream the data out to disk. That is just convoluted. We should instead have `SSTWriter` write directly to disk. Can you add a TODO that this method should be removed and `SSTWriter` should take an optional path to write to disk.
</blockquote></details>

Removed.
___
*[pkg/storage/engine/sst_writer.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SvFd8FYfZoaoy6Lv:-Lt6pw6c46l6w3A2-BSl:b-wnfmk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L195)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do you need `Read` and `ReadAt`? I'm pretty sure `sstable.Writer` doesn't need those methods. 
</blockquote></details>

Done. Removed.

**Review by petermattis — APPROVED** [review]
:lgtm:

Given the changes to bulk IO and KV code, @dt and @nvanbenschoten should give this a quick review to make sure we're not messing anything up.

> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-Lt7nhwz-3RCAXoLZEIc:b-qgqw8h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/importccl/load.go, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7kX57AAgIApimtCmj:-Lt7kX57AAgIApimtCmk:bmgch5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/ccl/importccl/load.go#L367)):*
> ```Go
> 
> 	// TODO(itsbilal): Pass a file handle into SSTWriter instead of writing to a
> 	// MemFile first.
> ```

Might be able to snipe @dt or someone else from Bulk IO into doing this. `ExternalStorage` needs to be able to provide a `Writer` interface for uploading data. Shouldn't be difficult.
___
*[pkg/storage/replica_raftstorage.go, line 882 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7mjqO8WIeaSQJidVz:-Lt7mjqO8WIeaSQJidW-:buqxwzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/storage/replica_raftstorage.go#L882)):*
> ```Go
> 	}
> 	if unreplicatedSST.DataSize > 0 {
> 		if err := inSnap.SSSS.WriteSST(ctx, unreplicatedSSTFile.Data()); err != nil {
> ```

This deserves a TODO as it maintains the same strange behavior as previously where we build the sstable in memory and then write it to a file. Better to just build the sstable directly on disk.
___
*[pkg/storage/engine/sst_writer.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SvFd8FYfZoaoy6Lv:-Lt7inb4Ez1RikD3R-d3:b-stsisp) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L195)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Removed.
</blockquote></details>

`Read()` is still present. Is it needed for something?
___
*[pkg/storage/engine/sst_writer_test.go, line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7j3Ql-9dYI5t4d08V:-Lt7j3Ql-9dYI5t4d08W:byj69mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/storage/engine/sst_writer_test.go#L171)):*
> ```Go
> 		_ = makePebbleSST(b, kvs)
> 	}
> 	b.StopTimer()
> ```

How does the benchmark time for building sstables compare between Pebble and RocksDB?

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_raftstorage.go, line 882 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7mjqO8WIeaSQJidVz:-LtBwroX801NSDkUXi4M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/storage/replica_raftstorage.go#L882)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This deserves a TODO as it maintains the same strange behavior as previously where we build the sstable in memory and then write it to a file. Better to just build the sstable directly on disk.
</blockquote></details>

Done.
___
*[pkg/storage/engine/sst_writer.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt5SvFd8FYfZoaoy6Lv:-LtBvGI29kncgsKQsC0z:b-s4mwnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/988ee5edbe636e78bea411691785d33f29729b22/pkg/storage/engine/sst_writer.go#L195)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`Read()` is still present. Is it needed for something?
</blockquote></details>

Nope, don't know why I thought it was being used as part of `writeCloseSyncer`. Removed.
___
*[pkg/storage/engine/sst_writer_test.go, line 171 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7j3Ql-9dYI5t4d08V:-LtBy2zd4prUnFu0ZExN:b-hf4392) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/storage/engine/sst_writer_test.go#L171)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How does the benchmark time for building sstables compare between Pebble and RocksDB?
</blockquote></details>

Comparing just the SSTWriters themselves (which, it's important to note, is only part of the picture though a pretty important part), where old = RocksDBSstFileWriter:

```
name             old time/op   new time/op   delta
WriteSSTable-12   3.95µs ± 3%   2.48µs ± 4%  -37.37%  (p=0.008 n=5+5)

name             old speed     new speed     delta
WriteSSTable-12  301MB/s ± 3%  481MB/s ± 4%  +59.71%  (p=0.008 n=5+5)
```

Any benchmarks around streaming / applying snapshots would also be interesting.

**Comment by itsbilal** [comment]
Resolved merge conflicts, and added a 4th commit that updates all tests using `RocksDBSstFileWriter` to use `SSTWriter` except for the ones that compare the two (or specifically test the RocksDB writer).

**Review by dt — APPROVED** [review]
Did a quick scan of the bulk-IO parts and LGTM.

> Reviewed 1 of 12 files at r6, 1 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-LtQOQ0xEQgIUCufJ6-_:b-t45h97)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @dt, @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/ccl/importccl/load.go, line 367 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-Lt7kX57AAgIApimtCmj:-LtQGJSNDVzpkNDKWW29:b-sky1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c7b84c56f43dcbfa46ecf1b29070aa25449bf9b/pkg/ccl/importccl/load.go#L367)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Might be able to snipe @dt or someone else from Bulk IO into doing this. `ExternalStorage` needs to be able to provide a `Writer` interface for uploading data. Shouldn't be difficult.
</blockquote></details>

Hm, the `Reader` argument to uploads mostly comes from the cloud APIs. Some of the current implementations also rely on being able to `Seek` in the passed content to retry files on failure (in some cases we added this because of flaky cloud providers, others include it internally). Even if we could stick a buffer in the middle to turn a Writer into a Reader, if we switched to a more streaming model where we upload as we write, retries will be tricky (i.e. we might need to build another layer of reties, over the entire request, if we can no longer retry just uploading the result).

Happy to have my name added to the TODO, but I don't know if it'll happen right away.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r3, 12 of 12 files at r6, 6 of 6 files at r7, 11 of 11 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-LtQcYL0-fwfBtaVg6wh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_sst_snapshot_storage.go, line 109 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQaBfN5uStQq4ZfvsS:-LtQaBfN5uStQq4ZfvsT:b3qg5ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/replica_sst_snapshot_storage.go#L109)):*
> ```Go
> // the provided SST when it is finished using it. If the provided SST is empty,
> // then no file will be created and nothing will be written.
> func (ssss *SSTSnapshotStorageScratch) WriteSST(ctx context.Context, data []byte) error {
> ```

If we're taking a context in `NewFile`, why does this still also take a context?
___
*[pkg/storage/replica_sst_snapshot_storage.go, line 212 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQaSkm8efXGJuY9E9H:-LtQaSkm8efXGJuY9E9I:b48gktz) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/replica_sst_snapshot_storage.go#L212)):*
> ```Go
> 		return nil
> 	}
> 	if sssf.chunkSize > 0 && len(sssf.buffer) > 0 {
> ```

Remove the `sssf.chunkSize > 0` condition. We don't care about that here.
___
*[pkg/storage/store_snapshot.go, line 122 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQbZYLE45ZZr4AdX_V:-LtQbZYLE45ZZr4AdX_W:b-z7eg8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/store_snapshot.go#L122)):*
> ```Go
> 	ssss        *SSTSnapshotStorageScratch
> 	currSST     engine.SSTWriter
> 	currSSTFile *SSTSnapshotStorageFile
> ```

Do you mind checking that we still need this field? It seems to be used once in `multiSSTWriter.Close`, but I'd expect `engine.SSTWriter.Close` to have already closed the file. Is that incorrect?

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajkr, @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_sst_snapshot_storage.go, line 109 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQaBfN5uStQq4ZfvsS:-LtQg74rCCDp3jIkYUX9:bv7wlz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/replica_sst_snapshot_storage.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're taking a context in `NewFile`, why does this still also take a context?
</blockquote></details>

Because we call `NewFile` in this method. The context is stored on a per-file basis, which we could probably change if we want.
___
*[pkg/storage/replica_sst_snapshot_storage.go, line 212 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQaSkm8efXGJuY9E9H:-LtQp6bW6-LUX3BN_zsb:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/replica_sst_snapshot_storage.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Remove the `sssf.chunkSize > 0` condition. We don't care about that here.
</blockquote></details>

Done. 
___
*[pkg/storage/store_snapshot.go, line 122 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQbZYLE45ZZr4AdX_V:-LtQp27y55Mo2LHxbeJX:b-gkenzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/store_snapshot.go#L122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind checking that we still need this field? It seems to be used once in `multiSSTWriter.Close`, but I'd expect `engine.SSTWriter.Close` to have already closed the file. Is that incorrect?
</blockquote></details>

That's correct, it's not necessary. Thanks for discovering! Removed.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-:-LtQuDOLBCB2Z23RYgqK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_sst_snapshot_storage.go, line 109 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtQaBfN5uStQq4ZfvsS:-LtQtv9LCDD9y9-1jY0G:bjzd86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/959ae8e94086b92d8a21f5d25a255e228bc92fd4/pkg/storage/replica_sst_snapshot_storage.go#L109)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Because we call `NewFile` in this method. The context is stored on a per-file basis, which we could probably change if we want.
</blockquote></details>

Oh I see, I thought this was a method on `SSTSnapshotStorageFile`, not on `SSTSnapshotStorageScratch`.

**Comment by itsbilal** [comment]
Thanks for the review!

bors r+

**Review by ajkr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_sst_snapshot_storage.go, line 174 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtR12hW7-NAxqp2au_g:-LtR12hW7-NAxqp2au_h:b-p7vopx) ([raw file](https://github.com/cockroachdb/cockroach/blob/47396f3f3317a50edfc53861c302a1f8c20906c3/pkg/storage/replica_sst_snapshot_storage.go#L174)):*
> ```Go
> // SSTSnapshotStorageScratch. Writing empty contents is okay and is treated as
> // a noop. The file must have not been closed.
> func (sssf *SSTSnapshotStorageFile) Write(contents []byte) (int, error) {
> ```

Where is the int return value used?

**Comment by itsbilal** [comment]
___
*[pkg/storage/replica_sst_snapshot_storage.go, line 174 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtR12hW7-NAxqp2au_g:-LtR7romAgr4qCoLN4ak:b-kk3dmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/47396f3f3317a50edfc53861c302a1f8c20906c3/pkg/storage/replica_sst_snapshot_storage.go#L174)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

Where is the int return value used?
</blockquote></details>

It's used inside `sstable.Writer.writeRawBlock` in Pebble. Also it's part of the io.Writer interface so we're forced to supply it as a result.

**Review by ajkr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42252)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/replica_sst_snapshot_storage.go, line 174 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42252#-LtR12hW7-NAxqp2au_g:-LtRB8XnC91wj_bMv0EG:b5r46ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/47396f3f3317a50edfc53861c302a1f8c20906c3/pkg/storage/replica_sst_snapshot_storage.go#L174)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It's used inside `sstable.Writer.writeRawBlock` in Pebble. Also it's part of the io.Writer interface so we're forced to supply it as a result.
</blockquote></details>

Understood, thanks.

**Pull request merged**
