### PR TITLE
backfill: fix memory accounting bug in index backfiller

### PR DESCRIPTION
**Pull request by adityamaru**
Fixes a bug where we were under accounting for the memory
used by the index backfiller.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/sql/backfill/backfill.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvm0-c4E7reFwEuucG:-MHvm0-c4E7reFwEuucH:b3yuegk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/backfill/backfill.go#L745)):*
> ```Go
> 
> 		// If the number of index entries are going to cause the entries buffer to
> 		// re-slice, we must account for this in the index memory account.
> ```

nit: I'd probably expand the comment saying something like "we have already accounted for `cap(entries)` and entries slice will have to relocate, very likely it'll double in capacity, so we account for another `cap(entries)`".
___
*[pkg/sql/backfill/backfill.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvhdqu7-Fi24m08tX1:-MHvhdqu7-Fi24m08tX2:bxf2hfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/backfill/backfill.go#L747)):*
> ```Go
> 		// re-slice, we must account for this in the index memory account.
> 		if cap(entries)-len(entries) < len(buffer) {
> 			if err := ib.boundAccount.Grow(ctx, int64(unsafe.Sizeof(rowenc.IndexEntry{}))*
> ```

nit: I'd extract this into a global constant (that what we do in other places), i.e. something like `const sizeOfIndexEntry = int64(unsafe.Sizeof(rowenc.IndexEntry{}))`

Also, we're accounting for the size of empty `IndexEntry`, however, later it might store large `[]byte`, do we update the account accordingly somewhere?
___
*[pkg/sql/rowenc/index_encoding.go, line 1259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvlB-914hAMnzLZmbM:-MHvlB-914hAMnzLZmbN:b-69nfnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/rowenc/index_encoding.go#L1259)):*
> ```Go
> 		// We must account for additional index entries in the index memory account
> 		// if secondaryIndexEntries is going to get re-sliced.
> 		if cap(secondaryIndexEntries)-len(secondaryIndexEntries) < len(entries) {
> ```

`s/entries/secondaryIndexEntries/`.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54692)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/backfill/backfill.go, line 745 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvm0-c4E7reFwEuucG:-MHwIpAy-FRsvFReBfTp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/backfill/backfill.go#L745)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: I'd probably expand the comment saying something like "we have already accounted for `cap(entries)` and entries slice will have to relocate, very likely it'll double in capacity, so we account for another `cap(entries)`".
</blockquote></details>

Done.
___
*[pkg/sql/backfill/backfill.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvhdqu7-Fi24m08tX1:-MHwkK14CTA91t3_sm74:bk4yiew) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/backfill/backfill.go#L747)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: I'd extract this into a global constant (that what we do in other places), i.e. something like `const sizeOfIndexEntry = int64(unsafe.Sizeof(rowenc.IndexEntry{}))`

Also, we're accounting for the size of empty `IndexEntry`, however, later it might store large `[]byte`, do we update the account accordingly somewhere?
</blockquote></details>

yup, in `EncodeSecondaryIndexes` we account for the keys in all the IndexEntry structs as they could potentially be quite large.
___
*[pkg/sql/rowenc/index_encoding.go, line 1259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvlB-914hAMnzLZmbM:-MHwkAz_Bg-TOIt7Xqkp:b-ckl6mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/rowenc/index_encoding.go#L1259)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`s/entries/secondaryIndexEntries/`.
</blockquote></details>

I reworded the comment to match your previous recommendation.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-:-MHyDyxu96aQw9Ly54Vt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/sql/backfill/backfill.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54692#-MHvhdqu7-Fi24m08tX1:-MHyDjnICmaF_EOvYnUj:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e2881b1402b8e396eca00546d0963543f0f66b7/pkg/sql/backfill/backfill.go#L747)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

yup, in `EncodeSecondaryIndexes` we account for the keys in all the IndexEntry structs as they could potentially be quite large.
</blockquote></details>

Ack.

**Comment by adityamaru** [comment]
TFTR!

bors r=yuzefovich

**Pull request merged**
