### PR TITLE
importccl: move stub stats logic outside publish txn

### LINKED ISSUE #70410: roachtest: tpccbench/nodes=9/cpu=4/multi-region failed
roachtest.tpccbench/nodes=9/cpu=4/multi-region [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3466946&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3466946&tab=artifacts#/tpccbench/nodes=9/cpu=4/multi-region) on master @ [d9278939d4be4d1109e9ed0a84c6e9cd2a8705bb](https://github.com/cockroachdb/cockroach/commits/d9278939d4be4d1109e9ed0a84c6e9cd2a8705bb):

```
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTPCCBenchSpec.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:902
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:777
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:172
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.(*clusterImpl).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1987
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.loadTPCCBench
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:966
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runTPCCBench.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:1066
		  | main.(*monitorImpl).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/monitor.go:106
		  | golang.org/x/sync/errgroup.(*Group).Go.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (6) output in run_092812.543732632_n1_cockroach_workload_fixtures_import_tpcc
		Wraps: (7) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-3466946-1632119031-36-n12cpu4-geo:1 -- ././cockroach workload fixtures import tpcc --warehouses=3000 --checks=false --partitions=3 --zones="us-east1-b,us-west1-b,europe-west2-b" returned
		  | stderr:
		  | I210920 09:28:13.712212 1 ccl/workloadccl/fixture.go:345  [-] 1  starting import of 9 tables
		  | I210920 09:28:30.516886 68 ccl/workloadccl/fixture.go:478  [-] 2  imported 7.8 MiB in item table (100000 rows, 0 index entries, took 16.795294584s, 0.46 MiB/s)
		  | I210920 09:28:35.638880 31 ccl/workloadccl/fixture.go:478  [-] 3  imported 3.0 MiB in district table (30000 rows, 0 index entries, took 21.918323337s, 0.13 MiB/s)
		  | I210920 09:28:37.368016 30 ccl/workloadccl/fixture.go:478  [-] 4  imported 160 KiB in warehouse table (3000 rows, 0 index entries, took 23.647565382s, 0.01 MiB/s)
		  | I210920 09:29:21.186560 67 ccl/workloadccl/fixture.go:478  [-] 5  imported 383 MiB in new_order table (27000000 rows, 0 index entries, took 1m7.464939651s, 5.68 MiB/s)
		  | I210920 09:34:46.272774 66 ccl/workloadccl/fixture.go:478  [-] 6  imported 4.7 GiB in order table (90000000 rows, 90000000 index entries, took 6m32.551220907s, 12.30 MiB/s)
		  | I210920 09:35:29.312540 33 ccl/workloadccl/fixture.go:478  [-] 7  imported 6.5 GiB in history table (90000000 rows, 0 index entries, took 7m15.591492291s, 15.18 MiB/s)
		  | I210920 09:43:21.245596 32 ccl/workloadccl/fixture.go:478  [-] 8  imported 52 GiB in customer table (90000000 rows, 90000000 index entries, took 15m7.524314635s, 58.41 MiB/s)
		  | I210920 09:49:11.939503 69 ccl/workloadccl/fixture.go:478  [-] 9  imported 90 GiB in stock table (300000000 rows, 0 index entries, took 20m58.217797335s, 73.36 MiB/s)
		  | I210920 09:50:36.478020 70 ccl/workloadccl/fixture.go:478  [-] 10  imported 51 GiB in order_line table (900015304 rows, 0 index entries, took 22m22.75670363s, 38.65 MiB/s)
		  | Error: importing fixture: importing table district: pq: relation "district" is offline: importing
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ``````
		  |   | ././cockroach workload fixtures import tpcc --warehouses=3000 --checks=false --partitions=3 --zones="us-east1-b,us-west1-b,europe-west2-b"
		  |   | ``````
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (8) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *cluster.WithCommandDetails (8) *exec.ExitError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpccbench/nodes=9/cpu=4/multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Epic CRDB-7779

### PR DESCRIPTION
**Pull request by adityamaru**
This change pulls the logic related to inserting table statistic
stubs for new tables created during the import, out of the txn
closure that sets the tables to `public` from `offline`.
This was motivated by the failure mode observed in #70410 where
we failed to write the stats stub for a particular table and ended
up with a descriptor published in the offline state.

Fixes: #70410

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:/ I want to reach enlightenment on this. 

Nevertheless, the change itself :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-:-Mk4BxnuE2RiYkEeGCyg:b1cihys)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @michae2)

___
*[pkg/ccl/importccl/import_stmt.go, line 2371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-Mk4C6hq4gD3eMQMFEvM:-Mk4C6hq4gD3eMQMFEvN:b-jo84xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e697db662d190b62967c2f108c03667ec5aa27cd/pkg/ccl/importccl/import_stmt.go#L2371)):*
> ```Go
> 					statistic.NullCount = nullCount
> 				}
> 				err = stats.InsertNewStats(ctx, execCfg.InternalExecutor, nil /* txn */, statistics)
> ```

when I look at this, I feel sad about how sequential it is is. Hope this isn't a global cluster with hecka columns.

**Review by ajwerner — COMMENTED** [review]
wait, actually, there's probably a reason it was in the txn. We probably want the stats published at or before we make the tables public, no? If we're going to do it, maybe do it before?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-:-Mk4CLivBpesegvJ-Pnn:bequr3g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @michae2)

**Review by michae2 — COMMENTED** [review]
Thanks for looking at this. Original motivation for same txn was to write stub stats atomically with table publishing, but before publishing would also be fine. After publishing would leave a gap during which queries would be planned without stats. (Granted, it's best-effort anyway, so not a huge issue, but might as well not have a gap.)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-:-Mk4DRhmDm5iFSsMrVro:b7yad33)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 2371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-Mk4C6hq4gD3eMQMFEvM:-Mk4CTJ90lA-Ti8s5z2e:b-nzuh7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e697db662d190b62967c2f108c03667ec5aa27cd/pkg/ccl/importccl/import_stmt.go#L2371)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

when I look at this, I feel sad about how sequential it is is. Hope this isn't a global cluster with hecka columns. 
</blockquote></details>

Fair point. I'm starting work on distinct and null counts. @adityamaru if you add something like `TODO(michae2): parallelize` somewhere I can take a shot at it.

**Review by michae2 — COMMENTED** [review]
> I don't have a clear RCA for the associated issue yet, so I'm hoping that this proposed solution might get someone to see something I missed. Regardless, I feel more comfortable keeping the table publishing closure as small as possible, especially since the stats stubbing is best effort, and swallowing the error seems to be tickling something.

I'm not sure exactly what `TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "unnamed"` means yet, but it seems bad in general to keep using the same txn after the abort. So this is definitely an improvement.

> Another open question is does this refactor mean we should add a details.StatsInserted bool to prevent us from inserting multiple stubs across resumptions? Does it matter?

I don't think it matters for query planning (the optimizer will simply use the latest stats). But as @ajwerner points out writing the statistics is currently serial, so if the import has many tables or columns, writing redundant stats will add some extra latency to the IMPORT. Adding the bool sounds nice, if it's not too much trouble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-:-Mk4Geja3bsMqCijiwYr:b-fbynv4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm: This is fine, too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70447#-:-Mk4J6WL-J-5ahB3HWUp:b-jv4u45)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @michae2)

**Comment by adityamaru** [comment]
For posterity, the RCA from Nathan in the related issue is consistent with what we were observing. I feel better about this change now 🙂

**Pull request merged**
