### PR TITLE
go.mod: bump Pebble to 3a56d35134e9

### PR DESCRIPTION
**Pull request by RaduBerinde**
3a56d351 options: make MinDeletionRate non-experimental, rename to TargetByteDeletionRate
77f4fbfd sharedcache: move to fine-grained locking
c34cb152 sharedcache: fix bug that "leaks" cache block indexes
06487261 db: Add FormatMajorVersion for virtual sstables
c3bf955f cmd/pebble: sample read amp during write-only ycsb workloads
d96868fd db: fix TestCleaner flake

Release note: None
Epic: none

### CODE REVIEW

**Review by bananabrick — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104544#-:-NXMWKA6E54EqJhqUZaM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104544#-:-NXMWKX7E98ySrF6Kycw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
