### PR TITLE
backupccl: enable backing up and restoring user defined schemas

### LINKED ISSUE #50875: backup/restore: support user defined schemas in backup + restore
User defined schemas will need to be added to the backup/restore descriptor collection as well as the ID remapping process.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50875.

This commit adds support for backup/restore to operate when user defined
schemas have been created. We don't add a new `BACKUP SCHEMA` command,
as this would most likely create backups that have dangling references
across schemas.

Release note (enterprise change): Enable backup and restore when user
defined schemas are in use.

### CODE REVIEW

**Comment by rohany** [comment]
I'll add some tests for when user defined schemas can be modified once those PR's land.

**Review by pbardea — COMMENTED** [review]
I think we'll also need to update revision_history to track the creation/deletion of schemas. Approach LGTM though

> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-:-METWrXp3P29snBHJsFb:bsazttl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METGu1E4y6rgqITVFtG:-METGu1E4y6rgqITVFtH:bwb84y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/backup_test.go#L1486)):*
> ```Go
> 	// Test restoring tables with user defined schemas when restore schemas are
> 	// not being remapped.
> 	t.Run("no-remap", func(t *testing.T) {
> ```

Can we also test restoring the table into the same database it was backed up from?
___
*[pkg/ccl/backupccl/restore_planning.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METZQ691m4w5d4FtjiD:-METZQ691m4w5d4FtjiE:b5xudo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L155)):*
> ```Go
> // allocateDescriptorRewrites determines the new ID and parentID (a "TableRewrite")
> // for each table in sqlDescs and returns a mapping from old ID to said
> // TableRewrite. It first validates that the provided sqlDescs can be restored
> ```

Could you also s/TableRewrite/DescriptorRewrite in this comment
___
*[pkg/ccl/backupccl/restore_planning.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METUnDUC7xIiKvWtyrJ:-METUnDUC7xIiKvWtyrK:bcsvy5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L318)):*
> ```Go
> 		}
> 
> 		// Construct rewrites for any user defined schemas.
> ```

This entire method has been monstrously large for a while. I wonder if we can pull out this `schemasByID` in a helper. Also happy to do this in a follow up, but maybe leaving a TODO would be useful.
___
*[pkg/ccl/backupccl/restore_planning.go, line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METZi_hASLZXlUFl-hk:-METZi_hASLZXlUFl-hl:brv6mco) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L792)):*
> ```Go
> 	rw, ok := descriptorRewrites[curSchemaID]
> 	if !ok {
> 		// TODO (rohany): Should this return an error?
> ```

Do we expect to hit this case? I don't think so?
___
*[pkg/ccl/backupccl/targets.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METXAsK0iinS4ZdNpSZ:-METXAsK0iinS4ZdNpS_:bnh56gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/targets.go#L142)):*
> ```Go
> 	}
> 
> 	// Add all schemas. Can't do this below rohany.
> ```

This comment needs cleanup

**Review by rohany — COMMENTED** [review]
> I think we'll also need to update revision_history to track the creation/deletion of schemas. Approach LGTM though

Yup, will do in a follow up

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-:-MEUPfwd6ejZmpo5SNk7:b-93oa64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 1486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METGu1E4y6rgqITVFtG:-MEUPkM2BR-aUaDbUwwo:b-b1hobl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/backup_test.go#L1486)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we also test restoring the table into the same database it was backed up from?
</blockquote></details>

Done, i forgot this originally it seems.
___
*[pkg/ccl/backupccl/restore_planning.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METZQ691m4w5d4FtjiD:-MEUPoO1D6tTgE_lb6QP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L155)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Could you also s/TableRewrite/DescriptorRewrite in this comment
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_planning.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METUnDUC7xIiKvWtyrJ:-MEUPpKq8a93VOuYFykj:bguiyq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L318)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This entire method has been monstrously large for a while. I wonder if we can pull out this `schemasByID` in a helper. Also happy to do this in a follow up, but maybe leaving a TODO would be useful.
</blockquote></details>

Added a TODO for now
___
*[pkg/ccl/backupccl/restore_planning.go, line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METZi_hASLZXlUFl-hk:-MEUPtHw9_P2cjw39oXv:b-sxye1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L792)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we expect to hit this case? I don't think so?
</blockquote></details>

Yeah, this shouldn't happen. Updated to return an error.
___
*[pkg/ccl/backupccl/targets.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METXAsK0iinS4ZdNpSZ:-MEUPwZ3C8SV_hTl2gqH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/targets.go#L142)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This comment needs cleanup
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-:-MEURyCE4kFP3qKMoQG2:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Review by rohany — COMMENTED** [review]
The test have caught a problem with import + user defined schemas which is pretty similar to the problem we had with user defined types. In short, the ID we assign to import tables is 53 (minDescID + 1), and then we remap this to a real ID later. The problem is that a schema descriptor could have ID 53, which causes the remapping logic to corrupt the schema ID in the table descriptor. The way we went around this for types was to disallow importing tables (with a create statement) with user defined types. However, this restriction with user defined schemas feels even more artificial. I think instead we should be using a descriptor ID that is guaranteed to not be present in any of the references, or to just allocate ID's for the import tables up front. cc @dt 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-:-MEVPIuQ7picB9Eq2ko6:b3diaoe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52588#-METZi_hASLZXlUFl-hk:-MEVOyzf0yAKhPl8uLoB:b-j6nf98) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef41c63406c8af09dea6a8e09bf8b0a48c574074/pkg/ccl/backupccl/restore_planning.go#L792)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah, this shouldn't happen. Updated to return an error.
</blockquote></details>

Never mind, it seems that this could happen -- in import, we use the rewrite methods as well, but only provide some table IDs. I don't like not returning an error here, but we might just have to.

**Comment by dt** [comment]
does pgdump emit dumps of a table in a schema but not the schema creation? i.e. are there pgdumps that, to import, we need to resolve an existing schema based on a name that appears in the dumpfile?

**Comment by rohany** [comment]
PG dump emits schema creation statements i believe, but I'm looking at just the case of `IMPORT TABLE myschema.tb (...) CSV DATA ...`

**Comment by dt** [comment]
Ah, I see. It feels like we should be rewriting the IDs to real ones _before_ setting the real parent ID -- it makes me nervous that we're rewriting IDs in a desc where some are real and some are placeholders, and just hoping (and as you're now seeing, incorrectly) they don't collide.

Why wasn't this an issue before schemas, just if the parent DB had an ID that collided?

**Comment by rohany** [comment]
> Why wasn't this an issue before schemas, just if the parent DB had an ID that collided?

I think its just luck. `defaultCSVParentID` is 52 and `defaultCSVTableID` is 53. Usually in tests we make a database first with ID 52 (the min user descriptor ID). So we never run into this problem. If we made two databases (so that the second had id 53) and then used the second in the test we would run into the problem i think.

**Comment by rohany** [comment]
I played around with this. In the case I mentioned above, we do in fact prepare to import a table with ID 53 and parent ID 53. However, because the rewrite for 53 has a correct parent ID in it, we don't mess anything up. However, this feels pretty hacky to me. @dt do you want to fix this?

**Comment by dt** [comment]
Hm, I'm still not quite sure what the problem is -- can you provide an example? 

The rewritten desc's parent ID is always set to the parent in the rewrite rule. Where are we confusing a new-ID 53 for an old-ID 53?

**Comment by rohany** [comment]
I'm saying that we aren't, because of how we do rewrites of parentID's. But the descriptor that we rewrite still has parentID = 53 and ID = 53. So it's not a problem for databases, but for schemas and user defined types.

**Comment by dt** [comment]
Ah, I see -- you're saying we resolve the ID of a type or schema and stick it in the desc while it is in "old-ID" (i.e. fake ID), but we resolved the real ID that type or schema, i.e. what should be the "new ID" post-rewrite. Essentially when we resolve an _existing_ ID during desc creation, we're now mixing old-ids and new-ids in the same desc and that's where this gets us into trouble since we can't tell them apart. Hmm. Eh, can we just say you can't refer to existing schemas or types for now and if you want to IMPORT into a table that uses existing schemas or types, you should `CREATE` the table you want -- letting `CREATE` resolve all the schema elements correctly and make the right desc, and then use `IMPORT INTO` to load the data?

**Pull request merged**
