### PR TITLE
Add runtime statistics to Status Summaries

### LINKED ISSUE #4956: ui: reorganize table on Nodes page
The table on the Nodes page should have only the following information:

* live bytes + system bytes + intent bytes (just call this “bytes”)
* started at becomes uptime, which is humanized
* total ranges
* client connections
* capacity
* load/CPU (small graph, 10 minutes)
* memory (small graph, 10 minutes)

We're removing a bunch of stuff like node ID and intent bytes and adding a few stats to highlight the most important metrics for a user of the admin UI.

### PR DESCRIPTION
**Pull request by mrtracy**
This commit refactors the way that runtime statistics are sampled by cockroach,
enabling them to be part of status summaries. Previously, they were only
recorded as time series.

RuntimeStatsRecorder has been renamed "RuntimeStatsSampler", and it is now only
responsible for periodically sampling runtime statistics and storing them in a
set of metric gauges. These gauges are contained in a registry, and that
registry is added to the server's StatusRecorder; this allows these values to be
recorded to time series _and_ to node status summaries.

Finally, with the new runtime statistics on the node summaries, this commit
completes the blank columns on the UI's "Nodes" table.

Fixes #4956 

screen shot 2016-03-24 at 7 08 08 pm

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5557)

### CODE REVIEW

**Comment by mrtracy** [comment]
cc @tschottdorf for metrics-related stuff

**Comment by maxlang** [comment]
:lgtm: for the frontend portions

I still want us to move away from the MetricConstants pattern after Beta.

Would it make sense to add qps/bytes in/bytes out to this PR? I remember Peter or Spencer mentioning the node table should mimic the cluster overview stats.

---

Reviewed 3 of 12 files at r1.
Review status: 3 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ui/ts/pages/nodes.ts, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDf7Sxr2CN_nLRaEeM7:-KDf7SxsZbuhlhxLM9lc:312584101) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/ui/ts/pages/nodes.ts#L182)):*
Might average make more sense than CPU sum? I'm not sure how we'd call it out though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-:-KDf6d7uFV1eqYJw56NW:-171210472)*

**Comment by cuongdo** [comment]
:lgtm: for backend

---

Reviewed 9 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/status/runtime.go, line 108 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDfRFQglfode1anuH9F:-KDfRFQglfode1anuH9G:1187021304) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/server/status/runtime.go#L108)):*
I didn't know you could mix and match pointer and non-pointer receivers for the same struct!

---

*[ui/ts/pages/nodes.ts, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDf7Sxr2CN_nLRaEeM7:-KDfSiwL9RkPWjOVbCF9:686924155) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/ui/ts/pages/nodes.ts#L182)):*
Yeah, average would be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-:-KDfSrY6OSADd756ySeu:1617125230)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/status/runtime.go, line 108 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDfRFQglfode1anuH9F:-KDfqaiJdNKvnbsMRjna:-398702914) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/server/status/runtime.go#L108)):*
Yes indeed!

---

*[ui/ts/pages/nodes.ts, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDf7Sxr2CN_nLRaEeM7:-KDfsoFj_KTrNJaO-msO:234613494) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/ui/ts/pages/nodes.ts#L182)):*
This is already the average: `/ rows.length`.

I don't know how to call it out, but its very intuitive.  Related: there's nothing that says that the other rollup values are sums.  Tooltips is probably the way to go.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557)*

**Comment by maxlang** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ui/ts/pages/nodes.ts, line 182 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557#-KDf7Sxr2CN_nLRaEeM7:-KDg4ebdYTWm-zvR3zOV:-2123462118) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9f93be52d22a22f3c7835da29d4993cc11cff0/ui/ts/pages/nodes.ts#L182)):*
My bad, I was looking at the wrong line originally and then just moved this comment without thinking.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5557)*

**Pull request merged**
