### PR TITLE
colexecdisk: fix TestExternalSortMemoryAccounting for good

### LINKED ISSUE #91076: colexec: TestExternalSortMemoryAccounting is flakey
Seems to be failing somewhat regularly:

```
    external_sort_test.go:169: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4988/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/colexec/colexecdisk/colexecdisk_test_/colexecdisk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/colexec/colexecdisk/external_sort_test.go:169
        	Error:      	"2083771148" is not greater than or equal to "2187528824"
        	Test:       	TestExternalSortMemoryAccounting
        	Messages:   	maximum memory bound not satisfied: actual 2187528824, expected max 2083771148
```

Test history: https://teamcity.cockroachdb.com/project.html?tab=testDetails&projectId=Cockroach_Ci_TestsAwsLinuxArm64BigVm&testNameId=7444190392994169507&page=1

Jira issue: CRDB-21097

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes `TestExternalSortMemoryAccounting` for good. It's worth noting that in 256223fe49f4a7f528c20a1b178be24cc3e55342 (which was merged a couple of months ago) we improved the memory accounting around the time we spill to disk, so the test was probably almost flaking until the recent changes to how we grow the Bytes vector in case of appends.

Fixes: #91076.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Done adjusting the comment, RFAL

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91107#-:-NFpfFhY02KDlaJnjK0s:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
Thank you!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
