### PR TITLE
server,cli/haproxy: use node liveness to filter the generated conf

### LINKED ISSUE #19863: cli/gen: Decommissioned nodes are included in `gen haproxy` output
When I run `cockroach gen haproxy`, decommissioned nodes are included in the server list. They should be removed.

### PR DESCRIPTION
**Pull request by knz**
Fixes #19863.

Prior to this patch, `cockroach gen haproxy` would include
decommissioned nodes in the generated configuration.
This patch removes them.

This is achieved by extending `/_status/nodes` to also
report the livesness information as currently known
via gossip.

Release note (cli change): `cockroach gen haproxy` now excludes
decommissioned nodes.

### CODE REVIEW

**Comment by tbg** [comment]
Isn't the correct thing to include all nodes that aren't explicitly decommissioned? If I generate a haproxy conf while some node is down for expected (short enough) maintenance (like a version upgrade), I want it in my haproxy conf, right?

Also, is there a rationale for making a new endpoint vs augmenting the data returned by the old endpoint?

**Comment by knz** [comment]
> Isn't the correct thing to include all nodes that aren't explicitly decommissioned? If I generate a haproxy conf while some node is down for expected (short enough) maintenance (like a version upgrade), I want it in my haproxy conf, right?

I wasn't sure; but that works for me. Changed.

> Also, is there a rationale for making a new endpoint vs augmenting the data returned by the old endpoint?

I wanted to share some code with the internal API. But it's not too important. Done.

**Review by tbg — APPROVED** [review]
:lgtm: mod my comments.

Also, can you update the cli help comment for this command to mention that decommission{ed,ing} nodes are skipped?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-:-LycjXIo40OjCqs0p0yj:bl861po)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cli/haproxy.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-LycghLz2uIuC1AvrqCY:-LycghLz2uIuC1AvrqCZ:b-qturt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/cli/haproxy.go#L99)):*
> ```Go
> 		case storagepb.NodeLivenessStatus_DECOMMISSIONING,
> 			storagepb.NodeLivenessStatus_DECOMMISSIONED:
> 			fmt.Fprintf(stderr, "warning: node %d status is %s, excluding from haproxy configuration\n",
> ```

I think this warning should print only on `DECOMMISSIONING`. A `DECOMMISSIONED` node is understood to intentionally have been removed from the cluster a while ago, so nobody would expect it to show up in a haproxy config.
___
*[pkg/cli/haproxy.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-LycifNvAC7RN5XO8V0p:-LyciI5SADYM8cu1S2cK:b6tbw89) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/cli/haproxy.go#L116)):*
> ```Go
> 		// possible flags.
> 		//
> 		// TODO(knz): this logic is horrendously broken and
> ```

Wow, no kidding, this is wild.
___
*[pkg/cli/haproxy_test.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-Lycitr-1FwBzKy9LDyy:-Lycitr-1FwBzKy9LDyz:b-4z6uyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/cli/haproxy_test.go#L114)):*
> ```Go
> 			},
> 		},
> 		// Check that non-live nodes are not considered for generating the configuration.
> ```

s/non-live/decommission{ing,ed}/
___
*[pkg/server/serverpb/status.proto, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-LycjGUI5kQvGLxEfpFF:-LycjGUI5kQvGLxEfpFG:byld2h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/server/serverpb/status.proto#L115)):*
> ```protobuf
> message NodesResponse {
>   repeated server.status.statuspb.NodeStatus nodes = 1 [ (gogoproto.nullable) = false ];
>   map<int32, cockroach.storage.NodeLivenessStatus> liveness_by_node_id = 2 [
> ```

Do we use proto maps elsewhere? I'm asking because I faintly remember issues with them. Perhaps they weren't supported in gw-gateway, or the iteration order caused snags. If there's a precedent, I have no concerns but if this is the first map in these public protos consider using a repeated message instead.

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43908)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
> Also, can you update the cli help comment for this command to mention that decommission{ed,ing} nodes are skipped?

Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-:-LycrT956mYYqtfIzVIx:bb5xko2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cli/haproxy.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-LycghLz2uIuC1AvrqCY:-Lycr1xQ0Ry1yczu-eHL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/cli/haproxy.go#L99)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think this warning should print only on `DECOMMISSIONING`. A `DECOMMISSIONED` node is understood to intentionally have been removed from the cluster a while ago, so nobody would expect it to show up in a haproxy config.
</blockquote></details>

Done.
___
*[pkg/cli/haproxy_test.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-Lycitr-1FwBzKy9LDyy:-Lycr9Ix6OKP0RxecjbF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/cli/haproxy_test.go#L114)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/non-live/decommission{ing,ed}/
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.proto, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43908#-LycjGUI5kQvGLxEfpFF:-LycrFjz-eeFIWbi7WTe:b2wdp32) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0a641d86c1bf8289cabbea21fd4daaf3271484/pkg/server/serverpb/status.proto#L115)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Do we use proto maps elsewhere? I'm asking because I faintly remember issues with them. Perhaps they weren't supported in gw-gateway, or the iteration order caused snags. If there's a precedent, I have no concerns but if this is the first map in these public protos consider using a repeated message instead.
</blockquote></details>

There's some precedent in `RaftState` , `RaftDebugResponse`, `ProblemRangesResponse`, `HotRangesResponse`, `RangeResponse` below in the same file.

**Comment by knz** [comment]
> the iteration order caused snags

Yes that is a concern btw, that's why the haproxy code also sorts the node IDs.

**Comment by knz** [comment]
TFYR!

bors r=tbg

**Pull request merged**
