### PR TITLE
sql: ban window functions from HAVING clauses

### LINKED ISSUE #14513: query can kill server
**BUG REPORT**

- What did you do?
```
rara@Andrass-MacBook-Pro:~$ docker run -d --name=cockroach -p 26257:26257 -p 9999:9999 cockroachdb/cockroach:latest  start --insecure --http-port 9999
8e7a505b775b1d10294386987b35c915717b24c8b1e03a42c4b521078d599b6d
rara@Andrass-MacBook-Pro:~$ docker exec -it cockroach bash
root@8e7a505b775b:/cockroach# grep -F '[config]' cockroach-data/logs/cockroach.log 
I170331 14:41:29.601303 1 util/log/clog.go:991  [config] file created at: 2017/03/31 14:41:29
I170331 14:41:29.601303 1 util/log/clog.go:991  [config] running on machine: 8e7a505b775b
I170331 14:41:29.601303 1 util/log/clog.go:991  [config] binary: CockroachDB CCL f9b8c0c (linux amd64, built 2017/03/31 03:01:38, go1.8)
I170331 14:41:29.601303 1 util/log/clog.go:991  [config] arguments: [/cockroach/cockroach start --insecure --http-port 9999]
./cockroach sql -e "SELECT 1 GROUP BY 1 HAVING sum(1) OVER (PARTITION BY 1) > 1;" #will kill container
Error: driver: bad connection
Failed running "sql"
root@db9e2fa13cf8:/cockroach# 
rara@Andrass-MacBook-Pro:~$
```

- What did you expect to see?
Not sure...
This is a minimal failing version of a complex query. I'm a noob at sql, so I don't know if an SQL server should support GROUP BY ... HAVING AGGREGATION(...) OVER(...) ...  queries. If not I would expect some parsing error message.
- What did you see instead?
Query above made the docker container with the sql server die, without any log messages.

### PR DESCRIPTION
**Pull request by jordanlewis**
Resolves #14513.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14580)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580#-:-KgpbymQ8SdK8i3cobb9:bnfp4nl)*

**Review by dt — APPROVED** [review]

**Comment by andreimatei** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/group.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580#-Kgpf2mBxoC5GwJ76cOK:-Kgpf2mCkGGdX3-fF7pB:bke4e1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7da254aa13ccddc7e76ff54e68c2a57c8bb8e5e2/pkg/sql/group.go#L104)):*
> ```Go
> 	if n.Having != nil {
> 		if p.parser.WindowFuncInExpr(n.Having.Expr) {
> 			return nil, errors.New("window functions are not allowed in HAVING")
> ```

I think `pgerror.WithPGCode(err, pgerror.CodeSyntaxError)` is what we want

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580)*

**Comment by tamird** [comment]
How did you determine that it was a syntax error?

**Comment by andreimatei** [comment]
isn't it? I guess we should see what postgres returns; this seemed appropriate to me.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/group.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580#-Kgpf2mBxoC5GwJ76cOK:-KgpgR7VCM57892C840o:b-fpb0k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7da254aa13ccddc7e76ff54e68c2a57c8bb8e5e2/pkg/sql/group.go#L104)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `pgerror.WithPGCode(err, pgerror.CodeSyntaxError)` is what we want
</blockquote></details>

there's also `NewSyntaxError()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580#-:-KgpgJDs_HW3M3WxHZDF:b-jtitwe)*

**Comment by jordanlewis** [comment]
Postgres says:

```
jordan=# select 1 group by 1 having sum(1) OVER (PARTITION BY 1) > 1;
ERROR:  window functions are not allowed in HAVING
```

All of the rest of the invalid function in clause errors we throw are done in the same way. If we need to change them, we should change them all at once in a new PR.

**Comment by tamird** [comment]
Yeah, I would prefer that we avoid guessing.

**Comment by dt** [comment]
+1 to matching the other errors, and doing any mass-change or pg err codes, along with the supporting research to confirm we're returning the right ones, separately.

**Comment by andreimatei** [comment]
IMHO, this is the occasion to do the research about this new error. Returning errors codes is not an all or nothing thing, and we don't need to audit the whole codebase and fix everything.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14580#-:-KgpiRWD0URy2xCgXqWH:b8ribrn)*

**Comment by jordanlewis** [comment]
The error code returned is `42P20`, `windowing_error`. I pushed a patch.

**Comment by jordanlewis** [comment]
BTW, it's very easy to determine what error code is returned by Postgres from `psql` by changing the verbosity settings:

```
jordan=# \set VERBOSITY verbose
jordan=# select 1 group by 1 having sum(1) OVER (PARTITION BY 1) > 1;
ERROR:  42P20: window functions are not allowed in HAVING
LINE 1: select 1 group by 1 having sum(1) OVER (PARTITION BY 1) > 1;
                                   ^
LOCATION:  transformWindowFuncCall, parse_agg.c:881
```

**Review by dt — APPROVED** [review]

**Pull request merged**
