### PR TITLE
sql: declarative schema changer additional fixes for decomposition

### PR DESCRIPTION
**Pull request by fqazi**
These commits aim at solving the following issues with decomposition inside the declarative schema changer

1.  When cleaning up tables with foreign keys we never properly corrected the back-references in the source or destination table depending on the scenario.
2.  When dropping a sequence we never cleaned up back-references that existed from columns, leading to issues when the sequence was dropped first followed by the table.
3. The decomposition work converted constraints into objects, but never properly labelled the ConstraintID field as an attribute. As a result, incorrect duplicate errors were generated when any table had more than **one** constraint.

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
Thanks for doing this. I just have one real question (the one about HasTarget) the rest is basically a bunch of nits.

> Reviewed 8 of 11 files at r1, 2 of 4 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-:-Mpwn8hyA_Nxu2nBpJx1:b-j0orjq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwgnAs4CobcNvl99DN):*
nit: superfluous comma
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwgqGM5-4vp_YW9XXy):*
nit: s/add supports/adds support/
___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwgu3m8-Ectmr874_7):*
What's an object here? Did you mean an element? Did you mean to say that when doing complex cascaded drops, it was easy to declare duplicate drop targets, which is why you've added logic to detect these?

style nit: in general, prefer the active voice to the passive voice
___
*[-- commits, line 17 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwhkLA0nbtYHd9h1bm):*
nit: superfluous comma
___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwhwKG5KSeRILHe8nz):*
What's a later drop? I honestly don't understand.
___
*[-- commits, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwhp2V34FtCF13eqt_):*
Please reword this last sentence, it's hard to understand.
___
*[-- commits, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwi4h733AIej0g3iua):*
I'm glad you find the commit message template useful but you shouldn't feel that strict adherence to it is mandatory. In any case, this commit message body is good, it allows me to readily understand what the change is about!

On the other hand, commit message titles should be of the form `<package>: <imperative verb> <rest of title...>`, where package is the most important package affected. In this case it's probably `schemachanger` and not `sql` though that's not super important. In any case "declarative schema changer drops could fail on constraints" is not a great commit message title. Your other commit message titles could also be improved. Generally speaking, if they're rather long, then it's a good sign they need to be improved.

As you can tell, I care about good commit messages. I'm not alone in this regard.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwkfdU2qTxUZDi4Te1:-MpwkfdU2qTxUZDi4Te2:b-cuo6v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L189)):*
> ```Go
> 		UsesSequenceIDs: sequenceIDs,
> 	}
> 	if !b.HasElement(&expressionElem) {
> ```

Shouldn't this be `HasTarget` instead of `HasElement` ? I'm not sure.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwkxyh4gxOyJnALJ6N:-Mpwkxyh4gxOyJnALJ6O:bbgtihw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L475)):*
> ```Go
> 				addOrDropForDir(b, dir, dependedOnBy)
> 			}
> 		} else {
> ```

uber nit: else is superfluous here
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_sequence.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwlLLW5Dg0h2txUc-Q:-MpwlLLW5Dg0h2txUc-R:b-p2omb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_sequence.go#L60)):*
> ```Go
> 		if desc.IsTable() {
> 			for _, col := range desc.PublicColumns() {
> 				if dep.ColumnID == descpb.ColumnID(descpb.InvalidID) || col.GetID() != dep.ColumnID {
> ```

Can this `dep.ColumnID == 0` case even legitimately exist?

If so, this test clause should be hoisted to the `if` two lines above.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwm7YWDsxfdYP1dYSn:-Mpwm7YWDsxfdYP1dYSo:b1kbw6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scpb/scpb.proto#L157)):*
> ```protobuf
> message UniqueConstraint {
>   option (gogoproto.equal) = true;
>   ConstraintID constraint_id = 1 [(gogoproto.customname) = "ConstraintID", (gogoproto.nullable) = false];
> ```

Considering that `ConstraintID` is just a enum+ordinal pair, is it even worth having as a message? Seems like more trouble than it's worth and that we'd be better off replacing each field of type `ConstraintID` field with a `ConstraintType` type field and a `ConstraintOrdinal` field? Perhaps this has been discussed already between you and Andrew, I don't know. Not a big deal either way.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[-- commits, line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwgu3m8-Ectmr874_7):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What's an object here? Did you mean an element? Did you mean to say that when doing complex cascaded drops, it was easy to declare duplicate drop targets, which is why you've added logic to detect these?

style nit: in general, prefer the active voice to the passive voice
</blockquote></details>

Done.
___
*[-- commits, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwhwKG5KSeRILHe8nz):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

What's a later drop? I honestly don't understand.
</blockquote></details>

Done.
___
*[-- commits, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwhp2V34FtCF13eqt_):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Please reword this last sentence, it's hard to understand.
</blockquote></details>

Done.
___
*[-- commits, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwi4h733AIej0g3iua):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I'm glad you find the commit message template useful but you shouldn't feel that strict adherence to it is mandatory. In any case, this commit message body is good, it allows me to readily understand what the change is about!

On the other hand, commit message titles should be of the form `<package>: <imperative verb> <rest of title...>`, where package is the most important package affected. In this case it's probably `schemachanger` and not `sql` though that's not super important. In any case "declarative schema changer drops could fail on constraints" is not a great commit message title. Your other commit message titles could also be improved. Generally speaking, if they're rather long, then it's a good sign they need to be improved.

As you can tell, I care about good commit messages. I'm not alone in this regard.

</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwkfdU2qTxUZDi4Te1:-MpwtMTp8wkkicallBJg:b9qca76) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L189)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't this be `HasTarget` instead of `HasElement` ? I'm not sure.
</blockquote></details>

Done.

Good catch!
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go, line 475 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwkxyh4gxOyJnALJ6N:-Mpwtewi1vqjO8OMoX0B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/common_relation.go#L475)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

uber nit: else is superfluous here
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_sequence.go, line 60 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MpwlLLW5Dg0h2txUc-Q:-MpwuYR-7tCAQG6qiDMK:b57qo38) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_sequence.go#L60)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can this `dep.ColumnID == 0` case even legitimately exist?

If so, this test clause should be hoisted to the `if` two lines above.
</blockquote></details>

Done.

There are cases where it can be zero because we represent both sides of the relationship with the same node. So, I moved this up to skip over those scenarios.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwm7YWDsxfdYP1dYSn:-Mpx5_gR6VUXK9Vh5omX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7005e8e6c8e2deee7b1174df253d9a192ce1a125/pkg/sql/schemachanger/scpb/scpb.proto#L157)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Considering that `ConstraintID` is just a enum+ordinal pair, is it even worth having as a message? Seems like more trouble than it's worth and that we'd be better off replacing each field of type `ConstraintID` field with a `ConstraintType` type field and a `ConstraintOrdinal` field? Perhaps this has been discussed already between you and Andrew, I don't know. Not a big deal either way.
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
:lgtm:

Good work!

> Reviewed 4 of 14 files at r4, 2 of 4 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-:-MqGlipu6U_Mfe9qIDXT:bo6ckhq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[-- commits, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-Mpwi4h733AIej0g3iua):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for doing this, I appreciate the effort, and so will others.
___
*[pkg/sql/schemachanger/scpb/scpb.proto, line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73390#-MqGkk4q6hMiuTtOQJCy:-MqGkk4q6hMiuTtOQJCz:b-qhpjgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/71e683b6430e390de4e8edb1739977d5d718d637/pkg/sql/schemachanger/scpb/scpb.proto#L167)):*
> ```protobuf
>   option (gogoproto.equal) = true;
>   ConstraintType constraint_type = 1;
>   uint32 constraint_ordinal =2;
> ```

nit: missing space after `=`

**Comment by fqazi** [comment]
@postamar TFTR :)

**Pull request merged**
