### PR TITLE
streamingccl: enhance stream_ingestion_stats builtin to include more information

### PR DESCRIPTION
**Pull request by gh-casper**
This PR makes stream_ingestion_stats replication builtin to return more
information including stream ingestion details and progress. Also we now
have two variants, stream_ingestion_stats_pb that returns stats in protobuf
format, and stream_ingestion_stats_json that returns in json format.

This PR also supports querying stream progress without extending producer
job lifetime. More specifically, If 'frontier_ts' is specified with hlc.MaxTimestamp,
we treat it as only a query for the stream progress, instead of a heartbeat.

stream_ingestion_stats_* is not the replacement for metrics collected,
instead serves as a helper to get a quick overview of stream ingestion
status, aggregating almost all information about the ingestion job
and producer job together. It is supposed to run on the destination
cluster as the ingestion side has better knowledge of itself and the producer.

Example usage: SELECT stream_ingestion_stats_pb('ingestion_job_id')

Release note (sql change): create two invariants for stream_ingestion_stats 
builtin for protobuf and json respectively, stream_ingestion_stats_pb and 
stream_ingestion_stats_json, and extend them to return more details.

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Vu9A1HbcHQ09Ho5e:-N54Vu9A1HbcHQ09Ho5f:b-129642) (no related file):*
Nice to see this moving along.  I've left some minor comments on the code but nothing too major.

Eventually, I imagine we will want to also have some functions that return the status of these jobs as sql rows.  But we can iterate on what we need using this crdb_internal function for now.

___
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54k-ntEf6HscDkkiub):*
You can also mention the change in format and the addition of the _json function.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54_jUm7nxmZC7DXGs8:-N54_jUm7nxmZC7DXGs9:b-srtoos) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L103)):*
> ```Go
> 	}
> 	partitionProgress := make(map[string]*jobspb.StreamIngestionProgress_PartitionProgress)
> 	for sourcePartition, destPartition := range spec.SubscribingSqlInstances {
> ```

[nit] Would something like `srcPartitionID` and `dstSQLInstanceID` be better names for these loop variables?
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54UKbDAEfS3Y7rEX4g:-N54UKbDAEfS3Y7rEX4h:bbq0q2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L333)):*
> ```Go
> ) (bool, error) {
> 	var frontierChanged bool
> 	decodeResolvedSpans := func(resolvedSpanDatums rowenc.EncDatum) (*jobspb.ResolvedSpans, error) {
> ```

Up to you, but I could see moving this out its own func at the package level.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54L-Sx3su1rRQ-siSU:-N54L-Sx3su1rRQ-siSV:b-jks7we) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L400)):*
> ```Go
> 		curFrontier, ok := partitionFrontiers[partition]
> 		if !ok {
> 			err = errors.Errorf("Received progress update from unrecognized partition %s", partition)
> ```

[nit] s/Received/received/
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54SJi74TCQMSLTf75f:-N54SJi74TCQMSLTf75g:bp41kn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L83)):*
> ```Go
> 				lagInfo.FastestSourcePartition = partition
> 			}
> 			lagInfo.ReplicationLag = timeutil.Now().Sub(highwater.GoTime())
> ```

Does this need to be inside the loop?

Also, might want to use `timeutil.Since()` here.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54N43ACQsJzLldl95_:-N54N43ACQsJzLldl95a:bidasrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L92)):*
> ```Go
> 		return nil, err
> 	}
> 	streamStatus, err := client.Heartbeat(evalCtx.Ctx(), streaming.StreamID(details.StreamID), hlc.MinTimestamp)
> ```

No change required in this PR, but it is interesting to me that `crdb_internal.stream_ingestion_stats` will heartbeat the producer job, extending its life.  Feels like that might be worth documenting somewhere at least.

I also wonder if we want some sort of explicit timeout for this call since the user might be calling this function interactively.
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54XTbXDiao-4sIAphv:-N54XTbXDiao-4sIAphw:b-jvaqlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a93ffa6eba87e32ae4e405b0a8860c635fec328b/pkg/ccl/streamingccl/streampb/stream.proto#L114)):*
> ```protobuf
> 
> message StreamIngestionStats {
>   uint64 stream_id = 1;
> ```

Any particular reason we are removing this field?
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Ir-e3wxx_DZceLFk:-N54Ir-e3wxx_DZceLFl:b-o7r781) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streampb/stream.proto#L115)):*
> ```protobuf
> message StreamIngestionStats {
>   // The status of current stream producer job.
>   StreamReplicationStatus stream_replication_status = 1;
> ```

Perhaps `producer_status` might be a better name for this field?

I'm assuming we don't yet care about wire-compatibility of protobuf changes since this hasn't really shipped yet.
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54O22fEW1YpcZPzZDx:-N54O22fEW1YpcZPzZDy:b4q1wmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streampb/stream.proto#L137)):*
> ```protobuf
>     [(gogoproto.nullable) = false, (gogoproto.stdduration) = true];
> 
>     string fastest_source_partition = 3;
> ```

I wonder if it would be useful to also have the timestamp for each of these to get a sense of the range.  

In the long run, have we thought about a command that shows us all of the partitions?
___
*[`pkg/jobs/jobspb/jobs.proto` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Yu-C1iuxYHfBVgym:-N54Yu-C1iuxYHfBVgyn:b-ksw4mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/jobs/jobspb/jobs.proto#L107)):*
> ```protobuf
>     // surfaced to the user.
> 
>     // Source SQL instance that subscribes to this partition.
> ```

Should this be "Destination SQL instance"? Looking at where we we write to this value, we write the values in the SubscribingSqlInstances map, which I believe are currently populated with destination node IDs.
___
*[`pkg/sql/execinfrapb/processors_bulk_io.proto` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54aljT4_P1T_WNEfVn:-N54aljT4_P1T_WNEfVo:b-i59yt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/execinfrapb/processors_bulk_io.proto#L212)):*
> ```protobuf
>   repeated roachpb.Span tracked_spans = 2 [(gogoproto.nullable) = false];
> 
>   // Mapping between a source cluster partition and its subscribing sql instance
> ```

We appear to use "partition" and "partition ID" synonymously.  I'm not opposed to that, but in this case I wonder if "Mapping between a source cluster partition ID and its subscribing sql instance ID" might be good to clarify exactly what string and int are stored in this map. 
___
*[`pkg/sql/execinfrapb/processors_bulk_io.proto` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54aaSP8liY101zPkny:-N54aaSP8liY101zPknz:bx3s7cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/execinfrapb/processors_bulk_io.proto#L214)):*
> ```protobuf
>   // Mapping between a source cluster partition and its subscribing sql instance
>   // in the destination cluster. This describes the flow topology of the replication stream.
>   map<string, uint32> subscribing_sql_instances = 6 [(gogoproto.nullable) = false];
> ```

If you want you can give this a custom go field name with: `(gogoproto.customname) = "SubscribingSQLInstances"

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper, @stevendanna, and @yuzefovich)

___
*[`pkg/sql/sem/builtins/replication_builtins.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N55vvKn0p5C4REIqInb:-N55vvKn0p5C4REIqInc:babzz8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/sem/builtins/replication_builtins.go#L132)):*
> ```Go
> 					return nil, err
> 				}
> 				ingestionJobID := int64(tree.MustBeDInt(args[0]))
> ```

Let's add a `tree.DNull` check for `args[0]`.

**Comment by miretskiy** [comment]
> This PR makes stream_ingestion_stats replication builtin to return more information including stream ingestion details and progress.
> 
> Release note (sql change): enhance stream_ingestion_stats builtin to return more details.

Any chance to expand this commit message? explain how this builtin supposed to be used?
perhaps few examples?

**Review by gh-casper — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @stevendanna, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Vu9A1HbcHQ09Ho5e:-N57dek7-UVYbHSO-dsa:b-rdwatq) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Nice to see this moving along.  I've left some minor comments on the code but nothing too major.

Eventually, I imagine we will want to also have some functions that return the status of these jobs as sql rows.  But we can iterate on what we need using this crdb_internal function for now.
</blockquote></details>

Yes. That's the future SHOW REPLICATION STEAM <ingestion_job_id>.

___
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54k-ntEf6HscDkkiub):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

You can also mention the change in format and the addition of the _json function.
</blockquote></details>

Done.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54_jUm7nxmZC7DXGs8:-N5706a_EmD4vzH4951a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L103)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] Would something like `srcPartitionID` and `dstSQLInstanceID` be better names for these loop variables?
</blockquote></details>

Done.



_Code quote:_
```Go
SubscribingSqlInstances
```
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54UKbDAEfS3Y7rEX4g:-N571HcP4KAX4EbyFNp8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L333)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Up to you, but I could see moving this out its own func at the package level.
</blockquote></details>

Done.
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54L-Sx3su1rRQ-siSU:-N571NYz9Jtdp4jObKwu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L400)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] s/Received/received/
</blockquote></details>

Done.



_Code quote:_
```Go
Received progress
```
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54SJi74TCQMSLTf75f:-N571aScEkq3fs5i44-O:b-9ybz8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L83)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Does this need to be inside the loop?

Also, might want to use `timeutil.Since()` here.
</blockquote></details>

Moved out.



_Code quote:_
```Go
lagInfo.ReplicationLag = timeutil.Now().Sub(highwater.GoTime())
```
___
*[`pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54N43ACQsJzLldl95_:-N57dxV7AwsC61kejwSI:b-2x06tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go#L92)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

No change required in this PR, but it is interesting to me that `crdb_internal.stream_ingestion_stats` will heartbeat the producer job, extending its life.  Feels like that might be worth documenting somewhere at least.

I also wonder if we want some sort of explicit timeout for this call since the user might be calling this function interactively.
</blockquote></details>

I changed my mind on `stream_ingestion_stats` extending producer job life. It's not supposed to as it doesn't make sense. Now we only return producer job progress without updating it when the given frontier is `hlc.MaxTimestamp`. I know it's a little bit a hack but we can extend the meaning of `Heartbeat` to a broader sense, exchanging information. In the case of frontier being MaxTimestamp, we basically saying I don't have any update yet, no need to update your progress accordingly. What's your opinion? 
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54XTbXDiao-4sIAphv:-N57BxvICQuXpZoaubew:bswun9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a93ffa6eba87e32ae4e405b0a8860c635fec328b/pkg/ccl/streamingccl/streampb/stream.proto#L114)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Any particular reason we are removing this field?
</blockquote></details>

stream_id is redundant here as we have this field in stream_ingestion_details.
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Ir-e3wxx_DZceLFk:-N57CDwH-0Y3C6K5HC2b:b-4brb5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streampb/stream.proto#L115)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Perhaps `producer_status` might be a better name for this field?

I'm assuming we don't yet care about wire-compatibility of protobuf changes since this hasn't really shipped yet.
</blockquote></details>

Done. Yes, we don't yet care about wire-compatibility of protobuf changes.
___
*[`pkg/ccl/streamingccl/streampb/stream.proto` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54O22fEW1YpcZPzZDx:-N57CVyaEe7OpJx8rS_e:b-oo1swc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/ccl/streamingccl/streampb/stream.proto#L137)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wonder if it would be useful to also have the timestamp for each of these to get a sense of the range.  

In the long run, have we thought about a command that shows us all of the partitions?
</blockquote></details>

Actually in `stream_ingestion_progress`, we have the per-partition progress (ingested timestamp, its subscribing dest sql instance id) that tracks this. 

Now I added several fields in ReplicationLagInfo to make them clearer.
___
*[`pkg/jobs/jobspb/jobs.proto` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54Yu-C1iuxYHfBVgym:-N57KQl2DVYUWrrpgyug:b3t2z56) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/jobs/jobspb/jobs.proto#L107)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Should this be "Destination SQL instance"? Looking at where we we write to this value, we write the values in the SubscribingSqlInstances map, which I believe are currently populated with destination node IDs.
</blockquote></details>

Changed the name and description for it.
___
*[`pkg/jobs/jobspb/jobs.proto` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y5-r1-130:-N57KevbAv65vWKqoyCs:b-iysim) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/jobs/jobspb/jobs.proto#L130)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm a bit unsure about the need for this enum.

`NotStarted` -- doesn't it imply that cutover_time is empty?
`Started` -- doesn't it imply cutover_time is not empty?
`Finished` -- doesn't it imply that the job has finished?

Unless there is some other state that lives after cutover finishes, but before job finished?

Anyway, I'm not 100% sold on the need to have this enum.
@stevendanna thoughts?
</blockquote></details>

We need this for the future for several purposes.

We need to support adjusting cutover time later. We need to set status to be `Started` to prevent other user changes the cutover time after it's started.

`Finished` can help in the retry scenario. Let's say an ingestion job fails after the cutover finished (this field set to Finished), when we resume the job and we can skip the cutover and continue. You might say there's nothing to continue, but in the future, we have to make the tenant online and that can fail I believe.

I agree that this `CutoverStatus` is less for observability purpose, but I kinda want to introduce it here and also add a todo item.
___
*[`pkg/sql/execinfrapb/processors_bulk_io.proto` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54aljT4_P1T_WNEfVn:-N57Nd3N-Uujc7CK3cLZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/execinfrapb/processors_bulk_io.proto#L212)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

We appear to use "partition" and "partition ID" synonymously.  I'm not opposed to that, but in this case I wonder if "Mapping between a source cluster partition ID and its subscribing sql instance ID" might be good to clarify exactly what string and int are stored in this map. 
</blockquote></details>

Done.



_Code quote:_
```protobuf
Mapping between a source cluster partition and its subscribing sql instance
```
___
*[`pkg/sql/execinfrapb/processors_bulk_io.proto` line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N54aaSP8liY101zPkny:-N57P-kp6GHaTGjP9OMZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/execinfrapb/processors_bulk_io.proto#L214)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

If you want you can give this a custom go field name with: `(gogoproto.customname) = "SubscribingSQLInstances"
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/replication_builtins.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y7-r1-126:-N57P2ry43k4rdv2WB5i:b-toq2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/sem/builtins/replication_builtins.go#L126)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is this function intended to be used by end user? To view progress/stats? If so, does it make sense to return a JSON isntead?
</blockquote></details>

Oh, before this PR, `stream_ingestion_stats` returns the json format. Now I renamed it to `stream_ingestion_stats_json` and I introduced another `stream_ingestion_stats` which returns protobuf format. This is for convenience purpose, even though users can convert it by themselves.
___
*[`pkg/sql/sem/builtins/replication_builtins.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N55vvKn0p5C4REIqInb:-N57c24r7qFCMC3hf63t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/sem/builtins/replication_builtins.go#L132)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Let's add a `tree.DNull` check for `args[0]`.
</blockquote></details>

Done.

**Review by gh-casper — COMMENTED** [review]
Added.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-:-N57o7JK3TrhDMgjipFx:bqmjwcz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @stevendanna, and @yuzefovich)

**Review by stevendanna — COMMENTED** [review]
> Why wouldn't a check for cutover time != 0 not be sufficient?

I believe that in the proposed UX document, the user will be able to set a future cutover time on a still-running ingestion job. In that world, cutover_time may always be non-zero.  And, given that assumption, we also can't depend on just checking whether the cutover_time is in the past, because the user may have paused the job.

So, tracking whether cutover has actually been started seems reasonable to me, but if we do this in a follow up PR that makes use of it, we can perhaps think about it more clearly.

If we do add it here, then consider doing it as a separate commit where you can explain what it is used for.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-:-N59XHVVDqnC6jnZq9Pq:btkbzgj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gh-casper, @miretskiy, @stevendanna, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N59Z8NnDpheK5UJ9iH_:-N59Z8No9gUQpx2RGmR0:b-mehx18) (no related file):*
Thanks for addressing most of the comments.

I'd mildly prefer we move some of the unrelated changes to follow up PRs (I know this can be annoying given our current review cycle, but I think we can work on improving that).

___
___
*[`pkg/ccl/streamingccl/streamproducer/stream_lifetime.go` line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N59TE7I2cKkMCKwMXID:-N59TE7I2cKkMCKwMXIE:bqhyr06) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbb6a4614388f841376cadca49a923d6e56a882/pkg/ccl/streamingccl/streamproducer/stream_lifetime.go#L159)):*
> ```Go
> 		}
> 		status.ProtectedTimestamp = &ptsRecord.Timestamp
> 		return status, nil
> ```

Will this status's StreamStatus field be correct? 

Also, I'd slightly prefer if we created a different method for this behaviour -- but, I haven't thought it through that much.

While this change was in response to one of my comments, I think it might be better to do this in a follow-up PR.  If we do it in this PR, then I think we also need a test for this special behaviour.
___
*[`pkg/jobs/jobspb/jobs.proto` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y5-r1-130:-N59WLnLEc2cJrzCQO5d:b8r8s4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/jobs/jobspb/jobs.proto#L130)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

We need this for the future for several purposes.

We need to support adjusting cutover time later. We need to set status to be `Started` to prevent other user changes the cutover time after it's started.

`Finished` can help in the retry scenario. Let's say an ingestion job fails after the cutover finished (this field set to Finished), when we resume the job and we can skip the cutover and continue. You might say there's nothing to continue, but in the future, we have to make the tenant online and that can fail I believe.

I agree that this `CutoverStatus` is less for observability purpose, but I kinda want to introduce it here and also add a todo item.
</blockquote></details>

@gh-casper I think your explanation of why we need something that tracks the started state makes sense.  I think it is probably best to push this to another PR or commit where we also wire up the Started status?
___
*[`pkg/sql/sem/builtins/replication_builtins.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y7-r1-126:-N59QpKKDtIsqxDAPLzh:b-kajbfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/sem/builtins/replication_builtins.go#L126)):*
<details><summary><i>Previously, gh-casper wrote…</i></summary><blockquote>

Oh, before this PR, `stream_ingestion_stats` returns the json format. Now I renamed it to `stream_ingestion_stats_json` and I introduced another `stream_ingestion_stats` which returns protobuf format. This is for convenience purpose, even though users can convert it by themselves.
</blockquote></details>

As an FYI:  Another option here would be to have a single function with two different overloads, a single argument version that returns whatever we want the default format to be and a 2-argument overload that takes a second 'format' argument.

That said, my guess is that almost all users of this over SQL will want the json version, so perhaps that should be the default.

**Review by gh-casper — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83066)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @stevendanna, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N59Z8NnDpheK5UJ9iH_:-N5D017a-2ufBdBCO6nT:b-896fix) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Thanks for addressing most of the comments.

I'd mildly prefer we move some of the unrelated changes to follow up PRs (I know this can be annoying given our current review cycle, but I think we can work on improving that).
</blockquote></details>

Done.

___
___
*[`pkg/ccl/streamingccl/streamproducer/stream_lifetime.go` line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N59TE7I2cKkMCKwMXID:-N5D03ro9cBaX0vJzn72:b-rm0eqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbb6a4614388f841376cadca49a923d6e56a882/pkg/ccl/streamingccl/streamproducer/stream_lifetime.go#L159)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Will this status's StreamStatus field be correct? 

Also, I'd slightly prefer if we created a different method for this behaviour -- but, I haven't thought it through that much.

While this change was in response to one of my comments, I think it might be better to do this in a follow-up PR.  If we do it in this PR, then I think we also need a test for this special behaviour.
</blockquote></details>

On another commit.
___
*[`pkg/jobs/jobspb/jobs.proto` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y5-r1-130:-N5D-If19FdlGomhmeYF:brijyyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/jobs/jobspb/jobs.proto#L130)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

@gh-casper I think your explanation of why we need something that tracks the started state makes sense.  I think it is probably best to push this to another PR or commit where we also wire up the Started status?
</blockquote></details>

Sure. Removed Cutover for now.
___
*[`pkg/sql/sem/builtins/replication_builtins.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83066#-N4t12NnEuR5yRVE_4y7-r1-126:-N5D0CL70lxBsGMxif3v:b8bk5xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc163d876db6f909f4614d805c6ac320508ed097/pkg/sql/sem/builtins/replication_builtins.go#L126)):*
> a 2-argument overload that takes a second 'format' argument
Don't know the return type of the 2-argument overload. If protobuf, it should be `types.Bytes`. If json, it should be `types.Jsonb`.

I think we can change the `stream_ingestion_stats` to be `stream_ingestion_stats_pb` so that we don't assume what users want by default.

**Review by stevendanna — APPROVED** [review]

**Pull request merged**
