### PR TITLE
sql: fix recent leak of a context

### LINKED ISSUE #84801: roachtest: kv95/enc=false/nodes=3/cpu=32/no-admission failed [context oom]
roachtest.kv95/enc=false/nodes=3/cpu=32/no-admission [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/5813918?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyAwsBazel/5813918?buildTab=artifacts#/kv95/enc=false/nodes=3/cpu=32/no-admission) on master @ [457d724622e4fa2e62d6f4e7926509dbc7d18511](https://github.com/cockroachdb/cockroach/commits/457d724622e4fa2e62d6f4e7926509dbc7d18511):

```
		  |  1148.0s        0        94798.2        89682.9      0.9      6.3     10.5     32.5 read
		  |  1148.0s        0         5115.6         4719.9      2.0      7.1     11.5     21.0 write
		  |  1149.0s        0        86771.3        89680.4      1.4      6.0      9.4     24.1 read
		  |  1149.0s        0         4574.5         4719.8      2.6      7.6     12.1     24.1 write
		  |  1150.0s        0        77794.4        89670.1      1.6      5.8      8.4     19.9 read
		  |  1150.0s        0         4034.3         4719.2      3.1      7.3     10.0     14.2 write
		  | _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		  |  1151.0s        0            0.0        89592.1      0.0      0.0      0.0      0.0 read
		  |  1151.0s        0            0.0         4715.1      0.0      0.0      0.0      0.0 write
		  |  1152.0s        0            0.0        89514.4      0.0      0.0      0.0      0.0 read
		  |  1152.0s        0            0.0         4711.0      0.0      0.0      0.0      0.0 write
		Wraps: (4) COMMAND_PROBLEM
		Wraps: (5) Node 4. Command with error:
		  | ``````
		  | ./workload run kv --init --histograms=perf/stats.json --concurrency=192 --splits=1000 --duration=30m0s --read-percent=95 {pgurl:1-3}
		  | ``````
		Wraps: (6) exit status 1
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *cluster.WithCommandDetails (4) errors.Cmd (5) *hintdetail.withDetail (6) *exec.ExitError

	monitor.go:127,kv.go:159,kv.go:289,test_runner.go:896: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:159
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerKV.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/kv.go:289
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:896
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	main/pkg/cmd/roachtest/monitor.go:80
		  | runtime.doInit
		  | 	GOROOT/src/runtime/proc.go:6498
		  | runtime.main
		  | 	GOROOT/src/runtime/proc.go:238
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=aws</code>
, <code>ROACHTEST_cpu=32</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/test-eng
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*kv95/enc=false/nodes=3/cpu=32/no-admission.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-17874

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #84801.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
As @andreimatei pointed out, it doesn't leak a goroutine if we stick to stdlib contexts, but it does hold on to some memory, so reword as context leak rather than goroutine leak.

**Comment by yuzefovich** [comment]
Fixed.

TFTR!

bors r+

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`pkg/sql/conn_executor_exec.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WKeaYAu9UeXIVCOO8:-N7WKeaYAu9UeXIVCOO9:bsagc2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L284)):*
> ```Go
> 	var cancelQuery context.CancelFunc
> 	ctx, cancelQuery = contextutil.WithCancel(ctx)
> 	// When we exit this method, the execution flow must have finished, so
> ```

remove this comment :P
___
*[`pkg/sql/conn_executor_exec.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WMiI04IiTSosXmv_Q:-N7WMiI04IiTSosXmv_R:b-42hid2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L334)):*
> ```Go
> 	}
> 
> 	ex.addActiveQuery(ast, formatWithPlaceholders(ast, ex.planner.EvalContext()), queryID, cancelQuery)
> ```

let's move the creation of `cancelQuery` down, just above this, to make it easier to see that there's a connection between that cancel func and this registry. Let's also merge the `defer cancelQuery()` with the defer below; let's do `cancelQuery()` after `removeActiveQuery()` (even though that's not strictly required since `cancelQuery` is thread-safe).


And btw, move these lines below the defer.
```
	if ex.executorType != executorTypeInternal {
		ex.metrics.EngineMetrics.SQLActiveStatements.Inc(1)
	}
```
___
*[`pkg/sql/conn_executor_exec.go` line 512 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WMFx4C8WYiD6OL31T:-N7WMFx4C8WYiD6OL31U:b-w9i1ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L512)):*
> ```Go
> 			timerDuration,
> 			func() {
> 				ex.cancelQuery(queryID)
> ```

call `cancelQuery()` here instead of `ex.cancelQuery()`; there's no longer a reason to go through that registry.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/sql/conn_executor_exec.go` line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WKeaYAu9UeXIVCOO8:-N7WOB8TBI8muPCyDptF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L284)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

remove this comment :P
</blockquote></details>

Done.
___
*[`pkg/sql/conn_executor_exec.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WMiI04IiTSosXmv_Q:-N7WPE2XCPH_JQW9kHiX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L334)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's move the creation of `cancelQuery` down, just above this, to make it easier to see that there's a connection between that cancel func and this registry. Let's also merge the `defer cancelQuery()` with the defer below; let's do `cancelQuery()` after `removeActiveQuery()` (even though that's not strictly required since `cancelQuery` is thread-safe).


And btw, move these lines below the defer.
```
	if ex.executorType != executorTypeInternal {
		ex.metrics.EngineMetrics.SQLActiveStatements.Inc(1)
	}
```
</blockquote></details>

Done.
___
*[`pkg/sql/conn_executor_exec.go` line 512 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-N7WMFx4C8WYiD6OL31T:-N7WOsgGEV3HZYXsYt63:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d4afbc0130430186a64e9aed4138522de83da9c/pkg/sql/conn_executor_exec.go#L512)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

call `cancelQuery()` here instead of `ex.cancelQuery()`; there's no longer a reason to go through that registry.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
looks good but the tests are complaining that query errors are being generated. We somehow overwrite a query error, or produce an error as a result of the cancelation; I don't immediately see why that happens.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-:-N7WRVLS61epa0a_kvkS:b-93nzek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by yuzefovich — COMMENTED** [review]
We do check whether the ctx is canceled and change the error in that large `defer`, so we just needed to move the things around a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-:-N7WTkn19kBI3evnWsdV:b17vmob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84851#-:-N7WW1Cg-kNcd5PnTkqm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Pull request merged**
