### PR TITLE
sql/parser: add yacc type checking back into make process

### PR DESCRIPTION
**Pull request by nvb**
Previously in #4216 we had manually migrated our `sql.y` syntax
to support a union type. Unfortunately, this meant that we
lost all type checking provided by the yacc compiler, because all
`%type`/`%token` type declarations dealing with union types had been
changes to `%type <union> ...`. This change introduces a migration
step into the Makefile so that we can once again have access to this
type checking. Specifically:
- The `sql.y` syntax file has been restored to use the proper `%type <type_name>` 
  type declaration syntax, even for union types.
- The Makefile will first attempt to run this syntax through yacc
  to check for proper typing, as was done before unionizing most of
  the fields. Note that the script does not need to worry about the
  `.val` references or accessor methods in yacc rules, which are still
  needed in the syntax file, because yacc doesn't do any type checking
  within rules.
  
  At this point, if there is a type error, the yacc compiler will
  complain with a `"default action causes potential type clash"` error,
  as it used to.
- Next, the Makefile will run the syntax through a bit of `grep`/`sed`
  magic to convert the type declarations to unions so that the real
  `sql.go` file can be produced with the proper union types. One
  check that this is currently working is that the `sql.go` file was not
  affected by this change.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4364)

### CODE REVIEW

**Comment by petermattis** [comment]
Glad to see this done. A little bit of simplification to the implementation seems possible. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/Makefile, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANJWrQSBo9Z-YrJFD8:-KANJWrQSBo9Z-YrJFD9:899027773) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L12)):*
The `cat`, `sed` and `grep ` can be replaced by `awk '/func.*sqlSymUnion/ {print $(NF - 1)}' sql.y`.

---

*[sql/parser/Makefile, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANIeLEJCCMC6cEthC8:-KANIeLEJCCMC6cEthC9:2039268775) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L16)):*
Why do you have to save and restore `sql.y`? I would think that you could create an `sql.y.tmp` from `sql.y` and run yacc on `sql.y.tmp` and then delete `sql.y.tmp`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-:-KANK5KpuRIf95LvU8zq:1143645975)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/Makefile, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANJWrQSBo9Z-YrJFD8:-KANaj9imwNk3xh16H5Z:1877094695) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L12)):*
Magical. Done.

---

*[sql/parser/Makefile, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANIeLEJCCMC6cEthC8:-KANajfh5pyGiVati5T4:337568697) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L16)):*
The exclusive reason I'm doing it this way is so `sql.go` will have auto-generated comments that say `//line sql.y:30` instead of `//line sql.y.tmp:30`. If that doesn't seem like an issue to you, we can simplify.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/Makefile, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANIeLEJCCMC6cEthC8:-KASOpfavpInd8PuvAqq:968456542) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L16)):*
That sounds like a good reason. Looking at this again, I think this is too much work being done in the Makefile.  I suggest moving the bulk to a shell script which is invoked by the Makefile. This will allow easier commenting to provide clarity as to what is going on (such as your description of why `sql.y` is being compiled instead of `sql.y.tmp`). 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-:-KASPGBwySHRplDX99L6:676834233)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/Makefile, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANIeLEJCCMC6cEthC8:-KASwhL-0p2MIGGvRYQ7:-453717930) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L16)):*
I moved the logic within the Makefile rules into a `sql_union.sh` script. I wasn't sure if this should go in the `sql/parser/` dir or the `build/` dir, but I figured it should probably be close to the Makefile using it. PTAL

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/sql_union.sh, line 5 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATg-2kZMuaizP2bLFk:-KATg-2kZMuaizP2bLFl:-1179667223) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L5)):*
can you hand this down from the makefile? i.e. `YACC=$(YACC) ./sql_union.sh`

---

*[sql/parser/sql_union.sh, line 12 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATgIgz2GDEa1FQ1Ofc:-KATgIgz2GDEa1FQ1Ofd:1248363515) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L12)):*
withint?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/sql_union.sh, line 5 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATg-2kZMuaizP2bLFk:-KATjxsRLw0EsGAUVEBM:431195067) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L5)):*
Done. What's the convention for something like this though? Is it better to have the script be self-contained or to request external dependencies from the parent Makefile?

---

*[sql/parser/sql_union.sh, line 12 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATgIgz2GDEa1FQ1Ofc:-KATkJTWHs7Wg6iVLl3p:2099998112) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L12)):*
If  [misspell](https://github.com/client9/misspell) says it's a word, I don't see a problem

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/sql_union.sh, line 5 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATg-2kZMuaizP2bLFk:-KAToZhSW5ViwlN9R00L:476449669) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L5)):*
I'm not sure, but it also probably doesn't matter in this case. In go 1.6 this will change to `go tool yacc`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/sql_union.sh, line 5 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATg-2kZMuaizP2bLFk:-KAToklddPWa2aYJMErF:-143144487) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L5)):*
also YACC is now unused in the Makefile, so you can define it only here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by petermattis** [comment]
LGTM (again)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/Makefile, line 16 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KANIeLEJCCMC6cEthC8:-KAW06yzZm3c0djl_CJd:-120198786) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4e69d9edd79254444ca327206da2ce1ea8fa10a/sql/parser/Makefile#L16)):*
Yes, placing the script next to the Makefile is the right thing to do.

---

*[sql/parser/sql_union.sh, line 11 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KAW051ff9psj9tuWygz:-KAW051g4pv3YdkTUrUS:1313931292) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b219f6a11a77ce015d49fa0cd0eb7f1336df09c/sql/parser/sql_union.sh#L11)):*
Nice comments.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-:-KAW0Cb1U5JPda7AtORV:-1469122166)*

**Comment by nvanbenschoten** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/sql_union.sh, line 5 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KATg-2kZMuaizP2bLFk:-KAXiooSzHWyjowja7B-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cebd53330f0b33fedf5e50bdecd5def8b88a1cc/sql/parser/sql_union.sh#L5)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/Makefile, line 1 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KAXmjbir35Oooy10-Ib:-KAXmjbir35Oooy10-Ic:-1925365462) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02550203288bf788baa06f285912bc67b60cd7d/sql/parser/Makefile#L1)):*
i think you meant to delete this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/Makefile, line 1 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364#-KAXmjbir35Oooy10-Ib:-KAXnPSxS9MVrioakuq2:296096953) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02550203288bf788baa06f285912bc67b60cd7d/sql/parser/Makefile#L1)):*
Yep... https://github.com/cockroachdb/cockroach/pull/4376

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4364)*

**Pull request merged**
