### PR TITLE
sql: make some tweaks to using the vectorized engine

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: enable wrapping of unordered distinct in vectorized flow**

Release justification: bug fixes and low-risk updates to new
functionality.

This commit enhances `isSupported` check during the vectorized execution
planning so that operators that cannot run in `auto` mode (unordered
distinct, percent_rank, and cume_dist) would be reported as
"unsupported" which will enable wrapping the processor cores into the
vectorized flow. Previously, we would refuse to vectorize the whole flow
which is a mistake.

Release note: None

**sql: rename vectorize `experimental_on` to `on`**

Release justification: bug fixes and low-risk updates to new
functionality.

This commit renames `experimental_on` option of `vectorize` variable to
`on` since we're now confident in the correctness. This commit also
changes the behavior of `EXPLAIN (VEC)` slightly - previously, we were
setting `vectorize` to (what was) `experimental_on` and then running
`SupportsVectorized` check. Now we will return an error if `vectorize`
is set to `off` and in other cases we will run the check with the
current `vectorize` mode. This is done so that `EXPLAIN (VEC)` better
reflects reality.

Release note (sql change): `experimental_on` option for `vectorize`
session variable has been renamed to `on`. The only things that will
not run with `auto` but will run with `on` are unordered distinct and
two window functions (`percent_rank` and `cume_dist`), otherwise, the
two options are identical.

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
cc @ericharmeling on the rename

> Reviewed 12 of 12 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-:-M2XjYWyCH1wz0I4YkjA:b-7gwy53)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoEclA8jUYEyrexUY:-M2XoEclA8jUYEyrexUZ:bf01sda) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/cmd/roachtest/tpchvec.go#L515)):*
> ```Go
> 				vectorizeSetting := "off"
> 				if vectorize {
> 					for versionPrefix, vectorizeOption := range vectorizeOptionByVersionPrefix {
> ```

nit: might be cleaner to get the prefix from the version and access the map using that.
___
*[pkg/sql/explain_vec.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoSVYE5Mqx-uHspU8:-M2XoSVZ9_5kYjtoy6Wx:b27ltnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/sql/explain_vec.go#L79)):*
> ```Go
> 
> 	if flowCtx.EvalCtx.SessionData.VectorizeMode == sessiondata.VectorizeOff {
> 		return errors.New("vectorize set to 'off'")
> ```

Why is this changing? Please also add a comment detailing the reasoning for this behavior.
___
*[pkg/sql/colexec/execplan.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2Xn5T_DZbpggIAeVvV:-M2Xn5T_DZbpggIAeVvW:b-xsjsgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa79e9e238e998064e543fb1db5ca9fe6574ef6f/pkg/sql/colexec/execplan.go#L229)):*
> ```Go
> 			return false, errors.Newf("distinct with error on duplicates not supported")
> 		}
> 		if mode != sessiondata.VectorizeExperimentalOn && mode != sessiondata.VectorizeExperimentalAlways {
> ```

Extract this check into a helper function and reuse for window fns.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoEclA8jUYEyrexUY:-M2Yqhig4ku5Fhn1o21w:bm7ot66) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/cmd/roachtest/tpchvec.go#L515)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: might be cleaner to get the prefix from the version and access the map using that.
</blockquote></details>

There is already a precedent in this file of doing this kind of map iteration and prefix matching. I'd keep it this way because it's hard to mess this up whereas if we switch to extracting a prefix from the version first, I think that would be more error-prone.
___
*[pkg/sql/explain_vec.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoSVYE5Mqx-uHspU8:-M2YylleBQEYmaqrz6O8:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/sql/explain_vec.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this changing? Please also add a comment detailing the reasoning for this behavior.
</blockquote></details>

Added a comment.
___
*[pkg/sql/colexec/execplan.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2Xn5T_DZbpggIAeVvV:-M2YoTNXAuJBs6GkweiK:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa79e9e238e998064e543fb1db5ca9fe6574ef6f/pkg/sql/colexec/execplan.go#L229)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Extract this check into a helper function and reuse for window fns.
</blockquote></details>

Good point, done.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus `EXPLAIN` comment.

> Reviewed 13 of 13 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-:-M2bzFRl819OTlVCA32-:b247k1x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/explain_vec.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoSVYE5Mqx-uHspU8:-M2byhh640havLVGCACG:b-3alv0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/sql/explain_vec.go#L79)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Added a comment.
</blockquote></details>

So currently when running `EXPLAIN` `vectorize` will show `false` if vectorize is off. But now running an `EXPLAIN` will return an error? Or is this only for `EXPLAIN (VEC)`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46080)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/explain_vec.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2XoSVYE5Mqx-uHspU8:-M2cpyXz7oiSw0k6p0le:b-833i1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f6028e8053858a6be3a851a19f3582e008d29b1/pkg/sql/explain_vec.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So currently when running `EXPLAIN` `vectorize` will show `false` if vectorize is off. But now running an `EXPLAIN` will return an error? Or is this only for `EXPLAIN (VEC)`
</blockquote></details>

This change affects only `EXPLAIN (VEC)` variant:
```
root@:26257/tpch> set vectorize=off;
SET

Time: 292µs

root@:26257/tpch> explain (vec) select count(*) from lineitem;
ERROR: vectorize is set to 'off'
root@:26257/tpch> explain select count(*) from lineitem;
    tree    |    field    |  description
------------+-------------+----------------
            | distributed | true
            | vectorized  | false
  group     |             |
   │        | aggregate 0 | count_rows()
   │        | scalar      |
   └── scan |             |
            | table       | lineitem@l_ok
            | spans       | ALL
(8 rows)

Time: 669µs

root@:26257/tpch> set vectorize=auto;
SET

Time: 296µs

root@:26257/tpch> explain select count(*) from lineitem;
    tree    |    field    |  description
------------+-------------+----------------
            | distributed | true
            | vectorized  | true
  group     |             |
   │        | aggregate 0 | count_rows()
   │        | scalar      |
   └── scan |             |
            | table       | lineitem@l_ok
            | spans       | ALL
(8 rows)

Time: 879µs

root@:26257/tpch> explain (vec) select count(*) from lineitem;
             text
-------------------------------
  │
  └ Node 1
    └ *colexec.countOp
      └ *colexec.colBatchScan
(4 rows)
```
Regular `EXPLAIN` didn't override the vectorize setting, so no changes are needed in there.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46080)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/logictest/logic.go, line 564 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/46080#-M2crNb79HL4badKTduP:-M2crNb79HL4badKTduQ:b-cu0xja) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8cc60b4684f8b2a13faffa0a9c84010723210dc/pkg/sql/logictest/logic.go#L564)):*
> ```Go
> 		"local",
> 		"local-vec-off",
> 		"local-vec",
> ```

@asubiotto what do you think about removing `local-vec`, `fakedist-vec`, `fakedist-vec-disk` configs from the ist of the default ones because they are basically the same as without "-vec" suffix? We would explicitly put this configs into the "distinct" and "window" logic tests and probably would get almost the same coverage.

**Comment by asubiotto** [comment]
That's a good idea but I would probably wait until the 20.1 branch gets cut. My reasoning is that we might still want to switch off some new functionality but keep the testing coverage without adding explicit configs to the test files.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Noticed a typo in the comment.

bors r-

**Comment by yuzefovich** [comment]
Never mind, I think the comment is good.

bors r+

**Pull request merged**
