### PR TITLE
gossip: test forwarding never sends self

### PR DESCRIPTION
**Pull request by tamird**
@petermattis apologies for duplicating this work - I initially thought you had assigned me the issue rather than the PR.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5921)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip_test.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-KElKFeAys53nEnQPz5p:-KElKFeBYSf2vCLv0Ncm:789920279) ([raw file](https://github.com/cockroachdb/cockroach/blob/33cdb2b4fa585d87eabcb598f6c58ffdbed647f9/gossip/gossip_test.go#L171)):*
`s/non/none/g`

---

*[gossip/gossip_test.go, line 190 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-KElL1bu_mQ0FWKu8dxU:-KElL1bvz2u5H5h8dYB3:-418116501) ([raw file](https://github.com/cockroachdb/cockroach/blob/33cdb2b4fa585d87eabcb598f6c58ffdbed647f9/gossip/gossip_test.go#L190)):*
Does this reliably fail if you comment out the `args.NodeID == s.is.NodeID` condition in `server.gossipReceiver`? Wondering where the `100` number came from.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-:-KElLEpDZn5RIt4YTaOe:1417088721)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip_test.go, line 171 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-KElKFeAys53nEnQPz5p:-KElLX4DxjxwTUbmJ_io:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/33cdb2b4fa585d87eabcb598f6c58ffdbed647f9/gossip/gossip_test.go#L171)):*
Done.

---

*[gossip/gossip_test.go, line 190 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-KElL1bu_mQ0FWKu8dxU:-KElLXUhFM81mJQPbvvB:-1343508119) ([raw file](https://github.com/cockroachdb/cockroach/blob/33cdb2b4fa585d87eabcb598f6c58ffdbed647f9/gossip/gossip_test.go#L190)):*
Well, it doesn't exactly fail - it panics on the assertion which is still in there, but it does so reliably. Maybe I should remove the assertion, now that we have this test?

The number 100 is just what I started with, no particular origin.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921)*

**Comment by tamird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[gossip/gossip_test.go, line 190 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921#-KElL1bu_mQ0FWKu8dxU:-KElNZY324_FiJSe98jL:-409372469) ([raw file](https://github.com/cockroachdb/cockroach/blob/33cdb2b4fa585d87eabcb598f6c58ffdbed647f9/gossip/gossip_test.go#L190)):*
Removed the panic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5921)*

**Pull request merged**
