### PR TITLE
Add cluster overview page

### PR DESCRIPTION
**Pull request by maxlang**
This adds the cluster overview page and some changes to the graphs that I added to support it.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3863)

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[ui/ts/models/metrics.ts, line 245 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94CUEwhrsy0Eb6yphb:-K94CUExZHsJaJuf1ZdT:1852233548) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/models/metrics.ts#L245)):*
I do not believe that this property belongs on the Axis.  The Axis is more about selecting the data and decorating with some metadata (such as labels) which belongs very close to the data.

"Stacked", on the other hand, is a different chart type, not a different Axis type.  It's a peer to LineChart in a perfect world, although it could also be expressed as a variable to the LineChart.

Think of it this way: it should be possible to place to Axis on the same chart. You can have two Y-axis (one on the left, one on the right); this allows you visually to correlate changes in series which have different units.

In the case of "range", its probably appropriate for the axis, although it seems like you've smashed together two different properties (i.e. a forced range vs. a required range).  I think d3 might refer to these as "range" and "domain", I forget the exact nomenclature.

---

*[ui/ts/models/metrics.ts, line 256 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K947JBzjSc1aYF5Mmks:-K947JBzjSc1aYF5Mmkt:854527954) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/models/metrics.ts#L256)):*
Hah, this is a new pattern of sorts: a *settable* computed property. This is fine as is, but if we start using this elsewhere we'll want to expand our property library.

---

*[ui/ts/pages/cluster.ts, line 13 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K947h6DXNCi9ldCocPM:-K947h6DXNCi9ldCocPN:766723148) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L13)):*
Change author to yourself. 

We should probably should just scrap author tags.

---

*[ui/ts/pages/cluster.ts, line 25 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9487OJaaQRW9-aYD5b:-K9487OJaaQRW9-aYD5c:-1480801670) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L25)):*
Comments are wrong in this file in several places.

---

*[ui/ts/pages/cluster.ts, line 53 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9489pWrNhA9VGtqDih:-K9489pWrNhA9VGtqDii:2039129388) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L53)):*
Wrong coment.

---

*[ui/ts/pages/cluster.ts, line 60 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K948a-jaDXV2h8WwItt:-K948a-jaDXV2h8WwItu:-371010025) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L60)):*
So we're showing log entries for now?  I think I would rather show no table for now, and just wait for events to be available.

---

*[ui/ts/pages/cluster.ts, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94BR4H-qLXRdNt29TA:-K94BR4I6OQ9C_cI4t9P:-1110551836) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L137)):*
Use the form `(q: string): selector => {` with the double-arrow, which preserves the `this` pointer.  Then you don't need to use `thiz`.

---

*[ui/ts/pages/cluster.ts, line 145 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94BrEzU6MxBbnwZ916:-K94BrEzU6MxBbnwZ917:605462815) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L145)):*
This should be `title()`, not `_title()`?  I don't see how this compiles.  Also, there might be some indentation quirks here, hard to tell on reviewable.

---

*[ui/ts/pages/cluster.ts, line 179 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94CEDfF-aWRfpKQTAl:-K94CEDgIiXHvHWbeWuX:-1721079557) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L179)):*
Reiterating that I would elect *not* to show logs at all on the cluster page, too much noise.  Let's just wait until events are available; we may not even want to show those, the overview might be adequate for this page.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by tamird** [comment]
there are two commits here that "add nib" - should they be squashed?

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 3 of 3 files at r4, 4 of 7 files at r5.
Review status: 13 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[ui/styl/partials/layout.styl, line 30 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94SX9ROX08x78uPkJ9:-K94SX9SIBn_R9Fqwejf:-1119060038) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc91a3402be5c62875214743a017e12ee4be88d3/ui/styl/partials/layout.styl#L30)):*
doesn't appear to be in the right commit?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-:-K94SrYP1xjNkmdouZvS:-300577644)*

**Comment by maxlang** [comment]
@tamird 's old comments are here: https://github.com/cockroachdb/cockroach/commit/681382ab1708cc98cf1053e26be5d61fd33fef23

**Comment by maxlang** [comment]
Review status: 3 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[ui/ts/models/metrics.ts, line 245 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94CUEwhrsy0Eb6yphb:-K9PYDXIw7WBuC-4De2A:168566065) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/models/metrics.ts#L245)):*
Good point, this should probably be captured as a different chart/axis type vs an axis property.

The problem with range is that nvd3 has different properties for stacked area charts vs line charts, so I can't support the exact same behavior for stacked vs non-stacked. This would be fixed if chart/axis had different types.

If you're ok with leaving this for now, I think this change should be made in a different PR because currently we only have one chart/axis type so it'll be a bit of a refactor to add new types.

I'm not sure if we want to support two different axes on the same chart at first, but it could make sense to have "AxisGraph" be the main type and then have the Axes have types. Then ultimately you could support combo graphs like this: http://nvd3.org/examples/linePlusBar.html

---

*[ui/ts/models/metrics.ts, line 256 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K947JBzjSc1aYF5Mmks:-K9PVwogjkySa8FmJYCa:-1822390241) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/models/metrics.ts#L256)):*
Yeah, I wasn't sure how to fit this in to the previous pattern, so I just made it a special case here. A reasonable next step could be to allow the default to be ```T|()=>T```

---

*[ui/ts/pages/cluster.ts, line 13 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K947h6DXNCi9ldCocPM:-K9PUvHPchEkLt8Oz9c-:-723527612) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L13)):*
Yeah, author tags probably don't make as much sense here.

---

*[ui/ts/pages/cluster.ts, line 25 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9487OJaaQRW9-aYD5b:-K9PVNNwnD78MNx-5zDF:419444817) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L25)):*
Whoops, yeah, copy-pasted in a hurry.

---

*[ui/ts/pages/cluster.ts, line 53 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9489pWrNhA9VGtqDih:-K9PSC9IDVZW-EfLDSum:677916264) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L53)):*
oops

---

*[ui/ts/pages/cluster.ts, line 60 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K948a-jaDXV2h8WwItt:-K9PSEg8dLh-NY4BIkou:-1343020198) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L60)):*
Fair, I added this in for people to get a sense of the layout, but we have the mocks for events now.

---

*[ui/ts/pages/cluster.ts, line 137 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94BR4H-qLXRdNt29TA:-K9PTZpiujeXa8vQAQgT:-2003896356) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L137)):*
Thanks, fixed.

---

*[ui/ts/pages/cluster.ts, line 145 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94BrEzU6MxBbnwZ916:-K9PUHaE6q6vEyPPMIr8:1073045598) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L145)):*
Yeah this was incorrect. Not sure why I didn't catch it earlier, but you're right that it doesn't compile.

---

*[ui/ts/pages/cluster.ts, line 179 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94CEDfF-aWRfpKQTAl:-K9PUT8Sb4YMnfzGKsR3:1740281843) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/pages/cluster.ts#L179)):*
Removed.

---

*[ui/styl/partials/layout.styl, line 30 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94SX9ROX08x78uPkJ9:-K9PUXas6rABfQ3O0ct8:855541368) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc91a3402be5c62875214743a017e12ee4be88d3/ui/styl/partials/layout.styl#L30)):*
This stuff was included from another PR that was still in progress. Gone now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by maxlang** [comment]
Cluster page as of this PR (wip, will be changing since there are new designs)

screen shot 2016-01-31 at 8 15 28 pm

**Comment by maxlang** [comment]
I will squash the changes into one commit once the review gets an LGTM. Currently I've kept the changes based on PR comments in a separate commit.

**Comment by tamird** [comment]
Reviewed 2 of 4 files at r7, 5 of 5 files at r8.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[ui/ts/models/metrics.ts, line 258 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9TfpfX9SWaUgmOujHa:-K9TfpfY8VUck2KCt6o-:-909575204) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/models/metrics.ts#L258)):*
doesn't this return `string|Axis`?

---

*[ui/ts/pages/cluster.ts, line 167 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9Tg2UOT1qgkTTYja2k:-K9Tg2UOT1qgkTTYja2l:-297596466) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/pages/cluster.ts#L167)):*
i think this is overindented. also, does this need to be`any`?

---

*[ui/tsd.json, line 15 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9TfULuM0ce5mvBrNgk:-K9TfULvQb3MeQ6iXxUs:1906436169) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/tsd.json#L15)):*
is this an errant merge conflict resolution?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[ui/ts/models/metrics.ts, line 258 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9TfpfX9SWaUgmOujHa:-K9VIjkU5irxGdUejKTt:-683174229) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/models/metrics.ts#L258)):*
This causes the error: ```ts/models/metrics.ts(255,7): error TS2394: Overload signature is not compatible with function implementation.```

I'll add a TODO to add this to the chain prop utilities where this seems to work better.

---

*[ui/ts/pages/cluster.ts, line 167 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9Tg2UOT1qgkTTYja2k:-K9VJOhlk9DpTHcoJfIN:-695247207) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/pages/cluster.ts#L167)):*
Otherwise you get ```ts/pages/cluster.ts(167,40): error TS2314: Generic type 'MithrilComponent<T>' requires 1 type argument(s).```

I'll fix up the indentation.

---

*[ui/tsd.json, line 15 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9TfULuM0ce5mvBrNgk:-K9ThdJPqPrlsHogHFii:1976323304) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/tsd.json#L15)):*
It was updated when I added nvd3

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by tamird** [comment]
Review status: 5 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[ui/ts/pages/cluster.ts, line 167 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9Tg2UOT1qgkTTYja2k:-K9Xe4cP1u5iL1GWUOm4:-393636651) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/pages/cluster.ts#L167)):*
Right, I understand that it needs a type argument, but why must it be `any`? this array is homogenous.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by maxlang** [comment]
Review status: 5 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[ui/ts/pages/cluster.ts, line 167 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K9Tg2UOT1qgkTTYja2k:-K9YG8eSCrS7HkXnzfpL:-212298745) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e296fdc559941e9d023863a8182e748a3c6a369/ui/ts/pages/cluster.ts#L167)):*
It's parameterized by the controller type, but ```VisualizationWrapper``` doesn't have a controller type (it's very simple and doesn't have a controller.) I can't just pass in void because the type passed in needs to extend ```MithrilController```. I could write it as ```MithrilComponent<{}>``` but that doesn't really add anything and is also technically wrong because the controller is actually ```undefined```. Ultimately it's probably a limitation of the mithril typescript defs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Comment by mrtracy** [comment]
LGTM

---

Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/ts/models/metrics.ts, line 245 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-K94CUEwhrsy0Eb6yphb:-K9YUrxIXhZYRPBkkX5C:1511801362) ([raw file](https://github.com/cockroachdb/cockroach/blob/681382ab1708cc98cf1053e26be5d61fd33fef23/ui/ts/models/metrics.ts#L245)):*
I'm okay with punting this to later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863#-:-K9YVVz5x-iPByf5sL5Q:676834233)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3863)*

**Pull request merged**
