### PR TITLE
storage: require ranges to be collocated during merge

### PR DESCRIPTION
**Pull request by benesch**
Not requiring collocation during a merge admits the following problem.
Suppose you have three contiguous ranges A, B, and C, that are
distributed across four stores, S1 - S4, like so:

     S1       S2       S3       S4
    A B C    A B C    B C      A C

First, B and C are merged to form BC:

     S1       S2       S3       S4
    A BC     A BC     BC       A C

Note how S4 retains its replica of C. This replica will eventually be
garbage collected, but not immediately. Now, suppose A and BC are merged
to form ABC:

     S1       S2       S3       S4
    ABC      ABC      BC       ????

This merge will apply cleanly on S1 and S2, but it will explode on S4.
The replica of A on S4 cannot expand to subsume BC, because the store
has an intercepting replica, C.

In this particular case, it would be safe to force garbage collection of
C while applying the merge. But this is not possible in general! If S4
is lagging behind, the intersecting replica might be a snapshot from a
future *split* of the range ABC. In that case the intersecting replica
would need to be rebalanced away before we could apply the merge. The
idea of garbage collecting an intersecting range when applying a Raft
command is scary but perhaps workable, but the idea of rebalancing away
an intersecting range beneath Raft is laughable.

Instead, to solve this problem, we can require that ranges are
collocated before and during the merge transaction. Ensuring that a
replica of the right-hand range is present on the store when the merge
is applied neatly guarantees that there can be no replicas that
intersect the merged range.

### CODE REVIEW

**Comment by benesch** [comment]
This is looking pretty good on clearrange so far. I'll check back in tomorrow morning.

image

The unavailable ranges were caused by a race in gossip that's unrelated to the merge code. I couldn't get the node back online though; there's a bug in restarting nodes that have a committed but unapplied merge that I haven't tracked down yet.

**Review by tbg — DISMISSED** [review]
Doesn't seem that your clearrange cluster's admin ui is loading, so something probably exploded. :boom: 
Mostly looks good, with a few comments.

> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-:-LIk8u-Y6u086oup4-y5:bfh2vwd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/clearrange.go, line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk8c8ADbkELTZxpM9q:-LIk8c8B5pE_Y49OWT4q:b-4lq5kl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1118b4881220b983dcfce1e6682a72659943fd3/pkg/cmd/roachtest/clearrange.go#L124)):*
> ```Go
> 				// TODO(benesch): verify that every last range in the table has been
> 				// merged away. For now, just exercising the merge code is a good start.
> 				return nil
> ```

Isn't this as easy as `select count(*) from crdb_internal.ranges where "table" = 'bank' and "database" = 'bank'`?
___
*[pkg/storage/replica_gc_queue.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7JmoDXeI-l9s79n1:-LIk7JmoDXeI-l9s79n2:bdalzcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/replica_gc_queue.go#L243)):*
> ```Go
> 		// away. But currentMember is true, so we are still a member of the
> 		// subsuming range. The subsuming range will clean up the subsumed range
> 		// when it applies the merge trigger.
> ```

The subsuming range may never apply the command, though, if it got rebalanced away quickly, and then you'll permanently leak this keyspace. We gotta do something here
___
*[pkg/storage/store_snapshot.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7uPY3eobm_hDnrp2:-LIk7uPY3eobm_hDnrp3:bihjqdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/store_snapshot.go#L365)):*
> ```Go
> 		replDesc := (*Replica)(v).Desc()
> 		if !replDesc.EndKey.Equal(rangeDescriptor.EndKey) {
> 			return nil, errors.New("existing replica is awaiting merge")
> ```

Add here that the replica in question is going to be the subsuming one.

**Comment by benesch** [comment]
> Doesn't seem that your clearrange cluster's admin ui is loading, so something probably exploded.

A bunch more nodes failed with the concurrent map access caused by the gossip bug. 😅 Still nothing merge related!

**Review by bdarnell — COMMENTED** [review]
> Reviewed 3 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 3 files at r6, 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28071)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/keys.go, line 424 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvAI6a86gOcpV9N1os:-LIvAI6a86gOcpV9N1ot:bt531td) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/keys/keys.go#L424)):*
> ```Go
> // subsumed this range.
> func SubsumerKey(key roachpb.RKey) roachpb.Key {
> 	return MakeRangeKey(key, LocalSubsumerDescriptorSuffix, nil)
> ```

I think this wants to be a RangeID key instead of an addressable range key. If it's a regular range key, it actually appears in the middle of the combined range. 
___
*[pkg/storage/client_merge_test.go, line 1208 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvAF3zDmRKyIaBB9W3:-LIvAF3zDmRKyIaBB9W4:b-ujmrte) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/client_merge_test.go#L1208)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	t.Skip()
> ```

Don't forget this. 
___
*[pkg/storage/replica.go, line 5253 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvlrn49aZEwjoUjYBz:-LIvlrn49aZEwjoUjYC-:bw41dlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/replica.go#L5253)):*
> ```Go
> 			tmpBatch := r.store.engine.NewBatch()
> 			for _, keyRange := range rditer.MakeAllKeyRanges(&merge.RightDesc) {
> 				tmpBatch.ClearRange(keyRange.Start, keyRange.End)
> ```

Isn't this also bad for creating a lot of range tombstones? 
___
*[pkg/storage/replica_command.go, line 475 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvmkgqDzvssQDlUbYM:-LIvmkgqDzvssQDlUbYN:b-1bw3j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/replica_command.go#L475)):*
> ```Go
> 		// queue knows when it's safe to GC an orphaned replica of the deleted
> 		// range.
> 		log.Errorf(ctx, "subsumer %s", keys.SubsumerKey(roachpb.RKey(rightDesc.StartKey)))
> ```

Remove before merging.
___
*[pkg/storage/store_snapshot.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7uPY3eobm_hDnrp2:-LIvi54Y6XBXMaMBuRYz:bku0czv) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/store_snapshot.go#L365)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Add here that the replica in question is going to be the subsuming one.
</blockquote></details>

Is it always true that unequal end keys imply a pending merge here, or could it be a split too?
___
*[pkg/storage/batcheval/cmd_get_snapshot_for_merge.go, line 143 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvBpEc4wHpM8ugOroQ:-LIvBpEc4wHpM8ugOroR:b-1bw3j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/batcheval/cmd_get_snapshot_for_merge.go#L143)):*
> ```Go
> 			break
> 		}
> 		log.Errorf(ctx, "putting %s", iter.Key())
> ```

Remove before merging.

**Comment by benesch** [comment]
Oops, sorry, I forgot this branch had an open PR. I'm hoping to get this cleaned up by EOD tomorrow or Saturday. 🤦‍♂️

**Review by benesch — COMMENTED** [review]
OK, this is mostly cleaned up. One or two unresolved TODOs but definitely RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-:-LJ0yCdY-FB6bzEq4ftc:b-197mbi)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/clearrange.go, line 124 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk8c8ADbkELTZxpM9q:-LIklTw17gl35_hOOHMV:bp0idgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1118b4881220b983dcfce1e6682a72659943fd3/pkg/cmd/roachtest/clearrange.go#L124)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Isn't this as easy as `select count(*) from crdb_internal.ranges where "table" = 'bank' and "database" = 'bank'`?
</blockquote></details>

Yep, but that's going to return 20k rows to start and (I think?) scan over meta2. Seemed kind of rude to poll that. Now that I think about it, perhaps it's a good stressor.

The alternative is to watch until the num_ranges metric gets down around 100, and then start polling `crdb_internal.ranges`.
___
*[pkg/storage/client_merge_test.go, line 1208 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvAF3zDmRKyIaBB9W3:-LJ0xttOAlSKDyHd-odT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/client_merge_test.go#L1208)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't forget this. 
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 5253 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvlrn49aZEwjoUjYBz:-LJ0xwXAC0g-4UqN7N9Q:bxhq80w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/replica.go#L5253)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Isn't this also bad for creating a lot of range tombstones? 
</blockquote></details>

Yes. I'm not expecting it to last long though.
___
*[pkg/storage/replica_command.go, line 475 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvmkgqDzvssQDlUbYM:-LJ0xyU1DUKI5FAiCYHP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/replica_command.go#L475)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove before merging.
</blockquote></details>

Done.
___
*[pkg/storage/replica_gc_queue.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7JmoDXeI-l9s79n1:-LIklk-39oxJRUN2YPBP:b6kdbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/replica_gc_queue.go#L243)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The subsuming range may never apply the command, though, if it got rebalanced away quickly, and then you'll permanently leak this keyspace. We gotta do something here
</blockquote></details>

Agh. I had to rewrite all this to solve this problem. I think it's correct now though.
___
*[pkg/storage/store_snapshot.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7uPY3eobm_hDnrp2:-LJ0y6JjEGqU9EurIlP9:bf71hiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/store_snapshot.go#L365)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is it always true that unequal end keys imply a pending merge here, or could it be a split too?
</blockquote></details>

Need to think about this more.
___
*[pkg/keys/keys.go, line 424 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvAI6a86gOcpV9N1os:-LJ0y7zkB4bG1sLeHNl6:bjdk5iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/keys/keys.go#L424)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this wants to be a RangeID key instead of an addressable range key. If it's a regular range key, it actually appears in the middle of the combined range. 
</blockquote></details>

As discussed in #merges, no longer necessary.
___
*[pkg/storage/batcheval/cmd_get_snapshot_for_merge.go, line 143 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIvBpEc4wHpM8ugOroQ:-LJ0yB1s8XIaz7UtIj7a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66d134d38b83bdf56a9f7205dc89357ad75ba37/pkg/storage/batcheval/cmd_get_snapshot_for_merge.go#L143)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove before merging.
</blockquote></details>

Done.

**Review by bdarnell — APPROVED** [review]
> Reviewed 3 of 7 files at r11, 38 of 40 files at r12, 4 of 4 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28071)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/metadata3.proto, line 27 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LJEt4Y98eZR7ytV8un2:-LJEt4Y98eZR7ytV8un3:b8l0xw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/24340ae4b58cab6b3023b2622857f2306fe8ed3b/pkg/roachpb/metadata3.proto#L27)):*
> ```protobuf
> //
> // NOTE: Care must be taken when changing the encoding of this proto
> // because it is used as part of conditional put operations.
> ```

So this was moved to proto3 so that the new generation field doesn't change the encoding when it's zero? (without making it nullable and heap-allocated)
___
*[pkg/storage/below_raft_protos_test.go, line 115 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LJEtmiq3z7aN7_pOSVj:-LJEtmiq3z7aN7_pOSVk:b-xq7910) ([raw file](https://github.com/cockroachdb/cockroach/blob/24340ae4b58cab6b3023b2622857f2306fe8ed3b/pkg/storage/below_raft_protos_test.go#L115)):*
> ```Go
> 		populatedSum: 13610333037718127325,
> 	},
> 	reflect.TypeOf(&storage.Liveness{}): {
> ```

How is liveness encoded below raft? It's just for gossip, right? (In which case please add a comment about this and point out that changes to this type are not actually dangerous)

What changed in storage.Liveness anyway? I don't see any changes to that file. 
___
*[pkg/storage/client_merge_test.go, line 1063 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LJEuc9c0o73TdNdBEZQ:-LJEuc9c0o73TdNdBEZR:b5afr6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/24340ae4b58cab6b3023b2622857f2306fe8ed3b/pkg/storage/client_merge_test.go#L1063)):*
> ```Go
> 		}
> 		if _, err := store1.GetReplica(rangeID); err == nil {
> 			t.Fatalf("replica of r%d not gc'd from s1", rangeID)
> ```

Range IDs format with the `r` prefix automatically when `%s` is used.

**Review by benesch — COMMENTED** [review]
Ok, I'd like to merge this as is. It's not quite right yet, but the remaining problem involves teaching snapshots to subsume everything in their path if the end key is widened, and I'd like to do that in another PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-:-LJMiKaq8lL9x7gY8b2H:b-2dfygr)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/below_raft_protos_test.go, line 115 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LJEtmiq3z7aN7_pOSVj:-LJMhwLy8nohz4GYN_mg:b-l2euxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/24340ae4b58cab6b3023b2622857f2306fe8ed3b/pkg/storage/below_raft_protos_test.go#L115)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How is liveness encoded below raft? It's just for gossip, right? (In which case please add a comment about this and point out that changes to this type are not actually dangerous)

What changed in storage.Liveness anyway? I don't see any changes to that file. 
</blockquote></details>

The change to `storage.Liveness` was just a typo. Oops!

With the approach to the generation field that we discussed, there's now only a change to the populatedSum for RangeDescriptor. That means the empty RangeDescriptor now encodes the same way as before. :tada:
___
*[pkg/roachpb/metadata3.proto, line 27 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LJEt4Y98eZR7ytV8un2:-LJF0quUCOIkge5eUZ0l:btih660) ([raw file](https://github.com/cockroachdb/cockroach/blob/24340ae4b58cab6b3023b2622857f2306fe8ed3b/pkg/roachpb/metadata3.proto#L27)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

So this was moved to proto3 so that the new generation field doesn't change the encoding when it's zero? (without making it nullable and heap-allocated)
</blockquote></details>

Yes, exactly.
___
*[pkg/storage/store_snapshot.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28071#-LIk7uPY3eobm_hDnrp2:-LJMiE6Z4vSIJK1r2YbT:bavaluy) ([raw file](https://github.com/cockroachdb/cockroach/blob/816d7af4e5a6c7f2365d4b2e309901e87e9b528d/pkg/storage/store_snapshot.go#L365)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Need to think about this more.
</blockquote></details>

Discussed offline. We need to actually subsume ranges if we see a widened EndKey. Leaving to another PR.

**Comment by benesch** [comment]
Finally worked out the test failures here. Thanks for the reviews!

bors r=bdarnell

**Pull request merged**
