### PR TITLE
kv: handle NotLeaseHolderError in (*DistSender).RangeFeed

### PR DESCRIPTION
**Pull request by danhhz**
RangeFeeds work on followers, so they don't get NotLeaseHolderError in
the normal course of things. However, if an uninitialized replica is
contacted for a RangeFeed, it uses NotLeaseHolderError as a hint for
where a better one might be found. The error handling in
partialRangeFeed was missing this case, causing changefeeds to fail on
what should be a retryable error.

Touches #36077

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
How would I test this? Is it easy to set up an uninitialized replica?

**Comment by nvanbenschoten** [comment]
Is there a test for the corresponding logic in `Store.Send`? Maybe try removing that and seeing if anything fails. I'd imagine the tests would be similar.

I also don't have any strong argument for keeping the optimization instead of just returning a `RangeNotFoundError`. I thought you were suggesting removing optimization for normal `BatchRequests` as well in https://github.com/cockroachdb/cockroach/issues/36077#issuecomment-486307199, but if you're just talking about doing so for RangeFeed setup, I doubt that will cause any issues.

**Comment by danhhz** [comment]
I changed the RangeNotFoundError in `Store.Send` to an `errors.New` and no tests failed in pkg/storage or pkg/kv. I'm running the whole suite now just to see if something somewhere else picks it up.

I didn't realize that this was more copied from Store.Send than specifically added for RangeFeed. Given how rarely that codepath is being hit and that we don't otherwise expect NotLeaseHolderErrors to come back from RangeFeed, I'm leaning toward closing this PR and opening a replacement that returns `RangeNotFoundError` instead (only in `Store.RangeFeed`).

**Comment by danhhz** [comment]
Ha! Right after I sent that TestImportCSVStmt and TestScatterRandomizeLeases each found it by accident

```
--- FAIL: TestImportCSVStmt (16.67s)
    --- FAIL: TestImportCSVStmt/empty-with-files (2.59s)
        import_stmt_test.go:1181: error scanning '&{0xc00a70d0e0 <nil>}': pq: foo 1
```

```
--- FAIL: TestScatterRandomizeLeases (2.13s)
    scatter_test.go:110: pq: crdb_internal.lease_holder(): message: foo 3
```

**Pull request closed without merging**
