### PR TITLE
opt: Move Catalog types into new "cat" package

### PR DESCRIPTION
**Pull request by andy-kimball**
The Catalog-related interfaces (Table, View, Column, etc.) are becoming
more and more comprehensive over time. They could eventually be used by
other components other than the optimizer. In addition, leaving them in
the opt package causes potential confusion over the Catalog types vs.
the Metadata types (TableID, ColumnID, etc). For these reasons, this
commit moves the Catalog types into their own package, which nicely
encapsulates them and emphasizes that they are not opt-specific.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Shiuld it be sql/cat sql/catalog instead of sql/opt/cat, especially if we envision non-opt uses?

**Comment by andy-kimball** [comment]
I think we should leave it as `sql/opt/cat` until we get to the point where we want to use it for non-opt purposes. The more compelling reason to move it is to reduce confusion between `Catalog` and `Metadata` related type.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 27 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33175#-:-LTxINlqDYfD4amaHVtu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
