### PR TITLE
backupccl: resume mid-key requests immediately

### PR DESCRIPTION
**Pull request by dt**
Previously if a mid-key resumption request hit an intent, it would potentially be immediately aborted and put on the back of the queue to try later, like any other backup request. This however would mean that the remaining revisions of a key would be exported later, likely flushed into a different file. This forces us to consider endkeys to inclusive, rather than exclusive, since files can flush before all of the revisions of their last key have been recorded.

Now when a request is resuming mid-key, it will be immediately retried if it hits an intent, potentially repeatedly until the deadline at which it can invoke priority is reached. Thus the remainder of the key should be exported and flushed to the same file so that the key is never split across files.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
If i'm reading the commit message correctly, there's no need to change the lock policy logic above because we're going to retry and eventually wait for the intent to clear, correct?

Were you planning to add an additional commit here to return an assertion failure in the file sink if we flush midkey? If not I can write up a 24.1 release blocker issue.

**Review by stevendanna — APPROVED** [review]
Just confirming: This prevent SST's that end at an inclusive key because in the sst_file_sink the only time we will flush an SST that is mid-key is when we do an "out of order" flush.  Since we use 1 file sink per export worker, an out of order flush can never happen in the middle of exporting a given key _unless_ we caused it to by pushing a resume span to the end of the queue.

**Comment by dt** [comment]
> Just confirming: This prevent SST's that end at an inclusive key 

Yep. I added an assertion to the sink as well as suggested by @msbutler checking this property.

**Comment by dt** [comment]
>  there's no need to change the lock policy logic above

Correct: if we hit an intent while mid-key, we'll just re-attempt using the same lock policy and priority and pre-send delay as any other request we take off the queue would use. The only difference is we'll be sending the same req instead of putting it on the back of the queue and getting a different one, so e.g. if we are early in the backup we might spend time in the pre-send wait that previously we'd have spent sending other requests. But we have many workers and are only blocking one, and  only under we get to invoke priority (which, if the backup is backdated, could be immediately)

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
