### PR TITLE
roachtest: roachprod: add test name and run id vm labels for metrics

### LINKED ISSUE #98658: roachtest: name clusters after running test
**Is your feature request related to a problem? Please describe.**

The clusters get scraped by our internal Prom/Grafana instance, so it's helpful if the cluster name "means something".

**Describe the solution you'd like**

Switch from `$USER-1678829488-01-n10cpu8` to something like`$USER-nameoftestbutsanitizedandshortenedifnecessary-YYMMDD-nonce`

One problem with this approach is that we'd have to rethink cluster reuse in roachtest; it would be confusing if a cluster for test A were to be reused by test B. It's unclear if reuse is something we need to keep. (I'm uneasy about cross-pollution between tests because we increasingly do random systemd-run stuff that `roachprod wipe` won't clear up).

**Describe alternatives you've considered**

We could also try to export the name of the running test as a label. But I'm not sure how feasible this is.

**Additional context**

[Slack (internal)](https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1678844786969369?thread_ts=1678841298.001839&cid=C023S0V4YEB)

Jira issue: CRDB-25424

### PR DESCRIPTION
**Pull request by smg260**
These 2 commits add labels to clusters running roachtests, so that metrics can be better filtered in various dashboards. 

1. Adds `test_name` label to each cluster, and removes the label at the end of the test. Thus, each cluster would have this label updated for each test that it runs during a particular roachtest invocation. The test name will be simplified to conform to cloud labelling rules `[a-zA-Z-]`

2. Adds `test_run_id` label to each VM, *once*, for the duration of the run. Thus, each cluster would have this label added once at the beginning of a roachtest run (which would include multiple tests), and removed only after deregistration at the end.
\
In TeamCity this would take the form `<TC_USER>-<TC_BUILD_ID>`, and run locally `<USER>-<UNIX_TS>`

These 2 labels combined will allow it easy for a user to find metrics for a particular run of roachtest. (e.g. a specific GCE nightly)

Here is a [copy of an existing dashboard](https://grafana.testeng.crdb.io/d/qdkBruq4k/crdb-console-runtime-by-test?orgId=1&from=now-3h&to=now), modified to utilise the new labels.

Epic: None
Fixes: #98658
Release note: None

### CODE REVIEW

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107965)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEV4IQ1meV9zk-2b34:-NbEV4IQ1meV9zk-2b35:b4uiqmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/cluster.go#L620)):*
> ```Go
> 	r.mu.clusters[c.name] = c
> 	if err := c.addLabels(map[string]string{
> 		"test_run_id": runId,
> ```

Can this use the `VmLabelTestRunId` const specified in `test_runner.go`?
___
*[`pkg/cmd/roachtest/cluster.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEVO1y5Ko0wg_S_M5g:-NbEVO1y5Ko0wg_S_M5h:b-l5sevt) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/cluster.go#L635)):*
> ```Go
> 		return false
> 	}
> 	if err := c.removeLabels([]string{"test_run_id"}); err != nil && c.l != nil {
> ```

Dup: Can this use the `VmLabelTestRunId` const specified in `test_runner.go`?
___
*[`pkg/cmd/roachtest/test_runner.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEV_iX7L6QUUFEw8FM:-NbEV_iX7L6QUUFEw8FN:b52pjv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/test_runner.go#L81)):*
> ```Go
> 
> // VmLabelTestRunId is the label used to identify the test run id in the VM metadata
> const VmLabelTestRunId string = "test_run_id"
> ```

Naming nit, around initialisms: `VMLabelTestRunID` (https://google.github.io/styleguide/go/decisions.html#initialisms)
Spotted a few others in the PR: `runId`, `uniqueId`, `generateRunId`
___
*[`pkg/roachprod/vm/aws/aws.go` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbE_WqY7Jju0FF6YAON:-NbE_WqY7Jju0FF6YAOO:b-15nizg) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/roachprod/vm/aws/aws.go#L453)):*
> ```Go
> 	for region, list := range byRegion {
> 		// Capture loop vars here
> 		regionArgs := append(args, "--region", region)
> ```

Append can possibly mutate the `args` backing array so might be best to make a copy to be on the safe side (https://go.dev/play/p/N7SX5L5Ysod).

**Review by smg260 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107965)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEV4IQ1meV9zk-2b34:-NbU3taQCO8NK0g3yFKb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/cluster.go#L620)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Can this use the `VmLabelTestRunId` const specified in `test_runner.go`?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEVO1y5Ko0wg_S_M5g:-NbU3u7JDZN0iv5uF963:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/cluster.go#L635)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Dup: Can this use the `VmLabelTestRunId` const specified in `test_runner.go`?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/test_runner.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbEV_iX7L6QUUFEw8FM:-NbU4k0IAr_FK-1p5L1C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/cmd/roachtest/test_runner.go#L81)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Naming nit, around initialisms: `VMLabelTestRunID` (https://google.github.io/styleguide/go/decisions.html#initialisms)
Spotted a few others in the PR: `runId`, `uniqueId`, `generateRunId`
</blockquote></details>

Done.
___
*[`pkg/roachprod/vm/aws/aws.go` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-NbE_WqY7Jju0FF6YAON:-NbU4l8p7uyPM6Z9DX5l:b-uxrm2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/93b04f3c804c561ffebacd0ef9361a032a1b2376/pkg/roachprod/vm/aws/aws.go#L453)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Append can possibly mutate the `args` backing array so might be best to make a copy to be on the safe side (https://go.dev/play/p/N7SX5L5Ysod).
</blockquote></details>

Ugh thanks for this one.

**Review by herkolategan — APPROVED** [review]
Excellent!
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107965#-:-Nbn-QcG2s5WbtoJHhfF:b-g2sq62)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by smg260** [comment]
TFTR!

bors r=herkolategan

**Comment by smg260** [comment]
blathers backport 23.1

**Pull request merged**
