### PR TITLE
*: Bump dependencies in order to pull in etcd memory leak fix

### LINKED ISSUE #14776: restore: OOM with TPC-H scale factor 10 data
build: 725ea82
config: 6-node cluster on 6 Azure [Standard_D3 VMs](https://azure.microsoft.com/en-us/blog/new-d-series-virtual-machine-sizes/) (proposer-evaluated KV enabled, as required by RESTORE)

What I did (I gave the full URL to @danhhz):

```
RESTORE tpch.* FROM 'azure://[redacted]/scalefactor-10';
```

It looks like the store got to ~24 GB, which is around where it should be. However, the OOM killer killed the `cockroach` instance on the node from which I initiated the RESTORE:

```
[1041637.873658] Out of memory: Kill process 42101 (cockroach) score 961 or sacrifice child
[1041637.879925] Killed process 42101 (cockroach) total-vm:24957948kB, anon-rss:13761140kB, file-rss:0kB
```

Here are the last runtime stats before the kill:
```
I170410 22:35:07.800302 107 server/status/runtime.go:227  [n1] runtime stats: 12 GiB RSS, 1320 goroutines, 7.7 GiB/1.5 GiB/9.6 GiB GO alloc/idle/total, 2.4 GiB/2.7 GiB CGO alloc/total, 42113.69cgo/sec, 2.53/0.23 %(u/s)time, 0.00 %gc (0x)
```

This seems like a *lot* of memory allocated by Go. All the other nodes have ~3-4 GiB RSS, which seems fine.

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #14776 

Alternative to the confusion in #15041 that manually bumps only etcd.

### CODE REVIEW

**Comment by danhhz** [comment]
lgtm

**Comment by dt** [comment]
something is fishy here -- no change in glide.lock ?

**Comment by a-robinson** [comment]
Yeah, because I ran `glide update` and then reverted everything other than the etcd-related changes. Everything builds and passes tests locally, but is that no bueno?

**Comment by dt** [comment]
a manual bump would be editing versions in `glide.yaml`/`glide.lock`, then running `glide install` to materialize the (edited) resolution in the lock file into a `vendor` tree. Our CI will enforce that `vendor` tree is re-derivable from the lock file.

**Comment by a-robinson** [comment]
Closing since `glide cc` fixed #15041

**Pull request closed without merging**
