### PR TITLE
sql: add more check constraint schema change tests

### PR DESCRIPTION
**Pull request by thoszhang**
Added more tests related to adding check constraints.

Release note: None

### CODE REVIEW

**Review by vivekmenezes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35815#-:-LaD_QHzAp5n5N54ZRTY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @vivekmenezes)

**Comment by lucy-zhang** [comment]
I updated an error string that was changed in the last few days.

**Comment by knz** [comment]
nice!

this may want a backport too :)

**Pull request merged**
