### PR TITLE
sql: avoid detour though []byte when passing Session to exec

### PR DESCRIPTION
**Pull request by dt**
```
name                 old time/op    new time/op    delta
Select1_Cockroach-8    65.7µs ± 4%    62.2µs ± 1%  -5.30%  (p=0.000 n=10+10)
Insert1_Cockroach-8     484µs ± 4%     466µs ± 1%  -3.79%   (p=0.000 n=10+9)
Update1_Cockroach-8    1.13ms ± 5%    1.11ms ± 1%  -2.38%  (p=0.035 n=10+10)
Delete1_Cockroach-8    1.53ms ± 2%    1.49ms ± 2%  -2.17%  (p=0.000 n=10+10)
Scan1_Cockroach-8       263µs ± 3%     256µs ± 1%  -2.72%  (p=0.000 n=10+10)

name                 old alloc/op   new alloc/op   delta
Select1_Cockroach-8    2.16kB ± 0%    2.14kB ± 0%  -0.72%   (p=0.000 n=10+9)
Insert1_Cockroach-8    25.1kB ± 0%    25.1kB ± 0%    ~      (p=0.315 n=9+10)
Update1_Cockroach-8    42.8kB ± 0%    42.8kB ± 0%    ~     (p=0.810 n=10+10)
Delete1_Cockroach-8    40.4kB ± 0%    40.3kB ± 0%  -0.15%   (p=0.003 n=9+10)
Scan1_Cockroach-8      10.7kB ± 0%    10.7kB ± 0%    ~     (p=0.280 n=10+10)

name                 old allocs/op  new allocs/op  delta
Select1_Cockroach-8      49.0 ± 0%      48.0 ± 0%  -2.04%  (p=0.000 n=10+10)
Insert1_Cockroach-8       358 ± 0%       357 ± 0%  -0.28%  (p=0.000 n=10+10)
Update1_Cockroach-8       798 ± 0%       797 ± 0%  -0.13%  (p=0.000 n=10+10)
Delete1_Cockroach-8       738 ± 0%       738 ± 0%  -0.11%  (p=0.009 n=10+10)
Scan1_Cockroach-8         210 ± 0%       209 ± 0%  -0.62%   (p=0.000 n=10+8)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4289)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/server.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-KABb3TkdRlLt1-uew7y:-KABb3TkdRlLt1-uew7z:-1191123864) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be1e6cb624d16bc86a7ae4c21b482ba345c5d6/sql/server.go#L139)):*
`return protoFromResponse(reply)`?

---

*[sql/server.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-KABb6EMs23vwuIQ2TKD:-KABb6EMs23vwuIQ2TKE:-1623933175) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be1e6cb624d16bc86a7ae4c21b482ba345c5d6/sql/server.go#L144)):*
remove this newline

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-:-KABbFk4bWP_1NLrTtfr:676834233)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/server.go, line 139 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-KABb3TkdRlLt1-uew7y:-KABc0oCm-ZKOSVAgivL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be1e6cb624d16bc86a7ae4c21b482ba345c5d6/sql/server.go#L139)):*
Done.

---

*[sql/server.go, line 144 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-KABb6EMs23vwuIQ2TKD:-KABc0ZRg3cJvWKCi6BA:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/39be1e6cb624d16bc86a7ae4c21b482ba345c5d6/sql/server.go#L144)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289)*

**Comment by nvanbenschoten** [comment]
Nice! :lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4289#-:-KABmYV2fIaU3ccjPNA6:-1348913009)*

**Pull request merged**
