### PR TITLE
span: use KeyColumns in span.Builder

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### span: minor span.Builder cleanup

Release note: None

#### rowenc: move null PK check

EncodeIndexKey has a special NULL check for primary indexes. This
check is a bit out of left field in this code, which is meant to be
more generic.

This commit moves this check in the higher-level primary index
encoding routines and simplifies some related code. We no longer try
to plumb the null ColumnID, instead we figure it out when generating
the error.

Release note: None

#### span: use KeyColumns in span.Builder

This commit refactors span.Builder to use
`IndexFetchSpec_KeyColumn`s instead of descriptors. This is in
preparation for replacing the JoinReader descriptor with an
`IndexFetchSpec`.

Release note: None

#### span: don't allocate span.Builder

This commit replaces `MakeBuilder` (which allocates a `*Builder`) with
an `Init` method.  This should be more efficient and also simplifies
the code by removing the pool.

Release: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 7 of 7 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/rowexec/inverted_joiner.go, line 457 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ3ZipCX-fLpck_YcT:-MwQ3Ziq-RBTwd0W4EkO:bo9ay3) ([raw file](https://github.com/cockroachdb/cockroach/blob/126d70b4f147789fd280eae4fad7e26a58375f98/pkg/sql/rowexec/inverted_joiner.go#L457)):*
> ```Go
> 					ij.indexRow[prefixIdx] = row[colIdx]
> 				}
> 				// TODO(mgartner): MakeKeyFromEncDatumsDeprecated will allocate and grow a
> ```

nit: I don't see `MakeKeyFromEncDatumsDeprecated` anywhere.
___
*[pkg/sql/span/span_builder.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ1OBp1VwNheAVqlsX:-MwQ1OBp1VwNheAVqlsY:b-590p8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2bc85bd9364fbb49170cefa21852208e1149a99/pkg/sql/span/span_builder.go#L83)):*
> ```Go
> }
> 
> // SpanFromEncDatums encodes a span with prefixLen constraint columns from the
> ```

nit: prefixLen is no more.
___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwQ4sj41VLLMKzHJatt:b-ibu7f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
> ```Go
> 	// We need to advance the end key if it is inclusive or the index is
> 	// inverted.
> 	if cs.EndBoundary() == constraint.IncludeBoundary || s.index.GetType() == descpb.IndexDescriptor_INVERTED {
> ```

This change seems like it doesn't belong to the third commit. It'd be good to extra it into a separate commit (maybe separate PR) with the corresponding reasoning, and probably get a sign-off on this from someone else.
___
*[pkg/sql/span/span_builder.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4NVu4AdrEee9RhjL:-MwQ4NVu4AdrEee9RhjM:b-bif8ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/126d70b4f147789fd280eae4fad7e26a58375f98/pkg/sql/span/span_builder.go#L98)):*
> ```Go
> 	}
> 
> 	makeKeyFromRow := func(r rowenc.EncDatumRow) (k roachpb.Key, cn bool, e error) {
> ```

nit: this function seems to not be very useful anymore, maybe delete it entirely?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwRdaBK4JYNqloBFf8_:b-njfvg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This change seems like it doesn't belong to the third commit. It'd be good to extra it into a separate commit (maybe separate PR) with the corresponding reasoning, and probably get a sign-off on this from someone else.
</blockquote></details>

I was going to ask you about this check, which seems wrong/unnecessary. I believe you added it in https://github.com/cockroachdb/cockroach/commit/55bb02f999679f200ed962b05c934e7974d2d4f4  Do you remember why?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwSEdeQ1o9AKQFN41AW:b-jilaan) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I was going to ask you about this check, which seems wrong/unnecessary. I believe you added it in https://github.com/cockroachdb/cockroach/commit/55bb02f999679f200ed962b05c934e7974d2d4f4  Do you remember why?
</blockquote></details>

The logic was already present in `AdjustEndKeyForInterleave` which was removed in that commit, so I only inlined what was relevant.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwSXCPl7_hxkUf-IYF4:bhc5xr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The logic was already present in `AdjustEndKeyForInterleave` which was removed in that commit, so I only inlined what was relevant.
</blockquote></details>

Ah, I see. It looks like an early return path because inverted index can't be interleaved, but it failed to account for the `inclusive` flag. It looks like it has been there for a long time (since https://github.com/knz/cockroach/commit/21c2b8060f074c2d7e2ed70d37f083b466d1734f), before we could have exclusive boundaries for inverted indexes. I'll open up a separate PR to remove.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-:-MwT-gi40_9JWzyShGBD:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwT-RtU5JR_Ohq8tzR2:b-u9pnyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, I see. It looks like an early return path because inverted index can't be interleaved, but it failed to account for the `inclusive` flag. It looks like it has been there for a long time (since https://github.com/knz/cockroach/commit/21c2b8060f074c2d7e2ed70d37f083b466d1734f), before we could have exclusive boundaries for inverted indexes. I'll open up a separate PR to remove.
</blockquote></details>

Will rebase on top of #76865 when that merges.
___
*[pkg/sql/span/span_builder.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4NVu4AdrEee9RhjL:-MwT-JB93md9ZH_YcWI8:b-uvfgjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/126d70b4f147789fd280eae4fad7e26a58375f98/pkg/sql/span/span_builder.go#L98)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this function seems to not be very useful anymore, maybe delete it entirely?
</blockquote></details>

It makes the four callsites less cluttered. I left it (but I did remove the unnamed return).

**Review by RaduBerinde — COMMENTED** [review]
RFAL (the last commit is new)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-:-MwXrGYB1Pi6hmS3RHJ0:b-ouh4aj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/span/span_builder.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-MwQ4sj41VLLMKzHJats:-MwXrCwM4ZMjJKxLzhho:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a832aa74c7400c3929b8043e77a90d3f89c22e59/pkg/sql/span/span_builder.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Will rebase on top of #76865 when that merges.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r5, 2 of 2 files at r6, 7 of 7 files at r7, 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76836#-:-MwXthxKEWAOeg6Mj4Jv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
