### PR TITLE
release-21.1: sql: unify crdb_internal.invalid_objects contents with doctor

### LINKED ISSUE #55219: Share the code between implementation of doctor tool and `crdb_internal.invalid_objects`
**Describe the problem**

Recently we have introduced two tools for detecting sql internal data inconsistencies: [`cockroach debug doctor`](https://github.com/cockroachdb/cockroach/pull/52622) and [`crdb_internal.invalid_objects`](https://github.com/cockroachdb/cockroach/pull/54017). This is a meta-issue that describes future ideas for improving these tools and more specifically how to share code between them.

***Background***

The doctor tool performs consistency checks on the client side (either reading from a live cluster or a debug zip). This is handy for fast development and deployment of new checks and for supporting old cockroach releases. Its main drawback is that it is cumbersome to use for internal sever-side checks or in tests or logic tests.

The internal table so far detects invalid objects only via the descriptor `Validate` function. The table is very useful for checking the consistency of internal objects using a sql expression and these checks can easily be embedded in tests. The table is also automatically included in debug zips which means that as old releases are phased out it will duplicate most of the doctor tool checks.

***Future plans***

The main idea is that new checks will be first implemented and perfected via the doctor tool and eventually will find their way in the `crdb_internal.invalid_objects` table or other internal tables - one can imagine a similar table for troublesome jobs.

To that end it is important to share as much error checking code between the two tools. Currently only the implementation of table validation is shared.

***Proposals***

* [x] 1. Develop interface similar to `catalog.DescGetter` for querying the state of the namespace mapping.

* We should also consider adding some cheap namespace checks to descriptor validation.

* [x] 2. Refactor function `doctor.ExamineDescriptors` to use descriptor and namespace getters instead of the raw contents of the descriptor and namespace tables. 
 
* This will require adding ability to iterate over all descriptors in `DescGetter`.

*  [x] 3. Add namespace invalid objects to `crdb_internal.invalid_objects` that are currently only detected in `doctor.ExamineDescriptors`.

* Descriptors ids pointed to in the namespace map that no longer exist.
* Draining names entries in the descriptor table.

* [x] 4. Add descriptor ids that are pointed to from jobs but no longer exist to `crdb_internal.invalid_objects`.
* This check is currently implemented only in `doctor.ExamineJobs`.

### LINKED ISSUE #55978: doctor: detect orphaned schema change jobs
**Is your feature request related to a problem? Please describe.**

The doctor tool should be able to look at the jobs in `MutationJobIDs` and determine if any of them are in a terminal state.

### PR DESCRIPTION
**Pull request by postamar**
Backport 1/1 commits from #62803.

/cc @cockroachdb/release

---

    sql: unify crdb_internal.invalid_objects contents with doctor
    
    Previously, this table would only contain one validation error per
    object (i.e. table or type descriptor). Furthermore it would not contain
    any namespace or job validation errors for these descriptors.
    
    This patch addresses these shortcomings to make this table contain the
    same data that doctor would output for descriptor checks. Furthermore
    this patch expands the check suite with checks for:
    - jobs referenced in descriptors, to detect orphaned schema change jobs,
    - descriptors referenced in jobs.
    
    Fixes #55219.
    Fixes #55978.
    
    Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This change should be backported at some point: it's low-risk and enriches the `crdb_internal. invalid_objects` table considerably.

**Review by ajwerner — COMMENTED** [review]
This doesn’t change the validation we do during runtime, right?

Assuming not, I think given where we are in the cycle this should wait for 21.1.1 to merge. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64026#-:-MYr55Xy8k7pAFu8JZQL:brtot7s)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by postamar** [comment]
Correct, understood and agreed.

**Comment by postamar** [comment]
Rebased on fresh release-21.1 branch. Ready for review.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 10 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64026#-:-M_fyWsjAISp1bWyNknk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Pull request merged**
