### PR TITLE
changefeedccl: update changefeed.sink_io_workers description

### LINKED ISSUE #127362: Update the `changefeed.sink_io_workers` cluster setting description for sinks
Currently, the `changefeed.sink_io_workers` description on [cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings#setting-changefeed-sink-io-workers) mentions this setting only affects webhook sinks:

> the number of workers used by changefeeds when sending requests to the sink (currently webhook only): <0 disables, 0 assigns a reasonable default, >0 assigns the setting value

This description pulls from the eng/`cockroach` repo. We should update to add Pub/Sub and (possibly) v2 Kafka.

@asg0451 pointed out this discrepancy while [reviewing PR for a docs update](https://github.com/cockroachdb/docs/pull/18733/files) that included this cluster setting.

Jira issue: CRDB-40414

Epic CRDB-41784

### PR DESCRIPTION
**Pull request by rharding6373**
Include pubsub and kafka v2 in supported sinks.

Epic: CRDB-41784
Fixes: #127362

Release note (enterprise change): Updates the cluster setting `changefeed.sink_io_workers` with all the sinks that support the setting.

### CODE REVIEW

**Review by wenyihu6 — APPROVED** [review]
Do we want to mention about they are enabled in version 2 of the sinks?

**Comment by rharding6373** [comment]
> Do we want to mention about they are enabled in version 2 of the sinks?

I only did for kafka since it's recent, but you're right it's technically v2 for all of them. What do you think about "(currently the batching versions of webhook, pubsub, and kafka sinks that are enabled by changefeed.new_<sink>_enabled only)" instead? We've been trying to avoid "v2" in public-facing docs.

**Review by wenyihu6 — APPROVED** [review]
LGTM mod CI failure.

**Comment by rharding6373** [comment]
TFTR!

bors r=wenyihu6

**Pull request merged**
