### PR TITLE
client: add a simple test for Txn.ReverseScan

### PR DESCRIPTION
**Pull request by prideloki**
https://github.com/cockroachdb/cockroach/issues/5599 add a simple test for Txn.ReverseScan

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6842)

### CODE REVIEW

**Comment by petermattis** [comment]
@prideloki Thanks for adding this.

If the commit message contains the line "Fixes #5599", then the referenced issue will be closed when this PR is merged.

<details><summary><i>Previously, prideloki (Thanakom sangnetra) wrote…</i></summary>
> #### client: add a simple test for Txn\.ReverseScan
> 
> https://github.com/cockroachdb/cockroach/issues/5599 add a simple test for Txn.ReverseScan
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[client/client_test.go, line 826 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIStTObiHqtzve7dbwJ:-KIStTObiHqtzve7dbwK:-1582800541) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L826)):*
> ```Go
> 
> 	err := db.Txn(func(txn *client.Txn) error {
> 		// Try reverse scans for all keys
> ```

nit: Add punctuation (a period) to the end of all of these comments.

---

*[client/client_test.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIT6fWTFOBPBtB0ZcUM:-KIT6fWTFOBPBtB0ZcUN:-597965082) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L832)):*
> ```Go
> 				return err
> 			}
> 			client.CheckKVs(t, rows,
> ```

I realize this isn't a problem in this PR, but the `client.CheckKVs` utility function should really live in `client_test.go` and be named `checkKVs` (i.e. unexported).

---

*[client/client_test.go, line 837 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIStXJ9ExZnAOXvrAJW:-KIStXJ9ExZnAOXvrAJX:-903660486) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L837)):*
> ```Go
> 		}
> 
> 		// Try reverse scans for a half of the keys
> ```

nit: `s/for a half/for half/g`

---

*[client/client_test.go, line 866 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIStcaZqkmne7ADLrhu:-KIStcaZqkmne7ADLrhv:1282060709) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L866)):*
> ```Go
> 		}
> 
> 		// Try reverse scan with non-exist key
> ```

`s/non-exist/non-existent/g`

---

*[client/client_test.go, line 883 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIT6uz-jn2h_p0qu_eH:-KIT6uz-jn2h_p0qu_eI:-182320628) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L883)):*
> ```Go
> 		t.Fatal(err)
> 	}
> ```

nit: The spurious blank line should be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-:-KIStOJk4IE9fnh5amSi:-1893096386)*

**Comment by prideloki** [comment]
Review status: 0 of 25 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/client_test.go, line 832 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-KIT6fWTFOBPBtB0ZcUM:-KIT93vlQTPuek4a6yus:-1321867387) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba1f129503aab420caada868073747e0ca10befa/client/client_test.go#L832)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I realize this isn't a problem in this PR, but the `client.CheckKVs` utility function should really live in `client_test.go` and be named `checkKVs` (i.e. unexported).
</details>
okay, i will move it to `client_test.go`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842)*

**Comment by prideloki** [comment]
@petermattis it's done but there is an error in other part of the code

**Comment by petermattis** [comment]
:lgtm: What error are you referring to? The CircleCI failure? That looks unrelated to this change. I just kicked off another run.

<details><summary><i>Previously, prideloki (Thanakom sangnetra) wrote…</i></summary>
> @petermattis it's done but there is an error in other part of the code 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6842#-:-KImZodRNMpr1luFqtvq:-688234125)*

**Pull request merged**
