### PR TITLE
storage: Track and gossip number of applied commands per second in store capacity

### PR DESCRIPTION
**Pull request by a-robinson**
It's not ideal that we can't include reads here, but we want all replicas of a range to be treated the same for rebalance purposes, and only the leaseholder knows about the reads per second.

I wasn't planning on sending this out until I had finished the actual rebalancing logic, but I'm curious if there are strong opinions on how we plumb the per-range size/qps percentile values for use in rebalancing logic. I've written up a version that accumulates them locally, but that means that the node making rebalancing decisions only has its own store's percentiles to go by, which makes decisions different depending on who makes them (which is not great). Because of that, I want to also add a few select percentile values into the store's Capacity proto that gets gossiped so that we'll have info on all stores' distributions of range size/qps. It'd be something like

```protobuf
message StoreCapacity {
  optional int64 capacity = 1 [(gogoproto.nullable) = false];
  optional int64 available = 2 [(gogoproto.nullable) = false];
  optional int32 range_count = 3 [(gogoproto.nullable) = false];
  optional int32 lease_count = 4 [(gogoproto.nullable) = false];
  optional double applies_per_second = 5 [(gogoproto.nullable) = false];
  optional map<int32, int64> bytesPerRangePercentiles = 6 [(gogoproto.nullable) = false];
  optional map<int32, double> appliesPerRangePercentiles = 7 [(gogoproto.nullable) = false];
}
```

Each map would have a few select entries, something like 10%, 25%, 50%, 75%, 90%. Using a map for this is a bit awkward, but I don't know that a set of repeated key-value pairs is really any better, and hard-coded values feels even grosser. Opinions very welcome.

See https://github.com/cockroachdb/cockroach/issues/15988 / https://github.com/cockroachdb/cockroach/issues/12996 / https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/rebalancing_for_1_1.md for context.

### CODE REVIEW

**Comment by tschottdorf** [comment]
No review, just quick comment:

> It's not ideal that we can't include reads here, but we want all replicas of a range to be treated the same for rebalance purposes, and only the leaseholder knows about the reads per second.

Not suggesting we do that now, but https://github.com/cockroachdb/cockroach/issues/7611 would address that and, if we serve reads from followers as discussed in #16593, these stats could piggyback on the renewals.

**Comment by a-robinson** [comment]
Alright, finished actually writing the comment :)

**Comment by a-robinson** [comment]
> Not suggesting we do that now, but #7611 would address that and, if we serve reads from followers as discussed in #16593, these stats could piggyback on the renewals.

Ah, that's interesting. Thanks for the pointer.

**Comment by BramGruneir** [comment]
> Each map would have a few select entries, something like 10%, 25%, 50%, 75%, 90%. Using a map for this is a bit awkward, but I don't know that a set of repeated key-value pairs is really any better, and hard-coded values feels even grosser. Opinions very welcome.

Yeah.  I don't think there's a great solution here.  I don't like repeated keyValue pairs, you're right, the map is better than that.  But perhaps hard coded values (maybe in a sub message), it will achieve the same clunkiness as the map, but it would allow for easier deprecation/augmentation without having to do a lookup each time.   This proto is used everywhere, so we're going to have to ensure that any change is easily forward/backward compatible, I think the map makes that a little bit tricker, but I may be mistaken.

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 4170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDKG5uSNZ5cWI_6B1F:-KnDKG5uSNZ5cWI_6B1G:bln40mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica.go#L4170)):*
> ```Go
> 		log.Fatalf(ctx, "raft command index is <= 0")
> 	}
> 	r.applyStats.record(0)
> ```

So this doesn't take into account the size of the write.  Just that there is a write.  Perhaps count the number of keys written?  Or the number or bytes written?  Or both?  I'm not sure exactly what will be more useful.

Also, this will lock and unlock the replica stats mutex, is there way to not add a new lock to the critical path? 

Does this need to happen before the write occurs, how about during cleanup after the the write perhaps?  Or in a deferred goroutine... I'm just musing here, but there must be some best practice here.

---

*[pkg/storage/replica_stats.go, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDJ8Jvzj0KAeMtqt6J:-KnDJ8Jwr1xxlg1utI5_:b-ay0zns) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica_stats.go#L73)):*
> ```Go
> func (rs *replicaStats) record(nodeID roachpb.NodeID) {
> 	var locality string
> 	if rs.getNodeLocality != nil {
> ```

In what cases would getNodeLocality be nil?

---

*[pkg/storage/store.go, line 2403 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDJNkaKluFSM7Q_UZt:-KnDJNkaKluFSM7Q_UZu:b-tvj5y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae987c2b5435c460851a2d93d807a447336799c/pkg/storage/store.go#L2403)):*
> ```Go
> 	newStoreReplicaVisitor(s).Visit(func(r *Replica) bool {
> 		// TODO(a-robinson): This currently only includes writes, not reads served
> 		// by leaseholders. Should we take those into account too?
> ```

Why not one stat for reads, one for writes?  I can see there being potentially different use cases for both.  Perhaps we find that reads are helped by splits, but writes are helped by moving the replicas closer.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-:-KnDLQqvAfpZXpSTqDDl:btd67f)*

**Comment by a-robinson** [comment]
Thanks for the feedback!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 4170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDKG5uSNZ5cWI_6B1F:-KnGWldorcekpESfL-3O:bi7waoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica.go#L4170)):*
> So this doesn't take into account the size of the write. Just that there is a write. Perhaps count the number of keys written? Or the number or bytes written? Or both? I'm not sure exactly what will be more useful.

That's a good point. The raft command size is readily available and an appealing choice. @petermattis do you have a sense of whether counting queries, bytes, or keys would be more valuable here in terms of which affects performance the most?

> Also, this will lock and unlock the replica stats mutex, is there way to not add a new lock to the critical path?
> 
> Does this need to happen before the write occurs, how about during cleanup after the the write perhaps? Or in a deferred goroutine... I'm just musing here, but there must be some best practice here.

I'd probably be more worried about the allocations involved in creating a new goroutine for every apply if we were to try deferring this than I am about the overhead of locking here. And if we were to wrap it in a `RunAsyncTask`, we'd be eating a mutex lock/unlock inside the `Stopper` anyways.

---

*[pkg/storage/replica_stats.go, line 73 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDJ8Jvzj0KAeMtqt6J:-KnGTEiYMiMwKyhPWSec:b-mukq4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica_stats.go#L73)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

In what cases would getNodeLocality be nil?
</blockquote></details>

It's nil in the new case of `applyStats`. Note that when we create it we pass nil as the second argument, because we don't have origin node information for the request in the downstream-of-raft code.

---

*[pkg/storage/store.go, line 2403 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDJNkaKluFSM7Q_UZt:-KnGTmGY2bwIoHfPoOsx:b-j4wacx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ae987c2b5435c460851a2d93d807a447336799c/pkg/storage/store.go#L2403)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not one stat for reads, one for writes?  I can see there being potentially different use cases for both.  Perhaps we find that reads are helped by splits, but writes are helped by moving the replicas closer.  
</blockquote></details>

That's a good point, for sure. I don't know that we should make the change until we have a specific use for the reads-only stat, though. Right now the leaseholder-specific stat is useful for lease rebalancing (since moving the lease closer reduces latency on both reads and writes) and the write-only stat is (or will soon be) useful for replica rebalancing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-:-KnGSuT4vgYiJlxr4PTh:b-cfj7zw)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/roachpb/metadata.proto, line 101 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnGbLirrXoVL7wSXuWL:-KnGbLirrXoVL7wSXuWM:b4kokbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f546bb2b35cdfa1a996581ca5d7f204910cc/pkg/roachpb/metadata.proto#L101)):*
> ```protobuf
>   optional int32 range_count = 3 [(gogoproto.nullable) = false];
>   optional int32 lease_count = 4 [(gogoproto.nullable) = false];
>   optional double applies_per_second = 5 [(gogoproto.nullable) = false];
> ```

Can you add a comment detailing over what time period this metric is tracked?

---

*[pkg/storage/replica.go, line 4170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDKG5uSNZ5cWI_6B1F:-KnG_Y8jsH1ptXTyaByG:b-jf6nbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica.go#L4170)):*
> The raft command size is readily available and an appealing choice. @petermattis do you have a sense of whether counting queries, bytes, or keys would be more valuable here in terms of which affects performance the most?

My first guess would be number of keys. Though a really large value is going to be interesting too.

> I'd probably be more worried about the allocations involved in creating a new goroutine for every apply if we were to try deferring this than I am about the overhead of locking here. And if we were to wrap it in a RunAsyncTask, we'd be eating a mutex lock/unlock inside the Stopper anyways.

We already do lots of mutex locking/unlocking during Raft command application. I doubt the locking will show up and agree that a new goroutine would likely be worse from a performance perspective. Note that `applyRaftCommand` is called with `Replica.raftMu` held so there won't be any contention on the mutex.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-:-KnGbzPv1ViHjc0WZOD8:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 3 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/roachpb/metadata.proto, line 101 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnGbLirrXoVL7wSXuWL:-KnMB91zhppvVsByMoNs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e21f546bb2b35cdfa1a996581ca5d7f204910cc/pkg/roachpb/metadata.proto#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you add a comment detailing over what time period this metric is tracked?
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 4170 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664#-KnDKG5uSNZ5cWI_6B1F:-KnMB25XMdu2vqvzOqij:bb0encr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1617b8d5e912519a6fc69b5ed0b6b663abd2d1fe/pkg/storage/replica.go#L4170)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> The raft command size is readily available and an appealing choice. @petermattis do you have a sense of whether counting queries, bytes, or keys would be more valuable here in terms of which affects performance the most?

My first guess would be number of keys. Though a really large value is going to be interesting too.

> I'd probably be more worried about the allocations involved in creating a new goroutine for every apply if we were to try deferring this than I am about the overhead of locking here. And if we were to wrap it in a RunAsyncTask, we'd be eating a mutex lock/unlock inside the Stopper anyways.

We already do lots of mutex locking/unlocking during Raft command application. I doubt the locking will show up and agree that a new goroutine would likely be worse from a performance perspective. Note that `applyRaftCommand` is called with `Replica.raftMu` held so there won't be any contention on the mutex.
</blockquote></details>

Alright, switched from applies per second to keys written per second.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16664)*

**Pull request merged**
