### PR TITLE
storage: Use optimized SeekGE in CheckSSTConflicts

### LINKED ISSUE #66410: bulk: adaptively probe into existing data in AddSSTableRequests.checkForKeyCollisions
This is an idea that came from @andreimatei during a conversation about recent large-scale IMPORTs.

During IMPORTs, we repeatedly ingest SSTs through `AddSSTableRequests`. These requests set the `DisallowShadowing` flag to `true`, so they must check that none of the keys in their SST overlap with any of the keys in the destination range:

https://github.com/cockroachdb/cockroach/blob/9335ade9ce91ebdab1996d7c818b16df32557ac8/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L49-L57

For IMPORTs where the source is sorted similarly to the destination index, this behavior is fine because the destination keyspace is always empty so the call to `checkForKeyCollisions` is free. However, for portions of the IMPORT where the source is not sorted like the destination index, as is almost always the case for tables with secondary indexes, this repeat conflict checking on each `AddSSTableRequests` is quadratic and can dominate the cost of the IMPORT. This is especially true when the IMPORT creates high read amplification in the destination range, further slowing down the scan in `AddSSTableRequests`.

As an IMPORT continues, it would seem that the ratio of existing to new data would become larger and larger. Eventually, all `AddSSTableRequests` would begin to set their `IngestAsWrites` flag. But beyond this, the "efficiency" of each `checkForKeyCollisions` call would decrease.

It's possible that once we cross some threshold, it would be more efficient to probe into the range to check for conflicts instead of scanning the new data and the existing data in parallel using two iterators. The useful analogy here is to perform a "hash join" instead of a "merge join" once the ratio of existing to new data crosses some threshold. This optimization may be negated to some degree by the fact that we [seek each iterator](https://github.com/cockroachdb/cockroach/blob/9335ade9ce91ebdab1996d7c818b16df32557ac8/pkg/storage/mvcc.go#L3928) in `checkForKeyCollisionsGo` instead of calling next on them (a "zig-zag join", following our analogy). But what this still doesn't give us is the ability to use SST bloom filters to ignore most SSTs in the existing data. The ability to use bloom filters would be particularly important once read amplification grows.

So the proposal here is to take the ratio of `new/existing keys` and maybe the `read amplification` into account in `checkForKeyCollisions` and to switch to a probing mode once we determine that it makes sense to do so.

@adityamaru is this something we have considered?

Epic: CRDB-2556

### PR DESCRIPTION
**Pull request by itsbilal**
This nearly reverts #73514 by moving back to calling SeekGE on
the engine to skip past any empty spans on either the engine
or the SSTable. This is the more optimal approach on average,
and given optimizations in cockroachdb/pebble#1412 which this
change depends on, it also ends up performing better than
a SeekPrefixGE-driven appraoch and the pre-#73514 approach.

Improvement when running BenchmarkCheckSSTConflicts
against the pre-#73514 revision (vs. this one):

```
name                                                                      old time/op  new time/op  delta
CheckSSTConflicts/keys=1000/versions=8/sstKeys=1000/overlap=false-24      72.6µs ±11%  66.3µs ± 1%   -8.67%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=1000/overlap=true-24       12.2ms ± 1%   1.7ms ± 1%  -86.41%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=10000/overlap=false-24     69.8µs ± 2%  67.4µs ± 1%   -3.48%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=8/sstKeys=10000/overlap=true-24      13.3ms ± 3%   2.8ms ± 1%  -78.97%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=1000/overlap=false-24     75.8µs ± 3%  63.8µs ± 1%  -15.86%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=1000/overlap=true-24      13.0ms ± 1%   1.9ms ± 1%  -85.11%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=10000/overlap=false-24    69.8µs ±11%  64.6µs ± 1%   -7.45%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=1000/versions=64/sstKeys=10000/overlap=true-24     14.8ms ± 9%   3.1ms ± 2%  -79.05%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=1000/overlap=false-24     66.1µs ± 2%  63.7µs ± 1%   -3.65%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=1000/overlap=true-24      14.2ms ± 9%   1.9ms ± 1%  -86.55%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=10000/overlap=false-24    72.3µs ±10%  64.5µs ± 0%  -10.77%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=8/sstKeys=10000/overlap=true-24      122ms ± 2%    17ms ± 1%  -86.03%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=1000/overlap=false-24    69.0µs ± 9%  62.4µs ± 1%   -9.57%  (p=0.032 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=1000/overlap=true-24     14.0ms ± 1%   2.3ms ± 2%  -83.46%  (p=0.016 n=4+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=10000/overlap=false-24   69.4µs ± 9%  62.7µs ± 1%   -9.63%  (p=0.016 n=5+5)
CheckSSTConflicts/keys=10000/versions=64/sstKeys=10000/overlap=true-24     140ms ± 5%    26ms ± 1%  -81.70%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=1000/overlap=false-24    69.2µs ±10%  62.5µs ± 1%   -9.66%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=1000/overlap=true-24     15.3ms ±11%   2.3ms ± 1%  -85.21%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=10000/overlap=false-24   69.7µs ±12%  63.6µs ± 1%     ~     (p=0.095 n=5+5)
CheckSSTConflicts/keys=100000/versions=8/sstKeys=10000/overlap=true-24     148ms ± 6%    28ms ± 2%  -80.90%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=1000/overlap=false-24   67.1µs ±10%  61.1µs ± 2%   -8.93%  (p=0.016 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=1000/overlap=true-24    14.4ms ± 2%   2.5ms ± 5%  -82.45%  (p=0.016 n=4+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=10000/overlap=false-24  68.9µs ±21%  62.2µs ± 1%   -9.76%  (p=0.008 n=5+5)
CheckSSTConflicts/keys=100000/versions=64/sstKeys=10000/overlap=true-24    204ms ±14%    42ms ± 5%  -79.44%  (p=0.008 n=5+5)
```

Fixes #66410.

Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
This can't be merged until cockroachdb/pebble#1412 lands, and the vendor ref is bumped in Cockroach.

**Comment by erikgrinaker** [comment]
I ran a single TPCE import benchmark with and without this patch. For posterity, the import workload is:

```sql
CREATE TABLE trade (
    t_id          INT8 NOT NULL PRIMARY KEY,
    t_dts         TIMESTAMP NOT NULL,
    t_st_id       VARCHAR(4) NOT NULL,
    t_tt_id       VARCHAR(3) NOT NULL,
    t_is_cash     BOOL NOT NULL,
    t_s_symb      VARCHAR(15) NOT NULL,
    t_qty         INT4 NOT NULL CHECK (t_qty > 0),
    t_bid_price   DECIMAL(8,2) NOT NULL CHECK (t_bid_price > 0),
    t_ca_id       INT8 NOT NULL,
    t_exec_name   VARCHAR(49) NOT NULL,
    t_trade_price DECIMAL(8,2),
    t_chrg        DECIMAL(10,2) NOT NULL CHECK (t_chrg >= 0),
    t_comm        DECIMAL(10,2) NOT NULL CHECK (t_comm >= 0),
    t_tax         DECIMAL(10,2) NOT NULL CHECK (t_tax  >= 0),
    t_lifo        BOOL NOT NULL,
    FAMILY (t_id),
    FAMILY (t_comm, t_dts, t_st_id, t_trade_price, t_exec_name, t_tt_id, t_is_cash, t_s_symb, t_qty, t_bid_price, t_ca_id, t_chrg, t_lifo),
    FAMILY (t_tax)
);
CREATE INDEX ON trade (t_ca_id, t_dts DESC) STORING (t_st_id, t_tt_id, t_is_cash, t_s_symb, t_qty, t_bid_price, t_exec_name, t_trade_price, t_chrg);
CREATE INDEX ON trade (t_s_symb, t_dts ASC) STORING (t_ca_id, t_exec_name, t_is_cash, t_trade_price, t_qty, t_tt_id);
IMPORT INTO trade CSV DATA ('gs://cockroach-fixtures/tpce-csv/customers=100000/*/Trade.txt?AUTH=implicit') WITH delimiter = '|', DETACHED;
```

This took 4h43m46s without this patch, and 3h54m37s with it -- a pretty significant reduction of 17.3%. A few relevant graphs, where the first import started at 21:40 and the second one at 08:55, show that we're getting better resource utilization both in terms of CPU and IO:

Screenshot 2021-12-20 at 13 55 15
Screenshot 2021-12-20 at 13 55 25
Screenshot 2021-12-20 at 13 55 33
Screenshot 2021-12-20 at 13 56 14

I'll do another run and see if the results are consistent.

**Comment by erikgrinaker** [comment]
Second run was consistent: 4h55m23s vs 4h11m23s, so a 14.9% reduction. Nice work!

**Comment by itsbilal** [comment]
First commit is https://github.com/cockroachdb/cockroach/pull/74745 , which this change depends on, but otherwise this PR is ready for review.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-:-MtEh_Fb87MS3h-HoS9o:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @itsbilal)

___
*[pkg/storage/sst_iterator.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-MtEgwzw0DXtvYjtDJOr:-MtEgwzw0DXtvYjtDJOs:b-kcd13i) ([raw file](https://github.com/cockroachdb/cockroach/blob/095addc36bc381f18ff8f1dfd0376ad79a5dab3f/pkg/storage/sst_iterator.go#L95)):*
> ```Go
> 	trySeekUsingNext := false
> 	if r.seekGELastOp {
> 		// trySeekUsingNext = r.prevSeekKey <= key
> ```

leftover code?
___
*[pkg/storage/sst_iterator.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-MtEh3Pd8IfIbSOcvFpZ:-MtEh3Pd8IfIbSOcvFp_:brawe57) ([raw file](https://github.com/cockroachdb/cockroach/blob/095addc36bc381f18ff8f1dfd0376ad79a5dab3f/pkg/storage/sst_iterator.go#L97)):*
> ```Go
> 		// trySeekUsingNext = r.prevSeekKey <= key
> 		trySeekUsingNext = !key.Less(r.prevSeekKey)
> 	}
> ```

maybe add a comment like
// NB: seekGELastOp may still be true, and we haven't updated prevSeekKey. So be careful not to return before the end of the function that sets these fields up for the next SeekGE.

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-:-MtEkqu89cpV4WeA0nMv:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @sumeerbhola)

___
*[pkg/storage/sst_iterator.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-MtEgwzw0DXtvYjtDJOr:-MtEjSRy-eijOKB6MCIO:b-cq3ux4) ([raw file](https://github.com/cockroachdb/cockroach/blob/095addc36bc381f18ff8f1dfd0376ad79a5dab3f/pkg/storage/sst_iterator.go#L95)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

leftover code?
</blockquote></details>

Nope, it's just writing the below line in mathematical form, as the code form is a little weird with the `!Less`. 
___
*[pkg/storage/sst_iterator.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-MtEh3Pd8IfIbSOcvFpZ:-MtEjaWx1mZPm3h-LwA9:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/095addc36bc381f18ff8f1dfd0376ad79a5dab3f/pkg/storage/sst_iterator.go#L97)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

maybe add a comment like
// NB: seekGELastOp may still be true, and we haven't updated prevSeekKey. So be careful not to return before the end of the function that sets these fields up for the next SeekGE.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73981)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/sst_iterator.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73981#-MtEgwzw0DXtvYjtDJOr:-MtEpXRA4AL5Ig0AzSBi:bmnvm2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/095addc36bc381f18ff8f1dfd0376ad79a5dab3f/pkg/storage/sst_iterator.go#L95)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Nope, it's just writing the below line in mathematical form, as the code form is a little weird with the `!Less`. 
</blockquote></details>

ah yes, I was too hasty in my reading.

**Comment by itsbilal** [comment]
Thanks! Seeing as both this and #74745 are green and approved, I'll merge just this PR to save time.

bors r=sumeerbhola

**Pull request merged**
