### PR TITLE
sql: clean up large row errors and events

### PR DESCRIPTION
**Pull request by michae2**
Addresses: #67400, #69477

Remove ViolatesMaxRowSizeErr from CommonLargeRowDetails, as was done
for CommonTxnRowsLimitDetails in #69945.

Also remove the SafeDetails methods from CommonLargeRowDetails,
txnRowsReadLimitErr, and txnRowsWrittenLimitErr, as I don't think we
need them.

Release note: None (there was no release between the introduction of the
LargeRow and LargeRowInternal events and this commit).

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70102#-:-MjU9OnY1rsEbbnVKH7j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70102#-:-MjUIQcm-J52ieMH38-k:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

**Comment by michae2** [comment]
TFTRs!

bors r=knz,yuzefovich

**Comment by michae2** [comment]
Oh, one last thing!

bors r-

**Comment by michae2** [comment]
Ok, fixed two comments (thanks @yuzefovich!). I'm going to go ahead.

bors r=knz,yuzefovich

**Comment by michae2** [comment]
Backport will have to be after https://github.com/cockroachdb/cockroach/pull/70014

**Pull request merged**
