### PR TITLE
cli: unskip test_demo_partitioning interactive test

### LINKED ISSUE #96797: TestDockerCLI/test_demo_partitioning.tcl failed
```
expect: does "/cockroach/cockroach demo --no-line-editor --geo-partitioned-replicas\r\n#\r\n# --geo-partitioned replicas operates on a 9 node cluster.\r\n# The cluster size has been changed from the default to 9 nodes.\r\n#\r\n# Welcome to the CockroachDB demo database!\r\n#\r\n# You are connected to a temporary, in-memory CockroachDB cluster of 9 nodes.\r\n#\r\n# You are connected to tenant "demo-tenant", but can connect to the system tenant with\r\n# '\connect' and the SQL url printed via '\demo ls'.\r\n#\r\n# This demo session will send telemetry to Cockroach Labs in the background.\r\n# To disable this behavior, set the environment variable\r\n# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.\r\n*\r\n* ERROR: pq: update-setting: failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] lease held by different store; r59: replica (n4,s4):2 not lease holder; current lease is repl=(n2,s2):4VOTER_INCOMING seq=3 start=1675862669.825552515,0 epo=1 pro=1675862669.826726640,0\r\n*\r\nERROR: pq: update-setting: failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] lease held by different store; r59: replica (n4,s4):2 not lease holder; current lease is repl=(n2,s2):4VOTER_INCOMING seq=3 start=1675862669.825552515,0 epo=1 pro=1675862669.826726640,0\r\nFailed running "demo"\r\n:/# " (spawn_id exp3) match glob pattern "operation is unsupported in multi-tenancy mode"? no

```

> ERROR: pq: update-setting: failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] lease held by different store; r59: replica (n4,s4):2 not lease holder; current lease is repl=(n2,s2):4VOTER_INCOMING seq=3 start=1675862669.825552515,0 epo=1 pro=1675862669.826726640,0

This error shouldn't bubble up to the client, I don't think.

https://teamcity.cockroachdb.com/viewLog.html?buildId=8633421&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_Acceptance

from unrelated PR https://github.com/cockroachdb/cockroach/pull/96785.

Jira issue: CRDB-24338

### PR DESCRIPTION
**Pull request by aadityasondhi**
Fixes #96797.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
The test was skipped due to [this](https://github.com/cockroachdb/cockroach/issues/96797#issue-1576313126). You can it locally [once](https://github.com/cockroachdb/cockroach/issues/96797#issuecomment-1633165577), as far as I can tell. What indication is there that it just won't be flaky again?

The failure mode here was a DistSender-level error leaking up to the client. This is likely to happen again, as I don't think we've fixed it. So either the test needs to be able to handle this (if this bubbling up is expected behavior) or the bubbling up has to be prevented. The former seems really annoying to implement, and the latter seems conducive to higher quality anyway, so that seems to be the better option. But it's also a real little piece of work that likely won't be done as a drive-by.

In terms of what this kind of test failure means to users, it means that CRDB is harder to script against. I think someone had a similar conversation in KV the other day - if, e.g., commands to relocate a range don't reliably work, they are less useful.

**Comment by aadityasondhi** [comment]
@tbg I see, I overlooked that when the test passed. Thanks for pointing that out! I propose the following (let me know if you disagree):

1. We add additional retries to this test to make sure it passes without this error. (band-aid fix to get this test unskipped)
2. Maybe we can handle the distsender issue as part of this https://github.com/cockroachdb/cockroach/issues/93503. The solution there will be rewriting a lot of the logic that causes this error in the first place.

cc @andrewbaptist

**Comment by tbg** [comment]
> We add additional retries to this test to make sure it passes without this error. (band-aid fix to get this test unskipped)

SGTM. 

> Maybe we can handle the distsender issue as part of this https://github.com/cockroachdb/cockroach/issues/93503. The solution there will be rewriting a lot of the logic that causes this error in the first place.

it seems unrelated enough to not address this problem automatically. Even if it did, it would be doing so accidentally. The contract about which errors are returned from the KV API (and when) is not well defined currently.

https://github.com/cockroachdb/cockroach/issues/49868 is a related issue. I would suggest filing, against T-kv, an issue that asks for a clear contract implemented via a doc comment somewhere and a set of checks (maybe using https://github.com/cockroachdb/cockroach/pull/106508) that reliably catch and report unexpected errors. #49868 and this issue should then be linked against it.

This isn't solving the problem, obviously, but then we have a canonical reference that collects instances in which we see unexpected errors reaching KV clients.

**Review by AlexTalks — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106722#-:-Nbzjjux6RX2gGgBsfgK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by aadityasondhi** [comment]
bors r=AlexTalks

**Pull request merged**
