### PR TITLE
raft: add the concept of quorum supported expiration

### LINKED ISSUE #125263: raft: add concept of quorum supported expiration
Part of https://github.com/cockroachdb/cockroach/issues/123847

As part of the leader leases, the raft leader needs to calculate the quorum supported expiration (QSE). The QSE is defined as a leader’s maximum supported store liveness expiration across all quorums, where the value for each quorum is the minimum across replicas, from the perspective of an oracle.

Note that this should work with joint configurations as well. For joint configurations, the QSE is the minimum QSE across both the configurations. 

Jira issue: CRDB-39354

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
This patch adds the concept of QSE to {Majority,Joint}Config. For a majority config, the QSE is defined as the leader's maximum supported store liveness expiration across all quorums, where the value for each quorum is the minimum across all replicas, from the perspective of an oracle. For joint configurations, the QSE is the minimum across both its LHS and RHS.

Closes https://github.com/cockroachdb/cockroach/issues/125263

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/quorum/joint.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YcmsA86w3AqKsT9rd:-O3YcmsA86w3AqKsT9re:b-ir6y4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/joint.go#L85)):*
> ```Go
> }
> 
> // ComputeQSE takes a mapping of support timestamps and returns the quorum
> ```

The concept of a "quorum supported expiration" was useful for the design doc where everything was contextualized, but I'm wondering if it's a little too much of an unspecific implementation detail when translated to code and surrounded by other consensus concepts.

What do you think about reframing this in terms of "lead support", like we have in the `LeadSupportStatus`? We could call this `LeadSupportExpiration` and introduce a `LeadSupportTracker` (in-place of a QSETracker)?
___
*[`pkg/raft/quorum/joint.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YdOz3EQEcGV8gxvFz:-O3YdOz3EQEcGV8gxvG-:b-gmhifh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/joint.go#L85)):*
> ```Go
> }
> 
> // ComputeQSE takes a mapping of support timestamps and returns the quorum
> ```

nit: There's no "Compute" prefix on the associated commit index and election methods.
___
*[`pkg/raft/quorum/joint.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Ye5U33ldTv8bXaot3:-O3Ye5U33ldTv8bXaot4:bfblmed) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/joint.go#L91)):*
> ```Go
> // [*] The QSE is defined as a leader’s maximum supported store liveness
> // expiration across all quorums, where the value for each quorum is the minimum
> // across replicas, from the perspective of an oracle.
> ```

We could also add that this is the median in each quorum.
___
*[`pkg/raft/quorum/majority.go` line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YeKw76C4zkDw9ZtjM:-O3YeKw76C4zkDw9ZtjN:bvasyy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L152)):*
> ```Go
> 	}
> 
> 	var votedCnt int //vote counts for yes.
> ```

Can we add a comment here about why we don't use `quorumSupportedElement` (`medianElement`)? Or maybe we can if we map true to `1`, missing to `0`, and false to `-1`.
___
*[`pkg/raft/quorum/majority.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Yf1V42SjaEPqXFn2a:-O3Yf1V42SjaEPqXFn2b:bhwvuym) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L183)):*
> ```Go
> func (c MajorityConfig) ComputeQSE(supported map[pb.PeerID]hlc.Timestamp) hlc.Timestamp {
> 	if len(c) == 0 {
> 		// This plays well with joint quorums when one half is the zero
> ```

Instead of just describing why this is helpful to a caller, it would be good to also explain why this makes sense in isolation.
___
*[`pkg/raft/quorum/majority.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfYz-76TTG9QkVgjp:-O3YfYz-76TTG9QkVgjq:b-ag1jrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L213)):*
> ```Go
> // is found must be returned.
> func quorumSupportedElement[E cmp[E]](
> 	c MajorityConfig, getElementForPeer func(id pb.PeerID) (E, bool),
> ```

I'm a little concerned that this closure is going to have a runtime cost. Did you look into making this generic as well? Something like:

```go
type Comparable[T Comparable[T]] interface {
	Compare(T) int
}

type ComparableMap[T Comparable[T]] interface {
	Get(pb.PeerID) (Comparable[T], bool)
}

func medianElement[E Comparable[E], M ComparableMap[E]](c MajorityConfig, elems M) E {
	var e E
	return e
}
```
Then we could replace `AckedIndexer` with implementations of this `ComparableMap` interface.
___
*[`pkg/raft/quorum/majority.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Ypf_22ZvA8KWrF2GO:-O3Ypf_22ZvA8KWrF2GP:brrbk48) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L232)):*
> ```Go
> 		// Fill the slice with elements. Any unused slots will be left as zero/empty
> 		// for our calculation. We fill from the right (since the zeros will end up
> 		// on the left after sorting anyway).
> ```

There's an assumption here that a missing element should be assigned the zero value of `E` and that this zero value will sort as expected by the caller. It would be good to call that out. Or we could just remove the `bool` return value from `getElementForPeer` so that callers need to decide on how to handle zero values. Then you wouldn't need `i` down below.
___
*[`pkg/raft/quorum/quorum.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfBl80rEFj7qoJEFt:-O3YfBl80rEFj7qoJEFu:buu30an) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/quorum.go#L40)):*
> ```Go
> // greater, and 0 if they're equal.
> func (a Index) Compare(b Index) int {
> 	if a > b {
> ```

Does `return cmp.Compare(a, b)` work here?

**Review by arulajmani — COMMENTED** [review]
Sorry for procrastinating on this one. RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-:-O5K-mez214PHlOYhUiW:b-2h4vv7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/quorum/joint.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YcmsA86w3AqKsT9rd:-O5JxbRND2Xk4Fx1T7cj:bry1bq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/joint.go#L85)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The concept of a "quorum supported expiration" was useful for the design doc where everything was contextualized, but I'm wondering if it's a little too much of an unspecific implementation detail when translated to code and surrounded by other consensus concepts.

What do you think about reframing this in terms of "lead support", like we have in the `LeadSupportStatus`? We could call this `LeadSupportExpiration` and introduce a `LeadSupportTracker` (in-place of a QSETracker)?
</blockquote></details>

I changed this method name to `LeadSupportExpiration`. 
___
*[`pkg/raft/quorum/joint.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Ye5U33ldTv8bXaot3:-O5JxSj900Bx0wgvUSkr:bfekj6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/joint.go#L91)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We could also add that this is the median in each quorum.
</blockquote></details>

This comment no longer applies, but I'm open to suggestions on how this can be reworded/any additional details that'd be helpful.
___
*[`pkg/raft/quorum/majority.go` line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YeKw76C4zkDw9ZtjM:-O5JyrV1-_U1sK5qzSbO:brud9fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we add a comment here about why we don't use `quorumSupportedElement` (`medianElement`)? Or maybe we can if we map true to `1`, missing to `0`, and false to `-1`.
</blockquote></details>

I added a comment. I find this logic a bit more readable, so I'm inclined to keep it such instead of calling (what is now) `computeElement`. 
___
*[`pkg/raft/quorum/majority.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5Jz4r_0jHw7LkSTLws:-O5Jz4r_0jHw7LkSTLwt:b3hqneq) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L212)):*
> ```Go
> // that's the case, a second boolean return value indicating whether the element
> // is found must be returned.
> func quorumSupportedElement[E cmp[E]](
> ```

We spoke offline about calling this something generic, like `computeElement`. I'm not thrilled about the commentary here, so I'll gladly take suggestions if you have some.
___
*[`pkg/raft/quorum/majority.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfYz-76TTG9QkVgjp:-O5JnZbe4F8N8D8TqT4o:bfy72cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L213)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little concerned that this closure is going to have a runtime cost. Did you look into making this generic as well? Something like:

```go
type Comparable[T Comparable[T]] interface {
	Compare(T) int
}

type ComparableMap[T Comparable[T]] interface {
	Get(pb.PeerID) (Comparable[T], bool)
}

func medianElement[E Comparable[E], M ComparableMap[E]](c MajorityConfig, elems M) E {
	var e E
	return e
}
```
Then we could replace `AckedIndexer` with implementations of this `ComparableMap` interface.
</blockquote></details>

Done. I didn't fully replaced `AckedIndexer`, instead I specialized it as `ComparableMap[Index]`. This seemed the most non-disruptive way to make this change and fit quite well with the `CommitedIndex` methods on `{Joint,MajorityConfig`s. Let me know what you think.
___
*[`pkg/raft/quorum/majority.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Ypf_22ZvA8KWrF2GO:-O5JukDn2zBT3vO5OB4X:b64y698) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's an assumption here that a missing element should be assigned the zero value of `E` and that this zero value will sort as expected by the caller. It would be good to call that out. Or we could just remove the `bool` return value from `getElementForPeer` so that callers need to decide on how to handle zero values. Then you wouldn't need `i` down below.
</blockquote></details>

I called it out in the comment to this function. I have no strong preference, so we can push this handling to the caller if you prefer. 
___
*[`pkg/raft/quorum/quorum.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfBl80rEFj7qoJEFt:-O5JnYCwEZxu5jilxCAm:b9izszt) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/quorum.go#L40)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `return cmp.Compare(a, b)` work here?
</blockquote></details>

Yup, done.

**Review by nvb — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/quorum/majority.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Yf1V42SjaEPqXFn2a:-O5P8mCuE3ybJ37OGa_O:b-i43kb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of just describing why this is helpful to a caller, it would be good to also explain why this makes sense in isolation.
</blockquote></details>

This sentence is cut off.
___
*[`pkg/raft/quorum/majority.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfYz-76TTG9QkVgjp:-O5PABUqAwO6KvKRhhKM:b-7p5c8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L213)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done. I didn't fully replaced `AckedIndexer`, instead I specialized it as `ComparableMap[Index]`. This seemed the most non-disruptive way to make this change and fit quite well with the `CommitedIndex` methods on `{Joint,MajorityConfig`s. Let me know what you think.
</blockquote></details>

This makes sense. I think it came out well.
___
*[`pkg/raft/quorum/majority.go` line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5P9A5EDifU0YaWBC_K:-O5P9A5EDifU0YaWBC_L:b-lu3bnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L214)):*
> ```Go
> }
> 
> // computeElement returns the element that's supported by a majority in the
> ```

Should we keep "the maximum element"?
___
*[`pkg/raft/quorum/majority.go` line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5P8wET76-94rplQdYj:-O5P8wET76-94rplQdYk:bm37er8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L216)):*
> ```Go
> // computeElement returns the element that's supported by a majority in the
> // provided configuration. We assume that if an element is supported by a peer,
> // then all values up till the element are also supported by it.
> ```

s/all values up till/all elements with smaller values (as defined by the Comparable ordering)/
___
*[`pkg/raft/quorum/majority.go` line 221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5PAlSb2GWG9THRPAvd:-O5PAlSb2GWG9THRPAve:b-1alvzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L221)):*
> ```Go
> // a peer then it is treated as the zero value and sorts before all other
> // elements.
> func computeElement[E Comparable[E], M ComparableMap[E]](c MajorityConfig, elems M) E {
> ```

Are there any microbenchmarks around here that we can use to verify that performance is moving in the right direction and that we're not introducing new work?
___
*[`pkg/raft/quorum/majority.go` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5P9t049rTQdpo2X085:-O5P9t049rTQdpo2X086:b-jkpbzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L253)):*
> ```Go
> 	})
> 
> 	// We want the smallest element which is supported by a quorum. So we need to
> ```

I feel like the previous commentary was an improvement. Any reason to switch this?
___
*[`pkg/raft/quorum/majority.go` line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5P9x7I0Vg6bQt8arSe:-O5P9x7I0Vg6bQt8arSf:bcaa02l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L255)):*
> ```Go
> 	// We want the smallest element which is supported by a quorum. So we need to
> 	// move n/2 + 1 to the left from the end of the sorted slice (accounting for
> 	// zer-indexing).
> ```

"zero"

**Review by arulajmani — COMMENTED** [review]
Closing this out because of the microbenchmark regression in the approach. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-:-O5VSPYW1ajJtNLJSFhw:b-n2ez0u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/quorum/majority.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3Yf1V42SjaEPqXFn2a:-O5TcuUi11VpHnx0FSNG:b-9fp6p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This sentence is cut off.
</blockquote></details>

Sorry, fixed. 
___
*[`pkg/raft/quorum/majority.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O3YfYz-76TTG9QkVgjp:-O5Td_zpBemh41BjiMHZ:b-npjmht) ([raw file](https://github.com/cockroachdb/cockroach/blob/70f8a88a25c15ae664765630dbddf8f70e5f249f/pkg/raft/quorum/majority.go#L213)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This makes sense. I think it came out well.
</blockquote></details>

+1, I'm happy how this turned out too. Thanks for the suggestion.
___
*[`pkg/raft/quorum/majority.go` line 221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5PAlSb2GWG9THRPAvd:-O5VRrCn4jcM2OHNbkeZ:bnrye5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are there any microbenchmarks around here that we can use to verify that performance is moving in the right direction and that we're not introducing new work?
</blockquote></details>

```
  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/raft/quorum |

name                                        old time/op    new time/op    delta
MajorityConfig_CommittedIndex/voters=1-10     38.3ns ± 3%    39.5ns ± 2%   +3.19%  (p=0.001 n=9+9)
MajorityConfig_CommittedIndex/voters=3-10     64.1ns ± 2%    75.3ns ± 2%  +17.51%  (p=0.000 n=10+8)
MajorityConfig_CommittedIndex/voters=5-10     89.7ns ± 3%   115.6ns ± 3%  +28.94%  (p=0.000 n=9+10)
MajorityConfig_CommittedIndex/voters=9-10      199ns ± 3%     268ns ± 0%  +34.68%  (p=0.000 n=10+7)
MajorityConfig_CommittedIndex/voters=7-10      116ns ± 1%     157ns ± 2%  +35.74%  (p=0.000 n=9+10)
MajorityConfig_CommittedIndex/voters=11-10     238ns ± 5%     337ns ± 2%  +41.83%  (p=0.000 n=10+9)
```

These don't look great, unfortunately. We talked about this offline, and this seems like a result of the call to `Compare` in `slices.SortFunc()`. We decided that we'll close this PR out and not try to have a generic approach that covers both `CommittedIndex` and `LeadSupportExpiration`. 
___
*[`pkg/raft/quorum/majority.go` line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128054#-O5P9t049rTQdpo2X085:-O5Te39E2ajhqrsjlDAF:b-5jm8nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4663aaa9c7a53e25e502f550c55b8559d3905f4/pkg/raft/quorum/majority.go#L253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I feel like the previous commentary was an improvement. Any reason to switch this?
</blockquote></details>

I was trying to get away from the whole "across all quorums" phrasing, but admittedly, the new commentary was rather lacking. 

I took another stab, let me know what you think.

**Pull request closed without merging**
