### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable the following logic tests, and fix the bugs found while enabling them:

  alias_types
  alter_sequence
  alter_table
  array

The alter_table test isn't yet split out, because the optimizer doesn't
yet support DDL, so all EXPLAIN/TRACE statements fall back on the
planner anyway.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm_strong:  Nice fixes.

With `r2`, can we remove [this](https://github.com/cockroachdb/cockroach/blob/d18bc12bf3c33cd4811d27979cdb79b9c54220ad/pkg/sql/exec_util.go#L403) switch in shouldUseOptimizer?

---

Review status: 0 of 27 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/optbuilder/builder.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDBr7_W9-Duowk48f8x:-LDBr7_W9-Duowk48f8y:b-ivrrfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9533af83d849efd2bceb07e58cb1847b507fa6/pkg/sql/opt/optbuilder/builder.go#L61)):*
> ```Go
> 	// builder will not panic when it encounters an impure function. While the
> 	// cost-based optimizer does not currently handle impure functions, the
> 	// heuristic planner can handle them (and uses the builder code to do index
> ```

[nit] I'd say "for index constraints" instead of "to do index planning" which sounds like more than that

---

*[pkg/sql/opt/optbuilder/builder.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDBqGh57NNLLWuR9x_m:-LDBqGh57NNLLWuR9x_n:bdd2sag) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9533af83d849efd2bceb07e58cb1847b507fa6/pkg/sql/opt/optbuilder/builder.go#L179)):*
> ```Go
> 
> 	default:
> 		panic(builderError{pgerror.Unimplemented(
> ```

[nit] we're using this construct in a bunch of places (and more to come), we should put it in a helper function, e.g. `b.unimplementedf`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-:-LDBrdAX-qHeD0qqjN9h:b-2fc7cv)*

**Comment by andy-kimball** [comment]
I added a commit to do some refactoring of the fallback decision code. See what you think.

---

Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/optbuilder/builder.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDBr7_W9-Duowk48f8x:-LDCIdxj9bW2-Cg5QCCq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9533af83d849efd2bceb07e58cb1847b507fa6/pkg/sql/opt/optbuilder/builder.go#L61)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd say "for index constraints" instead of "to do index planning" which sounds like more than that
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/builder.go, line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDBqGh57NNLLWuR9x_m:-LDCK3gF965TMXqcAtGw:b9u5e2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae9533af83d849efd2bceb07e58cb1847b507fa6/pkg/sql/opt/optbuilder/builder.go#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we're using this construct in a bunch of places (and more to come), we should put it in a helper function, e.g. `b.unimplementedf`
</blockquote></details>

Yeah, not sure why I didn't think of doing that. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-:-LDCAKIu5RuqAo3OBZF5:b-qru6o3)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 32 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-:-LDCP7uu8r4cVGwRw3QD:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 14 of 17 files at r2, 5 of 5 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/array, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDChN6Y-24XegVhCsXQ:-LDChN6Z8tnqodyo_Pio:by9b5xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36898e23486a75927b24a84034720d01084ccf7/pkg/sql/logictest/testdata/logic_test/array#L1)):*
> ```
> # LogicTest: default opt distsql distsql-metadata
> ```

Is there a reason you haven't enabled `distsql-opt` here?

---

*[pkg/sql/opt/catalog.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDCeEba7r6MK3Ae-lWL:-LDCeEba7r6MK3Ae-lWM:bnaici0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fb5cfca0150afe4ab666acb5c3d3affdd5d5fb/pkg/sql/opt/catalog.go#L137)):*
> ```Go
> 
> 	// IsVirtualTable returns true if this table is a special system table that
> 	// constructs its rows "on the fly" when it's queried. An example are the
> ```

are -> is

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-:-LDCiuFmEN_Uta2kTOyr:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/array, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDChN6Y-24XegVhCsXQ:-LDCjE795dCIP0KxgZGw:b5ac1d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36898e23486a75927b24a84034720d01084ccf7/pkg/sql/logictest/testdata/logic_test/array#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there a reason you haven't enabled `distsql-opt` here?
</blockquote></details>

There's at least one issue with distsql that I added to the spreadsheet. Radu will take a look at it and then enable `distsql-opt` afterwards.

---

*[pkg/sql/opt/catalog.go, line 137 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25830#-LDCeEba7r6MK3Ae-lWL:-LDCjYOY3mIvu_wmZM96:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fb5cfca0150afe4ab666acb5c3d3affdd5d5fb/pkg/sql/opt/catalog.go#L137)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

are -> is
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25830)*

**Pull request merged**
