### PR TITLE
backupccl: fix glob used when finding prior BACKUP subdirs

### LINKED ISSUE #54010: Incremental BACKUPs to gs don't resolve previous incremental BACKUP folders correctly
While root causing #53932 I realized that the `findPriorBackupLocations` might not be returning the correct results for google storage as well.
The above-mentioned method is supposed to find any BACKUP sub-directories which match the glob `[0-9]*/[0-9]*.[0-9][0-9]/`. It does this by calling the ExternalStorage targets' `ListFiles` method. Both userfile and gs `ListFiles` method use a similar pattern where they find all filepaths with prefixes == the external storage path prior to the glob pattern, and then further filters it using `path.Match(match, globPattern)`. `path.Match` does not match prefixes as seen in - https://play.golang.org/p/QchOeN31vcv and so we are always returned an empty match.

This can be reproduced as follows:
```
CREATE TABLE foo (id INT);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';
INSERT INTO foo VALUES (1);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';
INSERT INTO foo VALUES (2);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';

DROP TABLE foo;
RESTORE TABLE foo FROM  'gs://cockroach-tmp/aditya-test/';

ERROR: making import requests for 3 backups: no backup covers time [1599494189.257411000,0,1599494163.075177000,0) for range [/Table/52/1,/Table/52/2) or backups listed out of order (mismatched start time)
```

Switching to using `nodelocal` instead will make the above set of statements pass correctly, reason being nodelocal ListFiles uses `glob.Match()` which matches directory hierarchies and so we return the appropriate subdir where a previous backup was found.

### PR DESCRIPTION
**Pull request by adityamaru**
Fixes: #54010, #53932

### CODE REVIEW

**Comment by adityamaru** [comment]
First commit is from #53926, will rebase once merged.

**Review by pbardea — APPROVED** [review]
LGTM with nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-:-MGnFuhY8MJwC8MPF7RH:b3590pt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnDzyr147SEgsFlspu:-MGnDzyr147SEgsFlspv:bp6hgw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L505)):*
> ```Go
> 			"nodelocal",
> 			makeBackups(localFoo1, localFoo2, localFoo3),
> 			makeCollections(`nodelocal://0/`, `nodelocal://1/`, `nodelocal://2/`),
> ```

nit: can we keep the `for testing backup *into* collection, pick collection shards on each node.` on this line to callout that this is indeed what we mean as opposed to `'nodelocal://0/0', 'nodelocal://0/1', 'nodelocal://0/2'`?
___
*[pkg/ccl/backupccl/backup_test.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnFJQ71gw1r0HD8HiM:-MGnFJQ71gw1r0HD8HiN:bgo9bvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L601)):*
> ```Go
> 			require.NoError(t, err)
> 			defer store.Close()
> 			files, err := store.ListFiles(ctx, "*/*/*/BACKUP_MANIFEST")
> ```

nit: I personally am partial to keeping the instances of "BACKUP_MANIFEST" as `backupManifestName`.
___
*[pkg/ccl/backupccl/backup_test.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnEyL48wr0j6TRhzv0:-MGnEyL48wr0j6TRhzv1:bhxklvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L604)):*
> ```Go
> 			require.NoError(t, err)
> 			full1 = files[0]
> 			full1 = strings.TrimSuffix(full1, "BACKUP_MANIFEST")
> ```

super-nit: I think this reads a bit better in-lined: `full1 = strings.TrimeSuffix(files[0], "BACKUP_MANIFEST")`, like you did with subdirFiles.
___
*[pkg/ccl/backupccl/backup_test.go, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnEeMeEiTOWmZnO3DX:-MGnEeMeEiTOWmZnO3DY:bnkwco5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L617)):*
> ```Go
> 			subdirFull1 = strings.TrimSuffix(strings.TrimPrefix(subdirFiles[0], "foo"), "BACKUP_MANIFEST")
> 			subdirFull2 = strings.TrimSuffix(strings.TrimPrefix(subdirFiles[1], "foo"), "BACKUP_MANIFEST")
> 			runRestores(test.collectionsWithSubdir, subdirFull1, subdirFull2)
> ```

nit: could we move the `runRestore` calls outside the if statement? I'd prefer the keep the minimum amount of special casing inside this test (e.g. just setting `full{1,2}` and `subdirFull{1,2}`).
___
*[pkg/ccl/backupccl/manifest_handling.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnFfcC-pp4I2HJypTL:-MGnFfcC-pp4I2HJypTM:b-6isrq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/manifest_handling.go#L601)):*
> ```Go
> 		// that too.
> 		backupManifestSuffix = backupOldManifestName
> 		prev, err = store.ListFiles(ctx, "[0-9]*/[0-9]*.[0-9][0-9]/"+backupManifestSuffix)
> ```

nit: it might be nice to move out this `"[0-9]*/[0-9]*.[0-9][0-9]/"` to a const.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnDzyr147SEgsFlspu:-MGs4nNH7BVSHE_kpT1F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L505)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: can we keep the `for testing backup *into* collection, pick collection shards on each node.` on this line to callout that this is indeed what we mean as opposed to `'nodelocal://0/0', 'nodelocal://0/1', 'nodelocal://0/2'`?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnFJQ71gw1r0HD8HiM:-MGs5JJrC5u97REUnOOP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L601)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: I personally am partial to keeping the instances of "BACKUP_MANIFEST" as `backupManifestName`.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 604 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnEyL48wr0j6TRhzv0:-MGs5RCv4BLtaseIrXNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L604)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

super-nit: I think this reads a bit better in-lined: `full1 = strings.TrimeSuffix(files[0], "BACKUP_MANIFEST")`, like you did with subdirFiles.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnEeMeEiTOWmZnO3DX:-MGs5fVA3rs3DakwYrqT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/backup_test.go#L617)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: could we move the `runRestore` calls outside the if statement? I'd prefer the keep the minimum amount of special casing inside this test (e.g. just setting `full{1,2}` and `subdirFull{1,2}`).
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54026#-MGnFfcC-pp4I2HJypTL:-MGs62jA-fcxgMKLoA7Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae0a366d42385b99b5a2b64f5f91b671dbd11b36/pkg/ccl/backupccl/manifest_handling.go#L601)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: it might be nice to move out this `"[0-9]*/[0-9]*.[0-9][0-9]/"` to a const.
</blockquote></details>

Done.

**Review by dt — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea,dt

**Pull request merged**
