### PR TITLE
roachpb: convert api.proto and data.proto to proto3

### PR DESCRIPTION
**Pull request by petermattis**
This shaves 6% off the encoded size of `Batch{Request,Response}` for a
simple scan operation.

See #18919

### CODE REVIEW

**Comment by petermattis** [comment]
This touches enough files that we should probably hold off on merging for a few weeks. Also, should I convert more files to `proto3`? `api.proto` contains the most important conversions as it touches RPC messages that contain primitive fields.

**Comment by bdarnell** [comment]
I'm nervous about this - we've broken things by making changes like this before (although at least this would be at the beginning of a cycle). See #5891 for more debate.

`api.proto` and `data.proto` are the big risks - if we get them converted to proto3 we might as well go all the way and get everything moved over. But it might be safer to leave them as-is and convert only selected messages to proto3 so we can give the change more scrutiny (Transaction and TxnMeta look like the biggest wins).

**Comment by petermattis** [comment]
#5891 was pre proposer-evaluated kv so there was a lot more stuff below raft. That said, recent changes to protos have proven fragile. I'd go so far as to say that this PR will almost certainly a surprising/subtle bug. Not sure how to mitigate that.

**Comment by bdarnell** [comment]
Yeah, it's gotten much better with propEvalKV (we didn't even have the below-raft-protos test when that was first proposed). They're even talking about bringing unknown-field preservation back to proto3, which counters one of my proto2-forever arguments. 

A 6% space savings isn't huge and most of that probably comes from a couple of messages, so we could minimize the risk by just not changing most of the protos. Or if we decide to go 100% proto3, we should probably go ahead and rip off the bandaid.

**Comment by petermattis** [comment]
Agreed that the 6% savings isn't huge, but I think it paves the way for only sending back a `Transaction` with the fields we want to update. So yeah, just converting `TxnMeta` and `Transaction` would be the minimal approach, though `roachpb.Header` might be useful too.

**Comment by petermattis** [comment]
I took another look at this PR this morning, and my preference is to convert more protos to proto3 rather than less. Proposer-evaluated KV means we have relatively few protos that need to remain proto2. Yeah, it is possible that we'll have some headaches in the transition, but I think they'll be minor. Converting a field from not-nullable to nullable is more problematic.

I've added another commit which converts `TxnMeta` to proto3.

**Comment by petermattis** [comment]
@bdarnell PTAL

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 9 of 20 files at r1, 37 of 37 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18930#-:-KxKKy8uvLRw18cfqgIP:bnfp4nl)*

**Pull request merged**
