### PR TITLE
server: adding tests for statement details status api

### PR DESCRIPTION
**Pull request by maryliag**
This commit adds test cases for the newly created
StatementDetails endpoint.

Release note: None
Release justification: Category 1

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6pS88E2lieq9usDzK):*
nit: release justification
___
*[pkg/server/status_test.go, line 2116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6m0fQ8x9dJI7lWi_g:-Mx6m0fQ8x9dJI7lWi_h:baaqsm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2116)):*
> ```Go
> 	testPath := func(path string, expected resultValues) {
> 		if err := getStatusJSONProtoWithAdminOption(firstServerProto, path, &resp, false); err != nil {
> 			t.Fatal(err)
> ```

nit: `require.NoError` ? 
___
*[pkg/server/status_test.go, line 2143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6mAWq6YoGBcfJE-yL:-Mx6mAWq6YoGBcfJE-yM:b-udouoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2143)):*
> ```Go
> 	// Test with no query params.
> 	testPath(path,
> 		resultValues{totalCount: 5, aggregatedTsCount: 1, planHashCount: 1, appNames: []string{"first-app", "second-app"}})
> ```

nit: it would improve the readability to have multi-line structs here

```golang
testPath(
  path,
  resultValues{
    totalCount:           5,
    aggregatedTsCount:    1,
     ...
  },
)
```
___
*[pkg/server/status_test.go, line 2143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6mi8d5lnfDoOqrpIl:-Mx6mi8d5lnfDoOqrpIm:bqeo3fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2143)):*
> ```Go
> 	// Test with no query params.
> 	testPath(path,
> 		resultValues{totalCount: 5, aggregatedTsCount: 1, planHashCount: 1, appNames: []string{"first-app", "second-app"}})
> ```

also this seems to be a good use case of table-driven tests, e.g.

```golang
	testData := []struct {
		path           string
		expectedResult resultValues
	}{
		{
			path: "stmtDetails?start=...",
			expectedResult: resultValues{
				totalCount: 1,
				// ...
			},
		},
	}

```

then just run those tabular data through a for-loop of `testPath` 
___
*[pkg/server/status_test.go, line 2176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6ngvK9-NeEJzL8O53:-Mx6ngvL7s0zURvWXjw4:bfzzodp) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2176)):*
> ```Go
> 	// Test with no query params.
> 	testPath(path,
> 		resultValues{totalCount: 5, aggregatedTsCount: 1, planHashCount: 1, appNames: []string{"first-app", "second-app"}})
> ```

I think we can refactor the different role option setting a bit along with the table-driven test refactors mentioned above

```golang
	type roleOptionSetting struct {
		grant  string
		revoke string
	}

	roleOptionSettings := []roleOptionSetting{
		{
			grant:  "ALTER USER ... VIEWACTIVITY; ALTER USER ... NOVIEWACTIVITYREDACTED",
			revoke: "ATLER USER ... NOVIEWACTIVITY;ALTER USER ... VIEWACTIVITYREDACTED",
		},
		// other combinartion of role options.
	}

	for _, roleOption := range roleOptionSetting {
		run := func(roleOption roleOption) {
			sqlConn.Exec(t, roleOption.grant)
			defer sqlConn.Exec(t, roleOption.revoke)

			for _, tc := range testData {
				testPath(tc.path, tc.expectedResult)
			}

		}(roleOption)
	}

```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6pS88E2lieq9usDzK):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: release justification
</blockquote></details>

Done
___
*[pkg/server/status_test.go, line 2116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6m0fQ8x9dJI7lWi_g:-Mx7H0mtAK4rufFATRrm:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2116)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: `require.NoError` ? 
</blockquote></details>

Done
___
*[pkg/server/status_test.go, line 2143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6mAWq6YoGBcfJE-yL:-Mx7H2hO4f1Mn0LVDNph:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2143)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: it would improve the readability to have multi-line structs here

```golang
testPath(
  path,
  resultValues{
    totalCount:           5,
    aggregatedTsCount:    1,
     ...
  },
)
```
</blockquote></details>

Done
___
*[pkg/server/status_test.go, line 2143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6mi8d5lnfDoOqrpIl:-Mx7H53H1drwMlfLbsZw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2143)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

also this seems to be a good use case of table-driven tests, e.g.

```golang
	testData := []struct {
		path           string
		expectedResult resultValues
	}{
		{
			path: "stmtDetails?start=...",
			expectedResult: resultValues{
				totalCount: 1,
				// ...
			},
		},
	}

```

then just run those tabular data through a for-loop of `testPath` 
</blockquote></details>

Done
___
*[pkg/server/status_test.go, line 2176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-Mx6ngvK9-NeEJzL8O53:-Mx7H8e60PoIfOhzBppy:b-eycs3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/026208c36c8a48bf22d32918a17d6ede6d98cacf/pkg/server/status_test.go#L2176)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think we can refactor the different role option setting a bit along with the table-driven test refactors mentioned above

```golang
	type roleOptionSetting struct {
		grant  string
		revoke string
	}

	roleOptionSettings := []roleOptionSetting{
		{
			grant:  "ALTER USER ... VIEWACTIVITY; ALTER USER ... NOVIEWACTIVITYREDACTED",
			revoke: "ATLER USER ... NOVIEWACTIVITY;ALTER USER ... VIEWACTIVITYREDACTED",
		},
		// other combinartion of role options.
	}

	for _, roleOption := range roleOptionSetting {
		run := func(roleOption roleOption) {
			sqlConn.Exec(t, roleOption.grant)
			defer sqlConn.Exec(t, roleOption.revoke)

			for _, tc := range testData {
				testPath(tc.path, tc.expectedResult)
			}

		}(roleOption)
	}

```
</blockquote></details>

I feel like adding the role as part of the loop got a little confusing, so I won't make this particular change. Having the loop on the test was a good improvement that make things clear enough :)

**Review by Azhng — APPROVED** [review]
Nice! :lgtm: Though make sure the tests is green for stress race.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77232#-:-MxARzij16mPVRe-3WVx:b-hqf2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Pull request merged**
