### PR TITLE
*: miscellaneous fixes to allow building with go1.13

### PR DESCRIPTION
**Pull request by petermattis**
Disable modules so that `bin/prereqs` and other uses of
`go/build.Import` do not run into a weird permissioning problem with
writing to the modules cache.

Remove unnecessary calls to `flag.Parse()` from tests. Something changed
with the order of initializers and now explicitly calling `flag.Parse()` in
a test causes the flags in the `testing` package to not be registered which
causes the test to fail to run. The explicit call to
`flag.Parse()` wasn't necessary in any case, as the `testing` package does
that automatically.

Release note: None (we're not upgrading to go1.13 yet)

### CODE REVIEW

**Comment by petermattis** [comment]
@bdarnell and @mberhault A handful of cert related tests in `pkg/security` are failing on go1.13.3 (I verified these pass on go1.12.12 which was just released):

```
~ make test GO=~/Development/go1.13/bin/go PKG=./security/
...
--- FAIL: TestRotateCerts (0.14s)
--- FAIL: TestUseCerts (0.21s)
--- FAIL: TestUseSplitCACerts (0.09s)
--- FAIL: TestUseWrongSplitCACerts (0.10s)
```

The errors are all similar:

```
--- FAIL: TestUseCerts (0.21s)
    certs_test.go:317: Expected success, got Get https://127.0.0.1:60775/_status/metrics/local: remote error: tls: handshake failure
```

Any idea what this is about?

**Comment by petermattis** [comment]
This is probably related:

```
E191020 01:51:23.029777 668 httpLoggerserver.go:3053  http: TLS handshake error from 127.0.0.1:60819: tls: failed to sign handshake: crypto/rsa: key size too small for PSS signature
```

**Comment by petermattis** [comment]
Ah, turns out that go1.13 doesn't like certs created with 512-bit keys. Bumping the key size up to 1024-bits in `security/certs_test.go` fixed the errors. This is ready for a look.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter)

___
*[pkg/base/addr_validation_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-Lrauv6EEJ1sARqv_D-a:-Lrauv6F3EI8hSw7ML6F:b8vk93r) ([raw file](https://github.com/cockroachdb/cockroach/blob/907e3cb5646886399e02f909656ac487cdbb6303/pkg/base/addr_validation_test.go#L67)):*
> ```Go
> 	// below, but before we test anything we need to ensure we indeed have
> 	// a reliably non-resolvable host name.
> 	_, err = net.DefaultResolver.LookupIPAddr(context.Background(), "some.nonexistent")
> ```

Well, this worked for about 10 min, and now `some.nonexistent` is resolving on my home network. What gives? Did something out there notice that I was trying to resolve that host and suddenly start returning a DNS entry for it?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter)

___
*[pkg/base/addr_validation_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-Lrauv6EEJ1sARqv_D-a:-Lraw8ho4IBB_nZKL1Dr:b-g94yq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/907e3cb5646886399e02f909656ac487cdbb6303/pkg/base/addr_validation_test.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Well, this worked for about 10 min, and now `some.nonexistent` is resolving on my home network. What gives? Did something out there notice that I was trying to resolve that host and suddenly start returning a DNS entry for it?
</blockquote></details>

Switching to Google's 8.8.8.8 DNS server resolved all of my woes here. I've removed this commit.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-:-LrdTKq63asHTacWHSd2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @petermattis)

___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-LrdSYE59nZCuzmESZQn:b4oczjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
> ```Go
> var Default = func() build.Context {
> 	c := build.Default
> 	// NB: This is a hack to disable the use of go modules with build.Import. It
> ```

Can you (in the comment) point to some documentation or code somewhere for more details on this? I skimmed the docs and the code and they suggest that a `nil` `JoinPath` is equivalent to `filepath.Join`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter and @RaduBerinde)

___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-LrdZXld10CaPjsKSwZj:bn4zltu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can you (in the comment) point to some documentation or code somewhere for more details on this? I skimmed the docs and the code and they suggest that a `nil` `JoinPath` is equivalent to `filepath.Join`.
</blockquote></details>

Added a pointer to the code. There is no documentation for this behavior, hence the description of this as a hack. I'm pretty certain a future version of Go will break this, but it will get us through go1.13 and hopefully we'll move to modules by go1.14.

**Review by bdarnell — APPROVED** [review]
> Reviewed 7 of 9 files at r2, 1 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter, @petermattis, and @RaduBerinde)

___
*[pkg/base/addr_validation_test.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-Lrauv6EEJ1sARqv_D-a:-Lrj-SlAAY_jKKh2VeAD:bl3kj3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/907e3cb5646886399e02f909656ac487cdbb6303/pkg/base/addr_validation_test.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Switching to Google's 8.8.8.8 DNS server resolved all of my woes here. I've removed this commit.
</blockquote></details>

FWIW, the most reliable way I've found to generate host resolution errors is to try to resolve something with a space in the name. The ISP nameservers that try to resolve everything to some ad-injection nonsense seem to leave these alone (or the space is recognized as invalid at some earlier level)
___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-Lrj0PwoAUKyHFjY4XDg:bqbv9ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Added a pointer to the code. There is no documentation for this behavior, hence the description of this as a hack. I'm pretty certain a future version of Go will break this, but it will get us through go1.13 and hopefully we'll move to modules by go1.14.
</blockquote></details>

When is the GO111MODULE env var read? Could setting that at init time suffice, or is that already too late (or dependent on link order)?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @bobvawter, @petermattis, and @RaduBerinde)

___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-Lrj4JWg8RllC_fFtZZz:b39mu6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

When is the GO111MODULE env var read? Could setting that at init time suffice, or is that already too late (or dependent on link order)?
</blockquote></details>

It seems to be read when the method is called? Would you prefer that approach. It is also somewhat fragile as I've read that the plan is to remove `GO111MODULE` in the future, and there is no guarantee that the read continues to take place when the method is called.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @bobvawter, @petermattis, and @RaduBerinde)

___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-Lrj9SjxEo2TUyBNWORM:b-x1ur5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It seems to be read when the method is called? Would you prefer that approach. It is also somewhat fragile as I've read that the plan is to remove `GO111MODULE` in the future, and there is no guarantee that the read continues to take place when the method is called.
</blockquote></details>

It may change in the future, but it seems less likely to change (and when it changes, more likely to be announced) than the non-nil JoinPath hack, so yes, I think that would be better.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41741)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell, @bobvawter, @petermattis, and @RaduBerinde)

___
*[pkg/testutils/buildutil/build.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41741#-LrdSYE59nZCuzmESZQm:-LrjCipOALEdP7xX-fzd:bd49sie) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8c5e5311cfd7141ecf12dd0f0c66264debd1d35/pkg/testutils/buildutil/build.go#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It may change in the future, but it seems less likely to change (and when it changes, more likely to be announced) than the non-nil JoinPath hack, so yes, I think that would be better. 
</blockquote></details>

Ack. Done.

**Comment by benesch** [comment]
FYI I have an old branch that started to convert the build system to be module aware. It's probably only half done, but it does start to port the various things that currently use `go/build` to the new module-aware importer, `https://godoc.org/golang.org/x/tools/go/packages`.

I've been holding off on reviving it because I heard you're planning to switch to Bazel, and IIUC Bazel doesn't use Go modules? But if you think it'd be useful, I can dust it off and toss it over the wall.

**Comment by petermattis** [comment]
> I've been holding off on reviving it because I heard you're planning to switch to Bazel, and IIUC Bazel doesn't use Go modules? But if you think it'd be useful, I can dust it off and toss it over the wall.

Hmm, interesting. Let me touch base with the dev-inf folks to see if they are interested.

**Comment by petermattis** [comment]
TFTR!

bors r=RaduBerinde,bdarnell

**Pull request merged**
