### PR TITLE
roachtest: don't reuse clusters that call dmsetup

### LINKED ISSUE #107865: roachtest: failover/chaos/read-only failed
roachtest.failover/chaos/read-only [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11114773?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11114773?buildTab=artifacts#/failover/chaos/read-only) on release-23.1 @ [8b970683af4630cbb30b4c92f0be86cfadd97993](https://github.com/cockroachdb/cockroach/commits/8b970683af4630cbb30b4c92f0be86cfadd97993):

```
(cluster.go:2249).Run: output in run_124106.058283365_n1-10_echo-0-sudo-blockdev: echo "0 $(sudo blockdev --getsz /dev/sdb) linear /dev/sdb 0" | sudo dmsetup create data1 returned: COMMAND_PROBLEM: exit status 1
(cluster.go:2249).Run: cluster.RunE: context canceled
(cluster.go:2249).Run: cluster.RunE: context canceled
(cluster.go:2249).Run: cluster.RunE: context canceled
test artifacts and logs in: /artifacts/failover/chaos/read-only/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=2</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30230

### PR DESCRIPTION
**Pull request by andrewbaptist**
Certain tests need to modify the blockdevice and they are prone to failures during setup that the device is still busy. Ideally we would figure out what is still holding onto the dish handle, but it is safer to simply not reuse clusters that perform this by adding `spec.ReuseNone()`

Fixes: #107865
Epic: none

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108115)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @erikgrinaker, @herkolategan, and @smg260)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-NayjJ_15v-U5oAdMWwC:-NayjJ_15v-U5oAdMWwD:bskonfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7f423b5ca0c7eba95ee6286df5efe092a56982/pkg/cmd/roachtest/tests/failover.go#L83)):*
> ```Go
> 				Benchmark:           true,
> 				Timeout:             60 * time.Minute,
> 				Cluster:             r.MakeClusterSpec(10, spec.CPU(2), spec.PreferLocalSSD(false), spec.ReuseNone()), // uses disk stalls
> ```

Nit: remove everything but the cluster size, since they are applied below; otherwise, it's redundant.

**Review by erikgrinaker — APPROVED** [review]
Thanks!

>mount/unmount

nit: unmount/mount works just fine, it's dmsetup that fails. The filesystem isn't in use, the device is.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-:-NazkWbm5mFC4CK-GzZX:b-bvqson)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-NayjJ_15v-U5oAdMWwC:-NazkfSY1YfOExycqCy3:b-276kpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7f423b5ca0c7eba95ee6286df5efe092a56982/pkg/cmd/roachtest/tests/failover.go#L83)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: remove everything but the cluster size, since they are applied below; otherwise, it's redundant.
</blockquote></details>

This is a different test than the ones below that use `clusterOpts`. This one doesn't need conditional options.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-Nazks7R4vyN8ymsIMhA:-Nazks7R4vyN8ymsIMhB:bk1vvwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7f423b5ca0c7eba95ee6286df5efe092a56982/pkg/cmd/roachtest/tests/failover.go#L133)):*
> ```Go
> 				// SSDs. See #97968.
> 				clusterOpts = append(clusterOpts, spec.PreferLocalSSD(false))
> 				clusterOpts = append(clusterOpts, spec.ReuseNone())
> ```

nit: let's add a comment for why we set this.

**Review by andrewbaptist — COMMENTED** [review]
Changed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-:-Nb0pz-hDI2uv5rgRL6-:b499q7j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-NayjJ_15v-U5oAdMWwC:-Nb0q-xG5x7meC9Q4Ff_:b-59ltpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7f423b5ca0c7eba95ee6286df5efe092a56982/pkg/cmd/roachtest/tests/failover.go#L83)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This is a different test than the ones below that use `clusterOpts`. This one doesn't need conditional options.
</blockquote></details>

Yep - as Erik mentioned, this test also needs it.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108115#-Nazks7R4vyN8ymsIMhA:-Nb0q6Ft7M-YRgJwRS6I:b-8b11j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed7f423b5ca0c7eba95ee6286df5efe092a56982/pkg/cmd/roachtest/tests/failover.go#L133)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: let's add a comment for why we set this.
</blockquote></details>

Added

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker, srosenberg

**Comment by erikgrinaker** [comment]
bors retry

**Comment by erikgrinaker** [comment]
blathers backport 23.1

**Pull request merged**
