### PR TITLE
kv: support gradual rollout of Leader leases

### LINKED ISSUE #125237: kv: add Leader lease settings
Part of https://github.com/cockroachdb/cockroach/issues/123847.

Add cluster settings for Leader leases.

Jira issue: CRDB-39329

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by nvb**
Fixes #125237.

This commit adds a pair of new cluster settings:
* `kv.raft.leader_fortification.fraction_enabled`
* `kv.leases.leader_leases.enabled`

The first is a public setting which controls the fraction of ranges for which the raft leader fortification protocol is enabled. Leader fortification is needed for a range to use a Leader lease. It can be set to 0.0 to disable leader fortification and, by extension, Leader leases. It can be set to 1.0 to enable leader fortification for all ranges and, by extension, use Leader leases for all ranges which do not require expiration-based leases. It can be set to a value between 0.0 and 1.0 to gradually roll out Leader leases across the ranges in a cluster.

The second is a private setting which controls whether leader leases are enabled for range which use the raft leader fortification protocol. The setting is private because most users should interact with
kv.raft.leader_fortification.fraction_enabled instead. The setting is only available for rare cases where an operator wants to disable leader leases without disabling the raft leader fortification.

Release note: None

### CODE REVIEW

**Review by miraradeva — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-:-O46o7Rv4tClPSqMBDjZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46hdCYDOKMqpmq2ut0):*
nit: "ranges"
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46hpXGDUaIr-4qwmIs:-O46hpXGDUaIr-4qwmIt:b-a1ickz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_range_lease.go#L102)):*
> ```Go
> 	settings.SystemOnly,
> 	"kv.leases.leader_leases.enabled",
> 	"controls whether leader leases are enabled for range which use the raft leader "+
> ```

nit: "range"
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46jtpc6KNGDzLUMShN:-O46jtpc6KNGDzLUMShO:b-xgro9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_range_lease.go#L1016)):*
> ```Go
> // lease's expiration (and stasis period).
> func (r *Replica) checkRequestTimeRLocked(now hlc.ClockTimestamp, reqTS hlc.Timestamp) error {
> 	var leaseRenewal time.Duration
> ```

The first case below is for epoch leases, and the second seems to be for expiration leases. Do leader leases also belong in that second case? Wouldn't the leader lease equivalent be something derived from the liveness interval of store liveness?
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46lA_L3oNkL3tHkMME:-O46lA_L3oNkL3tHkMMF:b-r2ztk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_store_liveness.go#L99)):*
> ```Go
> 	// introduce a new version (V24_3_StoreLivenessEnabled); this can only happen
> 	// once https://github.com/cockroachdb/cockroach/pull/128616 lands.
> 	storeLivenessEnabled := r.store.ClusterSettings().Version.IsActive(context.TODO(), clusterversion.V24_2_LeaseMinTimestamp)
> ```

Just noticed the comment above. So, what we really want here is a check for: (1) the future version gate `V24_3_StoreLivenessEnabled`, and (2) the future `SupportManager` cluster setting for store liveness? And this is the only place where we check either of them, right? If so, I can change this as part of the `SupportManager` PR.
___
*[`pkg/kv/kvserver/replica_store_liveness_test.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46mg6yEXkQGp6OyxsS:-O46mg6yEXkQGp6OyxsT:b-ttkamm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_store_liveness_test.go#L77)):*
> ```Go
> 	}
> 
> 	// Test panic on invalid fracEnabled.
> ```

Maybe test with different precisions of `fracEnabled`? E.g. `0.0001`, `0.001`, `0.01`, `0.1`.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-:-O47ZKwT25cNY9scDB9L:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46lA_L3oNkL3tHkMME:-O47XxqCBaLEFGstoRFI:b-vq34sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_store_liveness.go#L99)):*
>  (1) the future version gate `V24_3_StoreLivenessEnabled`

That should already exist and be in now that https://github.com/cockroachdb/cockroach/pull/128616 is in. (This PR needs a rebase)

I think we want to move this version gate into the SupportManager. We'd then only want to consult the store liveness cluster setting if the version check passes.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-:-O4Bz3663YduTIOSbgEM:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani and @miraradeva)

___
*[`-- commits` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46hdCYDOKMqpmq2ut0):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

nit: "ranges"
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46hpXGDUaIr-4qwmIs:-O4BwnU6ChruGx5aZPlK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_range_lease.go#L102)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

nit: "range"
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46jtpc6KNGDzLUMShN:-O4Bwq0A-m2r0M2Ulwr0:b-pmyb20) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_range_lease.go#L1016)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

The first case below is for epoch leases, and the second seems to be for expiration leases. Do leader leases also belong in that second case? Wouldn't the leader lease equivalent be something derived from the liveness interval of store liveness?
</blockquote></details>

If we allow the liveness interval for store liveness to differ from the regular `RangeLeaseDuration`, then yes. I'll add a TODO here for when we decide how we want to configure the store liveness manager.
___
*[`pkg/kv/kvserver/replica_store_liveness.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46lA_L3oNkL3tHkMME:-O4BwLh04bhQ29CNEHEq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_store_liveness.go#L99)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

>  (1) the future version gate `V24_3_StoreLivenessEnabled`

That should already exist and be in now that https://github.com/cockroachdb/cockroach/pull/128616 is in. (This PR needs a rebase)

I think we want to move this version gate into the SupportManager. We'd then only want to consult the store liveness cluster setting if the version check passes.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_store_liveness_test.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128815#-O46mg6yEXkQGp6OyxsS:-O4Bz1sI-ksjCQFvwrA6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5248090d024416a209d6102b87c345f1d8085062/pkg/kv/kvserver/replica_store_liveness_test.go#L77)):*
<details><summary><i>Previously, miraradeva (Mira Radeva) wrote…</i></summary><blockquote>

Maybe test with different precisions of `fracEnabled`? E.g. `0.0001`, `0.001`, `0.01`, `0.1`.
</blockquote></details>

Done.

**Pull request merged**
