### PR TITLE
opt: support for EXPLAIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: introduce and build ExplainOp

The ExplainOp must remember the physical props required by the
underlying query.

For now we only support `EXPLAIN (VERBOSE)`.

Release note: None

#### opt: execbuild support for EXPLAIN

Release note: None

#### opt: remove exec-explain

Remove the `exec-explain` directive and convert all the tests to exec
an EXPLAIN statement. Add `hide-columns` option to suppress the header
with the column names and types, for cleaner output (and to avoid a
ton of diffs in this change).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LB77u0E7MdC3cOWsZU2:-LB7j-H5AHjh2J62dBOd:bf60r49) ([raw file](https://github.com/cockroachdb/cockroach/blob/25aab08d453e332c5e7b56df64f9635c5ac45596/pkg/sql/opt/memo/logical_props_builder.go#L370)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Is it OK that stats aren't initialized?
</blockquote></details>

I figured a zero row count is fine, but maybe I should be more explicit about that

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 370 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LB77u0E7MdC3cOWsZU2:-LB8EMVXDgvDxgqFPXhd:bscyzau) ([raw file](https://github.com/cockroachdb/cockroach/blob/25aab08d453e332c5e7b56df64f9635c5ac45596/pkg/sql/opt/memo/logical_props_builder.go#L370)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I figured a zero row count is fine, but maybe I should be more explicit about that
</blockquote></details>

Added a comment. Also added a comment in the coster.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 113 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBI3nM_4lSYX3cMRPS_:-LBIN7dzBM7I23WQJym5:b-cmkx5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c8c35a49acfb6f2d3cc102f31d0fc12f2f78e3/pkg/sql/opt/exec/execbuilder/builder_test.go#L113)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'd call this "hide-column-names", and the variable `hideColumnNames`. As is, it sounds like you're hiding entire columns, when in fact you're just hiding the first row.
</blockquote></details>

I also considered `noheader` which is shorter (but still a bit cryptic), what do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
TFTRs.

---

Review status: 19 of 35 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/opt/exec/execbuilder/builder_test.go, line 113 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBI3nM_4lSYX3cMRPS_:-LBM0ZnP22ZUpWU5WaB7:b-sqmi1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c8c35a49acfb6f2d3cc102f31d0fc12f2f78e3/pkg/sql/opt/exec/execbuilder/builder_test.go#L113)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Hmm it's not bad, but I still think `hide-column-names` is clearer. If you want something shorter, maybe `hide-colnames` would be better?
</blockquote></details>

Ok, switched to `hide-colnames`. I like it because the logictests use a `colnames` directive (which does the opposite).

---

*[pkg/sql/opt/memo/private_storage.go, line 206 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBHyb1j4smFBvDP1f3C:-LBM0tdC89Q_PW87ai0B:b-b5nzgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/42313d8846ba7ec05ce27e2393c6ec3f9a9d8feb/pkg/sql/opt/memo/private_storage.go#L206)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

that -> that can

[nit] why not just copy the comment that's used everywhere else?
</blockquote></details>

Done. In an initial implementation, I just interned the pointer so the rest of the comment wasn't valid. It is now though.

---

*[pkg/sql/opt/optbuilder/scope.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBI0MeC4WLPTkZK1XRZ:-LBM1Q1z-7JjHdbg75Q_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42313d8846ba7ec05ce27e2393c6ec3f9a9d8feb/pkg/sql/opt/optbuilder/scope.go#L96)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I like this encapsulation. But now that you've made this change, is `makePresentation` used anywhere else? If not, maybe just inline it here.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/physprops/ordering, line 292 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBI1LTu2i6Ew0s2jn7H:-LBM1VcSBf5oukjhRAPS:bt36eww) ([raw file](https://github.com/cockroachdb/cockroach/blob/42313d8846ba7ec05ce27e2393c6ec3f9a9d8feb/pkg/sql/opt/xform/testdata/physprops/ordering#L292)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there any way you can avoid printing the physical props twice here?
</blockquote></details>

This was actually helpful while implementing, at some point the properties weren't passed through properly and these differed. I doubt we'll be looking at memos with `EXPLAIN` much, so I'd lean towards leaving it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-:-LBM48SD5S1Zkcyk97Jw:bz5maj4)*

**Comment by rytaft** [comment]
Reviewed 16 of 16 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/memo/private_storage.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBM6Jco74ZANcV3KzB2:-LBM6Jco74ZANcV3KzB3:b-kixegd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fbb8e7d8e68bebaaed379a7b4ebc86d684a4b8d/pkg/sql/opt/memo/private_storage.go#L206)):*
> ```Go
> }
> 
> // internExplainJoinDef adds the given value to storage and returns an id that
> ```

internExplainJoinDef  -> internExplainOpDef

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/memo/private_storage.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBM6Jco74ZANcV3KzB2:-LBM7QHXDZsD4Bp6RE0J:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fbb8e7d8e68bebaaed379a7b4ebc86d684a4b8d/pkg/sql/opt/memo/private_storage.go#L206)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

internExplainJoinDef  -> internExplainOpDef
</blockquote></details>

Thanks, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by rytaft** [comment]
Review status: 34 of 35 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/memo/private_storage.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBM6Jco74ZANcV3KzB2:-LBM9FE6A7VUH6ScDxsx:bn0tyxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fbb8e7d8e68bebaaed379a7b4ebc86d684a4b8d/pkg/sql/opt/memo/private_storage.go#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Thanks, done.
</blockquote></details>

Now you got rid of the Op... :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/memo/private_storage.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBM6Jco74ZANcV3KzB2:-LBMB0qe0Gz-oMCbVbwo:b-p8ylr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fbb8e7d8e68bebaaed379a7b4ebc86d684a4b8d/pkg/sql/opt/memo/private_storage.go#L206)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Now you got rid of the Op... :)
</blockquote></details>

Haha, sorry, thanks for checking

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/memo/private_storage.go, line 206 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-LBM6Jco74ZANcV3KzB2:-LBMBD9uBb3IpQAY8jnS:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fbb8e7d8e68bebaaed379a7b4ebc86d684a4b8d/pkg/sql/opt/memo/private_storage.go#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Haha, sorry, thanks for checking
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126)*

**Comment by RaduBerinde** [comment]
bors r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25126#-:-LBMGfhv2AW5_-oj2I5q:b-ydi9ay)*

**Pull request merged**
