### PR TITLE
sql/pgwire: support explicitly closing in-progress portals

### LINKED ISSUE #39524: sql: support for closing wire protocol portals before exhaustion
#39085 delivered an implementation of row count limits on portals that doesn't permit clients to close portals before exhaustion.

This feature is almost certainly in common use, and is easily reproduced with a Java test. We need to deliver a solution for this for 19.2.

### PR DESCRIPTION
**Pull request by madelynnblue**
This is done by extending stmtBuf a bit so we can utilize its rewind
functionality when we see a portal close message.

Closes #39524

Release note (sql change): Support explicitly closing portals over the
wire after partial use.

### CODE REVIEW

**Comment by awoods187** [comment]
its great to have this functionality!

**Review by andreimatei — COMMENTED** [review]
LGTM

consider moving the `StmtBuf` to its own package. Ever since pgwire started using it, I think it doesn't belong in `sql` any more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39639#-:-LmCQQ1kC70ZpA3q69YN:b-hnjnjw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

**Comment by mjibson** [comment]
I'll move it in a subsequent PR.

**Comment by mjibson** [comment]
For posterity: an initial attempt to move stmtbuf to its own package revealed that this would be a fairly annoying change since CmdPos and Command would also need to move over, and the Command interface has a `command()` func, implying that all commands would also need to move. Things are fine for now.

**Pull request merged**
