### PR TITLE
kvserver: avoid hanging proposal after leader goes down 

### LINKED ISSUE #38829: roachtest: gossip/chaos/nodes=9 failed
SHA: https://github.com/cockroachdb/cockroach/commits/07607a73daedbf57f47e42e2e3d6cfd529ab65a5

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=gossip/chaos/nodes=9 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1382906&tab=buildLog

```
The test failed on branch=release-19.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190711-1382906/gossip/chaos/nodes=9/run_1
	test_runner.go:693: test timed out (10h0m0s)

```

### PR DESCRIPTION
**Pull request by tbg**
Deflakes gossip/chaos/nodes=9, i.e.

Fixes #38829.

There was a bug in range quiescence due to which commands would hang in
raft for minutes before actually getting replicated. This would occur
whenever a range was quiesced but a follower replica which didn't know
the (Raft) leader would receive a request.  This request would be
evaluated and put into the Raft proposal buffer, and a ready check would
be enqueued. However, no ready would be produced (since the proposal got
dropped by raft; leader unknown) and so the replica would not unquiesce.

This commit prevents this by always waking up the group if the proposal
buffer was initially nonempty, even if an empty Ready is produced.

It goes further than that by trying to ensure that a leader is always
known while quiesced. Previously, on an incoming request to quiesce, we
did not verify that the raft group had learned the leader's identity.

One shortcoming here is that in the situation in which the proposal
would originally hang "forever", it will now hang for one heartbeat
or election timeout where ideally it would be proposed more reactively. Since
this is so rare I didn't try to address this. Instead, refer to
the ideas in

https://github.com/cockroachdb/cockroach/issues/37906#issuecomment-529041377

and

https://github.com/cockroachdb/cockroach/issues/21849

for future changes that could mitigate this.

Without this PR, the test would fail around 10% of the time. With this
change, it passed 40 iterations in a row without a hitch, via:

    ./bin/roachtest run -u tobias --count 40 --parallelism 10 --cpu-quota 1280 gossip/chaos/nodes=9

Release justification: bug fix
Release note (bug fix): a rare case in which requests to a quiesced
range could hang in the KV replication layer was fixed. This would
manifest as a message saying "have been waiting ... for proposing" even
though no loss of quorum occurred.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm: Thanks for tracking this down! Might want to get another set of #kv eyes on this in order to spread the knowledge.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-:-M2FFzvM1JH5NobyLf3j:b-y576uk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

**Review by nvb — APPROVED** [review]
:lgtm: nice find! How far back do we need to backport this?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-:-M2FmaseBAP63KvxD63e:b-xtm4ff)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/replica_raft.go, line 415 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-M2Fk3Uo8cfplvdDHf41:-M2Fk3Up6f1IWvPQ-usr:b7pjfnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4b0afa94695fa321d89b380806599c484dd782/pkg/kv/kvserver/replica_raft.go#L415)):*
> ```Go
> 	err := r.withRaftGroupLocked(true, func(raftGroup *raft.RawNode) (bool, error) {
> 		numFlushed := r.mu.proposalBuf.Len()
> 		if err := r.mu.proposalBuf.FlushLockedWithRaftGroup(raftGroup); err != nil {
> ```

I would lean towards returning the number of commands that were flushed from this function (i.e. `used` in `FlushLockedWithRaftGroup`). That avoids extra atomic accesses that seem a little racy, though I can't construct a scenario where anything actually goes wrong.
___
*[pkg/kv/kvserver/replica_raft.go, line 415 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-M2FlO4V5fj_QRIwnRFo:-M2FlO4V5fj_QRIwnRFp:b3epbau) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4b0afa94695fa321d89b380806599c484dd782/pkg/kv/kvserver/replica_raft.go#L415)):*
> ```Go
> 	err := r.withRaftGroupLocked(true, func(raftGroup *raft.RawNode) (bool, error) {
> 		numFlushed := r.mu.proposalBuf.Len()
> 		if err := r.mu.proposalBuf.FlushLockedWithRaftGroup(raftGroup); err != nil {
> ```

An alternative approach is to propagate `raft.ErrProposalDropped` errors up to here and unquiesce in that case as well. I'll defer to your preference.
___
*[pkg/kv/kvserver/store_raft.go, line 230 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-M2FmSg_2_rBSz5vFbyZ:-M2FmSga2XPbOHFEu5It:b-hpddcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4b0afa94695fa321d89b380806599c484dd782/pkg/kv/kvserver/store_raft.go#L230)):*
> ```Go
> 		// quiescing if there's outstanding work.
> 		r.mu.Lock()
> 		status := r.raftStatusRLocked()
> ```

Would the `BasicStatus()` do?

**Review by tbg — COMMENTED** [review]
bors r=nvanbenschoten,petermattis

> How far back do we need to backport this?

I don't see why this wasn't always a problem (though the roachtest didn't always fail...)
I'll definitely backport to 19.2 and there should be a similar simplified patch we can make to 19.1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-:-M2_NeeQ2lqk7AhxRyR1:bgsf7zm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/kv/kvserver/replica_raft.go, line 415 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46045#-M2FlO4V5fj_QRIwnRFo:-M2_4KwtEtNcIXG0PH0D:bobht24) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec4b0afa94695fa321d89b380806599c484dd782/pkg/kv/kvserver/replica_raft.go#L415)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

An alternative approach is to propagate `raft.ErrProposalDropped` errors up to here and unquiesce in that case as well. I'll defer to your preference.
</blockquote></details>

I'll leave as is.

**Comment by tbg** [comment]
bors pls

bors r=nvanbenschoten,petermattis

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46045)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
