### PR TITLE
distsql: implement aggregation

### PR DESCRIPTION
**Pull request by irfansharif**
Implementation of the `Aggregator` processor core type, working for the aggregation functions `SUM`, `COUNT`, `MIN`, `MAX`, `AVG`, `DISTINCT`, `COUNT DISTINCT`. This adds 'local' and 'final' aggregation.

cc @RaduBerinde, @dt 
Part of #7587.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9793)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @andreimatei 

I will look into more detail, but I have a general comment: we don't have to handle arbitrary "select" and "group by" expressions in this processor; we don't want that kind of logic duplicated in all processors. We will have a separate processor (we called it `program` in the RFC) that can add columns to streams with results from expressions, which will be used as necessary. So the aggregation processor can assume that whatever values it needs are already in the input stream. We will always use a column for each aggregation function for each aggregation function, and a set of columns for the grouping. The aggregating functions (SUM, COUNT) should be defined in the proto, they will be specified directly (not through an expression).

As an analogy, SQL supports `ORDER BY (a+b)` but our sorting processor does not; we would use `program` to generate a column with the values for `a+b`, and then we would run the sorting processor with an ordering for that column.

Some of the work you did around expressions will be useful to implement `program`, so we should save a copy of the branch.


Another thing I want to note is that there will be no distinction between a local aggregating processor and a final one. We would simply use them with different functions. For example to implement `COUNT`, the local aggregator will use the COUNT function; the final aggregator will use the SUM function to sum the counts. From the perspective of the physical plan and components, the two processors don't know or care about each other. It's up to the physical planner to choose the functions so that the end result corresponds to whatever function is in the logical plan.

**Comment by irfansharif** [comment]
@dt: feel free to unassign yourself from this, will most likely move over the expression handling into a separate processor in the future (see `program` above`.

@RaduBerinde: just a general question, for a `COUNT DISTINCT` if your rows are distributed over multiple nodes you would need the 'local' stages (occurring on each node) to output the `DISTINCT` rows and in the 'final' stage you would need to aggregate `DISTINCT` rows received from *all* input sources then run a `COUNT` over the results. in this scenario, the external compiler responsible for instructing the separate nodes to carry out the separate stages with the separate instructions (i.e. setting up the flow), where is this going to be?

**Comment by andreimatei** [comment]
For the `COUNT DISTINCT`, the logical plan should have a `COUNT` node and a `DISTINCT` node (this probably doesn't correspond to the plan nodes we have today), and then the physical plan might have a single-phase `COUNT` processor and a two-phase `DISTINCT` processor (or if we're smart, we can maybe fuse the 2nd stage DISTINCT with the COUNT).
Both logical planning and physical planning are... fledgling.

**Comment by irfansharif** [comment]
if the query is `SELECT 1 FROM kv GROUP BY v`, are we designing `program` such that it will emit literal `1`'s? i.e. emit rows with values `(1, v)`? and consequently have the `aggregator` constructed with `GROUP BY $1` and `SELECT $0`?
I ask this because this would mean a simpler implementation of aggregator with no need to parse out expressions but simply being passed the aggregation function and the column index to aggregate on.

**Comment by RaduBerinde** [comment]
Yes, in that case the program will receive a stream of `(v)`s and emit a stream of `(1, v)`s. The aggregator should not do anything with expressions (other than an output filter, which most processors should support).

**Comment by irfansharif** [comment]
> Basic implementation of the `Aggregator` processor core type, working currently only for a subset of the aggregation functions (`SUM` and `COUNT`) and limited to only local aggregation with one input and one output stream.
A bulk of this PR is a blatant rewrite of `sql/group.go` with commonalities such `aggregateFuncHolder` and `extractAggregatesVisitor`, we expect the spec to contain expressions with the column names passed along as indexed variables (`$1`, `$0`, etc) therefore the equivalent of `qvalues` as found in `package sql` is `parser.IndexedVar`. 
This should serve well as an initial implementation but not comfortable with the `parser` package being so tightly coupled to `distsql`, it'd be best to get a discussion going on how to go about decoupling the two packages by possibly tacking more onto the aggregator spec proto.

Update: Made the changes necessary to pull out changes specific to the `program` processor core type out of this PR, will follow up with that implementation shortly.

**Comment by RaduBerinde** [comment]
Thanks for the update Irfan, this is progressing very quickly!

The specification of the aggregator looks good!

There is one thing that's amiss - the aggregator processor core has a single input. The only processor cores that have multiple inputs are related to joins. Note that a single input can have multiple input streams - but they all have the same "schema" and are merged into a single input through an input synchronizer (and that's what the processor's `Run()` receives).

This should simplify the code a bit. Note that `ag.next()` model (especially after this simplification) is a bit convoluted - it  follows the one-row-at-a-time interface that existing sql code has, but we don't need to stick to that. We are running the entire processor loop so we can have a separate data accumulation stage and then a data rendering and row output stage.

---

Review status: 0 of 18 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[sql/distsql/aggregator.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp5J2tdfF4Y7TXHwEo:-KTp5J2uJm6wJhISmCRF:bz9e7o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L65)):*
> ```Go
> 		inputs:   inputs,
> 		output:   output,
> 		ctx:      log.WithLogTag(ctx.Context, "Aggregator", nil),
> ```

these get prepended to all logs so shorter is better, maybe just "agg"

---

*[sql/distsql/aggregator.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp5e0OHVtQfq-DKuXk:-KTp5e0OHVtQfq-DKuXl:bq9a8tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L69)):*
> ```Go
> 	}
> 
> 	ag.render = make(columns, len(spec.SelectExprs))
> ```

this does not describe what we are rendering, maybe `inputCols`

---

*[sql/distsql/aggregator.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp6cnN6vtzqhRSTsU7:-KTp6cnN6vtzqhRSTsU8:b-bu5dkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L241)):*
> ```Go
> 
> // extract returns a tuple comprised of the indexes specified by render and the group key.
> func (ag *aggregator) extract(row sqlbase.EncDatumRow) (parser.DTuple, parser.DTuple) {
> ```

We are building the first DTuple here just to loop over it. We don't need to do that, we can just loop over `g.groupKey` directly.

---

*[sql/distsql/aggregator.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp67UsLlbcXSh_xB0i:-KTp67UsLlbcXSh_xB0j:b-8bj3hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L244)):*
> ```Go
> 	tuple := make(parser.DTuple, len(ag.render)+len(ag.groupKey))
> 	for i, colIdx := range ag.render {
> 		tuple[i] = row[colIdx].Datum
> ```

before we can access `Datum`, we need to call `Decode()`.

---

*[sql/distsql/aggregator.go, line 264 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp7eejTFIFbfTMIz_G:-KTp7eejTFIFbfTMIz_H:b-o8oimf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L264)):*
> ```Go
> 	}
> 
> 	p := &parser.FuncExpr{
> ```

What we're doing here is ingenious but needs a comment. We are relying on the fact that each name in the enum matches a SQL function known to the parser.

---

*[sql/distsql/aggregator.go, line 267 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp7YclV9mTMm7qqeLT:-KTp7YclV9mTMm7qqeLU:b89kpx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L267)):*
> ```Go
> 		Name: parser.NormalizableFunctionName{
> 			FunctionName: &parser.QualifiedFunctionName{
> 				FunctionName: parser.Name(AggregatorSpec_Func_name[int32(expr.Func)]),
> ```

why not `expr.Func.String()`?

---

*[sql/distsql/processors.proto, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2AcIzDI9tPS_DRoT:-KTp2AcIzDI9tPS_DRoU:b-i91snm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L147)):*
> ```protobuf
>   }
> 
>   message SelectExpr {
> ```

We shouldn't use `Select`, maybe just `Expr` since it's already nested inside AggregationExpr.

---

*[sql/distsql/processors.proto, line 149 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2PRp8sDbUO4DiS9i:-KTp2PRp8sDbUO4DiS9j:bz91u4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L149)):*
> ```protobuf
>   message SelectExpr {
>     optional Func func = 1 [(gogoproto.nullable) = false];
>     optional bool distinct = 2 [(gogoproto.nullable) = false];
> ```

This needs explanation. How does it affect the results and how does it interact with the function? E.g. what's `SUM` with `distinct=true`?

---

*[sql/distsql/processors.proto, line 150 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2RgMOvrrGA58eQ39:-KTp2RgMOvrrGA58eQ3A:br28uer) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L150)):*
> ```protobuf
>     optional Func func = 1 [(gogoproto.nullable) = false];
>     optional bool distinct = 2 [(gogoproto.nullable) = false];
>     optional uint32 col_idx = 3 [(gogoproto.nullable) = false];
> ```

This needs a comment (it describes the "argument" to the agg func).

---

*[sql/distsql/processors.proto, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp3mRivKvdLowupcI3:-KTp3mRivKvdLowupcI4:b-u8n17r) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L155)):*
> ```protobuf
>   repeated sqlbase.ColumnType.Kind types = 1 [(gogoproto.nullable) = false];
> 
>   // GroupKey is a subset of the columns in the input stream schema on the
> ```

It's confusing that the name doesn't match the actual name in the proto. I would just not mention the name at all (that's how we seem to do it e.g. in `roachpb/data.go`)

---

*[sql/distsql/processors.proto, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp3X4oZToZwQkCpa8o:-KTp3X4oZToZwQkCpa8p:bk5y4eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L157)):*
> ```protobuf
>   // GroupKey is a subset of the columns in the input stream schema on the
>   // basis of which we define our groups.
>   repeated uint32 group_key = 2 [(gogoproto.nullable) = false];
> ```

group_key_cols or group_cols

---

*[sql/distsql/values.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp1SukU5RN0yqj1ynr:-KTp1SukU5RN0yqj1yns:b-g50r8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/values.go#L23)):*
> ```Go
> )
> 
> type values struct {
> ```

What is the use of this type? Is it implementing some interface? If so add a `var _ Interface = &values{}`. If not, it doesn't seem to add much value (we could just use `EncDatumRows` and do the slice operations directly); also why the `error` in the functions?

The name is maybe a bit too generic too.

Consider putting it in `base.go` where we have misc  small stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KTp8Ri3LE280qJuyCdv:be8e100)*

**Comment by irfansharif** [comment]
I've changed it somewhat to reflect this, could you confirm it is what you had in mind?

---

Review status: 0 of 17 files reviewed at latest revision, 12 unresolved discussions.

---

*[sql/distsql/aggregator.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp5J2tdfF4Y7TXHwEo:-KTu8s3iAvJZlgiTmtzi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> these get prepended to all logs so shorter is better, maybe just "agg"
</details>
Done.

---

*[sql/distsql/aggregator.go, line 69 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp5e0OHVtQfq-DKuXk:-KTu9-XNhGdjVr7CbyJj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L69)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this does not describe what we are rendering, maybe `inputCols`
</details>
Done.

---

*[sql/distsql/aggregator.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp6cnN6vtzqhRSTsU7:-KTyuK5MRlKCuezcpE3m:b-ylyf4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L241)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We are building the first DTuple here just to loop over it. We don't need to do that, we can just loop over `g.groupKey` directly.
</details>
I'm not sure I completely understand this, but I did move away the `tuple` allocation to be done just the one time. does this still apply?

---

*[sql/distsql/aggregator.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp67UsLlbcXSh_xB0i:-KTu9YoECm1tr0nhSgYq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> before we can access `Datum`, we need to call `Decode()`.
</details>
Done.

---

*[sql/distsql/aggregator.go, line 264 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp7eejTFIFbfTMIz_G:-KTyxXLGL1nbQkyPPuD9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L264)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What we're doing here is ingenious but needs a comment. We are relying on the fact that each name in the enum matches a SQL function known to the parser.
</details>
Done.

---

*[sql/distsql/aggregator.go, line 267 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp7YclV9mTMm7qqeLT:-KTybDFvZemBjBltOqy-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L267)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> why not `expr.Func.String()`?
</details>
Done.

---

*[sql/distsql/processors.proto, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2AcIzDI9tPS_DRoT:-KTyxcMUY3u-8nD1x-xU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L147)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We shouldn't use `Select`, maybe just `Expr` since it's already nested inside AggregationExpr.
</details>
Done.

---

*[sql/distsql/processors.proto, line 149 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2PRp8sDbUO4DiS9i:-KTzRBxuOfh9AaY4jBJf:b-ou5shk) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L149)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This needs explanation. How does it affect the results and how does it interact with the function? E.g. what's `SUM` with `distinct=true`?
</details>
`SUM` with `distinct = true` functions like you would expect `SUM DISTINCT` to function. This was taken from `parser.FuncExpr.Type` (`DISTINCT|ALL`) and the behaviour that follows. Documented.

---

*[sql/distsql/processors.proto, line 150 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp2RgMOvrrGA58eQ39:-KTyxretoiu3EFL8KmkJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L150)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This needs a comment (it describes the "argument" to the agg func).
</details>
Done.

---

*[sql/distsql/processors.proto, line 155 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp3mRivKvdLowupcI3:-KTyxvGFHFAqy0FsZAbr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L155)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's confusing that the name doesn't match the actual name in the proto. I would just not mention the name at all (that's how we seem to do it e.g. in `roachpb/data.go`)
</details>
Done.

---

*[sql/distsql/processors.proto, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp3X4oZToZwQkCpa8o:-KTyy2_i-HuVmG1tvT9d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/processors.proto#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> group_key_cols or group_cols
</details>
Done.

---

*[sql/distsql/values.go, line 23 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp1SukU5RN0yqj1ynr:-KTz4QvV1kfg_EJ9aFhq:b-lqk5rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/values.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What is the use of this type? Is it implementing some interface? If so add a `var _ Interface = &values{}`. If not, it doesn't seem to add much value (we could just use `EncDatumRows` and do the slice operations directly); also why the `error` in the functions?
> 
> The name is maybe a bit too generic too.
> 
> Consider putting it in `base.go` where we have misc  small stuff.
</details>
The reason I pulled this out into a separate `values.go` was because I need some sort of row store for this and `sorter`. I've changed this now to use `RowBuffer` here and just a simple `rows sqlbase.EncDatumRows`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KTzF6MF_Zuv_erjChA8:b4znss6)*

**Comment by RaduBerinde** [comment]
Yeah I looked briefly and it looks good overall. I will do one more pass over the change (the rebase with pkg/ is throwing off reviewable so I can't easily see the partial diffs).

---

Review status: 0 of 17 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KTzn0rnWSO47i7bSYhL:b-nl5prd)*

**Comment by irfansharif** [comment]
yea, had that issue as well. let me know okay to merge.

---

Review status: 0 of 17 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KUI5EpqxFOzMa8Z4asL:b-ewymew)*

**Comment by RaduBerinde** [comment]
Sorry for the delay, a couple of comments, otherwise :lgtm:

---

Review status: 0 of 17 files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/aggregator.go, line 181 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJefow5OMYWbhe067U:-KUJefoxa4viNE3Va_hI:bdmgndu) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L181)):*
> ```Go
> 	// Render the results.
> 	for bucket := range ag.buckets {
> 		tuple := make(parser.DTuple, 0, len(ag.inputCols))
> ```

do we need to reallocate this each time? we could just do `tuple = tuple[:0]`. Also why `len(ag.inputCols)` when we're appending `len(ag.funcs)` below?

---

*[pkg/sql/distsql/aggregator.go, line 187 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJf3Ix1NFOkyu42mEb:-KUJf3Ix1NFOkyu42mEc:bpgi4nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L187)):*
> ```Go
> 		}
> 
> 		row, err := sqlbase.DTupleToEncDatumRow(tuple)
> ```

We should be using an [EncDatumRowAlloc](https://github.com/cockroachdb/cockroach/blob/6bdffebff3b51a0a4da1138fe4c8d6bc42e6bcb0/pkg/sql/sqlbase/encoded_datum.go#L287) here (we could pass it to the function)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KUJfRyRM2om1VZfcu7B:b-f46gb3)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 17 files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/aggregator.go, line 161 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJkb-HYV1JQkkRn30g:-KUJkb-HYV1JQkkRn30h:b-1d3av8) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L161)):*
> ```Go
> 		}
> 
> 		encoded, err := sqlbase.EncodeDTuple(scratch, groupedValues)
> ```

As I mentioned in the other PR, we should use the `EncDatum` encoding infrastructure instead of going through `DTuple`. Feel free to leave a TODO and file an issue though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793)*

**Comment by irfansharif** [comment]
TFTR!

---

Review status: 0 of 18 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/aggregator.go, line 161 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJkb-HYV1JQkkRn30g:-KUO8ubltHZpOu_zDAgb:bx3tnqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L161)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> As I mentioned in the other PR, we should use the `EncDatum` encoding infrastructure instead of going through `DTuple`. Feel free to leave a TODO and file an issue though.
</details>
Done (left a TODO, will clean up with the other follow up PR right after).

---

*[pkg/sql/distsql/aggregator.go, line 181 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJefow5OMYWbhe067U:-KUO9zVpJd-ToKYkOauY:bljiek) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L181)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> do we need to reallocate this each time? we could just do `tuple = tuple[:0]`. Also why `len(ag.inputCols)` when we're appending `len(ag.funcs)` below?
</details>
Done.
also `len(ag.inputCols) == len(ag.funcs)` but changed for clarity. 

---

*[pkg/sql/distsql/aggregator.go, line 187 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJf3Ix1NFOkyu42mEb:-KUOEggy1TyedE71DLjA:b586nzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We should be using an [EncDatumRowAlloc](https://github.com/cockroachdb/cockroach/blob/6bdffebff3b51a0a4da1138fe4c8d6bc42e6bcb0/pkg/sql/sqlbase/encoded_datum.go#L287) here (we could pass it to the function)
</details>
Done, changed the function signature to `func DTupleToEncDatumRow(EncDatumRow, parser.DTuple) (EncDatumRow, error)` returning the original slice despite not having changed it (via `append`, etc.). not sure what the standard conventions around this are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KUOG38uA2IKfVB8PZam:b-814g8k)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/aggregator.go, line 187 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJf3Ix1NFOkyu42mEb:-KUOjOy-tiS5X6A-72Xj:b-zfymv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L187)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> Done, changed the function signature to `func DTupleToEncDatumRow(EncDatumRow, parser.DTuple) (EncDatumRow, error)` returning the original slice despite not having changed it (via `append`, etc.). not sure what the standard conventions around this are.
</details>
Since we don't modify it, we don't need to return it. We should check that it has the right length though (and panic if not).

---

*[sql/distsql/aggregator.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp6cnN6vtzqhRSTsU7:-KUOkB5bvDyXQP51k0q2:b4i50go) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L241)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> I'm not sure I completely understand this, but I did move away the `tuple` allocation to be done just the one time. does this still apply?
</details>
We create `aggregatedValues` but we only use it to loop over it once. We could just loop over `ag.render` and get the `Datum` where we use it. Just seems like this intermediary step to store all values in a tuple is extraneous. This will apply to the other returned tuple as well once we stop using EncodeDTuple and just call `Encode` on each value. I'm guessing the `extract()` function might just go away then anyway.
Fine to keep as is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-:-KUOjaztZKjo9WoccsKm:bnfp4nl)*

**Comment by irfansharif** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/aggregator.go, line 187 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KUJf3Ix1NFOkyu42mEb:-KUPnbTfk4FI4SMm-omj:brq7jse) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbb14a7141b3d9d832f313bb8b556e5ca7f91c3/pkg/sql/distsql/aggregator.go#L187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Since we don't modify it, we don't need to return it. We should check that it has the right length though (and panic if not).
</details>
Done, returning an error instead.

---

*[sql/distsql/aggregator.go, line 241 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793#-KTp6cnN6vtzqhRSTsU7:-KUPoca935GSLej0Vmj6:b-ikah21) ([raw file](https://github.com/cockroachdb/cockroach/blob/aab774ea767a56f1a2a254796cd7dffc79db0781/sql/distsql/aggregator.go#L241)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> We create `aggregatedValues` but we only use it to loop over it once. We could just loop over `ag.render` and get the `Datum` where we use it. Just seems like this intermediary step to store all values in a tuple is extraneous. This will apply to the other returned tuple as well once we stop using EncodeDTuple and just call `Encode` on each value. I'm guessing the `extract()` function might just go away then anyway.
> Fine to keep as is for now.
</details>
i see. will swap out when swapping out `EncodeDTuple`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9793)*

**Pull request merged**
