### PR TITLE
sql: implement INET column type operators

### PR DESCRIPTION
**Pull request by mwistrom**
Release note (sql change): Implement additional INET column type operators:

- contains, contained by,  etc.

- binary opeations

- addition/subtraction

Implement the following operators for INET column types: <<, <<=, >>, >>=,
&&, +, -. ^, |, &.  These operators are the same as the operators that exists
in PostgreSQL 10 and are described in Table: 9.36 of the PostgreSQL documentation.

### CODE REVIEW

**Comment by mwistrom** [comment]
This is for #18847

**Comment by justinj** [comment]
Hi @mwistrom! Thank you for the contribution, sorry it took us a while to get back to you! It looks like the addition of the `~` operator for `INET` has made a previously unambiguous expression ambiguous. Would you mind adding an appropriate type hint to that test? It's not great in general that that's necessary and I've mentioned it to the team to see what we can do to guard against this kind of problem in the future, but I think that's the only way around it for the time being. There needs to be a type hint on the placeholder (`$1:::INT`) in the `TO_HEX` test in `TestPGPreparedQuery` I think.

The code looks great! In addition, we have a couple other kinds of tests that I think this PR would benefit from making use of. It would be good to have some tests in `TestParse2` in `parse_test.go`, and also would be good to add some logic tests (in `pkg/sql/logictest/testdata/logic_test/inet`) that test this in a fully running database scenario.

---

Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33ckmg-7FJ0hyO-CTZ:-L33ckmg-7FJ0hyO-CT_:bvrc1r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/.gitignore#L12)):*
> ```
> # https://github.com/github/gitignore/tree/master/Global
> 
> /.idea
> ```

We generally avoid checking in editor-specific files to the `.gitignore`.

---

*[pkg/sql/sem/builtins/builtins.go, line 420 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33d77jFOnZ3PsrcwPC:-L33d77jFOnZ3PsrcwPD:bxp2lqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L420)):*
> ```Go
> 		tree.Builtin{
> 			Types: tree.ArgTypes{
> 				{"val", types.INet},
> ```

These strings are the names of the parameters, so I think they shouldn't have the same name, maybe in this particular case they could be something like `container` and `containee`?

---

*[pkg/sql/sem/builtins/builtins.go, line 437 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33dI7cM89sLzXMsHih:-L33dI7cM89sLzXMsHii:b-lr0xth) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L437)):*
> ```Go
> 		tree.Builtin{
> 			Types: tree.ArgTypes{
> 				{"val", types.INet},
> ```

ditto here

---

*[pkg/sql/sem/builtins/builtins.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33dKuaoReWexSj-2IY:-L33dKuaoReWexSj-2IZ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L454)):*
> ```Go
> 		tree.Builtin{
> 			Types: tree.ArgTypes{
> 				{"val", types.INet},
> ```

ditto

---

*[pkg/sql/sem/tree/eval.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33gKy0xmikMAn8_msK:-L33gKy1YAVJZ3yJ1k6-:bdykfik) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/tree/eval.go#L848)):*
> ```Go
> 		},
> 		BinOp{
> 			// Note: postgres ver 10 does NOT have Int - INet. Throws ERROR: 42883
> ```

nit: we try to give all comments periods

---

*[pkg/sql/sem/tree/eval_test.go, line 1044 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iEAx_3opVoF99mAi:-L33iEAx_3opVoF99mAj:b-8ug2ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/tree/eval_test.go#L1044)):*
> ```Go
> 		{`'NaN'::decimal::float`, `NaN`},
> 		{`'NaN'::float::decimal`, `NaN`},
> 		// inet operations: ~ & | + - << <<= >> >>= &&
> ```

period please!

---

*[pkg/util/ipaddr/ipaddr.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iMaSBYOWYuyWpx8Y:-L33iMaSBYOWYuyWpx8Z:b-6vd04c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L73)):*
> ```Go
> // IPv4mask is used to select only the lower 32 bits of uint128
> // IPv4 addresses may not have the the upper 96 bits of Addr set to 0
> //   IPv4 addresses mapped to IPv6 have prefix bits that should not
> ```

periods needed for these comments, and also the indentation on this one is a bit off

---

*[pkg/util/ipaddr/ipaddr.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iRbZY12Dz95KROhp:-L33iRbZY12Dz95KROhq:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L77)):*
> ```Go
> const IPv4mask = uint64(0xFFFFFFFF)
> 
> // IPv4max is used for overflows
> ```

ditto

---

*[pkg/util/ipaddr/ipaddr.go, line 401 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33moPCGi36PPZx4R0A:-L33moPCGi36PPZx4R0B:b-m4n3ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L401)):*
> ```Go
> 
> func (ipAddr *IPAddr) sum(o int64, neg bool) (IPAddr, error) {
> 	// neg carries information about whether to add or subtract other
> ```

period

---

*[pkg/util/ipaddr/ipaddr.go, line 412 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iy7BLL1ue2fziB8p:-L33iy7BLL1ue2fziB8q:b-g6xniv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L412)):*
> ```Go
> 		neg = !neg
> 		// postgresql ver 10 seems to have an error with min int64
> 		// it does not handle the overflow correctly
> ```

periods and capitalization needed for these

---

*[pkg/util/ipaddr/ipaddr.go, line 476 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33jFt4dNFf1f-4OBof:-L33jFt4dNFf1f-4OBog:b-m4n3ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L476)):*
> ```Go
> 
> // ContainsOrEquals determines if one ipAddr is in the same
> // subnet as another or the addresses and subnets are equal
> ```

period

---

*[pkg/util/ipaddr/ipaddr.go, line 500 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33jHMuGYyIsiSNBWlU:-L33jHMuGYyIsiSNBWlV:bob8mai) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L500)):*
> ```Go
> 
> // ContainsOrContainedBy determines if one ipAddr is in the same
> // subnet as another or vice versa
> ```

period 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-:-L33chd2BIoI1xT6RC7V:bbwnbgk)*

**Comment by mwistrom** [comment]
Hey, you didn't take too long at all to get back to me. I think you had to release an Alpha version which is always a bit of work. Thank you for the feedback. I'll get on the changes here over the next day or so.

**Comment by mwistrom** [comment]
Review status: 0 of 16 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/builtins/builtins.go, line 420 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33d77jFOnZ3PsrcwPC:-L3dmh2UmkHpzlwQUncl:b-z9pvkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L420)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

These strings are the names of the parameters, so I think they shouldn't have the same name, maybe in this particular case they could be something like `container` and `containee`?
</blockquote></details>

For the "contained by" and "contained" operators, I would like to use "val" and "container" as appropriate for the names of the parameters. Clearly the "container" parameter is different than the IPAddr, and it would be a good idea to distinguish it from 
For the "Contained or Contained By" operation, I would like to stick with "val" and "val". 

Reason:
"val" is used in the other INET operations that already exist to represent an IPAddr. "inet_same_familty" currently uses "val" and "val" to represent two parameters that are basically the same type.

---

*[pkg/sql/sem/builtins/builtins.go, line 437 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33dI7cM89sLzXMsHih:-L3iZV3eWdCPlaeoMPS-:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L437)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

ditto here
</blockquote></details>

See above.

---

*[pkg/sql/sem/builtins/builtins.go, line 454 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33dKuaoReWexSj-2IY:-L3iZWk4G-OoZDctOaFM:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L454)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

See above.

---

*[.gitignore, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33ckmg-7FJ0hyO-CTZ:-L3dWz8Ld07hi_6OiyT5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/.gitignore#L12)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

We generally avoid checking in editor-specific files to the `.gitignore`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437)*

**Comment by justinj** [comment]
Looks good! I think you just need to rebase and re-run the docs generation (`make generate PKG=./docs/...`).

---

Review status: 0 of 16 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[pkg/sql/sem/builtins/builtins.go, line 420 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33d77jFOnZ3PsrcwPC:-L4Ca7t5rpSBYks5hM0F:bdr5wo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L420)):*
<details><summary><i>Previously, mwistrom (Mark Wistrom) wrote…</i></summary><blockquote>

For the "contained by" and "contained" operators, I would like to use "val" and "container" as appropriate for the names of the parameters. Clearly the "container" parameter is different than the IPAddr, and it would be a good idea to distinguish it from 
For the "Contained or Contained By" operation, I would like to stick with "val" and "val". 

Reason:
"val" is used in the other INET operations that already exist to represent an IPAddr. "inet_same_familty" currently uses "val" and "val" to represent two parameters that are basically the same type.
</blockquote></details>

Hm, I don't feel too strongly, but my stance would probably be that we should change `inet_same_family` to not have duplicate names :) but I'm also fine with leaving it.

---

*[pkg/util/ipaddr/ipaddr.go, line 28 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L4CacGaBKF14lWXFDO7:-L4CacGbQMdtjxdAy2-d:b7uu702) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a648b4097f8ae0600294914a366af4219a724d2/pkg/util/ipaddr/ipaddr.go#L28)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror"
> 	"github.com/cockroachdb/cockroach/pkg/util/uint128"
> 	"math"
> ```

nit: sorry for not catching this - this should go with the other stdlib package imports (I wouldn't have mentioned this but docs need regenerating anyway :smile:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-:-L4Cb7u9OXKM04t8Fhq7:b6czmgg)*

**Comment by mwistrom** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[pkg/sql/sem/builtins/builtins.go, line 420 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33d77jFOnZ3PsrcwPC:-L4E28qWXgd02Kbct_65:b-9hh18t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/builtins/builtins.go#L420)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Hm, I don't feel too strongly, but my stance would probably be that we should change `inet_same_family` to not have duplicate names :) but I'm also fine with leaving it.
</blockquote></details>

Left it as "container" and "val".  I wouldn't mind changing all of the "vals" in the inet operators to "ipAddr". That would touch most (all?) of the inet operators, which seems a bit beyond the scope of a first checkin.   :)

---

*[pkg/sql/sem/tree/eval.go, line 848 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33gKy0xmikMAn8_msK:-L3il9dSye271nnokJhC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/tree/eval.go#L848)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: we try to give all comments periods
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval_test.go, line 1044 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iEAx_3opVoF99mAi:-L3il2Zn1vVCcYBzSAFM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/sql/sem/tree/eval_test.go#L1044)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

period please!
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iMaSBYOWYuyWpx8Y:-L3ilB4rcj4mJyoI0wHr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L73)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

periods needed for these comments, and also the indentation on this one is a bit off
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 77 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iRbZY12Dz95KROhp:-L3ilBVVCsLoPfFJTk6B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L77)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 401 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33moPCGi36PPZx4R0A:-L3ilBzTse90iqKvR26H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L401)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

period
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 412 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33iy7BLL1ue2fziB8p:-L3ilCQaXIscpZHBfHiV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L412)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

periods and capitalization needed for these
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 476 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33jFt4dNFf1f-4OBof:-L3ilCqxs-BGS115TNRj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L476)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

period
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 500 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L33jHMuGYyIsiSNBWlU:-L3ilDHSjgzdKvTpeap3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f814cce41aed9587c14c51e9503ddc95ed1d392/pkg/util/ipaddr/ipaddr.go#L500)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

period 
</blockquote></details>

Done.

---

*[pkg/util/ipaddr/ipaddr.go, line 28 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437#-L4CacGaBKF14lWXFDO7:-L4E1npVnQeSUewqyRlV:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a648b4097f8ae0600294914a366af4219a724d2/pkg/util/ipaddr/ipaddr.go#L28)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: sorry for not catching this - this should go with the other stdlib package imports (I wouldn't have mentioned this but docs need regenerating anyway :smile:)
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21437)*

**Comment by justinj** [comment]
Looks great! Looks like you need a rebase on master to resolve a conflict, and if you wouldn't mind squashing your commits that would be great.

**Comment by mwistrom** [comment]
OK, resolved the conflict during the rebase on master.
Squashed the commits into one.

I hope that it is it. Of course, lemme know if there is more work to be done.

I really appreciate your help in getting the in. It was great fun!

Mark

**Comment by justinj** [comment]
Great! Thanks so much for the contribution @mwistrom!

**Pull request merged**
