### PR TITLE
cli: code clean-up and polishing

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: mod potentially making the `fooContext` types anonymous

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cli/start.go, line 280 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-Kqm5XTNaNtz8vYKROTT:-Kqm5XTNaNtz8vYKROTU:b-ugwpuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/795027b4aa12881806499d6a046fe94bf948b831/pkg/cli/start.go#L280)):*
> ```Go
> var ErrorCode = 1
> 
> // startContext captures the command-line arguments for the `start` command.
> ```

this comment is missing on quitContext, nodeContext, and zoneContext - btw, all these types are unnecessary, right? you could just write
```
var startCtx struct {
  *cliContext
  serverInsecure bool
}{&ctx}
```
right?

---

*[pkg/cli/zone.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-Kqm68p2isIjqCgLei6v:-Kqm68p2isIjqCgLei6w:b-wn4hqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/795027b4aa12881806499d6a046fe94bf948b831/pkg/cli/zone.go#L52)):*
> ```Go
> 
> type zoneContext struct {
> 	// Embed the cli context.
> ```

useless comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-:-Kqm61wjmlNzNkAFr4n4:b-n8mnnl)*

**Comment by knz** [comment]
Good suggestions. Thanks. PTAL

---

Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-:-KqmJJxiwoHfrjxkfoVJ:bwdyy3x)*

**Comment by tamird** [comment]
:lgtm_strong: 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cli/context.go, line 128 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmKLmimH5ypIM7pW5W:-KqmKLmimH5ypIM7pW5X:b-fdql7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/59745be50235105c5c3dd2d96a3cbca0b5d08ffb/pkg/cli/context.go#L128)):*
> ```Go
> 	// execStmts is a list of statements to execute.
> 	execStmts statementsValue
> }{}
> ```

won't the embedded `cliContext` be nil, here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-:-KqmLd1i_upDsk5cmv5m:b-uwkowd)*

**Comment by knz** [comment]
Indeed, that was an oversight. Thanks for spotting it.

**Comment by tamird** [comment]
Looks like some tests need updating, though.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-:-KqmMU1ATZU0ziJQ0L-N:bwm1u02)*

**Comment by tamird** [comment]
Couple of optional nits since you're going to have to eat another CI cycle :speak_no_evil: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cli/context.go, line 281 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNJqomdPmKxxl95x2:-KqmNJqomdPmKxxl95x3:bflmsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L281)):*
> ```Go
> 	startKey:   engine.NilKey,
> 	endKey:     engine.MVCCKeyMax,
> 	replicated: false,
> ```

nit: can omit this

---

*[pkg/cli/context.go, line 285 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNNlg1WKWMjdJXKGO:-KqmNNlg1WKWMjdJXKGP:bxuuwym) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L285)):*
> ```Go
> 
> // zoneCtx captures the command-line parameters of the `zone` command.
> var zoneCtx = struct {
> ```

nit: no need for the literal; this can just be a declaration:
```
var zoneCtx struct {
...
}
```

---

*[pkg/cli/context.go, line 291 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNSbmsIR7PZTrDD3g:-KqmNSbmsIR7PZTrDD3h:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L291)):*
> ```Go
> 
> // startCtx captures the command-line arguments for the `start` command.
> var startCtx = struct {
> ```

ditto

---

*[pkg/cli/context.go, line 298 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNTNvtUWuNVhjPN8g:-KqmNTNvtUWuNVhjPN8h:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L298)):*
> ```Go
> 
> // quitCtx captures the command-line parameters of the `quit` command.
> var quitCtx = struct {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-:-KqmNVFZf3hmdndhsUVA:b50y4pr)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cli/context.go, line 281 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNJqomdPmKxxl95x2:-Kqmc-XJm0ZL6iI8LxeU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L281)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: can omit this
</blockquote></details>

Done.

---

*[pkg/cli/context.go, line 285 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNNlg1WKWMjdJXKGO:-Kqmc4ZRBF4Qxwn1fNz4:bydxw1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L285)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: no need for the literal; this can just be a declaration:
```
var zoneCtx struct {
...
}
```
</blockquote></details>

Nice, TIL. Done.

---

*[pkg/cli/context.go, line 291 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNSbmsIR7PZTrDD3g:-Kqmc5u9nFVdWE_LyfuN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L291)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/cli/context.go, line 298 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465#-KqmNTNvtUWuNVhjPN8g:-Kqmc6ISHiA8GAlmlg1Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6885369ed6aa60d5ad3b30362c5281bd024d2744/pkg/cli/context.go#L298)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465)*

**Comment by knz** [comment]
grmbl, fixed

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17465)*

**Pull request merged**
