### PR TITLE
schemachanger: Refactor tests for concurrent schema changer behaviors

### LINKED ISSUE #107223: schemachanger: better concurrency testing
When interpreting DDL statements, the declarative schema changer checks that there are no concurrent schema changes on the affected descriptors. This effectively acquires an exclusive lock on those descriptors.

We've had bugs like https://github.com/cockroachdb/cockroach/issues/106487 for which it has been difficult to validate the fix other than by running a workload, which is unfortunate. We should instead have an integration test in the form of a go test, in which a bunch of various schema changes fire up concurrently on the same limited set of descriptors. 

For example:
1. for each table, one thread in which we sequentially rename a table by cycling through a bunch of names,
2. for each table, one thread in which we sequentially create and drop secondary indexes,
3. for each schema and for each database, cycle through a bunch of names
4. etc.

The fully qualified names of the tables can be retrieved in each transaction and fmt.Sprint-ed into the DDL statement by looking up the descriptors by ID because the IDs don't change.

This is just a general idea, we haven't implemented RENAME TO statements in the declarative schema changer as of yet.

Jira issue: CRDB-29951

### LINKED ISSUE #108140: schemachanger_test: Clean up redundant ConCurrentSchemaChange tests
It looks like we have three redundant unit tests about the behavior of declarative schema changer for concurrent schema changes. We should clean them up.

Related https://github.com/cockroachdb/cockroach/issues/107223
Releated slack conversation: https://cockroachlabs.slack.com/archives/C04N0AS14CT/p1691090587886769

Jira issue: CRDB-30326

### PR DESCRIPTION
**Pull request by Xiang-Gu**
1. It cleans up some redundant tests about concurrent schema changer behavior and refactor in a new simpler, cleaner test
2. It adds an integration style test for testing concurrent schema change behaviors where we run many schema changes for an extended period of time and assert that all of they eventually succeed and the descriptors end up in the expected state.

Fix #108140
Fix #107223

Epic: None
Release note: None

### CODE REVIEW

**Comment by Xiang-Gu** [comment]
CI tests are flaky tests unrelated to this PR. Ready for a look!

**Comment by rafiss** [comment]
nice work! quick question, do you know if the new test would have been able to catch the bug described here? https://github.com/cockroachdb/cockroach/pull/106933

**Comment by Xiang-Gu** [comment]
@rafiss yes but with a different error! So I looked at that PR that fixes the bug. It essentially added two lines as listed below. So I did the following:
1.  Run the test as in the PR, it passes;
2. Remove [one](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/builder_state.go#L98) line and re-run this test, rather quickly, it fails with error
```
    schemachanger_test.go:770: pq: internal error: executing declarative schema change PreCommitPhase stage 2 of 2 with 3 MutationType ops (rollback=false) for DROP INDEX: error executing PreCommitPhase stage 2 of 2 with 3 MutationType ops: *scop.SetJobStateOnDescriptor: ... unexpected schema change job ID 889775506765152257 on table 107, expected 0
```
3. Add back that line, re-run the test, and it passes.
4. Remove [another one](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scbuild/builder_state.go#L79) line and re-run this test, rather quickly, it fails with the same type of error again.
5. Add back this other line, re-run the test, and it passes.

**Review by fqazi — APPROVED** [review]
@Xiang-Gu This is excellent stuff! A couple of suggestions for improvements, the transaction one can be ignored.

> Reviewed 2 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108451#-:-NbVKD0e4rl3HBjwxy3c:b-bep12d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108451#-NbVJ2faAo9q6uFiUbV3:-NbVJ2faAo9q6uFiUbV4:bojb85s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02d1f38289546f078b43cd322797fe543f39cdf/pkg/sql/schemachanger/schemachanger_test.go#L635)):*
> ```Go
> 			scName = newSCName
> 			t.Logf("RENAME SCHEMA TO %v", newSCName)
> 		} else if isPQErrWithCode(err, pgcode.UndefinedDatabase) {
> ```

Would it make sense to use catalog queries here instead and transactions, that way, we get retry errors instead. But I think we can't because of declarative based on our slack conversation.
___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108451#-NbVJijp-zKDjibjrufc:-NbVJijp-zKDjibjrufd:blb957f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02d1f38289546f078b43cd322797fe543f39cdf/pkg/sql/schemachanger/schemachanger_test.go#L643)):*
> ```Go
> 
> 	// A goroutine that renames table `testdb.testsc.t` randomly.
> 	go repeatWorkWithInterval("rename-tbl-worker", renameTblInterval, func() error {
> ```

ctxgroup is a cleaner pattern here and would simplify the code

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/schemachanger_test.go` line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108451#-NbVJijp-zKDjibjrufc:-NbVVR_47ZTTSrP7NNp2:b8guzoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c02d1f38289546f078b43cd322797fe543f39cdf/pkg/sql/schemachanger/schemachanger_test.go#L643)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

ctxgroup is a cleaner pattern here and would simplify the code
</blockquote></details>

I explored `ctxgroup` but its functionality is not suitable for our case here.
Namely, `ctxgourp` allows us to spawn workers, and wait for them to complete. Here we want the main routine to let workers work indefinitely and signal them to finish once a time up fires.

**Comment by Xiang-Gu** [comment]
TFTR!
bors r+

**Pull request merged**
