### PR TITLE
server: add approximate proposal quota to the range debug page

### PR DESCRIPTION
**Pull request by BramGruneir**
screen shot 2017-05-31 at 17 01 47

### CODE REVIEW

**Comment by irfansharif** [comment]
LGTM however I don't know if this is something slated for the 1.1 release. 
Additionally if we end up using units for Log Size (`KB/KiB`), the same units will apply here (for now at least).

**Comment by petermattis** [comment]
:lgtm: 

On the non-leaseholder, can we indicate that the proposal quota is invalid with a `-`? If that is difficult, feel free to ignore.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16245#-:-KlVPvy-Wl0ZluEOUWdl:b-ec540f)*

**Comment by BramGruneir** [comment]
@petermattis

Easy, and done.  


@irfransharif
We haven't put any units in yet and just leave it as bytes, but I could convert this value to KiB right now if you think that's a good idea.  

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16245#-:-KlVwJUCppZ9Tw8813tD:b-mpvj1p)*

**Comment by irfansharif** [comment]
I do, yes. :lgtm: eitherway.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16245#-:-KlVz4dp9RhNKE8aZb4E:bhujjay)*

**Comment by BramGruneir** [comment]
So I tried to use humanize on this, but it insisted on showing MiB not KiB.  I'm going to leave it as is for now.  

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16245#-:-KlZZ65jviS8KnQDERe2:b-jdb4p)*

**Pull request merged**
