### PR TITLE
add health check

### PR DESCRIPTION
**Pull request by maxlang**
Adds the health check icon to the top bar. Currently it refreshes every 2 seconds (based on an interval timer) but in an upcoming PR I'm going to wire up all refreshes to a global refresh object that can change the refresh interval and allows pages to register/deregister refreshers.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4952)

### CODE REVIEW

**Comment by tamird** [comment]
merge conflict

**Comment by maxlang** [comment]
Unable to reach server health endpoint
screen shot 2016-03-07 at 4 17 10 pm

Able to reach server health endpoint
screen shot 2016-03-07 at 4 16 34 pm

**Comment by maxlang** [comment]
@tamird fixed

**Comment by cuongdo** [comment]
When the node is down, I think "Updated:" should be the last time the UI
was able to reach the backend.

**Comment by petermattis** [comment]
Showing `NaN` in the `Updated` field looks like a bug. I'm not a designer, but I wish the down indication was bigger and bolder.

**Comment by maxlang** [comment]
I created an issue for this: https://github.com/cockroachdb/cockroach/issues/4954

**Comment by maxlang** [comment]
@petermattis something like

screen shot 2016-03-07 at 4 31 34 pm

**Comment by petermattis** [comment]
@maxlang Yes, something like that (though now the "Updated:" string looks out of place).

**Comment by maxlang** [comment]
@petermattis maybe

screen shot 2016-03-07 at 4 39 10 pm

I'll make a note to discuss with Andrew

**Comment by mrtracy** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/components/health.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCI-3MLgkCiTRZqwPHT:-KCI-3MM7oNK7EqicnQC:1286476376) ([raw file](https://github.com/cockroachdb/cockroach/blob/688a87e49f14f9913edfd9d0126a1dceba2c627a/ui/ts/components/health.ts#L17)):*
You do not appear to be using this.  Did you mean to use it when parsing the result from the server?

---

*[ui/ts/components/health.ts, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCHyyCThZ7OFW7IemB2:-KCHyyCThZ7OFW7IemB3:-1277474054) ([raw file](https://github.com/cockroachdb/cockroach/blob/688a87e49f14f9913edfd9d0126a1dceba2c627a/ui/ts/components/health.ts#L34)):*
Reminder that you don't need "thiz" in typescript when using double-arrow `=>` functions.  `this` means the same as `thiz` in this scope.

---

*[ui/ts/components/health.ts, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCHzJ_XuG_DcMifQZv1:-KCHzJ_YIcN3M1tMowPj:1531200515) ([raw file](https://github.com/cockroachdb/cockroach/blob/688a87e49f14f9913edfd9d0126a1dceba2c627a/ui/ts/components/health.ts#L47)):*
Move this into the controller itself, on a method like `startRefresh()`.  You should also declare getHealth differently, as in the following syntax:
```typescript
startRefresh() {
  setInterval(this.getHealth, 2000)
}

getHealth: () :MithrilPromise<void> => {

}
```

The declaration of getHealth with a `=>` will permanently set the `this` pointer, allowing it to be used directly in callbacks.
   
Finally, add an `onunload` method to the controller which removes the interval.

---

*[ui/ts/components/health.ts, line 53 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCI-9TZIam6nTXAZngV:-KCI-9TZIam6nTXAZngW:267573741) ([raw file](https://github.com/cockroachdb/cockroach/blob/688a87e49f14f9913edfd9d0126a1dceba2c627a/ui/ts/components/health.ts#L53)):*
This should be done in the promise the controller creates, rather than here in the view. 

Also, use `_.startsWith()`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952)*

**Comment by maxlang** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/components/health.ts, line 17 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCI-3MLgkCiTRZqwPHT:-KCI9ysmptHkKMBRLzD3:-722045206) ([raw file](https://github.com/cockroachdb/cockroach/blob/688a87e49f14f9913edfd9d0126a1dceba2c627a/ui/ts/components/health.ts#L17)):*
Ah yeah, I'll just ditch this for now. We'll probably want a richer response from the server anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952)*

**Comment by mrtracy** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/ts/components/health.ts, line 22 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCIeL3HP2sWtFUJXrX4:-KCIeL3HP2sWtFUJXrX5:946237992) ([raw file](https://github.com/cockroachdb/cockroach/blob/5795fe7814f5e6421ceb032367a16974058fe34b/ui/ts/components/health.ts#L22)):*
I just want to say that I absolutely hate pedantic linter-enforced over-specification like this. The type is completely apparent from the declaration, and in this case it reads like some sort of confusing double-vision. Even languages like Go and C++ don't force you to do this (they have auto-typing), and it's not even idiomatic typescript.

If we do decide to overhaul this to a different framework in 1.0, I am 100% in favor of relaxing our tslint rules significantly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-:-KCIfJmmzaaxIkPya4wZ:1417088721)*

**Comment by maxlang** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[ui/ts/components/health.ts, line 22 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952#-KCIeL3HP2sWtFUJXrX4:-KCIw_Gua7rncVYa1Wbq:1613188253) ([raw file](https://github.com/cockroachdb/cockroach/blob/5795fe7814f5e6421ceb032367a16974058fe34b/ui/ts/components/health.ts#L22)):*
Agreed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4952)*

**Pull request merged**
