### PR TITLE
sql: Add a SHOW NODES command

### LINKED ISSUE #40445: sql: show nodes command
In SQL, users often want to know about the other nodes in the cluster to inspect locality or other information.

We could imagine something like the CLI's `cockroach node status` 

```SQL
id |        address        |      sql_address      |                build                 |            started_at            |            updated_at            |                  locality                  | is_available | is_live
+----+-----------------------+-----------------------+--------------------------------------+----------------------------------+----------------------------------+--------------------------------------------+--------------+---------+
   1 | ip-10-12-39-73:26257  | ip-10-12-39-73:26257  | v19.2.0-alpha.20190606-1986-g6bcf17c | 2019-09-03 20:56:56.853397+00:00 | 2019-09-03 21:01:22.360921+00:00 | cloud=aws,region=us-east-2,zone=us-east-2c | true         | true
   2 | ip-10-12-34-163:26257 | ip-10-12-34-163:26257 | v19.2.0-alpha.20190606-1986-g6bcf17c | 2019-09-03 20:56:58.02616+00:00  | 2019-09-03 21:01:23.537103+00:00 | cloud=aws,region=us-east-2,zone=us-east-2c | true         | true
   3 | ip-10-12-43-63:26257  | ip-10-12-43-63:26257  | v19.2.0-alpha.20190606-1986-g6bcf17c | 2019-09-03 20:56:59.292659+00:00 | 2019-09-03 21:01:20.300322+00:00 | cloud=aws,region=us-east-2,zone=us-east-2c | true         | true
```

I think we would need locality, sql address, build, webui of each node, etc.

### PR DESCRIPTION
**Pull request by rohany**
This PR adds a SHOW NODES command that displays the same data as the
cockroach node status command.

Fixes #40445.

Release note (sql change): Adds a SHOW NODES command that displays the
same data as cockroach node status.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Code LGTM but I am concerned about the choice to use gossip over KV range liveness.
(I appreciate that you are reusing the same logic as `cockroach node status` and therefore your task was not to think about this. But your PR is bringing to my attention the idea that maybe both are using the wrong approach.)

@andreimatei what do you think? Is it reasonable to query only the gossip records? See my extended question about this below inline. (I'd normally ask Tobias but since he's on vacation you're next in line)

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-:-LoU_VWD27G_pk6gNxfi:b-pv02j4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/delegate/show_nodes.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZ_EW6GukJx5nwQgU:-LoUZ_EXAYK45v6XMNyL:b-opquoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/delegate/show_nodes.go#L17)):*
> ```Go
> // delegateShowNodes implements the SHOW NODES statement.
> func (d *delegator) delegateShowNodes(n *tree.ShowNodes) (tree.Statement, error) {
> 	// Note: Keep this query consistent with the one used in cockroach node status (cli/node.go).
> ```

An idea: put the SQL text of the query into a constant variable, export it, and use it from both places. Do you think this would work?
___
*[pkg/sql/delegate/show_nodes.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZv-M54kwI295j-jV:-LoUZv-M54kwI295j-jW:b-23dzgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/delegate/show_nodes.go#L31)):*
> ```Go
> 			END AS is_available,
> 		ifnull(is_live, false) as is_live
> 	FROM crdb_internal.gossip_liveness LEFT JOIN crdb_internal.gossip_nodes USING (node_id)`
> ```

So we have this difference between the gossip database and the KV node liveness database.
It is possible for the gossip database to "forget" nodes that are still valid for the entire cluster. This is possible e.g. when you shut down the entire cluster, let it sleep for a while so that liveness records in gossip expire, then restart the cluster but leaving some nodes out. 
The KV node liceness database is always guaranteed to know everything (but it slower to query and may become unavailable due to partial outages).

Have you purposefully chosen one over the other? I am concerned that we are going to create UX surprise here, where users may find themselves in a situation where they don't see all the nodes they expect to see here.
___
*[pkg/sql/parser/sql.y, line 3612 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZlzSE7F0CZffi2PA:-LoUZlzSE7F0CZffi2PB:ba87cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/parser/sql.y#L3612)):*
> ```Yacc
> | SHOW JOB error // SHOW HELP: SHOW JOBS
> 
> // %Help: SHOW NODES - display node information
> ```

maybe `- list visible nodes and node properties`

**Review by knz — COMMENTED** [review]
Also @rohany my LGTM is also conditional on the presence of unit tests for the new feature:

- you need to extend `parse_test.go`
- also `help_test.go`
- also an output check for the results of SHOW NODE. You'll want a manual test cluster (i.e. not a logic test) and compare the values with those given to you by the accessors on the test cluster object.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-:-LoU_xIp8689M9V2B5l_:b-aeswa8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rohany, and @solongordon)

___
*[pkg/sql/delegate/show_nodes.go, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZ_EW6GukJx5nwQgU:-LoVxMOaEy8vam7629Mb:b-r6jwwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/delegate/show_nodes.go#L17)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

An idea: put the SQL text of the query into a constant variable, export it, and use it from both places. Do you think this would work?
</blockquote></details>

I wanted to, but I have to make the query here slightly different (the AS qualifications are a little bit different). The CLI does its own formatting with column headers but we have to specify them here.
___
*[pkg/sql/parser/sql.y, line 3612 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZlzSE7F0CZffi2PA:-LoVxXBM69y0fCWWSXBJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/parser/sql.y#L3612)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe `- list visible nodes and node properties`
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40636)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

___
*[pkg/sql/delegate/show_nodes.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40636#-LoUZv-M54kwI295j-jV:-LoX3six5prL3zifDiWS:bln2up4) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b3395cb59a01b42a9d89fe912aa436743ca6cf/pkg/sql/delegate/show_nodes.go#L31)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So we have this difference between the gossip database and the KV node liveness database.
It is possible for the gossip database to "forget" nodes that are still valid for the entire cluster. This is possible e.g. when you shut down the entire cluster, let it sleep for a while so that liveness records in gossip expire, then restart the cluster but leaving some nodes out. 
The KV node liceness database is always guaranteed to know everything (but it slower to query and may become unavailable due to partial outages).

Have you purposefully chosen one over the other? I am concerned that we are going to create UX surprise here, where users may find themselves in a situation where they don't see all the nodes they expect to see here.


</blockquote></details>

I agree that gossip is the wrong source of data for this.
The liveness records sound like a better source, but I don't know the technicalities about what lingers in there. Are long-gone nodes deleted from there? Is that integrated with decomissioned nodes perhaps?

**Comment by andreimatei** [comment]
I'd question if we need this statement in the first place. Can't we muddle along with the virtual tables and the cli command for longer? I'd take a predisposition for inaction when it comes to adding new sql commands. I question whether nodes are even a fundamental cockroach concept that warrants such language integration; in Cockroach Cloud for example we should be moving away from talking about nodes. And even if they are, I'd take time to debate the columns returned by this command. I wonder about the updated_at column, which suggests a surprising execution model for this command (presenting some sort of historical info instead of "up to date" info), and I don't really know what live and available mean (they're not properly documented for the cli command).

**Comment by Freeaqingme** [comment]
What permissions/grants would a user need to be allowed to perform this command?

**Comment by knz** [comment]
> f cockroach node status already shows this same information, then we're not doing worse than before - we're merely consistently broadcasting what another command knows to be true.

Counterpoint:

If `cockroach node status` is currently wrong, we have to fix it.
If we introduce a new `SHOW NODES` on top of this and it's also wrong, no we have two things to fix and test instead of just one.

I'm not keen on doubling down on tech debt just because we're ok with debt in general. Interest accrues unpleasingly.

**Pull request closed without merging**
