### PR TITLE
acceptanceccl: add RestoreBig benchmark

### PR DESCRIPTION
**Pull request by madelynnblue**
@cuongdo could you review the non-CCL changes?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14393)

### CODE REVIEW

**Comment by cuongdo** [comment]
`terrafarm` changes LGTM

---

Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/builder.sh, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgGWZMdtGINB4QrZPtv:-KgGWZMdtGINB4QrZPtw:b-kz6usk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/build/builder.sh#L125)):*
> ```Shell
> vols="${vols} --volume=${HOME}/.yarn-cache:${container_home}/.yarn-cache"
> vols="${vols} --volume=${cockroach_toplevel}:/go/src/github.com/cockroachdb/cockroach"
> vols="${vols} --volume=${HOME}/.ssh:/root/.ssh"
> ```

I'm uneasy with exposing SSH keys to the builder image. Is there a way around this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-:-KgL93dtAFUHawgE5lja:b-kwnpt0)*

**Comment by mjibson** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/builder.sh, line 125 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgGWZMdtGINB4QrZPtv:-KgLQN4YQn9PAtKXgR-A:bctw3rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/build/builder.sh#L125)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

I'm uneasy with exposing SSH keys to the builder image. Is there a way around this?
</blockquote></details>

I've removed this. We can reasses ways to add it later, like maybe only adding ~/.ssh/azure{_pub} or something. But for now since I'm not using the builder things work fine. Not sure how this will work on mac.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by danhhz** [comment]
ccl stuff LGTM

---

Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgGZqdKV_u2Lb_2zpfH:-KgGZqdL7Op2v4ZF93az:b-87q4iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/pkg/ccl/acceptanceccl/backup_test.go#L137)):*
> ```Go
> 	// (mis-)Use a sub benchmark to avoid running the setup code more than once.
> 	b.Run("", func(b *testing.B) {
> 		log.Info(ctx, b.N)
> ```

include some more context in these log messages about what they are

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgG_FEZpFnB9FwFB70Y:-KgG_FEZpFnB9FwFB70Z:b-twwlhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/pkg/ccl/acceptanceccl/backup_test.go#L138)):*
> ```Go
> 	b.Run("", func(b *testing.B) {
> 		log.Info(ctx, b.N)
> 		restoreBaseURI := fmt.Sprintf("azure://%s/BenchmarkRestoreBig/%s-%d?%s=%s&%s=%s",
> ```

I prefer that we use net/url to construct the query params here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-:-KgG_gRP3txUjh9XIjke:bpepozd)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/util.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgLUjZtwthFIjtDMdmy:-KgLUjZuVRnSOm6ytx5W:bjqp0ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/a789e7a25c7db316d4751806b8c3e65c547538ca/pkg/acceptance/util.go#L140)):*
> ```Go
> 
> // IsRemote is true when terraform should be used instead of docker.
> func IsRemote() bool {
> ```

why don't you export the entire block from main_test and main_stub_test instead of exporting this and repeating those blocks? In fact, that would allow you to avoid having a separate main_stub_test in ccl/acceptance altogether.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by mjibson** [comment]
Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/acceptance/util.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgLUjZtwthFIjtDMdmy:-KgNJBc4lh4zFMbH7DJ7:bsl5ij8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a789e7a25c7db316d4751806b8c3e65c547538ca/pkg/acceptance/util.go#L140)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why don't you export the entire block from main_test and main_stub_test instead of exporting this and repeating those blocks? In fact, that would allow you to avoid having a separate main_stub_test in ccl/acceptance altogether.
</blockquote></details>

I did some things that I think make this work. Better now?

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgGZqdKV_u2Lb_2zpfH:-KgLVnheRHw267lsRAdY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/pkg/ccl/acceptanceccl/backup_test.go#L137)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

include some more context in these log messages about what they are
</blockquote></details>

Done.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 138 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgG_FEZpFnB9FwFB70Y:-KgLVnxkwv_y5PRXMKp3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b7ac5fc0a17ce81fe99fb7358b396665dc43f1f/pkg/ccl/acceptanceccl/backup_test.go#L138)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I prefer that we use net/url to construct the query params here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by tamird** [comment]
Reviewed 1 of 6 files at r1, 7 of 8 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/main_test.go, line 17 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNLXvwVo66uUDdi9US:-KgNLXvwVo66uUDdi9UT:b-d4kt91) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/acceptance/main_test.go#L17)):*
> ```Go
> // Author: Peter Mattis (peter@cockroachlabs.com)
> 
> // Acceptance tests are comparatively slow to run, so we use the above build
> ```

remove this comment?

---

*[pkg/acceptance/test_main.go, line 15 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNLfxBmAKfFNIpK642:-KgNLfxBmAKfFNIpK643:b32vqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e0d3da51125a14c7b0afa7590bc7e7d5af5147/pkg/acceptance/test_main.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> //
> // Author: Tamir Duberstein (tamird@gmail.com)
> ```

D:

---

*[pkg/acceptance/test_main.go, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNM9tkawlW96qW5Fh_:-KgNM9tlG3ycqRSaM_ho:blo4al) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/acceptance/test_main.go#L36)):*
> ```Go
> func MainTest(m *testing.M) {
> 	if !*flagRemote {
> 		log.Infof(context.Background(), "not running with `acceptance` build tag or against remote cluster; skipping")
> ```

make this `fmt.Fprintln(os.Stderr...` to match the corollary file while you're here

---

*[pkg/ccl/acceptanceccl/main_test.go, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNLozdfVlTknX1bahN:-KgNLozdfVlTknX1bahO:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/ccl/acceptanceccl/main_test.go#L18)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	/*
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by mjibson** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/acceptance/main_test.go, line 17 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNLXvwVo66uUDdi9US:-KgNNJUJhaxtPBVcH6eH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/acceptance/main_test.go#L17)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this comment?
</blockquote></details>

Done.

---

*[pkg/acceptance/test_main.go, line 36 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNM9tkawlW96qW5Fh_:-KgNNg1fCuxGll8WKqj1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/acceptance/test_main.go#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

make this `fmt.Fprintln(os.Stderr...` to match the corollary file while you're here
</blockquote></details>

Done.

---

*[pkg/ccl/acceptanceccl/main_test.go, line 18 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgNLozdfVlTknX1bahN:-KgNNLTT1HKwPuGildSj:b-59se1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b114c35d6c7a5e0d37d9cc8c0ce4bf8d70e34d8f/pkg/ccl/acceptanceccl/main_test.go#L18)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

?
</blockquote></details>

Oops. Leftover from a test. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by tamird** [comment]
Reviewed 1 of 8 files at r3, 3 of 3 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 105 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgOnrv-aZgNUdp25PDB:-KgOnrv0-6lVYl7pTmiD:biwyjwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be377b5e054f3141a736a77b33f8bf99c794de9/pkg/ccl/acceptanceccl/backup_test.go#L105)):*
> ```Go
> // the time to restore it. Run with:
> // make bench TESTTIMEOUT=1h PKG=./pkg/ccl/acceptanceccl BENCHES=BenchmarkRestoreBig TESTFLAGS='-v -benchtime 1m -remote -key-name azure -cwd ../../acceptance/terraform/azure'
> func BenchmarkRestoreBig(b *testing.B) {
> ```

this test should look at flagRemote

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Comment by mjibson** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/acceptanceccl/backup_test.go, line 105 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393#-KgOnrv-aZgNUdp25PDB:-KgQ5RLgJykPLpHpeNNf:b50ebwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be377b5e054f3141a736a77b33f8bf99c794de9/pkg/ccl/acceptanceccl/backup_test.go#L105)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this test should look at flagRemote
</blockquote></details>

MakeFarmer calls SkipUnlessRemote, so no need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14393)*

**Pull request merged**
