### PR TITLE
cli: use lib/pq which now supports multiple result sets

### PR DESCRIPTION
**Pull request by madelynnblue**
Test results changed because lib/pq returns the first tag, not last.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13443)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/sql_util.go, line 257 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-KcP4zOvE45UEuEPuQu4:-KcP4zOvE45UEuEPuQu5:bm8axo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d66f68ed11152d375c9f2c4f8a8e4c2d6a84b33/pkg/cli/sql_util.go#L257)):*
> ```Go
> 	}
> 	defer func() {
> 		cerr := rows.Close()
> ```

i think you can just ignore this error; `(*database/sql.Rows).Close` is in our errcheck excludes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443)*

**Comment by mjibson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/cli/sql_util.go, line 257 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-KcP4zOvE45UEuEPuQu4:-KcPBaJMZLGAEUoag3fO:b-1w2nls) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d66f68ed11152d375c9f2c4f8a8e4c2d6a84b33/pkg/cli/sql_util.go#L257)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i think you can just ignore this error; `(*database/sql.Rows).Close` is in our errcheck excludes
</blockquote></details>

Nope, it's not ignored. See the defer in runQuery above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/sql_util.go, line 257 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-KcP4zOvE45UEuEPuQu4:-KcPGy6yY94SpAQHrBa7:bhu60xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d66f68ed11152d375c9f2c4f8a8e4c2d6a84b33/pkg/cli/sql_util.go#L257)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Nope, it's not ignored. See the defer in runQuery above.
</blockquote></details>

Oh, that's probably because `rows` doesn't have the type I think it does.

Now that you're ignoring the error, please remove the named return here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-:-KcPH3XIKNX22v8GO7Rq:bnfp4nl)*

**Comment by mjibson** [comment]
@knz adding you because of the rows.Close bug from the newly added database name prompt code and the tcl expect test changes.

**Comment by knz** [comment]
"lib/pq returns the first tag, not last" - that's a bug. I'd be wary of merging this PR until that bug gets fixed. The problem I see is that observing the last tag in the cli provides visual feedback that all statements were processed successfully.

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cli/sql.go, line 435 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-Kcb7H200T1iAlq6px_2:-Kcb7H21wx-kJnWgAyfp:by060oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ea338ab9c0c313b57f605c791af7f2f298e9e9e/pkg/cli/sql.go#L435)):*
> ```Go
> 	// one. However since we aren't using database/sql, we have to manually
> 	// ensure rows is closed before executing another query on the connection.
> 	_ = rows.Close()
> ```

TIL. Thanks for spotting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-:-Kcb7g_CV1AZ4ubBmGIt:bcq9a0i)*

**Comment by knz** [comment]
also this breaks interactive patterns such as `set database=foo; delete from blah where x= 3` -> can't see any more how many rows were deleted.

**Comment by mjibson** [comment]
I would really like to get this stuff to the point where it's the same as psql, which will print each tag during multi-statement input. psql does this by doing client-side parsing of the statements and sending them after each `;`. Is that approach too slow? It might make sense to add the ability to lib/pq to get each result, whether it was a query with rows or not.

**Comment by tamird** [comment]
On Fri, Feb 10, 2017 at 11:18 AM, Matt Jibson <notifications@github.com>
wrote:

> It might make sense to add the ability to lib/pq to get each result,
> whether it was a query with rows or not.


Sounds like the right thing to me. Perhaps those new methods should be tied
into NextResult or whatever that method is called.

**Comment by knz** [comment]
> psql does this by doing client-side parsing of the statements and
> sending them after each |;|. Is that approach too slow?

The problem is not that it is slow; the problem is that it breaks
server-side automatic retries.

So :+1: on Tamir's suggestion to have lib/pq report all the tags.

**Comment by mjibson** [comment]
I've fixed lib/pq to return the last tag. Getting the all tags stuff will take another PR because it's not trivial.

**Comment by knz** [comment]
:lgtm:
Thanks for the extra mile.

---

Reviewed 6 of 6 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13443#-:-KcwlWjYuh-YNZ_HWbbm:bdq3ekl)*

**Pull request merged**
