### PR TITLE
sql: show time since table stats were collected in EXPLAIN

### LINKED ISSUE #57517: sql: add time of last updated stats to explain analyze
One big source of potential slow queries is out of date statistics in the CBO. We aim to refresh these sufficiently often to provide good plans without impacting the cluster too much. However, sometimes, this isn't frequent enough. It can be tricky for developers to think to look at the last time statistics were refreshed. If they do, `CREATE STATISTICS` is an easy enough solution. We should consider making the last time statistics were updated more discoverable. One place to put this would be in `explain analyze` as it is a user trigger that this query may be underperforming and it can help clue them on the need to update statistics.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: more granular redaction of EXPLAIN

This change replaces the MakeDeterministic explain flag with a more
granular bitfield, which can control various types of redactions.

Release note: None

#### sql: show time since table stats were collected in EXPLAIN

Example:
```
EXPLAIN SELECT * FROM rides JOIN vehicles ON rides.vehicle_id = vehicles.id;
                                         info
--------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • hash join
  │ estimated row count: 500
  │ equality: (vehicle_id) = (id)
  │
  ├── • scan
  │     estimated row count: 500 (100% of the table; stats collected 15 seconds ago)
  │     table: rides@primary
  │     spans: FULL SCAN
  │
  └── • scan
        estimated row count: 15 (100% of the table; stats collected 11 seconds ago)
        table: vehicles@primary
        spans: FULL SCAN
(16 rows)
```

Durations are rounded to the nearest unit (second, minute, hour, day).

Fixes #57517.

Release note (sql change): EXPLAIN and EXPLAIN ANALYZE now show how
long ago table statistics were collected.

CC @awoods187

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61858#-:-MVbY7xeBCd0OvwIcKum:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/exec/explain/flags.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61858#-MVbVOJo7cHe04h_9q4D:-MVbVOJp5CLlQL_1yVie:bdv0n1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab4f1a7e9e93030d1c76a4879128942de679ff1/pkg/sql/opt/exec/explain/flags.go#L47)):*
> ```Go
> 
> 	// RedactVolatile hides any values that can vary from one query run to the
> 	// other, even if the configuration and data distribution changes (e.g.
> ```

[nit] did you mean "even if the configuration and data distribution does not change"?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61858#-:-MVba5Dl1djstiMD7Nkx:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/exec/explain/flags.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61858#-MVbVOJo7cHe04h_9q4D:-MVba2-w9g_pjKwhZLxA:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bab4f1a7e9e93030d1c76a4879128942de679ff1/pkg/sql/opt/exec/explain/flags.go#L47)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] did you mean "even if the configuration and data distribution does not change"?
</blockquote></details>

Good catch, fixed.

**Comment by awoods187** [comment]
This is great! cc @ianjevans because we will probably get questions about how were stats collected/how do i update them (e.g., analyze/auto stats) etc.

**Pull request merged**
