### PR TITLE
workload/ycsb: implement read-modify-write

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
Nice

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-:-LlmdYye9W9x6UI7k2B7:bb70w76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/ycsb.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-LlmcYQ2974wwG9nVrtJ:-LlmcYQ2974wwG9nVrtK:b-11lci5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd27d52d95c3e6bec7c3c157b4a77fc503d4751a/pkg/workload/ycsb/ycsb.go#L578)):*
> ```Go
> 			return err
> 		}
> 		for res.Next() {
> ```

Should this ever read more than one row? If not you could do `QueryRowContext`

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-:-Llmgq_D3QLa7eXaAxq9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jeffrey-xiao)

___
*[pkg/workload/ycsb/ycsb.go, line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-Llmfdq10QbetKA7neBr:-Llmfdq10QbetKA7neBs:b-qziiib) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd27d52d95c3e6bec7c3c157b4a77fc503d4751a/pkg/workload/ycsb/ycsb.go#L300)):*
> ```Go
> 	}
> 
> 	readStmts := make([]*gosql.Stmt, numTableFields)
> ```

nit: move up next to `readStmt` and rename to `readFieldStmts`. Same thing in the `ycsbWorker` struct.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39430)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jeffrey-xiao)

___
*[pkg/workload/ycsb/ycsb.go, line 571 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-LlmhCnU5HWJSQEq1biP:-LlmhCnU5HWJSQEq1biQ:bazshxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd27d52d95c3e6bec7c3c157b4a77fc503d4751a/pkg/workload/ycsb/ycsb.go#L571)):*
> ```Go
> 	value := yw.randString(fieldLength)
> 	fieldIdx := yw.rng.Intn(numTableFields)
> 	args := make([]interface{}, 2)
> ```

You can use an array here without it escaping. Could you do that here, in `insertRow`, and in `updateRow`? Something like:
```
diff --git a/pkg/workload/ycsb/ycsb.go b/pkg/workload/ycsb/ycsb.go
index 4d92b018db..f2d9356556 100644
--- a/pkg/workload/ycsb/ycsb.go
+++ b/pkg/workload/ycsb/ycsb.go
@@ -484,12 +484,12 @@ func (yw *ycsbWorker) randString(length int) string {
 }

 func (yw *ycsbWorker) insertRow(ctx context.Context, keyIndex uint64, increment bool) error {
-       args := make([]interface{}, numTableFields+1)
+       var args [numTableFields + 1]interface{}
        args[0] = yw.buildKeyName(keyIndex)
        for i := 1; i <= numTableFields; i++ {
                args[i] = yw.randString(fieldLength)
        }
-       if _, err := yw.insertStmt.ExecContext(ctx, args...); err != nil {
+       if _, err := yw.insertStmt.ExecContext(ctx, args[:]...); err != nil {
                yw.nextInsertIndex = new(uint64)
                *yw.nextInsertIndex = keyIndex
                return err
@@ -509,7 +509,7 @@ func (yw *ycsbWorker) insertRow(ctx context.Context, keyIndex uint64, increment

 func (yw *ycsbWorker) updateRow(ctx context.Context) error {
        var stmt *gosql.Stmt
-       args := make([]interface{}, 2)
+       var args [2]interface{}
        args[0] = yw.nextReadKey()
        fieldIdx := yw.rng.Intn(numTableFields)
        value := yw.randString(fieldLength)
@@ -520,7 +520,7 @@ func (yw *ycsbWorker) updateRow(ctx context.Context) error {
                stmt = yw.updateStmts[fieldIdx]
                args[1] = value
        }
-       if _, err := stmt.ExecContext(ctx, args...); err != nil {
+       if _, err := stmt.ExecContext(ctx, args[:]...); err != nil {
                return err
        }
        return nil
```

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jeffrey-xiao)

___
*[pkg/workload/ycsb/ycsb.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39430#-Llmp3zW0HxA-MChbImi:-Llmp3zW0HxA-MChbImj:b4fehe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d038f43c53baa585aac1eab137c31ebd37938c/pkg/workload/ycsb/ycsb.go#L506)):*
> ```Go
> 
> func (yw *ycsbWorker) insertRow(ctx context.Context) error {
> 	var args [numTableFields]interface{}
> ```

`numTableFields + 1`

**Comment by jeffrey-xiao** [comment]
TFTRs!

bors r+

**Pull request merged**
