### PR TITLE
distsqlrun: make joinreader use limited batches

### LINKED ISSUE #35950: sql: lookup joins should use batch limit
See https://github.com/cockroachdb/cockroach/issues/35947#issuecomment-474442227

Lookup joins should use a batch limit because we don't know how many rows we might get - unless we know the input forms a key (in which case we know we'll get at most one per input row).

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #35950.

Previously, lookup join put no limit on the number of returned rows from
each of its lookups. This could be hugely problematic. Imagine a
circumstance in which a lookup join was planned on a pair of tables that
had 1 billion match rows on the right side for every row on the left
side: in this case, the lookup join would ask the KV backend to return a
single giant buffer with all 1 billion rows.

Also, joinReader's tracing span collection was slightly broken - fix that while we're at it, to make sure we can test this change properly.

Release note (bug fix): prevent OOM conditions during lookup joins
between tables with a very large n:1 relationship.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38837)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-LjYi3hq11QfcPFQdBJV:-LjYi3hr7GU37Rzg1HQw:bckqkbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a68b20437af80f7979dba2070e58904aad37825/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L787)):*
> ```
> SET tracing = on; SELECT COUNT(*) FROM (SELECT * FROM b NATURAL INNER LOOKUP JOIN a); SET tracing = off
> 
> let $lookupTableID
> ```

Huh, this is cool! I don't think I've seen using variables in logic tests before.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-LjYi3hq11QfcPFQdBJV:-LjYrnkI2L3qo9Fs-c9I:buxs8mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a68b20437af80f7979dba2070e58904aad37825/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L787)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Huh, this is cool! I don't think I've seen using variables in logic tests before.
</blockquote></details>

Unfortunately the test below still only passes when this is 63 (because of the output)..

**Review by solongordon — APPROVED** [review]
:lgtm: Glad it was this straightforward!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-:-LjpoihC0y42yTGc0_XH:b-bvamrv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 785 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-LjpodXa5UlbWR1YyjKd:-LjpodXa5UlbWR1YyjKe:b-azww38) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc19926054edd942ccec171ffb53267fb175d4c8/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L785)):*
> ```
> 
> statement ok
> SET tracing = on; SELECT count(*) FROM (SELECT * FROM b NATURAL INNER LOOKUP JOIN a); SET tracing = off
> ```

I'd say might as well verify the `count(*)` result while you're at it.

**Review by jordanlewis — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-:-LjvZ4h1E6GPHKURHbdU:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 787 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-LjYi3hq11QfcPFQdBJV:-LjvZ0Px49dZeNZNQC18:bibnswa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a68b20437af80f7979dba2070e58904aad37825/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L787)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Unfortunately the test below still only passes when this is 63 (because of the output)..
</blockquote></details>

Yeah :( But at least it'll rewrite correctly with `-rewrite` without having to edit the queries.
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join, line 785 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38837#-LjpodXa5UlbWR1YyjKd:-LjvZ-wn687_1-OpQgNX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc19926054edd942ccec171ffb53267fb175d4c8/pkg/sql/opt/exec/execbuilder/testdata/lookup_join#L785)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'd say might as well verify the `count(*)` result while you're at it.
</blockquote></details>

Done.

**Pull request merged**
