### PR TITLE
sql/rowexec: make bulk row writer (materialized view/ctas) write-at-now

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Not too familiar with this code, but don't we also need to change the `writeTS` to be around the current time, and check the version gate?

**Comment by dt** [comment]
> need to change the writeTS to be around the current time

I'm not following; if writeAtBatchTS is true we're just going to ignore writeTS and batchTS so why change it?

> check the version gate?

I've never really understood why we needed the gate: if we just set it, and the server ignores it because it is too old, that's the same as not setting it because the version is too old.

**Comment by erikgrinaker** [comment]
> > need to change the writeTS to be around the current time
> 
> I'm not following; if writeAtBatchTS is true we're just going to ignore writeTS and batchTS so why change it?

Yeah, I think you're right. As long as all SST timestamps are uniform and match `SSTTimestampToRequestTimestamp` then it's fine.

> > check the version gate?
> 
> I've never really understood why we needed the gate: if we just set it the request field, and let an old server ignore it because it is too old, that's the same as not setting it because the version is too old, isn't it?

I don't know the details of the bulk IO code well enough to say. If neither the old code nor the new code cares about some SSTs being written as-is and others being rewritten to the current timestamp in mixed-version clusters then it should be fine.

**Review by erikgrinaker — APPROVED** [review]

**Comment by dt** [comment]
> As long as all SST timestamps are uniform and match SSTTimestampToRequestTimestamp

If writeAtBatchTS is true, we set batchTS to now() on first key of each flush and we set key ts to batchTS (ignoring writeTS), so yeah, that'll be the case.

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by rafiss** [comment]
Looks like you fixed https://github.com/cockroachdb/cockroach/issues/62932. Thanks!

**Pull request merged**
