### PR TITLE
util/limit: replace unfair semaphore with fair quotapool

### PR DESCRIPTION
**Pull request by ajwerner**
Release note: None

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by ajwerner** [comment]
@dt want a backport on this?

**Comment by dt** [comment]
maybe after a week or two of bake-time on master?

**Comment by ajwerner** [comment]
TFTR!

bors r=dt

**Comment by nvanbenschoten** [comment]
Do you two feel ok with me backporting this to 20.2 and 21.1 as part of the backport of https://github.com/cockroachdb/cockroach/pull/66338? Has it baked for long enough?

**Comment by ajwerner** [comment]
@nvanbenschoten I feel good about it.

**Pull request merged**
