### PR TITLE
opt: move ordering logic to new package

### PR DESCRIPTION
**Pull request by RaduBerinde**
Many relational operators have a `CanProvideOrdering` function used to
figure out whether they can satisfy a required ordering, and another
piece of code that builds the child required orderings (in
`buildChildPhysicalProps`). The logic for these has to be "in sync"
but the code lives in separate places. This makes changes hard to
develop, as you have to constantly jump back and forth. Worse, we will
need to add a third routine to figure out the ordering that is being
provided.

We create a new `oporder` package that will be home to this logic for
all operators. Each operator will have a separate file in the package,
which will make it easy to work with a given operator's code
holistically.

With this package, we also have a good place for unit testing of these
functions (which allows simpler, more targeted tests than the usual
opttester approach).

Release note: None

The last commit message has some benchmarks, no significant changes.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: nice work!

> Reviewed 10 of 10 files at r1, 3 of 3 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 4 of 4 files at r6, 3 of 3 files at r7, 3 of 3 files at r8, 3 of 3 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-:-LQC7P7rEnECfmkqp6gi:b-kbynj8)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr_format.go, line 540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBfs2x5GZyCNW5rZlM:-LQBfs2x5GZyCNW5rZlN:b40v3ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/memo/expr_format.go#L540)):*
> ```Go
> 
> // ScanIsReverseFn is a callback that is used to figure out if a scan needs to
> // happen in reverse (depending on that code directly would be a package
> ```

Which code? What package is it in?
___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQBgJ5YBSfELGTr5gMT:bhzdg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
> ```Go
> 
> /*
> Package oporder contains operator-specific logic related to orderings - whether
> ```

[nit] `oporder` kind of breaks our naming convention. Maybe `optorder` fits a bit better? Also, I'm not convinced that it should be inside `ops`. Maybe it should be its own package under `opt`?
___
*[pkg/sql/opt/ops/oporder/limit.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBrAKvAjWwixTSDekG:-LQBrAKvAjWwixTSDekH:bcqbwi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c195e1704abad053853f8a7de2203c74ffea09e/pkg/sql/opt/ops/oporder/limit.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

[nit] maybe name this file `limit_offset.go`
___
*[pkg/sql/opt/ops/oporder/lookup_join.go, line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBpsf39SYwIPi3byoQ:-LQBpsf39SYwIPi3byoR:b-bnzsd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/15fc7d8c946e60c0115f334858bf2028534d7043/pkg/sql/opt/ops/oporder/lookup_join.go#L23)):*
> ```Go
> 
> func lookupOrIndexJoinCanProvideOrdering(expr memo.RelExpr, required *props.OrderingChoice) bool {
> 	// LookupJoin and IndexJoin can pass through its ordering if the ordering
> ```

[nit] its -> their
___
*[pkg/sql/opt/ops/oporder/lookup_join.go, line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQC73YR6kTA-Tn6yAcp:-LQC73YS443TfS-LXIDP:b-px8967) ([raw file](https://github.com/cockroachdb/cockroach/blob/12d862e96f4e03071901d9ca0da97c2643fdbac4/pkg/sql/opt/ops/oporder/lookup_join.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

[nit] Maybe name this file `lookup_index_join.go` or something like that?
___
*[pkg/sql/opt/ops/oporder/scan.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBiGPJByPyzwdSFlQR:-LQBiGPKEYmFfSj1cVVP:bfu4lg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/scan.go#L37)):*
> ```Go
> // required ordering, according to ScanCanProvideOrdering.
> func ScanIsReverse(scan *memo.ScanExpr, required *props.OrderingChoice) bool {
> 	ok, reverse := ScanPrivateCanProvideOrdering(
> ```

It's unfortunate that we need to call this function multiple times. I guess that's what we were doing before, but maybe with this new architecture there is an opportunity to avoid that?
___
*[pkg/sql/opt/ops/oporder/scan_test.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBkNAF9BXfrfK4abSa:-LQBkNAF9BXfrfK4abSb:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/scan_test.go#L29)):*
> ```Go
> )
> 
> func TestScan(t *testing.T) {
> ```

Nice tests!
___
*[pkg/sql/opt/xform/custom_funcs.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBkn54EHEY9NakfPtO:-LQBkn54EHEY9NakfPtP:b2a5qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/xform/custom_funcs.go#L408)):*
> ```Go
> ) *memo.ScanPrivate {
> 	// Determine the scan direction necessary to provide the required ordering.
> 	_, reverse := oporder.ScanPrivateCanProvideOrdering(c.e.mem.Metadata(), scanPrivate, &ordering)
> ```

should you change this one to `ScanIsReverse`?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr_format.go, line 540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBfs2x5GZyCNW5rZlM:-LQEDpKQ9z5i7Cg32f7B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/memo/expr_format.go#L540)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Which code? What package is it in?
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQECyKcEJEhTOHst_HJ:b-igxauq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] `oporder` kind of breaks our naming convention. Maybe `optorder` fits a bit better? Also, I'm not convinced that it should be inside `ops`. Maybe it should be its own package under `opt`?
</blockquote></details>

It's oporder as in operator-specific ordering. I put it in ops because i see it as almost an extended "definition" of operators. I don't have a strong preference for where it should live. Is there a reason you prefer it to be under `opt`?
___
*[pkg/sql/opt/ops/oporder/limit.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBrAKvAjWwixTSDekG:-LQEEGe2EsHEtnEQNXDx:b-n9vcii) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c195e1704abad053853f8a7de2203c74ffea09e/pkg/sql/opt/ops/oporder/limit.go#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe name this file `limit_offset.go`
</blockquote></details>

I don't think we need to be this specific with filenames.
___
*[pkg/sql/opt/ops/oporder/lookup_join.go, line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBpsf39SYwIPi3byoQ:-LQEET8z8Yl4PMVAg0Hq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15fc7d8c946e60c0115f334858bf2028534d7043/pkg/sql/opt/ops/oporder/lookup_join.go#L23)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] its -> their
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/oporder/scan.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBiGPJByPyzwdSFlQR:-LQEEtIt7LHKEY8MWsNM:bea6t24) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/scan.go#L37)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It's unfortunate that we need to call this function multiple times. I guess that's what we were doing before, but maybe with this new architecture there is an opportunity to avoid that?
</blockquote></details>

I don't see an easy way how. If it turns out to be a perf issue, we can make `ScanIsReverse` faster (it can just look at the first column in the ordering and the corresponding index column).
___
*[pkg/sql/opt/xform/custom_funcs.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBkn54EHEY9NakfPtO:-LQEEoivEGuSleOw4XIX:b-5z4cg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/xform/custom_funcs.go#L408)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should you change this one to `ScanIsReverse`?
</blockquote></details>

We don't have the `ScanExpr` here, just the private. I think that with the new representation we can change rules to pass around expressions rather than privates, but I didn't want to tackle that right now.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQEaL1G7_80WxbnlBf_:b-hz0bmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's oporder as in operator-specific ordering. I put it in ops because i see it as almost an extended "definition" of operators. I don't have a strong preference for where it should live. Is there a reason you prefer it to be under `opt`?
</blockquote></details>

Ohh I see. In that case why not just call it `order`?

In my mind, `ops` should be reserved for the specs that optgen uses to generate code for expressions and operations. We have lots of other operator-specific code throughout the opt package. And `order` doesn't seem that different than some other top-level directories like `props`. 

But I really don't feel that strongly... maybe @andy-kimball has an opinion?
___
*[pkg/sql/opt/ops/oporder/scan.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBiGPJByPyzwdSFlQR:-LQE_zo66qq8clKvnVti:b-y4vxly) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/scan.go#L37)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't see an easy way how. If it turns out to be a perf issue, we can make `ScanIsReverse` faster (it can just look at the first column in the ordering and the corresponding index column).
</blockquote></details>

Sounds good - something we can keep an eye on, anyway

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQEjGhc68R5LwEZQGdQ:b-4g3hkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ohh I see. In that case why not just call it `order`?

In my mind, `ops` should be reserved for the specs that optgen uses to generate code for expressions and operations. We have lots of other operator-specific code throughout the opt package. And `order` doesn't seem that different than some other top-level directories like `props`. 

But I really don't feel that strongly... maybe @andy-kimball has an opinion?
</blockquote></details>

`opt/order` seems ok to me (it feels a bit too general but maybe that's ok). Or maybe `opt/ordering`, and I could rename the main APIs to `ordering.CanProvide` and `ordering.BuildChildRequired`. I'll let Andy chip in before I start moving stuff.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQF0PKi3jCNKtcHSck8:bgw1f7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`opt/order` seems ok to me (it feels a bit too general but maybe that's ok). Or maybe `opt/ordering`, and I could rename the main APIs to `ordering.CanProvide` and `ordering.BuildChildRequired`. I'll let Andy chip in before I start moving stuff.
</blockquote></details>

I'd be fine with `opt/ordering`.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ordering/main_test.go, line 23 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQFJDf18IW3dqIJwEyO:-LQFKHxNBOxxWCcNINi6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64dba8d2f02e6b0257a46fa3d3066573154b74e7/pkg/sql/opt/ordering/main_test.go#L23)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] it's opt.Expr
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/oporder/doc.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32018#-LQBgJ5YBSfELGTr5gMS:-LQFGitHAAHpxLAgQ62J:b4dyq6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfd645a1191a06d290f7e4a32c3dc2f42685cef2/pkg/sql/opt/ops/oporder/doc.go#L16)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd be fine with `opt/ordering`.
</blockquote></details>

Done (and squashed all commits).

**Review by rytaft — APPROVED** [review]
> Reviewed 18 of 19 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32018)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
