### PR TITLE
sql: add refcursor type

### LINKED ISSUE #111560: sql: add support for the refcursor data type
PG has a special type `REFCURSOR`, which is basically a string, but is used to hold the name of a PLpgSQL cursor. While it's generally used as a variable in a PLpgSQL routine, it can also be used in other contexts (e.g. function parameter or return type, table column type etc.). The type isn't recognized by previous versions of CRDB, so we'll have to add validation to ensure that statements that use `REFCURSOR` fail until the cluster is fully upgraded to 23.2.

Jira issue: CRDB-31968

### PR DESCRIPTION
**Pull request by DrewKimball**
#### types: remove pg_lsn from postgresPredefinedTypeIssues

This patch removes pg_lsn from the list of predefined types in
postgres that aren't yet supported, since it can now be parsed.

Informs #105130

Release note: None

#### sql: check unsupported types during schema changes and type/function creation

It is necessary to check the cluster version when building an expression
that references a newly-added type, in order to ensure that all nodes
support that type. Previously, these checks were omitted for casts in
the vectorized engine, expressions for partial index predicates and
check constraints, function parameters and return types, and user-defined
composite types.

This patch adds version-checking for function/procedure parameters and
return types, as well as for user-defined types. It also augments the
type-checking logic for casts and type annotations with a version
check; this handles the remaining cases. The execution-time checks
for cast expressions are left untouched, just in case the new
type-checking logic misses important cases.

For now, these changes only apply to the `PG_LSN` type, which will
be new in 23.2. A future commit will add support for `REFCURSOR`, and
will need to use the same checks.

Informs #111560

Release note: None

#### sql: add support for REFCURSOR data type

This patch adds support for the `REFCURSOR` type. It is a special type
used to hold the name of a cursor for PLpgSQL, although it can be used
in other contexts (like function return types or column types). `REFCURSOR`
is a string under the hood, and behaves like the `TEXT` data type in most
cases.

`REFCURSOR` has no casts in the `pg_cast` table; instead, all of its
casts are the "IO" string casts. That means that there is an assignment
cast from every type to `REFCURSOR`, and an explicit cast from `REFCURSOR`
to every other type (except other string types, which are again assignment).
See `ContextOriginAutomaticIOConversion` in `cast.go` for more info.

This patch also adds `REFCURSOR` to the checks from the previous commit,
so that statements with `REFCURSOR` are disallowed unless all nodes
are running v23.2.

Fixes #111560

Release note (sql change): Added support for the `REFCURSOR` data type.
`REFCURSOR` is a special string type that is used to handle cursors.
PLpgSQL cursor declarations are required to use a variable of type
`REFCURSOR`, and the name of a cursor can be passed to and from a
PLpgSQL function or procedure.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work on this. Just some questions and suggestions.

It doesn't have to be part of this PR, but during stability period let's try to add `REFCURSOR` to `pkg/sql/sem/eval/cast_test/testdata/types.txt` so that we can compare our casts to Postgres' casts of the type.

> Reviewed 13 of 13 files at r1, 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-Nflq0MlB4EwgHbv1UXY:brulrnv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @DrewKimball, and @yuzefovich)

___
*[`pkg/sql/sem/tree/type_check.go` line 3431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NflcTeMExssTTVMKlLt:-NflcTeMExssTTVMKlLu:b-diz6ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/db31fb4208e4c48be4c9eee08c9f7c2dbb827579/pkg/sql/sem/tree/type_check.go#L3431)):*
> ```Go
> func CheckUnsupportedType(ctx context.Context, version clusterversion.Handle, typ *types.T) error {
> 	if version == nil {
> 		return nil
> ```

When will version be nil?
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfldmHdAON561Xc820W:-NfldmHdAON561Xc820X:b-22th63) ([raw file](https://github.com/cockroachdb/cockroach/blob/db31fb4208e4c48be4c9eee08c9f7c2dbb827579/pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed#L65)):*
> ```
> 
> # ----------------------------------------------------------------------
> # Verify that PG_LSN is not allowed after upgrading the gateway.
> ```

Nice upgrade testcases! Do you think it would be worth adding a testcase that successfully uses PG_LSN after upgrading all nodes and finalizing? (And same comment about the REFCURSOR upgrade testcases?) (I'm willing to accept the argument that this is already handled by the non-upgrade testcases.)
___
*[`pkg/sql/logictest/testdata/logic_test/refcursor` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NflpK-GBjMxJhOPdHqU:-NflpK-GBjMxJhOPdHqV:b-9ryuhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5726afb0e3255edc9e0f04440de4f4f5ad85c5/pkg/sql/logictest/testdata/logic_test/refcursor#L87)):*
> ```
> (100,bar)
> 
> # Function that returns REFCURSOR.
> ```

request: Could you also add a testcase with a function that returns a heterogeneous tuple of REFCURSOR and some other types? (Or maybe a composite type that contains REFCURSOR.)

**Review by DrewKimball — COMMENTED** [review]
>It doesn't have to be part of this PR, but during stability period let's try to add `REFCURSOR` to `pkg/sql/sem/eval/cast_test/testdata/types.txt` so that we can compare our casts to Postgres' casts of the type.

Opened an issue: https://github.com/cockroachdb/cockroach/issues/111618

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-NfoFvP970zB138o3OMc:b14kvjd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @michae2, and @yuzefovich)

___
*[`pkg/sql/sem/tree/type_check.go` line 3431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NflcTeMExssTTVMKlLt:-NfmMUFZ5NHCi80QHhs7:b47reed) ([raw file](https://github.com/cockroachdb/cockroach/blob/db31fb4208e4c48be4c9eee08c9f7c2dbb827579/pkg/sql/sem/tree/type_check.go#L3431)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

When will version be nil?
</blockquote></details>

Sometimes `SemaContext` is unset (especially for tests), and sometimes not all the fields are initialized. I added a comment.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfldmHdAON561Xc820W:-Nfo2wQj9Q4L61BhoaQG:b-n4fw30) ([raw file](https://github.com/cockroachdb/cockroach/blob/db31fb4208e4c48be4c9eee08c9f7c2dbb827579/pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed#L65)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Nice upgrade testcases! Do you think it would be worth adding a testcase that successfully uses PG_LSN after upgrading all nodes and finalizing? (And same comment about the REFCURSOR upgrade testcases?) (I'm willing to accept the argument that this is already handled by the non-upgrade testcases.)
</blockquote></details>

I found that even with a retry, that test still occasionally fails with the "not supported" error. There's probably a way we could make it work, but it just doesn't seem worth it when we're already testing elsewhere.
___
*[`pkg/sql/logictest/testdata/logic_test/refcursor` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NflpK-GBjMxJhOPdHqU:-NfoEDHR8CdU5Jv8puRV:b-gh93gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f5726afb0e3255edc9e0f04440de4f4f5ad85c5/pkg/sql/logictest/testdata/logic_test/refcursor#L87)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

request: Could you also add a testcase with a function that returns a heterogeneous tuple of REFCURSOR and some other types? (Or maybe a composite type that contains REFCURSOR.)
</blockquote></details>

Good idea, Done.

**Comment by DrewKimball** [comment]
@michae2 I had to refactor the `SemaContext` changes a bit to make bazel happy, could you take another look at that?

**Review by michae2 — COMMENTED** [review]
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @DrewKimball, and @yuzefovich)

___
*[`pkg/sql/sem/tree/type_check.go` line 3438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfrtflYEjgKdL-446qP:-NfrtflYEjgKdL-446qQ:b-y1nurt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/sem/tree/type_check.go#L3438)):*
> ```Go
> // the current cluster version. If the given version handle is nil,
> // CheckUnsupportedType returns nil.
> func CheckUnsupportedType(ctx context.Context, semaCtx *SemaContext, typ *types.T) error {
> ```

I could be wrong, but it looks like we're always calling this sometime after a call to `tree.ResolveType`. Would it make sense for this check to be the responsibility of `tree.ResolveType`, instead of creating this new function? Perhaps by injecting the version into the `TypeReferenceResolver` (which semaCtx also has)?

**Review by yuzefovich — COMMENTED** [review]
Nice work figuring it all out! I have some nits and questions for your consideration. Perhaps it might be good to get a sign off from our Foundations friends too.

> Reviewed 34 of 34 files at r3, 27 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-Nfs3zYqAG9apWZA5tk8:b-nfafrg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @DrewKimball)

___
*[`pkg/sql/catalog/colinfo/col_type_info.go` line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfs1bJm4yTZYc1eI1gx:-Nfs1bJm4yTZYc1eI1gy:bssgs4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5bd000dd3c47d763029f818e9616f8882c561a/pkg/sql/catalog/colinfo/col_type_info.go#L81)):*
> ```Go
> 			}
> 		}
> 		if t.Oid() == oid.T_refcursor {
> ```

Curious, do we not need the same check for `pg_lsn` type because it cannot be used in the column definition but `refcursor` can?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfrx0h5ByR01AkQ619B:-Nfrx0h6-Jte3xDsgEfA:b-km562g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/opt/optbuilder/create_function.go#L310)):*
> ```Go
> 	ctx context.Context, semaCtx *tree.SemaContext, expected *types.T, cols []scopeColumn,
> ) error {
> 	// The return type must be supported by the current cluster version.
> ```

nit: perhaps adjust the comment to also mention that all argument types must be supported too? (Is "cols" arguments to the function?)
___
*[`pkg/sql/sem/tree/type_check.go` line 3430 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfrxieS2E6Wm5MNMDX5:-NfrxieS2E6Wm5MNMDX6:b-nukfu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/sem/tree/type_check.go#L3430)):*
> ```Go
> type UnsupportedTypeChecker interface {
> 	// CheckType returns an error if the given type is not supported by the
> 	// current cluster version. If the given version handle is nil, CheckType
> ```

nit: where is the "version handle" coming from? Perhaps mention explicitly that it's an argument to `eval.NewUnsupportedTypeChecker`.
___
*[`pkg/sql/types/types.go` line 2944 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfryAgrB5HZvkilAPRM:-NfryAgrB5HZvkilAPRN:b-sfwv5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef2fd68a7f25fd699d673fc2c4ab5c650979ad16/pkg/sql/types/types.go#L2944)):*
> ```Go
> 	"money":         41578,
> 	"path":          21286,
> 	"pg_lsn":        -1,
> ```

nit: this change seems out of place. IIUC we should've removed it earlier when we introduced support for `pg_lsn` type, so perhaps extract it into a separate commit?
___
*[`pkg/sql/types/types.go` line 739 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfs2nQQ324ethbhhCLP:-Nfs2nQQ324ethbhhCLQ:b-96mkx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5bd000dd3c47d763029f818e9616f8882c561a/pkg/sql/types/types.go#L739)):*
> ```Go
> 	visibleQCHAR = 9
> 
> 	visibleREFCURSOR = 202
> ```

Why do we need this? Did we allow refcursor type pre-23.2 and it had a different type representation that we need to upgrade now?

(Side note: it seems that we could easily remove all other `visible*` constants because the oldest version that might be using is 19.1, so the upgrades must have been performed, right?)
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfryaskD-nY3reRNai3:-NfryaskD-nY3reRNai4:bdetbph) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed#L71)):*
> ```
> 
> # ----------------------------------------------------------------------
> # Verify that PG_LSN is not allowed after upgrading the gateway.
> ```

nit: shouldn't this file also check that once the cluster is upgraded, PG_LSN is allowed? Is that beyond the scope of mixed version tests?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @michae2, and @yuzefovich)

___
*[`pkg/sql/catalog/colinfo/col_type_info.go` line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfs1bJm4yTZYc1eI1gx:-NftG3DD1zPe-i5ivrk1:b-peyzvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5bd000dd3c47d763029f818e9616f8882c561a/pkg/sql/catalog/colinfo/col_type_info.go#L81)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Curious, do we not need the same check for `pg_lsn` type because it cannot be used in the column definition but `refcursor` can?
</blockquote></details>

`PG_LSN` is checked below - it has its own family.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfrx0h5ByR01AkQ619B:-NftG86h4INEwEuZOB88:b-x6fjea) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/opt/optbuilder/create_function.go#L310)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps adjust the comment to also mention that all argument types must be supported too? (Is "cols" arguments to the function?)
</blockquote></details>

Actually, `cols` is the columns returned by the last body statement, while `expected` is the explicitly defined function return type that those columns must conform to.
___
*[`pkg/sql/sem/tree/type_check.go` line 3430 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfrxieS2E6Wm5MNMDX5:-NftGYHo-rMMKDjuAfNA:bkbscw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/sem/tree/type_check.go#L3430)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: where is the "version handle" coming from? Perhaps mention explicitly that it's an argument to `eval.NewUnsupportedTypeChecker`.
</blockquote></details>

Ah, that comment is stale. I'll fix it.
___
*[`pkg/sql/sem/tree/type_check.go` line 3438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfrtflYEjgKdL-446qP:-NftGucH5k-hDrwezRfF:bt3mtt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/sem/tree/type_check.go#L3438)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I could be wrong, but it looks like we're always calling this sometime after a call to `tree.ResolveType`. Would it make sense for this check to be the responsibility of `tree.ResolveType`, instead of creating this new function? Perhaps by injecting the version into the `TypeReferenceResolver` (which semaCtx also has)?
</blockquote></details>

`tree.ResolveType` confusingly doesn't always go through the type resolver, and whether it does for the test cases seems to depend on the test configuration. I think it might be because we parse directly into `*types.T`. I could spend more time figuring it out, but I don't think it's worth it unless this method is really distressing.
___
*[`pkg/sql/types/types.go` line 2944 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfryAgrB5HZvkilAPRM:-NftJUa58V8E4B_OQnQZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef2fd68a7f25fd699d673fc2c4ab5c650979ad16/pkg/sql/types/types.go#L2944)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this change seems out of place. IIUC we should've removed it earlier when we introduced support for `pg_lsn` type, so perhaps extract it into a separate commit?
</blockquote></details>

Done.
___
*[`pkg/sql/types/types.go` line 739 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfs2nQQ324ethbhhCLP:-NftZYhsD5GhuaCHdesA:bv6wrpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5bd000dd3c47d763029f818e9616f8882c561a/pkg/sql/types/types.go#L739)):*
Good point. I tried this before, but failed to intercept the OID setting for string types in `upgradeType`. Done.

>(Side note: it seems that we could easily remove all other `visible*` constants because the oldest version that might be using is 19.1, so the upgrades must have been performed, right?)

It seems like it... though I don't think I'm willing to rock that boat at the moment.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfryaskD-nY3reRNai3:-NftJZI39DaZ3eDXvNBO:bnsdmh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/logictest/testdata/logic_test/pg_lsn_mixed#L71)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: shouldn't this file also check that once the cluster is upgraded, PG_LSN is allowed? Is that beyond the scope of mixed version tests?
</blockquote></details>

That would be ideal, but even with a retry loop the cluster version still doesn't always propagate in time for the test to succeed. If you have any ideas we can try them, but otherwise I think the other logic tests are enough coverage.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r5, 12 of 12 files at r6, 25 of 25 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-NfvPBpc12U6g4b-BFBQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @michae2)

___
*[`pkg/sql/catalog/colinfo/col_type_info.go` line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Nfs1bJm4yTZYc1eI1gx:-NfvNjXA4ZgbOFBq9OqH:bvryl1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5bd000dd3c47d763029f818e9616f8882c561a/pkg/sql/catalog/colinfo/col_type_info.go#L81)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`PG_LSN` is checked below - it has its own family.
</blockquote></details>

Indeed, nvm.

**Review by ecwall — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @DrewKimball, and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_refcursor` line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfvUq7o8_pAcx6sHPh9:-NfvUq7o8_pAcx6sHPhA:b-xasd61) ([raw file](https://github.com/cockroachdb/cockroach/blob/9868ce861cd5fb52467ce576d54a232700e80df0/pkg/sql/logictest/testdata/logic_test/mixed_version_refcursor#L1)):*
> ```
> # LogicTest: cockroach-go-testserver-upgrade-to-master
> ```

Can you split this and the other logic tests into subtests?

Also, it looks like some of the test cases are copied - can the logic test configs be merged together into 1 file so that it is harder for the test cases to drift apart in the future? I think we probably need some way of asserting different outcomes for the same statement based on which config ran.

Nice to see cross version tests BTW.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @ecwall, @michae2, and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/mixed_version_refcursor` line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfvUq7o8_pAcx6sHPh9:-Nfvg_b20vmFjfS47GOI:biphlav) ([raw file](https://github.com/cockroachdb/cockroach/blob/9868ce861cd5fb52467ce576d54a232700e80df0/pkg/sql/logictest/testdata/logic_test/mixed_version_refcursor#L1)):*
Thanks for taking a look.

>Can you split this and the other logic tests into subtests?

Done.

>Also, it looks like some of the test cases are copied - can the logic test configs be merged together into 1 file so that it is harder for the test cases to drift apart in the future? I think we probably need some way of asserting different outcomes for the same statement based on which config ran.

I tried moving the `refcursor` tests to the `mixed_version_refcursor` file after upgrading all nodes, but it caused the test to become flaky since the upgrade doesn't always propagate in time even with the retry directive.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 2 of 27 files at r4, 34 of 34 files at r5, 8 of 12 files at r6, 26 of 26 files at r8, 25 of 25 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-NfwxKo2-X5PbmwgABmX:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @ecwall)

___
*[`pkg/sql/sem/tree/type_check.go` line 3438 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-NfrtflYEjgKdL-446qP:-Nfwtlqa-sD76pANC0Tu:b-h8iywk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eef52b1f8cc404fa72c70d0e46a3deb540d31f0/pkg/sql/sem/tree/type_check.go#L3438)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`tree.ResolveType` confusingly doesn't always go through the type resolver, and whether it does for the test cases seems to depend on the test configuration. I think it might be because we parse directly into `*types.T`. I could spend more time figuring it out, but I don't think it's worth it unless this method is really distressing.
</blockquote></details>

Thanks for looking into it. I am fine with your current approach.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
*[`pkg/sql/sem/cast/cast_map.go` line 643 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Ng-Iw3b1tvF8EWNSw0E:-Ng-Iw3b1tvF8EWNSw0F:bwee8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/880df4c71a6acc22f9f2ede330051436600564a9/pkg/sql/sem/cast/cast_map.go#L643)):*
> ```Go
> 		oidext.T_box2d: {MaxContext: ContextExplicit, origin: ContextOriginAutomaticIOConversion, Volatility: volatility.Immutable},
> 		oid.T_pg_lsn:   {MaxContext: ContextExplicit, origin: ContextOriginAutomaticIOConversion, Volatility: volatility.Immutable},
> 		oid.T_bytea:    {MaxContext: ContextExplicit, origin: ContextOriginAutomaticIOConversion, Volatility: volatility.Immutable},
> ```

None of these explicit casts are allowed by Postgres, AFAICT. We should remove them.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/cast/cast_map.go` line 489 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Ng-Gikl3doHQ_elCFT6:-Ng-Gikl3doHQ_elCFT7:b-7kfpvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/880df4c71a6acc22f9f2ede330051436600564a9/pkg/sql/sem/cast/cast_map.go#L489)):*
> ```Go
> 			origin:         ContextOriginAutomaticIOConversion,
> 			Volatility:     volatility.Stable,
> 			VolatilityHint: "INTERVAL to REFCURSOR casts depend on IntervalStyle; consider using to_char(interval)",
> ```

I'm not convinced there should be assignment casts from _every_ type to the REFCURSOR type. For example, assigment casts from INTERVAL to REFCUROSR are not allowed in Postgres:

```
marcus=# CREATE TABLE t (r REFCURSOR);
CREATE TABLE

marcus=# INSERT INTO t VALUES ('1'::INTERVAL);
ERROR:  42804: column "r" is of type refcursor but expression is of type interval
LINE 1: insert into t values ('1'::INTERVAL);
                              ^
HINT:  You will need to rewrite or cast the expression.
LOCATION:  transformAssignedExpr, parse_target.c:594
```

In fact, assignment casts from any of the string-like types to REFCURSOR are also not supported by Postgres:

```
marcus=# INSERT INTO t VALUES ('1'::VARCHAR);
ERROR:  42804: column "r" is of type refcursor but expression is of type character varying

marcus=# INSERT INTO t VALUES ('1'::TEXT);
ERROR:  42804: column "r" is of type refcursor but expression is of type text

marcus=# INSERT INTO t VALUES ('1'::BPCHAR);
ERROR:  42804: column "r" is of type refcursor but expression is of type character

marcus=# INSERT INTO t VALUES ('a'::CHAR);
ERROR:  42804: column "r" is of type refcursor but expression is of type character

marcus=# INSERT INTO t VALUES ('a'::NAME);
ERROR:  42804: column "r" is of type refcursor but expression is of type name
```

The IO casts you're describing allow any type to be implicitly cast to the 5 string-like types:

```
marcus=# SELECT pg_typeof('a'::TEXT || '1'::REFCURSOR);
 pg_typeof
-----------
 text
```

So I think we should keep the REFCURSOR -> TEXT/VARCHAR/NAME/BPCHAR/CHAR casts and remove all the rest that were added in this commit.

**Comment by mgartner** [comment]
*[`pkg/sql/types/types_test.go` line 782 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-Ng-JGCM6NqhOFx5FCWB:-Ng-JGCM6NqhOFx5FCWC:b-ltbf05) ([raw file](https://github.com/cockroachdb/cockroach/blob/880df4c71a6acc22f9f2ede330051436600564a9/pkg/sql/types/types_test.go#L782)):*
> ```Go
> 		{QChar, InternalType{Family: StringFamily, Oid: oid.T_char, Width: 1, VisibleType: visibleQCHAR}},
> 		{Name, InternalType{Family: name, Oid: oid.T_name}},
> 		{RefCursor, InternalType{Family: StringFamily, Oid: oid.T_refcursor}},
> ```

I'd argue that this should be a different type family. What's the motivation for re-using the StringFamily?

**Review by mgartner — COMMENTED** [review]
Nice work! Apologies for the late drive-by. I left some comments about the casts and type family.

> Reviewed 34 of 34 files at r10, 12 of 12 files at r11, 25 of 25 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111392#-:-Ng-KEgW2pGPpm9xZA05:b6jeq8o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by DrewKimball** [comment]
>In fact, assignment casts from any of the string-like types to REFCURSOR are also not supported by Postgres:

Even explicit casts aren't supported... I though I checked this, but clearly not.

>I'd argue that this should be a different type family. What's the motivation for re-using the StringFamily?

I originally thought that REFCURSOR basically behaves like text, but it seems it's significantly more restrictive. I'll work on a fix.

**Pull request merged**
