### PR TITLE
tree: fix casts and parse to obey type limits

### LINKED ISSUE #54844: ALTER COLUMN TYPE to lower integer range (Ex int8 to int2) should fail
**Steps to reproduce**
```
root@127.0.0.1:55511/defaultdb> create table foo (i int8);
CREATE TABLE

root@127.0.0.1:55511/defaultdb> insert into foo values (-9223372036854775807);
INSERT 1

root@127.0.0.1:55511/defaultdb> SET enable_experimental_alter_column_type_general = true;

root@127.0.0.1:55511/defaultdb> alter table foo alter column i type int2;
NOTICE: ALTER COLUMN TYPE changes are finalized asynchronously; further schema changes on this table may be restricted until the job completes; some writes to the altered column may be rejected until the schema change is finalized
ALTER TABLE

root@127.0.0.1:55511/defaultdb> show create foo;
  table_name |        create_statement
-------------+----------------------------------
  foo        | CREATE TABLE public.foo (
             |     i INT2 NULL,
             |     FAMILY "primary" (i, rowid)
             | )
(1 row)
```

**Desired behavior**
Our [docs](https://www.cockroachlabs.com/docs/v20.1/alter-column.html#altering-column-types) indicate that only increasing precision is allowed and that the existing data must remain valid. This `ALTER COLUMN TYPE` violates that.

I realized I was looking at 20.1 docs, but there's no mention in [20.2 docs](https://www.cockroachlabs.com/docs/dev/alter-column.html#altering-column-data-types) that this would be valid.

In PG,
```
vy=# alter table foo alter column i type int2;
ERROR:  smallint out of range
```

### PR DESCRIPTION
**Pull request by otan**
Resolves #54844

A more general solution for this should be #55094.

Release note (bug fix): Previously, casts and parsing of strings to
types may allow an out-of-bounds value to be successfully used (e.g.
SELECT -232321321312::int2 would work), but fail with an out-of-bounds
message when it is inserted into the table. This has been rectified to
instead be checked when the value is parsed or being casted to.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
the logic lgtm! had questions about error messages and testing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-:-MMr5QOL0crUn7OU82IZ:b-cqjx4x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @solongordon)

___
*[pkg/sql/sem/tree/casts.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr5Gtc4Q2cafgGYN80:-MMr5Gtc4Q2cafgGYN81:b-c156qy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L383)):*
> ```Go
> }
> 
> // AdjustValueToType checks that the width (for strings, byte arrays, and bit
> ```

Would be nice if this function could get unit-tested. Is that do-able?
___
*[pkg/sql/sem/tree/casts.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr3Tjv5m2DcckgFLDc:-MMr3Tjv5m2DcckgFLDd:b-jhn8ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L404)):*
> ```Go
> // only occur during casting and parsing but not update/inserts (see
> // enforceLocalColumnConstraints).
> func AdjustValueToType(typ *types.T, inVal Datum) (outVal Datum, err error) {
> ```

Perhaps we should preserve the string parameter but make it optional so that the error message still remains as helpful as it can be for INSERT and UPDATE?
___
*[pkg/sql/sem/tree/parse_string.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr4zvV2o_5e1P83-5g:-MMr4zvV2o_5e1P83-5h:bigkwt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/parse_string.go#L35)):*
> ```Go
> 			return nil, false, err
> 		}
> 		d = formatBitArrayToType(r, t)
> ```

is there a test for this new error case for string parsing?
___
*[pkg/sql/sem/tree/parse_string.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr54ya1ORinvzjiKrd:-MMr54ya1ORinvzjiKre:b-2ggzmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/parse_string.go#L96)):*
> ```Go
> 		return d, dependsOnContext, err
> 	}
> 	d, err = AdjustValueToType(t, d)
> ```

and for this error case?

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/casts.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr5Gtc4Q2cafgGYN80:-MMrYK1p3NzlKTi9gLZ9:b-177e5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L383)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Would be nice if this function could get unit-tested. Is that do-able?
</blockquote></details>

i've spot checked these to be covered by logic tests or eval tests already.
i think there's value to refactoring all of these such that this function does not exist anymore, but that should come down the road. if you feel strongly i can give it a go.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/sem/tree/casts.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr3Tjv5m2DcckgFLDc:-MMrLrsH-YHJnIKacNy8:bqedazk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L404)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Perhaps we should preserve the string parameter but make it optional so that the error message still remains as helpful as it can be for INSERT and UPDATE?
</blockquote></details>

In theory no, because now INSERT/UPDATE is no longer in charge of asserting width (ParseAndRequireString is). In theory, we can remove the logic from there but I think it's safer we do it just in case I missed something.
___
*[pkg/sql/sem/tree/parse_string.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr4zvV2o_5e1P83-5g:-MMrLdIr3fDNCnTvMnk2:b-hpgcfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/parse_string.go#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a test for this new error case for string parsing?
</blockquote></details>

yes -- since the logic from the existing bit (https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/bit#L43) is demoted to a lower level.
___
*[pkg/sql/sem/tree/parse_string.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr54ya1ORinvzjiKrd:-MMrLmPO4p2qlSZULlaC:b-ybffv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/parse_string.go#L96)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and for this error case?
</blockquote></details>

yes, because the invalid INSERT cases have moved to this level.

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rafiss, and @solongordon)

___
*[pkg/sql/sem/tree/casts.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr5Gtc4Q2cafgGYN80:-MMrjrVg0M2MC6f4jHUT:bpt9gru) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L383)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i've spot checked these to be covered by logic tests or eval tests already.
i think there's value to refactoring all of these such that this function does not exist anymore, but that should come down the road. if you feel strongly i can give it a go.
</blockquote></details>

well as a general rule i think our code base should move in a direction of favoring unit tests over logic tests when possible. or maybe in a direction of having both whenever possible. but i think with the state a lot of code is in, refactors may be needed to get to a unit-testable state. anyway, not something that needs to be done now
___
*[pkg/sql/sem/tree/casts.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr3Tjv5m2DcckgFLDc:-MMrjn2Y46ScsETYwlzB:bnd81ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/casts.go#L404)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

In theory no, because now INSERT/UPDATE is no longer in charge of asserting width (ParseAndRequireString is). In theory, we can remove the logic from there but I think it's safer we do it just in case I missed something.
</blockquote></details>

yeah better to stay safe 
___
*[pkg/sql/sem/tree/parse_string.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55095#-MMr4zvV2o_5e1P83-5g:-MMrjdSXACYSHFiUNgcb:b-2bf08y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad14ed0f1d4190e74e499b120287233f6fbe8859/pkg/sql/sem/tree/parse_string.go#L35)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yes -- since the logic from the existing bit (https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/bit#L43) is demoted to a lower level.
</blockquote></details>

ah got it so that's the reason why we can't have the column name any more. annoying

**Comment by otan** [comment]
bors r=rafiss

**Comment by yuzefovich** [comment]
Just noticed that this wasn't backported to 20.2, should it be? Or at least a subset of integer out of range casts? @otan @rafiss

**Comment by otan** [comment]
it's a little bit on the riskier side for me, and if we do it we should backport it all the way down to 19.2

**Comment by yuzefovich** [comment]
Ack, let's not backport then until we have a user complaining about it.

**Pull request merged**
