### PR TITLE
ui: change index columns in DbSummaryTables from 'Indices'->'Indexes'

### LINKED ISSUE #56385: adminui: databases page: should says "indexes", not "indices"
Screen Shot 2020-11-06 at 3 20 04 PM

When referring to databases, the common plural is "indexes". That's what we've settled on a long time ago. The docs verify this, although there are a couple of unfortunate slips.

### PR DESCRIPTION
**Pull request by abarganier**
Small cosmetic change to make copy more consistent in the DB Console UI.

Resolves #56385

Release justification: None. Safe, low impact cosmetic change.
Release note: None

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
> ui: update index column headers in DatabaseSummaryTables to read 'indexes' instead of 'indices.

This commit title feels a little long, might cause wrapping issues, I aim for a max of ~70 characters.
Our guidelines on this are not strict at the moment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61146#-:-MUQeH6d4Au_WL3IR_Tz:b-pxi410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Comment by ajwerner** [comment]
https://www.youtube.com/embed/cEXJqPK35mA?start=2657&end=2687

**Comment by abarganier** [comment]
@dhartunian thanks for the guidance, updated the commit title to be more brief / <= 70 chars.

@ajwerner go team indexes! 😄

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61146#-:-MUV86gu35pQBaFlaZoX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nathanstilwell)

**Pull request merged**
