### PR TITLE
tlp: do not generate mutations in partitioned queries

### LINKED ISSUE #79737: tlp: do not generate mutations in partitioned/unpartitioned queries
roachtest.tlp [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4851270&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4851270&tab=artifacts#/tlp) on release-22.1 @ [4ea439798aa75b54d3e05cfcc86493d35ac12cdb](https://github.com/cockroachdb/cockroach/commits/4ea439798aa75b54d3e05cfcc86493d35ac12cdb):

```
The test failed on branch=release-22.1, cloud=gce:
test artifacts and logs in: /artifacts/tlp/run_1
	tlp.go:172,tlp.go:76,test_runner.go:875: expected unpartitioned and partitioned results to be equal
		(1) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runTLPQuery.func2
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tlp.go:245
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runWithTimeout.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tlp.go:270
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (2) expected unpartitioned and partitioned results to be equal
		  |   []string{
		  |   	strings.Join({
		  |   		"-1.829103946685791,3311348944,true,-20701.36157012891460,-631829",
		  |   		"8756515923150,2015-07-01 00:31:15.000052 +0000 +0000,89487259763",
		  |   		"54554968,0010000010100100001111011,@,w\be6,",
		  | - 		"false,tru",
		  | + 		"true,fals",
		  |   		"e,false,true,false,false",
		  |   	}, ""),
		  |   }
		  | sql: SELECT *, EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL, true, false, false FROM defaultdb.public.table2 AS tab_11015
		  | (SELECT *,
		  | EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL,
		  | EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL
		  | FROM defaultdb.public.table2 AS tab_11015
		  | WHERE EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48))
		  | UNION ALL (SELECT *,
		  | EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL,
		  | NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL
		  | FROM defaultdb.public.table2 AS tab_11015
		  | WHERE NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)))
		  | UNION ALL (SELECT *,
		  | EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48), NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)), (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL,
		  | (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL, (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NOT NULL, (NOT (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48))) IS NOT NULL
		  | FROM defaultdb.public.table2 AS tab_11015
		  | WHERE (EXISTS (SELECT (SELECT 'cplmn' AS col_5743 FROM defaultdb.public.table2@[0] AS tab_11019 WHERE tab_11019.col2_2 LIMIT 1) AS col_5744 FROM defaultdb.public.table2@[0] AS tab_11016, [INSERT INTO defaultdb.public.table3 AS tab_11017(col3_2, col3_3, col3_4, col3_5, col3_6, col3_7, col3_8, col3_10) VALUES ('{"E)jW": null, "bar": {}, "foo": [false]}', 3414623677, '08:59:00.963801+00:51:00', 'BOX(-0.3726651061892007 -0.5001501548513134,0.5464926733978004 1.015492124714179)', '22:30:19.569144', '^&>', -0.31109264492988586, '010700004000000000') RETURNING ARRAY['1990-08-21','1978-08-01'] AS ret_5], defaultdb.public.table3@[0] AS tab_11018 ORDER BY tab_11018.col3_0 ASC LIMIT 48)) IS NULL)
		  | with args: []
		Error types: (1) *withstack.withStack (2) *errutil.leafError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tlp.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by mgartner**
Previously, TLP could generate mutations in partitioned queries because
it used the same `sqlsmith.Smither` that is used for generating
mutations which add data to tables. It was thought that this would be
impossible because TLP explicitly constructs only `SELECT` statements,
but the `sqlsmith.Smither` could generate nested mutations with the
`tree.StatementSource` syntax, for example:

    SELECT * FROM t
    WHERE EXISTS (SELECT * FROM [INSERT INTO t(a) VALUES (1) RETURNING *])

Now, the TLP generator uses its own `sqlsmith.Smither` where all
mutations are disabled.

Fixes #79737

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Nice work! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81017#-:-N1GXoXi22fWu18jxkIP:bnahwna)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @msirek)

___
*[`pkg/cmd/roachtest/tests/tlp.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81017#-N1GXGy0AM6gJ6tu1suE:-N1GXGy0AM6gJ6tu1suF:b-213mcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0098a43197839589419e57f5b111b3cdb5f39e71/pkg/cmd/roachtest/tests/tlp.go#L172)):*
> ```Go
> 
> 		// Run 1000 mutations first so that the tables have rows. Run a mutation
> 		// for a tenth of the iterations after that to continually change the
> ```

nit: update comment if we're not mutating on 10% of iterations anymore.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81017)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @msirek)

___
*[`pkg/cmd/roachtest/tests/tlp.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81017#-N1GXGy0AM6gJ6tu1suE:-N1GbCmcArvNhoiFOaFJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0098a43197839589419e57f5b111b3cdb5f39e71/pkg/cmd/roachtest/tests/tlp.go#L172)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: update comment if we're not mutating on 10% of iterations anymore.
</blockquote></details>

Done.

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81017#-:-N1Giuw37Sdh1uvDssec:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
