### PR TITLE
engineccl: add randomized error injector test for encryptedFS

### PR DESCRIPTION
**Pull request by sumeerbhola**
The encryptedFS can return an error after doing part of the work, as modifying the encryption metadata and the underlying FS is not atomic. This makes some operations (rename, link, remove) non-idempotent, which is harmless for the CockroachDB use cases (since they don't retry on the same files). The test works around these by retrying in a way that makes them idempotent. Additionally, the test catches panics caused by FS errors, in order to test a node that crashes because of a panic caused by a transient error, and is subsequently restarted.

Epic: none

Informs: #96670

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-:-NaNdy2I683lQks3dBjF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaN_zo372v04F3X63QV:-NaN_zo372v04F3X63QW:bg6fkhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L448)):*
> ```Go
> // errorInjector injects errors into metadata writes involving the
> // encryptedFS, i.e., writes by the file registry and key manager. Data files
> // in the test below have names prefixed by TEST and spared this error
> ```

nit: "and are spared"
___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNaXGx1_kDq2Hi6j57:-NaNaXGx1_kDq2Hi6j58:b-77ibfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L543)):*
> ```Go
> 	// Error injection starts after initialization, to simplify the test (the
> 	// caller does not need to handle errors and call restart again).
> 	ei.startErrors()
> ```

Is there potential for a race on the `startInjecting` field? Maybe there's no asynchronous file I/O performed after initialization until the first write? Might be worth using a `atomic.Bool` just in case that changes.
___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNc81CACSWNiPGsX08:-NaNc81CACSWNiPGsX09:b-2jurg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L649)):*
> ```Go
> 	// underlying FS. and additionally call restart to get the registry into a
> 	// clean state (it elides files that are not found in the underlying FS when
> 	// loading the registry).
> ```

where does the requirement for a restart come from? If we leak a file in the registry, are the observable results of the other operations the same?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107618)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNwkm23F9h7Xwxtt6A:-NaNwkm23F9h7Xwxtt6B:b84b7np) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L811)):*
> ```Go
> }
> 
> func makeOps(rng *rand.Rand, numOps int) []fsTestOp {
> ```

I'm remembering that I let #98408 die on the vine, but it had some generic facilities for writing these kinds of tests. After this merges, I might spend a quality friday trying to use those facilities here.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-:-NaRlhLi1qQnzcTfPkED:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @jbowens)

___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaN_zo372v04F3X63QV:-NaRjbcr5XT-4QA60kdI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L448)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: "and are spared"
</blockquote></details>

Done
___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNaXGx1_kDq2Hi6j57:-NaRk5cT18w4OJ7nyeM3:b-llxm7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L543)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Is there potential for a race on the `startInjecting` field? Maybe there's no asynchronous file I/O performed after initialization until the first write? Might be worth using a `atomic.Bool` just in case that changes.
</blockquote></details>

Added a comment
```
// The test is single threaded, and there is no async IO in the lower  
// layers, so this field does not need synchronization.
```
___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 649 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNc81CACSWNiPGsX08:-NaRkKTo-reLoBj5JF4i:b-u0d7d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L649)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

where does the requirement for a restart come from? If we leak a file in the registry, are the observable results of the other operations the same?
</blockquote></details>

I believe they are. I was being defensive in trying to not know too much about the implementation details of `encryptedFS`, while still ensuring that the output will be the same as the plain FS. I've added a comment.
Clearly, I was not successful in the overall approach since `renameOp` and `linkOp` do need to understand the `encryptedFS` implementation.
___
*[`pkg/ccl/storageccl/engineccl/encrypted_fs_test.go` line 811 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107618#-NaNwkm23F9h7Xwxtt6A:-NaRlXs90KFsNsdhJVzt:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/401011e102d9d4d2392bff1a2cbe713a09b2027a/pkg/ccl/storageccl/engineccl/encrypted_fs_test.go#L811)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I'm remembering that I let #98408 die on the vine, but it had some generic facilities for writing these kinds of tests. After this merges, I might spend a quality friday trying to use those facilities here.
</blockquote></details>

:+1:

**Comment by sumeerbhola** [comment]
bors r=jbowens

**Pull request merged**
