### PR TITLE
opt: improve selectivity estimation based on null counts

### LINKED ISSUE #36157: opt: selectivity for IS NULL filter is incorrect
To reproduce:

```
EXPLAIN (OPT, VERBOSE) SELECT * FROM
((VALUES (NULL, NULL), (NULL, 1), (2, NULL)) EXCEPT (VALUES (1, 2), (2, 3), (3, 4)))
WHERE column1 IS NULL;
+----------------------------------------------------------------------------------------------+
  select                                                                                        
   ├── columns: column1:1 column2:2                                                             
   ├── cardinality: [0 - 3]                                                                     
   ├── stats: [rows=3, distinct(1)=1, null(1)=2]                                                
   ├── cost: 0.22                                                                               
   ├── key: (2)                                                                                 
   ├── fd: ()-->(1)                                                                             
   ├── except                                                                                   
   │    ├── columns: column1:1 column2:2                                                        
   │    ├── left columns: column1:1 column2:2                                                   
   │    ├── right columns: column1:3 column2:4                                                  
   │    ├── cardinality: [0 - 3]                                                                
   │    ├── stats: [rows=3, distinct(1)=1, null(1)=2, distinct(1,2)=0, null(1,2)=3]             
   │    ├── cost: 0.18                                                                          
   │    ├── key: (1,2)                                                                          
   │    ├── values                                                                              
   │    │    ├── columns: column1:1 column2:2                                                   
   │    │    ├── cardinality: [3 - 3]                                                           
   │    │    ├── stats: [rows=3, distinct(1)=1, null(1)=2, distinct(1,2)=0, null(1,2)=3]        
   │    │    ├── cost: 0.04                                                                     
   │    │    ├── (NULL, NULL)                                                                   
   │    │    ├── (NULL, 1)                                                                      
   │    │    └── (2, NULL)                                                                      
   │    └── values                                                                              
   │         ├── columns: column1:3 column2:4                                                   
   │         ├── cardinality: [3 - 3]                                                           
   │         ├── stats: [rows=3, distinct(3)=3, null(3)=0, distinct(3,4)=3, null(3,4)=0]        
   │         ├── cost: 0.04                                                                     
   │         ├── (1, 2)                                                                         
   │         ├── (2, 3)                                                                         
   │         └── (3, 4)                                                                         
   └── filters                                                                                  
        └── column1 IS NULL [outer=(1), constraints=(/1: [/NULL - /NULL]; tight), fd=()-->(1)]  
```

As shown, the estimated null count for `column1` is 2, but the row count of the select statement is 3.

### PR DESCRIPTION
**Pull request by rytaft**
This commit makes several changes to improve selectivity estimation
when there are a large number of null values.

1. It removes the code to reduce the columns used for selectivity estimation
based on functional dependencies. This reduction was only useful in a few very
specific circumstamces, and added a lot of unnecessary complexity (especially
when calculating selectivity based on null values removed).

2. It combines selectivity estimation based on null counts with the other
  selectivity estimation functions. This is much more accurate than doing it
  separately. 

For example, consider a table `t` with column `x`, which has 10 rows.
7 of the rows have `x=NULL`, and the other 3 rows have 3 distinct values.
  
To estimate the selectivity of the predicate `x=1 OR x IS NULL`, we should use
the formula:
  `sel = (new distinct / old distinct) * (1 - null fraction) + null fraction`
 ` --> sel(x) = (1/3) * (1 - 7/10) + 7/10 = 0.8`

As expected, `SELECT * FROM t WHERE x=1 OR x IS NULL` should return 8 rows.

Since it is necessary to *add* the null fraction to account for the `IS NULL`
part of the predicate, we must include it when we calculate the selectivity
for a column based on distinct counts or histograms. Column selectivities
are multiplied together to estimate the total selectivity, so it's not possible
to account for null values afterwards.

Fixes #36157

Release note (performance improvement): Improved statistics estimation
during query planning for columns with many null values.

### CODE REVIEW

**Comment by rytaft** [comment]
Apologies that there are a ton of test diffs -- I've looked over them pretty carefully and most of them are either (1) very small changes to the row count or (2) removal of column stats that aren't needed (the old code was storing column stats for every column in `NotNullCols`). There are just a few cases where the row count is significantly different, and it seems to me that almost all of those cases are an improvement.

**Comment by rytaft** [comment]
Please hold off on reviewing for a moment -- I want to make one simplifying change.

**Comment by rytaft** [comment]
Ok -- ready for review

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41520)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2963 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-Lqvcu8e8DnIWOPsEU2A:-Lqvcu8e8DnIWOPsEU2B:b-7g556b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L2963)):*
> ```Go
> 		newDistinct := colStat.DistinctCount
> 		oldDistinct := inputColStat.DistinctCount
> 		nullFraction := inputColStat.NullCount / inputStats.RowCount
> ```

Would be good to add a comment with the overall formula (what you have in the commit message). In this formula, don't we want `(colstat.NullCount / inputColStat.NullCount) * nullFraction` for the second term?
E.g. what if we only had nulls both before and after, just fewer of them after?

By the way, I'd find it easier to reason about if we were calculating the "estimated output rows" (and divide that by `inputStats.RowCount` at the end) instead of calculating the selectivity directly. In that case, the term I mentioned above would just be `colstat.NullCount`.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LqveT7a1JbKJOnkrQN9:-LqveT7a1JbKJOnkrQNA:b-tkamdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L3033)):*
> ```Go
> 
> 		// Account for the difference in null values.
> 		colSelectivity *= 1 - nullFraction
> ```

I think we should come up with a helper function given that we're using this non-trivial formula in multiple places.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-:-LrHu81D1vlYl-O6dbWY:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 2963 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-Lqvcu8e8DnIWOPsEU2A:-LrHs_1r0D1HSufdzsJx:br1gv4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L2963)):*
> Would be good to add a comment with the overall formula (what you have in the commit message). 

Added a comment above the new function `outputRowCount`

> In this formula, don't we want (colstat.NullCount / inputColStat.NullCount) * nullFraction for the second term?
> E.g. what if we only had nulls both before and after, just fewer of them after?

I think it was technically correct as written since as far as I know there's no way for the null count to decrease partially based on a single column predicate. But I agree it makes things clearer in the formula, so I've made the change.

> By the way, I'd find it easier to reason about if we were calculating the "estimated output rows" (and divide that by inputStats.RowCount at the end) instead of calculating the selectivity directly. In that case, the term I mentioned above would just be colstat.NullCount.

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3033 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LqveT7a1JbKJOnkrQN9:-LrHu4NO4fiBrLcZLHeF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L3033)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we should come up with a helper function given that we're using this non-trivial formula in multiple places.
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
Nice work! :lgtm: except that I think the refactoring broke something (some test outputs changed, and some look strange).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-:-LrJBi9EBbgFHBevyHLE:bkm58nu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3069 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJFahM8_ideQHD4y7B:-LrJFahM8_ideQHD4y7C:b-krwjnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L3069)):*
> ```Go
> 
> 	// Avoid setting selectivity to 0.
> 	selectivity = max(selectivity, epsilon)
> ```

Do we want to keep this check, given that we're multiplying multiple selectivities?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJB6Af8ydnWpwaSkjN:-LrJB6Af8ydnWpwaSkjO:bx0xnwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38c3108e84e41bfbeb59b8ad7228b95362ea972/pkg/sql/opt/memo/statistics_builder.go#L2410)):*
> ```Go
> // fraction returns a/b if a is less than b. Otherwise returns 1.
> func fraction(a, b float64) float64 {
> 	if a < b && b != 0 {
> ```

[nit] `b != 0` only makes a difference if a is negative, which I assume is not allowed
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJFHeEEl1izVyBlEwR:-LrJFHeF-KIa0I-WByEi:bakwwfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38c3108e84e41bfbeb59b8ad7228b95362ea972/pkg/sql/opt/memo/statistics_builder.go#L3032)):*
> ```Go
> 	// Avoid setting row count to 0. The stats may be stale, and we
> 	// can end up with weird and inefficient plans if we estimate 0 rows.
> 	return max(rowCount, epsilon)
> ```

We were capping the selectivity to `epsilon`, now we are capping the `rowCount` which then gets divided by `inputStats.RowCount` which itself could be very small..  I think it's fine to make this function return the selectivity (the internal formula can still use `rowCount`).

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41520)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3069 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJFahM8_ideQHD4y7B:-LrK8bVi24e4TeMqyweg:bocfb8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5defc28b087238e544853083b2d4c75b30bbd15a/pkg/sql/opt/memo/statistics_builder.go#L3069)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we want to keep this check, given that we're multiplying multiple selectivities?
</blockquote></details>

There are lots of other places where we multiply selectivities together without that check. I think it's fine since `float64` can represent much smaller values than `epsilon` (1e-10). 
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJB6Af8ydnWpwaSkjN:-LrK6vIG3qCQ9s_3IgYj:bw4x0na) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38c3108e84e41bfbeb59b8ad7228b95362ea972/pkg/sql/opt/memo/statistics_builder.go#L2410)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `b != 0` only makes a difference if a is negative, which I assume is not allowed
</blockquote></details>

Yea... that's true. If `a` is negative I suppose we have bigger problems.... Fixed.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3032 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrJFHeEEl1izVyBlEwR:-LrK9bB41DlDpjJedlDD:b1p1nd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38c3108e84e41bfbeb59b8ad7228b95362ea972/pkg/sql/opt/memo/statistics_builder.go#L3032)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We were capping the selectivity to `epsilon`, now we are capping the `rowCount` which then gets divided by `inputStats.RowCount` which itself could be very small..  I think it's fine to make this function return the selectivity (the internal formula can still use `rowCount`).
</blockquote></details>

Good point! Fixed.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-:-LrKLfmbCozilcfczwdq:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @RaduBerinde)

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 824 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrKbA_OC4hrmEVxIApR:-LrKbA_OC4hrmEVxIApS:b52j451) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8cc55839a7568eba833a2122d72bedcd9d587f/pkg/sql/opt/memo/testdata/stats/scan#L824)):*
> ```
> index-join hist
>  ├── columns: a:1(int) b:2(date) c:3(decimal) d:4(float) e:5(timestamp) f:6(timestamptz!null) g:7(string)
>  ├── stats: [rows=1e-07, distinct(6)=1e-07, null(6)=0]
> ```

Out of curiosity, why did this change from 1 to 1e-07? (I can't tell what nulls have to do with this case)

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 824 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrKbA_OC4hrmEVxIApR:-LrKePjfBhPItksPlKCD:bapi75c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8cc55839a7568eba833a2122d72bedcd9d587f/pkg/sql/opt/memo/testdata/stats/scan#L824)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Out of curiosity, why did this change from 1 to 1e-07? (I can't tell what nulls have to do with this case)
</blockquote></details>

This new value is actually more correct since `'2019-10-30 23:00:00'` is outside of the range of data in the histogram. Previously, the code in `selectivityFromHistograms` was setting `newCount` to 1 if it was 0, in order to avoid calculating 0 rows. Now that `predicateSelectivity` takes care of avoiding 0 rows, we don't need that check anymore.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 824 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41520#-LrKbA_OC4hrmEVxIApR:-LrKgmDt-ZRvkKbNurN4:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8cc55839a7568eba833a2122d72bedcd9d587f/pkg/sql/opt/memo/testdata/stats/scan#L824)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This new value is actually more correct since `'2019-10-30 23:00:00'` is outside of the range of data in the histogram. Previously, the code in `selectivityFromHistograms` was setting `newCount` to 1 if it was 0, in order to avoid calculating 0 rows. Now that `predicateSelectivity` takes care of avoiding 0 rows, we don't need that check anymore. 
</blockquote></details>

Nice, thanks!

**Pull request merged**
