### PR TITLE
storage: advertise per-locality hosts

### LINKED ISSUE #25636: rpc: Advertise per-locality hosts
In some deployment patterns (including [this multi-cloud example](https://www.cockroachlabs.com/blog/multi-cloud-deployment/), nodes have multiple network interfaces. This typically involves a "local" or "private" interface that is only accessible by a subset of the nodes, and a "global" or "public" interface that is slower or more expensive but accessible by any node. We want to route traffic over the local interface whenever possible.

The "right" answer here is to use DNS, with resolvers in each datacenter returning the best IP address that is reachable from that location. However, getting this set up correctly is non-trivial and has additional moving pieces that must be maintained. A solution integrated into cockroach may be significantly easier to deploy.

Strawman proposal: Add a new flag `--advertise-alternate-host` which takes a list of locality/hostname pairs. This mapping would go into the gossiped node status, and each node would look through the list for a value that matched its locality and use that address to connect.

Example:

    cockroach start --certs-dir=... --locality=region=west --advertise-host=$PUBLIC_IP --alternate-advertise-host=region=west:$PRIVATE_IP

### PR DESCRIPTION
**Pull request by m-schneider**
After this patch we'll allow users to specify an advertise host per
locality. This is useful for nodes with a public and private network
interface. The public interface is slower, so this patch will give users
the ability to specify the private interface for nodes that can use it.

closes #25636

Release note: None

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
Looks good, just a few small tweaks. 

This PR also closes #28165.

I had an idea for a simple way to test this in a roachtest: Start all the nodes with `--advertise-addr` pointing to some bogus address, and then use a `--locality-advertise-addr` to give the real address. 

> Reviewed 22 of 22 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-:-LJowRRNBL4kse4kIfOl:b-dg81ts)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags_util.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoq-724oumKEAXen5z:-LJoq-724oumKEAXen6-:b-royll3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b688dd0fc33ecfaed47d8edb74fd2b2de6133f4/pkg/cli/flags_util.go#L58)):*
> ```Go
> 
> 	for _, value := range values {
> 		split := strings.Split(value, ":")
> ```

Colon isn't a great delimiter here because we might need to support port numbers and/or ipv6 literals. How about `@`: 

    --locality-advertise-addr=region=us-east@123.45.67.89,region=us-west@[12::34:56]:26257
___
*[pkg/cli/cliflags/flags.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoqpDc2KwGIMSSg80m:-LJoqpDc2KwGIMSSg80n:btejyxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b688dd0fc33ecfaed47d8edb74fd2b2de6133f4/pkg/cli/cliflags/flags.go#L390)):*
> ```Go
> 
> 	LocalityAdvertiseAddress = FlagInfo{
> 		Name: "locality-advertise-address",
> ```

We abbreviate address as `addr` in other flags. 
___
*[pkg/cli/cliflags/flags.go, line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJorjts6maX3GW_jwEo:-LJorjts6maX3GW_jwEp:b-uqwig9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4de61db984cc41d1b1a2fac182316a3a74706e/pkg/cli/cliflags/flags.go#L396)):*
> ```Go
> separated list of locality:address. For example:
> <PRE>
> "zone=1:127.0.0.1,zone=2:127.0.0.1"
> ```

Let's use the same localities from the example for `--locality`, i.e. `region=us-west`. 
___
*[pkg/gossip/gossip_test.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoz88B0QUAlgkSFEGy:-LJoz88B0QUAlgkSFEGz:bt5tmof) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4de61db984cc41d1b1a2fac182316a3a74706e/pkg/gossip/gossip_test.go#L212)):*
> ```Go
> 	defer stopper.Stop(context.TODO())
> 
> 	gopssipLocalityAdvetiseList := roachpb.Locality{}
> ```

s/gopssip/gossip/, s/Advetise/Advertise/

**Review by m-schneider — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28531)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/flags_util.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoq-724oumKEAXen5z:-LJp9U7RDYBICzBZS5c-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b688dd0fc33ecfaed47d8edb74fd2b2de6133f4/pkg/cli/flags_util.go#L58)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Colon isn't a great delimiter here because we might need to support port numbers and/or ipv6 literals. How about `@`: 

    --locality-advertise-addr=region=us-east@123.45.67.89,region=us-west@[12::34:56]:26257
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoqpDc2KwGIMSSg80m:-LJp9ZX0C8syGCarZTLl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b688dd0fc33ecfaed47d8edb74fd2b2de6133f4/pkg/cli/cliflags/flags.go#L390)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We abbreviate address as `addr` in other flags. 
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 396 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJorjts6maX3GW_jwEo:-LJp9ZoZBi1zCAcbytOq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4de61db984cc41d1b1a2fac182316a3a74706e/pkg/cli/cliflags/flags.go#L396)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Let's use the same localities from the example for `--locality`, i.e. `region=us-west`. 
</blockquote></details>

Done.
___
*[pkg/gossip/gossip_test.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28531#-LJoz88B0QUAlgkSFEGy:-LJp9apv7GqP69cxynEJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f4de61db984cc41d1b1a2fac182316a3a74706e/pkg/gossip/gossip_test.go#L212)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/gopssip/gossip/, s/Advetise/Advertise/
</blockquote></details>

Done.

**Review by bdarnell — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28531)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jseldess** [comment]
@m-schneider, why is there no release note text for this change? Without such a text, Docs will very likely miss this. 

In the future, please use `Release note: None` only if you are confident that users do NOT need to know about the change, and that there are no docs that need to be written or updated.

**Pull request merged**
