### PR TITLE
util/log: fix and re-enable TestFatalStacktraceStderr

### LINKED ISSUE #4457: circleci: failed tests (12945):
The following test appears to have failed:

[#12945](https://circleci.com/gh/cockroachdb/cockroach/12945):

```
=== RUN   TestRollover
--- PASS: TestRollover (1.00s)
=== RUN   TestLogBacktraceAt
--- PASS: TestLogBacktraceAt (0.00s)
=== RUN   TestFatalStacktraceStderr
F0217 21:27:45.644671 871 util/log/clog_test.go:519  cinap
goroutine 35 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xece56dc01, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:880 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0xbf39c0, 0x3, 0xbd2a8b, 0x15, 0x207, 0x0, 0xc820262420)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:737 +0x12f
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x96b5e0, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:38 +0x114
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x96b5e0, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:64 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x96b5e0, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:170 +0x66
--
testing.tRunner(0xc8202ac090, 0xbefc68)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xa4bdb0, 0xbefb00, 0x14, 0x14, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820089ee8, 0xa4b7e8)
	/usr/local/go/src/testing/testing.go:494 +0x70
github.com/cockroachdb/cockroach/util/log.TestMain(0xc820089ee8)
	/go/src/github.com/cockroachdb/cockroach/util/log/main_test.go:36 +0x19e
main.main()
	github.com/cockroachdb/cockroach/util/log/_test/_testmain.go:92 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0xbf39c0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1032 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:613 +0xbc
--- PASS: TestFatalStacktraceStderr (0.00s)
=== RUN   TestLogFilenameParsing
--- PASS: TestLogFilenameParsing (0.00s)
=== RUN   TestSelectFiles
--- PASS: TestSelectFiles (0.00s)
=== RUN   TestLogNilArg

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #4457.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4467)

### CODE REVIEW

**Comment by petermattis** [comment]
Ping. Easy fix. Easy review.

**Comment by tamird** [comment]
I don't have a clue what this is doing. Can you expand on the commit message?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4467#-:-KAp37yazuTMXLMLYe61:1753949649)*

**Comment by petermattis** [comment]
@tamird Commit message enhanced.

**Comment by tamird** [comment]
LGTM

**Pull request merged**
