### PR TITLE
workload/schemachange: fix deadlock between watch dogs and workers

### LINKED ISSUE #121542: roachtest: schemachange/mixed-versions failed [workload hung; but no activity is occurring]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14660501?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14660501?buildTab=artifacts#/schemachange/mixed-versions) on master @ [c43f54cdde5b7578f4a0ca61de41463f0d690993](https://github.com/cockroachdb/cockroach/commits/c43f54cdde5b7578f4a0ca61de41463f0d690993):

```
(test_runner.go:1185).runTest: test timed out (3h0m0s)
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14660501/schemachange-mixed-versions/1712037777135/1712048726943)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121411 roachtest: schemachange/mixed-versions failed [C-test-failure GA-blocker O-roachtest O-robot P-1 T-sql-foundations branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37322

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the schema change workload would hang with the worker threads waiting for the watch dog connections to terminate. Unfortunately, this would happen because when running workloads with multiple URLs there would be an upper limit on total connections, which could mean that some connection pools could be depleted if both the workers and watch dogs were on them. Because the watch dogs monitor loops needs connection for a single iteration, and the worker needs the watch dog to terminate before closing its connection. This would lead to dead lock, since the watch dog would never break out of its monitor loop. To address this, this patch will create a connection pool for the watch dog connections.

Fixes: #121542

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice find! it's pretty surprising that pgx does not have an AcquireTimeout on its connection pool.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121552#-:-NuUWdIzADcbKy0TkYkL:b-acltde)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @srosenberg)

___
*[`pkg/workload/schemachange/schemachange.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121552#-NuUd71o-WmWhiDT4o41:-NuUd71o-WmWhiDT4o42:bhplgx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd74e9db6394cab29130bbc46a5cc56167b6a963/pkg/workload/schemachange/schemachange.go#L233)):*
> ```Go
> 	// a connection for a monitoring cycle before it can check for its termination
> 	// channel.
> 	cfg.MaxTotalConnections = len(urls) * cfg.MaxConnsPerPool
> ```

this feels a bit harder to reason about. and i'm worried that something else unexpected could still happen as long as the watchdogs share pools with the workers.

what if instead, we just made a second `pool` inside of the `schemaChangeWorker`: https://github.com/cockroachdb/cockroach/blob/6cd935edb029c4f87d3e0e2c84da4874b32778c5/pkg/workload/schemachange/schemachange.go#L399

we could call it `watchdogPool`

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121552)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/workload/schemachange/schemachange.go` line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121552#-NuUd71o-WmWhiDT4o41:-NuVEUY_4gPE1zJFxBAs:b-9f02sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd74e9db6394cab29130bbc46a5cc56167b6a963/pkg/workload/schemachange/schemachange.go#L233)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this feels a bit harder to reason about. and i'm worried that something else unexpected could still happen as long as the watchdogs share pools with the workers.

what if instead, we just made a second `pool` inside of the `schemaChangeWorker`: https://github.com/cockroachdb/cockroach/blob/6cd935edb029c4f87d3e0e2c84da4874b32778c5/pkg/workload/schemachange/schemachange.go#L399

we could call it `watchdogPool`
</blockquote></details>

Done.

Good point, that should be much cleaner

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121552#-:-NuVGh1uDzT016UYQESP:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by fqazi** [comment]
bors r+

Ran into CI infrastructure issue, retrying one more time

**Comment by annrpom** [comment]
blathers backport 23.2

**Pull request merged**
