### PR TITLE
Add more JDBC scenarios in the acceptance tests.

### LINKED ISSUE #4556: sql: Missing JDBC tests
Issues #4550 and #4538 highlight there is insufficient testing via JDBC. This needs to be addressed.

### PR DESCRIPTION
**Pull request by knz**
This patch ensures that executeUpdate indeed has no result set for
CREATE, INSERT and DROP.

Also SELECT is tested to use unqualified table names when
the URL has specified the database already.

Fixes #4556.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4557)

### CODE REVIEW

**Comment by knz** [comment]
Needed for #4550 and #4548.

**Comment by tamird** [comment]
Can you explain what "we need to ..." in the commit message means? are you saying that this change implements that, or that it is still a future TODO item? If it's the latter, could you add the TODO in the relevant place in the code? That'll make review of the future change (#4548, I assume) easier.

---

Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[acceptance/java_test.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9AXRnvR6RvD30hhPd:-KB9AXRnvR6RvD30hhPe:56276997) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L27)):*
s/ :=/Conn :=/

---

*[acceptance/java_test.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9AzQwWhDN9DP62SPQ:-KB9AzQwWhDN9DP62SPR:-254152212) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L36)):*
incomplete name?

applies below as well.

---

*[acceptance/java_test.go, line 49 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB99l4on18rkgMgbkzo:-KB99l4on18rkgMgbkzp:1125978029) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L49)):*
i think i'd move this to the line above. even if you were going to omit ssl, you'd want the trailing slash

---

*[acceptance/java_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB99aBHi0kyS2AZcfVL:-KB99aBL5Pin76NynQlJ:-590529395) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L54)):*
this indentation is all over the place

---

*[acceptance/java_test.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9A1f_uTW4tSb-2qxe:-KB9A1f_uTW4tSb-2qxf:-1271552893) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L64)):*
can you include more information here? at least, include the actual result count.

looks like this applies throughout.

---

*[acceptance/java_test.go, line 75 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9ALakwOaFIP2dj0IM:-KB9ALakwOaFIP2dj0IN:-1920258358) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L75)):*
perhaps extract `42`, if it's not too inconvenient.

---

*[acceptance/java_test.go, line 80 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9AFcLwXj0qzwZh5qX:-KB9AFcLwXj0qzwZh5qY:1237085134) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L80)):*
weird space

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-:-KB8xhwr-l847aQnXcwV:1682824675)*

**Comment by knz** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[acceptance/java_test.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9AXRnvR6RvD30hhPd:-KB9HGib-ttD4zeZQwr3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L27)):*
Done.

---

*[acceptance/java_test.go, line 36 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9AzQwWhDN9DP62SPQ:-KB9HJCZLGaO1CZvUBqD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L36)):*
Done.

---

*[acceptance/java_test.go, line 49 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB99l4on18rkgMgbkzo:-KB9HKDOrV4loU93y-PA:-1705153254) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L49)):*
I beg to disagree. It is common practice when a db name is specified to not have a trailing slash in the connection URL. At least this is how I learned to do it.

---

*[acceptance/java_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB99aBHi0kyS2AZcfVL:-KB9HQwFlE8F9p8y7dMX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L54)):*
Done.

---

*[acceptance/java_test.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9A1f_uTW4tSb-2qxe:-KB9HSAUYLtP57pSGxUT:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L64)):*
Done.

---

*[acceptance/java_test.go, line 75 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9ALakwOaFIP2dj0IM:-KB9HTmf6Nw-eZpQTP4Z:-1560630273) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L75)):*
I do not understand this. There's a select underneath.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-:-KB9HHnKpG8EXYA4bdmP:-499146009)*

**Comment by tamird** [comment]
Where?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[acceptance/java_test.go, line 49 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB99l4on18rkgMgbkzo:-KB9LT0ioi8_zFOEkc3q:160383661) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L49)):*
OK.

---

*[acceptance/java_test.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9A1f_uTW4tSb-2qxe:-KB9LmL3zfJpV-OIdEKn:1614833381) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L64)):*
Looks like you got the others but missed this one.

---

*[acceptance/java_test.go, line 75 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9ALakwOaFIP2dj0IM:-KB9M-7bcbPXgkpdF7ad:-31488474) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L75)):*
sorry, i meant extract it into a variable, so that it's not duplicated, but it's fine as-is.

---

*[acceptance/java_test.go, line 30 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9LGDJ7J1TbmlHcMjh:-KB9LGDJ7J1TbmlHcMji:-2104240902) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ccd12287490d417a4d55b65ec39c453393c505/acceptance/java_test.go#L30)):*
can you rename these `test#` to something more descriptive? perhaps a camel-cased version of the name string you pass below. `createDB`, `setupSchema`, and `runQuery`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-:-KB9MQnde_wRbwxUG0aP:-2051389027)*

**Comment by knz** [comment]
You asked to clarify the commit message, so I did. There's no "we need to..." any more.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/java_test.go, line 64 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9A1f_uTW4tSb-2qxe:-KB9NZE_O57kNGvsqY7q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aadc64e3d559df4bea4940b0c560f70b50f6362/acceptance/java_test.go#L64)):*
Done.

---

*[acceptance/java_test.go, line 30 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-KB9LGDJ7J1TbmlHcMjh:-KB9NKYyFMgxMxuVB5NF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ccd12287490d417a4d55b65ec39c453393c505/acceptance/java_test.go#L30)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-:-KB9My_UtbLX2PLCS5Fo:334385515)*

**Comment by tamird** [comment]
Oh, reviewable didn't show me that. Looks good.

LGTM.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4557#-:-KB9NyNsZis0ua8EBSJo:-1706239109)*

**Comment by knz** [comment]
Note that the two tests currently fail in CircleCI, but that's intended. They will be fixed by #4548 and the solution to #4550.

**Comment by tamird** [comment]
Ah. I would include the fix in the same PR as the test, then.

**Comment by mjibson** [comment]
I concur about having the fix and test in the same PR.

**Comment by knz** [comment]
I am not sure that the effort required to split this commit in 3 separate commits in 3 different branches is going to be worth the benefit of having the test commited with the fix atomically. I suggest committing the fix PRs and then this test PR afterwards.

**Comment by knz** [comment]
Superseded by #4578.

**Pull request closed without merging**
