### PR TITLE
storage/engine: improve MVCCComparer's Separator and Successor functions

### PR DESCRIPTION
**Pull request by sumeerbhola**
to make smaller sstable indices.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I haven't added a test, and TestPebbleWritesSameSSTs need fixing, but wanted a quick confirmation that this is sound before doing those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-LuDUVagB_tosQ6tizG7:b-xep8a9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by petermattis — COMMENTED** [review]
Looks sane to me.

`TestPebbleWritesSameSSTs` is complaining because it is testing that our Pebble and RocksDB sstable writing produces the same output and changing successor and separator on Pebble but not on RocksDB violates that. I think that means we should change the C++ versions of these routines in tandem.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-LuDdlWN-KvIBrM4Zw57:brck1ie)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDekYx9FMBg7qJRdzV:-LuDekYy60zTpF36lYqd:bbc3624) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L59)):*
> ```Go
> 		aKey, _, ok := enginepb.SplitMVCCKey(a)
> 		if !ok {
> 			return append(dst, a...)
> ```

I believe it is kosher to return `a` here.  I'm not sure why we're making a copy. We should clarify the semantics.
___
*[pkg/storage/engine/pebble.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDeGOK0CyRDau56ezm:-LuDeGOK0CyRDau56ezn:b6ukejh) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L69)):*
> ```Go
> 			return append(dst, a...)
> 		}
> 		n := len(dst)
> ```

I think `len(dst)` should always be `0`. It looks like we currently always pass `nil` for `dst`. I'm not sure if that is worth fixing.

**Review by sumeerbhola — COMMENTED** [review]
I've added the corresponding c++ change (there are a number of printf's which I will remove). The `TestPebbleWritesSameSSTs` was still failing because `RocksDB` code path was never calling `FindShortSuccessor()`. The default for `IndexShorteningMode` is `kShortenSeparators` and not `kShortenSeparatorsAndSuccessor`. Shortening is not configurable in Pebble and I am not keen to add an option. So I changed the setting in `libroach/db.cc` for the sst writer to make the test pass. 
I am assuming we are not setting `kShortenSeparatorsAndSuccessor` for RocksDB since a grep did not find any other mention in our code. Should we change that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-LuEb8N99jJAAs46D0aB:b61rbk8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDekYx9FMBg7qJRdzV:-LuEaZKMDNo9Lv2_6xhs:b-vq6uma) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe it is kosher to return `a` here.  I'm not sure why we're making a copy. We should clarify the semantics.
</blockquote></details>

this `dst` parameter is confusing things here and in `Successor`. I think in both cases all callers set it to `nil`. How about I remove that parameter and then we are free to return `a` or a constructed slice.

**Review by petermattis — COMMENTED** [review]
> Shortening is not configurable in Pebble and I am not keen to add an option. 

I agree with this. I'm not clear on why this is configurable in RocksDB.

> I am assuming we are not setting kShortenSeparatorsAndSuccessor for RocksDB since a grep did not find any other mention in our code. Should we change that?

I can't think of any reason not to change it. Older versions of RocksDB will still be able to read this data, right? 

Should there be more targeted testing that the Go and C++ versions of these methods are the same? I'm thinking of something along the lines of Pebble's `TestDefAppendSeparator`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-LuF1H2K3Wzf-6pnts1o:by6xw0x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[c-deps/libroach/comparator.cc, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF1jhp2b8NgX6bStZB:-LuF1jhp2b8NgX6bStZC:busu1z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L73)):*
> ```cpp
>   if ((*a)[prefix] + 1 < b[prefix]) {
>     // They do not have consecutive characters at prefix.
>     const_cast<char*>(a->data())[prefix]++;
> ```

Eww, but I see why this is necessary. 
___
*[c-deps/libroach/comparator.cc, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF2DmxD-TfcKXdtz9j:-LuF2DmxD-TfcKXdtz9k:b-hy2x0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L106)):*
> ```cpp
>   (*start)[key_s.size()] = 0x00;
>   std::printf("Separator: sep: %s\n", rocksdb::Slice(*start).ToString(true).c_str());
>   return;
> ```

Nit: the explicit return isn't necessary.
___
*[c-deps/libroach/comparator.cc, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF2628BIkxPtVEbrwv:-LuF2628BIkxPtVEbrww:bhlgg16) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L116)):*
> ```cpp
>   }
>   int i;
>   for (i = 0; i < k.size(); ++i) {
> ```

Nit: move the declaration of `i` into the for-loop: `for (int i = 0 ...)`.
___
*[pkg/storage/engine/pebble.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDekYx9FMBg7qJRdzV:-LuF2Ra2-3M33PiMrHzI:b-rryklc) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L59)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this `dst` parameter is confusing things here and in `Successor`. I think in both cases all callers set it to `nil`. How about I remove that parameter and then we are free to return `a` or a constructed slice.
</blockquote></details>

The intention of the `dst` parameter was to provide a buffer that could be reused to avoid allocations.

**Review by sumeerbhola — COMMENTED** [review]
I don't know about older versions of RocksDB  -- maybe @ajkr can clarify.

I'll add tests and then ping this review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-LuIdFVE9uz-_bksUiAf:bfbsphg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[c-deps/libroach/comparator.cc, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF1jhp2b8NgX6bStZB:-LuIcOwbE9ksIhbtTAwI:b-8t14fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L73)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Eww, but I see why this is necessary. 
</blockquote></details>

I fixed this by passing the backing `std::string` as a parameter too.
___
*[c-deps/libroach/comparator.cc, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF2DmxD-TfcKXdtz9j:-LuIcMtc57M2-sSIH-zo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L106)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: the explicit return isn't necessary.
</blockquote></details>

Done
___
*[c-deps/libroach/comparator.cc, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuF2628BIkxPtVEbrwv:-LuIcNp08Y6WvAY_nl_2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0dd92e78151d24a6f0d3b442ba9e39e6a04acb1/c-deps/libroach/comparator.cc#L116)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: move the declaration of `i` into the for-loop: `for (int i = 0 ...)`.
</blockquote></details>

Done
___
*[pkg/storage/engine/pebble.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDekYx9FMBg7qJRdzV:-LuIPdzMAdfd8Vq49A5m:b-ioitjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The intention of the `dst` parameter was to provide a buffer that could be reused to avoid allocations. 
</blockquote></details>

I figured that was the intention, but I don't see it being used. I'll leave it alone in case we want to start using it in the future.
___
*[pkg/storage/engine/pebble.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-LuDeGOK0CyRDau56ezm:-LuIc_X4CiQm1aHqvlb2:bip06ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e3ace35de2706ace260d0236cafeaa606df241/pkg/storage/engine/pebble.go#L69)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think `len(dst)` should always be `0`. It looks like we currently always pass `nil` for `dst`. I'm not sure if that is worth fixing. 
</blockquote></details>

Left this unchanged since the contract does not state that `dst` needs to be empty or nil -- we can simplify later.

**Review by sumeerbhola — COMMENTED** [review]
I've added tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-Lubwp2Z-MgyqQ5HUkPS:bzh78jf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

**Review by petermattis — COMMENTED** [review]
:lgtm: modulo small concerns about the C++ test.

I didn't actually verify that the C++ and Go tests have the same test cases. I'm assuming they do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-Luc0sqM55NVymSMsRzG:bg9d1z7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[c-deps/libroach/comparator_test.cc, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc-n0LCX7sY7qmf5e9:-Luc-n0LCX7sY7qmf5eA:b-fu0t30) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L22)):*
> ```cpp
> 
> namespace {
> struct SeparatorTestCase {
> ```

Nit: add a blank line after the `namespace` line.
___
*[c-deps/libroach/comparator_test.cc, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc-X_pCYwKogwg2qaB:-Luc-X_q6HF8nS4LuzcV:b-u5613q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L33)):*
> ```cpp
> };
> 
>   DBKey makeKey(std::string s, int64_t wall_time = 0, int32_t logical = 0) {
> ```

Nit: this line appears to be misindented.
___
*[c-deps/libroach/comparator_test.cc, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc0D_tAKs5ztw_NhzW:-Luc0D_tAKs5ztw_NhzX:b-esd02l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L34)):*
> ```cpp
> 
>   DBKey makeKey(std::string s, int64_t wall_time = 0, int32_t logical = 0) {
>   return {DBSlice{const_cast<char*>(s.data()), static_cast<int>(s.size())}, wall_time, logical};
> ```

I think this is problematic. The lifetime of `s` ends when this function returns which will cause `s.data()` to be released. I think you're always passing in a const string to `makeKey`. If that is the case, I think you can replace the `std::string s` parameter with a `const rocksdb::Slice &s`.
___
*[c-deps/libroach/comparator_test.cc, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc0m-12L0CIJV1OdH2:-Luc0m-12L0CIJV1OdH3:b-awg06l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L45)):*
> ```cpp
> 
>     // Non-empty b values.
>     {makeKey(std::string("black")), makeKey(std::string("blue")), makeKey(std::string("blb"))},
> ```

Nit: the explicit `std::string` casts should be unnecessary. Or I'm forgetting my C++.

**Review by sumeerbhola — COMMENTED** [review]
Yes they are the same test cases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-:-Luckp_yCFk0quZ9Pa6Y:b4irras)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[c-deps/libroach/comparator_test.cc, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc-n0LCX7sY7qmf5e9:-LuchAlQ-rSim8a8s2O7:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L22)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: add a blank line after the `namespace` line.
</blockquote></details>

Done
___
*[c-deps/libroach/comparator_test.cc, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc-X_pCYwKogwg2qaB:-LuchE97CWCzKpJERRIM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L33)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: this line appears to be misindented.
</blockquote></details>

Done
___
*[c-deps/libroach/comparator_test.cc, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc0D_tAKs5ztw_NhzW:-LuckGAx4IB1_WOY_MSP:b-i3eabh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this is problematic. The lifetime of `s` ends when this function returns which will cause `s.data()` to be released. I think you're always passing in a const string to `makeKey`. If that is the case, I think you can replace the `std::string s` parameter with a `const rocksdb::Slice &s`.
</blockquote></details>

This was an oversight when I changed the code --  I started with a `std::string&` parameter. I've changed to `const char*` -- strings in c/c++ are always annoying (the unsigned char casting in the non test code is another example of that). 
___
*[c-deps/libroach/comparator_test.cc, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Luc0m-12L0CIJV1OdH2:-LuckkdEDVjn72X08BB7:bocj9hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9db84683ad53eb5ee920f76d81d330b4c9d8c0d9/c-deps/libroach/comparator_test.cc#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: the explicit `std::string` casts should be unnecessary. Or I'm forgetting my C++.
</blockquote></details>

these are now gone.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/sst_writer_test.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Lucn4-T9XTnk0HVN_Li:-Lucn4-T9XTnk0HVN_Lj:b-1bw3ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd3f27072cf4716fc0a989b5a98d34f2cb67ddf/pkg/storage/engine/sst_writer_test.go#L107)):*
> ```Go
> 
> 	kvs := makeIntTableKVs(numKeys, valueSize, revisions)
> 	fmt.Printf("rocks\n")
> ```

Remove before merging?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42646)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/sst_writer_test.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42646#-Lucn4-T9XTnk0HVN_Li:-Lv5obt58ogFtiXD9f5H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd3f27072cf4716fc0a989b5a98d34f2cb67ddf/pkg/storage/engine/sst_writer_test.go#L107)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Remove before merging?
</blockquote></details>

Done.

**Pull request merged**
