### PR TITLE
config,sql,sqlccl: remove index's zone configs when index is dropped

### LINKED ISSUE #20881: sql: clean up zone configs when index/partitions change
When dropping an index or removing a partition, the associated zone config should be removed.

### PR DESCRIPTION
**Pull request by benesch**
When dropping an index, ensure that any zone configs set on that index
or partitions of that index are removed.
    
Fixes #20881.
    
Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/drop_test.go, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OVsbzjK_5phaYp-RE:-L1OVsbzjK_5phaYp-RF:b3yfn7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/ccl/sqlccl/drop_test.go#L33)):*
> ```Go
> 	params, _ := tests.CreateTestServerParams()
> 	params.Knobs = base.TestingKnobs{
> 		SQLSchemaChanger: &sql.SchemaChangerTestingKnobs{BackfillChunkSize: chunkSize},
> ```

why do we need all the chunksize stuff? it's not immediately obvious to me why, so worth a comment if it sticks around

---

*[pkg/sql/backfill.go, line 235 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OXOHzbx4geDgCd334:-L1OXOHzbx4geDgCd335:bpd9g5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/sql/backfill.go#L235)):*
> ```Go
> 		}
> 
> 		_, err = writeZoneConfig(ctx, txn, sc.settings, sc.leaseMgr, sc.tableID, tableDesc, zone)
> ```

should this special case when zone is unchanged to avoid the write?

---

*[pkg/sql/drop_test.go, line 421 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OX1AtdsiWJAx_bgKN:-L1OX1AtdsiWJAx_bgKO:b5m8ka5) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/sql/drop_test.go#L421)):*
> ```Go
> 	tests.CheckKeyCount(t, kvDB, indexSpan, numRows)
> 
> 	// Hack in zone configs for the primary and secondary indexes. (You need a CCL
> ```

love it!

---

*[pkg/sql/zone_config.go, line 161 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OXaiNmX_9__WjBEzc:-L1OXaiNmX_9__WjBEzd:b-7y5i52) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c0e758bd97d14f8b450ed2fac3d319af3a58b95/pkg/sql/zone_config.go#L161)):*
> ```Go
> 	*sqlbase.TableDescriptor, []config.Subzone,
> ) ([]config.SubzoneSpan, error) {
> 	return nil, sqlbase.NewCCLRequiredError(errors.New(
> ```

there's more of these in backup/restore/export/import/addsstable, should we change them all?

---

*[pkg/testutils/sqlutils/zone.go, line 104 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OWTWDZNugrur9uhkK:-L1OWTWEUNw7tVn6wEvS:bpsx0jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/testutils/sqlutils/zone.go#L104)):*
> ```Go
> }
> 
> // ZoneConfigExists returns whether a zone config with the provfided
> ```

nit: provided

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038)*

**Comment by benesch** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/drop_test.go, line 33 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OVsbzjK_5phaYp-RE:-L1s1r2DWyIB_wGSf4BK:banfxm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/ccl/sqlccl/drop_test.go#L33)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

why do we need all the chunksize stuff? it's not immediately obvious to me why, so worth a comment if it sticks around
</blockquote></details>

Copy/pasta from the other `DROP INDEX` tests. Not important to test here, so removed!

---

*[pkg/sql/backfill.go, line 235 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OXOHzbx4geDgCd334:-L1s3htuVjMiEUfClNul:b1038g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/sql/backfill.go#L235)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should this special case when zone is unchanged to avoid the write?
</blockquote></details>

It doesn't seem worth the extra complexity given how infrequently schema changes run and the number of other writes they perform?

---

*[pkg/sql/zone_config.go, line 161 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OXaiNmX_9__WjBEzc:-L1s28qhxe7h3Eg4KhfL:bym39ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c0e758bd97d14f8b450ed2fac3d319af3a58b95/pkg/sql/zone_config.go#L161)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

there's more of these in backup/restore/export/import/addsstable, should we change them all?
</blockquote></details>

It's more or less impossible in the other cases to determine whether an "unknown SQL statement type" or "unknown command type" error is the result of needing a CCL binary or something else going wrong. Future work, perhaps?

---

*[pkg/testutils/sqlutils/zone.go, line 104 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OWTWDZNugrur9uhkK:-L1s3qitcdwSh_wgywwS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/testutils/sqlutils/zone.go#L104)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: provided
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/backfill.go, line 235 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-L1OXOHzbx4geDgCd334:-L1sDmQIXmDPbBQISewL:b-6ojdvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ce3e8ae3c3aa302c0603bc9eeaef08ae441b31/pkg/sql/backfill.go#L235)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It doesn't seem worth the extra complexity given how infrequently schema changes run and the number of other writes they perform?
</blockquote></details>

For some reason, when I wrote this comment, I was thinking that it triggered a TableDesc upversion, which seemed like a lot of extra work to waste, even infrequently. But now I can't remember why I thought that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21038#-:-L1sEf2ZOjQN2p3HBJfs:bnfp4nl)*

**Comment by benesch** [comment]
TFTR!

**Pull request merged**
