### PR TITLE
backupccl,importccl,changefeedccl: add option to disable using protected timestamps

### LINKED ISSUE #67118: protectedts: provide mechanism to disable subsystem
**Is your feature request related to a problem? Please describe.**

There have been bugs in the implementation of protected timestamp (recent deadlock in #66760). Also, the limits can be painful and can prevent backups. The limit problems can be solved by increasing the limits but the deadlock can't. We don't know what we'll find in the future. The subsystem, while important, is about ensuring work completes in the face of GC. If we opt out of protecting data, nothing catastropic should happen: backups, changefeeds, or schema changes may fail, but that's okay.

**Describe the solution you'd like**

Add a knob to turn off protected timestamps altogether. Perhaps just for backups or changefeeds.

**Describe alternatives you've considered**

Not adding this knob?

Jira issue: CRDB-8372

### PR DESCRIPTION
**Pull request by adityamaru**
Please see individual commits.

Fixes: https://github.com/cockroachdb/cockroach/issues/67118

### CODE REVIEW

**Comment by adityamaru** [comment]
Going to try and add some tests to ensure we're not laying down protected ts with this option. Wanted to put something out for option name bike-shedding.

**Comment by adityamaru** [comment]
Added tests, should be RFAL!

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67511#-MeUae1c7IrURboRhbQL:-MeUae1c7IrURboRhbQM:b-3sws0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2359bd04c57ad5dedfeec6f7d23fcd6dc46bbd5/pkg/ccl/changefeedccl/changefeed_stmt.go#L361)):*
> ```Go
> 
> 			_, disableProtectedTimestamp := details.Opts[changefeedbase.OptDisableProtectedTimestamp]
> 			shouldProtectTimestamp := !disableProtectedTimestamp &&
> ```

I think that you might also need to add a condition here:

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeed_processors.go#L1389

where we install protected timestamps during backfills.  As a potential followup, perhaps we can set this option to `true` when we are in a tenant so that we don't have to manage both conditions and multiple callsites.

**Comment by pbardea** [comment]
Do you think it'd also be valuable to add a cluster setting feature flag around controlling this for all backups/changefeeds? I think we'd usually use this as an escape hatch when there is something up with the protectedts integration in general (e.g. the deadlock). In such a case I can see there being utility for a big cluster-setting hammer to come down and stop using the subsystem all together.

That's not to say a per-job option doesn't have its use-cases, I could see a backup that's trying to install a large protection record could benefit from an escape hatch just for itself as well.

**Comment by adityamaru** [comment]
> Do you think it'd also be valuable to add a cluster setting feature flag around controlling this for all backups/changefeeds? I think we'd usually use this as an escape hatch when there is something up with the protectedts integration in general (e.g. the deadlock). In such a case I can see there being utility for a big cluster-setting hammer to come down and stop using the subsystem all together.
> 
> That's not to say a per-job option doesn't have its use-cases, I could see a backup that's trying to install a large protection record could benefit from an escape hatch just for itself as well.

I see what you mean, do you think we should only have the cluster setting then? I'm trying to weigh the value of having two more checks against the usefulness of a per-job escape hatch. The limits error has a solution independent of disabling the entire subsystem which is to bump the limits, so do we see ourselves recommending disabling protected ts entirely instead of that?

**Comment by adityamaru** [comment]
With the ongoing discussion in https://github.com/cockroachdb/cockroach/issues/67282 I believe there is a strong argument to be made for a per job option to disable protected timestamp. The work for #67282 will likely move the protected ts responsibility from the job to the scheduler and so we can piggyback on the logic being added in this PR. After an offline discussion with @pbardea, a cluster setting is useful but should lie somewhere in the `protectedts` package so as to completely disable the subsystem. I will do this in a follow up!

This PR is RFAL, @stevendanna I've addressed your comments as well 🙂

**Review by HonoreDB — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 13 of 13 files at r4, 4 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67511)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

**Review by pbardea — APPROVED** [review]

**Pull request closed without merging**
