### PR TITLE
sql: don't use qname visitor for check constraints

### PR DESCRIPTION
**Pull request by RaduBerinde**
The check constraints verification code uses a big hammer to do a relatively
simple thing. I was looking at splitting off some code from the sql package and
the dependency on the qname visitor (part of the select code) is problematic.

Implementing a convenience visitor implementation that takes a single function;
using it to replace the qname visitor use for check constraints.

This also results in a better error message.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6486)

### CODE REVIEW

**Comment by mjibson** [comment]
I'm not thrilled about this change. It adds some qval-specific knowledge into a place that shouldn't have to know anything about how qvals work. Could we make a helper function in select_qvalue.go that does this, and just move the code here to there? I'd be ok with that.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/walk.go, line 885 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-KGuG-aQiejY_fGWofgT:-KGuG-aRWNC7w14F9TJ1:105877528) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8d18b6fe95d7ac1b70f413da19116f6b7c8fdb/sql/parser/walk.go#L885)):*
"run" is a typo of some kind. It messes up the sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-:-KGuG9AHt4QbOautGE-k:707890910)*

**Comment by RaduBerinde** [comment]
We are not using `qval`s at all anymore, which is a construct of the select code. What "qval-specific knowledge" do you mean exactly? The only think the code "knows" is that any `QualifiedName` must refer to that particular column..

I am specifically trying to make this code not depend on select code. I am moving some of the basic definitions and functionality to a `sqlbase` package. This code unfortunately has to be part of it because it is used to create the system tables. It can't depend on select stuff which won't be in the package.

Even if we disregard this practical reason, `resolveQNames` (and all stuff in `select_qvalue.go`) is meant to work on select expressions and could change as needed to accommodate new select features; it's a hack that we are using it here. In fact, this is not even correct as it is. Because of the special handling `resolveQNames` does, we currently accept expressions like `CREATE TABLE t3 (a INT, b INT CHECK (COUNT(*) = 1))` (I verified this; adding a test).

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-:-KGw4tSJ07O6sbaJ1uFH:-662381625)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-:-KGwj1ff0BAVd9fmPo6T:1417088721)*

**Comment by mjibson** [comment]
Ok, I'm fine merging this. But there are three things about qualified names that have to be known to the CHECK function: 1) the need to use NormalizeColumnName, 2) what qname.Base is, 3) what qname.Column()  is. This isn't a huge burden, but it certainly seems easier to me with the old behavior because I know that resolveQNames function does everything I need it to and I don't have to familiarize myself with details of qnames. I'm ok because this is for a refactor for a separate purpose, but would still prefer some other place this logic can live that's not in the CHECK code.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-:-KGwnx580DTWVKzvpKF_:1222323060)*

**Comment by RaduBerinde** [comment]
Thanks! I think the right thing to do would be to provide some kind of basic qname processing infrastructure that is generic enough for both `resolveQNames` and this check code to use it yet still hides the details you mentioned. I will keep that in mind.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6486#-:-KGwr0g7eY1kDQfJza-M:1418447672)*

**Comment by RaduBerinde** [comment]
Closing this one since it was against a temporary branch (those commits have now been merged). Will merge in a new PR.

**Pull request closed without merging**
