### PR TITLE
stats,distsqlrun: improve create stats job progress reporting

### LINKED ISSUE #35360: stats: improve progress estimation
This issue tracks improving the progress estimation for creating table statistics.

An idea would be for samplers to send out periodic updates with the number of rows processed so far, and configure the sample-aggregator with previous table stats so it can estimate what percentage of the rows were processed.

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, all create stats jobs only reported progress when
each node had completed all processing. This resulted in a poor quality user
experience, since long create stats jobs would appear to have made zero
progress for a long period of time. This commit adds logic to report more
accurate incremental progress by counting the number of rows processed so
far and dividing that by the total number of rows in the table (estimated
according to the latest stats). The first job for a given table reports
0 progress until completion (since there are no stats available yet), but
all subsequent jobs will now have better progress estimation.

Fixes #35360
Informs #35346

Release note (admin ui change): Improved progress reporting for CREATE
STATISTICS jobs.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlpb/processors.proto, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_rZihM3K-Xyzum1SPB:-L_rZihM3K-Xyzum1SPC:b59qohk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab4169d715911f9559d43b55480add6972a85ea/pkg/sql/distsqlpb/processors.proto#L820)):*
> ```protobuf
> 
>   // The total number of rows expected in the table based on previous runs of
>   // CREATE STATISTICS. Used for progress reporting.
> ```

[nit] mention that if it is 0, the reported progress is 0 until the very end.
___
*[pkg/sql/distsqlrun/sampler.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_r_mbY4lGGj8JJIJ2X:-L_r_mbY4lGGj8JJIJ2Y:b-9srvwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab4169d715911f9559d43b55480add6972a85ea/pkg/sql/distsqlrun/sampler.go#L197)):*
> ```Go
> 			// report number of rows processed since the last update.
> 			meta := &ProducerMetadata{
> 				Progress: &jobspb.Progress{Details: &jobspb.Progress_CreateStats{
> ```

I am not crazy about ProducerMetadata containing a `jobspb.Progress` message.  The Progress message supports a wide array of things and we're only using it for a very specific case. We are also abusing the semantics because `CreateStatsProgress.RowsProcessed` is the number of rows processed so far but here we are using it as number of rows processed since the last update.

Can we replace ProducerMetadata.Progress with a more specific `SamplerRowsProcessed`?

And if we do that, do we still need `CreateStatsProgress.RowsProcessed`? That struct is meant to be updated in `FractionProgress` to be stored in the jobs table but we aren't doing that AFAICT (and we don't need it).

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/distsqlpb/processors.proto, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_rZihM3K-Xyzum1SPB:-L_rxNX--kNMPsviR2_-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab4169d715911f9559d43b55480add6972a85ea/pkg/sql/distsqlpb/processors.proto#L820)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] mention that if it is 0, the reported progress is 0 until the very end.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sampler.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_r_mbY4lGGj8JJIJ2X:-L_rwk0q0xTqriO1Pu_7:b-miea5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ab4169d715911f9559d43b55480add6972a85ea/pkg/sql/distsqlrun/sampler.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I am not crazy about ProducerMetadata containing a `jobspb.Progress` message.  The Progress message supports a wide array of things and we're only using it for a very specific case. We are also abusing the semantics because `CreateStatsProgress.RowsProcessed` is the number of rows processed so far but here we are using it as number of rows processed since the last update.

Can we replace ProducerMetadata.Progress with a more specific `SamplerRowsProcessed`?

And if we do that, do we still need `CreateStatsProgress.RowsProcessed`? That struct is meant to be updated in `FractionProgress` to be stored in the jobs table but we aren't doing that AFAICT (and we don't need it).
</blockquote></details>

Makes sense. I created a new `ProducerMetadata` message called `SamplerProgress`. (I wanted to make it a bit more general in case we add other types of progress such as ranges processed).

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-:-L_sAqxR07onX8r0UeTl:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlpb/data.proto, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_sAnNk0f4thfLdWqbN:-L_sAnNk0f4thfLdWqbO:b1y4rhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa3899310fd514a4ce056132e02afe505fb0281/pkg/sql/distsqlpb/data.proto#L273)):*
> ```protobuf
>     roachpb.TxnCoordMeta txn_coord_meta = 4;
>     RowNum row_num = 5;
>     SamplerProgress sampler_progress = 7;
> ```

[nit] reserve 6?

**Review by RaduBerinde — COMMENTED** [review]
[nit] probably more of an "admin ui change" than "sql change"

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-:-L_sD2Zp8lNYG_mDGKmB:b-i3ymaw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @rytaft)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/distsqlpb/data.proto, line 273 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-L_sAnNk0f4thfLdWqbN:-L_sBGyeA570pgMZX2Vv:b67ilt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fa3899310fd514a4ce056132e02afe505fb0281/pkg/sql/distsqlpb/data.proto#L273)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] reserve 6?
</blockquote></details>

Done. (reserved doesn't work inside `oneof`, but it seems to have the same effect on the outside...)

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35684#-:-L_tC0P643Gd4qhNkdmX:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @RaduBerinde)

**Pull request merged**
