### PR TITLE
sql: ensure errors are unwrapped before their type is tested

### PR DESCRIPTION
**Pull request by knz**
Informs  #35854.

Pursuant to #35937, #35944 and the discussion on #35854, I am
realizing that there were folk under us working under two conflicting
set of assumptions:

- some prefer their error types unchanged, so as to be able to use
  type assertions to detect certain things (e.g. retry errors).
- some prefer to use `errors.Wrap` or `pgerror.Wrap` liberally,
  so as to decorate errors with useful information to troubleshoot
  problems when they arise.

The problem to solve is that `errors.Wrap` and alike change the type
of errors. The folk who do not like this, or simply did not know about
this, have historically written code that did not take this into
account.

I came to this realization following a comment from Andrei on
issue #35854. Then I ran the following command:

`git grep -n '[eE]rr\.(\*' pkg/{sql,ccl}|grep -v '_test.go:'`

to find all occurrences of type casts on error objects.

Then I added the missing calls to `errors.Cause()` so that the type
casts become more robust again, even in the presence of more generous
uses of `errors.Wrap` and `pgerror.Wrap`.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Before diving into the harder questions, let's do a warmup:
If we only do type checks on `err.Cause()`, then that means that our error types can't implement the `causer` interface - we can't say "this function may return `InvalidWidgetError`" and then have `InvalidWidgetError` implement `causer`. Is that cool, in your opinion?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-:-LaMQN-xCi4lF97YR5y1:buedgdv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @andy-kimball, and @RaduBerinde)

**Comment by knz** [comment]
Yes it's cool.

If your invalid widget error is both a causer and important, make a separate IsWidgetError() predicate for it that unrolls manually.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
For reference, I checked that already. None of our current important errors are causers.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
Also see #35920 for the direction I want to take. Make things important using a WithMarker() function, and check with IsErrorMarker().

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-:-LaMWpCI7LREy_MhAB4C:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @knz, and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-LaMWevDBIbbz4dGY_lN:-LaMVmuQ1Uz7i2RbUE5_:b-7gdvo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/993d7f3500f0aac41ff883a465a4073be21c1a55/pkg/sql/conn_executor_exec.go#L846)):*
> ```Go
> 		if pqErr.Code == pgerror.CodeUndefinedColumnError ||
> 			pqErr.Code == pgerror.CodeUndefinedTableError {
> 			// Be careful to not modify the error in-place (via SetHintf) as
> ```

I don't quite follow this. Can't we just make a shallow copy of `pqErr`?
___
*[pkg/sql/conn_executor_exec.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-LaMVKJe-Jen1euSrbpT:-LaMVKJe-Jen1euSrbpU:b93t43z) ([raw file](https://github.com/cockroachdb/cockroach/blob/993d7f3500f0aac41ff883a465a4073be21c1a55/pkg/sql/conn_executor_exec.go#L850)):*
> ```Go
> 			// on the fact that pgerror.Wrapf on a pgerror.Error object
> 			// always returns a fresh error object.
> 			pqErr, _ = pgerror.GetPGCause(pgerror.Wrapf(err, pqErr.Code, "falling back to heuristic planner"))
> ```

s/pqErr/pgErr ? What's "pq"?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @andy-kimball, and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-LaMWevDBIbbz4dGY_lN:-LaR8l-RBal6JOHumknc:bz5py0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/993d7f3500f0aac41ff883a465a4073be21c1a55/pkg/sql/conn_executor_exec.go#L846)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't quite follow this. Can't we just make a shallow copy of `pqErr`?
</blockquote></details>

Good idea! Done.
___
*[pkg/sql/conn_executor_exec.go, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35962#-LaMVKJe-Jen1euSrbpT:-LaR8m5kDFXBDwGhWtwB:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/993d7f3500f0aac41ff883a465a4073be21c1a55/pkg/sql/conn_executor_exec.go#L850)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/pqErr/pgErr ? What's "pq"?
</blockquote></details>

Done.

**Pull request merged**
