### PR TITLE
storeliveness: add transport metrics

### PR DESCRIPTION
**Pull request by miraradeva**
This commit adds seven new metrics for the Store Liveness Transport:

- `storeliveness.transport.send-queue-size`: Number of pending outgoing  messages in all Store Liveness Transport per-store send queues.
- `storeliveness.transport.send-queue-bytes`: Total byte size of pending  outgoing messages in all Store Liveness Transport per-store send queues.
- `storeliveness.transport.send-queue-idle`: Number of Store Liveness  Transport per-store send queues that have become idle due to no recently-sent messages.
- `storeliveness.transport.sent`: Number of Store Liveness messages sent by the Store Liveness Transport.
- `storeliveness.transport.received`: Number of Store Liveness messages received by the Store Liveness Transport.
- `storeliveness.transport.send_dropped`: Number of Store Liveness messages dropped by the Store Liveness Transport on the sender side.
- `storeliveness.transport.receive_dropped`: Number of Store Liveness messages dropped by the Store Liveness Transport on the receiver side.

Part of: https://github.com/cockroachdb/cockroach/issues/125067

Release note: None

----

Screenshot 2024-09-20 at 1 20 18 PM

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-:-O7UuHU-9qeJ0mzsQOv6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @miraradeva)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7Ut3sV2rrKiOLurjwm):*
"blocked"
___
*[`pkg/kv/kvserver/store.go` line 2194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UtKln5bad7CCJfzmQ:-O7UtKln5bad7CCJfzmR:bmry98x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/store.go#L2194)):*
> ```Go
> 	options := storeliveness.NewOptions(heartbeatInterval, livenessInterval, supportGracePeriod)
> 	sm := storeliveness.NewSupportManager(
> 		slpb.StoreIdent{NodeID: s.nodeDesc.NodeID, StoreID: s.StoreID()}, s.StateEngine(), options,
> ```

Is it surprising that this didn't cause any tests to fail? Was store liveness completely broken without this fix?
___
*[`pkg/kv/kvserver/storeliveness/metrics.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UpLe28dZMBXWYvTMK:-O7UpLe28dZMBXWYvTML:b-nfrlez) ([raw file](https://github.com/cockroachdb/cockroach/blob/df958c6de7f36d321ecc2d15761e1cc32cdb4dc4/pkg/kv/kvserver/storeliveness/metrics.go#L74)):*
> ```Go
> 	}
> 	metaMessagesDropped = metric.Metadata{
> 		Name: "storeliveness.transport.dropped",
> ```

Should we have separate metrics for `send_dropped` and `received_dropped`? We don't yet drop on receive, but once we do, it will be helpful to distinguish the two cases. EDIT: we do not drop on receive, as of commit 2. All the more reason to make this change here.
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UtgRp0jv8S-kT0I3U:-O7UtgRp0jv8S-kT0I3V:bhhihae) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/storeliveness/support_manager.go#L372)):*
> ```Go
> 	// Drop messages if maxReceiveQueueSize is reached.
> 	if len(q.mu.msgs) >= maxReceiveQueueSize {
> 		return errors.Errorf("store liveness receive queue is full")
> ```

We should pre-allocate this error as a static variable to avoid the cost on each dropped message. `var receiveQueueSizeLimitReachedErr = ...`
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7Uu05t-yXvsV0j4h4-:-O7Uu05t-yXvsV0j4h40:bwgjdgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/storeliveness/transport.go#L190)):*
> ```Go
> 		t.metrics.MessagesDropped.Inc(1)
> 	}
> 	t.metrics.MessagesReceived.Inc(1)
> ```

Do we want to increment "received" if "dropped" is incremented?

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131025)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`-- commits` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7Ut3sV2rrKiOLurjwm):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"blocked"
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/store.go` line 2194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UtKln5bad7CCJfzmQ:-O7VDrOb252-tj9os8IQ:b-3wtssf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/store.go#L2194)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is it surprising that this didn't cause any tests to fail? Was store liveness completely broken without this fix?
</blockquote></details>

No tests failed because I haven't added any tests with a real store. It should be caught by the end-to-end tests that I'll add soon. I spotted it in the logs while running a local cluster. Store liveness was running, and all stores were 0; I think it would have definitely caused issues if there were multiple stores per node.
___
*[`pkg/kv/kvserver/storeliveness/metrics.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UpLe28dZMBXWYvTMK:-O7VEf2-1KeM-xSeIj96:bl5eoqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/df958c6de7f36d321ecc2d15761e1cc32cdb4dc4/pkg/kv/kvserver/storeliveness/metrics.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we have separate metrics for `send_dropped` and `received_dropped`? We don't yet drop on receive, but once we do, it will be helpful to distinguish the two cases. EDIT: we do not drop on receive, as of commit 2. All the more reason to make this change here.
</blockquote></details>

Yes, good idea. I can also add metrics for the receiver queue, similar to the sender queue. Or leave it as a followup. 
___
*[`pkg/kv/kvserver/storeliveness/support_manager.go` line 372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7UtgRp0jv8S-kT0I3U:-O7VFfAo2GfJ2OFV190W:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/storeliveness/support_manager.go#L372)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should pre-allocate this error as a static variable to avoid the cost on each dropped message. `var receiveQueueSizeLimitReachedErr = ...`
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/storeliveness/transport.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-O7Uu05t-yXvsV0j4h4-:-O7VFghkDy4PLnC-XV0y:b9ujxrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3ed642fc22d127eb954026bd7def7f68d1d39a/pkg/kv/kvserver/storeliveness/transport.go#L190)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to increment "received" if "dropped" is incremented?
</blockquote></details>

Nope, good catch. I added a test too.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-:-O7_TsM22webMYKeqgt8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by miraradeva** [comment]
The most recent push deflakes the `TestTransportRestartedNode` test (some of the expected metrics were not always there in the presence of various expected races), and fixes the formatting of the `TestTransportFullReceiveQueue`.

**Review by nvb — APPROVED** [review]
:lgtm: when CI is green.

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131025#-:-O7eU0mh4BT3XANfL9cI:b-chrq76)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by miraradeva** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
