### PR TITLE
opt: add rule to replace ST_MaxDistance with ST_DFullyWithin

### PR DESCRIPTION
**Pull request by DrewKimball**
`ST_DFullyWithin` is equivalent to the expression `ST_MaxDistance <= x`.
Similar reformulations can be made for different comparison operators
(<, >, >=).

This PR consists of two commits. The first commit adds a builtin function 
`ST_DFullyWithinExclusive`, which is equivalent to `ST_MaxDistance < x`
but is able to exit early.

The second commit adds two rules that replace expressions of the form
`ST_MaxDistance <= x` with either `ST_DFullyWithin` or `ST_DFullyWithinExclusive`
depending on the comparison operator used. This replacement is desirable
because the `ST_DFullyWithin` function can exit early, while `ST_MaxDistance` cannot
do the same. `ST_DFullyWithin` can also be used to generate an inverted index scan.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-:-MFGCrxv-3vtKbNV-XmS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @otan)

___
*[pkg/geo/geomfn/distance.go, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFGAEPX0GboyhDMRsj-:-MFGAEPX0GboyhDMRsj0:b-vejlbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48a71c96933335c2339f41a17b78de8488abd4f/pkg/geo/geomfn/distance.go#L537)):*
> ```Go
> 			return dist >= u.stopAfter
> 		}
> 		return dist > u.stopAfter
> ```

This is the reverse of what the comment says

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53176)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/geo/geomfn/distance.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFGOhru7Lt9QhuPLvIB:-MFGOhru7Lt9QhuPLvIC:b-16uc02) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48a71c96933335c2339f41a17b78de8488abd4f/pkg/geo/geomfn/distance.go#L105)):*
> ```Go
> 		return false, err
> 	}
> 	if exclusive {
> ```

minor nit: missed this in the last pass, but since we have defined a bool for this, it is neater to use `exclusive == geo.FnExclusive` (in case someone swaps the bool around or what not). It may make sense to rename this `exclusivity` instead.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53176)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/geo/geomfn/distance.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFGOhru7Lt9QhuPLvIB:-MFI-Rzo8Md8Gt0XHr6I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48a71c96933335c2339f41a17b78de8488abd4f/pkg/geo/geomfn/distance.go#L105)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

minor nit: missed this in the last pass, but since we have defined a bool for this, it is neater to use `exclusive == geo.FnExclusive` (in case someone swaps the bool around or what not). It may make sense to rename this `exclusivity` instead.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/distance.go, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFGAEPX0GboyhDMRsj-:-MFHxhqtAQWJe6ReG-Rd:b22mi9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e48a71c96933335c2339f41a17b78de8488abd4f/pkg/geo/geomfn/distance.go#L537)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is the reverse of what the comment says
</blockquote></details>

Whoops, code is correct, comment is not. I'll change the comment. Done.

**Review by rytaft — COMMENTED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[pkg/geo/geomfn/distance.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFI5FpU7HDgClzuU9Pn:-MFI5FpV6wd-mvPSM7YS:bewk93r) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a22ae53914ab4f9424ba336b0e7fea49ea47d8/pkg/geo/geomfn/distance.go#L86)):*
> ```Go
> // points comprising geometries A and B is within D units. If exclusive,
> // DFullyWithin is equivalent to MaxDistance(a, b) < d. Otherwise, DWithin is
> // equivalent to Distance(a, b) <= d.
> ```

DWithin -> DFullyWithin, Distance -> MaxDistance

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53176)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/geo/geomfn/distance.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/53176#-MFI5FpU7HDgClzuU9Pn:-MFIARYa9hLWZiQtlv_3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a22ae53914ab4f9424ba336b0e7fea49ea47d8/pkg/geo/geomfn/distance.go#L86)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

DWithin -> DFullyWithin, Distance -> MaxDistance
</blockquote></details>

Done.

**Pull request merged**
