### PR TITLE
kv: log if request appears stuck

### PR DESCRIPTION
**Pull request by tbg**
See #8975.

Open for better suggestions here, but this should give us some idea without
being overly burdensome.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8997)

### CODE REVIEW

**Comment by tamird** [comment]
can you keep a counter just in dist sender? seems better to avoid rando changes

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 671 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQXEbzQLwU0a5Fnbw7y:-KQXEbzQLwU0a5Fnbw7z:bd9fi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f7c56beffd386b8b9b7543f1062a63791babc8/kv/dist_sender.go#L671)):*
> ```Go
> 				// Log a message if a request appears to get stuck for a long
> 				// time or, potentially, forever. See #8975.
> 				log.Warningf(ctx, ">= %d retries for an RPC, last error was: %s, remaining key range %s: %s", magicLogCurAttempt, pErr, rs, ba)
> ```

Similar to what @tamird suggests, I'd add a counter outside of the loop and then inside the loop do something like:

```
  count++
  if count % 20 == 0 {
    log.Warningf(ctx, "%d retries for an RPC, last error was: %s, remaining key ranges %s: %s", count, pErr, rs, ba)
  }
```

---

*[util/retry/retry.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQXEpGbSVrNlmUV3ybu:-KQXEpGbSVrNlmUV3ybv:b-9h7a9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f7c56beffd386b8b9b7543f1062a63791babc8/util/retry/retry.go#L104)):*
> ```Go
> // TotalAttempts is zero initially and increases with each call to Next().
> func (r *Retry) TotalAttempts() int {
> 	return r.currentAttempt
> ```

Heh, should probably be returning `r.totalAttempt`. But really I think this belongs in the `DistSender` code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997)*

**Comment by tschottdorf** [comment]
Can't argue with that. Done.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 671 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQXEbzQLwU0a5Fnbw7y:-KQXfqKNWgDNvB_OAnmP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f7c56beffd386b8b9b7543f1062a63791babc8/kv/dist_sender.go#L671)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Similar to what @tamird suggests, I'd add a counter outside of the loop and then inside the loop do something like:
> 
> ```
>   count++
>   if count % 20 == 0 {
>     log.Warningf(ctx, "%d retries for an RPC, last error was: %s, remaining key ranges %s: %s", count, pErr, rs, ba)
>   }
> ```
</details>
Done.

---

*[util/retry/retry.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQXEpGbSVrNlmUV3ybu:-KQXfrDDtflDJQcvT7tC:b-j61j5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f7c56beffd386b8b9b7543f1062a63791babc8/util/retry/retry.go#L104)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Heh, should probably be returning `r.totalAttempt`. But really I think this belongs in the `DistSender` code.
</details>
Typical copy pasta. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-:-KQXfI0GuKGiuqi9cfDx:b-yegusl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kv/dist_sender.go, line 676 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQZlHhUa35aLC_navG2:-KQZlHhVAaRFi7TuHoqN:b-3n9nml) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d691be2a8901bb153ae9a1ed817fceb1f0e1ebd/kv/dist_sender.go#L676)):*
> ```Go
> 				// should capture anything higher up (as it needs to be
> 				// incremented every time this method is called).
> 				log.Warningf(ctx, "%d retries for an RPC, last error was: %s, remaining key ranges %s: %s", numAttempts, pErr, rs, ba)
> ```

This logging can be triggered by either numAttempts or Txn.Sequence. If the latter, we should include that in the message. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-:-KQZlP94jWBYkCqvR1T1:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[kv/dist_sender.go, line 676 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997#-KQZlHhUa35aLC_navG2:-KQa1iLkXHLUF-WMJJTo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d691be2a8901bb153ae9a1ed817fceb1f0e1ebd/kv/dist_sender.go#L676)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This logging can be triggered by either numAttempts or Txn.Sequence. If the latter, we should include that in the message. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8997)*

**Pull request merged**
