### PR TITLE
Added warn_unused_result_attribute to db.cc Fixes #13101

### LINKED ISSUE #13101: rocksdb: Use `warn_unused_result` where appropriate
If we added the `warn_unused_result` attribute to functions in `storage/engine/rocksdb/db.cc` whose return values indicate success or failure, we could avoid oversights like #13099.

### PR DESCRIPTION
**Pull request by soniabhishek**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13607)

### CODE REVIEW

**Comment by bdarnell** [comment]
Hi Abishek, thanks for the contribution. However, as you can see in the [CI  logs](https://teamcity.cockroachdb.com/viewLog.html?buildId=151289&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildLog), at least some compilers are unhappy with this placement of the attributes. It looks like it wants a separate declaration with the attribute, instead of putting it on the definition itself. 

We may also want to put this attribute behind a macro so it can be `#ifdef`ed away if we need to support a compiler that doesn't support `warn_unused_result`.

Finally, if you amend your commit message to include `Fixes #13101`, github will automatically make a link to that issue.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13607#-:-Kd2EvSXy1aqkqpdihcH:b-vk9gny)*

**Comment by tamird** [comment]
@soniabhishek do you plan to address @bdarnell's concerns? This currently needs a rebase, as well.

**Comment by soniabhishek** [comment]
@bdarnell sorry for delay. I want to complete this but I am little bit stuck with your macro statement can you provide a example with function declaration  behind a macro.

**Comment by soniabhishek** [comment]
I am getting this error while running **make build** command

> Abhisheks-MacBook-Pro:cockroach abhishek$ make build
GOPATH set to /Users/abhishek/dev/go
make[1]: Nothing to be done for `build_lib_static'.
rm -rf /Users/abhishek/dev/go/native/x86_64-apple-darwin16.6.0/protobuf
mkdir -p /Users/abhishek/dev/go/native/x86_64-apple-darwin16.6.0/protobuf
cd /Users/abhishek/dev/go/native/x86_64-apple-darwin16.6.0/protobuf && cmake  -Dprotobuf_BUILD_TESTS=OFF /Users/abhishek/dev/go/src/github.com/cockroachdb/cockroach/c-deps/protobuf.src/cmake
/bin/bash: cmake: command not found
make: *** [/Users/abhishek/dev/go/native/x86_64-apple-darwin16.6.0/protobuf/Makefile] Error 127

**Comment by jordanlewis** [comment]
@AbhishekSaha, you'll need to install `cmake` - on Mac with Homebrew you can do that with `brew install cmake`. Please see the "install from source" instructions here: https://www.cockroachlabs.com/docs/install-cockroachdb.html

**Comment by soniabhishek** [comment]
thanks @jordanlewis but you mentioned wrong guy.

**Comment by jordanlewis** [comment]
Oops, very sorry!

**Comment by bdarnell** [comment]
For the macro, I mean to `#define` it in the header, like this (from [chromium](https://chromium.googlesource.com/chromium/src/base/+/master/compiler_specific.h#142)):

```
#if defined(COMPILER_GCC) || defined(__clang__)
#define WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
#define WARN_UNUSED_RESULT
#endif
```

And use it in declarations like

```
bool SplitKey(rocksdb::Slice buf, rocksdb::Slice *key, rocksdb::Slice *timestamp) WARN_UNUSED_RESULT;
```

**Comment by soniabhishek** [comment]
@bdarnell I did this
`#define WARN_UNUSED_RESULT __attribute__((warn_unused_result))`
and put this in front of definition  like this
`WARN_UNUSED_RESULT bool SplitKey(rocksdb::Slice buf, rocksdb::Slice *key, rocksdb::Slice *timestamp) { ...}`

So I observed when ever this attribute is place in front of definition this works. So do we still require to have a separate declaration with.??

**Comment by soniabhishek** [comment]
Also at line 661 when i add attribute to this definition.
`WARN_UNUSED_RESULT bool ConsolidateTimeSeriesValue(std::string *val, rocksdb::Logger* logger)`

It gives a warning of unused result when i test at Line 737
`onsolidateTimeSeriesValue(left->mutable_raw_bytes(), logger);`

**Comment by bdarnell** [comment]
> So I observed when ever this attribute is place in front of definition this works. So do we still require to have a separate declaration with.??

If it works with all compilers then it's fine. But in the previous version of the PR, it worked in some compilers but not others. Push your new changes and see if it the tests now pass.

> It gives a warning of unused result when i test at Line 737
ConsolidateTimeSeriesValue(left->mutable_raw_bytes(), logger);

That's exactly the kind of bug we were hoping to find with this change! That call should be changed to something like this:

    if (!ConsolidateTimeSeriesValue(left->mutable_raw_bytes(), logger)) {
        return false;
    }

**Comment by bdarnell** [comment]
LGTM, but I think the macro should be conditionally defined as in this comment: https://github.com/cockroachdb/cockroach/pull/13607#issuecomment-310230737

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13607#-:-KnbloQFWungrVX2oiqX:b-3ywa73)*

**Comment by soniabhishek** [comment]
@bdarnell i have changed it as per your reviews

**Comment by bdarnell** [comment]
Thanks!

**Comment by soniabhishek** [comment]
Thanks @bdarnell for your help. I am looking forward for more such contributions. Can you assign me any task.

**Comment by bdarnell** [comment]
@soniabhishek Take a look at the [helpwanted](https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue+label%3Ahelpwanted+no%3Aassignee) label in our issue tracker.

**Pull request merged**
