### PR TITLE
sql,*: remove DistributionTypeSystemTenantOnly

### LINKED ISSUE #116534: sql: reconsider remaining uses of DistributionTypeSystemTenantOnly
**Describe the problem**

Planners created with `DistributionTypeSystemTenantOnly` won't distribute work across SQL pods.  This represents a possible performance problem for operations inside secondary tenants.

```
pkg/ccl/streamingccl/streamproducer/stream_lifetime.go
290:		nil /* planner */, nil /* txn */, sql.DistributionTypeSystemTenantOnly)
```

```
pkg/sql/backfill.go
1048:			txn.KV(), DistributionTypeSystemTenantOnly)
1355:				DistributionTypeSystemTenantOnly)
```

```
pkg/sql/create_stats.go
600:			DistributionTypeSystemTenantOnly)
```

```
pkg/sql/distsql_plan_ctas.go
36:		distribute = DistributionTypeSystemTenantOnly
```

```
pkg/sql/distsql_spec_exec_factory.go
78:		distribute = DistributionTypeSystemTenantOnly
```

```
pkg/sql/index_backfiller.go
196:			nil /* planner */, txn.KV(), DistributionTypeSystemTenantOnly)
```

```
pkg/sql/mvcc_backfiller.go
142:			DistributionTypeSystemTenantOnly)
```

Jira issue: CRDB-34659

### PR DESCRIPTION
**Pull request by stevendanna**
**sql,*: remove DistributionTypeSystemTenantOnly**

Uses of DistributionTypeSystemTenantOnly represent places where UA/MT performance may not match single-tenant performance.

This replaces all uses of DistributionTypeSystemTenantOnly with DistributionTypeAlways.

Epic: none

Fixes #116534

**sql: rename two DistributionType options**

This commit does the following renaming to better represent the options:
- `DistributionTypeNone` -> `LocalDistribution`
- `DistributionTypeAlways` -> `FullDistribution`.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/sql/distsql_physical_planner.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116559#-NlyhPnv3b4ZJkJqeir5:-NlyhPnw8bT-oPwRfdqi:bnocpy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/20470d4569a49b82bf684da8d63c7cb9c7262638/pkg/sql/distsql_physical_planner.go#L153)):*
> ```Go
> const (
> 	// DistributionTypeNone does not distribute a plan across multiple instances.
> 	DistributionTypeNone = iota
> ```

Since we're now down to only two options, let's clean up this a bit. Should we just remove `DistributionType` altogether in favor of using `distribute bool` argument in its place? Or we could replace this type to use `bool` and rename two remaining options to something like `LocalDistribution` and `FullDistribution`. WDYT?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116559)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/sql/distsql_physical_planner.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116559#-NlyhPnv3b4ZJkJqeir5:-Nssli94-pImHNKodNor:b-byvwlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20470d4569a49b82bf684da8d63c7cb9c7262638/pkg/sql/distsql_physical_planner.go#L153)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Since we're now down to only two options, let's clean up this a bit. Should we just remove `DistributionType` altogether in favor of using `distribute bool` argument in its place? Or we could replace this type to use `bool` and rename two remaining options to something like `LocalDistribution` and `FullDistribution`. WDYT?
</blockquote></details>

I added another commit to do the renaming (while keeping the two-value enum).

**Review by yuzefovich — APPROVED** [review]
:lgtm: Perhaps someone else from @cockroachdb/sql-queries-prs should take a look too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116559#-:-NssmCvV-K95z6v-SnX7:b-6njulq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, @rharding6373, and @stevendanna)

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 4 of 11 files at r1, 7 of 7 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116559#-:-NstUtiqEqimojnvxiwd:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @dt, @rharding6373, and @stevendanna)

**Comment by yuzefovich** [comment]
Thanks!

bors r+

**Comment by stevendanna** [comment]
Thanks @yuzefovich !

**Pull request merged**
