### PR TITLE
build: disable jemalloc profiling in musl builds

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by benesch** [comment]
Did you test this on Alpine or should I?

**Comment by benesch** [comment]
Also, this needs to wait for 1.1, no?

**Comment by tamird** [comment]
Please do!

**Comment by tamird** [comment]
It should be safe either way, since it doesn't affect gnu binaries, but
there's no reason it can't wait.

**Comment by tamird** [comment]
Confirmed this makes the musl binary not deadlock on boot.

**Comment by benesch** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15675#-:-KjGvZYHNWe0nFPMRit3:b-uwkowd)*

**Pull request merged**
