### PR TITLE
roachtest: fix bench roachtests failing with validation when using json

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
The roachtests starting failing with validation errors `Error: error
creating metrics exporter: file path must end with .json` after this PR
was merged https://github.com/cockroachdb/cockroach/pull/133035 path
defined in `GetWorkloadHistogramArgs` was jumbled.

Also there was an error in
https://github.com/cockroachdb/cockroach/pull/135239.

This change intends to fix all the errors.

Epic: none

Release note: None

### CODE REVIEW

**Comment by sambhav-jain-16** [comment]
Triggered a test run: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/17810012?buildTab=overview&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true to verify the changes are working fine.

**Comment by srosenberg** [comment]
> The roachtests starting failing with validation errors `Error: error creating metrics exporter: file path must end with .json`. The path defined in `GetWorkloadHistogramArgs` was jumbled. This change intends to fix that.

Can you update your commit message to reference the aforementioned PR.

**Comment by sambhav-jain-16** [comment]
> > The roachtests starting failing with validation errors `Error: error creating metrics exporter: file path must end with .json`. The path defined in `GetWorkloadHistogramArgs` was jumbled. This change intends to fix that.
> 
> Can you update your commit message to reference the aforementioned PR.

Done

**Review by srosenberg — APPROVED** [review]

**Comment by sambhav-jain-16** [comment]
There were more errors in a different PR that I merged in the scripts https://github.com/cockroachdb/cockroach/pull/135239 (The build succeeded when I tested in my branch, not sure what happened suddenly).
I have reverted that commit in this PR to unblock the nightlies.

**Pull request merged**
