### PR TITLE
[DNM] protoutil: allocate uninitialized slices during protobuf marshaling

### LINKED ISSUE #22280: perf: investigate protobuf marshaling optimization
All of our protobuf marshaling code has a pattern that looks like:

```
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
```

We're allocating a zero-initialized slice and then overwriting it. Per #22244, we could do a similar hack to allocate an uninitialized slice.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #22280.

This change uses a similar hack to #22244 to avoid zero-initializing
byte slices that are allocated and immediately populated during
protobuf marshaling.

A comprehensive performance analysis of this has not been performed
yet. It's unclear whether this is a worthwhile change.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
All protobuf marshaling in our code flows through `protoutil. Marshal` (enforced by [`TestProtoMarshal `](https://github.com/cockroachdb/cockroach/blob/379771c762396337352e2b6f68c72db10d465d0d/pkg/testutils/lint/lint_test.go#L479)), so it will hit this optimization. However, it's not clear to me yet whether this is true of protobuf marshaling performed by gRPC or other libraries on our behalf.

**Comment by jordanlewis** [comment]
Good idea!

---

Reviewed 9 of 9 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26839#-:-LFOnaIC8orM4rIDUcW4:b-ovwawk)*

**Comment by nvanbenschoten** [comment]
> However, it's not clear to me yet whether this is true of protobuf marshaling performed by gRPC or other libraries on our behalf.

gRPC performs encoding and decoding of messages using a [`Codec`](https://github.com/grpc/grpc-go/blob/master/encoding/encoding.go#L71). These Codecs are configurable, but we use the default [proto codec](https://github.com/grpc/grpc-go/blob/master/encoding/proto/proto.go). This default version calls into all `proto.Marshaler`'s `Marshal` method. 

I wasn't able to observe any measurable difference when running with this change or with a more dramatic version of it where all generated `Marshal` methods are switched to use `unsafeutil.NonZeroingMakeByteSlice`. My experiments were to run `kv95` on a multi-node cluster and to run `BenchmarkWideTableIgnoreColumns/MultinodeCockroach` before and after the change. This indicates that this change isn't worthwhile from a perf perspective.

I'll defer to @petermattis about whether the commit here is worthwhile from a refactoring perspective, as it cleans up a bit of utility code that didn't belong in the `engine` package.

**Comment by petermattis** [comment]
go1.11's version of `gobytes` has this optimization builtin, so I was hoping to get rid of this hack. Since using it in protobuf marshaling doesn't seem to make a difference, I would leave it as-is to make it easier to delete.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26839#-:-LFx2zM43pLmcVU9tb_0:bar8e7t)*

**Comment by nvanbenschoten** [comment]
SGTM. I'm happy to avoid making this hack easier to use.

**Pull request closed without merging**
