### PR TITLE
backupccl: allow for remapping backed up types to existing types

### LINKED ISSUE #50324: backupccl: allow mapping of types to existing types in cluster
When restoring a table into a cluster that contains user defined types that overlap with the backup, the user needs to be able to allow the restore process to use the existing type in the cluster, if possible.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50324.

This PR extends the initial work on backup/restore with user defined
types to allow for remapping a type in a backup to a type that exists in
the cluster already.

In particular, restore attempts the following for each type within a
table backup:

* If there is not another type with the same name, create the type that
  exists in the backup.
* If there is another type with the same name that is compatible with
  the type in the backup, then remap the type in the backup to the type
  in the cluster.
* If there is another type with the same name that is not compatible
  with the type in the backup, then bail out and ask the user to resolve
  the name conflict (by either dropping or renaming the existing type).

Release note (enterprise change): Add the ability for restore to remap
user defined types within the backup to existing types in the cluster.

### CODE REVIEW

**Comment by rohany** [comment]
Putting this up for some early reviews -- I'll add some more tests if this approach looks good. This PR lets a user map a type within a backup to an existing type in the cluster, but I'm not sure what to do if the user doesn't provide a mapping, and a type within the backup collides with a type in the cluster. In the case that the two are not compatible, what should happen?

**Comment by pbardea** [comment]
I'm looking at the UX and am considering the case where someone would script their restores, or is run by an administrator who isn't familiar with the application itself. This is the first time that we're referencing application type logic in the restore command itself.

I think the vast majority of the time the user will want to restore the type with the same name. With that in mind, I think it may make sense to have an option (something like `WITH ignore_type_conflicts`) that indicates that the restore should map to the existing type in the case of a name conflict. If the type is incompatible, the restore would fail and they would be able to rename the type and repeat the restore. This would more closely match what restore does today with regards to FKs.

cc @dt and @mwang1026 in case you have any thoughts here.

**Comment by rohany** [comment]
I do like the idea of having some option to automatically try to remap all backup types to cluster types -- while writing this PR, it already seems burdensome to track what types are in a backup and what they should map to. So a workflow like:
* By default, remap all types in a backup to the corresponding type in a cluster if there is a conflict and those types are compatible
* If there is a conflict, prompt to the user to provide a remapping.
* If there is a conflict and there isn't a valid type to remap to, then bail out completely and ask the user to either rename or drop the existing type in the cluster so the restore can succeed.

I'm not all too happy with the final step here, but maybe it isn't that bad because it only affects restores of single tables, not db's or full cluster.

**Comment by pbardea** [comment]
That sounds reasonable to me. I also I would be fine without step 2, where we just error out and ask them to rename the types so that either there is no conflict, or the conflict is moved out of the way. I'm mainly hesitant on how we allow the user to provide a mapping. We've discussed this issue before with users and I want to try to not paint ourselves in a corner to prevent us from remapping other items.

I think we should also think if we want this auto-mapping behaviour to be enabled by default (I think it is probably a sensible default), and if it is if it makes sense to provide a flag that will just give an error on conflicts.

**Comment by rohany** [comment]
Alright, that makes sense. Not having to manage these remappings explicitly makes life easier. Before I change the code, what do @dt and @mwang1026 think?

**Comment by mwang1026** [comment]
I did some snooping on how PG does this. Didn't find a definite answer (and I think it'd be worth actually testing this to see their behavior before committing to an implementation).

https://stackoverflow.com/questions/21357348/postgresql-backup-restore-with-custom-functions
This is about custom functions and restoring that function specifically, but if the function already exists with that name it errors out when you try to restore that function

https://stackoverflow.com/questions/29708226/pg-dump-a-custom-data-type
Restoring a table with a column referencing a type that doesn't yet exist throws an error, but it SEEMS like if that type exists then it restores fine

My 2c is that it's OK to restore if the type name + definition match, create the type if the type name does not exist, and if the name matches but definition doesn't throw a user-friendly error. I agree with Paul that remapping should happen independent of the restore.

**Comment by rohany** [comment]
I don't know of an equivalent PG tool to compare to here -- these are talking about `pg_dump`, which emits raw SQL about what operations to perform. So when importing the dumped SQL, the standard checks for "does this type exist yet" come into play, and it's possible to just remove a type creation statement (or only dump type creation statements) from the dump to not conflict with an existing type in the database.

**Comment by mwang1026** [comment]
Ack. My research was mainly about how to handle errors if there are conflicts in the user-defined types. As in,
- Can you restore a table referencing a type that doesn't exist -- in that case our job is easy, we just restore the type and the table and the data. PG errors because it doesn't know how to create that type unless it's also in the dump file.
- Can you restore a table referencing a type that already exists -- if the type name and definition in the to-be-restored-table match an existing one in the cluster (are UDT defined at cluster level?) then we should just restore the table + data and point to the existing UDT. Seems like PG just assumes you mean the type that already exists--and since pq_dump is string representation I guess you don't have issues re: reading the bytes in correctly that we would have.
- Can you restore a table referencing a type whose name matches an existing type but the definition does not? -- we should error out on this type of clash
- Can you restore a table referencing a type whose name doesn't match an existing type but definition does? -- can they define two named types with the same definition? this one I'm fuzzy about.

Are those the only scenarios?

**Comment by rohany** [comment]
> Can you restore a table referencing a type whose name doesn't match an existing type but definition does? -- can they define two named types with the same definition? this one I'm fuzzy about.

This is a pretty wonky case -- I think it would be over zealous to try and handle this case implicitly. The different names already means they are separate types, so we shouldn't look at the definitions. This sort of case would have to be handled with an explicit remapping.

I think that these are the only scenarios. PG dump avoids part of scenario 3 by dumping data as strings, so it doesn't run into the case of "name and definitions are the same, but internal representations are different".

**Comment by pbardea** [comment]
So to summarize, it sounds like we've reached some consensus on:
> restore if the type name + definition match, create the type if the type name does not exist, and if the name matches but definition doesn't throw a user-friendly error. 

I think if we want to add the ability to remap to a type with a different name, we can do that in a separate PR.

**Comment by rohany** [comment]
Updated PR to perform the steps here, and removed the manual remapping.

**Comment by rohany** [comment]
bumping

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @rohany)

___
*[pkg/ccl/backupccl/backup_test.go, line 1442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaciXC1MC-gRz2WRwI:-MAaciXC1MC-gRz2WRwJ:bd0th6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/backup_test.go#L1442)):*
> ```Go
> 	// Test cases where we attempt to remap types in the backup to types that
> 	// already exist in the cluster.
> 	t.Run("backup-remap", func(t *testing.T) {
> ```

Can we add a test case that tries to restore a type that's not identical, but compatible with the one in the restoring cluster? Can we also add a test case when we try to restore a type with a conflicting descriptor name?
___
*[pkg/ccl/backupccl/restore_planning.go, line 377 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaeQ3D1f8D4v2iIg13:-MAaeQ3D1f8D4v2iIg14:b-ihheb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/restore_planning.go#L377)):*
> ```Go
> 				needsNewParentIDs[targetDB] = append(needsNewParentIDs[targetDB], typ.ID)
> 			} else {
> ```

nit: extra empty line?
___
*[pkg/ccl/backupccl/restore_planning.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaiheTAMnb-C5ktZhZ:-MAaiheTAMnb-C5ktZh_:b-908pc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/restore_planning.go#L420)):*
> ```Go
> 					arrTyp := typesByID[typ.ArrayTypeID]
> 					if err := CheckObjectExists(ctx, txn, p.ExecCfg().Codec, parentID, keys.PublicSchemaID, arrTyp.Name); err != nil {
> 						return errors.Wrapf(err, "name collision for %q's array type", typ.Name)
> ```

For my understanding, how would we expect there to be a collision with the array type name and not with the underlying type itself?

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 1442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaciXC1MC-gRz2WRwI:-MAbGaxW4tauSAWDt586:b-d5vgg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/backup_test.go#L1442)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we add a test case that tries to restore a type that's not identical, but compatible with the one in the restoring cluster? Can we also add a test case when we try to restore a type with a conflicting descriptor name?
</blockquote></details>

This isn't possible without `ALTER TYPE` -- if the initial set of values has a different size, then the types won't be compatible. I'll add a TODO to come and add a test when it's possible.
___
*[pkg/ccl/backupccl/restore_planning.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaiheTAMnb-C5ktZhZ:-MAbHusbABDZjVnL-b_D:b6mk1dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/restore_planning.go#L420)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

For my understanding, how would we expect there to be a collision with the array type name and not with the underlying type itself?
</blockquote></details>

PG has some pretty weird (read dumb) rules for the array type name. When creating a type, it'll keep adding `_` to the front of the type name until there isn't a collision anymore for the array type. There could maybe be a case here where those rules result in a name conflict.

**Review by pbardea — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rohany)

___
*[pkg/ccl/backupccl/restore_planning.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaiheTAMnb-C5ktZhZ:-MAbVzp68igD9gZI2zMj:bifr7ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/restore_planning.go#L420)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

PG has some pretty weird (read dumb) rules for the array type name. When creating a type, it'll keep adding `_` to the front of the type name until there isn't a collision anymore for the array type. There could maybe be a case here where those rules result in a name conflict.
</blockquote></details>

Wow - I see... so we could potentially restore a type to the cluster, but the array type could have a different name. That might be worth having in a test case. I'm thinking something like:
In db1:
`CREATE TYPE _t1 ...` -> creates `_t1` and `__t1`
`CREATE TYPE t1 ...` -> creates `t1` and `___t1`

In db2:
`CREATE TYPE t1 ...` -> creates `t1` and `_t1`
Restore a table that uses the array type of t1 from db1. Ensure that the array type works properly.

I expect this to work, but is a bit of a tricky edge case and it would be nice to have this odd behavior documented in the tests.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50349#-MAaiheTAMnb-C5ktZhZ:-MAbkiH10pSWo8rVPxOT:b3x66mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd057df8eeaf1082e41259f0ad640d4e0531e5bb/pkg/ccl/backupccl/restore_planning.go#L420)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Wow - I see... so we could potentially restore a type to the cluster, but the array type could have a different name. That might be worth having in a test case. I'm thinking something like:
In db1:
`CREATE TYPE _t1 ...` -> creates `_t1` and `__t1`
`CREATE TYPE t1 ...` -> creates `t1` and `___t1`

In db2:
`CREATE TYPE t1 ...` -> creates `t1` and `_t1`
Restore a table that uses the array type of t1 from db1. Ensure that the array type works properly.

I expect this to work, but is a bit of a tricky edge case and it would be nice to have this odd behavior documented in the tests.

</blockquote></details>

Yeah, it's pretty wonky. Added a test cases.

**Comment by rohany** [comment]
bors r=pbardea

**Pull request merged**
