### PR TITLE
changefeedccl: fix DELETEs in cloud storage sinks

### LINKED ISSUE #36994: changefeedccl: no key for deleted records in cloud storage sink
Kafka has a key and a value in each message, but there's no place to put the key in the cloud storage sink, which is just an ndjson file of the values. I'd intended to put the key in the value in this case, but looks like that got dropped. This would also be a nice `WITH option` to have for non-cloud storage changefeeds, too.

### PR DESCRIPTION
**Pull request by danhhz**
All the other sinks (Kafka etc) have a place in each message for a key
and a value, but cloud storage sinks only have a place for a key. The
wrapper format we just moved to has a natural place to put the key (as
an entry in the wrapper), but we weren't doing this.

This commit adds a `WITH key_in_value` option that turns on this
behavior and defaults it to on for any changefeed using a cloud storage
sink.

Closes #36994

Release note (bug fix): `CHANGEFEED` now have a key_in_value option;
this is automatically used for cloud storage sinks, making the primary
key of deleted rows recoverable

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Squash the fixup commit please.

> Reviewed 8 of 8 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37147#-:-LdLOA7f74xG_sPxKHN7:b5x03h2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by tbg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37147#-:-LdLPSri-pkY5DFQA_QK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by danhhz** [comment]
Thanks for the review!

bors r=tbg

**Comment by danhhz** [comment]
`fixup! changefeedccl: fix DELETEs in cloud storage sinks`

🤦‍♂ my shame is forever committed to public record. i wonder if i could put something in my `~/.gitconfig` to make `git rebase` always run with `--autosquash`

**Comment by danhhz** [comment]
Indeed I can: `git config --global rebase.autosquash true`

**Comment by tbg** [comment]
What's your workflow for the `fixup!` commits btw? Do you look up manually which commit you want to amend, and then copy-paste the title into the title of your new commit?

**Comment by danhhz** [comment]
I look up the sha I want to amend and then use `git commit --fixup <sha>` which generates the message for you

**Pull request merged**
