### PR TITLE
sql: include db name in job descriptions

### LINKED ISSUE #17910: ui: Admin UI Jobs Table is ambiguous
**FEATURE REQUEST**

In the jobs table, the database on which the jobs are running in ambiguous since we only show the table name: 

image

We need another column or some other way to indicate which database is being impacted given the jobs table is scoped to the cluster.

cockroach version
Build Tag:    798df64
Build Time:   2017/08/21 15:05:23
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  798df647566b6bd5391f533f865d2e85bc756ca8
Build Type:   release-gnu

### PR DESCRIPTION
**Pull request by dt**
Fixes #17910.

### CODE REVIEW

**Comment by benesch** [comment]
CCL code all :lgtm:! I'll defer to @knz on the sql/parser code. Thanks, @dt! :raised_hands: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-:-KsoSVeiuq9DF6PdOJro:b-snjnna)*

**Comment by knz** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/grant.go, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-KssC_zlNITiTIcngsCN:-KssC_zmepjeb2NUD8NA:bnk4slu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d676af03eb6088a6011e36dbb67bef2ad59f900/pkg/sql/parser/grant.go#L64)):*
> ```Go
> 
> 		if db != "" {
> 			if name, ok := pattern.(*TableName); ok {
> ```

You need to qualify instances of `AllTablesSelector` too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036)*

**Comment by dt** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/grant.go, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-KssC_zlNITiTIcngsCN:-KstEtRZASR5yeG9qcuk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d676af03eb6088a6011e36dbb67bef2ad59f900/pkg/sql/parser/grant.go#L64)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to qualify instances of `AllTablesSelector` too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036)*

**Comment by knz** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/grant.go, line 66 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-KstH-bNYkijiRrdGDwF:-KstH-bO7rB2V9Xd5YMR:b-tewqwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cccf5f41f443275e8d365b6fac844a51206a69d/pkg/sql/parser/grant.go#L66)):*
> ```Go
> 			switch p := pattern.(type) {
> 			case *TableName:
> 				if err := p.QualifyWithDatabase(db); err != nil {
> ```

I'd recommend making an interface to TablePattern to do the qualification, this way you ensure that all instances are covered in all cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036)*

**Comment by dt** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/grant.go, line 66 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-KstH-bNYkijiRrdGDwF:-KstKrGwIFbHdtdlwXVM:b1gxh1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9cccf5f41f443275e8d365b6fac844a51206a69d/pkg/sql/parser/grant.go#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd recommend making an interface to TablePattern to do the qualification, this way you ensure that all instances are covered in all cases.
</blockquote></details>

Made an interface -- didn't add to `TablePattern` directly because of UnresolvedName, but I put the implementer assertion list next to the `TablePattern`'s for discoverability. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18036#-:-KstRqJyFEzJ1_1nhjWj:bnfp4nl)*

**Pull request merged**
