### PR TITLE
pgwire: rename ReadBuffer.GetString to GetUnsafeString

### PR DESCRIPTION
**Pull request by fqazi**
Previously, it was not clear that GetString would not copy data from the ReadBuffer. This could be problematic if the object was long lived, since the entire buffer would have been kept alive. To reduce risk, this patch renames GetString to GetUnsafeString. It also adds a GetSafeString method for cases where a copy is needed. The latter is adopted inside: parseClientProvidedSessionParameters

Informs: #137627
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice, this is will be very helpful for avoiding similar bugs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137682#-:-OEPJhhy9zRM7dEe_mxV:bdzdphi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Review by mgartner — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137682#-:-OEQASd19lEEl2kaXB2m:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Pull request merged**
