### PR TITLE
kvserver: remove unused snapshot fields

### PR DESCRIPTION
**Pull request by andrewbaptist**
This commit removes a number of unused fields in snapshot messages.

Release note: None
Epic: none

### CODE REVIEW

**Comment by andrewbaptist** [comment]
This can be merged into 24.1 if #102629 goes into 23.2. That patch stops reading the field everywhere, but this patch actually removes the fields.

**Comment by pav-kv** [comment]
> This can be merged into 24.1 if https://github.com/cockroachdb/cockroach/pull/102629 goes into 23.2. That patch stops reading the field everywhere, but this patch actually removes the fields.

Does this presume that upgrades from 23.2 to 24.1 will happen from a 23.2 minor version that contains this patch? That won't always be true, will it?

**Comment by andrewbaptist** [comment]
All the 23.2 builds have that patch (it was merged prior to the 23.2 branch) so it will be ok from any 23.2.x version. However we could consider deferring this until 24.2 if we want to support 23.1 -> 24.1 upgrades. On Jan 25, 2024, at 11:55 PM, Pavel Kalinnikov ***@***.***> wrote:﻿

This can be merged into 24.1 if #102629 goes into 23.2. That patch stops reading the field everywhere, but this patch actually removes the fields.

Does this presume that upgrades from 23.2 to 24.1 will happen from a 23.2 minor version that contains this patch? That won't always be true, will it?

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99884#-:-NpQGmRA-DXG_P9ZFIsQ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 1394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99884#-NpQGMbq0SDhpVE50Whm:-NpQGMbq0SDhpVE50Whn:b-rxniaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb40c98a1b97a4e67b26e66caa9cfd18ac52b7d/pkg/kv/kvserver/store_snapshot.go#L1394)):*
> ```Go
> 		} else if header.SenderQueueName == kvserverpb.SnapshotRequest_OTHER {
> 			s.metrics.RangeSnapshotRebalancingRcvdBytes.Inc(inc)
> 		} else { // replicate queue does both types, so need to split
> ```

nit: move the comment below and capitalize.
___
*[`pkg/kv/kvserver/client_merge_test.go` line 3726 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99884#-NpQEwlV5oA9KTV92EpO:-NpQEwlV5oA9KTV92EpP:b3x4yp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/79603e69de4e04d2d2b7100380376318d3fe82f1/pkg/kv/kvserver/client_merge_test.go#L3726)):*
> ```Go
> 		sstNames []string,
> 	) error {
> 		// Only verify snapshots of type VIA_SNAPSHOT_QUEUE and on the range under
> ```

nit: should the VIA_SNAPSHOT_QUEUE part of this comment be removed?

**Comment by andrewbaptist** [comment]
bors r=kvoli

**Pull request merged**
