### PR TITLE
go.mod: bump Pebble to 0cd1ceea645a

### PR DESCRIPTION
**Pull request by RaduBerinde**
0cd1ceea db: add SetCreatorID
51684eae db: reorder existing format major version for pre-Pebblev1 tables
e2ebcd7a db: add format major version for flushable ingests
63a83669 objstorage: allow attaching of shared objects
8285e8dd db: wait for compactions in scan step
02d779ff objstorage: basic shared object functionality
b2293d08 objstorage: add in-memory and logging implementations of shared.Storage
fccb83b6 record: fix TestSyncRecordWithSignalChan flake

Release note: none
Epic: none

### CODE REVIEW

**Comment by nicktrav** [comment]
Beat me to it! Can you also apply this:

```diff
diff --git a/pkg/clusterversion/cockroach_versions.go b/pkg/clusterversion/cockroach_versions.go
index 17cf6f4afbd..b168721c715 100644
--- a/pkg/clusterversion/cockroach_versions.go
+++ b/pkg/clusterversion/cockroach_versions.go
@@ -360,9 +360,7 @@ const (

        // V23_1EnsurePebbleFormatSSTableValueBlocks upgrades the Pebble format major
        // version to FormatSSTableValueBlocks, which supports writing sstables in a
-       // new format containing value blocks (sstable.TableFormatPebblev3). As part
-       // of this upgrade, a preceding Pebble format major version
-       // (FormatPrePebblev1MarkedCompacted) upgrade also occurs.
+       // new format containing value blocks (sstable.TableFormatPebblev3).
        //
        // Only a Pebble version that has upgraded to FormatSSTableValueBlocks can
        // read sstables with format sstable.TableFormatPebblev3 -- i.e., it is
```

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97847#-:-NPSmD41B0dCXOw1Y2rv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

**Review by RaduBerinde — COMMENTED** [review]
Done. TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97847#-:-NPT30F0Cdqf8wZKBeTY:bw14vpv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick)

**Pull request merged**
