### PR TITLE
sql: add Index interface and TableDescriptor methods in catalog

### PR DESCRIPTION
**Pull request by postamar**
Previously, the catalog.TableDescriptor interface and its implementing
types would liberally return descpb.IndexDescriptor values, pointers and
slices. In an effort to stop manipulating such protos directly, this
patch introduces a catalog.Index interface to encapsulate it.

Addresses #57465.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This is like https://github.com/cockroachdb/cockroach/pull/58273 but with less race conditions!

**Comment by postamar** [comment]
I took the opportunity to clean up the commits a bit as well, I found the diffs were becoming a bit ugly, especially since this all warrants another look (evidently). As a result, the meat&potatoes of this change is all in the first commit. I used `sync.Once` to make `indexCache` concurrent, or so I hope.

**Review by thoszhang — COMMENTED** [review]
I only looked at the first commit. Doesn't this still initialize the cache lazily? I was hoping we wouldn't even need any sort of synchronization on the cache if we just force all `tabledesc.Immutable` initialization to go through some constructor, and initialize the cache in that function. Maybe I'm missing something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58678#-:-MQZuE1lE6__7SV3uSTU:bcn069v)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by postamar** [comment]
No, you're right, it's still lazy, just less so. I guess I got caught up in with this idea that designing structs so that their zero values are meaningful is idiomatic go. I just looked and I don't think there's anything wrong with building the cache eagerly in `MakeImmutable`,  I'll go ahead and see what that gives next week.

**Comment by postamar** [comment]
To the surprise of no one, getting rid of the laziness makes for better code. What was I thinking.

**Comment by postamar** [comment]
RFAL @lucy-zhang @ajwerner

**Comment by postamar** [comment]
Rebased on master to fix conflicts.

**Review by ajwerner — APPROVED** [review]
I'm assuming the later commits didn't change. :lgtm: for the first one, though I could have given it a more detailed read. 

> Reviewed 10 of 16 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58678#-:-MQrxLwHDMUuaLpyzP68:bu2w783)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

**Comment by postamar** [comment]
Thanks. In addition to the cursory visual checks I'd already done, I just checked to see how much the later commits changed with the following method, for each later commit `c`:
1. `git checkout $c`,
2. with `c_old` being the corresponding commit in https://github.com/cockroachdb/cockroach/pull/58273 , `git cherry-pick -n $c_old`,
4. look at `git diff` and see if there are any non-trivial differences in the conflicts. 
I didn't find any surprises. It's not perfect but I figure git is better at diffing things at scale than humans so this leaves me reasonably confident that the later commits are as they should be.

**Review by thoszhang — APPROVED** [review]
> Reviewed 7 of 16 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58678)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @miretskiy)

**Comment by postamar** [comment]
Thanks for the reviews everyone. I had to force-push again to address another conflict.

**Pull request merged**
