### PR TITLE
*,bazel: support `dev test pkg/{...}` expansion

### PR DESCRIPTION
**Pull request by irfansharif**
Discovered these while trying to flesh out https://github.com/cockroachdb/dev/pull/4.

We're doing a few things in this commit:
- Exclude the testdata dir under pkg/testutils from gazelle/bazel
  consideration
- Fix a few incorrect package resolutions (they were pointing to
  testdata paths previously).
- Break a circular dependency in the uuid package. This only happened in
  the test target (pkg/util/uuid -> pkg/testutils/skip -> pkg/util/uuid)
  so flew by undetected earlier.

Combining this with https://github.com/cockroachdb/dev/pull/4, now we
can use `go test` style "..." expansion in `dev`[*]:

  dev test pkg/util/...

[*]: Though failing tests that are broken under Bazel.

Release note: None

### CODE REVIEW

**Review by alan-mas — APPROVED** [review]

**Comment by alan-mas** [comment]
lgtm+ =)

**Comment by rickystewart** [comment]
> Break a circular dependency in the uuid package. This only happened in
> the test target (pkg/util/uuid -> pkg/testutils/skip -> pkg/util/uuid)
> so flew by undetected earlier.

I think I took care of this in a commit last week (probably at around the same time as you), so this can probably be removed from the msg?

**Comment by rickystewart** [comment]
whoops lmao

**Review by rickystewart — APPROVED** [review]

**Comment by irfansharif** [comment]
Done, TFTR!

bors r+

**Pull request merged**
