### PR TITLE
sql: deflake TestPerfLogging in event_log_test

### LINKED ISSUE #70649: sql: TestPerfLogging failed
sql.TestPerfLogging [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3489069&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3489069&tab=artifacts#/) on master @ [c438563d64d6cd6493a59d84e65e62d3f6060725](https://github.com/cockroachdb/cockroach/commits/c438563d64d6cd6493a59d84e65e62d3f6060725):

```
    event_log_test.go:703: INSERT INTO t(i) VALUES (7), (8), (9)
    event_log_test.go:732: {INFO 1632436734529629000 360317 util/log/event_log.go 32 {"Timestamp":1632436734529589325,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹7›), (‹8›), (‹9›)","Tag":"INSERT","User":"root","TxnID":"207c1bb1-8b22-498c-8a80-645397cca75e","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 32 true SQL_PERF 309 0 0}
    event_log_test.go:696: INSERT INTO t(i) VALUES (-1), (-2), (-3)
    event_log_test.go:703: UPDATE t SET i = i - 10 WHERE i < 0
    event_log_test.go:732: {INFO 1632436734617377000 360317 util/log/event_log.go 32 {"Timestamp":1632436734617327301,"EventType":"txn_rows_written_limit","Statement":"UPDATE ‹\"\"›.‹\"\"›.‹t› SET ‹i› = ‹i› - ‹10› WHERE ‹i› < ‹0›","Tag":"UPDATE","User":"root","TxnID":"12c8ef87-b730-4d29-9cf6-9134e0e1eea3","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 34 true SQL_PERF 313 0 0}
    event_log_test.go:696: BEGIN
    event_log_test.go:703: INSERT INTO t(i) VALUES (10); INSERT INTO t(i) VALUES (11), (12);
    event_log_test.go:732: {INFO 1632436734688660000 360317 util/log/event_log.go 32 {"Timestamp":1632436734688620077,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹11›), (‹12›)","Tag":"INSERT","User":"root","TxnID":"d5733a51-cd26-40c2-afb8-bdfec1ec3f77","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 36 true SQL_PERF 300 0 0}
    event_log_test.go:741: COMMIT
    event_log_test.go:696: SET transaction_rows_written_log = 1
    event_log_test.go:703: INSERT INTO t(i) VALUES (13), (14)
    event_log_test.go:732: {INFO 1632436734756904000 360317 util/log/event_log.go 32 {"Timestamp":1632436734756869807,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹13›), (‹14›)","Tag":"INSERT","User":"root","TxnID":"6df4c0e1-55a1-4443-928d-b7cde0f1d9cc","SessionID":"16a7948de5433df40000000000000001","NumRows":2} n1,client=‹127.0.0.1:59062›,hostssl,user=root 37 true SQL_PERF 300 0 0}
    event_log_test.go:741: RESET transaction_rows_written_log
    event_log_test.go:703: INSERT INTO t(i) VALUES (15), (16), (17), (18)
    event_log_test.go:732: {INFO 1632436734823760000 360317 util/log/event_log.go 32 {"Timestamp":1632436734823711396,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹15›), (‹16›), (‹17›), (‹18›)","Tag":"INSERT","User":"root","TxnID":"9daec8d0-7e2b-4b11-823a-92aa34ff9cfb","SessionID":"16a7948de5433df40000000000000001","NumRows":4} n1,client=‹127.0.0.1:59062›,hostssl,user=root 38 true SQL_PERF 324 0 0}
    event_log_test.go:696: INSERT INTO t(i) VALUES (-1)
    event_log_test.go:703: DELETE FROM t WHERE i < 0
    event_log_test.go:732: {INFO 1632436734910154000 360317 util/log/event_log.go 32 {"Timestamp":1632436734910121559,"EventType":"txn_rows_written_limit","Statement":"DELETE FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› < ‹0›","Tag":"DELETE","User":"root","TxnID":"aa0abc86-ad62-4452-8f31-1cfe449569ee","SessionID":"16a7948de5433df40000000000000001","NumRows":4} n1,client=‹127.0.0.1:59062›,hostssl,user=root 39 true SQL_PERF 285 0 0}
    event_log_test.go:703: UPSERT INTO t(i) VALUES (-2), (-3), (-4), (-5)
    event_log_test.go:732: {INFO 1632436734979130000 360317 util/log/event_log.go 32 {"Timestamp":1632436734979095104,"EventType":"txn_rows_written_limit","Statement":"UPSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹-2›), (‹-3›), (‹-4›), (‹-5›)","Tag":"INSERT","User":"root","TxnID":"745fc9a2-5fa4-462a-9396-b1c0db96ed98","SessionID":"16a7948de5433df40000000000000001","NumRows":4} n1,client=‹127.0.0.1:59062›,hostssl,user=root 40 true SQL_PERF 324 0 0}
    event_log_test.go:696: BEGIN
    event_log_test.go:703: INSERT INTO t(i) VALUES (15), (16), (17); INSERT INTO t(i) VALUES (18);
    event_log_test.go:732: {INFO 1632436735054625000 360317 util/log/event_log.go 32 {"Timestamp":1632436735054592707,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹15›), (‹16›), (‹17›)","Tag":"INSERT","User":"root","TxnID":"89d62ec4-ca41-4502-97c5-f47bec0d849d","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 41 true SQL_PERF 312 0 0}
    event_log_test.go:741: ROLLBACK
    event_log_test.go:696: SET transaction_rows_written_err = 1
    event_log_test.go:703: INSERT INTO t(i) VALUES (15), (16)
    event_log_test.go:741: RESET transaction_rows_written_err
    event_log_test.go:703: SELECT * FROM t WHERE i = 6
    event_log_test.go:703: SELECT * FROM t WHERE i IN (6, 7, 8)
    event_log_test.go:732: {INFO 1632436735264629000 360317 util/log/event_log.go 32 {"Timestamp":1632436735264594255,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›, ‹8›)","Tag":"SELECT","User":"root","TxnID":"0f5b8e48-e3cd-4fbd-b9ce-05366e52813f","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 42 true SQL_PERF 305 0 0}
    event_log_test.go:696: BEGIN
    event_log_test.go:703: SELECT * FROM t WHERE i = 6; SELECT * FROM t WHERE i = 7; SELECT * FROM t WHERE i = 8;
    event_log_test.go:732: {INFO 1632436735330923000 360317 util/log/event_log.go 32 {"Timestamp":1632436735330890619,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› = ‹8›","Tag":"SELECT","User":"root","TxnID":"17904896-81cc-45cf-95b7-142427bcd84e","SessionID":"16a7948de5433df40000000000000001","NumRows":3} n1,client=‹127.0.0.1:59062›,hostssl,user=root 43 true SQL_PERF 284 0 0}
    event_log_test.go:741: COMMIT
    event_log_test.go:696: SET transaction_rows_read_log = 1
    event_log_test.go:703: SELECT * FROM t WHERE i IN (6, 7)
    event_log_test.go:732: {INFO 1632436735394326000 360317 util/log/event_log.go 32 {"Timestamp":1632436735394292694,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›)","Tag":"SELECT","User":"root","TxnID":"b5dda6d8-d521-48f7-b576-689347ccf94a","SessionID":"16a7948de5433df40000000000000001","NumRows":2} n1,client=‹127.0.0.1:59062›,hostssl,user=root 44 true SQL_PERF 296 0 0}
    event_log_test.go:741: RESET transaction_rows_read_log
    event_log_test.go:703: SELECT * FROM t WHERE i IN (6, 7, 8, 9)
    event_log_test.go:732: {INFO 1632436735455034000 360317 util/log/event_log.go 32 {"Timestamp":1632436735455001756,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›, ‹8›, ‹9›)","Tag":"SELECT","User":"root","TxnID":"eb546bf7-9b73-40b5-a569-29adb1781f8f","SessionID":"16a7948de5433df40000000000000001","NumRows":4} n1,client=‹127.0.0.1:59062›,hostssl,user=root 45 true SQL_PERF 314 0 0}
    event_log_test.go:696: BEGIN
    event_log_test.go:703: SELECT * FROM t WHERE i IN (6, 7); SELECT * FROM t WHERE i IN (8, 9)
    event_log_test.go:732: {INFO 1632436735519075000 360317 util/log/event_log.go 32 {"Timestamp":1632436735519040381,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹8›, ‹9›)","Tag":"SELECT","User":"root","TxnID":"aa92ea09-0968-4e71-8ad1-8f4241949951","SessionID":"16a7948de5433df40000000000000001","NumRows":4} n1,client=‹127.0.0.1:59062›,hostssl,user=root 46 true SQL_PERF 296 0 0}
    event_log_test.go:741: ROLLBACK
    event_log_test.go:696: SET transaction_rows_read_err = 1
    event_log_test.go:703: SELECT * FROM t WHERE i = 6 OR i = 7
    event_log_test.go:725: 2 log messages for query ``SELECT * FROM t WHERE i = 6 OR i = 7`` matching ````, expected zero messages
    panic.go:632: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestPerfLogging606051429
--- FAIL: TestPerfLogging (11.28s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestPerfLogging PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries michae2
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPerfLogging.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by michae2**
Fixes: #70649

One of our testcases was checking for no SQL_PERF log events of any
kind, which is a bit too strict. Add a logRe so that we're specifically
checking for no txn_rows_read_limit messages.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: we will also want to backport this to 21.1 and 21.2.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70651#-:-MkK3-MV0WOq2xpZQER2:bgukwpo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/event_log_test.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70651#-MkK2sTf-LM7NiY0jMkz:-MkK2sTf-LM7NiY0jMl-:b-rxm6ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/c05ee2a84c6bc1b233dbdcaa2675d72a52b8cea1/pkg/sql/event_log_test.go#L486)):*
> ```Go
> 			query:       `INSERT INTO t(i) VALUES (15), (16)`,
> 			errRe:       `pq: txn has written 2 rows, which is above the limit: TxnID .* SessionID .*`,
> 			logRe:       ``,
> ```

Here is another one.

**Comment by michae2** [comment]
Hmm, I might have been too hasty about this. Here is the last bit of [the slow query log](https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Testrace/3489069:id/logTestPerfLogging606051429/sqltest-sql-slow.log):

```
I210923 22:38:55.054625 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 41 ={"Timestamp":1632436735054592707,"EventType":"txn_rows_written_limit","Statement":"INSERT INTO ‹\"\"›.‹\"\"›.‹t›(‹i›) VALUES (‹15›), (‹16›), (‹17›)","Tag":"INSERT","User":"root","TxnID":"89d62ec4-ca41-4502-97c5-f47bec0d849d","SessionID":"16a7948de5433df40000000000000001","NumRows":3}
I210923 22:38:55.264629 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 42 ={"Timestamp":1632436735264594255,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›, ‹8›)","Tag":"SELECT","User":"root","TxnID":"0f5b8e48-e3cd-4fbd-b9ce-05366e52813f","SessionID":"16a7948de5433df40000000000000001","NumRows":3}
I210923 22:38:55.330923 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 43 ={"Timestamp":1632436735330890619,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› = ‹8›","Tag":"SELECT","User":"root","TxnID":"17904896-81cc-45cf-95b7-142427bcd84e","SessionID":"16a7948de5433df40000000000000001","NumRows":3}
I210923 22:38:55.394326 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 44 ={"Timestamp":1632436735394292694,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›)","Tag":"SELECT","User":"root","TxnID":"b5dda6d8-d521-48f7-b576-689347ccf94a","SessionID":"16a7948de5433df40000000000000001","NumRows":2}
I210923 22:38:55.455034 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 45 ={"Timestamp":1632436735455001756,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹6›, ‹7›, ‹8›, ‹9›)","Tag":"SELECT","User":"root","TxnID":"eb546bf7-9b73-40b5-a569-29adb1781f8f","SessionID":"16a7948de5433df40000000000000001","NumRows":4}
I210923 22:38:55.519075 360317 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:59062›,hostssl,user=root] 46 ={"Timestamp":1632436735519040381,"EventType":"txn_rows_read_limit","Statement":"SELECT * FROM ‹\"\"›.‹\"\"›.‹t› WHERE ‹i› IN (‹8›, ‹9›)","Tag":"SELECT","User":"root","TxnID":"aa92ea09-0968-4e71-8ad1-8f4241949951","SessionID":"16a7948de5433df40000000000000001","NumRows":4}
```

Now I'm starting to wonder if the `SELECT * FROM t WHERE i IN (6, 7); SELECT * FROM t WHERE i IN (8, 9)` case immediately before is the interesting one.

**Comment by michae2** [comment]
I added a `logRe` for the other one, and put a little more detail in the `logRe` of all cases between those two. So hopefully this is specific enough not to flake any more, or to tell us more precisely which case is failing.

After `make stress` up to a few hundred runs, no failures, so I'll go ahead.

bors r=yuzefovich

**Comment by michae2** [comment]
Seems like a flake, I'm going to try again.

bors r+

**Pull request merged**
