### PR TITLE
build: update to go1.7rc5

### PR DESCRIPTION
**Pull request by tamird**
Also change chmod to only affect GOTOOLDIR, since not all of GOROOT
needs to be writable (GOROOT/pkg is mounted from the host).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8371)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8371#-:-KOeLgxghWCL9_BYgZKs:bnfp4nl)*

**Comment by bdarnell** [comment]
LGTM, but since AFAIK go 1.7 is scheduled for release today we may want to just wait until that's available.

**Comment by tamird** [comment]
I wasn't aware. OK.

**Comment by tamird** [comment]
Looks like we're headed for rc6
https://github.com/golang/go/issues/16590#issuecomment-237627455.

**Comment by bdarnell** [comment]
OK, let's go ahead and merge this then; we'll want the xgo changes for this week's beta.

**Pull request merged**
