### PR TITLE
bulkio: Drop support for `RECURRING NEVER` for scheduled backups.

### PR DESCRIPTION
**Pull request by miretskiy**
`RECURRING NEVER` doesn't make much sense for scheduled backups.
This clause is particularly confusing when combined with
`FULL BACKUP ALWAYS` clause.

Release Notes: None

### CODE REVIEW

**Comment by miretskiy** [comment]
friendly ping, @dt

**Comment by miretskiy** [comment]
friendly ping, @dt

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
hey bors, what gives?

bors r=dt

**Pull request merged**
