### PR TITLE
Use RegisterSystemConfigChannel in TestSystemConfigGossip

### LINKED ISSUE #3920: Failed tests (11584): TestSystemConfigGossip
The following test appears to have failed:

[#11584](https://circleci.com/gh/cockroachdb/cockroach/11584):

```
I0119 12:19:25.439421 742 kv/range_cache.go:189  adding descriptor: key=/Meta2/"\x93" desc=range_id:1 start_key:"" end_key:"\223" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
W0119 12:19:25.440865 742 rpc/send.go:198  Node.Batch: error reply: server/node.go:494: node 1 stopped
I0119 12:19:25.441372 742 client/db.go:485  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:494: node 1 stopped
E0119 12:19:25.441766 742 storage/queue.go:123  [split] range=3 [/Table/12-/Max): error: storage/split_queue.go:100: unable to split range=3 [/Table/12-/Max) at key "/Table/13/0": failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:494: node 1 stopped
I0119 12:19:25.444107 742 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestSystemConfigGossip (1.06s)
	server_test.go:566: mismatch: expected name:"foo" id:2 , got {Name:foo ID:1 Privileges:<nil>}
=== RUN   TestStatusLocalStacks
I0119 12:19:25.508942 742 rpc/clock_offset.go:153  monitoring cluster offset
I0119 12:19:25.537954 742 raft/raft.go:446  [group 1] 1 became follower at term 5
I0119 12:19:25.538668 742 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0119 12:19:25.539031 742 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0119 12:19:25.539372 742 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0119 12:19:25.539547 742 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0119 12:19:25.539905 742 raft/raft.go:487  [group 1] 1 became leader at term 6
I0119 12:19:25.543128 742 storage/replica_command.go:1214  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1453205966.542s
--
I0119 12:19:35.114486 742 client/db.go:485  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:494: node 1 stopped
W0119 12:19:35.114745 742 ts/db.go:96  error writing time series data: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:494: node 1 stopped
I0119 12:19:35.116841 742 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (1.85s)
	<autogenerated>:28: prior leak detected, leaktest disabled
FAIL
FAIL	github.com/cockroachdb/cockroach/server	31.783s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0119 12:19:25.007588 773 server/status/runtime.go:137  runtime stats: 11 goroutines, 3.04MiB active, 50000000.00cgo/sec, 544530.00/388950.00 %(u/s)time, 9051.40 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.00s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by vivekmenezes**
Might also fix #3920 by always picking up latest value of config.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3927)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/server_test.go, line 504 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8TtSFEbt7BTUUPTfa3:-K8TtSFEbt7BTUUPTfa4:-1813459318) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L504)):*
these `break`s are not necessary

---

*[server/server_test.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8TyDv4h8UkXXXRiFz6:-K8TvvW7epAUNqyA377y:1025357039) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L525)):*
this error message should include some debug information, perhaps `%s` of the config received?

---

*[server/server_test.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8Tvz7pIRVVItvMYiWC:-K8Tvz7pIRVVItvMYiWD:800137197) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L526)):*
is long enough? could we throw something else into gossip and wait for it to come out?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/server_test.go, line 504 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8TtSFEbt7BTUUPTfa3:-K8VEJcsq-9cqEQ2usjw:-1054325829) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L504)):*
removed

---

*[server/server_test.go, line 525 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8TyDv4h8UkXXXRiFz6:-K8VJkipTw6eJ-dF5S07:-9312800) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L525)):*
It now use a %v on the systemConfig which does log a lot.

---

*[server/server_test.go, line 526 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-K8Tvz7pIRVVItvMYiWC:-K8VJv0jBz7BOoNP1eNq:-998864248) ([raw file](https://github.com/cockroachdb/cockroach/blob/7019aeca6a3f04650019f82e534171314a7b69a2/server/server_test.go#L526)):*
It's testing if gossip is dormant. I know we care about new system configs being reported properly, but I actually don't know if we really care about the channel remaining dormant. I've increased the timeout to 50ms.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927)*

**Comment by tamird** [comment]
I'd feel more comfortable with this change going in if it definitely did or did not fix the mentioned test.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-:-K8uhMOZs6AdrvztTkkv:-1685954085)*

**Comment by vivekmenezes** [comment]
I'm unable to reproduce the failure on master without this change. This PR bring this test in line with how we register for system config updates. I think you're worried about this change  masking the breakage. Let me see what more I can do to reproduce it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3927#-:-K8zpt1vxod8vt3pYzwh:-208984249)*

**Comment by bdarnell** [comment]
LGTM, although I don't think it fixes #3920; see my comment there.

**Pull request closed without merging**
