### PR TITLE
opt: add exploration rules for min/max => limit 1 transform

### PR DESCRIPTION
**Pull request by andy-kimball**
Add new rules that work similarly to the existing ReplaceMaxWithLimit and
ReplaceMinWithLimit rules, except that they recognize the non-Scalar GroupBy
case. The new rules add an ordered LIMIT 1 to the input when it can be proven
that there is at most one group, and there exists a single min/max aggregate
function operating on that group. In that case, the GROUP BY can be entirely
replaced by a PROJECT, similar to this:

  SELECT min(k) FROM kw WHERE w = 5 GROUP BY w
  =>
  SELECT k FROM kw@w WHERE w = 5

Note that the Max and Min versions of this rule are not fully symmetric.
This is because NULL values sort first in CRDB. This can interfere with the
calculation of the Min function, because NULL values need to be ignored unless
the group contains only NULL values (in which case the function returns NULL).
Therefore, this rule only works when the MIN column is NOT NULL, as only in
that case is one input row always sufficient to calculate MIN.

Release note (sql change): Add optimization to scan over only 1 row when
finding the MIN/MAX of a single aggregate group, as long as the correct
index is present.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-:-Lx3CC7wCViNpE_PG4Ed:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx34v2sEdMKg-b7rDjq:-Lx34v2tCtCMR5cc6d5P:b-drsm89) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/memo/statistics_builder.go#L1485)):*
> ```Go
> 			s.RowCount = 1
> 		} else {
> 			// GroupBy returns 0 or 1 rows, depending on whether input has rows.
> ```

[nit] GroupBy with empty grouping columns returns 0 or 1 rows,....
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx37j4jDOpc15820t50:-Lx37j4jDOpc15820t51:b5ybqfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/rules/groupby.opt#L58)):*
> ```
> #   SELECT min(k) FROM kw WHERE w = 5 GROUP BY w
> #   =>
> #   SELECT k FROM kw@w WHERE w = 5
> ```

Should this be kw@wk?
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3860_9Na0JJ3RSA28:-Lx3860_9Na0JJ3RSA29:b4aqls1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/rules/groupby.opt#L61)):*
> ```
> #
> # This rule may result in a lower cost plan if the column min(x) is applied to
> # is indexed.
> ```

[nit] I'd just refer to k instead of x to use the previous example
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3Ay_v7XBelGQ_H2Lk:-Lx3Ay_v7XBelGQ_H2Ll:b-55k50z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L681)):*
> ```
> 
> # Basic min case (min function must take non-null column).
> opt
> ```

Do you want to add `expect=ReplaceMinWithLimit` etc here and below?
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3BJOt91m_bDogR21D:-Lx3BJOt91m_bDogR21E:b4r32jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L875)):*
> ```
> 
> # One of grouping columns is not constant, with min function.
> opt
> ```

expect-not?
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 969 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3BeBKDz-HUdxjnYNn:-Lx3BeBKDz-HUdxjnYNo:b4r32jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L969)):*
> ```
> # ReplaceMinWithLimit does not apply on multiple aggregations
> # on different columns
> opt
> ```

expect-not?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43547)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx34v2sEdMKg-b7rDjq:-Lx6xpJL43jvndbfFLYz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/memo/statistics_builder.go#L1485)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] GroupBy with empty grouping columns returns 0 or 1 rows,....
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx37j4jDOpc15820t50:-Lx6wgHi5hOo-BA3FX3k:b-kkstb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/rules/groupby.opt#L58)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be kw@wk?
</blockquote></details>

Switched to that, since it's more clear. Also, I forgot to add the `LIMIT 1`.
___
*[pkg/sql/opt/xform/rules/groupby.opt, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3860_9Na0JJ3RSA28:-Lx6wu-I0o2USjtek6uS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/rules/groupby.opt#L61)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd just refer to k instead of x to use the previous example
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3Ay_v7XBelGQ_H2Lk:-Lx6x8aL1atNH1YNLK7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L681)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you want to add `expect=ReplaceMinWithLimit` etc here and below?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3BJOt91m_bDogR21D:-Lx6xbv2-v917TpGZ4BH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L875)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

expect-not?
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/testdata/rules/groupby, line 969 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-Lx3BeBKDz-HUdxjnYNn:-Lx6xqK-1_2Y4HuD1-k4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85f3c8314689ff3218ae96c22b90aba77712bd2/pkg/sql/opt/xform/testdata/rules/groupby#L969)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

expect-not?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43547#-:-Ly545Pv0NqNdOVRPEe2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Pull request merged**
