### PR TITLE
scplan: break out stage building into scstage package and invert rule directions

### PR DESCRIPTION
**Pull request by postamar**
These 4 commits introduce a new scstage package. This was motivated by the more immediate goal of inverting dependency edge directions, to express them as precedence constraints instead of succession constraints.

### CODE REVIEW

**Comment by postamar** [comment]
This is best reviewed commit by commit. The first two are strict refactors, the third is tiny, and the fourth is dominated by test artifact noise. Ultimately, this PR doesn't really change anything substantial.

Next steps here would be to explore precedence rules with strict precedence rules, which force the nodes to be in different stages. I'm feeling uneasy about relying on the topological sort to ensure that operations are performed in the correct order, I'd rather generate a bunch of stages and collapse them together afterwards. Anyway, plenty of fertile ground to explore, as always.

**Review by ajwerner — COMMENTED** [review]
This is Good. One concern about a behavior change. Otherwise, :lgtm: 

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 13 of 14 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 17 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-:-MqoaPgY4xygaqEbFOA2:b3okw88)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scplan/opgen/op_gen.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoZ5K0DOz2E0P4BaAc:-MqoZ5K0DOz2E0P4BaAd:b-zgzzjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0037e285d7a90d8680703d2e61673ddfdbbe853/pkg/sql/schemachanger/scplan/opgen/op_gen.go#L46)):*
> ```Go
> 		edgesToAdd = edgesToAdd[:0]
> 		if err := t.iterateFunc(g.Database(), func(n *scpb.Node) error {
> 			status := n.Status
> ```

I recall this having something to do with edge cases involving nodes which were referenced by dependencies. I think this was vestigial. Thanks for cleaning it up. Cleanup passes from me around some of this code are overdue. 
___
*[pkg/sql/schemachanger/scplan/scstage/stage.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoX1--3yTX9JzY62fX:-MqoX1--3yTX9JzY62fY:b-9o1j86) ([raw file](https://github.com/cockroachdb/cockroach/blob/32ff362162b0d9910a535ccc42e07942c68e6a33/pkg/sql/schemachanger/scplan/scstage/stage.go#L27)):*
> ```Go
> // the stage, reflecting the fact that any set of ops can be thought of as a
> // transition from one state to another.
> type Stage struct {
> ```

I could see moving this to `scgraph`. Ultimately we'll want the visualization stuff to have awareness of this.
___
*[pkg/sql/schemachanger/scplan/scstage/stage.go, line 114 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoaL770f0Ft5hXqlNH:-MqoaL770f0Ft5hXqlNI:bi78syh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d57d081def19becc1959bdae9c2ac329b2c51e1/pkg/sql/schemachanger/scplan/scstage/stage.go#L114)):*
> ```Go
> 
> 	revertibleAllowed := true
> 	for _, stage := range stages {
> ```

Can we add a check that there is at most one `PreCommit` stage?
___
*[pkg/sql/schemachanger/testdata/alter_table_add_column, line 238 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoZynC9X3XfHGgXJUA:-MqoZynC9X3XfHGgXJUB:b-dt8hwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3206d89bf31852a9fa0de3b1cbe9b313b0ded0f3/pkg/sql/schemachanger/testdata/alter_table_add_column#L238)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> update progress of schema change job #1
> upsert descriptor #56
>   ...
>          version: 4
>        mutationId: 2
>   -    state: DELETE_AND_WRITE_ONLY
>   +    state: DELETE_ONLY
>      name: tbl
>      newSchemaChangeJobId: "1"
>   ...
>        time: {}
>      unexposedParentSchemaId: 55
>   -  version: "4"
>   +  version: "5"
> commit transaction #8
> begin transaction #9
> ## PostCommitPhase non-revertible stage 8 of 8 with 3 MutationType ops
> ```
</details>

why did this stage go away? It seems important

**Review by postamar — COMMENTED** [review]
Thanks for the review. I'll salvage as much as I can from this PR and rework the strict precedence + collapse.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-:-MqpfUlP-QaWANWLGjye:boxxnja)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scplan/scstage/stage.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoX1--3yTX9JzY62fX:-Mqpd7O_C0IN7b_lLm_1:bukpk3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/32ff362162b0d9910a535ccc42e07942c68e6a33/pkg/sql/schemachanger/scplan/scstage/stage.go#L27)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I could see moving this to `scgraph`. Ultimately we'll want the visualization stuff to have awareness of this.
</blockquote></details>

I agree in the longer term. 
___
*[pkg/sql/schemachanger/scplan/scstage/stage.go, line 114 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoaL770f0Ft5hXqlNH:-MqpdQez-0nz6g_0bCiu:b57xns) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d57d081def19becc1959bdae9c2ac329b2c51e1/pkg/sql/schemachanger/scplan/scstage/stage.go#L114)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we add a check that there is at most one `PreCommit` stage?
</blockquote></details>

Yes! Let's.
___
*[pkg/sql/schemachanger/testdata/alter_table_add_column, line 238 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/73674#-MqoZynC9X3XfHGgXJUA:-MqpdUXA4QW0Quj26KJb:bb8662y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3206d89bf31852a9fa0de3b1cbe9b313b0ded0f3/pkg/sql/schemachanger/testdata/alter_table_add_column#L238)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> update progress of schema change job #1
> upsert descriptor #56
>   ...
>          version: 4
>        mutationId: 2
>   -    state: DELETE_AND_WRITE_ONLY
>   +    state: DELETE_ONLY
>      name: tbl
>      newSchemaChangeJobId: "1"
>   ...
>        time: {}
>      unexposedParentSchemaId: 55
>   -  version: "4"
>   +  version: "5"
> commit transaction #8
> begin transaction #9
> ## PostCommitPhase non-revertible stage 8 of 8 with 3 MutationType ops
> ```
why did this stage go away? It seems important
</blockquote></details>

Oh, good catch. My changes basically violate the two version invariant, which is bad!

What's happening is that a bunch of stages got collapsed together when they shouldn't have. It seems that we were relying on the fact that each state transition was a separate edge and therefore (pre-this-PR at least) a separate stage.

In retrospect this strict-precedence change needs some adjusting. I'm not such a huge fan of violating it after collapsing the stages. In fact, knowing what I know now, I'd feel easier if the two-version invariant were enforced by the rules engine somehow. 
I'm thinking now that perhaps it might be best to separate precedence constraints from same-stage/different-stage constraints somehow. I'll go back to the drawing board.

Also this violation should have been caught by the stage validation checks.

**Comment by postamar** [comment]
I force-pushed this branch to keep only the safe and uncontroversial commits at the beginning of it, which I will bors as soon as CI gives a green light. The removed commits are still being reworked.

**Pull request merged**
