### PR TITLE
sql: add unbounded_parallel_scans session variable

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit introduces `unbounded_parallel_scans` session variable that
controls whether the scans (i.e. served by the TableReader DistSQL
processors) will be parallelized across ranges even if we cannot
guarantee an upper bound on the number of rows scanned. Currently, we
only parallelize the scan across ranges if
1. there are no hard nor soft limits (meaning that the query cannot have
the LIMIT clause)
2. we know during the planning that less than 10k rows will be scanned.

The first condition is needed in order to not scan too much data
unnecessarily and is not affected by the new session variable. The
rationale for the second condition is that all scanned rows will be
buffered in memory by a single node, and since we cannot use
BatchRequest's limits when we want cross-range parallelism (those limits
disable the parallelism), the total footprint of rows can be arbitrarily
large which could lead to OOMs of the nodes. Thus, we put this condition
in place: if we know that less than 10k rows will be returned, then we
take our chances and enable the parallelism.

However, these two conditions are contradictory in nature which results
in parallelizing scans rarely, which is especially detrimental in the
multi-region setup. The long term solution to this problem is expanding
the Streamer API to a) power the TableReaders, and b) to support LIMITs,
but in the short term this commit introduces a session variable that
effectively disables the second condition. This gives power to the users
to choose the parallelism at their own risk.

Addresses: #100496.

Epic: CRDB-25448

Release note (sql change): New session variable `unbounded_parallel_scans`
has been introduced which controls whether scans will be parallelized across
ranges in more cases. Note that using this feature can lead to increased
likelihood of OOMs, so it should be used with care (namely when you
expect that the scan should read "reasonable" number of rows - probably
less than 10k). Also note that queries with LIMITs aren't affected by
this variable - cross-range parallelism of scans continues to be
disabled for those.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSInXt5Doe5tbi7KV4e):*
Thoughts about the naming? Perhaps `unsafe_parallelize_scans` would be better? Or something else?

**Review by DrewKimball — COMMENTED** [review]
What do you think of making the setting a float instead, which would be the threshold for *estimated* row count under which we'd parallelize?

> Reviewed 1 of 1 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-:-NSIvHc29iDiJM5qdrRv:bq5ag0e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 1886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSIv26Y090DQdem8u-o:-NSIv26Y090DQdem8u-p:bek1l32) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/testdata/select#L1886)):*
> ```
>   table: b@b_c_key
>   spans: /!NULL-/2 /10/0
>   parallel
> ```

Is this case correct? Or is the comment just confusing?

**Review by yuzefovich — COMMENTED** [review]
I thought about that, but what I don't like about the float is that it makes it more confusing to the user as well as less predictable, like the user tunes some queries, picks the threshold to be low enough for all needed scans to be parallelized, and then a week later auto stats are collected and the new estimate exceeds the threshold - boom, we get back to the supposedly-too-slow sequential-scan latency. Thoughts? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-:-NSIwNzM6q5MIKwB-zzn:byf1z2v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 1886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSIv26Y090DQdem8u-o:-NSIvy6f2vc565Cdxcs4:bu2f4qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/testdata/select#L1886)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Is this case correct? Or is the comment just confusing?
</blockquote></details>

The comment is confusing - I meant to say that with default settings it's not parallelizable because we have a null in the start key, but with `parallelize_scans = true`, it is parallelizable.

My thinking behind the comments for such cases to indicate the reason for why the scan is not parallelizable with `parallelize_scans=false`. Do you have a suggestion for how to make this less confusing?

**Review by DrewKimball — APPROVED** [review]
>I thought about that, but what I don't like about the float is that it makes it more confusing to the user as well as less predictable, like the user tunes some queries, picks the threshold to be low enough for all needed scans to be parallelized, and then a week later auto stats are collected and the new estimate exceeds the threshold - boom, we get back to the supposedly-too-slow sequential-scan latency. Thoughts?

Yeah, I think that's reasonable justification to keep it as a bool. And I guess we intend to get around this problem using the streamer in the future anyway, so it's probably just not worth making things super configurable.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-:-NSJ-FgfCvg8YrE1IJ8R:b-eisvid)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSJ-gCSBRSvuFItqU7H:-NSJ-gCSBRSvuFItqU7I:b-7qis6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/relational.go#L696)):*
> ```Go
> 			// a sufficiently small upper bound on the number of rows scanned,
> 			// we still will parallelize this scan.
> 			parallelize = b.evalCtx.SessionData().ParallelizeScans
> ```

We're intentionally setting this even for the single-span single-row case despite it being a no-op, right? I think it's probably a good idea to avoid confusion, but just making sure we think it through.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 1886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSIv26Y090DQdem8u-o:-NSIzzo7AerjoWtlAUCB:b-itwrbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/testdata/select#L1886)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The comment is confusing - I meant to say that with default settings it's not parallelizable because we have a null in the start key, but with `parallelize_scans = true`, it is parallelizable.

My thinking behind the comments for such cases to indicate the reason for why the scan is not parallelizable with `parallelize_scans=false`. Do you have a suggestion for how to make this less confusing?
</blockquote></details>

Maybe just clarify that the NULL prevents us from putting a bound on the rowcount (that's why, right?).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSInXt5Doe5tbi7KV4e):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thoughts about the naming? Perhaps `unsafe_parallelize_scans` would be better? Or something else?
</blockquote></details>

Unsafe or experimental might be a good idea since we probably don't want anyone using this unless we explicitly recommend it.

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks for putting this together so quickly!

> Reviewed 1 of 1 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-:-NSM-ep_3IWDvPdfzoJZ:b-eejm4b)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`-- commits` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSInXt5Doe5tbi7KV4e):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Unsafe or experimental might be a good idea since we probably don't want anyone using this unless we explicitly recommend it.
</blockquote></details>

`unsafe_` might raise unwarranted paranoia. What about something like `limit_parallel_scan_memory_usage` that defaults to `true` (i.e. invert the condition) - to convey the risk with more specifics than just `unsafe`.

**Comment by cucaroach** [comment]
> `unsafe_` might raise unwarranted paranoia. What about something like `limit_parallel_scan_memory_usage` that defaults to `true` (i.e. invert the condition) - to convey the risk with more specifics than just `unsafe`.

I would be wary about sessions variables where the desired default isn't the Go default of false until https://github.com/cockroachdb/cockroach/issues/70888 is fixed.  Maybe "experimental_unbound_parallel_scans"?

**Comment by rytaft** [comment]
I like that. Just to bikeshed a little more, I'd tweak it to `experimental_unbounded_parallel_scans`

**Comment by yuzefovich** [comment]
I agree with Tommy that we should have the name that defaults to `false`. I also believe that we agreed to stay away from "experimental" in the name, plus there is nothing experimental about this particular setting - its behavior is well understood and could be well documented.

How about just `unbounded_parallel_scans`? "Unbounded" implies that a lot of data can be read implying (?) more memory usage.

**Comment by yuzefovich** [comment]
Or perhaps `unbounded_unlimited_parallel_scans`? This will seem a bit more scary, plus has the added benefit of indicating that queries with LIMITs aren't affected.

**Comment by fabiog1901** [comment]
My $0.02 - users typically don't pay too much attention at the cluster setting/ session variables names. They mostly look at the plain English description in the Docs. So I'd just make sure our docs are clear and easy to understand :-)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSInXt5Doe5tbi7KV4e):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`unsafe_` might raise unwarranted paranoia. What about something like `limit_parallel_scan_memory_usage` that defaults to `true` (i.e. invert the condition) - to convey the risk with more specifics than just `unsafe`.
</blockquote></details>

Alright, I settled on `unbounded_parallel_scans`.
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSJ-gCSBRSvuFItqU7H:-NSMkFwS6d88rM-Vb_6V:bj70s9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/relational.go#L696)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We're intentionally setting this even for the single-span single-row case despite it being a no-op, right? I think it's probably a good idea to avoid confusion, but just making sure we think it through.
</blockquote></details>

We shouldn't get here if we have single-span single-row case, right? In that scenario we should go into `if ok && maxResuls < ...` branch.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 1886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-NSIv26Y090DQdem8u-o:-NSMlcol7XnJifryC1Vp:b-ns5jwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2bfbe9acf27320391f7e557b9972d4a22436e9/pkg/sql/opt/exec/execbuilder/testdata/select#L1886)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Maybe just clarify that the NULL prevents us from putting a bound on the rowcount (that's why, right?).
</blockquote></details>

Yeah, I believe so, done.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100773#-:-NSRpxXVAqk9rwUaz5Cs:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

**Pull request merged**
