### PR TITLE
sql: support EXPLAIN(DEBUG) for UPDATE, INSERT, DELETE and JOIN.

### LINKED ISSUE #4944: sql: populate EXPLAIN of DELETE
currently:
```
 explain (debug) delete from deletes where k = 5;
 RowIdx | Key | Value | Disposition
--------+-----+-------+-------------
(0 rows)
```
Particularly since there may be fast or slow paths the query planner can take depending on the query (eg uses row values for filtering).

### LINKED ISSUE #4945: sql: populate EXPLAIN(DEBUG) of UPDATE
currently:
```
explain (debug) update deletes set a = 4 where k = 6;
 RowIdx | Key | Value | Disposition
--------+-----+-------+-------------
(0 rows)
```

### PR DESCRIPTION
**Pull request by knz**
Note: when EXPLAIN(DEBUG) is used, the table data is not modified. The DebugValues() only report values that were read.

Fixes #4944.
Fixes #4945.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7606)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Note that Github doesn't understand the "Fixes #foo, #bar."  syntax; you'll need to write:
> Fixes #foo.
> Fixes #bar.

instead

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/delete.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg40IBqqWzpyPkMDQm:-KLg40ICcQaaIhCVGR1u:1436543577) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/delete.go#L112)):*
> ```Go
> 	sel := d.run.rows.(*selectTopNode).source.(*selectNode)
> 	if scan, ok := sel.source.plan.(*scanNode); ok &&
> 		d.run.explain != explainDebug && canDeleteWithoutScan(d.n, scan, &d.tw) {
> ```

can you add a comment here? why don't you need this on the non-fastpath case?

---

*[sql/table_join.go, line 595 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg3woarclLCyH156O0:-KLg3woarclLCyH156O1:104491795) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/table_join.go#L595)):*
> ```Go
> 	}
> 
> 	// Load all the rows from the right side in memory.
> ```

move inside the `if`?

---

*[sql/table_join.go, line 657 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg3jE-c0RYCCIPNNzT:-KLg3jE-c0RYCCIPNNzU:-1280936503) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/table_join.go#L657)):*
> ```Go
> // Next implements the planNode interface.
> func (n *joinNode) Next() (bool, error) {
> ```

remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-:-KLg4ITJSij0msW-Af4b:1162482157)*

**Comment by tamird** [comment]
Oh, you just have the same issue twice; remove one :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-:-KLg4eXsOnZ4sLUmpCQz:1002490995)*

**Comment by knz** [comment]
There were actually 2 issues.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/delete.go, line 112 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg40IBqqWzpyPkMDQm:-KLg6lFIcc874fuhcti8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/delete.go#L112)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you add a comment here? why don't you need this on the non-fastpath case?
</details>
Done.

---

*[sql/table_join.go, line 595 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg3woarclLCyH156O0:-KLg6qcUykteEFe6mA7A:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/table_join.go#L595)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> move inside the `if`?
</details>
Done.

---

*[sql/table_join.go, line 657 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-KLg3jE-c0RYCCIPNNzT:-KLg6tFlnMj-AlOBtxq8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1102f2019cc626412ee84ecc508f35f0bb98f207/sql/table_join.go#L657)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606#-:-KLg6SQ4OD0-oloLD6Xn:-1421438785)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7606)*

**Pull request merged**
