### PR TITLE
storage: fix the Pebble MVCCValueMerger to be consistent with the

### LINKED ISSUE #45546: roachtest: engine/switch/nodes=3 failed
[(roachtest).engine/switch/nodes=3 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1775192&tab=buildLog) on [master@3e2334ded18d2f18c08f2f912be085df563ca6ff](https://github.com/cockroachdb/cockroach/commits/3e2334ded18d2f18c08f2f912be085df563ca6ff):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/engine/switch/nodes=3/run_1
	cluster.go:2368,engine_switch.go:126,engine_switch.go:140,test_runner.go:741: error with attached stack trace:
		    main.(*monitor).WaitE
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2356
		    main.(*monitor).Wait
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2364
		    main.registerEngineSwitch.func1
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:126
		    main.registerEngineSwitch.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/engine_switch.go:140
		    main.(*testRunner).runTest.func2
		    	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:741
		    runtime.goexit
		    	/usr/local/go/src/runtime/asm_amd64.s:1357
		  - monitor failure:
		  - unexpected node event: 1: dead

	cluster.go:1410,context.go:135,cluster.go:1399,test_runner.go:778: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1775192-1582963470-12-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 1: dead
		2: 4471
		4: skipped
		3: 4490
		Error:  1: dead

```

<details><summary>More</summary><p>

Artifacts: [/engine/switch/nodes=3](https://teamcity.cockroachdb.com/viewLog.html?buildId=1775192&tab=artifacts#/engine/switch/nodes=3)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aengine%2Fswitch%2Fnodes%3D3.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by sumeerbhola**
RocksDB equivalent by preserving the oldest MVCCMetadata.MergeTimestamp

Fixes #45546

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
Nice find! Glad the tests are finding these issues which are real, but also not something deep with Pebble.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45736#-:-M1dwqb71a-iZKZGf1DC:bdxetpg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/pebble_merge.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45736#-M1dwWYH3WtAxCPFzGay:-M1dwWYH3WtAxCPFzGaz:b-jl1wnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/55512d0e80a6eb73336476a0203ad756ccd9fe95/pkg/storage/pebble_merge.go#L173)):*
> ```Go
> 	timeSeriesOps []roachpb.InternalTimeSeriesData
> 	rawByteOps    [][]byte
> 	ts            []hlc.LegacyTimestamp
> ```

Perhaps rename this to `mergeTS`.

Is there a strong reason to maintain a slice here? Or could we maintain a single value for the oldest merge timestamp seen? I haven't fully paged this code back into memory, so feel free to leave as-is.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45736#-:-M1f3QSIDJjqaVxFSacA:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

___
*[pkg/storage/pebble_merge.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45736#-M1dwWYH3WtAxCPFzGay:-M1f2Wyh6TjauJkTKqRd:b-wrct3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/55512d0e80a6eb73336476a0203ad756ccd9fe95/pkg/storage/pebble_merge.go#L173)):*
> Perhaps rename this to mergeTS.
> Is there a strong reason to maintain a slice here? Or could we maintain a single value for the oldest merge timestamp seen? I haven't fully paged this code back into memory, so feel free to leave as-is.

Renamed to `oldestMergeTS` and now keeping only one value.

**Comment by sumeerbhola** [comment]
Failure seems unrelated https://teamcity.cockroachdb.com/viewLog.html?buildId=1788846&buildTypeId=Cockroach_UnitTests

bors r+

**Pull request merged**
