### PR TITLE
gossip: create SystemConfigDeltaFilter, use in SchemaChangeManager and LeaseManager

### PR DESCRIPTION
**Pull request by nvb**
SystemConfigDeltaFilter keeps track of SystemConfig values so that unmodified
values can be filtered out from a SystemConfig update. This can prevent
repeatedly unmarshaling and processing the same SystemConfig values.

The change then uses the newly introduces `SystemConfigDeltaFilter` in the
gossip workers for the `SchemaChangeManager` and the `LeaseManager`.

This is one of the proposed improvements from https://github.com/cockroachdb/cockroach/issues/20753#issuecomment-357371903.

Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/gossip/util.go, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L3-HsdRoMLPkunG-ty5:-L3-HsdRoMLPkunG-ty6:bcgmpg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa7d403bcc2f455612657568ee806b20e56a5359/pkg/gossip/util.go#L74)):*
> ```Go
> 		prevVal, ok := df.hashes[keyHash]
> 		if !ok || !bytes.Equal(kv.Value.RawBytes, prevVal.kv.Value.RawBytes) {
> 			// The key is new or the value changed.
> ```

Or it's a false positive. CRC32 is not large enough to avoid false positives. 

This construct also allows for false negatives, if there are two keys that collide that both have the same value. To avoid that, we should include the key in `hashVal` too. But if we're doing that, we might as well avoid all the manual hashing and just make it a map from key to value (letting the `map` type handle collisions for us). 

---

*[pkg/gossip/util.go, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L3-M4qGOluPNlHmUUNO:-L3-M4qGOluPNlHmUUNP:b-n05z6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa7d403bcc2f455612657568ee806b20e56a5359/pkg/gossip/util.go#L84)):*
> ```Go
> 	}
> 
> 	// Delete the kvs that no longer exist in the system config from the map.
> ```

We're doing an assignment to the map for every new value, so why not just build up a new map and swap them at the end instead of updating the existing map and then deleting from it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473)*

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/issues/7335 

@nvanbenschoten any interest on working on changing the gossiping to just gossip the id and version? That's a bigger change.

**Comment by nvanbenschoten** [comment]
@vivekmenezes: #7335 certainly seems like a change we're going to want to make in the future but it's a fairly involved change that will need a migration story. The small change proposed in this PR is much more straightforward and still demonstrates a big improvement in https://github.com/cockroachdb/cockroach/issues/20753#issuecomment-357371903.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/gossip/util.go, line 74 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L3-HsdRoMLPkunG-ty5:-L30K8v72Daxwg0iQXBe:b-hy7n8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa7d403bcc2f455612657568ee806b20e56a5359/pkg/gossip/util.go#L74)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Or it's a false positive. CRC32 is not large enough to avoid false positives. 

This construct also allows for false negatives, if there are two keys that collide that both have the same value. To avoid that, we should include the key in `hashVal` too. But if we're doing that, we might as well avoid all the manual hashing and just make it a map from key to value (letting the `map` type handle collisions for us). 
</blockquote></details>

Done. I was able to speed up `ForModified` with a few subtle changes that allow us to avoid allocating for all key and values in the map except new additions during each iteration.

```
name                       time/op
SystemConfigDeltaFilter-4   179µs ± 2%

name                       alloc/op
SystemConfigDeltaFilter-4  1.10kB ± 0%

name                       allocs/op
SystemConfigDeltaFilter-4    40.0 ± 0%
```

---

*[pkg/gossip/util.go, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L3-M4qGOluPNlHmUUNO:-L30QxvP2yPM7ik4V3ha:baaa45h) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa7d403bcc2f455612657568ee806b20e56a5359/pkg/gossip/util.go#L84)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We're doing an assignment to the map for every new value, so why not just build up a new map and swap them at the end instead of updating the existing map and then deleting from it?
</blockquote></details>

That's how I had originally written this, but benchmarks showed that this was a lot faster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-:-L30RGVEL4JP2vgcR89h:bhj40th)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/util.go, line 1 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L30swd7xejKKcNlrKWL:-L30swd7xejKKcNlrKWM:b67g1yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9774afd637558f2485bc75ae691e14387b3b0ae/pkg/gossip/util.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

`s/2017/2018/g`

---

*[pkg/gossip/util.go, line 76 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L30uNsdfOQPlFrSio5b:-L30uNsdfOQPlFrSio5c:bo8kr2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa8f900101ae0ec400746c3484ba571f549912d/pkg/gossip/util.go#L76)):*
> ```Go
> 		if ok {
> 			// No allocations.
> 			*df.lastVals[keyStr] = newVal
> ```

Isn't this `*prevVal = newVal`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-:-L30vOdwqngYz_U7i3mD:bnfp4nl)*

**Review by vivekmenezes — APPROVED** [review]
Nice!

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/gossip/util.go, line 1 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L30swd7xejKKcNlrKWL:-L31XajT073au-mycCBD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9774afd637558f2485bc75ae691e14387b3b0ae/pkg/gossip/util.go#L1)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/2017/2018/g`
</blockquote></details>

Done.

---

*[pkg/gossip/util.go, line 76 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L30uNsdfOQPlFrSio5b:-L31XcTBEnRb2lmToJ4-:bwh3spp) ([raw file](https://github.com/cockroachdb/cockroach/blob/faa8f900101ae0ec400746c3484ba571f549912d/pkg/gossip/util.go#L76)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Isn't this `*prevVal = newVal`?
</blockquote></details>

Done. Thanks for the 10% speedup!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/util.go, line 32 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L32gfcLJ-omofAdNpwj:-L32gfcLJ-omofAdNpwk:b-3bggtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae12b6ddfc7a1c72f99744ff8cfe128aad0de8fc/pkg/gossip/util.go#L32)):*
> ```Go
> type SystemConfigDeltaFilter struct {
> 	keyPrefix roachpb.Key
> 	lastVals  map[string]*filterVal
> ```

An alternative to using a `map` here is to use the fact that the system config values are sorted. This is required by `SystemConfig.GetIndex` and `SystemConfig.Equal`. That means you're trying to find the delta of two sorted sets which is a scan over both sets. That could save some allocations and be generally simpler than the map-based approach (no need for the `epoch`). Or maybe not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/util.go, line 32 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473#-L32gfcLJ-omofAdNpwj:-L3L1axEzoLIgfHTX4ns:b-ittrhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae12b6ddfc7a1c72f99744ff8cfe128aad0de8fc/pkg/gossip/util.go#L32)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

An alternative to using a `map` here is to use the fact that the system config values are sorted. This is required by `SystemConfig.GetIndex` and `SystemConfig.Equal`. That means you're trying to find the delta of two sorted sets which is a scan over both sets. That could save some allocations and be generally simpler than the map-based approach (no need for the `epoch`). Or maybe not. 
</blockquote></details>

I wasn't aware that we required the `SystemConfig` keys to always being sorted and didn't want to depend on that here if it was just an implementation detail. Since it sounds like we can rely on that precondition, your proposed approach is better. I opened #21610 to make the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21473)*

**Pull request merged**
