### PR TITLE
kvcoord: fix t.Fatal() on goroutines

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
`require.NoError` works on non-main goroutines. Maybe we should just switch to that. `panics` can also be swallowed.

**Comment by petermattis** [comment]
> require.NoError works on non-main goroutines. Maybe we should just switch to that. panics can also be swallowed.

`require.NoError` calls `testing.FailNow` which I thought was the bit that was verboten on non-main goroutines. `assert.NoError` works, though.

**Comment by andreimatei** [comment]
well `require.NoError()` also calls `assert.NoError()` - and afterwards it'll kill the goroutine with `t.FailNow()`. Killing goroutines other than the test's main one can easily cause major confusion, that's why I went with the panic. Or not killing the goroutine can easily lead to an NPE... But I'll look again at the particular cases here.

Of course the best thing to do is bring the errors to the main goroutine somehow, but I was lazy.

**Review by nvb — COMMENTED** [review]
Hm yeah, I guess I was wrong about that. I thought I've seen it work, but I don't see why it would now. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48457#-:-M6f9XohBPWzySrJ4Q5C:blu0ygx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
yeah... I'll stay with the `panic`.
The alternative is `t.Error()/assert.Foo()` followed by a `return nil, nil,...` The latter is ugly, and also likely leads to crashes because of those unexpected nils.
Isn't it silly that the go test runner has no way of recovering from panics on all goroutines?

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48457#-:-M6l4g5E8tzLmS4gkq-u:b-hwhiih)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
