### PR TITLE
sql: deflake TestSerialNormalizationWithUniqueUnorderedID

### LINKED ISSUE #102749: sql/sem/builtins: TestSerialNormalizationWithUniqueUnorderedID failed
sql/sem/builtins.TestSerialNormalizationWithUniqueUnorderedID [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9923301?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9923301?buildTab=artifacts#/) on release-23.1.0 @ [5efa6ff20f56d2ce8111b710190d1b378adb26d9](https://github.com/cockroachdb/cockroach/commits/5efa6ff20f56d2ce8111b710190d1b378adb26d9):

```
I230503 17:17:03.904804 1086209 jobs/registry.go:616  [T1,n1] 178  active version is 23.1
I230503 17:17:03.956653 1086209 upgrade/upgrademanager/manager.go:742  [T1,n1] 179  running Upgrade to 22.2-102: "create sql activity updater job"
I230503 17:17:03.956842 1506293 jobs/adopt.go:261  [T1,n1] 180  job 862007537850777601: resuming execution
I230503 17:17:04.029029 1508295 jobs/registry.go:1584  [T1,n1] 181  MIGRATION job 862007537850777601: stepping through state running
I230503 17:17:04.123997 1508295 jobs/registry.go:1584  [T1,n1] 182  MIGRATION job 862007537850777601: stepping through state succeeded
I230503 17:17:04.266847 1086209 jobs/wait.go:145  [T1,n1] 183  waited for 1 [862007537850777601] queued jobs to complete 310.036295ms
I230503 17:17:04.266958 1086209 server/server_sql.go:1615  [T1,n1] 184  done ensuring all necessary startup migrations have run
I230503 17:17:04.269151 1523192 jobs/job_scheduler.go:407  [T1,n1] 185  waiting 4m0s before scheduled jobs daemon start
I230503 17:17:04.272907 1523869 kv/kvclient/rangefeed/rangefeedcache/watcher.go:335  [T1,n1] 186  tenant-settings-watcher: established range feed cache
I230503 17:17:04.276268 1524317 kv/kvclient/rangefeed/rangefeedcache/watcher.go:335  [T1,n1] 187  tenant-capability-watcher: established range feed cache
I230503 17:17:04.300659 1524317 multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go:149  [T1,n1] 188  received results of a full table scan for tenant capabilities
I230503 17:17:04.311029 1523219 server/auto_upgrade.go:78  [T1,n1] 189  no need to upgrade, cluster already at the newest version
I230503 17:17:04.327388 1523202 sql/syntheticprivilegecache/cache.go:199  [T1,n1] 190  warmed privileges for virtual tables in 58.022916ms
I230503 17:17:04.355716 1095319 3@pebble/event.go:734  [n1,s1,pebble] 191  [JOB 7] WAL created 000006
I230503 17:17:04.359520 1086209 1@server/server_sql.go:1733  [T1,n1] 192  serving sql connections
I230503 17:17:04.413855 1532844 5@util/log/event_log.go:32  [T1,n1,client=127.0.0.1:43528,user=root] 193 ={"Timestamp":1683134224368122839,"EventType":"create_database","Statement":"CREATE DATABASE t","Tag":"CREATE DATABASE","User":"root","DescriptorID":104,"DatabaseName":"t"}
I230503 17:17:04.414032 1532844 5@util/log/event_log.go:32  [T1,n1,client=127.0.0.1:43528,user=root] 194 ={"Timestamp":1683134224368122839,"EventType":"create_table","Statement":"CREATE TABLE t.public.t (i INT8 NOT NULL PRIMARY KEY DEFAULT unordered_unique_rowid(), j INT8)","Tag":"CREATE TABLE","User":"root","DescriptorID":106,"TableName":"t.public.t"}
I230503 17:17:04.861054 1095716 3@pebble/event.go:734  [n1,s1,pebble] 195  [JOB 8] WAL created 000007
I230503 17:17:05.331450 1095619 3@pebble/event.go:734  [n1,s1,pebble] 196  [JOB 9] WAL created 000008
I230503 17:17:05.579126 1633044 13@kv/kvserver/replicate_queue.go:839  [T1,n1,replicate,s1,r30/1:/Table/2{8-9}] 197  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230503 17:17:05.580281 1633704 13@kv/kvserver/replicate_queue.go:839  [T1,n1,replicate,s1,r30/1:/Table/2{8-9}] 198  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
I230503 17:17:06.582793 1715058 13@kv/kvserver/replicate_queue.go:839  [T1,n1,replicate,s1,r2/1:/System/NodeLiveness{-Max}] 199  error processing replica: 0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster
    builtins_test.go:159: Key counts in each split range
    builtins_test.go:161: range 0: 1172
    builtins_test.go:161: range 1: 1186
    builtins_test.go:161: range 2: 1172
    builtins_test.go:161: range 3: 1169
    builtins_test.go:161: range 4: 1352
    builtins_test.go:161: range 5: 1281
    builtins_test.go:161: range 6: 1324
    builtins_test.go:161: range 7: 1344
    builtins_test.go:176: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins_test.go:176
        	Error:      	"38.80159999999995" is not less than "35.2585"
        	Test:       	TestSerialNormalizationWithUniqueUnorderedID
        	Messages:   	chiSquared value of 38.801600 must be less than criticalVal 35.258500 to guarantee distribution is relatively uniform
W230503 17:17:06.809674 1706034 kv/kvserver/intentresolver/intent_resolver.go:826  [-] 200  failed to gc transaction record: could not GC completed transaction anchored at /Table/106/1/1080464494111752193/0: node unavailable; try another peer
I230503 17:17:06.810826 1203835 rpc/context.go:2302  [T1,n1,rnode=1,raddr=127.0.0.1:43041,class=default,rpc] 201  connection heartbeat loop ended with err: <nil>
W230503 17:17:06.810728 1107332 sql/sqlliveness/slinstance/slinstance.go:334  [T1,n1] 202  exiting heartbeat loop
I230503 17:17:06.811478 1113396 sql/stats/automatic_stats.go:550  [T1,n1] 203  quiescing auto stats refresher
W230503 17:17:06.811583 1107332 sql/sqlliveness/slinstance/slinstance.go:321  [T1,n1] 204  exiting heartbeat loop with error: node unavailable; try another peer
I230503 17:17:06.811653 1145491 jobs/registry.go:1584  [T1,n1] 205  AUTO SPAN CONFIG RECONCILIATION job 862007521056718849: stepping through state succeeded
E230503 17:17:06.811684 1107332 server/server_sql.go:507  [T1,n1] 206  failed to run update of instance with new session ID: node unavailable; try another peer
I230503 17:17:06.812217 1092472 server/start_listen.go:103  [T1,n1] 208  server shutting down: instructing cmux to stop accepting
E230503 17:17:06.812060 1145491 jobs/registry.go:989  [T1,n1] 207  error getting live session: node unavailable; try another peer
W230503 17:17:06.823493 1454560 jobs/adopt.go:518  [T1,n1] 209  could not clear job claim: clear-job-claim: failed to send RPC: sending to all replicas failed; last error: ba: Scan [/Table/15/1/102,/Table/15/1/103), [txn: 62891975], [can-forward-ts] RPC error: node unavailable; try another peer
I230503 17:17:06.826323 1086209 server/server_controller_orchestration.go:263  [T1,n1] 210  server controller shutting down ungracefully
I230503 17:17:06.826393 1086209 server/server_controller_orchestration.go:274  [T1,n1] 211  waiting for tenant servers to report stopped
W230503 17:17:06.827085 1086209 server/server_sql.go:1693  [T1,n1] 212  server shutdown without a prior graceful drain
--- FAIL: TestSerialNormalizationWithUniqueUnorderedID (8.47s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #101921 sql/sem/builtins: TestSerialNormalizationWithUniqueUnorderedID failed [C-test-failure O-robot branch-release-23.1]
</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSerialNormalizationWithUniqueUnorderedID.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-27632

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #102749

This test has random input so retry failures to reduce chances of flaking.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/sem/builtins/builtins_test.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103040#-NVAInbe2kzFYdF6MzXZ:-NVAInbe2kzFYdF6MzX_:b-ncm71m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfe21dd5c571a4b45f021c442ec68604b7c3347/pkg/sql/sem/builtins/builtins_test.go#L190)):*
> ```Go
> 	// This test can flake when the random data is not distributed evenly so only
> 	// require it pass once.
> 	const maxAttempts = 2
> ```

nit: you could use `retry.WithMaxAttempts()` here, (it can accept the `runTest` function as a parameter)

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins_test.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103040#-NVAInbe2kzFYdF6MzXZ:-NVAjU2_2Hc7t5ZGrmxh:bk4hbv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfe21dd5c571a4b45f021c442ec68604b7c3347/pkg/sql/sem/builtins/builtins_test.go#L190)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: you could use `retry.WithMaxAttempts()` here, (it can accept the `runTest` function as a parameter)
</blockquote></details>

Thanks I was looking for that.

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
