### PR TITLE
pgwire: also support cancel under TLS

### PR DESCRIPTION
**Pull request by knz**
The pg protocol spec says that cancel messages should be sent
unencrypted, prior to authentication and the TLS handshake.

We've seen a report of a user seeing this after TLS in their logs
though. See https://github.com/cockroachlabs/support/issues/600

So this patch extends the code to handle both situations.

Release note (bug fix): CockroachDB now handles PostgreSQL "cancel"
messages on TLS connections in the same way as when they are sent
without TLS: the connection is closed, but no action takes place. No
error is logged. As a reminder, PostgreSQL "cancel" messages are still
unsupported in CockroachDB and client should still use CANCEL QUERY
instead.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
I think closing a connection when the client opened it just to send a cancel message (so, in the per-TLS case) is make sense (and regardless of what I think, it is mandated by the docs), but is it also fine in the post-TLS case? Are we doing anybody a favor by closing a connection that was being used by other stuff, instead of just ignoring the message? Is that what pg does?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54618#-:-MHlgnpt-dykIWgNqM4y:b-bxkjk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

**Comment by knz** [comment]
> Is that what pg does?

Yes: the pgwire protocol does not even support a response for a cancel request, and specifies the conn is closed immediately after the query is cancelled.

**Comment by andreimatei** [comment]
LGTM assuming you've actually tested pg.

**Comment by knz** [comment]
I can't really test pg since `psql` nor lib/pq does never do this. The only thing I have is the doc...

**Comment by andreimatei** [comment]
Well but that's what I'm saying - the doc only talks about cancel messages sent on brand new connections, not on existing connections. Closing a connection that was opened for this specific purpose is one thing, closing an arbitrary connection is another in my opinion.
Unless we know that pg behaves differently, my preference is to just ignore the message when it comes on an established connection. Which ignoring, btw, is what the protocol tells you to do when the pid in the message is not recognized, so that makes me feel even better about ignoring it.

I think you can test pg with the data-driven pgwire tests that we have, where you can control exactly what messages get sent. I might be wrong...

**Comment by knz** [comment]
> Well but that's what I'm saying - the doc only talks about cancel messages sent on brand new connections, not on existing connections. 

You might be misreading my diff? The new condition I added is also on the code path for brand new connections, before authn happens. Does this change your view?

**Review by andreimatei — COMMENTED** [review]
What new condition? I see that you've extracted a helper function, but otherwise did you change anything about the handling of the cancel message on brand new conns?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54618#-:-MHlsNaGD7pb1eI_TGFB:bcvq0r7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by knz** [comment]
See the green part at the bottom right here:
image

**Review by andreimatei — COMMENTED** [review]
Rapahel just explained to me that this patch changes the existing behavior a lot less than I thought - it only applies in the initial version-negotiation phase of a conn.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54618#-:-MHmAwyFAeOeUA7UVv-M:b32oom)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by knz** [comment]
thanks

bors r=andreimatei

**Pull request merged**
