### PR TITLE
allocator: prioritize non-voter promotion to satisfy voter constraints

### LINKED ISSUE #98020: ccl/multiregionccl: TestMultiRegionDataDriven failed
ccl/multiregionccl.TestMultiRegionDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/8924823?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/8924823?buildTab=artifacts#/) on master @ [fcea283ebca17a6d923c5d4b0401697438b77dbd](https://github.com/cockroachdb/cockroach/commits/fcea283ebca17a6d923c5d4b0401697438b77dbd):

```
=== RUN   TestMultiRegionDataDriven
I230304 07:16:59.107940 1 (gostd) rand.go:199  [T1] 1  random seed: 4267267524760381632
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/a5ee0b0d8f7b79a0b4e56a682326700f/logTestMultiRegionDataDriven2123913141
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestMultiRegionDataDriven
    datadriven_test.go:428: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/a5ee0b0d8f7b79a0b4e56a682326700f/logTestMultiRegionDataDriven2123913141
--- FAIL: TestMultiRegionDataDriven (203.33s)
=== RUN   TestMultiRegionDataDriven/secondary_region
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:1:
        new-cluster [1 args]
        <no input to command>
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:4:
        exec-sql [1 args]
        SET CLUSTER SETTING server.time_until_store_dead = '25s';
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:8:
        exec-sql [1 args]
        CREATE DATABASE db PRIMARY REGION "us-west-1" REGIONS "us-central-1", "eu-west-1" SECONDARY REGION "us-east-1";
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:12:
        exec-sql [1 args]
        ALTER DATABASE db SURVIVE REGION FAILURE;
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:16:
        exec-sql [1 args]
        CREATE TABLE db.rbt(k INT PRIMARY KEY, v INT) LOCALITY REGIONAL BY TABLE IN "us-west-1";
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:20:
        exec-sql [1 args]
        INSERT INTO db.rbt VALUES (1, 1), (2,2)
        ----
    datadriven_test.go:129: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/secondary_region:25:
         
        expected:
        
        found:
        expected leaseholder 2 but got 3
    --- FAIL: TestMultiRegionDataDriven/secondary_region (131.32s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #92235 ccl/multiregionccl: TestMultiRegionDataDriven failed [C-test-failure O-robot T-sql-sessions branch-release-22.2 skipped-test]
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMultiRegionDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #106559: allocator: voter constraint never satisfied when there are a correct number of replicas and all existing replicas are necessary
**Describe the problem**

When there are the correct number of voters/non-voters and all existing replicas are necessarily satisfying some constraint, the allocator may not satisfy any remaining constraints - even though it should.

Consider the example from #98020

Node Localities
```
# region -> node_id
eu-west-1
  └── [8 9 10]
us-central-1
  └── [5 6 7]
us-east-1
  └── [1 2]
us-west-1
  └── [3 4]
```

Span config:
```
num_replicas=6 
num_voters=5 
constraints={'+region=eu-west-1':1,'+region=us-central-1':1,'+region=us-east-1':1,'+region=us-west-1':1} 
voter_constraints={'+region=us-west-1':2,'+region=us-east-1':2}
```

Existing replicas:

```
voters=[n1,n2,n4,n5,n8]
non_voters=[n3]
```

There are the correct number of voters/replicas. All existing replicas are necessary (from allocators perspective) to satisfy the existing constraints—including the non-voter on n3.

n3 should be promoted to a voter, then either n5 (us-central-1) or n8 (eu-west-1) should be demoted to a non-voter. i.e., a rebalance with a promotion and demotion.

However this will never occur, as we get stuck on:

https://github.com/cockroachdb/cockroach/blob/5e6cc9e5598da0498c9fa9287314d63c88778510/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1644-L1648

Which checks if the existing replica (necessary=true) is less than the replacement (necessary=true). If the replacement candidate inputs (diversity score) is not greater than the existing, we will never rebalance to satisfy the constraint.

**To Reproduce**

#106548 reproduces the no rebalance target behavior. Reproduction using the simulator and more directly when calling `Allocator.Rebalance(Non)Voter`.

**Expected behavior**

Rebalance action returned with a promotion and demotion.

**Environment:**
Reproduces on master. Assume all versions affected.

Jira issue: CRDB-29615

### LINKED ISSUE #108127: kvserver: sustained constraint non-conformance for MR schemas
_Originally posted by @dikshant in https://github.com/cockroachdb/cockroach/issues/106128#issuecomment-1663129173_

Here is a debug zip, see below for repro steps.
https://drive.google.com/file/d/1Ilkl1vWS8CpyuNDku93dC9XLs0U9aI4k/view?usp=sharing

I tried this on a 23.1.7 on a 18 node multi region cluster in roachprod.

So this is interesting. Mapping replicas to replica_localities using @j82w 's fixed query shows the correct mappings:
```
root@localhost:26257/meetup> SELECT DISTINCT
                          ->       split_part(unnest(replica_localities), ',', 2) replica_localities,
                          ->       unnest(replicas) replica,
                          ->       range_id
                          ->     FROM [SHOW RANGE FROM TABLE product FOR ROW ('europe-west1', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')];
    replica_localities   | replica | range_id
-------------------------+---------+-----------
  region=europe-west1    |       7 |       69
  region=europe-west1    |       9 |       69
  region=europe-central2 |      11 |       69
  region=europe-central2 |      12 |       69
  region=europe-north1   |      15 |       69
(5 rows)
```

However, the violating range is still present and this is after waiting 10+ minutes:
```
root@localhost:26257/meetup> SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
  zone_id | subzone_id |       type       |       config       | report_id |        violation_start        | violating_ranges
----------+------------+------------------+--------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=us-east4:2 |         1 | 2023-08-02 23:44:58.271424+00 |                3
(1 row)

Time: 105ms total (execution 105ms / network 0ms)
```

# Reproduction steps:

1) Create a MR cluster. I used:
   ```
   roachprod create dikshant-test -n 18 --gce-zones 'us-east4-a','us-east4-a','us-east4-a','us- 
   central1-a','us-central1-a','us-central1-a','europe-west1-b','europe-west1-b','europe-west1- 
   b','europe-central2-b','europe-central2-b','europe-central2-b',"europe-north1-b","europe- 
   north1-b","europe-north1-b","us-west1-a","us-west1-a","us-west1-a" && roachprod stage 
   dikshant-test release v23.1.7 && roachprod start dikshant-test:1-18
   ```

2) Apply the following DDL and DML:
   https://gist.github.com/dikshant/d4d170d70e493119b7cb6306aedb7551

3) Check for violating ranges after waiting for ~10 minutes:
   ```
   SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
   ```

It seems the violating range always has the primary region on the config. I don't know if this is expected behavior.

For example I ran an ALTER to change the primary region:
```
ALTER DATABASE "meetup" SET PRIMARY REGION "us-west1";
SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
```
And got:

```
  zone_id | subzone_id |       type       |       config       | report_id |        violation_start        | violating_ranges
----------+------------+------------------+--------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=us-west1:2 |         1 | 2023-08-03 00:11:17.833192+00 |                2
(1 row)
```

Whereas running:
```
SET alter_primary_region_super_region_override = 'on';
ALTER DATABASE "meetup" SET PRIMARY REGION "europe-west1";
```
Gives us (after waiting a bit):
```
SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
  zone_id | subzone_id |       type       |         config         | report_id |        violation_start        | violating_ranges
----------+------------+------------------+------------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=europe-west1:2 |         1 | 2023-08-03 00:16:19.488701+00 |                8
```
            

Jira issue: CRDB-30324

### PR DESCRIPTION
**Pull request by kvoli**
Previously, it was possible for a satisfiable voter constraint to never
be satisfied when:

1. There were a correct number of `VOTER` and `NON_VOTER` replicas.
2. All existing replicas were necessary to satisfy a replica constraint,
   or voter constraint.

The allocator relies on the `RebalanceVoter` path to resolve voter
constraint violations when there are a correct number of each replica
type.

Candidates which are `necessary` to satisfy a constraint are
ranked higher as rebalance targets than those which are not. Under most
circumstances this leads to constraint conformance. However, when every
existing replica is necessary to satisfy a replica constraint, and a
voter constraint is unsatisfied -- `RebalanceVoter` would not consider
swapping a `VOTER` and `NON_VOTER` to satisfy the constraint.

For example, consider a setup where there are two stores, one in
locality `a` and the other `b`, where some range has the following
config and initial placement:

```
replicas          = a(non-voter) b(voter)
constraints       = a:1 b:1
voter_constraints = a:1
```

In this example, the only satisfiable placement is `a(voter)`
`b(non-voter)`, which would require promoting `a(non-voter) ->
a(voter)`, and demoting `b(voter)->b(non-voter)`. However, both are
necessary to satisfy `constraints` leading to no rebalance occurring.

Add an additional field to the allocator candidate struct, which is used
to sort rebalance candidates. The new field, `voterNecessary` is sorted
strictly after `necessary`, but before `diversityScore`.

The `voterNecessary` field can be true only when rebalancing voters, and
when the rebalance candidate is necessary to satisfy a voter constraint,
the rebalance candidate already has a non-voter, and the existing voter
is not necessary to satisfy *any* voter constraint.

Note these rebalances are turned into swaps (promotion and demotion) in
`plan.ReplicationChangesForRebalance`, so incur no snapshots.

Fixes: https://github.com/cockroachdb/cockroach/issues/98020
Fixes: https://github.com/cockroachdb/cockroach/issues/106559
Fixes: https://github.com/cockroachdb/cockroach/issues/108127

Release note (bug fix): Voter constraints which were never satisfied due
to all existing replicas being considered necessary to satisfy a replica
constraint, will now be satisfied by promoting existing non-voters.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-:-Ng03rdW2y64ArPhvqmK:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng02Mh8AeWzaxKp-4vq):*
nit: the code calls it `necessaryVoter`
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1788 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng00ybI0Sev38xP8dN9:-Ng00ybI0Sev38xP8dNA:bg33mh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d871218716512b40c544971d7b16e0e81d653935/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1788)):*
> ```Go
> 		// removed) in order to satisfy a voter constraint. When every replica is
> 		// necessary to satisfy an all-replica, or voter constraint, the remove
> 		// replica will not always be the existingCandidate.
> ```

should this be "the remove replica will always be the existingCandidate"?
___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng-ajeV3m8GvNidozCl:-Ng-ajeV3m8GvNidozCm:b-m3sg5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/657834adc168af5486ee626909c42e1063eec68f/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance#L53)):*
> ```
> # #106559.
> set_span_config delay=15m
> [0,10000): num_replicas=6 num_voters=5 constraints={'+region=eu-west-1':1,'+region=us-central-1':1,'+region=us-east-1':1,'+region=us-west-1':1} voter_constraints={'+region=us-west-1':2,'+region=us-east-1':2}
> ```

We've increased the number of voters we need in us-west-1, so I thought that was the constraint that would not be satisfied.
But r1 has `(n6,s6):9, (n7,s7):4` which are in us-west-1.
Can you add some code comments specifying what is unexpected in the violating constraints output?

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-:-Ng1WWn34CrwTBpvtKHJ:bzftgo7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`-- commits` line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng02Mh8AeWzaxKp-4vq):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: the code calls it `necessaryVoter`
</blockquote></details>

Renamed to `voterNecessary` in the code./
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator.go` line 1788 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng00ybI0Sev38xP8dN9:-Ng0kHM528iq_nQAzXFx:bvw4lym) ([raw file](https://github.com/cockroachdb/cockroach/blob/d871218716512b40c544971d7b16e0e81d653935/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1788)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be "the remove replica will always be the existingCandidate"?
</blockquote></details>

I was referring to the simulateRemoveTarget below. Which normally is selected as the same target as the replica being removed. Here it won't be because the voterNecessary field is only used for rebalancing. Updated to extend the comment.
___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng-ajeV3m8GvNidozCl:-Ng0mZu28HZ5C6NCkB3q:b-mkzmpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/657834adc168af5486ee626909c42e1063eec68f/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We've increased the number of voters we need in us-west-1, so I thought that was the constraint that would not be satisfied.
But r1 has `(n6,s6):9, (n7,s7):4` which are in us-west-1.
Can you add some code comments specifying what is unexpected in the violating constraints output?
</blockquote></details>

If the nodes in the AU locality were not added, then that would be the case. I realized that the initial config constraints were running into the same bug here, so the placement doesn't actually match the initial span config applied.

This led to the AU locality nodes violating the constraints for some of the ranges, as the issue persisted. 

I updated to use simpler localities and removed the AU nodes by setting the node locality after the cluster was setup, rather than adding nodes with a specific locality (shortcoming of the test harness currently).

Added additional comments as well.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 8 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-:-Ng4-m8e3PY6yIjzTzSU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng-ajeV3m8GvNidozCl:-Ng3zheyCwvwoXy-Vm9T:b-4v0jpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/657834adc168af5486ee626909c42e1063eec68f/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance#L53)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

If the nodes in the AU locality were not added, then that would be the case. I realized that the initial config constraints were running into the same bug here, so the placement doesn't actually match the initial span config applied.

This led to the AU locality nodes violating the constraints for some of the ranges, as the issue persisted. 

I updated to use simpler localities and removed the AU nodes by setting the node locality after the cluster was setup, rather than adding nodes with a specific locality (shortcoming of the test harness currently).

Added additional comments as well.
</blockquote></details>

This is easier to understand -- thanks.
Is there a way to log the placement after 4m, to show the initial assignment, and to log the placement after 10m (even for the successful case -- I realize that the unsuccessful one has the failed assertion that logs the placement).

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111609)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111609#-Ng-ajeV3m8GvNidozCl:-Ng4EdLwEo57yw9Bo0Sm:b1qnbcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/657834adc168af5486ee626909c42e1063eec68f/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_conformance#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is easier to understand -- thanks.
Is there a way to log the placement after 4m, to show the initial assignment, and to log the placement after 10m (even for the successful case -- I realize that the unsuccessful one has the failed assertion that logs the placement).
</blockquote></details>

This is possible in the rand_test framework, but not with arbitrary localities and constraints.

https://github.com/kvoli/cockroach/blob/ed5175253df75879c39d3c8ec155364852167ea1/pkg/kv/kvserver/asim/tests/rand_test.go#L140-L148


So there's no easy way atm, but it would be nice to add in the near future.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
