### PR TITLE
sql: add PARTITION ALL BY syntax for CREATE/ALTER TABLE

### PR DESCRIPTION
**Pull request by otan**
Added `PARTITION ALL BY` syntax for `CREATE TABLE` and `ALTER TABLE`
which is currently unimplemented. These will eventually become the
building blocks for table-level implicit partitioning.

Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
Looks good.  Just one comment on the approach taken below.

> Reviewed 16 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-:-MQSlZaG9VPijtBeUBDL:b-q2zdzn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQSVTyb8b98GnEakS2b:bima71p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
> ```Go
> // PartitionTableBy represents a PARTITION [ALL] BY definition within
> // a CREATE/ALTER TABLE statement.
> type PartitionTableBy struct {
> ```

Is the motivation of creating a new structure here avoiding having to change all references of `PartitionBy`?  If so, I worry that this makes the code less understandable, as we have `PartitionTableBy` which only refers to Tables, and `PartitionBy` which refers to tables (when in `PartitionTableBy`) and to indexes when not in that structure.  I thought for a while how we could fix this with naming changes to only `PartitionTableBy`, but I couldn't think of a better option there.

What are the downsides to adding the `bool` field to the `PartitionBy` structure directly?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQTEaCyDA_iPkditklv:b5uvtue) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is the motivation of creating a new structure here avoiding having to change all references of `PartitionBy`?  If so, I worry that this makes the code less understandable, as we have `PartitionTableBy` which only refers to Tables, and `PartitionBy` which refers to tables (when in `PartitionTableBy`) and to indexes when not in that structure.  I thought for a while how we could fix this with naming changes to only `PartitionTableBy`, but I couldn't think of a better option there.

What are the downsides to adding the `bool` field to the `PartitionBy` structure directly?
</blockquote></details>

I wanted to strongly type this so that you can't accidentally introduce PARTITION ALL BY to an index, and introduce that sanity check everywhere index partition bys are created.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQXdjcc5UP57QsvLpIc:bdq5gwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I wanted to strongly type this so that you can't accidentally introduce PARTITION ALL BY to an index, and introduce that sanity check everywhere index partition bys are created.
</blockquote></details>

In how many places are the partition bys created for indexes?  If it's only a few, doing that might make the code more understandable.  If not, at the very least I think we need a better comment above the PartitionBy definition to outline the differences between PartitionBy and PartitionTableBy (and maybe a short discussion as to why we named things the way we did).

**Review by mgartner — APPROVED** [review]
> Reviewed 17 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQYPJL76sUzV8fd1lBL:bxkb41s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

In how many places are the partition bys created for indexes?  If it's only a few, doing that might make the code more understandable.  If not, at the very least I think we need a better comment above the PartitionBy definition to outline the differences between PartitionBy and PartitionTableBy (and maybe a short discussion as to why we named things the way we did).
</blockquote></details>

We could do something like this:

```
type PartitionBy struct { ... }

type PartitionTableBy struct {
  All bool
  *PartitionBy
}

type PartitionIndexBy struct {
  *ParititionBy
}
```

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @mgartner)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQia8Ro21dPaOZQ5-Al:b-bi6so8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We could do something like this:

```
type PartitionBy struct { ... }

type PartitionTableBy struct {
  All bool
  *PartitionBy
}

type PartitionIndexBy struct {
  *ParititionBy
}
```
</blockquote></details>

both suggestions have been done!

**Review by mgartner — APPROVED** [review]
> Reviewed 23 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @dt)

___
*[pkg/sql/sem/tree/create.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-MQSVTya55ZC-9cuRA5K:-MQidI7L8csMKbGPtZdk:b-5x5502) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bca583a404cf5f6d8d4aebadeb3f703d2babe3/pkg/sql/sem/tree/create.go#L1100)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

both suggestions have been done!
</blockquote></details>

Should the comment for `PartitionByIndex` read `CREATE/ALTER INDEX` instead of `CREATE/ALTER TABLE`?

**Review by ajstorm — APPROVED** [review]
Thanks for making the changes.  

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58514#-:-MQmSXyr0DcRcNBwdYXk:b-s66gsy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @dt, and @mgartner)

**Comment by otan** [comment]
bors r=ajstorm,mgartner

**Pull request merged**
