### PR TITLE
sql: pool some of the processor allocations

### LINKED ISSUE #88525: sql/colexec/colbuilder: consider pooling render operators
**Is your feature request related to a problem? Please describe.**

Likely fallout from https://github.com/cockroachdb/cockroach/pull/83689, we now see 5+% of bytes allocated in tpcc due to these operators:
Screen Shot 2022-09-22 at 6 02 48 PM

**Describe the solution you'd like**
We pool other operators, we could pool these.

Jira issue: CRDB-19943

### LINKED ISSUE #88964: rowexec: tableReader can be accessed after being Released
Found when working on #88608.

Currently we have an issue where a `tableReader` (the only row-by-row processor allocation of which is `sync.Pool`ed) can be accessed even after it has been `Release`d. In particular, this could occur if the tableReader is part of the subquery tree with `rowSourceToPlanNode` adapter having it as input. We defer the closure of the subquery `planNode` tree until after the main query is executed, and `rowSourceToPlanNode.Close` calls `ConsumerClosed` on its input. However, the processors from the subquery are released when the subquery execution finishes, so that `ConsumerClosed` call can occur on a processor that was already put back into the pool (and possibly even picked up from the pool by another query).

This is a very old issue (dating at least to #38866), and with the move to the vectorized engine we are now unlikely to use the table reader processor. However, #88608 wanted to pool more processors, so the issue becomes more pressing.

Jira issue: CRDB-20057

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: clarify closing contract around plan node and row source adapters**

This commit cleans up the `rowSourceToPlanNode` adapter (from the
DistSQL processor to the planNode object) in the following manner:
- it removes the incorrect call to `ConsumerClosed` of the wrapped
input. This call was redundant (because the other side of the adapter
`planNodeToRowSource` does the closure too) but was also incorrect since
it could access the row source that was put back into the sync.Pool (and
maybe even picked up by another query). See issue 88964 for more details.
- it removes the checks around non-nil "metadata forwarder". These were
needed when the local planNode and DistSQL processor engines were merged
into one about four years ago, but nowadays the adapter always gets
a non-nil forwarder.

Fixes: #88964.

Release note: None

**sql: pool some of the processor allocations**

This commit makes it so that we now pool allocations of noop,
planNodeToRowSource, and columnarizer processors. Additionally,
trailing meta callbacks for these three as well as materializers
are changed to not be anonymous functions to further reduce the
allocations.

Fixes: #88525.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmark results are similar to what we had in #88608 before I had to pull out the last commit.

**Comment by yuzefovich** [comment]
The second commit here is an extension of what we had in #88608 (pooling of `planNodeToRowSource`s was added) and the first commit is new.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88973#-:-NDCZz_GDIicgAYe9oUa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
