### PR TITLE
sql: fix data race in MemberOfWithAdminOption

### LINKED ISSUE #95642: ccl/sqlproxyccl: TestBackendDialTLS failed due to race condition in catalog nstree
ccl/sqlproxyccl.TestBackendDialTLS [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8396114?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8396114?buildTab=artifacts#/) on master @ [2861a4ee05fac1cc13f87bf00f368a65ea8700dc](https://github.com/cockroachdb/cockroach/commits/2861a4ee05fac1cc13f87bf00f368a65ea8700dc):

```
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1964 +0x1cba
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1882 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:173 +0x117

Goroutine 5649 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:644 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:368 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:177 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:774 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).AcceptClients.func1()
      github.com/cockroachdb/cockroach/pkg/server/tenant.go:716 +0x267
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1588 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 5686 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:172 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:903 +0xf76
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:722 +0x2ac
  github.com/cockroachdb/cockroach/pkg/sql.(*internalTxn).QueryIteratorEx()
      <autogenerated>:1 +0x132
  github.com/cockroachdb/cockroach/pkg/sql.forEachRoleMembership()
      github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2760 +0x155
  github.com/cockroachdb/cockroach/pkg/sql.resolveMemberOfWithAdminOption()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:613 +0x1e4
  github.com/cockroachdb/cockroach/pkg/sql.MemberOfWithAdminOption.func2()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:552 +0x111
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:387 +0x51
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:305 +0x147
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:386 +0x2a4
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:356 +0xd0
==================
=== RUN   TestBackendDialTLS/tenant11
=== RUN   TestBackendDialTLS/tenant11To10
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackendDialTLS.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23645

### LINKED ISSUE #96539: ccl/sqlproxyccl: TestBackendDialTLS failed
ccl/sqlproxyccl.TestBackendDialTLS [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8580435?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8580435?buildTab=artifacts#/) on master @ [5fbcd8a8deac0205c7df38e340c1eb9692854383](https://github.com/cockroachdb/cockroach/commits/5fbcd8a8deac0205c7df38e340c1eb9692854383):

```
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2048 +0xad7
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2050 +0xc12
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1892 +0x424
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:171 +0x117

Goroutine 4821 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:644 +0x3c4
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:368 +0xd15
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:177 +0x48c
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:777 +0xc0a
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServerWrapper).AcceptClients.func1()
      github.com/cockroachdb/cockroach/pkg/server/tenant.go:729 +0x267
  github.com/cockroachdb/cockroach/pkg/server.startServeSQL.func1.1()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1631 +0x2eb
  github.com/cockroachdb/cockroach/pkg/util/netutil.(*TCPServer).ServeWith.func1()
      github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:188 +0x111
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6

Goroutine 4847 (running) created at:
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:170 +0x344
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:900 +0xf76
  github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryIteratorEx()
      github.com/cockroachdb/cockroach/pkg/sql/internal.go:719 +0x2ac
  github.com/cockroachdb/cockroach/pkg/sql.(*internalTxn).QueryIteratorEx()
      <autogenerated>:1 +0x132
  github.com/cockroachdb/cockroach/pkg/sql.resolveMemberOfWithAdminOption()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:652 +0x55b
  github.com/cockroachdb/cockroach/pkg/sql.MemberOfWithAdminOption.func2()
      github.com/cockroachdb/cockroach/pkg/sql/authorization.go:552 +0x111
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:387 +0x51
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:305 +0x147
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:386 +0x2a4
  github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan.func1()
      github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:356 +0xd0
==================
=== RUN   TestBackendDialTLS/tenant11
```
<p>Parameters: <code>TAGS=bazel,gss,race</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-sessions @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestBackendDialTLS.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24174

### PR DESCRIPTION
**Pull request by andyyang890**
Previously, there was a data race in the `MemberOfWithAdminOption`
function where a context cancellation would cause a transaction
to attempt to clean itself up before a singleflight query using
that transaction had completed.

Fixes #95642
Fixes #96539

Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
nice find! i wonder if the same issue could be affecting all the other usages of `singleflight`. (and if so, if the fix should be done in that package)

**Comment by ajwerner** [comment]
This will affect all the singleflights where an outer transaction is used.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98376#-:-NQC9MY20cPwxpfzyKY9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890)

**Comment by andyyang890** [comment]
> nice find! i wonder if the same issue could be affecting all the other usages of singleflight. (and if so, if the fix should be done in that package)

@rafiss I created another PR with an alternative fix that involves mitigating the data race within the `singleflight` package itself: #98469. Let me know if you would prefer that solution!

cc @ajwerner @andreimatei

**Comment by rafiss** [comment]
if possible, could we add a more targeted test that catches this bug? it feels kind of lucky to me that `TestBackendDialTLS` is the one that caught this. i could imagine that test being refactored in the future, and no longer catching a future regression on this.

**Comment by andyyang890** [comment]
Closed in favor of #98617

**Pull request closed without merging**
