### PR TITLE
rfc: generic query plans

### PR DESCRIPTION
**Pull request by mgartner**
Epic: CRDB-37712

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The RFC was reviewed in a Google doc [here](https://docs.google.com/document/d/1RtqpIr8IYiILt81ygOMJQ3w2B1T31GLMtdUoPbJYDuQ/edit).

There is a very simple prototype of this RFC here: https://github.com/cockroachdb/cockroach/pull/124061

**Review by michae2 — APPROVED** [review]
Nice work!

**Pull request merged**
