### PR TITLE
release-23.1: sql: regulate MODIFYCLUSTERSETTING with cluster setting

### PR DESCRIPTION
**Pull request by fqazi**
This PR introduces the cluster setting
sql.auth.modify_cluster_setting_applies_to_all.enabled which determines
whether users with MODIFYCLUSTERSETTING are able to edit non
sql.defaults settings. It also allows this setting to prevent viewing
sql.default settings. Additionally, a deprecation warning is added for
this cluster setting to inform that it should be replaced once the
cluster is finalized

Fixes: #122023

Release justification: important bug fix

Release note (bug fix): reintroduce
sql.auth.modify_cluster_setting_applies_to_all.enabled so that mixed
version clusters can migrate off this setting.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122055)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/logictest/testdata/logic_test/cluster_settings` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122055#-NvI4-V1Eq1QWn-hGjwp:-NvI4-V1Eq1QWn-hGjwq:b-lu94w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca3b894537d7c7bd1f1ce0710f6538198e517c0/pkg/sql/logictest/testdata/logic_test/cluster_settings#L132)):*
> ```
> 
> statement error only users with MODIFYCLUSTERSETTING or VIEWCLUSTERSETTING privileges are allowed to show cluster setting 'diagnostics.reporting.enabled'
> SHOW CLUSTER SETTING diagnostics.reporting.enabled
> ```

nit: can you add another test to make sure `SHOW CLUSTER SETTING sql.defaults.xyz` and `SET CLUSTER SETTING sql.defaults.xyz` works at this point?

**Review by rafiss — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122055)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

**Review by dhartunian — APPROVED** [review]

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122055)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/sql/logictest/testdata/logic_test/crdb_internal` line 1293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122055#gh-1567411745:-NvbHcz4ExqTZ38DCE1p:bmfg71q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dedcb16c45386008e1222d3d99911b9022ee860/pkg/sql/logictest/testdata/logic_test/crdb_internal#L1293)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: should this reference `sql.auth.modify_cluster_setting_applies_to_all.enabled`?
</blockquote></details>

Yes, good catch

**Comment by fqazi** [comment]
blathers backport staging-v23.1.19

**Comment by mikeCRL** [comment]
Revised the release note to add a brief mention of the role:

> Reintroduced [cluster setting](https://deploy-preview-18484--cockroachdb-docs.netlify.app/docs/v23.1/cluster-settings) `sql.auth.modify_cluster_setting_applies_to_all.enabled` so that mixed-version clusters can migrate off of this setting. It is deprecated in favor of the role [`MODIFYSQLCLUSTERSETTING`](https://deploy-preview-18484--cockroachdb-docs.netlify.app/docs/v23.1/set-cluster-setting#required-privileges). [#122455](https://github.com/cockroachdb/cockroach/pull/122455)

Feedback welcome, ideally in the PR https://github.com/cockroachdb/docs/pull/18484 in advance of the release (~mid-day tomorrow, Eastern).

**Comment by mikeCRL** [comment]
Thanks again for the release note correction, @rafiss.

**Pull request merged**
