### PR TITLE
sql: handle and test routines with polymorphic parameters and return type

### LINKED ISSUE #123239: optbuilder: internal error in edge cases
This is an issue to track regressions in edge cases that were introduced as a result of #119616. For example,

```sql
CREATE OR REPLACE FUNCTION dup (inout f2 anyelement, out f3 anyarray)
 AS 'select $1, array[$1,$1]' LANGUAGE sql;
 SELECT dup(22);
```

Jira issue: CRDB-38255

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: handle and test routines with polymorphic parameters and return type

This commit adds overload resolution and type-checking logic for UDFs
and stored procedures that have polymorphic-typed parameters and/or
a polymorphic return type. Currently, this only applies to `ANYELEMENT`
and `ANYARRAY`.

Fixes #123239

Release note (bug fix): Fixed a bug that could cause internal errors
when a routine had polymorphic parameters and/or a polymorphic return
type. The bug has existed since v22.2 when UDFs were introduced.

#### sql: add session var to gate polymorphic parameter fix

This commit adds a session variable, `optimizer_use_polymorphic_parameter_fix`,
as an escape hatch so that the polymorphic routine parameter fixes from
the previous commit can be disabled.

Informs #123239

Release note: None

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first commit is from #123457.

**Review by yuzefovich — COMMENTED** [review]
I'm still reading through but thought I'd push what I have so far.

I ran `pg_regress` on this PR - the diff is at https://github.com/yuzefovich/cockroach/commit/24f25edc82241bed36a39449b40590d2dc70df86.

There are still two stack traces there worth checking out, e.g:
```sql
 create function f1(x anyarray) returns anyarray as $$
 begin
   return x;
 end$$ language plpgsql;
 select f1(array[2,4]) as int, f1(array[4.5, 7.7]) as num;
```
Another difference I noticed is:
```
  create function dfunc(anyelement = 'World'::text) returns text as $$
    select 'Hello, ' || $1::text;
  $$ language sql;
-+ERROR:  argument of DEFAULT must be type anyelement, not type string
++ERROR:  invalid cast: anyelement -> string
```

> Reviewed 2 of 2 files at r1, 5 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-NwvCG4D7JboKUjxNa1e:bkdecwu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvBYkN-MGCZr_0tCl3:-NwvBYkN-MGCZr_0tCl4:bc6eqo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L337)):*
> ```Go
> 					"A result of type %s requires at least one input of type "+
> 						"anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.",
> 					polyTyp.SQLStringForError(),
> ```

nit: should we do `strings.ToLower(polyTyp.SQLStringForError())` to match postgres? Diff from the pg_regress:
```
--ERROR:  cannot determine result data type
+ ERROR:  cannot determine result data type
 -DETAIL:  A result of type anyelement requires at least one input of type anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.
++DETAIL:  A result of type ANYELEMENT requires at least one input of type anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.
```
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuDx9l3DH-hZ3XHfda:-NwuDx9l3DH-hZ3XHfdb:byued1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L343)):*
> ```Go
> 				makeErr(funcReturnType)
> 			} else {
> 				for i := range funcReturnType.TupleContents() {
> ```

nit: could simplify this a bit with
```
for _, tc := range funcReturnType.TupleContents() {
...
```
by using `tc` later.
___
*[`pkg/sql/opt/optbuilder/routine.go` line 675 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuEj8y5NpKt6FrHsOH:-NwuEj8y5NpKt6FrHsOI:b-bhqs3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/routine.go#L675)):*
> ```Go
> 	// Check whether some arguments were omitted. We need to use the
> 	// corresponding DEFAULT expressions if so.
> 	if numDefaultsToUse := o.Types.Length() - len(args); numDefaultsToUse > 0 {
> ```

nit: now that this block is inside a function, it'd be cleaner to check if `numDefaultToUse` is non-positive and short-circuit the function if so.
___
*[`pkg/sql/sem/tree/overload.go` line 1066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvF2X00l9qFI2NSPFb:-NwvF2X00l9qFI2NSPFc:b-1ulbfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/overload.go#L1066)):*
> ```Go
> 			}
> 		}
> 		if hasPolymorphicTyp {
> ```

nit: maybe negate and short-circuit?
___
*[`pkg/sql/sem/tree/type_check.go` line 3632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvFkie8UTHJCArgZlj:-NwvFkie8UTHJCArgZlk:b-ayzfna) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/type_check.go#L3632)):*
> ```Go
> //     be at least one non-NULL argument in order to resolve a concrete type.
> //
> // enforceConsistency, if true, indicates that resolvePolymorphicArgTypes should
> ```

nit: do you think it would be cleaner to return `(anyElemTyp *types.T, err error)`, and the caller than decide whether to panic with the error or not? We'll probably need an extra boolean to indicate whether any polymorphic types were found. The current approach seems reasonable too.

nit: `s/resolve/Resolve/`.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_polymorphic` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuGiu-5SskxV-XRDYD:-NwuGiu-5SskxV-XRDYE:b3pifyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/logictest/testdata/logic_test/procedure_polymorphic#L137)):*
> ```
> CALL p('hi'::greetings, 'hello'::greetings);
> 
> ## The supplied arguments for ANYENUM parameters must have the same type, and
> ```

nit: probably missing a TODO above this comment.

**Review by DrewKimball — COMMENTED** [review]
Thanks for taking a look, and for running pg_regress!

>There are still two stack traces there worth checking out

This is now fixed - we were missing the logic to replace polymorphic parameter types when they are passed to PL/pgSQL. This also prompted me to add a commit to throw the correct error when the user attempts to define a polymorphic-typed variable.

>Another difference I noticed

Opened an issue here: https://github.com/cockroachdb/cockroach/issues/123536

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-Nwx41n_AbkgxPn2HyHz:b-fy7gq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvBYkN-MGCZr_0tCl3:-Nwx2Nq16ogi5bPHUN26:b-7ia5uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L337)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we do `strings.ToLower(polyTyp.SQLStringForError())` to match postgres? Diff from the pg_regress:
```
--ERROR:  cannot determine result data type
+ ERROR:  cannot determine result data type
 -DETAIL:  A result of type anyelement requires at least one input of type anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.
++DETAIL:  A result of type ANYELEMENT requires at least one input of type anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.
```
</blockquote></details>

Good point; I'll use `T.Name()` like in other places. I also added `anyarray` to the implementation. I wonder though, if we should be using `SQLStandardName` instead?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 343 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuDx9l3DH-hZ3XHfda:-Nwx2v15DdE8VbWf47KE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L343)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: could simplify this a bit with
```
for _, tc := range funcReturnType.TupleContents() {
...
```
by using `tc` later.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/routine.go` line 675 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuEj8y5NpKt6FrHsOH:-Nwx3Gl494RGW5m8F_cb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/routine.go#L675)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: now that this block is inside a function, it'd be cleaner to check if `numDefaultToUse` is non-positive and short-circuit the function if so.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/overload.go` line 1066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvF2X00l9qFI2NSPFb:-Nwx3POPE2Fkeb4uqY4n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/overload.go#L1066)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe negate and short-circuit?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/type_check.go` line 3632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvFkie8UTHJCArgZlj:-Nwx3U2A6wrO_NK42y9W:b-38f8kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/type_check.go#L3632)):*
My thinking was that we should try and avoid the overhead, since this function could be called often if there's a candidate overload that usually gets filtered out. But that's probably not that important... what do you think?

>nit: `s/resolve/Resolve/`.
Done.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_polymorphic` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwuGiu-5SskxV-XRDYD:-Nwx40A073seQPCBW3YK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/logictest/testdata/logic_test/procedure_polymorphic#L137)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably missing a TODO above this comment.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
Very nice work! I have some minor comments.

> Reviewed 9 of 18 files at r2, 20 of 20 files at r4, 13 of 13 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-NxEDSAb6RbIgXNFKrBj:bvprjhy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxEDFSU8QaQmQqUDHOu):*
What's your thinking behind introducing this gate? Is it because we'll be backporting it to 24.1.1 version so that we have an escape hatch?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvBYkN-MGCZr_0tCl3:-NxE4FEz-tVUqhNt2RxS:bdcqxon) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L337)):*
> I wonder though, if we should be using `SQLStandardName` instead?

Seems like we should.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxE3wNyApgWPg4vJqkr:-NxE3wNz11KJ2cyh38aM:b-824njd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/opt/optbuilder/create_function.go#L321)):*
> ```Go
> 		for i := range cf.Params {
> 			if cf.Params[i].IsInParam() {
> 				typ, err := tree.ResolveType(b.ctx, cf.Params[i].Type, b.semaCtx.TypeResolver)
> ```

nit: we resolve types for all parameters in a loop above. Should we additionally check all input parameters for having polymorphic type there too, unconditionally?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 352 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxECzBe268meMryggtk:-NxECzBe268meMryggtl:bmgumuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f12ba3324c1e5857acab33ac162090889a4a30/pkg/sql/opt/optbuilder/plpgsql.go#L352)):*
> ```Go
> 				panic(recordVarErr)
> 			} else if typ.IsPolymorphicType() {
>         // NOTE: Postgres also returns an "unsupported" error.
> ```

nit: indentation is off.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxED2X077zyHo4dbrmk:-NxED2X077zyHo4dbrml:b-d6v9un) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f12ba3324c1e5857acab33ac162090889a4a30/pkg/sql/opt/optbuilder/plpgsql.go#L354)):*
> ```Go
>         // NOTE: Postgres also returns an "unsupported" error.
> 				panic(pgerror.Newf(pgcode.FeatureNotSupported,
> 					"variable \"%s\" has pseudo-type %s", dec.Var, typ.SQLStringForError(),
> ```

nit: should we be using `typ.SQLStandardName()` here?
___
*[`pkg/sql/opt/optbuilder/routine.go` line 738 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxE6Ldg3H5mHd05Jni4:-NxE6Ldg3H5mHd05Jni5:brdzqwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/opt/optbuilder/routine.go#L738)):*
> ```Go
> func (b *Builder) routineHasPolymorphicOutParam(params tree.RoutineParams) bool {
> 	for i := range params {
> 		if params[i].IsOutParam() {
> ```

nit: this seems like another boolean we can compute when resolving types in the first loop over parameters. I don't feel strongly whether this helper function should be removed though - up to you.
___
*[`pkg/sql/sem/tree/overload.go` line 1074 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwzPELX8IbMBcX3ErkH:-NwzPELX8IbMBcX3ErkI:bj9nxij) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/sem/tree/overload.go#L1074)):*
> ```Go
> 				_, isOutParam := toParamOrdinal(i, ol.OutParamOrdinals)
> 				if isOutParam {
> 					// A CALL statement must specify an argument for each OUT parameter
> ```

Related to something you spotted earlier in one of my PRs: IIRC the expression for the OUT parameter must of coercible to the type, is it already handled elsewhere when that type is polymorphic? Do we have a test for a mismatch?
___
*[`pkg/sql/sem/tree/type_check.go` line 3632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvFkie8UTHJCArgZlj:-NxE83Xh26CesgBMxHEc:b-f2w7g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/type_check.go#L3632)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

My thinking was that we should try and avoid the overhead, since this function could be called often if there's a candidate overload that usually gets filtered out. But that's probably not that important... what do you think?

>nit: `s/resolve/Resolve/`.
Done.
</blockquote></details>

What overhead are you referring to? The overhead of having to create an error object when `ok=false` would suffice? Yeah, that's a good point, current approach seems good then. Maybe extend the comment a bit for why we have this `enforceConsistency=false` option.
___
*[`pkg/sql/sem/tree/type_check.go` line 3707 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxEAHFW1SP7x-4MBdea:-NxEAHFW1SP7x-4MBdeb:b-857l9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/sem/tree/type_check.go#L3707)):*
> ```Go
> 		// All supplied arguments were NULL.
> 		//
> 		// Note: we do not return ok=false when enforceConsistency is false, because
> ```

nit: I think we either need to adjust the contract of the method (i.e. extend the comment to spell out what happens in this case) or return `ok=false` when `enforceConsistency=false` in order to make misuse of this exported method less error-prone.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_polymorphic` line 404 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxECO8iESyGZlpoxJ4L:-NxECO8iESyGZlpoxJ4M:b-a98itc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/logictest/testdata/logic_test/procedure_polymorphic#L404)):*
> ```
> # Note: When the proc is called, Postgres returns an error with the message:
> # "cannot display a value of type anyelement". This seems like an oversight, so
> # the difference is probably ok. See #123454.
> ```

Interesting find! Do you wanna file a bug upstream? :smiley:

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 16 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxEDFSU8QaQmQqUDHOu):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What's your thinking behind introducing this gate? Is it because we'll be backporting it to 24.1.1 version so that we have an escape hatch?
</blockquote></details>

Yes, that's right. It wasn't too hard to do and it decreases risk, so why not?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvBYkN-MGCZr_0tCl3:-NxnvmWj4ME3pe-bHdoM:b-8qwk8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/opt/optbuilder/create_function.go#L337)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> I wonder though, if we should be using `SQLStandardName` instead?

Seems like we should.
</blockquote></details>

Tracking issue: https://github.com/cockroachdb/cockroach/issues/124087
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxE3wNyApgWPg4vJqkr:-NxpdCmzBONfdfSiQy7o:b-xig8dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/opt/optbuilder/create_function.go#L321)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we resolve types for all parameters in a loop above. Should we additionally check all input parameters for having polymorphic type there too, unconditionally?
</blockquote></details>

I've moved this check to the previous loop. Is that what you meant?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 352 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxECzBe268meMryggtk:-NxnvrohCpg7sYWmaHg7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f12ba3324c1e5857acab33ac162090889a4a30/pkg/sql/opt/optbuilder/plpgsql.go#L352)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: indentation is off.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxED2X077zyHo4dbrmk:-Nxnw-pF5TLQq33f2lCY:b1263uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f12ba3324c1e5857acab33ac162090889a4a30/pkg/sql/opt/optbuilder/plpgsql.go#L354)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we be using `typ.SQLStandardName()` here?
</blockquote></details>

:facepalm: Yes, good catch. I'll do `Name()` for now for consistency with other errors; we can track changing to `SqlStandardName` with https://github.com/cockroachdb/cockroach/issues/124087.
___
*[`pkg/sql/opt/optbuilder/routine.go` line 738 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxE6Ldg3H5mHd05Jni4:-NxoYaqn6DEr2hWe4yil:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/opt/optbuilder/routine.go#L738)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this seems like another boolean we can compute when resolving types in the first loop over parameters. I don't feel strongly whether this helper function should be removed though - up to you.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/overload.go` line 1074 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwzPELX8IbMBcX3ErkH:-NxoZ6Ft1Klu6Geewk8f:by20x2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/sem/tree/overload.go#L1074)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Related to something you spotted earlier in one of my PRs: IIRC the expression for the OUT parameter must of coercible to the type, is it already handled elsewhere when that type is polymorphic? Do we have a test for a mismatch?
</blockquote></details>

Very good point - we should also be calling `ResolvePolymorphicArgTypes` with the OUT parameters here. I've now fixed it, and added some tests.
___
*[`pkg/sql/sem/tree/type_check.go` line 3632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NwvFkie8UTHJCArgZlj:-NxpZ0y50qDV4OfZLHa1:bx2b8z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5c55f8e0abaeef42a6c474151f4352b8142f2f3/pkg/sql/sem/tree/type_check.go#L3632)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What overhead are you referring to? The overhead of having to create an error object when `ok=false` would suffice? Yeah, that's a good point, current approach seems good then. Maybe extend the comment a bit for why we have this `enforceConsistency=false` option.
</blockquote></details>

Yes, exactly. I've added some detail to the comment.
___
*[`pkg/sql/sem/tree/type_check.go` line 3707 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxEAHFW1SP7x-4MBdea:-NxpZlvXEAIrS9OX8dUh:b-d2p8cd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/sem/tree/type_check.go#L3707)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I think we either need to adjust the contract of the method (i.e. extend the comment to spell out what happens in this case) or return `ok=false` when `enforceConsistency=false` in order to make misuse of this exported method less error-prone.
</blockquote></details>

We can't return `ok=false`, since that case needs to pass the overload resolution step. I'll move this check outside of this function so it's no longer an issue. This also required returning the count of polymorphic parameters, so that we can distinguish between no polymorphic parameters, and the case when only NULL is supplied as the arguments.
___
*[`pkg/sql/logictest/testdata/logic_test/procedure_polymorphic` line 404 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxECO8iESyGZlpoxJ4L:-NxpwaZy4O3ecHFpr9ug:bl3srfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/logictest/testdata/logic_test/procedure_polymorphic#L404)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Interesting find! Do you wanna file a bug upstream? :smiley:
</blockquote></details>

Filed one here: https://postgrespro.com/list/id/18463-f8cd77e12564d8a2@postgresql.org#head

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r7, 11 of 11 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-Nxs0oH2Co7vJFHONcIU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxE3wNyApgWPg4vJqkr:-NxryLaU1kU2-yvAZhNR:bqfcuyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7e75d44a7e2608f1252f80332ef48d78704b9e7/pkg/sql/opt/optbuilder/create_function.go#L321)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I've moved this check to the previous loop. Is that what you meant?
</blockquote></details>

Yeah, thanks.
___
*[`pkg/sql/sem/tree/type_check.go` line 3638 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxrzIKM-E4MumJCMKO0:-NxrzIKM-E4MumJCMKO1:b-f2jkn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff82fc935cf3f7fda7348c053f11452ee1303046/pkg/sql/sem/tree/type_check.go#L3638)):*
> ```Go
> // throw a suitable error in the case of invalid arguments, rather than
> // returning with ok=false. Note: we do this instead of always returning the
> // error because error construction can be expensive.a
> ```

nit: "expensive.a".

**Review by DrewKimball — COMMENTED** [review]
TFYR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-NxvX_RO2l9Bzdi0R0GF:b-814cj3)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/sem/tree/type_check.go` line 3638 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NxrzIKM-E4MumJCMKO0:-NxvWg48EB94_umrxKeM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff82fc935cf3f7fda7348c053f11452ee1303046/pkg/sql/sem/tree/type_check.go#L3638)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: "expensive.a".
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 18 files at r2, 3 of 20 files at r4, 2 of 13 files at r5, 2 of 16 files at r7, 4 of 14 files at r10, 19 of 19 files at r11, 1 of 1 files at r12, 12 of 12 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-O09SWGN1hFkKDzdLJ1j:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`docs/generated/sql/bnf/create_trigger_stmt.bnf` line 2 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-O09S17GDSJhdiLiKqqI:-O09S17GDSJhdiLiKqqJ:bd8i93o) ([raw file](https://github.com/cockroachdb/cockroach/blob/00df4aa21dfd33bac44b61d81ec457df40ae63e9/docs/generated/sql/bnf/create_trigger_stmt.bnf#L2)):*
> ```
> create_trigger_stmt ::=
> 	'CREATE' 'TRIGGER' unrestricted_name create_trigger_timing create_trigger_event_list 'ON' table_name opt_create_trigger_level 'EXECUTE' create_trigger_func_or_proc func_name '(' ')'
> ```

Looks like this `TRIGGER` diagram was included by accident.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NyRH3EdEqdiiw4L71xA:-NyRH3Ee-dWNrBPaclpf:b-rxybty) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a77708190d404cd90881d445b80c047e1cb1c8/pkg/sql/opt/optbuilder/create_function.go#L244)):*
> ```Go
> 			if resolved := texpr.ResolvedType(); !resolved.Identical(typ) {
> 				if !cast.ValidCast(resolved, typ, cast.ContextAssignment) {
> 					if !typ.IsPolymorphicType() || !resolved.Equivalent(typ) {
> ```

nit: Might help to add a note here like: "If the argument's type is polymorphic and equivalent to the DEFAULT expression's type, then a cast is not necessary.

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-:-O0AyEZv7uDiSXrO0ScN:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-NyRH3EdEqdiiw4L71xA:-O0Ay1PJAE2o_RO9mak2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a77708190d404cd90881d445b80c047e1cb1c8/pkg/sql/opt/optbuilder/create_function.go#L244)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Might help to add a note here like: "If the argument's type is polymorphic and equivalent to the DEFAULT expression's type, then a cast is not necessary.
</blockquote></details>

Done.
___
*[`docs/generated/sql/bnf/create_trigger_stmt.bnf` line 2 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/123459#-O09S17GDSJhdiLiKqqI:-O0AxpUf3-eTr0MY7pUf:b-m16fax) ([raw file](https://github.com/cockroachdb/cockroach/blob/00df4aa21dfd33bac44b61d81ec457df40ae63e9/docs/generated/sql/bnf/create_trigger_stmt.bnf#L2)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks like this `TRIGGER` diagram was included by accident.
</blockquote></details>

Nice catch, thanks!

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 16 files at r15, 14 of 14 files at r18, 11 of 11 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123459)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

**Pull request merged**
