### PR TITLE
workload/tpcc: preserve unexpected errors during checks

### PR DESCRIPTION
**Pull request by stevendanna**
In these checks, we expect that the queries return no rows. As a result, we expect for `gosql.ErrNoRows`. But, if we got a non-nil error that isn't ErrNoRows, it would be helpful for debugging to be able to see that error.

Release note: None

Epic: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
Thanks for the fix! Since previously an error may have been swallowed, I am curious if you have a hunch or a suspicion of a specific type of error?

:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89748#-:-NE6e5jl1wQJw8WpSORp:b-1mtxlp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[`pkg/workload/tpcc/checks.go` line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89748#-NE6cJvMASPEmcxxnHZK:-NE6cJvN4Y1Tc3jbt7NC:bbprxbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5630a6e21f8f7dd7462adc28d559eb8ed078fe23/pkg/workload/tpcc/checks.go#L290)):*
> ```Go
> 			return errors.Wrapf(err, "unexpected error during check")
> 		} else {
> 			return errors.Errorf("right EXCEPT right returned nonzero results.")
> ```

The literal error message is rather confusing. Could we make it more "mathy" to disambiguate? E.g., 

```
return errors.Errorf("new_order on LHS returned nonzero results.")
```

**Review by renatolabs — APPROVED** [review]
:lgtm:

Suggestion: IMO the error handling logic is more readable as below, but it's personal preference.

```go
if err := secondQuery.Scan(); err == nil {
    return errors.Errorf("right EXCEPT right returned nonzero results.")
} else if !errors.Is(err, gosql.ErrNoRows) {
    return errors.Wrapf(err, "unexpected error during check")
}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89748#-:-NE72sjR-W2-sO6MO7Sh:b-1nzpu)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @srosenberg and @stevendanna)

**Review by stevendanna — COMMENTED** [review]
@srosenberg Based on a review of some recent and past issues, I think most of the time we see this error, it is actually us having swallowed a "result is ambiguous" error that was caused by some other issue in the cluster.

@renatolabs That's much better, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89748#-:-NE7sQQU126ZYRwzB5l4:b-62ck51)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @srosenberg)

___
*[`pkg/workload/tpcc/checks.go` line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89748#-NE6cJvMASPEmcxxnHZK:-NE7so1t5Sb8wPM2wthn:b-fn0fqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5630a6e21f8f7dd7462adc28d559eb8ed078fe23/pkg/workload/tpcc/checks.go#L290)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

The literal error message is rather confusing. Could we make it more "mathy" to disambiguate? E.g., 

```
return errors.Errorf("new_order on LHS returned nonzero results.")
```
</blockquote></details>

I tried to add more descriptive messages here.

**Comment by stevendanna** [comment]
bors r=srosenberg,renatolabs

**Comment by stevendanna** [comment]
blathers backport 22.2

**Comment by stevendanna** [comment]
blathers backport 22.2.0

**Pull request merged**
