### PR TITLE
server,sql: allow admin UI to view table details for non-admins

### LINKED ISSUE #44033: observability: ui regression introduced by fixing #42567
**BACKGROUND**
the recent security fix in #42567 that was backported to 19.2.2 created a discrepancy between the behavior of `show tables` from the sql shell and viewing the `databases/tables` page on the web-ui. 

the [release note](https://www.cockroachlabs.com/docs/releases/v19.2.2.html#admin-ui-changes) mentions the following: `Certain web UI pages (like the list of databases or tables) now restrict their content to match the privileges of the logged-in user.`

**DESCRIPTION**
Even when granted the necessary select privileges on the respective database and table, the UI still returns `this database has no tables`. even though the database and tables are accessible from the sql shell.

the trick here is that when you run `SHOW TABLES`, the query that is executed is `select * from <currentdb>.information_schema.tables` which is always possible if the user has the correct permissions on the db.

but the UI endpoint executes `select * from system.xxx` where the logged-in user, if not admin, does not have permission to access directly.

Currently, on a non-enterprise enabled cluster only the root user has the admin role. which means that this page will never be accessible as the root user can not log in to the UI.

this fallout is also documented here https://github.com/cockroachdb/docs/pull/6321 

A related issue is https://github.com/cockroachdb/cockroach/issues/43870

**WORKAROUND (FOR USERS)**

Use an admin user to log in to the UI and view the information.

Core users without a license can create a non-root admin users as follows:

1. obtain temporary eval license
2. create user and grant admin role
3. let license expire; the admin user will continue to be valid

A patch revision will be issued for the affected release to correct this limitation.

**SOLUTION (INTERNAL)**

rework the ui query to match the sql query issued from `show tables`

----

big thanks to @knz for explaining this to me and detailing the proposals in the above PR and issue.

note from knz: `it was not designed to be used by non-admin users to start with, and it kinda worked "by accident" until we patched the security problem`

### PR DESCRIPTION
**Pull request by otan**
Resolves #44033 

* Added `crdb_internal.get_zone_config` and
`crdb_internal.get_namespace_id`, which executes queries to system
tables and checks permissions afterwards. This is needed for speedy
point lookups for the admin UI.
* Modified the EvalContext with a PrivilegedAccessor, containing
any accessors that requires privileged access to view data.
* Modified the admin UI to use the new crdb_internal queries.

Release note (admin ui change, security update, bug fix): We previously
introduced a fix on the admin UI to prevent non-admin users from
executing queries - however, this accidentally made certain pages
requiring table details not to display. This PR allows the table details
to be displayed in its former glory.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Overall this is very good (as usual) and thank you for the fast turnaround on the architectural direction.
I have one final comment on the structure of the code and afterwards this will be good to go.

> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-:-Lz979Ej7pLXICJngXUq:bx0yxcf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/sql/sem/builtins/builtins.go, line 3330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-Lz976m5DZ4pwN6DAB_4:-Lz976m5DZ4pwN6DAB_5:bh4iv1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e28b50c91bec40c1f5f5abe7cc5eb8607fcf204/pkg/sql/sem/builtins/builtins.go#L3330)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Int),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				const query = `SELECT id FROM system.namespace WHERE "parentID" = $1 AND name = $2`
> ```

yeah so this is what I was writing earlier about needing an accessor in the EvalContext.

Here is your challenge:
- we are *not* exporting the InternalExecutor for use directly by SQL built-ins
- it's not the responsibility of a SQL built-in function to enforce policy about which users have access to which descriptor. That policy code must be in `sql/authorization.go`

Hence my suggestion from earlier:
- have this logic (the SQL query to system.xxx + permission filtering) in the `sql` package
- make an interface in `tree` with just these two functions `LookupNamespaceID` and `LookupZoneConfigByNamespaceID` and have a reference of that interface type in `EvalContext`
- have the 2 builtins only call these two functions without concerning themselves with descriptors, permissions etc
___
*[pkg/sql/sem/builtins/builtins.go, line 5356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-Lz96jhH2n8oNnNLye1s:-Lz96jhICdugOqQ8qLOn:bbt476n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e28b50c91bec40c1f5f5abe7cc5eb8607fcf204/pkg/sql/sem/builtins/builtins.go#L5356)):*
> ```Go
> 
> // checkDescriptorPermissions returns nil if the executing user has permissions
> // to check the permissions of a descriptor given it's ID.
> ```

... given *its* ID

and this function, as explained above, needs to be in `sql` (and I suspect the code can be simplified once you have this in `sql`).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/sql/sem/builtins/builtins.go, line 3330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-Lz976m5DZ4pwN6DAB_4:-Lz99Q7M5k48oFzc9EHv:b-tjywky) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e28b50c91bec40c1f5f5abe7cc5eb8607fcf204/pkg/sql/sem/builtins/builtins.go#L3330)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yeah so this is what I was writing earlier about needing an accessor in the EvalContext.

Here is your challenge:
- we are *not* exporting the InternalExecutor for use directly by SQL built-ins
- it's not the responsibility of a SQL built-in function to enforce policy about which users have access to which descriptor. That policy code must be in `sql/authorization.go`

Hence my suggestion from earlier:
- have this logic (the SQL query to system.xxx + permission filtering) in the `sql` package
- make an interface in `tree` with just these two functions `LookupNamespaceID` and `LookupZoneConfigByNamespaceID` and have a reference of that interface type in `EvalContext`
- have the 2 builtins only call these two functions without concerning themselves with descriptors, permissions etc

</blockquote></details>

(Moreover the `sqlutil` thing did not exist in 19.1 and 2.1 so your current approach would not be backportable. This is a mere detail compared to the more important argument about which package is responsible for privilege checks, but a relevant practical detail nonetheless.)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/sem/builtins/builtins.go, line 3330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-Lz976m5DZ4pwN6DAB_4:-Lz9RdGw2rW0YVLp_3zH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e28b50c91bec40c1f5f5abe7cc5eb8607fcf204/pkg/sql/sem/builtins/builtins.go#L3330)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

(Moreover the `sqlutil` thing did not exist in 19.1 and 2.1 so your current approach would not be backportable. This is a mere detail compared to the more important argument about which package is responsible for privilege checks, but a relevant practical detail nonetheless.)
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 5356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-Lz96jhH2n8oNnNLye1s:-Lz9RdqU42TzcopM3f-p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e28b50c91bec40c1f5f5abe7cc5eb8607fcf204/pkg/sql/sem/builtins/builtins.go#L5356)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

... given *its* ID

and this function, as explained above, needs to be in `sql` (and I suspect the code can be simplified once you have this in `sql`).
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm_strong:  awesome.

> Reviewed 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44167#-:-Lz9TNcJ6VVsnlKnN9kF:b-tqx3rc)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=knz

thanks for the help! remaining push was to fix a lint error.
i will look at backporting this, but 19.1 is already on it's way. not sure if we should restart for it.

**Comment by knz** [comment]
> not sure if we should restart for it.

Please ask for advice from Artem and Tim. If there's enough support demand it should make it.

**Comment by knz** [comment]
maybe also discuss on #release

**Pull request merged**
