### PR TITLE
opt: support BYTES for histogram range calculations

### LINKED ISSUE #68346: opt: row estimates for bytes columns inaccurate
Optimizer row estimates for `BYTES` columns are dividing the histogram bucket by 2 instead of by the portion of the key space covered by the span. (Not totally sure this is specific to `BYTES` but that is where I observed it.)

Here's an example:

```
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
CREATE TABLE t (
  i INT PRIMARY KEY,
  s STRING,
  b BYTES,
  INDEX s (s),
  INDEX b (b)
);
ALTER TABLE t INJECT STATISTICS '[
  {
    "columns": [
      "i"
    ],
    "created_at": "2021-08-02 17:23:30.293908",
    "distinct_count": 65536,
    "histo_buckets": [
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "0"
      },
      {
        "distinct_range": 32766,
        "num_eq": 1,
        "num_range": 32766,
        "upper_bound": "32767"
      },
      {
        "distinct_range": 32767,
        "num_eq": 1,
        "num_range": 32767,
        "upper_bound": "65535"
      }
    ],
    "histo_col_type": "INT8",
    "name": "repro",
    "null_count": 0,
    "row_count": 65536
  },
  {
    "columns": [
      "s"
    ],
    "created_at": "2021-08-02 17:23:30.293908",
    "distinct_count": 65536,
    "histo_buckets": [
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "\\x0000"
      },
      {
        "distinct_range": 32766,
        "num_eq": 1,
        "num_range": 32766,
        "upper_bound": "\\x7FFF"
      },
      {
        "distinct_range": 32767,
        "num_eq": 1,
        "num_range": 32767,
        "upper_bound": "\\xFFFF"
      }
    ],
    "histo_col_type": "STRING",
    "name": "repro",
    "null_count": 0,
    "row_count": 65536
  },
  {
    "columns": [
      "b"
    ],
    "created_at": "2021-08-02 17:23:30.293908",
    "distinct_count": 65536,
    "histo_buckets": [
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "\\x0000"
      },
      {
        "distinct_range": 32766,
        "num_eq": 1,
        "num_range": 32766,
        "upper_bound": "\\x7FFF"
      },
      {
        "distinct_range": 32767,
        "num_eq": 1,
        "num_range": 32767,
        "upper_bound": "\\xFFFF"
      }
    ],
    "histo_col_type": "BYTES",
    "name": "repro",
    "null_count": 0,
    "row_count": 65536
  }
]';
EXPLAIN SELECT i FROM t WHERE i >= 0x55B4 AND i < 0x55B5;
EXPLAIN (OPT, VERBOSE) SELECT i FROM t WHERE i >= 0x55B4 AND i < 0x55B5;
EXPLAIN SELECT s FROM t WHERE s >= '\x55B4' AND s < '\x55B5';
EXPLAIN (OPT, VERBOSE) SELECT s FROM t WHERE s >= '\x55B4' AND s < '\x55B5';
EXPLAIN SELECT b FROM t WHERE b >= '\x55B4' AND b < '\x55B5';
EXPLAIN (OPT, VERBOSE) SELECT b FROM t WHERE b >= '\x55B4' AND b < '\x55B5';
```

For the `BYTES` column the row estimate is 16383 instead of 1, like I would expect.

```
                           info
----------------------------------------------------------
  scan t@b
   ├── columns: b:3
   ├── constraint: /3/1: [/'\x55b4' - /'\x55b5')
   ├── stats: [rows=16383, distinct(3)=16383, null(3)=0]
   │   histogram(3)=  0     0      16383     0
   │                <--- '\x55b4' ------- '\x55b5'
   └── cost: 17380.59
(7 rows)
```

**Environment:**
 - CockroachDB version 21.2 (development) cd27f55de43e6bb3107c3ff2c6df6cd7b2dff73b
 - Server OS: MacOS 11.5.1

### PR DESCRIPTION
**Pull request by mgartner**
Fixes #68346

Release note (performance improvement): The accuracy of histogram
calculations for BYTES types has been improved. As a result, the
optimizer should generate more efficient query plans in some cases.

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Thank you for looking at this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-Mgrcyb12pmgSaTW3Uf2:bqjvsdi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MgrbeAu-COTT2qlETu3:-MgrbeAu-COTT2qlETu4:b-7jny2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram.go#L864)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	switch typ.Family() {
> 	case types.StringFamily, types.BytesFamily, types.UuidFamily, types.INetFamily:
> 		return true
> 	}
> 	return false
> ```
</details>


To my untrained eye it looks like this list is missing a few more non-numeric type families, such as `CollatedStringFamily` and `JsonFamily`. Plus, I'm wondering if `ArrayFamily` and `TupleFamily` belong here as well? Hmm. I am new to this code, but it almost seems like `getRangeNonNumeric` should be the default range-calculation function, and `getRange` should only be called for special cases, since presumably every type's key encoding is bytewise ordered / comparable and at least somewhat bytewise "dense".

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[pkg/sql/opt/props/histogram.go, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MgrbeAu-COTT2qlETu3:-MhHHQA-8ocjQDzyPtA7:b-kxu2fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram.go#L864)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	switch typ.Family() {
> 	case types.StringFamily, types.BytesFamily, types.UuidFamily, types.INetFamily:
> 		return true
> 	}
> 	return false
> ```

To my untrained eye it looks like this list is missing a few more non-numeric type families, such as `CollatedStringFamily` and `JsonFamily`. Plus, I'm wondering if `ArrayFamily` and `TupleFamily` belong here as well? Hmm. I am new to this code, but it almost seems like `getRangeNonNumeric` should be the default range-calculation function, and `getRange` should only be called for special cases, since presumably every type's key encoding is bytewise ordered / comparable and at least somewhat bytewise "dense".
</blockquote></details>

I like the idea of swapping the default, and checking instead for the types that we explicitly support in `getRange`. Can these other non-numeric types be easily added in this PR? Otherwise, maybe open an issue for the other types that we're missing?

On a somewhat related note, I think we can also add `Interval`, `Enum`, and `Oid` as numeric types (in a separate PR...).
___
*[pkg/sql/opt/props/histogram_test.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MhHHm1u1QA4_wehNXoz:-MhHHm1u1QA4_wehNXp-:b-377uww) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram_test.go#L710)):*
> ```Go
> 	})
> 
> 	t.Run("bytes", func(t *testing.T) {
> ```

is all of this basically directly copied from above? if so, can you just have one copy that's used for both string and bytes?

**Review by mgartner — COMMENTED** [review]
Sorry for the delay in getting back to these comments. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-MjjRzOD5lufpx5XXFNF:brlj4s7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MgrbeAu-COTT2qlETu3:-MjjRcXcE4I_AeQqhE-D:bv38p10) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram.go#L864)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I like the idea of swapping the default, and checking instead for the types that we explicitly support in `getRange`. Can these other non-numeric types be easily added in this PR? Otherwise, maybe open an issue for the other types that we're missing?

On a somewhat related note, I think we can also add `Interval`, `Enum`, and `Oid` as numeric types (in a separate PR...).
</blockquote></details>

I've combined the three functions `getRange`, `getRangeNonNumeric` and `isNonNumeric` range into a single switch statement. I think this is more clear and avoids having to keep three functions in-sync.
___
*[pkg/sql/opt/props/histogram_test.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MhHHm1u1QA4_wehNXoz:-MjjRxSj1PmC7goGsDQq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram_test.go#L710)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is all of this basically directly copied from above? if so, can you just have one copy that's used for both string and bytes?
</blockquote></details>

Done.

**Review by mgartner — COMMENTED** [review]
I created #70320 to track calculating ranges for additional types.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-MjjS4Ii0KWwiWTSklp7:bt5mdwt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-Mk3aV5l8qQGia6u0UHf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MgrbeAu-COTT2qlETu3:-Mk3aEEg5PJF5avW4YeV:b-dk8r9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2ae5b2945da28b0d1088140f7818d53cfefb7d4/pkg/sql/opt/props/histogram.go#L864)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I've combined the three functions `getRange`, `getRangeNonNumeric` and `isNonNumeric` range into a single switch statement. I think this is more clear and avoids having to keep three functions in-sync.
</blockquote></details>

OK, thanks for the refactor and the filed issue.
___
*[pkg/sql/opt/props/histogram_test.go, line 647 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3R7WR1X4UZPT-LV-8:-Mk3R7WR1X4UZPT-LV-9:bbs5e7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d230794bb8309ec1e1a87c2f7157d6c402e7de9a/pkg/sql/opt/props/histogram_test.go#L647)):*
> ```Go
> 	})
> 
> 	t.Run("string/bytes", func(t *testing.T) {
> ```

nit: "/" is the subtest separator for `go test`, so this name creates a `TestFilterBucket/string/bytes` sub-sub-test instead of a `TestFilterBucket/<x>` sub-test. Maybe use `"string,bytes"` or some other symbol instead?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-Mk3d0dCE8JKfAAGPP-q:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/props/histogram.go, line 716 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3cNqP9IQZ2OfTA1dd:-Mk3cE11DI4OCT8VTuTn:b-wqg9id) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f3a670fc360251158bae37af2fa3a3a80cb827/pkg/sql/opt/props/histogram.go#L716)):*
> ```Go
> //
> func getRangesBeforeAndAfter(
> 	bucketLowerBound, bucketUpperBound, spanLowerBound, spanUpperBound tree.Datum, swap bool,
> ```

nit: I think we can get rid of the bucket v. span distinction to further clarify things. i.e. bucket -> before, span -> after
___
*[pkg/sql/opt/props/histogram.go, line 820 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3bi6l4DXzxjtpPM0-:-Mk3bi6l4DXzxjtpPM00:b-fcy8f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f3a670fc360251158bae37af2fa3a3a80cb827/pkg/sql/opt/props/histogram.go#L820)):*
> ```Go
> 		// For non-numeric types, convert the datums to encoded keys to
> 		// approximate the range. We utilize an array to reduce repetitive code
> 		// number of repetitive calls.
> ```

nit: "...to reduce repetitive code number of repetitive calls." is repetitive! :wink:

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 716 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3cNqP9IQZ2OfTA1dd:-MkIV7zq3qgWf2PhTOec:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f3a670fc360251158bae37af2fa3a3a80cb827/pkg/sql/opt/props/histogram.go#L716)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I think we can get rid of the bucket v. span distinction to further clarify things. i.e. bucket -> before, span -> after
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 820 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3bi6l4DXzxjtpPM0-:-MkIVG0wDFaM0FNxsLZc:b-9gwj7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/73f3a670fc360251158bae37af2fa3a3a80cb827/pkg/sql/opt/props/histogram.go#L820)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "...to reduce repetitive code number of repetitive calls." is repetitive! :wink: 
</blockquote></details>

:upside_down_face: 
___
*[pkg/sql/opt/props/histogram_test.go, line 647 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-Mk3R7WR1X4UZPT-LV-8:-MkIVT1W-Pwu5rc38Dxj:b-k2rwtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d230794bb8309ec1e1a87c2f7157d6c402e7de9a/pkg/sql/opt/props/histogram_test.go#L647)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: "/" is the subtest separator for `go test`, so this name creates a `TestFilterBucket/string/bytes` sub-sub-test instead of a `TestFilterBucket/<x>` sub-test. Maybe use `"string,bytes"` or some other symbol instead?
</blockquote></details>

Good catch. Fixed.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/props/histogram.go, line 666 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MkI_GJECLo62BgHXCxD:-MkI_GJF513rSmIccn6O:bb9zyr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0419139502d57c4d2e2e12dd45e056533273e61/pkg/sql/opt/props/histogram.go#L666)):*
> ```Go
> }
> 
> // getRangesBeforeAndAfter returns the size of the ranges before and after the
> ```

nit: update comment to remove references to bucket/span
___
*[pkg/sql/opt/props/histogram.go, line 736 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MkIZznfE1BSK14uFFgh:-MkIZznfE1BSK14uFFgi:b-rsw7ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0419139502d57c4d2e2e12dd45e056533273e61/pkg/sql/opt/props/histogram.go#L736)):*
> ```Go
> 	// TODO(rytaft): handle more types here.
> 	// Note: the calculations below assume that bucketLowerBound is inclusive and
> 	// Span.PreferInclusive() has been called on the span.
> ```

nit: update comment (just say all bounds are inclusive)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 666 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MkI_GJECLo62BgHXCxD:-MkJHEXe7EALO9i1Ph8F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0419139502d57c4d2e2e12dd45e056533273e61/pkg/sql/opt/props/histogram.go#L666)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update comment to remove references to bucket/span
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 736 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-MkIZznfE1BSK14uFFgh:-MkJHVl51pXeH-fGWoYD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0419139502d57c4d2e2e12dd45e056533273e61/pkg/sql/opt/props/histogram.go#L736)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update comment (just say all bounds are inclusive)
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68740#-:-MkO6QWZ6RjpBeaFImUY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
