### PR TITLE
storage: process Raft snapshots on the new raftSnapshotQueue

### LINKED ISSUE #12238: storage: revisit Raft log truncation and Raft snapshots
In normal operation, all of the replicas for a range are close to the commit index and raft log truncation deletes unnecessary state. When one replica falls too far behind, the raft log queue will decide to truncate the raft log for the range in such a way that will force that replica to be "caught up" via a snapshot. Once this occurs, there is not much point in keeping that original replica as part of the range as it no longer contributes to the Range quorum. 

Raft-initiated snapshots involve a decent amount of complexity in the code (i.e. `Replica.mu.{outSnap,outSnapDone}`). As an alternative to that complexity, we could replace the Raft related snapshot code with a small bit of code to enqueue the replica in the replicate queue when a Raft snapshot is requested. I think this would involve lying to Raft to indicate that the snapshot was generated and then having the replicate queue remove any replica which is in state `ProgressStateSnapshot`. In addition to the code simplification, this approach would have the benefit of proactively rebalancing active ranges away from slow nodes. There is some additional overhead to going through the Raft group configuration change to remove a replica and add a new one, but I think that will be lost in the noise. 

There is some exploration to do here to make sure I'm not missing anything. @bdarnell please point out the flaws in this idea.

Cc @cockroachdb/stability

### PR DESCRIPTION
**Pull request by petermattis**
Add a new raftRepairQueue which is used to serialize the generation and
sending of Raft snapshots. In addition to serializing the sending of Raft
snapshots, the raftRepairQueue allowed for the removal of a bunch of
complexity surrounding the raft.Storage interface. Replica.Snapshot now
returns a placeholder instead of actually generating a snapshot. If a
raft.Ready contains a snapshot to send, the replica is enqueued on the Raft
repair queue. Replica.mu.{outSnap,outSnapDone} are thus no longer
necessary.

Removed BenchmarkReplicaSnapshot which wasn't benchmarking anything useful.
Even before this change, Replica.Snapshot was only taking a RocksDB
snapshot and doing a small bit of work.

Fixes #12238

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12686)

### CODE REVIEW

**Comment by petermattis** [comment]
I'm mildly surprised all of the tests pass (i.e. this was easier than expected). Before merging, I'm going to experiment with this on `blue` to see if it improves performance during node recovery.

**Comment by BramGruneir** [comment]
:lgtm: This is a LOT cleaner.  Makes all snapshotting a lot easier to follow and hopefully easier to measure as well.

---

Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_repair_queue.go, line 15 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hL3xM55gCKhKN8W0g:-K_hL3xNM1qN0wMytvXI:baez50f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> //
> // Author: Ben Darnell
> ```

Was this by Ben?  We really should just remove all author tags anyway.

---

*[pkg/storage/replica.go, line 4164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hOzXTXyNufXEcgk2y:-K_hOzXTXyNufXEcgk2z:bw6ipjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica.go#L4164)):*
> ```Go
> 	}
> 
> 	if r.store.cfg.TestingKnobs.DisablePeriodicGossips {
> ```

Was this change supposed to be part of this pr?  Seems out of place.

---

*[pkg/storage/replica_command.go, line 3280 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hQ06MY2yQ65zR2rLw:-K_hQ06MY2yQ65zR2rLx:b-of3pxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica_command.go#L3280)):*
> ```Go
> }
> 
> func (r *Replica) sendSnapshot(
> ```

This is just code movement right?

---

*[pkg/storage/store.go, line 1355 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hQhPn-B0jsxvkTaD8:-K_hQhPn-B0jsxvkTaD9:b-8eid00) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L1355)):*
> ```Go
> // Replica.maybeGossipSystemConfig and Replica.maybeGossipNodeLiveness.
> func (s *Store) maybeGossipSystemData(ctx context.Context) error {
> 	if s.cfg.TestingKnobs.DisablePeriodicGossips {
> ```

This seems out of place in this PR.  Or at least in this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-:-K_hSOVYkkZ9O4ARCgXJ:b-5aj9zv)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_repair_queue.go, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iG_bcYzowPotWas74:-K_iG_bcYzowPotWas75:bws3vr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L39)):*
> ```Go
> 	// raftRepairQueueTimerDuration is the duration between Raft repair of queued
> 	// replicas.
> 	raftRepairQueueTimerDuration = 0 // zero duration to process replication greedily
> ```

s/replication/repair/

---

*[pkg/storage/raft_repair_queue.go, line 41 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iGc9hs4NdACG3xgsp:-K_iGc9hs4NdACG3xgsq:bpmp6u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L41)):*
> ```Go
> 	raftRepairQueueTimerDuration = 0 // zero duration to process replication greedily
> 
> 	raftSnapshotPriority float64 = 10000
> ```

There's no need for a constant here; priorities only matter if `shouldQueue` can return more than one value. Just use zero for this one. 

---

*[pkg/storage/raft_repair_queue.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iGkySxs-zhYygN0ze:-K_iGkySxs-zhYygN0zf:bafbwc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L44)):*
> ```Go
> )
> 
> // raftRepairQueue manages a queue of replicas which may need to add an
> ```

s/add an additional replica/catch a replica up with a snapshot/

`raftSnapshotQueue` might be a better name, to distinguish from the replication queue (which we sometimes refer to as "repair")

---

*[pkg/storage/raft_repair_queue.go, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLxKdTOhIFawuEzSr:-K_iLxKdTOhIFawuEzSs:b-pweref) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L62)):*
> ```Go
> 			// The Raft leader (which sends Raft snapshots) may not be the
> 			// leaseholder. Operating on a replica without holding the lease is the
> 			// reason Raft repair cannot be performed by the replicateQueue.
> ```

We could fold this into the replicate queue by setting needsLease to false there but adding a check that we hold the lease for every operation but raft snapshots. I think that's messier overall but it would let us get rid of the store snapshot semaphore (since the replicate queue would then be the only goroutine that ever generates snapshots). 

---

*[pkg/storage/raft_repair_queue.go, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iJJmPnmzkvYD4u1cu:-K_iJJmPnmzkvYD4u1cv:b-7sc9e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L77)):*
> ```Go
> 	ctx context.Context, now hlc.Timestamp, repl *Replica, sysCfg config.SystemConfig,
> ) (shouldQ bool, priority float64) {
> 	// If a follower needs a snapshot, enqueue at the highest priority.
> ```

Every time a snapshot needs to be sent, `raftRepairQueue.Add` will be called. Enqueuing replicas from `shouldQueue` (which is used by the background scanner`) is unnecessary and might lead us to attempt to send the same snapshot twice. I think `shouldQueue` should unconditionally return `false` for this queue (in which case there's very little value in having this attached to the scanner at all, except for a standardized idiom for metrics and logging)

---

*[pkg/storage/raft_repair_queue.go, line 79 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iHi5VmSKm-6wxep05:-K_iHi5VmSKm-6wxep06:b-hv0nhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L79)):*
> ```Go
> 	// If a follower needs a snapshot, enqueue at the highest priority.
> 	if status := repl.RaftStatus(); status != nil {
> 		for _, p := range status.Progress {
> ```

Maybe comment that `status.Progress` is only populated on raft leaders.

---

*[pkg/storage/raft_repair_queue.go, line 104 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iHzThmB0ZVjLmvREf:-K_iHzThmB0ZVjLmvREg:bso2yyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L104)):*
> ```Go
> 				// Enqueue this replica again to see if there are more repairs to be
> 				// made.
> 				rq.MaybeAdd(repl, rq.clock.Now())
> ```

I don't think this will ever do anything useful - we process all the followers in this loop, and after we've completed the snapshot we've reset their progress state and they won't go back to ProgressStateSnapshot until raft has communicated with that follower and decided its out of date again. Remove this and let the replica be requeued naturally if need be. 

---

*[pkg/storage/replica.go, line 3100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iJ0bzUH7CsJw1lQzH:-K_iJ0c-fUl9pNDGUM2I:bz229ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica.go#L3100)):*
> ```Go
> 
> 	// Raft-initiated snapshots are handled by the Raft repair queue.
> 	if !raft.IsEmptySnap(msg.Snapshot) {
> ```

I don't think it really matters, but I'd use `msg.Type == raftpb.MsgSnap` instead of `!IsEmptySnap` here. 

---

*[pkg/storage/replica_raftstorage.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iKE3pFNhp7y5dZAUQ:-K_iKE3pFNhp7y5dZAUR:b-abcpy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica_raftstorage.go#L273)):*
> ```Go
> // replica lock is held. Note that the returned snapshot is a placeholder and
> // does not contain any of the replica data. The snapshot is actually generated
> // (and sent) by the replicate queue.
> ```

s/replicate/raft repair/

---

*[pkg/storage/replica_raftstorage.go, line 303 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iKng1Cnw69F-qrHF9:-K_iKng1Cnw69F-qrHFA:bqb4l31) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica_raftstorage.go#L303)):*
> ```Go
> 			"not generating %s snapshot because replica is too large: %d > 2 * %d",
> 			snapType, size, maxBytes)
> 		return &OutgoingSnapshot{}, raft.ErrSnapshotTemporarilyUnavailable
> ```

This error is no longer returned to raft (from the `Snapshot` method), so it doesn't have to be raft's special error constant. We could replace it with our own "snapshotTooLargeError" (or just an `Errorf` since I think the test is the only thing that cares about the details of this error now)

---

*[pkg/storage/store.go, line 2200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLGguFM-IxOQD9to2:-K_iLGguFM-IxOQD9to3:b-ekqf0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L2200)):*
> ```Go
> 
> // AcquireRaftSnapshot blocks waiting for the an available snapshot slot. The
> // caller MUST call ReleaseRaftSnapshot.
> ```

And the caller must be in a stopper task so the store cannot be shut down while we're waiting (or we need to do this in a `select` and bring back the return value).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-:-K_iMSNZu1VGdzm_ynfb:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_repair_queue.go, line 82 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hiqwfXa7ExGi9qTJ8:-K_hiqwfXa7ExGi9qTJ9:b564vwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L82)):*
> ```Go
> 			if p.State == raft.ProgressStateSnapshot {
> 				if log.V(2) {
> 					log.Infof(ctx, "%s raft snapshot needed, enqueuing", repl)
> ```

better to annotate the context, i think

---

*[pkg/storage/replica_raftstorage.go, line 326 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hiNltQ7Wq0I5N4c9d:-K_hiNltQ7Wq0I5N4c9e:b-cfi9ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica_raftstorage.go#L326)):*
> ```Go
> 	log.Event(ctx, "snapshot generated")
> 	r.store.metrics.RangeSnapshotsGenerated.Inc(1)
> 	return &snapData, nil
> ```

this might want to be a value now that we're not storing it on the replica.

---

*[pkg/storage/store.go, line 3402 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_gQwSPg17Tz2IeGTcn:-K_gQwSPg17Tz2IeGTco:bqyga1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L3402)):*
> ```Go
> 
> 	s.scheduler.Start(s.stopper)
> 	s.stopper.RunWorker(func() {
> ```

`s.stopper.RunWorker(s.scheduler.Wait)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Comment by petermattis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[pkg/storage/store.go, line 2200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLGguFM-IxOQD9to2:-K_jARBEui38vgBQGy_S:btmexig) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L2200)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I was wondering if we should just get rid of this. Allowing 1 snapshot the replicate queue and 1 for the Raft snapshot queue seems reasonable. Thoughts?
</blockquote></details>

I've add a `ctx` argument and moved the usage of `{Acquire,Release}RaftSnapshot` to `Replica.sendSnapshot`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Comment by petermattis** [comment]
Review status: 12 of 14 files reviewed at latest revision, 16 unresolved discussions.

---

*[pkg/storage/replica_raftstorage.go, line 326 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_hiNltQ7Wq0I5N4c9d:-K_jCRwqplIr0x695M6v:b-1n6rbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/replica_raftstorage.go#L326)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

It'd still have a pointer receiver, wouldn't it? Anyway, perhaps a simple comment about this being a potential performance implication.
</blockquote></details>

How is this a performance implication? The 1 allocation will be lost in the noise of the rest of the work that needs to be performed for the snapshot.

---

*[pkg/storage/store.go, line 2200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLGguFM-IxOQD9to2:-K_jHezA7i3vrSQUofWv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L2200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Might be better for this method to return an error rather than making the caller do it via `ctx.Err()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Comment by petermattis** [comment]
This seems to be working fine on test clusters.

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 2200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLGguFM-IxOQD9to2:-K_uPQ7ZeDjjyUTqTJrk:b-l0m866) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L2200)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yeah, allowing two snapshots seems reasonable (especially since the sending side is cheap thanks to streaming snapshots). I was thinking about the time we changed from a mutex to a semaphore and we were skeptical that we'd ever want to raise the limit above 1, but now I think it would be fine to allow 2 and get rid of this mechanism completely. 

---

*[pkg/storage/raft_repair_queue.go, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iJJmPnmzkvYD4u1cu:-K_uQ-mygegsGcWh7jND:bx9u1ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L77)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

How would we attempt to send the same snapshot twice? When `raftRepairQueue.process` is called, we send the snapshot and on success the follower will be moved to `ProgressStateProbe`. I wanted this background process as well to handle situations in which the queue is full or sending the Raft snapshot fails with a temporary error (i.e. the snapshot was rejected). I'm not dealing with the temporary `preemptiveSnapshotError` yet, but that was the thought here.
</blockquote></details>

I was thinking a double-send might be possible if the scanner called shouldQueue while a snapshot send was in progress (since we don't change the progress state until the end and we don't hold a lock the whole time), but I'm not sure if the locking in the scanner would allow that. 

If the queue is full, then the scanner is an awfully slow way to recover - we won't try again for an average of 5 minutes. I think if we can't add the range to the queue then we need to call ReportSnapshotStatus with an error so that raft will trigger a retry. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/storage/store.go, line 2200 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iLGguFM-IxOQD9to2:-Ka2iEAmZm2fEO2t49GD:b-umues9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/store.go#L2200)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, allowing two snapshots seems reasonable (especially since the sending side is cheap thanks to streaming snapshots). I was thinking about the time we changed from a mutex to a semaphore and we were skeptical that we'd ever want to raise the limit above 1, but now I think it would be fine to allow 2 and get rid of this mechanism completely. 
</blockquote></details>

Done. See https://github.com/cockroachdb/cockroach/pull/12778.

---

*[pkg/storage/raft_repair_queue.go, line 77 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686#-K_iJJmPnmzkvYD4u1cu:-Ka2iIzoF2AyrGmu5qEG:bp9ta9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e54a9f25578464f420acda93a94678c955e98e/pkg/storage/raft_repair_queue.go#L77)):*
`raftSnapshotQueue.process` is serialized by the single goroutine used for processing a queue. Even if a replica is queued unnecessarily, we'll only send the Raft snapshot once.

> If the queue is full, then the scanner is an awfully slow way to recover - we won't try again for an average of 5 minutes. I think if we can't add the range to the queue then we need to call ReportSnapshotStatus with an error so that raft will trigger a retry.

Or perhaps we should make the queue size larger. Raft snapshots take a handful of seconds to apply on the remote side. Even on the optimistic end, if we're processing 1 Raft snapshot per second, a queue size of 1000 would be sufficient to avoid inadvertent queue idleness. 

The `priorityQueue` used inside `queue` orders based purely on priority. I wonder what it does when all of the priorities are equal. It isn't at all clear to me that the newest item wouldn't be added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12686)*

**Pull request merged**
