### PR TITLE
ui: new sql activity page

### PR DESCRIPTION
**Pull request by maryliag**
New SQL Activity page that includes Sessions, Statement
and Transaction pages.
Clear Stats action link moved to the top of Transactions and Statements page.

Partially addresses #66052
Session Details and Statement Details replace the full page. A following PR will make Transaction Details have the same behaviour.

https://www.loom.com/share/655914eba8ed4c449dad46fc786f17eb

Screen Shot 2021-10-14 at 4 21 41 PM
Screen Shot 2021-10-14 at 4 21 49 PM
Screen Shot 2021-10-14 at 4 21 57 PM

Release note (ui change): Session, Statement and Transaction pages
are now grouped inside the new SQL Activity page.

### CODE REVIEW

**Review by matthewtodd — CHANGES_REQUESTED** [review]
Excellent use of Loom! 🎉

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-:-Mm-ZM5XCCVHBpGVua0R:bni5r7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm-a3oX-wcrxWa74bff:-Mm-a3oX-wcrxWa74bfg:bkb6ndr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1875a0d78c57c484e01452f9da60e8d6817cde/pkg/ui/workspaces/db-console/src/app.tsx#L188)):*
> ```XML
>                   path={`/sql-activity/:${tabAttr}`}
>                   component={SQLActivityPage}
>                 />
> ```

Do we want to remove / redirect the old routes, too?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm-a3oX-wcrxWa74bff:-Mm-brqM8EvY8k_T-hjx:b-ibmtg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1875a0d78c57c484e01452f9da60e8d6817cde/pkg/ui/workspaces/db-console/src/app.tsx#L188)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Do we want to remove / redirect the old routes, too?
</blockquote></details>

oh yeah, I forgot to do that!

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm-a3oX-wcrxWa74bff:-Mm-dCV73naqZTjCqqjk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad1875a0d78c57c484e01452f9da60e8d6817cde/pkg/ui/workspaces/db-console/src/app.tsx#L188)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

oh yeah, I forgot to do that!
</blockquote></details>

Done

**Review by Annebirzin — APPROVED** [review]
Looks great! And thanks for the Loom video!

**Review by Azhng — COMMENTED** [review]
:fire: :fire: :fire:

> Reviewed 10 of 25 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-:-MmEjzRl5yEZfgzEewv2:bpfv5hr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivity/clearStats.tsx, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEgGTz63Sh3NTZO_ML:-MmEgGTz63Sh3NTZO_MM:b-i05nt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/sqlActivity/clearStats.tsx#L42)):*
> ```XML
>       break;
>   }
>   const toolTipText = `${statsType} statistics are aggregated once an hour and organized by the start time. 
> ```

The hourly aggregation is a default setting, if user change the cluster setting this no longer holds true. Should we word it somewhat differently to reflect that ?
___
*[pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEiX3f5uaz3k5o6XXU:-MmEiX3f5uaz3k5o6XXV:bjwr0be) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx#L19)):*
> ```XML
> const { statistic, countTitle } = statisticsClasses;
> 
> interface TableStatistics {
> ```

while we are on this, is it possible that we can rename this component? `TableStatistics` means something really different and it's outside the scope of the SQL Stats. 

Reading through the component code, it seems like this component mostly handles the text we display when the filter is active vs. when the active is non active. So perhaps `FilterResultRow` or `FilterResultStats` or something like that ? 
___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm9YTIP8jU0zW7KUCWB:-Mm9YTIQ9ATqyzZbs2Ty:b-khl5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L24)):*
> ```XML
> const { TabPane } = Tabs;
> 
> const SQLActivityPage = (props: any) => {
> ```

I think we can constraint the type of `props` further here using union type, right?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/sqlActivity/clearStats.tsx, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEgGTz63Sh3NTZO_ML:-MmIoJteDG3IhSgkJks0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/sqlActivity/clearStats.tsx#L42)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The hourly aggregation is a default setting, if user change the cluster setting this no longer holds true. Should we word it somewhat differently to reflect that ?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEiX3f5uaz3k5o6XXU:-MmIm9fxBM4UcxiEM_Ik:bvmljxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx#L19)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

while we are on this, is it possible that we can rename this component? `TableStatistics` means something really different and it's outside the scope of the SQL Stats. 

Reading through the component code, it seems like this component mostly handles the text we display when the filter is active vs. when the active is non active. So perhaps `FilterResultRow` or `FilterResultStats` or something like that ? 
</blockquote></details>

This component is the statistics of the table (it just happens that the table itself is about statistics), meaning how many results in total, how many being displayed, how many pages, the columns selected, etc. We had the last cleared info here too before it was removed, changing to such a specific name using "filter" is not representative of what it is and also if we decide to add more things in the future will we keep renaming to a really long name to represent everything on it.
___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm9YTIP8jU0zW7KUCWB:-MmIoH-E5C-haZ-kEmug:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L24)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think we can constraint the type of `props` further here using union type, right? 
</blockquote></details>

Done

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEiX3f5uaz3k5o6XXU:-MmJ2uN_EBspBQ3hPkRB:bxzhrtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx#L19)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

This component is the statistics of the table (it just happens that the table itself is about statistics), meaning how many results in total, how many being displayed, how many pages, the columns selected, etc. We had the last cleared info here too before it was removed, changing to such a specific name using "filter" is not representative of what it is and also if we decide to add more things in the future will we keep renaming to a really long name to represent everything on it.
</blockquote></details>

I see. Let's add a quick comment here to clarify that, I got really confused when I saw this name :sweat_smile:, because I couldn't seem to understand how is this related to the SQL Table statistics 
___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm9YTIP8jU0zW7KUCWB:-MmJ4jx-28Z5NYAxLE4H:b-s0kher) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L24)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Nice! Actually, quick question here, it seems like `props` is not being propagated further down the JSX tree in the `return` block, so how does React propagate the `props` here?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmEiX3f5uaz3k5o6XXU:-MmJ9Yh9ETYPzUMAg5jG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx#L19)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I see. Let's add a quick comment here to clarify that, I got really confused when I saw this name :sweat_smile:, because I couldn't seem to understand how is this related to the SQL Table statistics 
</blockquote></details>

Done
___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm9YTIP8jU0zW7KUCWB:-MmJ9b1y90WJED4_Yi7h:bq85p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L24)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Nice! Actually, quick question here, it seems like `props` is not being propagated further down the JSX tree in the `return` block, so how does React propagate the `props` here? 
</blockquote></details>

I'm using the "Connected" components, so I don't need to pass the props explicitly, but they're being passed there, it would be equivalent of doing `<TransactionsPage {...props} />` instead of `<TransactionsPageConnected />` for example

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-Mm9YTIP8jU0zW7KUCWB:-MmJCQkq1ZXvzpE9K3An:b-pdwshu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0111c56251595fe3a11999d7b854420b3955fb9/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L24)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm using the "Connected" components, so I don't need to pass the props explicitly, but they're being passed there, it would be equivalent of doing `<TransactionsPage {...props} />` instead of `<TransactionsPageConnected />` for example
</blockquote></details>

Oh I see. That makes sense. So, does that means the `props` required for `SessionPage`/`TransationPage`/`StatementPage` are actually not included in the `SQLActivityPage` , since they have already being connected to the Redux reducers?

**Review by Azhng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx, line 32 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/71325#-MmJRm2P6JKV3zTZoFA_:-MmJRm2P6JKV3zTZoFAa:b64kiaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/55f9362667077daf5e3be91eb9d1d8dbb24cf394/pkg/ui/workspaces/db-console/src/views/sqlActivity/sqlActivityPage.tsx#L32)):*
> ```XML
>   StatementsPageProps;
> 
> const SQLActivityPage = (props: SQLActivityProps) => {
> ```

Retracting my previous comment. Chatted with Marylia offline and the type intersection for the Props type was actually incorrect, since component-specific props are not stored at the `SQLActivityProps` level.

**Review by matthewtodd — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71325)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Pull request merged**
