### PR TITLE
misc: cleaning out my TODOs

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8161)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1dvYZphRj93rmrTbI:-1791303802) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
> ```Go
> 	case *parser.DInt:
> 		// Start at offset 4 because `putInt32` clobbers the first 4 bytes.
> 		// TODO(tamird): @petermattis sez this allocates. Investigate.
> ```

Refreshing my memory here. `Append{Int,Uint}` calls `formatBits` which formats into a byte array which escapes to the heap. At least it escaped the last time I checked. Perhaps go1.7 is different.

---

*[sql/pgwire/v3.go, line 778 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1ckwUAB_KeqfkMbC2:-KO1ckwUAB_KeqfkMbC3:-1542470298) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2433bde6f47ef5512b68e3992ff93590be520a6/sql/pgwire/v3.go#L778)):*
> ```Go
> 			// Send CommandComplete.
> 			tag = append(tag, ' ')
> 			tag = strconv.AppendUint(tag, uint64(len(result.Rows)), 10)
> ```

I believe `strconv.AppendUint` used to perform an allocation. Did that change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-:-KO1e7iNHfUXoIsZ7kqJ:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1f-D7PY7mcatjw-dd:843777140) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Refreshing my memory here. `Append{Int,Uint}` calls `formatBits` which formats into a byte array which escapes to the heap. At least it escaped the last time I checked. Perhaps go1.7 is different.
</details>
I spent this morning trying to figure out what inefficiency of that code you were referring to when this TODO was written. So you're right that `formatBits` writes into a byte array, but it doesn't escape to the heap unless there's not sufficient space in the destination buffer. Relevant code is [here](https://github.com/golang/go/blob/master/src/strconv/itoa.go#L138) and hasn't really changed since it was written.

I just re-convinced myself by profiling the stdlib's benchmarks and indeed, given a sufficiently large input buffer, `Append{Int,Uint}` do not allocate.

---

*[sql/pgwire/v3.go, line 778 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1ckwUAB_KeqfkMbC2:-KO1nyFEWvIs_cy9N3H4:747150048) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2433bde6f47ef5512b68e3992ff93590be520a6/sql/pgwire/v3.go#L778)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I believe `strconv.AppendUint` used to perform an allocation. Did that change?
</details>
Explained above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1qHuDcJI1iWyfZ7iR:-2075291197) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I spent this morning trying to figure out what inefficiency of that code you were referring to when this TODO was written. So you're right that `formatBits` writes into a byte array, but it doesn't escape to the heap unless there's not sufficient space in the destination buffer. Relevant code is [here](https://github.com/golang/go/blob/master/src/strconv/itoa.go#L138) and hasn't really changed since it was written.
> 
> I just re-convinced myself by profiling the stdlib's benchmarks and indeed, given a sufficiently large input buffer, `Append{Int,Uint}` do not allocate.
</details>
https://github.com/golang/go/blob/master/src/strconv/itoa.go#L138 was causing `a` to escape to the heap in previous Go versions. `--memprofile mem.prof --memprofilerate=1` showed this in benchmarks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1qsvKeqF8scuJoNLi:804147281) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> https://github.com/golang/go/blob/master/src/strconv/itoa.go#L138 was causing `a` to escape to the heap in previous Go versions. `--memprofile mem.prof --memprofilerate=1` showed this in benchmarks.
</details>
How can you tell that `a` is escaping rather than `d` being allocated because `dst` is too small?

I just tested this with Go 1.6 and also saw zero allocations. Note that I made this change to the go sources:
```diff
diff --git a/src/strconv/itoa_test.go b/src/strconv/itoa_test.go
index 48dc03e..7341f65 100644
--- a/src/strconv/itoa_test.go
+++ b/src/strconv/itoa_test.go
@@ -135,7 +135,7 @@ func BenchmarkFormatInt(b *testing.B) {
 }
 
 func BenchmarkAppendInt(b *testing.B) {
-	dst := make([]byte, 0, 30)
+	dst := make([]byte, 0, 65)
 	for i := 0; i < b.N; i++ {
 		for _, test := range itob64tests {
 			AppendInt(dst, test.in, test.base)
@@ -152,7 +152,7 @@ func BenchmarkFormatUint(b *testing.B) {
 }
 
 func BenchmarkAppendUint(b *testing.B) {
-	dst := make([]byte, 0, 30)
+	dst := make([]byte, 0, 65)
 	for i := 0; i < b.N; i++ {
 		for _, test := range uitob64tests {
 			AppendUint(dst, test.in, test.base)

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1uKI96d5fJOMMpYzc:-1386272473) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> How can you tell that `a` is escaping rather than `d` being allocated because `dst` is too small?
> 
> I just tested this with Go 1.6 and also saw zero allocations. Note that I made this change to the go sources:
> ```diff
> diff --git a/src/strconv/itoa_test.go b/src/strconv/itoa_test.go
> index 48dc03e..7341f65 100644
> --- a/src/strconv/itoa_test.go
> +++ b/src/strconv/itoa_test.go
> @@ -135,7 +135,7 @@ func BenchmarkFormatInt(b *testing.B) {
>  }
>  
>  func BenchmarkAppendInt(b *testing.B) {
> -	dst := make([]byte, 0, 30)
> +	dst := make([]byte, 0, 65)
>  	for i := 0; i < b.N; i++ {
>  		for _, test := range itob64tests {
>  			AppendInt(dst, test.in, test.base)
> @@ -152,7 +152,7 @@ func BenchmarkFormatUint(b *testing.B) {
>  }
>  
>  func BenchmarkAppendUint(b *testing.B) {
> -	dst := make([]byte, 0, 30)
> +	dst := make([]byte, 0, 65)
>  	for i := 0; i < b.N; i++ {
>  		for _, test := range uitob64tests {
>  			AppendUint(dst, test.in, test.base)
> 
> ```
> 
</details>
If `a` is escaping, `go tool pprof` reports an allocation on the line that declares `a`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1upbcinDd4eFfpcNo:94206985) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> If `a` is escaping, `go tool pprof` reports an allocation on the line that declares `a`. 
</details>
Oh. What version of Go did you observe that with?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO1wbkzTsIinwoxyMN9:1223592237) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Oh. What version of Go did you observe that with?
</details>
I don't recall. If you're not seeing anything now when mem profiling with `--memprofilerate=1`, then this is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by tamird** [comment]
Review status: 3 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types.go, line 143 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161#-KO1dvYZphRj93rmrTbH:-KO280DIU60tizGv6zXr:-1574111208) ([raw file](https://github.com/cockroachdb/cockroach/blob/cff9e5a484ccaa34aa5d988af0df582a45b9b62b/sql/pgwire/types.go#L143)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I don't recall. If you're not seeing anything now when mem profiling with `--memprofilerate=1`, then this is fine.
</details>
I'm a little concerned about this. I tried to replicate your result (allocation on the line where `a` is declared) with every Go version from 1.4 to 1.7 and none of them produce that result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8161)*

**Comment by tamird** [comment]
Well, I guess I'll merge this for now. @petermattis let me know if you're able to look into the behaviour of `Append{Int,Uint}`.

**Pull request merged**
