### PR TITLE
The max tpmC rate  is 12.605x the number of warehouses

### PR DESCRIPTION
**Pull request by petermattis**
Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Noticed this in passing. This is the number we used in the tpcc spreadsheet. I can't recall where the number comes from. Cc @arjunravinarayan and @jordanlewis for verification.

**Comment by nvanbenschoten** [comment]
The max tpmC rate comes from a combination of the number of workers per warehouse and the maximum fraction of the time that each worker can spend on newOrder txns given the default mix and the default keying and thinking times.

The default mix is 
```
newOrder=45,payment=43,orderStatus=4,delivery=4,stockLevel=4
```

Our default is actually a little bit different than this. I'm not sure why. @jordanlewis do you?

The default [keying and thinking times](https://github.com/cockroachdb/cockroach/blob/4f21f583432bef4e5f9d634854248b835945d059/pkg/workload/tpcc/worker.go#L60) are in `worker.go`. The max tpmC rate then appears as the runtime of each txn approaches 0.

```
num workers per warehouse = 10
"decks" per worker = 1
new order txns complete in a deck = 45
time to complete all txns in a deck = 45*(18+12) + 43*(3+12) + 4*(2+10) + 4*(2+5) + 4*(2+5) = 2099 seconds

new order txns complete per warehouse per time = 10 * 45 / (2099 / 60) = 12.8632 tpmC per warehouse
```

**Review by nvb — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
> Our default is actually a little bit different than this.

Was the point to reduce the variance in results for tests shorter than the time it takes to complete a single deck (~35 minutes)?

**Comment by jordanlewis** [comment]
We use the "deck" method described in the following paragraph. There are 2 ways to regulate the mix that are permitted by the spec - one that requires a percentage-based method that's continually checked to ensure that the mix is meeting the spec, and a simpler one that takes a uniformly random pass through a deck of cards with 10 cards for each of the two common txns, and 1 each for the other three txns.

image

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28010)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28010#-LIkeHMe2UnyILI_X2kM:-LIkeHMe2UnyILI_X2kN:b24aftq) ([raw file](https://github.com/cockroachdb/cockroach/blob/630cef499499c97e5821f38d5dce7ba2710521ef/pkg/cmd/roachtest/tpcc.go#L415)):*
> ```Go
> 			}
> 			// Determine the fraction of the maximum possible tpmC realized.
> 			maxTpmC := 12.86 * float64(warehouses)
> ```

So should this be 12.8632?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28010)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28010#-LIkeHMe2UnyILI_X2kM:-LIkgPQG1UFghrO5QnTd:bukt4jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/630cef499499c97e5821f38d5dce7ba2710521ef/pkg/cmd/roachtest/tpcc.go#L415)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

So should this be 12.8632?
</blockquote></details>

Given that out mix is `newOrder=10,payment=10,orderStatus=1,delivery=1,stockLevel=1`, it should actually be somewhere around `12.605`. I don't have strong opinions though. We're already accepting some loss of precision to reduce the number of iterations of this search loop anyway.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28010)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 415 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28010#-LIkeHMe2UnyILI_X2kM:-LIklaxkDhrv-nnarnPR:b-ly9ift) ([raw file](https://github.com/cockroachdb/cockroach/blob/630cef499499c97e5821f38d5dce7ba2710521ef/pkg/cmd/roachtest/tpcc.go#L415)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Given that out mix is `newOrder=10,payment=10,orderStatus=1,delivery=1,stockLevel=1`, it should actually be somewhere around `12.605`. I don't have strong opinions though. We're already accepting some loss of precision to reduce the number of iterations of this search loop anyway.
</blockquote></details>

I agree that the loss of precision in the search loop likely overwhelms this. I switched to 12.605 and added a comment explaining how that number is derived. 

It is sort of suspicious that our mix results in a lower max-tpmC than the default mix.

**Comment by jordanlewis** [comment]
> It is sort of suspicious that our mix results in a lower max-tpmC than the default mix.

Yeah, but this is explicitly the mix that they recommend using. I don't really understand why they even mention the percentages-based mix when they also recommend the deck method which has slightly different resultant percentages.

**Review by nvb — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=nvanbenschoten

**Pull request merged**
