### PR TITLE
migrations: Migration that adds zone configs for system ranges

### PR DESCRIPTION
**Pull request by a-robinson**
Adds a migration for @a6802739's original PR, #12335, and fixes a couple small issues with it. We may actually want to remove the part of the original commit that adds the new zone configs during cluster bootstrap, since as @bdarnell has repeatedly noted we'd prefer all clusters, both old and new, to have their configurations added in the same way.

@a6802739 @petermattis

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12513)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 3 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/cli/zone.go, line 170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTL0wTskt3RiAJcpja:-KZTL0wTskt3RiAJcpjb:b-k3lwti) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L170)):*
> ```Go
> 	path := []sqlbase.ID{keys.RootNamespaceID}
> 	str := strings.Join(names, ".")
> 	switch str {
> ```

`str` isn't needed

---

*[pkg/cli/zone.go, line 171 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTL5OX3uyFdfl1Thdc:-KZTL5OX3uyFdfl1Thdd:b5a0adp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L171)):*
> ```Go
> 	str := strings.Join(names, ".")
> 	switch str {
> 	case ".default":
> ```

can we use constants for all of these? they sure get repeated a lot.

---

*[pkg/cli/zone.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLOA9IHPU0MqiyKMg:-KZTLOA9IHPU0MqiyKMh:b-is1f3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L351)):*
> ```Go
> 	sort.Strings(output)
> 	// Ensure the default zone is always printed first.
> 	zoneNames := map[sqlbase.ID]string{
> ```

perhaps this can be used in `runGetZone`?

EDIT: I see this changed to a slice in r3 but I think it should be a map and used basically everywhere.

---

*[pkg/cli/zone.go, line 359 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLF1h03Euo8mIAXCI:-KZTLF1h03Euo8mIAXCJ:b5eazlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L359)):*
> ```Go
> 	for id, name := range zoneNames {
> 		if _, ok := zones[id]; ok {
> 			fmt.Printf("%s\n", name)
> ```

nit: `Println(name)`?

---

*[pkg/cli/zone.go, line 409 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLSxtrbGYrHXCiE70:-KZTLSxtrbGYrHXCiE71:b-eybw7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L409)):*
> ```Go
> 	id := path[len(path)-1]
> 	switch id {
> 	case keys.RootNamespaceID, keys.MetaSystemID, keys.IdentifierSystemID, keys.NormalSystemID:
> ```

also should use the map above

---

*[pkg/config/config.go, line 401 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLdOdh2b_a054y8IT:-KZTLdOdh2b_a054y8IU:b-l41gpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/config/config.go#L401)):*
> ```Go
> 		objectID = keys.RootNamespaceID
> 	}
> 	if bytes.HasPrefix(key, keys.Meta1Prefix) || bytes.HasPrefix(key, keys.Meta2Prefix) {
> ```

else if? boy this code is getting hard to read.

---

*[pkg/migrations/migrations.go, line 294 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMyYRCJgfNOmA2O-P:-KZTMyYRCJgfNOmA2O-Q:b9xzzvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations.go#L294)):*
> ```Go
> 			return nil
> 		}); err != nil {
> 			return errors.Wrapf(err, "failed to get/put key %q", kv.Key)
> ```

can you do the wrapping in the closure so that it's not ambiguous?

---

*[pkg/migrations/migrations_test.go, line 124 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMHiQeUMvwYHeldtx:-KZTMHiQeUMvwYHeldty:b-1xdgq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations_test.go#L124)):*
> ```Go
> }
> 
> func (f *fakeDB) Txn(ctx context.Context, retryable func(txn *client.Txn) error) error {
> ```

s/ctx/_/
s/retryable/_/
s/txn //

---

*[pkg/sql/sqlbase/system.go, line 427 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTKUGc1JuwbT-2_u94:-KZTKUGc1JuwbT-2_u95:b2vl7cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/sql/sqlbase/system.go#L427)):*
> ```Go
> 	desc := config.MetaZoneConfig()
> 	if err := value.SetProto(&desc); err != nil {
> 		log.Fatalf(context.TODO(), "could not marshal %v", desc)
> ```

can we panic here, or return an error? I think in general, we should avoid `log.Fatal{,f}(context.TODO,...)` because an actual hit here will be absolutely terrible to debug.

more broadly, I see that you're following precedent here, but this precedent is ... terrible -- returning a slice of one? yeesh.

and later in r5 all the functions are exported, and yet they are never used separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513)*

**Comment by a-robinson** [comment]
Sorry for not making it more clear, but the first commit is just #12335. Most of your comments should be directed there.

---

Review status: 7 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/cli/zone.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLOA9IHPU0MqiyKMg:-KZTP6WN6jMxJDjktRmG:b-de2c6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L351)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

perhaps this can be used in `runGetZone`?

EDIT: I see this changed to a slice in r3 but I think it should be a map and used basically everywhere.
</blockquote></details>

If map iteration is used here, the output becomes non-deterministic, which breaks the CLI example test.

---

*[pkg/migrations/migrations.go, line 294 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMyYRCJgfNOmA2O-P:-KZTPV8xi31lrnBtq4cN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations.go#L294)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you do the wrapping in the closure so that it's not ambiguous?
</blockquote></details>

Done.

---

*[pkg/migrations/migrations_test.go, line 124 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMHiQeUMvwYHeldtx:-KZTPUmZwMtPK_J2Q5Hp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations_test.go#L124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/ctx/_/
s/retryable/_/
s/txn //
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-:-KZTOsBrrnI9czX6HBWO:b21zojh)*

**Comment by tamird** [comment]
Oh, are you planning for both to be merged? I expected that you would
simply take over the change.

**Comment by a-robinson** [comment]
I wasn't planning on taking it over, just layering the migration on top. @a6802739, what would you like to do? It's really your choice.

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/cli/zone.go, line 351 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTLOA9IHPU0MqiyKMg:-KZW_tou_CQEA0aRryz2:bulcjvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e731a3e268422960a2dbef2eaaa77a6ffd3fd8f2/pkg/cli/zone.go#L351)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

If map iteration is used here, the output becomes non-deterministic, which breaks the CLI example test.
</blockquote></details>

sure, maybe you need to construct a slice here but the bigger point is using a shared map of zone configs.

---

*[pkg/migrations/migrations_test.go, line 124 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMHiQeUMvwYHeldtx:-KZW_rrPOvknpKnhVE69:bggitzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations_test.go#L124)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

missed `f` and `txn`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513)*

**Comment by a6802739** [comment]
@a-robinson, yeah, I will process #12335 first.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/migrations/migrations.go, line 292 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZWn1nNmezccjMFph1Z:-KZWn1nOgOSk6MJ9-7zA:bbme8r0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3989ab8d4c6656eb2213980698a02fbfabd4c9d/pkg/migrations/migrations.go#L292)):*
> ```Go
> 				return err
> 				return errors.Wrapf(err, "failed to put key %q", kv.Key)
> 			}
> ```

You don't want to do something like `INSERT INTO system.zones (id, config) VALUES ($1, $2) ON CONFLICT DO NOTHING`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-:-KZWnEympNbAJcTe5LNi:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/migrations/migrations.go, line 292 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZWn1nNmezccjMFph1Z:-KZYR6LNDGudCMyXom4S:b-dbhia5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3989ab8d4c6656eb2213980698a02fbfabd4c9d/pkg/migrations/migrations.go#L292)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You don't want to do something like `INSERT INTO system.zones (id, config) VALUES ($1, $2) ON CONFLICT DO NOTHING`?
</blockquote></details>

Yeah, we probably should. That makes testing it pretty nasty though, since we need to get access to the testserver's sqlExecutor to pass into the migration manager. Simply casting the testserver isn't an option due to the import cycle that referring to server.TestServer would create, but adding anything to the testserver interface that returns a sql.Executor creates import cycles between serverutils and sql, so I'll probably have to rework the test pretty heavily to do so.

Also, with some hacks in place to make it testable, I found that using the sql executor rather than the kv client made the test take 6.8 seconds instead of 0.47 seconds. I'm not quite sure why, but it seems like a interestingly large difference for what conceptually should be a similar amount of work.

I'll see what alternatives I can work out.

---

*[pkg/migrations/migrations_test.go, line 124 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZTMHiQeUMvwYHeldtx:-KZYE2aeZdM7qVkBY5RK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada5a5adb7d094e06256b282f65350f826d0c69c/pkg/migrations/migrations_test.go#L124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

missed `f` and `txn`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513)*

**Comment by petermattis** [comment]
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/migrations/migrations.go, line 292 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513#-KZWn1nNmezccjMFph1Z:-K_UUFBCnUk7EuiC1OWq:bqrjxoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3989ab8d4c6656eb2213980698a02fbfabd4c9d/pkg/migrations/migrations.go#L292)):*
> Also, with some hacks in place to make it testable, I found that using the sql executor rather than the kv client made the test take 6.8 seconds instead of 0.47 seconds. I'm not quite sure why, but it seems like a interestingly large difference for what conceptually should be a similar amount of work.

Yeah, that's very strange. 

I was thinking this wouldn't be too difficult given that `eventlogUniqueIDDefault` executes a SQL statement. I wouldn't want you to spend too much time on this as the KV-based migration is fine as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12513)*

**Comment by a-robinson** [comment]
Closing in favor of #14740.

**Pull request closed without merging**
