### PR TITLE
sql: add experimental domiciling syntax

### PR DESCRIPTION
**Pull request by pawalt**
Previously, we issued nonvoters to all cluster regions when
using our new multi-region syntax.
This was inadequate because it made it impossible to domicile
data to a particular region.
This patch adds a PLACEMENT RESTRICTED mode to the database to
allow users to remove non-voters from all REGIONAL BY ROW and
REGIONAL BY TABLE tables.

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
I would encourage you to break your PR into separate PRs, or at least separate commits. This has a few benefits:
* I like to think reviews take ~O(number of lines^2) time as you need to keep track of a lot of state at the same time. Reviewers have to jump back and forth to figure if something was done. You'll likely get faster reviews too if they're small.
* (if working on a big project) smaller commits earlier give you better stepping stones, and makes you less prone to having to refactor everything out. You get feedback quicker too because you send out smaller pieces and are able to commit earlier.
* Feedback on large PRs can lead to it not merging.
* It flexes your muscles into breaking down a project into smaller tasks. And you can ask people to help you parallelise too.
* You have more commits and PRs under your name, which of course is v important!

In your case, I would have separated them in commits akin to:
* One for SQL syntax, return an unimplemented error. This would have drastically reduced the number of files in later commits!
* One for the core logic in region_util.go(), with unit tests there.
* Piece the syntax with the logic in the back, maybe a separate one for the session variable, maybe another for the crdb_internal and maybe another for telemetry.

Nonetheless, review comments below. I would probably break the PR apart to make this more tenable.

> Reviewed 42 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-:-MfGLsDY38GcWOxIibH7:br68tey)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @pawalt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGN_730y8oEleObd-V:-MfGN_730y8oEleObd-W:b-r73o5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L1)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> ```

any reason why we choose `-vec-off`?
___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGO9zY62licwBZMQTh:-MfGO9zY62licwBZMQTi:b4ij9yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L13)):*
> ```
> 
> statement ok
> SET CLUSTER SETTING sql.defaults.experimental_domiciling.enabled = true
> ```

any reason we set both the cluster setting AND the session variable?
just the session setting is enough.
___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGNonaErziapgPn1Iw:-MfGNonaErziapgPn1Ix:b-wivtv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L22)):*
> ```
> 
> statement ok
> CREATE DATABASE zone_survivable_strict PRIMARY REGION "ca-central-1" REGIONS "ap-southeast-2", "us-east-1" PLACEMENT RESTRICTED
> ```

we should add an observable thing here to check placement is correct, i.e. `select ...., placement from crdb_internal.databases where ...`
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGNbhxEGxFdkezfe0L:-MfGNbhxEGxFdkezfe0M:b-8imd4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L1)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> ```

i think this can fit in the file `domiciling` file
___
*[pkg/sql/alter_database.go, line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGOVrlBMLqHltKbHRS:-MfGOVrlBMLqHltKbHRT:be90qem) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/alter_database.go#L755)):*
> ```Go
> 	// that are IN PRIMARY REGION must have their zone configs rebuilt.
> 	if updatedRegionConfig.Placement() == descpb.DataPlacement_RESTRICTED {
> 		if err := params.p.updateZoneConfigsForAllTables(params.ctx, n.desc); err != nil {
> ```

hmm, setting this on all regional by table tables is going to break a critical assumption we make that regional by table zone config uses the database zone config. there are a few i can think of:
* this reasoning is used in, e.g. DROP REGION <primary region>, as I'm fairly sure we don't "unset" any zone configs for REGIONAL BY TABLE tables (see https://github.com/cockroachdb/cockroach/blob/2424e907896fe4ae296bf969d22303abd80c7056/pkg/sql/region_util.go#L10).  it's worth a test for this case. 
is there any reason we choose to set zone configs on all RBR tables, as opposed
* you should check all the ALTER TABLE LOCALITY commands and ensure zone configs are updated appropriately, e.g. global -> RBT, RBR -> RBT and vice versa.

i almost wonder if instead the database zone config be rewritten instead, and the global zone config have voters overwritten instead. that allows us to keep this fundamental assumption.
___
*[pkg/sql/alter_database.go, line 1015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGQ19w66PnfkYpWVDI:-MfGQ19w66PnfkYpWVDJ:b1k0pl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/alter_database.go#L1015)):*
> ```Go
> 		n.desc.RegionConfig.Placement == descpb.DataPlacement_RESTRICTED {
> 		return errors.WithDetailf(
> 			pgerror.New(pgcode.InvalidParameterValue,
> ```

nit: prefer one arg per line, i.e.
```
pgerror.New(
   pgcode.InvalidParamterValue,
   "string " +
     "str",
)
```

few of these below as well.
___
*[pkg/sql/alter_database.go, line 1112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGQCUy5gDnWrfB0SrS:-MfGQCUy5gDnWrfB0SrT:b-l1u3q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/alter_database.go#L1112)):*
> ```Go
> 			pgcode.InvalidDatabaseDefinition,
> 			"ALTER DATABASE PLACEMENT requires that the cluster setting "+
> 				"sql.defaults.experimental_domiciling is enabled",
> ```

this doesn't require the cluster setting; just the session variable, i.e. `SET experimental_domiciling = true`. the cluster setting determines the *default* of `experimental_domiciling`.
I also think we're getting rid of `experimental` as a prefix -- contact andy woods on what to call this.
___
*[pkg/sql/descriptor.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGS8287b4pVUiNPbeV:-MfGS82ADLfRMAeyW5uA:bos151q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/descriptor.go#L303)):*
> ```Go
> 	primaryRegion tree.Name,
> 	regions []tree.Name,
> 	placement tree.DataPlacement,
> ```

we should probably add telemetry on how often placement is used on creation here.
___
*[pkg/sql/region_util_test.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGRO45AeH_Miq6UjuO:-MfGRO45AeH_Miq6UjuP:bwegzjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/region_util_test.go#L41)):*
> ```Go
> 				descpb.SurvivalGoal_ZONE_FAILURE,
> 				descpb.InvalidID,
> 				descpb.DataPlacement_DEFAULT,
> ```

suggest adding `restricted` tests in here.
___
*[pkg/sql/sem/tree/data_placement.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGMvtH7huPmR-QjBIy:-MfGMvtH7huPmR-QjBIz:b-1kfw7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/sem/tree/data_placement.go#L35)):*
> ```Go
> 	switch *node {
> 	case DataPlacementRestricted:
> 		ctx.WriteString("PLACEMENT RESTRICTED")
> ```

nit:
```
ctx.WriteString("PLACEMENT ")
switch *node {
   case DataPlacementRestricted:
      ctx.WriteString("RESTRICTED")
   ...
}
```
___
*[pkg/sql/sem/tree/data_placement.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGNBU40GF-WRZuqLVc:-MfGNBU40GF-WRZuqLVd:b5pirtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/sql/sem/tree/data_placement.go#L44)):*
> ```Go
> 
> // TelemetryName returns a representation of SurvivalGoal suitable for telemetry
> func (node *DataPlacement) TelemetryName() string {
> ```

can you add a test in `pkg/ccl/telemetryccl/testdata/telemetry/multiregion` to test this out?
___
*[pkg/util/log/eventpb/ddl_events.proto, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-MfGQtX5EKeM6htn4JdV:-MfGQtX5EKeM6htn4JdW:b-fxjj4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5505934b3bf5fe649b1542ba0cebb7bc15b07919/pkg/util/log/eventpb/ddl_events.proto#L100)):*
> ```protobuf
>   // The name of the database.
>   string database_name = 3 [(gogoproto.jsontag) = ",omitempty"];
>   // The new survival goal
> ```

nit: full stop at the end. (survival goal has the same problem)

**Comment by otan** [comment]
oops, s/Feedback on large PRs can lead to it not merging./Feedback on large PRs can lead to it not merging in a timely fashion as you spin on feedback on just one or two files and other things can merge in parallel./

this is neat btw! i applaud the effort to finish 1 intern project in 1 commit/<1 week, haha!

**Review by ajstorm — COMMENTED** [review]
In addition to @otan's great arguments, there's also this bit from Reviewable.  You don't want people missing out on some files that need reviewing.



I was hoping to have a look, so let me know if you're going to continue to use this PR, or if you're going to break things down.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67946#-:-MfIK8YM7TZcuJ3cC7al:bgkmmjh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

**Comment by pawalt** [comment]
I'll split this out into a few PRs and bump you when they're ready to go.

**Comment by pawalt** [comment]
Closing for size

**Pull request closed without merging**
