### PR TITLE
server, storage, sql, gossip: use a shared NodeIDContainer

### LINKED ISSUE #9344: server: investigate having a single shared source for the NodeID
Various server components maintain the `NodeID`, and - because the `NodeID` is determined during server startup - the server code does various `SetNodeID` calls.

In addition, the server maintains `nodeLogTagVal` which is an atomic `NodeID` container, used for log tags.

Investigate cleaning all this up by having everyone share a reference to a single atomic (or synchronized) container for the `NodeID`.

### PR DESCRIPTION
**Pull request by RaduBerinde**
This series of changes consolidates different copies of the node ID:
- in gossip
- in server, for the node ID tag
- in sql executor and lease manager

In addition, all gossip tests now include the nodeID tag in gossip's ambient context.

Fixes #9344.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10165)

### CODE REVIEW

**Comment by tamird** [comment]
> storage: add NodeIDContainer reference to StoreCfg

What's the rationale for this commit? Not clear why it's an improvement.

Otherwise :lgtm_strong: 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 33 of 33 files at r3, 18 of 18 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/base/node_id.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmtEbckpgKCq5R9Mq:-KUpmtEbckpgKCq5R9Mr:b-u2r4km) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/base/node_id.go#L35)):*
> ```Go
> // set, the value cannot change.
> type NodeIDContainer struct {
> 	syncutil.Mutex
> ```

how come this mutex is needed at all? Looks like it's for the logic in `Set`, but that can also use https://godoc.org/sync/atomic#CompareAndSwapInt32 to achieve the same effect.

---

*[pkg/base/node_id.go, line 75 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpnBGT2pFSsmEwludq:-KUpnBGT2pFSsmEwludr:b-ap6nd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/base/node_id.go#L75)):*
> ```Go
> // Reset changes the NodeID regardless of the old value. Can only be used from
> // testing code.
> func (n *NodeIDContainer) Reset(_ util.Tester, val roachpb.NodeID) {
> ```

heh, neat trick

---

*[pkg/gossip/gossip.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmCcHRyhedMgii27M:-KUpmCcHRyhedMgii27N:be8kluz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a5848db3617937a05aad6c56b9234c49ad94682/pkg/gossip/gossip.go#L223)):*
> ```Go
> 		bootstrapAddrs:    map[util.UnresolvedAddr]struct{}{},
> 	}
> 	stopper.AddCloser(stop.CloserFn(func() {
> ```

while you're here, there is no need for this wrapper `func()`.

---

*[pkg/gossip/gossip.go, line 253 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpoxBLqusPyqj02zWK:-KUpoxBLqusPyqj02zWL:b-6gflfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/gossip/gossip.go#L253)):*
> ```Go
> }
> 
> // NewTest is a simplified wrapper around New that creates the NodeIDContainer
> ```

move this to test code?

---

*[pkg/server/node_test.go, line 75 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUppupU9kU2I9vj2ojT:-KUppupVLgWRZEOaXZnu:b-kwhy1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5512a2a4ec70000b646162d93eeed5acd8d6fb/pkg/server/node_test.go#L75)):*
> ```Go
> 	grpcServer := rpc.NewServer(nodeRPCContext)
> 	serverCfg := makeTestConfig()
> 	g, nodeID := gossip.NewTest(
> ```

nit: this can be `cfg.Gossip, cfg.NodeID = gossip.NewTest(`

---

*[pkg/server/server.go, line 143 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUppQWac9O-jmhjohHa:-KUppQWac9O-jmhjohHb:bqypjvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/server/server.go#L143)):*
> ```Go
> 	// a regular tag since it's just doing an (atomic) load when a log/trace
> 	// message is constructed.
> 	s.cfg.AmbientCtx.AddLogTag("n", &s.nodeIDContainer)
> ```

perhaps a comment explaining where the node ID is set?

---

*[pkg/storage/store.go, line 944 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpq9JLPkSx3WMZvaxQ:-KUpq9JLPkSx3WMZvaxR:b-c4n90h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5512a2a4ec70000b646162d93eeed5acd8d6fb/pkg/storage/store.go#L944)):*
> ```Go
> 		// either.
> 		if s.cfg.Gossip != nil {
> 			panic("Gossip set but NodeID not set")
> ```

return an error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-:-KUpqi-GvX3FvBw7Q650:b-il79o3)*

**Comment by RaduBerinde** [comment]
TFTR! It felt weird that we were using `.Gossip.NodeID` for stuff that isn't really related to gossip, but I agree that the result is more error prone since we have to initialize the NodeID as well (and it has to match the one in Gossip). Removed the commit.

---

Review status: 0 of 39 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/base/node_id.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmtEbckpgKCq5R9Mq:-KUqtotVvS1Cw2Ib7DId:bonrykq) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/base/node_id.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come this mutex is needed at all? Looks like it's for the logic in `Set`, but that can also use https://godoc.org/sync/atomic#CompareAndSwapInt32 to achieve the same effect.
</details>
Both work, changed. A bit annoying that `CompareAndSwapInt32` doesn't return the existing value when it fails, fortunately not a problem for our "set once" model here.

---

*[pkg/gossip/gossip.go, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmCcHRyhedMgii27M:-KUr-MovUnOSxj8_pono:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a5848db3617937a05aad6c56b9234c49ad94682/pkg/gossip/gossip.go#L223)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> while you're here, there is no need for this wrapper `func()`.
</details>
Done.

---

*[pkg/gossip/gossip.go, line 253 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpoxBLqusPyqj02zWK:-KUqu9fqcszKYzhPCR4h:b32hwnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/gossip/gossip.go#L253)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> move this to test code?
</details>
it's used from many different packages.

---

*[pkg/server/node_test.go, line 75 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUppupU9kU2I9vj2ojT:-KUqy9gKmXhmvFpvOkMC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5512a2a4ec70000b646162d93eeed5acd8d6fb/pkg/server/node_test.go#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: this can be `cfg.Gossip, cfg.NodeID = gossip.NewTest(`
</details>
Done.

---

*[pkg/server/server.go, line 143 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUppQWac9O-jmhjohHa:-KUqzziJRAMKj5TS3I_s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/server/server.go#L143)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> perhaps a comment explaining where the node ID is set?
</details>
Done.

---

*[pkg/storage/store.go, line 944 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpq9JLPkSx3WMZvaxQ:-KUquI6zrFZVaFRGXi4_:b-4frw17) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5512a2a4ec70000b646162d93eeed5acd8d6fb/pkg/storage/store.go#L944)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> return an error?
</details>
It's gone now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-:-KUquSxnhsOikZz0uUz_:b-5b2cdd)*

**Comment by tamird** [comment]
Reviewed 32 of 33 files at r8, 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/base/node_id.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmtEbckpgKCq5R9Mq:-KUrIXMB03onyC_SWaof:b-59z7ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/base/node_id.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Both work, changed. A bit annoying that `CompareAndSwapInt32` doesn't return the existing value when it fails, fortunately not a problem for our "set once" model here.
</details>
You could also use `SwapInt32`, right? You're always going to `Fatal` unless the old value is zero.

---

*[pkg/gossip/gossip.go, line 253 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpoxBLqusPyqj02zWK:-KUrIubsdQ6mCfEJUY2g:b-33cf2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/gossip/gossip.go#L253)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> it's used from many different packages.
</details>
Ah, how unfortunate. However, it doesn't depend on any unexported APIs, so perhaps it could be in a different package like testutils? If not, it should take a util.Tester like you did elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/base/node_id.go, line 35 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpmtEbckpgKCq5R9Mq:-KUrOOHIvboiFBW8gUuJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/base/node_id.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> You could also use `SwapInt32`, right? You're always going to `Fatal` unless the old value is zero.
</details>
Done.

---

*[pkg/gossip/gossip.go, line 253 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpoxBLqusPyqj02zWK:-KUrOTWPTxGgHKFYh9LJ:b-phpd76) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/gossip/gossip.go#L253)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Ah, how unfortunate. However, it doesn't depend on any unexported APIs, so perhaps it could be in a different package like testutils? If not, it should take a util.Tester like you did elsewhere.
</details>
It's hard to do either: in many contexts `testing.T` is not plumbed through, and moving the code in a separate package will make it inaccessible to tests inside the `gossip` package (circular dependency). I appreciate the principle behind your suggestion but I would keep it as is given it's only a few lines of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165)*

**Comment by tamird** [comment]
Reviewed 1 of 8 files at r10, 7 of 7 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/gossip/gossip.go, line 253 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165#-KUpoxBLqusPyqj02zWK:-KUrS0Ew27c36sGsZfzw:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/10a66308996227d516588603bfc3e31d45eb3d8d/pkg/gossip/gossip.go#L253)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's hard to do either: in many contexts `testing.T` is not plumbed through, and moving the code in a separate package will make it inaccessible to tests inside the `gossip` package (circular dependency). I appreciate the principle behind your suggestion but I would keep it as is given it's only a few lines of code.
</details>
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10165)*

**Pull request merged**
