### PR TITLE
sql: add diagnostics request entry for EXPLAIN ANALYZE (DEBUG)

### LINKED ISSUE #46330: ui: EXPLAIN ANALYZE (DEBUG) results don't show up
When a diagnostics bundle is generated with EXPLAIN BUNDLE (and not via a diagnostics request), the bundle does not show up in the "statement diagnostics history". Either
 - we should change the API to return all diagnostics in the `system_diagnostics` table
 - or I can change the EXPLAIN ANALYZE (DEBUG) code to also insert a "fake" request in the other table. @andreimatei what do you think about this?

To reproduce, just run `EXPLAIN ANALYZE (DEBUG) SELECT 1`.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: fix error handling for EXPLAIN ANALYZE (DEBUG)

If we hit an error recording a statement bundle, we can't simply set an error on
the statement result (we would need to produce an error event, plus we may have
already committed an implicit transaction).

For now, just put the error message in the output of the command. Note that
these errors are not expected to happen in practice, I only noticed it because I
was making an unrelated change and had a bug.

Release note: None

#### sql: add diagnostics request entry for EXPLAIN ANALYZE (DEBUG)

When a statement diagnostic is generated via `EXPLAIN ANALYZE (DEBUG)`, we
insert a row in statement_diagnostics but there is no corresponding request in
statement_diagnostics_requests. The UI only shows the history of the requests.

This change adds a corresponding request; it is created directly as a completed
request.

Fixes #46330.

Release note (bug fix): statement diagnostics created through EXPLAIN ANALYZE
(DEBUG) now show up in the UI page.

### CODE REVIEW

**Comment by dhartunian** [comment]
This is v. helpful. Thanks @RaduBerinde! I'll start working off this PR.

**Comment by dhartunian** [comment]
👍 Confirming that this works for me. I was able to add a working link on the statement diagnostics page to the bundle download. This works if you trigger in the UI and in the CLI.

**Comment by RaduBerinde** [comment]
Thanks David!

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46759#-:-M3lXOj8A9dpo3QurT3C:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 451 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46759#-M3lX8beCYWyeu7-qdHB:-M3lX8beCYWyeu7-qdHC:b-rzdrtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c9116af754b5e8e6f183caf1320165f036d6df/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L451)):*
> ```Go
> 			_, err := r.ie.ExecEx(ctx, "stmt-diag-add-completed", txn,
> 				sqlbase.InternalExecutorSessionDataOverride{User: security.RootUser},
> 				"INSERT INTO system.statement_diagnostics_requests"+
> ```

I'd go through `stmtdiagnostics.Registry` to create this request. Either through `InsertRequest()`, or through a even more dedication method.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 451 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46759#-M3lX8beCYWyeu7-qdHB:-M3ld6UO0PsQe53Ma1xm:bya8zrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c9116af754b5e8e6f183caf1320165f036d6df/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L451)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd go through `stmtdiagnostics.Registry` to create this request. Either through `InsertRequest()`, or through a even more dedication method.
</blockquote></details>

We are in the `Registry` here..

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 451 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46759#-M3lX8beCYWyeu7-qdHB:-M3leKhp-KsnzXqVtzu0:b-4urg53) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c9116af754b5e8e6f183caf1320165f036d6df/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L451)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are in the `Registry` here..
</blockquote></details>

oh, ha, I thought we were in the executor. nvm me.

Would you mind putting a few more words in the comment above saying that that the admin ui likes to see this request?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/stmtdiagnostics/statement_diagnostics.go, line 451 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46759#-M3lX8beCYWyeu7-qdHB:-M3lfhlc3_ndxphM9Qcs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c9116af754b5e8e6f183caf1320165f036d6df/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L451)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

oh, ha, I thought we were in the executor. nvm me.

Would you mind putting a few more words in the comment above saying that that the admin ui likes to see this request?
</blockquote></details>

done

**Pull request merged**
