### PR TITLE
util/decimal: further restrict large pow executions

### LINKED ISSUE #10569: sql: POW pegs CPU
```
SELECT POW(425644047350.89246::decimal, 74.4647211651881::decimal)
```

Found with RSG.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #10569

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10570)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/decimal/decimal.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570#-KWMJ7CfzcGOaAoeggqY:-KWMJ7CfzcGOaAoeggqZ:bz61226) ([raw file](https://github.com/cockroachdb/cockroach/blob/65b2ccc3ce53f733536b802a8610b94bbe3a9786/pkg/util/decimal/decimal.go#L331)):*
> maximum number of digits exp10 is expected to return

What is exp10? Did you mean `QuoRound`?

---

*[pkg/util/decimal/decimal_test.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570#-KWMJY42YF9OX6kh1Ycy:-KWMJY42YF9OX6kh1Ycz:b-156v5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/65b2ccc3ce53f733536b802a8610b94bbe3a9786/pkg/util/decimal/decimal_test.go#L449)):*
> ```Go
> 	b.ResetTimer()
> 	for i := 0; i < b.N; i++ {
> 		_, _ = Log(z, vals[i%len(vals)], 16)
> ```

Lets panic/fail on error. It adds a bit of overhead to the benchmark, but it should be negligible, and we've seen a few cases where benchmarks weren't actually doing what we thought.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570)*

**Comment by mjibson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/decimal/decimal.go, line 331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570#-KWMJ7CfzcGOaAoeggqY:-KWWcUIJzve2Et1q2D4A:bv13iyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/65b2ccc3ce53f733536b802a8610b94bbe3a9786/pkg/util/decimal/decimal.go#L331)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> > maximum number of digits exp10 is expected to return
> 
> What is exp10? Did you mean `QuoRound`?
</details>
No, exp10 is the culprit here. inf.exp10 calls big.Exp, which calls expNN, which is slow for large values like this. QuoRound calls quo which calls quoRem which calls exp10. I profiled a bunch of stuff and the call to expNN is the one that keeps getting slower and slower when the inputs are large because it's got a for loop.

---

*[pkg/util/decimal/decimal_test.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570#-KWMJY42YF9OX6kh1Ycy:-KWWcTIIzHQm1Yup199y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65b2ccc3ce53f733536b802a8610b94bbe3a9786/pkg/util/decimal/decimal_test.go#L449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Lets panic/fail on error. It adds a bit of overhead to the benchmark, but it should be negligible, and we've seen a few cases where benchmarks weren't actually doing what we thought.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570)*

**Comment by mjibson** [comment]
PTAL?

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10570#-:-KWdpR12J6SudGzgxdpW:bnfp4nl)*

**Pull request merged**
