### PR TITLE
sql: catch panics in makeQueryIndexRecommendation

### LINKED ISSUE #88246: sql: optimizer panics during index recommendation generation should not crash nodes
See #88037.

If the optimizer panics while generating index recommendations, a node can crash. Below is the crash log from #88037 that shows an optimizer panic crashing the node.

```
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125  encountered internal error:
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +expected required columns to be a subset of output columns
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +(1) assertion failure
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +Wraps: (2) attached stack trace
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  -- stack trace:
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/ordering.projectBuildProvided
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/project.go:87
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/ordering.BuildProvided
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/ordering.go:66
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:778
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:266
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).makeQueryIndexRecommendation
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:745
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:570
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:233
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1432
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1058
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:687
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2382
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:128
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1919
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1923
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1845
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:827
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | runtime.goexit
E220916 06:44:56.948222 960 sql/sqltelemetry/report.go:57 ⋮ [n1,client=34.74.3.67:51630,user=root] 125 +  | 
```

Notice the line:

```
... | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).makeQueryIndexRecommendation
```

We need to correctly catch optimizer panics so that they do not crash nodes.

Jira issue: CRDB-19745

### PR DESCRIPTION
**Pull request by michae2**
In the optimizer we use the convention of panic-based error handling for a performance advantage. This means at the boundaries we must remember to recover and return errors instead of letting panics escape.

`sql.(*optPlanningCtx).makeQueryIndexRecommendation` calls some optimizer helper functions in addition to calling
`xform.(*Optimizer).Optimize`. While `Optimize` has the panic-recovery code, these helper functions do not, so we need to add panic recovery to `makeQueryIndexRecommendation` as well.

Fixes: #88246

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-:-NGKPdbdBrDb-zrUcGmI:b-pt8m11)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/plan_opt.go` line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-NGKPf00E9ZrGpI-QGbZ:-NGKPf00E9ZrGpI-QGb_:b-tsupg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b0b8676c337cea7e08d857d9d53c410501c966/pkg/sql/plan_opt.go#L710)):*
> ```Go
> // optimal plan.
> func (opc *optPlanningCtx) makeQueryIndexRecommendation(ctx context.Context) (err error) {
> 	defer func() {
> ```

[nit] it seems like this logic is duplicated in a couple places; do you think it would be worth moving it to a function somewhere (maybe errorutil)?

**Review by yuzefovich — APPROVED** [review]
:lgtm:

We also probably want to backport this, right? If so, it might be better to keep this change as is and open a separate PR that extracts a helper function for recovering.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-:-NGNQ5bs-dBsxAJnpXxW:b-9vfi9z)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/plan_opt.go` line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-NGKPf00E9ZrGpI-QGbZ:-NGNPyeF9HBMkTmyMg77:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/10b0b8676c337cea7e08d857d9d53c410501c966/pkg/sql/plan_opt.go#L710)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] it seems like this logic is duplicated in a couple places; do you think it would be worth moving it to a function somewhere (maybe errorutil)?
</blockquote></details>

+1

**Review by michae2 — COMMENTED** [review]
Good call on backporting. TFTRs!

bors r=DrewKimball,yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-:-NGblEfDBCcDF0b8c1bj:b-rkmn6y)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/plan_opt.go` line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/91457#-NGKPf00E9ZrGpI-QGbZ:-NGbl9z29ONqDVu7SWEP:b-wkwbhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7871ea83580f1641d789ad84b0ad463f8f83154/pkg/sql/plan_opt.go#L710)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Good point. This is now in https://github.com/cockroachdb/cockroach/pull/91752

**Comment by mgartner** [comment]
Thanks for fixing this! Looks like the backport to 22.1 failed - do we still want to backport to that version?

**Pull request merged**
