### PR TITLE
colexec: reset batch selection vector in chunkingBatchSource

### PR DESCRIPTION
**Pull request by Azhng**
colexec: reset batch sel vector in chunkingBatchSource

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45545#-:-M1DhxRcD48_tlVu0xfI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/utils_test.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45545#-M1DhN_z6-Xucsq1ZFgM:-M1DhN_z6-Xucsq1ZFgN:b-lc4wg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3ea71b805beb74690d2617d2b3bbabb2d00e2fe/pkg/sql/colexec/utils_test.go#L1223)):*
> ```Go
> 	}
> 	// Explicitly set to false since this could be modified by the downstream
> 	// operators.
> ```

~nit: you might want to highlight that using `ResetInternalBatch` is not needed here because the vectors will be replaced below.~

Or maybe it'd be better just to use `ResetInternalBatch` anyway since every operator that owns a batch does that before returning the batch as the output. And then there would be no comment necessary.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45545)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/utils_test.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45545#-M1DhN_z6-Xucsq1ZFgM:-M1GnWQP7JsE767nn3qN:b-446111) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3ea71b805beb74690d2617d2b3bbabb2d00e2fe/pkg/sql/colexec/utils_test.go#L1223)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

~nit: you might want to highlight that using `ResetInternalBatch` is not needed here because the vectors will be replaced below.~

Or maybe it'd be better just to use `ResetInternalBatch` anyway since every operator that owns a batch does that before returning the batch as the output. And then there would be no comment necessary.
</blockquote></details>

An issue with calling `ResetInternalBatch` here is that if the column type is a `Bytes`, it's going to cause a panic since `c.batch` is a window into the `c.col`. 

https://github.com/cockroachdb/cockroach/blob/master/pkg/col/coldata/batch.go#L270
https://github.com/cockroachdb/cockroach/blob/master/pkg/col/coldata/bytes.go#L398

I think the two options here is either:
1. we only reset the selection vector 
2. we reallocate the `c.batch` wither explicitly or via calling `Reset` 

Personally I prefer we just reset the selection vector

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45545)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/utils_test.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45545#-M1DhN_z6-Xucsq1ZFgM:-M1LmRhU1cilwKsNgLDh:b-8uhx2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3ea71b805beb74690d2617d2b3bbabb2d00e2fe/pkg/sql/colexec/utils_test.go#L1223)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

An issue with calling `ResetInternalBatch` here is that if the column type is a `Bytes`, it's going to cause a panic since `c.batch` is a window into the `c.col`. 

https://github.com/cockroachdb/cockroach/blob/master/pkg/col/coldata/batch.go#L270
https://github.com/cockroachdb/cockroach/blob/master/pkg/col/coldata/bytes.go#L398

I think the two options here is either:
1. we only reset the selection vector 
2. we reallocate the `c.batch` wither explicitly or via calling `Reset` 

Personally I prefer we just reset the selection vector 
</blockquote></details>

Right, just unsetting the selection vector is good.

Please mention in the comment that `SetSelection(false)` is sufficient because both the vectors and the nulls are explicitly set below, and furthermore, calling `ResetInternalBatch` isn't valid because we're operating on `Window`s into the vectors.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45545)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colexec/utils_test.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45545#-M1DhN_z6-Xucsq1ZFgM:-M1MnmXk3VnFbUPijOZV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3ea71b805beb74690d2617d2b3bbabb2d00e2fe/pkg/sql/colexec/utils_test.go#L1223)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Right, just unsetting the selection vector is good.

Please mention in the comment that `SetSelection(false)` is sufficient because both the vectors and the nulls are explicitly set below, and furthermore, calling `ResetInternalBatch` isn't valid because we're operating on `Window`s into the vectors.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
LGTM

**Pull request merged**
