### PR TITLE
server, sql: span stats returns logical MVCC stats

### LINKED ISSUE #108766: sql: SHOW RANGES WITH DETAILS shows incorrect MVCC stats
```
\x
CREATE TABLE test (n INT);
INSERT INTO test SELECT generate_series(1, 1000000);
SHOW RANGES FROM TABLE test WITH DETAILS;

-[ RECORD 1 ]
start_key             | …/<TableMin>
end_key               | <after:/Max>
range_id              | 64
range_size_mb         | 52.081746000000000000
lease_holder          | 2
lease_holder_locality | cloud=local,region=local,zone=local
replicas              | {1,2,3}
replica_localities    | {"cloud=local,region=local,zone=local","cloud=local,region=local,zone=local","cloud=local,region=local,zone=local"}
voting_replicas       | {1,3,2}
non_voting_replicas   | {}
learner_replicas      | {}
split_enforced_until  | NULL
range_size            | 52081746
span_stats            | {"approximate_disk_bytes": 43660186, "intent_bytes": 0, "intent_count": 0, "key_bytes": 75000000, "key_count": 3000000, "live_bytes": 156245238, "live_count": 3000000, "sys_bytes": 879, "sys_count": 18, "val_bytes": 81245238, "val_count": 3000000}
```

`key_count: 3000000` is not correct, there's 1 million keys in the range, not 3 million. Seems like it's adding up results from all replicas or something.

@zachlite Is this related to your recent span stats work?

Jira issue: CRDB-30628
Epic: CRDB-30635

### PR DESCRIPTION
**Pull request by zachlite**
Previously, the MVCC stats returned by span stats were mistakenly accumulated from each node. This commit fixes that, and adds clarifying comments.

Resolves: https://github.com/cockroachdb/cockroach/issues/108766 Epic: CRDB-30635
Release note (bug fix): A bug was fixed where a SpanStatsRequest would return post-replicated MVCC stats. Now, a SpanStatsRequest returns the logical MVCC stats for the requested span.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108852)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @erikgrinaker, and @zachlite)

___
*[`pkg/server/span_stats_server.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-Nc7y8v1BkN1pM46W1gI:-Nc7y8v1BkN1pM46W1gJ:brugl1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/server/span_stats_server.go#L116)):*
> ```Go
> 				res.SpanToStats[spanStr].ApproximateDiskBytes += spanStats.ApproximateDiskBytes
> 				res.SpanToStats[spanStr].RemoteFileBytes += spanStats.RemoteFileBytes
> 				res.SpanToStats[spanStr].ExternalFileBytes += spanStats.ExternalFileBytes
> ```

there is no need for the rangeCount here?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108852)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @erikgrinaker, and @maryliag)

___
*[`pkg/server/span_stats_server.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-Nc7y8v1BkN1pM46W1gI:-Nc8Czxh5YjD5B1mHECG:b-yvzjxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/server/span_stats_server.go#L116)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

there is no need for the rangeCount here?
</blockquote></details>

No. If we did accumulate range count here, it would really be replica count.

**Review by maryliag — APPROVED** [review]
:lgtm: 
still want to see an approval from @dhartunian or @erikgrinaker 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-:-Nc8Df0j5vA_Lf3QDC2T:bn6odda)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @erikgrinaker)

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108852)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, and @zachlite)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHWyyDn9RJpqvccy1):*
Span stats are new in 23.2, right? If so, there's no need to add a release note, since we haven't ever released the bug that we're fixing here.
___
*[`pkg/roachpb/span_stats.proto` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHlT1AAwhNZj0bhZc:-NcMHlT1AAwhNZj0bhZd:bo0ukzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/roachpb/span_stats.proto#L40)):*
> ```proto
> message SpanStats {
>   // TotalStats are the logical MVCC stats for the requested span.
>   cockroach.storage.enginepb.MVCCStats total_stats = 1 [(gogoproto.nullable) = false];
> ```

nit: consider simply `stats` here. `total_stats` can be a bit misleading, since it's not a sum.
___
*[`pkg/roachpb/span_stats.proto` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHyRqBoebqezBYlju:-NcMHyRqBoebqezBYljv:b-fitxbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/roachpb/span_stats.proto#L50)):*
> ```proto
>   // data in the span. NB; this *includes* files stored remotely, not just on
>   // _local_ disk; see the RemoteFileBytes field below.
>   // It represents a physical value is accumulated by the fan-out.
> ```

nit: "physical value across all replicas"
___
*[`pkg/server/span_stats_server.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMI7627Bx6ZRdvPOet:-NcMI7627Bx6ZRdvPOeu:b-rv9x0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/server/span_stats_server.go#L114)):*
> ```Go
> 			if _, ok := responses[spanStr]; ok {
> 				// Accumulate values for physical quantities:
> 				res.SpanToStats[spanStr].ApproximateDiskBytes += spanStats.ApproximateDiskBytes
> ```

nit: consider restructuring this to avoid duplicating fields, which also avoids future issues where developers may forget to update both sites. Something like:

```go
for spanStr, spanStats := range nodeResponse.SpanToStats {
  // Accumulate values for physical quantities:
  res.SpanToStats[spanStr].ApproximateDiskBytes += spanStats.ApproximateDiskBytes
  // ...other accumulated fields

  // Logical values: take the values from the node that responded first.
  // TODO: this should really be read from the leaseholder.
  if _, ok := responses[spanStr]; !ok {
    res.SpanToStats[spanStr].TotalStats = spanStats.TotalStats
    // ...other non-accumulated fields
  }
}
```

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108852)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @erikgrinaker, and @maryliag)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHWyyDn9RJpqvccy1):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Span stats are new in 23.2, right? If so, there's no need to add a release note, since we haven't ever released the bug that we're fixing here.
</blockquote></details>

No, span stats were added in 23.1.   The new functionality in`SHOW RANGES WITH DETAILS` is new in 23.2... and hopefully we'll be able to backport that to 23.1, but maybe not.
___
*[`pkg/roachpb/span_stats.proto` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHlT1AAwhNZj0bhZc:-NcNqAJqDuZsu6Ew5LmR:b-pnhz2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/roachpb/span_stats.proto#L40)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: consider simply `stats` here. `total_stats` can be a bit misleading, since it's not a sum.
</blockquote></details>

Ack - but I'm not going to touch right now, since I want to backport this.
___
*[`pkg/roachpb/span_stats.proto` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMHyRqBoebqezBYlju:-NcNqKYi50qA4qDxpvdg:b-dtkds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/roachpb/span_stats.proto#L50)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: "physical value across all replicas"
</blockquote></details>

Done, thanks!
___
*[`pkg/server/span_stats_server.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108852#-NcMI7627Bx6ZRdvPOet:-NcNqMbs3UhQy17XZuSw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d5b1a517eae539631758fe739d49c6cb022d6d4/pkg/server/span_stats_server.go#L114)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: consider restructuring this to avoid duplicating fields, which also avoids future issues where developers may forget to update both sites. Something like:

```go
for spanStr, spanStats := range nodeResponse.SpanToStats {
  // Accumulate values for physical quantities:
  res.SpanToStats[spanStr].ApproximateDiskBytes += spanStats.ApproximateDiskBytes
  // ...other accumulated fields

  // Logical values: take the values from the node that responded first.
  // TODO: this should really be read from the leaseholder.
  if _, ok := responses[spanStr]; !ok {
    res.SpanToStats[spanStr].TotalStats = spanStats.TotalStats
    // ...other non-accumulated fields
  }
}
```
</blockquote></details>

Done

**Pull request merged**
