### PR TITLE
colexec: add unordered distinct

### LINKED ISSUE #39240: exec: unordered distinct
The vectorized engine currently only handles DISTINCT on fully-ordered columns. It doesn't yet know how to deal with distincts on unordered (or partially ordered) columns.

This issue tracks implemented an unordered distinct operator. Unordered distinct is implemented with a hash table. The DistSQL implementation of unordered distinct could serve as a guide - but it's possible that we could get away with reusing much of the unordered aggregation code rather than doing something from scratch.

### PR DESCRIPTION
**Pull request by yuzefovich**
**distsql: add a test comparing distinct operator and processor**

Release note: None

**colexec: minor cleanup of hashjoiner_tmpl**

This commit removes some extra empty lines from the generated code by
appending `-` to the end of the template definitions. Also, it refactors
one conditional into an assignment.

Release note: None

**colexec: fix a bug in hash table when null equality is allowed**

Previously we incorrectly were handling the case of allowed null
equality in the hash table (which is used by the hash grouper and
unordered distinct) - we were resetting groupID of the tuple on the
probe side of that tuple has NULL value in the equality column whereas
the build tuple has a non-NULL value. This could result in incorrectly
populated `same` array and is now fixed.

Release note: None

**colexec: add unordered distinct**

This commit adds an unordered distinct operator. The operator simply
builds a hashTable on the first call to Next() on the whole input, then
iterates over all of the tuples to check whether the tuple is the "head"
of a linked list that contain all of the tuples that are equal on
distinct columns. Only the "head" is included into the big selection
vector. Once the big selection vector is populated, the operator
proceeds to returning the batches according to a chunk of the selection
vector.

This doesn't take into account whether the input is partially ordered,
and this item is left as a follow-up work.

Fixes: #39240.

Release note (sql change): vectorized execution engine now supports
DISTINCT on unordered input.

**colexec: fix hash grouper**

Previously, hash grouper could hit an internal error of index outside of
range when it was looking for the "head" of a linked list. Now this is
fixed by refactoring the code in question. I think the code is now more
comprehensible.

There is no release note since hash grouper so far has been used only
with `experimental_on`.

Release note: None

**distsql: enhance testing columnar aggregator against processor**

This commit adds an ability to insert NULL values into grouping columns
and increases the number of grouping columns tested (previously it was
hard-coded as one). ANY_NOT_NULL aggregate is now skipped since it
returns non-deterministic output.

This change required modifications to the test harness to allow the
results of aggregation to deviate slightly when operating on float
values because direct string matching will not work in some cases.

Also, this commit extracts out arguments to the test harness into
a separate struct.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks:
```
BenchmarkUnorderedDistinct/numCols=1/nulls=false/numBatches=1-16         	   20000	     72192 ns/op	 113.48 MB/s
BenchmarkUnorderedDistinct/numCols=1/nulls=false/numBatches=16-16        	    2000	   1014894 ns/op	 129.15 MB/s
BenchmarkUnorderedDistinct/numCols=1/nulls=false/numBatches=256-16       	      30	  36663955 ns/op	  57.20 MB/s
BenchmarkUnorderedDistinct/numCols=1/nulls=true/numBatches=1-16          	   10000	    107804 ns/op	  75.99 MB/s
BenchmarkUnorderedDistinct/numCols=1/nulls=true/numBatches=16-16         	    1000	   1513768 ns/op	  86.59 MB/s
BenchmarkUnorderedDistinct/numCols=1/nulls=true/numBatches=256-16        	      50	  37036900 ns/op	  56.62 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=false/numBatches=1-16         	   20000	     87886 ns/op	 186.42 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=false/numBatches=16-16        	    1000	   1483883 ns/op	 176.66 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=false/numBatches=256-16       	      20	  59172647 ns/op	  70.88 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=true/numBatches=1-16          	   10000	    152882 ns/op	 107.17 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=true/numBatches=16-16         	     500	   2421836 ns/op	 108.24 MB/s
BenchmarkUnorderedDistinct/numCols=2/nulls=true/numBatches=256-16        	      30	  57637260 ns/op	  72.77 MB/s
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_tmpl.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LuKhaFf4wQu2XuSDsdJ:-LuKhaFf4wQu2XuSDsdK:bdalqu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e64c235be770252593d03d2caab89e6c9870786/pkg/col/coldata/vec_tmpl.go#L71)):*
> ```Go
> 			toCol = execgen.SLICE(toCol, 0, int(args.DestIdx))
> 			// {{if eq .LTyp.String "Bytes"}}
> 			maxIdx := uint16(0)
> ```

I don't really like this solution, but it is least "invasive." I think that we want to have special casing for NULL vs non-NULL case, and possibly we might get rid off `maybeBackfillOffsets` method of Bytes then (this is TBD).

**Comment by yuzefovich** [comment]
The problem with NULLs in `Append` has been also triggered by recently added unit test case for merge joiner (#42774).

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 954 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LwW8Rfp1SKxk89r_vtq:-LwW8Rfp1SKxk89r_vtr:b-4o1kwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L954)):*
> ```
> ----
> ·                         distributed  false                                      ·                         ·
> ·                         vectorized   false                                      ·                         ·
> ```

Note that these queries are no longer executed via the vectorized engine because now we have a non-streaming operator (newly introduced unordered distinct) whereas previously we were wrapping a distinct processor (and all wrapped processors are considered streaming).

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/distinct_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2bRCW1W6yk5b5fV01:-Lx2bRCW1W6yk5b5fV02:bj0o6cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/distinct_test.go#L110)):*
> ```Go
> 		runTests(t, []tuples{tc.tuples}, tc.expected, unorderedVerifier,
> 			func(input []Operator) (Operator, error) {
> 				return NewUnorderedDistinct(testAllocator, input[0], tc.distinctCols, tc.colTypes), nil
> ```

I think it would be nice if this test clause would actually mix up the tuples to be unordered, but maybe it's not important.
___
*[pkg/sql/colexec/execplan.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2bYXID5V9KIPrd_sX:-Lx2bYXID5V9KIPrd_sY:bdzgycr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/execplan.go#L605)):*
> ```Go
> 				return result, err
> 			}
> 			// TODO(yuzefovich): implement the distinct on partially ordered columns.
> ```

Can you open an issue for this? It's a nice self contained project.
___
*[pkg/sql/colexec/unordered_distinct.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2caHkBnTHTMTXmIay:-Lx2caHkBnTHTMTXmIaz:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/unordered_distinct.go#L107)):*
> ```Go
> 		// Since next is no longer useful and pre-allocated to the appropriate
> 		// size, we can use it as the selection vector. This way we don't have to
> 		// reallocate a huge array.
> ```

Nice!
___
*[pkg/sql/colexec/unordered_distinct.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2cs418vnmRlbvK5S_:-Lx2cs418vnmRlbvK5Sa:b-m2shrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/unordered_distinct.go#L110)):*
> ```Go
> 		op.sel = op.ht.next
> 
> 		for _, keyID := range op.ht.first {
> ```

Hmm doesn't this undercount in the case of hash collisions? I forget how this works, but I thought that you have to traverse the whole chain to check equality as well.
___
*[pkg/sql/opt/exec/execbuilder/testdata/aggregate, line 954 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LwW8Rfp1SKxk89r_vtq:-Lx2d3pJA_aCfQF6ekw2:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/opt/exec/execbuilder/testdata/aggregate#L954)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Note that these queries are no longer executed via the vectorized engine because now we have a non-streaming operator (newly introduced unordered distinct) whereas previously we were wrapping a distinct processor (and all wrapped processors are considered streaming).
</blockquote></details>

Ack.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/distinct_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2bRCW1W6yk5b5fV01:-Lx3NTsl4f2px7lDWTIi:b-hoczt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/distinct_test.go#L110)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it would be nice if this test clause would actually mix up the tuples to be unordered, but maybe it's not important.
</blockquote></details>

Hm, I think it's not that important. This is more like sanity-check test, it can be very easy.
___
*[pkg/sql/colexec/execplan.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2bYXID5V9KIPrd_sX:-Lx31YNa7IjGW-PHjBHB:b-w9umra) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/execplan.go#L605)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you open an issue for this? It's a nice self contained project.
</blockquote></details>

Done. 

I was thinking of this TODO as the necessary part before closing #39240, and actually I started working on it right after. Maybe I'll pick it back up soon.
___
*[pkg/sql/colexec/unordered_distinct.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2caHkBnTHTMTXmIay:-Lx32_Jt4Bj6fgEgaLKF:b-ehup8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/unordered_distinct.go#L107)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

I copied this approach from `hash_aggregator.go` (so kudos to Angela).
___
*[pkg/sql/colexec/unordered_distinct.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-Lx2cs418vnmRlbvK5S_:-Lx3N9BP7DlAtSnr_rBs:bhke4ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/c283edcd8f5ace22453ce3cc8cf984ac9069f22a/pkg/sql/colexec/unordered_distinct.go#L110)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm doesn't this undercount in the case of hash collisions? I forget how this works, but I thought that you have to traverse the whole chain to check equality as well.
</blockquote></details>

You're totally right - nice catch! I added `TestDistinctAgainstProcessor`, and it caught this problem right away. I'll have to spend a little bit more time on this (I might delay fixing this until I'm working on spilling for hash joiner).

**Comment by asubiotto** [comment]
I understand that this PR is not ready for another review? Let me know if that changes.

**Comment by yuzefovich** [comment]
Yeah, it has a bug at the moment, so not RFAL.

**Comment by yuzefovich** [comment]
Alright, this guy is RFAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 11 of 11 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 113 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHsQcBAXxr1eC5ACGi:-LzHsQcBAXxr1eC5ACGj:b-do0knz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7241ce33b8877d948eb9290a7d67b440a2dc5bcc/pkg/sql/colexec/hashjoiner_tmpl.go#L113)):*
> ```Go
> 				continue
> 			} else if probeIsNull {
> 				ht.differs[toCheck] = true
> ```

I would probably write this:
```
if probeIsNull {
    if !buildIsNull {
        ht.differs[toCheck] = true
    }
    continue
}
```
And maybe add a comment to the `ht.differs[toCheck]`? I think this code could generally use more comments.
___
*[pkg/sql/colexec/unordered_distinct.go, line 102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHxvCtBfrLLO_tM7Ys:-LzHxvCtBfrLLO_tM7Yt:b4wx6vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L102)):*
> ```Go
> 	if !op.buildFinished {
> 		op.buildFinished = true
> 		op.builder.exec(ctx)
> ```

Doing this naively will store every single tuple in the hash table right? That seems unnecessarily memory-intensive. Is there a way we can modify the hash table to only keep the first tuple? Will this affect performance? Seems like we're skipping the rest in `head` below anyway.
___
*[pkg/sql/colexec/unordered_distinct.go, line 138 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyZjLEz-JFiLAnKjg:-LzHyZjLEz-JFiLAnKjh:bv7q5qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L138)):*
> ```Go
> 		toCol := op.output.ColVec(i)
> 		fromCol := op.ht.vals.colVecs[colIdx]
> 		toCol.Copy(
> ```

Should this be wrapped in a `PerformOperation`? Don't we have a lint rule that enforces this?
___
*[pkg/sql/colexec/unordered_distinct.go, line 146 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyuXw2-rNghksmMsd:-LzHyuXw2-rNghksmMse:blhlrml) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L146)):*
> ```Go
> 					SrcEndIdx:   batchEnd,
> 				},
> 				Sel64: op.sel,
> ```

Does this `op.sel` need to be "advanced" for the next iteration? If so, would this be caught by randomizing the batch size?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqHi17w-LL0BG75K2:-LzHqHi17w-LL0BG75K3:bev9jfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L130)):*
> ```Go
> 
> 	seed := rand.Int()
> 	rng := rand.New(rand.NewSource(int64(seed)))
> ```

Why is this not `randutil.NewPseudoRand`?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqWsu2d9ma4al1QPl:-LzHqWsu2d9ma4al1QPm:b-7uprol) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L140)):*
> ```Go
> 	}
> 
> 	for run := 1; run < nRuns; run++ {
> ```

`<=`?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqwKk7K-6WVyRUnDJ:-LzHqwKk7K-6WVyRUnDK:b-x823my) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L193)):*
> ```Go
> 					}
> 					if err := verifyColOperator(
> 						true, /* anyOrder */
> ```

Not sure if I said this before, but we should probably extract these arguments out into a struct.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 50 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzI-uYpEwilH9ljNn5X:-LzI-uYpEwilH9ljNn5Y:b-m1b5bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2159b655c3e81070a703730725d3cde66915ebd0/pkg/sql/distsql/columnar_utils_test.go#L50)):*
> ```Go
> 	memoryLimit int64,
> ) error {
> 	const floatPrecision = 0.0000001
> ```

I'm not sure why the addition of `NULL`s to grouping columns affected this?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 113 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHsQcBAXxr1eC5ACGi:-LzNpnkK79rXqGIBUvCV:bjskgl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7241ce33b8877d948eb9290a7d67b440a2dc5bcc/pkg/sql/colexec/hashjoiner_tmpl.go#L113)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would probably write this:
```
if probeIsNull {
    if !buildIsNull {
        ht.differs[toCheck] = true
    }
    continue
}
```
And maybe add a comment to the `ht.differs[toCheck]`? I think this code could generally use more comments.
</blockquote></details>

I think keeping two `if`s separate is easier to understand. Added a couple of comments. In general, my understanding of this code is not great though :/
___
*[pkg/sql/colexec/unordered_distinct.go, line 102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHxvCtBfrLLO_tM7Ys:-LzNq6KI0_igufEcNLbu:b-gevm4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Doing this naively will store every single tuple in the hash table right? That seems unnecessarily memory-intensive. Is there a way we can modify the hash table to only keep the first tuple? Will this affect performance? Seems like we're skipping the rest in `head` below anyway.
</blockquote></details>

Yes, as we discussed, the whole input is stored in the hash table, and only `head` values will be output. It is inefficient but should be addressed separately as a follow-up work.
___
*[pkg/sql/colexec/unordered_distinct.go, line 138 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyZjLEz-JFiLAnKjg:-LzNqwL2EIIa8edKYyLR:bcl3f9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L138)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this be wrapped in a `PerformOperation`? Don't we have a lint rule that enforces this?
</blockquote></details>

Yes, good catch. I think I wrote it initially before we had memory monitoring in place.

No, we don't have linters for `Vec.Append` and `Vec.Copy` calls (only for creating batches, creating and appending columns) because it'll be hard to come up with a regex that would enforce it. It could work if we were to name the variables the same way throughout `colexec` package. Previously, I simply went over all usages of `Copy` and `Append` and made sure that they are accounted for.
___
*[pkg/sql/colexec/unordered_distinct.go, line 146 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyuXw2-rNghksmMsd:-LzNs5qS7bo2R-__OgJS:bl4o59x) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L146)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this `op.sel` need to be "advanced" for the next iteration? If so, would this be caught by randomizing the batch size?
</blockquote></details>

No, it is not needed. We populate `op.sel` on the first call to `Next()` for all batches to be output, and then we copy only a slice of it ([op.outputBatchStart, batchEnd]). I think it would have been caught by the tests if there were a bug with this.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqHi17w-LL0BG75K2:-LzNt86q1Igww9rBnu0g:b-qadz7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L130)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this not `randutil.NewPseudoRand`?
</blockquote></details>

For ease of reproduction of the test failures. I think at some point I was using `randutil.NewPseudoRand` and had a failure that I couldn't reproduce for some reason. I started generating `seed` locally in these tests and never had such a problem afterwards. The seed is always printed out right in the failure.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqWsu2d9ma4al1QPl:-LzNtoI1AFJa8lLozqD5:bluifq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L140)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`<=`?
</blockquote></details>

Thanks, I think more idiomatic is to start from `0` instead :)
___
*[pkg/sql/distsql/columnar_operators_test.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqwKk7K-6WVyRUnDJ:-LzNvheJ9JV_aCCrtycv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L193)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure if I said this before, but we should probably extract these arguments out into a struct.
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 50 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzI-uYpEwilH9ljNn5X:-LzNvijq4TYl1wtRwU16:brpw2eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2159b655c3e81070a703730725d3cde66915ebd0/pkg/sql/distsql/columnar_utils_test.go#L50)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure why the addition of `NULL`s to grouping columns affected this?
</blockquote></details>

It's not the addition of `NULL`s that prompted this change, but the enhancement of the aggregator test. It actually could happen previously, but it wasn't very likely, and now it became more likely, so I hit it a couple of times out of like 10k runs.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 11 of 11 files at r14, 1 of 1 files at r15, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-:-LzbrTtH17T2Qsa2Job-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/unordered_distinct.go, line 102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHxvCtBfrLLO_tM7Ys:-LzbpVo00KaCoB2b79N4:bkfd1ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L102)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, as we discussed, the whole input is stored in the hash table, and only `head` values will be output. It is inefficient but should be addressed separately as a follow-up work.
</blockquote></details>

Could you create an issue for it?
___
*[pkg/sql/colexec/unordered_distinct.go, line 138 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyZjLEz-JFiLAnKjg:-LzbqffGEacqutvuT4r1:b-eq4k4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L138)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, good catch. I think I wrote it initially before we had memory monitoring in place.

No, we don't have linters for `Vec.Append` and `Vec.Copy` calls (only for creating batches, creating and appending columns) because it'll be hard to come up with a regex that would enforce it. It could work if we were to name the variables the same way throughout `colexec` package. Previously, I simply went over all usages of `Copy` and `Append` and made sure that they are accounted for.
</blockquote></details>

Hmm, I wonder what we could do here, it seems like it's easy for something to slip through the cracks.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqHi17w-LL0BG75K2:-LzbqmGu7MLHzV6dYCtH:b-2lu7s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L130)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

For ease of reproduction of the test failures. I think at some point I was using `randutil.NewPseudoRand` and had a failure that I couldn't reproduce for some reason. I started generating `seed` locally in these tests and never had such a problem afterwards. The seed is always printed out right in the failure.
</blockquote></details>

That seems like something we should look into.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-:-LzbxUbS2oXiaX8Ewy64:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/unordered_distinct.go, line 102 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHxvCtBfrLLO_tM7Ys:-Lzbx2A3Dnv8D0BlApkB:b-i7xk6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you create an issue for it?
</blockquote></details>

Done #44404
___
*[pkg/sql/colexec/unordered_distinct.go, line 138 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHyZjLEz-JFiLAnKjg:-Lzbx4fJ2-pu9G491dqR:bf67r5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/293bf9d3f8e35af9e5f005b30d9141251b3f404e/pkg/sql/colexec/unordered_distinct.go#L138)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, I wonder what we could do here, it seems like it's easy for something to slip through the cracks.
</blockquote></details>

I don't have any ideas at the moment :/
___
*[pkg/sql/distsql/columnar_operators_test.go, line 130 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42522#-LzHqHi17w-LL0BG75K2:-LzbxI1Y1WrahfqUYzA_:b-tk1nj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3af32786ae12d6f2b6ee58a7c365546fd30d8ba4/pkg/sql/distsql/columnar_operators_test.go#L130)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That seems like something we should look into.
</blockquote></details>

I don't see it as a big deal. Maybe some time down the line in stabilization period.

**Pull request merged**
