### PR TITLE
sql: allow ALTER TABLE ADD to force a single column family

### LINKED ISSUE #7697: sql: cannot force a new family with ALTER TABLE ADD
There's no way to force a column to be in its own family with the ALTER TABLE ADD syntax. If you try to specify FAMILY information, you have to give a family name and it errors if that name doesn't exist. If you don't specify a FAMILY, the heuristics may assign it to an existing one

### PR DESCRIPTION
**Pull request by danhhz**
Also fix a bug where specifying a family name at table creation time didn't
work.

Closes #7697.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7711)

### CODE REVIEW

**Comment by paperstreet** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/testdata/family, line 86 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMBRp31bkGBDHWoMrmv:-KMBRp31bkGBDHWoMrmw:697176004) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/testdata/family#L86)):*
> ```
> 
> statement ok
> ALTER TABLE abcd ADD COLUMN g INT FAMILY CREATE
> ```

I'm not convinced CREATE is really the best thing here. Can anyone think of precedent from some other part of sql?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711)*

**Comment by knz** [comment]
I'd like to suggest that:
1) newly created families also receive an identifier (optionally?)
2) the syntax be `ADD <colname> <type> CREATE FAMILY <opt_family_name>`

What do you think?

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMETwCAVbhWM-2jc7KJ:877137491)*

**Comment by petermattis** [comment]
I like @knz's suggestion. Should also be clear on what the semantics are if `CREATE FAMILY` is specified by the family already exists. For symmetry with other `CREATE` constructs, it should error and we should add `CREATE IF NOT EXISTS` if desired.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMEt3BkJDAZ8d5X5qAL:1548541717)*

**Comment by paperstreet** [comment]
Very nice, I agree with both of you. This is not the primary thing I'm working on right now, but I'll followup with those changes when I get a minute.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMPGoc_1-pd_tMLN-St:-682481616)*

**Comment by paperstreet** [comment]
RFAL

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMUclPBZ9Yj16YiOri_:677011428)*

**Comment by knz** [comment]
Reviewed 7 of 7 files at r1, 2 of 8 files at r3.
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/create.go, line 301 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgQGLorg16JRLFu79:-KMUgQGMwnWh_kmBHWZ9:-1935504407) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/parser/create.go#L301)):*
> ```Go
> 		buf.WriteString(" FAMILY")
> 		if len(node.Family.Name) > 0 {
> 			buf.WriteString(" ")
> ```

`WriteByte(' ')`

---

*[sql/parser/parse_test.go, line 466 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgTUv-_rRQw5XykCD:-KMUgTUv-_rRQw5XykCE:-866389385) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/parser/parse_test.go#L466)):*
> ```Go
> 		{`ALTER TABLE IF EXISTS a ADD COLUMN IF NOT EXISTS b INT, ADD CONSTRAINT a_idx UNIQUE (a)`},
> 		{`ALTER TABLE a ADD b INT FAMILY fam_a`},
> 		{`ALTER TABLE a ADD b INT FAMILY CREATE`},
> ```

Need a test for if exists and with a family identifier.

---

*[sql/parser/sql.y, line 1533 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUga2WvDDMe-TyQaL8:-KMUga2WvDDMe-TyQaL9:-746984912) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/parser/sql.y#L1533)):*
> ```Yacc
>     $$.val = NamedColumnQualification{Qualification: &ColumnFamilyConstraint{Family: Name($2)}}
>   }
> | FAMILY CREATE
> ```

No opportunity to set a name for the newly created family?

---

*[sql/sqlbase/table.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgg3ULSxtb7f0HJCF:-KMUgg3ULSxtb7f0HJCG:555616582) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/sqlbase/table.go#L68)):*
> ```Go
> 				})
> 			}
> 			if d.Family.Create {
> ```

Again I thinkw e should allow creating a family and setting a name for it. Which means this case should be handled first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711)*

**Comment by paperstreet** [comment]
Push another revision with the WriteByte change but Github hasn't picked it up yet

---

Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/create.go, line 301 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgQGLorg16JRLFu79:-KMUjAaLoaKQAnixhjqo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/parser/create.go#L301)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> `WriteByte(' ')`
</details>
Done.

---

*[sql/parser/parse_test.go, line 466 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgTUv-_rRQw5XykCD:-KMUnVEqqRQwgAelQxvy:743886175) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/parser/parse_test.go#L466)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Need a test for if exists and with a family identifier.
</details>
Ditto old revision : - )

---

*[sql/parser/sql.y, line 1533 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUga2WvDDMe-TyQaL8:-KMUj3AnJg7uYXrO8rZ9:-1258811257) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/parser/sql.y#L1533)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> No opportunity to set a name for the newly created family?
</details>
You're looking at an old revision : - )

---

*[sql/sqlbase/table.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUgg3ULSxtb7f0HJCF:-KMUj6A2YZ3wLIeyMIOp:67742895) ([raw file](https://github.com/cockroachdb/cockroach/blob/c826df430010bf29e4df0d4433becc51fc28af90/sql/sqlbase/table.go#L68)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Again I thinkw e should allow creating a family and setting a name for it. Which means this case should be handled first.
</details>
Ditto old revision

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMUo73xPyQtN-Erl2iw:462731214)*

**Comment by knz** [comment]
Sorry for the mixup in my latest review, Reviewable got me confused there... :'(

---

Reviewed 6 of 8 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/parser/sql.y, line 1557 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUorCuHRNDKa59bMYK:-KMUorCvtXpsFPC1MRtr:-1202129391) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/parser/sql.y#L1557)):*
> ```Yacc
>     $$.val = NamedColumnQualification{Qualification: &ColumnFamilyConstraint{Family: Name($3), Create: true}}
>   }
> | CREATE IF NOT EXISTS FAMILY name
> ```

Probably you want opt_name here too for symmetry.

---

*[sql/sqlbase/structured.go, line 916 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUpZpSw3GR8PnmpyKC:-KMUpZpTyyenmMFWACG0:-752286478) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/sqlbase/structured.go#L916)):*
> ```Go
> 	if idx == -1 {
> 		if create {
> 			desc.AddFamily(ColumnFamilyDescriptor{Name: family, ColumnNames: []string{col}})
> ```

Please add a comment here to explain that a new name will be created automatically (by which function?) if family == "".

---

*[sql/testdata/family, line 101 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUpoDw4FbYGbJTee2-:-KMUpoDxisGCLBSi7B_d:-1179679525) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/testdata/family#L101)):*
> ```
> 
> statement ok
> ALTER TABLE abcd ADD COLUMN j INT CREATE IF NOT EXISTS FAMILY f_j
> ```

Test "if not exists" without a family name too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMUogQ34oycWmsdgjny:-908987543)*

**Comment by paperstreet** [comment]
I figured that was what happened

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/parser/sql.y, line 1557 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUorCuHRNDKa59bMYK:-KMUqe4FgvRwmof195_T:-288434370) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/parser/sql.y#L1557)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Probably you want opt_name here too for symmetry.
</details>
`IF NOT EXISTS` is nonsensical without a name

---

*[sql/sqlbase/structured.go, line 916 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUpZpSw3GR8PnmpyKC:-KMUrBYMfrO0XYK-A_yo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/sqlbase/structured.go#L916)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Please add a comment here to explain that a new name will be created automatically (by which function?) if family == "".
</details>
Done.

---

*[sql/testdata/family, line 101 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-KMUpoDw4FbYGbJTee2-:-KMUqqQ68KDFOtTFpkgL:1964612069) ([raw file](https://github.com/cockroachdb/cockroach/blob/948297cc00d1ba8f98724a6a8421770a759b089a/sql/testdata/family#L101)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Test "if not exists" without a family name too.
</details>
`IF NOT EXISTS` is nonsensical without a name, it would just be a parse error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMUqlTDpk2Uyb7_Ptss:1788723145)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMUysgTsupXkQ67U-FL:1417088721)*

**Comment by paperstreet** [comment]
Thanks for the review!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7711#-:-KMV6sLku0axrUyeG004:-588504495)*

**Pull request merged**
