### PR TITLE
release: build linux-arm binary for release

### PR DESCRIPTION
**Pull request by rickystewart**
Release note (build change): Experimental binaries are available for 64-bit ARM systems running Linux. Experimental binaries are not yet qualified for production use.
Release justification: build *experimental* Linux ARM64 binary for release

### CODE REVIEW

**Review by rail — APPROVED** [review]
Woooooooo!

**Comment by rickystewart** [comment]
bors r=rail

**Review by jlinder — APPROVED** [review]
One thing I'd ask is that a release note be added to the commit in this PR. Making _experimental_ Linux ARM64 binaries available is a notice we want to add in the release notes for the release this appears in.

Otherwise, LGTM.

**Comment by rickystewart** [comment]
bors r=rail,jlinder

**Pull request merged**
