### PR TITLE
authserver: add support to access DB console APIs via JWT

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
Previously, the DB Console APIs could only be accessed using HTTP
cookies. This was undesirable for some of our customers and they
proposed to be able to access the DB console APIs via JWT
authentication.

This PR looks up the JWT within the Authorization header, and if
provided, verifies its signature against the configured cluster
settings for Cluster SSO.
In case of multiple matched identities, the requester may provide
the user to be used as part of the X-Cockroach-User request header.

Epic: [CRDB-40211](https://cockroachlabs.atlassian.net/browse/CRDB-40211)
Part of: https://cockroachlabs.atlassian.net/browse/CRDB-41989

Release note (enterprise change, ops change, security update):
Allowed access to DB console APIs via JWT, which can be supplied as a
Bearer token in Authorization header.

### CODE REVIEW

**Comment by pritesh-lahoti** [comment]
Keeping the PR in draft stage due to:
- dependent open PRs
- pending unit tests

**Review by souravcrl — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6ujfGX3QsbWG_Asuzz:-O6ujfGX3QsbWG_Asv--:b37urtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2734f68e07809579987316c3ecf85e6a6fdf91/pkg/ccl/jwtauthccl/authentication_jwt.go#L203)):*
> ```Go
> 	user, authError = authenticator.RetrieveIdentity(ctx, user, tokenBytes, identMap)
> 	if authError != nil {
> 		return
> ```

nit: we should we return the authError from `authenticator.RetrieveIdentity` since we loose some of the authentication error logs incase we decide not to send it back to pgwire.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6ul8067zN8CR4Z36Bg:-O6ul8067zN8CR4Z36Bh:b2t1iqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2734f68e07809579987316c3ecf85e6a6fdf91/pkg/ccl/jwtauthccl/authentication_jwt.go#L309)):*
> ```Go
> 		// If the username is not provided, and we match it to a single user,
> 		// then use that user identity.
> 		if user.IsEmptyRole() && len(acceptedUsernames) == 1 {
> ```

If I try cluster SSO with "" (empty user) string, will this cause validation issues since now we accept empty SQL user also?
```
export PGPASSWORD='password'
psql -h localhost -p 26257 -U '' 
```
Should we have another check in `ValidateJWTLogin` which verifies user.IsEmptyRole() == false?
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6utyeV4kZXUJcpMnkl:-O6utyeV4kZXUJcpMnkm:b-uvnqak) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/ccl/jwtauthccl/authentication_jwt.go#L242)):*
> ```Go
> 	identMap *identmap.Conf,
> ) (retrievedUser username.SQLUsername, authError error) {
> 	unverifiedToken, err := jwt.ParseInsecure(tokenBytes)
> ```

We already had checked the JWT token for non parsability in `ValidateJWTLogin`, we do this here again. Is the duplication necessary or will be move the `RetrieveIdentity` call to authJWT in pgwire, so we will need to independently verify the token in each of the calls? 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uwf-t9-Xk5OdxecA4:-O6uwf-t9-Xk5OdxecA5:b-q51ywf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/ccl/jwtauthccl/authentication_jwt.go#L310)):*
> ```Go
> 		// then use that user identity.
> 		if user.IsEmptyRole() && len(acceptedUsernames) == 1 {
> 			return acceptedUsernames[0], nil
> ```

I would like to propose instead of validating `len(acceptedUsernames) == 1` we can simply validate if there is atleast 1 acceptedUsername and return that here:
```
// If the username is not provided, and we match it to a first user from token principal,
// then use that as user identity.
if user.IsEmptyRole() && len(acceptedUsernames) > 0 {
    return acceptedUsernames[0], nil
}
```
___
*[`pkg/server/authserver/api.go` line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uw2LDAodOnsjULl3S:-O6uw2LDAodOnsjULl3T:b-2hh3y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/api.go#L111)):*
> ```Go
> 	// - the username associated with the JWT (if validated), and
> 	// - an error for any internal errors which prevented validation.
> 	VerifyJWT(ctx context.Context, jwtStr, usernameOptional string) (bool, string, error)
> ```

nit: named return values can be used here for improving readability.
___
*[`pkg/server/authserver/authentication.go` line 534 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uujOL1GttkhXcHYYK:-O6uujOL1GttkhXcHYYL:b-rx7qzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L534)):*
> ```Go
> 	// Verify the JWT against the user identity. The configured cluster settings
> 	// for Cluster SSO via JWT are honored.
> 	if _, err = jwtVerifier.j.ValidateJWTLogin(
> ```

`RetrieveIdentity` is duplicated in the code path as we already made the call earlier to get the retrieved user. Is the plan to finally move the RetrieveIdentity logic out of ValidateJWTLogin and an independent call will be made from `authJWT` in pgwire/auth_methods.go`?
___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O6upTMN7cl2RThO5KhZ:bx847kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
> ```Go
> 		userName, jerr = am.verifyJWT(req)
> 		if jerr == nil {
> 			req = req.WithContext(ContextWithHTTPAuthInfo(req.Context(), userName, 0))
> ```

QQ: we are initializing the context with session ID = 0, won't observability for the session be affected since we will not be able to track down the session information from the context, and it won't be logged for JWT sessions? Should we still have the existing cookie and session information for JWT auth attempts also, just in case we need that for session tracking or do you feel it is redundant at this point? 

I would have liked JWT issuer or some unique ID from the JWT(can be a composite key with username, issuer and claim to be used to generate session UID) which wouldn't need a separate entry into the system.web_sessions table initialized using `authserver.NewAuthSession()` and can just be put into the session context for logging later and is idempotent for same JWT token with same `X-Cockroach-User` value. Although this may lead to some confusion, since multiple CRDB nodes could be logging the same session UID when it might be expected that each node starts a separate session with each web UI client.
___
*[`pkg/server/authserver/authentication.go` line 733 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uxeTxC7yKxVb3ienv:-O6uxeTxC7yKxVb3ienw:b6maj9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L733)):*
> ```Go
> // verifyJWT retrieves the JWT from the Authorization request header,
> // verifies its signature and returns the associated username.
> func (am *authenticationMux) verifyJWT(req *http.Request) (string, error) {
> ```

nit:  named return types can be used for readability.

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6ul8067zN8CR4Z36Bg:-O82HkA4DahsckFxLT45:b-8qkxcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2734f68e07809579987316c3ecf85e6a6fdf91/pkg/ccl/jwtauthccl/authentication_jwt.go#L309)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

If I try cluster SSO with "" (empty user) string, will this cause validation issues since now we accept empty SQL user also?
```
export PGPASSWORD='password'
psql -h localhost -p 26257 -U '' 
```
Should we have another check in `ValidateJWTLogin` which verifies user.IsEmptyRole() == false?
</blockquote></details>

Yes, this is now a side-effect that the username is only required if the token potentially matches multiple identities within the cluster, so technically this should work. But looks like there is an explicit validation to disallow cluster SSO with an empty username.
```
Username cannot be empty when a password is provided.
Failed running "sql"
```
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 242 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6utyeV4kZXUJcpMnkl:-O82GKkBDs6TPUb7igYx:b-ra8kt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/ccl/jwtauthccl/authentication_jwt.go#L242)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

We already had checked the JWT token for non parsability in `ValidateJWTLogin`, we do this here again. Is the duplication necessary or will be move the `RetrieveIdentity` call to authJWT in pgwire, so we will need to independently verify the token in each of the calls?
</blockquote></details>

For the DB console flow, `RetrieveIdentity` gets called prior to `ValidateJWTLogin`, so the duplication is now in `ValidateJWTLogin`. However, that is required for cluster SSO related requests.
We could have had a new interface method to accept the token object (in addition to bytes), but that did not seem ideal.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uwf-t9-Xk5OdxecA4:-O86L37f-arhtGyQzBZp:b4xe3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/ccl/jwtauthccl/authentication_jwt.go#L310)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

I would like to propose instead of validating `len(acceptedUsernames) == 1` we can simply validate if there is atleast 1 acceptedUsername and return that here:
```
// If the username is not provided, and we match it to a first user from token principal,
// then use that as user identity.
if user.IsEmptyRole() && len(acceptedUsernames) > 0 {
    return acceptedUsernames[0], nil
}
```
</blockquote></details>

This could make the behaviour unpredictable, as it will then depend on the order of identities in the token. Depending on the matched identity, some of the actions may or may not be allowed, hence it could easily get confusing.
Mandating the username header in such cases seemed to be a fair requirement, similar to username-token auth for cluster SSO.
___
*[`pkg/server/authserver/authentication.go` line 534 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uujOL1GttkhXcHYYK:-O86dOPf0n42o086Mk_O:b-t3q42g) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L534)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

`RetrieveIdentity` is duplicated in the code path as we already made the call earlier to get the retrieved user. Is the plan to finally move the RetrieveIdentity logic out of ValidateJWTLogin and an independent call will be made from `authJWT` in pgwire/auth_methods.go`?
</blockquote></details>

Yes, I did consider this option, but it felt counter-intuitive. As a caller, it needs to be made explicit that they need to call into `RetrieveIdentity` prior to `ValidateJWTLogin`. By definition, the `ValidateJWTLogin` method is expected to perform all the required validations.
Separately, I could run a benchmark to see the potential impact on latency due to this duplication. My hunch is that it would be minimal in the context of a DB console user.
___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O86Lzhq3fh1-KjOxcci:b8ilika) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

QQ: we are initializing the context with session ID = 0, won't observability for the session be affected since we will not be able to track down the session information from the context, and it won't be logged for JWT sessions? Should we still have the existing cookie and session information for JWT auth attempts also, just in case we need that for session tracking or do you feel it is redundant at this point? 

I would have liked JWT issuer or some unique ID from the JWT(can be a composite key with username, issuer and claim to be used to generate session UID) which wouldn't need a separate entry into the system.web_sessions table initialized using `authserver.NewAuthSession()` and can just be put into the session context for logging later and is idempotent for same JWT token with same `X-Cockroach-User` value. Although this may lead to some confusion, since multiple CRDB nodes could be logging the same session UID when it might be expected that each node starts a separate session with each web UI client.
</blockquote></details>

Maintaining a session essentially kills the purpose of using JWTs. But if it is useful for auditing/debugging, I would look into understanding this better.

**Review by souravcrl — COMMENTED** [review]
Are there still any TODOs for this PR or are we good to merge?

> Reviewed 1 of 5 files at r4, 3 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-:-O87zK73Bc_biXdvBMTg:b-6d4dov)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O88-S7R5HFJ6-PY35dE:b-kurdj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
> ```Go
> 	defer authenticator.mu.Unlock()
> 
> 	if !authenticator.mu.enabled {
> ```

I feel we should add the same gate for `RetrieveIdentity` also, as this tracks whether jwt was enabled for the cluster or not and other settings were properly loaded.
___
*[`pkg/server/authserver/authentication.go` line 534 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uujOL1GttkhXcHYYK:-O87ximG9ktvDVmsLCi0:b6ny9ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L534)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Yes, I did consider this option, but it felt counter-intuitive. As a caller, it needs to be made explicit that they need to call into `RetrieveIdentity` prior to `ValidateJWTLogin`. By definition, the `ValidateJWTLogin` method is expected to perform all the required validations.
Separately, I could run a benchmark to see the potential impact on latency due to this duplication. My hunch is that it would be minimal in the context of a DB console user.
</blockquote></details>

Makes sense. We could add a TODO to do it at a later point if we observe perf degradation.
___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O87y4VkAwcgw_7wfVYx:bxve9g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Maintaining a session essentially kills the purpose of using JWTs. But if it is useful for auditing/debugging, I would look into understanding this better.
</blockquote></details>

Sure, I think we can track that separately and move ahead with this PR if you feel scope would be more.

**Review by pritesh-lahoti — COMMENTED** [review]
Added unit-tests and have opened up for broader review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-:-O8IObY8CeVbyNQzcSVc:bgi4u44)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O8IQxln63gJ0Jwbn14l:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

I feel we should add the same gate for `RetrieveIdentity` also, as this tracks whether jwt was enabled for the cluster or not and other settings were properly loaded.
</blockquote></details>

Done!
___
*[`pkg/server/authserver/authentication.go` line 534 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uujOL1GttkhXcHYYK:-O8ISU5KC5uhJeCVN2V-:bkd5ega) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L534)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Makes sense. We could add a TODO to do it at a later point if we observe perf degradation.
</blockquote></details>

Added a TODO
___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O8ISWOA8hZAZ5wIOntQ:bc4n35j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Sure, I think we can track that separately and move ahead with this PR if you feel scope would be more.
</blockquote></details>

I'll think further and decide if it needs to be addressed in this PR or could be tracked separately. Thank you for the call-out!

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O8IoBZtDHzltNmes3zm:b7im2if) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Done!
</blockquote></details>

I had to revert this change back, as the flow gets stuck when `RetrieveIdentity` is called from within `ValidateJWTLogin`, as the lock is already acquired.

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O8L2wRW3I6grUJlTdST:b-t1vhtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

I'll think further and decide if it needs to be addressed in this PR or could be tracked separately. Thank you for the call-out!
</blockquote></details>

Decided to track separately - https://cockroachlabs.atlassian.net/browse/CRDB-42734

**Review by souravcrl — COMMENTED** [review]
> Reviewed 5 of 5 files at r8, 5 of 5 files at r9, 6 of 6 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O8LDH8K3HGOljOdfU5Z:b-re16an) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

I had to revert this change back, as the flow gets stuck when `RetrieveIdentity` is called from within `ValidateJWTLogin`, as the lock is already acquired.
</blockquote></details>

Can we just validate that JWT is enabled or nor before calling `RetrieveIdentity` ? We could appropriately error out if JWT authentication is not enabled for the cluster. 
___
*[`pkg/server/authserver/authentication.go` line 534 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6uujOL1GttkhXcHYYK:-O8LE16y3zWdTbIUNNqv:b2nh4n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L534)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Added a TODO
</blockquote></details>

:1:
___
*[`pkg/server/authserver/authentication.go` line 640 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O6upTMN7cl2RThO5KhY:-O8LE2GnA7aCw-mb84C0:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb4976dd3421260461381b642562f9710123b3f9/pkg/server/authserver/authentication.go#L640)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Decided to track separately - https://cockroachlabs.atlassian.net/browse/CRDB-42734
</blockquote></details>

:+1: 
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 381 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O8LH1Sh2CghRIk35w5-:-O8LH1Sh2CghRIk35w50:b31c76n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ed5a7f51f27c6eb7029b7b1d7251d73795cb115/pkg/ccl/testccl/authccl/auth_test.go#L381)):*
> ```Go
> 					return "ok " + dbName, nil
> 
> 				case "console_api_auth":
> ```

I feel we could add a case for auth logs and verify those as well inline with the `pgwire/auth_test.go` here: https://github.com/cockroachdb/cockroach/blob/94366ce9e697b8cbad2c7fbf9939c7a04d1eb986/pkg/sql/pgwire/auth_test.go#L361-L439
This would ensure we are erroring correctly.

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O8LdXnV59yUbjrr8Ggg:bac22zf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Can we just validate that JWT is enabled or nor before calling `RetrieveIdentity` ? We could appropriately error out if JWT authentication is not enabled for the cluster.
</blockquote></details>

I believe the only better way to do this would be when `RetrieveIdentity` moves out of `ValidateJWTLogin` completely.
As of right now, there is no major validation/verification being done by `RetrieveIdentity`, so planning to skip the JWT enabled check.
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 381 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O8LH1Sh2CghRIk35w5-:-O8LgK8H5BZgzDl3jS0O:b4l58ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ed5a7f51f27c6eb7029b7b1d7251d73795cb115/pkg/ccl/testccl/authccl/auth_test.go#L381)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

I feel we could add a case for auth logs and verify those as well inline with the `pgwire/auth_test.go` here: https://github.com/cockroachdb/cockroach/blob/94366ce9e697b8cbad2c7fbf9939c7a04d1eb986/pkg/sql/pgwire/auth_test.go#L361-L439
This would ensure we are erroring correctly.
</blockquote></details>

Makes sense. Would suggest taking this up separately.

**Review by souravcrl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130779)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 155 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O88-S7R5HFJ6-PY35dD:-O8LybuB8Cg-VAgZhotb:b-rsu3mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b30211d303cd8e05d8a7fac653f13fb7e3b8/pkg/ccl/jwtauthccl/authentication_jwt.go#L155)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

I believe the only better way to do this would be when `RetrieveIdentity` moves out of `ValidateJWTLogin` completely.
As of right now, there is no major validation/verification being done by `RetrieveIdentity`, so planning to skip the JWT enabled check.
</blockquote></details>

ok, makes sense
___
*[`pkg/ccl/testccl/authccl/auth_test.go` line 381 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/130779#-O8LH1Sh2CghRIk35w5-:-O8LyZFs8fhI6K9AleZ4:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ed5a7f51f27c6eb7029b7b1d7251d73795cb115/pkg/ccl/testccl/authccl/auth_test.go#L381)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Makes sense. Would suggest taking this up separately.
</blockquote></details>

:+1:

**Comment by pritesh-lahoti** [comment]
bors r=souravcrl

**Comment by pritesh-lahoti** [comment]
blathers backport 24.1 24.2

**Pull request merged**
