### PR TITLE
roachtest: test 32 node import/restore

### PR DESCRIPTION
**Pull request by tbg**
30+ node clusters have been repeat offenders in internal investigations,
mostly due to getting into a state in which heartbeats fail and Raft
commands get stuck, and more specifically triggered by backup/restore
activity. The hope is that this test can reproduce some of that.

For starters, add some logging that prints whenever the gossip_alerts
table is nonempty (which hints at stuck proposals, liveness errors,
etc). The intention is to make this fail the tests in the future.

Additionally, regularly print the disk usage stats because that's
something some users have shown interest in understanding better.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
RFAL, though I'll run the affected tests manually once to see what will happen. (I've run tidbits of them enough to know that the added checks are working).

**Comment by tschottdorf** [comment]
import/tpch/nodes=32 *almost* made it through, but:

```
$  /home/tschottdorf/go/bin/roachprod run tobias-32:1-32 -- ./healthcheck {log-dir}
tobias-32: ./healthcheck {log-dir} 32/32
   1:
   2:
   3:
   4: /home/tschottdorf/logs/cockroach.log:W180703 15:57:35.440592 251 storage/node_liveness.go:551  [n21,hb] slow heartbeat took 1.4s
/home/tschottdorf/logs/cockroach.tobias-32-0004.tschottdorf.2018-07-03T14_43_49Z.005755.log:W180703 15:57:35.440592 251 storage/node_liveness.go:551  [n21,hb] slow heartbeat took 1.4s
Process exited with status 1
   5:
   6:
   7:
   8:
   9: /home/tschottdorf/logs/cockroach.log:W180703 15:55:24.296137 165 storage/node_liveness.go:551  [n4,hb] slow heartbeat took 1.0s
/home/tschottdorf/logs/cockroach.tobias-32-0009.tschottdorf.2018-07-03T14_43_49Z.005741.log:W180703 15:55:24.296137 165 storage/node_liveness.go:551  [n4,hb] slow heartbeat took 1.0s
Process exited with status 1
  10:
  11:
  12:
  13:
  14:
  15: /home/tschottdorf/logs/cockroach.log:W180703 15:58:17.500110 277 storage/node_liveness.go:551  [n29,hb] slow heartbeat took 2.7s
/home/tschottdorf/logs/cockroach.tobias-32-0015.tschottdorf.2018-07-03T14_43_49Z.005670.log:W180703 15:58:17.500110 277 storage/node_liveness.go:551  [n29,hb] slow heartbeat took 2.7s
Process exited with status 1
  16:
  17:
  18:
  19:
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:
  29:
  30:
  31:
  32:
```

**Comment by a-robinson** [comment]
:lgtm: but I'm a little surprised that's all the test found. Can we consider it a good test yet if it isn't able to reproduce the problems we've heard about?

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/cmd/roachtest/cluster.go, line 1011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW1jQqBV0j2mgH5ElZ:-LGW1jQqBV0j2mgH5El_:b-nlalik) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/cluster.go#L1011)):*
> ```Go
> }
> 
> // getDiskUsageInByte does what's on the tin. nodeIdx starts at one.
> ```

It bothers me that there isn't an `s` on the end of this. No need to change if you don't want, though.

---

*[pkg/cmd/roachtest/import.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW-Am_5rNddYIiN0ps:-LGW-AmaD5ZdpKwdlH2d:brz9swx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/import.go#L70)):*
> ```Go
> 
> func registerImportTPCH(r *registry) {
> 	for _, n := range []int{4, 8, 32} {
> ```

These tests just run nightly, right? Much more frequently could start to get fairly expensive.

---

*[pkg/cmd/roachtest/restore.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW0s1o5hUcYqhPV1Hs:-LGW0s1o5hUcYqhPV1Ht:b-xvay9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/restore.go#L80)):*
> ```Go
> 		return err
> 	}
> 	const runCheck = "./healthcheck"
> ```

Style nit, but in case there's a reason I might want to know, why not `.sh`?

---

*[pkg/cmd/roachtest/restore.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW1yc58feGTz4NPdVy:-LGW1yc58feGTz4NPdVz:bjnlyn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/restore.go#L154)):*
> ```Go
> 			bytesUsed = append(bytesUsed, cur)
> 		}
> 		sort.Slice(bytesUsed, func(i, j int) bool { return bytesUsed[i] > bytesUsed[j] }) // descending
> ```

1. Don't you think we're going to be interested in which node has the most bytes used, not just how many bytes are used?
2. If not, there's `sort.Ints(bytesUsed)` for this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-:-LGW2I9qAc4ncZHQxZAr:b-9p7u9w)*

**Comment by tschottdorf** [comment]
restore2TB also failed on a slow heartbeat:

```
   9: /home/tschottdorf/logs/cockroach.log:W180703 16:48:22.959519 148 storage/node_liveness.go:551  [n3,hb] slow heartbeat took 1.2s
/home/tschottdorf/logs/cockroach.tobias-32-0009.tschottdorf.2018-07-03T16_44_31Z.011772.log:W180703 16:48:22.959519 148 storage/node_liveness.go:551  [n3,hb] slow heartbeat took 1.2s
```

>  I'm a little surprised that's all the test found. Can we consider it a good test yet if it isn't able to reproduce the problems we've heard about?

Yes and no, it's definitely testing something that others have had problems with. If we're not seeing these problems, it's more likely something in their setup. AWS comes to mind, I hope I can just run these tests against an AWS cluster as well.

TFTR! I'll respond to your feedback later.

**Review by tbg — COMMENTED** [review]
Updated, could you take another look? I'm now using crdb_internal.gossip_alerts and am not failing the test when it sees something (only logging). I actually managed to get a clean run of restore2tb with this. However, import/tpch/nodes=32 just hung until the cluster was GC'ed. The health checker complained about slow raft proposals, so it seems that something seems to have wedged.
This will be easier to diagnose when it happens on teamcity, so my suggestion is to go ahead and merge this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-:-LKRDglU2Bt5xNDf-JLB:b-ou2uxi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/cluster.go, line 1011 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW1jQqBV0j2mgH5ElZ:-LKRA4oR4W8TJuxhLSbW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/cluster.go#L1011)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It bothers me that there isn't an `s` on the end of this. No need to change if you don't want, though.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/import.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW-Am_5rNddYIiN0ps:-LKRA7RI5DwohN2F5GwS:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/import.go#L70)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

These tests just run nightly, right? Much more frequently could start to get fairly expensive.
</blockquote></details>

Yes.
___
*[pkg/cmd/roachtest/restore.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW0s1o5hUcYqhPV1Hs:-LKRADOQ8Howenz8igX6:bckulq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/restore.go#L80)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Style nit, but in case there's a reason I might want to know, why not `.sh`?
</blockquote></details>

Done. (The code isn't there any more).
___
*[pkg/cmd/roachtest/restore.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LGW1yc58feGTz4NPdVy:-LKRDbiz8wnMX2htqEem:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb057a9d44733c260dcc1c7bc53b99755f0e23b1/pkg/cmd/roachtest/restore.go#L154)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

1. Don't you think we're going to be interested in which node has the most bytes used, not just how many bytes are used?
2. If not, there's `sort.Ints(bytesUsed)` for this.
</blockquote></details>

Done.

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-:-LKYL7fF-eXfse4d8s8p:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/restore.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27104#-LKYKott3U8UxWyzVIdF:-LKYKott3U8UxWyzVIdG:b-kdocrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/950eb097055eea2ca51de9b8742f9a50e24db5cb/pkg/cmd/roachtest/restore.go#L121)):*
> ```Go
> 			}
> 			if len(rr) > 0 {
> 				logger.printf(rr.String() + "\n")
> ```

Why the extra newline when `rr.String()` already ends with one?

**Comment by tschottdorf** [comment]
Finally getting around to landing this. Changed a few minor things and giving things a test run:

```
--- PASS: restore2TB/nodes=32 (2248.61s)
```

the other two are still running (1:10h in).

**Comment by tschottdorf** [comment]
The import-tpch-nodes-32 test shows various health alerts of the queues failing to process. For the raft log queue, I see "requested index at commit not found". Then there's a lot of `queue.replicagc.process.failure`, the failure I saw was

```
E181006 12:01:08.000811 328120 storage/queue.go:791  [n17,replicaGC,s16,r2663/4:/Table/53/1/551{60525…-87222…}] context deadline exceeded
```

and then of course there's lots of snapshot throttling

```
snapshot failed: (n10,s7):?: remote declined preemptive snapshot ad3f46bb at applied index 21: store busy applying snapshots
```

Going through these health alerts is one instance where it'd be super helpful to just have a rundown of queue errors encountered by the various queues. cc @andreimatei, perhaps the event logs could do that.

**Comment by tschottdorf** [comment]
I'm also curious what we'd want the logfiles to look like during this operation in an ideal world (i.e. no unexpected errors). Nothing interesting is happening, so shouldn't the logs basically look dormant?

There's lots of activity in the logs, mostly thanks to rebalancing (which implies snapshots).

**Comment by tschottdorf** [comment]
the 32 node version fails just like https://github.com/cockroachdb/cockroach/issues/30793, which I suppose is expected.

bors r=a-robinson

**Pull request merged**
