### PR TITLE
ui: update changefeed metrics page

### LINKED ISSUE #97931: changefeedccl: Fix max behind nanos metric
Max behind nanos metric has been the source of large number of
escalations -- often times because it's confusing metric.

Concretely: max behind nanos needs to be renamed.
I propose renaming this metric to be "checkpoint lag" (or something similar)
to communicate that this is *not* message latency, but an indicator how
far behind the changefeed checkpoint is.

Before renaming/changing it, we should find out what the process for
retiring this metric might be.  I suspect that we can't easily remove
it given how widely it is used.  Instead, we should introduce a new metric,
with better behavior and name, and show that metric in the console.

It would be nice to also make sure that this metric doesn't jump around during restarts
and behaves sensibly during initial scan.

Jira issue: CRDB-24970

Epic CRDB-9181

### LINKED ISSUE #98085: changefeedccl: Rename Sink Byte Traffic view in db console
Sink byte traffic reflects the volume of bytes we've emitted out of the database 

QYKudzpNqwBTBWamzUWpvuVWYj687-mD4rpxNLS2qrDLoOsY9RH3qM_SIogPxoJ_ySJ8FXVJMky6nrOKycKRAUYucwZcQya45EseFeKm4C9fxu8BPOpAZ6kagALI

We should rename this view to "Emitted Bytes" which more clearly reflects the actual information we're sending out.

Jira issue: CRDB-25068

Epic CRDB-9181

### LINKED ISSUE #98086: changefeedccl: add commit latency to db console metics page
Commit latency tracks the difference between the event's MVCC timestamp and the time it is acknowledged by the downstream sink. This is the latency metric we are recommending customers use (over max changefeed latency). We should add p99 commit latency as the first view in the changefeed db console metrics page.

### LINKED ISSUE #98088: changefeedccl: add backfill pending ranges to db console
The metric backfill_pending_ranges tracks the number of ranges we have left to send out when performing a backfill. This is the only indication we give to users that a backfill is progressing and way to estimate time to completion. This is an important enough metric that we should include it in the db console changefeed metrics page. We could also add backfill count to this to give an indication of how many backfills those bytes are spread between.

### LINKED ISSUE #99409: changefeedccl: change max behind nanos description
The max_behind_nanos description in the status_vars page is: Largest commit-to-emit duration of any running feed

We should change this to be "time since last checkpoint"

Jira issue: CRDB-26155

### LINKED ISSUE #100640: cdc,dbconsole: add Kafka schema registry retries to DB Console
**Is your feature request related to a problem? Please describe.**

We’ve found that schema registry retries can be expensive, and lack observability.

**Describe the solution you'd like**

Add `changefeed.schema_registry.retry_count` metric to the DB Console changefeed page, which was introduced in [this PR](https://github.com/cockroachdb/cockroach/pull/98135).

**Additional context**
- https://github.com/cockroachdb/cockroach/issues/99221
- https://github.com/cockroachdb/cockroach/pull/99833

Jira issue: CRDB-26533

Epic CRDB-9181

### PR DESCRIPTION
**Pull request by samiskin**
Resolves https://github.com/cockroachdb/cockroach/issues/98085
Resolves https://github.com/cockroachdb/cockroach/issues/98088
Resolves https://github.com/cockroachdb/cockroach/issues/99409
Resolves https://github.com/cockroachdb/cockroach/issues/100640
Resolves https://github.com/cockroachdb/cockroach/issues/97931
Resolves https://github.com/cockroachdb/cockroach/issues/98086

This PR does the following changes:
- Added a `scale` parameter to `Metrics` so that I could support a duration metric that's being emitted in Seconds rather than Nanoseconds.  Would like frontend feedback on whether this is ok.
- Added support for minutes and hours in Duration graphs
- There is now a "Changefeed Status" graph to show counts of Running/Paused/Failed
- There is now a "Commit Latency" graph to show P50,P90, and P99 commit latencies
- Sink Byte Traffic is now Emitted Bytes
- Sink Timings has been removed because I don't believe either of the metrics exist anymore
- Max Changefeed Latency is now Max Checkpoint Latency
- There is now a Backfill Pending Ranges graph
- There is now a Protected Timestamp Max Age graph
- There is now a Schema Registry Registrations graph

Screenshot 2023-04-18 at 5 02 33 PM
Screenshot 2023-04-19 at 12 48 19 PM
Screenshot 2023-04-18 at 4 19 24 PM
Screenshot 2023-04-18 at 4 19 42 PM

Release note (ui change): The metrics page for changefeeds has been updated with new graphs to track backfill progress, protected timestamps age, and number of schema registry registrations.

### CODE REVIEW

**Comment by shermanCRL** [comment]
So great! Should we take the opportunity to add some explanatory text next to each of the graphs?

**Comment by miretskiy** [comment]
do we want to include number of currently running/paused changefeeds?

**Comment by jayshrivastava** [comment]
We can close this one too! https://github.com/cockroachdb/cockroach/issues/97931

**Comment by samiskin** [comment]
@shermanCRL I have tooltip text for "Max Checkpoint Latency", "Protected Timestamp Max Age", and "Backfill Pending Ranges", and I think the others are pretty self explanatory.

@miretskiy Added
Screenshot 2023-04-18 at 5 02 33 PM

**Comment by miretskiy** [comment]
How difficult is it to change the scale on those graphs? Max protected age -- would be nice not to divide by 1e9;
I don't think we need more than a minute granularity.

**Comment by samiskin** [comment]
Age gets shown as Seconds right now, I looked into adding minutes/hours and it's doable just needs new frontend changes since they currently only support up to seconds.  I'll make it show "1h 2m 3s" and see what they think about it.

**Comment by shermanCRL** [comment]
@samiskin Cool though I think a bit of text saying why you care about this, and how to interpret it -- does it represent a problem -- may help. Maybe a link to relevant docs? I’m imagining that it might prevent an escalation or get a user to a solution faster. @amruss what do you think?

**Comment by samiskin** [comment]
Added support for minutes and hours
Screenshot 2023-04-20 at 1 57 56 PM

**Review by dhartunian — COMMENTED** [review]
nice! The latest screenshot example looks great. my comments are just around some docs/tests.

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-:-NTVR_-G10agdk7Lb7x3:bsv62is)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @samiskin)

___
*[`pkg/ui/workspaces/cluster-ui/src/graphs/utils/domain.ts` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NTVQURkA3mPfzsg6lae:-NTVQURl0rD_R5kVcI7n:bmfssst) ([raw file](https://github.com/cockroachdb/cockroach/blob/191d065422e27ae63ebaedd679c38e518a16e632/pkg/ui/workspaces/cluster-ui/src/graphs/utils/domain.ts#L224)):*
> ```XML
> }
> 
> function ComputeDurationAxisDomain(extent: Extent): AxisDomain {
> ```

can you write a few tests for this?
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NTV2OT10EcLlMtjWaFs:-NTV2OT23mCPsZsVP2Uw:bxelprv) ([raw file](https://github.com/cockroachdb/cockroach/blob/191d065422e27ae63ebaedd679c38e518a16e632/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx#L92)):*
> ```XML
>   title?: string;
>   rate?: boolean;
>   scale?: number;
> ```

I know the existing code doesn't do this but would you mind adding documentation for this parameter? Seems like others might be motivated to use it.

**Review by samiskin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @HonoreDB)

___
*[`pkg/ui/workspaces/cluster-ui/src/graphs/utils/domain.ts` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NTVQURkA3mPfzsg6lae:-NT_lQxy8Tm_B-LvrDw4:b6gsstw) ([raw file](https://github.com/cockroachdb/cockroach/blob/191d065422e27ae63ebaedd679c38e518a16e632/pkg/ui/workspaces/cluster-ui/src/graphs/utils/domain.ts#L224)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can you write a few tests for this?
</blockquote></details>

Added tests in a new `pkg/ui/workspaces/cluster-ui/src/graphs/utils/domain.spec.ts` file 👍
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NTV2OT10EcLlMtjWaFs:-NT_lXJB7HFYCHFt1dpO:b2uofo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/191d065422e27ae63ebaedd679c38e518a16e632/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx#L92)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I know the existing code doesn't do this but would you mind adding documentation for this parameter? Seems like others might be motivated to use it.
</blockquote></details>

Added comment 👍

**Review by jayshrivastava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @HonoreDB, and @samiskin)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NV5rL_l2LFd66cYSwNV:-NV5rL_l2LFd66cYSwNW:b-qhn3gx) (no related file):*
This is really great work :)

___
___
*[`pkg/ccl/changefeedccl/metrics.go` line 386 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NV5nqagBIepIXJ_U66Z:-NV5nqagBIepIXJ_U66_:b-ln7zq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f01834469d1e739c2ca0d016b940efe1beff720d/pkg/ccl/changefeedccl/metrics.go#L386)):*
> ```Go
> 	metaChangefeedMaxBehindNanos = metric.Metadata{
> 		Name:        "changefeed.max_behind_nanos",
> 		Help:        "Time since the changefeed last checkpointed its progress",
> ```

The comment implies that it's the time since the most recent checkpoint. It shows the time since the oldest checkpoint. It's also calculated across all changefeeds.

edit: I just saw the tooltip text. We can probably use the first sentence of that here.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NV5qsiq5gtctlVG1NSC:-NV5qsiq5gtctlVG1NSD:b-j32lfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f01834469d1e739c2ca0d016b940efe1beff720d/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L62)):*
> ```XML
>       const scaledValues = result.datapoints.map(v => ({
>         ...v,
>         value: v.value && v.value * (s.props.scale ?? 1),
> ```

The `&&` is confusing. Is that right?

**Comment by shermanCRL** [comment]
*[`pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts` line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101790#-NV5qsiq5gtctlVG1NSC:-NV5s-Je0-PKITB-500m:ba0dt2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f01834469d1e739c2ca0d016b940efe1beff720d/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L62)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

The `&&` is confusing. Is that right? 
</blockquote></details>

It’s kinda idiomatic truthy javascript. Maybe some parens would make it clearer. Or make it more clearly booleans instead of truthy if it’s confusing.

**Comment by shermanCRL** [comment]
Remind me @samiskin, is Commit Latency the commit-to-emit latency? Asking because, now that we have [reduced latency](https://github.com/cockroachdb/cockroach/pull/101487), where is the best place to observe it?

**Comment by samiskin** [comment]
@shermanCRL Yep, its the time that we confirmed emitting of the message minus the MVCC timestamp.  We should be able to view the reduction with this metric, most directly by running without batching (which would add its own latency)

**Comment by shermanCRL** [comment]
Looks like this needs follow-up?

**Pull request merged**
