### PR TITLE
storage: remove Engine interface cruft

### PR DESCRIPTION
**Pull request by jbowens**
Remove a few methods from the `Engine` interface type that don't belong.

**storage: remove Engine.InMem**

Remove storage.Engine's InMem method. This method was a hole in the
abstraction. Clients should not need to distinguish between on-disk and
in-memory engines.

**storage: remove Engine.WriteFile**

Remove the WriteFile method on the Engine interface, converting call sites to
use the storage/fs.WriteFile function. The Engine itself should only expose
primitives, and higher-level utilities like a WriteFile routine can be
implemented in terms of those primitives.

**storage/fs: move Engine.ReadFile to fs.ReadFile**

Move the Engine's ReadFile method off of the Engine interface and into a
storage/fs helper function written it terms of existing Engine methods.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Nice cleanups, thanks!

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88063)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvserver/replica_proposal.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-NCLDfYg1adAPcMZ2D1s:-NCLDfYg1adAPcMZ2D1t:bl2l5wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5051c83dee80b94dc4b3b423042215aa5d39eefc/pkg/kv/kvserver/replica_proposal.go#L489)):*
> ```Go
> 	if eng.InMem() {
> 		// Ingest a copy of the SST. Otherwise, Pebble will claim and mutate the
> 		// sst.Data byte slice, which will also be used later by e.g. rangefeeds.
> ```

I thought this comment was obsolete, but I'm having doubts now. @erikgrinaker do you remember what this is referring to?

This might be referring to encryption-at-rest which will mutate the byte slice passed to `(vfs.File).Write`: https://github.com/cockroachdb/cockroach/blob/58589fd69b25e8c6ca9ab0d164e6f8f30bd02d91/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L82-L84

But in that case, this applies to non-in-memory filesystems too.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-:-NCMEU9c-FVEP2WBOP1g:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/fs/fs.go` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-NCMDyF5Dcxf_wFUpN5U:-NCMDyF6D8p6lv30QOeo:b-oe5ivh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b143e13f9bf8138055c38df6075d2b8c839d2aea/pkg/storage/fs/fs.go#L80)):*
> ```Go
> 		return err
> 	}
> 	_, err = io.Copy(f, bytes.NewReader(data))
> ```

what motivated this change?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88063)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-NCLDfYg1adAPcMZ2D1s:-NCMEsA26cicSfrfMB9r:b-1dqcty) ([raw file](https://github.com/cockroachdb/cockroach/blob/5051c83dee80b94dc4b3b423042215aa5d39eefc/pkg/kv/kvserver/replica_proposal.go#L489)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I thought this comment was obsolete, but I'm having doubts now. @erikgrinaker do you remember what this is referring to?

This might be referring to encryption-at-rest which will mutate the byte slice passed to `(vfs.File).Write`: https://github.com/cockroachdb/cockroach/blob/58589fd69b25e8c6ca9ab0d164e6f8f30bd02d91/pkg/ccl/storageccl/engineccl/encrypted_fs.go#L82-L84

But in that case, this applies to non-in-memory filesystems too.
</blockquote></details>

While implementing rangefeed support for `AddSSTable`, I was seeing test failures because the emitted `RangeFeedSSTable` event contents would differ from the SST given by the client. If we no longer see such test failures then I guess this no longer applies.

I can't remember exactly which tests failed, but likely the ones in `rangefeed_external_test.go`.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88063)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_proposal.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-NCLDfYg1adAPcMZ2D1s:-NCVYLyJEjlPk349TkJa:b-kzhlom) ([raw file](https://github.com/cockroachdb/cockroach/blob/5051c83dee80b94dc4b3b423042215aa5d39eefc/pkg/kv/kvserver/replica_proposal.go#L489)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

While implementing rangefeed support for `AddSSTable`, I was seeing test failures because the emitted `RangeFeedSSTable` event contents would differ from the SST given by the client. If we no longer see such test failures then I guess this no longer applies.

I can't remember exactly which tests failed, but likely the ones in `rangefeed_external_test.go`.
</blockquote></details>

Thanks—I'm going to merge this, but I'll followup with writing a unit test that runs with encryption-at-rest and explicitly skips sideloading. I'm worried we have a bug here.
___
*[`pkg/storage/fs/fs.go` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88063#-NCMDyF5Dcxf_wFUpN5U:-NCSj-O5EMsyAevZQFEI:b-brxljg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b143e13f9bf8138055c38df6075d2b8c839d2aea/pkg/storage/fs/fs.go#L80)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what motivated this change?
</blockquote></details>

This was taken from the previous `(*Pebble).WriteFile` implementation, but the old code should be equivalent, and I think it should avoid an allocation. Reverted.

**Comment by jbowens** [comment]
TFTRs!

bors r=erikgrinaker,sumeerbhola

**Pull request merged**
