### PR TITLE
cli: avoid manually calling os.Exit

### PR DESCRIPTION
**Pull request by tamird**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4212)

### CODE REVIEW

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4212#-KA-HPvuNIQR8eZ6XzWU:-KA-HPvvW83plNN4KXvW:-1081620755) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe31ceff251334f1f1f129c216e3d586ba8ec92d/cli/sql.go#L46)):*
I checked the cobra docs and source code and did not find any definition / semantics for SilenceErrors (it's not even used anywhere in cobra, despite its existence in the parameters struct). What does it stand for?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4212)*

**Comment by tamird** [comment]
It prevents the error from being printed on exit.

**Comment by knz** [comment]
@tamird is that so?

1) is it desirable? if e.g. runInteractive encounters an input error, don't we want this error to be properly printed out before exiting?

2) is this actually implemented in cobra? As I said I went through the cobra code and did not see SilentErrors used anywhere.

**Comment by tamird** [comment]
1) note that I'm still manually printing query errors as they come.

2) I can't point you to where it's implemented, but I tested it.

**Comment by petermattis** [comment]
LGTM

Is there a problem with manually calling exit? If yes, can you call it out in the commit message or elsewhere.

**Comment by tamird** [comment]
Noted it in the commit message.

**Pull request merged**
