### PR TITLE
sql/row: fix the deleter in an edge case

### LINKED ISSUE #54629: Crash when deleting a row on a table with a unique index and similar PK
**Describe the problem**

Deleting a row in one of our tables causes the node to instantly crash and the row to remain. I believe this is the same issue as in #47541 although I can't prove it.

This is likely a rare circumstance due to the poor indexing (see below).

**To Reproduce**

* Create a cockroachdb node (standalone) or a cluster, here's a handy `docker-compose.yaml`: https://gist.github.com/dpkirchner/1ab4d1e0450a2d381c762837711cbb5f
* `docker exec -it crdb-1 cockroach sql --insecure -e 'create database test'`
* `docker exec -it crdb-1 cockroach sql --insecure -d test`
* Execute the following SQL
* Execute `DELETE FROM foo WHERE ref1_name = 'a' AND ref2_id = 1;`
* Witness crash (docker exits with no output or possibly `ERROR: driver: bad connection`)

```
CREATE TABLE ref1 (
  name VARCHAR(50) NOT NULL,
  CONSTRAINT "primary" PRIMARY KEY (name ASC),
  FAMILY "primary" (name)
);

CREATE TABLE ref2 (
  id INT8 NOT NULL DEFAULT unique_rowid(),
  CONSTRAINT "primary" PRIMARY KEY (id ASC),
  FAMILY "primary" (id)
);

CREATE TABLE foo (
  ref1_name VARCHAR(50) NOT NULL,
  FOREIGN KEY (ref1_name) REFERENCES ref1(name),
  ref2_id INT8 NOT NULL,
  FOREIGN KEY (ref2_id) REFERENCES ref2(id)
);

-- v The crash only occurs when *both* this index and the PK exist
CREATE UNIQUE INDEX unique_ref1_ref2 ON foo (ref1_name, ref2_id);
-- BTW: I didn't mean for this unique index to exist any more, it was a holdover from other work

ALTER TABLE foo ALTER PRIMARY KEY USING COLUMNS (ref1_name, ref2_id);
-- ^

INSERT INTO ref1 VALUES ('a');
INSERT INTO ref2 VALUES (1);
INSERT INTO foo VALUES ('a', 1);
```

**Expected behavior**
I expected the row to be deleted and for the node not to crash.

**Additional data / screenshots**
Log of the full panic for Google-bait:

```
E200921 20:00:14.902436 1152 sql/conn_executor.go:812  [n1,client=127.0.0.1:57510,hostnossl,user=root] a SQL panic has occurred while executing "DELETE FROM foo WHERE (ref1_name = 'a') AND (ref2_id = 1)": runtime error: index out of range [2] with length 2
E200921 20:00:14.902535 1152 util/log/crash_reporting.go:208  [n1,client=127.0.0.1:57510,hostnossl,user=root] a panic has occurred!
I200921 20:00:15.252503 2710 kv/kvserver/replica_consistency.go:246  [n1,consistencyChecker,s1,r4/1:/System{/tsd-tse}] triggering stats recomputation to resolve delta of {ContainsEstimates:2876 LastUpdateNanos:1600718413272249000 IntentAge:0 GCBytesAge:0 LiveBytes:-8340 LiveCount:-692 KeyBytes:-33660 KeyCount:-692 ValBytes:25320 ValCount:-692 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
E200921 20:00:15.583352 1152 util/log/crash_reporting.go:533  [n1,client=127.0.0.1:57510,hostnossl,user=root] Reported as error 94db42a1eef6457db0086ca49f89ec55
panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: panic while executing 1 statements: DELETE FROM _ WHERE (_ = _) AND (_ = _); caused by runtime error: index out of range [2] with length 2

goroutine 1152 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc003eaf000, 0x4be8060, 0xc004b27580, 0x4108040, 0xc00400b900)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:826 +0x3f9
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc003eaf000, 0x4be8060, 0xc004b27580)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:477 +0x61
panic(0x4108040, 0xc00400b900)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.findColumnValue(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/index_encoding.go:472
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.EncodeColumns(0xc003f78c28, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc004936480, 0xc004e1fb40, 0x2, 0x2, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:247 +0x347
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.EncodeSecondaryIndex(0xc00380b200, 0xc0038d0000, 0xc004936480, 0xc004e1fb40, 0x2, 0x2, 0x4be8001, 0xc003f15740, 0xc0042b0900, 0x3, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/index_encoding.go:1029 +0x1a6
github.com/cockroachdb/cockroach/pkg/sql/row.(*Deleter).DeleteRow(0xc00521ac48, 0x4be8060, 0xc003f15740, 0xc003eb1600, 0xc004e1fb40, 0x2, 0x2, 0xc004000001, 0x1, 0x11)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/deleter.go:161 +0x105
github.com/cockroachdb/cockroach/pkg/sql.(*tableDeleter).row(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_delete.go:66
github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).processSourceRow(0xc00521ac00, 0x4be8060, 0xc003f15740, 0xc0039f6780, 0xc003eaf3f0, 0xc004e1fb40, 0x2, 0x2, 0x40b8780, 0x3f38001)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go:173 +0x8e
github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).BatchedNext(0xc00521ac00, 0x4be8060, 0xc003f15740, 0xc0039f6780, 0xc003eaf3f0, 0x3f38000, 0xc0051d3401, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go:126 +0x150
github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec(0xc004e1fa80, 0x4be8060, 0xc003f15740, 0xc0039f6780, 0xc003eaf3f0, 0xc0051d3400, 0x2d66db5)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:159 +0xcd
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x4314820, 0x5, 0x4bea6a0, 0xc004e1fa80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:395 +0xb9
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0051d3b88, 0x4314820, 0x5, 0x4bea6a0, 0xc004e1fa80)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:144 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0051d3b88, 0x4bea6a0, 0xc004e1fa80, 0x4314820, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:721 +0x2a6
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0051d3b88, 0x4bea6a0, 0xc004e1fa80, 0x759c038, 0x759c038)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:111 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:75
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x4be8060, 0xc003f15740, 0xc0039f6780, 0xc003eaf3f0, 0x4bea6a0, 0xc004e1fa80, 0x200000000, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:398 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc00493e000, 0x4be8060, 0xc003f15740, 0x759e9c0, 0x3cce6c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:117 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc00493e000, 0x4be8060, 0xc003f15740)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:748 +0x52
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc0042b3560, 0x4be8060, 0xc003f15740, 0x44d3218, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x247
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00011ca00, 0xc0045085b0, 0xc0042b0510, 0xc0051d4458, 0xc000749b80, 0xc003eaf4d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:405 +0x5f1
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00011ca00, 0x4be8120, 0xc0042abf80, 0xc003eaf4d0, 0xc0045085b0, 0xc0042b0510, 0x4bea6a0, 0xc004e1fa80, 0xc000749b80, 0xc003eaf1c8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1019 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc003eaf000, 0x4be8120, 0xc0042abf80, 0xc003eaf3f0, 0x2, 0x7f26638adda8, 0xc004b54f80, 0xc0051d4700, 0xc00479d438, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:938 +0x3f0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc003eaf000, 0x4be8120, 0xc0042abf80, 0xc003eaf3f0, 0x7f26638adda8, 0xc004b54f80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:831 +0x6cd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc003eaf000, 0x4be8120, 0xc0042abf80, 0x4c00da0, 0xc004efbb30, 0xc004ca8ab3, 0x35, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:536 +0xb06
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc003eaf000, 0x4be8120, 0xc0042abf80, 0x4c00da0, 0xc004efbb30, 0xc004ca8ab3, 0x35, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x4f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc003eaf000, 0x4be8060, 0xc003f15640, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1406 +0x1b77
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc003eaf000, 0x4be8060, 0xc004b27580, 0xc0003c07c0, 0x5400, 0x15000, 0xc0003c0858, 0xc003ed8c70, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1335 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000c4c580, 0x4be8060, 0xc004b27580, 0xc003eaf000, 0x5400, 0x15000, 0xc0003c0858, 0xc003ed8c70, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:479 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc004ae9b6f, 0xc004c371a0, 0x4be8060, 0xc004b27580, 0xc003ed8c70, 0xc000c4c580, 0xc004b54900, 0x4c0bd20, 0xc004c5d260, 0xc004c3d200, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:582 +0x317
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:510 +0x17e
```

I'll send the logs to support@ after getting the issue id but I can also share them with whoever wants 'em, nothing proprietary here. The above repro works 100% of the time.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: 20.1.5
 - Server OS: [e.g. Linux/Distrib]: Docker Desktop for Mac, but it also happens on CoreOS Linux in GKE 
 - Client app [e.g. `cockroach sql`, JDBC, ...]: `cockroach sql`

**Additional context**
What was the impact?

The node crashes causing query failures throughout the cluster.

Deleting either the PK or the unique index resolves the issue.

### PR DESCRIPTION
**Pull request by yuzefovich**
To be filled.

Fixes: #54629.

Release note (bug fix): CockroachDB could previously crash after
performing a primary key change (when an already existing index was
reused) and later performing a DELETE operation, this is now fixed.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hm, the CI is happy, but I really don't understand the impact of removing that code snippet. The comment mentions #14601 which added a regression test which passes now.

I guess I'd like for someone from the optimizer team (maybe @RaduBerinde) to confirm my understanding (some more context [here](https://github.com/cockroachdb/cockroach/issues/54629#issuecomment-701006317)) that the set of columns requested by the scan (that is the input to the deleter) doesn't include those `ExtraColumnID` columns (in the reproduction it is the hidden `rowid` column).

**Review by RaduBerinde — COMMENTED** [review]
This is from the description for ExtraColumnIDs:
```
	// For non-unique indexes, these columns are appended to the key.
	// For unique indexes, these columns are stored in the value (unless the key
	// contains a NULL value: then the extra columns are appended to the key to
	// unique-ify it).
```

So for a non-unique index, we definitely need them as part of the key. For unique index, we need them if any of the columns are nullable. We need tests with these cases.

What I don't understand is that even if we call `maybeAddCol`, we only add the column if it is in `fetchColIDtoRowIndex` map. So how can calling `maybeAddCol` lead to a crash later? Feels like something else is wrong.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54983#-:-MIRMtLpDzUAnmRYhlug:btsggyr)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54983)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54983#-MIROpGb1LS7NUjPJ1S4:-MIROpGb1LS7NUjPJ1S5:bu70cpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c719b88e0673a2f282194a44ee6fe5bb7cb143/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1184)):*
> ```
> ALTER TABLE t54629 ALTER PRIMARY KEY USING COLUMNS (c);
> INSERT INTO t54629 VALUES (1);
> DELETE FROM t54629 WHERE c = 1
> ```

In this example, why do we even have an `ExtraColumnID` set in any of the indexes? We have an index on `c` storing `rowid` and an index on `rowid` storing `c`. Neither should need any ExtraColumnIDs.. In particular, I don't think the primary index should ever have ExtraColumnIDs (which is documented as only used for secondary indexes).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54983)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54983#-MIROpGb1LS7NUjPJ1S4:-MIRQAv60au9brqKO275:b2zf8h8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c719b88e0673a2f282194a44ee6fe5bb7cb143/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1184)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In this example, why do we even have an `ExtraColumnID` set in any of the indexes? We have an index on `c` storing `rowid` and an index on `rowid` storing `c`. Neither should need any ExtraColumnIDs.. In particular, I don't think the primary index should ever have ExtraColumnIDs (which is documented as only used for secondary indexes).
</blockquote></details>

My message above wasn't quite right. In any case, there is definitely something confusing going on here.

Here is the SHOW CREATE for the table at the time of DELETE:
```
demo@127.0.0.1:44673/defaultdb> SHOW CREATE TABLE t54629;
  table_name |               create_statement
-------------+------------------------------------------------
  t54629     | CREATE TABLE public.t54629 (
             |     c INT8 NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (c ASC),
             |     UNIQUE INDEX t54629_c_key (c ASC),
             |     FAMILY "primary" (c, rowid)
             | )
```

But here is what the optimizer sees through the catalog:
```
demo@127.0.0.1:44673/defaultdb> EXPLAIN (OPT, CATALOG) SELECT * FROM t54629;
                                    text
----------------------------------------------------------------------------
  TABLE t54629
   ├── c int not null
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_mvcc_timestamp decimal [hidden] [system]
   ├── tableoid oid [hidden] [system]
   ├── INDEX primary
   │    └── c int not null
   └── INDEX t54629_c_key
        ├── c int not null
        └── rowid int not null default (unique_rowid()) [hidden] (storing)
```

It sees two indexes - one is a primary index, and the other is a secondary index on `c` that stores `rowid`. In any case, it seems wrong that either of these have any `ExtraColumnIDs`.

Another question - is it ok to drop the uniqueness constraint on `rowid`? Don't we want to retain a unique index on it?  The documentation doesn't talk about this case.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/alter_primary_key, line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54983#-MIROpGb1LS7NUjPJ1S4:-MIRTpOdBXFM1gtI-G2X:bmaly3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c719b88e0673a2f282194a44ee6fe5bb7cb143/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1184)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

My message above wasn't quite right. In any case, there is definitely something confusing going on here.

Here is the SHOW CREATE for the table at the time of DELETE:
```
demo@127.0.0.1:44673/defaultdb> SHOW CREATE TABLE t54629;
  table_name |               create_statement
-------------+------------------------------------------------
  t54629     | CREATE TABLE public.t54629 (
             |     c INT8 NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (c ASC),
             |     UNIQUE INDEX t54629_c_key (c ASC),
             |     FAMILY "primary" (c, rowid)
             | )
```

But here is what the optimizer sees through the catalog:
```
demo@127.0.0.1:44673/defaultdb> EXPLAIN (OPT, CATALOG) SELECT * FROM t54629;
                                    text
----------------------------------------------------------------------------
  TABLE t54629
   ├── c int not null
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_mvcc_timestamp decimal [hidden] [system]
   ├── tableoid oid [hidden] [system]
   ├── INDEX primary
   │    └── c int not null
   └── INDEX t54629_c_key
        ├── c int not null
        └── rowid int not null default (unique_rowid()) [hidden] (storing)
```

It sees two indexes - one is a primary index, and the other is a secondary index on `c` that stores `rowid`. In any case, it seems wrong that either of these have any `ExtraColumnIDs`.

Another question - is it ok to drop the uniqueness constraint on `rowid`? Don't we want to retain a unique index on it?  The documentation doesn't talk about this case.
</blockquote></details>

Ah, sorry, the catalog does match SHOW CREATE. I think having `ExtraColumnIDs` set here is the only problem.

**Comment by yuzefovich** [comment]
Thanks for taking a look. It must be that Alter PK operation is broken. I'll look into it more.

**Comment by yuzefovich** [comment]
Hm, it's interesting that the regression test I have in this PR passes on `local` config but fails on `fakedist` config. The index descriptors are the same in both cases (we have `rowid` column in `ExtraColumnIDs`), but for some reason on `local` config `del.FetchCols` contains two columns whereas on `fakedist` config it has only one. @RaduBerinde do you know why that would be the case?

**Comment by yuzefovich** [comment]
Never mind, It seems to me that there is some race going on, and if I add some breakpoints, then I can make both `local` fail and `fakedist` succeed. This is very suspicious.

**Comment by RaduBerinde** [comment]
The ALTER statement shouldn't return until the schema change is complete..

**Comment by yuzefovich** [comment]
We do show this notice when for Alter PK operation:
```
NOTICE: primary key changes are finalized asynchronously; further schema changes on this table may be restricted until the job completes
ALTER TABLE
```
so it might be an exception to that rule.

**Comment by RaduBerinde** [comment]
Ah, did not know that, interesting.

**Comment by yuzefovich** [comment]
Closing this fix as it's wrong, and we need to think harder on how to solve the issue.

**Pull request closed without merging**
