### PR TITLE
sqlccl: move backup/restore/load benchmarks to a common file

### PR DESCRIPTION
**Pull request by danhhz**
And delete one of the redundant Restore benchmarks.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13568)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/bench_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568#-Kcv6c5Z4wcRwgPAzzmc:-Kcv6c5Z4wcRwgPAzzmd:b3f6fe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/17025955e25e10322a7d42b71ffe1843ad8f1db5/pkg/ccl/sqlccl/bench_test.go#L53)):*
> ```Go
> 	// 	sqlDB.Exec(split)
> 	// }
> 	// rebalanceLeases(b, tc)
> ```

Although this is commented out, we probably don't want to delete the implementation completely?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/bench_test.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568#-Kcv6c5Z4wcRwgPAzzmc:-KcxIaiUUWXlXEinWR0G:b-cod0qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/17025955e25e10322a7d42b71ffe1843ad8f1db5/pkg/ccl/sqlccl/bench_test.go#L53)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Although this is commented out, we probably don't want to delete the implementation completely?
</blockquote></details>

The linter complains about unused functions. I could work around that in the usual way, but I don't see us using this code again. Updated the TODO here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568#-:-Kcy1kDzKY59lUqhlgLP:bnfp4nl)*

**Comment by danhhz** [comment]
TFTR!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13568#-:-Kcy1vx1ei8sIf3BCh3S:b-814g8k)*

**Pull request merged**
