### PR TITLE
ui: Split out trace details route from snapshot overview route to enable back-button browsing.

### PR DESCRIPTION
**Pull request by benbardin**
Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @dhartunian)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNBzvBIqyCsPO5x_i):*
I'd like to play with this but it doesn't build for me:
```
$ dev build

ERROR in ./src/views/tracez/traceDetails.tsx
Module not found: Error: Can't resolve 'src/js' in '/home/andrei/.cache/bazel/_bazel_andrei/da3e2f93300e18367ce1ab9206c9f57e/sandbox/linux-sandbox/5644/execroot/com_github_cockroachdb_cockroach/pkg/ui/workspaces/db-console/src/views/tracez'
```
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNLKh130V89mtkMSV):*
I think "trace collection" is less suggestive than "traces snapshot", or just "snapshot".
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNi3C8au68VfnOMcn):*
These pages generate content specific to the rendering node (unfortunately, for the most part). This is not how most pages work (although it's also not uncommon for hand-crafted advanced debug pages). Since these pages are getting love, I think the new URLs should have a node id in them, maybe like `/tracez/trace_collection/node/1/snap/1`. The backend should then route the RPC to the desired node, like other admin RPCs do. This way the pages would work when accessed through a balancer.
WDYT?

It'd also be cool if the page let you select the node you want to talk to from a drop down. Otherwise the only way is the generic http proxying support on the advanced debug page, but that's a bit hard to find and use. 
___
*[`pkg/server/serverpb/admin.proto` line 1172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iLQ5zBwY-H_vHFoXd:-N6iLQ69A3LHJV3xRS00:b-ildm4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0e98321e444bfefe55d7fc23632ed2cea5adc1/pkg/server/serverpb/admin.proto#L1172)):*
> ```protobuf
>   // consumption in the browser.
>   string serialized_recording = 4;
>   string operation = 5;
> ```

This field needs a comment. Maybe name `root_operation`. 
___
*[`pkg/ui/workspaces/db-console/src/views/tracez/traceDetails.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iKJ0gB1MYXffgJLpB:-N6iKJ0gB1MYXffgJLpC:b-f1bikt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0e98321e444bfefe55d7fc23632ed2cea5adc1/pkg/ui/workspaces/db-console/src/views/tracez/traceDetails.tsx#L77)):*
> ```XML
> }
> 
> const TraceView = ({ currentTrace, cancel, showLive }: TraceViewProps) => {
> ```

s/currentTrace/trace ?

Also let's find something more suggestive for `cancel`.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, and @dhartunian)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNBzvBIqyCsPO5x_i):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd like to play with this but it doesn't build for me:
```
$ dev build

ERROR in ./src/views/tracez/traceDetails.tsx
Module not found: Error: Can't resolve 'src/js' in '/home/andrei/.cache/bazel/_bazel_andrei/da3e2f93300e18367ce1ab9206c9f57e/sandbox/linux-sandbox/5644/execroot/com_github_cockroachdb_cockroach/pkg/ui/workspaces/db-console/src/views/tracez'
```
</blockquote></details>

Fixed! Not sure why I didn't run into that, but expunging my cache uncovered the error.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNLKh130V89mtkMSV):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think "trace collection" is less suggestive than "traces snapshot", or just "snapshot".
</blockquote></details>

Yeah, you may be right. Let me think on this a bit.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNi3C8au68VfnOMcn):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

These pages generate content specific to the rendering node (unfortunately, for the most part). This is not how most pages work (although it's also not uncommon for hand-crafted advanced debug pages). Since these pages are getting love, I think the new URLs should have a node id in them, maybe like `/tracez/trace_collection/node/1/snap/1`. The backend should then route the RPC to the desired node, like other admin RPCs do. This way the pages would work when accessed through a balancer.
WDYT?

It'd also be cool if the page let you select the node you want to talk to from a drop down. Otherwise the only way is the generic http proxying support on the advanced debug page, but that's a bit hard to find and use. 
</blockquote></details>

I think you're right long-term. I'd like to punt on this for the current round of work though - though this is definitely useful, I don't think I'll have time to do it before stability, and there's a lot of value to unlock by doing the other work first. When time permits I'll be glad to turn to this - when that happens, I don't think there will be any trouble changing the route structure again!

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84174)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @benbardin, and @dhartunian)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6iNi3C8au68VfnOMcn):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

I think you're right long-term. I'd like to punt on this for the current round of work though - though this is definitely useful, I don't think I'll have time to do it before stability, and there's a lot of value to unlock by doing the other work first. When time permits I'll be glad to turn to this - when that happens, I don't think there will be any trouble changing the route structure again!
</blockquote></details>

OK, but at least do something such that the `trace_collection` page says something other than `No snapshot selected` when an invalid snapshot id is given (particularly since this is what's gonna happen when you go through a balancer without session affinity).
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6oRK2U3GULJaCzbIEh):*
A couple of observations. Maybe some of these are not new issues, in which case feel free to ignore if you want.

1. The `trace_collection` page always says `no snapshot selected` for a second before loading the selected snapshot. Can we have it not do that (ideally showing a loading sign, but whatever).
2. Now that the browser back button works from the `trace_details`, let's remove the `Back` button from the page I'd say. It'd be cool if the `Snapshot: <x>` part of the breadcrumb would also be clickable.
3.  Editing the URL of the `trace_details` page to an invalid trace id results in a javascript error.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6oSmoO5C_jdEU-KIJ-):*
consider `snapshot` instead of `trace_collection` and `trace` instead of `trace_details` in the URLs
___
*[`pkg/server/admin.go` line 3710 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84174#-N6oLCKs4kyT03ppYcrN:-N6oLCKtCJmySbvRZbF7:b-ffbv1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ab59a5cb617d52deeb97db70253a6469ee06a1c/pkg/server/admin.go#L3710)):*
> ```Go
> 
> 	operation := ""
> 	if len(recording) > 0 {
> ```

we test for `nil` above. There should be such a thing as a 0-len recording, so get rid of this check. If you want, you can transform the check above into `len(recording) > 0`.

**Comment by dhartunian** [comment]
@benbardin I assume this is out of date and we can close, correct?

**Comment by benbardin** [comment]
Yup!

**Pull request closed without merging**
