### PR TITLE
builtins: improve docs and refactor code for unordered_unique_id

### PR DESCRIPTION
**Pull request by andyyang890**
**builtins: improve documentation for unordered_unique_rowid**

This patch clarifies that `unordered_unique_rowid` generates unique IDs
that are statistically likely to be unordered because it bit-reverses
the insert timestamp for use as the ID's timestamp bit segment.

Release note: None

----

**builtinconstants: define constants for unique int bit segments**

This patch defines constants for the sizes and bitmasks for each
bit segment in a unique int generated for row IDs.

Release note: None

----

**builtins: refactor bit shifting logic in mapToUnorderedUniqueInt**

This patch refactors the bit shifting logic in `mapToUnorderedUniqueInt`
to use constants instead of magic numbers.

Release note: None

----

Epic: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice cleanup! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-:-NawCFotATDgATKjIzg3:b-t2g9ob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rharding6373)

___
*[`pkg/sql/sem/builtins/builtins.go` line 9800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-NawC7JH6tlDenGD0IZ6:-NawC7JH6tlDenGD0IZ7:b96hq3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b8c1c913c934775d9fe304652b4cfe4cbb20c3/pkg/sql/sem/builtins/builtins.go#L9800)):*
> ```Go
> // should preserve the number of 1-bits.
> func mapToUnorderedUniqueInt(val uint64) uint64 {
> 	// val is [0][48 bits of ts][15 bits of node id]
> ```

this `val is [0][48 bits of ts][15 bits of node id]` comment still seems helpful to keep

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

___
*[`pkg/sql/sem/builtins/builtins.go` line 9800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-NawC7JH6tlDenGD0IZ6:-NawcUAh3Cd5VLHE2d0i:b-ex7252) ([raw file](https://github.com/cockroachdb/cockroach/blob/56b8c1c913c934775d9fe304652b4cfe4cbb20c3/pkg/sql/sem/builtins/builtins.go#L9800)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this `val is [0][48 bits of ts][15 bits of node id]` comment still seems helpful to keep
</blockquote></details>

Added it back!

**Review by rharding6373 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 9801 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-NawkN-a8BFCROfsguUL:-NawkN-a8BFCROfsguUM:bzhpai8) ([raw file](https://github.com/cockroachdb/cockroach/blob/241990737c7e2d561fbeb84709e455cd7a9b6732/pkg/sql/sem/builtins/builtins.go#L9801)):*
> ```Go
> func mapToUnorderedUniqueInt(uniqueInt uint64) uint64 {
> 	// val is [0][48 bits of ts][15 bits of node id]
> 	ts := uniqueInt & builtinconstants.UniqueIntTimestampMask
> ```

There are a few things in here that don't appear to be a clean refactor. E.g.: `ts` is missing a `>> 15` to shift the timestamp into the least significant bits. And `ts<<builtinconstants.UniqueIntLeadingZeroBits` below should probably be a right shift.

Could you add some unit tests to test the behavior and make sure it's expected? Particularly if this PR is intended to be a refactor, please compare the test results before and after the change.

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

___
*[`pkg/sql/sem/builtins/builtins.go` line 9801 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-NawkN-a8BFCROfsguUL:-NaworlH5DNJXr3MEZtr:b-djhzjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/241990737c7e2d561fbeb84709e455cd7a9b6732/pkg/sql/sem/builtins/builtins.go#L9801)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

There are a few things in here that don't appear to be a clean refactor. E.g.: `ts` is missing a `>> 15` to shift the timestamp into the least significant bits. And `ts<<builtinconstants.UniqueIntLeadingZeroBits` below should probably be a right shift.

Could you add some unit tests to test the behavior and make sure it's expected? Particularly if this PR is intended to be a refactor, please compare the test results before and after the change.
</blockquote></details>

I did verify this manually but good call out to add a test. I've added a few cases to the test file.

The reason the `>> 15` is not necessary is because instead of shifting it down to the least significant bits before the reversal, I am shifting to the most significant bits so that after it is reversed it will be in the least significant bits (before then shifting it back to its expected location). After my change, `ts` and `reversedTS` both hold the timestamp segment at its correct location instead of at the least significant bits, which I believe makes for easier reading.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-:-Nax3pRWE3eCUS5pze4w:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890 and @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 9801 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/108085#-NawkN-a8BFCROfsguUL:-Nax3jsw1M-J2WYi6bTG:b-lhoshn) ([raw file](https://github.com/cockroachdb/cockroach/blob/241990737c7e2d561fbeb84709e455cd7a9b6732/pkg/sql/sem/builtins/builtins.go#L9801)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I did verify this manually but good call out to add a test. I've added a few cases to the test file.

The reason the `>> 15` is not necessary is because instead of shifting it down to the least significant bits before the reversal, I am shifting to the most significant bits so that after it is reversed it will be in the least significant bits (before then shifting it back to its expected location). After my change, `ts` and `reversedTS` both hold the timestamp segment at its correct location instead of at the least significant bits, which I believe makes for easier reading.
</blockquote></details>

Ah, I see, I didn't follow that before. Thanks for the tests!

**Comment by andyyang890** [comment]
TFTRs!

bors r=rafiss,rharding6373

**Pull request merged**
