### PR TITLE
security: Add certificate manager.

### PR DESCRIPTION
**Pull request by mberhault**
This is the first step towards #1674.

Introduces two new security objects:
* certificate_loader: scans certsDir for certs/keys
* certificate_manager: long-lived: builds tls.Config objects

The certificate_manager is currently only used by the `cert debug-list`
command and the current cert system remains in place.

A few small notes:
* embedded certs were renamed to the new naming scheme
* most test changes are to use the new embedded assets setter

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14507)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-Kg_ukougzV8Prd0JJnZ:b-x4qmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
> ```Go
> 
> 	// DefaultCertsDirectory is the default value for the cert directory flag.
> 	DefaultCertsDirectory = "cockroach-certs"
> ```

Should this default to `~/.cockroach-certs` (at least for client commands) instead of a directory relative to `$PWD`?

---

*[pkg/security/certificate_loader.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_y9qh29kC3Dv33UsF:-Kg_y9qh29kC3Dv33UsG:b-lvfyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_loader.go#L33)):*
> ```Go
> 
> // AssetLoader describes the functions necessary to read certificate and key files.
> type AssetLoader struct {
> ```

I would expect this to be an interface instead of a struct of function pointers.

---

*[pkg/security/certificate_loader.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_xza7g_HjxtKH74EN:-Kg_xza7g_HjxtKH74EO:bt502r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_loader.go#L143)):*
> ```Go
> 	return &CertificateLoader{
> 		certsDir:             certsDir,
> 		skipPermissionChecks: envutil.EnvOrDefaultBool("COCKROACH_SKIP_KEY_PERMISSION_CHECK", false),
> ```

I think we try to do all `envutil` calls at initialization time (so that `cockroach debug env` can collect all of them)

---

*[pkg/security/certificate_manager.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_yO97vkjymacXPo2Z:-Kg_yO97vkjymacXPo2_:bad25tr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_manager.go#L95)):*
> ```Go
> 	}
> 
> 	log.Infof(context.Background(), "Found certificate: %+v", cl.Certificates())
> ```

This looks like it's going to be too verbose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-KgavUWO8vKbm3-1tLyV:b-1szfng) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Should this default to `~/.cockroach-certs` (at least for client commands) instead of a directory relative to `$PWD`?
</blockquote></details>

Two aspects here:
* put is in `~/`. We could, although I'm not sure that's very relevant in prod environments. The other default directory (`cockroach-data` is also relative).
* hidden directory: that I don't think we need. hidden directories are useful if you have a crowded dir (eg: your home machine), but will just make it that much more annoying in prod.

---

*[pkg/security/certificate_loader.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_y9qh29kC3Dv33UsF:-Kgaxe6Qr8bdoaG4lvCT:b-w3hv4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_loader.go#L33)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I would expect this to be an interface instead of a struct of function pointers.
</blockquote></details>

I went that way originally, but then I need to define the interface, and some type of struct that implements the interface. it's not really simpler or shorter. Probably more idiomatic go though.

---

*[pkg/security/certificate_loader.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_xza7g_HjxtKH74EN:-KgaxpV4d0LphaNjTS3T:b-trqxux) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_loader.go#L143)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think we try to do all `envutil` calls at initialization time (so that `cockroach debug env` can collect all of them)
</blockquote></details>

arg. good point. Moved to init() and added a `TestDisablePermissionCheck` on the certificate_manager.

---

*[pkg/security/certificate_manager.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_yO97vkjymacXPo2Z:-KgaxaudcvpyJ0vNcSry:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/security/certificate_manager.go#L95)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This looks like it's going to be too verbose.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by bdarnell** [comment]
Review status: 43 of 46 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-Kgeq18VZrd_xtAOXHZZ:bhqk388) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Two aspects here:
* put is in `~/`. We could, although I'm not sure that's very relevant in prod environments. The other default directory (`cockroach-data` is also relative).
* hidden directory: that I don't think we need. hidden directories are useful if you have a crowded dir (eg: your home machine), but will just make it that much more annoying in prod.
</blockquote></details>

Yeah, that's why I said it might be different for client commands. For prod/server use, a visible directory using the same rules as `cockroach-data` makes sense. But clients want to be able to run `cockroach sql` and have it pick up their certs automatically, and I think in that case the home directory makes sense (instead of setting `COCKROACH_CERTS_DIR` in your shell profile)

For us, using a relative path kind of makes sense because we want to test with multiple clusters (so it's convenient to cd into the `gamma` directory and run `cockroach sql` from there). But it will be more typical to have a single cluster that you want to access globally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by mberhault** [comment]
Review status: 43 of 46 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-Kgg0eG4Og1rT5BUe6fB:b-74r7a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, that's why I said it might be different for client commands. For prod/server use, a visible directory using the same rules as `cockroach-data` makes sense. But clients want to be able to run `cockroach sql` and have it pick up their certs automatically, and I think in that case the home directory makes sense (instead of setting `COCKROACH_CERTS_DIR` in your shell profile)

For us, using a relative path kind of makes sense because we want to test with multiple clusters (so it's convenient to cd into the `gamma` directory and run `cockroach sql` from there). But it will be more typical to have a single cluster that you want to access globally.


</blockquote></details>

I agree for the `sql` command. But what about all the other client commands, or even the certs commands? Those are more likely to be run by admins, and some of them from a machine running a node.
We could use `~/.cockroach-certs` for the `sql` command, and `cockroach-cert` for everything else, but then I'm concerned about unpredictable behavior. Default flag values don't usually change for a single binary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by bdarnell** [comment]
Review status: 43 of 46 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-KggAXOLM0Ctn8RQ2SmE:bsc1t8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

I agree for the `sql` command. But what about all the other client commands, or even the certs commands? Those are more likely to be run by admins, and some of them from a machine running a node.
We could use `~/.cockroach-certs` for the `sql` command, and `cockroach-cert` for everything else, but then I'm concerned about unpredictable behavior. Default flag values don't usually change for a single binary.
</blockquote></details>

I think that `start` and `cert` are the only commands for which a `~/.cockroach-certs` default might be misplaced (at least `cockroach quit` and `cockroach zone` should get the same defaults as `cockroach sql`). But I agree that consistency is important, and therefore I'd lean towards using `~/.cockroach-certs` for all commands, even `start` (and `cert`, although that one is more questionable and it's likely to always be a special case for cert-related stuff). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by mberhault** [comment]
Review status: 43 of 46 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-KggxalxiGZPKOpx8tr0:b-mm4irr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think that `start` and `cert` are the only commands for which a `~/.cockroach-certs` default might be misplaced (at least `cockroach quit` and `cockroach zone` should get the same defaults as `cockroach sql`). But I agree that consistency is important, and therefore I'd lean towards using `~/.cockroach-certs` for all commands, even `start` (and `cert`, although that one is more questionable and it's likely to always be a special case for cert-related stuff). 
</blockquote></details>

Consistency would be better indeed.
The cert command will need special handling anyway. For example, it's the only command that needs a `ca-key`, and that should be settable though its own flag.

It's reasonably easy to expand `~` on unix-like systems (well `${HOME}` is easier). Out of curiosity though, what should we do for windows? Do those mean anything?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by bdarnell** [comment]
Review status: 43 of 46 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-KgoJ1Wr6ySsAZDkl4Yt:b5i10px) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

Consistency would be better indeed.
The cert command will need special handling anyway. For example, it's the only command that needs a `ca-key`, and that should be settable though its own flag.

It's reasonably easy to expand `~` on unix-like systems (well `${HOME}` is easier). Out of curiosity though, what should we do for windows? Do those mean anything?
</blockquote></details>

Windows users have a home directory (the `os/user` package has functions to get this in a cross-platform way), but the conventions for where to put things under the home directory are different. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by mberhault** [comment]
Review status: 42 of 46 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/base/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-Kg_ukotr5tUtaAkANR0:-Kgsz4yBggwT-IEtvSB6:b-aldaih) ([raw file](https://github.com/cockroachdb/cockroach/blob/c20b4acc3e0565c0dcd950715d287ec2e985aea4/pkg/base/config.go#L60)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Windows users have a home directory (the `os/user` package has functions to get this in a cross-platform way), but the conventions for where to put things under the home directory are different. 
</blockquote></details>

ok. I've changed it to `${HOME}/.cockroach-certs` with a `os.ExpandEnv` around it.
We'll see if we want to make an exception for the `cert` commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507)*

**Comment by mberhault** [comment]
Ben, care to have a last look?

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14507#-:-KgylUsAGOuJA83UBwvA:bnfp4nl)*

**Comment by RaduBerinde** [comment]
The examples-go repo still has a reference to `SetReadFileFn`. I noticed this while trying to do a `:GoRename` of something unrelated.

https://github.com/cockroachdb/examples-go/blob/4d5fa2153f1f15db6fed3dbbdebeac552cca42ad/filesystem/main_test.go#L26

**Comment by mberhault** [comment]
good catch, thank you. I've remove it in https://github.com/cockroachdb/examples-go/pull/104, it's not even used.

**Pull request merged**
