### PR TITLE
perf: reduce LeaseHolderCache memory usage

### LINKED ISSUE #17388: perf: reduce LeaseHolderCache memory usage
#17202 was a non-starter because the `UnorderedCache` used internally by `LeaseHolderCache` updates an LRU list on every access. `LeaseHolderCache` is accessed on every RPC putting it in the critical path. Rather than a single `UnorderedCache`, we could shard `LeaseHolderCache` based on the range ID, providing a lock per shard. This would be relatively straightforward.

While we're mucking in this code, we might want to trim down the data stored by `LeaseHolderCache`. Currently it caches a `ReplicaDescriptor`, but only `ReplicaDescriptor.StoreID` is needed.

### PR DESCRIPTION
**Pull request by a6802739**
@petermattis  Fixes #17388.

please help me review it. Thank you very much.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/gossip/gossip.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-KtqcNoUeUN431N1KHSC:-KtqcNoUeUN431N1KHSD:b-j8ld3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L747)):*
> ```Go
> 	defer g.mu.Unlock()
> 	existingNodeID, ok := g.storeMaps[desc.StoreID]
> 	if !ok || existingNodeID != desc.Node.NodeID {
> ```

I don't think we need a condition here, we can just unconditionally set `g.storeMaps[desc.StoreID] = desc.Node.NodeID`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-:-KtqdKeJ51ZKl6I2kzhu:bnfp4nl)*

**Comment by petermattis** [comment]
:lgtm: Generally looks good. A few naming commits below.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/gossip/gossip.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-KtqlNuVjv9f9W6_wcPu:-KtqlNuVjv9f9W6_wcPv:bar6v5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L231)):*
> ```Go
> 	resolversTried map[int]struct{} // Set of attempted resolver indexes
> 	nodeDescs      map[roachpb.NodeID]*roachpb.NodeDescriptor
> 	// storeMaps could help us directly get the NodeID for the specified StoreID
> ```

I'd make this slightly more direct: `storeMaps maps store IDs to node IDs.`

The pluralization feels awkward here as there is only one map. Can you `s/storeMaps/storeMap/g` throughout this PR (i.e for all uses of `storeMaps` and `StoreMaps`).

---

*[pkg/gossip/gossip.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-Ktqlyoake6DcYBz1JSB:-Ktqlyoake6DcYBz1JSC:b-cn7ffd) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L445)):*
> ```Go
> 
> // GetNodeID looks up the NodeID by StoreID.
> func (g *Gossip) GetNodeID(storeID roachpb.StoreID) (roachpb.NodeID, error) {
> ```

Apologies for the naming nits, but the name of this method is too similar to `GetNodeIDAddress`. Perhaps `GetNodeIDForStoreID`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-:-KtqmeQ3PBlhXtKr0SVQ:b-dof6ir)*

**Comment by a6802739** [comment]
@petermattis, @bdarnell, Thanks for your review.

---

Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/gossip/gossip.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-KtqlNuVjv9f9W6_wcPu:-Ktuy_GlSohUnPRITGFL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L231)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd make this slightly more direct: `storeMaps maps store IDs to node IDs.`

The pluralization feels awkward here as there is only one map. Can you `s/storeMaps/storeMap/g` throughout this PR (i.e for all uses of `storeMaps` and `StoreMaps`).
</blockquote></details>

Done.

---

*[pkg/gossip/gossip.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-Ktqlyoake6DcYBz1JSB:-KtuybxUEUsE2IynQjq9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L445)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Apologies for the naming nits, but the name of this method is too similar to `GetNodeIDAddress`. Perhaps `GetNodeIDForStoreID`.
</blockquote></details>

Done.

---

*[pkg/gossip/gossip.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-KtqcNoUeUN431N1KHSC:-KtuydFTzycZlPsmfrFe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52397e9653eb2b5ac659a886cc5fea1731f976ec/pkg/gossip/gossip.go#L747)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think we need a condition here, we can just unconditionally set `g.storeMaps[desc.StoreID] = desc.Node.NodeID`. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-:-KtuyfMz7BRm3aNmq5Wu:b-j6lo2s)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18443#-:-KtvcXc24ypLTqFLlnfW:bnfp4nl)*

**Comment by a6802739** [comment]
@petermattis , could I merge this now?

**Comment by petermattis** [comment]
@a6802739 Yes!

**Pull request merged**
