### PR TITLE
backupccl: refactor backup destination resolution

### PR DESCRIPTION
**Pull request by pbardea**
During backup planning we need to resolve the backup destination. This
means that we need to:
1. Determine if we're going to resolve to a backup collection or not
2. Determine if we should auto-append
3. Read any encryption options we may need if we determine that we're
donig an incremental backup
4. Find the previous backups in the chain if we're doing an incremental
backup.

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
This is a WIP, but ready for early feedback. I still want to rework some of the naming (e.g. encryptionContext) and need to do general clean up.

**Comment by pbardea** [comment]
I'm going to implement the TODO on `resolveDest`s first.

**Comment by adityamaru** [comment]
Did a first pass this LGTM, really like how it cleans up the ever 🎈-ing `backupPlanHook`.

**Comment by pbardea** [comment]
Cleaned it up a bit - it should be RFAL.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r=dt

**Pull request merged**
