### PR TITLE
Makefile: better support for multiple checkouts

### PR DESCRIPTION
**Pull request by tamird**
Use `$(git rev-parse --git-path)` instead of hardcoding `.git`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9072)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072#-KQgORsRad4rZxnt-Ly2:-KQgORsRad4rZxnt-Ly3:bwrm1na) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc681b1a7ebb75b463548d7f133867f4e563394/Makefile#L197)):*
> ```Makefile
> ifneq ($(SKIP_BOOTSTRAP),1)
> 
> GITHOOKSDIR := $(shell git rev-parse --git-path hooks)
> ```

so this would always install the hooks from the "bare checkout", not from the worktree, right? That's neat, but it deserves a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072#-:-KQgOhGzEd8y8wcl8ACO:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072#-KQgORsRad4rZxnt-Ly2:-KQgXX9Czgiya1rU_eDD:bn7i5h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc681b1a7ebb75b463548d7f133867f4e563394/Makefile#L197)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> so this would always install the hooks from the "bare checkout", not from the worktree, right? That's neat, but it deserves a comment.
</details>
Wouldn't the comment be repeating, verbatim, the code here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072#-KQgORsRad4rZxnt-Ly2:-KQgk7RzNRRDo4HV9gJc:b-9z72lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc681b1a7ebb75b463548d7f133867f4e563394/Makefile#L197)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Wouldn't the comment be repeating, verbatim, the code here?
</details>
Well the code here is not really readable by most people, and the fact that it has an impact on worktrees  is worth calling out in my opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Makefile, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072#-KQgORsRad4rZxnt-Ly2:-KQgq1cq8eVew5cioI2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fc681b1a7ebb75b463548d7f133867f4e563394/Makefile#L197)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> Well the code here is not really readable by most people, and the fact that it has an impact on worktrees  is worth calling out in my opinion.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9072)*

**Pull request merged**
