### PR TITLE
distsqlrun: plumb kv tracing into distsql

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, kv tracing only worked in local SQL. Now, FlowSetupRequest
and FlowCtx are augmented with traceKV flags, so DistSQL can get in on
the fun as well.

Release note (sql change): kv traces (SHOW KV TRACE FOR SESSION) now
work for distsql-executed queries as well.

### CODE REVIEW

**Review by knz — APPROVED** [review]
w00t! :tada: 

a test perhaps?

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-:-LHrvlj62ar8TJYY8pXU:b-vgnbas)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
ok I "approved" the thing but it really needs a test :)

**Comment by jordanlewis** [comment]
Added a test. TFTR

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-:-LHsMEB63Y7lhqiD-7sK:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/trace_test.go, line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-LHsM5YGDyhkf4OZZXTD:-LHsM5YGDyhkf4OZZXTE:b-sfb9xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23b2f47f65538edcb6e389b4c3520151e5022d8/pkg/sql/trace_test.go#L523)):*
> ```Go
> 	r.Exec(t, "SET tracing = on,kv; SELECT count(*) FROM test.a; SET tracing = off")
> 
> 	for node := range []int{0, 1} {
> ```

nit: `for node := 0; node < 2; node++ {`

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/trace_test.go, line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-LHsM5YGDyhkf4OZZXTD:-LHsNj__Bv-Af8bTNWKB:b-24rx7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23b2f47f65538edcb6e389b4c3520151e5022d8/pkg/sql/trace_test.go#L523)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: `for node := 0; node < 2; node++ {`
</blockquote></details>

But mine is shorter and just as clear :grin: If this weren't just a test I'd take your suggestion.

**Review by knz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/trace_test.go, line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-LHsM5YGDyhkf4OZZXTD:-LHsPNyZBWKVACjX8p14:bsk351s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d23b2f47f65538edcb6e389b4c3520151e5022d8/pkg/sql/trace_test.go#L523)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

But mine is shorter and just as clear :grin: If this weren't just a test I'd take your suggestion.
</blockquote></details>

you made a mistake though, `for _, node := range ...` 

in which case I'm not so sure it's shorter in the end :)

**Comment by jordanlewis** [comment]
Ha, true, but it works out to be the same... ok I'll fix it

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27802)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/tablereader.go, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27802#-LHsUlJM0LIP2ve29Ztk:-LHsUlJM0LIP2ve29Ztl:bies4u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb280e66b1be6b0947ececec29d5d5e4d056d4e/pkg/sql/distsqlrun/tablereader.go#L209)):*
> ```Go
> 	// This call doesn't do much; the real "starting" is below.
> 	tr.input.Start(fetcherCtx)
> 	// TODO(radu,andrei,knz): set the traceKV flag when requested by the session.
> ```

This TODO can also be removed.

**Pull request merged**
