### PR TITLE
sql: unit test, benchmark and logictests for COPY

### PR DESCRIPTION
**Pull request by cucaroach**
As a new/half supported feature COPY FROM STDIN support is under tested.
Add tests and a simple benchmark to pave the way for enhancements and
optimizations.

Assists: https://github.com/cockroachdb/cockroach/issues/81731

Release note: None

Release justification: non-production code change

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I'll defer to Oliver on Copy stuff, but the conn executor changes LGTM.

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-:-N8fJznuBwEVUniJUuHR:bb17ovb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @otan)

___
*[`pkg/sql/copy.go` line 694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fEwsTAIBzT7XOJJ8R:-N8fEwsTAIBzT7XOJJ8S:bn59zkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copy.go#L694)):*
> ```Go
> 	stmtTs := txnOpt.stmtTimestamp
> 	autoCommit := false
> 	// TODO: turn on insertFastPath!
> ```

nit: add a name to the TODOs :)
___
*[`pkg/sql/copyshim.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fF1tS22nJxyFtbmgx:-N8fF1tS22nJxyFtbmgy:bc9wrtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L1)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> ```

nit: `s/2016/2022/`
___
*[`pkg/sql/copyshim.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fGvqg5Liyvb05UEYY:-N8fGvqg5Liyvb05UEYZ:b-d2qv68) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L70)):*
> ```Go
> }
> 
> // RunCopyFrom exposes copy functionality for the logictest "copy" command, its test
> ```

nit: `s/test only/test-only/` for readability.
___
*[`pkg/sql/copyshim.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fHYNq6AtiyFtR6qAs:-N8fHYNq6AtiyFtR6qAt:b-nzm6j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L92)):*
> ```Go
> 	// TODO: test open transaction and implicit txn
> 	var txnOpt copyTxnOpt
> 	if true {
> ```

This seems suspicious.
___
*[`pkg/sql/copyshim.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fHqNe0Xb_fR0xNbyn:-N8fHqNfCsAzXZbT1FlB:b-1ko9x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L138)):*
> ```Go
> 	}
> 	rows := 0
> 	c, err := newCopyMachine(context.TODO(), conn, stmt.AST.(*tree.CopyFrom), p, txnOpt,
> ```

Looks like there is `ctx` in scope.
___
*[`pkg/sql/distsql_running.go` line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fFdbc51vbvbb1U1Al:-N8fFdbc51vbvbb1U1Am:beaxwde) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/distsql_running.go#L1296)):*
> ```Go
> }
> 
> // PlanAndRunAll combines running the the main query, subqueries and cascades/checks.
> ```

nit: add a comment about the error return argument (maybe just copy-paste from `execWithDistSQLEngine`?).

**Review by cucaroach — COMMENTED** [review]
Thanks Yahor!  I'll wait for @otan to get back before moving forward with this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-:-N8jM69w5nhmJkBml1r1:bhewzt6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[`pkg/sql/copyshim.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fHYNq6AtiyFtR6qAs:-N8jLr18DS847lwhS77h:b-wjx27l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L92)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This seems suspicious.
</blockquote></details>

Yeah I'll clean it up, I was hoping to figure out a way to test this but it will require some heavy lifting.
___
*[`pkg/sql/copyshim.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N8fHqNe0Xb_fR0xNbyn:-N8jM2Oc8vZ388k60TqG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fa741dff843e6b5ba5fd3e9aac6dfd7038b6cc2/pkg/sql/copyshim.go#L138)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Looks like there is `ctx` in scope.
</blockquote></details>

Done.

**Review by otan — COMMENTED** [review]
> Reviewed 2 of 19 files at r1, 8 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85462)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/copy_from_test.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U01rW7iwKODodYE4d:-N9U01rW7iwKODodYE4e:b-q9k3rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/copy_from_test.go#L101)):*
> ```Go
> 
> 	// send data in 5 batches of 10k rows
> 	const ROWS = sql.CopyBatchRowSize * 4
> ```

nit: constants are usually not fully uppercase. make this `copyRowSize` or something?
___
*[`pkg/sql/copy_from_test.go` line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U08pZ2uwFBkGE8GwM:-N9U08pZ2uwFBkGE8GwN:b-ku7xsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/copy_from_test.go#L142)):*
> ```Go
> 	ROWS := 50000
> 	datalen := 0
> 	THREADS := 10
> ```

same here and for ROWS
___
*[`pkg/sql/logictest/logic.go` line 2303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U12RHBe6wyPa-pztK:-N9U12RHBe6wyPa-pztL:bgg58gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/logictest/logic.go#L2303)):*
> ```Go
> 			// not ideal but the go sql.DB interface doesn't support COPY so fixing it the right way that would
> 			// require major surgery (ie making logictest use libpq or something low level like that).
> 			rows, err := sql.RunCopyFrom(context.Background(), t.cluster.Server(0), "test", nil, query.sql, []string{data.String()})
> ```

is there an advantage to make this runnable using `logictest` vs. make a new custom datadriven test that specifically tests COPY, ideally using a driver? i can see a case in logic tests for using COPY to insert data, but the caveat you mention here feels like it can be an easy gotcha.

this just seems like it's adding a few more hacks than i understand in full.

**Review by cucaroach — COMMENTED** [review]
> Dismissed @otan from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85462)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[`pkg/sql/copy_from_test.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U01rW7iwKODodYE4d:-N9Ws8ME7GuaTMsiFP0u:b-kpbal) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/copy_from_test.go#L101)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: constants are usually not fully uppercase. make this `copyRowSize` or something?
</blockquote></details>

Hmm, you're right, there are only a handful of upper case vars in the codebase, but they do exist and our code guidelines don't mention it so I'm not inclined to change it. 

```
❯ rg  "\s[A-Z]+\s*:=" pkg/**/*.go                                                                                                                                      -130-
pkg/sql/type_change.go
760:    for _, ID := range typeDesc.ReferencingDescriptorIDs {

pkg/sql/sqlliveness/slstorage/slstorage_test.go
693:    ID := sqlliveness.SessionID("foo")

pkg/upgrade/upgrademanager/manager_external_test.go
376:    N := 25

pkg/sql/physicalplan/aggregator_funcs_test.go
428:    A := math.Abs(a)
429:    B := math.Abs(b)

pkg/sql/pgwire/types_test.go
88:     CET := time.FixedZone("Europe/Paris", 0)
89:     EST := time.FixedZone("America/New_York", 0)

pkg/sql/opt/xform/physical_props.go
243:    H := func(n float64) float64 {

pkg/sql/opt/memo/statistics_builder.go
4207:                   FD := &filtersFDs[i]
```
___
*[`pkg/sql/logictest/logic.go` line 2303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U12RHBe6wyPa-pztK:-N9Wt6EP6W8CgwSvCM9v:b-ujo3ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/logictest/logic.go#L2303)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

is there an advantage to make this runnable using `logictest` vs. make a new custom datadriven test that specifically tests COPY, ideally using a driver? i can see a case in logic tests for using COPY to insert data, but the caveat you mention here feels like it can be an easy gotcha.

this just seems like it's adding a few more hacks than i understand in full.
</blockquote></details>

Yeah its ugly, I'll file an enhancement request to use a custom datadriven approach, then I can probably use pgx and do it all from the client side right?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85462)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @otan, and @yuzefovich)

___
*[`pkg/sql/copy_from_test.go` line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U01rW7iwKODodYE4d:-N9YI9Zc3uBVPdk_Cy7-:b-ekxmho) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/copy_from_test.go#L101)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Hmm, you're right, there are only a handful of upper case vars in the codebase, but they do exist and our code guidelines don't mention it so I'm not inclined to change it. 

```
❯ rg  "\s[A-Z]+\s*:=" pkg/**/*.go                                                                                                                                      -130-
pkg/sql/type_change.go
760:    for _, ID := range typeDesc.ReferencingDescriptorIDs {

pkg/sql/sqlliveness/slstorage/slstorage_test.go
693:    ID := sqlliveness.SessionID("foo")

pkg/upgrade/upgrademanager/manager_external_test.go
376:    N := 25

pkg/sql/physicalplan/aggregator_funcs_test.go
428:    A := math.Abs(a)
429:    B := math.Abs(b)

pkg/sql/pgwire/types_test.go
88:     CET := time.FixedZone("Europe/Paris", 0)
89:     EST := time.FixedZone("America/New_York", 0)

pkg/sql/opt/xform/physical_props.go
243:    H := func(n float64) float64 {

pkg/sql/opt/memo/statistics_builder.go
4207:                   FD := &filtersFDs[i]
```
</blockquote></details>

i'm not sure we should be copying something that is "not in the standard style" (and i would also be inclined to change if we weren't on stability), but i'm not gonna block on that.
___
*[`pkg/sql/logictest/logic.go` line 2303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85462#-N9U12RHBe6wyPa-pztK:-N9YIM_h2U2HSO4QSUFn:bs2smkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/03be63751477be3c6c7af37ced655df75c7ad68c/pkg/sql/logictest/logic.go#L2303)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Yeah its ugly, I'll file an enhancement request to use a custom datadriven approach, then I can probably use pgx and do it all from the client side right?
</blockquote></details>

should we do that upfront instead of committing this? i could be convinced otherwise (i don't want to block progress but if we're going to build something better straight up i'd rather just commit that) but i'm inclined to only commit that.

**Comment by cucaroach** [comment]
> i'm not sure we should be copying something that is "not in the standard style" (and i would also be inclined to change if we weren't on stability), but i'm not gonna block on that.

IMHO discussions about coding conventions that aren't spelled out publicly or encoded in a linter somewhere are bordering on noise and just a drag on code review velocity.

> should we do that upfront instead of committing this? i could be convinced otherwise (i don't want to block progress but if we're going to build something better straight up i'd rather just commit that) but i'm inclined to only commit that.

This week is supposed to be SQL queries testing week so I wouldn't be able to get to it until next week and at that point this and the downstream changes that depend on this run the risk of missing the 22.2 boat.  Maybe I'm being hyperbolic but seems unwise to hold up feature testing because part of the testing framework is a little janky.

**Review by otan — APPROVED** [review]
> IMHO discussions about coding conventions that aren't spelled out publicly or encoded in a linter somewhere are bordering on noise and just a drag on code review velocity.

to be fair, i do think it's somewhere in go conventions, and it's nitty having to edit special cases in code. 

> Maybe I'm being hyperbolic but seems unwise to hold up feature testing because part of the testing framework is a little janky.

yeah that's fine, just asking.

**Comment by cucaroach** [comment]
> to be fair, i do think it's somewhere in go conventions, and it's nitty having to edit special cases in code.

I went looking for it but came up empty.  If the IDE used a different style for const's that would make me happier, still its hard to teach an old C/C++ dog new tricks ;-)  If you widen the search to include vendor or the go runtime [there's a couple dozen hits so I think its pretty squarely in a grey area.  The goruntime uses a lot of single letter capital locals (but not consts).  :shrug:

**Pull request merged**
