### PR TITLE
codeowners: add upgrade-prs team to pkg/upgrade

### PR DESCRIPTION
**Pull request by celiala**
Add `upgrade-prs` team as reviewers to`pkg/upgrade`.

Epic: None
Release note: None
Release justification: non-production change (updating codeowners).

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by celiala** [comment]
> We need to make sure release-eng-prs has permission: "push" (for an example, see https://github.com/cockroachlabs/crl-infrastructure/pull/1849/files)

`push` attribute is set 
https://github.com/cockroachlabs/crl-infrastructure/blob/main/terraform/github/cockroachdb/team-repos.tf#L1328

I'm wondering if this is what I'm missing?

https://github.com/cockroachlabs/crl-infrastructure/pull/1947

**Comment by celiala** [comment]
oooh - release-eng-prs , not upgrade-prs. ah, thanks!

**Comment by celiala** [comment]
garr 🤯  - i'm still getting `cockroachdb/upgrade-prs does not exist` errors, even though team is now in place:
https://github.com/orgs/cockroachdb/teams/upgrade-prs

let me try some permutations to see what the linter is looking for..

https://mesolite.cluster.engflow.com/invocations/default/1359065a-7416-4254-bc0d-629012481776
```
Error Trace:	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/gen-lint_test.go:2651
Error:      	Received unexpected error: owner cockroachdb/upgrade-prs does not exist
```

https://mesolite.cluster.engflow.com/invocations/default/fbb9ff44-18ef-4211-a55a-fef97532fc37
`2024/05/30 17:13:36 loading codeowners: owner cockroachdb/upgrade-prs does not exist`

**Comment by RaduBerinde** [comment]
FWIW in the link, the team shows up as `upgrade prs` not `upgrade-prs`

**Comment by celiala** [comment]
> FWIW in the link, the team shows up as upgrade prs not upgrade-prs

ah! let's fix it and see if this was the issue? 🤞🏼 
https://github.com/cockroachlabs/crl-infrastructure/pull/1952/files

**Comment by celiala** [comment]
linter passed 🎉  (seems like I needed to x-reference teams back to object in `owners.go` file)
TFTR!

bors r=RaduBerinde

**Pull request merged**
