### PR TITLE
cfetcher: operate on the typed columns rather than untyped Vecs

### PR DESCRIPTION
**Pull request by yuzefovich**
**coldata: introduce TypedVecs helper**

This commit extracts the helper struct out of the ordered synchronizer
that stores the well-typed columns alongside the untyped Vecs. The idea
is that every Vec is stored both in Vecs slice as well as in the typed
slice, in order. Components that know the type of the vector they are
working with can then access the typed column directly, avoiding
expensive type casts.

The newly introduced struct is used by the ordered synchronizer and the
follow-up commits will introduce it elsewhere (for example, in the
cFetcher).

Release note: None

**cfetcher: operate on the typed columns rather than untyped Vecs**

This commit uses the `coldata.TypedVecs` helper (introduced in the
previous commit) in the context of the cFetcher. In all decoding methods
we are already performing a large type switch for each value for each
row, so we always know exactly the type of the column we're writing
into.

Additionally, this commit inlines a single function call and removes an
`if` conditional in the value decoding path.

Release note: None

**pgwire: add benchmarks for writing from columnar representation**

Release note: None

**pgwire: operate on the well-typed columns**

This commit applies the same optimization as in the previous commit but
to the pgwire-writing logic.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Cool! Curious whether there are any observable benefits from this change, e.g. from introducing a pool for typed vecs? :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71302#-:-Mn6ncUe89XuN2SWmCT6:b-9bkqp9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

**Review by rharding6373 — COMMENTED** [review]
Looks good! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71302#-:-MnC3Oyl9esAj2SjPRkY:b3prxon)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

**Review by rharding6373 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71302#-:-MnC3YiqBQ0ImNpn9dK7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @mgartner)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
