### PR TITLE
sqlccl: allow IMPORT with no primary key

### PR DESCRIPTION
**Pull request by madelynnblue**
Achieve this by manually setting the hidden column datums to a function
that mimics unique_rowid.

Release note (sql change): allow tables with no primary key in
IMPORT CSV.

### CODE REVIEW

**Comment by mjibson** [comment]
@knz Assigning you to either review or triage to someone else on a SQL team to review the emulation of unique_rowid here.

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 442 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4ujcAgrVnvofLInyki:-L4ujcAgrVnvofLInykj:bnw6tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L442)):*
> ```Go
> 	dataFileI := 0
> 	for dataFileIndex, dataFile := range dataFiles {
> 		dataFileI++
> ```

nit: i think this was more clear before

---

*[pkg/ccl/sqlccl/csv.go, line 587 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uj2qxiP6B0W_kmRRq:-L4uj2qxiP6B0W_kmRRr:b-yuhckx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L587)):*
> ```Go
> 		if col.Hidden {
> 			// Check that this is the only hidden column and that it's in its expected
> 			// place after all the visible columns.
> ```

instead of sniffing the order, check that `default_expr` is `unique_rowid()`

---

*[pkg/ccl/sqlccl/csv.go, line 673 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uiBfWp4gAFIcK-dXE:-L4uiBfWp4gAFIcK-dXF:bvqktud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L673)):*
> ```Go
> // generateRowInt attempts to mimic the behavior of builtins.GenerateUniqueInt,
> // but with an idempotent result. The lower 15 bits are set to the file number,
> // and the upper 48 bits are set to the line number. This is similar to the
> ```

this doesn't mention the xor (which is important because it means it's fine to pass values for file greater than 2^15)

---

*[pkg/ccl/sqlccl/csv.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uh0aZQtOiTnqTMLyc:-L4uh0aZQtOiTnqTMLyd:bolfk9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L675)):*
> ```Go
> // and the upper 48 bits are set to the line number. This is similar to the
> // node ID and timestamp scheme.
> func generateRowInt(file int32, line int) *tree.DInt {
> ```

How about a small test that asserts (and shows to a reader of the code) how all these sort

```
generateRowInt(0, 0)
generateRowInt(1, 0)
generateRowInt(2<<15, 0)
generateRowInt(0, 1)
generateRowInt(0, 10000)
builtins.GenerateUniqueInt(0)
```

now that i write this out, it might be more obvious if you swapped the order of file and line in the method def

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-:-L4ujfgCE7BHyubNjElo:bnfp4nl)*

**Comment by knz** [comment]
LGTM modulo resolution of the few remaining comments

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 673 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uiBfWp4gAFIcK-dXE:-L4vxnShTZTV9CWYGwMG:b2n3tdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L673)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this doesn't mention the xor (which is important because it means it's fine to pass values for file greater than 2^15)
</blockquote></details>

I would also strongly suggest extracting the function that computes `unique_rowid()` into its own package, and have that used both here and for `unique_rowid()` so that we don't  have any divergence if we ever want to change them in the future.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 386 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4vy0aLN3-ZG2tUmksa:-L4vy0aMNcEwfOLMOn4N:bjj4sqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/sql/distsqlrun/flow_diagram.go#L386)):*
> ```Go
> func (c *ReadCSVSpec) summary() (string, []string) {
> 	ss := make([]string, 0, len(c.Uri))
> 	for _, s := range c.Uri {
> ```

This looks like an unrelated change. Why is it part of this commit?

---

*[pkg/sql/distsqlrun/processors.proto, line 533 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4vy4NIgoevjn1O3GZK:-L4vy4NIgoevjn1O3GZL:b-rqxvnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/sql/distsqlrun/processors.proto#L533)):*
> ```protobuf
>   // uri is a storageccl.ExportStorage URI pointing to the CSV files to be
>   // read. The map key must be unique across the entire IMPORT job.
>   map<int32, string> uri = 7;
> ```

ditto?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-:-L4vyFkG158uTsaDduQ2:ba85ylp)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/csv.go, line 442 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4ujcAgrVnvofLInyki:-L4ySXBuk-DKx7Luhlog:bkzz7g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L442)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: i think this was more clear before
</blockquote></details>

The variable is named similarly to its field in csvRecord, so I think this is a better name. I've changed the name of dataFileI to be something else so maybe they won't get confused.

---

*[pkg/ccl/sqlccl/csv.go, line 587 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uj2qxiP6B0W_kmRRq:-L4yUp_v-AYhh0LUXUm9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L587)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

instead of sniffing the order, check that `default_expr` is `unique_rowid()`
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/csv.go, line 673 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uiBfWp4gAFIcK-dXE:-L4yWLokzfo17pN1nv7X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L673)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would also strongly suggest extracting the function that computes `unique_rowid()` into its own package, and have that used both here and for `unique_rowid()` so that we don't  have any divergence if we ever want to change them in the future.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/csv.go, line 675 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4uh0aZQtOiTnqTMLyc:-L4yYQgtR7WhKv6PauW3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/ccl/sqlccl/csv.go#L675)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

How about a small test that asserts (and shows to a reader of the code) how all these sort

```
generateRowInt(0, 0)
generateRowInt(1, 0)
generateRowInt(2<<15, 0)
generateRowInt(0, 1)
generateRowInt(0, 10000)
builtins.GenerateUniqueInt(0)
```

now that i write this out, it might be more obvious if you swapped the order of file and line in the method def
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 386 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4vy0aLN3-ZG2tUmksa:-L4yWkSPVVofnNaoTmHh:bao95nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/sql/distsqlrun/flow_diagram.go#L386)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This looks like an unrelated change. Why is it part of this commit?
</blockquote></details>

c.Uri is no longer a []string, it's a map[int32]string, so this method had to adapt.

---

*[pkg/sql/distsqlrun/processors.proto, line 533 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542#-L4vy4NIgoevjn1O3GZK:-L4yWqtfyw7y3bWwzAC0:bfx0g1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d884b3ad15d58699d21e9474d67bd0c5e986eb3/pkg/sql/distsqlrun/processors.proto#L533)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto?
</blockquote></details>

This is the necessary code to pass along the index of the CSV file down to the CSV reader and KV writer so it knows how to generate a unique ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22542)*

**Comment by danhhz** [comment]
Thanks for the fix!

**Pull request merged**
