### PR TITLE
kv,importccl: allow reverting IMPORT beyond gcthreshold

### PR DESCRIPTION
**Pull request by dt**
IMPORT INTO uses RevertRange to rollback a failed import. RevertRange typically only
allows reverting to a time above the GCThreshold since otherwise it cannot assume
that the prior revision of a key it is clearing is still there to be reverted *to*.
However IMPORT INTO is a special-case, since it takes the table OFFLINE during the
IMPORT, meaning it can assume no other writers are (over)writing any keys in it.
Since the IMPORT itself only writes _new_ keys (with DisallowShadowing=true) it
can therefore safely assume that any existing keys from before the IMPORT are still
there, even if they are older than the GCThreshold, since they would not have been
shadowed by the import and thus not GC'ed. Thus a revert to the time at which the
table was offline can be done ignoring the GCThreshold.

This is usually moot since IMPORT INTO adds a protected timestamp record to prevent
the GC in the first place, but if it fails or if a RESTORE'ed IMPORT fails, that
protected timestamp record may not be there or be there anymore, but we still need
to rollback before the table can be returned to an online state.

An open question is if, given this observation that we do not need to worry about GC,
we should still even bother adding protected timestamps before running IMPORT INTO at
all. Also, if in the future IMPORT INTO somehow is able to update existing rows or is
able to run without taking the table offline, this assumption may no longer hold.

Release note: none.

Release justification: Category 3: Fix for high-severity (table cannot be rolled back and recovered after RESTORE) bug in existing functionality (RESTORE).

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @sumeerbhola)

___
*[pkg/sql/revert.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUFBtnT4gFS9d5z3eaz:-MUFBtnT4gFS9d5z3eb-:bajz461) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d5db06be9c90e34e2a630c3deca07c49187a69/pkg/sql/revert.go#L38)):*
> ```Go
> 	tables []catalog.TableDescriptor,
> 	targetTime hlc.Timestamp,
> 	ignoreGCThreshold bool,
> ```

We may want to add a comment here about `ignoreGCThreshold` to refer to `AllowTargetBelowGc` to see if this should be set as it may not be obvious if other callers should set this.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @sumeerbhola)

___
*[pkg/sql/revert.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUFBtnT4gFS9d5z3eaz:-MUG5eXE8R4B-QrGLvEe:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d5db06be9c90e34e2a630c3deca07c49187a69/pkg/sql/revert.go#L38)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

We may want to add a comment here about `ignoreGCThreshold` to refer to `AllowTargetBelowGc` to see if this should be set as it may not be obvious if other callers should set this.
</blockquote></details>

Done

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/roachpb/api.proto, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUGjokI3CzHSnDniPcE:-MUGjokI3CzHSnDniPcF:b-z6fvha) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03bcf20abeb1657a5f368fd9bdd17ab53cf8c27/pkg/roachpb/api.proto#L356)):*
> ```protobuf
>   // GC threshold. This is safe to set only in very specific situations, such as
>   // when the target span was OFFLINE since the target time as it is during
>   // IMPORT INTO. In this case, since the IMPORT knows it is the only writer and
> ```

(just some questions to satisfy my curiosity -- I don't really know the import context well enough to provide a proper review)

Where is this `IMPORT INTO` behavior of "no shadowing" enforced? And will the table be still OFFLINE when this `RevertRangeRequest` runs?
In this `IMPORT INTO` case, can there be other keys in the `[key, endKey)` interval that existed prior to the `IMPORT INTO` or is everything in that range new?
___
*[pkg/roachpb/batch.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUGllm80XkZA6adDIqv:-MUGllm80XkZA6adDIqw:bc4d2l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03bcf20abeb1657a5f368fd9bdd17ab53cf8c27/pkg/roachpb/batch.go#L84)):*
> ```Go
> 			}
> 		case *RevertRangeRequest:
> 			if !t.AllowTargetBelowGc {
> ```

I think it would help to add a comment that `EarliestActiveTimestamp` is used to check that the request is not running afoul of the GCThreshold, so we incorporate `t.TargetTime` only when the request wants itself to be checked.
___
*[pkg/sql/revert.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUFBtnT4gFS9d5z3eaz:-MUGmpE0BRnHyfQukdsB:b-7hunfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d5db06be9c90e34e2a630c3deca07c49187a69/pkg/sql/revert.go#L38)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done
</blockquote></details>

nit: can we unify on one name instead of both `ignoreGCThreshold` and `AllowTargetBelowGc`. `ignoreGCThreshold` seems reasonable enough to use in the proto.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61004)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @sumeerbhola)

___
*[pkg/roachpb/api.proto, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUGjokI3CzHSnDniPcE:-MUHC7s813SVfGJQs-4N:b-4z9m9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03bcf20abeb1657a5f368fd9bdd17ab53cf8c27/pkg/roachpb/api.proto#L356)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(just some questions to satisfy my curiosity -- I don't really know the import context well enough to provide a proper review)

Where is this `IMPORT INTO` behavior of "no shadowing" enforced? And will the table be still OFFLINE when this `RevertRangeRequest` runs?
In this `IMPORT INTO` case, can there be other keys in the `[key, endKey)` interval that existed prior to the `IMPORT INTO` or is everything in that range new?
</blockquote></details>

It sets `DisallowShadowing` on `AddSSTable` requests sent to KV that enforces that no key in the added SST overlaps an existing key unless it has the same ts and value.

"Offline" means no other writers since AddSSTable isn't txn-safe, so while there an be keys in existing `[key, endKey)`,  we can assume that nobody will write _to those keys_ once we're offline (since we're the only writer and we have `DisallowShadowing`). Thus whatever keys were live at the offline time are still live now, so they haven't been GC'ed.
___
*[pkg/roachpb/batch.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUGllm80XkZA6adDIqv:-MUHE7YC1k0naxxH8UXT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d03bcf20abeb1657a5f368fd9bdd17ab53cf8c27/pkg/roachpb/batch.go#L84)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it would help to add a comment that `EarliestActiveTimestamp` is used to check that the request is not running afoul of the GCThreshold, so we incorporate `t.TargetTime` only when the request wants itself to be checked.
</blockquote></details>

Done.
___
*[pkg/sql/revert.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61004#-MUFBtnT4gFS9d5z3eaz:-MUHDHFTBcVkFAfT_hq4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/47d5db06be9c90e34e2a630c3deca07c49187a69/pkg/sql/revert.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can we unify on one name instead of both `ignoreGCThreshold` and `AllowTargetBelowGc`. `ignoreGCThreshold` seems reasonable enough to use in the proto.
</blockquote></details>

Done.

**Comment by dt** [comment]
TFTRs!

bors r=pbardea

**Pull request merged**
