### PR TITLE
cli/interactive_tests: wait for liveness to update in demo test

### LINKED ISSUE #122134: acceptance: TestDockerCLI_test_demo_node_cmds failed [node reports draining=true after restart is completed]
acceptance.TestDockerCLI_test_demo_node_cmds [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_Acceptance/14783942?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_Acceptance/14783942?buildTab=artifacts#/) on release-24.1 @ [64f3f0bfab805c0bad14c2dc26b47693b0729140](https://github.com/cockroachdb/cockroach/commits/64f3f0bfab805c0bad14c2dc26b47693b0729140):

```
=== RUN   TestDockerCLI_test_demo_node_cmds
    test_log_scope.go:170: test logs captured to: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/_tmp/b38fdc3e3d87d99024418e1ae9af5f4c/logTestDockerCLI_test_demo_node_cmds1946639592
    test_log_scope.go:81: use -show-logs to present logs inline
    generated_cli_test.go:145: -- test log scope end --
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/_tmp/b38fdc3e3d87d99024418e1ae9af5f4c/logTestDockerCLI_test_demo_node_cmds1946639592
--- FAIL: TestDockerCLI_test_demo_node_cmds (69.10s)
=== RUN   TestDockerCLI_test_demo_node_cmds/test_demo_node_cmds.tcl
    util_docker.go:259: non-zero exit code: 1
    --- FAIL: TestDockerCLI_test_demo_node_cmds/test_demo_node_cmds.tcl (59.97s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #119508 acceptance: TestDockerCLI_test_demo_node_cmds failed [restart caused &#34;avoid up-replicating to fragile quorum&#34;; store throttled] [A-testing C-bug C-test-failure O-robot P-2 T-kv branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDockerCLI_test_demo_node_cmds.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37720

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/122134
Release note: None

### CODE REVIEW

**Review by andrewbaptist — COMMENTED** [review]
I don't really like the sleep here, could you do this in an `expect` loop, something like https://github.com/cockroachdb/cockroach/blob/54a5a4611bfbc8b7ad0c32337883ece676959d8e/pkg/cli/interactive_tests/test_demo_global.tcl#L36

The 1 second seems artificial and while it will probably work, relying on time rather than a retry means that the "normal" caase will be slower (albeit only by 1sec), but there is still a risk of failure since we don't have a time bound on when this update will be seen.

**Comment by rafiss** [comment]
> I don't really like the sleep here, could you do this in an expect loop

done; this is ready for another look

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123018#-:-NyzHaQWBwGW8qe799p7:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @arulajmani)

**Pull request merged**
