### PR TITLE
keys: introduce tenant keyspaces, generate SQL keys through tenant-bound key generator

### PR DESCRIPTION
**Pull request by nvb**
First step in addressing #47903.

This PR introduces a few new important concepts to the CockroachDB codebase:
- Tenants
- Tenant IDs
- Tenant keyspaces
- The "System" tenant

A TenantID is a unique ID associated with a tenant in a multi-tenant cluster. Each tenant is granted exclusive access to a portion of the keyspace and a collection of SQL tables in that keyspace which comprise a logical cluster. The "system" tenant is the system's internal tenant in a multi-tenant cluster and the only tenant in a single-tenant cluster.

The system tenant differs from all other tenants in three important ways:
1. the system tenant's keyspace is not prefixed with a tenant specifier.
2. the system tenant is created by default during cluster initialization.
2. the system tenant had the ability to create and destroy other tenants.

The PR then combines the concepts introduced in the previous commit with a new tenant-bound key generator structure called the `TenantIDKeyGen`. This key generator is bound to a TenantID on creation and is only capable of producing SQL keys for that tenant.

The change then removes all other forms of SQL key generation. Notably, it removes all free functions in `pkg/keys` that generate SQL keys and redirects all key generation in `pkg/sql/sqlbase/index_encoding.go` through `pkg/keys`. I audited all uses of `encoding.EncodeUvarintAscending` (and `DecodeUvarint64` for C++) in the codebase to get to a point where I feel relatively confident about this. Still, it will be nice to verify this further in the future when we test SQL tenant servers and reject all cross-tenant KV traffic.

With all SQL key generation flowing through the tenant-bound key generators, the change then introduces two global key generators:
- `SystemTenantKeyGen`: a SQL key generator for the system tenant
- `TODOTenantKeyGen`: equivalent to `SystemTenantKeyGen`, but should be used when it is unclear which tenant should be referenced by the surrounding context.

These two key generators are used appropriately. Most production code uses the `TODOTenantKeyGen` for now because it will later be replaced with a real tenant-bound key generator that hangs off of its SQL server. Most testing code uses the `SystemTenantKeyGen`. Once most of the obvious uses of `TODOTenantKeyGen` are addressed in the next PR, I might put it behind a function that takes an "issueNo" to make sure that all remaining uses of it are tracked in Github.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Looks good so far! I left a comment about having the tenantID and its encoding/decoding encapsulated away in a package. I wonder if you had already considered and decided against that.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, 86 of 86 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-:-M5gapEk7nFHDtfU6qgl:bq3t9xh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[pkg/keys/constants.go, line 35 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_PLy2t2yFgqTiIwW:-M5g_PLy2t2yFgqTiIwX:b-joraem) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/constants.go#L35)):*
> ```Go
> 	// The maximum value for a Uint64 encoded table ID is:
> 	//  \xfd\xff\xff\xff\xff\xff\xff\xff\xff
> 	// So we could also set this to be \xfe without issue. That would prevent
> ```

Yeah, using xfe can't hurt. Let's do it
___
*[pkg/keys/constants.go, line 282 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_fHc7GRia3yvyOoE:-M5g_fHc7GRia3yvyOoF:b-9h4m0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/constants.go#L282)):*
> ```Go
> 	// Should this be TablePrefix(math.MaxUint32 + 1)? Should we just set it to
> 	// tenantPrefix?
> 	TableDataMax = SystemTenantKeyGen.TablePrefix(math.MaxUint32)
> ```

Yeah that seems wrong. I wouldn't set it to tenantPrefix, based on a desire to keep the spans tight and "noninterlinked".
___
*[pkg/keys/printer.go, line 250 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_zWh2Rb8rqsvup58:-M5g_zWh2Rb8rqsvup59:boeqnzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/printer.go#L250)):*
> ```Go
> 	tenantIDStr := input[:slashPos]
> 	tenantID, err := strconv.ParseUint(tenantIDStr, 10, 64)
> 	fmt.Println(tenantID, err)
> ```

This method too would be better kept in the hypothetical `tenantpb` package.
___
*[pkg/keys/printer_test.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gaEnT4VF6zvmxb7P1:-M5gaEnT4VF6zvmxb7P2:bmi4wwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/printer_test.go#L203)):*
> ```Go
> 		{makeKey(ten5KeyGen.TablePrefix(42),
> 			roachpb.RKey(encoding.EncodeVarintAscending(nil, 1222)),
> 			roachpb.RKey(encoding.EncodeStringAscending(nil, "handsome man"))),
> ```

lol, never noticed these mysteriously ridiculous test cases. I'm scared of git blaming them, mostly because I might be the winner
___
*[pkg/keys/tenant.go, line 175 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gZe5a4XVeAfbMEr62:-M5gZe5a4XVeAfbMEr63:b-5c3uyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f7a9167bb7bd6af3fad4f1e2c01cf767db0f/pkg/keys/tenant.go#L175)):*
> ```Go
> 		return 0, errors.Errorf("key is not a descriptor table entry: %v", key)
> 	}
> 	// descID
> ```

partial comment?
___
*[pkg/roachpb/tenant.go, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gW-Cl9KhvFZu768li:-M5gW-Cl9KhvFZu768lj:bgrvkvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L18)):*
> ```Go
> // Each tenant is granted exclusive access to a portion of the keyspace and a
> // collection of SQL tables in that keyspace which comprise a "logical" cluster.
> type TenantID uint64
> ```

Could this be more opaque? It shouldn't just look like an int, i.e. something like


```go
type TenantID struct{id uint64}
```

instead? No SQL uses should never care about the value. They will care whether it's SystemTenantID or not, but that's about it. A tenantID is only initialized in startup code (and tests), so there's going to be a constructor that has an underlying type, but that's it? The underlying type doesn't matter (outside of key encoding/decoding). Makes me wonder whether the tenantID and the structure that holds it for encoding purposes should live together in a `tenantpb` package (I'm fine not making it a protobuf until we have to, it's unclear that we will), so that nobody outside of that package even knows what the underlying type is (you need a constructor of course, but only in one place at startup and in tests).
___
*[pkg/roachpb/tenant.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gWygF151_LfiON_k-:-M5gWygF151_LfiON_k0:bfsv267) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L24)):*
> ```Go
> // system tenant differs from all other tenants in three important ways:
> // 1. the system tenant's keyspace is not prefixed with a tenant specifier.
> // 2. the system tenant is created by default during cluster initialization.
> ```

It's also always present (i.e. can't be destroyed)
___
*[pkg/roachpb/tenant.go, line 25 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gWoySAs0vNvG9mHx3:-M5gWoyTBZsu9oisjgin:b2ni3xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L25)):*
> ```Go
> // 1. the system tenant's keyspace is not prefixed with a tenant specifier.
> // 2. the system tenant is created by default during cluster initialization.
> // 2. the system tenant had the ability to create and destroy other tenants.
> ```

has

**Review by nvb — COMMENTED** [review]
TFTR!

> I left a comment about having the tenantID and its encoding/decoding encapsulated away in a package. I wonder if you had already considered and decided against that.

Discussed inline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-:-M5xsym5A28cMPMZiCNf:b-qsy8uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @tbg)

___
*[pkg/keys/constants.go, line 35 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_PLy2t2yFgqTiIwW:-M5xtMIK48zsEj8Fc54j:bq5z3e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/constants.go#L35)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah, using xfe can't hurt. Let's do it
</blockquote></details>

Done. And updated the doc.
___
*[pkg/keys/constants.go, line 282 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_fHc7GRia3yvyOoE:-M5xvpI34B7YopNJvEdY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/constants.go#L282)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah that seems wrong. I wouldn't set it to tenantPrefix, based on a desire to keep the spans tight and "noninterlinked".
</blockquote></details>

Done.
___
*[pkg/keys/printer.go, line 250 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5g_zWh2Rb8rqsvup58:-M5xx1fbCg4qenjmFkLu:b-l3bk72) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/printer.go#L250)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This method too would be better kept in the hypothetical `tenantpb` package.
</blockquote></details>

Let's discuss on the other thread.
___
*[pkg/keys/printer_test.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gaEnT4VF6zvmxb7P1:-M5xx7Jf45KdQtIOycck:bq7dvhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/printer_test.go#L203)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

lol, never noticed these mysteriously ridiculous test cases. I'm scared of git blaming them, mostly because I might be the winner
</blockquote></details>

I took a look – it wasn't who I thought it would be...
___
*[pkg/keys/tenant.go, line 175 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gZe5a4XVeAfbMEr62:-M5xsRkk1KbiyG57c7SL:b-fsbbmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d9f7a9167bb7bd6af3fad4f1e2c01cf767db0f/pkg/keys/tenant.go#L175)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

partial comment?
</blockquote></details>

Copied from before, but fixed.
___
*[pkg/roachpb/tenant.go, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gW-Cl9KhvFZu768li:-M5xdEzlDHCqTnczVPIS:bktaw4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L18)):*
> something like

Good idea! Done.

I did consider adding a `tenant` package but decided against it. The reason for that is that I don't want this multi-tenancy stuff to be viewed as a half-baked extension to Cockroach. Instead, I want it to be clear that this **is** the new Cockroach. The changes we're making to the keyspace and to the KV layer are fundamental and any new reader of this code should consider multi-tenancy from the beginning.

I also don't think there's enough code in this file to warrant a new package. I could be convinced otherwise though.
___
*[pkg/roachpb/tenant.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gWygF151_LfiON_k-:-M5xkUaW7FhgPpN2MJWT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L24)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's also always present (i.e. can't be destroyed)
</blockquote></details>

Done.
___
*[pkg/roachpb/tenant.go, line 25 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gWoySAs0vNvG9mHx3:-M5xkV07DZBmrGDsXPJA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L25)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

has
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
:lgtm: let's get this in ASAP, I assume it rots out from under you like twice an hour.

@asubiotto did you see this PR?

> Reviewed 90 of 90 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 6 of 6 files at r10, 86 of 86 files at r11, 5 of 5 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-:-M6-crPYBzj9wLu7lsrG:b-u8nys7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @nvanbenschoten)

___
*[c-deps/libroach/encoding.h, line 125 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-beaF-kHNnyoJ6y2k:-M6-beaG1QxmARv-K8f_:bafqvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/c-deps/libroach/encoding.h#L125)):*
> ```objc
> // tbl stores the decoded descriptor ID of the table.
> //
> // TODO(nvanbenschoten): support tenant ID prefix.
> ```

Can you file this one?
___
*[pkg/keys/keys.go, line 693 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-cG8p2MR7vGC9EwD3:-M6-cG8p2MR7vGC9EwD4:b-z7vwtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/pkg/keys/keys.go#L693)):*
> ```Go
> // For secondary index keys, the row prefix is defined as the entire key.
> //
> // TODO(nvanbenschoten): support tenant ID prefix.
> ```

Maybe make a checklist-style issue for completing tenantID support. It can be close to a placeholder only since I assume those will be your next PRs.
___
*[pkg/keys/printer_test.go, line 203 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gaEnT4VF6zvmxb7P1:-M6-WK_L80Ahr0Ziulyi:b95e18n) ([raw file](https://github.com/cockroachdb/cockroach/blob/82bc28e3edc1875a16df921cb107ce68b809f6b7/pkg/keys/printer_test.go#L203)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I took a look – it wasn't who I thought it would be...
</blockquote></details>

Couldn't not do it now, #3055 for anyone else watching.
___
*[pkg/keys/tenant.go, line 58 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-cXQO2iYAZoMtrrQf:-M6-cXQO2iYAZoMtrrQg:b-7q43bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/pkg/keys/tenant.go#L58)):*
> ```Go
> 
> // SystemTenantKeyGen is a SQL key generator for the system tenant.
> var SystemTenantKeyGen = MakeTenantIDKeyGen(roachpb.SystemTenantID)
> ```

In the final code, do you see this used outside of tests at all?
___
*[pkg/roachpb/tenant.go, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gW-Cl9KhvFZu768li:-M6-X9vp8KOl3yyFi8DO:bw0gc98) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> something like

Good idea! Done.

I did consider adding a `tenant` package but decided against it. The reason for that is that I don't want this multi-tenancy stuff to be viewed as a half-baked extension to Cockroach. Instead, I want it to be clear that this **is** the new Cockroach. The changes we're making to the keyspace and to the KV layer are fundamental and any new reader of this code should consider multi-tenancy from the beginning.

I also don't think there's enough code in this file to warrant a new package. I could be convinced otherwise though.
</blockquote></details>

I think our thinking is similar here and I think what I'm after is better phrased as a comment on the state of the encoding routines: It's a shame that SQL and KV are so intermingled here. `pkg/keys` contains a whole bunch of KV internals but ends up also being the place where SQL keys are constructed. I know that there are some legit dependencies, but it's totally unclear what they are, you have to basically look at the callers for each of them which is prohibitive.

Now for constructing SQL keys, I agree that the tenant key gen you made is *the* way to get keys for use by SQL, though the name is perhaps even too tenant-specific then? If there's a `TenantIDKeyGen`, could there be a `NoTenantIDKeyGen`? Nope, could not. What we're looking at is perhaps better named a `SQLKeys` instance (consisting of a `SQLEncoder` (generates keys) and `SQLDecoder` (decodes keys) component if you wanted to pull it apart more). And I think *that* is the thing I would want to see in a separate package, in an ideal world: definitely enough code to justify a package, and also the right boundary. This package would depend only on `encoding` and a few constants: `DescriptorTableID`, etc (and these SQL-specific constants should move with the keygen, out of `keys`). It doesn't seem like it would depend on `keys` which is great because then that can be kv-specific. The packages will catch some dependency because things like the system config etc, but those warts seem like they're going away over time.

I don't think it's necessary to make the changes I'm suggesting here, since we want to move quickly and this PR is already making things better, but I would love to see us headed that way if you're interested. (And even if not, curious whether there's something blocking it).

Something that I will point out again is that it just seems totally random that the tenant ID lives in roachpb. It isn't even a proto and the dependency of `keys` on `roachpb` generally also doesn't seem justified (right?). Curious what your thinking is here.

**Review by nvb — COMMENTED** [review]
TFTR! I responded to your comment about package structure below. I'm happy to continue the discussion because I'd like to get this right, but I'm going to merge this when possible to keep things moving/not rotting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-:-M61Y7s4AJJPZEoECfbj:b1hsv9l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @tbg)

___
*[c-deps/libroach/encoding.h, line 125 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-beaF-kHNnyoJ6y2k:-M61GJsT2X3UtgFPmU9P:b-4qfhld) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/c-deps/libroach/encoding.h#L125)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you file this one?
</blockquote></details>

Done. https://github.com/cockroachdb/cockroach/issues/48122.
___
*[pkg/keys/keys.go, line 693 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-cG8p2MR7vGC9EwD3:-M61GOdD4qYbOunAX_t8:b-mgst6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/pkg/keys/keys.go#L693)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Maybe make a checklist-style issue for completing tenantID support. It can be close to a placeholder only since I assume those will be your next PRs.
</blockquote></details>

This is actually the same issue as https://github.com/cockroachdb/cockroach/issues/48122. I also filed https://github.com/cockroachdb/cockroach/issues/48123 to track the use of `keys.TODOTenantKeyGen` (now `keys.TODOSQLCodec`) more generally.
___
*[pkg/roachpb/tenant.go, line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M5gW-Cl9KhvFZu768li:-M61HbVa9uP-XIVNjZJQ:balhpha) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a38f75536efd8fadfeba5fa33c23da5268a429/pkg/roachpb/tenant.go#L18)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think our thinking is similar here and I think what I'm after is better phrased as a comment on the state of the encoding routines: It's a shame that SQL and KV are so intermingled here. `pkg/keys` contains a whole bunch of KV internals but ends up also being the place where SQL keys are constructed. I know that there are some legit dependencies, but it's totally unclear what they are, you have to basically look at the callers for each of them which is prohibitive.

Now for constructing SQL keys, I agree that the tenant key gen you made is *the* way to get keys for use by SQL, though the name is perhaps even too tenant-specific then? If there's a `TenantIDKeyGen`, could there be a `NoTenantIDKeyGen`? Nope, could not. What we're looking at is perhaps better named a `SQLKeys` instance (consisting of a `SQLEncoder` (generates keys) and `SQLDecoder` (decodes keys) component if you wanted to pull it apart more). And I think *that* is the thing I would want to see in a separate package, in an ideal world: definitely enough code to justify a package, and also the right boundary. This package would depend only on `encoding` and a few constants: `DescriptorTableID`, etc (and these SQL-specific constants should move with the keygen, out of `keys`). It doesn't seem like it would depend on `keys` which is great because then that can be kv-specific. The packages will catch some dependency because things like the system config etc, but those warts seem like they're going away over time.

I don't think it's necessary to make the changes I'm suggesting here, since we want to move quickly and this PR is already making things better, but I would love to see us headed that way if you're interested. (And even if not, curious whether there's something blocking it).

Something that I will point out again is that it just seems totally random that the tenant ID lives in roachpb. It isn't even a proto and the dependency of `keys` on `roachpb` generally also doesn't seem justified (right?). Curious what your thinking is here.
</blockquote></details>

I agree with a lot of what you're saying. For one, you're right that the name is too tenant-specific. I added another commit that renames it to `keys.SQLCodec` with some inner delegation to a `sqlEncoder` and a `sqlDecoder`. That all turned out very well.

The part that I'm less sure about is the package structure. If we pull all of this out of `pkg/keys`, then what is the point of that package? Its godoc says "Package keys manages the construction of keys for CockroachDB's key-value layer." So the construction of SQL keys to be handed to the key-value layer seems very appropriate for `pkg/keys`. Maybe I'm thinking about this incorrectly, but I think it's nice that there's a single package responsible for the structure and encoding of the keyspace instead of fragmenting such responsibility across a series of packages.

But then this begs the question - how much of SQL encoding should live in `./pkg/keys`: just the table ID prefix? the table ID, index ID, and column-family prefix? The entire key? That's where I'm less sure.

Similarly, I don't see it as a problem for tenant ID to live in `roachpb` any more than I see it as a problem that `roachpb.Key` (which `./pkg/keys` has a huge dependency on) or `roachpb.StoreID` live in `roachpb`. `roachpb` is meant to store common type definitions that may be part of protos and that other packages need to depend on. It seems to be serving exactly that goal by hosting `roachpb.TenantID`.
___
*[pkg/keys/tenant.go, line 58 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/47999#-M6-cXQO2iYAZoMtrrQf:-M61G_VtB_C8J1eugJKN:b-dnur3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada04e2e17093f8ab2f4bcdc0cd7ad31ee64e8ac/pkg/keys/tenant.go#L58)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

In the final code, do you see this used outside of tests at all?
</blockquote></details>

I'm not sure. I think it still might be used by code in KV that is specific to the system-tenant. I think we'll have to wait and see.

**Pull request merged**
