### PR TITLE
importccl: Checkpoint SSTable Ingestion

### LINKED ISSUE #23832: import: Checkpoint sstable ingestion
For any given import job, each node that is ingesting sorted data and writing sstables should be able to checkpoint that it has received all information necessary for a given range and successfully imported the resulting sstables.  This will allow import jobs which are restarted to discard individual rows destined for an already-complete range / node.

### PR DESCRIPTION
**Pull request by bobvawter**
This change updates the distributed CSV import system to track which SSTables
have been generated during the import job.  The readCSVProcessor discards rows
which are contained in an already-completed SST.

Compatibility notes: this mechanism depends on two new protobuf fields,
`ReadCSVSpec.drop_complete` and `ImportDetails.Table.span_progress`.  An
updated node will treat (missing) progress information from an old node as
though the spans had not yet been converted to an SSTable.  Old nodes will not
be aware of the new progress information and will still send rows to new nodes
in the shuffle phase, which should still be prepared to ingest the rows.

Resolves #23832

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/ccl/importccl/csv.go, line 1419 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L972t_C3sUfyMOtPIpP:-L972t_C3sUfyMOtPIpQ:b9uc5tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/ccl/importccl/csv.go#L1419)):*
> ```Go
> 					}
> 
> 					// Mark the sst's span as being complete
> ```

It is my opinion that we should not mark individual SSTs in this list, but instead only the sample groups. Reasons:

1. It is fewer writes to the jobs table. With the liveness epoch changes I expect failure to occur less, so I think it's fine to redo slightly more work in order to make this a bit faster. Otherwise each SST write is also blocked on a write to the jobs table, which will contend with all other nodes in the cluster. Might as well reduce that contention if possible.
2. I'm not entirely convinced that the spans (that is, `sst.span`) on two adjacent SSTs are close enough that they will be merged. Also I don't see code in range_group.go that does merging of adjacent ranges, only overlapping ranges.
3. Because we know the spans at the sample groups, we can know that they are perfectly adjacent, and so can be merged.

---

*[pkg/ccl/importccl/csv_test.go, line 944 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L972ZCO5WHcWsNyZ7A-:-L972ZCO5WHcWsNyZ7A0:b-b7y9ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/ccl/importccl/csv_test.go#L944)):*
> ```Go
> 	}
> 
> 	// Since this test reliably triggers the ReadCSV.DropComplete behavior,
> ```

Is there a way to assert that span_progress is populated after the job has paused and before it is resumed?

---

*[pkg/roachpb/span_group.go, line 47 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L970vLoCzxomeYzgC0a:-L970vLpA2S4EF0lHc7c:bqlbtfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/roachpb/span_group.go#L47)):*
> ```Go
> // returning whether the addition(s) increased the span of the group
> // or not.
> func (g *SpanGroup) AddAll(spans []Span) bool {
> ```

This could take a `...Span` which would remove the need for the `Add` function.

---

*[pkg/roachpb/span_group.go, line 103 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9729we8uRmIRxh-He1:-L9729we8uRmIRxh-He2:b-gho8q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/roachpb/span_group.go#L103)):*
> ```Go
> // interval.Comparable types are both just aliases of []byte,
> // we don't have to perform any other conversion.
> func s2r(s Span) interval.Range {
> ```

If Add and AddAll are merged into one function, then this and r2s are each only called once. Does it make sense to have them remain as functions or should they just be inlined? I learn toward removing the functions, but I can see the argument for keeping them explicit too, if you think that's better. Whatever.

---

*[pkg/sql/distsqlrun/processors.proto, line 530 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L971yOU9GA-wVQC4cyu:-L971yOU9GA-wVQC4cyv:bf1nlvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/sql/distsqlrun/processors.proto#L530)):*
> ```protobuf
>   // progress information to discard rows that are destined for
>   // spans which are already marked as complete.
>   optional bool drop_complete = 8 [(gogoproto.nullable) = false];
> ```

I don't see the need for this. During sampling the span_progress will be empty, so it won't do anything. Does it have another purpose?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375)*

**Comment by bobvawter** [comment]
PTAL

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/ccl/importccl/csv.go, line 1419 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L972t_C3sUfyMOtPIpP:-L9CN4rBBQ82aTUiR0Hv:bvekb3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/ccl/importccl/csv.go#L1419)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

It is my opinion that we should not mark individual SSTs in this list, but instead only the sample groups. Reasons:

1. It is fewer writes to the jobs table. With the liveness epoch changes I expect failure to occur less, so I think it's fine to redo slightly more work in order to make this a bit faster. Otherwise each SST write is also blocked on a write to the jobs table, which will contend with all other nodes in the cluster. Might as well reduce that contention if possible.
2. I'm not entirely convinced that the spans (that is, `sst.span`) on two adjacent SSTs are close enough that they will be merged. Also I don't see code in range_group.go that does merging of adjacent ranges, only overlapping ranges.
3. Because we know the spans at the sample groups, we can know that they are perfectly adjacent, and so can be merged.
</blockquote></details>

Progress is now tracked on a per-split basis.

---

*[pkg/ccl/importccl/csv_test.go, line 944 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L972ZCO5WHcWsNyZ7A-:-L9CNIgq5PP4b3j4rj3E:b-13ei46) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/ccl/importccl/csv_test.go#L944)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Is there a way to assert that span_progress is populated after the job has paused and before it is resumed?
</blockquote></details>

The test has been updated to verify that the entire table keyspace is marked as complete.

---

*[pkg/roachpb/span_group.go, line 47 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L970vLoCzxomeYzgC0a:-L9CNO5B6zalQsTBcuzj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/roachpb/span_group.go#L47)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This could take a `...Span` which would remove the need for the `Add` function.
</blockquote></details>

Done.

---

*[pkg/roachpb/span_group.go, line 103 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9729we8uRmIRxh-He1:-L9CODYp0_IDy-9Zdhw1:b-r5aksf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/roachpb/span_group.go#L103)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

If Add and AddAll are merged into one function, then this and r2s are each only called once. Does it make sense to have them remain as functions or should they just be inlined? I learn toward removing the functions, but I can see the argument for keeping them explicit too, if you think that's better. Whatever.
</blockquote></details>

`s2r()` has multiple callers now.

---

*[pkg/sql/distsqlrun/processors.proto, line 530 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L971yOU9GA-wVQC4cyu:-L9CNS6tEyJ0v6em2t7S:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7bc83ca3e865850b0f60f1c8cbf63913a19a22d/pkg/sql/distsqlrun/processors.proto#L530)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't see the need for this. During sampling the span_progress will be empty, so it won't do anything. Does it have another purpose?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-:-L9CN-l7BfriGTybqHas:bb71pro)*

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/importccl/csv.go, line 1457 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9E9Yms7gw6Bd92Y_kA:-L9E9Yms7gw6Bd92Y_kB:bns98i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6900027b4657330bbc06ea3cff96e6cd591832b7/pkg/ccl/importccl/csv.go#L1457)):*
> ```Go
> 					d.Tables[0].SpanProgress = sg.Slice()
> 					return nil
> 				}(); err != nil {
> ```

Since the only error that can occur here is from DecodeTablePrefix, I think it's safe to return the error upstream even though it would fatal the job. This is because that error indicates something is very wrong and we should fatal the job.

---

*[pkg/ccl/importccl/csv_test.go, line 957 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9EAVTCA01yE09TIymJ:-L9EAVTCA01yE09TIymK:b-gqhk28) ([raw file](https://github.com/cockroachdb/cockroach/blob/6900027b4657330bbc06ea3cff96e6cd591832b7/pkg/ccl/importccl/csv_test.go#L957)):*
> ```Go
> 	}
> 
> 	// Ensure that an entire table range is marked as complete
> ```

I think you can do `rescheduledLease.Details.(*jobs.Payload_Import).Import.Tables[0].Desc.TableSpan().EqualValue(spans)`

---

*[pkg/roachpb/span_group.go, line 86 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9E7MwN8NN8hmWLffY_:-L9E7MwN8NN8hmWLffYa:b-1nhs5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6900027b4657330bbc06ea3cff96e6cd591832b7/pkg/roachpb/span_group.go#L86)):*
> ```Go
> 	rg := g.rg
> 	if rg == nil {
> 		return []Span{}
> ```

This should return nil.

---

*[pkg/testutils/jobutils/jobs_verification.go, line 170 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9EBDTn0c2SJWvZjBzw:-L9EBDTn0c2SJWvZjBzx:b-ppyf96) ([raw file](https://github.com/cockroachdb/cockroach/blob/6900027b4657330bbc06ea3cff96e6cd591832b7/pkg/testutils/jobutils/jobs_verification.go#L170)):*
> ```Go
> func GetJobPayload(t *testing.T, db *sqlutils.SQLRunner, jobID int64) *jobs.Payload {
> 	ret := &jobs.Payload{}
> 	{
> ```

nit: no need for these scoping `{}`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375)*

**Comment by mjibson** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/distsql_plan_csv.go, line 257 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9GrNiK3goPqj28sKHq:-L9GrNiK3goPqj28sKHr:b-8trswh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9e40810adc536606e8f0412ef8ac3083afc489/pkg/sql/distsql_plan_csv.go#L257)):*
> ```Go
> 		// prevent the RangeRouter from erroring out, at the cost of an
> 		// imbalanced data flow.
> 		DefaultDest: &defaultStream,
> ```

If this happens, then that node will generate some SSTs that span way more than its target range. During addsstable, this will cause a "addsstable over a split" error. We need to rethink this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375)*

**Comment by benesch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/span_group.go, line 86 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-L9E7MwN8NN8hmWLffY_:-L9GzS3I6g_OHuNxJbTw:bddarjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6900027b4657330bbc06ea3cff96e6cd591832b7/pkg/roachpb/span_group.go#L86)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Done.  Still weirds me out that `nil` is  a useful value.
</blockquote></details>

This bothers me too, especially because `nil` maps will blow up if you try to use them. ¯\_(ツ)_/¯  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375)*

**Comment by mjibson** [comment]
:lgtm:

Nice!

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24375#-:-L9fbgLh5c4DPXSkhzxn:bli1pub)*

**Pull request merged**
