### PR TITLE
ts: use AmbientContext in poller, ts.Server

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of #9807.

@tamird @tschottdorf @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9951)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ts/db.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-KTzoo0GO0ITz7zFxn3E:-KTzmcD9_Fcpc5bGnbfd:btfcml3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c13a5662ad2b4c91c45408b31ffaa074137185e/pkg/ts/db.go#L50)):*
> ```Go
> // poller maintains information for a polling process started by PollSource().
> type poller struct {
> 	log.AmbientContext
> ```

I'll annoyingly suggest we add more guidance on the usage comment on `AmbientContext` to cover both embedding and usage within a `RunTask/RunWorker`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-:-KTzpbZSe5O0asCDpi3K:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ts/db.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-KTzpzegpLOMhxq4RcVj:-KTzpzegpLOMhxq4RcVk:bd8h8vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c13a5662ad2b4c91c45408b31ffaa074137185e/pkg/ts/db.go#L116)):*
> ```Go
> 		}
> 	}); err != nil {
> 		log.Warning(p.AnnotateCtx(context.Background()), err)
> ```

this one might want to be TODO since it's not async

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-:-KTzq3UayHDxp-HAAMOB:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ts/db.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-KTzoo0GO0ITz7zFxn3E:-KU1XlYTByIdlqqh3W6B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c13a5662ad2b4c91c45408b31ffaa074137185e/pkg/ts/db.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> I'll annoyingly suggest we add more guidance on the usage comment on `AmbientContext` to cover both embedding and usage within a `RunTask/RunWorker`.
</details>
Done.

---

*[pkg/ts/db.go, line 116 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-KTzpzegpLOMhxq4RcVj:-KU1WkgWOV3HDEqjKiuB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c13a5662ad2b4c91c45408b31ffaa074137185e/pkg/ts/db.go#L116)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this one might want to be TODO since it's not async
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/util/log/ambient_context.go, line 28 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951#-KU1xLlA1VX7TCwUV7Zj:-KU1xLlBucSxVvIzuzKe:b-813th4) ([raw file](https://github.com/cockroachdb/cockroach/blob/655e68001d3e704e2d2fff68cc2f651167b3b7a7/pkg/util/log/ambient_context.go#L28)):*
> ```Go
> // AmbientContext is a helper type used to "annotate" context.Contexts with log
> // tags and a Tracer or EventLog. It is intended to be embedded into various
> // serer components.
> ```

Serer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9951)*

**Pull request merged**
