### PR TITLE
cdc: allow setting client_cert and client_key in schema registry URI

### LINKED ISSUE #96470: changefeed schemaregistry mtls feature request
**Is your feature request related to a problem? Please describe.**
Creating this feature request as requested on behalf customer. I've asked them to provide further details.

**Describe the solution you'd like**
changefeed feature request to support ca_cert client_cert and client_key in the schema registry option.

**Describe alternatives you've considered**
Unknown

**Additional context**
we have self hosted kafka and schema registry which supports mtls authentication only. Since we are unable to pass the cert related query parameters with the schema registry we are unable to use avro format.

Jira issue: CRDB-24139

### PR DESCRIPTION
**Pull request by HonoreDB**
Only the ca_cert param was supported in the WITH confluent_schema_registry URI, meaning that our client could be told how to verify the endpoint, but not how to authenticate to it.
This PR adds support for the client_cert and client_key params. These are the same as the params of the same name in the Kafka and webhook sinks.

Addresses https://github.com/cockroachdb/cockroach/issues/64622
Fixes #96470

Release note (enterprise change): The confluent_schema_registry URI for avro changefeeds now supports client_cert and client_key params.

### CODE REVIEW

**Comment by HonoreDB** [comment]
Haven't end-to-end tested this locally yet, but the tests pass and this is the same logic the webhook sink uses, so I'd be surprised if there's an issue.

**Review by jayshrivastava — APPROVED** [review]
Just a small comment. LGTM otherwise. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96510#-:-NNNrbZm0ZZBBot6rRQo:b-xrisnw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)

___
*[`pkg/ccl/changefeedccl/schema_registry.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96510#-NNNqill4sUppnsOaJ_y:-NNNqill4sUppnsOaJ_z:b-3z62ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e4ea86f9083e1ede7d925809a63f25d62287562/pkg/ccl/changefeedccl/schema_registry.go#L85)):*
> ```Go
> 		if stringParam := query.Get(k); stringParam != "" {
> 			var decoded []byte
> 			err := decodeBase64FromString(stringParam, &decoded)
> ```

ultra mega nit: consider not storing decoded keys in memory for longer than we need to. we can store the encoded keys in the `schemaRegistryParams` struct and decode them in `newClientFromTLSKeyPair()`

**Comment by HonoreDB** [comment]
...and, twelve years later, I have successfully tested this locally. TFTR, I'll address that comment.

**Comment by HonoreDB** [comment]
Actually, the "decoding" in question is just base64 decoding, so I don't think we get any security benefit from delaying it, can follow up if you disagree.

**Comment by HonoreDB** [comment]
bors r=[jayshrivastava]

**Pull request merged**
