### PR TITLE
sql: support MATERIALIZED syntax in CTEs

### LINKED ISSUE #45863: opt: Support AS MATERIALIZED option in CTEs
PG 12 supports `AS MATERIALIZED` and `AS NOT MATERIALIZED` syntax for user controller of CTE materialization. For example:
```
WITH x AS MATERIALIZED (SELECT * FROM very_large_table) SELECT * FROM x;
```
With this syntax, the user can override the optimizer's default decision to not materialize that table (since it's only referenced once).
```
WITH x AS NOT MATERIALIZED (SELECT * FROM very_small_table) SELECT * FROM x UNION ALL SELECT * FROM x;
```
Similarly, this syntax allows the user to override the optimizer's default decision to materialize the table (since it's referenced multiple times).

Adding this option requires adding a flag to the generated `WithPrivate` struct, and then updating the parser to parse the new syntax, and set the flag. The optimizer's `InlineWith` rule (see `with.opt`) then changes to take into account the new flag.

### PR DESCRIPTION
**Pull request by Anthuang**
The MATERIALIZED/NOT MATERIALIZED syntax, introduced in PostgresSQL 12,
allows the user to override the optimizer's default decision to
not materialize/materialize a table, respectively.

For example, the following query is non-recursive and side-effect-free
so the optimizer will not materialize the table by default:
```
WITH cte AS (SELECT 1) SELECT * FROM cte
```

To force materialization, `MATERIALIZED` can be specified explcitly:
```
WITH cte AS MATERIALIZED (SELECT 1) SELECT * FROM cte
```

Similarly, the opposite can be done:
```
WITH cte AS NOT MATERIALIZED (SELECT 1/0) SELECT * FROM cte
```

Or even for multiple different CTEs:
```
WITH cte (x) AS MATERIALIZED (INSERT INTO abc VALUES (1, 2)), cte2 (y)
  AS NOT MATERIALIZED (SELECT x + 1 FROM cte) SELECT * FROM cte, cte2
```

Resolves: #45863 

Release note (sql change): CTEs were extended to support
the MATERIALIZED/NOT MATERIALIZED syntax added in
PostgreSQL 12.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Very nice work! Looks great overall.

One thing is to consider how this should work with RECURSIVE (and maybe we need to investigate exactly how it works with pg). I think there should be an error when it is used with a recursive CTE. But do we want to disallow the combination in the syntax altogether? What if you use WITH RECURSIVE but the CTE is not actually recursive (especially useful when you define multiple CTEs, some of which are recursive), should it be allowed? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-:-M4_sUntBMm_OtoqnDPu:b-9tngmk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anthuang)

___
*[pkg/sql/opt/memo/expr_format.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_rjWB6I3hHNgjf19a:-M4_rjWB6I3hHNgjf19b:br0m6yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/opt/memo/expr_format.go#L221)):*
> ```Go
> 			fmt.Fprintf(f.Buffer, " (%s)", t.Name)
> 		}
> 		if t.Mtr.Set {
> ```

[nit] I would make this a "field" under the node (use tp.Childf), and name it `materialized` / `not-materialized`
___
*[pkg/sql/opt/norm/custom_funcs.go, line 2046 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_rLNM0UcnE1EiGsTC:-M4_rLNM0UcnE1EiGsTD:b-879zwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/opt/norm/custom_funcs.go#L2046)):*
> ```Go
> func (c *CustomFuncs) CanInlineWith(binding, expr memo.RelExpr, private *memo.WithPrivate) bool {
> 	if private.Mtr.Set {
> 		return !private.Mtr.Materialize
> ```

[nit] add a short comment explaining that this setting is meant to override this rule, regardless of the checks below
___
*[pkg/sql/opt/norm/testdata/rules/with, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_sLQC9Oz1umTw6rOD:-M4_sLQC9Oz1umTw6rOE:b-v0nmbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/opt/norm/testdata/rules/with#L769)):*
> ```
>  │    └── (1 / 0,)
>  └── projections
>       └── "?column?":1 [as="?column?":2, outer=(1)]
> ```

Also add a test where the CTE is used multiple times in the query and we use `NOT MATERIALIZED`
___
*[pkg/sql/parser/parse_test.go, line 1420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_tADhAyf1Fu2i4vob:-M4_tADhAyf1Fu2i4voc:b-8lx8lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/parser/parse_test.go#L1420)):*
> ```Go
> 		{`WITH cte (x) AS (INSERT INTO abc VALUES (1, 2)), cte2 (y) AS (SELECT x + 1 FROM cte) SELECT * FROM cte, cte2`},
> 		{`WITH RECURSIVE cte (x) AS (SELECT 1), cte2 (y) AS (SELECT x + 1 FROM cte) SELECT 1`},
> 		{`WITH cte AS MATERIALIZED (SELECT 1) SELECT * FROM cte`},
> ```

Add some testcases with RECURSIVE
___
*[pkg/sql/parser/sql.y, line 6423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_qHV2D7OGRGp7IQtM:-M4_qHV2D7OGRGp7IQtN:blvo1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/parser/sql.y#L6423)):*
> ```Yacc
> common_table_expr:
>   table_alias_name opt_column_list AS '(' preparable_stmt ')'
>    	{
> ```

[nit] I think we try to avoid tabs in this file
___
*[pkg/sql/sem/tree/with.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-M4_r35B0J8M4Br2fPvx:-M4_r35B0J8M4Br2fPvy:b-ycw88q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6744b961fb3c8b84cc0a2562b203e022864ce93e/pkg/sql/sem/tree/with.go#L28)):*
> ```Go
> // MaterializeClause represents a materialize clause inside of a WITH clause.
> type MaterializeClause struct {
> 	Materialize bool
> ```

[nit] move Set to be the first field, and some field comments (in particular that Materialize can only be used when Set is true)

**Comment by Anthuang** [comment]
From running some queries, it seems to me like Postgres ignores "NOT MATERIALIZED" in the presence of "RECURSIVE".

Also, it seems like Postgres doesn't allow non-recursive CTEs with "RECURSIVE" is specified:
```
postgres=# WITH RECURSIVE t(n) AS (SELECT * FROM t) SELECT * FROM t;
ERROR:  recursive query "t" does not have the form non-recursive-term UNION [ALL] recursive-term
```

I get the same result with:
```
postgres=# WITH RECURSIVE t(n) AS (SELECT * FROM t), s(n) AS (VALUES (1) UNION ALL SELECT n+1 FROM t WHERE n < 100 ) SELECT * FROM t;
ERROR:  recursive query "t" does not have the form non-recursive-term UNION [ALL] recursive-term
```

I think it's valid, then, to just throw an error.

**Comment by RaduBerinde** [comment]
In your examples, you are defining the CTE `t` and then using `t` inside, in a way that doesn't match the recursive CTE usage. That is what's causing the error. If you rename it, it works:
```
radu=> WITH RECURSIVE cte1(n) AS (SELECT * FROM t) SELECT * FROM cte1;
 n 
---
 1
 2
 3
(3 rows)
```

**Comment by Anthuang** [comment]
Ah, my bad. In that case I think it makes sense to allow the combination so that we can support the usecase you mentioned.

**Comment by Anthuang** [comment]
Could you explain how recursive CTEs are built? I'm reading the code but I want to make sure I don't miss anything.

Thank you for all your help so far, Radu!

**Comment by RaduBerinde** [comment]
The logic is all in this function: https://github.com/cockroachdb/cockroach/blob/4994d4a9b48870424790b3a24968db3ead051fc4/pkg/sql/opt/optbuilder/with.go#L34

If we want to ignore the clause for recursive CTEs, I don't think you need to change anything right? Other than adding some tests with the combination.

**Comment by Anthuang** [comment]
If we don't change anything, wouldn't specifying the `MATERIALIZED`/`NOT MATERIALIZED` clause on recursive CTEs currently cause the default behavior to be overridden?

Seems like running these two queries give me different results:
```
EXPLAIN WITH RECURSIVE t(n) AS MATERIALIZED (VALUES (1) UNION ALL SELECT n+1 FROM t WHERE n < 100 ) SELECT sum(n) FROM t;
                tree                |    field     |                      description
------------------------------------+--------------+---------------------------------------------------------
                                    | distributed  | false
                                    | vectorized   | false
  root                              |              |
   ├── group                        |              |
   │    │                           | aggregate 0  | sum(column1)
   │    │                           | scalar       |
   │    └── scan buffer node        |              |
   │                                | label        | buffer 2 (t)
   └── subquery                     |              |
        │                           | id           | @S1
        │                           | original sql | VALUES (1) UNION ALL SELECT n + 1 FROM t WHERE n < 100
        │                           | exec mode    | all rows
        └── buffer node             |              |
             │                      | label        | buffer 2 (t)
             └── recursive cte node |              |
                  │                 | label        | working buffer (t)
                  └── values        |              |
                                    | size         | 1 column, 1 row
```
```
EXPLAIN WITH RECURSIVE t(n) AS NOT MATERIALIZED (VALUES (1) UNION ALL SELECT n+1 FROM t WHERE n < 100 ) SELECT sum(n) FROM t;
              tree             |    field    |    description
-------------------------------+-------------+---------------------
                               | distributed | false
                               | vectorized  | false
  group                        |             |
   │                           | aggregate 0 | sum(n)
   │                           | scalar      |
   └── render                  |             |
        └── recursive cte node |             |
             │                 | label       | working buffer (t)
             └── values        |             |
                               | size        | 1 column, 1 row
```

**Review by Anthuang — COMMENTED** [review]
I've resolved all of the comments! Not exactly sure how to get that to show up on Github..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-:-M59sHmx5wrZfIWhyL9N:bj3tifj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
Sorry for missing your earlier update. I see, so even for recursive CTEs we can control whether the result of the recursive CTE is stored in a buffer or used directly. I think that is just fine. Let's just add some tests in norm/testdata/rules/with with the recursive variant so it's clear what they do, and then we can merge.

Thank you for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-:-M5AUXOD6gTM2hMvLC42:brkzkjz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by Anthuang — COMMENTED** [review]
Done! How should I proceed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47341#-:-M5dIvadB1OF-RXuryPm:b-7n1ext)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
LGTM, thanks!

bors r+

**Pull request merged**
