### PR TITLE
docgen: update SQL diagrams for triggers

### PR DESCRIPTION
**Pull request by taroface**
Made updates to the CREATE TRIGGER and DROP TRIGGER SQL diagrams. These will be used with the docs added in https://github.com/cockroachdb/docs/pull/19129

The generated diagrams:
image

image

Epic: none
Release note: none
Release justification: non-production code change

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135051#-:-OBYi8TX1tFeaR2HIVNU:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @taroface)

**Comment by taroface** [comment]
bors r=DrewKimball

**Comment by taroface** [comment]
bors r=DrewKimball

**Comment by taroface** [comment]
bors r=DrewKimball

**Pull request merged**
