### PR TITLE
sql: turn on column family heuristics

### PR DESCRIPTION
**Pull request by danhhz**
```
name                                    old time/op    new time/op    delta
Bank2_Cockroach-32                        12.2ms ± 6%    14.3ms ±29%     ~             (p=0.690 n=5+5)
Bank4_Cockroach-32                        8.78ms ±25%    9.02ms ±26%     ~             (p=1.000 n=5+5)
Bank8_Cockroach-32                        4.74ms ±25%    4.40ms ±25%     ~             (p=0.548 n=5+5)
Bank16_Cockroach-32                       3.00ms ±47%    3.33ms ±20%     ~             (p=0.310 n=5+5)
Bank32_Cockroach-32                       2.26ms ±20%    1.98ms ±18%     ~             (p=0.310 n=5+5)
Bank64_Cockroach-32                       1.40ms ±23%    1.66ms ±40%     ~             (p=0.222 n=5+5)
Select1_Cockroach-32                      61.7µs ± 1%    64.1µs ± 1%   +3.91%          (p=0.008 n=5+5)
Select2_Cockroach-32                       801µs ± 1%     674µs ± 1%  -15.88%          (p=0.008 n=5+5)
Select3_Cockroach-32                      1.07ms ± 1%    0.94ms ± 1%  -12.33%          (p=0.008 n=5+5)
Insert1_Cockroach-32                       513µs ± 1%     521µs ± 3%     ~             (p=0.056 n=5+5)
Insert10_Cockroach-32                      671µs ± 2%     675µs ± 1%     ~             (p=0.690 n=5+5)
Insert100_Cockroach-32                    1.82ms ± 1%    1.81ms ± 2%     ~             (p=0.222 n=5+5)
Insert1000_Cockroach-32                   12.1ms ± 5%    12.0ms ± 4%     ~             (p=0.421 n=5+5)
Update1_Cockroach-32                       715µs ± 2%     720µs ± 0%     ~             (p=0.095 n=5+5)
Update10_Cockroach-32                     1.14ms ± 2%    1.13ms ± 2%     ~             (p=0.421 n=5+5)
Update100_Cockroach-32                    4.53ms ± 1%    4.33ms ± 2%   -4.46%          (p=0.008 n=5+5)
Update1000_Cockroach-32                   34.5ms ± 1%    33.3ms ± 2%   -3.66%          (p=0.008 n=5+5)
Upsert1_Cockroach-32                      1.75ms ± 1%    1.68ms ± 1%   -4.01%          (p=0.008 n=5+5)
Upsert10_Cockroach-32                     2.20ms ± 2%    1.93ms ± 3%  -12.24%          (p=0.008 n=5+5)
Upsert100_Cockroach-32                    7.24ms ± 3%    4.73ms ± 3%  -34.72%          (p=0.008 n=5+5)
Upsert1000_Cockroach-32                   55.5ms ± 3%    30.4ms ± 3%  -45.30%          (p=0.008 n=5+5)
Delete1_Cockroach-32                       733µs ± 1%     693µs ± 2%   -5.45%          (p=0.008 n=5+5)
Delete10_Cockroach-32                     1.25ms ± 2%    0.85ms ± 2%  -31.91%          (p=0.008 n=5+5)
Delete100_Cockroach-32                    6.33ms ± 0%    2.35ms ± 2%  -62.82%          (p=0.008 n=5+5)
Delete1000_Cockroach-32                   63.4ms ± 3%    17.9ms ± 2%  -71.80%          (p=0.008 n=5+5)
Scan1_Cockroach-32                         182µs ± 2%     185µs ± 1%     ~             (p=0.095 n=5+5)
Scan10_Cockroach-32                        210µs ± 2%     214µs ± 2%     ~             (p=0.151 n=5+5)
Scan100_Cockroach-32                       479µs ± 1%     488µs ± 1%   +1.68%          (p=0.008 n=5+5)
Scan1000_Cockroach-32                     2.68ms ± 2%    2.74ms ± 2%     ~             (p=0.095 n=5+5)
Scan10000_Cockroach-32                    23.9ms ± 1%    24.3ms ± 4%     ~             (p=0.151 n=5+5)
Scan1000Limit1_Cockroach-32                192µs ± 1%     195µs ± 2%     ~             (p=0.095 n=5+5)
Scan1000Limit10_Cockroach-32               223µs ± 2%     227µs ± 2%     ~             (p=0.095 n=5+5)
Scan1000Limit100_Cockroach-32              477µs ± 1%     484µs ± 3%     ~             (p=0.095 n=5+5)
Scan10000FilterLimit1_Cockroach-32         379µs ± 1%     384µs ± 2%     ~             (p=0.056 n=5+5)
Scan10000FilterLimit10_Cockroach-32        427µs ± 1%     429µs ± 4%     ~             (p=1.000 n=5+5)
Scan10000FilterLimit50_Cockroach-32       2.49ms ± 2%    2.47ms ± 1%     ~             (p=0.690 n=5+5)
Sort100000Limit10_Cockroach-32             483ms ± 1%     220ms ± 5%  -54.45%          (p=0.008 n=5+5)
Sort100000Limit10Distinct_Cockroach-32     498ms ± 2%     239ms ± 2%  -52.09%          (p=0.008 n=5+5)
TrackChoices1_Cockroach-32                 582µs ± 2%     574µs ± 2%     ~             (p=0.222 n=5+5)
TrackChoices10_Cockroach-32                117µs ± 3%     110µs ± 5%   -5.64%          (p=0.016 n=5+5)
TrackChoices100_Cockroach-32              66.1µs ± 2%    61.5µs ± 4%   -6.95%          (p=0.008 n=5+5)
TrackChoices1000_Cockroach-32             62.7µs ± 4%    54.2µs ± 3%  -13.62%          (p=0.008 n=5+5)
InsertDistinct1_Cockroach-32              1.56ms ± 2%    1.59ms ± 2%     ~             (p=0.151 n=5+5)
InsertDistinct10_Cockroach-32             1.09ms ± 2%    1.19ms ± 7%   +9.64%          (p=0.032 n=5+5)
InsertDistinct100_Cockroach-32            1.34ms ± 2%    1.80ms ±15%  +34.41%          (p=0.008 n=5+5)
WideTable1_Cockroach-32                   2.19ms ± 1%    2.31ms ± 2%   +5.44%          (p=0.008 n=5+5)
WideTable10_Cockroach-32                  3.42ms ± 1%    3.68ms ± 2%   +7.43%          (p=0.008 n=5+5)
WideTable100_Cockroach-32                 15.2ms ± 2%    16.0ms ± 1%   +4.99%          (p=0.008 n=5+5)
WideTable1000_Cockroach-32                 132ms ± 2%     136ms ± 2%   +2.83%          (p=0.016 n=5+5)
PgbenchQuery_Cockroach-32                 3.21ms ± 2%    3.08ms ± 2%   -4.07%          (p=0.016 n=5+5)
ParallelPgbenchQuery_Cockroach-32        32.7ms ±114%    25.7ms ±47%     ~             (p=0.421 n=5+5)

name                                    old alloc/op   new alloc/op   delta
Bank2_Cockroach-32                        1.08MB ±24%    1.16MB ± 7%     ~             (p=0.548 n=5+5)
Bank4_Cockroach-32                         862kB ±34%     828kB ±27%     ~             (p=0.690 n=5+5)
Bank8_Cockroach-32                         558kB ±12%     580kB ±17%     ~             (p=0.548 n=5+5)
Bank16_Cockroach-32                        429kB ± 4%     444kB ±14%     ~             (p=0.690 n=5+5)
Bank32_Cockroach-32                        345kB ±12%     329kB ±10%     ~             (p=0.548 n=5+5)
Bank64_Cockroach-32                        256kB ± 4%     263kB ± 1%     ~             (p=0.056 n=5+5)
Select1_Cockroach-32                      3.73kB ± 0%    3.73kB ± 0%     ~             (p=0.063 n=5+5)
Select2_Cockroach-32                      91.8kB ± 0%    71.4kB ± 0%  -22.25%          (p=0.008 n=5+5)
Select3_Cockroach-32                       136kB ± 0%     116kB ± 0%  -15.00%          (p=0.008 n=5+5)
Insert1_Cockroach-32                      29.8kB ± 0%    29.8kB ± 0%     ~             (p=0.421 n=5+5)
Insert10_Cockroach-32                     74.9kB ± 0%    74.9kB ± 0%     ~             (p=0.333 n=5+5)
Insert100_Cockroach-32                     488kB ± 0%     488kB ± 0%     ~             (p=0.841 n=5+5)
Insert1000_Cockroach-32                   4.18MB ± 0%    4.18MB ± 0%     ~             (p=0.841 n=5+5)
Update1_Cockroach-32                      51.7kB ± 0%    51.6kB ± 0%   -0.14%          (p=0.008 n=5+5)
Update10_Cockroach-32                      122kB ± 0%     120kB ± 0%   -1.57%          (p=0.016 n=4+5)
Update100_Cockroach-32                     795kB ± 0%     774kB ± 0%   -2.68%          (p=0.016 n=4+5)
Update1000_Cockroach-32                   6.59MB ± 0%    6.39MB ± 0%   -3.01%          (p=0.029 n=4+4)
Upsert1_Cockroach-32                       104kB ± 0%      98kB ± 0%   -6.01%          (p=0.008 n=5+5)
Upsert10_Cockroach-32                      172kB ± 0%     129kB ± 0%  -25.06%          (p=0.008 n=5+5)
Upsert100_Cockroach-32                     942kB ± 0%     554kB ± 0%  -41.22%          (p=0.008 n=5+5)
Upsert1000_Cockroach-32                   7.87MB ± 1%    4.48MB ± 0%  -43.10%          (p=0.008 n=5+5)
Delete1_Cockroach-32                      45.3kB ± 0%    44.0kB ± 0%   -2.87%          (p=0.008 n=5+5)
Delete10_Cockroach-32                     70.3kB ± 0%    54.1kB ± 0%  -23.06%          (p=0.008 n=5+5)
Delete100_Cockroach-32                     307kB ± 0%     155kB ± 0%  -49.35%          (p=0.008 n=5+5)
Delete1000_Cockroach-32                   3.19MB ± 0%    1.07MB ± 0%  -66.46%          (p=0.016 n=4+5)
Scan1_Cockroach-32                        16.0kB ± 0%    16.0kB ± 0%     ~             (p=0.365 n=5+5)
Scan10_Cockroach-32                       19.5kB ± 0%    19.5kB ± 0%     ~             (p=0.968 n=5+5)
Scan100_Cockroach-32                      50.5kB ± 0%    50.5kB ± 0%     ~             (p=0.730 n=5+5)
Scan1000_Cockroach-32                      318kB ± 0%     318kB ± 0%     ~             (p=1.000 n=5+5)
Scan10000_Cockroach-32                    5.54MB ± 0%    5.54MB ± 0%     ~             (p=0.841 n=5+5)
Scan1000Limit1_Cockroach-32               16.6kB ± 0%    16.6kB ± 0%     ~             (p=0.952 n=5+5)
Scan1000Limit10_Cockroach-32              19.9kB ± 0%    19.9kB ± 0%     ~             (p=0.667 n=5+5)
Scan1000Limit100_Cockroach-32             50.8kB ± 0%    50.8kB ± 0%     ~             (p=0.992 n=5+5)
Scan10000FilterLimit1_Cockroach-32        48.6kB ± 0%    48.6kB ± 0%     ~             (p=0.421 n=5+5)
Scan10000FilterLimit10_Cockroach-32       54.8kB ± 0%    54.8kB ± 0%     ~             (p=1.000 n=5+5)
Scan10000FilterLimit50_Cockroach-32        462kB ± 0%     462kB ± 0%     ~             (p=0.952 n=5+5)
Sort100000Limit10_Cockroach-32             118MB ± 0%      42MB ± 0%  -64.13%          (p=0.029 n=4+4)
Sort100000Limit10Distinct_Cockroach-32     136MB ± 0%      60MB ± 0%  -55.87%          (p=0.008 n=5+5)
TrackChoices1_Cockroach-32                46.6kB ± 0%    44.0kB ± 0%   -5.68%          (p=0.008 n=5+5)
TrackChoices10_Cockroach-32               23.5kB ± 0%    16.5kB ± 0%  -29.72%          (p=0.008 n=5+5)
TrackChoices100_Cockroach-32              20.0kB ± 0%    16.0kB ± 0%  -19.99%          (p=0.008 n=5+5)
TrackChoices1000_Cockroach-32             22.7kB ± 0%    17.8kB ± 0%  -21.70%          (p=0.016 n=4+5)
InsertDistinct1_Cockroach-32               303kB ± 0%     303kB ± 0%     ~             (p=0.635 n=5+5)
InsertDistinct10_Cockroach-32              316kB ± 0%     323kB ± 2%   +2.41%          (p=0.008 n=5+5)
InsertDistinct100_Cockroach-32             473kB ± 0%     540kB ±19%  +14.19%          (p=0.032 n=5+5)
WideTable1_Cockroach-32                    170kB ± 0%     170kB ± 0%   +0.52%          (p=0.016 n=5+4)
WideTable10_Cockroach-32                   373kB ± 0%     374kB ± 0%   +0.36%          (p=0.008 n=5+5)
WideTable100_Cockroach-32                 2.36MB ± 0%    2.36MB ± 0%   +0.15%          (p=0.008 n=5+5)
WideTable1000_Cockroach-32                21.2MB ± 0%    21.2MB ± 0%     ~             (p=0.056 n=5+5)
PgbenchQuery_Cockroach-32                  277kB ± 0%     247kB ± 0%  -10.68%          (p=0.029 n=4+4)
ParallelPgbenchQuery_Cockroach-32         1.41MB ± 4%    1.33MB ± 6%     ~             (p=0.056 n=5+5)

name                                    old allocs/op  new allocs/op  delta
Bank2_Cockroach-32                         11.6k ±20%     12.5k ± 8%     ~             (p=0.421 n=5+5)
Bank4_Cockroach-32                         9.56k ±30%     9.20k ±21%     ~             (p=0.841 n=5+5)
Bank8_Cockroach-32                         6.45k ±10%     6.64k ±15%     ~             (p=0.548 n=5+5)
Bank16_Cockroach-32                        5.00k ± 4%     5.10k ±12%     ~             (p=0.690 n=5+5)
Bank32_Cockroach-32                        4.03k ±10%     3.89k ± 7%     ~             (p=0.690 n=5+5)
Bank64_Cockroach-32                        3.03k ± 4%     3.14k ± 1%     ~             (p=0.056 n=5+5)
Select1_Cockroach-32                        58.0 ± 0%      58.0 ± 0%     ~     (all samples are equal)
Select2_Cockroach-32                       1.20k ± 0%     1.19k ± 0%   -0.72%          (p=0.000 n=5+4)
Select3_Cockroach-32                       2.06k ± 0%     2.05k ± 0%     ~             (p=0.079 n=4+5)
Insert1_Cockroach-32                         300 ± 0%       300 ± 0%     ~     (all samples are equal)
Insert10_Cockroach-32                        508 ± 0%       508 ± 0%     ~     (all samples are equal)
Insert100_Cockroach-32                     2.35k ± 0%     2.35k ± 0%     ~             (p=1.000 n=5+5)
Insert1000_Cockroach-32                    20.5k ± 0%     20.5k ± 0%     ~             (p=0.524 n=5+5)
Update1_Cockroach-32                         575 ± 0%       580 ± 0%   +0.87%          (p=0.008 n=5+5)
Update10_Cockroach-32                        887 ± 0%       884 ± 0%     ~             (p=0.079 n=4+5)
Update100_Cockroach-32                     3.68k ± 0%     3.59k ± 0%   -2.43%          (p=0.000 n=5+4)
Update1000_Cockroach-32                    29.7k ± 0%     28.8k ± 0%   -2.88%          (p=0.029 n=4+4)
Upsert1_Cockroach-32                       1.15k ± 0%     1.12k ± 0%   -2.79%          (p=0.008 n=5+5)
Upsert10_Cockroach-32                      1.54k ± 0%     1.40k ± 0%   -9.36%          (p=0.008 n=5+5)
Upsert100_Cockroach-32                     5.70k ± 0%     4.36k ± 0%  -23.46%          (p=0.008 n=5+5)
Upsert1000_Cockroach-32                    46.8k ± 0%     33.4k ± 0%  -28.55%          (p=0.008 n=5+5)
Delete1_Cockroach-32                         479 ± 0%       466 ± 0%   -2.71%          (p=0.029 n=4+4)
Delete10_Cockroach-32                        684 ± 0%       591 ± 0%  -13.71%          (p=0.008 n=5+5)
Delete100_Cockroach-32                     2.60k ± 0%     1.69k ± 0%  -34.87%          (p=0.008 n=5+5)
Delete1000_Cockroach-32                    21.6k ± 0%     12.6k ± 0%  -41.81%          (p=0.016 n=4+5)
Scan1_Cockroach-32                           200 ± 0%       200 ± 0%     ~     (all samples are equal)
Scan10_Cockroach-32                          227 ± 0%       227 ± 0%     ~     (all samples are equal)
Scan100_Cockroach-32                         425 ± 0%       425 ± 0%     ~     (all samples are equal)
Scan1000_Cockroach-32                      2.31k ± 0%     2.31k ± 0%     ~             (p=0.873 n=5+5)
Scan10000_Cockroach-32                     21.2k ± 0%     21.2k ± 0%     ~             (p=1.000 n=5+5)
Scan1000Limit1_Cockroach-32                  207 ± 0%       207 ± 0%     ~     (all samples are equal)
Scan1000Limit10_Cockroach-32                 233 ± 0%       233 ± 0%     ~     (all samples are equal)
Scan1000Limit100_Cockroach-32                430 ± 0%       430 ± 0%     ~     (all samples are equal)
Scan10000FilterLimit1_Cockroach-32           509 ± 0%       509 ± 0%     ~     (all samples are equal)
Scan10000FilterLimit10_Cockroach-32          563 ± 0%       563 ± 0%     ~     (all samples are equal)
Scan10000FilterLimit50_Cockroach-32        1.80k ± 0%     1.80k ± 0%     ~             (p=0.167 n=5+5)
Sort100000Limit10_Cockroach-32             75.1k ± 0%     60.3k ± 0%  -19.74%          (p=0.029 n=4+4)
Sort100000Limit10Distinct_Cockroach-32      135k ± 0%      120k ± 0%  -10.93%          (p=0.008 n=5+5)
TrackChoices1_Cockroach-32                   397 ± 0%       387 ± 0%   -2.52%          (p=0.008 n=5+5)
TrackChoices10_Cockroach-32                  117 ± 0%       107 ± 0%   -8.55%          (p=0.008 n=5+5)
TrackChoices100_Cockroach-32                86.0 ± 0%      77.0 ± 0%  -10.47%          (p=0.000 n=5+4)
TrackChoices1000_Cockroach-32               83.0 ± 0%      73.0 ± 0%     ~             (p=0.079 n=4+5)
InsertDistinct1_Cockroach-32               1.90k ± 0%     1.90k ± 0%     ~             (p=0.079 n=5+5)
InsertDistinct10_Cockroach-32              1.97k ± 0%     2.06k ± 0%   +4.62%          (p=0.016 n=5+4)
InsertDistinct100_Cockroach-32             3.32k ± 0%     3.90k ±22%  +17.51%          (p=0.032 n=5+5)
WideTable1_Cockroach-32                    1.96k ± 0%     1.96k ± 0%   +0.41%          (p=0.016 n=5+4)
WideTable10_Cockroach-32                   4.01k ± 0%     4.02k ± 0%   +0.27%          (p=0.008 n=5+5)
WideTable100_Cockroach-32                  24.0k ± 0%     24.0k ± 0%   +0.13%          (p=0.008 n=5+5)
WideTable1000_Cockroach-32                  223k ± 0%      224k ± 0%     ~             (p=0.690 n=5+5)
PgbenchQuery_Cockroach-32                  2.89k ± 0%     2.85k ± 0%   -1.28%          (p=0.029 n=4+4)
ParallelPgbenchQuery_Cockroach-32          13.9k ± 4%     13.8k ± 7%     ~             (p=0.841 n=5+5)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7623)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice!

Do you know where the InsertDistinct100 slowdown comes from? Is it that we were able to do a CPut before and now we first need to do a Get?

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/testdata/select_non_covering_index, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-KM6AOdqAjpaoa-tY8JW:-KM6AOdqAjpaoa-tY8JX:138703401) ([raw file](https://github.com/cockroachdb/cockroach/blob/053a360ca7a9acf6e743675cbb20fd6dec945e92/sql/testdata/select_non_covering_index#L25)):*
> ```
> ----
> 0  /t/b/2/1            NULL    PARTIAL
> 0  /t/primary/1/b/c/d  /2/3/4  ROW
> ```

Regarding these testcases which aren't specific to families - it's not reasonable to have to update them any time we change the heuristics. We should instead update the "create table" statements in these tests to explicitly set one family per column.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KM6ABCxYQFPUtzYPz3h:-2122419235)*

**Comment by tschottdorf** [comment]
Also interested in `InsertDistinct`. It doesn't do anything but insert batches of (out-of-order) rows in a simple table with only a three-element composite primary key.

**Comment by paperstreet** [comment]
Happily, `INSERT` still doesn't require a get. The Insert benchmark is unchanged, which bears that out.

There's an allocation uptick in InsertDistinct, which is probably the cause of the time slowdown. I could pprof it again and see if I can find where that's coming from, but I really can't imaging what's different

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KM6CyVr5X6O3naW0T2v:1393219958)*

**Comment by RaduBerinde** [comment]
+34.41% is significant so it would be good to investigate. Can be done later (doesn't need to hold up this PR) but in that case please file an issue.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KM6P4ferq0VCZ7OnzCA:1425955764)*

**Comment by paperstreet** [comment]
This got really bizarre. When I run only the InsertDistinct benchmark (either on my laptop or gcloud), there is no change. I've done this several times. When I run the 15 minute big suite of sql benchmarks, it repros. Some sort of benchmark bleeding?

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/testdata/select_non_covering_index, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-KM6AOdqAjpaoa-tY8JW:-KM6Es_K341_rvc7ItrV:-2033325122) ([raw file](https://github.com/cockroachdb/cockroach/blob/053a360ca7a9acf6e743675cbb20fd6dec945e92/sql/testdata/select_non_covering_index#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Regarding these testcases which aren't specific to families - it's not reasonable to have to update them any time we change the heuristics. We should instead update the "create table" statements in these tests to explicitly set one family per column.
</details>
Done, though I left table and alter_table since I'd like to see those changes. This also surfaced the inability to force a new family with ALTER TABLE ADD, so I created an issue: https://github.com/cockroachdb/cockroach/issues/7697

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KMA5veSYYOaGnspDBTB:2105201239)*

**Comment by RaduBerinde** [comment]
... wow

I notice there is a lot of variation (±15%) - can you post all the results of `InsertDistinct100_Cockroach` in the raw output? I wonder if it's just a single run that's superslow

What variation do you get if run more iterations (say 100) of InsertDistinct100_Cockroach?

BTW are you using `test.count` or are you running `make bench` multiple times?

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KMA6x9-ni9SZPJnDeUR:1411502378)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KMAsTJJRuLJNh2UcN76:1417088721)*

**Comment by paperstreet** [comment]
Running the benchmark in a loop with count=1 instead of using count=5 seems to have cleared up the InsertDistinct benchmark. Updated the commit message with the new results

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7623#-:-KMB-kJzJZzUiYCfHL6-:-31564108)*

**Pull request merged**
