### PR TITLE
release-22.2: server,ui: add limit and sort to sql activity, split stmt and txns storage in redux

### PR DESCRIPTION
**Pull request by xinhaoz**
Backport 7/7 commits from #98815.
Backport 1/1 commits from #99712.

-----------------

See individual commits.

DB-Console (22.2): https://www.loom.com/share/d13568d08c0443d7a0e51f065f30bea4
DB-Console Details pages (22.2): https://www.loom.com/share/8f84030cf3904877b06a4b3d244b09f1

/cc @cockroachdb/release

Release justification: low-risk updates to existing functionality (code yellow fixes)

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
Great! There is one extra thing you will need to do because is a backport.
Imagine your changes go on 22.2.8, but as soon as a new cluster-ui version is created, it will use the new UI, so your current UI should work with all crdb versions < 22.2.8.
Take advantage that our staging cluster doesn't have your backend changes to test if is working. It will ignore your new parameter and return 20k results, so then you should extra the extra steps of checking (on the ui side), the amount of rows returned, if that is bigger than your request you know is using an older crdb version for the backend, so you should order the result by the column selected and filter our to return just the top X selected. This will have to be done on the frontend.

Make sure once this is merged, you update our staging cluster with the nightly image and test right away, so we can catch any issues before an actual release is created.

> Reviewed 3 of 3 files at r1, 22 of 22 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 20 of 20 files at r5, 12 of 12 files at r6, 24 of 24 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-:-NRJw8E-An98D6NbIvj9:b679o4s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.tsx` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-NRJvb4j4frz_pcJXgMz:-NRJvb4kBkFkzAbo-PVa:b-xy0axx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb8da783a79cb9f8ed50c77bcac42519d86e47e/pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.tsx#L24)):*
> ```XML
> 
> export function PageConfig(props: PageConfigProps): React.ReactElement {
>   const isCockroachCloud = useContext(CockroachCloudContext);
> ```

have you checked on Cloud? because this was added to change to a white background on cloud, which is grey in DB console

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.tsx` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-NRJvb4j4frz_pcJXgMz:-NRJyqmOE3u3McSeGMUF:b-bn418g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bb8da783a79cb9f8ed50c77bcac42519d86e47e/pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.tsx#L24)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

have you checked on Cloud? because this was added to change to a white background on cloud, which is grey in DB console
</blockquote></details>

Oops, this was deleted by accident during merge conflict resolution, I'll add it back.

**Review by xinhaoz — COMMENTED** [review]
Yeah I've already verified that on CC it does just throw away the new parms, returning the results as in the old version. Are we deciding to take this approach with mixed versions over just showing a message that the page will not be working as expected until upgrade is complete? Even if we do the sort and limit on the client side, it's still going to be using a subset of the data that may not contain all the queries they expected -- are we okay with that? Is there a way to determine if an upgrade is ongoing on the CC side -- maybe we can hide the limit and sort knobs until it's finalized.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-:-NRJyuvY-Uvz4hXxhDZn:bq3xcio)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
I'm not even talking about mixed version. Someone could be on 22.2.0 and never upgrade, but they will see this new UI. So what we should do on that case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-:-NRK2UNb8saFgI2VHMQu:b-41oo5w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by xinhaoz — COMMENTED** [review]
Ah right, I forgot it'll just pick up the latest cluster-ui anyways. Sounds good, I can check in the request response directly and do the sort/limit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-:-NRKA4w_7yyOgSeDR7Co:b-jcahh2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts` line 214 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-NS72f3E2hvTs_ftrYuK:-NS72f3E2hvTs_ftrYuL:bxz6w9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a67ed4e36edee2c6d13788b46c8df25187629b/pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts#L214)):*
> ```XML
> 
>   // Filter out stmts not belonging to txns response.
>   res.statements = res.statements.filter(stmt =>
> ```

at the beginning of this function you did `res.statements = [];` so you won't have anything to filter out here



_Code quote:_
```XML
res.statements = [];
```

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts` line 214 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-NS72f3E2hvTs_ftrYuK:-NS7IIRfE9GLUIwpF4PZ:b-462rp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/42a67ed4e36edee2c6d13788b46c8df25187629b/pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts#L214)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

at the beginning of this function you did `res.statements = [];` so you won't have anything to filter out here
</blockquote></details>

Ah nice catch. Fixed and added more tests to verify this part of the behaviour.

**Review by maryliag — APPROVED** [review]
Awesome work!
:lgtm: 

> Reviewed 7 of 34 files at r13, 23 of 24 files at r14, 5 of 5 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99403#-:-NSfSO96EhjGCk2wmbK2:b97t7nc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Pull request merged**
