### PR TITLE
security: clear client cert expiration cache on SIGHUP

### LINKED ISSUE #110493: Ability to flush `security_certificate_expiration_client` metric cache without restarting nodes
**Is your feature request related to a problem? Please describe.**
When using the `security_certificate_expiration_client` metric and the certificate id is rotated, the old cert is cached. This results in the `min()` expiry alert being triggered even though the old cert is no longer being used. 

**Describe the solution you'd like**
The operator would like a way to flush the cache so that it can start fresh with new certificates going forward. This would also allow verification that the certificate rotation was successful.

**Describe alternatives you've considered**
Currently, the only way to flush the cache is to restart nodes, which is disruptive to high-traffic clusters.

Jira issue: CRDB-31459
Epic: CRDB-28893

### PR DESCRIPTION
**Pull request by rafiss**
Fixes #110493.
Epic: CRDB-28893

Release note (security update): The SIGHUP signal will now clear the
cached expiration times for client certificates that are reported by
the security.certificate.expiration.client metric. (The SIGHUP signal also
will still cause the server to reload certificates from the filesystem, as
it did before.)

### CODE REVIEW

**Review by knz — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/security/certificate_manager.go` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeOWZxF9eOEjZnyHbOI:-NeOWZxF9eOEjZnyHbOJ:bch8wd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1766112006fd69f23962f0e44124fdb31e94c8f/pkg/security/certificate_manager.go#L179)):*
> ```Go
> 					log.StructuredEvent(ctx, &eventpb.CertsReload{Success: true})
> 				}
> 				cm.clientCertExpirationCache.Clear()
> ```

I'd recommend pulling this up, above the call to `LoadCertificates`, such that the structured logging message is still guaranteed to be emitted after the reload (and now, flush) completes.

**Comment by knz** [comment]
this would also benefit from a test, you can see TestRotateCerts for an example.

**Review by rafiss — COMMENTED** [review]
thanks for the pointer to the test!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-:-NeRulGz39754Of2i1-i:bpialjq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/security/certificate_manager.go` line 179 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeOWZxF9eOEjZnyHbOI:-NeOswch4GDAOAVBpUwN:b7anmnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1766112006fd69f23962f0e44124fdb31e94c8f/pkg/security/certificate_manager.go#L179)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'd recommend pulling this up, above the call to `LoadCertificates`, such that the structured logging message is still guaranteed to be emitted after the reload (and now, flush) completes.
</blockquote></details>

good call

**Review by knz — APPROVED** [review]
This works for me. Let's however check with @lancel66 whether the customer is OK with a flush of all the metrics at once (an alternative design, not considered here, was to provide a mechanism to flush the metric for just 1 SQL user).

> Reviewed 1 of 2 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-:-NeSzl0x4XdL619viATl:b-uzjzf7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-NeSz64xBmnshfsjNIn_:btxylbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
> ```Go
> 		OnEvictedEntry: func(entry *cache.Entry) {
> 			gauge := entry.Value.(*aggmetric.Gauge)
> 			gauge.Update(0)
> ```

Why was this needed?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @mgartner)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-NeceHJaDh0E5Hus4VUf:bpiywsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why was this needed?
</blockquote></details>

I noticed this comment on `Unlink`
```
// Unlink unlinks this child from the parent, i.e. the parent will no longer// track this child (i.e. won't generate labels for it, etc). However, the child  
// will continue to be functional and reference the parent, meaning updates to  
// it will be reflected in the aggregate stored in the parent.
```

so it seems more correct to reset the child gauge when unlinking.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-NeckTYN2BgUGEubsheV:b-3d4xjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

I noticed this comment on `Unlink`
```
// Unlink unlinks this child from the parent, i.e. the parent will no longer// track this child (i.e. won't generate labels for it, etc). However, the child  
// will continue to be functional and reference the parent, meaning updates to  
// it will be reflected in the aggregate stored in the parent.
```

so it seems more correct to reset the child gauge when unlinking.
</blockquote></details>

probably worth a comment.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @mgartner)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-Nekw8xy8hK1gc7Rn0ga:b5jh9m6) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

probably worth a comment.
</blockquote></details>

i've added one now

**Review by cameronnunez — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mgartner, and @rafiss)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-NenFrbo9yIEb84RaPym:bydccwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i've added one now
</blockquote></details>

the aggregate value stored in the parent is meaningless, so that's why it wasn't being reset when unlinked. but this change is harmless so up to you 
___
*[`pkg/security/certificate_manager.go` line 190 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NenGDY42mct8PrhZGRg:-NenGDY42mct8PrhZGRh:bhey9ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ca81daeec9c9533f1b724118d53b19738fb027/pkg/security/certificate_manager.go#L190)):*
> ```Go
> }
> 
> // MaybeUpsertClientExpiration updates the updates or inserts the expiration
> ```

nit: "updates" instead of "updates the updates"

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110726)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez, @knz, and @mgartner)

___
*[`pkg/security/cert_expiry_cache.go` line 91 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NeSz64xBmnshfsjNInZ:-NeoDIeA4nR-08kNdS9D:bfzaz2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/17e8e3caa92d100d735bb0e296c1a74cec96476a/pkg/security/cert_expiry_cache.go#L91)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

the aggregate value stored in the parent is meaningless, so that's why it wasn't being reset when unlinked. but this change is harmless so up to you
</blockquote></details>

i'll keep it since it's a good example to set for other usages
___
*[`pkg/security/certificate_manager.go` line 190 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110726#-NenGDY42mct8PrhZGRg:-NeoDHE59t_2gGuKeRvB:b-zd56p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ca81daeec9c9533f1b724118d53b19738fb027/pkg/security/certificate_manager.go#L190)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

nit: "updates" instead of "updates the updates"
</blockquote></details>

fixed, thanks!

**Comment by rafiss** [comment]
tftrs!

bors r+

**Pull request merged**
