### PR TITLE
cli/sql: Repace linenoise by chzyer/readline

### LINKED ISSUE #4398: Investigate using chzyer/readline instead of linenoise for sql cli
As suggested by @chzyer in https://github.com/cockroachdb/cockroach/pull/4209#issuecomment-184585579

### PR DESCRIPTION
**Pull request by guanqun**
fixes #4398 

The output seems OK:

```
root@:15432> set database=system;
OK
root@:15432> show
          -> tables;
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4438)

### CODE REVIEW

**Comment by guanqun** [comment]
I spent only a few minutes to hack this, @chzyer please help review. Thanks.

**Comment by knz** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl1pR8zmXu5Mm_6oqG:-KAl1pR8zmXu5Mm_6oqH:-584282075) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L95)):*
Can you clarify what happens if the history file cannot be read upon initializing readline?
We probably don't want this to prevent the user from using the sql client.

---

*[cli/sql.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl2ClkcQRtPPL8ddaw:-KAl2Cllw8DDhNF86S_p:1910744978) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L148)):*
Please include the comment "We save the history between each statement..."

Also here same question, what happens if readline cannot save the history?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by knz** [comment]
Also see the CI report, currently `make check` reports a failure.

**Comment by chzyer** [comment]
@knz, readline is not working well if Stdout is not a tty. I'm still working on that.

**Comment by guanqun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl1pR8zmXu5Mm_6oqG:-KAmgkq6sS8FPdhrx9hK:-589851882) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L95)):*
I tried that, no error will be returned, so this won't prevent the user from using sql client. You can call this a *feature* :D

---

*[cli/sql.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl2ClkcQRtPPL8ddaw:-KAmespvK9_ALJgGWTYZ:823362489) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L148)):*
Sure I'll add back the comment.

The `readline` library doesn't provide a return value for this operation. Maybe we should ask @chzyer to add that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by guanqun** [comment]
`make check` error is fixed.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-:-KAmjaif35KrBjeTVKnw:-1713956697)*

**Comment by chzyer** [comment]
@guanqun I have send a PR to you. Please check that.

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/sql.go, line 95 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl1pR8zmXu5Mm_6oqG:-KAnwzawkLuB2CfuLbM1:-582396477) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L95)):*
Ok that's good.

---

*[cli/sql.go, line 148 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAl2ClkcQRtPPL8ddaw:-KAnx9PNYTfhnVhbtmzy:-1632001379) ([raw file](https://github.com/cockroachdb/cockroach/blob/50496588afcbe5227d457379f72b8b17c3ed0d01/cli/sql.go#L148)):*
I think it's fine as is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by knz** [comment]
Ok waiting for the commit https://github.com/guanqun/cockroach/pull/1 before merging this one. Thanks

**Comment by guanqun** [comment]
@chzyer Can you sign the CLA?

**Comment by chzyer** [comment]
@guanqun Done!

**Comment by tamird** [comment]
Before we merge this, would you mind squashing down to one commit? Thanks for your work on this!

**Comment by chzyer** [comment]
@guanqun Please fixed my misspelling by the way. 😂

**Comment by guanqun** [comment]
Sure! In the process.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-:-KAosVpdpvGhGNp3LWdy:1800263664)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cli/sql.go, line 88 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotGucfKYUYL3qr67r:-KAotGucfKYUYL3qr67s:427474888) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L88)):*
Since this method doesn't even return an error, this comment should really be on the method upstream, not here.

---

*[cli/sql.go, line 136 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotQSoiSR91mb_evV1:-KAotQSoiSR91mb_evV2:-2032212453) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L136)):*
s/trying/try/

---

*[cli/sql.go, line 137 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotRmAT8rGW00L5M9S:-KAotRmAT8rGW00L5M9T:2117699806) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L137)):*
s/disk/disk /, s/is/was/

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAotO4kFQIjC7NNesWJ:1977216776) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
use `:=` here

Also, this seems worse than the old code - if there was some error opening the history file (i.e. disk is full), we won't see until we get to here, where the old code presumably reports that error at `SetHistoryPath`-time.

Finally, this is going to log an error every time it tries to save the history and fails? that seems worse as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by guanqun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cli/sql.go, line 137 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotRmAT8rGW00L5M9S:-KAowQngctQnBp-sFpTN:-1414862284) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L137)):*
These are from chzyer's commit. I'll fix these.

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAowXdpWkW1hOxuIo09:162374765) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
Let me take a look into this new API first.

---

*[cli/sql.go, line 103 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAow5TfdECPrgK7dJhH:-KAow5TgKkhsjLLeCAUg:-394308175) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64a714d92293533416aa2c2449f8d7da1b9a89a/cli/sql.go#L103)):*
@chzyer, I don't believe here is quite correct. If we use Ctrl+C, we just directly exit the sql client.

But ideally, it just cancels the current line, it should stay in the sql client.  Just like the original behaviour.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by chzyer** [comment]
*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAoyc9gXr7P2YL256O6:-1681930525) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
If we call `readline.SetHistoryPath("")`, AddHistory will not save to disk any more, but it still can hold in memory. If readline is not trying to save to disk, the err will always be nil.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by guanqun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cli/sql.go, line 88 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotGucfKYUYL3qr67r:-KAoxg450XLcx9mqtJxP:2005483474) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L88)):*
The comment will be removed.

---

*[cli/sql.go, line 103 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAow5TfdECPrgK7dJhH:-KAozGy3c3T9Kwa3GbGS:882022907) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64a714d92293533416aa2c2449f8d7da1b9a89a/cli/sql.go#L103)):*
Fixed, added a check for `ErrInterrupt`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by chzyer** [comment]
*[cli/sql.go, line 103 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAow5TfdECPrgK7dJhH:-KAp-4t_VkN221GxyWWX:-1768990902) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64a714d92293533416aa2c2449f8d7da1b9a89a/cli/sql.go#L103)):*
I'm not sure for that.  I just follow the origin logic .
```
if err == linenoise.KillSignalError {
	break
} else if err != nil {
	fmt.Fprintf(osStderr, "input error: %s", err)
	return err
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by guanqun** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAp-2zlZ0I_rZHtM49n:1986649206) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
So it looks we're OK for this one?

---

*[cli/sql.go, line 103 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAow5TfdECPrgK7dJhH:-KAp1JBWN4YDYBZhiN8k:1154681946) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64a714d92293533416aa2c2449f8d7da1b9a89a/cli/sql.go#L103)):*
Hmm, I'd personally prefer cancel the current line edit without leaving sql client. But anyway, I'll change to the original logic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAp2Zi0UCDHaZcFMq7b:40157335) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
Why are there no comments on `readline.SetHistoryPath`? I'm not thrilled about relying on undocumented behaviour.

Still, this is somewhat worse in that it reports the error after the first command, rather than at startup.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by chzyer** [comment]
*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAp44wHD63RZvAGFlu7:546917852) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
There is not everything can reports at startup. How about the disk is almost full and the error only can occurred after we wrote several historys?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by chzyer** [comment]
*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAp4ujw-RjUsxyl42Oz:-2079381415) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
BTW, sorry for the missing comments. I will add them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KAp7x5IPcXPhrezWHjV:1913868170) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
Sure, it's not possible to completely avoid errors from AddHistory, but it is possible to avoid _some_ errors, and that's worthwhile.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438)*

**Comment by knz** [comment]
LGTM.

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/sql.go, line 140 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-KAotO4kFQIjC7NNesWI:-KApRJDvfClnXHhODRYM:10269308) ([raw file](https://github.com/cockroachdb/cockroach/blob/38329a3f6ee7069e373bc31d9f96affbd28c0cdc/cli/sql.go#L140)):*
This handling is fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4438#-:-KApRNn7tLCdd5YeimN0:-492975211)*

**Comment by guanqun** [comment]
Thank you all!

**Pull request merged**
