### PR TITLE
pgcryptocipher: add helper function for parsing cipher method

### PR DESCRIPTION
**Pull request by andyyang890**
**pgcryptocipher: create new package for pgcrypto cipher functions**

This patch creates a new package that will contain the implementation
of pgcrypto cipher functions, along with related helpers.

Release note: None

----

**pgcryptocipher: add helper function for parsing cipher method**

This patch adds a helper function for parsing the cipher method string
passed to pgcrypto cipher functions.

Release note: None

----

Informs #21001

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
looks pretty good! just had small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-:-NYZnLxH0BPK5Fvjl8Vd:b1ec7y9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmZEf5-mkblGZCGnz:-NYZmZEf5-mkblGZCGo-:blpxfqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L58)):*
> ```Go
> 	switch algorithm := submatches[cipherMethodRE.SubexpIndex("algorithm")]; strings.ToLower(algorithm) {
> 	case "aes":
> 		ret.algorithm = aesCipher
> ```

can you add a case for "bf" and use an `unimplemented.NewWithIssue` error. (and let's make a single tracking issue for all the legacy/unsupported encryption algorithms)
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmPtM7BRewy1wRtFP:-NYZmPtM7BRewy1wRtFQ:b-wnfqyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L60)):*
> ```Go
> 		ret.algorithm = aesCipher
> 	default:
> 		return cipherMethod{}, errors.Newf(`cipher method has unsupported algorithm: "%s"`, algorithm)
> ```

for all of these non-unimplemented errors, let's use `pgerror.Newf` with a pgcode of `22023` (InvalidParameterValue), in order to match postgres.
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmv576OihkocPZNrw:-NYZmv576OihkocPZNrx:bmigzws) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L64)):*
> ```Go
> 
> 	switch mode := submatches[cipherMethodRE.SubexpIndex("mode")]; strings.ToLower(mode) {
> 	case "", "cbc":
> ```

similar to above, can you add a case for "ebc"
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/doc.go` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZk41yBXg5P5wWeTvM:-NYZk41yBXg5P5wWeTvN:b-lvz824) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc3feb4eb137d1aba97246ab50dedcd5bbdd174/pkg/sql/sem/builtins/pgcrypto/raw/doc.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> // Package raw contains the implementation of raw encryption functions.
> ```

i'm in favor of making a new package, but the one thing is i don't think it's clear what "raw encryption functions" means since that term comes from the Postgres docs

maybe we could use a name like `pgcryptoutil`, and have this package only contain the parsing+padding logic.

then we can move the `pgcrypto` business logic to `pkg/sql/sem/builtins/pgcrypto`. this could include things like `func crypt` and `func getHashFunc`

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/pgcrypto/raw/doc.go` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZk41yBXg5P5wWeTvM:-NYZpn8cBfH-emm92Zsj:b-p3ivt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc3feb4eb137d1aba97246ab50dedcd5bbdd174/pkg/sql/sem/builtins/pgcrypto/raw/doc.go#L11)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm in favor of making a new package, but the one thing is i don't think it's clear what "raw encryption functions" means since that term comes from the Postgres docs

maybe we could use a name like `pgcryptoutil`, and have this package only contain the parsing+padding logic.

then we can move the `pgcrypto` business logic to `pkg/sql/sem/builtins/pgcrypto`. this could include things like `func crypt` and `func getHashFunc`
</blockquote></details>

I was thinking we could have all the logic for the raw encryption functions in its own package and only expose the following two functions:
```
Encrypt(data []byte, key []byte, iv []byte, cipherType string) ([]byte, error)
Decrypt(data []byte, key []byte, iv []byte, cipherType string) ([]byte, error)
```

My thinking is that all these helper functions are only used for this specific use case so we can keep them unexported.

To address your point about `raw` being a Postgres-specific term, what if named the package `cipher`?

I was also thinking that the code for different areas of pgcrypto should each go in their own package in the `pgcrypto` directory instead of all going into one big `pgcrypto` package.

Thoughts?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/sem/builtins/pgcrypto/raw/doc.go` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZk41yBXg5P5wWeTvM:-NY_kJ4JEjk7HL9t8HVj:b-ncqsva) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc3feb4eb137d1aba97246ab50dedcd5bbdd174/pkg/sql/sem/builtins/pgcrypto/raw/doc.go#L11)):*
> My thinking is that all these helper functions are only used for this specific use case so we can keep them unexported.

you're right, that's a good reason. let's organize it how you were thinking

`cipher` is a better name. the one issue is that we generally try to make package names unique, and `cipher` collides with the package from the standard library: https://pkg.go.dev/crypto/cipher

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1849657053/Organization+of+code+into+packages#Where-to-create-new-packages-and-how-to-name-them

i think a name like `pgcryptocipher` might work. then the other packages you were alluding to could be `pgcryptohash` and `pgcryptorand`

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmZEf5-mkblGZCGnz:-NYe4YA8BqqbjHo0hWFA:b-aijh24) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L58)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add a case for "bf" and use an `unimplemented.NewWithIssue` error. (and let's make a single tracking issue for all the legacy/unsupported encryption algorithms)
</blockquote></details>

Done. Filed https://github.com/cockroachdb/cockroach/issues/105466
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 60 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmPtM7BRewy1wRtFP:-NYe4Xfq8n3EnwAbzvLm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L60)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for all of these non-unimplemented errors, let's use `pgerror.Newf` with a pgcode of `22023` (InvalidParameterValue), in order to match postgres.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go` line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZmv576OihkocPZNrw:-NYe4YW-Cia_TAVbyvbF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8cdf64047add6b3d30bbd5cb460e25d198a19b0/pkg/sql/sem/builtins/pgcrypto/raw/cipher_method.go#L64)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to above, can you add a case for "ebc"
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/pgcrypto/raw/doc.go` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-NYZk41yBXg5P5wWeTvM:-NYe4V740Mqg5KgBtRV7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc3feb4eb137d1aba97246ab50dedcd5bbdd174/pkg/sql/sem/builtins/pgcrypto/raw/doc.go#L11)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> My thinking is that all these helper functions are only used for this specific use case so we can keep them unexported.

you're right, that's a good reason. let's organize it how you were thinking

`cipher` is a better name. the one issue is that we generally try to make package names unique, and `cipher` collides with the package from the standard library: https://pkg.go.dev/crypto/cipher

see: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1849657053/Organization+of+code+into+packages#Where-to-create-new-packages-and-how-to-name-them

i think a name like `pgcryptocipher` might work. then the other packages you were alluding to could be `pgcryptohash` and `pgcryptorand`

</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105301#-:-NYsqVoD4EpQg91VQDbo:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
