### PR TITLE
sql: fix distsql planning issue with optimizer (streaming aggregation)

### PR DESCRIPTION
**Pull request by RaduBerinde**
The distsql planner looks at physical properties of various plan nodes
to figure out what orderings it needs to preserve when merging data
from multiple nodes. These are passed as required orderings in the
exec.Factory, but not for all operators - only those which would
actually matter.

There is a code path related to setting up streaming aggregations
which was unaccounted for which looks at the ordering of the input
node.

To fix this, we now pass required orderings to filters and
projections. I looked at all the operators and the rest either:
 - never produce an ordering as far as the optimizer is concerned
   (VirtualScan, HashJoin, ScalarGroupBy, SetOp, ProjectSet); or
 - they pass through the input ordering unchanged (Distinct); or
 - they cannot be distributed (Limit, Ordinality).

Release note (bug fix): Fixed an issue which causes invalid results or
an "incorrectly ordered stream" error with streaming aggregations (in
some cases).

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31825#-:-LPdWMrjBTRZkT-iskA7:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31825#-:-LPfXMUX5P-EAiJOPfIg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31825#-LPfURf87vLu44IwP33c:-LPfURf87vLu44IwP33d:b-cba4r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf5e6281b185f6ed3e3d8b15cec1322b452d021/pkg/sql/opt/exec/execbuilder/relational_builder.go#L98)):*
> ```Go
> }
> 
> // reqOrdering converts an OrderingChoice to a ColumnOrdering (according to the
> ```

reqOrdering -> sqlOrderingFromChoice

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31825#-:-LPfdd8U1bVpIixsw_46:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31825#-LPfURf87vLu44IwP33c:-LPfdcUGB47t9hCFfKxj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf5e6281b185f6ed3e3d8b15cec1322b452d021/pkg/sql/opt/exec/execbuilder/relational_builder.go#L98)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

reqOrdering -> sqlOrderingFromChoice
</blockquote></details>

Done.

**Pull request merged**
