### PR TITLE
sql: hide experimental_enable_hash_sharded_indexes cluster/session setting

### LINKED ISSUE #75442: Deprecate `experimental_enable_hash_sharded_indexes` session var and removing gates
As we fix all the known issues of hash sharded index implementation and ready for traffic, we need to deprecate the session setting and gates around it.

Epic CRDB-7363

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
closes #75442

Release note (sql change): The experimental_enable_hash_sharded_indexes
session variable has been removed, along with the corresponding cluster
setting. The functionality of being able to create hash sharded index
is enabled automatically. SQL statements refer to the setting will still
work but will have no effects.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:tada: :lgtm: 

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76937#-:-MwbkXq1-gzeq7biwDKF:b-3uzqpd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/vars.go, line 1575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76937#-MwbjxIo6f8rC0lVDyNj:-MwbjxIo6f8rC0lVDyNk:bcj0g1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f880a7761d2902b951b4aaa61cdb831402b8cbfe/pkg/sql/vars.go#L1575)):*
> ```Go
> 
> 	// CockroachDB extension.
> 	// This is only kept for backwards compatibility and no longer hash any effect.
> ```

AFAIK we remove old settings and let `SET` fail instead of making it a no-op. Is there a strong reason to differ from that behavior for this particular setting?

**Comment by mgartner** [comment]
nit: There's a "sessiong" typo in the commit message and PR title.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76937)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

___
*[pkg/sql/vars.go, line 1575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76937#-MwbjxIo6f8rC0lVDyNj:-Mwbm9hBBxWJOscu4cuC:b-ur5syq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f880a7761d2902b951b4aaa61cdb831402b8cbfe/pkg/sql/vars.go#L1575)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

AFAIK we remove old settings and let `SET` fail instead of making it a no-op. Is there a strong reason to differ from that behavior for this particular setting?
</blockquote></details>

We have one other setting like this (`enable_drop_enum_value`). I can see the desire to not cause problems for any customers who may have existing scripts that use them; on the other hand, I expect they'd be using the cluster setting, not the session variable.

If we do want to keep it, I would consider separating them out into a "retired variables" list (similar to retired cluster settings) rather than keeping them in this map.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76937)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @postamar)

___
*[pkg/sql/vars.go, line 1575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76937#-MwbjxIo6f8rC0lVDyNj:-Mwbr-h588eCh5Qafrsl:b-k4k8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f880a7761d2902b951b4aaa61cdb831402b8cbfe/pkg/sql/vars.go#L1575)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We have one other setting like this (`enable_drop_enum_value`). I can see the desire to not cause problems for any customers who may have existing scripts that use them; on the other hand, I expect they'd be using the cluster setting, not the session variable.

If we do want to keep it, I would consider separating them out into a "retired variables" list (similar to retired cluster settings) rather than keeping them in this map.
</blockquote></details>

oh, definitely not strong reason to keep it. I agree that removing this and let `SET` fail would be nice since it send out a strong message that CRDB is getting better :)
Will remove this.

**Comment by postamar** [comment]
Hooray, we're there! Congratulations to everyone involved.

**Comment by chengxiong-ruan** [comment]
TFTR!

**Pull request merged**
