### PR TITLE
raft: add replicas.leaders.not_fortified metric

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit adds the metric replicas.leaders.not_fortified which reports the number of leaders that think they are not fortified.

References: #132754

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134545)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @herkolategan, @iskettaneh, and @srosenberg)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWmXSWBE4POsG3KQQJ:-OBWmXSWBE4POsG3KQQK:b-lsr7id) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/replica_metrics.go#L135)):*
> ```Go
> 	desc                     *roachpb.RangeDescriptor
> 	raftStatus               *raft.SparseStatus
> 	leadSupportStatus        raft.LeadSupportStatus
> ```

If we're going to add LeadSupportStatus, should we just change `raftStatus` to be a full `raft.Status`?
___
*[`pkg/kv/kvserver/replica_metrics.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWmbm97zbQBTu__l-S:-OBWmbm97zbQBTu__l-T:b-li5650) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/replica_metrics.go#L191)):*
> ```Go
> 		leaderBehindCount = calcBehindCount(d.raftStatus, d.desc, d.vitalityMap)
> 		leaderPausedFollowerCount = int64(len(d.paused))
> 		leaderNotFortified = d.leadSupportStatus.LeadSupportUntil == (hlc.Timestamp{}) ||
> ```

Do we need the first part of this condition? Isn't the `.Less()` enough?
___
*[`pkg/kv/kvserver/metrics.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWm1kK8Qv3Ac0EKdRq:-OBWm1kK8Qv3Ac0EKdRr:b-h55tca) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/metrics.go#L93)):*
> ```Go
> 	}
> 	metaLeaderNotFortifiedCount = metric.Metadata{
> 		Name:        "raft.leader.not_fortified",
> ```

Should we adjust the name/description/measurement here to more closely mirror the `replicas.leaders_not_leaseholders` metric? If so, we can also move this up right below that metric.
___
*[`pkg/kv/kvserver/metrics.go` line 2598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWmGrN9OHpWD2EYgz1:-OBWmGrO9mjlerM1ul1x:b-sj9rr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/metrics.go#L2598)):*
> ```Go
> 	QuiescentCount                *metric.Gauge
> 	UninitializedCount            *metric.Gauge
> 	LeaderNotFortifiedCount       *metric.Gauge
> ```

Same note about mirroring the naming convention of `RaftLeaderNotLeaseHolderCount`.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134545)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @herkolategan, @nvanbenschoten, and @srosenberg)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWmXSWBE4POsG3KQQJ:-OBWtIks-S9CWSwgpgDl:b-5mib2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/replica_metrics.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're going to add LeadSupportStatus, should we just change `raftStatus` to be a full `raft.Status`?
</blockquote></details>

But that will make it copy the Config and Progress.Inflights unnecessarily, right?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-:-OBbREdK4BghPhdLQF6_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @herkolategan, @iskettaneh, and @srosenberg)

___
*[`pkg/kv/kvserver/replica_metrics.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134545#-OBWmXSWBE4POsG3KQQJ:-OBbR3xtCn7-wEr83NWQ:b8hw28z) ([raw file](https://github.com/cockroachdb/cockroach/blob/48254c04cf0c4110a3d1dab9200378b0a9df134b/pkg/kv/kvserver/replica_metrics.go#L135)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

But that will make it copy the Config and Progress.Inflights unnecessarily, right?
</blockquote></details>

Yes, that's true. I guess we can leave this as is for now to avoid the extra copies.

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Pull request merged**
