### PR TITLE
ui: Extract Sessions Page from DB Console

### LINKED ISSUE #57296: ui: Extract Sessions Page from DB Console
See this doc for details https://docs.google.com/document/d/1POnd0peq25-unOEtQ8lwjPeJET6lHEYhJ49ZQEfx3TI/edit#heading=h.7qmr2zgyor18

- [ ] Isolate CSS for Sessions Page into modules
- [ ] Move Sessions Page component into `admin-ui-component` repo
- [ ] Reimport Sessions Page into DB Console
- [ ] Clean up unused components and styles in DB Console after Sessions Page import
- [ ] Write new redux layer in `admin-ui-components`
- [ ] Integrate Sessions Page into CockroachCloud

### PR DESCRIPTION
**Pull request by vladlos**
reimport session page from ui repo

Resolves: #57296

Release note (ui): none

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58034#-:-MQrVb1q0iy-a2X4PkPR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by elkmaster** [comment]
https://github.com/cockroachdb/yarn-vendored/pull/52

**Pull request merged**
