### PR TITLE
sql: add zone partitions when using ADD COLUMN UNIQUE on RBR

### LINKED ISSUE #66637: sql: Missing zone config when adding unique timestamp column to REGIONAL BY ROW table
When adding a unique timestamp column to a REGIONAL BY ROW table, for some reason the zone configuration doesn't get created on the new index.  Repro via these steps (on cockroach demo --nodes 9)

```

demo@127.0.0.1:26257/movr> create database multi_region primary region "us-east1" regions "europe-west1", "us-west1";
CREATE DATABASE

Time: 15ms total (execution 14ms / network 0ms)

demo@127.0.0.1:26257/movr> use multi_region;
SET

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/multi_region> create table t2 (c1 int, c2 int, c3 int);
CREATE TABLE

Time: 5ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/multi_region> alter table t2 set locality regional by row;
NOTICE: LOCALITY changes will be finalized asynchronously; further schema changes on this table may be restricted until the job completes
ALTER TABLE SET LOCALITY

Time: 202ms total (execution 202ms / network 0ms)

demo@127.0.0.1:26257/multi_region> alter table t2 add column c5 timestamp not null unique;
ALTER TABLE

Time: 286ms total (execution 285ms / network 0ms)

demo@127.0.0.1:26257/multi_region> select crdb_internal.validate_multi_region_zone_configs();
ERROR: crdb_internal.validate_multi_region_zone_configs(): missing zone configuration for partition "us-west1" of t2@t2_c5_key
SQLSTATE: 42P17
```

### PR DESCRIPTION
**Pull request by otan**
Resolves #66637

Release note (bug fix): Fixed a bug where using ADD COLUMN UNIQUE
on REGIONAL BY ROW tables did not correctly add the zone configs
for the newly created column index.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: Just a few minor questions.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-:-Mcj-ndq0DjjPwMNsLLW:b-18uoi0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-Mciyoi00wpSF1Q6m-vk:-Mciyoi00wpSF1Q6m-vl:b-wds7xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/28830d6ed3eefc28471979ed5bea5022f2c1f8e9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L537)):*
> ```
> 
> statement ok
> SELECT crdb_internal.validate_multi_region_zone_configs()
> ```

Pretty painful that we had this test, just without the validate() call.  Does it make sense to perform this call internally, in all cases where we're modifying a MR table (not as part of this commit, ofc)
___
*[pkg/sql/add_column.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-Mcj-Ir-BrP2MWUKX1gz:-Mcj-Ir-BrP2MWUKX1h-:b5tmuuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/28830d6ed3eefc28471979ed5bea5022f2c1f8e9/pkg/sql/add_column.go#L167)):*
> ```Go
> 	}
> 
> 	// We need to allocate new IDs in case we need to configure their zone
> ```

Nit: Allocate new IDs for the new index?  Might help readers if we're more explicit here.

Also, is there a reason why we can't do this in the same `if idx != nil` block above?  Is there something that transpires in the interim that we require to be done before we can assign the zone configs?  Or, alternatively, can we move that block down here?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66656)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-Mciyoi00wpSF1Q6m-vk:-Mckv5p3AHUOQ6ylLC0a:b-ozswhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/28830d6ed3eefc28471979ed5bea5022f2c1f8e9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L537)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Pretty painful that we had this test, just without the validate() call.  Does it make sense to perform this call internally, in all cases where we're modifying a MR table (not as part of this commit, ofc)
</blockquote></details>

probably worthwhile, yes!
___
*[pkg/sql/add_column.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-Mcj-Ir-BrP2MWUKX1gz:-MckvOFN2KJGGeuKN23t:b-jj5xsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/28830d6ed3eefc28471979ed5bea5022f2c1f8e9/pkg/sql/add_column.go#L167)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Allocate new IDs for the new index?  Might help readers if we're more explicit here.

Also, is there a reason why we can't do this in the same `if idx != nil` block above?  Is there something that transpires in the interim that we require to be done before we can assign the zone configs?  Or, alternatively, can we move that block down here?
</blockquote></details>

We need the index ID and column ID and mutation written before allocation before we write the zone configs - otherwise things turn up unrecognised all over the place.
I've put a comment to that effect here.

**Review by ajstorm — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66656)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm and @otan)

___
*[pkg/sql/add_column.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66656#-MclJYVn8CXWWiXafsUi:-MclJYVn8CXWWiXafsUj:b-2ns778) ([raw file](https://github.com/cockroachdb/cockroach/blob/f93a29520fab40e1eaf5e93a7036a1dbd003995b/pkg/sql/add_column.go#L168)):*
> ```Go
> 
> 	// We need to allocate new IDs for the created columns and indexes
> 	// in case we need to configure their zone partitioning.
> ```

Nit: If this is really only needed for the zone configs, should we tuck it into the `idx != nil` branch below?  Also helps to lower the risk in backporting.

**Pull request merged**
