### PR TITLE
builtins: implement ST_Intersection and ST_Buffer for geography types

### LINKED ISSUE #48389: geo/geogfn: implement ST_Buffer({geography,float8,int4})
Implement `ST_Buffer` on arguments {geography,float8,int4}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

_Observers: Please react to this issue if you need this functionality._

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48529 for an example PR.

The following additional guidance has been issued on implementing this function:

Implement BestSRID, Transform and do!

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:28:55Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48390: geo/geogfn: implement ST_Buffer({geography,float8})
Implement `ST_Buffer` on arguments {geography,float8}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

_Observers: Please react to this issue if you need this functionality._

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48529 for an example PR.

The following additional guidance has been issued on implementing this function:

Implement BestSRID, Transform and do!

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:28:55Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48391: geo/geogfn: implement ST_Buffer({geography,float8,text})
Implement `ST_Buffer` on arguments {geography,float8,text}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Buffer.html).

_Observers: Please react to this issue if you need this functionality._

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48529 for an example PR.

The following additional guidance has been issued on implementing this function:

Implement BestSRID, Transform and do!

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:28:55Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48398: geo/geogfn: implement ST_Intersection({geography,geography})
Implement `ST_Intersection` on arguments {geography,geography}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Intersection.html).

_Observers: Please react to this issue if you need this functionality._

For Geography builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geogfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geogfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48529 for an example PR.

The following additional guidance has been issued on implementing this function:

Implement BestSRID, Transform and do!

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:28:55Z. Changes to titles, body and labels may be overwritten.</sub>

### LINKED ISSUE #48812: geo: implement ST_Intersection({text,text}) -> geometry
Implement `ST_Intersection` on arguments {text,text}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Intersection.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48441 for an example PR.

The following additional guidance has been issued on implementing this function:

cast to Geometry type, then use ST_Intersection implemention for Geometry

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-06-30T05:29:32Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
PostGIS uses _ST_BestSRID to approximate a geography as a geometry to
perform ST_Buffer and ST_Intersection. We're obliged to do the same -
comments are inline.

Resolves #48812
Resolves #48389
Resolves #48390
Resolves #48391
Resolves #48398

Release note (sql change): Implements the ST_Buffer and ST_Intersection
functions for Geography types.

Release note (sql change): Implement ST_Intersection for string types.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51537)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geogfn/best_projection.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDG_Mc294DQH-0pB_X5:-MDG_Mc294DQH-0pB_X6:b2lcogc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L31)):*
> ` if geography objects are within one half zone UTM but not same UTM will pick one of those`

I didn't understand this phrasing.
___
*[pkg/geo/geogfn/best_projection.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGZc7h7ks5Hou2DXY_:-MDGZc7h7ks5Hou2DXYa:b-4qo9gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L41)):*
> ```Go
> 
> 	// Check if these fit either the North Pole or South Pole areas.
> 	// If the center of each is greater than 70, and it is within 45 degrees, we can use
> ```

would be clearer as:
// If the center has latitude greater than 70 degrees, and length within 45 degrees, we can use ...

Are these 45 and 70 constants used to match the behavior of PostGIS or is there a deeper reason?
___
*[pkg/geo/geogfn/best_projection.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGbRty2d_yTDummBMZ:-MDGbRty2d_yTDummBM_:bemljtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L54)):*
> ```Go
> 	}
> 
> 	// Attempt to fit the geometries into one UTM zone, which is 6 degrees wide each.
> ```

How about:
// Each UTM zone is 6 degrees wide and distortion is low for geometries that fit within the zone. We use
// UTM if the width is lower than the UTM zone width, even though the geometry may span 2 zones -- using
// the geometry center to pick the UTM zone should result in most of the geometry being in the picked zone. 
___
*[pkg/geo/geogfn/best_projection.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGdGEI6GAq6S2mCF3E:-MDGdGEI6GAq6S2mCF3F:bu4x8bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L59)):*
> ```Go
> 		// Offset longitude -180 to 0 and divide by 6 to get the zone.
> 		// Note that we treat 180 degree longtitudes as offset 59.
> 		sridOffset := geopb.SRID(math.Min(math.Floor((center.Lng.Degrees()+180)/6), 59))
> ```

What about the exceptions https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Exceptions ?
___
*[pkg/geo/geogfn/best_projection.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGcbJQ2RucxRroogTD:-MDGcbJQ2RucxRroogTE:b-4nkbab) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L64)):*
> ```Go
> 			return getGeomProjection(32601 + sridOffset)
> 		}
> 		// Start at the south UTM SRID.
> ```

Hmm, so the geometry could span 4 zones. 
Though the purpose of the S and N zone distinction is unclear to me -- it doesn't seem to be motivated by distortion. Do you know why they are distinct?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGfexY1AXVLsKPpncm:-MDGfexY1AXVLsKPpncn:b-1uh0eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/sql/sem/builtins/geo_builtins.go#L342)):*
> ```Go
> 		return nil, err
> 	}
> 	return retransformedGeom.AsGeography()
> ```

naming nit: how about `inLatLonGeom, inProjectedGeom, outProjectedGeom, outLatLonGeom` instead of `geom, transformedGeom, appliedGeom, retransformedGeom`

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51537)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geogfn/best_projection.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDG_Mc294DQH-0pB_X5:-MDGlsjJ5p6PPjY4eeEH:b-zfzkxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ` if geography objects are within one half zone UTM but not same UTM will pick one of those`

I didn't understand this phrasing.


</blockquote></details>

Fixed it up.
___
*[pkg/geo/geogfn/best_projection.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGZc7h7ks5Hou2DXY_:-MDGoVYLE68M8qRh7htC:bc52m4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

would be clearer as:
// If the center has latitude greater than 70 degrees, and length within 45 degrees, we can use ...

Are these 45 and 70 constants used to match the behavior of PostGIS or is there a deeper reason?

</blockquote></details>

I was roughly following PostGIS, but also modified this logic such that 45 makes a lot more sense.
___
*[pkg/geo/geogfn/best_projection.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGbRty2d_yTDummBMZ:-MDGowNB4_X6OKRotzRU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L54)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about:
// Each UTM zone is 6 degrees wide and distortion is low for geometries that fit within the zone. We use
// UTM if the width is lower than the UTM zone width, even though the geometry may span 2 zones -- using
// the geometry center to pick the UTM zone should result in most of the geometry being in the picked zone. 
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/best_projection.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGdGEI6GAq6S2mCF3E:-MDGqOOZ3BMGz8SVqJsA:bnszbfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L59)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What about the exceptions https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Exceptions ?
</blockquote></details>

I don't think we care too much about it, so I've ignored it but added a comment.
___
*[pkg/geo/geogfn/best_projection.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGcbJQ2RucxRroogTD:-MDGp9oAE-GF2rIkHLjj:b-hkc60p) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/geo/geogfn/best_projection.go#L64)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Hmm, so the geometry could span 4 zones. 
Though the purpose of the S and N zone distinction is unclear to me -- it doesn't seem to be motivated by distortion. Do you know why they are distinct?
</blockquote></details>

Usage of false northings -- see http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/coordref/coordsys/projected/mapprojections.htm.
I'm not sure it makes a difference in practice though.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-:-MDHn-o53ImakJnJKBlm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geogfn/best_projection.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHk9pwCgn8rBhfOvhB:-MDHk9pwCgn8rBhfOvhC:b-pmf5dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L30)):*
> ```Go
> // The algorithm is described by ST_Buffer documentation:
> //   It first determines the best SRID that fits the bounding box of the 2
> //   geography objects ... if Geography objects span multiple zones, it will pick one
> ```

do you mean UTM zones? But the rest of the sentence talks about both UTM and LAEA. This would be easier to understand if the sentence didn't mix the two.
___
*[pkg/geo/geogfn/best_projection.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHkWdT3DoAd9TAcRqH:-MDHkWdT3DoAd9TAcRqI:b-1cvhnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L41)):*
> ```Go
> 
> 	// Check if these fit either the North Pole or South Pole areas.
> 	// If the center has latitude than 70 (an arbitrary polar threshold), and it is
> ```

... has latitude greater than 70 ...
___
*[pkg/geo/geogfn/best_projection.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHlRPWAEXlVfFw-h64:-MDHlRPWAEXlVfFw-h65:b-kosccv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L49)):*
> ```
> https://epsg.io/3574.
> ```
this says [-90, 0] for latitude and doesn't mention LAEA -- did you mean to add a different link? I couldn't find a "South Pole LAEA" -- perhaps it does not exist. Which is fine --  we can just say in a comment here that we reused the same idea as the northern hemisphere.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51537)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geogfn/best_projection.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHk9pwCgn8rBhfOvhB:-MDHw9uq7ggxGykqkfA6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L30)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do you mean UTM zones? But the rest of the sentence talks about both UTM and LAEA. This would be easier to understand if the sentence didn't mix the two.
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/best_projection.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHkWdT3DoAd9TAcRqH:-MDHwCj4ErLUa-J1FFMS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... has latitude greater than 70 ...
</blockquote></details>

Done.
___
*[pkg/geo/geogfn/best_projection.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDHlRPWAEXlVfFw-h64:-MDHwVp80ePCBZ3kCpSE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bdc1d09f48063674a3cf1c12dc50284d274b88ad/pkg/geo/geogfn/best_projection.go#L49)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> https://epsg.io/3574.
> ```
this says [-90, 0] for latitude and doesn't mention LAEA -- did you mean to add a different link? I couldn't find a "South Pole LAEA" -- perhaps it does not exist. Which is fine --  we can just say in a comment here that we reused the same idea as the northern hemisphere.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51537#-MDGfexY1AXVLsKPpncm:-MDHwWe51OTmpBnzhJl_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0052ff5ff07e9e10240979f7156fe1800defb6/pkg/sql/sem/builtins/geo_builtins.go#L342)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

naming nit: how about `inLatLonGeom, inProjectedGeom, outProjectedGeom, outLatLonGeom` instead of `geom, transformedGeom, appliedGeom, retransformedGeom`
</blockquote></details>

Done.

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
