### PR TITLE
storage: rename MVCCStats.{SeparatedIntentCount,IntentAge} to Lock{Count,Age}

### PR DESCRIPTION
**Pull request by nvb**
Informs #109645.

Simple rename of the fields. The new names incorporate the increased role that these fields will play with replicated locks.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
There appears to be a lot of follow-up work needed here. For example,`ComputeStats()` doesn't have any lock-specific handling, `MVCCStats.AvgLockAge()` uses `IntentCount` rather than `LockCount` to compute the average, and we don't track `LockBytes` at all. Is the intent (...) for this PR to simply rename the fields, and then follow up with a later PR that adjusts the code and stats with proper lock handling?

> Reviewed 1 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110590#-:-NebFoJP3lxG2_AuIZ6n:bj5jrhu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick)

**Comment by nvanbenschoten** [comment]
> Is the intent (...) for this PR to simply rename the fields, and then follow up with a later PR that adjusts the code and stats with proper lock handling?

Heh, yes, this is just the rename. It doesn't do any of the actual work to track replicated locks in the MVCCStats.

**Review by erikgrinaker — APPROVED** [review]
Rename seems fine. May want a release note for this (or the follow-up), since these fields are exposed in various public APIs (e.g. SHOW RANGES and HTTP APIs).

> Reviewed 2 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110590#-:-NegKhrC57n-cTqidZZ8:b-p6zwdy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick)

**Comment by nvanbenschoten** [comment]
> May want a release note for this (or the follow-up), since these fields are exposed in various public APIs (e.g. SHOW RANGES and HTTP APIs).

Good point. I've added a note to https://github.com/cockroachdb/cockroach/issues/109645 to include a release note in the larger commit.

TFTR!

bors r+

**Pull request merged**
