### PR TITLE
roachprod: show process exit status with monitor

### PR DESCRIPTION
**Pull request by erikgrinaker**
### roachprod: remove netcat references

`roachprod monitor` used to use `netcat` to wait for process
termination, but this was replaced by a `kill -0` loop back in #37390.
However, the code still contained code and comments related to netcat.

This patch removes the outdated `netcat` code and references.

Release note: None

### roachprod: show process exit status with monitor

This patch changes `roachprod monitor` to use `systemctl` to poll
process info on non-local clusters, and outputs the exit status for dead
nodes. On local clusters, it retains the old logic.

Release note: None

During the lifecycle of a cluster (`create`, `start`, `stop`) the output is:

```
$ roachprod monitor grinaker-mon
2: dead (exit status 0)
3: dead (exit status 0)
1: dead (exit status 0)
1: 9628
2: 9714
3: 9674
1: dead (exit status 137)
2: dead (exit status 137)
3: dead (exit status 137)
```

/cc @cockroachdb/test-eng

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thank you! Good after comments.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-:-Mc5xUYF-wB52zEPSgZp:b-pkd8ei)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5whn35oE_WLApDKF-:-Mc5whn35oE_WLApDKF0:be9u749) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L375)):*
> ```Go
> 	status=unknown
> {{- else }}
> 	pid=$(systemctl show cockroach --property MainPID --value)
> ```

it will always bug me that this is visible in the "outer" scope later but I guess that's just how this works.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5wyaeEelrEasljDm6:-Mc5wyaeEelrEasljDm7:b-qrlngz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L380)):*
> ```Go
> 
>   if [ "${pid}" != "${lastpid}" ]; then
>     if [ "${pid}" == 0 ]; then
> ```

Hmm, realizing now that `monitor` is a bit too forgiving. I think we want it to catch *all* node terminations. If a node rapidly cycles (i.e. pid changes from X to Y) we basically want to still say that it died.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5xIFJE2oJ9By3vN0S:-Mc5xIFJE2oJ9By3vN0T:b-uldgof) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L381)):*
> ```Go
>   if [ "${pid}" != "${lastpid}" ]; then
>     if [ "${pid}" == 0 ]; then
>       echo "dead (exit status ${status})"
> ```

you might need to change `roachtest.newMonitor` as well, it might string match on the output here and I don't know if it's doing it in a way that will work with this change. Probably best to test that too, though it will have to be manual :-/

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66414)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5whn35oE_WLApDKF-:-Mc8iluCEJ_roZyJk3YV:bir6btg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L375)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

it will always bug me that this is visible in the "outer" scope later but I guess that's just how this works.
</blockquote></details>

Not sure which outer scope you mean here. The global shell script scope? There are no scopes in shell, except for explicit local variables in functions, which seems unnecessary. I don't think it should have any practical impact in this case anyway -- not like it'll leak into any parent or child processes or anything.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5wyaeEelrEasljDm6:-Mc8gEz48IJdL5xYTlYY:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L380)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, realizing now that `monitor` is a bit too forgiving. I think we want it to catch *all* node terminations. If a node rapidly cycles (i.e. pid changes from X to Y) we basically want to still say that it died.
</blockquote></details>

Good point, fixed.
___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5xIFJE2oJ9By3vN0S:-Mc8iUX6-WvDYx6vUokM:b79l79s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L381)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

you might need to change `roachtest.newMonitor` as well, it might string match on the output here and I don't know if it's doing it in a way that will work with this change. Probably best to test that too, though it will have to be manual :-/
</blockquote></details>

It matches on `dead`:

https://github.com/cockroachdb/cockroach/blob/c6d85fe144974b18e430ddc596dd556358f687c6/pkg/cmd/roachprod/main.go#L1155

Tested it manually:

```
	cluster.go:1740,context.go:140,cluster.go:1729,test_runner.go:882: dead node detection: /home/erik/go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor grinaker-1623660519-01-n4cpu8 --oneshot --ignore-empty-nodes: exit status 1 3: 9199
		2: dead (exit status 137)
		4: skipped
		1: 9447
```

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66414)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5whn35oE_WLApDKF-:-Mc9Ayv0C3WXTU4qqa_T:b18wrw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L375)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Not sure which outer scope you mean here. The global shell script scope? There are no scopes in shell, except for explicit local variables in functions, which seems unnecessary. I don't think it should have any practical impact in this case anyway -- not like it'll leak into any parent or child processes or anything.
</blockquote></details>

Sorry, didn't want to make you wonder what to do with this comment. I was just venting, the absence of scopes in shell script always weirds me out.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66414)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-Mc5whn35oE_WLApDKF-:-Mc9EU8J24dS467I0VAd:b-h29pk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ef43c537bf97ab6f73652b9a53af90046090586/pkg/cmd/roachprod/install/cluster_synced.go#L375)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Sorry, didn't want to make you wonder what to do with this comment. I was just venting, the absence of scopes in shell script always weirds me out.
</blockquote></details>

No worries, was just curious if you maybe meant something else like the template scope.

**Comment by erikgrinaker** [comment]
bors r=tbg

TFTR!

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66414)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachprod/install/cluster_synced.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66414#-McM8K785eV5XYkxevxy:-McM8K785eV5XYkxevxz:b-ysc716) ([raw file](https://github.com/cockroachdb/cockroach/blob/23146edbf21762c4a2d794b956d1dc62d54e6bfc/pkg/cmd/roachprod/install/cluster_synced.go#L410)):*
> ```Go
> 				return
> 			}
> 			// Give the session a valid stdin pipe so that nc won't exit immediately.
> ```

Thanks for the first commit removing netcat crap! I was doing the same in #51298, but got stalled. Peter had some comments there (https://github.com/cockroachdb/cockroach/pull/51298#pullrequestreview-446806139) about how some comments about the handling of stdout should evolve; would you mind seeing if they make sense to you / if they're still applicable?

**Pull request merged**
