### PR TITLE
ui: add a retry delay to the cached data reducer

### LINKED ISSUE #8699: ui: when the ui is disconnected it makes a huge number of requests
When a request fails it's instantly retried. This means when we lose connection to the backend server we are constantly making requests that all fail to connect instantly.

After a failure, we need to add a pause before retrying to prevent this.

### PR DESCRIPTION
**Pull request by maxlang**
The then and catch callback order was also switched. If the catch
comes first, the then callback will always be triggered (like a
finally) but we only want to invalidate data if there was no
error.

Currently the retry delay is fixed at 1 second.

Fixes #8699

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8759)

### CODE REVIEW

**Comment by maxlang** [comment]
Without fix (note the huge number of requests):

screen shot 2016-08-23 at 3 12 04 am

With fix (after about a minute):

screen shot 2016-08-23 at 3 11 17 am

cc @tamird

**Comment by mrtracy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/redux/cachedDataReducer.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759#-KPsbhjfQblRoeM3WdTT:-KPsbhjfQblRoeM3WdTU:brba2e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1898661de941f1a2abab8c17aa9bb976d8d6a3/ui/app/redux/cachedDataReducer.ts#L67)):*
> ```XML
>     this.ERROR = `cockroachui/CachedDataReducer/${actionNamespace}/ERROR`;
>     this.INVALIDATE = `cockroachui/CachedDataReducer/${actionNamespace}/INVALIDATE`;
>     this.RETRY = `cockroachui/CachedDataReducer/${actionNamespace}/RETRY`;
> ```

I would just re-use INVALIDATE for this purpose.  It's exactly the same concept; "don't refresh this, it is current".

Maybe change the name of INVALIDATE if you think "Valid" implies a successful result, but I don't think it does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759)*

**Comment by tamird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/redux/cachedDataReducer.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759#-KPsbhjfQblRoeM3WdTT:-KPsczNXulT4uZvhWLNt:b-2m2lic) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1898661de941f1a2abab8c17aa9bb976d8d6a3/ui/app/redux/cachedDataReducer.ts#L67)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I would just re-use INVALIDATE for this purpose.  It's exactly the same concept; "don't refresh this, it is current".
> 
> Maybe change the name of INVALIDATE if you think "Valid" implies a successful result, but I don't think it does.
</details>
Also, it seems like you'd want to store the time of the next attempt rather than a boolean.

This hardcoded retry interval doesn't seem great to me, so I'd prefer something more robust go in its place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759)*

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/redux/cachedDataReducer.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759#-KPsbhjfQblRoeM3WdTT:-KPsckJbipNXz_TCZ8YH:b-vbjnij) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1898661de941f1a2abab8c17aa9bb976d8d6a3/ui/app/redux/cachedDataReducer.ts#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Also, it seems like you'd want to store the time of the next attempt rather than a boolean.
> 
> This hardcoded retry interval doesn't seem great to me, so I'd prefer something more robust go in its place.
</details>
@mrtracy Valid does imply that the result is current and successful. It's even used as part of a check in some places. We keep the stale data around so setting valid to true in reference to the error would break the current set of assumptions.

@tamrid I considered this but I don't see any benefit right now. I'd still just use the default for everything. Let's add this functionality if/when we need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759)*

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/redux/cachedDataReducer.ts, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759#-KPsbhjfQblRoeM3WdTT:-KPsflUc3iNwdwZJ3I1C:b-uehca2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea1898661de941f1a2abab8c17aa9bb976d8d6a3/ui/app/redux/cachedDataReducer.ts#L67)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> @mrtracy Valid does imply that the result is current and successful. It's even used as part of a check in some places. We keep the stale data around so setting valid to true in reference to the error would break the current set of assumptions.
> 
> @tamrid I considered this but I don't see any benefit right now. I'd still just use the default for everything. Let's add this functionality if/when we need it.
</details>
*@tamird

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8759)*

**Comment by mrtracy** [comment]
Did this get thrown into master directly?  Is there anything left to do here?

**Comment by maxlang** [comment]
I'm reworking this. It can be closed for now.

**Pull request closed without merging**
