### PR TITLE
obsservice: turn the ObsService into an OTLP server 

### PR DESCRIPTION
**Pull request by andreimatei**
This patch makes the Obs Service implement the OTLP Logs gRPC service.
This reverses the connection direction for exporting events out of CRDB:
now CRDB connects out to the Obs Service through a new --obsservice-addr
flag. The Obs Service gets a new `--otlp-addr` flag taking the
host:port on which to expose the service.

By using standard OTLP we can have the data flow through an
OpenTelemetry Collector before going to the Obs Service. This makes the
Obs Service topology more flexible (since we can rely on the collector
to be deployed widely and funnel the data), and gives the collector the
opportunity to tee the data to other destinations.

Release note: None
Epic: CRDB-23641

### CODE REVIEW

**Comment by andreimatei** [comment]
First commit is #93733

**Review by andreimatei — COMMENTED** [review]
> First commit is #93733

Now all commits are original.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-:-NMVJCddDLNn2m1TcVfo:b-f3g3ne)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @cucaroach, @dhartunian, @herkolategan, and @srosenberg)

___
*[`pkg/obsservice/obspb/update-opentelemetry-proto.sh` line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NMGLupr9KAI0szVuCwx-r3-85:-NMV8FPJ60_FmqCzSx4Z:b-nd7sd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3891d22921b110d1d0f00b063e99bb2e0cac944/pkg/obsservice/obspb/update-opentelemetry-proto.sh#L85)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

/ is perhaps not the best choice for sed separator here, I'd use |
</blockquote></details>

Ack, This change is in https://github.com/cockroachdb/cockroach/pull/93733, which merged. I'll probably leave it alone.

**Review by dhartunian — APPROVED** [review]
:lgtm: just some minor comments/nits. excited to see where this leads!

> Reviewed 6 of 27 files at r5, 9 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-:-NNCctIZAA5J1AQgCkyE:bui8lks)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, @andreimatei, and @cucaroach)

___
*[`pkg/base/test_server_args.go` line 170 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCWmu53LL01uFRRP5h:-NNCWmu53LL01uFRRP5i:b-8fwh5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/base/test_server_args.go#L170)):*
> ```Go
> 	// ObsServiceAddr is the address to which events will be exported over OTLP.
> 	// If empty, exporting events is inhibited.
> 	ObsServiceAddr string
> ```

Minor: I'm wondering if this should also be an OTLPSinkAddr or something. could encourage folks to integrate with their own infra. Either way, maybe best not to encourage that just yet.
___
*[`pkg/obs/event_exporter.go` line 251 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCayv-4e4F-jG5G7D0:-NNCayv-4e4F-jG5G7D1:bttt5vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obs/event_exporter.go#L251)):*
> ```Go
> 			select {
> 			case <-ctx.Done():
> 				//	// We'll return after flushing everything.
> ```

nit :extra //
___
*[`pkg/obsservice/obslib/ingest/ingest.go` line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCcXRo-fnT5qoZiqz_:-NNCcXRo-fnT5qoZiqza:b-qj8x11) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obsservice/obslib/ingest/ingest.go#L45)):*
> ```Go
> ) (*logspb.ExportLogsServiceResponse, error) {
> 	_ = persistEvents(ctx, request.ResourceLogs, e.db)
> 	return &logspb.ExportLogsServiceResponse{}, nil
> ```

why don't we care about the error here?
___
*[`pkg/server/tenant.go` line 1017 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCbw2kA_fedOinCRZ4:-NNCbw2kA_fedOinCRZ5:bud1fpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/server/tenant.go#L1017)):*
> ```Go
> 	remoteFlowRunner := flowinfra.NewRemoteFlowRunner(baseCfg.AmbientCtx, stopper, &remoteFlowRunnerAcc)
> 
> 	// Create the EventServer. It will be made operational later, after the
> ```

nit: update comment.
___
*[`pkg/sql/event_log.go` line 699 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCcDPj8RDWIGyZUpbJ:-NNCcDPj8RDWIGyZUpbK:b-l30r36) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/sql/event_log.go#L699)):*
> ```Go
> 		// others serialize their UUIDs, but I went with the network byte order.
> 		binary.BigEndian.PutUint64(traceID[:], uint64(sp.TraceID()))
> 		binary.BigEndian.PutUint64(spanID[:], uint64(sp.SpanID()))
> ```

does this change have impact on existing deployments? I guess these are random IDs anyway, but just want to check. I don't think we read these back anywhere.

**Review by abarganier — APPROVED** [review]
Very cool - :lgtm: modulo a couple minor nits. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-:-NNDqey90zxnG8s5SeKT:bcef07x)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aadityasondhi, @andreimatei, and @cucaroach)

___
*[`pkg/obs/event_exporter.go` line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNDooUv6nTJVkMMHz7E:-NNDooUv6nTJVkMMHz7F:bftvb1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obs/event_exporter.go#L276)):*
> ```Go
> 				s.buf.mu.sizeBytes -= sizeBytes
> 				msgSize += sizeBytes
> 				req.ResourceLogs[0].ScopeLogs = append(req.ResourceLogs[0].ScopeLogs,
> ```

nit: would it make sense to pre-allocate `ScopeLogs` to `len(s.buf.mu.events)`? 



_Code quote:_
```Go
.ScopeLogs
```
___
*[`pkg/obsservice/obslib/ingest/ingest.go` line 35 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNDpyXK2iB_-BJrCR4f:-NNDpyXLBGdG9D6-NJd9:b-k5f2ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obsservice/obslib/ingest/ingest.go#L35)):*
> ```Go
> 
> // SetDB sets the database connection that the ingester will use to persist the
> // events it receives. It needs to be called before Export().
> ```

nit: should we check the `e.db` is defined in `Export()` before calling `persistEvents()`? Seems like we might hit an NPE panic otherwise



_Code quote:_
```Go
It needs to be called before Export().
```

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95632)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aadityasondhi, @cucaroach, and @dhartunian)

___
*[`pkg/base/test_server_args.go` line 170 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCWmu53LL01uFRRP5h:-NNcccKB54Mc2QVJLaX5:b6l4pxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/base/test_server_args.go#L170)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Minor: I'm wondering if this should also be an OTLPSinkAddr or something. could encourage folks to integrate with their own infra. Either way, maybe best not to encourage that just yet.
</blockquote></details>

yeah... I figured that putting `ObsService` in these names is more suggestive about what this data is about.
If anything, I think the name of the flag that's externally visible is more debatable... But I dunno, I'd keep "obs service" for now at least.
___
*[`pkg/obs/event_exporter.go` line 251 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCayv-4e4F-jG5G7D0:-NNcddpb-3ndx6VtGKYs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obs/event_exporter.go#L251)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit :extra //
</blockquote></details>

done
___
*[`pkg/obs/event_exporter.go` line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNDooUv6nTJVkMMHz7E:-NNceNETE8GETqK70A9w:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obs/event_exporter.go#L276)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: would it make sense to pre-allocate `ScopeLogs` to `len(s.buf.mu.events)`? 
</blockquote></details>

done
___
*[`pkg/obsservice/obslib/ingest/ingest.go` line 35 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNDpyXK2iB_-BJrCR4f:-NNceqOjDV7L2NOrF2oC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obsservice/obslib/ingest/ingest.go#L35)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: should we check the `e.db` is defined in `Export()` before calling `persistEvents()`? Seems like we might hit an NPE panic otherwise
</blockquote></details>

done
___
*[`pkg/obsservice/obslib/ingest/ingest.go` line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCcXRo-fnT5qoZiqz_:-NNcf6LXCyDFm_eb84iH:b-cybkay) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/obsservice/obslib/ingest/ingest.go#L45)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why don't we care about the error here?
</blockquote></details>

added logging
As far as returning it, you're not really supposed to return errors from this API according to OTLP.
___
*[`pkg/server/tenant.go` line 1017 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCbw2kA_fedOinCRZ4:-NNcfnHi5U1vD1A7KVEm:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/server/tenant.go#L1017)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: update comment.
</blockquote></details>

done
___
*[`pkg/sql/event_log.go` line 699 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95632#-NNCcDPj8RDWIGyZUpbJ:-NNcgCHs47lRmlNxbfTr:by29c5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/047724d81793633d7fe1979e96deedf19fbead97/pkg/sql/event_log.go#L699)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

does this change have impact on existing deployments? I guess these are random IDs anyway, but just want to check. I don't think we read these back anywhere.
</blockquote></details>

Nobody cares about these so far.

**Pull request merged**
