### PR TITLE
kvserver: write ForceFlushIndex and integrate with RAC2

### LINKED ISSUE #135601: rac2: chronic send-queue in apply_to_all causes problems with splits, merges, and below-raft migrations
See the reproduction in unit tests in https://github.com/cockroachdb/cockroach/pull/135339 and discussion in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731949918262989 and https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731706469382499.

Since the `SplitTrigger` does not apply at the state machine on the replica with the send-queue, the timeout of 20s in `maybeDropMsgApp` where the store with the uninitialized RHS rejects MsgApps, eventually expires. The uninitialized replica returns a MsgAppResp, which triggers a snapshot to be sent to the replica. These snapshots cannot apply since they overlap with the unsplit range, and cause a `snapshot intersects existing range; initiated GC:` error. This is wasteful.

Both merge and below-raft migrations call `waitForApplication` which waits for all replicas to apply some command (`SubsumeRequest` and `MigrateRequest` respectively). These exceed the deadline when a replica has a chronic send-queue.

Some solutions involving force-flushing are discussed in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731949918262989.

Note that force-flushing should be ok for splits and merges since only a tiny subset of ranges on an overloaded store should get force-flushed. For a below-raft migration, force-flushing will affect all ranges, so there is a much higher probability of extreme overload. However, AFAIK, we have had only 3 below-raft migrations in history: truncatedAndRangeAppliedStateMigration, migration for separated intents, addRaftAppliedIndexTermMigration. The last one was in Feb 2022. So these are very rare. The rarity of such migrations suggests that perhaps we can get away with providing some instruction to cluster operators to take a look at cluster health and ensure empty send-queues before starting an upgrade that involves such a migration.

Jira issue: CRDB-44654

Epic CRDB-42900

### PR DESCRIPTION
**Pull request by sumeerbhola**
- ReplicatedEvalResult.DoTimelyApplicationToAllReplicas is added and set
  in splitTriggerHelper, MergeTrigger, Migrate, Subsume.
- The previous setting to true is gated on cluster version
  V25_1_AddRangeForceFlushKey.
- This causes ReplicaState.ForceFlushIndex to be set, and
  RangeForceFlushKey (a replicated range-id local key) to be written when
  applying the corresponding batch to the state machine. The index is set
  to the index of the entry being applied, and is monotonically
  increasing.
- replica_rac2.Processor and rac2.RangeController have
  existing ForceFlushIndexChangedLocked methods that are called whenever
  the Replica sees a change in the force-flush-index.

Fixes #135601

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
This is a small change. The first commit is from https://github.com/cockroachdb/cockroach/pull/136321

@kvoli There is no unit testing of whether the ForceFlushIndex is properly plumbed to the rangeController when updated, or when the Replica is initialized using a snapshot. Once your split/merge/migrate tests are merged, I think we can modify them to also introspect the state of `rangeController` to see that it has a ForceFlushIndex that is advancing. We could also create a new replica in one of those tests and check that the ForceFlushIndex in that replica is the same as the others. Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136330#-:-OCk7Asv-7Nr5xVgAch4:b-k4drb3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — COMMENTED** [review]
That SGTM. I think we'd want to cherry-pick those testing commits ontop of this branch in that case, as they will need to be updated (not just the testing files regenerated) to pass CI w/o this patch.

Or, were you thinking of early returning in them without failing and merging?

Either way, sgtm extending/re-using them for integration testing here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136330#-:-OD72B19-Ya-Jxqov_Ku:b-cz533r)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by kvoli** [comment]
Opened these drafts for the two tests rebased on of this branch:
- https://github.com/cockroachdb/cockroach/pull/136495
- https://github.com/cockroachdb/cockroach/pull/136496

**Review by sumeerbhola — COMMENTED** [review]
I was thinking we would
- merge this
- merge your two testing PRs
- extend those tests to look at ForceFlushIndex

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136330#-:-OD7htgz0neQPXnWwM9b:b-3ebcd7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

**Review by kvoli — APPROVED** [review]
> I was thinking we would
> 
> -   merge this
> -   merge your two testing PRs
> -   extend those tests to look at ForceFlushIndex

Ack, SGTM.


:lgtm: -- see nit about comment.

> Reviewed 7 of 7 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136330#-:-OD7o-oVAy9mlpb_8Uwm:bcw0h87)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_application_result.go` line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136330#-OD7odsm68IesxjpFTdC:-OD7odsm68IesxjpFTdD:bqa0xjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/772624a17848d945d3a030d9ed52fe91bfdc5b41/pkg/kv/kvserver/replica_application_result.go#L61)):*
> ```Go
> 	// Rangefeeds have been disconnected prior to application.
> 	r.MVCCHistoryMutation = nil
> 	r.DoTimelyApplicationToAllReplicas = false
> ```

nit: similar to the draft, I think we need a comment here explaining why we don't set this to true. I might have missed that comment if it was moved somewhere else, if so ignore this suggestion.

**Comment by sumeerbhola** [comment]
> nit: similar to the draft, I think we need a comment here explaining why we don't set this to true. I might have missed that comment if it was moved somewhere else, if so ignore this suggestion.

Added a comment
```
	// See detailed comment in ReplicatedEvalResult.IsTrivial on why
	// DoTimelyApplicationToAllReplicas is trivial. It has been consumed in
	// apply.Batch.Stage.
```

**Comment by sumeerbhola** [comment]
There are some flakes https://teamcity.cockroachdb.com/viewLog.html?buildId=18004676&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_Testrace
The `TestFlowControlCrashedNodeV2/v2_enabled_when_leader_level=2/kvadmission.flow_control.mode=apply_to_elastic` seems to be flaking every few days https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_Tests&testNameId=7218178376158913265&tab=testDetails

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
