### PR TITLE
sql: add support for enum array builtins

### PR DESCRIPTION
**Pull request by rafiss**
Release note (sql change): Array builtin functions can now be used with
arrays of enums.

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
ah yikes
```
a panic has occurred!
 +use of enum metadata before hydration as an enum

Wraps: (2) while executing: SELECT array_cat(ARRAY[_, _], ARRAY[_]) FROM _
```

```
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432  a panic has occurred!
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +use of enum metadata before hydration as an enum
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +(1) attached stack trace
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  -- stack trace:
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:660
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | runtime.gopanic
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/usr/local/go/src/runtime/panic.go:965
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Wait
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:469
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | runtime.gopanic
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/usr/local/go/src/runtime/panic.go:965
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).ensureHydratedEnum
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2439
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:2404
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4380
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.DecodeTableKey
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/column_type_encoding.go:442
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.decodeArrayKey
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/column_type_encoding.go:1145
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.DecodeTableKey
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/column_type_encoding.go:226
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.(*EncDatum).EnsureDecoded
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:234
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:978
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*copyingRowReceiver).Push
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:454
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:189
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:732
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:438
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:535
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1276
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1398
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1075
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:713
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1719
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1721
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1643
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:662
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:639
E211013 20:18:57.764299 7502892 1@util/log/logcrash/crash_reporting.go:140 â‹® [n1,client=â€¹127.0.0.1:54576â€º,hostssl,user=root] 573432 +Wraps: (2) while executing: SELECT array_cat(ARRAY[_, _], ARRAY[_]) FROM _
```

**Comment by rafiss** [comment]
I guess I can just ban these builtins from DistSQL, but just curious @yuzefovich is the above error surprising to you?

**Review by yuzefovich — COMMENTED** [review]
I'm not sure whether DistSQL-blocklisting these builtins will solve the error above, but if it does and you'll go this route, I'd leave a TODO to figure it out. My guess is that somewhere we're holding onto `*types.T` object and never call `DistSQLTypeResolved.HydrateTypeSlice`.

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71482#-:-Mlvl39m1s3kW5KLaxhJ:b-2d2i7h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by rafiss** [comment]
I see. I wonder if it's an issue with `HydrateTypeSlice` not handling the array type descriptor. There's nothing in its implementation that seems to care about `typedesc.GetUserDefinedArrayTypeDescID(...)` which I would guess might be needed.

```
// HydrateTypeSlice installs metadata into a slice of types.T's.
func (dt DistSQLTypeResolver) HydrateTypeSlice(ctx context.Context, typs []*types.T) error {
	for _, t := range typs {
		if t.UserDefined() {
			id, err := typedesc.GetUserDefinedTypeDescID(t)
			if err != nil {
				return err
			}
			name, desc, err := dt.GetTypeDescriptor(ctx, id)
			if err != nil {
				return err
			}
			if err := desc.HydrateTypeInfoWithName(ctx, t, &name, dt); err != nil {
				return err
			}
		}
	}
	return nil
}
```

**Comment by rafiss** [comment]
i changed `array_cat` to use a different ReturnTyper and that seems to have fixed it... see the latest revision

**Review by yuzefovich — COMMENTED** [review]
LGTM, but I'll defer to Oliver.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71482#-:-Mm-J_KHCjXNDgrZoFBt:b-mmu58q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request merged**
