### PR TITLE
opt: add ScanPrivate.IsUnfiltered() helper function

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds a new method to `ScanPrivate`, `IsUnfiltered`, which
returns true if the scan is guaranteed to produce all rows in the table.
It returns false if it may not return all rows because it has a limit,
it is constrained, or it scans a partial index.

This commit updates a few lines of code that were manually performing
these checks.

Related context: https://github.com/cockroachdb/cockroach/pull/49933#issuecomment-641668956

Release note: None

### CODE REVIEW

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/xform/coster.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0puLMCgt1gWtW4wL3:-MB0puLMCgt1gWtW4wL4:brkanh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/coster.go#L317)):*
> ```Go
> 	// estimate turns out to be smaller than the actual row count.
> 	var preferConstrainedScanCost memo.Cost
> 	if scan.IsUnfiltered(c.mem.Metadata()) {
> ```

By using `IsUnfiltered` here, a Scan with a limit is also exempt from receiving this slight cost increase. I don't think this is a big issue, because if the cost was equal for two plans, one with a Limit and one without, there shouldn't be any issue with preferring the limited Scan. But LMK if I'm wrong about this.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-:-MB0riFICDd1V3eW_wYN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/xform/coster.go, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0puLMCgt1gWtW4wL3:-MB0qgZZ2DPN5wmV68vO:b-aot0wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/coster.go#L317)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

By using `IsUnfiltered` here, a Scan with a limit is also exempt from receiving this slight cost increase. I don't think this is a big issue, because if the cost was equal for two plans, one with a Limit and one without, there shouldn't be any issue with preferring the limited Scan. But LMK if I'm wrong about this.
</blockquote></details>

Yeah this should be fine.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB0r9Ei-16do5bTfCOi:btbia6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
> ```Go
> 	scanPrivate *memo.ScanPrivate, required physical.OrderingChoice,
> ) bool {
> 	// Don't push a limit into the scan if the scan is already filtered by a
> ```

The comment is the opposite of what we're doing..

I think the old code is what we want here.. we'll want to allow pushing a limit into a constrained partial index scan.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @RaduBerinde)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB10NadEA1kcweSvXhH:b-gwnef5) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
Hmm looks like I got a bit confused here.

> I think the old code is what we want here.. we'll want to allow pushing a limit into a constrained partial index scan.

But we'll also want to allow pushing a limit into an unconstrained partial index scan, correct? In that case I think it'd look something like:

```
if scanPrivate.HardLimit != 0 {
    return false
}

if scanPrivate.IsUnfiltered {
    return false
}
```

Or maybe we should be pushing a limit into any non-limited, non-canonical scan? The comments mention `PushLimitIntoScan` (no longer a rule) pushing a limit into unconstrained scans. But `GenerateLimitedScans` only operates on canonical scans, not all unconstrained scans.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB1CXkh9YE54cFz5_A2:-MB1CXkh9YE54cFz5_A3:b-hksi7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1197)):*
> ```Go
> // satisfied by the Scan operator.
> //
> // NOTE: Limiting canonical scans is done by the GenerateLimitedScans rule,
> ```

I think this should still say "unconstrained scans"
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB1C5F_Dl3mUxN1PIBE:b-mdtyc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm looks like I got a bit confused here.

> I think the old code is what we want here.. we'll want to allow pushing a limit into a constrained partial index scan.

But we'll also want to allow pushing a limit into an unconstrained partial index scan, correct? In that case I think it'd look something like:

```
if scanPrivate.HardLimit != 0 {
    return false
}

if scanPrivate.IsUnfiltered {
    return false
}
```

Or maybe we should be pushing a limit into any non-limited, non-canonical scan? The comments mention `PushLimitIntoScan` (no longer a rule) pushing a limit into unconstrained scans. But `GenerateLimitedScans` only operates on canonical scans, not all unconstrained scans.
</blockquote></details>

This rule is specific to constrained scans. `GenerateLimitedScans` considers all indexes so it handles the unconstrained case.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB2-gJ59Qg0mQyYSSn6:bbnvwlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This rule is specific to constrained scans. `GenerateLimitedScans` considers all indexes so it handles the unconstrained case.
</blockquote></details>

Ahh, don't know how I missed that. However, `GenerateLimitedScans` cannot handle unconstrained partial index scans because it doesn't deal with any filters, and unconstrained partial index scans can only be generated when there is a filter.

I'll leave this unchanged in this PR for now. But I think there are two options for generating limited, unconstrained, partial index scans:

1) Add a new rule `GenerateLimitedPartialIndexScans` that matches a `(Limit (Select (Scan)))`.

2) Modify `PushLimitIntoConstrainedSan` to handle unconstrained partial index scans.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB4pDCkB1N6oGxc14ks:b-caezrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ahh, don't know how I missed that. However, `GenerateLimitedScans` cannot handle unconstrained partial index scans because it doesn't deal with any filters, and unconstrained partial index scans can only be generated when there is a filter.

I'll leave this unchanged in this PR for now. But I think there are two options for generating limited, unconstrained, partial index scans:

1) Add a new rule `GenerateLimitedPartialIndexScans` that matches a `(Limit (Select (Scan)))`.

2) Modify `PushLimitIntoConstrainedSan` to handle unconstrained partial index scans.
</blockquote></details>

I see. The reason why things are like this is that without `GenerateLimitedScans`, we may not create expressions for the relevant indexes in the first place (at least in the case where they require an index join). This is not a problem for partial index scans - they are created because we have a filter that matches the predicate. So I believe (2) would be the right thing.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50784)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB1CXkh9YE54cFz5_A2:-MB5uOOr28jfY7TaMMuW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think this should still say "unconstrained scans"
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50784#-MB0r9Ei-16do5bTfCOh:-MB5tx8d9MJv1OqTKODs:bm26x7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/215029dae07f42634730e5d46a86b5b808706eae/pkg/sql/opt/xform/custom_funcs.go#L1202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I see. The reason why things are like this is that without `GenerateLimitedScans`, we may not create expressions for the relevant indexes in the first place (at least in the case where they require an index join). This is not a problem for partial index scans - they are created because we have a filter that matches the predicate. So I believe (2) would be the right thing.
</blockquote></details>

Sounds good to me. I created an issue to track: https://github.com/cockroachdb/cockroach/issues/50828

**Comment by mgartner** [comment]
bors r=RaduBerinde

**Pull request merged**
