### PR TITLE
storage: allocate tmpdir under store path (and plumb it to ccl calls)

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14397)

### CODE REVIEW

**Comment by dt** [comment]
@danhhz so I did end up back to returning os.TempDir() here -- it cuts down on a some cruft/plumbing -- but (reading between the lines of your previously voiced concerns), I *think* the addition of `SetTempDir` and its usage in a test to prevent leaked files addresses the underlying issue better anyway?

**Comment by danhhz** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKJnMVDlg_GLkF4CZn:-KgKJnMVDlg_GLkF4CZo:b-rnpxus) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/ccl/sqlccl/backup_test.go#L146)):*
> ```Go
> 		}
> 		for _, leftover := range items {
> 			t.Fatalf("found %q remaining in tmpdir", leftover.Name())
> ```

t.Errorf so you can see them all

---

*[pkg/storage/store.go, line 4052 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKY6XI6p-PUd_-1LQX:-KgKY6XI6p-PUd_-1LQY:bboiw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/storage/store.go#L4052)):*
> ```Go
> func (s *Store) GetTempPrefix() (string, error) {
> 	path := s.engine.GetTempDir()
> 	return path, os.MkdirAll(path, 0755)
> ```

Create the temp dir when (*RocksDB).tempDir field is set (so in NewRocksDB and, with my other comment, in newMemRocksDB). then this doesn't return an error. (or call MkdirAll in a place I wouldn't expect)

---

*[pkg/storage/engine/rocksdb.go, line 1810 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKXhfzYHOEI1scxZZV:-KgKXhfzYHOEI1scxZZW:b-ekkx3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/storage/engine/rocksdb.go#L1810)):*
> ```Go
> 	// instances created via InMem, unless it is set explicitly via SetTempDir.
> 	if r.tempDir == "" {
> 		return os.TempDir()
> ```

this should be a bare return r.tempDir and newMemRocksDB should explictly set it to os.TempDir. that way it's much harder to accidentally end up using system temp in prod

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397)*

**Comment by dt** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup_test.go, line 146 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKJnMVDlg_GLkF4CZn:-KgKoh1MlMkLjolIHdNP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/ccl/sqlccl/backup_test.go#L146)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

t.Errorf so you can see them all
</blockquote></details>

Done.

---

*[pkg/storage/store.go, line 4052 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKY6XI6p-PUd_-1LQX:-KgKai3uEDxXt9pSI5NI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/storage/store.go#L4052)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Create the temp dir when (*RocksDB).tempDir field is set (so in NewRocksDB and, with my other comment, in newMemRocksDB). then this doesn't return an error. (or call MkdirAll in a place I wouldn't expect)
</blockquote></details>

Done.

---

*[pkg/storage/engine/rocksdb.go, line 1810 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgKXhfzYHOEI1scxZZV:-KgKa892sOLTEp9vTc1m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a432dc1a9f5a6a38a41e2330dbf5200c1095c48/pkg/storage/engine/rocksdb.go#L1810)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this should be a bare return r.tempDir and newMemRocksDB should explictly set it to os.TempDir. that way it's much harder to accidentally end up using system temp in prod
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/rocksdb.go, line 336 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgL-Fvxf2_XOkv9LicK:-KgL-Fvyg5y-Ru8jGjWy:bx7h0ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/4648641141cb38dcc4711deb26853cd78fa007e1/pkg/storage/engine/rocksdb.go#L336)):*
> ```Go
> 	}
> 
> 	if err := r.SetTempDir(tmp); err != nil {
> ```

a little strange that this is SetTempDir and newMemRocksDB just does it directly. probably fine to set it directly here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-:-KgL-Q6hqqkXBn2jynri:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/rocksdb.go, line 336 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgL-Fvxf2_XOkv9LicK:-KgL-mJm1RRBXO72cEd2:b-ng2tyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4648641141cb38dcc4711deb26853cd78fa007e1/pkg/storage/engine/rocksdb.go#L336)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

a little strange that this is SetTempDir and newMemRocksDB just does it directly. probably fine to set it directly here
</blockquote></details>

I used the setter for its mkdir call, whereas in InMem I was thinking I could get away without it (though I guess a mkdirAll on os.TempDir should be a noop in that case).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397)*

**Comment by dt** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/engine/rocksdb.go, line 336 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgL-Fvxf2_XOkv9LicK:-KgL2pw3U3pXvJbHK0LB:bi6yz0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4648641141cb38dcc4711deb26853cd78fa007e1/pkg/storage/engine/rocksdb.go#L336)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I used the setter for its mkdir call, whereas in InMem I was thinking I could get away without it (though I guess a mkdirAll on os.TempDir should be a noop in that case).
</blockquote></details>

Switched InMem to use the same setter, just for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397)*

**Comment by dt** [comment]
+cc @petermattis on the added fields and methods on the RocksDB wrapper.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/engine/engine.go, line 203 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgLOMh_HdcIstP24-fx:-KgLOMhaX_JVJ9bZ0YRt:b4u1ulc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b31dea292a7c17e7eb45562890b12ffd0fa5adc0/pkg/storage/engine/engine.go#L203)):*
> ```Go
> 	NewSnapshot() Reader
> 
> 	// GetTempDir returns a path under which tempdirs or tmpfiles can be created.
> ```

Let's use `temp` consistently. Do a pass through this PR for all uses of `tmp` (I saw a handful).

---

*[pkg/storage/engine/engine.go, line 204 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgLOh-zLRNMJLyb5_-y:-KgLOh-zLRNMJLyb5_-z:ba6yk7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b31dea292a7c17e7eb45562890b12ffd0fa5adc0/pkg/storage/engine/engine.go#L204)):*
> ```Go
> 
> 	// GetTempDir returns a path under which tempdirs or tmpfiles can be created.
> 	GetTempDir() string
> ```

The methods above were sorted lexicographically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-:-KgLOzNLVavmWcgwcPWr:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/storage/engine/engine.go, line 203 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgLOMh_HdcIstP24-fx:-KgLSxaj8mDKpaLJwdH9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b31dea292a7c17e7eb45562890b12ffd0fa5adc0/pkg/storage/engine/engine.go#L203)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's use `temp` consistently. Do a pass through this PR for all uses of `tmp` (I saw a handful).
</blockquote></details>

Done.

---

*[pkg/storage/engine/engine.go, line 204 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397#-KgLOh-zLRNMJLyb5_-y:-KgLSxCF9yYGZe1rZ92H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b31dea292a7c17e7eb45562890b12ffd0fa5adc0/pkg/storage/engine/engine.go#L204)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The methods above were sorted lexicographically.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14397)*

**Pull request merged**
