### PR TITLE
sqlcli,cdc: improve sinkless changefeed display in interactive sql shell

### PR DESCRIPTION
**Pull request by HonoreDB**
This commit improves the experience of someone
trying out CREATE CHANGEFEED or EXPERIMENTAL
CHANGEFEED in a cockroach sql terminal by
automatically turning off the table display
format (which prevents flushing) and setting
bytea_output=escape, as core changefeeds output
JSON as bytes datums, for the duration of the
changefeed query.

Changefeeds with sinks specified are not affected,
nor are cockroach sql invocations that don't
detectably output to a terminal.

Release note (cli change): Improved the output of sinkless changefeeds in the cockroach sql terminal.

Release justification: Prevents UX degradation in 22.2 as a side effect of fixing the bytea_output bug.

### CODE REVIEW

**Comment by ajwerner** [comment]
What about having the cli detect a sinkless changefeed statement and then switch the mode automatically?

**Comment by HonoreDB** [comment]
> What about having the cli detect a sinkless changefeed statement and then switch the mode automatically?

I do think that'd be reasonable but I like the idea of being backwards-compatible. Even gating behind `if c.sqlExecCtx.TerminalOutput` there are some use cases for table output (`WITH initial_scan='only'` flushes after the initial scan, keyboard interrupt flushes). The bytea_output part isn't a backwards compatibility issue but there are some people running changefeeds on protobufs who want to see the literal bytes.

Still, we could just add a setting to turn the automatic mode switching off. And maybe it'd be better to be parsing the statement to check if it's sinkless so that we can support changefeed syntax that doesn't work with `experimental changefeed` (e.g. I think changefeed expressions currently don't).

**Comment by ajwerner** [comment]
>WITH initial_scan='only' flushes after the initial scan, keyboard interrupt flushes

This is far-fetched and something we can freely change in a major version CLI release.

**Comment by HonoreDB** [comment]
Pushed a commit that detects a sinkless changefeed statement and switches the mode automatically.

**Review by rafiss — CHANGES_REQUESTED** [review]
i'd be in favor of just going with commit 2 (or i guess, squash these two together). i like the tests, but just had some questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-:-N9CntXtBv-N4Qsbeqy0:b-caum5m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`pkg/cli/clisqlshell/parser.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CmOlICvbfb22C5o6R:-N9CmOlICvbfb22C5o6S:be2dntn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L18)):*
> ```Go
> )
> 
> // We don't depend on tree in this package, but we do
> ```

i worry a bit about this being hard to maintain, since the CLI doesn't see much active development.

do you have thoughts on doing regexp matching instead? or do what we do for `COPY` and be a bit more naive?

https://github.com/cockroachdb/cockroach/blob/47dfddfa505a377d4efbaa91632d317d77e4d963/pkg/cli/clisqlshell/sql.go#L1794
___
*[`pkg/cli/clisqlshell/parser.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9Cm4jM2mGuT0mAZvcU:-N9Cm4jM2mGuT0mAZvcV:b-2mnt9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L35)):*
> ```Go
> // an undefined transition: the token is not in
> // transitions and defaultTransition is unset.
> type statementType struct {
> ```

is `statementType` the right name here? it seems like it's more like `tokenType`?
___
*[`pkg/cli/clisqlshell/sql.go` line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CkmHwBGb0L3dVNiXd:-N9CkmHwBGb0L3dVNiXe:b-23ze85) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/sql.go#L1172)):*
> ```Go
> 	// record values are output as bytea datums, and escaped output
> 	// is much more readable than the default hex.
> 	if prevByteaOutput == `hex` {
> ```

should this be `if prevByteaOutput != `escape`?

**Review by HonoreDB — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/cli/clisqlshell/parser.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CmOlICvbfb22C5o6R:-N9Dn4OQ8btTWtkxpqy8:b-lu1uut) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L18)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i worry a bit about this being hard to maintain, since the CLI doesn't see much active development.

do you have thoughts on doing regexp matching instead? or do what we do for `COPY` and be a bit more naive?

https://github.com/cockroachdb/cockroach/blob/47dfddfa505a377d4efbaa91632d317d77e4d963/pkg/cli/clisqlshell/sql.go#L1794
</blockquote></details>

I'm open to doing this more naively. The complexity mainly comes from checking whether there's an INTO clause; I don't want anyone to think their changefeed on TABLE tennis is fine, but a changefeed on table badminton hangs, and then be annoyed hours later to discover that the problem is that badminton contains "into". But false positives seem like they wouldn't be a big deal. I could change it to just always switch modes if the second lexical token is CHANGEFEED, and if you're creating a sinkful changefeed you'll get the job ID back in json form instead of table form, so it'll look like
```
{"job_id":"787032705335984129"}
```

instead of

```
        job_id
----------------------
  787032804510957569
```

What do you think?
___
*[`pkg/cli/clisqlshell/parser.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9Cm4jM2mGuT0mAZvcU:-N9Dr4uI3ZfNvoCE3UF0:b-pg0aso) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is `statementType` the right name here? it seems like it's more like `tokenType`?
</blockquote></details>

It's both, right now. If I'm not deleting this file entirely I'll make those distinct types.
___
*[`pkg/cli/clisqlshell/sql.go` line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CkmHwBGb0L3dVNiXd:-N9Dq9NF7_KwMJzFxL5U:b213qbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/sql.go#L1172)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be `if prevByteaOutput != `escape`?
</blockquote></details>

I think no? Right now it makes no difference since those are the only two possible values, but presumably if another value is added it won't be the default, and if you've explicitly set your bytea_output to something other than the default you know what you're doing and don't want it overridden/

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85181)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @rafiss)

___
*[`pkg/cli/clisqlshell/parser.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CmOlICvbfb22C5o6R:-NABgtDpDwI8T8Mp8xji:b8hza9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L18)):*
> I could change it to just always switch modes if the second lexical token is CHANGEFEED, and if you're creating a sinkful changefeed you'll get the job ID back in json form instead of table form

that seems fine to me. 
___
*[`pkg/cli/clisqlshell/sql.go` line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CkmHwBGb0L3dVNiXd:-NABj0HiDxT0fHMYl9Wn:bnfuayw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/sql.go#L1172)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I think no? Right now it makes no difference since those are the only two possible values, but presumably if another value is added it won't be the default, and if you've explicitly set your bytea_output to something other than the default you know what you're doing and don't want it overridden/
</blockquote></details>

i see, that sounds fine

**Review by HonoreDB — COMMENTED** [review]
Squashed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-:-NAQxsmP4TO7qZ00jzVb:b-un4k3m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/cli/clisqlshell/parser.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CmOlICvbfb22C5o6R:-NAQxxQj5ciTzEhuV0OJ:bwkozc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L18)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> I could change it to just always switch modes if the second lexical token is CHANGEFEED, and if you're creating a sinkful changefeed you'll get the job ID back in json form instead of table form

that seems fine to me. 
</blockquote></details>

Per offline discussion, keeping as-is with the promise that CDC team is on the hook for maintaining this.
___
*[`pkg/cli/clisqlshell/parser.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9Cm4jM2mGuT0mAZvcU:-NAQy69H99BgV6We6kNz:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/parser.go#L35)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

It's both, right now. If I'm not deleting this file entirely I'll make those distinct types.
</blockquote></details>

Fixed.
___
*[`pkg/cli/clisqlshell/sql.go` line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-N9CkmHwBGb0L3dVNiXd:-NAQyAqt--8YnEEQg1E5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee9ee1266b71588b275e22e8d7aab11b42d09e5/pkg/cli/clisqlshell/sql.go#L1172)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see, that sounds fine
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85181#-:-NAjKULm5KSJDwGYGm3h:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request merged**
