### PR TITLE
Metrics: refactor initialization and query

### PR DESCRIPTION
**Pull request by mberhault**
- change a bunch of major objects to return a metrics struct
- the registry is passed around less (still a bit, mainly in gossip)
- remove most `Get{Counter,Gauge,Rate}` methods, use actual metrics
  objects

I still need to figure out what to do with gossip. I has the one metric used by clients as well. More on that later.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8531)

### CODE REVIEW

**Comment by mrtracy** [comment]
Really like this refactoring, eliminating the passed-in registries and the Get methods are both big wins. LGTM, although (channeling Tamir here) the Metrics() methods may be able to return values instead of pointers; the individual metric objects are already pointers.  I'm not sure how that plays out with the reflection in AddMetricStruct, though.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-:-KPBhQKCPMUNsAr7Eb_0:b-3eefji)*

**Comment by tamird** [comment]
:heart_eyes: @mrtracy 

I left individual comments as a checklist, LGTM otherwise.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfNZ1fQI8kM-Hsf6Q:-KPDfNZ1fQI8kM-Hsf6R:b-tbobnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/kv/txn_coord_sender.go#L127)):*
> ```Go
> 
> // NewTxnMetrics returns a new instance of TxnMetrics that contains metrics.
> func NewTxnMetrics() *TxnMetrics {
> ```

this can return a value (and be named `make`)

---

*[rpc/clock_offset.go, line 53 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfXIsvTeRmBuDUbXa:-KPDfXIsvTeRmBuDUbXb:b4vv0sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/rpc/clock_offset.go#L53)):*
> ```Go
> 	}
> 
> 	metrics *RemoteClockMetrics
> ```

why a pointer? `Metrics()` should still return a pointer, but no reason to have a pointer in the struct.

---

*[sql/pgwire/server.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfmFY_S_zUnln59TY:-KPDfmFY_S_zUnln59TZ:b1diktn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/sql/pgwire/server.go#L69)):*
> ```Go
> 	executor *sql.Executor
> 
> 	metrics *ServerMetrics
> ```

ditto re pointer

---

*[sql/pgwire/v3.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfowf8xfuLKpbCzlJ:-KPDfowf8xfuLKpbCzlK:b-2guby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/sql/pgwire/v3.go#L124)):*
> ```Go
> 	doingExtendedQueryMessage, ignoreTillSync bool
> 
> 	metrics *ServerMetrics
> ```

same here

---

*[storage/reservation.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfuUyfPdUhAPZOQyK:-KPDfuUyfPdUhAPZOQyL:b-ejnhgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/reservation.go#L80)):*
> ```Go
> type bookie struct {
> 	clock              *hlc.Clock
> 	metrics            *StoreMetrics
> ```

this too

---

*[storage/store_metrics.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfySfYdDv7NEy_rAD:-KPDfySglgWMxH8-gI1F:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/store_metrics.go#L153)):*
> ```Go
> }
> 
> func newStoreMetrics() *StoreMetrics {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-:-KPDg-gnclVqLiXlN4nH:b-7ex48o)*

**Comment by mberhault** [comment]
@mrtracy you make a great @tamird impression.
All done.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfNZ1fQI8kM-Hsf6Q:-KPDn6ZsJtAzEhD5Pcrd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/kv/txn_coord_sender.go#L127)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this can return a value (and be named `make`)
</details>
Done.

---

*[rpc/clock_offset.go, line 53 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfXIsvTeRmBuDUbXa:-KPDnQrM07to5BLctbBa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/rpc/clock_offset.go#L53)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why a pointer? `Metrics()` should still return a pointer, but no reason to have a pointer in the struct.
</details>
Done.

---

*[sql/pgwire/server.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfmFY_S_zUnln59TY:-KPDnxF8wty2eSLHzJPr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/sql/pgwire/server.go#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto re pointer
</details>
Done.

---

*[sql/pgwire/v3.go, line 124 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfowf8xfuLKpbCzlJ:-KPDoAuPllCYn1t1WL7c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/sql/pgwire/v3.go#L124)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> same here
</details>
Done.

---

*[storage/reservation.go, line 80 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfuUyfPdUhAPZOQyK:-KPDo_cdtvW1eK5BMKas:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/reservation.go#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this too
</details>
Done.

---

*[storage/store_metrics.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfySfYdDv7NEy_rAD:-KPDo_LBR_pguXXJt72Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/store_metrics.go#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-:-KPDobGRmpi_fu35bBxB:b-6f7zrt)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[kv/txn_coord_sender.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfNZ1fQI8kM-Hsf6Q:-KPDrPDjNSc0-r3iHW59:b4t5lxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/kv/txn_coord_sender.go#L127)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> Done.
</details>
Rename plz.

---

*[sql/pgwire/server.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDrYVkaO7THMn1vzYd:-KPDrYVkaO7THMn1vzYe:bqrein5) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c67f85f279ca98cf994bc6ed7ce0727f8d4191/sql/pgwire/server.go#L84)):*
> ```Go
> }
> 
> func newServerMetrics() ServerMetrics {
> ```

rename plz

---

*[storage/store_metrics.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfySfYdDv7NEy_rAD:-KPDrfQ5SlPWes4IxK1w:bqrein5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/store_metrics.go#L153)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> Done.
</details>
rename plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-:-KPDriFn1FO-yPu7GFc6:bnfp4nl)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/server.go, line 168 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDs67Opci3dr7tYPoi:-KPDs67Opci3dr7tYPoj:bdfphyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c67f85f279ca98cf994bc6ed7ce0727f8d4191/server/server.go#L168)):*
> ```Go
> 	}, s.gossip)
> 	txnMetrics := kv.NewTxnMetrics()
> 	s.registry.AddMetricStruct(txnMetrics)
> ```

this almost certainly needs to change to `AddMetricStruct(sender.Metrics())` .

There may be other such subtle mistakes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531)*

**Comment by mberhault** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[kv/txn_coord_sender.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfNZ1fQI8kM-Hsf6Q:-KPDv4UznCGjBb1KZOz1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/kv/txn_coord_sender.go#L127)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Rename plz.
</details>
Done.

---

*[server/server.go, line 168 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDs67Opci3dr7tYPoi:-KPDszLOJdVgKXI0Vkik:b-apbquz) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c67f85f279ca98cf994bc6ed7ce0727f8d4191/server/server.go#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this almost certainly needs to change to `AddMetricStruct(sender.Metrics())` .
> 
> There may be other such subtle mistakes.
</details>
I intentionally made `AddMetricStruct` support both plain structs and pointers to structs. I verified that metrics are indeed being added properly, they are.

---

*[sql/pgwire/server.go, line 84 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDrYVkaO7THMn1vzYd:-KPDvDw-Ew7PngTAVWKG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c67f85f279ca98cf994bc6ed7ce0727f8d4191/sql/pgwire/server.go#L84)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> rename plz
</details>
Done.

---

*[storage/store_metrics.go, line 153 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDfySfYdDv7NEy_rAD:-KPDt6Q04ACEBiGG8cMC:bih704o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b408778bedd40f33ed0d3719a5fce86a90fbdac3/storage/store_metrics.go#L153)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> rename plz
</details>
I'm actually reverting this, we have a lock in StoreMetrics, we need a pointer for it. There's a todo there to remove it and the thing it protects. Will take a look later, there are other metrics to reorganize here and there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531)*

**Comment by mberhault** [comment]
I've added one last commit to remove the last uses of `Get{Gauge,Counter,Rate}` and unexport those methods (they're used in local tests). I may remove them entirely later.

**Comment by tamird** [comment]
Reviewed 12 of 12 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/server.go, line 168 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531#-KPDs67Opci3dr7tYPoi:-KPEdNwlWDWeJhUKWvRE:b-4fz835) ([raw file](https://github.com/cockroachdb/cockroach/blob/59c67f85f279ca98cf994bc6ed7ce0727f8d4191/server/server.go#L168)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> I intentionally made `AddMetricStruct` support both plain structs and pointers to structs. I verified that metrics are indeed being added properly, they are.
</details>
AddMetricStruct is going to end up grabbing references to this dead struct, not the *copy* of it which will live on in `sender`.  What am I missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8531)*

**Comment by mberhault** [comment]
`AddMetricStruct` reflects over the fields in the struct and adds the metrics themselves, not the struct

**Comment by tamird** [comment]
Right, but are those all references, or might they be values? Either way,
it is my opinion that only pointers to structs should be supported by
AddMetricStruct to avoid surprises.

**Comment by mberhault** [comment]
They're all references. The only way to be a value would be to bypass the constructors and manually construct a `metric.XX` object, which would definitely deviate from the pattern.

**Comment by tamird** [comment]
Seems needlessly subtle.

**Pull request merged**
