### PR TITLE
kvserver: reset tscache after merge to closed ts 

### PR DESCRIPTION
**Pull request by andreimatei**
This patch deals with what happens to the RHS's timestamp cache on a
merge. Before this patch, we were either not touching the cache at all,
when the leases of the LHS and RHS were collocated at merge time, or we
were bumping the RHS's ts cache up to the freeze point otherwise
(because, in this case, the RHS's ts cache info has been lost).  This
patch goes further: now we'll bump the RHS ts cache up to the RHS closed
timestamp on the argument the the RHS's closed timestamp is lost.

This patch is needed by the effort to move closed timestamp to be
per-range instead of per-store, and also to have future-time closed
timestamps. Today, the new ts cache bump is not necessary for a fairly
subtle reason: if the pre-merge leases are collocated,, then the closed
ts of the RHS is not "lost" because it's the same as the one of the LHS.
If the leases are not collocated, the freeze time of the RHS is
certainly above its closed ts. So, in either case, the current code
doesn't lead to the possibility of accepting write post-merge that
invalidate previous follower reads.

The RHS' closed timestamp is plumbed from the freeze to the merge
through subsume response.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/helpers_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTILv-Z1nTN88QBjk8d:-MTILv-Z1nTN88QBjk8e:bfvlcsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/813a1c1e148fd1f68eda3fb70dbb87f1b1fbc238/pkg/kv/kvserver/helpers_test.go#L293)):*
> ```Go
> }
> 
> // MaxClosed returns the maximum closed timestamp known to the Replica.
> ```

What's the point of this test method now?
___
*[pkg/kv/kvserver/replica.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIM33z5xm03VGYZN4k:-MTIM33z5xm03VGYZN4l:b-qhkf32) ([raw file](https://github.com/cockroachdb/cockroach/blob/813a1c1e148fd1f68eda3fb70dbb87f1b1fbc238/pkg/kv/kvserver/replica.go#L404)):*
> ```Go
> 		lastReplicaAdded     roachpb.ReplicaID
> 		lastReplicaAddedTime time.Time
> 		// initialMaxClosed is the initial MaxClosedTimestamp timestamp for the replica as known
> ```

Did you mean to change this?
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTINwhX2NOTrPRt1WlW:-MTINwhY4k-GdPpOqa4H:bavku1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/kv/kvserver/batcheval/cmd_subsume.go#L171)):*
> ```Go
> 	reply.LeaseAppliedIndex = lai
> 	reply.FreezeStart = cArgs.EvalCtx.Clock().NowAsClockTimestamp()
> 	closedTS, ok := cArgs.EvalCtx.MaxClosedTimestamp(ctx)
> ```

This seems correct for when we have per-range closed timestamps, but it is correct with the current system? Is it possible that we have already proposed a higher closed timestamp on the current side-transport but haven't yet reflected that in `MaxClosedTimestamp`? I wonder if we should just return `false` for this method if we haven't started using per-range closed timestamps on this range.
___
*[pkg/roachpb/api.proto, line 1661 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIOd5r5C1n3HtvZifC:-MTIOd5r5C1n3HtvZifD:b-b98vtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/roachpb/api.proto#L1661)):*
> ```protobuf
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/util/hlc.ClockTimestamp"];
> 
>   // ClosedTS is the range's closed timestamp at the moment of the subsumption.
> ```

nit: name this `closed_timestamp`, like it's named in the `RangeInfo` and `Entry` structs.
___
*[pkg/roachpb/data.proto, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIOq3Y8rWL6ZNSxPRg:-MTIOq3Y8rWL6ZNSxPRh:b-dwer7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/roachpb/data.proto#L161)):*
> ```protobuf
>   // bump the timestamp cache for the keys previously owned by the subsumed
>   // range.
>   util.hlc.Timestamp right_closedTS = 6 [(gogoproto.nullable) = false];
> ```

Same point about naming. `right_closed_timestamp`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59854)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/helpers_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTILv-Z1nTN88QBjk8d:-MTMrIJL-YDjWvuwhj9C:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/813a1c1e148fd1f68eda3fb70dbb87f1b1fbc238/pkg/kv/kvserver/helpers_test.go#L293)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's the point of this test method now?
</blockquote></details>

removed
___
*[pkg/kv/kvserver/replica.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIM33z5xm03VGYZN4k:-MTMr0Xm1X8QinJO6P4g:b32wsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/813a1c1e148fd1f68eda3fb70dbb87f1b1fbc238/pkg/kv/kvserver/replica.go#L404)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to change this?
</blockquote></details>

no
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTINwhX2NOTrPRt1WlW:-MTNJIKd1e7KQY7Xxn6k:bs8a7co) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/kv/kvserver/batcheval/cmd_subsume.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems correct for when we have per-range closed timestamps, but it is correct with the current system? Is it possible that we have already proposed a higher closed timestamp on the current side-transport but haven't yet reflected that in `MaxClosedTimestamp`? I wonder if we should just return `false` for this method if we haven't started using per-range closed timestamps on this range.
</blockquote></details>

In light of this, I've moved this patch to #59854, and made this code use a new `FrozenClosedTimestamp`, different from `MaxClosedTimestamp`.
___
*[pkg/roachpb/api.proto, line 1661 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIOd5r5C1n3HtvZifC:-MTNJGVz5T9q56JCTe9A:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/roachpb/api.proto#L1661)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: name this `closed_timestamp`, like it's named in the `RangeInfo` and `Entry` structs.
</blockquote></details>

done
___
*[pkg/roachpb/data.proto, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59854#-MTIOq3Y8rWL6ZNSxPRg:-MTNJHHb5-PSAa3J2Vv3:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ba2d88cf765c5fb167a2380435c45300d13cfbf/pkg/roachpb/data.proto#L161)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same point about naming. `right_closed_timestamp`.
</blockquote></details>

done

**Comment by andreimatei** [comment]
moved to #59854

**Comment by andreimatei** [comment]
Sorry, moved to #59566

**Pull request closed without merging**
