### PR TITLE
Removed AddRange() from the stores public API. Added a method AddRang…

### PR DESCRIPTION
**Pull request by vivekmenezes**
…eTest() to accommodate one external test.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
This PR given you a sense for what calls AddRangeTest and what calls addRange. I've like to call it one name and merge it in. But I was wondering if you had any ideas on how we can make this a pure private method. Thanks

**Comment by tamird** [comment]
Looks like `AddRange` is never used outside of tests?

**Comment by vivekmenezes** [comment]
That's why I'd like to take it out. But simply changing it to addRange() is
insufficient. See the two callers that call AddRangeTest()

**Comment by tamird** [comment]
Right; I meant that there seems to be no point in unexporting `AddRange` and then adding `AddRangeTest` which has identical behaviour.

I'd just remove `AddRange` from the `rangeManager` interface and add a comment like https://github.com/cockroachdb/cockroach/pull/976/files#diff-da8e1e05c0b956041095f9bddf67aea0R133

**Comment by bdarnell** [comment]
I think renaming the method is worthwhile; the existence of `AddRange` is confusing since it's not normally used. However, we do not need both an exported `AddRangeTest` and an unexported `addRange` (in addition to `addRangeInternal`, which is the important one): just call `AddRangeTest` from all tests that need it whether they're in the same package or not.

**Comment by vivekmenezes** [comment]
Ready for another look

**Comment by tamird** [comment]
LGTM

**Pull request merged**
