### PR TITLE
colexec, colflow: minor refactor of vectorized stats collection

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit moves some of the logic of vectorized stats collection from
`colflow` into `colexec` package. It also adds support for collecting
stats on the streams of the vectorized flow.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Does adding these stream stats give us any new information?

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47347#-:-M5wNEvX1XVi1QHu9OT2:bl1hcyp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
Yep, check this out (when your mouse points at a stream, similar to what we have in the rowexec):
Screen Shot 2020-04-27 at 9 17 09 AM

**Comment by asubiotto** [comment]
Right, but in rowexec we have some more information (e.g. number of bytes sent over the wire). Based on what I've seen here we display the same stats as the upstream operator (i.e. batches, tuples etc...). I guess my question is whether there are cases where this provides us with more information than we already have?

**Comment by yuzefovich** [comment]
Yeah, we don't get any new information with this PR, but I think it's still a nice cleanup, and addition of special outbox stats probably can be done in a follow-up work.

**Comment by asubiotto** [comment]
OK. Could you please add a TODO and create an accompanying issue?

**Review by yuzefovich — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47347#-:-M60Sv-fBivGOL4tSdmr:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47347#-:-M60Ti4UBW4amH7MtOFp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
